### ISSUE TITLE
streaming (repairs and bootstrap) manage their resources badly

### ISSUE THREAD

**Issue by glommer** [scylladb/scylladb#1002]
Repairs and bootstrap faces the same problems other actors in scylla face: how to do as much work as possible, without using up too much resources.

But the way they solve it is sub-optimal, and not in line with other instances of the same problem over our code base. A simple semaphore is used to limit parallelism to X, where X is a magic number.

This approach has the problem of not enabling us to do enough work in boxes where more parallelism could be used, and conversely doing too much in machines and workloads where we have less resources available for the task.

**Comment by penberg** [comment]
For future reference, here's a hack we merged on the issue:

https://github.com/scylladb/scylla/commit/2cd756ae5e64d3dac42e6a5f707c72b39995cbda

**Comment by slivne** [comment]
@asias
- is there any limitation on streaming bandwidth / parallelism today, or is it only caped in cpu/disk by the schedulers ?
- with regards to repair - we are moving to row level repair - we should revisit this once its fully integrated.

**Comment by slivne** [comment]
@asias to see if we have resolved this with the new streaming / repair - can you provide info on how we manage resources / compute parallelism for streaming and repair.

I know that streaming has been changed (a while back) I am not aware of resource management issues related to streaming - but maybe there are. Can you list areas where you expect issues (and the next ask will be can you actually push the system to these point).

Row level repair I know we had additional patches that went into 3.2 / master to make row level repair more restrained and more efficient. Can you list areas where you expect issues (and the next ask will be can you actually push the system to these point).

**Comment by asias** [comment]
The original issue "A simple semaphore is used to limit parallelism to X, where X is a magic number." was solved when when switching to the seastar streaming interface long time ago.  I think we should close this issue.

I think we will not do more work on streaming and we will focus on repair.

For repair, we have CPU and  DISK scheduler to limit the amount of resources that can be used by repair. We limit the MEMORY usage by repair at most 10% of shard memory.  We do not have NETWORK scheduler to limit the network usage.
