### ISSUE TITLE
SSTable readers of large partitions use at least 32 KiB IO size

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#10030]
The data file input stream is using buffer size of 128 KiB. Seastar's dynamic IO adjustments mechanism is setting the minimum buffer size to 1/4 of that:

```c++
    size_t minimal_buffer_size() const {
        return std::min(std::max(_options.buffer_size / 4, size_t(8192)), _options.buffer_size);
    }
``` 

So minimal_buffer_size() will be 32 KiB.

SSTable readers which want to read a single row from a partition which has a clustering index will narrow down data file range with the accuracy of column_index_size_in_kb (64 KiB by default). So the minimal buffer size doesn't hurt the default clustering index accuracy. However, users may want to increase the accuracy of the index in order to reduce IO overhead. This will not be effective currently. Even though the index is more selective, the reader will still use 32 KiB IO size.

One way to fix this is to lower the minimum buffer size of the dynamic adjustments and let them settle on the optimal size.

Another way is to use the information in the index to narrow down data file range which is read.

**Comment by bhalevy** [comment]
@tgrabiec what's the severity of this issue, what's the extent of its affect?

**Comment by mykaul** [comment]
I wonder how important it is - for two completely different use cases - NVMe's on one hand, which are perfectly happy with small random reads (4/8K or so) and on the very far end of the scale - object storage, which may be happier with smaller reads as well. (Lastly, EBS optimal IO size is 16KB).
