### ISSUE TITLE
database: read related metrics are out-of-date w.r.t. the underlying implementation

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#10065]
`replica::database` exports the following metrics:
* active_reads
* queued_reads
* paused_reads
* paused_reads_permit_based_evictions
* reads_shed_due_to_overload

For each semaphore class: `user`, `streaming` and `system`. Our recent rework of the reader concurrency control, in particular 3d816b7c16 changed the meaning of some of these metrics significantly, to the point where they don't fulfill their previous function. To be clear there is nothing incorrect with the metrics themselves: they might need a touch-up for their description but they are largely OK. The problem is in how these metrics were and are still interpreted and used, in particular in Graphana: `active_reads` and `queued_reads` for example used to mean reads that have gone to the disk (and hence missed in cache) and reads that want to go to the disk but can't because the disk is overloaded. These metrics were used as badness metrics: them being non-zero (especially the `queued_reads`) was used to explain high latencies. Since the semaphore was moved to in front of the cache they cannot be used in this quality anymore: `active_reads` simply means reads that passed admission and is actively executing. It says nothing about where it is reading from: cache or disk. `queued_reads` simply means reads that are waiting for admission. With the new admission algorithm we expect reads to be queued much more commonly -- a non-zero `queued_reads` is normal -- so in some respect this metric also lost its "badness" status.
We need to at the very least update the metric descriptions and update them and update Graphana too. Ideally we want to restore the badness metrics: we should introduce a counter for reads that are currently reading from disk, as this is a very useful metric to have.

**Comment by raphaelsc** [comment]
@denesb another metric we shoud have is # of sstable readers. today, when debugging OOM, we don't exactly how many readers exist until we peek into the coredump right? # of sstable reader is also a great indicator for read amplification issues, so we can correlate it with compaction falling behind or bad stratetegy settings.

**Comment by denesb** [comment]
Yes, I agree something like this would be nice to have. There is no such stat maintained today but it is easy to add one. While at it, we can add a metric for cache and memtable readers. Then we could immediately spot if there is a problem with too many sstables.

**Comment by amnonh** [comment]
@denesb @raphaelsc could you open a scylla-monitoring issue with the correct explenation?

**Comment by denesb** [comment]
> @denesb @raphaelsc could you open a scylla-monitoring issue with the correct explenation?

This requires changes in scylla code too. We need to do the changes on the scylla end to find out what needs to change in monitoring.

**Comment by denesb** [comment]
For example I think we will want the old "queued sstable reads" and "active sstable reads" in their old meaning back. Currently, this requires code changes as these things are simply not tracked. So it is even more than just hooking up a different existing internal metric to the outside-facing one.

**Comment by denesb** [comment]
> Doesn't look like something we'll backport (or need to).

No, I don't think we need to (or should).
