### ISSUE TITLE
scylla_cpuset_setup: make it idempotent

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylladb#10121]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

When you run cpuset setup, it ALWAYS deletes perftune.yaml - https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_cpuset_setup#L36
It shouldn't do it in case the cpuset.conf didn't really change.

Motivation is that ansible role is reentrant and idempotent - and it uses the cpuset to properly set cpuset
https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-node/tasks/common.yml#L196
and after you rerun the role, it shouldn't delete perftune.yaml, if the cpuset didn't change to stay idempotent

**Comment by vladzcloudius** [comment]
The patch above doesn't fix the the problem and introduces a regression: https://github.com/scylladb/scylladb/issues/11385

**Comment by vladzcloudius** [comment]
The patch above doesn't fix the issue because it can trigger `perftune.yaml` deletion if some irrelevant change has been done to `scylla-server` configuration file.

Additional info can be found here: https://github.com/scylladb/scylladb/issues/11385

**Comment by denesb** [comment]
No backporting required, fixes already present in 5.1+.
