### ISSUE TITLE
[tools/scylla-sstable] more flexibility for obtaining the schema

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#10126]
The ability to read the schema from a `schema.cql` is great when getting sstables from a user as part of an investigation. This allows for much flexibility on where the tool can be run.
However in some cases the examined sstables are located inside a standard scylla data directory, which also contains the schema tables with the definitions of all the schemas. In these cases it would be great if the tool could just read the schema tables and obtain the schema from there.
On a similar note it would be great if `schema.cql` would be allowed to contain more then one table definitions. When this is the case we could try to parse the keyspace/table from the sstable path, or alternatively ask user to specify it with a new flag.

The overarching idea here is to shorten the number of necessary steps required to inspect an sstable. The current way of a required `schema.cql` with a single table definition works well and covers all use cases, but in some cases requires extra steps that could be avoided leading to a more streamlined experience.

**Comment by denesb** [comment]
0d5fd526a5 added a way to use schemas of built-in tables, based on their name.

**Comment by mykaul** [comment]
Is there more to this issue?

**Comment by denesb** [comment]
> Is there more to this issue?

Yes, I plan on adding support for discovering and reading schema tables from the disk, just like `sstabledump` does.

**Comment by nyh** [comment]
@denesb you reverted this commit in https://github.com/scylladb/scylladb/pull/13419 so I'm reopening the issue

**Comment by avikivity** [comment]
Not a bug, not backporting.
