### ISSUE TITLE
Allow distributing user-defined aggregates

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#10215]
Following the idea described and implemented in https://github.com/scylladb/scylla/pull/9209 , let's allow distributing more complex computations than just count(*) - namely, user-defined aggregates.
Not all user-defined aggregates can be easily distributed, so for starters the scope should be reduced to commutative ones - so, in particular, we may need a way to mark some functions/aggregates as having this characteristic.

This is an umbrella issue, because the scope is quite big and more granular sub-issues are likely to be created.

**Comment by nyh** [comment]
> Following the idea described and implemented in #9209 , let's allow distributing more complex computations than just count(*) - namely, user-defined aggregates. Not all user-defined aggregates can be easily distributed, so for starters the scope should be reduced to commutative ones - so, in particular, we may need a way to mark some functions/aggregates as having this characteristic.

Unless I'm missing something, the aggregates are already fed data in basically random partition order, so what would be the point of a user having a non-commutative aggregate? I'm not saying it's impossible to invent a non-commutative aggregate, what I'm saying that the use should already expect that the data be given to this aggregation function in random order. All we need to do is to clearly say that unlike "SELECT *" which has a repeatable (though random-looking) order, this repeatability is not guaranteed in UDAs. Would anyone object if we say that? Is there any reason why a user might need data to be fed into a UDA in repeatable order?

**Comment by Jadw1** [comment]
Closing the issue. It has been resolved by this https://github.com/scylladb/scylladb/pull/10295
