### ISSUE TITLE
seastar::gate_closed_exception and error applying view update when stopping migration service

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#10217]
*Installation details*
Kernel version: `5.11.0-1028-aws`
Scylla version (or git commit hash): `5.1.dev-0.20220303.0544973b15dd with build-id 3b69cb8b4d61d8190175613119fcc982a0b5eddb`
Cluster size: 3 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-050e5a4fbd1175aa3` (aws: eu-west-1)

Scylla running with shards number (live nodes):
   gemini-1tb-10h-master-db-node-dfd0facd-1 (52.215.207.192 | 10.0.1.29): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-5 (54.246.227.25 | 10.0.3.173): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-6 (34.241.254.50 | 10.0.2.172): 14 shards
Scylla running with shards number (terminated nodes):
   gemini-1tb-10h-master-db-node-dfd0facd-3 (54.74.33.231 | 10.0.2.208): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-4 (54.78.3.38 | 10.0.2.12): 14 shards
   gemini-1tb-10h-master-db-node-dfd0facd-2 (34.244.27.104 | 10.0.2.230): 14 shards

Gemini command:
`/$HOME/gemini -d --duration 8h --warmup 2h -c 50 -m mixed -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --oracle-replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '1'}" --test-cluster=10.0.1.29,10.0.2.230,10.0.2.208 --outfile /home/centos/gemini_result_972a80f3-7b38-4c35-9cbe-9811563ddd43.log --seed 32 --oracle-cluster=10.0.1.67 `
Gemini version: `1.7.5`

Test: `gemini-1tb-10h`
Test name: `gemini_test.GeminiTest.test_load_random_with_nemesis`
Test config file(s):
- [gemini-1tb-10h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/c739275ca255f2fc2902a6496d3fbaae38b10012/test-cases/gemini/gemini-1tb-10h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/c739275ca255f2fc2902a6496d3fbaae38b10012/test-cases/gemini/gemini-1tb-10h.yaml&source=gmail-html&ust=1647419196287000&usg=AOvVaw17byBvcyBSNzY5NNQNLmV7))

**Issue description**

```
< t:2022-03-11 09:56:19,751 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-11 09:56:19.749: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=32833588-e68f-4d5c-b4cd-d75657cfd7dd: nemesis_name=RepairStreamingErr target_node=Node gemini-1tb-10h-master-db-node-dfd0facd-4 [54.78.3.38 | 10.0.2.12] (seed: False)
```

During RepairStreamingErr nemesis repair was interrupted by instance hard reboot
```
< t:2022-03-11 10:12:22,856 f:nemesis.py      l:2774 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.GeminiChaosMonkey: Interrupt the task by hard reboot
```

When migration service was stopped:
```
< t:2022-03-11 10:14:34,540 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-03-11T10:12:26+00:00 gemini-1tb-10h-master-db-node-dfd0facd-4 !    INFO |  [shard 11] migration_manager - stopping migration service
```

Got exceptions, like:
```
2022-03-11T10:12:35+00:00 gemini-1tb-10h-master-db-node-dfd0facd-4 !     ERR |  [shard 7] view - Error applying view update to 10.0.2.12 (view: ks1.table1_col6_idx_index, base token: -5010111858101061436, view token: 6440814261652291722): std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1_col6_idx_index (pk{00042115d36c}) to commitlog): seastar::gate_closed_exception (gate closed)

2022-03-11T10:12:35+00:00 gemini-1tb-10h-master-db-node-dfd0facd-4 !     ERR |  [shard 7] view - Error applying view update to 10.0.2.12 (view: ks1.table1_mv_0, base token: -5010111858101061436, view token: -2470919840309646346): std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1_mv_0 (pk{03d5524d3939666531355a55343351344464664832416d6e6a696a755a4d477345686732496366392b595571777731586c734646516f53466f344177474c7244683843634f5337415159784f6553494b6d2f6e4c322f763246734a7050532b63493753483947307167384d786e6341422b3043577757675335436f56583050654f4e363836624e624448562b70656b3057576d4e64774e4d79753368617262707a494a64504466595651723558386a6d2f2b54443371586c4c7a514330794a3745784e6d6f4b6b4f3449667867485a4332663243647a3242697157346c36626671596f6a7376447150794b3675714e54492f644865496a383876334d52766f764c4c392f6a49746178464c5663345a7342706e4165306570443779664a4b74786779783233527950544e523464386e49486846474d326d5751726e72486e4b5264493764484465624c2f4b6f4541575972495a455770572b6667673674525370686355625a417961437a7a61784164672f7878744e55436a716d585967755843444e316e42736d56536a774867747a54544a42423246354a636f377663506e794c73693450457a66456670302b44784b46724b50506c4c6f644c55516c48354b574f42717a3445377057497776516477544436375475584a66586f53524c71446e574e466265722b61694b4a746e6a3137766c6b5677676877396a4e6d49533834514c534f416478336c304a61377a6d656c4d4364746e315a38706665442f51374a4862303475377764787546574d51304b6e504d4f415a74715a7672544d7763676d5344345064716363536d657649735541616433536b703363594e484a586c59306c4f6e445065443345596a47456c4c734250665831732b4c762f2f7072734b7670573969764c5249634f45572f66313043506d6764516156626966636369593654424c766641305252654e744c3366654b3076676c2b6e597367346a755861693437364f483679704c4b366b727857544f2b72423847386d5864514965307132384731435148665a32613935307953304c49517a46726531724e556c764b44516c4a33486b6d6e454a655857507141587246576437307265397a39734d4f514230586354544e6f32497362566a464f53417974714b364679345675782b39417753656d7448534b78432b4b633266563077494f782b3763516454796f58754331457942426e52723149483336647a303064543478355569526d704252555170644663707978706147615a713372542f7770577268366e6f655735623051394479483961594e46394b6b48424a4a677a774a555a625a42756453663459626f554731504b6f48656f6e61684358534666325a6c534d0004028a13f1000835d6a0ec9437882f00083c3bb185d70c1b0d00016c}) to commitlog): seastar::gate_closed_exception (gate closed)

2022-03-11T10:12:35+00:00 gemini-1tb-10h-master-db-node-dfd0facd-4 !     ERR |  [shard 1] view - Error applying view update to 10.0.2.12 (view: ks1.table1_mv_0, base token: -4908554026030169129, view token: 575631968853645206): std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1_mv_0 (pk{01295539784c55364e5a7a674577795a596b65636833385849304c7958666d397077383863597846524f79316a514b594373507478696f643037797a48416932306649374d716b574735475366367443647a534f746e45614954562f662b4e6454584e5531444948515859427439763348507159667838557a68366963534436374c4352644b614f39643768396c58445932765051376f51496978564765357255584c396545564b52535a364341583648527a3631786c75762b7a535236786e443239674c4d436d523758763649706b6749574b6d362f324a693444396f4c517a4b6c366c6336673278412b4c417568653979455645656f6e764f4d524a2f70716c52746d3630384a43304974425a37766c5434324f45664477686544526a415951644c393135454d5567000463d99b9b000850be4658792b625600086348967f51bd766c000122}) to commitlog): seastar::gate_closed_exception (gate closed)

2022-03-11T10:12:35+00:00 gemini-1tb-10h-master-db-node-dfd0facd-4 !     ERR |  [shard 7] view - Error applying view update to 10.0.2.12 (view: ks1.table1_col5_idx_index, base token: -5010111858101061436, view token: -2236684040309286292): std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1_col5_idx_index (pk{000c00000003624cb406f6de11dc}) to commitlog): seastar::gate_closed_exception (gate closed)
```

I suppose it's expected exceptions. Or not?

Restore Monitor Stack command: `$ hydra investigate show-monitor dfd0facd-6f45-41fb-b5fb-c289529348e7`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=dfd0facd-6f45-41fb-b5fb-c289529348e7](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmaster%26test_id%3Ddfd0facd-6f45-41fb-b5fb-c289529348e7&source=gmail-html&ust=1647419196287000&usg=AOvVaw19Nd_gFHvDeu-V6Nfb61ue))
Show all stored logs command: `$ hydra investigate show-logs dfd0facd-6f45-41fb-b5fb-c289529348e7`

Test id: `dfd0facd-6f45-41fb-b5fb-c289529348e7`

Logs:

db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/db-cluster-dfd0facd.tar.gz)&source=gmail-html&ust=1647419196288000&usg=AOvVaw12MtVjwT4bRqWlPUNPWWh_)

sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dfd0facd-6f45-41fb-b5fb-c289529348e7/20220311_150645/sct-runner-dfd0facd.tar.gz)&source=gmail-html&ust=1647419196288000&usg=AOvVaw0uwgeMMnnVAxP6oDvRkxm3)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/148/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-1tb-10h/148/&source=gmail-html&ust=1647419196288000&usg=AOvVaw1zjSZfWoi6a0qFK3oObbZI))

**Comment by bhalevy** [comment]
> I suppose it's expected exceptions. Or not?

Eventually, we're cleaning up the shutdown process slowly so services would be shut down cleanly so it won't happen.

**Comment by juliayakovlev** [comment]
Reproduced with `2022.1~rc3`

```
< t:2022-04-13 07:55:55,305 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-13T07:53:53+00:00 longevity-mv-si-4d-2022-1-db-node-b8f84a1a-7 !    INFO |  [shard 13] migration_manager - stopping 
migration service
< t:2022-04-13 07:55:55,306 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-13T07:53:59+00:00 longevity-mv-si-4d-2022-1-db-node-b8f84a1a-7 !     ERR |  [shard 13] view - Error applying view up
date to 10.0.2.223 (view: mview.users_by_first_name, base token: -3562495931180614819, view token: -8327979940312790031): std::_Nested_exception<std::runtime_error> (Could not write mutation mview:users_by_first
_name (pk{00051266665106}) to commitlog): seastar::gate_closed_exception (gate closed)
< t:2022-04-13 07:55:55,306 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-04-13T07:53:59+00:00 longevity-mv-si-4d-2022-1-db-node-b8f84a1a-7 !     ERR |  [shard 13] view - Error applying view up
date to 10.0.2.223 (view: mview.users_by_last_name, base token: -3562495931180614819, view token: 4063372438403984359): std::_Nested_exception<std::runtime_error> (Could not write mutation mview:users_by_last_na
me (pk{0005776d327d1a}) to commitlog): seastar::gate_closed_exception (gate closed)
```

## Installation details

Kernel Version: 5.13.0-1021-aws

Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`

Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-9 (13.48.67.166 | 10.0.0.248) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-8 (13.53.126.151 | 10.0.0.11) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-7 (13.51.238.109 | 10.0.2.223) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-6 (13.51.178.96 | 10.0.3.173) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-5 (16.16.27.239 | 10.0.3.181) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-4 (13.51.176.206 | 10.0.2.227) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-3 (16.16.66.187 | 10.0.2.212) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-22 (13.53.122.214 | 10.0.1.168) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-21 (16.170.158.251 | 10.0.1.93) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-20 (16.170.162.125 | 10.0.1.163) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-2 (16.170.158.106 | 10.0.2.134) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-19 (16.171.64.185 | 10.0.0.25) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-18 (16.170.158.196 | 10.0.3.173) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-17 (13.48.26.249 | 10.0.3.190) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-16 (13.49.21.53 | 10.0.1.125) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-15 (16.16.65.81 | 10.0.2.216) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-14 (13.49.75.75 | 10.0.2.242) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-13 (16.170.221.229 | 10.0.2.130) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-12 (16.170.141.199 | 10.0.3.55) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-11 (13.49.245.75 | 10.0.3.150) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-10 (13.53.126.35 | 10.0.2.79) (shards: 14)
- longevity-mv-si-4d-2022-1-db-node-b8f84a1a-1 (16.170.141.63 | 10.0.1.166) (shards: 14)


OS / Image: `ami-001615890d21c8784` (aws: eu-north-1)


Test: `longevity-mv-si-4days-test`

Test id: `b8f84a1a-eb19-4b48-8f72-f9d86b51338f`

Test name: `longevity/longevity-mv-si-4days-test`

Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7f5f150f522fd17c764c1b64e1a8f750c7a8cf18/test-cases/longevity/longevity-mv-si-4days.yaml)


- Restore Monitor Stack command: `$ hydra investigate show-monitor b8f84a1a-eb19-4b48-8f72-f9d86b51338f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b8f84a1a-eb19-4b48-8f72-f9d86b51338f)
- Show all stored logs command: `$ hydra investigate show-logs b8f84a1a-eb19-4b48-8f72-f9d86b51338f`



## Logs:
- **db-cluster-b8f84a1a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/db-cluster-b8f84a1a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/db-cluster-b8f84a1a.tar.gz)
- **monitor-set-b8f84a1a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/monitor-set-b8f84a1a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/monitor-set-b8f84a1a.tar.gz)
- **loader-set-b8f84a1a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/loader-set-b8f84a1a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/loader-set-b8f84a1a.tar.gz)
- **normal-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/normal-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/normal-b8f84a1a.log.tar.gz)
- **summary-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/summary-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/summary-b8f84a1a.log.tar.gz)
- **events-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/events-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/events-b8f84a1a.log.tar.gz)
- **output-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/output-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/output-b8f84a1a.log.tar.gz)
- **debug-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/debug-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/debug-b8f84a1a.log.tar.gz)
- **sct-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/sct-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/sct-b8f84a1a.log.tar.gz)
- **error-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/error-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/error-b8f84a1a.log.tar.gz)
- **critical-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/critical-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/critical-b8f84a1a.log.tar.gz)
- **raw_events-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/raw_events-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/raw_events-b8f84a1a.log.tar.gz)
- **warning-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/warning-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/warning-b8f84a1a.log.tar.gz)
- **email_data-b8f84a1a.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/email_data-b8f84a1a.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/email_data-b8f84a1a.json.tar.gz)
- **argus-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/argus-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/argus-b8f84a1a.log.tar.gz)
- **left_processes-b8f84a1a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/left_processes-b8f84a1a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b8f84a1a-eb19-4b48-8f72-f9d86b51338f/20220417_023937/left_processes-b8f84a1a.log.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-mv-si-4days-test/2/)

**Comment by juliayakovlev** [comment]
Reproduced with `2022.1~rc3-20220406.5cc3b678c`
https://jenkins.scylladb.com/job/enterprise-2022.1/job/longevity/job/longevity-mv-si-4days-test/4/
Test is still running
Test_id: ee400458-62ee-424f-970e-b57323a09b3c

```
2022-05-02T02:15:11+00:00 longevity-mv-si-4d-2022-1-db-node-ee400458-14 !     ERR |  [shard 8] view - Error applying view update to 10.0.1.16 (view: sec_index.users_initials_ind_index, base token: -3694684769749876596, view token: 6835559088765985505): std::_Nested_exception<std::runtime_error> (Could not write mutation sec_index:users_initials_ind_index (pk{00040000325f}) to commitlog): seastar::gate_closed_exception (gate closed)
```

During RepairStreamingErr nemesis

**Comment by avikivity** [comment]
/cc @nyh @xemul @gleb-cloudius 

By itself, the exception isn't a big problem. We're trying to stop the service and the view update loses the race. We end up with a small view inconsistency.

It's another manifestation of the storage_proxy dependency loop: sp (for base table) -> replica::database -> sp (for views).

The solution should be to have two storage proxies. Then there is no loop: sp -> replica::database -> sp_view.

The stop sequence would then be stop the base storage proxy, drain it, stop the database, stop sp_view.

Of course, it exposes another loop, because the dependency loop is really sp_base -> replica::database -> sp_view -> replica::database. So we need separate replica services too. All in all a large effort for a minor thing, unfortunately.

**Comment by gleb-cloudius** [comment]
On Tue, May 03, 2022 at 05:09:37AM -0700, Avi Kivity wrote:
> The solution should be to have two storage proxies. Then there is no loop: sp -> replica::database -> sp_view.
> 
> The stop sequence would then be stop the base storage proxy, drain it, stop the database, stop sp_view.
> 
You do not need a separate sp for any kind of recursive work. You will
end up with millions of them. To solve the problem the storage proxy may
account for different work separately and have a way to stop top level
requests and internally generated requests separately. So the stop
sequence will be:

co_await sp.stop_cql_requests();
co_await sp.stop_views();
co_await sp.stop_paxos();

etc...

--
			Gleb.

**Comment by xemul** [comment]
The replica::database -> sp (for views) is artificial in some sense. It's only triggered from sp -> database one thus when a database needs to update a view it can return some work for storage proxy instead of recursing into it.

**Comment by nyh** [comment]
I agree with Gleb. I don't understand why we can't begin with **stopping front-ends** (CQL, Alternator, etc. but also RPC writes!) and then stop background processes (TTL, repair, compaction, etc.,) and then finally, when we're sure that no write is in progress, stop the backend objects. Avi, isn't this simpler than your proposal?

There would still be a question of what does "stopping" CQL entail - do we let ongoing writes which can take some more time (e.g., view updates) continue until done, or stop them abruptly? We should probably do the latter, even if it causes slight inconsistency of the base and view (we'll have the same inconsistency on poweroff, anyway). But if we want to make a bigger effort we can also let these requests continue until timeout if the timeout is reasonable (and if a view update times out, we write a hint, so we'll preserve the consistency).

**Comment by xemul** [comment]
> I agree with Gleb. I don't understand why we can't begin with stopping front-ends

@nyh  -- c17a03727ce593bb4ed6fcad8e178070fb23dc05

**Comment by slivne** [comment]
@nyh / @avikivity / @xemul - ping

**Comment by yarongilor** [comment]
Might reproduced as well in Gemini-3h longevity.
Got many errors during the streaming repair nemesis:
```
2022-05-03 18:58:35.086 <2022-05-03 18:56:40.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=87047c02-330e-486e-b751-346e227ea6df: type=DATABASE_ERROR regex=Exception  line_number=11943 node=gemini-with-nemesis-3h-normal-5-0-db-node-d67bfdb8-2
2022-05-03T18:56:40+00:00 gemini-with-nemesis-3h-normal-5-0-db-node-d67bfdb8-2 !     ERR |  [shard 0] view - Error applying view update to 10.0.1.227 (view: ks1.table1_col10_idx_index, base token: -3308343448415804717, view token: 5966732715267908131): std::_Nested_exception<std::runtime_error> (Could not write mutation ks1:table1_col10_idx_index (pk{000c000000034d34824565fe6691}) to commitlog): seastar::gate_closed_exception (gate closed)
```


## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.0~rc3-20220503.3e98e17d1` with build-id `9bb31d710ed5084b792891adbae7c4144484501f`
Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-with-nemesis-3h-normal-5-0-oracle-db-node-d67bfdb8-1 (3.239.179.133 | 10.0.0.120) (shards: 2)
- gemini-with-nemesis-3h-normal-5-0-db-node-d67bfdb8-3 (3.236.37.216 | 10.0.0.76) (shards: 2)
- gemini-with-nemesis-3h-normal-5-0-db-node-d67bfdb8-2 (54.236.62.0 | 10.0.1.227) (shards: 2)
- gemini-with-nemesis-3h-normal-5-0-db-node-d67bfdb8-1 (3.239.239.157 | 10.0.3.222) (shards: 2)


OS / Image: `ami-086343078ffe88520` (aws: us-east-1)

Test: `gemini-3h-with-nemesis-test`
Test id: `d67bfdb8-3693-43b5-9e29-962e4ab5782b`
Test name: `scylla-5.0/gemini-/gemini-3h-with-nemesis-test`
Test config file(s):

- [gemini-3h-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/62186fccc8ee0c02ba7e1ce6a10f12b8e358eabb/test-cases/gemini/gemini-3h-with-nemesis.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor d67bfdb8-3693-43b5-9e29-962e4ab5782b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d67bfdb8-3693-43b5-9e29-962e4ab5782b)
- Show all stored logs command: `$ hydra investigate show-logs d67bfdb8-3693-43b5-9e29-962e4ab5782b`

## Logs:
- **db-cluster-d67bfdb8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/db-cluster-d67bfdb8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/db-cluster-d67bfdb8.tar.gz)
- **monitor-set-d67bfdb8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/monitor-set-d67bfdb8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/monitor-set-d67bfdb8.tar.gz)
- **loader-set-d67bfdb8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/loader-set-d67bfdb8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/loader-set-d67bfdb8.tar.gz)
- **sct-runner-d67bfdb8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/sct-runner-d67bfdb8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/sct-runner-d67bfdb8.tar.gz)
- **parallel-timelines-report-d67bfdb8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/parallel-timelines-report-d67bfdb8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d67bfdb8-3693-43b5-9e29-962e4ab5782b/20220503_195051/parallel-timelines-report-d67bfdb8.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/gemini-/job/gemini-3h-with-nemesis-test/8/)

**Comment by DoronArazii** [comment]
@xemul any news for this issue?

**Comment by slivne** [comment]
@nyh / @avikivity / @xemul - ping

**Comment by xemul** [comment]
No news.

**Comment by bhalevy** [comment]
This issues shouldn't be labeled as `high` since other than the error printout during shutdown the issue is benign, causing no data consistency nor availability issues.

**Comment by juliayakovlev** [comment]
The issue were not reproduced with `5.0~rc8-20220612.f28542a71` (https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-mv-si-4days-test/3/)

**Comment by bhalevy** [comment]
Looks like this issue can be closed for now.
Nothing to work on.
