### ISSUE TITLE
Allow listing all inherited service level attributes for a role

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylladb#10222]
The current implementation of Service Levels allows the users to list Service Levels attached directly to a Role. However the user can also grant other roles with attached Service Levels to a Role and there is no straightforward way of listing these. For example in the following scenario:

1) create Service Level "A" with timeout=40ms
2) attach SL "A" to Role A
3) create Service Level "B" with timeout=10ms
4) attach SL "B" to Role B
5) Grant Role B to Role A

the effective timeout for Role A would be 10ms (inherited from Role B) IIUC, but when listing the Service Levels for Role A using `LIST ATTACHED SERVICE_LEVEL OF ROLE A` the user will only receive information about SL "A" with a timeout of 40ms.
From reading old `dtest` code I see we used to support `LIST SERVICE_LEVEL OF <role>` that seemed to list all SLs attached to a Role or inherited from granted roles. A different approach would be to use `LIST SERVICE_LEVEL OF <role>` for getting the effective SL attributes for a Role and use something like `LIST ALL SERVICE_LEVELS OF <role>` to get all SLs attached or inherited for a Role.

**Comment by nyh** [comment]
@Jadw1 @kostja does the LIST EFFECTIVE SERVICE LEVEL added in commit 49860952f99ae8bb5266104f3ded8467cb5e24cc for issue #15604 solve this issue and it can be closed?

**Comment by Jadw1** [comment]
Yes, #15604 solves this. Closing
