### ISSUE TITLE
Failed to create *.Ec2Snitch: std::system_error (error system:110, Connection timed out)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#10250]
## Installation details

Kernel Version: 5.13.0-1017-aws

Scylla version (or git commit hash): `5.0~rc2-20220316.839d9ef41` with build-id `1319e7e64335b7e5c7531f773e92ef997b6c51ba`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- alternator-48h-5-0-db-node-048c3c9d-4 (34.252.111.203 | 10.0.2.142) (shards: 14)
- alternator-48h-5-0-db-node-048c3c9d-3 (34.241.22.97 | 10.0.1.81) (shards: 14)
- alternator-48h-5-0-db-node-048c3c9d-2 (54.77.123.158 | 10.0.2.227) (shards: 14)
- alternator-48h-5-0-db-node-048c3c9d-1 (54.155.111.1 | 10.0.0.206) (shards: 14)

OS / Image: `ami-07df681f83cd78172` (aws: eu-west-1)

Test: `longevity-alternator-200gb-48h-test`

Test id: `048c3c9d-c41a-41b7-83c3-6e6930f528ec`

Test name: `longevity/longevity-alternator-200gb-48h-test`

Test config file(s):

- [longevity-alternator-200GB-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/234f79a81bc97d0e44c3ab51441017b646fdf393/test-cases/longevity/longevity-alternator-200GB-48h.yaml)

## Issue description
During `disrupt_repair_streaming_err` node3 AWS instance was rebooted, scylla failed to reboot with the following error:
```
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !     ERR |  [shard 0] snitch_logger - Failed to create org.apache.cassandra.locator.Ec2Snitch: std::system_error (error system:110, Connection timed out)
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down tracing instance
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down tracing instance was successful
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down migration manager notifier
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down migration manager notifier was successful
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down prometheus API server
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down prometheus API server was successful
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down sighup
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO |  [shard 0] init - Shutting down sighup was successful
2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !     ERR |  [shard 0] init - Startup failed: std::system_error (error system:110, Connection timed out)
```

starting scylla manually after that, scylla booted up o.k. 

- Restore Monitor Stack command: `$ hydra investigate show-monitor 048c3c9d-c41a-41b7-83c3-6e6930f528ec`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=048c3c9d-c41a-41b7-83c3-6e6930f528ec)
- Show all stored logs command: `$ hydra investigate show-logs 048c3c9d-c41a-41b7-83c3-6e6930f528ec`

## Logs:
- **db-cluster-048c3c9d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/db-cluster-048c3c9d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/db-cluster-048c3c9d.tar.gz)
- **monitor-set-048c3c9d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/monitor-set-048c3c9d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/monitor-set-048c3c9d.tar.gz)
- **loader-set-048c3c9d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/loader-set-048c3c9d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/loader-set-048c3c9d.tar.gz)
- **sct-runner-048c3c9d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/sct-runner-048c3c9d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/048c3c9d-c41a-41b7-83c3-6e6930f528ec/20220320_163307/sct-runner-048c3c9d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-alternator-200gb-48h-test/2/)

**Comment by slivne** [comment]
Ec2Snitch does a lookup to a metadata service on AWS it needs networking

@syuu1228 / @yarongilor did we change anything in the systemd definition of scylla

```
scyllaadm@ip-172-31-37-61:~$ cat /lib/systemd/system/scylla-server.service
[Unit]
Description=Scylla Server
Wants=scylla-jmx.service
Wants=scylla-housekeeping-restart.timer
Wants=scylla-housekeeping-daily.timer

[Service]
PermissionsStartOnly=true
Type=notify
LimitCORE=infinity
LimitMEMLOCK=infinity
LimitNOFILE=800000
LimitAS=infinity
LimitNPROC=8096
EnvironmentFile=/etc/sysconfig/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf
ExecStartPre=/opt/scylladb/scripts/scylla_prepare
ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET $MEM_CONF
ExecStopPost=/opt/scylladb/scripts/scylla_stop
TimeoutStartSec=1y
TimeoutStopSec=900
KillMode=process
Restart=on-abnormal
User=scylla
OOMScoreAdjust=-950
StandardOutput=syslog
StandardError=syslog
SyslogLevelPrefix=false
Slice=scylla-server.slice

[Install]
WantedBy=multi-user.target
```

I think we had in the past 

```
After=network.target
```

This will not happen on initial boot of the ami since we have another service assuring network will be up


```
scyllaadm@ip-172-31-37-61:~$ cat /lib/systemd/system/scylla-image-setup.service 
[Unit]
Description=Scylla Cloud Image Setup service
Before=scylla-server.service
After=network.target
ConditionPathExists=!/etc/scylla/machine_image_configured

[Service]
Type=oneshot
ExecStart=/opt/scylladb/scylla-machine-image/scylla_image_setup
RemainAfterExit=yes
TimeoutStartSec=900

[Install]
RequiredBy=scylla-server.service
```

can we please check if we changed anything / how do we grantee that scylla starts only after networking is up

**Comment by fruch** [comment]
@slivne seems like it's in a different file
https://github.com/scylladb/scylla/blob/master/dist/common/systemd/scylla-server.service.d/dependencies.conf

**Comment by syuu1228** [comment]
I think it's not because the running order of systemd unit, as @fruch pointed out.
I tried to look into log files, but I couldn't find how it happened.

But it looks like connected to network, since SCT is connected via SSH just 30 secs before "Connection timed out" error:
```
2022-03-20T16:02:00+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !    INFO | Accepted publickey for scyllaadm from 10.0.0.187 port 55532 ssh2: RSA SHA256:1YmYWh7roz4Y3FSY7N8CetmQNlK/K5FeBPITC8KF0u8

...

2022-03-20T16:02:31+00:00 alternator-48h-5-0-db-node-048c3c9d-3 !     ERR |  [shard 0] snitch_logger - Failed to create org.apache.cassandra.locator.Ec2Snitch: std::system_error (error system:110, Connection timed out)
```

**Comment by soyacz** [comment]
It looks it happened again on 2022.2 rc1 when during `MultipleHardReboot` nemesis, after second reboot Scylla startup froze for 2 minutes on `creating snitch` and failed eventually later with `std::system_error (error system:110, Connection timed out)` error:
```
Sep 08 06:58:36 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - Scylla version 2022.2.0~rc1-0.20220902.a9bc6d191031 with build-id 074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda starting ...
[...]
Sep 08 06:58:36 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - starting gossiper
Sep 08 06:58:36 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - seeds={10.12.1.130}, listen_address=10.12.3.29, broadcast_address=10.12.3.29
Sep 08 06:58:36 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - creating snitch
Sep 08 07:00:46 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - Shutting down snitch
Sep 08 07:00:46 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - Shutting down snitch was successful
Sep 08 07:00:46 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - Shutting down gossiper
[...]
Sep 08 07:00:46 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - Shutting down sighup was successful
Sep 08 07:00:46 longevity-1000-keyspaces-increase-db-node-398ad127-6 scylla[1078]:  [shard  0] init - Startup failed: std::system_error (error system:110, Connection timed out)
```

snitch was set to  `org.apache.cassandra.locator.Ec2Snitch`
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc1-20220902.a9bc6d191031` with build-id `074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda`
Cluster size: 6 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-1000-keyspaces-increase-db-node-398ad127-6 (44.192.100.23 | 10.12.3.29) (shards: 30)
- longevity-1000-keyspaces-increase-db-node-398ad127-5 (44.203.6.196 | 10.12.3.116) (shards: 30)
- longevity-1000-keyspaces-increase-db-node-398ad127-4 (44.211.48.81 | 10.12.0.145) (shards: 30)
- longevity-1000-keyspaces-increase-db-node-398ad127-3 (3.239.242.190 | 10.12.2.94) (shards: 30)
- longevity-1000-keyspaces-increase-db-node-398ad127-2 (18.215.124.59 | 10.12.1.54) (shards: 30)
- longevity-1000-keyspaces-increase-db-node-398ad127-1 (44.198.168.237 | 10.12.1.130) (shards: 30)


OS / Image: `ami-0ca7b54e210ff10f6` (aws: us-east-1)

Test: `longevity-multi-keyspaces-60h-test`
Test id: `398ad127-3219-4ad3-b431-5b3f1a586534`
Test name: `enterprise-2022.2/longevity/longevity-multi-keyspaces-60h-test`
Test config file(s):

- [longevity-multi-keyspaces.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/e27da25e5bb5ed0df6e58973e2bc042777d141b9/test-cases/longevity/longevity-multi-keyspaces.yaml)


- Restore Monitor Stack command: `$ hydra investigate show-monitor 398ad127-3219-4ad3-b431-5b3f1a586534`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=398ad127-3219-4ad3-b431-5b3f1a586534)
- Show all stored logs command: `$ hydra investigate show-logs 398ad127-3219-4ad3-b431-5b3f1a586534`

## Logs:
| 20220908_025901 | grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_025901/grafana-screenshot-longevity-multi-keyspaces-60h-test-scylla-per-server-metrics-nemesis-20220908_030058-longevity-1000-keyspaces-increase-monitor-node-398ad127-1.png |
| 20220908_025901 | grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_025901/grafana-screenshot-overview-20220908_025902-longevity-1000-keyspaces-increase-monitor-node-398ad127-1.png                                                             |
| 20220908_081721 | grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_081721/grafana-screenshot-longevity-multi-keyspaces-60h-test-scylla-per-server-metrics-nemesis-20220908_081819-longevity-1000-keyspaces-increase-monitor-node-398ad127-1.png |
| 20220908_081721 | grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_081721/grafana-screenshot-overview-20220908_081721-longevity-1000-keyspaces-increase-monitor-node-398ad127-1.png                                                             |
| 20220908_083348 | critical       | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/critical-398ad127.log.tar.gz                                                                                                                                          |
| 20220908_083348 | db-cluster     | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/db-cluster-398ad127.tar.gz                                                                                                                                            |
| 20220908_083348 | debug          | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/debug-398ad127.log.tar.gz                                                                                                                                             |
| 20220908_083348 | email_data     | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/email_data-398ad127.json.tar.gz                                                                                                                                       |
| 20220908_083348 | error          | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/error-398ad127.log.tar.gz                                                                                                                                             |
| 20220908_083348 | event          | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/events-398ad127.log.tar.gz                                                                                                                                            |
| 20220908_083348 | left_processes | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/left_processes-398ad127.log.tar.gz                                                                                                                                    |
| 20220908_083348 | loader-set     | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/loader-set-398ad127.tar.gz                                                                                                                                            |
| 20220908_083348 | monitor-set    | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/monitor-set-398ad127.tar.gz                                                                                                                                           |
| 20220908_083348 | normal         | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/normal-398ad127.log.tar.gz                                                                                                                                            |
| 20220908_083348 | output         | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/output-398ad127.log.tar.gz                                                                                                                                            |
| 20220908_083348 | event          | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/raw_events-398ad127.log.tar.gz                                                                                                                                        |
| 20220908_083348 | sct            | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/sct-runner.tar.gz                                                                                                                                                     |
| 20220908_083348 | summary        | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/summary-398ad127.log.tar.gz                                                                                                                                           |
| 20220908_083348 | warning        | https://cloudius-jenkins-test.s3.amazonaws.com/398ad127-3219-4ad3-b431-5b3f1a586534/20220908_083348/warning-398ad127.log.tar.gz     

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-multi-keyspaces-60h-test/7/)

**Comment by fruch** [comment]
@syuu1228 I still think the snitch need to be able to retry.

AWS internal API can be busy, for all kind of reason. in the startup script we have retires for it, the snitch should have those too.

**Comment by DoronArazii** [comment]
@syuu1228 what's left to do here?

**Comment by DoronArazii** [comment]
@syuu1228 What's the next step here? Do we have PR?

/Cc @yaronkaikov

**Comment by yaronkaikov** [comment]
> @syuu1228 What's the next step here? Do we have PR?
> 
> /Cc @yaronkaikov

@DoronArazii There is a PR under review for this https://github.com/scylladb/scylladb/pull/11688

**Comment by avikivity** [comment]
This deserves a backport, but will let it stew for a bit first. It appears to be very rare.

**Comment by avikivity** [comment]
Backported to 4.6, 5.0, 5.1.

**Comment by roydahan** [comment]
@yaronkaikov / @avikivity wasn't this back-ported to 2022.2?

**Comment by yaronkaikov** [comment]
@roydahan It was backport after we started `rc4`
