### ISSUE TITLE
Docs: there is no "latest" path

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#10267]
Unlike all other docs projects, we do not have a "latest" path for this project.
Example:
https://scylla.docs.scylladb.com/latest/alternator/alternator.html
return 404
while https://scylla.docs.scylladb.com/master/alternator/alternator.html
do work

**Comment by tzach** [comment]
@dgarcia360 please take a look

**Comment by dgarcia360** [comment]
The URL that does not change is "stable" (not latest) for all projects:

In this project:

- https://scylla.docs.scylladb.com/stable/alternator/alternator.html

Other projects:

- https://sphinx-theme.scylladb.com/stable/
- https://monitoring.docs.scylladb.com/stable/
- https://operator.docs.scylladb.com/stable/
- https://python-driver.docs.scylladb.com/stable/

**Comment by nyh** [comment]
@tzach what does "latest" supposed to point to? Is this the highest-numbered release tag, not including release candidates? Or if not, what will be the rule?
How will the meaning of "latest" differ from "stable" that @dgarcia360 mentioned?

**Comment by tzach** [comment]
It is up to the specific project maintainer, its is not automated.
For scylla, it means the latest GA minor version (so no RC)

BTW, there is an automated version of "latest" which report you are not using the latest version.

**Comment by tzach** [comment]
Done (with "stable" not "latest")
See https://docs.scylladb.com/stable/
