### ISSUE TITLE
system_schema.tables displays data of extensions column in a wrong unclear byte format

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#10309]
*Installation details*
Kernel version: `5.11.0-1028-aws`
Scylla version (or git commit hash): `5.0.rc0-0.20220204.da0cd2b10 with build-id cfe14388a81a0f203b14fd947caadf1f2a1e722f`
Cluster size: 2 nodes (i3.xlarge)
Scylla running with shards number (live nodes):
   toggle-gc-mode-gc-mode--db-node-b83900e6-1 (13.51.47.152 | 10.0.2.34): 4 shards
   toggle-gc-mode-gc-mode--db-node-b83900e6-2 (16.170.146.17 | 10.0.3.59): 4 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-045415ecdee4b63a6` (aws: eu-north-1)

Test: `longevity-large-partition-8h-test_delete_rows_nemesis`
Test name: `longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity`
Test config file(s):
- [longevity-large-partition-8h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/f077b1bcba0453b565116211aaf633c7341c07e8/test-cases/longevity/longevity-large-partition-8h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/f077b1bcba0453b565116211aaf633c7341c07e8/test-cases/longevity/longevity-large-partition-8h.yaml&source=gmail-html&ust=1648819500511000&usg=AOvVaw2HKIGzyZsnFaXv7zrIiFai))

**Issue description**

====================================
Querying the `tables` table `extensions` column shows bad-format/unclear byte value like:
```
cqlsh> ALTER TABLE  scylla_bench.test WITH tombstone_gc = {'mode': 'timeout'};
cqlsh> SELECT keyspace_name, table_name, extensions FROM system_schema.tables where keyspace_name = 'scylla_bench' ;

 keyspace_name | table_name    | extensions
---------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------
  scylla_bench |          test | {'tombstone_gc': 0x02000000040000006d6f64650700000074696d656f75741c00000070726f7061676174696f6e5f64656c61795f696e5f7365636f6e64730400000033363030}
  scylla_bench | test_counters |                                                                                                                                                   {}

(2 rows)
cqlsh> ALTER TABLE  scylla_bench.test WITH tombstone_gc = {'mode': 'repair'};
cqlsh> SELECT keyspace_name, table_name, extensions FROM system_schema.tables where keyspace_name = 'scylla_bench' ;

 keyspace_name | table_name    | extensions
---------------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------
  scylla_bench |          test | {'tombstone_gc': 0x02000000040000006d6f6465060000007265706169721c00000070726f7061676174696f6e5f64656c61795f696e5f7365636f6e64730400000033363030}
  scylla_bench | test_counters |                                                                                                                                                 {}

(2 rows)
```
The expected results is to see something like:
```
scylla_bench |          test | {'tombstone_gc': 'repair'}
```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor b83900e6-f1ff-434b-a268-02a83906ceaf`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=gc_mode_dbg&test_id=b83900e6-f1ff-434b-a268-02a83906ceaf](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dgc_mode_dbg%26test_id%3Db83900e6-f1ff-434b-a268-02a83906ceaf&source=gmail-html&ust=1648819500511000&usg=AOvVaw2zKHT6eRhtVNDvOKTPHyW9))
Show all stored logs command: `$ hydra investigate show-logs b83900e6-f1ff-434b-a268-02a83906ceaf`

Test id: `b83900e6-f1ff-434b-a268-02a83906ceaf`

Logs:
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/db-cluster-b83900e6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/db-cluster-b83900e6.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/db-cluster-b83900e6.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/db-cluster-b83900e6.tar.gz)&source=gmail-html&ust=1648819500511000&usg=AOvVaw0CYsatthjxwnwpn_pamZJl)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/loader-set-b83900e6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/loader-set-b83900e6.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/loader-set-b83900e6.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/loader-set-b83900e6.tar.gz)&source=gmail-html&ust=1648819500511000&usg=AOvVaw28LmxGSIJVbTrYGwqKKx38)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/sct-runner-b83900e6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/sct-runner-b83900e6.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/sct-runner-b83900e6.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b83900e6-f1ff-434b-a268-02a83906ceaf/20220331_082822/sct-runner-b83900e6.tar.gz)&source=gmail-html&ust=1648819500511000&usg=AOvVaw1SFhztW2C-rg2bcmVhiSrm)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/Delete_Rows_4_6/job/longevity-large-partition-8h-test_delete_rows_nemesis/16/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-staging/job/Longevity_yaron/job/Delete_Rows_4_6/job/longevity-large-partition-8h-test_delete_rows_nemesis/16/&source=gmail-html&ust=1648819500511000&usg=AOvVaw3nWVTRucdoki4Jfa-URrk2))

**Comment by yarongilor** [comment]
@asias , can you please advise?

**Comment by avikivity** [comment]
It is probably very difficult to fix now since it involves a schema change.

**Comment by asias** [comment]
The new option uses extensions. Any options uses the extensions are not displayed with the "decoded" content.

**Comment by elcallio** [comment]
The only real option is to teach cqlsh to interpret certain extension tags and deserialize the extension content. But that is not very scalable. And typically only helps users of cqlsh. Which is not exactly the end of all db introspection. 
Extensions are by design black-box opaque...

**Comment by yarongilor** [comment]
> tombstone_gc

But how would a user know what's he's table tombstone_gc mode? is there any alternative way to get it?

**Comment by avikivity** [comment]
> The only real option is to teach cqlsh to interpret certain extension tags and deserialize the extension content. But that is not very scalable. And typically only helps users of cqlsh. Which is not exactly the end of all db introspection. Extensions are by design black-box opaque...

Saying "by design" doesn't excuse it. It could have been designed not to be opaque (serializers could serialize into a human readable string).

**Comment by avikivity** [comment]
We could fix it by adding a second column with human readable strings, and after a transition period delete the first column.

**Comment by slivne** [comment]
The solution is todo the describe schema on the server side - this is what users are supposed todo.

We have an issue for this https://github.com/scylladb/scylla/issues/9571

**Comment by elcallio** [comment]
Making extensions serialize to binary instead of for example enforce json was perhaps a bit short sighted. But @slivne has the really correct solution.

**Comment by kostja** [comment]
Server side describe schema is implemented. We will not do anything else on this, since it involves a breaking change or having a duplicate column which would act the same as DESCRIBE SCHEMA output.
