### ISSUE TITLE
"CONTAINS NULL" and "CONTAINS KEY NULL" restrictions should match nothing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#10359]
If we have a set column `s` and a restriction `s CONTAINS NULL`, Cassandra rejects it with an InvalidRequest `Unsupported null value for column s`.

In Scylla we decided in the past (e.g., see #4776) **not** to reject queries that compare things to NULL. We decided that "= NULL" or "< NULL" should 1. not fail, and 2. not match anything. We have tests that verify these comparisons in `test_null.py`.

But the situation today for "CONTAINS NULL" is that it unlike Cassandra, it doesn't fail - and yet unlike our tradition not to match anything against NULL, it **does** match things - it matches only non-null sets. The following test fails:

```python
def test_filtering_contains_null(cassandra_bug, cql, table1):
    p = unique_key_string()
    cql.execute(f"INSERT INTO {table1} (p,c,s) VALUES ('{p}', '1', {{1, 2}})")
    cql.execute(f"INSERT INTO {table1} (p,c,s) VALUES ('{p}', '2', {{3, 4}})")
    cql.execute(f"INSERT INTO {table1} (p,c) VALUES ('{p}', '3')")
    assert list(cql.execute(f"SELECT c FROM {table1} WHERE p='{p}' AND s CONTAINS NULL ALLOW FILTERING")) == []
```

The SELECT in this test. returns the two rows with the non-empty sets (c=1 and c=2) instead of nothing.

@avikivity can you please confirm (or deny) that according to your understanding of SQL, `CONTAINS NULL` should match no set - not actual sets and not nulls?

My understanding is that `CONTAINS x` on a set checks whether any of the set's elements is `= x`. Since `= NULL` matches no element, `CONTAINS NULL` should match no set. Am I missing something?

We have the same bug with the `CONTAINS KEY` operator (for maps). `CONTAINS KEY NULL` appears to match any map (even null maps) - instead of not matching any maps.

We have reproducing cql-pytest tests in `test_null.py`:
* `test_filtering_contains_null`
* `test_filtering_contains_key_null`

CC @cvybhu @psarna

**Comment by avikivity** [comment]
"x CONTAINS y" means that set x contains element y. But it's not possible (IIUC) for a set to contain NULL. The empty set certainly doesn't contain it. So x CONTAINS NULL should return false for any x.

**Comment by avikivity** [comment]
I don't think this is worth backporting. Nobody writes statements like that. It's good that we fixed it, but the risk of anyone actually using it is low.
