### ISSUE TITLE
Comparison with UNSET_VALUE should produce an error

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#10358]
In issue #4776 we decided that although Cassandra generates an error on a "WHERE x=NULL", Scylla will not - and simply match nothing.

It turns out that Scylla also silently ignores an UNSET_VALUE binding of "WHERE x=?", whereas Cassandra prints the error message "Unsupported unset value for column %s" (added in Cassandra commit 9c3855b5fd83b9fa9ffb2e5495e43cbea9855dee) in this case.
UNSET_VALUE is useful in write commands, to avoid parts of the write - but it is probably a user's mistake to use it in a read command, and we shouldn't remain silent in that case.

Reproduced by several translated Cassandra unit tests in `cassandra_tests/validation/operations/select_test.py`:
* `test*ContainsWithIndex`
* `testFilteringWithoutIndices`
* `testFilteringWithoutIndicesWithCollections`
* `testFilteringWithoutIndicesWithFrozenCollections`
* `testAllowFilteringOnPartitionKey`
* `testAllowFilteringOnPartitionKeyWithoutIndicesWithCollections`

And also in `cassandra_tests/validation/operations/select_single_column_relation_test.py`:
* `testWithUnsetValues`

**Comment by nyh** [comment]
This bug is not really specific to to equality comparisons. Perhaps in general, an UNSET_VALUE anywhere (or in most places?) in any WHERE expression (as opposed to an INSERT or UPDATE) should be considered an error. In commit 808a93d29bc8e4335e111201f99e4b2296ccc8d0 I fixed another bug involving an UNSET_VALUE in the WHERE expression `m[?]` which even led to a crash. So, perhaps instead of checking for UNSET_VALUE in each separate type of expression, we can add the check for UNSET_VALUE in one place, where WHERE expressions are executed.

The question is whether really UNSET_VALUE is not allowed anywhere in WHERE expressions. I think it isn't, but the documentation (the only vague explanation I found was the NEWS file in Cassandra commit 48f644686b48357354f16c74b02b6d2c450a8c2d) isn't clear.

On the other hand UNSET_VALUE is allowed in some other contexts (not WHERE) in SELECT. For example a LIMIT of UNSET_VALUE means no limit (this is documented in the above commit, and tested in one of the unit tests introduced there).

**Comment by nyh** [comment]
Commit 0b418fa7cf164e7fcbeab2d4ab1a3412eb8aeef0 by @avikivity  improved the UNSET-checking code to be more centralized and it now generates an error in more cases, such as `WHERE c=?` when c is a clustering key. However, `WHERE x=?` when x is a regular column still fails to report an error.

**Comment by avikivity** [comment]
Probably we're bypassing evaluate() here.

**Comment by nyh** [comment]
> Probably we're bypassing evaluate() here.

Turns out you were exactly right - when there are no items to filter, it doesn't get to check this, but when there are items, we do catch this case correctly. I'm adding tests for this in https://github.com/scylladb/scylladb/pull/12534 and they are passing. So closing as fixed by https://github.com/scylladb/scylladb/commit/0b418fa7cf164e7fcbeab2d4ab1a3412eb8aeef0

**Comment by avikivity** [comment]
> > Probably we're bypassing evaluate() here.
> 
> Turns out you were exactly right - when there are no items to filter, it doesn't get to check this, but when there are items, we do catch this case correctly. I'm adding tests for this in #12534 and they are passing. So closing as fixed by [0b418fa](https://github.com/scylladb/scylladb/commit/0b418fa7cf164e7fcbeab2d4ab1a3412eb8aeef0)

I meant "bypassing evaluate" in a different way (using a different code path), but you are generous to interpret my mistake as guessing the correct cause.
