### ISSUE TITLE
scylla_setup fails while executing perftune.py script

### ISSUE THREAD

**Issue by sdjerdj** [scylladb/scylladb#10367]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Background info:
While testing a new storage protocol setup (NVMe over RDMA), I have run into the following error message when tried to run scylla_setup:

raceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 86, in <module>
    rps_cpus = run('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname), shell=True, check=True, capture_output=True, encoding='utf-8').stdout.strip()
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic enp1s0 --get-cpu-mask' returned non-zero exit status 1.
Performance Tuning setup failed. Press any key to continue...

This prevents even starting up the scylla instance
If I do the setup using the local (root) disk, the scylla_setup runs without any issues.

*Installation details*
Scylla version : scylla-4.6.1-0.20220328.2309d6b51.x86_64
Cluster size: 3 nodes
OS OEL8.5

*Hardware details (for performance issues)*          Delete if unneeded
Platform : 3 VMs using standard OS based KVM
Hardware: Each VM is with 2 cores and 4GB of RAM
Disks: (SSD/HDD, count)
The storage is exported via nvme over rdma from one PC using (file) loopback devices as back end storage (SSD)
Each VM talks directly to the "storage server" via IB/rdma to avoid the virtualization masking the nvme device as scsi device.
The actual setup of the RAID 0 is successful and the mount is present on the OS level

[root@kvm111 data]# df -h ./
Filesystem      Size  Used Avail Use% Mounted on
/dev/md0        100G  2.7G   98G   3% /var/lib/scylla
[root@kvm111 data]#

I can execute the FIO test without issues using the md0 device

I have tried re-installing the scylla software and re-creating the test from the beginning, the result is the same,

**Comment by sdjerdj** [comment]
Complete output of the scylla-setup steps:

[root@kvm111 ~]# scylla_setup 
Skip any of the following steps by answering 'no'
Do you want to run check your kernel version?
Yes - runs a  script to verify that the kernel for this instance qualifies to run Scylla. No - skips the kernel check.
[YES/no]no
Do you want to verify the ScyllaDB packages are installed?
Yes - runs a script to confirm that ScyllaDB is installed. No - skips the installation check.
[YES/no]no
Do you want the Scylla server service to automatically start when the Scylla node boots?
Yes - Scylla server service automatically starts on Scylla node boot. No - skips this step. Note you will have to start the Scylla Server service manually.
[YES/no]yes
Do you want to disable SELinux?
Yes - disables SELinux. Choosing Yes greatly improves performance. No - keeps SELinux activated.
[YES/no]yes
Do you want to setup Network Time Protocol(NTP) to auto-synchronize the current time on the node?
Yes - enables time-synchronization. This keeps the correct time on the node. No - skips this step.
[YES/no]yes
ntp is already configured, skip setup
Do you want to setup RAID and XFS?
It is recommended to use RAID and XFS for Scylla data. If you select yes, you will be prompted to choose the unmounted disks to use for Scylla data. Selected disks are formatted as part of the process.
Yes - choose a disk/disks to format and setup for RAID and XFS. No - skip this step.
[YES/no]yes
Are you sure you want to setup RAID and XFS?
If you choose Yes, the selected drive will be reformated, erasing all existing data in the process.
[YES/no]yes
Do you want to change RAID level to RAID5?
If you choose Yes, change RAID level to RAID5. Otherwise we will use RAID0.
[yes/NO]no
Please select unmounted disks from the following list: /dev/nvme0n1, /dev/nvme0n2, /dev/nvme0n3, /dev/nvme0n4, /dev/nvme0n5, /dev/nvme0n6
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: 
> /dev/nvme0n1 
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: /dev/nvme0n1
> /dev/nvme0n2 
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: /dev/nvme0n1, /dev/nvme0n2
> done
/dev/md0 will be used to setup a RAID
Creating fRAID{args.raid_level} for scylla using 2 disk(s): /dev/nvme0n1,/dev/nvme0n2
mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md0 started.
log stripe unit (1048576 bytes) is too large (maximum is 256KiB)
log stripe unit adjusted to 32KiB
meta-data=/dev/md0               isize=512    agcount=16, agsize=6548480 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1
data     =                       bsize=1024   blocks=104775680, imaxpct=25
         =                       sunit=1024   swidth=2048 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=1024   blocks=51168, version=2
         =                       sectsz=512   sunit=32 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Do you want to enable coredumps?
Yes - sets up coredump to allow a post-mortem analysis of the Scylla state just prior to a crash. No - skips this step.
[YES/no]yes
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
kernel.core_pipe_limit = 16
Generating coredump to test systemd-coredump...

PID: 14612 (bash)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Tue 2022-04-12 15:19:51 EDT (3s ago)
  Command Line: /bin/bash /tmp/tmpv4hf3wfo
    Executable: /usr/bin/bash
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (djusi)
       Boot ID: e2054b4af9ec4843b63b4fdc6cbdbb8f
    Machine ID: 1c81c199463241e6a8e2a20270dfc330
      Hostname: kvm111.srnet.lan
       Storage: /var/lib/systemd/coredump/core.bash.0.e2054b4af9ec4843b63b4fdc6cbdbb8f.14612.1649791191000000
       Message: Process 14612 (bash) of user 0 dumped core.
                
                Stack trace of thread 14612:
                #0  0x00007fb1bdf4367b kill (libc.so.6)
                #1  0x00005608bcf7c27c kill_pid (bash)
                #2  0x00005608bcfb938f kill_builtin (bash)
                #3  0x00005608bcf675a0 execute_builtin.isra.4 (bash)
                #4  0x00005608bcf69f4e execute_simple_command (bash)
                #5  0x00005608bcf6b1d6 execute_command_internal (bash)
                #6  0x00005608bcf6ca86 execute_command (bash)
                #7  0x00005608bcf54409 reader_loop (bash)
                #8  0x00005608bcf52bdb main (bash)
                #9  0x00007fb1bdf2f493 __libc_start_main (libc.so.6)
                #10 0x00005608bcf5339e _start (bash)


systemd-coredump is working finely.
Do you want to setup a system-wide customized configuration for Scylla?
Yes - setup the sysconfig file. No - skips this step.
[YES/no]yes
Do you want to enable Network Interface Card (NIC) and disk(s) optimization?
Yes - optimize the NIC queue and disks settings. Selecting Yes greatly improves performance. No - skip this step.
[yes/NO]yes
Please select a NIC from the following list:
['ib0', 'enp1s0', 'ib1']
> enp1s0
The clocksource is the physical device that Linux uses to take time measurements. In most cases Linux chooses the fastest available clocksource device as long as it is accurate. In some situations, however, Linux errs in the side of caution and does not choose the fastest available clocksource despite it being accurate enough. If you know your hardwares fast clocksource is stable enough, choose "yes" here. The safest is the choose "no" (the default)
Yes - enforce clocksource setting. No - keep current configuration.
[yes/NO]no
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 86, in <module>
    rps_cpus = run('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname), shell=True, check=True, capture_output=True, encoding='utf-8').stdout.strip()
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic enp1s0 --get-cpu-mask' returned non-zero exit status 1.
Performance Tuning setup failed. Press any key to continue...

Do you want IOTune to study your disks IO profile and adapt Scylla to it? (*WARNING* Saying NO here means the node will not boot in production mode unless you configure the I/O Subsystem manually!)
Yes - let iotune study my disk(s). Note that this action will take a few minutes. No - skip this step.
[YES/no]yes
tuning /sys/devices/virtual/block/md0
tuning: /sys/devices/virtual/block/md0/queue/nomerges 2
tuning /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1
tuning: /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/queue/nomerges 2
tuning /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n2
tuning: /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n2/queue/nomerges 2
tuning /sys/devices/virtual/block/md0
tuning /sys/devices/virtual/block/md0
tuning /sys/devices/virtual/block/md0
tuning /sys/devices/virtual/block/md0
INFO  2022-04-12 15:20:54,124 [shard 0] iotune - /var/lib/scylla/saved_caches passed sanity checks
WARN  2022-04-12 15:20:54,125 [shard 0] iotune - write_cache for /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/queue/write_cache is set to write back. Some disks have poor implementation of this mode, pay attention to the measurements accuracy.
WARN  2022-04-12 15:20:54,125 [shard 0] iotune - write_cache for /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n2/queue/write_cache is set to write back. Some disks have poor implementation of this mode, pay attention to the measurements accuracy.
INFO  2022-04-12 15:20:54,125 [shard 0] iotune - Disk parameters: max_iodepth=256 disks_per_array=2 minimum_io_size=512
Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 212 MB/s (deviation 86%)
Measuring sequential read bandwidth: 589 MB/s (deviation 3%)
Measuring random write IOPS: 1765 IOPS (deviation 82%)
Measuring random read IOPS: 74542 IOPS (deviation 30%)
Writing result to /etc/scylla.d/io_properties.yaml
Writing result to /etc/scylla.d/io.conf
Created symlink /etc/systemd/system/multi-user.target.wants/scylla-node-exporter.service → /usr/lib/systemd/system/scylla-node-exporter.service.
Do you want to set the CPU scaling governor to Performance level on boot?
Yes - sets the CPU scaling governor to performance level. No - skip this step.
[YES/no]no
Do you want to enable fstrim service?
Yes - runs fstrim on your SSD. No - skip this step.
[YES/no]yes
Will Scylla be the only service on this host?
Answer yes to lock all memory to Scylla, to prevent swapout. Answer no to do nothing.
[YES/no]yes
Do you want to configure rsyslog to send log to a remote repository?
Answer yes to setup rsyslog to a remote server, Answer no to do nothing.
[YES/no]no
ScyllaDB setup finished.
scylla_setup accepts command line arguments as well! For easily provisioning in a similar environment than this, type:

    scylla_setup --disks /dev/nvme0n1,/dev/nvme0n2 --nic enp1s0 \
                 --no-kernel-check --no-verify-package --io-setup 1 \
                 --no-cpuscaling-setup --no-rsyslog-setup

Also, to avoid the time-consuming I/O tuning you can add --no-io-setup and copy the contents of /etc/scylla.d/io*
Only do that if you are moving the files into machines with the exact same hardware
[root@kvm111 ~]#

**Comment by sdjerdj** [comment]
If needed I can provide the exect steps how to set up the NVMe over RDMA client  and target.

**Comment by sdjerdj** [comment]
For testing purposed, I have disabled the var-lib-scylla.mount system service and re-ran the scylla_setup

[root@kvm111 /]# systemctl stop var-lib-scylla.mount 
[root@kvm111 /]# systemctl status var-lib-scylla.mount 
● var-lib-scylla.mount - Scylla data directory
   Loaded: loaded (/etc/systemd/system/var-lib-scylla.mount; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2022-04-12 19:29:45 EDT; 2s ago
    Where: /var/lib/scylla
     What: /dev/disk/by-uuid/025a5902-88a4-4ece-8cf2-e1454b7b56b7

Apr 12 15:19:02 kvm111.srnet.lan systemd[1]: var-lib-scylla.mount: Directory /var/lib/scylla to mount over is not empty, mounting anyway.
Apr 12 15:19:02 kvm111.srnet.lan systemd[1]: Mounting Scylla data directory...
Apr 12 15:19:02 kvm111.srnet.lan systemd[1]: Mounted Scylla data directory.
Apr 12 19:29:30 kvm111.srnet.lan systemd[1]: Unmounting Scylla data directory...
Apr 12 19:29:30 kvm111.srnet.lan umount[29410]: umount: /var/lib/scylla: target is busy.
Apr 12 19:29:30 kvm111.srnet.lan systemd[1]: var-lib-scylla.mount: Mount process exited, code=exited status=32
Apr 12 19:29:30 kvm111.srnet.lan systemd[1]: Failed unmounting Scylla data directory.
Apr 12 19:29:45 kvm111.srnet.lan systemd[1]: Unmounting Scylla data directory...
Apr 12 19:29:45 kvm111.srnet.lan systemd[1]: var-lib-scylla.mount: Failed with result 'exit-code'.
Apr 12 19:29:45 kvm111.srnet.lan systemd[1]: Unmounted Scylla data directory.
[root@kvm111 /]# systemctl disable var-lib-scylla.mount 
Removed /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount.
[root@kvm111 /]#


[root@kvm111 /]# scylla_setup --nic enp1s0 --no-kernel-check --no-verify-package --io-setup 1 --no-cpuscaling-setup --no-rsyslog-setup --no-raid-setup
ntp is already configured, skip setup
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
kernel.core_pipe_limit = 16
Generating coredump to test systemd-coredump...

PID: 29696 (bash)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Tue 2022-04-12 19:31:49 EDT (3s ago)
  Command Line: /bin/bash /tmp/tmpjg0m3e9i
    Executable: /usr/bin/bash
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (djusi)
       Boot ID: e2054b4af9ec4843b63b4fdc6cbdbb8f
    Machine ID: 1c81c199463241e6a8e2a20270dfc330
      Hostname: kvm111.srnet.lan
       Storage: /var/lib/systemd/coredump/core.bash.0.e2054b4af9ec4843b63b4fdc6cbdbb8f.29696.1649806309000000
       Message: Process 29696 (bash) of user 0 dumped core.
                
                Stack trace of thread 29696:
                #0  0x00007f794d32a67b kill (libc.so.6)
                #1  0x0000564a9ac5b27c kill_pid (bash)
                #2  0x0000564a9ac9838f kill_builtin (bash)
                #3  0x0000564a9ac465a0 execute_builtin.isra.4 (bash)
                #4  0x0000564a9ac48f4e execute_simple_command (bash)
                #5  0x0000564a9ac4a1d6 execute_command_internal (bash)
                #6  0x0000564a9ac4ba86 execute_command (bash)
                #7  0x0000564a9ac33409 reader_loop (bash)
                #8  0x0000564a9ac31bdb main (bash)
                #9  0x00007f794d316493 __libc_start_main (libc.so.6)
                #10 0x0000564a9ac3239e _start (bash)


systemd-coredump is working finely.
tuning /sys/devices/virtual/block/md0
already tuned: /sys/devices/virtual/block/md0/queue/nomerges
tuning /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1
already tuned: /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/queue/nomerges
tuning /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n2
already tuned: /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n2/queue/nomerges
tuning /sys/devices/virtual/block/md0
tuning /sys/devices/virtual/block/md0
tuning /sys/devices/virtual/block/md0
tuning /sys/devices/virtual/block/md0
INFO  2022-04-12 19:31:53,339 [shard 0] iotune - /var/lib/scylla/saved_caches passed sanity checks
WARN  2022-04-12 19:31:53,340 [shard 0] iotune - write_cache for /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/queue/write_cache is set to write back. Some disks have poor implementation of this mode, pay attention to the measurements accuracy.
WARN  2022-04-12 19:31:53,340 [shard 0] iotune - write_cache for /sys/devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n2/queue/write_cache is set to write back. Some disks have poor implementation of this mode, pay attention to the measurements accuracy.
INFO  2022-04-12 19:31:53,340 [shard 0] iotune - Disk parameters: max_iodepth=256 disks_per_array=2 minimum_io_size=512
Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 317 MB/s (deviation 61%)
Measuring sequential read bandwidth: 635 MB/s (deviation 15%)
Measuring random write IOPS: 2472 IOPS (deviation 60%)
Measuring random read IOPS: 83800 IOPS (deviation 25%)
Writing result to /etc/scylla.d/io_properties.yaml
Writing result to /etc/scylla.d/io.conf
ScyllaDB setup finished.


[root@kvm111 /]# mount |grep scy
/dev/md0 on /var/lib/scylla type xfs (rw,noatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,sunit=2048,swidth=4096,noquota)


[root@kvm111 /]# systemctl status var-lib-scylla.mount 
● var-lib-scylla.mount - Scylla data directory
   Loaded: loaded (/etc/systemd/system/var-lib-scylla.mount; disabled; vendor preset: disabled)
   Active: active (mounted) since Tue 2022-04-12 19:31:49 EDT; 11min ago
    Where: /var/lib/scylla
     What: /dev/md0
    Tasks: 0 (limit: 24595)
   Memory: 60.0K
   CGroup: /system.slice/var-lib-scylla.mount

Apr 12 19:31:49 kvm111.srnet.lan systemd[1]: Mounting Scylla data directory...
Apr 12 19:31:49 kvm111.srnet.lan systemd[1]: Mounted Scylla data directory.
[root@kvm111 /]#

As you can see, the setup completed successfully

**Comment by sdjerdj** [comment]
After this setup was completed I have made sure that the automatic load of the nvme over rdma stack is working 
and rebooted the VMs
After this, I have configured the additional parameters in the scylla.yaml file and successfully started up the cluster.

**Comment by sdjerdj** [comment]
Did a quick cassandra-stress write test and I can definitely see data on the nodes:

[root@kvm111 ~]# nodetool status
Datacenter: sc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  172.16.1.112  581.16 MB  256          ?       4fd87cd7-68a7-4a80-9614-e209283bf544  r2
UN  172.16.1.113  788.26 MB  256          ?       ec074278-25f9-4377-b7b2-3089d7675554  r3
UN  172.16.1.111  545.14 MB  256          ?       7e7adae8-9b1b-486a-8c63-68606db357ea  r1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
[root@kvm111 ~]#

Additionally I can see via iostat workload on the md0 device.

**Comment by sdjerdj** [comment]
I think I found what might be confusing the script:

nvme lists the device names as expected (nvme0n1), however, iostat actually shows the "controller" id in the naming (nvme0c0n1):

[root@kvm111 lib]# nvme list
Node                  SN                   Model                                    Namespace Usage                      Format           FW Rev  
--------------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1          57488d26b4c12158     Linux                                    1          53.69  GB /  53.69  GB    512   B +  0 B   5.4.17-2
/dev/nvme0n2          57488d26b4c12158     Linux                                    2          53.69  GB /  53.69  GB    512   B +  0 B   5.4.17-2
/dev/nvme0n3          57488d26b4c12158     Linux                                    3          53.69  GB /  53.69  GB    512   B +  0 B   5.4.17-2
/dev/nvme0n4          57488d26b4c12158     Linux                                    4          53.69  GB /  53.69  GB    512   B +  0 B   5.4.17-2
/dev/nvme0n5          57488d26b4c12158     Linux                                    5          53.69  GB /  53.69  GB    512   B +  0 B   5.4.17-2
/dev/nvme0n6          57488d26b4c12158     Linux                                    6          53.69  GB /  53.69  GB    512   B +  0 B   5.4.17-2
[root@kvm111 lib]#


[root@kvm111 lib]# iostat -x 
Linux 5.4.17-2136.305.5.4.el8uek.x86_64 (kvm111.srnet.lan) 	04/12/2022 	_x86_64_	(4 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          10.21    0.03    5.66    0.02    5.09   78.99

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              5.37    0.88    146.82     34.36     0.18     0.13   3.18  12.52    0.40    0.74   0.00    27.32    38.95   0.55   0.34
dm-0             5.10    1.00    141.37     34.96     0.00     0.00   0.00   0.00    0.41    0.59   0.00    27.70    35.07   0.56   0.34
dm-1             0.03    0.00      0.60      0.00     0.00     0.00   0.00   0.00    0.19    0.00   0.00    22.85     0.00   0.25   0.00
nvme0c0n1        7.43   19.85    745.53   2012.76     0.01     0.03   0.07   0.15    0.86    1.35   0.02   100.28   101.38   1.52   4.16
nvme0c0n2        7.39   19.83    747.10   2014.77     0.01     0.04   0.12   0.19    0.84    1.32   0.02   101.09   101.60   1.51   4.10
nvme0c0n3        0.02    0.00      0.18      0.00     0.00     0.00   0.00   0.00    0.12    0.00   0.00    11.24     0.00   0.32   0.00
md0             14.72   37.55   1528.39   4126.82     0.00     0.00   0.00   0.00    0.00    0.00   0.00   103.83   109.90   0.00   0.00
nvme0c0n4        0.02    0.00      0.17      0.00     0.00     0.00   0.00   0.00    0.16    0.00   0.00    10.18     0.00   0.34   0.00
nvme0c0n5        0.02    0.00      0.18      0.00     0.00     0.00   0.00   0.00    0.15    0.00   0.00    11.24     0.00   0.37   0.00
md127            0.01    0.00      0.28      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00    21.75     0.00   0.00   0.00
nvme0c0n6        0.02    0.00      0.17      0.00     0.00     0.00   0.00   0.00    0.16    0.00   0.00    10.18     0.00   0.31   0.00
md126            0.01    0.00      0.28      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00    21.75     0.00   0.00   0.00

**Comment by sdjerdj** [comment]
The same is visible if I list the devices via the configfs:

[root@kvm111 lib]# ls -l /sys/block/nvme*
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0c0n1 -> ../devices/virtual/nvme-fabrics/ctl/nvme0/nvme0c0n1
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0c0n2 -> ../devices/virtual/nvme-fabrics/ctl/nvme0/nvme0c0n2
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0c0n3 -> ../devices/virtual/nvme-fabrics/ctl/nvme0/nvme0c0n3
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0c0n4 -> ../devices/virtual/nvme-fabrics/ctl/nvme0/nvme0c0n4
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0c0n5 -> ../devices/virtual/nvme-fabrics/ctl/nvme0/nvme0c0n5
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0c0n6 -> ../devices/virtual/nvme-fabrics/ctl/nvme0/nvme0c0n6
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0n1 -> ../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0n2 -> ../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n2
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0n3 -> ../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n3
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0n4 -> ../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n4
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0n5 -> ../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n5
lrwxrwxrwx. 1 root root 0 Apr 12 21:06 /sys/block/nvme0n6 -> ../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n6
[root@kvm111 lib]#

**Comment by syuu1228** [comment]
@sdjerdj Hi,

Cloud you try this command on the VM, and copy & paste result on this thread:
```
sudo /opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic enp1s0 --get-cpu-mask
```


Also, I need to know more detail of this VM configuration, so I have few questions:
 - please provide VM configuration file such as libvirt XML file, if possible.
 - I'm guessing default NIC `enp1s0` is KVM virtual NIC, and `ib0` /`ib1` are pci-passthrough IB interface, correct?
 - What happens if we detach IB interface and run same setup again (you probably have to setup without nvme drives though)?

**Comment by sdjerdj** [comment]
@syuu1228 
Here is the requested output of the command above:

`[root@kvm111 ~]# sudo /opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic enp1s0 --get-cpu-mask
ERROR: [Errno 2] No such file or directory: '/sys/devices/virtual/modalias'. Your system can't be tuned until the issue is fixed.

[root@kvm111 ~]#
`

As for the config you are correct:
enp1s0 is the client side NIC, and the ib0 is is a sriov virtual function passed through from a Mellanox ConnectX-3 NIC for storage connection.

If I detach the NVMe storage and let the script do its thing, it'll use the root device and detect is as a regular scsi device
(in the back end that is just a boot image file exported via NFS to the KVM hypervisor
This setup worked as expected, no errors while running the scylla_setup script

**Comment by steve-gray** [comment]
As discussed with @avikivity on Slack, we've also seen this issue. Environment details were:

- Oracle Cloud
- Oracle Linux 8.7-2013 image
- AMD Epyc64 VM (Standard.Flex.E4) with 16 cores, 64GB
- 2x Attached block volumes 

The issue is that if connected via iSCSI it seems that the perf-tune code is picking up something and hitting this error. Switching the volumes to paravirtualised fixes the issue I assume since the extra HBA/NIC's used for the volumes are gone. Both `scylla_setup` and `scylla-server` daemon fail with this error:

```
ERROR: [Errno 2] No such file or directory: '/sys/devices/virtual/modalias'. Your system can't be tuned until the issue is fixed.
```

**Comment by steve-gray** [comment]
When will this be part of a release @avikivity? The commit appears to fix the underlying framework but guess it'll be a bit of time till we see a Scylla release with it?
