### ISSUE TITLE
The CQL token() function should validate its parameters

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#10448]
As [our documentation of the `token()` function](https://docs.scylladb.com/getting-started/functions/) explains,

> The arguments of the token depend on the type of the partition key columns that are used. 

If the number or type of arguments passed to `token()`'s do not match the requirements of the partition key, an invalid request error should be thrown. Currently it is not - the SELECT seems to silently match nothing but I'm worried that under the hood it might be doing something undefined and worse could happen - as happened in Cassandra which had the same bug (https://issues.apache.org/jira/browse/CASSANDRA-14989) - and had a null pointer exception in this case. The Cassandra bug was fixed in Cassandra 4.0.

This bug is reproduced by two unit tests translated from Cassandra:
* `cassandra_tests/validation/operations/select_test.py`::`testTokenFctRejectsInvalidColumnType`
* `cassandra_tests/validation/operations/select_test.py`::`testTokenFctRejectsInvalidColumnCount`

**Comment by raphaelsc** [comment]
bumped into lack of validation today when running:

```
cqlsh> CREATE KEYSPACE ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cqlsh> CREATE COLUMNFAMILY ks.cf (rowkey text, ckey int, value int, PRIMARY KEY(rowkey, ckey));
cqlsh> INSERT INTO ks.cf (rowkey, ckey, value) VALUES ('1', 1, 1); 
cqlsh> INSERT INTO ks.cf (rowkey, ckey, value) VALUES ('2', 1, 1);
```

cassandra 4.0.4 rejects ckey value (which is the same type as partition key) param:

```
cqlsh> select token(ckey) from ks.cf where rowkey='1' and ckey=1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Type error: ckey cannot be passed as argument 0 of function system.token of type text
```

whereas scylla accepts it, apparently returning a bogus value, which can mislead the application:

```
cqlsh> select token(rowkey) from ks.cf where rowkey='1' and ckey=2;

 system.token(rowkey)
----------------------
  8213365047359667313

(1 rows)
cqlsh> select token(ckey) from ks.cf where rowkey='1' and ckey=2;

 system.token(ckey)
----------------------
 -3248873570005575792
```

**Comment by denesb** [comment]
Compatibility improvement, not backporting.
