### ISSUE TITLE
Implement (time)UUID-based SSTable generation numbers

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#10459]
With UUID- or timeUUID-based generation numbers, we achieve globally unique identifiers for SSTables, which can be a foundation for multiple interesting projects, like shared storage.

The timeUUID-based idea comes from @raphaelsc's comment here: https://github.com/scylladb/scylla/pull/10404#issuecomment-1105620744

/cc @raphaelsc @avikivity 

Ref:
* https://issues.apache.org/jira/browse/CASSANDRA-17048
* https://github.com/apache/cassandra/commit/0040fea3797ea3e497691e9d1e2660711c60ac4d

**Comment by bhalevy** [comment]
Cc @raphaelsc @cmm

**Comment by bhalevy** [comment]
@tchaikov I added you to help out with this effort, with @raphaelsc's guidance.

**Comment by bhalevy** [comment]
@mykaul asked me to take ownership of this issue.
We're already on it....

**Comment by tchaikov** [comment]
> @tchaikov I added you to help out with this effort, with @raphaelsc's guidance.

ack. was reading the related issues today.
