### ISSUE TITLE
Repair failed after RemoveNodeThenAddNode failed to properly remove node

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylladb#10460]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.1.dev-20220421.cc40685c288f` with build-id `fde9a351743afef6ce27c7787712211d9ee8f41f`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-acecfe6e-9 (54.194.242.138 | 10.0.1.123) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-8 (34.243.183.187 | 10.0.0.144) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-7 (34.240.111.77 | 10.0.3.13) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-6 (18.202.225.136 | 10.0.0.71) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-5 (52.215.235.205 | 10.0.2.81) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-4 (34.244.12.198 | 10.0.1.34) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-3 (34.242.229.178 | 10.0.0.33) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-2 (52.208.144.39 | 10.0.3.200) (shards: 8)
- longevity-twcs-48h-master-db-node-acecfe6e-1 (34.243.226.229 | 10.0.3.228) (shards: 8)

OS / Image: `ami-07d353a9e8649b3a1` (aws: eu-west-1)

Test: `longevity-twcs-48h-test`
Test id: `acecfe6e-3e7b-436a-9f53-023a9d25b9ee`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f485155a9f8b359c8e8da8d07cd3d4396aa5ca27/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

**>>>>>>>**
During the DestroyDataThenRepair nemesis running repair failed with the following:

`sct.log`:
```
error: Repair job has failed with the error message: [2022-04-24 03:07:27,441] Repair session 3 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-04-24 03:07:27,441] Repair session 3 failed
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

In the `system.log` of the node on which the repair was running:

```
Apr 24 03:07:22 longevity-twcs-48h-master-db-node-acecfe6e-9 scylla[23462]:  [shard 4] repair - repair[e06e2c85-def5-4032-99ea-ab10c47a4a2d]: shard 4 failed - 501 out of 762 ranges failed
Apr 24 03:07:22 longevity-twcs-48h-master-db-node-acecfe6e-9 scylla[23462]:  [shard 1] repair - repair[e06e2c85-def5-4032-99ea-ab10c47a4a2d]: Repair 169 out of 762 ranges, shard=1, keyspace=system_auth, table={roles, role_members, role_attributes}, range=(-5058220623817991004, -5026594872127330145], peers={10.0.3.228, 10.0.3.13}, live_peers={10.0.3.228, 10.0.3.13} 
Apr 24 03:07:22 longevity-twcs-48h-master-db-node-acecfe6e-9 scylla[23462]:  [shard 3] repair - repair[e06e2c85-def5-4032-99ea-ab10c47a4a2d]: Repair 736 out of 762 ranges, shard=3, keyspace=system_auth, table={roles, role_members, role_attributes}, range=(8803803055631728665, 8839037464936345555], peers={10.0.3.228, 10.0.3.13}, live_peers={10.0.3.228, 10.0.3.13}
Apr 24 03:07:22 longevity-twcs-48h-master-db-node-acecfe6e-9 scylla[23462]:  [shard 3] repair - repair[e06e2c85-def5-4032-99ea-ab10c47a4a2d]: Repair 737 out of 762 ranges, shard=3, keyspace=system_auth, table={roles, role_members, role_attributes}, range=(8839037464936345555, 8840137109723375053], peers={10.0.3.13, 10.0.0.33}, live_peers={10.0.3.13}, status=partial
Apr 24 03:07:22 longevity-twcs-48h-master-db-node-acecfe6e-9 scylla[23462]:  [shard 3] repair - repair[e06e2c85-def5-4032-99ea-ab10c47a4a2d]: Repair 737 out of 762 ranges, shard=3, keyspace=system_auth, table={roles, role_members, role_attributes}, range=(8839037464936345555, 8840137109723375053], peers={10.0.3.13}, live_peers={10.0.3.13, 10.0.0.33}
Apr 24 03:07:22 longevity-twcs-48h-master-db-node-acecfe6e-9 scylla[23462]:  [shard 7] repair - repair[e06e2c85-def5-4032-99ea-ab10c47a4a2d]: shard 7 stats: repair_reason=repair, keyspace=system_auth, tables={roles, role_members, role_attributes}, ranges_nr=762, round_nr=2286, round_nr_fast_path_already_synced=2286, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=15345, tx_hashes_nr=0, rx_hashes_nr=0, duration=1.0312425 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{10.0.1.123, 0}, {10.0.3.228, 0}, {10.0.3.13, 0}}, row_from_disk_nr={{10.0.1.123, 0}, {10.0.3.228, 0}, {10.0.3.13, 0}}, row_from_disk_bytes_per_sec={{10.0.1.123, 0}, {10.0.3.228, 0}, {10.0.3.13, 0}} MiB/s, row_from_disk_rows_per_sec={{10.0.1.123, 0}, {10.0.3.228, 0}, {10.0.3.13, 0}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
Apr 24 03:07:22 longevity-twcs-48h-master-db-node-acecfe6e-9 scylla[23462]:  [shard 7] repair - repair[e06e2c85-def5-4032-99ea-ab10c47a4a2d]: shard 7 failed - 501 out of 762 ranges failed
```

(The same is present for all other shards.)

Before the repair session, a RemoveNodeThenAddNode nemesis failed, as described in: https://github.com/scylladb/scylla-cluster-tests/issues/4667
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor acecfe6e-3e7b-436a-9f53-023a9d25b9ee`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=acecfe6e-3e7b-436a-9f53-023a9d25b9ee)
- Show all stored logs command: `$ hydra investigate show-logs acecfe6e-3e7b-436a-9f53-023a9d25b9ee`

## Logs:
- **db-cluster-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/db-cluster-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/db-cluster-acecfe6e.tar.gz)
- **monitor-set-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/monitor-set-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/monitor-set-acecfe6e.tar.gz)
- **loader-set-acecfe6e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/loader-set-acecfe6e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/loader-set-acecfe6e.tar.gz)
- **normal-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/normal-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/normal-acecfe6e.log.tar.gz)
- **summary-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/summary-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/summary-acecfe6e.log.tar.gz)
- **events-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/events-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/events-acecfe6e.log.tar.gz)
- **output-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/output-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/output-acecfe6e.log.tar.gz)
- **debug-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/debug-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/debug-acecfe6e.log.tar.gz)
- **sct-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/sct-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/sct-acecfe6e.log.tar.gz)
- **error-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/error-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/error-acecfe6e.log.tar.gz)
- **critical-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/critical-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/critical-acecfe6e.log.tar.gz)
- **raw_events-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/raw_events-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/raw_events-acecfe6e.log.tar.gz)
- **warning-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/warning-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/warning-acecfe6e.log.tar.gz)
- **email_data-acecfe6e.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/email_data-acecfe6e.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/email_data-acecfe6e.json.tar.gz)
- **argus-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/argus-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/argus-acecfe6e.log.tar.gz)
- **left_processes-acecfe6e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/left_processes-acecfe6e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/acecfe6e-3e7b-436a-9f53-023a9d25b9ee/20220424_043226/left_processes-acecfe6e.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/29/)

**Comment by slivne** [comment]
I don't understand why repair should fail ?

Are we running repair while an active topology change (adding / removing node) is being done ?

**Comment by KnifeyMoloko** [comment]
@slivne This failure happened about a half hour after a RemoveNodeThenAddNode nemesis failed, due to one of the nodes not being removed properly. Apart from that, I don't see any nodes being removed or added during this nemesis. The nemesis iteself stops the scylla service on one of the nodes, deletes some non-system data files and starts the scylla service again.

**Comment by fgelcer** [comment]
@DoronArazii , it is lacking labels and assignee

**Comment by mykaul** [comment]
We missed analyzing it. After ~1 year with no one looking at it, I'm regretfully closing this. We should do a better job here (@DoronArazii - let's ensure we don't miss those!)

**Comment by xtrey** [comment]
@mykaul Seems so, I can open new one with linking this one. Is this a preferable way to deal with such issues?

**Comment by xtrey** [comment]
Closed in favor of https://github.com/scylladb/scylladb/issues/21765
