### ISSUE TITLE
Enhancement: scylla_raid_setup -ask a user if he wants to disable fstrim in case it's enabled

### ISSUE THREAD

**Issue by rayakurl** [scylladb/scylladb#10560]
## Installation details

Kernel Version: 5.13.0-1024-gcp

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-ubuntu2004-jenkins-db-node-0769239b-0-1 (34.148.80.57 | 10.142.0.31) (shards: 2)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts` (gce: us-east1)

Test: `artifacts-ubuntu2004-test`
Test id: `0769239b-1f5b-4c45-b845-04921d5f9628`
Test name: `scylla-master/artifacts-offline-install/artifacts-ubuntu2004-test`
Test config file(s):

- [ubuntu2004.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ea4aaa1b4f8b631fea2df71d8206e815c3d7614d/test-cases/artifacts/ubuntu2004.yaml)

## Issue description
As a default, in Ubuntu 20.04 the fstrim is 'enabled'.
```
raya_kurlyand@raya-ubuntu20-test:~$ systemctl status fstrim.timer
● fstrim.timer - Discard unused blocks once a week
     Loaded: loaded (/lib/systemd/system/fstrim.timer; enabled; vendor preset: enabled)
     Active: active (waiting) since Thu 2022-05-12 14:38:34 UTC; 3min 40s ago
    Trigger: Mon 2022-05-16 01:17:58 UTC; 3 days left
   Triggers: ● fstrim.service
       Docs: man:fstrim

May 12 14:38:34 raya-ubuntu20-test systemd[1]: Started Discard unused blocks once a week.
```
Since commit a19d00ef9b8b50ce520bb2cfbf5bc00b30de5cda we ask the user if he would like to enable fstrim.
We should ask the user if he wants to disable it as well or just to disable it without asking.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0769239b-1f5b-4c45-b845-04921d5f9628`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0769239b-1f5b-4c45-b845-04921d5f9628)
- Show all stored logs command: `$ hydra investigate show-logs 0769239b-1f5b-4c45-b845-04921d5f9628`

## Logs:
- **db-cluster-0769239b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0769239b-1f5b-4c45-b845-04921d5f9628/20220506_042819/db-cluster-0769239b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0769239b-1f5b-4c45-b845-04921d5f9628/20220506_042819/db-cluster-0769239b.tar.gz)
- **sct-runner-0769239b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0769239b-1f5b-4c45-b845-04921d5f9628/20220506_042819/sct-runner-0769239b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0769239b-1f5b-4c45-b845-04921d5f9628/20220506_042819/sct-runner-0769239b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2004-test/398/)

**Comment by syuu1228** [comment]
But if we disable fstrim.timer, we will never TRIM rootfs.
Maybe we should also enable "discard" on rootfs, when we enable it for RAID volume?
@avikivity Do you have any idea?

**Comment by syuu1228** [comment]
As I commented above, we cannot disable fstrim.timer since it's needed for rootfs.
Closing.
