### ISSUE TITLE
Change internal representation to v2

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#10587]
That is use `range_tombstone_change` instead of `range_tombstone` to represent ranged deletions inside `mutation_partition`.

As part of this move, we also want to change how range deletions are stored. Currently we have two lists: one for rows and one for range tombstones. Any read will have to do a lookup in both and advance in both data structures in sync. This setup makes writes simple, as they update just the relevant structure (either one or the other), it pushes the responsibility of merging the two to reads. As continuity information is stored in the rows container, range tombstones cannot be evicted, they are only removed when the partition itself is evicted (after it has no more rows).

The proposed change is to merge the two containers into one: the rows container will also store range tombstone changes. Each row would also contain the currently active range tombstone change [1]. In the start and end positions of a range tombstone change we will introduce an entry for it [2][3]. When applying a new range deletion, we'd have to iterate over all entries it covers and apply it to them, removing any superfluous entries (range tombstone changes that are supplanted by the new write), as well as inserting new range tombstone change entries.
An example rows container with the new proposed format:
```
{ {row: at(1), rtc: {}}, {rtc: ts: 5, before(2)}, {row: at(2), rtc: 5}, {row: at(3), rtc: 5}, {rtc: after(5), ts: {}}, {row: at(6), rtc: {}} }
```
Where `row` is a regular row entry and `rtc` is a range tombstone change entry. Notice how all rows the range deletion applies to, repeat the range tombstone information in them.

[1] We can maybe merge this with the row tombstone, but in certain cases we have both. We can start with a separate field and examine the possibility of reducing storage requirements later.
[2] If this coincides with with a row, we can merge the two and add a special flag to the row, signaling that it doubles as a range tombstone change. If the change is from one tomb to the other, we'd need to store the other tomb too. So maybe only use when the new tomb is `null`.
[3] Maybe we can piggyback on dummy rows for this.

**Comment by mykaul** [comment]
Should I move this to 5.3? It may not make it to 5.2, but 5.3 is perhaps realistic and better than 5.x?
@tgrabiec , @bhalevy  - thoughts?

**Comment by bhalevy** [comment]
Yes, even if it could make to 5.2, I think it's too late in the process for that since it's an intrusive change that would be better off with more soak time in master before getting to a release branch.

**Comment by mykaul** [comment]
I don't think we intend to backport this... ?

**Comment by bhalevy** [comment]
> I don't think we intend to backport this... ?

This change is way too risky to backport.
