### ISSUE TITLE
Scylla_setup get mode sq_split,and the read-write latency become higher because cpu0 si is 100% 

### ISSUE THREAD

**Issue by vlaualv** [scylladb/scylladb#10600]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 4.3.6
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Platform : Physical
Hardware: sockets= cores=80VCpu hyperthreading= memory=376G
Disks: SSD 3.7TB (nvme)
NIC infomation: bond0 with two NICs
`[root@ scylla.d]# ethtool -l enp94s0f0

Channel parameters for enp94s0f0:
Pre-set maximums:
RX:             0
TX:             0
Other:          512
Combined:       63
Current hardware settings:
RX:             0
TX:             0
Other:          0
Combined:       63`

I run scylla_setup script in my phisical machine, I get the perftune.yaml as follows:
`cpu_mask: 0x0000ffff,0xffffffff,0xffffffff
mode: sq_split
nic: bond0
tune:`

The mode automaticly generated by scylla_setup is sq_split, it will divide all IRQS of a given NIC between CPU0 and its HT siblings.
When I load data into scylla cluster,one of node CPU0 si is 100%，and the latency of this node is higher than other node. Futhermore, this node has packet loss in NIC.

I read System Configuration Guide(https://docs.scylladb.com/getting-started/system-configuration/),this documetation suggest,use posix_net_conf.sh srcript with the -mq parameter for bare metal setups with multi-queue nics.

Which mode should I choose to avoid performance degradation ？
Is it a bug for scylla_setup?

**Comment by slivne** [comment]
We support only the two latest scylla open source releases, as of today May 22 2022 its 4.5 and 4.6 

Please upgrade

With regards to your question

https://docs.scylladb.com/operating-scylla/admin-tools/perftune/

sq and sq_split will allow interrupts to run on a vcpu / core

mq allows sending interrupts to all cores - you need to have enough queues

We have seen cases in the past in which there are not enough queues and there is a need to spread the interrupts on more cores - especially on very large machines.

if this is not enough  for interrupts you can also use the ```--irq-cpu-mask, --cpu-mask``` to set the number of cpus to run scylla on vs the cores to have interrupts spread over.
f

**Comment by vladzcloudius** [comment]
This issue is supposed to be resolved after we added "large machines support" in https://github.com/scylladb/seastar/issues/1171.

Closing
