### ISSUE TITLE
Drop support for CQL v2

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#10607]
In my review of https://github.com/scylladb/scylla/pull/10599 I raised eyebrows about an inconsistency in the antique CQL v2 definition.
They had the following text:
```
    [short]        A 2 byte unsigned integer
    [bytes]        A [int] n, followed by n bytes if n >= 0. If n < 0,  no byte should follow and the value represented is `null`.
    [short bytes]  A [short] n, followed by n bytes if n >= 0.
    
6.10 list
  A [short] n indicating the number of elements in the list, followed by n elements.
  Each element is [short bytes] representing the serialized value.
``` 

If `[short]` is an **unsigned** 2-byte integer, why is `[short bytes]` saying **if n >= 0**? I'm guessing this "if" wasn't redundant - that there was indeed a possibility of size = -1 (a short version of the `null` value), so I guess either `[short]` was actually signed, or maybe it was unsigned but the value 65535 (-1) was treated specially. But I don't know, and I think nothing short of Cassandra code archaeology can resolve this mystery of what they actually had in the code. The answer to this question may mean that our implementation of the function `read_collection_value()` might be wrong in how it handles negative sizes (it currently reads an unsigned size, and assumes nulls were impossible).

But my main point in this issue is that perhaps all this archaeology is unnecessary - according to my investigation, the CQL binary protocol v3 was released in 2014, for Cassandra 2.1, and in Cassandra 3.0 dropped support for v2 completely (even the document on the v2 protocol was deleted). If Cassandra 3.0 dropped this support, why should we uglify our code with attempted support for this protocol - support which I'm now worried is not accurate, and is not (as far as I know) being tested?

If we decide to drop the v2 protocol, the first thing we can do is to rid `types.cc` of all code for `!using_32_bits_for_collections()`.  See also `cql_serialization_format.hh`. I don't know if there is any other code in Scylla which is different for protocol version <=2. I couldn't find any.

CC @cvybhu

**Comment by avikivity** [comment]
Not a bug, not backporting.
