### ISSUE TITLE
Column name printed in a strange way in error message

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#10632]
In the test `cassandra_tests/validation/operations/select_single_column_relation_test.py::testInvalidNonFrozenUDTRelation`, we check that the query `SELECT * FROM %s WHERE b IS NOT NULL"` should complain about the use of "b IS NOT NULL" (because it's only allowed in a materialized view).

However, a recent regression caused this message to print 
> restriction '(unresolved(b)) IS NOT null' is only supported in materialized view creation

(I know this is a recent regression because when I translated this test, it passed).

I assume the phrasing `(unresolved(b))` means something to us internally, but we should print expressions in error messages using normal CQL syntax - not with our own invented syntax.

**Comment by nyh** [comment]
I also saw this in a manual cqlsh session, and found it unexpected and strange:
```
cqlsh> select * from system_schema.tables where xyz='usertable' ;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Undefined name xyz in where clause ('unresolved(xyz)')"
```

In this case, the `unresolved(xyz)` is not only weird, it's also redundant because it repeats the name `xyz` already mentioned earlier in the same message.

**Comment by nyh** [comment]
Maybe I should generalize this issue not just about printing column in WHERE expressions, but other stuff at well. For example, the statement `DELETE FROM tbl WHERE token(pk) = token(?)` results in the error message:

> The token function cannot be used in WHERE clauses for UPDATE and DELETE statements: ((token(partitionkey)) = <anonymous function>(?))

The part about `<anonymous function>` is misleading and dare I say, wrong (it's not anonymous, it's `token()`).

**Comment by nyh** [comment]
I keep seeing these weird error messages, and it's frustrating (when you see garbage in an error message, it's hard to trust anything in that error message...).

In the review of #13480, @cvybhu said that fixing this issue
> would require us to go through all the places that format expressions for error messages and change the format marker from "{}" to "{:user}".

**Comment by nyh** [comment]
@cvybhu the above patch to `resolve_column()` improves things slightly, but not completely. Consider the CQL request :+1: ```
select * from tab where z=3;
```
Where z isn't a valid column. Before the above patch, the error message is the ugly:

> InvalidRequest: Error from server: code=2200 [Invalid query] message="Undefined name z in where clause ('unresolved(z)')"

After the patch it becomes:

> InvalidRequest: Error from server: code=2200 [Invalid query] message="Undefined name z in where clause ('z')"

It is better in the sense that the silly "unresolved()" thing is gone, but it is bad in the sense that the name of the column, "z", is repeated twice. From the wording of the message, I would have expected what appears to be in the parenthesis to be the full where clause, `'z=3'`, not just `'z'`. Or it would have been enough simply not to print that z again, i.e., just `Undefined name z in where clause.`.

**Comment by cvybhu** [comment]
I think all of the issues mentioned here has been fixed, we can close this.
