### ISSUE TITLE
[CDC]: scylla has to commit a suicide if a concurrent boot is detected

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#10682]
*Installation details*
HEAD: f873806c7c985a5716b2d6b8c7459d45985326a9

*Description*
Apparently a current CDC implementation allows the system to silently enter an invalid state if one tries to start multiple new scylla nodes together.

As a result the CDC handshake can get result in an inconsistent state as opposed to bootstrapping code that would serialize different nodes - nodes will JOIN the ring one after another.

The easiest way to address the issue above is to make the node that wants to join and uses CDC to gracefully shut itself down if it detects that there is an another node that is JOINING right now.

**Comment by vladzcloudius** [comment]
See more details here: https://github.com/scylladb/scylla-docs/issues/3833

**Comment by kbr-** [comment]
In fact, when CDC was implemented, it improved the state of things by adding more checks that try to prevent entering invalid state.

Anyhow, if you purged all Scylla code of CDC code, you would still have "system silently entering invalid state if one tries to start multiple new scylla nodes together".

**Comment by vladzcloudius** [comment]
> Anyhow, if you purged all Scylla code of CDC code, you would still have "system silently entering invalid state if one tries to start multiple new scylla nodes together".

I'm pretty sure you are very wrong about that.
Anyway, you are welcome to prove that with a reproducer, @kbr-

**Comment by vladzcloudius** [comment]
> In fact, when CDC was implemented, it improved the state of things by adding more checks that try to prevent entering invalid state.

Apparently not - hence this GH issue.
Instead of getting all defensive, @kbr- , you'd better either read what I wrote or do the experiments I've suggested. Otherwise it becomes very counterproductive.

**Comment by vladzcloudius** [comment]
And it looks like Kamil IS right - at least in regards to a current `master`:
```
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  492 KB     1            ?       21c5178f-5877-4425-8f70-96440919d6b8  rack1
UJ  127.0.0.2  ?          3            ?       17d5a933-0e3d-45de-baaa-4547b98faa74  rack1
UJ  127.0.0.3  ?          3            ?       2d859ff7-f70e-4158-9e08-ca4dd60c431e  rack1
```

@asias Any comments? This seems to be a regression.

**Comment by vladzcloudius** [comment]
> > @kbr- this is not "assumption" - this is an enforced behavior. I encourage you to do an experiment: try to start all nodes of a new cluster together and see how they are going to join. Pay a particular attention to timestamps on the log.
> 
> Here is the proof that I'm right: [scylladb/scylla-docs#3833 (comment)](https://github.com/scylladb/scylla-docs/issues/3833#issuecomment-1139734138)
> 
> > Apparently not - hence this GH issue.
> 
> I said it **improved** the state of things, not made it perfect. One of the patches that improved it is: [a3f3563](https://github.com/scylladb/scylla/commit/a3f3563828fb7a1a9684a5801e8706b0ce7a4d45) But there are still problems that existed from the beginning of Scylla.

The patch above is irrelevant to the issue in question.
What we need is that a node that is going to bootstrapping or is in the middle of boostrapping (streaming) - the moment it detects that there is another node that is in a JOINING state it should fail the bootstrapping immediately with a corresponding error message.

**Comment by asias** [comment]
> And it looks like Kamil IS right - at least in regards to a current `master`:
> 
> ```
> Status=Up/Down
> |/ State=Normal/Leaving/Joining/Moving
> --  Address    Load       Tokens       Owns    Host ID                               Rack
> UN  127.0.0.1  492 KB     1            ?       21c5178f-5877-4425-8f70-96440919d6b8  rack1
> UJ  127.0.0.2  ?          3            ?       17d5a933-0e3d-45de-baaa-4547b98faa74  rack1
> UJ  127.0.0.3  ?          3            ?       2d859ff7-f70e-4158-9e08-ca4dd60c431e  rack1
> ```
> 
> @asias Any comments? This seems to be a regression. We should commit a suicide if we can't prevent this.

Try: 

--enable-repair-based-node-ops true --allowed-repair-based-node-ops replace,decommission,rebuild,removenode,bootstrap

To enable RBNO for bootstrap

We would see something like:

```
slogger.warn("bootstrap[{}]: Found pending node ops = {}, sleep 5 seconds and check again", uuid, pending_ops);
```

**Comment by vladzcloudius** [comment]
> > And it looks like Kamil IS right - at least in regards to a current `master`:
> > ```
> > Status=Up/Down
> > |/ State=Normal/Leaving/Joining/Moving
> > --  Address    Load       Tokens       Owns    Host ID                               Rack
> > UN  127.0.0.1  492 KB     1            ?       21c5178f-5877-4425-8f70-96440919d6b8  rack1
> > UJ  127.0.0.2  ?          3            ?       17d5a933-0e3d-45de-baaa-4547b98faa74  rack1
> > UJ  127.0.0.3  ?          3            ?       2d859ff7-f70e-4158-9e08-ca4dd60c431e  rack1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @asias Any comments? This seems to be a regression. We should commit a suicide if we can't prevent this.
> 
> Try:
> 
> --enable-repair-based-node-ops true --allowed-repair-based-node-ops replace,decommission,rebuild,removenode,bootstrap
> 
> To enable RBNO for bootstrap
> 
> We would see something like:
> 
> ```
> slogger.warn("bootstrap[{}]: Found pending node ops = {}, sleep 5 seconds and check again", uuid, pending_ops);
> ```

@asias This is all great but what should do users of older/Enterprise releases? To remind you we officially obligated ourselves to fix issues in the 2 last two major releases (OSS and Enterprise independently) and RBNO are still not GA in at least the later.

Could you, please, confirm that the behavior described above is a regression and, if yes, when it was introduced?

**Comment by kbr-** [comment]
>  And I do remember that it once worked.

I think what you remember is that you tried to start bootstrapping a node when another node was in the middle of its bootstrap process (streaming) and that failed.

We still have this protection, but it's dependent on timing. It doesn't always catch the problem, especially when you start bootstrapping two nodes at exactly the same time or just a few seconds apart.

Experiment a you'll see. 
First experiment: make a cluster that has enough data so streaming takes a minute. Then after streaming starts, try to bootstrap another node. It will fail.
Second experiment (you already did this): start bootstrapping two nodes at the same time. More often than not they won't notice each other and will both happily bootstrap.

This was the state when I joined Scylla 2 years ago and I don't remember any changes that were meant to improve this (other than recently added `node_ops` RPC for RBNO), and I was closely observing the topology change code during this time. I think @asias will only confirm.

**Comment by kostja** [comment]
Should be addressed by moving CDC to Raft, which is part of the new centralized topology coordinator.

**Comment by kostja** [comment]
@kbr-scylla fixed with the centralized coordinator, suggest to close.

**Comment by kbr-scylla** [comment]
Yep, fixed in raft-topology mode (currently experimental).
