### ISSUE TITLE
Specially-crafted column names can break indexing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#10707]
In pull-request #10123 we fixed #2962 - indexing of collection columns. At this point one can do things like
```
create index on tab(r);
create index on tab(keys(m));
create index on tab(values(m));
create index on tab(entries(m));
```
The current implementation saved the index's "target" as a string, in the above examples, `r`, `keys(m)`, `values(m)`, `entries(m)`.

There's a problem that in CQL, column names can be anything, if quoted - it can even contain parentheses. We can have a regular column called `keys(m)`, and attempting to index this column currently stores this name naively as the "target", where it will be later confused as an index on some potentially-nonexistent collection m.

As @enedil showed in https://github.com/scylladb/scylla/pull/10123#discussion_r885621331 Cassandra solves this problem by quoting with double-quotes the column name when needed, so target can contain `"keys(m)"` (with quotes) if that's the actual name of the column, or `keys("keys(m")` (when `keys(m)` is the silly name of a map column).

As a first step, we should write a comprehensive test for the various edge-cases involved here - index on a regular column named `keys(m)`, index on a map called `keys(m)`, i.e., `keys("keys(m)")`, columns whose name include quotes (e.g., consider a map column called `keys("m")`, and test which special characters cause the addition of quotes - just parentheses and quotes). All these tests will probably pass on Cassandra but fail on Scylla.
This test could try two things: It should try to use the index in practice (adding data and searching data), but if in some cases it's not possible to reproduce the bugs in this way, we can fall back on reading system_schema.indexes to see what's actually there. Testing system_schema.indexes may be good in any case, if we consider this a public API and we don't want it to accidentally change.

CC @enedil

**Comment by avikivity** [comment]
@nyh do you consider this safe to backport?

Writes post-patch will not be readable pre-patch, but this is only for the specially crafted names, right?

**Comment by nyh** [comment]
I explained in the patch that:

> This change is *mostly* backward compatible: Already-existing indexes will still have unescaped column names stored for their "target" string, and the unescaping code will see they are not wrapped in quotes, and not change them. Backward compatibility will only fail on existing indexes on columns whose name begin and end in the quote characters - but this case is extremely unlikely.

So I think this is safe to backport.

**Comment by avikivity** [comment]
Well, it doesn't backport cleanly, so please do it yourself.

**Comment by mykaul** [comment]
@nyh - will you backport it?

**Comment by denesb** [comment]
> @nyh - will you backport it?

The problem solved itself, all versions not having this were EOL'd. Removing label.
