### ISSUE TITLE
schema disagreement during the 'no corrupt repair' operation having load with large partitions

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#10744]
## Installation details

Kernel Version: 5.13.0-1025-aws
Scylla version (or git commit hash): `5.1.dev-20220602.adda43edc75b` with build-id `eea9cb622b5c595953c10dec6ea50dbf613bc959`
Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-bede707b-5 (34.243.35.77 | 10.0.3.155) (shards: 7)
- longevity-twcs-48h-master-db-node-bede707b-4 (34.245.200.191 | 10.0.2.15) (shards: 7)
- longevity-twcs-48h-master-db-node-bede707b-3 (54.77.119.188 | 10.0.3.133) (shards: 7)
- longevity-twcs-48h-master-db-node-bede707b-2 (34.242.103.244 | 10.0.2.207) (shards: 7)
- longevity-twcs-48h-master-db-node-bede707b-1 (34.246.173.62 | 10.0.1.181) (shards: 7)

OS / Image: `ami-0e4ae5153255d0f42` (aws: eu-west-1)

Test: `longevity-twcs-48h-test`
Test id: `bede707b-905f-4fd9-88ac-47f06dfcd061`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a53b3070cef02c729648aad9c88c951e11318523/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

In this test run we had following list of nemesis applied:

Nemesis Name | Target node | Status | ▲ Start | End
-- | -- | -- | -- | --
disrupt_remove_node_then_add_node | longevity-twcs-48h-master-db-node-bede707b-3 | Terminated | 2022-06-03 06:45:15 | 2022-06-03 20:19:35
disrupt_no_corrupt_repair | longevity-twcs-48h-master-db-node-bede707b-5 | Failed | 2022-06-03 05:29:06 | 2022-06-03 06:23:11
disrupt_start_stop_scrub_compaction | longevity-twcs-48h-master-db-node-bede707b-5 | Succeeded | 2022-06-03 05:03:18 | 2022-06-03 05:11:55
disrupt_network_random_interruptions | longevity-twcs-48h-master-db-node-bede707b-3 | Skipped | 2022-06-03 04:43:32 | 2022-06-03 04:45:53
disrupt_nodetool_enospc | longevity-twcs-48h-master-db-node-bede707b-5 | Succeeded | 2022-06-03 04:20:29 | 2022-06-03 04:26:24
disrupt_nodetool_decommission | longevity-twcs-48h-master-db-node-bede707b-4 | Succeeded | 2022-06-03 03:49:58 | 2022-06-03 04:03:05

Problems started appearing during the `disrupt_no_corrupt_repair` nemesis. 
In this nemesis we start repair operation and drop 10 tables with the `drop_table_during_repair_ks_{i}.standard1` template.

Start of the repair operation on the `node 5` at `05:59:01`:
```
2022-06-03T05:59:01+00:00 longevity-twcs-48h-master-db-node-bede707b-5     !INFO | scylla[10413]:  [shard 0] repair - repair[cbd90ad1-11b7-4184-9f7d-1a4fbd43ebfb]: starting user-requested repair for keyspace drop_table_during_repair_ks_9, repair id 1, options {{ trace -> false}, { jobThreads -> 1}, { incremental -> false}, { parallelism -> parallel}, { primaryRange -> false}}
```

At `06:02:51` we get first schema disagreement.

```
< t:2022-06-03 06:02:51,759 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > 
    Node 10.0.1.181:9042 is reporting a schema disagreement: {
        UUID('b645b8c2-a3ae-39d2-b606-eaeba897eefb'): [
            <DefaultEndPoint: 10.0.1.181:9042>, 
            <DefaultEndPoint: 10.0.3.133:9042>, 
            <DefaultEndPoint: 10.0.2.207:9042>
        ], 
        UUID('971fd2a1-200c-33c9-af30-bcacd61a5489'): [
            <DefaultEndPoint: 10.0.3.155:9042>
        ]
}
``` 
Then second one at `06:07:26`:
```
< t:2022-06-03 06:07:26,521 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > 
    Node 10.0.1.181:9042 is reporting a schema disagreement: {
        UUID('501a1da3-728f-3e60-aea0-f8299f59fb48'): [
            <DefaultEndPoint: 10.0.1.181:9042>,          
            <DefaultEndPoint: 10.0.3.133:9042>
        ], 
        UUID('b645b8c2-a3ae-39d2-b606-eaeba897eefb'): [
            <DefaultEndPoint: 10.0.3.155:9042>, 
            <DefaultEndPoint: 10.0.2.207:9042>
        ]
    }
```

And third one at `06:12:51` which is also the last one:
```
< t:2022-06-03 06:12:51,576 f:thread.py       l:52   c:cassandra.cluster    p:WARNING > 
    Node 10.0.2.207:9042 is reporting a schema disagreement: {
        UUID('ca4feb38-b062-349f-a172-972346733659'): [
            <DefaultEndPoint: 10.0.3.155:9042>,          
            <DefaultEndPoint: 10.0.3.133:9042>, 
            <DefaultEndPoint: 10.0.2.207:9042>
        ], 
        UUID('501a1da3-728f-3e60-aea0-f8299f59fb48'): [
            <DefaultEndPoint: 10.0.1.181:9042>
        ]
    }
```

After this third schema disagreement `node 1` doesn't switch to `501a1da3-728f-3e60-aea0-f8299f59fb48` schema at all.
If we look at nodes logs we see following:

Node 1:
```
2022-06-03T06:07:16+00:00 longevity-twcs-48h-master-db-node-bede707b-1     !INFO | scylla[7716]:  [shard 0] schema_tables - Schema version changed to 501a1da3-728f-3e60-aea0-f8299f59fb48
```

Node 2:
```
2022-06-03T06:07:27+00:00 longevity-twcs-48h-master-db-node-bede707b-2     !INFO | scylla[7733]:  [shard 0] schema_tables - Schema version changed to 501a1da3-728f-3e60-aea0-f8299f59fb48
...
2022-06-03T06:12:41+00:00 longevity-twcs-48h-master-db-node-bede707b-2     !INFO | scylla[7733]:  [shard 3] schema_tables - Schema version changed to ca4feb38-b062-349f-a172-972346733659
```

Node 3:
```
2022-06-03T06:07:24+00:00 longevity-twcs-48h-master-db-node-bede707b-3     !INFO | scylla[7788]:  [shard 0] schema_tables - Schema version changed to 501a1da3-728f-3e60-aea0-f8299f59fb48`
...
2022-06-03T06:12:38+00:00 longevity-twcs-48h-master-db-node-bede707b-3     !INFO | scylla[7788]:  [shard 3] schema_tables - Schema version changed to ca4feb38-b062-349f-a172-972346733659
```

Node 4:
```
2022-06-03T06:07:35+00:00 longevity-twcs-48h-master-db-node-bede707b-5     !INFO | scylla[10413]:  [shard 0] schema_tables - Schema version changed to 501a1da3-728f-3e60-aea0-f8299f59fb48
...
2022-06-03T06:12:42+00:00 longevity-twcs-48h-master-db-node-bede707b-5     !INFO | scylla[10413]:  [shard 3] schema_tables - Schema version changed to ca4feb38-b062-349f-a172-972346733659
```

Then it leads to the following errors on the loaders side at `06:19:07`:

```
loader2:
2h29m44.5s   54749  109600      0 15ms   11ms   5.9ms  3.5ms  2.8ms  1.4ms  1.7ms  
2022/06/03 06:19:07 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.

loader3:
2h27m47.2s   61378  121500      0 13ms   10ms   5.8ms  3.3ms  2.6ms  1.2ms  1.6ms  
2022/06/03 06:19:10 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
```

And after 24 minutes the last loader fails:
```
loader1:
2h55m36.3s   37982   37982      0 22ms   17ms   7ms    2.2ms  1.9ms  885µs  1.2ms  
2022/06/03 06:43:40 Operation timed out for scylla_bench.test - received only 1 responses from 2 CL=QUORUM.
```

Then, at `2022-06-03 06:45:15` starts the last one nemesis - `disrupt_remove_node_then_add_node`.
This nemesis removes node `node 3` which is the one among 3 with agreement on the `ca4feb38-b062-349f-a172-972346733659` schema.

It cannot be removed for 60 minutes and gets removed forcibly:
```
2022-06-03T06:45:21+00:00 longevity-twcs-48h-master-db-node-bede707b-3   !NOTICE | sudo[17869]: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl stop scylla-server.service
...
2022-06-03T06:45:22+00:00 longevity-twcs-48h-master-db-node-bede707b-3  !WARNING | scylla[7788]:  [shard 5] storage_proxy - Failed to apply mutation from 10.0.1.181#5: seastar::abort_requested_exception (abort requested)
...
2022-06-03T07:45:22+00:00 longevity-twcs-48h-master-db-node-bede707b-3  !WARNING | scylla[7788]:  [shard 5] storage_proxy - Failed to apply mutation from 10.0.1.181#5: seastar::abort_requested_exception (abort requested)
2022-06-03T07:45:22+00:00 longevity-twcs-48h-master-db-node-bede707b-3  !WARNING | systemd[1]: scylla-server.service: State 'stop-final-sigterm' timed out. Killing.
2022-06-03T07:45:22+00:00 longevity-twcs-48h-master-db-node-bede707b-3   !NOTICE | systemd[1]: scylla-server.service: Killing process 7788 (scylla) with signal SIGABRT.
```

After the forced removal of the `node 3` we see start of the repair operation on the `node 1` that was in disagreement with all other nodes:
```
2022-06-03T07:48:01+00:00 longevity-twcs-48h-master-db-node-bede707b-1     !INFO | scylla[7716]:  [shard 0] repair - repair[b5689756-1bce-47a0-a307-f67da7be671a]: starting user-requested repair for keyspace system_distributed_everywhere, repair id 2, options {{ trace -> false}, { jobThreads -> 1}, { incremental -> false}, { parallelism -> parallel}, { primaryRange -> false}}
```

But it never succeeds failing to connect to the forcibly removed `node 3` with following errors:
```
2022-06-03T07:53:22+00:00 longevity-twcs-48h-master-db-node-bede707b-1  !WARNING | scylla[7716]:  [shard 0] repair - repair[b5689756-1bce-47a0-a307-f67da7be671a]: Failed to send node_ops_cmd::repair_updater to node=10.0.3.133
```

So, at this stage `node 1` was trying to repair for about 12 hours until the critical event happened at `19:48:42`:
```
2022-06-03 19:48:42.157: (ScyllaBenchEvent Severity.CRITICAL) period_type=end event_id=8d5e1b60-29f3-4650-b712-628e54bf6fd9 duration=16h0m42s: node=Node longevity-twcs-48h-master-loader-node-bede707b-1 [54.220.46.122 | 10.0.2.226] (seed: False)
stress_cmd=scylla-bench -workload=timeseries -mode=write -replication-factor=3 -partition-count=400 -clustering-row-count=10000000 -clustering-row-size=200 -concurrency=100 -rows-per-request=100 -start-timestamp=1654228072483270396 -connection-count 100 -max-rate 50000 --timeout 120s -duration=2880m -error-at-row-limit 1000
errors:
Stress command completed with bad status 1: 2022/06/03 04:21:00 EOF
2022/06/03 04:21:00 EOF
2022/06/03 04:21:00 EOF
2022/06/03 04:21:00 EOF
2022
```
Other 2 nodes were just idle.

- Restore Monitor Stack command: `$ hydra investigate show-monitor bede707b-905f-4fd9-88ac-47f06dfcd061`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=bede707b-905f-4fd9-88ac-47f06dfcd061)
- Show all stored logs command: `$ hydra investigate show-logs bede707b-905f-4fd9-88ac-47f06dfcd061`

## Screenshots:
![Screenshot from 2022-06-07 18-10-22](https://user-images.githubusercontent.com/3796058/172416502-5e6c70e2-1dc2-4a86-b77e-c86ae3152b93.png)
![Screenshot from 2022-06-07 18-07-43](https://user-images.githubusercontent.com/3796058/172416622-7e44545c-e04c-416d-abed-83b495383400.png)

## Logs:
- **db-cluster-bede707b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/db-cluster-bede707b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/db-cluster-bede707b.tar.gz)
- **monitor-set-bede707b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/monitor-set-bede707b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/monitor-set-bede707b.tar.gz)
- **loader-set-bede707b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/loader-set-bede707b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/loader-set-bede707b.tar.gz)
- **normal-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/normal-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/normal-bede707b.log.tar.gz)
- **summary-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/summary-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/summary-bede707b.log.tar.gz)
- **events-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/events-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/events-bede707b.log.tar.gz)
- **output-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/output-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/output-bede707b.log.tar.gz)
- **debug-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/debug-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/debug-bede707b.log.tar.gz)
- **sct-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/sct-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/sct-bede707b.log.tar.gz)
- **error-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/error-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/error-bede707b.log.tar.gz)
- **critical-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/critical-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/critical-bede707b.log.tar.gz)
- **raw_events-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/raw_events-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/raw_events-bede707b.log.tar.gz)
- **warning-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/warning-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/warning-bede707b.log.tar.gz)
- **email_data-bede707b.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/email_data-bede707b.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/email_data-bede707b.json.tar.gz)
- **argus-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/argus-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/argus-bede707b.log.tar.gz)
- **left_processes-bede707b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/left_processes-bede707b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/bede707b-905f-4fd9-88ac-47f06dfcd061/20220603_203532/left_processes-bede707b.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/37/)

**Comment by mykaul** [comment]
Have we executed this recently on 5.2/master? Does it still happen? Unsure why it was not triaged (@DoronArazii  ?)

**Comment by DoronArazii** [comment]
@vponomaryov before i'm throwing this to dev investigation - can you please try to reproduce it so we won't waste time?

**Comment by vponomaryov** [comment]
> @vponomaryov before i'm throwing this to dev investigation - can you please try to reproduce it so we won't waste time?

In last 10 CI runs using various maser versions for about 4 months this bug was not reproduced, but the nemesis set was used a different one.

So, I will run the same nemesis set and see whether it gets reproduced or not.

**Comment by vponomaryov** [comment]
@DoronArazii @mykaul 
The reproducer test run has passed successfully with the same set of nemesis.
So, I think it can be closed.

**Comment by DoronArazii** [comment]
Thanks @vponomaryov
