### ISSUE TITLE
MV - CLUSTERING ORDER BY should reject non clustering columns

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#10767]
**Installation details**
Scylla version (or git commit hash): `5.0.rc5-0.20220515.9da666e77` with build-id `5992da65161c733b3f85b8c93bbbb5151d4d321c`

**Description**
Scylla MVs fails parsing the user input and allows an user to create a view and specify a `CLUSTERING ORDER BY` clause to a non clustering column. The behavior is correct for base tables, however it seems views will accept whatever column we specify and ignore it when building the actual schema.

```cql
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

cqlsh> -- Fails correctly
cqlsh> CREATE TABLE ks.tbl (pk int, ck int, val int, PRIMARY KEY(pk, ck)) WITH CLUSTERING ORDER BY (val ASC, ck DESC);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Only clustering key columns can be defined in CLUSTERING ORDER directive"

cqlsh> -- Works correctly
cqlsh> CREATE TABLE ks.tbl (pk int, ck int, val int, PRIMARY KEY(pk, ck)) WITH CLUSTERING ORDER BY (ck DESC);

cqlsh> -- Works INCORRECTLY
cqlsh> CREATE MATERIALIZED VIEW ks.tbl_view AS SELECT * FROM ks.tbl WHERE pk IS NOT NULL AND ck IS NOT NULL PRIMARY KEY(ck, pk) WITH CLUSTERING ORDER BY (val DESC);
cqlsh> DESC MATERIALIZED VIEW ks.tbl_view ;

CREATE MATERIALIZED VIEW ks.tbl_view AS
    SELECT *
    FROM ks.tbl
    WHERE pk IS NOT null AND ck IS NOT null
    PRIMARY KEY (ck, pk)
    WITH CLUSTERING ORDER BY (pk ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

And yes, Cassandra properly refuses creating such view:

```cqlsh
cqlsh> CREATE MATERIALIZED VIEW ks.tbl_view AS SELECT * FROM ks.tbl WHERE pk IS NOT NULL AND ck IS NOT NULL PRIMARY KEY(ck, pk) WITH CLUSTERING ORDER BY (val DESC);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Clustering key columns must exactly match columns in CLUSTERING ORDER BY directive"
cqlsh> 
```

**Comment by nyh** [comment]
I'm worried that perhaps we have an even bigger bug here - the fact that we didn't notice the wrong column on `CLUSTERING ORDER BY` suggests that **maybe** (I need to write a test to confirm) we don't obey this directive even when it's on the right column (a clustering key column).

Cassandra has unit tests for this CLUSTERING ORDER BY on materialized views in `org/apache/cassandra/cql3/ViewSchemaTest.java` (which I haven't yet translated), but it seems we don't have such a test.

**Comment by nyh** [comment]
After I saw another user using `CLUSTERING ORDER BY`, I decided to do a full investigation on how `CLUSTERING ORDER BY` works in materialized views today - and how it should work. The result is several new tests which I wrote in https://github.com/scylladb/scylladb/pull/12307. I'll copy-paste here the **conclusions** of the tests: Here is a summary of what works correctly and what needs to be fixed:

The tests discover that the CLUSTERING ORDER BY feature in materialized views generally works as expected, but there are three differences between Scylla and Cassandra in this feature. I consider two differences to be bugs (and hence the test is marked xfail) and one a Scylla extension:

1.  When a base table has a reverse-order clustering column and this clustering column is used in the materialized view, in Cassandra the view's clustering order inherits the reversed order. In Scylla, the view's clustering order reverts to the default order. Arguably, both behaviors can be justified, but usually when in doubt we should implement Cassandra's behavior - not pick a different behavior, even if the different behavior is also reasonable. So this test (`test_mv_inherit_clustering_order()`) is marked "xfail".
    If we want to fix this behavior to match Cassandra's we should also consider backward compatibility - what happens if we change this behavior in Scylla now, after we had the opposite behavior in previous releases? We may choose to enshrine Scylla's Cassandra- incompatible behavior here - and document this difference.

2.  The CLUSTERING ORDER BY should, as its name suggests, only list clustering columns. In Scylla, specifying other things, like regular columns, partition-key columns, or non-existent columns, is silently ignored, whereas it should result in an Invalid Request error (as it does in Cassandra). So test_mv_override_clustering_order_error() is marked "xfail".

3.  When a materialized view has several clustering columns, Cassandra requires that a CLUSTERING ORDER BY clause, if present, must specify the order of all of all clustering columns. Scylla, in contrast, allows the user to override the order of only some of these columns - and the rest get the default order. I consider this to be a legitimate Scylla extension, and not a compatibility bug, so marked the test with "scylla_only".

**Comment by denesb** [comment]
Not a regression, no backporting.

**Comment by nyh** [comment]
> Not a regression, no backporting.

I don't insist on backporting, but I have some doubts about the "not a regression" criterion. Do we really only backport regression fixes? Don't regular bug fixes also qualify for backporting?

I think here the appropriate "excuse" to not backport is that this is an error-path bug fix - a user (like @fee-mendes above) can try an **erroneous** command and instead of being told it's an error, Scylla does something stupid. There is no pressing reason to backport such fixes, unless a lot of users are encountering this problem.

**Comment by denesb** [comment]
Yes, we backport more than regression fixes. Unfortunately we don't have a crystal clear critera, we have to consider each bugfix on a case-by-case basis and do a cost vs. benefit analysis. In this case, this is a bug which requires the user to do something nonsense, to be triggered. So I thought even though the fix is simple, it is not worth to backport this.
