### ISSUE TITLE
Commitlog doesn't respect maximum IO buffer size

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#10769]
There are two `class file` methods: `disk_write_max_length()` and `disk_read_max_length()`. They return maximum sizes of IO buffers with which scheduler can (try to) provide its latency goal. If a request exceeds this threshold the IO still happens, but the request goes with its "weight" (or "cost") reduced thus overloading the disk.

IO streams take these sizes into account, so compaction/memtable flush/query code is already on the safe side. Commitlog uses file IO API directly but doesn't take those sizes into account limiting its buffer with hard-coded 128k.

**Comment by elcallio** [comment]
The commitlog buffer management cannot really change much - it is bound by incoming transactions etc. But the write loop could change to segment the writev calls into `disk_write_max_length()` sizes I guess.

**Comment by slivne** [comment]
Seastar issue https://github.com/scylladb/seastar/issues/1099

**Comment by xemul** [comment]
Merged 663f2e2a8f81b57ba3934a79a21c20d011677b17
