### ISSUE TITLE
Replace node causing host-id collision is unsafe and can lead to a split-brain situation

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#10792]
*Installation details*
Scylla version (or git commit hash): `5.0.rc7-0.20220602.41a00c744` with build-id `12671ee67c8f9a992f1e64f5647ff883e5f495e0`
Cluster size: 4
OS: Docker image tag `2c646b3451a8`

*Description*

1. Start n1, n2, n3
2. Stop n3
3. Replace n3 with n4
4. Start n3

At point, there will be a small window on which n1, n2, n3 will see their status as:
```shell
UN  172.17.0.3  ?          256          ?       354722b1-d500-4a11-94d6-3559dfdbf554  rack1
UN  172.17.0.2  928 KB     256          ?       c0f0d576-a230-4e2f-89cc-9e82b4d5d33a  rack1
UN  172.17.0.4  2.02 MB    256          ?       10438643-2cbd-4b2e-9a79-916be6ea3b5d  rack1
```

and **n4** will see itself as (!!!):

```shell
UN  172.17.0.3  1.3 MB     256          ?       354722b1-d500-4a11-94d6-3559dfdbf554  rack1
UN  172.17.0.2  928 KB     256          ?       c0f0d576-a230-4e2f-89cc-9e82b4d5d33a  rack1
UN  172.17.0.9  1.22 MB    256          ?       10438643-2cbd-4b2e-9a79-916be6ea3b5d  rack1
```

After a while, **n4** will no longer appear in its own gossip and n3 will be missing:
```shell
UN  172.17.0.3  1.3 MB     256          ?       354722b1-d500-4a11-94d6-3559dfdbf554  rack1
UN  172.17.0.2  928 KB     256          ?       c0f0d576-a230-4e2f-89cc-9e82b4d5d33a  rack1
```

The logs for **n3** and **n4** will show that one has taken over the other. From **n4**:
```shell
WARN  2022-06-13 22:02:46,202 [shard 0] storage_service - Not updating host ID 10438643-2cbd-4b2e-9a79-916be6ea3b5d for 172.17.0.4 because it's mine
INFO  2022-06-13 22:02:46,202 [shard 0] storage_service - handle_state_normal: remove endpoint=172.17.0.9 token=1654884868917742205
INFO  2022-06-13 22:02:46,202 [shard 0] storage_service - handle_state_normal: Nodes 172.17.0.4 and 172.17.0.9 have the same token 1654884868917742205. 172.17.0.4 is the new owner
INFO  2022-06-13 22:02:46,202 [shard 0] storage_service - handle_state_normal: remove endpoint=172.17.0.9 token=1632238965534354493
(...)
```

**From n3**:
```shell
WARN  2022-06-13 22:01:45,893 [shard 0] storage_service - Not updating host ID 10438643-2cbd-4b2e-9a79-916be6ea3b5d for 172.17.0.9 because it's mine
INFO  2022-06-13 22:01:45,893 [shard 0] storage_service - handle_state_normal: Nodes 172.17.0.9 and 172.17.0.4 have the same token 495177852904727735. Ignoring 172.17.0.9
INFO  2022-06-13 22:01:45,893 [shard 0] storage_service - handle_state_normal: Nodes 172.17.0.9 and 172.17.0.4 have the same token -8860264566310077306. Ignoring 172.17.0.9
(...)
```

At this point, both **n3** and **n4** will be serving queries as coordinators (which is strange, to say least), which means that we can not be certain about the data consistency. Moreover, restarting **n4** at any given moment will cause it to takeover **n3** for the remaining nodes of the cluster. 

Ideally, we should NOT allow two nodes with the same host_id to be up in parallel, such situation should be strictly forbidden and one would expect **n3** to fail to boot in step (4) above.

@asias

**Comment by asias** [comment]
In your procedure:

```
    Start n1, n2, n3
    Stop n3
    Replace n3 with n4
    Start n3
```

You start n3 again after it has been replaced by n4?

The replace procedure requires we have to make sure the dead node is really dead before we replace it. If we decide to replace it, the admin has to make sure the replaced node will not go back to the cluster.

**Comment by fee-mendes** [comment]
> You start n3 again after it has been replaced by n4?

Correct
> 
> 
> The replace procedure requires we have to make sure the dead node is really dead before we replace it.

Right, this is undocumented - however. The [Replace a Dead Node](https://docs.scylladb.com/operating-scylla/procedures/cluster-management/replace-dead-node/) procedure has no mention that a Dead node after getting replaced can come back from the dead.

> If we decide to replace it, the admin has to make sure the replaced node will not go back to the cluster. 

Which is sort of an operational burden. We have seen a similar situation in the field on which a node which was thought to be down got restarted after triggering alerts which were eventually picked up by someone unaware of the operation.

There are many scenarios when such mistake may happen (eg: a hardware refresh, where many replace operations take place and several stop/starts in between of multiple nodes), that it should be simply safer for Scylla to refuse even letting a replaced node to come back from the dead, unless it is explicitly allowed to do so - THEN, yes, the operator who explicitly requested for it should be the one to blame ;-)

**Comment by dorlaor** [comment]
On Tue, Jun 14, 2022 at 9:40 AM Shlomi Livne ***@***.***>
wrote:

> On Tue, Jun 14, 2022 at 5:51 AM fee-mendes ***@***.***> wrote:
>
> > You start n3 again after it has been replaced by n4?
> >
> > Correct
> >
> > The replace procedure requires we have to make sure the dead node is
> > really dead before we replace it.
> >
> > Right, this is undocumented - however. The Replace a Dead Node
> > <
> https://docs.scylladb.com/operating-scylla/procedures/cluster-management/replace-dead-node/
> >
> > procedure has no mention that a Dead node after getting replaced can come
> > back from the dead.
> >
>
> Dead means dead - there is no other way to interpret Dead.
>

We can be friendlier and clearer, since this is risky. I added this doc
request:
https://github.com/scylladb/scylla-doc-issues/issues/860

**Comment by bhalevy** [comment]
ping @fee-mendes, can we close this issue with https://github.com/scylladb/scylladb/commit/dcba652013e0f7c5aa8804f353079060e2a7a6e2?

**Comment by fee-mendes** [comment]
Yes, that's precisely it. Thanks @bhalevy . Closed!
