### ISSUE TITLE
messaging_service.o taking too much memory to compile

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#1081]
I just had compilation of messaging_service.o in distcc die in the middle for no apparent reason (reported a "compiler error").

When I compiled it locally, cc1plus grows to 4 GB of resident memory to complete this compilation.
We should probably find a way - including possibly splitting this source file - to make this compilation take less memory.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 22, 2016 at 08:47:00AM -0700, nyh wrote:
> I just had compilation of messaging_service.o in distcc die in the middle for no apparent reason (reported a "compiler error").
> 
> When I compiled it locally, cc1plus grows to 4 GB of resident memory to complete this compilation.
> We should probably find a way - including possibly splitting this source file - to make this compilation take less memory.
> 
messaging_service.cc has two kind if functions:

 Convenience functions for verb handlers to use - almost all of then templates
 Verb handling functions - non template function

If each verb or set of verbs will be defined in a separate file each of
those files will take less memory to compile (it may take more time
overall though). Since we want those function to be generated from IDL
anyway we can make IDL compiler generate separate file for each verb.

--
			Gleb.

**Comment by nyh** [comment]
6 years have passed, the compiler changed, messaging_service changed, and new source files were added with their own inefficiencies, and we introduced "dev build mode" for day-to-day development which should use less memory. So I don't know if compiling messaging_service.o still takes "too much memory" and if this issue is still relevant. 

However, something which is still easy to see is that  `build/dev/message/messaging_service.o` is still the biggest object file in Scylla's build. It is almost 14 MB in size, more than double the size of the next biggest file (main.o at 6 MB). Usually the object file size is proportional to the build time and the memory used during the build, which suggests that messaging_service.o is still a problem.

**Comment by nyh** [comment]
I'm closing this issue. Nobody has reported an out-of-memory during build in recent years, so there is no reason why we need to single out this specific file from all the problems we have with slow and huge builds (slow compilation and huge object file are usually correlated, see also issue #1). Yes, messaging_service.o is the biggest object file (and twice the size of the next one), but there are many other very large object files, so I don't think it makes sense to have an issue open on this specific file.

**Comment by avikivity** [comment]
@xemul fixed a huge bug there.

**Comment by nyh** [comment]
> @xemul fixed a huge bug there.

What do you mean? When? What bug?

Nobody came back to this issue for years, but I see it did bother @michoecho so he moved to compiling this file first (de0f2c21ec100498387ef83d8d8b16159403a3e0).

**Comment by avikivity** [comment]
Something to do with the hashing templates, that caused excessive compile times. I forget exactly what it was.

**Comment by xemul** [comment]
@avikivity , b5fee0752746a16a419c36dae3d93d13d0d198da , but it was about row_level.o rather than messaging_service.o

**Comment by avikivity** [comment]
Ah, that's why I couldn't find it

**Comment by xemul** [comment]
Some quick numbers. I made a message/handlers.cc file with all headers, all messaging_service::register*, ::unregister* and ::send* helpers from messaging_service.cc. It compiles on its own and:

This file compilation time is ~the same (1m20s) as the messaging_service.cc one, i.e. handlers maintenance code takes all the compilation time.
Removing all the _code_ and leaving _just_ _#include_-s in handlers.cc gives 46s compilation time, i.e. just reading headers is 50%.

For the record -- there are 30 idl headers, 30 idl.impl headers, messaging_service.hh, repair.hh and 35 other scylla headers.

Removing all "idl/*impl.hh"-s gives 10s compilation time, i.e. *impl.hh contribute 80% to the above.
And the cherry on top -- compiling a .cc that _just_ includes messaging_service.hh and repair.hh is 10s.
