### ISSUE TITLE
Write timeouts and bad write latency by Shard 0

### ISSUE THREAD

**Issue by Bychin** [scylladb/scylladb#10982]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.5.2-0.20211114.26aca7b9f
Cluster size: 1+1+1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.9

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): bare metal
Hardware: sockets=2 x Intel(R) Xeon(R) Gold 6238R CPU @ 2.20GHz cores=56 hyperthreading=yes memory=6x 32 Gb DDR4
Disks: RAID 0 of 6 NVMEs 15.36TB each for data and commitlogs

Hello!

After reviewing our metrics, we noticed that sometimes Shard 0 performs very poorly compared to other Shards (green line in all graphs below (rendered by Shard for 1 node), note that in our case `write_request_timeout_in_ms` is set to `450ms`):
<img width="1362" alt="Снимок экрана 2022-07-06 в 12 01 40" src="https://user-images.githubusercontent.com/24765937/177513113-5edd3331-4fa0-4690-8c84-f91ec0fc7ea8.png">
<img width="344" alt="Снимок экрана 2022-07-06 в 12 02 13" src="https://user-images.githubusercontent.com/24765937/177513119-05c0728e-9abc-4fbb-a843-fa46f37bd705.png">
<img width="682" alt="Снимок экрана 2022-07-06 в 12 02 20" src="https://user-images.githubusercontent.com/24765937/177513123-38903ee5-f930-4d2f-8be8-8738be3afaf5.png">

At first we thought that it was a misconfiguration/tuning problem and re-ran `scylla_setup` script and restarted scylla. The content of `perftune.yaml` was:
```
cpu_mask: 0x0000ffff,0xffffffff,0xffffffff,0xffffffff
mode: sq_split
nic:
- eth3
tune:
- net
```
And the content of `cpuset.conf` was (yes, right now we use only 80 vcores for scylla):
```
CPUSET="--cpuset 1-55,57-81 "
```

But after restart, nothing has changed, Shard 0 still sometimes performs very badly.

We then decided to change `sq_split` mode to `mq` in `perftune.yaml` and restart scylla again. Again, no change in terms of Shard 0 performance.

We don't have any more ideas on how to fix this and it looks like a bug to me.

**Comment by Bychin** [comment]
I have updated ScyllaDB Grafana Dashboards and made additional screenshots, hope this helps.
Dashboards are rendered by Shard for 1 node (beccasc-nvme-1), Shard 0 is a light green line on all graphs:

<details>
  <summary>ScyllaDB Detailed Dashboard</summary>
<img width="1367" alt="detailed_01" src="https://user-images.githubusercontent.com/24765937/182903754-030a9873-4382-452d-90a0-76495df7a68a.png">
<img width="1365" alt="detailed_02" src="https://user-images.githubusercontent.com/24765937/182903769-8d159b77-42e5-4273-ab13-2daadba1b7f1.png">
<img width="1362" alt="detailed_03" src="https://user-images.githubusercontent.com/24765937/182903774-bb2129a1-adf1-4e9c-a657-01a1149df754.png">
<img width="1375" alt="detailed_04" src="https://user-images.githubusercontent.com/24765937/182903779-8109138d-4763-40e4-909c-eb3a9af5f495.png">
<img width="1372" alt="detailed_05" src="https://user-images.githubusercontent.com/24765937/182903783-ce87ab37-42bc-4ce2-ad30-d5e10f9667b6.png">
</details>

<details>
  <summary>ScyllaDB Advanced Dashboard</summary>
<img width="1374" alt="advanced_01" src="https://user-images.githubusercontent.com/24765937/182904269-94933894-6f18-4913-a800-d889ed7fc95d.png">
<img width="1356" alt="advanced_02" src="https://user-images.githubusercontent.com/24765937/182904283-5c1e1bfd-61e3-4b20-846d-338f9bf9d271.png">
<img width="1367" alt="advanced_03" src="https://user-images.githubusercontent.com/24765937/182904289-77f7146b-105a-46b3-8b83-b11575102f31.png">
<img width="1362" alt="advanced_04" src="https://user-images.githubusercontent.com/24765937/182904295-3ec4d159-b555-40ef-abd0-e4762bb6f28d.png">
<img width="1352" alt="advanced_05" src="https://user-images.githubusercontent.com/24765937/182904301-f0c3e896-867d-4416-b171-d736f5958fac.png">
<img width="1367" alt="advanced_06" src="https://user-images.githubusercontent.com/24765937/182904303-d9af8af2-3852-410c-806e-b138b93aca77.png">
<img width="1352" alt="advanced_07" src="https://user-images.githubusercontent.com/24765937/182904306-8a2e1be2-72a7-4dc3-9ab0-26b9a5a8bd55.png">
<img width="1365" alt="advanced_08" src="https://user-images.githubusercontent.com/24765937/182904308-aef312a0-5e14-40bf-9b26-9e87f51a4e55.png">
<img width="1362" alt="advanced_09" src="https://user-images.githubusercontent.com/24765937/182904311-b3c2ce6e-4e82-4670-b73d-393a8aa93756.png">

</details>

**Comment by Bychin** [comment]
And `nodetool status becca` output:
```
$ nodetool status becca
Datacenter: OS
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.13.42.225  39.98 TB   256          100.0%            271065e8-2005-4d0b-a945-8b583ebb29b5  RACK1
Datacenter: UD
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.13.42.226  39.97 TB   256          100.0%            a754f0a9-93aa-4161-ba46-9f719f8a7f11  RACK1
Datacenter: UG
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.13.42.224  39.99 TB   256          100.0%            125268d6-9e34-4ba3-92e5-9c3b05da8393  RACK1
```

**Comment by avikivity** [comment]
4.5.2 has reached end-of-life. Please upgrade to a supported version (ideally 5.0.1) and reopen if it reproduces.

**Comment by Bychin** [comment]
JFYI: No problem after upgrading all nodes to 4.6.6
