### ISSUE TITLE
test_resharding_by_smp_decrease[4-TimeWindowCompactionStrategy-15] fails from time to time with count(*) off by one

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#10983]
Latest failure: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/50/testReport/resharding_test/TestReshardingVariants/Run_Dtest_Parallel_Cloud_Machines___HeavyDtest___heavy_split000___test_resharding_by_smp_decrease_4_TimeWindowCompactionStrategy_15_/
```
self = <resharding_test.TestReshardingVariants object at 0x7f50cfa6ce50>
node_count = 4, compaction_strategy = 'TimeWindowCompactionStrategy'
murmur3 = 15

    def test_resharding_by_smp_decrease(self, node_count, compaction_strategy, murmur3):
        """
        Resharding with 10M objects after decreasing the SMP parameter
        and restarting the cluster
        """
>       self._resharding_basic(self.SMP_FOR_DECREASE, rows=100000, murmur3=self.murmur3)

resharding_test.py:371: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
resharding_test.py:178: in _resharding_basic
    self._verify_row_number('standard1', op_cnt)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <resharding_test.TestReshardingVariants object at 0x7f50cfa6ce50>
cf = 'standard1', expected_row_num = 100000, keyspace = 'keyspace1'

    def _verify_row_number(self, cf, expected_row_num, keyspace='keyspace1'):
        session = self.patient_cql_connection(self.node)
        resp = session.execute('SELECT count(*) FROM {0}.{1};'.format(keyspace, cf), timeout=120)
        row_number = rows_to_list(resp)[0][0]
        logger.debug('number of rows: {}'.format(row_number))
>       assert row_number == expected_row_num
E       assert 99999 == 100000
E         +99999
E         -100000

resharding_test.py:140: AssertionError
```

The test successfully verifies the number of rows using `_verify_row_number` before resharding, and also it verifies the data successfully with cassandra-stress.  It seems like the last `SELECT count(*)` returning 99999 is unjustified.

**Comment by bhalevy** [comment]
Previous recent failures:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/43/testReport/junit/resharding_test/TestReshardingVariants/Run_Dtest_Parallel_Cloud_Machines___HeavyDtest___heavy_split000___test_resharding_by_smp_decrease_4_TimeWindowCompactionStrategy_15_/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/26/testReport/junit/resharding_test/TestReshardingVariants/Run_Dtest_Parallel_Cloud_Machines___HeavyDtest___heavy_split000___test_resharding_by_smp_decrease_4_TimeWindowCompactionStrategy_15_/

**Comment by slivne** [comment]
AFAIK we have changed the way we do select count(*) 

@psarna / @havaker / @Jadw1 - I am not sure who should check this

**Comment by psarna** [comment]
@bhalevy distributing aggregates is done by adding another layer of indirection, a supercoordinator. This supercoordinator splits the query into smaller ranges and sends these ranges to be fulfilled by "regular" coordinators. Everything else, including the consistency level, is preserved, so all of these coordinators would use QUORUM/ALL, whatever the user specified. In case any part of the distribution fails, e.g. one of the coordinators fails to send the partial result to the supercoordinator, the supercoordinator takes it upon himself to gather the result. In other words, the supercoordinator falls back to acting as a regular coordinator if the distribution fails.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla-dtest/pull/2766 verifies the number of rows with QUORUM consistency level.
Let's see if that solves the problem and if so, this issue can be closed.

**Comment by bhalevy** [comment]
The issue seem to be solved with https://github.com/scylladb/scylla-dtest/commit/a11c3c1121b800e4abcbeedf6156ff290a25eaea, closing.
