### ISSUE TITLE
Strong impact of nodetool repair on the cluster

### ISSUE THREAD

**Issue by Bychin** [scylladb/scylladb#11107]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.5.2-0.20211114.26aca7b9f
Cluster size: 1+1+1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.9

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): bare metal
Hardware: sockets=2 x Intel(R) Xeon(R) Gold 6238R CPU @ 2.20GHz cores=56 hyperthreading=yes memory=6x 32 Gb DDR4
Disks: RAID 0 of 6 NVMEs 15.36TB each for data and commitlogs

Hello!

When trying to run nodetool repair as is (on 1 node with/without the -pr flag), we get bad timings for 99pct and max on the coordinator and client, which hit the timeout, many retrays.

<img width="1371" alt="Снимок экрана 2022-07-20 в 12 49 34" src="https://user-images.githubusercontent.com/24765937/180391471-dc2b7815-4bd9-4931-b837-f205976759d7.png">
<img width="693" alt="Снимок экрана 2022-07-20 в 12 49 41" src="https://user-images.githubusercontent.com/24765937/180391484-7565d1eb-c45d-4ed1-ac4b-1687aa2f4098.png">
<img width="349" alt="Снимок экрана 2022-07-20 в 12 49 49" src="https://user-images.githubusercontent.com/24765937/180391487-ace64e04-46cf-4163-a4ad-165dee86ab08.png">

It can be seen that repair heavily loads the CPU and there is a suspicion that in general this process has too much CPU quota, which is why it is not enough to process client requests:
<img width="349" alt="Снимок экрана 2022-07-20 в 12 51 38" src="https://user-images.githubusercontent.com/24765937/180391490-39d002cf-f19a-4ea4-9846-070211416220.png">

We tried to run repair with finer settings using `cassandra_repair.py`, playing with the number of `workers` (parallel processing) and `steps` (number of splits of one range). But only the configuration with 1 and 100, respectively, did not affect write requests. In such a gentle mode, the repair of the node would be completed in 6 days, which is unacceptable for us.

We also tried to run repair with the `-pull` and `-hosts` parameters (specifying only one node as a data source), but the situation has not changed much - there are too many timeout errors and a noticeable degradation of timings on the client.

I understand that the repair operation between nodes in different data centers is the most difficult, but I still think that with our hardware it should not have such a strong impact on the cluster in terms of degradation of servicing client requests.

**Comment by Bychin** [comment]
And `nodetool status becca` output:
```
$ nodetool status becca
Datacenter: OS
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.13.42.225  39.98 TB   256          100.0%            271065e8-2005-4d0b-a945-8b583ebb29b5  RACK1
Datacenter: UD
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.13.42.226  39.97 TB   256          100.0%            a754f0a9-93aa-4161-ba46-9f719f8a7f11  RACK1
Datacenter: UG
==============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.13.42.224  39.99 TB   256          100.0%            125268d6-9e34-4ba3-92e5-9c3b05da8393  RACK1
```

**Comment by avikivity** [comment]
4.5.2 has reached end-of-life and is not supported. You should upgrade to 4.6.

Note that 5.0 has a new I/O scheduler that greatly reduces the impact of repair, so I recommend upgrading to 5.0.1.

**Comment by Bychin** [comment]
JFYI: No problem after upgrading all nodes to 5.0.1
