### ISSUE TITLE
Docs: Issue in page Consistency Levels

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11126]
I would like to report an issue in page https://docs.scylladb.com/master/cql/consistency

### Problem

the consistency calculator spacing is broken, looks off
https://docs.scylladb.com/stable/cql/consistency.html#consistency-level-calculator

###  Suggest a fix
Move the consistency calculator to a dedicated page

**Comment by tzach** [comment]
![image](https://user-images.githubusercontent.com/170200/180948795-9240a535-bdbf-4837-aee1-350cfe26de86.png)

**Comment by annastuchlik** [comment]
Fixed with https://github.com/scylladb/scylladb/pull/11149
