### ISSUE TITLE
segfault during service initialization on GCE with non-ephemeral disks 

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#11121]
it happened with `5.0.0-0.20220706.1ad59d6a7 with build-id 271eb4ed645d5b1c4564acca7fe5f8f400245726`, but this time there is a `Segmentation fault on shard 1.`:

```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:750
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:780
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:792
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3668
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3654
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3650
?? ??:0
std::vector<unsigned int, std::allocator<unsigned int> >::operator[](unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:1046
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4065
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4123
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
/data/scylla-s3-reloc.cache/by-build-id/271eb4ed645d5b1c4564acca7fe5f8f400245726/extracted/scylla/libexec/scylladb/libreloc/libpthread.so.0 0x9298 
/data/scylla-s3-reloc.cache/by-build-id/271eb4ed645d5b1c4564acca7fe5f8f400245726/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x100352 
```

@xemul asked in [this comment](https://github.com/scylladb/scylla/issues/10927#issuecomment-1191476419) to report it in a new issue...
and this is the content of the comment:
```
The crashing place is

    auto alloc_io_queues = [&ioq_topology, &disk_config] (shard_id shard) {
        for (auto& topo : ioq_topology) {
            auto& io_info = topo.second;
            auto group_idx = io_info.shard_to_group[shard]; <<<<<<<<<<<<<<<<< HERE
            std::shared_ptr<io_group> group;
```

## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-gce-image-pd-jenkins-db-node-2507d686-0-1 (34.139.32.239 | 10.142.1.94) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/7829706404308503910` (gce: us-east1)

Test: `artifacts-gce-image-persistent-disk-test`
Test id: `2507d686-cc6f-4a12-982c-726c962a07a6`
Test name: `scylla-5.0/artifacts/artifacts-gce-image-persistent-disk-test`
Test config file(s):

- [gce-image-persistent-disk.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f6a114e4d29c1865df8246e8e6e1d433169d7082/test-cases/artifacts/gce-image-persistent-disk.yaml)

## Issue description

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2507d686-cc6f-4a12-982c-726c962a07a6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2507d686-cc6f-4a12-982c-726c962a07a6)
- Show all stored logs command: `$ hydra investigate show-logs 2507d686-cc6f-4a12-982c-726c962a07a6`

## Logs:
- **db-cluster-2507d686.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2507d686-cc6f-4a12-982c-726c962a07a6/20220706_121401/db-cluster-2507d686.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2507d686-cc6f-4a12-982c-726c962a07a6/20220706_121401/db-cluster-2507d686.tar.gz)
- **sct-runner-2507d686.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2507d686-cc6f-4a12-982c-726c962a07a6/20220706_121401/sct-runner-2507d686.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2507d686-cc6f-4a12-982c-726c962a07a6/20220706_121401/sct-runner-2507d686.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts/job/artifacts-gce-image-persistent-disk-test/13/)

**Comment by DoronArazii** [comment]
@xemul ping, please have a look

**Comment by xemul** [comment]
Ah, it's due to #10927, but this time it's non-0 shard that steps on an io-queues that had been released on misconfiguration
