### ISSUE TITLE
table::snapshot aborts if it fails to allocate a snapshot_manager

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11132]
As implemented in https://github.com/scylladb/scylla/blob/1d39d803affd3c6e49d2319ef1591d2d79ac188f/replica/table.cc#L1386-L1393
table::snapshot uses a critical allocation that if fails, it cannot coordinate the snapshot process among all shards, thus we defer to aborting rather than hanging is seen on multiple occasions, e.g. when running OOM.

**Comment by bhalevy** [comment]
The plan to fix this issue is by refactoring table::snapshot and introducing a static `table::snapshot_on_all_shards` function that will orchestrate the snapshot process, without resorting to allocating this snapshot_manager object.

**Comment by avikivity** [comment]
This is part of a huge change (ba42852b0e1d2bec677e60a863c505a637884e04), not backporting. We'll just hope that the odds of an OOM happening while a snapshot is taken are low.
