### ISSUE TITLE
unset value is evil

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#11143]
The cql3 code is littered for checks of unset values. We have a raw_value type, one of whose reasons for existence is to support unset values. Yet unset is only supported by a tiny subset of operations - UPDATE and INSERT, where the unset is a bind variable directly corresponding to a regular or static column being updated.

**Comment by avikivity** [comment]
Plan for fixing:
 - update the prepare code to determine which bind variable can be unset
    - initially, all can be unset
    - when preparing in a context that doesn't support unset (e.g. anything that isn't in the right clause of a non-LWT INSERT or UPDATE statement), mark everything recursively as not supporting unset
    - when preparing in a context that does support unset, only allow the top-level to be unset. e.g. `SET A = :supports_unset` works, but `SET A = ( 5, :doesnt_support_unset)` doesn't.
  - build a vector of which bind variables support unset, and a flag if non of them do. Store in the prepared statement.
  - when executing a query, the query processor checks if any bind variables that don't accept unset are unset, and fails the query if they do
  - unset bind variables that do support unset are materialized as NULLs, and a separate flag in a vector is set to indicate the variable is unset
  - the operation that supports unset is split into two implementations: one for general expressions, one for single bind variables. The second one adds a check for the separate flag.

As a result, most of the code can forget about unset values.

**Comment by nyh** [comment]
See also #10358, where I asked for more-or-less the same thing, and also mentions a few xfailing tests that will be fixed by making errors on UNSET more regular.

**Comment by slivne** [comment]
Lets add this to the queue of the CQL rewrite and decide when i should be added

**Comment by psarna** [comment]
@cvybhu please take a look at the suggested fix plan (https://github.com/scylladb/scylladb/issues/11143#issuecomment-1197114560). In particular:
 1. if you have any remarks
 2. if you prefer to proceed with analyzed_where_clause first, or whether this one should go first, or perhaps both in parallel

**Comment by cvybhu** [comment]
> @cvybhu please take a look at the suggested fix plan ([#11143 (comment)](https://github.com/scylladb/scylladb/issues/11143#issuecomment-1197114560)). In particular:
> 
>     1. if you have any remarks
> 
>     2. if you prefer to proceed with analyzed_where_clause first, or whether this one should go first, or perhaps both in parallel

The plan sounds very nice, unset values are annoying.

  
> when preparing in a context that does support unset, only allow the top-level to be unset. e.g. SET A = :supports_unset works, but SET A = ( 5, :doesnt_support_unset) doesn't.

Cassandra allows unset values in fields of user defined types, something like this works there:
```rust
let set_fields = session.prepare("update ks.my_tab set m = {a: ?, b: ?, c: ?} WHERE p = 0").await?;
session.execute(&set_fields, (Unset, Unset, 5)).await?;
```
I guess instead of this the user can write:
```rust
let set_fields = session.prepare("update ks.my_tab set m.a = ?, m.b = ?, m.c = ? where p = 0").await?;
```
However to be a drop-in replacement we would have to support this as well
  
Another way to do this would be to move `unset_value` out of `expr::constant`. We could make the constant keep `bytes_opt` instead of `raw_value`. `unset_value` could be made into a variant of expression, or even a separate thing altogether. `evaluate()` would just fail if it encounters an `unset_value`.

All the code that has to care about unset values would be forced to look at the arguments and see if one of them is a bind variable which contains an `unset_value`. Such code already has to contain special cases for unset values, so maybe it wouldn't be too much of a problem.

This way support for `unset_value` would happen organically - it will throw an error everywhere except in cases where the code actually supports it. We wouldn't have to think about specifying cases where it's supported and where it isn't.

> if you prefer to proceed with analyzed_where_clause first, or whether this one should go first, or perhaps both in parallel

I think doing both in parallel shouldn't cause any issues, `analyzed_where_clause` will moslty manipulate already prepared expressions. The proposed plan would happen during preparation, so there should be few conflicts.

**Comment by cvybhu** [comment]
I wonder if something similar could be done for empty values

**Comment by avikivity** [comment]
> > @cvybhu please take a look at the suggested fix plan ([#11143 (comment)](https://github.com/scylladb/scylladb/issues/11143#issuecomment-1197114560)). In particular:
> > ```
> > 1. if you have any remarks
> > 
> > 2. if you prefer to proceed with analyzed_where_clause first, or whether this one should go first, or perhaps both in parallel
> > ```
> 
> The plan sounds very nice, unset values are annoying.
> 
> > when preparing in a context that does support unset, only allow the top-level to be unset. e.g. SET A = :supports_unset works, but SET A = ( 5, :doesnt_support_unset) doesn't.
> 
> Cassandra allows unset values in fields of user defined types, something like this works there:
> 
> ```rust
> let set_fields = session.prepare("update ks.my_tab set m = {a: ?, b: ?, c: ?} WHERE p = 0").await?;
> session.execute(&set_fields, (Unset, Unset, 5)).await?;
> ```
> 
> I guess instead of this the user can write:
> 
> ```rust
> let set_fields = session.prepare("update ks.my_tab set m.a = ?, m.b = ?, m.c = ? where p = 0").await?;
> ```
> 
> However to be a drop-in replacement we would have to support this as well

We should. So just add it to the cases we support. So long as we limit where unset values are used.

btw, if a bind variable is used both in an unset-acceptable and unset-unacceptable context, we should reject unsets.

```cql
UPDATE foo SET u = :u, v = :v IF v = :u
```

Unset is unacceptable for IF so it should be rejected for SET too.

> 
> Another way to do this would be to move `unset_value` out of `expr::constant`. We could make the constant keep `bytes_opt` instead of `raw_value`. `unset_value` could be made into a variant of expression, or even a separate thing altogether. `evaluate()` would just fail if it encounters an `unset_value`.

`constant` definitely can't have unsets, but still as long as bind_variable can be unset, any expression evaluation must consider it.

> 
> All the code that has to care about unset values would be forced to look at the arguments and see if one of them is a bind variable which contains an `unset_value`. Such code already has to contain special cases for unset values, so maybe it wouldn't be too much of a problem.

The problem is that any evaluation can inherit it from a bind_variable input.

> 
> This way support for `unset_value` would happen organically - it will throw an error everywhere except in cases where the code actually supports it. We wouldn't have to think about specifying cases where it's supported and where it isn't.
> 
> > if you prefer to proceed with analyzed_where_clause first, or whether this one should go first, or perhaps both in parallel
> 
> I think doing both in parallel shouldn't cause any issues, `analyzed_where_clause` will moslty manipulate already prepared expressions. The proposed plan would happen during preparation, so there should be few conflicts.

**Comment by cvybhu** [comment]
I think we can close this now, #12517 has been merged.

**Comment by mykaul** [comment]
> I think we can close this now, #12517 has been merged.

Great - thanks!
