### ISSUE TITLE
Removenode not working in 5.0.0 with rbno

### ISSUE THREAD

**Issue by geobeau** [scylladb/scylladb#11159]
With 5.0.0, we don't seem to be able to perform removenode anymore.

# Steps to reproduce
* Configure with: `allowed_repair_based_node_ops: "replace,bootstrap,removenode,decommission,rebuild"`
* Start new cluster spawning 2 nodes in two dc (total 4, 14 shards per nodes)
* Cluster should be all UN
* Stop a node
* Perform `nodetool removenode <UUID>` from a node of the same dc
* Node is not removed - removenode does not finish

Removal of the node was expected (even after days, for an empty cluster)

# Investigation

Let's consider this topology:
DC1
- nodeA -> removenode coordinator
- nodeB -> Dead node

DC2
- nodeC
- nodeD

`nodetool removenode <UUID of nodeB>` is initiated on nodeA: the repair is initated but never terminate
The removenode is blocked because nodeC and nodeD don't terminate their own repair.
nodeC and nodeD don't terminate their repair because one or two shards (out of 14) are not able to finishing their repair. They get stuck while doing rpc for row_level repairs: https://github.com/scylladb/scylladb/blob/scylla-5.0.1/repair/row_level.cc#L1482-L1503

After entering: `send_repair_row_level_start` for a distant node, they never finish.

This can be seen when terminating a node later in the cluster:
```
WARN  2022-07-28 08:00:15,456 [shard 2] repair - repair id [id=1, uuid=a289d6cb-81e7-456c-84be-8fecf62f1775] on shard 2, keyspace=system_traces, cf=node_slow_log, range=(-4806827859878074922, -4804163522638383805], got error in row level repair: seastar::rpc::closed_error (connection is closed)
```

We have been able to reproduce on a new cluster in 5.0.1 and a production cluster in 4.6.3 (70 nodes).
Decomission, join and replace work properly.
Using stream instead of repair works.

# Details

*Installation details*
Scylla version (or git commit hash): 522d0a81e7c0c43f51401b95f0fb22204451f599 (right below 5.0.1)
Cluster size: 4 (2 in dc1 + 2 in dc2) 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker/Centos

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker
Hardware: sockets=1 cores=8 hyperthreading=16 memory=256G
Disks: (SSD/HDD, count) 6 SSD (RAID 0)

**Comment by geobeau** [comment]
I actually reproduce on my version with 4 nodes in the same DC.

**Comment by asias** [comment]
We saw similar problem here:

https://github.com/scylladb/scylladb/issues/11354#issuecomment-1235150549

**Comment by asias** [comment]
We might found the root cause here:

https://github.com/scylladb/scylladb/issues/11507#issuecomment-1336358038

**Comment by geobeau** [comment]
@asias 

> We might found the root cause here:
> 
> [#11507 (comment)](https://github.com/scylladb/scylladb/issues/11507#issuecomment-1336358038)

Have you been able to produce a fix that we could test on our master? In the other issue, it seems to have no update after "We need rpc expert to take a look.".

**Comment by asias** [comment]
There are fixes like below in newer scylla version.  Reopen if you still have this issue with 5.2. 

https://github.com/scylladb/seastar/issues/1146
https://github.com/scylladb/seastar/pull/1500
