### ISSUE TITLE
Scylla alternator table "default_time_to_live" doesn't work for alternator write request

### ISSUE THREAD

**Issue by codingcuisg** [scylladb/scylladb#11168]
Hi team, 

I am using scylla 4.4.8 and alternator for testing the table level TTL, alternator TTL feature is not officially supported on this version yet so I was testing about turning on table level TTL for expiring the data. 

The table level TTL is working for normal cql insert/update however this approach is not working with alternator write request. 

Trying to understand what's the difference there, any specific purpose of this design or it's a bug ? 

**Table schema:**

`CREATE TABLE alternator_amphawa_alternator_v2.amphawa_alternator_v2 (
    pk text,
    sk text,
    ":attrs" map<text, blob>,
    PRIMARY KEY (pk, sk)
) WITH CLUSTERING ORDER BY (sk ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'enabled': 'false', 'keys': 'NONE', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 86400
    AND gc_grace_seconds = 86400
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = 'NONE';

scylla_tags = {}`

**sstable dump:**
result after cql insert
`{
    "partition" : {
      "key" : [ "runzetest_pk" ],
      "position" : 1645780
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 1645835,
        "clustering" : [ "runzetest_sk" ],
        "liveness_info" : { "tstamp" : "2022-07-30T13:04:43.716122Z", "ttl" : 86400, "expires_at" : "2022-07-31T13:04:43Z", "expired" : false },
        "cells" : [ ]
      }
    ]
  },`
result after alternator update item
`{
    "partition" : {
      "key" : [ "AD-1-417946977603439519/ads_ctr" ],
      "position" : 5448
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 5667,
        "clustering" : [ "ADSITE-1-FOOD_BANNER" ],
        "liveness_info" : { "tstamp" : "2022-07-30T09:10:12.345982Z" },
        "cells" : [
          { "name" : "\":attrs\"", "path" : [ "historical_click" ], "value" : "0x0108ecea93970618035a03120114" },
          { "name" : "\":attrs\"", "path" : [ "historical_ctr" ], "value" : "0x0108ecea93970618056a061204cc68913b" },
          { "name" : "\":attrs\"", "path" : [ "historical_cvr" ], "value" : "0x0108ecea93970618056a06120400000000" },
          { "name" : "\":attrs\"", "path" : [ "historical_impression" ], "value" : "0x0108ecea93970618035a0412029b23" }
        ]
      }
    ]
  },`

Thanks

**Comment by slivne** [comment]
default_time_to_live should not work alternator tables - there is a different feature for alternator ttl #5060, having said that you are not the first to request this #9465. 

The extension to support something like default ttl needs to be approved by product and also provide a way to set this via alternator API - not via CQL (there is a draft pr https://github.com/scylladb/scylladb/pull/11194) 

As this is a duplicate I am closing this issue - please track the others
