### ISSUE TITLE
Warning in Scylla install on Ubuntu 22.04 :  Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11186]
*Installation details*
Scylla version (or git commit hash): 5.0.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 22.04

```
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys d0a112e067426ab2
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.08ZVGdNgXa/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys d0a112e067426ab2
gpg: key D0A112E067426AB2: "ScyllaDB Package Signing Key 2022 <security@scylladb.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
 ```

**Comment by benipeled** [comment]
Following the apt-key deprecation, we should switch to importing the key with gpg

`gpg --homedir /tmp --no-default-keyring --keyring <path-to-key> --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys <key-id>`

And add the signed-by flag to the scylla.list file

`deb [arch=amd64,arm64 signed-by=<path-to-key>] http://path/to/repo stable main`


PS> there is a great explanation about the apt-key deprecation https://askubuntu.com/a/1307181

**Comment by slivne** [comment]
@benipeled / @yaronkaikov is this fixed ?

**Comment by benipeled** [comment]
@slivne the gpg (as described above) recently added to SCT and machine-image,
next step is to switch from apt-key to gpg and add the `signed-by` on pkg (and later remove the apt-key refs from the other repos)

PS> this is WARN msg only, installation with apt-key is still works as expected

**Comment by benipeled** [comment]
The repo file for Scylla >= 5.1 and Scylla-Enterprise >= 2022.2 has been updated,
It's now includes the `signed-by=/etc/apt/keyrings/scylladb.gp` ref

Installation guides on https://www.scylladb.com/download have been updated accordingly
