### ISSUE TITLE
Consumer receives out of order mutation fragments when consuming a frozen_mutation

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11198]
In addition to https://github.com/scylladb/scylladb/issues/11147, as found by @mikolajsieluzycki 
`frozen_mutation::consume` and `consume_gently` return the mutation fragments in non-monotonically increasing order,
consuming first all range tombstones (if any) and then all clustering rows, basically in the order they are serialized in the frozen_mutation.

We want those functions to interleave the consumed range tombstones and clustering rows, in position_in_partition order so we can produce an ordered v2 mutation fragment stream when using each range_tombstone and clustering_row position to flush the range_tombstone_change_generator at this position as we do when consuming a mutation.

Note that currently we don't yet consume frozen_mutation in reverse but rather we defer to unfreezing it and consuming the thawed mutation - see https://github.com/scylladb/scylladb/blob/a4844826fcc7a845a03a1c927a5bfe3d57c09901/mutation_partition.cc#L2214-L2226

With this issue fixed we'd be able also to consume the frozen_mutation in reverse as we do in `mutation::consume*`

**Comment by avikivity** [comment]
@bhalevy I understand there is no impact on existing code, therefore no need to backport. Is this correct?

**Comment by bhalevy** [comment]
> @bhalevy I understand there is no impact on existing code, therefore no need to backport. Is this correct?

yes, that's correct.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
