### ISSUE TITLE
Change the `system.local`'s `rpc_address` to hold local node config's `broadcast_rpc_address`, not `rpc_address`

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#11201]
In Scylla and Cassandra (pre-4.1), there are two addresses related to handling user requests:

- `rpc_address` - the address that Scylla/Cassandra binds to and listens for CQL connections. Notably, it can be set to 0.0.0.0 so that Scylla listens on all interfaces.
- `broadcast_rpc_address` - the address that Scylla/Cassandra is supposed to advertise to the drivers so that they know to which address to connect to.

Both `system.local` and `system.peers` tables have a `rpc_address`:

- In `system.local` it corresponds to the configuration's `rpc_address`,
- In `system.peers` it corresponds to the configuration's `broadcast_rpc_address`.

Despite the fact that what `system.peers` does sounds more inconsistent, exposing node's `broadcast_rpc_address` is more useful as `rpc_address` may be just `0.0.0.0` which doesn't allow drivers to connect. In fact, in Cassandra 4.1, `system.local`'s `rpc_address` is also changed to contain `broadcast_rpc_address` (relevant issue: https://issues.apache.org/jira/browse/CASSANDRA-11181).

**Comment by piodul** [comment]
cc: @psarna @wprzytula

**Comment by avikivity** [comment]
Not a bug, not backporting.
