### ISSUE TITLE
repair_history_maps should not be defined in global scope

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11208]
Change a8ad385ecd3 introduced
```
thread_local std::unordered_map<utils::UUID, seastar::lw_shared_ptr<repair_history_map>> repair_history_maps;
```

We're trying to avoid global scoped variables as much as we can so this should probably be embedded in some sharded service.
Naturally, the repair service comes into mind.

Cc @asias, @xemul

**Comment by bhalevy** [comment]
The tricky part here is that the repair history maps are needed in repair tombstone_gc_mode both on the coordinator side of the node when compacting for query and on the replica side when compacting for compaction.

We can get access to the compaction manager relatively easily on the replica side of things but it's harder on the coordinator side.

**Comment by asias** [comment]
This is supposed to be low priority. I am not sure why it is marked as high.

**Comment by avikivity** [comment]
Not sure why this has the High label (or even bug). Looks like a refactoring that doesn't need backports. @bhalevy ?

**Comment by bhalevy** [comment]
> Not sure why this has the High label (or even bug). Looks like a refactoring that doesn't need backports. @bhalevy ?

True, it's a work item, not a bug.
No backport is required (and the change is quite intrusive so the bar is even higher for it for backporting)
