### ISSUE TITLE
Issue in page Getting Started With ScyllaDB Alternator - is pointing to the nightly build

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11218]
I would like to report an issue in page https://docs.scylladb.com/master/alternator/getting-started

### Problem
"Because Alternator is still improving quickly, it is recommended to run the latest nightly build. Make sure you have the latest nightly image by running: docker pull scylladb/scylla-nightly:latest"

@nyh IMHO we should now point users to latest stable version

**Comment by nyh** [comment]
@tzach what is the latest stable version? scylladb/scylla:latest?
I don't see anything documented about this in https://hub.docker.com/r/scylladb/scylla/... Is latest the "latest" release in the chronological sense or latest in the numerical sense? I mean, if 5.0.3 came out after 5.1, which will be the "latest"?
I'll open a separate issue about that in scylla packaging...

**Comment by tzach** [comment]
Last patch verion of the lastr minor version
But for the doc, we do not have to point to a spesfic version, just send the user to the latest, and not nightly.

**Comment by nyh** [comment]
I'll send a patch to update the docker instructions to not use a nightly version, but maybe we (@eliransin) need to rethink this entire document and why it exists and how it describes its own purpose.
It's basically a "how to play with Alternator on your own laptop" document, without clearly saying so (it begins by telling you that "This section will guide you through the steps for setting up the cluster", but then running just one node locally).

**Comment by nyh** [comment]
The link to https://www.scylladb.com/download/open-source/#docker is also worthless (points to some generic "getting started" page so I'll fix that link as well :-(

**Comment by tzach** [comment]
My point is "nightly" was recomended when Alternator was very new, and there was not stable release supporting it.
This is not the case anymore.

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
