### ISSUE TITLE
Applying a range tombstone which covers many range tombstones is quadratic

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#11211]
Range tombstones are kept in memory (cache/memtable) in range_tombstone_list. It  keeps them deoverlapped, so applying a range tombstone which covers many range tombstones will erase existing range tombstones from the list. This operation needs to be exception-safe, so range_tombstone_list maintains an undo log. This undo log will receive a record for each range tombstone which is removed. For exception safety reasons, before pushing an undo log entry, we reserve space in the log by calling std::vector::reserve(size() + 1). This is O(N) where N is the number of undo log entries. Therefore, the whole application is O(N^2).

This can cause reactor stalls and availability issues when replicas apply such deletions.

**Comment by bhalevy** [comment]
> For exception safety reasons, we before pushing an undo log entry, we reserve space in the log by calling std::vector::reserve(1).

you mean `std::vector::reserve(vector.size() + 1)`?

> This is O(N) where N is the number of undo log entries.

Doesn't the underlying implementation reallocate the container capacity in exponentially increasing size (up to a point)
so that actual penalty is practically O(log(n))?

**Comment by raphaelsc** [comment]
> > For exception safety reasons, we before pushing an undo log entry, we reserve space in the log by calling std::vector::reserve(1).
> 
> you mean `std::vector::reserve(vector.size() + 1)`?
> 
> > This is O(N) where N is the number of undo log entries.
> 
> Doesn't the underlying implementation reallocate the container capacity in exponentially increasing size (up to a point) so that actual penalty is practically O(log(n))?

"Correctly using reserve() can prevent unnecessary reallocations, but inappropriate uses of reserve() (for instance, calling it before every [push_back()](https://en.cppreference.com/w/cpp/container/vector/push_back) call) may actually increase the number of reallocations (by causing the capacity to grow linearly rather than exponentially) and result in increased computational complexity and decreased performance."

**Comment by tgrabiec** [comment]
> > For exception safety reasons, we before pushing an undo log entry, we reserve space in the log by calling std::vector::reserve(1).
> 
> you mean `std::vector::reserve(vector.size() + 1)`?

Yes

> 
> > This is O(N) where N is the number of undo log entries.
> 
> Doesn't the underlying implementation reallocate the container capacity in exponentially increasing size (up to a point) so that actual penalty is practically O(log(n))?

Not during explicit reserve().

**Comment by avikivity** [comment]
Although not a regression and not a trivial fix, backported to 5.0 and 5.1 since it can be quite painful.

Left 4.6 alone, users who need it can update to 5.0.

**Comment by rayakurl** [comment]
@tgrabiec - as agreed, please run a unitestst in order to make sure it's safe to release 2022.1.4 on  2022.1.4-0.20221218.b3c6acb11 with build-id ef0f471d3e2071d6f6546ff797eb81f475399326
