### ISSUE TITLE
Issue in page scylla-types

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11213]
I would like to report an issue in page https://docs.scylladb.com/master/operating-scylla/admin-tools/scylla-types

### Problem

The link to the type-mapping document leads to a 404 page: https://github.com/scylladb/scylla/blob/master/docs/design-notes/cql3-type-mapping.md

###  Suggest a fix

**Comment by denesb** [comment]
Said document was moved to https://github.com/scylladb/scylladb/blob/master/docs/dev/cql3-type-mapping.md

**Comment by denesb** [comment]
@annastuchlik

**Comment by annastuchlik** [comment]
This issue has been resolved with https://github.com/scylladb/scylladb/pull/11224.
