### ISSUE TITLE
Alternator - DescribeTable calls should include ProvisionedThroughput

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#11222]
Scylla version (or git commit hash): `5.0.1-0.20220719.b177dacd3` with build-id `217f31634f8c8722cadcfe57ade8da58af05d415`

Scylla Alternator documentation properly states that [the BillingMode and ProvisionedThroughput options are ignored by Scylla](https://github.com/scylladb/scylladb/blob/master/docs/alternator/compatibility.md#provisioning). It is not clear - however - whether this data is simply never recorded, nor what are its defaults.

# Boring Story Part

Issue #5068 dives a little bit deeper on that aspect, and tries to bring a rationale on how to properly account and cap according to one's provisioned throughput.

This issue, however, aim to tackle another angle that seems to have never been thought of: The fact that implementations need rely on `ProvisionedThroughput` in order to properly know how frequently to dispatch requests against the database.

One real-life example is an investigation I have recently been through: It turns out that one of the most famous [DynamoDB connectors for Spark](https://github.com/audienceproject/spark-dynamodb) rely on the value of `ProvisionedThroughput` in order to determine the concurrency to send requests to.

The lack of `ProvisionedThroughput` within a `DescribeTable` response causes the above project to throw a fancy NPE:

```scala
scala> val scyllaDf = spark.read.dynamodb("mytable")
java.lang.NullPointerException
  at com.audienceproject.spark.dynamodb.connector.TableConnector.$anonfun$x$6$6(TableConnector.scala:72)
  at scala.collection.immutable.Map$Map1.getOrElse(Map.scala:119)
  at com.audienceproject.spark.dynamodb.connector.TableConnector.<init>(TableConnector.scala:74)
  at com.audienceproject.spark.dynamodb.datasource.DynamoTable.<init>(DynamoTable.scala:50)
  at com.audienceproject.spark.dynamodb.datasource.DefaultSource.inferSchema(DefaultSource.scala:40)
  at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:81)
  at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:274)
  at scala.Option.map(Option.scala:230)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:248)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
  at com.audienceproject.spark.dynamodb.implicits$DynamoDBDataFrameReader.dynamodb(implicits.scala:36)
  ... 51 elided
```

Which point us to the [following code excerpt](https://github.com/audienceproject/spark-dynamodb/blob/master/src/main/scala/com/audienceproject/spark/dynamodb/connector/TableConnector.scala#L71:L77), which makes it clear that a NPE is thrown due to a lack of `ProvisionedThroughput` within Alternator's response.

It is worth to mention that the aforementioned project in question is not an edge-case. In fact, our **Scylla Migrator** solution relies on this very specific project to properly connect and migrate to Alternator! What's worse, we have a nasty undocumented hack inside it to overcome that limitation under [here](https://github.com/scylladb/scylla-migrator/blob/master/src/main/scala/com/scylladb/migrator/readers/DynamoDB.scala#L21:L23)  :^)

The hack-ish workaround basically involves hardcoding the RCUs and WCUs to 25 for whatever reason. Which makes me raise a ton of other questions around why this specific number was chosen, but which aren't relevant to **THIS** specific issue.

# Actual Issue Discussion

When a table is created with `BillingMode: PAY_PER_REQUEST` in AWS, its relevant `ProvisionedThroughput` will return all values with a 0:
```json
     "ProvisionedThroughput":
     {
      "NumberOfDecreasesToday":0,
      "ReadCapacityUnits":0,
      "WriteCapacityUnits":0
     }
```

Whereas when a table is created with `BillingMode: PROVISIONED` in AWS, the response will **NOT** return a `BillingMode` and only its relevant `ProvisionedThroughput` along with the user specified values:
```json
    "ProvisionedThroughput":{
     "NumberOfDecreasesToday":0,
     "ReadCapacityUnits":5,
     "WriteCapacityUnits":5
    }
```

# Full Responses

### AWS DynamoDB Provisioned Throughput
```json
{ "Table":
  {
   "AttributeDefinitions": [
    {
      "AttributeName":"pk",
      "AttributeType":"S"
    },
    {
      "AttributeName":"sk",
      "AttributeType":"S"
    }
    ],
   "CreationDateTime":1.659558221466E9,
   "ItemCount":1,
   "KeySchema": [
    {
     "AttributeName":"pk",
     "KeyType":"HASH"
    },
    {
     "AttributeName":"sk",
     "KeyType":"RANGE"
    }
    ],
    "ProvisionedThroughput":{
     "NumberOfDecreasesToday":0,
     "ReadCapacityUnits":5,
     "WriteCapacityUnits":5
    },
    "TableArn":"arn:aws:dynamodb:us-east-1:XYZ:table/felipemendes_poc",
    "TableId":"f102548b-dc5d-45c7-9094-caf6e2f80559",
    "TableName":"felipemendes_poc",
    "TableSizeBytes":24,
    "TableStatus":"ACTIVE"
   }
}
```

### AWS DynamoDB - On Demand
```json
{ "Table":
  {
    "AttributeDefinitions":[
     {
      "AttributeName":"pk",
      "AttributeType":"S"
     },
     {
      "AttributeName":"sk",
      "AttributeType":"S"
     }
     ],
     "BillingModeSummary":{
     "BillingMode":"PAY_PER_REQUEST",
     "LastUpdateToPayPerRequestDateTime":1.659668747128E9
     },
     "CreationDateTime":1.659668747128E9,
     "ItemCount":0,
     "KeySchema":[
     {
      "AttributeName":"pk",
      "KeyType":"HASH"
     },
     {
      "AttributeName":"sk",
      "KeyType":"RANGE"
     }
     ],
     "ProvisionedThroughput":
     {
      "NumberOfDecreasesToday":0,
      "ReadCapacityUnits":0,
      "WriteCapacityUnits":0
     },
     "TableArn":"arn:aws:dynamodb:us-east-1:XYZ:table/felipemendes-ondemand",
     "TableClassSummary":{
      "TableClass":"STANDARD"
     },
     "TableId":"818812db-3f6f-41e9-b7e8-bd59f749f138",
     "TableName":"felipemendes-ondemand",
     "TableSizeBytes":0,
     "TableStatus":"ACTIVE",
     "TableThroughputModeSummary":{
      "LastUpdateToPayPerRequestDateTime":1.659668747128E9,
      "TableThroughputMode":"PAY_PER_REQUEST"
     }
  }
}
```

### ScyllaDB Alternator (doesn't matter which mode)
```json
{ "Table":
  {
    "TableName":"mytable",
    "CreationDateTime":1659667261,
    "TableStatus":"ACTIVE",
    "TableArn":"arn:scylla:alternator:alternator_mytable:scylla:table/mytable",
    "TableId":"8c181530-13aa-11ed-a330-70672e61da56",
    "BillingModeSummary":{
     "BillingMode":"PAY_PER_REQUEST",
     "LastUpdateToPayPerRequestDateTime":1659667261
    },
    "KeySchema":[
     {
      "AttributeName":"pk",
      "KeyType":"HASH"
     },
     {
      "AttributeName":"sk",
      "KeyType":"RANGE"
     }
    ],
    "AttributeDefinitions":[
     {
      "AttributeName":"sk",
      "AttributeType":"S"
     },
     {
      "AttributeName":"pk",
      "AttributeType":"S"
     }
   ]
  }
}
```

@nyh

**Comment by nyh** [comment]
We already have an xfailing test for this - `test_describe_table.py`::`test_describe_table_provisioned_throughput`.

I'll fix this. Should be easy enough.

**Comment by nyh** [comment]
@fee-mendes I understand that a library might fail if a value it expects to read is missing, but I'm curious if it actually cares about the numbers. What if we always return on-demand billing mode (and 0 provisioning) even if the user tried to set provisioned billing mode? Would that be fine, or do you think an application might insist that if it created a table with provisioned throughput and some throughput numbers - it must be abled to read the same thing via DescribeTable?

Finding where to store that silly billing and provisioning information that we don't use, if we have to do it, will be the (slightly) difficult part. Returning on-demand and all zeros unconditionally is easier ;-)

**Comment by fee-mendes** [comment]
@nyh it does care about the numbers in order to control parallelism. See [TableConnector.scala](https://github.com/audienceproject/spark-dynamodb/blob/master/src/main/scala/com/audienceproject/spark/dynamodb/connector/TableConnector.scala) for an understanding on what it does.

That said, I personally don't care if we return all 0s. In essence, when `ProvisionedThroughput = 0` the library will override it to a parallelism of 100. Of course if this is too much or too few, then it is up to the user to tune it according to his needs.

So I am ok with returning 0 for now and getting rid of the obscure NPE error :-)

**Comment by avikivity** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
I'll backport. This isn't a terrible bug but breaks specific applications that are surprised when this specific piece of DescribeTable is missing - and the fix is simple and (I think) risk-free.

**Comment by nyh** [comment]
Backported to next-5.1 (d3fd09042980142ef9005903315e46814bdf59ae), next-5.0 (50c2c1b1d44c6538b9e9d166287447a3ae362b47), next-4.6 (5ee69ff3a90f1c98d2285838fb81251a69b3bced)

**Comment by ojii** [comment]
Would it be possible for alternator to return the provisioned throughput requested in CreateTable/UpdateTable? I maintain a DynamoDB client library and recently ran our test suite against Alternator again and Alternator unexpectedly returning a throughput of 0 makes [our test fail](https://github.com/HENNGE/aiodynamo/blob/dcf67351c339d3689ae3570f0cad2678e486eabf/tests/integration/test_client.py#L286-L305).

**Comment by mykaul** [comment]
> Would it be possible for alternator to return the provisioned throughput requested in CreateTable/UpdateTable? I maintain a DynamoDB client library and recently ran our test suite against Alternator again and Alternator unexpectedly returning a throughput of 0 makes [our test fail](https://github.com/HENNGE/aiodynamo/blob/dcf67351c339d3689ae3570f0cad2678e486eabf/tests/integration/test_client.py#L286-L305).

@ojii - can you please open a separate new issue with the above request?
