### ISSUE TITLE
Error messages  !ERR | scylla[8138]:  [shard  0] raft_rpc - Failed to send vote request  could be reported as warning while node is decommissioning

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#11229]
## Installation details

Kernel Version: 5.15.0-1015-aws
Scylla version (or git commit hash): `5.1.0~dev-20220802.663f2e2a8f81` with build-id `d6f523279872624d89a9a451f02d8276f0073cb5`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-5f916b01-9 (13.48.45.112 | 10.0.0.124) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-8 (13.48.84.188 | 10.0.2.138) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-7 (16.16.68.255 | 10.0.2.41) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-6 (16.170.238.0 | 10.0.1.28) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-5 (13.51.13.70 | 10.0.0.49) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-4 (16.171.58.148 | 10.0.2.6) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-3 (13.53.182.134 | 10.0.0.250) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-2 (16.170.146.52 | 10.0.0.99) (shards: 14)
- longevity-100gb-4h-master-db-node-5f916b01-1 (16.171.54.121 | 10.0.0.152) (shards: 14)

OS / Image: `ami-0da67a130b28d1222` (aws: eu-north-1)

Test: `longevity-100gb-4h-with-raft-test`
Test id: `5f916b01-3570-4da2-a47b-2b2c53ab8eb8`
Test name: `scylla-master/SCT_Raft_Experimental/longevity-100gb-4h-with-raft-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5eb7e7241a351a35cd9c1756cd43cc329cb5a873/test-cases/longevity/longevity-100gb-4h.yaml)

## Issue description

During  nemesis, which terminates or decomissions nodes in logs there are many log error messages while node is decomissioning
```
2022-08-05T04:58:57+00:00 longevity-100gb-4h-master-db-node-5f916b01-6      !ERR | scylla[8138]:  [shard  0] raft_rpc - Failed to send vote request ab9ee2a3-157e-48ea-bbf9-562013cb2f1c: seastar::rpc::closed_error (connection is closed)
```

the errors are not affect on test job, but seems they could be reported as warning

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5f916b01-3570-4da2-a47b-2b2c53ab8eb8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5f916b01-3570-4da2-a47b-2b2c53ab8eb8)
- Show all stored logs command: `$ hydra investigate show-logs 5f916b01-3570-4da2-a47b-2b2c53ab8eb8`

## Logs:
- **db-cluster-5f916b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/db-cluster-5f916b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/db-cluster-5f916b01.tar.gz)
- **monitor-set-5f916b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/monitor-set-5f916b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/monitor-set-5f916b01.tar.gz)
- **loader-set-5f916b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/loader-set-5f916b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/loader-set-5f916b01.tar.gz)
- **sct-runner-5f916b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/sct-runner-5f916b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/sct-runner-5f916b01.tar.gz)
- **parallel-timelines-report-5f916b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/parallel-timelines-report-5f916b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5f916b01-3570-4da2-a47b-2b2c53ab8eb8/20220805_080919/parallel-timelines-report-5f916b01.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/SCT_Raft_Experimental/job/longevity-100gb-4h-with-raft-test/4/)

**Comment by kostja** [comment]
Closing, this is addressed in the current master.
