### ISSUE TITLE
The assertion about low_mark <= rp in database::truncate is wrong when truncate_at is in the past

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11231]
The assert in https://github.com/scylladb/scylladb/blob/master/replica/database.cc#L2385-L2391

 was tweaked several times:
- Introduced in 83323e155e2f26ead355b45b64531980e8ca66ff,
- then fixed in b2b1a1f7e1b75afb135b3bcacd4be33ce10d57c4 to account for no rp from discard_sstables,
- then in 9620755c7f2b18109dc4b2b64a0cd38ff0cbb2eb to account for cases we do not flush the table,
- then again in 71c5dc82df7eb7f63c1be4ef07d569bf0e97b5e5 to make that more accurate.

But, the assert wasn't correct in the first place
in the sense that we first get `low_mark` which
represents the highest replay_position at the time truncate
was called, but then we call discard_sstables with a time_point
of `truncated_at` that we get from the caller via the timestamp_func,
and that one could be in the past, before truncate was called -
hence discard_sstables with that timestamp may very well
return a replay_position from older sstables, prior to flush
that can be smaller than the low_mark.

The real fix to this issue is to have a truncate_tombstone
that will carry an authoritative api::timstamp (#11230)

**Comment by bhalevy** [comment]
For example, this assert was tripped in https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1690/artifact/logs-gating.release.2/1659695090812_snapshot_test.py%3A%3ATestSnapshot%3A%3Atest_basic_mulitple_tables_snapshot_using_column_family/node1.log
```
INFO  2022-08-05 10:24:48,878 [shard 0] database - Dropping ks.cf0 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Dropping ks.cf1 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Dropping ks.cf2 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Dropping ks.cf3 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Dropping ks.cf4 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Truncating ks.cf0 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Truncating ks.cf1 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Truncating ks.cf2 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Truncating ks.cf3 with auto-snapshot
INFO  2022-08-05 10:24:48,878 [shard 0] database - Truncating ks.cf4 with auto-snapshot
scylla: replica/database.cc:2450: future<> replica::database::truncate(replica::column_family &, db::replay_position, bool, db_clock::time_point): Assertion `!did_flush || low_mark <= rp || rp == db::replay_position()' failed.
Aborting on shard 0.
```

**Comment by avikivity** [comment]
@bhalevy should this be backported?

**Comment by bhalevy** [comment]
It's a real byg however extremely rare and IIRC we've stumbled upon it only in the said dtest, so I think it doesn't merit backport

**Comment by bhalevy** [comment]
Also, not a regression. It's been buggy forever

**Comment by avikivity** [comment]
Not backporting per above.
