### ISSUE TITLE
Issue in page The CDC Log Table

### ISSUE THREAD

**Issue by sasiikumaarr** [scylladb/scylladb#11236]
I would like to report an issue in page https://docs.scylladb.com/master/using-scylla/cdc/cdc-log-table

### Problem
I could not able to find a way to disable creating log table for a cdc enabled table.
log table is generated when i create a table with CDC enable= true but i do not want to create cdc log table.

###  Suggest a fix

**Comment by elcallio** [comment]
How would CDC enabled without log work? I think you are confusing CDC _possible_ (it always is) with _enabled_ (active).
