### ISSUE TITLE
Row cache will miss a row if upper bound of population range is evicted and has an adjacent dummy row

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#11239]
Scenario:

```
cache = [
    row(pos=2, continuous=false),
    row(pos=after(2), dummy=true)
]
```

Scanning read starts, starts populating [-inf, before(2)] from sstables.

row(pos=2) is evicted.

```
cache = [
    row(pos=after(2), dummy=true)
]
```

Scanning read finishes reading from sstables.

Refreshes cache cursor via `partition_snapshot_row_cursor::maybe_refresh()`, which calls `partition_snapshot_row_cursor::advance_to()` because iterators are invalidated. This advances the cursor to after(2). `no_clustering_row_between(2, after(2))` returns true, so advance_to() returns true, and maybe_refresh() returns true. This is interpreted by the cache reader as "the cursor has not moved forward", so it marks the range as complete, without emitting the row with pos=2. Also, it marks row(pos=after(2)) as continuous, so later reads will also miss the row.

The bug is in `advance_to()`, which is using `no_clustering_row_between(a, b)` to determine its result, which by definition excludes the starting key.

**Comment by tgrabiec** [comment]
Discovered by row_cache_test.cc::test_concurrent_reads_and_eviction with reduced key range in the `random_mutation_generator` (1024 -> 16).

**Comment by tgrabiec** [comment]
I'm backporting this to all branches.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
