### ISSUE TITLE
Dropping table should truncate all sstables

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11232]
Currently `drop_table_on_all_shards` receives a timestamp_func that is passed to the truncate path.
But the truncate timstamp this function returns needs to include all sstables in the table.

It's nonsensical to use a past truncate_at time_point when deleting the whole table.
That might leave sstables in it, preventing it's directory from being deleted (see https://github.com/scylladb/scylladb/issues/10896 and https://github.com/scylladb/scylladb/pull/11001#discussion_r917392167)

The timestamp_func practically serves another purpose which is to synchronize between the shards in database::truncate so callers use utils::joinpoint for that. See https://github.com/scylladb/scylladb/blob/7f80602b010a973dd24953cf39161699e7afcb42/db/schema_tables.cc#L1214-L1219
and https://github.com/scylladb/scylladb/blob/7f80602b010a973dd24953cf39161699e7afcb42/db/schema_tables.cc#L1331

So at this time, drop_table_on_all_shards just needs to create its own joinpoint, return db_clock::time_point::max() to make sure all sstables are discarded by https://github.com/scylladb/scylladb/blob/7f80602b010a973dd24953cf39161699e7afcb42/replica/database.cc#L2383

**Comment by avikivity** [comment]
I don't understand why. If you delete sstables that have data after the truncate timestamp, you lose that data.

**Comment by bhalevy** [comment]
> I don't understand why. If you delete sstables that have data after the truncate timestamp, you lose that data.

It's in the drop_table (a.k.a drop_column_family) case.
We expect no sstables to be created at or after the time truncate is called, since the table is already detached at this point, compaction is stopped, and the table is flushed before an auto-snapshot is taken (otherwise memtables are cleared).

**Comment by avikivity** [comment]
I confused "truncate sstables" with "truncate table". sstables aren't really truncated.

We can use a truncate timestamp of +inf perhaps.

**Comment by bhalevy** [comment]
> I confused "truncate sstables" with "truncate table". sstables aren't really truncated.
> 
> We can use a truncate timestamp of +inf perhaps.

Exactly.  The fix uses `db_clock::time_stamp::max()`

**Comment by avikivity** [comment]
@bhalevy should this be backported?

**Comment by bhalevy** [comment]
> @bhalevy should this be backported?

No, it is minor and not a regression.
