### ISSUE TITLE
multishard_mutation_query: shard reads don't enter the async gate

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11254]
The range scan code has to make sure the table object against which the query is executed stays alive on all shards while the query is ongoing, lest a table drop could yank it out from below the feet of shard readers. To this end it uses `table::read_in_progress()`. When stopped, the table advances this phaser and waits for all ongoing reads before proceeding:
https://github.com/scylladb/scylladb/blob/3ffc978166abd50e7de545a8441cac34c0ea1ff0/replica/table.cc#L818-L842
The problem is that after the `await_pending_ops()` line, nothing prevents from new reads proceeding and successfully obtaining a new phaser. To defend against this, reads should also take the `_async_gate`. Closing this gate is the first thing `stop()` does, so after that no new read can be started.
The solution is to make the range scan code also take the async gate.

**Comment by denesb** [comment]
After closer inspection and attempting to reproduce the race with a unit test, I realized that the race isn't there: when dropping a table, at this point the table is removed from the `database`, so looking up the table to obtain a read phaser will fail in the first place.
I'm not sure what the purpose of `_async_gate` is to be honest anymore.

**Comment by slivne** [comment]
@denesb who can help answer this ?

**Comment by slivne** [comment]
If this is not a bug please remove the label and close (and maybe remove the _async_gate if its not needed anymore)

**Comment by denesb** [comment]
> If this is not a bug please remove the label and close (and maybe remove the _async_gate if its not needed anymore)

I'm working exactly on that. I'll close this issue.

**Comment by denesb** [comment]
For posterity: the PR dropping the async gate: https://github.com/scylladb/scylladb/pull/11283
