### ISSUE TITLE
raft, read_barrier, and possibly other raft methods, should retry intermittent rpc failures

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#11262]
If the leader is unavailable during read_barrier, a closed_error occurs, which is not handled in any way and eventually reaches the client and causes it to drop connection.

This is the cause of many dtests failures with raft enabled.

**Comment by kbr-** [comment]
By the way, what is the cause of leader unavailability in those dtests?

**Comment by gusev-p** [comment]
> By the way, what is the cause of leader unavailability in those dtests?

The tests stops the nodes themselves and then modify the configuration with `CREATE/DROP`

**Comment by kbr-** [comment]
> modify the configuration with CREATE/DROP

You mean they modify the schema?

So the scenario is:
1. nodes {A,B}, A is the leader
2. test stops node A
3. test sends CREATE/DROP to node B
4. node B forwards to A (didn't notice yet that A lost leadership), closed_error happens

?

**Comment by gusev-p** [comment]
[yes](https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-dtest/job/PR-2810/lastBuild/testReport/concurrent_schema_changes_test/TestConcurrentSchemaChanges/test_changes_while_node_toggle_raft_/)
