### ISSUE TITLE
Docs: Troubleshooting, Reverse Queries fail when the partition is larger than the maximum safe size, is out of date

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11274]
I would like to report an issue in page https://docs.scylladb.com/master/troubleshooting/reverse-queries

### Problem

The problem described in this page is not valid in Scylla 5.0 and later

**Comment by tzach** [comment]
@tarzanek @denesb - please comment

**Comment by denesb** [comment]
This page is still valid for partition-range scans and any query having to read from a pre `mc` sstable. So in practice, most users will not hit it.

**Comment by denesb** [comment]
Also note that 5.0 doesn't have all the reverse query related changes. AFAIK the cache/memtable still didn't support reverse reads.

**Comment by annastuchlik** [comment]
See https://github.com/scylladb/scylladb/pull/11100.
I'll open a new PR with this fix.

**Comment by michoecho** [comment]
Bump.
Other relevant pages: 
https://docs.scylladb.com/stable/operating-scylla/procedures/tips/benchmark-tips.html#dont-use-reverse-queries
https://monitoring.docs.scylladb.com/stable/use-monitoring/cql_optimization.html#reversed-cql-reads
https://monitoring.docs.scylladb.com/stable/use-monitoring/advisor/cqlReverseOrder.html
