### ISSUE TITLE
Node decommissions successfully in a split-brain cluster, forever staying DL for its peers

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylladb#11302]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6.3, not tested against other versions
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): N/A

*Hardware details (for performance issues)* 
Platform (physical/VM/cloud instance type/docker): Kubernetes, only reproduced in [kind](https://kind.sigs.k8s.io/) so far

The issue originated from a functional test created by QA (@vponomaryov): https://github.com/scylladb/scylla-cluster-tests/blob/4af808c848863d1b3e96c3581bb51fe13a9f986f/functional_tests/scylla_operator/test_functional.py#L174. See https://github.com/scylladb/scylla-operator/issues/982 for the original issue.

Below a very brief description of the issue, for more context please see [my comment under the original issue](https://github.com/scylladb/scylla-operator/issues/982#issuecomment-1205214536) and the discussion that follows it.

The minimal scenario to reproduce this issue would be as follows:
```
1. Set up a 3 node Scylla Cluster
2. Stop the last Scylla node
3. Start the last Scylla node again
4. Immediately decommission the last Scylla node
```

When you run the above scenario in [kind](https://kind.sigs.k8s.io/), you hit the very specific conditions that are required to reproduce the bug:
1. **There is no gossip traffic going from nodes 1 and 2 to node 3.** 
2. All the other rpc traffic flows normally, including gossip traffic from node 3 to nodes 1 and 2 and **responses to node_ops commands from nodes 1 and 2 to node 3.**

What happens then is that, due to the lack of gossip exchange, the cluster goes split-brain. Nodes 1 and 2 see each other as UN and both see node 3 as DN. Node 3 sees itself as UN and all the other nodes as DN.
Since node_ops commands are exchanged without any issues, the decommissioning of node 3 succeeds, despite it seeing other nodes as DN.

This, in turn, causes node 3 to stay in nodes 1 and 2's peers tables as DL forever. 

To sum up, what causes this issue is the unfortunate timing of the decommissioning happening before there's successful gossip exchange. You won't observe it if you wait for all the nodes to see each other as UN.

I believe that the expected behavior should be for the decommissioning to fail in that scenario.

Again, to see the details, including logs and tcpdumps, see [the discussion in the original issue](https://github.com/scylladb/scylla-operator/issues/982).

Although I was only able to reproduce it in [kind](https://kind.sigs.k8s.io/), I think there are enough reasons to think that's a Scylla bug. Dropping the gossip packets going from nodes 1 and 2 to node 3 should be enough to reproduce it.

@fruch also claims he has a viable reproducer: https://github.com/scylladb/scylla-operator/issues/982#issuecomment-1207434655

fyi @slivne

**Comment by fee-mendes** [comment]
I think this is a (much worse) variation of https://github.com/scylladb/scylladb/issues/11011#issuecomment-1182734632 ?

In particular, in that scenario the operation would fail as one node couldn't reach the decommissioned node, but decommission would proceed and succeed anyway. However, for larger tables it would always fail and avoid the race. 

@asias mentioned in the aforementioned issue that there are some patches to improve that situation. Would the one here be also covered?

**Comment by fruch** [comment]
@asias can you take a look into this one ?

**Comment by asias** [comment]
> Again, to see the details, including logs and tcpdumps, see [the discussion in the original issue](https://github.com/scylladb/scylla-operator/issues/982).

Hello, could you attach the scylla node logs here. 

I looked at the logs mentioned here: https://github.com/scylladb/scylla-operator/issues/982#issue-1241564734

Logs
[kubernetes-ec2f57f5.tar.gz](https://github.com/scylladb/scylla-operator/files/8728116/kubernetes-ec2f57f5.tar.gz)

But I couldn't find scylla node logs.

**Comment by asias** [comment]
```
    There is no gossip traffic going from nodes 1 and 2 to node 3.
    All the other rpc traffic flows normally, including gossip traffic from node 3 to nodes 1 and 2 and responses to node_ops commands from nodes 1 and 2 to node 3.
```
This is a very weird situation. How did we end up with the network situation above?

I know why the node stays DL forever. The problem is that with node_ops_cmd based node operation, we still rely on the gossip status of STATUS_LEFT from the node being decommissioned to notify other nodes this node has finished decommission and can be moved from STATUS_LEAVING to STATUS_LEFT.

I think we can verify in the beginning of the decommission to check if node3 sees node2 and node1 as UP, otherwise reject the decommission.

Could you find a way to reproduce this reliably so you can test my fix?

**Comment by fruch** [comment]
> ```
>     There is no gossip traffic going from nodes 1 and 2 to node 3.
>     All the other rpc traffic flows normally, including gossip traffic from node 3 to nodes 1 and 2 and responses to node_ops commands from nodes 1 and 2 to node 3.
> ```
> 
> This is a very weird situation. How did we end up with the network situation above?
> 
> I know why the node stays DL forever. The problem is that with node_ops_cmd based node operation, we still rely on the gossip status of STATUS_LEFT from the node being decommissioned to notify other nodes this node has finished decommission and can be moved from STATUS_LEAVING to STATUS_LEFT.
> 
> I think we can verify in the beginning of the decommission to check if node3 sees node2 and node1 as UP, otherwise reject the decommission.
> 
> Could you find a way to reproduce this reliably so you can test my fix?

yes, we have dtest based reproducer here:
https://gist.github.com/fruch/7487febf59afd60a7972a08e4ef44daf

**Comment by asias** [comment]
> > This is a very weird situation. How did we end up with the network situation above?
> > I know why the node stays DL forever. The problem is that with node_ops_cmd based node operation, we still rely on the gossip status of STATUS_LEFT from the node being decommissioned to notify other nodes this node has finished decommission and can be moved from STATUS_LEAVING to STATUS_LEFT.
> > I think we can verify in the beginning of the decommission to check if node3 sees node2 and node1 as UP, otherwise reject the decommission.
> > Could you find a way to reproduce this reliably so you can test my fix?
> 
> yes, we have dtest based reproducer here: https://gist.github.com/fruch/7487febf59afd60a7972a08e4ef44daf

I saw:

```
10:14:34,045 test_reproducer_iptables INFO  test_reproducer_iptables.py:61   | 
10:14:42,689 iptables        DEBUG iptables.py    :9    | Executing following command: sudo iptables --flush test_reproducer_iptables
10:14:42,704 iptables        DEBUG iptables.py    :14   | 
10:14:42,704 iptables        DEBUG iptables.py    :9    | Executing following command: sudo iptables --delete INPUT --proto all --jump test_reproducer_iptables
- stats posted to elasticsearch [https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243]: {'error': 0, 'passed': 0, 'failure': 1, 'skipped': 0, 'xfailed': 0, 'xpass': 0, 'passed & error': 0, 'failure & error': 0, 'skipped & error': 0, 'error & error': 0} -
======================================================================================================= short test summary info =======================================================================================================
FAILED test_reproducer_iptables.py::TestBootstrap::test_reproducer_for_982 - AssertionError: b'iptables: No chain/target/match by that name.\n'
```

I have:

```
$ sudo iptables -nL|grep test_reproducer_iptables
Chain test_reproducer_iptables (0 references)
```

Btw:

```
iptables_obj.create_new_chain()
```

will fail if the chain exists so the test will fail.

I tried:

```
        iptables_obj = IPTable(chain_name=__name__)
        try:
            iptables_obj.create_new_chain()
        except:
            pass
```

to workaround.

**Comment by fruch** [comment]
> > > This is a very weird situation. How did we end up with the network situation above?
> > > I know why the node stays DL forever. The problem is that with node_ops_cmd based node operation, we still rely on the gossip status of STATUS_LEFT from the node being decommissioned to notify other nodes this node has finished decommission and can be moved from STATUS_LEAVING to STATUS_LEFT.
> > > I think we can verify in the beginning of the decommission to check if node3 sees node2 and node1 as UP, otherwise reject the decommission.
> > > Could you find a way to reproduce this reliably so you can test my fix?
> > 
> > 
> > yes, we have dtest based reproducer here: https://gist.github.com/fruch/7487febf59afd60a7972a08e4ef44daf
> 
> I saw:
> 
> ```
> 10:14:34,045 test_reproducer_iptables INFO  test_reproducer_iptables.py:61   | 
> 10:14:42,689 iptables        DEBUG iptables.py    :9    | Executing following command: sudo iptables --flush test_reproducer_iptables
> 10:14:42,704 iptables        DEBUG iptables.py    :14   | 
> 10:14:42,704 iptables        DEBUG iptables.py    :9    | Executing following command: sudo iptables --delete INPUT --proto all --jump test_reproducer_iptables
> - stats posted to elasticsearch [https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243]: {'error': 0, 'passed': 0, 'failure': 1, 'skipped': 0, 'xfailed': 0, 'xpass': 0, 'passed & error': 0, 'failure & error': 0, 'skipped & error': 0, 'error & error': 0} -
> ======================================================================================================= short test summary info =======================================================================================================
> FAILED test_reproducer_iptables.py::TestBootstrap::test_reproducer_for_982 - AssertionError: b'iptables: No chain/target/match by that name.\n'
> ```
> 
> I have:
> 
> ```
> $ sudo iptables -nL|grep test_reproducer_iptables
> Chain test_reproducer_iptables (0 references)
> ```
> 
> Btw:
> 
> ```
> iptables_obj.create_new_chain()
> ```
> 
> will fail if the chain exists so the test will fail.
> 
> I tried:
> 
> ```
>         iptables_obj = IPTable(chain_name=__name__)
>         try:
>             iptables_obj.create_new_chain()
>         except:
>             pass
> ```
> 
> to workaround.

What you see is the cleanup code of the test failing, let's take it into a dtest issue, how to make it a bit smarter. it's failing since the chain is removed during the test, while we still have add a finalizer function to remove on case of failure in the test, yes we need better cleanup for it

**Comment by rzetelskik** [comment]
> This is a very weird situation. How did we end up with the network situation above?

It's caused by stale entires in conntrack (https://github.com/scylladb/scylla-operator/issues/982#issuecomment-1218106849). Because Pods are ephemeral, there's a service (load balancer) with static IP used for each node's identity. QA uses kube-proxy in iptables mode, which means there's a FORWARD rule for each endpoint behind the load balancer. After node 3 is restarted, the IP behind the load balancer changes and the FORWARD rule in iptables is updated. Yet the stale conntrack entires are only updated after ~2 minutes, hence the weird network situation.

**Comment by avikivity** [comment]
@asias should we backport this? risk vs benefit
