### ISSUE TITLE
UDAs do not survive restart

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#11309]
After creating a user aggregate using `CREATE AGGREGATE ks.a (int) SFUNC rowf STYPE int FINALFUNC finf INITCOND 0;`  and restarting Scylla using 
```./build/release/scylla --developer-mode=true --workdir=/xfs/tmp --experimental-features=udf --enable-user-defined-functions=true --skip-wait-for-gossip-to-settle=0```
 to start and Ctrl+C to stop, the user aggregate `ks.a` no longer works. 

When trying to use it in a `SELECT` statement, I'm getting an error 
`InvalidRequest: Error from server: code=2200 [Invalid query] message="Unknown function 'ks.a'"`
 with no new logs (using default log levels). 

Additionally,  after running the `CREATE AGGREGATE` query again after restarting, no error message is returned and  `schema_tables - Schema version changed ...` appears in Scylla logs, but further `SELECT` queries using the aggregate still display the same error. The `CREATE AGGREGATE` query can also be run again without logging an `InvalidRequest: Error from server: code=2200 [Invalid query] message="The function 'ks.a : (int) -> int' already exists"` message, which we would expect in this case.

**Comment by avikivity** [comment]
Backported to 5.1 only, since it's experimental. Already in 5.2.
