### ISSUE TITLE
New io_uring integration?

### ISSUE THREAD

**Issue by Cybergenik** [scylladb/scylladb#11301]
Not an issue, just thought I'd ask.

Has the ScyllaDB core team looked into the new [io_uring](https://kernel.dk/io_uring.pdf) kernel updates.

Userspace [lib](https://github.com/axboe/liburing)

Considering contributing if this is something that the team would be open to?

**Comment by avikivity** [comment]
It's already integrated since 8f690fdd47ba840360ca38620359be9a3ae09c58
