### ISSUE TITLE
Alternator - Scan operation returns a different hashing order than DynamoDB

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#11315]
*Installation details*
HEAD https://github.com/scylladb/scylladb/commit/055340ae39ba7701e798ca370d01d343c28ac231

**Description**

I decided to raise this "issue" (which may not be really a bug per se, but rather a missing documentation aspect) while going through [DynamoDB Streams Kinesis](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.KCLAdapter.Walkthrough.CompleteProgram.html) **StreamsAdapterDemo.java** example. In particular, the following code excerpt caught my attention:

```java
        if (StreamsAdapterDemoHelper.scanTable(dynamoDBClient, srcTable).getItems()
                                    .equals(StreamsAdapterDemoHelper.scanTable(dynamoDBClient, destTable).getItems())) {
            System.out.println("Scan result is equal.");
        }
        else {
            System.out.println("Tables are different!");
        }
```

Which in summary means that - for two tables in perfect sync - without any writes going in between - a Scan operation should return the result set in the same order so it can be considered "equal". As with any full-table scan in a distributed hashing table, there must be a logic on which the partition/hash key elements are read. 

AWS doesn't mention about the fact that - while a regular user should typically never care about the hash key ordering - the resulting response from a `Scan` operation should always return the data in the same order, even though the above example states that it **IS** the case. In fact, the [Scan](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html) API page takes good care to avoid to mention anything explicit about the ResultSet ordering.

Moreover, both the [KeySchemaElement](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_KeySchemaElement.html) and the [Core components of DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey) pages also take proper care on stating that `DynamoDB uses the partition key's value as input to an internal hash function` or alike, which makes it clear that the hashing function for DynamoDB is somewhat a state secret.

ScyllaDB - and Alternator for that matter - uses a different (and well-known!) hashing algorithm: Cassandra's implementation of Murmur3, so obviously `Scan` operations & comparisons between DynamoDB and Alternator will fail, and the above sample program will erroneously report a message claiming that the "`Tables are different!`".

I decided to try this myself. Also, to prove the fact that a Scan operation should always return the ResultSet in the same order always, each table was scanned 10 times serially. I created 2 tables in AWS and 1 table in Alternator, their md5 responses are noticeably equal across AWS, but different for Alternator:

```shell
$ md5sum aws_dynamo_order_* aws_dynamo_table2_order_* scylla_alternator_order_*
17ed5f072739a197b78dacd418faa35f  aws_dynamo_order
17ed5f072739a197b78dacd418faa35f  aws_dynamo_table2_order
1fb7060653dfaf79f762ae6455801038  scylla_alternator_order
```

This makes it clear that users shouldn't erroneously assume that Alternator and DynamoDB hashing algorithms are the same and any application that naively tries to do a comparison between `Scan` results across both systems will - of course - not work.

This clearly needs to be documented, however, should we try to implement AWS hashing function is an entirely different story . :-)

**Comment by tzach** [comment]
Agree this is a doc, not implementation issue.
@fee-mendes can you send a quick PR for this?

**Comment by fee-mendes** [comment]
PR submitted.

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
