### ISSUE TITLE
container image needs extra help to expose the REST API

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#11319]
`podman run -it --rm -p 10000:10000 docker.io/scylladb/scylla:5.0.1 --smp 1`

Does not really expose the REST API because the default listener is on localhost:10000, and podman/docker redirect to some other IP address.

`podman run -it --rm -p 10000:10000 docker.io/scylladb/scylla:5.0.1 --api-address 0.0.0.0 --smp 1`

works.

**Comment by fee-mendes** [comment]
I think that until we add some sort of authentication to the REST API it should default to localhost as direct access to it can introduce security concerns.

In particular, today, the correct (read: secure) way of sending commands to the RestAPI from an external system would be via the `scylla-manager-agent`. As in:

```shell
$ curl -X GET -k -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" https://localhost:10001/compaction_manager/compaction_history
```

Where `${TOKEN}` is the agents defined `auth_token`

**Comment by avikivity** [comment]
The container manager takes responsibility for security. For example, if you omit -p 10000:10000, you don't have access to the REST API. If you write -p 127.0.0.1:10000:10000, the REST API will only be available on the host's localhost.

**Comment by fee-mendes** [comment]
> For example, if you omit -p 10000:10000, you don't have access to the REST API.

That's an incorrect statement. If you omit the `-p 10000:10000` you can still reach the container RestAPI via the container IP as soon as you decide to bind the API address to `0.0.0.0`. Try it yourself:

```shell
$ docker run -dit --name scylla scylladb/scylla:5.0.1 --api-address 0.0.0.0 --smp 1 --skip-wait-for-gossip-to-settle 0 
$ sleep 5; curl $(docker inspect scylla -f '{{.NetworkSettings.IPAddress }}'):10000/storage_service/scylla_release_version; echo
"5.0.1-0.20220719.b177dacd3"
```

Therefore, the RestAPI shouldn't be automatically bound to anything other than 127.0.0.1 by default. And if one wants it, only then the _container manager_ will take responsbility for security, as he must explicitly request so. ;-)

For the sake of docker & non-docker consistency, let's stay with the default as it is today.

**Comment by avikivity** [comment]
You're right, I'm very surprised. So you can't run two containers that listen on the same port without -p?

**Comment by fee-mendes** [comment]
You can. But you can't - of course - bind both ports to the same local port. The `-p 10000` (which only exposes it outside the container to be reached externally, but doesn't necessarily bind it to a host port) is already in place when you spin up a container. That allows you to reach the RestAPI port if (**and only if**) you decided to configure the `--api-address` to listen on `0.0.0.0`.

For a list of pre-defined, already exposed ports see `docker inspect <container_name> -f '{{ .NetworkSettings.Ports }}'`.

**Comment by avikivity** [comment]
Ah, I now remember that monitoring will bind to random ports if another instance is up.

Thanks for the explanations.

So I now think it's best not to change anything for now. But when we disaggregate the image as @tnozicka wants we'll have to change it.
