### ISSUE TITLE
Can't drop a keyspace if there are UDAs in it

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#11327]
While working on #11310, I found that if we attempt to drop a keyspace that contains a UDA, the keyspace becomes problematic: if we try to create another keyspace with the same name, we receive an error `AlreadyExists: Keyspace 'ks' already exists`, if we try to `DESCRIBE` it, we get `Keyspace 'ks' not found.`, and if we try to `DROP` it again, we receive no error, while we should get `ConfigurationException: Cannot drop non existing keyspace 'ks'.` (but on the first `DROP KEYSPACE` query, we got a `NoHostAvailable:` error)

The only logs from Scylla we get are 
```
INFO  2022-08-18 18:02:55,301 [shard  0] migration_manager - Drop Keyspace 'ks'
INFO  2022-08-18 18:02:55,309 [shard  0] schema_tables - Dropping keyspace ks
```
when we first drop the keyspace, and
```
INFO  2022-08-18 18:02:58,946 [shard  0] migration_manager - Drop Keyspace 'ks'
INFO  2022-08-18 18:02:59,006 [shard  0] schema_tables - Schema version changed to ad1eaeb4-9044-369b-bb78-876e710c18d7
```
on following `DROP` attempts.

What's worth noting, there are no issues if we `DROP` the aggregate before dropping the keyspace.

**Comment by nyh** [comment]
Odd. Sounds like we can easily write a cql-pytest (or cql or C++ or whatever) test for this. Please check if this problem is specific to UDAs, or do other things such as UDFs, UDTs, or (anything else I can't think of right now) can also cause similar problems.

**Comment by wmitros** [comment]
The reproducer is in fact very simple: 
```
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE FUNCTION ks.f1(acc int, val int)
    RETURNS NULL ON NULL INPUT
    RETURNS int
    LANGUAGE lua
    AS $$ return acc $$;

CREATE FUNCTION ks.f2(acc int)
    RETURNS NULL ON NULL INPUT
    RETURNS int
    LANGUAGE lua
    AS $$ return acc $$;

CREATE AGGREGATE ks.agg(int)
    SFUNC f1
    STYPE int
    FINALFUNC f2
    INITCOND 0;

DROP KEYSPACE ks;
```
I tested if there's a problem with UDFs, UDTs and there are no issues (unsurprisingly, tables and indexes work as well)

**Comment by avikivity** [comment]
Not a regression, and UDAs are still experimental, so not backporting this relatively serious bug.
