### ISSUE TITLE
scylla-server.service:26: Standard output type syslog is obsolete

### ISSUE THREAD

**Issue by horschi** [scylladb/scylladb#11322]
*Installation details*
Scylla version (or git commit hash): 5.0.1
Cluster size: 9+1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 22.04

I have seen a systemd warning, complaining about a invalid setting in the scylla-server service file:

Aug 12 08:54:06 p-L10-3 systemd[1]: /lib/systemd/system/scylla-server.service:26: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.

It seems the file contains obsolete configurations.

**Comment by avikivity** [comment]
Minor, not backporting.
