### ISSUE TITLE
Malformed sstables get evicted on compaction

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11344]
*Installation details*
Kernel version: `5.13.0-1031-aws`
Scylla version (or git commit hash): `5.0.0-0.20220628.c9e79cb4a with build-id daef393310f38c086a6e5070c8f2013684973a48`
Cluster size: 4 nodes (i3.large)
Scylla running with shards number (live nodes):
   longevity-mini-test-upload-s-db-node-c1adb7dd-1 (54.154.136.243 | 10.4.3.232): 2 shards
   longevity-mini-test-upload-s-db-node-c1adb7dd-2 (54.194.16.253 | 10.4.0.209): 2 shards
   longevity-mini-test-upload-s-db-node-c1adb7dd-4 (34.245.4.216 | 10.4.1.200): 2 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-050b81d683f061fbd` (aws: eu-west-1)

Test: `mini-longevity`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-mini-test-1h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/c848b7c8051178ddb0d2c9e35cc762defd5c386f/test-cases/longevity/longevity-mini-test-1h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/c848b7c8051178ddb0d2c9e35cc762defd5c386f/test-cases/longevity/longevity-mini-test-1h.yaml&source=gmail-html&ust=1661249686401000&usg=AOvVaw2ZErNl61vRayKCsRsIVF6A))

**Issue description**

When working on corrupted sstables collection feature for SCT, I noticed that sometimes corrupted sstables are getting evicted and cannot be collected anymore for further analysis (see db logs for `longevity-mini-test-upload-s-db-node-c1adb7dd-2` sstable: `md-29-`, `invalid_mutation_fragment_stream` error). For test purposes I was modifying randomly sstables with vi (some deletions/additions). Possibly easy way to reproduce would be `echo corrupt | tee md-*-Data.db` and see compaction evicts some of them.

Restore Monitor Stack command: `$ hydra investigate show-monitor c1adb7dd-661d-4fc2-ac1a-1d858cc56e46`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=upload-sstables-on-data-corruption&test_id=c1adb7dd-661d-4fc2-ac1a-1d858cc56e46](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dupload-sstables-on-data-corruption%26test_id%3Dc1adb7dd-661d-4fc2-ac1a-1d858cc56e46&source=gmail-html&ust=1661249686401000&usg=AOvVaw2geYXeH9LcVBYqAmtDVOb5))
Show all stored logs command: `$ hydra investigate show-logs c1adb7dd-661d-4fc2-ac1a-1d858cc56e46`

Test id: `c1adb7dd-661d-4fc2-ac1a-1d858cc56e46`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-mini-longevity-scylla-per-server-metrics-nemesis-20220820_170117-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-mini-longevity-scylla-per-server-metrics-nemesis-20220820_170117-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-mini-longevity-scylla-per-server-metrics-nemesis-20220820_170117-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-mini-longevity-scylla-per-server-metrics-nemesis-20220820_170117-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png)&source=gmail-html&ust=1661249686401000&usg=AOvVaw34VIgUYGC5e9IyqRKudOPO)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-overview-20220820_170007-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-overview-20220820_170007-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-overview-20220820_170007-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170007/grafana-screenshot-overview-20220820_170007-longevity-mini-test-upload-s-monitor-node-c1adb7dd-1.png)&source=gmail-html&ust=1661249686401000&usg=AOvVaw2E7L3w7fN90u8aYGA1KURq)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/db-cluster-c1adb7dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/db-cluster-c1adb7dd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/db-cluster-c1adb7dd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/db-cluster-c1adb7dd.tar.gz)&source=gmail-html&ust=1661249686401000&usg=AOvVaw2IMEti9rDJgK88Er-dO9-W)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/loader-set-c1adb7dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/loader-set-c1adb7dd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/loader-set-c1adb7dd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/loader-set-c1adb7dd.tar.gz)&source=gmail-html&ust=1661249686401000&usg=AOvVaw3PxmNDOBlhyg7c9nzBIMZ9)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/monitor-set-c1adb7dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/monitor-set-c1adb7dd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/monitor-set-c1adb7dd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/monitor-set-c1adb7dd.tar.gz)&source=gmail-html&ust=1661249686401000&usg=AOvVaw1Ty1fmTmqjY8UPlNfQohkQ)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/sct-runner-c1adb7dd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/sct-runner-c1adb7dd.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/sct-runner-c1adb7dd.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/c1adb7dd-661d-4fc2-ac1a-1d858cc56e46/20220820_170857/sct-runner-c1adb7dd.tar.gz)&source=gmail-html&ust=1661249686401000&usg=AOvVaw1FPPcoph7mTyZykkHej0XK)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/mini-longevity/32/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/mini-longevity/32/&source=gmail-html&ust=1661249686402000&usg=AOvVaw0cPI23BHKf8yWyw71uIrpK))

**Comment by bhalevy** [comment]
@raphaelsc please look into this

**Comment by bhalevy** [comment]
@raphaelsc I don't see why compaction would delete sstables that it couldn't read.
I think the best we can do is to move them to the quarantine subdirectory so they won't be subject to further compaction until they're examined.

**Comment by raphaelsc** [comment]
I think this is a misunderstanding

In the log message:
`"compaction failed: invalid_mutation_fragment_stream ([validator 0x6010067fe900 for sstable writer /var/lib/scylla/data/keyspace1/standard1-0873cc2020a611eda09f4bdc5b8a795e/md-29-big-Data.db (keyspace1.standard1 0873cc20-20a6-11ed-a09f-4bdc5b8a795e)]"`

md-29-big-Data.db refers to the output sstable being created, not the input data which is the source of corruption

See:         `, _validator(format("sstable writer {}", _sst.get_filename()), _schema, _cfg.validation_level)`

You need to look at the corresponding compaction job which failed and look at the input files. For that failure above, the corresponding compaction is:
`2022-08-20T16:41:05+00:00 longevity-mini-test-upload-s-db-node-c1adb7dd-2     !INFO | scylla[8784]:  [shard 0] compaction - [Compact keyspace1.standard1 e27b1310-20a6-11ed-a211-d5f355615b79] Compacting [/var/lib/scylla/data/keyspace1/standard1-0873cc2020a611eda09f4bdc5b8a795e/md-14-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-0873cc2020a611eda09f4bdc5b8a795e/md-28-big-Data.db:level=0:origin=compaction]`

so you should look at either file md-14-big-Data.db or md-28-big-Data.db for the corruption. Input files will be left behind even on compaction failure, whereas output file is automatically deleted on purpose.

I assume that compaction failure should dump the compaction id to make it easier to match the corresponding log which prints the input files.

**Comment by soyacz** [comment]
Thanks @raphaelsc for clarification. I'm closing the issue.
