### ISSUE TITLE
Distributed loader prioritized keyspaces has been removed. Breaks enterprise

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylladb#11349]
In 7396de72b17ab15154f5b994e5fc3851a033d6be (and refactorings before it) the set of prioritized keyspaces (and processing thereof) was removed, due to apparent non-usage (which is true for open-source version). 

This functionality is however required for certain features of the enterprise version (ear). As such is needs to be restored and reenabled.

**Comment by avikivity** [comment]
@elcallio do we need to backport it to any branch?

**Comment by elcallio** [comment]
If possible, it should be backported to 2021.x, where the feature was both introduced and apparently (accidentality) removed. Not sure if the code is compatible though. Or we can consider replicated key provider an outlier and not backport for things like that...?

**Comment by avikivity** [comment]
Not affecting any release, not backporting.
