### ISSUE TITLE
Scylla documentation: some default values are incorrect in "Scylla Auditing Guide"

### ISSUE THREAD

**Issue by rayakurl** [scylladb/scylladb#11341]
https://docs.scylladb.com/stable/operating-scylla/security/auditing

"audit" default parameter value is 'table' by default (not 'none')

"audit_categories" default value is 'DCL,DDL,AUTH,ADMIN'  (not an empty string)

**Comment by annastuchlik** [comment]
This issue has been resolved with https://github.com/scylladb/scylladb/pull/11347.
