### ISSUE TITLE
Issue in page Scylla SSTable - 3.x - recent default sstable format 

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11346]
I would like to report an issue in page https://docs.scylladb.com/master/architecture/sstable/sstable3/index

### Problem
`In Scylla 3.1 and above, mc format is enabled by default.` - This is no longer true I believe, as currently `md` format is default one (although I don't know which version it started to be).
###  Suggest a fix

**Comment by tzach** [comment]
@soyacz please point to the relevant commit with this change, so we can document when md become the default.
Also, you can now edit each doc page directly. Look for Edit this page" on the right side of the page

**Comment by annastuchlik** [comment]
Support for the `md` format was added in version 4.3: https://github.com/scylladb/scylladb/issues/4442.
And it became the default: https://www.scylladb.com/product/release-notes/scylla-open-source-4-3/

**Comment by soyacz** [comment]
Thanks @annastuchlik , I've forgotten about this issue.

**Comment by annastuchlik** [comment]
This issue has been fixed with https://github.com/scylladb/scylladb/pull/11431.
