### ISSUE TITLE
Docs: add new options to scylla-sstable page

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11363]
I would like to report an issue in page https://docs.scylladb.com/master/operating-scylla/admin-tools/scylla-sstable

### Problem
https://github.com/scylladb/scylladb/commit/975b0c0b03ca25a2caa3c7b1f14e911098ac479d adds two new commands:

* validate-checksums - helps identifying whether an sstable is intact or
  not, but checking the digest and the per-chunk checksums against the
  data on disk.
* decompress - helps when one wants to manually examine the content of a
  compressed sstable.

###  Suggest a fix

Add the commands to the doc

**Comment by tzach** [comment]
Another commit with tool update 
https://github.com/scylladb/scylladb/commit/0d5fd526a523e8352708e545af0c6470ed0c97e1

**Comment by denesb** [comment]
The two new commands you mention are already present on that doc page. But I do see we don't really talk about the schema at all (let alone the new way to get it), so I will send a PR to fix it.

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
