### ISSUE TITLE
Most Alternator TTL regression tests are skipped by default and should not be

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#11374]
Most of the single-node functional tests for the Alternator TTL features, in test/alternator/test_ttl.py, are marked "veryslow" and thus are skipped by default when running regression tests (one needs to pass `--runveryslow` to pytest to get them to run). This is undesirable because regressions will not be caught.

The reason why these tests were marked "veryslow" is because they need to wait until items get expired - which can be up to 24 hours (or realistically, 10 minutes) on DynamoDB. However, in Scylla, test/alternator/run already configures `--alternator-ttl-period-in-seconds` to one second, so most of these tests shouldn't take more than one or few seconds to run, which is slow, but not "very" slow, and arguably can be run by default.

I propose to:
1. Have the tests find the current value of "--alternator-ttl-period-in-seconds" and only skip the test if it's higher than 1 second (or when testing against DynamoDB) - avoiding the skip if "--veryslow" is set.
2. We could allow sub-second "--alternator-ttl-period-in-seconds" setting. We can set it to 0.5 seconds with (hopefully) negligible impact of the performance on non-TTL tests, but reduce the time of TTL tests even more.

**Comment by psarna** [comment]
We could also make more specialized decorators and distinguish between pytest.mark.veryslow and pytest.mark.veryslow_on_aws, and only skip the former in our tests. I agree about (2.), the faster, the better.

**Comment by avikivity** [comment]
@nyh please evaluate for backport. Will likely expose other fixes that want backporting.

**Comment by nyh** [comment]
Since Alternator TTL is officially experimental in 5.1 and earlier, I don't think backporting the tests or fixes is critical - but on the other hand you're probably right and it's worth the slight effort to backport it to 5.1 (and probably not to anything earlier).

If I apply this patch, I also need to apply a few followup patches for increasing timeouts:
3a30fbd56cd259eedf6a168f4c5267a5c526759e
6bc3075bbd20e9c4d75f62e6f837ca40cd4b3cab

**Comment by nyh** [comment]
Backported to 5.1 in https://github.com/scylladb/scylladb/pull/12200

**Comment by avikivity** [comment]
Already backported, not backporting further. @nyh please remember to remove the label after backporting.
