### ISSUE TITLE
Docs: User-defined functions (UDF/UDA)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11378]
Document CQL UDF sysntax, including Lua and WASM implementation.
See similar doc in compatible Apache Cassandra docs
https://cassandra.apache.org/doc/latest/cassandra/cql/functions.html#user-defined-scalar-functions
https://cassandra.apache.org/doc/latest/cassandra/cql/functions.html#user-defined-aggregates-functions

**Comment by psarna** [comment]
I posted a pull request with documentation. It's currently based on Lua for two reasons:
1. Lua is human-readable, while WebAssembly is not, at least not directly
2. Our WebAssembly UDF ABI is subject to lots of changes (with some ongoing right now), so it makes little sense to document it right now. Once @wmitros publishes a stable helper library for writing UDFs in Rust, we'll be able to produce a very thorough doc on how to use Wasm-powered UDFs in Scylla.

**Comment by avikivity** [comment]
In 5.1, not backporting further as it's documentation only.
