### ISSUE TITLE
Docs: scylla tools are now hosted in the scylla executable

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11393]
Meaning, they don't have their own executables anymore, i.e.:
`scylla-types` is now `scylla types` and `scylla-sstable` is now `scylla sstable`. Note that we are invoking the `scylla` executable for both tool, just with a different first command-line argument, designating the actual tool to invoke (in the absence of which `scylla` itself is started).

Since: 5.0 (5eccb4284)

**Comment by denesb** [comment]
@tzach can I just update the current docs and the old ones will keep referencing the old way of invoking the tools?

**Comment by tzach** [comment]
Since we do not yet use branching in docs, its better to include both for now, stating which is relevant to which release.

**Comment by denesb** [comment]
Ok, will do.

**Comment by denesb** [comment]
Oh, right, the change of hosting the tools in the executable happened before a release was cut, so we have no release shipping with `scylla-types` and `scylla-sstable` named executables.
