### ISSUE TITLE
Concurrent same-name table creation with a different schema leads to a cluster-wide crash 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#11396]
Issuing two CREATE TABLE statements with a different name for one of the partition key columns leads to the following assertion failure on all replicas:  

```
scylla: schema.cc:363: schema::schema(const schema::raw_schema&, std::optional<raw_view_info>): Assertion `!def.id || def.id == id - column_offset(def.kind)' failed.
```

The reason is that once the create table mutations are merged, the `columns` table contains two entries for the same position in the partition key tuple.

If the schemas were the same, or not conflicting in a way which leads to abort, the current behavior would be to drop the older table as if the last CREATE TABLE was preceded by a DROP TABLE.

**Comment by tgrabiec** [comment]
The proposed fix is to make CREATE TABLE mutation include a tombstone for all older schema changes of this table, effectively overriding them. The behavior will be the same as if the schemas were not different, older table will be dropped.

**Comment by avikivity** [comment]
While this fixes an important bug, it isn't a regression and the bug is quite rare, so not backporting.
