### ISSUE TITLE
Cassandra tombstone_warn_threshold functional.

### ISSUE THREAD

**Issue by taras3bor** [scylladb/scylladb#11410]
Cassandra has option in config 'tombstone_warn_threshold'. For queries with tombstones more than that it will show warning messages with raw query text, e.g.:

Node1:
`WARN [ReadStage-1] 2022-08-04 19:13:57,545 ReadCommand.java:536 - Read 1000 live rows and 9000 tombstone cells for query SELECT record_time FROM data_filler2.data WHERE token(dataset) >= token(2) AND token(dataset) <= -2951164572069483307 LIMIT 1000; token -3248873570005575792 (see tombstone_warn_threshold).`
Node2:
`WARN [ReadStage-1] 2022-08-04 19:14:03,662 ReadCommand.java:536 - Read 1000 live rows and 9000 tombstone cells for query SELECT record_time FROM data_filler2.data WHERE token(dataset) >= token(2) AND token(dataset) <= -2951164572069483307 LIMIT 1000; token -3248873570005575792 (see tombstone_warn_threshold)
WARN [ReadStage-1] 2022-08-04 19:14:03,833 ReadCommand.java:536 - Read 1000 live rows and 9000 tombstone cells for query SELECT record_time FROM data_filler2.data WHERE token(dataset) >= token(2) AND token(dataset) <= -2951164572069483307 LIMIT 1000; token -3248873570005575792 (see tombstone_warn_threshold)
WARN [ReadStage-1] 2022-08-04 19:14:04,000 ReadCommand.java:536 - Read 999 live rows and 9000 tombstone cells for query SELECT record_time FROM data_filler2.data WHERE token(dataset) >= token(2) AND token(dataset) <= -2951164572069483307 LIMIT 1000; token -3248873570005575792 (see tombstone_warn_threshold)`

If tombstone_warn_threshold=0 or commented out - logs don`t appear.

In #11053 problem with query timeout because of large tombstones solved. But tombstones still have impact on query time.
It would be good, to reproduce such functional.

*Installation details*
Scylla version (or git commit hash): 5.2.0
Cluster size: 3
OS: CentOS 8 Stream

**Comment by taras3bor** [comment]
I propose a solution to it  https://github.com/scylladb/scylladb/pull/11356

**Comment by mykaul** [comment]
@DoronArazii - let's see what milestone this should be in (it's merged, so I assume 5.1?)

**Comment by DoronArazii** [comment]
@mykaul i'm not sure what it is - or if we need to do something about it.

@avikivity WDYT?

**Comment by mykaul** [comment]
> @mykaul i'm not sure what it is - or if we need to do something about it.

Looks like it's going to land in 5.2, if I follow the PR.

> 
> @avikivity WDYT?

**Comment by avikivity** [comment]
Fixed by b9d55ee02fa0db172a3701b65263e990e9479fba
