### ISSUE TITLE
Scylla fail to install on rocky9 (missing python2 package)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#11435]
When installing scylla on rocky9 is fails with the following error
```
Command: 'sudo yum install -y scylla'

Exit code: 1

Stdout:

Last metadata expiration check: 0:00:05 ago on Thu 01 Sep 2022 09:11:32 PM UTC.
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Stderr:

Error:
 Problem: package scylla-5.2.0~dev-0.20220831.4e413787d2dd.x86_64 requires scylla-tools-core = 5.2.0~dev, but none of the providers can be installed
  - conflicting requests
  - nothing provides python2 needed by scylla-tools-core-5.2.0~dev-0.20220831.4e413787d2dd.noarch
```

SCT PR with the test code for running it:
https://github.com/scylladb/scylla-cluster-tests/pull/5048

```bash
export SCT_IP_SSH_CONNECTIONS=public
export SCT_SCYLLA_REPO=https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/master/rpm/centos/latest/scylla.repo

hydra run-test artifacts_test --backend gce --config test-cases/artifacts/rocky9.yaml
```

python2 package isn't supported anymore in CentOS 9 Stream (python2.7 is EOL for more then 2 years by now)

We are still depended on python2, cause of cqlsh.

**Comment by syuu1228** [comment]
If we merge cassandra-4.x branch from upstream, cqlsh will support python3. But I'm not sure our changes is incompatible with them or not.
Maybe we should backport cqlshlib only, just support pyhon3?

**Comment by syuu1228** [comment]
Or we have to do "relocatable-python2", but we have avoided to do that for years so I guess we should just move to python3.

**Comment by fruch** [comment]
@syuu1228 

few months back, I've was trying to make cqlsh as a separated repo
https://github.com/fruch/cqlsh

similar approach as in https://github.com/jeffwidman/cqlsh

The idea is that we could make it a standalone package (with tests and it's own life-cycle), and pull it where it's needed (i.e. as part of scylla-tools-java, installation for example)


but yes, one other option is only todo the python3 needed changes (but it would be hard to backport only them)

**Comment by avikivity** [comment]
Separate repo for cqlsh would be wonderful.

**Comment by avikivity** [comment]
e.g. scyla-cqlsh.git

**Comment by fruch** [comment]
> e.g. scyla-cqlsh.git

Shouldn't it now be scylladb-cqlsh.git ?

**Comment by yaronkaikov** [comment]
@fruch Once you get https://github.com/scylladb/scylladb/pull/11937 merged, this should be fixed, right ?

**Comment by fruch** [comment]
> @fruch Once you get https://github.com/scylladb/scylladb/pull/11937 merged, this should be fixed, right ?

Yes it should (i.e. we'll need to test, but it should remove the python2 dependency)

**Comment by yaronkaikov** [comment]
Closed with https://github.com/scylladb/scylladb/pull/11937

**Comment by mykaul** [comment]
@tzach - is Rocky 9 (and the others - RHEL 9.x, etc.) are going to be supported in 5.3 and beyond?

**Comment by fruch** [comment]
> @tzach - is Rocky 9 (and the others - RHEL 9.x, etc.) are going to be supported in 5.3 and beyond?

they should, I need to merge/enable the rocky9 test. as for RHEL we don't directly test it, I think the only paid distro we tested is OEL.
