### ISSUE TITLE
Linearizability violations found in ScyllaDB 4.6 LWTs

### ISSUE THREAD

**Issue by Rivers-Shall** [scylladb/scylladb#11442]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

# Installation details
Scylla version (or git commit hash): 4.6.5-0.20220719.2ec293ab0 with build-id 5d88a4812c5100284588735a8ba2755e915f98d5
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): [jgoerzen/debian-base-standard docker image](https://hub.docker.com/r/jgoerzen/debian-base-standard)

# Issue Description
We found linearizability violations in ScyllaDB 4.6 LWTs. 

## The definition of linearizability for LWTs
A history of LWTs satisfies linearizability if there exists a permutation of those LWTs where each LWT reads the value written by its predecessor. 

## Tests and workloads
We designed a specific workload generator for LWTs (available [here](https://github.com/Rivers-Shall/scylla-jepsen-test/blob/master/src/scylla/cas_only_register.clj)) which we have integrated into the [Jepsen](https://jepsen.io/) testing framework. 

Regarding the tests for the violations found, the workload comprises a write operation initializes the (single) key followed by multiple LWTs. Our tests ran with 20 clients and 100 requests per second per client; we injected no fault.

## Violations found

The following shows a snippet of a problematic history (full history available at [here](https://pixeldrain.com/u/RS7mCrRM)) which omits failed, timeout, and the subsequent LWTs. 

```text
// Initializing the key to value 0
{:type :invoke, :f :write, :value 0, :time 3258929299, :process 4, :index 1}
{:type :ok, :f :write, :value 0, :time 3385904647, :process 4, :index 4}

// LWT 1 
{:type :invoke, :f :cas, :value [0 6], :time 3889930164, :process 4, :index 62}
{:type :ok, :f :cas, :value [0 6], :time 3932208553, :process 4, :index 64}

// LWT 2
{:type :invoke, :f :cas, :value [0 7], :time 3932365563, :process 4, :index 65}
{:type :ok, :f :cas, :value [0 7], :time 3959566974, :process 4, :index 69}

// LWT 3 
{:type :invoke, :f :cas, :value [0 9], :time 4238097700, :process 9, :index 120}
{:type :ok, :f :cas, :value [0 9], :time 4611739587, :process 9, :index 204}
```

We observe that all three LWTs finished successfully; however, by the definition of linearizability for LWTs, at most one of them should have committed.

## Reproduction

Please use the virtual machine and follow the instruction [here](https://box.nju.edu.cn/d/3f4b3ab397af44fdbf1b/).

**Comment by tzach** [comment]
@kostja FYI

**Comment by kostja** [comment]
What are the quorum settings in the test? Is it a single-DC or multi-DC setup?

**Comment by Rivers-Shall** [comment]
> What are the quorum settings in the test? Is it a single-DC or multi-DC setup?

I believe in jepsen it is a single-DC setup.

**Comment by Rivers-Shall** [comment]
What is the status of this issue now? Is there a need for more information or assistance?

**Comment by kostja** [comment]
We're working on reproducing the issue, and will get back as soon as we get any questions.

**Comment by Rivers-Shall** [comment]
> > The following shows a snippet of a problematic history (full history available at [here](https://pixeldrain.com/u/RS7mCrRM)) which omits failed, timeout, and the subsequent LWTs.
> 
> > (...) We observe that all three LWTs finished successfully; however, by the definition of linearizability for LWTs, at most one of them should have committed.
> 
> If there were any concurrent ops running with the 3 CAS ops that you presented, they may have made the history legal. E.g. there might have been concurrent CAS ops like `[6 x], [x 0]` happening with the `[0 6]` and `[0 7]` ops. Then the following serialization would make the two ops legal: `[0 6], [6 x], [x 0], [0 7]`. You cannot say there was a violation without looking at the entire history.
> 
> Did Jepsen give you an analysis of this history that proves linearizability failure?

We omitted other failed, timeout, and subsequent LWTs so there cannot be other concurrent ops. And yes, jepsen gave me the report.
```text
// 0 stands for the index of data unit which lwts are performed on.
0 {:linearizable {:valid? false,
                                        :configs ({:model #knossos.model.CASRegister{:value 6},
                                                   :last-op {:process 4,
                                                             :type :ok,
                                                             :f :cas,
                                                             :value [0
                                                                     6],
                                                             :index 64,
                                                             :time 3932208553},
                                                   :pending [{:process 4,
                                                              :type :invoke,
                                                              :f :cas,
                                                              :value [0
                                                                      7],
                                                              :index 65,
                                                              :time 3932365563}]}),
                                        :final-paths ([{:op {:process 4,
                                                             :type :ok,
                                                             :f :cas,
                                                             :value [0
                                                                     6],
                                                             :index 64,
                                                             :time 3932208553},
                                                        :model #knossos.model.CASRegister{:value 6}}
                                                       {:op {:process 4,
                                                             :type :ok,
                                                             :f :cas,
                                                             :value [0
                                                                     7],
                                                             :index 69,
                                                             :time 3959566974},
                                                        :model #knossos.model.Inconsistent{:msg "can't CAS 6 from 0 to 7"}}]),
                                        :previous-ok {:process 4,
                                                      :type :ok,
                                                      :f :cas,
                                                      :value [0 6],
                                                      :index 64,
                                                      :time 3932208553},
                                        :last-op {:process 4,
                                                  :type :ok,
                                                  :f :cas,
                                                  :value [0 6],
                                                  :index 64,
                                                  :time 3932208553},
                                        :op {:process 4,
                                             :type :ok,
                                             :f :cas,
                                             :value [0 7],
                                             :index 69,
                                             :time 3959566974}},
                         :timeline {:valid? true},
                         :valid? false},
```
I also uploaded the [whole history(for all data units)](https://pixeldrain.com/u/P2uhLzQJ), [whole report](https://pixeldrain.com/u/7RtiNhfj), and [jepsen log](https://pixeldrain.com/u/NmgtsWMH).

**Comment by margdoc** [comment]
The `cas-only-register` test uses a client-side timestamps generator and non-conditional update as the initial write. It leads to applying mutation with a timestamp higher than the server's clock. Thus for some time at the beginning of the test, LWT queries can be applied, but the mutation with a higher timestamp (the initial one) overwrites their result. It is mentioned in the [documentation](https://docs.scylladb.com/stable/using-scylla/lwt.html) to not mix client-side timestamps and LWT:
> When using user-supplied timestamps, you must make sure that the timestamp is assigned by the transaction coordinator. If not, it will not be possible to guarantee consistency.

**Comment by kbr-** [comment]
By the way, this statement does not make any sense, it's self-contradictory:
> When using user-supplied timestamps, you must make sure that the timestamp is assigned by the transaction coordinator. If not, it will not be possible to guarantee consistency.

"When using X, you must make sure not to use X".

cc @annastuchlik 

More generally I believe there are absolutely 0 correctness guarantees given if you mix regular writes with LWT ops. No matter if you use coordinator-generated or client-generated timestamps. The coordinator-generated timestamp is no use if there are multiple coordinators performing ops, some of them regular writes, some of them LWTs.
