### ISSUE TITLE
Remove set_configuration from public API

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#11447]
> @[gleb-cloudius](https://github.com/gleb-cloudius) gleb-cloudius [5 days ago](https://github.com/scylladb/scylladb/issues/11447#r959236746)
> I do not think this is our public API any longer. modify_config is. We should hide this in private. @kostja ? Also we already have a check for _abort in wait_for_entry() which this function is calling. The work it does before doing so is insignificant.
>  
> Member
> @[kostja](https://github.com/kostja) kostja [5 days ago](https://github.com/scylladb/scylladb/issues/11447#r959324038)
> We use it in tests, so we can't make it private. We could try to switch tests to modify_config(), I guess.

**Comment by sajdakabir** [comment]
Hey, I want to work on this issue. Can someone guide me, please?

**Comment by kostja** [comment]
Sure. Mostly, to do it, you will need to update the tests to use a replacement call - modify_config(). Other than the tests, set_configuration() is not used now anywhere.

**Comment by sajdakabir** [comment]
Hey, @kostja this is my first-time open-source contribution. I don't understand what I have to do :( .  Can you please tell me more about this?

**Comment by kostja** [comment]
1. First you need to download and build Scylla. The easiest way to do it is to use the frozen toolchain:
https://github.com/scylladb/scylladb/tree/master/tools/toolchain
If you're wiling to bring your on build, e.g. on Ubuntu, best is to connect on Slack - depending on the specific version the issues may vary and dependencies have to be selected and installed manually.

2. Run the tests. Start ./test.py in the root directory after you build, and you'll see the test report flowing in. 

3. Patch raft/server.hh to make set_configuration() private. Follow up on the build failures.

**Comment by kostja** [comment]
@sajdakabir

**Comment by mykaul** [comment]
@kostja , @sajdakabir - any updates?
