### ISSUE TITLE
Doc: clarify the procedure of updating OS packages during ScyllaDB image upgrade 

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#11450]
https://docs.scylladb.com/stable/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2022.1-to-2022.1-image.html#download-and-install-the-new-release
This section describes two procedures for upgrading the image. The way it is documented now may be confusing:

> when i read the procedure i was thinking that we need to do both

Write an introduction to the recommended procedure to clarify there are two procedures and the one involving OS package updates is recommended.

Ask @yaronkaikov  for review.

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
