### ISSUE TITLE
Issue in page Upgrade Guide - ScyllaDB Enterprise 2021.1 to 2022.1 for Red Hat Enterprise Linux 7 or CentOS 7

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylladb#11463]
I would like to report an issue in page https://docs.scylladb.com/master/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2021.1-to-2022.1-rpm

### Problem
> Applicable Versions
This guide covers upgrading ScyllaDB from version 2021.1.8 or later to ScyllaDB Enterprise version **2021.1.y**, on the following platforms:

###  Suggest a fix
This guide covers upgrading ScyllaDB from version 2021.1.8 or later to ScyllaDB Enterprise version **2022.1.y**, on the following platforms:

**Comment by annastuchlik** [comment]
Fixed with https://github.com/scylladb/scylladb/pull/11477
