### ISSUE TITLE
Make DESCRIBE statement work with local indexes

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#11475]
This issue is created ahead of time, and depends on #11106 to be merged first.

Now that we support server-side describe, we can finally fix the issue with DESCRIBE INDEX not working well for local indexes.

Example:
```cql
CREATE TABLE t(id int PRIMARY KEY, v1 int, v2 int);
CREATE INDEX ON t(v1);

DESCRIBE INDEX t_v1_idx ;
> CREATE INDEX t_v1_idx ON test.t (v1); -- this is valid CQL

CREATE INDEX ON t((id),v1);

DESCRIBE INDEX t_v1_idx_1;
> CREATE INDEX t_v1_idx_1 ON test.t ({"pk":["id"],"ck":["v1"]}); -- this is invalid CQL
```
As you can see, describing a local index results in dumping our internal, JSON-based serialization format of the index definition, which prevents users from simply copy-pasting this information to cqlsh in order to recreate this index. Fortunately, now that DESCRIBE output is computed server-side, we can prepare proper, valid strings ourselves, and make sure that describing a local index works as expected, i.e.:

```cql
DESCRIBE INDEX t_v1_idx_1;
> CREATE INDEX t_v1_idx_1 ON test.t ((id), v1);
```

**Comment by Jadw1** [comment]
I'm closing this. It has been resolved in original PR of server-side describe https://github.com/scylladb/scylladb/pull/11106 and works correctly now.

```
cqlsh:ks> create index on t((id),v1);
cqlsh:ks> describe index t_v1_idx_1;

CREATE INDEX t_v1_idx_1 ON ks.t((id), v1);
```

Cc @eliransin @ptrsmrn
