### ISSUE TITLE
Fix the Docker commands for starting and stopping a ScyllaDB node

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#11501]
https://docs.scylladb.com/stable/operating-scylla/procedures/config-change/rolling-restart

The Docker commands use `scylla` instead of `scylla-server`:
```
docker exec -it some-scylla supervisorctl stop scylla
docker exec -it some-scylla supervisorctl start scylla
```

**Fix:**
```
docker exec -it some-scylla supervisorctl stop scylla-server
docker exec -it some-scylla supervisorctl start scylla-server
```

**Comment by tzach** [comment]
@yaronkaikov any idea when did this change (in which release)

**Comment by annastuchlik** [comment]
@tzach I've traced the commands back to 2018, and they have always been `[start|stop] scylla-server` for Linux.
The commands for Docker were added with this commit: https://github.com/scylladb/scylla-docs/commit/23751f96fd8a738c9fe4f5e3be4783593e5a4330. They included `scylla` instead of `scylla-server`. 
It was reported to me as a bug - @yaronkaikov could you confirm?

**Comment by yaronkaikov** [comment]
@annastuchlik @tzach The right commands are:
```
docker exec -it some-scylla supervisorctl stop scylla
docker exec -it some-scylla supervisorctl start scylla
```
Just confirm it locally
```
[yaronkaikov@london]~$ podman run -d docker.io/scylladb/scylla:latest
Trying to pull docker.io/scylladb/scylla:latest...
Getting image source signatures
Copying blob 53b7b6d0ea96 done  
Copying blob 3b65ec22a9e9 done  
Copying config a04dba2caa done  
Writing manifest to image destination
Storing signatures
61512cc6320cd6e29f930622e830906d2b3fb6f12d521288aac26be0f6373b03
[yaronkaikov@london]~$ podman ps -a
CONTAINER ID  IMAGE                                                             COMMAND     CREATED         STATUS             PORTS       NAMES
6ec4753b7080  fc9fd5ea664fd124b5631c227086ba2e60bc442f0c7465d99d3e1f79286c856c              6 days ago      Created                        gallant_mahavira
0c7cbf97da6e  fc9fd5ea664fd124b5631c227086ba2e60bc442f0c7465d99d3e1f79286c856c              6 days ago      Created                        romantic_jang
61512cc6320c  docker.io/scylladb/scylla:latest                                              17 seconds ago  Up 17 seconds ago              serene_blackburn
[yaronkaikov@london]~$ docker exec -it some-scylla su stop scylla-server
Error: No such container: some-scylla
[yaronkaikov@london]~$ podman exec -it serene_blackburn supervisorctl stop scylla-server
scylla-server: ERROR (no such process)
[yaronkaikov@london]~$ podman exec -it serene_blackburn supervisorctl stop scylla
scylla: stopped
[yaronkaikov@london]~$ podman exec -it serene_blackburn supervisorctl start scylla
scylla: started
[yaronkaikov@london]~$ 
```

Who reported this ?

**Comment by Michal-Leszczynski** [comment]
@yaronkaikov I reported this. I noticed it when I was working on scylla-manager where we have docker image for scylla 4.6.1.

```
[miles@fedora scylla-manager]$ podman run -d docker.io/scylladb/scylla:4.6.1
037f6c6efe51072e0b459b7559a0c7da4a208bdfb830b9b7509bc24ad68982ba
[miles@fedora scylla-manager]$ podman ps -a
CONTAINER ID  IMAGE                             COMMAND     CREATED         STATUS             PORTS       NAMES
91e8a878eac2  docker.io/scylladb/scylla:latest              42 minutes ago  Up 42 minutes ago              gallant_mahavira
879c9572b8e6  docker.io/scylladb/scylla:4.6.1               2 minutes ago   Up 2 minutes ago               romantic_jang
037f6c6efe51  docker.io/scylladb/scylla:4.6.1               6 seconds ago   Up 7 seconds ago               serene_blackburn
[miles@fedora scylla-manager]$ podman exec -it serene_blackburn supervisorctl stop scylla
scylla: ERROR (no such process)
[miles@fedora scylla-manager]$ podman exec -it serene_blackburn supervisorctl stop scylla-server
scylla-server: stopped
```
I didn't know that process name changed in the next release (4.6.2). Sorry that I bothered you with this.

**Comment by yaronkaikov** [comment]
> @yaronkaikov I reported this. I noticed it when I was working on scylla-manager where we have docker image for scylla 4.6.1.
> 
> ```
> [miles@fedora scylla-manager]$ podman run -d docker.io/scylladb/scylla:4.6.1
> 037f6c6efe51072e0b459b7559a0c7da4a208bdfb830b9b7509bc24ad68982ba
> [miles@fedora scylla-manager]$ podman ps -a
> CONTAINER ID  IMAGE                             COMMAND     CREATED         STATUS             PORTS       NAMES
> 91e8a878eac2  docker.io/scylladb/scylla:latest              42 minutes ago  Up 42 minutes ago              gallant_mahavira
> 879c9572b8e6  docker.io/scylladb/scylla:4.6.1               2 minutes ago   Up 2 minutes ago               romantic_jang
> 037f6c6efe51  docker.io/scylladb/scylla:4.6.1               6 seconds ago   Up 7 seconds ago               serene_blackburn
> [miles@fedora scylla-manager]$ podman exec -it serene_blackburn supervisorctl stop scylla
> scylla: ERROR (no such process)
> [miles@fedora scylla-manager]$ podman exec -it serene_blackburn supervisorctl stop scylla-server
> scylla-server: stopped
> ```
> 
> I didn't know that process name changed in the next release (4.6.2). Sorry that I bothered you with this.

@Michal-Leszczynski Sure, not a problem.

**Comment by yaronkaikov** [comment]
@Michal-Leszczynski I assume this can be close?

**Comment by annastuchlik** [comment]
@Michal-Leszczynski I appreciate you reporting this. It's always better to make sure something is correct than leave a possible bug in the docs :) 
I'm closing this issue.
