### ISSUE TITLE
Using listen_address as preferred_ip is not nice

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#11502]
When  gossiping-property-file snitch is configured it gossips messaging_service.listen_address() value as the INTERNAL_IP state. The address in question is merely the argument of the `--listen-address` command. If at the same time prefer_local=true, then peer nodes are strongly suggested to _use_ this address to connect to peer with. However, `--listen-address` can validly be `0.0.0.0`, there are no checks about it on start.

refs:
 scylladb/scylla-operator#797
 scylladb/scylladb#11353

**Comment by xemul** [comment]
For the record -- connect("0.0.0.0") effectively means connect("localhost") so such a configuration would wrap nodes into themselves

**Comment by vladzcloudius** [comment]
That's a valid point if we indeed allow `0.0.0.0`.
Our documentation highly discourages to use it: https://docs.scylladb.com/stable/operating-scylla/admin.html#advanced-networking

**Comment by xemul** [comment]
Documentation ... seem to suggest using `127.0.0.1` as listen_address, but in this case the BUG would persist

**Comment by vladzcloudius** [comment]
> Documentation ... seem to suggest using `127.0.0.1` as listen_address, but in this case the BUG would persist

In some cases using `127.0.0.1` both as a `listen_address` and as `INTERNAL_IP` makes sense, e.g. in `ccm`.

There is an explanation which address is used as "internal IP" in our Snitch Doc page: https://docs.scylladb.com/stable/operating-scylla/system-configuration/snitch.html#gossipingpropertyfilesnitch

**Comment by avikivity** [comment]
Not a bug, not backporting.
