### ISSUE TITLE
Scylla doesn't send "per-partition rate limit exceeded exception" even if the driver supports it

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#11517]
In the per-partition rate limiting feature (https://github.com/scylladb/scylla/pull/9810) we introduced a new error code which is returned by Scylla in order to reject requests which go over the limit. Drivers need to negotiate support in order to be able to receive it, otherwise it will be reported as `Config_error` instead. However, due to a mistake, `Config_error` is _always_ sent, even if the driver negotiated support for it.

**Comment by avikivity** [comment]
Backported to 5.1, only vulnerable release.
