### ISSUE TITLE
compaction_window_size accepts a <= 0 value

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#11521]
HEAD https://github.com/scylladb/scylladb/commit/bbad3eac63d1816e5104c8ad7e4a1f304963ef0a

As found out by https://github.com/scylladb/scylladb/pull/11445#discussion_r967776157 - it turns out that in `time_window_compaction_strategy_options` only checks whether `window_size` is a valid integer.

```cpp
        try {
            window_size = std::stoi(it->second);
        } catch (const std::exception& e) {
            throw exceptions::syntax_exception(sstring("Invalid integer value ") + it->second + " for " + COMPACTION_WINDOW_SIZE_KEY);
        }
```

Interesting enough, what a <= 0 window is supposed to do? We better not try to figure it out :-)

FWIW, Cassandra properly rejects this absurd:
**Cassandra**
```cql
cassandra@cqlsh> CREATE TABLE ks.twcs (pk int primary key) WITH compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': 0};
ConfigurationException: 0 must be greater than 1 for compaction_window_size
```

**Comment by raphaelsc** [comment]
Duplicate of #2336.

**Comment by raphaelsc** [comment]
This is a known issue.

**Comment by fee-mendes** [comment]
Thanks, closed as dup then :)
