### ISSUE TITLE
cdc_test.TestCdc.test_cluster_expansion_with_cdc[Multi_DC_cluster] failing sometimes

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#11531]
For example:
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2207/testReport/junit/cdc_test/TestCdc/Sanity_Tests___test_cluster_expansion_with_cdc_Multi_DC_cluster_/

```
        assert len(update_rows) >= confirmed_count
>       assert len(update_rows) <= confirmed_count + unconfirmed_count
E       AssertionError: assert 40432 <= (40337 + 0)
E        +  where 40432 = len([Row(cdc_stream_id=b'\x80\x00\x00\x00\x00\x00\x00\x01G\xe9\x03\x1e(\x00\x00\x01', cdc_time=UUID('81bb947a-332d-11ed-19...-9b23-d3fe07a17223'), cdc_batch_seq_no=0, a=2453, b='3', cdc_operation=2, cdc_ttl=None, tok=-9200450656408261354), ...])
```

The test performs a bunch of writes. Some of them may be unconfirmed (e.g. timed out). This check asserts that the number of CDC log rows is between the number of confirmed and unconfirmed writes.

The first assertion has passed:
```
assert len(update_rows) >= confirmed_count
```
but the second didn't:
```
assert len(update_rows) <= confirmed_count + unconfirmed_count
```

From the details:
```
E       AssertionError: assert 40432 <= (40337 + 0)
```
We know that all writes were confirmed (`unconfirmed_count == 0`), and for some reason `len(update_rows) > confirmed_count`: the CDC log has more rows than there were writes!

One potential explanation for this would be retries: perhaps there was some recent change in the driver configuration of dtest, which caused the driver to retry, so a single write could correspond to many rows in the CDC log (because it was retried)?

**Comment by kbr-** [comment]
Another failure:
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2201/testReport/junit/cdc_test/TestCdc/Sanity_Tests___test_cluster_expansion_with_cdc_Multi_DC_cluster_/

**Comment by kbr-** [comment]
Another:
https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2199/

**Comment by kbr-** [comment]
Apparently there were no such failures observed in the `next` job.
Perhaps this is related to the environment in which CI is running - e.g. slow machines causing the driver to timeout and retry the writes, resulting in multiple CDC log rows per write?

**Comment by kbr-** [comment]
The test disables write retries:
```
            # We don't want the driver to retry writes, because this would cause us to count writes incorrectly.
            stmt.retry_policy = FallthroughRetryPolicy()
```

**Comment by denesb** [comment]
Another https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2280/.

**Comment by kbr-** [comment]
I managed to reproduce on my laptop with brute force: by starting the test concurrently 6 times. I'm guessing the core ingredient in reproducing was nodes competing for resources, which causes them to slow down, schedule tasks differently etc. The test eventually starts 10 nodes with smp=2, my number of cores is 12, so that's roughly 6*10*2/12 = 10 Scylla shards competing for each core.

The test performs a bunch of writes to a CDC-enabled table. Concurrently to the writes it bootstraps the 10th node. Writes are performed by workers. They are writing to a table with two columns `a, b` where `a` is the partition key and `b` is used to store the worker's ID. For a given `(a, b)` pair, there is at most one write with this pair. At the end the test reads the number of CDC log rows and compares it to the total number of writes performed (sum of number of writes performed by each worker). The assertion fails because **the number of CDC log rows is greater than the number of performed writes**.

I modified the test to print the written rows:
```
('0', '0')
('1', '0')
...
```
and also to print the CDC log rows:
```
Row(cdc_stream_id=b"\x80\x03\x08\x0b\x8d\xfew~'f\xa6\x18l\x00\x00\x11", cdc_time=UUID('f9c27222-383c-11ed-7a2b-fc3596554300'), cdc_batch_seq_no=0, a=2731, b='7', cdc_operation=2, cdc_ttl=None, tok=-9222518766204717186)
Row(cdc_stream_id=b"\x80\x03\x08\x0b\x8d\xfew~'f\xa6\x18l\x00\x00\x11", cdc_time=UUID('fa032812-383c-11ed-32b9-17b18cc32868'), cdc_batch_seq_no=0, a=2731, b='2', cdc_operation=2, cdc_ttl=None, tok=-92225187662
...
```

I then tested my first hypothesis: that there is a pair `(a, b)` with two corresponding CDC log rows:
```
$ sed -e 's/.*\(a=.*\), cdc_op.*/\1/' cdclog | sort | uniq -c | grep "2 a"
      2 a=1713, b='0'
      2 a=1713, b='1'
```
indeed.

I looked for the rows in the log:
```
Row(cdc_stream_id=b'\xe7\xb8\x00\x00\x00\x00\x00\x00\x9b\x80\xe5Y(\x00;\xd1', cdc_time=UUID('ed8ef1f6-383c-11ed-a0b9-9c3a3341b52a'), cdc_batch_seq_no=0, a=1713, b='0', cdc_operation=2, cdc_ttl=None, tok=-1749648455233437696)
Row(cdc_stream_id=b'\xe7\xb8\x00\x00\x00\x00\x00\x00\xa3.\xea\xd8$\x00B\x01', cdc_time=UUID('ed8ef1f6-383c-11ed-a0b9-9c3a3341b52a'), cdc_batch_seq_no=0, a=1713, b='0', cdc_operation=2, cdc_ttl=None, tok=-1749648455233437696)
```

Interesting. The rows have the same `cdc$time` value, which is a timeuuid: `ed8ef1f6-383c-11ed-a0b9-9c3a3341b52a`.
This should be impossible. When Scylla makes a write to a CDC-enabled table, it **generates a unique timeuuid** for the `cdc$time` column. Thus, for a given timeuuid, there **must be at most one CDC log row with this timeuuid** in `cdc$time`.

I extracted the timestamp from `ed8ef1f6-383c-11ed-a0b9-9c3a3341b52a` using the following script:
```python3
#!/usr/bin/python3

from uuid import UUID
from datetime import datetime
import sys


def get_timestamp(u):
    return int((UUID(u).time - 0x01b21dd213814000)/10)

t = get_timestamp(sys.argv[1])
print(t)
print(datetime.utcfromtimestamp(t / 1000 / 1000).strftime('%Y-%m-%d %H:%M:%S'))
```
and got:
```
1663606985311487
2022-09-19 17:03:05
```

I then looked at the stream IDs. Do they come from the same generation or from different generations? The generation timestamps are:
```
cqlsh> select time from system_distributed.cdc_generation_timestamps ;
2022-09-19 17:03:32.246000+0000
2022-09-19 17:01:41.452000+0000
2022-09-19 16:59:58.984000+0000
...
```

Since the timestamp of the write is `17:03:05`, it should belong to the second to last generation: `17:01:41.452000+0000`.
```
select range_end, streams from system_distributed.cdc_streams_descriptions_v2 where time = '2022-09-19 17:01:41.452+0000';
```
and indeed, after grepping the output of above for the stream IDs, we can see:
```
-1750542624439147341 | {0xe79d78260801df84dd8dbbb2fc003bc1, 0xe7a0000000000000c6ec85ccb8003bc1}
-1695033994071600375 | {0xe7b4d2c2021fe4b436eaee626c003bd1, 0xe7b80000000000009b80e55928003bd1}
-1680135501370461410 | {0xe87a07902526930a6d69f8d204003be1, 0xe880000000000000b9bed6ffe4003be1}
```
the stream ID `0xe7b80000000000009b80e55928003bd1` is the partition key of the first of our two CDC log rows.

The second rows' stream ID can actually be found in the last generation:
```
select range_end, streams from system_distributed.cdc_streams_descriptions_v2 where time = '2022-09-19 17:03:32.246+0000';
```

```
-1750542624439147341 | {0xe79d78260801df843c48ec4ff80041f1, 0xe7a0000000000000bed8dc1e640041f1}
-1695033994071600375 | {0xe7b4d2c2021fe4b4d2f253ee84004201, 0xe7b8000000000000a32eead824004201}
-1680135501370461410 | {0xe87a07902526930abe978a5e58004211, 0xe880000000000000c752e8564c004211}
```
the stream ID is `0xe7b8000000000000a32eead824004201`.

This second row should not exist, because the stream ID comes from a generation that started operating after the row's timestamp.
I looked at Scylla logs to see when this generation was created:
```
INFO  2022-09-19 17:03:21,177 [shard 0] cdc - Inserting new generation data at UUID 21da0719-57a1-4616-8921-eaabd6aad686
INFO  2022-09-19 17:03:21,246 [shard 0] cdc - New CDC generation: (2022/09/19 17:03:32, 21da0719-57a1-4616-8921-eaabd6aad686)
```

interesting: the generation was created at `17:03:21`. The write's timestamp is `17:03:05`. So the write was performed **16 seconds before that generation was even created**. So it was impossible for the CDC code to write using this stream ID!

So we have a row in a partition to which it wasn't written?

Interestingly, if the write was performed 30 seconds later, that's the stream ID which should have been used. The two stream IDs belong to the same vnode and the same shard.

Conclusion? I'm suspecting there's a bug on the read path somewhere. I recall we had some bugs in the past with mutation fragment streams where partitions were not being closed and we could mix in some rows from a subsequent next partition to the earlier partition in the result while doing range scans. A similar thing could have happened here: the second stream ID (from the "wrong" generation) is a neighbor of the first stream ID (to which the row belongs) in token order, so during partition scans the two stream IDs would appear consecutively. If a bug caused the read result to place rows in the wrong partitions, then read repair wrote the row back so now it appears in every query.

Alternatively, there could be a bug in streaming/repair (dunno which one is used by default now) which mixes rows from different partitions: the test does bootstrap a node concurrently with the writes; streaming started shortly after this write. I'm gonna see if the problem reproduces without the bootstrap.

@denesb @tgrabiec were there any tricky changes to the read path recently (2-4 weeks ago)?

**Comment by denesb** [comment]
Very likely caused by https://github.com/scylladb/scylladb/issues/11561.

**Comment by denesb** [comment]
You can try applying the fix and rerunning your reproducer. The fix is here https://github.com/scylladb/scylladb/pull/11532/commits/852f8f0677b9dcdf37e40f841d4f22d201708715 (part of https://github.com/scylladb/scylladb/pull/11532).

**Comment by avikivity** [comment]
And such fixes should be extracted! But if the fix is already available (and you're confident in it), we can apply it.

**Comment by kbr-** [comment]
@denesb but I see that your PR https://github.com/scylladb/scylladb/pull/11532 had a CI failure due to this test :D So either this is not the cause, or the PR does not completely fix the problem.

**Comment by denesb** [comment]
Hmm, indeed.

**Comment by avikivity** [comment]
@kbr- please repeat your reproducer with #11561 reverted to see.

**Comment by denesb** [comment]
> And such fixes should be extracted! But if the fix is already available (and you're confident in it), we can apply it.

It fixed another failing dtest that was consistently failing once I added validation to the read path.

**Comment by kbr-** [comment]
> @kbr- please repeat your reproducer with https://github.com/scylladb/scylladb/issues/11561 reverted to see.

Will do.

> @kbr- you can use scylla sstable to dump sstables of the CDC table directly to see whether this is an artifact of the read or indeed the stray row is present on the disk.

The read results would be nondeterministic - it's a concurrency bug, right?
If so, then combined with the fact that I'm getting these rows on every read now - they're probably already in sstables.
They could end up there due to read repair, though.

**Comment by denesb** [comment]
Read repair doesn't use the buggy evictable reader (unless the read is a range scan itself). You can check the origin of sstables (unless they were compacted) with `scylla sstable --dump-scylla-metadata`

**Comment by kbr-** [comment]
> unless the read is a range scan itself

well yes, the test retrieves the data using a full scan.

**Comment by kbr-** [comment]
I removed the `co_await maybe_yield()`, didn't help. Still reproduces.

**Comment by kbr-** [comment]
I need to find a reproducer which doesn't take 20 minutes.

**Comment by kbr-** [comment]
What the heck.
Two observations.
1. The problem only reproduces in Multi-DC setup.
2. I bisected it to 6dedc69608810d455d3233b71e8d67af6a41b004 (cc @xemul ) - it doesn't reproduce on that commit's parent (16a3e55aa166cd5b8f349abad4dd75b80eba526d). 

But I don't understand how this commit could cause a row to appear in the wrong partition... and what does this thing have to do with Multi-DC vs Single-DC?

**Comment by kbr-** [comment]
Even if we introduced or fixed a bug which modified how replica sets were calculated for writes or reads, this should not cause rows to appear in the wrong partitions. Calculating replica sets wrongly should only cause data not to appear. I would be more inclined to believe that there's a pre-existing bug which was unmasked.

**Comment by avikivity** [comment]
6dedc69608810d455d3233b71e8d67af6a41b004 is itself a fix, we can't revert it.

**Comment by avikivity** [comment]
It was merged 16 days ago. Does that agree with when the flakiness started appearing?

**Comment by kbr-** [comment]
The first CI failure was observed 8 days ago, according to my knowledge.
It's plausible (if there were not too many CI runs between 8 days ago and 16 days ago, we could have been (un)lucky enough not to get it during this time).

Note that I can reliably reproduce it on https://github.com/scylladb/scylladb/commit/6dedc69608810d455d3233b71e8d67af6a41b004 but the same method does not work on https://github.com/scylladb/scylladb/commit/16a3e55aa166cd5b8f349abad4dd75b80eba526d.

**Comment by avikivity** [comment]
So we have the following options:

1. revert 6dedc69608810d455d3233b71e8d67af6a41b004 and 4cbe6ee9f40c6b744c907b657969d79939026d8b
2. find the problem

I'll go with 1, @xemul can follow up with a fixed 4cbe6ee9f40c6b744c907b657969d79939026d8b.

**Comment by avikivity** [comment]
It's not so easy, 4cbe6ee9f40c6b744c907b657969d79939026d8b is part of a merge (421557b40aa8d1adf5016722418936a99595cb20), I don't know what's the impact of reverting it. I guess we can try.

**Comment by kbr-** [comment]
@avikivity if you decide to and do the revert, before applying the revert to `master`, give me the branch and I'll check if the problem does not reproduce on that branch.

**Comment by kbr-** [comment]
This new setting (single DC with single node + NTS) also does not reproduce on https://github.com/scylladb/scylladb/commit/16a3e55aa166cd5b8f349abad4dd75b80eba526d.

**Comment by kbr-** [comment]
This actually makes some sense.

This is evidence that https://github.com/scylladb/scylladb/commit/4cbe6ee9f40c6b744c907b657969d79939026d8b broke the way replica sets are calculated in NetworkTopologyStrategy.

When we have more than 1 replica, when we bootstrap a node, there will be some intersection between old replica sets and new replica sets for any vnode. So even if we calculate, say, 1 of these replicas incorrectly, but we have more than 1 replicas to perform reads from, we won't miss any row.

When I reduced the replica sets to 1 replica, when we bootstrap a node and change replica sets, there is no intersection. So if we calculate replicas incorrectly now, we will miss rows. And that is what I'm observing.

It's also plausible that the commit broke how we calculate replica sets in NTS, because it modifies stuff related to `topology`, which affects how we caluculate DCs and racks for nodes, which affects how NTS calculates replica sets.

Still, this does not explain why in the many-replicas case we're getting extra rows; I think that is related to some other bug which this change has only unmasked.

**Comment by kbr-** [comment]
> Still, this does not explain why in the many-replicas case we're getting extra rows; I think that is related to some other bug which this change has only unmasked.

Even if we calculated replica sets completely randomly - we should never ever mix rows from different partitions. Let's say we ask the wrong replica for a partition X, or a partition range that contains X, which that replica doesn't have. This replica would return a stream of mutation fragments which does not contain X. When the coordinator merges this stream with streams from other replicas it should simply skip anything that this replica has returned, and not mix in stuff from other partitions to the result that it calculates for X.

**Comment by kbr-** [comment]
> The coordinator does not do additional filtering on the partition key or token.

The coordinator merges mutation streams obtained from different replicas. These streams may contain multiple partitions. Even if there were some extra partitions which we didn't ask for (and there shouldn't be really), the coordinator should not mix them up while merging.

**Comment by avikivity** [comment]
> > The coordinator does not do additional filtering on the partition key or token.
> 
> The coordinator merges mutation streams obtained from different replicas. These streams may contain multiple partitions. Even if there were some extra partitions which we didn't ask for (and there shouldn't be really), the coordinator should not mix them up while merging.

With this I agree.

**Comment by xemul** [comment]
4cbe6ee9f40c6b744c907b657969d79939026d8b moved adding a node to topology from out of `update_normal_tokens`. It's possible that there was an extra call to update_topology() that added a entry while it shouldn't. Here's a suspicious place that probably should not be there in storage_service::bootstrap():

```c++
            if (!bootstrap_rbno) {
                // When is_repair_based_node_ops_enabled is true, the bootstrap node
                // will use node_ops_cmd to bootstrap, node_ops_cmd will update the pending ranges.
                slogger.debug("bootstrap: update pending ranges: endpoint={} bootstrap_tokens={}", get_broadcast_address(), bootstrap_tokens);
                mutate_token_metadata([this, &bootstrap_tokens] (mutable_token_metadata_ptr tmptr) {
                    auto endpoint = get_broadcast_address();
                    tmptr->update_topology(endpoint, _sys_ks.local().local_dc_rack());
                    tmptr->add_bootstrap_tokens(bootstrap_tokens, endpoint);
                    return update_pending_ranges(std::move(tmptr), format("bootstrapping node {}", endpoint));
                }).get();
            }
```

**Comment by kbr-** [comment]
@xemul still fails.

If you want to reproduce the "missing rows" case reliably, apply this patch to cdc_test.py:
```diff
diff --git a/cdc_test.py b/cdc_test.py
index f8cdc224..c9ff86b9 100644
--- a/cdc_test.py
+++ b/cdc_test.py
@@ -89,7 +89,7 @@ class CDCInitializeHelper:  # pylint: disable=no-member
                 node_idx += 1
                 logger.debug('Starting node {}'.format(node_idx))
                 node = self.cluster.new_node(
-                    node_idx, data_center=f"dc{dcx}", auto_bootstrap=True)  # pylint: disable=no-member
+                    node_idx, data_center=f"datacenter{dcx}", auto_bootstrap=True)  # pylint: disable=no-member
                 node.start(wait_for_binary_proto=True, wait_other_notice=wait_other_notice)
 
     # Retrieve the ID of the last known generation from the local tables of the node `session` is connected to.
@@ -152,10 +152,10 @@ class CDCInitializeHelper:  # pylint: disable=no-member
 @pytest.mark.dtest_full
 class TestCdc(Tester, CDCInitializeHelper):
     SINGLE_DC_SIZE = [3]
-    MULTI_DC_SIZE = [3, 3, 3]
+    MULTI_DC_SIZE = [1]
 
     SINGLE_DC_REPL = f"{{'class': 'SimpleStrategy', 'replication_factor': {SINGLE_DC_SIZE[0]}}}"
-    _replication = ", ".join([f"'dc{i}': {n}" for i, n in enumerate(MULTI_DC_SIZE, start=1)])
+    _replication = ", ".join([f"'datacenter{i}': {n}" for i, n in enumerate(MULTI_DC_SIZE, start=1)])
     MULTI_DC_REPL = f"{{'class': 'NetworkTopologyStrategy', {_replication}}}"
 
     @pytest.fixture(scope='function', autouse=True)
```

(it simply reduces the test from 3 DCs 3 nodes each to 1 DC with 1 node, but it also changes the dc name from `dc1` to `datacenter1` because for some reason when there's one datacenter Scylla throws an error that it expects the dc name to be `datacenter1 - probably another bug or sth -.-)

**Comment by kbr-** [comment]
@avikivity with your reverts I failed to repro, both the "missing rows" and the "too many rows" cases.

**Comment by kbr-** [comment]
But we must investigate the "too many rows" case - I claim that a row should never appear in the wrong partition, even if we calculated replicas completely randomly.

**Comment by xemul** [comment]
6dedc69608810d455d3233b71e8d67af6a41b004 has this hunk

```patch
@@ -854,6 +854,7 @@ void token_metadata_impl::calculate_pending_ranges_for_bootstrap(
     for (auto& x : tmp) {
         auto& endpoint = x.first;
         auto& tokens = x.second;
+        all_left_metadata->update_topology(endpoint, {});
         all_left_metadata->update_normal_tokens(tokens, endpoint).get();
         for (auto& x : strategy.get_address_ranges(*all_left_metadata, endpoint).get0()) {
             new_pending_ranges.emplace(x.second, endpoint);
```

which adds a entry without dc/rack and this _does_ affect the result for NTS

**Comment by xemul** [comment]
@kbr- , would you please give :point_up: a shot? It fixed the test (patched with your patch) for me

**Comment by kbr-** [comment]
@xemul it seems to work

**Comment by avikivity** [comment]
> @avikivity with your reverts I failed to repro, both the "missing rows" and the "too many rows" cases.

The trichotomy theorem leads me to believe you did reproduce the "exactly the right number of rows" case.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
