### ISSUE TITLE
SStables in maintenance set will be forgotten if user stopped off-strategy compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#11543]
Doesn't affect reshape on boot, only off-strategy compaction triggered by repair-based ops.

If user stops off-strategy compaction using API, compaction manager will propagate the error but will give up on off-strategy compaction altogether.

That's problematic because sstables in maintenance set won't be compacted with the rest of the data in main set, leading to an increase in space and read amplification.

**Comment by raphaelsc** [comment]
That happens until off-strategy is triggered again by another node op, which cannot happen anytime soon.

**Comment by avikivity** [comment]
Backported to 5.1. @raphaelsc please evaluate for 5.0.

**Comment by avikivity** [comment]
@raphaelsc ^

**Comment by denesb** [comment]
All live versions have this, removing label.
