### ISSUE TITLE
shard_reader can leave partitions unclosed when buffer-copying loop yields

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11561]
Regression caused by 8ab57aa4ab.
The above commit introduced a yield in the loop copying the fragments from the remote shard. This yield can allow the multishard reader to run before the shard reader is run again, consuming the half-copied buffer from the shard reader. If the remote reader is EOS and this is the last buffer, the multishard reader will consider the shard reader to be EOS as the `_end_of_stream` flag is updated before the buffer is copied. As a consequence of this the multishard reader will not consider this shard reader anymore, dropping the remaining uncopied part of the buffer. Worse still, if the copy stopped in the middle of a partition, the partition won't be closed before the new one is opened from another shard.

**Comment by denesb** [comment]
Affected versions: 5.1+.

**Comment by avikivity** [comment]
I'll revert it (and backport the revert), we can rework the original patch later.

**Comment by avikivity** [comment]
It's not cleanly revertable.

**Comment by kbr-** [comment]
Due to
5ca73019dd5a08e335daa26a868ad45fb59def6d

**Comment by avikivity** [comment]
It's easy to work around it. But I'll wait to see if it's indeed the root cause.
