### ISSUE TITLE
Long multiple reactor stalls when working with many tables 

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11574]
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc1-20220902.a9bc6d191031` with build-id `074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc1.0.20220902.a9bc6d191031.tar.gz
Cluster size: 1 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-5000-tables-2022-2-db-node-e63869e7-6 (52.18.182.189 | 10.4.3.157) (shards: 30)
- longevity-5000-tables-2022-2-db-node-e63869e7-5 (52.209.184.81 | 10.4.1.177) (shards: 30)
- longevity-5000-tables-2022-2-db-node-e63869e7-4 (34.244.117.125 | 10.4.0.207) (shards: 30)
- longevity-5000-tables-2022-2-db-node-e63869e7-3 (34.252.129.47 | 10.4.1.67) (shards: 30)
- longevity-5000-tables-2022-2-db-node-e63869e7-2 (63.33.212.36 | 10.4.2.140) (shards: 30)
- longevity-5000-tables-2022-2-db-node-e63869e7-1 (34.250.225.7 | 10.4.0.243) (shards: 30)

OS / Image: `ami-0492fd8e302e5af45` (aws: eu-west-1)

Test: `scale-5000-tables-test`
Test id: `e63869e7-14a8-4815-aee1-d12107a6f01d`
Test name: `enterprise-2022.2/scale/scale-5000-tables-test`
Test config file(s):

- [longevity-5000-tables.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2c58692522ad32eb07c2b8c4ebda8414843d169a/test-cases/scale/longevity-5000-tables.yaml)

## Issue description
Test scenario:
1. create test cluster with 1 node (i3.8xlarge)
2. create 5000 tables
3. add another 4 nodes one by one to cluster

On newly added nodes we see multiple reactor stalls - see attached from 2 nodes. If neeeded I can provide decoded ones from all the nodes.

[decoded-stalls-node-2.log](https://github.com/scylladb/scylladb/files/9598515/decoded-stalls-node-2.log)
[decoded-stalls-node-3.log](https://github.com/scylladb/scylladb/files/9598517/decoded-stalls-node-3.log)

Example lines:
```
2022-09-14T14:48:25+00:00 longevity-5000-tables-2022-2-db-node-e63869e7-2     !INFO | scylla[7945]: Reactor stalled for 2460 ms on shard 0. Backtrace: 0x4ef30a2 0x4ef1d00 0x4ef2fb0 0x7f43d082aa1f 0xad90e 0x304491a 0x304d2b1 0x304c3b7 0x2aeecd0 0x2b41a90 0x2b40120 0x2b3c96f 0x2b271b5 0x2b8abbf 0x4f02894 0x4f03c77 0x4f02ecc 0x4ea9b38 0x4ea9011 0x110f8a5 0x110ce5a 0x27b74 0x110bd2d
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:774
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:793
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1368
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1110
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1127
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1351
?? ??:0
?? ??:0
std::_Hash_impl::hash(void const*, unsigned long, unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/functional_hash.h:198
 (inlined by) std::hash<std::basic_string_view<char, std::char_traits<char> > >::operator()(std::basic_string_view<char, std::char_traits<char> > const&) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/string_view:695
 (inlined by) std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >::operator()(seastar::basic_sstring<char, unsigned int, 15u, true> const&) const at ././seastar/include/seastar/core/sstring.hh:662
 (inlined by) std::__detail::_Hash_code_base<seastar::basic_sstring<char, unsigned int, 15u, true>, std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, std::__detail::_Select1st, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>::_M_hash_code(seastar::basic_sstring<char, unsigned int, 15u, true> const&) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable_policy.h:1219
 (inlined by) std::pair<std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>, bool> std::_Hashtable<seastar::basic_sstring<char, unsigned int, 15u, true>, std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value> >, std::__detail::_Select1st, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, true> > > >(std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, true> > > const&, std::integral_constant<bool, true>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable.h:2102
 (inlined by) void std::__detail::_Insert_base<seastar::basic_sstring<char, unsigned int, 15u, true>, std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value> >, std::__detail::_Select1st, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_range<std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, true> > > >(std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>, std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, true> > > const&, std::integral_constant<bool, true>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable_policy.h:905
 (inlined by) void std::__detail::_Insert_base<seastar::basic_sstring<char, unsigned int, 15u, true>, std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value> >, std::__detail::_Select1st, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::insert<std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true> >(std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>, std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/hashtable_policy.h:887
 (inlined by) void std::unordered_map<seastar::basic_sstring<char, unsigned int, 15u, true>, query::non_null_data_value, std::hash<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::equal_to<seastar::basic_sstring<char, unsigned int, 15u, true> >, std::allocator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value> > >::insert<std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true> >(std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>, std::__detail::_Node_iterator<std::pair<seastar::basic_sstring<char, unsigned int, 15u, true> const, query::non_null_data_value>, false, true>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unordered_map.h:617
 (inlined by) query::result_set_builder::accept_new_row(clustering_key_prefix const&, query::result_row_view const&, query::result_row_view const&) at ./query-result-set.cc:103
void query::result_view::consume<query::result_set_builder&>(query::partition_slice const&, query::result_set_builder&) const at ././query-result-reader.hh:177
void query::result_view::consume<query::result_set_builder&>(query::result const&, query::partition_slice const&, query::result_set_builder&) at ././query-result-reader.hh:156
 (inlined by) query::result_set::from_raw_result(seastar::lw_shared_ptr<schema const>, query::partition_slice const&, query::result const&) at ./query-result-set.cc:206
 (inlined by) operator() at ./query-result-set.cc:213
 (inlined by) result_set at ./query-result-set.cc:210
db::schema_tables::create_view_from_mutations(db::schema_ctxt const&, schema_mutations, std::optional<utils::UUID>) at ./db/schema_tables.cc:3117
operator() at ./db/schema_tables.cc:1315
 (inlined by) seastar::noncopyable_function<seastar::lw_shared_ptr<schema const> (schema_mutations, db::schema_tables::schema_diff_side)>::direct_vtable_for<db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&)::$_54>::call(seastar::noncopyable_function<seastar::lw_shared_ptr<schema const> (schema_mutations, db::schema_tables::schema_diff_side)> const*, schema_mutations, db::schema_tables::schema_diff_side) at ././seastar/include/seastar/util/noncopyable_function.hh:124
seastar::noncopyable_function<seastar::lw_shared_ptr<schema const> (schema_mutations, db::schema_tables::schema_diff_side)>::operator()(schema_mutations, db::schema_tables::schema_diff_side) const at ././seastar/include/seastar/util/noncopyable_function.hh:209
db::schema_tables::diff_table_or_view(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, seastar::noncopyable_function<seastar::lw_shared_ptr<schema const> (schema_mutations, db::schema_tables::schema_diff_side)>) at ./db/schema_tables.cc:1280
db::schema_tables::merge_tables_and_views(seastar::sharded<service::storage_proxy>&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&, std::map<utils::UUID, schema_mutations, std::less<utils::UUID>, std::allocator<std::pair<utils::UUID const, schema_mutations> > >&&) at ./db/schema_tables.cc:1307
db::schema_tables::do_merge_schema(seastar::sharded<service::storage_proxy>&, std::vector<mutation, std::allocator<mutation> >, bool) at ./db/schema_tables.cc:1158
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2345
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2752
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2921
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2804
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:265
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:156
scylla_main(int, char**) at ./main.cc:566
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) main at ./main.cc:1727
?? ??:0
_start at ??:?
_start at ??:?

```

- Restore Monitor Stack command: `$ hydra investigate show-monitor e63869e7-14a8-4815-aee1-d12107a6f01d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e63869e7-14a8-4815-aee1-d12107a6f01d)
- Show all stored logs command: `$ hydra investigate show-logs e63869e7-14a8-4815-aee1-d12107a6f01d`

## Logs:
| 20220915_203649 | critical       | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/critical-e63869e7.log.tar.gz       |
| 20220915_203649 | db-cluster     | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/db-cluster-e63869e7.tar.gz         |
| 20220915_203649 | debug          | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/debug-e63869e7.log.tar.gz          |
| 20220915_203649 | email_data     | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/email_data-e63869e7.json.tar.gz    |
| 20220915_203649 | error          | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/error-e63869e7.log.tar.gz          |
| 20220915_203649 | event          | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/events-e63869e7.log.tar.gz         |
| 20220915_203649 | left_processes | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/left_processes-e63869e7.log.tar.gz |
| 20220915_203649 | loader-set     | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/loader-set-e63869e7.tar.gz         |
| 20220915_203649 | monitor-set    | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/monitor-set-e63869e7.tar.gz        |
| 20220915_203649 | normal         | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/normal-e63869e7.log.tar.gz         |
| 20220915_203649 | output         | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/output-e63869e7.log.tar.gz         |
| 20220915_203649 | event          | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/raw_events-e63869e7.log.tar.gz     |
| 20220915_203649 | summary        | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/summary-e63869e7.log.tar.gz        |
| 20220915_203649 | warning        | https://cloudius-jenkins-test.s3.amazonaws.com/e63869e7-14a8-4815-aee1-d12107a6f01d/20220915_203649/warning-e63869e7.log.tar.gz        |
+-----------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------+

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/scale/job/scale-5000-tables-test/4/)

**Comment by slivne** [comment]
potentially a regression - need to check the stalls and see when they happen (in schema creation or during other steps)

**Comment by bhalevy** [comment]
@tgrabiec please look into this

**Comment by tgrabiec** [comment]
I don't understand the stall report:

```
| | | ++[3#1/1 100%] addr=0x128ac38 total=8862 count=6 avg=1477:
| | | |              table at ./replica/database.hh:776
| | | |              (inlined by) seastar::lw_shared_ptr<replica::table>::make<seastar::lw_shared_ptr<schema const>&, replica::table::config, db::commitlog&, compaction_manager&, sstables::sstables_manager&, cell_locker_stats&, cache_tracker&> at ././seastar/include/seastar/core/shared_ptr.hh:268
| | | |              (inlined by) seastar::make_lw_shared<replica::table, seastar::lw_shared_ptr<schema const>&, replica::table::config, db::commitlog&, compaction_manager&, sstables::sstables_manager&, cell_locker_stats&, cache_tracker&> at ././seastar/include/seastar/core/shared_ptr.hh:418
| | | |              (inlined by) replica::database::add_column_family at ./replica/database.cc:976
| | |   ++[4#1/1 100%] addr=0x128d7f8 total=13289 count=9 avg=1477:
```

Why is `total` for the child node (`[4#1/1 100%] addr=0x128d7f8 total=13289`) greater than the total for the parent node? `[3#1/1 100%] addr=0x128ac38 total=8862 count=6 avg=1477`. What's the meaning and unit of `total`?

**Comment by bhalevy** [comment]
@tgrabiec can you share the whole report?
If it's a "link" to a common suffix, it might be called from multiple paths, hence having a greater `total` than it's parent on this path.

**Comment by tgrabiec** [comment]
@bhalevy It's https://github.com/scylladb/scylladb/files/9598515/decoded-stalls-node-2.log from the first message.

IMO, it's confusing to show total form the caller perspective if you group the tree form the callee perspective.

**Comment by tgrabiec** [comment]
I don't recall anything changing recently in this code path, so on the surface it doesn't look like regression.

**Comment by fgelcer** [comment]
> @soyacz Can you please attach the stall report for node-2 from the caller perspective?

@bhalevy , how could we do that?

**Comment by tgrabiec** [comment]
@fgelcer It says `Use --direction=top-down to print callers first.`

**Comment by soyacz** [comment]
[stalls-2-top-down-decoded.log](https://github.com/scylladb/scylladb/files/9633429/stalls-2-top-down-decoded.log)
[stalls-3-top-down-decoded.log](https://github.com/scylladb/scylladb/files/9633430/stalls-3-top-down-decoded.log)

**Comment by avikivity** [comment]
Now it's clear. schema_tables.cc is littered with calls to coroutine::parallel_for_each(), and with a large number of inputs this can be expensive.

**Comment by avikivity** [comment]
I guess we can litter them with maybe_yield() as the first statement. The alternative is to add yields in coroutine::parallel_for_each(), though that penalizes the common use case of limited concurrency. Maybe we should use max_concurrent_for_each() instead (seems like a good idea anyway).

**Comment by raphaelsc** [comment]
> > I guess we can litter them with maybe_yield() as the first statement. The alternative is to add yields in coroutine::parallel_for_each(), though that penalizes the common use case of limited concurrency.
> 
> Even then, the loop in the `coroutine::parallel_for_each` constructor won't yield. It will just queue the unavailable future and go on with its business.
> 
> See https://github.com/scylladb/seastar/blob/92fdfec585ad41a3f36159eacf9a784a3ee960db/include/seastar/coroutine/parallel_for_each.hh#L116-L133
> 
> > Maybe we should use max_concurrent_for_each() instead (seems like a good idea anyway).
> 
> Agreed. Some parallelism can help for parallelizing I/O but we don't need unlimited parallelism.

Unlimited parallelism is rarely a good idea. I have some examples in my mind where it shoot us in the foot, due to memory usage exploding and CPU hogging. parallel_for_each() is good when the container is small, but once it grows to high amounts, it can become problematic. We should prefer and recommend the variant that enforces a limit.
