### ISSUE TITLE
docs: Issue in page Migrate to Scylla

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11573]
I would like to report an issue in page https://docs.scylladb.com/master/using-scylla/migrate-scylla

### Problem

Link to "unirestore" leads to private github repo: https://github.com/scylladb/field-engineering/tree/master/unirestore
For people who are not members of the scylla github organization this will result in "Page not found" page.

###  Suggest a fix

The tool has to be moved to a publicly accessible repository.

**Comment by denesb** [comment]
@tzach @annastuchlik

**Comment by tzach** [comment]
I suggest to remove the link for now.
Next version of Scylla Manager will include a similar restore function, base on the Manager backup format.

**Comment by avikivity** [comment]
No production impact, not backporting.
