### ISSUE TITLE
Materialized View non primary key "is not null" meaningless condition

### ISSUE THREAD

**Issue by dennissetiawan** [scylladb/scylladb#11606]
I would like to file an issue about a non functional is not null condition when trying to create materialized view.

FOR EXAMPLE:
```
CREATE TABLE test (
	id text PRIMARY KEY,
	flag text,
	value TEXT
)

CREATE MATERIALIZED VIEW test_notnull AS
	SELECT * FROM test WHERE value IS NOT NULL AND flag IS NOT NULL PRIMARY KEY(value,id);


INSERT INTO test (id,value) VALUES ('b','222');
SELECT * FROM test_notnull;
```

When I select the MV the value is there even if the flag is null. 
It's misleading that we allow setting IS NOT NULL for a non-key column and then ignore the restriction

**Comment by nyh** [comment]
Closing as a duplicate of #10365.
