### ISSUE TITLE
 db/view: view_builder::execute(): injects partition-start unconditionally on resuming build-step

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11607]
When resuming a build-step, the view builder injects the partition-start
fragment of the last processed partition, to bring the consumer
(compactor) into the correct state before it starts to consume the
remainder of the partition content. This results in an invalid fragment
stream when the partition was actually over or there is nothing left for
the build step.

**Comment by avikivity** [comment]
What's the impact?

**Comment by denesb** [comment]
I don't know of any impact downstream. It can be benign or we just didn't notice until the validator started screaming.

**Comment by avikivity** [comment]
I guess what happens (before the fix) is:

start p1
row p1
row p1
row p1
end p1
start p1   <-- bad
start p2
row p2
row p2
end p2

and because the consumer don't care about the extra start p1, nothing bad happens.

Does this look correct?

**Comment by denesb** [comment]
Yes, this is what I think was the case.

**Comment by avikivity** [comment]
Yes it does, but "the consumer" is compact_for_query, not what I thought it would be.

**Comment by avikivity** [comment]
Shouldn't we also be closing and re-opening range tombstones?

**Comment by denesb** [comment]
The closing is taken care of by the compactor when the step is stopped. But the resuming is not because we start a new consumer and reuse the same reader (so the range tombstone is not re-emited). I created a separate issue for this: https://github.com/scylladb/scylladb/issues/11668.

**Comment by denesb** [comment]
Wow, we also loose the partition tombstone. How did no one stumble on this. Also, we lost the range tombstone(s) even with v1, so the bug is there since the beginning.

**Comment by avikivity** [comment]
@nyh please comment

**Comment by nyh** [comment]
@avikivity unfortunately there's not much I can say except that clearly, we have a lot of complicated code regarding pausing build steps (I don't even remember what this is about...) that was never covered in a test case :-( If I understand what @denesb wrote, this issue is marked close, but #11668 is open. The first step towards fixing that issue should be to be able to reproduce it in a test case.
@denesb did you reach this situation in one the existing bigger tests and found this with your validator, or what?

**Comment by denesb** [comment]
My validator didn't found this. My validator only found the extra partition-start case that this issue is about. When discussing whether to backport or not, @avikivity asked whether we should also re-emit range-tombstones when re-emitting the partition start. Upon looking at the issue closer (and writing a unit test) I found that indeed this is broken and not just for range tombstone changes: also for v1 range tombstones and partition tombstones.

**Comment by avikivity** [comment]
I'm considering for backport but am confused due to lack of tests (so no indication what's the impact).

**Comment by denesb** [comment]
This issue was found by the validator (https://github.com/scylladb/scylladb/pull/11532).

**Comment by avikivity** [comment]
@denesb I'm stuck on backport decision.

**Comment by denesb** [comment]
No need to backport, as https://github.com/scylladb/scylladb/issues/11668 also fixes this and it is already backported.
