### ISSUE TITLE
Upgrade test: delete DB entries are still listed with CL=QUORUM

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11618]
## Installation details

Kernel Version: 4.18.0-408.el8.x86_64
Scylla version (or git commit hash): `2022.1.2-20220905.f1a246a8b` with build-id `aae082a8a9a1136b4d3f3751749267327a63014b`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.1/scylla-enterprise-x86_64-package-2022.1.2.0.20220905.f1a246a8b.tar.gz
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-8-db-node-a406b619-0-4 (35.229.26.65 | 10.142.0.27) (shards: 8)
- rolling-upgrade--centos-8-db-node-a406b619-0-3 (34.73.145.224 | 10.142.0.25) (shards: 8)
- rolling-upgrade--centos-8-db-node-a406b619-0-2 (34.138.143.31 | 10.142.0.20) (shards: 8)
- rolling-upgrade--centos-8-db-node-a406b619-0-1 (34.74.89.120 | 10.142.0.19) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: us-east1)

Test: `rolling-upgrade-centos8-test`
Test id: `a406b619-c7d1-4423-ade7-0323d9db42ae`
Test name: `enterprise-2022.2/rolling-upgrade/rolling-upgrade-centos8-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/217e97ea822e360e5d798aebce545dafe012217a/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

In upgrade test, after upgrade of the last node, cluster started to behave strangely:
1. Scylla logs started to log messages like `commitlog - Commitlog shutdown complete` - only, no other entries. Looks like all compactions/other activity stopped, but db was responding.
2. we hit data inconsistency: after deleting a row with QUORUM we selected this row and got a row instead of empty result:
```
< t:2022-09-20 17:24:14,498 f:common.py       l:1473 c:utils                p:DEBUG > Executing CQL 'DELETE FROM dense_cf_test WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 AND ip = '192.168.0.3'' ...
< t:2022-09-20 17:24:14,503 f:common.py       l:1473 c:utils                p:DEBUG > Executing CQL 'SELECT * FROM dense_cf_test WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 AND ip = '192.168.0.3'' ...
< t:2022-09-20 17:24:14,510 f:fill_db_data.py l:3255 c:sdcm.fill_db_data    p:ERROR > AssertionError: Lists differ: [[UUID('f47ac10b-58cc-4372-a567-0e02b2c3d479'), '192.168.0.3', None, 42]] != []
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor a406b619-c7d1-4423-ade7-0323d9db42ae`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a406b619-c7d1-4423-ade7-0323d9db42ae)
- Show all stored logs command: `$ hydra investigate show-logs a406b619-c7d1-4423-ade7-0323d9db42ae`

## Logs:
- **db-cluster-a406b619.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/db-cluster-a406b619.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/db-cluster-a406b619.tar.gz)
- **monitor-set-a406b619.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/monitor-set-a406b619.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/monitor-set-a406b619.tar.gz)
- **loader-set-a406b619.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/loader-set-a406b619.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/loader-set-a406b619.tar.gz)
- **sct-runner-a406b619.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/sct-runner-a406b619.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a406b619-c7d1-4423-ade7-0323d9db42ae/20220920_173555/sct-runner-a406b619.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/rolling-upgrade/job/rolling-upgrade-centos8-test/6/)

**Comment by michoecho** [comment]
> Scylla logs started to log messages like commitlog - Commitlog shutdown complete - only, no other entries. Looks like all compactions/other activity stopped, but db was responding.

Note that this is https://github.com/scylladb/scylladb/issues/11508. It's irrelevant.

**Comment by soyacz** [comment]
@roy There were no changes to that test recently.
I also tried to reproduce by running this scenario in a loop for few hours on my laptop but didn't reproduce.

**Comment by roydahan** [comment]
You can also check if it's related to upgrade, by adding this test as a step to the upgrade_test we have in dtest (in the same places we have the fill_db_data (i.e. before, while mixed, after).

**Comment by DoronArazii** [comment]
@kbr- please have a look

**Comment by kbr-** [comment]
@DoronArazii I'm swamped right now. Reassigning to my direct manager.

**Comment by roydahan** [comment]
@soyacz can you please try to reproduce it in dtest?

**Comment by DoronArazii** [comment]
@soyacz ^^

**Comment by mykaul** [comment]
> I was trying to reproduce it but didn't make it. I'm not aware of reproduction in any other test run. Maybe this was one-time issue related to something else (e.g. problems with GCE, as db-nodes logs were strangely silent).

Thanks @soyacz - can we close this issue until it reproduces again?

**Comment by soyacz** [comment]
I think we can close until reproduction.
