### ISSUE TITLE
scylla should automatically take snapshot of views when snapping the base table

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11612]
When the snapshot code was introduced in 2f2a4e83e0dcaf012e965e39af54e8ba89c65077, the intention of taking a snapshot of a table's views via the base table was already expressed as:
```c++
    if (cf_name.find(".") != sstring::npos) {
        throw std::invalid_argument("Cannot take a snapshot of a secondary index by itself. Run snapshot on the table that owns the index.");
    }
```

However, this was never implemented.
This wasn't found by tests, like the snapshot_test dtest since the condition above is too weak, allowing explicit snapshot of materialized views as they do not contain a dot in their name.

Commit aa127a2dbb8b4742fb456eff78420fbc1a4eaecb (backported to 4.6) fixed the logic to detect secondary indexes and views more accurately, preventing their snapshot via the api, but the logic to automatically take their snapshot when we take the base table's snapshot is still missing.

**Comment by bhalevy** [comment]
Cc @nyh @amnonh

**Comment by avikivity** [comment]
Not a regression, not backporting.
