### ISSUE TITLE
missing delimiter between partition key and clustering key in large data warning

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11620]
f3089bf3d1eda2be01e3af07fe1fde6fb08b62d5 added https://github.com/scylladb/scylladb/blob/f3089bf3d1eda2be01e3af07fe1fde6fb08b62d5/db/large_data_handler.cc#L64

That prints `pk_str` possibly followed, immediately, by the clustering key for large rows and cells.
Note that there is no delimiter between `pk_str` and `extra_path` so they are concatenated together.

**Comment by avikivity** [comment]
Cosmetic, not backporting.
