### ISSUE TITLE
Adjust docs/large-partition-table.rst to rows column

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11622]
Since a7511cf6000de0e2191e9ca18025f45bfdb04068 (scylla 5.0),
sstables containing partitions with too many rows are recorded in system.large_partitions.

Adjust the doc respectively.

**Comment by avikivity** [comment]
Not a bug, not backporting.

**Comment by bhalevy** [comment]
I see this as a bugvin the documentstion.
since it's versioned now it should be in sync with the code in each branch
