### ISSUE TITLE
create table taking > 7 minutes

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#11639]
## Installation details

Kernel Version: 5.10.0-17-cloud-amd64
Scylla version (or git commit hash): `5.0.3-20220907.b9a61c8e9` with build-id `7be266d2954825cdf843c744de04a0443a8f156c`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.0/scylla-x86_64-package-5.0.3.0.20220907.b9a61c8e9.tar.gz
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--debian-bullseye-db-node-9bcb2706-0-4 (35.231.205.57 | 10.142.0.142) (shards: 8)
- rolling-upgrade--debian-bullseye-db-node-9bcb2706-0-3 (34.148.206.119 | 10.142.0.141) (shards: 8)
- rolling-upgrade--debian-bullseye-db-node-9bcb2706-0-2 (34.138.39.119 | 10.142.0.140) (shards: 8)
- rolling-upgrade--debian-bullseye-db-node-9bcb2706-0-1 (35.231.204.238 | 10.142.0.139) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-11` (gce: us-east1)

Test: `rolling-upgrade-debian11-test`
Test id: `9bcb2706-6120-467f-a699-85261b70f011`
Test name: `scylla-5.1/rolling-upgrade/rolling-upgrade-debian11-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/801435dc23af9a7675a01e41286d77b3f20ea23a/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

**>>>>>>>**

rolling upgrade test failed by timeout, but it didn't even start to upgrade... it failed in a stage called `pre-test - prepare test keyspaces and tables`
went to investigate why, and i found that the tables we create, are taking from ~7 up to ~15 minutes:
```
Created tables for test "order_by_with_in_test: Check that order-by works with IN" in 517 seconds
Created tables for test "static_cf_test: Test static CF syntax" in 453 seconds
Created tables for test "static_cf_test_batch: Test static CF syntax with batch" in 453 seconds
Created tables for test "noncomposite_static_cf_test: Test non-composite static CF syntax" in 453 seconds
Created tables for test "noncomposite_static_cf_test_batch: Test non-composite static CF syntax with batch" in 451 seconds
Created tables for test "dynamic_cf_test: Test non-composite dynamic CF syntax" in 453 seconds
Created tables for test "dense_cf_test: Test composite "dense" CF syntax" in 452 seconds
Created tables for test "sparse_cf_test: Test composite "sparse" CF syntax" in 454 seconds
Created tables for test "limit_ranges_test: Validate LIMIT option for "range queries" in SELECT statements" in 451 seconds
Created tables for test "limit_multiget_test: issue ##2574 Validate LIMIT option for "multiget" in SELECT statements" in 452 seconds
Created tables for test "limit_sparse_test: Validate LIMIT option for sparse table in SELECT statements" in 454 seconds
Created tables for test "counters_test: Validate counter support" in 451 seconds
Created tables for test "indexed_with_eq_test: Check that you can query for an indexed column even with a key EQ clause" in 922 seconds
Created tables for test "mv_with_eq_test: Check that you can query from materialized view" in 903 seconds
Created tables for test "select_key_in_test: Query for KEY IN (...)" in 459 seconds
Created tables for test "exclusive_slice_test: Test SELECT respects inclusive and exclusive bounds" in 454 seconds
Created tables for test "in_clause_wide_rows_test: Check IN support for "wide rows" in SELECT statement" in 910 seconds
Created tables for test "order_by_test: Check ORDER BY support in SELECT statement" in 908 seconds
Created tables for test "more_order_by_test: More ORDER BY checks CASSANDRA-4160" in 907 seconds
Created tables for test "order_by_validation_test:  Check we don't allow order by on row key CASSANDRA-4246" in 456 seconds
Created tables for test "reversed_comparator_test" in 905 seconds
Created tables for test "null_support_test:  Test support for nulls on new versions" in 452 seconds
Created tables for test "nameless_index_test:  Test CREATE INDEX without name and validate the index can be dropped" in 920 seconds
Created tables for test "deletion_test: Test simple deletion and in particular check for CASSANDRA-4193 bug" in 902 seconds
Created tables for test "count_test" in 453 seconds
Created tables for test "batch_test" in 455 seconds
Created tables for test "table_options_test" in 452 seconds
Created tables for test "timestamp_and_ttl_test" in 455 seconds
Created tables for test "no_range_ghost_test" in 1361 seconds
Created tables for test "undefined_column_handling_test" in 453 seconds
Created tables for test "range_tombstones_test: Test deletion by 'composite prefix' (range tombstones)" in 453 seconds
Created tables for test "range_tombstones_compaction_test: Test deletion by 'composite prefix' (range tombstones) with compaction" in 453 seconds
Created tables for test "delete_row_test: Test deletion of rows" in 580 seconds
Created tables for test "range_query_2ndary_test: Test range queries with 2ndary indexes CASSANDRA-4257" in 924 seconds
Created tables for test "set test" in 578 seconds
```

so i went to the last build we have it passing, and the create table takes couple of seconds (the cluster started with 5.0.1-0.20220719.b177dacd3 with build-id 217f31634f8c8722cadcfe57ade8da58af05d415):
```
Created tables for test "order_by_with_in_test: Check that order-by works with IN" in 96 seconds
Created tables for test "static_cf_test: Test static CF syntax" in 30 seconds
Created tables for test "static_cf_test_batch: Test static CF syntax with batch" in 30 seconds
Created tables for test "noncomposite_static_cf_test: Test non-composite static CF syntax" in 31 seconds
Created tables for test "noncomposite_static_cf_test_batch: Test non-composite static CF syntax with batch" in 31 seconds
Created tables for test "dynamic_cf_test: Test non-composite dynamic CF syntax" in 30 seconds
Created tables for test "dense_cf_test: Test composite "dense" CF syntax" in 30 seconds
Created tables for test "sparse_cf_test: Test composite "sparse" CF syntax" in 29 seconds
Created tables for test "limit_ranges_test: Validate LIMIT option for "range queries" in SELECT statements" in 30 seconds
Created tables for test "limit_multiget_test: issue ##2574 Validate LIMIT option for "multiget" in SELECT statements" in 30 seconds
Created tables for test "limit_sparse_test: Validate LIMIT option for sparse table in SELECT statements" in 30 seconds
Created tables for test "counters_test: Validate counter support" in 30 seconds
Created tables for test "indexed_with_eq_test: Check that you can query for an indexed column even with a key EQ clause" in 76 seconds
Created tables for test "mv_with_eq_test: Check that you can query from materialized view" in 60 seconds
Created tables for test "select_key_in_test: Query for KEY IN (...)" in 30 seconds
Created tables for test "exclusive_slice_test: Test SELECT respects inclusive and exclusive bounds" in 29 seconds
Created tables for test "in_clause_wide_rows_test: Check IN support for "wide rows" in SELECT statement" in 61 seconds
Created tables for test "order_by_test: Check ORDER BY support in SELECT statement" in 59 seconds
Created tables for test "more_order_by_test: More ORDER BY checks CASSANDRA-4160" in 61 seconds
Created tables for test "order_by_validation_test:  Check we don't allow order by on row key CASSANDRA-4246" in 30 seconds
```

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9bcb2706-6120-467f-a699-85261b70f011`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9bcb2706-6120-467f-a699-85261b70f011)
- Show all stored logs command: `$ hydra investigate show-logs 9bcb2706-6120-467f-a699-85261b70f011`

## Logs:
[db.log](https://cloudius-jenkins-test.s3.amazonaws.com/9bcb2706-6120-467f-a699-85261b70f011/20220920_015533/db-cluster-9bcb2706.tar.gz)
[monitor.log](https://cloudius-jenkins-test.s3.amazonaws.com/9bcb2706-6120-467f-a699-85261b70f011/20220920_015533/monitor-set-9bcb2706.tar.gz)
[loader.log](https://cloudius-jenkins-test.s3.amazonaws.com/9bcb2706-6120-467f-a699-85261b70f011/20220920_015533/loader-set-9bcb2706.tar.gz)
[sct.log](https://cloudius-jenkins-test.s3.amazonaws.com/9bcb2706-6120-467f-a699-85261b70f011/20220920_015533/sct-runner-9bcb2706.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.1/job/rolling-upgrade/job/rolling-upgrade-debian11-test/7/)

**Comment by fgelcer** [comment]
this was found in the rolling upgrade job for 5.1 (but we didn't even reach this version, as we timed out in very early stage of the job, where we had 5.0.3 installed (against previous build that passed, that had 5.0.1 installed at this phase of the test).

**Comment by fgelcer** [comment]
exact same happened to another upgrade job (5.1, starting from the same 5.0.3):

## Installation details

Kernel Version: 4.18.0-408.el8.x86_64
Scylla version (or git commit hash): `5.0.3-20220907.b9a61c8e9` with build-id `7be266d2954825cdf843c744de04a0443a8f156c`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.0/scylla-x86_64-package-5.0.3.0.20220907.b9a61c8e9.tar.gz
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-8-db-node-ff9ef85a-0-4 (34.148.216.91 | 10.142.15.201) (shards: 8)
- rolling-upgrade--centos-8-db-node-ff9ef85a-0-3 (34.138.238.184 | 10.142.15.252) (shards: 8)
- rolling-upgrade--centos-8-db-node-ff9ef85a-0-2 (34.138.87.228 | 10.142.15.250) (shards: 8)
- rolling-upgrade--centos-8-db-node-ff9ef85a-0-1 (104.196.109.204 | 10.142.15.248) (shards: 8)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: us-east1)

Test: `rolling-upgrade-centos8-test`
Test id: `ff9ef85a-3e2b-42c5-8dc4-87d8b8fb5c5e`
Test name: `scylla-5.1/rolling-upgrade/rolling-upgrade-centos8-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/801435dc23af9a7675a01e41286d77b3f20ea23a/test-cases/upgrades/rolling-upgrade.yaml)

**Comment by fgelcer** [comment]
and another one:

## Installation details

Kernel Version: 3.10.0-1160.76.1.el7.x86_64
Scylla version (or git commit hash): `5.0.3-20220907.b9a61c8e9` with build-id `7be266d2954825cdf843c744de04a0443a8f156c`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.0/scylla-x86_64-package-5.0.3.0.20220907.b9a61c8e9.tar.gz
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-3c34b7b6-0-4 (34.73.106.42 | 10.142.0.138) (shards: 8)
- rolling-upgrade--centos-db-node-3c34b7b6-0-3 (34.75.26.123 | 10.142.0.136) (shards: 8)
- rolling-upgrade--centos-db-node-3c34b7b6-0-2 (34.74.25.97 | 10.142.0.135) (shards: 8)
- rolling-upgrade--centos-db-node-3c34b7b6-0-1 (34.139.109.2 | 10.142.0.134) (shards: 8)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: us-east1)

Test: `rolling-upgrade-centos7-test`
Test id: `3c34b7b6-9881-42f9-abd5-b4eca106e0d6`
Test name: `scylla-5.1/rolling-upgrade/rolling-upgrade-centos7-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/801435dc23af9a7675a01e41286d77b3f20ea23a/test-cases/upgrades/rolling-upgrade.yaml)

**Comment by avikivity** [comment]
Is this a regression? What's the last version known to work?

**Comment by fgelcer** [comment]
> Is this a regression? What's the last version known to work?

@avikivity , AFAICT it started happening recently... it could be something related to GCE, but it could be a regression introduced on one of the latest patches of 5.0, as i mentioned in here https://github.com/scylladb/scylladb/issues/11639#issuecomment-1257153152

**Comment by avikivity** [comment]
Let's also rerun on AWS (if it's easy).

**Comment by fgelcer** [comment]
> We are going to try to rerun with 5.0.1
> 
> ```
> [shlomi@shlomi-scylladb-com scylla]$ git shortlog scylla-5.0.1..scylla-5.0.3
> Avi Kivity (3):
>       Merge 'Backport: Fix map subscript crashes when map or subscript is null' from Nadav Har'El
>       Merge 'row_cache: Fix missing row if upper bound of population range is evicted and has adjacent dummy' from Tomasz Grabiec
>       Merge 'database: evict all inactive reads for table when detaching table' from Botond Dénes
> 
> Beni Peled (1):
>       release: prepare for 5.0.3
> 
> Benny Halevy (2):
>       sstables: time_series_sstable_set: insert: make exception safe
>       multishard_mutation_query: do_query: stop ctx if lookup_readers fails
> 
> Karol Baryła (1):
>       transport/server.cc: Return correct size of decompressed lz4 buffer
> 
> Nadav Har'El (5):
>       test/cql-pytest: improve tests for map subscripts and nulls
>       expressions: fix invalid dereference in map subscript evaluation
>       expressions: don't dereference invalid map subscript in filter
>       test/cql-pytest: reproducer for CONTAINS NULL bug
>       cross-tree: fix header file self-sufficiency
> 
> Piotr Grabowski (1):
>       type_json: support integers in scientific format
> 
> Piotr Sarna (1):
>       cql3: fix misleading error message for service level timeouts
> 
> Tomasz Grabiec (2):
>       memtable: Fix missing range tombstones during reads under ceratin rare conditions
>       test: memtable: Make failed_flush_prevents_writes() immune to background merging
> 
> Yaron Kaikov (1):
>       release: prepare for 5.0.2
> ```

running here from `5.0.1`:
https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/issue_11639_reproducers_and_staging/job/rolling-upgrade-debian11-test/3/

**Comment by fgelcer** [comment]
> Let's also rerun on AWS (if it's easy).

need to change in the test itself how to select the correct image, but it should not be hard... i will give it a try

**Comment by fgelcer** [comment]
> > Let's also rerun on AWS (if it's easy).
> 
> need to change in the test itself how to select the correct image, but it should not be hard... i will give it a try

running it in here:
https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/issue_11639_reproducers_and_staging/job/rolling-upgrade-aws-debian11-test/2/

**Comment by fgelcer** [comment]
> running here from 5.0.1:
> https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/issue_11639_reproducers_and_staging/job/rolling-upgrade-debian11-test/3/

it passed the pre-test phase, and failed for the repair, during mixed cluster (seems like #11459)

so, with confidence, there is a regression from 5.0.1 to 5.0.3

@avikivity @slivne

ps: i'm still checking the run on AWS, as it seems like many changes are needed in SCT to be able to run this test in there...

**Comment by fgelcer** [comment]
this issue is invalid... with this failed build we didn't have https://github.com/scylladb/scylla-cluster-tests/pull/5294 in it, so that is the reason for the failure.
once re-running with that patch applied, we are back to reasonable create table times.

**Comment by avikivity** [comment]
The patch says "revert x" without any explanation what was wrong with it and what we're losing by reverting it. How was anyone able to review it?

**Comment by fgelcer** [comment]
well, the issue is basically what is reported in this issue, but the issue was in SCT... although i don't see an issue in SCT for it, but the revert was sent straight away once we figured out the regression it caused...
