### ISSUE TITLE
"Enable Authorization" doc page references a wrong CL used by a 'cassandra' user

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#11633]
HEAD: 4c93a694b7928c20bdb86b77dea5c50cd71195a0

*Description*
The doc page tells that 'cassandra' user uses `EACH_QUORUM` CL while in fact it's `QUORUM`:

"The cassandra user is special. When you try to login with this username, it is required to usen EACH_QUORUM consistency level(CL) for replies."

```
db::consistency_level password_authenticator::consistency_for_user(std::string_view role_name) {
    if (role_name == DEFAULT_USER_NAME) {
        return db::consistency_level::QUORUM;
    }
    return db::consistency_level::LOCAL_ONE;
}
```

**Comment by vladzcloudius** [comment]
@annastuchlik FYI

**Comment by tzach** [comment]
Thanks @vladzcloudius 
in the future, please point to the relevant page when opening a doc issue:
https://docs.scylladb.com/stable/operating-scylla/security/enable-authorization.html

Even better, you can open an issue directly, or fix the issue, from the top right section of each page
![image](https://user-images.githubusercontent.com/170200/192129785-aa84fa57-ea3b-4002-abb1-1d597d02b279.png)
