### ISSUE TITLE
dtest test_resetlocalschema_api_issue_7811 AssertionError: Schema versions are different on the nodes

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11643]
This is seen consistently since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/93/testReport/junit/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_resetlocalschema_api_issue_7811/
scylla version 2a74a0086f89
scylladb/scylla-dtest@ef8537c64f22a9df05137369cc24212ee717f3cd

```
AssertionError: Schema versions are different on the nodes: 68fa8f59-d325-3290-b77c-37ab17181527: [127.0.83.1, 127.0.83.2] unexpectedly
assert 1 == 2
  +1
  -2
```

I'm not sure what could have introduced the regression.

last consistently passed with 6799e766ca95

```
scylla$ git log --oneline 6799e766ca95..2a74a0086f89
2a74a0086f docs: fix typos
cf30432715 Merge 'test: add a topology suite with Raft disabled' from Kamil Braun
43131976e9 updateable_value: Update comment about cross-shard copying
9b6fc553b4 db: commitlog: don't print INFO logs on shutdown
a24a8fd595 Update seastar submodule
ce7bb8b6d0 test.py: PythonTestSuite: sum default config params with user-provided ones
1661fe9f37 test: add a topology suite with Raft disabled
311806244d test: pylib: use Python dicts to manipulate `ScyllaServer` configuration
fd19825eaa test: pylib: store `config_options` in `ScyllaServer`
```

scylladb/scylla-dtest@250ea614e947429463538d749655782e13ba73e7

```
scylla-dtest$ git log --oneline git log --oneline 250ea614e9..ef8537c64f22
ef8537c6 secondary_indexes_test: Remove DTCS
```

**Comment by bhalevy** [comment]
@tgrabiec can you please look into this?
dtest #92 run is incomplete so the regression probably sneaked in in a previous merge so we need to bisect it.

**Comment by bhalevy** [comment]
I bisected this issue to a3356e866b093a8655cc9c3b3e6c8a68e3b3a6cc

Cc @fee-mendes @nyh

**Comment by bhalevy** [comment]
I think this change inadvertently fixed https://github.com/scylladb/scylladb/issues/7811
causing the test to fail.

Cc @raphaelsc @juliayakovlev

**Comment by fee-mendes** [comment]
> I bisected this issue to [a3356e8](https://github.com/scylladb/scylladb/commit/a3356e866b093a8655cc9c3b3e6c8a68e3b3a6cc)
> 
> Cc @fee-mendes @nyh

I can't reproduce it. Well, at least not an error. :-)

N1:
> ./tools/toolchain/dbuild ./build/dev/scylla --developer-mode 1 --listen-address 127.0.0.1 --workdir tmp1 --skip-wait-for-gossip-to-settle 1

N2: 
> ./tools/toolchain/dbuild ./build/dev/scylla --developer-mode 1 --workdir tmp2 --listen-address 127.0.0.2 --api-address 127.0.0.2 --seed-provider-parameters seeds=127.0.0.1 --rpc-address 127.0.0.2

`schema.cql`:
```cql
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 2};
CREATE TABLE ks.cf (pk int PRIMARY KEY) WITH compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_unit': 'NOPE'};
CREATE TABLE ks.cf (pk int PRIMARY KEY) WITH compaction = {'class': 'TimeWindowCompactionStrategy'};
```

Manual run:
> $ cqlsh 127.0.0.1 9042 -f schema.cql ; sleep 2; curl -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_proxy/schema_versions'; echo; sleep 2; curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://127.0.0.2:10000/storage_service/relocal_schema'; sleep 2; curl -X GET --header 'Accept: application/json' 'http://localhost:10000/storage_proxy/schema_versions'; echo
```
schema.cql:3:SyntaxException: Invalid window unit NOPE for compaction_window_unit

Warnings :
TimeWindowCompactionStrategy tables without a default_time_to_live may potentially introduce too many windows. Ensure that insert statements specify a TTL (via USING TTL), when inserting data to this table. The restrict_twcs_without_default_ttl configuration option can be changed to silence this warning or make it into an error

[{"key": "702bc2b8-763d-3f0b-bd90-0bbf8f1c1a08", "value": ["127.0.0.2","127.0.0.1"]}]
[{"key": "702bc2b8-763d-3f0b-bd90-0bbf8f1c1a08", "value": ["127.0.0.2","127.0.0.1"]}]
```

**Comment by fee-mendes** [comment]
> I think this change inadvertently fixed #7811 causing the test to fail.
> 
> Cc @raphaelsc @juliayakovlev

Yes and no. There are other compaction strategies which aren't verified.

**Comment by bhalevy** [comment]
I'll adjust the test to support both cases

**Comment by mykaul** [comment]
@bhalevy , @tgrabiec - did we get to a conclusion here? Should we re-open this, or is there a new issue to track for this?

**Comment by bhalevy** [comment]
> @bhalevy , @tgrabiec - did we get to a conclusion here? Should we re-open this, or is there a new issue to track for this?

There's a missing backport.
I pinged https://github.com/scylladb/scylladb/issues/14710#issuecomment-1867290095
Let's start with that.

**Comment by bhalevy** [comment]
> Lack of #14710 could explain it. relocal schema invokes schema merge path now, so if we corrupted schema so that the table is on disk but not in database object, relocal schema will fail the same way "create table" would fail.

Yes.  The test started failing right after bfd84014779c33bb9859c37daf30f2fc8ec818c4 was backported.

**Comment by mykaul** [comment]
Same in 5.2.14? - https://jenkins.scylladb.com/job/scylla-5.2/job/dtest-release/39/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_resetlocalschema_api_issue_7811_SizeTieredCompactionStrategy_/
