### ISSUE TITLE
`scylla_storage_proxy_coordinator_read_rate_limited` metric is not updated on coordinator node

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11651]
When per partition rate limit for read is set and non shard aware driver query hits coordinator node and we reached rate limit, `scylla_storage_proxy_coordinator_read_rate_limited` metric is not getting updated on this coordinator node.

Scylla version:  5.1.0-rc2

**Comment by denesb** [comment]
All live versions have this, removing label.
