### ISSUE TITLE
db::view::view_builder: resuming a view build step doesn't re-emit active range tombstones

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11668]
When pausing a build-step, we keep the reader but not the compactor. When resuming said build-step we create a new compactor and re-inject the partition start into the start of the fragment stream,  to correctly initialize the compactor into the state it was before it paused. This is not enough however since the v2 conversion, as in addition to the partition start, the range tombstone active at the time when the build was paused also has to be injected to re-activate the range tombstone. The lack of this can cause data resurrection.

**Comment by denesb** [comment]
Looks like we even loose the partition tombstone.

**Comment by denesb** [comment]
After thinking about a bit I think both issues have been present since the beginning: even with range tombstone (v1)  the compactor created after resume will not know about it and so will happily resurrect any shadowed rows.

**Comment by avikivity** [comment]
@denesb please backport.

**Comment by denesb** [comment]
Backported to 5.1.
To backport to 5.1 we need to backport https://github.com/scylladb/scylladb/issues/9482 as well.

**Comment by denesb** [comment]
Backported to 5.0 and 2021.1.

**Comment by avikivity** [comment]
Removing backport candidate label.
