### ISSUE TITLE
compatible_ring_position_or_view is not cheap to copy

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11669]
This class exists for one purpose only: to serve as glue code between `dht::ring_position` and `boost::icl::interval_map`. The latter requires that keys in its intervals are:
* default constructible
* copyable
* have standalone compare operations

For this reason we have to wrap `dht::ring_position` in a class, together with a schema to provide all this. This is     `compatible_ring_position`. There is one further requirement by code using the interval map: it wants to do lookups without copying the lookup key(s). To solve this, we came up with `compatible_ring_position_or_view` which is a union of a key or a key view + schema. As we recently found out, boost::icl copies its keys **a lot**. It seems to assume these keys are cheap to copy and carelessly copies them around even when iterating over the map. But `compatible_ring_position_or_view` is not cheap to copy as it copies a `dht::ring_position` which allocates, and it does that via an `std::optional` and `std::variant` to add insult to injury.

**Comment by avikivity** [comment]
Not a regression, not backporting.

**Comment by denesb** [comment]
(5.2+ already has it)

**Comment by denesb** [comment]
Backported to 2022.1 as scylladb/scylla-enterprise@9c766ffd32ffa114dfa48c8063269041bc8ef34f.
