### ISSUE TITLE
Table not created on node during restart in 5000 tables test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11675]
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc1-20220902.a9bc6d191031` with build-id `074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc1.0.20220902.a9bc6d191031.tar.gz
Cluster size: 1 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-5000-tables-scale-te-db-node-9432a26c-7 (176.34.94.226 | 10.4.1.154) (shards: -1)
- longevity-5000-tables-scale-te-db-node-9432a26c-6 (34.247.69.21 | 10.4.1.147) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-5 (52.48.210.162 | 10.4.3.131) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-4 (52.50.144.231 | 10.4.0.121) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-3 (54.154.228.197 | 10.4.2.4) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-2 (54.75.40.247 | 10.4.3.250) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-1 (52.51.92.89 | 10.4.3.123) (shards: 30)

OS / Image: `ami-0492fd8e302e5af45` (aws: eu-west-1)

Test: `scale-5000-tables-test`
Test id: `9432a26c-4f6a-472e-82fc-12eda02a1916`
Test name: `enterprise-2022.2/scale/scale-5000-tables-test`
Test config file(s):

- [longevity-5000-tables.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f275e01e52e838da724c69e0416d2da8078b514/test-cases/scale/longevity-5000-tables.yaml)

## Issue description

In 5000 tables test (5k tables already created), during one node being restarted (`disrupt_stop_start_scylla_server` nemesis on node `longevity-5000-tables-scale-te-db-node-9432a26c-5`) another table was created. After restart completed it looks that schema was not propagated to this node (no sign of it in logs of that node) and later it resulted in c-s to fail due:
```
Stress command completed with bad status 1: java.lang.RuntimeException: Unable to find table feeds.table5000
```

During startup of this node, many reactor stalls were present. Decoded:
[5000-tables-bottom-up-decoded.log](https://github.com/scylladb/scylladb/files/9684602/5000-tables-bottom-up-decoded.log)
[5000-tables-top-down-decoded.log](https://github.com/scylladb/scylladb/files/9684604/5000-tables-top-down-decoded.log)

We see this error for the first time in this test, but we cannot say if this is a regression - this specific nemesis and perfect timing of creating table during node restart wasn't run before in this test.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9432a26c-4f6a-472e-82fc-12eda02a1916`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9432a26c-4f6a-472e-82fc-12eda02a1916)
- Show all stored logs command: `$ hydra investigate show-logs 9432a26c-4f6a-472e-82fc-12eda02a1916`

## Logs:
- **db-cluster-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/db-cluster-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/db-cluster-9432a26c.tar.gz)
- **monitor-set-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/monitor-set-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/monitor-set-9432a26c.tar.gz)
- **loader-set-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/loader-set-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/loader-set-9432a26c.tar.gz)
- **sct-runner-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/sct-runner-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/sct-runner-9432a26c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/scale/job/scale-5000-tables-test/5/)

**Comment by slivne** [comment]
We discussed this on the call
 - we need to check if the schema got in synch at all ? 
 - if it did how long it took for it to get in synch ?

**Comment by DoronArazii** [comment]
@eliransin this is a 'schema changes' case - do you want me to push it to 5.2?

/Cc @roydahan @avikivity

**Comment by mykaul** [comment]
> @eliransin this is a 'schema changes' case - do you want me to push it to 5.2?
> 
> /Cc @roydahan @avikivity

@eliransin ?

**Comment by eliransin** [comment]
> > @eliransin this is a 'schema changes' case - do you want me to push it to 5.2?
> > /Cc @roydahan @avikivity
> 
> @eliransin ?

yes

**Comment by mykaul** [comment]
I assume need reproduction WITH Raft enabled, or closed?
@eliransin ?

**Comment by DoronArazii** [comment]
@eliransin / @kostja ^^

**Comment by kostja** [comment]
@soyacz I second @mykaul's comment, please re-run with consistent-cluster-management.

**Comment by kostja** [comment]
The enablement happens in scylla.yaml. The commit was backported. Please double check that consistent_cluster_management: true is set.

I also recommend setting force-schema-commit-log option, it improves DDL performance significantly, and going forward we will be requiring it on.

**Comment by DoronArazii** [comment]
@soyacz any results here?

**Comment by soyacz** [comment]
> @soyacz any results here?

I did test on 2023.1.0~rc1 - error did not reproduce.

**Comment by mykaul** [comment]
> > @soyacz any results here?
> 
> I did test on 2023.1.0~rc1 - error did not reproduce.

Woot! Closing for the time being - please re-open if it reproduces.
