### ISSUE TITLE
API, to return list of sstable names containing a given partition key, is not considering all sstables

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#11681]
After commit 1e7a444a8b0, replica::table::get_sstable_set() is only returning SSTable in main set, meaning SSTables in maintenance set aren't being considered. If a tool relies on this API for extracting data / metadata from files containing pkey K, it's going to miss relevant files that are temporarily stored in the maintenance set.

**Comment by avikivity** [comment]
Backported to 4.6, 5.0, 5.1.

**Comment by raphaelsc** [comment]
> > Backported to 4.6, 5.0, 5.1.
> 
> Dequeued backports, they break the start and stop node smoke tests with segfault:
> 
> ```
> [Backtrace #0]
> void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
>  (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:760
>  (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:790
> seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:802
>  (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3667
>  (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3648
>  (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3644
> wasmtime_runtime::traphandlers::unix::trap_handler at wasmtime_runtime.9xv9ixev-cgu.15:?
> ?? ??:0
> std::__uniq_ptr_impl<sstables::sstable_set_impl, std::default_delete<sstables::sstable_set_impl> >::_M_ptr() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unique_ptr.h:173
>  (inlined by) std::unique_ptr<sstables::sstable_set_impl, std::default_delete<sstables::sstable_set_impl> >::get() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unique_ptr.h:422
>  (inlined by) std::unique_ptr<sstables::sstable_set_impl, std::default_delete<sstables::sstable_set_impl> >::operator->() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/unique_ptr.h:416
>  (inlined by) sstables::sstable_set::all() const at ./sstables/sstable_set.cc:140
>  (inlined by) operator()<seastar::lw_shared_ptr<sstables::sstable_set> > at ./sstables/sstable_set.cc:967
>  (inlined by) __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > > std::__partition<__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > >, sstables::compound_sstable_set::all() const::$_12>(__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > >, __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > >, sstables::compound_sstable_set::all() const::$_12, std::bidirectional_iterator_tag) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:1495
>  (inlined by) __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > > std::partition<__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > >, sstables::compound_sstable_set::all() const::$_12>(__gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > >, __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable_set>*, std::vector<seastar::lw_shared_ptr<sstables::sstable_set>, std::allocator<seastar::lw_shared_ptr<sstables::sstable_set> > > >, sstables::compound_sstable_set::all() const::$_12) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_algo.h:4654
>  (inlined by) sstables::compound_sstable_set::all() const at ./sstables/sstable_set.cc:967
> sstables::sstable_set::all() const at ./sstables/sstable_set.cc:140
> sstables::get_uncompacting_sstables(compaction::table_state const&, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > >) at ./compaction/compaction.cc:186
>  (inlined by) sstables::get_fully_expired_sstables(compaction::table_state const&, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > const&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) at ./compaction/compaction.cc:1763
> replica::table::table_state::fully_expired_sstables(std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable> > > const&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) const at ./replica/table.cc:2478
> sstables::compaction::setup() at ./compaction/compaction.cc:626
> operator() at ./compaction/compaction.cc:1593
>  (inlined by) sstables::compaction_result std::__invoke_impl<sstables::compaction_result, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(std::__invoke_other, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
>  (inlined by) std::__invoke_result<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>::type std::__invoke<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
>  (inlined by) decltype(auto) std::__apply_impl<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1, std::tuple<>>(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&, std::tuple<>&&, std::integer_sequence<unsigned long>) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1858
>  (inlined by) decltype(auto) std::apply<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1, std::tuple<> >(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&, std::tuple<>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/tuple:1869
>  (inlined by) seastar::future<sstables::compaction_result> seastar::futurize<sstables::compaction_result>::apply<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&, std::tuple<>&&) at ././seastar/include/seastar/core/future.hh:2118
>  (inlined by) operator() at ././seastar/include/seastar/core/thread.hh:258
>  (inlined by) seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1>(seastar::thread_attributes, sstables::compaction::run(std::unique_ptr<sstables::compaction, std::default_delete<sstables::compaction> >)::$_1&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././seastar/include/seastar/util/noncopyable_function.hh:124
> seastar::noncopyable_function<void ()>::operator()() const at ./build/release/seastar/./seastar/include/seastar/util/noncopyable_function.hh:209
>  (inlined by) seastar::thread_context::main() at ./build/release/seastar/./seastar/src/core/thread.cc:299
> ```
> 
> @raphaelsc please look into it, see the 5.1 job for example: https://jenkins.scylladb.com/job/scylla-5.1/job/next/55/

we need to backport https://github.com/scylladb/scylladb/commit/eddf32b94c96b7a96744f62a46aacaeca5fef28f too, which is contained in the series merged. No issue was opened for it, because copy of compound_set was not stressed before this fix.

**Comment by denesb** [comment]
> we need to backport [eddf32b](https://github.com/scylladb/scylladb/commit/eddf32b94c96b7a96744f62a46aacaeca5fef28f) too, which is contained in the series merged. No issue was opened for it, because copy of compound_set was not stressed before this fix.

Please create an issue for it, for backport posterity.

**Comment by mykaul** [comment]
I could not find a backport of https://github.com/scylladb/scylladb/commit/eddf32b94c96b7a96744f62a46aacaeca5fef28f in branch-5.1 - is it still needed?

**Comment by denesb** [comment]
All live versions have this, removing label.
