### ISSUE TITLE
Failure of `remove_from_group0` in `storage_service::removenode` is not handled correctly

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#11723]
This is how `storage_service::removenode` looks like:
```cpp
            try {

                // ... start removenode, do steps 1 through 5 ...

                // Step 6: Finish
                req.cmd = node_ops_cmd::removenode_done;
                parallel_for_each(nodes, [&ss, &req, uuid] (const gms::inet_address& node) {
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("removenode[{}]: Got done response from node={}", uuid, node);
                        return make_ready_future<>();
                    });
                }).get();

                slogger.info("removenode[{}]: removing node {} from group 0", uuid, endpoint);
                assert(ss._group0);
                ss._group0->remove_from_group0(endpoint).get();
                slogger.info("removenode[{}]: node {} removed from group 0", uuid, endpoint);

                slogger.info("removenode[{}]: Finished removenode operation, removing node={}, sync_nodes={}, ignore_nodes={}", uuid, endpoint, nodes, ignore_nodes);
            } catch (...) {
                // we need to revert the effect of prepare verb the removenode ops is failed
                req.cmd = node_ops_cmd::removenode_abort;
                parallel_for_each(nodes, [&ss, &req, &nodes_unknown_verb, &nodes_down, uuid] (const gms::inet_address& node) {
                    if (nodes_unknown_verb.contains(node) || nodes_down.contains(node)) {
                        // No need to revert previous prepare cmd for those who do not apply prepare cmd.
                        return make_ready_future<>();
                    }
                    return ss._messaging.local().send_node_ops_cmd(netw::msg_addr(node), req).then([uuid, node] (node_ops_cmd_response resp) {
                        slogger.debug("removenode[{}]: Got abort response from node={}", uuid, node);
                    });
                }).get();
                slogger.info("removenode[{}]: Aborted removenode operation, removing node={}, sync_nodes={}, ignore_nodes={}", uuid, endpoint, nodes, ignore_nodes);
                throw;
            }
```

As we can see, the `remove_from_group0` step happens after the "Finish" step.
If `remove_from_group0` throws an exception, the exception handler will send a `node_ops_cmd::removenode_abort` message to other nodes. The other nodes will have already cleared their knowledge about this operation by now (due to the Finish step) and they will reject the message.

`remove_from_group0` should either happen before the Finish step or it should be moved out of the try...catch.

EDIT: design doc for fixing the problems with error handling in `removenode` and `decommission`:
https://docs.google.com/document/d/1Gvy2_ZezCa2XY5li05umOznIwjvIYFGmYpeZQg5RbZM/

**Comment by kbr-** [comment]
Ref: https://github.com/scylladb/scylladb/issues/11721

**Comment by kostja** [comment]
@alecco I think this is best testing by injecting a failure in htis place, and then either trying to go forward (finish the operation) or backward (remove the dead node). Assigning to you for adding a test, when we have a test we can decide what to do wit the bug.

**Comment by kbr-** [comment]
> or backward (remove the dead node)

Going backward would mean aborting the removal (so we keep the dead node in the cluster).

But really, there is no way to correctly fix this without Raft-based topology changes.

There are two crucial steps in the removal procedure: removing the tokens (`storage_service::excise`) and removing the group 0 member `raft_group::remove_from_group0`. These two steps must be done atomically. We cannot do one of them and then fail. We'll either end up with a (voting) member of group 0 that doesn't have tokens (this is what's happening right now), or with a member of the token ring that's not a member of group 0 (probably even worse).

A Raft-based fault-tolerant topology coordinator would ensure that both steps are finished if one of them is finished. Right now this simply cannot be done.

cc @gleb-cloudius

**Comment by kbr-** [comment]
> We'll either end up with a (voting) member of group 0 that doesn't have tokens (this is what's happening right now)

Perhaps we could improve the situation at least by starting `removenode` with another step: turn the node into a non-voter.

That would be at least symmetric to the bootstrap procedure, which starts by joining group0 as a non-voter and ends with becoming a voter.

**Comment by kostja** [comment]
I think it's best if we provide some built-in stored procedures to handle this. We could revitalize the patch which adds system stored procedure support to Scylla.

**Comment by kostja** [comment]
Now that we have a test for it, we can take this ticket into implementation.

**Comment by kbr-** [comment]
> I think it's best if we provide some built-in stored procedures to handle this. We could revitalize the patch which adds system stored procedure support to Scylla.

Or we could use the mechanism used to implement every other API: REST endpoints.

It would be awkward to use stored procedures just for this one thing and REST endpoints for everything else.

**Comment by kbr-** [comment]
As discusses in https://github.com/scylladb/scylladb/pull/12172#discussion_r1038114834
fixing this should also modify the code to throw an error when we fail to obtain the Raft ID instead of continuing.

**Comment by kbr-** [comment]
> fixing this should also modify the code to throw an error when we fail to obtain the Raft ID instead of continuing.

In fact, with https://github.com/scylladb/scylladb/issues/12204, we'll be able to completely get rid of this reverse-translation thing. We'll be able to pass the Raft ID of removed server directly as a parameter to `remove_from_group0`, because it will be easily obtainable at the call site:
- during replace, we already obtain the Host ID of replaced node and it must be present for us to proceed (existing check; replace operation will already fail if we can't obtain the Host ID). Furthermore, we plan to improve the situation even further, by deprecating the `replace_address_first_boot` parameter, replace it with `replace_host_first_boot` or something like that (which is a Host ID, not an IP address)
- during node remove, we actually already get the Host ID from the API. Currently we translate it to IP, then from IP to Raft ID using the address map. With Host ID and Raft ID merged, we just pass that Host ID. Nice.

cc @tgrabiec

**Comment by kbr-scylla** [comment]
Test case presenting the issue:
https://github.com/kbr-scylla/scylladb/commit/4a879fe042197c133b5e2305e9456a92e799d0b5

**Comment by mykaul** [comment]
Don't think anything Raft related needs to be backported to releases earlier than 5.2.
