### ISSUE TITLE
docs: misformat links to Scylla University from Data Manipulation page

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11724]
I would like to report an issue in page https://docs.scylladb.com/master/cql/dml

### Problem

Two links to Scylla U are not properly formated

You can read more about TTL in the [documentation](https://docs.scylladb.com/stable/cql/time-to-live.html) and also in this Scylla University lesson <https://university.scylladb.com/courses/data-modeling/lessons/advanced-data-modeling/topic/expiring-data-with-ttl-time-to-live/>.

which look like
![image](https://user-images.githubusercontent.com/170200/194051977-856379d5-deb3-48ff-b428-1d2fe65bfc96.png)

and

A TTL of null is equivalent to inserting with a TTL of 0. You can read more about TTL in the [documentation](https://docs.scylladb.com/stable/cql/time-to-live.html) and also in this Scylla University lesson <https://university.scylladb.com/courses/data-modeling/lessons/advanced-data-modeling/topic/expiring-data-with-ttl-time-to-live/>.

Problem intreduced in 
https://github.com/scylladb/scylla-docs/commit/7fa136cee4330b9f7cd8545842395e646908b486

###  Suggest a fix

Fix the link format by adding a `_` suffix as defined here https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#external-links

**Comment by annastuchlik** [comment]
This issue has been fixed with https://github.com/scylladb/scylladb/pull/11876.
