### ISSUE TITLE
Docs: "Apache Cassandra Query Language (CQL)" on page "Using ScyllaDB" leads to a 404

### ISSUE THREAD

**Issue by half0wl** [scylladb/scylladb#11753]
I would like to report an issue in page https://cloud.docs.scylladb.com/stable/learn-more/index.html

### Problem

Clicking on "Apache Cassandra Query Language (CQL)" leads to https://docs.scylladb.com/using-scylla/cql/ which 404s.

###  Suggest a fix

Update the link to a non-404 destination (looks like that should lead to https://docs.scylladb.com/stable/cql/index.html?)

**Comment by annastuchlik** [comment]
@half0wl Thank you for reporting the problem. It is now fixed.
