### ISSUE TITLE
test.py: topology test files with multiple tests take longer and longer to run with `--repeat`

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#11757]
When running, for example,
```
test.py --mode dev test_topology --repeat 100
```

the subsequent repeats of `test_topology.py` will take longer and longer - and eventually start timing out.

This happens due to how the test framework is handing out clusters to tests (using `Pool`). For example: after the first test of `test_topology.1` (the first repeat of `test_topology`)  finishes, we won't immediately lease a cluster to the second test in `test_topology.1` - because there are other repeats (`test_topology.2` and so on) which started in the meantime and are also competing for the clusters in the `Pool`. The more repeats managed to start (a test file starts once it manages to lease the first cluster), the longer it will take for each of them to run - because they all compete for the `Pool` clusters, and `Pool` serves them in a round-robin fashion (I think).

cc @kostja

**Comment by kostja** [comment]
The clusters are marked dirty in topology tests. So they are not returned to the pool. The problem apparently they are not destroyed (since recently) to avoid ip address reuse. WDYT?

**Comment by kbr-** [comment]
It doesn't matter if they are marked dirty or not, returned to the pool or not.
Whether the Pool creates a new cluster or gives out an existing one doesn't matter. The problem is in the **order** of how it handles requests.

If you imagine the sequence of events of how clusters are handled out, and consider the test file run assigned to each event - the problem is that the intervals between each occurence of a given test file run are growing:
```
run 1, run 2, run 3, run 4, run 5, run 6, run 7, run 8, run 1, run 2, run 3, run 4, run 5, run 6, run 7, run 8, run 9, run 10, run 11, run 12, run 1, run 2, run 3, run 4, run 5, run 6, run 7, run 8, run 9, run 10, run 11, run 12, run 13, run 14, run 15, run 16
```

something like this.

**Comment by kbr-** [comment]
Instead, existing runs should be prioritized (again assuming pool size == 4; suppose there are 3 test cases in the file):
```
run 1, run 2, run 3, run 4, run 1, run 2, run 3, run 4, run 1, run 2, run 3, run 4, run 5, run 6, run 7, run 8, ...
```

in this sequence we managed to run all tests in the first 4 runs before starting the first test in run 5 and so on.

**Comment by kostja** [comment]
The way test.py does it is that it builds a list of cases. With --repeat, it creates more object. Each object is independent. Then it begins running the tests in the order they are added to the list. Why should the order of tests have anything to do with the pool?

**Comment by kbr-** [comment]
test.py builds a list of **test files**. Each file contains multiple tests (test cases). The test file leases a single cluster at the beginning, then passes it to the first test case. Then each subsequent test case attempts to lease a cluster for itself.

Initially we manage to lease 4 clusters, one to each test file, so we start 4 runs of the test file, let's call them 1, 2, 3, 4. (`test_topology.X` for `X = 1,2,3,4`). Runs 5, 6, ... haven't started their test cases yet because they are waiting for an available cluster. But they **are waiting**, because test.py has already invoked them.

Eventually the first test case in run `1` finishes, and the cluster is leased to run `5`, so run `5` starts the first test case. Then first test case in run `2` finishes, cluster is leased to run `6` and so on until run `8`.

Then the first test case in run `5` finishes. The cluster is leased to the second test case in run `1`, apparently (or it may be leased to run `9` - but for some reason, apparently from my experiments, it gives it to run `1`, which is better for us because it allows run `1` to finish faster). And so on, until the second test cases of runs `2,3,4` have their clusters.

When the second test case of run `1` finishes, the cluster is leased to the second test case of run `5`, and so on `2`->`6`, ..., `4`->`8`.

When the second test case of run `5` finishes, the cluster is leased to run `9`.

There is a pattern here: each run takes longer and longer to get a cluster for its next test case, because in the meantime more runs have started waiting and they are all competing.

Instead of this, when the first test case of run `1` finishes, the cluster should not be leased to the first test case of run `5`, but it should be leased to the second test case of run `1`.


(Note: I'm not 100% sure this is the exact pattern, but what I am 100% sure is that earlier runs are waiting for later runs to finish and return their clusters; the more runs we have, the longer we need to wait; and runs that started later have to wait longer)

**Comment by kostja** [comment]
Indeed, this changed with leasing clsuters per test case, not per test file (my mental model is deprecated after alejo's chagnes). In any case it shouldn't matter unless we have a quadratic algorithm sitting somewhere in there. Its also fine to not return clusters back to the pool if they are leased by a file (i.e. return to leasing the cluster to a file, not to a case).

**Comment by kbr-** [comment]
I think we should go all the way so that test.py operates on test (case) level, not on test file level.

It would solve this problem: we would not longer care about how long a single test file runs, only about how long a test case runs.

It would also solve a different problem: it would give us the ability to run test cases from a single file concurrently. Right now, even though we have 4 clusters in the pool, a single run of test_topology will run its test cases sequentially.

**Comment by kostja** [comment]
The actual problem is that we start tracking the test timeout time before leasing the cluster, we should do it after the cluster is leased.

**Comment by kbr-scylla** [comment]
> The actual problem is that we start tracking the test timeout time before leasing the cluster, we should do it after the cluster is leased.

I disagree.

There must be some timeout on waiting for a cluster to start, we cannot wait forever. This is the timeout that we're hitting. And this time to wait is **unbounded**, so no matter what timeout we choose, we'll hit it with large enough `--repeat`

**Comment by kostja** [comment]
> > The actual problem is that we start tracking the test timeout time before leasing the cluster, we should do it after the cluster is leased.
> 
> I disagree.
> 
> There must be some timeout on waiting for a cluster to start, we cannot wait forever. This is the timeout that we're hitting. And this time to wait is **unbounded**, so no matter what timeout we choose, we'll hit it with large enough `--repeat`

Fine, there must be some timeout on it, but it's not related to a specific test. It'd be reasonable to have a timeout on the entire run as well.
