### ISSUE TITLE
docs: GitHub links on page "Using ScyllaDB" leads to a invalid repository

### ISSUE THREAD

**Issue by half0wl** [scylladb/scylladb#11752]
I would like to report an issue in page https://cloud.docs.scylladb.com/stable/learn-more/index.html

### Problem

Clicking on "Create an issue" or "Edit this page" leads to `https://github.com/scylladb/scylla-cloud-doc/issues/new?<...snip>` which is an invalid repository.

###  Suggest a fix

Update the links to point to this repository.

**Comment by tzach** [comment]
The repo is private, so it look like invalid to you.
In any case, we will fix this. Thanks for thre report!

**Comment by annastuchlik** [comment]
@half0wl Thank you for reporting the problem. It is now fixed.
