### ISSUE TITLE
Service Levels: Node crashes during parsing of service level creation with unreserved keywords

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#11774]
There is a coding mistake making service level queries to crash when involving a service level name which is an
unreserved word.
Unreserved words are cql type names such as `int` or `text` and the word `empty`
The bug is due to trying to consume an already consumed text in the parser.
Affected branches - All service level supporting branches 4.6,5.0,5.1 and master itself.
An example for a such a query is:
`CREATE SERVICE LEVEL empty WITH timeout=3;`

**Comment by avikivity** [comment]
Backported to 4.6, 5.0, 5.1.
