### ISSUE TITLE
Decommission can fail due to concurrent fiber dropping RPC connections

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#11780]
The decommission operation sends a bunch of RPCs and opens RPC streams. These remote call may fail due to connection dropping by concurrently running fiber.

This concurrent dropping is caused by `storage_service::handle_state_normal`. Note that even if the operator first checks that every node is considered to be in NORMAL state from the POV of the decommissioned node before starting the operation, it does not guarantee that `handle_state_normal` has finished on this node - it may still be running.

`handle_state_normal` contains this call:
```cpp
    // Send joined notification only when this node was not a member prior to this
    if (!is_member) {
        co_await notify_joined(endpoint);
    }
```

`notify_joined` does:
```cpp
    co_await container().invoke_on_all([endpoint] (auto&& ss) {
        ss._messaging.local().remove_rpc_client_with_ignored_topology(netw::msg_addr{endpoint, 0});
        return ss._lifecycle_notifier.notify_joined(endpoint);
    });
```

and `remove_rpc_client_with_ignored_topology` drops all connections to this node, causing a concurrently running decommission to fail.

**Comment by kbr-** [comment]
cc @asias @xemul

**Comment by kbr-** [comment]
This causes `test_topology.test_decommission_node_add_column` to fail.

**Comment by kbr-** [comment]
cc @gleb-cloudius

**Comment by xemul** [comment]
> ... and remove_rpc_client_with_ignored_topology drops all connections to this node ...

not _all_, but only those whose location was unknown at the time of the fist RPC verb in this verb-group was sent to

**Comment by kbr-** [comment]
I wonder if instead of closing the client immediately, we could put it in the background and drain all existing RPCs.

The drain could potentially be long though, e.g. RPC streams could be opened. And we'd need to ensure that the drains are interrupted when we close messaging service so we don't prevent shutdowns.

**Comment by avikivity** [comment]
I'd like to consider for backport. Is it a regression? How likely it is to happen in real life?

**Comment by kbr-** [comment]
The RPC clients dropping code was introduced in 7bdad47de2f5ba4a0da220aff13e4c510782ee3e, which didn't make it into 5.1.

Very unlikely to happen in real life, to reproduce it you have to issue decommission **immediately** after bootstrapping a node, and even then there's a chance you won't reproduce.
