### ISSUE TITLE
View building fail to move staging SSTables to base dir because generations are taken

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#11789]
Manifests in the following scenario:

1) staging directory is reshaped on boot
2) reshape picks a generation for output sstable without awareness of generations in base dir. that's because staging files are populated first to underlying table
3) now a sstable in staging and base dir share the same generation
4) staging files are registered for view building
5) view building completes but fail to move sstables from staging which generation are already used by another sstables in the base dir.

**Comment by bhalevy** [comment]
Note: please hold off any backports of https://github.com/scylladb/scylladb/commit/ba6186a47fbae2b88af5e049b214b2148a7c55ca since it appears to cause #11843.

https://github.com/scylladb/scylladb/pull/11795 should be preferred instead.
