### ISSUE TITLE
distributed_loader should first detect the highest generation in a table before allowing new sstables to be created in it

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11793]
This is the root cause for https://github.com/scylladb/scylladb/issues/11789
See also discussion in https://github.com/scylladb/scylladb/pull/11790

Currently, we call `populate_column_family` for each sub-directory in the table:
https://github.com/scylladb/scylladb/blob/4ff204c028ded45e33e7d53687de2a6f43b069dc/replica/distributed_loader.cc#L563-L565

and the latter calls
https://github.com/scylladb/scylladb/blob/4ff204c028ded45e33e7d53687de2a6f43b069dc/replica/distributed_loader.cc#L503
and
https://github.com/scylladb/scylladb/blob/4ff204c028ded45e33e7d53687de2a6f43b069dc/replica/distributed_loader.cc#L523

that might create new sstables, while
https://github.com/scylladb/scylladb/blob/4ff204c028ded45e33e7d53687de2a6f43b069dc/replica/distributed_loader.cc#L499
has only been called locally in the sub-directory, so the actual sstable with the highest generation might not have been detected yet.

**Comment by bhalevy** [comment]
Cc @raphaelsc

**Comment by denesb** [comment]
This is a little bit on the large size but it had some time to stew in master, so I backported it.
Backport to 5.1 was clean but there are conflicts in 5.0 around coroutines. Please prepare a backport PR for 5.0.

**Comment by bhalevy** [comment]
Backport was done, removing label.
