### ISSUE TITLE
test_smallest_ip_join_late dtest: Startup failed: std::runtime_error (Node 127.0.*.2 has gossip status=UNKNOWN

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11799]
Regression seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/115/testReport/junit/bootstrap_test/TestBootstrap/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_smallest_ip_join_late_2/
Scylla version f673d0abbe75
```
failed on teardown with "AssertionError: Unexpected errors found: [('node3', ['ERROR 2022-10-13 03:33:58,195 [shard 0] init - Startup failed: std::runtime_error (Node 127.0.8.2 has gossip status=UNKNOWN. Try fixing it before adding new node to the cluster.)'])]"
```

@asias please look into this

**Comment by bhalevy** [comment]
@asias git bisect points to 810b424a8c3612a0a3419cd556839596e381829a

**Comment by asias** [comment]
The test is problematic. It tested starting multiple nodes in parallel which we do not support. The patch https://github.com/scylladb/scylladb/commit/810b424a8c3612a0a3419cd556839596e381829a makes scylla detect such and reported it correctly. I think we should drop the test. 

```
        # only start node2 and node3, node2 will be the real `first node`
        node2.start(wait_for_binary_proto=False, wait_other_notice=False)

        node2.watch_log_for(exprs=skip_shadow_round_msg)
        logger.info("Verified shadow round doesn't start on node2")

        node3.start(wait_for_binary_proto=False, wait_other_notice=False)
```

**Comment by bhalevy** [comment]
> The test is problematic. It tested starting multiple nodes in parallel which we do not support. The patch [810b424](https://github.com/scylladb/scylladb/commit/810b424a8c3612a0a3419cd556839596e381829a) makes scylla detect such and reported it correctly. I think we should drop the test.
> 
> ```
>         # only start node2 and node3, node2 will be the real `first node`
>         node2.start(wait_for_binary_proto=False, wait_other_notice=False)
> 
>         node2.watch_log_for(exprs=skip_shadow_round_msg)
>         logger.info("Verified shadow round doesn't start on node2")
> 
>         node3.start(wait_for_binary_proto=False, wait_other_notice=False)
> ```

@roydahan are you ok with dropping this test based on @asias analysis?

**Comment by roydahan** [comment]
@asias why not just adjusting the test, so node3 will join after node2?
Does it defeat the test purpose?

**Comment by asias** [comment]
> @asias why not just adjusting the test, so node3 will join after node2? Does it defeat the test purpose?

The node would fail like this now days.

Node 2:
```
ERROR 2022-10-20 16:09:36,114 [shard 0] init - Startup failed: std::runtime_error (Failed to learn about other nodes' tokens during bootstrap. Make sure that:
 - the node can contact other nodes in the cluster,
 - the `ring_delay` parameter is large enough (the 30s default should be enough for small-to-middle-sized clusters),
 - a node with this IP didn't recently leave the cluster. If it did, wait for some time first (the IP is quarantined),
and retry the bootstrap.)
```

Node 3:
```
ERROR 2022-10-20 16:09:01,543 [shard 0] init - Startup failed: std::runtime_error (Node 127.0.29.2 has gossip status=UNKNOWN. Try fixing it before adding new node to the cluster.)
```

@roydahan Can assign someone from you team to modify the test? 

Also the setting below is useless and can be dropped. 

```
        # node1 has the smallest ip, but it's started later, expect bootstrap
        # even the option isn't enabled
        node1.set_configuration_options(values={'auto_bootstrap': False})
        # node2: normal test
        node2.set_configuration_options(values={'auto_bootstrap': True})
        # node3: auto_bootstrap option will be ignored even it's set to False
        node3.set_configuration_options(values={'auto_bootstrap': False})
```

**Comment by bhalevy** [comment]
ping @roydahan

**Comment by roydahan** [comment]
Re-reading the test, It doesn't make sense to change it since it's testing something very specific.
I think we can drop the test.

**Comment by bhalevy** [comment]
> Re-reading the test, It doesn't make sense to change it since it's testing something very specific. I think we can drop the test.

So let's do that.

**Comment by bhalevy** [comment]
> Re-reading the test, It doesn't make sense to change it since it's testing something very specific. I think we can drop the test.

@roydahan we can either drop it or the the expected failure.
