### ISSUE TITLE
Typo in Alternator code

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#11800]
@fee-mendes discovered the following typo in the Alternator code, `executor.cc`:

```c++
            sstring where_clause = "\"" + view_hash_key + "\" IS NOT NULL";
            if (!view_range_key.empty()) {
                where_clause = where_clause + " AND \"" + view_hash_key + "\" IS NOT NULL";
            }
```
clearly the second `view_hash_key` should be `view_range_key`, no?
This is the GSI code - curiously the code for the LSI code is similar but with the correct variable.

The interesting question is whether this bug can be demonstrated in a real use case, and if so we should write a test that reproduces it.

While looking at this code I think I may have spotted another bug: What if the key name view_hash_key needs quoting in CQL (`maybe_quote()`)? I think we are missing this quoting, and this is a second bug that needs to be tested and fixed. If this is a bug then it appears twice in the code - for GSI and LSI.

**Comment by avikivity** [comment]
@fee-mendes please update the subject to reflect the effect of the bug. Is it incorrect results? crashes? end of the universe?

**Comment by avikivity** [comment]
Or rather, @nyh

**Comment by nyh** [comment]
It turns out (@nuivall please correct me if you disagree) that this issue is of little or no practical importance: It turns out that the "IS NOT NULL" that we so diligently add to the definition of materialized views in Alternator doesn't get checked at all (because it is only checked in the CQL front-end code, which we don't call), and doesn't have any practical effect.

The only reason I have to anyway consider backporting this patch is that the incorrect definition is saved in the schema, so a GSI created today may be still alive with that incorrect definition 5 years from now, and who knows, maybe will start causing problems them.

**Comment by avikivity** [comment]
Ok. Please backport if you think it's worthwhile. But fix the subject regardless.

**Comment by nyh** [comment]
Backported to next-5.1 (bba55d59687b6271279a7ae9329ef07247968123)
