### ISSUE TITLE
docs: Question in page Expiring Data with Time to Live (TTL)

### ISSUE THREAD

**Issue by SarpongAbasimi** [scylladb/scylladb#11824]
I would like to report an issue in page https://docs.scylladb.com/master/cql/time-to-live

@denesb This is not really an issue but rather a question.
Based on the example in the documentation.
 Let us say I have this table with `1 billion` data in it
```sql
CREATE TABLE heartrate_ttl (
    pet_chip_id  uuid,
    name text,
    heart_rate int,
    PRIMARY KEY (pet_chip_id))

```
but all of the sudden I decide to 
`ALTER TABLE heartrate_ttl WITH default_time_to_live = 3600;`

What is the performance implications?
My initial thought was that this would not have a lot of performance implications because the 1 billion data which were already inserted would sill have the TTL set to `null` and that the `TTL` will only be applied to data that are inserted after the `TTL`

I just want your thoughts, thanks

**Comment by SarpongAbasimi** [comment]
@pdziepak

**Comment by SarpongAbasimi** [comment]
@krewenki

**Comment by denesb** [comment]
Please ask questions on slack or the scylladb-users@googlegroups.com email group.

> but all of the sudden I decide to
> ALTER TABLE heartrate_ttl WITH default_time_to_live = 3600;

This statement will only have effect on writes executed *after* this statement, no effect whatsoever on the already written data.

**Comment by SarpongAbasimi** [comment]
@denesb thank you, I thought so 😊. 
I have tried is and it affects only the writes after the statement 
`ALTER TABLE heartrate_ttl WITH default_time_to_live = 3600;`
Which means that there is no performance issue or outages in Sylla.
