### ISSUE TITLE
repair_based_node_operations_test: Rejected removenode operation, removing node=127.0.83.3, sync_nodes=[127.0.83.2, 127.0.83.1], ignore_nodes=[]; the node being removed is alive, maybe you should use decommission instead?

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11830]
Several repair base node operations started failing since
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/116/testReport/junit/repair_based_node_operations_test/TestRepairBasedNodeOperations/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split014___test_enable_rbno_for_all_operations/
Scylla version 87b7e7ff9ca1
```
ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.ccm/scylla-repository/87b7e7ff9ca1ff6524c5f67a43da56693004d2cb/scylla-tools-java/bin/nodetool -h 127.0.83.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy removenode c77d537d-6dba-4555-8b0e-b31db909a039 exited with non-zero status; exit status: 1; 
stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/remove_node' failed: std::runtime_error (removenode[1447d85a-41c2-4139-9ec4-58a6a78c3672]: Rejected removenode operation, removing node=127.0.83.3, sync_nodes=[127.0.83.2, 127.0.83.1], ignore_nodes=[]; the node being removed is alive, maybe you should use decommission instead?)
```

I'm not sure yet if the issue is with scylla or with the test, and which change exactly triggered the failures.

**Comment by bhalevy** [comment]
@asias can you please look into this?

**Comment by bhalevy** [comment]
Similar failure here: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/72/testReport/system_tables_test/TestClusterStatusTable/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split007___test_content_remove_node/
```
ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/dtest-daily-debug/scylla/.ccm/scylla-repository/9e34779c533722bcc212159b9ccf3db620a5bf28/scylla-tools-java/bin/nodetool -h 127.0.68.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy removenode 482b8194-e03a-4e53-9af8-95eaf7361d9d exited with non-zero status; exit status: 1; 
stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/remove_node' failed: std::runtime_error (removenode[53ba1a03-0524-4e5f-ba8f-efe3058568a1]: Rejected removenode operation, removing node=127.0.68.2, sync_nodes=[127.0.68.1], ignore_nodes=[]; the node being removed is alive, maybe you should use decommission instead?)
```

**Comment by asias** [comment]
This suggests in the dtest when removenode was run, the removed node was indeed still up or it was killed forcefully and the other nodes hadn't marked the node down yet.

**Comment by bhalevy** [comment]
Makes sense. So c76cf5956da just exposed the test issue, not caused it.

BTW, When fixing the test it hit another failure due to the fact that it passes the node-to-be-removed ip address to nodetool (as https://docs.scylladb.com/stable/operating-scylla/nodetool-commands/removenode.html suggests), but storage_service::removenode supports only uuid as the host id.

I'm baffled about how the test passed before c76cf5956da, up until https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/115/testReport/system_tables_test/TestClusterStatusTable/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_content_remove_node/

**Comment by bhalevy** [comment]
> I'm baffled about how the test passed before [c76cf59](https://github.com/scylladb/scylladb/commit/c76cf5956da7c60b5f24bced4d057c9eda58b03b), up until https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/115/testReport/system_tables_test/TestClusterStatusTable/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_content_remove_node/

Okay, mystery solved. The test_content_remove_node dtest uses `node2.hostid()` rather than the node ip address.
When stopping the node before invoking nodetool removenode, I changed that to use the ip address since the hostid cannot be discovered using `nodetool info` when the node is down.
