### ISSUE TITLE
[jespen] Bootstrap of multiple nodes as seeds is failing

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#11853]
## Installation details

Kernel Version: 4.19.0-21-cloud-amd64
Scylla version (or git commit hash): `5.2.0~dev-20221027.e245780d568b` with build-id `eabf9c884f530ffeaf1cfc0513fa5f0d11db764d`

Cluster size: 5 nodes (n1-standard-4)

Scylla Nodes used in this run:
- jepsen-ubuntu-db-node-06909595-0-5 (34.73.97.225 | 10.142.0.122) (shards: 4)
- jepsen-ubuntu-db-node-06909595-0-4 (34.74.59.212 | 10.142.0.121) (shards: 4)
- jepsen-ubuntu-db-node-06909595-0-3 (35.231.8.221 | 10.142.0.120) (shards: 4)
- jepsen-ubuntu-db-node-06909595-0-2 (104.196.37.122 | 10.142.0.118) (shards: 4)
- jepsen-ubuntu-db-node-06909595-0-1 (35.237.205.81 | 10.142.0.100) (shards: 4)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10` (gce: us-east1)

Test: `jepsen-test-all`
Test id: `06909595-dc47-400e-98ac-80c31dd418e7`
Test name: `scylla-master/jepsen/jepsen-test-all`
Test config file(s):

- [jepsen.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8c149204bc3ef80e71a8fd21cee24ae9d90453fb/test-cases/jepsen/jepsen.yaml)

## Issue description

As part of the jepsen tests, the cluster is booted with all nodes being seeds, and since 810b424a8c3612a0a3419cd556839596e381829a was merged

it's started failing like the following:
```
Oct 28 07:50:29 jepsen-ubuntu-db-node-06909595-0-2 scylla[24818]:  [shard 0] init - Startup failed: std::runtime_error (Node 10.142.0.100 has gossip status=UNKNOWN. Try fixing it before adding new node to the cluster.)
```

before that in https://jenkins.scylladb.com/job/scylla-master/job/jepsen/job/jepsen-test-all/130/ it was running and passing just fine,.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 06909595-dc47-400e-98ac-80c31dd418e7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=06909595-dc47-400e-98ac-80c31dd418e7)
- Show all stored logs command: `$ hydra investigate show-logs 06909595-dc47-400e-98ac-80c31dd418e7`

## Logs:
- **db-cluster-06909595.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/db-cluster-06909595.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/db-cluster-06909595.tar.gz)
- **monitor-set-06909595.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/monitor-set-06909595.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/monitor-set-06909595.tar.gz)
- **loader-set-06909595.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/loader-set-06909595.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/loader-set-06909595.tar.gz)
- **sct-runner-06909595.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/sct-runner-06909595.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/sct-runner-06909595.tar.gz)
- **jepsen-data.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/jepsen-data.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/06909595-dc47-400e-98ac-80c31dd418e7/20221028_160219/jepsen-data.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/jepsen/job/jepsen-test-all/133/)

**Comment by fruch** [comment]
@asias, can you take a look into this one ?

**Comment by fruch** [comment]
a dtest that reproduce the issue:
```python
    def test_start_seed_nodes_at_the_same_time(self):
        cluster = self.cluster

        cluster.populate(3)
        node1, node2, node3 = cluster.nodelist()
        node1.start(no_wait=True)
        node2.start(no_wait=True)
        node3.start()

        session = self.patient_cql_connection(node1)
        create_ks(session, 'ks', 4)
        create_cf(session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})

        insert_c1c2(session, keys=range(1000), consistency=ConsistencyLevel.THREE)
```

@kostja, since you know jespen test, is there a way to make them not start all the nodes at the same time ?

**Comment by kostja** [comment]
https://github.com/scylladb/jepsen/blob/master/src/scylla/db.clj#L486 start is not waiting for a complete join, and the seeds are specified upfront. db.clj needs to be fixed to account for the new procedure.

**Comment by roydahan** [comment]
@kostja are you doing this change?

**Comment by kostja** [comment]
No.

**Comment by kostja** [comment]
@margdoc do you encounter any startup issues when running your jepsen test?

**Comment by margdoc** [comment]
No, there wasn't any problem with startup, but I was running jepsen test with scylla 4.6

**Comment by mykaul** [comment]
Did it work in the past (read: is this a regression) ?

**Comment by fruch** [comment]
> Did it work in the past (read: is this a regression) ?

Yes it worked (we run this case on a weekly basis), and I'm pointing to the commit that broke it https://github.com/scylladb/scylladb/commit/810b424a8c3612a0a3419cd556839596e381829a

**Comment by kostja** [comment]
And the commit that broke it did it on purpose - it's a long debate whether or not we shoudl allow concurrent bootstrap and whether or not it's safe - ending up in us moving the bootstrap to raft, which hasn't been done yet, and in the meanwhile, digging ourselves into a hole on a completely different track with fixing customer issues arising from us not having raft and allowing operations which are unsafe without it.

**Comment by mykaul** [comment]
@kostja - are you saying that raft would allow that? I think it's inevitable that we'll run into such issues with K8s based deployments, and we don't want to introduce the logic into the operator to 'wait'.

**Comment by avikivity** [comment]
Then this becomes an issue with Jepsen.

**Comment by asias** [comment]
I send a PR here: https://github.com/scylladb/scylladb/pull/12041

**Comment by kostja** [comment]
@margdoc changed jepsen to bootstrap nodes sequentially: https://github.com/scylladb/jepsen/pull/15, please retest.
