### ISSUE TITLE
Allow manually selecting compaction strategy for Alternator tables

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#11856]
Today, Alternator tables are always created with the default compaction strategy (which in the open-source branch is STCS). For some use cases, this choice may not be optimal: For example a use case which constantly adds new items with a one-month TTL on each might want to use TWCS with (say) a one-day time window.

Today a user can modify this default compaction strategy using CQL, but there is no DynamoDB-API equivalent. Although using CQL on Alternator tables works, it is not a good practice because it might break if we change Alternator's table naming in the future, and also will not work in setups that only expose the DynamoDB API and not CQL.

So I propose that we add the ability to use the existing `TagResource` DynamoDB API to configure the table's compaction strategy, similar to how we configure the table's write isolation option as a tag (see the "Alternator-specific API" section in `docs/alternator/alternator.md`).

We should document how to change the compaction strategy in the same "Alternator-specific API" section, and explain what happens after such a change - Does the data get re-organized immediately, or gradually as compactions happen? Is this documented somewhere for CQL?

In the future it can be nice to develop a controller that automatically picks the best compaction strategy without hints from the user. But I think we should start by having a manual override like I'm proposing here which is much easier to implement, and the automatic controller, if we want one, should be a separate issue.

Noted by @yarongilor 
CC @raphaelsc @nuivall @havaker

**Comment by yarongilor** [comment]
IIUC, we probably should keep in mind that, unlike the case of 'write-isolation' tag, there we be kind of a duplication in the case of table compaction-strategy value since it will appear as a standard table attribute and as a table tag as well. something like:
```
CREATE TABLE alternator_usertable_no_lwt.usertable_no_lwt (
    p text,
    c text,
    ":attrs" map<text, blob>,
    PRIMARY KEY (p, c)
) WITH CLUSTERING ORDER BY (c ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': '**IncrementalCompactionStrategy**'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 7200
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

scylla_tags = {'system:write_isolation': 'forbid_rmw', 'system:ttl_attribute': 'ttl', ', 'system:compaction': '**IncrementalCompactionStrategy**'}
```

**Comment by nyh** [comment]
@yarongilor you're very right. We'll have to special-case reads and write to this specific tag in Alternator, and instead read and write the table property.
So indeed it will not be exactly the same implementation as the write-isolation tag, though for the user it will "feel" like they are similar - the same API will be used to configure both.

Interestingly, we have the opposite direction already, in another case: We have the SYNCHRONOUS_VIEW_UPDATES_TAG_KEY tag used to mark synchronous materialized views, and CQL materialized-view create or alter operations that have the `synchronous_updates` property get translated to changes of the tag, instead of modifying the schema table.

We actually have another example similar to this, of the

**Comment by nyh** [comment]
I'm closing this issue for now. While there might be in theory some reasons why we might want to configure the compaction strategy on an Alternator table, as @raphaelsc noticed (in a discussion on the mailing list), the motivating example given above was wrong: 

TWCS works well with CQL's TTL, because it can notice that entire old windows have expired and delete entire sstables. But it will work terribly with Alternator's TTL: This use case will have old windows with data, and then when the expiration occurs, it will have new tombstones in a new window. TWCS never compacts between windows, so we will never delete the old data from disk.
