### ISSUE TITLE
Multiple "commitlog - cannot parse the version" warnings during boot

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#11867]
When Scylla boots (e.g., I tried running a test like `test/cql-pytest/run test_null.py`), I see the following warning messages in the log:

```
INFO  2022-10-31 16:46:07,434 [shard 0] database - Using schema commit log.
WARN  2022-10-31 16:46:07,435 [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-125792602.log
WARN  2022-10-31 16:46:07,435 [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-18014398635274586.log
WARN  2022-10-31 16:46:07,435 [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-125792601.log
...
INFO  2022-10-31 16:46:07,562 [shard 0] init - starting schema commit log
WARN  2022-10-31 16:46:07,563 [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-18014398635274587.log
WARN  2022-10-31 16:46:07,563 [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-125792602.log
WARN  2022-10-31 16:46:07,564 [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-18014398635274586.log
WARN  2022-10-31 16:46:07,564 [shard 0] commitlog - Cannot parse the version of the file: CommitLog-2-125792601.log
...
INFO  2022-10-31 16:46:07,578 [shard 0] init - starting commit log
WARN  2022-10-31 16:46:07,578 [shard 0] commitlog - Cannot parse the version of the file: SchemaLog-2-125792602.log
WARN  2022-10-31 16:46:07,578 [shard 0] commitlog - Cannot parse the version of the file: SchemaLog-2-125792601.log
```

@tgrabiec @elcallio does this ring a bell?

**Comment by elcallio** [comment]
It is the effect of having a separate schema commitlog sharing storage folder with the "normal" commitlog. They find each others files and complain about unknown files. Could easily be fixed by either moving the schema logs or joining the two instances  back together again, but use two-phased replay.

**Comment by FlorianHockmann** [comment]
We're also seeing these warnings after updating to 5.1. Are these problematic or will the schema "process" ignore the "normal" commitlog and the one reading the "normal" commitlog ignore the schema commitlog and therefore it isn't problematic?

> Could easily be fixed by either moving the schema logs

Just to be sure: There currently is no option to configure Scylla to use separate directories for both commitlogs and you only meant that this would be a possible solution for the future, right?

**Comment by tgrabiec** [comment]
> We're also seeing these warnings after updating to 5.1. Are these problematic or will the schema "process" ignore the "normal" commitlog and the one reading the "normal" commitlog ignore the schema commitlog and therefore it isn't problematic?

Correct, it's not a correctness problem.

**Comment by tgrabiec** [comment]
> Just to be sure: There currently is no option to configure Scylla to use separate directories for both commitlogs and you only meant that this would be a possible solution for the future, right?

Yes

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to 5.2 (it's failing QA runs).

**Comment by denesb** [comment]
> @scylladb/scylla-maint please consider backport to 5.2 (it's failing QA runs).

I don't know if we can backport https://github.com/scylladb/scylladb/commit/0152c000bbb459d377d93caee39e2ea27daaa392 to an already released version. Although the change is small, it changes the on-disk directory layout. Not sure if this is expected on a minor release.

**Comment by denesb** [comment]
@avikivity, @tgrabiec do you think we can backport the above?

**Comment by mykaul** [comment]
ping @avikivity  , @tgrabiec  for above.

**Comment by tgrabiec** [comment]
Technically we could backport it. The change is transparent to the user.

Btw, the downgrades are not safe with this change if we crashed with data in the schema commitlog. In this case we may revert to an older schema.
