### ISSUE TITLE
Global index caching should not be enabled by default.

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#11889]
Global index caching, as introduced in 4.6 (078a6e422b96c7d2cca04c8cbe539ff6a572b95c and 9f957f1cf99a1d75104e48c21f8cff67b9867070) has proven to be misdesigned, because it poses a risk of catastrophic performance regressions in common workloads by flooding the cache with useless index entries. Because of that, it should be disabled by default.

Also see #11202 for a discussion.

**Comment by michoecho** [comment]
Refs scylladb/scylla-enterprise#2460

**Comment by avikivity** [comment]
Not a bug, not backporting.
