### ISSUE TITLE
Cleanup compaction doesn't cleanup the memtable

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11901]
Currently (5.2.dev 44f48bea0ffa0474371439a46e120c85d25f3d34) cleanup compaction ignores the memtable contents.
To clean up the memtable content one needs to explicitly flush it before initiating cleanup.

To prevent human errors, cleanup should either cleanup the memtable, or automatically flush it before it collects the sstable candidates.

I will also submit a dtest that reproduces this issue.

**Comment by raphaelsc** [comment]
dup of https://github.com/scylladb/scylladb/issues/1239
