### ISSUE TITLE
After changing node ip and keeping its host_id, the old endpoint still appears in system.peers

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11925]
Seen consistently in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/84/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split012___test_change_node_ip/
For example:
```
    def check_peer_and_local_table(self, nodes):
        peers_and_local = []
        for node in nodes:
            status = nodetool_status(node)
            logger.debug("nodetool status from {}: {}".format(node.name, status))
            s = self.patient_exclusive_cql_connection(node)
            peers = rows_to_list(s.execute("SELECT host_id, peer FROM system.peers"))
            local = rows_to_list(s.execute("SELECT host_id, broadcast_address FROM system.local"))
>           peers_and_local.append(str(sorted(peers + local)))
E           TypeError: '<' not supported between instances of 'NoneType' and 'UUID'
```

Locally, I see also:
```
12:42:06,474 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2123 | Check peer table for node3 with ip address 127.0.49.33 : peers=[[UUID('fd396b2b-3162-4dc4-832d-fbe5777a2f14'), '127.0.49.2'], [UUID('eac15ed3-8f32-421b-91da-5d5bf5a0caa8'), '127.0.49.3'], [UUID('444777d5-1b55-4aa8-afd4-9d6b5f237fbd'), '127.0.49.1']] 
12:42:06,474 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2124 | Check peer table for node3 with ip address 127.0.49.33 : local=[[UUID('eac15ed3-8f32-421b-91da-5d5bf5a0caa8'), '127.0.49.33']] 
12:42:06,474 update_cluster_layout_tests WARNING update_cluster_layout_tests.py:2126 | Expected 2 peers but got 3
```

I'm not sure why this is seen consistently in debug mode and not in dev/release modes.
It's probably related to relative timing of racing async calls.

My analysis shows that `storage_service::on_join` is called with the old endpoint inet_address,
calling `on_change` with `application_state::STATUS` and `versioned_value::STATUS_NORMAL`,
calling `handle_state_normal(endpoint)`.

There log messages show:
```
WARN  2022-11-08 12:55:15,208 [shard 0] storage_service - Not updating host ID 81909e9f-202d-47ce-94da-3406dab51f26 for 127.0.63.3 because it's mine
```

BUT https://github.com/scylladb/scylladb/blob/a9063f9582f0ea22dd2c95d457c5626f23f0256e/service/storage_service.cc#L971-L977

calls `update_topology(endpoint, get_dc_rack_for(endpoint))`

since 421557b40aa8d1adf5016722418936a99595cb20

which puts it back into the topology.

And, https://github.com/scylladb/scylladb/blob/a9063f9582f0ea22dd2c95d457c5626f23f0256e/service/storage_service.cc#L997-L999
calls `notify_joined(endpoint)` which is not the root cause of this issue, but there's no reason to notify that the old endpoint joined when it owns no tokens and is marked for removal.

Later on, https://github.com/scylladb/scylladb/blob/a9063f9582f0ea22dd2c95d457c5626f23f0256e/service/storage_service.cc#L1217-L1218
Sees the old endpoint in token_metadata (after update_topology inserted it back)
and calls `do_update_system_peers_table(endpoint, state, value)` which adds it back to system.peers, after it was removed from it.

The following change fixes the issue for me locally:
```
diff --git a/service/storage_service.cc b/service/storage_service.cc
index 03611a7ed0..9896d4e6da 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -969,11 +969,15 @@ future<> storage_service::handle_state_normal(inet_address endpoint) {
     }
 
     bool is_member = tmptr->is_member(endpoint);
+    bool do_notify_joined = !is_member && !endpoints_to_remove.contains(endpoint);
+
     // Update pending ranges after update of normal tokens immediately to avoid
     // a race where natural endpoint was updated to contain node A, but A was
     // not yet removed from pending endpoints
-    if (!is_member) {
-        tmptr->update_topology(endpoint, get_dc_rack_for(endpoint));
+    if (do_notify_joined) {
+        auto dc_rack = get_dc_rack_for(endpoint);
+        slogger.debug("handle_state_normal: update_topology: endpoint={} dc={} rack={}", endpoint, dc_rack.dc, dc_rack.rack);
+        tmptr->update_topology(endpoint, std::move(dc_rack));
     }
     co_await tmptr->update_normal_tokens(owned_tokens, endpoint);
     co_await update_pending_ranges(tmptr, format("handle_state_normal {}", endpoint));
@@ -994,7 +998,7 @@ future<> storage_service::handle_state_normal(inet_address endpoint) {
     }
 
     // Send joined notification only when this node was not a member prior to this
-    if (!is_member) {
+    if (do_notify_joined) {
         co_await notify_joined(endpoint);
     }
 
```

**Comment by bhalevy** [comment]
Cc @asias

**Comment by bhalevy** [comment]
@mykaul @tgrabiec this is another example why it would be simpler to map tokens to host IDs and separately maintain a host_id -> inet_address directory.

**Comment by xemul** [comment]
@bhalevy ,

> BUT
>
>       bool is_member = tmptr->is_member(endpoint); 
>       // Update pending ranges after update of normal tokens immediately to avoid 
>       // a race where natural endpoint was updated to contain node A, but A was 
>       // not yet removed from pending endpoints 
>       if (!is_member) { 
>           tmptr->update_topology(endpoint, get_dc_rack_for(endpoint)); 
>       } 
>
> calls update_topology(endpoint, get_dc_rack_for(endpoint))
>
> since 421557b40aa8d1adf5016722418936a99595cb20
> 
> which puts it back into the topology.

It was such even before the change -- the subsequent call to

```c++
    co_await tmptr->update_normal_tokens(owned_tokens, endpoint);
```

used to insert the endpoint into topology itself. See 4cbe6ee9f40c6b744c907b657969d79939026d8b

**Comment by xemul** [comment]
>     12:42:06,474 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2123 | Check peer table for node3 with ip address 127.0.49.33 : peers=[[UUID('fd396b2b-3162-4dc4-832d-fbe5777a2f14'), '127.0.49.2'], [UUID('eac15ed3-8f32-421b-91da-5d5bf5a0caa8'), '127.0.49.3'], [UUID('444777d5-1b55-4aa8-afd4-9d6b5f237fbd'), '127.0.49.1']] 
>     12:42:06,474 update_cluster_layout_tests DEBUG update_cluster_layout_tests.py:2124 | Check peer table for node3 with ip address 127.0.49.33 : local=[[UUID('eac15ed3-8f32-421b-91da-5d5bf5a0caa8'), '127.0.49.33']] 
>     12:42:06,474 update_cluster_layout_tests WARNING update_cluster_layout_tests.py:2126 | Expected 2 peers but got 3

To sum up: the node had IP 127.0.49.3, changed it into 127.0.49.33 and found itself in the system.peers under the old IP address

**Comment by xemul** [comment]
> My analysis shows that storage_service::on_join is called with the old endpoint inet_address,

Presumably that's because other nodes gossip this information around having this node's old IP?

**Comment by asias** [comment]
@bhalevy can you check if https://github.com/scylladb/scylladb/pull/11936 alone make your test pass? 

(I saw your PR https://github.com/scylladb/scylladb/pull/11930, my PR is not intended to replace it)

**Comment by bhalevy** [comment]
> @bhalevy can you check if #11936 alone make your test pass?
> 
> (I saw your PR #11930, my PR is not intended to replace it)

Yes, v2 ([5768f1c](https://github.com/scylladb/scylladb/commit/5768f1cee064cd12434b5ea1e44c5ea4fd732246)) works with test_change_node_ip too

**Comment by bhalevy** [comment]
> @bhalevy does this need to be backported?

No, it was introduced in 5.2.0 by https://github.com/scylladb/scylladb/commit/421557b40aa8d1adf5016722418936a99595cb20
and the branch already has the fix.
