### ISSUE TITLE
token_metadata:is_member should not depend on topology

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#11935]
The topology is about rack and dc. The is_member is about if the node is part of the token ring. We should check is_member with the token ring info directly.

**Comment by avikivity** [comment]
@asias from the description it looks like it doesn't directly fix a bug and therefore needs no backport. Is this correct?

**Comment by asias** [comment]
> @asias from the description it looks like it doesn't directly fix a bug and therefore needs no backport. Is this correct?

Correct.

**Comment by avikivity** [comment]
Not a bug, not backporting.
