### ISSUE TITLE
topology copy constructor doesn't copy _sort_by_proximity

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11962]
See https://github.com/scylladb/scylladb/blob/ff87624fb4d6699a4dcecaf847a1375018da5ffa/locator/token_metadata.cc#L1269-L1275

**Comment by bhalevy** [comment]
The impact of this issue is minor since `_sort_by_proximity = true` by default, so it only disables an optimization for `SimpleSnitch` that doesn't sort by proximity.

See https://github.com/scylladb/scylladb/blob/ff87624fb4d6699a4dcecaf847a1375018da5ffa/main.cc#L734-L746

**Comment by avikivity** [comment]
Since the impact is very low, not backporting.
