### ISSUE TITLE
Run a 'select table' query failed with : "Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#11964]
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc2-20220919.75d087a2b75a` with build-id `463f1a57b82041a6c6b6441f0cbc26c8ad93091e`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc2.0.20220919.75d087a2b75a.tar.gz
Cluster size: 5 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-3h-2022-2-db-node-5d70fb77-5 (3.250.107.231 | 10.4.3.245) (shards: 7)
- longevity-twcs-3h-2022-2-db-node-5d70fb77-4 (34.244.241.249 | 10.4.0.5) (shards: 7)
- longevity-twcs-3h-2022-2-db-node-5d70fb77-3 (34.245.58.118 | 10.4.1.87) (shards: 7)
- longevity-twcs-3h-2022-2-db-node-5d70fb77-2 (54.75.37.154 | 10.4.0.12) (shards: 7)
- longevity-twcs-3h-2022-2-db-node-5d70fb77-1 (52.215.206.231 | 10.4.3.240) (shards: 7)

OS / Image: `ami-00bd31f22bcf5ae1a` (aws: eu-west-1)

Test: `longevity-twcs-3h-test`
Test id: `5d70fb77-88f3-45d1-9e14-b825d9840c47`
Test name: `enterprise-2022.2/longevity/longevity-twcs-3h-test`
Test config file(s):

- [longevity-twcs-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9818d76f6d1584c8d4652429a6aa1c616b6bb3c2/test-cases/longevity/longevity-twcs-3h.yaml)

## Issue description

**>>>>>>>**
scenario:
during no-corrupt-repair, the nemesis tries running a select query to get a table for the test.
It runs using a page fetcher with a set page size.
Then it wait for 30 seconds to get results by required page number (in this case it is - 1).
The operation failed with 30 seconds timeout of this query (with CL=ONE) for the cassandra driver not getting any pages result at all:
```
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-10-03 13:27:18.056: (DisruptionEvent Severity.ERROR) period_type=end event_id=e68255e3-43e7-4adb-bc50-3aa932ba7f9f duration=10m33s: nemesis_name=NoCorruptRepair target_node=Node longevity-twcs-3h-2022-2-db-node-5d70fb77-5 [3.250.107.231 | 10.4.3.245] (seed: False) errors=Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3669, in wrapper
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = method(*args, **kwargs)
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1417, in disrupt_no_corrupt_repair
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self._prepare_test_table(ks=f'drop_table_during_repair_ks_{i}', table='standard1')
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1685, in _prepare_test_table
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     ks_cfs = self.cluster.get_non_system_ks_cf_list(db_node=self.target_node)
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3340, in get_non_system_ks_cf_list
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self.get_any_ks_cf_list(db_node, filter_out_table_with_counter=filter_out_table_with_counter,
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3402, in get_any_ks_cf_list
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     regular_table_names = execute_cmd(cql_session=session, entity_type="column")
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3366, in execute_cmd
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     fetcher = PageFetcher(execute_result).request_all()
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2256, in __init__
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self.wait(seconds=30)
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 2331, in wait
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise RuntimeError(error_message('Requested pages were not delivered before timeout'))
< t:2022-10-03 13:27:18,059 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > RuntimeError: Requested pages were not delivered before timeout. Requested: 1; retrieved: 0; empty retrieved 0
```
The code of fetcher, executed by test is:
```
            session.default_fetch_size = 1000
            session.default_consistency_level = ConsistencyLevel.ONE
            execute_result = session.execute_async(cmd)
            fetcher = PageFetcher(execute_result).request_all()
            current_rows = fetcher.all_data()
```

During this time, there was a scylla-bench load running and some large-data warnings happened:
```
< t:2022-10-03 13:27:17,694 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:DEBUG > 2022-10-03T13:27:17+00:00 longevity-twcs-3h-2022-2-db-node-5d70fb77-1  !WARNING | scylla[7589]:  [shard 1] large_data - Writing large partition scylla_bench/test: 781684047872 (2317
4255 bytes) to me-274-big-Data.db
< t:2022-10-03 13:27:17,872 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-10-03T13:27:17+00:00 longevity-twcs-3h-2022-2-db-node-5d70fb77-2  !WARNING | scylla[7754]:  [shard 6] large_data - Writing large partition scylla_bench/test: 313532612608 (39633240 b
ytes) to me-265-big-Data.db
< t:2022-10-03 13:27:17,872 f:events_processes.py l:146  c:sdcm.sct_events.events_processes p:DEBUG > Get process `MainDevice' from EventsProcessesRegistry[lod_dir=/home/ubuntu/sct-results/20221003-101102-525719,id=0x7fc974fccfa0,default=True]
< t:2022-10-03 13:27:17,874 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:DEBUG > 2022-10-03 13:27:17.872 <2022-10-03 13:27:17.000>: (DatabaseLogEvent Severity.WARNING) period_type=one-time event_id=d63bed88-c1ee-459a-b5f0-dfb2679aa93d: type=WARNING regex=(^WARNI
NG|!\s*?WARNING).*\[shard.*\] line_number=13396 node=longevity-twcs-3h-2022-2-db-node-5d70fb77-2
< t:2022-10-03 13:27:17,874 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:DEBUG > 2022-10-03T13:27:17+00:00 longevity-twcs-3h-2022-2-db-node-5d70fb77-2  !WARNING | scylla[7754]:  [shard 6] large_data - Writing large partition scylla_bench/test: 313532612608 (3963
3240 bytes) to me-265-big-Data.db
< t:2022-10-03 13:27:17,952 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 2h40m50s   47096   47096      0 70ms   12ms   5.9ms  4.2ms  3.6ms  2ms    2.1ms  
< t:2022-10-03 13:27:17,988 f:cluster.py      l:2960 c:sdcm.cluster         p:DEBUG > Retrying read after timeout. Attempt #2
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 5d70fb77-88f3-45d1-9e14-b825d9840c47`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=5d70fb77-88f3-45d1-9e14-b825d9840c47)
- Show all stored logs command: `$ hydra investigate show-logs 5d70fb77-88f3-45d1-9e14-b825d9840c47`

## Logs:
- **db-cluster-5d70fb77.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/db-cluster-5d70fb77.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/db-cluster-5d70fb77.tar.gz)
- **monitor-set-5d70fb77.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/monitor-set-5d70fb77.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/monitor-set-5d70fb77.tar.gz)
- **loader-set-5d70fb77.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/loader-set-5d70fb77.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/loader-set-5d70fb77.tar.gz)
- **sct-runner-5d70fb77.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/sct-runner-5d70fb77.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/sct-runner-5d70fb77.tar.gz)
- **parallel-timelines-report-5d70fb77.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/parallel-timelines-report-5d70fb77.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/5d70fb77-88f3-45d1-9e14-b825d9840c47/20221003_135606/parallel-timelines-report-5d70fb77.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/longevity/job/longevity-twcs-3h-test/2/)

**Comment by mykaul** [comment]
(unsure, why are we still testing RC2?)

**Comment by yarongilor** [comment]
not reproduced in 2022.2 rc4
