### ISSUE TITLE
All nodes experiencing Reactor stalls (>800 ms) when attempting to alter a table's tombstone_gc mode

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylladb#11977]
## Installation details

Kernel Version: 5.15.0-1022-aws
Scylla version (or git commit hash): `5.2.0~dev-20221109.243fcb96f042` with build-id `70e3ae2ea7c092f91209c7caa8900898399783cb`

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-267fb9fa-9 (54.197.176.105 | 10.12.8.65) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-8 (18.212.254.82 | 10.12.10.188) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-7 (3.91.158.141 | 10.12.9.98) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-6 (18.215.172.40 | 10.12.10.12) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-5 (34.201.148.87 | 10.12.9.121) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-4 (54.221.143.217 | 10.12.11.16) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-3 (3.94.161.45 | 10.12.8.171) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-2 (50.17.73.82 | 10.12.11.112) (shards: 7)
- longevity-twcs-48h-master-db-node-267fb9fa-1 (52.23.225.88 | 10.12.11.10) (shards: 7)

OS / Image: `ami-05f7774a78151a2ad` (aws: us-east-1)

Test: `longevity-twcs-48h-test`
Test id: `267fb9fa-8d2c-4db7-95b0-9eef1e549340`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/edd40ec9434202317c397afe574df7f057147341/test-cases/longevity/longevity-twcs-48h.yaml)

## Issue description

At `2022-11-12 06:00:27.748`, a ToggleTableGcMode nemesis has started. As the name suggests, it alters a non-system table tombstone_gc_mode option, like so:
`< t:2022-11-12 06:00:41,621 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "ALTER TABLE  scylla_bench.test WITH tombstone_gc = {'mode': 'repair'};" 10.12.10.12 9042"...`
The query, however, failed:
```
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "ALTER TABLE  scylla_bench.test WITH tombstone_gc = {\'mode\': \'repair\'};" 10.12.10.12 9042'

Exit code: 1

Stdout:



Stderr:

Connection error: ('Unable to connect to any servers', {'10.12.10.12': ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out for system.local - received only 0 responses from 1 CL=ONE." info={\'received_responses\': 0, \'required_responses\': 1, \'consistency\': \'ONE\'}',)})
```
Looking into the logs of the other nodes, it seems that all of the nodes have experienced several reactor stalled simultaneously, eventually reaching above 800 ms:
Node 1:
[node1_reactor_stalled.log](https://github.com/scylladb/scylladb/files/10005192/node1_reactor_stalled.log)

Node 2:
[node2_reactor_stalled.log](https://github.com/scylladb/scylladb/files/10005193/node2_reactor_stalled.log)

Node 3:
[node3_reactor_stalled.log](https://github.com/scylladb/scylladb/files/10005195/node3_reactor_stalled.log)

Node 6:
[node6_reactor_stalled.log](https://github.com/scylladb/scylladb/files/10005226/node6_reactor_stalled.log)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 267fb9fa-8d2c-4db7-95b0-9eef1e549340`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=267fb9fa-8d2c-4db7-95b0-9eef1e549340)
- Show all stored logs command: `$ hydra investigate show-logs 267fb9fa-8d2c-4db7-95b0-9eef1e549340`

## Logs:
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221112_213533/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20221112_213637-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221112_213533/grafana-screenshot-overview-20221112_213533-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png                                                 
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221112_233454/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20221112_233529-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221112_233454/grafana-screenshot-overview-20221112_233454-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png                                                 
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221112_235043/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20221112_235118-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221112_235043/grafana-screenshot-overview-20221112_235043-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png                                                 
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_012148/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20221113_012224-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_012148/grafana-screenshot-overview-20221113_012148-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png                                                 
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_022824/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20221113_022900-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_022824/grafana-screenshot-overview-20221113_022824-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png                                                 
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_035908/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20221113_035943-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_035908/grafana-screenshot-overview-20221113_035908-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png                                                 
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_140656/grafana-screenshot-longevity-twcs-48h-test-scylla-per-server-metrics-nemesis-20221113_140732-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png
grafana        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_140656/grafana-screenshot-overview-20221113_140656-longevity-twcs-48h-master-monitor-node-267fb9fa-1.png                                                 
critical       | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/critical-267fb9fa.log.tar.gz                                                                                                                      
db-cluster     | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/db-cluster-267fb9fa.tar.gz                                                                                                                        
debug          | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/debug-267fb9fa.log.tar.gz                                                                                                                         
email_data     | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/email_data-267fb9fa.json.tar.gz                                                                                                                   
error          | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/error-267fb9fa.log.tar.gz                                                                                                                         
event          | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/events-267fb9fa.log.tar.gz                                                                                                                        
left_processes | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/left_processes-267fb9fa.log.tar.gz                                                                                                                
loader-set     | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/loader-set-267fb9fa.tar.gz                                                                                                                        
monitor-set    | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/monitor-set-267fb9fa.tar.gz                                                                                                                       
normal         | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/normal-267fb9fa.log.tar.gz                                                                                                                        
output         | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/output-267fb9fa.log.tar.gz                                                                                                                        
event          | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/raw_events-267fb9fa.log.tar.gz                                                                                                                    
sct            | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/sct-267fb9fa.log.tar.gz                                                                                                                           
summary        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/summary-267fb9fa.log.tar.gz                                                                                                                       
warning        | https://cloudius-jenkins-test.s3.amazonaws.com/267fb9fa-8d2c-4db7-95b0-9eef1e549340/20221113_142016/warning-267fb9fa.log.tar.gz                                                                                                                       

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/64/)

**Comment by avikivity** [comment]
Why were no logs captured during the run?

Proposal: QA runs with no logs will not be reported. @roydahan

**Comment by roydahan** [comment]
@ShlomiBalalis please attach the logs.

**Comment by ShlomiBalalis** [comment]
> Why were no logs captured during the run?
> 
> Proposal: QA runs with no logs will not be reported. @roydahan

Sorry, there must have been an issue with Argus/the issue template. There are definitely logs for this run, they were just not automatically included for some reason. I edited the description to include them

**Comment by DoronArazii** [comment]
Duplicate with #2577
