### ISSUE TITLE
storage_proxy encountered std::bad_alloc and crash

### ISSUE THREAD

**Issue by JerryKwan** [scylladb/scylladb#11990]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): scylla-conf-5.0.5-0.20221009.5a97a1060.x86_64
Cluster size: 10 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

After running for a while and the data volume saved in one node is almost 850G, the node crashed with the following logs
```
Nov 15 12:28:53 localhost scylla: [shard 23] storage_proxy - exception during mutation write to 104.225.xx.xx: std::bad_alloc (std::bad_alloc)
Nov 15 12:28:53 localhost  scylla: [shard 23] storage_proxy - exception during mutation write to 158.120.xx.xx: std::bad_alloc (std::bad_alloc)
Nov 15 12:28:53 localhost  scylla: [shard 23] storage_proxy - exception during mutation write to 158.120.xx.xx: std::bad_alloc (std::bad_alloc)
Nov 15 12:28:53 localhost  scylla: [shard 23] storage_proxy - exception during mutation write to 104.225.xx.xx: std::bad_alloc (std::bad_alloc)
Nov 15 12:28:53 localhost  scylla: [shard 23] storage_proxy - exception during mutation write to 158.120.xx.xx: std::bad_alloc (std::bad_alloc)
Nov 15 12:28:53 localhost  scylla: [shard 22] storage_proxy - Failed to apply mutation from 158.120.xx.xx#22: std::bad_alloc (std::bad_alloc)
Nov 15 12:28:53 localhost  scylla: [shard 23] storage_proxy - exception during mutation write to 104.225.xx.xx: std::bad_alloc (std::bad_alloc)
```

**Comment by denesb** [comment]
@JerryKwan we need a coredump to debug this. Can you please restart scylla with `--abort-on-lsa-bad-alloc=1` and `--abort-on-seastar-bad-alloc` additional command line parameters. The next time scylla will hit a bad-alloc, it will generate a coredump. See https://docs.scylladb.com/stable/troubleshooting/report-scylla-problem.html#core-dump for how to upload it so we can inspect it.

**Comment by avikivity** [comment]
Do you have monitoring installed?

Please describe the cluster hardware in more detail: memory per node, cores per node, disk space, disk type.

**Comment by avikivity** [comment]
And the schema!

**Comment by mykaul** [comment]
ping @JerryKwan

**Comment by JerryKwan** [comment]
@mykaul 
Sorry, we have changed back to Cassandra

**Comment by mykaul** [comment]
Thanks, closing for the time being.
