### ISSUE TITLE
Document scylla-api-cli

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#11999]
scylla-api-cli is a lightweight command line tool interfacing the scylla REST API.
The tool can be used to list the different API functions and their parameters, and to print detailed help for each function.

Then, when invoking any function, scylla-api-cli performs basic validation on the function arguments and prints the result to the standard output. Note that json results msy be pretty-printed using commonly available command line utilities.

It is recommended to use scylla-api-cli for interactive usage of the REST API over plain http tools, like curl, to prevent human errors.

**Comment by tzach** [comment]
Related PR:
https://github.com/scylladb/scylladb/pull/11849

While #11849 describe a UI interafce to rhe REST API, this issue describe a CLI for the same REST API

**Comment by tzach** [comment]
@bhalevy FYI

**Comment by mykaul** [comment]
The tool appears in the 5.1 release notes, but is not targeted to be documented until 5.2?

**Comment by tzach** [comment]
> The tool appears in the 5.1 release notes, but is not targeted to be documented until 5.2?

Should be part of 5.1 release (even if its a few day late)
