### ISSUE TITLE
Running task manager's task that is already aborted should be prevented

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#11995]
Task manager lacks a dedicated mechanism to abort task/check
whether task was aborted.

Thus, when `start()` is called on a task manager's task when 
the corresponding operation has already been aborted, its state is set
to `task_manager::task_state::running` and it continues to run until
abort status is checked (and/or an exception is thrown).

Instead the task's state should be immediately set to 
`task_manager::task_state::failed` and stored in task manager, but
its run method should not be called.

**Comment by avikivity** [comment]
@Deexie should this be backported? can a user trigger it?

**Comment by avikivity** [comment]
Removing backport label per above.
