### ISSUE TITLE
compaction: compaction_manager::task can be stopped more that once causing a program to crash

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#12002]
compaction_manager::stop_ongoing_compactions can be called because of 
many different reasons. That may cause a compaction_manager::task 
(and consequently compaction_data) to be stopped many times. 

In its stop() method compaction_data calls request_abort() on an abort source. 
If this action is performed more than once, a whole program is aborted.

**Comment by avikivity** [comment]
Backported to 5.1. Will backport further pending feedback from @raphaelsc .

**Comment by avikivity** [comment]
Removing backport candidate label.

**Comment by bhalevy** [comment]
> Fixed by [7ead1a7](https://github.com/scylladb/scylladb/commit/7ead1a7857b49ebe9a5c6e66ca5b4640a869da50).

closing...
