### ISSUE TITLE
Grouped clustering keys relation makes ignore filtering

### ISSUE THREAD

**Issue by wyfo** [scylladb/scylladb#12014]
*Installation details*
Scylla version (or git commit hash): 4.6.9-0.20221009.18e7a4603 (and 5.0.5-0.20221009.5a97a1060)

## Steps to reproduce
```cql
// (for cqlsh PAGING OFF)
CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
USE test;
CREATE TABLE test(pk int, ts timestamp, id int, processed boolean, PRIMARY KEY (pk, ts, id));
INSERT INTO test (pk, ts, id, processed) VALUES (0, currentTimestamp(), 0, true);
INSERT INTO test (pk, ts, id, processed) VALUES (0, currentTimestamp(), 1, true);
INSERT INTO test (pk, ts, id, processed) VALUES (0, currentTimestamp(), 2, false);
INSERT INTO test (pk, ts, id, processed) VALUES (0, currentTimestamp(), 3, false);
SELECT id, processed FROM test WHERE pk = 0 AND ts >= 0 AND processed = false ALLOW FILTERING;
/* as expected */
//  id | processed
// ----+-----------
//   2 |     False
//   3 |     False
SELECT id, processed FROM test WHERE pk = 0 AND (ts, id) >= (0, 0) AND processed = false ALLOW FILTERING;
/* unexpected, should be the same as above */
//  id | processed
// ----+-----------
//   0 |      True  /* `processed = false` is ignored */
//   1 |      True
//   2 |     False
//   3 |     False
```

**Comment by wyfo** [comment]
@ultrabug

**Comment by cvybhu** [comment]
Posted a fix in #12031

**Comment by wyfo** [comment]
Thank you for the patch.

So, this is a duplicate of #6200; I did search for similar issue before posting, but my wording was not close enough.

Feel free to close it as duplicate, or let's just wait #12031 merge.

**Comment by cvybhu** [comment]
Let's just wait for #12031 to autoclose this issue

**Comment by nyh** [comment]
Thanks @wyfo for re-discovering this bug and @cvybhu for fixing it.

@eliransin @mykaul please consider how we could devote developer time to solving these known bugs before users have to rediscover them. Preemptively discovering these bugs and creating easy-to-use reproducer tests was the main reason why I started the Cassandra unit test translation project (a 20% project which unfortunately I have not been able to give enough attention for), but the fact is that even after we have an open issue and an xfailing test, we often do not go and fix the bug. I think we should reconsider that reactive approach, and consider more proactive approach - because in my experience it's often much more difficult and time-consuming to understand a user's bug and discover what caused it, than it would have been to solve the bug in the first place.

**Comment by nyh** [comment]
Backported 2d2034ea28b8615a130146ad9780010d29d2fcc9 to next-5.1 (c8bb147f84c062dca765c2c5d7aa5f444e660471) and a non-trivial backport to next-5.0 (b2ef530c8fe57cb00ecf5a52cf3f71fc85ab3a23)

**Comment by avikivity** [comment]
What about 4.6? I guess we can backport the 5.0 change once it promotes.

**Comment by yacir** [comment]
Thanks for your reactivity guys. 

What about the 4.6 backport ? We didn't move to the v5 yet

**Comment by avikivity** [comment]
@nyh the 5.0 backport is failing (restrictions_test.multi_col_in).

**Comment by denesb** [comment]
> @nyh the 5.0 backport is failing (restrictions_test.multi_col_in).

Dequeued 5.0 backport as it breaks next promotion.

**Comment by nyh** [comment]
@cvybhu can you please do the backport to 5.0 (and maybe also 4.6...) yourself? As I said, it didn't trivially apply and when I fixed it maybe I did something wrong (or maybe there's something wrong in the multi_col_in test?)

**Comment by cvybhu** [comment]
> @cvybhu can you please do the backport to 5.0 (and maybe also 4.6...) yourself? As I said, it didn't trivially apply and when I fixed it maybe I did something wrong (or maybe there's something wrong in the multi_col_in test?)

Sure, although I never backported anything yet. What's the exact process? Should it go something like:
* I checkout to `branch-5.0` and create a branch to add my fix on
* I open a PR to merge my branch into `branch-5.0`
* Someone cherry-picks it to `next-5.0`
* It passes the tests there
* The PR gets closed
* `next-5.0` becomes `branch-5.0`

I guess I will have to use dbuild or something like that to build old scylla and run the tests.
I tried building `5.0` on my current environment, but it didn't build.

**Comment by mykaul** [comment]
@cvybhu - once you figure out the process, can you please add it to https://github.com/scylladb/scylladb/wiki for future reference?

**Comment by avikivity** [comment]
> > @cvybhu can you please do the backport to 5.0 (and maybe also 4.6...) yourself? As I said, it didn't trivially apply and when I fixed it maybe I did something wrong (or maybe there's something wrong in the multi_col_in test?)
> 
> Sure, although I never backported anything yet. What's the exact process? Should it go something like:
> 
> * I checkout to `branch-5.0` and create a branch to add my fix on
> * I open a PR to merge my branch into `branch-5.0`
> * Someone cherry-picks it to `next-5.0`

Uses scripts/pull_github_pr.sh to do that

> * It passes the tests there
> * The PR gets closed
> * `next-5.0` becomes `branch-5.0`
> 


That's exactly correct.

> I guess I will have to use dbuild or something like that to build old scylla and run the tests. I tried building `5.0` on my current environment, but it didn't build.

Yes

**Comment by nyh** [comment]
> > @cvybhu can you please do the backport to 5.0 (and maybe also 4.6...) yourself? As I said, it didn't trivially apply and when I fixed it maybe I did something wrong (or maybe there's something wrong in the multi_col_in test?)
> 
> Sure, although I never backported anything yet. What's the exact process? Should it go something like:
> 
>     * I checkout to `branch-5.0` and create a branch to add my fix on

Right. You can use `git cherry-pick -m1 -x <commitid>` to add your fix based to the existing master merged patch, but there will be conflicts you'll need to fix manually.
Alternatively, if you want to add your patches manually, please add a note in the merge commit about this being a backport of this-and-that master commit.

Please at least run the specific test which Avi reported to have failed manually, before the CI will later run all the tests.

> I guess I will have to use dbuild or something like that to build old scylla and run the tests. I tried building `5.0` on my current environment, but it didn't build.

Right. You can use commands like the following to build and run the failed test (completely untested).
```
rm -r build
dbuild configure.py --disable-dpdk
dbuild ninja build/dev/tests/restrictions_test
dbuild build/dev/test/restrictions_test -- -c1 -m1G
```

**Comment by cvybhu** [comment]
Okay I made a backport to 5.0 in #12086, I think it looks the way it's supposed to.
The same fix works on `4.6`, so I will open another PR once I'm sure that's the correct way to do it.

` scripts/pull_github_pr.sh` tried to perform `git merge` with the original fix branch, which basically tried to merge master into branch-5.0, so I didn't use that.

`git cherry-pick -m1 -x <commitid>` worked beautifully

**Comment by nyh** [comment]
Thanks @cvybhu for the backport, and @avikivity for merging it into 5.1 and 4.6. I see it was successfully promoted in both branches, so removing the "backport candidate" tag.

**Comment by cvybhu** [comment]
> @cvybhu - once you figure out the process, can you please add it to https://github.com/scylladb/scylladb/wiki for future reference?

Added a wiki page here: https://github.com/scylladb/scylladb/wiki/Backporting

I was a bit surprised that there wasn't any review/approval required to do it.

There's also the [`dev/docs`](https://github.com/scylladb/scylladb/tree/master/docs/dev) directory and it looks like the files there are fresher than the wiki.
Not sure where I should put the documentation.

cc @annastuchlik

**Comment by nyh** [comment]
Thanks @cvybhu. In the distant past, we used the wiki a lot, but it fell out of favor for several reasons. The first reason was that, like you said, there was no review process on creation, modification, or deletion of pages, nor any way for reviewers to comment on a document. It even happened (more than once) that a document which someone wrote was unilaterally deleted by another person who decided to copy part of the information to another document and delete the original. The second reason was that there was no versioning - do we, or where do we, keep documents related only to old versions? It is more natural to have the documents together with the source code. Finally, it was hard to find these wiki documents - for developers the source directory is more easily available, visible, and searchable.

This is why I would recommend putting developer documentation in docs/dev, not in the wiki.

We already have docs/dev/maintainer.md, where (mostly) Avi shared some useful maintenance tips. It too mentions backporting, with some of the same commands that you used, but from a maintainers point of view. Maybe it makes sense to have a file docs/dev/contributor.md which is more oriented towards "regular" contributors, who need to create pull requests (like you did) and not merge them. I don't think it can be a bigger document, with all sorts of tips, not just about backporting, that developers can turn to regularly for github tips et al.

**Comment by denesb** [comment]
We already have a contributor.md in the root directory. I think that
would be a good place to add this guide to.

**Comment by nyh** [comment]
> We already have a contributor.md in the root directory. I think that would be a good place to add this guide to.

I just realized we actually have two: CONTRIBUTING.md and docs/contribute.rst. I think neither is in the right place - if it's documentation for developers, why isn't it in docs/dev? And it would also be nice to merge the two files... The important thing is just that the top-level README.md continues to point to the right document.

I see we also have a third (!) document, HACKING.md. The README.md calls this "developer guidelines". I don't know how exactly these three files are supposed to differ from each other, and if it's a good idea to merge them all together or keep them separate but with clearer names.

**Comment by nyh** [comment]
I opened #12126 about the document duplication.
