### ISSUE TITLE
queries should use the effective replication map topology rather than the latest one

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12050]
Currently, there are a couple places in storage_proxy where low level function use the latest topology for looking up endpoints calculated using the e_r_m that's held by the query.

It is possible that some of those endpoints may be removed from the latest topology if, for example, a concurrent decommissioned removed them.

This may be seen with `update_cluster_layout_tests.py::TestUpdateClusterLayout::test_simple_decommission_node_while_query_info_2` after fa613285e70ff85c24158fd3309518f1106d56f4.

See https://github.com/scylladb/scylladb/blob/f3eecb47f64de4390839c350c766285d18ecf5d2/service/storage_proxy.cc#L5327-L5331

and https://github.com/scylladb/scylladb/blob/f3eecb47f64de4390839c350c766285d18ecf5d2/service/storage_proxy.cc#L5988-L5989

**Comment by avikivity** [comment]
@xemul @bhalevy do we need to backport this? or is the 30-second ring delay sufficient?
