### ISSUE TITLE
CQL, batch statements, inserting a row with a null key column should be forbidden

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#12060]
A similar problem was raised in [this issue](https://github.com/scylladb/scylladb/issues/7852) for regular `INSERT` statements.

The query `cql.execute(f"BEGIN BATCH INSERT INTO {table1} (p,c) VALUES ('{s}', null);APPLY BATCH;")` produces `Invalid null value in condition for column p` on Cassandra but is silently ignored by Scylla.

The new test `test_insert_null_key_in_batch` demonstrates the issue.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1.
