### ISSUE TITLE
Node may abort if cache update fails in the middle

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#12068]
This can manifest as:

```
seastar/src/core/memory.cc:644: void seastar::memory::cpu_pages::free_span_no_merge(uint32_t, uint32_t): Assertion `nr_pages' failed.
Aborting on shard 0.
```

The reason is alloc-dealloc mismatch of position_in_partition objects allocated by cursors inside `coroutine` object stored in the `update` variable in `row_cache::do_update()`:

```
        utils::coroutine update; // Destroy before cleanup to release snapshots before invalidating.
```

It is allocated under cache region, but in case of exception it will be destroyed under the standard allocator. If update is successful, it will be cleared under region allocator, so there is not problem in the normal case.

**Comment by tgrabiec** [comment]
Also, there is no problem if clustering key is using the inline storage, so smaller than 16 bytes.

**Comment by mykaul** [comment]
Asking (a bit ahead of time, but I see a PR) - do we need to consider backporting this?

**Comment by avikivity** [comment]
Backported to 5.0, 5.1. 5.2 already has the fix.
