### ISSUE TITLE
Consistent schema updates

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#1207]
Scylla version (or git commit hash): 1.0

Schema changes are not linearizable, so concurrent updates may lead to inconsistent schemas (e.g., using a user type in one node while another concurrently delete the type, or two nodes concurrently creating a table with the same name).

The general guidance seems to be to perform schema updates always through the same node (shifting the consistency burden to the user). In Scylla's case, even this approach can lead to conflicting changes due to sharding, and that's why such updates need to be made under the merge lock.

Eventually we may want to support consistent schema updates across a cluster.

**Comment by alecco** [comment]
This is the same as Cassandra # 10250: Executing lots of schema alters concurrently can lead to dropped alters

When executing concurrent alter tables and indexing of a different table, some dropped columns show up afterwards even after waiting for 20 seconds to let schema changes settle.

This only happens without Raft enabled. Once Raft is enabled the issue goes away.

**Comment by dorlaor** [comment]
Isn't it time to close it or at least to link to the raft implementation in 5.0? @kostja

**Comment by kostja** [comment]
I believe the policy is to close these after going GA
