### ISSUE TITLE
Scylla aarch64 yum repository provides only 5.0.rc0 version

### ISSUE THREAD

**Issue by zoranosmanlic** [scylladb/scylladb#12075]
*Installation details*
Scylla version (or git commit hash):  5.0.5
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL

*Details*
Platform (physical/VM/cloud instance type/docker): AWS i4gen.4xlarge
URL: https://www.scylladb.com/download/?platform=rhel&version=scylla-5.0#open-source
PLATFORM: RHEL
VERSION: 5 (5.0.5)
ARCH: AARCH64
OS: Rocky Linux 8.4 aarch64 AMI

*Procedure from website*
sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo curl -o /etc/yum.repos.d/scylla.repo -L http://downloads.scylladb.com/rpm/centos/scylla-5.0.repo
sudo yum info scylla

yum info scylla
scylladb-5.0                                                                                                                                                                   9.2 kB/s |  20 kB     00:02    
scylladb-5.0-noarch                                                                                                                                                            7.5 kB/s |  15 kB     00:01    
Available Packages
Name         : scylla
Version      : 5.0.rc0
Release      : 0.20220204.da0cd2b10
Architecture : aarch64
Size         : 6.8 k
Source       : scylla-5.0.rc0-0.20220204.da0cd2b10.src.rpm
Repository   : scylladb-5.0
Summary      : Scylla is a highly scalable, eventually consistent, distributed, partitioned row DB.
URL          : http://www.scylladb.com/
License      : AGPLv3
Description  : Scylla is a highly scalable, eventually consistent, distributed,
             : partitioned row DB.
             : This package installs all required packages for ScyllaDB,  including
             : scylla-server, scylla-jmx, scylla-tools, scylla-tools-core scylla-node-exporter.

yum info scylla-5.0.5
Last metadata expiration check: 2:06:18 ago on Thu 24 Nov 2022 03:44:33 PM UTC.
Error: No matching Packages to list

*Expected*
installation of scylla 5.0.5

*Errors*
Wrong version is offered. - 5.0.rc0
Latest versions are not available.

**Comment by noellymedina** [comment]
cc. @DoronArazii

**Comment by benipeled** [comment]
@zoranosmanlic thanks for reporting this issue - please try now, it should work as expected 

```
[root@fd52658a252d yum.repos.d]# yum list --showduplicates "scylla"
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:00:04 ago on Thu Nov 24 18:19:07 2022.
Available Packages
scylla.aarch64                                                                                                                                   5.0.rc0-0.20220204.da0cd2b10                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.rc1-0.20220206.891990ec0                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.rc2-0.20220316.839d9ef41                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.rc3-0.20220406.f92622e0d                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.rc5-0.20220515.9da666e77                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.rc6-0.20220523.338edcc02                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.rc7-0.20220602.41a00c744                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.rc8-0.20220612.f28542a71                                                                                                                                   scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.0-0.20220628.c9e79cb4a                                                                                                                                     scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.1-0.20220719.b177dacd3                                                                                                                                     scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.2-0.20220807.299122e78                                                                                                                                     scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.3-0.20220907.b9a61c8e9                                                                                                                                     scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.4-0.20220921.1c82766f3                                                                                                                                     scylladb-5.0
scylla.aarch64                                                                                                                                   5.0.5-0.20221009.5a97a1060                                                                                                                                     scylladb-5.0
```

Fixed https://github.com/scylladb/scylla-pkg/pull/3132

**Comment by zoranosmanlic** [comment]
Thank you, it is working now!

yum clean metadata
yum info scylla-5.0.5
Available Packages
Name         : scylla
Version      : 5.0.5
Release      : 0.20221009.5a97a1060
Architecture : aarch64
Size         : 6.8 k
Source       : scylla-5.0.5-0.20221009.5a97a1060.src.rpm
Repository   : scylladb-5.0
Summary      : Scylla is a highly scalable, eventually consistent, distributed, partitioned row DB.
URL          : http://www.scylladb.com/
License      : AGPLv3
Description  : Scylla is a highly scalable, eventually consistent, distributed,
             : partitioned row DB.
             : This package installs all required packages for ScyllaDB,  including
             : scylla-server, scylla-jmx, scylla-tools, scylla-tools-core scylla-node-exporter.
