### ISSUE TITLE
storage_service: handle_state_normal: algorithm for detecting a replaced node is wrong and inefficient

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12082]
In https://github.com/scylladb/scylladb/blob/996eac9569fba1b08ae15e2533a158fd0d23b214/service/storage_service.cc#L953-L969

We try to detect a replaced node so to insert it to `endpoints_to_remove` when it has no owned tokens left.
However, *for each token* we first generate  a multimap using `get_endpoint_to_token_map_for_reading()`.
There are 2 problems with that:
1. unless the replaced node owns a single token, this map will not empty after erasing one token out of it, since the token metadata has not changed yet (this is done later with `update_normal_tokens(owned_tokens, endpoint)`)
2. generating this map for each token is inefficient, turning this algorithm complexity to quadratic in the number of tokens.

**Comment by bhalevy** [comment]
DTest that triggers this path is replace_address_test.py::TestReplaceAddress::test_replace_shutdown_node

**Comment by avikivity** [comment]
Not a bug, not backporting.

**Comment by bhalevy** [comment]
I think it is a bug, but I'm not sure how it is exposed or how to reproduce it.
So as a latent bug it doesn't merit backporting.
