### ISSUE TITLE
Raft tests: test that Raft IDs are not lost during restarts

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12083]
Copy-pasting from https://github.com/scylladb/scylladb/pull/11953#discussion_r1032624385

There's one very good reason why we MUST persist IP<->RAFT_ID mappings: remove_from_group0, which is used during removenode and replace operations.

The removenode and replace operations API are expressed in terms of IP and/or Host ID. To remove a server from group 0, we must translate the IP/HostID to the Raft ID - and in this case, the node is down, and there's no guarantee that its IP is available from gossiper.

For example, consider this scenario: we have 3 nodes A, B, C, we shutdown all of them, then restart A and B. We must be able to remove C from group 0. So we must be able to obtain C's Raft ID somehow, even though C is not gossiping.

^ this is a good candidate for a test.

Perhaps we should do even more: should we be re-gossiping the Raft IDs of other nodes? If in the future we allow bootstrapping with some nodes dead, for example - how would the bootstrapped node know the dead node's Raft IDs? Or maybe there is some possibility that C's Raft ID didn't manage to reach one of the nodes before C died?

**Comment by tgrabiec** [comment]
Refs https://github.com/scylladb/scylladb/issues/6088

**Comment by kbr-** [comment]
Test in the context of replace. Instead of just shutting down the node I want to replace, I shutdown all nodes and restart all except the one I want to replace.
https://github.com/kbr-/scylla/tree/test-raft-ids-preserved-restarts

aaaaand it doesn't work.
```
ERROR 2022-12-06 18:45:40,573 [shard 0] init - Startup failed: std::runtime_error (Cannot perform replace operation: Raft ID of the replaced server (IP: 127.18.219.1) is missing.)
```
so the Raft ID must've got lost by the restart.

Branch based on https://github.com/scylladb/scylladb/pull/12172

**Comment by kbr-** [comment]
Probably the best fix is just to go with https://github.com/scylladb/scylladb/issues/12204.
But we're stuck until https://github.com/scylladb/scylladb/pull/12084 is merged.

**Comment by kostja** [comment]
@kbr-scylla suggest to close. Would you like extra testing for host ids?
