### ISSUE TITLE
Multi-process docker container is against best practices

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#12093]
Our docker container runs the scylladb server, scylla-jmx, and contains the nodetool and cqlsh binaries. In addition it has a supervisor (supervisord) that checks if processes crashed and restarts them. This is against container best practices, which recommend minimal images, and delegate the supervision to a container manager (e.g. Kubernetes).

To fix this, we need to break apart our image into 4:

1. a minimal one with just scylla-server (no Java)
2. one with Java+jmx
3. one with Java+nodetool
4. one with cqlsh

We'd also need the original aggregated image for compatibility, at least for a while.

For naming, we can choose between tags and repositories to separate the different images.

Tags:
    docker.io/scylladb/scylla:{server,jmx,nodetool,cqlsh}-{version}

Repositories:
    docker.io/scylladb/scylla-{server,jmx,nodetool,cqlsh}:{version}

**Comment by avikivity** [comment]
/cc @tnozicka 

@syuu1228 do you want to pick this up?

**Comment by mykaul** [comment]
With a bit of luck, it'll also help us to move to distroless base image, such as https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md

**Comment by avikivity** [comment]
Oh, we'll also want a docker-compose.yaml so it's still easy to bring up a node.

**Comment by avikivity** [comment]
> With a bit of luck, it'll also help us to move to distroless base image, such as https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md

With relocatable packages, we're 98% of the way there.

**Comment by tzach** [comment]
Similar to https://github.com/scylladb/scylladb/issues/5307

**Comment by avikivity** [comment]
Closed as duplicate of #5307
