### ISSUE TITLE
cql transport server: report unhandled error as SERVER_ERROR to the client

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#12104]
If a `std::bad_alloc` exception occurred while parsing a large batch request, it's not properly reported to the client.

The exception was caught by try/catch in `cql_server::connection::process_request_one` and an attempt was made to construct the error response message via `make_error` function. This attempt failed since the error message contained entire query and exceeded the limit of `64K` in `cql_server::response::write_string`, causing `Value too large` exception to be thrown. This new exception reached the general handler in `cql_server::connection::process_request`, where it was just logged and no information about the problem was sent to the client. As a result, the client received a timeout exception after a while and no other information about the cause of the error.

**Comment by DoronArazii** [comment]
@gusev-p any updates here?

**Comment by gusev-p** [comment]
> @gusev-p any updates here?

the [PR](https://github.com/scylladb/scylladb/pull/11949) is ready, but got stuck on review. I'll get back to it in a week.

**Comment by mykaul** [comment]
Leaving it on 5.2 at the moment, hoping it'll get in and backported. If not, I'll move it to 5.3 in a week's time.

**Comment by DoronArazii** [comment]
@benipeled why there's no auto "backport candidate" here?

**Comment by benipeled** [comment]
The backport script is looking for the `Fixes` keyword only [0] while a4cf509 uses `Closes`

[0] r'Fixes:? (?:#|https://github.com/scylladb/scylla\w*/issues/)(\d+)'

**Comment by avikivity** [comment]
@gusev-p please use Fixes in the future.

**Comment by gusev-p** [comment]
> @gusev-p please use Fixes in the future.

ok

**Comment by avikivity** [comment]
Backported to 5.2. @gusev-p please prepare a backport to 5.1.

**Comment by gusev-p** [comment]
> Backported to 5.2. @gusev-p please prepare a backport to 5.1.

ok

**Comment by gusev-p** [comment]
> Backported to 5.2. @gusev-p please prepare a backport to 5.1.

https://github.com/scylladb/scylladb/pull/13303

**Comment by avikivity** [comment]
Backported to 5.1.
