### ISSUE TITLE
high latency during replace node operation with mixed workload

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#12101]
*Installation details*
Scylla version (or git commit hash): `Scylla Server Version: 5.2.0~dev.20221105.768d77d31b6e with build-id 31818162ae404f25877763c515a14214a03356a7`
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0d7c91b81d0530b15` (`eu-west-1`)

we saw an increased latency for this operation, and we agreed that we might have stalls during it, that may reflect the issue, hence i'm reporting here the result of `stall-analyser.py` during the replace node operation.
note in the beginning of attached log:
```
Processed 2675 stalls lasting a total of 24845 milliseconds.
min=6 avg=9.3 median=8 p95=15 p99=17 p999=19 max=19
```

[decoded_stalls.log](https://github.com/scylladb/scylladb/files/10099220/decoded_stalls.log)

for more details (like recreating monitor stack), `test_id: 2795f3eb-1b44-430d-909e-53a6477cd64e`

**Comment by fgelcer** [comment]
email subject of the report of this build is `[scylla-perf-results] Performance Regression Compare Results (latency during operations) - test_latency_mixed_with_nemesis - 5.2.0~dev.20221105.768d77d31b6e - 2022-11-06 05:38:43.579464`

**Comment by bhalevy** [comment]
Stalls look similar to thttps://github.com/scylladb/scylladb/issues/8942

**Comment by DoronArazii** [comment]
Bring back 'master/triage' as it was not taken yet by dev.
RBNO for 5.2 is questionable - then pushing to 5.3

/Cc @asias @mykaul

**Comment by dorlaor** [comment]
Replace node uses RBNO by default from quite some time already, it's not
relevant

**Comment by fgelcer** [comment]
> we are seeing it on our weekly runs (both old and new latency tests with operations), and it is not yet solved. if there is some requirement for extra information, we will gladly provide, but right of now, we consider it in our weekly performance meeting as a known issue, and we don't discuss it anymore.

for both master and enterprise branches

**Comment by DoronArazii** [comment]
@eliransin / @asias it's in your queue for 5.3?

**Comment by asias** [comment]
I mentioned here https://github.com/scylladb/scylladb/issues/13044#issuecomment-1482178808, we had the big latency spike due the the extra spike of writes after replace operation. It looks like the extra spike of writes was a decision of the loader. I am not looking the the client side issue. We need c-s / driver expert to take a look.

**Comment by mykaul** [comment]
> I mentioned here [#13044 (comment)](https://github.com/scylladb/scylladb/issues/13044#issuecomment-1482178808), we had the big latency spike due the the extra spike of writes after replace operation. It looks like the extra spike of writes was a decision of the loader. I am not looking the the client side issue. We need c-s / driver expert to take a look.

Were speculative retries perhaps were enabled?

**Comment by roydahan** [comment]
They are enabled and should be enabled for latency test according to Avi.
(We disabled only for throughput test).

We have now 3 issues for the same problem and there are relevant comments in all of them. 
We need to unify the work somehow and track only one.
It can be this one.

@asias if you think someone else should join this or take over, please ping someone.

**Comment by mykaul** [comment]
> They are enabled and should be enabled for latency test according to Avi. (We disabled only for throughput test).

Agreed, but they can explain the rise in (attempted?) writes. There should be metrics for it, I believe.

> 
> We have now 3 issues for the same problem and there are relevant comments in all of them. We need to unify the work somehow and track only one. It can be this one.

Yes, please keep the most relevant ones, with links to relevant comments in the others - if needed, and close the rest. They are not useful.

> 
> @asias if you think someone else should join this or take over, please ping someone.

**Comment by asias** [comment]
> They are enabled and should be enabled for latency test according to Avi. (We disabled only for throughput test).
> 
> We have now 3 issues for the same problem and there are relevant comments in all of them. We need to unify the work somehow and track only one. It can be this one.
> 
> @asias if you think someone else should join this or take over, please ping someone.

I do think someone should look at it. I am not sure who. We do not have an official owner of the c-s tool. 

@eliransin  FYI.

**Comment by eliransin** [comment]
@piodul this is probably a dup of #13160 and is suspected to be a client side issue, or at least client side triggered (driver?)

**Comment by piodul** [comment]
> @piodul this is probably a dup of #13160 and is suspected to be a client side issue, or at least client side triggered (driver?)

Yes, looks like this is a duplicate. Decoded stalls look similar, c-s latency as well, and I think the analysis from https://github.com/scylladb/scylladb/issues/13160#issuecomment-1592896569 also applies. I'm closing this issue and will continue on the other one.
