### ISSUE TITLE
raft: replace should be possible in RECOVERY mode

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12114]
We should test that replace is possible in `group_upgrade_state=RECOVERY` mode. removenode is possible (it must be), then why not replace?

This may be problematic. The new replacing node must enter RECOVERY too. But currently the only way to enter RECOVERY is through CQL, and CQL only becomes available after the node finishes bootstrapping.
Perhaps we should allow entering RECOVERY through configuration as well.

An alternative would be for the replacing/bootstrapping node to enter RECOVERY if it sees that one of the existing nodes is in RECOVERY. This would actually be very easy, because a bootstrapping node already retrieves the `group0_upgrade_state` of other nodes during bootstrap.

**Comment by kostja** [comment]
No we should not. Please provide a rationale.

**Comment by kbr-** [comment]
The rationale is the same as for having the replace operation at all.

Why do we have it? Perhaps don't strictly need it, because you could remove the node then bootstrap a new one and you get the same result.

The replace operation is there so you can make the procedure 2 times shorter: you bootstrap and remove at the same time, so you can replace a node in say 10 hours instead of 20.
Perhaps it's even required in some situations, where removing a node would cause us to run out of disk space, so we must replace that node instead?

Same considerations apply during the RECOVERY procedure. The purpose of RECOVERY is to be able to remove a node in situations where group 0 is unavailable. But often you don't want to end up with fewer nodes, you want to end up with the same number of nodes, so you want to replace really.

So the question is, can we always simulate replace with remove followed with a bootstrap, or are there situations where we *must* replace? If there are such situations (e.g. removing instead of replacing would have us run out of disk space), then we must always be able to replace.

**Comment by kostja** [comment]
"But often you don't want to end up with fewer nodes, you want to end up with the same number of nodes, so you want to replace really." - do you have any data on that or it's a guess?
Besides, what is the impact of just adding a new node to an upgraded cluster?
Generally, github issue is not best forum for discussions around motivation. Why not create a feature request following the feature request template and settle the priority of this feature there?

**Comment by kbr-scylla** [comment]
We're working on a different approach, where this won't be necessary https://github.com/scylladb/scylladb/issues/18791 (cc @patjed41)

closing this issue.
