### ISSUE TITLE
Document Scylla total schema size limit

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#12133]
The total binary footprint of all scylla columns, tables, etc. must fit a single commit log size segment divided by two. We don't seem to list this limitation anywhere in the docs.

**Comment by kostja** [comment]
It's a scylla.yaml parameter. 
BTW, another matter that all nodes in the cluster should have the same value of this parameter, otherwise the cluster will break (the nodes with smaller commit log segment size in mb won't be able to talk with the nodes with the larger segment size). So when it's changed, it should be changed on all nodes. We don't document it either.

In other words, @mykaul it's a pretty fundamental limit and it normally stays the same throughout cluster's life since the cluster is created. Maybe there is a metric, but I don't think one should go anywhere beyond scylla.yaml to find it out.

**Comment by nyh** [comment]
> The total binary footprint of all scylla columns, tables, etc. must fit a single commit log size segment divided by two. We don't seem to list this limitation anywhere in the docs.

@kostja can you explain this "must"? What causes this requirement? You listed this as a documentation issue but do we have another issue on fixing this requirement - not just documenting it?

**Comment by kostja** [comment]
> causes this requirement? You listed this as a documentation issue but do we have another issue on fixing this requirement - not just d

We write it as a single batch to the commit log when shipping the schema over today. There is a PRD document for various alternatives of alleviating this limit: 
https://docs.google.com/document/d/1MZQkuPSYUhkTRmdNCrGeTI5jPR7ZMec9fQHvPl_OZY0/edit

It is not planned.

Between all the alternatives, I think the way to go nowadays is to use Kamil's design for snapshot transfer of Raft based tables, and stop using the migration manager implementation which fetches all the existing mutations and sends them over:
https://docs.google.com/document/d/1K2qf2iszC0ozgEBhuY2Cue0OKlsehNwbY-GVVQC8lag/edit

It is not planned either, that is, it is planned after the new topology change coordinator is finished, which is after 5.3.

**Comment by annastuchlik** [comment]
I'm going to document it in two places:
- The newly created Known Limitations page
- The Troubleshooting page (what to do if a cluster is unable to sync schema).

@kostja Is there another place where the user might need that information?

**Comment by denesb** [comment]
Documentation change, not backporting.
