### ISSUE TITLE
documentation: document which repair modes we really support

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12132]
https://docs.scylladb.com/stable/operating-scylla/nodetool-commands/repair.html 

suggests that we have an option to do "sequential repair". As noted long ago in issues #210 and #2084, we don't actually support the concept of "sequential repair", never did, and probably (see #210) never will. So we shouldn't claim that such an option exists and "explain" what it does.

@asias maybe you can take a look if there are other discrepancies between the options described in that document and what Scylla and nodetool actually support? Maybe there are more options we document but don't support, or on the contrary - options which we support but don't document?

CC @asias @annastuchlik

**Comment by tzach** [comment]
@asias ping

**Comment by asias** [comment]
No. We do not and will not support sequential repair. We should drop it from our doc.

**Comment by mykaul** [comment]
@annastuchlik - can you please remove that part?

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. 5.0 is too old to care about documentation now.

**Comment by bhalevy** [comment]
It would have been better to document that we do not support it (and merely ignore it at the moment), than to omit it entirely from the documentation, since it's an incompatibility with Cassandra's nodetool repair that we to explain and warn users about.

**Comment by annastuchlik** [comment]
@bhalevy As a rule, we should document what is supported rather than what is not, but I see your point.
The information seems to fit this section of the Cassandra Compatibility page: https://opensource.docs.scylladb.com/master/using-scylla/cassandra-compatibility.html#repair-and-consistency
I could add a note that the `-seq, --sequential` option is not supported. What do you think?

**Comment by bhalevy** [comment]
I believe we also don't support `-j --jobs`.

Maybe we need a section about repair parallelism and explain how it depends on the given range(s).
There, we can mention the non-supoort of the legacy options and reger to the Cassandra compatibility page.
