### ISSUE TITLE
storage_proxy::schedule_repair transfers endpoints accross topologies

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#12136]
The schedule_repair() accepts `std::unordered_map<dht::token, std::unordered_map<gms::inet_address, std::optional<mutation>>>` and inet_addresses in this nested map were obtained from erm earlier, when proxy created response handler for it. When the schedule_repair() fiber runs it calls mutate_internal() which calls mutate_prepare() which grabs erm from scratch and tries to resolve endpoints from new topology

**Comment by xemul** [comment]
Cc @bhalevy

**Comment by avikivity** [comment]
Why not carry the erm? This is just a read repair, so nobody gets hurt if we extend the life of the topology a little.

**Comment by bhalevy** [comment]
> Why not carry the erm? This is just a read repair, so nobody gets hurt if we extend the life of the topology a little.

Yes, in this case I think this is the right way.
The discussion about other solution that could be used instead of varrying endpoints where carrying the erm is undesirable.

**Comment by bhalevy** [comment]
ping @xemul

**Comment by xemul** [comment]
Yikes. It was fixed by https://github.com/scylladb/scylladb/pull/12256 but wrong  fixes: tag was there
