### ISSUE TITLE
Scylla setup should set net.ipv4.tcp_timestamps=1 (or just warn if it isn't set as such)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#12144]
In newer OS, this is the default, but in some older ones, it isn't, and it may cause rpc hangs.
Scylla systemd unit or some other startup script should warn if it is not set to '1'.

**Comment by nyh** [comment]
@mykaul I suggest that Scylla itself can check this setting on boot and refuse to boot. We already have similar tests in main.cc like tcp_syncookies (although in that particular case we just warn, not refuse to boot). I don't think we should rely on external scripts for Scylla to protect itself. It can also be a good place in Scylla to insert a comment on why this flag is needed.

@gleb-cloudius can you please give here some context on why this flag is important to RPC?

**Comment by gleb-cloudius** [comment]
On Wed, Nov 30, 2022 at 02:27:07AM -0800, nyh wrote:
> @gleb-cloudius can you please give here some context on why this flag is important to RPC?
> 

I is not important to RPC specifically. It makes tcp behave bad in
presents of a lot of packet drops.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
> On Wed, Nov 30, 2022 at 02:27:07AM -0800, nyh wrote: @gleb-cloudius can you please give here some context on why this flag is important to RPC?
> I is not important to RPC specifically. It makes tcp behave bad in presents of a lot of packet drops.

And that is why it would be weird to require it to be set. There are people out there with networking HW that actually works.

**Comment by nyh** [comment]
So we don't need to require it to be set. We can do what we do in main.cc for tcp_syncookies, namely, just warn if this flag is off, warning the user that it may cause packet loss and therefore bad performance.

If there are people who deliberately set this flag to 0 and still get good performance, then I agree - we shouldn't even warn about it, and let's close this issue. But I have no idea if that's the case. I got the opposite impression from you in the old discussion we had on the topic, but maybe I just misunderstood.

**Comment by gleb-cloudius** [comment]
Without packet drops the feature is irrelevant. IMO we do need to force it to 1 because believe me you do not want to debug it once again when we will have the rare case of an installation where there will be packet drops and the knob with be 0.

**Comment by avikivity** [comment]
We have https://github.com/scylladb/scylladb/tree/master/dist/common/sysctl.d. Note it won't help with containers.
