### ISSUE TITLE
alternator expiration service hangs on shutdown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12145]
Seen in debug mode on all nodes, e.g. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/102/artifact/logs-full.debug.030/1669790745426_alternator_ttl_tests.py%3A%3ATestAlternatorTTL%3A%3Atest_ttl_with_load_and_decommission/node1.log
```
Scylla version 5.2.0~dev-0.20221130.8bc0af9e34fa with build-id f5d2fb8e06735745b0f4c1cac0b783857efd800c starting ...

INFO  2022-11-30 05:55:38,903 [shard 0] init - Shutting down repair
INFO  2022-11-30 05:55:38,903 [shard 0] init - Shutting down repair was successful
INFO  2022-11-30 05:55:38,903 [shard 0] init - Shutting down expiration service
WARN  2022-11-30 05:55:46,356 [shard 0] alternator_ttl - expiration scanner read timed out, will retry: exceptions::read_timeout_exception (Operation timed out for alternator_user_table.user_table - received only 0 responses from 2 CL=LOCAL_QUORUM.)
...
```

`expiration scanner read timed out` message repeats until the test kills the node to get a coredump.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/102/artifact/logs-full.debug.030/1669790745426_alternator_ttl_tests.py%3A%3ATestAlternatorTTL%3A%3Atest_ttl_with_load_and_decommission/node1-scylla.720.1669788332.core.gz

**Comment by nyh** [comment]
@nuivall you were right, and infinite repeat was not a great idea. If we had a limited number (e.g., 10) this would have worked like before - just take a long time to shutdown (which is not a big problem for dtest).

But what will be even better is to stop the retry loop immediately if a shutdown was requested. I'll check how to do that and prepare a patch.

**Comment by nuivall** [comment]
Stopping on shutdown looks a bit a similar to stopping on another ttl scan execution (i.e.  current is stuck >= 24 hours), perhaps the patch can handle both (unless this is already done)?

**Comment by nyh** [comment]
@nuivall the code is already written as a loop whose very inner part has:
```c++
if (abort_source.abort_requested()) {
            co_return;
}
```

So whenever a shutdown is requested, it stops whatever scan it is currently on. But it stops between scan pages - an individual page, including the new even-more-inner-loop, can still hang. I need to move the check into the even-more-inner loop.
I'll send a patch in a few minutes.

**Comment by bhalevy** [comment]
Apparently this was introduced by 1e59c3f9ef4c89b32d7c70db17ca01b6a3c8d05e (in 5.2 time frame)
which was backported to branch-2022.2.  I'm not sure why not to 5.1

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
