### ISSUE TITLE
Clean up deprecation warnings on new seastar::http namespace

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12142]
Recently @xemul added to Seastar a new HTTP client implementation, and in the process moved around some of the HTTP **server** classes to a more neutral namespace to be shared between server and client classes. The old names were deprecated. This currently causes Scylla's compilation to give off dozens of warnings like:

```
alternator/server.hh:80:78: warning: 'request' is deprecated: Use http::request instead [-Wdeprecated-declarations]
```

We should update the Scylla code to use the new namespace and avoid these deprecation warnings.

**Comment by avikivity** [comment]
Not a bug, not backporting.
