### ISSUE TITLE
raft: test that group 0 snapshotting works

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12146]
The state machine is snapshotted after certain thresholds, group 0 uses the defaults specified in raft/server.hh:
```cpp
    struct configuration {
        // automatically snapshot state machine after applying
        // this number of entries
        size_t snapshot_threshold = 1024;
        // Automatically snapshot state machine if the log memory usage exceeds this value.
        // The value is in bytes.
        // Must be smaller than max_log_size.
        // It is recommended to set this value to no more than half of the max_log_size,
        // so that snapshots are taken in advance and there is no backpressure due to max_log_size.
        size_t snapshot_threshold_log_size = 2 * 1024 * 1024;
```

AFAIU we currently have no tests which would perform a sufficient number of schema changes for a snapshot to be created, and it would be best to test multiple snapshots with restarts/crashes in between.

We could:
- perform thousands of schema changes - with restarting/crashing nemesis in between - but that would be a long test (perhaps not fit for test.py), or
- reduce the snapshot thresholds using a config variable (hidden to the user, for testing only) or an error injection, so we can write a shorter test (still we want to see many snapshots happen on different nodes).

**Comment by kbr-scylla** [comment]
PR by @alecco: https://github.com/scylladb/scylladb/pull/12726

**Comment by kbr-scylla** [comment]
Closing since https://github.com/scylladb/scylladb/pull/12726 was merged
