### ISSUE TITLE
Alternator: a better, and rack-aware, /localnodes request

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12147]
We have in Alternator a "/localnodes" request which returns the list of live nodes on the same data-center as the node receiving this request. It was meant to be used by an application (or load balancer) that wants to know where to send DynamoDB API requests.

However, this "/localnodes" feature has two problems that this issue proposes to fix:
1. The "/localnodes" feature is not rack-aware. In a multi-rack setup (e.g., availability zones in EC2) an application might want to send requests not to a random node in its entire DC - but to a random node **only in its rack**, to avoid extra inter-rack networking costs. We would like to have a request that lists the live nodes in a specific rack - not in the entire dc.
2. "/localnodes" currently inquires about the DC of the Scylla node being contacted. It requires the application to first know the IP address of some Scylla node in this DC. Where does it get this initial information? It's even harder to get this information when we get down to the level of a single rack. It seems easier to assume that we know of one node anywhere in the cluster no matter in which dc and rack (perhaps via some DNS setup), and ask it about the members of a specific named DC and rack which it isn't necessarily part of.

What I propose is to add to the "/localnodes" request the options "dc=" and optionally "rack=" where the requester can ask for a DC and rack with a specific name, and get the known live nodes on this dc and rack.

What I have in mind is that on EC2 for example, Scylla setups would use region and AZ names as dc and rack names (respectively), so that an application that knows that it is running in a certain region and certain AZ can ask _any_ Scylla nodes to get the list of live Scylla nodes in this specific dc and rack.

CC @amnonh

**Comment by mykaul** [comment]
@ptrsmrn - can you prioritize it? We get customer asks for it.

**Comment by ptrsmrn** [comment]
> @ptrsmrn - can you prioritize it? We get customer asks for it.

@mykaul is Q4'24 OK? CC @kostja

**Comment by nyh** [comment]
> @mykaul is Q4'24 OK? CC @kostja

Please note that we'll also need to consider how this new API will be used in the load-balancing library - see https://github.com/scylladb/alternator-load-balancing/issues/31.

**Comment by mykaul** [comment]
> > @mykaul is Q4'24 OK? CC @kostja
> 
> Please note that we'll also need to consider how this new API will be used in the load-balancing library - see [scylladb/alternator-load-balancing#31](https://github.com/scylladb/alternator-load-balancing/issues/31).

Yes, that's the end goal - but this is the 1st step, no? Extend the API with parameters.

**Comment by mykaul** [comment]
> > @ptrsmrn - can you prioritize it? We get customer asks for it.
> 
> @mykaul is Q4'24 OK? CC @kostja

I had hoped it's 1 day of work. half a day to extend the API and half a day to write a test for it. Perhaps I'm over-simplifying things here. I've looked at local_nodelist_handler() only, perhaps there's more to it.

**Comment by mykaul** [comment]
> > > @ptrsmrn - can you prioritize it? We get customer asks for it.
> > 
> > 
> > @mykaul is Q4'24 OK? CC @kostja
> 
> I had hoped it's 1 day of work. half a day to extend the API and half a day to write a test for it. Perhaps I'm over-simplifying things here. I've looked at `local_nodelist_handler()` only, perhaps there's more to it.

@ptrsmrn, @kostja - any updates?

**Comment by ptrsmrn** [comment]
@mykaul No updates. Though this effort was scheduled for Q4, we're still busy with items carried over from Q3. Should this be given a higher priority?

**Comment by mykaul** [comment]
> @mykaul No updates. Though this effort was scheduled for Q4, we're still busy with items carried over from Q3. Should this be given a higher priority?

If, as I suspect, it takes a day to complete, then yes please.

**Comment by nyh** [comment]
I want to take a stab at this so assigning to myself. If for some reason I don't complete it today, then we can go back to the planning for Q4.

**Comment by mykaul** [comment]
> I want to take a stab at this so assigning to myself. If for some reason I don't complete it today, then we can go back to the planning for Q4.

Go ahead.

**Comment by nyh** [comment]
Created a pull request https://github.com/scylladb/scylladb/pull/20915 implementing exactly what I proposed in the original issue (note this is only the server side, we still need to do something in the client side that uses it, like https://github.com/scylladb/alternator-load-balancing/issues/31).
