### ISSUE TITLE
raft: test that there's no leftovers in group 0 after remove/replace procedures

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12153]
With Raft enabled, removenode, decommission and replace operations must remove the node from group 0, additionally to removing its tokens from the token ring. Without Raft-coordinated topology operations it's not possible to handle failures correctly (see https://github.com/scylladb/scylladb/issues/11723#issuecomment-1332301558). But we can at least test that we don't leave any garbage in group 0 members in the happy path. And maybe write some failing tests with error injections to show that we indeed don't handle failures correctly yet.

Such remaining group 0 members that correspond to removed nodes will decrease group 0's availability.

We could either write dedicated tests for this, or always check it in topology test framework's teardown phase so the check runs after every topology test.

BTW. perhaps we should start these operations with becoming non-voter? but then we'll remain a non-voter if the operation fails... but maybe that's better than what we have now? We could also become a non-voter after streaming finishes, but before we remove the tokens. At this moment, the probability of failure is very low.

**Comment by kbr-** [comment]
To do this we may need additional APIs for querying the state of group 0.

**Comment by kostja** [comment]
I believe Raft configuration is already easy to query from Raft system tables. It is fine to use these in an internal test.

**Comment by kbr-** [comment]
> I believe Raft configuration is already easy to query from Raft system tables.

Only the configuration from the last snapshot. It is stored in `system.raft_config` (btw. the name could be better to disambiguate that it is the snapshot config). To query the latest configuration, one would have to deserialize log entries stored in a binary blob format in `system.raft` and iterate over them to find the last config entry (and take the snapshot one only if a config entry is not found there).

**Comment by kbr-scylla** [comment]
This is now easy to do with the new `system.raft_config` virtual table (the old `system.raft_config` table was renamed) introduced in https://github.com/scylladb/scylladb/pull/12502

There's an example test which does this. We can copy the verification step from this test to other tests.

**Comment by avikivity** [comment]
@kbr- please evaluate for backport.

**Comment by kbr-scylla** [comment]
Just a bit of extra testing that's already running no the `master` branch (and didn't catch any problem with the existing code), I think there's no need to backport.
