### ISSUE TITLE
raft: API for manual maintenance of group 0?

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12154]
Without Raft-based topology changes it is not possible to correctly handle failures during e.g. node removal operations. As the code is written now, we might end up with a member of group 0 that is not a member of the token ring (see https://github.com/scylladb/scylladb/issues/11723#issuecomment-1332301558).

One way to deal with such failures would be to have a manual API for group 0 maintenance. There is the RECOVERY mode for establishing group 0 from scratch, but sometimes it might be overkill. Suppose for example we had 3 nodes A, B, C, and C was removed from the token ring, but the removal procedure failed on `remove_from_group0`. Still, group 0 is available and the API could be used to send a manual request to remove the leftover from group 0. The user would only have to find the Raft ID of the leftover member (which is easy - find the Raft IDs of A and B, remove everything else).

**Comment by kostja** [comment]
I suggest this is closed as "Won't fix". We're solving the failed removenode differently now.

**Comment by kostja** [comment]
@kbr-scylla please close if you agree.

**Comment by kbr-scylla** [comment]
https://github.com/scylladb/scylladb/pull/12502 includes the ability to query group 0, and makes it possible to clean up group 0 with `removenode`.
