### ISSUE TITLE
AzureSnitch failing to select a rack

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#12185]
```
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 0] init - creating snitch
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 0] snitch_logger - AzureSnitch using region: eastus, zone: .
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 3] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 4] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 2] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 1] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 6] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
Dec 03 06:39:09 longevity-10gb-3h-master-db-node-eastus-1 scylla[32070]:  [shard 5] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
```

this lead to gossip info having no rack:

```
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG > /10.0.0.10
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   generation:1670050929
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   heartbeat:3267
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   RPC_ADDRESS:10.0.0.10
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X6:7
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   LOAD:1.29175e+09
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X5:0:895903334:1670051017988
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   STATUS:NORMAL,690453247408654047
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X9:org.apache.cassandra.locator.AzureSnitch
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X3:3
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X8:v2;1670051045494;b3cc616a-e930-4fa7-b1da-181bef7712e3
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   HOST_ID:eccc0553-3929-41a0-9f3b-c4eea871c466
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X4:1
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   SCHEMA:e511791e-8453-3d7c-9a4b-52833ed9f296
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   RACK:
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X2:system_distributed.cdc_generation_timestamps:0.000000;system_traces.sessions:0.000000;keyspace1.standard1:1.000000;system_traces.node_slow_log_time_idx:0.000000;system_traces.sessions_time_idx:0.000000;system_auth.role_attributes:0.000000;system_traces.events:0.000000;system_distributed_everywhere.cdc_generation_descriptions_v2:0.000000;system_distributed.view_build_status:0.000000;system_distributed.service_levels:1.000000;system_distributed.cdc_streams_descriptions_v2:0.000000;system_auth.role_members:0.000000;system_auth.roles:1.000000;system_traces.node_slow_log:0.000000;
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X7:12
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   DC:eastus
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   RELEASE_VERSION:3.0.8
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   NET_VERSION:0
< t:2022-12-03 07:53:48,718 f:cluster.py      l:2709 c:sdcm.cluster         p:DEBUG >   X1:AGGREGATE_STORAGE_OPTIONS,ALTERNATOR_STREAMS,ALTERNATOR_TTL,CDC,CDC_GENERATIONS_V2,COLLECTION_INDEXING,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_FOR_NULL_VALUES,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,EMPTY_REPLICA_PAGES,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,KEYSPACE_STORAGE_OPTIONS,LARGE_COLLECTION_DETECTION,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,MD_SSTABLE_FORMAT,ME_SSTABLE_FORMAT,NONFROZEN_UDTS,PARALLELIZED_AGGREGATION,PER_TABLE_CACHING,PER_TABLE_PARTITIONERS,RANGE_SCAN_DATA_VARIANT,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_COMMITLOG,SCHEMA_TABLES_V3,SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT,STREAM_WITH_RPC_STREAM,TOMBSTONE_GC_OPTIONS,TRUNCATION_TABLE,TYPED_ERRORS_IN_READ_RPC,UDA,UDA_NATIVE_PARALLELIZED_AGGREGATION,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WRITE_FAILURE_REPLY,XXHASH
```

and drivers ignoring those hosts:
```
< t:2022-12-03 07:56:52,291 f:cluster.py      l:3330 c:cassandra.pool       p:DEBUG > Host 10.0.0.5:9042 is now marked up
< t:2022-12-03 07:56:52,291 f:cluster.py      l:3330 c:cassandra.pool       p:DEBUG > Host 10.0.0.6:9042 is now marked up
< t:2022-12-03 07:56:52,291 f:cluster.py      l:3330 c:cassandra.pool       p:DEBUG > Host 10.0.0.7:9042 is now marked up
< t:2022-12-03 07:56:52,291 f:cluster.py      l:3330 c:cassandra.pool       p:DEBUG > Host 10.0.0.8:9042 is now marked up
< t:2022-12-03 07:56:52,291 f:cluster.py      l:3330 c:cassandra.pool       p:DEBUG > Host 10.0.0.9:9042 is now marked up
< t:2022-12-03 07:56:52,292 f:cluster.py      l:3330 c:cassandra.pool       p:DEBUG > Host 10.0.0.10:9042 is now marked up
< t:2022-12-03 07:56:52,292 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Opening new connection to 10.0.0.6:9042
< t:2022-12-03 07:56:52,296 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Established new connection <LibevConnection(139820654753584) 10.0.0.6:9042>, registering watchers and refreshing schema and topology
< t:2022-12-03 07:56:52,306 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Refreshing node list and token map using preloaded results
< t:2022-12-03 07:56:52,307 f:cluster.py      l:3330 c:cassandra.cluster    p:WARNING > Found an invalid row for peer (10.0.0.5). Ignoring host.
< t:2022-12-03 07:56:52,307 f:cluster.py      l:3330 c:cassandra.cluster    p:WARNING > Found an invalid row for peer (10.0.0.9). Ignoring host.
< t:2022-12-03 07:56:52,307 f:cluster.py      l:3330 c:cassandra.cluster    p:WARNING > Found an invalid row for peer (10.0.0.10). Ignoring host.
< t:2022-12-03 07:56:52,307 f:cluster.py      l:3330 c:cassandra.cluster    p:WARNING > Found an invalid row for peer (10.0.0.7). Ignoring host.
< t:2022-12-03 07:56:52,308 f:cluster.py      l:3330 c:cassandra.cluster    p:WARNING > Found an invalid row for peer (10.0.0.8). Ignoring host.
< t:2022-12-03 07:56:52,308 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 10.0.0.5:9042>
< t:2022-12-03 07:56:52,308 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 10.0.0.6:9042 eastus>
< t:2022-12-03 07:56:52,308 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 10.0.0.7:9042>
< t:2022-12-03 07:56:52,308 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 10.0.0.8:9042>
< t:2022-12-03 07:56:52,308 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 10.0.0.9:9042>
< t:2022-12-03 07:56:52,308 f:cluster.py      l:3330 c:cassandra.cluster    p:DEBUG > [control connection] Removing host not found in peers metadata: <Host: 10.0.0.10:9042>
```

## Installation details

Kernel Version: 5.15.0-1023-azure
Scylla version (or git commit hash): `5.2.0~dev-20221203.1a6bf2e9ca02` with build-id `68462c978ff36fe6852b5957b71920bc0246832e`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-8 (20.231.103.190 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-7 (20.106.157.248 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-6 (20.25.83.20 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-5 (20.25.83.3 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-4 (20.25.82.232 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-3 (20.25.82.29 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-2 (20.25.81.212 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-0e8d5a5b-eastus-1 (20.25.81.152 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.0-dev-x86_64-2022-12-03T07-54-37` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `0e8d5a5b-47ff-440f-adff-463c8c508574`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/03d131e85932283f0936a548d98598480dd94540/test-cases/longevity/longevity-10gb-3h.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0e8d5a5b-47ff-440f-adff-463c8c508574`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0e8d5a5b-47ff-440f-adff-463c8c508574)
- Show all stored logs command: `$ hydra investigate show-logs 0e8d5a5b-47ff-440f-adff-463c8c508574`

## Logs:
- **db-cluster-0e8d5a5b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/db-cluster-0e8d5a5b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/db-cluster-0e8d5a5b.tar.gz)
- **monitor-set-0e8d5a5b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/monitor-set-0e8d5a5b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/monitor-set-0e8d5a5b.tar.gz)
- **loader-set-0e8d5a5b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/loader-set-0e8d5a5b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/loader-set-0e8d5a5b.tar.gz)
- **sct-runner-0e8d5a5b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/sct-runner-0e8d5a5b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/sct-runner-0e8d5a5b.tar.gz)
- **parallel-timelines-report-0e8d5a5b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/parallel-timelines-report-0e8d5a5b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0e8d5a5b-47ff-440f-adff-463c8c508574/20221203_111400/parallel-timelines-report-0e8d5a5b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/134/)

**Comment by xemul** [comment]
This is what API call returned:
```
[shard 0] snitch_logger - AzureSnitch using region: eastus, zone: .
```

Zones are not supported everywhere (https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support (but maybe there's no regions outside of this list :shrug: )), so it looks a valid response from the IMDS

**Comment by avikivity** [comment]
But, eastus does support zones according to that link.

**Comment by fruch** [comment]
@xemul question is why `UNKNOWN_RACK` doesn't propagate to gossip, or it shouldn't ?

**Comment by xemul** [comment]
> 

Because empty zone is set as is into shard-0 rack. On non-0 shards it's replaced with UNKNOWN_RACK string

**Comment by fruch** [comment]
> > But, eastus does support zones according to that link.
> 
> It does, but my point is that empty zone is valid response from IMDS call. Whether or not this particular instance had to have it is question number two.
> 
> @fruch , is there any way to get (back?) to the faulty node via ... ssh?

no there isn't, the only thing I can say it happen on all 6 nodes when it did.

I would recommend adding enough logs for what is the whole response (header and all) are it's empty.

**Comment by xemul** [comment]
> I would recommend adding enough logs for what is the whole response (header and all) are it's empty.

Good suggestion, but I would only add it under TRACE level. Would it be possible to re-run the test with `--logger-log-level snitch_logger=trace` option?

**Comment by fruch** [comment]
> > I would recommend adding enough logs for what is the whole response (header and all) are it's empty.
> 
> Good suggestion, but I would only add it under TRACE level. Would it be possible to re-run the test with `--logger-log-level snitch_logger=trace` option?

we could, but this specific situation I don't have a way to recreate

**Comment by bhalevy** [comment]
@xemul what's the next step? should we wait for reproduction with fe4cf231bc2e09276a2b0cbc235d198c1a580a13?

**Comment by xemul** [comment]
I think it won't reproduce with this patch, but I've one more relevant patch to submit

**Comment by soyacz** [comment]
The reason of not having az might be that we don't set az value in SCT tests. We do it to have higher chance of getting resources and not failing the tests (still we have to use spot instances only as we cannot buy on demand yet).

**Comment by avikivity** [comment]
@xemul please backport if needed, it was closed manually so I can't easily trace the commits.

**Comment by xemul** [comment]
Done

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
