### ISSUE TITLE
db::view::row_locker lock functions may leak operations_currently_waiting_for_lock on failure

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12190]
operations_currently_waiting_for_lock is incremented unconditionally, e.g. in
https://github.com/scylladb/scylladb/blob/b551cd254c6daf07014267950fcdd17aaf19acf0/db/view/row_locking.cc#L60
but decremented only on success:
https://github.com/scylladb/scylladb/blob/b551cd254c6daf07014267950fcdd17aaf19acf0/db/view/row_locking.cc#L71

**Comment by avikivity** [comment]
@bhalevy please advise on backport, it's confusing since the commit points at "add latency_tracker".

**Comment by bhalevy** [comment]
@avikivity the issue is minor, affecting only metrics so it doesn't warrant backport by itself.

**Comment by avikivity** [comment]
What does "may leak operations" mean?

**Comment by bhalevy** [comment]
It's "may leak operations_currently_waiting_for_lock" which is a member of lock_stats, that is part of the
column_family metrics:
```c++
            _metrics.add_group("column_family", {
                ms::make_total_operations(format("row_lock_{}_acquisitions", stat_name), stats.lock_acquisitions, ms::description(format("Row lock acquisitions for {} lock", stat_name)))(cf)(ks).set_skip_when_empty(),
                ms::make_queue_length(format("row_lock_{}_operations_currently_waiting_for_lock", stat_name), stats.operations_currently_waiting_for_lock, ms::description(format("Operations currently waiting for {} lock", stat_name)))(cf)(ks),
                ms::make_histogram(format("row_lock_{}_waiting_time", stat_name), ms::description(format("Histogram representing time that operations spent on waiting for {} lock", stat_name)),
                        [&stats] {return to_metrics_histogram(stats.estimated_waiting_for_lock);})(cf)(ks).aggregate({seastar::metrics::shard_label}).set_skip_when_empty()
            });
```

By "leak" I meant that there is an imbalance where the counter is increment unconditionally and decremented only on success, hence it is "leaked" on failure.

**Comment by avikivity** [comment]
Ah, ok. I'll update the subject.

**Comment by avikivity** [comment]
Not backporting as it's only metrics.
