### ISSUE TITLE
raft: reuse Host ID as Raft ID

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12204]
This will be possible when https://github.com/scylladb/scylladb/pull/12084 is merged.

It will simplify things A LOT.

**Comment by mykaul** [comment]
Optimistically targeting to 5.2, adding 'high' label based on the 'A LOT' comment

**Comment by kbr-** [comment]
Pretty simple actually: https://github.com/kbr-/scylla/tree/host-id-as-raft-id
Based on Benny's PR. It will also require rebasing once my replace-fix PR is merged.

**Comment by kostja** [comment]
* Kamil Braun ***@***.***> [22/12/06 18:56]:
> Pretty simple actually: https://github.com/kbr-/scylla/tree/host-id-as-raft-id
> Based on Benny's PR. It will also require rebasing once my
> replace-fix PR is merged.

Awesome!


-- 
Konstantin Osipov, Moscow, Russia

**Comment by avikivity** [comment]
Enhancement, not issue. Luckily 5.1 raft is experimental and we need not support upgrades.
