### ISSUE TITLE
raft: optimize loading persisted RAFT_SERVER_IDs on startup

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12205]
In https://github.com/scylladb/scylladb/pull/12035 we persist, and then load peers' Raft IDs on startup to gossip them to other nodes. We do it inefficiently with separate SELECT from the system table for every peer. Compare this to the analogous code for HOST_ID and tokens which uses a single SELECT to scan the table. We should do the same.

Alternatively, after https://github.com/scylladb/scylladb/pull/12084 is finished, we can start using the HOST ID of a node as the Raft ID (issue: https://github.com/scylladb/scylladb/issues/12204). Then most of this code will become unnecessary.

**Comment by kbr-scylla** [comment]
We can close this if https://github.com/scylladb/scylladb/pull/12275 is merged.
