### ISSUE TITLE
test: `exceptions::configuration_exception` after killing a node and immediately restarting it

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#12218]
None of our existing topology tests in test.py restart a node after killing it with `manager.server_stop`. They always remove the killed node. All tests which restart nodes are using `stop_gracefully`.

So I wrote this simple test:
```python3
async def test_restart(manager: ManagerClient, random_tables) -> None:
    servers = await manager.running_servers()
    await manager.server_stop(servers[0].server_id)
    await manager.server_start(servers[0].server_id)
```

the restarted server fails with:
```
ERROR 2022-12-06 18:18:55,069 [shard 0] init - Startup failed: exceptions::configuration_exception (Cannot add table 'service_levels' to non existing keyspace 'system_distributed'.)
```

- I removed `--unsafe-bypass-fsync 1` from startup options, didn't help.
- Happens both with and without Raft.
- Doesn't happen with a single node (the test fails but due to the driver being the driver - the node restarts). Happens with 2 and 3 nodes. So it apparently requires a cluster.

We do start the nodes in an "unsupported" way (i.e. wait-for-gossip-to-settle disabled, ring_delay 0)... But it we should this anyway. We want to remove all these sleeps eventually.

**Comment by kbr-scylla** [comment]
Need to test with
```
force_schema_commit_log: true
```

**Comment by tgrabiec** [comment]
"Cannot parse the version of the file ..." are benign: https://github.com/scylladb/scylladb/issues/11867

**Comment by kostja** [comment]
Fix: add a separate schema commit log for schema and use force-schema-commit-log

**Comment by avikivity** [comment]
Test-only, not backporting. @kbr- please backport if you think 5.2 needs it.
