### ISSUE TITLE
Scylla Alternator histogram should use Summary

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#12230]
The Alternator reports multiple histograms for operation latencies.
Instead it should report a histogram per node and a summary per shard.

**Comment by nyh** [comment]
Amnon, can you please add some hints on how to do this change, or an example of some other metrics that already have "a histogram per node and a summary per shard" from which we can learn how to do this?

**Comment by amnonh** [comment]
I've open this issue thinking that I would get to it.
Just to explain what is needed:
Change the histogram type to:
`utils::timed_rate_moving_average_summary_and_histogram`

Now, instead of registering just a histogram metrics, you need to register a histogram per node and a summary per shard.

To report a histogram per node, you add a `.aggregate({seastar::metrics::shard_label})` to the definition.

You can look at `storage_proxy.cc void storage_proxy_stats::write_stats::register_stats()` for summary and histograms as a reference.

It's best to mark all those reported metrics with `.set_skip_when_empty()` as can be seen int the storage_proxy code

**Comment by nyh** [comment]
As fixing this will make Alternator's latency histograms less expensive, it will be a good opportunity to add latency histograms for more operations. I opened a separate issue about that - https://github.com/scylladb/scylladb/issues/17615.

**Comment by mykaul** [comment]
@amnonh / @nyh - do we wish to backport this? I'm unsure, as it's partially an enhancement.

**Comment by nyh** [comment]
I think we don't need to backport it, it's a performance enhancement, and users did not complain about it previously.
Moreover, if I remember correctly (but @amnonh can comment), accepting this change in Scylla requires changing the monitoring stack for the version which has it - so if we backport this patch we'll also need to backport the monitoring patch and this can get messy, so perhaps it's better not to do it.

However, one of the main goals (as far as *I* am concerned) of this patch is to make it more efficient to later add more historgrams to Alternator (this is https://github.com/scylladb/scylladb/issues/17615). If we do that, and if we backport **that** patch, it might become more important to backport this one as well.

**Comment by nyh** [comment]
> I think we don't need to backport it, it's a performance enhancement, and users did not complain about it previously. 

I just realized that @mykaul actually did complain about the size of these histograms in another venue. So we maybe we **should** backport it. @mykaul, recommendation?

**Comment by mykaul** [comment]
> > I think we don't need to backport it, it's a performance enhancement, and users did not complain about it previously.
> 
> I just realized that @mykaul actually did complain about the size of these histograms in another venue. So we maybe we **should** backport it. @mykaul, recommendation?

I think if it's safe, we probably should.
