### ISSUE TITLE
GCP image in docs not exist

### ISSUE THREAD

**Issue by charlychiu** [scylladb/scylladb#12238]
When I run the command following in official docs [here](https://www.scylladb.com/download/?platform=gcp#open-source)

> gcloud compute instances create <name of new instance> --image scylladb-5-1-0 --image-project scylla-images --local-ssd interface=nvme --zone <optional> --machine-type=n1-standard-8

I will got the error with
```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Required 'compute.images.useReadOnly' permission for 'projects/scylla-images/global/images/scylla-5-1-0'
```

Thanks **Yaron Kaikov** help me find out the problem is in slack, discussion [here](https://scylladb-users.slack.com/archives/C2NLNBXLN/p1670402583299389)

# Root Cause:
GCP project `scylla-images` not contain with image `scylladb-5-1-0`

**Comment by tzach** [comment]
@yaronkaikov please advise

**Comment by yaronkaikov** [comment]
@tzach This is what you changed already yesterday, page has already been fixed https://www.scylladb.com/download/?platform=gcp#open-source. closing
