### ISSUE TITLE
Unexpected isolation behaviour when using LWTs

### ISSUE THREAD

**Issue by sebver** [scylladb/scylladb#12255]
*Installation details*
Scylla version (or git commit hash): 5.1.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

The documentation seems to indicate that LWT's are applied in isolation. I've made a small example program that stress tests this and I seem to be running in some issues.

What my program is trying to do (I am using 3 nodes and RF = 2):

1. Insert 100 rows in same partition, but different clustering id, all with version = 0.
2. Have 10 writers in parallel update all the rows in that partition using a batch with an `IF` condition. Every writer uses a different version, but an individual writer sets all rows to the same version.
3. Have 10 readers read this whole partition in parallel. Expected behaviour would be that they all see the same version. It doesn't matter what the version is, but it should be the same for all the rows.

Unfortunately that doesn't happen, sporadically I'm getting rows with a different version. To complicate matters, I'm testing this on two different clusters, and on one it fails much sooner than the other (but I've seen both of them fail). Both clusters seem equally healthy though.

Here is the code for this example: https://github.com/sebver/scylla-isolation-test/blob/master/src/main.rs

Perhaps I'm just misunderstanding and we're not expecting this behaviour in the first place - or my example is wrong.

**Comment by kostja** [comment]
You need to be reading with Read Consistency set to Serial, not QUORUM. 
```
    async move {
                let mut select = session
                    .prepare("SELECT version FROM isolation_test")
                    .await
                    .unwrap();
                select.set_consistency(READ_CONSISTENCY);
               ```
