### ISSUE TITLE
Deprecate Thrift

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#12262]
It doesn't seem to be used and not worth the efforts and complexity associated.

**Comment by mykaul** [comment]
@tgrabiec - would that also allow not to support partial keys?

**Comment by nyh** [comment]
Duplicate of https://github.com/scylladb/scylladb/issues/3811.

**Comment by mykaul** [comment]
Closing as dup, will continue the discussion on #3811

**Comment by avikivity** [comment]
Really closing as duplicate of #3811.
