### ISSUE TITLE
token_metadata should map tokens to hosts rather than to endpoints

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12279]
As part of https://github.com/scylladb/scylladb/issues/6403, now that host_id is unique (https://github.com/scylladb/scylladb/commit/dcba652013e0f7c5aa8804f353079060e2a7a6e2),
we should keep token ownership by host_id rather than by endpoint.

**Comment by gusev-p** [comment]
Fixed in this PR https://github.com/scylladb/scylladb/pull/15903
