### ISSUE TITLE
cdc should identify nodes using their host_id rather than endpoint

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12283]
As part of https://github.com/scylladb/scylladb/issues/6403, now that host_id is unique (https://github.com/scylladb/scylladb/commit/dcba652013e0f7c5aa8804f353079060e2a7a6e2),
cdc should identify nodes by their host_id rather than endpoint.

**Comment by kbr-scylla** [comment]
I don't really know what this means, to be honest. Which parts of CDC?

**Comment by bhalevy** [comment]
In hindsight, I agree there isn't anything to do, beyond maybe https://github.com/scylladb/scylladb/pull/17919, that's very minor.  Once the gossiper will change to use host_id callers of `for_each_endpoint_state_until` will be encouraged not to use the node's inet_address, including cdc_generation, but currently there isn't anything to do here with that respect as far as I can tell.
