### ISSUE TITLE
Deleting a long base partition may leave some undeleted view rows

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12297]
While we always suspect that fluke network problems and the likes are what can lead to base-view inconsistencies, a Scylla user discovered a case where a specific kind of DELETE operation may consistently leave a base-view inconsistency .

The following cql-ptest reproducer is a simplified version of the user's workload:

```python
def test_long_partition_delete_bug(cql, test_keyspace):
    with new_test_table(cql, test_keyspace, 'p int, c int, x int, y int, primary key (p,c)') as table:
        with new_materialized_view(cql, table, '*', 'p, x, c', 'p is not null and x is not null and c is not null') as mv:
            for i in reversed(range(1000)):
                cql.execute(f'INSERT INTO {table} (p,c,x,y) VALUES (1,{i},{i},{i})')
            assert list(cql.execute(f"SELECT c FROM {table} WHERE p = 1")) == list(cql.execute(f"SELECT c FROM {mv} WHERE p = 1"))
            t = list(cql.execute(f"SELECT writetime(y) FROM {table} WHERE p = 1 and c = 900"))[0].writetime_y
            cql.execute(f'DELETE FROM {table} USING TIMESTAMP {t} WHERE p=1')
            assert list(cql.execute(f"SELECT c FROM {table} WHERE p = 1")) == list(cql.execute(f"SELECT c FROM {mv} WHERE p = 1"))
```

The test writes 1000 rows to the base table, with with clustering key 0..999. The write loop is in reverse order, so the first row in clustering order (c=0) will have the latest write timestamp. The test then takes the 900th row's timestamp, and deletes p at that timestamp. Because of the timestamp order, only the last 100 rows, who have timestamps older than the 900th row, will get deleted. Since these 100 rows get deleted from the base table, they should also get deleted from the view table, but the failure of the last assert with the message `Right contains 100 more items, first extra item: Row(c=900)` demonstrates that the rows got deleted from the base table, but not from the view table!

Some interesting observations which can help pinpointing the cause of this bug:
* The "USING TIMESTAMP" seems to be an important part of this reproducer - deleting the entire partition without USING TIMESTAMP seems to correctly delete all the view rows as well.
* The test succeeds when replacing 1000 by 100 (and 900 by 90). Somehow the fact that the base partition is longer than some threshold activates the bug.
* The `reversed()` timestamp order is is important as well. If we don't reverse the insertion order, the deletion will shadow the first 100 rows in the base partition instead of the last 100, and the deletions will correctly happen on the view as well.

**Comment by avikivity** [comment]
Could it be #11668?

**Comment by nyh** [comment]
Maybe it's related - I'll check. But it can't be exactly the same thing because the test fails on master, and that issue is already fixed.

**Comment by nyh** [comment]
By the way, we don't need 1000 rows for this test to fail - it's starts to fail when the test has 113 rows or 101 rows after the deletion.  I don't think this threshold 100 is a coincidence, I think it's `max_rows_for_view_updates`.

**Comment by nyh** [comment]
I have some clues as to what's wrong, but this fix is turning out harder than I had hoped:

In the general case, the view building code can't write a single view-table partition tombstone and needs to write a separate tombstone for each view row. We have code that does this, and stops after reaching `max_rows_for_view_updates` (100) rows. After reaching 100 rows, the code correctly stops to continue later - and correctly remembers the partition tombstone to continue later. BUT, does it continue later? It doesn't continue! It only does the first 100 and then stops.

The code which runs this whole thing is `table::generate_and_propagate_view_updates()` :
```
    while (true) {
        utils::chunked_vector<frozen_mutation_and_schema> updates;
        try {
            updates = co_await builder.build_some();
        } catch (...) {
            err = std::current_exception();
            break;
        }
        if (updates.empty()) {
            break;
        }
```

So this loop stops if build_some() ever returns 0. And it turns out that in this test, it does after the first 100 row deletions in the first build_some() returns 0!

In build_some() I added printouts and saw we have `_view_updates` with one item (one partition) but the returned `mutations` is empty.

I suspect that we're trying to do some sort of optimization or compaction which notices that all the first 100 row modifications do absolutely nothing (they try to delete a row with an older partition-tombstone) and optimize it to think there are zero modifications. If my understanding is correct, this is wrong for two reasons:

1. In this test we stop after the first 100 do-nothing deletions and don't know we need to continue checking more (this is this bug)
2. In any case, even if a partition tombstone is older than data we already have, we can't ignore the partition tombstone and need to save it too - otherwise old data might be resurrected. This seem to me a new bug that I don't know how to reproduce (if it's really a bug).

**Comment by avikivity** [comment]
Wow, what an unfortunate bug.

**Comment by michoecho** [comment]
bd52e05ae23458581d7e7276f706ae87d96f284b?

**Comment by nyh** [comment]
@michoecho you're right, if I comment out the code
```c++
if (can_skip_view_updates(update, existing)) {
    return;
}
```

The bug is fixed and the test passes.

Now I need to consider a correct and permanent fix: I need to think now if I should change can_skip_view_updates() to return false in this case (this is important if point 2 in my above comment is true), or I need to fix the iteration where finding nothing to do on the first 100 rows doesn't mean we can stop trying more rows. Perhaps I need to fix both!  (and I would need two tests instead of one, to reproduce the two problems spearate).

**Comment by nyh** [comment]
I'm starting to believe that `can_skip_view_updates()` is not wrong - when a row tombstone is covered by newer live data, the row tombstone is genuinely not needed. In my test, the first 100 row updates can genuinely be skipped. The main bug is that after skipping 100 row updates the code stops doing the rest, and that is wrong.
Yes, commenting out `can_skip_view_updates()` avoids the bug, but only because we never skip anything and it removes a correct optimization so I don't want to adopt that solution.

I'm trying to build now more delicate tests that don't involve partition tombstones to prove that the problem is not `can_skip_view_updates()` handling of tombstones but something more fundemental, and then I can go about fixing that something more fundemental.

**Comment by nyh** [comment]
Yes, as I suspected the bug is NOT specific to partition tombstones, and is a bug in the loop I mentioned in https://github.com/scylladb/scylladb/issues/12297#issuecomment-1349014205 - not in `can_skip_view_updates()` itself.

In the following test I create a partition with 200 rows, and then create one base mutation (a BATCH) which modifies a column "y" that isn't selected by the view in all 200 rows, plus adds one new row at the very end. Scylla rightly sees that all modifications of the first 100 rows are not relevant to the view and can be skipped, but then the bug leads us to stop there - instead of noticing that the 201st row **is** relevant and can't be skipped. 

```python
@pytest.mark.parametrize("size", [50, 200])
def test_12297_1(cql, test_keyspace, size):
    with new_test_table(cql, test_keyspace, 'p int, c int, x int, y int, primary key (p,c)') as table:
        # Note that column "y" is not selected by the materialized view
        with new_materialized_view(cql, table, 'p, x, c', 'p, x, c', 'p is not null and x is not null and c is not null') as mv:
            for i in range(size):
                cql.execute(f'INSERT INTO {table} (p,c,x,y) VALUES (1,{i},{i},{i})')
            # In a single batch (a single mutation), update "y" column in all
            # 'size' existing rows, plus add one new row in the last position
            # (the partition is sorted by the "c" column). The first 'size'
            # updates can be skipped in the view (because y isn't selected),
            # but the last one can't - it really adds a new row.
            cmd = 'BEGIN BATCH '
            for i in range(size):
                cmd += f'UPDATE {table} SET y=7 where p=1 and c={i}; '
            cmd += f'INSERT INTO {table} (p,c,x,y) VALUES (1,{size+1},{size+1},{size+1}); '
            cmd += 'APPLY BATCH;'
            cql.execute(cmd)
            # We should now have the same size+1 rows in both base and view
            assert list(cql.execute(f"SELECT c FROM {table} WHERE p = 1")) == list(cql.execute(f"SELECT c FROM {mv} WHERE p = 1"))
```

**Comment by nyh** [comment]
Backported:
* next-5.1 (099145fe9ac7eed496c14d92b4654d1fbc48b25d) - trivial backport
* next-5.0 (07c20bdfea4e4ec6318f36195cce71bcbfc3a1e4 ) - required fairly elaborate changes as the code modified by this patch uses coroutines in master but still used futures in 5.0 and looked very different. As usual, I verified that the tests for this patch passed after the backport (and CI will check all the other tests).
