### ISSUE TITLE
Update cassandra-stress to support Serverless bundle 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#12291]
Scylla Java driver 3.11.2.3 support a bundle file for endpoint.
cassnadra-stress should use it as well
https://github.com/scylladb/java-driver/commit/f5fc83dd895196670ccec17731c601c4694afaf3

**Comment by mykaul** [comment]
@avelanarius - is that under your team? Please handle or re-assign.

**Comment by avelanarius** [comment]
But… it was already done by my team: https://github.com/scylladb/scylla-tools-java/pull/313

**Comment by mykaul** [comment]
> But… it was already done by my team: [scylladb/scylla-tools-java#313](https://github.com/scylladb/scylla-tools-java/pull/313)

Thanks!

**Comment by tzach** [comment]
How dare you complete it before I opened the issue :wink:
