### ISSUE TITLE
Expire unused entries from `direct_fd_pinger::_rate_limits`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#12309]
Follow-up to https://github.com/scylladb/scylladb/issues/12156

`direct_fd_pinger::_rate_limits` is used to rate-limit warnings about missing IP address mappings when pinging Raft servers for failure detection. The map contains a separate `rate_limit` entry for each server (but only if that server was missing its mapping at some point).

The desired size of this map is 0 if everything goes right and we're never missing an IP address - but if there are situations where e.g. a newly added node is missing an IP address for a few seconds, this could lead to more and more entries being inserted into the map. Its size is theoretically unbounded. The map is cleared when we restart the node (it lives only in memory).

We could deal with this by removing entries which haven't been accessed for a long time. Perhaps we have a data structure designed for similar use case somewhere already? If not, perhaps we could write a generic data structure for this?

**Comment by andriipatsula** [comment]
This looks like a `LRU` problem. As an example, I wrote a simple class `lru_cache` that must be suitable for this task. I didn't spent much time testing this implementation, but the overall idea must be clear. If the the interface, the idea is Ok at a first glance - I'll continue working on this approach.

```C++
template <class Key, class Val>
class lru_cache {
    struct cache_entry {
        Key _key;
        Val _value;
        lowres_clock::time_point _last_visit;
        
        cache_entry(const Key& k, Val&& v)
            : _key(k)
            , _value(std::forward<Val>(v))
            , _last_visit(lowres_clock::now())
        {}
    };

    using recent_cache_entries = std::list<cache_entry>;
    using cache = std::unordered_map<Key, typename recent_cache_entries::iterator>;

private:
    recent_cache_entries _lru_entries;
    cache _cache;

private:
    void touch(typename recent_cache_entries::const_iterator it) {
        _lru_entries.splice(_lru_entries.begin(), _lru_entries, it);
        cache_entry& entry = *_lru_entries.begin();
        entry._last_visit = lowres_clock:now();
    }

public:
    /// Get and/or create an instance of a type Val
    /// * if the object already exists - update the `_last_visit` timestamp
    ///    and move cache_entry to the beginning of the `recent_cache_entries`.
    template<typename... Args>
    Val& try_get(const Key& k, Args &&... args) {
        if (auto it = _cache.find(k); it != _cache.end()) {
            touch(it->second);

            cache_entry& entry = *it->second;
            return entry._value;
        }
        
        _lru_entries.emplace_front(k, Val(args...));
        auto it = _lru_entries.begin();
        _cache.emplace(k, it);
        return it->_value;
    }

    /// Remove the cache_entry with the given key, if exists.
    void remove(const Key& k) {
        if (auto it = _cache.find(k); it != _cache.end()) {
            _lru_entries.erase(it->second);
            _cache.erase(it);
        }
    }

    /// Remove the cache entries older than specified interval.
    void remove_least_recent(std::chrono::milliseconds interval) {
        const auto now = lowres_clock::now();
        typename recent_cache_entries::const_iterator it = _lru_entries.begin();

        for (; it != _lru_entries.end(); ++it) {
            const auto& entry = *it;
            if (now - entry._last_visit >= interval)
                break;
        }

        _lru_entries.erase(it, _lru_entries.end());

    }
};

int main() {
    using namespace std::chrono_literals;
    using namespace direct_failure_detector; 

    lru_cache<direct_failure_detector::pinger::endpoint_id, rate_limit> cache;
    cache.try_get(pinger::endpoint_id("0"), std::chrono::milliseconds(1));
    cache.try_get(pinger::endpoint_id("0"), std::chrono::milliseconds(1)); // the same key - do not create new one.
    
    cache.try_get(pinger::endpoint_id("1"), std::chrono::milliseconds(10));

    std::this_thread::sleep_for(5ms);

    cache.remove_least_recent(std::chrono::milliseconds(15));
    return 0;
}
```

And the usage:
[raft_group_registry.cc#L408](https://github.com/andriipatsula/scylla/blob/1e7d92978d49f4645fd96ba123e9fab0ba963cd2/service/raft/raft_group_registry.cc#L408)
```diff
    if (!addr) {
-       auto [it, _] = _rate_limits.try_emplace(id, std::chrono::minutes(5));
-       auto& rate_limit = it->second;
+      auto& rate_limit = _rate_limits.try_get(id, std::chrono::minutes(5));
        rslog.log(log_level::warn, rate_limit, "Raft server id {} cannot be translated to an IP address.", id);

+     _rate_limits.remove_least_recent(std::chrono::minutes(30))

        co_return false;
    }
```

**Comment by andriipatsula** [comment]
@kbr-scylla , @kostja what do you think about the approach above?

**Comment by kostja** [comment]
@andriipatsula looks acceptable to me.

**Comment by andriipatsula** [comment]
where 'd be the best place to live for this utility class?

**Comment by kbr-scylla** [comment]
@andriipatsula sorry for not answering for so long, I was on vacation first, then I was a bit swamped, but now got a bit more breathing space.

I like the code a lot - thanks!
Some comments I have:
- I think this is not exactly LRU cache, in LRU cache we remove the least recently used entries based on the size of the cache - once the size grows over certain threshold when trying to insert an entry, we remove the least recently used entry. Here, on the other hand, the size of the cache may potentially grow unbounded (if we insert many entries in a short period of time), and we remove all entries whose latest usage is older than some time threshold. So I'm a bit worried about using the `lru_cache` name. Maybe something more generic like `recent_entries_cache`? But I'm not sure. Or maybe I'm wrong and LRU cache can also mean this.
- it's also more than a cache - it's a map combined with a caching mechanism. So maybe an even better name would mention "map", e.g. `recent_entries_map` or something
- `_lru_entries.emplace_front(k, Val(args...));` - should probably forward `args` here
- the loop in `remove_least_recent` could be replaced with `std::find_if`

As for the place to put this, I think the utils/ directory is appropriate.
In fact there's already an "lru" class there, in utils/lru.hh, but it's much more low level than the data structure you proposed and it doesn't seem to be appropriate for our use case so let's ignore it. But it's another reason to use some different naming than "lru" :P

**Comment by andriipatsula** [comment]
Hello @kbr-scylla . Thank you for feedback. I prepared a PR and resolved issues you mentioned in your message above. Feel free to comment and to suggest improvements.
