### ISSUE TITLE
test.py will overwrite output files when two tests have the same "shortname"

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12310]
In the past, test output files (xml and log files) were composed using both a shortname and a unique number, e.g, testname.1234.log. Because the run number 1234 was unique, it wasn't important that the shortname wasn't globally unique.

However, recently (commit ea99750de784258b419031378a008623caae9f01), @avikivity changed the numbers to be "less-unique" - they are now low integers like 1,2,3, which are unique for different runs of the same tests, but not unique among different tests. So after this patch, it because critical that the "shortname" of different tests are unique - otherwise their output files will overwrite each other. 

For example, in issue #12241 we noticed that output files from a successful test/scylla-gdb/run test overwrote the error logs from a failed test/alternator/run test - just because both tests have the same shortname "run".

In this specific case, the shortname of a RunTest could be the full path name (e.g, "alternator_run", not just "run"), @kostja can you please do that because I don't know how?

But test.py should solve this problem of duplicate output file names once and for all. It should either detect and warn about duplicate shortnames, or, I think a better solution is not to use just the "shortname" of a test for naming its output file but rather use a fuller name which includes the test suite's name concatenated with the shortname, to reduce the chance of duplication of the same name between two different suites.

**Comment by avikivity** [comment]
I think the files should be local to the test directory. For example, a test in the boost suite will write into boost/$shortname.xml.

**Comment by nyh** [comment]
@avikivity I'm fine with that - I was actually going to suggest it - but then I thought it is quite possible that Jenkins would not know how to handle the tree of test results and how to name it, so I thought about using a, say, underscore instead of a slash. But if Jenkins can handle slashes, it's even better.

**Comment by avikivity** [comment]
I thought the same, then noticed that we already generate a tree (example of post-patch result: testlog/dev/xml/cql-pytest/cassandra_tests/validation/operations/select_test.1.xunit.xml).

**Comment by benipeled** [comment]
Yes, Jenkins is looking for

- testlog/**/xml/*.xunit.xml
- testlog/**/xml/junit.xml

So please make sure the new log-path matches the first pattern

**Comment by nyh** [comment]
@benipeled the "xml" subdirectory must be the penultimate component? It doesn't seem to fit the path that Avi posted above.

**Comment by avikivity** [comment]
It's possible that we fold those .xmls into a super-xml

**Comment by avikivity** [comment]
test-only, not backporting.
