### ISSUE TITLE
docs: Issue in page Data Definition

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12334]
I would like to report an issue in page https://docs.scylladb.com/branch-5.1/cql/ddl

### Problem
There is a line whose left column says "compaction" but right column says "compression options"

###  Suggest a fix
The left column of that line should be "compression", not "compaction". We have a different line which is truly about compaction.

**Comment by avikivity** [comment]
Backported to 5.1.

**Comment by avikivity** [comment]
(already in 5.2)
