### ISSUE TITLE
DESCRIBE statement missing role-based access control

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#12342]
```c++
future<> describe_statement::check_access(query_processor& qp, const service::client_state& state) const {
    state.validate_login();
    co_return;
}
```

But, the user might not have access to the keyspace being described.

Need to check whether table/keyspace access is checked by Cassandra and by postgresql.

**Comment by avikivity** [comment]
I guess it's moot since everyone has access to the schema tables, and we don't have row-based access control.

**Comment by Jadw1** [comment]
Cassandra doesn't do any check in describe
https://github.com/apache/cassandra/blob/6da9e33602fad4b8bf9466dc0e9a73665469a195/src/java/org/apache/cassandra/cql3/statements/DescribeStatement.java#L111-L114

Should we add keyspace/table access validation anyway (even if the informations displayed by describe are accessible by schema tables as you said)?

**Comment by nyh** [comment]
> Should we add keyspace/table access validation anyway (even if the informations displayed by describe are accessible by schema tables as you said)?

I vote no, unless we want to do per-row access control on the schema tables and I don't think we want to do it now.
We should document this - that the schemas are visible to all roles, just the content itself may be protected.

**Comment by avikivity** [comment]
Agree with @nyh, it's pointless to lock one door when the window is open.

**Comment by kostja** [comment]
Access must be checked. Without it, the user can learn the object exists, which is an information disclosure. All vendors do it.

**Comment by kostja** [comment]
Regarding access to schema tables, non-superuser roles should not have it. With virtual tables it's easy to do - populate virtual tables with the content available to the current role, grant access to virtual tables to everyone.

**Comment by avikivity** [comment]
> Access must be checked. Without it, the user can learn the object exists, which is an information disclosure. All vendors do it.

Of course, this is correct, but adding access checking to DESCRIBE is pointless without also limiting access to system_schema tables which disclose the same information.

To do the latter, we must apply row-based access control, or convert them to virtual tables ("manual RBAC"), both of which are significant undertakings.

My conclusions are that this is a flaw, but we have to accept it for the time being.

**Comment by Jadw1** [comment]
> I guess it's moot since everyone has access to the schema tables, and we don't have row-based access control.

@avikivity can we close it?

**Comment by piodul** [comment]
> @avikivity can we close it?

@avikivity ping

**Comment by kostja** [comment]
@avikivity DESCRIBE in other databases requries some access to the schema being described. But this is not the case in Cassandra, and I guess we should maintain compatibility. Please feel free to reopen.
