### ISSUE TITLE
secondary_index_test.test_secondary_index_collections fails with multiple compaction groups

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#12368]
Logs show:

unknown location(0): fatal error: in "test_secondary_index_collections": std::runtime_error: Expected more rows (1), got 0
test/lib/exception_utils.cc(21): last checkpoint

**Comment by nyh** [comment]
@raphaelsc please post instructions on how to run this test with "multiple compaction groups" that reproduces this failure.

Unfortunately the Boost test framework's exception reporting really sucks, so I have no idea which of the checks failed. We'll need to add BOOST_TEST_PASSPOINT() or BOOST_TEST_CHECKPOINT(...) in this test to see where the failure came from.

@enedil the failure is in a test you recently modified, so might be familiar to you.

**Comment by DoronArazii** [comment]
@raphaelsc where is it standing?

**Comment by tchaikov** [comment]
spotted in next's promotion: https://jenkins.scylladb.com/job/scylla-master/job/next/6065

**Comment by raphaelsc** [comment]
> spotted in next's promotion: https://jenkins.scylladb.com/job/scylla-master/job/next/6065

This is https://github.com/scylladb/scylladb/issues/14076#event-9376608862, but likely easier to reproduce with multiple compaction groups. Fixing 14706 probably will fix this too.

**Comment by mykaul** [comment]
Closing, as https://github.com/scylladb/scylladb/issues/14076#event-9376608862 is fixed. We can re-open if we bump to this again.
