### ISSUE TITLE
[v3.0.8] Node addition get stuck 

### ISSUE THREAD

**Issue by palash340** [scylladb/scylladb#12372]
*Installation details* 
Scylla version : 3.0.8
Cluster size: 18 (one under UJ status)
OS :  AWS AMI (Linux 5.1.15-1.el7.elrepo.x86_64)

*Hardware details (for performance issues)*     
Platform (physical/VM/cloud instance type/docker):  AWS i3.4xlarge
Hardware:  cores=16   memory= 126GB
Disks: (SSD/HDD, count)  SSD

Tried adding node to cluster with auto_bootstrap enabled, after syncing data successfully from 2 nodes it stuck.
Enabled trace logs for range_streamer did not observed any logs post that.
Average disk utilisation on node : 2.6 TB (out of 3.5 TB) 
Disk utilisation on new node : 400 GB (out of 3.5 TB) in 4 days

Observed similar behaviour when ran `nodetool rebuild` 

Please let me know if you need more details

**Comment by palash340** [comment]
Request participants @michoecho @tgrabiec  @denesb 
Unfortunately we can't upgrade scylla version and pressing issue for us.

**Comment by denesb** [comment]
>  Unfortunately we can't upgrade scylla version and pressing issue for us.

Why can't you upgrade? Note that we are very unlikely to invest time into investigating an issue with an EOL'd version. The issue might be simply fixed on a newer version already.

**Comment by avikivity** [comment]
3.0 went end-of-life almost three years ago. Your only option is to upgrade.
