### ISSUE TITLE
GET `/storage_service/native_transport` should only return true after the server's been started

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylladb#12376]
The current implementation of `is_native_transport_running` , the method behind GET `/storage_service/native_transport`, only checks for non-emptiness of `_listen_adresses` vector. 

https://github.com/scylladb/scylladb/blob/d9269abf5b50c8f2a0c45334f6169691ef06c9a5/api/storage_service.cc#L264

Since items are pushed to the vector before the server is actually started, it may result in the calls to `/storage_service/native_transport` being racy, i.e. you might get a confirmation before there's anyone listening on the port.

https://github.com/scylladb/scylladb/blob/d9269abf5b50c8f2a0c45334f6169691ef06c9a5/transport/controller.cc#L145

For instance we are using this API endpoint in the readiness probe's implementation in Scylla Operator and it's caused us issues in the past: https://github.com/scylladb/scylla-operator/issues/769.

For cql it's possible to check for `RPC_READY` state with failure detector, yet it feels like this shouldn't be the intended behavior anyway.

**Comment by tnozicka** [comment]
@mykaul would you mind getting someone to triage this one?

**Comment by mykaul** [comment]
@eliransin - I think it's in your team? (unsure, please re-assign if not)

**Comment by eliransin** [comment]
@nuivall please have a look

**Comment by nuivall** [comment]
for CQL it was fixed in a51529dd1547fe029e8c259f8b03891106f6edc0

**Comment by mykaul** [comment]
Why is Thrift even interesting? It should be disabled.

**Comment by rzetelskik** [comment]
@nuivall the code snippets in the issue description come from that commit. The issue is that the vector is populated before the server is started - how has this been fixed?

**Comment by nuivall** [comment]
@rzetelskik code looks like this:

```
std::vector<socket_address> controller::listen_addresses() const {
    return _server ? _listen_addresses : std::vector<socket_address>();
}
```

`_listen_addresses` vector is populated, but `_server` is empty because it's moved to there only after server is ready (e.g. after `set_cql_ready(true).get();` ) so it returns empty vector before server started.

**Comment by rzetelskik** [comment]
@nuivall you're right, thanks

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.

**Comment by avikivity** [comment]
Un-backported to 5.0, 5.1, 5.2.  @nuivall please generate a backport to 5.2.

**Comment by avikivity** [comment]
(backports caused a crash in debug mode)

**Comment by nuivall** [comment]
@avikivity is it possible to pick up both commits? First makes tserver ownership management easier, I don't have an idea for a readable patch without this seastar::async simplification...

**Comment by denesb** [comment]
Backported to 5.2 (the entire PR).
