### ISSUE TITLE
sstables skipped by off-strategy compaction remain in maintenance set

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12383]
This seem to be the cause for e.g. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/119/testReport/compaction_test/TestCompaction/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split048___test_delete_tombstone_gc_node_down_TimeWindowCompactionStrategy_/

I reproduced this locally, and it looks like what happens there is:
1. repair brings to node tombstones from deletions made while node4 was down
2. those are written to a very few new sstables with origin=repair
3. off-strategy compaction does nothing since the created sstables are too few (below offstrategy_threshold=4) and they remain in the maintenance set
4. major compaction is run, but since it doesn't include maintenance sstables (do we have an open issue for it to do so?) we end up with data in the output sstables of major compaction + tombstones on the repair sstables, and they are not compacted together
5. while the expected output is full compaction and the elimination of both the data and the tombstones (based on tombstone_gc_mode=repair)

Note that even if we have major compaction take care of maintenance set, this will cause this test to pass, however we should still fix this issue, so that even in the absence of major compaction we still want the sstables left behind repair to be compacted normally with regular compaction, but they won't while they stay in the maintenance set.

**Comment by raphaelsc** [comment]
not sure about # 2. off-strategy compaction, even if no reshape is needed, will move sstables from maintenance set to main one on completion. that can be seen in compaction_manager::offstrategy_compaction_task.

**Comment by bhalevy** [comment]
After investigating further I suspect the issue could be with the test.
Currently it only waits for off-strategy compaction after running repair on node4.
After that it runs repair on all other nodes but it doesn't wait for off-strategy compaction.
The tombstones we're seeing may be arriving from those repairs.

I'm testing a fix to the test to simply trigger and wait for offstrategy compaction after repairing (in parallel) all nodes.
And then check for remaining deletes partitions.

**Comment by bhalevy** [comment]
This is applied on top of https://github.com/scylladb/scylla-dtest/pull/2952 so I'll wait for it to be promoted and then submit the fix (assuming it works well)

**Comment by bhalevy** [comment]
yeah, that's it.  Closing this issue.
