### ISSUE TITLE
Unit-tests takes 6 hours to complete

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#12396]
Starting from https://jenkins.scylladb.com/job/scylla-master/job/next/5518/ the unit-tests take about 6 hours to complete (before it took something between 2.5-3 hours), It seems related to https://github.com/scylladb/scylladb/commit/3fce43124af67c3eeda082b07ced9d367ad60b68 
**Running test without this commit:**
```
ubuntu@ip-172-31-43-170:/jenkins/scylla$ time ./tools/toolchain/dbuild -- ./test.py --mode release multishard_mutation_query_test
Found 7 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_all.1 3.69s
[2/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_all_multi_range.1 3.70s
[3/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_reversed.1 3.72s
[4/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_evict_a_shard_reader_on_each_page.1 3.78s
[5/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_with_partition_row_limits.1 3.93s
[6/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_abandoned_read.1 5.71s
[7/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.fuzzy_test.1 507.52s
------------------------------------------------------------------------------

real	8m28.360s
user	0m0.258s
sys	0m0.132s
```
**With the commit**

```
ubuntu@ip-172-31-43-170:/jenkins/scylla$ time ./tools/toolchain/dbuild -- ./test.py --mode release multishard_mutation_query_test
Found 7 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_all.1 3.73s
[2/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_reversed.1 3.79s
[3/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_all_multi_range.1 3.80s
[4/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_read_with_partition_row_limits.1 3.80s
[5/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_evict_a_shard_reader_on_each_page.1 3.91s
[6/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.test_abandoned_read.1 5.68s
 

[7/7]       boost   release [ PASS ] boost.multishard_mutation_query_test.fuzzy_test.1 3317.50s
------------------------------------------------------------------------------

real	55m18.336s
user	0m1.001s
sys	0m0.939s
```

**Comment by nyh** [comment]
CC @denesb I think you're familiar with this multishard_mutation_query_test.fuzzy_test, maybe you have an idea why it takes more than 500 seconds even before the suspected patch, and 3300 seconds after it - all in the release build.

I guess the effect of compaction groups on this test is a bug that should be fixed, but didn't we consider even the pre-bug number, 500 seconds, a bit too much for a single test?

**Comment by DoronArazii** [comment]
@bhalevy please assign the correct dev to fix it

**Comment by raphaelsc** [comment]
> CC @denesb I think you're familiar with this multishard_mutation_query_test.fuzzy_test, maybe you have an idea why it takes more than 500 seconds even before the suspected patch, and 3300 seconds after it - all in the release build.
> 
> I guess the effect of compaction groups on this test is a bug that should be fixed, but didn't we consider even the pre-bug number, 500 seconds, a bit too much for a single test?

I doubt my series has any effect on that. Compaction groups is disabled by default.

**Comment by bhalevy** [comment]
@tgrabiec / @denesb any recent change that could make fuzzy test tun much longer?

**Comment by bhalevy** [comment]
@yaronkaikov hiw about the other tests?
Recent raft changes and additional test my have contributed to the extra time too.
Also, how did you get to the change you mentioned above?
Did you run git bisect or is it a change related to a particular jenkins job?

**Comment by yaronkaikov** [comment]
> @yaronkaikov hiw about the other tests? Recent raft changes and additional test my have contributed to the extra time too. Also, how did you get to the change you mentioned above? Did you run git bisect or is it a change related to a particular jenkins job?

@bhalevy I reverted locally https://github.com/scylladb/scylladb/commit/3fce43124af67c3eeda082b07ced9d367ad60b68 and then build and run those tests

I don't know about other tests, I assume there is more than 1,  i think i can get it from one of the builds (will post it here later)

**Comment by yaronkaikov** [comment]
@raphaelsc @bhalevy manage to narrow down the issue (i think)
running ` ./tools/toolchain/dbuild  -- ./test.py boost` from  the commit https://github.com/scylladb/scylladb/commit/827cd0d37b1e0895e47c953282c9fd003d6b469e everything seems to be ok. 
Starting https://github.com/scylladb/scylladb/commit/e103e41c7678350e61a1be34f5e41785362ecacb i see tests in `release` takes 2-3 times more

It actually makes sense since this commit (based on the commit message) actually applies it on tests.

**Comment by bhalevy** [comment]
And it looks like database_test times out in debug mode:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1308/artifact/testlog/x86_64/debug/

**Comment by raphaelsc** [comment]
> And it looks like database_test times out in debug mode:
> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1308/artifact/testlog/x86_64/debug/

I understand database_test timing out with the change, but commit https://github.com/scylladb/scylladb/commit/e103e41c7678350e61a1be34f5e41785362ecacb is essentially a no-op. If @yaronkaikov had mentioned https://github.com/scylladb/scylladb/commit/e3e7c3c7e51bd73d79218ed4e8f62b4fe4df7daf instead, I'd understand it.

**Comment by raphaelsc** [comment]
there's no sane explanation for static group series affecting ./tools/toolchain/dbuild -- ./test.py --mode release multishard_mutation_query_test though, as the command explicitly specifies multishard_mutation_query_test, meaning it's not running in parallel to database_test for example which may run with compaction groups enabled.

**Comment by fruch** [comment]
Took 9 hours, but there's tests still failing on ARM:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1313/

**Comment by bhalevy** [comment]
> Took 9 hours, but there's tests still failing on ARM:
> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1313/

The testlog folder shows the results in x86_64/debug:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1313/artifact/testlog/x86_64/debug/

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1313/artifact/testlog/x86_64/debug/scylla-5.log
Shows a SEGV in scylla running test_wasm, but no backtrace.  Do we collect coredumps from unit tests?

**Comment by bhalevy** [comment]
@yaronkaikov / @benipeled the build id, 7c2d26125619e0ab5d466d198fefc3ab4fc04cd5, is of the aarch64 debug package, but the testlog folder is x86_64/debug.

**Comment by yaronkaikov** [comment]
> @yaronkaikov / @benipeled the build id, 7c2d26125619e0ab5d466d198fefc3ab4fc04cd5, is of the aarch64 debug package, but the testlog folder is x86_64/debug.

@bhalevy we will look into it

**Comment by yaronkaikov** [comment]
https://github.com/scylladb/scylladb/commit/b4e4bbd64a8fd3852c55c3e1398aa2d9eec5b536 actually solve this issue, https://jenkins.scylladb.com/job/scylla-master/job/build/1314/ passed in a reasonable time

**Comment by tgrabiec** [comment]
> @tgrabiec / @denesb any recent change that could make fuzzy test tun much longer?

Not that I know of.
