### ISSUE TITLE
Latency degradation on read workload during decommission

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#12403]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2.0~dev.20221219.3e6ddf21bc0f with build-id 4b2025074efc29f0de734ae31e056c6ac1563dea
Cluster size: 3 (but the decommission happens in 3 nodes that were added in the operation before that, so there are 3 decommission in a row)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0c7844f06f7081bb3 (eu-west-1) - i3.2xlarge

during this test we have "only" 65 reactor stalls, but the decommission degradation is twice than last good known one (the average, because it was `5.75 ms`, `7.11 ms` and `8 ms` and now it is `8.8 ms`, `13.09 ms` and `13.63 ms`)

the last good one ran `5.2.0~dev.20220921.1ba78ac35b3e with build-id e8b404519bb0cdfa562e6ad63954cc56e52333b4` and has `test_id: e5d019b7-265f-454b-9ede-8c13a067565d`, and had 488 reactor stalls, meaning that maybe the problem here is not related to reactor stalls

last good one:

![e5d019b7-265f-454b-9ede-8c13a067565d](https://user-images.githubusercontent.com/32832995/209699469-8a38be0f-a764-42ac-bc38-4b70b8c214d1.png)

last run:

![30107bfb-509b-458c-8d5e-335ecf492de2](https://user-images.githubusercontent.com/32832995/209700053-1a1e7208-fb0b-4756-aeab-708e9ed32a50.png)

and searching for the first degradation during decommission for this workload we have:
`5.2.0~dev.20220929.c194c811df01 with build-id 3e922fa2f3dd7546827b4bb02ec4cebd184e062b` with `test_id: 5bbe03b4-09be-4cea-a32b-d393f80dd7fa` (it had 172 reactor stalls):

![5bbe03b4-09be-4cea-a32b-d393f80dd7fa](https://user-images.githubusercontent.com/32832995/209700121-dfd95a2c-6f83-4725-be2a-71118ddceb6f.png)

we also have a degradation, introduce on the same build (also for decommission) on mixed workload, reported here --> #12239 and it may be related

**Comment by roydahan** [comment]
@fgelcer I think we should focus here on the "add_new_node" degradation.
Please change the details according to that. the decommission may be the same issue as the one with the "mixed" workload and the results match this theory.

**Comment by mykaul** [comment]
In prep for tomorrow meeting, do we have an update on this? @fgelcer ?

**Comment by fgelcer** [comment]
> In prep for tomorrow meeting, do we have an update on this? @fgelcer ?

@mykaul , the meeting will be held on Wednesday, and tomorrow, Tuesday, i plan working on all the perf runs of the week + this and another issue are still needing answers

**Comment by fgelcer** [comment]
read workload from this week has outstanding results, hence i don't think that is a relevant problem, and because i think the problem here was that we choose a bad AMI with some debug/unknown content, the results were bad.
@roydahan ?

**Comment by roydahan** [comment]
Closing.
