### ISSUE TITLE
scylla-helper.slice is missing AllowedCPUs settings, so all processes running under it can run on any CPU?

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#12424]
Looking at https://github.com/scylladb/scylladb/blob/f186de909d461003e83ce24f256c2fb6884b6004/dist/common/systemd/scylla-helper.slice, seems like while the CPU usage itself is limited, but it could still run on any core. Generally, we want to ensure it does not run on cores where Scylla shards are running.

systemd's documentation (https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html# ) has these options to control it:
```
AllowedCPUs=, StartupAllowedCPUs=
Restrict processes to be executed on specific CPUs. Takes a list of CPU indices or ranges separated by either whitespace or commas. CPU ranges are specified by the lower and upper CPU indices separated by a dash.

Setting AllowedCPUs= or StartupAllowedCPUs= doesn't guarantee that all of the CPUs will be used by the processes as it may be limited by parent units. The effective configuration is reported as EffectiveCPUs=.

While StartupAllowedCPUs= applies to the startup and shutdown phases of the system, AllowedCPUs= applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases. Using StartupAllowedCPUs= allows prioritizing specific services at boot-up and shutdown differently than during normal runtime.

This setting is supported only with the unified control group hierarchy.

AllowedMemoryNodes=, StartupAllowedMemoryNodes=
Restrict processes to be executed on specific memory NUMA nodes. Takes a list of memory NUMA nodes indices or ranges separated by either whitespace or commas. Memory NUMA nodes ranges are specified by the lower and upper NUMA nodes indices separated by a dash.

Setting AllowedMemoryNodes= or StartupAllowedMemoryNodes= doesn't guarantee that all of the memory NUMA nodes will be used by the processes as it may be limited by parent units. The effective configuration is reported as EffectiveMemoryNodes=.

While StartupAllowedMemoryNodes= applies to the startup and shutdown phases of the system, AllowedMemoryNodes= applies to normal runtime of the system, and if the former is not set also to the startup and shutdown phases. Using StartupAllowedMemoryNodes= allows prioritizing specific services at boot-up and shutdown differently than during normal runtime.

This setting is supported only with the unified control group hierarchy.
```

**Comment by michoecho** [comment]
> Generally, we want to ensure it does not run on cores where Scylla shards are running.

But in the most common setup Scylla is running on _all_ cores. So there's no way around it — you have to run it on the same CPUs as Scylla.

Well, there are the special cores reserved for network IRQs, but I'm not sure why forcing other programs to run on them should be a good idea. If they are underloaded, the other programs are going to be scheduled there anyway. If they are overloaded (if they are the bottleneck), then adding load there will directly decrease the performance of the system.

**Comment by mykaul** [comment]
> > Generally, we want to ensure it does not run on cores where Scylla shards are running.
> 
> But in the most common setup Scylla is running on _all_ cores. So there's no way around it — you have to run it on the same CPUs as Scylla.
> 
> Well, there are the special cores reserved for network IRQs, but I'm not sure why forcing other programs to run on them should be a good idea. If they are underloaded, the other programs are going to be scheduled there anyway. If they are overloaded (if they are the bottleneck), then adding load there will directly decrease the performance of the system.

I was under the impression we'd like to ensure cores, as much as possible, are dedicated to Scylla and are uninterrupted by other processes, be it the node exporter, JMX, LDAP or whatnot. The Linux kernel scheduling does a decent job, but not amazing, at scheduling - it strives mostly for fairness and if some Scylla core CPU is available (and say core0 isn't), it'll run there - while I don't mind the helper service waiting a bit for its share, vs. slowing down (potentially) Scylla.

Perhaps I'm missing something on how we provision Scylla core services across CPUs - don't we aim to reserve, if possible, some cores for the OS and aux. services?

**Comment by michoecho** [comment]
> Perhaps I'm missing something on how we provision Scylla core services across CPUs - don't we aim to reserve, if possible, some cores for the OS and aux. services?

I'm only familiar with how our AWS images are organized — and these don't reserve anything for non-Scylla tasks. The default setup is to reserve 1/16 of cores for network IRQ processing, and run Scylla shards on all other cores. I suspect that most setups follow this pattern.

> The Linux kernel scheduling does a decent job, but not amazing, at scheduling - it strives mostly for fairness and if some Scylla core CPU is available (and say core0 isn't), it'll run there

You have to ask people more field-experienced than me to know, but AFAIK the consensus is that the auxiliary stuff running on the same cores as Scylla does not cause problems in practice. So if you sacrificed cores for that, you would be losing performance for nothing.

And for one-off tasks, like ssh-ing on a Scylla node and doing something there, the distributed system should in most configurations — by design — survive the resulting hiccups without user-visible effects, as long as one node at most is hiccuping.

**Comment by mykaul** [comment]
> > Perhaps I'm missing something on how we provision Scylla core services across CPUs - don't we aim to reserve, if possible, some cores for the OS and aux. services?
> 
> I'm only familiar with how our AWS images are organized — and these don't reserve anything for non-Scylla tasks. The default setup is to reserve 1/16 of cores for network IRQ processing, and run Scylla shards on all other cores. I suspect that most setups follow this pattern.
> 
> > The Linux kernel scheduling does a decent job, but not amazing, at scheduling - it strives mostly for fairness and if some Scylla core CPU is available (and say core0 isn't), it'll run there
> 
> You have to ask people more field-experienced than me to know, but AFAIK the consensus is that the auxiliary stuff running on the same cores as Scylla does not cause problems in practice. So if you sacrificed cores for that, you would be losing performance for nothing.
> 
> And for one-off tasks, like ssh-ing on a Scylla node and doing something there, the distributed system should in most configurations — by design — survive the resulting hiccups without user-visible effects, as long as one node at most is hiccuping.

You bring an interesting use case here - we've seen some issues that may have to do with sshd (see https://github.com/scylladb/scylladb/issues/11528#issuecomment-1308562103 - unproven theory) - it's yet another process we should probably limit.

**Comment by avikivity** [comment]
Yes, we don't really have unused cores that can be used for random tasks. We do have networking-only and compute-only cores, but a latency spike in either will be reflected on the client.
