### ISSUE TITLE
compressed_file_data_source doesn't track its buffers

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12448]
All file sources involved in an sstable read are supposed to register their buffers for tracking with the `reader_permit` so the memory they consume is accounted on the permit and therefore the `reader_concurrency_semaphore` knows about this memory. The compressed file data source looses this tracking: it replaces the tracked buffers coming from the underlying tracked file impl, containing compressed data, with untracked buffers containing decompressed data. This means that the semaphore doesn't know about the memory these buffers contain and can therefore incorrectly admit more reads when really the memory consumption is well above the admission threshold.

**Comment by denesb** [comment]
Yes, its so hard to find these places. In this case, the semaphore knew about ~30M worth of memory (consumed by 7 readers), while there was ~250M of memory just in temporary buffers. These were all decompressed buffers pinned by parsers.

**Comment by avikivity** [comment]
Don't know whether to backport or not. It's not a regression, but does fix memory tracking correctness. It seems pretty safe.

I guess I'll let it stew a bit and rethink it.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1. 5.2 has it.
