### ISSUE TITLE
test.py, allow to set test cluster parameters (config, cmdline) before launching

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#12442]
At the time the cluster starts with fixed parameters (`make_scylla_conf`, `SCYLLA_CMDLINE_OPTIONS`), this is inflexible and does not allow to precisely describe some test scenarios. For example, in `test_topology.py/test_nodes_with_different_smp` we need to start the cluster with different `--smp` parameter values. Now in this test we just stop the cluster and start the nodes again with `--smp` parameter specified. This is hacky and inefficient. It would be more convenient in this test to get an empty cluster and to start it exactly how it's needed.

**Comment by kostja** [comment]
i think you can use a different suite with different defaults pretty easily already today. You can have a single-node topology suite just by changing the node count default, and that's exactly what you need in the test.

**Comment by kostja** [comment]
This is done.
