### ISSUE TITLE
Cached reads may temporarily miss rows under some conditions

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#12451]
Consider the following MVCC state of a partition:

```
   v2: ==== <7> [entry2] ==== <9> ===== <last dummy>
   v1: ================================ <last dummy> [entry1]
```

Where `===` means a continuous range and `---` means a discontinuous range.

After two LRU items are evicted (entry1 and entry2), we will end up with:

```
   v2: ---------------------- <9> ===== <last dummy>
   v1: ================================ <last dummy> [entry1]
```

This will cause readers to incorrectly think there are no rows before entry <9>, because the range is continuous in v1, and continuity of a snapshot is a union of continuous intervals in all versions. The cursor will see the interval before <9> as continuous and the reader will produce no rows.

This is only temporary, because current MVCC merging rules are such that the flag on the latest entry wins, so we'll end up with this once v1 is no longer needed:

 
```
   v2: ---------------------- <9> ===== <last dummy>
```

...and the reader will go to sstables to fetch the evicted rows before entry <9>, as expected.

The bug is in `rows_entry::on_evicted()`, which treats the last dummy entry in a special way, and doesn't evict it, and doesn't clear the continuity by omission.

The situation is not easy to trigger because it requires certain eviction pattern concurrent with multiple reads of the same partition in different versions, so across memtable flushes.

This affects all current versions.

**Comment by tgrabiec** [comment]
Fixed by f97268d8f2c4d67542ec985fe8d137ed67518b63

**Comment by avikivity** [comment]
Considering a backport to 5.1. f340c9cca5dbbc230885d1fc5dd88945679ed3fc removed a call to unlink_from_lru(), and this patch talks about eviction order. Did f340c9cca5dbbc230885d1fc5dd88945679ed3fc introduce the bug by keeping the row in lru, or is this just a coincidence and a backport is indicated?

@michoecho @tgrabiec

**Comment by avikivity** [comment]
Easy to check with the companion unit test.

**Comment by avikivity** [comment]
It indeed fails without the fix and passes with the fix.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1. 5.2 already had the fix.

**Comment by denesb** [comment]
2021.1 backport dequeued as it doesn't build
