### ISSUE TITLE
http parser generates huge amounts of allocations

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#12468]
Parsing an http request generates an allocation per character when processing header values, leading to huge performance drop in alternator. See https://github.com/scylladb/scylladb/pull/12445 for more details.

**Comment by avikivity** [comment]
I want to backport it, but will wait a bit to be sure it doesn't cause regressions.

**Comment by avikivity** [comment]
@michoecho please check if 5.1 has the bug. IIUC it doesn't.

**Comment by michoecho** [comment]
> @michoecho please check if 5.1 has the bug. IIUC it doesn't.

It does have the bug. It's quite an old regression, at least as old as 4.3.

**Comment by avikivity** [comment]
Ok. Please create a backport.

**Comment by avikivity** [comment]
It's https://github.com/scylladb/scylla-seastar/tree/branch-5.1.

**Comment by michoecho** [comment]
I know the branch, but I don't know the procedure. Do I just make a PR in https://github.com/scylladb/scylla-seastar?

**Comment by avikivity** [comment]
> I know the branch, but I don't know the procedure. Do I just make a PR in https://github.com/scylladb/scylla-seastar?

Yes.

**Comment by avikivity** [comment]
@michoecho reminder

**Comment by avikivity** [comment]
Backported to 5.1.

**Comment by avikivity** [comment]
(already in 5.2.)
