### ISSUE TITLE
Forbid more than one partition-key equality check in the same WHERE clause

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12472]
Cassandra refuses the request

```
DELETE FROM tbl WHERE partitionKey = ? AND partitionKey = ?
```

It complains that: 
```
partitionkey cannot be restricted by more than one relation if it includes an Equal
```

Scylla currently does allow such requests without error, and it seems to do (according to my tests) the right thing - `WHERE partitionKey = 1 AND partitionKey = 2` correctly returns no matches, and `WHERE partitionKey = 1 AND partitionKey = 1` returns the matches for `partitionKey = 1`.

We should decide if this deviation from Cassandra was intentional (e.g., we **want** to support this expression to allow users to more easily write "generic" expressions) or accidental.  If it was accidental, we should add this checking to our expression validation. If it was intentional, we should perhaps document this difference somewhere (?) and close this issue. Documenting our extensions over Cassandra may be important for users who want to write an application using Scylla but also be able to run the same application later against Cassandra, so would like to know which Scylla CQL features aren't supported by Cassandra.

This difference was discovered by the translated Cassandra tests:
* `cassandra_tests/validation/operations/compact_storage_test.py`::`testDeleteWithNoClusteringColumns` 
* `cassandra_tests/validation/operations/compact_storage_test.py`::`testDeleteWithOneClusteringColumns` 
* `cassandra_tests/validation/operations/compact_storage_test.py`::`testDeleteWithTwoClusteringColumns`

I also created and will shortly submit a test `test_restrictions.py::test_multiple_eq_restrictions_on_pk` to verify that giving two equality checks in the expression does the right thing (as I explained above).

**Comment by avikivity** [comment]
We should strive to allow all expressions, even the ones that don't make sense.

Consider a C compiler that rejects certain expressions because it doesn't them, even though they make mathematical sense.

**Comment by nyh** [comment]
@avikivity you are right. Although, modern compilers do often warn you (or fail if `-Werror`) on expressions that appear useless and are more likely to be a typo than useful - e.g., using "=" instead of "==", or putting code after a return. E.g., imagine that a user wanted to type `WHERE p = 1 AND v = 2` and mistyped `WHERE p = 1 AND p = 2` and doesn't understand why he gets no results.

I suggest that if we decide to allow this expression that Cassandra doesn't, we should at least start building a document of expression features that we support and Cassandra doesn't.

**Comment by avikivity** [comment]
We have a document: https://github.com/scylladb/scylladb/blob/master/docs/cql/cql-extensions.md

Listing such tiny things though is of limited value. I suggest we wait until the grammar is fully relaxed and then say that any expression is accepted in a context that accepts a value (and point to our documentation of what an expression is). Currently different contexts accepts different sub-grammars.

**Comment by nyh** [comment]
Another similar "issue" (or non-issues) is that when Cassandra sees `WHERE c = ? and c > ?` is produces the error: 
```
c cannot be restricted by more than one relation if it includes an Equal
```
Scylla does allow this case as well.

As before, one could argue on one hand that it doesn't make sense to refuse such a perfectly valid expression, but someone else can argue that this is most likely a user's typo and the user would probably like to be told that.

**Comment by avikivity** [comment]
Here is postgres opinion on the matter:

```
avi=# select * from t2 where k1 = 3 and k1 = 4;
 k1 | k2 
----+----
(0 rows)
```

**Comment by nyh** [comment]
So Avi, should we decide that this is deliberate behavior, and close this issue?

I would like to document it, but I understand what you're saying that it's just a part of a bigger attempt to allow more general expressions so maybe we don't need to document every little piece of how the expression becomes more general.

**Comment by nyh** [comment]
Closing this issue and WONTFIX. We hereby declare that any legal expression, no matter how silly it looks and how unlikely it is to be useful, should be accepted.
