### ISSUE TITLE
SELECT DISTINCT should refuse GROUP BY with clustering column

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12479]
The query `SELECT DISTINCT p FROM tbl WHERE ...` returns one result per partition, so if we add a `GROUP BY p` at the end, nothing canges and it is accepted.

In Cassandra if you add `GROUP BY p,c` to this query, it is refused as non-sensical because you can't take results where there's already only one per partition key, and group them by something smaller (a clustering row). This query reports in Cassandra that "Grouping on clustering columns is not allowed for SELECT DISTINCT queries".
Scylla, on the other hand, seems to simply ignore the "GROUP BY p,c".

This is a very minor issue, because it is about the error path (a request which should have been rejected), not about the successful path. Neverthless, it seems worthwhile to warn the user that they tried to do something nonsensical - it might have been a typo and the user could benefit from correcting that typo.

Updated list of cql-pytest tests reproducing this issue:

* `test_distinct.py`::`test_distinct_in_partition_group_by_c`
* `cassandra_tests/validation/operations/compact_storage_test.py`::`testGroupByWithoutPaging`
* `cassandra_tests/validation/operations/select_group_by_test.py`::`testGroupByWithoutPaging`

**Comment by avikivity** [comment]
Why? I think it makes sense. The grouping is a no-op, but so is adding 0, and it's allowed in all programming languages.

**Comment by avikivity** [comment]
btw, grouping by a prefix of the clustering key is not a no-op. I see no reason to support grouping by a prefix of the clustering key and reject grouping by the whole clustering key.

**Comment by nyh** [comment]
@avikivity I'm not sure I follow... If SELECT DISTINCT already picks just a single row from each partition, how can you further group this by anything smaller than the whole partition? Maybe you could, but how can this be useful?

I agree that in some respects, forbidding silly no-ops is not necessary. However, there is also some of alerting users that their expressions don't appear useful, and may be typos. As I noted, Cassandra also has this check (and verified it in a unit test, which is why I noticed it now while translating this test).

I agree that we can decide that Scylla doesn't want this unnecessary check, and close this issue.

**Comment by avikivity** [comment]
I guess there's confusion here about SELECT DISTINCT. In SQL it applies to the entire result row. In CQL it applies only to the partition key. I was using the SQL definition.

**Comment by denesb** [comment]
A minor error-path fix, not backporting.
