### ISSUE TITLE
Combination of COUNT with GROUP BY is different from Cassandra in case of no matches

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12477]
This issue reports a difference between the results of Cassandra and Scylla in the case of a quite-esoteric request. This difference is probably mostly insignificant, and perhaps should never be fixed - but I'd still like to write it down in case someone in the future rediscovers the same difference, or perhaps someone today wants to think what code caused this difference in the first place, and could this maybe result in bigger, less esoteric, incompatibility?

The difference is in queries like:
```
select p, c, count(c) from {table} where p=XXXX group by p, c
```

Where the `p=XXXX` matches nothing (`c in ()` also causes tghe same problem). Cassandra returns no results at all for this query, which makes sense.

Scylla, on the other hand, returns one result row: p=null, c=null, count(c)=0. This is not only different from Cassandra, it's also strange, because we don't really expect to ever see p=null or c=null returned from a select grouped by p,c - which is supposed to list valid p,c combinations.

Updated list of cql-pytest tests reproducing this issue:

* `test_aggregate.py`::`test_count_and_group_by_row_none`
* `test_aggregate.py`::`test_count_and_group_by_partition_none`
* `cassandra_tests/validation/operations/compact_storage_test.py`::`testGroupByWithoutPaging`.
* `cassandra_tests/validation/operations/select_group_by_test.py`::`testGroupByWithoutPaging`

**Comment by nyh** [comment]
This issue is apparently less "esoteric" and "insignificant" than I figured, because it was re-discovered and reported by a user in duplicate issue #13027.

**Comment by ptrsmrn** [comment]
@avikivity has made a changes in aggregate functions recently in https://github.com/scylladb/scylladb/pull/13105, perhaps it's resolved this issue?

**Comment by avikivity** [comment]
Should we backport it? Probably not. Looks like an edge case, and better not to risk stable versions.

**Comment by nyh** [comment]
I agree it doesn't look like a very important case (when I first reported it I went as far as saying it "perhaps should never be fixed"), but we did get an actual user running into it so apparently it's less esoteric than we thought.

I would say that if it's a clean backport we can do it, but if the fix involved changes to areas which changed recently like expressions, then it's not worth the effort.

**Comment by shantanugithub** [comment]
@nyh @avikivity This issue becomes a major concern when we use spring data cassandra which directly maps the attributes to the entity fields defined. Values like null for primitive and NaN will immediately fail and we would need to introduce another layer between for validating this. Can we please consider backporting the fix to 5.2 series ?

**Comment by nyh** [comment]
@avikivity any objections that I backport this?

I see this is a one-line patch so I hope that even if it's not a clean backport, it won't be a difficult one. I also hope that by the nature of being a very simple one-line patch, there is low risk to the stability of older version (the change only kicks in if aggregate *and* GROUP BY is used).

**Comment by denesb** [comment]
This is a minor edge case but apparently user hit it. It is a simple fix which had time to cook on master for months.
@nyh can you backport this? It doesn't apply cleanly to 5.2.
