### ISSUE TITLE
Internal error in a COUNT request with empty IN

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12475]
The query
```
select count(*) from {table1} where p in ()
```
should result in the count 0, because the empty `p in ()` matches no row. However, what we get in Scylla now is an internal error:

> E   cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.43.23.93:9042 datacenter1>: <Error from server: code=0000 [Server error] message="forward_aggregates::finalize(): operation cannot be completed due to invalid argument sizes. this.aggrs.size(): 1 result.query_result.size(): 0  Backtrace: 0x36e982e 0x36e9dd0 0x36ea0e8 0x1174bf2 0x1174a04 0x3586500 0x3586394 0x3586148 0x1c9eab5 0x1ca9c7f 0x1ca951b 0x1cb2aa7 0x1ca4a8d 0x1a225c3 0x1a4a3e7 0x1a4adac 0x1a4aa9d 0x356ab95 0x35af304 0x35b05a7 0x35af8d9 0x3562611 0x3561b78 0xfbe9d4 0xff14c0 0xfbdc63 /lib64/libc.so.6+0x2950f /lib64/libc.so.6+0x295c8 0xfbcfa4

Also in the Scylla log we see the same error:
```
ERROR 2023-01-09 14:52:55,975 [shard 0] forward_service - forward_aggregates::finalize(): operation cannot be completed due to invalid argument sizes. this.aggrs.size(): 1 result.query_result.size(): 0 
```

CC @havaker @Jadw1 @cvybhu

**Comment by nyh** [comment]
This issue is annoying me - it's not a big disaster for clients, of course, but it's blocking my regression test PR (https://github.com/scylladb/scylladb/pull/12478). So unless anyone else volunteers to do it, I'll take a stab at it myself.

**Comment by nyh** [comment]
> > This issue is annoying me - it's not a big disaster for clients, of course, but it's blocking my regression test PR (#12478). So unless anyone else volunteers to do it, I'll take a stab at it myself.
> 
> I can put it on my CQL queue, but that will take time. Maybe @havaker wants to as he did stuff with aggregates in the past.

I'll try to see if I can solve it in less than an hour, maybe it's a trivial missing check. If not, I'll leave it to you guys.

**Comment by nyh** [comment]
A "WHERE p = null" also fails with the same internal error.

Basically, it seems that the aggregation distributors only needs to send the request to nodes that have the relevant partitions, but a restriction of "p IN ()" or "p = null" has no partitions at all, so gets sent to no node, and I guess that confuses the code.

**Comment by nyh** [comment]
I have a patch, and now I know more about the aggregation code :-) I'll send it soon as a new PR.

**Comment by nyh** [comment]
Sent a PR to fix this bug - https://github.com/scylladb/scylladb/pull/12715

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. Autopar aggregates are new in 5.1.

**Comment by denesb** [comment]
Backport dequeued from 5.1, breaks the build.

**Comment by avikivity** [comment]
Re-backported to 5.1.
