### ISSUE TITLE
RFC: Raft - opt-out for new cluster, opt-in for exiting cluster (upgrade)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#12470]
Enabling Raft has a significant impact on the Scylla cluster.
To make sure it does not cause unexpected regressions  on running clusters while used by default for new clusters, we should:
- Disable Raft default for upgrades (opt-in).
- Enable Raft by default for new clusters (opt-out)

Once we gain more experience, we will enable Raft by default for all clusters.

**Comment by kbr-scylla** [comment]
https://github.com/scylladb/scylladb/issues/12572
PR: https://github.com/scylladb/scylladb/pull/12585
