### ISSUE TITLE
Reshape during node restart using too much disk space?

### ISSUE THREAD

**Issue by AccretiveUser** [scylladb/scylladb#12495]
(I was asked on the community forum to repost this here)

I noticed on my nodes while upgrading from 5.1.0 to 5.1.2 that on one node it decided to do a reshape operation (that took a couple hours).

During this I happened to be just df’ing and noticed it used quite a bit of disk space, roughly double the normal disk space:

pre-reshape:
/dev/nvme1n1 3661060799 1318457771 2342603028 37% /var/lib/scylla

during reshape, near the end of it:
/dev/nvme1n1 3661060799 2582195011 1078865788 71% /var/lib/scylla

My concern is what would have happened if my node started out at over 50% disk used? Would the reshape be able to complete?

I’m using only LCS compaction strategy on all my tables, so I thought it would be “safe” to go over 50% disk used, but is that an incorrect assumption?

After further searching on this issue, I found (an apparently not currently fully documented BTW) the nodetool command to stop a reshape in progress, however again my concern is does this mean now I need to manually check the logs during all upgrades to make sure a reshape didn't kick off?

I think better behavior would be something like:

1. Modify the reshape process (if possible) to delete old files as it goes rather than apparently waiting until the very end to clean up.

or

2. Run a basic prediction before starting a reshape to verify the needed space will be available, and if it doesn't look like a safe amount of space would be left, then don't reshape.

**Comment by raphaelsc** [comment]
@AccretiveUser could you please grep your scylla logs for 'is not disjoint' ?

**Comment by AccretiveUser** [comment]
journalctl -u scylla-server --no-pager |grep 'is not disjoint' |more

(replaced table name with "nnn")

> Jan 04 23:47:45 ip-172-31-128-7 scylla[352239]:  [shard 0] LeveledManifest - Tur
> ns out that level 2 is not disjoint, found 23 overlapping SSTables, so compactin
> g everything on behalf of nnn
> Jan 04 23:47:45 ip-172-31-128-7 scylla[352239]:  [shard 1] LeveledManifest - Tur
> ns out that level 2 is not disjoint, found 26 overlapping SSTables, so compactin
> g everything on behalf of nnn
> Jan 04 23:47:45 ip-172-31-128-7 scylla[352239]:  [shard 2] LeveledManifest - Tur
> ns out that level 2 is not disjoint, found 26 overlapping SSTables, so compactin
> g everything on behalf of nnn
> Jan 04 23:47:45 ip-172-31-128-7 scylla[352239]:  [shard 3] LeveledManifest - Tur
> ns out that level 2 is not disjoint, found 15 overlapping SSTables, so compactin
> g everything on behalf of nnn

**Comment by raphaelsc** [comment]
What's the context at which reshape was triggered? Some node operation? Restarted service?

**Comment by raphaelsc** [comment]
PR was sent to address this: https://github.com/scylladb/scylladb/pull/12496

**Comment by AccretiveUser** [comment]
> What's the context at which reshape was triggered? Some node operation? Restarted service?

Yes, during normal rolling upgrade (performed manually) on 3 node cluster, from 5.1.0 to 5.1.2. Node was drained, service stopped, apt upgrade performed, service started which then triggered the reshape, but only this 1 node of 3 for some reason. A full weekly scheduled repair on the cluster had completed a few hours before this.

**Comment by avikivity** [comment]
Better fix would be to recompact just overlapping tables. The bad level could be the entire table.

**Comment by avikivity** [comment]
Backported to 5.1. 5.0 is affected, but the backport isn't trivial, and the issue isn't huge - too much work on some restarts when LCS is in use. 5.2 already has the fix.

**Comment by raphaelsc** [comment]
> Better fix would be to recompact just overlapping tables. The bad level could be the entire table.

Agreed. That's actually we do when restoring disjointness on regular compaction. Reshape should follow the same approach.
