### ISSUE TITLE
Clean hugepage files after death

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylladb#125]
The /dev/hugepages is full with files which we don't recycle.
It happens w/o the use of the --hugepages flag and probalby the fault
of dpdk:

p_1272  rtemap_1733  rtemap_2194  rtemap_2655  rtemap_3115  rtemap_3577  rtemap_4037  rtemap_4499  rtemap_496   rtemap_542   rtemap_5881  rtemap_6341  rtemap_6802  rtemap_7263  rtemap_7724  rtemap_8185
rtemap_1273  rtemap_1734  rtemap_2195  rtemap_2656  rtemap_3116  rtemap_3578  rtemap_4038  rtemap_45    rtemap_4960  rtemap_5420  rtemap_5882  rtemap_6342  rtemap_6803  rtemap_7264  rtemap_7725  rtemap_8186
rtemap_1274  rtemap_1735  rtemap_2196  rtemap_2657  rtemap_3117  rtemap_3579  rtemap_4039  rtemap_450   rtemap_4961  rtemap_5421  rtemap_5883  rtemap_6343  rtemap_6804  rtemap_7265  rtemap_7726  rtemap_8187
rtemap_1275  rtemap_1736  rtemap_2197  rtemap_2658  rtemap_3118  rtemap_358   rtemap_404   rtemap_4500  rtemap_4962  rtemap_5422  rtemap_5884  rtemap_6344  rtemap_6805  rtemap_7266  rtemap_7727  rtemap_8188
rtemap_1276  rtemap_1737  rtemap_2198  rtemap_2659  rtemap_3119  rtemap_3580  rtemap_4040  rtemap_4501  rtemap_4963  rtemap_5423  rtemap_5885  rtemap_6345  rtemap_6806  rtemap_7267  rtemap_7728  rtemap_8189
rtemap_1277  rtemap_1738  rtemap_2199  rtemap_266   rtemap_312   rtemap_3581  rtemap_4041  rtemap_4502  rtemap_4964  rtemap_5424  rtemap_5886  rtemap_6346  rtemap_6807  rtemap_7268  rtemap_7729  rtemap_819
rtemap_1278  rtemap_1739  rtemap_22    rtemap_2660  rtemap_3120  rtemap_3582  rtemap_4042  rtemap_4503  rtemap_4965  rtemap_5425  rtemap_5887  rtemap_6347  rtemap_6808  rtemap_7269  rtemap_773   rtemap_8190
rtemap_1279  rtemap_174   rtemap_220   rtemap_2661  rtemap_3121  rtemap_3583  rtemap_4043  rtemap_4504  rtemap_4966  rtemap_5426  rtemap_5888  rtemap_6348  rtemap_6809  rtemap_727   rtemap_7730  rtemap_8191
rtemap_128   rtemap_1740  rtemap_2200  rtemap_2662  rtemap_3122  rtemap_3584  rtemap_4044  rtemap_4505  rtemap_4967  rtemap_5427  rtemap_5889  rtemap_6349  rtemap_681   rtemap_7270  rtemap_7731  rtemap_82
rtemap_1280  rtemap_1741  rtemap_2201  rtemap_2663  rtemap_3123  rtemap_3585  rtemap_4045  rtemap_4506  rtemap_4968  rtemap_5428  rtemap_589   rtemap_635   rtemap_6810  rtemap_7271  rtemap_7732  rtemap_820
rtemap_1281  rtemap_1742  rtemap_2202  rtemap_2664  rtemap_3124  rtemap_3586  rtemap_4046  rtemap_4507  rtemap_4969  rtemap_5429  rtemap_5890  rtemap_6350  rtemap_6811  rtemap_7272  rtemap_7733  rtemap_821
rtemap_1282  rtemap_1743  rtemap_2203  rtemap_2665  rtemap_3125  rtemap_3587  rtemap_4047  rtemap_4508  rtemap_497   rtemap_543   rtemap_5891  rtemap_6351  rtemap_6812  rtemap_7273  rtemap_7734  rtemap_822
rtemap_1283  rtemap_1744  rtemap_2204  rtemap_2666  rtemap_3126  rtemap_3588  rtemap_4048  rtemap_4509  rtemap_4970  rtemap_5430  rtemap_5892  rtemap_6352  rtemap_6813  rtemap_7274  rtemap_7735  rtemap_823
rtemap_1284  rtemap_1745  rtemap_2205  rtemap_2667  rtemap_3127  rtemap_3589  rtemap_4049  rtemap_451   rtemap_4971  rtemap_5431  rtemap_5893  rtemap_6353  rtemap_6814  rtemap_7275  rtemap_7736  rtemap_824
rtemap_1285  rtemap_1746  rtemap_2206  rtemap_2668  rtemap_3128  rtemap_359   rtemap_405   rtemap_4510  rtemap_4972  rtemap_5432  rtemap_5894  rtemap_6354  rtemap_6815  rtemap_7276  rtemap_7737  rtemap_825
rtemap_1286  rtemap_1747  rtemap_2207  rtemap_2669  rtemap_3129  rtemap_3590  rtemap_4050  rtemap_4511  rtemap_4973  rtemap_5433  rtemap_5895  rtemap_6355  rtemap_6816  rtemap_7277  rtemap_7738  rtemap_826
rtemap_1287  rtemap_1748  rtemap_2208  rtemap_267   rtemap_313   rtemap_3591  rtemap_4051  rtemap_4512  rtemap_4974  rtemap_5434  rtemap_5896  rtemap_6356  rtemap_6817  rtemap_7278  rtemap_7739  rtemap_827
rtemap_1288  rtemap_1749  rtemap_2209  rtemap_2670  rtemap_3130  rtemap_3592  rtemap_4052  rtemap_4513  rtemap_4975  rtemap_5435  rtemap_5897  rtemap_6357  rtemap_6818  rtemap_7279  rtemap_774   rtemap_828
rtemap_1289  rtemap_175   rtemap_221   rtemap_2671  rtemap_3131  rtemap_3593  rtemap_4053  rtemap_4514  rtemap_4976  rtemap_5436  rtemap_5898  rtemap_6358  rtemap_6819  rtemap_728   rtemap_7740  rtemap_829
rtemap_129   rtemap_1750  rtemap_2210  rtemap_2672  rtemap_3132  rtemap_3594  rtemap_4054  rtemap_4515  rtemap_4977  rtemap_5437  rtemap_5899  rtemap_6359  rtemap_682   rtemap_7280  rtemap_7741  rtemap_83
rtemap_1290  rtemap_1751  rtemap_2211  rtemap_2673  rtemap_3133  rtemap_3595  rtemap_4055  rtemap_4516  rtemap_4978  rtemap_5438  rtemap_59    rtemap_636   rtemap_6820  rtemap_7281  rtemap_7742  rtemap_830
rtemap_1291  rtemap_1752  rtemap_2212  rtemap_2674  rtemap_3134  rtemap_3596  rtemap_4056  rtemap_4517  rtemap_4979  rtemap_5439  rtemap_590   rtemap_6360  rtemap_6821  rtemap_7282  rtemap_7743  rtemap_831
rtemap_1292  rtemap_1753  rtemap_2213  rtemap_2675  rtemap_3135  rtemap_3597  rtemap_4057  rtemap_4518  rtemap_498   rtemap_544   rtemap_5900  rtemap_6361  rtemap_6822  rtemap_7283  rtemap_7744  rtemap_832
rtemap_1293  rtemap_1754  rtemap_2214  rtemap_2676  rtemap_3136  rtemap_3598  rtemap_4058  rtemap_4519  rtemap_4980  rtemap_5440  rtemap_5901  rtem

**Comment by avikivity** [comment]
I don't think this happens any more, please recheck.

**Comment by nyh** [comment]
This is a seven year old issue, and three years ago @avikivity already said this doesn't happen any more, and today I'm not seeing it any more either, so closing this issue.
Maybe it has something to do with using dpdk (which today we usually don't use), or old versions of Seastar and/or DPDK. If it ever happens again, let's open a new issue with up-to-date information.
