### ISSUE TITLE
RPC wrappers, pass arguments by const ref

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#12504]
Now they are always passed by value, which sometimes leads to redundant copies, e.g. in `storage_proxy::handle_write` `forward_fn` from `receive_mutation_handler` declares the parameter as `const frozen_mutation& m`, but then it’s passed to this wrapper and gets copied, so we would have n copies for each forwarding.

The parameters [are serialised synchronously](https://github.com/scylladb/seastar/blob/master/include/seastar/rpc/rpc_impl.hh#L471) so there should be no lifetime issues.

This was not the case before, but the behaviour changed in [this commit](https://github.com/scylladb/scylladb/commit/2f56a360e7e77bb6697432dcca0937dcd4fdb6de). Nowdays there is no problem to get an object by reference during sending.

**Comment by avikivity** [comment]
Changed? That's the commit that introduced messaging_service.

**Comment by gusev-p** [comment]
> Changed? That's the commit that introduced messaging_service.

I copied this from @gleb reply in the slack channel, didn't investigated it on my own yet.

**Comment by gleb-cloudius** [comment]
> Changed? That's the commit that introduced messaging_service.

This https://github.com/scylladb/seastar/commit/3942546d4165071948104107b7c9626486a8c999 commit.
I probably checked what was first this change or the massaging service was introduced.

**Comment by denesb** [comment]
Minor improvement, but the fix is very low-risk, so I'll backport.

**Comment by denesb** [comment]
Backported to 5.2.
