### ISSUE TITLE
Make USING TIMESTAMP range validation optional

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12527]
It is a well-known risk in CQL (see for example https://stackoverflow.com/a/63535718/8891224) that if you mistakenly write data using a client-defined timestamp (`USING TIMESTAMP`) which is far into the future then you won't be able to delete or change this data using "normal" timestamp. We have seen users reach this problem after writing data from a client with a misconfigured clock, or a buggy client code using number of nanoseconds (instead of microseconds) as a timestamp.

Issue #5619 asked that this risk be avoided by demanding that timestamps **must** be in microseconds since the epoch (something which hadn't been a rule until then, see my complaint in https://github.com/scylladb/scylladb/issues/5619#issuecomment-871147653), and that in those units, timestamps should something reasonably close to the current time.  That issue was closed by commit 2150c0f7a2d56b9ea2a5607a4066c4c1c3aba40f, which made it an error to write timestamps more than **3 days in the future** (in microseconds since the epoch).

Since then, we had at least one user complaining that they want to deliberately send arbitrary timestamps and this check is preventing it.

We would like to replaced the fixed "3 days" check with a configurable "safe mode"-style option which makes this  "3 days" number configurable. I'm not sure if we really need the ability to configure different ranges (e.g., 10 days instead of 3 days) or it's enough to have the option to disable this 3-day check completely. @bhalevy noted in the previous discussion we had about this in https://github.com/scylladb/scylladb/issues/5619 that if we disable the 3-day check we should at least check that the value isn't too huge - he said: "I still think we need a fail-safe restriction of being convertible to a timeuuid."

Please note that issue https://github.com/scylladb/scylladb/issues/11588 can easily be confused with this issue, but in fact these are two completely unrelated issues. That other issue is about the timestamp CQL type, which holds 64-bit integers but is expected to be _milliseconds_ since the epoch. This issue is about the USING TIMESTAMP timestamp, which is _microseconds_ since the epoch. The code checking each of these things is in a different place, and the bug is different - the problem in 11588 was that we don't do write-time validation (on the timestamp type) and do the validation too late - during read. The problem here is that we do do write-time validation (of using timestamp), and the user wants to avoid that.

**Comment by nyh** [comment]
@bhalevy I don't understand the requirement that you mentioned in https://github.com/scylladb/scylladb/issues/5619 to be able to convert a writetime() into a timeuuid. Can you please explain it?

Arguably, if someone is using USING TIMESTAMP with timestamps which aren't "valid" times, deliberately (this is the point of this issue) they wouldn't want to convert them into timeuuids in any case, and we don't need to add any check ing for that. I think what you normally want to convert to a timeuuid is the "timestamp" CQL type, which is completely unrelated to USING TIMESTAMP (and by the way the "timestamp" type is officially a real timestamp with millisecond resolution).

**Comment by bhalevy** [comment]
> @bhalevy I don't understand the requirement that you mentioned in #5619 to be able to convert a writetime() into a timeuuid. Can you please explain it?
> 
> Arguably, if someone is using USING TIMESTAMP with timestamps which aren't "valid" times, deliberately (this is the point of this issue) they wouldn't want to convert them into timeuuids in any case, and we don't need to add any check ing for that. I think what you normally want to convert to a timeuuid is the "timestamp" CQL type, which is completely unrelated to USING TIMESTAMP (and by the way the "timestamp" type is officially a real timestamp with millisecond resolution).

Unfortunately I didn't leave behind any breadcrumbs that would help me, and you, figure why exactly I thought this is required.  It is very likely that you're right and at the time what I had in mind is a conversion of the timestamp type to a timeuuid by timestamp related functions.  Since then we've fixed the documentation to disambiguate `timestamp` used as the CQL type, vs. the write timestamp in `USING TIMESTAMP` or `SELECT writetime`.

**Comment by avikivity** [comment]
Not a bug, not backporting.

**Comment by mykaul** [comment]
> Not a bug, not backporting.

I thought @nyh already did backport it to 5.1 (we wish to have it in enterprise 2022.2.1 for a customer)

**Comment by nyh** [comment]
No, I did not backport it to any open-source release exactly because of Avi's sentiment that it's not a bug and we normally only backport bug fixes. I was specifically asked to backport it to one specific Scylla Enterprise subrelease (not even the main branch) and did that and later @vladzcloudius backported it to a second specific Scylla Enterprise subrelease. But it's not backported to anything else.
That's the current situation. If you feel it should be different, please let me know.

**Comment by mykaul** [comment]
> No, I did not backport it to any open-source release exactly because of Avi's sentiment that it's not a bug and we normally only backport bug fixes. I was specifically asked to backport it to one specific Scylla Enterprise subrelease (not even the main branch) and did that and later @vladzcloudius backported it to a second specific Scylla Enterprise subrelease. But it's not backported to anything else. That's the current situation. If you feel it should be different, please let me know.

That's OK - thanks.
