### ISSUE TITLE
system_tables_test: test_default_content: AssertionError: Unexpected memory value: 1019215872

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12522]
Seen first in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/175/testReport/system_tables_test/TestRuntimeInfoTable/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_default_content/
Scylla version abc43f97c916
```
AssertionError: Unexpected memory value: 1019215872
assert 1019215872 == 1073741824
  +1019215872
  -1073741824
```

**Comment by bhalevy** [comment]
@tchaikov can you please look into this issue?
I'm not sure if anything changed recently in regarding memory accounting.
Let's identify first what caused this and determine if the test needs to be adjusted or something needs to be fixed on the scylla/seastar side of things.

**Comment by tchaikov** [comment]
@bhalevy ack. Will take a look early tomorrow.

**Comment by tchaikov** [comment]
strange enough, i am not able to reproduce this issue locally, 
```
platform linux -- Python 3.9.14, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
Using --randomly-seed=2264447499
rootdir: /home/kefu/dev/scylla-dtest, configfile: pytest.ini
plugins: typeguard-2.13.3, metadata-2.0.4, forked-1.4.0, xdist-2.2.0, timeout-1.4.2, subtests-0.5.0, repeat-0.9.1, randomly-3.5.0, html-3.1.1, elk-reporter-0.2.1
timeout: 2700.0s
timeout method: signal
timeout func_only: False
collected 4137 items / 4136 deselected / 1 selected

system_tables_test.py::TestRuntimeInfoTable::test_default_content PASSED                                                                                                                                                                                                 [100%]
```
```console
$ echo $(cd ~/dev/scylladb/; git rev-parse HEAD)
abc43f97c916716056b734fe28b2dfc82c2f727f
```

will take a closer look.

**Comment by tchaikov** [comment]
i see. the debug build survives this test, while the release build does not.

**Comment by avikivity** [comment]
Backported to 5.2. Doesn't exist in 5.1.

**Comment by bhalevy** [comment]
@tchaikov the test still fails in a similar way, please look onto it and see if this issue needs to be reopened or should a new one be opened.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/198/testReport/system_tables_test/TestRuntimeInfoTable/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_default_content/
```
AssertionError: Unexpected memory value: 1071644672
assert 1071644672 == 1073741824
  +1071644672
  -1073741824
```

**Comment by tchaikov** [comment]
ack. i am on this.

**Comment by tchaikov** [comment]
i am testing with

- scylladb: the master HEAD + release build
- scylla-dtest: next HEAD
- scylla-ccm: next HEAD

with following command line
```console
$ pytest --cassandra-dir=$HOME/dev/scylladb/build/release \
  system_tables_test.py::TestRuntimeInfoTable::test_default_content
```

not able to reproduce this issue. still looking..

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/204/testReport/system_tables_test/TestRuntimeInfoTable/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_default_content/
```
AssertionError: Unexpected memory value: 1071644672
assert 1071644672 == 1073741824
  +1071644672
  -1073741824
```

It always reproduces for me with `export SCYLLA_EXT_OPTS="--smp 2"`

**Comment by tchaikov** [comment]
@bhalevy i am fine reopening this. just wanted know if you managed to reproduce it or it's just the jenkins.

**Comment by bhalevy** [comment]
> @bhalevy i am fine reopening this. just wanted know if you managed to reproduce it or it's just jenkins.

It is readily reproduced locally for me with --smp=2 as I mentioned sbove (but not with 1), for dome reason there are 2MB miising from the total.
Maybe it'd be best to open a new issue for that since it might be a different bug.

**Comment by tchaikov** [comment]
thanks, Benny. reproduced with `--smp=2`.

**Comment by tchaikov** [comment]
it's a different issue. as this is mostly related to the test, probably we can repurpose this issue for the new bug.
