### ISSUE TITLE
Bootstrapping server stuck in `waiting for schema information to complete` loop for a minute, causing tests to time out

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#12546]
Recently next promotions started failing due to a new reason: a raft upgrade test is timing out before even starting, because it does not manage to obtain a cluster from the cluster pool within 5 minutes.

Looking at the logs, it turns out that we were indeed building a cluster for this test, but it took over 5 minutes to do so, so we exceed the default 5 minute timeout.

Digging more, the difference from other clusters which also participated in this run appears to be that for this cluster, the second and third node that were bootstrapping got stuck for 1 minute "waiting for schema information to complete".

Attaching logs from one of the failed next promotions
[x86_64.zip](https://github.com/scylladb/scylladb/files/10436084/x86_64.zip)

In `debug/topology_raft_disabled.test_raft_upgrade.1.log` we see the following:
```
==================================== ERRORS ====================================
_____________ ERROR at setup of test_raft_upgrade_with_node_remove _____________
...
E           TimeoutError
...
------------------------------ Captured log setup ------------------------------
14:05:12.045 DEBUG> before_test for test_raft_upgrade_with_node_remove
...
14:05:12.208 DEBUG> RESTClient fetching GET http+unix://api/cluster/before-test/test_raft_upgrade_with_node_remove
=============================== warnings summary ===============================
...
```

The test failed at setup, it was waiting for the `api/cluster/before-test/` endpoint. This is the test framework endpoint used to obtain clusters for test.

Looking into the test framework logs, we can see:
```
14:05:12.563 INFO> [debug/topology_raft_disabled.test_raft_upgrade.1] Waiting for new cluster for test debug/topology_raft_disabled.test_raft_upgrade.1::test_raft_upgrade_with_node_remove...
14:05:12.563 INFO> [debug/topology_raft_disabled.test_raft_upgrade.1] Created new cluster 32241226-965f-11ed-a08c-1418774357e7
...
14:05:59.922 INFO> [debug/topology_raft_disabled.test_raft_upgrade.1] Cluster ScyllaCluster(name: 32241226-965f-11ed-a08c-1418774357e7, running: ScyllaServer(260, 127.219.61.60, 1cba11fc-7786-4763-a57a-4b9cca70542e), stopped: ) added ScyllaServer(260, 127.219.61.60, 1cba11fc-7786-4763-a57a-4b9cca70542e)
...
14:08:08.590 INFO> [debug/topology_raft_disabled.test_raft_upgrade.1] Cluster ScyllaCluster(name: 32241226-965f-11ed-a08c-1418774357e7, running: ScyllaServer(260, 127.219.61.60, 1cba11fc-7786-4763-a57a-4b9cca70542e), ScyllaServer(275, 127.219.61.32, cad5ae04-c476-49a4-bc61-e7b8e1759414), stopped: ) added ScyllaServer(275, 127.219.61.32, cad5ae04-c476-49a4-bc61-e7b8e1759414)
...
14:10:32.059 INFO> [debug/topology_raft_disabled.test_raft_upgrade.1] Cluster ScyllaCluster(name: 32241226-965f-11ed-a08c-1418774357e7, running: ScyllaServer(260, 127.219.61.60, 1cba11fc-7786-4763-a57a-4b9cca70542e), ScyllaServer(275, 127.219.61.32, cad5ae04-c476-49a4-bc61-e7b8e1759414), ScyllaServer(329, 127.219.61.9, 50513b74-6547-4a58-b107-96340579a71f), stopped: ) added ScyllaServer(329, 127.219.61.9, 50513b74-6547-4a58-b107-96340579a71f)
```

the cluster object was created at `14:05:12`, the third server was added at `14:10:32`. That's over 5 minutes, so over the timeout.

The second and third nodes that were added had IDs `275` and `329`. Looking at `debug/scylla-275.log`, we see a pattern like this:
```
INFO  2023-01-17 14:07:00,384 [shard 0] storage_service - waiting for schema information to complete
INFO  2023-01-17 14:07:00,463 [shard 0] schema_tables - Schema version changed to 59adb24e-f3cd-3e02-97f0-5b395827453f
INFO  2023-01-17 14:07:00,464 [shard 0] storage_service - Set host_id=1cba11fc-7786-4763-a57a-4b9cca70542e to be owned by node=127.219.61.60
...
INFO  2023-01-17 14:07:01,385 [shard 0] storage_service - waiting for schema information to complete
INFO  2023-01-17 14:07:02,385 [shard 0] storage_service - waiting for schema information to complete
... more of the same ...
INFO  2023-01-17 14:07:59,418 [shard 0] storage_service - waiting for schema information to complete
INFO  2023-01-17 14:08:00,470 [shard 0] storage_service - waiting for schema information to complete
INFO  2023-01-17 14:08:00,687 [shard 0] migration_manager - Requesting schema pull from 127.219.61.60:0
INFO  2023-01-17 14:08:00,687 [shard 0] migration_manager - Pulling schema from 127.219.61.60:0
INFO  2023-01-17 14:08:01,408 [shard 0] schema_tables - Creating keyspace system_auth
INFO  2023-01-17 14:08:02,566 [shard 0] schema_tables - Creating keyspace system_distributed
```

The node was stuck in a loop that printed `waiting for schema information to complete` each second, for about a minute. After that there was a `Requesting schema pull from 127.219.61.60:0` which caused it to get unstuck.

The same thing happened in `debug/scylla-329.log`.

This was observed in two pipelines: https://jenkins.scylladb.com/job/scylla-master/job/next/ and https://jenkins.scylladb.com/job/scylla-enterprise/job/next/. Note that the latter uses the `enterprise` branch from scylla-enterprise repo which is created by merging the `master` branch from OSS periodically.

From what I know, this was actually first observed yesterday in the enterprise job on commit https://github.com/scylladb/scylla-enterprise/commit/563ba3071cbf75be19d4b6db144771fc6849fde3. On the master job it was first observed today on commit 9e17564c7038faba7d94bf4de60dd6837368b73b.

Perhaps some change was merged recently that introduced or increased the probability of this `waiting for schema information to complete` problem, or generally slowed Scylla startup?

cc @avikivity @bhalevy @kostja @asias @tgrabiec

**Comment by asias** [comment]
We saw 'storage_service - waiting for schema information to complete" issue in the past.  I believe Tomek has fixed it. We hit it again? Bootstrap process will wait for schema to match before it can proceed.

**Comment by tgrabiec** [comment]
I think the culprit is that bootstrap takes too long, longer than `migration_delay` (60 s), so schema pull is delayed due to this code in migration_manager::maybe_schedule_schema_pull():

```

    if (db.get_version() == replica::database::empty_version || runtime::get_uptime() < migration_delay) {
        // If we think we may be bootstrapping or have recently started, submit MigrationTask immediately
        mlogger.debug("Submitting migration task for {}", endpoint);
        return submit_migration_task(endpoint);
    }
``` 

This is the logic which we inherited from Cassandra, so it's been like this since the dawn of time.

This is invoked when we notice schema mismatch in gossip. If we notice it and `runtime::get_uptime() < migration_delay`, we pull immediately. If not, we assume this is not during bootstrap and don't make a full pull in the hope that there is a schema propagation in progress and the mismatch will be resolved by the in-flight RPCs with schema deltas.

The code schedules a check after migration_delay and will pull anyway if the discrepancy is still there. This is why it gets unblocked after 60s.

So something caused bootsrap to take longer than 60s, that's why it's failing now. 

We should improve this and rely on a flag "in_bootstrap" or something instead of time.

**Comment by kbr-scylla** [comment]
Hmm... indeed, scylla-275.log, first timestamp:
```
WARN  2023-01-17 14:06:00,201 seastar - Seastar compiled with default allocator, will not abort on bad_alloc
```
first "waiting for schema":
```
INFO  2023-01-17 14:07:00,384 [shard 0] storage_service - waiting for schema information to complete
```
that's just over 60 seconds!

So there are two problems:
1. the unreliable piece of code that you presented,
2. bootstrap getting slower over time, and the only way we observe this is stupid next promotion failures like this...

Problem 1 might be easy to deal with, but how do we prevent bootstrap from getting slower? Do we even care? I think we do care for quick testing...

**Comment by kostja** [comment]
But why does it get slower?

**Comment by kbr-scylla** [comment]
>  But why does it get slower?

No idea. Some recently merged change slowed it down, and we started to hit this problem.

**Comment by kbr-scylla** [comment]
> If not, we assume this is not during bootstrap and don't make a full pull in the hope that there is a schema propagation in progress and the mismatch will be resolved by the in-flight RPCs with schema deltas.

@tgrabiec Does this logic take into account the later-introduced `serialized_action` / `_schema_pulls` thing? Maybe with this, it doesn't make sense to delay the pulls ever. We already have protection from doing too many pulls anyway.

**Comment by tgrabiec** [comment]
> @tgrabiec Does this logic take into account the later-introduced `serialized_action` / `_schema_pulls` thing? Maybe with this, it doesn't make sense to delay the pulls ever. We already have protection from doing too many pulls anyway.

It does, but the mechanism you mention serializes pull, it doesn't prevents the first pull. Here, we avoid any pulls. They are more expensive the incremental broadcast which happens on schema changes because they read the whole schema.

**Comment by tgrabiec** [comment]
Also, full pulls would be initiated by many nodes, with many nodes. Serialization has the scope of a particular endpoint we pull from. We're missing optimizations there which would allow us to avoid redundant pulls with different nodes which share the schema version.

**Comment by kbr-scylla** [comment]
We haven't seen this issue for a long time, closing.
