### ISSUE TITLE
Implement native reverse queries

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12557]
Currently scylla implements reverse queries in "legacy half reverse" mode
See [docs/dev/reverse-reads.md](https://github.com/scylladb/scylladb/blob/563998b69a1cb2db4e4dba7eb9f9703204588ffd/docs/dev/reverse-reads.md) for more information.
In this mode, slices that are returned by replicas in reverse order, with respect to their boundaries, yet each slice is ordered using the forward schema and it requires reversing on the coordinator side.  This is inefficient, and triggered e.g. #11199.

With native reverse order, the replica would returned slices that are already reversed (as they are consumed from readers nowadays) and the coordinator will just need to consume them using the reversed schema, without needing to reverse the frozen mutations.

**Comment by bhalevy** [comment]
Cc @tgrabiec @denesb

**Comment by avikivity** [comment]
This is just about the intra-page frozen mutation query, yes?

**Comment by bhalevy** [comment]
Yes, as far as I understand.

**Comment by bhalevy** [comment]
@paszkow I added a new label for "technical debt" which are notable, strategic backlog items.
Please add this to the team queue.
Note that I submitted https://github.com/scylladb/scylladb/pull/13444, but @denesb had some reservations about it and he wants to solve the problem in a cleaner way - so please consult with him about the details.
The gist of it is that for asking to read the results in reverse order, the coordinator should send the reverse-schema version (which is the version of the reverse-schema, that by design is also the reverse (compliment) of the version of the (native order) schema), and that will flag the replica to run a reverse query and send the results in native-reverse order.

I think this requires a quite deep dive into our mutation-fragment streaming mechanisms, but that's good as an educational work item.

**Comment by dani-tweig** [comment]
@mykaul , the PR is still in review.
Should we change milestone to 6.2?

**Comment by mykaul** [comment]
> @mykaul , the PR is still in review. Should we change milestone to 6.2?

Indeed, and I did.

**Comment by paszkow** [comment]
The PR is actually done and passed the reviews. It is not yet merged, because there is a corresponding PR to dtest that extends tests for reversed queries waiting to be merged. So it potentially could part of 6.1 but definitely 6.2.

**Comment by avikivity** [comment]
There's a new mechanism to support upgrade tests in test.py (by @Jadw1, but I can't find it). Please follow up with upgrade tests in test.py, they catch problems earlier.

**Comment by Jadw1** [comment]
> There's a new mechanism to support upgrade tests in test.py (by @Jadw1, but I can't find it). Please follow up with upgrade tests in test.py, they catch problems earlier.

https://github.com/scylladb/scylladb/pull/20055 adds an error injection which allows to suppress specified cluster features. Example test: https://github.com/scylladb/scylladb/blob/master/test/topology_custom/test_deprecating_cluster_features.py#L54
