### ISSUE TITLE
types: is_tuple(): doesn't handle reverse types

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12576]
Currently reverse types match the default case (false), even though they might be wrapping a tuple type. One user-visible effect of this is that a schema, which has a reversed<frozen<UDT>> clustering key component, will have this component incorrectly represented in the schema cql dump: the UDT will loose the frozen attribute. When attempting to recreate this schema based on the dump, it will fail as the only frozen UDTs are allowed in primary key components.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.
