### ISSUE TITLE
 mutation_compactor: last range tombstone in partition will trigger validation error if covered by partition tombstone

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12575]
Currently all consumed range tombstone changes are unconditionally forwarded to the validator. Even if they are shadowed by a higher level tombstone and/or purgable. This can result in a situation where a range tombstone change was seen by the validator but not passed to the consumer. The validator expects the range tombstone change to be closed by end-of-partition but the end fragment won't come as the tombstone was dropped, resulting in a false-positive validation failure.

Introduced by: 302917f63dfebd84e0af2f228db2a102b9f57979
Affected branches: 5.2

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. I think 5.0 isn't vulnerable.

**Comment by avikivity** [comment]
It was later dequeued. @denesb please re-backport

**Comment by denesb** [comment]
> It was later dequeued. @denesb please re-backport

No need, 5.1 wasn't vulnerable in the first place. 5.2 backport was not dequeued. So we are all good.

**Comment by raphaelsc** [comment]
> > It was later dequeued. @denesb please re-backport
> 
> No need, 5.1 wasn't vulnerable in the first place. 5.2 backport was not dequeued. So we are all good.

@denesb I think there's an use-after-move in the patch. Courtesy of clang-tidy.

@avikivity we should seriously consider adding clang-tidy as part of our CI. we can run 'clang-tidy \<file\> --checks=bugprone-use-after-move' against the files touched by patches. use-after-move bug is a plague (see https://github.com/scylladb/scylladb/pull/13386) and static analyzers are our best friend. note they can report false positives, so perhaps we should start by warning about them, rather than refusing a CI run to be successful. although warnings only are usually ignored. Perhaps make it part of maintainer cookbook...

**Comment by mykaul** [comment]
I think it's worth opening a separate issue for clang-tidy execution. We can certainly run it if it doesn't take too much resources, etc - then evaluate its usefulness after a month or so.

**Comment by denesb** [comment]
> > > It was later dequeued. @denesb please re-backport
> > 
> > 
> > No need, 5.1 wasn't vulnerable in the first place. 5.2 backport was not dequeued. So we are all good.
> 
> @denesb I think there's an use-after-move in the patch. Courtesy of clang-tidy.
> 
> @avikivity we should seriously consider adding clang-tidy as part of our CI. we can run 'clang-tidy <file> --checks=bugprone-use-after-move' against the files touched by patches. use-after-move bug is a plague (see #13386) and static analyzers are our best friend. note they can report false positives, so perhaps we should start by warning about them, rather than refusing a CI run to be successful. although warnings only are usually ignored. Perhaps make it part of maintainer cookbook...

Good catch, fix here: https://github.com/scylladb/scylladb/pull/13749

**Comment by denesb** [comment]
> (we will need to backport the fix too)

The move-after free is benign currently as the validator doesn't check clustering keys, which is the only thing destroyed by the move. The tombstone and fragment kind stays intact, and that is the only thing this specific validator is configured to look at currently.

So no need to backport https://github.com/scylladb/scylladb/pull/13749.
