### ISSUE TITLE
Turn consistent-cluster-management ON by default in new clusters

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#12572]
We should turn consistent-cluster-management ON by default in new installations.

The feature is now generally available and is barely a feature - it fixes a number of gotchas in schema propagation code. The only downside (and why we call it a feature) is that now Scylla requires a majority of nodes to be around to do schema changes. This is acceptable in new deployments.

The fix is to change the default-installed scylla.yaml to turn the feature ON (the default is OFF). 

People using existing yaml files will continue using eventual schema propagation, unless consistent-cluster-management is explicitly requested.

**Comment by kostja** [comment]
Avi: We may need to recommend disabling it for two dc deployments. 
I think a comment to the config option explaining possible dangers of 2-dc setup can serve as such recommendation

**Comment by kbr-scylla** [comment]
>  I think a comment to the config option explaining possible dangers of 2-dc setup can serve as such recommendation

We explain everything in the Raft docs, we can leave a reference to that.

Why would we recommend disabling it for two dc deployments? In the future Raft is going to be mandatory. It wouldn't make sense to make mandatory a feature that previously wasn't recommended.

**Comment by avikivity** [comment]
Was already backported to 5.2. Not backporting further, this is a major change.
