### ISSUE TITLE
raft: support associative commands for faster replay

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#12581]
When bootstrapping a new node, replaying schema changes can take a long time if the current log is long. We observed timeouts in tests due to this, where there were 40 changes to replay.

One possible optimization to combat this would be to leverage the fact that those commands are associative:

```
apply(m1)
apply(m2)
```

is equivalent to:

```
apply(m1 + m2); 
```

This would be the case if m1 and m2 came from a snapshot.

Raft could first combine the commands into a single command and apply the combined command, and treat this event as if the whole batch was applied.

**Comment by tgrabiec** [comment]
@kostja @gleb-cloudius @kbr-

**Comment by tgrabiec** [comment]
Refs https://github.com/scylladb/scylladb/issues/12591

**Comment by gleb-cloudius** [comment]
Raft provides an array of commands to apply exactly to support such cases. It is a matter of `group0_state_machine::apply` to be smart and not apply command one by one if there is more efficient way to do it.

**Comment by avikivity** [comment]
I think it could be optimized further. For example, apply([insert mutation, delete mutation]) is larger than apply([combine(insert mutation, delete mutation)]).

We could have the state machine interface expose a try_combine() function that attempts to merge commands.

**Comment by gleb-cloudius** [comment]
> I think it could be optimized further. For example, apply([insert mutation, delete mutation]) is larger than apply([combine(insert mutation, delete mutation)]).

What "larger" means here?

> 
> We could have the state machine interface expose a try_combine() function that attempts to merge commands.

apply() gets all of the commands together. It can merge them in any way it finds it useful.
