### ISSUE TITLE
table::compaction_group_for_token should use signed arithmetic

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12595]
Currently, `compaction_group_for_token`, uses unsigned arithmetic to calculate which compaction_group owns a given token.
See https://github.com/scylladb/scylladb/blob/ebc100f74fc2d8946cf4810499ce1f0c70ba5ea8/replica/table.cc#L523-L529
However, this doesn't follow the "native" token ordering which is based on signed arithmetic, which determines that the range for `_compaction_groups[number_of_cg - 1]` is ordered before `_compaction_groups[0]`.
This is problematic for https://github.com/scylladb/scylladb/issues/12594
and in particular around the token with value `std::numeric_limits<int64_t>::min()` which is ambiguos.
We use it to map back both the minimum and maximum tokens in https://github.com/scylladb/scylladb/blob/ebc100f74fc2d8946cf4810499ce1f0c70ba5ea8/dht/token.cc#L22-L28

We get around this when normalizing the token value here:
https://github.com/scylladb/scylladb/blob/ebc100f74fc2d8946cf4810499ce1f0c70ba5ea8/dht/token.hh#L33-L40

https://github.com/scylladb/scylladb/blob/ebc100f74fc2d8946cf4810499ce1f0c70ba5ea8/dht/token.hh#L49-L51

**Comment by avikivity** [comment]
Agree we should bias the token so it fits in [0, max].

**Comment by avikivity** [comment]
Not a bug, not backporting.
