### ISSUE TITLE
Schema merging of incremental changes is inefficient

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#12591]
Currently, applying a schema change on a replica works like this:

1. Collect all affected keyspaces from incoming mutations
2. Read current state of schema
3. Apply the mutations
4. Read new state of schema

The "Read ... state of schema" step reads all kinds of schema objects. In particular, to read the "table" objects, it does the following:
```
for every affected keyspace k:
     read all mutations from system_schema.tables for k
     extract all existing table names from those mutations
     for every existing table:
           read mutations from {tables, columns, indexes, view_virtual_columns, ...} for that table 
```

As you can see, the number of reads performed is O(nr tables in a keyspace), not O(nr tables in a change).

This means that making a sequence of schema changes like adding a table is quadratic.

Another aspect which magnifies this is that we don't read those tables using a single scan, but issue individual queries for each table separately.

We could optimize this by collecting names of affected tables and only read mutations for these.

Another possible optimization, for cases when many tables are indeed affected, is to issue a single scan to read all tables in a keyspace.

**Comment by mykaul** [comment]
Hoping to see all of this fixed in 5.3. If not, we can either defer to next release, or split what was not fully fixed to a different issue.

**Comment by tgrabiec** [comment]
> We could optimize this by collecting names of affected tables and only read mutations for these.

This was fixed in https://github.com/scylladb/scylladb/pull/12592

> Another possible optimization, for cases when many tables are indeed affected, is to issue a single scan to read all tables in a keyspace.

This wasn't started and we're not planning to fix it any time soon.

**Comment by DoronArazii** [comment]
Okay, closing this one as completed.
@tgrabiec for the longterm, do we have an issue to cover the second section ^^

**Comment by tgrabiec** [comment]
> Okay, closing this one as completed. @tgrabiec for the longterm, do we have an issue to cover the second section ^^

No, we don't.

**Comment by DoronArazii** [comment]
I will open one and will add it to the backlog.
