### ISSUE TITLE
Backport test.py efficiency improvements

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#12617]
Post-hoc issue for backporting the following PRs to 5.2 branch:
- https://github.com/scylladb/scylladb/pull/12588 - don't use a range scan query to detect CQL availability; these queries are super inefficient and may be problematic especially in debug mode
- https://github.com/scylladb/scylladb/pull/12542 - disable commitlog segment preallocation, reducing pressure on disk

cc @avikivity

**Comment by kbr-scylla** [comment]
The first PR is still waiting to get merged, hopefully it will be in by tomorrow. I'll backport both to 5.2 once it's ready.

**Comment by kbr-scylla** [comment]
There are some other improvements and fixes, I think they might be worth backporting too (some of them make debugging failures easier, for example), although they are probably optional:
- https://github.com/scylladb/scylladb/pull/12613
- https://github.com/scylladb/scylladb/pull/12549
- https://github.com/scylladb/scylladb/pull/12564
- https://github.com/scylladb/scylladb/pull/12563
- https://github.com/scylladb/scylladb/pull/12560

**Comment by avikivity** [comment]
I think it's better to backport all of them, so we don't have slightly different versions around.

**Comment by kbr-scylla** [comment]
The backport was done, closing.
