### ISSUE TITLE
test.py: AF_UNIX path too long

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#12622]
When running unit-tests inside a folder located in a long path, the run will fail with AF_UNIX path too long

For example, I created a test job https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-temp-benipeled
The workspace for this job is /jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled

When running unit-tests, it fails on `AF_UNIX path too long

AF_UNIX path too long
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/./test.py", line 1389, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/./test.py", line 1356, in main
    await run_all_tests(signaled, options)
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/./test.py", line 1227, in run_all_tests
    await reap(done, pending, signaled)
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/./test.py", line 1209, in reap
    result = coro.result()
             ^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/./test.py", line 196, in run
    await test.run(options)
  File "/usr/lib64/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/test/pylib/scylla_cluster.py", line 972, in get_cluster_manager
    yield manager
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/./test.py", line 882, in run
    await manager.start()
  File "/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/test/pylib/scylla_cluster.py", line 737, in start
    await self.site.start()
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_runner.py", line 162, in start
    self._server = await loop.create_unix_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/unix_events.py", line 318, in create_unix_server
    sock.bind(path)
OSError: AF_UNIX path too long
As can see from the traceback, it happens when starting scylla cluster by
test/pylib/scylla_cluster.py::ScyllaClusterManager function - the function tries to
open a UNIX socket in a long path - something like
/jenkins/workspace/scylla-master/releng-testing/next-temp-benipeled/scylladb/testlog/release/manager-lidshrit/api
which is longer than UNIX's 108 character limit

I didn't find a way to increase this limit (except for re-compiling the kernel)

From time to time we saw it on other jobs as well, ex. byo (which has a long path)

**Comment by nyh** [comment]
Yes, this is unfortunately a long-standing (we're talking decades...) of Unix-domain sockets. I can think of two workarounds that will solve this problem:
1. Put the socket in /tmp literally, not $TMPDIR. In the past we (not me!) wanted to put test-related files in a specific directory where it uses a known disk and where it is saved, but there is no specific reason why the sockets need to be in $TMPDIR.
2. Use **relative** paths for the unix-domain socket - change the working directory to $TMPDIR and create/use the socket without a full path. https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars says that this will work.

**Comment by avikivity** [comment]
Why do we even have unix-domain sockets in test.py?

**Comment by nyh** [comment]
> Why do we even have unix-domain sockets in test.py?

I feel that test.py became too complicated, too monolithic, and much bigger than the tests that actually use its features, but that's a different discussion and we don't need to hold it now (or even ever - if it works, it works). But specifically to answer your question: They wanted test.py to handle the cluster of Scylla processes (a la ccm) and the individual tests the communicate with test.py to enquire or change this cluster - and they do this using an HTTP server over a unix-domain socket.

**Comment by DoronArazii** [comment]
@nyh do you volunteer to be the assignee of this case?

**Comment by nyh** [comment]
Simple reproducer:
```
$ pwd
/tmp/abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz/scylla
$ ./test.py --mode=dev test_concurrent_schema
...
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_runner.py", line 162, in start
    self._server = await loop.create_unix_server(
  File "/usr/lib64/python3.10/asyncio/unix_events.py", line 307, in create_unix_server
    sock.bind(path)
OSError: AF_UNIX path too long
```

**Comment by nyh** [comment]
Sent a fix in https://github.com/scylladb/scylladb/pull/12667

**Comment by kostja** [comment]
The reason Unix sockets are preferred to TCP is to avoid clashes in port numbers, especially if a test hangs.

**Comment by nyh** [comment]
> The reason Unix sockets are preferred to TCP is to avoid clashes in port numbers, especially if a test hangs.

This is not a compelling reason, because you can easily have the server pick a unique port (listen on port 0), and then tell the client which port number it chose. There can be no clashes and you usually have a few tens of thousands port numbers available so you won't run out of them either.

But there's also nothing wrong with UNIX-domain sockets. It's a perfectly valid choice and does work if you cater to its weird requirements. Let's keep UNIX-domain sockets - they are a nice blast from the past.

**Comment by avikivity** [comment]
Note: there are "more correct" symbolic names for /tmp.

**Comment by avikivity** [comment]
Not backporting, this is test-only, and under circumstances unlikely to reproduce for a branch.

**Comment by nyh** [comment]
> Note: there are "more correct" symbolic names for /tmp.

Not really - I assume you mean `$TMPDIR`, but we deliberately override this in test.py and possibly in Jenkins, and the whole point of this patch is that no matter in which long-named directory the user chose to put the regular temporary files, these socket files should be in the short-named "/tmp" and not in any other fancier (and long-named) directory.
