### ISSUE TITLE
docs: Issue in page Scylla Repair

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#12624]
I would like to report an issue in page https://docs.scylladb.com/branch-5.1/operating-scylla/procedures/maintenance/repair

### Problem
'Repair Base Operation' should be 'Repair Based Node Operations' as far as I know.
@eliransin @asias  please confirm

**Comment by annastuchlik** [comment]
You're right. However, I'm not fixing the section you're referring to because it's outdated and should be removed (there's an up-to-date page about Repair Based Node Operations). The following PR fixes the problem:  https://github.com/scylladb/scylladb/pull/12984

**Comment by annastuchlik** [comment]
Fixed with https://github.com/scylladb/scylladb/pull/12984
