### ISSUE TITLE
Handle EDQUOT error just like ENOSPC

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#12626]
When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.

**Comment by mykaul** [comment]
> When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.

Do you have a reproduction / test that it doesn't?

**Comment by soyacz** [comment]
> > When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.
> 
> Do you have a reproduction / test that it doesn't?

Not yet, we can plan adding it - we start using https://chaos-mesh.org/docs/simulate-io-chaos-on-kubernetes/ so we'll be able to simulate it easily.

**Comment by mykaul** [comment]
> > > When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.
> > 
> > 
> > Do you have a reproduction / test that it doesn't?
> 
> Not yet, we can plan adding it - we start using https://chaos-mesh.org/docs/simulate-io-chaos-on-kubernetes/ so we'll be able to simulate it easily.

I'm closing this item for the time being.
Let's re-open if indeed (1) XFS returns EDQUOT and (2) Scylla doesn't handle it properly.

As for simulating - just assign an XFS quota on a mount the Scylla K8S operator and fill that mount point, no need for anything artifical.

**Comment by avikivity** [comment]
> > > > When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.
> > > 
> > > 
> > > Do you have a reproduction / test that it doesn't?
> > 
> > 
> > Not yet, we can plan adding it - we start using https://chaos-mesh.org/docs/simulate-io-chaos-on-kubernetes/ so we'll be able to simulate it easily.
> 
> I'm closing this item for the time being. Let's re-open if indeed (1) XFS returns EDQUOT and (2) Scylla doesn't handle it properly.
> 
> As for simulating - just assign an XFS quota on a mount the Scylla K8S operator and fill that mount point, no need for anything artifical.

XFS will surely return EDQUOT (just grep the source), and ScyllaDB won't handle it correctly (ditto).

**Comment by mykaul** [comment]
> > > > > When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.
> > > > 
> > > > 
> > > > Do you have a reproduction / test that it doesn't?
> > > 
> > > 
> > > Not yet, we can plan adding it - we start using https://chaos-mesh.org/docs/simulate-io-chaos-on-kubernetes/ so we'll be able to simulate it easily.
> > 
> > 
> > I'm closing this item for the time being. Let's re-open if indeed (1) XFS returns EDQUOT and (2) Scylla doesn't handle it properly.
> > As for simulating - just assign an XFS quota on a mount the Scylla K8S operator and fill that mount point, no need for anything artifical.
> 
> XFS will surely return EDQUOT (just grep the source), and ScyllaDB won't handle it correctly (ditto).

OK, re-opening. @bhalevy - I assume your team should handle this?

**Comment by bhalevy** [comment]
Why do we care about EDQUOT?

For the sake of the argument, if we handle it like an I/O error, ENOSPC in particular, and isolate the node, I'd expect the admin to fix the environment are remove any quota restrictions, as scylla is not designed to run as a service on a general purpose server.

**Comment by bhalevy** [comment]
> Why do we care about EDQUOT?
> 
> For the sake of the argument, if we handle it like an I/O error, ENOSPC in particular, and isolate the node, I'd expect the admin to fix the environment and remove any quota restrictions, as scylla is not designed to run as a service on a general purpose server.

**Comment by bhalevy** [comment]
> When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.

I suggest that the proper handling would be to follow ENOSPC handling as effectively, running out of quota is equivalent to running out of storage space (just that it's tunable).

**Comment by avikivity** [comment]
> > When using XFS quota it filesystem may return EDQUOT error. Scylla should handle it properly.
> 
> I suggest that the proper handling would be to follow ENOSPC handling as effectively, running out of quota is equivalent to running out of storage space (just that it's tunable).

Yes, I don't see any reason to play games.

Separately, the operator should monitor disk usage and increase quota ahead of time.

**Comment by mykaul** [comment]
Setting this to 5.3, but we may wish to have it backported later to 5.2.x.

**Comment by avikivity** [comment]
Not a regression, not backporting. There's something to be said about this being a bug, but let's deal with it later.
