### ISSUE TITLE
docs: Issue in page Upgrade Guide - ScyllaDB Enterprise 2022.x.y to 2022.x.z for Ubuntu 20.04

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylladb#12658]
I would like to report an issue in page https://docs.scylladb.com/master/upgrade/upgrade-enterprise/upgrade-guide-from-2022.x.y-to-2022.x.z/upgrade-guide-from-2022.x.y-to-2022.x.z-ubuntu-20-04

### Problem

scylla-enterprise-server  is not existing as service name
(but package name is still scylla-enterprise !!!)

###  Suggest a fix

please change SERVICE name to scylla-server

**Comment by tarzanek** [comment]
it's in most places ? 
e.g. https://docs.scylladb.com/master/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2021.1-to-2022.1-ubuntu.html too

**Comment by annastuchlik** [comment]
This issue affects the latest upgrade guides for ScyllaDB Enterprise:
https://docs.scylladb.com/stable/upgrade/upgrade-enterprise/upgrade-guide-from-2022.x.y-to-2022.x.z/
https://docs.scylladb.com/master/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/

**Comment by annastuchlik** [comment]
As this bug affects the versions that are now referred to by the users for upgrades, the fixing PR **must be backported to version 5.1**.

**Comment by annastuchlik** [comment]
Fixed with https://github.com/scylladb/scylladb/pull/12679 and https://github.com/scylladb/scylladb/pull/12698.

**Comment by avikivity** [comment]
Looks like it was already backported. @denesb please remember to drop the backport candidate label with a note when backporting.
