### ISSUE TITLE
doc: fix the documentation redirects to the Cloud docs

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#12672]
Some blog posts include outdated links to the Cloud documentation (the Cloud documentation used to be part of the main ScyllaDB doc set), but redirects are not working for files moved at some point to the AWS directory. For example, this link was reported via our Slack:
https://docs.scylladb.com/scylla-cloud/cloud-setup/cloud-prom-proxy

Redirects to appropriate pages at https://cloud.docs.scylladb.com/ should be added.

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. 5.0 doesn't have this.

**Comment by annastuchlik** [comment]
@avikivity Great, thank you so much.
