### ISSUE TITLE
docs: Issue in page Scylla Snitches

### ISSUE THREAD

**Issue by mixellent** [scylladb/scylladb#12691]
I would like to report an issue in page https://docs.scylladb.com/branch-5.1/operating-scylla/system-configuration/snitch

### Problem
Missing full stop in the following paragraph.

SimpleSnitch
Use the SimpleSnitch when working with single cluster deployments and all the nodes are under the same datacenter The SimpleSnitch binds all the nodes to the same Rack and datacenter and is recommended to be used only in single datacenter deployments.

###  Suggest a fix
SimpleSnitch
Use the SimpleSnitch when working with single cluster deployments and all the nodes are under the same datacenter. The SimpleSnitch binds all the nodes to the same Rack and datacenter and is recommended to be used only in single datacenter deployments.

**Comment by mykaul** [comment]
@mixellent - will you be sending a PR to fix it?

**Comment by mixellent** [comment]
@mykaul thanks for pointing that it, didn't notice the "edit page" link. Closing this (added PR #12692)
