### ISSUE TITLE
system_auth: Refactor to use EverywhereStrategy

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#12697]
There is a similar and general issue about this #1796 however here we try to deal with the specific chalenge of `system_auth` as it creates too much friction for users.

Our documented procedure today for starting a cluster and adding removing node, document that whenever a change to the
cluster topoloy happen, the user should change the replication fuctor to match the cluster topology:
1. https://docs.scylladb.com/stable/operating-scylla/security/authentication.html#prerequisites sais: `et the system_auth keyspace replication factor to the number of nodes in the datacenter via cqlsh`
2. https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-node-to-cluster.html sais: `It is recommended to set system_auth replication factor to the number of nodes in each DC.`

In order to lessen the friction we should move `system_auth` to `EverywhereReplication` , the following things should be taken into account:
1. New cluster should create this keyspace with `EverywhereReplication` 
2. Uppon topology change the `system_auth` keyspace should be automatically repaired and in general we should maintain availability during the transition.
3. During upgrade the kesyspace should be changed (and repaired) automatically without affecting availability.

Besides all of the above, we have one known problem today where repairs on such keyspaces has high chance of failing on large clusters. We will need to think of a way to mitigate this problem. One note about it is that it also exists today if the user follows our documentation since the data is also replicated accross all nodes in the cluster.

**Comment by avikivity** [comment]
A problem with the NetworkTopology -> Everywhere change is that before it's repaired, reads will not see all data. So a simple ALTER TABLE won't work.

Perhaps we need a TransitionalReplicationStrategy that takes two replication strategies as input: one for read and one for write, and use that until repair. It may work for vnode->tablet too.

/cc @asias @tgrabiec

**Comment by mykaul** [comment]
> A problem with the NetworkTopology -> Everywhere change is that before it's repaired, reads will not see all data. So a simple ALTER TABLE won't work.
> 
> Perhaps we need a TransitionalReplicationStrategy that takes two replication strategies as input: one for read and one for write, and use that until repair. It may work for vnode->tablet too.
> 
> /cc @asias @tgrabiec

I wonder how urgent it is to solve that - or can we have new clusters with Everywhere and existing clusters continue as they were. Yes, we are not solving the pain for them, but we are making the experience better with new clusters. (and defer the upgrade issue to later releases)

**Comment by eliransin** [comment]
> I wonder how urgent it is to solve that - or can we have new clusters with Everywhere and existing clusters continue as they were. Yes, we are not solving the pain for them, but we are making the experience better with new clusters. (and defer the upgrade issue to later releases)

The main problem will be the difference in procedures that depends what was the starting point of the cluster. So for example in add node we will say something like, if you started before version X, increase the reolication factor, else do nothing / only do a repair.
I think it is even more confusing than what we have today (in the UX sense)

**Comment by tarzanek** [comment]
just a side note - once this is fixed our docs have to explicitly say and emphasize to NOT use cassandra user for user traffic and always create own (super)user
cassandra user name queries system_auth with QUORUM, which is extra traffic and kills performance (especially with replicas on all nodes)

**Comment by eliransin** [comment]
> A problem with the NetworkTopology -> Everywhere change is that before it's repaired, reads will not see all data. So a simple ALTER TABLE won't work.
> 
> Perhaps we need a TransitionalReplicationStrategy that takes two replication strategies as input: one for read and one for write, and use that until repair. It may work for vnode->tablet too.
> 
> /cc @asias @tgrabiec

@avikivity today the situation is that we recommend our users to manually increase the replication to everywhere (have RF match the number of nodes). So a simple alter table should actually work (if the user followed our recomendations).

I also wonder about repair, does your proposed solution, natively supports repair? (do we repair by read or by write?)
A possibly easier solution will be to trigger a repair internally (maybe?) 

Thinking about it some more yielded the following steps to the full solution:
1. Start creating the table (for new deployments) with the Everywhere strategy.
2. Find a solution for the transition, the simplest way I can see is:
2.1 Every node alters the keyspace (if it is not already) to Everywhere
2.2 Every node triggers repair for it's own copy after the keyspace was altered, and it repairs at least once, after a succesfull repair it will save a value in `system.scylla_local`  something like key=auth_transision value=completed. The node will keep trying to repair until the value is found in `ststem.scylla_local`

It seams like it there is a transient state where login is flaky however:
1. This is the state also today when for example adding some nodes to the cluster and changing the system_auth replication until the repair.
2. It should at least be a one time pain and then we are free of it.

**Comment by eliransin** [comment]
after a brief discussion with @asias, I have a plan for the migration:
1. We define a feature bit for the `auth_migration`
2. Once the feature bit is enabled, every node : 
    1. Will alter the `system_auth` keyspace to EverywhereTopology (if it is not already altered)
    2. if `auth_upgraded` doesn't exist in `system_local.scylla_local` Will do in a loop (until success): 
        1. sleep for a random period in (x,y) seconds
        2. trigger a repair
        3. if success write to `system_local.scylla_local` the key `auth_upgraded` break the loop, else repeat.

Notes:
There is some rdundancy with repairs here, however, this is a one time operation and IMHO doesn't worth the 
complication of coordinating it so only one repair is ran.
Risks:
In case something goes wrong, we can fix almost everything by just running a `nodetool repair` on the `system_auth` keyspace.

Some additional thing to consider is that maybe this change should be paired with a configuration option that prevents
the user from changing the replication strategy specifically on this  keyspace, to prevent situations that users have some
autmation in place for add/remove nodes that alters the RF for NetworkTopologyStrategy which will override this change.

**Comment by kbr-scylla** [comment]
Shouldn't we manage it with Raft group 0 instead?
cc @kostja

**Comment by bhalevy** [comment]
> Shouldn't we manage it with Raft group 0 instead? cc @kostja

+1

**Comment by ptrsmrn** [comment]
> Shouldn't we manage it with Raft group 0 instead? cc @kostja

It's been decided to migrate `system_auth` under RAFT. 
@eliransin I think we can close this issue, because it's a (kind-of) duplicate of:
1. https://github.com/scylladb/scylladb/issues/1796
2. https://github.com/scylladb/scylladb/issues/15221
