### ISSUE TITLE
UDA keep using old UDF even after the UDF is replaced 

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#12709]
If we have an UDF:
```
CREATE FUNCTION sfunc (state bigint, val bigint) RETURNS NULL ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state + val;'
```
and a UDA:
```
CREATE AGGREGATE my_sum(bigint) SFUNC sfunc STYPE bigint INITCOND 0
```
and we replace the UDF:
```
CREATE OR REPLACE FUNCTION sfunc (state bigint, val bigint) RETURNS NULL ON NULL INPUT RETURNS bigint LANGUAGE lua AS 'return state + 2 * val;'
```
The `my_sum` aggregate will keep using the previous UDF until we restart the node.

The issue is also present in Cassandra, which can be experienced by manual testing and is confirmed by the unadressed todos ([here](https://github.com/apache/cassandra/blob/67b483b5c884dfe0afa5ed221903387d212fe918/src/java/org/apache/cassandra/cql3/statements/schema/CreateFunctionStatement.java#L84) and [here](https://github.com/apache/cassandra/blob/67b483b5c884dfe0afa5ed221903387d212fe918/src/java/org/apache/cassandra/cql3/statements/schema/CreateFunctionStatement.java#L152))

**Comment by avikivity** [comment]
Backported to 5.2. It's not easy to backport to 5.1, and given that UDA are experimental there, and this is advanced functionality, not backporting further.

**Comment by denesb** [comment]
5.2 backport dequeued, breaks the build.

**Comment by avikivity** [comment]
@wmitros please prepare a backport

**Comment by wmitros** [comment]
> @wmitros please prepare a backport

I submitted https://github.com/scylladb/scylladb/pull/13542.

**Comment by avikivity** [comment]
Backported to 5.2 as 7b2215d8e06986e31256a1e6e85bed1358704612.
