### ISSUE TITLE
system_distributed.service_levels configuration table should be moved to system_distributed_everywhere as it is too fragile

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#12706]
The `service_levels` table which is part of the `system_distributed` keyspace was proven to be too fragile. This table is polled by every node every 10 seconds with a scan query (which doesn't have speculative retry) with `CL=ONE`.
This combination causes two problems:
1. Availability - since `system_distributed` has a constant replication factor (3 in the time of writing) , the larger the cluster, more and more nodes are involved in the scan query. Since we don't have speculative retry for scan queries (by design) if one of the involved nodes fails to reply, it fails the whole scan query causing the time of a new configuration propagation to be very unpredictable for an overloaded cluster.
2. Non linearity - when the table has inconsistencies (for the normal reasons which Scylla is designed to deal with), it can happen that every poll will result in a different observed configuration. Until the table is repaired, there will be flactuations where a specific added service level can appear in some of the polls and not appear in others or it will appear with different configuration, this in turn will cause unnecesairy and incorrect configuration updates on the node, making it alternate between those observed configrations back and forth. This, besides from the fact that it loads the system, creates unpredictability.

For those two reasons we need to:
1. Move the `service_levels` table to the `system_distributed_everywhere` keyspace.
2. Consider queriying the table sometimes (with some probability or evry x polls) with 'CL=TWO' (or CL='ALL') in order to have anti entropy and reduce the need for repairing this table on a regular basis.

Chalenges:
There are 2 main challenges for this change one of which is common to all users of `EverywhereStrategy`:
1. Common - Repair of a table distributed everywhere is fragile, and the probablility for it to fail correlates tightly with the cluster size (nodes and shards number).
2. Secific - All upgrade paths should be crefully considered and tested since the user might loose some of the configuration if the transition is not done correctly.

**Comment by mykaul** [comment]
Is this feasible for 5.4? where are we with this?

**Comment by nyh** [comment]
@kostja @mykaul this issue was set to P1 ten months ago, maybe it's time to either do it or lower its priority?

**Comment by kostja** [comment]
It's in progress as service levels are being moved to raft by @Jadw1

**Comment by mykaul** [comment]
Since https://github.com/scylladb/scylladb/issues/17926 is merged, why is this still open? What's left for 6.0?
@Jadw1 , @piodul ?

**Comment by Jadw1** [comment]
I didn't linked it to #17926 but created a new issue. Closing manually
