### ISSUE TITLE
nodetool tablestats shows incorrect live and total disk space used

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#12717]
Their description:

Space used (live) | 9592399 | Total number of bytes of disk space used by all active SSTables belonging to this table | Storing data on disk in SSTables
-- | -- | -- | --
Space used (total) | 9592399 | Total number of bytes of disk space used by SSTables belonging to this table, including obsolete SSTables waiting to be GCd | Same as above.

Our total space used is implementing an incorrect semantics. It shows the total disk space ever used, which is incorrect. It should be space used by all sstables, including the ones waiting to be deleted.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.
