### ISSUE TITLE
Docs: Upgrade from Scylla 5.1 to 5.2

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#12734]
Make sure to comment on Raft, and how to enable it post upgrade

**Comment by tzach** [comment]
Already done in commit https://github.com/scylladb/scylladb/commit/40f61db1205dbf57645a0e2b349ea1011f14d669

https://docs.scylladb.com/master/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/upgrade-guide-from-5.1-to-5.2-generic.html

**Comment by annastuchlik** [comment]
@tzach Yes, it was added some time ago and is on branch-5.2.
Is there anything else to be added to address the issue, or can I close it?
