### ISSUE TITLE
Mark high cardinality counters with skip_when_empty

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#12751]
The following counters have a high cardinality and should be marked with ```skip_when_empty```:

```
scylla_storage_proxy_coordinator_reads_local_node (storage_proxy.cc)
scylla_storage_proxy_coordinator_completed_reads_local_node (storage_proxy.cc)
scylla_transport_cql_errors_total (./transport/server.cc)
```

Additional counters are candidates as well

**Comment by DoronArazii** [comment]
@amnonh what are the steps? (I see it under 5.3 which is about to branch-out soon)

**Comment by mykaul** [comment]
I assume it'll need a backport, as we've branched 5.3 already.

**Comment by mykaul** [comment]
@amnonh - what's the next step here?

**Comment by amnonh** [comment]
PR #13558 is outdated, I'll need to rebase and push
