### ISSUE TITLE
doc: document the metric update in version 5.2

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#12754]
The upgrade guide from 5.1 to 5.2 has been added, but the information about metrics is missing - there's only a placeholder:
https://docs.scylladb.com/master/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/metric-update-5.1-to-5.2.html

@amnonh Could you provide me with the list of new or removed metrics in 5.2 so that I can complete the docs before the release?
Also, is there anything we should add to the [upgrade guide from 5.1 to 5.2](https://docs.scylladb.com/master/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/upgrade-guide-from-5.1-to-5.2-generic.html)? The changes in metrics will be described in the release notes, so the users will be aware of the change, but is the upgrade procedure affected?

@tzach

**Comment by amnonh** [comment]
@annastuchlik I'm waiting for a RC to get the list of metrics.
About the upgrade, users should upgrade the monitoring to 4.3 first and only then upgrade Scylla.
Datadog users will not be affected

**Comment by annastuchlik** [comment]
@amnonh The upgrade guide includes a note to upgrade the Monitoring Stack before upgrading ScyllaDB.
The download page and the documentation always refer to installing the latest version, so I'd like to keep it that way. But if you think the information is critical, I can create a new Prerequisite section and move the information from the note there to make it more prominent. 

![image](https://user-images.githubusercontent.com/37244380/217493062-c7cd9b11-4c83-4d2a-9b04-08ab4fff930d.png)

**Comment by amnonh** [comment]
@annastuchlik there are metrics changes, so the minimal Scylla Monitoring release is 4.3 that will be backwards compatible.
We can phrase it differently

**Comment by annastuchlik** [comment]
@amnonh How about:

If you use ScyllaDB Monitoring Stack, we recommend upgrading the Monitoring Stack **before** upgrading ScyllaDB.
For ScyllaDB 5.2, you MUST upgrade the Monitoring Stack to version 4.3 or later.

**Comment by amnonh** [comment]
Sounds good

**Comment by amnonh** [comment]
New in 5.2
========
|name|Help
-- | --
scylla_database_disk_reads | Holds the number of currently active disk read operations.
scylla_database_sstables_read | Holds the number of currently read sstables.
scylla_memory_malloc_failed | Total count of failed memory allocations
scylla_raft_group0_status | status of the raft group, 0 - disabled, 1 - normal, 2 - aborted
scylla_storage_proxy_coordinator_cas_read_latency_summary | CAS write latency summary
scylla_storage_proxy_coordinator_cas_write_latency_summary | CAS write latency summary
scylla_storage_proxy_coordinator_read_latency_summary | Read latency summary
scylla_storage_proxy_coordinator_write_latency_summary | Write latency summary
scylla_streaming_finished_percentage | Finished percentage of node operation on this shard
scylla_view_update_generator_sstables_pending_work | Number of bytes remaining to be processed from SSTables for view updates

Name Change in 5.2
================

5.1 | 5.2
-- | --
scylla_database_active_reads_memory_consumption | scylla_database_reads_memory_consumption
scylla_memory_regular_virtual_dirty_bytes | scylla_memory_regular_unspooled_dirty_bytes
scylla_memory_system_virtual_dirty_bytes | scylla_memory_system_unspooled_dirty_bytes
scylla_memory_virtual_dirty_bytes | scylla_memory_unspooled_dirty_bytes

**Comment by annastuchlik** [comment]
I assume that 
`scylla_storage_proxy_coordinator_cas_read_latency_summary` is "CAS write latency summary" (not "write"), and that's how I'm documenting it.

**Comment by avikivity** [comment]
Already backported to 5.2. Not backporting further as it's 5.2 specific.
