### ISSUE TITLE
doc: Add page for OSS x Enterprise matrix

### ISSUE THREAD

**Issue by noellymedina** [scylladb/scylladb#12758]
Up until today, we knew that a new MAJOR Ent release will come with a new MAJOR OSS release.

- 2019.1 was based on OSS 3.0

- 2020.1 was based on OSS 4.0

But then this logic was changed:

- 2021.1 was based on OSS 4.3

Resumed again:

- 2022.1 was based on OSS 5.0

And then Minor (STS) release was introduced on Ent:

- 2022.2 is based on OSS 5.1

- 2022.3 will be based on OSS 5.2?

Will Ent 2023.1 be based on OSS 6.0?

Customers keep asking us for this correlation and it would be great to have it as a table/matrix in our docs, something similar to [Monitor matrix](https://monitoring.docs.scylladb.com/stable/reference/matrix.html).
```
╒══════════════╕
│ O.S │ Enterp │
╞═════╪════════╡
│ 3.0 │ 2019.1 │ 
├─────┼────────┤
│ 4.0 │ 2020.1 │ 
├─────┼────────┤
│ 4.3 │ 2021.1 │ 
├─────┼────────┤
│ 5.0 │ 2022.1 │
├─────┼────────┤
│ 5.1 │ 2022.2 │
╘══════════════╛
```
:smile: 
Thanks

Cc @tomer-sandler @tzach

**Comment by tzach** [comment]
@noellymedina this looks like a (good) Enterprise roadmap question, not an open source project issue.

**Comment by tomer-sandler** [comment]
Tzach, these the the 2 docs repo @annastuchlik told us to use to report docs issues/need:
> Cloud issues: https://github.com/scylladb/scylla-cloud-doc/issues
> Open Source/Enterprise issues: https://github.com/scylladb/scylladb/issues

Where does this request belong then?

**Comment by annastuchlik** [comment]
@tomer-sandler This issue is opened in the right repo, thank you! :)

**Comment by annastuchlik** [comment]
@tzach I'm going to add the matrix. I think it should be in both Enterprise and OSS docs.
I'll create a new "Reference" section - this is where such information should be placed (apart from the Matrix, I'll be moving some more reference-like content there for the sake of better organization).

**Comment by avikivity** [comment]
Not a bug, not backporting.
