### ISSUE TITLE
throwing reader_concurrency_semaphore::consume() causes memory leaks

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12767]
Said method can now throw std::bad_alloc since https://github.com/scylladb/scylladb/commit/aab5954cfb65cc1bee645384a45a844f252f8d7e. All call-sites should have been adapted in the series introducing the throw, but some managed to slip through because the oom unit test didn't run in debug mode.
In particular, the `mutation_fragment` constructors (which call `consume()`) and the tracking allocator are vulnerable.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
