### ISSUE TITLE
Scylla cluster nodes utilizes 100% of CPU even with no load

### ISSUE THREAD

**Issue by psaawkel** [scylladb/scylladb#12774]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in 

*Installation details*
Scylla version (or git commit hash): 5.1.0
Cluster size: 2 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI):  CentOS

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): Kubernetes/Docker
Hardware: sockets=1 cores=8 hyperthreading=true memory=32G
Disks: (SSD/HDD, count) 2 SSDs in RAID

I am running Scylla cluster in kubernetes, managed by Scylla-operator and noticed it utilizes CPU to the pod defined limits even if not loaded with requests when standalone pod with similar settings does not.
I also noticed when I installing cluster (kubernetes is creating first pod, and then, after 3 minutes the second) the first pod is starting and utilizing normally at 2-3% of CPU, and when the second node is created and started - both uses 100% of CPU limit assigned to pod.

'top -c' copied below:

```
Tasks: 309 total,   2 running, 307 sleeping,   0 stopped,   0 zombie
%Cpu(s): 22.1 us,  5.4 sy,  0.0 ni, 69.0 id,  0.4 wa,  0.0 hi,  1.0 si,  2.0 st
KiB Mem :  8008744 total,   178432 free,  6416988 used,  1413324 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   886048 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 4517 root      20   0   16.0t   1.3g  32080 R  49.5 16.4   6:47.68 /usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --memory 1300M --reserve-memory 100M --smp 1 --overprovisioned --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=10.233.17.208 --broadcast-address 10.233.17.208 --broadcast-rpc-address 10.233.17.208 --alternator-address 0.0.0.0 --blocked-reactor-notify-ms 999999999 --prometheus-address=0.0.0.0
 2145 root      20   0 2275720 109488  20400 S   4.3  1.4  46499:56 /usr/local/bin/kubelet --logtostderr=true --v=2 --node-ip=192.168.122.12 --hostname-override=test-k8s-worker2 --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/etc/kubernetes/kubelet-config.yaml --kubeconfig=/etc/kubernetes/kubelet.conf --pod-infra-container-image=k8s.gcr.io/pause:3.3 --runtime-cgroups=/systemd/system.slice --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin
26185 root       0 -20       0      0      0 S   4.0  0.0   0:04.70 [kworker/3:1H]
 3030 root      20   0   10.3g 112760  13864 S   2.7  1.4  10626:02 /usr/local/bin/etcd
  738 root      20   0   16.0t  61420   3764 S   2.3  0.8   4235:44 /usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 10.233.65.99 --rpc-address 10.233.65.99 --seed-provider-parameters seeds=10.233.65.99 --alternator-address 10.233.65.99 --blocked-reactor-notify-ms 999999999
 1212 root      20   0 1271364  97040   6888 S   2.0  1.2  23757:23 /usr/bin/dockerd --iptables=false --exec-opt native.cgroupdriver=systemd --data-root=/var/lib/docker --log-opt max-size=50m --log-opt max-file=5 --dns 10.233.0.3 --dns 8.8.8.8 --dns 8.8.4.4 --dns-search default.svc.fluodata.cluster --dns-search svc.fluodata.cluster --dns-opt ndots:2 --dns-opt timeout:2 --dns-opt attempts:2
26209 root      20   0       0      0      0 S   1.3  0.0   0:00.85 [kworker/u8:4]
14734 root      20   0       0      0      0 S   1.0  0.0   0:01.23 [kworker/u8:1]
23862 root      20   0       0      0      0 S   1.0  0.0   0:01.92 [kworker/u8:0]
    1 root      20   0  129128   6104   2528 S   0.7  0.1 657:23.29 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
 4008 root      20   0       0      0      0 S   0.7  0.0   0:01.60 [kworker/u8:2]
 7347 root      20   0  737824  20160   5888 S   0.7  0.3 239:22.26 /speaker --port=7472 --config=metallb
30792 root      20   0  162260   2540   1656 R   0.7  0.0   0:00.07 top -c
    9 root      20   0       0      0      0 S   0.3  0.0   1762:36 [rcu_sched]

```

As you can see, Scylla node from cluster utilizes 49.5% CPU, and standalone Scylla utilizes 2.3% CPU.

Resources limits:
```
resources:
     limits:
       cpu: 500m
       memory: 1500Mi
     requests:
       cpu: 500m
       memory: 1500Mi
```

And traces from perf:

[trace-standalone-scylla-no-load.txt](https://github.com/scylladb/scylladb/files/10679811/trace-standalone-scylla-no-load.txt)
[trace-second-node-connected-high-load.txt](https://github.com/scylladb/scylladb/files/10679812/trace-second-node-connected-high-load.txt)
[trace-second-node-connected-no-load.txt](https://github.com/scylladb/scylladb/files/10679813/trace-second-node-connected-no-load.txt)
[trace-before-second-node-connected.txt](https://github.com/scylladb/scylladb/files/10679814/trace-before-second-node-connected.txt)

Logs from node:
[logs-from-scylla-in-scylla-fndt-waw-1-fndt-waw-1a-0.log](https://github.com/scylladb/scylladb/files/10679875/logs-from-scylla-in-scylla-fndt-waw-1-fndt-waw-1a-0.log)

Any ideas? As I understand Scylla in overprovisioned mode should utilize to minimum when not loaded. I don't know if I can rely on this deployment as a production system, if there is a bug/problem and might work wrong.

**Comment by fruch** [comment]
scylla-operator is optimized to use each CPU to it's fullest, setting it with `cpu: 500m` ends up with  
the following commandline arguments
`--smp 1 --overprovisioned`

so from from scylla-pov it assumes it's has one core totally available for it, and might explain this

can you also clearify what's the stand-alone ? it's just `docker run scylladb/scylla:5.0.1` with not extra parameters ?

@tnozicka do we have any recommendation for usage  of scylla-opeatror on lower then 1 CPUs configurations ?

**Comment by psaawkel** [comment]
As a stand-alone Scylla I meant running scylladb/scylla:5.1.0 under kubernetes as a deployment (with persistent volume for data), it alse have 500m CPU limit and behaves great - CPU rises only when there is high load or during compaction or other task, at idle (or 1req/s) it takes 0,8% to 1,5% CPU.
About scylla-operator is optimized to use each CPU to its fullest, there is a screenshot here:
https://monitoring.docs.scylladb.com/stable/intro.html
Where load is approx 30% at 80k req/s, I have 100% load at 0,5req/s (or at 0 reqs also 100%) - this is why I think my cluster does not work properly.
![image](https://user-images.githubusercontent.com/47543625/218684558-73d95e6d-529b-4d17-9434-d89fed7dd528.png)

**Comment by fruch** [comment]
if you are't using scylla-operator (https://operator.docs.scylladb.com/stable/), please supply the k8s configuration you are using, and the scylla.yaml from one of those pods. also logs from the those pod would be helpful to understand what's wrong.

I'll say again scylla-operator is the advised way of running scylla under k8s

I'm not sure I understand how scylla-monitor example screenshot is related (I'm quite sure it's not from a setup using k8s, or even using docker...)

**Comment by avikivity** [comment]
Which traces correspond to the state where it consumes all cpu?

**Comment by psaawkel** [comment]
> I'll say again scylla-operator is the advised way of running scylla under k8s
Definitely, that's why I trying to make scylla-operator running properly.

Simple scylladb/scylla:5.1.0 deployment is running only for test env and for comparison and I am disappointed that scylla-operator behaves worse (at least when it comes to CPU consumption at IDLE or low load)

@avikivity sorry for inconsistences:
[trace-standalone-scylla-no-load.txt](https://github.com/scylladb/scylladb/files/10679811/trace-standalone-scylla-no-load.txt) - from scylladb/scylla:5.1.0 deployment (not-scylla operator) at idle, for comparison, keyspaces contains ~1Gb of highly compressed data.


The rest is from one of the scylla-operator node, having ~1G data each:
[trace-before-second-node-connected.txt](https://github.com/scylladb/scylladb/files/10679814/trace-before-second-node-connected.txt) - from first node after running `helm upgrade -i scylla -n scylla .` when the first node started, and second node not yet - it behaves normally consuming 1-2% CPU.
[trace-second-node-connected-no-load.txt](https://github.com/scylladb/scylladb/files/10679813/trace-second-node-connected-no-load.txt) - from first node, when second node ready and connected, no relevant load yet, CPU rises to its max and if we wait it stays high, and the functions are the same even after few days of running cluster.

[trace-second-node-connected-high-load.txt](https://github.com/scylladb/scylladb/files/10679812/trace-second-node-connected-high-load.txt) - from first node, like above, but some reading load added.
 Share of kernel or libc.so.6 functions in perf is reduced in favor of scylla functions.

**Comment by psaawkel** [comment]
Any idea?

**Comment by avikivity** [comment]
I'm guessing you're running on a very old kernel. Please reproduce on a newer kernel (4.18+, preferably newer). With older kernels Scylla uses a compatibility mode (epoll) which is not as well tested as the regular mode (linux-aio).

**Comment by psaawkel** [comment]
Thanks. That could be it.
The host system was Centos 7 with 3.10.0-1160.el7.x86_64 and after kernel upgrade to 5.4.232-1.el7.elrepo.x86_64 scylla not starts
`
INFO  2023-02-23 22:09:10,278 [shard 0] database - Keyspace system: Reading CF schema_functions id=d1b675fe-2b50-3ca4-8e49-c0f81989dcad version=a50959dd-2be0-3e4e-8bb5-cf40796e256a
ERROR 2023-02-23 22:09:10,284 [shard 0] seastar - io_submit: Operation not supported
exception running reactor main loop on shard 0.
Backtrace:
  0x4c7deb8
  0x4c8dd24
  0x4c341a8
  0x4c33681
  0x10765b6
  0x1073b9a
  /opt/scylladb/libreloc/libc.so.6+0x27b74
  0x1072a6d
2023-02-23 22:09:11,324 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-02-23 22:09:11,324 INFO exited: scylla (exit status 1; not expected)
`
But kernel supports io_submit
`
[root@k8s-worker1 tmp]# grep CONFIG_AIO /boot/config-$(uname -r)
CONFIG_AIO=y
`
Also executed your fsqual tool:
`
[root@k8s-worker1 fsqual]# ./fsqual
memory DMA alignment:    512
disk DMA alignment:      512
filesystem block size:   4096
context switch per write io (size-changing, append, blocksize 4096, iodepth 1):                                                                        0.0001 (GOOD)
context switch per write io (size-changing, append, blocksize 4096, iodepth 3):                                                                        0.7977 (BAD)
context switch per write io (size-unchanging, append, blocksize 4096, iodepth 3)                                                                       : 0 (GOOD)
context switch per write io (size-unchanging, append, blocksize 4096, iodepth 7)                                                                       : 0 (GOOD)
context switch per write io (size-unchanging, append, blocksize 512, iodepth 1):                                                                        0.9998 (BAD)
context switch per write io (size-unchanging, overwrite, blocksize 512, iodepth                                                                        1): 0.9999 (BAD)
context switch per write io (size-unchanging, overwrite, blocksize 512, O_DSYNC,                                                                        iodepth 1): 0.9999 (BAD)
context switch per write io (size-unchanging, overwrite, blocksize 512, O_DSYNC,                                                                        iodepth 3): 1 (BAD)
context switch per write io (size-unchanging, overwrite, blocksize 512, O_DSYNC,                                                                        iodepth 3): 1 (BAD)
context switch per write io (size-changing, append, blocksize 4096, iodepth 1):                                                                        0 (GOOD)
context switch per write io (size-changing, append, blocksize 4096, iodepth 3):                                                                        0.8039 (BAD)
context switch per write io (size-unchanging, append, blocksize 4096, iodepth 3)                                                                       : 0 (GOOD)
context switch per write io (size-unchanging, append, blocksize 4096, iodepth 7)                                                                       : 0 (GOOD)
context switch per write io (size-unchanging, append, blocksize 512, iodepth 1):                                                                        0.9985 (BAD)
`
Scylla:4.3.0 is running normally, but 4.5.0 and newer not.

**Comment by denesb** [comment]
Removing forgotten label.
