### ISSUE TITLE
reader_concurrency_semaphore: add trace-points to semaphore events

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12781]
Basically, all major permit state changes should get a corresponding trace point.
For this to work, we probably have to store a trace_state_ptr on the permit, which is refreshed on each page.

Requested by @avikivity, based on user feedback. I started looking into how this should be implemented, but I might not get around to do it for a while, so I created this issue so we don't forget.

**Comment by avikivity** [comment]
Not a bug, not backporting.

**Comment by bhalevy** [comment]
> Not a bug, not backporting.

@avikivity apparently the series contains a prerequisite (https://github.com/scylladb/scylladb/pull/13255/commits/156e5d346d427abc4c79075cb2e71d68ed35d703) for backporting #14819 (to provide a new `make_tracking_only_permit` overload)

**Comment by denesb** [comment]
> > Not a bug, not backporting.
> 
> @avikivity apparently, as @tchaikov found out, the series contains a prerequisite ([156e5d3](https://github.com/scylladb/scylladb/commit/156e5d346d427abc4c79075cb2e71d68ed35d703)) for backporting #14819 (to provide a new `make_tracking_only_permit` overload)

This is not a prerequisite to https://github.com/scylladb/scylladb/issues/14819. Interfaces change and backported patches have to be adapted to older versions all the time. https://github.com/scylladb/scylladb/issues/14819 does not depend on the functionality introduced here.

**Comment by bhalevy** [comment]
okay, so if we can resolve the backporting issue without cherry-picking from this series that's good enough.
