### ISSUE TITLE
FAILED ttl_test.py::TestDistributedTTL::test_ttl_is_respected_on_repair[parallel_aggregates_disabled] 

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#12796]
Observed a failure in next promotion

```
 [gw1] FAILED ttl_test.py::TestDistributedTTL::test_ttl_is_respected_on_repair[parallel_aggregates_disabled] 
```

HEAD: fd4ee4878ab6814c5cc119c7538ac0eafa560afb

job: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/5654/

**Comment by nyh** [comment]
Duplicate of https://github.com/scylladb/scylladb/issues/11684
