### ISSUE TITLE
A node got ENOSPC following a nodetool cleanup, then left permanently down

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#12790]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

1. Run nodetool cleanup on node-1 for all keyspaces, getting to keyspace "scylla_bench".
2. After an hour and a half of cleanup, node-1 got enospc.
3. the cleanup failed and node left permanently down.

error log
--------------
running cleanup:
```
< t:2023-02-02 22:45:48,137 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  cleanup keyspace1"...
< t:2023-02-02 22:45:48,137 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-02-02 22:45:48.136: (InfoEvent Severity.NORMAL) period_type=not-set event_id=0e104f20-2e30-4844-8476-c7782ad5da86: message=NodetoolCleanupMonkey Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True)
< t:2023-02-02 22:47:01,692 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool  cleanup keyspace1" finished with status 0
< t:2023-02-02 22:47:01,693 f:cluster.py      l:2579 c:sdcm.cluster_aws     p:DEBUG > Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True): Command '/usr/bin/nodetool  cleanup keyspace1' duration -> 73.5542554019994 s
< t:2023-02-02 22:47:01,693 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  cleanup scylla_bench"...
```
got enospc:
```
2023-02-03 00:14:58.673 <2023-02-03 00:14:58.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=3e2711de-66ee-4262-a352-64c91a33afd3: type=NO_SPACE_ERROR regex=No space left on device line_number=43989 node=longevity-large-partitions-200k-pks-db-node-dc3133bf-1
2023-02-03T00:14:58+00:00 longevity-large-partitions-200k-pks-db-node-dc3133bf-1      !ERR | scylla[13578]:  [shard 12] storage_service - Shutting down communications due to I/O errors until operator intervention: Disk error: std::system_error (error system:28, No space left on device)

2023-02-03 00:14:58.939 <2023-02-03 00:14:58.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=3e2711de-66ee-4262-a352-64c91a33afd3: type=NO_SPACE_ERROR regex=No space left on device line_number=44087 node=longevity-large-partitions-200k-pks-db-node-dc3133bf-1
2023-02-03T00:14:58+00:00 longevity-large-partitions-200k-pks-db-node-dc3133bf-1      !ERR | scylla[13578]:  [shard 11] commitlog - Failed to persist commits to disk for HintsLog-2-198158383618283613.log: storage_io_error (Storage I/O error: 28: No space left on device)

2023-02-03 00:14:58.939 <2023-02-03 00:14:58.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=3e2711de-66ee-4262-a352-64c91a33afd3: type=NO_SPACE_ERROR regex=No space left on device line_number=44088 node=longevity-large-partitions-200k-pks-db-node-dc3133bf-1
2023-02-03T00:14:58+00:00 longevity-large-partitions-200k-pks-db-node-dc3133bf-1      !ERR | scylla[13578]:  [shard 11] commitlog - Failed to flush commits to disk: storage_io_error (Storage I/O error: 28: No space left on device)

2023-02-03 00:14:58.946 <2023-02-03 00:14:58.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=3e2711de-66ee-4262-a352-64c91a33afd3: type=NO_SPACE_ERROR regex=No space left on device line_number=44122 node=longevity-large-partitions-200k-pks-db-node-dc3133bf-1
2023-02-03T00:14:58+00:00 longevity-large-partitions-200k-pks-db-node-dc3133bf-1     !INFO | scylla[13578]:  [shard  4] compaction - [Compact scylla_bench.test faddfac0-a356-11ed-856b-596b6382cf3f] Compacting of 3 sstables interrupted due to: storage_io_error (Storage I/O error: 28: No space left on device)
```
nodetool cleanup failed (and the nemesis as well):
```
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-02-03 00:52:40.606: (DisruptionEvent Severity.ERROR) period_type=end event_id=10832df7-0f14-4409-8f10-15ad882a7f9d duration=2h6m54s: nemesis_name=NodetoolCleanup target_node=Node longevity-large-partitions-200k-pks-db-node-dc3133bf-5 [34.244.187.225 | 10.4.1.142] (seed: False) errors=Encountered a bad command exit code!
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Command: '/usr/bin/nodetool  cleanup scylla_bench'
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Exit code: 2
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stdout:
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stderr:
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at java.security.AccessController.doPrivileged(Native Method)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 	at java.lang.Thread.run(Thread.java:750)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4013, in wrapper
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = method(*args[1:], **kwargs)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1747, in disrupt_nodetool_cleanup
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     node.run_nodetool(sub_cmd="cleanup", args=keyspace)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2578, in run_nodetool
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = _run()
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, **kwargs)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = connection.run(**command_kwargs)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise UnexpectedExit(result)
< t:2023-02-03 00:52:40,608 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

```

node-1 is permanently down:
```
< t:2023-02-03 01:03:14,258 f:base.py         l:276  c:sdcm.sct_events.base p:DEBUG > (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=75a8c80a-9f8f-4903-a00d-5f469dbde9a4: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-dc3133bf-2 error=Current node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-2 [34.250.85.19 | 10.4.0.110] (seed: False). Node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True) (not target node) status is DN marked to not publish
< t:2023-02-03 01:04:03,539 f:base.py         l:276  c:sdcm.sct_events.base p:DEBUG > (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=bd843813-85e2-4e99-9007-6806e5c3288d: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-dc3133bf-2 error=Current node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-2 [34.250.85.19 | 10.4.0.110] (seed: False). Node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True) (not target node) status is DN marked to not publish
< t:2023-02-03 01:04:52,996 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > 2023-02-03 01:04:52.994: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=67d8e1b3-e36b-4331-9dd2-744276bdb756: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-dc3133bf-2 error=Current node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-2 [34.250.85.19 | 10.4.0.110] (seed: False). Node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True) (not target node) status is DN
< t:2023-02-03 01:04:57,676 f:base.py         l:276  c:sdcm.sct_events.base p:DEBUG > (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=bf0037f5-84e4-4246-a510-28f29309c1c4: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-dc3133bf-3 error=Current node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-3 [54.246.49.66 | 10.4.0.240] (seed: False). Node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True) (not target node) status is DN marked to not publish
< t:2023-02-03 01:05:47,705 f:base.py         l:276  c:sdcm.sct_events.base p:DEBUG > (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=538c3e2b-c39c-43e3-90f3-47411510cacb: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-dc3133bf-3 error=Current node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-3 [54.246.49.66 | 10.4.0.240] (seed: False). Node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True) (not target node) status is DN marked to not publish
< t:2023-02-03 01:06:37,338 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:CRITICAL > 2023-02-03 01:06:37.336: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=2d01888b-b5a6-4fcc-8480-aa9f669424d9: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-dc3133bf-3 error=Current node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-3 [54.246.49.66 | 10.4.0.240] (seed: False). Node Node longevity-large-partitions-200k-pks-db-node-dc3133bf-1 [176.34.201.33 | 10.4.3.237] (seed: True) (not target node) status is DN
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1028-aws
Scylla version (or git commit hash): `5.2.0~rc0-20230119.34ab98e1be2e` with build-id `88ca9e450d4e14608b5119a0588d64820dc37b86`

Cluster size: 5 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-dc3133bf-2 (34.250.85.19 | 10.4.0.110) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-dc3133bf-4 (52.210.150.62 | 10.4.3.95) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-dc3133bf-3 (54.246.49.66 | 10.4.0.240) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-dc3133bf-1 (176.34.201.33 | 10.4.3.237) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-dc3133bf-5 (34.244.187.225 | 10.4.1.142) (shards: 14)

OS / Image: `ami-0074ee7c18f72707e` (aws: eu-west-1)

Test: `longevity-large-partition-200k-pks-4days-aws-i4i-test`
Test id: `dc3133bf-9598-4a1b-9bc6-cf094b26adc8`
Test name: `scylla-5.2/longevity/longevity-large-partition-200k-pks-4days-aws-i4i-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1cdfd0f5963c662ea18f4e1dc169a30656e4a8d5/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor dc3133bf-9598-4a1b-9bc6-cf094b26adc8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=dc3133bf-9598-4a1b-9bc6-cf094b26adc8)
- Show all stored logs command: `$ hydra investigate show-logs dc3133bf-9598-4a1b-9bc6-cf094b26adc8`

## Logs:
Restore Monitor Stack command: `$ hydra investigate show-monitor dc3133bf-9598-4a1b-9bc6-cf094b26adc8`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=branch-5.2&test_id=dc3133bf-9598-4a1b-9bc6-cf094b26adc8](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dbranch-5.2%26test_id%3Ddc3133bf-9598-4a1b-9bc6-cf094b26adc8&source=gmail-html&ust=1676030670194000&usg=AOvVaw1M5YYUKRucSRZODG1F5ZhO))
Show all stored logs command: `$ hydra investigate show-logs dc3133bf-9598-4a1b-9bc6-cf094b26adc8`

Test id: `dc3133bf-9598-4a1b-9bc6-cf094b26adc8`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-longevity-large-partition-200k-pks-4days-aws-i4i-test-scylla-per-server-metrics-nemesis-20230203_014919-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-longevity-large-partition-200k-pks-4days-aws-i4i-test-scylla-per-server-metrics-nemesis-20230203_014919-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-longevity-large-partition-200k-pks-4days-aws-i4i-test-scylla-per-server-metrics-nemesis-20230203_014919-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-longevity-large-partition-200k-pks-4days-aws-i4i-test-scylla-per-server-metrics-nemesis-20230203_014919-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png)&source=gmail-html&ust=1676030670194000&usg=AOvVaw1e35D-uNu_8pG0vz7W0clu)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-overview-20230203_014806-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-overview-20230203_014806-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-overview-20230203_014806-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_014806/grafana-screenshot-overview-20230203_014806-longevity-large-partitions-200k-pks-monitor-node-dc3133bf-1.png)&source=gmail-html&ust=1676030670194000&usg=AOvVaw3ssu3_sWoJfQMXB-XTElLK)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/db-cluster-dc3133bf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/db-cluster-dc3133bf.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/db-cluster-dc3133bf.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/db-cluster-dc3133bf.tar.gz)&source=gmail-html&ust=1676030670195000&usg=AOvVaw1UlxTOq58Jp5_pqhq5os1y)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/loader-set-dc3133bf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/loader-set-dc3133bf.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/loader-set-dc3133bf.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/loader-set-dc3133bf.tar.gz)&source=gmail-html&ust=1676030670195000&usg=AOvVaw1CBIL5H-y9jS5V9jbCPAYO)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/monitor-set-dc3133bf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/monitor-set-dc3133bf.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/monitor-set-dc3133bf.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/monitor-set-dc3133bf.tar.gz)&source=gmail-html&ust=1676030670195000&usg=AOvVaw2XXYh1BJJHZVR_KA7oS_Tq)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/sct-runner-dc3133bf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/sct-runner-dc3133bf.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/sct-runner-dc3133bf.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/dc3133bf-9598-4a1b-9bc6-cf094b26adc8/20230203_020343/sct-runner-dc3133bf.tar.gz)&source=gmail-html&ust=1676030670195000&usg=AOvVaw1ak0KMuf9Jg6M_lRJB4S5i)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-large-partition-200k-pks-4days-aws-i4i-test/3/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-large-partition-200k-pks-4days-aws-i4i-test/3/&source=gmail-html&ust=1676030670195000&usg=AOvVaw2IoHBYlJPBQf_Z7SXTwSuf))

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-large-partition-200k-pks-4days-aws-i4i-test/3/)
</details>

 [Argus](https://argus.scylladb.com/workspace?state=WyIyY2YwM2JmZi01YTNkLTQxMmQtODg4My02YTU1OWRjZjU2YWIiXQ)

**Comment by yarongilor** [comment]
The Issue might related to https://github.com/scylladb/scylladb/issues/10370

**Comment by fgelcer** [comment]
@yarongilor , search in previous runs of this job (or the one using i3 instances) what were the results for this failing nemesis

**Comment by roydahan** [comment]
@yarongilor missing information.

**Comment by yarongilor** [comment]
> @yarongilor , search in previous runs of this job (or the one using i3 instances) what were the results for this failing nemesis

It appears the nemesis passed ok in previous runs using Instance type: i3en.3xlarge.

example:
Id: c729edd1-2896-49d0-9520-057d3ed9df22
Scylla version: 2022.2.0~rc2-20220919.75d087a2b75a
```
disrupt_nodetool_cleanup | longevity-large-partitions-200k-pks-db-node-c729edd1-12 | Succeeded | 2022-10-01 08:12:31 | 2022-10-01 10:54:59
-- | -- | -- | -- | --
Nemesis InformationClass: SisyphusName: disrupt_nodetool_cleanupStatus: SucceededDuration: 2 hours, 42 minutes, 28 secondsTarget InformationName: longevity-large-partitions-200k-pks-db-node-c729edd1-12Public IP: 54.246.226.221Private IP: 10.4.3.35State: terminatedShards: 10
```

**Comment by fgelcer** [comment]
@yarongilor , what is the disk utilization on i3en? share screenshots of i4i disk utilization too..
it may be the case we need to either increase the instance type, or reduce the dataset (for i4i only)

**Comment by yarongilor** [comment]
i3en disk usage:
![image](https://user-images.githubusercontent.com/9427929/218405400-f98816ee-acc2-4888-94e4-75d4a7e24c69.png)

i4i disk usage:
![image](https://user-images.githubusercontent.com/9427929/218405804-3e3aafb6-0307-46a5-abed-d60bc4d972d9.png)

**Comment by roydahan** [comment]
And, what do we see here?

**Comment by yarongilor** [comment]
> And, what do we see here?

@roydahan , we see that in i4i the used space is higher than 50% which is problematic for OSS/STCS.
The i3en had much lower usage.
it may be the case we need to either increase the instance type, or reduce the dataset (for i4i only).

**Comment by roydahan** [comment]
Test issue
