### ISSUE TITLE
Node operations failures get masked by abort request failures

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12798]
Seen for example in #12333 where a decommission operation fails on one of the nodes (maybe on watchdog timeout), and the operation is aborted locally there.

Later the coordinator learns about the error when the heartbeat request fails with `node ops is unknown`
and eventually decommission is aborted by the coordinator, sending `decommission_abort` requests to all nodes.
This, again fails with `node ops is unknown` since the node already aborted the operation internally.
The failure in
https://github.com/scylladb/scylladb/blob/ccc8e47db1807f3cd5088b3cebf0627c1c28dcff/service/storage_service.cc#L2085
is leaked out as an exception that masks the exception caught by
https://github.com/scylladb/scylladb/blob/ccc8e47db1807f3cd5088b3cebf0627c1c28dcff/service/storage_service.cc#L2081
which was intended to be rethrown at
https://github.com/scylladb/scylladb/blob/ccc8e47db1807f3cd5088b3cebf0627c1c28dcff/service/storage_service.cc#L2095

**Comment by avikivity** [comment]
@bhalevy please advise whether a backport is needed.

**Comment by bhalevy** [comment]
> @bhalevy please advise whether a backport is needed.

Yes, a backport is needed, otherwise we're left in the dark in case of node ops error, masking important issues like #12969 / #12989

I prepared a backport branch with the required patches for 5.2: https://github.com/bhalevy/scylla/commits/branch-5.2-node-ops-backports
- 6373452b317dc8475076ca7353004cc4908b865e
- 53636167caae299389018c6f2f805560e64d4ce7
- 5856e69462342a6559aa066c9837f4bb9fe17f98
- 2b44631ded8b9dd4db70a0cabdc8c87789698cc6
- 6373452b317dc8475076ca7353004cc4908b865e
