### ISSUE TITLE
test_cfstats regression: AssertionError: SSTable count is 0 not >=1

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12808]
See for example https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/192/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split003___test_cfstats/
```
AssertionError: SSTable count is 0 not >=1
assert 0.0 >= 1
 +  where 0.0 = float('0')
```

Git bisect points at 55a8421e3d35b85ca1497d615540aafe2e02bffd by @raphaelsc 

The change delays the stats update to `rebuild_statistics()`.

**Comment by avikivity** [comment]
According to bisect, newly introduced regression.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
