### ISSUE TITLE
scylla hangs on shutdown in test_total_space_limit_of_commitlog dtest

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12810]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/192/testReport/commitlog_test/TestCommitLog/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_total_space_limit_of_commitlog_with_small_limit/

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/192/artifact/logs-full.release.000/1676097707853_commitlog_test.py%3A%3ATestCommitLog%3A%3Atest_total_space_limit_of_commitlog_with_small_limit/node1.log
```
Scylla version 5.3.0~dev-0.20230211.402d5fd7e39f with build-id fd2a19360ca3c7883c155ea3618de82fcbcddc80 starting ...

INFO  2023-02-11 06:39:38,832 [shard 0] compaction_manager - Asked to stop
INFO  2023-02-11 06:39:38,832 [shard 0] compaction_manager - Stopping 2 tasks for 0 ongoing compactions due to shutdown
INFO  2023-02-11 06:39:38,832 [shard 0] init - Signal received; shutting down
INFO  2023-02-11 06:39:38,832 [shard 0] init - Shutting down view builder ops
INFO  2023-02-11 06:39:38,832 [shard 0] view - Draining view builder
INFO  2023-02-11 06:39:38,832 [shard 0] init - Shutting down view builder ops was successful
INFO  2023-02-11 06:39:38,832 [shard 0] init - Shutting down local storage
INFO  2023-02-11 06:39:38,832 [shard 0] storage_service - Stop transport: starts
INFO  2023-02-11 06:39:38,832 [shard 0] migration_manager - stopping migration service
INFO  2023-02-11 06:39:38,832 [shard 0] storage_service - Shutting down native transport server
WARN  2023-02-11 06:39:38,832 [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
INFO  2023-02-11 06:39:38,832 [shard 0] gossip - failure_detector_loop: Finished main loop
INFO  2023-02-11 06:39:38,833 [shard 0] cql_server_controller - CQL server stopped
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Shutting down native transport server was successful
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Shutting down rpc server
INFO  2023-02-11 06:39:38,833 [shard 0] thrift_controller - Thrift server stopped
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Shutting down rpc server was successful
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Shutting down alternator server
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Shutting down alternator server was successful
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Shutting down redis server
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Shutting down redis server was successful
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2023-02-11 06:39:38,833 [shard 0] gossip - My status = NORMAL
INFO  2023-02-11 06:39:38,833 [shard 0] gossip - Announcing shutdown
INFO  2023-02-11 06:39:38,833 [shard 0] storage_service - Node 127.0.51.1 state jump to normal
```

Core dump here: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/192/artifact/logs-full.release.000/1676097707853_commitlog_test.py%3A%3ATestCommitLog%3A%3Atest_total_space_limit_of_commitlog_with_small_limit/node1-scylla.60164.1676097705.core.gz
Reloc package here: http://downloads.scylladb.com/unstable/scylla/master/relocatable/2023-02-11T03:16:01Z/scylla-unstripped-5.3.0~dev-0.20230211.402d5fd7e39f.x86_64.tar.gz

@elcallio please look into this
Cc @eliransin

**Comment by eliransin** [comment]
@bhalevy you mentioned that you think it is related to a recent change by @elcallio, do you have a pointer about what it is?

**Comment by bhalevy** [comment]
I may have misremembered that.

The test last passed in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/189/testReport/commitlog_test/TestCommitLog/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_total_space_limit_of_commitlog_with_large_limit/
version 5d914adcef1f206b684cf4cdfdcbfb0ebd227665

And first failed in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/190/testReport/commitlog_test/TestCommitLog/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_total_space_limit_of_commitlog_with_large_limit/
version 53366db6c66798808143b1e3170f2bb6dbcae5f6

```
$ git log --oneline 5d914adcef1f206b684cf4cdfdcbfb0ebd227665..53366db6c66798808143b1e3170f2bb6dbcae5f6
53366db6c6 build: disable Seastar's io_uring backend again
b4559a6992 Update seastar submodule
40142a51d0 test: topology: wait for token ring/group 0 consistency after decommission
1b2140e416 compaction: Fix inefficiency when updating LCS backlog tracker
5d1e40bc18 Added missing full stop to SimpleSnitch paragraph
132af20057 Merge 'test/pylib: scylla_cluster: ensure there's space in the cluster pool when running a sequence of tests' from Kamil Braun
681a066923 test/pylib: put UNIX-domain socket in /tmp
325246ab2a Merge 'doc: fix the service name from "scylla-enterprise-server" "to "scylla-server"' from Anna Stuchlik
2be131da83 doc: fixes https://github.com/scylladb/scylladb/issues/12672, fix the redirects to the Cloud docs
d8073edbb7 Merge 'cql3, locator: call fmt::format_to() explicitly and include used headers' from Kefu Chai
d065f9f82e sstables: The generation_type is not formattable
186ceea009 cql3/selection: construct string_view using char* not size
616bf26422 docs: add opensource flag
11a59bcc76 doc: fix the service name in the upgrade guide for patch releases versions 2022
71ae644d40 doc: fix the service name in the upgrade guide from 2021.1 to 2022.1
58b4dc5b9a cql3/stats: include the used header.
ccc03dd1ec cql3, locator: call fmt::format_to() explicitly
8655a8be19 docs: Update suggested AWS instance types in benchmark tips
c927eea1d5 Merge 'table: trim ranges for compaction group cleanup' from Benny Halevy
64cc4c8515 docs: fixes https://github.com/scylladb/scylladb/issues/12654, update the links to the Download Center
fa7e904cd6 commitlog: fix total_size_on_disk accounting after segment file removal
3eabe04f5d test/pylib: scylla_cluster: ensure there's space in the cluster pool when running a sequence of tests
b5ef57ecc2 test/pylib: pool: introduce `replace_dirty`
858803cc2c test/pylib: pool: replace `steal` with `put(is_dirty=True)`
1123565eb0 table: perform_cleanup_compaction: trim owned ranges on compaction_group boundaries
95a8e0b21d table: make_compaction_groups: calculate compaction_group token ranges
912b56ebcf dht: range_streamer: define logger as static
```

**Comment by elcallio** [comment]
So I can't even run this test in current master. When it gets to executing the cassandra-stress part, it just times out. No apparent info from scylla on what it thinks is bad. But some quick experimenting shows that it is the `--memory 512M` flag sent to the scylla node process that causes it to hang/deadlock. Oh, and shutting down is very much blocked here as well... Changing this makes the test at least fail in different ways...

**Comment by elcallio** [comment]
Turns out the real bug is an ancient one: We did not update `total_size_on_disk` in commitlog totals when o_dsync was off. I am guessing that before fa7e904cd6  we instead caused counter wrap-arounds here, and the tests managed to work because of this.

**Comment by bhalevy** [comment]
> Turns out the real bug is an ancient one: We did not update `total_size_on_disk` in commitlog totals when o_dsync was off. I am guessing that before [fa7e904](https://github.com/scylladb/scylladb/commit/fa7e904cd6e55f67c360c49fc4910fc517757bbb) we instead caused counter wrap-arounds here, and the tests managed to work because of this.

Out of curiosity, can you please point at the code to where the hang happened due to the counter mis-handling?

**Comment by elcallio** [comment]
Did not try to figure that part out...

**Comment by elcallio** [comment]
Yeah, as expected, it fails due to counter wrap-around (we actually delete a segment), then count down total on disk ->very large number -> no new segment. It works with more memory allocated because no memtable flush happens.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport to 5.2

See https://jenkins.scylladb.com/job/scylla-5.2/job/dtest-daily-release/4/testReport/commitlog_test/TestCommitLog/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_total_space_limit_of_commitlog_with_memory_based_limit/ et. al.

**Comment by denesb** [comment]
> @scylladb/scylla-maint please backport to 5.2

Backport queued as 128050e9844ec53527a2057954f839edffa7da91.

**Comment by avikivity** [comment]
What about earlier versions? Are they not vulnerable?

If not, the backport candidate label should be removed.

**Comment by denesb** [comment]
> @denesb ^^

Sorry, I thought I answered this.

Removing backport candidate label, as according to my understanding, the bug was benign before https://github.com/scylladb/scylladb/commit/fa7e904cd6e55f67c360c49fc4910fc517757bbb, which is only in 5.2.
@bhalevy @elcallio if my reasoning was flawed, please re-add the label and specify what other versions need the backport.
