### ISSUE TITLE
Flaky Alternator test test_scan.py :: test_scan_long_partition_tombstone_string

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#12817]
The Alternator test `test_scan.py::test_scan_long_partition_tombstone_string` tests that a full-table scan (in Alternator) that encounters a long list of consecutive partition tombstones, and verifies that the scan stops a page after a configured limit (`query_tombstones_page_limit`) instead of continuing an unbounded amount of time.

Unfortunately, for a full-table scan (unlike a single-partition scan), because of our parallel algorithm, Scylla may actually read more than that limit because it may read from multiple vnodes concurrently. Experimentally, I noticed that it never read more than 4 times the limit, so this is what I used in the test. However, it turns out that in some very rare occasions, it can be over 4., and this test with its 4-multiplied limit failed three times in the last couple of months in our various CI runs (the latest case was 
https://jenkins.scylladb.com/job/scylla-master/job/build/1363/).

So I'll probably need to increase this multiplier "4" in the test.

**Comment by denesb** [comment]
@nyh please look into backporting this. We just seen a failure in next-2023.1.
We don't normally backport test fixes but this is a very simple fix and solves an annoying flakyness.

**Comment by nyh** [comment]
Backported to next-5.2 (12a29edf901b2d051ed01047de1e870de930ec2c). Not backporting to earlier releases as this was anyway a xfailing test in those releases (and anyway skipped because it was very slow).
