### ISSUE TITLE
types: deserializing multiprecision_int can access unitialized memory

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12821]
https://github.com/scylladb/scylladb/blob/2653865b34d86ef338fa6f55fb29fe81675924bc/types.cc#L2024-L2042
`bool negative = current_fragment().front() < 0` assumes current fragment is not empty, which is not always true, the previous unserializer in the chain might have consumed the current fragment entirely, so this read will trigger reading uninitialized memory and hence undefined behavior.
Found by running range scans with random schema and random data.

**Comment by denesb** [comment]
I already have a fix.

**Comment by michoecho** [comment]
I'm personally responsible for this bug (495bf5c431f872ac733f9ec9797f766a85e23e8d).

> assumes current fragment is not empty, which is not always true, the previous unserializer in the chain might have consumed the current fragment entirely

It was supposed to be always true, dammit. The consumption function of `FragmentedView` (`remove_prefix`) in all implementations takes care not to leave an empty fragment in the front. This means that the empty fragments are coming from the buffers themselves, not from their views. I didn't expect that when I wrote the code.

This is not the first time I see this, but apparently last time (https://github.com/scylladb/scylladb/pull/8397#issuecomment-812520964) I didn't think to go over all the deserialization code and look for other instances of the same misunderstanding. So some of them were fixed, while these two (varint and bool deserizalization in types.cc) remained...

**Comment by denesb** [comment]
Since `FragmentedView` is an interface, we cannot guarantee that all implementations will be well behaved in this regards.

**Comment by michoecho** [comment]
> Since `FragmentedView` is an interface, we cannot guarantee that all implementations will be well behaved in this regards.

That's true. I should have known better.

**Comment by mykaul** [comment]
I assume will be backported to 5.2 as well?

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.
