### ISSUE TITLE
types: deserializing bool can access uninitialized memory

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#12823]
https://github.com/scylladb/scylladb/blob/2653865b34d86ef338fa6f55fb29fe81675924bc/types.cc#L2117-L2123

`return v.current_fragment().front() != 0; ` assumes current fragment is not empty, which is not always true, the previous unserializer in the chain might have consumed the current fragment entirely, so this read will trigger reading uninitialized memory and hence undefined behavior.
Found by running range scans with random schema and random data.

**Comment by mykaul** [comment]
I assume this is going into 5.2 as well.

**Comment by denesb** [comment]
Fixes for bugs like this usually get backported to all live releases.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.
