### ISSUE TITLE
Raft dueling_repro test failure in next

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#12825]
```
- raft.replication_test.drops_04_dueling_repro_drops.1.xunit.xml.[empty]
- raft.replication_test.drops_04_dueling_repro_drops.2.xunit.xml.[empty]
- raft.replication_test.drops_04_dueling_repro.3.xunit.xml.[empty]
```

HEAD: 076e1bb23b99bfcc1e03c815ef4df5641d3553b2

queue:

10ca08e8aca99f0e382b7b5577b4e2bf7c1b7106 Merge 'Sequence CDC preimage select with Paxos learn write' from Kamil Braun
a24600a662b9a481986c63305d5523d2578690e2 Merge 'test/pylib: split and refactor topology tests' from Alecco
5e9964d7dc0b67e39f806898a9e89c2185d8a290 Update seastar submodule
aa74967488e7e75312f85d91c20912fdf1635b6b sstable_test_env: Remove working_sst helper
a59f55d4109862ff5400e90dcf0a57aaf7611454 install-dependencies.sh: update node_exporter to 1.5.0
747cdf6c9b7854380afe35aa4a14bdf299143cdf test/cql-pytest: regression test for old bug of misused index
7b99382cbe1b6a981ef2755f4e80314aa43c2c56 configure.py: use seastar_dep and seastar_testing_dep
c27c1ac1ec0334cbd11bdda49b9a12c9170df3d0 Merge 'test/pylib: use larger timeout for decommission/removenode' from Kamil Braun
7e90d3b659a8209aee41249ed4e19bef09c81f54 docs/operating-scylla: add a document on diagnostic tools
e2e271c7e70c80eb21bb965b017a0262f7762958 test/cql-pytest: another reproducer for index+limit+filtering bug
df368ec8a5c1c528a34f76ad39262c5975102f9a test/alternator: more tests for listing streams
0b25e667f27be3af6324a7918318cc51675ed0f2 Merge 'cql3: convert LWT IF clause to expressions' from Avi Kivity
6803db56745070f602bd6acc8bed6d6e5263d428 abstract_replication_strategy: add for_each_natural_endpoint_until
076e1bb23b99bfcc1e03c815ef4df5641d3553b2 (HEAD -> next, origin/next) Merge 'functions: handle replacing UDFs used in UDAs' from Wojciech Mitros

**Comment by xemul** [comment]
dup of #12820

**Comment by kbr-scylla** [comment]
Closing as duplicate
