### ISSUE TITLE
`nodetool scrub --no-snapshot` exits with a warning that my disk space is low. 

### ISSUE THREAD

**Issue by buptzhoutian** [scylladb/scylladb#12864]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version : `4.4.4`
Cluster size: `3G`
OS : `Debian-10`

---------

I tried to exec `nodetool scrub` on one node of a small scylladb cluster, however it failed to start, and told me to add more capacity, even when snapshot is disabled and the free space is enough. 

```
$ nodetool  status
Using /etc/scylla/scylla.yaml as the config file
Datacenter: dc1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.19.21.118  2.33 GB    256          ?       a995bf88-ad18-11ed-94d8-fb11af478785  dc1-k
UN  10.19.21.220  2.31 GB    256          ?       b3159268-ad18-11ed-97e8-83c62d60a5dc  dc1-k
UN  10.19.21.82   2.32 GB    256          ?       b757d00c-ad18-11ed-a4e1-2b0dfba7ccd8  dc1-i
UN  10.19.21.77   2.32 GB    256          ?       bb212d32-ad18-11ed-bc84-a789fa405883  dc1-j
UN  10.10.21.20   2.3 GB     256          ?       bee2ee9c-ad18-11ed-90eb-df7a7508e0fc  dc1-h

$ nodetool  scrub --no-snapshot -- ks table
Using /etc/scylla/scylla.yaml as the config file
WARN  17:03:24,280 Only 62.121GiB free across all data volumes. 
Consider adding more capacity to your cluster or removing obsolete snapshots

$ nodetool  listsnapshots
Using /etc/scylla/scylla.yaml as the config file
Snapshot Details:
There are no snapshots
```

**Comment by michoecho** [comment]
The warning doesn't estimate free space against the size of sstables (though it probably should). It is hardcoded to 64 GiB:

https://github.com/scylladb/scylla-tools-java/blob/f0bab7af668b0f763900a11ccb066b202e4cc82e/src/java/org/apache/cassandra/config/DatabaseDescriptor.java#L557-L560

But it is just a harmless warning. It doesn't affect anything, in particular it doesn't cause nodetool to stop. Are you sure nodetool failed to start? Maybe it just exited quickly, but successfully?

**Comment by buptzhoutian** [comment]
> The warning doesn't estimate free space against the size of sstables (though it probably should). It is hardcoded to 64 GiB:
> 
> https://github.com/scylladb/scylla-tools-java/blob/f0bab7af668b0f763900a11ccb066b202e4cc82e/src/java/org/apache/cassandra/config/DatabaseDescriptor.java#L557-L560
> 
> But it is just a harmless warning. It doesn't affect anything, in particular it doesn't cause nodetool to stop. Are you sure nodetool failed to start? Maybe it just exited quickly, but successfully?

Thank you for your help!
You are right, although there aren't any log messages or console output indicating the scrub is done, I can see "Finished scrubbing" syslog messages of all the shards.
