### ISSUE TITLE
data_dictionary_impl might return invalid data

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#12875]
`get_table_views()` return a reference, but `data_dictionary_impl::get_table_views()` return a reference to a temporary value. this is not allowed.

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by avikivity** [comment]
Backported to 5.2, 5.1, though I suspect it can't be triggered.
