### ISSUE TITLE
`standard_memory_segment_store_backend` is leaked when gets destroyed

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#12872]
in `contiguous_memory_segment_store`, the lifecycle of allocated `seastar_memory_segment_store_backend` is managed by a `unique_ptr<segment_store_backend>`. but `segment_store_backend` does not have a virtual dtor.

so `contiguous_memory_segment_store` is destroyed with the dtor of its parent class. this is not expected.

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by avikivity** [comment]
No real impact, not backporting.
