### ISSUE TITLE
Do not pull schema on_join if raft schema is ON

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#12870]
Currently scylla registers a migration manager subscription to on_join event in Gossiper and performs a schema pull on every join event. This is unnecessary. We can remove the pull action from pretty much all Gossiper events, if Raft is enabled.

This is a follow up to strongly consistent schema changes.

**Comment by DoronArazii** [comment]
Pushing to 5.4 (we've already branched out to 5.3).

**Comment by kbr-scylla** [comment]
Reopening as per @tgrabiec 's comment (https://github.com/scylladb/scylladb/pull/13695#discussion_r1204276339) - the merged PR does not completely fix the problem of eradicating migration_manager schema pulls. E.g. `using_raft()` function may return `false` during early stages of node startup even though Raft was enabled before in the cluster.

We need to fix this before GA-ing topology.

**Comment by denesb** [comment]
@kbr-scylla please evaluate for backport.

**Comment by kbr-scylla** [comment]
It doesn't fix any known issue in 5.2.
