### ISSUE TITLE
Schema loading should not ignore parts which are disabled by cluster features 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#12895]
There is a cluster feature called SCYLLA_KEYSPACES (introduced in 58529591a9ac9be49f53a69ed33cb9161406be95), which when enabled allows one to create keyspaces with a non-default `storage_type`.

Currently, schema loading code will ignore the mutations which correspond to those attributes if the cluster feature is not enabled:

```c++
    co_await proxy.local().get_db().invoke_on_all([&] (replica::database& db) -> future<> {
        for (auto&& val : created) {
            auto scylla_specific_rs = co_await extract_scylla_specific_keyspace_info(proxy, val);
            auto ksm = create_keyspace_from_schema_partition(val, std::move(scylla_specific_rs));
            co_await db.create_keyspace(ksm, proxy.local().get_erm_factory());
```

```c++

future<lw_shared_ptr<query::result_set>> extract_scylla_specific_keyspace_info(distributed<service::storage_proxy>& proxy, const schema_result_value_type& partition) {
    lw_shared_ptr<query::result_set> scylla_specific_rs;
    if (proxy.local().features().cluster_schema_features().contains<schema_feature::SCYLLA_KEYSPACES>()) {
        ...
    }
    co_return scylla_specific_rs;
```

This is dangerous, because if such mutations are present, it's incorrect to create a keyspace which behaves not with accordance to those attributes. Such keyspaces can be created only after all nodes are able to recognize the new attributes.

Rather than silently dropping such mutations, the node should fail.

\cc @xemul 

Refs #12590

**Comment by kostja** [comment]
Schema is managed by Raft, features are negotiated using Raft, it's impossible to address past features, but for all future features it's not possible.
