### ISSUE TITLE
init - Startup failed: seastar::sleep_aborted (Sleep is aborted)

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#12898]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

**Problem**
Startup failed on a new node that was created as replacement for terminated/decommissioned node:
```
Feb 09 18:18:25 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

**Description**

This falure happens twice during this test.
Test runs with workload prioritization (I am not sure if it is connected to the issue).

1. First time it happens during decommission nemesis. `longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-1` has been decommissioned and new `longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 (3.250.19.195 | 10.4.0.18`) node was added and starting:

```
Feb 09 18:18:06 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - Scylla version 2022.1.5-0.20230108.8c2c21866 with build-id 90676755bb7af26527b54cf1a5afb6498162afba starting ...
```

12 seconds later `system_auth.roles` table was created and then waiting for gossip:
```
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] schema_tables - Creating system_auth.roles id=5bc52802-de25-35ed-aeab-188eecebb090 version=ea493725-02da-35db-a811-8c3d56
02f317
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] schema_tables - Schema version changed to f337bf8c-8ae7-3fb1-8736-765babb83237
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - starting batchlog manager
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - starting load meter
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - starting cf cache hit rate calculator
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - starting view update backlog broker
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - Waiting for gossip to settle before accepting client requests...
```

Immediatelly after that Scylla was stopped:
```
Feb 09 18:18:20 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] compaction - [Compact system_schema.keyspaces 21a9ff60-a8a6-11ed-9d76-7a1eec6b1387] Compacted 7 sstables to [/var/lib/scy
lla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-280-big-Data.db:level=0]. 93kB to 14kB (~15% of original) in 6ms = 2MB/s. ~896 total partitions merged to 6.
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 systemd[1]: Stopping Scylla JMX...
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 systemd[1]: Stopped Scylla JMX.
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] compaction_manager - Asked to stop
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 systemd[1]: Stopping Scylla Server...
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 6] compaction_manager - Stopped
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
Feb 09 18:18:23 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] gossip - failure_detector_loop: Finished main loop
```

And startup failed:
```
Feb 09 18:18:25 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 scylla[9336]:  [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

2. Second time it happened during terminate and replace nemesis. `longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-4` was terminated and new `longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 (34.244.86.108 | 10.4.1.190)` was srationg:
```
Feb 09 19:43:13 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] init - Scylla version 2022.1.5-0.20230108.8c2c21866 with build-id 90676755bb7af26527b54cf1a5afb6498162afba starting ...
```

12 seconds later `system_auth.roles` table creation and waiting for gossip:
```
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] schema_tables - Creating system_auth.roles id=5bc52802-de25-35ed-aeab-188eecebb090 version=ad4e69b2-6508-37a7-a378-0d04d8
2bdaca
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] schema_tables - Schema version changed to 0ea3d465-4a91-30ab-9fef-1bb0a71e60e6
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] init - starting batchlog manager
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] init - starting load meter
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] init - starting cf cache hit rate calculator
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] init - starting view update backlog broker
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] init - Waiting for gossip to settle before accepting client requests...
```

Immediatelly the Scylla was stopped:
```
Feb 09 19:43:26 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] compaction - [Compact system_schema.scylla_tables 05507f40-a8b2-11ed-8da4-635f0950790e] Compacted 4 sstables to [/var/lib/scylla/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-182-big-Data.db:level=0]. 54kB to 14kB (~26% of original) in 9ms = 1MB/s. ~512 total partitions merged to 6.
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: Stopping Scylla JMX...
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: Stopped Scylla JMX.
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] compaction_manager - Asked to stop
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: Stopping Scylla Server...
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
Feb 09 19:43:29 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] gossip - failure_detector_loop: Finished main loop
```

Startup failed:
```
Feb 09 19:43:31 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 scylla[9279]:  [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
Feb 09 19:44:44 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: scylla-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 19:44:44 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: scylla-server.service: Failed with result 'exit-code'.
Feb 09 19:44:44 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: Stopped Scylla Server.
Feb 09 19:44:47 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 systemd[1]: Starting Scylla Server...
```

No errors/coredump/aborting/faults. Scylla was started successfully after that

## Impact

Scylla was started successfully after that

## How frequently does it reproduce?

twice during same test run

## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `2022.1.5-20230108.8c2c21866` with build-id `90676755bb7af26527b54cf1a5afb6498162afba`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.1/scylla-enterprise-x86_64-package-2022.1.5.0.20230108.8c2c21866.tar.gz

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-8 (34.244.86.108 | 10.4.1.190) (shards: 14)
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7 (3.250.19.195 | 10.4.0.18) (shards: 14)
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-6 (18.203.111.207 | 10.4.0.81) (shards: 14)
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-5 (52.18.185.36 | 10.4.0.76) (shards: 14)
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-4 (34.241.207.150 | 10.4.0.35) (shards: 14)
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-3 (34.245.22.37 | 10.4.0.113) (shards: 14)
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-2 (34.245.97.254 | 10.4.2.60) (shards: 14)
- longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-1 (3.252.194.109 | 10.4.3.61) (shards: 14)

OS / Image: `ami-0287067067652acb9` (aws: eu-west-1)

Test: `longevity-sla-100gb-4h-test`
Test id: `910e5c8f-b2de-44e8-bf21-de82c605135d`
Test name: `enterprise-2022.1/SCT_Enterprise_Features/Workload_Prioritization/longevity-sla-100gb-4h-test`
Test config file(s):

- [longevity-sla-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f7f2ad938ec65adf0229b47ebdde6c9a8d6c39b4/test-cases/longevity/longevity-sla-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 910e5c8f-b2de-44e8-bf21-de82c605135d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=910e5c8f-b2de-44e8-bf21-de82c605135d)
- Show all stored logs command: `$ hydra investigate show-logs 910e5c8f-b2de-44e8-bf21-de82c605135d`

## Logs:
- **db-cluster-910e5c8f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/db-cluster-910e5c8f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/db-cluster-910e5c8f.tar.gz)
- **sct-runner-910e5c8f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/sct-runner-910e5c8f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/sct-runner-910e5c8f.tar.gz)
- **monitor-set-910e5c8f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/monitor-set-910e5c8f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/monitor-set-910e5c8f.tar.gz)
- **loader-set-910e5c8f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/loader-set-910e5c8f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/loader-set-910e5c8f.tar.gz)
- **parallel-timelines-report-910e5c8f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/parallel-timelines-report-910e5c8f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/910e5c8f-b2de-44e8-bf21-de82c605135d/20230209_195531/parallel-timelines-report-910e5c8f.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/Workload_Prioritization/job/longevity-sla-100gb-4h-test/2/)
</details>

**Comment by fgelcer** [comment]
seeing such behavior for Azure artifacts test:
```
systemd[1]: Stopping Scylla JMX...
systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
systemd[1]: Stopped Scylla JMX.
systemd[1]: scylla-jmx.service: Consumed 4.186s CPU time.
scylla[4567]:  [shard 0] compaction_manager - Asked to stop
systemd[1]: Stopping Scylla Server...
scylla[4567]:  [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
scylla[4567]:  [shard 0] gossip - failure_detector_loop: Finished main loop
scylla[4567]:  [shard 0] init - Signal received; shutting down
```

and then, a 2nd time:
```
scylla[7867]:  [shard 0] init - serving
scylla[7867]:  [shard 0] init - Scylla version 5.3.0~dev-0.20230423.bd0b299322c9 initialization completed.
systemd[1]: Stopping Scylla JMX...
systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
systemd[1]: Stopped Scylla JMX.
systemd[1]: scylla-jmx.service: Consumed 2.196s CPU time.
scylla[7867]:  [shard 0] compaction_manager - Asked to stop
scylla[7867]:  [shard 3] compaction_manager - Asked to stop
systemd[1]: Stopping Scylla Server...
scylla[7867]:  [shard 6] compaction_manager - Asked to stop
scylla[7867]:  [shard 3] compaction_manager - Stopped
scylla[7867]:  [shard 6] compaction_manager - Stopped
scylla[7867]:  [shard 2] compaction_manager - Asked to stop
scylla[7867]:  [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
scylla[7867]:  [shard 0] gossip - failure_detector_loop: Finished main loop
```

[job is here](https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-azure-image-test/70) and logs can be downloaded as follow:
[db-cluster logs](https://cloudius-jenkins-test.s3.amazonaws.com/a920b0ba-b864-4de0-b30a-6cfa55a876d5/20230423_145316/db-cluster-a920b0ba.tar.gz)
[sct-runner-events](https://cloudius-jenkins-test.s3.amazonaws.com/a920b0ba-b864-4de0-b30a-6cfa55a876d5/20230423_145316/sct-runner-events-a920b0ba.tar.gz)
[sct-runner-python-log](https://cloudius-jenkins-test.s3.amazonaws.com/a920b0ba-b864-4de0-b30a-6cfa55a876d5/20230423_145316/sct-a920b0ba.log.tar.gz)


not sure why we don't have the regular sct.logs... @temichus @soyacz @fruch  ?

**Comment by yaronkaikov** [comment]
@mykaul @DoronArazii This issue seems to cause the Azure artifact test to fail, preventing the' next-machine-image' from being promoted. we need it to backport the kernel fix to 5.2 and start `rc5`

**Comment by fruch** [comment]
> seeing such behavior for Azure artifacts test:
> ```
> systemd[1]: Stopping Scylla JMX...
> systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
> systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
> systemd[1]: Stopped Scylla JMX.
> systemd[1]: scylla-jmx.service: Consumed 4.186s CPU time.
> scylla[4567]:  [shard 0] compaction_manager - Asked to stop
> systemd[1]: Stopping Scylla Server...
> scylla[4567]:  [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
> scylla[4567]:  [shard 0] gossip - failure_detector_loop: Finished main loop
> scylla[4567]:  [shard 0] init - Signal received; shutting down
> ```
> 
> and then, a 2nd time:
> ```
> scylla[7867]:  [shard 0] init - serving
> scylla[7867]:  [shard 0] init - Scylla version 5.3.0~dev-0.20230423.bd0b299322c9 initialization completed.
> systemd[1]: Stopping Scylla JMX...
> systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
> systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
> systemd[1]: Stopped Scylla JMX.
> systemd[1]: scylla-jmx.service: Consumed 2.196s CPU time.
> scylla[7867]:  [shard 0] compaction_manager - Asked to stop
> scylla[7867]:  [shard 3] compaction_manager - Asked to stop
> systemd[1]: Stopping Scylla Server...
> scylla[7867]:  [shard 6] compaction_manager - Asked to stop
> scylla[7867]:  [shard 3] compaction_manager - Stopped
> scylla[7867]:  [shard 6] compaction_manager - Stopped
> scylla[7867]:  [shard 2] compaction_manager - Asked to stop
> scylla[7867]:  [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[]: seastar::sleep_aborted (Sleep is aborted)
> scylla[7867]:  [shard 0] gossip - failure_detector_loop: Finished main loop
> ```
> 
> [job is here](https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-azure-image-test/70) and logs can be downloaded as follow:
> [db-cluster logs](https://cloudius-jenkins-test.s3.amazonaws.com/a920b0ba-b864-4de0-b30a-6cfa55a876d5/20230423_145316/db-cluster-a920b0ba.tar.gz)
> [sct-runner-events](https://cloudius-jenkins-test.s3.amazonaws.com/a920b0ba-b864-4de0-b30a-6cfa55a876d5/20230423_145316/sct-runner-events-a920b0ba.tar.gz)
> [sct-runner-python-log](https://cloudius-jenkins-test.s3.amazonaws.com/a920b0ba-b864-4de0-b30a-6cfa55a876d5/20230423_145316/sct-a920b0ba.log.tar.gz)
> 
> 
> not sure why we don't have the regular sct.logs... @temichus @soyacz @fruch  ?

sct runner logs now split into two files, one with SCT.log and one with the rest of the files, events output and such

**Comment by fruch** [comment]
@fgelcer @yaronkaikov 
the issue you are facing isn't related to this issue, it's an SCT issue
I'm fixing it in https://github.com/scylladb/scylla-cluster-tests/pull/6062

**Comment by fgelcer** [comment]
in this case, i just deleted my commento to not mess up with this one

**Comment by yaronkaikov** [comment]
> in this case, i just deleted my commento to not mess up with this one

me2

**Comment by bhalevy** [comment]
What exactly is the issue?

For example, for the first (decommission) case, I see:
```
2023-02-09T18:18:23+00:00 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7   !NOTICE | sudo[9769]: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl stop scylla-server.service
```

Why is the service stopped?
Is it part of the test?

Is the issue that scylla is stopped, or that it doesn't stop cleanly, and it prints this error?
```
2023-02-09T18:18:26+00:00 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7      !ERR | scylla[9336]:  [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

**Comment by DoronArazii** [comment]
@juliayakovlev ^^

**Comment by juliayakovlev** [comment]
@bhalevy 

> What exactly is the issue?
> 
> For example, for the first (decommission) case, I see:
> 
> ```
> 2023-02-09T18:18:23+00:00 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7   !NOTICE | sudo[9769]: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl stop scylla-server.service
> ```
> 
> Why is the service stopped? Is it part of the test?
> 
> Is the issue that scylla is stopped, or that it doesn't stop cleanly, and it prints this error?

I re-checked, we really restart the scylla. So the issue that Scylla was stopped with "Startup failed" error

> 
> ```
> 2023-02-09T18:18:26+00:00 longevity-sla-100gb-4h-2023-1-db-node-910e5c8f-7      !ERR | scylla[9336]:  [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
> ```

**Comment by bhalevy** [comment]
So this is very minor.
We just need to attenuate the sleep_aborted exception in https://github.com/scylladb/scylladb/blob/1cefb662cd2cfb1474d46901726eee9c55d3bef3/main.cc#L1765
and exit cleanly in this case.

**Comment by bhalevy** [comment]
@xemul ^^

**Comment by fruch** [comment]
> > So this is very minor. We just need to attenuate the sleep_aborted exception in
> > 
> > https://github.com/scylladb/scylladb/blob/1cefb662cd2cfb1474d46901726eee9c55d3bef3/main.cc#L1765
> > 
> > 
> > and exit cleanly in this case.
> 
> @bhalevy When did you plan to fix it? Now we can get test failed with this error despite it is minor
> @roydahan should we decrease error severity / ignore this error?

We can't ignore such an error, if scylla fails to boot, it's not something we easily can ignore

**Comment by juliayakovlev** [comment]
> > > So this is very minor. We just need to attenuate the sleep_aborted exception in
> > > https://github.com/scylladb/scylladb/blob/1cefb662cd2cfb1474d46901726eee9c55d3bef3/main.cc#L1765
> > > 
> > > and exit cleanly in this case.
> > 
> > 
> > @bhalevy When did you plan to fix it? Now we can get test failed with this error despite it is minor
> > @roydahan should we decrease error severity / ignore this error?
> 
> We can't ignore such an error, if scylla fails to boot, it's not something we easily can ignore

Startup did not failed. We configure a new node and restart Scylla. This error arrear when we (from SCT) stop Scylla. This is wrong error diuring stopping service

**Comment by denesb** [comment]
This issue is not relevant to production deployments, not backporting.
