### ISSUE TITLE
Allow evaluating any CQL expressions

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#12906]
A CQL [expression](https://github.com/scylladb/scylladb/blob/ef50170120153b7cc11bea7cfccfa85b5a28bd82/cql3/expr/expression.hh#L147) is our representation of a parsed CQL abstract syntax tree.

Pieces of CQL like `pk = 3` or `token(p1, p2) IN (1, udf_function(1, other_column)) AND c1 = 3 AND ck < 2`  are parsed by ANTLR and then represented as `expression`.

We would like to be able to evaluate any such expression to a single value. This is the job of the function [`expr::evaluate`](https://github.com/scylladb/scylladb/blob/ef50170120153b7cc11bea7cfccfa85b5a28bd82/cql3/expr/expression.hh#L750). It takes an expression like `pk = 3`, finds out the value of `pk` and then evaluates the whole expression to `TRUE`, `FALSE`, `NULL` or an error.

The function is already implemented for most types of expressions, but other still cause `on_internal_error`.

Having `evaluate` could greatly simplify the filtering code. Instead of extracting restrictions for each column and then checking whether they are true we could just call `evaluate()` on the whole WHERE clause. This is currently impossible because e.g `token(pk)` will cause `on_internal_error`, so special care has to be taken to avoid any such situations.

It will also allow us to move forward with the CQL rewrite. It will be much easier and safer to refactor when we can just call `evaluate()` on any expression without worries about crashing.

**Comment by avikivity** [comment]
Still missing column_mutation_attrbute.

**Comment by DoronArazii** [comment]
I'm wondering why it didn't received the auto-"backport candidate" label from the bot.
Although, I know it's probably won't get backported.

**Comment by avikivity** [comment]
It has the "enhancement" label.
