### ISSUE TITLE
Moving WASM compilation to alien

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#12904]
Currently, the compilation of WASM UDFs is performed by a call to a foreign function (wasmtime::precompile_module), which cannot be divided with yielding points and, as a result, causes
long reactor stalls for big UDFs, which in turn may increase latency.

Some time ago, when discussing this problem with @avikivity, he suggested submitting the compilation to the `alien` instance. This would in fact remove the stalls (because the stall detector does not measure the execution time of `alien` tasks) and help with latency (the `alien` tasks are executed only after the more "urgent" tasks), but I'm not sure whether the difference would be worthwhile.

Also, I'm not completely sure how to approach implementation of this. I started writing a working example like [this](https://github.com/scylladb/scylladb/commit/d35cc886f79dcdf2f39d71efa5b136dd1b0b2ed8#diff-e52e05ed9f80dc30769fd670b11bd29b7910703a45628f06dde87ec31171360a) but this approach may be completely wrong, so I'm not posting a PR yet, and waiting for some input instead

**Comment by wmitros** [comment]
@avikivity what do you think? (And is there someone else I should tag here?)

**Comment by wmitros** [comment]
Apparently, if we do this well, we can avoid impacting latency completely, because alien will execute the compilation on another shard used for less latency-prone tasks 
I think this got buried in your notifications @avikivity so I'm adding you again.
The initial approach is [here](https://github.com/scylladb/scylladb/commit/d35cc886f79dcdf2f39d71efa5b136dd1b0b2ed8#diff-e52e05ed9f80dc30769fd670b11bd29b7910703a45628f06dde87ec31171360a)
@tchaikov I see you've also worked on alien in seastar, so maybe you can also give me some ideas

**Comment by avikivity** [comment]
run_on() is a way for the alien thread to run something on Seastar.

For seastar to run something on the alien thread, launch an std::thread in main(), give it some mutex-protected queue of std::packaged_task, and place the packaged_task from the thread. The last thing the task does is call alien::submit_to(original_shard, [&] { done.set_value(the_result); }); do notify the caller shard that it is done.

**Comment by wmitros** [comment]
> run_on() is a way for the alien thread to run something on Seastar.
> 
> For seastar to run something on the alien thread, launch an std::thread in main(), give it some mutex-protected queue of std::packaged_task, and place the packaged_task from the thread. The last thing the task does is call alien::submit_to(original_shard, [&] { done.set_value(the_result); }); do notify the caller shard that it is done.

Thanks, it makes more sense to run it from main(), though it will probably require more work as well. I'll try this approach now

**Comment by tchaikov** [comment]
yes, we use a similar approach in Ceph where we need to schedule some task on alien threads. we create a thread pool, and a task queue for executing the task. since scylladb is using C++20, probably we can just use `std::counting_semaphore` for coordinate the consumer and producer of the task queue. see also https://github.com/ceph/ceph/blob/main/src/crimson/os/alienstore/thread_pool.h .

**Comment by avikivity** [comment]
The thread pool can be of size 1.

**Comment by wmitros** [comment]
I tried to use the approach with an std::thread in main() at https://github.com/scylladb/scylladb/pull/13051. The resulting code was heavily inspired by https://github.com/ceph/ceph/blob/main/src/crimson/os/alienstore/thread_pool.h, but I tried to reduce it just to our use case. @avikivity @tchaikov please take a look

**Comment by avikivity** [comment]
Please file it as a pull request in draft more, I don't want yet another way to review.

**Comment by wmitros** [comment]
Ok, I converted https://github.com/scylladb/scylladb/pull/13051 to draft mode

**Comment by avikivity** [comment]
It was just me being confused. I thought for no reason you were pointing me to a branch, not a pull. There's no problem having it in non-draft mode if it's in a ready state.

**Comment by avikivity** [comment]
Not a bug, not backporting.
