### ISSUE TITLE
Adding a UDT field of type duration doesn't check whether it's allowed

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#12913]
Having values of the `duration` type is not allowed for clustering columns, because `duration` can't be ordered (is 30 days less than 1 month?).
This is correctly validated when creating a table:
```cql
cqlsh:ks> CREATE type type_with_duration (a int, d duration);
cqlsh:ks> CREATE TABLE tab (pk int, ck frozen<type_with_duration>, PRIMARY KEY (pk, ck));
InvalidRequest: Error from server: code=2200 [Invalid query] message="duration type is not supported for PRIMARY KEY part ck"
```

But when adding a new field to a user defined type, there is no check whether this UDT is used in some clustering key.
```cql
cqlsh:ks> CREATE TYPE my_type (a int);
cqlsh:ks> CREATE TABLE tab (pk int, ck frozen<my_type>, PRIMARY KEY (pk, ck));
cqlsh:ks> ALTER TYPE my_type ADD d duration; -- Success, but should fail with an error
```

**Comment by denesb** [comment]
@cvybhu do we need a backport to 5.4?
5.2 doesn't have UDT permissions, so doesn't need it.

**Comment by denesb** [comment]
Backported to 5.4 and 5.2.

**Comment by denesb** [comment]
5.2 backport dequeued, it breaks the build.

**Comment by denesb** [comment]
Re-did 5.2 backport.
