### ISSUE TITLE
Altering a service level timeout doesn't affect existing connections

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#12923]
Currently, the SL timeout is only looked up in the config once, when the connection is started (in https://github.com/scylladb/scylladb/blob/e88f590eda3f5e1c5d076cb1899626a583ddc1cd/transport/server.cc#L859). Hence changing the setting in a live cluster (via `alter service_level x with timeout = y`) won't affect existing connections.

As seen in https://github.com/scylladb/scylla-enterprise/issues/2671, this can easily confuse users. It is also not documented.

We should either document this or — better yet — modify the behavior so that `alter` also affects existing connections. This would make for a better user experience.

Since the code already works with variable timeouts (even per-query timeouts, with `USING TIMEOUT`), this modification should be easy.

**Comment by michoecho** [comment]
Workaround note: if someone wants to apply a new timeout to existing clients, currently the least invasive way to do this is a rolling restart of the CQL transport on all nodes, via a rolling `nodetool disablebinary; nodetool enablebinary` on the cluster, after the `alter`.

**Comment by vladzcloudius** [comment]
@tzach @annastuchlik FYI

**Comment by tzach** [comment]
@eliransin can you please validate?

**Comment by eliransin** [comment]
This is a know caveat that we should address eventually. I will put it in the plan.

**Comment by nyh** [comment]
Hi @michoecho in the original issue you said "We should either document this or — better yet — modify the behavior".
I see several documentation changes were done about this, but all of them were marked as "Refs" this issue, not "Fixes". 
Can you please check if all your documentation concerns have been addressed and this issue can be closed, or if not what needs to be documented? Or, did you decide that documentation is not enough and want to keep the issue open until we modify the behavior?

**Comment by michoecho** [comment]
> Can you please check if all your documentation concerns have been addressed and this issue can be closed, or if not what needs to be documented? Or, did you decide that documentation is not enough and want to keep the issue open until we modify the behavior?

I didn't decide anything; this decision is not mine to make.

But If you are asking for my opinion, then I think we should keep it open until we modify the behavior.
