### ISSUE TITLE
Aggregate functions do not work on counter columns.

### ISSUE THREAD

**Issue by jandrewb** [scylladb/scylladb#12939]
Previous versions of Scylla were able to return the sum of multiple counter value rows. Now, I get an error as described below.

*Installation details*
Scylla version: 5.1

create table test (id uuid, a counter, primary key (id));
update test set a = a+3 where id=now();
select sum(a) from test;

ServerError: Cannot mock aggregate function system.sum

**Comment by DoronArazii** [comment]
@jul-stas can you please check it? (might be a regression)
I saw you've handled something similar 3 y ago https://github.com/scylladb/scylladb/issues/3174

**Comment by michoecho** [comment]
@jandrewb Scylla 5.1 added parallelized aggregates (https://github.com/scylladb/scylladb/pull/10295) and apparently they aren't implemented for counters. You can work around this by disabling parallelized aggregates (e.g. by setting `enable_parallelized_aggregation: false` in the config YAML).

@Jadw1 Why aren't parallel aggregates implemented for counters? A simple oversight?

**Comment by Jadw1** [comment]
Currently we cannot serialize cql's `selection`, so we are sending it as `forwad_request` to other nodes and there recreate (mock) the selection also recreating the aggregation functions.

While mocking the functions, I get function arguments' type based on their names  and schema's types. But as I see now, the sum function's argument is long and I'm looking for function with counter type as argument.

Anyway, I can quickly fix it

**Comment by Jadw1** [comment]
@mykaul This PR #12963 should fix the problem

**Comment by mykaul** [comment]
@Jadw1 - I assume this was backported to 5.1?

**Comment by avikivity** [comment]
It wasn't backported anywhere yet (github leaves a link to the commit when that happens).

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. Autopar is new in 5.1.
