### ISSUE TITLE
No download link for unified installer

### ISSUE THREAD

**Issue by vrischmann** [scylladb/scylladb#12934]
(I'm not sure this is the correct place for issues regarding the website, feel free to redirect me if it isn't).

The download link for the unified installer on this page: https://www.scylladb.com/download/?platform=tar&version=scylla-5.1
is invalid; it is just http://downloads.scylladb.com.s3.amazonaws.com/downloads/scylla/relocatable/scylladb-5.1/ but this is not browsable so I have no way to find the `.tar.gz` archive.

Here's a screenshot of what I see on the download page:
![image](https://user-images.githubusercontent.com/1916079/220060482-7bafb0ec-c5eb-4d7f-afa0-8e81568da194.png)

I naively tried to fetch http://downloads.scylladb.com.s3.amazonaws.com/downloads/scylla/relocatable/scylladb-5.1/scylla-unified-package-5.1.tar.gz but this doesn't exist either.

**Comment by michoecho** [comment]
cc @tzach

The link should be http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.1/ (`downloads.scylladb.com.s3.amazonaws.com` vs `downloads.scylladb.com`).

**Comment by tzach** [comment]
Thanks
Will this work with http**s**?

**Comment by michoecho** [comment]
> Thanks Will this work with http**s**?

Right, it should be https.

**Comment by tzach** [comment]
Actually, https does *not* work

**Comment by michoecho** [comment]
> Actually, https does _not_ work

Why? https://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.1/ works fine for me.

**Comment by tzach** [comment]
You are right, sorry

**Comment by tzach** [comment]
https://github.com/scylladb/scylla-pkg/issues/3319

**Comment by tzach** [comment]
Fixed. Please validate.

**Comment by michoecho** [comment]
> Fixed. Please validate.

It's fixed for 5.1, but not fixed for previous versions.

**Comment by tzach** [comment]
It is now

**Comment by michoecho** [comment]
> It is now

Right. Closing the issue as completed.

@vrischmann Thanks for the report.

**Comment by tzach** [comment]
Thanks @michoecho !
