### ISSUE TITLE
Support Prometheus native histograms once they will be available

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#12931]
Prometheus are replacing their histograms implementation, we should switch to that once it is available

**Comment by tzach** [comment]
Note the feature still experimntal in Promethous
https://github.com/prometheus/prometheus/blob/65cf528403b9cd2f6e4b526ee2c29d2e84c76178/docs/feature_flags.md?plain=1#L107

**Comment by tzach** [comment]
@amnonh any update on Promethous support?
