### ISSUE TITLE
doc: clarify the requirement to restore from a backup

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#12945]
The issue on page https://docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html
The procedure includes the following requirement:

![image](https://user-images.githubusercontent.com/37244380/220292716-1166bbcd-2a82-4a76-b910-c83c064e8b53.png)

However, the restore procedure works without the "same IPs" requirement being fulfilled. See https://scylladb-users.slack.com/archives/C2NLNBXLN/p1676889168358529.

Info from the field: "The same IPs thing was for usage with Ansible. The same number of nodes and token ranges per node is the requirement for this procedure. "

FIX:
1. Remove the second bullet ("same IPs") from the list in the note as it's not relevant if you're not using ansible.
2. Update the note above - it links to the Manager documentation, but it should be replaced with the link to the Manager's Restore page: https://manager.docs.scylladb.com/stable/restore/
![image](https://user-images.githubusercontent.com/37244380/220295814-0257caf3-20e1-41a8-ac05-d737c058a50f.png)

**Comment by annastuchlik** [comment]
@fee-mendes @tzach @bhalevy Could you confirm that the fix I propose is the correct one?

**Comment by fee-mendes** [comment]
LGTM @annastuchlik ! Thanks for the quick turnaround ;-)
