### ISSUE TITLE
docs: Issue in protocol extensions

### ISSUE THREAD

**Issue by wyfo** [scylladb/scylladb#12940]
From LWT prepared statements metadata mark section https://github.com/scylladb/scylladb/blob/master/docs/dev/protocol-extensions.md#lwt-prepared-statements-metadata-mark
> The feature is identified by the SCYLLA_LWT_ADD_METADATA_MARK key that is meant to be sent in the SUPPORTED message along with the following additional parameters:
> -    SCYLLA_LWT_OPTIMIZATION_META_BIT_MASK is a 32-bit unsigned integer that represents the bit mask that should be used by the client to test against when checking prepared statement metadata flags to see if the current query is conditional or not.

Documentation is wrong, as the parameter is named `LWT_OPTIMIZATION_META_BIT_MASK`, as written in Scylla code:
https://github.com/scylladb/scylladb/blob/d3c6e72c6934cb7b8f16231ea2fa7075d855202f/transport/cql_protocol_extension.cc#L34

**Comment by annastuchlik** [comment]
@wyfo Thanks for reporting this documentation bug. I'll fix it right away.
