### ISSUE TITLE
docs: Issue in page Upgrade Guide - ScyllaDB Enterprise 2021.1 to 2022.1 for Ubuntu/Debian/Ent image

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylladb#12954]
I would like to report an issue in the following pages:
- https://docs.scylladb.com/branch-5.1/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2021.1-to-2022.1-ubuntu
- https://docs.scylladb.com/stable/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2021.1-to-2022.1-debian.html
- https://docs.scylladb.com/stable/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2021.1-to-2022.1-image.html#

### Problem
In the "main" upgrade page for RHEL/CentOS the [applicable versions section](https://docs.scylladb.com/stable/upgrade/upgrade-enterprise/upgrade-guide-from-2021.1-to-2022.1/upgrade-guide-from-2021.1-to-2022.1-rpm.html#applicable-versions) includes a minimal version `2021.1.8` that the upgrade is supported from the version from which QA certified the upgrade path).

The minimal version is missing in all other upgrade docs.

###  Suggest a fix
Include the minimal version from which the upgrade is supported (QA certified).

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please merge this PR to master and backport to branch-5.1 and branch-5.2.
It must be backported as it affects the upgrade guides for previous versions.
