### ISSUE TITLE
Node operations may fail if prepare takes longer than heartbeat timeout 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#12969]
Affects operations like node decommission, bootstrap, removenode, replace. The algorithm installs a session on all nodes in the cluster in the prepare phase. The session is kept alive by a receiving periodic heartbeats from the coordinator. 

The coordinator first prepares the sessions and then starts the heartbeat updater. This is problematic. If it takes long to prepare some of the nodes, the other nodes may already decide to abort the session because they didn't receive any heartbeat. We should start the heartbeat updater before sending prepares.

As a result, the coordinator may proceed with the operation while some nodes already aborted it, and reverted to the previous token metadata. The coordinator will find out at the end, when it tries to finalize the operation with all the nodes by removing the sessions. 

In case of decommission, for example, the coordinator will find out after switching to STATUS=LEFT. There is no way to abort past that, and the operation will in fact be finalized. As a result, we completed decommissioning while some nodes were operating with the old topology, so were using the old replica set, without the pending node. As a result, some writes may end up on fewer replicas than they should. Some CL=1 writes could be lost, if they ended up only on the node which is being decommissioned.

**Comment by kbr-scylla** [comment]
I think the algorithm you're talking about - the `node_ops` thing - runs both in RBNO mode and outside?

**Comment by kbr-scylla** [comment]
If this was observed in production, I doubt it's related to RBNO in any way, because RBNO is disabled by default for all topology operations except replace. Did the customer enable RBNO for other operations?

**Comment by tgrabiec** [comment]
Observed in https://github.com/scylladb/scylladb/issues/11011

**Comment by bhalevy** [comment]
@tgrabiec and I discussed a solution for decommission at least that requires minimum changes.
I'll let him present it.

**Comment by asias** [comment]
We can start the watchdog only after the prepare verb is done and is about
return.

The prepare verb is supposed to be fast. But it may change in the future.

**Comment by bhalevy** [comment]
1. *should* prevent the abort on the sync node
2. will prevent decommission from proceeding to the gossip phase if any sync node aborted the node op during streaming / repair-based data sync.

**Comment by bhalevy** [comment]
I closed https://github.com/scylladb/scylladb/issues/12333 as dup of #11011 (and this issue)

**Comment by mykaul** [comment]
> I closed #12333 as dup of #11011 (and this issue)

The latter though is 'just' a test failure, while it is not a test issue at all - this one describes (as well as 12333) a more serious issue?

**Comment by bhalevy** [comment]
> > I closed #12333 as dup of #11011 (and this issue)
> 
> The latter though is 'just' a test failure, while it is not a test issue at all - this one describes (as well as 12333) a more serious issue?

#11011, #12333, and this issue all seem to have the same root cause, that is most clearly described here.

**Comment by asias** [comment]
> The straw man plan is:
> 
>     1. start the heartbeat updater early, before *_prepare.
> 
> 
>     * It ignores errors, so it doesn't matter it will report them
> 
>     * but that can be improved by keeping a set of nodes for heartbeat update and add the nodes to that set right before sending the *_prepare command

The heartbeat is very cheap. It is not worth the complexity.  

> 
>     2. Use a round of heartbeat update right before "committing" the operation on the coordinator, to make sure no node aborted it in that time.

I think we do not need this. The _watchdog_interval is 120s. The heartbeat update interval is 10s.  At most 10s after the "committing" time, the watchdog will be updated, long before the 120s would fire to abort.

**Comment by asias** [comment]
I sent the PR here: https://github.com/scylladb/scylladb/pull/12980.

@bhalevy I am sorry that you need to rebase https://github.com/scylladb/scylladb/pull/12799. Since #12980 is a bug fix, we need to have it before your refactor in #12799  for easier backport anyway.

**Comment by tgrabiec** [comment]
> I think we do not need this. The _watchdog_interval is 120s. The heartbeat update interval is 10s. At most 10s after the "committing" time, the watchdog will be updated, long before the 120s would fire to abort.

By "commit", we mean leave_ring(). We need to fail the bootstrap if any of the nodes aborted, and streaming succeeds.

**Comment by tgrabiec** [comment]
@kbr-scylla Without RBNO, bootstrap doesn't use node ops.

**Comment by tgrabiec** [comment]
@asias Why bootstrap doesn't use node ops if RBNO is disabled, but desommission always uses node ops?

**Comment by tgrabiec** [comment]
Bootstrap and replace are not vulnerable to the consistency issue caused by earlier aborts, only decommission and removenode.

**Comment by bhalevy** [comment]
> Bootstrap and replace are not vulnerable to the consistency issue caused by earlier aborts, only decommission and removenode.

@tgrabiec please elaborate.

Bootstrap, IIUC, isn't vulnerable to this issue since if rbno is disabled it doesn't use node operation, and if it is, then the bootstrapping node uses bootstrap_with_repair that compensate for any peer aborting the node op and using the previous token_metadata as a coordinator.

Why is replace with rbno disabled not vulnerable, is it because the replaced node must be down already?

Why is removenode vulnerable? The coordinator sends `removenode_sync_data` to the peers, so if any of them aborted, that fails, and consequently the coordinator will fail before `advertise_token_removed`

**Comment by tgrabiec** [comment]
> Bootstrap, IIUC, isn't vulnerable to this issue since if rbno is disabled it doesn't use node operation, and if it is, then the bootstrapping node uses bootstrap_with_repair that compensate for any peer aborting the node op and using the previous token_metadata as a coordinator.

Bootstrap with RBNO is not vulnerable because it sends bootstrap_done before jumping to NORMAL. So if any node aborted the node op, we will fail bootstrap before jumping to NORMAL and bootstrap will have to be repeated. Why do you think  bootstrap_with_repair() compensates for the safety problem?

Replace is not vulnerable for the same reason, we send replace_done before jumping to NORMAL.

removenode is not vulnerable to safety problem if prepare is delayed, but it is vulnerable to the safety problem if some node aborts after removenode_sync_data is initiated, because removenode_done is sent after advertise_token_removed() is called.

**Comment by bhalevy** [comment]
> Why do you think bootstrap_with_repair() compensates for the safety problem?

Sorry, you're right, repair-based bootstrap could miss a write that uses the previous token_metadata just as well as streaming would have.

**Comment by avikivity** [comment]
Waiting for backport branch to pass CI.

**Comment by DoronArazii** [comment]
Backported to 5.1
Removing label.

**Comment by tgrabiec** [comment]
@DoronArazii Which commit? I don't see ba919aa88a in branch-5.1

**Comment by DoronArazii** [comment]
> > Backported to 5.1
> 
> @DoronArazii Which commit? I don't see [ba919aa](https://github.com/scylladb/scylladb/commit/ba919aa88aa462b91520f73d3b7c2e775caaee87) in branch-5.1

https://github.com/scylladb/scylladb/commit/504f4ae397a7c66086e4b05ed637f835f7130853

**Comment by bhalevy** [comment]
@tgrabiec is right that we didn't backport the full fix that will prevent this issue,
only the additional config options that provide a workaround for it.
I think it's reasonable to remove the Backport Candidate given the workaround, but let's do that consciously.

**Comment by DoronArazii** [comment]
Okay, thanks for the heads-up.
Adding back the label - someone from @scylladb/scylla-maint shall take that decision.
