### ISSUE TITLE
doc: possibly outated information about CDC options

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#12964]
According to the [CDC Options](https://docs.scylladb.com/stable/cql/ddl.html#cdc-options) section on the Data Definitions page, the options are experimental:
![image](https://user-images.githubusercontent.com/37244380/220623619-fc83a246-7d2f-40f4-a2d0-a3d604c641d9.png)

I think they are no longer experimental because CDC went GA in version 4.3 and 2021.1.1. I'd like to remove the information about the options being experimental, but I need confirmation.
@tzach @kbr-scylla @elcallio Could you confirm?

**Comment by tzach** [comment]
True, CDC is not experimental for a long time.

Its hard to keep track for "experimental" mentioned in docs.
We need to use explict tags to mark experimental, so we can quick search for it, and fix it.

**Comment by annastuchlik** [comment]
Thanks!
Yes, let's use one of the tags we have to mark what is experimental.

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. 5.0 does not have this.
