### ISSUE TITLE
raft - remote_verb_error (connection is closed) when transferring snapshot

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#12972]
## Issue description

- [X] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In test, we create 1 node, then create 5000 tables and then add another nodes to cluster.
When adding first node, existing node logs show error (with some context):
```
Feb 21 16:30:46 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  1] raft_group_registry - Raft server id a1018c3f-739c-4fea-8d2b-94fdaf448142 cannot be translated to an IP address.
Feb 21 16:30:47 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] gossip - InetAddress 10.4.2.158 is now UP, status = UNKNOWN
Feb 21 16:30:47 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] raft_group_registry - marking Raft server a1018c3f-739c-4fea-8d2b-94fdaf448142 as alive for raft groups
Feb 21 16:30:47 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 21 16:30:47 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 21 16:30:47 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 21 16:30:47 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 21 16:30:48 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] mutation_partition - Memory usage of unpaged query exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit)
Feb 21 16:30:48 longevity-5000-tables-2023-1-db-node-d89f20f6-1 scylla[5704]:  [shard  0] raft - [0478b1fd-32de-4906-8071-bec9c81b1fe2] Transferring snapshot to a1018c3f-739c-4fea-8d2b-94fdaf448142 failed with: seastar::rpc::remote_verb_error (connection is closed)
```
In the meantime added node shows:
```
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] storage_service - Starting up server gossip
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard 10] compaction - [Compact system.local 180a6b30-b205-11ed-b3bb-03052efc5e67] Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-40-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-70-big-Data.db:level=0:origin=memtable]
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] gossip - failure_detector_loop: Started main loop
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] raft_group0 - setup_group0: joining group 0...
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] raft_group0 - server a1018c3f-739c-4fea-8d2b-94fdaf448142 found no local group 0. Discovering...
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] raft_group0 - server a1018c3f-739c-4fea-8d2b-94fdaf448142 found group 0 with group id a00c7430-b1ae-11ed-bbd9-7bf2770c6d3b, leader 0478b1fd-32de-4906-8071-bec9c81b1fe2
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] raft_group0 - Server a1018c3f-739c-4fea-8d2b-94fdaf448142 is starting group 0 with id a00c7430-b1ae-11ed-bbd9-7bf2770c6d3b
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard 10] compaction - [Compact system.local 180a6b30-b205-11ed-b3bb-03052efc5e67] Compacted 2 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/mc-100-big-Data.db:level=0]. 28kB to 15kB (~53% of original) in 8ms = 1MB/s. ~256 total partitions merged to 1.
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] raft_group0 - server a1018c3f-739c-4fea-8d2b-94fdaf448142 joined group 0 with group id a00c7430-b1ae-11ed-bbd9-7bf2770c6d3b
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] raft_group0 - setup_group0: successfully joined group 0.
2023-02-21T16:30:46+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] raft_group0 - setup_group0: ensuring that the cluster has fully upgraded to use Raft...
2023-02-21T16:30:48+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] storage_service - Set host_id=0478b1fd-32de-4906-8071-bec9c81b1fe2 to be owned by node=10.4.0.247
2023-02-21T16:30:48+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] gossip - InetAddress 10.4.0.247 is now UP, status = NORMAL
2023-02-21T16:30:48+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] migration_manager - Requesting schema pull from 10.4.0.247:0
2023-02-21T16:30:48+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] migration_manager - Pulling schema from 10.4.0.247:0
2023-02-21T16:30:48+00:00 longevity-5000-tables-2023-1-db-node-d89f20f6-2     !INFO | scylla[5812]:  [shard  0] migration_manager - Requesting schema pull from 10.4.0.247:0
```

## Impact

Unknown, later we can see tables being populated and cluster works.
But this causes SCT to raise an error and failing the test.
If `seastar::rpc::remote_verb_error (connection is closed)` is catched and raft is retrying, maybe we should hide it or rephrase to not scare the user.

## How frequently does it reproduce?

It happened for all added nodes (5) in this test.

## Installation details

Kernel Version: 5.15.0-1028-aws
Scylla version (or git commit hash): `2023.1.0~rc1-20230208.fe3cc281ec73` with build-id `ff20df9822b5b6397724a6ff6caadde419b383e6`

Cluster size: 1 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-5000-tables-2023-1-db-node-d89f20f6-6 (34.252.200.114 | 10.4.2.130) (shards: 30)
- longevity-5000-tables-2023-1-db-node-d89f20f6-5 (54.246.45.102 | 10.4.0.228) (shards: 30)
- longevity-5000-tables-2023-1-db-node-d89f20f6-4 (34.243.98.114 | 10.4.0.238) (shards: 30)
- longevity-5000-tables-2023-1-db-node-d89f20f6-3 (34.244.54.19 | 10.4.1.23) (shards: 30)
- longevity-5000-tables-2023-1-db-node-d89f20f6-2 (54.195.136.190 | 10.4.2.158) (shards: 30)
- longevity-5000-tables-2023-1-db-node-d89f20f6-1 (52.50.126.236 | 10.4.0.247) (shards: 30)

OS / Image: `ami-056165f482cc8e0d8` (aws: eu-west-1)

Test: `scale-5000-tables-test`
Test id: `d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda`
Test name: `enterprise-2023.1/scale/scale-5000-tables-test`
Test config file(s):

- [longevity-5000-tables.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d318637cf75441501644e71531a5cd1feaea0278/test-cases/scale/longevity-5000-tables.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda)
- Show all stored logs command: `$ hydra investigate show-logs d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda`

## Logs:
- **db-cluster-d89f20f6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/db-cluster-d89f20f6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/db-cluster-d89f20f6.tar.gz)
- **email_data-d89f20f6.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/email_data-d89f20f6.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/email_data-d89f20f6.json.tar.gz)
- **output-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/output-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/output-d89f20f6.log.tar.gz)
- **debug-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/debug-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/debug-d89f20f6.log.tar.gz)
- **events-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/events-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/events-d89f20f6.log.tar.gz)
- **sct-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/sct-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/sct-d89f20f6.log.tar.gz)
- **normal-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/normal-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/normal-d89f20f6.log.tar.gz)
- **argus-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/argus-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/argus-d89f20f6.log.tar.gz)
- **raw_events-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/raw_events-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/raw_events-d89f20f6.log.tar.gz)
- **critical-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/critical-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/critical-d89f20f6.log.tar.gz)
- **warning-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/warning-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/warning-d89f20f6.log.tar.gz)
- **summary-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/summary-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/summary-d89f20f6.log.tar.gz)
- **left_processes-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/left_processes-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/left_processes-d89f20f6.log.tar.gz)
- **error-d89f20f6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/error-d89f20f6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/error-d89f20f6.log.tar.gz)
- **monitor-set-d89f20f6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/monitor-set-d89f20f6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/monitor-set-d89f20f6.tar.gz)
- **loader-set-d89f20f6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/loader-set-d89f20f6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d89f20f6-1ec1-4bca-a7f2-1e8c1d0bacda/20230222_190116/loader-set-d89f20f6.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/scale/job/scale-5000-tables-test/2/)
</details>

**Comment by bhalevy** [comment]
There's https://github.com/scylladb/scylladb/pull/12799 but it's for the current node operation, unrelated to raft.

**Comment by kostja** [comment]
@gleb-cloudius raft snapshot transfer hits the unpaged query memory limit. Shall we increase the limit or it's time to switch to paged transfer?

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius raft snapshot transfer hits the unpaged query memory limit. Shall we increase the limit or it's time to switch to paged transfer?

We use existing schema_pull rpc call which is called without raft as well. Why don't we see it without raft? Something is fishy here. As of the limit for internal queries it should not be enforced.

**Comment by gleb-cloudius** [comment]
BTW this is a soft limit anyway. It should not cause any exception to be thrown. I am not sure the connection dropping is related. It may be the same issue with the gossiper aborting existing connections when a node becomes normal that caused RBNO to fail the tests.

**Comment by DoronArazii** [comment]
@kbr-scylla / @gleb-cloudius for you this is blocking 5.2 ?

**Comment by gleb-cloudius** [comment]
> @kbr-scylla / @gleb-cloudius for you this is blocking 5.2 ?

No.

**Comment by gleb-cloudius** [comment]
> BIt may be the same issue with the gossiper aborting existing connections when a node becomes normal that caused RBNO to fail the tests.

I confirmed that this is indeed the case.

**Comment by kostja** [comment]
@soyacz for now please mask the error in the log. I have no idea yet how to fix all of the issues which dropping rpc connections during the boot generates.

**Comment by kostja** [comment]
@mykaul please create 'rpc' label or similar. We have a lot of flakiness in testing from @xemul 's 7bdad47de2f5ba4a0da220aff13e4c510782ee3e we have gotten a lot of flaky tests, since connections can be dropped in the middle and - as in this case - the test itself is not flaky, but there is an unwanted error message in the log. I don't know how to elegantly fix it yet. Generally, I think dropping messaging service connections should be transparent to clients, currently it isn't.

**Comment by kbr-scylla** [comment]
The snapshot transfer error is harmless (we automatically recover). The 5.2 tests are already ignoring it (https://github.com/scylladb/scylla-cluster-tests/commit/4cdffb4315d0cf3edf5b6b127c3f47b770de9941). So no need to backport.
