### ISSUE TITLE
Decommission and removenode may lead to consistency issues if one of the nodes decides to abort during streaming

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#12989]
This is split from https://github.com/scylladb/scylladb/issues/12969 

The node ops algorithm installs a session on all nodes in the cluster in the prepare phase. The session is kept alive by a receiving periodic heartbeats from the coordinator. While the session is alive, the node works with the transitionary token metadata, which has pending replica set. When session timesout, the node reverts to the previous token metadata state.

The coordinator may proceed with the operation while some nodes already aborted it. He will find out at the end, when he tries to finalize the operation with all the nodes by removing the sessions. In case of decommission and removenode, the coordinator will find out after committing the change via the gossiper. There is no way to abort past that, and the operation will in fact be finalized. As a result, we may complete decommissioning while some nodes were operating with the old topology, so were using the old replica set, without the pending node. As a result, some writes may end up on fewer replicas than they should. Some CL=1 writes could be lost, if they ended up only on the node which is being decommissioned.

CL=QUORUM reads are also affected. They may commit the write to 2 out of 3 replicas, where one of them is the decommissioned node. So they will be committed only to 1 replica in the new topology, after decommission. Streaming may miss that write. After decommission is finalized, CL=QUORUM read may not see the write. Running repair would fix this.

This can happen if the node ops timeout is triggered on one of the nodes by asymmetric conditions, which don't cause failures on the coordinator node. We saw that in practice in https://github.com/scylladb/scylladb/issues/11011. Other examples of such asymmetric conditions are reactor stalls. The may not necessarily cause streaming failures, as the node failure detector operates independently from node ops heartbeats. 

To mitigate this, the node ops coordinator should close the session as completed immediately prior to making a change to the gossiper. If any session aborted, we will fail the operation. 

This is still not completely safe, because there is a time window between closing the sessions and making a change to the gossiper which makes the system vulnerable, but the window is small.

**Comment by avikivity** [comment]
Waiting for backport branch to pass CI.
