### ISSUE TITLE
Optionally use owned ranges in sstable reader to efficiently skip over ranges

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12998]
Currently, cleanup compaction uses a `flat_mutation_reader_v2::filter` to skip over disowned partitions. This is inefficient.
So is the view update generator (See 10f8f13b9004fd5f73cab6a527be2fad291c044f).

https://github.com/scylladb/scylladb/pull/12422 allows cleaning up sstables implicitly in any compaction type
and it will also allow filtering the sstable for read from any path.
However, the filtering performance better be improved for that.
If we push the owned_ranges down to the reader, it could use the index to efficiently fast forward to the next owned token once it hits a disowned token.

**Comment by mykaul** [comment]
Is this realistic for 5.3?

**Comment by bhalevy** [comment]
> Is this realistic for 5.3?

I doubt it.
First, we should merge https://github.com/scylladb/scylladb/pull/12422, and do this on top of it.

**Comment by raphaelsc** [comment]
This will improve cleanup efficiency considerably when scaling out.

**Comment by raphaelsc** [comment]
I am working on this.
