### ISSUE TITLE
Regression in test_lwt_update_prepared after evaluate column_condition as a single expression

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13012]
The test_lwt_update_prepared dtest started failing in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/195/testReport/cql_prepared_test/TestCQL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_lwt_update_prepared/

The failure triggered a secondary bug in the test, that is fixed by https://github.com/scylladb/scylla-dtest/pull/3052
Yet the root cause for the failure is 37c9c46101c3aa411cee839ee74ca932e000692e according to git bisect.

From dtest.log for the failure:
```
14:59:50,662 7       cql_prepared_test              DEBUG    cql_prepared_test.py:78   | test_lwt_update_prepared: Executing a single LWT Update test for type boolean
14:59:50,670 7       tools.data                     DEBUG    data.py             :485  | test_lwt_update_prepared: Preparing statement: UPDATE boolean_update_test_table SET value=:upd_v WHERE k=0 IF value=:v
14:59:50,670 7       cql_prepared_test              DEBUG    cql_prepared_test.py:133  | test_lwt_update_prepared: Asserting results from two consecutive identical CAS statements with the following query args: {'upd_v': True, 'v': None}
14:59:50,672 7       tools.data                     DEBUG    data.py             :485  | test_lwt_update_prepared: Preparing statement: UPDATE boolean_update_test_table SET value=:upd_v WHERE k=1 IF value in (:v)
14:59:50,672 7       cql_prepared_test              DEBUG    cql_prepared_test.py:133  | test_lwt_update_prepared: Asserting results from two consecutive identical CAS statements with the following query args: {'upd_v': True, 'v': None}
14:59:50,673 7       tools.data                     DEBUG    data.py             :485  | test_lwt_update_prepared: Preparing statement: UPDATE boolean_update_test_table SET value=:upd_v WHERE k=2 IF value in :v
14:59:50,674 7       cql_prepared_test              DEBUG    cql_prepared_test.py:133  | test_lwt_update_prepared: Asserting results from two consecutive identical CAS statements with the following query args: {'upd_v': True, 'v': (None,)}
14:59:50,719 7       errors                         ERROR    conftest.py         :203  | test_lwt_update_prepared: test failed: 
...
stmt = <PreparedStatement query="UPDATE boolean_update_test_table SET value=:upd_v WHERE k=2 IF value in :v", consistency=ONE>
expected = [True, None], parameters = {'upd_v': True, 'v': (None,)}, cl = 1
timeout = 60, num_attempts = 1

    @retrying(num_attempts=1, sleep_time=10)
    def assert_one_prepared(session, stmt, expected, parameters, cl=ConsistencyLevel.ONE, timeout=60, num_attempts=1):
        res = session.execute(stmt, parameters=parameters, timeout=timeout)
        list_res = _rows_to_list(res)
>       assert list_res == [expected], f'Expected {[expected]} from "{stmt}", but got {list_res}'
E       AssertionError: Expected [[True, None]] from "<PreparedStatement query="UPDATE boolean_update_test_table SET value=:upd_v WHERE k=2 IF value in :v", consistency=ONE>", but got [[False, None]]
```

So it looks like the tuple arg to the prepared statement is treated differently with 37c9c46101c3aa411cee839ee74ca932e000692e compared to how it was treated before.

Cc @avikivity @nyh

**Comment by nyh** [comment]
The dtest `cql_prepared_test.py / test_lwt_update_prepared` is a big test which tests a lot of things but from the above printout it seems to me that the problem was an LWT update looking like "UPDATE ... SET value=:upd_v WHERE k=2 IF value in :v" where v=(None,) used to succeed (i.e., the IF was true) before Avi's patch, and fail (IF was false) after it.

Avi, is it possible that although you remembered to make the LWT equality check succeed for null=null, you forgot to also fix the LWT "IN" check in the same way, so that "null IN (null)" is supposed to succeed?

We should have really had this check in a functional test in scylla.git, not a dtest, but it's good we at least had it in dtest.

**Comment by bhalevy** [comment]
> The dtest `cql_prepared_test.py / test_lwt_update_prepared` is a big test which tests a lot of things but from the above printout it seems to me that the problem was an LWT update looking like
> 
> ```
> UPDATE ... SET value=:upd_v WHERE k=2 IF value in :v
> ```
> 
> and `:v=(None,)`, used to succeed (i.e., the IF was true) before Avi's patch, and fail (IF was false) after it.
> 
> Avi, is it possible that although you remembered to make the LWT equality check succeed for null=null, you forgot to also fix the LWT "IN" check in the same way, so that "null IN (null)" is supposed to succeed?
> 
> We should have really had this check in a functional test in scylla.git, not a dtest, but it's good we at least had it in dtest.

ping @avikivity

**Comment by bhalevy** [comment]
> The dtest `cql_prepared_test.py / test_lwt_update_prepared` is a big test which tests a lot of things but from the above printout it seems to me that the problem was an LWT update looking like
> 
> ```
> UPDATE ... SET value=:upd_v WHERE k=2 IF value in :v
> ```
> 
> and `:v=(None,)`, used to succeed (i.e., the IF was true) before Avi's patch, and fail (IF was false) after it.
> 
> Avi, is it possible that although you remembered to make the LWT equality check succeed for null=null, you forgot to also fix the LWT "IN" check in the same way, so that "null IN (null)" is supposed to succeed?
> 
> We should have really had this check in a functional test in scylla.git, not a dtest, but it's good we at least had it in dtest.

ping @avikivity please look into this issue.

**Comment by kostja** [comment]
AFAIR the old behavior was compatible with Cassandra. The course of action is to check how the current Cassandra behaves and do the same.

**Comment by DoronArazii** [comment]
> AFAIR the old behavior was compatible with Cassandra. The course of action is to check how the current Cassandra behaves and do the same.

Thanks @kostja, can you please assign someone to do that?

**Comment by ptrsmrn** [comment]
Jan is on vacation this week, can it wait until he's back? (I am guessing it can).

**Comment by avikivity** [comment]
I'll look at it now.

**Comment by avikivity** [comment]
I see this:

```c++
    // If cell value is NULL, IN list must contain NULL or an empty set/list. Otherwise it must contain cell value.
    if (cell_value) {
        return std::any_of(in_values.begin(), in_values.end(), [this, cell_value] (const bytes_opt& value) {
            return value.has_value() && is_satisfied_by(expr::oper_t::EQ, *cell_value->type(), *type_of(_column), *cell_value, *value);
        });
    } else {
        return std::any_of(in_values.begin(), in_values.end(), [] (const bytes_opt& value) { return !value.has_value() || value->empty(); });
    }
```

Note the comment, and the else branch checking not only for NULL, but also empty. This was not carried over to evaluate().

The dtest carries the following comment:

```python
            # Skip the tests that test 'value IN :v` with `:v = [null]`.
            # There's a bug in the python driver which causes them to fail.
            # Because of the bug the driver sends a list of [empty] instead of [null],
            # and the LWT update isn't applied.
            # https://github.com/scylladb/python-driver/issues/201
            if init_val is not None:
```

So, the Python driver converts NULL to empty, and pre-patch code treats empty as NULL.

**Comment by avikivity** [comment]
https://github.com/scylladb/python-driver/issues/201 was recently closed. I expect that running the test with the updated driver will show the fix.

The question is, should we treat empty values that are list members in the right-hand side of an IN operator in an IF clause as NULL, for bug-compatibility with the Python driver, or require a Python driver update?

I'm perhaps biased but I think this is so esoteric we can require a Python driver update here.

**Comment by avikivity** [comment]
> empty values that are list members in the right-hand side of an IN operator in an IF clause

Challenge: say this three times fast

**Comment by bhalevy** [comment]
> [scylladb/python-driver#201](https://github.com/scylladb/python-driver/issues/201) was recently closed. I expect that running the test with the updated driver will show the fix.

Right on.  it's passing consistently since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/297/testReport/junit/cql_prepared_test/TestCQL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_lwt_update_prepared/

> The question is, should we treat empty values that are list members in the right-hand side of an IN operator in an IF clause as NULL, for bug-compatibility with the Python driver, or require a Python driver update?
> 
> I'm perhaps biased but I think this is so esoteric we can require a Python driver update here.

I concur.

**Comment by avikivity** [comment]
> 
> I concur.

Maybe you're biased too.

So, close as not planned?

**Comment by bhalevy** [comment]
@nyh what's your take on this?

**Comment by nyh** [comment]
I'm on vacation, will be back in a week. Sorry.

**Comment by mykaul** [comment]
What will users who use Cassandra driver do though (how will it even behave) ?

**Comment by mykaul** [comment]
ping @nyh - any idea what the next step is in this issue?

**Comment by nyh** [comment]
I'm closing the issue. I read the above discussion, and as far as I understand the test used to fail because the Python driver botched up the request (in a way that the newly modified Scylla cared about), and the test stopped failing when we fixed the Python driver.

It is sad the test now depends on Scylla's Python driver - which is something I avoid doing in test/cql-pytest - but it wouldn't be the first time in dtest so I think it's fine.

**Comment by nyh** [comment]
> What will users who use Cassandra driver do though (how will it even behave) ?

Users who use Cassandra's driver with open bugs (https://datastax-oss.atlassian.net/jira/software/c/projects/PYTHON/issues/PYTHON-1355) will experience those bugs, there's nothing we can do about it. As you can see I opened a bug upstream, pointed them to the solution, but they didn't take it.
If one of those users try to run dtest (why?), this specific test will fail.
