### ISSUE TITLE
[p0] S3: Pick up dangling objects on restart

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13024]
When loading sstables on boot (`distributed_loader::populate_keyspace`) the dangling objects should be removed.
The not-yet-sealed sstables were detected by the `TemporaryTOC` file presence, now there's an sstables_registry entry with `creating` status
The should-be-deleted sstables were detected via deletion log files, now there's an sstables_registry entry with `deleting` status

refs: #13016 
refs: #12523

**Comment by michoecho** [comment]
@xemul What does the `[p0]` in the issue name mean?

**Comment by xemul** [comment]
@bhalevy asked me to prioritize those, so p0 is highest-prio, p{N+1} is lower prio than p{N}

**Comment by michoecho** [comment]
> @bhalevy asked me to prioritize those, so p0 is highest-prio, p{N+1} is lower prio than p{N}

Oh, I see. So it's a symbol internal to the batch of S3-related issues.
I was slightly confused, because in Yaniv's system a "P0 issue" means an emergency (i.e. a production cluster on fire).
