### ISSUE TITLE
Configurables should have option to listen for start/stop of scylla

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylladb#13034]
Needed for configurables in enterprise. 
Configurables allow "loose" coupling of a subsystem into the scylla init process, augmenting config, adding to argument parsing etc.
Typically used to register extension iff required. 
However, such a system might need to also know when the server is reaching a "started" state, as well as when it shuts down. 
(See https://github.com/scylladb/scylla-enterprise/issues/2673)

**Comment by eliransin** [comment]
@elcallio please try to implement this missing interface.

**Comment by elcallio** [comment]
?  #13035 (already merged, waiting for backport to enterprise).

**Comment by eliransin** [comment]
I got confused because the issue didn't close automatically due to the commit being pushed instead of the PR being merged.
Issue is resolved by https://github.com/scylladb/scylladb/commit/dba45f3dc8aa0790711627f66f68f5531dc8d10e which is already merged.

**Comment by DoronArazii** [comment]
@avikivity ping

**Comment by mykaul** [comment]
Re-ping @avikivity

**Comment by avikivity** [comment]
It's now merged into enterprise. What other versions does it need to go into?

**Comment by elcallio** [comment]
All enterprise versions that have a664ac7 applied should receive this, and the actual replicated provider fix (once rebased etc).

**Comment by avikivity** [comment]
I'll need some enterprise issue to refer to (and this discussion should have happened there)

**Comment by elcallio** [comment]
https://github.com/scylladb/scylla-enterprise/issues/2673

**Comment by avikivity** [comment]
No open source branches need this, removing "Backport candidate" label.
