### ISSUE TITLE
Configurables should have optional access to service objects defined by init sequence

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylladb#13036]
Needed for configurables in enterprise.
Configurables allow "loose" coupling of a subsystem into the scylla init process, augmenting config, adding to argument parsing etc.
Typically used to register extension iff required.
However, such a system might need to also know/access service objects created by init sequence, esp. to avoid global variables. 
(See https://github.com/scylladb/scylla-enterprise/issues/2718)

**Comment by DoronArazii** [comment]
@elcallio where is it standing?
