### ISSUE TITLE
reader_concurrency_semaphore::clear_inactive_reads() doesn't properly evict inactive reads

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#13048]
This method is called from `stop()` and is intended to kick out all inactive reads while stopping the semaphore. The method however only does a half-job: it destroys the inactive reader entries but it doesn't sets the permit to evicted status.
If this inactive read is an underlying reader managed by an evictable reader one, this will cause the evictable reader to recreate the evicted reader and then trigger an assert in `reader_permit::impl::on_register_as_inactive()` the next time it registers it as inactive, due to the permit still being in inactive state.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
