### ISSUE TITLE
Error applying view update to a stopped node: !ERR | exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#13052]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

Stopping Scylla on node1
Write c-s data to a new table
Create a materialized-view for the new table
==>
Nodes start reporting "Error applying view update" for node-1 (which is down).

log:
```
< t:2023-03-01 15:50:15,283 f:nemesis.py      l:4089 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.AddRemoveMvNemesis: Start disruption at `2023-03-01 15:50:15.283289`
< t:2023-03-01 15:50:15,283 f:nemesis.py      l:1082 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.AddRemoveMvNemesis: Set current_disruption -> AddRemoveMv Node add-remove-mv-add-remo-db-node-9e785e68-2 [13.49.223.67 | 10.0.1.164] (seed: True)
< t:2023-03-01 15:50:16,379 f:nemesis.py      l:2867 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.AddRemoveMvNemesis: Stopping Scylla on node1
< t:2023-03-01 15:50:17,135 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2023-03-01T15:50:17+00:00 add-remove-mv-add-remo-db-node-9e785e68-1     !INFO | systemd[1]: Stopping Scylla Server...
< t:2023-03-01 15:55:30,494 f:tester.py       l:2270 c:LongevityTest        p:DEBUG > MV create statement: CREATE MATERIALIZED VIEW new_mv_keyspace.standard1_view AS SELECT "C0", key FROM new_mv_keyspace.standard1 WHERE "C0" is not null and key is not null PRIMARY KEY ("C0", key) WITH comment='test MV'
< t:2023-03-01 15:55:30,495 f:common.py       l:1642 c:utils                p:DEBUG > Executing CQL 'CREATE MATERIALIZED VIEW new_mv_keyspace.standard1_view AS SELECT "C0", key FROM new_mv_keyspace.standard1 WHERE "C0" is not null and key is not null PRIMARY KEY ("C0", key) WITH comment='test MV'' ...
< t:2023-03-01 15:55:30,495 f:common.py       l:1650 c:utils                p:DEBUG > Executing CQL 'CREATE MATERIALIZED VIEW new_mv_keyspace.standard1_view AS SELECT "C0", key FROM new_mv_keyspace.standard1 WHERE "C0" is not null and key is not null PRIMARY KEY ("C0", key) WITH comment='test MV'' ...
< t:2023-03-01 15:55:30,858 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2023-03-01T15:55:30+00:00 add-remove-mv-add-remo-db-node-9e785e68-6      !ERR | scylla[6218]:  [shard  0] view - Error applying view update to 10.0.1.135 (view: new_mv_keyspace.standard1_view, base token: -9142289485168477712, view token: -6214617924892048640): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
< t:2023-03-01 15:55:30,907 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-03-01T15:55:30+00:00 add-remove-mv-add-remo-db-node-9e785e68-6      !ERR | scylla[6218]:  [shard  0] view - Error applying view update to 10.0.1.135 (view: new_mv_keyspace.standard1_view, base token: -9142289485168477712, view token: -6214617924892048640): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
< t:2023-03-01 15:55:30,956 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2023-03-01T15:55:30+00:00 add-remove-mv-add-remo-db-node-9e785e68-2      !ERR | scylla[5712]:  [shard  0] view - Error applying view update to 10.0.1.135 (view: new_mv_keyspace.standard1_view, base token: -9205070661563626499, view token: -2238675517991323973): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
< t:2023-03-01 15:55:30,981 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2023-03-01T15:55:30+00:00 add-remove-mv-add-remo-db-node-9e785e68-5      !ERR | scylla[6066]:  [shard  0] view - Error applying view update to 10.0.1.135 (view: new_mv_keyspace.standard1_view, base token: -9218618722159992404, view token: 2114256278035108657): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
```
Perhaps the severity/error level of this message better be 'warning'.
## Impact
No impact except for log messages burst.

## How frequently does it reproduce?
all the time.
```
$ grep -c 'new_mv_keyspace.standard1_view,' events_log/error.log 
1400
```
*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1028-aws
Scylla version (or git commit hash): `5.2.0~rc1-20230207.8ff4717fd010` with build-id `78fbb2c25e9244a62f57988313388a0260084528`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- add-remove-mv-add-remo-db-node-9e785e68-6 (13.53.122.131 | 10.0.1.189) (shards: 14)
- add-remove-mv-add-remo-db-node-9e785e68-5 (13.53.47.141 | 10.0.2.221) (shards: 14)
- add-remove-mv-add-remo-db-node-9e785e68-4 (16.171.54.8 | 10.0.2.223) (shards: 14)
- add-remove-mv-add-remo-db-node-9e785e68-3 (13.48.84.197 | 10.0.2.213) (shards: 14)
- add-remove-mv-add-remo-db-node-9e785e68-2 (13.49.223.67 | 10.0.1.164) (shards: 14)
- add-remove-mv-add-remo-db-node-9e785e68-1 (13.51.237.227 | 10.0.1.135) (shards: 14)

OS / Image: `ami-0065ee69f8c867af0` (aws: eu-north-1)

Test: `longevity-100gb-4h-test-restart-then-repair`
Test id: `9e785e68-bfbc-4838-a6ac-a8b6cd5ae68d`
Test name: `scylla-staging/yarongilor/longevity-100gb-4h-test-restart-then-repair`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9a024d6835156d4e907f9f770813b561bd88ef1d/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9e785e68-bfbc-4838-a6ac-a8b6cd5ae68d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9e785e68-bfbc-4838-a6ac-a8b6cd5ae68d)
- Show all stored logs command: `$ hydra investigate show-logs 9e785e68-bfbc-4838-a6ac-a8b6cd5ae68d`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-100gb-4h-test-restart-then-repair/10/)
</details>

**Comment by yarongilor** [comment]
There might be a chance this issue is similar to https://github.com/scylladb/scylladb/issues/6666

**Comment by nyh** [comment]
Indeed, it is not surprising that if the other node is down, the send to it should fail. This is a fairly common occurrence (and handled by saving hints), that definitely shouldn't be logged as error, although it does indicate a type of error (a node being down), I don't think the user needs to see it printed hundreds of times.

Note that this error logging doesn't **only** happen if the remote node is down. On the other hand, some other reasons are even more benign - see https://github.com/scylladb/scylladb/issues/12977 where we go this error message when an index was removed, and also the error message was scary and non-useful.

**Comment by yarongilor** [comment]
reproduced during a nemesis of rolling-restart-cluster:
```
< t:2023-03-15 04:26:23,910 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2023-03-15T04:26:22+00:00 longevity-mv-si-4d-2023-1-db-node-957eafaf-2      !ERR | scylla[859]:  [shard  0] view - Error applying view update to 10.4.2.161 (view: sec_index.users_last_access_ind_index, base token: -6746185454449037394, view token: -8633496417911784468): exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
< t:2023-03-15 04:26:23,911 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2023-03-15T04:26:22+00:00 longevity-mv-si-4d-2023-1-db-node-957eafaf-2  !WARNING | scylla[859]:  [shard  0] view - Error executing build step for base sec_index.users: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
```

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`




Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-2023-1-db-node-957eafaf-9 (54.73.115.231 | 10.4.2.97) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-8 (54.217.32.143 | 10.4.1.4) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-7 (54.194.14.74 | 10.4.1.162) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-6 (54.216.103.109 | 10.4.0.152) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-5 (3.249.247.111 | 10.4.0.25) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-4 (34.245.135.126 | 10.4.3.199) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-3 (3.253.32.101 | 10.4.2.57) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-24 (54.76.234.176 | 10.4.0.34) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-23 (18.202.246.98 | 10.4.0.191) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-22 (34.255.209.144 | 10.4.0.143) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-21 (34.248.45.117 | 10.4.2.192) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-20 (34.245.92.176 | 10.4.1.139) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-2 (54.170.155.6 | 10.4.0.126) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-19 (52.30.101.242 | 10.4.3.94) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-18 (3.250.225.181 | 10.4.1.167) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-17 (3.250.192.34 | 10.4.2.16) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-16 (34.253.139.52 | 10.4.0.191) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-15 (54.77.109.71 | 10.4.0.14) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-14 (34.241.180.114 | 10.4.2.31) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-13 (34.240.249.139 | 10.4.0.238) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-12 (34.240.172.148 | 10.4.1.251) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-11 (34.245.56.205 | 10.4.1.249) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-10 (3.253.4.168 | 10.4.2.109) (shards: 14)
- longevity-mv-si-4d-2023-1-db-node-957eafaf-1 (34.242.222.43 | 10.4.2.161) (shards: 14)


OS / Image: `ami-0336a5a646b08dc25` (aws: eu-west-1)

Test: `ics-longevity-mv-si-4days-test`
Test id: `957eafaf-0d72-4435-998a-e0401bffd511`
Test name: `enterprise-2023.1/SCT_Enterprise_Features/ICS/ics-longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4ec1600f015410814cdbe6d94ce29af866d6ccda/test-cases/longevity/longevity-mv-si-4days.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 957eafaf-0d72-4435-998a-e0401bffd511`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=957eafaf-0d72-4435-998a-e0401bffd511)
- Show all stored logs command: `$ hydra investigate show-logs 957eafaf-0d72-4435-998a-e0401bffd511`


## Logs:
- **db-cluster-957eafaf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/db-cluster-957eafaf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/db-cluster-957eafaf.tar.gz)
- **email_data-957eafaf.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/email_data-957eafaf.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/email_data-957eafaf.json.tar.gz)
- **output-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/output-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/output-957eafaf.log.tar.gz)
- **debug-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/debug-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/debug-957eafaf.log.tar.gz)
- **events-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/events-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/events-957eafaf.log.tar.gz)
- **sct-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/sct-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/sct-957eafaf.log.tar.gz)
- **normal-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/normal-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/normal-957eafaf.log.tar.gz)
- **argus-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/argus-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/argus-957eafaf.log.tar.gz)
- **raw_events-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/raw_events-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/raw_events-957eafaf.log.tar.gz)
- **critical-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/critical-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/critical-957eafaf.log.tar.gz)
- **warning-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/warning-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/warning-957eafaf.log.tar.gz)
- **summary-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/summary-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/summary-957eafaf.log.tar.gz)
- **left_processes-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/left_processes-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/left_processes-957eafaf.log.tar.gz)
- **error-957eafaf.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/error-957eafaf.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/error-957eafaf.log.tar.gz)
- **monitor-set-957eafaf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/monitor-set-957eafaf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/monitor-set-957eafaf.tar.gz)
- **loader-set-957eafaf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/loader-set-957eafaf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/957eafaf-0d72-4435-998a-e0401bffd511/20230319_045422/loader-set-957eafaf.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-mv-si-4days-test/2/)
</details>
