### ISSUE TITLE
expr::search_and_replace doesn't preserve the order field of binary_operator

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#13055]
There is a bug in `expr::search_and_replace`. It doesn't preserve the `order` field of binary_operator.

https://github.com/scylladb/scylladb/blob/d85af3dca4c1113053d4b4da5b31c49eb8f471a7/cql3/expr/expression.cc#L1478-L1480

`order` field is used to mark relations created using SCYLLA_CLUSTERING_BOUND.
SCYLLA_CLUSTERING_BOUND is a CQL feature used for internal queries inside Scylla.
It means that we should handle the restriction as a raw clustering bound, not as an expression in the CQL language.
    
Losing the SCYLLA_CLUSTERING_BOUND marker could cause issues because the database could end up selecting the wrong clustering ranges.

Luckily it doesn't look like any real code path hits this bug, we would've probably noticed it by now.
Still it should be fixed and backported to older versions

**Comment by cvybhu** [comment]
It doesn't look like this causes any actual issues, but it would be good to backport this, just for the piece of mind.
It has the potential to fetch wrong data.

Looking at the git history, the bug was introduced together with `replace_column_def` in d33053b841a0faa2313389b2aeeabfe76c54890f.
Later `replace_column_def` evolved into `search_and_replace`, but the bug persisted.
That was over 2.5 years ago, so all the recent versions are affected.

AFAIU after closing a PR with the fix for `master`, the issue will get the `backport candidate` label and then I can start the backports.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.
