### ISSUE TITLE
Add metrics for CQL request and response sizes

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#13061]
*Installation details*
HEAD: b6e427551193fd9a06d12e2c1de832e51a26ac00

*Description*
We need metrics that would allow us reasoning about sizes of requests and the amount of data that is returned.

We can start with averages but histograms would definitely make sense eventually.

**Comment by DoronArazii** [comment]
@mykaul / @vladzcloudius can we close it? or it requires more work?

**Comment by vladzcloudius** [comment]
> @mykaul / @vladzcloudius can we close it? or it requires more work?

We should close it only after histograms are added (mentioned in the opening message).

**Comment by mykaul** [comment]
> > @mykaul / @vladzcloudius can we close it? or it requires more work?
> 
> We should close it only after histograms are added (mentioned in the opening message).

Thanks @vladzcloudius - will you be able to complete this work (we hope to branch out 5.3 very soon). Alternatively, we may prefer to open a separate GH issue to track that activity?

**Comment by mykaul** [comment]
> > > > @mykaul / @vladzcloudius can we close it? or it requires more work?
> > > 
> > > 
> > > We should close it only after histograms are added (mentioned in the opening message).
> > 
> > 
> > Thanks @vladzcloudius - will you be able to complete this work (we hope to branch out 5.3 very soon). Alternatively, we may prefer to open a separate GH issue to track that activity?
> 
> No. I'm not planning to work on that any time soon.

Thanks - then I'm in favor of opening a separate item to track the histogram request.

**Comment by DoronArazii** [comment]
> > @mykaul / @vladzcloudius can we close it? or it requires more work?
> 
> We should close it only after histograms are added (mentioned in the opening message).

Closing as completed.
