### ISSUE TITLE
undefined behavior in table::generate_and_propagate_view_updates()

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#13093]
When evaluation order (which is undefined behavior) is right-to-left, we end up with use-after-move

make_flat_mutation_reader_from_mutations_v2(m.schema(), std::move(permit), std::move(m))

This use-after-move may affect memory accounting for tracking only permit for view updates,

or potentially cause Scylla to crash due to use-after-move on schema.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.
