### ISSUE TITLE
doc: fix the information that BYPASS CACHE is Enterprise-only

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#13106]
https://docs.scylladb.com/stable/operating-scylla/procedures/tips/benchmark-tips.html#bypass-cache
According to the above page, BYPASS CACHE is Enteprise-only. In fact, it's OSS since version 3.1.

- Fix the information.
- Add the link to the BYPASS CACHE section https://docs.scylladb.com/stable/cql/dml.html#bypass-cache

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. 5.0 doesn't have this.
