### ISSUE TITLE
test_add_node_during_index_build enhancement: off-strategy compaction starts before building view finished

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#13118]
This issue is originated and discussed in: https://github.com/scylladb/scylla-dtest/pull/3042#issuecomment-1445354580

When a down node is taken back up, the off-strategy for a tested user-table started 13 seconds before build-view finished.
error log was:
```
        view_build_finish_time = wait_for_view(cluster=self.cluster, session=session, ks=keyspace_name,
                                               view=get_index_view_name(index_name), raise_exception=True)
        bootstrap_node_build_finish_time = view_build_finish_time[uuid.UUID(bootstrap_node.hostid())]
        matches = bootstrap_node.watch_log_for(f"Starting off-strategy compaction for {keyspace_name}.{table_name}",
                                               timeout=300, verbose=True)
        offstrategy_start_date = datetime.datetime.strptime(' '.join(matches[0].split()[1:3])[2:].split(',')[0],
                                                            '%y-%m-%d %H:%M:%S')
        index_is_built(self.cluster, session, ks_name=keyspace_name, table_name=table_name, index_name=index_name,
                       wait_for_view=False)
    
>       assert offstrategy_start_date >= bootstrap_node_build_finish_time, \
            "Off-strategy compaction started before build view finished"
E       AssertionError: Off-strategy compaction started before build view finished
E       assert datetime.datetime(2023, 2, 22, 16, 26, 16) >= datetime.datetime(2023, 2, 22, 16, 26, 29, 3513)
```

Scylla version 5.3.0~dev-0.20230218.941407b905a6 
(Tested on unstable/master:2023-02-18T13:56:49Z)
Full Dtest log:
[dtest.log](https://github.com/scylladb/scylladb/files/10930475/dtest.log)

**Comment by mykaul** [comment]
@bhalevy - please prioritize (or de-prioritize) - needs triaging.

**Comment by bhalevy** [comment]
@raphaelsc isn't that by design?

**Comment by raphaelsc** [comment]
> @raphaelsc isn't that by design?

Off-strategy can only start on sstables that have completed view building. So probably what QA is seeing is off-strategy starting after each view building batch completes.

The code is very explicit about that:
```
        // Filter out sstables that require view building, to avoid a race between off-strategy
        // and view building. Refs: #11882
        const auto old_sstables = boost::copy_range<std::vector<sstables::shared_sstable>>(*maintenance_sstables.all()
                | boost::adaptors::filtered([] (const sstables::shared_sstable& sst) {
            return !sst->requires_view_building();
        }));
```

**Comment by raphaelsc** [comment]
Perhaps we should batch off-strategy, by deferring it until no view building is ongoing. What do you think?

**Comment by bhalevy** [comment]
> > Perhaps we should batch off-strategy, by deferring it until no view building is ongoing. What do you think?
> 
> It could work if we treat those sstables that are no longer staging but still in the maintenance set as ineligible for regular compaction, then deferring off-strategy compaction until we're done updating the views for all of them makes sense.

Actually, I think regular compaction get the candidates only from the main sstable set, so this might be even simpler than I thought.

**Comment by yarongilor** [comment]
@raphaelsc , @bhalevy , please clarify the state of this issue. Is the new enhancement reproduction of the problem is valid?

It is curently reproduced in the PR https://github.com/scylladb/scylla-dtest/pull/3042 of.
After rebasing and adding a small update: test keeps failing, where the off-strategy of a specific table-view starts 2 seconds before the view-build for this table is done:
```
secondary_indexes_test.py::TestSecondaryIndexes::test_add_node_during_index_build ------------------------------ live log logreport ------------------------------
16:16:08,123 errors          ERROR conftest.py    :208  | test failed: 
self = <secondary_indexes_test.TestSecondaryIndexes object at 0x7f3ed66c8850>

    def test_add_node_during_index_build(self):
        """
        Decommission one node during index building and read data by index
        """
>       self._node_action_during_index_build(node_action='add', nodes=3, rf=3, num_rows=100000)

secondary_indexes_test.py:1495: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <secondary_indexes_test.TestSecondaryIndexes object at 0x7f3ed66c8850>
node_action = 'add', nodes = 3, rf = 3, num_rows = 100000

    def _node_action_during_index_build(self, node_action, nodes, rf, num_rows):
        keyspace_name = 'ks'
        table_name = 'cf'
        index_name = 'b_index'
        index_column = 'b'
        view_name = get_index_view_name(index_name)
    
        session = self.prepare(nodes=nodes, rf=rf, keyspace_name=keyspace_name, session_node=3)
        node2 = self.cluster.nodelist()[1]
        node2_ip = list(node2.network_interfaces['binary'])[0].replace('.', r'\.')
    
        create_cf(session, table_name, key_type='int', columns={'b': 'int'},
                  compaction={'class': self.compaction_strategy})
    
        statement = session.prepare("INSERT INTO {}.{} (key, b) VALUES (?, ?)".format(keyspace_name, table_name))
        statement.consistency_level = ConsistencyLevel.QUORUM
    
        execute_concurrent_with_args(session, statement,
                                     map(lambda k: [k] + [k + num_rows], [k for k in range(0, num_rows)]))
        self.cluster.flush()
    
        # Create index and wait while the build is starting
        create_index(session, table_name, index_column, index_name, compaction=self.compaction_strategy)
        wait_for_view_build_start(session, ks=keyspace_name, view=view_name)
    
        exclude_errors = [rf'Can\'t send migration request: node {node2_ip} is down',
                          rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to {node2_ip}.*: exceptions::unavailable_exception \(Cannot achieve consistency level for cl ONE. Requires 1, alive 0\)',
                          rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to {node2_ip}.*: exceptions::mutation_write_timeout_exception \(Operation timed out for {keyspace_name}.{index_name}_index - received only 0 responses from 1 CL=ONE.\)',
                          rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to .*: exceptions::mutation_write_failure_exception \(Operation failed for {keyspace_name}.{index_name}_index - received 0 responses and 1 failures from 1 CL=ONE.\)',
                          rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to .*: exceptions::mutation_write_failure_exception \(abort requested\)',
                          ]
        self.ignore_log_patterns += exclude_errors
    
        # Perform action on second node
        self.node_action_with_delay(node_action, node2)
    
        # Index will not finish building, because view building underneath is paused until updates can be sent.
        if node_action == 'add':
            assert True
    
        if node_action in ['remove', 'decommission']:
            logger.debug('Add new node')
            session = self.add_new_node(node_index=nodes + 1)
            session.execute('USE {}'.format(keyspace_name))
        elif node_action == 'stop':
            logger.debug('Start node {}'.format(node2.name))
            node2.start(wait_for_binary_proto=True)
            session = self.patient_cql_connection(node2)
    
        bootstrap_node = node2 if node_action == 'stop' else self.cluster.nodelist()[-1]
    
        view_build_finish_time = wait_for_view(cluster=self.cluster, session=session, ks=keyspace_name,
                                               view=view_name, raise_exception=True)
        bootstrap_node_build_finish_time = view_build_finish_time[uuid.UUID(bootstrap_node.hostid())]
        matches = bootstrap_node.watch_log_for(f"Starting off-strategy compaction for {keyspace_name}.{view_name}",
                                               timeout=300, verbose=True)
        offstrategy_start_date = datetime.datetime.strptime(' '.join(matches[0].split()[1:3])[2:].split(',')[0],
                                                            '%y-%m-%d %H:%M:%S')
        index_is_built(self.cluster, session, ks_name=keyspace_name, table_name=table_name, index_name=index_name,
                       wait_view_built=False)
    
>       assert offstrategy_start_date >= bootstrap_node_build_finish_time, \
            "Off-strategy compaction started before build view finished"
E       AssertionError: Off-strategy compaction started before build view finished
E       assert datetime.datetime(2023, 8, 21, 16, 16, 1) >= datetime.datetime(2023, 8, 21, 16, 16, 3, 68327)
```

Cc: @mykaul , @roydahan

**Comment by yarongilor** [comment]
> @raphaelsc , @bhalevy , please clarify the state of this issue. Is the new enhancement reproduction of the problem is valid?
> 
> It is curently reproduced in the PR [scylladb/scylla-dtest#3042](https://github.com/scylladb/scylla-dtest/pull/3042) of. After rebasing and adding a small update: test keeps failing, where the off-strategy of a specific table-view starts 2 seconds before the view-build for this table is done:
> 
> ```
> secondary_indexes_test.py::TestSecondaryIndexes::test_add_node_during_index_build ------------------------------ live log logreport ------------------------------
> 16:16:08,123 errors          ERROR conftest.py    :208  | test failed: 
> self = <secondary_indexes_test.TestSecondaryIndexes object at 0x7f3ed66c8850>
> 
>     def test_add_node_during_index_build(self):
>         """
>         Decommission one node during index building and read data by index
>         """
> >       self._node_action_during_index_build(node_action='add', nodes=3, rf=3, num_rows=100000)
> 
> secondary_indexes_test.py:1495: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <secondary_indexes_test.TestSecondaryIndexes object at 0x7f3ed66c8850>
> node_action = 'add', nodes = 3, rf = 3, num_rows = 100000
> 
>     def _node_action_during_index_build(self, node_action, nodes, rf, num_rows):
>         keyspace_name = 'ks'
>         table_name = 'cf'
>         index_name = 'b_index'
>         index_column = 'b'
>         view_name = get_index_view_name(index_name)
>     
>         session = self.prepare(nodes=nodes, rf=rf, keyspace_name=keyspace_name, session_node=3)
>         node2 = self.cluster.nodelist()[1]
>         node2_ip = list(node2.network_interfaces['binary'])[0].replace('.', r'\.')
>     
>         create_cf(session, table_name, key_type='int', columns={'b': 'int'},
>                   compaction={'class': self.compaction_strategy})
>     
>         statement = session.prepare("INSERT INTO {}.{} (key, b) VALUES (?, ?)".format(keyspace_name, table_name))
>         statement.consistency_level = ConsistencyLevel.QUORUM
>     
>         execute_concurrent_with_args(session, statement,
>                                      map(lambda k: [k] + [k + num_rows], [k for k in range(0, num_rows)]))
>         self.cluster.flush()
>     
>         # Create index and wait while the build is starting
>         create_index(session, table_name, index_column, index_name, compaction=self.compaction_strategy)
>         wait_for_view_build_start(session, ks=keyspace_name, view=view_name)
>     
>         exclude_errors = [rf'Can\'t send migration request: node {node2_ip} is down',
>                           rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to {node2_ip}.*: exceptions::unavailable_exception \(Cannot achieve consistency level for cl ONE. Requires 1, alive 0\)',
>                           rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to {node2_ip}.*: exceptions::mutation_write_timeout_exception \(Operation timed out for {keyspace_name}.{index_name}_index - received only 0 responses from 1 CL=ONE.\)',
>                           rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to .*: exceptions::mutation_write_failure_exception \(Operation failed for {keyspace_name}.{index_name}_index - received 0 responses and 1 failures from 1 CL=ONE.\)',
>                           rf'(\(rate limiting dropped [0-9]+ similar messages\) )?Error applying view update to .*: exceptions::mutation_write_failure_exception \(abort requested\)',
>                           ]
>         self.ignore_log_patterns += exclude_errors
>     
>         # Perform action on second node
>         self.node_action_with_delay(node_action, node2)
>     
>         # Index will not finish building, because view building underneath is paused until updates can be sent.
>         if node_action == 'add':
>             assert True
>     
>         if node_action in ['remove', 'decommission']:
>             logger.debug('Add new node')
>             session = self.add_new_node(node_index=nodes + 1)
>             session.execute('USE {}'.format(keyspace_name))
>         elif node_action == 'stop':
>             logger.debug('Start node {}'.format(node2.name))
>             node2.start(wait_for_binary_proto=True)
>             session = self.patient_cql_connection(node2)
>     
>         bootstrap_node = node2 if node_action == 'stop' else self.cluster.nodelist()[-1]
>     
>         view_build_finish_time = wait_for_view(cluster=self.cluster, session=session, ks=keyspace_name,
>                                                view=view_name, raise_exception=True)
>         bootstrap_node_build_finish_time = view_build_finish_time[uuid.UUID(bootstrap_node.hostid())]
>         matches = bootstrap_node.watch_log_for(f"Starting off-strategy compaction for {keyspace_name}.{view_name}",
>                                                timeout=300, verbose=True)
>         offstrategy_start_date = datetime.datetime.strptime(' '.join(matches[0].split()[1:3])[2:].split(',')[0],
>                                                             '%y-%m-%d %H:%M:%S')
>         index_is_built(self.cluster, session, ks_name=keyspace_name, table_name=table_name, index_name=index_name,
>                        wait_view_built=False)
>     
> >       assert offstrategy_start_date >= bootstrap_node_build_finish_time, \
>             "Off-strategy compaction started before build view finished"
> E       AssertionError: Off-strategy compaction started before build view finished
> E       assert datetime.datetime(2023, 8, 21, 16, 16, 1) >= datetime.datetime(2023, 8, 21, 16, 16, 3, 68327)
> ```
> 
> Cc: @mykaul , @roydahan

ping @bhalevy , @raphaelsc

**Comment by raphaelsc** [comment]
https://github.com/scylladb/scylla-dtest/pull/3042#issuecomment-1708572756

**Comment by yarongilor** [comment]
update following a meeting with Raphael.
It might be better not to test implementation validations like log messages since they may frequently be modified.
It would be too much of an overhead to maintain such a Dtest.
Alternatively we can try testing the "output", meaning the expected result of node bootstrap operation and its data consistency for the materialized-view.

**Comment by mykaul** [comment]
> It might be better not to test implementation validations like log messages since they may frequently be modified.

I hope not frequently, as in the future we'll use them for alerts as well (not just metrics).
So - what are we going to do here?
