### ISSUE TITLE
docs: breadcrumbs links does not work

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13117]
### Problem

breadcrumbs should act as link for each.
Currently (not sure since when), only the first two are links:

![image](https://user-images.githubusercontent.com/170200/223961491-9a40ffa2-2448-4c68-abbd-cfeb3eb90f21.png)

**Comment by tzach** [comment]
@dgarcia360 FYI

**Comment by dgarcia360** [comment]
I'm taking this issue
