### ISSUE TITLE
doc: document Ubuntu 22 as the recommended OS for Enterprise and Open Source

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#13138]
The following pages need to be updated:
https://docs.scylladb.com/stable/getting-started/os-support.html
https://enterprise.docs.scylladb.com/stable/getting-started/os-support.html

The information comes from @tomer-sandler and was confirmed by @mykaul .

This is a security-related issue.

**Comment by annastuchlik** [comment]
@yaronkaikov 
Hi Yaron, 
Please help me determine what is the recommended OS for ScyllaDB Enterprise and Open Source.
- According to the current documentation, it's Ubuntu 20.04.
- According to @mykaul (as forwarded by @tomer-sandler) it should be 22.04.

The recommended OS should be the OS that is used to build the image, so:
- Which Ubuntu version is used to build the images (OSS and Enerprise)?
- If it's 22.04, when did the change from 20.04 take place?

**Comment by yaronkaikov** [comment]
> @yaronkaikov Hi Yaron, Please help me determine what is the recommended OS for ScyllaDB Enterprise and Open Source.
> 
> * According to the current documentation, it's Ubuntu 20.04.
> * According to @mykaul (as forwarded by @tomer-sandler) it should be 22.04.
> 
> The recommended OS should be the OS that is used to build the image, so:
> 
> * Which Ubuntu version is used to build the images (OSS and Enterprise)?

Starting from 5.2 and 2023.1 our images are based on Ubuntu:22.04 

> * If it's 22.04, when did the change from 20.04 take place?

We actually officially support ubuntu:22.04 starting 5.1 --> 2022.1

**Comment by annastuchlik** [comment]
Thanks!

**Comment by yaronkaikov** [comment]
> > > @yaronkaikov Hi Yaron, Please help me determine what is the recommended OS for ScyllaDB Enterprise and Open Source.
> > > 
> > > * According to the current documentation, it's Ubuntu 20.04.
> > > * According to @mykaul (as forwarded by @tomer-sandler) it should be 22.04.
> > > 
> > > The recommended OS should be the OS that is used to build the image, so:
> > > 
> > > * Which Ubuntu version is used to build the images (OSS and Enterprise)?
> > 
> > 
> > Starting from 5.2 and 2023.1 our images are based on Ubuntu:22.04
> 
> More specifically, our AMIs are going to be based on Ubuntu 22.04 _minimal_ images.

Also GCP and Azure

**Comment by annastuchlik** [comment]
@yaronkaikov  Supporting Ubuntu 22.04 is documented starting with 5.0 - is this a bug??

The recommended OS should be the same as the OS in the image. I'll make the update (backport to branch-5.2 will be required).

**Comment by tomer-sandler** [comment]
> > @yaronkaikov Hi Yaron, Please help me determine what is the recommended OS for ScyllaDB Enterprise and Open Source.
> > 
> > * According to the current documentation, it's Ubuntu 20.04.
> > * According to @mykaul (as forwarded by @tomer-sandler) it should be 22.04.
> > 
> > The recommended OS should be the OS that is used to build the image, so:
> > 
> > * Which Ubuntu version is used to build the images (OSS and Enterprise)?
> 
> Starting from 5.2 and 2023.1 our images are based on Ubuntu:22.04
> 
> > * If it's 22.04, when did the change from 20.04 take place?
> 
> We actually officially support ubuntu:22.04 starting 5.1 --> 2022.1

Isn't OSS 5.0 is the base for 2022.1?
And OSS 5.1 the base for 2022.2?
And OSS 5.2 the base for 2023.1?

**Comment by yaronkaikov** [comment]
> > > @yaronkaikov Hi Yaron, Please help me determine what is the recommended OS for ScyllaDB Enterprise and Open Source.
> > > 
> > > * According to the current documentation, it's Ubuntu 20.04.
> > > * According to @mykaul (as forwarded by @tomer-sandler) it should be 22.04.
> > > 
> > > The recommended OS should be the OS that is used to build the image, so:
> > > 
> > > * Which Ubuntu version is used to build the images (OSS and Enterprise)?
> > 
> > 
> > Starting from 5.2 and 2023.1 our images are based on Ubuntu:22.04
> > > * If it's 22.04, when did the change from 20.04 take place?
> > 
> > 
> > We actually officially support ubuntu:22.04 starting 5.1 --> 2022.1
> 
> OSS 5.0 is the base for 2022.1, and OSS 5.1 the base for 2022.2 (so we officially support if from 2022.2 not 2022.1)

Yes, sorry, I meant OSS 5.1 and Enterprise 2022.2

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
