### ISSUE TITLE
wrong `select *` at the beginning of ttl_test

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#13137]
Error happened at the beginning of `ttl_test.py::TestDistributedTTL::test_ttl_is_respected_on_repair`. Probably it was caused because the schema wasn't yet agreed after altering the keyspace.

https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2268/testReport/ttl_test/TestDistributedTTL/Tests___Sanity_Tests___test_ttl_is_respected_on_repair_parallel_aggregates_disabled_/

```
self = <ttl_test.TestDistributedTTL object at 0x7f11098a8750>
enable_parallized_aggregation = 'false'

    @pytest.mark.next_gating
    @pytest.mark.dtest_debug
    @pytest.mark.parametrize("enable_parallized_aggregation", ['true', 'false'], ids=["parallel_aggregates_enabled", "parallel_aggregates_disabled"])
    def test_ttl_is_respected_on_repair(self, enable_parallized_aggregation):
        """ Test that ttl is respected on repair """
    
        self.prepare(jvm_args=['--logger-log-level', 'forward_service=trace',
                     '--enable-parallelized-aggregation', enable_parallized_aggregation])
        self.session1.execute("""
            ALTER KEYSPACE ks WITH REPLICATION =
            {'class' : 'SimpleStrategy', 'replication_factor' : 1};
        """)
        self.session1.execute("""
            INSERT INTO ttl_table (key, col1) VALUES (1, 1) USING TTL 5;
        """)
        self.session1.execute("""
            INSERT INTO ttl_table (key, col1) VALUES (2, 2) USING TTL 1000;
        """)
    
>       assert_all(
            self.session1,
            "SELECT * FROM ttl_table;",
            [[1, 1, None, None], [2, 2, None, None]]
        )

ttl_test.py:784: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tools/retrying.py:43: in inner
    return func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

session = <cassandra.cluster.Session object at 0x7f11210fea10>
query = 'SELECT * FROM ttl_table;'
expected = [[1, 1, None, None], [2, 2, None, None]], cl = 1
ignore_order = False, num_attempts = 1, result_as_string = False
print_result_on_failure = True, timeout = None

    @retrying(num_attempts=1, sleep_time=10)
    def assert_all(session, query, expected, cl=ConsistencyLevel.ONE, ignore_order=False, num_attempts=1,
                   result_as_string=False, print_result_on_failure=True, timeout=None):
        """
        Assert query returns all expected items optionally in the correct order
        @param session Session in use
        @param query Query to run
        @param expected Expected results from query
        @param cl Optional Consistency Level setting. Default ONE
        @param ignore_order Optional boolean flag determining whether response is ordered
        @param timeout Optional query timeout, in seconds
        @param num_attempts: defines how many time try to assert data in case failure. Used in retrying decorator
        @param result_as_string: return result as string
        @param print_result_on_failure print actual result in the error in case failure
    
        Examples:
        assert_all(session, "LIST USERS", [['aleksey', False], ['cassandra', True]])
        assert_all(self.session1, "SELECT * FROM ttl_table;", [[1, 42, 1, 1]])
        """
        from tools.misc import list_to_hashed_dict  # to avoid cyclic dependency
        from tools.data import get_list_res  # to avoid cyclic dependency
    
        if result_as_string:
            list_res = get_list_res(session, query, cl, ignore_order, result_as_string, timeout=timeout)
        else:
            simple_query = SimpleStatement(query, consistency_level=cl)
            res = session.execute(simple_query) if timeout is None else session.execute(simple_query, timeout=timeout)
            list_res = _rows_to_list(res)
    
        if ignore_order:
            expected = list_to_hashed_dict(expected)
            list_res = list_to_hashed_dict(list_res)
        error = f"Expected {expected} from {query}, but got {list_res}" if print_result_on_failure \
            else f'Actual result ({len(list_res)} rows) is not as expected ({len(expected)} rows). Query: {query}'
>       assert list_res == expected, error
E       AssertionError: Expected [[1, 1, None, None], [2, 2, None, None]] from SELECT * FROM ttl_table;, but got [[1, 1, None, None]]

tools/assertions.py:215: AssertionError
```

**Comment by michoecho** [comment]
> Should be fixed by [scylladb/scylla-dtest#3086](https://github.com/scylladb/scylla-dtest/pull/3086) / [scylladb/scylla-dtest@8c2611d](https://github.com/scylladb/scylla-dtest/commit/8c2611d7d25d91089baf57283480f6dfc901788d)

It didn't help. The failure was seen again in https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2293/testReport/ttl_test/TestDistributedTTL/Tests___Sanity_Tests___test_ttl_is_respected_on_repair_parallel_aggregates_disabled_/ which contains the dtest patch.

**Comment by mykaul** [comment]
@Jadw1 - can you take a look at the above failure?

**Comment by Jadw1** [comment]
> @Jadw1 - can you take a look at the above failure?

on it

**Comment by bhalevy** [comment]
@Jadw1 by default session.execute runs the query with CL=ONE.  I'm not exactly sure what are the formal semantics for that consistency level for scans, but if we want any sane consistency I guess it should be executed with CL=QUORUM

**Comment by bhalevy** [comment]
@tgrabiec how does CL plays with range queries?

**Comment by bhalevy** [comment]
> > @tgrabiec how does CL play with range queries?
> 
> I think it has the same semantic as with point queries, for any given key (range) the result comes from CL replicas.

but how does the list if keys determined / assembled by the coordinator?

**Comment by bhalevy** [comment]
cc @eliransin

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla-dtest/pull/3102 improves on https://github.com/scylladb/scylla-dtest/pull/3086

**Comment by DoronArazii** [comment]
@eliransin / @Jadw1 can you please update on the progress?

**Comment by DoronArazii** [comment]
@Jadw1 ping

**Comment by bhalevy** [comment]
It still fails from time to time.
For example: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/247/testReport/ttl_test/TestDistributedTTL/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_ttl_is_respected_on_repair_parallel_aggregates_disabled_/
```
AssertionError: Expected [[1, 1, None, None], [2, 2, None, None]] from SELECT * FROM ttl_table;, but got [[1, 1, None, None]]
```

**Comment by DoronArazii** [comment]
@eliransin can we prioritize it as part of the quality effort?

**Comment by mykaul** [comment]
@kbr-scylla - thoughts on the above?

**Comment by kbr-scylla** [comment]
@Jadw1 what `--smp` were you using to run the test? Maybe it's a problem with propagating the new schema between shards, and even though `wait_for_schema_agreement` finishes, doing the query on one of the shards uses the old schema...

**Comment by Jadw1** [comment]
> @Jadw1 what `--smp` were you using to run the test? Maybe it's a problem with propagating the new schema between shards, and even though `wait_for_schema_agreement` finishes, doing the query on one of the shards uses the old schema...

the default value which is 1

**Comment by kbr-scylla** [comment]
Could you try running this:

>     * run the same instructions in the loop: (I've run it like 10000 times with both normal and heavy cpu load)
>       
>       * create a keyspace with RF=2
>       * create table
>       * alter the keyspace to RF=1
>       * insert the 2 rows
>       * select *
>       * drop the keyspace

but with larger `--smp`s. I see that the failure on Jenkins used `--smp 2`, but it could be that larger `smp`s make it easier to reproduce.
Other options may be important as well for reproducibility, like `--overprovisioned` or `--unsafe-bypass-fsync 1`
```
command used: "/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-cla2yw4p/test/node1/bin/scylla --options-file /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-cla2yw4p/test/node1/conf/scylla.yaml --log-to-stdout 1 --abort-on-seastar-bad-alloc --abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --logger-log-level forward_service=trace --enable-parallelized-aggregation false --api-address 127.0.46.1 --collectd-hostname 58f487be27b9.node1 --smp 2 --memory 1024M --developer-mode true --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.46.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --commitlog-use-o-dsync 0 --max-networking-io-control-blocks 1000"
```

**Comment by bhalevy** [comment]
> > @Jadw1 what `--smp` were you using to run the test? Maybe it's a problem with propagating the new schema between shards, and even though `wait_for_schema_agreement` finishes, doing the query on one of the shards uses the old schema...
> 
> the default value which is 1

Please update your scylla-ccm repo.
We've changed the default to 2.
In any case, you can override the default using `SCYLLA_EXT_OPTS="--smp 2"`

**Comment by michoecho** [comment]
I found the cause.

When altering the replication factor, there's a race in `merge_keyspaces()` which can cause shards other than 0 to finish the schema update with an effective replication map based on the old replication factor, instead of the new one.

Explanation:

`merge_keyspaces()` calls `database.update_keyspace()` on all shards in parallel.

`database.update_keyspace()` calls `keyspace.update_from()` which updates `keyspace._replication_factor` and creates a new `keyspace._effective_replication_map`.

However, on shard 0 `database.update_keyspace()` also calls (indirectly, through `get_notifier().update_keyspace()`) `storage_service.replicate_to_all_cores()`, which in parallel on all cores *reads* `keyspace._replication_factor` and creates a new `keyspace._effective_replication_map`.

With the right timing, the following can happen:
1. `database.update_keyspace()` is called on shards 0 and 1.
2. Shard 0 completes its `keyspace.update_from()` call, enters `storage_service.replicate_to_all_cores()` and sends to shard 1 a task which reads `keyspace._replication_factor`.
3. Shard 1 enters `database.update_keyspace()` and before it can update `keyspace._replication_factor` with the new value, it runs the task received from shard 0, which reads the old RF.
4. Shard 1 completes its `keyspace.update_from()` call, updating `keyspace._replication_factor` with the new value, and updating its `keyspace._effective_replication_map` with a new effective replication map based on the new RF.
5. Shard 0 completes its `storage_service.replicate_to_all_cores()`, updating `keyspace._effective_replication_map` on shard 1 with a new effective replication map based on the old RF.

At the end, the effective replication map on shard 1 is based on the *old* RF.

Now, if:

- node 0 shard 1 has RF=2
- node 1 shard 1 has RF=1
- node 1 shard 1 receives a write (since RF=1, it will not be replicated to node 0)
- node 0 shard 1 receives a CL=ONE read (since RF=2, it will only read from itself)

then the read won't see the write.

**Comment by michoecho** [comment]
Reliable (timing dependent, but mostly reliable — it works reliably for me) reproducer, assuming two nodes with --smp=2:

```diff
diff --git a/replica/database.cc b/replica/database.cc
index 7f4a14a4d7..d30ba29d1e 100644
--- a/replica/database.cc
+++ b/replica/database.cc
@@ -1244,6 +1244,11 @@ future<>
 keyspace::create_replication_strategy(const locator::shared_token_metadata& stm, const locator::replication_strategy_config_options& options) {
     using namespace locator;

+    if (utils::fb_utilities::get_broadcast_address().raw_addr() % 2 == 0) {
+        if (this_shard_id() == 1) {
+            co_await seastar::sleep(100ms);
+        }
+    }
     _replication_strategy =
             abstract_replication_strategy::create_replication_strategy(
                 _metadata->strategy_name(), options);
diff --git a/service/storage_service.cc b/service/storage_service.cc
index 6767ae7246..96406444de 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -2669,6 +2669,7 @@ future<> storage_service::join_cluster(cdc::generation_service& cdc_gen_service,
 }

 future<> storage_service::replicate_to_all_cores(mutable_token_metadata_ptr tmptr) noexcept {
+    using namespace std::chrono_literals;
     assert(this_shard_id() == 0);

     slogger.debug("Replicating token_metadata to all cores");
@@ -2689,6 +2690,10 @@ future<> storage_service::replicate_to_all_cores(mutable_token_metadata_ptr tmpt
             pending_token_metadata_ptr[this_shard_id()] = make_token_metadata_ptr(co_await tmptr->clone_async());
         });

+        if (utils::fb_utilities::get_broadcast_address().raw_addr() % 2 == 1) {
+            co_await seastar::sleep(1000ms);
+        }
+
         // Precalculate new effective_replication_map for all keyspaces
         // and clone to all shards;
         //
@@ -2754,6 +2759,9 @@ future<> storage_service::replicate_to_all_cores(mutable_token_metadata_ptr tmpt
         std::rethrow_exception(std::move(ex));
     }

+    if (utils::fb_utilities::get_broadcast_address().raw_addr() % 2 == 0) {
+        co_await seastar::sleep(1000ms);
+    }
     // Apply changes on all shards
     try {
         co_await container().invoke_on_all([&] (storage_service& ss) {
```

```diff
diff --git a/ttl_test.py b/ttl_test.py
index d1682edf..ef59fac3 100644
--- a/ttl_test.py
+++ b/ttl_test.py
@@ -756,18 +756,20 @@ class TestDistributedTTL(Tester):
             {'class' : 'SimpleStrategy', 'replication_factor' : 1};
         """)

-        self.session1.execute(f"""
-            INSERT INTO ttl_table (key, col1) VALUES (1, 1) USING TTL {short_ttl};
-        """)
-        self.session1.execute(f"""
-            INSERT INTO ttl_table (key, col1) VALUES (2, 2) USING TTL {long_ttl};
-        """)
-
-        assert_all(
-            self.session1,
-            "SELECT * FROM ttl_table;",
-            [[1, 1, None, None], [2, 2, None, None]]
-        )
+        expected = []
+        for i in range(64):
+            self.session1.execute(f"""
+                INSERT INTO ttl_table (key, col1) VALUES ({i}, {i}) USING TTL {short_ttl};
+            """)
+            expected += [[i, i, None, None]]
+
+        for i in range(10):
+            assert_all(
+                self.session1,
+                "SELECT * FROM ttl_table;",
+                expected,
+                ignore_order=True
+            )
         time.sleep(short_ttl + 2)
         logger.debug('SStable dump after writes with RF = 1')
         print_sstable(self.node1, 'ks', 'ttl_table')
```

**Comment by michoecho** [comment]
@kbr-scylla In the end I had to resort to making hypotheses and adding sleeps to the code. I didn't manage to reproduce it as a black box, even over thousands of runs. You were right.

**Comment by bhalevy** [comment]
Based on @michoecho terrific analysis I think that the direction for fixing this would be around this loop:
https://github.com/scylladb/scylladb/blob/d2e089777bf5cca87a81a6ace7c5d67d37365a08/db/schema_tables.cc#L1362

I'd consider first breaking it into 2 loops:
one for the created keyspaces and the other for the altered keyspaces.

And for each loop, first invoke on shard 0 and then on the other shards.
And with that in mind, maybe it's about time we handle errors on this path to prevent leaving the shards in an inconsistent state. Undoing keyspace creation is technically easy (though ideally we should create the keyspaces on all shards provisionally before they are "published", and only after all succeeded, we should commit the changes and make the created keyspaces visible on all shards).

As for undoing `update_keyspace`, this will need more work.
We should consider aborting if shard 0 succeeds and any of the other shards fails.

**Comment by bhalevy** [comment]
> Based on @michoecho terrific analysis I think that the direction for fixing this would be around this loop:
> 
> https://github.com/scylladb/scylladb/blob/d2e089777bf5cca87a81a6ace7c5d67d37365a08/db/schema_tables.cc#L1362
> 
> I'd consider first breaking it into 2 loops: one for the created keyspaces and the other for the altered keyspaces.
> 
> And for each loop, first invoke on shard 0 and then on the other shards. And with that in mind, maybe it's about time we handle errors on this path to prevent leaving the shards in an inconsistent state. Undoing keyspace creation is technically easy (though ideally we should create the keyspaces on all shards provisionally before they are "published", and only after all succeeded, we should commit the changes and make the created keyspaces visible on all shards).
> 
> As for undoing `update_keyspace`, this will need more work. We should consider aborting if shard 0 succeeds and any of the other shards fails.

After re-reading Michal's explanation, we may want to go even deeper than that.

The call to `database::keyspace_changed` which invokes `update_topology_change_info` on shard 0 that ends up calling `mutate_token_metadata` on each shard.  I think that the race in storage_service::replicate_on_all_shards that Michal described can still happen if we call `update_keyspace` on all other shards in parallel, so we'd need to serialize the loop. This will call mutate_token_metadata and replicate_to_all_cores for each shard after updating its keyspace replication strategy.  It should arrive at the right state after the last shard updates its replication strategy but it is extremely wasteful.

Maybe we should notify the subscribers only when all shards are done updating the database.
Or maybe we should detect that things are in flux in `storage_service::keyspace_changed` and apply the change only when all keyspace shards are updated.
Yikes

**Comment by tgrabiec** [comment]
> This will call mutate_token_metadata and replicate_to_all_cores for each shard after updating its keyspace replication strategy. It should arrive at the right state after the last shard updates its replication strategy but it is extremely wasteful.

Should we mutate token metadata on shard 0 only, and rely on replicate_to_all_cores() to take care of other shards?

**Comment by michoecho** [comment]
What I would like to see first is documentation of what are the relevant data structures, what code is responsible for modifying them and when it is supposed to happen.

All the relevant pieces of code I mentioned in my explanation (`database::update_keyspace`, `keyspace::update_from`, `storage_service::replicate_to_all_cores`, `migration_listener::on_update_keyspace`, `merge_keyspaces`, `keyspace::_effective_replication_map`) have a combined total of **zero** documentation. I have no idea what's the bigger picture of it all supposed to be.

**Comment by bhalevy** [comment]
> What I would like to see first is documentation of what are the relevant data structures, what code is responsible for modifying them and when it is supposed to happen.
> 
> All the relevant pieces of code I mentioned in my explanation (`database::update_keyspace`, `keyspace::update_from`, `storage_service::replicate_to_all_cores`, `migration_listener::on_update_keyspace`, `merge_keyspaces`, `keyspace::_effective_replication_map`) have a combined total of **zero** documentation. I have no idea what's the bigger picture of it all supposed to be.

Here's my proposal: https://github.com/scylladb/scylladb/pull/14158
(minus documentation.  and I agree it's a good opportunity to add some).

**Comment by denesb** [comment]
The fix of this issue (https://github.com/scylladb/scylladb/commit/ba1578605908bce48f0008d76cd32f8e255ac526) is already in branch-5.4, removing the backport label.

**Comment by avikivity** [comment]
You didn't actually, and what about 5.1/5.2?

**Comment by bhalevy** [comment]
> You didn't actually, and what about 5.1/5.2?

https://github.com/scylladb/scylladb/pull/15872 is queued at next-5.2

I didn't prepare a backport for 5.1.
Let me know if it's needed.

**Comment by denesb** [comment]
> You didn't actually, and what about 5.1/5.2?

I meant, remove the "Requires-Backport-to-5.4" label.

**Comment by avikivity** [comment]
ah, ok.

Looks like it's just a test backport, so should be done if flakiness is observed.

**Comment by bhalevy** [comment]
> ah, ok.
> 
> Looks like it's just a test backport, so should be done if flakiness is observed.

No, not really.  We thought so in the beginning but it turned out to related to a fundamental issue around applying schema changes in an orderly way across shards.

See the eventual fix: https://github.com/scylladb/scylladb/pull/14158

**Comment by mykaul** [comment]
Backported to 5.2 via https://github.com/scylladb/scylladb/pull/15872
