### ISSUE TITLE
Docs: add Raft recovery information on Troubleshooting, Procedures

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13149]
With the introduction of Raft as the default in 5.2, many producers will need an update, including a link to the [manual recovery procedure](https://docs.scylladb.com/master/architecture/raft.html#raft-manual-recovery-procedure).

For example:
- Adding/remove/replace nodes will fail without a quorum
- Updating the schema will fail without a quorum

The recovery procedure should be added to the Troubleshooting section.

**Comment by tzach** [comment]
@kostja @annastuchlik FYI

**Comment by tzach** [comment]
For example, [adding a node](https://docs.scylladb.com/master/operating-scylla/procedures/cluster-management/add-node-to-cluster.html) should include a note about the need for quorum and what to do if there is no quorum

**Comment by annastuchlik** [comment]
@kostja Could you provide me with the information in this PR? Perhaps we could set up a meeting to determine what should be updated?

**Comment by tzach** [comment]
@annastuchlik lets start with adding a link to the recovery procedure in the  Troubleshooting section.
