### ISSUE TITLE
log printing of boost::adaptors::map_keys range is broken

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13146]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/214/artifact/logs-full.release.018/1678519307327_lwt_schema_modification_test.py%3A%3ATestLWTSchemaModification%3A%3Atest_lwt_load/node7.log
```
INFO  2023-03-11 07:04:41,412 [shard 0] repair - bootstrap_with_repair: started with keyspaces=system_distributed_everywheresystem_tracessystem_authsystem_distributed, nr_ranges_total=8153
```

This message comes from https://github.com/scylladb/scylladb/blob/1379d8330f1966fec818cfe5567544091bbfdfd2/repair/repair.cc#L1356

Looks like I broke it in cffe00cc58607517252536be36fca55ea491f163

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport to 5.[2-3]

**Comment by denesb** [comment]
Backport is not clean, please create backport PRs.

**Comment by bhalevy** [comment]
> Backport is not clean, please create backport PRs.

@denesb: https://github.com/scylladb/scylladb/pull/14405

**Comment by denesb** [comment]
> > Backport is not clean, please create backport PRs.
> 
> @denesb: #14405

I need one for 5.3 first.

**Comment by bhalevy** [comment]
> > > Backport is not clean, please create backport PRs.
> > 
> > 
> > @denesb: #14405
> 
> I need one for 5.3 first.

Sorry for asking to backport to 5.3 in https://github.com/scylladb/scylladb/issues/13146#issuecomment-1600499247.

https://github.com/scylladb/scylladb/commit/15c9f0f0df14b98fc4e10456e2526956f639e30e is already in 5.3

**Comment by DoronArazii** [comment]
@denesb I guess 'backport candidate' & 'Requires-Backport-to-5.2' can be removed?

**Comment by denesb** [comment]
Yes, removed.
