### ISSUE TITLE
docs: Issue in page OS Support by Platform and Version: out of date warning on kernel 3.15

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13154]
I would like to report an issue in page https://docs.scylladb.com/branch-5.1/getting-started/os-support

### Problem
The following message is out of date, can be removed:

> ScyllaDB requires a fix to the XFS append introduced in kernel 3.15 (back-ported to 3.10 in RHEL/CentOS). ScyllaDB will not run with earlier kernel versions. Details in [ScyllaDB issue 885](https://github.com/scylladb/scylla/issues/885).

**Comment by annastuchlik** [comment]
This information is only present in version 5.1. It was removed from master and version 5.2 with this commit: https://github.com/scylladb/scylladb/commit/7cd613fc085976c2489080dce4a8b470d878febd. Closing.
