### ISSUE TITLE
unified package has the whole cqlsh build directory  

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#13181]
Since merge of #11937, seems like the unified package has all of the content of the cqlsh/build directory

It was identified by SCT failing to get the correct `.relocatable_package_version` since now there's multiple of those files:

```
🟢 ❯ curl https://downloads.scylladb.com/unstable/scylla/master/relocatable/2023-03-15T03:10:52Z/scylla-unified-5.3.0~dev-0.20230315.1d9b7f3a929b.x86_64.tar.gz -o ./unified_package.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  177M  100  177M    0     0  5708k      0  0:00:31  0:00:31 --:--:-- 5535k

~ on  master [📝✓] took 32s
🟢 ❯ tar -xzO --wildcards -f ./unified_package.tar.gz scylla-*/.relocatable_package_version
2
2
2
3.0
```

cqlsh only tar doesn't has the full build directory: 
https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/master/relocatable/2023-03-15T03%3A10%3A52Z/scylla-cqlsh-5.3.0~dev-0.20230315.1d9b7f3a929b.noarch.tar.gz

so we need to figure out where it's coming from.

**Comment by fruch** [comment]
@yaronkaikov FYI, I wonder if if to patch it in SCT until we figure it out or not.

@syuu1228 do you have any idea what have I missed ?

**Comment by avikivity** [comment]
Submodule cqlsh is new, no backport needed.
