### ISSUE TITLE
cql-pytest - add the ability to run any released version of Scylla 

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13189]
One of the design goals of the cql-pytest test suite is that you can any test against any implementation of CQL - Any version of Scylla, Cassandra, or even some Cassandra-emulating web service. You can run yourself any Scylla/Cassandra version, and then `cd cql-pytest; pytest` to connect to it and run the tests. But running Scylla and Cassandra is not easy, so we have convenience scripts `test/cql-pytest/run` and `test/cql-pytest/run-cassandra`, respectively, to do it.

Currently, `test/cql-pytest/run` only knows how to run Scylla which you compiled yourself (`build/*/scylla`). Sometimes we want to run a test against some older official release (e.g., to check if a bug we found is a regression). This is doable manually, but inconvenient. I would like to do conveniently through `test/cql-pytest/run`:

1. Add an option to `run` which specifies a desired version of Scylla.
2. It will download a relocatable package (tar of executable and libraries) of this version, extract it and run it instead of `build/*/scylla`.
3. The downloaded relocatable package will be cached for some time (e.g., keep the last N downloaded versions or keep them for duration T) to allow quickly retesting on the same version.

@fruch noted in https://github.com/scylladb/scylla-ccm/issues/438 that ccm already does this and we can copy from it (different Scylla versions apparently had different package organizations so there is some non-trivial logic).

Another thing we will need to handle is that some of the Scylla options that `test/cql-pytest/run` passes to Scylla changed over the years. It might not be possible to run a one-year-old Scylla with the options we currently pass to run today's Scylla. We may need to add some logic to the `run` script on how to detect which options to pass to which version, or allow the user to specify options to add or remove from Scylla in the `run` command line.

**Comment by nyh** [comment]
Today I wished again that I had this feature. A question was raised of whether some specific old Scylla release had a specific feature, or it didn't. Yes, I can go to the git logs and try to look for the relevant commit, but then I can miss problems a partial backport (that, for example, remembered to backport the original patch but forgot some followup improvements). It would have been so convenient to just run the cql-pytest test(s) for that feature from modern Scylla's test/cql-pytest directory against that specific old Scylla release, and only if the tests pass - I'm sure that the feature was correctly supported by that old version.

**Comment by nyh** [comment]
Another wish for this feature: We could use it for bisecting a problem that is reproduced by a cql-pytest or alternator test easily and much faster than "git bisect": Imagine we had a list of nightly versions of Scylla and the downloadable relocatable package for all of them. We could do a binary search over these versions to automatically find the first version where a specific test fails (or vice versa). We can probably download-and-run each version in just a couple of minutes, compared to the much longer delays involve in "git bisect" and compiling all the versions.

**Comment by kostja** [comment]
@nyh while I think it's a useful feature, I also think you can't have it all in test.py. test.py needs to focus on the main use case - running the test when developing patches and finding regressions these patches introduce. Multi-version tests, as well as upgrade/downgrade tests,  need access to an out-of-source build, possibly multiple versions - which is something test.py doesn't assume for most of the tests. Perhaps we need to build a different tool for that.

**Comment by nyh** [comment]
> @nyh while I think it's a useful feature, I also think you can't have it all in test.py.
> test.py needs to focus on the main use case - running the test when developing patches and finding regressions these patches introduce. Multi-version tests, as well as upgrade/downgrade tests, need access to an out-of-source build, possibly multiple versions - which is something test.py doesn't assume for most of the tests. Perhaps we need to build a different tool for that.


I agree, which is why I never suggested it should be in the script "test.py". Like you, I consider test.py a one-trick pony, a tool to run all tests inside Jenkins. This is exactly why I insisted in the past, and still insist on having additional scripts like test/cql-pytest/run (which is what I mentioned in the issue, not test.py) that do things that this pony can't or doesn't want to do. So for example I have a script test/cql-pytest/run-cassandra to run tests in test/cql-pytest against _Cassandra_ instead of Scylla and want such a script for other test subdirectories as well (e.g., https://github.com/scylladb/scylladb/issues/10098).  I have another script test/alternator/run to run Alternator tests against DynamoDB instead of Scylla. 

I'm a big fan of the Unix philosophy - build small tools that do one thing best instead of one big tool that tries to do everything. The biggest risk on the "one big tool" approach is that eventually someone will decide it doesn't need to do X because it already does Y and Z. This can't happen when you have many small tools, and can always add another tool that does X.

**Comment by nyh** [comment]
> Another wish for this feature: We could use it for bisecting a problem that is reproduced by a cql-pytest or alternator test easily and much faster than "git bisect": Imagine we had a list of nightly versions of Scylla and the downloadable relocatable package for all of them. We could do a binary search over these versions to automatically find the first version where a specific test fails (or vice versa). We can probably download-and-run each version in just a couple of minutes, compared to the much longer delays involve in "git bisect" and compiling all the versions.

I just ran into this need again. This could have saved me hours in bisecting https://github.com/scylladb/scylladb/issues/17237.

**Comment by mykaul** [comment]
> > Another wish for this feature: We could use it for bisecting a problem that is reproduced by a cql-pytest or alternator test easily and much faster than "git bisect": Imagine we had a list of nightly versions of Scylla and the downloadable relocatable package for all of them. We could do a binary search over these versions to automatically find the first version where a specific test fails (or vice versa). We can probably download-and-run each version in just a couple of minutes, compared to the much longer delays involve in "git bisect" and compiling all the versions.
> 
> I just ran into this need again. This could have saved me hours in bisecting #17237.

@yaronkaikov - you have something that can help with this, no?

**Comment by yaronkaikov** [comment]
> > > Another wish for this feature: We could use it for bisecting a problem that is reproduced by a cql-pytest or alternator test easily and much faster than "git bisect": Imagine we had a list of nightly versions of Scylla and the downloadable relocatable package for all of them. We could do a binary search over these versions to automatically find the first version where a specific test fails (or vice versa). We can probably download-and-run each version in just a couple of minutes, compared to the much longer delays involve in "git bisect" and compiling all the versions.
> > 
> > 
> > I just ran into this need again. This could have saved me hours in bisecting #17237.
> 
> @yaronkaikov - you have something that can help with this, no? BTW, I imagine that for such simple use cases, a 'docker run' running this bisection could be a very easy and quick win.

Yes, we do. We have a bisect job in Jenkins that can run through 2 commits and run specific tests (from test.py). the job is https://jenkins.scylladb.com/job/scylla-master/job/bisect/ , @nyh Let me know if you need help with running it.

**Comment by nyh** [comment]
> Yes, we do. We have a bisect job in Jenkins that can run through 2 commits and run specific tests (from test.py). the job is https://jenkins.scylladb.com/job/scylla-master/job/bisect/ , @nyh Let me know if you need help with running it.

Thanks for the offer. I'm actually done with bisection of this issue, so if you explain to me today how to use this job, and I won't use it today, I probably won't remember anything next time I need to do bisection :-( Other developers also won't benefit from tutoring me personally. So please consider **documenting** this technique in writing, and perhaps also other magic Jenkins jobs that developers should know about and often don't. This documentation can be in scylla.git's "docs/dev" directory or perhaps in some other more-scylladb-the-company specific place, but developers will need to able to find this information when they need it. Perhaps we can put a link to such documentation on our Jenkins homepage?

**Comment by nyh** [comment]
>     1. Add an option to `run` which specifies a desired version of Scylla.
> 
>     2. It will download a relocatable package (tar of executable and libraries) of this version, extract it and run it instead of `build/*/scylla`.

For some version (especially official releases, may be more), we might be able to download and run Scylla via docker, which is easier to do than the relocatable package (our run script doesn't need to worry about finding the version, unpacking it or caching it) so can help us get this capability more quickly - but will probably be less efficient if the docker downloads more than we really need.

**Comment by nyh** [comment]
I just ran into this need again, needing to check the suspicion that a relatively recently-added test that xfails on master actually passed on an older version (after a user reported a regression).

This will be a super-convenient feature, and I'm considering just sitting down a few hours and doing it instead of keep coming to this issue and saying how useful it will be.

**Comment by fruch** [comment]
poors man kind of way, is using ccm to pull version and extract them, and just teach test.py to work with scylla executable from a specific location.

and then later clone the ccm logic of retrieving releases

**Comment by nyh** [comment]
If you are used to ccm, you can already do this easily: Run one scylla node with ccm, then 'cd test/cql-pytest' and run 'pytest'.
You can't do this with test.py, and I have no intention of changing that. Test.py is all about insisting to run Scylla by itself.

**Comment by fruch** [comment]
> If you are used to ccm, you can already do this easily: Run one scylla node with ccm, then 'cd test/cql-pytest' and run 'pytest'. You can't do this with test.py, and I have no intention of changing that. Test.py is all about insisting to run Scylla by itself.

you missed my point, ccm can download and extract, regardless of running a node or not
see those helper scripts 
https://github.com/scylladb/scylla-ccm/blob/next/scripts/download_release.sh

it's not running scylla, it never calls `ccm start`

but once you run those commands, you have a scylla executable (and the rest of it) sitting in `~/.ccm/scylla-repository/release/5.1.18/bin/scylla` 

from this point if you just teach test.py to use that executable (or folders)

I think it would solve a big portion of the problem with a relatively low effort (I think... not sure how test.py is entrenched into specific locations and such)

**Comment by mykaul** [comment]
> I created a small script, fetch_scylla.py (inspired by CCM's implementation but not identical) which gets the Scylla relocatable package, which is significantly smaller than the "unified" package or docker image, for a particular version such as 5.4.1 or 2021.1, and then test/cql-pytest/run can use it. It works beautifully (I just used it to confirm again that #15559 did not exist on 2021.1), but there is one major annoyance:
> 
> The script test/cql-pytest/run runs Scylla with a gazillion parameters that are useful for the current Scylla, but 9 of them are not supported in 2021.1 and need to be dropped. To add insult to injury, I tried to run 5.4 and there was a specific parameter it needed ("--force-schema-commit-log=true") which wasn't needed for later versions and didn't exist in earlier versions.
> 
> So before I make this feature useful, I need to figure out how to have a Scylla startup script which is forgiving to changes in command line parameters. If I can't find a better option, I may need to hard-code version checks (e.g., "use parameter XYZ but only if version is >5.4") but this will be very ugly so I'm still looking for a better option.

Hard-coding makes sense. It's not such a big deal (as we do not have that many versions and that many changes). I reckon it'll be useful reference elsewhere (docker-compose for example)
