### ISSUE TITLE
doc: fix the service name

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#13207]
The service name for ScyllaDB Enterprise is `scylla-server`, NOT `scylla-enterprise-server`. The service name was fixed in the Enterprise-to -Enterprise user guides:
https://github.com/scylladb/scylladb/pull/12679
https://github.com/scylladb/scylladb/pull/12698

The same bug is present in the Open Souce-to-Enterprise user guides and must be fixed:
https://docs.scylladb.com/stable/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.1-to-2022.2/upgrade-guide-from-5.1-to-2022.2-generic.html

https://docs.scylladb.com/stable/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.0-to-2022.1/upgrade-guide-from-5.0-to-2022.1-rpm.html
https://docs.scylladb.com/stable/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.0-to-2022.1/upgrade-guide-from-5.0-to-2022.1-debian-10.html
https://docs.scylladb.com/stable/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.0-to-2022.1/upgrade-guide-from-5.0-to-2022.1-ubuntu.html

In addition, fix the name if the installation package to be` scylla-enterprise`, NOT `scylla-enterprise-server` in the 5.0-to-2022.1 upgrade guides.

**Comment by avikivity** [comment]
Already backported, removing label.
