### ISSUE TITLE
Internal server error when null is used in multi-column relation

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13217]
The Cassandra unit test `cassandra_tests/validation/operations/select_multi_column_relation_test.py`::`testMultiClusteringInvalidQueries` prepares the query
```
SELECT * FROM %s WHERE a = 0 AND (b, c, d) IN ((?, ?, ?), (?, ?, ?))
```
and then binds to it `1, 2, None, 2, 1, 4`. Cassandra does not allow this null in the tuple in the condition, and gives the error:
```
Invalid null value in condition for columns: [b, c, d]
```
Arguably, instead of giving this error, Scylla could silently accept this null, just not matching anything (this is how Scylla usually handles nulls). But today Scylla neither gives a good error message nor silently accepts it - instead it generates an internal server error, with the message "attempted to create key component from empty optional". This is a `logic_error` exception thrown deep in compound.h, and causes the internal server error.

Surprisingly, the same test shows that when the query is the same except just a single item in the IN, i.e.,
```
SELECT * FROM %s WHERE a = 0 AND (b, c, d) IN ((?, ?, ?))
```
it correctly gives an error in the null. I am guessing (?) that a single-item IN is handled differently (perhaps as an equality check) from multi-item IN, and has different error checking.

**Comment by Jager227** [comment]
Should we specify which column contains the null value for the error, or should we simply display a message stating that it is not allowed to use null in the query?
