### ISSUE TITLE
alternator: no validation error for unused ExpressionAttributeNames in BatchGetItem

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#13251]
BatchGetItem request is a map of table names and 'sub-requests', ExpressionAttributeNames is defined on
'sub-request' level but the code was instead checking the top level, obtaining nullptr every time which
effectively disables unused names check.

Fixed as a part of cl: https://github.com/scylladb/scylladb/pull/12675

**Comment by denesb** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
The specific patch that solved this issue (https://github.com/scylladb/scylladb/commit/9ce65270d5a6579797e0928dd65871747f233e81) is a minor error-validation improvement, so I don't think should be backported.
The larger PR that contained it (https://github.com/scylladb/scylladb/pull/12675) also contains a minor performance improvement, which we also usually don't backport.
So I'm removing the backport candidate tag.
@nuivall please write here if you think differently.
