### ISSUE TITLE
dtest: all nodes crash with `error: too many positional options have been specified on the command line`

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#13283]
Seen in
* https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/209/
* https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/213/

All dtests fail with an error like this:
```
Scylla version 5.3.0~dev-0.20230322.923646de4a04 with build-id 9910030b22c5c9c9a28a159c4c5653166014f7ad starting ...
command used: "/jenkins/workspace/scylla-master/scylla-ci/scylla/.dtest/dtest-q_si00i4/test/node1/bin/scylla --options-file /jenkins/workspace/scylla-master/scylla-ci/scylla/.dtest/dtest-q_si00i4/test/node1/conf/scylla.yaml --log-to-stdout 1 --abort-on-seastar-bad-alloc  --abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --blocked-reactor-notify-ms 100 --api-address 127.0.77.1 --collectd-hostname a3855b4c9df0.node1 --smp 2 --memory 1024M --developer-mode true --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.77.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --commitlog-use-o-dsync 0 --max-networking-io-control-blocks 1000"
parsed command line options: [options-file: /jenkins/workspace/scylla-master/scylla-ci/scylla/.dtest/dtest-q_si00i4/test/node1/conf/scylla.yaml, log-to-stdout, (positional) 1, abort-on-seastar-bad-alloc, (positional) , abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, blocked-reactor-notify-ms, (positional) 100, api-address: 127.0.77.1, collectd-hostname, (positional) a3855b4c9df0.node1, smp, (positional) 2, memory, (positional) 1024M, developer-mode: true, default-log-level, (positional) info, collectd, (positional) 0, overprovisioned, prometheus-address: 127.0.77.1, unsafe-bypass-fsync, (positional) 1, kernel-page-cache, (positional) 1, commitlog-use-o-dsync: 0, max-networking-io-control-blocks, (positional) 1000]
error: too many positional options have been specified on the command line

Try --help.
```

Looks like a test env issue.

**Comment by denesb** [comment]
Looks like arguments to command-line options are considered positional arguments:
```smp, (positional) 2```

**Comment by denesb** [comment]
Actually, I tried this locally and arguments are printed like above but they parse fine. So I have no idea what is wrong.

**Comment by denesb** [comment]
From @fruch:

> @bhalevy
>
> Seems like it's cause of:
> https://github.com/scylladb/scylla-ccm/pull/437
>
> Want to take a look before we start reverting it ?

**Comment by nyh** [comment]
It looks like "--log-to-stdout 1" stopped working (as if log-to-stdout no longer requires a parameter). Other paramters taking an integer continued to work. Did anything change in this recently?

**Comment by nyh** [comment]
> It looks like "--log-to-stdout 1" stopped working (as if log-to-stdout no longer requires a parameter). Other paramters taking an integer continued to work. Did anything change in this recently?

Yes, it seems the log_to_stdout option doesn't take any arguments, and it never did. So how did this break today?

**Comment by fruch** [comment]
> > It looks like "--log-to-stdout 1" stopped working (as if log-to-stdout no longer requires a parameter). Other paramters taking an integer continued to work. Did anything change in this recently?
> 
> Yes, it seems the log_to_stdout option doesn't take any arguments, and it never did. So how did this break today?

Seems like we have a CCM change that broke out of the next cycle

**Comment by fruch** [comment]
faulty commits in CCM were yank out of master/next branches

Fix to avoid ccm or dtest commit skip next again:
https://github.com/scylladb/scylla-pkg/pull/3351

**Comment by mykaul** [comment]
@fruch - so can we now close this one?

**Comment by fruch** [comment]
> @fruch - so can we now close this one?

Yes, the offending code was removed, and the issue with scylla-pkg that didn't used the next branch for ccm was fixed.
