### ISSUE TITLE
sstable_compaction_test may timeout

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13280]
As seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/185/ (while checking #13264)

```
[2023-03-21T18:40:04.052Z] ------------------------------------------------------------------------------
[2023-03-21T18:40:04.052Z] The following test(s) have failed: boost/sstable_compaction_test
...
[2023-03-21T18:40:04.054Z] test/boost/sstable_compaction_test.cc(0): Entering test case "max_ongoing_compaction_test"
...
[2023-03-21T18:40:04.058Z] === TEST.PY SUMMARY START ===
[2023-03-21T18:40:04.058Z] Test timed out
[2023-03-21T18:40:04.058Z] === TEST.PY SUMMARY END ===
[2023-03-21T18:40:04.058Z] 
[2023-03-21T18:40:04.058Z] ------------------------------------------------------------------------------
[2023-03-21T18:40:04.058Z] Summary: 1 of the total 8104 tests failed
[2023-03-21T18:40:04.058Z] Traceback (most recent call last):
[2023-03-21T18:40:04.058Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1421, in workaround_python26789
[2023-03-21T18:40:04.058Z]     code = await main()
[2023-03-21T18:40:04.058Z]            ^^^^^^^^^^^^
[2023-03-21T18:40:04.058Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1402, in main
[2023-03-21T18:40:04.058Z]     write_consolidated_boost_junit_xml(options.tmpdir, mode)
[2023-03-21T18:40:04.058Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1353, in write_consolidated_boost_junit_xml
[2023-03-21T18:40:04.058Z]     test_xml = test.get_junit_etree()
[2023-03-21T18:40:04.058Z]                ^^^^^^^^^^^^^^^^^^^^^^
[2023-03-21T18:40:04.058Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 629, in get_junit_etree
[2023-03-21T18:40:04.058Z]     self.__junit_etree = ET.parse(self.xmlout)
[2023-03-21T18:40:04.058Z]                          ^^^^^^^^^^^^^^^^^^^^^
[2023-03-21T18:40:04.058Z]   File "/usr/lib64/python3.11/xml/etree/ElementTree.py", line 1218, in parse
[2023-03-21T18:40:04.058Z]     tree.parse(source, parser)
[2023-03-21T18:40:04.058Z]   File "/usr/lib64/python3.11/xml/etree/ElementTree.py", line 580, in parse
[2023-03-21T18:40:04.058Z]     self._root = parser._parse_whole(source)
[2023-03-21T18:40:04.058Z]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-03-21T18:40:04.058Z] xml.etree.ElementTree.ParseError: no element found: line 1, column 0
[2023-03-21T18:40:04.405Z] [Pipeline] echo
[2023-03-21T18:40:04.410Z] Error: test failed, error: |hudson.AbortException: script returned exit code 255|.
```

There are two surprises in the logs:

1. It has 1hour gap in handling compaction activity
```
INFO  2023-03-21 14:00:00,618 [shard 0] compaction - [Compact tests.1 e83204e0-c7df-11ed-b840-94ae612915a0] Compacted 4 sstables to [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/release/scylla-2163326a-eb7e-4c90-b40d-a6f3d866b418/1/mc-1-big-Data.db:level=0]. 163kB to 40kB (~25% of original) in 41ms = 999kB/s. ~512 total partitions merged to 4.
INFO  2023-03-21 15:00:05,001 [shard 0] compaction - [Compact tests.5 4c9c5f90-c7e8-11ed-b840-94ae612915a0] Compacting [/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/release/scylla-2163326a-eb7e-4c90-b40d-a6f3d866b418/5/mc-1-big-Data.db:level=0:origin=compaction]
```

2. While running normally the test case only has `origin=memtable` jobs, while _this_ run also contains (and seem to hang in) `origin=compaction`

Cc @raphaelsc

**Comment by DoronArazii** [comment]
@raphaelsc can you please explore this one, CI-Stability gets a large attention those days

**Comment by xemul** [comment]
@raphaelsc , nope, we didn't discuss this with Avi

**Comment by raphaelsc** [comment]
> @raphaelsc , nope, we didn't discuss this with Avi

oops :-)

**Comment by DoronArazii** [comment]
@raphaelsc is it fixing the issue ^^ ? 
Can we close it? or do you still actively working on it?

**Comment by raphaelsc** [comment]
> @raphaelsc is it fixing the issue ^^ ? Can we close it? or do you still actively working on it?

no, I just bumped into it again with CI. will make time to investigate it by the end of this week

**Comment by mykaul** [comment]
> > @raphaelsc is it fixing the issue ^^ ? Can we close it? or do you still actively working on it?
> 
> no, I just bumped into it again with CI. will make time to investigate it by the end of this week

@raphaelsc - any updates?

**Comment by raphaelsc** [comment]
I don't think 1h is random. we arm a 1h timer to reevaluate compaction. we probably have some timing issue, which causes the reevaluation not to happen asap.

**Comment by tchaikov** [comment]
surfaced again in https://jenkins.scylladb.com/job/scylla-master/job/next/6137/consoleFull#-20089227642d64d3cc-9cf1-4f8e-9ae7-050ec58d788c

**Comment by mykaul** [comment]
Haven't seen it since June - closing for the time being.

**Comment by kbr-scylla** [comment]
In this CI failure https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5734 it seems that during `boost.sstable_compaction_test.max_ongoing_compaction_test` the node entered some kind of compaction hot loop and kept spamming the logs with DEBUG-level `compaction_manager` logs (introduced in 63e4d6c96565344ab68a82d8306317a976069372)

**Comment by kbr-scylla** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5734/artifact/testlog/x86_64/debug/boost.sstable_compaction_test.max_ongoing_compaction_test.3.log 24GB log file

**Comment by raphaelsc** [comment]
@bhalevy did you see another occurrence? if yes, please share the jenkins link.

**Comment by raphaelsc** [comment]
I will patch the test to fail after a reasonable amount of iterations that would be enough for success. So we can avoid such huge log files.

**Comment by bhalevy** [comment]
Timed out again with 25GB log file in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7959/testReport/junit/boost.sstable_compaction_test.max_ongoing_compaction_test.3.xunit/xml/Tests___Unit_Tests____empty_/
It looks like compaction tasks just keep on running in a loop.  For example, looking at a particular task:
```
test/boost/sstable_compaction_test.cc(3998): Entering test case "max_ongoing_compaction_test"
...
random-seed=2947374100
```

```
DEBUG 2024-04-11 15:59:58,894 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
DEBUG 2024-04-11 15:59:58,894 [shard 0:main] compaction - [0x60b000013248] Going to compact 1 expired sstables
DEBUG 2024-04-11 16:00:04,701 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
DEBUG 2024-04-11 16:00:04,701 [shard 0:main] compaction - [0x60b000013248] Going to compact 4 non-expired sstables
DEBUG 2024-04-11 16:00:04,705 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
DEBUG 2024-04-11 16:00:04,706 [shard 0:main] compaction - [0x60b000013248] Going to compact 4 non-expired sstables
DEBUG 2024-04-11 16:00:04,725 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
DEBUG 2024-04-11 16:00:04,726 [shard 0:main] compaction - [0x60b000013248] Going to compact 4 non-expired sstables
DEBUG 2024-04-11 16:00:04,757 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
DEBUG 2024-04-11 16:00:04,757 [shard 0:main] compaction - [0x60b000013248] Going to compact 0 non-expired sstables
DEBUG 2024-04-11 16:00:04,807 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
DEBUG 2024-04-11 16:00:04,807 [shard 0:main] compaction - [0x60b000013248] Going to compact 0 non-expired sstables
...
```

I'm compressing the log and will upload to uploads.scylladb.com.
Also trying to see if it's reproducible with the same seed.

**Comment by raphaelsc** [comment]
> Timed out again with 25GB log file in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7959/testReport/junit/boost.sstable_compaction_test.max_ongoing_compaction_test.3.xunit/xml/Tests___Unit_Tests____empty_/ It looks like compaction tasks just keep on running in a loop. For example, looking at a particular task:
> 
> ```
> test/boost/sstable_compaction_test.cc(3998): Entering test case "max_ongoing_compaction_test"
> ...
> random-seed=2947374100
> ```
> 
> ```
> DEBUG 2024-04-11 15:59:58,894 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
> DEBUG 2024-04-11 15:59:58,894 [shard 0:main] compaction - [0x60b000013248] Going to compact 1 expired sstables
> DEBUG 2024-04-11 16:00:04,701 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
> DEBUG 2024-04-11 16:00:04,701 [shard 0:main] compaction - [0x60b000013248] Going to compact 4 non-expired sstables
> DEBUG 2024-04-11 16:00:04,705 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
> DEBUG 2024-04-11 16:00:04,706 [shard 0:main] compaction - [0x60b000013248] Going to compact 4 non-expired sstables
> DEBUG 2024-04-11 16:00:04,725 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
> DEBUG 2024-04-11 16:00:04,726 [shard 0:main] compaction - [0x60b000013248] Going to compact 4 non-expired sstables
> DEBUG 2024-04-11 16:00:04,757 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
> DEBUG 2024-04-11 16:00:04,757 [shard 0:main] compaction - [0x60b000013248] Going to compact 0 non-expired sstables
> DEBUG 2024-04-11 16:00:04,807 [shard 0:main] compaction - [0x60b000013248] TWCS expired check sufficiently far in the past, checking for fully expired SSTables
> DEBUG 2024-04-11 16:00:04,807 [shard 0:main] compaction - [0x60b000013248] Going to compact 0 non-expired sstables
> ...
> ```
> 
> I'm compressing the log and will upload to uploads.scylladb.com. Also trying to see if it's reproducible with the same seed.

Thanks, the logs are shedding good light on it, I have an idea of what's going on.

**Comment by bhalevy** [comment]
I've uploaded the log file to gs://upload.scylladb.com/b3e2af63-01f3-48e1-a2da-615ccc6331c6/max_ongoing_compaction_test.txt.xz
And FWIW, it doesn't reproduce for me on the first try with the above seed neither in dev nor in debug mode.

**Comment by raphaelsc** [comment]
> One more https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8117/consoleFull

Will jump on it, sorry for this annoyance

**Comment by benipeled** [comment]
Similar failure in 2023.1 (without the xxG log file)

https://jenkins.scylladb.com/job/enterprise-2023.1/job/next/340/artifact/testlog/x86_64/debug/boost.sstable_compaction_test.max_ongoing_compaction_test.2.log/*view*/

**Comment by tchaikov** [comment]
spotted again, 11.02 GiB log file this time. see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10133/
