### ISSUE TITLE
api: /compaction_manager/metrics/pending_tasks_by_table is unsafe against concurrent table set modification

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#13290]
It iterates over tables using `do_for_each(db.get_column_families(), ...`. 

database::get_column_families() returns a direct reference to the unordered_map used to hold column families: 

```
std::unordered_map<table_id, lw_shared_ptr<column_family>>& get_column_families() {
        return _column_families;
}
```
If the iteration is preempted and the table set is modified, iterators in the map may get invalidated and do_for_each() will hit undefined behavior.

**Comment by mykaul** [comment]
@Deexie - is that something in your domain?

**Comment by Deexie** [comment]
I will take a look.

**Comment by denesb** [comment]
@Deexie do we need to backport this to 5.2?

**Comment by Deexie** [comment]
> @Deexie do we need to backport this to 5.2?

Yes, we do

**Comment by Deexie** [comment]
> This is a pretty big change. Are there other known users of the unsafe interface, other than the task api?

Actually task api does not use it. And in 5.2 `get_column_families()` is used in approximately the same files
