### ISSUE TITLE
[p1] Enforce CompleteMultipartUpload usage

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13320]
S3 upload sink sends Complete message on flush(). This heavily uses the fact that sstables layer flushes the output stream once -- before closing (*), i.e. the stream usage pattern is like

```
for (...)
    write()
flush()
close()
```

The sstables layer respects this "contract" because file output stream may assert if flush happens to be in the middle of writes.

The S3 upload sink should be restricted not to allow more writes after a flush, otherwise it can silently lose the data.

(*) sending Complete on close() is bad, as sending may fail and failing close is no-go.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
