### ISSUE TITLE
Alternator/rest api python tests makes name assumptions that break "other" source tree

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylladb#13332]
`test_storage_service_keyspaces` and `test_fetch_from_system_tables` assumes all and only system keyspaces are prefixed with "system". For enterprise this is not true with replicated provider (though it probably should be, but historical reasons etc). 
These tests used to pass since they would normally run in a universe where these keyspaces are not created, but since having to move to actually init this keyspace early they suddenly cause test failures.

**Comment by avikivity** [comment]
This is a very old test (4.1). Does the fix need backports? What triggered the bug? I see "since having to move to actually init this keyspace early", is there a commit hash for it?

I expect we don't need to backport, but making sure.

**Comment by elcallio** [comment]
No, it should not need backport, as it only really broke things in enterprise, and at that in those forced to do unconditional early init of replicated provider KS/CF.
