### ISSUE TITLE
doc: remove irrelevant info about previous releases from the Raft docs

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#13345]
https://docs.scylladb.com/stable/architecture/raft.html

The page about Raft includes information about previous releases irrelevant in version 5.2. The information should be removed in master and branch-5.2.

Origin: https://github.com/scylladb/scylladb/pull/13292#issue-1637181621

**Comment by avikivity** [comment]
Already backported by @denesb. Please remember to clear the backport candidate label.
