### ISSUE TITLE
ScyllaDB NTP setup - support latest Amazon NTP instructions (internal source, etc.)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#13344]
See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service-ubuntu

It should be using 169.254.169.123 IP address, instead of 1.amazon.pool.ntp.org and such (if I'm reading https://github.com/scylladb/scylladb/blob/c7131a05741da13c96612da6223b90f914b6b7ee/dist/common/scripts/scylla_ntp_setup#L91 correctly) for IPv4 (and fd00:ec2::123 for IPv6)

The advantage is that it won't be using DNS and it'll be a single hop

For backup, it should go to time.aws.com

So in chrony, I'd expect to see something like:
```
server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4
```
and
```
pool time.aws.com iburst
```
only.

**Comment by yaronkaikov** [comment]
@mykaul It seems we do configure it with `169.254.169.123` Address.
This is from the latest master AMI:
```
scyllaadm@ip-10-0-4-7:/etc$ chronyc sources
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
^* 169.254.169.123               3   4   377     1    +17us[  +20us] +/-  487us
^- prod-ntp-3.ntp1.ps5.cano>     2   6    77    33   +625us[ +632us] +/-   42ms
^- pugot.canonical.com           2   6    77    35   -175us[ -167us] +/-   69ms
^- prod-ntp-4.ntp1.ps5.cano>     2   6    77    35   +404us[ +411us] +/-   41ms
^- prod-ntp-5.ntp4.ps5.cano>     2   6    77    34   -621us[ -613us] +/-   41ms
^- ns2.iu13.org                  2   6    77    34  -3193us[-3185us] +/-   15ms
^- ip148.ip-15-204-21.us         2   6    77    34   +179us[ +187us] +/-   72ms
^- ntp05.cymru.com               2   6    77    36    -12ms[  -12ms] +/-   40ms
^- gcbbs.net                     2   6    77    34    -79us[  -71us] +/-   36ms
```

**Comment by mykaul** [comment]
> @mykaul It seems we do configure it with `169.254.169.123` Address. This is from the latest master AMI:
> 
> ```
> scyllaadm@ip-10-0-4-7:/etc$ chronyc sources
> MS Name/IP address         Stratum Poll Reach LastRx Last sample               
> ===============================================================================
> ^* 169.254.169.123               3   4   377     1    +17us[  +20us] +/-  487us
> ^- prod-ntp-3.ntp1.ps5.cano>     2   6    77    33   +625us[ +632us] +/-   42ms
> ^- pugot.canonical.com           2   6    77    35   -175us[ -167us] +/-   69ms
> ^- prod-ntp-4.ntp1.ps5.cano>     2   6    77    35   +404us[ +411us] +/-   41ms
> ^- prod-ntp-5.ntp4.ps5.cano>     2   6    77    34   -621us[ -613us] +/-   41ms
> ^- ns2.iu13.org                  2   6    77    34  -3193us[-3185us] +/-   15ms
> ^- ip148.ip-15-204-21.us         2   6    77    34   +179us[ +187us] +/-   72ms
> ^- ntp05.cymru.com               2   6    77    36    -12ms[  -12ms] +/-   40ms
> ^- gcbbs.net                     2   6    77    34    -79us[  -71us] +/-   36ms
> ```

We should not have so many sources. Something is not properly configured. It looks like configurations are appended perhaps?
Specifically, note that they all have lower stratum than 169.x...

**Comment by yaronkaikov** [comment]
It seems that this configuration is coming from us (you mention the link in the description), not sure why we are doing it, maybe @syuu1228 knows. 

In any case `/etc/chrony/conf.d/00-cpc.conf` contains the default setting. when i replaced it with the one we are creating and restart the service i have:
```
scyllaadm@ip-10-0-4-178:/etc/chrony$ chronyc sources
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
^* 169.254.169.123               3   4    17     6  -1309ns[-5974ns] +/-  494us
```
