### ISSUE TITLE
Stress failed after replacing dead node

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#13379]
## Issue description

- [ ] This issue is a regression.
- [X] It is unknown if this issue is a regression.

Recently we changed set/order of nemesis we run, and we started to receive errors like:
```
2023-03-29 12:02:01.242: (CassandraStressLogEvent Severity.CRITICAL) period_type=one-time event_id=7cbaacad-ba6d-4591-a75e-2c5b265f613b during_nemesis=DestroyDataThenRepair: type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=15047 node=Node longevity-10gb-3h-master-loader-node-999db2e0-eastus-1 [74.235.173.157 | 10.0.0.11] (seed: False)
java.io.IOException: Operation x10 on key(s) [4e4b4e304b3134343830]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (3 responses were required but only 2 replica responded, 1 failed)
```
Which is incorrect - 2 responses should be required (failed replica is due test stopped one node).
One remark, on Azure its quite common for newly created node to get IP address like previously terminated one (this is just a clue, don't know if it is the reason). I tracked this kind of errors in historical runs - there were several examples of it, but it was rare (in all the cases terminate/replace/grow/shrink cluster were involved at some moment).

## Impact

Quorum queries fail when 1 node is down (for rf=3).

## How frequently does it reproduce?

Happened today for 2 jobs (oss master and enterprise master)

## Installation details

Kernel Version: 5.15.0-1035-azure
Scylla version (or git commit hash): `5.3.0~dev-20230329.6525209983d1` with build-id `da8cde2a3d8c048a3a15dfd19fd14dd535fec6d1`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-999db2e0-eastus-8 (74.235.39.143 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-999db2e0-eastus-7 (40.76.41.134 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-999db2e0-eastus-6 (74.235.173.90 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-999db2e0-eastus-5 (74.235.173.70 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-999db2e0-eastus-4 (74.235.173.66 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-999db2e0-eastus-3 (74.235.173.52 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-999db2e0-eastus-2 (74.235.173.35 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-999db2e0-eastus-1 (74.235.173.23 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.3.0-dev-x86_64-2023-03-29T09-23-04` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `999db2e0-2c7e-466d-957f-38e11782ed0b`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0db766261e239b80335c0517e98b959998aedca6/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 999db2e0-2c7e-466d-957f-38e11782ed0b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=999db2e0-2c7e-466d-957f-38e11782ed0b)
- Show all stored logs command: `$ hydra investigate show-logs 999db2e0-2c7e-466d-957f-38e11782ed0b`

## Logs:
- **db-cluster-999db2e0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/db-cluster-999db2e0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/db-cluster-999db2e0.tar.gz)
- **sct-runner-events-999db2e0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/sct-runner-events-999db2e0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/sct-runner-events-999db2e0.tar.gz)
- **sct-999db2e0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/sct-999db2e0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/sct-999db2e0.log.tar.gz)
- **monitor-set-999db2e0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/monitor-set-999db2e0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/monitor-set-999db2e0.tar.gz)
- **loader-set-999db2e0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/loader-set-999db2e0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/loader-set-999db2e0.tar.gz)
- **parallel-timelines-report-999db2e0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/parallel-timelines-report-999db2e0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/999db2e0-2c7e-466d-957f-38e11782ed0b/20230329_121603/parallel-timelines-report-999db2e0.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/185/)
</details>

**Comment by mykaul** [comment]
Which replication strategy are you using?
What do you see on the server side logs?

**Comment by soyacz** [comment]
> Which replication strategy are you using? What do you see on the server side logs?

simple strategy, db logs are not showing anything special, quiet at this moment.

**Comment by mykaul** [comment]
> > Which replication strategy are you using? What do you see on the server side logs?
> 
> simple strategy, db logs are not showing anything special, quiet at this moment.

Errr... we should be getting rid of it, hopefully soon.

**Comment by gleb-cloudius** [comment]
Of course. There is nothing special in the error if it happens during a topology change.

**Comment by soyacz** [comment]
It happened ~7-8 minutes after completing topology change.

**Comment by soyacz** [comment]
Also it is not only related to Azure and reused ip's. I could find more instances of this error (even for 4.4, before that I have no track record), but looks recently it happens more often (especially on Azure).

**Comment by gleb-cloudius** [comment]
I see in the event log replace event much closer to the error:

```
t:2023-03-29 12:01:33,428 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-03-29 12:01:33.404: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=6b5f0140-ac46-41b8-a5c9-8d2de8c8a857: nemesis_name=DrainKubernetesNodeThenReplaceScyllaNode target_node=Node longevity-10gb-3h-master-db-node-999db2e0-eastus-6 [74.235.173.90 | 10.0.0.10] (seed: False)
```

There is also no node in the cluster with ip `10.0.0.11` so it is not clear why is it in the error message you posted. In the loader log I see `3 responses were required but only 2 replica responded, 1 failed` errors are starting at the time the nemesis above runs.

**Comment by soyacz** [comment]
> DrainKubernetesNodeThenReplaceScyllaNode

this one is skipped - test is not k8s based.

`10.0.0.11` - this is loader node ip.

`3 responses were required but only 2 replica responded, 1 failed` error happened after taking node down during `disrupt_destroy_data_then_repair` and looks this was only node that was down during this error.

**Comment by roydahan** [comment]
3 nodes are required for RF=3 happens while adding a node.

@soyacz please check if it was during a nemesis and which part of the nemesis.
Please check that we didn't have time skew of the events in SCT log (compare the actual time of message).

If not sure, run a reproducer with the relevant/suspected nemesis.

Regarding Azure, please check if it's related somehow to the "reboot issue" that we can't control its exact time.

**Comment by soyacz** [comment]
> 3 nodes are required for RF=3 happens while adding a node.
> 
> @soyacz please check if it was during a nemesis and which part of the nemesis. Please check that we didn't have time skew of the events in SCT log (compare the actual time of message).

This happened during `disrupt_destroy_data_then_repair` on the beginning, when test took one node down. 10m after grow-shrink cluster nemesis which I suspect as the culprit of this issue. No time skew of the events.

> 
> If not sure, run a reproducer with the relevant/suspected nemesis.

This reproduces in Azure tests on master, on 5.2/2023.1 not reproduced (but nemesis set is different)

> 
> Regarding Azure, please check if it's related somehow to the "reboot issue" that we can't control its exact time.

I don't think it's related to reboot, unless vm's termination has also some issue and cluster somehow is still aware of the node (nodetool status is not showing it, there's 6 nodes).

New reproduction, different nemesis set,  after `disrupt_terminate_and_replace_node` (again around 10m after it, when 1 node got down):

## Installation details

Kernel Version: 5.15.0-1035-azure
Scylla version (or git commit hash): `5.3.0~dev-20230415.1da02706ddb8` with build-id `f7ac5cd90e63ace5065c583d6d1d9c381f39b5c2`




Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-9 (4.236.135.69 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-8 (20.172.239.126 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-7 (20.124.192.224 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-6 (52.147.206.146 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-5 (52.147.203.53 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-4 (4.236.142.193 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-3 (52.147.206.145 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-2 (52.149.151.7 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-10 (20.163.223.80 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-master-db-node-60a8b4f0-eastus-1 (74.235.213.177 | 10.0.0.5) (shards: 7)


OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.3.0-dev-x86_64-2023-04-15T09-37-43` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `60a8b4f0-13f9-4bff-93e8-64579883dff6`
Test name: `scylla-master/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ff477556b85d35096ab56c744b880dc96c0d82ca/test-cases/longevity/longevity-10gb-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 60a8b4f0-13f9-4bff-93e8-64579883dff6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=60a8b4f0-13f9-4bff-93e8-64579883dff6)
- Show all stored logs command: `$ hydra investigate show-logs 60a8b4f0-13f9-4bff-93e8-64579883dff6`


## Logs:
- **db-cluster-60a8b4f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/db-cluster-60a8b4f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/db-cluster-60a8b4f0.tar.gz)
- **sct-runner-events-60a8b4f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/sct-runner-events-60a8b4f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/sct-runner-events-60a8b4f0.tar.gz)
- **sct-60a8b4f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/sct-60a8b4f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/sct-60a8b4f0.log.tar.gz)
- **monitor-set-60a8b4f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/monitor-set-60a8b4f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/monitor-set-60a8b4f0.tar.gz)
- **loader-set-60a8b4f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/loader-set-60a8b4f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/loader-set-60a8b4f0.tar.gz)
- **parallel-timelines-report-60a8b4f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/parallel-timelines-report-60a8b4f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60a8b4f0-13f9-4bff-93e8-64579883dff6/20230415_114054/parallel-timelines-report-60a8b4f0.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-10gb-3h-azure-test/189/)
</details>

**Comment by roydahan** [comment]
@soyacz what's the minimal reproducer we need here?
replace node then something else?
we need to better understand this issue, to make sure it's not a blocker.

**Comment by soyacz** [comment]
@roydahan my suspect is `disrupt_terminate_and_replace_node` - from all runs this error happened when getting down one node after this nemesis. I'll try with this single nemesis on master to see if it reproduces.

**Comment by roydahan** [comment]
@ShlomiBalalis has a reproducer as part of https://github.com/scylladb/scylla-enterprise/issues/2852, probably a dup.
(Replacing a node that gets the same IP as the previous node and then sometime later stopping it)

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis has a reproducer as part of [scylladb/scylla-enterprise#2852](https://github.com/scylladb/scylla-enterprise/issues/2852), probably a dup. (Replacing a node that gets the same IP as the previous node and then sometime later stopping it)

See https://github.com/scylladb/scylla-dtest/pull/3126

**Comment by roydahan** [comment]
@soyacz please provide information from a recent reproducer.
Again, the "require 3 while QUORUM" is not the real problem here in case it happens when it should happen (there are several cases).

**Comment by soyacz** [comment]
> @soyacz please provide information from a recent reproducer. Again, the "require 3 while QUORUM" is not the real problem here in case it happens when it should happen (there are several cases).

Last reproduction happened on 2023-04-26, after that https://github.com/scylladb/scylladb/commit/a8040306bba37d2aa8f69dee4f3a5ddc952b13bc was merged and this issue is not showing up anymore.

I think it can be closed.
