### ISSUE TITLE
Use-after-move in virtual table for secondary indexes

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#13396]
That's courtersy of https://github.com/raphaelsc/seastar/commit/153813d3b88f284fe135c8ac3c00d6777faad276.

Report:
./index/built_indexes_virtual_reader.hh:228:40: warning: invalid invocation of method 'operator->' on object 's' while it is in the 'consumed' state [-Wconsumed]
                _db.find_column_family(s->ks_name(), system_keyspace::v3::BUILT_VIEWS),

**Comment by avikivity** [comment]
Backported to 5.1, 5.2.
