### ISSUE TITLE
Use-after-move when tracking view builder progress

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#13395]
That's courtersy of https://github.com/raphaelsc/seastar/commit/153813d3b88f284fe135c8ac3c00d6777faad276.

Report:
In file included from db/system_keyspace.cc:51:
./db/view/build_progress_virtual_reader.hh:202:40: warning: invalid invocation of method 'operator->' on object 's' while it is in the 'consumed' state [-Wconsumed]
                _db.find_column_family(s->ks_name(), system_keyspace::v3::SCYLLA_VIEWS_BUILDS_IN_PROGRESS),

**Comment by avikivity** [comment]
Backported to 5.1, 5.2.
