### ISSUE TITLE
Use-after-move when reading from SSTable in reverse

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#13394]
That's courtersy of https://github.com/raphaelsc/seastar/commit/153813d3b88f284fe135c8ac3c00d6777faad276.

Report:
sstables/mx/reader.cc:1705:58: error: invalid invocation of method 'operator*' on object 'schema' while it is in the 'consumed' state [-Werror,-Wconsumed]
            legacy_reverse_slice_to_native_reverse_slice(*schema, slice.get()), pc, std::move(trace_state), fwd, fwd_mr, monitor);

**Comment by avikivity** [comment]
Backported to 5.1, 5.2.
