### ISSUE TITLE
make sure readers are closed around their use in a seastar thread

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13406]
As seen in https://github.com/scylladb/scylla-enterprise/issues/2786#issuecomment-1490046781
we have a pattern of using flat mutation readers in a seastar thread where the reader is moved to a lambda capture
and then the lambda function has uses a deferred_close to close the reader, like in https://github.com/scylladb/scylladb/blob/207dcbb8fa6bc679298c424366f89f0f226c3abb/sstables/sstables.cc#L1832-L1833

The problem here is that `seastar::async` may throw, destroying the reader without closing it first.

We can wrap the seastar::async call with `with_closeable(std::move(reader)` to deal with that.

**Comment by michoecho** [comment]
I'm closing the issue and the corresponding PR then. The entire issue is mostly cosmetic anyway (if a bad_alloc in seastar::async happens, the node is most likely dying anyway), so there is no point backporting anything for it either.
