### ISSUE TITLE
db/view: update view generator doesn't close staging sstable reader on exceptions

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#13413]
When exception is thrown during reading sstable it will be retried later, but reader should be closed properly (although I am not sure what are the consequences of not doing it)

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to all 5.x

**Comment by denesb** [comment]
> @scylladb/scylla-maint please consider backport to all 5.x

On it.

**Comment by denesb** [comment]
Done.
