### ISSUE TITLE
artifacts offline installation failed because openjdk-11 is not istalled

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#13414]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

installation of ScyllaDB on a fresh Ubuntu22 fails, because apparently depency is not met.

```
2023-04-02 07:04:36.443: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=a373afe8-a00f-4c33-97f2-8d48c9b4aaf8, source=ArtifactsTest.SetUp()
exception=[Node artifacts-ubuntu2204-jenkins-db-node-c1bf1abb-0-1 [34.148.14.176 | 10.142.0.129] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ntar xvfz ./unified_package.tar.gz\ncd ./scylla-*\n./install.sh --housekeeping\ncd -\nrm -f /tmp/scylla.yaml\n"'
Exit code: 1
Stdout:
scylla-5.3.0~dev/install.sh
scylla-5.3.0~dev/uninstall.sh
fs.aio-max-nr = 30000000
fs.file-max = 9223372036854775807
fs.nr_open = 1073741816
fs.inotify.max_user_instances = 1200
kernel.sched_autogroup_enabled = 0
kernel.numa_balancing = 0
vm.swappiness = 1
Scylla offline install completed.
Stderr:
+ tar xvfz ./unified_package.tar.gz
+ cd ./scylla-5.3.0~dev
+ ./install.sh --housekeeping
sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_min_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_wakeup_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_latency_ns: No such file or directory
dpkg-query: package 'openjdk-11-jre-headless' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 3640, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 4291, in node_setup
self._scylla_install(node)
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 4370, in _scylla_install
node.offline_install_scylla(unified_package=self.params.get('unified_package'),
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 2062, in offline_install_scylla
self.remoter.run('sudo bash -cxe "%s"' % install_cmds)
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo bash -cxe "\ntar xvfz ./unified_package.tar.gz\ncd ./scylla-*\n./install.sh --housekeeping\ncd -\nrm -f /tmp/scylla.yaml\n"'
Exit code: 1
Stdout:
scylla-5.3.0~dev/install.sh
scylla-5.3.0~dev/uninstall.sh
fs.aio-max-nr = 30000000
fs.file-max = 9223372036854775807
fs.nr_open = 1073741816
fs.inotify.max_user_instances = 1200
kernel.sched_autogroup_enabled = 0
kernel.numa_balancing = 0
vm.swappiness = 1
Scylla offline install completed.
Stderr:
+ tar xvfz ./unified_package.tar.gz
+ cd ./scylla-5.3.0~dev
+ ./install.sh --housekeeping
sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_min_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_wakeup_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_latency_ns: No such file or directory
dpkg-query: package 'openjdk-11-jre-headless' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
```

## How frequently does it reproduce?

last 2 runs of this same job

## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-ubuntu2204-jenkins-db-node-c1bf1abb-0-1 (34.148.14.176 | 10.142.0.129) (shards: 2)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts` (gce: us-east1)

Test: `artifacts-ubuntu2204-test`
Test id: `c1bf1abb-f908-4f59-a490-4ab3a2b29d93`
Test name: `scylla-master/artifacts-offline-install/artifacts-ubuntu2204-test`
Test config file(s):

- [ubuntu2204.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a317398419d94861af4e5fdf7b945c7655d4cc77/test-cases/artifacts/ubuntu2204.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c1bf1abb-f908-4f59-a490-4ab3a2b29d93`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c1bf1abb-f908-4f59-a490-4ab3a2b29d93)
- Show all stored logs command: `$ hydra investigate show-logs c1bf1abb-f908-4f59-a490-4ab3a2b29d93`

## Logs:
- **db-cluster-c1bf1abb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1bf1abb-f908-4f59-a490-4ab3a2b29d93/20230402_070501/db-cluster-c1bf1abb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1bf1abb-f908-4f59-a490-4ab3a2b29d93/20230402_070501/db-cluster-c1bf1abb.tar.gz)
- **sct-runner-events-c1bf1abb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1bf1abb-f908-4f59-a490-4ab3a2b29d93/20230402_070501/sct-runner-events-c1bf1abb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1bf1abb-f908-4f59-a490-4ab3a2b29d93/20230402_070501/sct-runner-events-c1bf1abb.tar.gz)
- **sct-c1bf1abb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c1bf1abb-f908-4f59-a490-4ab3a2b29d93/20230402_070501/sct-c1bf1abb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c1bf1abb-f908-4f59-a490-4ab3a2b29d93/20230402_070501/sct-c1bf1abb.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-test/220/)
</details>

**Comment by fgelcer** [comment]
@yaronkaikov

**Comment by yaronkaikov** [comment]
@syuu1228 Can you please have a look on this?

**Comment by syuu1228** [comment]
Not reproduced on my side:
```
$ sudo ./install.sh --housekeeping
fs.aio-max-nr = 30000000
fs.file-max = 9223372036854775807
fs.nr_open = 1073741816
fs.inotify.max_user_instances = 1200
sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_min_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_wakeup_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_latency_ns: No such file or directory
kernel.sched_autogroup_enabled = 0
kernel.numa_balancing = 0
vm.swappiness = 1
Scylla offline install completed.
```

Also, we don't run `dpkg-query` on install.sh. but scylla-cluster-tests does.
So it likely the test problem.
```
$ grep dpkg install.sh scylla-tools/install.sh 
$ 

$ grep dpkg-query -r .
./sdcm/cluster.py:            cmd = 'dpkg-query --show'
./sdcm/cluster.py:            result = self.remoter.run(f'dpkg-query --show {self.scylla_pkg()}', verbose=False, ignore_status=True)
./sdcm/cluster.py:            cmd = f"dpkg-query --show --showformat '${{Version}}' {self.scylla_pkg()}"
./sdcm/cluster.py:            cmd = "dpkg-query --show 'scylla*'"
./sdcm/provision/common/utils.py:            if dpkg-query --show syslog-ng ; then
./sdcm/provision/common/utils.py:                    if dpkg-query --show syslog-ng ; then
grep: ./sdcm/provision/common/__pycache__/utils.cpython-310.pyc: binary file matches
grep: ./sdcm/__pycache__/cluster.cpython-310.pyc: binary file matches
grep: ./unit_tests/__pycache__/test_cluster.cpython-310-pytest-6.2.5.pyc: binary file matches
./unit_tests/test_cluster.py:            ("dpkg-query --show --showformat '${Version}' scylla", (0, "3.3~rc1-0.20200209.0d0c1d43188-1", "")),
./unit_tests/test_cluster.py:            ("dpkg-query --show --showformat '${Version}' scylla",
./unit_tests/test_cluster.py:             (1, "", "dpkg-query: no packages found matching scylla\n")),
./unit_tests/test_cluster.py:            ("dpkg-query --show --showformat '${Version}' scylla",
./unit_tests/test_cluster.py:             (1, "", "dpkg-query: no packages found matching scylla\n")),
```

**Comment by DoronArazii** [comment]
@yaronkaikov ping

**Comment by yaronkaikov** [comment]
> May be related to #13356 and friends? (update dbuild?, etc.)

:+1: Thanks @mykaul This seems to be the root cause of this regression, verified with https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/byo_build_tests_dtest/1768/ (with revert to https://github.com/scylladb/scylladb/pull/13356/commits/2c4f6f19c876c778446ea8ba8410877891792527) , then tried to run the failing test (https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/artifacts-offline-install/job/artifacts-ubuntu2204-test/25/) which passed the problematic section. @tchaikov  Can you please have a look?

**Comment by tchaikov** [comment]
- [ ] https://github.com/scylladb/scylla-jmx/pull/198
- [ ] https://github.com/scylladb/scylla-cluster-tests/pull/5994

**Comment by tchaikov** [comment]
> Not reproduced on my side:
> 
> ```
> $ sudo ./install.sh --housekeeping
> fs.aio-max-nr = 30000000
> fs.file-max = 9223372036854775807
> fs.nr_open = 1073741816
> fs.inotify.max_user_instances = 1200
> sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
> sysctl: cannot stat /proc/sys/kernel/sched_min_granularity_ns: No such file or directory
> sysctl: cannot stat /proc/sys/kernel/sched_wakeup_granularity_ns: No such file or directory
> sysctl: cannot stat /proc/sys/kernel/sched_latency_ns: No such file or directory
> kernel.sched_autogroup_enabled = 0
> kernel.numa_balancing = 0
> vm.swappiness = 1
> Scylla offline install completed.
> ```
> 
> Also, we don't run `dpkg-query` on install.sh. but scylla-cluster-tests does. So it likely the test problem.
> 
> ```
> $ cd scylla-5.3.0~dev
> $ grep dpkg install.sh scylla-tools/install.sh 
> $ 
> 
> $ cd ~/scylla-cluster-tests
> $ grep dpkg-query -r .
> ./sdcm/cluster.py:            cmd = 'dpkg-query --show'
> ./sdcm/cluster.py:            result = self.remoter.run(f'dpkg-query --show {self.scylla_pkg()}', verbose=False, ignore_status=True)
> ./sdcm/cluster.py:            cmd = f"dpkg-query --show --showformat '${{Version}}' {self.scylla_pkg()}"
> ./sdcm/cluster.py:            cmd = "dpkg-query --show 'scylla*'"
> ./sdcm/provision/common/utils.py:            if dpkg-query --show syslog-ng ; then
> ./sdcm/provision/common/utils.py:                    if dpkg-query --show syslog-ng ; then
> grep: ./sdcm/provision/common/__pycache__/utils.cpython-310.pyc: binary file matches
> grep: ./sdcm/__pycache__/cluster.cpython-310.pyc: binary file matches
> grep: ./unit_tests/__pycache__/test_cluster.cpython-310-pytest-6.2.5.pyc: binary file matches
> ./unit_tests/test_cluster.py:            ("dpkg-query --show --showformat '${Version}' scylla", (0, "3.3~rc1-0.20200209.0d0c1d43188-1", "")),
> ./unit_tests/test_cluster.py:            ("dpkg-query --show --showformat '${Version}' scylla",
> ./unit_tests/test_cluster.py:             (1, "", "dpkg-query: no packages found matching scylla\n")),
> ./unit_tests/test_cluster.py:            ("dpkg-query --show --showformat '${Version}' scylla",
> ./unit_tests/test_cluster.py:             (1, "", "dpkg-query: no packages found matching scylla\n")),
> ```

@syuu1228 , hi Takuya, i think it was indeed `install.sh` which failed.  in https://github.com/scylladb/scylladb/blob/7a05cc3a06ff6acef3798ae042ed000243b6ba37/unified/install.sh#L179, https://github.com/scylladb/scylla-jmx/blob/master/install.sh is called, where we have https://github.com/scylladb/scylla-jmx/blob/48e16998d92965efe9e7e311e5ad15de6bfdb497/install.sh#L95 . so, if `dpkg -L` cannot find the package being queried in the ubuntu system, it fails with the error message quoted above, like
```
dpkg-query: package 'openjdk-11-jre-headless' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
```

i am trying to fix it in https://github.com/scylladb/scylla-jmx/pull/198 . sorry for the regression.
