### ISSUE TITLE
need to bump up tools/jmx

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#13418]
we've been seeing crashes in JVM shipped along with openjdk-8, see https://github.com/scylladb/scylla-jmx/issues/194 . the error message is attached here for SEO:

```
ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-5.2/dtest-daily-release/scylla/.ccm/scylla-repository/908a82bea064f54318d4dc4e5dcd67e6f2f10b8b/share/cassandra/bin/nodetool -h 127.0.42.4 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy info exited with non-zero status; exit status: 1; 
stderr: nodetool: Failed to connect to '127.0.42.4:7199' - ConnectException: 'Connection refused (Connection refused)'.
```

tools/jmx now includes the change switching from openjdk-8 to openjdk-11 to alleviate this pain. and scylladb master HEAD also includes a change bumping up the tools/jmx submodule. but unfortunately, we failed to create an issue on scylladb side to track the fix, and to associate the PR with it.

so, here is the belated issue for tracking the backports of https://github.com/scylladb/scylladb/pull/13356

**Comment by mykaul** [comment]
I think https://github.com/scylladb/scylladb/pull/13356 was missing the 'Backport candidate' label for some reason.

**Comment by tchaikov** [comment]
> I think #13356 was missing the 'Backport candidate' label for some reason.

@mykaul hi Yaniv, thanks for adding that label. i think it's my fault not adding "Branches"  and "Fixes" tags in the cover letter.

**Comment by nyh** [comment]
> I think #13356 was missing the 'Backport candidate' label for some reason.

https://github.com/scylladb/scylladb/pull/13356 is a pull request, not an issue - so it shouldn't get a backport candidate tag. An issue should get this tag, and I guess the purpose of this issue was to do this. Unfortunately, the commit - 
https://github.com/scylladb/scylladb/commit/dfb55975fc2ea20309f5f56ab32dab2bcce51c49 - didn't say it "fixes" this issue so this issue wasn't closed. I'll do it now and add the backport candidate tag to it.

**Comment by denesb** [comment]
Do we nee to backport this to 5.2?

**Comment by mykaul** [comment]
> Do we nee to backport this to 5.2?

I think the move from Java 8 to Java 11 is too big of a change to backport.
