### ISSUE TITLE
[p0] Object storage: Implement authentication support

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13425]
So far all the testing had been happening over minio with pulically configured bucket. On "real" AWS there seem to be a fundamental obstacle:

```
$ curl -X POST 'https://xemul.s3.amazonaws.com/foo?uploads'
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Anonymous users cannot initiate multipart uploads.  Please authenticate.</Message><RequestId>...</RequestId><HostId>...</HostId></Error>
```

It's not possible to initiate multipart upload anonymously, all the more so plain anonymous PUT works (with the policy config below)

@mykaul , maybe you have some knowledge how to allow anonymous multipart access?

policy file:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicAccess",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "*",
            "Resource": [
                "arn:aws:s3:::BUCKETNAME",
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        }
    ]
}
```

**Comment by mykaul** [comment]
I'm afraid not - I've never done anything with an anonymous user. Always authenticated + encrypted.

**Comment by avikivity** [comment]
Not a bug, not backporting.
