### ISSUE TITLE
SSTable set is left uncompacted post off-strategy compaction completion

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#13429]
When off-strategy compaction completes, regular compaction is not triggered. If off-strategy output causes the table's SSTable set to not conform the compaction strategy goal, it means that read and space amplification will be suboptimal until the next compaction kicks in, which can take undefinite amount of time (e.g. when active memtable is flushed).

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to 2022.1 / 2022.2 / 2023.1 ^^

**Comment by denesb** [comment]
I backported to 5.2, there were some conflicts but they were simple to resolve.
But starting with 5.1 the conflicts are more involved, @raphaelsc please prepare backport PRs for 5.1. and 5.0.

**Comment by DoronArazii** [comment]
@raphaelsc ping ^^
