### ISSUE TITLE
CQL compression might cause reactor stalls on buffer allocation

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#13437]
Compression libraries operate on contiguous buffers. We sometimes compress large chunks of data, which causes a need for large contiguous buffers, which are problematic for the allocator.

The allocator impact can be minimized by reusing buffers. This is the case e.g. for out CQL frame compression routines.
However, as proven by https://github.com/scylladb/scylla-enterprise/issues/2694, this reuse isn't aggressive enough — even if the buffers could be reused perfectly, they are periodically reallocated (once per 100000 uses) anyway, often enough for the resulting stalls to be worrisome.

**Comment by avikivity** [comment]
Not backporting, performance only and not a regression.
