### ISSUE TITLE
Compaction manager "periodic reevaluation" is one-off

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#13430]
The manager intended to periodically reevaluate compaction need for each registered table. But it's not working as intended. The reevaluation is one-off.

This means that compaction was not kicking in later for a table, with low to none write activity, that had expired data 1 hour from now.

**Comment by mykaul** [comment]
@raphaelsc - do we need a backport to 5.1, 5.0 ?

**Comment by avikivity** [comment]
@denesb I see you backported to 5.2, but why not to 5.1 too?

**Comment by raphaelsc** [comment]
> @denesb I see you backported to 5.2, but why not to 5.1 too?

I need to resolve a conflict. Will do it early this week

**Comment by DoronArazii** [comment]
Backported.
Removing label.
