### ISSUE TITLE
docs: Issue in page Scylla CQL Drivers - add Scylla Cloud support

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13453]
I would like to report an issue in page https://docs.scylladb.com/master/using-scylla/drivers/cql-drivers/index

### Problem

Its hard to understand which of the drivers support Scylla Cloud Serverless:
- Java
- Go
- Python
- Rust

**Comment by avikivity** [comment]
@annastuchlik should this be backported? a simple cherry-pick won't work.

**Comment by annastuchlik** [comment]
@avikivity I think the information added with this PR is not critical.
