### ISSUE TITLE
[p1] Implement S3 client concurrency control

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13458]
Currently S3 client doesn't control the amount of connections it spawns towards server. _Each_ "I need new socket" request from the http client is served instantly. This results in the whole lot of connections being in pool which, in turn, _seems to_ be causing S3 server to drop connections on the fly (scylla is reporting "transport endpoint not connected" exceptions when reading sstables on stress testing).

Said that -- it's better to make all S3 clients share the pool of connections and implement concurrency control in it not to overwhelm node and server with active connections. Likely will need a seastar::experimental::htttp::client patch too.

**Comment by raphaelsc** [comment]
when implementing the pool, we need to take into account the connection timeouts. use http keepalive?!

**Comment by xemul** [comment]
> use http keepalive?!

It's already the default for http::client
