### ISSUE TITLE
Compaction log messages should identify the compaction group

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13467]
The table layer performs compaction per-compaction group, for example:
https://github.com/scylladb/scylladb/blob/7a05cc3a06ff6acef3798ae042ed000243b6ba37/replica/table.cc#L1226-L1232
or
https://github.com/scylladb/scylladb/blob/7a05cc3a06ff6acef3798ae042ed000243b6ba37/replica/table.cc#L1271-L1280

But the log messages from compaction_manager and downwards do not identify the compaction_group/table_state they are working on.

It is interesting to know the compaction group token range, and in the future, the tablet_id.
(Cc @tgrabiec)

**Comment by raphaelsc** [comment]
It's indeed important. In the future, compaction group id should be the same as of the tablet.
