### ISSUE TITLE
Compaction shares are unnecessarily bumped during major compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#13487]
Commit 49892a06b9e688535, back in 2018, bumps the compaction shares by 200 to guarantee a minimum base line.

However, after commit e3f561db3180194b0925, major compaction runs in maintenance group meaning that bumping shares became completely irrelevant and only causes regular compaction to be unnecessarily more aggressive.

**Comment by raphaelsc** [comment]
FYI @bhalevy

**Comment by avikivity** [comment]
Not a regression, not backporting.
