### ISSUE TITLE
topology / group 0: store shard_count and ignore_msb in topology table

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13508]
Today every node is gossiping their shard_count and ignore_msb. We should move these values to the `topology` table. They are needed, for example, when creating CDC generations. In https://github.com/scylladb/scylladb/pull/13385 I add CDC generations management to the topology coordinator but I use hardcoded values for shard_count/ignore_msb and left a FIXME.

When a node joins or restarts and observes that its shard_count/ignore_msb has changed, it should update the information in group 0.

This should probably be done by a request to the topology coordinator instead of a direct update by the node - otherwise there's a potential for races (e.g. the coordinator decides to remove the node while the node tries to update its topology entry).

cc @gleb-cloudius @tgrabiec

**Comment by avikivity** [comment]
@kbr-scylla I expect this doesn't need to be backported, please confirm.

**Comment by kbr-scylla** [comment]
Confirmed
