### ISSUE TITLE
raft topology: impossible to enter RECOVERY mode when we require contacting quorum on restart

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13537]
With Raft topology we'll require to contact a quorum on node restart in some situations. For example in https://github.com/scylladb/scylladb/pull/13521 when we notice that our local shard count changes we'll update it in `system.topology` as part of the restarting process, which requires committing a command to group 0 and therefore a quorum to be available.

But that means if we permanently lose quorum, we won't be able to enter RECOVERY mode to re-create group 0 in a smaller cluster, because entering RECOVERY requires CQL to be available (it's done by writing a value to a local table).

Suggestions:
- make CQL for local tables available earlier
- make it possible to enter RECOVERY through a different API

cc @kostja @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> Local CQL should be available before group0. We have been trying to accomplish this for a while by now.

This, in itself, is a can of worms. What if even a local cql  depend on cluster's features (something about commitlog for instance) and we move features into the group0?

**Comment by gleb-cloudius** [comment]
> We should be able tor ead the local state of group0 before we fully boot. It is not a can of worms, it's a chicken-egg problem, and group0 local state is a good enough chicken which could give us the first egg.

Reading the local state is not enough for features since the decision about what features are enabled is global.

**Comment by kostja** [comment]
It is not enough to know the exact set of globally enabled features. However, it is enough to know some old enough subset, sufficient to drive the boot process up to the start of group0.

**Comment by gleb-cloudius** [comment]
On Mon, Apr 17, 2023 at 06:21:25AM -0700, Konstantin Osipov wrote:
> It is not enough to know the exact set of globally enabled features. However, it is enough to know some old enough subset, sufficient to drive the boot process up to the start of group0.
>

Consider a feature that adds a new local table (or it may be a virtual
table one can use to issue nodetools commands to a node). A node may
think that a feature is disabled after the crash, but the cluster
already enabled it. And the user (which may be a management app) thinks
it is enabled since he already used it while the node was down. If he
will issue a command to the node after it opened CQL port and before it
managed to synch with the leader the command will fail unexpectedly.

This is just one example, there may be others.

**Comment by kostja** [comment]
I agree, but I think it's a more general problem of opening CQL too early. Besides, we could make CQL available internally before opening it up.

**Comment by tgrabiec** [comment]
There was a suggestion to implement a maintenance mode which starts a server in isolated state: https://github.com/scylladb/scylladb/issues/5489

**Comment by kbr-scylla** [comment]
Note that the Raft recovery procedure uses `nodetool removenode` to remove nodes while in RECOVERY mode, so the nodes cannot be isolated from each other.

We could modify the procedure to work with such a maintenance mode though: the admin would have to remove a dead peer from every node (instead of just executing a single `nodetool removenode`).

**Comment by kbr-scylla** [comment]
> We could modify the procedure to work with such a maintenance mode though: the admin would have to remove a dead peer from every node (instead of just executing a single nodetool removenode).

This is strictly worse however, because `removenode` performs data streaming and this wouldn't do it.

Alternatively if we went with the maintenance mode route, we could tell each node: "when you restart after leaving maintenance, create a fresh group 0 but ignore these peers: ..."; after restart, group 0 is formed without the dead nodes but they are still part of the token ring. Then we can use `removenode` with group 0 to remove them from the token ring.

**Comment by mykaul** [comment]
I'm hoping/assuming maintenance mode is the solution to this - and that is going to be in 5.4 - but perhaps I'm too optimistic - shall we defer to 6.0?

**Comment by kbr-scylla** [comment]
@mykaul 5.4 has already been branched, and we don't backport features, only bugfixes. So it's not going to be in 5.4. Updating milestone.

**Comment by kbr-scylla** [comment]
Solved by maintenance mode https://github.com/scylladb/scylladb/pull/15346, closing.
