### ISSUE TITLE
reader_concurrency_semaphore: execution loop can stall

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#13540]
The execution loop consumes permits from the _ready_list and executes them. The _ready_list usually contains a single permit. When the _ready_list is not empty, new permits are queued until it becomes empty. The execution loops relies on admission checks triggered by the read releasing resouces, to bring in any queued read into the _ready_list, while it is executing the current read. But in some cases the current read might not free any resorces and thus fail to trigger an admission check and the currently queued permits will sit in the queue until another source triggers an admission check.
I don't yet know how this situation can occur, if at all, but it is reproducible with a simple unit test, so it is best to cover this corner-case in the off-chance it happens in the wild.

**Comment by avikivity** [comment]
@denesb I don't know if this deserves a backport. IIRC it can stall in synthetic circumstances, but we don't know how to create real ones.

**Comment by denesb** [comment]
> @denesb I don't know if this deserves a backport. IIRC it can stall in synthetic circumstances, but we don't know how to create real ones.

Yes, I am not sure this fixes a real problem. On the other hand the fix is very simple and on the off chance that we hit this, I don't think we'd know.

**Comment by avikivity** [comment]
As enough time passed, backported to 5.2. 5.4 had it.
