### ISSUE TITLE
docs: Issue in page Lightweight Transactions

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13578]
I would like to report an issue in page https://docs.scylladb.com/master/using-scylla/lwt

### Problem
The first lines of the document say the following about versions:

> New in version 3.2: Scylla Open Source (experimental)
>
> Changed in version 4.0: Scylla Open Source (production ready)
>
>In releases prior to Scylla 4.0 this feature is an experimental feature, to use it you must [enable the experimental status](https://docs.scylladb.com/master/operating-scylla/admin.html#yaml-enabling-experimental-features).

I think this is a very long premable - three paragraphs - that is hardly relevant since none of these versions are even supported.

###  Suggest a fix

I would replace the three paragraphs by one, like the following

> This feature was introduced in version 3.2 and remained [experimental](https://docs.scylladb.com/master/operating-scylla/admin.html#yaml-enabling-experimental-features) before Scylla 4.0. Since version 4.0, it is production ready.

**Comment by annastuchlik** [comment]
Now that the documentation is versioned, we can just remove the information, as it's completely redundant in version 5.3.

**Comment by annastuchlik** [comment]
No need to backport.
