### ISSUE TITLE
"exception during mutation write - Column definition mv_pk does not match any column" after changing "tombstone_gc" for the materialized view

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#13579]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

"exception during mutation write - Column definition mv_pk does not match any column" error received from storage_proxy on one node after changing "tombstone_gc" for the materialized view.

```
2023-04-19 00:03:58.067: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=32bbceaa-6540-4bce-a022-891278e2
d8a9: nemesis_name=ToggleTableGcMode target_node=Node longevity-mv-synch-12h-2023-1-db-node-41726b20-5 [34.241.84.46 | 10.4.2.222] (seed: False)
< t:2023-04-19 00:53:53,280 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "ALTER MATERIALIZED VIEW  mv_synchronous_ks.cf_update_synch_view_3 WITH tombstone_gc = {'mode': 'repair'};" 10.4.2.222 9042"...
```

The error received on the node `longevity-mv-synch-12h-2023-1-db-node-41726b20-3`
```
2023-04-19T00:53:54+00:00 longevity-mv-synch-12h-2023-1-db-node-41726b20-3      !ERR | scylla[5396]:  [shard 2] storage_proxy - exception during mutation write to 10.4.3.252: std::runtime_error (Column definition mv_pk does not match any column in the query selection)
```

But right after that schema version has been changed:
```
2023-04-19T00:53:54+00:00 longevity-mv-synch-12h-2023-1-db-node-41726b20-3     !INFO | scylla[5396]:  [shard 0] schema_tables - Schema version changed to 453f68b8-7fe0-3cbd-9286-5e4c9a7bcda1
```

and altering was completed.

I see similar closed issue: https://github.com/scylladb/scylladb/issues/10192.

## Impact

I did not see any impact except of error in the node log. But I can not say that all mutations were written or not

## How frequently does it reproduce?

Got it once

## Installation details

Kernel Version: 5.19.0-1022-aws
Scylla version (or git commit hash): `2023.1.0~rc4-20230402.f90af81a13cc` with build-id `4db7799d283c7ca63c7639b04db34c301dbcfb66`

Cluster size: 6 nodes (i4i.xlarge)

Scylla Nodes used in this run:
- longevity-mv-synch-12h-2023-1-db-node-41726b20-9 (52.48.247.218 | 10.4.2.20) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-8 (52.210.74.109 | 10.4.3.233) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-7 (34.244.185.185 | 10.4.3.12) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-6 (52.30.18.185 | 10.4.0.152) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-5 (34.241.84.46 | 10.4.2.222) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-4 (3.252.140.125 | 10.4.0.130) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-3 (34.244.241.189 | 10.4.3.252) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-2 (52.17.8.67 | 10.4.2.166) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-11 (54.75.37.83 | 10.4.1.129) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-10 (3.250.125.35 | 10.4.3.248) (shards: 4)
- longevity-mv-synch-12h-2023-1-db-node-41726b20-1 (34.241.50.223 | 10.4.3.170) (shards: 4)

OS / Image: `ami-000f0d43cb22bd09e` (aws: eu-west-1)

Test: `longevity_mv_synchronous_updates-12h`
Test id: `41726b20-862f-42ae-beaf-ebea19a6ba90`
Test name: `enterprise-2023.1/longevity/longevity_mv_synchronous_updates-12h`
Test config file(s):

- [longevity-mv-synchronous-updates-12h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a4aa12434fbb3ed650674f447d1a3f9f5b15413e/test-cases/longevity/longevity-mv-synchronous-updates-12h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 41726b20-862f-42ae-beaf-ebea19a6ba90`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=41726b20-862f-42ae-beaf-ebea19a6ba90)
- Show all stored logs command: `$ hydra investigate show-logs 41726b20-862f-42ae-beaf-ebea19a6ba90`

## Logs:
- **db-cluster-41726b20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/db-cluster-41726b20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/db-cluster-41726b20.tar.gz)
- **sct-runner-events-41726b20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/sct-runner-events-41726b20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/sct-runner-events-41726b20.tar.gz)
- **sct-41726b20.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/sct-41726b20.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/sct-41726b20.log.tar.gz)
- **monitor-set-41726b20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/monitor-set-41726b20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/monitor-set-41726b20.tar.gz)
- **loader-set-41726b20.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/loader-set-41726b20.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/41726b20-862f-42ae-beaf-ebea19a6ba90/20230419_041439/loader-set-41726b20.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity_mv_synchronous_updates-12h/4/)
</details>

**Comment by mykaul** [comment]
@juliayakovlev - does the column exist? See the discussion @ https://github.com/scylladb/scylladb/issues/9823#issuecomment-1512582974 if the column doesn't exist.

**Comment by DoronArazii** [comment]
@cvybhu can you please provide first assessment

**Comment by mykaul** [comment]
@eliransin - ping

**Comment by mykaul** [comment]
Thanks @juliayakovlev - closing for the time being.
