### ISSUE TITLE
boost.Master Test Suite.release.test_group0_history_clearing_old_entries

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#13594]
```
[Exception] - critical check co_await get_history_size() == 1 has failed [2 != 1]
 == [File] - test/boost/group0_test.cc
 == [Line] -98
```

Seen in:
* https://jenkins.scylladb.com/job/scylla-master/job/next/5897/
* https://jenkins.scylladb.com/job/scylla-master/job/next/5899/

@kbr-scylla @kostja @gleb-cloudius

**Comment by kostja** [comment]
kostja@hulk:~/work/scylla/scylla$ ./test.py --mode=release group0_test --repeat=1000
Found 3000 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[3000/3000]  boost   release [ PASS ] boost.group0_test.test_group0_history_clearing_old_entries.1000            
------------------------------------------------------------------------------

**Comment by yaronkaikov** [comment]
@avikivity Since all active releases are using the new servers this should be backported to all

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.
