### ISSUE TITLE
sstables/compressed_file_data_source_impl may segfault if the file is corrupt and EOF is reached prematurely

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13599]
In `compressed_file_data_source_impl::get`, `read_exactly` might return an empty temporary_buffer if we reach EOF on the uncompressed file prematurely.
See https://github.com/scylladb/scylladb/blob/6ca1b144883478e33ce3ab21abe61283b14cdebf/sstables/compress.cc#L391

If that happens, we may try to dereference a null pointer returned by `buf.get()` in https://github.com/scylladb/scylladb/blob/6ca1b144883478e33ce3ab21abe61283b14cdebf/sstables/compress.cc#L399

Instead, we should throw an exception about the corrupt file.

**Comment by denesb** [comment]
Backported to 5.2.
