### ISSUE TITLE
Consider allowing UNSET_VALUE in IN expressions

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13659]
Scylla currently doesn't allow an UNSET_VALUE when binding an "IN" expression, such as the LWT expression `IF v IN (?, ?)`. We print the error message "Unexpected unset value for bind variable 1".

This is allowed in Cassandra, starting in https://github.com/apache/cassandra/commit/70e33d96e1f1236788afb50c1f02fbc64d760281 (for https://issues.apache.org/jira/browse/CASSANDRA-12981). Looking at the code in that commit, it appears that Cassandra prints an error if the IN list itself is unset, but if it's a real list (as in the above example) and one or more its members are UNSET_VALUE bound variables, these are simply skipped and do nothing.

Maybe Cassandra's behavior is useful, to allow writing a single statement with an IN of several options, but allow to run it with fewer options? But on the other hand, I think that whoever wants to do this, would just make the entire list a bound variable, instead of an individual member, and getting an error message on a forgotten bind is useful?

@avikivity for your consideration. I'm also fine if we just close this issue and mark this down as yet another intended difference in Scylla's handling of nulls and unsets.

**Comment by avikivity** [comment]
I think it's unnecessary. Unset pollutes the type system and it's better not to have to look for it everywhere.

**Comment by nyh** [comment]
I tend to agree, even though this behavior was intentionally added to Cassanda (I mentioned the exact commit above), I don't understand their intention and I agree it is a mistake. So closing this issue. We can reopen it if we change our mind.
