### ISSUE TITLE
Misformatted printout of column name in LWT error message

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13657]
When attempting the LWT operation `set m['foo'] = 'bar'` when m is a **frozen** collection, Scylla wants to print the message:

```
Invalid operation (m['foo'] = 'bar') for frozen collection column m
```

But it ends up printing the hexadecimal ASCII (!) of the column name:
```
Invalid operation (m['foo'] = 'bar') for frozen collection column 6d
```

I guess we end up printing a "bytes" instead of a string.

Reproduced by translated Cassandra unit test `cassandra_tests/validation/operations/insert_update_if_condition_collections_test.py`::`testMapItem`

**Comment by nyh** [comment]
By the way, ironically, in Cassandra `IF v IN ?` (what I suggested above that should be used!) is not allowed if the bound variable in its entirety is UNSET_VALUE or NULL - it prints `"Invalid 'unset' value in condition"`.
Cassandra it only allows a single member of a list `(?, ?, ?)` to be unset. I'm starting to think that this Cassandra behaviour simply doesn't make sense, and we shouldn't emulate it.

**Comment by nyh** [comment]
The fix, https://github.com/scylladb/scylladb/commit/a29b8cd02ba269d4b1151904574913d4cbd45000, already reached 5.4. I think that given the low severity of this issue (it's just about error messages), we don't need to backport it further back.

But I want to ask @fee-mendes (who rediscovered this issue in Scylla 5.2 - see https://github.com/scylladb/scylladb/issues/15882) if he thinks differently. It should be easy (I hope...) to backport this patch.

**Comment by denesb** [comment]
@fee-mendes ping on the backport question above ^^.

**Comment by fee-mendes** [comment]
> @fee-mendes ping on the backport question above ^^.

Already answered in https://github.com/scylladb/scylladb/issues/15882#issuecomment-1827769150 - which is the issue I opened.

> Well, it is cosmetics. :) Yet, if it turns out to be effortless, then why not? ;-)

**Comment by denesb** [comment]
Backported to 5.2.
