### ISSUE TITLE
Yield while building large results in Alternator - rjson::print, executor::batch_get_item

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#13689]
Branched from https://github.com/scylladb/scylladb/issues/7926 to separate the issue to smaller chunks.

In this issue we fix (the most obvious cases in which yielding is necessary):
- The low-level JSON printing code (rjson::print() called in server.cc).
- For BatchGetItem, executor::batch_get_item() also ends with a loop over all items, which doesn't yield.

**Comment by nyh** [comment]
I'll backport this fix, as it is a bug fix in latency.

**Comment by nyh** [comment]
Verified that all three backports (to 5.3, 5.2, 5.1) were successfully promoted.
