### ISSUE TITLE
DESCRIBE query is not working on table enabled the cdc

### ISSUE THREAD

**Issue by brightwon** [scylladb/scylladb#13702]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Scylla Enterprise 2022.2.0 (ScyllaDB Cloud)
Cluster size: 
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

When I run the DESCRIBE command in cqlsh, `'module' object has no attribute 'viewkeys'` error is occured.
my test_table is with cdc enabled.

I raised an issue in the Slack community and register an issue at Dor Laor's request.
https://scylladb-users.slack.com/archives/C2NLNBXLN/p1682296010680869

![image](https://user-images.githubusercontent.com/46628677/235077721-0fbd04d7-1f18-43a2-b7fb-8e5888548033.png)

**Comment by piodul** [comment]
In https://github.com/scylladb/scylladb/pull/18467, we explicitly forbade calling DESCRIBE on a CDC log table. Now, we return a clear message:

```
ks.t_scylla_cdc_log is a cdc log table and it cannot be described directly. Try `DESC TABLE ks.t` to describe cdc base table and it's log table.
```

(Note that this requires a recent version of cqlsh which supports server-side describe, at least v6.0.19)

The rationale for this is that CDC log tables are created by setting an appropriate option on the base table. Executing DESCRIBE on the base table shows commands that allow to recreate the table. The output contains an ALTER TABLE command which shows the parameters that can be altered:

```cql
CREATE MATERIALIZED VIEW ks.t_mv AS
    SELECT v, pk
    FROM ks.t
    WHERE v IS NOT null
    PRIMARY KEY (v, pk)
    WITH CLUSTERING ORDER BY (pk ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99.0PERCENTILE'
    AND paxos_grace_seconds = 864000
    AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'};

ALTER TABLE ks.t_scylla_cdc_log WITH bloom_filter_fp_chance = 0.01
    AND caching = {'enabled': 'false', 'keys': 'NONE', 'rows_per_partition': 'NONE'}
    AND comment = 'CDC log for ks.t'
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '60', 'compaction_window_unit': 'MINUTES', 'expired_sstable_check_frequency_seconds': '1800'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99.0PERCENTILE'
    AND paxos_grace_seconds = 864000
    AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'};
```

However, one thing is missing from the output - column types of the `t_scylla_cdc_log` table. We previously allowed DESCRIBE on those tables and it outputted a `CREATE TABLE ks.t_scylla_cdc_log` with information about the columns. While it's not required for schema backup purposes, it could have been useful for users that wanted to consume CDC tables directly - we have some funky rules which decide what the columns in the cdc log table are based on the base table columns.

I think it would be nice to keep this functionality, so I'm not sure we made the right decision. However, I'm not sure what should be the output of `DESCRIBE ks.t_scylla_cdc_log`.

- `CREATE TABLE ks.t_scylla_cdc_log`? In that case this would create a non-cdc table.
- `CREATE TABLE ks.t` + `ALTER TABLE ks.t_scylla_cdc_log`? I'm not sure we can show column names in the second table. Also, it creates the base table.
- Keep the current behavior (return an error)? Maybe I'm overstating the importance of this feature.

@kostja @kbr-scylla @Jadw1 what is your opinion?

**Comment by kbr-scylla** [comment]
For backup/restore purposes you need to use the `WITH INTERNALS` option anyway, so I wonder if the motivation described in https://github.com/scylladb/scylladb/pull/18467 makes sense after all?

> However, I'm not sure what should be the output of DESCRIBE ks.t_scylla_cdc_log

How about:
- when describing the whole keyspace, show CREATE + ALTER
- but when describing just the log table, show CREATE but also print a warning that the table must not be created on its own, mention what needs to be done if the user wants to backup/restore schema etc.

This way if the user wants to learn about the log table they can explicitly describe it, and if they want backup/restore they can describe the whole keyspace (or the base table --- if describing the base table also includes the log table ALTER? perhaps it should)

**Comment by piodul** [comment]
> For backup/restore purposes you need to use the `WITH INTERNALS` option anyway, so I wonder if the motivation described in #18467 makes sense after all?

Not sure if I get your point. The primary motivation for that PR was to hide cdc log tables from `DESCRIBE` statements, primarily from `DESCRIBE SCHEMA` but we also did it for `DESCRIBE <table>` statements for consistency. Do you mean that we should behave differently when using `WITH INTERNALS`?

> - but when describing just the log table, show CREATE log but also print a warning that the table must not be created on its own, mention what needs to be done if the user wants to backup/restore schema etc.

Sounds reasonable. A `DESCRIBE SCHEMA` call won't be a concatenation of all `DESCRIBE <table>` calls for all allowed tables, but maybe this makes sense. I hope the warning will be significant enough to get the message through.

**Comment by kbr-scylla** [comment]
> to hide cdc log tables from DESCRIBE statements

and what was the motivation of that?

> Do you mean that we should behave differently when using WITH INTERNALS

possibly yes

**Comment by piodul** [comment]
> > to hide cdc log tables from DESCRIBE statements
> 
> and what was the motivation of that?

To make it possible to restore schema by replaying commands generated by `DESCRIBE SCHEMA`/`DESCRIBE KEYSPACE` etc. You don't want to have a statement like `CREATE TABLE t_scylla_cdc_log` if you already have `CREATE TABLE t (...) WITH cdc = {'enabled': true}` in the output: executing both of them will lead to an error and executing the first one before another will do the wrong thing.

**Comment by kbr-scylla** [comment]
> To make it possible to restore schema by replaying commands generated by DESCRIBE SCHEMA/DESCRIBE KEYSPACE etc

And IIUC, that motivation is obsolete, because we determined that restoring schema by the "regular" DESCRIBE is incorrect, and we need a DESCRIBE WITH INTERNALS to actually restore schema correctly.

Which, back to my point -- makes the PR's motivation obsolete.

**Comment by kostja** [comment]
@piodul what's the point of producing alter specification if there is no create specification?

**Comment by piodul** [comment]
> @piodul what's the point of producing alter specification if there is no create specification?

Sorry, for some reason I have pasted `CREATE MATERIALIZED VIEW` rather than `CREATE TABLE` in the comment and I didn't notice it. I updated it.

`DESCRIBE` does generate a `CREATE` specification, but for the base table only. Because the base table has the `WITH cdc = {'enabled: true}` part, it additionally generates the CDC log table. Thus, we don't need and don't want `CREATE TABLE t_scylla_cdc_log` in the output because it would be redundant and would collide with the table generated by the other statement.

We generate `ALTER` for the CDC log table because it is possible to modify some parameters on it and we want to preserve them.

**Comment by piodul** [comment]
As pointed by @nyh in https://github.com/scylladb/scylladb/pull/21228#issuecomment-2429740659, the discussion about allowing DESCRIBE TABLE for cdc log tables that I started is a bit off-topic here, as the problem stated in the issue seems to be about calling DESCRIBE TABLE on the _base_ table.

I created a separate issue to track it: https://github.com/scylladb/scylladb/issues/21235

**Comment by piodul** [comment]
As for the original issue, I believe it is fixed by moving to server-side DESCRIBE. `scylla-cqlsh` starting from v6.0.19 and up supports it (https://github.com/scylladb/scylla-cqlsh/pull/88). Server-side describe (https://github.com/scylladb/scylladb/pull/11106) is supported in ScyllaDB OSS 5.2 and up, and in ScyllaDB Enterprise 2023.1 and up.

Closing.
