### ISSUE TITLE
Scylla crashes with message "Aborted" on OrangePi 5 (Rockchip RK3588S aarch64 - release build only - debug works)

### ISSUE THREAD

**Issue by picakia** [scylladb/scylladb#13712]
Hello, I have a problem with running Scylla 5.1.8 on Orange Pi 5 (Ubuntu 22.04). After running `scylla --version` I'm only getting:
```
root@orangepi5:~$ scylla --version
Aborted
```

I digged around and I found that iotune command also fails with this same error:
```
root@orangepi5:~$ iotune --help
Aborted
```

I also tried building scylla from source following your guide and to my suprise **debug** build worked without any errors while *release* and *dev* builds failed with no error message. 
```
root@orangepi5:/data/scylla-src# ./tools/toolchain/dbuild ./build/debug/scylla --version
5.3.0~dev-0.20230428.3b44ecd1e735
```

The same was true when building *seastar* from source - *release/dev* were crashing, but *debug* worked like a charm.
I tried to find a problem in the source code in `iotune.cc` and only managed to locate 2 includes that causes crash:
```
include <seastar/core/sharded.hh>
include <seastar/core/app-template.hh>
```
After commenting them (and leaving only simple main function) the `iotune` command worked.

If you need any more details feel free to ask, I'm also on Slack so we can quickly brainstorm when needed.

*Installation details*
Scylla version: **5.1.8-0.20230319.c90807d29f30-1**
Cluster size: N/A
OS: **Ubuntu 22.04.2 LTS**
Kernel: **Linux orangepi5 5.10.110-rockchip-rk3588 aarch64**

*Hardware details*
Platform: **OrangePI 5**
Hardware: **8-core Rockchip RK3588S, 8GB RAM, aarch64**
Disks: **64GB SD-Card (system), 256 GB M.2 NVME (with xfs for database)**

**Comment by DoronArazii** [comment]
@xemul can you please provide first assessment to this

**Comment by xemul** [comment]
@picakia , please check several things:

1. whether `dmesg` contains any errors or OOM messages or whatever you think is suspicious
2. try `iotune` with `-c1` flag
3. run `iotune` from under strace (mind using the `-f` flag as it forks actively)

**Comment by picakia** [comment]
@xemul 
1. I can't find any OOM or anything suspicious in `dmesg`, I also created a 20 GB swap file on NVME drive to see if it helps but nothing changed

2. 
```bash
# seastar release from apt repository
root@orangepi5:/data/seastar-src# iotune -c1
Aborted

# seastar built from source master branch
root@orangepi5:/data/seastar-src# ./build/release/apps/iotune/iotune -c1
Aborted
root@orangepi5:/data/seastar-src# ./build/dev/apps/iotune/iotune -c1
Aborted
root@orangepi5:/data/seastar-src# ./build/debug/apps/iotune/iotune -c1
WARNING: debug mode. Not for benchmarking or production
the option '--evaluation-directory' is required but missing
```

3.
* seastar release from apt repository -> [strace_iotune_APT.log](https://github.com/scylladb/scylladb/files/11371933/strace_iotune_APT.log)
* seastar **release build** from source master branch -> [strace_iotune_release.log](https://github.com/scylladb/scylladb/files/11371936/strace_iotune_release.log)

* seastar **dev build** from source master branch -> [strace_iotune_dev.log](https://github.com/scylladb/scylladb/files/11371938/strace_iotune_dev.log)

* seastar **debug build** from source master branch -> [strace_iotune_debug.log](https://github.com/scylladb/scylladb/files/11371939/strace_iotune_debug.log)

**Comment by xemul** [comment]
It looks like it's trying to print something on the screen, but fails (like https://github.com/scylladb/seastar/pull/1249). 
@picakia , what's the fmtlib version on your node?
Also, can you run release's iotune from under gdb and collect the backtrace once it crashes?

**Comment by picakia** [comment]
@xemul 
I'm assuming that you are reffering to whole package (libfmt-dev):
```
root@orangepi5:/data/seastar-src# apt install libfmt-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libfmt-dev is already the newest version (8.1.1+ds1-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

* gdb backtrace - iotune **release build** from source master branch -> [gdb_backtrace_iotune_release.txt](https://github.com/scylladb/scylladb/files/11381195/gdb_backtrace_iotune_release.txt)

**Comment by xemul** [comment]
A-ha

```c++
static char* mem_base() {
    static char* known;
    static std::once_flag flag;
    std::call_once(flag, [] {
        auto r = ::mmap(NULL, 2 * mem_base_alloc,
                    PROT_NONE,
                    MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE,
                    -1, 0);
        if (r == MAP_FAILED) {
            abort(); // <<<<<<< aborts here
        }   
        ::madvise(r, 2 * mem_base_alloc, MADV_DONTDUMP);
        auto cr = reinterpret_cast<char*>(r);
        known = align_up(cr, mem_base_alloc);
        ::munmap(cr, known - cr);
        ::munmap(known + mem_base_alloc, cr + 2 * mem_base_alloc - (known + mem_base_alloc));
    });
    return known;
}   
```

and release strace output proves that

```
mmap(NULL, 35184372088832, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = -1 ENOMEM (Cannot allocate memory)
```

It tries to mmap `(1 << 44) * 2` of vmem. It shouldn't fail in theory, because its a virtual memory. I can suggest several options why it's so

1. `RLIMIT_AS`/`RLIMIT_DATA` is too low
2. `/proc/sys/vm/overcommit_memory` doesn't allow VM overcommit
3. `/proc/sys/vm/max_map_count` is too low (but that's unlikely)
4.  cgroup configuration is very restrictive and doesn't allow for this

**Comment by xemul** [comment]
OK, so here's what's the root-cause:
```
orangepi@orangepi5:~$ zcat /proc/config.gz | fgrep VA_BITS
CONFIG_ARM64_VA_BITS_39=y
# CONFIG_ARM64_VA_BITS_48 is not set
CONFIG_ARM64_VA_BITS=39
```

The kernel is configured to provide 39 bits for user-space addresses, while seastar wants to have `constexpr size_t mem_base_alloc = size_t(1) << 44;` and mmaps 2x times that value, i.e. -- it needs 45 bits.

@avikivity , do we want to support this anyhow?

**Comment by mykaul** [comment]
@xemul - but how does it work with debug then?

**Comment by xemul** [comment]
Debug builds use native malloc()-s and don't create this area on start (@mykaul )

**Comment by xemul** [comment]
> OK, so here's what's the root-cause:
> 
> ```
> orangepi@orangepi5:~$ zcat /proc/config.gz | fgrep VA_BITS
> CONFIG_ARM64_VA_BITS_39=y
> # CONFIG_ARM64_VA_BITS_48 is not set
> CONFIG_ARM64_VA_BITS=39
> ```
> 
> The kernel is configured to provide 39 bits for user-space addresses, while seastar wants to have `constexpr size_t mem_base_alloc = size_t(1) << 44;` and mmaps 2x times that value, i.e. -- it needs 45 bits.
> 
> @avikivity , do we want to support this anyhow?

@avikivity , ping :point_up:

**Comment by avikivity** [comment]
By itself no. Pis aren't good platforms for databases.

I want to support 57 virtual address bits (for 5 page table levels), and such a change could easily support 39 too. We'll need to make the [bit range allocation](https://github.com/scylladb/seastar/blob/40771928ad2dcbf2a25bfcc97c8916e6cc326891/src/core/memory.cc#L35)  dynamic, allocate just enough bits for memory per shard and just enough bits for the number of shards (can support >256 shards this way) and store the masks and shifts in globals instead of constants.

**Comment by xemul** [comment]
> By itself no. Pis aren't good platforms for databases.
> 
> I want to support 57 virtual address bits (for 5 page table levels), and such a change could easily support 39 too. We'll need to make the [bit range allocation](https://github.com/scylladb/seastar/blob/40771928ad2dcbf2a25bfcc97c8916e6cc326891/src/core/memory.cc#L35) dynamic, allocate just enough bits for memory per shard and just enough bits for the number of shards (can support >256 shards this way) and store the masks and shifts in globals instead of constants.

Thanks for making it clear! I took a note at scylladb/seastar#1651 . I think we're done with the current issue
