### ISSUE TITLE
scylla_raid_setup: may need to run wipefs before reformatting disk when previous filesystem exists

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylladb#13737]
I found reports on Fedora and Arch user communities which says cannot find /dev/disk/by-uuid entry after formatted disk.
It seems similar with our issue on scylla_raid_setup (#11359 and scylladb/scylla-enterprise#2835 and others).

references:
https://forums.fedoraforum.org/showthread.php?288890-kernel-3-7-7-201-missing-dev-disk-by-uuid-entries-no-dev-disk-by-label
https://bbs.archlinux.org/viewtopic.php?id=229064
https://bugzilla.redhat.com/show_bug.cgi?id=902512

The discussion on the thread says, when we reformat a volume with another filesystem, kernel and libblkid may
skip to populate /dev/disk/by-* since it detected two filesystem signatures, because mkfs.xxx did not cleared previous filesystem signature.
To avoid this, we need to run wipefs before running mkfs.

It is probably rare case, and probably fixed on recent versions of distribution, but I suppose we should run wipefs for safety.

**Comment by denesb** [comment]
Backported to 5.2, 5.1, 2022.1. Already part of 5.3.
Backport to 2021.1 is not clean, I will need a backort PR for that.
