### ISSUE TITLE
Warning message about compatibility with Cassandra 4.0

### ISSUE THREAD

**Issue by guy9** [scylladb/scylladb#13739]
*Installation details*
Scylla version (or git commit hash): ScyllaDB Docker image 5.1.7
Cluster size: 3 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker (tested on Linux)

When using ScyllaDB as a storage backend for [Jaeger](https://github.com/jaegertracing/jaeger), the following warning is received: 

```
WARN: DESCRIBE|DESC was moved to server side in Cassandra 4.0. As a consequence DESRIBE|DESC will not work in cqlsh '6.0.0' connected to Cassandra '3.0.8', the version that you are connected to. DESCRIBE does not exist server side prior Cassandra 4.0.
Cassandra version detected: 3
```

More details and a docker-compose example can be found [here](https://github.com/jaegertracing/jaeger/tree/main/plugin/storage/scylladb).

**Comment by guy9** [comment]
CC @dorlaor

**Comment by nyh** [comment]
Closing this issue as a duplicate, leaving the more general issue #14225 which mentions this use case as well as others.
