### ISSUE TITLE
Following an interrupted decommission, nodetool rebuild fails: "Failed to open channel in 15 seconds"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#13741]
## Issue description

While running DecommissionStreamingErr we follow these steps:

Run nodetool decommission on a random db node in the cluster.
When we see the DECOMMISSIONING: unbootstrap starts log line, we perform a hard reboot on the target node to interrupt the decommission process.
After the node reboots, we run nodetool rebuild on it.
The expected behavior is for the target node to be able to stay in the cluster and rebuild without issues.

In this case, the rebuild process failed (and so did the nodetool command):

node-3 decommission is interrupted, then running a nodetool rebuild on node-3 fails with:
```


disrupt_decommission_streaming_err | longevity-10gb-3h-5-2-db-node-ffca5e56-0-3 | Failed | 2023-04-27 23:08:44 | 2023-04-27 23:12:11
-- | -- | -- | -- | --
Nemesis InformationClass: SisyphusName: disrupt_decommission_streaming_errStatus: FailedFailure reasonTraceback (most recent call last):   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run     channel = self.open_channel()   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel     raise OpenChannelTimeout(f'Failed to open channel in {timeout} seconds') sdcm.remote.libssh2_client.exceptions.OpenChannelTimeout: Failed to open channel in 15 seconds  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute     result = connection.run(**command_kwargs)   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 591, in run     return self._complete_run(   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 649, in _complete_run     raise exception sdcm.remote.libssh2_client.exceptions.FailedToRunCommand: Failed to run a command due to exception!  Command: '/usr/bin/nodetool  rebuild '  Stdout:    Stderr:    Exception:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run     channel = self.open_channel()   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel     raise OpenChannelTimeout(f'Failed to open channel in {timeout} seconds')  Failed to open channel in 15 seconds


```
```
< t:2023-04-27 23:11:53,618 f:cluster.py      l:4660 c:sdcm.cluster         p:ERROR > Decommission Node longevity-10gb-3h-5-2-db-node-ffca5e56-0-3 [34.138.29.62 | 10.142.0.246] (seed: False) FAIL
< t:2023-04-27 23:11:53,623 f:nemesis.py      l:3412 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: The decommission of target node is successfully interrupted
< t:2023-04-27 23:11:53,640 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  rebuild "...
< t:2023-04-27 23:12:10,287 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Command: '/usr/bin/nodetool  rebuild '
< t:2023-04-27 23:12:10,485 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-27 23:12:10.477: (NodetoolEvent Severity.ERROR) period_type=end event_id=f811862c-fe5d-4ac3-bb57-47e96fd41507 during_nemesis=DecommissionStreamingErr duration=16s: nodetool_command=rebuild node=longevity-10gb-3h-5-2-db-node-ffca5e56-0-3 errors=['Failed to run a command due to exception!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nStdout:\n\n\n\nStderr:\n\n\n\nException:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\n\nFailed to open channel in 15 seconds\n', 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\nsdcm.remote.libssh2_client.exceptions.OpenChannelTimeout: Failed to open channel in 15 seconds\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 591, in run\n    return self._complete_run(\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 649, in _complete_run\n    raise exception\nsdcm.remote.libssh2_client.exceptions.FailedToRunCommand: Failed to run a command due to exception!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nStdout:\n\n\n\nStderr:\n\n\n\nException:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\n\nFailed to open channel in 15 seconds\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2585, in run_nodetool\n    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 62, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 606, in _run\n    if self._run_on_retryable_exception(exc, new_session):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_libssh_cmd_runner.py", line 78, in _run_on_retryable_exception\n    raise RetryableNetworkException(str(exc), original=exc)\nsdcm.remote.base.RetryableNetworkException: Failed to run a command due to exception!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nStdout:\n\n\n\nStderr:\n\n\n\nException:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\n\nFailed to open channel in 15 seconds\n\n']
```

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.19.0-1022-gcp
Scylla version (or git commit hash): `5.2.0-20230427.429b696bbc1b` with build-id `9736db0414bad938b1d5d959bb25fbb4fb8558ce`

Cluster size: 6 nodes (n1-highmem-16)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-9 (34.23.42.30 | 10.142.0.9) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-8 (35.185.121.53 | 10.142.0.6) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-7 (34.74.113.62 | 10.142.0.3) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-6 (34.75.150.20 | 10.142.0.249) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-5 (34.139.239.191 | 10.142.0.248) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-4 (34.75.73.155 | 10.142.0.247) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-3 (34.138.29.62 | 10.142.0.246) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-2 (34.139.78.252 | 10.142.0.245) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-10 (35.185.73.122 | 10.142.0.10) (shards: 14)
- longevity-10gb-3h-5-2-db-node-ffca5e56-0-1 (34.138.234.75 | 10.142.0.244) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/1410634968730132419` (gce: us-east1)

Test: `longevity-10gb-3h-gce-test`
Test id: `ffca5e56-9566-454f-9d67-802d1f29cca0`
Test name: `scylla-5.2/longevity/longevity-10gb-3h-gce-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0fc27a30470bede5f583e2ae29f71e81c76c2b4c/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ffca5e56-9566-454f-9d67-802d1f29cca0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ffca5e56-9566-454f-9d67-802d1f29cca0)
- Show all stored logs command: `$ hydra investigate show-logs ffca5e56-9566-454f-9d67-802d1f29cca0`

## Logs:
- **db-cluster-ffca5e56.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/db-cluster-ffca5e56.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/db-cluster-ffca5e56.tar.gz)
- **sct-runner-events-ffca5e56.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/sct-runner-events-ffca5e56.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/sct-runner-events-ffca5e56.tar.gz)
- **sct-ffca5e56.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/sct-ffca5e56.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/sct-ffca5e56.log.tar.gz)
- **monitor-set-ffca5e56.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/monitor-set-ffca5e56.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/monitor-set-ffca5e56.tar.gz)
- **loader-set-ffca5e56.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/loader-set-ffca5e56.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/loader-set-ffca5e56.tar.gz)
- **parallel-timelines-report-ffca5e56.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/parallel-timelines-report-ffca5e56.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ffca5e56-9566-454f-9d67-802d1f29cca0/20230428_021417/parallel-timelines-report-ffca5e56.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-10gb-3h-gce-test/10/)
</details>

**Comment by mykaul** [comment]
Unsure what this is:
```
cloud-init[553]: 2023-04-27 23:09:11,127 - __init__.py[WARNING]: Unhandled unknown content-type (x-scylla/json) userdata: 'b'{'...'
``` 
- but doesn't look related to the issue. @syuu1228 - any idea?

**Comment by mykaul** [comment]
Restart:
```
2023-04-27T23:08:57+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | scylla[14599]:  [shard 13] compaction - [Compact system.peers 7cceb7a0-e550-11ed-b27b-f1a1d259b8d0] Compacted 2 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-139-big-Data.db:level=0]. 139kB to 98kB (~70% of original) in 21ms = 4MB/s. ~256 total partitions merged to 2.
2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3   !NOTICE | syslog-ng[646]: syslog-ng starting up; version='3.35.1'
2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3   !NOTICE | syslog-ng[646]: Syslog connection established; fd='18', server='AF_INET(10.142.0.243:32768)', local='AF_INET(0.0.0.0:0)'
2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | scylla-manager-agent[16057]: {"L":"INFO","T":"2023-04-27T23:08:36.006Z","N":"http","M":"GET /gossiper/endpoint/live/","from":"10.142.0.255:44616","status":200,"bytes":91,"duration":"0ms"}
2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3   !NOTICE | kernel: Linux version 5.19.0-1022-gcp (buildd@lcy02-amd64-054) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #24~22.04.1-Ubuntu SMP Sun Apr 23 09:51:08 UTC 2023 (Ubuntu 5.19.0-1022.24~22.04.1-gcp 5.19.17)
2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-5.19.0-1022-gcp root=PARTUUID=a403b5ce-0f74-47a0-937d-83fbf1e8d65c ro console=ttyS0 net.ifnames=0 clocksource=tsc tsc=reliable panic=-1
...
Multiple AVC errors (do we have a bug on this?!)
...
```

After a while, Scylla starts to come up:
```
2023-04-27T23:09:16+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | scylla[1058]: Scylla version 5.2.0-0.20230427.429b696bbc1b with build-id 9736db0414bad938b1d5d959bb25fbb4fb8558ce starting ...

Commitlog warnings - expected I guess(?):
[ykaul@ykaul ~]$ grep -Frisnc " Cannot parse the version of the file" /home/ykaul/Downloads/db-cluster-ffca5e56/longevity-10gb-3h-5-2-db-node-ffca5e56-0-3/messages.log
1974
Example:
```
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | scylla[1058]:  [shard  0] database - Using schema commit log.
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3  !WARNING | scylla[1058]:  [shard  0] commitlog - Cannot parse the version of the file: CommitLog-2-1303310.log
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3  !WARNING | scylla[1058]:  [shard  0] commitlog - Cannot parse the version of the file: CommitLog-2-18014398510785295.log
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3  !WARNING | scylla[1058]:  [shard  0] commitlog - Cannot parse the version of the file: CommitLog-2-72057594039231247.log
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3  !WARNING | scylla[1058]:  [shard  0] commitlog - Cannot parse the version of the file: CommitLog-2-90071992548713231.log
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3  !WARNING | scylla[1058]:  [shard  0] commitlog - Cannot parse the version of the file: CommitLog-2-180143985096123151.log
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3  !WARNING | scylla[1058]:  [shard  0] commitlog - Cannot parse the version of the file: CommitLog-2-198158383605605135.log
2023-04-27T23:09:18+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3  !WARNING | scylla[1058]:  [shard  0] commitlog - Cannot parse the version of the file: CommitLog-2-234187180624569103.log
...
```

Finally, started:
```
2023-04-27T23:09:51+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | systemd[1]: Started Scylla Server.
```

**Comment by fgelcer** [comment]
> Restart:
> 
> ```
> 2023-04-27T23:08:57+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | scylla[14599]:  [shard 13] compaction - [Compact system.peers 7cceb7a0-e550-11ed-b27b-f1a1d259b8d0] Compacted 2 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-139-big-Data.db:level=0]. 139kB to 98kB (~70% of original) in 21ms = 4MB/s. ~256 total partitions merged to 2.
> 2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3   !NOTICE | syslog-ng[646]: syslog-ng starting up; version='3.35.1'
> 2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3   !NOTICE | syslog-ng[646]: Syslog connection established; fd='18', server='AF_INET(10.142.0.243:32768)', local='AF_INET(0.0.0.0:0)'
> 2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | scylla-manager-agent[16057]: {"L":"INFO","T":"2023-04-27T23:08:36.006Z","N":"http","M":"GET /gossiper/endpoint/live/","from":"10.142.0.255:44616","status":200,"bytes":91,"duration":"0ms"}
> 2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3   !NOTICE | kernel: Linux version 5.19.0-1022-gcp (buildd@lcy02-amd64-054) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #24~22.04.1-Ubuntu SMP Sun Apr 23 09:51:08 UTC 2023 (Ubuntu 5.19.0-1022.24~22.04.1-gcp 5.19.17)
> 2023-04-27T23:09:12+00:00 longevity-10gb-3h-5-2-db-node-ffca5e56-0-3     !INFO | kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-5.19.0-1022-gcp root=PARTUUID=a403b5ce-0f74-47a0-937d-83fbf1e8d65c ro console=ttyS0 net.ifnames=0 clocksource=tsc tsc=reliable panic=-1
> ...
> Multiple AVC errors (do we have a bug on this?!)
> ...
> ```

why is it using kernel `Ubuntu 5.19.0-1022.24~22.04.1-gcp 5.19.17`.. didn't we move to use `5.15`?
@mykaul @yaronkaikov ?

**Comment by mykaul** [comment]
> why is it using kernel `Ubuntu 5.19.0-1022.24~22.04.1-gcp 5.19.17`.. didn't we move to use `5.15`?
> @mykaul @yaronkaikov ?

On gcp (1) the bug does not exist and (2) a 5.15 kernel (LTS) is not available yet. It'll be there later on.

**Comment by fgelcer** [comment]
> @yarongilor - are we sure we wait enough? I'm unsure we handle the reboot (end to end, waiting for Scylla to be up) correctly.

https://github.com/scylladb/scylla-cluster-tests/issues/6085

**Comment by mykaul** [comment]
> > @yarongilor - are we sure we wait enough? I'm unsure we handle the reboot (end to end, waiting for Scylla to be up) correctly.
> 
> [scylladb/scylla-cluster-tests#6085](https://github.com/scylladb/scylla-cluster-tests/issues/6085)

Then I suspect (but unsure) that we can close this bug.

**Comment by fgelcer** [comment]
> > > @yarongilor - are we sure we wait enough? I'm unsure we handle the reboot (end to end, waiting for Scylla to be up) correctly.
> > 
> > 
> > [scylladb/scylla-cluster-tests#6085](https://github.com/scylladb/scylla-cluster-tests/issues/6085)
> 
> Then I suspect (but unsure) that we can close this bug.

i just sent a fix, and will now run a reproducer to see if this issue goes away

**Comment by fgelcer** [comment]
following [this run](https://argus.scylladb.com/test/8bcc5636-0d1a-4f9f-a34d-387b4b9ebf71/runs?additionalRuns[]=12a14a69-1b3b-4a43-937c-a73cfef95100), including [this fix](https://github.com/scylladb/scylla-cluster-tests/pull/6086) in SCT, we have the problematic nemesis finally passing.
