### ISSUE TITLE
The nodes with base Scylla version complain about `exception while processing a message` during rolling upgrade of the cluster

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylladb#13752]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

This job (debian 10) passed last week, so it looks like a regression.

During this rolling upgrade test, we were going to upgrade Scylla from version `5.2.0~rc5-20230425.a89867d8c230` (base version) to version `5.3.0~dev-20230426.a29b8cd02ba2` in the cluster of 4 nodes.

The 1st node we started upgrading was `node-2`
```
< t:2023-04-30 21:08:28,723 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-30 21:08:28.720: (InfoEvent Severity.NORMAL) period_type=not-set event_id=5cd401db-8d86-478f-90d3-fa296b21b7ae: message=Upgrade Node rolling-upgrade--debian-buster-db-node-fb7d9154-0-2 begin
```
In the middle of this process the other nodes: `node-3`, `node-4`, `node-1` - started throwing the following messages in their logs. These messages are something new - we didn't have them in previous (passed) runs of this Job.
```
2023-04-30T21:11:30+00:00 rolling-upgrade--debian-buster-db-node-fb7d9154-0-4     !INFO | scylla[3539]:  [shard 0] rpc - client 10.142.0.7:62251 msg_id 10:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
2023-04-30T21:11:30+00:00 rolling-upgrade--debian-buster-db-node-fb7d9154-0-1     !INFO | scylla[3250]:  [shard 0] rpc - client 10.142.0.7:55818 msg_id 10:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
2023-04-30T21:11:30+00:00 rolling-upgrade--debian-buster-db-node-fb7d9154-0-3     !INFO | scylla[3477]:  [shard 0] rpc - client 10.142.0.7:64127 msg_id 10:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
```
The upgrade of `node-2` the succeeded
```
< t:2023-04-30 21:14:55,042 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-30 21:14:55.041: (InfoEvent Severity.NORMAL) period_type=not-set event_id=40561c45-436b-4124-bff8-4e474f0676b6: message=Upgrade Node rolling-upgrade--debian-buster-db-node-fb7d9154-0-2 ended
```
The next node of the cluster we were going to upgrade was `node-1`
```
< t:2023-04-30 21:23:30,178 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-30 21:23:30.171: (InfoEvent Severity.NORMAL) period_type=not-set event_id=6323d401-0f34-4e1a-97b0-b25768078648: message=Upgrade Node rolling-upgrade--debian-buster-db-node-fb7d9154-0-1 begin
```
Meanwhile, the messages like `caught exception while processing a message: std::out_of_range (deserialization buffer underflow)` continued to flood the logs of `node-3`, `node-4`, and `node-1`
The upgrade of the `node-1` succeeded and this node stopped throwing the above-mentioned log messages
```
< t:2023-04-30 21:29:43,156 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-30 21:29:43.154: (InfoEvent Severity.NORMAL) period_type=not-set event_id=4764ecb0-e9f5-4ca4-9c0a-dfba6f3d0d7b: message=Upgrade Node rolling-upgrade--debian-buster-db-node-fb7d9154-0-1 ended
```
Only `node-3` and `node-4` which remained on the base Scylla version kept showing them in their logs
```
2023-04-30T21:29:43+00:00 rolling-upgrade--debian-buster-db-node-fb7d9154-0-4     !INFO | scylla[3539]:  [shard 0] rpc - client 10.142.0.7:62251 msg_id 573895:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
2023-04-30T21:29:43+00:00 rolling-upgrade--debian-buster-db-node-fb7d9154-0-3     !INFO | scylla[3477]:  [shard 0] rpc - client 10.142.0.6:52563 msg_id 116406:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
```
After the upgrade of the `node-1` we tried to run some queries on the cluster and one of those queries timed out
```
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR >                          < t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR > 
                            ALTER TABLE table_options_test
                            WITH comment = 'other comment'
                             AND read_repair_chance = 0.3
                             AND dclocal_read_repair_chance = 0.3
                             AND gc_grace_seconds = 100
                             AND bloom_filter_fp_chance = 0.1
                             AND compaction = { 'class' : 'SizeTieredCompactionStrategy',
                                                'min_sstable_size' : 42 }
                             AND compression = { 'sstable_compression' : 'SnappyCompressor' }
                        
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR > Traceback (most recent call last):
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3254, in _run_db_queries
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR >     res = session.execute(item['queries'][i])
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1661, in execute_verbose
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR >     return execute_orig(*args, **kwargs)
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR >   File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
< t:2023-04-30 21:33:49,961 f:fill_db_data.py l:3257 c:sdcm.fill_db_data    p:ERROR > cassandra.OperationTimedOut: errors={'10.142.0.22:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.142.0.22:9042

```

## Impact

The issue may cause problems during the upgrade of the cluster

## How frequently does it reproduce?
It reproduced in 2 builds of 2

## Installation details

Kernel Version: 4.19.0-23-cloud-amd64
Scylla version (or git commit hash): `5.2.0~rc5-20230425.a89867d8c230` with build-id `15657fcbd406469aa63748f0b8aab3330c137b4e`

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--debian-buster-db-node-fb7d9154-0-4 (34.139.67.78 | 10.142.0.22) (shards: 7)
- rolling-upgrade--debian-buster-db-node-fb7d9154-0-3 (35.196.75.58 | 10.142.0.10) (shards: 7)
- rolling-upgrade--debian-buster-db-node-fb7d9154-0-2 (35.227.27.183 | 10.142.0.7) (shards: 7)
- rolling-upgrade--debian-buster-db-node-fb7d9154-0-1 (34.138.29.145 | 10.142.0.6) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10` (gce: us-east1)

Test: `rolling-upgrade-debian10-test`
Test id: `fb7d9154-c329-480c-9c0b-13ff6d8e30e0`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-debian10-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/916f7b2c035a80dca98e450460f1bc3e88219cce/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor fb7d9154-c329-480c-9c0b-13ff6d8e30e0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=fb7d9154-c329-480c-9c0b-13ff6d8e30e0)
- Show all stored logs command: `$ hydra investigate show-logs fb7d9154-c329-480c-9c0b-13ff6d8e30e0`

## Logs:
- **db-cluster-fb7d9154.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/db-cluster-fb7d9154.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/db-cluster-fb7d9154.tar.gz)
- **sct-runner-events-fb7d9154.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/sct-runner-events-fb7d9154.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/sct-runner-events-fb7d9154.tar.gz)
- **sct-fb7d9154.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/sct-fb7d9154.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/sct-fb7d9154.log.tar.gz)
- **monitor-set-fb7d9154.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/monitor-set-fb7d9154.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/monitor-set-fb7d9154.tar.gz)
- **loader-set-fb7d9154.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/loader-set-fb7d9154.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fb7d9154-c329-480c-9c0b-13ff6d8e30e0/20230430_214429/loader-set-fb7d9154.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-debian10-test/184/)
</details>

**Comment by ilya-rarov** [comment]
Another example

## Issue description
Again, we were upgrading Scylla from version `5.2.0~rc5-20230425.a89867d8c230` to version `5.3.0~dev-20230426.a29b8cd02ba2` in the cluster of 4 nodes.

We started the upgrade of the cluster with the `node-3`
```
< t:2023-04-30 17:47:40,754 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-30 17:47:40.751: (InfoEvent Severity.NORMAL) period_type=not-set event_id=c77e0ddb-9dad-4597-a182-b1c2112c6a63: message=Upgrade Node rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-3 begin
```
The other nodes: `node-1`, `node-2`, `node-4` started complaining about the processing of the messages
```
2023-04-30T17:51:28+00:00 rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-1     !INFO | scylla[20454]:  [shard 0] rpc - client 10.142.0.129:60816 msg_id 14:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
2023-04-30T17:51:28+00:00 rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-4     !INFO | scylla[21021]:  [shard 0] rpc - client 10.142.0.129:55797 msg_id 8:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
2023-04-30T17:51:28+00:00 rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-2     !INFO | scylla[20700]:  [shard 0] rpc - client 10.142.0.129:50519 msg_id 13:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
```
The upgrade of the `node-3` succeeded
```
< t:2023-04-30 17:54:42,733 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-04-30 17:54:42.731: (InfoEvent Severity.NORMAL) period_type=not-set event_id=b1b7ba40-aa4b-411e-8528-6bb92bcf2a21: message=Upgrade Node rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-3 ended
```
After that, we tried to run scylla-bench
```
< t:2023-04-30 18:03:07,841 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo  docker exec abc81fd53ae89cbde692964f8a9c78d0660030e6bd9bd8b8550657e465b8c481 /bin/sh -c 'scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=800 -clustering-row-count=5555 -clustering-row-size=uniform:100..1024 -concurrency=5 -connection-count=5 -consistency-level=quorum -rows-per-request=10 -timeout=30s -validate-data -username cassandra -password cassandra -error-at-row-limit 1000 -nodes 10.142.0.127,10.142.0.128,10.142.0.129,10.142.0.130'"...
```
but it was timed out and failed
```
< t:2023-04-30 18:03:38,894 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo  docker exec abc81fd53ae89cbde692964f8a9c78d0660030e6bd9bd8b8550657e465b8c481 /bin/sh -c 'scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=800 -clustering-row-count=5555 -clustering-row-size=uniform:100..1024 -concurrency=5 -connection-count=5 -consistency-level=quorum -rows-per-request=10 -timeout=30s -validate-data -username cassandra -password cassandra -error-at-row-limit 1000 -nodes 10.142.0.127,10.142.0.128,10.142.0.129,10.142.0.130'"; Exit status: 1
< t:2023-04-30 18:03:38,895 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: 2023/04/30 18:03:38 gocql: no response received from cassandra within timeout period
```
## Installation details

Kernel Version: 5.4.0-1103-gcp
Scylla version (or git commit hash): `5.2.0~rc5-20230425.a89867d8c230` with build-id `15657fcbd406469aa63748f0b8aab3330c137b4e`



Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-4 (34.138.187.117 | 10.142.0.130) (shards: 7)
- rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-3 (34.23.164.186 | 10.142.0.129) (shards: 7)
- rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-2 (35.231.108.215 | 10.142.0.128) (shards: 7)
- rolling-upgrade--ubuntu-bionic-db-node-33c321c1-0-1 (34.139.239.86 | 10.142.0.127) (shards: 7)


OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts` (gce: us-east1)

Test: `rolling-upgrade-ubuntu18.04-test`
Test id: `33c321c1-4901-4ef4-b991-efeef07aea54`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ubuntu18.04-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/916f7b2c035a80dca98e450460f1bc3e88219cce/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 33c321c1-4901-4ef4-b991-efeef07aea54`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=33c321c1-4901-4ef4-b991-efeef07aea54)
- Show all stored logs command: `$ hydra investigate show-logs 33c321c1-4901-4ef4-b991-efeef07aea54`


## Logs:
- **db-cluster-33c321c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/db-cluster-33c321c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/db-cluster-33c321c1.tar.gz)
- **sct-runner-events-33c321c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/sct-runner-events-33c321c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/sct-runner-events-33c321c1.tar.gz)
- **sct-33c321c1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/sct-33c321c1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/sct-33c321c1.log.tar.gz)
- **monitor-set-33c321c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/monitor-set-33c321c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/monitor-set-33c321c1.tar.gz)
- **loader-set-33c321c1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/loader-set-33c321c1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/33c321c1-4901-4ef4-b991-efeef07aea54/20230430_181402/loader-set-33c321c1.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ubuntu18.04-test/254/)
</details>

**Comment by DoronArazii** [comment]
@gleb-cloudius can you please have a look

**Comment by gleb-cloudius** [comment]
Most likely the reason is this: https://github.com/scylladb/scylladb/pull/12966/commits/f5f566bdd8b2fbffd104593dba033175f51b26ae#r1183617420

**Comment by gleb-cloudius** [comment]
@bhalevy ^^^

**Comment by denesb** [comment]
No branches affected, no backport needed.
