### ISSUE TITLE
"partition key token" name changed, break java-driver test

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#13769]
Driver tests `com.datastax.driver.core.M3PTokenIntegrationTest.should_get_token_from_row_and_set_token_in_query` started failing with all java driver version (both datastax and scylla)
https://github.com/datastax/java-driver/blob/741df6f98a1aad172d7dce2a760fac6c280a208c/integration-tests/src/test/java/com/datastax/oss/driver/core/metadata/TokenITBase.java#L182

seem like the change is a29b8cd02ba2..113fb320197

and in:
https://github.com/scylladb/scylladb/pull/13480/
https://github.com/scylladb/scylladb/pull/13480/commits/be8ef63bf503da88c55cd0ec84514d9e31db019f

the hardcode name "partition key token" was removed/change, and seems like driver code and test code is counting on this name.

**Comment by DoronArazii** [comment]
@ptrsmrn / @eliransin please assign someone to handle this

**Comment by ptrsmrn** [comment]
@cvybhu can you confirm it is indeed [your change](https://github.com/scylladb/scylladb/commit/1cefb662cd2cfb1474d46901726eee9c55d3bef3#diff-f156f2f21e75de18dc077db531cab59a6a25a9f2c7804aff56143b9d53e66e04L1227) that broke the test?

**Comment by cvybhu** [comment]
> @cvybhu can you confirm it is indeed [your change](https://github.com/scylladb/scylladb/commit/1cefb662cd2cfb1474d46901726eee9c55d3bef3#diff-f156f2f21e75de18dc077db531cab59a6a25a9f2c7804aff56143b9d53e66e04L1227) that broke the test?

Yes that looks like it broke because of https://github.com/scylladb/scylladb/pull/13480

Before this change `partition key token` was a special entity representing the partition key token, but now it's just an ordinary function call, so it makes sense that its name is `token(i)`.

I think the test should be changed to match the new column name. Although that would probably be incompatible with Cassandra, so maybe we could just remove this line:
```python3
assert stmt.column_metadata[0].name == 'partition key token'
```
I don't see why it would be important to check the column name there.

**Comment by DoronArazii** [comment]
Took by dev, removing 'master/triage'

**Comment by fruch** [comment]
> > @cvybhu can you confirm it is indeed [your change](https://github.com/scylladb/scylladb/commit/1cefb662cd2cfb1474d46901726eee9c55d3bef3#diff-f156f2f21e75de18dc077db531cab59a6a25a9f2c7804aff56143b9d53e66e04L1227) that broke the test?
> 
> Yes that looks like it broke because of https://github.com/scylladb/scylladb/pull/13480
> 
> Before this change `partition key token` was a special entity representing the partition key token, but now it's just an ordinary function call, so it makes sense that its name is `token(i)`.
> 
> I think the test should be changed to match the new column name. Although that would probably be incompatible with Cassandra, so maybe we could just remove this line:
> ```python3
> assert stmt.column_metadata[0].name == 'partition key token'
> ```
> I don't see why it would be important to check the column name there.

It's more than just in a test its in the driver code as well this assumption of the name

@avelanarius might give a better insight as to if it's important or not. Anyhow we can't change this on a datastax driver code, so it might be breaking someones code. That's why we run those integration tests.

**Comment by avikivity** [comment]
> > @cvybhu can you confirm it is indeed [your change](https://github.com/scylladb/scylladb/commit/1cefb662cd2cfb1474d46901726eee9c55d3bef3#diff-f156f2f21e75de18dc077db531cab59a6a25a9f2c7804aff56143b9d53e66e04L1227) that broke the test?
> 
> Yes that looks like it broke because of #13480
> 
> Before this change `partition key token` was a special entity representing the partition key token, but now it's just an ordinary function call, so it makes sense that its name is `token(i)`.
> 
> I think the test should be changed to match the new column name. Although that would probably be incompatible with Cassandra, so maybe we could just remove this line:
> 
> ```python
> assert stmt.column_metadata[0].name == 'partition key token'
> ```
> 
> I don't see why it would be important to check the column name there.

Let's try to maintain compatibility, it's dangerous to play with user-visible strings.

**Comment by cvybhu** [comment]
> Let's try to maintain compatibility, it's dangerous to play with user-visible strings.

Hmm alright, I will take a look and see if it's possible to force the column name to be `partition key token` even with the new `function_call` mechanisms.

**Comment by mykaul** [comment]
Should we revert the offending commit, first of all?

**Comment by cvybhu** [comment]
> Should we revert the offending commit, first of all?

Looks like it requires just a small change, I think this fixes it:

```diff
diff --git a/cql3/expr/prepare_expr.cc b/cql3/expr/prepare_expr.cc
index c2ca1e41d..d287bda68 100644
--- a/cql3/expr/prepare_expr.cc
+++ b/cql3/expr/prepare_expr.cc
@@ -1244,6 +1244,15 @@ static lw_shared_ptr<column_specification> get_lhs_receiver(const expression& pr
             return make_lw_shared<column_specification>(schema.ks_name(), schema.cf_name(), std::move(identifier), std::move(tuple_type));
         },
         [&](const function_call& fun_call) -> lw_shared_ptr<column_specification> {
+            // In case of an expression like `token(p1, p2, p3) = ?` the receiver name should be "partition key token".
+            // This is required for compatibality with the java driver, it breaks with a receiver name like "token(p1, p2, p3)".
+            if (is_partition_token_for_schema(fun_call, schema)) {
+              return make_lw_shared<column_specification>(
+                  schema.ks_name(), schema.cf_name(),
+                  ::make_shared<column_identifier>("partition key token", true),
+                  long_type);
+            }
+
             data_type return_type = std::visit(
                     overloaded_functor{
                         [](const shared_ptr<db::functions::function>& fun) -> data_type { return fun->return_type(); },
```

I will post a quick patch and we could just merge it.

I just need to get back access to my work computer because I ran into some problems with the security system.

**Comment by nyh** [comment]
> I just need to get back access to my work computer because I ran into some problems with the security system.

Sad, but not surprising :-(
A few days ago, said "security system" decided that my super-obfuscated password that I can barely remember was too old (3 months?) so I was forced to change it to something that I even more barely remember. Now I mistype my password half the time. Security theater at its best.

**Comment by avikivity** [comment]
Why? It successfully prevents access to the computer at least 50% of the time, more than before.

If you mistype your own password, I imagine an attacker will mistype it even more.

**Comment by denesb** [comment]
Looks like no backport needed (no branches affected).
