### ISSUE TITLE
multishard_mutation_query: reader_context::lookup_readers() is not exception safe w.r.t. closing readers

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#13784]
When looking up the saved readers on each shard, there is a check which makes sure the looked up reader matches the semaphore used by the read context (the scan as a whole). If there is a mismatch, an exception is triggered, via `on_internal_error()`. The looked-up querier's reader is not closed however, possibly triggering an assert failure in the reader's destructor. Additionally, there is a lookup for the table object, which also happens after the querier was looked up.

**Comment by mykaul** [comment]
@avikivity - can you backport this to relevant branches?

**Comment by avikivity** [comment]
Backported to 5.1, 5.2, 5.3.

**Comment by avikivity** [comment]
Un-backported from 5.1, 5.2. It need generate_partition_key for the unit test, and I got into trouble backporting that.

@denesb please backport to 5.1, 5.2.

**Comment by denesb** [comment]
Re-did backports for 5.2 and 5.1.

**Comment by denesb** [comment]
@mykaul I removed the "Required-Backport-to-5.2" as I assumed it works the same as "Backport candidate" label. Let me know if this is not the case.

**Comment by mykaul** [comment]
> @mykaul I removed the "Required-Backport-to-5.2" as I assumed it works the same as "Backport candidate" label. Let me know if this is not the case.

I'm not sure what the 'Required-...' means - I'll work with @DoronArazii and we'll align the labels a bit. Generally, in OSS, we should probably just have 'Backport candidate' label, and the discussion where to can live within the bug comments.

**Comment by DoronArazii** [comment]
How would you know which versions should have the fix by "Backport Candidate"?
By "Required-Backport-to-5.2" I can ensure that it will be eventually arrive to the infected branch.
BTW, in this case @mykaul added the label so I don't quite know why it was added, the customer is using 2022.1

**Comment by mykaul** [comment]
> How would you know which versions should have the fix by "Backport Candidate"? By "Required-Backport-to-5.2" I can ensure that it will be eventually arrive to the infected branch. BTW, in this case @mykaul added the label so I don't quite know why it was added, the customer is using 2022.1

We don't have 'Required-Backport-to-5.1' though? And soon 'Required-Backport-to-5.3' ?

**Comment by DoronArazii** [comment]
> We don't have 'Required-Backport-to-5.1' though? And soon 'Required-Backport-to-5.3' ?

I will create.

**Comment by mykaul** [comment]
> > How would you know which versions should have the fix by "Backport Candidate"?
> 
> The rule to determine that is as follows:
> 
> * author of the fix should state which is the earliest affected version

This could / should be stated via lablels - then it'd be easier to track and ensure we did not miss backports perhaps? (As I assume right now it's via a comment, which can be easily lost)

> * maintainer will then backport to the earliest supported version that is >= than this version and all later versions

**Comment by denesb** [comment]
> > * author of the fix should state which is the earliest affected version
> 
> This could / should be stated via lablels - then it'd be easier to track and ensure we did not miss backports perhaps? (As I assume right now it's via a comment, which can be easily lost)

Yes, but note that not all have right to create labels. An alternative is to require all bugs to state affected version. But that will require oversight as some people will ignore the requirement. So at that point a lable might be better.

> 
> > * maintainer will then backport to the earliest supported version that is >= than this version and all later versions
> 
> I think the order is also important here - from latest to earliest.

Yes.
