### ISSUE TITLE
docs: Issue in page Nodetool - nodetool checkAndRepairCdcStreams is not documented

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylladb#13783]
I would like to report an issue in page https://enterprise.docs.scylladb.com/branch-2022.2/operating-scylla/nodetool

### Problem

nodetool checkAndRepairCdcStreams
is not documented

###  Suggest a fix

please document above (either based on help from nodetool or from developers)

**Comment by denesb** [comment]
Improvement, not backporting.
