### ISSUE TITLE
on_internal_error doesn't log an error when not aborting

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13786]
[this issue is opened for backporting purposes]

Refs https://github.com/scylladb/seastar/issues/1648

Up until scylladb/seastar@40c03bb8ddef9f7097cca798ff55cc3110cbcd85, on_internal_error would log the error only when abort_on_internal_error is set, right before aborting.

On the other path, when throwing the exception, it would print nothing to the log.
This is wrong. The internal error must be visible as we're on a very high risk path and recovering from that error is not always possible.

**Comment by bhalevy** [comment]
Fixed with e103ef3bcb7d0ec30e0375096c527e33659aa0ad

Refs https://github.com/scylladb/seastar/pull/1584

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider backporting to all live versions

**Comment by denesb** [comment]
Backported to all 5.x.
