### ISSUE TITLE
rust: low-severity CVE in dependency

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#13807]
Currently used version (5.0.1) of the Wasmtime dependency that we're using has a vulnerability that may result in undefined behaviour when using Wasm user-defined functions. The fix is available in versions 6.0.2, 7.0.1 and 8.0.1

**Comment by wmitros** [comment]
The issue is also present in branch 5.2, but there should be no conflicts when backporting

**Comment by denesb** [comment]
Backported to 5.2.
