### ISSUE TITLE
docs: Issue in page System Requirements - break cloud recommendation to different pages

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13808]
I would like to report an issue on page https://docs.scylladb.com/branch-5.2/getting-started/system-requirements

### Problem

The page is long, and finding a cloud (e.g. Azure) instance type without scrolling is hard. The Cloud headers are not part of any menu.

###  Suggest a fix

Break each cloud into a dedicated page, including snitch, instance types, Scylla Cloud info, etc

**Comment by denesb** [comment]
Improvement, not backporting.
