### ISSUE TITLE
Scylla shard aware consumes more cpu & high latency

### ISSUE THREAD

**Issue by altanozlu** [scylladb/scylladb#13827]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.0.10-0.20230207.6bb7fac8d
Cluster size: 1 node 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Linux 5.4.0-1100-gcp #109~18.04.1-Ubuntu

*Hardware details (for performance issues)*         : 
Platform (physical/VM/cloud instance type/docker): gcp t2d-standard-8 (8 core 32gb ram)
Hardware: sockets= cores= hyperthreading= memory=
Disks: 1tb ssd

We have rolled out gocql shard aware driver with connecting to 19042 and our latency has increased also cpu usage of scylladb server is increased, after changing back to 9042 latency has dropped to normal levels.

scylladb/gocql version is 1.7.3
<img width="1054" alt="Screenshot 2023-05-09 at 17 10 31" src="https://github.com/scylladb/scylladb/assets/5479094/3c3047df-bdf0-4c38-abae-337fe6d50f87">

<img width="635" alt="Screenshot 2023-05-09 at 17 10 07" src="https://github.com/scylladb/scylladb/assets/5479094/72b3ecec-7934-4131-acc3-6bb666b30bb8">

**Comment by dorlaor** [comment]
We don't have experience with t2d VMs - are all cores assigned to the VM
all the time? Is the storage local NVMe? Did you run scylla setup to make
sure
it benchmarks the disk?

Best to use the off the shelf AMI

**Comment by avelanarius** [comment]
> We have rolled out gocql shard aware driver with connecting to 19042 and our latency has increased also cpu usage of scylladb server is increased, after changing back to 9042 latency has dropped to normal levels.

Just to clarify: When you changed back to port 9042, did you also change the driver (to a non-shard-aware gocql driver)?

**Comment by altanozlu** [comment]
I've updated my driver from 1.6.0 to 1.7.3 and set port to 19042 then latency increased(16:57) after i've just changed port to 9042 (17:24) then latency come back to normal. I think it's just about enabling shard aware port.
Also we use ssd pd not nvme, and all cores has been assigned to vm. Btw it's been used for a year like this and problem only occurred when enabling 19042 port.

<img width="1054" alt="Screenshot 2023-05-09 at 18 56 40" src="https://github.com/scylladb/scylladb/assets/5479094/7ee00e9f-acc6-4e07-927f-b83e07cad3da">

<img width="592" alt="Screenshot 2023-05-09 at 18 58 44" src="https://github.com/scylladb/scylladb/assets/5479094/c1a92632-7a24-486b-ad84-1f6f9dbf2977">

**Comment by avikivity** [comment]
Please share your perftune.yaml.

Some increase in network traffic and CPU usage is expected, since the traffic is spread over more connections, resulting in more packets sent.

**Comment by altanozlu** [comment]
> Please share your perftune.yaml.
> 
> Some increase in network traffic and CPU usage is expected, since the traffic is spread over more connections, resulting in more packets sent.

Hi i don't have perftune.yaml in /etc/scylla/ and /etc/scylla.d/

**Comment by avikivity** [comment]
Did you not run scylla_setup? How is it even running?

**Comment by altanozlu** [comment]
I did run it 🤔 
io_properties.yaml:
```
disks:
  - mountpoint: /
    read_iops: 14984
    read_bandwidth: 741173184
    write_iops: 17053
    write_bandwidth: 739584896
```

**Comment by altanozlu** [comment]
hi @avikivity is there anything i can do rn ?

**Comment by vladzcloudius** [comment]
> @vladzcloudius I'm suspecting irq core misconfiguration, but don't know how to check it.
> 
> Note these instances have SMT disabled.

Let's see all syslog lines that have "scylla_prepare" - printed when the service is starting, @altanozlu .

**Comment by altanozlu** [comment]
Hmm it could be a thing about non-prepared statements 🤔 i have deployed 19042 again at 08:36 and reverted it 08:44
<img width="532" alt="Screenshot 2023-05-12 at 11 48 10" src="https://github.com/scylladb/scylladb/assets/5479094/4a4a1822-ae64-422a-a327-232f183979a4">

**Comment by vladzcloudius** [comment]
> journalctl _COMM=scylla --since "2023-05-10 10:00:00" | grep scylla_prepare returns no result

This suggests that you haven't enabled perftune.py tweaking (check the `SET_NIC_AND_DISKS` in `/etc/default/scylla-server`.

If it's set to 'no' then my guess is right. As a result you are not going to enjoy Scylla to the fullest ;)

You were supposed to enable it via a corresponding item when you ran `scylla_setup` and it's strongly recommented to do so.

**Comment by vladzcloudius** [comment]
> Hmm it could be a thing about non-prepared statements thinking i have deployed 19042 again at 08:36 and reverted it 08:44 <img alt="Screenshot 2023-05-12 at 11 48 10" width="532" src="https://user-images.githubusercontent.com/5479094/237920429-4a4a1822-ae64-422a-a327-232f183979a4.png">

FYI: Share-aware feature which runs on top of Token Awareness works only with prepared statements.

**Comment by altanozlu** [comment]
here is my /etc/default/scylla-server
>
```

# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME=ens4

# setup NIC's and disks' interrupts, RPS, XPS, nomerges and I/O scheduler (posix)
SET_NIC_AND_DISKS=yes

# tune clocksource
SET_CLOCKSOURCE=no

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=no

# Disable disk writeback cache
DISABLE_WRITEBACK_CACHE=no
```



> > Hmm it could be a thing about non-prepared statements thinking i have deployed 19042 again at 08:36 and reverted it 08:44 <img alt="Screenshot 2023-05-12 at 11 48 10" width="532" src="https://user-images.githubusercontent.com/5479094/237920429-4a4a1822-ae64-422a-a327-232f183979a4.png">
> 
> FYI: Share-aware feature which runs on top of Token Awareness works only with prepared statements.

normally gocql prepares statements and you don't have to do anything.

**Comment by vladzcloudius** [comment]
> normally gocql prepares statements and you don't have to do anything.

It's not normally - it's always.
However the `PREPARE` statement it's going to sent is naturally "unprepared" ;)

> SET_NIC_AND_DISKS=yes
Then it's weird that you don't see corresponding messages from `scylla_prepare` when you restart the service.

Can I see the content of `/etc/scylla.d/cpuset.conf` and `/etc/scylla.d/perftune.yaml`?

**Comment by altanozlu** [comment]
> > normally gocql prepares statements and you don't have to do anything.
> 
> It's not normally - it's always. However the `PREPARE` statement it's going to sent is naturally "unprepared" ;) If you see many of these means that your query string is not "parametrized" and have parameters values inline.
> 
> For example:
> 
> ```
> # Good!
> session.Query(`INSERT INTO tweet (timeline, id, text) VALUES (?, ?, ?)`,
>         "me", gocql.TimeUUID(), "hello world").Exec()
> 
> # Not good!
> session.Query(`INSERT INTO tweet (timeline, id, text) VALUES ("me", "04079e95-431f-48d8-9e32-72f4a4e27393", "hello world")).Exec()
> ```
> 
> > SET_NIC_AND_DISKS=yes
> > Then it's weird that you don't see corresponding messages from `scylla_prepare` when you restart the service.
> 
> Can I see the content of `/etc/scylla.d/cpuset.conf` and `/etc/scylla.d/perftune.yaml`?

here is my code:

```go
stm := "select relation_type from relations where user_id = ? and other_user_id = ?"
err := r.scylla.Query(stm, userID, otherUserID).WithContext(ctx).Scan(&relationType)
```

cpuset.conf:
`CPUSET="--cpuset 1-7 "`
and as i said i don't have /etc/scylla.d/perftune.yaml
i've run scylla_setup again and still don't have it (i skip xfs and swap steps)

**Comment by mykaul** [comment]
@vladzcloudius - any idea on the above?

**Comment by altanozlu** [comment]
I've created another node and drained the node in the issue. New node has /etc/scylla.d/perftune.yaml and shard aware driver seems to work fine now.

**Comment by mykaul** [comment]
Great news @altanozlu - shall we close the issue?

**Comment by altanozlu** [comment]
sure!

**Comment by vladzcloudius** [comment]
> @vladzcloudius - any idea on the above?

perftune.yaml is not created by `scylla_setup`. It's created by `scylla-service` when it starts for the first time **if tweaking was previously enabled by scylla_setup**.

fyi @mykaul
