### ISSUE TITLE
Seeing "deserialization buffer underflow" after upgrading a master node to enterprise

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#13838]
Reproducer:
* Create a 2 node cluster of OSS master nodes (dev build), node1 is the seed node.
* Start up node1
* Start up node2
* After a while, stop node2
* Upgrade node2 to scylla enterprise (also dev build)
* Start node2

I see the following in the logs of node1 (OSS node):
```
INFO  2023-05-10 03:48:02,934 [shard 0] rpc - client 127.0.0.2:55306 msg_id 2:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:03,590 [shard 0] rpc - client 127.0.0.2:55306 msg_id 3:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:04,634 [shard 0] rpc - client 127.0.0.2:55306 msg_id 4:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:04,990 [shard 0] rpc - client 127.0.0.2:55306 msg_id 5:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:06,290 [shard 0] rpc - client 127.0.0.2:55306 msg_id 6:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:06,335 [shard 0] rpc - client 127.0.0.2:55306 msg_id 7:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:07,890 [shard 0] rpc - client 127.0.0.2:55306 msg_id 8:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:08,236 [shard 0] rpc - client 127.0.0.2:55306 msg_id 9:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:09,790 [shard 0] rpc - client 127.0.0.2:55306 msg_id 10:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:09,937 [shard 0] rpc - client 127.0.0.2:55306 msg_id 11:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:11,090 [shard 0] rpc - client 127.0.0.2:55306 msg_id 12:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:11,337 [shard 0] rpc - client 127.0.0.2:55306 msg_id 13:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:12,891 [shard 0] rpc - client 127.0.0.2:55306 msg_id 14:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:12,938 [shard 0] rpc - client 127.0.0.2:55306 msg_id 15:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
INFO  2023-05-10 03:48:13,991 [shard 0] rpc - client 127.0.0.2:55306 msg_id 16:  caught exception while processing a message: std::out_of_range (deserialization buffer underflow)
```

It is spammed continuously.

**Comment by mykaul** [comment]
@bhalevy - This 'deserialization' reminds me something you've worked on recently?

**Comment by bhalevy** [comment]
which versions exactly?
I wonder if this could be related to the raft tagged_unit64 bug

**Comment by denesb** [comment]
> which versions exactly?

It was just `master` and `enterprise` from the point in time when this issue was opened. I don't think I still have the branches checked out.

**Comment by bhalevy** [comment]
This is most likely a duplicate of https://github.com/scylladb/scylladb/issues/13752
if you caught enterprise before merging the tagged_integer change in master

**Comment by bhalevy** [comment]
Not sure if upgrading master to enterprise at an arbitrary point in time even makes sense, since enterprise lags behind master, so it would usually be a downgrade.

**Comment by denesb** [comment]
> This is most likely a duplicate of #13752 if you caught enterprise before merging the tagged_integer change in master

Looks plausible, I will close this.

**Comment by denesb** [comment]
> Not sure if upgrading master to enterprise at an arbitrary point in time even makes sense, since enterprise lags behind master, so it would usually be a downgrade.

Yeah, I didn't expect it to work flawlessly, but this looked like a quite serious bug that we want to address.

**Comment by bhalevy** [comment]
> > Not sure if upgrading master to enterprise at an arbitrary point in time even makes sense, since enterprise lags behind master, so it would usually be a downgrade.
> 
> Yeah, I didn't expect it to work flawlessly, but this looked like a quite serious bug that we want to address.

I think that the other way around (upgrading enterprise to master both sampled together at any given point in time) should always work.
Maybe worth pursuing by qa.  Cc @roydahan do you test anything similar regularly?

**Comment by roydahan** [comment]
> > > Not sure if upgrading master to enterprise at an arbitrary point in time even makes sense, since enterprise lags behind master, so it would usually be a downgrade.
> > 
> > 
> > Yeah, I didn't expect it to work flawlessly, but this looked like a quite serious bug that we want to address.
> 
> I think that the other way around (upgrading enterprise to master both sampled together at any given point in time) should always work. Maybe worth pursuing by qa. Cc @roydahan do you test anything similar regularly?

No, because it's not a supported upgrade path.

**Comment by bhalevy** [comment]
To catch regressions in IDL we can do an upgrade test in dtest-release-daily between e.g. the most recent release branch (e.g. 5.2) to master (or the equivalent for enterprise), although it's not a supported upgrade path.

**Comment by roydahan** [comment]
> To catch regressions in IDL we can do an upgrade test in dtest-release-daily between e.g. the most recent release branch (e.g. 5.2) to master (or the equivalent for enterprise), although it's not a supported upgrade path.

This path is supported and tested.
We don't support enterprise to master.
