### ISSUE TITLE
docs: Issue in page System Requirements - update Azure instance types to the lasv3-series

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13833]
I would like to report an issue in page https://docs.scylladb.com/branch-5.2/getting-started/system-requirements

### Problem

The recomended instance types for Azure is lsv2

###  Suggest a fix

The recomended instance types for Azure should be updated to [lsv3](https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series)

**Comment by tzach** [comment]
https://github.com/scylladb/scylladb/pull/13835

**Comment by annastuchlik** [comment]
Fixed with https://github.com/scylladb/scylladb/pull/13835.
