### ISSUE TITLE
Suggest adding support for new AWS i4g instances

### ISSUE THREAD

**Issue by AccretiveUser** [scylladb/scylladb#13830]
AWS has a new storage-optimzed instance type today:

https://aws.amazon.com/blogs/aws/new-storage-optimized-amazon-ec2-i4g-instances-graviton-processors-and-aws-nitro-ssds/

**Comment by mykaul** [comment]
cc @roydahan

**Comment by roydahan** [comment]
@yaronkaikov was it followed by extending the list of instances to be tested as part of ami-test?
If not, it shouldn't be marked as DONE.

**Comment by yaronkaikov** [comment]
@roydahan No we didn't extend the list, please advice which instance type should we trigger in master and releases

**Comment by roydahan** [comment]
> @roydahan No we didn't extend the list, please advice which instance type should we trigger in master and releases

IIRC, we moved to "cover all" approach in releases, so this is easy.
In master I would take a 2xlarge or something like that that is quite common.

**Comment by roydahan** [comment]
@ShlomiBalalis FYI that there are new ARM instances that are going to be supported and the perftune results should still match your tests.
