### ISSUE TITLE
Enabling features on boot is slow (even in dev mode)

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13837]
This is something I've noticed in the past month or two (?) - I don't know when exactly it started.
Anyway it takes a noticeable fraction of a second to enable each feature. With the number of features we have this significantly slows down the boot process.
In debug it's even worse obviously.
@tgrabiec confirmed that he also noticed that.

We should investigate where the slowness comes from and where it started. I'm pretty sure it's a regression.

**Comment by mykaul** [comment]
Does it make sense to git bisect it, or is it too much history?

**Comment by kbr-scylla** [comment]
I think it makes sense. Bisect will be fast even with large history.

**Comment by nyh** [comment]
@kbr-scylla good catch, I hate those slow boots :-( I didn't see this happening in a single-node test/alternator/run et al., where boot time has remained around 0.4 seconds (although now that I think of it, maybe this too is slower than the 0.3 second I seem to remember from the past?). Maybe this has something to do with waiting for these features to be gossiped on a multi-node cluster?

**Comment by kbr-scylla** [comment]
@nyh this is happening for single node boot too.

Just look at the times:
```
INFO  2023-05-10 10:05:58,577 [shard 0] features - Feature SECONDARY_INDEXES_ON_STATIC_COLUMNS is enabled
INFO  2023-05-10 10:05:58,646 [shard 0] features - Feature LARGE_COLLECTION_DETECTION is enabled
INFO  2023-05-10 10:05:58,990 [shard 0] features - Feature COLLECTION_INDEXING is enabled
INFO  2023-05-10 10:05:59,332 [shard 0] features - Feature PER_TABLE_PARTITIONERS is enabled
INFO  2023-05-10 10:05:59,666 [shard 0] features - Feature LWT is enabled
INFO  2023-05-10 10:05:59,714 [shard 0] features - Feature NONFROZEN_UDTS is enabled
INFO  2023-05-10 10:05:59,765 [shard 0] features - Feature RANGE_SCAN_DATA_VARIANT is enabled
INFO  2023-05-10 10:05:59,815 [shard 0] features - Feature COMPUTED_COLUMNS is enabled
INFO  2023-05-10 10:05:59,860 [shard 0] features - Feature PARALLELIZED_AGGREGATION is enabled
INFO  2023-05-10 10:05:59,909 [shard 0] features - Feature DIGEST_INSENSITIVE_TO_EXPIRY is enabled
INFO  2023-05-10 10:05:59,951 [shard 0] features - Feature VIEW_VIRTUAL_COLUMNS is enabled
INFO  2023-05-10 10:05:59,989 [shard 0] features - Feature MD_SSTABLE_FORMAT is enabled
INFO  2023-05-10 10:06:00,008 [shard 0] features - Feature CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX is enabled
INFO  2023-05-10 10:06:00,028 [shard 0] features - Feature CDC_GENERATIONS_V2 is enabled
INFO  2023-05-10 10:06:00,049 [shard 0] features - Feature DIGEST_FOR_NULL_VALUES is enabled
INFO  2023-05-10 10:06:00,072 [shard 0] features - Feature ALTERNATOR_TTL is enabled
INFO  2023-05-10 10:06:00,095 [shard 0] features - Feature PER_TABLE_CACHING is enabled
INFO  2023-05-10 10:06:00,118 [shard 0] features - Feature HINTED_HANDOFF_SEPARATE_CONNECTION is enabled
INFO  2023-05-10 10:06:00,144 [shard 0] features - Feature CDC is enabled
INFO  2023-05-10 10:06:00,175 [shard 0] features - Feature SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT is enabled
INFO  2023-05-10 10:06:00,199 [shard 0] features - Feature ME_SSTABLE_FORMAT is enabled
INFO  2023-05-10 10:06:00,223 [shard 0] features - Feature UDA is enabled
INFO  2023-05-10 10:06:00,247 [shard 0] features - Feature EMPTY_REPLICA_PAGES is enabled
INFO  2023-05-10 10:06:00,269 [shard 0] features - Feature TOMBSTONE_GC_OPTIONS is enabled
INFO  2023-05-10 10:06:00,293 [shard 0] features - Feature AGGREGATE_STORAGE_OPTIONS is enabled
INFO  2023-05-10 10:06:00,316 [shard 0] features - Feature TYPED_ERRORS_IN_READ_RPC is enabled
INFO  2023-05-10 10:06:00,340 [shard 0] features - Feature SUPPORTS_RAFT_CLUSTER_MANAGEMENT is enabled
INFO  2023-05-10 10:06:00,375 [shard 0] features - Feature SCHEMA_COMMITLOG is enabled
INFO  2023-05-10 10:06:00,399 [shard 0] features - Feature UDA_NATIVE_PARALLELIZED_AGGREGATION is enabled
```

Hm, does it depend on the feature or is it randomness? Some features took 300ms to enable (`COLLECTION_INDEXING`, `PER_TABLE_PARTITIONERS`). Others took 20ms.

**Comment by kbr-scylla** [comment]
It's super fast when I put the work directory in `/tmp`. Maybe the slowness is caused by persisting enabled features. But I don't recall this slowness at the time when we first introduced persisting enabled features.

We should perhaps consider looking for a way to persist enabled features in bulk, but we should also see if there wasn't e.g. a regression in commitlog (btw. IIRC the features are persisted in sync mode).

**Comment by kbr-scylla** [comment]
Maybe it's a regression of my SSD :)

**Comment by kbr-scylla** [comment]
The algorithm is really not the smartest to say the least:
```cpp
void feature_service::persist_enabled_feature_info(const gms::feature& f) const {
    // Executed in seastar::async context, because `gms::feature::enable`
    // is only allowed to run within a thread context

    std::set<sstring> feats_set = db::system_keyspace::load_local_enabled_features().get0();
    feats_set.emplace(f.name());
    db::system_keyspace::save_local_enabled_features(std::move(feats_set)).get0();
}

future<> feature_service::enable(std::set<std::string_view> list) {
    // `gms::feature::enable` should be run within a seastar thread context
    return seastar::async([this, list = std::move(list)] {
        for (gms::feature& f : _registered_features | boost::adaptors::map_values) {
            if (list.contains(f.name())) {
                if (db::qctx && !f) {
                    persist_enabled_feature_info(f);
                }
                f.enable();
            }
        }
    });
}
```

For each feature we load the whole set of enabled features from disk, then persist the whole set again with the feature added...

Maybe it's the read which is taking so long.

**Comment by kbr-scylla** [comment]
@nyh it's easy to fix the algorithm, but I think that before we do that, we should find out whether there was a regression after the algorithm was introduced. As I said, I don't think it was as slow initially. The read/writes themselves might have slowed down at some point.

**Comment by tgrabiec** [comment]
@xemul Is working to improve this as far as I know.

**Comment by avikivity** [comment]
You should be using --unsafe-bypass-fsync and --kernel-page-cache.

**Comment by xemul** [comment]
> @nyh it's easy to fix the algorithm, but I think that before we do that, we should find out whether there was a regression after the algorithm was introduced. As I said, I don't think it was as slow initially. The read/writes themselves might have slowed down at some point.

@kbr-scylla , I think it could be "regressed" by 737f4acc10d5b798b89697095cdce2d66d2e9685 prior to which enabling and sysks read-update-write happened on shard-0 only

**Comment by kbr-scylla** [comment]
Do we need to do the disk operations on all shards? We do need to see which features are enabled on all shards, but that's just in-memory state, the on-disk part could only happen on shard 0, no?

**Comment by xemul** [comment]
> Do we need to do the disk operations on all shards?

No we don't

> We do need to see which features are enabled on all shards, but that's just in-memory state, the on-disk part could only happen on shard 0, no?

Yes. The commit's goal was to fix a bug, sysks being updated on all shards was ... unwanted side effect of it :( and #13172 makes sysks update happen on shard-0 only as well

**Comment by nyh** [comment]
> > The algorithm is really not the smartest to say the least:
> > ```c++
> > void feature_service::persist_enabled_feature_info(const gms::feature& f) const {
> >     // Executed in seastar::async context, because `gms::feature::enable`
> >     // is only allowed to run within a thread context
> > 
> >     std::set<sstring> feats_set = db::system_keyspace::load_local_enabled_features().get0();
> >     feats_set.emplace(f.name());
> >     db::system_keyspace::save_local_enabled_features(std::move(feats_set)).get0();
> > }
> > 
> > future<> feature_service::enable(std::set<std::string_view> list) {
> >     // `gms::feature::enable` should be run within a seastar thread context
> >     return seastar::async([this, list = std::move(list)] {
> >         for (gms::feature& f : _registered_features | boost::adaptors::map_values) {
> >             if (list.contains(f.name())) {
> >                 if (db::qctx && !f) {
> >                     persist_enabled_feature_info(f);
> >                 }
> >                 f.enable();
> >             }
> >         }
> >     });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For each feature we load the whole set of enabled features from disk, then persist the whole set again with the feature added...
> > Maybe it's the read which is taking so long.
> 
> @kbr-scylla , @nyh , it's (partially) fixed in #13172

Thanks. I see that https://github.com/scylladb/scylladb/pull/13172/commits/1461a892a664c411462e68212970836d58a84f1f indeed persists all the changes in one go instead of each one separately.

**Comment by xemul** [comment]
@kbr-scylla , please, confirm (or deny) that #13172 fixes it

**Comment by kbr-scylla** [comment]
Yes, enabling features and startup in general is noticeably faster with your PR.

**Comment by avikivity** [comment]
Performance only (and for just metadata), not backporting.
