### ISSUE TITLE
messaging: when upgrading OSS nodes to Enterprise, service-levels are matched to the default scheduling group

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#13841]
On connection setup, the isolation cookie of the connection is matched to the appropriate scheduling group. This is achieved by iterating over the known statement tenant connection types as well as the system connections and choosing the one with a matching name.

If a match is not found, it is assumed that the cluster is upgraded and the remote node has a scheduling group the local one doesn't have. To avoid demoting a scheduling group of unknown importance, in this case the default scheduling group is chosen.

This is problematic when upgrading an OSS cluster to an enterprise version, as the scheduling groups of the enterprise service-levels will match none of the statement tenants and will hence fall-back to the default scheduling group. As a consequence, while the cluster is mixed, user workload on old (OSS) nodes, will be executed under the system scheduling group and concurrency semaphore. Not only does this mean that user workloads are directly competing for resources with system ones, but the two workloads are now sharing the semaphore too, reducing the available throughput. This usually manifests in queries timing out on the old (OSS) nodes in the cluster.

**Comment by mykaul** [comment]
I'm unsure why the backport candidate was removed here - @denesb  ?

**Comment by denesb** [comment]
> I'm unsure why the backport candidate was removed here - @denesb ?

The backport candidate lable *is* on this issue, added by the bot, as it's supposed to do.

**Comment by mykaul** [comment]
> > I'm unsure why the backport candidate was removed here - @denesb ?
> 
> The backport candidate lable _is_ on this issue, added by the bot, as it's supposed to do.

err - you are right  - wrong bug. 

Need maintainers to backport I guess - it had the label set 1.5 months ago.

**Comment by denesb** [comment]
Backported to 5.3, 5.2 and 5.1. No point in backporting to enterprise releases, the fix only affects OSS.
