### ISSUE TITLE
[UDF] Can't format the resource for a function with no arguments

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#13842]
There are 2 main cases where a query normally result in an error message that includes the formatted resource: 
```
cassandra@cqlsh> GRANT EXECUTE ON TABLE ks.t TO mike;
SyntaxException: Resource <table ks.t1> does not support any of the requested permissions.
```
and
```
cassandra@cqlsh> GRANT SELECT ON TABLE ks.abc123 TO mike;
InvalidRequest: Error from server: code=2200 [Invalid query] message="<table ks.abc> doesn't exist."
```

Scylla crashes if the modified permission is on a function with no arguments:
```
cassandra@cqlsh> GRANT EXECUTE ON FUNCTION ks.fun() TO mike;
OperationTimedOut: errors={'127.0.0.1:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.0.1:9042
```

**Comment by denesb** [comment]
@wmitros do we need to backport this?

**Comment by mykaul** [comment]
> @wmitros do we need to backport this?

Isn't UDF experimental? I don't see a strong reason to.

**Comment by wmitros** [comment]
> @wmitros do we need to backport this?

The `resource` here is only used in UDF permissions, and we only have UDF permissions since 5.4, so there's nothing to backport
