### ISSUE TITLE
"cannot append clustering row" runtime error seen by user

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13876]
A user from Stackoverflow reported in https://stackoverflow.com/questions/76227522/scylla-cannot-append-clustering-row that he got the error message:

>  <IP address>:9042 replied with server error (mutation_partition::append_clustered_row(): cannot append clustering row with key {position: clustered,ckp{00024174000400000000},0} to the partition, last clustering row is equal or greater: ckp{0002426300042d3ce7c5}), defuncting connection.

The user is puzzled what this means (saying "It sounds like a corrupted SS table. Is this situation recoverable? Should the mutation be retried?"), and so am I. Does this error message indicate a bug in Scylla, and if so, should we use `on_internal_error()` instead of of a `runtime_error`, to 1. give us a backtrace and 2. tell the user it's a bug, not some incorrect request on his part.

Without a backtrace I don't know how to even guess in what context was this `append_clustered_row()` tried and failed. @denesb, do you have any ideas or suggestions?

**Comment by denesb** [comment]
> The user reported that he was using Scylla 4.6.11-0.20221128.6c0825e2a and that he "can't reproduce this issue yet. It's a tiny fraction of all requests and not an actual problem but it sounds serious enough to find out what it means."

First of all, he has to upgrade to a version we support (5.1) because we will not investigate a bug in an EOL'd version.

**Comment by denesb** [comment]
Improvement, not backporting.
