### ISSUE TITLE
docs: Issue in page CDC Overview - Add Rust connector to Java and Go

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13877]
I would like to report an issue in page https://docs.scylladb.com/master/using-scylla/cdc/cdc-intro.html#using-cdc-with-applications

### Problem

The [new CDC Rust connector](https://github.com/scylladb/scylla-cdc-rust ) is missing 

###  Suggest a fix

Add Rust to every CDC related info
including the above and https://docs.scylladb.com/stable/using-scylla/drivers/cql-drivers/index.html

**Comment by denesb** [comment]
Improvement, not backporting.
