### ISSUE TITLE
Alternator CreateTable operator should refuse duplicate AttributeName in AttributeDefinitions

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13870]
In an Alternator `CreateTable` operation, the user is expected to pass a `AttributeDefinitions` parameter to declare the type of the key attributes (for either base or GSI/LSI key attributes). It looks like:
```
        AttributeDefinitions=[
            { 'AttributeName': 'p', 'AttributeType': 'S' },
            { 'AttributeName': 'x', 'AttributeType': 'S' },
        ], 
```
Note that somewhat unfortunately, this parameter is a **list**, not a map, so the user can be tempted to repeate the same AttributeName twice, perhaps even with a different type, e.g.,
```
        AttributeDefinitions=[
            { 'AttributeName': 'p', 'AttributeType': 'S' },
            { 'AttributeName': 'x', 'AttributeType': 'S' },
            { 'AttributeName': 'x', 'AttributeType': 'N' },
        ],
 ```
Why would a user ever do this? I don't know. It might be, for example, some ill-fated attempt to create two different GSIs with the same key but using different types (which doesn't even make sense, because which attribute definition applies to which GSI?). In any case, DynamoDB prints the following error in this case:

> An error occurred (ValidationException) when calling the CreateTable operation: Attribute Name is duplicated: x

We currently don't - the error is silently ignored and one of the two definitions (I didn't check which) takes effect. We should make it into an error like DynamoDB does.

**Comment by denesb** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
As the commit explains, this fix improves the error experience but isn't necessary for correctness or safety. So no need to backport. Removing the backport candidate tag.
