### ISSUE TITLE
Log which peer node that has the error in repair error log

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#13881]
It would be helpful to locate the exact node that has the error. 

For example, we when see

scylla[15000]:  [shard 12] repair - repair id [id=49957, uuid=a73840ce-6869-4753-9312-0d7802d12499] on shard 12, keyspace=system_auth, cf=roles, range=(-inf, 9223372036854775807], got error in row level repair: std::runtime_error (compressed reader out of sync)

It would be helpful if we know which node has the error to locate the corrupted sstable.

**Comment by denesb** [comment]
Improvement, not backporting.

**Comment by mykaul** [comment]
> Improvement, not backporting.

For easier debuggability, probably worth backporting.

**Comment by denesb** [comment]
Ok, the patch looks very low-risk so I backported to 5.2.
