### ISSUE TITLE
Async functions yield while traversing the gossiper endpoint state map

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13899]
Currently, there are several places where async functions access the gossiper endpoint state map using `get_endpoint_states` (or internally in gossiper via `_endpoint_state_map` and they might preempt while traversing the map.

This is dangerous since rehashing the map keys while yielding may invalidate outstanding iterators.
See https://en.cppreference.com/w/cpp/container/unordered_map/insert
```
If rehashing occurs due to the insertion, all iterators are invalidated.
```

The places that need to be fixed according to my examination are:

https://github.com/scylladb/scylladb/blob/b112a3b78a4fa8b92216b3ec9920270100e40a85/gms/gossiper.cc#L721
since a01c900d66c1f0ba448c97dba14852cd3f0d0c8e (5.0)

https://github.com/scylladb/scylladb/blob/b112a3b78a4fa8b92216b3ec9920270100e40a85/service/storage_service.cc#L1821
Since 84a78f45580b2397b8938b219e12ecfa8a757b49 (4.6)

https://github.com/scylladb/scylladb/blob/b112a3b78a4fa8b92216b3ec9920270100e40a85/service/storage_service.cc#L2834
Since forever pretty much

**Comment by bhalevy** [comment]
I think that we didn't hit this so far (that we know of) due to fortunate timing and the scarcity of node operations.

**Comment by denesb** [comment]
Doesn't apply to 5.2 cleanly, @bhalevy please provide a backport PR.

**Comment by bhalevy** [comment]
> Doesn't apply to 5.2 cleanly, @bhalevy please provide a backport PR.

@denesb: https://github.com/scylladb/scylladb/pull/16431

**Comment by denesb** [comment]
Backport to 5.2 queued.
