### ISSUE TITLE
Schema agreement waiting exits too soon with raft-based topology

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#13911]
Observed sporadically in `./test.py --mode dev test_tablets -s` after it is moved to topology_experimental_raft (6f5e91b74c). Manifests as later CQL request failures due to the coordinator not knowing yet about the table. The reason is that the driver ACKs the schema change before the peers processes it.

Driver trace reveals that the reason is that the query for system.peers returns rows with rpc_address and schema_version columns not set:

```
00:03:40.618 DEBUG> [control connection] Waiting for schema agreement
00:03:40.620 DEBUG> peers <FastResultMessage(kind=2, column_metadata=[('system', 'peers', 'peer', <class 'cassandra.cqltypes.InetAddressType'>), ('system', 'peers', 'host_id', <class 'cassandra.cqltypes.UUIDType'>), ('system', 'peers', 'rpc_address', <class 'cassandra.cqltypes.InetAddressType'>), ('system', 'peers', 'schema_version', <class 'cassandra.cqltypes.UUIDType'>)], column_names=['peer', 'host_id', 'rpc_address', 'schema_version'], column_types=[<class 'cassandra.cqltypes.InetAddressType'>, <class 'cassandra.cqltypes.UUIDType'>, <class 'cassandra.cqltypes.InetAddressType'>, <class 'cassandra.cqltypes.UUIDType'>], 

parsed_rows=[
  ('127.246.194.3', UUID('59adb24e-f3cd-3e02-97f0-5b395827453f'), None, None), 
  ('127.246.194.4', UUID('41c5dcd6-d98e-4767-9201-6e9d0ad6d885'), None, None)
], stream_id=3, trace_id=None)>

local <FastResultMessage(kind=2, column_metadata=[('system', 'local', 'schema_version', <class 'cassandra.cqltypes.UUIDType'>)], column_names=['schema_version'], column_types=[<class 'cassandra.cqltypes.UUIDType'>], parsed_rows=[(UUID('0e6dc6c9-399e-3961-886f-0a05c93c6d81'),)], stream_id=4, trace_id=None)>

00:03:40.620 DEBUG> versions defaultdict(<class 'set'>, {UUID('0e6dc6c9-399e-3961-886f-0a05c93c6d81'): {<DefaultEndPoint: 127.246.194.2:9042>}})
00:03:40.620 DEBUG> [control connection] Schemas match
```

As a result, the versions dict contains only the local version, which matches.

The reason for this is that when a peer is marked as UP, and `storage_service::on_change()` is processed, the node is not yet part of token metadata, and hence it's ignored:

```
DEBUG 2023-05-17 00:47:31,841 [shard 0] storage_service - endpoint=127.171.144.3 on_change:     app_state=SCHEMA, versioned_value=Value(f842d79a-af53-3cf9-8bc5-d4900b92a749,21)
DEBUG 2023-05-17 00:47:31,841 [shard 0] storage_service - endpoint=127.171.144.3 not a normal token owner
```

It is added to topology later:
```
TRACE 2023-05-17 00:47:32,164 [shard 0] storage_service - raft topology: loading topology: raft id=50c196df-c39a-4022-bf61-9599a655fcb9 ip=127.171.144.3 node state=normal dc=datacenter1 rack=rack1 tokens state={} tokens={-4753551240548989313, 5303819414355625433, -7419683683239018759, 4661457008624485895, -3741638931633762425, -6935254742270004502, -6264141849582388882, 4810515423101427623, -2546547479786984032, -4378069515908256537, 3059258707516462949, -4020066675415662880, 7108771765263080975, 7742746171664310519, 4930137567827198637, 6557921661783909394}
```

Probably a regression since raft-based topology management.

**Comment by tgrabiec** [comment]
This is with the following patch on top:
```patch
diff --git a/service/storage_service.cc b/service/storage_service.cc
index 60c92737be..d3b0927cfc 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -2423,6 +2423,8 @@ future<> storage_service::on_change(inet_address endpoint, application_state sta
             } else if (state == application_state::INTERNAL_IP) {
                 co_await maybe_reconnect_to_preferred_ip(endpoint, inet_address(value.value()));
             }
+        } else {
+            slogger.debug("endpoint={} not a normal token owner", endpoint);
         }
     }
 }

```

**Comment by kostja** [comment]
@tgrabiec why don't you think it's a driver bug?

**Comment by tgrabiec** [comment]
> @tgrabiec why don't you think it's a driver bug?

It's obviously due to scylla not maintaining system.peers properly.

How would the driver do a schema agreement wait differently? There is no other mechanism currently as far as I know.

**Comment by tgrabiec** [comment]
> > Probably a regression since raft-based topology management.
> 
> This is kind of regressions that I expect we will have a lot of (reliance on certain system tables/gossiper states behaviour by an external observers) . But do you run your test with raft topology enabled actually? The default in test.py is to disable it.

test_tablets.py depends on experimental raft so it's now in topology_experimental_raft suite.

**Comment by gleb-cloudius** [comment]
> > > Probably a regression since raft-based topology management.
> > 
> > 
> > This is kind of regressions that I expect we will have a lot of (reliance on certain system tables/gossiper states behaviour by an external observers) . But do you run your test with raft topology enabled actually? The default in test.py is to disable it.
> 
> test_tablets.py depends on experimental raft so it's now in topology_experimental_raft suite.

Not in the master( 9b0679c140bb82aeb3b52174e73ce8ee642eba8b) though as far as I can see.

**Comment by gleb-cloudius** [comment]
This is  item 20 in https://docs.google.com/document/d/135ftYBsA8XadEQ8f94qtFodJqvgQtP6ZhkOY6vMtJuk/edit

**Comment by tgrabiec** [comment]
> Not in the master( https://github.com/scylladb/scylladb/commit/9b0679c140bb82aeb3b52174e73ce8ee642eba8b) though as far as I can see.

Not yet, due to this issue ;)

> This is item 20 in https://docs.google.com/document/d/135ftYBsA8XadEQ8f94qtFodJqvgQtP6ZhkOY6vMtJuk/edit

I think we should fix this sooner. It's hard to develop on top of a system which is broken. We'll keep wasting time investing failures.

**Comment by tgrabiec** [comment]
One way would be to do the schema agreement wait on the scylla side as part of DDL execution.

**Comment by gleb-cloudius** [comment]
> > This is item 20 in https://docs.google.com/document/d/135ftYBsA8XadEQ8f94qtFodJqvgQtP6ZhkOY6vMtJuk/edit
> 
> I think we should fix this sooner. It's hard to develop on top of a system which is broken. We'll keep wasting time investing failures.

Of course. It should not be marked as `n` there.

**Comment by gleb-cloudius** [comment]
> One way would be to do the schema agreement wait on the scylla side as part of DDL execution.

Well, currently the code never update schema_version in peer's table at all. Who knows what depends on it. The question is how to propagate the schema version of each node to all other nodes. We can leave it in the gossiper and somehow make it work there or we can put it into a raft state and make each node write into it, but it would be an overkill.

**Comment by avikivity** [comment]
Looks like this merits a backport, @gleb-cloudius @tgrabiec please confirm

**Comment by gleb-cloudius** [comment]
> Looks like this merits a backport, @gleb-cloudius @tgrabiec please confirm

This fixes bug  in the experimental mode only.
