### ISSUE TITLE
Endpoint might be used after move in gossiper::is_alive

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13921]
The inet_address is moved here: https://github.com/scylladb/scylladb/blob/9b0679c140bb82aeb3b52174e73ce8ee642eba8b/gms/gossiper.cc#L2237

But might be used later if the endpoint state wasn't found, when a warning is logged here: https://github.com/scylladb/scylladb/blob/9b0679c140bb82aeb3b52174e73ce8ee642eba8b/gms/gossiper.cc#L2244

**Comment by bhalevy** [comment]
Introduced by 2210d10552996c04a9f414a5093e4e0f08fb3e02 on October, 2017

**Comment by denesb** [comment]
The bug is benign, not backporting.
