### ISSUE TITLE
Transferring snapshot to ... failed with: seastar::rpc::remote_verb_error (Can't find a column family tablets in keyspace system)

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13946]
The snapshot transfer code is unconditionally trying to send tablet mutations even though the TABLETS experimental feature is disabled
```cpp
        if (options->group0_snapshot_transfer) {
            // if `group0_snapshot_transfer` is `true`, the sender must also understand canonical mutations
            // (`group0_snapshot_transfer` was added more recently).
            if (!cm_retval_supported) {
                on_internal_error(mlogger,
                    "migration request handler: group0 snapshot transfer requested, but canonical mutations not supported");
            }
            cm.emplace_back(co_await db::system_keyspace::get_group0_history(db));
            for (auto&& m : co_await replica::read_tablet_mutations(db)) { //// <------- here
                cm.emplace_back(std::move(m));
            }
        }
```

```cpp
future<std::vector<canonical_mutation>> read_tablet_mutations(seastar::sharded<replica::database>& db) {
    auto s = db::system_keyspace::tablets();
    auto rs = co_await db::system_keyspace::query_mutations(db, db::system_keyspace::NAME, db::system_keyspace::TABLETS);
```

Thanks to @margdoc for finding the problem!
branch for reproducing: https://github.com/margdoc/scylla/commits/raft_topology_cdc_data_in_parts_errors
(run with `./test.py test_cdc_generation_data`; the test triggers an error injection inside topology coordinator which causes it to send many small commands, which triggers a snapshot transfer)

Now it's funny we didn't catch it in our tests, we have test/topology/test_snapshot.py, but... the test/topology suite enables the TABLETS feature...

**Comment by kbr-scylla** [comment]
cc @kostja

**Comment by tgrabiec** [comment]
After https://github.com/scylladb/scylladb/pull/13939, tablet tests are moved to experimental suite, so we can drop the "tablets" feature from the topology suite.

**Comment by denesb** [comment]
Raft change, not backporting.

**Comment by kbr-scylla** [comment]
The problem was introduced in 46eae545ad850da42b4775e23def7bf1250cd54f which didn't end up in 5.2 so no need to backport.
