### ISSUE TITLE
docs: notes about upgrading drivers and client applications before upgrading Scylla

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13958]
As observed in https://github.com/scylladb/scylla-enterprise/issues/2937

Our customer tried to upgrade their Scylla from 2021.1.14 to 2022.1.6. Their application started throwing errors from the Java driver, which didn't understand the `duration` type. Turns out they were using an ancient driver version.

We should instruct our users to upgrade their drivers before upgrading Scylla.

However, I don't know what the minimum driver version for each Scylla version is.
Perhaps we can deduce it by looking at our old docker images or relocatable packages?

cc @avelanarius @vladzcloudius

**Comment by kbr-scylla** [comment]
Another recent example reported by @AdamStawarz: customer was upgrading from 2021.1.12 to 2022.1.6, their app which was using the go driver started throwing
```
panic: unsupported strategy class: org.apache.cassandra.locator.EverywhereStrategy

goroutine 4857637938 [running]:
github.com/gocql/gocql.getStrategy(0xc01259de60)
        vendor/github.com/gocql/gocql/topology.go:89 +0x1e8
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc00007d0a0, 0xc00dd55d40, {0xc0111a6140, 0x1d})
        vendor/github.com/gocql/gocql/policies.go:460 +0xa5
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc00007d0a0, {{0xc0111a6140?, 0xdcf6c0?}, {0xc01a120990?, 0xc0003f6710?}})
        vendor/github.com/gocql/gocql/policies.go:448 +0xc5
github.com/gocql/gocql.(*Session).handleKeyspaceChange(0xc00442ae00, {0xc0111a6140, 0x1d}, {0xc01a120990, 0x7})
        vendor/github.com/gocql/gocql/events.go:127 +0x6c
github.com/gocql/gocql.(*Session).handleSchemaEvent(0xc00442ae00, {0xc00d72d880?, 0x3, 0x1a7fa50?})
        vendor/github.com/gocql/gocql/events.go:112 +0x16d
created by github.com/gocql/gocql.(*eventDebouncer).flush
        vendor/github.com/gocql/gocql/events.go:64 +0xc5
```

the driver didn't understand `EverywhereStrategy` and panicking.

Turns out that in later versions of this driver, the panic was turned into a warning. (The code is used for token-aware routing.)

**Comment by kbr-scylla** [comment]
> Another recent example reported by @AdamStawarz:

 https://github.com/scylladb/scylla-enterprise/issues/2951

**Comment by avelanarius** [comment]
Another thing we should improve is to run integration tests of older drivers against new Scylla versions. (Currently we do it the other way around: run integration test of newest drivers against old/new Scyllas)

**Comment by tzach** [comment]
@vladzcloudius @kbr-scylla can you please explicitly state what is the minimal releases of the Java driver and  Spark Connector  required (if you know it)?

**Comment by mykaul** [comment]
@roydahan - FYI. We'll need a matrix of 'base versions' and 'latest versions' tested, of both Scylla and Cassandra's.

**Comment by roydahan** [comment]
Regularly tested are the latest 2 driver versions per repo (scylla / Cassandra).

**Comment by roydahan** [comment]
> Another thing we should improve is to run integration tests of older drivers against new Scylla versions. (Currently we do it the other way around: run integration test of newest drivers against old/new Scyllas)

Not true, this is what you have in driver matrix tests.

**Comment by mykaul** [comment]
> > Another thing we should improve is to run integration tests of older drivers against new Scylla versions. (Currently we do it the other way around: run integration test of newest drivers against old/new Scyllas)
> 
> Not true, this is what you have in driver matrix tests.

Can you share the matrix?

**Comment by roydahan** [comment]
As said [here](https://github.com/scylladb/scylladb/issues/13958#issuecomment-1556169403), we test only 2 latest driver versions.

**Comment by tzach** [comment]
> As said https://github.com/scylladb/scylladb/issues/13958#issuecomment-1556169403, we test only 2 latest driver versions. 

What are the last two release tested per driver?

**Comment by roydahan** [comment]
Depends on which scylla release you're referring to...
For example:
Latest for 5.2.0, 5.2.1 and 5.2.2 runs:

Python driver:
Datastax - 3.27.0 & 3.26.0 
Scylla - 3.25.11 & 3.26.1

Java driver:
Datastax - 4.15.0 & 4.14.1
Scylla - 3.10.2 & 3.7.1

CPP driver:
Datastax - 2.16.2 & 2.15.3
Scylla - 2.16.2 & 2.15.2

Please note it can change every time it finds a newer release.

**Comment by tzach** [comment]
> Java driver:
> Datastax - 4.15.0 & 4.14.1
> Scylla - 3.10.2 & 3.7.1
> 

@avelanarius AFAIK, Scylla Java fork [4.13.0 is available](https://java-driver.docs.scylladb.com/scylla-4.13.0.x/index.html)

**Comment by tzach** [comment]
> @avelanarius AFAIK, Scylla Java fork 4.13.0 is available

@avelanarius ping

**Comment by tzach** [comment]
See https://github.com/scylladb/scylladb/issues/13958 for a related feature

**Comment by mykaul** [comment]
We can't declare more than we test.
