### ISSUE TITLE
Compute table schema version in group0

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#13957]
1. Problem statement

Currently, when creating or altering a table, each node computes the table schema version independently when applying schema mutations:

```
  do_merge_schema() -> merge_tables_and_views() -> create_table_from_mutations() -> schema_mutations::digest()
```

In the absence of bugs, each node should come up with the same version.

If this is not the case, and we have a situation when two nodes use different versions for the current table schema, the cluster can enter a degraded state when replica-side coordinator will keep requesting the definition of the unknown table schema version synchronously with the request:

```
  migration_manager::get_schema_for_write() -> get_schema_definition() -> send_get_schema_version()
```

...and issue full schema pull with the request coordinator to make sure the local replica has a more recent schema:  

``` 
  migration_manager::get_schema_for_write() -> maybe_sync() -> merge_schema_from()
```

This will add latency to such requests as they need to wait until the schema pull is complete. Schema pulls are known to be heavy in some cases, and can take seconds to complete.

There is a proposal to avoid this problem in the happy path when making a schema change: https://github.com/scylladb/scylladb/issues/2109. However, this will not be effective if each node computes a different table schema version.

1. Solution

To mitigate this problem, I propose to compute the version centrally when producing a group0 command, e.g. using the timestamp of the command (which is guaranteed to be globally unique) and have each node pick up the version. This removes the possibility for discrepancy.

**Comment by tgrabiec** [comment]
One potential source for digest mismatch: https://github.com/scylladb/scylladb/issues/4485

**Comment by tgrabiec** [comment]
We already have `version` field in scylla_tables.tables which can be reused for that, which was added long time ago to handle migration to a new schema tables format.

**Comment by mykaul** [comment]
How do we know which node came up 'wrong' (with the wrong version, due to bugs, etc.) ?

**Comment by kostja** [comment]
This is exactly what we need for schema version global monotonicity.

**Comment by kbr-scylla** [comment]
How should this interact with feature enablement? Today, enabling features changes schema version. Do we ignore this and just always use the version that we applied from group 0 state machine? It might make sense in the end, when we also move enabled features into group 0 - so feature enablement will be serialized with schema changes - but not sure if it makes sense in the mixed mode as well, where schema is kept in group 0 but features are still enabled through gossip.

**Comment by tgrabiec** [comment]
Do you have any specific problem in mind?

It is illegal to produce schema changes which depend on features which are not yet enabled in the whole cluster. In a mixed cluster, if the follower doesn't have the feature enabled, it must still already support it and supporting means that it can interpret the schema change which depends on the new feature. 

So schema version calculation can ignore features. It makes sense even with feature enablement through gossip.

**Comment by kbr-scylla** [comment]
> Do you have any specific problem in mind?

I don't, just thinking whether it's safe to ignore it.

> it must still already support it and supporting means that it can interpret the schema change which depends on the new feature

But it calculates schema version differently before it actually enables the feature, even though it already supports it. (Maybe this is wrong?) I remember seeing this when debugging test failures - I think during node restarts or bootstraps, schema version change log messages are interleaving with feature enablement messages.

You also debugged a problem where too slow enabling of features caused long-taking schema mismatches.

But I guess this is actually an undesirable trait of the current system and the proposal would also get rid of it which is actually what we want.

---

So does it have to be an actual calculation or can we just take the current `state_id` from group 0 state machine as the schema version?

**Comment by tgrabiec** [comment]
> But I guess this is actually an undesirable trait of the current system and the proposal would also get rid of it which is actually what we want.

Yes, after this issue is fixed, it won't change, and that's good. The version can be some global sequence number.

**Comment by DoronArazii** [comment]
@gusev-p are you actively working on it?

**Comment by kbr-scylla** [comment]
I just realized we're talking about two different things here:
- per-table schema version
- global schema digest

I guess we'd like to replace both with something that originates in group 0.

Now the question is, is that something the same thing -- for example, is it all right for the global schema "digest" (which will no longer be a digest, but some monotonically growing timeuuid, for example) to be the same as table schema version for some table existing within that schema? Is it all right for multiple tables to have the same table schema version?

Is the schema version even needed at all in group 0 mode?

**Comment by kbr-scylla** [comment]
>  Is it all right for multiple tables to have the same table schema version?

I guess this won't happen if we assume that each command in group 0 creates at most one table.

But if we ever consider commands that create two tables for example, we could potentially use a single version for both of them, which may be a mistake. So we need to be careful here.

**Comment by avikivity** [comment]
We need to assume that a single transaction can affect multiple tables. One example is version upgrade.

**Comment by kostja** [comment]
We can even switch to integer table ids (int64). Kamil, seems like you should write down your thoughts/suggestions before coding them, wdyt?

**Comment by kostja** [comment]
@avi honestly I doubt our ddl will be transactional long term. besides, table id doesn't need to change during table life cycle - table id != table version; we can use id + version as a full identifier. right now we merge multiple concepts into schema id.

**Comment by tgrabiec** [comment]
> Is it all right for multiple tables to have the same table schema version?

table_schema_version currently cannot be shared between different tables. It identifies both the table and a version within that table.

**Comment by avikivity** [comment]
> @avi honestly I doubt our ddl will be transactional long term. besides, table id doesn't need to change during table life cycle - table id != table version; we can use id + version as a full identifier. right now we merge multiple concepts into schema id.

I don't understand why our ddl will not be transactional in the long term.

**Comment by bhalevy** [comment]
Reopened by https://github.com/scylladb/scylladb/commit/35849fc901cb2d70f6aa18a590c0963ded17d1b7

**Comment by denesb** [comment]
Improvement, not bugfix, not backporting.
