### ISSUE TITLE
raft topology: make a decommissioning/removed node a non-voter early

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13959]
When we remove a node, we should make it a non-voter early in the procedure in some cases, improving availability.
- for `removenode`, there is no downside to making the removed node a non-voter first thing, because it's already dead. And it will improve availability in some situations - consider a 4-node cluster, one node is dead. If we make the dead node a non-voter at the beginning of `removenode`, group 0 will survive the death of another node in the middle of `removenode`.
- for `decommission` with even number of nodes, there is also no downside to making the decommissioning node a non-voter. All majorities containing this node will remain majorities when we make this node a non-voter and remove it from the set, because the required size of a majority decreases.
- for `decommission` with odd number of nodes there is a downside though, making it a non-voter may actually reduce availability. So in this case it should probably stay as a voter until it's removed completely.

Note for `decommission`: when a node restarts and notices that it's a non-voter, it will become a voter again. If a node was `decommission`ing and restarts, and we want `decommission` to continue (e.g. because it's at a finishing non-abortable step), we must ensure that the node doesn't become a voter. Node banning (#13850) should solve this.

cc @gleb-cloudius @tgrabiec

**Comment by gleb-cloudius** [comment]
> for removenode, there is no downside to making the removed node a non-voter first thing, because it's already dead. And it will improve availability in some situations - consider a 4-node cluster, one node is dead. If we make the dead node a non-voter at the beginning of removenode, group 0 will survive the death of another node in the middle of removenode.

`removenode` may fail and the already dead node can be resurrected. We need to make sure restore its voter state on the recovery path.

**Comment by kbr-scylla** [comment]
> We need to make sure restore its voter state on the recovery path.

Not necessary, we can leave that responsibility to the node itself -- it would become a voter again when it restarts, for example.

IMO it's better to keep it as non-voter especially when we even had the administrator thinking it's irrecoverable and attempting `removenode` -- until the node itself confirms that it's actually alive.

**Comment by avikivity** [comment]
The commit and the issue reference each other, but none of them say why this is a good idea apart from "improving availabilty". How does it improve availability?

Changelogs and especially issues are not supposed to repeat what the code says in simpler words, but to explain why.

What happens if decommission fails? Will voting rights be restored?

**Comment by kbr-scylla** [comment]
> How does it improve availability?

Example for `removenode` is given in the issue:

> consider a 4-node cluster, one node is dead. If we make the dead node a non-voter at the beginning of removenode, group 0 will survive the death of another node in the middle of removenode.

Example for decommission: 4 node cluster, we start decommissioning one of them but it dies before we finish and we didn't make it a non-voter. Now we're in a state where the death of another node would cause group 0 majority loss. But if we made it a non-voter at the beginning of decommission, we can survive the death of yet another node.

> What happens if decommission fails? Will voting rights be restored?

If the node that attempted to decommission restarts, it will become a voter again.

**Comment by denesb** [comment]
Raft change, no backport needed.
