### ISSUE TITLE
Large data handler does not take range tombstones into account

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#13968]
For detecting large partitions with too many rows we count only rows, but we don't count range tombstone markers.
Since the range tombstones need to be processed and accumulation of them may reduce performance we should count them too.  Since they are associated with clustering positions it makes sense to use the same counter as part as total number of rows for the purpose of threshold detection and reporting, but to add a separate counter (and respective column in the large_partitions system table) that would count only range tombstone markers (that correspond with range_tombstone_change mutation fragments in memory).

With that in mind, it'd also make sense to distinguish between live and dead rows, and to add another counter, similar in logic to the one described above for range tombstones, that would count the number of dead rows out of the total number of rows (what that crosses the threshold).  This way when a partition is detected with "too many rows", we'd know how many of which are dead and how many are range tombstone markers (the rest are alive).

**Comment by bhalevy** [comment]
Cc @vladzcloudius @raphaelsc 

Note: I'm not marking this as `Enhancement` since I thing it can be considered as an oversight of our present large partition detection logic, and I'd recommend backporting the fix to older releases.

**Comment by vladzcloudius** [comment]
> Cc @vladzcloudius @raphaelsc
> 
> Note: I'm not marking this as `Enhancement` since I think it can be considered as an oversight of our present large partition detection logic, and I'd recommend backporting the fix to older releases.

I totally agree with you.
I'd mark it as a "bug" even, @bhalevy 

If we don't count row/range tombstones for "large partition" detector purposes we are going to not detect partitions filled to tombstones. And knowing about those is very important.
It would also be great not just to know about them but also have a "live" vs "dead" vs "tombstones" counters that would allow us to reason about specific "large" partitions detected by the  "large_partition" detector.

**Comment by bhalevy** [comment]
Cc @paszkow

**Comment by mykaul** [comment]
@bhalevy - do we wish to backport this to 6.0?

**Comment by bhalevy** [comment]
> @bhalevy - do we wish to backport this to 6.0?

Yes, the baseline is close enough.
But are you sure the patch didn't make it there?

**Comment by nodep** [comment]
The patch is already in 6.0
