### ISSUE TITLE
Make raft based schema management the default in 5.4

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#13980]
Starting 5.2, Raft is the default for new clusters.
Starting 5.4, we need to make it default when upgrading existing clusters as well.
In order to do it, we need to flip the switch consistent-cluster-management's default from False to True in the command line options.

**Comment by kbr-scylla** [comment]
Changed title and milestone according to our discussion on weekly call

**Comment by avikivity** [comment]
Not a bug, not backporting.
