### ISSUE TITLE
doc: update the information about Raft in version 5.3

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#14014]
Review the section about Raft and make necessary updates: https://docs.scylladb.com/stable/architecture/raft.html
This should be done closer to the release when the final decisions about Raft in 5.3 are taken.

**Comment by annastuchlik** [comment]
@kbr-scylla @kostja I've assigned this issue to myself so that I remember about it, but I'll need your help to make sure the Raft docs in 5.3 are up to date.

The decision to enable Raft by default for new deployments and for upgrades may also affect the entire `Handling Failures` section. If Raft is the default, the section should be moved from the Raft page higher in the page tree as an independent page, as it will be relevant for all ScyllaDB users, not just those who enabled Raft.

**Comment by annastuchlik** [comment]
@kbr-scylla @kostja Can you now confirm that Raft is disabled by default for existing deployments in 5.3 (no change compared to 5.2)?
I've made the [final updates ](https://github.com/scylladb/scylladb/pull/14703)to the 5.2-to-5.3 upgrade guide, and I'd like to mark the task as done once the PR is merged.
This issue was opened to make sure no updates are required regarding Raft, as it was under discussion in May 2023.

**Comment by kbr-scylla** [comment]
> @kbr-scylla @kostja Can you now confirm that Raft is disabled by default for existing deployments in 5.3 (no change compared to 5.2)?

Yes.

Also note that b39ca9791911165c2ad2de09ca79adcd366f7061 enables `consistent_cluster_management` by default, it's currently on `master` branch, so -- assuming it won't get reverted (and I don't think it will) -- it will be part of 5.4. But we'll know that for sure once 5.4 gets branched.

**Comment by annastuchlik** [comment]
@kbr-scylla Thanks, that's all I wanted to know. This issue was just a reminder to make sure there's no confusion over 5.3 in that matter, so I can close it now.
