### ISSUE TITLE
docs: Issue in page Repair Based Node Operations

### ISSUE THREAD

**Issue by aniaptebsft** [scylladb/scylladb#14017]
I would like to report an issue in page https://docs.scylladb.com/branch-5.2/operating-scylla/procedures/cluster-management/repair-based-node-operation

### Problem
First letter in this line is upcase `E`
`Enable_repair_based_node_ops: true
`
###  Suggest a fix
First letter in the above line should be smallcase `e`

**Comment by denesb** [comment]
Minor documentation fix, not backporting.
