### ISSUE TITLE
test_tablets.py is flaky due to driver not seeing the host as up after server restart

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#14032]
Apparently, the driver may be still establishing connections in the
background after connecting to the cluster and queries may fail with:

  cassandra.cluster.NoHostAvailable

When executing "INSERT INTO test.test  ..." after manager.server_restart() in test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
