### ISSUE TITLE
Incremental compaction is not working in cleanup

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14035]
Since c7826aa9100, cleanup compacts entire runs, not only the individual fragments. Turns out cleanup is incorrectly holding reference to input runs, meaning incremental compaction cannot release space earlier.  So the promise of low temporary space requirement is not hold when running cleanup with ICS.

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to 2022.2 + 2023.1
@raphaelsc do we need it any further than that?

**Comment by denesb** [comment]
Backported to 5.3. Doesn't apply cleanly to 5.2. @raphaelsc please open backport PRs for 5.2 and 5.1.

**Comment by denesb** [comment]
5.2 and 5.1 backports are queued.
