### ISSUE TITLE
doc: update platform support for Unified Installer

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#14033]
https://docs.scylladb.com/stable/getting-started/install-scylla/unified-installer.html

Currently, the document says:
```
Supported distros
- CentOS 7 (Only support root offline install)
- CentOS 8
- Ubuntu 18.04 (developer-mode is used if NOFILE rlimit is too low)
- Debian 10
```

The list of platforms has been extended since this document was added. Is the support of Unified Installer limited to the older platform versions, or should we add Ubuntu 20.04, Ubuntu 22.04, and Debian 11?

It would be best to simply add the link to the [OS Support page](https://docs.scylladb.com/master/getting-started/os-support.html) - if Unified Installer supports all supported platforms.

@yaronkaikov @tzach Please advise.

**Comment by yaronkaikov** [comment]
@annastuchlik AFAICT today with offline installer we support all the above and also debian11, ubuntu 20.04 and 22.04, rocky8 and rocky9
@roydahan did i miss anything?

**Comment by annastuchlik** [comment]
OK, thanks!  So if @roydahan doesn't object, I'll update the section with a link to the list of supported platforms, as we shouldn't maintain the list of supported platforms in two places.

**Comment by roydahan** [comment]
AFAIK rocky9 isn't supported yet.
And I think we removed Ubuntu18.04 from support matrix.

**Comment by annastuchlik** [comment]
Ubunutu 18 is still there: https://docs.scylladb.com/stable/getting-started/os-support.html
I'll make the update for the latest versions of ScyllaDB and open a new issue to determine what is supported in version 5.3.

**Comment by tzach** [comment]
5.2.0 does not include Ubuntu 18 support
https://forum.scylladb.com/t/release-scylla-5-2-0-release-part-2/520

**Comment by yaronkaikov** [comment]
> OK, I'll remove it from version 5.2. @tzach @yaronkaikov How about 2023.1? Should I remove it, too?

AFAIK 2023.1 and 5.2 should be identical

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
