### ISSUE TITLE
backlog_controller should destroy _update_timer before _current_backlog

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14056]
The _update_timer callback calls adjust() that
depends on _current_backlog and currently, _current_backlog is
destroyed before _update_timer.

This is benign since there are no preemption points in
the destructor, but it's more correct and elegant
to destroy the timer first, before other members it depends on.

**Comment by bhalevy** [comment]
See:
https://github.com/scylladb/scylladb/blob/af65d5a1e8e61565da6ef60ae7a4a8dab675e0f6/backlog_controller.hh#L85-L87
vs.
https://github.com/scylladb/scylladb/blob/af65d5a1e8e61565da6ef60ae7a4a8dab675e0f6/replica/database.cc#L416-L422

**Comment by bhalevy** [comment]
Found by code inspection when analyzing a CI failure in #14043
but FWIW, I haven't see this issue manifested in practice.

**Comment by avikivity** [comment]
Not backporting as the bug is benign.
