### ISSUE TITLE
partitioned_sstable_set::erase might leave an empty run in _all_runs

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14052]
Since it was introduced in 02b2df1ea98c115fd20baeab3ae58dc20968bfa8
there are 2 problems in:
https://github.com/scylladb/scylladb/blob/af65d5a1e8e61565da6ef60ae7a4a8dab675e0f6/sstables/sstable_set.cc#L367

1. If `sst` was not inserted or is already removed, `_all_runs[sst->run_identifier()].erase(sst);` will allocate an entry for it in `_all_runs` (as noticed by @michoecho)
2. If `_all_runs[sst->run_identifier()]` becomes empty after erasing `sst`, we don't erase it from `_all_runs`.

**Comment by bhalevy** [comment]
The extent of this issue seems to affect only the performance of `partitioned_sstable_set::select_sstable_runs` (and `incremental_compaction_strategy::estimated_pending_compactions` that calls it), as it will need to scan a increasingly longer set of runs if we get to accumulate empty runs over time.

**Comment by bhalevy** [comment]
Ref https://github.com/scylladb/scylladb/pull/14043

**Comment by raphaelsc** [comment]
> The extent of this issue seems to affect only the performance of `partitioned_sstable_set::select_sstable_runs` (and `incremental_compaction_strategy::estimated_pending_compactions` that calls it), as it will need to scan a increasingly longer set of runs if we get to accumulate empty runs over time.

This issue is benign, as we rebuild the set when a sstable is removed.

**Comment by raphaelsc** [comment]
but the patch is worth it :-)

**Comment by avikivity** [comment]
Not backporting as the issue was analyzed be benign above.
