### ISSUE TITLE
partitioned_sstable_set::insert should handle sstables already in the set

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14060]
Currently, `partitioned_sstable_set::insert` may erase a sstable from the set inadvertently, if an exception is thrown while (re-)inserting it.  See
https://github.com/scylladb/scylladb/blob/af65d5a1e8e61565da6ef60ae7a4a8dab675e0f6/sstables/sstable_set.cc#L345-L346

Such an exception might be thrown from
https://github.com/scylladb/scylladb/blob/af65d5a1e8e61565da6ef60ae7a4a8dab675e0f6/sstables/sstable_set.cc#L357

This scenario is theoretical, and sstables are not known to be inserted more than once, but we should handle this vulnerability and return early from the function is the sstable is already in the sstable set.

**Comment by avikivity** [comment]
Don't fix a known bug, not backporting.
