### ISSUE TITLE
`test_upgrade_with_no_schema_commitlog`: booting server stuck, pulling schema in a loop

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14065]
Failure observed in next promotion. Test log:
[topology_raft_disabled.test_raft_upgrade_no_schema.3.log](https://github.com/scylladb/scylladb/files/11589583/topology_raft_disabled.test_raft_upgrade_no_schema.3.log)

Cluster:
```
20:14:15.689 INFO> Cluster after test test_upgrade_with_no_schema_commitlog: ScyllaCluster(name: 213fcbd0-fd7a-11ed-8772-0ea53e629375, running: ScyllaServer(656, 127.77.107.51, 529abf27-b2fa-4be8-814e-ee99d3dec690), ScyllaServer(658, 127.77.107.58, e5dc8e35-54f1-4f3f-bf0d-d2983b74a86a), ScyllaServer(660, 127.77.107.23, 78c8d75d-fb9e-473c-b194-69a36307efaf), ScyllaServer(664, 127.77.107.21, 40e01022-dcca-41dc-bb3d-27393c975238), stopped: )
```

attaching logs of all servers:
[scylla-656.log](https://github.com/scylladb/scylladb/files/11589589/scylla-656.log)
[scylla-658.log](https://github.com/scylladb/scylladb/files/11589592/scylla-658.log)
[scylla-660.log](https://github.com/scylladb/scylladb/files/11589594/scylla-660.log)
[scylla-664.log](https://github.com/scylladb/scylladb/files/11589597/scylla-664.log)

The test timed out when trying to boot server 664:
```
    async def test_upgrade_with_no_schema_commitlog(manager: ManagerClient, random_tables: RandomTables):
        # RAFT without schema_commit_log should produce error at node startup
        # We can't test this on the already running nodes, since schema commitlog feature
        # may have already been enabled on them
        new_server_info = await manager.server_add(start=False, config={
            'consistent_cluster_management': 'True',
            'force_schema_commit_log': 'False'
        })
        await manager.server_start(new_server_info.server_id,
                                   "Bad configuration: consistent_cluster_management "
                                   "requires schema commit log to be enabled")
    
        # Rollback RAFT and restart new node
        # Now it's the same as initially running nodes, except with force_schema_commit_log = False
        await manager.server_update_config(new_server_info.server_id, 'consistent_cluster_management', False)
        await manager.server_stop_gracefully(new_server_info.server_id)
>       await manager.server_start(new_server_info.server_id)
```

The server got stuck. It looks like it's pulling schema in a loop; there are 210 (!) occurrences of `Schema version changed to` in server 664's logs. We surely did not perform 210 schema changes so even if we have to reply the entire Raft log, there should be at most ~20 occurrences. For example in server 660's logs there are exactly 20 occurrences.

The pulls are not changing the schema version:
```
INFO  2023-05-28 20:13:15,276 [shard 0] schema_tables - Schema version changed to 36ccd013-04c8-369f-ab7b-403f03aa8567
INFO  2023-05-28 20:13:15,278 [shard 1] migration_manager - Schema merge with 127.77.107.58:0 completed
INFO  2023-05-28 20:13:15,292 [shard 1] migration_manager - Requesting schema pull from 127.77.107.58:0
INFO  2023-05-28 20:13:15,292 [shard 1] migration_manager - Pulling schema from 127.77.107.58:0
INFO  2023-05-28 20:13:16,494 [shard 0] schema_tables - Schema version changed to 36ccd013-04c8-369f-ab7b-403f03aa8567
INFO  2023-05-28 20:13:16,496 [shard 0] migration_manager - Schema merge with 127.77.107.58:0 completed
INFO  2023-05-28 20:13:16,524 [shard 0] migration_manager - Requesting schema pull from 127.77.107.58:0
INFO  2023-05-28 20:13:16,525 [shard 0] migration_manager - Pulling schema from 127.77.107.58:0
INFO  2023-05-28 20:13:17,726 [shard 0] schema_tables - Schema version changed to 36ccd013-04c8-369f-ab7b-403f03aa8567
INFO  2023-05-28 20:13:17,728 [shard 1] migration_manager - Schema merge with 127.77.107.58:0 completed
INFO  2023-05-28 20:13:17,742 [shard 1] migration_manager - Requesting schema pull from 127.77.107.58:0
INFO  2023-05-28 20:13:17,742 [shard 1] migration_manager - Pulling schema from 127.77.107.58:0
INFO  2023-05-28 20:13:18,954 [shard 0] schema_tables - Schema version changed to 36ccd013-04c8-369f-ab7b-403f03aa8567
INFO  2023-05-28 20:13:18,956 [shard 0] migration_manager - Schema merge with 127.77.107.58:0 completed
INFO  2023-05-28 20:13:18,983 [shard 0] migration_manager - Requesting schema pull from 127.77.107.58:0
INFO  2023-05-28 20:13:18,983 [shard 0] migration_manager - Pulling schema from 127.77.107.58:0
```

**Comment by kbr-scylla** [comment]
So here's the story on what happens with schema when a node bootstraps...

Normal production use case, with ring_delays and waiting for gossip to settle:
- booting node sleeps early in the boot procedure, waiting for gossip to settle
- during the wait, the node observes the states of other nodes and pulls their schemas
- the booting node doesn't create any keyspaces/tables on its own - any keyspace it would create (e.g. in system_distributed keyspace), it first checks that it already exists and skips

Our tests disable all the sleeps, and this is what usually happens. It's different, but it works:
- booting node does not sleep and does not pull schema of other nodes first; it  starts creating its own keyspaces and tables (e.g. in system_distributed keyspace), creating different schema mutations
- then the node observes others' states and pulls their schemas. These schemas fortunately correctly merge even though both definitions contain the same tables and so on.
- the booting node performs a CL=ALL write to other nodes (CDC generation write). The other nodes notice that they don't have the schema version of the table used by the write - that's because the booting node created its own version of the table.
- this triggers a schema pull on the other nodes from the booting nodes. Schemas converge.

But there's of course a fun race here, and with a bit of instrumentation we can make it reproduce 100% of the time. This is also what happened in the run from the issue...
- booting node creates the system_distributed_everywhere keyspace. But before it creates any table in this keyspace...
- in the meantime (concurrent gossiping), the booting node pulls schema from existing node. The schema contains a table inside system_distributed_everywhere keyspace. Fortunately the schemas merge and the table works! Note we're using a new keyspace mutation (from booting node) but old table mutation (from existing node) for a table in this keyspace.
- then the booting node tries to create/update other tables in system_distributed{_everywhere} keyspaces. It observes that all the tables are already present and up-to-date (because it pulled the schema).
- the booting node performs the CL=ALL write as before. But the write uses the table definition from existing nodes, even though it's in a keyspace created by this new node. The old nodes receive and apply the write,  they don't need to pull the schema because they know this table's schema already.
- therefore there is no reason for the old nodes to pull schema from the booting node. Their schema is constantly "behind" the booting node's schema (the booting node has the extra system_distributed_everywhere mutation that it created).
- booting node runs repair code, and on every range it calls `sync_schema`:
```
        rlogger.debug("repair[{}]: Repair {} out of {} ranges, keyspace={}, table={}, range={}, peers={}, live_peers={}",
            global_repair_id.uuid(), ranges_index, ranges_size(), _status.keyspace, table_names(), range, neighbors, live_neighbors);
        co_await mm.sync_schema(db.local(), neighbors);
```
this triggers a pull on every range. However, the booting node already has all the schema mutations from other nodes. It's the other nodes who don't have the schema of the booting node, but there's nothing that would trigger a pull in the other direction.
- the existing nodes won't automatically pull even when the booting node finishes booting - because they don't observe a gossiper `on_change` schema event, as the new node is not changing its schema. The new node stops pulling schema after repair finishes too. Schema is out of sync.
- Fortunately we can trigger pull in the other direction, bringing schema up to sync, by performing any schema change such as creating a keyspace.

The test failed simply because all the schema pulls (triggered on every range repair) took too long - this was debug mode - and the test timed out. But even in dev mode the pulls significantly slow down boot. Booting two-node cluster with my instrumentation takes ~16 seconds in dev mode compared to usual ~3 seconds.

Here's a reproducer:
https://github.com/kbr-scylla/scylladb/commit/f45fb53f1225f21e35e0972d48e13f01d910b3b4
run with
```
./test.py --mode dev test_schema_disagreement -s -v
```
It boots two nodes, instrumenting the second to create the system_distributed_everywhere keyspace in the "right" order compared to the schema pull.
We can see how many pulls the second node does when it's doing the repair...
```
$ grep "Schema version changed" testlog/dev/scylla-2.log  | wc -l
773
```

cc @tgrabiec - you might find this interesting

**Comment by kostja** [comment]
If we need to address it in the master only, it's sufficient to do https://github.com/scylladb/scylladb/issues/13957 and disable schema events during gossiping

**Comment by kostja** [comment]
What I don't get from your description Kamil, is how do we end up with a different schema digest here? From your description it sounds like all nodes have an identical schema.

**Comment by nyh** [comment]
> Our tests disable all the sleeps, and this is what usually happens. It's different, but it works:
> 
>     * booting node does not sleep and does not pull schema of other nodes first; it  starts creating its own keyspaces and tables (e.g. in system_distributed keyspace), creating different schema mutations

This is exactly what I noticed today in https://github.com/scylladb/scylladb/issues/14073 - various dtests requiring bootstrap of a new node in an existing cluster failed because the booting node didn't even wait to know about ONE other node, so it got the wrong schema (a brand new schema instead of the cluster's existing schema) and then didn't copy all the tables that exist.

I "hacked" a fix for it, but it appears that as the code is currently written, setting `ring_delay_ms=0` as we do in tests (and I wanted to do in dtest) simply doesn't work in the current code. The parameter `ring_delay_ms` is not just used for "just in case" sleeps, it is also used as a **maximum** delays to wait until something necessary happens (i.e., we one another node).

**Comment by nyh** [comment]
For reasons I explained in #14073 I think that we either need to change the `ring_delay_ms` logic in the code, or we can't safely set it to 0 in tests - maybe 1 second is enough and I tested it doesn't effect regular cluster boots - it seems this 1 second is a maximum usually, not the whole thing is slept. However, it does effect "node replace", where we have "sleeping before replacing" which is 2 times ring_delay_ms (if we don't change it, this is 20 seconds of completely unjustified sleep).

**Comment by kbr-scylla** [comment]
I tried the following patch:
```diff
diff --git a/service/storage_service.cc b/service/storage_service.cc
index 0a8f249b76..7ffb003406 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -1536,6 +1536,39 @@ future<> storage_service::update_topology_with_local_metadata(raft::server& raft
     co_await _sys_ks.local().set_must_synchronize_topology(false);
 }
 
+// Wait until gossiper observes the given nodes or timeout is reached.
+// Called on initial startup (bootstrap/replace), not during restarts.
+static future<> wait_until_seen_during_boot(
+        const gms::gossiper& g, const std::unordered_set<gms::inet_address>& initial_contact_nodes,
+        db::timeout_clock::time_point timeout, abort_source& as) {
+    logger::rate_limit rate_limit{std::chrono::seconds{5}};
+    while (!as.abort_requested()) {
+        std::vector<gms::inet_address> observed = g.get_endpoints();
+        std::unordered_set<gms::inet_address> observed_set{observed.begin(), observed.end()};
+
+        std::vector<gms::inet_address> diff;
+        diff.reserve(initial_contact_nodes.size());
+        for (auto& n: initial_contact_nodes) {
+            if (!observed_set.contains(n)) {
+                diff.push_back(n);
+            }
+        }
+        if (diff.empty()) {
+            slogger.info("All initial contact nodes ({}) seen in gossip", initial_contact_nodes);
+            co_return;
+        }
+
+        if (db::timeout_clock::now() >= timeout) {
+            auto err = ::format("Timed out waiting for nodes {} to show up in gossip during boot", diff);
+            slogger.error("{}", err);
+            throw std::runtime_error{std::move(err)};
+        }
+
+        slogger.log(log_level::info, rate_limit, "Nodes {} not yet seen in gossip during initial boot", diff);
+        co_await sleep_abortable(std::chrono::milliseconds{100}, as);
+    }
+}
+
 future<> storage_service::join_token_ring(cdc::generation_service& cdc_gen_service,
         sharded<db::system_distributed_keyspace>& sys_dist_ks,
         sharded<service::storage_proxy>& proxy,
@@ -1735,6 +1768,12 @@ future<> storage_service::join_token_ring(cdc::generation_service& cdc_gen_servi
     });
     _listeners.emplace_back(make_lw_shared(std::move(schema_change_announce)));
     co_await _gossiper.wait_for_gossip_to_settle();
+    if (!_sys_ks.local().bootstrap_complete()) {
+        co_await wait_until_seen_during_boot(
+            _gossiper, initial_contact_nodes, db::timeout_clock::now() + std::chrono::minutes{5}, _abort_source);
+        co_await _migration_manager.local().wait_for_schema_agreement(
+            _db.local(), db::timeout_clock::now() + std::chrono::minutes{5}, &_abort_source);
+    }
```

Unfortunately, `wait_for_schema_agreement` does not finish even though the booting node pulls schema. For some reason the versions are different. Perhaps because of the initial schema mutations present on the booting node? I'd have to investigate further.

**Comment by kbr-scylla** [comment]
I don't understand why the schema versions are different when I introduce `wait_for_schema_agreement`.
When the second node boots its initial schema version is `59adb24e-f3cd-3e02-97f0-5b395827453f`. It's the same on all nodes when they boot.
Then the second node, before it creates any of its own tables, pulls the schema while `wait_for_schema_agreement` is sleeping.
And for some reason the resulting version is different than the one on the first node.
```
DEBUG 2023-05-31 13:07:41,160 [shard 0] migration_manager - Submitting migration task for 127.208.239.1
INFO  2023-05-31 13:07:41,160 [shard 0] migration_manager - Requesting schema pull from 127.208.239.1:0
INFO  2023-05-31 13:07:41,160 [shard 0] migration_manager - Pulling schema from 127.208.239.1:0
DEBUG 2023-05-31 13:07:41,168 [shard 0] migration_manager - Applying schema mutations from 127.208.239.1:0
DEBUG 2023-05-31 13:07:41,177 [shard 0] migration_manager - Submitting migration task for 127.208.239.1
INFO  2023-05-31 13:07:41,177 [shard 0] migration_manager - Requesting schema pull from 127.208.239.1:0
INFO  2023-05-31 13:07:41,178 [shard 0] schema_tables - Creating keyspace system_auth
INFO  2023-05-31 13:07:41,178 [shard 0] schema_tables - Creating keyspace system_distributed
INFO  2023-05-31 13:07:41,178 [shard 0] schema_tables - Creating keyspace system_distributed_everywhere
INFO  2023-05-31 13:07:41,178 [shard 0] schema_tables - Creating keyspace system_traces
INFO  2023-05-31 13:07:41,182 [shard 0] schema_tables - Creating system_distributed.cdc_streams_descriptions_v2 id=0bf73fd7-65b2-36b0-85e5-658131d5df36 version=fd23b57b-0960-30c1-b233-79461a388172
INFO  2023-05-31 13:07:41,182 [shard 0] schema_tables - Creating system_traces.sessions_time_idx id=0ebf001c-c1d1-3693-9a63-c3d96ac53318 version=23147722-8cb0-304b-988d-2fc99ff5e019
INFO  2023-05-31 13:07:41,183 [shard 0] schema_tables - Creating system_auth.role_members id=0ecdaa87-f8fb-3e60-88d1-74fb36fe5c0d version=12fbbbbf-3433-3cb8-a45f-e959b67a6972
INFO  2023-05-31 13:07:41,183 [shard 0] schema_tables - Creating system_distributed_everywhere.cdc_generation_descriptions_v2 id=234d2227-dd63-3d37-ac5f-c013e2ea9e6e version=ec3dc0ec-659d-3c7e-a386-68859c8027ff
INFO  2023-05-31 13:07:41,184 [shard 0] schema_tables - Creating system_distributed.view_build_status id=5582b59f-8e4e-35e1-b913-3acada51eb04 version=0782be75-61fd-3369-a279-d18ff921b7d1
INFO  2023-05-31 13:07:41,184 [shard 0] schema_tables - Creating system_auth.roles id=5bc52802-de25-35ed-aeab-188eecebb090 version=5dc14a24-bed2-33c7-a25d-a0809299fffc
INFO  2023-05-31 13:07:41,185 [shard 0] schema_tables - Creating system_auth.role_attributes id=6b8c7359-a843-33f2-a1d8-5dc6a187436f version=20ff2707-0d25-3590-9222-ce8b952cd984
INFO  2023-05-31 13:07:41,186 [shard 0] schema_tables - Creating system_traces.events id=8826e8e9-e16a-3728-8753-3bc1fc713c25 version=b6df6394-5250-32b6-8d04-7f67544b0afb
INFO  2023-05-31 13:07:41,186 [shard 0] schema_tables - Creating system_distributed.service_levels id=b8c556bd-212d-37ad-9484-690c73a5994b version=c02fd5f0-eaa3-3934-a217-9d375e1c9ce0
INFO  2023-05-31 13:07:41,187 [shard 0] schema_tables - Creating system_traces.node_slow_log id=bfcc4e62-5b63-3aa1-a1c3-6f5e47f3325c version=f68fe67c-ef99-3748-81c5-9e7364760f07
INFO  2023-05-31 13:07:41,188 [shard 0] schema_tables - Creating system_traces.sessions id=c5e99f16-8677-3914-b17e-960613512345 version=61178e59-402c-33d6-ac8a-3b280b93044b
INFO  2023-05-31 13:07:41,189 [shard 0] schema_tables - Creating system_traces.node_slow_log_time_idx id=f9706768-aa1e-3d87-9e5c-51a3927c2870 version=217517bc-fc0f-3faf-a98f-823d22dbee46
INFO  2023-05-31 13:07:41,189 [shard 0] schema_tables - Creating system_distributed.cdc_generation_timestamps id=fdf455c4-cfec-3e00-9719-d7a45436c89d version=f181a6ed-63d9-3abd-9235-2351888858ee
DEBUG 2023-05-31 13:07:41,204 [shard 0] migration_manager - Gossiping my schema version 742e566b-4756-3a64-81d5-4ce929c52056
INFO  2023-05-31 13:07:41,205 [shard 0] schema_tables - Schema version changed to 742e566b-4756-3a64-81d5-4ce929c52056
INFO  2023-05-31 13:07:41,205 [shard 0] migration_manager - Schema merge with 127.208.239.1:0 completed
```

in this run the resulting version was `742e566b-4756-3a64-81d5-4ce929c52056`, but it's `d31a1d4f-c097-32eb-a4e7-a2e421904eed` on the first node.

**Comment by kbr-scylla** [comment]
Ah, it's because the booting node didn't enable features yet.

**Comment by avikivity** [comment]
Seems like test-only. @kbr-scylla please confirm.

**Comment by kbr-scylla** [comment]
Yes
