### ISSUE TITLE
Replace operation during boot doesn't wait for schema pull

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14073]
In an attempt to speed up Scylla boot in dtest (https://github.com/scylladb/scylla-dtest/issues/2429), I tried adding to the options that dtest uses to start Scylla the options `skip_wait_for_gossip_to_settle: 0` and `ring_delay_ms: 0` - see https://github.com/scylladb/scylla-dtest/commit/c70114f1cc13dcdc5b5e4f422f81e61ccd1d5d55

The dtest `counter_tests.py::TestCountersOnMultipleNodes::test_counter_consistency_node_replace`

Fails with this change. I checked and it's not an issue of the **test** not waiting enough - I added very long sleeps between every step of this test and it still fails.

The test puts data in a three-node cluster, and then stops the third node, and runs a fourth node to **replace** the dead node.  No matter how long the application waits, the data never arrives to node 4.

The log suggests that the replace repair-based-operation  fails to copy all the data:
```
INFO  2023-05-29 17:31:26,551 [shard 0] repair - replace_with_repair: started with keyspaces={system_distributed_everywhere, system_distributed}, source_dc=datacenter1, nr_ranges_total=1285, ignore_nodes={}
```

Note only the two keyspaces being copied. In another node I see an empty boostrap seeing also system_traces, system_auth, and these are missing here. And of course, I expected to see the test table being copied as well (the fact it wasn't caused the failure).

A second and a half later, we finally see this in the log:
```
INFO  2023-05-29 17:31:28,020 [shard 0] migration_manager - Requesting schema pull from 127.0.34.1:0
```

So it seems to me that only a second and a half after we start the repair-based replace operation, do we fetch a schema which tells us what we need to repair...

@asias could we perhaps be missing a synchronization point - that the replace (and I guess also normal bootstrap?) shouldn't start before we have the schema? 

@fruch noticed that running with Raft ("--consistent-cluster-management" in dtest) makes this problem go away. I guess Raft retrieves the schema in a different - and earlier - way.

UPDATE: (see details below): We actually do wait for schema pull, but only up to the configured `ring_delay_ms`. If `ring_delay_ms=0` (as I tried to do), we believe the schema is up to date because we didn't even wait enough to find any other node and see that it has a different schema.

CC @asias @fruch

**Comment by mykaul** [comment]
I believe @kostja and team were looking at related issues.

**Comment by asias** [comment]
In storage_service::join_token_ring, there is a call to 

co_await wait_for_ring_to_settle(delay);

where we wait for the schema match.

Since the ring delay is zero, perhaps migration_manager::have_schema_agreement gives wrong answer. 

You can add some log in the code to check.

**Comment by nyh** [comment]
@asias the code that you mentioned has:
```c++
        while (!_migration_manager.local().have_schema_agreement()) {
            slogger.info("waiting for schema information to complete");
            co_await sleep_abortable(std::chrono::seconds(1), _abort_source);
        }
```
So the fact I don't see this message "waiting for schema information to complete" in the new node means it does think have_schema_agreement(). But I don't really understand what "schema agreement" means in this case - this node has never pulled a schema from any other node - as I noted above this will only happen about 1.5 seconds later. I'll try to figure out now who starts this "schema pull" code, and why do we think there is a "schema agreement" before that.

**Comment by nyh** [comment]
Thanks @asias I think you indeed pointed me to the right direction.
I think the problem is in `migration_manager::have_schema_agreement()` which has this in the beginning:
```
    const auto known_endpoints = _gossiper.get_endpoint_states();
    if (known_endpoints.size() == 1) {
        // Us.
        return true;
    }
```
I think the point of this code was not to wait when we're the **only** node, but it seems it also returns true in the new 4th node in my cluster. Perhaps we're calling it so early that we haven't yet set the gossiper's enpoint states. But, we *do* have seeds, we should have known we're not alone and not return true...

Commenting out the "return true" in this code fixes the broken dtest!

But now I need to find a better fix for the same thing.

**Comment by nyh** [comment]
To be more explicit on the double-use of ring_delay_ms as both a timeout and an unconditional sleep:
1. In `wait_ring_to_settle()`, the configuration `ring_delay_ms` is used as the maximum sleep until something critical happens (we find another node).
2. In `join_token_ring()` we have an unconditional sleep of `2*ring_delay_ms` (20 seconds by default!) when replacing a node, just in case.

**Comment by nyh** [comment]
@kbr-scylla you're right that Raft cluster management takes a different code path, but I'm not testing it, I'm testing the default dtest configuration which doesn't use Raft cluster management.

It seems like as long as `wait_ring_to_settle()` uses `ring_delay_ms` as a maximum delay and not, say, some other configuration option, I simply can't set `ring_delay_ms` to as 0 as I wanted.

**Comment by kbr-scylla** [comment]
Most dtests run in both modes in CI.
There are dtests which are "raft only" and "gossip only".
You could try removing the sleeps from raft only dtests and conditionally from those dtests that run in both modes when they are executed in raft mode.

**Comment by kbr-scylla** [comment]
> I think the point of this code was not to wait when we're the only node, but it seems it also returns true in the new 4th node in my cluster. Perhaps we're calling it so early that we haven't yet set the gossiper's enpoint states.

@nyh yep
That's why I introduced this:
```cpp
// Wait until gossiper observes the given nodes or timeout is reached.
// Called on initial startup (bootstrap/replace), not during restarts.
static future<> wait_until_seen_during_boot(
        const gms::gossiper& g, const std::unordered_set<gms::inet_address>& initial_contact_nodes,
        db::timeout_clock::time_point timeout, abort_source& as) {
    logger::rate_limit rate_limit{std::chrono::seconds{5}};
    while (!as.abort_requested()) {
        std::vector<gms::inet_address> observed = g.get_endpoints();
        std::unordered_set<gms::inet_address> observed_set{observed.begin(), observed.end()};

        std::vector<gms::inet_address> diff;
        diff.reserve(initial_contact_nodes.size());
        for (auto& n: initial_contact_nodes) {
            if (!observed_set.contains(n)) {
                diff.push_back(n);
            }
        }
        if (diff.empty()) {
            slogger.info("All initial contact nodes ({}) seen in gossip", initial_contact_nodes);
            co_return;
        }

        if (db::timeout_clock::now() >= timeout) {
            auto err = ::format("Timed out waiting for nodes {} to show up in gossip during boot", diff);
            slogger.error("{}", err);
            throw std::runtime_error{std::move(err)};
        }

        slogger.log(log_level::info, rate_limit, "Nodes {} not yet seen in gossip during initial boot", diff);
        co_await sleep_abortable(std::chrono::milliseconds{100}, as);
    }
}
```
in my patch for #14065
it might solve your problem as well.

**Comment by denesb** [comment]
This looks important but potentially risk. @kbr-scylla @nyh please evaluate for backport.

**Comment by kbr-scylla** [comment]
Only affects ring_delay=0 test environments.
