### ISSUE TITLE
C-S fails to write after node replace procedure using the same IP address

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#14078]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

## Impact

Load stops working.

## How frequently does it reproduce?

First time observed.

## Installation details

Kernel Version: 5.15.0-1038-azure
Scylla version (or git commit hash): `5.2.2-20230521.9dd70a58c3f9` with build-id `d692f21f4fc0ee40fac88d4bdef5d4f0999127ba`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-9 (20.172.206.214 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-8 (20.228.249.255 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-7 (20.169.238.54 | 10.0.0.14) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-6 (172.173.174.70 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-5 (172.173.174.64 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-4 (172.173.174.60 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-3 (172.173.174.52 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-2 (20.168.221.25 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-11 (172.174.13.186 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-10 (20.124.7.206 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-5-2-db-node-e0063d34-eastus-1 (20.168.218.161 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.2.2-x86_64-2023-05-21T13-50-58` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `e0063d34-df6e-47ce-9ceb-e978abe944f6`
Test name: `scylla-5.2/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5aba36f0357571086239a7753f24ae714f8b4ee6/test-cases/longevity/longevity-10gb-3h.yaml)

## Details:
Sequence of nemesises applied before the problem appearence:
- mgmt_backup - went OK, no node changes
- add_remove_dc - went OK, new `node-7 (10.0.0.14)` was added and removed
- decommission_streaming_err - went OK, existing node `node-2 (10.0.0.6)` was decommissioned and new `node-8` added with the same IP. 
- terminate_and_replace_node - caused failure.

So, the `terminate_and_replace_node` step in more details:

At first we terminate the `node-8` node which was recently added using the `10.0.0.6` IP address:
```
2023-05-21 14:49:48,950 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-21 14:49:48.928: (InfoEvent Severity.NORMAL) period_type=not-set event_id=47cc70d7-24a2-4108-be83-44394c81b3f9: message=StartEvent - Terminate node and wait 5 minutes
2023-05-21 14:49:50,976 f:virtual_machine_provider.py l:126  c:sdcm.provision.azure.virtual_machine_provider p:INFO  > Triggering termination of instance: longevity-10gb-3h-5-2-db-node-eastus-8
2023-05-21 14:49:51,810 f:virtual_machine_provider.py l:140  c:sdcm.provision.azure.virtual_machine_provider p:INFO  > Waiting for termination of instance: longevity-10gb-3h-5-2-db-node-eastus-8...
2023-05-21 14:50:47,095 f:virtual_machine_provider.py l:142  c:sdcm.provision.azure.virtual_machine_provider p:INFO  > Instance longevity-10gb-3h-5-2-db-node-eastus-8 has been terminated.
```

The load significantly drops for about a minute:
![Screenshot from 2023-05-29 21-31-50](https://github.com/scylladb/scylladb/assets/3796058/e5b6c011-3ce0-4f36-b693-12080b6e4490)

Then, the new node `node-9` gets created with the same IP address - `10.0.0.6`:
```
2023-05-21 14:58:45,511 f:virtual_machine_provider.py l:61   c:sdcm.provision.azure.virtual_machine_provider p:INFO  > Creating 'longevity-10gb-3h-5-2-db-node-eastus-9' VM in resource group SCT-e0063d34-df6e-47ce-9ceb-e978abe944f6-eastus...
...
2023-05-21 15:04:34,251 f:virtual_machine_provider.py l:112  c:sdcm.provision.azure.virtual_machine_provider p:INFO  > Provisioned VM longevity-10gb-3h-5-2-db-node-eastus-9 in the SCT-e0063d34-df6e-47ce-9ceb-e978abe944f6-eastus resource group
2023-05-21 15:04:34,252 f:cloud_init.py   l:31   c:sdcm.provision.helpers.cloud_init p:INFO  > Waiting for cloud-init to complete on node longevity-10gb-3h-5-2-db-node-eastus-9...
```

And right after it we get following errors:
```
2023-05-21 15:04:55,787 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-05-21 15:04:55.785: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=b7f092ef-d618-4d98-abd2-a61368653b46 during_nemesis=TerminateAndReplaceNode: type=TooManyHintsInFlight regex=Too many hints in flight|Too many in flight hints line_number=3159 node=Node longevity-10gb-3h-5-2-loader-node-e0063d34-eastus-2 [172.173.174.89 | 10.0.0.12] (seed: False)
2023-05-21 15:04:55,787 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > java.io.IOException: Operation x10 on key(s) [31374d37374c4b4d3631]: Error executing: (OverloadedException): Queried host (longevity-10gb-3h-5-2-db-node-eastus-5.internal.cloudapp.net/10.0.0.9:9042) was overloaded: Too many in flight hints: 10485768
2023-05-21 15:04:56,039 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-05-21 15:04:56.026: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=816a3ee3-5dc4-45c1-80ff-027cf136d2e8 during_nemesis=TerminateAndReplaceNode: type=TooManyHintsInFlight regex=Too many hints in flight|Too many in flight hints line_number=3097 node=Node longevity-10gb-3h-5-2-loader-node-e0063d34-eastus-1 [172.173.174.81 | 10.0.0.11] (seed: False)
2023-05-21 15:04:56,039 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > java.io.IOException: Operation x10 on key(s) [3634344b4b34394d3830]: Error executing: (OverloadedException): Queried host (longevity-10gb-3h-5-2-db-node-eastus-5.internal.cloudapp.net/10.0.0.9:9042) was overloaded: Too many in flight hints: 10485768
```

There were lots of these `overloaded` messages for the `node-5 (10.0.0.9)` node.

The new `node-9` first logs:
```
May 21 15:04:39 longevity-10gb-3h-5-2-db-node-eastus-9 systemd[1]: Starting Scylla Cloud Image Setup service...
May 21 15:05:55 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[957]: 16384+0 records in
May 21 15:05:55 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[957]: 16384+0 records out
May 21 15:05:55 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[957]: 17179869184 bytes (17 GB, 16 GiB) copied, 72.362 s, 237 MB/s
May 21 15:08:18 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[1028]: Setting up swapspace version 1, size = 16 GiB (17179865088 bytes)
May 21 15:08:18 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[1028]: no label, UUID=ad04bca3-ef83-40fa-a4b4-233caba6d345
May 21 15:08:18 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[1067]: Created symlink /etc/systemd/system/multi-user.target.wants/mnt-swapfile.swap → /etc/systemd/system/mnt-swapfile.swap.
May 21 15:09:09 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[1099]: 2023-05-21 15:09:09,208 - [scylla_configure] - INFO - Going to create scylla.yaml...
May 21 15:09:09 longevity-10gb-3h-5-2-db-node-eastus-9 scylla_image_setup[1099]: Going to create scylla.yaml...
```

Here we see that it was getting data for `~72-76` seconds which cover the time frame of the `overloaded` messages given by loaders.

With the appearance of the `overloaded` message the load just stopped:
![Screenshot from 2023-05-29 21-41-46](https://github.com/scylladb/scylladb/assets/3796058/5407579a-75f9-4d05-adb0-cd802e451806)

The DB cluster state in ~10 minutes at `2023-05-21 15:14:19,233`:
```
> Datacenter: eastus
> ==================
> Status=Up/Down
> |/ State=Normal/Leaving/Joining/Moving
> --  Address    Load       Tokens       Owns    Host ID                               Rack
> UN  10.0.0.5   1.52 GB    256          ?       b322d284-74a7-4bdc-b531-5a7835e50130  eastus
> UN  10.0.0.6   1.33 GB    256          ?       be7ddf8e-3fe4-42bf-bbd7-0610320798e5  eastus
> UN  10.0.0.7   1.8 GB     256          ?       c60ade10-8960-476a-a962-8baf6f2c8e5a  eastus
> UN  10.0.0.8   2.03 GB    256          ?       f635c4b7-2028-4962-849a-64d543b2aa07  eastus
> UN  10.0.0.9   2.29 GB    256          ?       c8536cd8-acf1-49f4-9a6f-17c2a9ec1178  eastus
> UN  10.0.0.10  2.06 GB    256          ?       02441953-33b8-4515-a904-cb944489dd21  eastus
```

So, here our nemesis continue to run against the DB cluster without any load.

The `remove_node_then_add_node` nemesis removes `node-4 (10.0.0.8)` node and adds new `node-10 (10.0.0.8)`.
And when we reach the `nodetool_decommission` nemesis where we decommission the `node-5` which was `overloaded`, according to the info from the loaders, we got crash of loaders:

```
2023-05-21 16:29:28,573 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-21 16:29:28.571: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=b7f092ef-d618-4d98-abd2-a61368653b46 during_nemesis=SoftRebootNode duration=3h0m55s: node=Node longevity-10gb-3h-5-2-loader-node-e0063d34-eastus-2 [172.173.174.89 | 10.0.0.12] (seed: False)
2023-05-21 16:29:28,573 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5
2023-05-21 16:29:28,573 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > errors:
2023-05-21 16:29:28,573 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
2023-05-21 16:29:28,573 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: Failed to connect over JMX; not collecting these stats
2023-05-21 16:29:28,573 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > com.datastax.driver.core.exceptions.Transport
```
```
2023-05-21 16:38:04,611 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-21 16:38:04.597: (CassandraStressEvent Severity.CRITICAL) period_type=end event_id=816a3ee3-5dc4-45c1-80ff-027cf136d2e8 duration=3h10m0s: node=Node longevity-10gb-3h-5-2-loader-node-e0063d34-eastus-1 [172.173.174.81 | 10.0.0.11] (seed: False)
2023-05-21 16:38:04,611 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > stress_cmd=cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5
2023-05-21 16:38:04,611 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > errors:
2023-05-21 16:38:04,611 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
2023-05-21 16:38:04,611 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stress command completed with bad status 1: Failed to connect over JMX; not collecting these stats
2023-05-21 16:38:04,611 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > com.datastax.driver.core.exceptions.Transport
```

## Monitoring:
- Restore Monitor Stack command: `$ hydra investigate show-monitor e0063d34-df6e-47ce-9ceb-e978abe944f6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e0063d34-df6e-47ce-9ceb-e978abe944f6)
- Show all stored logs command: `$ hydra investigate show-logs e0063d34-df6e-47ce-9ceb-e978abe944f6`

## Logs:
- **db-cluster-e0063d34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/db-cluster-e0063d34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/db-cluster-e0063d34.tar.gz)
- **sct-runner-events-e0063d34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/sct-runner-events-e0063d34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/sct-runner-events-e0063d34.tar.gz)
- **sct-e0063d34.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/sct-e0063d34.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/sct-e0063d34.log.tar.gz)
- **monitor-set-e0063d34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/monitor-set-e0063d34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/monitor-set-e0063d34.tar.gz)
- **loader-set-e0063d34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/loader-set-e0063d34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/loader-set-e0063d34.tar.gz)
- **parallel-timelines-report-e0063d34.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/parallel-timelines-report-e0063d34.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e0063d34-df6e-47ce-9ceb-e978abe944f6/20230521_164242/parallel-timelines-report-e0063d34.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-10gb-3h-azure-test/16/)
[Argus](https://argus.scylladb.com/test/8c977b7f-0cad-49ba-a41d-604ac9130d59/runs?additionalRuns[]=e0063d34-df6e-47ce-9ceb-e978abe944f6)

**Comment by vponomaryov** [comment]
Looks related to the following fixed issue: https://github.com/scylladb/scylla-enterprise/issues/2852

**Comment by DoronArazii** [comment]
@asias is it your area of expertise? can you please provide an assessment?

**Comment by DoronArazii** [comment]
@kostja ping

**Comment by kostja** [comment]
Sorry I missed the pings.

**Comment by gleb-cloudius** [comment]
There is too much information here. What is exactly the problem you want to be investigated in the issue? Overloaded exception? Well, you killed one node, so the system stores hints to it. They are not flushedto disk fast enough so you get overloaded exception. If there is something to investigate here is the performance of `node-5` disk.

If you are asking why cassandra-stress exists well, this is QA tool. Debug it. In my experience it tends to crash when facing too much errors.

**Comment by kostja** [comment]
@gleb-cloudius could https://github.com/scylladb/scylladb/issues/13865 be related?

**Comment by mykaul** [comment]
@gleb-cloudius - I think the ask is why did the load fail.

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius - I think the ask is why did the load fail.

I do not see how. There is no replacenode failure here.

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius - I think the ask is why did the load fail.

The error we got cannot be more clear. The node is overloaded by hints.

**Comment by mykaul** [comment]
> > @gleb-cloudius - I think the ask is why did the load fail.
> 
> The error we got cannot be more clear. The node is overloaded by hints.

If hints are supposed to help us, and they don't (overloading), shouldn't we delete them when we get such error? (or is it too late?)

**Comment by gleb-cloudius** [comment]
> > > @gleb-cloudius - I think the ask is why did the load fail.
> > 
> > 
> > The error we got cannot be more clear. The node is overloaded by hints.
> 
> If hints are supposed to help us, and they don't (overloading), shouldn't we delete them when we get such error? (or is it too late?)

We can do many things. The hints behave the way they behave in cassandra  and we can do something completely different. But you will fight symptoms not the problem.

**Comment by mykaul** [comment]
> > > > @gleb-cloudius - I think the ask is why did the load fail.
> > > 
> > > 
> > > The error we got cannot be more clear. The node is overloaded by hints.
> > 
> > 
> > If hints are supposed to help us, and they don't (overloading), shouldn't we delete them when we get such error? (or is it too late?)
> 
> We can do many things. The hints behave the way they behave in cassandra and we can do something completely different. But you will fight symptoms not the problem.

Can you explain?

**Comment by gleb-cloudius** [comment]
> > > > > @gleb-cloudius - I think the ask is why did the load fail.
> > > > 
> > > > 
> > > > The error we got cannot be more clear. The node is overloaded by hints.
> > > 
> > > 
> > > If hints are supposed to help us, and they don't (overloading), shouldn't we delete them when we get such error? (or is it too late?)
> > 
> > 
> > We can do many things. The hints behave the way they behave in cassandra and we can do something completely different. But you will fight symptoms not the problem.
> 
> Can you explain?

Explain what?

**Comment by mykaul** [comment]
> > > > > > @gleb-cloudius - I think the ask is why did the load fail.
> > > > > 
> > > > > 
> > > > > The error we got cannot be more clear. The node is overloaded by hints.
> > > > 
> > > > 
> > > > If hints are supposed to help us, and they don't (overloading), shouldn't we delete them when we get such error? (or is it too late?)
> > > 
> > > 
> > > We can do many things. The hints behave the way they behave in cassandra and we can do something completely different. But you will fight symptoms not the problem.
> > 
> > 
> > Can you explain?
> 
> Explain what?

The problem... I may have misunderstood it.

**Comment by gleb-cloudius** [comment]
> > > > > > > @gleb-cloudius - I think the ask is why did the load fail.
> > > > > > 
> > > > > > 
> > > > > > The error we got cannot be more clear. The node is overloaded by hints.
> > > > > 
> > > > > 
> > > > > If hints are supposed to help us, and they don't (overloading), shouldn't we delete them when we get such error? (or is it too late?)
> > > > 
> > > > 
> > > > We can do many things. The hints behave the way they behave in cassandra and we can do something completely different. But you will fight symptoms not the problem.
> > > 
> > > 
> > > Can you explain?
> > 
> > 
> > Explain what?
> 
> The problem... I may have misunderstood it.

Overloaded exception happens when hints are not written to disk fast enough (in flight). There should not be 10485768 in flight hints.

**Comment by mykaul** [comment]
@eliransin - is this something your team need to look at?

**Comment by DoronArazii** [comment]
@piodul it's in your area of expertise?

**Comment by DoronArazii** [comment]
> > @eliransin - is this something your team need to look at?
> 
> We need to look at IO and hints metrics. hydra never worked for me.

@vponomaryov can you help with this?

**Comment by fgelcer** [comment]
> * Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e0063d34-df6e-47ce-9ceb-e978abe944f6)

@gleb-cloudius , if you click this link, you will be able to build a monitor from a Jenkins job, in case this is what you need:

`Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e0063d34-df6e-47ce-9ceb-e978abe944f6)`

**Comment by vponomaryov** [comment]
> > > @eliransin - is this something your team need to look at?
> > 
> > 
> > We need to look at IO and hints metrics. hydra never worked for me.
> 
> @vponomaryov can you help with this?

@fgelcer provided correct answer. No need to run `hydra` locally.

Need just to trigger the [hydra-show-monitor](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e0063d34-df6e-47ce-9ceb-e978abe944f6) CI job with the desired test ID.

**Comment by DoronArazii** [comment]
@gleb-cloudius / @kostja any ideas how to move forward with this urgent case?

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius / @kostja any ideas how to move forward with this urgent case?

For what reason it is urgent? Fixing c-s to not abort on a storm of errors is a solution.

**Comment by gleb-cloudius** [comment]
> 
> What's your expectation wrt c-s? Extend timeout?

My experience with it was that it stopped the traffic after a bunch of errors. It should not. Otherwise a temporary overload  (which may be worth investigating of course) becomes a catastrophic failure (traffic stopped, cluster is dead, call the wambulance!). IIRC there is an option to ignore errors. If not the QA needs to invest in fixing tools it uses for testing.

**Comment by mykaul** [comment]
> > What's your expectation wrt c-s? Extend timeout?
> 
> My experience with it was that it stopped the traffic after a bunch of errors. It should not. Otherwise a temporary overload (which may be worth investigating of course) becomes a catastrophic failure (traffic stopped, cluster is dead, call the wambulance!). IIRC there is an option to ignore errors. If not the QA needs to invest in fixing tools it uses for testing.

I understand - I'm just unsure (and don't know) - is c-s more sensitive than other clients apps? (assuming they are sanely configured, with reasonable timeouts, retries, etc.) ?

**Comment by gleb-cloudius** [comment]
> > > What's your expectation wrt c-s? Extend timeout?
> > 
> > 
> > My experience with it was that it stopped the traffic after a bunch of errors. It should not. Otherwise a temporary overload (which may be worth investigating of course) becomes a catastrophic failure (traffic stopped, cluster is dead, call the wambulance!). IIRC there is an option to ignore errors. If not the QA needs to invest in fixing tools it uses for testing.
> 
> I understand - I'm just unsure (and don't know) - is c-s more sensitive than other clients apps? (assuming they are sanely configured, with reasonable timeouts, retries, etc.) ?

It's c-s that fails intentionally. Look up "-errors" here: https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/tools/toolsCStress.html

**Comment by mykaul** [comment]
> > > > What's your expectation wrt c-s? Extend timeout?
> > > 
> > > 
> > > My experience with it was that it stopped the traffic after a bunch of errors. It should not. Otherwise a temporary overload (which may be worth investigating of course) becomes a catastrophic failure (traffic stopped, cluster is dead, call the wambulance!). IIRC there is an option to ignore errors. If not the QA needs to invest in fixing tools it uses for testing.
> > 
> > 
> > I understand - I'm just unsure (and don't know) - is c-s more sensitive than other clients apps? (assuming they are sanely configured, with reasonable timeouts, retries, etc.) ?
> 
> It's c-s that fails intentionally. Look up "-errors" here: https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/tools/toolsCStress.html

This is exactly my thinking: -errors [retries=N] - what should the N value be? I don't think we should just ignore errors?

**Comment by gleb-cloudius** [comment]
> > 
> > It's c-s that fails intentionally. Look up "-errors" here: https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/tools/toolsCStress.html
> 
> This is exactly my thinking: -errors [retries=N] - what should the N value be? I don't think we should just ignore errors?

Ignoring errors in c-s and ignoring then in a test result are two different things. You should not ignore presence of errors in a test run, but you should not stop traffic because a short period of error burst.

**Comment by DoronArazii** [comment]
@gleb-cloudius per your suggestions above, what should be the next step for this issue?

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius per your suggestions above, what should be the next step for this issue?

Run it with ignoring errors and lets see if the cluster is really died or not. As far as metrics goes I do see buildup of hints, but I did not see any serious problems in IO dashboard. In fact I did not see much IO in streaming scheduling group at all (IIRC this is one that is used for hints). May be you just overloaded the cluster and that is why you get overloaded exception which is there to tell you that you overloaded the cluster otherwise why would they exists?

**Comment by DoronArazii** [comment]
@vponomaryov ^^

**Comment by vponomaryov** [comment]
@gleb-cloudius , @DoronArazii
The load was absent since 15:05 till the loader crash at 16:29. 
The crash happened during the decommission of the `node-5` which was behaving not like all other nodes. 
How can we get `overload` not having any `load`?
Why all other , non-`node-5`, nodes were behaving differently?
The point of this bugreport is not stress tool and number of errors it tolerates.
The point of this bugreport is the `node-5` special non-healthy behavior.

**Comment by mykaul** [comment]
@gleb-cloudius - anything you need from @vponomaryov to continue the investigation?

**Comment by gleb-cloudius** [comment]
I already said what should be done.

**Comment by gleb-cloudius** [comment]
> The load was very-low since 15:05 till the loader crash at 16:29. >

By this point loaders are already dead. The load is zero.

> The crash happened during the decommission of the `node-5` which was behaving not like all other nodes.
> How can we get `overload` not having any (close-to-0) `load`? 

Overload errors were before the load stopped when one of the nodes was killed. Make sense since killing a node causes hints to be saved.

> Why all other , non-`node-5`, nodes were behaving differently?

Because they did not have hints accumulated. There is always a slowest node.

> The point of this bugreport is not stress tool and number of errors it tolerates. The point of this bugreport is the `node-5` special non-healthy behavior.

Because it was overloaded. As I said above I do see that it has hints accumulated in the graphs, so the error is expected. Why didn't it manage to flush them in time I did not look close into, and a glance on IO dashboard does not show anything special, but considering that hints do get accumulated and it is expected to have hints since one node is dead by this point the overloaded errors are expected.


> **Or, in short:** the load catastrophically dropped and failed only when the problematic `node-5` went down by the `decommission` process - after ~1,5 hours.

Try with ignore errors. I cannot tell why c-s crashes long after it stopped sending traffic.

**Comment by vponomaryov** [comment]
I think we can close it. The bug doesn't get reproduced anymore.
Example from the latest 5.2 test run ([Argus](https://argus.scylladb.com/test/8c977b7f-0cad-49ba-a41d-604ac9130d59/runs?additionalRuns[]=9e4df04f-75f7-4540-b8c2-a67f65381735), [CI](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-10gb-3h-azure-test/30)) with the same configuration:
![Screenshot from 2023-11-17 17-40-48](https://github.com/scylladb/scylladb/assets/3796058/3d73590c-d0fb-4a27-ae8e-d3e2dabfe830)
