### ISSUE TITLE
parallel build could fail the `create-relocatable-package.py`

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#14079]
we use ninja to build precompiled tarballs. usually, this works fine. but sometimes if fails. #13978 was created to understand the root cause. and we are observing a more interesting backtrace:
```
19:15:36  FAILED: build/dev/dist/tar/scylla-unstripped-5.4.0~dev-0.20230529.4ad9ac84b448.x86_64.tar.gz 
19:15:36  scripts/create-relocatable-package.py --mode dev 'build/dev/dist/tar/scylla-unstripped-5.4.0~dev-0.20230529.4ad9ac84b448.x86_64.tar.gz'
19:15:36  Traceback (most recent call last):
19:15:36    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/scripts/create-relocatable-package.py", line 170, in <module>
19:15:36      ar.reloc_add('build/node_exporter', arcname='node_exporter')
19:15:36    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/scripts/create-relocatable-package.py", line 24, in reloc_add
19:15:36      return self.add(name, arcname="{}/{}".format(RELOC_PREFIX, arcname),
19:15:36             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:15:36    File "/usr/lib64/python3.11/tarfile.py", line 2008, in add
19:15:36      self.add(os.path.join(name, f), os.path.join(arcname, f),
19:15:36    File "/usr/lib64/python3.11/tarfile.py", line 1986, in add
19:15:36      tarinfo = self.gettarinfo(name, arcname)
19:15:36                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
19:15:36    File "/usr/lib64/python3.11/tarfile.py", line 1865, in gettarinfo
19:15:36      statres = os.lstat(name)
19:15:36                ^^^^^^^^^^^^^^
19:15:36  FileNotFoundError: [Errno 2] No such file or directory: 'build/node_exporter/sth72i28'
19:15:36  Exception ignored in: <function _Stream.__del__ at 0x7f08aba8d080>
19:15:36  Traceback (most recent call last):
19:15:36    File "/usr/lib64/python3.11/tarfile.py", line 411, in __del__
19:15:36    File "/usr/lib64/python3.11/tarfile.py", line 461, in close
19:15:36  ValueError: write to closed file
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1545/

with @syuu1228 's comment at https://github.com/scylladb/scylladb/pull/13978#issuecomment-1565613124 

> Hmm, I thought `FileExistsError` won't happen since executes `shutil.rmtree()` just before `os.makedirs()`. Maybe this is because we are running multiple builds in parallel with different modes? If so, it can be fix by changing build directory from `build/{SCYLLA_DIR}` to `build/{mode}/{SCYLLA_DIR}`.

it's obvious that the backtrace above is a strong proof that Takuya's guess is quite right. in other words, we have two build job running in parallel:

1. `scripts/create-relocatable-package.py --mode dev 'build/dev/dist/tar/scylla-unstripped-5.4.0~dev-0.20230529.4ad9ac84b448.x86_64.tar.gz'`, which collects the bits from `node_exporter`, using 

   ```py
   ar.reloc_add('build/node_exporter/node_exporter', arcname='node_exporter/node_exporter')
   ```
2.   `scripts/strip.sh build/node_exporter/node_exporter`, which uses objcopy to do its job. 

but according to [objcopy(1)](https://man7.org/linux/man-pages/man1/objcopy.1.html):

> objcopy creates temporary files to do its translations and deletes them afterward.

so there is a racing that the python's tarfile module could be reading a directory still in flux, so when it tries to `lstat` a file previous found in this directory, that file could have been deleted because it is a temporary file created by `objcopy`. that's why we have this backtrace with a file named `build/node_exporter/sth72i28`, which was not directly created by us.

**Comment by avikivity** [comment]
IIUC it's rare enough that we don't need to backport this.
