### ISSUE TITLE
boost.multishard_mutation_query_test.test_read_all fails

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#14087]
```
14:59:26  INFO  2023-05-30 09:48:47,956 [shard 1] messaging_service - Stopping tls server - Done
14:59:26  unknown location(0): fatal error: in "test_read_all": seastar::internal::backtraced<std::runtime_error>: do_require(): FAIL @ void tests::require_equal(const LHS &, const RHS &, std::source_location) [LHS = unsigned long, RHS = unsigned int]() test/lib/test_utils.hh:46: 1 != 0 Backtrace: /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x52b98e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x52bf70 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x52c288 0xf7a6c2 0xf7a4d4 0x265b3d0 0x265b254 0x26593b0 0xe7eaaa 0xe7e605 0xe7d55b 0xe7d3e8 0xe7b143 0xe7a542 0x25c050e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x42eaa6
14:59:26     --------
...
 test/boost/multishard_mutation_query_test.cc(516): Leaving test case "test_read_all"; testing time: 3203680us
...

14:59:26  Output of build/dev/test/boost/multishard_mutation_query_test --run_test=test_read_all --report_level=no --logger=HRF,test_suite:XML,test_suite,/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/dev/xml/boost.multishard_mutation_query_test.test_read_all.1.xunit.xml --catch_system_errors=no --color_output=false -- -c2 -m3G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100:

...

14:59:26  random-seed=1589691387
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1554/

not sure exactly which test failed. created #14086 to ease the future investigation.

**Comment by avikivity** [comment]
@tchaikov our tests sometimes output a random seed they ran with, which makes it easier to reproduce

**Comment by tchaikov** [comment]
thank you Avi. so i can / need to try to reproduce the failure with the seed.

**Comment by DoronArazii** [comment]
@denesb any updates here? 
raising the priority as we are trying to eliminate those issues

**Comment by denesb** [comment]
> @denesb any updates here? raising the priority as we are trying to eliminate those issues

No progress. We need another failure which has the error with the now fixed source lines.

**Comment by mykaul** [comment]
Can we close if it was not reproduced thus far? We can always re-open.

**Comment by tchaikov** [comment]
closing as "works for us so far" =)

**Comment by mykaul** [comment]
@denesb -, @tchaikov 
I've just seen a failure @ https://jenkins.scylladb.com/job/scylla-master/job/next/6711/testReport/junit/boost/multishard_mutation_query_test/test_read_all/ - can you please take a look?
(probably need to open a new bug?)

**Comment by denesb** [comment]
> @denesb -, @tchaikov I've just seen a failure @ https://jenkins.scylladb.com/job/scylla-master/job/next/6711/testReport/junit/boost/multishard_mutation_query_test/test_read_all/ - can you please take a look? (probably need to open a new bug?)

Wow, I can actually reproduce this failure with the random seed from the test.

**Comment by avikivity** [comment]
Backported to 5.4. Will backport further if this shows up in CI (test-only issue so production workloads are not affected).
