### ISSUE TITLE
doc: update the OS support matrix for version 5.3

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#14084]
I'm going to update the OS support matrix for ScyllaDB 5.3: https://docs.scylladb.com/stable/getting-started/os-support.html

@roydahan @scylladb/releng @tzach 
Please provide me with the information about OSs for which we added or dropped support in version 5.3.
If nothing has changed compared to version 5.2, please let me know, too.

**Comment by yaronkaikov** [comment]
@annastuchlik Ubuntu 18.04 was dropped

**Comment by yaronkaikov** [comment]
@roydahan We also support now rocky9, right ?

**Comment by roydahan** [comment]
Yes.

**Comment by denesb** [comment]
5.3 was scratched, not backporting.
