### ISSUE TITLE
Optimization for avoiding bloom filter during compaction is gone

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14091]
Commit https://github.com/scylladb/scylladb/commit/8c4b5e4283a09a18594d1ad5f3d16b61da22b0bb introduced an optimization which only calculates max purgeable timestamp when a tombstone satisfy the grace period.

Commit 'repair: Get rid of the gc_grace_seconds' removed it.

Compaction is much slower as a result when facing tombstone heavy workloads.

**Comment by mykaul** [comment]
@raphaelsc - any idea why this issue is still open?

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/pull/13908 is the one fixing it, I reckon?

**Comment by raphaelsc** [comment]
> @raphaelsc - any idea why this issue is still open?

That's my fault. Closing it with https://github.com/scylladb/scylladb/commit/38b226f997c55a46267b9bdf7bebcf8718b86cc8...

**Comment by mykaul** [comment]
@raphaelsc , @avikivity - do we plan to backport this?

**Comment by raphaelsc** [comment]
> @raphaelsc , @avikivity - do we plan to backport this?

It's fixing a regression, so my understanding is yes, we need to backport this. Customers that are using default TTL can be really affected by this.

**Comment by mykaul** [comment]
@raphaelsc , @avikivity - please backport then.

**Comment by avikivity** [comment]
@raphaelsc please prepare backports.

**Comment by raphaelsc** [comment]
> @raphaelsc please prepare backports.

5.2: https://github.com/scylladb/scylladb/pull/15744
5.1: https://github.com/scylladb/scylladb/pull/15745

**Comment by denesb** [comment]
Backports queued, removing backport candidate labels.
