### ISSUE TITLE
alternator: DeleteTable returns some details which DynamoDB doesn't

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14132]
In commit https://github.com/scylladb/scylladb/commit/ffd4fcceec4237bb2b145bc23b30d17a7fd5b4e9 @alezzqz fixed issue https://github.com/scylladb/scylladb/issues/11472 where Alternator's `DeleteTable` operation did not return all the information about the deleted table that DynamoDB did.

However, it seems we added **too many** things to the response. The test we have for this feature currently **fails** on DynamoDB and shows that the attributes **`KeySchema`**, **`AttributeDefinitions`**, and **`CreationDateTime`** that we added (and the test checks) are not actually returned by DynamoDB for `DeleteTable` (they are returned by `DescribeTable`):
```
test/alternator/run --aws test_table.py::test_delete_table_description 
```

There are two ways to fix this:
1. Be maximally compatible with DynamoDB and **don't** return these three attributes in the `DeleteTable` response. The test should be modified to check that these attributes are _not_ returned instead of checking (as it does now) that they _are_ returned.
2. Leave those extra attributes in the response as a Scylla extension. Document this extension somewhere (at a minimum, in code comments) and split the test into two - one that passes on both Alternator and DynamoDB, and another one checking the Scylla extension that is expected to fail on DynamoDB.

**Comment by alezzqz** [comment]
I could try to create new tests but unfortunately I have no DynamoDB credentials and couldn't run it's tests

**Comment by nyh** [comment]
> I could try to create new tests but unfortunately I have no DynamoDB credentials and couldn't run it's tests

Please do try to get DynamoDB credentials. According to https://aws.amazon.com/dynamodb/pricing/ they have a free tier which is more than enough to run the tests.

Anyway, before changing the code or tests, we should decide which approach to take. My gut feeling is that unless there is a good reason for us to extend DynamoDB (in this case, to return the schema of a just-deleted table), we shouldn't, and we should just implement the minimum that DynamoDB does. So that's option 1 above. But I'm open to being convinced otherwise.

**Comment by Jager227** [comment]
> > I could try to create new tests but unfortunately I have no DynamoDB credentials and couldn't run it's tests
> 
> Please do try to get DynamoDB credentials. According to https://aws.amazon.com/dynamodb/pricing/ they have a free tier which is more than enough to run the tests.
> 
> Anyway, before changing the code or tests, we should decide which approach to take. My gut feeling is that unless there is a good reason for us to extend DynamoDB (in this case, to return the schema of a just-deleted table), we shouldn't, and we should just implement the minimum that DynamoDB does. So that's option 1 above. But I'm open to being convinced otherwise.

Is it a final decision?
