### ISSUE TITLE
test_compaction_task.test_major_keyspace_compaction_task failure

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#14131]
https://jenkins.scylladb.com/job/scylla-master/job/next/6095/

head: 3cd9aa1448a7a37bd1326c2813d6ba41d45904a7

```
scylla-master/next failed on Test stage, for more details: https://jenkins.scylladb.com/job/scylla-master/job/next/6095/
failed tests: 2 of 17375.
- test_compaction_task.test_major_keyspace_compaction_task
    requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.139.67.12:10000/task_manager/wait_task/eb347f8e-2e92-4a6a-a87a-8282d167bbe2
- non-boost tests.rest_api.test_compaction_task.debug.1
Full details on the Test Result page: https://jenkins.scylladb.com/job/scylla-master/job/next/6095/testReport/
```

**Comment by nyh** [comment]
The failed test is from test/rest_api, `test_compaction_task.py::test_major_keyspace_compaction_task`, using the debug build mode.
I ran it 1000 times locally on a dev build and it didn't fail, so maybe the failure has something to do with timing or the slow debug run.
The test got an 500 Internal Server Error response for `http://127.139.67.12:10000/task_manager/wait_task/eb347f8e-2e92-4a6a-a87a-8282d167bbe2`. The pytest log is https://jenkins.scylladb.com/job/scylla-master/job/next/6095/artifact/testlog/x86_64/debug/rest_api.test_compaction_task.1.log and the Scylla log is https://jenkins.scylladb.com/job/scylla-master/job/next/6095/artifact/testlog/x86_64/debug/scylla-25.log - I don't see anything there which might give more information on this "500" error (I hoped I would see somewhere some more specific exception message, but I don't).

**Comment by avikivity** [comment]
Doesn't backport cleanly to 5.3. @Deexie is it needed there (and earlier)?

**Comment by Deexie** [comment]
It is needed since 48082207292971c8fc27237aff889d374a5a751e. So it's needed in 5.3 but not earlier

**Comment by Deexie** [comment]
On second thought, no, there is no need. While this one improves the test, it does not solve the problem entirely.

https://github.com/scylladb/scylladb/pull/14585, which will surely be clearer to apply, will do the job and will be worth backporting.

**Comment by avikivity** [comment]
Not backporting per above.
