### ISSUE TITLE
CDC log table not yet available after returning from CREATE TABLE

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14138]
I'm not sure if this is a bug in Scylla, the Python driver, or both of them, so I'll try to describe the problem.

I can reproduce this problem in dtest when avoiding sleeps during Scylla boot (it may also be reproducable with Raft-based cluster management), in many CDC tests including 
`cdc_test.py::TestCdcWithCompactStorage::test_artificial_column_with_type_empty_is_missing[preimage:full-postimage:false-use_regular_column:false]`.

These tests have a 2-node cluster, create a table with CDC enabled, and immediately afterwards read from the CDC log - `SELECT * FROM ks1.cf1_scylla_cdc_log` with **CL=ALL**.  The read often fails with:

```
Cannot achieve consistency level for cl ALL. Requires 2, alive 1
```

The problem goes away if I add a 1-second sleep before the SELECT.

I think something like the following happens:
1. The CREATE TABLE creates two table-creating mutations, for the base table and the CDC table.
2. The second node receives these mutations in this order, and does them one after another.
3. If the client happens to send the SELECT between these two mutations, the second node will not know of the cdc_log table and the request will fail.

I suspect that for some reason CREATE TABLE returns before applying both mutations locally. The Python driver appears to wait for schema agreement after a schema change, but perhaps we returned before the mutation was even applied locally, so the schema agreement is trivially successful (it sees the pre-change state) - so doesn't wait?

CC @kbr-scylla

**Comment by kbr-scylla** [comment]
@nyh do you create the table immediately after bootstrapping the two nodes (and this is done with 0 sleeps)? Because if so, it might be that the nodes don't see each other in `system.peers` by the time you create the table, so the schema doesn't propagate and driver's `wait_for_schema_agreement` doesn't work. I saw this in our test.py topology tests in non-Raft mode; we need to add explicit token ring synchronization waits to avoid this.

If this is what happens, it should be reproducible with normal table creation as well (just create a table *without* CDC immediately after booting the cluster and try to query it).

However, you only posted this:
```
Cannot achieve consistency level for cl ALL. Requires 2, alive 1
```

I don't think this error appears when the other node is missing schema. IIRC this error appears on an early check in `storage_proxy`, before the query is even done, when `storage_proxy` looks into `gossiper` to see if the required number of nodes is alive.

If it was a problem with missing schema, you should see an error in the logs too, something like "couldn't find column_family" (I don't remember the specifics).

So it could also be that the node doesn't see the other as alive yet, which is also plausible if you try to do the query immediately after boot.

**Comment by kbr-scylla** [comment]
> IIRC this error appears on an early check in storage_proxy, before the query is even done, when storage_proxy looks into gossiper to see if the required number of nodes is alive.

Yep, it's thrown from `assure_sufficient_live_nodes` - even before the coordinator tries to contact any other node.

The exception you would get if coordinator tried to contact a replica and then failed would be `request_timeout_exception` or `request_failure_exception`. But you're getting `unavailable_exception`:
```cpp
unavailable_exception::unavailable_exception(db::consistency_level cl, int32_t required, int32_t alive) noexcept
    : unavailable_exception(prepare_message("Cannot achieve consistency level for cl {}. Requires {}, alive {}", cl, required, alive),
        cl, required, alive)
    {}

request_timeout_exception::request_timeout_exception(exception_code code, const sstring& ks, const sstring& cf, db::consistency_level consistency, int32_t received, int32_t block_for) noexcept
    : cassandra_exception{code, prepare_message("Operation timed out for {}.{} - received only {} responses from {} CL={}.", ks, cf, received, block_for, consistency)}
    , consistency{consistency}
    , received{received}
    , block_for{block_for}
    { }

request_failure_exception::request_failure_exception(exception_code code, const sstring& ks, const sstring& cf, db::consistency_level consistency_, int32_t received_, int32_t failures_, int32_t block_for_) noexcept
    : cassandra_exception{code, prepare_message("Operation failed for {}.{} - received {} responses and {} failures from {} CL={}.", ks, cf, received_, failures_, block_for_, consistency_)}
    , consistency{consistency_}
    , received{received_}
    , failures{failures_}
    , block_for{block_for_}
    {}
```

**Comment by nyh** [comment]
> > IIRC this error appears on an early check in storage_proxy, before the query is even done, when storage_proxy looks into gossiper to see if the required number of nodes is alive.

Thanks. I'll look more into this angle. I thought I already fixed CCM bugs which didn't wait enough for "wait_other_notice" and then the bug (that your fix was merged) that Scylla didn't wait for the first node when starting the second node, but maybe I missed another thing in this area. Beyond using CDC these dtests also have their own special code for starting the cluster, maybe this special code has a bug that it's not wait_other_notice properly.

If it's this, then indeed it's not related to CDC and I'll close this issue.

**Comment by nyh** [comment]
@kbr-scylla you were right - if I change this test to read with CL=ALL the base table, it also fails with the same error. So the CDC was a red herring and unrelated to this test bug, and this appears to be a test bug, not a Scylla bug.. Thanks. I'm closing this issue now.

**Comment by nyh** [comment]
It turns out that waiting for nodes to know that each other as "live", as we do now in CCM (after fixing previous bugs...)  isn't quite enough :-( For CL=ALL to work on node 1, it needs to know not only that node 2 is "alive", but it needs to know that it actually has the tokens that are being used in this query.

So it appears we need to find a way until node 1 knows node 2's tokens, not just that node 2 is alive :-( What a mess.

**Comment by nyh** [comment]
Or maybe it's even worse! The function `storage_proxy::get_endpoints_for_reading()` finds **zero** nodes, not even one. This doesn't make sense.  I'll stop the spam now until I find a solution :-(
