### ISSUE TITLE
raft topology: assertion failure on node restart

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14136]
Bootstrap a single node then restart it:
```
scylla: service/storage_service.cc:1211: future<> service::topology_coordinator::handle_node_transition(service::topology_coordinator::node_to_work_on &&): Assertion `!node.rs->ring' failed.
Aborting on shard 0.
Backtrace:
  /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so+0x3b9f2c
  /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so+0x3e4bd2
  /lib64/libc.so.6+0x3cb1f
  /lib64/libc.so.6+0x8ce5b
  /lib64/libc.so.6+0x3ca75
  /lib64/libc.so.6+0x267fb
  /lib64/libc.so.6+0x2671a
  /lib64/libc.so.6+0x35655
  0x231e30b
  0x230e4e8
  0x22dbc92
  0xfce9ad
  /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so+0x3c865f
  /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so+0x3c9827
  /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so+0x3c8c49
  /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so+0x34277e
  /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so+0x34198e
  0xf66382
  0xfa0b60
  0xf6539b
  /lib64/libc.so.6+0x2750f
  /lib64/libc.so.6+0x275c8
  0xf63f24
```

looks like the node does not observe itself inside topology, there's this print:
```
INFO  2023-06-05 12:55:51,849 [shard 0] storage_service - raft topology: adding myself to topology: 4286c668-3655-4ccd-bba2-8179401da962
```

which means the node went there:
```cpp
    while (!_topology_state_machine._topology.contains(raft_server.id())) {
        slogger.info("raft topology: adding myself to topology: {}", raft_server.id());
```

This caused it to add itself as "joining", but there's already a row for this node in topology - hence the assertion failure.

**Comment by kbr-scylla** [comment]
This is a regression introduced in commit f26179cd27a1948386f9d86cb5d3e89f8c5224ad
```
Author: Gleb Natapov <gleb@scylladb.com>
Date:   Sun May 28 18:13:49 2023 +0300

    service: raft: split off setup_group0_if_exist from setup_group0
    
    Currently setup_group0 is responsible to start existing group0 on restart
    or create a new one and joining the cluster with it during bootstrap. We
    want to create the server for existing group0 earlier, before we start
    to accept messages because some messages may assume that the server
    exists already. For that we split creation of exiting group0 server into
    a separate function and call it on restart before the messaging service
    starts accepting messages.
    
    Fixes: #13887
```

@gleb-cloudius 

I'm suspecting this might be related to persistence somehow - perhaps the Raft log / snapshot are not loaded properly if we initialize group 0 early? Which would mean it's much worse than just Raft topology, because it could also affect other group 0 stuff (schema).

**Comment by kbr-scylla** [comment]
Wait a sec, I might have broken something on my side

**Comment by kbr-scylla** [comment]
No, I verified - it's https://github.com/scylladb/scylladb/commit/f26179cd27a1948386f9d86cb5d3e89f8c5224ad

**Comment by kbr-scylla** [comment]
After applying this:
```diff
diff --git a/service/storage_service.cc b/service/storage_service.cc
index 1aaeda5e37..a1d85c23ae 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -307,10 +307,6 @@ future<> storage_service::topology_state_load(cdc::generation_service& cdc_gen_s
     running = true;
 #endif
 
-    if (!_raft_topology_change_enabled) {
-        co_return;
-    }
-
     slogger.debug("raft topology: reload raft topology state");
     // read topology state from disk and recreate token_metadata from it
     _topology_state_machine._topology = co_await db::system_keyspace::load_topology_state();
```

I'm now getting a segfault.
```
[Backtrace #0]
/home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=711dc0100d57fcd0826204e4644569a4a50b4122, not stripped

seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at reactor.cc:?
seastar::install_oneshot_signal_handler<11, (void (*)())(&seastar::sigsegv_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at reactor.cc:?
/lib64/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=81daba31ee66dbd63efdc4252a872949d874d136, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
service::wait_until_every_peer_joined_group0(db::system_keyspace&, service::group0_members const&, seastar::abort_source&) at raft_group0.cc:?
service::storage_service::topology_state_load(cdc::generation_service&) [clone .resume] at storage_service.cc:?
seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at main.cc:?
seastar::reactor::run_some_tasks() at ??:?
seastar::reactor::do_run() at ??:?
seastar::reactor::run() at ??:?
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ??:?
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ??:?
scylla_main(int, char**) at main.cc:?
std::function<int (int, char**)>::operator()(int, char**) const at ??:?
main at main.cc:?
__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

it doesn't make sense: we don't call `wait_until_every_peer_joined_group0` from `topology_state_load`.

Looks like we're accessing some uninitialized stuff from `topology_state_load` when we apply those commands early? Indeed, is `storage_service` initialized by this time yet?

**Comment by gleb-cloudius** [comment]
> After applying this:
> 
> ```diff
> diff --git a/service/storage_service.cc b/service/storage_service.cc
> index 1aaeda5e37..a1d85c23ae 100644
> --- a/service/storage_service.cc
> +++ b/service/storage_service.cc
> @@ -307,10 +307,6 @@ future<> storage_service::topology_state_load(cdc::generation_service& cdc_gen_s
>      running = true;
>  #endif
>  
> -    if (!_raft_topology_change_enabled) {
> -        co_return;
> -    }
> -
>      slogger.debug("raft topology: reload raft topology state");
>      // read topology state from disk and recreate token_metadata from it
>      _topology_state_machine._topology = co_await db::system_keyspace::load_topology_state();
> ```
> 
> I'm now getting a segfault.

I am not sure it is safe. We check it in other places.

> 
> ```
> [Backtrace #0]
> /home/kbraun/dev/scylladb/build/dev/seastar/libseastar.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=711dc0100d57fcd0826204e4644569a4a50b4122, not stripped
> 
> seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at reactor.cc:?
> seastar::install_oneshot_signal_handler<11, (void (*)())(&seastar::sigsegv_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at reactor.cc:?
> /lib64/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=81daba31ee66dbd63efdc4252a872949d874d136, for GNU/Linux 3.2.0, not stripped
> 
> __GI___sigaction at :?
> service::wait_until_every_peer_joined_group0(db::system_keyspace&, service::group0_members const&, seastar::abort_source&) at raft_group0.cc:?
> service::storage_service::topology_state_load(cdc::generation_service&) [clone .resume] at storage_service.cc:?
> seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at main.cc:?
> seastar::reactor::run_some_tasks() at ??:?
> seastar::reactor::do_run() at ??:?
> seastar::reactor::run() at ??:?
> seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ??:?
> seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ??:?
> scylla_main(int, char**) at main.cc:?
> std::function<int (int, char**)>::operator()(int, char**) const at ??:?
> main at main.cc:?
> __libc_start_call_main at ??:?
> __libc_start_main_alias_2 at :?
> _start at ??:?
> ```
> 
> it doesn't make sense: we don't call `wait_until_every_peer_joined_group0` from `topology_state_load`.
> 
> Looks like we're accessing some uninitialized stuff from `topology_state_load` when we apply those commands early? Indeed, is `storage_service` initialized by this time yet?

It should be. We call `ss.local().join_cluster()` next thing (besides starting listening on messaging service, but ss should be ready when we open listening port as well).

**Comment by gleb-cloudius** [comment]
> > I am not sure it is safe. We check it in other places.
> 
> We wouldn't commit topology change commands unless topology was enabled. This should be an assertion if anything.

IIRC it is there because ` group0_state_machine::load_snapshot` calls it unconditionally.

**Comment by gleb-cloudius** [comment]
> 
> Looks like we're accessing some uninitialized stuff from `topology_state_load` when we apply those commands early? Indeed, is `storage_service` initialized by this time yet?

We accessing `ss::_group0` which is set in `join_cluster` as well and used during snapshot loading.

**Comment by tgrabiec** [comment]
Would that be a reason to move topology state machine out of storage_service? This way the init dependency is:

```
group0_state_machine <- group0 <- storage_service
```

**Comment by gleb-cloudius** [comment]
> Would that be a reason to move topology state machine out of storage_service? This way the init dependency is:
> 
> ```
> group0_state_machine <- group0 <- storage_service
> ```

And if there is a link from group0_state_machine back to storage_service there will be still a loop. And currently there is. 

But there is no init order problem now. storage_service is initialized much earlier then group0_state_machine.

**Comment by avikivity** [comment]
experimental code, not backporting.
