### ISSUE TITLE
 raft.replication_test.backpressure_drops fails

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#14160]
scylla-master/next failed on Test stage, for more details: https://jenkins.scylladb.com/job/scylla-master/job/next/6103/
failed tests: 1 of 17530.
- raft.replication_test.backpressure_drops
Full details on the Test Result page: https://jenkins.scylladb.com/job/scylla-master/job/next/6103/testReport/

**Comment by kostja** [comment]
@kbr-scylla is looking at it it's a duplicate of #14029
