### ISSUE TITLE
upgrade_test.TestUpgradeWithExperimentalRaft.test_upgrade_cluster_nodes_with_twcs: Bad configuration: consistent_cluster_management requires schema commit log to be enabled

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14176]
Failing since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release-with-raft/129/testReport/junit/upgrade_test/TestUpgradeWithExperimentalRaft/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split019___test_upgrade_cluster_nodes_with_twcs/
```
ccmlib.node.NodeUpgradeError: Node node1 failed to start after upgrade. Error: 04 May 2023 03:07:18 [node2] Missing: ['127.0.98.1.* now UP']:
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release-with-raft/129/artifact/logs-full.release.019/1683169642210_upgrade_test.py%3A%3ATestUpgradeWithExperimentalRaft%3A%3Atest_upgrade_cluster_nodes_with_twcs/node1.log
```
INFO  2023-05-04 02:55:41,445 [shard 0] init - Scylla version 4.6.11-0.20221128.6c0825e2a with build-id 20fae5748479d9299577bec6c68d77ef5cc0d6a7 starting ...
...
INFO  2023-05-04 03:05:16,691 [shard 0] init - Scylla version 4.6.11-0.20221128.6c0825e2a shutdown complete.
...
INFO  2023-05-04 03:05:17,832 [shard 0] init - Scylla version 5.3.0~dev-0.20230504.113fb3201972 with build-id 73f7ce039257cd915d5ddd363ca50675ef9b86eb starting ...
...
ERROR 2023-05-04 03:05:18,114 [shard 0] init - Bad configuration: consistent_cluster_management requires schema commit log to be enabled
```

**Comment by bhalevy** [comment]
FWIW, I'm not sure if the issue is with the test or with scylla.

**Comment by kostja** [comment]
With the test.

**Comment by gusev-p** [comment]
It doesn't reproduce locally for some reason (the test passed). The command I used:
`(env) [gusev-p@potwor1 scylla-dtest]$ pytest --rootdir '/home/gusev-p/scylla-dtest' -s -c '/home/gusev-p/scylla-dtest/pytest.ini' --scylla-version release:5.2 --cassandra-dir '/home/gusev-p/scylladb/build/release' upgrade_test.py::TestUpgradeWithExperimentalRaft::test_upgrade_cluster_nodes_with_twcs &> /home/gusev-p/dtest-run/my_out`

Can someone familiar with the test code please help me?

The initial problem is that schema commitlog must be enabled before enabling raft. When existing user is migrating to raft, they need to restart the cluster with new code without raft and wait for schema commitlog feature to spread around the cluster. Then another restart with enabled raft. For new users there is a `force_schema_commit_log` flag in a config which allows to use schema commit log without waiting for the feature. I'm not sure how to reflect this in the logic of the tests.

There is already a [full-fledged upgrade test](https://github.com/scylladb/scylladb/blob/master/test/topology_raft_disabled/test_raft_upgrade_no_schema.py) for this scenario in terms of test.py.

@fruch @aleksbykov @juliayakovlev

**Comment by aleksbykov** [comment]
@gusev-p , does release version 5.2 already use schema_commit_log feature enabled by default for new node?

**Comment by gusev-p** [comment]
> @gusev-p , does release version 5.2 already use schema_commit_log feature enabled by default for new node?

Only if `force_schema_commit_log: true` is set in `scylla.yaml`.

**Comment by fruch** [comment]
@gusev-p 

You were running the test with 5.2

The issue is seen on master

Use 

--scylla-version=unstable/master:latest

And you might be able to see the failure

**Comment by aleksbykov** [comment]
@gusev-p , then may be need set it explicitly in test to false

**Comment by gusev-p** [comment]
> @gusev-p , then may be need set it explicitly in test to false

to true you mean, yeah, probably, will try

**Comment by gusev-p** [comment]
test failed locally with this command:
`pytest --rootdir '/home/gusev-p/scylla-dtest' -s -c '/home/gusev-p/scylla-dtest/pytest.ini' --keep-test-dir --scylla-version=unstable/master:latest --consistent-cluster-management --cassandra-dir '/home/gusev-p/scylladb/build/release' upgrade_test.py &> /home/gusev-p/dtest-run/my_out`

can be swept under the rug with ``force_schema_commit_log`: true`
