### ISSUE TITLE
compare_cells_for_merge may wrongly prefer an expired cell over a live and expiring one

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14182]
`compare_atomic_cell_for_merge` currently compares cell values for two live / expiring cells that have the same write timestamp.

If the values are different, the function selects the cell with the larger value, without comparing their expiration time and ttl.

That may lead to selecting an already expired cell over one that is still alive and that will expire later.
This may show up over cql as a row with null value for the cell, instead of no results if only the expired cell would exist.

Detailed description:
The comparison function is implemented as follows:
https://github.com/scylladb/scylladb/blob/ce6a1ca13b598e1ecbf60c270b69a3810053522c/mutation/atomic_cell.cc#L73-L110

It compares the cell's attributes in the following order:
1. timestamp
2. liveliness
and in case both are alive:
3. value
4. has_ttl (prefer expiring cells)
if both are expiring
5. expiry (prefer cells that expire later)
6. ttl (prefer cells that were written later, i.e. have smaller ttl)

With eventual consistency semantics, it's unclear why comparing cells value trumps over timing related attributes, where the write timestamp-based logic clearly dictates that latest writes wins, regardless of the value they carry.
So when 2 cells timestamp is equal, we should pick the one that appears to have been written later, and only if all timing-related attributes are equal, examine the value so to keep the selection algorithm deterministic.

This was suggested by @vladzcloudius based on a field issue where the user apparently uses `USING TIMESTAMP` and hits a corner case when apparently retrying a write using a previously used timestamp that causes a cell to lose its value:

This was reproduced by @tgrabiec as follows:
```
cqlsh> insert into test.t (pk, ck, v) values (1, 2, 100) using ttl 10 and timestamp 700;
cqlsh> insert into test.t (pk, ck, v) values (1, 2, 90) using ttl 10 and timestamp 700;

cqlsh> select * from test.t;

 pk | ck | v
----+----+-----
  1 |  2 | 100

(1 rows)
cqlsh> select * from test.t;

 pk | ck | v
----+----+------
  1 |  2 | null
```

**Comment by bhalevy** [comment]
Also, `atomic_cell_or_collection::equals` also compares value last for live or expiring cells:
https://github.com/scylladb/scylladb/blob/ce6a1ca13b598e1ecbf60c270b69a3810053522c/mutation/atomic_cell.cc#L124-L160

**Comment by nyh** [comment]
I agree that our existing comparison order makes little sense, but nothing we'll ever do on timestamp ties will ever be "correct" - timestamp ties are a problem that Scylla can't really solve no matter which order we chose, and you shouldn't have them. The only reason why this tie-breaking code had to exist in the first place is to ensure that the reconciliation process converges on some result and doesn't oscillate back and forth when the same data is merged multiple times in repairs etc.

If we change the order in our code, we may need to do something to avoid the above "oscillation" problem on mixed clusters during upgrades.

**Comment by vladzcloudius** [comment]
> I agree that our existing comparison order makes little sense, but nothing we'll ever do on timestamp ties will ever be "correct" - timestamp ties are a problem that Scylla can't really solve no matter which order we chose, and you shouldn't have them. The only reason why this tie-breaking code had to exist in the first place is to ensure that the reconciliation process converges on some result and doesn't oscillate back and forth when the same data is merged multiple times in repairs etc.
> 
> If we change the order in our code, we may need to do something to avoid the above "oscillation" problem on mixed clusters during upgrades.

This is not a problem, @nyh. This "oscillation" will happen only once and we should document that properly in release notes. I don't see this as an issue at all considering the real issue (and NOT a corner case, @bhalevy!) we are going to fix here.

**Comment by bhalevy** [comment]
> client retries the write some time later but adjusts the value of `v` that corresponds to the state at the time of retry:

new value must haveca new timestamp if it needs to overridecthe orevious value.
This is not a retry anymore.

**Comment by vladzcloudius** [comment]
> > client retries the write some time later but adjusts the value of `v` that corresponds to the state at the time of retry:
> 
> new value must have a new timestamp if it needs to overridecthe orevious value. This is not a retry anymore.

In my example it's the same timestamp (due to `USING TIMESTAMP`). It has a different expiration time (because a "now" on a coordinator was different) however due to a bug in the current resolution logic scylla won't get to checking it.

**Comment by vladzcloudius** [comment]
> The only gurantee we can make with eventual consistency is that data (or deletions) that has larger write timestamp wins. When there's a tie, all bets are off, and the assumption is that 2 cells with the same write timestamp will carry the same value and will have the same expiration properties and times. Anything we do in this area is complimentary and the user shouldn't plan their application around it to prefer one value over another.

This is simply not true, @bhalevy. And the code in Cassandra is the proof.
We should fix the bug in our code and move on.

> Retried inserts that use the same write timestamp should write the same value, and if there is a ttl to that data, the retry should adjust the remaining ttl USING TTL over CQL, such that the expiration time of the retried insert would be the same as the original one.
> In particular, if the application wants to update a cell value, it must issue a larger timestamp for it.

The same here. Please, don't invent the restrictions that don't and should not exist.

**Comment by raphaelsc** [comment]
checking in late to the party, but here's my understanding:

we know expiry to be picked from coordinator's clock, which means data of ts T and ttl N will be expired in N seconds.

if I redo that write (for whatever reason I want), I expect that the new write, which has a higher expiry, will shadow the previous write with lower expiry. a cell value is completely arbitrary and should be our last resort in our merging rules.

that's the semantics. otherwise, like @vladzcloudius pointed out, we'll cause confusion.

**Comment by bhalevy** [comment]
> > The only gurantee we can make with eventual consistency is that data (or deletions) that has larger write timestamp wins. When there's a tie, all bets are off, and the assumption is that 2 cells with the same write timestamp will carry the same value and will have the same expiration properties and times. Anything we do in this area is complimentary and the user shouldn't plan their application around it to prefer one value over another.
> 
> This is simply not true, @bhalevy. And the code in Cassandra is the proof.

Proof for what? That there's an algorithm for tie breaking?
Yes, there is one, but what does the user buy by abusing it?

> We should fix the bug in our code and move on.

Of course we need to fix it.
But, with all due respect we should educate our customers to apply best practices.when using the product.  Sending a different value using an already used timestamp for a cell is calling for trouble. The derived wall-clock expuration time is determined by the coordinator and so there's an inherent race between parallel writes arriving from different coordinators and there is no good way to ensure determinstic serialization of such a write.

As I said, in this case, if the user is already providing a tiemstamp, and it issues a new value for a cell, then they need to dispatch a new timestamp for it to ensure it will override the previous value.  That's teally the essence of ordering of mutations.

So we better not just "move on", since this will come back to haunt us, even after fixing this bug, if the user will continue to do the above (assuming they do, should be double checked, but we have no other explanation for their symptoms so far).

> 
> > Retried inserts that use the same write timestamp should write the same value, and if there is a ttl to that data, the retry should adjust the remaining ttl USING TTL over CQL, such that the expiration time of the retried insert would be the same as the original one.
> > In particular, if the application wants to update a cell value, it must issue a larger timestamp for it.
> 
> The same here. Please, don't invent the restrictions that don't and should not exist. If you refer some other DB (not Scylla) that is not compatible with Cassandra - then you are probably right (I can't tell since I don't know which DB you are talking about). Regarding Scylla however this is plain incorrect - unless, of course, ScyllaDB decided to break the compatibility with Cassandra. As far as know such decision hasn't been made yet.

Please see my explanation above.
There are limitations to using server-based timestamps on a distributed system with uncoordinated clocks.
User-provided timestamps are there to help the application achieve better control over serializability of parallel writes, and so they should use it properly.
The rest is best effort, sorry, it is what it is.

> 
> The users _can_ update the value to the existing cell with the same timestamp and they _can_ rely on the fact that the resolution is _not_ only according to the timestamp as you claim here but a little bit more complex.

Let's try to be smart rather than right.
I agree the application _can_ do exactly what you said  based on the protocol, but as my analogy to C pointers, it is very leagal to dereference a null pointer, but it will crash your application, so normally you don't want to do it.

> 
> What needs to be done in addition to fixing the aforementioned bug is that resolution diagram must be also documented and become clear and official. After that it would no longer confuse our customers nor ScyllaDB engineers.

Agreed.  We definitely need to improve our documentation in this area and provide better advice to apication developers.

**Comment by vladzcloudius** [comment]
> Proof for what? That there's an algorithm for tie breaking?

Proof of the fact that it's much richer than what you claim it is.
Here is my analogy for you:
Most of the Porsche owners would never make it drive faster than 90mph - it doesn't mean it can't.
Some that would try (driving it fast) would kill themselves (because they are lousy drivers) - it still doesn't mean that one can never or should never drive it fast.

As long as there are clear rules how to operate the appliance/SW and a clear warnings what may happen if you operate it incorrectly the decision is and must be on a user. 

> Yes, there is one, but what does the user buy by abusing it?

Every user has its own reasons - it doesn't need to be of your or my concern.
A word "abusing" is describing your personal attitude to a specific API. 

> But, with all due respect we should educate our customers to apply best practices.when using the product. 

This is where you are wrong with all due respect. This is not the case that is covered by "best practices". There is nothing wrong in **not** following your recommendations above. It's your personal taste that **those** are "best practices" however somebody (like myself) would disagree with you.

> Sending a different value using an already used timestamp for a cell is calling for trouble. The derived wall-clock expuration time is determined by the coordinator and so there's an inherent race between parallel writes arriving from different coordinators and there is no good way to ensure determinstic serialization of such a write.

There is - you just make sure that you send your writes with a delay large enough to make sure that the second write is definitely done with a coordinator time larger than the previous one regardless on which coordinator it lands.

> As I said, in this case, if the user is already providing a tiemstamp, and it issues a new value for a cell, then they need to dispatch a new timestamp for it to ensure it will override the previous value. That's teally the essence of ordering of mutations.

Again, you assume you know any possible business logic of every possible user - you don't. There are many ways to ensure the ordering in Scylla and what you proposed is just one of them. There are others and users are free to choose what fits them best as long as rules are properly defined.

> So we better not just "move on", since this will come back to haunt us, even after fixing this bug, if the user will continue to do the above (assuming they do, should be double checked, but we have no other explanation for their symptoms so far).

Nothing is going to "haunt" us, @bhalevy. As long as we document the resolution logic users will be able to do good decisions on their own. No need to be paranoid about it.

> Please see my explanation above.
> There are limitations to using server-based timestamps on a distributed system with uncoordinated clocks.
> User-provided timestamps are there to help the application achieve better control over serializability of parallel writes, and so they should use it properly.
The rest is best effort, sorry, it is what it is.

What is "best effort"? Who's using anything improperly? Benny, please, stop it. All there is here is a bug in scylla. Nothing else!
So, please, let's concentrate on making sure Scylla behaves in a way compatible with Cassandra's logic and documenting it. 
Leave the rest to the user to decide. Trust me, you are not telling here anything our users are not aware of - definitely those advanced ones that would potentially hit this case. Some can give you and me a few lessons on how to serialize writes...

So, please, don't waste your precious time trying to "educate" them - instead let's invest our time in writing a proper documentation on the topic.

BTW, you can put all your concerns and advises there as "Notes" or "Important" section.

> Let's try to be smart rather than right.
> I agree the application can do exactly what you said based on the protocol, but as my analogy to C pointers, it is very leagal to dereference a null pointer, but it will crash your application, so normally you don't want to do it.

This analogy definitely doesn't apply here. The application (Scylla) not only *can* do what I said it will also behave correctly and consistently if used according to clear rules. And this is unlike what's going to happen if you would try to dereference a `null` pointer in C. See my analogy about cars above instead.

"Smart" here would be to write a clear documentation that would allow our users understand how our application works instead of inventing voodoo rules.

**Comment by bhalevy** [comment]
@vladzcloudius Qualifying relying on write timestamps as "voodoo" is just gaslighting. Let's take our discussion off line since this is going nowhere.

**Comment by tzach** [comment]
https://github.com/scylladb/scylladb/issues/14063

**Comment by nyh** [comment]
> @vladzcloudius Qualifying relying on write timestamps as "voodoo" is just gaslighting. Let's take our discussion off line since this is going nowhere.

@vladzcloudius I think you're also overstating the effectiveness of Benny's fix. It will help when the two same-timestamp writes happened more than one real second apart (so the "expiration times" are not the same). But it will not help when the two same-timestamp writes happened less than one real second apart, so the expiration times will be identical and can't be used to prevent "mixing" of the two writes. If we're talking about a specific user that (for a reason I still don't understand) sent two different writes at two very different times with the same timestamp, then indeed this fix will help. But it's not a magic bullet and won't help at all other cases of timestamp ties.

**Comment by bhalevy** [comment]
Note that the resolution algorithm changed significantly in https://github.com/apache/cassandra/commit/e225c88a65f2e8091f8ea6212c291416674882a1.
In particular, `resolveRegular` was changed to compare expiration before cell value.

Our implementation of `compare_atomic_cell_for_merge` should be compatible with Cassandra's `reconcile`.
I'm not sure about differences in reconciliation of counters.
In the scope of this issue, I'll only focus on regular cells, and compatibility with Cassandra's `resolveRegular`.

**Comment by tgrabiec** [comment]
On Fri, Jun 9, 2023 at 11:18 PM Vladislav Zolotarov <
***@***.***> wrote:

> Proof for what? That there's an algorithm for tie breaking?
>
> Proof of the fact that it's much richer than what you claim it is.
> Here is my analogy for you:
> Most of the Porsche owners would never make it drive faster than 90mph -
> it doesn't mean it can't.
> Some that would try (driving it fast) would kill themselves (because they
> are lousy drivers) - it still doesn't mean that one can never or should
> never drive it fast.
>
> As long as there are clear rules how to operate the appliance/SW and a
> clear warnings what may happen if you operate it incorrectly the decision
> is and must be on a user.
>
> Yes, there is one, but what does the user buy by abusing it?
>
> Every user has its own reasons - it doesn't need to be of your or my
> concern.
> A word "abusing" is describing your personal attitude to a specific API.
>
> But, with all due respect we should educate our customers to apply best
> practices.when using the product.
>
> This is where you are wrong with all due respect. This is not the case
> that is covered by "best practices". There is nothing wrong in *not*
> following your recommendations above. It's your personal taste that
> *those* are "best practices" however somebody (like myself) would
> disagree with you.
>
> Sending a different value using an already used timestamp for a cell is
> calling for trouble. The derived wall-clock expuration time is determined
> by the coordinator and so there's an inherent race between parallel writes
> arriving from different coordinators and there is no good way to ensure
> determinstic serialization of such a write.
>
> There is - you just make sure that you send your writes with a delay large
> enough to make sure that the second write is definitely done with a
> coordinator time larger than the previous one regardless on which
> coordinator it lands.
>
> As I said, in this case, if the user is already providing a tiemstamp, and
> it issues a new value for a cell, then they need to dispatch a new
> timestamp for it to ensure it will override the previous value. That's
> teally the essence of ordering of mutations.
>
> Again, you assume you know any possible business logic of every possible
> user - you don't. There are many ways to ensure the ordering in Scylla and
> what you proposed is just one of them. There are others and users are free
> to choose what fits them best as long as rules are properly defined.
>
> So we better not just "move on", since this will come back to haunt us,
> even after fixing this bug, if the user will continue to do the above
> (assuming they do, should be double checked, but we have no other
> explanation for their symptoms so far).
>
> Nothing is going to "haunt" us, @bhalevy <https://github.com/bhalevy>. As
> long as we document the resolution logic users will be able to do good
> decisions on their own. No need to be paranoid about it.
>

The expiration clock has 1 second resolution. What if the retry happens
within the same second? In that case we're back to conflict resolution by
value and cells will get mixed up from different updates. No guarantee that
the more recent value wins (largest wins).

**Comment by vladzcloudius** [comment]
> The expiration clock has 1 second resolution. What if the retry happens
within the same second? In that case we're back to conflict resolution by
value and cells will get mixed up from different updates. No guarantee that
the more recent value wins (largest wins).

Good API documentation is a way to avoid the confusion, @tgrabiec.
The absence of it (the current state) is way to a confusion.
This discussion goes in circles for quite some time. 
There is nothing to discuss here (for me at least): 
* Benny's fix is in works and it addresses the issue in question (the discrepancy between Scylla's and Cassandra's behavior) .
* Tzach has created a Doc issue to have a Documentation section that makes it super clear how the resolution works including the resolution of corresponding clocks.

@bhalevy You know I never refuse an off-line discussion. ;)

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to all 5.x branches as well as 2021.1 + 2022.1

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint ping
We have a customer waiting for this.

**Comment by denesb** [comment]
Backport is not clean. @bhalevy please prepare backport PRs.

**Comment by DoronArazii** [comment]
@bhalevy thanks, we need another 2 at the other repo for 2021.1 + 2022.1

**Comment by bhalevy** [comment]
> @bhalevy thanks, we need another 2 at the other repo for 2021.1 + 2022.1

I submitted PRs for 5.1 and 5.2 in addition to 5.3
Do we need one for 5.0 as well?

**Comment by DoronArazii** [comment]
> > @bhalevy thanks, we need another 2 at the other repo for 2021.1 + 2022.1
> 
> I submitted PRs for 5.1 and 5.2 in addition to 5.3 Do we need one for 5.0 as well?

5.0 is EOL
We need an enterprise PRs for 2021.1 & 2022.1

**Comment by DoronArazii** [comment]
Backported.
Removing the labels.
