### ISSUE TITLE
RFC: Streaming may be inefficient and slow due to a static division of the streaming plan into 10 chunks

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#14191]
*Installation details*
HEAD: 4592bbe18207e9b25d485ba37103de9a35574a1d

*Description*
Streaming work of every streaming plan is processed in 10 chunks on a node level. Meaning that shards will not move to the next chunk work till all shards on the node finished the work in the context of a previous chunk:

https://github.com/scylladb/scylladb/blob/master/dht/range_streamer.cc#L267

And the thing is that it will always be that some shards are going to finish faster than others and then wait for slower ones to catch up.

And the more the difference in the amount of data to stream (e.g. if there are large partitions or something else that is harder to process like large cells) the more time those fast shard would sit idle do nothing.

Here is screenshot that demonstrates the phenomena: this is a per-shard view on a node that is being decommissioned where I emphasized two distinctive time frames:
* Fast: where all shards are streaming
* Slow: where only two are streaming because others have finished their streaming

![image](https://github.com/scylladb/scylladb/assets/6103981/5ccaf9c5-4a23-4225-96bc-75fb34275b0a)

And the funny thing is that it may be other shards that would be "slow" in the next chunk.
Hence if shards would stream not in chunks but "the whole thing" it would make the whole streaming finish much faster because shards would waste much less time in the "waiting" state.

There are multiple ways to make things faster in a simple easy change: e.g. make the number of chunks configurable and live-updatable. And possibly set the default to 1.

A more involving change would require us recall why this chunking logic is there to begin with. And this is in order to be more efficient in streaming errors handling: if there are any we are re-streaming the whole chunk. So, having to re-stream only 1/10 is obviously much better than the whole thing.

So, instead of resolving the errors issue by chopping the streaming plan we could be less lazy and actually store the current streaming progress (since we atomic streaming unit is a token range) in some `system` table, and do it for every shard independently. And since AFAIK the steaming plan progresses over token ranges monotonously this storing can be coalesced too if we see that updating the system table for every next range is too heavy.

This would not only resolve "chunking" issue and would allow each shard push all the way till the completion as fast as possible in the presence of possible errors and node restarts, but will also open a huge range of opportunities for additional APIs, e.g.:
* Pausing/resuming streaming.
* Canceling streaming.
* Progress tracking.

**Comment by vladzcloudius** [comment]
FYI @bhalevy @asias

**Comment by denesb** [comment]
Isn't streaming in the same awkward spot as schema-changes: we reluctant to make changes (and backport them) as we already have (are working on) an improved version (RBNO in this case)?
The question to ask: does it make sense to implement the above suggestion in current master? If not, is it worth it to implement something this complex just for an older version?

**Comment by DoronArazii** [comment]
@asias which versions should have the fix?

**Comment by mykaul** [comment]
> @asias which versions should have the fix?

@DoronArazii - see https://github.com/scylladb/scylladb/issues/14191#issuecomment-1588745091 - at the very least 2022.2.x, but then we'll see what else, depending on cadenece and complexity to backport.

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backports to all the active 5.x branches.

**Comment by denesb** [comment]
The fix (dad5caf1417362ed136e19db9f21dc6b3ebdbd90) looks like an improvement, not a bugfix to me. But this is open to interpretation. @avikivity do you think we should backport this to OSS too, or just enterprise?

**Comment by DoronArazii** [comment]
@avikivity please take a decision.

**Comment by DoronArazii** [comment]
@avikivity ping, we need backports to 2022.2 and above.

**Comment by mykaul** [comment]
> @avikivity ping, we need backports to 2022.2 and above.

@avikivity - ping - do we wish to backport this?

**Comment by nyh** [comment]
Note that Avi sent PR https://github.com/scylladb/scylladb/pull/15261 to rename the option added in this fix, so if the new configuration option is backported, its rename should be too.

**Comment by nyh** [comment]
Note that Avi sent PR https://github.com/scylladb/scylladb/pull/15261 to rename the option added in this fix, so if the new configuration option is backported, its rename should be too.

**Comment by mykaul** [comment]
> > @avikivity ping, we need backports to 2022.2 and above.
> 
> @avikivity - ping - do we wish to backport this?

@avikivity - re-ping

**Comment by raphaelsc** [comment]
long term is RBNO, long long term, tablets. not saying we shouldn't expose a knob to help field, but perhaps the effort should stop there.

**Comment by avikivity** [comment]
Not backporting since this is an enhancement and also the word "may".
