### ISSUE TITLE
Implement local query processor

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#14202]
Cassandra was designed as an eventual consistent network-first database. In the boot order the networking services would get started first, and the local persistent state would follow. Specifically:
* in order to start we need to know the cluster features, which are learned from the network
* there is no way to  run local queries, the query processor depends on storage proxy, which depends on messaging.

With raft and strongly consistent topology changes we have reversed the boot order when we first need to read and possibly modify the local state and only then reach out to network. This is key to boot safety, e.g. predictable upgrade/downgrade, when a new version and the features we support are known before we try to reach out to the rest of the nodes in the clusters.

We have switched to raft based topology, features and schema without doing the due diligence on reversing the code dependencies and changing the boot order.

This creates ugly anomalies with boot loops, when we first start services and later "finish" initializing them with persisted information.

Specifically, we need to know the state of the system keyspace *before* starting Raft Group0. It includes locally persisted features, local host id, last persisted state of topology on this node. Without it, we have to provide cludges in patches like https://github.com/scylladb/scylladb/pull/13850/commits when local host id is **optional** in messaging service and is set later. Another case is when the direct failure detector (a networking service) needlessly pings self over network because it is unaware of the local host id and can't obviously know who is self and thus set it as alive node without extra pings. 

In tablets and s3 storage we suffer similarly from this boot order dependency.

We have started on the effort of implementing a local query  processor but this effort fell short of the query processor itself, only touched the storage proxy and a few related classes. We need to finish this effort.

**Comment by denesb** [comment]
> Isn't @denesb working on this currently?

I did attempt to fix this with https://github.com/scylladb/scylladb/pull/13983, because it blocks https://github.com/scylladb/scylladb/pull/13067, but my approach was rejected so I'd have to start all over with a different approach. See https://github.com/scylladb/scylladb/pull/13983 for more details on why my approach was rejected and what was proposed instead, I don't want to repeat it here.

**Comment by kbr-scylla** [comment]
I'll take a stab at this then.

**Comment by kbr-scylla** [comment]
https://github.com/kbr-scylla/scylladb/commits/qp-2-init-new

For now I sent a PR that implements a "local" `storage_proxy` (actually it splits `storage_proxy` init to two phases).

**Comment by kbr-scylla** [comment]
Although https://github.com/scylladb/scylladb/pull/14256 addresses literally the title of this issue, the work is not done if we consider the full contents of the issue - we still need to fix `system_keyspace` initialization, making it available early too.

This is what my last PR does:
https://github.com/scylladb/scylladb/pull/14285

**Comment by kbr-scylla** [comment]
https://github.com/scylladb/scylladb/pull/14285 was merged.
Now this problem:
> Without it, we have to provide cludges in patches like https://github.com/scylladb/scylladb/pull/13850/commits when local host id is optional in messaging service and is set later.

doesn't exist anymore; see new version of the banning nodes PR:
https://github.com/scylladb/scylladb/pull/13850/commits/87f65d01b87a12458bbf499bb0965c8d3f8a6fab

**Comment by avikivity** [comment]
Not a bug, not backporting.
