### ISSUE TITLE
Feature Request: add scrub in segregation mode to scylla sstable tool

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14203]
Currently, `scylla sstable` tool can validate sstables, but it can't fix them if any inconsistencies are found.
Scylla, on the other hand, has scrub compaction in segregation mode that can produce a sequence of valid sstables from an in put sstable that has out-of-order partitions and/or rows.

It is possible that sstables are found as corrupt when uploaded using `nodetool refresh`.
In this case we have no simple way to salvage whatever we can from them, and such an offline tool could be used
to extract the valid parts of such sstables and then to ingest those using the upload procedure.

**Comment by bhalevy** [comment]
Cc @tzach @mykaul

**Comment by denesb** [comment]
Feature, so won't be backported.

**Comment by avikivity** [comment]
@mykaul why did you add the backport label? see @denesb comment.

**Comment by mykaul** [comment]
> @mykaul why did you add the backport label? see @denesb comment.

For Enterprise. OK - it was taken care of.
