### ISSUE TITLE
Memtables utilization is very poor

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#14212]
As part of some debug activity I tested two specific patterns of load, it seams that for both of them the utilization of memtables was very poor. What I attempted to do was to fill the nodes memtables almost up until the dirty memory manger threshold is
reached (this last detail is just how I got to view the metrics and doesn't have specific relevance to the issue).
When I tried to do it with some guess of the overhead on the memtable (started with 20%) I found that the overhead is
a lot larger and is 120%-280%.
Setup:
A cluster of 1 node with --smp 2 and --memory 2G

I tried two different populations on the cluster/node, the common for both of them is that they didn't trigger a flush (as I expected):
First I tried:
`ccm stress -- write no-warmup cl=QUORUM n=35000 -schema 'replication(factor=1)' -mode cql3 native -rate threads=300 -col 'size=FIXED(128) n=FIXED(8)' -pop seq=1..40000` - rows with total of 1024 bytes of data (+10 bytes of partition key)
When sampling the unspooled memory after the commend:
`curl "127.0.0.1:9180/metrics" | grep memory_regular | grep shard` gave me:
```
scylla_memory_regular_dirty_bytes{shard="0"} 69337088.000000
scylla_memory_regular_dirty_bytes{shard="1"} 69468160.000000
scylla_memory_regular_unspooled_dirty_bytes{shard="0"} 69337088.000000
scylla_memory_regular_unspooled_dirty_bytes{shard="1"} 69468160.000000
```
computations:
There is ~35MB of data that was written (35K rows).
The memtables occupy `69337088 + 69468160 = ~132MB` 
This is and overhead of ~100MB which is ~280%
Then to rule out that this is about alignment to 4K pages I tried:
`ccm stress -- write no-warmup cl=QUORUM n=10000 -schema 'replication(factor=1)' -mode cql3 native -rate threads=300 -col 'size=FIXED(512) n=FIXED(7)' -pop seq=1..40000` - 10000 rows, one per partition with 7 columns of 512 bytes each + partition key of 10 bytes, which are ~3.6K 
I got:
```
scylla_memory_regular_dirty_bytes{shard="0"} 45219840.000000
scylla_memory_regular_dirty_bytes{shard="1"} 45613056.000000
scylla_memory_regular_unspooled_dirty_bytes{shard="0"} 45219840.000000
scylla_memory_regular_unspooled_dirty_bytes{shard="1"} 45613056.000000

```
computations:
There is around 36MB of data (10 rows)
The memtables occupy: `45219840 + 45613056 = ~86MB `
This is an overhead of 50MB which is ~130% overhead.

The schema created by the stress tool is:
```
cqlsh> DESCRIBE keyspace1.standard1 ;

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob,
    "C5" blob,
    "C6" blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

It looks very high of an overhead for the memtables to me and I think it is worth looking into.
I labeled it under performance because the large overhead will cause more frequent flushes which eventually affects performance. Also it causes more memory pressure.

All of this of course assuming that I got this right :slightly_smiling_face:

**Comment by eliransin** [comment]
@michoecho, @bhalevy thought you might find this interesting.

**Comment by eliransin** [comment]
I have updated the opening section of this issue to also include the dirty bytes and not only unspooled bytes. And they are very close so it doesn't seem like holes in the lsa.

**Comment by tgrabiec** [comment]
It's probably due to sparse LSA segments: https://github.com/scylladb/scylladb/issues/1329

We have memory_footprint_test which can be used to estimate the essential overhead (the live part).

**Comment by michoecho** [comment]
There are two factors here:

1. The metrics you are looking at (scylla_memory_regular_dirty_bytes, scylla_memory_regular_unspooled_dirty_bytes) count the total memory usage of LSA (including) holes, not the actual usage. If you look at the actual usage, you will see that almost half of the memtable space in this test is holes:
```
scylla_lsa_total_space_bytes{shard="0"} 73400320.000000
scylla_lsa_total_space_bytes{shard="1"} 70516736.000000
scylla_lsa_used_space_bytes{shard="0"} 33188159.000000
scylla_lsa_used_space_bytes{shard="1"} 33282230.000000
scylla_lsa_occupancy{shard="0"} 45.215279
scylla_lsa_occupancy{shard="1"} 47.197636
```
So the actual memory usage (excluding LSA holes) per partition is not ~3800 B, but ~1900 B.

This is mostly benign. But not quite, because flush control is based on the `total` metrics, not the `used` metrics, so this sparsity might indeed cause (arbitrarily) small sstables to be written.

2. Each partition in memtables has about 200 bytes of overhead, each row has about 300 bytes of overhead, and each cell has about 50 bytes of overhead, due to implementation details. Therefore your partitions — each with 1 row of 8 columns — have about (200 B + 1 * 300 B + 8 * 50 B) = 900 B of overhead each.

This explains why the partitions take ~1900 B even though they only have ~1000 B of data.

**Comment by michoecho** [comment]
The 56 B overhead per cell (8 for the pointer to blob_storage in managed_bytes, 8 for the size in managed_bytes, 8 for the backpointer to managed_bytes in blob_storage, 8 for the size in blob_storage, 8 for the successor pointer in blob_storage, 8 bytes for the cell timestamp, 1 byte for cell flags, plus a few bytes for alignment) is quite sad in particular.

It could be reduced to ~ 8 B (just the timestamp + some size metadata) if we stored our rows more efficiently (i.e. without keeping each cell in a separate allocation).
