### ISSUE TITLE
Server restart hangs with topology on raft enabled

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#14217]
The restarted server hangs in `group0_service.setup_group0_if_exist()`, which waits for snapshot loading, which waits for `storage_service::topology_state_load()`, which waits for IP mapping for servers mentioned in the topology, and produces logs like this:
```
WARN  2023-06-12 15:45:21,369 [shard 0] storage_service - (rate limiting dropped 196 similar messages) raft topology: cannot map c94ae68f-869d-4727-8b2f-d40814e395f0 to ip, retrying.
```

This is a regression after f26179cd27a1948386f9d86cb5d3e89f8c5224ad, where group0 server is initialized before the IP mapping in the gossiper is restored from system.peers.

**Comment by avikivity** [comment]
experimental code only, not backporting.
