### ISSUE TITLE
Too many translation units depend on the wasmtime_bindings.hh generated file

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#14224]
As of c3d91f5190, 206 translation units depend on the `rust/wasmtime_bindings.hh` file, even though it's only actually used in a small part of the project. To improve compilation, we should minimize unnecessary includes, especially because it's a file that needs to be generated before any work is done on the dependent units

**Comment by avikivity** [comment]
Not a bug, not backporting.
