### ISSUE TITLE
Documentation: update perftune.py documentation

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#14233]
*Installation details*
Scylla version: 5.1

*Description*
After https://github.com/scylladb/scylladb/pull/14092 perftune.py is going to generate perftune.yaml in a very different way:
* `irq_cpu_mask` is going to be used instead of `mode`.
* More than a single physical core is going to be used for IRQ handling for large machines.

More detailed description can be found in description of these patches:

* https://github.com/scylladb/seastar/commit/8e92a32d861748d71c55d6f4023cb5557d238da4
* https://github.com/scylladb/seastar/commit/16290aa9d0472239b5880cd067d4d17d00b44b4b

And in the `perftune.py --help`.

We need to upgrade our perftune.py related pages correspondingly.
In particular: 
* https://docs.scylladb.com/stable/kb/perftune-modes-sync.html
* https://docs.scylladb.com/stable/operating-scylla/admin-tools/perftune.html

**Comment by annastuchlik** [comment]
[Info](https://github.com/scylladb/scylla-docs/issues/2467#issuecomment-1653790893) from @vladzcloudius:

> https://opensource.docs.scylladb.com/stable/operating-scylla/admin-tools/perftune.html is outdated and incomplete.
> 
> More specifically:
> 
> * `mode` became outdated. Today we use a generic `irq_cpu_mask` instead.
> * There is no explanation about `tuners` (set by the `--tune` parameter). Without it people may not realize for example that passing `--tune-clock true` is not going to tune anything unless `--tune system` is provided as well.
>   
>   * Currently supported tuners are:
>     
>     * net: will tweak networking
>     * disks: will tweak disks
>     * system: will tweak general system related things like a clock source
> * Some examples may be in order. I believe we worked on some examples lately - you can use them here as well.

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
