### ISSUE TITLE
stalls when formatting compaction input list

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14247]

**Comment by raphaelsc** [comment]
Fixed by 5544d12f18e9109cdaab5cf384bf477c6ae0a4d9.

**Comment by mykaul** [comment]
I don't think it's a regression, but it does seem to merit a backport.

**Comment by raphaelsc** [comment]
> I don't think it's a regression, but it does seem to merit a backport.

agreed. it's not a mere performance issue, quadratic behaviors that translate into stalls are bugs.

**Comment by raphaelsc** [comment]
also the fix is simple enough that the benefits outweigh the risks, if any here.

**Comment by mykaul** [comment]
@raphaelsc - do we have backports ready/done ? Do we have issues to track them?

**Comment by bhalevy** [comment]
Isn't this a duplicate of https://github.com/scylladb/scylladb/issues/14071?

**Comment by raphaelsc** [comment]
> Isn't this a duplicate of #14071?

yes. closing this one in favor of that one

**Comment by avikivity** [comment]
Already backported via #14071.
