### ISSUE TITLE
scylla-fstrim.timer is enabled but not started 

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylladb#14249]
### Installation details
Scylla version checked:  2021.1.12 
Scylla version affected: Probably all of them

### Problem spotted
According to https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_fstrim_setup, the service is not started by this script (and none of the remaining ones).

### Solution
After line: https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_fstrim_setup#L20
Add:
```
systemd_unit('scylla-fstrim.timer').start()
```

**Comment by ebenzecri** [comment]
FYI @vladzcloudius @tarzanek

**Comment by ebenzecri** [comment]
@syuu1228 Could you please take a look at this? Thanks!

**Comment by vladzcloudius** [comment]
cc @mykaul, please, prioritize high! This is a very dangerous issue since today `scylla-fstrim.timer` is not going to run till after the next VM reboot!

And we have this service (timer) for a very good reason.

**Comment by vladzcloudius** [comment]
cc @DoronArazii @tomer-sandler

**Comment by mykaul** [comment]
> Scylla version affected: Probably all of them

This is unlikely, as I think in newer versions we've stopped using that service and moved to online discard (via the mount option) ?

**Comment by mykaul** [comment]
> cc @mykaul, please, prioritize high! This is a very dangerous issue since today `scylla-fstrim.timer` is not going to run till after the next VM reboot!

I'm unsure why it's very dangerous.

> 
> And we have this service (timer) for a very good reason.

I was under the impression it was not a good idea and we've moved to online discard?

**Comment by vladzcloudius** [comment]
> > Scylla version affected: Probably all of them
> 
> This is unlikely, as I think in newer versions we've stopped using that service and moved to online discard (via the mount option) ?

Incorrect, @mykaul this is optional. The user can choose which option to use and a periodic `fstrim` is still available.

**Comment by vladzcloudius** [comment]
> > cc @mykaul, please, prioritize high! This is a very dangerous issue since today `scylla-fstrim.timer` is not going to run till after the next VM reboot!
> 
> I'm unsure why it's very dangerous.

Because if you don't run `fstrim` periodically this can cause a significant performance degradation.

> 
> > And we have this service (timer) for a very good reason.
> 
> I was under the impression it was not a good idea and we've moved to online discard? ([a19d00e](https://github.com/scylladb/scylladb/commit/a19d00ef9b8b50ce520bb2cfbf5bc00b30de5cda) )

`fstrim` is still a much better and robust option than `discard`: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems

![image](https://github.com/scylladb/scylladb/assets/6103981/7e4a3cb8-352b-4513-ab58-b5646130f44e)


We don't recommend our friends to use `discard`. ;)

**Comment by mykaul** [comment]
> > > cc @mykaul, please, prioritize high! This is a very dangerous issue since today `scylla-fstrim.timer` is not going to run till after the next VM reboot!
> > 
> > 
> > I'm unsure why it's very dangerous.
> 
> Because if you don't run `fstrim` periodically this can cause a significant performance degradation.

OK, so there's no danger (read: data loss, corruption, unavailability) here. Just performance degradation.

> 
> > > And we have this service (timer) for a very good reason.
> > 
> > 
> > I was under the impression it was not a good idea and we've moved to online discard? ([a19d00e](https://github.com/scylladb/scylladb/commit/a19d00ef9b8b50ce520bb2cfbf5bc00b30de5cda) )
> 
> `fstrim` is still a much better and robust option than `discard`: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems

This document is >5 years old. It was written in the days where some SSDs and storages still exhibited hiccups during garbage collection / trimming. This is (1) not the case today - mostly and (2) using online discard smooths out this behavior. So our recommendation should actually be move to online discard.

**Comment by vladzcloudius** [comment]
> > > > cc @mykaul, please, prioritize high! This is a very dangerous issue since today `scylla-fstrim.timer` is not going to run till after the next VM reboot!
> > > 
> > > 
> > > I'm unsure why it's very dangerous.
> > 
> > 
> > Because if you don't run `fstrim` periodically this can cause a significant performance degradation.
> 
> OK, so there's no danger (read: data loss, corruption, unavailability) here. Just performance degradation.

Performance degradation is dangerous enough - not less dangerous than complete unavailability for very many use cases.

> 
> > > > And we have this service (timer) for a very good reason.
> > > 
> > > 
> > > I was under the impression it was not a good idea and we've moved to online discard? ([a19d00e](https://github.com/scylladb/scylladb/commit/a19d00ef9b8b50ce520bb2cfbf5bc00b30de5cda) )
> > 
> > 
> > `fstrim` is still a much better and robust option than `discard`: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems
> 
> This document is >5 years old. 

Are you sure? Based on a timestamp in the example on this page it's pretty fresh:

![image](https://github.com/scylladb/scylladb/assets/6103981/bf76d6f0-6509-47e8-9852-44cbd44ae528)


> It was written in the days where some SSDs and storages still exhibited hiccups during garbage collection / trimming. This is (1) not the case today - mostly

Exactly. Hence no much reason to move away from `fstrim`.

> and (2) using online discard smooths out this behavior. So our recommendation should actually be move to online discard.

I couldn't find any proof/document/benchmark clearly confirming your claim that discard is **better** than fstrim.
Do you have one? If, yes, please, share.

My personal experience with `discard` was rather negative.

On top of that, what our recommendations need to be is totally irrelevant to matter of this GH issue. The script in question is only called when the customer **chose** to enable `fstrim`. However the script has a bug - it enables the service but doesn't start it as expected.

So, let's just fix it and move on.

**Comment by DoronArazii** [comment]
Backported to all 5.x

Removing label.

**Comment by mykaul** [comment]
This makes me wonder if it's the path we wish to take - @avikivity and I just discussed if we need this, if we have online discard for our mount points.

**Comment by vladzcloudius** [comment]
> This makes me wonder if it's the path we wish to take - @avikivity and I just discussed if we need this, if we have online discard for our mount points.

@mykaul do we have a reason to move away from `fstrim`? Do we have a reproducer of any issue that it causes with kernel that people use **today**?

**Comment by mykaul** [comment]
> > This makes me wonder if it's the path we wish to take - @avikivity and I just discussed if we need this, if we have online discard for our mount points.
> 
> @mykaul do we have a reason to move away from `fstrim`? Do we have a reproducer of any issue that it causes with kernel that people use **today**?

First of all, I'm not sure it makes sense to use with online trimming. It's probably useless, but it will do some work, that we may or may not wish to have. For example, by default, it'll discard every block it can (minimum-size is 0).
We need to decide on a policy. I believe it'll be good to do a fstrim on specific events (node reboot, Scylla service restart) and keep online trimming.

**Comment by avikivity** [comment]
With online trimming there's no need for fstrim.

**Comment by vladzcloudius** [comment]
> With online trimming there's no need for fstrim.

I agree with Avi. Only one or another needs to be used at the same time. Using both is IMO unnecessary overkill. 

There were some implementation differences mentioned on different threads but AFAIR `discard` "cleans more" than `fstrim` hence running the later when `discard` is enabled will likely do very little actual work.
But this is, of course, provided I didn't miss something.
