### ISSUE TITLE
Minio server start race

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#14269]
When minio starts and opens its port it still may not be fully ready to serve `mc` command configuration requests.
Need to add retries if first `mc` command fails

**Comment by xemul** [comment]
Seen in #13896 and #14260
Also refs #13901

**Comment by DoronArazii** [comment]
Can you send a fix for it?

**Comment by tchaikov** [comment]
hi @xemul are you working on this issue? if not, i can take it.

**Comment by xemul** [comment]
Not yet, so the help is appreciated

**Comment by tchaikov** [comment]
silly me i referenced an unrelated issue in https://github.com/scylladb/scylladb/pull/14517.

@xemul could you help close this issue.

**Comment by xemul** [comment]
dfff5f2f2e368a111b96fe940633f6f98dc27588
