### ISSUE TITLE
Scylla allows me to change the password of a superuser even if I'm not a superuser

### ISSUE THREAD

**Issue by igorribeiroduarte** [scylladb/scylladb#14277]
*Installation details*

Scylla version (or git commit hash): 5.2.0-0.20230427.429b696bbc1b

*Description*

If I grant `ALTER` on `ALL ROLES` to an ordinary user, this user is able to change the password for a superuser.
Someone might say that if I granted `ALTER` on `ALL ROLES` I should indeed be allowed to alter even a superuser,
but if you look into our [documentation](https://docs.scylladb.com/stable/operating-scylla/security/authorization.html#alter-role) on this matter, you'll see that a non superuser role is not allowed to alter the SUPERUSER status of another role (with the intention of protecting superuser from normal users) and the issue described here allows any user with the mentioned permissions to work around this limitation by first changing the password of the superuser and then doing anything with this superuser.

*How to reproduce*
* Create a superuser -> `create role admin with password = '1' and SUPERUSER=true and login=true;`
* Create a normal user -> `create role customer_user with login=true and password='1';`
* Grant alter on all roles to the normal user -> `grant alter on all roles to customer_user;`
* Login with the normal user and change the superuser's password: `cqlsh -u customer_user -p 1;  alter role admin with password='2';`

CC: @vladzcloudius @tarzanek @ebenzecri @pdbossman

**Comment by vladzcloudius** [comment]
cc @DoronArazii @mykaul @tomer-sandler

**Comment by igorribeiroduarte** [comment]
This together with https://github.com/scylladb/scylladb/issues/14279 won't allow me to give `ALTER` permissions to a user without also giving permissions for this user to change superusers

**Comment by DoronArazii** [comment]
@eliransin please assign someone

**Comment by ptrsmrn** [comment]
@KrzaQ please check how Casandra and PostgreSQL handle it and write a brief summary here. Then we'll let @kostja decide on the next step.

**Comment by KrzaQ** [comment]
PostgreSQL doesn't seem to have an exact alternative - you can grant alter on a specific role, but if you do it on an admin role, then the intent is pretty clear.

Cassandra reproduces this issue fully.

**Comment by KrzaQ** [comment]
Behavior matches Cassandra - we're treating it as not a bug.

I'll add a test to verify this behavior in cql or cql-pytest.

**Comment by ManjotS** [comment]
IMHO reimplementing a security flaw because Cassandra has it could be less than ideal.

**Comment by kostja** [comment]
@igorribeiroduarte  In order to address the problem in line with discretionary access control model concepts and behaviour of most of the DBMS vendors, we'd need to split users and roles. Roles in DBMS are bags of grants and not authentication/authorization objects. A password is a property of a user, and can not be set for a role. Roles can be granted in any direction, as long as there are no loops - e.g. role A can be granted to role B, and role C can be granted to role B, this doesn't make neither A nor C a parent of B any more than one node in a directed acyclic graph is a parent of the other node. 

@tzach @avikivity  if you believe it's important then we could transform Scylla authentication/authorization and roles closer to ANSI SQL and PostgreSQL model, otherwise I believe fixing this is just transitioning one broken implementation to another, but this time not only broken, but also an incompatible one.

**Comment by kostja** [comment]
@igorribeiroduarte please keep in mind that there is a viable workaround/solution for the issue: the system administrator can always log in with AllowAllAuthenticator and reset the password back.

**Comment by tzach** [comment]
We inherited the role/user from Apache Cassandra CQL.
Moving away from it means we lose CQL compatability.

**Comment by kostja** [comment]
Tests are in, closing the issue - please reopen or open a new one if the behavior change originally requested here is desirable.

**Comment by vladzcloudius** [comment]
> @igorribeiroduarte please keep in mind that there is a viable workaround/solution for the issue: the system administrator can always log in with AllowAllAuthenticator and reset the password back.

How is this a workaround if that user (with `ALTER on ALL ROLES`)  can change it back right after that, @kostja?
We need something that would allow **preventing** it.

And note that to set `AllowAllAuthenticator` requires a service restart while the issue described here can be reproduced by a user that only needs permissions above and access to CQL.
