### ISSUE TITLE
Increase the default priority class shares to 200 (on stable branches)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#14281]
Follow up of https://github.com/scylladb/scylladb/issues/13753#issuecomment-1592846141

**Comment by michoecho** [comment]
Note: doesn't apply to current master (after 66e43912d6f0d82ce465b462d44a42ff76c41925), only to stable branches.

**Comment by bhalevy** [comment]
@michoecho can you please submit a PR for 5.3 fixing this issue and we'll backport it from there?

**Comment by michoecho** [comment]
> @michoecho can you please submit a PR for 5.3 fixing this issue and we'll backport it from there?

It's a seastar-side change, so it will be fixed in Scylla when https://github.com/scylladb/seastar/pull/1706 is applied to branch 5.3 in https://github.com/scylladb/scylla-seastar, and branch 5.3 in Scylla is updated to use that updated Seastar branch.

(And ditto for 5.2/5.1).
