### ISSUE TITLE
Off-strategy compaction leaks input sstables into "cleanup set"

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14304]
Today, compaction manager has a cleanup set marking all sstables requiring cleanup. Maintenance sstables can be included in this set. Turns out off-strategy compaction is not removing input sstables on completion, so they are leaked, causing additional write amplification as cleanup may pick them afterwards, and space issues as the space of those sstables aren't released till next cleanup happens.

**Comment by raphaelsc** [comment]
@bhalevy assigned this to you, but I can pick it up if you need help.

**Comment by bhalevy** [comment]
> @bhalevy assigned this to you, but I can pick it up if you need help.

thanks. looks like you got a firm handle on this issue, so feel free to send a fix

**Comment by raphaelsc** [comment]
> > @bhalevy assigned this to you, but I can pick it up if you need help.
> 
> thanks. looks like you got a firm handle on this issue, so feel free to send a fix

Roger that.

**Comment by bhalevy** [comment]
`sstables_requiring_cleanup` exists only in master (and 5.3 that was canceled), but not in 5.3, so no backport is required.
