### ISSUE TITLE
repair failing during bootstrap for no apparent reason, claiming a peer is dead (but it was marked alive and NORMAL)

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14301]
Observed during CI run a few days ago, I also recall seeing it on next earlier but didn't create an issue the first time.
This was during initial cluster boot before a test started in `test.py` topology suite.
Two nodes booted successfully.
First node: [scylla-243.log](https://github.com/scylladb/scylladb/files/11789504/scylla-243.log)
Second node: [scylla-244.log](https://github.com/scylladb/scylladb/files/11789505/scylla-244.log)
Then the third node failed: [scylla-246.log](https://github.com/scylladb/scylladb/files/11789510/scylla-246.log)

The error doesn't give too many details:
```
ERROR 2023-06-18 15:33:06,345 [shard 0] init - Startup failed: std::runtime_error ({shard 1: std::runtime_error (repair[af4efac1-cbe0-446c-9f47-85f7ee753f37]: 27 out of 49 ranges failed, keyspace=system_distributed_everywhere, tables={cdc_generation_descriptions_v2}, repair_reason=bootstrap, nodes_down_during_repair={127.172.235.29}, aborted_by_user=false)})
```
however there's a clue: `nodes_down_during_repair={127.172.235.29}`

There were warnings since the beginning of repair:
```
WARN  2023-06-18 15:32:54,553 [shard 1] repair - repair[af4efac1-cbe0-446c-9f47-85f7ee753f37]: Repair 1 out of 49 ranges, keyspace=system_distributed_everywhere, table={cdc_generation_descriptions_v2}, range=(8604444975001353367,+inf), peers={127.172.235.29, 127.172.235.30}, live_peers={127.172.235.30}, status=partial
```
we can see that `live_peers` does not include `.29`: `{127.172.235.29, 127.172.235.30}, live_peers={127.172.235.30}`
and then
```
ERROR 2023-06-18 15:32:54,934 [shard 0] storage_service - bootstrap[20a8c62e-f9af-499d-9a36-5abb652f6f53]: Operation failed, sync_nodes={127.172.235.30, 127.172.235.29, 127.172.235.41}: std::runtime_error ({shard 1: std::runtime_error (repair[af4efac1-cbe0-446c-9f47-85f7ee753f37]: 27 out of 49 ranges failed, keyspace=system_distributed_everywhere, tables={cdc_generation_descriptions_v2}, repair_reason=bootstrap, nodes_down_during_repair={127.172.235.29}, aborted_by_user=false)})
```

Hmm... it looks like the errors happened only on shard 1? This could be a clue.

Other than that, we see that node `.29` was marked as UP by gossiper earlier:
```
INFO  2023-06-18 15:32:54,322 [shard 0] gossip - InetAddress 127.172.235.29 is now UP, status = NORMAL
```
we don't see a DOWN notification later.

NORMAL state handlers have finished:
```
INFO  2023-06-18 15:32:54,549 [shard 0] storage_service - Started waiting for normal state handler for nodes {127.172.235.29, 127.172.235.30}
INFO  2023-06-18 15:32:54,549 [shard 0] storage_service - Finished waiting for normal state handler for nodes {127.172.235.29, 127.172.235.30}
```

and the CDC generation write, which is done with CL=ALL, was successful.
```
INFO  2023-06-18 15:32:54,550 [shard 0] cdc - New CDC generation: (2023/06/18 12:32:54, add2bc1d-6823-40b8-88dc-680aa8920f1b)
```

But - maybe the information about `.29` liveness didn't reach shard 1 by the time repair started?

cc @asias - could you please look into this? Do you think my hypothesis is plausible?

**Comment by michoecho** [comment]
Witnessed again in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/1957/artifact/testlog/x86_64/dev/scylla-194.log

**Comment by mykaul** [comment]
@asias - please look into this, if it's still even relevant (?)

**Comment by mykaul** [comment]
Closing for the time being, as we have not seen it happening for quite some time.
