### ISSUE TITLE
CQL grammar doesn't allow SELECT of function with constant parameters

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14310]
The not-exactly-useful, but still legal, SELECT command
```
SELECT mintimeuuid('2013-01-01 00:05+0000') FROM tbl WHERE p=123
```
Fails to parse (a syntax error). It works in Cassandra.

Note that the following variants **do** work, showing where exactly the bug is located in `Cql.g`:
1. `SELECT mintimeuuid(t) FROM tbl WHERE p=123` (where `t` is a column of type timestamp) does work. So the grammar's `selectionFunctionArgs` doesn't accept constants but accepts a column name.
2. The same expression `mintimeuuid('2013-01-01 00:05+0000')` works as part of a WHERE, so it's only a bug in the SELECT parsing.
3. `SELECT now() FROM tbl WHERE p=123` works - so the parser has just a problem with constant function arguments, it is fine with constant-returning functions without arguments.

**Comment by nyh** [comment]
The following patch:
```patch
+++ b/cql3/Cql.g
@@ -419,9 +419,16 @@ selector returns [shared_ptr<raw_selector> s]
     : us=unaliasedSelector (K_AS c=ident { alias = c; })? { $s = ::make_shared<
raw_selector>(us, alias); }
     ;
 
+selectionLiteral returns [expression value]
+    : c=constant           { $value = std::move(c); }
+    | K_NULL               { $value = make_untyped_null(); }
+    | e=marker             { $value = std::move(e); }
+    ;
+
 unaliasedSelector returns [expression s]
     @init { expression tmp; }
     :  ( c=cident                                  { tmp = unresolved_identifier{std::move(c)}; }
+       | z=selectionLiteral                        { tmp = std::move(z); }
        | K_COUNT '(' countArgument ')'             { tmp = make_count_rows_function_expression(); }
        | K_WRITETIME '(' c=cident ')'              { tmp = column_mutation_attribute{column_mutation_attribute::attribute_kind::writetime,
                                                                                               unresolved_identifier{std::move(c)}}; }
```

(I used the name "selectionLiteral" that Cassandra's parser uses)

This almost works - it does print an ANTLR warning which I don't understand and will have to be fixed, but finishes the build. The problem is that when actually used with a constant selector, we get a runtime error:
```
no way to express SELECT constant in the grammar yet
```

So I guess this needs support also in the evaluate() code. CC @cvybhu @avikivity

**Comment by cvybhu** [comment]
I think this might be a duplicate of https://github.com/scylladb/scylladb/issues/12607 (or the other way around)

To fix this we will have to move selectables to expressions, complete `prepare` implementation and modify the grammar.

**Comment by nyh** [comment]
Yes, it seems the same thing. I'll close this one as a duplicate and add missing information (if any) to that other issue.
