### ISSUE TITLE
Compactions that filter partitions may pollute index caching

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14317]
Index caching is not scan resistant yet, so compactions that use index for forwarding to the next partition (e.g. cleanup), may end up polluting the index caching. Once the caching is scan resistant, MFU entries will remain cached, whereas LRU entries which aren't frequent will have lower priority over the most frequently used ones. We can easily fix the problem today by bypassing the cache with the help of partition slice's option set.

**Comment by raphaelsc** [comment]
PR https://github.com/scylladb/scylladb/pull/14469 will significantly reduce the impact of cache pollution, by partition skipping during cleanup and view updates from staging.

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backports to all active 5.x

**Comment by denesb** [comment]
I am not sure we should even backport this. This is a performance improvement, it is not fixing a bug or regression. Cleanup has always worked with a filter.

**Comment by DoronArazii** [comment]
> I am not sure we should even backport this. This is a performance improvement, it is not fixing a bug or regression. Cleanup has always worked with a filter.

@raphaelsc the plan is not to backport this?

**Comment by raphaelsc** [comment]
> > I am not sure we should even backport this. This is a performance improvement, it is not fixing a bug or regression. Cleanup has always worked with a filter.
> 
> @raphaelsc the plan is not to backport this?

Yes, this is a good improvement, but not fixing a regression.

**Comment by mykaul** [comment]
@raphaelsc - so the backport labels should be removed, no?

**Comment by raphaelsc** [comment]
> @raphaelsc - so the backport labels should be removed, no?

Done. thanks
