### ISSUE TITLE
Add a mechanism to forbid updating LiveUpdatable configuration parameters via CQL

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#14355]
Every configuration parameter (defined in [config.hh](https://github.com/scylladb/scylladb/blob/master/db/config.hh)) has `liveness` value assigned, which controls if a configuration parameter can be changed in runtime or not (in which case it requires a restart). Currently, changing configuration parameters in runtime can be achieved by e.g.:
- modifying `scylla.yaml` and sending `SIGHUP` signal to reload the configuration on the fly,
- updating rows from `system.config` virtual table,
- API call.

A mechanism to forbid updating LiveUpdatable configuration parameters via CQL, i.e. updating `system.config` virtual table, is needed, because we don't want off-premise (cloud) users to reconfigure their nodes themselves (by updating `system.config`) in runtime, but we want to leave that possibility opened for on-premise users. This means that even though a configuration parameter has been defined with `liveness::LiveUpdate`, some users shouldn't be able to change it via CQL in runtime, which is possible now, and for that reason we should treat this issue as a security vulnerability.

Extends https://github.com/scylladb/scylladb/pull/4559

**Comment by avikivity** [comment]
Not a bug, not backporting.

**Comment by ptrsmrn** [comment]
If I can only add my 2 cents: it's a bug in the sense that it's a security loophole, by which cloud users can perform an operation they are not allowed to, in this case - changing some configuration options in the runtime.
