### ISSUE TITLE
UUID - 1fd4c376-bc6c-462f-a177-90ae402777f2  : Benchmarking on Azure storage optimised instances 

### ISSUE THREAD

**Issue by shahswapnil24** [scylladb/scylladb#14353]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

I have send Prometheus data with the UUID mentioned. We have performed benchmarking on Azure storage optimized instances and would like to understand the performance difference between Intel (L8sV3) and AMD (L8asV3) instances. 

*Installation details*
Scylla version (or git commit hash):  Scylla Enterprise 2022.2.3-0.20230312.af0a90c86e0c
Cluster size: 3 nodes 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Cloud Instance (Azure L8sV3 and L8asV3)
Hardware: sockets= cores= hyperthreading= memory= 
Disks: (SSD/HDD, count) NVMe 1

**Comment by mykaul** [comment]
@shahswapnil24 - if you are using enterprise versions, I suggest opening a ticket with Scylla, so we can look into it with all the details, logs, etc.
I assume the data was sent following https://opensource.docs.scylladb.com/stable/troubleshooting/report-scylla-problem.html#send-files-to-scylladb-support ?

**Comment by gcarmin** [comment]
@mykaul  this should have gone to me directlly.
Thanks - I'm closing this one.
