### ISSUE TITLE
unit tests try to talk to themselves via rpc

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#14388]
running any cql_query_test shows (may need debug mode to slow it down)

```
ERROR 2023-06-25 20:33:52,036 [shard 0] rpc - client 127.0.0.1:7000: client connection dropped: connection is closed
ERROR 2023-06-25 20:33:52,142 [shard 0] rpc - client 127.0.0.1:7000: client connection dropped: connection is closed
ERROR 2023-06-25 20:33:52,241 [shard 0] rpc - client 127.0.0.1:7000: client connection dropped: connection is closed
ERROR 2023-06-25 20:33:52,342 [shard 0] rpc - client 127.0.0.1:7000: client connection dropped: connection is closed
ERROR 2023-06-25 20:33:52,439 [shard 0] rpc - client 127.0.0.1:7000: client connection dropped: connection is closed
```

this is wrong, cql_test_env shouldn't try to talk to anything.

**Comment by avikivity** [comment]
@kbr-scylla @kostja

**Comment by kostja** [comment]
@margdoc I thinik this is something you could look at, CC @kbr-scylla

**Comment by nyh** [comment]
@avikivity I'm doing "wireshark" over an actual single-node Scylla run (not a unit test), and it also seems to be "talking to itself" - sending a message to TCP port 7000 (rpc) to 127.0.0.1 (this node itself), roughly once every 0.1 seconds, very regularly. I'm not sure it's the **same** issue that you saw in unit tests, but maybe? Why would Scylla need to send itself messages over TCP?

**Comment by kostja** [comment]
Direct failure detector currently doesn't make a distinction between self and other nodes in the cluster. This can be fixed now after @kbr-scylla refactoring of CQL query processor, we can load host id early and detect that we're trying to ping self in the failure detector.

**Comment by avikivity** [comment]
Minor, not backporting.
