### ISSUE TITLE
test_permissions.test_grant_revoke_uda_permissions is flaky

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#14395]
branch: 5.3

scylla-5.3/next failed on Test stage, for more details: https://jenkins.scylladb.com/job/scylla-5.3/job/next/36/
failed tests: 3 of 38240.
- non-boost tests.cql-pytest.test_describe.dev.1
- non-boost tests.cql-pytest.test_permissions.dev.3
- test_permissions.test_grant_revoke_uda_permissions
    cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot delete function cql_test_1687782735223.cql_test_1687782735253 : (frozen<tuple<bigint, bigint>>, bigint) -> frozen<tuple<bigint, bigint>>, as it is used by user-defined aggregate cql_test_1687782735223.custom_avg"
Full details on the Test Result page: https://jenkins.scylladb.com/job/scylla-5.3/job/next/36/testReport/

**Comment by avikivity** [comment]
@wmitros please see if you can harden the test.

**Comment by wmitros** [comment]
Fixed by https://github.com/scylladb/scylladb/pull/14662
