### ISSUE TITLE
View update generator may process disowned tokens after aborted decommission

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14392]
Decommission migrates tokens from the decommissioned node to the remaining nodes.
When a table as materialized view or secondary indexes, we generate view updates from the sstables containing those tokens that are put in the staging sub-directory.

When decommission is aborted, it is no longer necessary to generate those view updates and cleanup is run to remove those now-disowned tokens from the nodes, but cleanup skips the staging sstables due to the race with view building (see #9559).
It was observed that the view update generation process may take a long time, which holds up cleanup.
and even with #13812, we wait for view updates to be done before cleaning up the staging sstables.

This was addressed in #11932 by simply skipping over the disowned tokens in the view update generator reader, which may not be the optimal way, but it is correct and allows the view update generator to completely quickly after decommission is aborted, and the cleanup can run normally.

This issue is now opened for backporting purposes.

**Comment by bhalevy** [comment]
Fixed by 3aff59f1899393bfa299e17f52995d63fa6b7d35

**Comment by DoronArazii** [comment]
@mykaul the milestone that has this patch (https://github.com/scylladb/scylladb/commit/3aff59f1899393bfa299e17f52995d63fa6b7d35) is 5.2
We need it backported to 5.1 if possible.
@scylladb/scylla-maint please assist.

**Comment by denesb** [comment]
Backported to 5.1.
