### ISSUE TITLE
alternator-executor - Unhandled exception in data streaming: std::system_error (error system:32, send: Broken pipe) 

### ISSUE THREAD

**Issue by libo-sober** [scylladb/scylladb#14416]
*Installation details*
Scylla version (or git commit hash): 5.1.12
Cluster size: 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

### Phenomenon
Some nodes in the cluster crashed. In the log of this node, there are reports of such exceptions: `alternator-executor - Unhandled exception in data streaming: std::system_error (error system:32, send: Broken pipe)`. And there is a prompt that `commitlog - Cannot parse the version of the file: SchemaLog-2-1949134339.log`
![ Unhandled exception in data streaming](https://github.com/scylladb/scylladb/assets/70140794/1c6576db-f7d3-4079-9466-a3cee63d9cc2)
![Cannot parse commitlog](https://github.com/scylladb/scylladb/assets/70140794/8146d1c2-c890-4a0a-8870-1b5d402ecb24)

### Background
When such an exception occurs, the cluster has a large number of read write and delete ops. And the item is relatively large. Previously, we upgraded the cluster from 4.6.11 to 5.1.10, and then upgraded to the current 5.1.12. The host running scylla has no abnormalities.
![scylla ops](https://github.com/scylladb/scylladb/assets/70140794/83ac0c87-1907-4f03-9749-83951b3bea07)

### Guesses

1. Is it related to cluster upgrade, which makes it impossible to parse the old version of commitlog？
2. Is it related to performing large item operations when there is a large number of ops in the cluster?

Thanks.

**Comment by mykaul** [comment]
Is it related to https://github.com/scylladb/scylladb/issues/14403 ?

**Comment by libo-sober** [comment]
> #14403 seems to have identical details to this issue, and discusses the same issues mentioned here (the commit-log error messages, the "Unhandled exception in data streaming" messages, the large items and the crashes).
> 
> Can we close this one as a duplicate?

Yes, thanks. I will follow https://github.com/scylladb/scylladb/issues/14403 .

**Comment by nyh** [comment]
@mykaul, silly question - I see you changed this issue from "completed" to "not planned". Could we get more fine-grained reasons listed here, like "duplicate", or "invalid", and so on? "not planned" sounds misleading in most cases...

**Comment by mykaul** [comment]
> @mykaul, silly question - I see you changed this issue from "completed" to "not planned". Could we get more fine-grained reasons listed here, like "duplicate", or "invalid", and so on? "not planned" sounds misleading in most cases...

I wish... Even the 'not planned' one - I'm unsure (but hopeful) one day we'll be able to get granular statistics for these (which is why I bothered to change it in the 1st place). This is what they have right now:
```
"state": {
        "description": "State of the issue; either 'open' or 'closed'",
        "type": "string",
        "examples": [
          "open"
        ]
      },
```
So I'm not even sure if it's not just cosmetics right now :-/ 

We could add a label, but I'm afraid we have so many already, and we'll be inconsistent, and so forth.
