### ISSUE TITLE
docs: min_sstable_size is wrongly defined as 50

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14413]
The `min_sstable_size` STCS option is in bytes, not in MB.
While https://github.com/scylladb/scylladb/blob/3ca0c6c0a5b2705eb475537a738e987be4b863ba/docs/cql/compaction.rst?plain=1#L119 defines it as `50`,
It is is defined as 50MB in scylla's code: https://github.com/scylladb/scylladb/blob/3ca0c6c0a5b2705eb475537a738e987be4b863ba/compaction/size_tiered_compaction_strategy.hh#L21

**Comment by bhalevy** [comment]
See also https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlCreateTable.html#compactSubprop__compactionSubpropertiesSTCS

**Comment by raphaelsc** [comment]
good catch
