### ISSUE TITLE
streaming reader_concurrency_semaphore uses CPU based admittance

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#14425]
None of the reads done through the streaming concurrency semaphore go through cache, so the CPU based admittance strategy makes no sense there and it could contribute to the excess slowness of repair observed recently.

**Comment by asias** [comment]
> None of the reads done through the streaming concurrency semaphore go through cache, so the CPU based admittance strategy makes no sense there and it could contribute to the excess slowness of repair observed recently.

Is this a recent regression, which commit? What happens if the streaming goes with the cpu based admittance? Will it make streaming to complete with regular query?

**Comment by denesb** [comment]
> > None of the reads done through the streaming concurrency semaphore go through cache, so the CPU based admittance strategy makes no sense there and it could contribute to the excess slowness of repair observed recently.
> 
> Is this a recent regression, which commit? 

CPU based admission was added in 4.6. It is not new.

> What happens if the streaming goes with the cpu based admittance? Will it make streaming to complete with regular query?

No, but the semaphore will make the competition between the streaming reads more fierce because the CPU based admission is more strict than the regular resources based one.

**Comment by DoronArazii** [comment]
@mykaul the issue found on 2023.2.0 which is equally to 5.3 - adding the relevant backport label

**Comment by asias** [comment]
Any progress on this?

**Comment by DoronArazii** [comment]
@denesb where is it standing?

**Comment by denesb** [comment]
Closing, streaming using the CPU-based admittance should not have any adverse effects on streaming/repair performance.

**Comment by asias** [comment]
> Closing, streaming using the CPU-based admittance should not have any adverse effects on streaming/repair performance.

Botond, could you share more details on why? If streaming does not need CPU-based admittance, can we just get rid of it even if the impact is low?

**Comment by denesb** [comment]
> There should be no impact at all, but I will try to test this, to see if there is any observable difference.

According to my testing, CPU-based admittance does not have any negative impact, on the opposite, it even improves the repair time a bit.

I tested with a table, having 100K partitions, each having 100 small rows, and a cluster with 3 nodes (RF=3). I ran a simple repair. @asias do you have a better test scenario in mind that I could test with?

**Comment by asias** [comment]
> > There should be no impact at all, but I will try to test this, to see if there is any observable difference.
> 
> According to my testing, CPU-based admittance does not have any negative impact, on the opposite, it even improves the repair time a bit.
> 
> I tested with a table, having 100K partitions, each having 100 small rows, and a cluster with 3 nodes (RF=3). I ran a simple repair. @asias do you have a better test scenario in mind that I could test with?

Do you run background c-s (cql) workload while you run repair? We need to check if the cql workload have too much impact on repair. You can also insert more partitions and delete some sstables on one of the nodes to generate some difference to make repair work harder.

**Comment by denesb** [comment]
> Do you run background c-s (cql) workload while you run repair? We need to check if the cql workload have too much impact on repair. 

I think adding a background load would just muddy the picture here.

**Comment by asias** [comment]
> > Do you run background c-s (cql) workload while you run repair? We need to check if the cql workload have too much impact on repair.
> 
> I think adding a background load would just muddy the picture here.

The concern is about the cql takes the cpu admittance so that streaming could not take, as a result streaming gets slow unnecessarily? If there is no cql workload, I doubt taking the cpu admiitance (e.g. take a lock no body takes) could make any real  differences.

**Comment by denesb** [comment]
> The concern is about the cql takes the cpu admittance so that streaming could not take, as a result streaming gets slow unnecessarily? If there is no cql workload, I doubt taking the cpu admiitance (e.g. take a lock no body takes) could make any real differences.

This cannot happen. User and streaming workloads are on separate semaphores, each with their own admission.

**Comment by denesb** [comment]
Even with much more partitions and increased parallelism, there is no difference.

**Comment by avikivity** [comment]
I thought of a reason to disable CPU based admittance. Suppose the system is heavily loaded, so little CPU is left for the streaming group. Suppose read-ahead and streaming (and write-behind on the remote side) work well enough that the reader is always either consuming CPU, or waiting for CPU to become available. This will block new readers from starting. If this continues long enough, then those readers will time out.

Now, I don't think this is a reason to remove CPU based admittance, just to think more about the issue. There has to be a maximum concurrency level, or we run out of memory. If there is a maximum concurrency level N, and there are N+1 readers, one of them will starve. So removing CPU based admittance doesn't solve the problem, it moves it from N=1 to N=something else.

This is why I disliked timeouts on streaming readers - they can cause the system to thrash.

**Comment by bhalevy** [comment]
> > There should be no impact at all, but I will try to test this, to see if there is any observable difference.
> 
> According to my testing, CPU-based admittance does not have any negative impact, on the opposite, it even improves the repair time a bit.
> 
> I tested with a table, having 100K partitions, each having 100 small rows, and a cluster with 3 nodes (RF=3). I ran a simple repair. @asias do you have a better test scenario in mind that I could test with?

@denesb I think the original issue is related to repair over nodes with different number of shards, which causes an inflation in the number of streams.

**Comment by denesb** [comment]
> @denesb I think the original issue is related to repair over nodes with different number of shards, which causes an inflation in the number of streams.

Yes, but that doesn't change whether individual reads get stuck on the CPU admittance or not.
