### ISSUE TITLE
TWCS not deleting expired sstables

### ISSUE THREAD

**Issue by mnutt** [scylladb/scylladb#14423]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2.2-0.20230521.9dd70a58c3f9
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04

### Context

I have a scylla database with a single non-system keyspace and table:

```
CREATE TABLE production.links (
    pkey text,
    time timestamp,
    extra_data text,
    link text,
    PRIMARY KEY (pkey, time)
) WITH CLUSTERING ORDER BY (time DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'DAYS'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 1209600
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

I have writers that insert data like this:

```
UPDATE links SET link=?, extra_data=? WHERE pkey=? AND time=?
```

Where `time` is a timestamp rounded down to the nearest hour. The idea is to then query to retrieve the latest link, and use `time` to ensure that we don't write keys older than an hour, rounding the timestamp to ensure no `pkey` partition has too many records.

### Issue

My expectation is that I store 14 days' worth of records, with a compaction window of 1 day, and that each day the sstables from 14 days ago expire and get deleted. I've been running the cluster for about 3 weeks now and have seen disk space steadily increasing the entire time:

<img width="2251" alt="image" src="https://github.com/scylladb/scylladb/assets/3705/e9254ae2-d76a-41d4-ab85-d7940f2d55d7">
(disk space usage of /var/lib/scylla, in TB)

From https://github.com/scylladb/scylladb/issues/8038 I found [this tool](https://gist.githubusercontent.com/raphaelsc/c7dfeab7b1083c129c222762edd4e672/raw/4da9e7cb1b737dd648342f9cbc85efe419bf7338/expired_sstables_status.py) which didn't support tables of format me, modifying the script to add me to the list lets it run but I have no clue if that invalidates the results.

If the results _are_ valid, it seems to show many deletable tables: https://gist.github.com/mnutt/96cc6619e612d6157a5c72988c7d6881

Scylla log sample with `compaction` and `compaction_manager` tracing: https://gist.github.com/mnutt/239df5b5b34e97a308aa86fa74f92c59

I have tried a full compaction as well as restarting scylla on one of the nodes, without any change in the rate of disk space increase.

**Comment by raphaelsc** [comment]
> Example `sstablemetadata` output: https://gist.github.com/mnutt/899b9172e504d5d73af13b6a31185702

please run https://gist.github.com/raphaelsc/f013a6743806e6587f110dcdf0db4daf. 

usage: ics_or_stcs_describe_sstable_layout.py /path/to/table smp_count

smp_count is the total number of cpus assigned to scylla (take into account if any core was dedicated to handling networking IRQ).

**Comment by raphaelsc** [comment]
@mnutt what does nodetool cfstats production.links say?

**Comment by mnutt** [comment]
I just noticed `gc_grace_seconds = 864000` which was absolutely supposed to be `86400`. It has to be the most likely cause of the issue; I'm going to update it and repair to verify but will likely be closing this issue out shortly.

**Comment by raphaelsc** [comment]
So you're updating existing rows, right? one of the problems with it is transient read and space amplification, as we cannot get rid of the shadowed data (by update) until it gets expired. A possible way to handle it is major compaction, but you said you tried it above.

**Comment by raphaelsc** [comment]
Yes, a high gc_grace_seconds may be deferring purge of fully expired sstables by 10 days. please keep me posted.

**Comment by mnutt** [comment]
Confirmed it was `gc_grace_seconds`. Changed it, repaired tables, and it has freed the space. Sorry for the spurious report.

> So you're updating existing rows, right?
With `[pkey, ROUND(ts, 'HOUR')]`, row updates can occur, but not more than an hour after the fact. My hope with that is that we'd only have to wait an extra hour, max, at the end of the TTL.
