### ISSUE TITLE
Resharding doesn't need to apply compacting reader

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14439]
Resharding should be restricted to segregating data according to its owner shard. Today, it applies compacting reader, which is redundant because reshape will later do it anyway.

**Comment by mykaul** [comment]
@raphaelsc , @bhalevy - priority for this?

**Comment by mykaul** [comment]
We see it happening frequently when customer change instance type though, right?

**Comment by avikivity** [comment]
> We see it happening frequently when customer change instance type though, right?

No, because instance type change happens through bootstrap + decommission.

Resharding happens when we want to change the number of cores dedicated to networking. And it won't happen with tablets, so there's no reason to touch this. If resharding is a little slower no one notices.

**Comment by bhalevy** [comment]
FWIW, there was a plan not long ago to make the number of shards more agile with serverless.

**Comment by mykaul** [comment]
> > We see it happening frequently when customer change instance type though, right?
> 
> No, because instance type change happens through bootstrap + decommission.
> 
> Resharding happens when we want to change the number of cores dedicated to networking. And it won't happen with tablets, so there's no reason to touch this. If resharding is a little slower no one notices.

Right - it happened when perftune settings were not set correctly and were changed, thus changing the no. of cores.

**Comment by mykaul** [comment]
@raphaelsc - are you planning to work on it for 6.0? Otherwise, not sure it'll be important enough to work at all?

**Comment by raphaelsc** [comment]
@mykaul if you don't have any objection I am planning to close this since resharding perf issues will no longer be a problem with tablets

**Comment by mykaul** [comment]
> @mykaul if you don't have any objection I am planning to close this since resharding perf issues will no longer be a problem with tablets

OK.
