### ISSUE TITLE
sstables/metadata_collector.cc:49 @update_min_max_components: failed to log message: fmt='{}: setting max_clustering_key={}': seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple - not enough bytes (expected 4, got 0)

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14435]
After enabling TestCommitLog in gating:
scylladb/scylla-dtest@e0cd2ac306deec541b17bc9ef5404cb2703ab3af

We immediately observed a failure
```
failed on teardown with "AssertionError: Unexpected errors found: [('node1', ["ERROR 2023-06-28 09:35:07,721 [shard 0] metadata_collector - sstables/metadata_collector.cc:49 @update_min_max_components: failed to log message: fmt='{}: setting max_clustering_key={}': seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple - not enough bytes (expected 4, got 0) Backtrace: 0x5a7fbde 0x5a80190 0x5a80478 0x2d19948 0x2d19504 0x2cbd2dd 0x1c8c163 0x1c8b61d 0x1c8b574 0x1c8b129 0x1253d9c 0x25b9975 0x5a89d43 0x25b8ff6 0x23667e6 0x21ea871 0x21e9c06 0x59618a6", "ERROR 2023-06-28 09:35:07,720 [shard 0] metadata_collector - sstables/metadata_collector.cc:44 @update_min_max_components: failed to log message: fmt='{}: setting min_clustering_key={}': seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple - not enough bytes (expected 4, got 0) Backtrace: 0x5a7fbde 0x5a80190 0x5a80478 0x2d19948 0x2d19504 0x2cbd2dd 0x1c8c163 0x1c8b61d 0x1c8b574 0x1c8b129 0x1253d9c 0x25b9975 0x5a89d43 0x25b9056 0x23667a5 0x21ea871 0x21e9c06 0x59618a6", "ERROR 2023-06-28 09:35:07,721 [shard 0] metadata_collector - sstables/metadata_collector.cc:49 @update_min_max_components: failed to log message: fmt='{}: setting max_clustering_key={}': seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple - not enough bytes (expected 4, got 0) Backtrace: 0x5a7fbde 0x5a80190 0x5a80478 0x2d19948 0x2d19504 0x2cbd2dd 0x1c8c163 0x1c8b61d 0x1c8b574 0x1c8b129 0x1253d9c 0x25b9975 0x5a89d43 0x25b8ff6 0x23667a5 0x21ea871 0x21e9c06 0x59618a6", "ERROR 2023-06-28 09:35:07,725 [shard 0] metadata_collector - sstables/metadata_collector.cc:22 @convert: failed to log message: fmt='{}: convert: {}': seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple - not enough bytes (expected 4, got 0) Backtrace: 0x5a7fbde 0x5a80190 0x5a80478 0x2d19948 0x2d19504 0x2cbd2dd 0x1c8c163 0x1c8b61d 0x1c8b574 0x1c8b129 0x1253d9c 0x25b984d 0x5a89d43 0x25b7b79 0x208b911 0x237590b 0x21e9c0e 0x59618a6", "ERROR 2023-06-28 09:35:07,725 [shard 0] metadata_collector - sstables/metadata_collector.cc:22 @convert: failed to log message: fmt='{}: convert: {}': seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple - not enough bytes (expected 4, got 0) Backtrace: 0x5a7fbde 0x5a80190 0x5a80478 0x2d19948 0x2d19504 0x2cbd2dd 0x1c8c163 0x1c8b61d 0x1c8b574 0x1c8b129 0x1253d9c 0x25b984d 0x5a89d43 0x25b7b79 0x208b8fa 0x237590b 0x21e9c0e 0x59618a6"])]"
```

one of the lines where this is triggered:
```cpp
        mdclogger.trace("{}: setting min_clustering_key={}", _name, position_in_partition_view::printer(_schema, min_pos));
```

looks like `position_in_partition_view::printer(_schema, min_pos)` is incorrect - `min_pos` can't be printed in some cases?

**Comment by bhalevy** [comment]
I would be nice to run some tests with trace logging level enabled by default on all loggers.
Let's bring some popcorn and sit down to enjoy the wonderful colors of the smoke coming out the system ;-)

**Comment by michoecho** [comment]
This is a regression in 3738fcbe054ef1540f262079d89e44c9b873769e. That commit uses `zip_iterator` to iterate over the key tuple and the type tuple. But `zip_iterator` requires both ranges to have the same length (unlike python). But `position_in_partition` doesn't have to have all components — trailing components might be absent. The old code handled that properly, the new doesn't, and reads garbage memory.

cc @tchaikov

**Comment by bhalevy** [comment]
> This is a regression in [3738fcb](https://github.com/scylladb/scylladb/commit/3738fcbe054ef1540f262079d89e44c9b873769e). That commit uses `zip_iterator` to iterate over the key tuple and the type tuple. But `zip_iterator` requires both ranges to have the same length (unlike python). But `position_in_partition` doesn't have to have all components — trailing components might be absent. The old code handled that properly, the new doesn't, and reads garbage memory.
> 
> cc @tchaikov

True. We indeed may update min_max_components with partial prefixes that can arrive from range tombstones.
In fact, even a partition tombstone can be seen as a partial (and empty) prefix so it covers all rows in the range (and it encoded as such in min_max_components IIRC).

**Comment by mykaul** [comment]
@tchaikov - and I assume we'll need a backport to 5.3?

**Comment by tchaikov** [comment]
> @tchaikov - and I assume we'll need a backport to 5.3?

@mykaul no need. double checked.
```console
 git br -r --contains 3738fcbe054ef1540f262079d89e44c9b873769e | grep origin
  origin/HEAD -> origin/master
  origin/br-next
  origin/master
  origin/next
```

and i inspected the output of `git log origin/branch-5.3` also.

**Comment by michoecho** [comment]
> > @tchaikov - and I assume we'll need a backport to 5.3?
> 
> @mykaul no need. double checked.

@tchaikov You either have `origin` set to something other than https://github.com/scylladb/scylladb, or you didn't fetch it in a long time:
```
git branch -r --contains 3738fcbe054ef1540f262079d89e44c9b873769e | grep origin
  origin/br-next
  origin/branch-5.3
  origin/master
  origin/next
  origin/next-5.3
```
```
git tag --contains 3738fcbe054ef1540f262079d89e44c9b873769e
scylla-5.3.0-rc0
```
```
git log origin/branch-5.3 | grep -A 5 'commit 3738fcbe054ef1540f262079d89e44c9b873769e'

commit 3738fcbe054ef1540f262079d89e44c9b873769e
Author: Kefu Chai <kefu.chai@scylladb.com>
Date:   Thu Apr 13 18:19:24 2023 +0800

    keys: specialize fmt::formatter<partition_key> and friends
```
![image](https://github.com/scylladb/scylladb/assets/45052050/fdfae3d2-00a7-499c-953f-44ee2f702000)

**Comment by tchaikov** [comment]
Ahh, i haven’t updated the branch for a while. Thank you for pointing this out!

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
