### ISSUE TITLE
Use statement might throw an exception instead of returning an exceptional future

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#14449]
The use statement execution code can throw if the keyspace is doesn't exist, this can be a problem for code that will use execute in a fiber since the exception will break the fiber even if then_wrapped is used.

**Comment by eliransin** [comment]
It is not a per-SE bug but I have added it so it will enter the backport cycle, except this it also causes an audit bug on enterprise.

**Comment by nyh** [comment]
> The use statement execution code can throw if the keyspace is doesn't exist, this can be a problem for code that will use execute in a fiber since the exception will break the fiber even if then_wrapped is used.

It's not clear from this phrasing if this problem actually happens or you could reproduce it, or it's  a thought experiment of something that **might** happen. If it does happen, please give an example scenario how it happens (even better - an actual test case). If it's just a thought experiment, then can you please explain better the thought: What do you mean "code that will use execute in a fiber" - this function is just many of statement::execute implementations, do all of those implementations catch exceptions? Who are the callers and why shouldn't we catch exceptions there to solve this problem for all statement types and not just USE?

**Comment by denesb** [comment]
Backported to 5.4 and 5.2.
