### ISSUE TITLE
conftest.py: run_async() is broken w.r.t. paged queries

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#14451]
As it sets the future's result on the first callback, i.e. on the first page if the request is paged. The rest of the pages are ignored.

**Comment by alecco** [comment]
It could have this [PagedResultHandler](https://docs.datastax.com/en/developer/python-driver/3.19/query_paging/#handling-paged-results-with-callbacks). WDYT?

cc @fruch

**Comment by fruch** [comment]
> It could have this [PagedResultHandler](https://docs.datastax.com/en/developer/python-driver/3.19/query_paging/#handling-paged-results-with-callbacks). WDYT?
> 
> cc @fruch

this is how we use it in dtest and in SCT, when we need paging.

but we don't use the `run_async` anywhere... so I'm not sure exactly what's it's missing to be able to handle paging correctly

**Comment by denesb** [comment]
> It could have this [PagedResultHandler](https://docs.datastax.com/en/developer/python-driver/3.19/query_paging/#handling-paged-results-with-callbacks). WDYT?

Looks good to me.

**Comment by denesb** [comment]
I don't even mind if it is a separate method, like `cql.run_async(statement, my_handler)`, where `my_handler` is invoked with the result on each page, by the internal `ResultHandler`.

**Comment by alecco** [comment]
Meanwhile, you can use just non-async execute in your test.

The main reason for async queries in tests was to be able to do queries in parallel (e.g. with `asyncio.gather()`) and for future-proofing.

**Comment by denesb** [comment]
Improvement, not backporting.
