### ISSUE TITLE
docs: link to a ScyllaDB private repository

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#14459]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.2/using-scylla/mig-tool-review

### Problem

The page contains a link to a private repository:

> For example, [unirestore](https://github.com/scylladb/field-engineering/tree/master/unirestore): SSTable to SSTable

As a result, it's a dead link.

### Solution

We should make the `unirestore `tool public or remove the information from the docs.

@tzach @ebenzecri  Could you advise?

**Comment by tzach** [comment]
I sugget to remove the link to this tool

**Comment by ebenzecri** [comment]
@vladzcloudius @tarzanek Guys?

**Comment by denesb** [comment]
Minor doc improvement, not backporting.
