### ISSUE TITLE
alternator: assertion in output_stream when exception occurs during response streaming

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#14453]
For instance if client connection breaks then broken_pipe exception is thrown, that will later trigger assertion in ~output_stream because we are not calling close() in such case. Sadly this brings down the whole server.

**Comment by nyh** [comment]
This should be backported as widely as we can, as it can bring down an entire cluster (as happened https://github.com/scylladb/scylladb/issues/14403) because of unexpected application behavior.

**Comment by nyh** [comment]
Also happened in https://github.com/scylladb/scylladb/issues/13179

**Comment by nuivall** [comment]
@DoronArazii how we can kick off the backport process here?

**Comment by DoronArazii** [comment]
> @DoronArazii how we can kick off the backport process here?

Tagging @scylladb/scylla-maint sometimes speed up the process.

**Comment by DoronArazii** [comment]
BTW do we need it in 2022.1? (equal to 5.0 which is already EOL)?
If we do, then you should raise a dedicated PR on the enterprise repo.

**Comment by nuivall** [comment]
I have no idea how we usually judge such backports so I'd let others decide, but consequence of not having the patch is severe - cluster crash when client has some connectivity issues.

**Comment by nyh** [comment]
> @DoronArazii how we can kick off the backport process here?

I'll do it myself now.
I'll (try to) backport to 5.1, 5.2 and 5.3.
The Enterprise versions backport process is different, and isn't discussed here.

**Comment by nyh** [comment]
Sadly the backport is not clean. E.g., 0b5655021a71263fce81d0f5766b6016d4d43b9f also messed with the make_streamed(), and likely even older code is even more different. I'll need to create separate PRs to have the result tested :-(

**Comment by nyh** [comment]
Sorry for the spam, but I'm starting to think I actually need to backport the other conflicting changes (like https://github.com/scylladb/scylladb/issues/13689) first, instead of trying to fix this backport.

**Comment by nyh** [comment]
Backported to next-5.3 (fb0afb04aea0d7f683dcebe946eafe6fe0213ca5)

**Comment by nyh** [comment]
I confirmed that all three backports (to 5.3, 5.2, 5.1) were successfullly promoted.

**Comment by DoronArazii** [comment]
Backported. Removing the tracking 5.x labels.
