### ISSUE TITLE
doc:  Verify it the documented Automatic Bug Reporting Tool limitation is still valid

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#14488]
https://enterprise.docs.scylladb.com/stable/operating-scylla/admin.html#core-dumps
The administration guide includes the following information about core dumps:

> On RHEL and CentOS, the Automatic Bug Reporting Tool ([ABRT](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/System_Administrators_Guide/ch-abrt.html)) conflicts with Scylla coredump configuration. Remove it before installing Scylla: `sudo yum remove -y abrt`

However, the linked page to ABRT is empty, which indicates it was added long ago.

What's more, the same information is added to the [installation guide](https://www.scylladb.com/download/?platform=rhel&version=scylla-5.2#open-source):

> If you have The Automatic Bug Reporting Tool (commonly abbreviated as ABRT) installed, it will conflict with ScyllaDB coredump configuration. Remove it before installing ScyllaDB: `sudo yum remove -y abrt`

Is this limitation up to date? Perhaps it's no longer valid?

**Comment by annastuchlik** [comment]
@scylladb/releng  @denesb Could you help?

**Comment by denesb** [comment]
> @denesb Woud this link be OK? https://fedoraproject.org/wiki/Automatic_Bug_Reporting_Tool

I think this would be a better link: https://abrt.readthedocs.io/en/latest/.

**Comment by denesb** [comment]
Minor doc improvement, not backporting.
