### ISSUE TITLE
Optimizing range read with a lot of tombstones

### ISSUE THREAD

**Issue by MyByte0** [scylladb/scylladb#14484]
Slow Performance When Performing Scan Query for 100 Records After Deleting All Data in Scylla Cluster.  

Example: After deleting all data in the Scylla cluster, there is a noticeable slow performance issue when performing a scan query task to retrieve 100 records. The query operation takes a significant amount of time to complete, affecting the overall system responsiveness. Please provide any relevant error messages, log entries, or additional details to assist in troubleshooting and resolving this performance issue.  

Add a intelligent tombstone gc mode in this case, like tombstone rate, or another way.

**Comment by nyh** [comment]
Perhaps what you need is repair-based tombstone removal. After deleting vasts amount of data, you can do a **repair** (to ensure that no replica missed some of the deletions) followed by a **compaction** (to actually delete the tombstones). Issue #14130 asks to document this feature better and clearer with exact steps on how to use it to actually remove tombstones immediately.

If you have different ideas on how to safely get rids of tombstones, please elaborate. I didn't understand what you meant by "a intelligent tombstone gc mode in this case, like tombstone rate".

CC @asias

**Comment by MyByte0** [comment]
I see that immediate mode could be useful. Would it be a bad idea to use this mode? Will it get significant performance overhead?

**Comment by nyh** [comment]
This is a tracker for issues and enhancement requests. For questions and discussions on how to best use existing features, we have better places like the scylladb-dev mailing list on googlegroups.com.

**Comment by MyByte0** [comment]
Implement a triggering strategy that can identify a significant number of delete operations and prioritize compaction. The preferred selection criteria are files with a higher count of tombstones or older tombstones. It is essential to ensure that the existence of tombstones is limited within a specified boundary. For instance, if a user defines a duration D, Lethe guarantees that each tombstone will not exist for more than D time. Furthermore, efforts should be made to minimize space amplification, write amplification, and enhance throughput.

The following metadata needs to be recorded: the timestamp a of the earliest tombstone in the file and an estimated count b of the invalidated records due to tombstones.


> 

Implement a triggering strategy that can identify a significant number of delete operations and prioritize compaction. The preferred selection criteria are files with a higher count of tombstones or older tombstones. It is essential to ensure that the existence of tombstones is limited within a specified boundary. For instance, if a user defines a duration D, Lethe guarantees that each tombstone will not exist for more than D time. Furthermore, efforts should be made to minimize space amplification, write amplification, and enhance throughput.  

The following metadata needs to be recorded: the timestamp a of the earliest tombstone in the file and an estimated count b of the invalidated records due to tombstones.
