### ISSUE TITLE
Alternator: Support new ReturnValuesOnConditionCheckFailure feature

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14481]
As announced in https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-dynamodb-cost-failed-conditional-writes/, starting a few days ago DynamoDB added a new option for write operations (PutItem, UpdateItem, or DeleteItem), `ReturnValuesOnConditionCheckFailure`, which if set to `ALL_OLD` returns the current value of the item - but only if a condition check failed:

> Previously, condition check errors in single write operations did not return a copy of the item in the event of a condition check error. A separate read request was necessary to get the item and investigate the cause of the error. Now with the ReturnValuesOnConditionCheckFailure parameter, DynamoDB error messages can include a copy of the item as it was during the write attempt at no additional cost.

**Comment by mykaul** [comment]
This doesn't look like a bug that needs backport?

**Comment by nuivall** [comment]
It's a new feature, not a bug fix.

**Comment by nyh** [comment]
> It's a new feature, not a bug fix.

Right. Our "tradition" in Alternator is that if an API feature is not yet supported, and trying to use it results in a reasonable error or reasonable behavior, then adding support for this feature is considered a "feature" and usually not backported unless there are other circumstances.
