### ISSUE TITLE
In LWT conditions, lists with null values behave differently when passed as a bound value

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#14492]
Performing an `LWT` update with the condition `col IN (null)` should succeed when `col IS NULL`:
```cql
cqlsh:ks> CREATE TABLE tab (p int PRIMARY KEY, r int);
cqlsh:ks> UPDATE tab SET r = 123 WHERE p = 0 IF r IN (null);

 [applied] | r
-----------+------
      True | null

cqlsh:ks> 
```
This doesn't work when the list is passed as a bound value. The LWT statement isn't applied.

Here's an example `cql-pytest` test case:
```python
@pytest.fixture(scope="module")
def table1(cql, test_keyspace):
    schema='p int, c int, r int, s int static, PRIMARY KEY(p, c)'
    with new_test_table(cql, test_keyspace, schema) as table:
        yield table

def test_lwt_list_with_null(cql, table1):
    p = unique_key_int()

    res1 = cql.execute(f"UPDATE {table1} SET r = 1 WHERE p = {p} AND c = 0 IF r IN (null)")
    assert res1[0].applied
    assert res1[0].r == None

    prepared_update = cql.prepare(f"UPDATE {table1} SET r = 1 WHERE p = {p} AND c = 1 IF r IN ?")
    res2 = cql.execute(prepared_update, (None,))
    assert res2[0].applied
    assert res2[0].r == None
```
It fails:
```
        prepared_update = cql.prepare(f"UPDATE {table1} SET r = 1 WHERE p = {p} AND c = 1 IF r IN ?")
        res2 = cql.execute(prepared_update, (None,))
>       assert res2[0].applied
E       assert False
E        +  where False = Row(applied=False, r=None).applied
```

Scylla version: Scylla 5.4.0~dev-0.20230629.f6f974cdeb11

refs: https://github.com/scylladb/scylladb/pull/12411
/cc @avikivity

**Comment by nyh** [comment]
@cvybhu I think this may be a Python driver bug, not a Scylla bug.  Similar to what I first saw in the context https://github.com/scylladb/scylladb/pull/12425/commits/ec1f048a89af9ec47abdfd9b51205890ae2164f8 and reported in https://github.com/scylladb/python-driver/issues/201

I noted that the driver mistakenly translates a null in a collection into an "empty" value (size=0) instead of null value (size=-1). Scylla which gets these "empty values" does the right thing with them (in particular, sees that they are not null).

**Comment by cvybhu** [comment]
You're right, with Rust driver it works correctly:

```rust
let prepared_update = session
        .prepare("UPDATE tab SET r = 123 WHERE p = 0 IF r IN ?")
        .await
        .unwrap();
    let in_list: Vec<Option<i32>> = vec![None];
    let res = session.execute(&prepared_update, (in_list,)).await.unwrap();
    println!("{:#?}", res);
```
```
QueryResult {
    rows: Some(
        [
            Row {
                columns: [
                    Some(
                        Boolean(
                            true,
                        ),
                    ),
                    None,
...
}
```

I opened this isse because the `cql_prepared_test.TestCQL.test_lwt_update_prepared` dtest failure is caused by this behavior.
That's strange, did this test ever pass? 0_o

**Comment by cvybhu** [comment]
The author of the test noticed the issue with nulls in the original commit: https://github.com/scylladb/scylla-dtest//commit/1cd4b13e06d789444ebfa2817b66b895dc30a62c

But then added them anyway, even though test failed with them: https://github.com/scylladb/scylla-dtest//commit/a657990cbad1f5bbad9b938d3aae860d0cb61855

Ummm....

¯\_(ツ)_/¯

**Comment by cvybhu** [comment]
Closing this as a duplicate of https://github.com/scylladb/python-driver/issues/201
