### ISSUE TITLE
View building crashes on large partitions with range tombstones.

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#14503]
View update routines accept mutation objects.
But what comes out of staging sstable readers is a stream of mutation_fragment_v2 objects.
To build view updates after a repair/streaming, we have to convert the fragment stream into mutations. This is done by piping the stream to mutation_rebuilder_v2.

To keep memory usage limited, the stream for a single partition might have to be split into multiple partial mutation objects. view_update_consumer does that, but in improper way -- when the split/flush happens inside an active range tombstone, the range tombstone isn't closed properly. This is illegal, and triggers an internal error.

**Comment by michoecho** [comment]
@scylladb/scylla-maint Pinging for backports.

**Comment by nyh** [comment]
> @scylladb/scylla-maint Pinging for backports.

I'll do it now.

**Comment by nyh** [comment]
Backported to next-5.3 (b0d3dc58c2a28b23315da05bf9b24b27bd3dc7d5).

The backport to next-5.2 and next-5.1 wasn't clean. The conflict was just header files in test/boost/view_build_test.cc so I thought and fixed it but it turns out it uses header files (test/lib/key_utils.hh) which didn't yet exist in 5.1 or 5.2, so it won't build... (I briefly added a backport commit, and then dequeued it, sorry about the mess). So @michoecho please look into the tests and what header files you need for it (and how to avoid needing them) and prepare separate backport PRs (probably the same PR could work for both 5.1 and 5.2).

**Comment by michoecho** [comment]
> Backported to next-5.3 ([b0d3dc5](https://github.com/scylladb/scylladb/commit/b0d3dc58c2a28b23315da05bf9b24b27bd3dc7d5)).
> 
> The backport to next-5.2 and next-5.1 wasn't clean. The conflict was just header files in test/boost/view_build_test.cc so I thought and fixed it but it turns out it uses header files (test/lib/key_utils.hh) which didn't yet exist in 5.1 or 5.2, so it won't build... (I briefly added a backport commit, and then dequeued it, sorry about the mess). So @michoecho please look into the tests and what header files you need for it (and how to avoid needing them) and prepare separate backport PRs (probably the same PR could work for both 5.1 and 5.2).

I see, thanks. I will prepare the PRs.

**Comment by denesb** [comment]
5.3 backport was dequeued as it breaks the build. @michoecho please prepare a backport PR for 5.3.

**Comment by michoecho** [comment]
Done. I prepared backport PRs for all branches.

**Comment by nyh** [comment]
> Done. I prepared backport PRs for all branches:
> 
>     * [[backport 5.1] view: fix range tombstone handling on flushes in view_updating_consumer #14621](https://github.com/scylladb/scylladb/pull/14621)
> 
>     * [[backport 5.2] view: fix range tombstone handling on flushes in view_updating_consumer #14619](https://github.com/scylladb/scylladb/pull/14619)
> 
>     * [[backport 5.3] view: fix range tombstone handling on flushes in view_updating_consumer #14622](https://github.com/scylladb/scylladb/pull/14622)

Thanks, all of these are now merged to the respective "next" branches, let's see that they promote and then we can remove all the backport-candidate tag from this issue.

**Comment by denesb** [comment]
Promotions were successful, removed the backport labels.
