### ISSUE TITLE
SELECT CAST column names should match Cassandra's

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14508]
When doing a `SELECT CAST(b AS int)`, Cassandra returns a column named `cast(b as int)`.
An application may depend on this specific column name to look at the results.
Currently, Scylla uses a different name - `system.castasint(b)`. For Cassandra compatibility, we should switch to the same name that Cassandra uses

@avikivity recently did the same for the `token` function to print exactly the same string as Cassandra prints for column names - see `operator<<` in  `cql3/expr/expression.cc`, the `is_token_function` (and we have a for_metadata case). 

Reproduced by a translated Cassandra unit test:
* `cassandra_tests/functions/cast_fcts_test.py`::`testNumericCastsInSelectionClause`.

I don't know if this name was a recent regression from the expressions rewrite, or we always used this different name. If we always used the different name, switching to Cassandra's may cause backward compatibility with our own old versions, so I don't know what to suggest (I think even in this case it's better to move towards Cassandra compatibility).

**Comment by avikivity** [comment]
Probably better to move towards compatibility (as the Cassandra name is better).

**Comment by avikivity** [comment]
This increases compatibility with Cassandra, but generates incompatibility with older versions of ScyllaDB, so I don't it's a good idea for a patch release.
