### ISSUE TITLE
CAST from timestamp to string not same as Cassandra on zero milliseconds

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14518]
This issue was previously noted in the discussion on pull request https://github.com/scylladb/scylladb/issues/13588 and in issue #7997, but we didn't have a separate issue about this until now.

When x is a `timestamp` column, and we use `SELECT CAST(x AS text)`, the format of the output looks like ` 2017-12-27T11:57:42.500Z`

It turns out that if the millseconds part is zero (the timestamp is a whole second), Scylla drops the ".000Z" entirely - i.e., drops both the zero milliseconds **and** also the timezone part ("Z"). This makes little sense (why drop the timezone only on whole second) and incompatible with Cassandra.

The following translated Cassandra unit test reproduces this issue:
* `cassandra_tests/functions/cast_fcts_test.py`::`testTimeCastsInSelectionClause`

**Comment by denesb** [comment]
This is a minor compatibility improvement in CQL, which can even break clients, not backporting.
