### ISSUE TITLE
raft: INFO level log when a server gains or loses leadership

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14524]
Gaining/losing leadership is a relatively rare event; it is certainly rare when we have a smoothly working network, and even if not, leadership changes should happen only once in 1-2 seconds at most (based on our current failure detector settings).

But it's sometimes useful to know that this happened for the purposes of debugging. Ref: #14257 for example where they would have been useful and saved some debugging time.

I propose we log these events at INFO level.

cc @tgrabiec

**Comment by kbr-scylla** [comment]
@piodul @patjed41 consider this

**Comment by kbr-scylla** [comment]
@gleb-cloudius regarding your comment (https://github.com/scylladb/scylladb/pull/14877#discussion_r1279043583)

A node becoming a topology coordinator is different than it becoming a leader, these events are not happening at the same time (one triggers the other after a while) and if there's a bug it could even happen that e.g. a node that is a leader doesn't become a topology coordinator -- then leadership event logs could help debugging such an issue.

I think it's valuable to have these logs.

@kostja WDYT?

**Comment by kbr-scylla** [comment]
These logs are even more useful when we don't have the topology coordinator.

**Comment by kbr-scylla** [comment]
@gleb-cloudius see https://github.com/scylladb/scylladb/issues/14257 for an example where leadership failover events would have been useful for debugging and potentially saved us time (and there was no topology coordinator).

**Comment by kbr-scylla** [comment]
> It is a library. It should not print logs by default if everything is normal.

I don't see the implication.

> But how anybody wating the log suppose to know what fsm is?

How the log looks like (whether it mentions "fsm" or not) is a different discussion from whether we want to have a log at all. We can implement a separate higher-level log for example "raft group 0 -- losing leadership" etc.

**Comment by kbr-scylla** [comment]
I agree that logging for Raft in general is too much (it will be too much once we have tablet raft groups), but just for group 0 it makes a lot of sense IMO.

**Comment by gleb-cloudius** [comment]
> > It is a library. It should not print logs by default if everything is normal.
> 
> I don't see the implication.

You do not? How our logs would look like if every library we use decided to print something there from time to time?

**Comment by gleb-cloudius** [comment]
> I agree that logging for Raft in general is too much (it will be too much once we have tablet raft groups), but just for group 0 it makes a lot of sense IMO.

OK, but the place you want to log is general for all groups.

**Comment by kbr-scylla** [comment]
Fixed by #14877 (not closed because the commit message didn't have `Fixes`)
