### ISSUE TITLE
internal_keyspace extention: enhance the semantics also to flushes (dirty_memory_manager)

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#14529]
Commit 7c8c020c0eced51071aa4f67674fde12f2dc69d7 introduced a new type of a keyspace, an internal keyspace:

It is said in the commit message:
>To be populated early by extensions. Such a keyspace should be
1.) Started before user keyspaces
2.) Flushed/closed after user keyspaces
3.) For all other regards be considered "user".

It should be extended also to:
4) should not compete with user keyspace for flushes

This is to prevent deadlocks,
The explanation, this extension was created in order to allow for "soft system_tables", which means that their schema as well
as the data is not local. The semantics didn't concern at all if flushes should compete with user tables of not.
pure system tables can be assumed not to compete with user table flushes thus if a specific user table flush would like to
force a system table flush as a condition to it's own flush it can do so without the fear of a deadlock that will be resulted if
the flush of the system table is serialized after the user table flush.
We actually do this in enterprise in tables that are encrypted using `replicated_key_provider` and we indeed deadlock since
internal keyspaces **does** compete with user table flushes.

Since they are considered to be a "high priority keyspaces" anyway we should extend the semantics as aforementioned above.
I am also labeling it as a bug since this missing additional semantic causes us a real deadlock in `replicated_key_provide`.

**Comment by denesb** [comment]
Backport to 2023.1 queued as 0954c5d18d998b90213589d32b35f54f5e81a2a9.
@elcallio do any other versions need this?

**Comment by denesb** [comment]
> Backport to 2023.1 queued as 0954c5d18d998b90213589d32b35f54f5e81a2a9. @elcallio do any other versions need this?

Dequeued, breaks the build.

**Comment by mykaul** [comment]
> > Backport to 2023.1 queued as 0954c5d18d998b90213589d32b35f54f5e81a2a9. @elcallio do any other versions need this?
> 
> Dequeued, breaks the build.

@eliransin - who's looking at this?

**Comment by eliransin** [comment]
> > > Backport to 2023.1 queued as 0954c5d18d998b90213589d32b35f54f5e81a2a9. @elcallio do any other versions need this?
> > 
> > 
> > Dequeued, breaks the build.
> 
> @eliransin - who's looking at this?

I will look at this, missed the fact it breaks 2023.1

**Comment by elcallio** [comment]
Where is the broken build?

**Comment by eliransin** [comment]
This is in 2023.1 (I am not sure about the dequing...)
scylladb/scylla-enterprise@308d41be02c405abac608e113fc7f9af8417e362

Also - we have https://github.com/scylladb/scylla-enterprise/issues/3334 to manage 2023.1 backport of this patch.
I think this issue can be closed.
