### ISSUE TITLE
[Debian 12] Build From Source

### ISSUE THREAD

**Issue by TheHellTower** [scylladb/scylladb#14549]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Not installed
Cluster size: 0
OS: Debian 12

Platform: WSL

Hello, I'm trying to [Build from Source](https://www.scylladb.com/download/?platform=source#open-source) but I got the following errors:

<details>
    <summary>
        Logs "sudo ./install-dependencies.sh"
    </summary>

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
diffutils is already the newest version (1:3.8-4).
openssl is already the newest version (3.0.9-1).
openssl set to manually installed.
.....
Setting up xfsprogs (6.1.0-1) ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Setting up zlib1g-dev:amd64 (1:1.2.13.dfsg-1) ...
Setting up libhwloc-dev:amd64 (2.9.0-1) ...
...
Processing triggers for systemd (252.6-1) ...
Processing triggers for libc-bin (2.36-9) ...
ldconfig: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package openjdk-11-jdk-headless is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  openjdk-17-jre-headless

E: Package 'openjdk-11-jdk-headless' has no installation candidate
```

</details>

<details>
    <summary>
        Logs "sudo ./configure.py --mode=release"
    </summary>

```
Traceback (most recent call last):
  File "/home/tht/scylladb-setup/scylla/./configure.py", line 1462, in <module>
    level = optimization_level(args.cxx, modes[mode]["optimization-level"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tht/scylladb-setup/scylla/./configure.py", line 192, in __call__
    raise Exception(f'Unable to tell version of {cxx_compiler}')
Exception: Unable to tell version of clang++
```

</details>

```
clang++ --version
Debian clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Do you have ant idea ?

Best Regards,,
TheHelllTower.

**Comment by tchaikov** [comment]
we use java-11 for some of the tools implemented in java. they are not yet java-17 compatible. but as you found that, unfortunately, debian bookworm does not include java-11. but unstable does. 

so you want to continue using `install-dependencies.sh` for preparing the building / testing environment for scylladb, you would need to grab the deb package from [unstable](https://packages.debian.org/sid/openjdk-11-jre-headless) or install it from [oracle](https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html) . and install the deb package manually.

**Comment by TheHellTower** [comment]
> we use java-11 for some of the tools implemented in java. they are not yet java-17 compatible. but as you found that, unfortunately, debian bookworm does not include java-11. but unstable does.
> 
> so you want to continue using `install-dependencies.sh` for preparing the building / testing environment for scylladb, you would need to grab the deb package from [unstable](https://packages.debian.org/sid/openjdk-11-jre-headless) or install it from [oracle](https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html) . and install the deb package manually.

Thank you for this temporary solution in the worst case I got it working on debian 11 but yeah that would be better under debian 12 since WSL doesn't permit to downgrade(even thought it's for testing purposes it doesn't require VMs so it's easier)

I'll try this solution in the day then send details here if it's working or no !

Thanks !

**Comment by tchaikov** [comment]
no problem! 

and sorry, i missed the other problem you posted -- `configure.py` failed to identify the clang version. i just created #14566 in order to address it.

**Comment by TheHellTower** [comment]
> no problem!
> 
> and sorry, i missed the other problem you posted -- `configure.py` failed to identify the clang version. i just created #14566 in order to address it.

It doesn't matter that much for me I'm trying ScyllaDB to make kind of switches(depending on a user-choice user X or Y db system) but yeah I hope it will then help other users ! Do you think one day ScyllaDB will be usable on Debian 12 without additional steps ?

**Comment by tchaikov** [comment]
you can always run scylla in a docker.

**Comment by TheHellTower** [comment]
> you can always run scylla with docker / podman, etc.

Using docket on Debian  12 or you mean with Debian 11 ?

**Comment by tchaikov** [comment]
I think it does not matter that much anymore in the user space if one runs an application in the container . See https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/tips/best-practices-scylla-on-docker.html

**Comment by TheHellTower** [comment]
> I think it does not matter that much anymore in the user space if one runs an application in the container . See https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/tips/best-practices-scylla-on-docker.html

Thanks for all your answers and sorry for the inconvenience !
