### ISSUE TITLE
Temporary SSTables generated by incremental compaction are being incorrectly compacted

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14560]
SSTables containing GCable data, from input SSTable runs, are temporarily generated by incremental compaction, in order to allow space of input runs to be reclaimed earlier. Turns out compaction can pick those temporary SSTables while the compaction that created them is still ongoing. And those temporary are supposed to be deleted on compaction completion. They only reason they can be picked by compaction is if incremental compaction failed and then they become available. They cannot be deleted on failure because there might be a SSTable that wasn't exhausted by incremental compaction and has data shadowed by a GCable tombstone living in that temporary SSTable.

Manifests as follow:
```
sstable - Generating a new run identifier for SSTable /var/lib/scylla/data/.../me-370260-big-Data.db as overlapping was detected when inserting it into SSTable run 60cbdb02-d8b1-4c36-9666-75522cd0623a
compaction - [Compact ...] Compacting [/var/lib/scylla/data/.../me-370344-big-Data.db:level=0:origin=garbage_collection,/var/lib/scylla/data/.../me-370288-big-Data.db:level=0:origin=garbage_collection, ...
sstable - Unable to delete /var/lib/scylla/data/.../me-370260-big-TOC.txt because it doesn't exist.
```

It's not a correctness issue because another input SSTable, which overlaps in token with the temporary SSTable, will prevent the GCable tombstone from being purged, even though the temporary SSTable is being compacted in another job than the one that it was created at. That's because we don't purge a tombstone if there's a SSTable in the table that is possibly shadowed by that tombstone, which is done so to prevent data ressurrection. So we can say this is an inefficiency issue, which adds write amplification.

This problem happened because Compaction manager excludes SSTables from partial run using the run id, but turns out compaction is incorrectly using the same run id for both the temporary and the actual output runs. So an overlapping is introduced in the SSTable set, which causes Scylla to pick another run id for the temporary SSTables. As manager filters out compacting by run id, it incorrectly allows the temporary to be picked by regular compaction, which causes the problem.
This exposes an inefficiency in how we exclude those partial SSTable runs from being selected. 
The compaction which generate the temporary SSTable will later be unable to delete it, because it was deleted by another compaction first.

Can be easily fixed by registering those output runs with compacting_sstable_registration, meaning that partial runs will be unavailable for compaction until the latter completes.

**Comment by raphaelsc** [comment]
FYI @bhalevy

**Comment by bhalevy** [comment]
@tchaikov please look into this.

Cc @raphaelsc

**Comment by mykaul** [comment]
@tchaikov - any updates? This is a very high priority item for us.

**Comment by tchaikov** [comment]
> SSTables containing GCable data, from input SSTable runs, are temporarily generated by incremental compaction, in order

@raphaelsc what do you mean by "incremental" compaction? does it imply the ICS? if yes, shall this issue only manifest in scylladb enterprise ?

**Comment by tchaikov** [comment]
> @tchaikov - any updates? This is a very high priority item for us.

@mykaul Yaniv, no update so far. i am still trying to understand the issue.

**Comment by mykaul** [comment]
> > @tchaikov - any updates? This is a very high priority item for us.
> 
> @mykaul Yaniv, no update so far. i am still trying to understand the issue.

Thanks - please prioritize it. We have customers impacted by this most likely.

**Comment by tchaikov** [comment]
sure thing, i just realized that it's my P1 issue yesterday afternoon.

**Comment by bhalevy** [comment]
> > SSTables containing GCable data, from input SSTable runs, are temporarily generated by incremental compaction, in order
> 
> @raphaelsc what do you mean by "incremental" compaction? does it imply the ICS? if yes, shall this issue only manifest in scylladb enterprise ?

@tchaikov incremental compaction started with LCS so it's available in the oss version as well.
ICS uses the same technique, but it applied different higher level logic determining which sstables to compact, and that is based on STCS.

As for this particular issue, it's possible that it is manifested only with ICS, but the code infrastructure is in oss so the fix needs to arrive here.

Maybe you should reproduce the issue with scylla-enterprise and develop the fix there, and from that derive the part that needs to go to master (hopefully it will be the entire fix)

**Comment by tchaikov** [comment]
@raphaelsc hi Raphael, i am trying to demostrate the problem using the sequence diagram below. does it make sense? 

```mermaid
sequenceDiagram
    participant c1 as compaction job A
    participant ts as a gc-only SSTable
    participant is as input SSTables of job A
    participant os as output SSTables of job A
    participant c2 as compaction job B
    loop until compaction completes
        c1 ->>+ is: compacts
        c1 ->>+ os: creates with a new run id 0x42
        c1 ->>+ ts: creates with the same run id 0x42.. ehh, overlapped, let's use 0x43 instead
        critical on failure
        option still being used, as it shadows some data in a partially consumed sstable
            c1 --> ts: hmm, don't remove it yet
        option not being used
            c1 --> ts: remove it
        end
        c2 ->> ts: wrongly picks up for compaction as 0x43 is not being compacted
        ts ->>- c1: removed
        is ->>- c1: compaction done
        os ->>- c1: compaction done
    end
```

**Comment by tchaikov** [comment]
@raphaelsc  i still don't quite follow on one thing in your analysis

>  sstable - Generating a new run identifier for SSTable /var/lib/scylla/data/.../me-370260-big-Data.db as overlapping was detected when inserting it into SSTable run 60cbdb02-d8b1-4c36-9666-75522cd0623a

IIUC, the temporary (gc-only) table is assigned with a new run id here. but we only insert sstables specified by `compaction_descriptor` into the current input sstable set in `compaction::setup()`. while the gc-only sstables are created by the `compacted_fragments_writer`, which is in turn created by `compacted_fragments_writer()`. and the one which actually creates the temporary tables is the retval of `create_gc_compaction_writer()`, where we pass the `this->_run_identifier` down to `sstable::get_writer()`, so i think the temporary table should *always* share the same run identifier with the current compaction task, right?

but i have a hypothesis which might be able to explain why the temporary sstables ends up having a different run id:

1. compaction job A created a gc-only sstable α with its own run id
2. and α gets added to the main set of the compaction group somehow (i haven't found the proof in the source code yet, though).
3. the job A failed. 
4. compaction manager retried job A.
5. job A setup itself by adding the filtered sstables in its main set to the compaction descriptor.  sstable α is also in the club. but since it overlaps with the token range, it is assigned with a new run id different from the one representing job A.
6. since then, ssstable α is an "orphaned" sstable.
7. it is picked up by a regular compaction .

**Comment by raphaelsc** [comment]
> @raphaelsc i still don't quite follow on one thing in your analysis
> 
> > sstable - Generating a new run identifier for SSTable /var/lib/scylla/data/.../me-370260-big-Data.db as overlapping was detected when inserting it into SSTable run 60cbdb02-d8b1-4c36-9666-75522cd0623a
> 
> and
> 
> > This problem happened because Compaction manager excludes SSTables from partial run using the run id, but turns out compaction is incorrectly using the same run id for both the temporary and the actual output runs. So an overlapping is introduced in the SSTable set, which causes Scylla to pick another run id for the temporary SSTables.
> 
> IIUC, the temporary (gc-only) table is assigned with a new run id here. but we only insert sstables specified by `compaction_descriptor` into the current input sstable set in `compaction::setup()`. while the gc-only sstables are created by the `compacted_fragments_writer`, which is in turn created by `compacted_fragments_writer()`. and the one which actually creates the temporary tables is the retval of `create_gc_compaction_writer()`, where we pass the `this->_run_identifier` down to `sstable::get_writer()`, so i think the temporary table should _always_ share the same run identifier with the current compaction task, right?
> 
> but i have a hypothesis which might be able to explain why the temporary sstables ends up having a different run id:
> 
> 1. compaction job A created a gc-only sstable α with its own run id
> 2. and α gets added to the main set of the compaction group somehow (i haven't found the proof in the source code yet, though).
> 3. the job A failed.
> 4. compaction manager retried job A.
> 5. job A setup itself by adding the filtered sstables in its main set to the compaction descriptor.  sstable α is also in the club. but since it overlaps with the token range, it is assigned with a new run id different from the one representing job A.
> 6. since then, ssstable α is an "orphaned" sstable.
> 7. it is picked up by a regular compaction .

That's exactly how it happens. One caveat though. Note that sstable_set is also used by replica::table, so it could be that table itself generated a new run id for the SSTable which introduced overlapping.

So what we need to do is the following:

Guarantee that those SSTables created with create_gc_compaction_writer() will always pick a different run id. As they  belong to a conceptually different sstable run anyway. Patch compaction manager to register partial output SSTables into set of compacting SSTables (which prevent further compaction work from touching them). Please see compaction_manager::task::compact_sstables() and compacting_sstable_registration. Therefore, we prevent regular compaction from picking those SSTables for the lifetime of compaction process that generated them. On success, compaction removes those temporary SSTable(s) from table's sstable set, so they cannot be selected anymore.

**Comment by tchaikov** [comment]
> > @raphaelsc i still don't quite follow on one thing in your analysis
> > > sstable - Generating a new run identifier for SSTable /var/lib/scylla/data/.../me-370260-big-Data.db as overlapping was detected when inserting it into SSTable run 60cbdb02-d8b1-4c36-9666-75522cd0623a
> > 
> > 
> > and
> > > This problem happened because Compaction manager excludes SSTables from partial run using the run id, but turns out compaction is incorrectly using the same run id for both the temporary and the actual output runs. So an overlapping is introduced in the SSTable set, which causes Scylla to pick another run id for the temporary SSTables.
> > 
> > 
> > IIUC, the temporary (gc-only) table is assigned with a new run id here. but we only insert sstables specified by `compaction_descriptor` into the current input sstable set in `compaction::setup()`. while the gc-only sstables are created by the `compacted_fragments_writer`, which is in turn created by `compacted_fragments_writer()`. and the one which actually creates the temporary tables is the retval of `create_gc_compaction_writer()`, where we pass the `this->_run_identifier` down to `sstable::get_writer()`, so i think the temporary table should _always_ share the same run identifier with the current compaction task, right?
> > but i have a hypothesis which might be able to explain why the temporary sstables ends up having a different run id:
> > 
> > 1. compaction job A created a gc-only sstable α with its own run id
> > 2. and α gets added to the main set of the compaction group somehow (i haven't found the proof in the source code yet, though).
> > 3. the job A failed.
> > 4. compaction manager retried job A.
> > 5. job A setup itself by adding the filtered sstables in its main set to the compaction descriptor.  sstable α is also in the club. but since it overlaps with the token range, it is assigned with a new run id different from the one representing job A.
> > 6. since then, ssstable α is an "orphaned" sstable.
> > 7. it is picked up by a regular compaction .
> 
> That's almost how it happens except that we don't need job A to fail. That's because a new job B can proceed in parallel to A and pick the gc-only SSTable that had a new run id generated for it. Also note that sstable_set is also used by replica::table, so it could be that table itself generated a new run id for the SSTable which introduced overlapping.
> 

than you @raphaelsc ! i see now. // i should have update my `compile_commands.json` first. my lsp server was looking at an out dated compiling database.

just realized we replace the main set with a better one, after exhausting one or more sstables. so in that case, we construct a new sstable set by inserting the sstables one after another. and the gc-only sstables are no exception, so they are assigned a different run id here. and then, the old main set is replaced with the new one.

> So what we need to do is the following:
> 
> Guarantee that those SSTables created with create_gc_compaction_writer() will pick a different run id. As they belong to a conceptually different sstable run anyway. Patch compaction manager to register partial output SSTables into set of compacting SSTables (which prevent further compaction work from touching them). Please see compaction_manager::task::compact_sstables() and compacting_sstable_registration. Therefore, we prevent regular compaction from picking those SSTables for the lifetime of compaction process that generated them. On success, compaction removes those temporary SSTable(s) from table's sstable set, so they cannot be selected anymore.

thank you! will create a PR.

**Comment by raphaelsc** [comment]
> > So what we need to do is the following:
> > Guarantee that those SSTables created with create_gc_compaction_writer() will pick a different run id. As they belong to a conceptually different sstable run anyway.
> 
> this might be difficult with #14725, i will see if there is an alternative to achieve this goal. may i learn what is the practical reason to have a different run id part from that "they belong to a conceptually different sstable run"?

Efficiency. The strategy for incremental compaction (ICS) groups sstables by run id. Physical sstables sharing the same id can be seen as logically the same sstable (as they don't overlap in token range). As you noticed, we generate a run id for a sstable that would cause overlap in a run. It could happen that it's not the GC-only sstable that is pushed out of the run, but actually the output (non temporary) sstable that belongs to the new run being created. So that sstable would be seen by ICS as a standalone one (as there are no others sharding the same id), and will have to climb up the LSM tree again, which translates into additional write amplification. We can pick a random UUID for GC-only sstables and use it for every new sstable created via create_gc_compaction_writer().

**Comment by tchaikov** [comment]
@raphaelsc now i understand it better. thank you for your help. the pull request has been updated.

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to all the active 5.x branches.

**Comment by denesb** [comment]
The fix is not trivial, I suggest we let it "cook" in master for a bit, before backporting.

**Comment by mykaul** [comment]
@roydahan - please share master test results when you have them.

**Comment by tchaikov** [comment]
i will prepare a backport tomorrow.

**Comment by roydahan** [comment]
> @roydahan - please share master test results when you have them.

master results of what?
What are the tests that are reproducing the issues?
What are the system tests that were run in order to verify it works in scale?
What are the system tests that were run to make sure there are no regressions?

**Comment by bhalevy** [comment]
> > @roydahan - please share master test results when you have them.
> 
> master results of what? What are the tests that are reproducing the issues? What are the system tests that were run in order to verify it works in scale? What are the system tests that were run to make sure there are no regressions?

@roydahan see conversation in https://github.com/scylladb/scylladb/issues/14560#issuecomment-1647777959, https://github.com/scylladb/scylladb/issues/14560#issuecomment-1649755557 and https://github.com/scylladb/scylladb/issues/14560#issuecomment-1649801593:
> I thought it should at least see one of the regular longevity runs that QA runs periodically (not sure when).

**Comment by tchaikov** [comment]
@roydahan i think the problem manifests as a performance issue, which was be observed when performing compactions with sstables containing garbage collected data (tombstones). if the "the regular longevity runs" is able to cover this specific user case, i think we should be able verify the change. if there are no regression from functionality or performance perspectives spotted with them, i think we should be safe.

**Comment by roydahan** [comment]
> @roydahan i think the problem manifests as a performance issue, which was be observed when performing compactions with sstables containing garbage collected data (tombstones). if the "the regular longevity runs" is able to cover this specific user case, i think we should be able verify the change. if there are no regressions from functionality or performance perspectives spotted with them, i think we should be safe.

Sounds like the regular longevity runs don't cover this scenario.
At lease as not something I can say in high certainty - not in terms of compaction performance nor with tombstones.

**Comment by DoronArazii** [comment]
Backported into 5.1 + 5.2
Removing labels.
