### ISSUE TITLE
compound_view::explode() uses bad format string

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#14577]
```c++
format("non-zero component divider found ({:d}) mid", format("0x{:02x}", composite::eoc_type(marker) & 0xff)));
```

format a `sstring` with `{:d}` will annoy fmtlib, and it will throw an exception in this case.

**Comment by denesb** [comment]
This is a minor fix for an error-path, but the risk is very low too. Backported to 5.2.
