### ISSUE TITLE
bad_request while waiting for task in test_compaction_task.py

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#14584]
`test_major_keyspace_compaction_task` fails in debug mode on task_manager/wait_task  with

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://127.62.26.9:10000/task_manager/wait_task/0f3037f2-2c94-47cf-9094-2653370d66a8
```

https://jenkins.scylladb.com/job/scylla-master/job/next/6227/

**Comment by denesb** [comment]
Test only fix, not backporting.
