### ISSUE TITLE
Docs: Upgrade from ScyllaDB 5.2 to 5.3

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#14581]

**Comment by annastuchlik** [comment]
The upgrade guide is already on branch-5.3: https://opensource.docs.scylladb.com/branch-5.3/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.3/upgrade-guide-from-5.2-to-5.3-generic.html

It requires some improvements, but I have a separate[ task](https://github.com/scylladb/scylladb/issues/13993) to do it.
Let me close this issue.
