### ISSUE TITLE
docs: document the "minimum_keyspace_rf" option

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#14598]
The `minimum_keyspace_rf` option was added to configure the lowest acceptable RF.
See https://github.com/scylladb/scylladb/commit/cdedc7905077ed94a3172759ab4f70af1013e061#commitcomment-121073446 for details.

Document and backport to branch-5.3 so that the documentation is in sync with the feature.

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
