### ISSUE TITLE
performance regression after extending statement scope guard

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#14590]
Bad commit: c42a91ec72

perf-simple-query --smp 1

 before:

216489.88 tps ( 61.1 allocs/op,  13.1 tasks/op,   43558 insns/op,        0 errors)
217708.69 tps ( 61.1 allocs/op,  13.1 tasks/op,   43542 insns/op,        0 errors)
219495.02 tps ( 61.1 allocs/op,  13.1 tasks/op,   43538 insns/op,        0 errors)
216863.84 tps ( 61.1 allocs/op,  13.1 tasks/op,   43567 insns/op,        0 errors)
218936.48 tps ( 61.1 allocs/op,  13.1 tasks/op,   43546 insns/op,        0 errors)

after:

201773.52 tps ( 63.1 allocs/op,  15.1 tasks/op,   44600 insns/op,        0 errors)
210875.48 tps ( 63.1 allocs/op,  15.1 tasks/op,   44558 insns/op,        0 errors)
210186.55 tps ( 63.1 allocs/op,  15.1 tasks/op,   44588 insns/op,        0 errors)
211021.76 tps ( 63.1 allocs/op,  15.1 tasks/op,   44569 insns/op,        0 errors)
208597.52 tps ( 63.1 allocs/op,  15.1 tasks/op,   44587 insns/op,        0 errors)

Two extra allocations, two extra tasks, 1k extra instructions, for something that is DDL only.

**Comment by kbr-scylla** [comment]
I'll revert the patch.

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> Two extra allocations, two extra tasks, 1k extra instructions, for something that is DDL only.

I'll investigate where two tasks are coming from, but the claim that it is DDL only is incorrect. We plan to move truncate and auth to group0 as well. Non of them are DDL but will require the same treatment.
