### ISSUE TITLE
Slight incompatibility of error path of size() function in condition expression

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14592]
The DynamoDB documentation for [the size() function](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html) in ConditionException claims that it requires a **path** parameter - `size(x)` and `size(#xyz)` work. If the data read from that path has a type that size() can't work on (e.g., an integer), the condition fails with `ConditionalCheckFailedException`.  So far so good, and Alternator behaves like DynamoDB in all these cases.

But it turns out that DynamoDB also allows size's parameter to be a **value** instead of a path - i.e., `size(:xyz)` works even thought it's not documented. If the value `:xyz` defined in `ExpressionAttributeValues` has a suitable type (e.g., a string) its size is defined and the condition using the size may pass. But if the value of `:xyz` has the wrong type (e.g., an integer), DynamoDB knows the error is in the query itself - not the data - and generates a `ValidationException`, with the error message: `Invalid ConditionExpression: Incorrect operand type for operator or function; operator or function: size, operand type: N`.

Trying to use `size(size(x))` also generates the same `ValidationException` - it's also a wrong type (size(x) is an integer, and size() can't be called on that) and known from the query - not from the data.

The importance of this issue is very minor - it's only about the appropriate error type in a case that is in any case erroneous. Alternator also allows `size(:xyz)` in cases where it's properly defined.

**Comment by denesb** [comment]
A minor, non-correctness improvement on the error path. Not backporting.
