### ISSUE TITLE
Handle TLS version of broken pipe same as "normal"

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylladb#14625]
See https://github.com/scylladb/scylla-enterprise/issues/2876

In generic_server.cc, we handle exceptions thrown by wire to check for broken pipes (ECONN etc).
These are treated with less verbosity, since they are less severe errors. 
However, TLS wire exceptions will translate to non-terminated session errors, which are _not_ handled,
leading to terrifying log messages when TLS connections are misused by clients.

**Comment by mykaul** [comment]
I think it's a useful fix to backport (but it is based on a Seastar change that we need as well)

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to active versions

**Comment by denesb** [comment]
Backported to 5.2 as 9a9b5b691dc5b8e00d425b60e8b35f6873e8d354 (seastar update) and 198297a08af6983e6e242ca31b3662de4c017873.
