### ISSUE TITLE
`locator::config::this_host_id` is never assigned after initial `null` assignment

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14638]
I noticed this in main.cc:
```cpp
            // The local node's host_id is updated after loading from system.local
            // or making a random one for a new node
            tm_cfg.topo_cfg.this_host_id = host_id::create_null_id();
```

But it seems `this_host_id` is never assigned to later.

I don't know what the consequences of this are, whether this is a bug or not.
@bhalevy please advise

**Comment by bhalevy** [comment]
That was intentional in 7d3384089aa1688c32712b32bc58a9ff80936cb0
Right @tgrabiec ?

**Comment by kostja** [comment]
Let's remove host_id from tm_cfg, it's redundant there. There is no host_id when it is created and the field is unused/overwritten anyway.

**Comment by bhalevy** [comment]
> But before [7d33840](https://github.com/scylladb/scylladb/commit/7d3384089aa1688c32712b32bc58a9ff80936cb0) we also didn't update `this_host_id`, unless I'm not seeing something. [7d33840](https://github.com/scylladb/scylladb/commit/7d3384089aa1688c32712b32bc58a9ff80936cb0) didn't remove any assignments to `this_host_id`.

True, the local host id is updated only later in the process in main.
Also in f3d5df54482e2867336d4b36b6a979e823c8c5ff the cfg `this_host_id` was used only by unit tests.

It's ok for cql_test_env to follow a similar path like main.

> Let's remove host_id from tm_cfg, it's redundant there. There is no host_id when it is created and the field is unused/overwritten anyway.

I'm not sure if that's required or even easy enough to do for unit tests.

**Comment by kbr-scylla** [comment]
> I'm not sure if that's required or even easy enough to do for unit tests.

In https://github.com/scylladb/scylladb/pull/14640 I changed the behavior of cql_test_env to be the same as main (i.e. we assign null and end at that)... and the tests still pass.

So it looks like `this_host_id` in `topology` is completely unnecessary.

**Comment by kbr-scylla** [comment]
I checked what happens when I remove all assignments of `this_host_id` from network_topology_strategy_test, locator_topology_test, token_metadata_test.

The tests are still passing.

**Comment by bhalevy** [comment]
I guess that @tgrabiec's changed around topology::node `this_node` not having to be first node to be inserted allow us to manage without cfg `this_host_id`.
I'm fine with dropping it if it's not required.

**Comment by kbr-scylla** [comment]
BTW. @BorishuV why are you adding items that are assigned to Kostja's team members, to the Storage team?
