### ISSUE TITLE
sstable_compaction_test: sstable_expired_data_ratio a table created twice

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#14657]
Working on a per-table metrics reporting, I've hit the following issue.
During the test, 
test/boost/sstable_compaction_test: sstable_expired_data_ratio

The following table is created twice without being deleted:
cf = tombstone_purge
ks = tests

Not sure if it affects the test correctness. It's not something that should happen. But it does crash when per-table metrics are enabled.

**Comment by bhalevy** [comment]
> @bhalevy - does that belong to your team?

yes.  @tchaikov can you please look into this?

**Comment by denesb** [comment]
Test only fix, not backporting.
