### ISSUE TITLE
boost.group0_test.test_group0_history_clearing_old_entries is flaky

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#14653]
https://jenkins.scylladb.com/job/scylla-master/job/next/6248/artifact/testlog/x86_64/debug/boost.group0_test.test_group0_history_clearing_old_entries.2.log

`test/boost/group0_test.cc(150): fatal error: in "test_group0_history_clearing_old_entries": critical check timestamps2.size() == timestamps1.size() - older_by_sleep_dur + 1 has failed [8 != 9]`

**Comment by bhalevy** [comment]
Hit in https://jenkins.scylladb.com/job/scylla-5.2/job/next/230/artifact/testlog/x86_64/debug/[…]group0_test.test_group0_history_clearing_old_entries.3.log
```
test/boost/group0_test.cc(150): fatal error: in "test_group0_history_clearing_old_entries": critical check timestamps2.size() == timestamps1.size() - older_by_sleep_dur + 1 has failed [7 != 8]
```

**Comment by mykaul** [comment]
@DoronArazii - an example where we need to expedite a backport to fix CI stability.

**Comment by DoronArazii** [comment]
Backported to 5.2
Removing labels.
