### ISSUE TITLE
database::add_column_family isn't exception safe

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#14666]
In `database::add_column_family` if emplace on `_column_families` or ` _ks_cf_to_uuid` throws, the previous operations are not undone, leaving inconsistent data related to column families. 

```
  ks.add_or_update_column_family(schema);
  cf->start();
  schema->registry_entry()->set_table(cf->weak_from_this());
  _column_families.emplace(uuid, std::move(cf));
  _ks_cf_to_uuid.emplace(std::move(kscf), uuid);
```

**Comment by avikivity** [comment]
Unlikely to impact users, not backporting
