### ISSUE TITLE
Increase schema commitlog default segment size

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#14668]
We implemented schema commitlog and effectively made it mandatory starting from Scylla 5.2, when consistent_cluster_managent: true became the default. 

The main value of a separate schema commitlog is to reduce write amplification of changes to system tables and raft tables, as well as have an ability to set independent commitlog sync properties for these writes (i.e. syncing a schema commitlog write is not flushing the data commit log).

However, we left the default segment size in schema commit log the same as in data commit logs. The segment size puts a limit on the size of mutation that can be written at once, and some schema mutation writes are known to be much larger than average (see https://github.com/scylladb/scylladb/issues/13864)

Given schema commit log is now separate we can have a much larger default segment size for it, thus alleviating the limit hit in #13864.

Let's introduce a new scylla.yaml variable, **schema_commitlog_segment_size**.
Let's have the default for schema_commitlog_segment_size for schema set to 128MB, it is 4x to the default in data commitlog (32MB).

Let's avoid deriving commitlog_sync_period_in_ms for schema_commitlog. Schema commit log runs in batch mode, so doesn't need this parameter at all.

**Comment by mykaul** [comment]
What happens when someone upgrades from 5.2?

**Comment by kostja** [comment]
The new defaults begin to apply. For commitlog, this doesn't require an upgrade.

**Comment by kbr-scylla** [comment]
@kostja @avikivity @mykaul I backported this to branch 5.2.

This is because -- as I described in https://github.com/scylladb/scylladb/issues/13864#issuecomment-1662277980 -- introducing schema commitlog and related changes caused us to start hitting commitlog size limits when transferring snapshots. The test in #13864 ran on 2023.1 which is based on 5.2. Hitting the limit was apparently a blocker for 2023.1 release and we need this workaround (cc @DoronArazii )

**Comment by avikivity** [comment]
btw2, we should set a hard limit for the schema commitlog so it doesn't grow too much.

**Comment by kbr-scylla** [comment]
Replaced the backport with just 4cd58477613459c5a71cc0f4cb63bc06af89b88e

**Comment by avikivity** [comment]
What's the point? Now it has no effect.

**Comment by kbr-scylla** [comment]
The user now has the option to increase the segment size for schema commitlog if they hit the limit.
So we don't increase it by default, but we give the option to increase it if necessary.

**Comment by avikivity** [comment]
The user has no idea about this problem. So the scenario is disaster -> call for help -> change the configuration -> restart -> possibly a recovery.
