### ISSUE TITLE
topology_experimental_raft.test_topology_ops is flaky

### ISSUE THREAD

**Issue by margdoc** [scylladb/scylladb#14679]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2446/artifact/testlog/x86_64/release/topology_experimental_raft.test_topology_ops.1.log

```
=================================== FAILURES ===================================
______________________________ test_topology_ops _______________________________

request = <FixtureRequest for <Function test_topology_ops>>
manager = <test.pylib.manager_client.ManagerClient object at 0x7f6515e73c10>

    @pytest.mark.asyncio
    async def test_topology_ops(request, manager: ManagerClient):
        """Test basic topology operations using the topology coordinator."""
        logger.info("Bootstrapping first node")
        servers = [await manager.server_add()]
    
        logger.info(f"Restarting node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
        await manager.server_start(servers[0].server_id)
    
        logger.info("Bootstrapping other nodes")
        servers += [await manager.server_add(), await manager.server_add()]
    
        logger.info(f"Restarting node {servers[0]} when other nodes have bootstrapped")
        await manager.server_stop_gracefully(servers[0].server_id)
        await manager.server_start(servers[0].server_id)
    
        logger.info(f"Stopping node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
    
        logger.info(f"Replacing node {servers[0]}")
        replace_cfg = ReplaceConfig(replaced_id = servers[0].server_id, reuse_ip_addr = False, use_host_id = False)
        servers = servers[1:] + [await manager.server_add(replace_cfg)]
>       await check_token_ring_and_group0_consistency(manager)

test/topology_experimental_raft/test_topology_ops.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology/util.py:71: in check_token_ring_and_group0_consistency
    group0_members = await get_current_group0_config(manager, srv)
test/topology/util.py:52: in get_current_group0_config
    host = (await wait_for_cql_and_get_hosts(manager.cql, [srv], time.time() + 60))[0]
test/pylib/util.py:79: in wait_for_cql_and_get_hosts
    await asyncio.gather(*(wait_for_cql(cql, h, deadline) for h in hosts))
test/pylib/util.py:58: in wait_for_cql
    await wait_for(cql_ready, deadline)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_cql.<locals>.cql_ready at 0x7f6515f523e0>
deadline = 1689180082.963028, period = 1

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float, period: float = 1) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:43: AssertionError
```

**Comment by bhalevy** [comment]
@DoronArazii should this issue be prioritized as P1 as well, like https://github.com/scylladb/scylladb/issues/14752?

**Comment by xemul** [comment]
Very similar hit on https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2726/artifact/testlog/x86_64/debug/topology.test_replace.1.log

**Comment by Annamikhlin** [comment]
similar issue seems on: https://jenkins.scylladb.com/job/scylla-master/job/build/1561/artifact/testlog/aarch64/debug/topology_experimental_raft.test_topology_ops.1.log
```
test/topology_experimental_raft/test_topology_ops.py:80: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology/util.py:71: in check_token_ring_and_group0_consistency
    group0_members = await get_current_group0_config(manager, srv)
test/topology/util.py:53: in get_current_group0_config
    await read_barrier(manager.cql, host)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cql = <cassandra.cluster.Session object at 0xffff7e3c40d0>
host = <Host: 127.188.213.39:9042 datacenter1>

    async def read_barrier(cql: Session, host: Host):
        """To issue a read barrier it is sufficient to attempt dropping a
        non-existing table. We need to use `if exists`, otherwise the statement
        would fail on prepare/validate step which happens before a read barrier is
        performed.
        """
>       await cql.run_async("drop table if exists nosuchkeyspace.nosuchtable", host = host)
E       cassandra.OperationTimedOut: errors={'127.188.213.39:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.188.213.39:9042

test/pylib/util.py:123: OperationTimedOut
```

**Comment by DoronArazii** [comment]
@kostja / @kbr-scylla please update if this is in progress - it's failing master.

**Comment by tchaikov** [comment]
a new one: https://jenkins.scylladb.com/job/scylla-master/job/next/6367/testReport/(root)/test_topology_ops/Tests___Unit_Tests___test_topology_ops/

```
    @pytest.mark.asyncio
    async def test_topology_ops(request, manager: ManagerClient):
        """Test basic topology operations using the topology coordinator."""
        logger.info("Bootstrapping first node")
        servers = [await manager.server_add()]
...
        servers = servers[1:] + [await manager.server_add(replace_cfg)]
>       await check_token_ring_and_group0_consistency(manager)

test/topology_experimental_raft/test_topology_ops.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

manager = <test.pylib.manager_client.ManagerClient object at 0x7f0be826a690>

    async def check_token_ring_and_group0_consistency(manager: ManagerClient) -> None:
        """Ensure that the normal token owners and group 0 members match
           according to each currently running server.
        """
        servers = await manager.running_servers()
        for srv in servers:
            group0_members = await get_current_group0_config(manager, srv)
            group0_ids = {m[0] for m in group0_members}
            token_ring_ids = await get_token_ring_host_ids(manager, srv)
>           assert token_ring_ids == group0_ids
E           AssertionError
```

**Comment by bhalevy** [comment]
> a new one: https://jenkins.scylladb.com/job/scylla-master/job/next/6367/testReport/(root)/test_topology_ops/Tests___Unit_Tests___test_topology_ops/
> 
> ```
>     @pytest.mark.asyncio
>     async def test_topology_ops(request, manager: ManagerClient):
>         """Test basic topology operations using the topology coordinator."""
>         logger.info("Bootstrapping first node")
>         servers = [await manager.server_add()]
> ...
>         servers = servers[1:] + [await manager.server_add(replace_cfg)]
> >       await check_token_ring_and_group0_consistency(manager)
> 
> test/topology_experimental_raft/test_topology_ops.py:48: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> manager = <test.pylib.manager_client.ManagerClient object at 0x7f0be826a690>
> 
>     async def check_token_ring_and_group0_consistency(manager: ManagerClient) -> None:
>         """Ensure that the normal token owners and group 0 members match
>            according to each currently running server.
>         """
>         servers = await manager.running_servers()
>         for srv in servers:
>             group0_members = await get_current_group0_config(manager, srv)
>             group0_ids = {m[0] for m in group0_members}
>             token_ring_ids = await get_token_ring_host_ids(manager, srv)
> >           assert token_ring_ids == group0_ids
> E           AssertionError
> ```

https://github.com/scylladb/scylladb/pull/14983 ?

**Comment by tchaikov** [comment]
@bhalevy hi Benny, yeah, they are checking the same condition. but somehow `test_topology_ops` insists that the condition should evaluates to true when the new node joins the cluster. while `wait_for_token_ring_and_group0_consistency` is more tolerant -- it sets a deadline.

**Comment by bhalevy** [comment]
Cc @kbr-scylla

**Comment by avikivity** [comment]
Seen again in https://github.com/scylladb/scylladb/pull/14998.

**Comment by kbr-scylla** [comment]
I'm investigating this now.

**Comment by kbr-scylla** [comment]
Everybody's posting somewhat related failures and now there are three different issues reported in this single GitHub issue, it's kind of hard to manage and annoying.

The original post describes a timeout in `wait_for_cql_and_get_hosts`, we failed to query the node for too long (the function tries to query `system.local` to check availability).
This failure does not seem to appear any more in CI (I checked multiple builds), I don't have an idea what might have caused it and I couldn't reproduce. Therefore I want to close this issue, I don't see a point in keeping it open. The logs are gone. The next time it appears (if it does), we need to save the logs so they are available for analysis.

This post: https://github.com/scylladb/scylladb/issues/14679#issuecomment-1655428672 is a completely different failure. We already have a separate issue for it (two even): https://github.com/scylladb/scylladb/issues/14885 and https://github.com/scylladb/scylladb/issues/14975. There's a fix ready: https://github.com/scylladb/scylladb/pull/15009

This post: https://github.com/scylladb/scylladb/issues/14679#issuecomment-1667425500 is yet another different failure. It's a timeout when trying to execute `drop table if exists nosuchkeyspace.nosuchtable` query (which involves group 0). There we have the logs. I'm going to open a separate GH issue for it.

This post: https://github.com/scylladb/scylladb/issues/14679#issuecomment-1670736073 is another instance of https://github.com/scylladb/scylladb/issues/14885 and https://github.com/scylladb/scylladb/issues/14975.

This: https://github.com/scylladb/scylladb/issues/14679#issuecomment-1672114337 is also an instance of https://github.com/scylladb/scylladb/issues/14885 and https://github.com/scylladb/scylladb/issues/14975. It's unrelated to the original post.

As described in the second paragraph, I'm closing this issue.

For the future, I have a request to everyone who posted -- take a glance at the logs, compare, see if it's actually the same issue or something different, if it's different open another GH issue (or looks for existing one which is actually the same failure).

**Comment by kbr-scylla** [comment]
> This post: https://github.com/scylladb/scylladb/issues/14679#issuecomment-1667425500 is yet another different failure. It's a timeout when trying to execute drop table if exists nosuchkeyspace.nosuchtable query (which involves group 0). There we have the logs. I'm going to open a separate GH issue for it.

As promised: https://github.com/scylladb/scylladb/issues/15013

**Comment by yaronkaikov** [comment]
Test failed again in https://jenkins.scylladb.com/job/scylla-master/job/build/1605/testReport/junit/(root)/non-boost%20tests/Build__Test__Publish___buildTestPublishArm___topology_experimental_raft_test_topology_ops_debug_1/

@bhalevy @kostja , is it a different issue ?

**Comment by bhalevy** [comment]
> Test failed again in https://jenkins.scylladb.com/job/scylla-master/job/build/1605/testReport/junit/(root)/non-boost%20tests/Build__Test__Publish___buildTestPublishArm___topology_experimental_raft_test_topology_ops_debug_1/
> 
> @bhalevy @kostja , is it a different issue ?

https://jenkins.scylladb.com/job/scylla-master/job/build/1605/artifact/testlog/aarch64/debug/scylla-369.log
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==87827==ERROR: AddressSanitizer: SEGV on unknown address 0xfffffffffffffff8 (pc 0xffffa11fd174 bp 0xfffff7513350 sp 0xfffff7513350 T0)
==87827==The signal is caused by a READ memory access.
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

Looks like https://github.com/scylladb/scylladb/issues/15090
