### ISSUE TITLE
deadlock caused by view update _registration_sem and streaming reader _streaming_concurrency_sem

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#14676]
Consider

- 10 repair instances take all the 10 _streaming_concurrency_sem

- repair readers are done but the permits are not released since they
  are waiting for view update _registration_sem

- view updates trying to take the _streaming_concurrency_sem to make
  progress of view update so it could release _registration_sem, but it
  could not take _streaming_concurrency_sem since the 10 repair
  instances have taken them

- dead lock happens

**Comment by denesb** [comment]
A missing detail is that, upon reaching EOS, repair reader replaces the underlying (evictable) reader with an empty reader. The empty reader is not evictable, so the resources cannot be forcibly released.

**Comment by asias** [comment]
> A missing detail is that, upon reaching EOS, repair reader replaces the underlying (evictable) reader with an empty reader. The empty reader is not evictable, so the resources cannot be forcibly released.

You are right. Raphael and I looked the empty reader thing as well. 

In read_rows_from_disk, we call _repair_reader->pause() unconditionally. But when eos, the _reader_handle is reset, so pause() will not call _reader_handle->pause(). 

```
void repair_reader::pause() {
    _reader.set_timeout(db::no_timeout);
    if (_reader_handle) {
        _reader_handle->pause();
    }
}

future<> repair_reader::on_end_of_stream() noexcept {
    return _reader.close().then([this] {
        _reader = mutation_fragment_v1_stream(make_empty_flat_reader_v2(_schema, _permit));
        _reader_handle.reset();
    });     
}       
        
future<> repair_reader::close() noexcept {
    return _reader.close().then([this] {
        _reader_handle.reset();
    });
}
```

Since we pass _permit to the empty ready, does it make sense to let make_empty_flat_reader_v2 return a handler, so we can pause as well?

**Comment by denesb** [comment]
> Since we pass _permit to the empty ready, does it make sense to let make_empty_flat_reader_v2 return a handler, so we can pause as well?

The handler is specific to the evictable reader, it will not work with any other kind of reader.

**Comment by denesb** [comment]
Backported to 5.3, 5.2, 5.1 and 2022.1.
