### ISSUE TITLE
Gossiper state is absent after full cluster restart with consistent topology changes enabled

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#14675]
This manifests as a failure in  `test_cluster_features.test_joining_old_node_fails` (dev mode):

```
    
        # Wait until the feature is considered enabled by all nodes
        cql = manager.cql
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
        logging.info(f"Waiting until {TEST_FEATURE_NAME} is enabled on all nodes")
>       await asyncio.gather(*(wait_for_feature(TEST_FEATURE_NAME, cql, h, time.time() + 60) for h in hosts))

test/topology/test_cluster_features.py:141: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/util.py:129: in wait_for_feature
    await wait_for(feature_is_enabled, deadline)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_feature.<locals>.feature_is_enabled at 0x7f8540516160>
deadline = 1689170433.9396355, period = 1

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float, period: float = 1) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:43: AssertionError
```

The feature is not getting enabled as expected. The reason is that gossiper doesn't see that other nodes support it. 

One of the reasons is that endpoint states are not restored after restart. 

See that `loaded_endpoints` is empty:

```
INFO  2023-07-12 23:01:51,683 [shard 0] storage_service - initial_contact_nodes={127.49.130.4}, loaded_endpoints={}, loaded_peer_features=2

```

This was disabled in fd1b1279c4324bc06a2d7710edc55546e72b93a5.

This also manifests as the following warnings in logs (triggered from `gossiper::is_alive()`:
```
WARN  2023-07-12 23:02:54,868 [shard 0] gossip - unknown endpoint 127.49.130.2
WARN  2023-07-12 23:02:54,868 [shard 0] gossip - unknown endpoint 127.49.130.3
WARN  2023-07-12 23:02:54,868 [shard 0] gossip - unknown endpoint 127.49.130.2
WARN  2023-07-12 23:02:54,869 [shard 0] gossip - unknown endpoint 127.49.130.3
WARN  2023-07-12 23:02:54,869 [shard 0] gossip - unknown endpoint 127.49.130.2
```

Reloading of topology from system.topology calls `storage_service::update_peer_info()`, which doesn't insert endpoint state:

```
future<> storage_service::update_peer_info(gms::inet_address endpoint) {
    slogger.debug("Update peer info: endpoint={}", endpoint);
    using namespace gms;
    auto* ep_state = _gossiper.get_endpoint_state_for_endpoint_ptr(endpoint);
    if (!ep_state) {
        co_return;
    }
```

The node doesn't see anyone to gossip with, so it won't learn about other nodes (on node .4):
```
TRACE 2023-07-12 23:01:53,364 [shard 0] gossip - === Gossip round START
TRACE 2023-07-12 23:01:53,364 [shard 0] gossip - My heartbeat is now 22
DEBUG 2023-07-12 23:01:53,364 [shard 0] gossip - Set live nodes to talk: endpoint_state_map=1, all_live_nodes={}, endpoints_to_talk_with={}
DEBUG 2023-07-12 23:01:53,364 [shard 0] gossip - No live nodes yet: try initial contact point nodes={}
DEBUG 2023-07-12 23:01:53,364 [shard 0] gossip - No one to talk with
TRACE 2023-07-12 23:01:53,364 [shard 0] gossip - Performing status check ...
DEBUG 2023-07-12 23:01:53,365 [shard 0] gossip - failure_detector_loop: Wait until live_nodes={} is not empty
TRACE 2023-07-12 23:01:53,365 [shard 0] gossip - === Gossip round OK
```

The node initially gossips only with seeds. If seed pointers form a graph which connects all the nodes, they all should eventually learn about each other. That's how seeds are configured here. For example, node .2 has seeds=[.4, .3]. However, so it happens that when .2 restarts, .4 is too early in the boot process and fails the gossip exchange:

```
WARN  2023-07-12 23:01:51,124 [shard 0] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 127.49.130.4, application_states = {{STATUS, Value(NORMAL,869247220184916093,1)}})
```

Only exchange with .3  completes. Then later, gossip will use only that (live) node, and won't use the other seed:

```
DEBUG 2023-07-12 23:01:50,968 [shard 0] gossip - Talk to live nodes: {127.49.130.3, 127.49.130.4}
....
TRACE 2023-07-12 23:01:51,974 [shard 0] gossip - === Gossip round START
TRACE 2023-07-12 23:01:51,974 [shard 0] gossip - My heartbeat is now 27
DEBUG 2023-07-12 23:01:51,974 [shard 0] gossip - Talk to live nodes: {127.49.130.3}
TRACE 2023-07-12 23:01:51,974 [shard 0] gossip - Sending a GossipDigestSyn to 127.49.130.3:0 ...
TRACE 2023-07-12 23:01:51,975 [shard 0] gossip - Performing status check ...
DEBUG 2023-07-12 23:01:51,983 [shard 0] gossip - replicating live endpoints to other shards
TRACE 2023-07-12 23:01:51,986 [shard 0] gossip - === Gossip round OK
```

In general, it is not guaranteed that seeds will be up to date and reachable at the time of restart, so we shouldn't rely on that.

**Comment by tgrabiec** [comment]
For gossiper to function, we need to restore endpoint states from system.peers on boot. 

Do you have other ideas @gleb-cloudius @kbr-scylla ?

**Comment by kbr-scylla** [comment]
Endpoint states should be populated in the same way as they were initially populated -- through `topology_state_load()`, whether it's by `group0_state_machine::apply` or `group0_state_machine::load_snapshot`.

If I understand correctly, `topology_state_load()` should update `system.peers` **and** populate gossiper.

Another matter is that features should be moved to group 0 so they shouldn't  depend on gossiper being populated correctly -- but we should populate it correctly nevertheless.

**Comment by tgrabiec** [comment]
So this is a bug in storage_service::update_peer_info()?

Note that gossiper is still used for other things, like is_alive() status, and propagating hit ratio.

**Comment by gusev-p** [comment]
I tried this:
```
diff --git a/service/storage_service.cc b/service/storage_service.cc
index cc1910aec6..898e40859c 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -354,6 +354,16 @@ future<> storage_service::topology_state_load(cdc::generation_service& cdc_gen_s
             // Save tokens, not needed for raft topology management, but needed by legacy
             // Also ip -> id mapping is needed for address map recreation on reboot
             if (!utils::fb_utilities::is_me(ip)) {
+                // We don't load gossiper endpoint states in storage_service::join_cluster
+                // if _raft_topology_change_enabled. On the other hand gossiper is still needed
+                // even in case of _raft_topology_change_enabled mode, since it still contains part
+                // of the cluster state. To work correctly, the gossiper needs to know the current
+                // endpoints. We cannot rely on seeds alone, since it is not guaranteed that seeds
+                // will be up to date and reachable at the time of restart.
+                if (!_gossiper.get_endpoint_state_for_endpoint_ptr(ip)) {
+                    co_await _gossiper.add_saved_endpoint(ip);
+                }
+
                 // Some state that is used to fill in 'peeers' table is still propagated over gossiper.
                 // Populate the table with the state from the gossiper here since storage_service::on_change()
                 // (which is called each time gossiper state changes) may have skipped it because the tokens
```
but it doesn't help: this `add_saved_endpoint` adds some app_states with the current version and zero generation (before gossiper is started), but `do_send_ack2_msg` for some reason ignores generation, it uses `get_state_for_version_bigger_than` and refuses to send the proper states (including SUPPORTED_FEATURES) later to this endpoint.

More specifically, let the cluster has three nodes 127.169.90.3, 127.169.90.9, 127.169.90.11, consider the following scenario for 127.169.90.9:
* it has finished the shadow round and cleared the endpoints list in gossiper (`reset_endpoint_state_map` call);
* the raft started, applied the log, called `add_saved_endpoint` with `127.169.90.3`, now `get_max_endpoint_state_version` for it == 24;
* `SYN` comes from 127.169.90.11:
```
DEBUG 2023-07-18 10:20:35,252 [shard 0] gossip - Process gossip syn msg from node 127.169.90.11:0, syn_msg=cluster_id:ec9958f0-2543-11ee-beb9-6cb3110abd30,partioner:org.apache.cassandra.dht.Murmur3Partitioner,digests:{127.169.90.3:0:25 127.169.90.11:1689668433:32 127.169.90.9:0:21 }
...
TRACE 2023-07-18 10:20:35,253 [shard 0] gossip - examine_gossiper(): ep=127.169.90.3, remote=0.25, local=0.24
TRACE 2023-07-18 10:20:35,253 [shard 0] gossip - examine_gossiper(): requesting version > 24 from 127.169.90.3
```
* we send `ack` with `0.24` digest for `127.169.90.3` to `127.169.90.11` :
`DEBUG 2023-07-18 10:20:35,253 [shard 0] gossip - Calling do_send_ack_msg to node 127.169.90.11:0, syn_msg=cluster_id:ec9958f0-2543-11ee-beb9-6cb3110abd30,partioner:org.apache.cassandra.dht.Murmur3Partitioner,digests:{127.169.90.3:0:25 127.169.90.11:1689668433:32 127.169.90.9:0:21 }, ack_msg=digests:{127.169.90.11:1689668433:0 127.169.90.3:0:24 } ...`
* we receive this ack on `127.169.90.11`
`TRACE 2023-07-18 10:20:35,253 [shard 0] gossip - handle_ack_msg():from=127.169.90.9:0,msg=digests:{127.169.90.11:1689668433:0 127.169.90.3:0:24 } endpoint_state:{[127.169.90.9->HeartBeatState = { generation = 1689668433, version = 0 }, AppStateMap = { STATUS : Value(NORMAL,999761785711538314,14) }  { SCHEMA : Value(b322434f-da04-30c9-b11b-1a40986fa4ce,11) }  { DC : Value(datacenter1,18) }`, but before that `127.169.90.11` received ack from `127.169.90.3` for the same gossiper round, and its state already updated to `1689668433.32` with all the proper app_states.
* `127.169.90.11` finally start processing acks from `127.169.90.9`

`DEBUG 2023-07-18 10:20:35,298 [shard 0] gossip - Process gossip ack msg digests from node 127.169.90.9:0, ack_msg_digest={127.169.90.11:1689668433:0, 127.169.90.3:0:24}`
but it adds states only with bigger versions:
```
TRACE 2023-07-18 10:20:35,299 [shard 0] gossip - local heartbeat version 32 greater than 24 for 127.169.90.3
TRACE 2023-07-18 10:20:35,299 [shard 0] gossip - Adding state of 127.169.90.3, STATUS: NORMAL,6819628969185243942
TRACE 2023-07-18 10:20:35,299 [shard 0] gossip - Adding state of 127.169.90.3, RPC_READY: 1
TRACE 2023-07-18 10:20:35,299 [shard 0] gossip - Adding state of 127.169.90.3, VIEW_BACKLOG: 0:48444211:1689668434809
```
`SUPPORTED_FEATURES` has smaller version and will never be updated.

**Comment by gusev-p** [comment]
I'm not sure where specifically the problem is. I don't know why `do_send_ack2_msg` ignores the generation. If it were to use it like `examine_gossiper`, it would send all the app states in the scenario above, since `127.169.90.9` has zero generation for `127.169.90.3` and `127.169.90.11` already has `{ generation = 1689668433, version = 32 }`

On the other hand, maybe we should just user zero as a version in `add_saved_endpoint`.

**Comment by tgrabiec** [comment]
Does the gossip state eventually converge when the real current generation of .3 is gossiped around?

**Comment by tgrabiec** [comment]
I recall we saw issues with schema disagreement which existed in gossip but not in schema tables, maybe this could explain it.

**Comment by gusev-p** [comment]
> Does the gossip state eventually converge when the real current generation of .3 is gossiped around?

No, the real generation just overwrites zero without populating properties with lower versions.

**Comment by gusev-p** [comment]
Without the fix above I observe the problem how @tgrabiec described it: the third node sends `SYN` to the first node when its gossiper is not started yet, it [just ignores the SYN](https://github.com/scylladb/scylladb/blob/master/gms/gossiper.cc#L157) and sends no replies to the third node. Later, third node receives reply from the second, adds it to `live_nodes`, and never communicates with the third node again.

This problem reproduces with `experimental_features: [consistent-topology-changes]`, without `tablets`.

**Comment by gusev-p** [comment]
Cassandra also [ignores generation](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/gms/GossipDigestAckVerbHandler.java#L86) when in prepares ack2. Probably it's less of a problem for them since they most of the time (minus unreachable nodes) send only one `SYN` in one gossiper round, so there is less space for conflicts.

**Comment by avikivity** [comment]
experimental only, not backporting
