### ISSUE TITLE
`test_view_update_generator_register_semaphore_unit_leak` is failing in daily master builds

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14687]
Failing often since today morning, didn't see it once before.
A commit related to `view_update_generator` was merged yesterday: d3034e0fab9848a22f5abe598e0e91f51ffacc51
So it is most likely the cause.
@asias please investigate.

**Comment by kbr-scylla** [comment]
Revert was queued: 4cee8206f860ab776e570d45ee512045995e3fa9
cc @denesb

**Comment by denesb** [comment]
https://github.com/scylladb/scylladb/pull/14727 should allow for undoing the revert.

**Comment by denesb** [comment]
The revert was reverted, this issue should be solved. Can re-open if seen in the wild.
