### ISSUE TITLE
Reject LIMIT without any value

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#14705]
The CQL grammar allows to specify `LIMIT` or `PER PARTITION LIMIT` without any value.
Scylla should reject such queries.

On current Scylla the query fails on an internal type check, which is okayish, but on previous versions of Scylla it causes `on_internal_error`.

```cql
cqlsh:ks> CREATE TABLE tab (p int PRIMARY KEY);
cqlsh:ks> SELECT * FROM tab LIMIT 10;

 p
---

(0 rows)
cqlsh:ks> SELECT * FROM tab LIMIT;
InvalidRequest: Error from server: code=2200 [Invalid query] message="AND conjunction produces a boolean value, which doesn't match the type: org.apache.cassandra.db.marshal.Int32Type of [limit]"
cqlsh:ks> SELECT * FROM tab PER PARTITION LIMIT;
InvalidRequest: Error from server: code=2200 [Invalid query] message="AND conjunction produces a boolean value, which doesn't match the type: org.apache.cassandra.db.marshal.Int32Type of [limit]"
cqlsh:ks> 
```

We should update the grammar so that the parser rejects such queries.

Scylla version (or git commit hash):  `5.4.0~dev-0.20230714.033e5348aa82`

**Comment by avikivity** [comment]
Backported to 5.1, 5.2. 5.4 already has it.
