### ISSUE TITLE
OOM when starting a Centos8 ARM

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#14721]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

a Scylla installation (artifacts test) cannot start on Centos8 node ARM instance

## Impact

during the initialization process, node got OOM errors, and exited:
```
[  845.503965] Tasks state (memory values in pages):
[  845.504700] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[  845.506030] [    717]     0   717      558        0   393216      103         -1000 systemd-udevd
[  845.507400] [    718]     0   718     1465        0   393216      132         -1000 auditd
[  845.508679] [   2246]     0  2246      265        1   393216       67         -1000 sshd
[  845.509928] [  19879]     0 19879      161        0   327680       52         -1000 sedispatch
[  845.511258] [  27485]    81 27485      323        0   393216       67          -900 dbus-daemon
[  845.512599] [  28332]   991 28332    11331        0   458752       82             0 node_exporter
[  845.513970] [  28334]     0 28334     8771        1   458752       87             0 rsyslogd
[  845.515273] [  28352]  1000 28352      364        0   393216       87             0 systemd
[  845.516563] [  28363]     0 28363      348        0   393216       83             0 systemd-hostnam
[  845.517958] [  28398]     0 28398     3782        0   393216       81             0 nm-dispatcher
[  845.519327] [  28568]   991 28568 268441841   218275  2359296        0          -950 scylla
[  845.520616] [  28909]    74 28909      275        0   393216       86             0 sshd
[  845.521868] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/rsyslog.service,task=rsyslogd,pid=28334,uid=0
[  845.524188] Out of memory: Killed process 28334 (rsyslogd) total-vm:561344kB, anon-rss:0kB, file-rss:64kB, shmem-rss:0kB, UID:0 pgtables:448kB oom_score_adj:0
[  845.531814] Out of memory: Killed process 28352 (systemd) total-vm:23296kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:384kB oom_score_adj:0
[  845.566972] Out of memory: Killed process 28909 (sshd) total-vm:17600kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:74 pgtables:384kB oom_score_adj:0
[  845.572830] Out of memory: Killed process 28363 (systemd-hostnam) total-vm:22272kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:384kB oom_score_adj:0
[  845.638712] Out of memory: Killed process 28332 (node_exporter) total-vm:725184kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:991 pgtables:448kB oom_score_adj:0
[  845.678515] Out of memory: Killed process 28398 (nm-dispatcher) total-vm:242048kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:384kB oom_score_adj:0
[  845.687367] Out of memory: Killed process 28917 (systemd-cgroups) total-vm:896kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:320kB oom_score_adj:0
[  845.690287] Out of memory: Killed process 28919 (systemd-cgroups) total-vm:896kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:320kB oom_score_adj:0
[  845.714623] Out of memory: Killed process 28916 (systemd-cgroups) total-vm:896kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:320kB oom_score_adj:0
[  845.717485] Out of memory: Killed process 28918 (systemd-cgroups) total-vm:384kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:192kB oom_score_adj:0
[  845.743930] Out of memory: Killed process 28915 (systemd-cgroups) total-vm:384kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:192kB oom_score_adj:0
[  845.746582] Out of memory: Killed process 28914 (systemd-cgroups) total-vm:384kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:192kB oom_score_adj:0
[  845.752215] Out of memory: Killed process 28912 (systemd-cgroups) total-vm:384kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:192kB oom_score_adj:0
[  845.765337] Out of memory: Killed process 28568 (scylla) total-vm:17180277824kB, anon-rss:13937728kB, file-rss:44608kB, shmem-rss:0kB, UID:991 pgtables:2304kB oom_score_adj:-950
[  845.933864] Out of memory: Killed process 27485 (dbus-daemon) total-vm:20672kB, anon-rss:0kB, file-rss:0kB, shmem-rss:0kB, UID:81 pgtables:384kB oom_score_adj:-900
[  847.188291] systemd[1]: serial-getty@ttyS0.service: Service RestartSec=100ms expired, scheduling restart.
[  847.189966] systemd[1]: serial-getty@ttyS0.service: Scheduled restart job, restart counter is at 49.
[  847.191452] systemd[1]: NetworkManager.service: Service RestartSec=100ms expired, scheduling restart.
[  847.193014] systemd[1]: NetworkManager.service: Scheduled restart job, restart counter is at 49.
[  847.194456] systemd[1]: scylla-node-exporter.service: Service RestartSec=100ms expired, scheduling restart.
[  847.196086] systemd[1]: scylla-node-exporter.service: Scheduled restart job, restart counter is at 49.
[  847.197588] systemd[1]: rsyslog.service: Service RestartSec=100ms expired, scheduling restart.
[  847.199036] systemd[1]: rsyslog.service: Scheduled restart job, restart counter is at 49.
[  847.200681] systemd[1]: Stopped System Logging Service.
[  847.205446] systemd[1]: Starting System Logging Service...
```

## How frequently does it reproduce?

it failed on a run from July 16th, and it failed again on a run from today (July 17th)... i will try to rebuild it, but it seems to be quite constant

## Installation details

Cluster size: 1 nodes (im4gn.xlarge)

Scylla Nodes used in this run:
- artifacts-centos8-jenkins-db-node-917fa206-1 (52.212.53.121 | 10.4.3.218) (shards: 4)

OS / Image: `ami-08396399fcc3968ff` (aws: undefined_region)

Test: `artifacts-centos8-arm-test`
Test id: `917fa206-bd94-412c-8aec-51ccb8ba047b`
Test name: `scylla-master/artifacts/artifacts-centos8-arm-test`
Test config file(s):

- [centos8.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d53fc0b8bb8e4369cb3062d3fe604134f83e42f3/test-cases/artifacts/centos8.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 917fa206-bd94-412c-8aec-51ccb8ba047b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=917fa206-bd94-412c-8aec-51ccb8ba047b)
- Show all stored logs command: `$ hydra investigate show-logs 917fa206-bd94-412c-8aec-51ccb8ba047b`

## Logs:
- **db-cluster-917fa206.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/917fa206-bd94-412c-8aec-51ccb8ba047b/20230716_082755/db-cluster-917fa206.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/917fa206-bd94-412c-8aec-51ccb8ba047b/20230716_082755/db-cluster-917fa206.tar.gz)
- **sct-runner-events-917fa206.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/917fa206-bd94-412c-8aec-51ccb8ba047b/20230716_082755/sct-runner-events-917fa206.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/917fa206-bd94-412c-8aec-51ccb8ba047b/20230716_082755/sct-runner-events-917fa206.tar.gz)
- **sct-917fa206.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/917fa206-bd94-412c-8aec-51ccb8ba047b/20230716_082755/sct-917fa206.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/917fa206-bd94-412c-8aec-51ccb8ba047b/20230716_082755/sct-917fa206.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-centos8-arm-test/381/)
[Argus](https://argus.scylladb.com/test/5ce83d45-d72e-4847-9a0c-94a97f7a458e/runs?additionalRuns[]=917fa206-bd94-412c-8aec-51ccb8ba047b)
</details>

**Comment by mykaul** [comment]
What's the Scylla version used?

**Comment by fgelcer** [comment]
> What's the Scylla version used?

`https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/master/rpm/centos/2023-07-17T03:08:08Z/scylla.repo`
let me try to check if we do have the version format we print from Scylla binary

**Comment by fgelcer** [comment]
> What's the Scylla version used?

```
Scylla version 5.4.0~dev-0.20230717.567b4536892f with build-id aeddfeffed882ccadcef1106c18736e2200efba4
```

**Comment by avikivity** [comment]
A freshly started instance shows:

MemTotal:       15849216 kB
MemFree:        15136768 kB
MemAvailable:   13935680 kB


That's already below what we allocate to the server.

**Comment by avikivity** [comment]
I'm guessing it's related to 64k pages. @fgelcer did we get this on Ubuntu?

@xemul

**Comment by avikivity** [comment]
After changing min_free_kbytes to 60000 the thing starts.

**Comment by avikivity** [comment]
kernel-4.18.0-494.el8.aarch64

**Comment by avikivity** [comment]
Here's the calculation in current kernels (probably wasn't changed in the last century):

```c
/*
 * Initialise min_free_kbytes.
 *
 * For small machines we want it small (128k min).  For large machines
 * we want it large (256MB max).  But it is not linear, because network
 * bandwidth does not increase linearly with machine size.  We use
 *
 *      min_free_kbytes = 4 * sqrt(lowmem_kbytes), for better accuracy:
 *      min_free_kbytes = sqrt(lowmem_kbytes * 16)
 *
 * which yields
 *
 * 16MB:        512k
 * 32MB:        724k
 * 64MB:        1024k
 * 128MB:       1448k
 * 256MB:       2048k
 * 512MB:       2896k
 * 1024MB:      4096k
 * 2048MB:      5792k
 * 4096MB:      8192k
 * 8192MB:      11584k
 * 16384MB:     16384k
 */
void calculate_min_free_kbytes(void)
{
        unsigned long lowmem_kbytes;
        int new_min_free_kbytes;

        lowmem_kbytes = nr_free_buffer_pages() * (PAGE_SIZE >> 10);
        new_min_free_kbytes = int_sqrt(lowmem_kbytes * 16);

        if (new_min_free_kbytes > user_min_free_kbytes)
                min_free_kbytes = clamp(new_min_free_kbytes, 128, 262144);
        else
                pr_warn("min_free_kbytes is not updated to %d because user defined value %d is preferred\n",
                                new_min_free_kbytes, user_min_free_kbytes);

}
```

This machine has 16GB, so we should have 16MB min_free_kbytes.

**Comment by avikivity** [comment]
The 64k page size means the hugepage size is 512MB, and the kernel adjusts min_free_kbytes to accomodate. After disabling transparent hugepages, I  get

```
$ cat /proc/sys/vm/min_free_kbytes 
15892
```

**Comment by avikivity** [comment]
With transparent_hugepage=madvise, we also see the funny reservation.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
