### ISSUE TITLE
View updates should keep the effective_replication_map

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#14730]
`mutate_MV` schedules view updates to be sent to the corresponding nodes, but it doesn't lock down the `effective_replication_map`, so the updates could posibly be sent to the wrong node on a topology change, 

```c++
        auto target_endpoint = get_view_natural_endpoint(_proxy.local().local_db(), keyspace_name, base_token, view_token);
        auto remote_endpoints = _proxy.local().local_db().find_keyspace(keyspace_name).get_effective_replication_map()->get_pending_endpoints(view_token);
        auto sem_units = pending_view_updates.split(mut.fm.representation().size());
```

**Comment by nyh** [comment]
@cvybhu I don't understand what is the issue that you are proposing here. Can you give an example scenario that would produce wrong results? Is it a coding bug (effective_replication_map needs to be locked in a certain fashion (?), it's a bug to use it the way we did it), or a conceptual problem with how topology changes work?

**Comment by mykaul** [comment]
> * It turns out that the update should now be sent to `D`, not `B`

I'm not sure why would that happen?

**Comment by cvybhu** [comment]
> > * It turns out that the update should now be sent to `D`, not `B`
> 
> I'm not sure why would that happen?

During the topology change `D` can take over the token range that `B` used to own. So now the update to a partition within the token range should be sent to `D`, instead of `B`. Keeping the `effective_replication_map` would prevent a full topology change until the existing updates are completely delivered.

**Comment by tgrabiec** [comment]
I think the topology change algorithm is supposed to deal with this scenario, and the bug is that we don't keep erm around sending.

If you keep erm around sending, and propagate fencing_token to the replica (like in 46f73fcaa6adb13b22de5b338e5e555ee2c779d5). Then in your scenario:

> 
> 1. A generates a view update and schedules it to be sent to B (this could take a moment, view updates are asynchronous and can accumulate)
> 2. In the meantime a new node joins the cluster - D
> 3. It turns out that the update should now be sent to D, not B
> 4. The update is still mistakenly sent to B, view inconsistency happens
> 

In step 1 erm is captured. When adding D, streaming will wait until that erm is released, so until the write reaches B or times out. Until streaming starts, B is still considered as the replica.
