### ISSUE TITLE
Missing counterasblob() function

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#14742]
Scylla has many `*asblob()` functions but is missing the version for the counter column type - `counterasblob()`. It does work in Cassandra.

The problem is code in `functions.cc` which creates all those functions, and has:
```
        // counters are not supported yet
        if (type.is_counter()) {
            warn(unimplemented::cause::COUNTERS);
            continue;
        }
```

We do already support counters, so we need to allow this function as well.

The function `blobascounter()` is similarly missing.

**Comment by tzach** [comment]
https://opensource.docs.scylladb.com/stable/cql/functions.html#blob-conversion-functions

**Comment by DoronArazii** [comment]
Backported to 5.1 + 5.2
Removing label.
