### ISSUE TITLE
thrift: Implement mixed column families

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#1474]
_Installation details_
Scylla version (or git commit hash): 8d87976

Currently we don't support mixed column families in the Thrift API; these are static column families to which columns are added dynamically.

A possible approach for this might be to always add a clustering key (and accompanying regular column) to static column families, which would normally be empty.

**Comment by tchaikov** [comment]
won't be fixed because Thrift is dropped. see #18416
