### ISSUE TITLE
Mitigate semaphore mismatch when possible

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#14770]
This issue is an OSS copy of https://github.com/scylladb/scylla-enterprise/issues/3182.

When semaphore mismatch is detected between two user's semaphores, the cached querier can be dropped instead of throwing an internal error.

Also the check is only present in multi-partition queires, it should be done in all queries.

**Comment by DoronArazii** [comment]
Adding 'backport candidate' (@Jadw1 next time please use "Fixes: #12345").
@scylladb/scylla-maint please consider a backport to all active 5.x + our supported enterprise versions

**Comment by denesb** [comment]
This is a potentially distrupting change. We should let it get into enterprise and get some testing with SL addition/removal under read load before backporting.

**Comment by mykaul** [comment]
> This is a potentially distrupting change. We should let it get into enterprise and get some testing with SL addition/removal under read load before backporting.

How will we get it into Enterprise without backporting?

**Comment by denesb** [comment]
> > This is a potentially distrupting change. We should let it get into enterprise and get some testing with SL addition/removal under read load before backporting.
> 
> How will we get it into Enterprise without backporting?

Via the regular master -> enterprise merge.

**Comment by denesb** [comment]
Backported to 5.1 and 5.2. There were conflicts, but they were relatively easy to sort out.
