### ISSUE TITLE
thrift: Enhance test coverage

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#1478]
_Installation details_
Scylla version (or git commit hash): 8d87976

Some verbs, like get_paged_slice, are not covered by dtests. We should add unit- or d-tests for such cases to increase coverage of the less common thrift verbs.

**Comment by nyh** [comment]
We will probably never do this issue.  The Thirft API is antiquated. It was already removed from Cassandra 4.0 (see https://issues.apache.org/jira/browse/CASSANDRA-11115), and it was proposed to deprecate from Scylla to in issue https://github.com/scylladb/scylladb/issues/3811, and although this hasn't happened, it will probably happen. It is likely we will deprecate Thrift before doing this 6 year old issue.
