### ISSUE TITLE
gossiper::replicate is not exception safe

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14794]
If replicate fails on any shard it will simply propagate the error but leave the gossiper in an inconsistent state.
Instead, it should prepare all copies in advance before applying them on all shards.
(And be called under the endpoint lock to make sure the shards are always in sync with each other)

**Comment by mykaul** [comment]
Not sure why the bot did not put the 'backport' labels on this. @yaronkaikov  ?

**Comment by yaronkaikov** [comment]
> Not sure why the bot did not put the 'backport' labels on this. @yaronkaikov ?

I assume since in the PR closing this issue we have 
```
Fixes https://github.com/scylladb/scylladb/issues/14794
Fixes https://github.com/scylladb/scylladb/issues/14799
```

without `:` after `Fixes` - And I think it is related to changes done in https://github.com/scylladb/jenkins/commit/6663a38cdd4cae821807503e1c5496b1520183be

**Comment by mykaul** [comment]
So we either fix or regexp or add a GH test that verifies that 'Fixes' has the required ':'  ... It's silly to run around such issues manually.

**Comment by mykaul** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword seems not to require ':'

**Comment by yaronkaikov** [comment]
@benipeled shouldn't https://github.com/scylladb/jenkins/pull/30 fix it ?

**Comment by benipeled** [comment]
1. `:` is not required
2. The format used is the short-path repo which is indeed added by https://github.com/scylladb/jenkins/pull/30  (merged now)

**Comment by benipeled** [comment]
> > Not sure why the bot did not put the 'backport' labels on this. @yaronkaikov ?
> 
> I assume since in the PR closing this issue we have
> 
> ```
> Fixes https://github.com/scylladb/scylladb/issues/14794
> Fixes https://github.com/scylladb/scylladb/issues/14799
> ```
> 
> without `:` after `Fixes` - And I think it is related to changes done in [scylladb/jenkins@6663a38](https://github.com/scylladb/jenkins/commit/6663a38cdd4cae821807503e1c5496b1520183be)

Github UI is misleading since it render the links, if you want to see the format you should check the commit locally

**Comment by bhalevy** [comment]
I've added the `Backport candidate` label.
38c2347a3ce298945d47d258c93ec3858a43c4fc is based on quite a few patches preparing for it so backporting it would be quite challenging.

I'm not sure that the severity of the issue really merits the backport.
At least, we don't have any known field or QA-found issues that we can attribute to it.

As an alternative, we can abort on exception in gossiper::replicate as a safeguard.
It will be annoying, but rare, and safe.

**Comment by bhalevy** [comment]
Note this series is based on 93be4c0cb0f0c53fe0eb7cd4d06ba15a7fc01d29 (#14801)

**Comment by avikivity** [comment]
I think this is impractical to backport (greater risk than benefit).

**Comment by bhalevy** [comment]
> I think this is impractical to backport (greater risk than benefit).

I agree.  Removing `Backport candidate` label.
