### ISSUE TITLE
sstabledump doesn't work with `uuid_sstable_identifier_enabled`

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#14790]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

during upgrading from 5.3.0-rc0, sstabledump fails with the following:
```
Command: 'for i in `sudo find /var/lib/scylla/data/keyspace_complex/ -type f |grep -v manifest.json |grep -v snapshots |head -n 1`; do echo $i; sudo sstabledump $i 1>/tmp/sstabledump.output || exit 1; done'
Exit code: 1
Stdout:
/var/lib/scylla/data/keyspace_complex/user_with_ck-f16b9850284c11ee9b315037fb05b276/me-3g7v_0hbv_2lvmo2mtl76kzm9t1i-big-TOC.txt
Stderr:
WARN  06:39:13,026 Only 28.306GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
Exception in thread "main" java.lang.NumberFormatException: For input string: "3g7v_0hbv_2lvmo2mtl76kzm9t1i"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:280)
at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:228)
at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:217)
at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:188)
at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
```

## Impact

sstabledump can't be used when sstable uuid identifer is enabled

## How frequently does it reproduce?

reproducible 100%

## Installation details

Kernel Version: 4.19.0-24-cloud-amd64
Scylla version (or git commit hash): `5.3.0~rc0-20230523.3c3621db072d` with build-id `78cb9caaf1cdd0b37c3a38fa83548e6c4e3d4ab4`
Target Scylla version (or git commit hash): `5.4.0~dev-20230717.567b4536892f` with build-id `98731517a6828085106956bea9f922fbb96697dc`

Cluster size: 4 nodes (n2-highmem-32)

Scylla Nodes used in this run:
- rolling-upgrade--debian-buster-db-node-4daaf7a3-0-4 (34.148.21.9 | 10.142.0.170) (shards: 30)
- rolling-upgrade--debian-buster-db-node-4daaf7a3-0-3 (34.139.131.81 | 10.142.0.169) (shards: 30)
- rolling-upgrade--debian-buster-db-node-4daaf7a3-0-2 (34.148.207.129 | 10.142.0.168) (shards: 30)
- rolling-upgrade--debian-buster-db-node-4daaf7a3-0-1 (104.196.170.210 | 10.142.0.166) (shards: 30)

OS / Image: `` (gce: undefined_region)

Test: `rolling-upgrade-debian10-test`
Test id: `4daaf7a3-ec9a-496a-8211-22b556cd03fb`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-debian10-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cb988e18f1796fbd233176de16e1054947281591/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 4daaf7a3-ec9a-496a-8211-22b556cd03fb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=4daaf7a3-ec9a-496a-8211-22b556cd03fb)
- Show all stored logs command: `$ hydra investigate show-logs 4daaf7a3-ec9a-496a-8211-22b556cd03fb`

## Logs:
- **db-cluster-4daaf7a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/db-cluster-4daaf7a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/db-cluster-4daaf7a3.tar.gz)
- **sct-runner-events-4daaf7a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/sct-runner-events-4daaf7a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/sct-runner-events-4daaf7a3.tar.gz)
- **sct-4daaf7a3.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/sct-4daaf7a3.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/sct-4daaf7a3.log.tar.gz)
- **loader-set-4daaf7a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/loader-set-4daaf7a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/loader-set-4daaf7a3.tar.gz)
- **monitor-set-4daaf7a3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/monitor-set-4daaf7a3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/4daaf7a3-ec9a-496a-8211-22b556cd03fb/20230722_065242/monitor-set-4daaf7a3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-debian10-test/198/)
[Argus](https://argus.scylladb.com/test/5581b90e-e664-44ae-92ae-b996ca485251/runs?additionalRuns[]=4daaf7a3-ec9a-496a-8211-22b556cd03fb)
</details>

**Comment by tchaikov** [comment]
this should be filed against https://github.com/scylladb/scylla-tools-java/issues/333 . and it's a dup of https://github.com/scylladb/scylla-tools-java/issues/333
