### ISSUE TITLE
thrift: Support composite column names and value

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#1479]
_Installation details_
Scylla version (or git commit hash): 8d87976

Currently, only the `key_validation_class` and the `comparator` (in case of a dynamic CF) can be composite types. The `comparator`, in case of static CFs, can also be composite (the regular column names would be composite), as can a column's `validation_class`. We should support this cases.

**Comment by tchaikov** [comment]
won't be fixed because Thrift is dropped. see #18416
