### ISSUE TITLE
storage_service: "Node {} is down for {} verb" log message has reversed args

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14807]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/245/artifact/logs-full.debug.094/1690100633894_rebuild_test.py%3A%3ATestRebuild%3A%3Atest_rebuild_many_keyspaces/node2.log
```
WARN  2023-07-23 08:23:23,388 [shard 0] storage_service - bootstrap[4b61683f-0431-4d19-b651-9f87bdc4e86e]: Node bootstrap_abort is down for 127.0.10.1 verb
```

This exists since d322bbf6ff797f221d245685be613e67dbad3015 (5.3)

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
