### ISSUE TITLE
view_updating_consumer does not account for mutation size

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#14819]
Te view updating consumer uses `_buffer_size`  to decide when to flush the accumulated mutations, passing them to the actual view building code. This `_buffer_size` is incremented every time a mutation fragment is consumed. This is not exact, as e.g. range tombstones are represented differently in the mutation object, than in the fragment, but it is good enough. There is one flaw however: `_buffer_size` is not incremented when consuming a partition-start fragment. This is when the `mutation` object is created in the mutation rebuilder. This is not a big problem when partition have many rows, but if the partitions are tiny, the error in accounting quickly becomes significant. If the partitions are empty, `_buffer_size` is not bumped at all for empty partitions, and any number of these can accumulate in the buffer. We have recently seen this causing stalls and OOM as the buffer got to immense size, only containing empty and tiny partitions.

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport to all the active 5.x versions.

**Comment by nyh** [comment]
@DoronArazii @avikivity is the 5.3 branch still active, or axed? Is 5.1? I'm confused.

**Comment by DoronArazii** [comment]
Where did you saw 5.3 in the existing labels:

![image](https://github.com/scylladb/scylladb/assets/97870791/6e68679f-e091-4791-b230-edcacec658eb)

**Comment by nyh** [comment]
@DoronArazii I was on vacation and sick and apparently did not get the memo. We still have a branch 5.3 - is it officially axed? If it was, why wasn't the branch removed or renamed?

**Comment by DoronArazii** [comment]
@nyh Understood.
5.3 is not in use. RE should archive it.
We will branch-out from master again soon (I don't know how we will call it..), so no need to backport anything to 5.3
Please consider backport only to 5.1 + 5.2

**Comment by nyh** [comment]
Backported cleanly to next-5.2 (75bec80ed02de387afc48681b74534351a4720cf),

**Comment by fgelcer** [comment]
> @DoronArazii I was on vacation and sick and apparently did not get the memo. We still have a branch 5.3 - is it officially axed? If it was, why wasn't the branch removed or renamed?

branches were recently renamed:
https://github.com/scylladb/scylladb/branches/all?query=5.3

**Comment by nyh** [comment]
Thanks @fgelcer. For reason on my own working directory, "branch -r" shows both origin/next-5.3 and origin/on-hold-next-5.3. Maybe it's cached somewhere on my own machine?

**Comment by fgelcer** [comment]
> Thanks @fgelcer. For reason on my own working directory, "branch -r" shows both origin/next-5.3 and origin/on-hold-next-5.3. Maybe it's cached somewhere on my own machine?

i see a command `git fetch -p`, based on [this page](https://stackoverflow.com/questions/31921561/how-to-clear-git-caches)

**Comment by denesb** [comment]
@nyh in the future, when backporting, please remove the relevant backporting labels too.

**Comment by denesb** [comment]
Backports dequeued because they break the build. I will re-do the backports today.

**Comment by denesb** [comment]
Re-did backports:
* 5.2: e34c62c567787ead774f36425b367cbe992723ab
* 5.1: a98d5206a508f6636d2e7601df4128872fb29613

**Comment by nyh** [comment]
> @nyh in the future, when backporting, please remove the relevant backporting labels too.

This should only be done when (and if) the backport promotes to master.

**Comment by denesb** [comment]
> > @nyh in the future, when backporting, please remove the relevant backporting labels too.
> 
> This should only be done when (and if) the backport promotes to master.

I do it immediately after queuing. No way I will remember to check back for promotion and remove the labels after. If promotion fails, somebody will dequeue the backport and will re-add the labels.

**Comment by nyh** [comment]
The minor risk of forgetting to remove the Backport Candidate tag is that later somebody will notice it again, will spend 30 seconds looking at the end of the issue and realize the tag can be removed.

On the other hand, the risk for removing the Backport Candidate tag when the backport wasn't successful and then forgetting to re-add it is that nobody will ever again remember to do the backport. I think it's worse.

**Comment by denesb** [comment]
It might not be 30 seconds. It may be minutes. There can be a lot of commits referencing an issue.

Anyway, we should have automation for this.

**Comment by mykaul** [comment]
> It might not be 30 seconds. It may be minutes. There can be a lot of commits referencing an issue.
> 
> Anyway, we should have automation for this.

Exactly. I'm still hopeful we can get mergify do the bulk of this work.
