### ISSUE TITLE
is there a plugin or how do i extend and use lua with a fix variable that i can do counter variable data in? 

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/scylladb#14817]
is there a plugin or how do i extend and use lua with a fix variable that i can do counter variable data in?

**Comment by nyh** [comment]
This is a tracker for reporting bugs and requesting missing features - not for general discussions or asking questions. We have several other forums for that, including a mailing list (scylladb-dev at googlegroups.com), slack and a web forum.

Despite this, I would still have answered your question here, if I could understand it, but I didn't... Scylla does support user-defined functions in Lua, and you don't need a separate plug-in to enable it. Is this what you wanted to achieve? Or something else? Let's continue this thread on the mailing list. Thanks.
