### ISSUE TITLE
cached_file, used by index caching, will potentially cause a crash after OOM 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14814]
cached_file can fetch multiple pages (each 4k in size) at once due to read ahead, 

when that happens, only the first page is wrapped in `ptr_type = std::unique_ptr<cached_page, cached_page_del>`. 

cached_page_del is an automatic deleter that will add page to LRU once unused (i.e. refcount drops to zero).

there's an optimistic assumption that pages not wrapped in ptr_type yet will be consumed eventually, and therefore they'll be added to LRU too once unused.

But if OOM happens before that, pages not consumed yet will remain unused and not linked to LRU

when the cached_file is destroyed after OOM, it will try to evict cache under the incorrect assumption that all unused entries are in LRU, but some of the unused entries are not linked to LRU,

so cached_file destructor will fail as follow:

`cached_file_test: utils/cached_file.hh:379: cached_file::~cached_file(): Assertion `_cache.empty()' failed.`

can be easily reproduced by injecting allocation failure after 2nd page was introduced into cache, but before it's consumed.

**Comment by bhalevy** [comment]
cc @tgrabiec

**Comment by DoronArazii** [comment]
Backported into 5.1 + 5.2

Removing labels.

**Comment by bhalevy** [comment]
@mykaul @avikivity I wonder if we should have labels marking issues backport state as final, like: "Backport Done", "No backport required", or "Backport denied"?

Today when an issue has no "Backport candidate" label I don't know if somehow it wasn't added by mistake or if it was removed when the backport completed or deemed unneeded or undesired for some reason.

**Comment by avikivity** [comment]
Yes I discussed it with @benipeled once. I don't know what to think about it now.

**Comment by mykaul** [comment]
> @mykaul @avikivity I wonder if we should have labels marking issues backport state as final, like: "Backport Done", "No backport required", or "Backport denied"?
> 
> Today when an issue has no "Backport candidate" label I don't know if somehow it wasn't added by mistake or if it was removed when the backport completed or deemed unneeded or undesired for some reason.

This is exactly the state machine implementation I've been mentioning in the thread about automation and labels... I just think we need to properly design and document our phases first, rather than add labels.

**Comment by benipeled** [comment]
> @mykaul @avikivity I wonder if we should have labels marking issues backport state as final, like: "Backport Done", "No backport required", or "Backport denied"?
> 
> Today when an issue has no "Backport candidate" label I don't know if somehow it wasn't added by mistake or if it was removed when the backport completed or deemed unneeded or undesired for some reason.

The logic added ~year ago - https://github.com/scylladb/jenkins/pull/26#issuecomment-1269698701 - the `backport-done` and `no-backport-require` labels should be used in this case
