### ISSUE TITLE
gossiper endpoint locking is inconsistent

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14838]
To serialize endpoint state changes and corresponding notifications processing
gossiper should call lock_endpoint and call the notifications while holding the lock.

However, in several cases the lock is not taken, maybe due to potential deadlocks
as described in https://github.com/scylladb/scylladb/pull/14471#issuecomment-1620102615, for example,
where the notification function calls back into the gossiper and if the endpoint is locked uncoditionally
on this path, lock_endpoint would deadlock since the lock is held around the called notification.

In addition, it is not guaranteed that `gossiper::replicate` is called under lock_endpoint
so if the endpoint state is updated in parallel the state could end up as inconsistent across shards
as the replicate calls aren't serialized.

**Comment by avikivity** [comment]
@benipeled this commit (and others) has "Fixes scylladb/scylladb#nnnn" (rather than "Fixes #nnnn"). The backport candidate bot doesn't understand this syntax and so doesn't apply the label. Please fix it and also check for older commits with this syntax (but don't re-add labels that were removed).

**Comment by benipeled** [comment]
> @benipeled this commit (and others) has "Fixes scylladb/scylladb#nnnn" (rather than "Fixes #nnnn"). The backport candidate bot doesn't understand this syntax and so doesn't apply the label. Please fix it and also check for older commits with this syntax (but don't re-add labels that were removed).

https://github.com/scylladb/jenkins/pull/30

**Comment by avikivity** [comment]
Fast

**Comment by avikivity** [comment]
Huge series, not backporting.
