### ISSUE TITLE
gossiper: mark_alive: _pending_mark_alive_endpoints is not cleared on exception paths

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14839]
gossiper::mark_alive inserts `addr` into `_pending_mark_alive_endpoints` so that only one `mark_alive` background fiber will run at a time for a given endpoint.  Further calls just silently return immediately if `addr` is already present in `_pending_mark_alive_endpoints`.

However, an unfortunate exception (which should be extremely rare but not impossible) could happen by or before `send_gossip_echo`, and in this case `_pending_mark_alive_endpoints.erase(addr)` in the `finally` continuation will never happen.

**Comment by avikivity** [comment]
@bhalevy please advise about backports

**Comment by bhalevy** [comment]
This doesn't fix a regression.
However, the fix has low risk and high gain.
When the issue is triggered, a node will not be able to mark another node is alive, and it will require service restart to recover.

**Comment by denesb** [comment]
@bhalevy it doesn't apply cleanly to 5.2,please open a backport PR.

**Comment by bhalevy** [comment]
> @bhalevy it doesn't apply cleanly to 5.2,please open a backport PR.

@denesb it depends on https://github.com/scylladb/scylladb/issues/14791 that for some reasons is not labeled as backport candidate

**Comment by bhalevy** [comment]
I'll prepare a branch with both
