### ISSUE TITLE
Task manager api responds with Internal Server Error

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#14914]
Task manager wait_task rest api call responds with Internal 
Server Error (500) when compaction represented by requested
task fails.

**Comment by denesb** [comment]
@Deexie do we need to backport this to 5.2?

**Comment by Deexie** [comment]
> @Deexie do we need to backport this to 5.2?

Yes

**Comment by denesb** [comment]
Please open a backport PR, the change doesn't apply cleanly.
