### ISSUE TITLE
schema::describe: print `synchronous_updates` only when it's present in extension map

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#14924]
Currently `synchronous_updates` is printed always in materialized view's description. It is not necessary to print it when the key is not present in schema's extension map.

Refers: https://github.com/scylladb/scylla-dtest/issues/3324

**Comment by nyh** [comment]
It isn't necessary, that's true, but what's the downside to print it?
Moreover, what do we do for other options that have defaults, do we print the default or not? If we do, why should this option get a different treatment?
(I don't consider a dtest a convincing-enough reason...)

**Comment by denesb** [comment]
Minor UX improvement, not backporting.
