### ISSUE TITLE
sstabledump returns 1 in TestCompactionAdditional.test_compaction_delete_with_smp_change

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#14920]
```
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]     def test_compaction_delete_with_smp_change(self):
...
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]         logger.debug("Stopping node1")
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]         node1.stop(gently=False)
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]     
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]         # verify that only some deletion markers will be kept since we reshard the files
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]         # and gc_period passed so some tombstones have been removed by compaction
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]         json_path = tempfile.mkstemp(suffix='.json')
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]         jname = json_path[1]
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z]         with open(jname, 'w') as f:
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.477Z] >           node1.run_sstable2json(f, keyspace='ks')
...
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.478Z] popenargs = (['/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/14915/scylla-core-package/scyll...t/dtest-hfnbrl64/test/node1/data/ks/cf-0310d710307b11eebc974b315c64dd1e/me-3g85_15bf_0nd1t2f1kiki1qbdrx-big-Data.db'],)
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.478Z] kwargs = {'env': {'ASAN_OPTIONS': 'disable_coredump=0:abort_on_error=1', 'AWS_ACCESS_KEY_ID': ****, 'AWS_SECR...RRORS': 'no', ...}, 'stdout': <_io.TextIOWrapper name='/tmp/tmpo6c169l3.json' mode='w' encoding='UTF-8'>, 'text': True}
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.478Z] process = <Popen: returncode: 1 args: ['/jenkins/workspace/scylla-master/gating-dtest-...>
23:20:21  [FullDtest] [full-split000] [2023-08-01T15:20:17.478Z] stdout = None, stderr = None, retcode = 1
```

see https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3386

**Comment by bhalevy** [comment]
@tchaikov doesn't this issue belong to scylla-tools-java?
Maybe we should transition the use the scylla sstable tool in `run_sstable2json` (in scylla-ccm/node.py)

**Comment by bhalevy** [comment]
> how about keeping it here just for tracking the possible occurrences in future?

I'm not sure what you mean by "here".
This is a compaction test, not a test for sstabledump so we can use whatever tool we need to get the job done.
So I see no reason not to use scylla sstable in this test.
Since `sstable2json` refers to a deprecated cassandra tool that was replaced long time ago by sstabledump we can introduce a new function to run it, e.g. `dump_sstable`, that would be generic enough and run `scylla sstable --dump`.
And then we can leave `run_sstable2json` as is and transition its user gradually to `dump_sstable` and eventually drop it when it has no users.

**Comment by tchaikov** [comment]
> > how about keeping it here just for tracking the possible occurrences in future?
> 
> I'm not sure what you mean by "here". 

https://github.com/scylladb/scylladb/issues, so one can find it when searching with related keywords. not in scylla-tools-java. probably it's just me who would like to search here when i run into a test failure.

> This is a compaction test, not a test for sstabledump so we can use whatever tool we need to get the job done. So I see no reason not to use scylla sstable in this test.

@bhalevy i concur with you on this. if you take a look at https://github.com/scylladb/scylla-dtest/pull/3444 . you'll see i am moving in this direction.

**Comment by tchaikov** [comment]
closing. wanted to make sure it can be found if any of us run into the same test failure.

**Comment by bhalevy** [comment]
> https://github.com/scylladb/scylladb/issues, so one can find it when searching with related keywords. not in scylla-tools-java. probably it's just me who would like to search here first when running into a test failure.

I understand where you're coming from.
I think it's fine to file the issue in this repo if we suspect that the issue is with scylla.
If not, scylla-dtest is also a good place to file the issue for tracking purposes and we should make a habit to look there too when some dtest fails.
