### ISSUE TITLE
Cluster features on raft: topology coordinator + check on boot followups

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#14972]
This issue collects the followups that need to be done after https://github.com/scylladb/scylladb/pull/14722, mostly collected from the discussion [here](https://github.com/scylladb/scylladb/pull/14722#discussion_r1282698054):

**Flush the `system.topology` table when feature columns are modified**

The feature check on startup (`enable_features_on_join`) reads the state of supported and enabled features stored in the table. Before enabling a feature, the topology coordinator makes sure to do a global barrier so that nodes observe a state which, when observed during `enable_features_on_join`, will not allow the node to revoke the support for the feature. However, this check happens very early, even before schema commitlog replay, so the state of the `system.topology` table it observes might not be recent enough.

We should make sure to flush the table at the right moments so that `enable_features_on_join` observes the recent enough state.

**Add a second feature check in `update_topology_with_local_metadata`**

When updating `supported_features` column in the `update_topology_with_local_metadata` function, it may happen that this is the last node to declare support for a feature, and the node can crash before applying the command that modifies `supported_features`. If that happens, on restart the check in `enable_features_on_join` will pass and the node will revoke its support for the feature when it reaches `update_topology_with_local_metadata` again. The node should not be allowed to do that if all nodes in the cluster support the feature, so we should add a check against it in `update_topology_with_local_metadata`.

**Get rid of the `barrier_after_feature_update`**

Due to the possible situation outlined in the previous point, feature enablement uses a special variant of the global barrier called `barrier_after_feature_update`. The barrier succeeds only after `update_topology_with_local_metadata` has been completed on the node. We can get rid of it and modify the regular barrier to check whether the local node's supported features are synchronized with its state in group 0 and only succeed if it is true - this should achieve similar effect.

**~New RPC for joining the cluster~**

(This is more like a separate item than a followup after the PR, but it's needed for features on raft to be complete)

The current implementation uses group 0 to disallow node downgrade when the version that the node is downgraded to does not support some enabled feature, but it still relies on gossip shadow round to determine whether it can join. We need to fix this, i.e. stop relying on gossip here. Because group 0 itself relies on features (the schema commitlog does, at least) and also it manages features, we get a circular dependency and we must do the features check before joining group 0. The proposed solution is to implement a new handshake procedure (JOIN_NODE rpc) which replaces GROUP0_MODIFY_CONFIG; it does the feature check and adds the node to group 0.

**Comment by avikivity** [comment]
Not a bug, not backporting.
