### ISSUE TITLE
test.py: minio server fails to start because of the port conflict

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#14985]
`RuntimeError: Failed to start minio server` getting this error when I run `test.py` if someone already started it on the local machine. It uses fixed port 9000, should be changed to a random available port.

**Comment by nyh** [comment]
Another option which I used in test/cql-pytest/run.py is not to pick a unique port number but pick a unique ip address. If we already do this for Scylla itself then we could use the same unique ip address also for minio.

**Comment by gusev-p** [comment]
yeah, `test.py` has some infra for it, I think I will use it

**Comment by gusev-p** [comment]
```
[gusev-p@potwor1 scylladb]$ /usr/local/bin/minio server --address 127.64.229.1:9000 ./data

API: SYSTEM()
Time: 10:38:05 UTC 08/08/2023
Error: listen tcp 127.0.0.1:9000: bind: address already in use (*net.OpError)
       2: internal/logger/logger.go:258:logger.LogIf()
       1: cmd/signals.go:80:cmd.handleSignals()
```
Strange, it's already using `test.py`, but minio itself seems to ignore `--address` parameter.

**Comment by gusev-p** [comment]
```
# echo-server.py

import socket

HOST = "127.96.128.1"  # Standard loopback interface address (localhost)
# HOST = "127.0.0.1"
PORT = 9000  # Port to listen on (non-privileged ports are > 1023)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    s.listen()
    conn, addr = s.accept()
    with conn:
        print(f"Connected by {addr}")
        while True:
            data = conn.recv(1024)
            if not data:
                break
            conn.sendall(data)
```

this code works, so nothing special with the local pseudonyms generated by `pylib/host_registry.py`

**Comment by gusev-p** [comment]
https://github.com/minio/minio/discussions/17817

**Comment by tchaikov** [comment]
@alecco @kostja hello gentlemen, i didn't realize that you were the assignees of this issue when creating the fix. my apologies! if you've started working on it. i will close my PR.

**Comment by alecco** [comment]
> @alecco @kostja hello gentlemen, i didn't realize that you were the assignees of this issue when creating the fix. my apologies! if you've started working on it. i will close my PR.

Kostja is OOO and I did not start yet. Thanks for taking care of this!

**Comment by nyh** [comment]
Sad that the solution is to accept a bug in minio (and excuse this bug as "an answer" in their github repository as they did), and a race-prone solution to pick a port (if two test runs race both can choose the same port and decide it's free). I guess it's better than no solution at all, but not ideal.

**Comment by tchaikov** [comment]
> and a race-prone solution to pick a port (if two test runs race both can choose the same port and decide it's free). I guess it's better than no solution at all, but not ideal.

#15042 was created to address the racing.

**Comment by nyh** [comment]
> Sad that the solution is to accept a bug in minio (and excuse this bug as "an answer" in their github repository as they 

I was too sad to let this minio bug slide, so I tried to engage them but they flatly refuse to accept that it's a bug that "--address" doesn't work...
I'm not saying they should have jumped to fix the bug in a day, but they refused to even keep the issue open, stating that this is "by design" without any attempt to accept how or why exactly it is "by design". As far as they were concerned, if the bug can be worked around (e.g., different port number), there's no need to fix it.

This should be a lesson to managers who think that it's a good idea to keep the number of open issues low at all cost (including closing unfixed issues). The minio github project has 6674 closed issues but only 21 (!) open issues. This is not natural. This is not good.

**Comment by nyh** [comment]
I just realized that the minio issue linked above wasn't an actual issue but a "discussion". I don't know why... Maybe by framing it as a "discussion" instead of an issue, we gave them an excuse to ignore it. But on the other hand, since it seems they close all these issues too, maybe not ;-)

**Comment by avikivity** [comment]
> @alecco @kostja hello gentlemen, i didn't realize that you were the assignees of this issue when creating the fix. my apologies! if you've started working on it. i will close my PR.

You should get an EADDRINUSE if you start working on an assigned issue.
