### ISSUE TITLE
raft topology: implement upgrade procedure

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15008]
Scenarios:
1. start with a cluster which is using schema-on-raft, upgrade to use topology-on-raft.
2. start with a cluster which is not using raft at all, upgrade to use topology-on-raft.

Scenario 2 could potentially be reduced to scenario 1 by running two upgrade procedures consecutively, but that would be very bad UX, requiring two rolling restarts.

Maybe it will be possible to implement a single procedure that covers both cases with some minor branching here and there.

Maybe even a slight modification to the existing upgrade-to-schema-on-raft will suffice.

Anyway, implementing this new/modified upgrade procedure definitely requires understanding how the existing procedure works, and how Raft RECOVERY works as well (which uses the same procedure). Sources to educate oneself:
- ScyllaDB docs for the user perspective: https://opensource.docs.scylladb.com/stable/architecture/raft.html#enabling-raft, https://opensource.docs.scylladb.com/stable/architecture/raft.html#raft-manual-recovery-procedure
- Design doc for implementation of the upgrade/recovery procedure: https://docs.google.com/document/d/1PvZ4NzK3S0ohMhyVNZZ-kCxjkK5URmz1VP65rrkTOCQ/edit
- Original PR with the procedure: https://github.com/scylladb/scylladb/pull/10835 (there were some follow-ups but this one is the most important)
- and of course the current code inside `service::raft_group0`, functions: `upgrade_to_group0`, `setup_group0`, `finish_setup_after_join` (the last two are interacting with and/or triggering the upgrade procedure too).

**Comment by kbr-scylla** [comment]
> Design doc for implementation of the upgrade/recovery procedure: https://docs.google.com/document/d/1PvZ4NzK3S0ohMhyVNZZ-kCxjkK5URmz1VP65rrkTOCQ/edit

Note that the design doc assumes that the implemented procedure would cover both schema and topology. But the implementation covers only schema. Maybe -- following the doc -- it will be easy to modify the implementation so it covers both schema and topology, in order to solve scenario 2 at least?

But we still need to solve scenario 1, which the doc does not cover.

**Comment by kbr-scylla** [comment]
Refs: https://github.com/scylladb/scylladb/issues/14918

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius

**Comment by piodul** [comment]
@avikivity

> Looks good from a shallow review. I'd like to make sure nothing is lost with upgrades in non-experimental operation.

Could you clarify what you would like me to do here? The non-experimental code path should work exactly the same as before.

> Also, upgrade from non-experimental to consistent topology should work.

This is going to be covered in https://github.com/scylladb/scylladb/issues/15008 which depends on this PR as far as I know.

**Comment by piodul** [comment]
Dang it, I posted the comment in the wrong place. Sorry for the confusion, will delete.

**Comment by mykaul** [comment]
Can be deferred to 6.0, I reckon?

**Comment by kbr-scylla** [comment]
Yes

**Comment by kbr-scylla** [comment]
The upgrade procedure should move the current CDC generation from system_distributed_everywhere to the new generations table (which is managed by topology coordinator)
