### ISSUE TITLE
gossiper::reset_endpoint_state_map does not clear the shadow live/unreachable endpoints

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15003]
gossiper::reset_endpoint_state_map clears only `_live_endpoints` and `_unreachable_endpoints`
on shard 0, but their shadow counterparts are untouched.
If the next update to those sets will cause them to be equal to the shadow copies
`replicate_live_endpoints_on_change()` will not replicate the new values to other shards
and we end up in an inconsistent state.
Therefore, `reset_endpoint_state_map` must clear also `_shadow_live_endpoints` and `_shadow_unreachable_endpoints`.

**Comment by denesb** [comment]
@bhalevy should we backport this? The code looks quite different in 5.2.

**Comment by bhalevy** [comment]
The issue exists there too but I don't think we've hit it in the wild so we can defer backporting
