### ISSUE TITLE
broken links in stable document

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15019]
for instance, the `SSTable2json` link in https://opensource.docs.scylladb.com/stable/operating-scylla/admin-tools/sstabledump.html points me to https://opensource.docs.scylladb.com/operating-scylla/admin-tools/sstable2json, which is 404. guess it should have been https://opensource.docs.scylladb.com/stable/operating-scylla/admin-tools/sstable2json with "stable" before "operating-scylla". 

but this issue does not exist in https://opensource.docs.scylladb.com/master/operating-scylla/admin-tools/sstabledump.html .

**Comment by annastuchlik** [comment]
This issue will be fixed by backporting https://github.com/scylladb/scylladb/pull/14664 to branch-5.2.

**Comment by annastuchlik** [comment]
https://github.com/scylladb/scylladb/pull/14664 was backported to branch-5.2, so the links are now working.
Closing.
