### ISSUE TITLE
raft topology: implement `--ignore-dead-nodes` for removenode and replace

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15025]
In gossiper mode it's possible to remove a node in presence of other dead nodes. This is necessary -- otherwise the cluster would be unable to proceed with topology operations as soon as two nodes die permanently.

This is not implemented yet in Raft topology.

For the first release we need a simple implementation that's similar to gossiper-mode behavior: assume that the nodes passed to `--ignore-dead-nodes` are permanently dead, we don't need to synchronize with them, and just ignore them when broadcasting commands to the cluster such as during `global_token_metadata_barrier`.

---

In the future we may aim for something more complicated, such as temporarily quarantining ignored nodes. But it's an open problem how to unquarantine nodes that we've been ignoring during topology operations. Bringing them up to the newest topology is not enough, because they may be missing some data; it's incorrect to serve reads from them. We basically need to "rebootstrap" these nodes (at least partially) -- i.e. start doing additional writes to them (while they don't yet serve reads), then stream whatever data they are missing; only after they obtain all missing pieces, it's safe to turn them back to normal members.

But for the initial implementation and release, simulating gossiper behavior should be enough.

cc @gleb-cloudius @tgrabiec @kostja

**Comment by denesb** [comment]
@kbr-scylla please evaluate for backport.

**Comment by kbr-scylla** [comment]
Experimental raft topology, no backport required
