### ISSUE TITLE
fstrim might be a no-op

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15033]
The fstrim service is used when the user opts not to use online discard. However, its log says

```
systemd[1]: Starting Discard unused blocks on filesystems from /etc/fstab...
systemd[1]: Finished Discard unused blocks on filesystems from /etc/fstab.
```

Since we place our mountpoint in /etc/systemd/system/var-lib-scylla.mount, not in /etc/fstab, it likely does nothing (possibly lies and looks in /proc/mounts and is okay).

**Comment by avikivity** [comment]
New fstrim has --listed-in /proc/self/mountinfo, so it's safe.

https://github.com/util-linux/util-linux/blame/123fe3336fe109200e4c6c645ac8c9202c38b3f6/sys-utils/fstrim.service.in#L8

**Comment by avikivity** [comment]
It's actually insufficient. fstrim will stop on the first non-empty path.

**Comment by mykaul** [comment]
BTW, shouldn't fstrim run on the root fs regardless of the option to use online discard for Scylla or not?

**Comment by avikivity** [comment]
It's not important, since the root fs is not a real disk.

**Comment by syuu1228** [comment]
> The fstrim service is used when the user opts not to use online discard. However, its log says
> 
> ```
> systemd[1]: Starting Discard unused blocks on filesystems from /etc/fstab...
> systemd[1]: Finished Discard unused blocks on filesystems from /etc/fstab.
> ```
> 
> Since we place our mountpoint in /etc/systemd/system/var-lib-scylla.mount, not in /etc/fstab, it likely does nothing (possibly lies and looks in /proc/mounts and is okay).

Well, current implementation of scylla_fstrim_setup is not rely on fstrim.timer, it unconditionally enables scylla-fstrim.timer and it directly runs `fstrim /var/lib/scylla` on our own fstrim script (scylla_fstrim), so it should be fine.

It does something like this:
```
    for d in mountpoints:
        print("Running fstrim on {} ...".format(d))
        res = subprocess.call(["fstrim", d])
```
https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_fstrim#L40

Note that we only run scylla_fstrim_setup when online discard is disabled:
```
        # no need for fstrim if online discard is enabled
        fstrim_setup = fstrim_setup and not online_discard
        fstrim_setup = interactive_ask_service('Do you want to enable fstrim service?', 'Yes - runs fstrim on your SSD. No - skip this step.', fstrim_setup)
        args.no_fstrim_setup = not fstrim_setup
        if fstrim_setup:
            run_setup_script('fstrim', 'scylla_fstrim_setup')
```
https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_setup#L510

**Comment by syuu1228** [comment]
But, then we shouldn't disable fstrim.timer on scylla_fstrim_setup.
We currently doing:
```
    if is_redhat_variant() or is_arch() or is_suse_variant():
        systemd_unit('fstrim.timer').disable()
```
https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_fstrim_setup#L21
It's likely mistake.
I think this was for avoid running fstrim on /var/lib/scylla from both scylla-fstrim.timer and fstrim.timer, but since fstrim.timer actually don't do that, disabling the service doesn't make sense.
I think we should just drop these lines.

**Comment by avikivity** [comment]
> > The fstrim service is used when the user opts not to use online discard. However, its log says
> > ```
> > systemd[1]: Starting Discard unused blocks on filesystems from /etc/fstab...
> > systemd[1]: Finished Discard unused blocks on filesystems from /etc/fstab.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since we place our mountpoint in /etc/systemd/system/var-lib-scylla.mount, not in /etc/fstab, it likely does nothing (possibly lies and looks in /proc/mounts and is okay).
> 
> Well, current implementation of scylla_fstrim_setup is not rely on fstrim.timer, it unconditionally enables scylla-fstrim.timer and it directly runs `fstrim /var/lib/scylla` on our own fstrim script (scylla_fstrim), so it should be fine.
> 
> It does something like this:
> 
> ```
>     for d in mountpoints:
>         print("Running fstrim on {} ...".format(d))
>         res = subprocess.call(["fstrim", d])
> ```
> 
> https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_fstrim#L40
> 
> Note that we only run scylla_fstrim_setup when online discard is disabled:
> 
> ```
>         # no need for fstrim if online discard is enabled
>         fstrim_setup = fstrim_setup and not online_discard
>         fstrim_setup = interactive_ask_service('Do you want to enable fstrim service?', 'Yes - runs fstrim on your SSD. No - skip this step.', fstrim_setup)
>         args.no_fstrim_setup = not fstrim_setup
>         if fstrim_setup:
>             run_setup_script('fstrim', 'scylla_fstrim_setup')
> ```
> 
> https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_setup#L510

Closing as invalid per above. I forgot all about scylla_fstrim.
