### ISSUE TITLE
implement sstablelevelreset as a scylla native tool

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15038]
`sstablelevelreset` is still being used by dtest. see also https://cassandra.apache.org/doc/latest/cassandra/tools/sstable/sstablelevelreset.html . 

this tool mutates the statistics component. see also `stats_metadata` in `sstables/types.hh`.

**Comment by denesb** [comment]
No, we don't have a replacement, but if needed, I think it would be quite easy to write one, as a new command to `scylla sstable`.

**Comment by fruch** [comment]
probably would suggest updating: 
https://opensource.docs.scylladb.com/stable/operating-scylla/admin-tools/ 
https://opensource.docs.scylladb.com/stable/using-scylla/cassandra-compatibility.html
with all the new options available 

beside those this tool isn't mentioned in any procedure or in any bug report in scylla.
only related to dtest
https://github.com/scylladb/scylla-tools-java/issues?q=is%3Aissue+sstablelevelreset+is%3Aclosed

**Comment by tchaikov** [comment]
@fruch hi Israel, thank you for referencing https://opensource.docs.scylladb.com/stable/using-scylla/cassandra-compatibility.html . that document includes `/operating-scylla/_common/tools_index.rst`. so i think it's been taken care of. i will update this document when adding the deprecation notices, for instance: #15040

> beside those this tool isn't mentioned in any procedure or in any bug report in scylla. only related to dtest https://github.com/scylladb/scylla-tools-java/issues?q=is%3Aissue+sstablelevelreset+is%3Aclosed

this is a very good point. but since we mentioned in the document. and our users and field engineers might still have the impression that these tools are available some day in future, and end up with a 404! so i think, we should be explicitly deprecate them and point these (potential) users to their alternatives, yeah, by giving them an HTTP 301.

**Comment by tchaikov** [comment]
> No, we don't have a replacement, but if needed, I think it would be quite easy to write one, as a new command to `scylla sstable`.

thanks. i will add it once i have more free cycles. the only reason why we need it is that dtest is using it, and by disabling uuid generation option in the test, we create a small gap in our product and test.

**Comment by denesb** [comment]
This tool is not in use, we will retire it without a native successor.
