### ISSUE TITLE
Offstrategy compaction must piggyback cleanup on reshape when invoked from the cleanup path

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15041]
perform_offstrategy is called from try_perform_cleanup
when there are sstables in the maintenance set that require
cleanup.

try_perform_clean first scans both the main and maintenance sets,
looking for sstables that require cleanup, and it calls perform_offstrategy
if any sstable in the maintenance set requires cleanup, and it expects offstrategy,
in this case, to piggyback cleanup on reshape compactio, based on the owned_ranges_ptr
try_perform_clean sets up in the compaction_state.

Currently, offstrategy compaction ignores the owned ranges ptr in compaction_state
and so, no cleanup is done during reshape and the reshape output sstable(s)
will contain disowned tokens, which are not cleaned up, since try_cleanup_compaction
does not scan the reshape output sstable(s).  If it would, they would be added to
`sstables_requiring_cleanup`, but this is less efficient, since it will require yet another
pass over the data, while piggybacking cleanup on reshape does that in a single pass.

**Comment by bhalevy** [comment]
The severity is high since this may cause data resurrection.
But priority can be P2 IMO since the combination of events is quite rare.
In any case, I'm testing the fix right now, so it doesn't matter much :)
And it doesn't need backporting since it's confined to master and doesn't exist in 5.2 and earlier (that have https://github.com/scylladb/scylladb/issues/9559 instead which is too risky to backport)

**Comment by bhalevy** [comment]
I'm also improving the `test_mv_resurrected_rows_after_decommission_interrupt` dtest to reproduce this issue.

**Comment by bhalevy** [comment]
Adding `Backport candidate` label.
I don't know why automation didn't add it...

**Comment by denesb** [comment]
@bhalevy is this part of the cleanup backport series? If not, please prepare a backport PR agasint 5.2.
