### ISSUE TITLE
materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_with_resharding_low_to_half_test is flaky

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15057]
Reported in: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6401/testReport/junit/materialized_views_test/TestInterruptBuildProcess/Tests___Sanity_Tests_RAFT___test_interrupt_build_process_with_resharding_low_to_half_test/

**Comment by nyh** [comment]
I don't know how to debug this. It seems this test usually succeeds in two minutes, but just once failed after more than 6 minutes - timing out a 5-minute wait for the view to be built.

Let's wait until we have another failure of this test and better understand if this common, if it's specific to the RAFT run, maybe related to the boot speedup, or what.

@fruch why does https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6401/testReport/junit/materialized_views_test/TestInterruptBuildProcess/Tests___Sanity_Tests_RAFT___test_interrupt_build_process_with_resharding_low_to_half_test/ contain only the exception, and not any other message printed by the test (I see those tests like to use loggers and log thing)? Where can I find those logs?

**Comment by denesb** [comment]
Seen again at: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3496/testReport/junit/materialized_views_test/TestInterruptBuildProcess/Tests___Sanity_Tests___test_interrupt_build_process_with_resharding_half_to_max_test/

**Comment by fruch** [comment]
node is getting stuck at boot:
```
INFO  2023-09-05 22:12:24,155 [shard  0:stre] schema_tables - Schema version changed to cf82dfdd-8a4a-3c33-a770-5ce0b8db295e
INFO  2023-09-05 22:12:24,160 [shard  3:comp] compaction - [Compact system.scylla_local 4a7cbe00-4c39-11ee-a289-2e98cca1f3d6] Compacting [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-shr0j41w/test/node3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3g94_1poo_0xfpc2gzchhkzq3rh2-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-shr0j41w/test/node3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3g94_1poo_0vi9c2gzchhkzq3rh2-big-Data.db:level=0:origin=compaction]
INFO  2023-09-05 22:12:24,167 [shard  3:comp] compaction - [Compact system.scylla_local 4a7cbe00-4c39-11ee-a289-2e98cca1f3d6] Compacted 2 sstables to [/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-shr0j41w/test/node3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3g94_1poo_0yakh2gzchhkzq3rh2-big-Data.db:level=0]. 64kB to 59kB (~90% of original) in 5ms = 12MB/s. ~256 total partitions merged to 2.
INFO  2023-09-05 22:26:30,819 [shard  0:main] compaction_manager - Asked to stop
INFO  2023-09-05 22:26:30,819 [shard  0:main] init - Shutting down group 0 service
INFO  2023-09-05 22:26:30,819 [shard  0:main] compaction_manager - Stopped
INFO  2023-09-05 22:26:30,819 [shard  1:main] compaction_manager - Asked to stop
INFO  2023-09-05 22:26:30,819 [shard  4:main] compaction_manager - Asked to stop
```

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4282/artifact/logs-full.release.011/1693952793834_materialized_views_test.py%3A%3ATestInterruptBuildProcess%3A%3Atest_interrupt_build_process_with_resharding_half_to_max_test/node3.log/*view*/

note that this test is using `--smp 17 --memory 8704M`

**Comment by nyh** [comment]
When reporting flaky tests, please write the different pieces of the test name in a way that github's search engine can search them. Right now, I can't seach for "TestInterruptBuildProcess" and find this issue. After I write this comment, it will be searchable :-)
Anyway, here is a searchable list of tests that are mentioned in this issue:
* `materialized_views_test`.`TestInterruptBuildProcess`.`test_interrupt_build_process_with_resharding_low_to_half_test`
* `materialized_views_test`.`TestInterruptBuildProcess`.`test_interrupt_build_process_with_resharding_half_to_max_test`

**Comment by nyh** [comment]
> node is getting stuck at boot:

Indeed, do we know if this is also the reason of the first failure reported in this issue (I couldn't find its logs).

In the new log, https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4282/artifact/logs-full.release.011/1693952793834_materialized_views_test.py%3A%3ATestInterruptBuildProcess%3A%3Atest_interrupt_build_process_with_resharding_half_to_max_test/node3.log/*view*/ 
we can indeed see that at 22:12:24,167 Scylla just hung. It never printed the log message "Starting listening for CQL clients", Which dtest waits for.

Soon before hanging, I see the log message "storage_service - waiting for schema information to complete".  This is from `storage_service::wait_for_ring_to_settle()`, and has what appears can be an endless loop:
```c++
        slogger.info("waiting for schema information to complete");
        while (!_migration_manager.local().have_schema_agreement()) {
            co_await sleep_abortable(std::chrono::milliseconds(10), _abort_source);
        }
```

@asias is there a possibility that when you have a lot of shards, somehow have_schema_agreement() or do resharding can always return false? Or something? I don't know how to debug this.

In any case, this failure seems to be completely unrelated to materialized views or view build or resharding - the boot hangs before the test manages to write anything to the database - before any views or resharding or anything like that ever happen. The same thing can probably happen without MV at all though maybe (just a guess...) it's related to large number of shards. @fruch do we have tests that run a large number of shards without MV?

**Comment by fruch** [comment]
Out of the back of my head, I don't think we do other tests that do such a high number of smp

Also it's much more resources the the estimation we are doing for the parally running, i.e. we calculate the number of cpus and amount of memory, and in our machines we run 5 tests in parallel, we don't know which tests and how much resources they might be using.

**Comment by dani-tweig** [comment]
@fruch , does this problem keep occurring? (it has not been mentioned for nearly a year)

**Comment by fruch** [comment]
> @fruch , does this problem keep occurring? (it has not been mentioned for nearly a year)

Those are not in gating, hence running much less than gating tests.

But would need to check history of it, if people didn't report here, doesn't mean it's not still happening

**Comment by fruch** [comment]
last time this test failed was on debug runs, and it was May 7:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/9b6695f0-42da-11ef-81c7-3986d18dafd5

and it was cause one node didn't started:
```
>           raise AssertionError(f"Unexpected errors found: {found_errors}")
E           AssertionError: Unexpected errors found: [('node1', ['ERROR 2024-05-06 22:52:42,416 [shard  0:main] init - Startup failed: service::raft_operation_timeout_error (group [ca61a0a0-0bfa-11ef-b8f8-203226b0a0ac] raft operation [read_barrier] timed out, there is no raft quorum, total voters count 3, alive voters count 1, dead voters [127.0.86.2,127.0.86.3])'])]
```
doesn't look similar to the reported issue above.

so yes, this didn't happened in the last 3 months.

**Comment by dani-tweig** [comment]
Closing.
If this occurs again, please reopen.
