### ISSUE TITLE
"nodetool stop RESHAPE" stops individual task, but doesn't abort the whole operation

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#15058]
On reshape on boot, we want "nodetool stop" to abort the whole reshape operation, rather than only stopping individual tasks. Otherwise, it's not helping to bypass reshape on boot.

```
[shard 13] compaction_manager - Stopping 1 tasks for 1 ongoing compactions for table ... and type=Reshape due to user request
[shard 13] compaction - [Reshape ...] Reshaping of 8 sstables interrupted due to: sstables::compaction_stopped_exception (Compaction for ... was stopped due to: user request)
[shard 13] compaction_manager - Reshape compaction task 0x6040045ce150 for table ... [0x604003b32f90]: stopped, reason: Compaction for ... was stopped due to: user request
compaction - [Reshape ...] Reshaping [/var/lib/scylla/data/...]
```

**Comment by raphaelsc** [comment]
this new dtest reproduces the issue https://github.com/scylladb/scylla-dtest/pull/3510

@Deexie FYI

**Comment by roydahan** [comment]
> @roydahan do we have a test for this API?

Hopefully now we will have...

**Comment by DoronArazii** [comment]
@scylladb/scylla-maint please consider backport

**Comment by denesb** [comment]
What are the affected branches? I doubt 5.1 is affected. @Deexie ?

**Comment by mykaul** [comment]
> What are the affected branches? I doubt 5.1 is affected. @Deexie ?

https://github.com/scylladb/scylladb/issues/15058#issuecomment-1678943381 mentions 5.1.

**Comment by denesb** [comment]
Cherry-pick is not clean, not even to 5.2. @Deexie please open backport pull requests for 5.2 and 5.1.

**Comment by Deexie** [comment]
@denesb Here are PRs for 5.2: #15122 and 5.1: #15123

**Comment by denesb** [comment]
> @denesb Here are PRs for 5.2: #15122 and 5.1: #15123

Both are queued. Removing labels.
