### ISSUE TITLE
should error out when creating a keyspace with storage option referencing a endpoint not configured

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15074]
the endpoints of object storage backend are configured using with `--object-storage-config-file` option.  and we can create keyspace using the extension of storage option when creating keyspace like

```cql
CREATE KEYSPACE ks WITH REPLICATION = {'replication_factor'=1} AND STORAGE = {'type'='S3', 'endpoint': '127.0.0.1', 'bucket': 'testbucket'};
```
where "127.0.0.1" should exist in the YAML file specified as the argument of `--object-storage-config-file` option, like:
```yaml
endpoints:
- name: 127.0.0.1
  port: 45875
```
but if the endpoint specified in the "CREATE KEYSPACE" statement, scylla crashes with `std::out_of_range` exception.

would be ideal if we can detect this problem when handling the "CREATE KEYSPACE" in `statements::create_keyspace_statement::validate()`. but when handling the "CREATE KEYSPACE" CQL statement, we don't have access to `sstables_manager` class, which manages the endpoints and the S3 clients talking to them.

**Comment by xemul** [comment]
FIY: #13745
