### ISSUE TITLE
Some gossiper apis may return stale information from non-zero shards

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15088]
The gossiper propagates `_live_endpoints` and `_unreachable_endpoints` lazily from shard 0 to all other shards using
`replicate_live_endpoints_on_change`.

Also, this replication is not exception safe so it's even possible that on error, some shards will won't get updated due to bad_alloc, or that `_live_endpoints` will be copied and `_unreachable_endpoints` will hit OOM.
It would be a rare event but not impossible.

That said, the some gossiper apis like `get_down_endpoint` or `get_endpoint_downtime` call gossiper functions that look at the current shard's `_unreachable_endpoints` which may not be up-to-date, while `get_live_endpoint` calls `get_live_members_synchronized` that checks `_live_endpoints` on shard 0.
The latter was fixed by e35762241ac42016a5ea42c2a72034169a2abfee, but I'm not sure why the other apis weren't taken care of, or why no issue was opened.

**Comment by bhalevy** [comment]
Since the gossiper class derives from `peering_sharded_service`,
the simplest way to solve this, IMO, would be to use `g.container().invoke_on(0` in the api level to get the latest and greatest from shard 0.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/pull/14801 is also related.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/issues/15089 was opened for `replicate_live_endpoints_on_change` for not being exception safe.

**Comment by bhalevy** [comment]
Duplicate of https://github.com/scylladb/scylladb/issues/12261

**Comment by denesb** [comment]
Already backported to 5.2, removing label.
