### ISSUE TITLE
hints: send_one_hint: file_send_gate holder is released too early

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#15110]
It's released before the possible call to `on_hint_send_failure` in `then_wrapped`. As a result, the effects of `on_hint_send_failure` (`segment_replay_failed` flag) were not visible in `send_one_file` after `ctx_ptr->file_send_gate.close()`, so we could decide that the segment was sent in full and delete it even if sending of some hints led to errors.

**Comment by gusev-p** [comment]
fixed as part of [this PR](https://github.com/scylladb/scylladb/pull/14901)

**Comment by denesb** [comment]
Backported to 5.2.
