### ISSUE TITLE
Python driver can't connect to the node

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#15119]
`test/topology_experimental_raft/test_fencing.py`, if one changes `servers = [await manager.server_add(), await manager.server_add()]` to `servers = await asyncio.gather(manager.server_add(), manager.server_add())` the driver sometimes has problems connecting to the last node. The test fails on the line `host2 = (await wait_for_cql_and_get_hosts(manager.cql, [servers[2]], time.time() + 60))[0]`, the logs says `12:39:59.014 INFO> Driver hasn't yet learned about hosts: {'127.157.193.8'}`.

[origin](https://github.com/scylladb/scylladb/pull/14901#discussion_r1301452512)

**Comment by Annamikhlin** [comment]
seems the same failure in **master/build** - [https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1622/testReport/ju[…]lishArm___topology_experimental_raft_test_fencing_debug_1/](https://jenkins.scylladb.com/view/master/job/scylla-master/job/build/1622/testReport/junit/(root)/non-boost%20tests/Build__Test__Publish___buildTestPublishArm___topology_experimental_raft_test_fencing_debug_1/)

**Comment by mykaul** [comment]
@avelanarius - can your team look at this failure?

**Comment by mykaul** [comment]
- worth keeping open, if we haven't seen it for a few months? Closing for the time being, please re-open if needed.
