### ISSUE TITLE
raft topology: support or deprecate IPs for --ignore-dead-nodes in removenode and replace

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15126]
The follow-up to #15113

In #15113 I left 2 identical FIXMEs in `storage_service::raft_removenode` and `storage_service::raft_replace`:
```
// FIXME: IPs should be supported, but the current implementation of raft_address_map doesn't allow this.
// We can also deprecate the use of IPs with consistent topology.
```
The original `removenode` and `replace` operations support `--ignore-dead-nodes` with `host_id`s and IPs. #15113 added support for `--ignore-dead-nodes` to the Raft-based operations, but only with `host_id`s, because `raft_address_map` doesn't provide `IP->id` translation.

We need to decide how to proceed with IPs. As discussed in [#15113 (comment)](https://github.com/scylladb/scylladb/pull/15113#discussion_r1301253946), we have the following options:
- implementing support for IPs (then we must decide how to do the `IP->id` translation),
- no longer supporting IPs,
- deprecating support for IPs.

The last option is probably the best one.

Apart from the FIXMEs in `raft_removenode` and `raft_replace`, I left two simple TODOs in `test_raft_ignore_nodes.py` in #15113. The one in `test_raft_replace_ignore_nodes`:
```
# TODO: Currently, raft_replace doesn't support IPs in the ignore_dead_nodes_for_replace parameter.
# After fixing it, we should change one of the host ids in ignore_dead to IP to check that it also works.
```
The one in `test_raft_remove_ignore_nodes` is similar. If we implement support for IPs, they should also be done.

**Comment by kostja** [comment]
@bhalevy I thought we decided to deprecate the use of IP addresses in nodetool, could you please confirm? 
CC @tzach ^^

**Comment by bhalevy** [comment]
we still support both and just print a warning in scylla if the legacy option is used.

**Comment by kostja** [comment]
We can preserve best-effort support when we translate IP addresses to the host ids using the address map on the local node which received the nodetool request. If the translation is unsuccessful, the command will fail. @kbr-scylla @bhalevy WDYT?

**Comment by bhalevy** [comment]
Sounds reasonable to me.

**Comment by kbr-scylla** [comment]
> We can preserve best-effort support when we translate IP addresses to the host ids using the address map on the local node which received the nodetool request. If the translation is unsuccessful, the command will fail. @kbr-scylla @bhalevy WDYT?

For now yes (and this is what Patryk's PR is doing), but I think we should deprecate nevertheless (which Patryk's PR is also doing).

We need to remove crap over time, not just add more.

**Comment by denesb** [comment]
Should we backport this?

**Comment by denesb** [comment]
> I think we can reconsider that after #16376 goes in (and after [26cbd28](https://github.com/scylladb/scylladb/commit/26cbd28883edb31e2d4db92bcbf56e0019ac7b23))

These are big changes, that we won't likely backport.

**Comment by kbr-scylla** [comment]
> Should we backport this?

Experimental so no.
