### ISSUE TITLE
The replication map used for view updates is not passed on to the storage proxy

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15144]
Currently, mutate_MV uses the effective replication map to calculate the endpoints needed for the operation, in
https://github.com/scylladb/scylladb/blob/93be4c0cb0f0c53fe0eb7cd4d06ba15a7fc01d29/db/view/view.cc#L1643

But later, down the stack, the storage_proxy retrieves potentially a newer version of the effectice_replication_map, in
https://github.com/scylladb/scylladb/blob/93be4c0cb0f0c53fe0eb7cd4d06ba15a7fc01d29/service/storage_proxy.cc#L3793
for `create_write_response_handler`.

It is possible, in rare corner cases, that endpoints selected at the top, will not be in the topology at the bottom, leading to cases like #15138.

This textbook fix for that today is carrying the e_r_m around along wit the endpoints down to `create_write_response_handler`.

**Comment by nyh** [comment]
Is this a duplicate of #14730 by @cvybhu ?

**Comment by bhalevy** [comment]
> Is this a duplicate of #14730 by @cvybhu ?

I think that #14730's scope is larger.

This issue is about the low-level mechanics of carrying the e_r_m ptr along with the endpoints requried for the view update, but I think that solving #14730 may require synchronization between topology changes and the use of the e_r_m, so that topology changes / node operations may need to implement a barrier that should block getting effective_replication_map references for write until outstanding effective_replication_map ptrs are in use for writes.
And then the "master" replication maps can change by adding pending nodes and writes can resume getting e_r_m ptrs.

I'm not sure how that is going to work with tablets and tablet migration.

Cc @tgrabiec @gleb-cloudius @kbr-scylla

**Comment by gleb-cloudius** [comment]
Why do we need to block getting effective_replication_map? Topology change has a barrier that waits for old effective_replication_map to stop been used while allowing getting new effective_replication_maps that reflect new topology.

**Comment by gleb-cloudius** [comment]
> > Why do we need to block getting effective_replication_map? Topology change has a barrier that waits for old effective_replication_map to stop been used while allowing getting new effective_replication_maps that reflect new topology.
> 
> [#14730 (comment)](https://github.com/scylladb/scylladb/issues/14730#issuecomment-1677000151) If I understood the problem correctly.

Waiting for requests with old effective_replication_map before streaming is enough.

**Comment by cvybhu** [comment]
> Is this a duplicate of https://github.com/scylladb/scylladb/issues/14730 by @cvybhu ?

It's very very similar. I opened my issue because I saw that e_r_m isn't carried further in `mutate_MV`.
They might be equal, AFAIU passing the e_r_m to storage proxy is all that's needed to ensure that view updates keep the e_r_m as long as needed.

**Comment by bhalevy** [comment]
Duplicate of #14730
