### ISSUE TITLE
Consistent-topology-changes: failed with exception (node state is bootstrapping): std::runtime_error (failed status returned from when second node is bootstrapping 

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#15152]
*Installation details*
Scylla version (or git commit hash): 5.4.0~dev-0.20230821.a4e7f9bed087
Cluster size: 2

If enable --consistent-schema-changes and --experimental-features:consistent-topology-changes and run any dtest test with 2 or more nodes, during cluster start and bootstraping 2nd node next error messages appeared in log and maked test with error:
```
>           raise AssertionError('Unexpected errors found: {}'.format(found_errors))
E           AssertionError: Unexpected errors found: [('node1', ['ERROR 2023-08-24 15:10:18,107 [shard 0] storage_service - raft topology: send_raft_topology_cmd(stream_ranges) failed with exception (node state is bootstrapping): std::runtime_error (failed status returned from cf03a2dd-5e1e-4ae0-9274-4ceb5cfc83f9/127.0.59.2)']), ('node2', ['ERROR 2023-08-24 15:10:18,107 [shard 0] storage_service - raft topology: raft_topology_cmd failed with: std::runtime_error ({shard 0: std::runtime_error (repair[1168c03a-2992-431d-8b38-64b2c80d4fa6]: 513 out of 513 ranges failed, keyspace=system_distributed_everywhere, tables={cdc_generation_descriptions_v2}, repair_reason=bootstrap, nodes_down_during_repair={127.0.59.1}, aborted_by_user=false, failed_because=unknown)})'])]

dtest_setup.py:546: AssertionError
```

`ERROR 2023-08-24 15:10:18,107 [shard 0] storage_service - raft topology: raft_topology_cmd failed with: std::runtime_error ({shard 0: std::runtime_error (repair[1168c03a-2992-431d-8b38-64b2c80d4fa6]: 513 out of 513 ranges failed, keyspace=system_distributed_everywhere, tables={cdc_generation_descriptions_v2}, repair_reason=bootstrap, nodes_down_during_repair={127.0.59.1}, aborted_by_user=false, failed_because=unknown)})`

example of dtest to run:
`pytest -v -s --scylla-version=unstable/master:latest --consistent-cluster-management --experimental-features=consistent-topology-changes replace_address_test.py::TestReplaceAddress::test_shutdown_all_and_replace_node[use_endpoint-rbo_enabled]
`

**Comment by patjed41** [comment]
Such errors also appear in `test.py`, for example, in `test_replace.py`.

The 2nd bootstrapping node cannot successfully finish the repair procedure multiple times. There are warnings like:
```
WARN  2023-08-28 12:22:22,285 [shard 0] repair - repair[b70094bd-b5a7-4164-b867-d5aa29aedc0a]: Repair 1 out of 165 ranges, keyspace=system_traces, table={sessions, node_slow_log_time_idx, sessions_time_idx, node_slow_log, events}, range=(8981040170036998442,+inf), peers={127.69.10.1}, live_peers={}, status=skipped_no_live_peers
```
The interesting part is `peers={127.69.10.1}, live_peers={}, status=skipped_no_live_peers`. Then, we can see in the logs:
```
INFO  2023-08-28 12:22:22,369 [shard 0] gossip - InetAddress 127.69.10.1 is now UP, status = NORMAL
```
After that, the repair procedure succeeds.

It seems like the bootstrap procedure is racing with gossiper marking nodes as UP. 51cec2be860378e54bd811f14e56e384927976bb has fixed this, but only for the gossiper-based topology. For the Raft-based topology, it hasn't been fixed yet, but 51cec2be860378e54bd811f14e56e384927976bb has left such a note:
```
For Raft-based topology, the node joining procedure will be coordinated by the topology coordinator right
from the start and it will be the coordinator who issues the 'wait for node to see other live nodes'.
```
So, this issue is known and planned to be fixed in the future, but I don't know the details. @kbr-scylla

**Comment by kbr-scylla** [comment]
Thanks @patjed41.

cc @piodul @gleb-cloudius 

> For Raft-based topology, the node joining procedure will be coordinated by the topology coordinator right
from the start and it will be the coordinator who issues the 'wait for node to see other live nodes'.

I wrote that comment anticipating that the new procedure based on JOIN RPC would do something like this.

Does https://github.com/scylladb/scylladb/pull/15196 solve this? If not, I'll create a follow-up issue.

**Comment by piodul** [comment]
> I wrote that comment anticipating that the new procedure based on JOIN RPC would do something like this.
> 
> Does #15196 solve this?

No, I don't think so. The last step of the JOIN RPC for the joining node is to start its group 0 server, so it doesn't have direct access to `system.topology` during the procedure.

**Comment by soyacz** [comment]
I tried another test which doesn't do much topology changes - just spins up 3 node cluster and found this issue too.
From the other hand, creating cluster with ccm cli doesn't generate these errors.

**Comment by gleb-cloudius** [comment]
> > I wrote that comment anticipating that the new procedure based on JOIN RPC would do something like this.
> > Does #15196 solve this?
> 
> No, I don't think so. The last step of the JOIN RPC for the joining node is to start its group 0 server, so it doesn't have direct access to `system.topology` during the procedure.

After starting the group0 it should wait for all normal nodes in the topology to be UP in gossiper. I had to writ such  code in error recovery patch otherwise bootstrap fails just because the gossiper is slow.

**Comment by soyacz** [comment]
@aleksbykov as a workaround (until this is fixed) try adding `@pytest.mark.no_boot_speedups` - helped for my case.

**Comment by piodul** [comment]
> After starting the group0 it should wait for all normal nodes in the topology to be UP in gossiper. I had to writ such code in error recovery patch otherwise bootstrap fails just because the gossiper is slow.

This will work for the current procedure but won't for JOIN RPC. The joining node doesn't have access to system.topology during the handshake, and after the handshake the coordinator will start bootstrapping the new node immediately. I suppose the joining node could do the wait while handling JOIN_NODE_RESPONSE, but it will have to receive the list of nodes to wait for in the arguments for the RPC.

**Comment by gleb-cloudius** [comment]
>  I suppose the joining node could do the wait while handling JOIN_NODE_RESPONSE, but it will have to receive the list of nodes to wait for in the arguments for the RPC.

Why? Doesn't it part of group0 at this point. so access to the up-to-date topology is just `read_barrier` call away?

**Comment by piodul** [comment]
> Why? Doesn't it part of group0 at this point. so access to the up-to-date topology is just `read_barrier` call away?

The `JOIN_NODE_RESPONSE` RPC contains a list of features that the new node should enable. AFAIK we want to enable them before actually joining the raft group 0. Therefore the topology coordinator can only add the new node to the group 0 configuration after the RPC finishes.

**Comment by gleb-cloudius** [comment]
> > Why? Doesn't it part of group0 at this point. so access to the up-to-date topology is just `read_barrier` call away?
> 
> The `JOIN_NODE_RESPONSE` RPC contains a list of features that the new node should enable. AFAIK we want to enable them before actually joining the raft group 0. Therefore the topology coordinator can only add the new node to the group 0 configuration after the RPC finishes.

A node does not need to _enable_ any features before joining group0. We only need to make sure that the node supports all enabled features before adding it to the group0. A node suppose to be able to handle not enabled, but supported features.

**Comment by denesb** [comment]
This looks like an improvement, not backport material. @kbr-scylla please re-add the label if you disagree.

**Comment by kbr-scylla** [comment]
major change + experimental
