### ISSUE TITLE
sstable_compaction_test.simple_backlog_controller_test is flaky

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15162]
The build https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3253/ failed on `sstable_compaction_test.simple_backlog_controller_test` due to an abandoned failed future.

Logs:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3253/artifact/testlog/x86_64/dev/boost.sstable_compaction_test.simple_backlog_controller_test.2.log

The culprit is `seastar::gate_closed_exception` visible in the logs.

This failure reproduces locally (with `--fail-on-abandoned-failed-futures=true` enabled for `sstable_compaction_test`). It happens once in a few hundred runs, but since this test is very fast, it's quite easy to reproduce.

There are also a lot of warnings like this in the logs:
```
WARN  2023-08-24 18:54:53,664 [shard 0] sstable - Unable to delete /jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/dev/scylla-f38b50bb-c21f-413b-8d32-83042faa17d4/me-299-big-TOC.txt because it doesn't exist.
```
They seem to appear in every run of this test. I don't know if they are related to the error. They may also indicate a different problem.

**Comment by kbr-scylla** [comment]
@raphaelsc could you please take a look, or find someone who could look at this test?

**Comment by raphaelsc** [comment]
> The build https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3253/ failed on `sstable_compaction_test.simple_backlog_controller_test` due to an abandoned failed future.
> 
> Logs: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3253/artifact/testlog/x86_64/dev/boost.sstable_compaction_test.simple_backlog_controller_test.2.log
> 
> The culprit is `seastar::gate_closed_exception` visible in the logs.
> 
> This failure reproduces locally (with `--fail-on-abandoned-failed-futures=true` enabled for `sstable_compaction_test`). It happens once in a few hundred runs, but since this test is very fast, it's quite easy to reproduce.
> 
> There are also a lot of warnings like this in the logs:
> 
> ```
> WARN  2023-08-24 18:54:53,664 [shard 0] sstable - Unable to delete /jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/dev/scylla-f38b50bb-c21f-413b-8d32-83042faa17d4/me-299-big-TOC.txt because it doesn't exist.
> ```
> 
> They seem to appear in every run of this test. I don't know if they are related to the error. They may also indicate a different problem.

The warning is benign. It seems a race between compaction manager stop and pending compactions. Will take a look next week.
