### ISSUE TITLE
raft: a node with crashed/non-existing group 0 server is still considered to be alive

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15167]
I don't know if it's a "real" problem, but I found this weird and unexpected.

Start a 2-node cluster in Raft mode, one of them becomes a leader. Then crash the other one's group 0 server through an error injection or restart the other node into RECOVERY mode so it doesn't start the Raft server.

The first node will keep being a leader, even though theoretically there is no quorum -- it should step down.

This happens because failure detector RPCs are answered positively even though there is no group 0 server running on the node.

Maybe it's not a problem, but maybe we should check whether group 0 is still "running" or fail the failure detector verb?

cc @kostja @gleb-cloudius

**Comment by gleb-cloudius** [comment]
Our failure detector is shared. There may be other groups running on the node where group0 is dead. What _I_ find weird and unexpected is that we insist on continuing running the node with a dead group0. We should just kill it.

**Comment by kostja** [comment]
I think for now it would suffice to check for group0 state in node liveness check as @kbr-scylla suggests. For other groups, when we have them, we can perhaps make sure the group is alive as long as the node is alive (if tablet is dead, we will restream it or move away from the node).

I think we had a discussion as to whether we should crash the entire node when group0 crashes and it was decided that the node can still serve reads e.g. for streaming/data movement/repair, so it's not the best idea to crash it - rather, it should enter a special state with limited set of supported functionality (we have not decided which set).

**Comment by gleb-cloudius** [comment]
> I think for now it would suffice to check for group0 state in node liveness check as @kbr-scylla suggests.

There is no need to push the solution down the road.

> For other groups, when we have them, we can perhaps make sure the group is alive as long as the node is alive (if tablet is dead, we will restream it or move away from the node).
> 
> I think we had a discussion as to whether we should crash the entire node when group0 crashes and it was decided that the node can still serve reads e.g. for streaming/data movement/repair, so it's not the best idea to crash it - rather, it should enter a special state with limited set of supported functionality (we have not decided which set).

That was when the only thing working through group0 was schema and even then that was a cowardy cop-out :) The more things we put into group0 the less it make sense to keep the node alive without it. 

But I do not think there is a controversy about the RECOVERY mode. A node in this mode should not pretend to be alive for raft purposes (not sure how it can be implemented when we will unify gossiper fd with raft one).

**Comment by kbr-scylla** [comment]
> not sure how it can be implemented when we will unify gossiper fd with raft one

ah, good observation. The node must stay alive for things like storage_proxy (which today use gossiper fd), but "dead" for group 0...
