### ISSUE TITLE
raft: leader changes not logged after cluster restart

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15166]
We should be seeing messages like:
```
raft_group0 - gaining leadership
```
or
```
raft_group0 - losing leadership
```

but they don't seem to appear after e.g. a cluster restart.

**Comment by avikivity** [comment]
Is the only effect the loss of these messages, or is there more?

**Comment by patjed41** [comment]
> Is the only effect the loss of these messages, or is there more?

Only the loss of these messages.

**Comment by denesb** [comment]
@patjed41 please evaluate for backport.

**Comment by kbr-scylla** [comment]
Very minor problem, no need to backport.
