### ISSUE TITLE
Docs: improve db/config.cc properties page

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylladb#15161]
## Motivation

Improve [db/config.cc properties](https://opensource.docs.scylladb.com/master/reference/db-config.html) based on maintainers feedback.

## Acceptance criteria

- [x] Define value status, unused / used, liveness, ...
- [x] Filter out unused values: Move them to a separate section "compatibility options" (or something similar).
- [x] Add type.
- [x] Instead of using list-table, how about using field lists.
- [x] Show options as links.
- [ ] Skip inline comments like /* hello world */. see "request_scheduler_id" in the rendered document

**Comment by dgarcia360** [comment]
I'm taking this issue

**Comment by tzach** [comment]
>  Define value status, unused / used, liveness, ...

Use Glossert terms to define this issue, link to the glossary

>  Instead of using list-table, how about using field lists.

It's better or worse. Better use a dedicated PR to test this idea

**Comment by dgarcia360** [comment]
> Define value status, unused / used, liveness, ...

I've linked to the glossary in https://github.com/scylladb/scylladb/pull/15164

We can try to add a nicer tooltip once we work on https://github.com/scylladb/sphinx-scylladb-theme/issues/873

>  Instead of using list-table, how about using field lists.

Moved this changes to https://github.com/scylladb/scylladb/pull/15205

**Comment by dgarcia360** [comment]
Open question:

> the parser can be improved to skip inline comments like /* hello world */. see "request_scheduler_id" in the rendered document

Now it renders:

Default value: {/* keyspace */}

How should it be displayed? Options:

a) Default value: keyspace
b) Default value: { keyspace }
c) Default value: None
