### ISSUE TITLE
scylla_fstrim_setup: should not disable fstrim.timer

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylladb#15176]
fstrim.timer run fstrim just for the block device listed on fstab (and also the block device doesn't use online discard).
So it will not run fstrim for /var/lib/scylla since we don't have fstab entry.
On scylla_fstrim_setup, we  currently doing:
```
    if is_redhat_variant() or is_arch() or is_suse_variant():
        systemd_unit('fstrim.timer').disable()
```
https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_fstrim_setup#L21
It's likely mistake.

I think this was for avoid running fstrim on /var/lib/scylla from both scylla-fstrim.timer and fstrim.timer, but since fstrim.timer actually don't do that, disabling the service doesn't make sense.
We should just drop these lines, and let run fstrim.timer for rootfs (and also for other filesystems not related scylla).

related #15033

**Comment by mykaul** [comment]
@syuu1228 - should be backported to 5.2, no?
