### ISSUE TITLE
gossiper: on_dead notifications are not called after remove_endpoint

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15178]
Since 75d1dd3a762638686142e93d4a5cf2f6bc402eba
gossiper::convict will no longer call `mark_dead`
(e.g. when called from the failure detection loop
after a node is stopped following decommission)
and therefore the on_dead notification won't get called.

These are imporant to clean up after the node is dead
e.g. in storage_proxy::on_down which cancels all
respective write handlers.

This is visible since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/339/testReport/bootstrap_test/TestBootstrap/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split013___test_decommissioned_wiped_node_can_join/
```
        # Decommision the new node and wipe its data
        logger.info("Decommissioning node4")
        mark = node1.mark_log()
        node4.decommission()
        logger.debug("Stopping node4")
        node4.stop(wait_other_notice=False)
>       node1.watch_log_for("{} is now (dead|DOWN)".format(node4.address()), from_mark=mark)
...
>                       raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str(
                            [e.pattern for e in tofind]) + ":\n" + reads[:50] + f".....\nSee {filename} for remainder")
E                       ccmlib.node.TimeoutError: 24 Aug 2023 13:39:02 [node1] Missing: ['127.0.33.4 is now (dead|DOWN)']:
```

**Comment by denesb** [comment]
No affected branches, no backport needed.
