### ISSUE TITLE
make_entry_descriptor does not understand uuid sstable

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#15187]
When loading a uuid sstable:

```
auto& table = db.find_column_family(meta.table);
auto& manager = table.get_sstables_manager();
auto ed = sstables::entry_descriptor::make_descriptor(table.dir(), data_filename, table.schema()->ks_name(), table.schema()->cf_name());
auto sst = manager.make_sstable(table.schema(), table.dir(), local, ed.generation, sstables::sstable_state::normal, ed.version, ed.format);
```

I saw the following:

```
error=sstables::malformed_sstable_exception (invalid version for file /home/asias/src/cloudius-systems/scylla/mycluster/tmp/2/data/ks1a/tb-07e33540453811eea4c65cdd2cb9494e/me-3g8w_00qf_4pbog2i7h2c7am0uoe-big-Data.db. Name doesn't match any known version.
```

It seems the current code make_entry_descriptor() does not understand uuid sstable.

**Comment by asias** [comment]
@bhalevy @raphaelsc  FYI

**Comment by raphaelsc** [comment]
@tchaikov

**Comment by raphaelsc** [comment]
@asias I think the problem might be that fname param contains dir, not just file name. For the future, we should consider switching to std::filesystem

**Comment by asias** [comment]
> @asias I think the problem might be that fname param contains dir, not just file name. For the future, we should consider switching to std::filesystem

You are correct! After passing only the filename, it worked!

Perhaps we can provide a sstables::entry_descriptor::make_descriptor() that takes the full filename.

Yes, std::filesystem::path is nicer.

**Comment by tchaikov** [comment]
yeah, fname should only contain the filename component in the path.

> Perhaps we can provide a sstables::entry_descriptor::make_descriptor() that takes the full filename.

lemme take care of it.

**Comment by tchaikov** [comment]
> make_entry_descriptor does not understand uuid sstable

@asias could you update the title to reflect the issue better?

**Comment by asias** [comment]
I am closing the issue since the original report was not an issue. The make_entry_descriptor understands uuid sstable. 

It is better to create a new issue for improvement to accept a single std::filesystem::path.
