### ISSUE TITLE
reader_concurrency_semaphore: deadlock between stop() and execution_loop()

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#15198]
Permits added to `_ready_list` remain there until executed by `execution_loop()`. But `execution_loop()` exits when `_stopped == true`, even though nothing prevents new permits from being added to `_ready_list` after `stop()` sets `_stopped = true`.

Thus, if there are reads concurrent with `stop()`, it's possible for a permit to be added to `_ready_list` after `execution_loop()` has already quit. Such a permit will never be destroyed, and `stop()` will forever block on `_permit_gate.close()`.

Refs https://github.com/scylladb/scylla-enterprise/issues/3298

**Comment by michoecho** [comment]
> @scylladb/scylla-maint please consider backport to active OSS versions

I think this can't be cherry-picked to past versions cleanly. I will likely have to prepare the backports myself.

**Comment by denesb** [comment]
I can try to cherry-pick. I will likely be able to resolve conflicts as I know the code well.

**Comment by denesb** [comment]
Backported to 5.2 and 5.1.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
