### ISSUE TITLE
test.py: add topology test for `gossiper/endpoint/live` and `gossiper/endpoint/down`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15223]
There were issues with these endpoints -- see https://github.com/scylladb/scylladb/issues/12261 and https://github.com/scylladb/scylladb/issues/15088 -- which were fixed recently (https://github.com/scylladb/scylladb/pull/15093, https://github.com/scylladb/scylladb/pull/12540, https://github.com/scylladb/scylladb/pull/13240).

We should have at least a simple 3-node topology test, preferably run it in a single mode so it doesn't slow down our test suite significantly (preferably outside debug), to test these endpoints.

`gossiper/endpoint/live` is already being used in some test.py tests as utility to help test other things (grep for `get_alive_endpoints`), but it is not tested as a feature on its own. `gossiper/endpoint/down` is not tested at all.

cc @asias @bhalevy

**Comment by kbr-scylla** [comment]
We can add similar function to this:
```python3
    async def get_alive_endpoints(self, node_ip: str) -> list:
        """Get the list of alive nodes according to `node_ip`."""
        data = await self.client.get_json(f"/gossiper/endpoint/live", host=node_ip)
        assert(type(data) == list)
        return data
```

for `down` endpoint.

**Comment by DoronArazii** [comment]
@bhalevy can you help here

**Comment by bhalevy** [comment]
@Deexie please add to your queue

**Comment by mykaul** [comment]
@Deexie - do we need a 5.2 backport for this?

**Comment by Deexie** [comment]
> @Deexie - do we need a 5.2 backport for this?

This change is just a new test - I do not know the backporting policies for test.

Both the tested endpoints and topology suite were in the 5.2
