### ISSUE TITLE
system_auth should be replicated automatically

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15221]
Today, adding nodes / DCs to the clusters involves a manual procedure to increase replication factor for `system_auth`.
See for example https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-node-to-cluster.html

Apart for being clunky and prone to human errors,
https://github.com/scylladb/scylladb/issues/5489 calls for serving CQL while the node is isolated
and to support that with authentication, we'll need auth tables to be fully replicated on all nodes.

**Comment by bhalevy** [comment]
@tgrabiec suggested putting `system_auth` in group0, like schema and topology.
> the question is whether it's ok for auth to return stale data. Local read is stale, unless you execute raft read barrier on each read

**Comment by bhalevy** [comment]
Cc @denesb

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/issues/1796 ? (and https://github.com/scylladb/scylladb/issues/12211 )

**Comment by mykaul** [comment]
cc @eliransin , @kostja - I believe it was recently discussed if it'll go to group0 or we'll start with something else.

**Comment by bhalevy** [comment]
> #1796 ? (and #12211 )

Yes.  This issue adds more motivation to https://github.com/scylladb/scylladb/issues/1796#issuecomment-462409455

**Comment by bhalevy** [comment]
> cc @eliransin , @kostja - I believe it was recently discussed if it'll go to group0 or we'll start with something else.

Not sure what was discussed, but we should eradicate vnode-based replication as we adopt tablets.

**Comment by bhalevy** [comment]
@mykaul who should own this issue?

**Comment by mykaul** [comment]
> @mykaul who should own this issue?

@ptrsmrn - is that in your domain? (and I believe a dup of existing / similar issues?)

**Comment by ptrsmrn** [comment]
> > @mykaul who should own this issue?
> 
> @ptrsmrn - is that in your domain? (and I believe a dup of existing / similar issues?)

@mykaul yes, it's auth, which is part of core-frontend. The issue falls under "move `system_auth` to RAFT" bag.

**Comment by kostja** [comment]
@bhalevy I don't see how we need auth in maintenance mode. On the contrary, I'd say maintenance should always run with AllowAllAuthenticator. So to me it's clearly a duplicate.

**Comment by bhalevy** [comment]
> @bhalevy I don't see how we need auth in maintenance mode. On the contrary, I'd say maintenance should always run with AllowAllAuthenticator. So to me it's clearly a duplicate.

no problem

**Comment by nuivall** [comment]
Resolved by https://github.com/scylladb/scylladb/pull/16578
