### ISSUE TITLE
test_value_affect_tracing_table: AssertionError: Error: probability=0.0 actual=0.002 diff=0.002 allowed=0

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15231]
The `test_value_affect_tracing_table` dtest started failing in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/345/testReport/nodetool_additional_test/TestGetTraceProbability/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_value_affect_tracing_table/
```
self = <nodetool_additional_test.TestGetTraceProbability object at 0x7fb33b11f290>
subtests = SubTests(ihook=<_pytest.config.compat.PathAwareHookProxy object at 0x7fb44908ced0>, suspend_capture_ctx=<bound method ...spended=False> _capture_fixture=None>>, request=<SubRequest 'subtests' for <Function test_value_affect_tracing_table>>)

    def test_value_affect_tracing_table(self, subtests):
        create_ks(self.session, 'ks', 2)
        create_cf(self.session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})
        prev_count = 0
        for valid_value in self.valid_values:
            with subtests.test(valid_value=valid_value):
                for node in (self.node1, self.node2, self.node3,):
                    set_node_probability(node, valid_value)
                probability_value = get_node_probability(self.node1)
>               prev_count = self.tracing_table_check(self.session, self.node2, probability_value,
                                                      self.valid_values[valid_value],
                                                      prev_count)

nodetool_additional_test.py:2769: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <nodetool_additional_test.TestGetTraceProbability object at 0x7fb33b11f290>
session = <cassandra.cluster.Session object at 0x7fb33ab1c850>
node = <ccmlib.scylla_node.ScyllaNode object at 0x7fb33b310e90>
probability = 0.0, num_keys = 500, prev_count = 11

    def tracing_table_check(self, session, node, probability, num_keys, prev_count):
        logger.info("Populating a table with {} keys...".format(num_keys))
        insert_c1c2_no_prepared(session, keys=range(num_keys))
        node.flush()
        node.flush()
        logger.info("Check that all tracing session have been flushed...")
        pattern = re.compile("INSERT INTO")
        tracing_query = SimpleStatement('SELECT parameters FROM system_traces.sessions')
        rows = rows_to_list(session.execute(tracing_query))
        count = functools.reduce(lambda x, y: x + y, map(lambda row: len(pattern.findall(row[0]['query'])), rows))
        calculated_probability = (count - prev_count) / num_keys
        diff = math.fabs(calculated_probability - probability)
        allowed_diff = self.valid_tolerance[probability]
        message = f"Error: probability={probability} actual={calculated_probability} diff={diff} allowed={allowed_diff}"
>       assert diff <= allowed_diff, message
E       AssertionError: Error: probability=0.0 actual=0.002 diff=0.002 allowed=0
E       assert 0.002 <= 0

nodetool_additional_test.py:2726: AssertionError
```

Scylla version 0bff96a61140

Need to bisect to see what commit introduced the regression and to decide whether scylla is at fault or maybe the test needs to be adjusted.

**Comment by DoronArazii** [comment]
@kbr-scylla can you please have a look

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/issues/14746#issuecomment-1676977659 mentions:
> scylla-master/next failed on Sanity Tests stage, for more details: https://jenkins.scylladb.com/job/scylla-master/job/next/6392/
> failed tests: 3 of 22612.
> 
> alternator_stream_tests.TestAlternatorStreams.test_verify_all_nodes_have_same_stream
botocore.errorfactory.InternalServerError: An error occurred (InternalServerError) when calling the BatchWriteItem operation (reached max retries: 0): Internal server error: exceptions::invalid_request_exception (cdc: attempted to get a stream from an earlier generation than the currently used one. With CDC you cannot send writes with timestamps too far into the past, because that would break consistency properties (write timestamp: 2023/08/14 07:31:24, current generation started at: 2023/08/14 07:31:24))

**Comment by bhalevy** [comment]
still being hit regularly on daily dtest-release runs

**Comment by bhalevy** [comment]
Hit again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/394/testReport/nodetool_additional_test/TestGetTraceProbability/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_value_affect_tracing_table/
```
AssertionError: Error: probability=0.0 actual=0.002 diff=0.002 allowed=0
assert 0.002 <= 0
```

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/next/6687/testReport/

```
self = <nodetool_additional_test.TestGetTraceProbability object at 0x7fd589e5a090>
subtests = SubTests(ihook=<_pytest.config.compat.PathAwareHookProxy object at 0x7fd693d17790>, suspend_capture_ctx=<bound method ...spended=False> _capture_fixture=None>>, request=<SubRequest 'subtests' for <Function test_value_affect_tracing_table>>)

    def test_value_affect_tracing_table(self, subtests):
        create_ks(self.session, 'ks', 2)
        create_cf(self.session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})
        prev_count = 0
        for valid_value in self.valid_values:
            with subtests.test(valid_value=valid_value):
                for node in (self.node1, self.node2, self.node3,):
                    set_node_probability(node, valid_value)
                probability_value = get_node_probability(self.node1)
>               prev_count = self.tracing_table_check(self.session, self.node2, probability_value,
                                                      self.valid_values[valid_value],
                                                      prev_count)

nodetool_additional_test.py:2805: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <nodetool_additional_test.TestGetTraceProbability object at 0x7fd589e5a090>
session = <cassandra.cluster.Session object at 0x7fd589f75fd0>
node = <ccmlib.scylla_node.ScyllaNode object at 0x7fd588c8a3d0>
probability = 1.0, num_keys = 500, prev_count = 5869

    def tracing_table_check(self, session, node, probability, num_keys, prev_count):
        logger.info("Populating a table with {} keys...".format(num_keys))
        insert_c1c2_no_prepared(session, keys=range(num_keys))
        node.flush()
        node.flush()
        logger.info("Check that all tracing session have been flushed...")
        pattern = re.compile("INSERT INTO")
        tracing_query = SimpleStatement('SELECT parameters FROM system_traces.sessions')
        rows = rows_to_list(session.execute(tracing_query))
        count = functools.reduce(lambda x, y: x + y, map(lambda row: len(pattern.findall(row[0]['query'])), rows))
        calculated_probability = (count - prev_count) / num_keys
        diff = math.fabs(calculated_probability - probability)
        allowed_diff = self.valid_tolerance[probability]
        message = f"Error: probability={probability} actual={calculated_probability} diff={diff} allowed={allowed_diff}"
>       assert diff <= allowed_diff, message
E       AssertionError: Error: probability=1.0 actual=1.014 diff=0.014000000000000012 allowed=0
E       assert 0.014000000000000012 <= 0
```

**Comment by tchaikov** [comment]
and again, see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4244/testReport/junit/nodetool_additional_test/TestGetTraceProbability/Tests___Sanity_Tests___test_value_affect_tracing_table/
```
self = <nodetool_additional_test.TestGetTraceProbability object at 0x7fec54842d10>
session = <cassandra.cluster.Session object at 0x7fec1c125790>
node = <ccmlib.scylla_node.ScyllaNode object at 0x7fec0e3bffd0>
probability = 1.0, num_keys = 500, prev_count = 5957

    def tracing_table_check(self, session, node, probability, num_keys, prev_count):
        logger.info("Populating a table with {} keys...".format(num_keys))
        insert_c1c2_no_prepared(session, keys=range(num_keys))
        node.flush()
        node.flush()
        logger.info("Check that all tracing session have been flushed...")
        pattern = re.compile("INSERT INTO")
        tracing_query = SimpleStatement('SELECT parameters FROM system_traces.sessions')
        rows = rows_to_list(session.execute(tracing_query))
        count = functools.reduce(lambda x, y: x + y, map(lambda row: len(pattern.findall(row[0]['query'])), rows))
        calculated_probability = (count - prev_count) / num_keys
        diff = math.fabs(calculated_probability - probability)
        allowed_diff = self.valid_tolerance[probability]
        message = f"Error: probability={probability} actual={calculated_probability} diff={diff} allowed={allowed_diff}"
>       assert diff <= allowed_diff, message
E       AssertionError: Error: probability=1.0 actual=1.08 diff=0.08000000000000007 allowed=0
E       assert 0.08000000000000007 <= 0
```

**Comment by bhalevy** [comment]
My conclusion from reading the dtest code is that it is broken in multiple ways and was broken from inception.
I'm not sure what caused us to see more failures now, but we just can't rely on the test until it's fixed
And it should be disabled till then.

**Comment by bhalevy** [comment]
@eliransin is tracing under your team's responsibilities?

**Comment by wmitros** [comment]
@bhalevy actually I think I mostly fixed this in https://github.com/scylladb/scylla-dtest/pull/3672

**Comment by bhalevy** [comment]
The dtest uses `with subtests.test` so the different subcases are running in parallel using the same cql session.

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/next/2612/

**Comment by avikivity** [comment]
Again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6691/

Why do we see this happening so often now? Maybe a regression?

**Comment by bhalevy** [comment]
> Again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6691/
> 
> Why do we see this happening so often now? Maybe a regression?

That's a good question.
What I could see testing locally that it just takes over a second for the tracing sessions query to stabilize as seen from the client side.  Frankly, I'm not sure how it's supposed to work.

We can try to bisect master.
From the jenkins history the regression may have started in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/345/testReport/junit/nodetool_additional_test/TestGetTraceProbability/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_value_affect_tracing_table/
Scylla version 0bff96a61140

**Comment by bhalevy** [comment]
I can't reproduce the relatively good results we saw on jenkins locally on my machine.
I'm really not sure what made it more flaky recently.
Maybe we run on faster test machines?
In any case, since the tracing sessions are flushed every 2 seconds and we don't have an api to force their flush, the test needs to wait for the results to stabilize after inserting data.

**Comment by raphaelsc** [comment]
Again: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4241/testReport/junit/nodetool_additional_test/TestGetTraceProbability/Tests___Sanity_Tests___test_value_affect_tracing_table/

```
AssertionError: Error: probability=1.0 actual=0.996 diff=0.0040000000000000036 allowed=0
assert 0.0040000000000000036 <= 0
```

**Comment by avikivity** [comment]
> > Again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6691/
> > Why do we see this happening so often now? Maybe a regression?
> 
> That's a good question. What I could see testing locally that it just takes over a second for the tracing sessions query to stabilize as seen from the client side. Frankly, I'm not sure how it's supposed to work.
> 
> We can try to bisect master. From the jenkins history the regression seen in dtest-release seem to have started in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/345/testReport/junit/nodetool_additional_test/TestGetTraceProbability/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_value_affect_tracing_table/ Scylla version [0bff96a](https://github.com/scylladb/scylladb/commit/0bff96a61140529cdbf012ffd02286e70fa84094) (There were similar failures before but they were sparser)

We have in the past few days many more reproductions. So maybe it was somewhat flaky before and very flaky now.

What caused the change?

**Comment by avikivity** [comment]
Seen again: https://github.com/scylladb/scylladb/pull/15756#issuecomment-1768383472

**Comment by mykaul** [comment]
And https://github.com/scylladb/scylladb/pull/15756#issuecomment-1768383472

Can we just remove it from CI for t he time being?

**Comment by bhalevy** [comment]
> And [#15756 (comment)](https://github.com/scylladb/scylladb/pull/15756#issuecomment-1768383472)
> 
> Can we just remove it from CI for t the time being?

There's no need to IMO since https://github.com/scylladb/scylla-dtest/pull/3675 fixed the test in a reliable way and there's agreement on it.

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6692/testReport/

**Comment by bhalevy** [comment]
> > > And [#15756 (comment)](https://github.com/scylladb/scylladb/pull/15756#issuecomment-1768383472)
> > > Can we just remove it from CI for t the time being?
> > 
> > 
> > There's no need to IMO since [scylladb/scylla-dtest#3675](https://github.com/scylladb/scylla-dtest/pull/3675) fixes the test in a reliable way and there's agreement on it.
> 
> Does it fix the test and hide a real regression?

No, the test was always flaky and I see nothing in scylla that could have caused this regression.
I also couldn't validate the regression locally.
I don't have a good explanation as to what caused the test to fail more frequently other than a change in the environment, either test servers or maybe test libraries.
It fail frequently for me locally even with older versions of scylla.

**Comment by avikivity** [comment]
Now it fails with ~50% probability. What's the failure rate now? What's the failure rate in master as of 1 month ago?

**Comment by bhalevy** [comment]
@fruch I think the following was probably inadvertent.
You fixed a warning since there is no dtest_gating marker but this exposed this issue in its full capacity.

```diff
index a7c38440..504fb431 100644
--- a/nodetool_additional_test.py
+++ b/nodetool_additional_test.py
@@ -2714,7 +2714,7 @@ def set_node_probability(node, value: float):
 
 
 @pytest.mark.dtest_full
-@pytest.mark.dtest_gating
+@pytest.mark.next_gating
 class TestGetTraceProbability(Tester):
```

**Comment by avikivity** [comment]
Aha, so before it wasn't gating due to a typo, and now it kills our builds.

So I think it's fair either to take it out of gating, or to fix it in dtest.

**Comment by avikivity** [comment]
> It was over 50% starting Aug 30 See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/396/testReport/junit/nodetool_additional_test/TestGetTraceProbability/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_value_affect_tracing_table/history/?start=25

What happened on Aug 30 to take it to 50%?

**Comment by bhalevy** [comment]
> > It was over 50% starting Aug 30 See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/396/testReport/junit/nodetool_additional_test/TestGetTraceProbability/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_value_affect_tracing_table/history/?start=25
> 
> What happened on Aug 30 to take it to 50%?

I don't know. I tried reproducing locally the relatively good results with versions that seemed more stable on jenkins but I can't, it still sucks on my machine so I guess it might environmental.

I didn't try with older versions of dtest / python driver though I'm not sure how that would change the outcome.

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6693/

**Comment by fruch** [comment]
> @fruch I think the following was probably inadvertent. You fixed a warning since there is no dtest_gating marker but this exposed this issue in its full capacity.
> 
> ```diff
> index a7c38440..504fb431 100644
> --- a/nodetool_additional_test.py
> +++ b/nodetool_additional_test.py
> @@ -2714,7 +2714,7 @@ def set_node_probability(node, value: float):
>  
>  
>  @pytest.mark.dtest_full
> -@pytest.mark.dtest_gating
> +@pytest.mark.next_gating
>  class TestGetTraceProbability(Tester):
> ```

it's a warning @avikivity  reported, meaning it's important, not ? :)

I assumed that we decided already about that test to be on gating (at some point), 
I wasn't aware of this instability issue.

**Comment by avikivity** [comment]
Seen again (yes it's not promoted yet): https://jenkins.scylladb.com/view/nexts/job/scylla-enterprise/job/next/2612/

**Comment by avikivity** [comment]
@fruch please backport the fix to 5.4.

**Comment by Annamikhlin** [comment]
enterprise gating failed yesterday with error:
https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2628/testReport/junit/nodetool_additional_test/TestGetTraceProbability/Tests___Sanity_Tests___test_value_affect_tracing_table/
```
E       AssertionError: Error: probability=0.001 actual=0.0019 diff=0.0009 allowed=0.0008
E       assert 0.0009 <= 0.0008
```

**Comment by bhalevy** [comment]
@Annamikhlin I think we can safely increase the allowed threshold to make the test less flaky.
We saw this also in master, and given the fact that we're testing a random distribution, and with small numbers in this test case, we can give it some more slack.

**Comment by bhalevy** [comment]
Can you please submit a fix?
