### ISSUE TITLE
compaction_backlog_tracker move ctor does not transfer the tracker registration properly

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15248]
Currently the compaction_backlog_tracker move ctor moves the other backlog manager into `this`:
https://github.com/scylladb/scylladb/blob/cf37ab96f4cf5e429faaa2fc256bb295b1924b3a/compaction/compaction_manager.cc#L2125

But if `other` was registered to this manager, we botch registration, as:
1. `this` is not registered to the moved manager
2. `other` will not deregister itself from the moved manager in its destructor since it's left with a null manager here

**Comment by denesb** [comment]
Looks like this is a change oriented to protect developers from making mistakes, so I won't backport.
@bhalevy please re-add the label if you disagree.

**Comment by bhalevy** [comment]
yes, the bug was benign since the only place we moved the backlog tracker, in `compaction_manager::register_backlog_tracker`, it isn't registered.
