### ISSUE TITLE
[arm, deubg]: topology_experimental_raft.test_raft_cluster_features

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#15254]
Full build log 
https://jenkins.scylladb.com/job/scylla-master/job/build/1605/testReport/junit/(root)/non-boost%20tests/Build__Test__Publish___buildTestPublishArm___topology_experimental_raft_test_topology_ops_debug_1/

**Comment by kbr-scylla** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/build/1605/artifact/testlog/aarch64/debug/scylla-369.log
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==87827==ERROR: AddressSanitizer: SEGV on unknown address 0xfffffffffffffff8 (pc 0xffffa11fd174 bp 0xfffff7513350 sp 0xfffff7513350 T0)
==87827==The signal is caused by a READ memory access.
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

looks like https://github.com/scylladb/scylladb/issues/15090#issuecomment-1692656790
