### ISSUE TITLE
[x86, dev]: non-boost tests.topology_experimental_raft.test_raft_cluster_features.dev

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#15252]
Full build log:

https://jenkins.scylladb.com/job/scylla-master/job/build/1605/testReport/junit/(root)/non-boost%20tests/Build__Test__Publish___buildTestPublishX86___topology_experimental_raft_test_raft_cluster_features_dev_1/

**Comment by kbr-scylla** [comment]
Weird

https://jenkins.scylladb.com/job/scylla-master/job/build/1605/artifact/testlog/x86_64/dev/scylla-358.log
```
ERROR 2023-09-03 04:36:51,539 [shard 0:main] init - Startup failed: std::system_error (error system:98, posix_listen failed for address 127.65.12.7:9180: Address already in use)
```

**Comment by kbr-scylla** [comment]
Closing as duplicate of https://github.com/scylladb/scylladb/issues/15755
