### ISSUE TITLE
Auth: password authenticator's create role is not durable

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#15251]
Some background:
From the start, we inherited a somewhat questionable behavior for authentication. There is a default hard coded user and password "cassandra" which is treated differently and will be read and **written** to the credentials table with `QUORUM` consistenct level . All of the other users even if have the exact same properties will do the same but with `LOCAL_ONE` consistency level.

The implications on login (under the recommended RF for the `system_auth` keyspace) are that unless a quorum of nodes are already up in the entire cluster, the user can't login with the "cassandra" user name.

However for other users, for login, it is required only that the node you are trying to log into is up since the credentials are obtained using `LOCAL_ONE`.

For creating a user, the quarantines are a lot weaker, once a role creation is acknowledged it is only guarantied to exist on on node in the same datacenter as the coordinator node (this will also be the coordinator node under recommended RF settings).
This means that if for example a role is created (and acknowledged) and the coordinator crashes soon after, the role might not exist on **all** of the other nodes. 
See for example: https://github.com/scylladb/siren/issues/9648#top

**Comment by eliransin** [comment]
I suggest the following:
1. Create roles with either `QUORUM_EACH` or `QUORUM` - this will ensure durability of the role
2. Make login as, two or three phase, try with `LOCAL_ONE` if it doesn't work, try with `LOCAL_QUORUM` and if this doesn't work, try with `QUORUM`. It is somewhat risky in the sense that it makes the case of faulty log in put more load on the system, but maybe we can find some mechanism to mitigate this (rate limiting or something similar). For users that exists, it is worth noting that this only affects some of the first logins after which the role is already cached and those fallbacks will not trigger again.

**Comment by eliransin** [comment]
/cc @mykaul 
Involving you since there is a (possibly) user visible tradeoff that we should consider.
Moreover, moving auth table to raft is going to solve this, forcing the information to propagate to a quorum nodes before acknowledging the role creation.

**Comment by mykaul** [comment]
The LOCAL_ONE write make little sense to me indeed. I'm good with the changes for role creation to QUORUM (perhaps EACH_QUORUM for multi-DC?)
As for the reads, I'd use LOCAL_QUORUM as well - unsure if there's a benefit of LOCAL_ONE and then fallback.
@tzach - thoughts?

**Comment by tzach** [comment]
related issue in Apache Cassandra. https://issues.apache.org/jira/browse/CASSANDRA-12988
The entire thread is intresting 

Among other is identify different CL for the following:

> ConsistencyLevel.LOCAL_ONE for both read and write operations in CassandraAuthorizer
> ConsistencyLevel.ONE for batches in there
> ConsistencyLevel.QUORUM for checks in CassandraRoleManager + PasswordAuthenticator if the username is "cassandra"
> ConsistencyLevel.LOCAL_ONE for checks in CassandraRoleManager + PasswordAuthenticator if the username is otherwise

Is it the same case for ScyllaDB?
Doesn't it make sense to move all of the above under Raft consistency, similar to Schmea?

> Make login as, two or three phase, try with LOCAL_ONE if it doesn't work, try with LOCAL_QUORUM and if this doesn't work, try with QUORUM

I don't like this (not sure why) It seems over-engineered and error-prone.

**Comment by eliransin** [comment]
> Is it the same case for ScyllaDB?
> Doesn't it make sense to move all of the above under Raft consistency, similar to Schmea?

I makes a lot of sense and is planned. It is going to take a while since the inter dependency between authorization and authentication needs to be figured out before we do (/cc @kostja )



> I don't like this (not sure why) It seems over-engineered and error-prone.

If we are whiling to live with the situation described here for a year or so, this is not necessary as it will be solved by the move to raft.

**Comment by nuivall** [comment]
Resolved by https://github.com/scylladb/scylladb/pull/16578
