### ISSUE TITLE
Commitlog replay can cause abort due to over-extended skip

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylladb#15269]
If a segment being replayed is truncated/corrupted we can attempt to skip more than available in the file, which causes assertion in `file_data_source_impl`. This being an assert is dubious, but that does not change the fact that we can just as well do this check properly in the replay reader.

**Comment by mykaul** [comment]
@scylladb/scylla-maint  - please backport to 5.2 and 5.4.

**Comment by denesb** [comment]
Backported to 5.4 and 5.2.
