### ISSUE TITLE
Annoying HTTPS warning when running Alternator tests against AWS

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#15287]
If I run Alternator tests against AWS DynamoDB, e.g. via the command:
```
./run --aws test_update_expression.py::test_update_expression_set_copy
```

The test ends successfully but with a warning:
```
=============================== warnings summary ===============================
test_update_expression.py::test_update_expression_set_copy
  /usr/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dynamodb.us-east-1.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

This warning is annoying - it's always something you need to see and ignore at the end of a successful test run. We can do certificate verification for AWS (but can't for local Alternator), Or alternatively find a way to avoid these warnings. 

We get the same warning when running Alternator with HTTPS (replace "--aws" above by "--https"):
```
test_update_expression.py: 17 warnings
  /usr/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.17.150.236'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

Here of course the only way to go is to ignore these warnings - we can't do certficiate verification, it's a locally-signed certificate.

I think the reason why AWS has just one warning and local has 17 warnings is that we make just one call with verify=false in both cases (in the `run` script, check_alternator()), but then in `conftest.py` we make a lot of requests with verify=false only in the local case (in the AWS case, we keep verify=true).

In conftest.py and run  I tried to use some trickery to avoid these warnings. Evidently it doesn't work at all... Maybe it worked in the past and stopped working?

```python
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

**Comment by denesb** [comment]
Test only change, not backporting.
