### ISSUE TITLE
Whole tablet metadata is reloaded on every mutation of topology

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#15294]
During tablet migration we move any given tablet through several stages. Each such transition affects only a handful of tablets, but currently every group0 member will reload whole tablet metadata when it applies the change. This is inefficient and with many tablets can add latency to tablet migration. 

We can figure out from group0 command which tablets changed and reload only them. 

Tablet metadata is mutated on a replica via two paths:

1) By topology_change command handled in group0_state_machine.cc:

```c++
    [&] (topology_change& chng) -> future<> {
        co_await write_mutations_to_database(_sp, cmd.creator_addr, std::move(chng.mutations));
        co_await _ss.topology_transition(_cdc_gen_svc);
    },
```

Reload is done in `storage_service::topology_state_load()`:
```
            tmptr->set_tablets(co_await replica::read_tablet_metadata(*_qp));
```

We could copy the old tablet map and override tablets which changed based on the selector passed to the method.

2) By schema change in schema_tablets.cc:

```c++
    if (has_tablet_mutations) {
        slogger.info("Tablet metadata changed");
        // We must do it after tables are dropped so that table snapshot doesn't experience missing tablet map,
        // and so that compaction groups are not destroyed altogether.
        // We must also do it before tables are created so that new tables see the tablet map.
        co_await db.invoke_on_all([&] (replica::database& db) -> future<> {
            co_await db.get_notifier().update_tablet_metadata();
        });
    }
```

We could have a tablet set detection code similar to the one we have for schema changes (see `get_affected_tables()`) which would return tablet_selector object extracted from mutations of system.tablets. We then pass that selector to update_tablet_metadata() and topology_transition().

Solving this is also a prerequisite for event-based notification of tablet metadata changes.

**Comment by mykaul** [comment]
Is this still on track for 6.0?

**Comment by avikivity** [comment]
@denesb had a patch for it

**Comment by denesb** [comment]
> Is this still on track for 6.0?

No. I have a PR but it needs rebase + fixes, and with the current amount of work on items we do need in 6.0, I won't have the time to get it into 6.0.

**Comment by bhalevy** [comment]
@denesb how is it looking for 6.1?

**Comment by denesb** [comment]
> @denesb how is it looking for 6.1?

There is a good chance that it will make it.
