### ISSUE TITLE
`cdc::topology_description`: avoid large allocation

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15302]
```
/* Describes a mapping of tokens to CDC streams in a whole token ring.
 *
 * Division of the ring to token ranges is defined in terms of `token_range_end`s
 * in the `_entries` vector. See the comment above `token_range_description` for explanation.
 */
class topology_description {
    std::vector<token_range_description> _entries;
public:
    topology_description(std::vector<token_range_description> entries);
    bool operator==(const topology_description&) const;

    const std::vector<token_range_description>& entries() const&;
    std::vector<token_range_description>&& entries() &&;
};
```

As observed in https://github.com/scylladb/scylla-enterprise/issues/3387#issuecomment-1706965061, the `vector` may cause a large allocation -- there could be many `token_range_descriptions` (it's `number_of_nodes * vnodes_per_node`).

We need to change this to `chunked_vector`, for example.

**Comment by denesb** [comment]
Doesn't apply cleanly. Since this was done by an external contributor, @kbr-scylla can you please take care of backporting this?

**Comment by kbr-scylla** [comment]
Queued backports to enterprise branches:
2022.2: 7f605a2012df6fab4565de8f4dbbb5d1f619fb68
2022.1: b62863ad7bada8a1e6734e127e876e79bab16d89
2021.1: e40d4abdf7a30453c126cb73debdb2cbd03dbaf6
