### ISSUE TITLE
alternator_tests.TesterAlternator.test_tls_connection: botocore.exceptions.SSLError: SSL validation failed for https://127.0.88.1:8043/ hostname '127.0.88.1' doesn't match 'ip-10-0-4-248.ec2.internal'

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15310]
Seen in next promotion:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/gating-dtest-release/4310/testReport/junit/alternator_tests/TesterAlternator/FullDtest___full_split000___test_tls_connection/
```
botocore.exceptions.SSLError: SSL validation failed for https://127.0.88.1:8043/ hostname '127.0.88.1' doesn't match 'ip-10-0-4-248.ec2.internal'
```

I wonder if that could be related to running this test on EC2
Though I'd be surprised if we only started doing this recently.

@nyh can you please look into this?

**Comment by bhalevy** [comment]
same in the successive run: https://jenkins.scylladb.com/view/master/job/scylla-master/job/gating-dtest-release/4311/testReport/alternator_tests/TesterAlternator/FullDtest___full_split000___test_tls_connection/

**Comment by bhalevy** [comment]
Refs https://github.com/scylladb/scylladb/pull/15292

**Comment by fruch** [comment]
It's broken because of a change in dtest,
I've merged https://github.com/scylladb/scylla-dtest/pull/2939

it broke the code that adds the nodes ip addresses to the certificates
and it broke it, I've fixed the commit and queued it again

**Comment by nyh** [comment]
So @fruch is there a PR that closes this issue? Or it should be closed because you already fixed it?

**Comment by bhalevy** [comment]
> It's broken because of a change in dtest, I've merged [scylladb/scylla-dtest#2939](https://github.com/scylladb/scylla-dtest/pull/2939)
> 
> it broke the code that adds the nodes ip addresses to the certificates and it broke it, I've fixed the commit and queued it again

Thank.  Next time I think we better follow the process of dequeuing / reverting the offending patch and letting the author fix and resubmit it after it has passed ci again.

Also, how come CI testing didn't catch this failure?

**Comment by fruch** [comment]
right now dtest CI runs only the affected tests. it's not 100%.
the CI failed to notice the usage of that function, seems like it doesn't handle multiple inheritance that good.

when it was introduce we assume we want to try try test only the specific tests changed (if it's the files that was touch, or something similar), cause running all would generate too much noise.

we might consider adding an option to run all gating test

**Comment by bhalevy** [comment]
> right now dtest CI runs only the affected tests. it's not 100%. the CI failed to notice the usage of that function, seems like it doesn't handle multiple inheritance that good.
> 
> when it was introduce we assume we want to try try test only the specific tests changed (if it's the files that was touch, or something similar), cause running all would generate too much noise.
> 
> we might consider adding an option to run all gating test

I think it would be a good idea to run all gating tests like we do in scylla PRs plus particular tests that changed or are affected and are not in next_gating.

**Comment by mykaul** [comment]
@fruch - can we close this?

**Comment by fruch** [comment]
> @fruch - can we close this?

yes
