### ISSUE TITLE
raft topology: add garbage collection for internal CDC generations table

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15323]
As discussed in https://github.com/scylladb/scylladb/pull/13962#issuecomment-1609112962, we need a mechanism to clear obsolete CDC generation data because we send the entire contents of `CDC_GENERATIONS_V3` as a part of the group 0 snapshot. We need to prevent these snapshots from endlessly growing as we introduce new generations over time.

The first step of implementing such a mechanism is making the `CDC_GENERATIONS_V3` single-partition and ordered by `timeuuid`s. This change enables the efficient clearing of old generations by inserting a range tombstone. #15163 has already introduced this change.

The second (and the last) step is actually clearing old generations. The proposed solution is to make the topology coordinator systematically insert a range tombstone covering all generations that are:
- published,
- not current (its `timeuuid` does not equal `current_cdc_generation_uuid`),
- older than `now() - 24 h`, where `now()` is the current time point of the coordinator's clock.

The explanation for the two first requirements is that we cannot delete unpublished and current generations. The last requirement addresses the clock discrepancies with a large reserve. We must ensure all nodes' clocks are in the future compared to a generation we want to remove.

Tombstones can be inserted by the topology coordinator, but it seems like its CDC publisher fiber introduced in #15281 is a better candidate for this task. It can be adjusted to do it.

**Comment by patjed41** [comment]
cc @kbr-scylla

**Comment by avikivity** [comment]
raft topology is still experimental, not backporting.
