### ISSUE TITLE
docs: Issue in page Eventual Consistency

### ISSUE THREAD

**Issue by ziyaddin** [scylladb/scylladb#15344]
I would like to report an issue in page https://www.scylladb.com/glossary/eventual-consistency

### Problem

There is a typo in the first figure – "Write X" should be written in the leftmost client arrow and "Read X" in the second one.

**Comment by tzach** [comment]
Thanks
First, you are right
Second, I find this entire figure confusing. Its hard to understand what is the time line.

AFAIU, the idea was something like:

```mermaid
sequenceDiagram
    box App
    participant Client1
    participant Client2
    participant Client3
    end
    box DC-1
    participant NodeA
    participant NodeB
    end
    box DC-1
    participant NodeC
    end
    Note over NodeA,NodeB: Old-x
    Note over NodeC: Old-x
    Client1->>+NodeA: Write-X
    Note over NodeA: X
    NodeA->>+NodeB: Write-X
    Note over NodeB: X
    NodeC->>+Client3: Read-Old-X
    NodeA->>+NodeC: Write-X
    Note over NodeC: X
    NodeB->>+Client2: Read-X
```

**Comment by tzach** [comment]
@scynthiadunlop can we remove the misleading digram?
