### ISSUE TITLE
main.cc: handle truncation records for tables migrating to schema commitlog

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#15354]
[The is a check in main.cc](https://github.com/scylladb/scylladb/blob/87088b65b663d2fe02d5bda8fab434a5a6f7f315/main.cc#L1389)

It generates an error if it finds a truncation record for a schema table. The reason for this error is that in would be incorrect to use truncation records, created based on old commitlog, while replaying new commitlog. We need to decide how to handle the same problem for other tables we switched to schema commitlog.

**Comment by kbr-scylla** [comment]
Citing @tgrabiec 

> We should extend the check to be safe. If we would want to support truncation in the future, we can add a commitlog domain selector to truncation records.

**Comment by avikivity** [comment]
@gusev-p please evaluate for backport
