### ISSUE TITLE
test.py: check exit code of a process during clean shutdown 

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#15365]
We need to track crashes during clean shutdown. Currently we don't check the process exit status during shutdown, we should do it instead and fail the test.

**Comment by mykaul** [comment]
cc @roydahan - we discussed this multiple times.

**Comment by roydahan** [comment]
I suggest to also check for coredumps that may have happened during the test.

**Comment by kostja** [comment]
Those would lead to a failing test already @roydahan

**Comment by andriipatsula** [comment]
In `async def run_test(...) -> bool`:

https://github.com/scylladb/scylladb/blob/56f7b2f45d1a384f12e24c84b8164ac7883a9b9e/test.py#L1135-L1139

`process.returncode` is examined, and if it isn't in `valid_exit_codes`,  the `Test.success` is set to `False` (marked as failed).

Nevertheless, there is one location where the return code isn't examined. In `class BoostTestSuite(UnitTestSuite)`:
https://github.com/scylladb/scylladb/blob/56f7b2f45d1a384f12e24c84b8164ac7883a9b9e/test.py#L322

> check exit code of a process during clean shutdown

@kostja , does this issue refers to the second location (BoostTestSuite)?

**Comment by kostja** [comment]
What you're referring to is test failure, not scylla failure. scylla_failure is test/lib/scylla_cluster.py

**Comment by nyh** [comment]
> I suggest to also check for coredumps that may have happened during the test.

In Linux, a process's exist status is composed of two pieces. The familiar 8-bit "exit code" is only half of the story. The other half of the story is additional bits which can tell you if the process was terminated by a signal, and even if a core dump was created while handling this signal (the core-dump thing is a Linux only extension). All of this is documented in the `wait(2)` manual page.

So to make a long story short, you can definitely tell if Scylla existed successfully, or whether exited unsuccessfully, killed by a signal (e.g., SIGSEGV, SIGABRT, etc.) or even if it dumped core (although I don't think that last piece of information is particularly useful).

**Comment by kostja** [comment]
review ping @kbr-scylla

**Comment by kbr-scylla** [comment]
> review ping @kbr-scylla

There is unaddressed review from @avikivity on the PR.

**Comment by denesb** [comment]
Test only change, not backporting.
