### ISSUE TITLE
Gossiper does not properly acquire lock_endpoint_update_semaphore in reset_endpoint_state_map

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#15361]
HEAD: 89ba4e4a5e5932fd172885759e6d74bb361ee9c8

The commit https://github.com/scylladb/scylladb/commit/0cc0a955436c115c33376577a06729dc7e081f85, introduced in PR https://github.com/scylladb/scylladb/pull/14801, modified the `gossiper::reset_endpoint_state_map` function to acquire a lock via `gossiper::lock_endpoint_update_semaphore`. However, the future returned by the latter function is just assigned to a variable and not awaited at all, leading to the lock not being effective at all.

```c++
future<> gossiper::reset_endpoint_state_map() {
    logger.debug("Resetting endpoint state map");
    auto lock = lock_endpoint_update_semaphore(); // <- co_await missing here
    auto version = _live_endpoints_version + 1;
    co_await container().invoke_on_all([version] (gossiper& g) {
        g._unreachable_endpoints.clear();
        g._live_endpoints.clear();
        g._live_endpoints_version = version;
        g._endpoint_state_map.clear();
    });
}
```

Found accidentally by looking at the code.

**Comment by avikivity** [comment]
What's the impact of the bug?

It's really hard to tell what the commit fixes when the commit and issue are mirror images of each other.

**Comment by kbr-scylla** [comment]
In any case, the original commit that introduced the bug did not end up in any release branch, so removing Backport candidate label.

**Comment by piodul** [comment]
> What's the impact of the bug?

I'm not sure. I just fixed an obvious mistake that I spotted in the code, not in response to any actual failure/crash/incorrect behavior etc., and I'm not confident enough in the gossiper area to tell exactly what bad things could happen.
