### ISSUE TITLE
[x86, release]: topology_custom.test_read_repair

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#15371]
It seems that this test is unstable (or flaky) - failed during https://jenkins.scylladb.com/job/scylla-master/job/next/6512/

Error log: https://jenkins.scylladb.com/job/scylla-master/job/next/6512/testReport/(root)/non-boost%20tests/Tests___Unit_Tests___topology_custom_test_read_repair_release_2/ 

Failed 1 of 10 - https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/1830/
Failed 6 - 100 - https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/1831/

**Comment by yaronkaikov** [comment]
@mykaul  @avikivity We should probably try to get a quick fix for this or remove it temporarily from gating (until it is stable again)

**Comment by mykaul** [comment]
The failures are a bit odd:
```
test_read_repair.py::test_incremental_read_repair[row-tombstone]
  /jenkins/workspace/scylla-master/next/scylla/test/topology_custom/test_read_repair.py:310: RuntimeWarning: coroutine 'ScyllaRESTAPIClient.keyspace_flush' was never awaited
    manager.api.keyspace_flush(node.ip_addr, "ks")
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

test_read_repair.py::test_incremental_read_repair[row-tombstone]
  /jenkins/workspace/scylla-master/next/scylla/test/topology_custom/test_read_repair.py:311: RuntimeWarning: coroutine 'ScyllaRESTAPIClient.keyspace_compaction' was never awaited
    manager.api.keyspace_compaction(node.ip_addr, "ks")
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /scylladir/testlog/x86_64/release/xml/topology_custom.test_read_repair.2.xunit.xml -

```

Some await missing?
@bhalevy - does the test belong to your team?
Regardless, let's remove it from gating until we resolve it.

**Comment by denesb** [comment]
No vulnerable releases, removing backport candidate label.
