### ISSUE TITLE
scylla-sstable should print the selected schema source

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15384]
As a followup to #15359, that issue was caused by a stray `schema.cql` file unintentionally left in the current working directory of the where the dtest ran.

I had to change the code of scylla-sstable to figure out what went on, while it would be clearer if the tool just printed out the schema loader auto-detection result.

We should also decide if we want to print the schema file used when explicitly passed as a command line option.

Third consideration is making sure the printout doesn't interfere with the standard output when e.g. a dump of the sstable contents is expected on the standard output - so any informational printout should be printed to the standard error.

**Comment by denesb** [comment]
Logs are printed to stderr and dump output to stdout, so there should be no interference. It will look ugly in the terminal, but I always pipe the output to `jq` anyway.

**Comment by bhalevy** [comment]
Maybe we need to add a `-v | --verbose` flag to make the tool more chatty?
Then we can turn it on in testing
and user may choose to use it when the tool is malfunctioning

**Comment by bhalevy** [comment]
> Maybe we need to add a `-v | --verbose` flag to make the tool more chatty? Then we can turn it on in testing and user may choose to use it when the tool is malfunctioning

Answering myself, but one could change `--default-log-level=debug` to achieve a similar result.

**Comment by denesb** [comment]
> > Maybe we need to add a `-v | --verbose` flag to make the tool more chatty? Then we can turn it on in testing and user may choose to use it when the tool is malfunctioning
> 
> Answering myself, but one could change `--default-log-level=debug` to achieve a similar result.

Or just `--logger-log-level scylla-sstable=trace`. In fact I often pass this in tests, it is invaluable when investigating problems.

**Comment by bhalevy** [comment]
I don't expect users out of the organization to be that intimately familiar with the logger names...
In any case we don't print anything useful on the success path, not even in trace level.
That's why I had to instrument the code to figure out what happened.

**Comment by denesb** [comment]
Maybe a debug-level message is the best middle-ground. There is no unwanted message by default and turning up the log-level will reveal what happens.

**Comment by denesb** [comment]
> I don't expect users out of the organization to be that intimately familiar with the logger names... In any case we don't print anything useful on the success path, not even in trace level. That's why I had to instrument the code to figure out what happened.

Maybe we can add a `-v` which enables trace-level logging for `scylla-sstable` and `-vv` would enable it for all loggers. This would not presume any knowledge of logger names or how they can be turned on.

**Comment by denesb** [comment]
Minor tool UX improvement, not backporting.
