### ISSUE TITLE
[dtest] test failed due to a node getting stuck in bootstrap

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15393]
Build https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3602/ failed on `resharding_test.TestReshardingVariants.test_resharding_by_smp_increase[4-SizeTieredCompactionStrategy-15]`.

Attached logs:
[dtest-gw4.log](https://github.com/scylladb/scylladb/files/12597046/dtest-gw4.log)
[1694518082201_resharding_test.py TestReshardingVariants test_resharding_by_smp_increase[4-SizeTieredCompactionStrategy-15].zip](https://github.com/scylladb/scylladb/files/12597049/1694518082201_resharding_test.py.TestReshardingVariants.test_resharding_by_smp_increase.4-SizeTieredCompactionStrategy-15.zip)

This test runs on a 4-node cluster. Before the test even started, the bootstrap procedure of the 3rd node got stuck during "waiting for schema information to complete":
```
INFO  2023-09-12 11:13:52,529 [shard 0:stre] storage_service - waiting for schema information to complete
INFO  2023-09-12 11:13:52,530 [shard 0:stre] schema_tables - Schema version changed to 4fd068ed-d970-3076-a296-1f6f23a86d17
...
INFO  2023-09-12 11:27:59,193 [shard 0:main] compaction_manager - Asked to stop
```

**Comment by kbr-scylla** [comment]
Taking off `infra?` label, the issue reproduces.

I posted some observations on https://github.com/scylladb/scylladb/issues/15911

**Comment by kbr-scylla** [comment]
KQL query for ElasticSearch to find similar failures:
```
outcome: failure and failure_message : "Missing.*Starting listening for CQL clients" and failure_message : "raise TimeoutError" and not outcome : error
```

looks like it's happening with Raft enabled and disabled.

I don't understand why `waiting for schema information to complete` hangs --- according to the lost, schema version is the same on all nodes.

I see two possible explanations
- whatever reported by the logs is not true, maybe there's a codepath that changes the schema version but doesn't cause a message to be printed
- or there's some problem with gossiping schema versions; `migration_manager::have_schema_agreement` (which we're checking in a loop until it returns `true`) needs to obtain `gms::application_state::SCHEMA` from other nodes, and if it's not there for some node, it will return `false`.

Also, this looks kinda similar to https://github.com/scylladb/scylladb/issues/16004, but there it was not the global schema digest being different, it was the per-table versions (which we don't wait for to be synchronized on bootstrap).

**Comment by kbr-scylla** [comment]
Perhaps different calls of `migration_manager::passive_announce` are racing with each other, and node may end up gossiping an old version. I don't see what prevents this from happening during feature enabling phase on boot, where we're concurrently calling `recalculate_schema_version` in the background. It seems that one of these tasks, that used a schema version calculated without all features, could update gossiper *after* a task that calculated a schema version with all features.

cc @tgrabiec

**Comment by kbr-scylla** [comment]
On the other hand, maybe not?
```cpp
    auto schema_change_announce = _db.local().observable_schema_version().observe([this] (table_schema_version schema_version) mutable {
        _migration_manager.local().passive_announce(std::move(schema_version));
    });
```

```cpp
void migration_manager::passive_announce(table_schema_version version) {
    _schema_version_to_publish = version;
    (void)_schema_push.trigger().handle_exception([version = std::move(version)] (std::exception_ptr ex) {
        mlogger.warn("Passive announcing of version {} failed: {}. Ignored.", version, ex);
    });
}
```

let's assume that this `observe` mechanism serializes the callback, so that the newest version will be always be handled last. In that case, the last `passive_announce` should set `_schema_version_to_publish` to the latest version and that version will be published in the end.

But not sure.

**Comment by kbr-scylla** [comment]
Maybe the race could happen inside here:
```cpp
static
future<> update_schema_version_and_announce(sharded<db::system_keyspace>& sys_ks, distributed<service::storage_proxy>& proxy, schema_features features) {
    auto uuid = co_await calculate_schema_digest(proxy, features);
    co_await sys_ks.local().update_schema_version(uuid);
    co_await proxy.local().get_db().invoke_on_all([uuid] (replica::database& db) {
        db.update_version(uuid);
    });
    slogger.info("Schema version changed to {}", uuid);
}
```

if a task with obsolete schema version hanged before the `db.update_version` step, we would end up with this version eventually.

**Comment by kbr-scylla** [comment]
It could be that the node is actually leaving the `have_schema_agreement` loop and getting stuck in `update_topology_change_info` trying to acquire merge lock --- obviously, to confuse the enemy, there is no log message in between. But what would be holding the merge lock? cc @bhalevy 

I feel stuck in the investigation, so I'll send a PR to improve the logging. Next time the issue reproduces in one of our CI runs, we'll have more details.

**Comment by kbr-scylla** [comment]
> I feel stuck in the investigation, so I'll send a PR to improve the logging. Next time the issue reproduces in one of our CI runs, we'll have more details.

https://github.com/scylladb/scylladb/pull/16021

**Comment by kbr-scylla** [comment]
Issue reproduced with more logs
[node1.log](https://github.com/scylladb/scylladb/files/13472762/node1.log)
[node2.log](https://github.com/scylladb/scylladb/files/13472763/node2.log)
[node3.log](https://github.com/scylladb/scylladb/files/13472764/node3.log)
[node4.log](https://github.com/scylladb/scylladb/files/13472765/node4.log)

**Comment by kbr-scylla** [comment]
node4 got stuck during boot printing in a loop:
```
INFO  2023-11-26 20:02:33,901 [shard 0:strm] migration_manager - (rate limiting dropped 497 similar messages) Schema mismatch for 127.0.3.2 (5269ca7d-7b22-3edc-8795-73f8591117d9 != 30a31e52-f9e0-33e9-8241-6f648af22fbe).
```

The last "Schema version changed to" message on node 4 is:
```
INFO  2023-11-26 20:02:28,915 [shard 0:strm] schema_tables - Schema version changed to 5269ca7d-7b22-3edc-8795-73f8591117d9
```
consistent with the above message.

The last "Schema version changed to" message on node 2 (`127.0.3.2`) is:
```
INFO  2023-11-26 20:02:01,931 [shard 0:strm] schema_tables - Schema version changed to 5269ca7d-7b22-3edc-8795-73f8591117d9
```
not consistent.

so why is node 4 claiming that node 2's schema version is `30a31e52-f9e0-33e9-8241-6f648af22fbe`?

This version is indeed one of the previous versions:
```
INFO  2023-11-26 20:02:01,877 [shard 0:strm] schema_tables - Schema version changed to 30a31e52-f9e0-33e9-8241-6f648af22fbe
```

**Comment by raphaelsc** [comment]
Another occurrence: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/6440/

**Comment by kbr-scylla** [comment]
I put this under https://github.com/scylladb/scylladb/issues/17493, now we have to wait and see if we observe it again after https://github.com/scylladb/scylladb/commit/111264e3b1d9331c03c489c621ef16fd5a49e1af

**Comment by kbr-scylla** [comment]
Removing it from raft-topology backlog - required, there's nothing we can currently do about it other than waiting.
