### ISSUE TITLE
test_read_repair takes infinite time in debug mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15425]
I observed it taking 40 minutes or so in `scylla sstable write`.

In addition, ctrl-C doesn't kill that process.

Will update with direct measurement later.

**Comment by avikivity** [comment]
Doesn't terminate. Source: #15414

**Comment by avikivity** [comment]
Turns out it's not infinite, only nearly so. #16470 has more details.

**Comment by nyh** [comment]
> In addition, ctrl-C doesn't kill that process.

We know of this problem for many years: https://github.com/scylladb/seastar/issues/261 and https://github.com/scylladb/scylladb/issues/5696

**Comment by avikivity** [comment]
```
17:59:32  [9124/9124] topology_custom  debug  [ PASS ] topology_custom.test_read_repair.1 4244.61s
```

**Comment by nyh** [comment]
See also https://github.com/scylladb/scylladb/issues/16899 - about this test not just being annoyingly slow, but also specifically about its failures on aarch64+debug. Probably one of the two issues should be closed.

**Comment by denesb** [comment]
Fix here: https://github.com/scylladb/scylladb/pull/17529

**Comment by denesb** [comment]
Backported to 5.4, 5.2 is not vulnerable.
