### ISSUE TITLE
test_scrub_with_one_node_expect_data_loss: Scrubbing in segregate mode of 1 sstables interrupted due to: std::runtime_error (Failed to generate sharding metadata

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15457]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/254/artifact/logs-full.debug.004/1694939900770_nodetool_additional_test.py%3A%3ATestNodetool%3A%3Atest_scrub_with_one_node_expect_data_loss/node1.log
```
INFO  2023-09-17 06:38:54,087 [shard 1:comp] compaction - [Scrub ks.cf ded68b50-5524-11ee-980f-f729f13d7e99] Scrubbing in segregate mode [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-uh_wha77/test/node1/data/ks/cf-cd3525a0552411ee8a10435178dcff2a/me-3g9g_0iga_3pqtc2bsfgy8l06dre-big-Data.db:level=0:origin=memtable]
ERROR 2023-09-17 06:38:54,995 [shard 1:comp] compaction - [Scrub compaction ks.cf] out-of-order partition key <non-utf8-key> ({key: pk{...}]}}}
WARN  2023-09-17 06:38:55,056 [shard 1:comp] sstable - create_sharding_metadata: range=[{2428938512207371993, ...},{2428938512207371993, ...}] has no intersection with shard=1 first_key={key: pk{...}, token: 2428938512207371993} last_key={key: pk{...}, token: 2428938512207371993} ranges_single_shard={} ranges_all_shards={{0, {[{2428938512207371993, ...},{2428938512207371993, ...}]}}}
```

@denesb please look into this

**Comment by denesb** [comment]
Looks like the output sstable is empty. This is entirely possible given that the input file is randomly corrupted.

**Comment by bhalevy** [comment]
How we come we only started hitting this now?

**Comment by denesb** [comment]
I have seen this before, although that was only recently too. I recall this test used to fail in the past regularly, maybe we just didn't notice?

**Comment by bhalevy** [comment]
So should the dtest simply ignore this error?
If so, can you please submit a PR?

**Comment by denesb** [comment]
The test failed due to timeout - scrub was re-tried indefinitely. Adding the error to the ignore pattern will not help here.

**Comment by denesb** [comment]
> The sstable is not supposed to contain partitions belonging to other shards. Should those be segregated or skipped?

Yes, normally it shouldn't. I think what happens here is that the corruption changes the partition keys so that now they hash to another shard. Scrub is simply not prepared for this, it assumes all keys belong to the local shard. That said, scrub should maybe handle such random corruptions, on the other hand that is not what scrub was designed to to, it was designed to fix specific problems we have seen before.

**Comment by bhalevy** [comment]
> > The sstable is not supposed to contain partitions belonging to other shards. Should those be segregated or skipped?
> 
> Yes, normally it shouldn't. I think what happens here is that the corruption changes the partition keys so that now they hash to another shard. Scrub is simply not prepared for this, it assumes all keys belong to the local shard. That said, scrub should maybe handle such random corruptions, on the other hand that is not what scrub was designed to do, it was designed to fix specific problems we have seen before.

Right.  Maybe in this case it should quarantine the sstable (if it's not already) and abort the scrub, without retrying endlessly.

**Comment by denesb** [comment]
You mean qurantine the input sstable? Isn't scrub supposed to bring sstables out of quarantine.
If we abort the scrub, it means the user has no way to fix their sstable. With online scrub that is, offline scrub runs on a single shard and owns all partitions, thus it is not vulnerable to this problem.

**Comment by bhalevy** [comment]
> You mean qurantine the input sstable? Isn't scrub supposed to bring sstables out of quarantine.

It's supposed to (but it can run on unquarantined sstables as well).

> If we abort the scrub, it means the user has no way to fix their sstable. With online scrub that is, offline scrub runs on a single shard and owns all partitions, thus it is not vulnerable to this problem.

True, the options are:
- abort scrub - this will allow manual scrub and the admin could decide what to do with the output.
- try to skip over it as it is suspected as corrupt
- segregate it, and don't try to add the output sstable.
  - where should it be put?
  - note that it will be loaded to another shard on restart, but if we suspect it's corrupt, I don't think we should allow that automatically.

**Comment by denesb** [comment]
I think we can rely on the assumption that all sstables belong to the local shard. We guarantee this by automatic resharding on startup. That said, I think the safest approach is to somehow qurantine such sstables, allowing the admin to take action. Best to not make automatic decisions when corruption is involved.

**Comment by bhalevy** [comment]
We also reshard on upload (nodetool refresh).
This could happen with non-corrupted sstables only if someone copied them into the base directory or due to a bug in resharding.

**Comment by mykaul** [comment]
@bhalevy - what's the next step here?

**Comment by bhalevy** [comment]
> @bhalevy - what's the next step here?

scrub needs to check the partition owning shard when processing the input sstable and handle the case when it doesn't belong to the current shard.

The safest way to handle it would be to abort scrub and print an error about it.
Then, the user can use the offline tool to scrub the suspected sstable and decide what to do with the offending partitions.

**Comment by mykaul** [comment]
Failed again @ https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/466/

**Comment by mykaul** [comment]
Another hit @ https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/529/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_scrub_with_one_node_expect_data_loss/

**Comment by denesb** [comment]
We should disable this test. I don't think it is a useful test right now. It just produces random failures, because it is testing scrub's reaction to something, scrub was never designed to deal with. So of course scrub will fail in random ways.
