### ISSUE TITLE
docs: separate configuration parameters by groups

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/scylladb#15468]
## Motivation

I was tasked to reformat the [Configuration Parameters](https://opensource.docs.scylladb.com/master/reference/configuration-parameters.html#configuration-parameters) documentation to group parameters as per their categorization in the code. Refer to this code example: https://github.com/scylladb/scylladb/blob/master/db/config.cc#L337C1-L339C1

Our challenge with the current comments is distinguishing between a group comment, its description, and a regular comment. A potential solution is to adopt annotations that formalize this structure.

For instance, instead of:

 ```
/* Commonly used properties */ 
/* Properties most frequently used when configuring Scylla. */
/* Before starting a node for the first time, you should carefully evaluate your requirements. */
 ```
 
They could be formatted as:

```
/*
  @Group
  @GroupName: Commonly used properties
  @GroupDescription: Properties most frequently used when configuring Scylla. Before initiating a node for the first time, it's essential to carefully assess your specific needs.
*/
```

This format, or a similar annotation-based approach, would allow us to:

- Easily identify comments tagged with `@Group`.
- Extract details using the `@GroupName` and `@GroupDescription` tags.
- Recognize the end of a group section by detecting the start of the subsequent group block.

## Feedback needed

Would you agree on the proposed format? If not, could you suggest an alternative syntax for defining group blocks?

## Next steps

Upon consensus, I will prepare a pull request to update both the `db/config.cc` file and the reference documentation generation script.

**Comment by annastuchlik** [comment]
@dgarcia360 The input from @avi:

> No problem to add headers as long as they don't conflict with Doxygen syntax.
