### ISSUE TITLE
docs: Issue in page ScyllaDB Counters

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylladb#15479]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.2/using-scylla/counters

### Problem
This Doc does not mention that counters do not support TTL
It is mention in here:
https://opensource.docs.scylladb.com/stable/cql/types.html#counters

Please fix it for both OSS and ENT.

###  Suggest a fix

**Comment by gcarmin** [comment]
@annastuchlik   - the wording:
 "You cannot use TIMESTAMP or set a TTL (time to live) when updating a counter."
Is not clear enough - I would expect something like:
"Counters do not support expiration."  like on teh 2nd page OR "Counters do not support TTL".

thanks

**Comment by nyh** [comment]
"expiration" is just part of the statement about both TIMESTAMP and TTL.
The Datastax (https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useCounters.html) wording is pretty good:
```
Cassandra rejects USING TIMESTAMP or USING TTL in the command to update a counter column.
```

By the way, I was surprised that USING TIMESTAMP isn't allowed with counters. I wonder why is that...

**Comment by annastuchlik** [comment]
To me, "TTL" is more precise than just "expiration", but we can have both :)
I've already updated one page, so I'll push one more commit to update the other, similar to what DataStax has.

**Comment by annastuchlik** [comment]
I've updated the related PR. Please have a look.

**Comment by gcarmin** [comment]
@nyh  - can we add it to scylla?
Also - it only means that you can not use it when you update the counter - but if I create it with TTL? 
If I update the counter and then update the TTL?

**Comment by nyh** [comment]
> @nyh - can we add it to scylla?

Add what? support for USING TTL for counters? support for USING TIMESTAMP?

I don't know why USING TIMESTAMP is not supported with counter updates. Maybe somebody else (@denesb ?) knows. Just theorizing without reading the actual code, it sounds to me that it **should have worked** - that a counter type is a CRDT (similar to say, a set) and just like you can add an element to a set with USING TIMESTAMP you should be able to add a "+1" to a counter (by the way, in lists, we have a known bug in this: https://github.com/scylladb/scylladb/issues/6846). 

USING TTL is a different issue. It's not clear what adding +1 to a counter with TTL 7 should mean - should the counter be incremented, but then automatically be decremented 7 seconds from now? We don't want to support that - this will require the counter to remain a long list of separate increments (like a collection), which is the anti-thesis of what we want to do in counters - frequently "compacting" them to a small number of pieces or even just one number, to make it efficient to read the counter. So I don't think we'll ever want to support USING TTL for counter updates.

> Also - it only means that you can not use it when you update the counter - but if I create it with TTL? If I update the counter and then update the TTL? I know we and C* blocking it - but the wording needs to be a bit more precise in my POV

One of the most basic design decisions in Cassandra (and therefore Scylla) is that **writes don't need to read** - i.e., when you do a write, you don't check first if the item already exists or doesn't, you just put the write into a new sstable. This is why Scylla's INSERT and UPDATE do (almost) exactly the same thing for ordinary items, and the same is true for counters: there is no way to "create" a counter - all you can do is to "update" it (i.e., increment), and a non-existent counter "defaults" to 0 when you increment it. In fact, unlike ordinary items, Cassandra/Scylla don't even allow the "INSERT" keyword on a counter column as far as I know.
