### ISSUE TITLE
Can't run `test/cql-pytest/run` on arm64 mac

### ISSUE THREAD

**Issue by michaelhly** [scylladb/scylladb#15470]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 62a8a31be7b0e22df36eaa7b6814e1cd6207327d
Cluster size: n/a
OS (RHEL/CentOS/Ubuntu/AWS AMI): MacOS

I've built scylladb with `./tools/toolchain/dbuild ninja build/release/scylla`:
```
...
[327/333] CXX build/release/test/lib/key_utils.o
[328/333] CXX build/release/test/lib/test_utils.o
[329/333] CXX build/release/test/lib/test_services.o
[330/333] CXX build/release/test/lib/data_model.o
[331/333] CXX build/release/test/lib/random_schema.o
[332/333] CXX build/release/test/lib/cql_test_env.o
[333/333] LINK build/release/scylla
```

But I cannot boot scylladb instance with the `test/cql-pytest/run` script:
```
% python3 test/cql-pytest/run
Scylla is: /Users/michaelhly/Projects/scylladb/build/release/scylla.
Booting Scylla on 127.1.68.61 in /var/folders/s8/h5m7nxxx16l2cx8m4rzxjtf00000gn/T/scylla-test-17469...
Boot failed after 0.1 seconds.
Traceback (most recent call last):
  File "/Users/michaelhly/Projects/scylladb/test/cql-pytest/run", line 38, in <module>
    run.wait_for_services(pid, [
  File "/Users/michaelhly/Projects/scylladb/test/cql-pytest/run.py", line 416, in wait_for_services
    os.waitpid(pid, os.WNOHANG)
ChildProcessError: [Errno 10] No child processes

Subprocess output:

Traceback (most recent call last):
  File "/Users/michaelhly/Projects/scylladb/test/cql-pytest/run", line 35, in <module>
    pid = run.run_with_temporary_dir(cmd)
  File "/Users/michaelhly/Projects/scylladb/test/cql-pytest/run.py", line 74, in run_with_temporary_dir
    return run_with_generated_dir(run_cmd_generator, make_new_tempdir)
  File "/Users/michaelhly/Projects/scylladb/test/cql-pytest/run.py", line 60, in run_with_generated_dir
    os.execve(cmd[0], cmd, dict(os.environ, **env))
OSError: [Errno 8] Exec format error: '/var/folders/s8/h5m7nxxx16l2cx8m4rzxjtf00000gn/T/scylla-test-17469/test_scylla'
```

Generated `cmd` and `env`:
```sh
cmd: ['/var/folders/s8/h5m7nxxx16l2cx8m4rzxjtf00000gn/T/scylla-test-19168/test_scylla', '--options-file', '/Users/michaelhly/Projects/scylladb/conf/scylla.yaml', '--developer-mode', '1', '--ring-delay-ms', '0', '--collectd', '0', '--smp', '2', '
-m', '1G', '--overprovisioned', '--max-networking-io-control-blocks', '1000', '--unsafe-bypass-fsync', '1', '--kernel-page-cache', '1', '--commitlog-use-o-dsync', '0', '--flush-schema-tables-after-modification', 'false', '--api-address', '127.1.
74.224', '--rpc-address', '127.1.74.224', '--listen-address', '127.1.74.224', '--prometheus-address', '127.1.74.224', '--seed-provider-parameters', 'seeds=127.1.74.224', '--workdir', '/var/folders/s8/h5m7nxxx16l2cx8m4rzxjtf00000gn/T/scylla-test-
19168', '--auto-snapshot', '0', '--skip-wait-for-gossip-to-settle', '0', '--logger-log-level', 'compaction=warn', '--logger-log-level', 'migration_manager=warn', '--num-tokens', '16', '--query-tombstone-page-limit', '1000', '--range-request-time
out-in-ms', '300000', '--read-request-timeout-in-ms', '300000', '--counter-write-request-timeout-in-ms', '300000', '--cas-contention-timeout-in-ms', '300000', '--truncate-request-timeout-in-ms', '300000', '--write-request-timeout-in-ms', '300000
', '--request-timeout-in-ms', '300000', '--experimental-features=udf', '--experimental-features=keyspace-storage-options', '--enable-user-defined-functions', '1', '--authenticator', 'PasswordAuthenticator', '--authorizer', 'CassandraAuthorizer',
 '--strict-allow-filtering', 'true', '--strict-is-not-null-in-views', 'true', '--permissions-update-interval-in-ms', '100', '--permissions-validity-in-ms', '100', '--shutdown-announce-in-ms', '0']

env:{'UBSAN_OPTIONS': 'halt_on_error=1:abort_on
_error=1:suppressions=/Users/michaelhly/Projects/scylladb/ubsan-suppressions.supp', 'ASAN_OPTIONS': 'disable_coredump=0:abort_on_error=1:detect_stack_use_after_returns=1'} 
```

**Comment by nyh** [comment]
When you build an executable with "dbuild" it's not just a different compiler, it's also a set of dynamically-loaded libraries, so you need to also **run** Scylla in that environment. In your case, you should be running
```
dbuild test/cql-pytest/run
```
However, I don't see how the "Exec format error" can be explained by using the wrong libraries. Maybe it's a different issue:

What test/cql-pytest/run.py (the tiny library that test/cql-pytest/run uses) does is to make a symbolic link with that long ugly name you see of the **latest built Scylla** from the pattern `build/*/scylla`.  

Could it be that after building the version of Scylla you wanted to run, you also built another (non arm) version, and that is the version that `run` is trying to run?

You can `touch` the scylla executable you want to run, or set the SCYLLA environment variable to the path of the arm64 executable. For example:
```
dbuild env SCYLLA=build/whatever/scylla test/cql-pytest/run
```

I hope one of these ideas works.

**Comment by tchaikov** [comment]
@michaelhly hi Michael , so i think you 

1. built scylla in a docker container which is in turn supported by a hypervisor on MacOS.
2. run the test on .. wait, on MacOS? you didn't provide enough information in this regard. i deduced this by looking at the path `/Users/michaelhly/`. some popular linux distros do not use this for `$HOME`, they use something like `/home/michaelhly` instead.

if this is true, then you were trying to an linux application on Mac. but for couple reasons the scylla executable does not run on MacOS:

1. different executable format (Mach-O versus ELF)
2. different syscalls (darwin versus linux)
3. different availability of third party libraries (you name it..)
4. and more

so, please make sure that when you run `python3 test/cql-pytest/run`, you also launch the test using a docker environment.

**Comment by michaelhly** [comment]
> When you build an executable with "dbuild" it's not just a different compiler, it's also a set of dynamically-loaded libraries, so you need to also **run** Scylla in that environment. In your case, you should be running
> 
> ```
> dbuild test/cql-pytest/run
> ```
> 
> However, I don't see how the "Exec format error" can be explained by using the wrong libraries. Maybe it's a different issue:
> 
> What test/cql-pytest/run.py (the tiny library that test/cql-pytest/run uses) does is to make a symbolic link with that long ugly name you see of the **latest built Scylla** from the pattern `build/*/scylla`.
> 
> Could it be that after building the version of Scylla you wanted to run, you also built another (non arm) version, and that is the version that `run` is trying to run?
> 
> You can `touch` the scylla executable you want to run, or set the SCYLLA environment variable to the path of the arm64 executable. For example:
> 
> ```
> dbuild env SCYLLA=build/whatever/scylla test/cql-pytest/run
> ```
> 
> I hope one of these ideas works.

This worked! Thank you!
