### ISSUE TITLE
test.py: AsertionError: Deadline exceeded, failing test

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#15482]
I can see this assertion in a few different failures I'm not sure if it's a specific test failure or util.py change
**Currently it blocks gating** 

- [test_raft_cluster_features.test_downgrade_after_successful_upgrade_fails](https://jenkins.scylladb.com/job/scylla-master/job/next/6548/testReport/junit/(root)/test_raft_cluster_features/Tests___Unit_Tests___test_downgrade_after_successful_upgrade_fails/)
- [test_fencing.test_fence_hints](https://jenkins.scylladb.com/job/scylla-master/job/next/6547/testReport/junit/(root)/test_fencing/Tests___Unit_Tests___test_fence_hints/)
- [test_raft_cluster_features.test_joining_old_node_fails](https://jenkins.scylladb.com/job/scylla-master/job/next/6546/testReport/junit/(root)/test_raft_cluster_features/Tests___Unit_Tests___test_joining_old_node_fails/)

```
manager = <test.pylib.manager_client.ManagerClient object at 0x7f73dea70150>

    @pytest.mark.asyncio
    async def test_downgrade_after_successful_upgrade_fails(manager: ManagerClient) -> None:
        for _ in range(3):
            await manager.server_add()
>       await test_cluster_features.test_downgrade_after_successful_upgrade_fails(manager)

test/topology_experimental_raft/test_raft_cluster_features.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology/test_cluster_features.py:172: in test_downgrade_after_successful_upgrade_fails
    await asyncio.gather(*(wait_for_feature(TEST_FEATURE_NAME, cql, h, time.time() + 60) for h in hosts))
test/pylib/util.py:131: in wait_for_feature
    await wait_for(feature_is_enabled, deadline)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_feature.<locals>.feature_is_enabled at 0x7f73dc4565c0>
deadline = 1695168605.547509, period = 1

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float, period: float = 1) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:45: AssertionError
```

**Comment by piodul** [comment]
The failure in `test_joining_node_fails` is related to 8c1e694644d23dd38c15d5ec42b6892b3e3ac341. The test restarts all nodes at once, and the nodes try to perform group0 operations in parallel, so some of them fail and need to be retried.

Recently, the a line was added to the start of topology coordinator's which is suposed to fence old writes of other coordinators:

https://github.com/scylladb/scylladb/blob/66286e45a85ed0b828cfa26d91ff39f7bf36855c/service/storage_service.cc#L2270-L2280

However, it's not a part of topology coordinator's retry loop, so if this fails then the topology coordinator gets stuck until the node loses leadership.

The test timed out because it waited for a feature to be enabled, but in raft cluster features it is done by the topology coordinator - which got stuck. It happened on the node that was chosen as a leader after restart (https://jenkins.scylladb.com/job/scylla-master/job/next/6546/artifact/testlog/x86_64/debug/scylla-1070.log):

```
INFO  2023-09-19 19:58:36,904 [shard 0:stre] storage_service - raft topology: start topology coordinator fiber
INFO  2023-09-19 19:58:36,906 [shard 0:main] raft_group0 - gaining leadership
INFO  2023-09-19 19:58:36,951 [shard 0:comp] compaction - [Compact system_schema.types c6505990-570d-11ee-919f-ab46b323d046] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-1070/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/me-3g9i_1b5o_53wdc27q169sif5eme-big-Data.db:level=0]. 11kB to 5kB (~52% of original) in 73ms = 152kB/s. ~256 total partitions merged to 2.
INFO  2023-09-19 19:58:36,959 [shard 0:comp] compaction - [Compact system.discovery c661beb0-570d-11ee-919f-ab46b323d046] Compacting [/scylladir/testlog/x86_64/debug/scylla-1070/data/system/discovery-1ef3d7924f263706a049fc39024f49c5/me-3g9i_1b5j_3z6bk27q169sif5eme-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-1070/data/system/discovery-1ef3d7924f263706a049fc39024f49c5/mc-2-big-Data.db:level=0:origin=memtable]
INFO  2023-09-19 19:58:37,132 [shard 0:stre] storage_service - raft topology: updating topology with local metadata
INFO  2023-09-19 19:58:37,178 [shard 0:main] raft_group_registry - marking Raft server fab6b687-8ea1-42f0-b5cf-3fbff64b86ca as alive for raft groups
INFO  2023-09-19 19:58:37,188 [shard 0:comp] compaction - [Compact system.discovery c661beb0-570d-11ee-919f-ab46b323d046] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-1070/data/system/discovery-1ef3d7924f263706a049fc39024f49c5/me-3g9i_1b5p_00n5c27q169sif5eme-big-Data.db:level=0]. 10kB to 5kB (~53% of original) in 184ms = 58kB/s. ~256 total partitions merged to 1.
INFO  2023-09-19 19:58:37,194 [shard 0:comp] compaction - [Compact system_schema.indexes c685c170-570d-11ee-919f-ab46b323d046] Compacting [/scylladir/testlog/x86_64/debug/scylla-1070/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/me-3g9i_1b5m_4jys027q169sif5eme-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-1070/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/me-3g9i_1b5k_1c84027q169sif5eme-big-Data.db:level=0:origin=memtable]
INFO  2023-09-19 19:58:37,349 [shard 0:goss] gossip - InetAddress 127.101.186.29 is now UP, status = NORMAL
INFO  2023-09-19 19:58:37,400 [shard 0:stre] storage_service - raft topology: refreshing topology to check if it's synchronized with local metadata
INFO  2023-09-19 19:58:37,509 [shard 0:comp] compaction - [Compact system_schema.indexes c685c170-570d-11ee-919f-ab46b323d046] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-1070/data/system_schema/indexes-0feb57ac311f382fba6d9024d305702f/me-3g9i_1b5p_1cv9c27q169sif5eme-big-Data.db:level=0]. 11kB to 5kB (~52% of original) in 256ms = 43kB/s. ~256 total partitions merged to 2.
INFO  2023-09-19 19:58:37,529 [shard 0:comp] compaction - [Compact system_schema.computed_columns c6b77fd0-570d-11ee-919f-ab46b323d046] Compacting [/scylladir/testlog/x86_64/debug/scylla-1070/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/me-3g9i_1b5m_45lsw27q169sif5eme-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-1070/data/system_schema/computed_columns-cc7c7069374033c192a4c3de78dbd2c4/me-3g9i_1b5j_53onk27q169sif5eme-big-Data.db:level=0:origin=memtable]
INFO  2023-09-19 19:58:37,603 [shard 0:goss] gossip - InetAddress 127.101.186.35 is now UP, status = NORMAL
INFO  2023-09-19 19:58:37,646 [shard 0:stre] storage_service - raft topology: race while changing state: Starting new topology coordinator 746532b0-cdc0-419a-bf78-3d5318b9fbad. Retrying
```

cc: @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> The test timed out because it waited for a feature to be enabled, but in raft cluster features it is done by the topology coordinator - which got stuck. It happened on the node that was chosen as a leader after restart 

What branch is that? Neither the mentioned commit nor cluster feature enablement through the coordinator are not in the master yet.

**Comment by kbr-scylla** [comment]
Dequeued https://github.com/scylladb/scylladb/commit/8c1e694644d23dd38c15d5ec42b6892b3e3ac341

**Comment by gleb-cloudius** [comment]
As for the commit, yes fencing should retry. For some reason I thought update_topology_state retries internally. but it should no of course.

**Comment by piodul** [comment]
> What branch is that? Neither the mentioned commit nor cluster feature enablement through the coordinator are not in the master yet.

Cluster feature enablement through the coordinator is in master for some time already (https://github.com/scylladb/scylladb/pull/15168). The commit https://github.com/scylladb/scylladb/commit/8c1e694644d23dd38c15d5ec42b6892b3e3ac341 is not in master, but it was queued.

**Comment by piodul** [comment]
> I'll check logs from the other cluster features test soon, but it's likely the same issue because that test also restarts all nodes.

I confirm this, the test `test_downgrade_after_successful_upgrade_fails` hit this on one of the nodes, too: https://jenkins.scylladb.com/job/scylla-master/job/next/6548/artifact/testlog/x86_64/debug/scylla-1150.log .

**Comment by kbr-scylla** [comment]
I dequeued the patch that caused cluster features test failures
the fencing test failure is tracked here: https://github.com/scylladb/scylladb/issues/15285
therefore I'm closing this issue
