### ISSUE TITLE
test_concurrent_reads_and_eviction: Mutation read doesn't match any expected version

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15483]
This was hit in CI with an unrelated change so it can be attrobuted to baseline version b87660f90c
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3706/artifact/testlog/x86_64/release/boost.row_cache_test.test_concurrent_reads_and_eviction.3.log
```
random-seed=2470087052
random_mutation_generator seed: 2568563592
test/boost/row_cache_test.cc(3447): fatal error: in "test_concurrent_reads_and_eviction": Mutation read doesn't match any expected version ...
```

[boost.row_cache_test.test_concurrent_reads_and_eviction.3.log.gz](https://github.com/scylladb/scylladb/files/12669636/boost.row_cache_test.test_concurrent_reads_and_eviction.3.log.gz)

@michoecho please look into this

**Comment by bhalevy** [comment]
> I looked into it and it appears to be a real problem. It seems that reverse reads are reading range tombstones incorrectly sometimes. But it will take some work to understand the cause.

Cc @denesb

**Comment by denesb** [comment]
Could this be a regression caused by v2 internal representation?

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6632/

**Comment by denesb** [comment]
@michoecho did you managed to reproduce this? I couldn't reproduce even with `--count=100` and the seed from the last failure hardcoded.

**Comment by michoecho** [comment]
Yes, I managed to reproduce it, but it's rare. It reproduced about once per ~20 minutes of running in the loop. `--count=100` is not good enough.

*However*, I noticed that when I set `debuggable = true;` in `test/lib/mutation_source_test.cc`, the failure reproduces very easily. (About once per ~3 runs.)

**Comment by denesb** [comment]
> _However_, I noticed that when I set `debuggable = true;` in `test/lib/mutation_source_test.cc`, the failure reproduces very easily. (About once per ~3 runs.)

Indeed, I immediately got a failing run once I set `debuggable  = true`. Thanks for the tip.

**Comment by denesb** [comment]
@michoecho if you don't mind, I will take over this issue.

**Comment by michoecho** [comment]
> @michoecho if you don't mind, I will take over this issue.

Sure, why not. But when you are done with it, please tell how you debugged it. `test_concurrent_reads_and_eviction` is very hard to debug. I'm interested what techniques other people use to do it.

**Comment by denesb** [comment]
> > @michoecho if you don't mind, I will take over this issue.
> 
> Sure, why not. But when you are done with it, please tell how you debugged it. `test_concurrent_reads_and_eviction` is very hard to debug. I'm interested what techniques other people use to do it.

Ok, will do.

**Comment by denesb** [comment]
Wow, I was super lucky and got a reallly small mutation reproducer:
```
test/lib/mutation_assertions.hh(134): fatal error: in "test_concurrent_reads_and_eviction": Mutations differ, expected {table: 'ks.cf', key: {'pk': ef4b9e22, token: -8892763474812993290}, mutation_partition: {
  tombstone: {tombstone: timestamp=3330002, deletion_time=777000602},
  range_tombstones: {
    {range_tombstone: start={position: clustered, ckp{00040e8c563e0004e1f8219b}, 1}, end={position: clustered, ckp{00040e8c563e0004f32c13c1}, -1}, {tombstone: timestamp=3330002, deletion_time=777000918}},
    {range_tombstone: start={position: clustered, ckp{00040e8c563e0004f32c13c1}, -1}, end={position: clustered, ckp{000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001113}},
    {range_tombstone: start={position: clustered, ckp{000416eb7874}, -1}, end={position: clustered, ckp{000416eb7874}, 1}, {tombstone: timestamp=3330002, deletion_time=777001120}},
    {range_tombstone: start={position: clustered, ckp{000416eb7874}, 1}, end={position: clustered, ckp{00047750d3ef}, 1}, {tombstone: timestamp=3330002, deletion_time=777001128}},
    {range_tombstone: start={position: clustered, ckp{00047750d3ef}, 1}, end={position: clustered, ckp{000486dd59e5000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001121}},
    {range_tombstone: start={position: clustered, ckp{000486dd59e5000416eb7874}, -1}, end={position: clustered, ckp{00048b105fe0000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001120}},
    {range_tombstone: start={position: clustered, ckp{00048b105fe0000416eb7874}, -1}, end={position: clustered, ckp{0004e1f8219b}, -1}, {tombstone: timestamp=3330002, deletion_time=777001117}},
    {range_tombstone: start={position: clustered, ckp{0004e1f8219b}, -1}, end={position: clustered, ckp{0004ef4b9e22}, -1}, {tombstone: timestamp=3330002, deletion_time=777001104}},
    {range_tombstone: start={position: clustered, ckp{0004ef4b9e22}, -1}, end={position: clustered, ckp{}, 1}, {tombstone: timestamp=3330002, deletion_time=777001004}}},
  rows: [
  ]
}
}
 ...but got: {table: 'ks.cf', key: {'pk': ef4b9e22, token: -8892763474812993290}, mutation_partition: {
  tombstone: {tombstone: timestamp=3330002, deletion_time=777000602},
  range_tombstones: {
    {range_tombstone: start={position: clustered, ckp{00040e8c563e0004e1f8219b}, 1}, end={position: clustered, ckp{00040e8c563e}, 1}, {tombstone: timestamp=3330002, deletion_time=777000918}},
    {range_tombstone: start={position: clustered, ckp{00040e8c563e}, 1}, end={position: clustered, ckp{000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001113}},
    {range_tombstone: start={position: clustered, ckp{000416eb7874}, -1}, end={position: clustered, ckp{000416eb7874}, 1}, {tombstone: timestamp=3330002, deletion_time=777001120}},
    {range_tombstone: start={position: clustered, ckp{000416eb7874}, 1}, end={position: clustered, ckp{00047750d3ef}, 1}, {tombstone: timestamp=3330002, deletion_time=777001128}},
    {range_tombstone: start={position: clustered, ckp{00047750d3ef}, 1}, end={position: clustered, ckp{000486dd59e5000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001121}},
    {range_tombstone: start={position: clustered, ckp{000486dd59e5000416eb7874}, -1}, end={position: clustered, ckp{00048b105fe0000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001120}},
    {range_tombstone: start={position: clustered, ckp{00048b105fe0000416eb7874}, -1}, end={position: clustered, ckp{0004e1f8219b}, -1}, {tombstone: timestamp=3330002, deletion_time=777001117}},
    {range_tombstone: start={position: clustered, ckp{0004e1f8219b}, -1}, end={position: clustered, ckp{0004ef4b9e22}, -1}, {tombstone: timestamp=3330002, deletion_time=777001104}},
    {range_tombstone: start={position: clustered, ckp{0004ef4b9e22}, -1}, end={position: clustered, ckp{}, 1}, {tombstone: timestamp=3330002, deletion_time=777001004}}},
  rows: [
  ]
}
}
````
Usually the printout is 10K lines.
The diff:
```diff
--- /dev/fd/63	2023-10-09 09:13:21.545162034 -0400
+++ /dev/fd/62	2023-10-09 09:13:21.545162034 -0400
@@ -1,9 +1,9 @@
-test/lib/mutation_assertions.hh(134): fatal error: in "test_concurrent_reads_and_eviction": Mutations differ, expected 
+ ...but got: 
 {table: 'ks.cf', key: {'pk': ef4b9e22, token: -8892763474812993290}, mutation_partition: {
   tombstone: {tombstone: timestamp=3330002, deletion_time=777000602},
   range_tombstones: {
-    {range_tombstone: start={position: clustered, ckp{00040e8c563e0004e1f8219b}, 1}, end={position: clustered, ckp{00040e8c563e0004f32c13c1}, -1}, {tombstone: timestamp=3330002, deletion_time=777000918}},
-    {range_tombstone: start={position: clustered, ckp{00040e8c563e0004f32c13c1}, -1}, end={position: clustered, ckp{000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001113}},
+    {range_tombstone: start={position: clustered, ckp{00040e8c563e0004e1f8219b}, 1}, end={position: clustered, ckp{00040e8c563e}, 1}, {tombstone: timestamp=3330002, deletion_time=777000918}},
+    {range_tombstone: start={position: clustered, ckp{00040e8c563e}, 1}, end={position: clustered, ckp{000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001113}},
     {range_tombstone: start={position: clustered, ckp{000416eb7874}, -1}, end={position: clustered, ckp{000416eb7874}, 1}, {tombstone: timestamp=3330002, deletion_time=777001120}},
     {range_tombstone: start={position: clustered, ckp{000416eb7874}, 1}, end={position: clustered, ckp{00047750d3ef}, 1}, {tombstone: timestamp=3330002, deletion_time=777001128}},
     {range_tombstone: start={position: clustered, ckp{00047750d3ef}, 1}, end={position: clustered, ckp{000486dd59e5000416eb7874}, -1}, {tombstone: timestamp=3330002, deletion_time=777001121}},
````

**Comment by michoecho** [comment]
> Wow, I was super lucky and got a reallly small mutation reproducer:

You weren't super lucky, it happens quite often. There is a fairly high chance that the range tombstones will remove all rows and only range tombstones will remain in the compacted output.

**Comment by denesb** [comment]
Thanks for the tips. From what I see, the problem is that the first range tombstone is extended. It should only go as far as `00040e8c563e0004f32c13c1` but it is extended to cover the entire `00040e8c563e` prefix.

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6632/

**Comment by denesb** [comment]
After a lot of staring at different results and annotating the generated mutations with metadata, it seems that the bug is that the read will sometimes mix in range tombstones from a later version. Don't know yet how/why this happens.

**Comment by denesb** [comment]
I expted this to be though but I got more than what I bargained for.

I managed to narrow down the problem to prefix keys. I think we are bitten by broken prefix keys compare, in reverse mode.

**Comment by denesb** [comment]
After yet more investigation, both of my above comments are wrong. The bug is not limited to prefix keys and the "wrong" keys do not come from later versions, they "bleed through" from earlier versions. I have manually verified the merging rules in the test and the expected mutation is correct. Which means that we have a bug in cache, where it merges range-tombstones from two versions wrong, sometimes a range tombstone, which is overridden by a later version, is still included.

I still don't understand why we need reverse reads for this to reproduce. The bug itself can happen with forward reads, but only if there are prior reverse reads. Maybe a reverse read mis-populates and then a later read steps on this? I don't yet know.

My 3 main suspicions for the source of the bug are:
* switching between reading from cache and underlying
* partition snapshot row cursor
* cache population logic

Debugging is made extra hard by the fact that despite hard-coding the random seeds, the test has innate randomness due to the timing between the concurrent reads and the concurrent updates/eviction. This means that each time I add more logging, I have to analyze a new case, digging up information from ~50K line of logs.

**Comment by michoecho** [comment]
> Debugging is made extra hard by the fact that despite hard-coding the random seeds, the test has innate randomness due to the timing between the concurrent reads and the concurrent updates/eviction. This means that each time I add more logging, I have to analyze a new case, digging up information from ~50K line of logs.

If this is a problem, make the test deterministic. This test doesn't do any IO and doesn't depend on real time, so you only have to ensure that `need_preempt()` returns the same sequence of decisions on every run.

One way to do it is to run as usual, but write down all the outcomes of `need_preempt()` to a file. When you get a failed run, make `need_preempt()` read its decisions from the file it created earlier. Then you will always get the same run.
That's what I did when debugging https://github.com/scylladb/scylladb/issues/12462, and it worked well.

A slightly easier (but more invasive) way is to make the result of `need_preempt()` pseudorandom. I.e. do this:
```diff
+
+namespace testing {
+    extern thread_local std::default_random_engine local_random_engine;
+}
+
 bool need_preempt() noexcept {
+    return testing::local_random_engine() % 100 == 0;
 #ifndef SEASTAR_DEBUG
     // prevent compiler from eliminating loads in a loop
     std::atomic_signal_fence(std::memory_order_seq_cst);
```

I just verified that this also works for this test. With this, once you find a failing seed, it will always keep resulting in the same failed run.

**Comment by denesb** [comment]
This seem to have worked (random-seed for `need_preempt()`, thanks for the tip.

**Comment by bhalevy** [comment]
> This seem to have worked (random-seed for `need_preempt()`, thanks for the tip.

Sounds like we should it make it an official and present a command line option, possible available only in non-release modes.

**Comment by denesb** [comment]
I found *a* bug. But looks like there might be more.

**Comment by denesb** [comment]
> I found _a_ bug. But looks like there might be more.

Found another bug. Hope this is the last.

**Comment by avikivity** [comment]
> > Sounds like we should it make it an official and present a command line option, possible available only in non-release modes.
> 
> It might be useful sometimes, but it also covers only a subset of a general problem.
> 
> Non-reproducible tests are evil. In a better world, we would have designed our test frameworks in such a way that all tests can be run with recording, and be replayed when they fail.
> 
> It's probably not even that hard to reach. I think it would be sufficient to record and replay the trace of:
> 
> 1. All `preempt_needed` decisions.
> 2. The results of all clock reads.
> 3. The IDs of all I/O completions and their lengths.
> 4. The IDs of timer completions.
> 5. The shard IDs of smp message receives.
> 6. The wakeups of condition_variables due to SIGTERM and SIGHUP.
> 
> Seastar is in a very good position for making all tests determinizable, and it's a shame that we don't make use of it. We could be two weeks of work away from eliminating the problem of non-reproducible test failures altogether.


@bhalevy please find time for it

**Comment by michoecho** [comment]
> @bhalevy please find time for it

@bhalevy Maybe I could do this (making Seastar tests deterministic/replayable) as a "20% project"?

**Comment by bhalevy** [comment]
> > @bhalevy please find time for it
> 
> @bhalevy Maybe I could do this (making Seastar-based tests deterministic/replayable) as a "20% project"?

Yes, it'd be a very good use of your time.  Thanks

**Comment by michoecho** [comment]
> > I found _a_ bug. But looks like there might be more.
> 
> Found another bug. Hope this is the last.

@denesb Don't tease us. What are the bugs? Are they fun?

**Comment by denesb** [comment]
> > > I found _a_ bug. But looks like there might be more.
> > 
> > 
> > Found another bug. Hope this is the last.
> 
> @denesb Don't tease us. What are the bugs? Are they fun?

I still don't know what the second bug is. I just know it exists.

As for the first one, it is this:
```diff

diff --git a/cache_flat_mutation_reader.hh b/cache_flat_mutation_reader.hh
index 8f5fc0a412..6de2fb2cd0 100644
--- a/cache_flat_mutation_reader.hh
+++ b/cache_flat_mutation_reader.hh
@@ -513,7 +513,9 @@ bool cache_flat_mutation_reader::ensure_population_lower_bound() {
             return false;
         }
 
-        if (cmp(cur.position(), _last_row.position()) != 0) {
+        if (cmp(cur.table_position(), _last_row.position()) != 0) {
             return false;
         }
```

**Comment by denesb** [comment]
The second bug is much more elusive. Each time I'm convinced I found it, it turns out the code at hand is correct and the bug happened at an earlier point, creating bad data.

**Comment by michoecho** [comment]
I found at least one logic bug:
```diff
diff --git a/cache_flat_mutation_reader.hh b/cache_flat_mutation_reader.hh
index 30f2f5c503..db93546980 100644
--- a/cache_flat_mutation_reader.hh
+++ b/cache_flat_mutation_reader.hh
@@ -579,12 +579,12 @@ void cache_flat_mutation_reader::maybe_update_continuity() {
                         if (insert_result.second) {
                             clogger.trace("csm {}: L{}: inserted dummy at {}", fmt::ptr(this), __LINE__, insert_result.first->position());
                             _snp->tracker()->insert(*insert_result.first);
+                            clogger.trace("csm {}: set_continuous({}), prev={}, rt={}", fmt::ptr(this), insert_result.first->position(),
+                                          _last_row.position(), _current_tombstone);
+                            insert_result.first->set_continuous(true);
+                            insert_result.first->set_range_tombstone(_current_tombstone);
+                            clogger.trace("csm {}: set_continuous({})", fmt::ptr(this), e.position());
                         }
-                        clogger.trace("csm {}: set_continuous({}), prev={}, rt={}", fmt::ptr(this), insert_result.first->position(),
-                                      _last_row.position(), _current_tombstone);
-                        insert_result.first->set_continuous(true);
-                        insert_result.first->set_range_tombstone(_current_tombstone);
-                        clogger.trace("csm {}: set_continuous({})", fmt::ptr(this), e.position());
                         e.set_continuous(true);
                     });
                 } else {
```
Explanation: assume that cache contains the following row entries for a partition:
- (pos: before 1, continuous: true, rt: ts=0)
- (pos: at 1, continuous: false, rt: ts=1)
When a reader attempts to read this partition, it will attempt to read underlying for range (before 1, at 1). This will set `_current_tombstone` to false, then it will read underlying (without consuming any rows, since the range is obviously empty), then it will call `maybe_update_continuity()`. `maybe_update_continuity()` will see that after finishing the read from underlying `_current_tombstone` is null, which is different from the tombstone of `_next_row`, so it will insert a dummy before `next_row` and set its rt to `_current_tombstone`.
But that's invalid, because an entry at this position (before 1) already exists, and is meaningful. Setting its rt to null makes the ts=0 disappear.

I'm not sure if the fix proposed above is sound, though.

Also, I found a third, unrelated bug (which results in undefined behavior, rather than a test failure):
```
diff --git a/cache_flat_mutation_reader.hh b/cache_flat_mutation_reader.hh
index 3a71326de4..30f2f5c503 100644
--- a/cache_flat_mutation_reader.hh
+++ b/cache_flat_mutation_reader.hh
@@ -341,7 +342,7 @@ future<> cache_flat_mutation_reader::do_fill_buffer() {
             });
         }
         _state = state::reading_from_underlying;
-        _population_range_starts_before_all_rows = _lower_bound.is_before_all_clustered_rows(*_schema) && !_read_context.is_reversed();
+        _population_range_starts_before_all_rows = _lower_bound.is_before_all_clustered_rows(*_schema) && !_read_context.is_reversed() && !_last_row;
         _underlying_upper_bound = _next_row_in_range ? position_in_partition::before_key(_next_row.position())
                                                      : position_in_partition(_upper_bound);
         if (!_read_context.partition_exists()) {
```
There is a place in the code which assumes that `_population_range_starts_before_all_rows` implies `!_last_row`. But this is not necessarily true if there exists a `rows_entry` with position=before_all_rows. In this case `_last_row` might be referenced even if invalid, leading e.g. to segfaults or assert violations.

But the test is still failing. I'm trying to find the fourth bug now.

**Comment by michoecho** [comment]
@denesb The rabbit hole goes deep. Other than the bug you've found, I've found 4 bugs so far (I've listed two in the previous comment, the other two are continuity breaks during races in cache population), and it's not over yet. I'm trying to understand the sixth bug now.

**Comment by michoecho** [comment]
After fixing 8 bugs (or 10, depending on how you count), I haven't seen the test fail for 100000 consecutive runs. I'll let it run a million times and then I'll get to properly documenting and submitting the patches.

**Comment by avikivity** [comment]
It points at the thing being way to complicated for our own good.

I don't know what to suggest, apart from flattening MVCC to use the timestamp as a discriminant instead of a version object.

**Comment by denesb** [comment]
Watch-points are indeed awesome, the hard part is coming up with what is worth watching. Great job!

**Comment by avikivity** [comment]
Possibly [reversible debugging](https://rr-project.org/) can help in these cases.

**Comment by avikivity** [comment]
rr can't support aio or io_uring, so we'll have to add an epoll+threadpool reactor backend that shunts disk I/O through the syscall thread. Shouldn't be hard.

**Comment by denesb** [comment]
Backported to 5.4, 5.2 is not affected.

**Comment by denesb** [comment]
> 5.2 is not affected

@michoecho can you double check this please? AFAIK the bugs fixed here were introduced by the v2 migration. Did I miss something?

**Comment by michoecho** [comment]
> > 5.2 is not affected
> 
> @michoecho can you double check this please? AFAIK the bugs fixed here were introduced by the v2 migration. Did I miss something?

That's hard to say. Most of the affected code has greatly changed between 5.2 and 5.4, so it's hard to see which bugs could have been also present in 5.2.

But, for example, I think that https://github.com/scylladb/scylladb/pull/15945/commits/47299d6b068912af098f4cfb92fd8107878ba7dd also applies to 5.2.

**Comment by denesb** [comment]
> .

Please create a 5.2 backport PR with the patches you think apply to it.
