### ISSUE TITLE
repair: high latency of RBNO bootstrap

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#15505]
Sometimes when a new node is bootstrapped with RBNO enabled, 
the state change indicating bootstrap finish is delayed. Thus, tests 
wait idly until a server is added, even though the logs show that 
the bootstrap's already finished.

**Comment by avikivity** [comment]
@Deexie does this merit a backport, or does it only impact tests? in any case I think the code is new enough that 5.2 doesn't have the problem.

**Comment by Deexie** [comment]
> @Deexie does this merit a backport, or does it only impact tests? in any case I think the code is new enough that 5.2 doesn't have the problem.

It impacts users as well. And 5.2 contains `shard_repair_task_impl`, so I think it's worth backporting

**Comment by denesb** [comment]
> > @Deexie does this merit a backport, or does it only impact tests? in any case I think the code is new enough that 5.2 doesn't have the problem.
> 
> It impacts users as well. And 5.2 contains `shard_repair_task_impl`, so I think it's worth backporting

There are many conflicts, @Deexie please prepare a backport PR.

**Comment by Deexie** [comment]
> > > @Deexie does this merit a backport, or does it only impact tests? in any case I think the code is new enough that 5.2 doesn't have the problem.
> > 
> > 
> > It impacts users as well. And 5.2 contains `shard_repair_task_impl`, so I think it's worth backporting
> 
> There are many conflicts, @Deexie please prepare a backport PR.

The change for that modifies what's added in #15005 and related issue #14966 is not backported. Of course I can skip that part (and in this case that would be really easy). But the thing is that the changes are pretty related and #14966 seems to be much more harmful than this one. @denesb what do you think about opening a joint backport PR to `branch-5.2`?

**Comment by Deexie** [comment]
Oh, nevermind, I checked for compaction tasks in the middle of cherry-pick... 5.2 does not contain https://github.com/scylladb/scylladb/issues/14966, sorry. I opened #15875 with this change only

**Comment by asias** [comment]
> Sometimes when a new node is bootstrapped with RBNO enabled, the state change indicating bootstrap finish is delayed. Thus, tests wait idly until a server is added, even though the logs show that the bootstrap's already finished.

It is not clear to me what is the problem according the the description above. What "state changing" are you referring to?  I first thought it was about cql read / write latency.

**Comment by Deexie** [comment]
`effective_replication_map_ptr` is kept in memory longer than it used to. From a comment to erm class:
```
Holding to this object keeps the associated token_metadata_ptr alive, keeping the token metadata version alive and seen as in use.
```

**Comment by asias** [comment]
> `effective_replication_map_ptr` is kept in memory longer than it used to. From a comment to erm class:
> 
> ```
> Holding to this object keeps the associated token_metadata_ptr alive, keeping the token metadata version alive and seen as in use.
> ```

Yes, it helps to release the effective_replication_map_ptr earlier.  But do you see any actual problem, e.g., taking longer to finish repair, user facing higher read / write cql latency?

You mentioned in the opening message:

```
Thus, tests wait idly until a server is added, even though the logs show that
the bootstrap's already finished.
```

Not releasing effective_replication_map_ptr should not have any impact on when the bootstrap should be considered as finished.

**Comment by Deexie** [comment]
> > `effective_replication_map_ptr` is kept in memory longer than it used to. From a comment to erm class:
> > ```
> > Holding to this object keeps the associated token_metadata_ptr alive, keeping the token metadata version alive and seen as in use.
> > ```
> 
> Yes, it helps to release the effective_replication_map_ptr earlier. But do you see any actual problem, e.g., taking longer to finish repair, user facing higher read / write cql latency?
> 
> You mentioned in the opening message:
> 
> ```
> Thus, tests wait idly until a server is added, even though the logs show that
> the bootstrap's already finished.
> ```
> 
> Not releasing effective_replication_map_ptr should not have any impact on when the bootstrap should be considered as finished.

Yes, I saw the problem while writing a test in test/topology. It was a test related to task manager so I set `task_ttl` to some really big number and while 2-node cluster was created immediately, it took `task_ttl` for 3-node cluster.

I didn't really check the actual path, rather focused on symptoms. So I do not know how exactly alive erm causes ManagerClient::server_add to hang, but I can find it if that's important.

**Comment by mykaul** [comment]
Backport to 5.2 is via https://github.com/scylladb/scylladb/pull/15875 - what else remains here?
