### ISSUE TITLE
S3 object part uploading cannot be recovered

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#15509]
A problem -- when uploading a part of an object with the multipart uploading API, the connected over which http client sends the part data can be closed by the server without even letting the client finish sending the request body (not even replying)

In that case just repeating the same request _may_ succeed, but after the multipart upload finalization request, the server somehow remembers the failed-and-restarted part's size to be the "short" one (from the failed request) and fails to complete the upload.

Logs:

```
s3 - PUT part 37 5242880 bytes in 40 buffers  // PUT request is about to be prepared and sent
http - pop http connection 192.168.88.164:60394 from pool  // transport connection is obtained
http - Send [PUT ... over 192.168.88.164:60394 // the PUT request header is sent
s3 - upload 37 part data 5242880 bytes in 40 buffers // the PUT request body is sent
http - 192.168.88.164:60394 peer close // server closes its end before body is written to the transport
http - makring connection 192.168.88.164:60394 as non-persistent // http client notices this and wraps the connection
http - dropping connection 192.168.88.164:60394
http - destroyed connection 192.168.88.164:60394
http - Restarting request 1 time due to std::system_error (error system:32, sendmsg: Broken pipe) // http client tries to restart the request (after a while)
http - pop http connection 192.168.88.164:63429 from pool // another transport connection is obtained
http - Send [PUT ... over 192.168.88.164:63429 // the same PUT request header is sent again over new connection
s3 - upload 37 part data 5242880 bytes in 40 buffers // the PUT body is sent again, it's _still_ 5Mb in size
s3 - uploaded 37 part data -> etag = "0214cdbbfdfb6346e618ca997749b25e" // server ACKs the part upload and reports back the etag
http - Send [POST ... // multipart upload finalize
http - request finished with 400 Bad Request: <Error><Code>EntityTooSmall</Code><Message>Your proposed upload is smaller than the minimum allowed size</Message><ProposedSize>3136000</ProposedSize><MinSizeAllowed>5242880</MinSizeAllowed><PartNumber>38</PartNumber><ETag>0214cdbbfdfb6346e618ca997749b25e</ETag><RequestId>HFT82T3YB4VBYQ9V</RequestId><HostId>+Z0QVWwkA6wBucZPSYcVGmiJLXU25k33CRot7ASCrbl/OsXfjUe85bh9FcyxrgIGrDLf33oh588=</HostId></Error>
```

(despite server reports part 38, that's OK, S3 client's part numbers are 1-less than the part-numbers that are sent to the server (spoiler: that's because array is indexed from 0 but in S2 api parts are numbered from 1))

Cc @tchaikov

**Comment by xemul** [comment]
Yup, re-uploading a part is ... not working as expected by the driver. After the upload is complete ListParts reports reduced size for the failed-and-reuploaded one

**Comment by xemul** [comment]
Parts are not required to be sequential. So it looks like if a part upload fails, the solution is not to replay the same request, but to upload _another_ part and just ignore the failed one

**Comment by tchaikov** [comment]
> Parts are not required to be sequential. 

yeah, the multipart upload initializes is performed in parallel: each part of the object to be uploaded is uploaded separately, and the upload is finalized after all parts are PUT'ed.

> the solution is not to replay the same request, but to upload another part and just ignore the failed one

i don't quite get this part. what do you mean by "another part", if we fail to upload range [10MB..15MB), i think we should upload [10MB, 15MB) again?

i am reading https://github.com/boto/boto/blob/develop/bin/s3put to understand how boto does the multipart upload. if one of the part fails, it retries in https://github.com/boto/boto/blob/70c65b4f67af41ccfd40d21e49880be568997ba6/bin/s3put#L147 . in which it always rereads exactly the same chunk of the part it is supposed to upload, and upload all of them in a single `PUT` request, see https://github.com/boto/boto/blob/70c65b4f67af41ccfd40d21e49880be568997ba6/boto/s3/key.py#L803.

**Comment by xemul** [comment]
> yeah, the multipart upload is performed in parallel:

Our driver also does it in parallel

>  don't quite get this part. what do you mean by "another part", if we fail to upload range [10MB..15MB), i think we should upload [10MB, 15MB) again?

Yes, we should upload it again. But if we reuse the same part number, and even get the etag from the second upload, finalization request will result in error -- for some reason aws remembers the part size from the actual data received from the failed upload. So my point is that we should probably pick another part number for reupload. Our find some other way

**Comment by xemul** [comment]
The sequence is like this:

- put part 7 content length 5mb
- writing part body fails after 3mb being sent
- put part 7 content length 5mb (again)
- success, got etag from server
- ... (upload other parts)
- finalize upload, part 7 etag is from the 2nd attempt reply
- bad request error, server says that part 7 had small size of 3mb

**Comment by xemul** [comment]
Docs say
> If you upload a new part using the same part number as a previously uploaded part, the previously uploaded part is overwritten.

Maybe there's a bug in our reuploading code... From logs it doesn't look like this, reupload happens with the same content length... Weird

**Comment by tchaikov** [comment]
yeah, i was reading https://github.com/boto/boto/blob/develop/boto/s3/multipart.py#L228 also, seems they do reuse the same `partNumber`.
