### ISSUE TITLE
[CDC][Alternator] Spin up of a new node fails after the decommission of another node

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#15525]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

During the `disrupt_decommission_streaming_err` nemesis we had following steps:

- Trigger decommission of a node
- Reboot that node in the middle
- Add new node If that node decommission was considered successful -> test fails on this step
- Run `nodetool rebuild` command - `not reached`

SCT log messages prior the new node addition:
```
2023-09-21 01:26:54,486 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  decommission "...
...
2023-09-21 01:26:58,821 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-09-21T01:26:58+00:00 alternator-3h-5-2-db-node-f2926fb5-2     !INFO | scylla[5549]:  [shard  0] api - decommission
...
2023-09-21 01:28:15,425 f:cluster.py      l:1037 c:sdcm.cluster_aws     p:DEBUG > Node alternator-3h-5-2-db-node-f2926fb5-2 [44.204.197.239 | 10.12.2.213] (seed: False): Hardly rebooting node
...
2023-09-21 01:28:19,199 f:db_log_reader.py l:114  c:sdcm.db_log_reader   p:DEBUG > 2023-09-21T01:28:14+00:00 alternator-3h-5-2-db-node-f2926fb5-2     !INFO | scylla[5549]:  [shard  0] storage_service - decommission[e9b9bdb6-5ce8-4609-9401-f042e1b3b6d8]: leaving token ring
...
2023-09-21 01:33:37,433 f:__init__.py     l:101  c:sdcm.utils.raft      p:DEBUG > Token rings members ids: {'19bd751d-dd5b-4d96-b660-d4c2140e38f4', '1e6a080b-08ae-4456-a99f-7b94cd9f1432', '453aea2c-9052-4f62-baef-d451d474a650', '190704f0-54d9-4dc6-a852-95f84d3f67a9', '9626e619-79e3-437a-98ce-574e50cb038b', 'd1268dc5-df37-4530-a13d-2ffc937848b8'}
2023-09-21 01:33:37,433 f:__init__.py     l:102  c:sdcm.utils.raft      p:DEBUG > Group0 members ids: {'19bd751d-dd5b-4d96-b660-d4c2140e38f4', '453aea2c-9052-4f62-baef-d451d474a650', '190704f0-54d9-4dc6-a852-95f84d3f67a9', '9626e619-79e3-437a-98ce-574e50cb038b', 'd1268dc5-df37-4530-a13d-2ffc937848b8', '1e6a080b-08ae-4456-a99f-7b94cd9f1432'}
2023-09-21 01:33:37,433 f:__init__.py     l:104  c:sdcm.utils.raft      p:DEBUG > Group0 differs from token ring: []
2023-09-21 01:33:37,433 f:__init__.py     l:134  c:sdcm.utils.raft      p:DEBUG > Group0 cleaned
2023-09-21 01:33:37,433 f:cluster.py      l:4657 c:sdcm.cluster         p:ERROR > Decommission for node Node alternator-3h-5-2-db-node-f2926fb5-2 [44.204.197.239 | 10.12.2.213] (seed: False) was aborted
2023-09-21 01:33:37,433 f:nemesis.py      l:3540 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Decommission aborted, Group0 was cleaned successfully. New node will be added
2023-09-21 01:33:37,433 f:nemesis.py      l:3548 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Decommission might complete before stopping it. Re-add a new node
2023-09-21 01:33:37,433 f:nemesis.py      l:1210 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Adding new node to cluster...
```

New node `node-8` logs:
```
Sep 21 01:36:59 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] storage_service - entering BOOTSTRAP mode
Sep 21 01:36:59 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] storage_service - Wait until local node knows tokens of peer nodes
Sep 21 01:36:59 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] gossip - Waiting for pending range setup...
Sep 21 01:36:59 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  4] compaction - [Compact system.local 5b12e720-581f-11ee-90f6-54d8e91b1b31] Compacted 2 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/me-102-big-Data.db:level=0]. 32kB to 19kB (~59% of original) in 5ms = 6MB/s. ~256 total partitions merged to 1.
Sep 21 01:37:36 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] gossip - No gossip backlog; proceeding
Sep 21 01:37:36 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] cdc - Inserting new generation data at UUID 75b1c5eb-044d-4666-817a-9d893984edaf
Sep 21 01:37:36 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] init - Shutting down group 0 service
...
Sep 21 01:37:38 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] init - Shutting down sighup was successful
Sep 21 01:37:38 alternator-3h-5-2-db-node-f2926fb5-8 scylla[5463]:  [shard  0] init - Startup failed: exceptions::unavailable_exception (Cannot achieve consistency level for cl ALL. Requires 6, alive 5)
Sep 21 01:38:52 alternator-3h-5-2-db-node-f2926fb5-8 systemd[1]: scylla-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 21 01:38:52 alternator-3h-5-2-db-node-f2926fb5-8 systemd[1]: scylla-server.service: Failed with result 'exit-code'.
Sep 21 01:38:52 alternator-3h-5-2-db-node-f2926fb5-8 systemd[1]: scylla-server.service: Consumed 3min 34.089s CPU time.
```

So, we see that, for some reason, the bootstrapping node itself attempted to use `cl=ALL` and failed with the `init - Startup failed: exceptions::unavailable_exception (Cannot achieve consistency level for cl ALL. Requires 6, alive 5)` error.

## Impact

Spin up of a new node fails after the decommission of another node

## How frequently does it reproduce?

First time.

## Installation details

Kernel Version: 5.15.0-1045-aws
Scylla version (or git commit hash): `5.2.9-20230920.5709d0043978` with build-id `686601fd1656c6724f7f042163b9285bf3efd582`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-5-2-db-node-f2926fb5-8 (44.193.203.179 | 10.12.3.240) (shards: -1)
- alternator-3h-5-2-db-node-f2926fb5-7 (18.210.6.136 | 10.12.3.234) (shards: 14)
- alternator-3h-5-2-db-node-f2926fb5-6 (18.214.40.255 | 10.12.0.125) (shards: 14)
- alternator-3h-5-2-db-node-f2926fb5-5 (35.171.193.87 | 10.12.3.238) (shards: 14)
- alternator-3h-5-2-db-node-f2926fb5-4 (3.238.78.107 | 10.12.3.58) (shards: 14)
- alternator-3h-5-2-db-node-f2926fb5-3 (44.197.171.20 | 10.12.0.168) (shards: 14)
- alternator-3h-5-2-db-node-f2926fb5-2 (44.204.197.239 | 10.12.2.213) (shards: 14)
- alternator-3h-5-2-db-node-f2926fb5-1 (35.153.198.102 | 10.12.3.228) (shards: 14)

OS / Image: `ami-010134ae489d8bdf5` (aws: us-east-1)

Test: `longevity-alternator-3h-test`
Test id: `f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52`
Test name: `scylla-5.2/longevity/longevity-alternator-3h-test`
Test config file(s):

- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c8f2325262b40177f6c8d8133b3d741d80541c35/test-cases/longevity/longevity-alternator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52)
- Show all stored logs command: `$ hydra investigate show-logs f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52`

## Logs:
- **db-cluster-f2926fb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/db-cluster-f2926fb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/db-cluster-f2926fb5.tar.gz)
- **sct-runner-events-f2926fb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/sct-runner-events-f2926fb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/sct-runner-events-f2926fb5.tar.gz)
- **sct-f2926fb5.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/sct-f2926fb5.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/sct-f2926fb5.log.tar.gz)
- **monitor-set-f2926fb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/monitor-set-f2926fb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/monitor-set-f2926fb5.tar.gz)
- **loader-set-f2926fb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/loader-set-f2926fb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/loader-set-f2926fb5.tar.gz)
- **parallel-timelines-report-f2926fb5.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/parallel-timelines-report-f2926fb5.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52/20230921_023152/parallel-timelines-report-f2926fb5.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-alternator-3h-test/25/)
[Argus](https://argus.scylladb.com/test/3aaf2e4f-df54-49ef-bc55-47aeddd8a7da/runs?additionalRuns[]=f2926fb5-d5e6-4c70-b4d5-9e21a86dfa52)
</details>

**Comment by vponomaryov** [comment]
Previous runs of the same job were running with the same set of nemesis and were passing this step with following message set:
```
Sep 01 03:51:10 alternator-3h-5-2-db-node-e00bfa84-8 scylla[5464]:  [shard  0] cdc - Inserting new generation data at UUID 7913c86d-f19d-476a-9cd3-3a7d66b063fa
Sep 01 03:51:10 alternator-3h-5-2-db-node-e00bfa84-8 scylla[5464]:  [shard  0] cdc - New CDC generation: (2023/09/01 03:52:15, 7913c86d-f19d-476a-9cd3-3a7d66b063fa)
Sep 01 03:51:10 alternator-3h-5-2-db-node-e00bfa84-8 scylla[5464]:  [shard  0] storage_service - sleeping 30000 ms for pending range setup
Sep 01 03:51:10 alternator-3h-5-2-db-node-e00bfa84-8 scylla[5464]:  [shard  0] gossip - Waiting for pending range setup...
Sep 01 03:51:47 alternator-3h-5-2-db-node-e00bfa84-8 scylla[5464]:  [shard  0] gossip - No gossip backlog; proceeding
Sep 01 03:51:47 alternator-3h-5-2-db-node-e00bfa84-8 scylla[5464]:  [shard  0] storage_service - Starting to bootstrap...
Sep 01 03:51:48 alternator-3h-5-2-db-node-e00bfa84-8 scylla[5464]:  [shard  0] range_streamer - Bootstrap starts, nr_ranges_remaining=7466
```

## Installation details

Kernel Version: 5.15.0-1043-aws
Scylla version (or git commit hash): `5.2.8-20230831.455ab99b6cce` with build-id `a005ab4189e1368da1a31fac941696858b2dbc2e`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-5-2-db-node-e00bfa84-8 (54.237.172.9 | 10.12.0.147) (shards: 14)
- alternator-3h-5-2-db-node-e00bfa84-7 (3.218.207.0 | 10.12.2.175) (shards: 14)
- alternator-3h-5-2-db-node-e00bfa84-6 (34.200.216.64 | 10.12.2.26) (shards: 14)
- alternator-3h-5-2-db-node-e00bfa84-5 (34.201.14.211 | 10.12.3.110) (shards: 14)
- alternator-3h-5-2-db-node-e00bfa84-4 (18.232.168.76 | 10.12.2.195) (shards: 14)
- alternator-3h-5-2-db-node-e00bfa84-3 (3.231.203.131 | 10.12.0.148) (shards: 14)
- alternator-3h-5-2-db-node-e00bfa84-2 (3.238.221.6 | 10.12.3.214) (shards: 14)
- alternator-3h-5-2-db-node-e00bfa84-1 (3.235.87.227 | 10.12.1.52) (shards: 14)

OS / Image: `ami-0903e86428e7afeae` (aws: us-east-1)

Test: `longevity-alternator-3h-test`
Test id: `e00bfa84-9153-40c1-b86b-55a516365663`
Test name: `scylla-5.2/longevity/longevity-alternator-3h-test`
Test config file(s):

- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/950c559768f8993aaba998e1eafca9acbd9db555/test-cases/longevity/longevity-alternator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor e00bfa84-9153-40c1-b86b-55a516365663`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e00bfa84-9153-40c1-b86b-55a516365663)
- Show all stored logs command: `$ hydra investigate show-logs e00bfa84-9153-40c1-b86b-55a516365663`

## Logs:
- **db-cluster-e00bfa84.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/db-cluster-e00bfa84.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/db-cluster-e00bfa84.tar.gz)
- **sct-runner-events-e00bfa84.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/sct-runner-events-e00bfa84.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/sct-runner-events-e00bfa84.tar.gz)
- **sct-e00bfa84.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/sct-e00bfa84.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/sct-e00bfa84.log.tar.gz)
- **monitor-set-e00bfa84.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/monitor-set-e00bfa84.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/monitor-set-e00bfa84.tar.gz)
- **loader-set-e00bfa84.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/loader-set-e00bfa84.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/loader-set-e00bfa84.tar.gz)
- **parallel-timelines-report-e00bfa84.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/parallel-timelines-report-e00bfa84.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e00bfa84-9153-40c1-b86b-55a516365663/20230901_042544/parallel-timelines-report-e00bfa84.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/longevity/job/longevity-alternator-3h-test/24/)
[Argus](https://argus.scylladb.com/test/3aaf2e4f-df54-49ef-bc55-47aeddd8a7da/runs?additionalRuns[]=e00bfa84-9153-40c1-b86b-55a516365663)
</details>

**Comment by mykaul** [comment]
Just the timestamps here kinda makes me suspect this is racy:
```
2023-09-21 01:33:37,433 f:cluster.py      l:4657 c:sdcm.cluster         p:ERROR > Decommission for node Node alternator-3h-5-2-db-node-f2926fb5-2 [44.204.197.239 | 10.12.2.213] (seed: False) was aborted
2023-09-21 01:33:37,433 f:nemesis.py      l:3540 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Decommission aborted, Group0 was cleaned successfully. New node will be added
2023-09-21 01:33:37,433 f:nemesis.py      l:3548 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Decommission might complete before stopping it. Re-add a new node
2023-09-21 01:33:37,433 f:nemesis.py      l:1210 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Adding new node to cluster...
```

**Comment by mykaul** [comment]
Does this have to do with CDC or Alternator at all?
@kbr-scylla - sounds familiar ?

**Comment by kbr-scylla** [comment]
@vponomaryov please verify that this is not the same as https://github.com/scylladb/scylla-enterprise/issues/3412
i.e. race in SCT described by @aleksbykov in this comment:
https://github.com/scylladb/scylla-enterprise/issues/3412#issuecomment-1727455433

**Comment by vponomaryov** [comment]
@kbr-scylla Yes, it looks the same. Even the `cdc` part looks the same.
So, probably we can close it reffering to the @aleksbykov 's comment.
