### ISSUE TITLE
Scylla can crash when stopping reader concurrency semaphore

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#15534]
Scylla can crash due to a complicated interaction of service level drop, evictable readers, inactive read registration path.

1) service level drop invoke stop of reader concurrency semaphore, which will wait for in flight requests

2) turns out it stops first the gate used for closing readers that will become inactive

3) proceeds to wait for in-flight reads by closing the reader permit gate.

4) one of evictable reads take the inactive read registration path, and finds the gate for closing readers closed.

5) flat mutation reader is destroyed, but finds the underlying reader was not closed gracefully and triggers the abort.

**Comment by mykaul** [comment]
@bhalevy , @raphaelsc  - can you asses the risk/complexity to get it backported into 5.1 & 5.2?

**Comment by raphaelsc** [comment]
> @bhalevy , @raphaelsc - can you asses the risk/complexity to get it backported into 5.1 & 5.2?

the risk is very low, so I think we can backport it now. /cc @denesb

**Comment by denesb** [comment]
Backported to 5.2 and 5.1.
