### ISSUE TITLE
Cassandra-incompatible behavior of prepared statement with same-named bind markers

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#15559]
When a query like `SELECT * FROM {table1} WHERE p=:x AND c=:x'` has two bind markers **with the same name**, here `:x`, Cassandra behaves as follows when executing the prepared statement:

1. When a bound value is passed in the request **with a name** (CQL protocol flag 0x40), e.g., x=3, this value is assigned to both instances of `:x` in the request. EDIT: As explained below in a comment https://github.com/scylladb/scylladb/issues/15559#issuecomment-1737217073, the driver doesn't actually uses the protocol flag 0x40 in this case - it actually passes the server just the values.
2. When a bound value is passed in the request **without a name** (CQL protocol flag 0x01), e.g., 3, this value is assigned just to the first bind marker, and the second one remains unset. The user needs to pass two values, e.g., (3,3), to fill both bind markers. Even passing (3,4) works, and the two bind markers that had the same name get different values! This is not different from the case of a query which uses the bind marker "?" multiple times, and execute can bind each one a different value.

Today, Scylla behaves differently. Point 1 above is the same, but point 2 behaves differently: Passing just 3 will fill both bind markers ":x". Passing (3,3) is considered an error _"Too many arguments provided to bind() (got 2, expected 1)"_.

In pull request #15526, in the context of token calculation, @cvybhu declared Cassandra's behavior in this case a bug, and added a "scylla_only" tag (should have been "cassandra_bug"...) to two tests that were vulnerable to this incompatibility:
* `test_prepare.py`::`test_single_pk_indexes_duplicate_named_variables`
* `test_prepare.py`::`test_composite_pk_indexes_duplicate_named_variables`

The reason why I created this issue is to rethink this declaration, and perhaps consider Scylla's behavior - not Cassandra's - to be buggy. If we decide to leave the current Cassandra-incompatible behavior, we should document it.

Here is a test reproducing this issue, passing on Cassandra and failing (in multiple places) on Scylla:
```python
def test_duplicate_named_bind_marker_prepared(cql, table1):
    x = unique_key_int()
    cql.execute(f'INSERT INTO {table1} (p,c) VALUES ({x},{x})')
    cql.execute(f'INSERT INTO {table1} (p,c) VALUES ({x},{x+1})')
    stmt = cql.prepare(f'SELECT * FROM {table1} WHERE p=:x AND c=:x')
    # If EXECUTE is passed a bound value with a name "x", both bind markers
    # named "x" are assigned, and the query works:
    assert [(1,1)] == list(cql.execute(stmt, {'x': x}))
    # If EXECUTE is passed unnamed bound values, they go to the bind
    # markers no matter what their name is - using ":x" twice in the query
    # has the same effect as using "?" twice - you still need to pass two
    # bound values.
    # The following currently fails on Scylla - the driver complains that
    # "Too many arguments provided to bind() (got 2, expected 1)", because
    # Scylla told it there is just one bind variable in the query.
    assert [(1,1)] == list(cql.execute(stmt, (x,x)))
    # Passing one unnamed value sets just the first :x and leaves the
    # second one unset, resulting in an invalid query:
    with pytest.raises(InvalidRequest, match='Invalid unset value for column c'):
        assert [(1,1)] == list(cql.execute(stmt, (x,)))
    # Passing unnamed values one can pass two different values even if the
    # query's bind markers have the same name :x - exactly like two different
    # "?" can also be bound to different values:
    y = unique_key_int()
    cql.execute(f'INSERT INTO {table1} (p,c) VALUES ({y},{y+1})')
    assert [(y,y+1)] == list(cql.execute(stmt, (y,y+1)))
```

**Comment by cvybhu** [comment]
> @cvybhu declared Cassandra's behavior in this case a bug, and added a "scylla_only" tag (should have been "cassandra_bug"...)

It's not necessarily a bug, but it's a difference between the two.

I personally like Scylla's approach more - it makes sense that `:x` is a singe variable and it can only have a single value.
What does it mean when both `:x = 3` and `:x = 4` are true?

Most of the time when someone uses named bind variables they pass them as a map of `name -> value`, otherwise they would just use question marks. Passing a map works correctly with both approaches, it isn't that big of a problem.

> this value is assigned just to the first bind marker, and the second one remains unset.

Note that this is a quirk of the Python driver - when the user doesn't pass a value for a bind variable Python driver sends `unset` for this bind variable. Rust driver would complain about invalid number .

**Comment by cvybhu** [comment]
If this discrepancy is ever fixed, please remember to test that the drivers are able to handle rolling updates where some of the nodes require X bind variables, and the other require Y:
https://github.com/scylladb/scylla-rust-driver/issues/815

**Comment by nyh** [comment]
> It's not necessarily a bug, but it's a difference between the two.

Indeed - this is why I titled this issue "Cassandra-incompatible behavior" and gave it priority P4, and didn't say it was a serious bug.
 
> I personally like Scylla's approach more - it makes sense that `:x` is a singe variable and it can only have a single value. What does it mean when both `:x = 3` and `:x = 4` are true?

The same can be asked about the "?" bind marker :-) The thing is, as I explained above, if you set "x=3" in the execute statement, everything works as expected - both ":x" are assigned. Only if you use positional bind values, you need to set both x's separately. On one hand it's weird, on the other hand it's more consistent with how "?" works. 

> Most of the time when someone uses named bind variables they pass them as a map of `name -> value`, otherwise they would just use question marks. Passing a map works correctly with both approaches, it isn't that big of a problem.

I agree, but I hope it actually works correctly in the token calculation like in https://github.com/scylladb/scylladb/pull/15526. If the query has `where p1=:x and p2=:x` and one passes the named bound value `{'x': 3}` This value 3 needs to be used twice in the token calculation, and I don't know if we or Cassandra or both actually do this correctly.

If I understand correctly, we opened https://github.com/scylladb/scylladb/issues/15374 because an actual user used a duplicate-named bind marker. Did they use a map or a tuple when actually making the request? Note that your tests in PR https://github.com/scylladb/scylladb/pull/15526 only checked the prepare phase - not that the execute phase actually works and calculates the token correctly.

> It could only cause trouble when someone passes a list of bind values instead of a map.

Interestingly, the protocol documentation actually recommends to users **not** to pass names when EXECUTE-ting a prepared statement, because doing that it's a waste: from https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec

**for EXECUTE statements, since the names for the expected values was returned during preparation, a client can always provide values in the right order without any names and using this flag, while supported, is almost surely inefficient.**

It seems that the Python-driver authors didn't heed this recommendation - when the Python driver gets a bind value `{'x': 3}` it passes this to the server, with the name, instead of converting this into (3) or (3,3). I know this because in my test above `{'x':3}` worked on both Scylla and Cassandra, while the unnamed options each fails on a different system - so Python couldn't have converted the named option to an unnamed option.

> > this value is assigned just to the first bind marker, and the second one remains unset.
> 
> Note that this is a quirk of the Python driver - when the user doesn't pass a value for a bind variable Python driver sends `unset` for this bind variable. Rust driver would complain about invalid number .

I agree.

**Comment by nyh** [comment]
> Interestingly, the protocol documentation actually recommends to users **not** to pass names when EXECUTE-ting a prepared statement, because doing that it's a waste: from https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec
> 
> **for EXECUTE statements, since the names for the expected values was returned during preparation, a client can always provide values in the right order without any names and using this flag, while supported, is almost surely inefficient.**
> 
> It seems that the Python-driver authors didn't heed this recommendation - when the Python driver gets a bind value `{'x': 3}` it passes this to the server, with the name, instead of converting this into (3) or (3,3). I know this because in my test above `{'x':3}` worked on both Scylla and Cassandra, while the unnamed options each fails on a different system - so Python couldn't have converted the named option to an unnamed option.

I'm no longer sure my deduction about what Python does is correct - it's better to look at the actual code :-( According to https://github.com/scylladb/scylla-rust-driver/issues/815, Scylla recently changed how it reports which bind markers exist. It's possible that Python does convert the named value `{'x': 3}` to an unnamed `(3)` but it simply detects correctly that Scylla expects `(3)` instead of `(3,3)` and that Cassandra expects `(3,3)` and that's why it works on both.

**Comment by nyh** [comment]
> Note that this is a quirk of the Python driver - when the user doesn't pass a value for a bind variable Python driver sends `unset` for this bind variable. Rust driver would complain about invalid number of bind variables.

Turns out this was done deliberately in the Python driver - see https://datastax-oss.atlassian.net/jira/software/c/projects/PYTHON/issues/PYTHON-420 and https://github.com/datastax/python-driver/commit/0b8b37ba89930b08a8fb29a6a2f064656dedad6c. I'm not saying it's a good idea - just that they did it deliberately.

**Comment by nyh** [comment]
I just realized that this issue not only represents an incompatibility with Cassandra, it is also a change (some might say, regression) from earlier versions of Scylla. The cql-pytest test I wrote for this issue, `test_prepare.py::test_duplicate_named_bind_marker_prepared`, fails on modern Scylla, but passes on old Scylla such as 2022.1 (and on Cassandra).
It would be interesting to do a bisection to understand exactly when this change was introduced and why.

**Comment by avikivity** [comment]
We know why, it was to type-check bind variables that appeared in multiple places but inferred into different types.

**Comment by avikivity** [comment]
19a6e69001f26133a7f7a0a13e89935888884e1a  scylladb/scylladb#10810

**Comment by vladzcloudius** [comment]
> We know why, it was to type-check bind variables that appeared in multiple places but inferred into different types.

I see. This doesn't justify the change in the user-facing API however. We could (and should!) have continued to report all bound markers as they appear in the prepared statement. 

Instead of allowing ourselves an incompatibility with Cassandra we should have simply added a check on the EXECUTE path that a parameters that are bound to the same named marker have exactly the same value. Wouldn't it resolve the challenge, @avikivity?

**Comment by nyh** [comment]
Please note that although #19493 "Fixed" this issue and caused it to be closed, what that fix does is NOT to adopt Cassandra's behavior (which had also been Scylla's behavior a year earlier). Rather, it adds an option to switch to Cassandra's behavior. So the bad news is that Scylla is still incompatible with Cassandra (or its old self) in this area like this issue reported; But the good news that anybody bothered by this can fix it by setting an option.
