### ISSUE TITLE
Non-root `amazon2-arm` artifact installation fails with the `Failed to get D-Bus connection: No such file or directory` error running `systemctl --user stop scylla-server.service` command (5.2.9, ARM)

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#15557]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Running the non-root `artifacts-amazon2-arm-test` CI job we get following error:

```
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Command: 'systemctl --user stop scylla-server.service'
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Exit code: 1
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stdout:
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stderr:
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
15:28:18  < t:2023-09-26 12:28:17,887 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Failed to get D-Bus connection: No such file or directory
```

## Impact

Scylla service cannot be stopped gracefully.

## How frequently does it reproduce?

2/2

## Installation details

Cluster size: 1 nodes (im4gn.xlarge)

Scylla Nodes used in this run:
- artifacts-amazon2-jenkins-db-node-a39d3ed3-1 (34.255.11.11 | 10.4.0.138) (shards: 4)

OS / Image: `ami-06b4c3e5d2605128e` (aws: eu-west-1)

Test: `artifacts-amazon2-arm-test`
Test id: `a39d3ed3-19fb-4d9d-8299-e2684c156462`
Test name: `scylla-5.2/artifacts-offline-install/artifacts-amazon2-arm-test`
Test config file(s):

- [amazon2.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6614181596b9d518d64deb85f531a41946e0baff/test-cases/artifacts/amazon2.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a39d3ed3-19fb-4d9d-8299-e2684c156462`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a39d3ed3-19fb-4d9d-8299-e2684c156462)
- Show all stored logs command: `$ hydra investigate show-logs a39d3ed3-19fb-4d9d-8299-e2684c156462`

## Logs:
- **db-cluster-a39d3ed3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a39d3ed3-19fb-4d9d-8299-e2684c156462/20230926_122838/db-cluster-a39d3ed3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a39d3ed3-19fb-4d9d-8299-e2684c156462/20230926_122838/db-cluster-a39d3ed3.tar.gz)
- **sct-runner-events-a39d3ed3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a39d3ed3-19fb-4d9d-8299-e2684c156462/20230926_122838/sct-runner-events-a39d3ed3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a39d3ed3-19fb-4d9d-8299-e2684c156462/20230926_122838/sct-runner-events-a39d3ed3.tar.gz)
- **sct-a39d3ed3.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a39d3ed3-19fb-4d9d-8299-e2684c156462/20230926_122838/sct-a39d3ed3.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a39d3ed3-19fb-4d9d-8299-e2684c156462/20230926_122838/sct-a39d3ed3.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/artifacts-offline-install/job/artifacts-amazon2-arm-test/27/)
[Argus](https://argus.scylladb.com/test/0b494d39-57e5-4042-ad8f-def20e660fcf/runs?additionalRuns[]=a39d3ed3-19fb-4d9d-8299-e2684c156462)
</details>

**Comment by vponomaryov** [comment]
@syuu1228 ^

**Comment by vponomaryov** [comment]
Previous runs had `nonroot_offline_install=false` parameter.
New ones have `nonroot_offline_install=true`. So, in this case it fails as described in this bugreport.

**Comment by mykaul** [comment]
The YAML has:
```
scylla_repo: 'https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-3.3.repo'
```

Which is probably ignored/ wrong.

What's the OS? Scylla version?

**Comment by fruch** [comment]
@yaronkaikov 

I think this is part of the refactor of the triggering done in scylla-pkg
this job was never triggered with `nonroot_offline_install=true`,

I believe it was misplaced in the new layout, and since it not triggered on master, it wasn't notice until hitting the release branch.

**Comment by yaronkaikov** [comment]
> @yaronkaikov
> 
> I think this is part of the refactor of the triggering done in scylla-pkg this job was never triggered with `nonroot_offline_install=true`,
> 
> I believe it was misplaced in the new layout, and since it not triggered on master, it wasn't notice until hitting the release branch.

Amm, could be, will take a look

**Comment by vponomaryov** [comment]
> The YAML has:
> 
> ```
> scylla_repo: 'https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-3.3.repo'
> ```
> 
> Which is probably ignored/ wrong.
> 
> What's the OS? Scylla version?

```
unified_package: https://downloads.scylladb.com/unstable/scylla/branch-5.2/relocatable/2023-09-20T20:16:52Z/scylla-unified-5.2.9-0.20230920.5709d0043978.aarch64.tar.gz
```

**Comment by mykaul** [comment]
@vponomaryov - Operating System?

**Comment by fruch** [comment]
> @vponomaryov - Operating System?

Amazon Linux 2

**Comment by yaronkaikov** [comment]
My original patch solved the issue in master, but this code is new and we didn't backport it to our releases. Will send another patch to fix it directly on branch

**Comment by yaronkaikov** [comment]
Closes via https://github.com/yaronkaikov/scylla-pkg/commit/0b59456833955e566aa23c28218201a29604741d
