### ISSUE TITLE
error_injector: add api to resolve parameters at runtime

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#15571]
```
// todo: it would be much cleaner to allow the test to set the appropriate value:
// utils::get_local_injector().resolve("decrease_commitlog_base_segment_id")
if (utils::get_local_injector().enter("decrease_commitlog_base_segment_id")) {
   config.base_segment_id = 0;
}
```
It would be convenient to declare relevant parameters right in the test. The similar code is in hints manager, it should be updated too.

https://github.com/scylladb/scylladb/pull/15532#discussion_r1336962509:
> Most of the infrastructure is already there, you can do inject_with_handler and then get parameters from the injection_handler object, see e.g. in raft_group_registry.cc, injection inside gossiper_state_change_subscriber_proxy::on_alive there's auto second_node_ip = handler.get("second_node_ip").
> 
> Unfortunately inject_with_handler returns  future<>, but maybe we could have a variant that returns void.

**Comment by kbr-scylla** [comment]
Solved by `inject_parameter`
