### ISSUE TITLE
docs: Issue in page Backup your Data

### ISSUE THREAD

**Issue by anand-chandrashekar** [scylladb/scylladb#15573]
I would like to report an issue in page https://enterprise.docs.scylladb.com/branch-2023.1/operating-scylla/procedures/backup-restore/backup

### Problem
The documentation does not specify support of tools when tables are encrypted.

###  Suggest a fix
I assume that standard/encrypted/mix of encrypted and non-encrypted tables are supported. Please specify

**Comment by tzach** [comment]
Thanks for reporting.

SSTables are uploaded to backup storage (e.g. S3), which also goes for Encrypted SSTables. We need to clarify this in the docs and, in particular, explicitly mention one needs to keep the encryption key available for when they need to *restore* from backup.

Note EaR is an Enterprise-only feature.
