### ISSUE TITLE
Row cache updates do not provide strong exception safety guarantees

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15576]
The row_cache update path uses an `external_updater` class with two api functions: `prepare` and `execute`.
The current design calls for:
- `prepare` to create only temporary state, so if it fails, the failure is handled gracefully and the error is propagated to `row_cache::update` caller leaving no state changes behind (to the row cache nor to the updated table).
- `execute` role is to apply the temporary state `prepare` left behind.

Currently (as of 5.4-dev 652153c291c9b7b85dccc41ae55a6decd4ae6065), we let errors from `execute` escape `row_cache::update`, but there is no guarantee that the `execute` implementation provides strong exception safety gurantees, i.e. either succeed in whole or be exception safe leaving the state unchanged in case an exception is thrown.

See https://github.com/scylladb/scylladb/blob/6d34f9920262b6feb9be154a176d6a477f036dd0/row_cache.hh#L172-L182

See also https://github.com/scylladb/scylladb/pull/13937#issuecomment-1552869028

**Comment by bhalevy** [comment]
Backport should be applicable to all live versions

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport

**Comment by denesb** [comment]
There are conflicts, please provide backport PRs. Actually, a single PR against branch-5.4 should be enough, I can try to cherr-pick that backport to the older branches too.

**Comment by denesb** [comment]
The 5.4 backport PR was good for 5.2 but it doesn't apply to 5.1.

**Comment by denesb** [comment]
@bhalevy please provide a backport for enterprise, if needed.
