### ISSUE TITLE
Move all group 0 tables to schema commitlog (and prevent group 0 - updated tables using regular commitlog from being added)

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15596]
Any tables updated by group 0 commands should be in schema commitlog.

Currently we have:
```cpp
    const auto set_null_sharder = schema_builder::register_static_configurator([](const sstring& ks_name, const sstring& cf_name, schema_static_props& props) {
        // tables in the "system" keyspace which need to use null sharder
        static const std::unordered_set<sstring> tables = {
            schema_tables::SCYLLA_TABLE_SCHEMA_HISTORY,
            system_keyspace::BROADCAST_KV_STORE,
            system_keyspace::TOPOLOGY,
            system_keyspace::CDC_GENERATIONS_V3,
        };
        if (ks_name == system_keyspace::NAME && tables.contains(cf_name)) {
            props.use_null_sharder = true;
        }
    });
    const auto set_wait_for_sync_to_commitlog = schema_builder::register_static_configurator([](const sstring& ks_name, const sstring& cf_name, schema_static_props& props) {
        static const std::unordered_set<sstring> tables = {
            system_keyspace::PAXOS,
            system_keyspace::BROADCAST_KV_STORE,
            system_keyspace::TOPOLOGY,
            system_keyspace::CDC_GENERATIONS_V3,
        };
        if (ks_name == system_keyspace::NAME && tables.contains(cf_name)) {
            props.wait_for_sync_to_commitlog = true;
        }
    });
    const auto set_use_schema_commitlog = schema_builder::register_static_configurator([](const sstring& ks_name, const sstring& cf_name, schema_static_props& props) {
        static const std::unordered_set<sstring> tables = {
            system_keyspace::RAFT,
            system_keyspace::RAFT_SNAPSHOTS,
            system_keyspace::RAFT_SNAPSHOT_CONFIG,
            system_keyspace::GROUP0_HISTORY,
            system_keyspace::DISCOVERY,
            system_keyspace::TABLETS,
            system_keyspace::LOCAL,
            system_keyspace::PEERS,
            system_keyspace::SCYLLA_LOCAL,
            system_keyspace::v3::CDC_LOCAL
        };
        if (ks_name == system_keyspace::NAME && tables.contains(cf_name)) {
            props.enable_schema_commitlog();
        }
    });
```

so basically everything in `set_null_sharder` list should be moved to `set_use_schema_commitlog` and removed from `set_wait_for_sync_to_commitlog` (after these changes, `set_null_sharder` would be empty and `set_wait_for_sync_to_commitlog` would have only PAXOS).

In the future, if we add new group 0-managed tables, we need to make sure they are using schema commitlog. Perhaps some sanity check would be appropriate.

# Motivation (IIUC):

@raphaelsc explained on Slack that tablet resharding procedure needs to pick new owner shards on `smp::count` change for tablet-based tables before those tablets' sstables are loaded, so before non-system keyspace initialization step. So we need to read tablet metadata (`system_keyspace::TABLETS`) before non-system keyspace initialization. To correctly read tablet metadata, we need to replay group 0 commands, which first requires replaying commitlog for of tables that are updated by group 0 commands. We cannot replay regular commitlog before non-system keyspace initialization, but we can (and do) replay schema commitlog.

(One option would be to replay only a subset of regular commitlog, but then we'd have to go over these commitlog segments again after non-system keyspace initialization).

cc @tgrabiec @gleb-cloudius @gusev-p @kostja

**Comment by kbr-scylla** [comment]
@tgrabiec what's the deal with `schema_tables::SCYLLA_TABLE_SCHEMA_HISTORY`? From grepping the code, it looks like the table is only DELETEd from, so is it some legacy we're no longer depending on? In that case perhaps we should stop writing to it as part of schema changes? If not, we should probably also move it to schema commitlog (right now it's even working in periodic mode, which is not right for schema tables...)

**Comment by kbr-scylla** [comment]
Copying @tgrabiec 's answer from slack:

It's populated by `db::schema_tables::store_column_mapping()`. It's used to interpret paxos state, which may be using old `schema_ptr` versions no longer present in the schema registry. I think about it as an on-disk `schema_registry` with extended lifetime of entries.

**Comment by kostja** [comment]
@kbr-scylla is tehre anything that still needs to be done about it?
