### ISSUE TITLE
[debug, aarch64]:topology_raft_disabled.test_raft_upgrade_basic is Flaky

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#15605]
Seen during my debug sessions in
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_aarch64_debug/2/console

Failed 1 of 10 runs

**Comment by mykaul** [comment]
@yaronkaikov - have we seen it recently?

**Comment by yaronkaikov** [comment]
No, for the last 10 builds it passed 9 times (the only time it didn't pass because it didn't run). we can close this

**Comment by yaronkaikov** [comment]
![image](https://github.com/scylladb/scylladb/assets/9914527/0b6407a4-f7e2-43fe-8505-f06f8899f860)

**Comment by mykaul** [comment]
Closing until/if it reproduces.
