### ISSUE TITLE
tests failing due to timeout

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#15623]
In the past few days, we are seeing an increasing amount of tests failing due to timeout. The failing tests are not consistent, feels like they are somewhat random, the common theme being the failure due to a timeout.

Seen in:
* https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4063/
* https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4045/
* https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4059/
* And many more...

**Comment by fruch** [comment]
@denesb 
timeouts is quite vauge,

some are on CQL queries timeout

one looks like this:
```
failed on teardown with "AssertionError: Unexpected errors found: [('node4', ['ERROR 2023-10-03 19:55:48,330 [shard 0:main] init - Startup failed: streaming::stream_exception (Stream failed)'])]"
```

and one was timeout on boot of a node to be seen by others:
```
ccmlib.node.TimeoutError: watch_rest_for_alive() timeout after 120 seconds
```

each one is a bit different, and not necessary from the same root cause

**Comment by denesb** [comment]
The common theme is that scylla seems to be much slower, as if it was spinning on something and not responding.

**Comment by nyh** [comment]
> The common theme is that scylla seems to be much slower, as if it was spinning on something and not responding.

In the past we had several instances where tests suddenly became super slow, because of things like:
1. Uncontrolled parallelism (trying to run 100 tests in parallel) causing slow runs and worse - a lot of paging which makes super-slow runs.
2. VMs / machines with slow disks and running into IOPS limits.

At some point I added to test.py the ability to print the amount of time that successful tests took - and you can compare these times to older runs to see if there is a suspicious increase. But it's not fullproof either - it's always possible that the slowness is temporary and only affected a few tests, not the entire run.

**Comment by denesb** [comment]
Closing this, will open individual issues for each failure instead.

**Comment by fruch** [comment]
> > The common theme is that scylla seems to be much slower, as if it was spinning on something and not responding.
> 
> In the past we had several instances where tests suddenly became super slow, because of things like:
> 
> 1. Uncontrolled parallelism (trying to run 100 tests in parallel) causing slow runs and worse - a lot of paging which makes super-slow runs.
> 2. VMs / machines with slow disks and running into IOPS limits.
> 
> At some point I added to test.py the ability to print the amount of time that successful tests took - and you can compare these times to older runs to see if there is a suspicious increase. But it's not fullproof either - it's always possible that the slowness is temporary and only affected a few tests, not the entire run.

in dtest the pararalizim of test is based on the VM resources (i.e. number of cpus / amount of memory) and it's mostly 5 on the VM types we are using

also we are using VMs with local disks, and we are formatting them

in those cases we used mostly `g4ad.8xlarge` `c3.8xlarge` `c5ad.8xlarge`
