### ISSUE TITLE
row_cache::row_cache() isn't exception-safe

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#15632]
If the constructor of `row_cache` throws, `_partitions` is cleared in the wrong allocator, possibly causing allocator corruption.

The bug affects all existing releases, but is extremely hard to hit. Almost surely it never manifested and will never manifest in practice.

Refs https://github.com/scylladb/scylladb/pull/15614

**Comment by denesb** [comment]
Backported to 5.2.
