### ISSUE TITLE
Lack of thread safety in boost test logger can cause tests to fail

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#15654]
The logger is not thread safe, so a multithreaded unit test can concurrently write into the log, yielding unreadable XMLs.

Example:
`Recently, boost/sstable_directory_test: failed to parse XML output '/scylladir/testlog/x86_64/release/xml/boost.sstable_directory_test.sstable_directory_shared_sstables_reshard_correctly.3.xunit.xml': not well-formed (invalid token): line 1, column 1351`

It happened before in multi shard reader tests.

**Comment by avikivity** [comment]
Great turnaround time, let's try to keep this pace.

**Comment by nyh** [comment]
Seems like the second coming of #5654 :-(

**Comment by nyh** [comment]
Or rather https://github.com/scylladb/scylladb/issues/4774. I'm closing it too.

**Comment by denesb** [comment]
Test only fix, not backporting.
