### ISSUE TITLE
test_tablets fails in debug mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15666]
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6627/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_tablets_debug_2/

**Comment by avikivity** [comment]
Also seen in same run: [Tests / Unit Tests / test_tablets.test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode](https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6627/testReport/junit/(root)/test_tablets/Tests___Unit_Tests___test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode/). Probably the same thing.

**Comment by tgrabiec** [comment]
Duplicate of #14746
