### ISSUE TITLE
cloud_bundle_test.TestScyllaCloudBundle.test_connectivity_with_scylla_driver fails

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15662]
scylla-master/next failed on Sanity Tests stage, for more details: https://jenkins.scylladb.com/job/scylla-master/job/next/6624/
failed tests: 1 of 20846.
- cloud_bundle_test.TestScyllaCloudBundle.test_connectivity_with_scylla_driver
    failed on setup with "subprocess.CalledProcessError: Command '['/bin/bash', '-c', 'docker build /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.local/lib/python3.11/site-packages/ccmlib/utils/../resources/docker/sniproxy -t sniproxy']' returned non-zero exit status 1."
Full details on the Test Result page: https://jenkins.scylladb.com/job/scylla-master/job/next/6624/testReport/

**Comment by avikivity** [comment]
And why are we calling docker build inside a test?!

**Comment by fruch** [comment]
> And why are we calling docker build inside a test?!

cause there no formal docker images for this simple tool 

this is is what we are building:

```
FROM alpine

RUN apk --no-cache add sniproxy

EXPOSE 80 443
ENTRYPOINT ["sniproxy", "-f"]
```

regardless I've found out the the retry we introduce to avoid this DNS issue. was really retrying exceptions....
I'll send a fix to ccm soon

**Comment by nyh** [comment]
> > And why are we calling docker build inside a test?!
> 
> cause there no formal docker images for this simple tool

It appears that the "modern" version of https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering is "we can solve any problem by adding an extra level of docker" :-(

Is there really a reason why this "sniproxy", whatever it is (and if we really absolutely need it in the test and can't do the same in Python), can't be run on the same Linux systems that all the other tests run, and needs to run in some sort of Alpine Linux environment?

**Comment by fruch** [comment]
> > > And why are we calling docker build inside a test?!
> > 
> > 
> > cause there no formal docker images for this simple tool
> 
> It appears that the "modern" version of https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering is "we can solve any problem by adding an extra level of docker" :-(
> 
> Is there really a reason why this "sniproxy", whatever it is (and if we really absolutely need it in the test and can't do the same in Python), can't be run on the same Linux systems that all the other tests run, and needs to run in some sort of Alpine Linux environment?

we needed that for serverless effert, and cause it running on multiple enveriments, driver test and not only dtest
we prefered it on docker based, and not complicated the different envs more.

if you have spare time, you can attend to it and find better solutions.

**Comment by mykaul** [comment]
I somewhat disagree with the approach of building it instead of fetching an already built container. Makes very little sense to me.
We can publish it easily as part of a GH action. Work with the operator team if needed to get it done.

**Comment by fruch** [comment]
> I somewhat disagree with the approach of building it instead of fetching an already built container. Makes very little sense to me. We can publish it easily as part of a GH action. Work with the operator team if needed to get it done.

if we have DNS issue, like in this case, it would happen also with fetch.
building vs. fetch won't solve this one

**Comment by mykaul** [comment]
> > I somewhat disagree with the approach of building it instead of fetching an already built container. Makes very little sense to me. We can publish it easily as part of a GH action. Work with the operator team if needed to get it done.
> 
> if we have DNS issue, like in this case, it would happen also with fetch. building vs. fetch won't solve this one

Build is fetch - you fetch the base image layer(s).
We can keep that pre-built in the local container cache (which I'm afraid we are brutally cleaning every time), we could keep it in local distributed cache, etc. It should be a fixed version, more reliable to fetch than build, etc.
But we can defer moving to this.

(finally - fetch should be retried from multiple repos)

**Comment by fruch** [comment]
> > > I somewhat disagree with the approach of building it instead of fetching an already built container. Makes very little sense to me. We can publish it easily as part of a GH action. Work with the operator team if needed to get it done.
> > 
> > if we have DNS issue, like in this case, it would happen also with fetch. building vs. fetch won't solve this one
> 
> Build is fetch - you fetch the base image layer(s).
> We can keep that pre-built in the local container cache (which I'm afraid we are brutally cleaning every time), we could keep it in local distributed cache, etc. It should be a fixed version, more reliable to fetch than build, etc.
> But we can defer moving to this.
> 
> (finally - fetch should be retried from multiple repos)

Those tests are running on fresh machines, so no caches there.

The rest of the suggestions would need more defining and work then a comment on an issue
