### ISSUE TITLE
docs: Issue in page OS Support by Linux Distributions and Version --> need OS support for Scylla Manager (Server/Agent)

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylladb#15706]
I would like to report an issue in page https://enterprise.docs.scylladb.com/branch-2023.1/getting-started/os-support

### Problem
Scylla Manager 3.2 is not supported for Ubuntu 18.04 (our download doesn't have that option).
However there's no OS support matrix for Scylla Manager (Server/Agent) in our docs.

###  Suggest a fix
Please add it.

**Comment by tzach** [comment]
Good point.
@tomer-sandler please reopen in the manager project.
Its project should keep its own support matrix.

**Comment by tzach** [comment]
You already did
https://github.com/scylladb/scylla-manager/issues/3608
