### ISSUE TITLE
Bloom filter efficiency can be reduced after node operation (TWCS tables only?)

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#15704]
This problem is limited to tables using TWCS, as they segregate incoming data through streaming into windows they belong to. 

Streaming / repair based node operations will create 1 SSTable for each range at the receiver. A partition estimation is sent for each range, to help the receiver size bloom filter correctly for each SSTable.

If off-strategy is enabled, then data segregation is postponed, and therefore each SSTable should use the partition estimation as is. If disabled, data segregation is performed, meaning that each range will produce M SSTables instead, where M is the number of time windows. 

There are two problems:
1) If off-strategy is used, we're incorrectly downsizing the estimation as if the data for a single range was going to be segregated into M SSTables.
2) We're picking the worst-case M when dowsizing is performed, which is M=100. If table has 20 windows, so streaming writer is producing filters that are 5x smaller, therefore they yield higher false ratios.

Both problems will result in inefficient filters until all SSTables produced by streaming are rewritten. That's problematic, as suboptimal filters may increase latency significantly, and add to the fact that file count increases in the receiver after a node op like decommission.

**Comment by raphaelsc** [comment]
The first problem was caught by @bhalevy. The credit goes to him.

**Comment by mykaul** [comment]
This doesn't look like something new - why are we seeing this just now?

**Comment by bhalevy** [comment]
> This doesn't look like something new - why are we seeing this just now?

The problem was amplified in the field since the schema had no clustering column.
With TWCS we also deploy ck-based filtering following the bloom-filter based filtering, but it is impossible with the lack of a clustering key in the schema.

Also, the issue is self-healing / workaround-able by (major) compaction so it's possible we've hit but didn't notice in time.

**Comment by raphaelsc** [comment]
The fix I thought of is min(max_windows, ceil(default_ttl / window_size)). Alternatively extend rpc verb to pass mutation_metadata (min, max ts) for each range streamed, so partition adjustment can be done more precisely in the receiver. Also, must include the fix for other problem which incorrectly downsizes estimation when offstrategy is enabled. Long term is dynamic adjustment of filter on sstable write completion, but that's for later.

**Comment by mykaul** [comment]
@avikivity - it's unclear if it was backported or not?

**Comment by mykaul** [comment]
@raphaelsc - can you check the status of the backport efforts for this?

**Comment by bhalevy** [comment]
> @raphaelsc - can you check the status of the backport efforts for this?

ping @raphaelsc
