### ISSUE TITLE
Upload dir for cf is not created

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#15708]
Before 9c3e055d22b2aaeadc9108c9a2d8f1ae90f44059 the init_system_keyspace created cf directory and staging and upload subdirs in it. All three were done in "one go" inside table::init_storage(). After the patch the directories creation was moved to sstable_directory::filesystem_components_lister::prepare which is called for cf main directory and its staging and quarantine subdirs, but _not_ for the upload one, so the latter is no longer created

**Comment by mykaul** [comment]
(This was not caught via dtest/test.py but with end to end test with manager backup-restore)

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport to 5.4 ASAP because it causes many SCT tests to fail.

**Comment by denesb** [comment]
Backport queued, removing labels.
