### ISSUE TITLE
[dtest] Tests / Sanity Tests-RAFT / compaction_additional_test.TestTimeWindowDataSegregation.test_memtable_flush  is flakey

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15716]
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6666/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___Sanity_Tests_RAFT___test_memtable_flush/

```
FileNotFoundError: [Errno 2] No such file or directory: '/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-u5c1iqhe/test/node3/data/ks/test-fcf5bd606b6b11ee85fd46177bc4ff2a/me-3ga8_15u6_0c03k2ncazh7xy6gq8-big-Statistics.db'
```

```
self = <compaction_additional_test.TestTimeWindowDataSegregation object at 0x7f82f5ee7c90>

    def test_memtable_flush(self):
        '''
        Verify scylla does memtable flush into separate sstables when TWCS is used.
        Also verify each sstable span one window.
        '''
        [node1, node2, node3], session = self.prepare(3)
        self._create_ks_cl_with_twcs(session, rf=3)
    
        # Simulating 10 minutes of writes without flush
        self._simulate_write_process_in_minutes(session, duration_minutes=10, flush_period_seconds=999999999999)
        list_of_sstables_pre_flush = []
        list_of_sstables_post_flush = []
        for node in self.cluster.nodelist():
            list_of_sstables_pre_flush = self._get_list_of_sstables(node)
            node.flush()
            list_of_sstables_post_flush = self._get_list_of_sstables(node)
            post = len(list_of_sstables_post_flush)
            pre = len(list_of_sstables_pre_flush)
            assert post - pre > 1, f"Expected more than one sstable after flush, lengths are {post} {pre}, {node}"
            for sf in list_of_sstables_post_flush:
>               span_info = self._get_info_on_sstable_spanning_one_window(sf, self.window_size * 60)

compaction_additional_test.py:1909: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
compaction_additional_test.py:1422: in _get_info_on_sstable_spanning_one_window
    stats = self._get_stats(statistics_file)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <compaction_additional_test.TestTimeWindowDataSegregation object at 0x7f82f5ee7c90>
statistics_file = '/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-u5c1iqhe/test/node3/data/ks/test-fcf5bd606b6b11ee85fd46177bc4ff2a/me-3ga8_15u6_0c03k2ncazh7xy6gq8-big-Statistics.db'

    def _get_stats(self, statistics_file):
>       with open(statistics_file, 'rb') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.dtest/dtest-u5c1iqhe/test/node3/data/ks/test-fcf5bd606b6b11ee85fd46177bc4ff2a/me-3ga8_15u6_0c03k2ncazh7xy6gq8-big-Statistics.db'

compaction_additional_test.py:1410: FileNotFoundError
```

**Comment by fruch** [comment]
looks like yet another place we work with sstables on a live node that has compaction running, and we need to disable them

**Comment by fruch** [comment]
> > looks like yet another place we work with sstables on a live node that has compaction running, and we need to disable them
> 
> @fruch - who owns this?

no one, I'm not even sure who owns TWCS

**Comment by denesb** [comment]
@tchaikov another instance of sstable pulled from under the feet of scylla-sstable.

**Comment by tchaikov** [comment]
not scylla-sstable, but the sstable_tools python module. but yeah, i got you point..

**Comment by denesb** [comment]
> not scylla-sstable, but the sstable_tools python module. but yeah, i got you point..

Right. BTW, the `sstable_tools` python module is not required anymore, we should migrate all users to `scylla-sstable`. There probably just this one test, or a few others in the same file.

**Comment by tchaikov** [comment]
let me take care of this test failure -- push the "pause" button when trying to check the moving train.

**Comment by denesb** [comment]
I think the proper solution, like I already suggested elsewhere, is to have ccm pause compactions itself before it calls to scylla-sstable. Then migrate this test to scylla-sstable.

It is of course fine to apply a quick-fix here first.

**Comment by tchaikov** [comment]
> I think the proper solution, like I already suggested elsewhere, is to have ccm pause compactions itself before it calls to scylla-sstable. Then migrate this test to scylla-sstable.
> 
> It is of course fine to apply a quick-fix here first.

@denesb probably could create an issue against ccm and follow it up there? so we have a better venue for the discussion, and once we are on the same page, we can track the progress and divide and conquer the problem if it involves multiple steps.
