### ISSUE TITLE
test_repair_compacts_data: AssertionError: RX rows 4 is not as expected: 0

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15719]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/393/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/
```
self = <repair_additional_test.TestRepairAdditional object at 0x7f7594a7a8d0>

    def test_repair_compacts_data(self):
        cluster = self.cluster
        cluster.populate(2).start(wait_for_binary_proto=True, wait_other_notice=True)
        node1, node2 = cluster.nodelist()
    
        session = self.patient_cql_connection(node1)
        keyspace = 'ks'
        table = 'tbl'
        create_ks(session, keyspace, 2)
        session.execute(
            f"CREATE TABLE {keyspace}.{table} (pk int, ck int, v int, PRIMARY KEY (pk, ck)) WITH compaction = {{'class': 'NullCompactionStrategy'}}")
    
        def write_data_to_node1(pk):
            node2.stop(wait_other_notice=True)
    
            for ck in range(10):
                session.execute(f"INSERT INTO {keyspace}.{table} (pk, ck, v) VALUES ({pk}, {ck}, 0)")
    
            node1.flush()
    
            session.execute(f"DELETE FROM {keyspace}.{table} WHERE pk = {pk}")
    
            node1.flush()
    
            node2.start(wait_other_notice=True)
    
        write_data_to_node1(0)
    
        node1_base_metrics = get_node_metrics(node_ip=self.cluster.get_node_ip(1),
                                              metrics=self.LIST_ROW_LEVEL_REPAIR_METRICS)
        node1.repair([keyspace, table])
        self.verify_repair_tx_rx_rows(node_idx=1,
                                      # with compaction, a single row (the tombstone) is sent over
                                      expected_tx_row_nr=node1_base_metrics['tx_row_nr'] + 1,
                                      expected_rx_row_nr=node1_base_metrics['rx_row_nr'],
                                      list_metrics=self.LIST_ROW_LEVEL_REPAIR_METRICS)
    
        write_data_to_node1(1)
    
        # Disable compaction on repair
        session.execute("UPDATE system.config SET value = '0' WHERE name = 'enable_compacting_data_for_streaming_and_repair'")
    
        node1_base_metrics = get_node_metrics(node_ip=self.cluster.get_node_ip(1),
                                              metrics=self.LIST_ROW_LEVEL_REPAIR_METRICS)
        node1.repair([keyspace, table])
>       self.verify_repair_tx_rx_rows(node_idx=1,
                                      # without compaction, all rows are sent over
                                      expected_tx_row_nr=node1_base_metrics['tx_row_nr'] + 10,
                                      expected_rx_row_nr=node1_base_metrics['rx_row_nr'],
                                      list_metrics=self.LIST_ROW_LEVEL_REPAIR_METRICS)

repair_additional_test.py:3377: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <repair_additional_test.TestRepairAdditional object at 0x7f7594a7a8d0>
node_idx = 1, expected_tx_row_nr = 1038, expected_rx_row_nr = 0
list_metrics = ['tx_row_nr', 'rx_row_nr', 'tx_hashes_nr', 'rx_hashes_nr']

    def verify_repair_tx_rx_rows(self, node_idx, expected_tx_row_nr, expected_rx_row_nr, list_metrics):
        metrics_res = get_node_metrics(node_ip=self.cluster.get_node_ip(node_idx), metrics=list_metrics)
        for metric in list_metrics:
            if metric not in metrics_res:
                metrics_res[metric] = 'N/A'
        logger.debug("Check expected rx ({}) tx ({}) rows.".format(expected_rx_row_nr, expected_tx_row_nr))
        assert metrics_res['tx_row_nr'] <= expected_tx_row_nr, \
            "TX rows {} is not as expected: {}".format(metrics_res['tx_row_nr'], expected_tx_row_nr)
>       assert metrics_res['rx_row_nr'] <= expected_rx_row_nr, \
            "RX rows {} is not as expected: {}".format(metrics_res['rx_row_nr'], expected_rx_row_nr)
E       AssertionError: RX rows 4 is not as expected: 0
E       assert 4 <= 0

repair_additional_test.py:141: AssertionError

[REST API](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/393/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/api/)
```

https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/393/artifact/logs-full.release.001/1697167813848_repair_additional_test.py%3A%3ATestRepairAdditional%3A%3Atest_repair_compacts_data/node1.log
```
Scylla version 5.4.0~dev-0.20231013.055f0617064d with build-id 57852eb6963f846a9266e86c7fa57f3143e77dbf starting ...
...
INFO  2023-10-13 03:30:09,635 [shard 0:stre] repair - repair[6dbe3255-5424-4ecd-a2c9-1522633251ce]: stats: repair_reason=repair, keyspace=ks, tables={tbl}, ranges_nr=513, round_nr=516, round_nr_fast_path_already_synced=514, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=2, rpc_call_nr=2573, tx_hashes_nr=0, rx_hashes_nr=2, duration=0.33515224 seconds, tx_row_nr=1, rx_row_nr=4, tx_row_bytes=52, rx_row_bytes=592, row_from_disk_bytes={{127.0.30.1, 104}, {127.0.30.2, 644}}, row_from_disk_nr={{127.0.30.1, 2}, {127.0.30.2, 5}}, row_from_disk_bytes_per_sec={{127.0.30.1, 0.000295932}, {127.0.30.2, 0.0018325}} MiB/s, row_from_disk_rows_per_sec={{127.0.30.1, 5.96744}, {127.0.30.2, 14.9186}} Rows/s, tx_row_nr_peer={{127.0.30.2, 1}}, rx_row_nr_peer={{127.0.30.2, 4}}
```

**Comment by fruch** [comment]
it was spotted 12 times in the last 3 months:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/eb806430-6df1-11ee-bf28-5927cc3d3ce3

I run into it while running dtest on ARM...

**Comment by bhalevy** [comment]
Failed 2 times in a row in dtest-release since
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/453/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/
Scylla version 5.5.0~dev-0.20231225.3968fc11bf9c

**Comment by bhalevy** [comment]
@asias please take a look into this

**Comment by asias** [comment]
a. write_data_to_node1(0)
b. repair 1
c. write_data_to_node1(1)
d. repair 2

After c and before d, the hints could send the missed writes to node2. node1 runs compaction, rows covered by the writes are removed and only the tombstone is left. No compaction on node 2. In step d, repair runs,  node1 get rows from node2.

The test asserts. 

We saw erros like

run1: 

AssertionError: RX rows 4 is not as expected: 0

run2:
AssertionError: RX rows 10 is not as expected: 0

@denesb I saw you wrote this dtest.  The test looks fragile. 

1) We need to skip the check of rx rows.
2) Even if enable_compacting_data_for_streaming_and_repair is set to 10, compaction could still compact on node1 before repair, so that we see less than 10 rows to be sent to node2.

**Comment by denesb** [comment]
@asias shouldn't we just disable HH? Note that the test creates the table with `NullCompactionStrategy`, so the node won't compact anything.

**Comment by mykaul** [comment]
Also seen @ https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/467/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/

**Comment by bhalevy** [comment]
Suspected hit in https://jenkins.scylladb.com/job/scylla-5.4/job/dtest-release/13/testReport/junit/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/
```
AssertionError: RX rows 6 is not as expected: 0
```

Scylla version 5.4.2-0.20240117.6c625e8cd3c6

**Comment by Annamikhlin** [comment]
seen again in 
https://jenkins.scylladb.com/job/scylla-5.4/job/dtest-release/18/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/

`AssertionError: RX rows 10 is not as expected: 0`

Scylla version: 5.4.7-0.20240602.98139a8716ab

**Comment by mykaul** [comment]
> seen again in https://jenkins.scylladb.com/job/scylla-5.4/job/dtest-release/18/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/
> 
> `AssertionError: RX rows 10 is not as expected: 0`
> 
> Scylla version: 5.4.7-0.20240602.98139a8716ab

@Annamikhlin - please open a new issue. Commenting on a closed issue may not help (could be that https://github.com/scylladb/scylla-dtest/pull/3871 was not backport to 5.4 of course - just asked there to do so )

**Comment by Annamikhlin** [comment]
https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-release/22/testReport/junit/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/

failed with ERROR:
```
E       AssertionError: TX rows 1048 is not as expected: 1038
E       assert 1048 <= 1038
```
is the fix relevant? could it be backported to 2024.1?

**Comment by mykaul** [comment]
@Annamikhlin - following the trail a bit - this was supposed to be in 5.4 via https://github.com/scylladb/scylla-dtest/pull/4392 - so what did we miss? @tchaikov - any idea?

**Comment by fruch** [comment]
> @Annamikhlin - following the trail a bit - this was supposed to be in 5.4 via https://github.com/scylladb/scylla-dtest/pull/4392 - so what did we miss? @tchaikov - any idea?

My guess is that the issue isn't HH as suspected, at least not in 5.4/2024.1

**Comment by fruch** [comment]
> > @Annamikhlin - following the trail a bit - this was supposed to be in 5.4 via https://github.com/scylladb/scylla-dtest/pull/4392 - so what did we miss? @tchaikov - any idea?
> 
> My guess is that the issue isn't HH as suspected, at least not in 5.4/2024.1

Or the assumption the fix got to 2024.1 magically on its own

In dtest there no syncs from OSS to enterprise releases, so thing needs to be tagged as both, to get to matching enterprise release.

**Comment by tchaikov** [comment]
yeah, we need to add "backport/2024.1" so that a PR can be backported for the ent.

**Comment by mykaul** [comment]
That still fails on 2024.1.9/dtest-debug: https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-debug/37/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split005___test_repair_compacts_data/

**Comment by mykaul** [comment]
> That still fails on 2024.1.9/dtest-debug: https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-debug/37/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split005___test_repair_compacts_data/

And 2024.1.10/dtest-release - https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-release/28/testReport/repair_additional_test/TestRepairAdditional/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_repair_compacts_data/
