### ISSUE TITLE
docs: Issue in page ScyllaDB Materialized Views

### ISSUE THREAD

**Issue by pdbossman** [scylladb/scylladb#15725]
I would like to report an issue in page https://enterprise.docs.scylladb.com/branch-2023.1/using-scylla/materialized-views

### Problem
The docs point to a blog for current examples and limitations.  When I read the limitations, they are discussed in the context of the feature being an experimental feature.  But the 2023.1 docs lead with this:
"Materialized Views is available as a production ready feature in Scylla Open Source 3.0. and Scylla Enterprise 2019.1."

"For more examples and current constraints, read the original [blog](http://www.scylladb.com/2017/07/27/materialized-views-preview-scylla-2-0/) on materialized views in Scylla."

###  Suggest a fix

Revisit whatever limitations exist and we want to express to customers and explicitly document them in the docs and do not rely on a pointer to a pre-GA blog post as an accurate representation of current limitations.

**Comment by tzach** [comment]
Nice catch.
I think we should fix it first in open source.

**Comment by avikivity** [comment]
Minor documentation issue, not backporting
