### ISSUE TITLE
Make large_xxx thresholds liveUpdatable

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#15729]
*Installation details*
HEAD: 6dc885a8e246036ba0e0fa6e1ff73f6517a2c4f1

*Description*
large_xxx loggers are extremely useful when you want to track and catch some "rogue" data items. However having to restart the cluster in order to change corresponding thresholds is very unfortunate.

Let's make following configurable live-updatable:
* `compaction_rows_count_warning_threshold`
* `compaction_large_partition_warning_threshold_mb`
* `compaction_large_row_warning_threshold_mb`
* `compaction_large_cell_warning_threshold_mb`

**Comment by vladzcloudius** [comment]
cc @tarzanek

**Comment by vladzcloudius** [comment]
As far as I can tell it should as trivial as simply updating corresponding values in `large_data_handler` instances.

**Comment by michoecho** [comment]
They are already live-updateable. Or at least they are supposed to be. (Since https://github.com/scylladb/scylladb/commit/2c4ff71d2b1ceacc22dfbbec75be19369a672568).

**Comment by vladzcloudius** [comment]
You are right. I looked a wrong branch. Closing.
