### ISSUE TITLE
Inefficient filter due to misestimation of partitions per sstable, by accounting components other than Data

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#15726]
It was noticed that filter efficiency is suboptimal, even when TWCS is not involved, therefore https://github.com/scylladb/scylladb/issues/15704 as root cause was ruled out.

I took a sstable run in shard 0 for example:
```
[Run 656915984919103164513221980986343081219: size: 46.6GiB, partitions: 647770584 rows: ...
	{ me-01-big-Scylla.db: size: 1000.0MiB, fs: 7.0MiB, ps: 13573702, ... 
...
```

Wrote a quick tool that estimates the filter size (denoted as *fs* above) given the amount of partitions (denoted as *ps* above).

For 13573702 ps, fs should be ~17MiB, but instead we're seeing 7MiB (2.42x smaller). So the immediate thought is: we're downsizing partition estimation somewhere, which leads to suboptimal filters.

I proceeded to find the compaction that generate that sstable run above:
```
...,/var/lib/scylla/data/.../me-7504-big-Data.db:level=0]. 116GB to 116GB (~100% of original) in 9634483ms = 12MB/s. ~648313344 total partitions merged to 648310236.
```

see that the input and output are ~116GB in size, but the output above says the run is ~46.6G long.
compression related? no.
additional space amplification caused by index? yes. that's a problem in common with use cases that have a single-row small partitions. In this case, index is almost 1.5x bigger than the data file itself.

Found out that the partition estimation is using the input size (with index included) to estimate the amount of sstables compaction is going to generate, which is wrong as sstables are split according to the compressed data size.

Another way to think about it, is that more than half of the space designated for filters of output sstables was thrown out, meaning that each sstable generated by compaction will have significantly smaller filters, which in turn, results in more false positives.

If we divide # of partitions of that run by 116 (the size used which led to incorrect estimation), and feed that into the tool, we get exactly the 7MB, which is the size of filters today.

The solution, of course, is patching partition estimation to use input's data size (excluding index and other irrelevant components) instead.

**Comment by raphaelsc** [comment]
> @raphaelsc was this a regression?

No. But the benefit-risk ratio is high, so it was worth backporting.

**Comment by denesb** [comment]
Backported to 5.4. Doesn't apply cleanly to 5.2, @raphaelsc please open a backport PR.

**Comment by mykaul** [comment]
> Backported to 5.4. Doesn't apply cleanly to 5.2, @raphaelsc please open a backport PR.

@raphaelsc - ping

**Comment by mykaul** [comment]
@raphaelsc , @denesb - ping for backport.
