### ISSUE TITLE
raft topology: topology is updated through gossiper notifications

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15732]
For example, when I run `topology/test_replace.py` with `--logger-log-level storage_service=debug` the first node, which is also the topology coordinator, logs
```
INFO  2023-10-17 10:13:45,032 [shard 0:goss] gossip - InetAddress 127.97.166.2 is now UP, status = UNKNOWN
DEBUG 2023-10-17 10:13:45,033 [shard 0:goss] storage_service - endpoint=127.97.166.2 on_alive: permit_id=972edf8f-8e2f-4db9-b525-41577ca6dba0
```
before the second node joins the cluster.

In `storage_service::on_alive` we do `tmptr->update_topology(endpoint, get_dc_rack_for(endpoint));`, and as far as I know we should never update the topology through gossip notifications in the raft-based topology mode.

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius
