### ISSUE TITLE
raft topology: requests are routed too early to bootstrapping/replacing nodes

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#15738]
First observed in https://github.com/scylladb/scylladb/issues/15686 .

The new procedure for joining nodes used by consistent topology changes (https://github.com/scylladb/scylladb/pull/15196) assigns tokens to the bootstrapping or replacing node before it is asked to perform a read barrier. Because of that, other nodes might start sending write requests to it before it learns about the current schema of the cluster, leading to errors in the nodes' logs like:

```
[shard  1:stat] storage_proxy - Failed to apply mutation from 10.4.0.51#1: std::_Nested_exception<schema_version_loading_failed> (Failed to load schema version 824c9691-66c2-11ee-a38d-01af987a8afa): data_dictionary::no_such_keyspace (Can't find a keyspace keyspace1)
```

The tokens should be assigned later, only after `join_node_response` RPC completes (it asks the new node to perform a read barrier).

Ref: https://github.com/scylladb/scylladb/issues/15686#issuecomment-1755608750

**Comment by mykaul** [comment]
Raft topology is experimental, I assume no need for backport.
