### ISSUE TITLE
Repair-based node operations write SSTables with useless filters due to a bug

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#15748]
The repair writer, which creates new SSTables, incorrectly picked the default value for partition estimation, rather than using the one received. That causes those new SSTables to have useless filters that will potentially add to read amplification until they're rewritten in the off-strategy step. So this can manifest as temporary latency spikes, which can of course, degrade service temporarily.

**Comment by raphaelsc** [comment]
Closed by https://github.com/scylladb/scylladb/commit/4592bbe18207e9b25d485ba37103de9a35574a1d

**Comment by raphaelsc** [comment]
@asias please proceed with backport of https://github.com/scylladb/scylladb/commit/4592bbe18207e9b25d485ba37103de9a35574a1d to branches 5.2 and 5.1. It's an important fix.

**Comment by denesb** [comment]
Backport queued to 5.2 and 5.1.
