### ISSUE TITLE
warning: "Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)"

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15743]
This comes from perf_event_open in Seastar. We need to add CAP_PERFMON (linuix 5.8+) or CAP_SYS_ADMIN (older versions)

**Comment by mykaul** [comment]
CAP_SYS_ADMIN is a bit too powerful - I think we should use the former (and I'm not sure we should/need to support kernel versions lower than 5.8?)
