### ISSUE TITLE
raft topology: non-first joining node can be incorrectly handled as the first one

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15807]
In `join_node_request_handler`, if we placed a join request before the first node becomes normal, the topology coordinator would incorrectly skip the join node handshake in `handle_node_transition`. It would happen because the topology coordinator decides whether
a node is the first in the cluster by checking if there are no normal nodes:
```cpp
case node_state::none: {
    if (_topo_sm._topology.normal_nodes.empty()) {
        slogger.info("raft topology: skipping join node handshake for the first node in the cluster");
    } else {
        ...
```
Therefore, we must ensure at least one normal node when the topology coordinator handles a join request for a non-first node.

Currently, instead of looking at normal nodes in `join_node_request_handler`, we use `topology::is_empty`. It is incorrect, because `topology::is_empty()` may return false when the first node is still new or in transition.

This issue needs to be fixed to make concurrent bootstrap in the raft-based topology work. In concurrent bootstrap, calling `join_node_request_handler` before the first node becomes normal is a common occurrence.

**Comment by mykaul** [comment]
Raft topology is experimental, I assume no need for backport.
