### ISSUE TITLE
Raft topology fencing: transitioning nodes are not included when doing token metadata barrier, but they may be coordinating requests

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#15804]
HEAD: 031ff755ce8da9d3d75a6d975bfaee6594d4d642

Currently, the `topology_coordinator::global_tablet_token_metadata_barrier` method only talks with normal nodes: it first sends `barrier_and_drain` to let all the nodes observe the newest topology version in `system.topology` and wait for all current read/write requests; after all nodes complete, it sends `fence` request to all normal nodes to tell them to start rejecting requests with older topology versions than the current one.

This works fine if normal nodes are the only ones that coordinate requests - this is the case for bootstrap, replace, and node removal. However, in case of decommission operation, the decommissioned node might still be serving requests during the process. Because it doesn't receive the `barrier_and_drain` RPC, it might still try to send some requests with old topology version after normal nodes received `fence`. This can lead to requests being fenced and failing on the replica side, even though it should not happen in normal circumstances. For example, seen here: https://github.com/scylladb/scylladb/pull/15724#issuecomment-1767083968

**Comment by piodul** [comment]
cc: @tgrabiec @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> Update: `fence` RPC was replaced with barrier, as fence version is now part of topology state (`system.topology`). But the issue remains, I think.
> 
> cc @gleb-cloudius

Yes. The problem that we do not drain decommissioning node and this part of the barrier did not change.

**Comment by kbr-scylla** [comment]
IIUC not draining decommissioning node was catched in tests
https://github.com/scylladb/scylladb/issues/16642#issuecomment-1877825210
