### ISSUE TITLE
C-S failed with java.io.IOException: Operation x10 on key(s) once latest node from initial set was starting decommissioned

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#15803]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Test runs two operations: add new node, decommission random node. Cluster started from 3 nodes. Then on each iteration new node was added, and one random node decommissioned.  All operations went fine, while the latest node from initial cluster's nodes - node1 - was starting decommissioned, cassandra-stress terminated with errors:

```
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.3.0.133:9042 (com.datastax.driver.core.exceptions.ConnectionException: [/10.3.0.133:9042] Write attempt on defunct connection), ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.3.0.133:9042 (com.datastax.driver.core.exceptions.ConnectionException: [/10.3.0.133:9042] Write attempt on defunct connection), ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.3.0.133:9042 (com.datastax.driver.core.exceptions.ConnectionException: [/10.3.0.133:9042] Write attempt on defunct connection), ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
java.io.IOException: Operation x10 on key(s) [395038363034324c4b30]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.3.0.133:9042 (com.datastax.driver.core.exceptions.ConnectionException: [/10.3.0.133:9042] Write attempt on defunct connection), ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))

com.datastax.driver.core.exceptions.TransportException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Error writing
        at org.apache.cassandra.stress.Operation.error(Operation.java:141)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))
java.io.IOException: Operation x10 on key(s) [34354f324c3450503130]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (tried: /10.3.0.133:9042 (com.datastax.driver.core.exceptions.ConnectionException: [/10.3.0.133:9042] Write attempt on defunct connection))
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionException: [ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042] Write attempt on defunct connection))

com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: ip-10-3-1-72.eu-west-2.compute.internal/10.3.1.72:9042 (com.datastax.driver.core.exceptions.ConnectionExce
```

## Impact

c-s stress failed with errors and it is possible that data lost or not fully replicated during add/decommission nodes

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1047-aws
Scylla version (or git commit hash): `5.5.0~dev-20231019.7d5e22b43b64` with build-id `24849f2c8ab97292bd8df0296ccd5f09377a4899`

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-9 (18.170.62.230 | 10.3.2.241) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-8 (18.170.218.103 | 10.3.1.75) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-7 (13.40.153.68 | 10.3.1.186) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-6 (18.170.27.153 | 10.3.1.65) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-5 (35.178.94.184 | 10.3.1.61) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-4 (18.170.52.249 | 10.3.0.133) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-3 (18.169.166.197 | 10.3.3.150) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-2 (13.40.33.193 | 10.3.0.224) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-12 (18.133.156.234 | 10.3.0.157) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-11 (18.130.141.179 | 10.3.2.156) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-10 (3.10.234.235 | 10.3.0.170) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-72f3e4eb-1 (13.40.61.59 | 10.3.1.72) (shards: 2)

OS / Image: `ami-06121f5e49e3b30ed` (aws: undefined_region)

Test: `longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test`
Test id: `72f3e4eb-e301-442f-a039-ec47fc0b291c`
Test name: `scylla-master/nemesis/longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test`
Test config file(s):

- [longevity-5gb-1h-GrowShrinkClusterNemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d60806e7b31f0e9351674ba718a5cdac8df07b86/test-cases/nemesis/longevity-5gb-1h-GrowShrinkClusterNemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 72f3e4eb-e301-442f-a039-ec47fc0b291c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=72f3e4eb-e301-442f-a039-ec47fc0b291c)
- Show all stored logs command: `$ hydra investigate show-logs 72f3e4eb-e301-442f-a039-ec47fc0b291c`

## Logs:
- **db-cluster-72f3e4eb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/db-cluster-72f3e4eb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/db-cluster-72f3e4eb.tar.gz)
- **sct-runner-events-72f3e4eb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/sct-runner-events-72f3e4eb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/sct-runner-events-72f3e4eb.tar.gz)
- **sct-72f3e4eb.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/sct-72f3e4eb.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/sct-72f3e4eb.log.tar.gz)
- **loader-set-72f3e4eb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/loader-set-72f3e4eb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/loader-set-72f3e4eb.tar.gz)
- **monitor-set-72f3e4eb.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/monitor-set-72f3e4eb.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/72f3e4eb-e301-442f-a039-ec47fc0b291c/20231022_063520/monitor-set-72f3e4eb.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/nemesis/job/longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test/59/)
[Argus](https://argus.scylladb.com/test/24e3a5d3-9092-4adf-a0a6-24210e792e45/runs?additionalRuns[]=72f3e4eb-e301-442f-a039-ec47fc0b291c)
</details>

**Comment by aleksbykov** [comment]
@mykaul , nothing critical or suspicious

**Comment by aleksbykov** [comment]
Branch: reproduce-15803
Job: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/abykov/job/nemesis-clone/job/longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test/

Test runs with on_demand:
1. decommission initial nodes starting from first in cluster - Issue was not reproduced
2. decommission initial nodes started from last (in initial set) - In progress

**Comment by fruch** [comment]
Happened again this week:

## Installation details

Kernel Version: 5.15.0-1049-aws
Scylla version (or git commit hash): `5.5.0~dev-20231108.a4aeef2eb0aa` with build-id `6c90f896983cf138cd171d49f9d406876333f910`





Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-9 (3.70.170.59 | 10.11.3.248) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-8 (18.184.237.252 | 10.11.3.217) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-7 (3.71.111.159 | 10.11.1.157) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-6 (18.185.100.59 | 10.11.0.163) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-5 (3.70.168.96 | 10.11.1.148) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-4 (3.72.36.106 | 10.11.3.240) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-3 (18.153.92.254 | 10.11.1.102) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-2 (18.184.121.34 | 10.11.3.171) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-11 (3.66.171.93 | 10.11.0.132) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-10 (3.70.100.168 | 10.11.3.227) (shards: 2)
- longevity-5gb-1h-GrowShrinkClusterN-db-node-9472bb49-1 (3.79.114.109 | 10.11.0.135) (shards: 2)


OS / Image: `ami-01d97e93413dd612b` (aws: undefined_region)

Test: `longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test`
Test id: `9472bb49-baf1-4ab8-beab-c1e1bd847abd`
Test name: `scylla-master/nemesis/longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test`
Test config file(s):

- [longevity-5gb-1h-GrowShrinkClusterNemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f6ce1209c6304330f85ffd16f12942c84db7d0d/test-cases/nemesis/longevity-5gb-1h-GrowShrinkClusterNemesis.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 9472bb49-baf1-4ab8-beab-c1e1bd847abd`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9472bb49-baf1-4ab8-beab-c1e1bd847abd)
- Show all stored logs command: `$ hydra investigate show-logs 9472bb49-baf1-4ab8-beab-c1e1bd847abd`


## Logs:
- **db-cluster-9472bb49.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/db-cluster-9472bb49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/db-cluster-9472bb49.tar.gz)
- **sct-runner-events-9472bb49.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/sct-runner-events-9472bb49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/sct-runner-events-9472bb49.tar.gz)
- **sct-9472bb49.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/sct-9472bb49.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/sct-9472bb49.log.tar.gz)
- **loader-set-9472bb49.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/loader-set-9472bb49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/loader-set-9472bb49.tar.gz)
- **monitor-set-9472bb49.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/monitor-set-9472bb49.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9472bb49-baf1-4ab8-beab-c1e1bd847abd/20231111_060722/monitor-set-9472bb49.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/nemesis/job/longevity-5gb-1h-GrowShrinkClusterNemesis-aws-test/79/)
[Argus](https://argus.scylladb.com/test/24e3a5d3-9092-4adf-a0a6-24210e792e45/runs?additionalRuns[]=9472bb49-baf1-4ab8-beab-c1e1bd847abd)
</details>

**Comment by fruch** [comment]
from a quick looks of it, it's smells like driver issue to me.

I can clearly see that one of the two c-s threads, is not being updated with the new nodes, and start complaining 
```
java.io.IOException: Operation x10 on key(s) [314e4d31323535313031]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (no host was tried)
```

driver should be reading the local and peer table, and update itself with all of the available nodes,
and for some reason the java-driver on those runs, keep trying to connect to nodes that already LEFT

@aleksbykov from what you wrote it's not clear, did you manage to reproduce the issue or not ?
it's reproducible in some way, I would recommend running with `cs_debug: true`, and moving it to java-driver

**Comment by aleksbykov** [comment]
@fruch , i reproduced only one time.I rerun the job with flag you provided

**Comment by aleksbykov** [comment]
Waiting job results

**Comment by roydahan** [comment]
> from a quick looks of it, it's smells like driver issue to me.
> 
> I can clearly see that one of the two c-s threads, is not being updated with the new nodes, and start complaining
> 
> ```
> java.io.IOException: Operation x10 on key(s) [314e4d31323535313031]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (no host was tried)
> ```
> 
> driver should be reading the local and peer table, and update itself with all of the available nodes, and for some reason the java-driver on those runs, keep trying to connect to nodes that already LEFT
> 
> @aleksbykov from what you wrote it's not clear, did you manage to reproduce the issue or not ? it's reproducible in some way, I would recommend running with `cs_debug: true`, and moving it to java-driver

@fruch could it be that we replaced the entire cluster and something is "fixed" in c-s to use an old node that was provided in "-host" parameter?
(@Mark-Gurevich do you see such a behavior for replacing an entire cluster testing?)

**Comment by fruch** [comment]
> > from a quick looks of it, it's smells like driver issue to me.
> > I can clearly see that one of the two c-s threads, is not being updated with the new nodes, and start complaining
> > ```
> > java.io.IOException: Operation x10 on key(s) [314e4d31323535313031]: Error executing: (NoHostAvailableException): All host(s) tried for query failed (no host was tried)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > driver should be reading the local and peer table, and update itself with all of the available nodes, and for some reason the java-driver on those runs, keep trying to connect to nodes that already LEFT
> > @aleksbykov from what you wrote it's not clear, did you manage to reproduce the issue or not ? it's reproducible in some way, I would recommend running with `cs_debug: true`, and moving it to java-driver
> 
> @fruch could it be that we replaced the entire cluster and something is "fixed" in c-s to use an old node that was provided in "-host" parameter? (@Mark-Gurevich do you see such a behavior for replacing an entire cluster testing?)

this is a nice guess, but we haven't seen it before. and while one stress command is failing like that, the other one that does the exactly same thing, doesn't fail like that.

**Comment by aleksbykov** [comment]
Issue was not reproduced with any scenario:
 - decommission node from begining
 - decommission node from the end of initial list
 - one from the begining on from the end

Because that issue was not reproduced, the cs_debug doesn't show any specific info

**Comment by aleksbykov** [comment]
@fruch , Issue was not reproduced for several runs in row. May be we can add the parameter `cs_debug: true` regular job? 
So when it fail again with this error we already have cs debug messages. WDYT?

**Comment by fruch** [comment]
> @fruch , Issue was not reproduced for several runs in row. May be we can add the parameter `cs_debug: true` regular job? 
> So when it fail again with this error we already have cs debug messages. WDYT?

Yes, we can add it by default for this case.

But it might also mask the issue, if it's some timing issue

**Comment by fruch** [comment]
Regardless I suggest moving this issue to the java driver, or opening a reference issue there.

All current findings point to it

**Comment by aleksbykov** [comment]
@fruch , done, should this issue be closed or will keep for a while?

**Comment by mykaul** [comment]
> Regardless I suggest moving this issue to the java driver, or opening a reference issue there.
> 
> All current findings point to it

I can easily move (I think) but I think it'd be best if you can open a clean bug describing the issue.

**Comment by aleksbykov** [comment]
Opened issue for java-driver: https://github.com/scylladb/java-driver/issues/259

**Comment by Mark-Gurevich** [comment]
> @fruch could it be that we replaced the entire cluster and something is "fixed" in c-s to use an old node that was provided in "-host" parameter? (@Mark-Gurevich do you see such a behavior for replacing an entire cluster testing?)

I haven't seen this happen, but I didn't run the replacement many times in SCT yet, so probably we will see this in the future.
