### ISSUE TITLE
Overloading scylla with materialized view writes can lead to deadlock

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#15844]
Observed effect is that view update backlog grows and doesn't clear even after write load stops. We encountered it when table had 5 materialized views, potentially with hot partitions.

**Comment by mykaul** [comment]
@avikivity - can you prioritize backporting this? I think it's an important fix.

**Comment by avikivity** [comment]
Backported to 5.1, 5.2, 5.4.
