### ISSUE TITLE
Make Raft (to be precise: schema changes based on group 0) mandatory

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15854]
We didn't do it for 5.4, but we might want to do it for the next release (so update `master` right now)?

@mykaul @kostja @avikivity @tzach @scylladb/raft

**Comment by kbr-scylla** [comment]
(for 5.4, Raft is enabled by default during upgrade: https://github.com/scylladb/scylladb/issues/13980)

**Comment by mykaul** [comment]
Makes sense.

**Comment by avikivity** [comment]
It's also sensible that we didn't enable it for 5.4, need to give people time to adjust.

**Comment by patjed41** [comment]
I reopened. This issue is not fixed. It got incorrectly closed because of a "fix issue_number" in the PR description.
