### ISSUE TITLE
raft topology: don't register topology-on-raft RPCs in non-topology-on-raft mode

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#15862]
Sub-task of https://github.com/scylladb/scylladb/issues/15555, followup to https://github.com/scylladb/scylladb/pull/15196#discussion_r1338149933.

If topology on raft mode is disabled, there is no use in registering RPCs that are exclusive to that mode. We should adjust the code in `storage_service` not to do that and make sure that the existing code does not accidentally try to send those RPCs when raft mode is disabled.

**Comment by kbr-scylla** [comment]
> make sure that the existing code does not accidentally try to send those RPCs when raft mode is disabled.

In fact, that would be dangerous if we release a version that sends those RPCs out. We then wouldn't be able to modify these RPCs in backward-incompatible way before going out of experimental mode!

We should be quick here and backport to 5.4 if necessary

**Comment by kbr-scylla** [comment]
Queued backport to 5.4
