### ISSUE TITLE
artifacts-debian10-arm-test fails - failure to install deps - repo configuration?

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#15878]
Probably a  repo misconfiguration : 
```
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Command: 'sudo apt-get install -y openjdk-11-jre-headless xfsprogs mdadm'
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > 
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Exit code: 100
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > 
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Stdout:
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > 
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > done.
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Processing triggers for sgml-base (1.29) ...
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Setting up libfontconfig1:arm64 (2.13.1-2) ...
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Processing triggers for mime-support (3.62) ...
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Processing triggers for libc-bin (2.28-10) ...
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Processing triggers for initramfs-tools (0.133+deb10u1) ...
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > update-initramfs: Generating /boot/initrd.img-4.19.0-18-arm64
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Errors were encountered while processing:
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING >  ca-certificates-java
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING >  openjdk-11-jre-headless:arm64
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > 
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > Stderr:
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > 
< t:2023-10-29 20:22:58,227 f:tester.py       l:593  c:ArtifactsTest        p:WARNING > E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by mykaul** [comment]
https://jenkins.scylladb.com/job/scylla-5.4/job/artifacts/job/artifacts-ubuntu2004-arm-test/3/consoleFull
https://jenkins.scylladb.com/job/scylla-5.4/job/artifacts-offline-install/job/artifacts-debian10-arm-test/5/

**Comment by yaronkaikov** [comment]
Since this is SCT code, @fgelcer who should take it?

**Comment by mykaul** [comment]
I wonder if we need to run 'sudo apt update' before.

**Comment by fruch** [comment]
> Similar issue for ubuntu2004-arm:
> 
> ```
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Command: 'sudo apt-get install -y lsof net-tools'
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Exit code: 100
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stdout:
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Reading package lists...
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Building dependency tree...
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Reading state information...
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Package net-tools is not available, but is referred to by another package.
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > This may mean that the package is missing, has been obsoleted, or
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > is only available from another source
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > Stderr:
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 
> 11:25:45  < t:2023-10-30 09:25:45,088 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > E: Package 'net-tools' has no installation candidate
> ```

this is not a similar issue to the issue report at the description

one is missing package and one is some configuring a package

**Comment by fruch** [comment]
the issue with installing java, seem very similar to 
https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/2019908

I think maybe installing `ca-certificates-java` first might solve the issue

**Comment by soyacz** [comment]
> one is missing package and one is some configuring a package

net-tools is required for `netstat` and is not crucial for most of the tests (only for collecting some diagnostic data), we could try-catch it and ignore error. We could move to `ss` from `iproute2` which is now more recommended.

**Comment by fruch** [comment]
my recommendation is to update the base image for those tests, we are hitting all kind of old bugs related to arm64 of those distros, and not like in GCE where we get the latest images, here they were hard coded long ago.

**Comment by mykaul** [comment]
> my recommendation is to update the base image for those tests, we are hitting all kind of old bugs related to arm64 of those distros, and not like in GCE where we get the latest images, here they were hard coded long ago.

I wonder how it all passed on master.

**Comment by fruch** [comment]
> > my recommendation is to update the base image for those tests, we are hitting all kind of old bugs related to arm64 of those distros, and not like in GCE where we get the latest images, here they were hard coded long ago.
> 
> I wonder how it all passed on master.

might I remind you the the arm64 workflow wasn't really getting to that point that often.
(also and I need to check it, maybe not all of those jobs are defined in master, and defined only for releases)

**Comment by mykaul** [comment]
> might I remind you the the arm64 workflow wasn't really getting to that point that often.

Once should have been enough to catch it?

**Comment by fruch** [comment]
> > > my recommendation is to update the base image for those tests, we are hitting all kind of old bugs related to arm64 of those distros, and not like in GCE where we get the latest images, here they were hard coded long ago.
> > 
> > 
> > I wonder how it all passed on master.
> 
> might I remind you the the arm64 workflow wasn't really getting to that point that often. (also and I need to check it, maybe not all of those jobs are defined in master, and defined only for releases)

both of those jobs are in tier2, and should be part of master and releases:
```
    aarch64:
      artifacts/artifacts-debian10-arm-test: [master, enterprise, oss-release, ent-release]
      artifacts/artifacts-ubuntu2004-arm-test: [master, enterprise, oss-release, ent-release]
```

and it least one of the issues here was seen on master:
https://argus.scylladb.com/test/5e32e21a-c00e-4ec3-b7cf-f13a3974217a/runs?additionalRuns[]=76fa11aa-9a6c-4547-be9a-22413a282cff
but not reported

**Comment by fruch** [comment]
Anyhow the base image we are using are from 2021, we should update them to avoid any issue related to package installation that might have been fixed since then (we should consider how to make it automatic, to some degree)
