### ISSUE TITLE
`--date-stamp` is ignored by SCYLLA-VERSION-GEN

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15894]
the argument passed to this option has been ignored since 839d8f40e6d0a3ba85a488fa4afa6031d1380b18.

we are using this option to override the default version number created using `date --utc +%Y%m%d`, so that we can create builds with the same version number even if these two builds are launched in two days.

**Comment by denesb** [comment]
Minor cleanup, not backporting.
