### ISSUE TITLE
test_add_many_nodes_under_load is flaky: wrong value

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15906]
Seen, for example, in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release-with-raft/297/testReport/update_cluster_layout_tests/TestLargeScaleCluster/Run_Dtest_Parallel_Cloud_Machines___LongDtest___long_split000___test_add_many_nodes_under_load/
```
self = <update_cluster_layout_tests.TestLargeScaleCluster object at 0x7f18bc1ed9d0>

    @pytest.mark.timeout(4200)
    def test_add_many_nodes_under_load(self):
        """
        Test large scale cluster (50 nodes cluster, or 12 in debug mode).
        Cluster starts with a starting_size=3 and grow to node_count=50 during a c-s write in the background (low load)
        and c-s read after adding all nodes to make sure all data was written successfully.
        In addition, while adding each node inserting 100 keys and verifying that all keys were written.
        E.Result: All nodes were added and c-s read successfully read all keys
        """
    
        cluster = self.cluster
        debug_mode = isinstance(cluster, ScyllaCluster) and cluster.scylla_mode == "debug"
        node_count = 40 if not debug_mode else 10
        starting_size = 3
        rf = 3
    
        nodes_str = f'up to {node_count}' if debug_mode else f'{node_count}'
        logger.info(f"Test adding {nodes_str} nodes under load: starting_size={starting_size} rf={rf}")
    
        timeout = self.cql_timeout(120)
    
        # Disable hinted handoff and set batch commit log so this doesn't
        # interfere with the test (this must be after the populate)
        config_options = {
            'hinted_handoff_enabled': False,
            'enable_sstable_key_validation': True,
            'range_request_timeout_in_ms': timeout * 1000,
        }
        cluster.set_configuration_options(
            values=config_options, batch_commitlog=True)
        cluster.populate(starting_size).start()
        sessions = dict()
        for n in cluster.nodelist():
            sessions[n] = self.patient_exclusive_cql_connection(n)
        node1 = cluster.nodelist()[0]
        session = self.patient_cql_connection(node1)
        create_ks(session, 'ks', rf)
        create_cf(session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})
        create_cf(session, 'test', columns={'val': 'int'})
    
        keys = 0
        max_keys = 1000000000 if not debug_mode else 60000
        stress_done = False
        add_nodes_done = False
        test_keys = 10000
        values = {}
        for i in range(test_keys):
            values[i] = None
    
        def run():
            nonlocal cluster, sessions, keys, max_keys, stress_done, add_nodes_done, values
            # each iteration just writes a small batch
            # so we check add_nodes_done in a reasonable frequently
            n = 1000
    
            logger.debug(f"Stress: starting to write up to {max_keys} keys in batches of {n}")
            while keys < max_keys and not add_nodes_done:
                node = random.choice(list(sessions.keys()))
                session = sessions[node]
                logger.debug(f"Stress: writing keys {keys}..{keys + n} using {node.name}")
                for k in random.choices(range(test_keys), k=n):
                    v = (values[k] or random.randint(0, 1000000)) + 1
                    session.execute(f"INSERT INTO ks.test (key, val) VALUES ('key{k}', {v})")
                    values[k] = v
                keys += n
            logger.debug(f"Stress: wrote {keys} keys: add_nodes_done={add_nodes_done}")
            stress_done = True
    
        executor = ThreadPoolExecutor(max_workers=node_count)
        t = executor.submit(run)
    
        consistency = ConsistencyLevel.ALL
        logger.debug("just before first insert")
        insert_c1c2(session, keys=range(starting_size * 100 + 1000), consistency=ConsistencyLevel.ONE)
    
        query = SimpleStatement("SELECT key FROM ks.cf", fetch_size=100, consistency_level=consistency)
        logger.debug(f"Starting to add nodes {starting_size + 1} to {node_count + 1}")
        for i in range(starting_size + 1, node_count + 1):
            node_i = new_node(cluster)
            node_i.start(wait_for_binary_proto=True, wait_other_notice=True)
            sessions[node_i] = self.patient_exclusive_cql_connection(node_i)
            sessions[node_i].execute("use ks;")
            insert_c1c2(sessions[node_i], keys=range(100000 + i * 2000,
                        100000 + i * 2000 + 100), consistency=consistency)
            logger.debug("added %s" % node_i.name)
    
            result = list(session.execute(query, timeout=timeout))
            assert len(result) == i * 100 + 1000, "data loss after increasing size to %d expecting %d rows %d" % \
                (len(cluster.nodelist()), i * 100 + 1000, len(result))
    
            if stress_done:
                break
        logger.debug(f"Done adding nodes: stress_done={stress_done}")
        add_nodes_done = True
    
        t.result()
    
        logger.debug("Cleanup on all nodes: starting")
        cleanup_futures = []
        for n in cluster.nodelist():
            cleanup_futures.append(executor.submit(n.cleanup))
        for t in cleanup_futures:
            t.result()
        logger.debug("Cleanup on all nodes: done")
    
        n = keys
        logger.debug(f"Stress: read {n} keys: starting")
        for k in range(test_keys):
            res = list(session.execute(f"SELECT val FROM ks.test WHERE key = 'key{k}'"))
            if values[k] is not None:
                assert len(res) == 1
>               assert res[0].val == values[k]
E               assert 282486 == 282487
E                +  where 282486 = Row(val=282486).val

update_cluster_layout_tests.py:2947: AssertionError
```

**Comment by bhalevy** [comment]
I think this might be due to flaky consistency level combination (ONE/ONE).
I'll submit a patch to use QUERY/QUERY in the dtest.

**Comment by mykaul** [comment]
> I think this might be due to flaky consistency level combination (ONE/ONE). I'll submit a patch to use QUORUM/QUORUM in the dtest.

That was my initial thought. @roydahan - perhaps we should do a more thorough review of tests that use CL ONE? I assume in very specific cases it may be required, but otherwise - not so sure.

**Comment by bhalevy** [comment]
> > I think this might be due to flaky consistency level combination (ONE/ONE). I'll submit a patch to use QUORUM/QUORUM in the dtest.
> 
> That was my initial thought. @roydahan - perhaps we should do a more thorough review of tests that use CL ONE? I assume in very specific cases it may be required, but otherwise - not so sure.

I think that's a good idea.
It's a shame the python driver Session defaults to ConsistencyLevel.LOCAL_ONE

**Comment by mykaul** [comment]
> > > I think this might be due to flaky consistency level combination (ONE/ONE). I'll submit a patch to use QUORUM/QUORUM in the dtest.
> > 
> > 
> > That was my initial thought. @roydahan - perhaps we should do a more thorough review of tests that use CL ONE? I assume in very specific cases it may be required, but otherwise - not so sure.
> 
> I think that's a good idea. It's a shame the python driver Session defaults to ConsistencyLevel.LOCAL_ONE

A decision made in 2015... Change from 'ONE' ... Perhaps it's not the right default anymore.

**Comment by bhalevy** [comment]
> > > > I think this might be due to flaky consistency level combination (ONE/ONE). I'll submit a patch to use QUORUM/QUORUM in the dtest.
> > > 
> > > 
> > > That was my initial thought. @roydahan - perhaps we should do a more thorough review of tests that use CL ONE? I assume in very specific cases it may be required, but otherwise - not so sure.
> > 
> > 
> > I think that's a good idea. It's a shame the python driver Session defaults to ConsistencyLevel.LOCAL_ONE
> 
> A decision made in 2015... Change from 'ONE' ... Perhaps it's not the right default anymore.

I check the Python driver version 3.11 and it still is.
See https://github.com/scylladb/python-driver/blob/64e7fad42ec88dfc72c7f12c389c3ef6c3f392fb/cassandra/cluster.py#L2460
and
https://github.com/scylladb/python-driver/blob/64e7fad42ec88dfc72c7f12c389c3ef6c3f392fb/cassandra/cluster.py#L323

But we can set it to QUORUM or LOCAL_QUORUM for the dtest default ExecutionProfile

**Comment by roydahan** [comment]
I don't understand what does it mean flakey consistency level ONE.
In many places we specifically use CL=ONE to make sure there is no data loss in even one of the nodes (when we do not expect it).
I don't know if it's the case here, need to drill down to the test which was significantly changed since I wrote it.

**Comment by bhalevy** [comment]
> I don't understand what does it mean flakey consistency level ONE. In many places we specifically use CL=ONE to make sure there is no data loss in even one of the nodes (when we do not expect it). I don't know if it's the case here, need to drill down to the test which has significantly changed since I wrote it.

With RF=3 and CL!=ALL insert may succeed on less than 3 replicas, and then if SELECT uses CL=ONE, it may read one of the outdated replicas, therefore the read is flaky, because it depends on which read returned first.  The basic "stable" CL combinations for write/read are: QUORUM/QUORUM, ALL/ONE, or ONE/ALL.

**Comment by roydahan** [comment]
right, and usually I prefer in tests that doesn't include any planned disruption to the cluster, to use ALL for write and ONE for read.

**Comment by mykaul** [comment]
> right, and usually I prefer in tests that doesn't include any planned disruption to the cluster, to use ALL for write and ONE for read.

I assume most customer workloads would prefer local quorum?

**Comment by roydahan** [comment]
It's not related to what customers prefer.
ONE is more sensitive so it can help detecting issues of data loss that may be masked by QUORUM (either due to not picking the lost replica or due to read repair).

**Comment by bhalevy** [comment]
> ONE is more sensitive so it can help detecting issues of data loss that may be masked by QUORUM (either due to not picking the lost replica

What do you mean by "not picking the lost replica"?
cl=ONE returns the read result once the first replica returns data for the query, if there was a lost writes cl=ONE will not detect it.

> or due to read repair).

`ONE` will indeed verify the latest copy after `ALL`, but I'm not sure how realistic it is.
We must have unit tests for consistency levels but system tests must cover the most common consistency levels used by customers - and if the most common is `LOCAL_QUORUM` for both writes and reads than this should be the main focus.
In addition, some tests should also cover other consistency levels like `{LOCAL_,}ONE/ALL` and `ALL/{LOCAL_,}ONE`

Related to that, we must test in SCT multi-DC / multi-RACK setups, whether in different availability zones or not (maybe we can use multiple vpcs to simulate that?) - since this is the most common configuration in the field.
I'm mentioning that in relation to using LOCAL_QUORUM vs. just QUORUM consistency level...

**Comment by roydahan** [comment]
> > ONE is more sensitive so it can help detecting issues of data loss that may be masked by QUORUM (either due to not picking the lost replica
> 
> What do you mean by "not picking the lost replica"? cl=ONE returns the read result once the first replica returns data for the query, if there was a lost writes cl=ONE will not detect it.
> 

I mean that if for example we had a data loss in one of the nodes, reading with ONE has the statistics potential to detect it while QUORUM will NOT (due to read repair).

> > or due to read repair).
> 
> `ONE` will indeed verify the latest copy after `ALL`, but I'm not sure how realistic it is. We must have unit tests for consistency levels but system tests must cover the most common consistency levels used by customers - and if the most common is `LOCAL_QUORUM` for both writes and reads than this should be the main focus. In addition, some tests should also cover other consistency levels like `{LOCAL_,}ONE/ALL` and `ALL/{LOCAL_,}ONE`
> 

It's not related to consistency testing, it's just a way to use the consistency to detect potential issues while testing.
In an ideal world, we would have an API to read all data from all replicas outside of the regular data path and this was your basic data validation.

> Related to that, we must test in SCT multi-DC / multi-RACK setups, whether in different availability zones or not (maybe we can use multiple vpcs to simulate that?) - since this is the most common configuration in the field. I'm mentioning that in relation to using LOCAL_QUORUM vs. just QUORUM consistency level...
