### ISSUE TITLE
Write timeout correlated with replace operation in `test_topology_ops`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15924]
[scylla-1180.log](https://github.com/scylladb/scylladb/files/13238765/scylla-1180.log)
[scylla-1199.log](https://github.com/scylladb/scylladb/files/13238766/scylla-1199.log)
[scylla-1206.log](https://github.com/scylladb/scylladb/files/13238767/scylla-1206.log)
[scylla-1229.log](https://github.com/scylladb/scylladb/files/13238768/scylla-1229.log)
[topology_experimental_raft.test_topology_ops.2.log](https://github.com/scylladb/scylladb/files/13238769/topology_experimental_raft.test_topology_ops.2.log)

```python3
    async def test_topology_ops(request, manager: ManagerClient):
        """Test basic topology operations using the topology coordinator."""
        logger.info("Bootstrapping first node")
        servers = [await manager.server_add()]
    
        logger.info(f"Restarting node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
        await manager.server_start(servers[0].server_id)
    
        await wait_for_cql_and_get_hosts(manager.cql, await manager.running_servers(), time.time() + 60)
        cql = await reconnect_driver(manager)
        finish_writes = await start_writes(cql)
    
        logger.info("Bootstrapping other nodes")
        servers += [await manager.server_add(), await manager.server_add()]
    
        logger.info(f"Restarting node {servers[0]} when other nodes have bootstrapped")
        await manager.server_stop_gracefully(servers[0].server_id)
        await manager.server_start(servers[0].server_id)
    
        logger.info(f"Stopping node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
        await check_node_log_for_failed_mutations(manager, servers[0])
    
        logger.info(f"Replacing node {servers[0]}")
        replace_cfg = ReplaceConfig(replaced_id = servers[0].server_id, reuse_ip_addr = False, use_host_id = False)
        servers = servers[1:] + [await manager.server_add(replace_cfg)]
        await check_token_ring_and_group0_consistency(manager)
    
        logger.info(f"Stopping node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
        await check_node_log_for_failed_mutations(manager, servers[0])
    
        logger.info(f"Removing node {servers[0]} using {servers[1]}")
        await manager.remove_node(servers[1].server_id, servers[0].server_id)
        await check_token_ring_and_group0_consistency(manager)
        servers = servers[1:]
    
        logger.info(f"Decommissioning node {servers[0]}")
        await manager.decommission_node(servers[0].server_id)
        await check_token_ring_and_group0_consistency(manager)
    
        logger.info("Checking results of the background writes")
>       await finish_writes()
```

```
>               await cql.run_async(stmt)
E               cassandra.OperationTimedOut: errors={'127.176.134.12:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.176.134.12:9042
```

```
12:11:54.580 ERROR> Write started 200.0350980758667s ago failed: errors={'127.176.134.12:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.176.134.12:9042
12:11:54.580 ERROR> Write started 200.0350465774536s ago failed: errors={'127.176.134.12:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.176.134.12:9042
12:11:54.580 ERROR> Write started 200.03473258018494s ago failed: errors={'127.176.134.12:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.176.134.12:9042
```

Writes coordinated by `127.176.134.12` (`scylla-1206`) timed out at `12:11:54.580`, they started 200.03s earlier, so at around `12:08:34:550`.

Here's what was happening around this time:
```
12:08:34.033 INFO> Replacing node Server(1180, 127.176.134.9)
```

scylla-1180 (`127.176.134.9`) was being replaced by scylla-1229 (`127.176.134.65`):
```
INFO  2023-11-02 12:08:34,813 [shard 0:strm] raft_group0 - Replacing a node with Raft ID: 745cf93d-51cb-4e3c-b5cc-cf7143dcecb1, IP address: 127.176.134.9
```
(from scylla-1229's logs)

So the write that timed out, started around the same time the replace operation started. Hence I think they might be related.
On the other hand, the replacing node started only at around `12:08:34,664`, so if my calculations are correct -- after the write started being coordinated...

The write was coordinated by the same node which was the topology coordinator. Dunno if it's related. I don't know what the reason of write timeout was.

Another interesting observation is that the replace operation hanged for around 4.5m. Logs from replacing node:
```
INFO  2023-11-02 12:08:36,520 [shard 0:strm] token_metadata - Added node 127.176.134.65 as pending replacing endpoint which replaces existing node 127.176.134.9
INFO  2023-11-02 12:08:36,555 [shard 0:strm] token_metadata - Added node 127.176.134.65 as pending replacing endpoint which replaces existing node 127.176.134.9
INFO  2023-11-02 12:08:36,573 [shard 0:main] raft_group_registry - marking Raft server e9e4d0aa-630e-4bf0-ab8b-9197808c2ef9 as alive for raft groups
INFO  2023-11-02 12:13:34,560 [shard 0: gms] storage_service - entering BOOTSTRAP mode
INFO  2023-11-02 12:13:34,560 [shard 0: gms] storage_service - raft topology: start streaming
```
notice the time gap between timestamps.

From looking at the code, the replacing node was most likely waiting for a command from the coordinator to proceed.

Coordinator logs during this time:
```
INFO  2023-11-02 12:08:36,514 [shard 0:strm] token_metadata - Added node 127.176.134.65 as pending replacing endpoint which replaces existing node 127.176.134.9
INFO  2023-11-02 12:08:36,516 [shard 0:strm] load_balancer - Examining DC datacenter1
INFO  2023-11-02 12:08:36,516 [shard 0:strm] load_balancer - Node 745cf93d-51cb-4e3c-b5cc-cf7143dcecb1: rack=rack1 avg_load=0, tablets=0, shards=2, state=normal
INFO  2023-11-02 12:08:36,516 [shard 0:strm] load_balancer - Node e9e4d0aa-630e-4bf0-ab8b-9197808c2ef9: rack=rack1 avg_load=0, tablets=0, shards=2, state=normal
INFO  2023-11-02 12:08:36,516 [shard 0:strm] load_balancer - Node ea47dca1-a84b-48ea-b0ad-7a5f1d8ef82e: rack=rack1 avg_load=0, tablets=0, shards=2, state=normal
INFO  2023-11-02 12:08:36,516 [shard 0:strm] load_balancer - Prepared 0 migrations in DC datacenter1
INFO  2023-11-02 12:08:36,516 [shard 0:strm] load_balancer - Prepared 0 migrations
INFO  2023-11-02 12:08:36,519 [shard 0:strm] token_metadata - Added node 127.176.134.65 as pending replacing endpoint which replaces existing node 127.176.134.9
WARN  2023-11-02 12:08:36,738 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:36,738 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:38,738 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:40,739 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:42,739 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:44,740 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:46,740 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:48,741 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:50,741 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:52,742 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:54,742 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:56,742 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:58,743 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2023-11-02 12:08:58,743 [shard 1:strm] gossip - failure_detector_loop: Mark node 127.176.134.9 as DOWN
INFO  2023-11-02 12:08:58,743 [shard 0:strm] gossip - InetAddress 127.176.134.9 is now DOWN, status = NORMAL
INFO  2023-11-02 12:13:34,546 [shard 0:strm] raft_group0 - making server 745cf93d-51cb-4e3c-b5cc-cf7143dcecb1 a non-voter...
INFO  2023-11-02 12:13:34,547 [shard 0:strm] raft_group0 - server 745cf93d-51cb-4e3c-b5cc-cf7143dcecb1 is now a non-voter.
INFO  2023-11-02 12:13:34,743 [shard 0:strm] token_metadata - Added node 127.176.134.65 as pending replacing endpoint which replaces existing node 127.176.134.9
INFO  2023-11-02 12:13:34,748 [shard 0:strm] storage_service - raft topology: removing node 745cf93d-51cb-4e3c-b5cc-cf7143dcecb1 from group 0 configuration...
INFO  2023-11-02 12:13:34,748 [shard 0:strm] storage_service - raft topology: node 745cf93d-51cb-4e3c-b5cc-cf7143dcecb1 removed from group 0 configuration
```

from the code, it either hanged on global_token_metadata_barrier in write_both_read_old stage, or in tablet draining stage.

I don't know if this topology coordinator hang is related to the client write timeout.

cc @tgrabiec @gleb-cloudius

**Comment by kbr-scylla** [comment]
Note: doesn't reproduce locally, I ran the test around 500 times.
The failure was in dev mode x86.

**Comment by kbr-scylla** [comment]
Also this:
```
WARN  2023-11-02 12:08:36,738 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:36,738 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:38,738 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:40,739 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:42,739 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:44,740 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:46,740 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:48,741 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:50,741 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:52,742 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:54,742 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:56,742 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2023-11-02 12:08:58,743 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.176.134.9, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2023-11-02 12:08:58,743 [shard 1:strm] gossip - failure_detector_loop: Mark node 127.176.134.9 as DOWN
INFO  2023-11-02 12:08:58,743 [shard 0:strm] gossip - InetAddress 127.176.134.9 is now DOWN, status = NORMAL
```

shows that there's something wrong with graceful shutdown. Other nodes should be immediately informed by the node that's shutting down about going down.
Maybe there's a bug with doing graceful shutdown in Raft topology mode.

**Comment by denesb** [comment]
Seen again in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4499/ (https://github.com/scylladb/scylladb/pull/15932). From a quick look it seems to be the same issue.

**Comment by tgrabiec** [comment]
> shows that there's something wrong with graceful shutdown. Other nodes should be immediately informed by the node that's shutting down about going down. Maybe there's a bug with doing graceful shutdown in Raft topology mode.

This is https://github.com/scylladb/scylladb/issues/15356

**Comment by tgrabiec** [comment]
Maybe it's somehow related to disconnects which I saw in https://github.com/scylladb/scylladb/issues/14746#issuecomment-1767332009

**Comment by tgrabiec** [comment]
> Another interesting observation is that the replace operation hanged for around 4.5m. Logs from replacing node:

It makes sense that the barrier will hang, because write requests on coordinator side hold to erm until the timeout, and the server-side timeout is 300s (`'write_request_timeout_in_ms': 300000,` = 5 min).

**Comment by tgrabiec** [comment]
Looking at the test code, those writes are Cl=1 RF=3, so it's strange they time-out on the client side if only 1 node is down.

**Comment by kbr-scylla** [comment]
1 node is down but replace is in progress, which IIUC increases CL by 1 for the moving token ranges.

**Comment by tgrabiec** [comment]
> 1 node is down but replace is in progress, which IIUC increases CL by 1 for the moving token ranges.

Still, that gives CL=2, so one replica should ACK the write.

**Comment by gleb-cloudius** [comment]
But we wait for all writes in the background for 'write_request_timeout_in_ms' and it probably hold for erm as well.

**Comment by tgrabiec** [comment]
> But we wait for all writes in the background for 'write_request_timeout_in_ms' and it probably hold for erm as well.

Yes, that would explain the topology coordinator delay, but not request failures.

**Comment by denesb** [comment]
Seen again in:
[topology_experimental_raft.test_topology_ops.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4504/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_topology_ops_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_topology_ops.dev.2)
    [topology_experimental_raft.test_topology_ops.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4504/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_topology_ops_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_topology_ops.dev.3)

**Comment by kbr-scylla** [comment]
Perhaps it's caused by https://github.com/scylladb/scylladb/issues/17429

**Comment by patjed41** [comment]
Investigated.

The first problem in the test is that `server_stop_gracefully` is unreliable. Sometimes, other nodes don't receive the DOWN notification. This problem is addressed by #17276. `test_tpology_ops` can fail only if some node doesn't receive the notification about the replaced node shutting down.

The second problem is that in tests Scylla uses higher write request timeout than the driver. Scylla uses 300 s, the driver uses 200 s.

The scenario when the test fails is as as follows:
- the node being replaced shuts down,
- some other node doesn't receive the DOWN notification; from this moment all client writes coordinated by this node become background writes that wait for a response from the shut down node (there are 2 alive nodes and writes use RF=3, CL=1),
- one of the writes hangs in `cql_server::connection::process_request` on `get_units(_server._memory_available, mem_estimate)` because the background writes have used up all available memory (there can be thousands of background writes since the test continuously sends writes),
- the first background write times out almost 5 minutes later, it returns the semaphore units, and the hanged write wakes up, but the driver has already timed out.

Moreover, even though this test has the failure frequency around 1/1000 in CI, it quite often passes in around 345 s instead of the normal 45 s. If the write coordinator doesn't run out of memory before it notices the replaced node shutting down, and there are some background writes, the test passes, but `barrier_and_drain` takes 5 min since it waits for background writes.

To ensure the test is not flaky, we should change the timeouts, so that Scylla times out before the driver. This change should be generally good, not only for this test.

Also, these timeouts are much too high for the vast majority of cases. They are so high only because of some extreme cases in aarch64/debug: https://github.com/scylladb/scylladb/issues/11289#issuecomment-1242153028. In the release and dev modes, they could be much lower. This would speed up tests that get stuck on 5 min `barrier_and_drain` (for example, see #17429). Changing the server timeout alone could also be good enough (changing the driver timeout in some modes may be harder to implement).

**Comment by mykaul** [comment]
@patjed41 - do we need a separate issue to track the reduced timeout (if running in !debug mode) so we can track this request?

**Comment by patjed41** [comment]
> @patjed41 - do we need a separate issue to track the reduced timeout (if running in !debug mode) so we can track this request?

No, we don't. I'll include this change for the server timeout in the fix for this issue. I must touch this timeout anyway and making its value dependent on the mode is simple.

After discussing it with @kbr-scylla, we decided to leave the client timeout unchanged. Reducing it in some modes requires too much effort for almost no improvement.
