### ISSUE TITLE
Some tests in test/cql-pytest/test_permissions.py fail on Cassandra

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#15969]
Some tests in `test/cql-pytest/test_permissions.py` fail on Cassandra (I used Cassandra 4.1.1), i.e., the command
```
test/cql-pytest/run-cassandra test_permissions.py
```

Two tests fail:

1. `test_drop_udf_with_same_name` fails in line 216, trying to use a body1 `"(i int) CALLED ON NULL INPUT RETURNS bigint LANGUAGE java AS 'return 42;'"` says: `Java source compilation failed: Line 1: Type mismatch: cannot convert from int to Long`. I guess Java when used in UDF can't promote integer types. How did this ever work before?

2. `test_grant_perms_on_nonexistent_udf` fails in line 321, saying "cassandra.protocol.ConfigurationException Keyspace ks doesn't exist". The error message is expected, but the test expects InvalidRequest instead of ConfugrationException. The test should probably be changed to allow both - this is unfortunately a common difference between Scylla and Cassandra and we usually just allow both in affected tests.

**Comment by nyh** [comment]
Unfortunately, fixing the above errors reveals the next two errors:
1. In `test_drop_udf_with_same_name`, trying to drop an overloaded function without explicit parameters is expected to yield an error, rather than attempting to drop one of them (and failing on "Unauthorized" method because of lack of permissions). Apparently this doesn't happen in Casandra, which seems to try to drop one of the functions of the same name, and fail on Unauthorized. We should consider this should be considered a cassandra_bug,  a bug in Scylla which should be reported, or a difference that should be excused by accepting either InvalidRequest or Unauthorized.
2. In `test_grant_perms_on_nonexistent_udf`, we try `RANT EXECUTE ON FUNCTION ks.fun42(int) TO cql_test_1699286053351` when neither "ks" nor "fun42" exist. Scylla reasonably throws InvalidRequest, Cassandra throws a SyntaxException saying "NoSuchElementException No value present" which doesn't make sense. I think this is a cassandra_bug.

**Comment by nyh** [comment]
I sent a pull request to fix this. **No backports will be needed** - the fixes are only relevant when running the tests against Cassandra, something we don't do in CI, and don't do on old branches.

**Comment by mykaul** [comment]
> I sent a pull request to fix this. **No backports will be needed** - the fixes are only relevant when running the tests against Cassandra, something we don't do in CI, and don't do on old branches.

I think we do test against Cassandra with our Python driver test matrix (still doesn't mean we'll need backports though? unsure).

**Comment by nyh** [comment]
> I think we do test against Cassandra with our Python driver test matrix (still doesn't mean we'll need backports though? unsure).

Thisissue  is about a scylla.git test (in test/cql-pytest), not a Python-driver test.
These may have some (fairly small) overlaps, but are not the same. The functionality that a Python driver test should cover is very different from what Scylla's test covers - in this case, we test "DROP FUNCTION ..." on various error paths (missing keyspace, missing function, missing argument types, etc.) because we want to check them in Scylla, but as far as the Python driver is concerned, they are all just a request passed as text to the server.

**Comment by denesb** [comment]
Only affects running cql-pytest against C*, not backporting.
