### ISSUE TITLE
test.py reported hundreds of fake test failures after just one test failed

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#15982]
We've discussed this issue many times in the past, and I thought we already fixed it, but apparently it returned in a new form (or was never fixed?).

In PR https://github.com/scylladb/scylladb/pull/15791 I added a new test file, `test/cql-pytest/cassandra_tests/validation/operations/create_test.py`. We wouldn't be surprised to see a few failures in the new test file, but when the CI ran the result was the following, with 135 tests failing:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/testReport/

There are two big problems here:
1. You can see that after `Tests / Unit Tests / non-boost tests.cql-pytest.cassandra_tests/validation/operations/create_test.debug.1` failed, dozens of more debug tests in other files failed. Because we didn't change any other file, it means that `create_test` somehow broke the Scylla executable and still test.py continued to run further test files on it.
2. Worse, it appears that **test.py** did notice that Scylla is broken, and did not actually run those test files. As you can see in the list of failed tests, none of them is an actual **test function** like normal failure reports - instead the reported failure is the entire test file. It's as if test.py knew it shouldn't run pytest on a specific test file - perhaps because Scylla was already dead - but still created a (mostly empty) failure report for this test file. test.py should have either created a new Scylla instance, or not run the test - but definitely not create a failure report on a test file that never failed.

CC @kostja @kbr-scylla

**Comment by nyh** [comment]
By the way (and this is probably a Jenkins scriptology bug, not test.py bug), in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/testReport/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_cassandra_tests_validation_operations_create_test_debug_1/ we are told to look at "create_test.1.log" for more information, but the directory https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/cql-pytest.cassandra_tests/validation/operations/ only has create_test.2.log. What a mess...

**Comment by nyh** [comment]
The mention of create_test.1.log is obviously a bug in some script, it's create_test.2.log which exists, and the Scylla log also refers to create_test.2 which is being run - not create_test.1.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/cql-pytest.cassandra_tests/validation/operations/create_test.2.log shows a completely ordinary test failure of test  (probably a test bug). It doesn't look like a Scylla crash. It's weird is that we don't see the specific test which failed, testCreateKeyspaceWithNTSOnlyAcceptsConfiguredDataCenterNames - in the failed test report. 

The XML file generated by this file, https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/create_test.2.xunit.xml - did report the specific failed test, and exactly its error message, so I don't know why Jenkins got confused, or if any of this Jenkins mess is related to the bigger question - of why we get dozens of other tests failing.

**Comment by nyh** [comment]
The mystery continues :-(
According to https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/testReport/, after create_test failed, [Tests / Unit Tests / non-boost tests.cql-pytest.cassandra_tests/validation/operations/delete_test.debug.1](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/testReport/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_cassandra_tests_validation_operations_delete_test_debug_1/) and [Tests / Unit Tests / non-boost tests.cql-pytest.cassandra_tests/validation/operations/delete_test.debug.3](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/testReport/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_cassandra_tests_validation_operations_delete_test_debug_3/) also failed.

But what actually failed? https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/testReport/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_cassandra_tests_validation_operations_delete_test_debug_3/ for example points me to /scylladir/testlog/x86_64/debug/cql-pytest.cassandra_tests/validation/operations/delete_test.3.log but this log file does not exist! It probably does not exist because the test didn't really fail - look at https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml - it suggests all the subtests in this test passed well.

So Scylla did NOT crash, no test function in delete_test ever failed, and yet on Jenkins we see it reported as having failed. Why? @kostja  I think I need your help here, or help from someone else who is more familiar with what happens between test.py and Jenkins.

**Comment by nyh** [comment]
@benipeled maybe I need your help here. Sorry about the spam above, but here is a very quick summary:

In https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/testReport/ only one test really failed, create_test. Here is the XML of this failure:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/create_test.2.xunit.xml
Maybe we should see nine of these failures and not just one (3 runs, 3 modes?).
But Jenkins reports hundreds of failures, completely unrelated. It seems that the other "failures" don't actually exist - they don't have log files and the .xml for them show that they actually worked without failing.

I'm running out of ideas on how to debug this, or whose fault it is (is it test.py from scylla.git, or some Jenkins glue code from another repository).

**Comment by benipeled** [comment]
> So Scylla did NOT crash, no test function in delete_test ever failed, and yet on Jenkins we see it reported as having failed. Why? @kostja I think I need your help here, or help from someone else who is more familiar with what happens between test.py and Jenkins.

From the console it seems that `delete_test` does fail (and other tests as well) 

```
18:27:58  [22817/26664] cql-pytest  debug  [ FAIL ] cql-pytest.cassandra_tests/validation/operations/delete_test.3 30.27s
```
If you believe it's not true, we should check what's wrong with test.py output

Regarding the missing files I can see
```
19:08:43  Output of pytest --host=127.36.39.12 -s --log-level=DEBUG -o junit_family=xunit2 --junit-xml=/scylladir/testlog/x86_64/dev/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml -rs test/cql-pytest/cassandra_tests/validation/operations/delete_test.py:
19:08:43  ===Log /scylladir/testlog/x86_64/dev/cql-pytest.cassandra_tests/validation/operations/delete_test.3.log not found===
```
Which is also test.py output (before Jenkins "magics")

Does test.py run the tests in parallel? maybe it overwrites the 1/2/3/modes log files

**Comment by nyh** [comment]
> From the console it seems that `delete_test` does fail (and other tests as well)
> 
> ```
> 18:27:58  [22817/26664] cql-pytest  debug  [ FAIL ] cql-pytest.cassandra_tests/validation/operations/delete_test.3 30.27s
> ```
> 
> If you believe it's not true, we should check what's wrong with test.py output

That's so strange... According to https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml it seems all the tests that this ran were successful, so the entire test file should have passed as well.

@kostja is it possibly we have in test.py a bug where the failure of some previous test (in cql-pytest, that would be a test **file**) causes other test (files) to think they failed even though they actually succeeded? (I don't know how to pinpoint this question more, but this is the evidence I have).

> Regarding the missing files I can see
> 
> ```
> 19:08:43  Output of pytest --host=127.36.39.12 -s --log-level=DEBUG -o junit_family=xunit2 --junit-xml=/scylladir/testlog/x86_64/dev/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml -rs test/cql-pytest/cassandra_tests/validation/operations/delete_test.py:
> 19:08:43  ===Log /scylladir/testlog/x86_64/dev/cql-pytest.cassandra_tests/validation/operations/delete_test.3.log not found===
> ```
> 
> Which is also test.py output (before Jenkins "magics")

@kostja any idea? I'm not familiar with what can cause the log file to be missing. The test did run, as you can see in its XML output: 
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml 

> Does test.py run the tests in parallel? maybe it overwrites the 1/2/3/modes log files

Yes, I think it runs tests in parallel, but has the build mode (e.g., "debug") and these ".3" etc. in the names, so it won't overwrite the same name.

**Comment by nyh** [comment]
By the way, I can't find anywhere the actual "pytest" output (I guess this should have been in the missing log file) so I don't know, perhaps it did fail in some weird way after having run all the individual tests. Or maybe some internal test.py code (e.g., recycling the cluster) failed and we don't see that in any log file either :-(

I'll try to see if I can reproduce this problem of the failing-successful-tests locally.

**Comment by benipeled** [comment]
> By the way, I can't find anywhere the actual "pytest" output (I guess this should have been in the missing log file) so I don't know, perhaps it did fail in some weird way after having run all the individual tests. Or maybe some internal test.py code (e.g., recycling the cluster) failed and we don't see that in any log file either :-(

What do you mean by "_the actual "pytest" output_"? do we usually have additional logs for pytest beside `test.py.debug-release-dev.log`? https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/test.py.debug-release-dev.log/*view*/

**Comment by nyh** [comment]
@benipeled I meant that test.py runs external "pytest" processes, and those have output and I don't know where this is.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/test.py.debug-release-dev.log shows that delete_test.3 failed (e.g., with the debug build - it also failed in others):

```
18:27:25.327 INFO> [debug/cql-pytest.cassandra_tests/validation/operations/delete_test.3] Leasing Scylla cluster ScyllaCluster(name: 4951e7ea-7cc1-11ee-a247-a8a159ead542, running: ScyllaServer(11, 127.36.39.9, 1bc4a9b3-59fc-4fb5-87d2-b9e84a017218), stopped: ) for test cql-pytest.cassandra_tests/validation/operations/delete_test.3
18:27:25.327 INFO> Starting test cql-pytest.cassandra_tests/validation/operations/delete_test.3: pytest --host=127.36.39.9 -s --log-level=DEBUG -o junit_family=xunit2 --junit-xml=/scylladir/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml -rs test/cql-pytest/cassandra_tests/validation/operations/delete_test.py
18:27:55.610 INFO> [debug/cql-pytest.cassandra_tests/validation/operations/delete_test.3] Discarding cluster after failed test cql-pytest/cassandra_tests/validation/operations/delete_test...
18:27:55.610 INFO> [debug/cql-pytest.cassandra_tests/validation/operations/delete_test.3] Test cql-pytest.cassandra_tests/validation/operations/delete_test.3 failed 
```

What's frustrating is that the test **should not** have failed - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4549/artifact/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml shows that all the pytest tests passed (0 failures). So why does test.py think it failed? I can't find in that log file any error or the output of pytest.

**Comment by temichus** [comment]
as only create_test.2 failed other just did not run because there are no report_error messages from test run https://github.com/scylladb/scylladb/blob/master/test.py#L1112


like we have for create_test.2 :
```
18:08:32  === TEST.PY SUMMARY START ===
18:08:32  Test exited with code 1
18:08:32  
18:08:32  === TEST.PY SUMMARY END ===
```

other tests has no pytest output  and no log files are generated
```
18:08:32  Output of pytest --host=127.36.39.9 -s --log-level=DEBUG -o junit_family=xunit2 --junit-xml=/scylladir/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/operations/delete_test.3.xunit.xml -rs test/cql-pytest/cassandra_tests/validation/operations/delete_test.py:
18:08:32  ===Log /scylladir/testlog/x86_64/debug/cql-pytest.cassandra_tests/validation/operations/delete_test.3.log not found===
```

so probably run_test just did not run at all
because we have  ``` self.success = False '``` by default that  indicated  test as fail

so I see 2 problems here

1) tactical: for some reason after the first fail other tests are not running (maybe it is by design but I'm not sure
2) strategical:  there are only 2 test results Pass/FAIL and FAIL by default. need to introduce 3dt than Junit support ERROR status that will indicate python problems and set this ERROR status by default (could be self.success = None)


@nyh we are new in test.py it would be great if you have/provide a reproducer for this issue that we can use to investigate/fix these problems

**Comment by nyh** [comment]
This is an old issue, and I don't remember how to reproduce it today and maybe it's a good idea to close it, so I'll close it now. 
Since this report, I have NOT seen a problem of one test failure showing as hundreds of failures following it. What I have seen, multiple times, are smaller (and unrelated to this issue!) annoyances in Jenkins like:
1. Failures linking to logs of *successful* runs, and you need to do some investigation to find the actual failure.
2. Short failure reports include a "path" of a log file with more information, but this path isn't accurate (e.g., one component of the path isn't what it says), and frustratingly - isn't a link that can be clicked on.
3. The same failure gets reported twice and you often need to find the relevant logs in three different places.

If you want to be proactive about fixing test.py, Jenkins or their interaction, I suggest inserting into a Scylla branch:
1. A deliberately "flaky" test in test/cql-pytest (e.g., deliberately fails the test in one of two runs).
2. A *crashing* test (one which causes Scylla to crash).

You then want to see what Jenkins reports - that it doesn't report hundreds of other failures (this issue), and that the failures that were detected have correct links, correct paths to logs, and so on.

**Comment by temichus** [comment]
according to an internal discussion with @nyh. this discussion can be continue here https://github.com/scylladb/qa-tasks/issues/1603
