### ISSUE TITLE
select count(*) unreliable -- works on some nodes and not others

### ISSUE THREAD

**Issue by tynli** [scylladb/scylladb#15987]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2.9
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04 (amd64)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets=1 cores=4 hyperthreading=1 memory=32GB
Disks: NVMe x1

We have an issue with a small table with the following create:

```
CREATE TABLE tbl_name (
    id int,
    active boolean,
    cid int,
    meta map<text, text>,
    search text,
    PRIMARY KEY (id, active)
) WITH CLUSTERING ORDER BY (active ASC);
```

When we create this table, we can do a `select *` from it and get all the results (whether or not we have populated the table). We have tried this test with either 0 or 13 rows in the table, and the results are the same in either case.

We have 3 nodes in the cluster, and `select *` works on this table from any node. However, if we `select count(*)` from this table, only 1 of the nodes will return data. The other 2 return `NoHostAvailable:` as the only output. Nothing is logged to syslog when the queries fail, so I have no logs to provide.

`nodetool status` shows that all nodes are healthy, when run from any of the nodes in the cluster.

**Comment by mykaul** [comment]
Can you explain how are you running the 'select count(*)' ? Via which tool (cqlsh, some driver, etc... ) ?
Do you have distributed select count (https://github.com/scylladb/scylladb/commit/fe65122ccd40a2a3577121aebdb9a5b50deb4a90 ) enabled? Can you enable tracing?

**Comment by nyh** [comment]
> We have 3 nodes in the cluster, and `select *` works on this table from any node. However, if we `select count(*)` from this table, only 1 of the nodes will return data. 

What client or library are you using and how are you telling it to make a request only to a specific node?

> The other 2 return `NoHostAvailable:` as the only output.

NoHostAvailable is a type of error - there is usually some text attached to the error as well. Can you paste it here?

**Comment by tynli** [comment]
The error I described in the original post is from cqlsh. Unfortunately, `NoHostAvailable:` is all that is output (nothing follows the colon).

I have also tried running this query through the gocql driver, and the error I get there is:

```
Operation timed out for tbl_name - received only 0 responses from 2 CL=LOCAL_QUORUM.
```

When I run the query after `TRACING ON` in cqlsh, I get exactly the same output as before. Here is the content of `system_traces.sessions`:

```
 session_id                           | client      | command | coordinator | duration | parameters                                                                                                                                                              | request            | request_size | response_size | started_at                      | username
--------------------------------------+-------------+---------+-------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+--------------+---------------+---------------------------------+----------
 c1c4fab0-7e41-11ee-8baf-867b5d5eac5e | <IP1>       |   QUERY | <IP1>       |  1002523 | {'consistency_level': 'ONE', 'page_size': '100', 'query': 'select count(*) from tbl_name;', 'serial_consistency_level': 'SERIAL', 'user_timestamp': '1699453138393751'} | Execute CQL3 query |           51 |             0 | 2023-11-08 14:18:58.395000+0000 |     user
```

I have attached events.log, which is the output from `system_traces.events` for this session_id.
[events.log](https://github.com/scylladb/scylladb/files/13298034/events.log)

**Comment by nyh** [comment]
@tynli thanks for the detailed information. I think we should try to reproduce this in our own environment (e.g., a dtest).

Note that scanning an almost empty table is surprisingly slow on large clusters, but I don't think it should ever exceed the default cqlsh timeout (I think it's 2 seconds) on a small cluster like you describe (3 nodes, 4 cores each). So it sounds like you found a bug, not a real timeout.

**Comment by tynli** [comment]
FWIW, this error started for us after applying a batch of kernel security updates to our cluster on October 19. The security notice associated with the update is here: https://ubuntu.com/security/notices/USN-6441-1

**Comment by nyh** [comment]
> FWIW, this error started for us after applying a batch of kernel security updates to our cluster on October 19. The security notice associated with the update is here: https://ubuntu.com/security/notices/USN-6441-1

Wow, this is very strange... So you're saying that you used the same version of Scylla before and it didn't have this bug before that Linux kernel upgrade? I don't see how upgrading the kernel can break SELECT COUNT but leave SELECT working, but who knows...

**Comment by mykaul** [comment]
@wmitros - can you please take a look?

**Comment by wmitros** [comment]
> @wmitros - can you please take a look?

I'm looking. It probably worth adding @havaker here assuming we're using the distributed select count(*) (which is enabled by default from what I see)

**Comment by pdbossman** [comment]
FYI - Setting `enable_parallelized_aggregation: false` circumvents the issue.

**Comment by mykaul** [comment]
I understood it was due to time drift between nodes. @pdbossman - that is a hard(!) requirement for Scylla to operate properly. Can we close this issue?

**Comment by pdbossman** [comment]
> I understood it was due to time drift between nodes. @pdbossman - that is a hard(!) requirement for Scylla to operate properly. Can we close this issue?

The issue is resolved.  This is OSS, I don't have authority to close it.
