### ISSUE TITLE
Bump r_c_s diagnostics log level to warning when reader_concurrency_semaphore runs out of resources

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15992]
Currently `maybe_dump_reader_permit_diagnostics` always uses log_level::info.
But if the concurrency semaphore is out of resources, this warrants a warning instead.

**Comment by denesb** [comment]
Why is running out of resources special, compared to when a queued read times out? A queued read timing out is always a sign that resources have run out -- more often it is the CPU.

**Comment by mykaul** [comment]
> Why is running out of resources special, compared to when a queued read times out? A queued read timing out is always a sign that resources have run out -- more often it is the CPU.

I think the resources running out are directly under the control of the user (in our case - QA workload)? That's why I thought it is better to move it to a WARN level, whereas we are less in control on the underlying resources, and their consumption? (i.e, separation of frontend resources and backend resources)

**Comment by mykaul** [comment]
(and yes, if we could, in the future, we should be able to convey this to the client, if that's an option - via https://github.com/scylladb/scylladb/blob/master/docs/dev/protocol-extensions.md#rate-limit-error ?)

**Comment by denesb** [comment]
The thing is: the only reason the semaphore diagnostics is ever dumped, is that some resource has run out, be that memory, CPU or disk. So if you propose to make this always a warning, that is fine, but I see no way to make it a warning only sometimes.

**Comment by mykaul** [comment]
> The thing is: the only reason the semaphore diagnostics is ever dumped, is that some resource has run out, be that memory, CPU or disk. So if you propose to make this always a warning, that is fine, but I see no way to make it a warning only sometimes.

<ugly code>
```
if ((semaphore.initial_resources().count == semaphore.available_resources().count) || (semaphore.initial_resources().memory == semaphore.available_resources().memory)) {
    rcslog.log(log_level::warn ...
} else {
    rcslog.log(log_level::info ...
}
```
</ugly code>

**Comment by denesb** [comment]
Yes, but why treat count(disk)/memory differently than CPU. And once you take that into account, the if (should) always be true.

**Comment by mykaul** [comment]
Closing for the time being. Can't make a good justification of when to make this a warning only (since it's a temporary issue) vs. a real error that something's wrong.
