### ISSUE TITLE
Allow to change server's connection in `for_each_gently`

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#16035]
In a current state, when a scheduling group of a service level is changed, user's connections need to be restarted to apply the changes.
Despite Workload Prioritization is an enterprise feature, `generic_server::for_each_gently` exists in both versions so it should be done in OSS.

This is part of PR https://github.com/scylladb/scylla-enterprise/pull/3242

**Comment by denesb** [comment]
Forward looking change, not backporting.
