### ISSUE TITLE
[IPv6 configuration] A node is stuck with "?U" status and Host ID is "null", unclear reason

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#16039]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Scylla configuration: all addresses are IPv6 
[scylla.yaml](https://github.com/scylladb/scylladb/files/13333804/scylla.yaml.log)

When cluster was created, `longevity-10gb-3h-5-4-db-node-ba01d950-1` node remained in status "?N":
```
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address                                  Load       Tokens       Owns    Host ID                               Rack
UN  2a05:d018:12e3:f000:7aed:3233:7bbb:c344  1.01 MB    256          ?       5728ba00-ca9c-45db-adc4-bf08c0067df7  1a
UN  2a05:d018:12e3:f000:1005:2f59:d49d:bc98  810.74 KB  256          ?       7679d491-4572-4612-bb39-59ce8ddca1f2  1a
?N  2a05:d018:12e3:f000:69d:d442:b592:5d7a   ?          256          ?       null                                  1a
UN  2a05:d018:12e3:f000:9129:adc0:f67a:79b6  317.33 KB  256          ?       a79c8fd3-b4d7-4452-b41e-49e93a6003bf  1a
UN  2a05:d018:12e3:f000:c352:c6ab:ea67:d165  448.57 KB  256          ?       3600e6fc-a89e-490c-9746-ac26393c4b94  1a
UN  2a05:d018:12e3:f000:d16b:cbcb:111a:bc43  582.42 KB  256          ?       0c118da7-d2b8-42dc-9799-a3b5fb79fa7b  1a
```

Host ID is `null` despite it was set:
```
2023-11-07T15:34:21.695+00:00 longevity-10gb-3h-5-4-db-node-ba01d950-1     !INFO | scylla[11960]:  [shard 0:main] init - Setting local host id to 37334da4-55c5-417c-ba3f-661ac2bf9e01
```

Setting host id for the node was seen by other nodes and status "NORMAL". For example:
```
2023-11-07T15:37:00.415+00:00 longevity-10gb-3h-5-4-db-node-ba01d950-2     !INFO | scylla[11943]:  [shard 0:goss] storage_service - Set host_id=37334da4-55c5-417c-ba3f-661ac2bf9e01 to be owned by node=2a05:d018:12e3:f000:069d:d442:b592:5d7a
2023-11-07T15:37:00.415+00:00 longevity-10gb-3h-5-4-db-node-ba01d950-2     !INFO | scylla[11943]:  [shard 0:goss] gossip - InetAddress 2a05:d018:12e3:f000:069d:d442:b592:5d7a is now UP, status = NORMAL
```

But `nodetool status` shows "?N" status.
As result the test failed with error `Not all nodes joined the cluster`

I did not find any errors in the DB node and test logs. It is really not clear why the status is UNKNOWN for this node.
When I ran the reproducers I received case when 2 nodes were in UNKNOWN status.

This issue is observed with 5.3.0 version and 5.4.0

## Impact

Cluster is not ready

## How frequently does it reproduce?
I ran few reproducers with different versions

5.4.0~rc1 - **the problem is reproduced**, reproduced almost every run
5.3.0-rc0 - **the problem is reproduced** (got from first run). Official IPv6 test was not run with this version.
2023.1.2 - the problem is NOT reproduced (ran twice). Official IPv6 test was run and passed.
5.2.9 - the problem is NOT reproduced (ran once). Official IPv6 test was run and passed.

## Installation details

Cluster size: 6 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-4-db-node-ba01d950-6 (54.247.25.73 | 2a05:d018:12e3:f000:7aed:3233:7bbb:c344) (shards: 7)
- longevity-10gb-3h-5-4-db-node-ba01d950-5 (18.203.248.49 | 2a05:d018:12e3:f000:1005:2f59:d49d:bc98) (shards: 7)
- longevity-10gb-3h-5-4-db-node-ba01d950-4 (3.252.162.208 | 2a05:d018:12e3:f000:d16b:cbcb:111a:bc43) (shards: 7)
- longevity-10gb-3h-5-4-db-node-ba01d950-3 (54.75.1.208 | 2a05:d018:12e3:f000:c352:c6ab:ea67:d165) (shards: 7)
- longevity-10gb-3h-5-4-db-node-ba01d950-2 (34.245.97.126 | 2a05:d018:12e3:f000:9129:adc0:f67a:79b6) (shards: 7)
- longevity-10gb-3h-5-4-db-node-ba01d950-1 (63.35.226.250 | 2a05:d018:12e3:f000:69d:d442:b592:5d7a) (shards: 7)

OS / Image: `ami-01715aa610de633df` (aws: undefined_region)

Test: `longevity-10gb-3h-ipv6-test`
Test id: `ba01d950-928e-49f4-a81e-1bb54e52f9ad`
Test name: `scylla-5.4/longevity/longevity-10gb-3h-ipv6-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/86e790b8fc04e31fae746e411198fe365b2766ae/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ba01d950-928e-49f4-a81e-1bb54e52f9ad`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ba01d950-928e-49f4-a81e-1bb54e52f9ad)
- Show all stored logs command: `$ hydra investigate show-logs ba01d950-928e-49f4-a81e-1bb54e52f9ad`

## Logs:
- **db-cluster-ba01d950.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/db-cluster-ba01d950.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/db-cluster-ba01d950.tar.gz)
- **sct-runner-events-ba01d950.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/sct-runner-events-ba01d950.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/sct-runner-events-ba01d950.tar.gz)
- **sct-ba01d950.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/sct-ba01d950.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/sct-ba01d950.log.tar.gz)
- **loader-set-ba01d950.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/loader-set-ba01d950.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/loader-set-ba01d950.tar.gz)
- **monitor-set-ba01d950.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/monitor-set-ba01d950.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/monitor-set-ba01d950.tar.gz)
- **parallel-timelines-report-ba01d950.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/parallel-timelines-report-ba01d950.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ba01d950-928e-49f4-a81e-1bb54e52f9ad/20231107_160047/parallel-timelines-report-ba01d950.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.4/job/longevity/job/longevity-10gb-3h-ipv6-test/3/)
[Argus](https://argus.scylladb.com/test/f588f989-1117-4f4c-b1bc-09227f1bcb3f/runs?additionalRuns[]=ba01d950-928e-49f4-a81e-1bb54e52f9ad)
</details>

**Comment by juliayakovlev** [comment]
Another reproducer:
2 nodes with `null` host_id: `longevity-10gb-3h-5-4-db-node-726ad7ab-4` and `longevity-10gb-3h-5-4-db-node-726ad7ab-6`

By log host_id was set successully. Other nodes also see this host_id.
For example, node `longevity-10gb-3h-5-4-db-node-726ad7ab-4` with IP `2a05:d018:12e3:f000:a90:e791:a483:e28a`. Setting host_id:
```
Nov 12 11:34:35 longevity-10gb-3h-5-4-db-node-726ad7ab-4 scylla[12476]:  [shard 0:main] init - Setting local host id to e687fc9e-a4aa-4265-83bd-123a1b3cf47e
```

Its status is UP and **UNKNOWN** seen on `longevity-10gb-3h-5-4-db-node-726ad7ab-2` :
```
Nov 12 11:34:38 longevity-10gb-3h-5-4-db-node-726ad7ab-2 scylla[12260]:  [shard 2:main] raft_group_registry - Raft server id e687fc9e-a4aa-4265-83bd-123a1b3cf47e cannot be translated to an IP address.
Nov 12 11:34:38 longevity-10gb-3h-5-4-db-node-726ad7ab-2 scylla[12260]:  [shard 0:goss] gossip - InetAddress 2a05:d018:12e3:f000:0a90:e791:a483:e28a is now UP, status = UNKNOWN
```

Setting host_id is seen later on the `longevity-10gb-3h-5-4-db-node-726ad7ab-2` :
```
Nov 12 11:35:29 longevity-10gb-3h-5-4-db-node-726ad7ab-2 scylla[12260]:  [shard 0:goss] storage_service - Set host_id=e687fc9e-a4aa-4265-83bd-123a1b3cf47e to be owned by node=2a05:d018:12e3:f000:0a90:e791:a483:e28a
```

And status in the cluster is `?U`  with Host ID = "null":
```
&lt; t:2023-11-12 11:36:17,669 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; Status=Up/Down
&lt; t:2023-11-12 11:36:17,669 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; |/ State=Normal/Leaving/Joining/Moving
&lt; t:2023-11-12 11:36:17,671 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; --  Address                                  Load       Tokens       Owns    Host ID                               Rack
&lt; t:2023-11-12 11:36:17,675 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; UN  2a05:d018:12e3:f000:4857:4997:eb0a:5d5d  ?          256          ?       9c0ce21e-1c56-4440-942f-790aaf55ecd4  1a
&lt; t:2023-11-12 11:36:17,678 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; UN  2a05:d018:12e3:f000:d510:5e05:8c45:5c9e  466.02 KB  256          ?       fec5a101-2939-44e7-a881-6e2cde8735c8  1a
&lt; t:2023-11-12 11:36:17,680 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; UN  2a05:d018:12e3:f000:d9fa:1c56:f18c:4cbb  188.43 KB  256          ?       d70afd66-2027-4191-a53b-12efe419bd39  1a
&lt; t:2023-11-12 11:36:17,682 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG &gt; ?N  2a05:d018:12e3:f000:a90:e791:a483:e28a   ?          256          ?       null                                  1a
```


## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details








Cluster size: 6 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-4-db-node-726ad7ab-6 (54.195.157.182 | 2a05:d018:12e3:f000:ea5:fa8d:4daa:a44b) (shards: 7)
- longevity-10gb-3h-5-4-db-node-726ad7ab-5 (34.245.153.44 | 2a05:d018:12e3:f000:366a:e44f:5412:3604) (shards: 7)
- longevity-10gb-3h-5-4-db-node-726ad7ab-4 (34.245.136.189 | 2a05:d018:12e3:f000:a90:e791:a483:e28a) (shards: 7)
- longevity-10gb-3h-5-4-db-node-726ad7ab-3 (3.254.140.245 | 2a05:d018:12e3:f000:d510:5e05:8c45:5c9e) (shards: 7)
- longevity-10gb-3h-5-4-db-node-726ad7ab-2 (3.253.25.236 | 2a05:d018:12e3:f000:4857:4997:eb0a:5d5d) (shards: 7)
- longevity-10gb-3h-5-4-db-node-726ad7ab-1 (54.170.234.145 | 2a05:d018:12e3:f000:d9fa:1c56:f18c:4cbb) (shards: 7)


OS / Image: `ami-01715aa610de633df` (aws: undefined_region)

Test: `longevity-10gb-3h-ipv6-test`
Test id: `726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa`
Test name: `scylla-staging/yulia/longevity-10gb-3h-ipv6-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f19b2a50775a12311bfc89c9615879614078e117/test-cases/longevity/longevity-10gb-3h.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa)
- Show all stored logs command: `$ hydra investigate show-logs 726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa`


## Logs:
- **db-cluster-726ad7ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/db-cluster-726ad7ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/db-cluster-726ad7ab.tar.gz)
- **sct-runner-events-726ad7ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/sct-runner-events-726ad7ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/sct-runner-events-726ad7ab.tar.gz)
- **sct-726ad7ab.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/sct-726ad7ab.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/sct-726ad7ab.log.tar.gz)
- **loader-set-726ad7ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/loader-set-726ad7ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/loader-set-726ad7ab.tar.gz)
- **monitor-set-726ad7ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/monitor-set-726ad7ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/monitor-set-726ad7ab.tar.gz)
- **parallel-timelines-report-726ad7ab.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/parallel-timelines-report-726ad7ab.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa/20231112_115120/parallel-timelines-report-726ad7ab.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/longevity-10gb-3h-ipv6-test/4/)
[Argus](https://argus.scylladb.com/test/f4a292e9-e796-4467-91c2-2c2f9a77c96b/runs?additionalRuns[]=726ad7ab-ce9e-4a6c-89b3-29fe7ac645fa)
</details>

**Comment by mykaul** [comment]
@elcallio - please have a look.

**Comment by elcallio** [comment]
So the problem is that parts of the JMX interface nodetool uses relies on endpoints as strings, i.e. textual IP:s. Scylla/seastar formats ipv6 addresses slightly different; java removes leading zeros in an address, i.e. `2001:db8:0:0:0:0:0:2` whereas scylla uses `inet_ntop` "standard" unix formatting with full zero fill, i.e.  `2001:0db8:0000:0000:0000:0000:0000:0002` .

Relatively easy stop-gap solution is to simply transform strings in scylla-jmx, normalizing to java-style text. I am reluctant to modify the formatting in scylla.

**Comment by elcallio** [comment]
The problem is of course making sure all relevant code paths are handled...

**Comment by mykaul** [comment]
@elcallio - any idea how did it work in the past? Doesn't sound like it ever did... ?

**Comment by mykaul** [comment]
Does it impact 5.4?

**Comment by elcallio** [comment]
Yes. In fact, given that java/inet_ntop formats differently and the way the API:s work, I don't think these nodetool ops ever worked properly for IPv6 hosts. Luckily, the java-only (JMX) fix should backport easily across all releases one might wish to fix.

**Comment by mykaul** [comment]
https://github.com/scylladb/scylla-jmx/pull/229 is the fix on JMX (then need backport to 5.4)

**Comment by avikivity** [comment]
Why did we discover it on 5.4 and not master?

**Comment by mykaul** [comment]
> 5.4.0~rc1 - **the problem is reproduced**, reproduced almost every run
> 5.3.0-rc0 - **the problem is reproduced** (got from first run). Official IPv6 test was not run with this version. <------
> 2023.1.2 - the problem is NOT reproduced (ran twice). Official IPv6 test was run and passed.
> 5.2.9 - the problem is NOT reproduced (ran once). Official IPv6 test was run and passed.

@avikivity - I would assume some sort of a 'race' on when we run this test on master (and it's obvious we don't run regularly IPv6 tests on master?)

**Comment by mykaul** [comment]
> @denesb since you reviewed it, please complete the backport

I thought they were all done?

**Comment by mykaul** [comment]
> > > @denesb since you reviewed it, please complete the backport
> > 
> > 
> > I thought they were all done?
> 
> @denesb I don't see updated tools/jmx in branch-5.4

https://github.com/scylladb/scylladb/commit/6f073dfa54b9d87548e1052e417db8fbd6f93b4b

**Comment by mykaul** [comment]
What's not clear to me is if it has https://github.com/scylladb/scylla-jmx/commit/80ce5996df340469a15ff13396334fa4c80f6c87 in it as well.

**Comment by avikivity** [comment]
I think we should fix the way scylladb formats ipv6.

**Comment by mykaul** [comment]
> I think we should fix the way scylladb formats ipv6.

The comment from https://github.com/elcallio/scylla-jmx/commit/ccb1ccb6cc9d88f4ccb490f02f1fe33fca3f06fe says:
```
While this is really broken nodetool code, the problem is probably easier to fix here, in Scylla-JMX,
as a stopgap until we can fully replace nodetool.
```

**Comment by avikivity** [comment]
> Probably not. I am however lying a bit as well: The current formatting was applied by [4ea6e06](https://github.com/scylladb/scylladb/commit/4ea6e06cac4143c609e0105fed5a8facc2e730e2), which changed formatting to use a special, manual `fmt` routine (in a header - why?), instead of `inet_ntop` in seastar. However, using the latter would instead print with _all_ middle zeroes truncated (i.e. `2001:db8::2` in this example), which would be just as non-matching.
> 
> I.e. we have two different formatting paths here. Not sure if there would be any bad consequences of changing the `gms:::inet_address` formatting to _not_ lead-zero.
> 
> But mainly I of course dislike the two paths...

4ea6e06 should be fixed to restore the previous behavior. After that, we can change jmx/nodetool/whatever to be more permissive, and after that change the formatters to conform to canonical representation (without zeroes).

**Comment by mykaul** [comment]
@tchaikov - please see above.

**Comment by mykaul** [comment]
@avikivity - but I vote to get the java fix to 5.4, to unblock its release (if it's not in already - not sure)

**Comment by elcallio** [comment]
> [4ea6e06](https://github.com/scylladb/scylladb/commit/4ea6e06cac4143c609e0105fed5a8facc2e730e2) should be fixed to restore the previous behavior. After that, we can change jmx/nodetool/whatever to be more permissive, and after that change the formatters to conform to canonical representation (without zeroes).

The problem is that it is java formatting that is the issue here. Java formatting != inet_ntop. Nodetool mixes data in inetaddress format with data in string format, addresses formatted in seastar/scylla. And I don't think we should change seastar to format ipv6 java-style. 

Which is why, until such time as we make a nodetool replacement, and can bypass the archaic JMX API:s it uses, it is easier to just try to ensure strings are java-formatted in the JMX stack.

**Comment by denesb** [comment]
Backport queued to 5.4 as https://github.com/scylladb/scylladb/commit/1a0424db01178d572a88564d1f650dde74f2ac3c
