### ISSUE TITLE
scylla_post_install.sh: "[ $RHEL ]" does not work for RHEL, it only detects CentOS

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylladb#16040]
On scylla_post_install.sh, Redhat variants detection code only references $ID_LIKE:
```
RHEL=$(echo $ID_LIKE | grep -oi rhel)
```
https://github.com/scylladb/scylladb/blob/master/scylla_post_install.sh#L21

This will work finely on CentOS, but doesn't work on RHEL itself.
To make it work correctly we also need to check `$ID = "rhel"`.

**Comment by avikivity** [comment]
Backported to 5.1, 5.2, 5.4.
