### ISSUE TITLE
[centos7] offline installs are failing cause of kernel detection warning

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#16045]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

cause of 7b08886e8dd8, offline installer for centos7 started failing, like the following

```
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory /  --no-verify-package '
Exit code: 1
Stdout:
[1;31mntp setup is disabled by default, since the installation is offline mode.[0m
[1;31mRHEL/CentOS7 default kernel detected.[0m
[1;31mTo get optimal performance, please install kernel-ml kernel.[0m
[1;31mSetup aborted.[0m
Stderr:
```

## Impact

user that before were able to install on any kernel, not would fail to install scylla

## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-centos7-jenkins-db-node-cd21b2b2-0-1 (34.75.213.89 | 10.142.0.16) (shards: 2)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: undefined_region)

Test: `artifacts-centos7-test`
Test id: `cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc`
Test name: `scylla-master/artifacts-offline-install/artifacts-centos7-test`
Test config file(s):

- [centos7.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/850e48e150a44d54441709201c6931c795df57af/test-cases/artifacts/centos7.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc)
- Show all stored logs command: `$ hydra investigate show-logs cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc`

## Logs:
- **db-cluster-cd21b2b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc/20231114_045206/db-cluster-cd21b2b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc/20231114_045206/db-cluster-cd21b2b2.tar.gz)
- **sct-runner-events-cd21b2b2.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc/20231114_045206/sct-runner-events-cd21b2b2.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc/20231114_045206/sct-runner-events-cd21b2b2.tar.gz)
- **sct-cd21b2b2.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc/20231114_045206/sct-cd21b2b2.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc/20231114_045206/sct-cd21b2b2.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-centos7-test/346/)
[Argus](https://argus.scylladb.com/test/de44ea71-69c4-4d26-a7d2-dc5992baa24d/runs?additionalRuns[]=cd21b2b2-e6d9-4461-a409-e1fe9c4c5cdc)
</details>

**Comment by fruch** [comment]
FYI @yaronkaikov @syuu1228 
not clear what a use is expected todo in this case, i.e. there's no flag for this question

**Comment by fruch** [comment]
@roydahan, in which dashboard this should go ?

**Comment by roydahan** [comment]
Good question...
What kernel version is running there?
Where does this message coming from?
"To get optimal performance, please install kernel-ml kernel"

**Comment by roydahan** [comment]
This is the cause of the failure, but not where the message is coming from.

**Comment by roydahan** [comment]
This is where it comes from: https://github.com/scylladb/scylladb/commit/85339d18206b315bbec9ffd2bbf78b403f3ffc14

**Comment by roydahan** [comment]
BTW, according to this issue, we don't need to wait for CentOS 7 EOL, and 5.4 is EOL of CentOS7:
https://github.com/scylladb/scylladb/issues/7365
https://github.com/scylladb/scylla-enterprise/issues/3502

**Comment by roydahan** [comment]
So, we either look for a more recent cento7 image, or dropping support for CentOS7.

**Comment by fruch** [comment]
> So, we either look for a more recent cento7 image, or dropping support for CentOS7.
> 

My vote is to start dropping it on master/5.4

**Comment by fruch** [comment]
I'm disabling those jobs for now, until handle (they don't provide any more information right now)

**Comment by benipeled** [comment]
I enabled `scylla-master/artifacts-offline-install/artifacts-centos7-test`
@fruch I'm not sure what else you disabled - please enable

**Comment by benipeled** [comment]
@fruch btw, for mandatory tests like in this case of `artifacts-centos7-test` we don't have the jenkins.jobEnabled() logic that skips disabled jobs as we have for other tests, and so offline-installer failed because it couldn't trigger `artifacts-centos7-test`

**Comment by fruch** [comment]
> I enabled `scylla-master/artifacts-offline-install/artifacts-centos7-test` @fruch I'm not sure what else you disabled - please enable

me neither, I've disable all the centos7 related ones

anyhow, we should be stopping their trigger anyhow, since soon centos7 is going to be EOL.

I think there was already agreement to remove support in 5.4/2024.1
