### ISSUE TITLE
Ignore skip_wait_for_gossip_to_settle if consistent-topology-changes is ON

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#16055]
With consistent_toplogy_changes enabled, waiting for gossip to settle at boot is useless/unnecessary, so we should override the configuration setting and always skip gossip wait.

Prompted by https://github.com/scylladb/scylladb/issues/4632#issuecomment-1810424574

**Comment by nyh** [comment]
By the way, in addition to `skip_wait_for_gossip_to_settle`, there is a second parameter, `shutdown_announce_in_ms` which is used when Scylla is gently killed, and we should consider if it can also be set to zero. Scylla should continue to announce its demise, but should be able to tell when it succeeded in announcing it, and not sleep for a constant duration like 2 seconds.

**Comment by kostja** [comment]
Unfortunately not yet, we don't store the up/down state in Raft yet, but the team is gradually converging to having to do it, right @kbr-scylla, @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> Unfortunately not yet, we don't store the up/down state in Raft yet, but the team is gradually converging to having to do it, right @kbr-scylla, @gleb-cloudius

The team strongly believes there are thing that do not make any sense whatsoever.  Storing up/down state in Raft is a shining example of one. But then you often blur the difference between up/down state as reported by local failure detector and administrative shutdown state. The later may make sense to store in RAFT, but it will still be unreliable (we do want to be able to shutdown s node when there is no majority available), so unless there is very good use case for it why bother.

**Comment by kostja** [comment]
This is what I call *gradually* converging :-) @gleb-cloudius so up/down state to me is why you call "administrative shutdown state". It is another tedious discussion why they are really close - e.g. if an instance was down long enough according to gossiper, the state can be propagated to Raft - and stored persistently. So the difference is not that big as you describe in the comment.

And as to this having any value, this issue at hand is exactly the reason why we need to store it in Raft. 
During graceful shutdown, we want to inform the rest of the cluster to stop routing queries to that node, and the fastest way to do it is by putting this state to Raft and letting the leader replicate it to the rest of the cluster rather than wait for this information to propagate via gossiper and rely on a timeout.

**Comment by gleb-cloudius** [comment]
> This is what I call _gradually_ converging :-) @gleb-cloudius so up/down state to me is why you call "administrative shutdown state". It is another tedious discussion why they are really close - e.g. if an instance was down long enough according to gossiper, the state can be propagated to Raft - and stored persistently. So the difference is not that big as you describe in the comment.

It really cannot. One of the reasons is  because if a node is in shutdown state other nodes may assume that the node will go through the start-up process to exit the sate and they can rely on it. If other nodes may put partitioned out node to this state the state becomes even more useless. It cannot be used for anything.

> 
> And as to this having any value, this issue at hand is exactly the reason why we need to store it in Raft. During graceful shutdown, we want to inform the rest of the cluster to stop routing queries to that node, and the fastest way to do it is by putting this state to Raft and letting the leader replicate it to the rest of the cluster rather than wait for this information to propagate via gossiper and rely on a timeout.

Currently it is done by the RPC to all nodes. Moving it to RAFT is fine by me, but what is the improvement? A node may be partitioned out from the majority. It will not be able to change its state in RAFT, so the operation will have to have a timeout like we have now. And if timeout is reached then the cluster will not be notified. OTOH putting it in the RAFT will require us to do raft write on each boot, so to boot a node majority will be required and this is the rubicon we did not cross yet.

**Comment by kostja** [comment]
> > This is what I call _gradually_ converging :-) @gleb-cloudius so up/down state to me is why you call "administrative shutdown state". It is another tedious discussion why they are really close - e.g. if an instance was down long enough according to gossiper, the state can be propagated to Raft - and stored persistently. So the difference is not that big as you describe in the comment.
> 
> It really cannot. One of the reasons is because if a node is in shutdown state other nodes may assume that the node will go through the start-up process to exit the sate and they can rely on it. If other nodes may put partitioned out node to this state the state becomes even more useless. It cannot be used for anything.

No, the point is that hte end result will be equivalent. By storing the down state in Raft the node will be required to pass through boot to get up. It's a way of fencing such node.

**Comment by kostja** [comment]
> Currently it is done by the RPC to all nodes. Moving it to RAFT is fine by me, but what is the improvement? A node may be partitioned out from the majority. It will not be able to change its state in RAFT, so the operation will have to have a timeout like we have now. And if timeout is reached then the cluster will not be notified. OTOH putting it in the RAFT will require us to do raft write on each boot, so to boot a node majority will be required and this is the rubicon we did not cross yet.

I'd be happy if it was a direct RPC, but it's just updating the node state  in gossip and a sleep. Where did you find a direct RPC?

**Comment by gleb-cloudius** [comment]
> > Currently it is done by the RPC to all nodes. Moving it to RAFT is fine by me, but what is the improvement? A node may be partitioned out from the majority. It will not be able to change its state in RAFT, so the operation will have to have a timeout like we have now. And if timeout is reached then the cluster will not be notified. OTOH putting it in the RAFT will require us to do raft write on each boot, so to boot a node majority will be required and this is the rubicon we did not cross yet.
> 
> I'd be happy if it was a direct RPC, but it's just updating the node state in gossip and a sleep. Where did you find a direct RPC?

It is direct RPC though in addition to the state: `send_gossip_shutdown`. And actually in case of a network partition propagating the state over gossiper is more reliable since the state can be injected without majority.

**Comment by gleb-cloudius** [comment]
> > > This is what I call _gradually_ converging :-) @gleb-cloudius so up/down state to me is why you call "administrative shutdown state". It is another tedious discussion why they are really close - e.g. if an instance was down long enough according to gossiper, the state can be propagated to Raft - and stored persistently. So the difference is not that big as you describe in the comment.
> > 
> > 
> > It really cannot. One of the reasons is because if a node is in shutdown state other nodes may assume that the node will go through the start-up process to exit the sate and they can rely on it. If other nodes may put partitioned out node to this state the state becomes even more useless. It cannot be used for anything.
> 
> No, the point is that hte end result will be equivalent. By storing the down state in Raft the node will be required to pass through boot to get up. It's a way of fencing such node.

What you propose here is isolation, not shutdown state. You want a leader to be able to isolate nodes it cannot communicate with from the majority it can communicate with. This is something else and was discussed in the context of failure recovery from a topology op failure. You will not be able to isolate those nodes to communicate between themselves though which is also a problem.

**Comment by kostja** [comment]
> send_gossip_shutdown

OK, I see send_gossip_shutdown() now, thanks. Then I guess in order to remove the shutdown delay we don't have to put the state in raft - not necessarily - we can make send_gossip_shutdown messages a two-way RPC, run it concurrently, and if it has succeeded on all nodes, avoid the sleep.

**Comment by mykaul** [comment]
Is this still realistic / needed for 6.0?

**Comment by kostja** [comment]
Yes, yes.
