### ISSUE TITLE
Reactor stalled for 718 ms: during `disrupt_destroy_data_then_repair` nightly nemesis run (tcp / kernel related ?)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#16066]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

during `disrupt_destroy_data_then_repair` nightly nemesis run, we noticed this reactor stall
it was in between nemesis, i.e. we weren't doing any disruption at that time

last time this node was the target of a nemesis was between 2023-11-14 04:50:33 and 2023-11-14 05:24:46

```
2023-11-14 07:01:27.163 <2023-11-14 07:01:27.071>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=48df2954-557e-40c3-8944-7e27bc4a0ba2: type=REACTOR_STALLED regex=Reactor stalled line_number=8958 node=longevity-5gb-1h-CorruptThenRepairM-db-node-08f37a80-3
2023-11-14T07:01:27.071+00:00 longevity-5gb-1h-CorruptThenRepairM-db-node-08f37a80-3     !INFO | scylla[23502]: Reactor stalled for 718 ms on shard 0. Backtrace: 0x5b1f40a 0x5b1e815 0x5b1fbbf 0x3dbaf 0x114609 0x5b71a5a 0x5b4ad3c 0x5b4ae93 0x5b30d7f 0x5b32057 0x5b313c9 0x5ad2497 0x5ad164c 0x131852a 0x1319f80 0x1316abc 0x27b89 0x27c4a 0x13144e4
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
(inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:836
(inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:855
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1469
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1206
(inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1226
(inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1506
?? ??:0
?? ??:0
seastar::file_desc::recv(void*, unsigned long, int) at ./build/release/seastar/./seastar/include/seastar/core/posix.hh:242
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:423
seastar::future<seastar::temporary_buffer<char> > std::__invoke_impl<seastar::future<seastar::temporary_buffer<char> >, seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&>(std::__invoke_other, seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
(inlined by) std::__invoke_result<seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&>::type std::__invoke<seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&>(seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:96
(inlined by) std::invoke_result<seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&>::type std::invoke<seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&>(seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/functional:113
(inlined by) auto seastar::internal::future_invoke<seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&, seastar::internal::monostate>(seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&, seastar::internal::monostate&&) at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1155
(inlined by) operator() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1458
(inlined by) void seastar::futurize<seastar::future<seastar::temporary_buffer<char> > >::satisfy_with_result_of<seastar::future<void>::then_impl_nrvo<seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0, seastar::future<seastar::temporary_buffer<char> > >(seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<seastar::temporary_buffer<char> >&&, seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<seastar::temporary_buffer<char> >&&, seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<seastar::temporary_buffer<char> >&&, seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&&) at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1991
(inlined by) operator() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1454
(inlined by) seastar::continuation<seastar::internal::promise_base_with_type<seastar::temporary_buffer<char> >, seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0, seastar::future<void>::then_impl_nrvo<seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0, seastar::future<seastar::temporary_buffer<char> > >(seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&&)::{lambda(seastar::internal::promise_base_with_type<seastar::temporary_buffer<char> >&&, seastar::reactor::do_recv_some(seastar::pollable_fd_state&, seastar::internal::buffer_allocator*)::$_0&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:741
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2651
(inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:3114
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3283
seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:3166
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ./main.cc:655
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
main at ./main.cc:2036
?? ??:0
?? ??:0
_start at ??:?
?? ??:0
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1049-aws
Scylla version (or git commit hash): `5.5.0~dev-20231113.7b08886e8dd8` with build-id `7548c48606c5b58f282fc2b596019226de0df6ed`

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-CorruptThenRepairM-db-node-08f37a80-3 (51.20.108.27 | 10.0.1.220) (shards: 2)
- longevity-5gb-1h-CorruptThenRepairM-db-node-08f37a80-2 (51.20.123.67 | 10.0.0.118) (shards: 2)
- longevity-5gb-1h-CorruptThenRepairM-db-node-08f37a80-1 (13.49.57.117 | 10.0.2.252) (shards: 2)

OS / Image: `ami-02ea62bee686ef03b` (aws: undefined_region)

Test: `longevity-5gb-1h-CorruptThenRepairMonkey-aws-test`
Test id: `08f37a80-5297-4b0a-b793-5992df771962`
Test name: `scylla-master/nemesis/longevity-5gb-1h-CorruptThenRepairMonkey-aws-test`
Test config file(s):

- [longevity-5gb-1h-CorruptThenRepairMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/850e48e150a44d54441709201c6931c795df57af/test-cases/nemesis/longevity-5gb-1h-CorruptThenRepairMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 08f37a80-5297-4b0a-b793-5992df771962`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=08f37a80-5297-4b0a-b793-5992df771962)
- Show all stored logs command: `$ hydra investigate show-logs 08f37a80-5297-4b0a-b793-5992df771962`

## Logs:
- **db-cluster-08f37a80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/db-cluster-08f37a80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/db-cluster-08f37a80.tar.gz)
- **sct-runner-events-08f37a80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/sct-runner-events-08f37a80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/sct-runner-events-08f37a80.tar.gz)
- **sct-08f37a80.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/sct-08f37a80.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/sct-08f37a80.log.tar.gz)
- **loader-set-08f37a80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/loader-set-08f37a80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/loader-set-08f37a80.tar.gz)
- **monitor-set-08f37a80.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/monitor-set-08f37a80.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/08f37a80-5297-4b0a-b793-5992df771962/20231114_115050/monitor-set-08f37a80.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/nemesis/job/longevity-5gb-1h-CorruptThenRepairMonkey-aws-test/81/)
[Argus](https://argus.scylladb.com/test/6f0107a4-4fbe-4686-bd0e-38bfe4dd70b7/runs?additionalRuns[]=08f37a80-5297-4b0a-b793-5992df771962)
</details>

**Comment by avikivity** [comment]
Somewhat similar to:

https://github.com/scylladb/scylladb/issues/11807 (but: sendmsg instead of recv)
https://github.com/scylladb/scylladb/issues/7882 (but: read instead of recv, much smaller stall)

**Comment by avikivity** [comment]
@fruch please decode adjacent kernel traces if any.

**Comment by fruch** [comment]
> @fruch please decode adjacent kernel traces if any.

```
Nov 14 07:01:26.706335 longevity-5gb-1h-CorruptThenRepairM-db-node-08f37a80-3 scylla[23502]: kernel callstack: 0xffffffffffffff80 0xffffffff9b9e6094 0xffffffff9b9e73df 0xffffffff9b9ea49c 0xffffffff9b9d0d4c 0xffffffff9b9d167d 0xffffffff9b9d2a59 0xffffffff9ba1104c 0xffffffff9b8e1c71 0xffffffff9b8e40c5 0xffffffff9b8e41d4 0xffffffff9bbc5ef9 0xffffffff9bc000da

ffffffffc059e7dc t bpf_prog_28a890580b33b0dc	[bpf]
ffffffff9b9e5f80 t __tcp_transmit_skb
ffffffff9b9e7310 t __tcp_send_ack.part.0
ffffffff9b9ea480 T tcp_send_ack
ffffffff9b9d0cd0 T tcp_cleanup_rbuf
ffffffff9b9d1480 t tcp_recvmsg_locked
ffffffff9b9d29e0 T tcp_recvmsg
ffffffff9ba10ff0 T inet_recvmsg
ffffffff9b8e1c00 T sock_recvmsg
ffffffff9b8e3fe0 T __sys_recvfrom
ffffffff9b8e41b0 T __x64_sys_recvfrom
ffffffff9bbc5ea0 T do_syscall_64
ffffffff9bc00078 T entry_SYSCALL_64_after_hwframe
```

**Comment by avikivity** [comment]
I can't make sense of it.

The interruption point is in __tcp_transmit_skb, a little after the call to skb_push. It's not in any loop.

(the KASLR offset is 0x19e00000)

**Comment by avikivity** [comment]
@xemul  any ideas?

**Comment by xemul** [comment]
Some observations from the calltrace itself:
* `tcp_recvmsg` locks the socket first
* `__tcp_send_ack` calls `alloc_skb` which does two allocations in a row (GFP_ATOMIC though)

**Comment by avikivity** [comment]
If the lock was the problem, the sample should have caught it spinning. But it was caught somewhere else, running straight-line code.

I can't believe the allocations take 718ms. Maybe 718ns on a very bad day.

**Comment by xemul** [comment]
> If the lock was the problem, the sample should have caught it spinning. 

Why? It could have spinned for some time then proceed with straight-line code and being caught there

> I can't believe the allocations take 718ms. Maybe 718ns on a very bad day.

Agree, it's GFP_ATOMIC there, so chances this caused a problem a indeed low

**Comment by avikivity** [comment]
I don't have any idea on how to proceed.

**Comment by mykaul** [comment]
@fruch - how reproducible is it?

**Comment by fruch** [comment]
> @fruch - how reproducible is it?

I've seen it once in 3 weeks, so not that much

**Comment by mykaul** [comment]
Closing, we haven't made progress here for several months - nor seen it re-happening.
