### ISSUE TITLE
Provide test/README.md

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#16080]
Explain what directories store what and how to add a new test.

**Comment by nyh** [comment]
I agree it's needed.

Another thing to consider is to move the existing top-level test.py and docs/dev/testing.md into test/. I think it makes more sense, even though arguably typing test/test.py is three characters longer than ./test.py. And docs/dev/testing.md is entirely on the test/ directory (e.g., it doesn't discuss dtest, SCT, or any other aspect of Scylla's testing) so can definitely be in that directory as part of the new README.md.
