### ISSUE TITLE
repaired_at in the stats component is never set

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16098]
it turns out we never set the repaired_at field of stats component of an sstable. but both sstablemetadata and scylla sstable dump-statistics dump this field. it'd be nice if we can set this field for debugging purpose.

**Comment by denesb** [comment]
There is not meaningful value to put in this field, since we have no incremental repair. We might start using this field once we implement incremental repair ourselves.
Until then, maybe we should set it to 0 or some other value which suggests it is not a meaningful value.

**Comment by tchaikov** [comment]
@denesb hi Botond, if we don't have incremental_repaire, shall we just drop https://github.com/scylladb/scylla-dtest/blob/next/incremental_repair_test.py ?

**Comment by denesb** [comment]
> @denesb hi Botond, if we don't have incremental_repair, shall we just drop https://github.com/scylladb/scylla-dtest/blob/next/incremental_repair_test.py ?

I'm in favor, see https://github.com/scylladb/scylla-dtest/pull/3735#discussion_r1398850769.
I suppose you should open a PR and let's see what the dtest maintainers think about it.

**Comment by tchaikov** [comment]
> > @denesb hi Botond, if we don't have incremental_repair, shall we just drop https://github.com/scylladb/scylla-dtest/blob/next/incremental_repair_test.py ?
> 
> I'm in favor, see [scylladb/scylla-dtest#3735 (comment)](https://github.com/scylladb/scylla-dtest/pull/3735#discussion_r1398850769). I suppose you should open a PR and let's see what the dtest maintainers think about it.

i repurposed the change to drop it. we can always revert to the original version in case they don't like it.
