### ISSUE TITLE
RFC: Integration of Tablets load balancer with Add/Remove DC operations

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#16130]
Among others, adding/removing  a DC change the RF of system tables https://github.com/scylladb/scylladb/issues/16129
depedent on https://github.com/scylladb/scylladb/issues/16101

**Comment by tgrabiec** [comment]
This task will be covered as part of https://github.com/scylladb/scylladb/issues/16129#issuecomment-1854144102
