### ISSUE TITLE
s3_test::test_client_multipart_upload spurious failure

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylladb#16133]
CI run: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4802/

```
Stacktrace

[Exception] - seastar::httpd::unexpected_status_error: Unexpected reply status
 == [File] - test/boost/s3_test.cc
 == [Line] - 149

Standard Output

[Info] - 1 out of 9 times failed.
 == [File] - test/boost/s3_test.cc
 == [Line] - 157

[Info] - passed: debug=3, release=3, dev=2
 == [File] - test/boost/s3_test.cc
 == [Line] - 157

[Info] - failed: dev=1
 == [File] - test/boost/s3_test.cc
 == [Line] - 157

Standard Error

[Exception] - seastar::httpd::unexpected_status_error: Unexpected reply status
 == [File] - test/boost/s3_test.cc
 == [Line] - 149

```

I'm gonna guess that maybe the test should not assume all s3 calls always succeed? Retry?

**Comment by mykaul** [comment]
@tchaikov - please take a look.

**Comment by xemul** [comment]
> I'm gonna guess that maybe the test should not assume all s3 calls always succeed? Retry?

We've been on it for quite a while https://github.com/scylladb/seastar/pull/1883
And it would be nice to see what exactly went wrong (https://github.com/scylladb/seastar/issues/1931), oh, well

**Comment by xemul** [comment]
Now we know how it really fails:

```
[Exception] - storage_io_error: S3 request failed with (200 OK)
 == [File] - test/boost/s3_test.cc
 == [Line] - 151
```

so the test expects some non-OK code, but server replies with OK

**Comment by xemul** [comment]
Last logs are:

```
INFO  2023-12-06 21:00:33,987 [shard 0:main] testlog - Delete object: /testbucket/testlargeobject-32022
unknown location(0): fatal error: in "test_client_multipart_upload": storage_io_error: S3 request failed with (200 OK)
```

so it tries to do DELETE request and expects to see NoContent(204), but sees OK(200)

**Comment by xemul** [comment]
Ah, no, it fails earlier. The fix is on its way. This bug made my ~~day~~ year
