### ISSUE TITLE
RFC: Place holder for Tablets related metrics

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#16131]
Initenal list of metrics suggest by @tgrabiec 

- tablets_count (per coordinator)
- tablets_migrating (per coordinator)
- tablets_repairing (per coordinator)
- tablets_migrations_in (per shard)
- tablets_migrations_out (per shard)
- tablets_repair (per shard)
- load_balancer_load (per shard)

**Comment by tzach** [comment]
@tgrabiec is the above enougth to generate the heat-map animation? https://github.com/scylladb/scylla-monitoring/issues/2111

**Comment by amnonh** [comment]
I'm un assigning myself, once the metrics will be part of the code I'll make sure they are part of the dasbhaords

**Comment by avikivity** [comment]
It's pointless to file issues that are both RFC and placeholder. It's like saying "please ignore me".

**Comment by tgrabiec** [comment]
\cc @amnonh

**Comment by avelanarius** [comment]
Additional metric idea: number of times ScyllaDB sent a tablet information (via custom payload). This will make it easy to determine if a user is really using a tablet-aware driver and to make sure the driver is working correctly.

**Comment by amnonh** [comment]
Lets start with the mandatory ones so we'll be able to show tablets distribution.

@avelanarius if the metric is only going to be used to see if someone is using tablets aware driver, the metric can be reported per node.

**Comment by bhalevy** [comment]
@pwrobelse please work with @amnonh and @tgrabiec on how to implement the metrics and what exactly to implement for the initial release.
@avikivity suggested that the tablets count metrics are less interesting for the user and summing up on-disk capacity (see `sstable_set::size_on_disk`) would be more interesting.
Also, let's start with per-shard metrics.
Later on we can add grouping by keyspace/table as a followup.

**Comment by tgrabiec** [comment]
> @pwrobelse please work with @amnonh and @tgrabiec on how to implement the metrics and what exactly to implement for the initial release. @avikivity suggested that the tablets count metrics are less interesting for the user and summing up on-disk capacity (see `sstable_set::size_on_disk`) would be more interesting. Also, let's start with per-shard metrics. Later on we can add grouping by keyspace/table as a followup.

We already export size on disk per shard via `column_family_total_disk_space`

```
        if (_config.enable_node_aggregated_table_metrics && !is_internal_keyspace(_schema->ks_name())) {
            _metrics.add_group("column_family", {
...
                ms::make_gauge("total_disk_space", ms::description("Total disk space used"), _stats.total_disk_space_used)(cf)(ks)(node_table_metrics).aggregate({seastar::metrics::shard_label}).set_skip_when_empty(),

```

**Comment by amnonh** [comment]
@bhalevy I would like to reflect how the load_balancer works, I understand that currently, it balances the number of tablets, so we'll need a metric for that

**Comment by bhalevy** [comment]
After discussing with @amnonh offline, it would be ok if we start with a minimalistic implementation of number of tablets per shard, and optimize it later on.

**Comment by bhalevy** [comment]
I.e., it should be ok to start with a naive implementation that calculates the number of tablets per shard using a function that walks over the tablets map (for each table in the keyspaces that use tablets).
- later on we can optimize that by maintaining a tablets counter per-table that can be incremented/decremented whenever tablet ownership changes (on migration / rebuild / split)
- and then, based on `_config.enable_metrics_reporting`, we can expose the per-table counters in `table::set_metrics()`

**Comment by bhalevy** [comment]
@amnonh / @tgrabiec which metrics group should expose the per-shard tablets count metric?
and should it be a "counter" type or "gauge"?

**Comment by amnonh** [comment]
it shoud be a gauge (is it can go up and down) maybe you want to add them to the metrics under table.cc

**Comment by tgrabiec** [comment]
> @amnonh / @tgrabiec which metrics group should expose the per-shard tablets count metric? and should it be a "counter" type or "gauge"?

Probably "column_family" group, set up in table::set_metrics(). It could publish table::_tablet_count, which would be set in table::update_effective_replication_map(), which is the place through which all tablet map changes are published.

There is automatic aggregation in the `enable_node_aggregated_table_metrics` if branch.

**Comment by amnonh** [comment]
Adding to @tgrabiec comment, please note that the column_familiy group is disabled by default, and we would like to see at least a total counter per shard.

**Comment by pwrobelse** [comment]
Hi @tgrabiec @amnonh, I created WIP commit on my branch.

Does it correctly depict the requirements from the discussion? Could you point out
the necessary adjustments?

https://github.com/pwrobelse/scylla/commit/ac559743af4b724499a08727112d099f3883d1a6 

What I did is as follows:
- in `table::set_metrics()` a new metric called `tablet_count_on_current_shard` is added to `column_family` group; it is created using `make_gauge()` and it returns `_stats.tablet_count_on_current_shard`
- `_stats.tablet_count_on_current_shard` is updated in `table::update_effective_replication_map()` that calls a new function: `table::calculate_tablet_count_on_current_shard()`
- the new function firstly gets token metadata, then retrieves tablet_map from it and traverses it; for each tablet_id it calls `tablet_map.get_shard()` and compares the result with `this_shard_id()`


I have a few questions. I am a new to this project, therefore, I apologize if the questions are very basic. What I am not sure about is:

-who aggregates the new metric? Benny mentioned that the calculation should be done for each table in the keyspaces that use tablets; I added a code that does it for table object
- how to test the new metric? I would like to add a test that would verify that the logic works correctly.
-

**Comment by amnonh** [comment]
@pwrobelse can you create a pr or share link to your branch?

**Comment by pwrobelse** [comment]
> @pwrobelse can you create a pr or share link to your branch?

Please find the link to draft PR:
https://github.com/scylladb/scylladb/pull/17056

**Comment by amnonh** [comment]
@tzach @tgrabiec @bhalevy  PR #17056 added the useful metric for representation.

One point that I wasn't sure about, and still am not sure about, is the per-table metrics.
Today, by default, Scylla reports per-table metrics aggregated by instance.

I would like to have a per-table representation for tablets. Right now, if the per-table-per-shard-metric is off (the default behavior)
All the panels in the per-table dashboard would work except the tablets.

I suggest changing the tablet registration to report both per shard and per table with or without shard aggregation based on the same table configuration flag.

**Comment by amnonh** [comment]
I've sent PR #17182 to address the issue; I would like to finalize the dashboard and need its metrics names.

**Comment by bhalevy** [comment]
With https://github.com/scylladb/scylladb/pull/17056 I think we're good for 6.0
So setting the milestone for post 6.0 for adding other metrics.

**Comment by tzach** [comment]
@bhalevy @tgrabiec I suggest closing this issue and opening more specific ones if we need more metrics.
