### ISSUE TITLE
scylla-sstable ignores scylla.yaml unless it is explicitely provided

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16132]
scylla-sstable tries multiple things to obtain the schema of the sstable(s) it is provided. The order of things it tries is as follows:
* read schema from `./schema.cql`
* read schema from system table path, derived from the path of the sstable
* read scylla.yaml from the default location and obtain ScyllaDB's data path from it
* read schema from default data path

scylla-sstable will stop immediately if one of these is successful. This is fine for the most path, but it provides a somewhat clunky UX on enterprise, when EAR is used. I won't go into much detail, given that this is an enterprise feature, the point is that for encrypted sstables to be read, `scylla.yaml` has to be processed. To make the tool work OOTB with EAR, it should always attempt to read `scylla.yaml`. To minimize the difference between the enterprise and open-source code-base, this change should be made in open-source too. It is also a forward-looking change, in case OSS will ever require the configuration read, to correctly process sstables.

**Comment by denesb** [comment]
There is no need to backport this to any OSS release, only enterprise is affected by this patch.

**Comment by rayakurl** [comment]
@fruch does it mean we can use scylla sstable instead of sstable dump in boyk tests?

**Comment by fruch** [comment]
> @fruch does it mean we can use scylla sstable instead of sstable dump in boyk tests?

this is just one of a list of issues that are tracked in:
https://github.com/scylladb/scylla-enterprise/issues/3716
