### ISSUE TITLE
[aarch64] test_select_from_mutation_fragments.test_many_partitions timeout - slow test - need to bump timeouts

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#16145]
Seen on https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2668/artifact/testlog/aarch64/debug/cql-pytest.test_select_from_mutation_fragments.1.log/*view*/
```
_____________________________ test_many_partitions _____________________________

cql = <cassandra.cluster.Session object at 0xffff08891bd0>
test_keyspace = 'cql_test_1700669188969', scylla_only = None

    def test_many_partitions(cql, test_keyspace, scylla_only):
        num_partitions = 5000
        with util.new_test_table(cql, test_keyspace, 'pk int PRIMARY KEY, v int') as table:
            delete_id = cql.prepare(f"DELETE FROM {table} WHERE pk = ?")
            for pk in range(num_partitions):
                cql.execute(delete_id, (pk,))
    
>           res = list(cql.execute(f"SELECT * FROM MUTATION_FRAGMENTS({table})"))

test/cql-pytest/test_select_from_mutation_fragments.py:430: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2708: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.197.180.38:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.197.180.38:9042
```

aarch64 ran on armatrading

**Comment by mykaul** [comment]
Also seen @ https://jenkins.scylladb.com/job/scylla-master/job/next/6875/

**Comment by Annamikhlin** [comment]
seen again in https://jenkins.scylladb.com/job/scylla-master/job/next/6895/testReport/junit/(root)/test_select_from_mutation_fragments/Build___aarch64___Unit_Tests_aarch64___test_many_partitions/

**Comment by Annamikhlin** [comment]
seen again on
https://jenkins.scylladb.com/job/scylla-master/job/next/6902/testReport/junit/(root)/non-boost%20tests/Build___aarch64___Unit_Tests_aarch64___cql_pytest_test_select_from_mutation_fragments_debug_1/

**Comment by Annamikhlin** [comment]
The commit already inside but the latest `master/next` failed again on `OperationTimedOut`
https://jenkins.scylladb.com/job/scylla-master/job/next/6917/testReport/junit/(root)/test_select_from_mutation_fragments/Build___aarch64___Unit_Tests_aarch64___test_many_partitions/

@denesb - could you please take a look

**Comment by denesb** [comment]
Looks like I bumped the wrong timeout. It is another test that is failing, not the one I patched.

**Comment by denesb** [comment]
New fix here: https://github.com/scylladb/scylladb/pull/16370

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/next/6977/testReport/junit/(root)/non-boost%20tests/Build___aarch64___Unit_Tests_aarch64___cql_pytest_test_select_from_mutation_fragments_debug_1/
