### ISSUE TITLE
scylla-server service hangs on start without returning status

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#16159]
Scylla installation on a new instance works as expected,
Once done, `sudo systemctl start scylla-server.service` hang with no return status
The last lines on `sudo journalctl -u scylla-server.service` shows the service "initialization completed"

```
Nov 23 12:46:40 ip-10-0-3-246 scylla[10114]:  [shard  0:main] init - Waiting for gossip to settle before accepting client requests...
Nov 23 12:46:40 ip-10-0-3-246 scylla[10114]:  [shard  0:comp] compaction - [Compact system.scylla_local 590da8f0-89fe-11ee-bbbb-56a13973fc34] Compacted 2 sstables to [/var/lib/scylla/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-3gbb_0zhs_2a38y2urx6y7pmjxv8-big-Data.db:level=0]. 12kB to 6kB (~52% of original) in 24ms = 510kB/s. ~256 total partitions merged to 4.
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:main] gossip - No gossip backlog; proceeding
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:main] init - allow replaying hints
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:main] init - Launching generate_mv_updates for non system tables
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:main] init - starting the view builder
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:main] init - starting native transport
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:stmt] cql_server_controller - Starting listening for CQL clients on 127.0.0.1:9042 (unencrypted, non-shard-aware)
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:stmt] cql_server_controller - Starting listening for CQL clients on 127.0.0.1:19042 (unencrypted, shard-aware)
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:main] init - serving
Nov 23 12:46:52 ip-10-0-3-246 scylla[10114]:  [shard  0:main] init - Scylla version 5.5.0~dev-0.20231123.00d82c0d54cd initialization completed.
```

Scylla version: 5.5.0~dev-0.20231123.00d82c0d54cd (release mode)
OS: Ubuntu 22.04.3 LTS (ami-02a35bd020554f400)
Running on AWS m5d.8xlarge

**Comment by benipeled** [comment]
Installed with latest nightly build https://downloads.scylladb.com/unstable/scylla/master/deb/unified/2023-11-23T03:03:59Z/scylladb-master/scylla.list

**Comment by xemul** [comment]
`service start scylla-jmx` hangs too

**Comment by xemul** [comment]
```
  11434 ?        Ss     0:00  \_ sshd: ubuntu [priv]
  11540 ?        S      0:00  |   \_ sshd: ubuntu@pts/1
  11541 pts/1    Ss     0:00  |       \_ -bash
  11554 pts/1    S+     0:00  |           \_ sudo su -
  11555 pts/3    Ss     0:00  |               \_ sudo su -
  11556 pts/3    S      0:00  |                   \_ su -
  11557 pts/3    S      0:00  |                       \_ -bash
  11616 pts/3    S+     0:00  |                           \_ systemctl start scylla-server
  11617 pts/3    S+     0:00  |                               \_ /bin/systemd-tty-ask-password-agent --watch
  11436 ?        Ss     0:00  \_ sshd: ubuntu [priv]
  11497 ?        S      0:00  |   \_ sshd: ubuntu@pts/0
  11498 pts/0    Ss+    0:00  |       \_ -bash
  11739 ?        Ss     0:00  \_ sshd: ubuntu [priv]
  11778 ?        S      0:00  |   \_ sshd: ubuntu@pts/4
  11779 pts/4    Ss     0:00  |       \_ -bash
  11793 pts/4    S+     0:00  |           \_ sudo su -
  11794 pts/5    Ss     0:00  |               \_ sudo su -
  11795 pts/5    S      0:00  |                   \_ su -
  11796 pts/5    S      0:00  |                       \_ -bash
  11902 pts/5    S+     0:00  |                           \_ systemctl start scylla-jmx.service
  11908 pts/5    S+     0:00  |                               \_ /bin/systemd-tty-ask-password-agent --watch
```

**Comment by benipeled** [comment]
Failed to start with exit-code 143  
```
ubuntu@ip-10-0-3-246:~$ journalctl -u scylla-jmx
Nov 23 12:32:46 ip-10-0-3-246 systemd[1]: Started Scylla JMX.
Nov 23 12:32:46 ip-10-0-3-246 scylla-jmx[9477]: Picked up JAVA_TOOL_OPTIONS:
Nov 23 12:32:46 ip-10-0-3-246 scylla-jmx[9477]: Using config file: /etc/scylla/scylla.yaml
Nov 23 12:32:46 ip-10-0-3-246 scylla-jmx[9477]: Connecting to http://127.0.0.1:10000
Nov 23 12:32:46 ip-10-0-3-246 scylla-jmx[9477]: Starting the JMX server
Nov 23 12:32:47 ip-10-0-3-246 scylla-jmx[9477]: JMX is enabled to receive remote connections on port: 7199
Nov 23 12:40:05 ip-10-0-3-246 systemd[1]: Stopping Scylla JMX...
Nov 23 12:40:06 ip-10-0-3-246 systemd[1]: scylla-jmx.service: Main process exited, code=exited, status=143/n/a
Nov 23 12:40:06 ip-10-0-3-246 systemd[1]: scylla-jmx.service: Failed with result 'exit-code'.
Nov 23 12:40:06 ip-10-0-3-246 systemd[1]: Stopped Scylla JMX.
Nov 23 12:40:06 ip-10-0-3-246 systemd[1]: scylla-jmx.service: Consumed 1.756s CPU time.
```

**Comment by mykaul** [comment]
143 is SIGTERM.

**Comment by mykaul** [comment]
Which Java version are we running?

**Comment by michoecho** [comment]
f4626f6b8e54a11d80e6412d8022a0f8aca830c3 deleted the `supervisor::notify("starting storage service", true);` call, which notifies systemd that the service started. Thus systemd waits forever.

@xemul

**Comment by xemul** [comment]
Why this message? Is this "starting storage service" line hard-coded into systemd somewhere?

@michoecho

**Comment by michoecho** [comment]
No, it's the second `true` argument. See https://github.com/scylladb/scylladb/blob/00d82c0d54cd50ccba7c11e7201df34d3aaf3881/supervisor.hh#L38.

**Comment by xemul** [comment]
Ah. That's easy then. Doesn't our CI start scylla via systemd?

**Comment by michoecho** [comment]
> Ah. That's easy then. Doesn't our CI start scylla via systemd?

I don't think so. Doesn't our CI only run test.py and dtest, both of which start Scylla in their own ways? Where would it use systemd?

**Comment by xemul** [comment]
> > Ah. That's easy then. Doesn't our CI start scylla via systemd?
> 
> I don't think so. Doesn't our CI only run test.py and dtest, both of which start Scylla in their own ways?
> Where would it use systemd?

It could be a fun unit test to start scylla with custom NOTIFY_SOCKET env and a check of what scylla told in there

**Comment by benipeled** [comment]
> > Ah. That's easy then. Doesn't our CI start scylla via systemd?
> 
> I don't think so. Doesn't our CI only run test.py and dtest, both of which start Scylla in their own ways? Where would it use systemd?

It's not - see https://github.com/scylladb/scylladb/blob/157a5c4b1b984cacf1524ceaf40a82305f6841cd/test/pylib/scylla_cluster.py#L407-L415

`self.exe` stand for the bin path

Similar case with dtest which AFAIK use SDK to run a cluster but not systemd, which makes sense when the purpose is  bootstrapping test-environment,

In any case we should try covering this area so similar failure will be caught on CI/gating

**Comment by xemul** [comment]
A related question. The place where this notification was, before I removed it, looks pretty random. What should have been initialized in Scylla after which it could notify systemd that it's ready? API listening? Native transport (hardly, it starts after joining cluster)? RPC port a.k.a. messing service?

**Comment by xemul** [comment]
Thrift maybe? 😛

**Comment by tchaikov** [comment]
i just created #16166 to address the regression. regarding where / when we should consider scylla "READY", i think we can always continue the discussion after the regression is addressed.

**Comment by tchaikov** [comment]
> > > Ah. That's easy then. Doesn't our CI start scylla via systemd?
> > 
> > 
> > I don't think so. Doesn't our CI only run test.py and dtest, both of which start Scylla in their own ways?
> > Where would it use systemd?
> 
> It could be a fun unit test to start scylla with custom NOTIFY_SOCKET env and a check of what scylla told in there

systemd allows us to control systemd units on a per-user basis. so in theory, we can install and start multiple scylla units with different names.

**Comment by fruch** [comment]
@benipeled  As for CI, I think it's about time to introduce one of the artifacts tests into it.

**Comment by nyh** [comment]
According to #16166, the regression was introduced last week in https://github.com/scylladb/scylladb/commit/f4626f6b8e54a11d80e6412d8022a0f8aca830c3. So if that patch will not backported, there will be no need to backport this fix as well.
