### ISSUE TITLE
how to have counter on a table row with other column types? will this be in the roadmap?

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/scylladb#16160]
how to have counter on a table row with other column types? will this be in the roadmap?

**Comment by tzach** [comment]
No, the feature is not planned.
You are more than welcome to share the use case in the [forum](https://forum.scylladb.com/) maybe we can suggest an alternative solution.

**Comment by nyh** [comment]
This is a duplicate of the 6-year-old issue https://github.com/scylladb/scylladb/issues/2433. There's an even older (9 year old) open issue on this in Cassandra - https://issues.apache.org/jira/browse/CASSANDRA-9810.

I seem to remember that the lack of this feature is not _entirely_ an oversight - I think there are real differences between the semantics of regular rows and counters and it would be confusing or misleading to mix them in the same update. But to be honest I never looked deeply in this issue.
