### ISSUE TITLE
latency degradation during upgrade of node on mixed workload (2ms on steady state to 1200ms during upgrade)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#16189]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

Steady state read/write are ~2ms, during the upgrade of the 1st node 
we are getting to write/reads ~1200ms

#### Total test HDR Histogram percentiles

Workload | Start time | End time | Percentile 50 | Percentile 90 | Percentile 99 | Percentile 99.9
-- | -- | -- | -- | -- | -- | --
WRITE | 2023-11-26 09:57:43 | 2023-11-26 10:30:16 | 0.54 | 1.91 | 83.69 | 1313.87
READ | 2023-11-26 09:57:43 | 2023-11-26 10:30:16 | 1.16 | 3.61 | 219.02 | 1349.52

### upgrade_node

Cycle | Scylla build | Latency percentile_90 WRITE |  Latency percentile_90 READ | Steady State percentile_90 WRITE | Steady State percentile_90 READ | Latency percentile_99 WRITE | Latency percentile_99 READ | Steady State percentile_99 WRITE | Steady State percentile_99 READ | Duration (sec) | Commit id, date
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Cycle #1 | current build | 1.91 | 4.99 | 0.58 | 1.19 | 1166.02 | 1225.79 | 1.49 | 2.09 | 0:05:23 | 5.5.0~dev-0.20231122.65e42e4166ce
Cycle #2 | current build | 1.85 | 3.56 | 0.58 | 1.19 | 4.34 | 45.25 | 1.49 | 2.09 | 0:05:12 | 5.5.0~dev-0.20231122.65e42e4166ce
Cycle #3 | current build | 2.04 | 4.07 | 0.58 | 1.19 | 355.73 | 468.45 | 1.49 | 2.09 | 0:05:38 | 5.5.0~dev-0.20231122.65e42e4166ce

Compare current average cycles results with previous version

Cycle | Scylla build | Latency percentile_90 WRITE |  Latency percentile_90 READ | Steady State percentile_90 WRITE | Steady State percentile_90 READ | Latency percentile_99 WRITE | Latency percentile_99 READ | Steady State percentile_99 WRITE | Steady State percentile_99 READ | Duration (sec) | Commit id, date
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
average | current build | 1.93 | 4.21 | 0.58 | 1.19 | 508.7 | 579.83 | 1.49 | 2.09 | 0:05:24 | 5.5.0~dev-0.20231122.65e42e4166ce
avg per version | 5.2.9 | 2.09( -7.66%) | 3.86( 9.07%) | 0.62 | 1.54 | 945.78( -46.21%) | 955.98( -39.35%) | 2.06 | 3.33 | 0:05:47( -6.63 %) | 5709d0043978,20230920
avg per version | 5.2.10 | 2.02( -4.46%) | 4.09( 2.93%) | 0.69 | 1.62 | 443.33( 14.75%) | 552.77( 4.9%) | 2.13 | 3.71 | 0:05:07( 5.54 %) | 454e5a711099,20231102
avg per version | 5.2.0~rc1 | 1.93( 0.0%) | 3.56( 18.26%) | 0.68 | 1.46 | 44.03( 1055.35%) | 95.97( 504.18%) | 1.95 | 2.94 | 0:07:16( -25.69 %) | 8ff4717fd010,20230207
avg per version | 5.2.0~rc0 | 1.99( -3.02%) | 4.63( -9.07%) | 1.03 | 2.45 | 1181.92( -56.96%) | 1219.77( -52.46%) | 2.19 | 4.32 | 0:07:35( -28.79 %) | 34ab98e1be2e,20230119
avg per version | 5.2.0 | 2.25( -14.22%) | 6.66( -36.79%) | 1.34 | 2.67 | 1036.28( -50.91%) | 1101.7( -47.37%) | 2.21 | 4.35 | 0:07:18( -26.03 %) | 429b696bbc1b,20230427

* All latency values are in ms. if latency has color red, check detailed HDR report
<span><b>Cycle: 1<span> </span></b>::<span> </span></span><span><b>total number of reactor stalls:</b><span> </span>2;<span> </span></span><span><b>stall value</b>: &lt;= 10 ms:<span> </span><b>number</b>: 2;</span></div><div><span><b>Cycle: 2<span> </span></b>::<span> </span></span><span><b>total number of reactor stalls:</b><span> </span>2;<span> </span></span><span><b>stall value</b>: &lt;= 10 ms:<span> </span><b>number</b>: 2;</span></div><div><span><b>Cycle: 3<span> </span></b>::<span> </span></span><span><b>total number of reactor stalls:</b><span> </span>4;<span> </span></span><span><b>stall value</b>: &lt;= 10 ms:<span> </span><b>number</b>: 4;</span></div></div>

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1049-aws
Scylla version (or git commit hash): `5.2.10-20231102.454e5a711099` with build-id `1cabeff053229b347a86aefb619c61419e5b647e`
Target Scylla version (or git commit hash): `5.5.0~dev-20231122.65e42e4166ce` with build-id `44721ca3535e729f9dd7dee34b519bfc91b8c564`

Cluster size: 3 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-upgrade-ubuntu-db-node-fa042003-3 (52.19.201.182 | 10.4.6.157) (shards: 7)
- perf-latency-upgrade-ubuntu-db-node-fa042003-2 (34.245.78.1 | 10.4.5.72) (shards: 7)
- perf-latency-upgrade-ubuntu-db-node-fa042003-1 (34.244.152.161 | 10.4.6.235) (shards: 7)

OS / Image: `ami-06c50bd68f5bcab2a` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-during-upgrade`
Test id: `fa042003-ae5d-4e4c-b21b-c497bfe4a7ac`
Test name: `scylla-master/scylla-master-perf-regression-latency-650gb-during-upgrade`
Test config file(s):

- [perf-regression-latency-650gb-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7ed5af5ba2fb977de6eadb8f9c2fbb78156658dd/test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor fa042003-ae5d-4e4c-b21b-c497bfe4a7ac`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=fa042003-ae5d-4e4c-b21b-c497bfe4a7ac)
- Show all stored logs command: `$ hydra investigate show-logs fa042003-ae5d-4e4c-b21b-c497bfe4a7ac`

## Logs:
- **db-cluster-fa042003.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/db-cluster-fa042003.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/db-cluster-fa042003.tar.gz)
- **sct-runner-fa042003.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/sct-runner-fa042003.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/sct-runner-fa042003.tar.gz)
- **monitor-set-fa042003.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/monitor-set-fa042003.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/monitor-set-fa042003.tar.gz)
- **loader-set-fa042003.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/loader-set-fa042003.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa042003-ae5d-4e4c-b21b-c497bfe4a7ac/20231126_110435/loader-set-fa042003.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-latency-650gb-during-upgrade/18/)
[Argus](https://argus.scylladb.com/test/45b2f64b-54c7-4fb6-9c28-e058f5976456/runs?additionalRuns[]=fa042003-ae5d-4e4c-b21b-c497bfe4a7ac)
</details>

**Comment by fruch** [comment]
> I remember we've discussed two items around this:
> 
> 1. Are we loading (the basic load) too much? We started with 50%, but it wasn't clear if average of 50% wouldn't mean at times that we overload the nodes (need to look at the monitor)

![image](https://github.com/scylladb/scylladb/assets/340979/44b25d9d-e75f-406b-b33e-5d8b6ac7525b)

it doesn't look like it's overload the CPUs

> 2. Should we test with more nodes?

What do you mean more nodes ? i.e. cluster of 3 nodes isn't big enough ?

**Comment by mykaul** [comment]
> What do you mean more nodes ? i.e. cluster of 3 nodes isn't big enough ?

Indeed. Test and see what the impact is with a cluster of 6 nodes for example.

**Comment by mykaul** [comment]
What is 'Commit id, date' ?

**Comment by avikivity** [comment]
Please don't report latency degradation as a percentage. 0.2ms -> 1.2ms is 6X the latency, but both are excellent.

**Comment by avikivity** [comment]
> ## Issue description
> * [ ]  This issue is a regression.
> * [x]  It is unknown if this issue is a regression.
> 

What's the point of running regression tests if we never know if it's a regression?

**Comment by fruch** [comment]
> > ## Issue description
> > * [ ]  This issue is a regression.
> > * [x]  It is unknown if this issue is a regression.
> > 
> 
> What's the point of running regression tests if we never know if it's a regression?

It's a new test

**Comment by roydahan** [comment]
@soyacz can we run the test with 6 nodes initial cluster size and report back the results?

**Comment by soyacz** [comment]
with 6 nodes cluster size, results are good. You can find results email by searching for `2cef20a7-83f0-41cf-9701-f3ac38fe05dc`

**Comment by roydahan** [comment]
it "violates" our original target of testing with 50% of max throughput, but I think it should be good enough.

![Screenshot 2024-03-13 at 14 13 07](https://github.com/scylladb/scylladb/assets/20959584/0aedea16-a0b7-411e-802c-7ecacc82ef4f)

@avikivity / @mykaul are you ok with this change?
(We can also ry it to 4 nodes which will bridge the gap a little bit from the max throughput)

**Comment by fruch** [comment]
> Why can't we test with 50% max throughput of 6 nodes?
> (If our acceptance criteria is <15ms, surely we can either bump the throughput or reduce the no. of nodes, no?)

No one said it's impossible, 
Just that playing with the number of nodes is quick, recalibrating the load to match some usage percentage is a bit longer process.

**Comment by roydahan** [comment]
If we increase the load again to be 50% of max throughput, we will probably be in the same issue as we were with 3.
Once one node is down, the throughput is heavier for the rest of the nodes and the latency jumps. 
There is a potential that the 5 nodes will handle it better, but it’s not guaranteed.

**Comment by roydahan** [comment]
so Lukasz, it's not enough to increase just the number of nodes, we also need to double the original load (double the throughput).

**Comment by soyacz** [comment]
trying that.
Also another approach could be switching i3en.2xlarge to i4i.2xlarge (taking half of the throughput measured in current throughput test) and keep 3 db nodes.

**Comment by soyacz** [comment]
test with doubled throughput: `2811f1ca-33d5-4ec7-b437-45206895589f`:
![image](https://github.com/scylladb/scylladb/assets/18242288/3968943e-9638-4e33-8c25-a8ae21d4ece5)

There's an issue with steady-state latency calculation (need to analyze the root cause of these), but test results looks fine.

**Comment by soyacz** [comment]
> @soyacz
> 
> so we can consider closing this, now that we switched to 6 nodes ? results are acceptable ?

Yes, results are stable so far
