### ISSUE TITLE
reader_permit::get_schema() is unsafe against table schema alter or drop

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16180]
The reader_permit records `schema*`, which can be destroyed on schema alter.

This affects both of these methods:
```
    future<reader_permit> obtain_reader_permit(table& tbl, const char* const op_name, db::timeout_clock::time_point timeout, tracing::trace_state_ptr trace_ptr);
    future<reader_permit> obtain_reader_permit(schema_ptr schema, const char* const op_name, db::timeout_clock::time_point timeout, tracing::trace_state_ptr trace_ptr);
```

The latter delegates to the first.

The implementation looks like this:
```
future<reader_permit> database::obtain_reader_permit(table& tbl, const char* const op_name, db::timeout_clock::time_point timeout, tracing::trace_state_ptr trace_ptr) {
    return get_reader_concurrency_semaphore().obtain_permit(tbl.schema().get(), op_name, tbl.estimate_read_memory_cost(), timeout, std::move(trace_ptr));
}

future<reader_permit> reader_concurrency_semaphore::obtain_permit(const schema* const schema, const char* const op_name, size_t memory,
        db::timeout_clock::time_point timeout, tracing::trace_state_ptr trace_ptr) {
    auto permit = reader_permit(*this, schema, std::string_view(op_name), {1, static_cast<ssize_t>(memory)}, timeout, std::move(trace_ptr));
    return do_wait_admission(*permit).then([permit] () mutable {
        return std::move(permit);
    });
}
```

So the raw schema pointer is stored in the permit. It can be accessed from `do_dump_reader_permit_diagnostics()`.

It is not guaranteed that the schema object is held by the outer scope, esp. when obtained via `table&` object.

For example, stream_transfer_task.cc has this:
```
        auto& tbl = sm.db().find_column_family(cf_id);
      return sm.db().obtain_reader_permit(tbl, "stream-transfer-task", db::no_timeout, {}).then([&sm, &tbl, plan_id, cf_id, id, dst_cpu_id, ranges=std::move(ranges), reason, topo_guard] (reader_permit permit) mutable {
```

The table's schema may change by the time we obtain the permit, and nothing may hold that schema version in memory. Streaming obtains the schema later.

The permit should keep schema_ptr.

\cc @denesb

**Comment by denesb** [comment]
In theory the permit's lifecycle should match that of the read, which should already make sure the table/schema is kept alive for its duration.

Of course, changing the raw ptr to  `schema_ptr` is not wrong and, eliminating a source of bug is always good. I will prepare a patch.

**Comment by mykaul** [comment]
> In theory the permit's lifecycle should match that of the read, which should already make sure the table/schema is kept alive for its duration.
> 
> Of course, changing the raw ptr to `schema_ptr` is not wrong and, eliminating a source of bug is always good. I will prepare a patch.

@tgrabiec - did you get a chance to prepare this patch?

**Comment by denesb** [comment]
> @tgrabiec - did you get a chance to prepare this patch?

I will do this, once I have some spare cycles.

**Comment by denesb** [comment]
@lkshminarayanan please prepare backport PR:s for 5.4 and 5.2. See instructions below on how to do this:
* checkout branch-5.4, and pull latest content
* create a new branch based on branch-5.4, just like you would do on master
* git cherry-pick -x -m1 76f0d5e35bb24d7aac95de628d816ff7fc3abb62
* The above will cherry-pick the entire branch, if the above has too much conflicts to handle, you can resort to cherry picking the individual commits. Just make sure to use `git cherr-pick -x`. The important part is the `-x`, this will add the `(cherry picked from commit XXXXX)` to the commit, which gives us a paper-trail on the origin of backport commits on release branches.
* Once you solve all conflicts, check that the code builds and at least the new tests pass.
* Open a PR as usual, select branch-5.4 as the base branch (by default `master` is selected as the base branch).
* In the PR description, mention that this is a backport (also mention to which version), and provide a link to the original PR.
* We usually also prepend the target version to the git PR title: `[branch-5.4] backport ....`.

Repeat the same for 5.2 as well.

**Comment by mykaul** [comment]
> @lkshminarayanan please prepare backport PR:s for 5.4 and 5.2. See instructions below on how to do this:
> 
> * checkout branch-5.4, and pull latest content
> * create a new branch based on branch-5.4, just like you would do on master
> * git cherry-pick -x -m1 [76f0d5e](https://github.com/scylladb/scylladb/commit/76f0d5e35bb24d7aac95de628d816ff7fc3abb62)
> * The above will cherry-pick the entire branch, if the above has too much conflicts to handle, you can resort to cherry picking the individual commits. Just make sure to use `git cherr-pick -x`. The important part is the `-x`, this will add the `(cherry picked from commit XXXXX)` to the commit, which gives us a paper-trail on the origin of backport commits on release branches.
> * Once you solve all conflicts, check that the code builds and at least the new tests pass.
> * Open a PR as usual, select branch-5.4 as the base branch (by default `master` is selected as the base branch).
> * In the PR description, mention that this is a backport (also mention to which version), and provide a link to the original PR.
> * We usually also prepend the target version to the git PR title: `[branch-5.4] backport ....`.
> 
> Repeat the same for 5.2 as well.

Probably should be somewhere in the dev docs.
