### ISSUE TITLE
Allow creating an Alternator table that uses tablets instead of vnodes

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16203]
Right now, for a new table to use tablets instead of vnodes, its keyspace must use the network topology replication strategy and the replication option `initial_tablets`, e.g.,
```
CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1, 'initial_tablets': 100}
```
In Alternator the user can't supply this option on `CreateTable` operation, so Alternator tables always get the old vnodes, and can't use tablets.

We could imagine creating a table with vnodes and then using CQL `ALTER KEYSPACE` to switch it to tablets, but switching from vnodes to tablets on existing table is not supported, so this won't work. We need a proper way to control whether or not an Alternator `CreateTable` operation uses tablets for a new table.

I think the easiest and perhaps best solution is to decide that Alternator **always** uses tablets on new tables, but only **if** they are available and enabled in the cluster (e.g., currently it requires enabling an experimental feature).

Two other more elaborate options:
1. We can set a global option configuration, e.g., `alternator_use_tablets`, which controls whether or not Alternator uses tablets.
2. Maybe we can (ab)use the new DynamoDB API TableClass (https://github.com/scylladb/scylladb/issues/10431) to say on each new table creation whether it should use vnodes or tablets.

Beyond the UI, we'll need to fix the implementation.  Creating an Alternator table **with GSI** probably not work currently with tablets, because the tablet implementation added a `before_create_column_family()` notifier that is supposed to be called when creating a table to create its tablet, and it is called for the base table in `prepare_new_column_family_announcement()`, which we call in `create_table_on_shard0()` (`executor.cc`), but we don't call any such function for the view we may also create - so most likely we'll get an error like in https://github.com/scylladb/scylladb/issues/16194. This is why I added the "materialized views" tag to this issue.

**Comment by mykaul** [comment]
Why is this Alternator specific? Why wouldn't the default for ALL new tables, given the configuration and feature enabled of tablet, is to use it?

**Comment by tgrabiec** [comment]
For GA we want to move away from the current logic of enabling tablets via `initial_tablets` option, and instead have them be enabled by default in the whole cluster, with opt-out config option. So this will take care of this problem for alternator.

**Comment by nyh** [comment]
> For GA we want to move away from the current logic of enabling tablets via `initial_tablets` option, and instead have them be enabled by default in the whole cluster, with opt-out config option. So this will take care of this problem for alternator.

If that's our goal, then why not do this right now? After all, the tablets feature can only be enabled with an "experimental=tablets" flag, so nobody can turn it on by mistake, and neither would any of the test frameworks (sct, dtest, etc.) who simply won't enable the experimental flag.

**Comment by nyh** [comment]
> We want to do that, just didn't get around to do it yet.

Great. If we had a configuration option to enable tablets on all NetworkTopology tables, Alternator will get tablets too, for free (although we probably will have the GSI bug I mentioned above, that I'll have to fix).

Please let me know if you do get around to doing it, or planning to, or need someone from @eliransin's team to do this. Should be very easy unless I'm missing something.

**Comment by tgrabiec** [comment]
> I think (unless I'm forgetting something ;-)) this issue it is basically the only thing standing between us and supporting Alternator on tablets.

Does alternator depend on CDC? We don't support it yet.

**Comment by tgrabiec** [comment]
I can see that alternator/ttl.cc uses per-keyspace erm in token_ranges_owned_by_this_shard.
We need to verify that sharding works with tablet-based sharder. Some algorithms may assume that shard is static on a given node, but with tablets it may change due to migration. Also, consecutive tokens do not land on consecutive shards, and multishard reader for example relied on that assumption.

**Comment by nyh** [comment]
Thanks @tgrabiec, good catches. So we'll need to fix all these places, and think what to do if CDC will not be supported (may need an option to choose between tablets and supporting alternator streams).

**Comment by nyh** [comment]
> For GA we want to move away from the current logic of enabling tablets via `initial_tablets` option, and instead have them be enabled by default in the whole cluster, with opt-out config option. So this will take care of this problem for alternator.

Given that this is the plan, I think we can already do the same for Alternator tables, i.e, if the tablets feature exists we can create all Alternator tables with tablets, unconditionally. However, @tgrabiec, where will I get the "initial_tablets" feature from?

@tgrabiec @mykaul can you please consider moving the CQL change from "for GA" to now? (which will allow me to avoid needing to solve the "initial_tablets" issue myself)? This change will also affect a lot of tests that are being written and will need to be changed, so I think we should do it as  earlier as possible.

I'll move the other issues discovered by @tgrabiec above to separate issues.

**Comment by tgrabiec** [comment]
> > Given that this is the plan, I think we can already do the same for Alternator tables, i.e, if the tablets feature exists we can create all Alternator tables with tablets, unconditionally.
> 
> On second thought, I have doubts :-( If enabling tablets means we have lost CDC support, why is this fine? In the DynamoDB API, Streams (i.e., CDC) can be enabled later, not during table creation. At table creation time, we don't know if CDC will be needed. So how can we decide if to use tablets or not? :-(

The idea was to warn about unsupported features when creating a keyspace. \cc @avikivity @tzach  

> 
> It seems like maybe we will need an ad-hoc way to enable tablets in Alternator just for testing, but may not be able to enable it yet for actual users. @tgrabiec what is the planned time frame for CDC+tablets support? Why don't we have an open issue about it (or at least, I couldn't find one)?

We have one now: https://github.com/scylladb/scylladb/issues/16317

We don't plan doing it before 6.0.

**Comment by tgrabiec** [comment]
> > For GA we want to move away from the current logic of enabling tablets via `initial_tablets` option, and instead have them be enabled by default in the whole cluster, with opt-out config option. So this will take care of this problem for alternator.
> 
> Given that this is the plan, I think we can already do the same for Alternator tables, i.e, if the tablets feature exists we can create all Alternator tables with tablets, unconditionally. However, @tgrabiec, where will I get the "initial_tablets" feature from?

If initial_tablets is not specified, it will be computed based on heuristics, e.g. as proposed here: https://docs.google.com/document/d/1k1u9r9kByvc6d6lF52fhHCyFkCNgDnU4L6h1qYwnm_0/edit?pli=1#bookmark=id.60lqse1onps8

**Comment by tgrabiec** [comment]
> @tgrabiec @mykaul can you please consider moving the CQL change from "for GA" to now? (which will allow me to avoid needing to solve the "initial_tablets" issue myself)? This change will also affect a lot of tests that are being written and will need to be changed, so I think we should do it as earlier as possible.

I opened https://github.com/scylladb/scylladb/issues/16319 for enabling-by-default

**Comment by nyh** [comment]
> > @tgrabiec @mykaul can you please consider moving the CQL change from "for GA" to now? (which will allow me to avoid needing to solve the "initial_tablets" issue myself)? This change will also affect a lot of tests that are being written and will need to be changed, so I think we should do it as earlier as possible.
> 
> I opened #16319 for enabling-by-default

Thanks. After asking to enable tablets on CQL by default to help Alternator, I realized (see https://github.com/scylladb/scylladb/issues/16203#issuecomment-1843131281 above) that I can't, at this point, enable tablets on Alternator **by default**, because it is missing some of the features that Alternator needs. So in Alternator, tablets will need to be explicitly enabled (and I already have a patch for this which I'll send later). So I am no longer hoping it will be the default in CQL just to help Alternator (but you can do it, or not, for other reasons).
