### ISSUE TITLE
wide_rows_test.TestWideRows.test_large_partition_detector_with_ttl_on_few_row_in_partition fails due to actual partition size is smaller than expected one

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16244]
`wide_rows_test.py::TestWideRows::test_large_partition_detector_with_ttl_on_few_row_in_partition` expects that the partition size should be in the expected range of of 10400000 and with 3% deviation of the upper bound so the upper bound is 10400000 * 103%, but what it got was 8389093.

```

    def test_large_partition_detector_with_ttl_on_few_row_in_partition(self):
        """
        Validate that when most of rows in the large partition are expired, this partition is not reported in
        the system.large_partitions table and there are no warning in the log
        """
        partition_rows = 10000
        partition_num = 1
        extra_partitions = 0
        entity_type = 'partition'
    
#...
>       cluster_state = self.validate_system_table(entity_type=entity_type, keyspace_name=self.KEYSPACE_NAME,
                                                   table_name=self.TABLE_NAME,
                                                   expected_entity_number=partition_num,
                                                   expected_entity_data_size=expected_partition_data_size)
#...
wide_rows_test.py:885: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
wide_rows_test.py:375: in validate_system_table
    self.validate_entity_size(cluster_state=cluster_state, expected_entity_data_size=expected_entity_data_size,
wide_rows_test.py:348: in validate_entity_size
    assert_equal_more_with_deviation(size, expected_size, row_size_threshold)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

actual = 8389093, expect = 10400000, deviation_perc = 3
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4996/testReport/junit/wide_rows_test/TestWideRows/Tests___Sanity_Tests___test_large_partition_detector_with_ttl_on_few_row_in_partition_TimeWindowCompactionStrategy_/

**Comment by bhalevy** [comment]
This looks like a test issue.
Let's improve the test to dump more information about the sstables if and when this is reproduced.
The logs are already deleted so we can't really tell.

**Comment by bhalevy** [comment]
@denesb please assign someone to improve the test

**Comment by bhalevy** [comment]
maybe dump metadata of all sstables in the stable

**Comment by denesb** [comment]
> maybe dump metadata of all sstables in the stable

But how will that help in finding out why there are 20K rows missing?

Actually, I think I just spotted the key to the issue: `TimeWindowCompactionStrategy`. If the test is "lucky" enough, the test partition could be segregated into two windows and then each window will compact the partition separately, and we will not have all rows included in the large partition size.

**Comment by bhalevy** [comment]
> > maybe dump metadata of all sstables in the stable
> 
> But how will that help in finding out why there are 20K rows missing?
> 
> Actually, I think I just spotted the key to the issue: `TimeWindowCompactionStrategy`. If the test is "lucky" enough, the test partition could be segregated into two windows and then each window will compact the partition separately, and we will not have all rows included in the large partition size.

Exactly, I suspect too that the partition ends up divided across sstables.
Dumping the metadata will allow us to see the token ranges and timestamp ranges in each sstable.
We also keep the larges partition size, number of rows in partition, row size, number of cells in row, and largest cell and collection sizes in each sstable.

**Comment by denesb** [comment]
> Exactly, I suspect too that the partition ends up divided across sstables.
> Dumping the metadata will allow us to see the token ranges and timestamp ranges in each sstable.
> We also keep the larges partition size, number of rows in partition, row size, number of cells in row, and largest cell and collection sizes in each sstable.

How about instead of adding this much diagnostics, we make the test not split partitions across time windows? :)
I'll prepare a patch.

**Comment by denesb** [comment]
Fix: https://github.com/scylladb/scylla-dtest/pull/4041
