### ISSUE TITLE
Disable self-pairing optimization

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16260]
A write to a base table generate (one or more) writes to a materialized view.  The writes to RF base replicas need to cause writes to RF view replicas. Our MV implementation, based on Cassandra's implementation, does this with "**pairing**" - each one of the base replicas writes to exactly one view replica. The function `get_view_natural_endpoint()` tells a base replica which of the view replicas it should send the update to.

The _standard_  pairing is based on the ring order - the first owner of the base token sends to the first owner of the view token, the second to the second, and so on. However, the existing code also uses an optimization we call **self-pairing**, where if a single node is both a base replica and a base replica, the pairing is this node would send the update to itself.

This self-pairing optimization can cause the pairing to change after view ranges are moved between nodes, so it can break base-view consistency in some edge cases (leading to "ghost rows"). So this issue proposes to remove the self-pairing exception in `get_view_natural_endpoint()`.

However, changing the pairing on an **existing** table can cause the very same inconsistencies we want to void, so we want an upgraded table to continue using the old pairing.

We could add a configuration option to turn self-pairing on or off on a view (similar to how we handle the `synchronous_updates` flag), but I propose to start with something simpler:

1. A table using **vnodes** will default to use self-pairing, like today.
2. A table using **tablets** will default to not use self-pairing.  Because old vnode tables cannot be upgrade to tablets, we don't risk pairing changes. In tablets, range movements are more common (even if the cluster itself doesn't grow, individual tables may move around nodes) so disabling the problematic optimization is more important.

Later, we can, if we want, add a configurable option to set this flag on a table, but we don't need to do it now (we did the same thing for `synchronous_updates`, which started with some automatic logic and only later we made it explicitly configurable).

**Comment by mykaul** [comment]
But some day we will support migration of a table (or keyspace?) from vnodes to tablets.
