### ISSUE TITLE
install-dependencies.sh: pip_packages are ignored

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#16269]
install-dependencies.sh contains a list called `pip_packages`:
https://github.com/scylladb/scylladb/blob/01e54f5b12e72a2976f973d23ae0c61ce19ba914/install-dependencies.sh#L132-L137

However, this list is not used to actually install the packages, one reason, might be that some specific constrains were needed on some of the packages:
https://github.com/scylladb/scylladb/blob/01e54f5b12e72a2976f973d23ae0c61ce19ba914/install-dependencies.sh#L322-L325

This means that new packages added to `pip_packages` are doomed to fail the script and also the build since they will not be installed and then will not be extracted into the python distribution package.

**Comment by nyh** [comment]
The commit that introduced this "pip_packages", 729d0feef0f12a13644d8f7c887323df49f53527 by @syuu1228, says it is used to "Pass --pip-packages option to tools/python3/reloc/build_reloc.sh", i.e., to build the "relocatable python". 

Apparently this is no longer done, so this variable isn't needed any more. I don't know enough about this code to explain why we no longer need these parameters to build the relocatable Python (?). Maybe @avikivity or @syuu1228 can explain.

**Comment by eliransin** [comment]
it looks like 5.2,5.3,5.4 have the same problem and also it is a clean cherry-pick for all versions.
@mykaul/@avi every version that is not expected to get `code coverage` or alternatively don't expect any new pip packages added to it, will not need this backport.
One consideration however is that the fix for this leave things semantically identical so it is a low risk backport.

**Comment by mykaul** [comment]
I don't see a huge use case for covering anything but master branch.
