### ISSUE TITLE
[Docs]: use Scylla Doctor instead of HealthCheck

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#16276]
Doc page: https://opensource.docs.scylladb.com/stable/troubleshooting/report-scylla-problem.html#health-check-report

*Description*
We have a public location to pick SD so let's make it official.

The whole "Health Check" section should be replaced with the following:

---------------
Scylla Doctor Vitals

1. Download latest Scylla Doctor from: https://downloads.scylladb.com/downloads/scylla-doctor/latest/
2. In case CQL authentication is enabled on the cluster, please, uncomment the `[CQL]` section in `scylla_doctor.conf` and setup CQL credentials that are allowed to perform `DESCRIBE SCHEMA` command.
3. Copy `scylla_doctor.pyz` and the updated (as described in (2) above) `scylla_doctor.conf` to all your Scylla nodes.
4. Execute the following command from the directory where you downloaded `scylla_doctor.pyz` and `scylla_doctor.conf` on every node of your cluster:

```
sudo ./scylla_doctor.pyz -cf ./scylla_doctor.conf --save-vitals <uniq host ID, e.g. its IP>.vitals.json
```
__Note: This is going to generate a `<uniq host ID, e.g. its IP>.vitals.json` file.__

5. Collect result JSON files into a local directory with a name identifying your cluster (e.g. `my_awesome_cluster`) and compress it. For example this is how you can do it using Linux `tar` command:
```
tar czvf my_awesome_cluster_vitals.tgz my_awesome_cluster
```
6. Upload the resulting archive with Vitals using instructions from https://opensource.docs.scylladb.com/stable/troubleshooting/report-scylla-problem.html#send-files-to-scylladb-support

**Comment by vladzcloudius** [comment]
> Bullet 3 could use some rewording. Specifically, "updated (if was needed)" isn't clear.

@mykaul see if it's clearer now.

> 
> Otherwise, LGTM. We should add it to regular QA tests.

**Comment by tzach** [comment]
What is Scylla Doctor license? 
HealthCheck was part of the project, is Scylla Doctor a 3rd party?

**Comment by vladzcloudius** [comment]
> What is Scylla Doctor license? HealthCheck was part of the project, is Scylla Doctor a 3rd party?

What license should it have, @tzach ?

**Comment by vladzcloudius** [comment]
> What is Scylla Doctor license? HealthCheck was part of the project, is Scylla Doctor a 3rd party?

We can keep it as a 3d party for now.
In general it makes sense to include the version that collects Vitals (the one that is downloadable from the URL in the opening message) part of our scylla/scylla-enterprise packages in the future.
This way people don't have to download it. 
Also QA testing, @mykaul mentioned, would be done with a specific version of the tool which will then be distributed.

**Comment by mykaul** [comment]
'and updated' -> 'and the updated'.

It'd be easier to review as a PR, TBH.

**Comment by vladzcloudius** [comment]
> 'and updated' -> 'and the updated'.

fixed ;)

> 
> It'd be easier to review as a PR, TBH.

True, I guess @annastuchlik is going to create one some time soon.

**Comment by vladzcloudius** [comment]
@annastuchlik @tzach ping

**Comment by tzach** [comment]
Approved!

**Comment by mykaul** [comment]
@roydahan - can we add Scylla Doctor to the artifact tests?

**Comment by roydahan** [comment]
We can, but the if we want to actually test something. It needs to read the content of the JSON output and verify it with something. And for the it should be better defined.

**Comment by tzach** [comment]
@roydahan lets start with validating there is a JSON

**Comment by vladzcloudius** [comment]
> @roydahan lets start with validating there is a JSON

@roydahan SD has a rather advanced CI with a lot of tests.
Please, take a closer look.

**Comment by vladzcloudius** [comment]
> @vladzcloudius I tried to download Scylla Doctor from https://downloads.scylladb.com/downloads/scylla-doctor/latest/ and modify scylla_doctor.conf, but the download failed. Are there prerequisites to downloading it? ![image](https://private-user-images.githubusercontent.com/37244380/303693539-2264db3f-8035-426d-959c-e2c5ddf5929b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0OTkyODMsIm5iZiI6MTcwNzQ5ODk4MywicGF0aCI6Ii8zNzI0NDM4MC8zMDM2OTM1MzktMjI2NGRiM2YtODAzNS00MjZkLTk1OWMtZTJjNWRkZjU5MjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE3MTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNGM1YjgwZThiYTc1Mzk5YzdjNzU4NGQ5MjQyY2I0NDNlNjViNzJkYjE0OTJmODRiZDUzODU0M2VmOWNmZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZfXMKCT7Fsr9D_3dVksD7AFxq1jz12YLuiHjCy5vzU)

Thre shouldn't be and it indeed doesn't work.
@d-helios @tarzanek any comments?

**Comment by vladzcloudius** [comment]
This one works https://downloads.scylladb.com/downloads/scylla-doctor/e57706c736468ddf52da9804ae45e3b68880bbe4/

@annastuchlik ^

You can use it until Artem fixes the permissions.

**Comment by vladzcloudius** [comment]
@d-helios this looks like a regression: the working link above is from December 03 2023.
And the latest upload was on Feb 06 2024 and it doesn't.

Please, check what has changed?

**Comment by vladzcloudius** [comment]
@annastuchlik Artem fixed permissions of files in the `latest` and they are downloadable now.

**Comment by vladzcloudius** [comment]
@annastuchlik ping

**Comment by mykaul** [comment]
nit: we also need to drop health check script at some point, if we don't maintain it (and I believe we do not )

**Comment by vladzcloudius** [comment]
> nit: we also need to drop health check script at some point, if we don't maintain it (and I believe we do not )

Correct. But not before we transition to SD officially == this issue (and the corresponding PR) are complete.  ;)
Ideally we should ship the SD .pyz artifact with Scylla packages **instead** of shipping `healthcheck` as we do today. This will simplify the "how to report issue" instructions even further - will remove the "download" part.

**Comment by vladzcloudius** [comment]
> @vladzcloudius Please have a look at the related PR: #17617 I'd like to make the update, but I don't have access to Zendesk, and I need you to provide the current instructions.

Working on it....

**Comment by vladzcloudius** [comment]
> > @vladzcloudius Please have a look at the related PR: #17617 I'd like to make the update, but I don't have access to Zendesk, and I need you to provide the current instructions.
> 
> Working on it....

Done, @annastuchlik

**Comment by juliayakovlev** [comment]
> > @roydahan lets start with validating there is a JSON
> 
> @roydahan SD has a rather advanced CI with a lot of tests. Please, take a closer look.

@vladzcloudius 
what should we validate in the JSON? 
What is expected there? 
Which is expected json structure? 
What is pass/fail criteria

**Comment by roydahan** [comment]
> > > @roydahan lets start with validating there is a JSON
> > 
> > 
> > @roydahan SD has a rather advanced CI with a lot of tests. Please, take a closer look.
> 
> @vladzcloudius what should we validate in the JSON? What is expected there? Which is expected json structure? What is pass/fail criteria
> 
> Please, add link to CI tests

@juliayakovlev in above comments it was mentioned that we just need to verify there is a JSON file in output, we can also verify it's not empty and valid JSON and possiblty contain the scylla version we expect it to contain.

**Comment by vladzcloudius** [comment]
However...
I suggest we coordinate on this before you, guys, do anything: I'm beginning the work that is supposed to replace `node_health_check` with SD in the scylla packages and we need more than just running SD CI (which happens automatically anyway).

We need to see how we integrate that CI with the automation you have so that we test the latest SD with the scylla-version-under-test.

Today the CI we have uses a specific Scylla version.
