### ISSUE TITLE
[packaging] scylla-native tools cannot be installed alongsined existing scylla

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16292]
Tools are included in the scylla executable and hence are deployed together with the scylla-server package.
This makes it hard to deploy the latest-and-greatest tool on a scylla-node running an older version of scylla.
We should explore possibilities of allowing installing the latest tools package, alongside an existing scylla, in a non-intrusive way.

**Comment by avikivity** [comment]
> Dockerize them?

No please no

**Comment by avikivity** [comment]
We have tarball install.sh, can be used for to install any version with no privileges.

**Comment by denesb** [comment]
> We have tarball install.sh, can be used for to install any version with no privileges.

Can it install to arbitrary prefixes? I also thought about `install.sh` but my worry is if somebody runs it without parameters, they will overwrite the currently installed scylla.

**Comment by mykaul** [comment]
> > Dockerize them?
> 
> No please no

Are they statically linked as well? Otherwise, how are you going to solve dependencies?

**Comment by denesb** [comment]
Maybe we can look into https://www.man7.org/linux/man-pages/man1/systemd-nspawn.1.html?

> > > Dockerize them?
> > 
> > 
> > No please no
> 
> Are they statically linked as well? Otherwise, how are you going to solve dependencies?

We bundle all dependencies in the relocatable tarball. As long as it is installed to a separate prefix, two scyllas can coexist peacefully.

**Comment by avikivity** [comment]
> > We have tarball install.sh, can be used for to install any version with no privileges.
> 
> Can it install to arbitrary prefixes? I also thought about `install.sh` but my worry is if somebody runs it without parameters, they will overwrite the currently installed scylla.

```sh
./install.sh --prefix ~/blah
```

It will only overwrite if run as root, but the concern is justified. I suppose we can make install.sh refuse to overwrite if $prefix/bin/scylla exists (unless --force).

**Comment by denesb** [comment]
> But it's not Scylla, it's just the tools - so we need to bundle the dependencies for the tool in a relocatable tarball - not saying it can't be done of course, but it needs to.

The tools are compiled into the scylla executable.

**Comment by denesb** [comment]
I'm not sure we need to keep this open. In one investigation, we have successfully installed a recent scylla-master based scylla-sstable, via the non-root install. It worked fine. I think the `--root` and `--prefix` flags of `install.sh` are a bit confusing, maybe we should work on those, but other than that, it worked.
