### ISSUE TITLE
Create tablet-based keyspaces by default when tablets feature is enabled

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16319]
Currently, tablets need to be enabled per-keyspace by specifying the `initial_tablets` option, e.g.:

```
CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3, 'initial_tablets': 100};
```

We want keyspaces to be tablet-based by default when "tablets" experimental feature is enabled, and allow users to opt-out from it on per-keyspace basis via option:  `'tablets': false`.

This will make it easier to run all tests with tablets, by simply flipping the switch. Also, we want to make tablets enabled by default in the future, and not require users to opt-in in their DDL statements to use tablets.  

Only `NetworkTopologyStrategy` currently supports tablets, so other strategies will remain vnode-based.

When 'initial_tablets' is not provided, it's chosen by the system based on current topology and RF so that all shards are covered:

```
initial_tablets = max(nr_shards_in(dc) / RF_in(dc) for dc in datacenters)
```

**Comment by tgrabiec** [comment]
See https://github.com/scylladb/scylla-ccm/pull/510/commits/fe3b917e73b9ac013327736f83c50d146ea31d52

**Comment by nyh** [comment]
Although I agree we should do this and even suggested it (in https://github.com/scylladb/scylladb/issues/16203#issuecomment-1830165333), we should think what we plan that will happen if we want to GA tablets before we have 100% of the non-experimental features, including **CDC**, working with tablet. Or, we do plan to fix CDC before GAing tablets?

**Comment by avikivity** [comment]
CREATE KEYSPACE should emit a warning about missing features. The user can then delete it and retry with tablets disabled.

**Comment by tgrabiec** [comment]
> CREATE KEYSPACE should emit a warning about missing features. The user can then delete it and retry with tablets disabled.

https://github.com/scylladb/scylladb/issues/16807
