### ISSUE TITLE
Docker: can not connect to Scylla 5.4 with CQLSh

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#16329]
Scylla version (or git commit hash): 5.4.0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

```
docker run -p 8000:8000 --name some-scylla -d scylladb/scylla:5.4 --smp 1 --memory 750M --overprovisioned 1
 docker exec -it some-scylla cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
```

I did not see anything interesting in the logs; look like init completed successfully 
```
...
INFO  2023-12-07 11:45:34,502 [shard 0:stre] schema_tables - Creating system_auth.role_attributes id=6b8c7359-a843-33f2-a1d8-5dc6a187436f version=a6a35437-a861-3131-8d80-00621a022d17
INFO  2023-12-07 11:45:34,507 [shard 0:stre] schema_tables - Schema version changed to b423fd25-a353-3ac8-bdc6-f72dbeb8f51b
INFO  2023-12-07 11:45:34,508 [shard 0:main] init - starting batchlog manager
INFO  2023-12-07 11:45:34,508 [shard 0:main] init - starting load meter
INFO  2023-12-07 11:45:34,508 [shard 0:main] init - starting cf cache hit rate calculator
INFO  2023-12-07 11:45:34,508 [shard 0:main] init - starting view update backlog broker
INFO  2023-12-07 11:45:34,508 [shard 0:main] init - Waiting for gossip to settle before accepting client requests...
INFO  2023-12-07 11:45:34,508 [shard 0:main] standard_role_manager - Created default superuser role 'cassandra'.
INFO  2023-12-07 11:45:46,508 [shard 0:main] gossip - No gossip backlog; proceeding
INFO  2023-12-07 11:45:46,508 [shard 0:main] init - allow replaying hints
INFO  2023-12-07 11:45:46,508 [shard 0:main] init - Launching generate_mv_updates for non system tables
INFO  2023-12-07 11:45:46,508 [shard 0:main] init - starting the view builder
INFO  2023-12-07 11:45:46,509 [shard 0:main] init - starting native transport
INFO  2023-12-07 11:45:46,509 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 172.17.0.2:9042 (unencrypted, non-shard-aware)
INFO  2023-12-07 11:45:46,509 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 172.17.0.2:19042 (unencrypted, shard-aware)
INFO  2023-12-07 11:45:46,509 [shard 0:main] init - serving
INFO  2023-12-07 11:45:46,509 [shard 0:main] init - Scylla version 5.4.0-0.20231205.58a89e7a4231 initialization completed.
```

**Comment by fruch** [comment]
scylla should be reachable on 127.0.0.1 from within the docker
since ever the default of cqlsh is 127.0.0.1.

@mykaul the code you are referring is when cqlsh is running on the host, so 127.0.01 can't work.

I think something has changed in scylla or in the docker image of scylla... not sure what.

**Comment by fruch** [comment]
Found the reason 
```
9dc8c219804 (T Jake Luciani       2015-07-13 09:41:18 -0400  262) OLD_CONFIG_FILE = os.path.expanduser(os.path.join('~', '.cqlshrc'))
9dc8c219804 (T Jake Luciani       2015-07-13 09:41:18 -0400  263) if os.path.exists(OLD_CONFIG_FILE):
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  264)     if os.path.exists(CONFIG_FILE):
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  265)         print '\nWarning: cqlshrc config files were found at both the old location (%s) and \
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  266)                 the new location (%s), the old config file will not be migrated to the new \
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  267)                 location, and the new location will be used for now.  You should manually \
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  268)                 consolidate the config files at the new location and remove the old file.' \
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  269)                 % (OLD_CONFIG_FILE, CONFIG_FILE)
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  270)     else:
8ffeebff631 (Tyler Hobbs          2015-08-07 15:34:16 -0500  271)         os.rename(OLD_CONFIG_FILE, CONFIG_FILE)
```

we for the last 7 year, writing the cqlshrc into the deprecated location, 
and once we took latest and greatest cqlsh code, that compatibility code was gone.

we should move it from `~/.cqlshrc` to  `~/.cassandra/cqlshrc`

**Comment by RoDmitry** [comment]
#3219 is a bit related

**Comment by fruch** [comment]
> cqlsh change? How come we didn't see it earlier? 

Cause this configuration is set only for docker specific, so no test code is counting on that fact, and specify the exact address (both ccm, and SCT)

Basically almost no one plays manually with unreleased docker images.

People noticed it right after the first release that has it

**Comment by mykaul** [comment]
So we are not doing the most basic test for our docker images nightly?
Isn't that also an artifact worth testing, before the release?

**Comment by fruch** [comment]
since around 2018 when there were multiple places calling cqlsh like
```
node.remoter.run('cqlsh -e "{}" {}'.format(cmd, node.private_ip_address), verbose=True)
```

till today that there once function called `run_cqlsh`, that still specify the host to use.

why ?, I don't know, it didn't made any issues, no one noticed, till now.

**Comment by fruch** [comment]
reading this commit description 😭, I did add a check for the switch to scylla-cqlsh ...
https://github.com/scylladb/scylla-cluster-tests/commit/335432fadc74bd16130fd6428155651d2a665027

but I counted on `run_cqlsh` function to be correct

**Comment by mykaul** [comment]
@fruch - is https://github.com/fruch/scylla/commit/7ef3f70d89bac474826a380b8a5440f045cd1771 the fix for this?

**Comment by fruch** [comment]
> @fruch - is https://github.com/fruch/scylla/commit/7ef3f70d89bac474826a380b8a5440f045cd1771 the fix for this?

Yes the fix is:
https://github.com/scylladb/scylladb/pull/16340

But I didn't get to test it yet.
Can't build the docker locally anymore

**Comment by mykaul** [comment]
@scylladb/scylla-maint - please backport to 5.4 (so we'll be able to include it in 5.4.1)

**Comment by denesb** [comment]
Backported to 5.4.
