### ISSUE TITLE
raft topology: Joining node may hang if there are dead node in the cluster while it is joining.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#16333]
Scylla version (or git commit hash): d1aaca893c892241939fb436d5eeb1f9d7038819

If a joining node fails on _gossiper.wait_alive during accept processing is will return the error to the coordinator and hang while the coordinator  will print  `storage_service - raft topology: attempt to send acceptance response to 445e1849-ef83-4fb7-ae6e-218f3aa6ae57 failed: Failed to mark node as alive in 30000 ms, nodes={127.145.243.2, 127.145.243.3, 127.145.243.1}, live_nodes={127.145.243.2, 127.145.243.3}. The node may hang. It's safe to shut it down manually now.` But new node knows that join failed so it should exit.

**Comment by mykaul** [comment]
Subject is probably wrong - should be dead node in the cluster.

**Comment by gleb-cloudius** [comment]
> Subject is probably wrong - should be dead node in the cluster.

Probably.

**Comment by kbr-scylla** [comment]
The original subject was funnier.
