### ISSUE TITLE
Tablet load balancer should not try to balance nodes which are known to be down

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16372]
Scheduling migrations when we know that one of the nodes is down is pointless because the migration will get stuck anyway.

This also applies to future repair transitions. It's better to schedule repair transitions which can succeed now, and later get back to those which involve the down node.

This issue is pointless before we make the tablet metadata barrier require only affected node (tablet replicas). Currently, the barrier requires all nodes to acknowledge, so if there is a node down then all tablet transitions will be stuck.

This is an optimization.

**Comment by xemul** [comment]
@tgrabiec , isn't it fixed by e5dcf03b88154fb77b6c1cfcd61a561ed70e1e37 already?

https://github.com/scylladb/scylladb/blob/7d31093d4bde6753eb2d30aed46a1435869d52f9/service/tablet_allocator.cc#L618-L621

**Comment by tgrabiec** [comment]
> @tgrabiec , isn't it fixed by [e5dcf03](https://github.com/scylladb/scylladb/commit/e5dcf03b88154fb77b6c1cfcd61a561ed70e1e37) already?
> 
> https://github.com/scylladb/scylladb/blob/7d31093d4bde6753eb2d30aed46a1435869d52f9/service/tablet_allocator.cc#L618-L621

No, this issue is about down nodes, which are still members and are not excluded. The patch filters excluded nodes. Excluded nodes are those which are permanently down after they are marked as such with removenode/replace.
