### ISSUE TITLE
Drop keyspace name from primary key of system.tablets

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16377]
It's causing friction and is not useful so we should drop it.

Example friction:

```

    void generate_migration_update(std::vector<canonical_mutation>& out, const group0_guard& guard, const tablet_migration_info& mig) {
        auto s = _db.find_schema(mig.tablet.table);
        auto& tmap = get_token_metadata_ptr()->tablets().get_tablet_map(mig.tablet.table);
        auto last_token = tmap.get_last_token(mig.tablet.tablet);
        if (tmap.get_tablet_transition_info(mig.tablet.tablet)) {
            slogger.warn("Tablet already in transition, ignoring migration: {}", mig);
            return;
        }
        out.emplace_back(
            replica::tablet_mutation_builder(guard.write_timestamp(), s->ks_name(), mig.tablet.table)
                .set_new_replicas(last_token, replace_replica(tmap.get_tablet_info(mig.tablet.tablet).replicas, mig.src, mig.dst))
                .set_stage(last_token, locator::tablet_transition_stage::allow_write_both_read_old)
                .build());
    }
```

We lookup schema only to extract the keyspace name which we need to pass to tablet_mutation_builder in order to build a primary key.

**Comment by bhalevy** [comment]
@tgrabiec how important to get this fixed before first release?
It seems like it would be much harder to get rid of it once out.

Also, does it affect the client driver?

Cc @avelanarius @sylwiaszunejko

**Comment by sylwiaszunejko** [comment]
> Also, does it affect the client driver?
> 
> Cc @avelanarius @sylwiaszunejko

Drivers does not rely on information in system.tablets; the only way the drivers are informed about tablets is in the `custom_payload` part of RESULT message. So, I don't think they are affected at all.

**Comment by nyh** [comment]
@tgrabiec I hope that you're suggesting (it's not clear...) just to take out the `keyspace_name` out of the key, but still leave it as a regular column. Because it's useful as a field - I used it in test/topology_experimental_raft/test_mv_tablets.py, get_tablet_replicas() the ability to look up the tablets by `keyspace_name` and `table_name`, **not** table id.  I don't mind that `keyspace_name` gets taken out of the primary key - it wasn't useful there (since I don't have the entire key anyway), just please leave it as a regular column.

**Comment by tgrabiec** [comment]
> @tgrabiec I hope that you're suggesting (it's not clear...) just to take out the `keyspace_name` out of the key, but still leave it as a regular column. Because it's useful as a field - I used it in test/topology_experimental_raft/test_mv_tablets.py, get_tablet_replicas() the ability to look up the tablets by `keyspace_name` and `table_name`, **not** table id. I don't mind that `keyspace_name` gets taken out of the primary key - it wasn't useful there (since I don't have the entire key anyway), just please leave it as a regular column.

Yes.

**Comment by tgrabiec** [comment]
> @tgrabiec how important to get this fixed before first release? It seems like it would be much harder to get rid of it once out.
> 

Yes, we should do it before the release.

**Comment by denesb** [comment]
I will look into this.

**Comment by denesb** [comment]
> Yes, we should do it before the release.

If we want to do it, the only possible time is before the release. Changing key schema is not possible at all. We can still do it because there is no backward compatibility requirement.
