### ISSUE TITLE
CQL LSI promises about synchronous view updates should match implementation

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16371]
Today, Scylla's documentation promises that our CQL extension of "local secondary indexes" (LSI) provide **synchronous view updates**. The document docs/cql/cql-extensions.md claims that regular ("global") secondary indexes can be requested to be synchronous but for local secondary indexes (created using a ScyllaDB extension to CQL) this is the default:

> Local secondary indexes already have synchronous updates, so there's no need to explicitly mark them as such.

The official LSI documentation in docs/using-scylla/local-secondary-indexes.rst also says:

> As of Scylla Open Source 4.0, updates for local secondary indexes are performed **synchronously**. When updates are synchronous, the client acknowledges the write operation only **after both** the base table modification **and** the view up
date are written. This is important to note because the process is no longer asynchronous and the modifications are immediately reflected in the index. In addition, if the view update fails, the client receives a write error.

This is **no longer true** with tablets. With tablets, base and view tablet replication is not guaranteed to be the same, so view updates are not always local, and the serendipitous ("implicit") synchronous updates  no longer happen. So now we have two options:

1. Change the documentation to match the implementation. I.e., remove the promises of synchronous updates in CQL LSI in the aforementioned (and any more?) documents. This is we did for CQL materialized views in https://github.com/scylladb/scylladb/pull/16369

2. Change the implementation to match the documentation. I.e., leave the promise of synchronous updates, and enable the `synchronous_updates=true` option on the view created to back the LSI. This is what we did for Alternator LSI in https://github.com/scylladb/scylladb/pull/16353 - because the DynamoDB API requires that updates be synchronous (i.e., support a strongly-consistent read immediately after write).

The main question we need to ask ourselves is why we added the concept of LSI to Scylla as a CQL extension. If consistency is part of the story - the ability to read from the index immediately after a write - then we should choose option 2. I also lean towards option 2.

However, please note that option 2 implies a performance compromise - we no longer benefit from **local** updates that we had in the past and improved performance, and to make things even worse, we make updates synchronous and increase latency further. However, if in the future we implement a feature where base and view tablets can migrate together, we will win this performance back.

**Comment by nyh** [comment]
I have decided to go with option 2 (change the implementation to match the documentation) - if you disagree please speak now or forever hold you peace ;-) 
My reasoning is that the synchronous updates might be considered by some reasons a _correctness_  feature, the ability to read what you wrote (in this case, reading using the index). I assume (I wasn't part of our CQL LSI design) it was done and mentioned prominently in the documentation for the same reason that DynamoDB allows strongly-consistent reads in its LSI.

There is a good question why LSI should get synchronous-updates by default but ordinary SI should not. The reason why both DynamoDB and our vnodes implementation provided this feature for LSI but not GSI was that it's efficient and risk-free to give this feature to LSI (where view updates are local) but was less efficient and more risky to give it for GSI (with remote view updates). With tablets, giving this feature for LSI as I plan to do now is also inefficient and risky (in the sense of remove view updates), BUT, we have an option to later fix those issues by migrating LSI view tablets to be with their base tablets. Doing that is already on our plan, as optional step 12 (@avikivity liked the co-locating tablets idea, @kostja didn't).

**Comment by kostja** [comment]
I don't mind either way but it's a different set of follow-up measures for each decision. For making them synchronous, we'll have to do the performance testing, obviously, and warn users in the change notes.

**Comment by nyh** [comment]
Writing a test for this issue exposed the fact that we can't even create a SI with tablets (MV works, but not SI)!
I opened https://github.com/scylladb/scylladb/issues/16396 and it will need to be solved first.
