### ISSUE TITLE
Validate replication strategy constraints in tablet-moving API 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16379]
There is a RESTful API to move tablet replica: `/storage_service/tablets/move`. It should validate replication strategy constraints:

- replicas are not on the same node
- replicas don't move across DC (violates RF in each DC)
- availability is not reduced due to rack overloading

We should also add a switch to force the move anyway (except for the first constraint, which is hard)

**Comment by bhalevy** [comment]
Cc @denesb

**Comment by denesb** [comment]
Tablets related change, no backports required.
