### ISSUE TITLE
tasks: dangling reference to task's child pointer

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#16380]
While iterating over `tasks::task_manager::task::impl::_children` vector, 
references to its elements are used. If iteration preempts, new element
may be added to the vector. If its new `size()` is greater than old `capacity()`
then the references are invalidated.

**Comment by denesb** [comment]
@Deexie do we need to backport this?

**Comment by Deexie** [comment]
> @Deexie do we need to backport this?

Yes, to 5.2 and 5.4

**Comment by mykaul** [comment]
> > @Deexie do we need to backport this?
> 
> Yes, to 5.2 and 5.4

@Deexie - please prepare them.

**Comment by Deexie** [comment]
Done, it cherry picks without conflicts to 5.4

**Comment by denesb** [comment]
Backported to 5.4 and 5.2.
