### ISSUE TITLE
test.py: One failing artifact will stop the entire run

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#16389]
This was discovered (accidentally) when trying to move to graceful shutdown of clusters on cleanup.
When one of the artifacts raises an exception, it will stop the entire testing loop and some unrelated tests
appears as failing.

Ways to reproduce:
1. Add a "raise" statement in one of the artifacts functions -for example the stop method PythonTestSuite

**Comment by eliransin** [comment]
Fix in a few minutes

**Comment by kostja** [comment]
We found a different way to address this, closing.
