### ISSUE TITLE
Make TRUNCATE TABLE safe with tablets

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16411]
TRUNCATING a table works by issuing an RPC to all the nodes which call `database::truncate_table_on_all_shards()`, which makes sure that older writes are dropped. 

It works with tablets, but is not safe.

A concurrent replication process may bring back old data. There is already such a background process, batchlog replay. There is attempt to handle it by keeping truncation timestamp per table (table::get_truncation_time()), which batchlog replay checks and drops mutations if they are older. It seems to me that this is prone to races, so it's not fully robust.

Repair is another process, but it's currently controlled by the admin. 

Tablet migration is another background process which can bring back old writes if it happens concurrently with truncation. 

The safest option is to make truncation a topology operation, so that it excludes with other processes in the system which could interfere with it (also repair). That will take care of tablet migration and background repair.

**Comment by avikivity** [comment]
I like the token-range tombstone solution, it makes truncate super-fast (doesn't need to wait for anything, including memtable flushes).

**Comment by bhalevy** [comment]
> I like the token-range tombstone solution, it makes truncate super-fast (doesn't need to wait for anything, including memtable flushes).

Me too.

I think there are 2 orthogonal issues:
1. Coordination - move from the truncate rpc call to a topology operation that can be coordinated by the tablets scheduler
2. Implementation of truncate at the comapction_group level. Current clumsy method that uses the trunated_at time point to delete sstables vs. a token range tombstone that carries a write timestamp which logically deletes any data written before this timestamp and deletion is done in the background by compaction. (See aslo #11230)

**Comment by bhalevy** [comment]
@michoecho please add to your queue post zstd RPC compression

**Comment by avikivity** [comment]
> > I like the token-range tombstone solution, it makes truncate super-fast (doesn't need to wait for anything, including memtable flushes).
> 
> Me too.
> 
> I think there are 2 orthogonal issues:
> 
> 1. Coordination - move from the truncate rpc call to a topology operation that can be coordinated by the tablets scheduler

With a token-range tombstone, it's not a topology operation. It becomes a QUORUM operation on all tokens.

```python
def truncate(ts, cl):
    for t in tablets:
        storage_proxy.truncate_range(t.range, cl)
```

Now it works for LOCAL_QUORUM - truncate succeeds if only the local datacenter is available.

It probably doesn't matter in practice, but the idea is that truncate is a data-plane operation like INSERT or UPDATE, not a DDL operation.

> 2. Implementation of truncate at the comapction_group level. Current clumsy method that uses the trunated_at time point to delete sstables vs. a token range tombstone that carries a write timestamp which logically deletes any data written before this timestamp and deletion is done in the background by compaction. (See aslo [Truncate must be based on a tombstone #11230](https://github.com/scylladb/scylladb/issues/11230))

**Comment by dani-tweig** [comment]
During Q2 we shall reach a decision of the way we want to solve this issue.
One of the solution candidates would be to disable the tablet load balancer before the TRUNCATE, and resume it after the operation is done.
The implementation itself is currently planned for Q3.

**Comment by nodep** [comment]
I made a draft design document listing the currently proposed solutions to TRUNCATE TABLE:
https://docs.google.com/document/d/1o9JO2a9eS7auLFMEngO74d_k6Gg0B1iiH593GaOKU3Y

**Comment by mykaul** [comment]
> I made a draft design document listing the currently proposed solutions to TRUNCATE TABLE: https://docs.google.com/document/d/1o9JO2a9eS7auLFMEngO74d_k6Gg0B1iiH593GaOKU3Y

Now that it is agreed upon, it should be moved to docs/dev
