### ISSUE TITLE
gossiper::add_saved_endpoint uses the local heart_beat_state if the ep_state already exists

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16429]
This issue stems from @tgrabiec's observation in https://github.com/scylladb/scylladb/pull/15788/files#r1428382450

Currently, when loading peers' endpoint state from system.peers, `add_saved_endpoint` is called.
The first instance of the endpoint state is created with the default `heart_beat_state`, with both generation and version set to zero.
However, if `add_saved_endpoint` finds an existing instance of the endpoint state, it reuses it, but it updates its heart_beat_state with the local `heart_beat_state()` rather than keeping the existing `heart_beat_state`, as it should.

See https://github.com/scylladb/scylladb/blob/10a11c2886cffb99f1be06fd5bf1920d5b0953b6/gms/gossiper.cc#L2086-L2092

This is a problem since it may confuse updates over gossip
later on via do_apply_state_locally that compares the remote
generation vs. the local generation, so they must stem from
the same root that is the endpoint itself.

Refs https://github.com/scylladb/scylladb/issues/15787

**Comment by tgrabiec** [comment]
The description doesn't explain why this is a problem.

**Comment by bhalevy** [comment]
@tgrabiec I've also been about this further.
It's possible to call add_saved_endpoint multiple times before gossip is started, but once we have an endpoint_state that we retrieved from that node, that will have a non-zero generation, should we even update it with local information from system.peers?

**Comment by tgrabiec** [comment]
> @tgrabiec I've also been about this further. It's possible to call add_saved_endpoint multiple times before gossip is started, but once we have an endpoint_state that we retrieved from that node, that will have a non-zero generation, should we even update it with local information from system.peers?

It's impossible to tell without storing the gossip generation and versions locally. Our local view may be older, or it may be more recent. If it's older, we should drop our local updates. If it's more recent, we should use our local state to preserve monotonicity of local history.

To properly restore gossip state, we should properly persist it (with generation and versions).

**Comment by asias** [comment]
> @tgrabiec I've also been about this further. It's possible to call add_saved_endpoint multiple times before gossip is started, but once we have an endpoint_state that we retrieved from that node, that will have a non-zero generation, should we even update it with local information from system.peers?

Nodes that are injecting gossip state for other nodes should only inject generation with zero. Never injecting non-zero generation state for other nodes. If the node that is going to inject gossip state see an existing non-zero generation state, it should stop injecting, because the 'real' node has come alive.

**Comment by bhalevy** [comment]
> > @tgrabiec I've also been about this further. It's possible to call add_saved_endpoint multiple times before gossip is started, but once we have an endpoint_state that we retrieved from that node, that will have a non-zero generation, should we even update it with local information from system.peers?
> 
> Nodes that are injecting gossip state for other nodes should only inject generation with zero. Never injecting non-zero generation state for other nodes. If the node that is going to inject gossip state see an existing non-zero generation state, it should stop injecting, because the 'real' node has come alive.

Agreed.  This is done in https://github.com/scylladb/scylladb/commit/3c30ec23a0e0d224dc04abdcffb05f71eb9feae9

**Comment by kbr-scylla** [comment]
In the discussion you linked, @tgrabiec says that the state must be set to generation 0.
@bhalevy you agree with him and disagree at the same time

> You're right. It should reuse ep_state.get_heart_beat_state()

"You're right" contradicts "It should reuse ep_state.get_heart_beat_state()"

Reusing ep_state.get_heartbeat_state() is not equal to using generation 0.

In the issue description you say

>  However, if add_saved_endpoint finds an existing instance of the endpoint state, it reuses it, but it updates its heart_beat_state with the local heart_beat_state() rather than keeping the existing heart_beat_state, as it should.

"as it should" **why?**

What is wrong with using generation 0 and version 0 (which is what `heart_beat_state()` returns)?

@tgrabiec claims that is the correct thing to do. And that's also what makes sense to me. If we add update another node's state inside gossiper on behalf of it, we should use gen=0 ver=0, so we don't accidentally overwrite a newer state that originates from this node.

And that is what the current code does.

Furthermore, @asias said
> If the node that is going to inject gossip state see an existing non-zero generation state, **it should stop injecting**, because the 'real' node has come alive.

(emphasis mine)

then you say
> Agreed. This is done in https://github.com/scylladb/scylladb/commit/3c30ec23a0e0d224dc04abdcffb05f71eb9feae9

agreeing, then pointing to a commit which contradicts @asias. The commit does not stop injecting, it keeps injecting, overwriting whatever state is present in gossiper with local information -- without setting gen=0 ver=0.

So with this, there's a possible that two nodes have different states for a given peer, but with the same non-zero generation and version. How is collision resolved when they gossip with each other?

I am extremely confused.

**Comment by kbr-scylla** [comment]
> agreeing, then pointing to a commit which contradicts @asias. The commit does not stop injecting, it keeps injecting, overwriting whatever state is present in gossiper with local information -- without setting gen=0 ver=0.

Hmm, sorry, now I see the `get_generation()` + `on_internal_error_noexcept` check.

So the code would have injected only when generation is 0...

**Comment by kbr-scylla** [comment]
> So the code would have injected only when generation is 0...

In that case, assuming the on_internal_error is not being triggered, isn't the previous code (which sets generation == 0 and injects state) equivalent to the new code from https://github.com/scylladb/scylladb/pull/16432 (which asserts generation == 0 and injects state)? In that case, what's the point of the change?
