### ISSUE TITLE
Allow concurrent tablet migration in the storage_service/tablets/move RESTful API

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16437]
Currently it waits for topology state machine to be idle, so it allows one tablet to be moved at a time. We should allow it to start migration if the current transition state is `topology::transition_state::tablet_migration` or `topology::transition_state::tablet_draining` to allow starting parallel tablet movement. That will be useful when scripting a custom rebalancing algorithm.

**Comment by bhalevy** [comment]
@tgrabiec I've just assigned this ticket to @tchaikov 
Have you already started working on it?

**Comment by tgrabiec** [comment]
> @tgrabiec I've just assigned this ticket to @tchaikov Have you already started working on it?

No, I haven't.

**Comment by denesb** [comment]
Tablets related change, no backports required.
