### ISSUE TITLE
Friendler error message when trying to use tablets when the experimental feature isn't turned on

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16467]
Right now, if the `tablets` experimental option is turned off, and you try to create an Alternator table with tablets (by setting the `initial_tablets` tag), you will get:

```
Internal server error: exceptions::configuration_exception (Tablet replication is not enabled)
```

A friendlier request should be an Invalid Request (which won't be retried), not an Internal Server Error. It will also be good for the error message to explain how to enable tablets - not just that it's not enabled.

I'm guessing (but didn't check) that in CQL when creating a keyspace we also get the "configuration exception" although there this exception probably translates to a good CQL error. But even then, I think the error text can be improved by referring to specific experimental feature that is not enabled.

**Comment by nyh** [comment]
This issue will become moot, and can be closed, if my pull request https://github.com/scylladb/scylladb/pull/16900 is merged. In that pull request, the code (see https://github.com/scylladb/scylladb/pull/16900/commits/a53eef451408aa4239aa8f99eec35b9f936157dd) begins by checking if the "tablets" experimental feature is on. If it is off, initial_tablets is not used - no matter what tag the user used. If it is on, that PR also changes the default - tablets are now enabled by default and the tag can be used to avoid them.

**Comment by bhalevy** [comment]
@nyh? https://github.com/scylladb/scylladb/pull/16900 was merged so can this issue be closed?
