### ISSUE TITLE
Skip large-cluster topology tests in debug mode, automatically

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16465]
Starting a large, even large-ish cluster in a debug build takes a ridiculous amount of time: In https://github.com/scylladb/scylladb/issues/16423#issuecomment-1862521778 @kbr-scylla reported that starting a 10-node cluster took a whopping 26 minutes.

This is why we have an unofficial policy (which @avikivity spoke against) of skipping those tests on debug mode. The way this is currently done is to list these tests in test/topology_experimental_raft/suite.yaml in the "skip_in_debug" section. This way is error prone:
1. Someone can forget to mark new tests as being skip_in_debug - this is what caused https://github.com/scylladb/scylladb/issues/16423.
2. As tests move or change, this information can become out-of-date.

A much more reliable and easier solution is to modify the `manager.add_servers()` method to check if the number of nodes is greater than some threshold (e.g., 4), it will call `pytest.skip()` if running in debug mode. Automatically. No need for the "skip_in_debug" manual list.

**Comment by kbr-scylla** [comment]
I think developers should be aware that a certain test case is skipped in debug. They should be making an educated decision, consciously, after weighting cons and pros.

**Comment by nyh** [comment]
> I think developers should be aware that a certain test case is skipped in debug. They should be making an educated decision, consciously, after weighting cons and pros.

I don't agree. There is no "educated decision" involved in not running a 7-node test in debug mode but running a 3-node test there. I think this is basically @avikivity's point - there is no good rationale why we should run just one of those - not neither and not both - in debug mode. It's just a framework-related tradeoff - what we can **afford** to run.

In my view, tests themselves shouldn't even know or care if they run in debug or dev or release builds. The decision whether to run the test on all three build modes or just one belongs to the operator who runs the tests (Jenkins) or the test framework, not to the individual test.

Anyway, I listed specific reasons why I think this decision should be done automatically, at the framework level, and not in a separate "suite.yaml" file. It really causes problems. We had both problems I mentioned (moved test and forgotten-to-blacklist test) just in the last week. And my proposal will fix it all automatically!

**Comment by nyh** [comment]
By the way, another reason why skip_in_debug that we have to today is very wrong is that it works in the wrong granularity: It works in the level of a whole file. We shouldn't be skipping entire test files just because one test function needs a 7-node cluster!

**Comment by kbr-scylla** [comment]
Nobody's defending the suite.yaml skip_in_* thing.

We have a better alternative, the `skip_mode` marker.

**Comment by nyh** [comment]
> Nobody's defending the suite.yaml skip_in_* thing. Since recently we have a better alternative, the `skip_mode` marker.

It's indeed better (I wish I knew about it 10 minutes ago), but also a mistake (and now I remember I said the same thing about the "release mode" skipping for injection). Imagine how much frustration both of us could have avoided if the problematic test would have been skipped automatically in debug mode instead of needing to discover this during next promotion.

**Comment by temichus** [comment]
@nyh , here I agree with @kbr-scylla I don't think that it is a good idea to have some mechanism that dynamically adds/removes tests from runs based on any checks/algorithms, especially in unit tests.  Developers should be aware that a certain test case is skipped in debug or not 
cc @kostja

**Comment by nyh** [comment]
@temichus please note that the discussion isn't about adding or removing tests - it's about optionally not running some of the tests in some of the build modes.
Arguably, the fact that tests run on multiple build modes is already outside the decision of the test author - it's not the test that says it should run on release, debug and dev builds - it's Jenkins and/or test.py which decides to do it.

Anyway, once I realized that it was possible to skip-in-debug an individual test in this test's source code, and not just in test/topology_experimental_raft/suite.yaml, there isn't much need for this issue and I'll close it. I think the "skip_in_debug" et al. lists in test/topology_experimental_raft/suite.yaml should be removed and this information should be moved into the tests themselves, but this is a different issue.
