### ISSUE TITLE
raft topology: hot retry loops and missing rollback

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16461]
There are some places in topology coordinator code where failure may lead to a hot retry loop -- retries without any sleeps in between -- which causes a log spam, which may lead to the node running out of disk space or losing relevant useful logs (if it's truncating logs that become too long). It's also a problem in CI, the node is spamming until the test timeouts and we end up with a log file with many GBs in size to download and investigate.

Furthermore, some places don't enter rollback state on failure when they should.

`commit_cdc_generation` state is one such example of both problems:
```cpp
            case topology::transition_state::commit_cdc_generation: {
                // make sure all nodes know about new topology and have the new CDC generation data
                // (we require all nodes to be alive for topo change for now)
                // Note: if there was a replace or removenode going on, we'd need to put the replaced/removed
                // node into `exclude_nodes` parameter in `exec_global_command`, but CDC generations are never
                // introduced during replace/remove.
                {
                    auto f = co_await coroutine::as_future(exec_global_command(std::move(guard),
                        raft_topology_cmd::command::barrier,
                        {_raft.id()}));
                    if (f.failed()) {
                        slogger.error("raft topology: transition_state::commit_cdc_generation, "
                                      "raft_topology_cmd::command::barrier failed, error {}", f.get_exception());
                        break;
                    }
```

the `f.failed()` branch will cause us not to throw, but return `true` from `handle_topology_transition` function, causing the topology coordinator loop to retry immediately.

We should enter rollback if there's a failure there.

But generally we need to carefully review the code (go through all topology coordinator states) if there are any places that don't have correct failure handling.

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius

**Comment by mykaul** [comment]
Is anyone working on this for 6.0?

**Comment by kbr-scylla** [comment]
There were some fixes like bb22e06a9e42f904ef23629fddfce3e093422a4e and bf068dd0230417c670134d3ff4c3709f9e061076.

We need to review the code if there's anything left to do. @gleb-cloudius

**Comment by gleb-cloudius** [comment]
Code looks fine now. Lets close and open more specific issues if tests find something.

**Comment by kbr-scylla** [comment]
Nice, thanks.
