### ISSUE TITLE
Massive cql-pytest failures with tablets

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16473]
To run cql-pytest tests with tablets, use the following patch:

```patch
diff --git a/test/cql-pytest/run.py b/test/cql-pytest/run.py
index 2e342c372e..571c7ceabc 100755
--- a/test/cql-pytest/run.py
+++ b/test/cql-pytest/run.py
@@ -311,6 +311,8 @@ def run_scylla_cmd(pid, dir):
         # test/alternator/run.
         '--experimental-features=udf',
         '--experimental-features=keyspace-storage-options',
+        '--experimental-features=consistent-topology-changes',
+        '--experimental-features=tablets',
         '--enable-user-defined-functions', '1',
         # Set up authentication in order to allow testing this module
         # and other modules dependent on it: e.g. service levels

diff --git a/test/cql-pytest/conftest.py b/test/cql-pytest/conftest.py
index 3942a50d8f..9c05e87b3e 100644
--- a/test/cql-pytest/conftest.py
+++ b/test/cql-pytest/conftest.py
@@ -95,7 +95,7 @@ def this_dc(cql):
 @pytest.fixture(scope="session")
 def test_keyspace(cql, this_dc):
     name = unique_name()
-    cql.execute("CREATE KEYSPACE " + name + " WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', '" + this_dc + "' : 1 }")
+    cql.execute("CREATE KEYSPACE " + name + " WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', '" + this_dc + "' : 1, 'initial_tablets': '100' }")
     yield name
     cql.execute("DROP KEYSPACE " + name)
 ```
(the first change enables the tablets experimental feature, the second change enables "initial_tablets" on `test_keyspace`, which is used by most (though not all) tests.

Running test/cql-pytest/run results in a lot of successful tests, but also a lot of failures.

It appears that specific tests, like those in test_cdc.py or test_describe.py, evoke specific missing features in the tablets implementation, which worries me less.

What is more worrying is that it appears that in every large run of many of the test files, at some point **all** the tests start failing. The kind of errors we see are similar to those in https://github.com/scylladb/scylladb/issues/16468 - I see bad_allocs, I see during DROP TABLE or CREATE TABLE
```
Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1230): std::_Nested_exception<std::runtime_error> (Failed to read tablet metadata for table 9daabf00-9e96-11ee-a1af-101c4212d20a): exceptions::read_failure_exception (Operation failed for system.tablets - received 0 responses and 1 failures from 1 CL=ONE.)"
```

CC @tgrabiec

**Comment by nyh** [comment]
An interesting case is the test_describe.py:
1. The test `test/cql-pytest/run test_describe.py::test_desc_cluster` shows a real bug in DESC CLUSTER - which had `Tried to obtain per-keyspace effective replication map of cql_test_1703013935042 but it's per-table`. We should open a separate issue about this bug.
2.  The test `test_describe.py::test_whitespaces_in_table_options` fails and then all further tests in this file fail. If I understand correctly, this test tried to use CDC, which instead of just reporting an error (this is a known issue https://github.com/scylladb/scylladb/issues/16318), caused the Raft thread to exit (@tgrabiec is that possible?) and from there on, everything kept failing.

**Comment by nyh** [comment]
After the CDC failure is fixed (#16318) we are still left with a random failure in the middle of the large test suite, after which every single test fails. The log again has bad_allocs logged, and I suspect this is related. I think we have a memory leak somewhere, but don't have a proof yet.

**Comment by nyh** [comment]
I opened several issues about specific tablet-reltated bugs the cql-pytest exposed when running the tests one by one (in cdc, in DESC CLUSTER, SELECT FROM MUTATION FRAGEMENTS, and two other failing tests) but all cql-pytest tests pass when run individually. 

But when running many test sequentially on the same Scylla - the whole test suite or even one large test file (e.g., test_materialized_views.py) - Scylla consistently breaks down in the middle, and it always seems to involve a bad_alloc somewhere.

**Comment by kbr-scylla** [comment]
Memory leak?

Also this:
> exceptions::read_failure_exception (Operation failed for system.tablets - received 0 responses and 1 failures from 1 CL=ONE.)

Maybe there's a message in logs somewhere before, describing the replica-side reason of failure (coordinator reports only that it received failure from replica, but there are no details from the replica why it failed; this happens also for local reads where coordinator = replica, also in system tables)

**Comment by nyh** [comment]
It's hard to say what the real problem is - I get weird errors (in https://github.com/scylladb/scylladb/issues/16468 I gave more examples) when reading system.tablets but also system_auth.roles (!), but in every such case there is also a bad_alloc somewhere. I think we're really running out of memory (and I checked that increasing the 1MB to 2MB solves these problems).

I just now realized that **maybe** this isn't a leak, but rather really tablets are taking a lot of memory? Maybe 100 tablets is too many (I just copied the example "initial_tablets = 100" I saw once without thinking) and taking a lot of memory, that doesn't fit into 1MB of memory! I'll try this again with initial_tablets = 4 or something, and see if it helps.

**Comment by tgrabiec** [comment]
On Wed, Dec 20, 2023 at 3:22 PM nyh ***@***.***> wrote:

> It's hard to say what the real problem is - I get weird errors (in #16468
> <https://github.com/scylladb/scylladb/issues/16468> I gave more examples)
> when reading system.tablets but also system_auth.roles (!), but in every
> such case there is also a bad_alloc somewhere. I think we're really running
> out of memory (and I checked that increasing the 1MB to 2MB solves these
> problems).
>
> I just now realized that *maybe* this isn't a leak, but rather really
> tablets are taking a lot of memory? Maybe 100 tablets is too many (I just
> copied the example "initial_tablets = 100" I saw once without thinking) and
> taking a lot of memory, that doesn't fit into 1MB of memory! I'll try this
> again with initial_tablets = 4 or something, and see if it helps.
>

Tablet metadata takes some memory, but I suspect that majority of the
overhead comes from the fact that memtables are split at tablet boundaries,
and there is a fixed LSA overhead associated with that (LSA region is 128K,
so 100*128K = 12 MB).

**Comment by tgrabiec** [comment]
On Wed, Dec 20, 2023 at 3:27 PM Kamil Braun ***@***.***>
wrote:

> Tablet metadata taking so much memory? (I guess you meant 1GB, not 1MB).
> Then what will happen in larger clusters with millions (?) of tablets...
>
100k tablets take 12MB in memory:

build/dev/scylla perf-tablets -c1 -m1G --tables 100 --tablets-per-table=1024
testlog - Size of tablet_metadata in memory: 12814 KiB

There is memtable overhead, but that depends on per-shard tablet count so
it's spread across the cluster.

**Comment by nyh** [comment]
Yes, I meant 1G :-) (this is what test/cql-pytest/run.py uses by default). 

I can confirm that lowering the silly "initial_tablets = 100" I used to "initial_tablets = 4" completely solves the problem. So I will close this issue.

Scylla's handling of bad_alloc is disappointing. Most of the failures did NOT mention a bad_alloc at all. Only a few of the errors and a couple of log messages during the entire run of 100 failed tests mentioned bad_alloc. 

Anyway, I assume or hope that in the future the "initial_tablets" will be more wisely calculated, automatically, without asking the user to determine it. Then I assume that on my setup - with just two shards (one node and two CPUs) you won't choose 100 tablets, so I wouldn't have this problem.

**Comment by kbr-scylla** [comment]
Setting initial_tablets = 4 may be sweeping some real problem under the rug.

**Comment by nyh** [comment]
I'll open a new issue about this.
