### ISSUE TITLE
test.py: teardown may race with ongoing test operation, causing IPs to be released prematurely

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16472]
This is what @gleb-cloudius observed when developing a test for topology coordinator

The test was booting a node concurrently with removing another node (possible with raft-topology)
The remove failed and caused test teardown to start. Apparently, this teardown happened before the `ScyllaServer.start` function in the concurrent booting task assigned the `cmd` field, so during teardown, when the cluster was stopped, `stop()` saw `cmd = None` and did not kill the node. Then it released the node's IP, but the process actually just started using it.
This caused cascading test failures for tests that tried to reuse the IP.

We need to protect ourselves from such situations.

Most functions in the framework were most likely developed without such concurrency in mind. But we do want to test concurrent operations in Raft-based topology.

**Comment by temichus** [comment]
@gleb-cloudius, @kbr-scylla, Do you have a reproducer for this, some test example or an existing test?
I haven't worked with test.py but to deal with concurrent threads/await in Python you need to implement them properly(in this case action+ expected result checker, like start failed or succeed with the result)

Thread can't be killed (like process, kill and forget) only finished 
just cancelling the task is not an option here:  
Calling Task.cancel() does not cancel the task.
Calling Task.cancel() does not block until the task is canceled.
+ https://superfastpython.com/asyncio-task-cancellation-best-practices/#Practice_5_Dont_Cancel_a_Task_and_Wait_For_It_To_Cancel


so we can introduce some new fixtures that will be responsible for spawning/managing new coroutines that must finished at test teardown.
but as I mentioned before, these coroutines should be implemented properly. like it must be finished(as booting) or can be interrupted/canceled like 

again if you provide an example of the problem, we can implement these fixtures + coroutines for booting and removing actions that can be safe to use in parallel

then the list of actions can be extended by everyone based on examples

**Comment by temichus** [comment]
@kostja, I read issue/code one more time.

and I see that ```cmd``` it is already sync point between ```start``` ```stop``` and cmd filed as  ``` self.cmd = await asyncio.create_subprocess_exec``` almost at the beginning of coroutine ```start``` but it is not enougnt

as I understood, the problem happened when passing:
```
 await asyncio.gather(start, remove)
```
The remove runs first(because we can not guarantee order) failed and caused test teardown but the start is still running because cancelled only the client(test) coroutine. but server aiohttp task continues running

in other words, this is equal to call in test
```
await asyncio.gather(stop, start)
```

And I honestly don't know how to handle this situation in ScyllaServer/ScyllaCluster/ScyllaClusterManager because even if we try to store all active tasks in classes  in order to wait for them they still will be stored asynchronous and it will work the same as with```cmd```

to guarantee the ordering, we need to wait for all client/server  coroutines are finished and only then trigger teardown

for example  
```
 await asyncio.gather(start, remove,  return_exceptions=True)
```

or (if we wanted to be fast) try to cancel tasks on the server via 

add some new endpoint in aiohttp /cluster/server/{server_id}/run_together

to handle simultaneous operations and run them in asyncio.gather

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius, @kbr-scylla, Do you have a reproducer for this, some test example or an existing test? 

Sorry I missed it. I hit the problem when something inside  `test_coordinator_queue_management.py` failed (not remember what exactly) and after that the bunch of unrelated tests started to fail since the test exit without killing its cluster as far as I understand and following tests start to fail because they try to reuse IPs that are still in use.

**Comment by kbr-scylla** [comment]
@temichus I managed to create a reproducer
https://github.com/kbr-scylla/scylladb/commit/9551931e6ef2ac98112643e5a50deaacb2c2dfb5

The test is simple
```python3
from test.pylib.manager_client import ManagerClient
import pytest
import logging
import asyncio

logger = logging.getLogger(__name__)

@pytest.mark.asyncio
async def test_concurrent_tasks(manager: ManagerClient):
    srv = await manager.server_add()
    await manager.server_stop(srv.server_id)

    async def fail():
        await asyncio.sleep(0.01)
        pytest.fail()

    start_task = asyncio.create_task(manager.server_start(srv.server_id))
    fail_task = asyncio.create_task(fail())

    await asyncio.gather(*[start_task, fail_task])
```

but I also orchestrated some timings: in `ScyllaServer.start` increased the time between starting Scylla process and assigning it to `self.cmd`
```diff
diff --git a/test/pylib/scylla_cluster.py b/test/pylib/scylla_cluster.py
index 7144df3178..6f0b232921 100644
--- a/test/pylib/scylla_cluster.py
+++ b/test/pylib/scylla_cluster.py
@@ -418,7 +418,7 @@ class ScyllaServer:
         env = os.environ.copy()
         env.clear()     # pass empty env to make user user's SCYLLA_HOME has no impact
         env.update(self.append_env)
-        self.cmd = await asyncio.create_subprocess_exec(
+        tmp = await asyncio.create_subprocess_exec(
             self.exe,
             *self.cmdline_options,
             cwd=self.workdir,
@@ -427,6 +427,10 @@ class ScyllaServer:
             env=env,
             preexec_fn=os.setsid,
         )
+        self.logger.info("start sleep")
+        await asyncio.sleep(0.2)
+        self.logger.info("start sleep end")
+        self.cmd = tmp
 
         self.start_time = time.time()
         sleep_interval = 0.1
```

I also decreased the suite pool size on the branch just to reproduce it faster
```diff
diff --git a/test/topology_custom/suite.yaml b/test/topology_custom/suite.yaml
index 7f510fee46..6029430464 100644
--- a/test/topology_custom/suite.yaml
+++ b/test/topology_custom/suite.yaml
@@ -1,5 +1,5 @@
 type: Topology
-pool_size: 4
+pool_size: 1
 cluster:
   initial_size: 0
 extra_scylla_config_options:
```

now you just do
```
/test.py --mode dev test_concurrent_tasks --repeat 2 -s -v
```

and what happens is that we have two sequential runs (because pool size = 1, so they don't run concurrently), in the first run, the server is started and assigned to self.cmd **after** teardown already did stop() (because of the sleep in start()) so the process is left running. Then in the second run, the initial `server_add` fails because when the node tries to boot, it sees that IP is already in use.

**Comment by kbr-scylla** [comment]
> And I honestly don't know how to handle this situation in ScyllaServer/ScyllaCluster/ScyllaClusterManager because even if we try to store all active tasks in classes in order to wait for them they still will be stored asynchronous and it will work the same as withcmd

But creating and storing a task is not an async operation. I think your idea would work. So generally:
- tests would be required to start all concurrent tasks by dedicated `ManagerClient` member function, not through `asyncio.create_task`. So let's say `ManagerClient.create_task`
- this `ManagerClient.create_task` would ensure to synchronize teardown with task creation

so the question is how to synchronize teardown with task creation. I think it should be simple. Teardown always calls `ManagerClient.stop()` so `ManagerClient.stop` and `ManagerClient.create_task` could synchronize between each other. So We would have
- a boolean flag like `teardown` or `stopping` which would be set to true on teardown
- and some additional primitive for teardown to be able to wait on tasks that were already created (in seastar we have gate, in python we could invent something or perhaps there's an existing thing in standard library)

Then:
- `stop` would set the flag to True, then wait for existing tasks to finish
- `create_task` would first check the flag, if it's True then do nothing, if it's False then create the task.

Note that checking/setting the flag and creating task is done atomically because creating task does not require a yield.

**Comment by kbr-scylla** [comment]
And even if creating a task required a yield, we'd just need to introduce a lock around checking/setting flag and task creation in that case. (But we shouldn't need a lock.)

**Comment by temichus** [comment]
@xtrey, I've suggested "synchronization on server" because the initial issues mentioned race between 2 meant that performing an API call on server (start, remove)

but @kbr-scylla example as only coro 1 that call server and 2ns coro that fails just local. 
in this case, synchronization(waiting for all coro that spawned in the test) must be done in the test body or via some object/fixture if it will be some wrapper for gather()

**Comment by xtrey** [comment]
Draft PR https://github.com/scylladb/scylladb/pull/17781

**Comment by nyh** [comment]
Again, please don't "assign" issues to me that I'm not expected to work on. If you want me to **review** a **PR**, please add me as a reviewer to the PR, or ping me on the PR (by mentioning @nyh in a comment). Either method will remind me to go to the PR. Assigning the issue is the wrong signal.
