### ISSUE TITLE
test_read_repair takes 10 minutes in debug mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#16470]
```
$ ./test.py --mode debug test_read_repair -v
Found 1 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/1]      topology_custom  debug  [ PASS ] topology_custom.test_read_repair.1 539.96s
------------------------------------------------------------------------------
CPU utilization: 3.7%

```

**Comment by avikivity** [comment]
Takes 32 seconds in dev mode.

**Comment by avikivity** [comment]
and with a seastar patch, 232 seconds.

**Comment by denesb** [comment]
I don't know how to make this test faster. Actually, I know: implementing the `LOCAL_ONLY()` `CQL` extension for `SELECT` and `INSERT/UPDATE` would help greatly. The test currently generates sstables, then uploads them to nodes. Even this is faster than stopping/starting nodes, which was even more painfully slow.

**Comment by denesb** [comment]
Opened https://github.com/scylladb/scylladb/issues/16478 for this idea, AFAIK so far we only discussed in email.

**Comment by nyh** [comment]
> Opened #16478 for this idea, AFAIK so far we only discussed in email.

It was originally raised in https://github.com/scylladb/scylladb/issues/9042#issuecomment-1719744952

**Comment by avikivity** [comment]
> I don't know how to make this test faster. Actually, I know: implementing the `LOCAL_ONLY()` `CQL` extension for `SELECT` and `INSERT/UPDATE` would help greatly. The test currently generates sstables, then uploads them to nodes. Even this is faster than stopping/starting nodes, which was even more painfully slow.

It tries to overflow the page size, yes? Maybe run it with artificially lower limits?

**Comment by denesb** [comment]
> > I don't know how to make this test faster. Actually, I know: implementing the `LOCAL_ONLY()` `CQL` extension for `SELECT` and `INSERT/UPDATE` would help greatly. The test currently generates sstables, then uploads them to nodes. Even this is faster than stopping/starting nodes, which was even more painfully slow.
> 
> It tries to overflow the page size, yes? Maybe run it with artificially lower limits?

We have a hardcoded size-limit of 1MB, which this test tries to overflow, correct. For some time now, this limit is sent by the coordinator to replica nodes. If so, maybe we can make it configurable for tests.
Note that this will solve just one factor in the slowness.

**Comment by avikivity** [comment]
Clsoing as duplicate of #15425

**Comment by avikivity** [comment]
Seen again (on ARM, without scylladb/seastar@e0d515b6cf96129cebdcbb1b031df90eb815e7fa)


```
16:51:18  [9100/9100] topology_custom  debug  [ PASS ] topology_custom.test_read_repair.1 5097.49s
```

**Comment by avikivity** [comment]
> > > I don't know how to make this test faster. Actually, I know: implementing the `LOCAL_ONLY()` `CQL` extension for `SELECT` and `INSERT/UPDATE` would help greatly. The test currently generates sstables, then uploads them to nodes. Even this is faster than stopping/starting nodes, which was even more painfully slow.
> > 
> > 
> > It tries to overflow the page size, yes? Maybe run it with artificially lower limits?
> 
> We have a hardcoded size-limit of 1MB, which this test tries to overflow, correct. For some time now, this limit is sent by the coordinator to replica nodes. If so, maybe we can make it configurable for tests. Note that this will solve just one factor in the slowness.

If it takes it down by a factor of 10, that's more than an hour saved.
