### ISSUE TITLE
nodetool removenode gets stuck on removing a dead/non-existing node

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#16475]
Revealed by [auth_test.py::TestAuth::test_remove_dead_node_consistency_failed](https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/byo/job/dtest-byo/81/testReport/junit/auth_test/TestAuth/FullDtest___full_split002___test_remove_dead_node_consistency_failed/) (which is not a part of PR-gating, and was unblocked by @KrzaQ fixing https://github.com/scylladb/scylladb/issues/2339).
`nodetool removenode <host-id>` seems to be getting stuck when trying to remove an already removed node by posting an RPC call to a dead node. This call doesn't return (?) until the `removenode` command times-out.
The [code](https://github.com/scylladb/scylladb/blob/master/tools/scylla-nodetool.cc#L592) doesn't check if the destination host-id is valid.
We only see one `api`-related log until the dtest is killed (`127.0.68.2` is the IP of the 2nd/killed node, it gets killed at `2023-12-19 22:19:51,611`):
```
DEBUG 2023-12-19 22:20:12,284 [shard 0:main] rpc - client 127.0.68.2:7000: fail to connect: Connection refused
DEBUG 2023-12-19 22:20:12,285 [shard 0:main] storage_proxy - Drop hit rate info for 127.0.68.2 because of disconnect
DEBUG 2023-12-19 22:20:12,285 [shard 0:main] messaging_service - dropped connection to 127.0.68.2
INFO  2023-12-19 22:20:12,314 [shard 0:strm] api - remove_node: host_id=4247eeb3-5e19-45e8-afd6-343059d1479f ignore_nodes={}
INFO  2023-12-19 22:20:12,316 [shard 0:strm] raft_group0 - Performing a group 0 read barrier...
DEBUG 2023-12-19 22:20:12,326 [shard 1:main] load_broadcaster - Skip CACHE_HITRATES update max_diff=0, published_nr=1
DEBUG 2023-12-19 22:20:12,361 [shard 0:strm] raft_rpc - service/raft/raft_rpc.cc:109: virtual void service::raft_rpc::send_vote_request(raft::server_id, const raft::vote_request &) dropping outgoing message to 4247eeb3-5e19-45e8-afd6-343059d1479f - node is not seen as alive by the failure detector
DEBUG 2023-12-19 22:20:12,384 [shard 0:main] rpc - client 127.0.68.2:7000: fail to connect: Connection refused
DEBUG 2023-12-19 22:20:12,385 [shard 0:main] storage_proxy - Drop hit rate info for 127.0.68.2 because of disconnect
DEBUG 2023-12-19 22:20:12,385 [shard 0:main] messaging_service - dropped connection to 127.0.68.2
DEBUG 2023-12-19 22:20:12,485 [shard 0:main] rpc - client 127.0.68.2:7000: fail to connect: Connection refused
DEBUG 2023-12-19 22:20:12,485 [shard 0:main] storage_proxy - Drop hit rate info for 127.0.68.2 because of disconnect
DEBUG 2023-12-19 22:20:12,485 [shard 0:main] messaging_service - dropped connection to 127.0.68.2
...
```

**Comment by ptrsmrn** [comment]
@denesb since you authored the mentioned code, could you please provide your assessment?

**Comment by denesb** [comment]
I don't understand, `nodetool` never issues `RPC` calls, it sends requests to the ScyllaDB REST API, what ScyllaDB does after that, is an entirely different matter.

You mean the ScyllaDB node tries to contact a dead node?

**Comment by ptrsmrn** [comment]
> I don't understand, `nodetool` never issues `RPC` calls, it sends requests to the ScyllaDB REST API, what ScyllaDB does after that, is an entirely different matter.

Right, I got confused by the rpc logs that surround the api log.

> You mean the ScyllaDB node tries to contact a dead node?

Yes.

**Comment by kbr-scylla** [comment]
Standard question: does the cluster have majority? With Raft enabled it's impossible to run topology changes if majority is lost. And all tests have Raft enabled now.

**Comment by ptrsmrn** [comment]
So @kbr-scylla are you saying this testcase will always fail now that we have RAFT enabled? The forever-hanging API call didn't look all that connected to RAFT being on or off.

**Comment by kostja** [comment]
@ptrsmrn please make the cluster use 3 nodes. This is how we adjust all such tests now.

**Comment by kostja** [comment]
@ptrsmrn the issue can be closed.

**Comment by ptrsmrn** [comment]
@kostja if you're talking about this change - https://github.com/scylladb/scylla-dtest/pull/3804 - it does NOT work.

**Comment by bhalevy** [comment]
Hit in https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-dtest/job/PR-3805/2/testReport/
```
self = <auth_test.TestAuth object at 0x7f0490bfbf10>

    def test_remove_dead_node_consistency_failed(self):
        """
        **Description:** Run "nodetool removenode"' on the dead node (when RF=2).
        **Expected Result:** Cluster is available - successful connection.
        """
        self.prepare(nodes=2)
        logger.info('Cluster with 2 nodes started')
    
        [node1, node2] = self.cluster.nodelist()
        session = self.get_session(node_idx=0, user='cassandra', password='cassandra')
        logger.info('Successfully get the session from node1')
        # make sure session works
        self._check_session_available(session)
    
        # change rf RF of system_auth to 2
        session.execute(
            "alter keyspace system_auth with replication = {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor':2};")
        self.cluster.repair()
    
        node2_hostid = node2.hostid()
        node2.stop(wait_other_notice=True, gently=False)
>       node1.nodetool("removenode %s" % node2_hostid)

auth_test.py:1624: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:767: in nodetool
    return super().nodetool(*args, **kwargs)
../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:837: in nodetool
    stdout, stderr = p.communicate(timeout=timeout)
/usr/lib64/python3.11/subprocess.py:1209: in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
/usr/lib64/python3.11/subprocess.py:2108: in _communicate
    ready = selector.select(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selectors.PollSelector object at 0x7f0490315810>, timeout = None

    def select(self, timeout=None):
        # This is shared between poll() and epoll().
        # epoll() has a different signature and handling of timeout parameter.
        if timeout is None:
            timeout = None
        elif timeout <= 0:
            timeout = 0
        else:
            # poll() has a resolution of 1 millisecond, round away from
            # zero to wait *at least* timeout seconds.
            timeout = math.ceil(timeout * 1e3)
        ready = []
        try:
>           fd_event_list = self._selector.poll(timeout)
E           Failed: Timeout >2700.0s
```

https://jenkins.scylladb.com/job/sct-github-PRs-scan/job/scylla-dtest/job/PR-3805/2/artifact/logs-PR.release.000/1703449443787_auth_test.py%3A%3ATestAuth%3A%3Atest_remove_dead_node_consistency_failed/node1.log
```
INFO  2023-12-24 19:39:44,929 [shard 0:strm] gossip - InetAddress 127.0.53.2 is now DOWN, status = NORMAL
INFO  2023-12-24 19:39:45,814 [shard 0:strm] api - remove_node: host_id=b20f47c2-5ace-4d2a-9b52-bca6fa39b877 ignore_nodes={}
INFO  2023-12-24 19:39:45,814 [shard 0:strm] raft_group0 - Performing a group 0 read barrier...
INFO  2023-12-24 20:24:00,781 [shard 0:main] compaction_manager - Asked to stop
```

**Comment by bhalevy** [comment]
This test times out consistently since https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/445/testReport/junit/auth_test/TestAuth/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split005___test_remove_dead_node_consistency_failed/

**Comment by ptrsmrn** [comment]
> Standard question: does the cluster have majority? With Raft enabled it's impossible to run topology changes if majority is lost. And all tests have Raft enabled now.

Again, it doesn't, and as much as I understand that the nodetool command would fail without the quorum, currently it hangs forever instead of failing/succeeding.

**Comment by kostja** [comment]
You fixed the test now to make sure the majority is always present. 
So now why the test would still fail?
- because the authentication data is sitting on the dead node
- because the nodetool removenode is trying to connect to a dead node.
 Maybe it's indeed the cause?

**Comment by kbr-scylla** [comment]
BTW I opened https://github.com/scylladb/scylladb/issues/16604 to improve the user experience

**Comment by mykaul** [comment]
> You fixed the test now to make sure the majority is always present. So now why the test would still fail?

Was it fixed?

**Comment by bhalevy** [comment]
> > You fixed the test now to make sure the majority is always present. So now why the test would still fail?
> 
> Was it fixed?

I don't think so.
If indeed this PR aimed at fixing this: https://github.com/scylladb/scylla-dtest/pull/3804

**Comment by ptrsmrn** [comment]
PR concluded with removing the failing test altogether - https://github.com/scylladb/scylla-dtest/pull/3804
https://github.com/scylladb/scylladb/issues/16604 is going to replace the `nodetool removenode` stall with returning an error
