### ISSUE TITLE
scylla-sstable: schema_loader uses dummy db::config when loading schema

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16480]
Similar to the code in `tools/scylla-sstable.cc`, which already uses a single `db::config` instance, propagating it to every place which needs it, we should do the same in `tools/schema_loader.cc`. This has no significance in OSS (beyond the increased memory consumption caused by multiple `db::config` instances), but in enterprise this means that schema table sstables might fail to be read, if they are encrypted with EAR.

Fix this in OSS as well, to reduce code-difference between enterprise and OSS.

**Comment by mykaul** [comment]
@scylladb/scylla-maint - please prioritize backporting this.

**Comment by denesb** [comment]
Doesn't affect OSS, only enterprise backports are needed.
