### ISSUE TITLE
new coordinator stucked in infinite loop after bootstrap was aborted by crashing old coordinator

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#16485]
scylla version:  5.5.0~dev-0.20231206.c5cde14b6d70 with build-id 5341165c3d71cafd0a47aedcf6ab70ddb60651dd

Based on PR: https://github.com/scylladb/scylladb/pull/16197, new test was created : https://github.com/aleksbykov/scylla/blob/remove_crashed_coordinator/test/topology_experimental_raft/test_reproduce_bootstrap_error.py

```python
    config = {
        'failure_detector_timeout_in_ms': 2000
    }
    nodes = [await manager.server_add(config=config) for _ in range(4)]
    

    coordinators_ids = await get_coordinator_host_ids(manager)
    assert len(coordinators_ids) == 1, "At least 1 coordinator id should be found"

    # kill coordinator during bootstrap
    coordinator_host = await get_coordinator_host(coordinators_ids[0], manager)
    other_nodes = [srv for srv in nodes if srv.server_id != coordinator_host.server_id]
    new_node = await manager.server_add(start=False)
    await manager.api.enable_injection(coordinator_host.ip_addr, "crash_coordinator_before_stream", one_shot=True)
    await manager.server_start(new_node.server_id, expected_error="Bootstrap failed. See earlier errors")

    coordinators_ids = await get_coordinator_host_ids(manager)
    assert len(coordinators_ids) == 2, "No new record about the coordinator's election"
    assert coordinators_ids[0] != coordinator_host[1], f"New coordinator wasn't elected {coordinators_ids}"
    await manager.server_stop_gracefully(coordinator_host.server_id)
    await manager.wait_for_host_down(other_nodes[-1].server_id, coordinator_host.server_id)
    await manager.remove_node(other_nodes[-1].server_id,coordinator_host.server_id)

    await check_token_ring_and_group0_consistency(manager)
```

Test is failed on:
```
>       await manager.wait_for_host_down(other_nodes[-1].server_id, coordinator_host.server_id)

test/topology_experimental_raft/test_reproduce_bootstrap_error.py:63: 
```
node1 was coordinator. New node was node5. its bootstrap was aborted with crashing coordinator before streaming started with error injection.
New coordinator (node2) was elected, but it stucked in infinite loop with errors:

```
INFO  2023-12-18 16:38:49,434 [shard 0:strm] storage_service - raft topology: coordinator fiber found a node to work on id=d247f94f-0b25-4a18-9124-6ca2001d6d59 state=left_token_ring
ERROR 2023-12-18 16:38:49,434 [shard 0:strm] storage_service - raft topology: node_state::left_token_ring (node: d247f94f-0b25-4a18-9124-6ca2001d6d59), global_token_metadata_barrier failed, error std::runtime_error (raft topology: exec_global_command(barrier_and_drain) failed with seastar::rpc::closed_error (connection is closed))
INFO  2023-12-18 16:38:49,434 [shard 0:strm] storage_service - raft topology: coordinator fiber found a node to work on id=d247f94f-0b25-4a18-9124-6ca2001d6d59 state=left_token_ring
ERROR 2023-12-18 16:38:49,435 [shard 0:strm] storage_service - raft topology: node_state::left_token_ring (node: d247f94f-0b25-4a18-9124-6ca2001d6d59), global_token_metadata_barrier failed, error std::runtime_er
```
Test logs:
[test.logs.tar.gz](https://github.com/scylladb/scylladb/files/13726930/test.logs.tar.gz)

**Comment by aleksbykov** [comment]
@gleb-cloudius can you take a look?

**Comment by gleb-cloudius** [comment]
Which git commit is this built from? I do not have c5cde14b6d70 in my tree.

**Comment by aleksbykov** [comment]
> Which git commit is this built from? I do not have [c5cde14](https://github.com/scylladb/scylladb/commit/c5cde14b6d709235b71f9273fc023bdb6d268a35) in my tree.

it is based on https://github.com/scylladb/scylladb/pull/16197

**Comment by gleb-cloudius** [comment]
> > Which git commit is this built from? I do not have [c5cde14](https://github.com/scylladb/scylladb/commit/c5cde14b6d709235b71f9273fc023bdb6d268a35) in my tree.
> 
> it is based on #16197

So it is based on 1efddc228d3289596a3bbcd394a650fa098158ed which does not contain 7ea8fa459cbf647fb227af193fdec7807907a6e8. Try to rebase and retry.

**Comment by aleksbykov** [comment]
@gleb-cloudius , issue reproduced with Scylla version 5.5.0~dev-0.20231221.3279817baa43 with build-id 6e9947860c1d1c4186645d6ef14b7cc571cb1a77.

**Comment by gleb-cloudius** [comment]
What is 3279817baa43? I do not have such revision in my tree.

**Comment by aleksbykov** [comment]
This my commit with test : https://github.com/aleksbykov/scylla/blob/remove_crashed_coordinator/test/topology_experimental_raft/test_reproduce_bootstrap_error.py

**Comment by gleb-cloudius** [comment]
> This my commit with test : https://github.com/aleksbykov/scylla/blob/remove_crashed_coordinator/test/topology_experimental_raft/test_reproduce_bootstrap_error.py

On top of which commit that exist in the tree? Where is the brunch that you test?

**Comment by aleksbykov** [comment]
@gleb-cloudius , i forgot to push after rebase. I rebased to latest next

**Comment by gleb-cloudius** [comment]
> > This my commit with test : https://github.com/aleksbykov/scylla/blob/remove_crashed_coordinator/test/topology_experimental_raft/test_reproduce_bootstrap_error.py
> 
> On top of which commit that exist in the tree? Where is the brunch that you test?

Did you check that it is the same failure?
