### ISSUE TITLE
test/cql-pytest/test_tombstone_limit.py fails with tablets

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16486]
Four tests in `test/cql-pytest/test_tombstone_limit.py` fail with tablets enabled (see https://github.com/scylladb/scylladb/issues/16473 for a hack to enable tablets by default):
* `test_partition_tombstone_prefix`
* `test_partition_tombstone_span`
* `test_static_row_tombstone_prefix`
* `test_static_row_tombstone_span`

The failure in all of them is in the same place - the function `check_pages_many_partitions()` expects to have one empty page in addition to the desired page, but apparently doesn't get one. The comment above this function even mentions vnodes, but because I'm not familiar with this test (@denesb wrote it) it's not clear to me how they are related or why this empty page doesn't appear with tablets - and is this a real problem or just the test needs to be fixed.

CC @tgrabiec

**Comment by denesb** [comment]
This is test problem. This test wants to test that range scans respect the tombstone limit. Range scans scan one vnode at a time (for the most part), so for this test to work, there has to be at least on vnode with enough partition tombstones to trip the limit. With tablest, the test will have to ensure at least one tablet has enough partition tombstones to do the same.

**Comment by nyh** [comment]
> This is test problem. This test wants to test that range scans respect the tombstone limit. Range scans scan one vnode at a time (for the most part), so for this test to work, there has to be at least on vnode with enough partition tombstones to trip the limit. With tablest, the test will have to ensure at least one tablet has enough partition tombstones to do the same.

Oh, I see, thanks. Then I guess the fact I ran with test with `initial_tablets = 100` forced on it (this is not yet automatic) didn't help - it is much more than the number of vnodes that test/cql-pytest/run usually uses (16).

**Comment by denesb** [comment]
> Oh, I see, thanks. Then I guess the fact I ran with test with `initial_tablets = 100` forced on it (this is not yet automatic) didn't help - it is much more than the number of vnodes that test/cql-pytest/run usually uses (16).

Yes, this test will want as small as possible tablet count.
