### ISSUE TITLE
DESC CLUSTER doesn't work with tablets

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16483]
When a keyspace has **tablets** enabled, running `DESC CLUSTER` results in an error like:

> Tried to obtain per-keyspace effective replication map of cql_test_1703071419122 but it's per-table

The interesting part of the backtrace is
```
replica::keyspace::get_effective_replication_map() const at database.cc:?
locator::describe_ring(replica::database const&, gms::gossiper const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, bool) at util.cc:?
service::storage_proxy::describe_ring(seastar::basic_sstring<char, unsigned int, 15u, true> const&, bool) const at storage_proxy.cc:?
cql3::statements::cluster_describe_statement::range_ownership(service::storage_proxy const&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) const at describe_statement.cc:?
cql3::statements::cluster_describe_statement::describe(cql3::query_processor&, service::client_state const&) const at describe_statement.cc:?
```

Can be reproduced by `test/cql-pytest/run test_describe.py::test_desc_cluster` (after hacking tablets to be enabled by default, see https://github.com/scylladb/scylladb/issues/16473).

CC @tgrabiec

**Comment by tgrabiec** [comment]
I think the fix should be to change `cluster_describe_statement::should_add_range_ownership()` to exclude tablet-based keyspaces.

**Comment by avikivity** [comment]
Yes. We may consider an extension later to also describe tablets somehow, but for now excluding tablets is enough.

**Comment by tzach** [comment]
Might be related: DESC SCHEMA is part of [manual backup/restore](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/backup.html).
It is problematic, as described in https://github.com/scylladb/scylladb/issues/16349

**Comment by tgrabiec** [comment]
> Might be related: DESC SCHEMA is part of [manual backup/restore](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/backup.html). It is problematic, as described in #16349

This issue is about DESC CLUSTER, so not related.

**Comment by nyh** [comment]
Sadly, no one seems to have actually run the mentioned test and see it still fails with this patch:
```
    def test_desc_cluster(scylla_only, cql, test_keyspace):
        cql.execute(f"USE {test_keyspace}")
        desc = cql.execute("DESC CLUSTER").one()
        desc_endpoints = []
>       for (end_token, endpoints) in desc.range_ownership.items():
E       AttributeError: 'Row' object has no attribute 'range_ownership'
```

Soon it will be easier to run cql-pytest with tablets enabled (I'll send a PR in an hour or two)
I see Avi already created a patch about the missing range ownership.
