### ISSUE TITLE
Improve Alternator Streams error before tablets support CDC 

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16497]
When Alternator is asked to use tablets (currently this needs to be done explicitly, 8e356d8c312849cbca4afeb2c425ad261ed5f638), Streams cannot be enabled because CDC is not yet supported with tablets (https://github.com/scylladb/scylladb/issues/16317).

Commit 7ee55dd03eb0766dff08c0bcf1b7e470a60264ad made an attempt to create a table with CDC together with tablets a nice CQL exception - invalid_request_exception. But this is not one of Alternator's api_error types, so it generates an "Internal Server Error":

> Internal server error: exceptions::invalid_request_exception (Cannot create CDC log for a table alternator_alternator_Test_1703085389283.alternator_Test_1703085389283, because keyspace uses tablets. See issue #16317.)

This "Internal Server Error" is ugly, and also may cause the driver to retry the request (boto3 by default retries it for up to a minute!) which is unhelpful and will fail again in the same way.

There are two options on how to fix the error message:
1. Alternator could have a separate check of whether tablets are used, and generate its own error message with an `api_error` - before ever trying to create the table.
2. Alternator could catch `exceptions::invalid_request_exception` coming from the table creation, and create an `api_error::validation` from its text.

I prefer the first approach because I think it will be more user-friendly - the error message should use DynamoDB API terminology, like "Streams", not CQL terminology like "CDC log". The error message should also mention the Alternator table's name - not the name as we converted it to CQL with the keyspace name.

**Comment by denesb** [comment]
Tablets related change, no backports required.
