### ISSUE TITLE
raft gossiper_state_change_subscriber_proxy on_alive error injector waits under the gossiper endpoint lock

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16506]
gossiper_state_change_subscriber_proxy on_alive callback implementation co_awaits `utils::get_local_injector().inject_with_handler` that will wait for up to 1 minute:
https://github.com/scylladb/scylladb/blob/ee203f846ed3753cd8031ae6a6ee4e333875aada/service/raft/raft_group_registry.cc#L132-L136

But the problem is that it does that while the endpoint_lock is acquired by the gossiper in
https://github.com/scylladb/scylladb/blob/ee203f846ed3753cd8031ae6a6ee4e333875aada/gms/gossiper.cc#L1618-L1619
as is the convention of issuing all notifications while holding the endpoint lock,
preventing changes to the endpoint state.

In particular `storage_service::topology_state_load` may hit this lock if it calls https://github.com/scylladb/scylladb/blob/ee203f846ed3753cd8031ae6a6ee4e333875aada/service/storage_service.cc#L562

**Comment by bhalevy** [comment]
Cc @tgrabiec @gusev-p @kbr-scylla

**Comment by bhalevy** [comment]
I think that this causes long delays in debug/dev testing.

**Comment by bhalevy** [comment]
and may cause the error injection in on_alive to timeout in the rare event that the endpoint state is not present yet in `topology_state_load` and it ends up calling `add_saved_endpoint` which may deadlock on the endpoint_lock held around the call to `on_alive`.

**Comment by kostja** [comment]
@bhalevy could you please clarify the description of this report? Which test is taking too long? The injection is not enabled for all tests, it's only used in test/topology_custom/test_old_ip_notification_repro.py

Are you fixing a flaky test?

**Comment by bhalevy** [comment]
@kostja I'm fixing this for https://github.com/scylladb/scylladb/pull/16432
so that end endpoint_lock could be taken in `storage_service::topology_state_load`

**Comment by kostja** [comment]
Sounds like both series are struggling with the fact that we load the endpoint state twice.

**Comment by bhalevy** [comment]
> Sounds like both series are struggling with the fact that we load the endpoint state twice.

@kostja the issue of waiting while holding the endpoint_lock is orthogonal to add_saved_endpoint.
I'd fix it regardless as holding the lock for a whole minute while we don't have to is bad by itself.
So let's move the discussion about add_saved_endpoint to https://github.com/scylladb/scylladb/issues/16429 / https://github.com/scylladb/scylladb/pull/16432

**Comment by kostja** [comment]
I really don't see why holding a lock for the duration of injection is bad. After all, it's the injection, we can put it anywhere we like. It's not going to be 1 minute in production. What is the underlying issue here?

**Comment by bhalevy** [comment]
> I really don't see why holding a lock for the duration of injection is bad. After all, it's the injection, we can put it anywhere we like. It's not going to be 1 minute in production. What is the underlying issue here?

Please see the issue description above: https://github.com/scylladb/scylladb/issues/16506#issue-2052167782
Don't you agree it's a problem?

**Comment by bhalevy** [comment]
What happens is that the error injection fails since it happens while holding the lock and waiting for something that requires acquiring the same lock in some corner cases.
Hence, we want to release the lock during the error injection callback so to let others access the endpoint state and wake up the error injection while it's waiting in `handler.wait_for_message`.
We use the endpoint generation to update the address map to allow proper serialization of this change.

**Comment by gusev-p** [comment]
I also don't understand the motivation behind this issue and PR.

> But the problem is that it does that while the endpoint_lock is acquired by the gossiper. In particular storage_service::topology_state_load may hit this lock if it calls

Someone called `real_mark_alive`, acquired the `endpoint_lock` and got stuck in `wait_for_message`. Then `topology_state_load` comes, didn't find ep in `get_endpoint_state_ptr`, calls `add_saved_endpoint` and gets stuck on the same lock.

Why is this a problem? Given that this injection is used in one specific test and `wait_for_message` is expected to resolve quickly.

The PR makes the code more complicated, and it significantly change the conditions under which the test `test_old_ip_notification_repro` operates. Is it still testing what it was supposed to test? It might be that the host_id<->ip mapping is now updated through some other event (`on_join`) since the lock for ep is now not held.

> Holding the gate may cause long delays in debug/dev testing
> and may cause the error injection in on_alive to timeout in the

I don’t see how the acquired lock is related to debug/dev long delays. We are either able to acquire the lock or we aren't, it has nothing to do with debug/dev builds.

**Comment by bhalevy** [comment]
> Why is this a problem? Given that this injection is used in one specific test and wait_for_message is expected to resolve quickly.

Without this I see `wait_for_message` timing out and the test fails.

**Comment by gusev-p** [comment]
> > Why is this a problem? Given that this injection is used in one specific test and wait_for_message is expected to resolve quickly.
> 
> Without this I see `wait_for_message` timing out and the test fails.

It was not clear from the issue description, that we actually hit this problem.

**Comment by gusev-p** [comment]
IIUC, we start hitting it because in #16429 we start acquiring the ep lock for every endpoint, not just for non existing ones, like it happens now in `add_saved_endpoint` itself. It would be helpful to add this to the PR motivation.
