### ISSUE TITLE
docs: Issue in page Nodetool scrub - circular definition of "scrub"

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#16505]
I would like to report an issue in page https://opensource.docs.scylladb.com/master/operating-scylla/nodetool-commands/scrub

### Problem
> scrub - Scrub the SSTable files in the specified keyspace or table(s)

This does not help understanding what Scrub do

###  Suggest a fix

> scrub - Help identify and fix corrupted SSTable.
Remove faulty data and eliminate tombstoned rows that have surpassed the table's gc_grace period. If partition-key values do not align with the specified column data type, the partition is handled as corrupted.

**Comment by denesb** [comment]
Scrub, in general is very under-documented. I want to add a dedicated documentation page (which will be linked from nodetool scrub page).

**Comment by denesb** [comment]
> scrub - Help identify and fix corrupted SSTable.
> Remove faulty data and eliminate tombstoned rows that have surpassed the table's gc_grace period. If partition-key values do not align with the specified column data type, the partition is handled as corrupted.

This latter part I'm not sure of. We do not check that values correspond to their types, not even in scrub.
We fix out-of-order rows and partitions though.
