### ISSUE TITLE
Implement /storage_service/get_tablet_keyspaces RESTful API

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16509]
Will be needed by scylla manager to choose an alternative approach to scheduling repair. For tablet keyspaces, the ring is per-table rather than per keyspace, so the scylla manager needs to use a different call to determine topology.

**Comment by mykaul** [comment]
CC @karol-kokoszka , @Michal-Leszczynski

**Comment by bhalevy** [comment]
@tchaikov can you please pick this up?

**Comment by tchaikov** [comment]
currently, scylla-manager (mgr for short) uses following RESTful APIs provided by scylla for performing repair

- GET `/storage_service/describe_ring/{keyspace}`
- GET `/storage_service/active_repair/`
- POST `/storage_service/repair_async/{keyspace}`
- GET `/storage_service/repair_status`

in which, the `/storage_service/describe_ring/{keyspace}` endpoint returns the distribution of the token range of the specified keyspace, the return value is a list of token range and its corresponding endpoints, each element looks like:
```json
{
  "start_token": "-9034050544407152667",
  "end_token": "-9026777106402418709",
  "endpoints": [
    "192.168.100.11",
    "192.168.100.12",
  ],
  "rpc_endpoints": [
    "192.168.100.11",
    "192.168.100.12",
  ],
  "endpoint_details": [
    {
      "host": "192.168.100.11",
      "datacenter": "dc1",
      "rack": "rack1"
    },
    {
      "host": "192.168.100.12",
      "datacenter": "dc1",
      "rack": "rack1"
    }
  ]
}
```

with the distribution of token ranges, mgr can schedule the repair of keyspace with the constraints and the task granularity specified. for instance, we might want to repair specified keyspace or table. and probably prioritize the (smaller) system keyspaces.

**Comment by tgrabiec** [comment]
The plan was that `get_tablet_keyspaces` only returns a list of keyspaces, and then mgr calls `/storage_service/describe_ring/{keyspace}/{table}` to get per-table distribution for tablet-based keyspaces.

**Comment by tchaikov** [comment]
@tgrabiec thank you Tomek. i am actually currently adding `/storage_service/describe_ring/{keyspace}/{table}/`. so, to be more specific, `get_tablet_keyspace` does not accept any parameter, and it should return keyspaces which are replicated using tablets, am i right?

**Comment by tchaikov** [comment]
Kefu:
> we could use the same set of APIs for performing cleanup on keyspaces backed by vnode and those backed by tablet as the new API also works for vnode keyspaces. Design document mentions that we do per-table cleanup even on vnode-based keyspaces.

Tomek

> we don’t do per-table cleanup on vnode keyspaces, need to revisit the design document.


see https://github.com/scylladb/scylla-manager/issues/3362 and https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA

**Comment by tgrabiec** [comment]
> Kefu:
> 
> > we could use the same set of APIs for performing cleanup on keyspaces backed by vnode and those backed by tablet as the new API also works for vnode keyspaces. Design document mentions that we do per-table cleanup even on vnode-based keyspaces.
> 
> Tomek
> 
> > we don’t do per-table cleanup on vnode keyspaces, need to revisit the design document.
> 
> see [scylladb/scylla-manager#3362](https://github.com/scylladb/scylla-manager/issues/3362) and https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA

I meant this doc: https://docs.google.com/document/d/1ATh5i4EMTJYnWERZ-BDH7lpgqwHe0HE-zxPWycW70So/edit#bookmark=id.ghsrwz1fdn4s


> For tablet-based keyspaces, intensity of range repair needs to be increased so that it’s more than one range per node. That’s because with tablets a single range will be owned by a single shard. So to keep the cluster fully utilized we need more parallelism. If the default for vnode-based keyspaces is 1 range per node, with tablets it should be <shard_count_per_node> of ranges per node to keep all shards busy (with some probability).

**Comment by tgrabiec** [comment]
> @tgrabiec thank you Tomek. i am actually currently adding `/storage_service/describe_ring/{keyspace}/{table}/`. so, to be more specific, `get_tablet_keyspace` does not accept any parameter, and it should return keyspaces which are replicated using tablets, am i right?

Yes.

**Comment by Michal-Leszczynski** [comment]
@tgrabiec was this issue solved with #17118?

**Comment by tgrabiec** [comment]
> @tgrabiec was this issue solved with #17118?

No, this issue is about adding an API to determine which keyspaces are using tablets. #17118 added a way to query topology on per-table basis, which should be used for tablet-based keyspaces.

**Comment by bhalevy** [comment]
> Why do we need an API for this? You can already achieve this with this query:
> 
> ```sql
> select keyspace_name from system_schema.scylla_keyspaces where initial_tablets >= 0 allow filtering;
> ```

That sounds like something scylla-manager can easily do.
Right, @Michal-Leszczynski?

**Comment by mykaul** [comment]
I'm not sure Scylla Manager always has CQL creds?

**Comment by karol-kokoszka** [comment]
Only scylla-cloud clusters provide CQL creds by default on cluster creation.
For all the others it's up to the end-user to include them or not.

**Comment by denesb** [comment]
Ok, I'll send a PR soon to add the REST API then.

**Comment by denesb** [comment]
PR here: https://github.com/scylladb/scylladb/pull/17319

I ended up just adding a new `replication` param to the existing `keyspaces` endpoint.

**Comment by denesb** [comment]
Feature, no backports needed.
