### ISSUE TITLE
[Compaction]: TWCS has 100% disk space amplification during reshaping

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#16514]
*Installation details*
HEAD: 65e42e4166cef5acafa7ce7f884d6cc2b55adc35

*Description*
The subject has it all. 
The immediate side effect is that everybody who uses TWCS has to keep at least the same amount of free disk space as the size of the corresponding table to make sure they can complete a node replacement if/when one of the nodes is going to die.

**Comment by vladzcloudius** [comment]
One way to address this issue is:
1) Segregate steamed data as it arrives.
2) Start compacting the resulting sstables together immediately in order to avoid "too many small files" issue.
3) Apply a back pressure on the streaming if compaction start falling behind.

**Comment by raphaelsc** [comment]
> One way to address this issue is:
> 
> 1. Segregate steamed data as it arrives.
> 2. Start compacting the resulting sstables together immediately in order to avoid "too many small files" issue.
> 3. Apply a back pressure on the streaming if compaction start falling behind.

Backpressure is useful even today. Consider node with 96 shards, 1k tables. If offstrategy is postponed to node op completion, then the file desc count can reach almost 150 million (96×1000×768×2).

**Comment by vladzcloudius** [comment]
@raphaelsc could you, please, clarify if this is a regression?
I guess it is at least compared to before reshaping was introduced.
But maybe it wasn't like that even after reshaping of TWCS was introduced ?

In any case we need to know since what version this issue has started.

**Comment by denesb** [comment]
@raphaelsc ping ^^

@vladzcloudius with tablets, this problem will go away, because each tablet will reshape independently and each will only have a small fraction of the shard's total storage.

As for pre-tablet versions: AFAIK @raphaelsc has a fix which makes use of SAG to provide an upper bound for the space amplification here. @raphaelsc can you please elaborate on that?

**Comment by denesb** [comment]
> It's a new option named offstrategy_space_amplification_goal, can be configured with a value between 0 and 1, where 1 means 100% and it's the behavior today where input is reshaped all at once. With a value of 0.5, the input will be reshaped in two rounds, and so on. Vlad already tested it and it works.

Please submit a PR so we can get it into OSS as well and backport it.

**Comment by mykaul** [comment]
> > It's a new option named offstrategy_space_amplification_goal, can be configured with a value between 0 and 1, where 1 means 100% and it's the behavior today where input is reshaped all at once. With a value of 0.5, the input will be reshaped in two rounds, and so on. Vlad already tested it and it works.
> 
> Please submit a PR so we can get it into OSS as well and backport it.

Ping @raphaelsc , @denesb
