### ISSUE TITLE
scylla-sstable: crash due to unclosed reader in tools/schema_loader.cc

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16519]
## Issue description

Not a regression (code has been like this since introduction of automatic schema discovery and load - present in 5.2+).

Crash happens here:
https://github.com/scylladb/scylladb/blob/9c7e5f627715d902e73bb960908e90036b260dfc/tools/schema_loader.cc#L441-L443

This seems like a genuine bug, no one closes that reader. This should be crashing all the time, but somehow it doesn't.
I cannot reproduce this crash locally, and it seems like it doesn't happen all the time in SCT either. Not yet sure why.

## Installation details

Kernel Version: 5.15.0-1051-aws
Scylla version (or git commit hash): `2024.1.0~rc2-20231217.f57117d9cfe3` with build-id `3a4d2dfe8ef4eef5454badb34d1710a5f36a859c`

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-2024-1-db-node-d3ef5cec-7 (18.234.171.30 | 10.12.8.13) (shards: -1)
- alternator-3h-2024-1-db-node-d3ef5cec-6 (54.226.242.5 | 10.12.10.50) (shards: 14)
- alternator-3h-2024-1-db-node-d3ef5cec-5 (35.172.219.253 | 10.12.8.64) (shards: 14)
- alternator-3h-2024-1-db-node-d3ef5cec-4 (3.80.141.243 | 10.12.9.211) (shards: 14)
- alternator-3h-2024-1-db-node-d3ef5cec-3 (34.224.174.172 | 10.12.9.148) (shards: 14)
- alternator-3h-2024-1-db-node-d3ef5cec-2 (54.159.81.125 | 10.12.11.208) (shards: 14)
- alternator-3h-2024-1-db-node-d3ef5cec-1 (34.226.202.252 | 10.12.9.39) (shards: 14)

OS / Image: `ami-02a2eda4799995de1` (aws: undefined_region)

Test: `longevity-alternator-3h-test`
Test id: `d3ef5cec-c5d4-4857-a1dc-5893417574e7`
Test name: `enterprise-2024.1/longevity/longevity-alternator-3h-test`
Test config file(s):

- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/afd9742f1a1950dd5fe92bcc8d9c0fc8440c6abb/test-cases/longevity/longevity-alternator-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d3ef5cec-c5d4-4857-a1dc-5893417574e7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d3ef5cec-c5d4-4857-a1dc-5893417574e7)
- Show all stored logs command: `$ hydra investigate show-logs d3ef5cec-c5d4-4857-a1dc-5893417574e7`

## Logs:
- **db-cluster-d3ef5cec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/db-cluster-d3ef5cec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/db-cluster-d3ef5cec.tar.gz)
- **sct-runner-events-d3ef5cec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/sct-runner-events-d3ef5cec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/sct-runner-events-d3ef5cec.tar.gz)
- **sct-d3ef5cec.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/sct-d3ef5cec.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/sct-d3ef5cec.log.tar.gz)
- **loader-set-d3ef5cec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/loader-set-d3ef5cec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/loader-set-d3ef5cec.tar.gz)
- **monitor-set-d3ef5cec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/monitor-set-d3ef5cec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/monitor-set-d3ef5cec.tar.gz)
- **parallel-timelines-report-d3ef5cec.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/parallel-timelines-report-d3ef5cec.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d3ef5cec-c5d4-4857-a1dc-5893417574e7/20231217_230452/parallel-timelines-report-d3ef5cec.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2024.1/job/longevity/job/longevity-alternator-3h-test/8/)
[Argus](https://argus.scylladb.com/test/cd11fe27-c9d5-4d20-a080-917a328b3d07/runs?additionalRuns[]=d3ef5cec-c5d4-4857-a1dc-5893417574e7)
</details>

**Comment by denesb** [comment]
Mystery solved.

https://github.com/scylladb/scylladb/blob/9c7e5f627715d902e73bb960908e90036b260dfc/readers/mutation_reader.cc#L89-L91

`consume()` operates on the `_impl` directly, so it will never trigger `set_close_required()`, and the top-level reader thinks it doesn't have to be closed. 
The combined reader does use top-level `flat_mutation_reader_v2` methods, so it will trigger `set_close_required()` on the underlying readers. But the combined reader also closes readers who have no more data for the current range. So sometimes, with just the right data-shape, some readers will be left unclosed and will trigger the crash.

**Comment by denesb** [comment]
Opened https://github.com/scylladb/scylladb/issues/16520 for the `consume()`/`close()` bad interaction.

**Comment by mykaul** [comment]
@avikivity  - please assist in the backport.

**Comment by avikivity** [comment]
Backported to 5.2, 5.4.
