### ISSUE TITLE
test/cql-pytest/test_tools.py is very slow

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16516]
I have observed this test taking tens of seconds. I think this is because it tries to generate partitions that belong to a certain shard, in a loop. I think we can ditch this code and just generate N partitions, and verify that the sstable containing them is assigned by the tool to the shard the partition belongs to.

**Comment by tchaikov** [comment]
@denesb hi Botond, do you mean something like (in pseudo code):

```py
for i in range(N):
  cql.insert_with_pk(table, i)
node.flush()
# now we have multiple sstables containing N partitions
for sstable in find_sstables(table):
  actual_shards = scylla.tool.shards_of(sstable)
  pks = some_unknown_tool.pk_of(sstable)
  expected_shards = set(list(scylla.types.shards_of(serialize(pk))) for pk in pks))
```

if so, and we don't have this `some_unknown_tool` yet, i'd suggest just replace 42 with 1. so we only generate a single pk (partition) for each shard.

what do you think?

**Comment by denesb** [comment]
I mean:
```
for i in range(N):
    cql.insert(...) // insert pk
    node.flush()
    // get latest sstable
   // verify shard_of sstable = shard_of(pk)
```
