### ISSUE TITLE
Node down after upgrade from 5.2.11 to 5.4.0 version

### ISSUE THREAD

**Issue by JackThird** [scylladb/scylladb#16512]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.0-0.20231205.58a89e7a4231
Cluster size: 3 nodes / 1 DC
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu server 22.04

I upgraded my nodes from 5.2.11 to 5.4.0, scylla-server is up and running on all servers but this is the current situation:

**- IP: 10.20.0.6**
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.20.0.6   16.15 GB   256          ?       6aba4177-b447-4934-8960-e62a9f1b7301  rack1
DN  10.20.0.8   ?          256          ?       47694372-6b86-4f6b-82c6-dc8f7ddb92ce  rack1
UN  10.20.0.27  16.02 GB   256          ?       130d1875-0a2b-4d87-b088-2f99839b981c  rack1
```

**- IP: 10.20.0.27**
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  10.20.0.6   16.15 GB   256          ?       6aba4177-b447-4934-8960-e62a9f1b7301  rack1
DN  10.20.0.8   ?          256          ?       47694372-6b86-4f6b-82c6-dc8f7ddb92ce  rack1
UN  10.20.0.27  16.02 GB   256          ?       130d1875-0a2b-4d87-b088-2f99839b981c  rack1
```

**- IP: 10.20.0.8**
```
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
DN  10.20.0.6   ?          256          ?       6aba4177-b447-4934-8960-e62a9f1b7301  rack1
UN  10.20.0.8   15.93 GB   256          ?       47694372-6b86-4f6b-82c6-dc8f7ddb92ce  rack1
DN  10.20.0.27  ?          256          ?       130d1875-0a2b-4d87-b088-2f99839b981c  rack1
```

In the logs I see **(10.20.0.6, 10.20.0.27):**
```
Dec 21 17:39:04 melchiorre scylla[1961595]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.8 30829ae0-9434-11ee-89fe-90a38ae2fe28 != b0378d80-7351-11ee-a0f8-520064d108ed
Dec 21 17:39:04 melchiorre scylla[1961595]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.8 30829ae0-9434-11ee-89fe-90a38ae2fe28 != b0378d80-7351-11ee-a0f8-520064d108ed
Dec 21 17:39:05 melchiorre scylla[1961595]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.8 30829ae0-9434-11ee-89fe-90a38ae2fe28 != b0378d80-7351-11ee-a0f8-520064d108ed
```

**(10.20.0.8):**
```
Dec 21 17:39:49 gaspare scylla[812288]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.27 b0378d80-7351-11ee-a0f8-520064d108ed != 30829ae0-9434-11ee-89fe-90a38ae2fe28
Dec 21 17:39:50 gaspare scylla[812288]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.6 b0378d80-7351-11ee-a0f8-520064d108ed != 30829ae0-9434-11ee-89fe-90a38ae2fe28
Dec 21 17:39:51 gaspare scylla[812288]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.6 b0378d80-7351-11ee-a0f8-520064d108ed != 30829ae0-9434-11ee-89fe-90a38ae2fe28
Dec 21 17:39:52 gaspare scylla[812288]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.6 b0378d80-7351-11ee-a0f8-520064d108ed != 30829ae0-9434-11ee-89fe-90a38ae2fe28
Dec 21 17:39:52 gaspare scylla[812288]:  [shard  0:goss] gossip - Group0Id mismatch from 10.20.0.27 b0378d80-7351-11ee-a0f8-520064d108ed != 30829ae0-9434-11ee-89fe-90a38ae2fe28
```

Raft was enabled on all nodes since version 5.2.11

I can provide further info if you need, thanks.

**Comment by avikivity** [comment]
@gleb-cloudius please take a look.

**Comment by JackThird** [comment]
ping

**Comment by gleb-cloudius** [comment]
It looks like your servers think they belong to different raft clusters. Do you have logs before and after upgrade for all nodes? DId you do something special during the upgrade like copying/removing any files from disk?

**Comment by JackThird** [comment]
I haven't logs because journalctl is flooded by listed gossip messages. 
I followed scylla [guide](https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.4/upgrade-guide-from-5.2-to-5.4-generic.html) to upgrade scylla from 5.2 to 5.4, no operations were performed while upgrading.

I attach also my scylla.yml configurations.
[scylla_configs.zip](https://github.com/scylladb/scylladb/files/13751812/scylla_configs.zip)


If it can help I activate 
minimum_replication_factor_fail_threshold: 3

These are my DBs:
- SELECT * FROM system_schema.keyspaces;
```
 keyspace_name                 | durable_writes | replication
-------------------------------+----------------+-------------------------------------------------------------------------------------
             kairosdb_a |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                  kairosdb_b |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
            kairosdb_c |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                kairosdb_d |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                   system_e |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '1'}
                 system_f |           True |                             {'class': 'org.apache.cassandra.locator.LocalStrategy'}
                kairosdb_g |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
              kairosdb_h |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
             kairosdb_i |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                  kairosdb_l |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
            system_distributed |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                        system |           True |                             {'class': 'org.apache.cassandra.locator.LocalStrategy'}
                  kairosdb_m |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
           kairosdb_n |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                  kairosdb_o |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                  kairosdb_p |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                  kairosdb_q |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}
                 system_traces |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '2'}
 system_distributed_everywhere |           True |                        {'class': 'org.apache.cassandra.locator.EverywhereStrategy'}
                  kairosdb_r |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}

```


- nodetool describecluster
```
Cluster Information:
        Name: Magi
        Snitch: org.apache.cassandra.locator.SimpleSnitch
        DynamicEndPointSnitch: disabled
        Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
        Schema versions:
                0105cd2d-02e6-3c5b-9d11-0c13892ec159: [10.20.0.6, 10.20.0.27]
```

```
Cluster Information:
        Name: Magi
        Snitch: org.apache.cassandra.locator.SimpleSnitch
        DynamicEndPointSnitch: disabled
        Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
        Schema versions:
                0105cd2d-02e6-3c5b-9d11-0c13892ec159: [10.20.0.8]
```

- cqlsh> SELECT * FROM system.scylla_local WHERE key = 'group0_upgrade_state';
```

 key                  | value
----------------------+--------------------------
 group0_upgrade_state | use_post_raft_procedures
```
Same query result on all nodes.

I don't know how to resolve the issue because nodetool repair/decommission didn't work with listed issue.

**Comment by JackThird** [comment]
I retrieve logs from syslog:
[logs.zip](https://github.com/scylladb/scylladb/files/13751890/logs.zip)


I did Scylla Upgrades yesterday 2023/12/21, more or less 14:00-16:00 GMT+1 (CET)

**Comment by gleb-cloudius** [comment]
The problem existed before the upgrade:
```
syslog_10.20.0.27:Dec 17 07:00:40 pippin scylla:  [shard  0] raft_group0 - setup_group0: group 0 ID present. Starting existing Raft server.
syslog_10.20.0.27:Dec 17 07:00:40 pippin scylla:  [shard  0] raft_group0 - Server 130d1875-0a2b-4d87-b088-2f99839b981c is starting group 0 with id b0378d80-7351-11ee-a0f8-520064d108ed
syslog_10.20.0.6:Dec 17 04:00:35 melchiorre scylla:  [shard  0] raft_group0 - setup_group0: group 0 ID present. Starting existing Raft server.
syslog_10.20.0.6:Dec 17 04:00:35 melchiorre scylla:  [shard  0] raft_group0 - Server 6aba4177-b447-4934-8960-e62a9f1b7301 is starting group 0 with id b0378d80-7351-11ee-a0f8-520064d108ed
syslog_10.20.0.8:Dec 17 05:30:36 gaspare scylla:  [shard  0] raft_group0 - setup_group0: group 0 ID present. Starting existing Raft server.
syslog_10.20.0.8:Dec 17 05:30:36 gaspare scylla:  [shard  0] raft_group0 - Server 47694372-6b86-4f6b-82c6-dc8f7ddb92ce is starting group 0 with id 30829ae0-9434-11ee-89fe-90a38ae2fe28
```

Note that gaspare has different group0 id.

Do you have earlier logs? Did you install this cluster with raft enabled or did you upgrade it to use raft?

**Comment by JackThird** [comment]
I attach historical logs:
- Gaspare (10.20.0.8)
[syslog.1.gz](https://github.com/scylladb/scylladb/files/13752776/syslog.1.gz)
[syslog.2.gz](https://github.com/scylladb/scylladb/files/13752887/syslog.2.gz)


- Melchiorre (10.20.0.6)
[syslog.1.gz](https://github.com/scylladb/scylladb/files/13752777/syslog.1.gz)
[syslog.2.gz](https://github.com/scylladb/scylladb/files/13752890/syslog.2.gz)
[syslog.3.gz](https://github.com/scylladb/scylladb/files/13752894/syslog.3.gz)
[syslog.4.gz](https://github.com/scylladb/scylladb/files/13752898/syslog.4.gz)


- Pippin (10.20.0.27)
[syslog.1.gz](https://github.com/scylladb/scylladb/files/13752781/syslog.1.gz)
[syslog.2.gz](https://github.com/scylladb/scylladb/files/13752900/syslog.2.gz)

I installed this cluster with 5.1, then upgrade to 5.2 (2023-10-25) and then upgrade to 5.4 (2023-12-21) .
Between 5.1 and 5.2 I activate the raft as per scylla [guide](https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/index.html).

**Comment by gleb-cloudius** [comment]
What happens is that when you bootstrapped Gaspare you started it first with the default config (addres 127.0.0.1 and seed also 127.0.0.1, raft is enabled). It booted and formed a single node cluster with a raft group that consists from itself. Later you changed the configuration to use local address 10.20.0.8 and seeds {10.20.0.6, 10.20.0.7} and probably disabled raft as well, but group0 config was already there, you did not remove system dir, so when you upgraded the cluster Gaspare used its existing raft group instead of joining others. We need to at least detect it somehow.

Some proof from Gaspare logs:

```
Dec  6 12:35:45 gaspare scylla:  [shard  0] init - seeds={127.0.0.1}, listen_address=127.0.0.1, broadcast_address=127.0.0.1
```

```
Dec  6 12:37:16 gaspare scylla:  [shard  0] raft_group0 - server 47694372-6b86-4f6b-82c6-dc8f7ddb92ce found no local group 0. Discovering...
Dec  6 12:37:16 gaspare scylla:  [shard  0] raft_group0 - server 47694372-6b86-4f6b-82c6-dc8f7ddb92ce found group 0 with group id 30829ae0-9434-11ee-89fe-90a38ae2fe28, leader 47694372-6b86-4f6b-82c6-dc8f7ddb92ce
```

```
Dec  6 12:37:41 gaspare scylla:  [shard  0] cql_server_controller - Starting listening for CQL clients on 127.0.0.1:19042 (unencrypted, shard-aware)
Dec  6 12:37:41 gaspare scylla:  [shard  0] init - serving
Dec  6 12:37:41 gaspare scylla:  [shard  0] init - Scylla version 5.2.11-0.20231126.a65838ee9c09 initialization completed.
```

```
Dec  6 14:11:49 gaspare scylla:  [shard  0] init - seeds={10.20.0.6, 10.20.0.7}, listen_address=10.20.0.8, broadcast_address=10.20.0.8
```

```
Dec  6 14:12:18 gaspare scylla:  [shard  0] cql_server_controller - Starting listening for CQL clients on 10.20.0.8:9042 (unencrypted, non-shard-aware)
Dec  6 14:12:18 gaspare scylla:  [shard  0] cql_server_controller - Starting listening for CQL clients on 10.20.0.8:19042 (unencrypted, shard-aware)
Dec  6 14:12:18 gaspare scylla:  [shard  0] init - serving
Dec  6 14:12:18 gaspare scylla:  [shard  0] init - Scylla version 5.2.11-0.20231126.a65838ee9c09 initialization completed.
```

**Comment by JackThird** [comment]
Yes I agree, 2023-12-06 my hosting substitute disks on gaspare and I reinstalled OS + scylla 5.2 with default config. 
Raft wasn't disabled because I kept defaults values (consistent_cluster_management=true) except IPs, directories and seeds.

Could you explain me how to fix this situation please? 
I tried to decommission gaspare node but failed because it pretends the other nodes UN.
`nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: std::runtime_error (decommission[718fc4fa-265a-4eb3-a1e2-53dda5313bd2]: Cannot start: nodes={10.20.0.27, 10.20.0.6} needed for decommission operation are down. It is highly recommended to fix the down nodes and try again.)`

Should I try removenode? I presume that others nodes (pippin, melchiorre) cannot communicate with gaspare.
I have RF=3 so I should remove gaspare without lose data.

**Comment by gleb-cloudius** [comment]
You need to run recovery procedure. @mykaul do you have a link handy?

**Comment by gleb-cloudius** [comment]
Found it: https://opensource.docs.scylladb.com/stable/architecture/raft.html#recover-raft-procedure

**Comment by tzach** [comment]
@gleb-cloudius, can we add guidelines to upgrade docs to fix such issues before the upgrade?

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius, can we add guidelines to upgrade docs to fix such issues before the upgrade?

The problem happened long before the upgrade. Upgrade just made it visible by probably issuing a schema change,

**Comment by mykaul** [comment]
Is there anything else to do here, or shall we close it?

**Comment by JackThird** [comment]
Hello, thank you for your answers, I will try recovery procedure next week, I will update you.

**Comment by JackThird** [comment]
Hello and happy new year.
Thanks to your advises I fixed the issue reported.

See you next time.
