### ISSUE TITLE
Add Software Bill of Materials (SBOM) of Open Source SW and tool to the doc

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#16533]
Each SW should include  its license.
Some context: https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/

SBOM can maybe be extract from the Make files (or similar)
Other (Java) project use Maven as SBOM.

**Comment by yaronkaikov** [comment]
@Annamikhlin FYI

**Comment by Annamikhlin** [comment]
Closing this issue in terms of PR https://github.com/scylladb/scylla-pkg/pull/4081 and another issue for docs: https://github.com/scylladb/scylladb/issues/18195
