### ISSUE TITLE
scylla-sstable: tool failed on deprecated configuration, while scylla itself doesn't

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#16538]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

since we started appended `--scylla-yaml-file /etc/scylla/scylla.yaml` to the command (so it can work with EaR)
```
Command: 'for i in `sudo find /var/lib/scylla/data/keyspace_complex/ -type f |grep -v manifest.json |grep -v snapshots |head -n 1`; do echo $i; sudo /usr/bin/scylla sstable dump-data --scylla-yaml-file /etc/scylla/scylla.yaml --keyspace keyspace_complex --table user_with_ck --sstables $i 1>/tmp/sstabledump.output || exit 1; done'
Exit code: 1
Stdout:
/var/lib/scylla/data/keyspace_complex/user_with_ck-6710bc90a24411ee957df74c21886c81/me-3gc6_0yv0_0qksi2feny1arja04o-big-Scylla.db
Stderr:
ERROR 2023-12-24 12:49:25,585 [shard 0:main] seastar - Exiting on unhandled exception: std::invalid_argument (Option is deprecated : consistent_cluster_management)
```

now we are failing on deprecated configuration options while scylla itself only warns about them
without failing.

## Impact

we can't test the sstable after rolling upgrade

## How frequently does it reproduce?
happens on all of the rolling upgrades tests

## Installation details

Kernel Version: 5.15.0-1050-aws
Scylla version (or git commit hash): `5.4.0-20231205.58a89e7a4231` with build-id `9b77be91b1fc75d71c99e1de13a69ea2ddb1f4d7`
Target Scylla version (or git commit hash): `5.5.0~dev-20231221.1ce07c6f27a3` with build-id `4c6695e3224902b07214b20d3b7c414d221c3f0c`

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-ae3f3ba4-4 (18.203.111.55 | 10.4.2.51) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-ae3f3ba4-3 (54.194.193.65 | 10.4.2.156) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-ae3f3ba4-2 (3.253.99.106 | 10.4.1.33) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-ae3f3ba4-1 (54.195.150.248 | 10.4.3.17) (shards: 7)

OS / Image: `ami-0345237a326a8e4bf` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5aad8174ba9d9f5985cf681ea128fe8b7b635a8d/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05)
- Show all stored logs command: `$ hydra investigate show-logs ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05`

## Logs:
- **db-cluster-ae3f3ba4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/db-cluster-ae3f3ba4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/db-cluster-ae3f3ba4.tar.gz)
- **sct-runner-events-ae3f3ba4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/sct-runner-events-ae3f3ba4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/sct-runner-events-ae3f3ba4.tar.gz)
- **sct-ae3f3ba4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/sct-ae3f3ba4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/sct-ae3f3ba4.log.tar.gz)
- **loader-set-ae3f3ba4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/loader-set-ae3f3ba4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/loader-set-ae3f3ba4.tar.gz)
- **monitor-set-ae3f3ba4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/monitor-set-ae3f3ba4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05/20231224_125903/monitor-set-ae3f3ba4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/197/)
[Argus](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=ae3f3ba4-5f58-4e58-9cef-c806fd9ebe05)
</details>

**Comment by mykaul** [comment]
consistent_cluster_management sounds like a change by the cluster team (perhaps due to 5ebfbf42bcff440012f6c2a37c27cf72f98db09e ) - @patjed41  ?

**Comment by fruch** [comment]
> consistent_cluster_management sounds like a change by the cluster team (perhaps due to [5ebfbf4](https://github.com/scylladb/scylladb/commit/5ebfbf42bcff440012f6c2a37c27cf72f98db09e) ) - @patjed41 ?

but still I would exact the tool to fail same as scylla, regardless 
i.e. if scylla doesn't fail on this configuration, that tool shouldn't fail

**Comment by roydahan** [comment]
It would be nice if we can get a quick fix for it in case it's simple, so we won't need to introduce workarounds for the tests.

**Comment by denesb** [comment]
The fix is simple, I will submit a PR tomorrow.

**Comment by denesb** [comment]
No OSS backports needed, removing label.
