### ISSUE TITLE
GROUP BY behavior change in 5.4.0? Possible bug?

### ISSUE THREAD

**Issue by A-Posthuman** [scylladb/scylladb#16531]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04 / Scylla AMI

I upgraded my cluster to 5.4.0 from 5.2.7 yesterday, things went pretty smoothly and afterwards I'm seeing a bit better performance.

However we have 1 program that started to fail and produce unexpected results, and this program uses the "GROUP BY" CQL clause. We tracked the problem down to apparently the program now receiving multiple rows back for the same value that should be grouped to just return the 1st row for each unique grouped value? At least that is how things behaved prior to 5.4.0, I don't know if this change was on purpose or is a bug?

Here's an edited version of the table schema in question:

```
CREATE TABLE a_table (
   pk varint,
   id varchar,
   ts timestamp,
   something varint,
   ...
   blah varchar,
   PRIMARY KEY (pk, id, ts)
) WITH CLUSTERING ORDER BY (id ASC, ts DESC)
  AND compaction = {'class': 'LeveledCompactionStrategy'}
  AND tombstone_gc = {'mode': 'repair'}
  AND comment = 'A comment'
;
```

And if I go into cqlsh now in 5.4.0 and do this query:

> select * FROM a_table WHERE pk = 7 AND id = 'an id that has multiple rows' AND ts > '2023-08-28 02:01:02+0000' GROUP BY id BYPASS CACHE;

Then it returns all the rows for 'an id that has multiple rows' instead of just the 1st row. We also see this behavior in this type of query that returns all the rows in the partition I think:

> select * FROM a_table WHERE pk = 59999 AND ts > '2023-08-28 02:01:02+0000' GROUP BY id ALLOW FILTERING BYPASS CACHE;

Prior to 5.4.0 that query only would return the 1st row for each unique id value in the partition. Can we get this behavior back? For now we are writing a workaround in our software.

**Comment by nyh** [comment]
@avikivity changed exactly this code path in 5.4, see https://github.com/scylladb/scylladb/commit/432cb02d643973aa0267a1dc42ccfe7feb99d153 which was supposed to fix this use case after some CQL expression rewrite broke it. I'm surprised we don't have a test for this case, I'll take a look and write the missing test.

**Comment by nyh** [comment]
> I'm surprised we don't have a test for this case, I'll take a look and write the missing test.

Turns out that although I wrote GROUP BY tests in test/cql-pytest/test_group_by.py (see commit c5195e0acd2b385483a1bf7c59729f955febbf26) that "almost" covered your case, but not exactly:

It turns out that the query
```
SELECT p,c1,c2,v FROM {table1} WHERE p=0 GROUP BY p
```
works as expected (returns just one row) - and the test verified this, but the seemingly same query:
```
SELECT * FROM {table1} WHERE p=0 GROUP BY p
```

With `*` instead of a list of columns, suddenly returns all the rows! Wow. @avikivity do you have any guess why this might happen? @avikivity do you want to fix this or should I (or let @ptrsmrn assign this regression?)?

In any case, I'll send now a PR with my test reproducing this issue.

**Comment by nyh** [comment]
By the way, @A-Posthuman if I'm correct in my analysis above this gives you a very simple workaround you can try: Try listing specific columns to SELECT, instead of `SELECT *`, and maybe it will start to work.

**Comment by nyh** [comment]
Created PR https://github.com/scylladb/scylladb/pull/16535 with a simple reproducer test for this regression (basically same test as above).

**Comment by A-Posthuman** [comment]
Thank you for the tip on the workaround, I just tested it in cqlsh and it does solve the issue. I'll modify our program to use that method for now.

**Comment by nyh** [comment]
I think I know why this bug happens, and it's indeed related to https://github.com/scylladb/scylladb/commit/432cb02d643973aa0267a1dc42ccfe7feb99d153:

Usually GROUP BY is used with aggregation functions. The query `SELECT x FROM tbl GROUP BY p` has no aggregation but there is an implicit aggregation - we're looking not for the sum (say) of each group (in this case, partition) but for the **first** of each group. So we rewrite the query as `SELECT first(x) FROM tbl GROUP BY p`. Clearly, we forget to do this rewriting for the case of `*`, and we need to rewrite it as `SELECT first(*)` - if this works - or `SELECT first(a), first(b), ...` expanding the `*` to all columns.

I'll work on a patch for this regression tomorrow morning.

As @A-Posthuman noted above, the fix will need to be backported to branch 5.4, but not to 5.2 which wasn't vulnerable to this bug (it had a different implementation of the expression evaluation).

**Comment by A-Posthuman** [comment]
Quick followup to report couple of things:

Using the workaround of selecting the individual column names does work, but I see higher than normal latency for this program's queries, Looking at the monitoring dashboard I see the 95% and 99% reads are running around 50% higher than typical, and that is after I cut out a lot of unneeded column names from the query - when I had all of them in there the latency was around 100% higher.

So hoping the "*" syntax returns soon and has normal latency.

Secondly I believe I ran into this separate bug when I specifically switched to using the GROUP BY with specific column names:

https://github.com/scylladb/scylladb/issues/16526

The error I received was:

> code=2100 [Unauthorized] message="User db_user has no EXECUTE permission on <function system."$$first$$"(varint)> or any of its parents"

I worked around that by switching my program to use my scylla superuser login. So far I don't think I've seen that error on any other types of queries since upgrading to 5.4.0. But I definitely have never seen it before with 5.2.7 using the regular non-superuser "db_user" account.

**Comment by nyh** [comment]
> Using the workaround of selecting the individual column names does work, but I see higher than normal latency for this program's queries, Looking at the monitoring dashboard I see the 95% and 99% reads are running around 50% higher than typical, and that is after I cut out a lot of unneeded column names from the query - when I had all of them in there the latency was around 100% higher.

@avikivity we should probably open a separate issue about that, but looking at the code now I'm starting the worry that the "first()" aggregator idea indeed hurts performance, because instead of just reading the first row from a partition and jumping to the next partition (did the old code know how to do that?) we now need to run an actual "aggregator" called first_function which ignores all but the first row - but needs to process all of them.

Anyway, looking at the code, it appears that today select_statement.cc has a separate path for prepared_selectors.empty() (this happens when you do "SELECT *") when we use selection::wildcard() and when it's not empty ("SELECT a,b,c") and we use selection::from_selectors() and uses all those first_function aggregators. So "SELECT *" doesn't do the first_function() thing at all, which is why we have this bug. I'm still trying to figure out how to fix it.

**Comment by nyh** [comment]
> Using the workaround of selecting the individual column names does work, but I see higher than normal latency for this program's queries, Looking at the monitoring dashboard I see the 95% and 99% reads are running around 50% higher than typical, and that is after I cut out a lot of unneeded column names from the query - when I had all of them in there the latency was around 100% higher.

What do you call the "typical" latency? Did you compare to a select of "*" that wrongly returned all the results instead of the the first one? Or to the old 5.2 benchmarks?

**Comment by A-Posthuman** [comment]
I was comparing to the 5.2 level of latency. This particular query has never had good latency, I always just chalked it up to the extra processing I was assuming scylla has to do on the server side to scan through the entire partition using "allow filtering" since I am skipping giving scylla the 2nd part of the pk because I want to get back a single row for every unique 2nd pk col.

Looking at my scylla monitoring reads latency chart, the rough 95% and 99% latency for the entire server when that program was running a few days ago was:

95%: ranging roughly from 28 ms to 44 ms
99%: ranging roughly from 78 ms to 90 ms

last night while running the program:

95%: 77 ms to 90 ms
99%: 128 ms to 160 ms

At normal times when this program isn't running, on 5.4.0 (which is slightly better latency than 5.2.7):

95%: 7 ms
99%: 9 ms

**Comment by nyh** [comment]
> I was comparing to the 5.2 level of latency. 
>...
> last night while running with 5.4.0 and the workaround the program:
> 
> 95%: 77 ms to 90 ms 99%: 128 ms to 160 ms

Thanks. It's hard to say if what hurt this specific query's latency was this specific change to expression processing, or something else - but the fact that reducing the number of columns on the SELECT made a big difference is indeed implicating :-( 
Let's try to think about this how I fix the original request the right thing. My first patch (which I plan to send very soon) will not improve the performance - "SELECT *" will behave like "SELECT a,b,c" behind the scenes and won't be any faster - so your workaround of SELECing only the columns you really need will actually be better than keep using "SELECT *". I may open a new issue about the performance regression later.

**Comment by A-Posthuman** [comment]
Is it possible to look back at the older GROUP BY code to see how it handled "*" queries? Using that older code on 5.2.7 seemed to have superior latency. But maybe there were good reasons to change it I'm not aware of that can't be reverted?

**Comment by nyh** [comment]
> Is it possible to look back at the older GROUP BY code to see how it handled "*" queries? Using that older code on 5.2.7 seemed to have superior latency. But maybe there were good reasons to change it I'm not aware of that can't be reverted?

I hope that @avikivity, who wrote the new code, can chime in. The purpose of this rewrite was a complete overhaul of the expression-handling code to make it easier to extend and debug (the old one was a really big mess). I think that both old and new code had to process all the rows; The old code did something simpler and more hard-coded on each row, and the new code is more general, but I'm having a hard time how this can explain doubling the latency.

I wonder (maybe @avikivity remembers) if the aggregation code also changed since 5.2 - maybe the first() aggregation, which should have been trivial and involve just one shard (because the query is a single-partition query) somehow became more complicated and more "parallelized" for no good reason? It can also be something very different which regressed and has nothing to do with the GROUP BY or first() aggregation - can you please check the performance of a similar ALLOW FILTERING query just without GROUP BY?

**Comment by A-Posthuman** [comment]
regarding queries on this table without GROUP BY:

select 1 complete pk's rows, no allow filtering, tracing on, 3 runs:
trace start: run 1: 11:12:30.594000, run 2: 11:16:03.787000, run 3: 11:18:33.019000
trace end: run 1: 11:12:30.599007, run 2: 11:16:03.792116, run 3: 11:18:33.024413
~5 ms on average

same, with allow filtering, tracing on, 3 runs:
trace start: run 1: 11:14:33.772000, run 2: 11:17:34.887000, run 3: 11:19:17.482000
trace end: run 1: 11:14:33.783354, run 2: 11:17:34.892098, run 3: 11:19:17.487853
~7 ms on average, but mainly due to the run 1 outlier

so not clear if there is any significant problem with allow filtering, 2 out of 3 runs appear roughly similar latency for this simple query

**Comment by nyh** [comment]
I sent a pull request with a fix for the "SELECT *" bug: https://github.com/scylladb/scylladb/pull/16559
And opened an issue about the remaining performance regression: https://github.com/scylladb/scylladb/issues/16560

**Comment by avikivity** [comment]
The new code could be slower, especially if you have large blobs. Is this the case?

**Comment by A-Posthuman** [comment]
the last set of latencies I posted were from a "*" query, here is the same query with all columns explicitly named:

select 1 complete pk's rows, no allow filtering, tracing on, 3 runs:
trace start: run 1: 11:12:30.594000, run 2: 13:25:59.597000, run 3: 13:27:15.229000
trace end: run 1: 11:12:30.599007, run 2: 13:25:59.606857, run 3: 13:27:15.239838
~8.5 ms on average

same, with allow filtering, tracing on, 3 runs:
trace start: run 1: 13:25:10.414000, run 2: 13:26:38.008000, run 3: 13:28:03.496000
trace end: run 1: 13:25:10.426091, run 2: 13:26:38.018205, run 3: 13:28:03.506801
~11 ms on average

So we can see using named cols vs. "*" tends to be worse from this quick comparison. I believe the db was roughly loaded the same in both tests, but I didn't check how many compactions were running. Also on this test the allow filtering version seems consistently a bit worse.

As for the characteristics of this table and the data, I don't think it's anything extreme. This particular primary key was returning 9 rows in these tests. The table is for storing time-series data, where the items of interest are evenly spread over 1 million partition keys via the murmur3 hashing technique, so there are no hotspots. There are something like 500 unique 'id' values that are used as the second part of the primary key, so around 500 million total unique ids in the entire table. Currently on average each id has maybe 3 rows of time series data saved. Here is the tablestats output:

```
                SSTable count: 1182
                SSTables in each level: [13/4, 9, 98, 1062/1000]
                Space used (live): 191246696135
                Space used (total): 191246696135
                Space used by snapshots (total): 0
                Off heap memory used (total): 567204446
                SSTable Compression Ratio: 0.4495150751821859
                Number of partitions (estimate): 2716051
                Memtable cell count: 300203
                Memtable data size: 448448238
                Memtable off heap memory used: 500039680
                Memtable switch count: 181
                Local read count: 10225515
                Local read latency: 7.437 ms
                Local write count: 27303083
                Local write latency: 0.022 ms
                Pending flushes: 0
                Percent repaired: 0.0
                Bloom filter false positives: 364
                Bloom filter false ratio: 0.00004
                Bloom filter space used: 7080608
                Bloom filter off heap memory used: 7080608
                Index summary off heap memory used: 60084158
                Compression metadata off heap memory used: 0
                Compacted partition minimum bytes: 51
                Compacted partition maximum bytes: 1358102
                Compacted partition mean bytes: 172336
```

The AWS instance type is not very beefy, it's 3 instances of Is4gen.xlarge (4 cores each instance)

**Comment by avikivity** [comment]
Are the two systems similar enough in terms of load for comparison? Better to test on idle systems with exactly the same data.

**Comment by nyh** [comment]
Backported to next-5.4 - 8ca57947563a036f1d6893bf41f2a4ab87a1aa8e.
No further backports are needed - 5.2 was not vulnerable to this issue, this feature broke in the expression rewrite that happened between 5.2 and 5.4.

**Comment by nyh** [comment]
@A-Posthuman this issue is closed as I fixed the behavior change, but if you want to continue discussing the performance regression, let's do it on the new issue I opened for that, https://github.com/scylladb/scylladb/issues/16560.

Please note that the performance problem is *not* the "*" vs an explicit list of column names - as far as I understand the code, even in 5.2 the "*" didn't really behave any differently than an explicit list of column names, and in fact in some cases "*" might not even be _all_ the columns (when materialized views are used, in some cases we add "virtual" columns which SELECT * do not select). So the workaround you used before this patch, to SELECT specific column names, can remain in your code and shouldn't cause a performance regression, and whatever the performance regression was - we should solve it.
