### ISSUE TITLE
Implement tablets splitting

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16536]
Design doc: https://docs.google.com/document/d/1k1u9r9kByvc6d6lF52fhHCyFkCNgDnU4L6h1qYwnm_0/edit?pli=1#heading=h.97hvtzxpawvi

@raphaelsc / @tgrabiec please fill description

**Comment by raphaelsc** [comment]
@bhalevy please rename it to "Implement tablets splitting". monitor is only a replica component of the whole feature.
