### ISSUE TITLE
RFC: Add API to disable/enable tablet load-balancing

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16553]
To simplify distributed operations like snapshot or repair, and until they are fully integrated with the tablets load-balancer,
consider implementing an api to control cluster-wide tablets load balancing, similar to the existing enable/disable auto-compaction apis.

Open questions:
- Can/should we provide per-keyspace control.
- Should this switch be persistent? and if so, where should it be persisted.

**Comment by nyh** [comment]
We do already have a REST API to do this, /storage_service/tablets/balancing, but it is _not_ per-keyspace, _not_ persistent, and as far as I understand _not_ cluster wide (but @tgrabiec please correct me if I'm wrong), so it might not fit what you hoped to see. It was good enough for my testing, though.

**Comment by bhalevy** [comment]
Looking at `storage_service::set_tablet_balancing_enabled`, the operation is global using group0
and the value of `tablet_balancing_enabled` is kept persistently in system.topology.
Given that, we can close this issue with d1c1b592362ce6d5f0e94828b390b042e65cf758

**Comment by tgrabiec** [comment]
> We do already have a REST API to do this, `/storage_service/tablets/balancing`, but it is _not_ per-keyspace, _not_ persistent, and as far as I understand _not_ cluster wide (but @tgrabiec please correct me if I'm wrong), so it might not fit what you hoped to see. It was good enough for my testing, though.

It is cluster-wide and persistent (based on group0).
