### ISSUE TITLE
Make the "me" sstable format mandatory

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16551]
The `me` sstable format includes an important feature of storing the `host_id` of the local node when writing sstables.
The is crucial for validating the sstable's `replay_position` in stats metadata as it is valid only on the originating node and shard (https://github.com/scylladb/scylladb/issues/10080), therefor we would like to make the `me` format mandatory.

The `me` format will be chosen automatically if all nodes in the cluster support the `ME_SSTABLE_FORMAT` feature.
However, in upgrade scenarios, the new version will have to fallback to the `md` format until all nodes are upgraded.
Once all supported scylladb versions support the `me` sstable format one could upgrade all sstables and then perform a rolling upgrade to the newest scylladb version that will make `me` mandatory and refuse to start in the presence of sstables using older formats.

**Comment by bhalevy** [comment]
Also, some of our unit tests still require support for the `mc` format.
This should be taken into consideration.

**Comment by avikivity** [comment]
`me` was introduced in Jan 2022. Our two-year rule allows us to assume a feature is present after two years, so soon we can just assume everything supports `me`.

**Comment by avikivity** [comment]
> Also, some of our unit tests still require support for the `mc` format. This should be taken into consideration.

We still support reading everything. The question is whether we allow the user to write to a downlevel format.

**Comment by tchaikov** [comment]
currently, we allow user to specify the default sstable to either `md` or `me` using scylla's configuration option of `sstable_format`. and we also have cluster `MD_SSTABLE_FORMAT` and `ME_SSTABLE_FORMAT` cluster features which are disabled if the said `sstable_format` is lower than the corresponding cluster feature. so, per Avi's comment mentioning the two-years policy, `sstable_format` option does not need to support sstable formats lower than md which was introduced in a37eaaa022544195e5b539a47a8e34440cfaff6b in Apr 2020, namely, we don't need to check for `kc`, `la` and `mc` in `feature_config_from_db_config()` anymore. also, these values are not listed as allowed values of `sstable_format` at all in `config.cc`.

i would like to be more specific on making `me` sstable format mandatory. IIUC, this implies

1. the config option of `sstable_format` is not respected anymore. if the cluster agrees on using `ME_SSTABLE_FORMAT`, all nodes would be using `me` for writing sstables. if `sstable_format` is specified with `md` on a node which supports `me`, a warning is printed when the node starts. but the node still boots.
2. in the upgrade scenario, i don't think we need to "upgrade all sstables and then perform a rolling upgrade to the newest scylladb version". as, we still read `md` sstables, and when writing new sstables, as long as the cluster agrees on using `ME_SSTABLE_FORMAT`, the new sstables would be written using `me` format. so, after a while, unless the data is ancient and the rows in them are not compacted, it would be in `me`. or, we have to enumerate all sstables in older formats, and rewrite them in`me` ?

**Comment by tchaikov** [comment]
> > Also, some of our unit tests still require support for the `mc` format. This should be taken into consideration.
> 
> We still support reading everything. The question is whether we allow the user to write to a downlevel format.

i think they are allowed to write in `md` only if the cluster is upgrading and the cluster feature of `ME_SSTABLE_FORMAT` is not enabled yet -- the existing nodes **could** still set their `sstable_format` to `md`. but once they upgrade to a new scylla version which enforces `me`, `sstable_format` will not be used anymore.

**Comment by bhalevy** [comment]
> after a while, unless the data is ancient and the rows in them are not compacted, it would be in me. or, we have to enumerate all sstables in older formats, and rewrite them in `me`?

For that we have [nodetool upgradesstables](https://opensource.docs.scylladb.com/stable/operating-scylla/nodetool-commands/upgradesstables.html).
There's no need to do that automatically.
Regular compaction will do the conversion implicitly over time.

**Comment by bhalevy** [comment]
> > > Also, some of our unit tests still require support for the `mc` format. This should be taken into consideration.
> > 
> > 
> > We still support reading everything. The question is whether we allow the user to write to a downlevel format.
> 
> i think they are allowed to write in `md` only if the cluster is upgrading and the cluster feature of `ME_SSTABLE_FORMAT` is not enabled yet -- the existing nodes **could** still set their `sstable_format` to `md`. but once they upgrade to a new scylla version which enforces `me`, `sstable_format` will not be used anymore.

Correct.

**Comment by tchaikov** [comment]
@mykaul hi Yaniv, shall we use 5.5 for the next milestone? as per Benny, the master is still on 5.5.dev. and i found the previous branch is `branch-5.4`. see the discussion at https://github.com/scylladb/scylladb/pull/16716#discussion_r1448960264 .

**Comment by mykaul** [comment]
> @mykaul hi Yaniv, shall we use 5.5 for the next milestone? as per Benny, the master is still on 5.5.dev. and i found the latest branch was `branch-5.4`. see the discussion at [#16716 (comment)](https://github.com/scylladb/scylladb/pull/16716#discussion_r1448960264) .

Yes, there's a bit of confusion here. In GH, we refer to 6.0. We may eventually decide to bump the no. to 6.0, or rename in GH 6.0 to 5.5. For the discussion above, please keep 6.0.

**Comment by tchaikov** [comment]
ack. thanks!

**Comment by mykaul** [comment]
@annastuchlik , @tzach  - do we wish to document this somewhere?

**Comment by tchaikov** [comment]
@mykaul FWIW, it's documented at https://opensource.docs.scylladb.com/master/architecture/sstable/sstable3/index.html , quote from this document

> ScyllaDB 5.5 and above, the `me` format is mandatory, and `md` format is used only when upgrading from an existing cluster using `md`. The `sstable_format` parameter is ignored if it is set to `md`.

the document change was landed as a part of #16716

**Comment by tchaikov** [comment]
Anna, thank you. will use 6.0 in future.
