### ISSUE TITLE
Performance regression in 5.4.0, perhaps related to GROUP BY

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16560]
This issue is about a performance regression between Scylla 5.2 and 5.4 noticed by @A-Posthuman in https://github.com/scylladb/scylladb/issues/16531#issuecomment-1869012655.

The user reports that tail latencies generally **improved** when upgrading from 5.2 to 5.4, but a specific query became significantly slower. The query looks something like

```
select * FROM a_table WHERE pk = 7 AND id = 'an id that has multiple rows' AND ts > '2023-08-28 02:01:02+0000' GROUP BY id BYPASS CACHE;
```

He reports that in ScyllaDB 5.2 he saw 99th percentile latencies of around 78-90ms, but in ScyllaDB 5.4, he saw 128-160ms.

This query involves a lot of things - there is a filter, a GROUP BY, BYPASS CACHE, any of these could have regressed in performance; Still, we **suspect** that the regression has to do with the recent GROUP BY rewrite last June (see PR #14467 and in particular commit 432cb02d643973aa0267a1dc42ccfe7feb99d153):

The suspicious sign that led us to this guess is that if we replace the `*` selector with a list of column names (as a workaround for #16531), the latency seemed to highly depend on the **number** columns we decide to SELECT: #16531 reports that listing just a few column names increased tail latency by 50%, but selecting all of them increases it by 100%. This observation rules out filtering or bypass cache or sstable handling or other stuff, which is unrelated to the number of selected columns. Conversely, GROUP BY does depend on it:

In the new 5.4 code, a `SELECT a,b,c,d GROUP BY id` is translated to `SELECT first(a), first(b), first(c), first(d) GROUP BY id`. These `first(a)` etc. are a new type **aggregator**, which just returns the first value in the group. Maybe this implementation is inefficient in some sense: Maybe it has a lot of overhead compared to the old 5.2 code which was more hard-coded? Maybe aggregating both `first(a)` **and** `first(b)` for some reason requires doing doubling the work? Maybe the fairly recent introduction of parallel aggregation made some of this even worse?

These are all guesses... If after more testing we discover that this regression was caused by something else, not by GROUP BY, so that some of my guesses above were way off, please edit this text.

 CC @avikivity @ptrsmrn

**Comment by A-Posthuman** [comment]
After further examination of some longer program runs, and looking back at several different days of data before 5.4.0, I no longer think there is a significant performance difference. Last night the program finished its run within like 1% of the runtime of how it performed under 5.2.7, so I think I was overreacting to seeing some short term spikes in the performance on 5.4.0 but looking at the charts now over longer time frames it looks ok to me. Sorry for the confusion!

**Comment by nyh** [comment]
Excellent :-) Thanks. So I'll close this issue.
