### ISSUE TITLE
Translate from host IDs to IPs on error messages

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#16588]
Example:
```
WARN  2023-12-31 14:45:55,123 [shard 0:main] direct_failure_detector - unexpected exception when pinging 562d3b89-1cf0-4640-bf42-7ce1e4576627: seastar::rpc::unknown_verb_error (unknown verb)
```

It's quite a headache to get which node is 562d3b89-1cf0-4640-bf42-7ce1e4576627. In fact, in this specific node, all I see is:
```
INFO  2023-12-31 14:45:54,623 [shard 0:main] raft_group_registry - marking Raft server 562d3b89-1cf0-4640-bf42-7ce1e4576627 as alive for raft groups
```

And in fact, in all 4 nodes participating in this cluster, that's all I could find.

**Comment by kbr-scylla** [comment]
The error itself may result from missing translation.

**Comment by mykaul** [comment]
> The error itself may result from missing translation.

That's where we need more elaborate error. It may indeed be the case - I just don't know - and looking at all logs, I could not figure out what node(/IP) is represented by this UUID.

**Comment by kbr-scylla** [comment]
@mykaul regarding your specific case, do you still have the nodes logs? The host ID should be one of the nodes present in the cluster. It's a member of group 0, or at least attempted to join group 0, otherwise the failure detector wouldn't ping it.

**Comment by mykaul** [comment]
ARGH. Lost the CI test who had this failure I've looked at. If I'll find it, I'll re-open.

**Comment by kbr-scylla** [comment]
@mykaul I think the translation is still valuable, we can do it under the condition that it's present. But the issue is low priority I think.
