### ISSUE TITLE
test.py: ignore host's env SCYLLA_CONF

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#16583]
test.py inherits its env from the user, which is the right thing: some python modules, e.g. logging, do accept env-based configuration. However, test.py also starts subprocesses, i.e. tests, which start other subprocesses, e.g. scylladb instances. And when the instance is started without an explicit configuration file, SCYLLA_CONF from user environment can be used.

This leads to spurious test failures:
```
E       AssertionError: assert None is not None                                                                                                               
E        +  where None = <function search at 0x7f56bb417560>('error processing arguments: no sstables specified on the command line', 'ERROR 2023-12-29 15:25:
27,533 [shard 0:main] seastar - Exiting on unhandled exception: std::invalid_argument (Option is deprecated : force_schema_commit_log)\n')                    
E        +    where <function search at 0x7f56bb417560> = re.search          
```

**Comment by benipeled** [comment]
> How come this issue didn't get a "backport candidate" label? We don't need to backport this fix so I'm not worried (it's just a test framework usability improvement) but the bot should have added a "backport candidate" when the issue was fixed, and I worried that if it missed this one it might miss it in other cases too.
> 
> I suspect that because @kostja used the syntax [gh-16583](https://github.com/scylladb/scylladb/issues/16583) instead of the more "usual" #16583, the backport missed the reference... @benipeled can you please check if this might explain it, and if so, expand the reference regexp with yet another possibility? Thanks.

Yes it explains it - see [0] - and no, I don't think we should add the gh-* pattern but users should align to the known/agreed patterns

[0] https://github.com/scylladb/jenkins/tree/master/backport-queue#pattern-rules

**Comment by nyh** [comment]
> > How come this issue didn't get a "backport candidate" label? We don't need to backport this fix so I'm not worried (it's just a test framework usability improvement) but the bot should have added a "backport candidate" when the issue was fixed, and I worried that if it missed this one it might miss it in other cases too.
> > I suspect that because @kostja used the syntax [gh-16583](https://github.com/scylladb/scylladb/issues/16583) instead of the more "usual" #16583, the backport missed the reference... @benipeled can you please check if this might explain it, and if so, expand the reference regexp with yet another possibility? Thanks.
> 
> Yes it explains it - see [0] - and no, I don't think we should add the gh-* pattern but users should align to the known/agreed patterns

The problem is that neither the authors nor the reviewer (me) remembered which patterns we agreed on. I guess @kostja used it because he read somewhere that works - and it did. And when I saw it as a reviewer I was initially surprised but then checked myself - and noticed github does understand this syntax, so I didn't complain. The auto-closing of the issue also worked.  didn't remember that our bots don't understand this syntax.

Instead of having to remind developers and reviewers which syntaxes are recognized (nobody will ever guess to look in https://github.com/scylladb/jenkins/tree/master/backport-queue#pattern-rules), I think it will be better to just make an attempt to support **all** patterns that github supports. I'm not saying that we'll get the patterns perfect immediately - maybe this is the first time you are seeing this "gh-*" pattern and this is why we missed it (does github have an official list?) - but if we fix support for every pattern we encounter, like "gh-*" now, we only need to fix each of them once, instead of "educating" the users again and again which patterns they can use, for years.

> 
> [0] https://github.com/scylladb/jenkins/tree/master/backport-queue#pattern-rules

**Comment by nyh** [comment]
Opened https://github.com/scylladb/jenkins/issues/32 about fixing the backport bot

**Comment by benipeled** [comment]
> > > How come this issue didn't get a "backport candidate" label? We don't need to backport this fix so I'm not worried (it's just a test framework usability improvement) but the bot should have added a "backport candidate" when the issue was fixed, and I worried that if it missed this one it might miss it in other cases too.
> > > I suspect that because @kostja used the syntax [gh-16583](https://github.com/scylladb/scylladb/issues/16583) instead of the more "usual" #16583, the backport missed the reference... @benipeled can you please check if this might explain it, and if so, expand the reference regexp with yet another possibility? Thanks.
> > 
> > 
> > Yes it explains it - see [0] - and no, I don't think we should add the gh-* pattern but users should align to the known/agreed patterns
> 
> The problem is that neither the authors nor the reviewer (me) remembered which patterns we agreed on. I guess @kostja used it because he read somewhere that works - and it did. And when I saw it as a reviewer I was initially surprised but then checked myself - and noticed github does understand this syntax, so I didn't complain. The auto-closing of the issue also worked. didn't remember that our bots don't understand this syntax.
> 

I agree that we shouldn't expect users to look for the accepted keywords but make it simple - there is an open issue (can't find it now) by @avikivity to auto-scan commits on branches that missing the accepted-keywords and alert the author/maintainer (and we have @kostja's suggestion about the cover letter template which is pretty similar - enforce standards)

> Instead of having to remind developers and reviewers which syntaxes are recognized (nobody will ever guess to look in https://github.com/scylladb/jenkins/tree/master/backport-queue#pattern-rules), I think it will be better to just make an attempt to support **all** patterns that github supports. I'm not saying that we'll get the patterns perfect immediately - maybe this is the first time you are seeing this "gh-_" pattern and this is why we missed it (does github have an official list?) - but if we fix support for every pattern we encounter, like "gh-_" now, we only need to fix each of them once, instead of "educating" the users again and again which patterns they can use, for years.
> 

`gh-` isn't a github's keyword

> > [0] https://github.com/scylladb/jenkins/tree/master/backport-queue#pattern-rules

**Comment by kostja** [comment]
I checked now https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue  and you're right @benipeled - gh- is not a keyword.

**Comment by nyh** [comment]
> I checked now https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue and you're right @benipeled - gh- is not an official keyword. I wonder why it works and apparently I had it somewhere wired up that it works...

What do you mean "it's not a keyword"? Yes, it's missing in the specific document (like our documentation, their documentation also isn't perfect) but listed in their another document, about link formats.
Most importantly, it **works** - it did close the issue automatically, and I am sure you read somewhere that it works and didn't just "invent" this syntax.
