### ISSUE TITLE
View-updates after streaming doesn't work with tablets

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16598]
When enabling tablets, the dtest `materialized_views_test.py::TestMaterializedViews::test_mvs_populating_from_existing_data` fails. It generates millions (!) of errors

```
Tried to obtain per-keyspace effective replication map of ks but it's per-table
```

The backtrace points to view_update_generator.cc calling get_keyspace_local_ranges().

The log messages hint that **streaming** is somehow involved. As far as I can tell this test does not do repair, but it seems we have some sort of automated tablet migration, because we see in the log just before the above error:

```
INFO  2024-01-01 18:50:10,369 [shard 0:strm] range_streamer - Tablet migration with 127.0.74.4 for keyspace=ks succeeded, took 0.008231445 seconds
INFO  2024-01-01 18:50:10,369 [shard 0:strm] range_streamer - Tablet migration succeeded, took 0 seconds, nr_ranges_remaining=0
INFO  2024-01-01 18:50:10,413 [shard 0:strm] view_update_generator - Processing ks.tm_table: 210kB in 1 sstables
```
and after it
```
WARN  2024-01-01 18:50:10,413 [shard 0:strm] view_update_generator - Processing ks failed for table tm_table:seastar::internal::backtraced<std::runtime_error> (Tried to obtain per-keyspace effective replication map of ks but it's per-table 
```

It seems like we streamed some tablet from another node, and after receiving it we wanted to run view updates on the newly streamed data, and this failed because the code doesn't work with tablets.

We need to understand:
1. Why we needed to do any view updates in this case at all. This is **not** repair. But, it's possible that because streaming is happening during view building, these view updates are happening. Maybe this is fine. Should we disable tablet movements during view building because they hurt performance (but should work...).
2. We need to fix the view_update_generator code to work correctly with tablets and not try a get_keyspace_local_ranges(). This function shouldn't even exist with tablets...
3. Understand why this failure resulted in millions of errors and a multi-gigabyte log file. Do we have a tight loop in view_update_generator that doesn't sleep between retries after an error?

**Comment by nyh** [comment]
The problematic code uses `find_keyspace(ks).get_effective_replication_map()->get_ranges(my_address)` which doesn't work because with tablets you shouldn't get the ERM of a keyspace, you should get one of a tablet.
But sadly, the obvious fix:
```
find_column_family(ks, cf).get_effective_replication_map()->get_ranges(my_address);
```
doesn't work - it turns out that while there is a `vnode_effective_replication_map::get_ranges(inet_address ep)`, there is no such function for non-vnode ERM. Those have other more-elaborate versions of this function I don't understand and now I need to figure out how to use them - or I need to write a new get_ranges function :-(
CC @tgrabiec

**Comment by nyh** [comment]
@mykaul removed the backport candidate tag for this fix, which perhaps makes sense, but the third patch of the PR, which fixes a log-spam problem which was incidental to the root bug, ended up being needed again, in https://github.com/scylladb/scylladb/issues/18222. I don't know if we should backport just one out of 3 patches in the PR, or what.

**Comment by mykaul** [comment]
It'd be misleading to add the back port label for just 1 incindental fix here. I'm also not sure it's important enough to backport.

**Comment by nyh** [comment]
Ok. I'll not backport the entire thing, I added in #18222 the idea to backport just the log-spam-avoidance patch. The problem that caused me to write this patch (and I guess, the user in #18222 to complain) was that the infinite log spam loop turned what might have been a relatively-benign problem (a bug detected, and the node needing reboot) into a disaster where the entire disk is filled with logs (in my own case, it was even worse - the test case decided to read the logs into memory and filled all of memory ;-)).

**Comment by mykaul** [comment]
If the disk is filled with logs (in a production setup) we have a log rotation issue.
