### ISSUE TITLE
intra-node tablet migration

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#16594]
@raphaelsc noticed we don't migrate tablets between shards on the same node. So we end up with imbalance. This is also necessary for resharding.

**Comment by avikivity** [comment]
Option 1:
 - internal API for migrating a compaction group to a different shard; can be done by taking a snapshot and materializing it on another shard
 - RPC endpoint exposing this
 - changes to the replica tablet array so it can store > 1 compaction group per tablet
 - changes to storage_proxy so it can consider two replicas on the same host (but different shard) as two different replicas
 
Option 2:
 - handle it internally within replica::table so it doesn't look like migration, but as an atomic switch

**Comment by dorlaor** [comment]
Would a stupid approach that ignores the target shard is in the same node
and run
the whole streaming procedure work? Silly but can be the simplest for gen #1

**Comment by avikivity** [comment]
no

**Comment by mykaul** [comment]
Added this as a feature (while I disagree it is) to the 6.0 features list - and now will track it towards feature freeze readiness.
