### ISSUE TITLE
direct failure detector: make ping timeout configurable and increase the default

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16607]
Direct failure detector works by pinging each node. Each ping message has a hardcoded timeout: 300ms. In multi-DC environments with network jitter this might be too small (https://github.com/scylladb/scylladb/issues/16410). We should increase it. Preferably, make it tunable, and set the default to a higher value than 300ms.

Ref: https://github.com/scylladb/scylladb/issues/16410
Ref: https://github.com/scylladb/scylla-enterprise/issues/4134

**Comment by kbr-scylla** [comment]
This impacts users, may cause frequent Raft leader changes decreasing availability. (https://github.com/scylladb/scylladb/issues/16410)

**Comment by kbr-scylla** [comment]
@mykaul I'd consider making it higher priority / earlier milestone, as it affects existing releases (5.2 -- Raft-based schema).

**Comment by mykaul** [comment]
What's the downside of at least making the default longer? 1s or so? Longer timeout to reach some raft state?

**Comment by kostja** [comment]
Yes, a bit more sluggish tests mostly.

**Comment by kbr-scylla** [comment]
The problem described in https://github.com/scylladb/scylladb/issues/16410 is easily shown by simulating network delays on loopback interface and starting two-node Scylla cluster locally
```
tc qdisc add dev lo netem delay 150ms 20ms
```
note: the above actually adds 300ms +-40ms latency (150ms +-20ms when the packet leaves and returns)

result:
```
INFO  2024-04-26 19:13:44,926 [shard 0:main] raft_group_registry - marking Raft server 31117c72-ad12-48d1-af10-8abaffed146f as dead for raft groups
INFO  2024-04-26 19:13:45,224 [shard 0:main] raft_group_registry - marking Raft server 31117c72-ad12-48d1-af10-8abaffed146f as alive for raft groups
INFO  2024-04-26 19:13:47,108 [shard 0:main] raft_group_registry - marking Raft server 31117c72-ad12-48d1-af10-8abaffed146f as dead for raft groups
INFO  2024-04-26 19:13:47,388 [shard 0:main] raft_group_registry - marking Raft server 31117c72-ad12-48d1-af10-8abaffed146f as alive for raft groups
INFO  2024-04-26 19:13:50,709 [shard 0:main] raft_group_registry - marking Raft server 31117c72-ad12-48d1-af10-8abaffed146f as dead for raft groups
INFO  2024-04-26 19:13:51,310 [shard 0:main] raft_group_registry - marking Raft server 31117c72-ad12-48d1-af10-8abaffed146f as alive for raft groups
INFO  2024-04-26 19:13:54,598 [shard 0:main] raft_group_registry - marking Raft server 31117c72-ad12-48d1-af10-8abaffed146f as dead for raft groups
```

**Comment by kbr-scylla** [comment]
There is a listener attached to the detector, with a threshold of 1000ms. This means that if the detector does not get a response from a given endpoint for 1000ms, the listener will receive a notification that the endpoint is dead. (This listener is for Raft groups and is the one printing the above message.)

Unfortunately, the design of direct failure detector's pinging is... not very clever (sorry for that.)
- pings are timed out after 300ms
- pings are done sequentially i.e. previous ping has to finish (or timeout) before next ping starts

With 300ms latencies with some jitter, we sometimes get a successful ping within 1000ms interval, but other times we get 3 subsequent pings timing out.

Hence the Raft listener is getting interleaved "alive" and "dead" notifications.

**Comment by kbr-scylla** [comment]
I think the design needs to be improved. The current design of sequential pinging, with notifying listeners in-between pings, is oversimplistic -- it may be good enough for low latency environments but not for wide-area networks.

As a quick workaround, we can increase the ping timeouts and increase the Raft listener threshold, which should be fine for our current usage of Raft (replicating metadata). I'll set the ping timeout default to `600ms` which should be more than enough even for pinging opposite side of Earth, and increase the Raft listener threshold to 2s. (So we'll need three failed pings to mark node as dead, and leader elections will start after ~2s from node dying.)

For the future, we'll want to reduce the Raft listener threshold again (because we want leader elections to happen fast after failure when using Raft for data path), that will require improving the failure detector design.

**Comment by kostja** [comment]
Maybe use an epidemic algorithm but do it properly this time? E.g. do something like swim?
