### ISSUE TITLE
Tablet-based tables should only work in tombstone_gc mode "repair"

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16627]
Running `nodetool repair -pr` on all nodes may miss some tablet if it migrated across the nodes between calls, and changed its primary owner. 

To prevent data resurrection, all tablet-based tables should work with tombstone_gc mode repair. This way when tablet was not repaired in this cycle, we won't expire tombstones for ranges which were not repaired.

Attempts to change the gc mode for such tables using DDL should be rejected.

**Comment by bhalevy** [comment]
@denesb can we please accelerate that for 6.0?

**Comment by asias** [comment]
@denesb This looks like a good candidate for @Deexie.  FYI: The commit a8ad385ecd3e2b372db3c354492dbe57d9d91760 introduces the tomgstone_gc repair mode. 

I agree we need to make the repair mode the default. 

I doubt we should reject the timeout mode for all tablet tables though. People can disable migration then run repair to work around the issue.  If we are serious about this, we should make SM disable migration for 6.0. 

Also, one might never use delete but ttl to delete data,  they can run the cluster without repair at all.

**Comment by tgrabiec** [comment]
If we allow changing repair mode to timeout, we should document that with tablets it should be used only when repair is not required. Otherwise, users may unknowingly run in an unsafe way.

**Comment by tgrabiec** [comment]
> Also, one might never use delete but ttl to delete data, they can run the cluster without repair at all.

Is this true in practice though that repair can be skipped? There are system distributed tables, out of user's control, which need to be repaired too.

**Comment by bhalevy** [comment]
@Deexie / @denesb where are we standing with this issue?

**Comment by Deexie** [comment]
> @Deexie / @denesb where are we standing with this issue?

The change waits for review. I just pinged
