### ISSUE TITLE
cql_tests.TestTruncate.test_cql_query_filtering_without_indexes fails due to number of entries in returned result is greater than expected

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16621]
```
    def test_cql_query_filtering_without_indexes(self):
...
        selected_index = 6
        inserted_times.sort()
        count_above_selected_time = loop_size - selected_index - 1
        selected_time = inserted_times[selected_index]
        selected_time_str = time.strftime("%H:%M:%S", selected_time)

        # CQL statement with relational operations( =, !=, >, < ).
        q2 = "Select item_id from t2 where insert_time > '{}' allow filtering;"\
            .format(selected_time_str)
        q2_result = rows_to_list(session.execute(q2))
        logger.debug(f"Query: {q2}, Len_Result: {len(q2_result)}, Result: {q2_result}")
>       assert len(q2_result) == count_above_selected_time, f"The returned list count doesnt match the calculated count"
E       AssertionError: The returned list count doesnt match the calculated count
E       assert 492 == 493
E        +  where 492 = len([[23], [114], [53], [110], [91], [128], ...])
```
see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5522/testReport/junit/cql_tests/TestTruncate/Tests___dtest___test_cql_query_filtering_without_indexes/

[1704260920438_cql_tests.py TestTruncate test_cql_query_filtering_without_indexes.zip](https://github.com/scylladb/scylladb/files/13817465/1704260920438_cql_tests.py.TestTruncate.test_cql_query_filtering_without_indexes.zip)

**Comment by nyh** [comment]
This is a known flaky test, previously observed by  @kbr-scylla and @Annamikhlin and documented in the dtest repository: https://github.com/scylladb/scylla-dtest/issues/3750.

**Comment by tchaikov** [comment]
i am closing this one. so the related failure reports can be gathered in a single place.

**Comment by nyh** [comment]
> i am closing this one. so the related failure reports can be found in a single place.

I'm not sure where it's better to collect CI failures - it's not always clear-cut if a certain failure is a test bug (and belongs in the dtest repository) or a Scylla bug (and belongs here). More importantly, when a test failure appears, people test to search for it here so it's a good idea to have the issue here. But anyway, since we already had an issue in the dtest repository, with better analysis (by @kbr-scylla), I guess if we keep only one of the two issue it should be that one.

**Comment by tchaikov** [comment]
yeah, even it was closed. it can still serve the purpose as pointer, which leads developers to a "better" place.
