### ISSUE TITLE
auth service on_* notifications need not launch background fibers.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16624]
Currently the auth service on_* vectors launch fibers in the background, while they are called in a seastar thread allowing them to `.get()` and await until they are resolved.

This is important with raft consistent-cluster-management that serializes schema changes so leaving background stuff behind goes against that sentiment.

See for example https://github.com/scylladb/scylladb/blob/91a5a41313b20bebbd4e62d80e30d2012a9db4ca/auth/service.cc#L73-L87

**Comment by bhalevy** [comment]
@mykaul can you please add a label for `auth`?

**Comment by mykaul** [comment]
Added. I assume @ptrsmrn need to look at this.

**Comment by nuivall** [comment]
@bhalevy should the `class migration_listener` callbacks functions be changed to return future<> so that we can run code in the foreground instead?

**Comment by bhalevy** [comment]
> @bhalevy should the `class migration_listener` callbacks functions be changed to return future<> so that we can run code in the foreground instead?

It isn't required since we ensure that the notifications run in a seastar thread.
See https://github.com/scylladb/scylladb/blob/13e16475fabb51be4c24e14c3ed1551885c4fe56/service/migration_listener.hh#L48

In hindsight that should have been defined as returning a future, but we need not go there.

**Comment by nuivall** [comment]
Then I wonder why it wasn't blocking in the first place. We were afraid of timeouts? As it looks like exceptions are ignored anyway.

**Comment by nuivall** [comment]
because this listener got deprecated and is no longer used in auth-v2 I think we can close this as won't fix
