### ISSUE TITLE
Server crash with scylla

### ISSUE THREAD

**Issue by JackThird** [scylladb/scylladb#16634]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.0-0.20231205.58a89e7a4231
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu Server 22.04 LTS

*Hardware details (for performance issues)*     
Platform (physical/VM/cloud instance type/docker): bare metal (hosting provider)
Hardware: CPU=8c/16t, memory=64GB
Disks: (SSD/HDD, count) 2x512GB SSD RAID 0, filesystem=XFS
Network: Public=1Gbps, Private=2Gbps
Swap: 16GB

I have saw random and unexpected server shutdown/crash since months. I substitute 2 nodes because I thought was an HW issue but the issue persist also on new nodes.

Maybe there is an issue with scylla or OS configuration.

For example these are two crash events:
1° crash:
Jan  3 03:00:04 gmt+2

2° crash
Jan  3 13:01:25 gmt+2

- Syslogs (contains also scylla logs):
[syslog.zip](https://github.com/scylladb/scylladb/files/13821389/syslog.zip)

- Coredumpctl file saved in the 2° crash:
[coredumpctl.zip](https://github.com/scylladb/scylladb/files/13821401/coredumpctl.zip)

- Events
On Jan 3 03:00 there were scylla snapshots backups.
On Jan 3 13:01 I tried to execute scylla snapshots backups and via iotop, just before crash, I saw this:
![iotop](https://github.com/scylladb/scylladb/assets/74727385/892b4a29-2ad4-41d1-966d-3697c2639028)

Backup steps:
```
# $1="keyspace_name"
# Backup keyspace schema
cqlsh $node_ip -e "DESCRIBE KEYSPACE $1" > $tmp_dir/$key_dir/${1}_schema.cql

# Pre-snapshot ops
nodetool cleanup $1
nodetool flush $1
nodetool clearsnapshot $1

# Take Snapshot
nodetool -h localhost -p 7199 snapshot -t ${1}_snap $1

# Check snapshot
nodetool listsnapshots

# Compress snapshot
time tar -I pigz -cf $tmp_dir/$key_dir/${1}_data.tgz $data_dir/$1/*/snapshots/${1}_snap* > /dev/null 2>&1

# Clear snapshot
nodetool clearsnapshot $1
```

- Scylla.yml:
[scylla.yaml.zip](https://github.com/scylladb/scylladb/files/13821476/scylla.yaml.zip)

- /etc/default/scylla-server:
[etc_default_scylla-server.zip](https://github.com/scylladb/scylladb/files/13821619/etc_default_scylla-server.zip)

- Misc
In the past I noticed server crash also when tried to fix the cluster via nodetool repair --full and nodetool cleanup.
RAID 0 is OK, hosting provider checked HW components like CPU. RAM and HD and results are normal, on the server there is only scylla service.
Scylla use 93% of RAM, 0% SWAP and data directory is only 30GB. 

Could you help me to understand what should investigate because I don't see errors in OS and Scylla logs or strange performance issues in my Zabbix graphs, thanks.

**Comment by avikivity** [comment]
coredumpctl.zip doesn't contain a scylladb core dump.

**Comment by JackThird** [comment]
I read about irqbalance and I understand that it's related also to scylla_setup.

Should I disable or keep alive that service?
I see two files:
/etc/default/irqbalance
/etc/default/irqbalance.scylla.orig
[irqbalance.zip](https://github.com/scylladb/scylladb/files/13828315/irqbalance.zip)

**Comment by avikivity** [comment]
The irqbalance crash should be reported to your OS vendor.

scylla_setup does play with irqbalance configuration, but it shouldn't crash if it's misconfigured (or for any reason).

**Comment by JackThird** [comment]
I don't know what to think, for example ten minutes ago I restarted scylla-server and server freeze. Hard reboot required.
This is last thing I see in htop:
![screen](https://github.com/scylladb/scylladb/assets/74727385/0abf2b52-c6e2-4fa0-a227-8d6ece918149)

My hosting provider did HW benchmarks and results are good, from my side I installed Ubuntu server last month with scylla-server.
Is there a way to understand why when I perform actions with Scylla, server goes down?
I performed also stress tests with stress linux tool but server didn't crash.

**Comment by mykaul** [comment]
I wonder why you have multiple Java processes running there. It should not cause the crash, but it's strange to see.

**Comment by avikivity** [comment]
> I wonder why you have multiple Java processes running there. It should not cause the crash, but it's strange to see.

Those are likely threads of the same process.

**Comment by avikivity** [comment]
Do you have any logs from the crash?

Does the hosting provider support serial consoles (AWS and GCP do). If so, look there for a panic.

**Comment by avikivity** [comment]
Also try: adding --memory 48G to the command line.

**Comment by JackThird** [comment]
I did a test on another scylla node where irqbalance were in **failed** status, I commented a row:
`#IRQBALANCE_ARGS=" --banirq=126 --banirq=128 --banirq=129 --banirq=130 --banirq=131 --banirq=132 --banirq=133 --banirq=134 --banirq=135 --banirq=136 --banirq=137 --banirq=138 --banirq=139 --banirq=140 --banirq=141 --banirq=142 --banirq=143 --banirq=144 --banirq=145 --banirq=146 --banirq=147 --banirq=148 --banirq=149 --banirq=150 --banirq=151 --banirq=152 --banirq=153 --banirq=154 --banirq=155 --banirq=156 --banirq=157 --banirq=158 --banirq=159 --banirq=160 --banirq=188 --banirq=189 --banirq=190 --banirq=191 --banirq=192 --banirq=193 --banirq=194 --banirq=195 --banirq=196 --banirq=197 --banirq=198 --banirq=199 --banirq=200 --banirq=201 --banirq=202 --banirq=203 --banirq=204 --banirq=127 --banirq=161 --banirq=162 --banirq=163 --banirq=164 --banirq=165 --banirq=166 --banirq=167 --banirq=168 --banirq=169 --banirq=170 --banirq=171 --banirq=172 --banirq=173 --banirq=174 --banirq=175 --banirq=176 --banirq=177 --banirq=178 --banirq=179 --banirq=180 --banirq=181 --banirq=182 --banirq=183 --banirq=184 --banirq=185 --banirq=186 --banirq=125"`

restarted scylla-server and a new row appeared:

`IRQBALANCE_ARGS=" --banirq=125 --banirq=127 --banirq=129 --banirq=130 --banirq=131 --banirq=132 --banirq=133 --banirq=134 --banirq=135 --banirq=136 --banirq=137 --banirq=138 --banirq=139 --banirq=140 --banirq=141 --banirq=142 --banirq=143 --banirq=144 --banirq=145 --banirq=146 --banirq=147 --banirq=148 --banirq=149 --banirq=150 --banirq=151 --banirq=152 --banirq=153 --banirq=154 --banirq=155 --banirq=156 --banirq=157 --banirq=158 --banirq=159 --banirq=160 --banirq=188 --banirq=189 --banirq=204"`

Now irqbalance is in **active** status.

**Comment by avikivity** [comment]
scylladb does play with irqbalance configuration to direct network interrupts to the cores that are dedicated to networking.

It's possible that your hardware breaks with that, or that the drivers have a bug. 

You can ask scylladb not to dedicate cores to networking (will cause it to spend some time reshaping sstables). I forget exactly how, but @vladzcloudius remembers.

Other things to do:
 - ask your hosting provider to connect a real serial console to the servers, reproduce the crash, and report to lkml so they can fix it
 - post `lspci` here for future reference

**Comment by JackThird** [comment]
> Other things to do:
> 
>     * ask your hosting provider to connect a real serial console to the servers, reproduce the crash, and report to lkml so they can fix it
> 
>     * post `lspci` here for future reference

- lspci
```
00:00.0 Host bridge: Intel Corporation Device 4c43 (rev 01)
00:01.0 PCI bridge: Intel Corporation Device 4c01 (rev 01)
00:01.1 PCI bridge: Intel Corporation Device 4c05 (rev 01)
00:08.0 System peripheral: Intel Corporation Device 4c11 (rev 01)
00:12.0 Serial controller: Intel Corporation Device 43fc (rev 11)
00:14.0 USB controller: Intel Corporation Tiger Lake-H USB 3.2 Gen 2x1 xHCI Host Controller (rev 11)
00:14.2 RAM memory: Intel Corporation Tiger Lake-H Shared SRAM (rev 11)
00:15.0 Serial bus controller: Intel Corporation Tiger Lake-H Serial IO I2C Controller #0 (rev 11)
00:16.0 Communication controller: Intel Corporation Tiger Lake-H Management Engine Interface (rev 11)
00:16.1 Communication controller: Intel Corporation Device 43e1 (rev 11)
00:16.4 Communication controller: Intel Corporation Device 43e4 (rev 11)
00:17.0 SATA controller: Intel Corporation Device 43d2 (rev 11)
00:1b.0 PCI bridge: Intel Corporation Device 43c4 (rev 11)
00:1c.0 PCI bridge: Intel Corporation Device 43b8 (rev 11)
00:1f.0 ISA bridge: Intel Corporation Device 438c (rev 11)
00:1f.4 SMBus: Intel Corporation Tiger Lake-H SMBus Controller (rev 11)
00:1f.5 Serial bus controller: Intel Corporation Tiger Lake-H SPI Controller (rev 11)
01:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM9A1/PM9A3/980PRO
02:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM9A1/PM9A3/980PRO
03:00.0 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
03:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GBASE-T (rev 02)
04:00.0 PCI bridge: ASPEED Technology, Inc. AST1150 PCI-to-PCI Bridge (rev 04)
05:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 41)
```

I asked for serial console, I hope to see some messages in that mode.
I continue to investigate, update the ticket in ​following days and yes, I'm interested in disable cores dedicated to networking as additional test.

**Comment by avikivity** [comment]
As a side note I see you are using consumer SSDs, they will give you very bad performance and likely die young due to the heavy write load. I recommend you move to enterprise disks. It doesn't explain the crash, but will give you grief in the future.

**Comment by vladzcloudius** [comment]
> scylladb does play with irqbalance configuration to direct network interrupts to the cores that are dedicated to networking.
> 
> It's possible that your hardware breaks with that, or that the drivers have a bug.
> 
> You can ask scylladb not to dedicate cores to networking (will cause it to spend some time reshaping sstables). I forget exactly how, but @vladzcloudius remembers.
> 
> Other things to do:
> 
>     * ask your hosting provider to connect a real serial console to the servers, reproduce the crash, and report to lkml so they can fix it
> 
>     * post `lspci` here for future reference

To disable any IRQ related tweaking:
1) Set following in the /etc/default/scylla-server:

```
SET_NIC_AND_DISKS="no"
SET_CLOCKSOURCE="no"
DISABLE_WRITEBACK_CACHE="no"
```

Remember what they were before you do the change!

2) Delete `/etc/scylla.d/perftune.yaml`
3) Find `irqbalance` file under `/etc` : `sudo find /etc -name irqbalance` 
4) If (3) finds any such file - clear all `--banirq` entries from it and reboot the machine (it's the safest way to clear all previous config for your case). Again, preserve the original config somewhere.


If this resolves the crash issues then you can start bringing backed up config one by one and see which one triggers the crash.

FYI there were issues with smp affinity configuration with networking cards in some older Xen kernels.

**Comment by JackThird** [comment]
Hello,
this night server go down again, this morning I did @vladzcloudius  changes but issue persist when I execute:
```
# $1=keyspace_name    
nodetool cleanup $1
nodetool flush $1
nodetool clearsnapshot $1
```


I checked serial console and what I see is "power off" so it means that server go down. 
I'm trying to understand how to reproduce the issue because sometimes I can execute listed command and sometimes they powered off the server. I think there are different triggers involved, I will update you.

**Comment by JackThird** [comment]
Before crash:
![crash](https://github.com/scylladb/scylladb/assets/74727385/716e2356-23da-432d-baa2-0144d81c219f)

When I perform nodetool cleanup, CPU temperature goes in few secs to 80°C. I was not able to do it via a stress tool (stress and stress-ng).
Due this very fast CPU usage I presume that Server fans don't have time to cool the temperature and server go down for security reason. 
I tried to reduce CPU usage in /etc/default/scylla-server from 16 (max) to 14 via --smp but temperature is still high.
Should I add more options to reduce CPU usage?

**Comment by vladzcloudius** [comment]
> Before crash: ![crash](https://private-user-images.githubusercontent.com/74727385/294475454-03ffcc82-c3f0-4e71-a61f-73f17fc47c12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjM5ODYsIm5iZiI6MTcwNDQ2MzY4NiwicGF0aCI6Ii83NDcyNzM4NS8yOTQ0NzU0NTQtMDNmZmNjODItYzNmMC00ZTcxLWE2MWYtNzNmMTdmYzQ3YzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE0MDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOWRkN2QyZDkxOGE0NDkzNzhiMDUxOWU4OTIwZTg3ZTRlMDMyMTc2MGIxMDUzZmFkZDAxZmI3NzljOGEyNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjD9gv97Iv03-AE_zc6sbqqXYqMiF3CBg6OTmzK0b_U)
> 
> When I perform nodetool cleanup, CPU temperature goes in few secs to 80°C. I was not able to do it via a stress tool (stress and stress-ng). Due this very fast CPU usage I presume that Server fans don't have time to cool the temperature and server go down for security reason. I tried to reduce CPU usage in /etc/default/scylla-server from 16 (max) to 14 via --smp but temperature is still high. Should I add more options to reduce CPU usage?

Scylla as any `seastar` application is going to consume any available CPU as long as there is work to do.
When you run `nodetool cleanup` you trigger an intensive compaction task which is naturally going to consume all available CPU (unless you restrict it - more on that below).
The same is going to happen when there any other kind of work, e.g. CQL processing, memtable flush, repair, compaction, streaming or any combination of them.

Therefore, in general, your infrastructure should be ready for high CPU utilization including the corresponding cooling if you really want to enjoy scylla in the fullest.

Now how to work the temperature issues around due to intensive compactions: you can restrict the maximum compaction I/O bandwidth using `compaction_throughput_mb_per_sec` parameter. 
However this may backfire if your compaction are going to start falling behind as a result. So beware!

How to try to reduce the CPU temperatures in general: reduce the maximum CPU frequency (use google to find out how). This is going to reduce the overall performance of your system but at least it would stop rebooting.

I hope this helps.

**Comment by JackThird** [comment]
Server no longer crashed so listed configurations helped me, thank you for you patience and time :)
