### ISSUE TITLE
test_remove_dead_node_consistency_failed failed - dead node was not removed? 

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#16633]
node 2 is dead, node1 is trying to remove it, but I don't think it manages to do so:
```
INFO  2024-01-02 23:15:21,021 [shard 0:strm] api - remove_node: host_id=e6e2489b-bedb-4634-863f-f7aed5ab8f99 ignore_nodes={}
INFO  2024-01-02 23:15:21,021 [shard 0:strm] raft_group0 - Performing a group 0 read barrier...
INFO  2024-01-02 23:59:25,111 [shard 0:main] compaction_manager - Asked to stop
```

Node 1 log @ https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/460/artifact/logs-full.release.005/1704239968122_auth_test.py%3A%3ATestAuth%3A%3Atest_remove_dead_node_consistency_failed/node1.log
Test log @ https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/460/artifact/logs-full.release.005/dtest-gw2.log

Scylla version 5.5.0~dev-0.20240102.91a5a41313b2 with build-id 380e0aa3fc55ffea09578b7033fe8b263e471b4d

**Comment by mykaul** [comment]
@kostja  , @kbr-scylla - known issue? I couldn't find it (seen on scylla-master CI dtest-release runs)

**Comment by mykaul** [comment]
It's failing consistently (good news?) since https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/455/

**Comment by kbr-scylla** [comment]
https://github.com/scylladb/scylladb/issues?q=is%3Aissue+is%3Aopen+test_remove_dead_node_consistency_failed
points to
https://github.com/scylladb/scylladb/issues/16475

Closing as dup
