### ISSUE TITLE
raft topology: simplify interaction with gossiper and `system.peers`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16644]
I think we coupled raft-topology with gossiper/`system.peers` too much and now it's causing us trouble.

For example, whenever raft command is applied that updates topology, we store all known nodes except us inside system.peers and re-insert them into gossiper. I think this is unnecessary and serves no purpose and only causes pain like -- to update gossiper we need to know the IP of a node, which might not yet be known when we apply topology command  -- and questions -- like what generation/version should we use to insert the peers -- and so on.

First, observe what nodes a given node is gossiping with. It's only gossiping with nodes that it can reach through seeds, then nodes that those seeds can reach through their seeds, etc. in other words, it's gossiping with the transitive closure calculated from the seeds graph. Even if we suppose we added an entry in system.topology table for some node, if that node is not reachable through this seeds transitive closure, we will not gossip with it -- because we won't ever know its IP address. IP addresses are obtained from seeds and then through gossiping.

So **raft topology can only restrict the set of nodes we're gossiping with, never extend it.**

Note that the raft-topology system only needs gossiping for one thing -- learning IP addresses. Otherwise the information flows from raft-topology into gossiper, not the other way around.

Note that when inserting info into gossiper, **we don't need to insert info about peers**. Only about ourself. Info about peers will propagate through regular gossiping, as it always did.

One might argue that the info we have from Raft topology command is fresher than what we have in gossiper, and the thing in gossiper would only eventually get updated through gossiping, and pushing it into our gossiper state from topology command updates it faster.
For that I will say:
- it doesn't matter. Raft topology doesn't need this info for anything. The only thing Raft topology needs from gossiper is IPs, and that is precisely the information that Raft topology cannot push.
- and it's actually not guaranteed that we'll push any info faster, because we might have an outdated IP mapping when we push it.
- and it's actually "more correct" to not push it, instead letting gossiper propagate it!

On that last two points, suppose that indeed some node X has updated some information about itself that we store in Raft topology, like num_shards, and committed a Raft command. We're another node and we apply this command locally. Is it better/faster to also push it into gossiper on behalf of that node at this point, instead of letting it get eventually updated through regular gossiping?

**No** -- suppose that X has also changed its IP from `.1` to `.2` when it restarted. Gossiper is IP based (it's a key-value store where keys are IPs), and the information we push into gossiper will use the old .1 key. So, we actually didn't update anything -- in fact we pushed **wrong information!** We updated gossiper saying that node `.1` has updated num_shards, when in fact, the node with new num_shards is `.2`.

So not only there is no additional guarantee, updating gossiper on behalf of peers may actually insert wrong info.

The same logic applies to `system.peers`. What `system.peers` originally did is storing information about peers in NORMAL status which we obtained through gossiping. It's also keyed by IP.

And raft-topology needs `system.peers` only for one thing: to restore IP mappings on restart.

There is no need to update gossiper on behalf of peers when applying topology change command. And in the same way, there is no need to update `system.peers` -- let gossiper do it, as it always did -- the same argument as above applies here, raft topology won't make it any more up to date than what gossiper can do, in fact it may update some info using obsolete IP.

-----

So all that said, I propose the following changes:
- when applying topology change command, in `topology_state_load`, only update system.local and insert gossiper app states for ourselves. Don't update system.peers or insert gossiper app states for peers.
- to make sure left nodes are not outstaying their welcome in gossiper, introduce host-ID based API for removing+banning nodes from gossiper and system.peers which topology_state_load would call for left nodes. Same as we did in messaging service. That API would take a host ID, iterate over all entries in gossiper and system.peers and remove everything with that host ID, and add it into a banned set which would prevent gossiper from ever again interacting with this ID.
- let gossiper handlers update system.peers as they do in gossiper-topology mode.

@kostja @gusev-p @gleb-cloudius @bhalevy @tgrabiec @piodul

**Comment by kbr-scylla** [comment]
Two things I remember that depend on system.peers/gossiper state
- nodetool status and perhaps other nodetool commands
- drivers

Does it mean we should push system.peers/gossiper state on behalf of peers when applying topology Raft commands?

I still think not. As above, neither there is a guarantee that the info is pushed faster from Raft commands, nor there is a guarantee we'll use the correct IP.

Still, for nodetool status the info we return in raft-topology mode should be based on raft-stored topology. But this is easy to fix, we can modify the REST endpoints used by nodetool to check if we're in raft topology mode and return info from raft-topology data structures (`topology_state_machine` etc.) instead of gossiper/system.peers. This info may sometimes need IP; for that, we can do the translation from host ID at this point, returning `?` placeholder or sth for nodes for which we're missing IP addresses.

Driver topology updates are eventually consistent anyway and I don't think we can provide any more guarantees there that what gossiper already gives. In fact since drivers are IP based (?) it's better to keep relying on gossiper there for the reasons I already provided. If we switched drivers to be host-ID based (whatever that would mean), then perhaps it would make sense to push info directly from raft-topology somehow.

**Comment by kbr-scylla** [comment]
It's worth to mention that for RECOVERY we'll revert to gossiper mode and that's when system.peers/gossiper consistency is important. And maybe system.peers being updated "faster" from raft-topology may help in such disaster recovery situation; or maybe not, as gossiper update may also be faster, and more consistent in presence of IP changes. And anyway, we'd like to eventually introduce another recovery method (that doesn't depend on reverting to gossiper topology). So I think pushing peer updates to gossiper from raft topology is neither a clear advantage or a clear disadvantage for recovery.

**Comment by gusev-p** [comment]
> Note that when inserting info into gossiper, **we don't need to insert info about peers**. Only about ourself. Info about peers will propagate through regular gossiping, as it always did.

[The reason](https://github.com/scylladb/scylladb/issues/14675) I added `add_saved_endpoint` to `topology_state_load`:
> In general, it is not guaranteed that seeds will be up to date and reachable at the time of restart, so we shouldn't rely on that.

So we still need to initialise gossiper with peers at startup.

**Comment by kbr-scylla** [comment]
Yes of course I agree @gusev-p. But that's regular part of old gossiping and system.peers updating logic.

I meant that we don't need to insert info about peers from Raft change command application logic.

**Comment by gleb-cloudius** [comment]
The plan was to get rid of gossiper all together. It's only purpose in the end suppose to be id to ip mapping distribution and only on systems that cannot do that through DNS. Even the failure detector should move to separate module. So the code that we have that tries to sync with gossiper should all disappear in the end (I also am not sure that we even continue distributing things line cpu count through gossiper in raft mode). 

You propose to leave gossiper as is basically and work in parallel with raft topology, but carefully instrument it to drop token metadata modifications, but do everything else. I think it is more error prone and the wrong direction overall. We want to get rid of gossiper code.

**Comment by kbr-scylla** [comment]
> The plan was to get rid of gossiper all together.

That never could be the plan because gossiper is distributing information that cannot go through Raft which is not only IPs, but also things like the heat metric used for load balancing. But I don't think this is important in the context of this discussion.

> So the code that we have that tries to sync with gossiper should all disappear in the end (I also am not sure that we even continue distributing things line cpu count through gossiper in raft mode).

My proposal is to reduce the amount of code related to gossiper in raft-topology mode, so it actually goes in the direction of disappearing this code!

> You propose to leave gossiper as is basically and work in parallel with raft topology, but carefully instrument it to drop token metadata modifications, but do everything else.

I want gossiper to:
- keep updating system.peers, which it needs to do because of IP addresses, we cannot get rid of that part.
- keep updating transient information like heat metric. Also something we cannot get rid of.
- drop everything else

So I'm for reducing gossiper role to the absolute minimum.

The only part where we disagree with I think is the other columns inside `system.peers` (other than host ID and IP). You think they should be updated from topology change commands, I think we should let gossiper update if for now. I argue that this is simpler, more correct, and will make raft topology operation smoother. But I don't want it to stay that way. In fact I would like to eventually reach a state where we can leave all those columns at `null`. Maybe even switch to another table for IP mappings. But for that we need to update tools that depend on `system.peers` first (drivers, nodetool). That is the end goal, but in the meantime, letting gossiper update system.peers just makes everything else easier.

**Comment by gleb-cloudius** [comment]
> > The plan was to get rid of gossiper all together.
> 
> That never could be the plan because gossiper is distributing information that cannot go through Raft which is not only IPs, but also things like the heat metric used for load balancing. But I don't think this is important in the context of this discussion.

Yes, it is not important if there is one or two thing that cannot be put into the raft. All that can be should be.

> 
> > So the code that we have that tries to sync with gossiper should all disappear in the end (I also am not sure that we even continue distributing things line cpu count through gossiper in raft mode).
> 
> My proposal is to reduce the amount of code related to gossiper in raft-topology mode, so it actually goes in the direction of disappearing this code!

IMO the goal should be to reduce amount of code in the gossiper. In this case I would rather remove state gossiper state handler all together the moment we will not need it for recovery.


> 
> > You propose to leave gossiper as is basically and work in parallel with raft topology, but carefully instrument it to drop token metadata modifications, but do everything else.
> 
> I want gossiper to:
> 
>     * keep updating system.peers, which it needs to do because of IP addresses, we cannot get rid of that part.

This means it will have to handle node states forever. And this, in turn, means that we need to distribute those states in gossiper forever.

I am not saying topology load is the best place for system.peers tables update though. May be we can move system.peers update to some kind of gossiper even subscriber that will get called on id->ip mapping change.

> 
>     * keep updating transient information like heat metric. Also something we cannot get rid of.
> 
>     * drop everything else
> 
> 
> So I'm for reducing gossiper role to the absolute minimum.
> 
> The only part where we disagree I think is the other columns inside `system.peers` (other than host ID and IP). You think they should be updated from topology change commands, I think we should let gossiper update if for now. I argue that this is simpler, more correct, and will make raft topology operation smoother. But I don't want it to stay that way. In fact I would like to eventually reach a state where we can leave all those columns at `null`. Maybe even switch to another table for IP mappings. But for that we need to update tools that depend on `system.peers` first (drivers, nodetool). That is the end goal, but in the meantime, letting gossiper update system.peers just makes everything else easier.

I am not sure carefully instrumenting crazy `handle_normal_state` handler is simpler. If you agree on the final goal there is no point doing a step back.

**Comment by kbr-scylla** [comment]
But system.peers updates are happening outside storage_service::handle_state_* functions, no? Otherwise, how in raft-topology mode are IPs being updated and stored in system.peers (because they are, IIUC), given that storage_service::handle_state_* functions are disabled?

I don't propose to reenable storage_service::handle_state_*.

**Comment by kbr-scylla** [comment]
Answering myself
this is `storage_service::on_change`
```cpp
    const auto host_id = _gossiper.get_host_id(endpoint);
    const auto& tm = get_token_metadata();
    const auto ep = tm.get_endpoint_for_host_id_if_known(host_id);
    // The check *ep == endpoint is needed when a node changes
    // its IP - on_change can be called by the gossiper for old IP as part
    // of its removal, after handle_state_normal has already been called for
    // the new one. Without the check, the do_update_system_peers_table call
    // overwrites the IP back to its old value.
    // In essence, the code under the 'if' should fire if the given IP is a normal_token_owner.
    if (ep && *ep == endpoint && tm.is_normal_token_owner(host_id)) {
        if (!is_me(endpoint)) {
            slogger.debug("endpoint={}/{} on_change:     updating system.peers table", endpoint, host_id);
            co_await _sys_ks.local().update_peer_info(endpoint, get_peer_info_for_update(endpoint, states));
        }
```

I think this is what stores IPs in raft-topology mode

And it also seems to store TOKENS and STATUS.

Also, it uses `tm.is_normal_token_owner(host_id)` so it depends on timing, assumes that raft topology command is applied first. If not, and we still consider the node e.g. as booting when we get gossiper update about it after it got transitioned to normal by topology coordinator, we'll fail to store its IP, if I understand correctly. @gusev-p 

**This** is error prone, those implicit dependencies between gossiper and raft topology that sometimes work if we're lucky. What is propose is getting rid of these dependencies and making it all simpler.

**Comment by gleb-cloudius** [comment]
> But system.peers updates are happening outside storage_service::handle_state_* functions, no? Otherwise, how in raft-topology mode are IPs being updated and stored in system.peers (because they are, IIUC), given that storage_service::handle_state_* functions are disabled?
> 
> I don't propose to reenable storage_service::handle_state_*.

I do see `update_peer_info` called from `handle_state_normal` somewhere close to the end after `handle_state_normal: endpoint={} is_normal_token_owner={} endpoint_to_remove={} owned_tokens={}` log.

**Comment by kbr-scylla** [comment]
> I am not saying topology load is the best place for system.peers tables update though. May be we can move system.peers update to some kind of gossiper even subscriber that will get called on id->ip mapping change.

I think that would be better than what we have right now.
(Maybe then we could also disable the code in `storage_service::on_change` in raft-topology mode completely.)
This subscriber would have to subscribe to both gossiper id/ip changes *and* topology_state_load.

The problem with inserting updates to obsolete IP in system.peers remains though. But I don't know if it's a big one. Maybe not.

**Comment by gleb-cloudius** [comment]
> > I am not saying topology load is the best place for system.peers tables update though. May be we can move system.peers update to some kind of gossiper even subscriber that will get called on id->ip mapping change.
> 
> I think that would be better than what we have right now. 

Agree.

> (Maybe then we could also disable the code in `storage_service::on_change` in raft-topology mode completely.) This subscriber would have to subscribe to both gossiper id/ip changes _and_ topology_state_load.

Yes.

**Comment by kbr-scylla** [comment]
Nowadays we have `storage_service::sync_raft_topology_nodes` that is called from both topology state machine apply and `storage_service::raft_ip_address_updater` on gossip events.
