### ISSUE TITLE
docs: Issue in page ScyllaDB Web Installer for Linux

### ISSUE THREAD

**Issue by datatriever** [scylladb/scylladb#16665]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.4/getting-started/installation-common/scylla-web-installer

### Problem
On Ubuntu 22.04 LTS (fully patched)
curl -sSf get.scylladb.com/server | sudo bash -s -- --scylla-version 4.6.1

Output
root@db-33 ~ # curl -sSf get.scylladb.com/server | sudo bash -s -- --scylla-version 4.6.1
Hit:1 http://mirror.hetzner.com/ubuntu/packages jammy InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu jammy InRelease                         
Hit:3 http://mirror.hetzner.com/ubuntu/packages jammy-updates InRelease           
Hit:4 http://mirror.hetzner.com/ubuntu/packages jammy-backports InRelease         
Get:5 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]        
Hit:6 http://mirror.hetzner.com/ubuntu/packages jammy-security InRelease          
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:8 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease
Fetched 119 kB in 1s (222 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
Installing Scylla version 4.6.1 for Ubuntu ...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.sGNHxwvzU2/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5e08fbd8b5d6ec9c
gpg: key 5E08FBD8B5D6EC9C: "ScyllaDB Package Signing Key 2020 <security@scylladb.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 5E08FBD8B5D6EC9C: "ScyllaDB Package Signing Key 2020 <security@scylladb.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
main: line 94:  4678 Segmentation fault      (core dumped) apt update -qq -o Acquire::Retries=3

###  Suggest a fix
Fix package

**Comment by tzach** [comment]
@yaronkaikov please take a look

**Comment by mykaul** [comment]
4.6.1 is not supported for quite a while.
@datatriever - does it happen with 5.2 or 5.4?

**Comment by yaronkaikov** [comment]
@mykaul yes, it seems we have a regression in the tool , probably related to the gpg key update

**Comment by yaronkaikov** [comment]
Running both `curl -sSf get.scylladb.com/server | sudo bash -s -- --scylla-version 5.2` or `curl -sSf get.scylladb.com/server | sudo bash -s -- --scylla-version 5.4` is working as expected 

@datatriever Please note that `4.6` has been EOL for a while now, supported releases are available https://opensource.docs.scylladb.com/stable/getting-started/os-support.html# 

@tzach We should update https://opensource.docs.scylladb.com/stable/getting-started/installation-common/scylla-web-installer.html# with more updated releases as examples

**Comment by tzach** [comment]
> @tzach We should update https://opensource.docs.scylladb.com/stable/getting-started/installation-common/scylla-web-installer.html# with more updated releases as examples

We already have a list of supported release here https://opensource.docs.scylladb.com/stable/getting-started/os-support.html We need to link to it, not duplicate it.

**Comment by datatriever** [comment]
Yes, this was about the documentation as it refers to the old version - that does not work due to gpg key issue.
I did the final installation with the Ubuntu package instructions which installs 5.4.1-0.20231231.3d22f42cf9c3 hence problem solved on that part... (but dropped ScyllaDB from tech stack due to other reasons)
