### ISSUE TITLE
Incorrect application of tombstones created from thrift with end bound having eoc=0

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#1668]
_Installation details_
Scylla version (or git commit hash): up to current master

bound_view doesn't distinguish between a prefix which covers all keys prefixed by it from the prefix which covers only the key equal to itself (thrift composite's `eoc` field determines that).

Example:

```
$ sudo sstable2json /var/lib/scylla/data/ks1/c2-e4e72ef06df511e6b310000000000000/ks1-c2-ka-4-Data.db 
[
{"key": "1",
 "cells": [["","00000000",1470761440040513],
           ["a","asd",2470761440040513,"t",1470764842],
           ["asd:","00000000",1470761451368658],
           ["asd:asd","00000000",1470761449416613]]}
]
```

Expected result:

```
cqlsh> select * from ks1.c2;

 id | c1  | c2   | v
----+-----+------+---
  1 |     | null | 0
  1 | asd |      | 0
  1 | asd |  asd | 0

(3 rows)
```

Actual result:

```
cqlsh> select * from ks1.c2;

 id | c1 | c2   | v
----+----+------+---
  1 |    | null | 0

(1 rows)
```

C\* 3.x has similar issue for which I opened https://issues.apache.org/jira/browse/CASSANDRA-12423

Spawned from #1446

**Comment by avikivity** [comment]
Downgrading, this only affects thrift which is rarely used these days.

**Comment by tchaikov** [comment]
won't be fixed because Thrift is dropped. see #18416
