### ISSUE TITLE
repair: memory accounting does not include keys 

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16710]
Issue explained by @michoecho (extracted from https://github.com/scylladb/scylladb/issues/15665#issuecomment-1752256111):

>  I can conclude that the problem is with how repair accounts memory. Repair has a memory limit it respects, but the only thing it accounts for is the frozen mutation fragment held in each repair_row. It doesn't account for anything else, in particular it doesn't account for keys. But in this test, there are rows with keys of size ~8 kiB and values of size ~16 B. (These rows come from materialized views). So the accounting is completely dysfunctional in this case, and repair ends up swallowing unlimited amounts of memory. (E.g. I witnessed a std::list holding multiple GiB worth of rows in the core, even though it was supposed to be limited to 32 MiB).
>
> Solution: fix repair_row::size() so that it accounts the size of everything it holds, not just the mutation fragment.

**Comment by michoecho** [comment]
Response by @asias:

> The repair_row holds a shared_ptr reference to decorated_key_with_hash which contains the key. Large keys is not supposed to explode the repair_row list.
> 
> It is not a trivial change to just account everything since the size of the rows has impact on how we decide rows to include in the algorithm.

So IIUC the accounting is somehow coupled with the repair algorithm, which makes the fix complicated.
