### ISSUE TITLE
Decide on a default for task_ttl_seconds

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#16714]
db/config.cc sets the default task_ttl_seconds to 0 - I presume it means no task ttl at all and they stay indefinitely (is this right?).
conf/scylla.yaml sets the default task_ttl_seconds to 10 seconds.

I think we should decide on one default, and set it to the same number in both (even better, comment out the setting in conf/scylla.yaml). It doesn't make sense that somebody who ugrades Scylla, or tests, use unlimited ttl while other people use 10 seconds.

Also, I don't understand how 10 seconds is a good default for something which, I thought, was an end-user feature. If the user doesn't check something in 10 seconds, this information is lost?

CC @denesb @Deexie

**Comment by mykaul** [comment]
> I think we should decide on one default, and set it to the same number in both (even better, comment out the setting in conf/scylla.yaml). It doesn't make sense that somebody who ugrades Scylla, or tests, use unlimited ttl while other people use 10 seconds.

Assuming we want users to be able to change it, if we comment it out in the YAML, what does it mean? I prefer a commented out with the default value that is the same in the code, perhaps.

**Comment by nyh** [comment]
> Assuming we want users to be able to change it, if we comment it out in the YAML, what does it mean? I prefer a commented out with the default value that is the same in the code, perhaps.

Yes, I meant "commented out with the default value that is the same in the code" - that's an often used tradition. What I don't like in the current situation is that the code doesn't seem to have a default at all (it has "0", which I guess means no TTL), so users who upgrade and keep their scylla.yaml, or users like me who don't use scylla.yaml at all, will simply get this default of "0" which I'm not sure we ever meant anyone to use (but I don't really know, which is why I asked @denesb and @Deexie who presumably know better than me what the intention was).

**Comment by nyh** [comment]
After looking at the code, I'm even more confused :-( @Deexie @denesb maybe you can help me understand...

The code has at the end of a task:
```
sleep_abortable(module->get_task_manager().get_task_ttl(), module->abort_source());
```
So if task_ttl is 0, it doesn't mean an infinite memory like I thought, quite the contrary - it means not sleep at all, and the task will be deleted immediately. So how did https://github.com/scylladb/scylladb/issues/16493 even happen? If the task_ttl_seconds is 0, won't we delete the tasks immediately and not "leak" memory when we do a loop of 100 table drops?

What am I missing here?

**Comment by denesb** [comment]
I will let @Deexie or @bhalevy answer, I'm not sure myself either, how this task TTL config works.

**Comment by bhalevy** [comment]
IIRC the reason we set the task ttl to 0 in db/config is for unit tests.
while the non-zero default in scylla.yaml is for cluster installation.

**Comment by nyh** [comment]
> IIRC the reason we set the task ttl to 0 in db/config is for unit tests. while the non-zero default in scylla.yaml is for cluster installation.

db/config.cc doesn't just affect "unit tests, so it's not a good reason to pick it based on what unit tests want.

The Python functional tests (if that's what you called "unit tests") have their own configuration in Python code, see test/cql-pytest/run.py and test/pylib/scylla_cluster.py, which overrides the default configuration in the code (these tests do NOT use scylla.yaml at all).

As an example, the Python tests wanted to have permissions-validity-in-ms to be 100ms to make tests quicker, so they set this value in both run.py and scylla_cluster.py. The default in the code (db/config.cc) is still 10,000ms, and the scylla.yaml has a commented out setting of 10,000ms (the same value as the default in the C++ code).

**Comment by nyh** [comment]
And please don't forget that beyond my request to decide on one default, I actually had two other puzzles here:
1. How come https://github.com/scylladb/scylladb/issues/16493 happened if the default in the code was ttl=0?
2. How is 10 seconds long enough for real users' needs? (in practice, is 10 seconds different from 0?)

**Comment by Deexie** [comment]
At first `task_ttl` was set to 10s by default (rather an arbitrary choice I think). After that it was set to 0 in db/config.cc (because of tests: https://github.com/scylladb/scylladb/pull/15239). Btw. the `task_ttl` can also be changed through API with `/task_manager/ttl`.

If we want to have the same value in both `db/config.cc` and `conf/scylla.yaml` then I think it should be 0, so that if someone doesn't need task_manager the memory won't be wasted. And if he does - he can set that through the API or with own .yaml

**Comment by nyh** [comment]
@Deexie I see. So "10 seconds" was considered "almost zero" and people who really use this feature are expected to higher number? 
I still think the choice of the default should be consistent (the same everywhere), tests should set the value to whatever they want (I explained above how), they don't care what the default is. And I'm still curious how, if the default is 0, we had the leak of https://github.com/scylladb/scylladb/issues/16493 happen. I must be missing something but I don't know what.

**Comment by Deexie** [comment]
I don't see the exact version of scylla used in these tests, but maybe it was lacking the change for https://github.com/scylladb/scylladb/pull/15859?

**Comment by nyh** [comment]
> I don't see the exact version of scylla used in these tests, but maybe it was lacking the change for #15859?

I was reproducing this a few days ago on master, so I don't think it's that. Weird.

**Comment by denesb** [comment]
I think I can easily reproduce the bad-alloc abort and check the value of the TTL in the core. If TTL is indeed 0 and we still keep tasks around, that would be yet another bug.

**Comment by bhalevy** [comment]
> I think I can easily reproduce the bad-alloc abort and check the value of the TTL in the core. If TTL is indeed 0 and we still keep tasks around, that would be yet another bug.

wouldn't it be enough for them to be scheduled concurrently, in a burst, to cause OOM?
If so, preventing regular compaction tasks from running in `submit` if there are no candidate sstables for compaction would prevent that.

**Comment by bhalevy** [comment]
> > I think I can easily reproduce the bad-alloc abort and check the value of the TTL in the core. If TTL is indeed 0 and we still keep tasks around, that would be yet another bug.
> 
> wouldn't it be enough for them to be scheduled concurrently, in a burst, to cause OOM? If so, preventing regular compaction tasks from running in `submit` if there are no candidate sstables for compaction would prevent that.

Continuing this line of thought: prevention is important, but we needed o(n^2) tasks to cause oom IIUC. submit is called for all tables/compaction_groups for each table deleted by the test, which did that in a loop.  With task_ttl=0 I would expect those futile tasks to be destroyed until the next submit burst.
Maybe they don't get to run due to their lower priority.

**Comment by nyh** [comment]
You can see my reproducer in the test I sent as a PR. There is no fancy racing involved - it's just a loop creating a table and then dropping it, serially (with 128 tablets). The loop takes a bit more than 1 second.

**Comment by Deexie** [comment]
Maybe I missed something, but why was https://github.com/scylladb/scylla-enterprise/issues/3713#issuecomment-1874109928 abandoned? If we don't filter the sstables, we continue cleanup (create cleanup task) in the loop and each `run_with_compaction_disabled` creates a regular compaction task. Seems like it could become large even without task_ttl...

**Comment by raphaelsc** [comment]
> > Maybe I missed something, but why was [scylladb/scylla-enterprise#3713 (comment)](https://github.com/scylladb/scylla-enterprise/issues/3713#issuecomment-1874109928) abandoned? If we don't filter the sstables, we continue cleanup (create cleanup task) in the loop and each `run_with_compaction_disabled` creates a regular compaction task. Seems like it could become large even without task_ttl...
> 
> I don't think it's abandoned. I planned on send the patches to fix that, but feel free to do that too.
> 
> Regardless, submit should not create regular compaction tasks if there is nothing to do. Maybe we can take advantage of the fact that compaction_reabler is destroyed when compactions are disabled and so it run the regular compaction sstable selection to select and register the sstables for conpaction and then pass them to the regular compaction task.
> 
> @raphaelsc, @Deexie, @lkshminarayanan WDYT? could that work?

yes, it should be similar to cleanup. evaluate first, create a task if needed

**Comment by tzach** [comment]
@bhalevy 
Could there be more mismatches (or overrides) between config.cc and scylla.yaml?

**Comment by denesb** [comment]
> @bhalevy Could there be more mismatches (or overrides) between config.cc and scylla.yaml?

With regards to task-manager or in general? In any case there is an easy way to find out:
* Start a single node with --config-file=/path/to/our/default/scylla.yaml (use defaults from config file)
* Start a single node without any config file (use defaults from config.cc)

Scan `system.config` and configure the result for the two nodes.
