### ISSUE TITLE
Alternator SIGABRT if requested TCP port is already in-use

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#16720]
**Installation details**
Scylla version (or git commit hash): 5.4.0-0.20231205.58a89e7a4231 with build-id `7486a70ced30f7c89053f5c5a230c20ad31ffc1f`

Seen by a user:

When Alternator is configured to listen on an already bound port (eg: 9042 CQL), ScyllaDB aborts. We should print a more meaningful message explaining the problem, perhaps even prior to start opening any TCP socket:

```shell
INFO  2024-01-10 12:38:28,429 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 172.17.0.7:9042 (unencrypted, non-shard-aware)
INFO  2024-01-10 12:38:28,429 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 172.17.0.7:19042 (unencrypted, shard-aware)
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
Aborting on shard 1.
Backtrace:
  0x35a19db
  0x35d1a1f
  linux-vdso.so.1+0x78f
  /opt/scylladb/libreloc/libc.so.6+0x90a6f
  /opt/scylladb/libreloc/libc.so.6+0x44b3f
  /opt/scylladb/libreloc/libc.so.6+0x30287
  /opt/scylladb/libreloc/libc.so.6+0x3db93
  /opt/scylladb/libreloc/libc.so.6+0x3dc0f
  0x369304b
  0x3629333
  0x3629c5f
  0x3628adb
  0x3628973
  0x362920f
  0x2cb590f
  0x361150f
2024-01-10 12:38:28,518 INFO exited: scylla (terminated by SIGABRT; not expected)
```

**Comment by nyh** [comment]
I failed to reproduce this in master, I tried `--alternator-port=9042` (so it asks to use the same port as CQL), and I get a clean failure:
```
INFO  2024-01-10 16:22:51,308 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on 127.0.0.1:9042 (unencrypted, non-shard-aware)
INFO  2024-01-10 16:22:51,308 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on 127.0.0.1:19042 (unencrypted, shard-aware)
INFO  2024-01-10 16:22:51,308 [shard 0:main] standard_role_manager - Created default superuser role 'cassandra'.
ERROR 2024-01-10 16:22:51,315 [shard 0:stmt] alternator_controller - Failed to set up Alternator HTTP server on 127.0.0.1 port 9042, TLS port 8043: std::system_error (error system:98, posix_listen failed for address 127.0.0.1:9042: Address already in use)
... <a bunch of shutdown messages>
ERROR 2024-01-10 16:23:01,578 [shard 0:main] init - Startup failed: std::system_error (error system:98, posix_listen failed for address 127.0.0.1:9042: Address already in use)
```

This is what I expected to happen, and the bug doesn't reproduce...

I'll try again now with the specific Scylla version mentioned above.

**Comment by nyh** [comment]
It turns out I only get the nice error message if I run Scylla one **one CPU**.
The ugly assertion error happens when I run Scylla on multiple CPUs (e.g., `-c 2`). I get these ugly assertion failures from all the CPUs except one.

So this bug does reproduce on master.

**Comment by nyh** [comment]
> > It turns out I only get the nice error message if I run Scylla one **one CPU**.
> 
> How many of our tests run like that? I reckon very very few of our users run it with one CPU only.

Of course, the general case has more than one CPU. It's just that when I ran it on one CPU to try to reproduce it, it didn't reproduce. Luckily I tried again with more than one CPU and found the bug does reproduce. I'll try to figure out why.

**Comment by nyh** [comment]
Oh @mykaul, just to clarify - cql-pytest (single-node functional tests) run with 2 CPUs exactly to avoid missing the multi-core bugs. I just ran a single-core instance manually, and it was a mistake.

**Comment by nyh** [comment]
Unfortunately, this is a Seastar bug. I opened https://github.com/scylladb/seastar/issues/2036. listen() gets confused if called on multiple cores (as we must): When the listening port is taken, it only gives a good exception on core 0, and fails an assertion on other cores.

The Seastar bug is almost 10 years old and I'm not sure how to fix it, so I think I'll work around it by listening on core 0 first, report the error, and only if core 0 worked - listen on the other cores.

**Comment by nyh** [comment]
Note that this bug is not specific only to Alternator configuration. If for example you use `--native-shard-aware-transport-port=9042` you get exactly the same assertion failure instead of a reasonable error message. It probably happens for other port configuration options as well.

**Comment by nyh** [comment]
@xemul fixed the Seastar bug so that now we get normal exceptions instead of assertion failures in Scylla, and we don't need a separate Scylla patch. I opened a PR https://github.com/scylladb/scylladb/pull/16769 to update Seastar to include this fix, and when it goes in, this issue will be closed.
