### ISSUE TITLE
test_rolling_cluster_replacement_sequentially dtests hang with consistent-topology-changes

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16730]
This might be a duplicate of https://github.com/scylladb/scylladb/issues/15967
as they show a similar symptom of endlessly retrying:
```
WARN  2024-01-09 08:01:10,368 [shard 0:strm] storage_service - raft topology: cannot map fbd65125-78ed-43f4-8386-a778306ae81f to ip, retrying.
```
on a replacing node, as seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release-with-consistent-topology-changes/30/artifact/logs-full.release.011/1704788118744_cluster_replacement_test.py%3A%3ATestClusterReplacement%3A%3Atest_rolling_cluster_replacement_sequentially_dead_nodes_multi_dc/node8.log

**Comment by bhalevy** [comment]
I think that the culprit is that with consistent topology changes we don't remove the existing node, as we do in handle_state_normal.
There is also an edge case when replace is aborted and rolled back, the legacy node ops call `del_replacing_endpoint` while that is missing from `storage_service::topology_state_load`.

In any case, the fix seems pretty straight forward, and just requires to remove a replacing endpoint also by value in `token_metadata_impl::remove_endpoint`, which makes sense regardless of this issue, as the removed endpoint need not be referenced at all in token_metadata and respective topology after `remove_endpoint`
```diff
diff --git a/locator/token_metadata.cc b/locator/token_metadata.cc
index 9f72708e12..e0ec2d5da7 100644
--- a/locator/token_metadata.cc
+++ b/locator/token_metadata.cc
@@ -634,6 +634,7 @@ void token_metadata_impl::remove_endpoint(host_id endpoint) {
     _topology.remove_endpoint(endpoint);
     _leaving_endpoints.erase(endpoint);
     del_replacing_endpoint(endpoint);
+    remove_by_value(_replacing_endpoints, endpoint);
     invalidate_cached_rings();
 }

 ```

**Comment by mykaul** [comment]
@bhalevy - is this still being worked on?

**Comment by mykaul** [comment]
Assuming it does not happen / not being worked on. Please re-open if still relevant.
