### ISSUE TITLE
service levels: service levels needs a self healing mechanism

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#16768]
We have a known caveat in service levels handling which arises from the design, the `service_levels` table which resides in
the `system_distributed` keyspace, is written to and read from with CL=1.
This produces an observed 'jittering' in the configuration when not all replicas contains the same data.
Right now we count on the user running repairs from time to time on the `system_*` keyspaces, however this might
not be done at all or done in very long intervals during which the system will continue to jitter.
My proposed solution for this is to implement a simple self healing mechanism:
Every time a configuration change is observed by the `service_level_controller` polling loop:
1. Try to issue a CL=ALL scan on the `service_levels` table which will force the table to self repair completely.
2. If step 1 fails, Try to issue a CL=QUORUM scan on `service_levels` table which will force the table to self repair, and to eventually converge.
3. If step 2 fails, run a CL=QUORUM read only on the service levels that have been changed so some of the configuration will be
    read repaired even if there are availability issues in the cluster.
4. Implement a self healing rest api which simply forces the above procedure to happen unconditionally with the change that
    instead of step 3, run the CL=QUORUM read on all known service levels (instead of changed ones).

We don't have to implement all methods but I believe that those will give us the complete solution, the configuration shouldn't
change at a high rate so eventually we should see convergence in configuration in a matter of minutes (WC) and not put too much load on the cluster, and if it fails we have the work around procedure of triggering self healing node by node in the cluster.

**Comment by piodul** [comment]
Addressed by moving service levels to raft.
