### ISSUE TITLE
[dtest][consistent-topology-changes] decommission after drain is hanging 

### ISSUE THREAD

**Issue by temichus** [scylladb/scylladb#16761]
with raft topology mode test test_decommission_after_drain_is_invalid  is hanging  instead of generating
        an unsupported operation message

*Installation details*
Scylla version 5.5.0~dev-0.20240111.f0d63302040c

logs: https://jenkins.scylladb.com/job/scylla-staging/job/artsiom_mishuta/job/dtest-pytest-gating/6/artifact/logs-full.release.000/

**Comment by temichus** [comment]
REMINDER: remove issues related test disabling from https://github.com/scylladb/scylla-dtest/pull/3848 when issue closed

**Comment by kbr-scylla** [comment]
> REMINDER: remove issues related test disabling from https://github.com/scylladb/scylla-dtest/pull/3848 when issue closed

@temichus the test should work now

**Comment by temichus** [comment]
added PR https://github.com/scylladb/scylla-dtest/pull/4125
