### ISSUE TITLE
No support for DynamicCompositeType

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#1677]
_Installation details_
Scylla version (or git commit hash): 1.3

creating a table with

```
CREATE TABLE test (    k int,    c 'DynamicCompositeType(s => UTF8Type, i => Int32Type)',    v int,    PRIMARY KEY
 (k, c)) WITH COMPACT STORAGE ...
```

fails

```
cqlsh:keyspace1> CREATE TABLE test (    k int,    c 'DynamicCompositeType(s => UTF8Type, i => Int32Type)',    v int,    PRIMARY KEY  (k, c)) WITH COMPACT STORAGE ;
SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] message="line 1:35 no viable alternative at input 'DynamicCompositeType(s => UTF8Type, i => Int32Type)'">
```

fails

java driver tests
com.datastax.driver.core.CustomTypeTest.DynamicCompositeTypeTest

**Comment by nyh** [comment]
I can't find any Cassandra documentation on this feature or whether it's still useful or relevant. The original Cassandra issue which introduced this ancient feature (10 years ago) was https://issues.apache.org/jira/browse/CASSANDRA-2231.
