### ISSUE TITLE
compation on read of expired tombstones doesn't work

### ISSUE THREAD

**Issue by alezzqz** [scylladb/scylladb#16781]
steps to reproduce:
1. `create table test_table ( a int, b int, primary key(a, b) ) with gc_grace_seconds = 5;`
2. insert some rows into the table
3. delete some rows from the table
4. flush table
5. `select * from test_table where a = 1;` to get rows into row cache
6. wait for grace period expired
7. `select * from test_table where a = 1;`  expired rows should be compacted and removed from cache here but they stay in cache indefinitely (see issue #6033, patch #12917)

it seems some changes of commit https://github.com/scylladb/scylladb/commit/43a7d83fd0f68fe87cb8c49d9bb6bb169fc042a6
change the behavior. If we change code in `tombstone_gc_state::get_gc_before_for_key`:
```
switch (options.mode()) {
    case tombstone_gc_mode::timeout:
        dblog.trace("Get gc_before for ks={}, table={}, dk={}, mode=timeout", s->ks_name(), s->cf_name(), dk);
        return check_min(s, saturating_subtract(query_time, s->gc_grace_seconds()));
```
to it's previous version:
```
switch (options.mode()) {
    case tombstone_gc_mode::timeout:
        dblog.trace("Get gc_before for ks={}, table={}, dk={}, mode=timeout", s->ks_name(), s->cf_name(), dk);
        return saturating_subtract(query_time, s->gc_grace_seconds());
```
everything works as expected

**Comment by elcallio** [comment]
Waiting for grace is no longer enough. You also need to expel commitlog data. In normal execution, this will happen eventually in an organic fashion. In test, maybe not always, though a nodetool flush will also attempt to do so. 
See https://github.com/scylladb/scylladb/issues/14870

**Comment by alezzqz** [comment]
Could you please explain conditions when row cache will be compacted? How to use it properly?
For instance, some application adds, removes and reads rows and there are lot of tombstones stay in row cache what impacts performance seriously. The previous implementation compacted and removed all the expired data just on read. Now I see (using own performance tests) that expired tombstones stay in cache indefinitely. Maybe Im doing something wrong?

**Comment by elcallio** [comment]
Assuming you have a steady write load, eventually all commitlog data will cycle fully, and tombstones will be allowed to GC, since no potential mutations resurrecting removed tombstones will be found (or rather mutation GC times). 
Basically, most tests doing artificial measurements of tombstone GC can get away  with just nodetool flush. It will nowadays also attempt to evacuate any remaining commit log data.

**Comment by alezzqz** [comment]
Unfortunately flush doesn't help: tombstones aren't going to be compacted anyway.
The test is not fully artificial - it imitates customers real life scenario when number of cached tombstones make system overloaded.
The issue was fixed but now it exists again. Maybe there's any other way to resolve it?

**Comment by avikivity** [comment]
We can limit a commitlog segment's age. Right now a commitlog segment can stay in memory indefinitely, holding on do data that prevents tombstones from being expired.

@elcallio didn't you have a patch for it?

Note limiting a commitlog segment's age can be good for other reasons. Note limiting it too much will increase write amplification.

**Comment by elcallio** [comment]
PR is here. https://github.com/scylladb/scylladb/pull/15971

**Comment by alezzqz** [comment]
I made few tests and found if we limit commitlog total size (`commitlog_total_space_in_mb` option) and wait until the limit exceeded - segments removed one by one and then cached tombstones started to be compacted. However to keep reasonable number of expired tombstones we have to reduce commitlog size too much. For instance, in my tests with commitlog total size just 1024mb we can get 50-60K of expired rows before they can be removed from cache. Setting too small commitlog size seems not good as well.
Commitlog segment's age may be a solution...

**Comment by Gst1298** [comment]
hi, we have the same problem with expired tombstones (Scylla 5.4.4). Can we hope to get any solution?

**Comment by alezzqz** [comment]
Maybe we could have an option for tombstones? To be compacted depending on CL segment lifetime and not depending (as it was before)? Some customers still have serious troubles with that issue and would enjoy a kind of option, I think.
