### ISSUE TITLE
Decommissioned wiped node could not be added again with error: Startup failed: std::runtime_error (A node with address 127.0.46.4 already exists

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#16796]
*Installation details*
Scylla version (or git commit hash): 5.5.0~dev-0.20240112.4e18f8b45381 with build-id 1ac9049b0fefe0d4b1baff6918a2629041d24515
Cluster size: 3

Dtest: bootstrap_test.py::TestBootstrap::test_decommissioned_wiped_node_can_join failed with error:
```INFO  2024-01-16 14:53:41,457 [shard 0:main] init - Shutting down configurables
INFO  2024-01-16 14:53:41,458 [shard 0:main] init - Shutting down configurables was successful
ERROR 2024-01-16 14:53:41,458 [shard 0:main] init - Startup failed: std::runtime_error (A node with address 127.0.46.4 already exists, cancelling join. Use replace_address if you want to replace this node.)
(END)

```

Node 4 was bootstrapped and the decommissioned. After decommission  it was wiped and start again. But Startup failed.
Logs:
[decommission_wipe_node_test.tar.gz](https://github.com/scylladb/scylladb/files/13947179/decommission_wipe_node_test.tar.gz)

to start test:
```
pytest --keep-test-dir --experimental-features=consistent-topology-changes --scylla-version=unstable/master:latest bootstrap_test.py::TestBootstrap::test_decommissioned_wiped_node_can_join
```

**Comment by kbr-scylla** [comment]
cc @gusev-p --- it could be related to calling `_gossiper.remove_endpoint()` in `topology_state_load`. Perhaps we're not removing the decommissioned endpoint properly? (Maybe when it's supposed to happen, we don't have the mapping or something?) Maybe one of the follow-ups you listed would solve it.

**Comment by gusev-p** [comment]
> cc @gusev-p --- it could be related to calling `_gossiper.remove_endpoint()` in `topology_state_load`. Perhaps we're not removing the decommissioned endpoint properly? (Maybe when it's supposed to happen, we don't have the mapping or something?) Maybe one of the follow-ups you listed would solve it.

The follow-up was about `remove_endpoint` in replace-with-same-ip.

I see
```
// Need to set it otherwise gossiper will try to send shutdown on exit
        co_await _gossiper.add_local_application_state({{ gms::application_state::STATUS, gms::versioned_value::left({}, _gossiper.now().time_since_epoch().count()) }});
```
in `storage_service::raft_decommission`, which should have probably handle this, but I don't understand how it's expected to work with `gossiper.remove_endpoint`, which would be called for left nodes in `topology_state_load`.

**Comment by gleb-cloudius** [comment]
Works for me locally. Probably was fixed by 1007ac49567e1159c26ad3ec08f0c916e1962c4e

**Comment by kbr-scylla** [comment]
@aleksbykov please verify as well, if it also works for you then we can close

**Comment by kbr-scylla** [comment]
ping @aleksbykov

**Comment by aleksbykov** [comment]
@kbr-scylla , issue doesn't reproduced. It could be closed

**Comment by kbr-scylla** [comment]
Thanks.
