### ISSUE TITLE
CREATE KEYSPACE should emit a warning about missing features with tablets enabled

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16807]
Tablet-based keyspaces won't support all the features:
  * CDC
  * Alternator streams
  * Alternator TTL

Emitting a warning gives the user a chance to then delete it and retry with tablets disabled.

**Comment by bhalevy** [comment]
@nyh can you pick up this issue?

**Comment by nyh** [comment]
@bhalevy I could, but I need clarifications from @tgrabiec or you first:

First, do you really want to print a warning each and every time a keyspace is created? Something like "Warning: this keyspace uses tablets so you will not be able to enable CDC on it later"?

Second, materialized views are **not** a "missing feature" and they do work with tables, so you should cross that off your list.

Third, the DynamoDB API has no concept of "warning". We do need to have a good error when trying to actually enable CDC (see https://github.com/scylladb/scylladb/issues/16497) but there is no good way to warn a user while creating a table that he will not be able to enable CDC later. So I guess you need to cross that off your list as well.

**Comment by tgrabiec** [comment]
> @bhalevy I could, but I need clarifications from @tgrabiec or you first:
> 
> First, do you really want to print a warning each and every time a keyspace is created? Something like "Warning: this keyspace uses tablets so you will not be able to enable CDC on it later"?

That was the idea. Suggested by @avikivity.

> 
> Second, materialized views are **not** a "missing feature" and they do work with tables, so you should cross that off your list.

Crossed out.

**Comment by tgrabiec** [comment]
> Second, materialized views are not a "missing feature" and they do work with tables, so you should cross that off your list.

@nyh Please make sure all release-blocking MV issues have a milestone set to 6.0

**Comment by nyh** [comment]
> > @bhalevy I could, but I need clarifications from @tgrabiec or you first:
> > First, do you really want to print a warning each and every time a keyspace is created? Something like "Warning: this keyspace uses tablets so you will not be able to enable CDC on it later"?
> 
> That was the idea. Suggested by @avikivity.

So let me get this straight - this message will be printed on every single keyspace creation in CQL which has tablets enabled, and will mention **only** CDC (because we crossed out MV, and as I noted, Alternator doesn't support warnings so needs to be crossed out too). Right?

I'll do that, although I think it won't be pretty.
I hope it doesn't break a bazillion dtests which might not like the new warning - we'll see.

**Comment by nyh** [comment]
> @nyh Please make sure all release-blocking MV issues have a milestone set to 6.0

I can, but as they say, "too many cooks spoil the broth" (also known as the "bystander effect"): If I and a dozen other people need to remember to do this each in their own area, surely some of them will be forgotten. One person (you, or Benny, or Yaniv) should once in a while search for all issues tagged "tablets" and decide for yourself what you want in 6.0 and what you don't want.

**Comment by nyh** [comment]
> It should be a CQL warning, not a log message that no one looks at.

Absolutely.

I'll send a patch in a few minutes. It was much harder than I anticipated to get this right without tons of code duplication (obviously, I don't want to duplicate the code which figures out from the strategy options whether tablets are used or not).
 
> As to the contents, I'm sure we have other deficiencies. LWT might not work, we don't migrate the paxos table contents.

We don't have an issue about LWT not working with tablets. @kbr-scylla?
If LWT doesn't work correctly, then neither does Alternator, by the way - it needs LWT for almost everything.

Anyway, once I have this warning message, you can easily change its text.

**Comment by tgrabiec** [comment]
On Tue, Feb 13, 2024 at 3:20 PM Avi Kivity ***@***.***> wrote:

> @bhalevy <https://github.com/bhalevy> I could, but I need clarifications
> from @tgrabiec <https://github.com/tgrabiec> or you first:
> First, do you really want to print a warning each and every time a
> keyspace is created? Something like "Warning: this keyspace uses tablets so
> you will not be able to enable CDC on it later"?
>
> That was the idea. Suggested by @avikivity <https://github.com/avikivity>.
>
> So let me get this straight - this message will be printed on every single
> keyspace creation in CQL which has tablets enabled, and will mention
> *only* CDC (because we crossed out MV, and as I noted, Alternator doesn't
> support warnings so needs to be crossed out too). Right?
>
> I'll do that, although I think it won't be pretty. I hope it doesn't break
> a bazillion dtests which might not like the new warning - we'll see.
>
> It should be a CQL warning, not a log message that no one looks at.
>
> As to the contents, I'm sure we have other deficiencies. LWT might not
> work, we don't migrate the paxos table contents.
>
Why is LWT a tablet-specific problem? We don't migrate paxos with vnodes
either.

**Comment by kbr-scylla** [comment]
> We don't have an issue about LWT not working with tablets. @kbr-scylla?

Yes?

**Comment by nyh** [comment]
> > We don't have an issue about LWT not working with tablets. @kbr-scylla?
> 
> Yes?

Avi claimed above that "LWT might not work, we don't migrate the paxos table contents.". Is there truth to that?
If it's not true, someone should convince Avi that it isn't. If it is true, someone should create an issue because I don't remember seeing one. I thought _you_ may serve as that "someone" ;-)

**Comment by kbr-scylla** [comment]
> Avi claimed above that "LWT might not work, we don't migrate the paxos table contents.". Is there truth to that?

I don't know, I know little about LWT and tablets, and even less when combined

>  If it's not true, someone should convince Avi that it isn't. If it is true, someone should create an issue because I don't remember seeing one. I thought you may serve as that "someone" ;-)

If some subsystem needs to be adjusted to work with tablets, I'd prefer to have someone from the tablets team to check that first and only when confirmed that LWT itself needs adjustments (and what kind of adjustments), report an issue for LWT team to look at. Could also be that the tablets code needs adjustments, not the LWT code, in which case it should be the responsibility of tablets team, not LWT team.
