### ISSUE TITLE
Reduced performance due to load balancer isolating hot tablets to a subset of shards

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16824]
Currently, the tablet load balancer assumes that each tablet has the same hotness. This may not be true, and some tables may be hotter than others. So we can end up with request load imbalance and reduced performance, since hot tablets may be isolated to a subset of shards.

This can be observed in scylla-bench workload after bootstrapping a new node concurrently with the load. The benchmark creates two tables, one of which is not used by the benchmark. The new node is first filled with cold tablets of the unused table, and majority of hot tablets stays on the old nodes.

One way to mitigate is to try to spread tablets of the same table across shards as much as possible, so that hot tablets are uniformly spread. We don't need to know which tablets are hot if we try to do it for all tables. This will approximate the behavior for vnodes and static sharding.

**Comment by mykaul** [comment]
If we've agreed it should go to 6.0, please set the milestone as such. Otherwise, I reckon 6.1.

**Comment by mykaul** [comment]
@bhalevy - who can work on this for 6.0?

**Comment by avikivity** [comment]
IMO important, very easy to regress in performance due to this. Also relatively easy to fix (adjust load balancer tablet selection algorithm).

**Comment by nyh** [comment]
@tgrabiec the solution you propose does not solve the general problem of hot **tablets**, but rather the more specific problem of hot **tables**, but I agree that the problem of hot tables is the more important case, so we should indeed do the fix you propose.

By the way, DynamoDB solved the problem of hot **tablets** (which they call "partitions") by:
1. Detecting them and _splitting_ them to smaller tablets.
2. At some point this no longer helps (e.g., imagine that someone sends a huge number of requests to the same row), so they have a limit of 3000 RCUs and 1000 WCUs that a single partition will accept. So it cannot dominate the node it runs on.

**Comment by bhalevy** [comment]
> @bhalevy - who can work on this for 6.0?

@tgrabiec, and he first needs to finish https://github.com/scylladb/scylladb/issues/16594
On top of that, we can statically balance tablets across shards in thee 6.0 scope (and it's a close call).

Post 6.0, I can see dynamic, heat-based balancing of tablets to disperse the load across nodes and across shards

**Comment by dani-tweig** [comment]
> [@tgrabiec](https://github.com/tgrabiec), and he first needs to finish [#16594](https://github.com/scylladb/scylladb/issues/16594)

Assigning Tomek

**Comment by bhalevy** [comment]
@mykaul / @dani-tweig IMO we should postpone this issue to 6.1.  Please ack.

**Comment by tgrabiec** [comment]
This has potential to cause regressions compared to vnodes, so I don't think it should be enterprise-only.

**Comment by mykaul** [comment]
@bhalevy - we'd still like to see it in 6.0 (after syncing with @dorlaor , @avikivity , @tzach ) - who can be assigned to this (other than Tomek) ?

**Comment by mykaul** [comment]
@bhalevy , @tgrabiec : 
Can we use the shuffle API as a valid workaround here, and push this from the 6.0 release blocker list?

**Comment by tgrabiec** [comment]
> @bhalevy , @tgrabiec : Can we use the shuffle API as a valid workaround here, and push this from the 6.0 release blocker list?

I don't think we can rely on shuffle, it's unpredictable, may be completely ineffective or even make the situation worse.

**Comment by tzach** [comment]
> I don't think we can rely on shuffle, it's unpredictable, may be completely ineffective or even make the situation worse.

It might, but what is the chance(percent)? 
If it is low enough, we can live with it till we have a proper solution.

**Comment by bhalevy** [comment]
> > I don't think we can rely on shuffle, it's unpredictable, may be completely ineffective or even make the situation worse.
> 
> It might, but what is the chance(percent)? If it is low enough, we can live with it till we have a proper solution.

For 6.0 we plan to have a simple mitigation which is to randomize tablet selection in tablet load balancing using a uniform distribution. This should result in a similar distribution of tablets per table on the destination node on average, with large enough number of tablets.

**Comment by bhalevy** [comment]
@tgrabiec is going to submit a PR destined for 6.0 with randomized picking of source tablets by the load balancer.
Then, we can continue to improve the selection algorithm for 6.1 and later.

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/commit/b9c88fdf4b01e962099b5cd9282f8c818334d02f is in 6.0, we can move this to 6.1 or open a new one for 6.1.

**Comment by bhalevy** [comment]
> [b9c88fd](https://github.com/scylladb/scylladb/commit/b9c88fdf4b01e962099b5cd9282f8c818334d02f) is in 6.0, we can move this to 6.1 or open a new one for 6.1.

Moved to 6.1.  We have the randomized selection in 6.0 and don't plan further improvement in 6.0 for the time being.
We'd consider backporting of further changes in this area on a case by case basis, if they fix severe enough issues.

**Comment by dani-tweig** [comment]
@tgrabiec , why did you remove the 'release blocker' label?
Can we live without it on 6.1?

**Comment by tgrabiec** [comment]
> @tgrabiec , why did you remove the 'release blocker' label? Can we live without it on 6.1?

It didn't block the 6.0 release, why should it block 6.1?
