### ISSUE TITLE
repair-based replace is unsafe if replication factor in a data center is too small

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16826]
Currently when replacing a node using repair, `do_rebuild_replace_with_repair` uses the new node data center as a `source_dc` and so it will sync only with nodes in that data center.

If, for example, the keyspace uses network_topology_replication_strategy and the replication factor is 1 in that data center, any data present on the replaced node will not be repaired onto the replacing node.

Similarly, even if the replication factor is larger, and more nodes in that DC were lost, and we use the --ignore-dead-nodes options, it is possible that not enough replicas are left in the DC which might lead to data loss.

The is reproducible using the following test case added to cluster_replacement_test.py:
```python
    def test_rolling_cluster_replacement_sequentially_dead_nodes_multi_dc_rf_1(self):
        """
        This test uses the network topology strategy to replace a node in a multi dc cluster.
        Replication is configured to have 1 replica in each data center.
        All nodes in the cluster are replaced, one at a time.
        """
        cluster = self.cluster
        cluster.populate([2, 2]).start()
        node1 = self.cluster.nodelist()[0]
        n_of_keys = self.num_keys
        self._insert_data(node1, rf={"dc1": 1, "dc2": 1}, n_of_keys=n_of_keys)
        rbnos = RepairBasedNodeOperationsScenarios(tester=self)
        for node in self.cluster.nodelist()[::-1]:
            new_node = rbnos.replace_node(replaced_node=node)
            cluster.add_seed(new_node)
            self._verify_data_integrity(n_of_keys)
```

**Comment by mykaul** [comment]
@bhalevy - is that on track for 6.0?

**Comment by bhalevy** [comment]
> @bhalevy - is that on track for 6.0?

No.  But It's a non-issue with tablets though.

**Comment by mykaul** [comment]
> > @bhalevy - is that on track for 6.0?
> 
> No. But It's a non-issue with tablets though.

So it can't be a P0 either.

**Comment by bhalevy** [comment]
Data point from the field:
After losing all nodes in one of two datacenters, a node from the lost DC was replaced and ended up with no data, as there are no other nodes left in its DC.

**Comment by mykaul** [comment]
This issue is on @bhalevy - which is going to PTO. @denesb - is there anyone that can pick this up?

**Comment by denesb** [comment]
> This issue is on @bhalevy - which is going to PTO. @denesb - is there anyone that can pick this up?

I assigned @Deexie, she will start to work on this after we deliver the mixed-shard repair fix.

**Comment by mykaul** [comment]
> > This issue is on @bhalevy - which is going to PTO. @denesb - is there anyone that can pick this up?
> 
> I assigned @Deexie, she will start to work on this after we deliver the mixed-shard repair fix.

Thanks @denesb ! In the meantime, shall we skip the test with this issue mentioned, so it won't continue and kill our CI?

**Comment by denesb** [comment]
> > > This issue is on @bhalevy - which is going to PTO. @denesb - is there anyone that can pick this up?
> > 
> > 
> > I assigned @Deexie, she will start to work on this after we deliver the mixed-shard repair fix.
> 
> Thanks @denesb ! In the meantime, shall we skip the test with this issue mentioned, so it won't continue and kill our CI?

I thought it is disabled already. Maybe it affects other tests which hit it indirectly.

**Comment by bhalevy** [comment]
Reopening issue so that test_safe_unsafe_rebuild will stop failing in next and CI
Until https://github.com/scylladb/scylla-dtest/issues/4823

**Comment by bhalevy** [comment]
Re-closing now that the backports are done

**Comment by mykaul** [comment]
@bhalevy - 2024.2.0-rc2 still fails on this - https://jenkins.scylladb.com/job/enterprise-2024.2/job/dtest-release/11/testReport/cluster_replacement_test/TestClusterReplacement/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split006___test_rolling_cluster_replacement_sequentially_dead_nodes_multi_dc_rf_1/ (perhaps a different reason?)
