### ISSUE TITLE
Joining node fails (gets stuck) on SCT longevity test

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#16849]
https://cloudius-jenkins-test.s3.amazonaws.com/33e9a8ce-d68b-40c0-9164-23f51ced4e7f/20240118_025204/db-cluster-33e9a8ce.tar.gz

This is a test that performs cluster resizing while stress-loading it. Node-5 fails to join along the way.

Here's a dump of @kbr-scylla 's thoughts:

=======8<========

it got stuck waiting for topology coordinator to accept its join request

```
Jan 17 16:03:55 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-5 scylla[5434]:  [shard 0:strm] storage_service - raft topology: join: sending the join request to 10.4.2.148
Jan 17 16:03:55 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-5 scylla[5434]:  [shard 0:strm] storage_service - raft topology: join: request to join placed, waiting for the response from the topology coordinator
```

we need to find the coordinator node to see what happened.
Looks like node 1 was the topology coordinator

```
Jan 17 10:50:33 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft topology: start topology coordinator fiber
```

and it noticed the request

```
Jan 17 16:03:55 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0: gms] storage_service - raft topology: placed join request for 51650633-cdc0-4693-bb97-47ec360e0228
```

but it didn't get the node's IP

```
Jan 17 19:22:06 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft topology: coordinator fiber found a node to work on id=51650633-cdc0-4693-bb97-47ec360e0228 state=none
Jan 17 19:22:06 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - (rate limiting dropped 163 similar messages) raft topology: cannot map 51650633-cdc0-4693-bb97-47ec360e0228 to ip, retrying.
```

and eventually timed out...

```
Jan 17 19:22:35 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - (rate limiting dropped 198 similar messages) raft topology: cannot map 51650633-cdc0-4693-bb97-47ec360e0228 to ip, retrying.
Jan 17 19:22:36 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft topology: raft_topology_cmd failed with: std::runtime_error (failed to obtain an IP for 51650633-cdc0-4693-bb97-47ec360e0228 in 30s)
Jan 17 19:22:36 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft_topology_cmd::command::wait_for_ip failed, error std::runtime_error (raft topology: exec_global_command(wait_for_ip) failed with std::runtime_error (failed status returned from a0e4b5f1-79c5-418a-870d-12502873d5c7/10.4.3.196))
Jan 17 19:22:36 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft topology: rejected node moved to left state 51650633-cdc0-4693-bb97-47ec360e0228
Jan 17 19:22:36 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft topology: attempt to send rejection response to 51650633-cdc0-4693-bb97-47ec360e0228 failed: no ip address mapping for 51650633-cdc0-4693-bb97-47ec360e0228. The node may hang. It's safe to shut it down manually now.
```

but it's weird. We can clearly see that the coordinator managed to get gossip info about this node.

```
Jan 17 16:03:56 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0: gms] gossip - InetAddress 10.4.1.182 is now UP, status = UNKNOWN
```

and eventually removed it after the join failed

```
Jan 17 19:23:05 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0: gms] gossip - FatClient 10.4.1.182 has been silent for 30000ms, removing from gossip
```

so it should have the IP
This looks like a bug. Either in gossiper not delivering the notification, or in raft address map updater gossiper subscription

waait why is there such a gap in the time

ah, tablet migrations took 3 hours?

maybe it's related. Maybe there's some mechanism which clears the mapping

lol, indeed. There is one, I just remembered

if node doesn't join group 0, the raft_address_map entry is TTLed

and the TTL is 1 hour if I recall correctly

**Comment by kbr-scylla** [comment]
So if I understand correctly, the problem here on raft / group 0 / topology side is that the raft_address TTLed entry disappears. Unfortunately the node is waiting for its join request to be handled for 3 hours (due to tablet migrations happening), and the TTL for raft_address_map is 1 hour.

Perhaps we should reconsider how we remove entries from raft_address_map in Raft topology mode. It looks like it should happen at the moment of removing a node, not earlier. (cc @gusev-p, @gleb-cloudius, @kostja)

Another observation that could be considered a problem is that those tablet operations block coordinator completely for 3 hours. I recall we discussed it at some point, and there was this entire related topic of erm lock holding, but I don't remember what the conclusion was. @tgrabiec is there a plan to let coordinator progress with joining nodes etc. while tablet migrations are in progress (some kind of yielding perhaps)?

**Comment by kbr-scylla** [comment]
As a workaround it's possible to increase the TTL to 24 hours or something. But then if tablet migrations or whatever takes 25 hours, we'll just hit the issue again.

**Comment by gleb-cloudius** [comment]
> So if I understand correctly, the problem here on raft / group 0 / topology side is that the raft_address TTLed entry disappears. Unfortunately the node is waiting for its join request to be handled for 3 hours (due to tablet migrations happening), and the TTL for raft_address_map is 1 hour.
> 

Shouldn't migration be preempted if there is a request? @tgrabiec

**Comment by avikivity** [comment]
Those TTLs are a minefield. Everything works, you move to a different workload, it stops working even though the system is operating normally.

You can't assume anything about how long a tablet migration takes.

**Comment by gleb-cloudius** [comment]
> Those TTLs are a minefield. Everything works, you move to a different workload, it stops working even though the system is operating normally.
> 

Entries for nodes that are part of the cluster are not TTLed. But here we have a node that just asked to join and not part of the cluster yet.

**Comment by avikivity** [comment]
And it killed the cluster.

**Comment by kbr-scylla** [comment]
> And it killed the cluster.

It only prevented the new node from joining, didn't affect the cluster otherwise.

**Comment by gleb-cloudius** [comment]
> And it killed the cluster.

It did not. Why do you think so?

**Comment by gleb-cloudius** [comment]
But regarding the bug I think the intention of the TTL is to drop an entry for a node that is not part of the cluster and is dead. Here we should get updates from gossiper so why not extend the TTL each time we have a ping?

**Comment by tgrabiec** [comment]
> Shouldn't migration be preempted if there is a request? @tgrabiec

Migrations are preempted, but we still wait for the currently running ones to finish. Probably something blocks barriers due to erm ptr and not letting them finish, maybe sstable compaction.

**Comment by kbr-scylla** [comment]
> there are no on_endpoint_change calls if there are no changes.

Perhaps we could refresh the entry on successful failure detector pings.

**Comment by kbr-scylla** [comment]
> Perhaps we could refresh the entry on successful failure detector pings.

Nevermind, the failure detector is only pinging group 0 members. At least the Raft failure detector.

We still have the gossip failure detector though...

**Comment by kbr-scylla** [comment]
Or we could change the failure detector now to be based on contents of topology state machine instead of group 0 membership.

There it would see the node in `none` state.

**Comment by gleb-cloudius** [comment]
> Or we could change the failure detector now to be based on contents of topology state machine instead of group 0 membership.
> 
> There it would see the node in `none` state.

It would not. It is only added after the handshake.

**Comment by tgrabiec** [comment]
If it's due to compaction holding erm ptr, then it's fixed by https://github.com/scylladb/scylladb/pull/14995

**Comment by gleb-cloudius** [comment]
> > Shouldn't migration be preempted if there is a request? @tgrabiec
> 
> Migrations are preempted, but we still wait for the currently running ones to finish. Probably something blocks barriers due to erm ptr and not letting them finish, maybe sstable compaction.

Why compaction would hold erm?

**Comment by kbr-scylla** [comment]
> It would not. It is only added after the handshake.

Then what's this
```
Jan 17 19:22:06 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft topology: coordinator fiber found a node to work on id=51650633-cdc0-4693-bb97-47ec360e0228 state=none
```

**Comment by tgrabiec** [comment]
> > > Shouldn't migration be preempted if there is a request? @tgrabiec
> > 
> > 
> > Migrations are preempted, but we still wait for the currently running ones to finish. Probably something blocks barriers due to erm ptr and not letting them finish, maybe sstable compaction.
> 
> Why compaction would hold erm?

It needs a sharder. But it needs it for a short period. This is fixed in https://github.com/scylladb/scylladb/pull/14995

**Comment by kbr-scylla** [comment]
Ah, that was after the tablet stuff finished.

**Comment by kbr-scylla** [comment]
> It would not. It is only added after the handshake.

@gleb-cloudius IIUC this means that there's an entry in topology already.

```
Jan 17 16:03:55 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0: gms] storage_service - raft topology: placed join request for 51650633-cdc0-4693-bb97-47ec360e0228
```

**Comment by gleb-cloudius** [comment]
> > It would not. It is only added after the handshake.
> 
> Then what's this
> 
> ```
> Jan 17 19:22:06 perf-latency-grow-shrink-ubuntu-db-node-33e9a8ce-1 scylla[5453]:  [shard 0:strm] storage_service - raft topology: coordinator fiber found a node to work on id=51650633-cdc0-4693-bb97-47ec360e0228 state=none
> ```

Ah. Indeed. We have a period when a node is in the topology but not yet joined group0.  Happens after initial handshake. So may be we can make the entry permanent at this point?

**Comment by kbr-scylla** [comment]
> So may be we can make the entry permanent at this point?

Yes

**Comment by mykaul** [comment]
Who owns the next step here?

**Comment by kbr-scylla** [comment]
It's in cluster team's backlog
