### ISSUE TITLE
Fail boot gracefully when resharding on down-scale with tablets

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#16843]
Currently we fail by crashing or on assertion failures. It's cryptic and unpredicatble. We should detect that sharder claims a non-existent shard and fail gracefully and with informative message: e.g. "Down-scaling shard count not supported with tablet-based tables. Replace the node instead."

Refs https://github.com/scylladb/scylladb/issues/16739

**Comment by tgrabiec** [comment]
This issue is also about documenting the process. We should recommend running rolling bootstrap+decommission. It's slightly safer than killing and replacing a dead node because we don't lose any writes.

**Comment by denesb** [comment]
Tablets is a new feature, no backports needed.
