### ISSUE TITLE
Scylla allows replacing a node in one dc/rack with a node in a different dc/rack

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16858]
Currently, when replacing a node, scylla doesn't check if the new node resides in the same dc and rack as the old node.
With network topology replication strategy this can lead into a state when the replication map changes in a way that is incompatible with our replace node operation that just rebuild the token ranges previously owned by the old node onto the new node.
But if the new node changes the topology, the mapping isn't not that trivial anymore and one must run full cluster repair and then cleanup all nodes (except the new one) to make sure the cluster conforms to the new topology, yet this is not the intention of replace node.
If a user really wants that, they should remove the old node and bootstrap the new one in the new dc/rack location.
Or if and when we support ignore-nodes with bootstrap one can add the new node first, ignoring the dead node, and then remove it.  This should be the default procedure done under the hood for tablet node replacement.

**Comment by kostja** [comment]
We should just prohibit this with the centralized coordinator, should be a few lines check.

**Comment by kbr-scylla** [comment]
I see there's a patch from @bhalevy but it only addresses the old gossip path.

**Comment by vladzcloudius** [comment]
> We should just prohibit this with the centralized coordinator, should be a few lines check.

Yup. This kind of thing is ALWAYS wrong! If a replacing node is from a different DC/RACK and if there is a NetworkingStrategy in the picture with RF>0 this will result in the same mess as removing and/or adding new VNODEs without streaming (because the replication ownership is going to change).

This means a data loss in a general case. - This must be forbidden.
