### ISSUE TITLE
Post-TRUNCATE commitlog filtering is broken in the presence of cross-shard/cross-node sstable movement

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#16865]
To ensure that commitlog doesn't resurrect data after a successful TRUNCATE, Scylla inserts a record to `system.truncated`, which contains the table ID and the commitlog position at the moment of truncation. Then, during commitlog replay, mutations with smaller positions are ignored.

To ensure that the set of mutations deleted from the sstable set is equal to the set of mutations deleted from the commitlog, the replay position "at the moment of truncation" is the max() of all the replay position of all deleted sstables. (A replay position of an sstable is the replay position of its source memtable, or — if the source was compaction — the max from all source sstables. This also means that once a shard receives a foreign sstable, its max() stay corrupted even after the sstable is compacted away).

The problem is that the calculation considers *all* sstables, even those which weren't created on this shard. The replay positions of such sstables are effectively nonsense for the purpose of replay, so if at least one exists, then the max() is also nonsense, and the entire mechanism is nonsense.

Depending on the circumstances, this can cause a commitlog replay (when the node wasn't shut down cleanly after a TRUNCATE) to resurrect data from before the truncation, or, worse yet, to ignore all commitlog entries for the truncated table (even those written long after the truncation).

To fix this, the replay position calculation should take the max() only of the sstables which were written on the current shard, in the current boot cycle.

Note: AFAIK cross-shard sstable movement can happen due to resharding, sstable uploads, or — I guess — file-based streaming.

**Comment by michoecho** [comment]
Clarification: the problem manifests when a shard that received some foreign sstable undergoes TRUNCATE, and Scylla doesn't shut down cleanly. Then, during the next startup, commitlog won't replay the mutations for the truncated table correctly.

**Comment by michoecho** [comment]
cc @elcallio @bhalevy

**Comment by bhalevy** [comment]
What's left after https://github.com/scylladb/scylladb/pull/16550/commits/9defabd583d6c7ea4467e0d17f92dc83e3fd290f ?

**Comment by bhalevy** [comment]
IIUC we need to similarly ignore the replay position for truncate, right?

**Comment by bhalevy** [comment]
Regardung vnode based resharding, IIRC, commitlog replay happens before sstables are resharded so the sstables' replay positions should apply to the shard that wrote the commitlog.  Then, commitlog replay should replay into the destination shard's memtable, based in the current incarnation sharding.

**Comment by michoecho** [comment]
> What's left after [9defabd](https://github.com/scylladb/scylladb/commit/9defabd583d6c7ea4467e0d17f92dc83e3fd290f) ?

Oh. I didn't known about that PR at all. Indeed, I think it fixes the issue. I'm going to close it.

It's a shame that I didn't find the PR/issue earlier, it would have saved me some time. (In fact, I didn't even look. I didn't not expect a 9 year-old issue to had been fixed between my 3 days old master and today).

**Comment by bhalevy** [comment]
> > What's left after [9defabd](https://github.com/scylladb/scylladb/commit/9defabd583d6c7ea4467e0d17f92dc83e3fd290f) ?
> 
> Oh. I didn't know about that PR at all. Indeed, I think it fixes the issue. I'm going to close it.
> 
> It's a shame that I didn't find the PR/issue earlier, it would have saved me some time. (In fact, I didn't even look. I didn't not expect a 9 year-old issue to had been fixed between today and my `origin/master` from 3 days ago).

https://github.com/scylladb/scylladb/pull/16550 lingered too long in the approval non-process.
