### ISSUE TITLE
Range reads on tablets are very inefficient due to lack of specialized sstable set

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#16876]
Perf reports incremental selection, during range reads, being a significant burden:

```
   6.76%  reactor-2  scylla             [.] sstables::compound_sstable_set::incremental_selector::select
   6.60%  reactor-4  scylla             [.] sstables::compound_sstable_set::incremental_selector::select
   6.50%  reactor-5  scylla             [.] sstables::compound_sstable_set::incremental_selector::select
   6.49%  reactor-1  scylla             [.] sstables::compound_sstable_set::incremental_selector::select
   6.39%  reactor-3  scylla             [.] sstables::compound_sstable_set::incremental_selector::select
   5.95%  scylla     scylla             [.] sstables::compound_sstable_set::incremental_selector::select
   1.57%  reactor-6  scylla             [.] sstables::compound_sstable_set::incremental_selector::select
   1.28%  reactor-5  scylla             [.] replica::table::apply
   1.26%  reactor-6  scylla             [.] replica::table::apply
   1.15%  reactor-4  scylla             [.] replica::table::apply
   1.06%  reactor-2  scylla             [.] replica::table::apply
   1.04%  scylla     scylla             [.] replica::table::apply
   0.98%  reactor-1  scylla             [.] replica::table::apply
```

With specialized sstable set, we can work with data from a single tablet at a time. Today, with compound set, sstables from all tablets are being processed at the same time, causing significant overhead.

**Comment by xemul** [comment]
Should the original #16864 be closed in favor of this one?

**Comment by bhalevy** [comment]
I'm working on forward porting my patch to replace the table's compound sstable_set that covers all compaction_groups with table_sstable_set which is dynamic, accessing one compaction_group / sstable_set at a time.

**Comment by raphaelsc** [comment]
> I'm working on forward porting my patch to replace the table's compound sstable_set that covers all compaction_groups with table_sstable_set which is dynamic, accessing one compaction_group / sstable_set at a time.

FYI: now we iterate on storage_group(s), not compaction_group(s). Each storage_group spans 1 compaction_group or more, and compaction_groups in the same storage_group might overlap, e.g. main overlaps with and left and right, left doesn't overlap with right, but I think, for simplicity, we can treat them all as overlapping and optimize later.

**Comment by bhalevy** [comment]
> > I'm working on forward porting my patch to replace the table's compound sstable_set that covers all compaction_groups with table_sstable_set which is dynamic, accessing one compaction_group / sstable_set at a time.
> 
> FYI: now we iterate on storage_group(s), not compaction_group(s). Each storage_group spans 1 compaction_group or more, and compaction_groups in the same storage_group might overlap, e.g. main overlaps with and left and right, left doesn't overlap with right, but I think, for simplicity, we can treat them all as overlapping and optimize later.

Please see https://github.com/bhalevy/scylla/blob/table_sstable_set/replica/table_sstable_set.cc that I'm currently testing. 
It doesn't access the table's _compaction_groups directly, but rather it uses tokens to iterate over the token ring and `table::compaction_group_for_token` to get to the right compaction_group.  That said, it uses that compaction_group token_range to find the last token in the group and skip to the next one.
IIUC it should work properly in split mode.

**Comment by raphaelsc** [comment]
> > > I'm working on forward porting my patch to replace the table's compound sstable_set that covers all compaction_groups with table_sstable_set which is dynamic, accessing one compaction_group / sstable_set at a time.
> > 
> > 
> > FYI: now we iterate on storage_group(s), not compaction_group(s). Each storage_group spans 1 compaction_group or more, and compaction_groups in the same storage_group might overlap, e.g. main overlaps with and left and right, left doesn't overlap with right, but I think, for simplicity, we can treat them all as overlapping and optimize later.
> 
> @raphaelsc Please see https://github.com/bhalevy/scylla/blob/table_sstable_set/replica/table_sstable_set.cc that I'm currently testing. It doesn't access the table's _compaction_groups directly, but rather it uses tokens to iterate over the token ring and `table::compaction_group_for_token` to get to the right compaction_group. That said, it uses that compaction_group token_range to find the last token in the group and skip to the next one. IIUC it should work properly in split mode.

The usage of compaction_group_for_token() is today restricted to writes (e.g. picking which compaction group to add sstable or to apply a mutation into memtable). Not reads, as there are potentially more than 1 group to read from during split. I plan to rename it to compaction_group_for_write() to avoid misusage. You need to replace that by storage_group_for_token().

**Comment by avikivity** [comment]
We can have a compound_sstable_set for all the compaction groups that can serve a read. It won't affect the performance too much (I hope).

**Comment by raphaelsc** [comment]
> We can have a compound_sstable_set for all the compaction groups that can serve a read. It won't affect the performance too much (I hope).

That's what we have today. Your reasoning is that groups are disjoint, therefore incremental selection on compound set should work right? That's true, but depends on the compaction strategy used. If it doesn't use interval map, e.g. twcs, then it returns all sstables at once, regardless of the current token in the selection. with ICS though, it should be okay, at least in my current understanding.

@xemul was the latency test done against enterprise or OSS?

**Comment by tgrabiec** [comment]
On Mon, Jan 22, 2024 at 1:16 PM Benny Halevy ***@***.***>
wrote:

> I'm working on forward porting my patch to replace the table's compound
> sstable_set that covers all compaction_groups with table_sstable_set which
> is dynamic, accessing one compaction_group / sstable_set at a time.
>
> FYI: now we iterate on storage_group(s), not compaction_group(s). Each
> storage_group spans 1 compaction_group or more, and compaction_groups in
> the same storage_group might overlap, e.g. main overlaps with and left and
> right, left doesn't overlap with right, but I think, for simplicity, we can
> treat them all as overlapping and optimize later.
>
> Please see
> https://github.com/bhalevy/scylla/blob/table_sstable_set/replica/table_sstable_set.cc
> that I'm currently testing.
> It doesn't access the table's _compaction_groups directly, but rather it
> uses tokens to iterate over the token ring and
> table::compaction_group_for_token to get to the right compaction_group.
> That said, it uses that compaction_group token_range to find the last token
> in the group and skip to the next one.
> IIUC it should work properly in split mode.
>
I still don't like the fact that we make sstable sets mutable, that opens
up room for races. Would be better to use a different abstraction to feed
the selector, perhaps directly from the table object.

In table_sstable_set, when you iterate over storage groups with preemption,
you're vulnerable to racing with tablet splitting which rewrites storage
groups.

**Comment by raphaelsc** [comment]
> On Mon, Jan 22, 2024 at 1:16 PM Benny Halevy ***@***.***> wrote: I'm working on forward porting my patch to replace the table's compound sstable_set that covers all compaction_groups with table_sstable_set which is dynamic, accessing one compaction_group / sstable_set at a time. FYI: now we iterate on storage_group(s), not compaction_group(s). Each storage_group spans 1 compaction_group or more, and compaction_groups in the same storage_group might overlap, e.g. main overlaps with and left and right, left doesn't overlap with right, but I think, for simplicity, we can treat them all as overlapping and optimize later. Please see https://github.com/bhalevy/scylla/blob/table_sstable_set/replica/table_sstable_set.cc that I'm currently testing. It doesn't access the table's _compaction_groups directly, but rather it uses tokens to iterate over the token ring and table::compaction_group_for_token to get to the right compaction_group. That said, it uses that compaction_group token_range to find the last token in the group and skip to the next one. IIUC it should work properly in split mode.
> I still don't like the fact that we make sstable sets mutable, that opens up room for races. Would be better to use a different abstraction to feed the selector, perhaps directly from the table object. In table_sstable_set, when you iterate over storage groups with preemption, you're vulnerable to racing with tablet splitting which rewrites storage groups. 

But it's fine as long as table sstable set is token based, no?

remapping of storage groups, after split, mean that group ids can no longer be trusted.

but if the new set queries the current group, meaning it spans range [x, y], then next iteration in incremental selection will pick range (y, z]. A split means [x, y] is spanned by two groups, rather than only one. And that any id held by a set would be invalid.

does tablet migration wait for reads to be drained on the old replica?

**Comment by raphaelsc** [comment]
Ah you're talking about making sstable sets mutable. I agree with that.
