### ISSUE TITLE
Dynamically allocate compaction groups for tablets

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#16877]
Today, empty compaction groups are added for tablets that aren't present in this shard.

The memory overhead can be significant, and can also contributed to wasted cpu cycles when processing the empty content of those empty groups. The waste is proportional to the number of tablets.

Coordinator guarantees that a given replica will see a tablet migrating in, while still on allow_write_both_read_old stage, so that's when a group is allocated.

Groups are deallocated on cleanup step.

On table creation, we only allocate groups that are present in this shard.

**Comment by raphaelsc** [comment]
This will allow us to synchronize cleanup with any in-flight writes:

```
// Synchronizes with in-flight writes if any, and also takes care of flushing if needed.
// FIXME: to be able to stop group and provide guarantee above, we must first be able to reallocate a new group if tablet is migrated back.
//co_await _cg.stop();
co_await cg_ptr->flush();
co_await cg_ptr->cleanup();
```

**Comment by ptrsmrn** [comment]
@raphaelsc to the best of my knowledge this isn't consider a release-blocker, can I drop this label then?

**Comment by raphaelsc** [comment]
Implementation plan
-----

Each storage_group represents in replica::_storage_groups represents the storage of a single tablet. 

When table object is created, make_storage_groups() is called. 

It already lays foundation for dynamic allocation, see:
```
            auto shard = tmap.get_shard(tid, tm.get_my_id());
            if (shard && *shard == this_shard_id()) {
                tlogger.debug("Tablet with id {} and range {} present for {}.{}", tid, range, schema()->ks_name(), schema()->cf_name());
            }
            // FIXME: don't allocate compaction groups for tablets that aren't present in this shard.
            auto cg = std::make_unique<compaction_group>(_t, tid.value(), std::move(range));
            ret.emplace_back(std::make_unique<storage_group>(std::move(cg), &list));
```

So we should just go on, and do the conditional allocation there. The vector is sparse, so nullptr should be inserted if tablet is not present.


- Allocation on migration start

When a tablet replica is migrating in, we should prepare for it by allocating a new storage_group for it.

Table is notified about migration, before any writes are sent to new replica. 

The place to do check for it is table::update_effective_replication_map(), where table is notified about changes in transition metadata.

1) Look at new erm for any transition at stage allow_write_both_read_old (coordinator only advances once all replicas see it)
```
    for (auto& transition : erm->get_token_metadata().tablets().get_tablet_map(table_id).transitions()) { 
        ...
    }
```
    
2) Then we can check if any pending replica (tablet_transition_info::pending_replica) matches this shard (in this host)

3) If it does, then we allocate storage_group if not allocated already.


- Deallocation on migration end

Similarly, when a tablet replica is moved out, we should deallocate its storage_group.

1) Look at new erm for any transition at stage end_migration

2) Un-comment this in table::cleanup_tablet()
```
    // Synchronizes with in-flight writes if any, and also takes care of flushing if needed.
    // FIXME: to be able to stop group and provide guarantee above, we must first be able to reallocate a new group if tablet is migrated back.
    //co_await _cg.stop();
```

The above synchronizes with in-flight writes, and at this stage, newer writes only reach new replica.

In-flight reads should work fine, as they work with a snapshot of data source, which shouldn't depend on existence of a given storage_group. sstable_set for example is immutable and we keep it alive for the duration of read.


- Exception handling

Change table::storage_group_of() to throw exception if storage_group is not allocated, to handle scenario where a write somehow reaches the old replica that has storage_group deallocated already.

- Split

Split is already responsible for remapping, so nothing needs to be done in table::handle_tablet_split_completion().

- Testing

Existing tests should provide good coverage, but it can be a fun exercise to add a simple test, where a table is migrated from node A to B, and back to A (using the tablet move api), inserting some data and querying the content.

/cc @avikivity @tgrabiec

**Comment by avikivity** [comment]
Q1: storage_service() does this:

```c++
        if (_db.local().get_config().check_experimental(db::experimental_features_t::feature::TABLETS)) {
            tmptr->set_tablets(co_await replica::read_tablet_metadata(_qp));
            tmptr->tablets().set_balancing_enabled(_topology_state_machine._topology.tablet_balancing_enabled);
        }

        co_await replicate_to_all_cores(std::move(tmptr));
    }

    co_await update_fence_version(_topology_state_machine._topology.fence_version);
```

(I don't see the other places where the fence version is updated).

The question is: the token metadata is updated on different shards at different times. It's possible for a query to start on one shard and continue on another. We don't want a query to start on a shard that knows about the new tablet replica, then continue on a shard that doesn't, since we don't perform fencing when crossing shards. Do we always pick up the effective replication map pointer from a location that is updated after replicate_to_all_shards()?

Q2. deallocation. How does the state machine prove that by the time we send the update that the tablet replica no longer lives on the shard, there are no queries running with an older topology? If we can't, the node has to do it itself (wait until all references to topologies that happen to have the tablet replica allocated are gone).

**Comment by avikivity** [comment]
The barrier is between which states?

@xemul promised a mermaid diagram of the states, perhaps we can decorate it with barriers. Not every state transition has a barrier.

**Comment by raphaelsc** [comment]
> The barrier is between which states?
> 
> @xemul promised a mermaid diagram of the states, perhaps we can decorate it with barriers. Not every state transition has a barrier.

```
FROM                            TO                      BARRIER
----------------------------------------------------------------
allow_write_both_read_old       write_both_read_old     YES
write_both_read_old             streaming               YES
streaming                       write_both_read_new     NO
write_both_read_new             use_new                 YES
use_new                         cleanup                 YES
cleanup                         end_migration           NO
end_migration                   (delete transition)     YES
```


so let's assume:

tablets T1 and T2 in shard 0.
tablets T3 in shard 1.

1) migration wants to move T2 into shard 1.

2) migration advances to streaming stage

3) a multi-shard read start, spanning T1, T2 and T3, using token_metadata version 1.

4) migration advances to write_both_read_new, no barrier is required, bumping version to 2.


However, do_query_tablets(), for multishard_mutation_query, works with replication_map from the shard it runs. It uses tablet_range_splitter to intersect the query range with tablet ranges.

So even if "coordinator" shard for the query hasn't seen write_both_read_new yet, we can still read successfully from old replica.

write_both_read_new to use_new requires a barrier though. And use_new to cleanup also requires a barrier, so we won't cleanup a group with ongoing queries using stale topology version.

**Comment by avikivity** [comment]
Ok.

But, can't we skip the barrier if we think the node is down?

(reminder: the barrier's role is to avoid fencing errors, so we can skip it if that's the only way to make progress)

I think the solution is: when a node receives topology updates that would have required a barrier, execute the barrier internally. This guarantees that even if the topology change coordinator didn't succeed in sending us a barrier, it will have happened.

@Deexie you can go ahead with the plan, I think that if anything's missing we'll fix it outside the storage group allocation code.

**Comment by raphaelsc** [comment]
> Ok.
> 
> But, can't we skip the barrier if we think the node is down?

Not today, but we plan to tackle it on https://github.com/scylladb/scylladb/issues/16527

Also quoting Tomek from another issue (https://github.com/scylladb/scylladb/issues/16372):
"This issue is pointless before we make the tablet metadata barrier require only affected node (tablet replicas). Currently, the barrier requires all nodes to acknowledge, so if there is a node down then all tablet transitions will be stuck."

**Comment by avikivity** [comment]
I see it has a patch. So, fixing this issue will add a new backlog item (apply barriers when catching up). But it's okay.
