### ISSUE TITLE
raft topology: node restart during bootstrap can cause ip_not_found errors on the data plane

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#16884]
Scenario:
  * cluster with two nodes A and B, A is a topology coordinator;
  * a node C joins the cluster, streaming is in progress
  * node B restarts, its `address_map` is reloaded from `system.peers` which lacks the mapping for C
  * node C is a pending node in `token_metadata`, requests coming to B after restart will crash since they won't find IP for C

The streaming will probably fail, the join process will be rolled back, node C will be removed from the `token_metadata`, so the problem will be auto-fixed eventually.

**Comment by kbr-scylla** [comment]
Addressed by https://github.com/scylladb/scylladb/pull/18927
