### ISSUE TITLE
raft topology: join failure after wait_for_ip

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#16882]
This is a follow-up issue for [this PR](https://github.com/scylladb/scylladb/pull/16878#issuecomment-1900494227).

If the join process fails after successful `wait_for_ip` on some nodes  (e.g. if some other node didn't receive the IP of the joining node in time) our `system.peers` table will have a non-existent IP address. This seems like a minor issue.

We need to persist `host_id <->IP` mappings somewhere during the join process, when the joining node is not yet a token ring member. The problem is that `system.peers` is now supposed to store these mappings only for token ring members.

**Comment by kbr-scylla** [comment]
> We need to persist host_id <->IP mappings somewhere during the join process, when the joining node is not yet a token ring member. The problem is that system.peers is now supposed to store these mappings only for token ring members.

Yeah. I'm worried that the driver may try connecting to a node that is still bootstrapping because it appeared in `system.peers`. (That's how driver determines topology, by combining `local` and `peers`)

**Comment by gusev-p** [comment]
it seems we need a separate table specifically for the mappings

**Comment by gusev-p** [comment]
> Yeah. I'm worried that the driver may try connecting to a node that is still bootstrapping because it appeared in `system.peers`. (That's how driver determines topology, by combining `local` and `peers`)

It's better not to merge https://github.com/scylladb/scylladb/pull/16878 then

**Comment by gusev-p** [comment]
raft topology mode:
`system.ips`
  host_id -> ip, insert/update in `raft_ip_address_updater`, remove a given `host_id` if there are no references to it from `topology.{normal_nodes|new_nodes|transition_nodes}`. `wait_for_ip` waits for `host_id` to appear in this table.
`system.peers`
  ip -> node fields, insert/update an ip if there is a mapping in `system.ips` and the corresponding `host_id` is in `topology.{normal_nodes|transition_nodes}`, remove otherwise

@kbr-scylla @gleb-cloudius

**Comment by kbr-scylla** [comment]
> It's better not to merge https://github.com/scylladb/scylladb/pull/16878 then

Hmm. Doesn't https://github.com/scylladb/scylladb/pull/16820 introduce a similar problem too?
In a comment you said
> It seems in case of IP address change the old IP address won't be removed from gossiper and from system.peers.

(but I'm not sure if you're describing the current state, or after the PR)

**Comment by gusev-p** [comment]
> Hmm. Doesn't #16820 introduce a similar problem too? In a comment you said
> 
> > It seems in case of IP address change the old IP address won't be removed from gossiper and from system.peers.
> 
> (but I'm not sure if you're describing the current state, or after the PR)

It's unrelated, we need to check this, maybe I'm wrong and some covert code removes them.

**Comment by gusev-p** [comment]
[the PR](https://github.com/scylladb/scylladb/pull/16878) is closed, there is no such problem without it,  closing this issue. I created another, more general one https://github.com/scylladb/scylladb/issues/16884
