### ISSUE TITLE
raft topology: IP address change, old IP isn't removed from system.peers and gossiper

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#16886]
In the gossiper mode this is handled by `handled_state_normal` - it removes IPs not referenced by token ring. In raft topology mode `handled_state_normal` is disabled and there is no other equivalent logic.

We should pass the `prev_ip` to `sync_raft_topology_nodes` and teach it to remove it after it inserts a new ip. When we load the mappings we should select the one with biggest timestamp and drop the old one in case scylla crashes before removing the old ip.

**Comment by kbr-scylla** [comment]
Please also include a regression test which shows the issue (currently fails) but will be fixed by the PR
