### ISSUE TITLE
[aarch64][debug] test_read_repair.test_incremental_read_repair[partition-tombstone]

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#16899]
Seen twice on https://jenkins.scylladb.com/job/scylla-master/job/next/7107/ and https://jenkins.scylladb.com/job/scylla-master/job/next/7108/

```
    async def test_incremental_read_repair(data_class, workdir, manager):
        """Stress the incremental read repair logic
    
        Write a long stream of row tombstones, with a live row before and after.
        """
        seed = int(time.time())
        logger.info(f"random-seed: {seed}")
        random.seed(seed)
        cmdline = ["--hinted-handoff-enabled", "0", "--query-tombstone-page-limit", "1000"]
        node1 = await manager.server_add(cmdline=cmdline)
        node2 = await manager.server_add(cmdline=cmdline)
    
        cql = manager.get_cql()
    
        host1, host2 = await wait_for_cql_and_get_hosts(cql, [node1, node2], time.time() + 30)
    
        cql.execute("CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 2}")
        table_schema = f"CREATE TABLE ks.tbl ({data_class.column_spec}) WITH speculative_retry = 'NONE'"
        cql.execute(table_schema)
    
        schema_file_path = os.path.join(workdir, "schema.cql")
        with open(schema_file_path, "w") as schema_file:
            schema_file.write(table_schema)
    
        dead_timestamp = int(time.time() * 1000)
        live_timestamp = dead_timestamp + 1
    
        total_rows = 20000
        max_live_rows = 32
        deletion_time = datetime.datetime.now()
    
        row_set: TypeAlias = set[int]
    
        async def generate_and_upload_sstable(node: ServerInfo, node_row: int) -> row_set:
            live_rows = {random.randint(0, total_rows - 1) for _ in range(random.randint(0, max_live_rows))}
            live_rows.add(node_row)
    
            sstable = data_class.generate_sstable(total_rows, live_rows, dead_timestamp, live_timestamp, deletion_time)
            scylla_exe = await manager.server_get_exe(node.server_id)
            node_workdir = await manager.server_get_workdir(node.server_id)
            table_upload_dir = glob.glob(os.path.join(node_workdir, "data", "ks", "tbl-*", "upload"))[0]
    
            input_file_path = os.path.join(workdir, f"node{node.server_id}.sstable.json")
            with open(input_file_path, "w") as f:
                json.dump(sstable, f, indent=4)
    
            subprocess.check_call([
                scylla_exe, "sstable", "write",
                "--schema-file", schema_file_path,
                "--input-file", input_file_path,
                "--output-dir", table_upload_dir,
                "--generation", "1"])
    
            await manager.api.load_new_sstables(node.ip_addr, "ks", "tbl")
    
            return live_rows
    
        node1_rows = await generate_and_upload_sstable(node1, 0)
        node2_rows = await generate_and_upload_sstable(node2, total_rows - 1)
        all_rows = node1_rows | node2_rows
        assert len(all_rows) >= 2
    
        logger.info(f"node1_rows: {len(node1_rows)} rows, row ids: {node1_rows}")
        logger.info(f"node2_rows: {len(node2_rows)} rows, row ids: {node2_rows}")
        logger.info(f"all_rows: {len(all_rows)} rows, row ids: {all_rows}")
    
        def check_rows(cql: Session, host: Host, expected_live_rows: row_set) -> None:
            actual_live_rows = set()
            actual_dead_rows = set()
            for row in cql.execute("SELECT * FROM MUTATION_FRAGMENTS(ks.tbl)", host=host):
                res = data_class.check_mutation_row(row, expected_live_rows)
                if res is None:
                    continue
                row_id, is_live = res
                if is_live:
                    actual_live_rows.add(row_id)
                else:
                    actual_dead_rows.add(row_id)
    
            # Account rows that have a tombstone but are live only once.
            actual_dead_rows -= actual_live_rows
    
            assert actual_live_rows == expected_live_rows
            assert len(actual_live_rows) + len(actual_dead_rows) == total_rows
    
        logger.info("Check rows with CL=ONE before read-repair")
>       check_rows(cql, host1, node1_rows)

test/topology_custom/test_read_repair.py:293: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology_custom/test_read_repair.py:276: in check_rows
    for row in cql.execute("SELECT * FROM MUTATION_FRAGMENTS(ks.tbl)", host=host):
cassandra/cluster.py:2726: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.123.210.31:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.123.210.31:9042

cassandra/cluster.py:5085: OperationTimedOut
```

**Comment by bhalevy** [comment]
@tgrabiec, @denesb I'm afraid this could be related to recent tablets related changes.

i wonder if this could be related to another unexplained failure (client timeout) that I saw here: https://github.com/scylladb/scylla-dtest/pull/3888#issuecomment-1902573348

**Comment by avikivity** [comment]
> @tgrabiec, @denesb I'm afraid this could be related to recent tablets related changes.
> 

What do we revert?

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/next/7110/

**Comment by yaronkaikov** [comment]
There is no offensive commit. The problem seems to be related to `Armatrading` All failures were running on this server 

https://jenkins.scylladb.com/job/scylla-master/job/next/7112/ passed while running on a cloud instance

@benipeled Is this the reason you removed `Armatrading` from active nodes in Jenkins?

**Comment by benipeled** [comment]
> There is no offensive commit. The problem seems to be related to `Armatrading` All failures were running on this server

The first part does not cause the second unless you investigate and find an infra issue on armatrading - did you?

> 
> https://jenkins.scylladb.com/job/scylla-master/job/next/7112/ passed while running on a cloud instance
> 
> @benipeled Is this the reason you removed `Armatrading` from active nodes in Jenkins?

It was removed because of the workspace/container-overlay storage issue but maybe something in the cleanup cause it - I doubt it, the test failure has nothing with the disk or local container service

**Comment by avikivity** [comment]
This test is just excessively slow.

**Comment by yaronkaikov** [comment]
> This test is just excessively slow.

Maybe, but 3 last builds passed while running on the fleet for `aarch64`. I would expect `Armatrading` to be faster, if this is not the case, why should we use it at all?

**Comment by denesb** [comment]
> This test is just excessively slow.

Yes, we have an issue somewhere where we discussed ways to speed it up (not have to work with >1MB full of tombstones datasets).

**Comment by mykaul** [comment]
ping @benipeled

**Comment by benipeled** [comment]
We didn't faced this issue again but no fix sent or infra changed, we might see this slowness again,
For now we have nothing to do with this case

**Comment by benipeled** [comment]
Seen again twice on master/next [#7247](https://jenkins.scylladb.com/job/scylla-master/job/next/7274/) and [#7275](https://jenkins.scylladb.com/job/scylla-master/job/next/7275/) - both ran on armatrading machine
I re-triggered next on EC2-arm

@denesb / @avikivity anything can be adjusted on the test/armatrading to deal with this failure?

**Comment by denesb** [comment]
I will have to adjust the test.

**Comment by Annamikhlin** [comment]
seen again on https://jenkins.scylladb.com/job/scylla-master/job/next/7284/testReport/(root)/test_read_repair/Build___aarch64___Unit_Tests_aarch64___test_incremental_read_repair_partition_tombstone_/

**Comment by nyh** [comment]
Seen again in the following CI run, https://jenkins.scylladb.com/job/scylla-master/job/next/7285/testReport/.

```
Build / aarch64 / Unit Tests aarch64 / test_read_repair.test_incremental_read_repair[partition-tombstone]

    @pytest.mark.parametrize("data_class", incremental_repair_test_data)
    @pytest.mark.asyncio
    async def test_incremental_read_repair(data_class, workdir, manager):
        """Stress the incremental read repair logic
    
        Write a long stream of row tombstones, with a live row before and after.
        """
        seed = int(time.time())
        logger.info(f"random-seed: {seed}")
        random.seed(seed)
        cmdline = ["--hinted-handoff-enabled", "0", "--query-tombstone-page-limit", "1000"]
        node1 = await manager.server_add(cmdline=cmdline)
        node2 = await manager.server_add(cmdline=cmdline)
    
        cql = manager.get_cql()
    
        host1, host2 = await wait_for_cql_and_get_hosts(cql, [node1, node2], time.time() + 30)
    
        cql.execute("CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 2}")
        table_schema = f"CREATE TABLE ks.tbl ({data_class.column_spec}) WITH speculative_retry = 'NONE'"
        cql.execute(table_schema)
    
        schema_file_path = os.path.join(workdir, "schema.cql")
        with open(schema_file_path, "w") as schema_file:
            schema_file.write(table_schema)
    
        dead_timestamp = int(time.time() * 1000)
        live_timestamp = dead_timestamp + 1
    
        total_rows = 20000
        max_live_rows = 32
        deletion_time = datetime.datetime.now()
    
        row_set: TypeAlias = set[int]
    
        async def generate_and_upload_sstable(node: ServerInfo, node_row: int) -> row_set:
            live_rows = {random.randint(0, total_rows - 1) for _ in range(random.randint(0, max_live_rows))}
            live_rows.add(node_row)
    
            sstable = data_class.generate_sstable(total_rows, live_rows, dead_timestamp, live_timestamp, deletion_time)
            scylla_exe = await manager.server_get_exe(node.server_id)
            node_workdir = await manager.server_get_workdir(node.server_id)
            table_upload_dir = glob.glob(os.path.join(node_workdir, "data", "ks", "tbl-*", "upload"))[0]
    
            input_file_path = os.path.join(workdir, f"node{node.server_id}.sstable.json")
            with open(input_file_path, "w") as f:
                json.dump(sstable, f, indent=4)
    
            subprocess.check_call([
                scylla_exe, "sstable", "write",
                "--schema-file", schema_file_path,
                "--input-file", input_file_path,
                "--output-dir", table_upload_dir,
                "--generation", "1"])
    
            await manager.api.load_new_sstables(node.ip_addr, "ks", "tbl")
    
            return live_rows
    
        node1_rows = await generate_and_upload_sstable(node1, 0)
        node2_rows = await generate_and_upload_sstable(node2, total_rows - 1)
        all_rows = node1_rows | node2_rows
        assert len(all_rows) >= 2
    
        logger.info(f"node1_rows: {len(node1_rows)} rows, row ids: {node1_rows}")
        logger.info(f"node2_rows: {len(node2_rows)} rows, row ids: {node2_rows}")
        logger.info(f"all_rows: {len(all_rows)} rows, row ids: {all_rows}")
    
        def check_rows(cql: Session, host: Host, expected_live_rows: row_set) -> None:
            actual_live_rows = set()
            actual_dead_rows = set()
            for row in cql.execute("SELECT * FROM MUTATION_FRAGMENTS(ks.tbl)", host=host):
                res = data_class.check_mutation_row(row, expected_live_rows)
                if res is None:
                    continue
                row_id, is_live = res
                if is_live:
                    actual_live_rows.add(row_id)
                else:
                    actual_dead_rows.add(row_id)
    
            # Account rows that have a tombstone but are live only once.
            actual_dead_rows -= actual_live_rows
    
            assert actual_live_rows == expected_live_rows
            assert len(actual_live_rows) + len(actual_dead_rows) == total_rows
    
        logger.info("Check rows with CL=ONE before read-repair")
>       check_rows(cql, host1, node1_rows)

test/topology_custom/test_read_repair.py:293: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology_custom/test_read_repair.py:276: in check_rows
    for row in cql.execute("SELECT * FROM MUTATION_FRAGMENTS(ks.tbl)", host=host):
cassandra/cluster.py:2726: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.56.40.31:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.56.40.31:9042

cassandra/cluster.py:5085: OperationTimedOut
```

Unless Scylla crashed (I didn't check), it's worth checking if this isn't a genuine timeout because the combination of aarch64 and debug is our slowest run.

**Comment by Annamikhlin** [comment]
currenlty `armatrating` was removed from ARM pool until we will have adjustment to the test. 
@denesb - please let us know when you need `armatrating` for your verification.

**Comment by avikivity** [comment]
Marked critical as it's failing all the time.

**Comment by kbr-scylla** [comment]
@denesb I don't know if this is the root cause, but we need to replace all `cql.execute` with `cql.run_async` which has timeouts adjusted for the slow ARM environments:
```python3
# TODO: paged result query handling (iterable?)
def run_async(self, *args, all_pages = False, **kwargs) -> asyncio.Future:
    """Execute a CQL query asynchronously by wrapping the driver's future"""
    # The default timeouts should have been more than enough, but in some
    # extreme cases with a very slow debug build running on a slow or very busy
    # machine, they may not be. Observed tests reach 160 seconds. So it's
    # incremented to 200 seconds.
    # See issue #11289.
    kwargs.setdefault("timeout", 200.0)
    return _wrap_future(self.execute_async(*args, **kwargs), all_pages = all_pages)
```

or do the necessary adjustments in the test if you need `cql.execute` for some reason.

Furthermore, when creating driver sessions from a topology test (if the default driver session `manager.get_cql()` is not suitable for the test's needs for some reason), use the session constructor `manager.con_gen` which performs additional adjustments (there are multiple driver parameters that had to be adjusted to remove flakiness).
(Doesn't apply to this particular test, which uses `manager.get_cql()`, so we just need to use `run_async`)

cc @scylladb/scylla-maint please enforce these during review.

**Comment by nyh** [comment]
> cc @scylladb/scylla-maint please enforce these during review.

It's not easy for either developers or maintainers to remember these quaint rules. It would be better if the test framework would make it harder to make such mistakes, or not even consider them mistakes:

For example, in the cql-pytest framework, the code which creates the `cql` fixture that every test uses (`cql_session()`) sets the so-called _execution profile_ with all the timeouts that we thought were appropriate. At that point, using the regular unmodified `cql.execute()` function will get you the right timeouts, SSL setup, and other stuff  - you don't need to use any special function to get the right parameters.

Similarly, the developers of the topology framework can make an effort to have the "adjustments" they needed apply to the regular `execute()` and `execute_async()` functions and not require using a different function they invented `run_async()`. **Alternatively**, if it's too hard to configure the existing functions we could have been monkey-patched the existing function names (execute(), execute_async()) to call another function that does the right thing - without the user needing to be aware of the new function. Or alternatively, if even that is too difficult (?) - we can monkey-patch the old execute() function to not work at all (throw an exception saying execute() should not be used and please use run_async() instead) - and developers would not be able to use it by mistake.

If we do this, we won't need to hope that the future developers and maintainers will remember to enforce these rules.

**Comment by nyh** [comment]
> Similarly, the developers of the topology framework can make an effort to have the "adjustments" they needed apply to the regular `execute()` and `execute_async()` functions and not require using a different function they invented `run_async()`.

According to the documentation https://docs.datastax.com/en/drivers/python/2.6/api/cassandra/cluster.html, doing exactly this should have been possible (but I didn't actually test it):

* The run_async() code sets `execute_async()`'s "timeout" parameter.
* The documentation explains that this "timeout" parameter overrides the session object's "default_timeout".
* But you can set this "default_timeout" by doing something like: `session = cluster.connect(); session.default_timeout = 200; yield session`. This change should apply to all calls of execute and execute_async, without needing wrapper functions or other monkey-business.

**Comment by denesb** [comment]
Fix here: https://github.com/scylladb/scylladb/pull/17529

**Comment by denesb** [comment]
@avikivity should we backport this?
