### ISSUE TITLE
Apply batch mutations to the same PK atomically.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#1689]
_Installation details_
Scylla version (or git commit hash): 906250dcbdbbee26c5892381ace90ec4d5e6223a

Currently if a batch contains several modifications to the same PK they are all applied separately, which makes it slower and break atomicity.  This can be fixed by combining all of them into one mutation and applying it only once.

**Comment by penberg** [comment]
Btw, this is the same as https://issues.apache.org/jira/browse/CASSANDRA-6737.

Cassandra merges the mutations to same PK in `BatchStatement.addStatementMutations()` that's called from `BatchStatement.getMutations()`. We can do something like this in `batch_statement::get_mutations()` but I'm still looking at how to do that.

**Comment by gleb-cloudius** [comment]
We have to not only merge mutations to the same PK inside single CF, but to merge modifications to  different CFs too, or make the modification atomic in some other way. There are people who relies on this behavior and achieving it  through batchlog reply is very expensive (cassandra bypass batchlog if only one PK is modified).

**Comment by slivne** [comment]
I think we can start with the same CF

Its a bigger whole for anyone trying to insert multiple rows to the same CF
using unlogged batches - it is hurting our performance in those cases.

We can split the other part of multiple CFs.

**Comment by tzach** [comment]
@avikivity does your patch close this issue?

**Comment by avikivity** [comment]
No.

**Comment by l15k4** [comment]
Hey, does this mean that if I group inserts by PK on client side to reasonable sized **unlogged** batches, it won't improve throughput at all? I was planning to do this in next iteration. 

I think I adhere to all recommendations that I was able to collect during the last month of using Scylla 24/7 but I still get like 1/8 of the proclaimed performance from your benchmarks of both Reads/Writes especially due to cache evictions and limited concurrency while having reasonably sized partition. Scylla seems to be throttling both Reads/Writes and backpressuring clients. 

This was the only thing I can think of how to improve Writes.

**Comment by gleb-cloudius** [comment]
On Thu, Jun 01, 2017 at 03:02:08AM -0700, Jakub Liska wrote:
> Hey, does this mean that if I group inserts by PK on client side to reasonable sized **unlogged** batches, it won't improve throughput at all? I was planning to do this in next iteration. 
> 
This issue is not about throughput, but atomicity guaranty. If you'll
group inserts into the same PK in one unlogged batch it will reduce
amount of client/server communication and thus should improve
throughput. This is if cql driver is smart enough to send batch to
correct node (it may disable "smart" mode for batches, but I do not know
if it does).

--
			Gleb.

**Comment by l15k4** [comment]
@gleb-cloudius So you would currently recommend me to do this? I could also control size of these PK batches, not sure though what is the optimal size, ie. 500 rows of 50KB as a maximum for a single batch. Any suggestions?

**Comment by gleb-cloudius** [comment]
On Thu, Jun 01, 2017 at 03:34:23AM -0700, Jakub Liska wrote:
> @gleb-cloudius So you would currently recommend me to do this? I could also control size of these PK batches, not sure though what is the optimal size, ie. 500 rows of 50KB as a maximum for a single batch. Any suggestions? 
> 
First of all you need to check that using batches does not disable
"smart" driver decisions (it continues to send queries to nodes that
are responsible for given PK). You do use prepared statements, right?
Second we need to understands what is your bottleneck now. If it is CPU
or networking then batching should help, if it is disk IO it will not.
It will only make back pressure mechanism less efficient and may cause
timeouts.

--
			Gleb.

**Comment by l15k4** [comment]
@gleb-cloudius 
I use datastax driver with contact points to all 3 `i3.xlarge` nodes : 
```
    Cluster.builder()
      .withClusterName(cqlClusterName)
      .withSocketOptions(new SocketOptions().setReadTimeoutMillis(cqlSocketTimeout))
      .withCompression(if (cqlCompression) Compression.SNAPPY else Compression.NONE)
      .addContactPoints(cqlContactPoints:_*)
      .build().connect(cqlKeyspace)
```
And currently single-insert PreparedStatements.
Unfortunately, cache management is broken in grafana for some reason, it is always loading indefinitely.
I think that both disk and network IO is heavily underutilized.
```
Compacted partition maximum bytes: 545791
```
```
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00             19.00              0.00               149                 1
75%             0.00             33.00              0.00               258                 3
95%             0.00             64.15              0.00              1109                14
98%             0.00             99.74              0.00              2299                29
99%             0.00            109.01              0.00              3973                50
Min             0.00              1.00              0.00                87                 0
Max             0.00          35526.00              0.00            545791              8239
```

![](http://i.imgur.com/5uOWIpv.png)
![](http://i.imgur.com/n7cB4RR.png)
![](http://i.imgur.com/hjRghed.png)
![](http://i.imgur.com/fT9FQSV.png)

**Comment by gleb-cloudius** [comment]
On Thu, Jun 01, 2017 at 04:08:11AM -0700, Jakub Liska wrote:
> @gleb-cloudius 
> I use datastax driver with contact points to all 3 `i3.xlarge` nodes : 
> ```
>     Cluster.builder()
>       .withClusterName(cqlClusterName)
>       .withSocketOptions(new SocketOptions().setReadTimeoutMillis(cqlSocketTimeout))
>       .withCompression(if (cqlCompression) Compression.SNAPPY else Compression.NONE)
>       .addContactPoints(cqlContactPoints:_*)
>       .build().connect(cqlKeyspace)
> ```
> And currently single-insert PreparedStatements.

OK. Here
http://docs.datastax.com/en/developer/java-driver/3.2/manual/load_balancing/
they say that for batches "the first non-null keyspace is used as the
keyspace of the batch, and the first non-null routing key as its routing
key", so it should work OK for you in this regards, especially if you
have 3 nodes with RF=3 in which case smartiness of the driver does not
matter since all nodes have all data anyway.

Yes cluster seams underutilized.  For performance analysis it is better
to use scylladb-users mailing list. Can you send more information there
about your setup and your workload such as what are sizes of your typical
writes, what is your parallelism and what kind of back pressure do you
see from Scylla. Previously you've said your concurrency is limited.
Limited by whom? Your application or Scylla?

--
			Gleb.

**Comment by l15k4** [comment]
yeah, RF=3, so it should be OK. I updated the last comment with those 2 **answers**. I'll try to dig into it a little more and possibly move this thread to groups.google.

**Comment by gleb-cloudius** [comment]
On Thu, Jun 01, 2017 at 04:53:21AM -0700, Jakub Liska wrote:
> yeah, RF=3, so it should be OK. I updated the last comment with those 2 **answers**. I'll try to dig into it a little more and possibly move this thread to groups.google.
> 
It would be helpful to look at cpu utilization per shard. Graphana shows
average which may hide the fact that some shards are idle while other
are overutilized. This may happen if you have only one client that opens
small number of connections, so work is not properly distributed between
shards.
 
--
			Gleb.

**Comment by l15k4** [comment]
```
scyllatop *cpu-user*
```
Shows that the load is evenly distributed among shards, however CPU softirq is on some shards even 20%... 

I tried this as I'm using ec2 https://github.com/scylladb/scylla/wiki/Scylla-production-recommendation#cpu-pinning

But scylla doesn't start with this `cpu-set` value. I'm using the AMI for `i3` instances.

I also hope that `SEASTAR_IO="--max-io-requests=192"` is not wrong, it is generated by the io tune script. ` --num-io-queues` uses the default value, dunno what.

**Comment by kostja** [comment]
@avi I don't understand what else needs to be done about this issue except e3c003544dabf3c689ece8fcc74ab67ecc01d4a1 . Please reopen if you can clarify.
