### ISSUE TITLE
Fail to execute "CREATE KEYSPACE IF NOT EXISTS" when run multiple times in parallel

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#16909]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

During a performance test, at beginning, when we run multiple c-s commands at one time. C-s creates keyspace with ` CREATE KEYSPACE IF NOT EXISTS "keyspace1"` and it failed with error `Keyspace 'keyspace1' does not exist`:
```
WARN  07:40:03,718 Query '[0 bound values] CREATE KEYSPACE IF NOT EXISTS "keyspace1" WITH replication = {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor' : '3'} AND durable_writes = true;' generated server side warning(s): org.apache.cassandra.locator.SimpleStrategy replication class is not recommended, but was used for keyspace keyspace1. You may suppress this warning by delisting org.apache.cassandra.locator.SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.
java.lang.RuntimeException: Encountered exception creating schema
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:100)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:228)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace 'keyspace1' does not exist
```
In the meantime, other c-s command passed this step like 2 ms before:
```
WARN  07:40:03,716 Query '[0 bound values] CREATE KEYSPACE IF NOT EXISTS "keyspace1" WITH replication = {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor' : '3'} AND durable_writes = true;' generated server side warning(s): org.apache.cassandra.locator.SimpleStrategy replication class is not recommended, but was used for keyspace keyspace1. You may suppress this warning by delisting org.apache.cassandra.locator.SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.
```
We run 4 c-s commands and only one - the closest - failed.
Looks like there's a some race condition when creating the same keyspace with `create keyspace if not exists`

## Impact

Create keyspace stmt fails

## How frequently does it reproduce?

FIrst time seen

## Installation details

Kernel Version: 5.15.0-1051-aws
Scylla version (or git commit hash): `5.5.0~dev-20240119.b1ba904c4977` with build-id `7a5829efb1f6ef7b467d2dc837300abcc0b739c8`

Cluster size: 3 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- perf-regression-latency-ubuntu-db-node-77529f32-3 (52.23.210.123 | 10.12.5.185) (shards: 14)
- perf-regression-latency-ubuntu-db-node-77529f32-2 (54.237.184.98 | 10.12.7.85) (shards: 14)
- perf-regression-latency-ubuntu-db-node-77529f32-1 (54.205.88.134 | 10.12.5.45) (shards: 14)

OS / Image: `ami-0984b399539cb7745` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-shard-aware-1TB-test`
Test id: `77529f32-c2b9-4020-9827-7bcb327ecccb`
Test name: `scylla-master/scylla-master-perf-regression-latency-shard-aware-1TB-test`
Test config file(s):

- [perf-regression-latency-1TB.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0b01a7b25092e4b8b03fd4e89d9bff46fd41621b/test-cases/performance/perf-regression-latency-1TB.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 77529f32-c2b9-4020-9827-7bcb327ecccb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=77529f32-c2b9-4020-9827-7bcb327ecccb)
- Show all stored logs command: `$ hydra investigate show-logs 77529f32-c2b9-4020-9827-7bcb327ecccb`

## Logs:
- **db-cluster-77529f32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/db-cluster-77529f32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/db-cluster-77529f32.tar.gz)
- **sct-runner-77529f32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/sct-runner-77529f32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/sct-runner-77529f32.tar.gz)
- **monitor-set-77529f32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/monitor-set-77529f32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/monitor-set-77529f32.tar.gz)
- **loader-set-77529f32.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/loader-set-77529f32.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/77529f32-c2b9-4020-9827-7bcb327ecccb/20240121_074933/loader-set-77529f32.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/scylla-master-perf-regression-latency-shard-aware-1TB-test/83/)
[Argus](https://argus.scylladb.com/test/623b19d1-a201-4ed0-94a2-b42347a4d2e5/runs?additionalRuns[]=77529f32-c2b9-4020-9827-7bcb327ecccb)
</details>

**Comment by nyh** [comment]
It is curious that the failure message "Keyspace 'keyspace1' **does not** exist" - even if this were true, there should not be a problem to create a keyspace if it **does not** exist!

Do I understand correctly that the parallel operations are **all** CREATE KEYSPACE? Could there be a DROP KEYSPACE for this keyspace happening as parallel as well?

CC @kbr-scylla

**Comment by michoecho** [comment]
> It is curious that the failure message "Keyspace 'keyspace1' does not exist" - even if this were true, there should not be a problem to create a keyspace if it does not exist!

Most likely this failure didn't happen in the `CREATE KEYSPACE` statement, but in the `USE KEYSPACE` statement which follows it.

> Looks like there's a some race condition when creating the same keyspace with create keyspace if not exists

Perhaps `CREATE KEYSPACE` succeeded on node A, but `USE KEYSPACE` statement was sent to node B before it picked the new keyspace up? Or is Scylla supposed to prevent this kind of ordering?

**Comment by nyh** [comment]
> > It is curious that the failure message "Keyspace 'keyspace1' does not exist" - even if this were true, there should not be a problem to create a keyspace if it does not exist!
> 
> Most likely this failure didn't happen in the `CREATE KEYSPACE` statement, but in the `USE KEYSPACE` statement which follows it.

I initially thought something like this too, but then saw the error message claims it came from CREATE KEYSPACE and not USE KEYSPACE. But maybe there's some automated call for USE KEYSPACE in the Java driver, or something, and it didn't really come from the CREATE KEYSPACE?

> Perhaps `CREATE KEYSPACE` succeeded on node A, but `USE KEYSPACE` statement was sent to node B before it picked the new keyspace up? Or is Scylla supposed to prevent this kind of ordering?

In CQL, schema-changing operations like CREATE KEYSPACE return a response to the client telling it "I did a schema change, please wait for the schema to settle" - and at this point the client waits for the schema to settle; It shouldn't send a USE KEYSPACE to any node before this finishes. However, maybe Raft introduces a new problem - the schema can be said to "settle" when just a majority of nodes know of the new schema, not all of them? @kbr-scylla could this be a real problem, or I'm talking nonsense and "wait for the schema to settle" still waits for all nodes?

**Comment by michoecho** [comment]
> I initially thought something like this too, but then saw the error message claims it came from CREATE KEYSPACE and not USE KEYSPACE. 

It doesn't claim that. There's a log for `CREATE KEYSPACE`, followed by a separate log about an error.

There's a backtrace. If we knew what exact version of cassandra-stress was used, we could just check what's in the failed line of code.

**Comment by nyh** [comment]
> > I initially thought something like this too, but then saw the error message claims it came from CREATE KEYSPACE and not USE KEYSPACE.
> 
> It doesn't claim that. There's a log for `CREATE KEYSPACE`, followed by a separate log about an error.

Right, I misread the report, I thought it was one error message...

> There's a backtrace. If we knew what exact version of cassandra-stress was used, we could just check what's in the failed line of code.

Right. The recent Cassandra Stress implementation doesn't have these function names, so I don't know what they used.
The recent implementation indeed has:
```
            JavaDriverClient client  = settings.getJavaDriverClient(false);
            client.execute(createKeyspaceStatementCQL3(), org.apache.cassandra.db.ConsistencyLevel.LOCAL_ONE);
            client.execute("USE \""+keyspace+"\"", org.apache.cassandra.db.ConsistencyLevel.LOCAL_ONE);
```

So indeed there's a USE there too.

**Comment by soyacz** [comment]
Version: 3.11.3-SNAPSHOT

**Comment by michoecho** [comment]
> Version: 3.11.3-SNAPSHOT

That's not exact enough. 3.11.3-SNAPSHOT is not a release, it could mean any commit in the 3.11.3 cycle. And to figure out what a line number refers to, it really has to be exact.

**Comment by avikivity** [comment]
It's likely the same cassandra-stress bundled in scylladb itself, so the scylladb version is enough to see the code.

**Comment by soyacz** [comment]
`scylla-enterprise-tools.noarch           2019.1.4-20191218.c752b991ea.el7`

**Comment by soyacz** [comment]
but I need to confirm it (as I took it from some currently running loader, which can differ for OS tests)

**Comment by kbr-scylla** [comment]
> In CQL, schema-changing operations like CREATE KEYSPACE return a response to the client telling it "I did a schema change, please wait for the schema to settle" - and at this point the client waits for the schema to settle; It shouldn't send a USE KEYSPACE to any node before this finishes. However, maybe Raft introduces a new problem - the schema can be said to "settle" when just a majority of nodes know of the new schema, not all of them? @kbr-scylla could this be a real problem, or I'm talking nonsense and "wait for the schema to settle" still waits for all nodes?

"wait for schema to settle" is a driver side operation and it should wait for all nodes to have synced schema, Raft or not.
Perhaps the wait is skipped if we see that the keyspace already exists?
If so, I have a hypothesis what could be happening:
- one instance of driver creates keyspace on node A
- another instance of driver tries to create keyspace on node B
- node B performs raft barrier and applies the latest change from raft log, it sees that keyspace is present and returns
- that driver which tried node B *does not wait for schema to settle* because there was no schema change performed by B. So it instantly tries to `use keyspace`, and it uses some other node C for that
- node C didn't yet apply the keyspace creation from raft log, and it fails

**Comment by kbr-scylla** [comment]
@soyacz you didn't mark that this issue is a regression or not. Why? Is this a new test that you weren't running before?

**Comment by michoecho** [comment]
> scylla-enterprise-tools.noarch           2019.1.4-20191218.c752b991ea.el7

@soyacz No, the actual version is `2022.2.dev-0.20220330.eef4cbb20a51`. (I found the `ami_id_loader: ami-0e13359ca00856b35` in the logs, ran the AMI, and ran `cassandra-stress version` to find this out).

And as I expected, the InvalidQueryException was thrown from the `USE KEYSPACE`, not the `CREATE KEYSPACE`.

> It's likely the same cassandra-stress bundled in scylladb itself, so the scylladb version is enough to see the code.

@avikivity No, SCT doesn't use the current cassandra-stress version. IIUC it uses whatever is in the "loader AMI", which is manually updated, sometimes.

**Comment by soyacz** [comment]
> @soyacz you didn't mark that this issue is a regression or not. Why? Is this a new test that you weren't running before?

It's not a new test, but possibly we didn't run to such race condition in the past so I was skeptical to mark it as regression.



> "wait for schema to settle" is a driver side operation and it should wait for all nodes to have synced schema, Raft or not.

So, having c-s from `2022.2.dev-0.20220330.eef4cbb20a51` does the driver does it? Maybe it's time to update our loaders?

**Comment by soyacz** [comment]
cc @fruch ^^

**Comment by kbr-scylla** [comment]
> So, having c-s from 2022.2.dev-0.20220330.eef4cbb20a51 does the driver does it? Maybe it's time to update our loaders?

The driver did it since forever. It shouldn't have changed across versions.

**Comment by kbr-scylla** [comment]
> It's not a new test, but possibly we didn't run to such race condition in the past so I was skeptical to mark it as regression.

If it never happened before, but now it's happening regularly, then it's probably a regression.

The question is how often it's happening now. If it happened once in 1000 runs then indeed it might have always been a problem we just didn't see it.

In fact I'm surprised that concurrent "create keyspace if not exists" even worked at all before Raft. Maybe it's because they are creating the same keyspace with the same definition

**Comment by soyacz** [comment]
> > It's not a new test, but possibly we didn't run to such race condition in the past so I was skeptical to mark it as regression.
> 
> If it never happened before, but now it's happening regularly, then it's probably a regression.
> 
> The question is how often it's happening now. If it happened once in 1000 runs then indeed it might have always been a problem we just didn't see it.

It's a first time seen I suppose, so it is more like 1/1000 case

> In fact I'm surprised that concurrent "create keyspace if not exists" even worked at all before Raft. Maybe it's because they are creating the same keyspace with the same definition

can be that there was always bigger gap between c-s started on loaders and it was working without a problem.
So if I'm correct, this is a race condition in c-s rather than scylla. I'm correct?

**Comment by nyh** [comment]
> In fact I'm surprised that concurrent "create keyspace if not exists" even worked at all before Raft. Maybe it's because they are creating the same keyspace with the same definition

It should be fairly easy to write a test to reproduce this issue by a test designed especially to reproduce it. In test/cql-pytest/test_keyspace.py I wrote test_concurrent_create_and_drop_keyspace which tries to concurrently create and drop the same keyspace, and it used to fail miserably before raft, even on a single node, and succeed today.

To reproduce this problem, of the USE, we would need a cluster or more than one node (so not test/cql-pytest) and a connection which is not "exclusive" (i.e., USE can go to a different node). I think it should be easy to reproduce exactly the scenario that @kbr-scylla described above.

I have an idea how we can fix this problem:.

We can change **CREATE TABLE IF NOT EXISTS** to return the "please wait for schema agreement" magic return value even if the table already existed - not just if it was now created. This will force the second thread to also wait for schema agreement, even if it believes the table was not created.

@kbr-scylla what do you think?

The downside of my suggestion is that if a workload does a lot of useless CREATE TABLE IF NOT EXISTS in a loop, it will become slower. But I don't think this is a common workload. Workloads usually done one or a few CREATE TABLE in the beginning - and don't try and retry it before every request or anything like that.

**Comment by nyh** [comment]
I looked at the create_keyspace_statement.cc code and indeed it does:

```c++
    try {
        m = service::prepare_new_keyspace_announcement(qp.db().real_database(), _attrs->as_ks_metadata(_name, tm, feat), ts);
        ret = ::make_shared<event::schema_change>(
                event::schema_change::change_type::CREATED,
                event::schema_change::target_type::KEYSPACE,
                keyspace());
    } catch (const exceptions::already_exists_exception& e) {
        if (!_if_not_exists) {
          co_return coroutine::exception(std::current_exception());
        }
    }
    co_return std::make_tuple(std::move(ret), std::move(m), std::vector<sstring>());
```
This means that if the keyspace already exists, the prepare_new_keyspace_announcement accepts, and "ret" is not set.

It should be trivial to move the setting of ret before the try, and then a schema-change will be reported to the driver even if the keyspace didn't have to be created and IF NOT EXISTS.

It will be a one-line patch. We just need to decide: 1. should we do this? (as I mentioned above the downside is lower performance for repeated CREATE KEYSPACE IF NOT EXIST). and 2. who will write the test for this (any one of us can, but our managers can get upset).

**Comment by fruch** [comment]
> I think we need to confirm the root cause before applying a fix. The root cause is most likely the fact that the driver is using the keyspace at a node on which it didn't create it. We need to have fencing in the driver to fix that. @soyacz it would be nice if you did not leave it to developers to guess what actually happened in this case: which scylla nodes were used and how the schema and the barriers actually propagated. All of this would be visible with group0 trace level logging enabled.

Nice, you want us to guess it's related to group0, and guess what a barrier is, and enable some debug level for an issue that happens intermittently happens when we try to test performance.

**Comment by avikivity** [comment]
> Yes, @fruch I do.

It's unreasonable. There's no documentation that allows anyone to figure out what happens.

Anyway, @nyh found the cause - a node issues CREATE KEYSPACE, gets an immediate response and so misses the schema synchronization.

I think it's reasonable to always return a schema change announcement, CREATE * IF NOT EXISTS is rare enough.

We can consider looking at the keyspace/table age and skipping the notification if it's old enough. But probably unnecessary.

**Comment by nyh** [comment]
> Anyway, @nyh found the cause - a node issues CREATE KEYSPACE, gets an immediate response and so misses the schema synchronization.

I'll create the (one line) PR and ask @fruch and @soyacz to test it with their existing test.

As I said, we could write a stand-alone test that will exercise this specific issue. I'm not volunteering to do it, and it's not necessary if the original issue is reproducable.

**Comment by nyh** [comment]
Created https://github.com/scylladb/scylladb/pull/16969 to hopefully fix this, in the way I described above (CREATE KEYSPACE IF NOT EXISTS always returns a change event, even if the keyspace already existed and didn't need to be recreated).

@soyacz I don't know if you will be able to reproduce this issue and test the fix. If not, it might be worthwhile to write a dedicated test for this. It won't be trivial, but perhaps also not hard: It's not enough to just CREATE KEYSPACE IF NOT EXISTS in N parallel loops, you actually need to do thundering herds of CREATE KEYSPACE IF NOT EXISTS, and if the problem didn't happen, delete the keyspace, and start the whole thing again - possibly many times until it's reproduced.

**Comment by kostja** [comment]
> > Yes, @fruch I do.
> 
> It's unreasonable. There's no documentation that allows anyone to figure out what happens.
> 

First and foremost it's unreasonable to expect attention to SCT failures given every development team has plenty of well defined and well understood bugs to look at. 

Every SCT bug has to be triaged, and the current triage status is not good - most of them are sitting forever in github database with the tag "longevity"

Developers on the server team are somehow expected to understand how the code written by QA works, but the opposite is considered "unreasonable". 

Anyhow, you may continue to expect that a desire to have well defined, well understood, reproducible test cases is "unreasonable", however, this expectation only means that someone will have to do it - at the cost of everything else.

**Comment by nyh** [comment]
> Created #16969 to hopefully fix this, in the way I described above (CREATE KEYSPACE IF NOT EXISTS always returns a change event, even if the keyspace already existed and didn't need to be recreated).

I have withdrawn my pull request, and will discontinue my involvement in this issue completely for reasons explained in the PR.

**Comment by roydahan** [comment]
BTW, I already investigated the exact same issue with @fruch and I opened a PR in tools-Java to workaround this problem in c-s level.

we already knew that it’s happening in the “USE keyspace” and we thought it’s a given that it’s not waiting for the schema agreement.

https://github.com/scylladb/scylla-tools-java/pull/358

**Comment by fruch** [comment]
> @roydahan - what's the next step here? Any change in cassandra-stress via [scylladb/scylla-tools-java#358](https://github.com/scylladb/scylla-tools-java/pull/358) ?

I think the fix in:
https://github.com/scylladb/scylladb/pull/16969, should fit better,

the change in c-s https://github.com/scylladb/scylla-tools-java/pull/358 isn't working, removing of the `USE` is breaking all of the other code that generate queries

**Comment by kostja** [comment]
No, there is a patch and it's OK. And the problem is a pain in the field. @piodul could you please take a look and merge?

**Comment by piodul** [comment]
Unfortunately, the patch is not OK. It has a bug which leads to privilege escalation. In short, it interacts badly with https://github.com/scylladb/scylladb/commit/b8473f45a55cf5b6343547deb5e25e6cbc3eaea8; after merging it, it will become possible to gain permissions on an existing keyspace by running CREATE KEYSPACE IF NOT EXISTS on it. Fortunately, the test associated with that commit caught it.

The patch needs to be improved before merging. I can take this over.

**Comment by nuivall** [comment]
@kbr-scylla @kostja can we issue RPC to all nodes executing read barrier on all of them after we do schema change but before return cql result?

**Comment by kostja** [comment]
We can. @avikivity suggested it earlier. What is your idea of the fix though? I was thinking that merging CREATE KEYSPACE + permisisons itno a single raft command would solve the issue.

**Comment by kbr-scylla** [comment]
> @kbr-scylla @kostja can we issue RPC to all nodes executing read barrier on all of them after we do schema change but before return cql result?

And what happens if the barrier fails?

cc @gleb-cloudius -- WDYT of the proposal?

**Comment by nuivall** [comment]
> We can. @avikivity suggested it earlier. What is your idea of the fix though? I was thinking that merging CREATE KEYSPACE + permisisons itno a single raft command would solve the issue.

Not really, because when executing this `use keyspace` (if I got it right this is what throws exception) this single transaction may have not propagated to all nodes yet.

Single transaction will help with more advanced cases when we interlace statement execution but it doesn't looks like it's the case here.

> And what happens if the barrier fails?

Either we return failure to the client (with meaning that it's unknown if statement succeeded or not) or ignore it.

**Comment by kbr-scylla** [comment]
> Either we return failure to the client (with meaning that it's unknown if statement succeeded or not) 

We know that the statement succeeded, because the precondition for starting the barrier is committing the group 0 command and applying it locally (`add_entry` with `wait_type::applied`). So we know that it was applied locally and it will eventually be applied on every node[^1].

And if we ignore it and return regular success, then we don't give any additional guarantees compared to what we have now.

Perhaps we could include "barrier succeeded" boolean in the success message? Then the driver could potentially react to that (e.g. by skipping the "wait for schema agreement" step if barrier succeeded).

But I don't know if extending the return message like that is possible in backwards-compatible way. (Without breaking old drivers etc.)

[^1]: Assuming we don't lose majority and then recover based on the minority which didn't get the command -- but that's irrelevant for this discussion.

**Comment by kostja** [comment]
> > We can. @avikivity suggested it earlier. What is your idea of the fix though? I was thinking that merging CREATE KEYSPACE + permisisons itno a single raft command would solve the issue.
> 
> Not really, because when executing this `use keyspace` (if I got it right this is what throws exception) this single transaction may have not propagated to all nodes yet.
> 
> Single transaction will help with more advanced cases when we interlace statement execution but it doesn't looks like it's the case here.
> 
> > And what happens if the barrier fails?
> 
> Either we return failure to the client (with meaning that it's unknown if statement succeeded or not) or ignore it.

This is a different scope than what's needed to push the fix. All we need to do in scope of this pull request is to avoid security/consistency violaitons. Your suggestion is more broad and should perhaps be applied to all of DDL (it's a separate project).

**Comment by gleb-cloudius** [comment]
> > @kbr-scylla @kostja can we issue RPC to all nodes executing read barrier on all of them after we do schema change but before return cql result?
> 
> And what happens if the barrier fails?
> 
> cc @gleb-cloudius -- WDYT of the proposal?

Same as you. Not all nodes can be alive, etc. Why not do the obvious: run the barrier in the "USE" statement itself?

**Comment by gleb-cloudius** [comment]
> > > > @kbr-scylla @kostja can we issue RPC to all nodes executing read barrier on all of them after we do schema change but before return cql result?
> > > 
> > > 
> > > And what happens if the barrier fails?
> > > cc @gleb-cloudius -- WDYT of the proposal?
> > 
> > 
> > Same as you. Not all nodes can be alive, etc. Why not do the obvious: run the barrier in the "USE" statement itself?
> 
> Then you can't use "USE" during lost quorum?

Like any other DDL statement with DDL over raft. Who do you know you have a permission to access the keyspace without accessing the up-to-date raft state anyway?

**Comment by piodul** [comment]
> > > > > @kbr-scylla @kostja can we issue RPC to all nodes executing read barrier on all of them after we do schema change but before return cql result?
> > > > 
> > > > 
> > > > And what happens if the barrier fails?
> > > > cc @gleb-cloudius -- WDYT of the proposal?
> > > 
> > > 
> > > Same as you. Not all nodes can be alive, etc. Why not do the obvious: run the barrier in the "USE" statement itself?
> > 
> > 
> > Then you can't use "USE" during lost quorum?
> 
> Like any other DDL statement with DDL over raft. How do you know you have a permission to access the keyspace without accessing the up-to-date raft state anyway?

Do we consider "USE" to be a DDL operation? AFAIK it only serves as a shortcut not to have to type `keyspace_name.` everywhere and it only sets some per-connection state.

You can still try to access the keyspace by its full name, so doing a barrier in USE doesn't solve the general problem (accessing the keyspace on other nodes before those nodes know about it).

**Comment by kostja** [comment]
USE is not a DDL, @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> USE is not a DDL, @gleb-cloudius

It is implemented in `cql3/statements/use_statement.cc` so I would say it is. The fact that it does not do barrier now is just an oversight. The kind of error it gives also makes it obviously a DDL statement.  But if you so inclined to see it as some special unicorn we can run the barrier with a timeout and proceed with the statement if it fails.

**Comment by kostja** [comment]
> > USE is not a DDL, @gleb-cloudius
> 
> It is implemented in `cql3/statements/use_statement.cc` so I would say it is. The fact that it does not do barrier now is just an oversight. The kind of error it gives also makes it obviously a DDL statement. But if you so inclined to see it as some special unicorn we can run the barrier with a timeout and proceed with the statement if it fails.

Unfortunately our clients which use USE indirectly throughtheir drives, by setting the current keyspace, are not aware of where it is implemented, @gleb-cloudius , so they don't know it's a DDL according to your opinion. In other words, I think this direction in the discussion is a dead end. We're not going to change the way USE is used by the clients today and we can't regress it IMO.

**Comment by gleb-cloudius** [comment]
> 
> You can still try to access the keyspace items by their full name, so doing a barrier in USE doesn't solve the general problem (accessing the keyspace on other nodes before those nodes know about it).

That's why drivers waits for schema to propagate. That is a known limitation since we do not want to run raft barrier on each DML statement. The only way around it (as far as I see) is to have schema versioning between drivers and Scylla (so that Scylla will know that drivre's request uses newer schema and it needs to pull it). This is what @kostja calls fencing. But USE statement is not expected to be fast, so there is no problem running the barrier there unconditionally.

**Comment by gleb-cloudius** [comment]
> > > USE is not a DDL, @gleb-cloudius
> > 
> > 
> > It is implemented in `cql3/statements/use_statement.cc` so I would say it is. The fact that it does not do barrier now is just an oversight. The kind of error it gives also makes it obviously a DDL statement. But if you so inclined to see it as some special unicorn we can run the barrier with a timeout and proceed with the statement if it fails.
> 
> Unfortunately our clients which use USE indirectly throughtheir drives, by setting the current keyspace, are not aware of where it is implemented, @gleb-cloudius , so they don't know it's a DDL according to your opinion. In other words, I think this direction in the discussion is a dead end. We're not going to change the way USE is used by the clients today and we can't regress it IMO.

Why should they be aware? Why would we change how they will use it?

**Comment by kostja** [comment]
The difference between fencing and the barrier is that fencing only blocks the driver when the schema actually changed. If you add barrier to USE, you're going to issue it *on any new connection*, regardless of whether the schema has changed or not.

**Comment by gleb-cloudius** [comment]
> The difference between fencing and the barrier is that fencing only blocks the driver when the schema actually changed. If you add barrier to USE, you're going to issue it _on any new connection_, regardless of whether the schema has changed or not.

Right. I explained it here: https://github.com/scylladb/scylladb/issues/16909#issuecomment-2111871652.  And the problem is?

**Comment by gleb-cloudius** [comment]
It is not that I am against what you call fencing, but it will not be implemented tomorrow, so it is a long term solution.
