### ISSUE TITLE
maintenance socket causes trouble on local setups

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16912]
When running `test.py --mode=dev` locally, I observed the following tests to fail:
```
auth_cluster.test_maintenance_socket.1
object_store.test_basic.1
```
Turns out, the problem is that the path to the scylla repository that I run the tests in, is too long, see the excerpt from a failed node startup:
```
391 ERROR 2024-01-22 04:30:35,176 [shard 0:main] init - Startup failed: std::runtime_error (Maintenance socket path is too long: /home/bdenes/ScyllaDB/scylla/worktree1/testlog/dev/pytest-of-bdenes/pytest-0/test_misconfigured_storage0/cql.m. Change it to string shorter than 108 chars.)  
```

The maintenance socket should be placed at a path, where it won't randomly fail depending on how long the `/path/to/scylla.git` is, e.g. somewhere in `/tmp`.

**Comment by kbr-scylla** [comment]
In the meantime you can pass `--tmpdir` to test.py to change where test logs and Scylla workdirs are stored for this run. `/path/to/scylla.git/testlog` is just the default

**Comment by kostja** [comment]
@denesb I think the cure is worse than the disease in this case. Maybe shorten your path? cc @xtrey
