### ISSUE TITLE
almost all rolling upgrate tests failed by timmeout on 'Step4 - Verify data during mixed cluster mode' 

### ISSUE THREAD

**Issue by temichus** [scylladb/scylladb#16941]
## Issue description

looks like This issue is a regression because almost all rolling upgrade tests failed  in upgrate to new build 5.5.0 dev-20240119.b1ba904c4977 (the previous version that passed 5.5.0 dev-20240112.4e18f8b45381)

regarding investigation logs from job rolling-upgrade-ami-test the following information was found
1)"Step4 - Verify data during mixed cluster mode" was the last step in the logs
2) on node-1 "starting user-requested repair for keyspace scylla_bench", it never ends (same on node-4)
3) No errors in SCT/DB logs found that will indicate on some problem

## Impact

 rolling upgrade test failed 

## How frequently does it reproduce?

almost all rolling upgrade tests failed with this build

## Installation details

Kernel Version: 5.15.0-1051-aws
Scylla version (or git commit hash): `5.4.1-20231231.3d22f42cf9c3` with build-id `d14e5365966bbef5e2ecbae7fd67f207eba03042`
Target Scylla version (or git commit hash): `5.5.0~dev-20240119.b1ba904c4977` with build-id `7a5829efb1f6ef7b467d2dc837300abcc0b739c8`

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-6dc51730-4 (52.16.216.167 | 10.4.0.171) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-6dc51730-3 (52.31.16.169 | 10.4.0.162) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-6dc51730-2 (34.247.161.237 | 10.4.1.97) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-6dc51730-1 (52.50.24.109 | 10.4.0.167) (shards: 7)

OS / Image: `ami-01c5dc7c4aece1f2a` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `6dc51730-1350-4dd4-a8a1-19b1f9639807`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d311c6c14f705175817159c0bce264a17e644447/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 6dc51730-1350-4dd4-a8a1-19b1f9639807`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=6dc51730-1350-4dd4-a8a1-19b1f9639807)
- Show all stored logs command: `$ hydra investigate show-logs 6dc51730-1350-4dd4-a8a1-19b1f9639807`

## Logs:
- **db-cluster-6dc51730.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/db-cluster-6dc51730.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/db-cluster-6dc51730.tar.gz)
- **sct-runner-events-6dc51730.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/sct-runner-events-6dc51730.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/sct-runner-events-6dc51730.tar.gz)
- **sct-6dc51730.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/sct-6dc51730.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/sct-6dc51730.log.tar.gz)
- **loader-set-6dc51730.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/loader-set-6dc51730.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/loader-set-6dc51730.tar.gz)
- **monitor-set-6dc51730.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/monitor-set-6dc51730.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/6dc51730-1350-4dd4-a8a1-19b1f9639807/20240120_110310/monitor-set-6dc51730.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/201/)
[Argus](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=6dc51730-1350-4dd4-a8a1-19b1f9639807)
</details>

**Comment by kostja** [comment]
@bhalevy the procedure fails when starting repair, could you please assign out for an initial investigation?

**Comment by fruch** [comment]
this is still happening:

```
🟢 ❯ git log --oneline 4e18f8b45381..b1ba904c4977 | grep Merge
b50d9bb802 Merge 'Add code coverage support' from Eliran Sinvani
e62114214f Merge 'More logging for Raft-based topology' from Kamil Braun
debf6753c7 Merge 'test/cql-pytest: run tests with tablets' from Botond Dénes
70252ee36f Merge 'auth: do not include unused headers' from Kefu Chai
d65ce16cf6 Merge 'Prevent empty compaction tasks in cleanup, upgrade sstables, and add_sstable' from Benny Halevy
8087bc72f0 Merge 'Basic tablet repair support' from Asias He
787b24cd24 Merge 'raft topology: join: shut down a node on error in response handler' from Patryk Jędrzejczak
f22fc88a64 Merge 'Configure service levels interval' from Michał Jadwiszczak
3d76aefb98 Merge "Enhance topology request status tracking" from Gleb
a9844ed69a Merge 'view: revert cleanup filter that doesn't work with tablets' from Nadav Har'El
49026dc319 Merge 'Turn on tablets on keyspace by default when the feature is enabled' from Pavel Emelyanov
423234841e Merge 'add automatic sstable cleanup to the topology coordinator' from Gleb
```

I'll take a guess it might be related to 8087bc72f0 (it's the only series touching repair)

**Comment by fruch** [comment]
@bhalevy 

we need this checked, it's blocking all of the rolling upgrades tests

**Comment by bhalevy** [comment]
@denesb @asias please look into this.
The suspect is https://github.com/scylladb/scylladb/commit/8087bc72f05b5e23522b37cdffc4d30f57898e73

**Comment by mykaul** [comment]
@asias , @bhalevy - any updates?

**Comment by denesb** [comment]
I will have a look now.

**Comment by denesb** [comment]
At the point of the repair, 3 nodes are on 5.4 (one rolled back from 5.5 -- node2) and one node is on 5.5 (node4).

**Comment by denesb** [comment]
@asias can you please have a look at this? I cannot spot anything obvious to me, this will be something intricate (or really obivous after we find it) in the tablet-repair related changes.
Maybe we need to repeat the run with `--logger-log-level repair=trace`.

**Comment by fruch** [comment]
> @asias can you please have a look at this? I cannot spot anything obvious to me, this will be something intricate (or really obivous after we find it) in the tablet-repair related changes. Maybe we need to repeat the run with `--logger-log-level repair=trace`.

triggered a run with this debug level:
-  https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/rolling-upgrade-ubuntu20.04-test/18/

**Comment by asias** [comment]
I will take a look.

**Comment by fruch** [comment]
Not that it news, but this was happening on all of the rolling upgrade tests, for the 3rd week in a row.

**Comment by mykaul** [comment]
> Not that it news, but this was happening on all of the rolling upgrade tests, for the 3rd week in a row.

Probably why it should be added to the nightly tests and be caught sooner - and then we can just revert the offending commit.

**Comment by fruch** [comment]
> > Not that it news, but this was happening on all of the rolling upgrade tests, for the 3rd week in a row.
> 
> Probably why it should be added to the nightly tests and be caught sooner - and then we can just revert the offending commit.

We can trigger every 10min, if no one would be taking action based on it, I wouldn't really matter

**Comment by asias** [comment]
I've manged to reproduce it. I will send a patch shortly.

**Comment by fruch** [comment]
@asias 

Issue still happening on:
`5.5.0~dev-20240209.7a710425f0e2`

Fix didn't yet reach master ?

**Comment by fruch** [comment]
@asias 

 e7e1f4b01a98c538cd4afe58353d17192a4e96a4 is in, but issue still happens on the weekly runs of rolling upgrade:

## Packages

Base Scylla version: `5.4.2-20240117.6c625e8cd3c6` with build-id `a5ef58a15621d3ca6ad42c56a13932ae5ec60159`
Target Scylla version (or git commit hash): `5.5.0~dev-20240209.7a710425f0e2` with build-id `f4777533fdd4b53d42e7a22dd9605eb4feb4fc5a`

Kernel Version: `5.15.0-1052-aws`

## Installation details

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-be6d2bf9-4 (34.251.99.227 | 10.4.1.158) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-be6d2bf9-3 (34.251.97.186 | 10.4.0.222) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-be6d2bf9-2 (3.254.176.238 | 10.4.3.118) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-be6d2bf9-1 (3.254.74.100 | 10.4.1.212) (shards: 7)


OS / Image: `ami-085f534141c6fcb25` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `be6d2bf9-3ffd-44eb-846a-1c4cd36d8761`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fba16698a8f23c0c1457cc8e9c268d371f4b3d6c/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor be6d2bf9-3ffd-44eb-846a-1c4cd36d8761`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=be6d2bf9-3ffd-44eb-846a-1c4cd36d8761)
- Show all stored logs command: `$ hydra investigate show-logs be6d2bf9-3ffd-44eb-846a-1c4cd36d8761`


## Logs:
- **db-cluster-be6d2bf9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/db-cluster-be6d2bf9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/db-cluster-be6d2bf9.tar.gz)
- **sct-runner-events-be6d2bf9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/sct-runner-events-be6d2bf9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/sct-runner-events-be6d2bf9.tar.gz)
- **sct-be6d2bf9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/sct-be6d2bf9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/sct-be6d2bf9.log.tar.gz)
- **loader-set-be6d2bf9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/loader-set-be6d2bf9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/loader-set-be6d2bf9.tar.gz)
- **monitor-set-be6d2bf9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/monitor-set-be6d2bf9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/be6d2bf9-3ffd-44eb-846a-1c4cd36d8761/20240210_110839/monitor-set-be6d2bf9.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/204/)
[Argus](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=be6d2bf9-3ffd-44eb-846a-1c4cd36d8761)
</details>

**Comment by denesb** [comment]
> @asias
> 
> https://github.com/scylladb/scylladb/commit/e7e1f4b01a98c538cd4afe58353d17192a4e96a4 is in, but issue still happens on the weekly runs of rolling upgrade:

The fix for repair is here: https://github.com/scylladb/scylladb/pull/17156
It is still under review. There is a holiday in China this week, so I think this will move next week at the earliest.

**Comment by mykaul** [comment]
> > @asias
> > [e7e1f4b](https://github.com/scylladb/scylladb/commit/e7e1f4b01a98c538cd4afe58353d17192a4e96a4) is in, but issue still happens on the weekly runs of rolling upgrade:
> 
> The fix for repair is here: #17156 It is still under review. There is a holiday in China this week, so I think this will move next week at the earliest.

Unless someone can take over this (which isn't something I usually encourage) . @Deexie perhaps?

**Comment by denesb** [comment]
> Unless someone can take over this (which isn't something I usually encourage) . @Deexie perhaps?

Actually, I see that only I had comments and @tgrabiec and @asias just responded to me. So I think the PR is good to go in.

**Comment by asias** [comment]
@fruch With repair: Fix rpc::source and rpc::optional parameter order in rpc message #17156 in master, I assume we do not see the upgrade issues any more. The https://github.com/scylladb/scylladb/commit/e7e1f4b01a98c538cd4afe58353d17192a4e96a4 does not fix the repair related issue but the classic streaming.

**Comment by bhalevy** [comment]
The issue was introduced by https://github.com/scylladb/scylladb/commit/8087bc72f05b5e23522b37cdffc4d30f57898e73, right?
I.e. no backport required.
Please confirm.
