### ISSUE TITLE
tablet storage is not freed when migrating a tablet replica away

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#16946]
Here's a cluster that sees some nodes bootstrapped:

![image](https://github.com/scylladb/scylladb/assets/1017210/973dac96-8ad3-4e78-817f-ae5189465b7f)

However, storage is not released.

![image](https://github.com/scylladb/scylladb/assets/1017210/0fa891ce-8bf5-4d81-87e8-6dcf5cd9dd6e)

New node storage increases, but existing node storage does not decrease.

**Comment by raphaelsc** [comment]
It's the problem Michal bumped into, will be fixed with @bhalevy's patch that adds table_sstable_set, getting rid of the fragile need of refreshing the compound set.

**Comment by tgrabiec** [comment]
We need to verify that it's fixed after 8bfd078c54de71cc4434c58d679ef8b0bf73ef10 (suspected cause) and add a test.py test case for this.

**Comment by bhalevy** [comment]
> It's the problem Michal bumped into, will be fixed with @bhalevy's patch that adds table_sstable_set, getting rid of the fragile need of refreshing the compound set.

That one was dropped, as @avikivity opposed the idea of breaking sstable_set immutability.
I have an alternative approach for tablet_sstable_set that will allow cloning it in a cheap way in the prepare phase while replacing some old sstable_sets with new ones, for exception safety reasons, so the need to refresh it will still be needed (as long as it's immutable), it will just happen differently by preparing the mutated set upfront, and the applying the atomically in the execute() phase.

**Comment by bhalevy** [comment]
> We need to verify that it's fixed after [8bfd078](https://github.com/scylladb/scylladb/commit/8bfd078c54de71cc4434c58d679ef8b0bf73ef10) (suspected cause) and add a test.py test case for this.

The patch landed.  @michoecho can you please verify it fixed this issue?

**Comment by raphaelsc** [comment]
> > It's the problem Michal bumped into, will be fixed with @bhalevy's patch that adds table_sstable_set, getting rid of the fragile need of refreshing the compound set.
> 
> That one was dropped, as @avikivity opposed the idea of breaking sstable_set immutability. I have an alternative approach for tablet_sstable_set that will allow cloning it in a cheap way in the prepare phase while replacing some old sstable_sets with new ones, for exception safety reasons, so the need to refresh it will still be needed (as long as it's immutable), it will just happen differently by preparing the mutated set upfront, and the applying the atomically in the execute() phase.

Yes, we can make refresh just copy pointers, rather than building sets, even ones that were not changed. Each group becomes responsible for rebuild its own individual set, which happens only when a new sstable is added or removed.

**Comment by michoecho** [comment]
Only after I attempted to write a test for this, I realized it's impractical within our frameworks.

Before https://github.com/scylladb/scylladb/commit/8bfd078c54de71cc4434c58d679ef8b0bf73ef10 the extraneous storage was tied up in unlinked files. There is no way to measure that without looking at whole-filesystem stats. So to write a test for this, the tested node would have to run in its own private filesystem.

This cannot be arranged easily. To mount a filesystem, you need either `CAP_SYS_ADMIN` or appropriately configured FUSE, and we don't really want to give either to e.g. dbuild.

**Comment by nyh** [comment]
An idea: Maybe you can use /proc (or a utility like lsof that itself uses /proc) to see the open-but-unlinked file that Scylla is holding?

**Comment by raphaelsc** [comment]
Another idea: reimplement API /column_family/metrics/total_disk_space_used by iterating through sstables in sstables_manager. sstables_manager keeps a list of all sstable objects in the system, even the ones that were unlinked and no longer present in any sstable set.

**Comment by michoecho** [comment]
> An idea: Maybe you can use /proc (or a utility like lsof that itself uses /proc) to see the open-but-unlinked file that Scylla is holding?

@nyh I can, but what do I do with this information? Should the test expect that Scylla never keeps an unlinked file open, and report a bug if it does?

Note that you can only see the paths of deleted files, but you can't inspect them (aside from attaching a debugger into the process that keeps them open, and running fstat from there, I guess). So you can't e.g. measure their sizes. 

> Another idea: reimplement API /column_family/metrics/total_disk_space_used by iterating through sstables in sstables_manager. sstables_manager keeps a list of all sstable objects in the system, even the ones that were unlinked and no longer present in any sstable set.

@raphaelsc That's rather unsatisfying because it means we have to trust Scylla's bookkeeping. But if you think this piece of bookkeeping is unlikely to be wrong, then I can add such an API.

**Comment by raphaelsc** [comment]
> > An idea: Maybe you can use /proc (or a utility like lsof that itself uses /proc) to see the open-but-unlinked file that Scylla is holding?
> 
> @nyh I can, but what do I do with this information? Should the test expect that Scylla never keeps an unlinked file open, and report a bug if it does?
> 
> Note that you can only see the paths of deleted files, but you can't inspect them (aside from attaching a debugger into the process that keeps them open, and running fstat from there, I guess). So you can't e.g. measure their sizes.
> 
> > Another idea: reimplement API /column_family/metrics/total_disk_space_used by iterating through sstables in sstables_manager. sstables_manager keeps a list of all sstable objects in the system, even the ones that were unlinked and no longer present in any sstable set.
> 
> @raphaelsc That's rather unsatisfying because it means we have to trust Scylla's bookkeeping while testing its bookkeeping. But if you think this piece of bookkeeping is unlikely to be wrong, then I can add such an API.

Ideally, we would inspect filesystem stats, but you said it cannot be achieved easily, so we can trust scylla to tell us the total disk space used by sstables.

**Comment by nyh** [comment]
> > An idea: Maybe you can use /proc (or a utility like lsof that itself uses /proc) to see the open-but-unlinked file that Scylla is holding?
> 
> @nyh I can, but what do I do with this information? Should the test expect that Scylla never keeps an unlinked file open, and report a bug if it does?

I'm not sure I understand the whole story, but if there's a situation when you know the file should NOT be open, then you can check that. For example, you can write a test that reads from a tablet once, migrates the tablet to a different node, and then checks the sstable in question is no longer open. I'm not saying it's trivial, but it's doable.

> Note that you can only see the paths of deleted files, but you can't inspect them (aside from attaching a debugger into the process that keeps them open, and running fstat from there, I guess). So you can't e.g. measure their sizes.

That's not true - as long as the file is open, even if it was unlinked, you can read its full content and see its size - both from inside the process (obviously) but also via /proc.
Here's an example in the shell (in a shell, `exec` can be used to open a file and keep it open):

```
$ echo $$
3394755
$ exec 3>/tmp/tmpfile
$ echo hello >&3
$ cat /tmp/tmpfile
hello
$ rm /tmp/tmpfile
$ cat /tmp/tmpfile
cat: /tmp/tmpfile: No such file or directory
$ ls -l /proc/3394755/fd/3
l-wx------. 1 nyh nyh 64 Feb 11 13:20 /proc/3394755/fd/3 -> '/tmp/tmpfile (deleted)'
$ cat /proc/3394755/fd/3
hello
```

As you can see, after being deleted, the file is still fully accessable - both size and full content, as `/proc/<pid>/fd/3` (I knew the file descriptor was 3). You can list `/proc/<pid>/fd` to get the list of file descriptors if you don't know its number.

**Comment by michoecho** [comment]
> That's not true - as long as the file is open, even if it was unlinked, you can read its full content and see its size [...] via /proc

@nyh Oh, wow, right. I didn't think about that. I didn't realize how magical those "symlinks" are.

I think that's what I'm going to use. Thanks.

**Comment by nyh** [comment]
> > That's not true - as long as the file is open, even if it was unlinked, you can read its full content and see its size [...] via /proc
> 
> @nyh Oh, wow, right. I didn't think about that. I didn't realize how magical those "symlinks" are.

Indeed, lstat() and friends do interesting things on those "symlinks" :-)

Plan 9 had some good ideas. UTF-8 was another one.

**Comment by nyh** [comment]
By the way, I don't know what test framework you were think of using, in some of them you have direct access to Scylla's process id. But in test/cql-pytest this sort of out-of-band communication isn't "cool" (the test is supposed to work also on Scylla run by the user manually, and not know what Scylla's process id is), so there's a test/cql-pytest/util.py function `local_process_id()` to find the process id of Scylla which listens to CQL. It sports another funky use of /proc - both /proc/net/tcp and /proc/*/fd.

**Comment by michoecho** [comment]
> By the way, I don't know what test framework you were think of using, in some of them you have direct access to Scylla's process id. But in test/cql-pytest this sort of out-of-band communication isn't "cool"

The framework is TopologyTest from test.py. These tests directly manipulate the nodes. Getting their PID is fine there.

> We need to verify that it's fixed after https://github.com/scylladb/scylladb/commit/8bfd078c54de71cc4434c58d679ef8b0bf73ef10 (suspected cause) and add a test.py test case for this.

I wrote a new test (d7955dec6222d5b01544bc00d3eae82459da8d32), which uses `/proc/$pid/fd/*` (37eb02a7b41e043ff5c5a9a7442022480ab73cd1) to account for the deleted-but-open files.

And apparently 8bfd078c54de71cc4434c58d679ef8b0bf73ef10 is not enough to release the files. Something else is still holding them open.

**Comment by nyh** [comment]
> > By the way, I don't know what test framework you were think of using, in some of them you have direct access to Scylla's process id. But in test/cql-pytest this sort of out-of-band communication isn't "cool"
> 
> The framework is TopologyTest from test.py. These tests directly manipulate the nodes. Getting their PID is fine there.
> 
> > We need to verify that it's fixed after [8bfd078](https://github.com/scylladb/scylladb/commit/8bfd078c54de71cc4434c58d679ef8b0bf73ef10) (suspected cause) and add a test.py test case for this.
> 
> I wrote a new test ([d7955de](https://github.com/scylladb/scylladb/commit/d7955dec6222d5b01544bc00d3eae82459da8d32)), which uses `/proc/$pid/fd/*` ([37eb02a](https://github.com/scylladb/scylladb/commit/37eb02a7b41e043ff5c5a9a7442022480ab73cd1)) to account for the deleted-but-open files.

Nice. But I looked at the code, and I think you accidentally used stat() where you should have used lstat()? I think it doesn't account the deleted file size correctly if you use stat()...

> And apparently [8bfd078](https://github.com/scylladb/scylladb/commit/8bfd078c54de71cc4434c58d679ef8b0bf73ef10) is not enough to release the files. Something else is still holding them open.

So good you're writing a test :-)
By the way, I still didn't understand why the **size** of the deleted files mattered to you in the first place. Isn't just the fact that they remain open the problem, regardless of their size?

**Comment by michoecho** [comment]
> By the way, I still didn't understand why the size of the deleted files mattered to you in the first place. Isn't just the fact that they remain open the problem, regardless of their size?

Yes, you're right, I overthought it. My reasoning was "there's technically nothing wrong about using deleted-but-open files, so the test shouldn't treat that as something illegal". But after sleeping on it, I see that it's stupid.

**Comment by michoecho** [comment]
I found the culprit. It's the backlog tracker. It keeps references to sstables and is not cleaned after tablet migration, so it keeps the sstables open indefinitely. (Perhaps this also can cause some other problems when the tablet is migrated back? I don't know how the tracker works.)

@raphaelsc What should we do about this?

**Comment by michoecho** [comment]
By the way, this is a good moment to take a step back and think about how we got here. This is the second bug in `cleanup_tablet`. First, we forgot to update the compound set. Second, we forgot to clean the backlog tracker. If it's easy enough to forget things like this, perhaps the APIs are not caller-friendly enough.

**Comment by raphaelsc** [comment]
```
        // Synchronizes with in-flight writes if any, and also takes care of flushing if needed.
        // FIXME: to be able to stop group and provide guarantee above, we must first be able to reallocate a new group if tablet is migrated back.
        //co_await _cg.stop();
```

**Comment by michoecho** [comment]
> ```
>         // Synchronizes with in-flight writes if any, and also takes care of flushing if needed.
>         // FIXME: to be able to stop group and provide guarantee above, we must first be able to reallocate a new group if tablet is migrated back.
>         //co_await _cg.stop();
> ```

Ah, so this was half-expected?

**Comment by raphaelsc** [comment]
> By the way, this is a good moment to take a step back and think about how we got here. This is the second bug in `cleanup_tablet`. First, we forgot to update the compound set. Second, we forgot to clean the backlog tracker. If it's easy enough to forget things like this, perhaps the APIs are not caller-friendly enough.

It's only a transient issue, until compaction groups are dynamically allocated.  The need to refresh compound set explicitly is problematic indeed and we need to put thought there to improve it.

**Comment by raphaelsc** [comment]
> > ```
> >         // Synchronizes with in-flight writes if any, and also takes care of flushing if needed.
> >         // FIXME: to be able to stop group and provide guarantee above, we must first be able to reallocate a new group if tablet is migrated back.
> >         //co_await _cg.stop();
> > ```
> 
> Ah, so this was half-expected?

Yes :-)

**Comment by michoecho** [comment]
@raphaelsc Just to clarify: are you working on https://github.com/scylladb/scylladb/issues/16877, or planning to work on it in the near future? Or is it waiting to be picked up by someone else?

**Comment by raphaelsc** [comment]
> @raphaelsc Just to clarify: are you working on #16877, or planning to work on it in the near future? Or is it waiting to be picked up by someone else?

It's on @ptrsmrn's team. The fix is very simple. Allocate new group when tablet is migrating in, deallocate old one on cleanup. I understand you don't want to maintain your test out of the tree for too long right?

please try your test with this, if it works, then we can close this issue and don't depend on #16877.

```
diff --git a/replica/table.cc b/replica/table.cc
index 400dcabbed..dea85099b9 100644
--- a/replica/table.cc
+++ b/replica/table.cc
@@ -3496,6 +3496,7 @@ future<> compaction_group::cleanup() {
             set->for_each_sstable([&all_sstables] (const sstables::shared_sstable& sst) mutable {
                 all_sstables.push_back(sst);
             });
+            _cg.backlog_tracker_adjust_charges(all_sstables, {});
             return _cg.delete_sstables_atomically(std::move(all_sstables));
         }
```

**Comment by michoecho** [comment]
> please try your test with this, if it works, then we can close this issue and don't depend on https://github.com/scylladb/scylladb/issues/16877.

It works, but is it correct to do this in `prepare()` (and not `execute()`)?

> I understand you don't want to maintain your test out of the tree for too long right?

No, I'm fine with waiting with the test. It's just that fixing the storage freeing problem is needed for the release, so I was wondering if it's assigned to someone.

**Comment by raphaelsc** [comment]
> > please try your test with this, if it works, then we can close this issue and don't depend on #16877.
> 
> It works, but is it correct to do this in `prepare()` (and not `execute()`)?

No, and we should even delete after execution. But in practice, at cleanup stage, we're not even consuming from this leaving replica and cleanup is also retried until it succeeds. Anyway, we should respect the prepare and execute semantics.

> 
> > I understand you don't want to maintain your test out of the tree for too long right?
> 
> No, I'm fine with waiting with the test. It's just that fixing the storage freeing problem is needed for the release, so I was wondering if it's assigned to someone.

Alright then. thanks.

**Comment by bhalevy** [comment]
So what's the verdict?
Do we need to adjust the backlog tracker charges (in the execute phase) in addition to #16877?

**Comment by raphaelsc** [comment]
> So what's the verdict? Do we need to adjust the backlog tracker charges (in the execute phase) in addition to #16877?

https://github.com/scylladb/scylladb/issues/16877 is enough, as compaction group will be deallocated anyway.

**Comment by bhalevy** [comment]
@raphaelsc is this issue still valid?

**Comment by bhalevy** [comment]
> > By the way, this is a good moment to take a step back and think about how we got here. This is the second bug in `cleanup_tablet`. First, we forgot to update the compound set. Second, we forgot to clean the backlog tracker. If it's easy enough to forget things like this, perhaps the APIs are not caller-friendly enough.
> 
> It's only a transient issue, until compaction groups are dynamically allocated. The need to refresh compound set explicitly is problematic indeed and we need to put thought there to improve it.

@raphaelsc can you please verify that the issue can be closed now?

**Comment by raphaelsc** [comment]
> > > By the way, this is a good moment to take a step back and think about how we got here. This is the second bug in `cleanup_tablet`. First, we forgot to update the compound set. Second, we forgot to clean the backlog tracker. If it's easy enough to forget things like this, perhaps the APIs are not caller-friendly enough.
> > 
> > 
> > It's only a transient issue, until compaction groups are dynamically allocated. The need to refresh compound set explicitly is problematic indeed and we need to put thought there to improve it.
> 
> @raphaelsc can you please verify that the issue can be closed now?

I think so. @michoecho do you mind rebasing https://github.com/scylladb/scylladb/compare/master...michoecho:scylla:test_tablet_storage_freeing and sending a PR? it should pass now. we can close this issue with the test validating it.

**Comment by raphaelsc** [comment]
new test added in https://github.com/scylladb/scylladb/pull/18906 passed 100 times confirming this issue is fixed, closing this.
