### ISSUE TITLE
Cannot restore backup with sstableloader

### ISSUE THREAD

**Issue by JackThird** [scylladb/scylladb#16968]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.0-0.20231205.58a89e7a4231
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu Server 22.04 LTS

Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): bare metal (hosting provider)
Hardware: CPU=8c/16t, memory=64GB
Disks: (SSD/HDD, count) 2x512GB SSD RAID 0, filesystem=XFS
Network: Public=1Gbps, Private=2Gbps
Swap: 16GB

Hi, I'm trying to restore a keyspace backup (RF=3) taken via nodetool snapshot to a single node test server but I receive below error:
```
root@testscylla:~/scylla_bck/kairosdb_XXX-202401240101# sstableloader -d 127.0.0.1 kairosdb_XXX/data_points
===== Using optimized driver!!! =====
WARN  17:05:08,428 Skipping file me-3gd1_0021_0vxox2fo7khskytqp2-big-Digest.crc32 - unsupported SSTable format or version
WARN  17:05:08,429 Skipping file me-3gd1_0021_0wku82jhjya0b0xgme-big-Summary.db - unsupported SSTable format or version
WARN  17:05:08,430 Skipping file me-3gd1_0021_0wku82pfcg7k5ppwme-big-Index.db - unsupported SSTable format or version
WARN  17:05:08,430 Skipping file me-3gd1_0021_0ufog24ay6z1udihk6-big-Scylla.db - unsupported SSTable format or version
WARN  17:05:08,430 Skipping file me-3gd1_0021_0wsk12mlvld0a71u92-big-Index.db - unsupported SSTable format or version
WARN  17:05:08,430 Skipping file me-3gd1_0021_0ufog24ay6z1udihk6-big-Index.db - unsupported SSTable format or version
WARN  17:05:08,430 Skipping file me-3gd1_0021_0wku82jhjya0b0xgme-big-CompressionInfo.db - unsupported SSTable format or version
[...]
  0% done.        0 statements sent (in        0 batches,        0 failed).
       0 statements generated.
       0 cql rows processed in        0 partitions.
       0 cql rows and        0 partitions deleted.
       0 local and        0 remote counter shards where skipped.   
```

I thought it was a scylla version mismatch between my prod and dev envs but they are the same:
```
# DEV
$ scylla --version
5.4.0-0.20231205.58a89e7a4231

$ curl -X GET "http://localhost:10000/storage_service/scylla_release_version"
"5.4.0-0.20231205.58a89e7a4231"

#PROD
$ scylla --version
5.4.0-0.20231205.58a89e7a4231

$ curl -X GET "http://localhost:10000/storage_service/scylla_release_version"
"5.4.0-0.20231205.58a89e7a4231"
```

On my DEV env I had a scylla version 5.1.1-0.20221208.1cfedc5b59f4 that I upgraded to 5.4.0-0.20231205.58a89e7a4231.
I deleted also /var/lib/scylla directory to start from scratch and changed RF from 3 to 1 in schema (file: kairosdb_XXX_schema.cql).

I attach dev env's files about:
syslog
scylla.yaml
directory_tree.png
cqlsh schema
[dev_20240124.zip](https://github.com/scylladb/scylladb/files/14041132/dev_20240124.zip)

I followed your guides for [full backup](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/backup.html) and [restore](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cassandra-to-scylla-migration-process.html).

PS. maybe it's linked to ticket #7035

**Comment by JackThird** [comment]
Hello, I drop a ping :)

**Comment by mykaul** [comment]
@denesb - can someone look at this?

**Comment by denesb** [comment]
This is the well known issue of `sstableloader` not supporting UUID generations.

**Comment by mykaul** [comment]
So the alternative, load and stream (https://opensource.docs.scylladb.com/stable/operating-scylla/nodetool-commands/refresh.html#load-and-stream ) could be used.

**Comment by JackThird** [comment]
[Here](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html) I read:
`The procedure restores each node using the backup file of the same node. If this is not the case, one should use other restoration methods tools like [sstableloader](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cassandra-to-scylla-migration-process.html). This procedure is much slower than restoring to the same topology cluster.`

As I understood @denesb, default value for uuid_sstable_identifiers_enabled is True so my sstables have UUID identifiers and sstableloader cannot be used to restore backup on a different size scylla cluster, right?

I'm a bit confused about scylla backup/restore procedures without using scylla-manger.

I did a test with @mykaul advise but I wa not able to see data.

My (dirty) workaround and maybe not a good solution:
- perform full snapshot backup and export schema
- import keyspace schema on scylla test node
- restart scylla to trigger dir creation under /var/lib/scylla/data/keyspace
- stop scylla service
- move snapshot files inside new created /var/lib/scylla/data/keyspace dirs
- start scylla service

nodetool repair/refresh not performed, data is available on test node.

**Comment by denesb** [comment]
> [Here](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html) I read: `The procedure restores each node using the backup file of the same node. If this is not the case, one should use other restoration methods tools like [sstableloader](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cassandra-to-scylla-migration-process.html). This procedure is much slower than restoring to the same topology cluster.`
> 
> As I understood @denesb, default value for uuid_sstable_identifiers_enabled is True so my sstables have UUID identifiers and sstableloader cannot be used to restore backup on a different size scylla cluster, right?

Yes.

> Do you have some ref. on listed issue?

We do not plan to add UUID generation support to sstableloader, instead we are working on retiring it altogether. The replacement will be `nodetool refresh --load-and-stream`

 
> I'm a bit confused about scylla backup/restore procedures without using scylla-manger.
> 
> I did a test with @mykaul advise but I wasn't able to see data.
> 
> My (dirty) workaround and maybe not a good solution:
> 
>     * perform full snapshot backup and export schema
> 
>     * import keyspace schema on scylla test node (RF changed from 3 -> 1)
> 
>     * restart scylla to trigger dir creation under /var/lib/scylla/data/keyspace
> 
>     * stop scylla service
> 
>     * move snapshot files inside new created /var/lib/scylla/data/keyspace dirs

I don't understand how this works without creating the tables?

> 
>     * start scylla service
> 
> 
> nodetool repair/refresh not performed, data is available on test node.

This is dangerous and it only worked because you had a single node which owns the entire ring. The correct procedure is to copy the table's sstables into the `upload` directory of the respected table, then do `nodetool refresh --load-and-stream`. This will guarantee that all data will end up on the node which owns it. Testing this procedure on a single node will not yield relevant result, try testing on a 3 node cluster.

**Comment by JackThird** [comment]
@denesb Thank you for the info, now it's clearer.
I did the test via nodetool refresh -las with file inside upload directories and I can see data.

Will you adapt also restore/backup scylla documentation in the future, please?

**Comment by denesb** [comment]
> Will you adapt also restore/backup scylla documentation in the future, please?

Yes.

@tzach @annastuchlik

**Comment by mykaul** [comment]
@JackThird - can we close this issue now?

**Comment by JackThird** [comment]
Hello,
sorry, I thought it was a reminder for the documentation update. 
Let me close it and thank you again :)
