### ISSUE TITLE
github-actions: add auto assign action

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#16988]
As preparation for the automated backport process, we are working on, we need to make sure the same code owner who fixed the issue in `master` will be assigned to the backport request

The way we can do it is to auto-assign each PR to the person who opened it. Then we can reflect it to the backport PR

**Comment by roydahan** [comment]
@yaronkaikov please remind me, why do we need the assignee in the original PR? can't we just read the "author" of the original one?

**Comment by yaronkaikov** [comment]
@roydahan I checked again, it seems it's not needed. Closing this for now
