### ISSUE TITLE
docs: Issue in page ScyllaDB FAQ

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#17003]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.4/faq

### Problem

It says "It is not possible to turn off the Scylla cache", which is not true. It's possible to do so via scylla.yaml option "enable_cache: false". 

###  Suggest a fix

Tell the truth, or at least don't lie.

**Comment by tgrabiec** [comment]
To give context, there is a confused user because of this: https://github.com/scylladb/scylladb/issues/16759#issuecomment-1911526276

**Comment by tzach** [comment]
Yet one more example of
https://github.com/scylladb/scylladb/issues/16631
