### ISSUE TITLE
tablets replace: Unable to find new replica for tablet when replacing a node in place after cluster restart

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#17025]
Seen with repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_replace_node_after_cluster_restart
The test starts a 3 node cluster with rf=3.
The it stops all nodes and restarts only 2 of them.
The 3rd node is wiped and started to replace its previous incarnation.
This fails with:
```
ERROR 2024-01-28 21:09:09,092 [shard 0:main] init - Startup failed: std::runtime_error (Replace failed. See earlier errors (Rolled back: Failed to drain tablets: std::runtime_error (Unable to find new replica for tablet b114ab20-be10-11ee-bdb0-92af7ccf2c80:1 on 78bb7269-ad74-4cac-9777-969844543410:1 when draining {78bb7269-ad74-4cac-9777-969844543410})))
```

Cc @tgrabiec

**Comment by xemul** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/119

Same in the test_enable_rbno_for_default_operation test case

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla-dtest/pull/3905

**Comment by bhalevy** [comment]
Some dtests were adjusted to mitigate this issue.
See https://github.com/scylladb/scylla-dtest/pull/3995

**Comment by bhalevy** [comment]
@tgrabiec what unit test / dtest reproduces this?

**Comment by tgrabiec** [comment]
test_mv_tablets_replace.py and test_tablets_removenode.py::test_replace
