### ISSUE TITLE
Fix MV dtests with consistent topology enabled

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#17021]
A prerequisite to enabling tablets is to enable consistent topology changes. @bhalevy ran all dtests with this experimental flag enabled, in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release-with-consistent-topology-changes/36/#showFailuresLink, and unfortunately, most of the failures appear to be MV-related tests. The following tests failed:

* materialized_views_test.TestMaterializedViews.test_remove_node_during_mv_insert_3_nodes
* materialized_views_test.TestMaterializedViews.test_remove_node_during_mv_insert_4_nodes
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_and_resharding_half_to_max_test
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_and_resharding_half_to_low_test
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_and_resharding_low_to_half_test
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_and_resharding_max_to_half_test 
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_with_resharding_max_to_half_test
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_with_resharding_half_to_low_test
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_with_resharding_low_to_half_test
* materialized_views_test.TestInterruptBuildProcess.test_interrupt_build_process_with_resharding_half_to_max_test
* materialized_views_test.TestMaterializedViews.test_mv_resurrected_rows_after_decommission_interrupt[without_rbno]
* materialized_views_test.TestMaterializedViews.test_mv_resurrected_rows_after_decommission_interrupt[with_rbno]

We need to figure out why, and fix the tests or the code.

**Comment by nyh** [comment]
The tests `test_remove_node_during_mv_insert*` failed on a "directory not empty" error appearing in the log (and dtest doesn't like unknown errors in the log) referring to files in the hints or view_hints directory:

```
E               ERROR 2024-01-27 11:29:57,780 [shard 0:strm] hints_manager - Exception when draining 127.0.81.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.dtest/dtest-hg7cng3l/test/node1/hints/0/127.0.81.2])
```
```
E               ERROR 2024-01-27 11:33:36,573 [shard 0:strm] hints_manager - Exception when draining 127.0.63.2: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/jenkins/workspace/scylla-master/dtest-release-with-consistent-topology-changes/scylla/.dtest/dtest-xg6vabp4/test/node1/view_hints/0/127.0.63.2])
```

The `*resharding*` tests all failed with core dumps...

The `resurrected_rows` tests failed with some sort of Raft error:
```
E           AssertionError: Unexpected errors found: [('node1', ['ERROR 2024-01-27 11:36:32,225 [shard 0:strm] raft_topology - send_raft_topology_cmd(stream_ranges) failed with exception (node state is decommissioning): seastar::rpc::closed_error (connection is closed)'])]
```

None of these errors appear to be caused by materialized views specific code, so @kostja I need your advice whether I should look into these issues myself (this is what I would have done normally) or you think that you want to assign them to someone else.

**Comment by nyh** [comment]
Opened separate issues for the separate problems above:
1. https://github.com/scylladb/scylladb/issues/17023 on the non-empty hints directory. This failure has nothing to do with materialized views - it's about writing (even of the base table) while doing a "remove node" operation, and a race condition between the node going down and storing hints for it.

**Comment by bhalevy** [comment]
@nyh what's left to resolve in this issue?

**Comment by nyh** [comment]
> @nyh what's left to resolve in this issue?

I will need to run it again to make sure. It looks like two issues I linked above are still open, but maybe they should have been closed too. I'll check.

**Comment by nyh** [comment]
Since dtest commit https://github.com/scylladb/scylla-dtest/commit/a643c4d234033260ef5b5c1f6d0d2b987a69c07c, dtest now enables consistent-topology-changes by default, so running any of these tests should have seen these problems if they still existed.

However, since https://github.com/scylladb/scylla-dtest/commit/17f9d015868ffb6fb27595099ce63dcc502832c7 none of the materialized views are in gating, so I can no longer know if they fail or not. So I'll run them again now to confirm.

**Comment by nyh** [comment]
Ran all aforementioned tests with current Scylla and dtest (which enables consistent topologyh by default):

The following tests passed:
* `materialized_views_test.py::TestMaterializedViews::test_remove_node_during_mv_insert_3_nodes`
* `materialized_views_test.py::TestMaterializedViews::test_remove_node_during_mv_insert_4_nodes`
* `materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_and_resharding_half_to_max_test`
* `materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_and_resharding_half_to_low_test`
* `materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_and_resharding_low_to_half_test`
* `materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_and_resharding_max_to_half_test`
* ...
* `materialized_views_test.py::TestInterruptBuildProcess::test_interrupt_build_process_and_resharding_half_to_max_test`
* `materialized_views_test.py::TestMaterializedViews::test_mv_resurrected_rows_after_decommission_interrupt[with_rbno]`
* materialized_views_test.py::TestMaterializedViews::test_mv_resurrected_rows_after_decommission_interrupt[without_rbno]

So none of these tests fail any more. Closing this issue.
