### ISSUE TITLE
Provide a way to query if a table is dropped for streaming and repair

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#17028]
Consider:

-  n1, n2, n3 in the cluster
-  n1 streams data to n2 / n1 runs repair with n2
-  a table t1 is dropped during  streaming / repair
-  it is possible n1 or n2 sees t1 is dropped while the other peer hasn't.

We want the streaming or repair operations to ignore those dropped table. 

There is a limitation in seastar rpc frame work, the exception type could not send back to the peer. For example, when the receiver of rpc call throws no_such_column_family, the sender only gets std::runtime_error instead of no_such_column_family exceptions. This makes it hard to send back exact error type back. 

In https://github.com/scylladb/scylladb/pull/16950 and https://github.com/scylladb/scylladb/pull/16686 tries to workaround the issue by sending a error code back. The problem is that there are lots of rpc calls used. It is error prone to convert every existing rpc calls to send a user error code (which should be handled by the rpc framework).

To avoid all those special handling of no_such_column_family everywhere, we can provide a way for the streaming or repair master node to check if a table is dropped, e.g., query from the raft statement if a table is dropped or not. When a streaming or repair fails, the master node check if a table is dropped using the previously mentioned method, and ignore table and go ahead without failing the operation.

**Comment by denesb** [comment]
I don't think this is enough. A table drop statement issued concurrent with this check, or any time after it, can result in  the same problem we have today. The result of the check becomes obsolete the second it is obtained. The only way to avoid is to use some raft locking primitive which inhibits dropping tables for a while, and use this window to run the initial part of the repair on all replicas. Repair would then make sure to pin the tables (via async gate) on all shards of all replicas in this init phase. After this, the lock can be released and repair could continue, because all repair-metas would now would have obtained the table handle and would hold on to it until the end of repair, ensuring the table cannot be dropped.

**Comment by asias** [comment]
> I don't think this is enough. A table drop statement issued concurrent with this check, or any time after it, can result in the same problem we have today. The result of the check becomes obsolete the second it is obtained. The only way to avoid is to use some raft locking primitive which inhibits dropping tables for a while, and use this window to run the initial part of the repair on all replicas. Repair would then make sure to pin the tables (via async gate) on all shards of all replicas in this init phase. After this, the lock can be released and repair could continue, because all repair-metas would now would have obtained the table handle and would hold on to it until the end of repair, ensuring the table cannot be dropped.

Note, the check happens after the repair is failed in the last step.

1) table is dropped
2) repair for a given table failed due to the drop
3) check if the table is dropped

Step 3 will return true only if the table is really get dropped. What's the race here?

It does not matter after step 3. There is nothing to do after step 3 for repair.

**Comment by denesb** [comment]
Indeed, I misunderstood the proposal.

Ignoring errors if the table is dropped, could potentially paper over other bugs that may or may not correlate with table drops. Maybe we can live with that.

**Comment by tchaikov** [comment]
"Can't find a column family with UUID"

adding keywords for SEO.

**Comment by denesb** [comment]
Doesn't https://github.com/scylladb/scylladb/pull/17231 already provide such a way?

**Comment by tchaikov** [comment]
but it's not merge yet.

**Comment by denesb** [comment]
This was a feature request, no backport needed.
