### ISSUE TITLE
docs: Issue in page System Requirements

### ISSUE THREAD

**Issue by TimMeiwald** [scylladb/scylladb#17037]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.4/getting-started/system-requirements

### Problem
ScyllaDB Sizing Calculator on this page 404's. URL https://price-calc.gh.scylladb.com/
Github claims no github pages here. 
###  Suggest a fix
If it still exists repoint the URL at the correct location.

**Comment by tzach** [comment]
Fixed by https://github.com/scylladb/scylladb/pull/17015 (once deployed)
