### ISSUE TITLE
test_select_from_mutation_fragments.py::test_slicing_rows fails due to missing result set

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#17031]
```
01:33:45  =================================== FAILURES ===================================
01:33:45  ______________________________ test_slicing_rows _______________________________
01:33:45  
01:33:45  cql = <cassandra.cluster.Session object at 0x7faaf5f0fc50>
01:33:45  test_table = 'cql_test_1706374473267.cql_test_1706374473388'
01:33:45  
01:33:45      def test_slicing_rows(cql, test_table):
01:33:45          """ Test that slicing rows from underlying works. """
...
01:33:45  >       check_slice(0, 0, 1)
01:33:45  
01:33:45  test/cql-pytest/test_select_from_mutation_fragments.py:343: 
...
01:33:45          expected_rows = [r for r in all_rows if r.ck1 == ck1 and r.ck2 >= ck2_start_inclusive and r.ck2 < ck2_end_exclusive]
01:33:45  >       assert res == expected_rows
01:33:45  E       assert [] == [Row(pk1=10, ...'{"v":"vv"}')]
01:33:45  E         Right contains one more item: Row(pk1=10, pk2=11, mutation_source='memtable:1', partition_region=2, ck1=0, ck2=0, position_weight=0, metadata='{"mar...e":true,"type":"regular","timestamp":1706374474340996}}}', mutation_fragment_kind='clustering row', value='{"v":"vv"}')
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6150/consoleFull

**Comment by denesb** [comment]
I looked at the logs and I got nowhere. The test tries to read specifically from the memtable, specifically from `memtable:0`, which will fail if the memtable is flushing or was flushed already by the time the read arrives.
The table this test uses is shared with other tests too, so tests can affect each other to some extent.

**Comment by denesb** [comment]
Alternatively, all tests which do not specifically want to test reads from memtable, can flush to disk and then read from sstables. For example this specific test, does not care which mutation-source the data is from. It is checking the correctness of hanlding of clustering-slices.

**Comment by avikivity** [comment]
Or just ignore the source of the mutation.

**Comment by denesb** [comment]
> Or just ignore the source of the mutation.

It is part of the clustering key, so if I want to test slicing, I cannot ignore it. In other cases I maybe can.
