### ISSUE TITLE
tablets: populate storage_group_vector elements sparsely

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#17042]
Currently, for every element of `storage_group_vector` we create a compaction group even if the corresponding tablet replica is on another shard or node. That can lead to an explosion of redundant allocations and force to manage an unnecessary large data structure for large tables/clusters. We should change that logic so that we only store the information that's relevant for a given shard.

This change should be implemented on top of https://github.com/scylladb/scylladb/pull/16918

**Comment by raphaelsc** [comment]
@ptrsmrn this is dup of https://github.com/scylladb/scylladb/issues/16877, that issue has good info on how to implement it, so if we'll keep only this one opened, we merge it into this one.
