### ISSUE TITLE
server starting function timed out on CQL connectivity check

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#17041]
Test `auth_cluster.test_password_login_message.debug` failed in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6170/ while adding 2 initial nodes. The testing framework's server start function timed out on the CQL connectivity check
```
E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/addservers, params: None, json: {'start': True, 'config': {'failure_detector_timeout_in_ms': 2000, 'authenticator': 'PasswordAuthenticator', 'authorizer': 'CassandraAuthorizer', 'permissions_validity_in_ms': 0, 'permissions_update_interval_in_ms': 0}, 'servers_num': 2}, body:
E               failed to start the node, timeout reached, server_id 19, IP 127.235.16.11, workdir scylla-19, host_id 90c6eece-22fa-4f7a-8025-51d641f161f6, cql [not connected]
E               Check the log files:
E               /scylladir/testlog/x86_64/test.py.debug-release-dev.log
E               /scylladir/testlog/x86_64/debug/scylla-19.log
```
even though the node correctly started:
```
INFO  2024-01-29 12:20:09,738 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on 127.235.16.11:19042 (unencrypted, shard-aware)
INFO  2024-01-29 12:20:09,738 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on 127.235.16.11:9042 (unencrypted, non-shard-aware)
INFO  2024-01-29 12:20:09,759 [shard 0:main] init - serving
INFO  2024-01-29 12:20:09,760 [shard 0:main] init - Scylla version 5.5.0~dev-0.20240129.869c2e9ab4e1 initialization completed.
```

Logs:
[auth_cluster.test_password_login_message.1.log](https://github.com/scylladb/scylladb/files/14085742/auth_cluster.test_password_login_message.1.log)
[scylla-18.log](https://github.com/scylladb/scylladb/files/14085746/scylla-18.log)
[scylla-19.log](https://github.com/scylladb/scylladb/files/14085748/scylla-19.log)

**Comment by kbr-scylla** [comment]
It's a weird failure, the server claims to have initialized, but the driver cannot connect apparently.
Maybe it is related to the configuration this test starts the servers with?
```python3
    config = {
        'failure_detector_timeout_in_ms': 2000,
        'authenticator': 'PasswordAuthenticator',
        'authorizer': 'CassandraAuthorizer',
        'permissions_validity_in_ms': 0,
        'permissions_update_interval_in_ms': 0,
    }

    servers = await manager.servers_add(2, config=config)
```

maybe it's related to authentication, the driver is stuck trying to authenticate perhaps?

**Comment by kbr-scylla** [comment]
cc @KrzaQ

**Comment by kbr-scylla** [comment]
The `cql_is_up` function in scylla_cluster.py lowers the driver's logging level for the function's duration, perhaps with it we would get some more info
```python3
    async def cql_is_up(self) -> CqlUpState:
        """Test that CQL is serving (a check we use at start up)."""
        caslog = logging.getLogger('cassandra')
        oldlevel = caslog.getEffectiveLevel()
        # Be quiet about connection failures.
        caslog.setLevel('CRITICAL')
```

**Comment by kbr-scylla** [comment]
Unfortunately couldn't reproduce after 100 runs in debug mode.

**Comment by ptrsmrn** [comment]
@nuivall will remove this testcase in https://github.com/scylladb/scylladb/pull/16578/files#diff-d1c566a12ba904e3cf20de29fdcf08d52be64b3e8b6b1bf6daff8b3a38b04d04, so I don't think we need to spend time investigating what exactly happened. If this issues pops up elsewhere, we can get back to it.

**Comment by kbr-scylla** [comment]
Ok, thanks.

I'd keep the issue opened during that time though, people will keep encountering it in CI and they need an issue to refer to.

**Comment by mykaul** [comment]
I wonder if this and https://github.com/scylladb/scylladb/issues/17298 are somehow related.

**Comment by nuivall** [comment]
this test was removed, we can revisit if it happens for other tests
