### ISSUE TITLE
commit log directory exceed the limit during disrupt_decommission_streaming_err nemesis

### ISSUE THREAD

**Issue by temichus** [scylladb/scylladb#17069]
## Packages

Scylla version: `5.5.0~dev-20240125.03313d359e32` with build-id `3ba319c2856389fd41198911105d86848352105e`

Kernel Version: `5.15.0-1054-azure`

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

SCT returns an error event 
```
error events from logs

2024-01-28 04:30:15.240: (CommitLogCheckErrorEvent Severity.ERROR) period_type=one-time event_id=84586574-645a-4cf2-9390-59da2dfdb8a5 during_nemesis=DecommissionStreamingErr: message=commit log directory exceed the limit. Prometheus response: [{'metric': {'__name__': 'scylla_commitlog_disk_total_bytes', 'instance': '10.0.0.6', 'job': 'scylla', 'shard': '0'}, 'values': [[1706415724.153, '54324629504'], [1706415725.153, '54324629504'], [1706415726.153, '54324629504'], [1706415727.153, '54324629504'], [1706415728.153, '54324629504'], [1706415729.153, '54324629504'], [1706415730.153, '54324629504'], [1706415731.153, '54324629504'], [1706415732.153, '54324629504'], [1706415733.153, '54324629504'], [1706415734.153, '54324629504'], [1706415735.153, '54324629504'], [1706415736.153, '54324629504'], [1706415737.153, '54324629504'], [1706415738.153, '54324629504'], [1706415739.153, '54324629504'], [1706415740.153, '54324629504'], [1706415741.153, '54324629504'], [1706415742.153, '54324629504'], [1706415743.153, '54324629504']]}]
```

and ended the commit log directory exceed the limit:
![image](https://github.com/scylladb/scylladb/assets/1948660/c9e1d5c0-7fef-432e-870d-2b06d3e1b9ff)

it is happened on node 10.0.0.6 (longevity-tls-1tb-7d-master-db-node-eastus-2) dirung ```disrupt_decommission_streaming_err``` nemesis

here are probably related logs in the DB
```
Jan 28 04:22:15.396779 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] gossip - No gossip backlog; proceeding
Jan 28 04:22:15.421958 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - entering JOINING mode
Jan 28 04:22:15.421970 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] init - starting system distributed keyspace
Jan 28 04:22:15.422193 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] system_distributed_keyspace - system_distributed(_everywhere) keyspaces and tables are up-to-date. Not creating
Jan 28 04:22:15.423770 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - Using saved tokens {9032469131516232887, 8999695680420888943, 8976643697586824843, 8767000023948637972, 8311945440292734439, 8166722538935102303, 8137042811352542273, 7924802141793886265, 7924495790116746744, 762456641924162962, 7483473247154159848, 7407022160155156025, 7375944706132688285, 7244439286044485093, 8424190774931965887, 7215687364557723213, 7210715516606127812, 6950122663154963456, 6903859902713321818, 6763956033558021140, 765267258304710627, 6760349312989490521, 6735703889114200491, 657250815917802923, 6256037610225121746, 8327547765529892307, 6274469215769264302, 6237529592319860544, 6138605946026551522, 5994492344617985572, 5463261908358653767, 5357033809859085367, 5332118891856930655, 6186609811788067823, 528085894295962548, 6240352563270514318, 5267613572483541310, 5211906096459032456, 7433013963734539341, 5170392947737090255, 5123902741227453675, 5056900544552214506, 4982938210860863614, 4819818626994443951, 5481564644548112246, 4499678538791031955, 443029577558725516, 442580438576449219, 4268816181980620196, 4181887828968372738, 3921660329769294078, 3856223263636792134, 3739185214796285892, 3724242228033244414, 6255232392045216260, 3169634767566266529, 3123279997467716106, 2999886987976272612, 3631646245512614561, 2998551448854482876, 2552413272047469964, 7761593709391224633, 2522757280787433749, 2399779202743533909, 2229556917895929665, 2085219074490044649, 1744871039235199417, 1576165879705206036, 8502538770556209976, 1509838648864879738, 1202693450978471247, 1145467000638444691, 7075199547079209163, 5163810626918192987, -231893154880300888, 9213004351347416300, -6901181735570444484, 7045753755311013041, -4013406170547773241, -3926305401166655772, -3740457048316868486, -3305100494172334699, -1407437619512570837, -6626235553883156549, -3953778883421172733, -2695455930012291864, 1141953374214551622, -5930089458868434977, 8891918465289461339, -7158223501599830445, 419047235250858261, -3104574463208004526, -2808158239862952606, -2146033003794274047, 4977502354633872150, -4222238256519711028, -4550351288050429477, -2749862029352200500, 8015459270710411050, 4613983886862459891, 34406979527660474, 3124318863696924798, -2734321352410563709, -2694160388086422447, -4820860162566446825, -2975737288810316911, -2662678894738691863, 7868992339520292414, -969369560428379435, -2601099600567711662, -2510945603089835694, 2752791119038024972, 1407079444354768417, -1942662041539640916, -2257384404862369320, 1756149028709900409, -5059269514579314300, -6059668884585245665, -126768590291082369, -4134477214501763308, -144771702922303770, -8804130882313146095, -2629404588555179282, 1389341281739436344, -117021626904424509, -3850475777176278778, -1422404645395666391, -3206358539302369001, -7008093662639312092, 6527406094812501357, -2997271255114082153, -4075541772563653057, -2377755365816148228, -8901827625090064486, 2238255651951403753, -4072197128655405652, -1722153256863880445, 7916766229458280139, -2589410079138667309, 7561625863187173191, -2466349421112364613, 7406355262479428269, -6559261203846291431, -6621763897442123420, -2942754935313406486, 2083474460154429784, -3605696434156820310, 6052011147079698542, 3974455644854318356, -2887850021010742757, -1911891519019435007, -1063505350166421543, 2195343009396647411, -4148962233908166206, -5292936784009070556, -5355950312127693079, 9127507852852292434, 5031037077747419729, -5903636958459354124, 3617293578706630506, -934244362259316666, 8690255605567757973, 1867036565385129970, -2575599918192171438, -2428088872281736978, 4567057943920874186, 368555649129423728, -8274190417363491819, -2461028937199726927, -2561486882371769453, -4796582642026280202, -1458290395882712699, -4474982919117184, -485663049349290255, -4987681798841506683, -1724407034966933410, -4998993394550796672, -5082173461617134492, 384749572086408554, 1305752244686795592, 1265542948717475918, -5186042421346424841, -5248207521428510259, 8198449165164541931, 4034654615929061959, 1547821377709386410, -9108084415633593895, -5379767692040762686, -5886614160457473564, -9164954992936034750, 2752603579970948129, -3254499789257865524, -6074345372984537590, 8532718605896780999, 1802356804549926629, -8805928290799897512, 8985848820839151755, -4235290942516389315, -4415964929531844682, -6442153000460986585, -9006473801740836848, -6552860709743266026, 8540225593165797325, 5603547257346941718, -656546517373916822, -6630683950746800041, -3412294914188292192, -7732778337855792712, -6738762193901744179, 2190459017836101499, -7236213362868511824, 9133192398221759916, -7282880841245559454, -4959515292420750768, -7369277217593039787, -7383573802424676941, -7603957138713991770, 4476637177494208393, -7998108474226555832, 2150492939178103599, -1985381516428633102, -7616598387246346628, -7744457330090116006, 5807927465357018506, -7809649310585885260, 8163278094238302629, -7880497274695097096, -7890240329630930496, -4654049916633789679, -8340764574248422222, -7963879692139136100, -1100135802270607797, -8033989206005043479, -4868227165593571028, -8044852491667232029, 7463833152910011136, 2274780094843211309, -8600976701639258308, -9101028759944833185, 5153791777089165803, -1769258028610672012, -1544856884331110586, -1431261194964447349, -8708304419155850770, 8665118728361265734, 4267715426935856497, 2841088952416738637, -3716730329430439986, -3874780633249711638, -1996628586191811800, -8834204959698891421, -4908207585259610868, -8868736427680177403, -9024308586844050750, -1889384281887814764, 1136666545929013352}
Jan 28 04:22:15.455908 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - Node 10.0.0.6 is in normal state, tokens: {1136666545929013352, -1889384281887814764, -9024308586844050750, -8868736427680177403, -4908207585259610868, -8834204959698891421, -1996628586191811800, -3874780633249711638, -3716730329430439986, 2841088952416738637, 4267715426935856497, 8665118728361265734, -8708304419155850770, -1431261194964447349, -1544856884331110586, -1769258028610672012, 5153791777089165803, -9101028759944833185, -8600976701639258308, 2274780094843211309, 7463833152910011136, -8044852491667232029, -4868227165593571028, -8033989206005043479, -1100135802270607797, -7963879692139136100, -8340764574248422222, -4654049916633789679, -7890240329630930496, -7880497274695097096, 8163278094238302629, -7809649310585885260, 5807927465357018506, -7744457330090116006, -7616598387246346628, -1985381516428633102, 2150492939178103599, -7998108474226555832, 4476637177494208393, -7603957138713991770, -7383573802424676941, -7369277217593039787, -4959515292420750768, -7282880841245559454, 9133192398221759916, -7236213362868511824, 2190459017836101499, -6738762193901744179, -7732778337855792712, -3412294914188292192, -6630683950746800041, -656546517373916822, 5603547257346941718, 8540225593165797325, -6552860709743266026, -9006473801740836848, -6442153000460986585, -4415964929531844682, -4235290942516389315, 8985848820839151755, -8805928290799897512, 1802356804549926629, 8532718605896780999, -6074345372984537590, -3254499789257865524, 2752603579970948129, -9164954992936034750, -5886614160457473564, -5379767692040762686, -9108084415633593895, 1547821377709386410, 4034654615929061959, 8198449165164541931, -5248207521428510259, -5186042421346424841, 1265542948717475918, 1305752244686795592, 384749572086408554, -5082173461617134492, -4998993394550796672, -1724407034966933410, -4987681798841506683, -485663049349290255, -4474982919117184, -1458290395882712699, -4796582642026280202, -2561486882371769453, -2461028937199726927, -8274190417363491819, 368555649129423728, 4567057943920874186, -2428088872281736978, -2575599918192171438, 1867036565385129970, 8690255605567757973, -934244362259316666, 3617293578706630506, -5903636958459354124, 5031037077747419729, 9127507852852292434, -5355950312127693079, -5292936784009070556, -4148962233908166206, 2195343009396647411, -1063505350166421543, -1911891519019435007, -2887850021010742757, 3974455644854318356, 6052011147079698542, -3605696434156820310, 2083474460154429784, -2942754935313406486, -6621763897442123420, -6559261203846291431, 7406355262479428269, -2466349421112364613, 7561625863187173191, -2589410079138667309, 7916766229458280139, -1722153256863880445, -4072197128655405652, 2238255651951403753, -8901827625090064486, -2377755365816148228, -4075541772563653057, -2997271255114082153, 6527406094812501357, -7008093662639312092, -3206358539302369001, 3739185214796285892, 3921660329769294078, 442580438576449219, 443029577558725516, 4819818626994443951, 9032469131516232887, 4181887828968372738, 2085219074490044649, -2694160388086422447, -4820860162566446825, 4982938210860863614, 5056900544552214506, 7375944706132688285, 5170392947737090255, 7433013963734539341, 2999886987976272612, 1145467000638444691, -4134477214501763308, 5463261908358653767, 5994492344617985572, 7407022160155156025, 7483473247154159848, 762456641924162962, 4268816181980620196, 5332118891856930655, 1576165879705206036, -2629404588555179282, 7924495790116746744, 8311945440292734439, 8137042811352542273, 6763956033558021140, -3305100494172334699, -1407437619512570837, -6626235553883156549, 8166722538935102303, 3856223263636792134, 8999695680420888943, 8976643697586824843, 2229556917895929665, 1202693450978471247, 6735703889114200491, 3123279997467716106, 6138605946026551522, 7210715516606127812, 5267613572483541310, 6240352563270514318, 6760349312989490521, 765267258304710627, 2552413272047469964, 5123902741227453675, 2399779202743533909, 8767000023948637972, -2975737288810316911, 657250815917802923, 3724242228033244414, 6186609811788067823, 528085894295962548, 6903859902713321818, 5357033809859085367, -2662678894738691863, 7868992339520292414, -969369560428379435, 7244439286044485093, 6950122663154963456, 8424190774931965887, 7215687364557723213, 5211906096459032456, 6256037610225121746, -2695455930012291864, 6255232392045216260, 3169634767566266529, -5930089458868434977, 1141953374214551622, 5481564644548112246, 4499678538791031955, 7924802141793886265, 6237529592319860544, 8327547765529892307, 6274469215769264302, 3631646245512614561, 2998551448854482876, 7761593709391224633, 2522757280787433749, -7158223501599830445, 8891918465289461339, 1744871039235199417, -2510945603089835694, 1509838648864879738, 8502538770556209976, -3953778883421172733, 7075199547079209163, 5163810626918192987, -231893154880300888, 9213004351347416300, -6901181735570444484, -117021626904424509, 1389341281739436344, 7045753755311013041, -4013406170547773241, -3926305401166655772, -3104574463208004526, 419047235250858261, -3740457048316868486, -2808158239862952606, -2146033003794274047, -4222238256519711028, 4977502354633872150, -4550351288050429477, -2749862029352200500, -2734321352410563709, 8015459270710411050, 34406979527660474, 3124318863696924798, 4613983886862459891, -2601099600567711662, 2752791119038024972, 1407079444354768417, -1942662041539640916, -2257384404862369320, 1756149028709900409, -5059269514579314300, -6059668884585245665, -126768590291082369, -144771702922303770, -8804130882313146095, -3850475777176278778, -1422404645395666391}
Jan 28 04:22:15.455996 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - handle_state_normal: node 10.0.0.6/b71a8340-6e2a-496f-8c85-9caeca9aeb7b was already a normal token owner
Jan 28 04:22:15.456002 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - Host ID b71a8340-6e2a-496f-8c85-9caeca9aeb7b continues to be owned by 10.0.0.6
Jan 28 04:22:15.456114 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - handle_state_normal: endpoint=10.0.0.6 == current_owner=10.0.0.6 token 1136666545929013352
Jan 28 04:22:15.456119 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - handle_state_normal: endpoint=10.0.0.6 == current_owner=10.0.0.6 token -1889384281887814764
Jan 28 04:22:15.456123 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - handle_state_normal: endpoint=10.0.0.6 == current_owner=10.0.0.6 token -9024308586844050750
Jan 28 04:22:15.456127 longevity-tls-1tb-7d-master-db-node-eastus-2 scylla[860]:  [shard  0:strm] storage_service - handle_state_normal: endpoint=10.0.0.6 == current_owner=10.0.0.6 token -8868736427680177403
```

## How frequently does it reproduce?

now seen only once 

## Installation details

Cluster size: 4 nodes (Standard_L16s_v3)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-master-db-node-ad15d2c8-eastus-5 (172.203.229.93 | 10.0.0.14) (shards: -1)
- longevity-tls-1tb-7d-master-db-node-ad15d2c8-eastus-4 (74.235.109.31 | 10.0.0.8) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-ad15d2c8-eastus-3 (74.235.108.44 | 10.0.0.7) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-ad15d2c8-eastus-2 (74.235.108.34 | 10.0.0.6) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-ad15d2c8-eastus-1 (172.203.237.168 | 10.0.0.5) (shards: 14)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-5.5.0-dev-x86_64-2024-01-26T02-45-34` (azure: undefined_region)

Test: `longevity-1tb-5days-azure-test`
Test id: `ad15d2c8-7616-4c3a-b222-524d3da4f085`
Test name: `scylla-master/longevity/longevity-1tb-5days-azure-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cf79ff757eb5b3431035e688ede85c4ea1dae417/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ad15d2c8-7616-4c3a-b222-524d3da4f085`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ad15d2c8-7616-4c3a-b222-524d3da4f085)
- Show all stored logs command: `$ hydra investigate show-logs ad15d2c8-7616-4c3a-b222-524d3da4f085`

## Logs:
- **db-cluster-ad15d2c8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/db-cluster-ad15d2c8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/db-cluster-ad15d2c8.tar.gz)
- **sct-runner-events-ad15d2c8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/sct-runner-events-ad15d2c8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/sct-runner-events-ad15d2c8.tar.gz)
- **sct-ad15d2c8.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/sct-ad15d2c8.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/sct-ad15d2c8.log.tar.gz)
- **loader-set-ad15d2c8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/loader-set-ad15d2c8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/loader-set-ad15d2c8.tar.gz)
- **monitor-set-ad15d2c8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/monitor-set-ad15d2c8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad15d2c8-7616-4c3a-b222-524d3da4f085/20240128_071952/monitor-set-ad15d2c8.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-1tb-5days-azure-test/35/)
[Argus](https://argus.scylladb.com/test/d03f9d55-942a-4f66-ae48-9d35d59a59e2/runs?additionalRuns[]=ad15d2c8-7616-4c3a-b222-524d3da4f085)
</details>

**Comment by mykaul** [comment]
What was the limit that was set? What was the impact, besides exceeding the limit?

**Comment by elcallio** [comment]
Second that question. What was the limit set, what was the configured segment size, and what was the measured disk footprint (also, measured or derived from scylla counters?). 
Remember that CL footprint is allowed to exceed the set size/<n shards> by one segment size per shard. This because configured size, segment size and number of shards might not add up/align. Thus a little salt should be ingested with measuring actual footprint.

**Comment by temichus** [comment]
@mykaul , @elcallio 

this check was implementes by @eliransin request:
```
The commitlog didn't go over the size limit. It is a little more involved, we should make sure that the size of the commitlog directory never exceeds the limit, we can't rely on metrics since if there is a bug in the metrics we will never catch an actual bug where the directory is larger than the stats and the size limit was actually breached.
```
regarding your questions:
1)no observed impact, all no other errors in the test

2) limit set as ```commitlog_total_space + 1 segment```

 ```scylla_commitlog_disk_total_bytes>=({commitlog_total_space+({commitlog_segment_size_in_mb}*1048576))"```
```
{commitlog_total_space} :
        set to max_disk_size(value from API) divided  to number for shards
        
        
+ {commitlog_segment_size_in_mb}*1048576) :
        add size of 1 segment,  Scylla actually stops creating new segments not when the next segment
        would cause us to exceed the value,
        but instead it checks if we've already reached or exceeded the limit.
        
  scylla_commitlog_disk_total_bytes >= :
        filter all good values when scylla_commitlog_disk_total_bytes<= commitlog_total_space + 1 segment
        and return from Prometheus only bad
```        
  from logs limit is : 8914993152+(32*1048576) = 8948547584 but got 54324629504  (x6 times bigger)
  ```
  Query to PrometheusDB: http://10.0.0.13:9090/api/v1/query_range?query=scylla_commitlog_disk_total_bytes>=(8914993152%2B(32%2A1048576))&start=1706425203.152964&end=1706425803.152964&step=1
  ```
  
  bur returner it only anes. and from graphs you can see that it returned only ones in ano moment
  
  Ony querying MAX value shows the problem:
  
![image](https://github.com/scylladb/scylladb/assets/1948660/7163fb09-e900-4d9e-8ef9-8548fbe700b0)

 if querying AVG value it does even not show the problem 
 
![image](https://github.com/scylladb/scylladb/assets/1948660/ec0ada2d-d77b-4198-b7bd-6633e38feb32)

**Comment by elcallio** [comment]
> 2\. limit set as `commitlog_total_space + 1 segment`

Where does this value come from? What does scylla.yaml say here?

Your example above says the expected value is about 8GB, and the offending one is ~56GB? 8 sounds very low for the type of machines we typically use...

**Comment by temichus** [comment]
@elcallio 

in yaml: commitlog_total_space_in_mb: -1

node has :
max_disk_size(from API commitlog/metrics/max_disk_size) = 124809904128
and 14 shards (from seastar-cpu-map.sh)

**commitlog_total_space is max_disk_size divided by the number of shards**

Calculated values commit log checking thread:
```
< t:2024-01-27 05:00:03,125 f:commit_log_check_thread.py l:37   c:CommitlogConfigParams p:DEBUG > CommitlogConfigParams
< t:2024-01-27 05:00:03,125 f:commit_log_check_thread.py l:38   c:CommitlogConfigParams p:DEBUG > smp: 14
< t:2024-01-27 05:00:03,125 f:commit_log_check_thread.py l:39   c:CommitlogConfigParams p:DEBUG > max_disk_size: 124809904128
< t:2024-01-27 05:00:03,125 f:commit_log_check_thread.py l:40   c:CommitlogConfigParams p:DEBUG > total_space: 8914993152
< t:2024-01-27 05:00:03,125 f:commit_log_check_thread.py l:41   c:CommitlogConfigParams p:DEBUG > use_hard_size_limit: True
< t:2024-01-27 05:00:03,125 f:commit_log_check_thread.py l:42   c:CommitlogConfigParams p:DEBUG > segment_size_in_mb: 32
```

**Comment by elcallio** [comment]
How much memory on the node? 128GB? 
128GB max size matches this, and at 14 shards, 9GB limit per shard. 
The 8 expected / 56 actual above, is this a shard-local measurement?
And this is all based on metrics, right? Did you get an actual measurement of the commitlog dir size as well?

If I read the metrics screenshot above correctly, the spike is at 05.22, which is 04.22 in the logs. At that time, the node was restarting from a crash, and replayed more or less the full set of logs from previous run. This is all done on shard 0. After this, the replayed segments are all added to shard zero commitlog for either re-use or delete. For a few moments, they will regardless count into the shards disk footprint, until we can determine if they are to be deleted or not. Hence the spike. 

Unless I am mistaken here, there is no bug, just the fact that during replay-boot, we don't adhere to the limits fully, esp. not on shard 0.

**Comment by temichus** [comment]
RAM (MiB) 131072 

is this a shard-local measurement - yes

as I mentioned, I **can see any observed impact**, all nemesis/stress commands passed,  no other errors in the test


and this check was implemented by @eliransin request to catch possible errors.

From my understanding as well , a **Hard limit** means that it can not exceed the limit

**Comment by elcallio** [comment]
It can, during/after replay. For a short bit.

**Comment by temichus** [comment]
I this case I can set up gate for this. But how short?  30sec, 1min, 5min. in this issue, I see 19sec

**Comment by temichus** [comment]
will set 1min them, there is fix proposal https://github.com/scylladb/scylla-cluster-tests/pull/7176

**Comment by kostja** [comment]
> Should be very short, but what you actually see here will also depend very much on the frequency of metrics polling, and any stalls there. Actual deletion of excess files + reduction of the counters will happen with relatively low prio vs. the other startup stuff happening here, i.e. compaction etc will starve it. I would go for a minute or so (excessive) after reply is finished.

Calle, asking the test for "going for a minute or so" is bad UX, we'll get a flaky test. Can we program a barrier so that even during startup there is a cap (be either time limit, or size limit) on the growth of the commit log.

Another concern is that some clients may perceive this growth as a hard limit (the name says so - a hard limit), so may run out of disk space in these circumstances.

WDYT?

**Comment by elcallio** [comment]
No one is "asking" tests to wait. But this is an artificial problem caused by over trusting/misusing metrics to measure an (in this instance) unrelated value. 
The disk foot print is not "growing" here. The files in question exist on disk, regardless. They are picked up, played back and discarded. Note that the actual size/amount of segments replayed might not be even remotely related to the current sharding/foot print limits. Should these files then be ignored when considering how much footprint we are currently consuming? To what end? Make counters look "better" for this particular test case (this has zero impact on anything real). 
The main confusion comes from the full set of segments from previous run being added to shard zero. 
The test could probably get by also by just looking at full footprint across all shards, which should be within limits (maybe + one segment extra per shard) until deletion/recycling is done. 
This also applies to a customer: We will _not_ start using up any significant real additional disk space before replay + deletion of old stuff is done. 
And again: the counters are correct (from a certain point of view). It is the tests assumptions that are wrong. Non-clean restart is a very special case.

**Comment by kostja** [comment]
The test is fixed. Too bad the hard limit is not hard, @elcallio
