### ISSUE TITLE
raft topology: send barrier to a decommissioning node

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#17108]
#16797 fixed the case when a decommissioning node sends a request with stale topology version which causes stale topology exceptions on replicas. However, it is still possible that a decommissioning node incorrectly accepts a request with stale topology version. If `barrier_and_drain` fails, we won't include the decommissioning node in the following barrier:

```cpp
future<group0_guard> global_token_metadata_barrier(group0_guard&& guard, std::unordered_set<raft::server_id> 
    ...
    if (drain_failed) {
        // if drain failed need to wait for fence to be active on all nodes
        co_return co_await exec_global_command(std::move(guard), raft_topology_cmd::command::barrier, exclude_nodes, drop_guard_and_retake::yes);
    }
    ...
}
```

We should also send `barrier` to a decommissioning node.

**Comment by kbr-scylla** [comment]
There was a discussion between @patjed41 and @tgrabiec about this somewhere, but I cannot find it.

**Comment by patjed41** [comment]
https://github.com/scylladb/scylladb/commit/543ad0987a18ebf9d09dc36eb0a0c63aa26def18#r137856902

**Comment by patjed41** [comment]
> What problem it may cause in practice?

I remember that me and @kbr-scylla discussed it and concluded that we don't really know what problems it may cause in practice. So we left it as a theoretical issue to investigate it later or at least to not forget about it. I don't know why this issue was moved to "required" though.

**Comment by tgrabiec** [comment]
> What problem it may cause in practice?

Writes which should be fenced at replica side will not be fenced, since decommissioned node is not included in fence rpc. Which makes fencing ineffective for that replica. It can cause problems which fencing is supposed to protect from, e.g. write request from stale coordinator may succeed when it shouldn't, leading to loss of that write.

**Comment by gleb-cloudius** [comment]
> > What problem it may cause in practice?
> 
> Writes which should be fenced at replica side will not be fenced, since decommissioned node is not included in fence rpc. Which makes fencing ineffective for that replica. It can cause problems which fencing is supposed to protect from, e.g. write request from stale coordinator may succeed when it shouldn't, leading to loss of that write.

Fencing does not prevent writes that should not succeed from succeeding. We have draining before fencing so all such writes should complete before the fence is advanced. The fence is there to prevent dirty data to get to the node. But since the node is decommissioned anyway who cares.

The only problem I see is that the node that is being decommissioned has to drain all requests it coordinates when it enters decommissioning state and stop coordinating new requests after that.

**Comment by tgrabiec** [comment]
> We have draining before fencing so all such writes should complete before the fence is advanced

The code in global_token_metadata_barrier() allows drain to fail:
```
        try {
            guard = co_await exec_global_command(std::move(guard), raft_topology_cmd::command::barrier_and_drain, exclude_nodes, drop_guard_and_retake::yes);
        } catch (...) {
            rtlogger.error("drain rpc failed, proceed to fence old writes: {}", std::current_exception());
            drain_failed = true;
        }
```

and barrier relies on fencing then:
```
        if (drain_failed) {
            // if drain failed need to wait for fence to be active on all nodes
            co_return co_await exec_global_command(std::move(guard), raft_topology_cmd::command::barrier, exclude_nodes, drop_guard_and_retake::yes);
```

so barrier does not guarantee that coordinators are drained.

**Comment by kbr-scylla** [comment]
> I remember that me and @kbr-scylla discussed it and concluded that we don't really know what problems it may cause in practice. So we left it as a theoretical issue to investigate it later or at least to not forget about it. I don't know why this issue was moved to "required" though.

Meh. Moved to optional/post-release. Although it's probably a single-line change.

**Comment by tgrabiec** [comment]
> > I remember that me and @kbr-scylla discussed it and concluded that we don't really know what problems it may cause in practice. So we left it as a theoretical issue to investigate it later or at least to not forget about it. I don't know why this issue was moved to "required" though.
> 
> Meh. Moved to optional/post-release. Although it's probably a single-line change.

Even though https://github.com/scylladb/scylladb/issues/17108#issuecomment-2095640289?
