### ISSUE TITLE
test_tablets.py::test_tablet_missing_data_repair fails due to `NoHostAvailable`

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#17107]
```
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.157.135.26:9042 datacenter1>: ConnectionException('Pool for 127.157.135.26:9042 is shutdown')})
...
    @pytest.mark.repair
    @pytest.mark.asyncio
    async def test_tablet_missing_data_repair(manager: ManagerClient):
...
        for idx in range(0,3):
            s = servers[idx].server_id
            await manager.server_stop_gracefully(s, timeout=120)
>           await check()

test/topology_experimental_raft/test_tablets.py:482: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    async def check():
        logger.info("Checking table")
        query = SimpleStatement("SELECT * FROM test.test;", consistency_level=ConsistencyLevel.ONE)
>       rows = await cql.run_async(query)
E       cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.157.135.26:9042 datacenter1>: ConnectionException('Pool for 127.157.135.26:9042 is shutdown')})

```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6229/

[scylla-1370.log](https://github.com/scylladb/scylladb/files/14125397/scylla-1370.log)
[topology_experimental_raft.test_tablets.4.log](https://github.com/scylladb/scylladb/files/14125398/topology_experimental_raft.test_tablets.4.log)

**Comment by tchaikov** [comment]
the test failure happened after the fix of #16859 got merged. so this is a new one.

**Comment by raphaelsc** [comment]
It may be a gossip delay issue, inspection of logs would reveal it

If so, we need this patch:

```
diff --git a/test/topology_experimental_raft/test_tablets.py b/test/topology_experimental_raft/test_tablets.py
index cada60f14b..3529e59b4a 100644
--- a/test/topology_experimental_raft/test_tablets.py
+++ b/test/topology_experimental_raft/test_tablets.py
@@ -479,6 +479,7 @@ async def test_tablet_missing_data_repair(manager: ManagerClient):
     for idx in range(0,3):
         s = servers[idx].server_id
         await manager.server_stop_gracefully(s, timeout=120)
+        await manager.servers_see_each_other(servers)
         await check()
         await manager.server_start(s)
```

**Comment by mykaul** [comment]
Again we need to add ```servers_see_each_other()``` (albeit in a different flow). I wonder what changed recently.

**Comment by raphaelsc** [comment]
> Again we need to add `servers_see_each_other()` (albeit in a different flow). I wonder what changed recently.

It's very time sensitive. The factor could be environment itself, which may invoke coordinator faster before gossip propagated added / removed nodes to it. Maybe, for the long run, all test functions adding / removing servers should be safe by default, meaning they only return once all nodes see each other. Tests that don't need it would be explicit about it. /cc @kostja.

**Comment by raphaelsc** [comment]
> > Again we need to add `servers_see_each_other()` (albeit in a different flow). I wonder what changed recently.
> 
> It's very time sensitive. The factor could be environment itself, which may invoke coordinator faster before gossip propagated added / removed nodes to it. Maybe, for the long run, all test functions adding / removing servers should be safe by default, meaning they only return once all nodes see each other. Tests that don't need it would be explicit about it. /cc @kostja.

relevant discussion: https://github.com/scylladb/scylladb/pull/17040

**Comment by Annamikhlin** [comment]
seen on https://jenkins.scylladb.com/job/scylla-master/job/next/7202/testReport/junit/(root)/test_tablets/Build___aarch64___Unit_Tests_aarch64___test_tablet_missing_data_repair/
