### ISSUE TITLE
Not able to add new node to a existing 3 node cluster

### ISSUE THREAD

**Issue by rohitraj-carousellgroup** [scylladb/scylladb#17122]
*Installation details*
Scylla version (or git commit hash): 5.2.9-0.20230920.5709d0043978-1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian

**Description**
We have currently 3 node scylla cluster. We are trying to add 1 new scylla node to the cluster. But we are facing issue while adding new scylla node to the cluster

Logs for node 4 which we are trying to add
`Feb 02 07:55:03 scylla-data-04 scylla[85175]:  [shard 0] compaction - [Compact system.scylla_local 5f3570d0-c1a0-11ee-873b-317629ea6125] Compacted 5 sstables to [/mnt/disks/scylla/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-1732-big-Data.db:level=0]. 253kB to 90kB (~35% of original) in 30ms = 8MB/s. ~640 total partitions merged to 2.
Feb 02 07:55:03 scylla-data-04 scylla[85175]:  [shard 0] compaction - [Compact system_schema.columns 5f3b8b50-c1a0-11ee-873b-317629ea6125] Compacting [/mnt/disks/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-68-big-Data.db:level=0:origin=memtable,/mnt/disks/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-64-big-Data.db:level=0:origin=compaction]
Feb 02 07:55:03 scylla-data-04 scylla[85175]:  [shard 0] compaction - [Compact system_schema.columns 5f3b8b50-c1a0-11ee-873b-317629ea6125] Compacted 2 sstables to [/mnt/disks/scylla/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-72-big-Data.db:level=0]. 122kB to 61kB (~50% of original) in 34ms = 3MB/s. ~256 total partitions merged to 10.
Feb 02 07:55:03 scylla-data-04 scylla[85175]:  [shard 0] compaction - [Compact system.scylla_local 5f41f3f0-c1a0-11ee-873b-317629ea6125] Compacting [/mnt/disks/scylla/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-1724-big-Data.db:level=0:origin=compaction,/mnt/disks/scylla/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-1732-big-Data.db:level=0:origin=compaction]
Feb 02 07:55:03 scylla-data-04 scylla[85175]:  [shard 0] compaction - [Compact system.scylla_local 5f41f3f0-c1a0-11ee-873b-317629ea6125] Compacted 2 sstables to [/mnt/disks/scylla/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/me-1736-big-Data.db:level=0]. 131kB to 90kB (~68% of original) in 32ms = 4MB/s. ~256 total partitions merged to 2.
Feb 02 07:55:04 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:05 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:06 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:07 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:08 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:09 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:10 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:11 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:12 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:13 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:14 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:15 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete
Feb 02 07:55:16 scylla-data-04 scylla[85175]:  [shard 0] storage_service - waiting for schema information to complete`

Logs for node 1
`Feb 02 07:54:48 scylla-data-01 scylla[2049742]:  [shard 0] raft_group_registry - marking Raft server 555735d1-9ede-4b5c-b100-c2bffb8cafc2 as alive for raft groups
Feb 02 07:54:49 scylla-data-01 scylla[2049742]:  [shard 0] gossip - InetAddress 10.240.2.199 is now UP, status = UNKNOWN`

**Comment by mykaul** [comment]
@kbr-scylla - is that related to Raft?

**Comment by kbr-scylla** [comment]
No idea.
Please provide full log from node4 as a file.

**Comment by mykaul** [comment]
@rohitraj-carousellgroup - can you please add logs?

**Comment by rohitraj-carousellgroup** [comment]
I will share logs shortly.

**Comment by rohitraj-carousellgroup** [comment]
I am sharing the logs for node-4
[logfile.txt](https://github.com/scylladb/scylladb/files/14460948/logfile.txt)

**Comment by rohitraj-carousellgroup** [comment]
We need one more help
We are able to add the cluster in our scylla db after upgradation
Scylla Version : 5.2.15
Currently our setup has 7 nodes
3 nodes in rack a
3 nodes in rack b
1 node in rack c
Replication Factor : 3
We want to do decommission the node which is currently in rack-c
While running nodetool decommission command in rack-c, we are getting this error
```
Apr 22 14:19:02 scylla-data-03 scylla[381072]:  [shard 0] storage_service - stream_ranges successful
Apr 22 14:19:02 scylla-data-03 scylla[381072]:  [shard 0] storage_service - DECOMMISSIONING: unbootstrap done
Apr 22 14:19:02 scylla-data-03 scylla[381072]:  [shard 0] storage_service - decommission[a581af49-0d71-4a74-8e88-5d17d6238053]: becoming a group 0 non-voter
Apr 22 14:19:02 scylla-data-03 scylla[381072]:  [shard 0] raft_group0 - becoming a non-voter (my id = 5dff8f6d-6761-46b6-b209-76ec17acb5cf)...
Apr 22 14:19:02 scylla-data-03 scylla[381072]:  [shard 0] storage_service - decommission[a581af49-0d71-4a74-8e88-5d17d6238053]: Operation failed, sync_nodes={10.240.2.82, 10.240.2.93, 10.240.2.84, 10.240.2.172, 10.240.100.0, 10.240.2.87, 10.240.100.2}: std::invalid_argument (The configuration must have at least one voter)
Apr 22 14:19:02 scylla-data-03 scylla[381072]:  [shard 0] storage_service - decommission[a581af49-0d71-4a74-8e88-5d17d6238053]: Stopped heartbeat_updater
Apr 22 14:19:02 scylla-data-03 scylla[381072]:  [shard 0] storage_service - decommission[a581af49-0d71-4a74-8e88-5d17d6238053]: Started decommission_abort[a581af49-0d71-4a74-8e88-5d17d6238053]: ignore_nodes=[], leaving_nodes=[10.240.100.2], replace_nodes={}, bootstrap_nodes={}, repair_tables=[]
```

**Comment by kbr-scylla** [comment]
@rohitraj-carousellgroup please provide the output of
```
select * from system.raft_state
```

executed on every node in the cluster

**Comment by rohitraj-carousellgroup** [comment]
node 1
 group_id                             | disposition | server_id                            | can_vote
--------------------------------------+-------------+--------------------------------------+----------
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | 555735d1-9ede-4b5c-b100-c2bffb8cafc2 |    False
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | 724cc1e2-b777-4d06-94de-83766e27cb19 |     True
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | a6181654-0163-44f6-ad07-74d87b80a828 |     True
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | af5a7f50-f74d-4467-a141-d8f5d46eca6f |     True

node 2
 group_id                             | disposition | server_id                            | can_vote
--------------------------------------+-------------+--------------------------------------+----------
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 1525fe2c-73b6-4809-8489-e66eb2919628 |     True
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 7a57bec2-e2e8-4172-9a40-7b9ac5d9b64e |     True
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 985d1aa2-71bc-4592-aef6-ec65cb21ff7f |     True

node 3
 group_id                             | disposition | server_id                            | can_vote
--------------------------------------+-------------+--------------------------------------+----------
 130367f0-1b09-11ee-9994-f71da009916d |     CURRENT | 5dff8f6d-6761-46b6-b209-76ec17acb5cf |     True

node 4
 group_id                             | disposition | server_id                            | can_vote
--------------------------------------+-------------+--------------------------------------+----------
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | 555735d1-9ede-4b5c-b100-c2bffb8cafc2 |    False
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | 724cc1e2-b777-4d06-94de-83766e27cb19 |     True
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | a6181654-0163-44f6-ad07-74d87b80a828 |     True
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | af5a7f50-f74d-4467-a141-d8f5d46eca6f |     True

node 5
 group_id                             | disposition | server_id                            | can_vote
--------------------------------------+-------------+--------------------------------------+----------
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | 555735d1-9ede-4b5c-b100-c2bffb8cafc2 |    False
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | 724cc1e2-b777-4d06-94de-83766e27cb19 |     True
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | a6181654-0163-44f6-ad07-74d87b80a828 |     True
 12d18280-1b09-11ee-a25b-3b6836c2eadb |     CURRENT | af5a7f50-f74d-4467-a141-d8f5d46eca6f |     True

node 6
 group_id                             | disposition | server_id                            | can_vote
--------------------------------------+-------------+--------------------------------------+----------
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 1525fe2c-73b6-4809-8489-e66eb2919628 |     True
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 7a57bec2-e2e8-4172-9a40-7b9ac5d9b64e |     True
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 985d1aa2-71bc-4592-aef6-ec65cb21ff7f |     True

node 7
 group_id                             | disposition | server_id                            | can_vote
--------------------------------------+-------------+--------------------------------------+----------
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 1525fe2c-73b6-4809-8489-e66eb2919628 |     True
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 7a57bec2-e2e8-4172-9a40-7b9ac5d9b64e |     True
 12e88cf0-1b09-11ee-95b1-29c55cddcfff |     CURRENT | 985d1aa2-71bc-4592-aef6-ec65cb21ff7f |     True
 
 We are trying to decommission node 3

**Comment by kbr-scylla** [comment]
@rohitraj-carousellgroup you've got 3 separate clusters in there, connected into one. You can see that by `group_id`, 3 different values are appearing there. There should be only one `group_id` in correctly setup cluster.

I suspect you bootstrapped the nodes using incorrect `seeds` configuration such that the nodes formed 3 independent clusters (perhaps separate cluster in each rack?). Then you restarted the nodes with different `seeds` configuration so that the nodes started gossiping with each other... and now you have this weird configuration with 3 different clusters pretending to be one :)

When bootstrapping nodes make sure to follow the correct documented procedure.

Similar to https://github.com/scylladb/scylladb/issues/14446

Anyway, the only way I currently see to fix your cluster is to perform the manual Raft recovery procedure: https://opensource.docs.scylladb.com/branch-5.2/architecture/raft.html#raft-manual-recovery-procedure

**Comment by rohitraj-carousellgroup** [comment]
@kbr-scylla , what will be the safest way,
1) should we create a fresh cluster, dump the data and switch the traffic
2) should we perform manual raft recovery procedure and it will not effect live read/write queries in scylla db.

**Comment by kbr-scylla** [comment]
Manual Raft recovery procedure will not affect availability of queries, assuming that:
- you're using RF >= 3
- you're using CL <= QUORUM
- you never shutdown more than 1 replica at a time (so all your restarts should be rolling restarts)

Usually the procedure is performed when you have a dead node, and you have to shutdown other nodes too so you have 2 nodes down at a time. But in your case there are no dead nodes so you will only have 1 node down at a time if you do rolling restarts.
