### ISSUE TITLE
Can we use tombstone_gc = {'mode': 'repair'} for GSI tables?

### ISSUE THREAD

**Issue by xxuvincent** [scylladb/scylladb#17142]
I have two questions here about tombstone_gc = {'mode': 'repair'} for GSI tables.

1. I am not sure whether tombstone_gc = {'mode': 'repair'} is supported for GSI tables or not.
2. How can I ensure that the tombstone_gc mode has been changed for GSI tables? I've noticed that #10309 provides a method to check the tombstone_gc mode for base table. But it might not be useful for GSI tables.

**Comment by nyh** [comment]
This is an issue tracker, for tracking bugs and requests for enhancement in the ScyllaDB code and/or documentation - not a place for questions and discussions. The project has several other venues for such questions and discussions, such as the mailing list https://groups.google.com/g/scylladb-dev and the forum https://forum.scylladb.com/.

If while discussing this issue you come across an actual bug (something that can't be done, or works incorrectly, or poorly, or something which you know can be done but is documented poorly) then please do create an issue about that and explain exactly what is broken or missing.
