### ISSUE TITLE
Relabel metrics occur unexpected reault when set replacement for column_family metrics

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylladb#17158]
When I tests the example  as following :
```  
$ cat conf.yaml 
relabel_configs:
  - source_labels: [shard]
    action: drop 
    target_label: shard 
    regex: (2)
  - source_labels: [shard]
    action: replace
    target_label: level 
    replacement: $1
    regex: (.*3)

```

It works expected for all non-column-family metrics, results in drop record if label match regex "2" and replace label 'shard' with 'level' if match regex ".*3", but unexpected in column_family that it add an record while there is no label after node aggregated.

And my config for scylla is 
``` 
./build/dev/scylla \
--commitlog-sync-period-in-ms 10 \
--developer-mode=1 \
--workdir /fdb-storage/scylla \
--network-stack posix \
--overprovisioned \
--alternator-port 18008 \
--alternator-write-consistency-level QUORUM \
--alternator-write-isolation always_use_lwt \
--blocked-reactor-notify-ms 999999999 \
--native-transport-port 19049 \
--native-shard-aware-transport-port 29049  \
--prometheus-addr 0.0.0.0 \
--prometheus-port 9199 \
--api-port 3005 --storage-port 7005 \
--ring-delay-ms 60000 \
--smp 5 --memory=10G \
--relabel-config-file conf.yaml
```

**Comment by qiuqiu-007** [comment]
Here is the result : 
![result](https://github.com/scylladb/scylladb/assets/143240433/1b0dcf59-b809-4fb9-b8f9-dae00e891d76)

**Comment by mykaul** [comment]
@amnonh - please take a look.

**Comment by amnonh** [comment]
This is not a bug; what happens here is that there are two actions. First, you drop a metric and add a label to one specific metric instance (as described).
Then you aggregate over shard (e.g., drop the shard label). The end result after dropping the shard is two metrics, one with the level label and one without.

Because all values are zero, you cannot tell the difference if you repeat it with the actual value; it will be easier to see.

**Comment by qiuqiu-007** [comment]
In my opinion, this should not be exported, cause it has been aggregated, then no label named "shard" in column-family metrics. If there is not a label match "shard", this label "level" should not be added to this metric, not even adds a record. @amnonh

**Comment by qiuqiu-007** [comment]
In scylla 5.4 metrics are set to be aggregated by default, so it is already aggregated before I set relabel config. So in this way, when it should not match the label "shard", cause there's no "shard" label in node-aggregated column family metrics, then label "level" should not be add. @amnonh

**Comment by amnonh** [comment]
This is not how filtering and aggregation works.
Filtering and relabel works at the metrics registration time.
Aggregation works at the reporting time. The scenario you've described works as expected.

**Comment by qiuqiu-007** [comment]
> This is not how filtering and aggregation works. Filtering and relabel works at the metrics registration time. Aggregation works at the reporting time. The scenario you've described works as expected.

I see. Thanks a lot !
