### ISSUE TITLE
Block tablet draining when tablet load balancing is disabled by user's requets

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#17173]
There is a RESTful API to disable tablet migration (calls `storage_service::set_tablet_balancing_enabled`), the toggle is stored in group0. Currently, this affects only load balancing migrations but not draining on decommission/removenode/replace. There are plans to use this toggle to provide stability of the ring information (describering RESTful API and system.token_ring), so we should refuse to perform migrations also during drain.

There are two options: fail node operations which depend on draining, or block them. Failing is potentially disruptive to node operations, and blocking has potential for deadlock. Example of deadlock: Admin1: disable migrations, Admin2: start decommission, waits for migrations to be enabled, Admin1: perform topology operation, which waits for decommission to yield the state machine. The move_tablet() API won't be blocked by decommission after https://github.com/scylladb/scylladb/issues/16437, so it won't cause deadlocks. I don't see why admin would want to perform other topology operations under disabled migrations, so we can go with blocking and document that admin should not perform any topology operations except tablet movement under migrations disabled. 

Migration can be disabled during decommission, in which case we can either: (1) fail the request to disable migrations, (2) let decommission which may be in progress to fail, or (3) block the request until decommission is finished. The most gentle option is option (3), which the API already implements, and it shouldn't suffer from deadlock issues.

\cc @bhalevy @denesb @avikivity

**Comment by bhalevy** [comment]
I vote for failing draining since the cause is due to an admin operation, rather than an automatic process that we know it would end in a timely manner.

**Comment by bhalevy** [comment]
@tgrabiec did you start working on this?
If not, @tchaikov can own it in conjunction with #16437

**Comment by tgrabiec** [comment]
> @tgrabiec did you start working on this? 

No

> If not, @tchaikov can own it in conjunction with #16437

Sounds good.

**Comment by bhalevy** [comment]
> > I vote for failing draining since the cause is due to an admin operation, rather than an automatic process that we know it would end in a timely manner.
> 
> That depends on which systems will call this disabling. If it will be called by a process in the cloud which is independent of topology operations then it could cause disruptions.
> 
> What's the downside of blocking? It seems safer in that regard.

The downside is that the request may block indefinitely.
For example, if the admin disabled migrations due to some reason, like they forgot about it, or maybe there was a bug and disabling migrations was needed as a workaround.
We can have a --force flag to bypass this check.

**Comment by bhalevy** [comment]
@avikivity said on today's call that this wouldn't be needed as the admin should just avoid topology changes if they want the tablets map / describring results to be stable.

**Comment by bhalevy** [comment]
Let's close then, and reopen if we convince ourselves this is required.

**Comment by tchaikov** [comment]
thanks Benny!
