### ISSUE TITLE
docs: remove SSTable2json from the docs?

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#17204]
https://opensource.docs.scylladb.com/master/operating-scylla/admin-tools/sstable2json

Arguments for removing:

- SSTable2json supported when using Scylla 2.x or lower version (and we're going to release 6.0!)
- It is not recommended to use this tool in the production cluster. 

@tzach What do you think?

**Comment by tzach** [comment]
+1 please do!

**Comment by denesb** [comment]
No backports needed.
