### ISSUE TITLE
docs: remove the MV problem from Troubleshooting

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#17205]
https://opensource.docs.scylladb.com/master/troubleshooting/error-messages/create-mv.html

Now that ScyllaDB is seedless, I think that this page can be removed from Troubleshooting.

@kbr-scylla @nyh Can you confirm?

**Comment by nyh** [comment]
Yes, I think you're right and it's no longer relevant. The modern code doesn't even have the string "Can't create materialized views until the whole cluster has been upgraded".
