### ISSUE TITLE
docs: Issue in page Upgrade Guide - ScyllaDB Enterprise 2023.x.y to 2023.x.z

### ISSUE THREAD

**Issue by pdbossman** [scylladb/scylladb#17210]
I would like to report an issue in page https://enterprise.docs.scylladb.com/branch-2023.1/upgrade/upgrade-enterprise/upgrade-guide-from-2023.x.y-to-2023.x.z/upgrade-guide-from-2023.x.y-to-2023.x.z-generic

### Problem
Nodetool drain is left out of procedure portion of instructions.

###  Suggest a fix

Add nodetool drain command above sudo systemctl stop scylla-server.  In the code block, etc.

**Comment by tzach** [comment]
Issue should be in Enterprise repo.
