### ISSUE TITLE
Logs are spammed with "sstable - Sharding metadata not available for .." on boot with tablets 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#17247]
It's benign (expected since c9f247f3e84662bacb29b69da957d3ab3960e16d), but annoying since it's printed for every sstable.

```
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_3863k217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_37iy8217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_373io217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_36vsw217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_368nk217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_360xs217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 0:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_38lj42n1exsq6i2i7n-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vcz_556o0217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 1:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_390yo217azumg1yv1v-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.
WARN  2024-02-09 13:17:30,415 [shard 0:main] sstable - Sharding metadata not available for /scylladir/testlog/x86_64/release/scylla-1363/data/test/test-c4567670c73c11eea88625d99eca538b/me-3gdh_0vd4_38dtc2n1exsq6i2i7n-big-Data.db, so Summary will be read to allow Scylla to compute shards owning the SSTable.

```

**Comment by raphaelsc** [comment]
we can demote that to debug log.

**Comment by bhalevy** [comment]
> we can demote that to debug log.

Shouldn't it be avoided with tablets?
If we expect no sharding metadata for sstables in tablets-enabled tables, we can rely on that.

**Comment by bhalevy** [comment]
@denesb please assign.
We should inspect the code for usage of the sharding metadata and make that conditional on vnodes.

**Comment by denesb** [comment]
@lkshminarayanan some context:: in the vnode world, sharding is based on the non-msb bits of the token, conceptually we have the following calculation:
```
owning shard = (token << 12) % smp::count
```
So each vnode a node owns, is striped onto all shards in a repeating pattern. Thus, determining whether an sstable belongs to this or that shard, cannot be done, just based on the range of keys it covers. So for each sstable, we store a sharding metadata: this is the sstable's range, intersected with all the shard ranges on this node: the resulting list of ranges is persisted into the sharding metadata (ScyllaMetadata component).
For tablets, this is not needed, as sharding is done on a tablet basis. An sstable always belongs to a single tablet and shard, so it is enough to just use the sstable's key range to determine which shard it belongs to. For this reason, with tablets we don't use sharding metadata anymore. However some code still expects to find this metadata and complains if it doesn't. We need to go over all the places that use sharding metadata and make its usage conditional, on the table using vnodes.

**Comment by raphaelsc** [comment]
> @denesb please assign.
> We should inspect the code for usage of the sharding metadata and make that conditional on vnodes.

I don't think we need to do anything. We have done that deliberately. Without sharding metadata available (which is only relevant with vnodes) the first and last keys are used and that will overlap with a single tablet usually. This issue is only annoyance and I think we don't have to do anything else other than demoting the log to debug level

**Comment by bhalevy** [comment]
> > @denesb please assign.
> > We should inspect the code for usage of the sharding metadata and make that conditional on vnodes.
> 
> I don't think we need to do anything. We have done that deliberately. Without sharding metadata available (which is only relevant with vnodes) the first and last keys are used and that will overlap with a single tablet usually. This issue is only about the annoyance and I think we don't have to do anything else other than demoting the log to debug level

Good, that said the log level can be determined by tablets or not, since the waning is justified for vnodes, but maybe I'm just over-complicating things

**Comment by denesb** [comment]
I agree, ideally, we don't need to log anything for tablets and log a warning for vnodes. But only if this it is reasonably easy to do.

**Comment by raphaelsc** [comment]
Issue became invalid after https://github.com/scylladb/scylladb/commit/c46c2d436f7886c838737168fe6725cc0a9c3a10
