### ISSUE TITLE
serious issue, slack channel has no one helping to answer questions for a long time, no help from telegram too.

### ISSUE THREAD

**Issue by kolinfluence** [scylladb/scylladb#17258]
i cant seem to set up scylladb using multi datacenter docker instances.

no idea what's wrong. i've opened ports etc. can someone give the instructions for it?

2 scylla instances of 4.4.8 (i need this version) in 2 datacenters (ovh and aws lightsail)

how to set it up? i can pay someone for the instructions. please help.

the local docker network ip is 10.252.252.0 and 10.252.252.1 (i can do 10.252.251.0 for other dc, not sure if this is how it should be set up)

https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/create-cluster-multidc.html

this does not work. pls help. been trying it for 1 week with multiple ways and configurations etc.

what's the instructions for docker containerized scylladb instances for multi datacenter setup?

p.s. : i can live with latest version scylladb too but need docker definitely.

**Comment by mykaul** [comment]
4.4.8 is way too outdated for anyone to look at it.

**Comment by nyh** [comment]
@kolinfluence this is a bug tracker, for reporting specific issues - bugs, feature requests, misleading or lacking documentation etc. It's a place for questions, so I'm closing this issue.

You could have phrased your question in a way it could have remained opened here, i.e., phrased it as a bug report on the documentation page, https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/create-cluster-multidc.html. However, to be a valid issue on the documentation you'd need to compare today's documentation to today's version of ScyllaDB! You tried to use instructions from latest Scylla against an ancient open-source version (the 4.4 branch came out almost three years ago), and it's not very surprising that it doesn't work. If you want us to look into this as a wrong- documentation problem you'll need to show that it fails on current ScyllaDB (even if eventually you plan to try the old version). You should also be more specific than "I don't know what's wrong". If you do those things you can create a new issue.

About Slack and Telegram (I didn't even know there was a Scylla presence in Telegram) - those are by definition **instant messaging** platforms, so if at the exact second you asked your question nobody who can answer it was present, you're unlikely to ever get a response. Moreover, if your question doesn't have an **instant** answer, it's also not a good fit for instant messaging. 

We do have other venues to discuss open-source ScyllaDB which are not instant-messaging. We have the scylladb-dev and scylladb-users mailing list on googlegroups.com, we have a forum (https://forum.scylladb.com/), and there is even a scylladb tag on stackoverflow. But even if you do ask your question there, it's important that like I said above, you should refer to modern versions of ScyllaDB, not three year old, and that you give more details about what errors you see.

**Comment by nyh** [comment]
Oh, and finally, you said you want to **pay** for the service, well ScyllaDB _the company_ does have paid enterprise products, paid support and long-term support for some versions (so you don't need to upgrade all the time), so you can ask for a quote on https://www.scylladb.com/pricing/. Most of the people you'll be interacting with on the open-source venues like this bug tracker will be developers of code, who can't give you price quotes or anything like that, nor spend time on solving your specific problem on a three-year-old version.
