### ISSUE TITLE
cql-pytest on Cassandra broke by tablet changes

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#17266]
Trying to run a cql-pytest on Cassandra (`test/cql-pytest/run-cassandra`) now skips the test, stating that `tablet-specific test skipped`.

The problem is the cool trick where we have test_keyspace using either test_keyspace_tablets or test_keyspace_vnodes, but on Cassandra, test_keyspace_tablets cannot be created and causes the test to be skipped.

I'll prepare a patch.
CC @denesb

**Comment by denesb** [comment]
Tablets related change, no backports required.
