### ISSUE TITLE
Write fails in DC1 when nodes in DC2 rebooted

### ISSUE THREAD

**Issue by Jay-s13** [scylladb/scylladb#17264]
My team has been facing an issue wherein if any activity is performed in DC2 of Scylla Multi DC setup with 3 nodes in DC1 and 6 nodes in DC2, we get following error in Go code, which uses GoCQL library,

`Cannot achieve consistency level for cl LOCAL_ONE. Requires 1, alive 0`
`Error for inserting submit => Cannot achieve consistency level for cl LOCAL_ONE. Requires 1, alive 0`

As per our understanding even if replication factor for system_auth is set to DC1 : 3 and DC2 : 1, when inserting record since LOCAL_ONE consistency is being used the query should limit to DC1 and hence any activity being performed in DC2 should not impact writes in DC1. Is there any possible explanation for failure in writes in DC1?

*Installation details*
**Scylla version:** 5.4.0
**Cluster size:** DC1 - 3 nodes, DC2 - 6 nodes
**OS (RHEL/CentOS/Ubuntu/AWS AMI):** Ubuntu 20.04

*Hardware details*
**Platform:** (GCP VMs) DC1 16 Core 32GB RAM, DC2 32 Core 64GB RAM
**Hardware:** cores=32 hyperthreading=2 memory=64GB
**Disks:** (SSD/HDD): DC1 - 1TB SSD, DC2 - 1TB SSD

**Comment by nyh** [comment]
I got confused by your statement of the problem you see. If I understand correctly, are you doing a LOCAL_ONE write in DC2? Where do you see an error on DC1 (the message you quoted doesn't say DC1 or an IP address,)? How is "system_auth" relevant?

Do you have more detail error messages or log messages you can quote?

**Comment by Jay-s13** [comment]
I missed out mentioning specifics, so what happens in our case is we **write to DC1** (mentioned DC1 node ips in connection string) through out the day in single table using **consistency LOCAL_QUORUM**, and **DC2 setup is only used to perform reads** on the same table. Now when we performed an upgrade in DC2 nodes we started facing errors in Golang code which writes to DC1 saying,

`level=error msg="error in inserting submit record Operation timed out for system_auth.roles - received only 0 responses from 1 CL=LOCAL_ONE."`
`Operation timed out for system_auth.roles - received only 0 responses from 1 CL=LOCAL_ONE.`

And the same keeps on repeating.
From our understanding the write operation happens in two parts, i.e.,
1. performs a read for non Cassandra user's roles in **system_auth.roles** with CL=LOCAL_ONE
2. Inserts into Table with CL=LOCAL_QUORUM which is the actual CL we set in code

So our concern is in spite of setting CL=LOCAL_QUORUM and mentioning only 3 IPs of DC1 in our Golang code, why would any failures in DC2 cause our write operations to break in DC1?
Also, if a check for system_auth.roles is performed with CL=LOCAL_ONE, why would the code try to connect to DC2 nodes? Since from our understanding **LOCAL_*** should limit the check to DC1 itself.

**Comment by mykaul** [comment]
CC @ptrsmrn

**Comment by nuivall** [comment]
@Jay-s13 it's a known issue or rather class of issues. We are working to improve data placement for auth keyspace. 

Currently we recommend setting RF of system_auth to number of nodes in each DC (using NetworkTopologyStrategy). Is your setup configured like that?

**Comment by Jay-s13** [comment]
Understood, when we faced the above issue the replication factor was set to 3 in DC1 and 1 in DC2. We have updated the replication to 3 in DC2 and it's been a week since and haven't faced any issues yet.
As per you advice we'll update RF to 6 in DC2 as well.
Thanks for your support.
