### ISSUE TITLE
Replace could fail because gracefully stopped node could be marked as alive.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#17276]
Scylla version 5.5.0~dev-0.20240211.13e16475fabb with build-id 155eca419cef95b6429a4ad42483e828be0ba4dc

Test: [replace_address_test.py::TestReplaceAddress::test_replace_first_boot[use_host_id-rbo_enabled]](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/42/artifact/logs-full.release.000/1707724092753_replace_address_test.py%3A%3ATestReplaceAddress%3A%3Atest_replace_first_boot%5Buse_host_id-rbo_enabled%5D/) could failed with error: 
`'node4', ['ERROR 2024-02-12 07:48:09,414 [shard 0:main] init - Startup failed: std::runtime_error (the topology coordinator rejected request to join the cluster: Cannot replace node da76afc5-8cd5-4439-b983-3620f07b3ede because it is considered alive)`

This happened because after node3 was stopped gracefully, 
```
INFO  2024-02-12 07:47:38,978 [shard 0:strm] schema_tables - Creating keyspace1.standard1 id=fe97d320-c97a-11ee-bbac-e011e05d00ad version=fe97d321-c97a-11ee-bbac-e011e05d00ad
INFO  2024-02-12 07:47:38,981 [shard 0:strm] migration_manager - Gossiping my schema version fe97e40a-c97a-11ee-923e-4f5f0fd81592
INFO  2024-02-12 07:47:38,981 [shard 0:strm] schema_tables - Schema version changed to fe97e40a-c97a-11ee-923e-4f5f0fd81592
INFO  2024-02-12 07:47:38,988 [shard 0:comp] compaction - [Compact system.topology_requests fe9bcac0-c97a-11ee-991c-6ff1f4bd6155] Compacting [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/me-3gdk_0lne_5u9g02btliyp9udlqt-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/me-3gdk_0lna_40oc02btliyp9udlqt-big-Data.db:level=0:origin=memtable]
INFO  2024-02-12 07:47:38,995 [shard 0:comp] compaction - [Compact system.topology_requests fe9bcac0-c97a-11ee-991c-6ff1f4bd6155] Compacted 2 sstables to [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/me-3gdk_0lne_5vz682btliyp9udlqt-big-Data.db:level=0]. 11kB to 6077 bytes (~53% of original) in 6ms = 1MB/s. ~256 total partitions merged to 3.
INFO  2024-02-12 07:47:38,996 [shard 0:comp] compaction - [Compact system.raft fe9d0340-c97a-11ee-991c-6ff1f4bd6155] Compacting [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gdk_0lne_5vjqo2btliyp9udlqt-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gdk_0lna_48e402btliyp9udlqt-big-Data.db:level=0:origin=compaction]
INFO  2024-02-12 07:47:39,002 [shard 0:comp] compaction - [Compact system.raft fe9d0340-c97a-11ee-991c-6ff1f4bd6155] Compacted 2 sstables to [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gdk_0lne_5xh6p2btliyp9udlqt-big-Data.db:level=0]. 216kB to 210kB (~97% of original) in 5ms = 43MB/s. ~256 total partitions merged to 1.
INFO  2024-02-12 07:47:39,003 [shard 0:comp] compaction - [Compact system.group0_history fe9e14b0-c97a-11ee-991c-6ff1f4bd6155] Compacting [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/group0_history-027e42f5683a3ed7b404a0100762063c/me-3gdk_0lne_5v4b42btliyp9udlqt-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/group0_history-027e42f5683a3ed7b404a0100762063c/me-3gdk_0ln4_5jz2p2btliyp9udlqt-big-Data.db:level=0:origin=compaction]
INFO  2024-02-12 07:47:39,008 [shard 0:comp] compaction - [Compact system.group0_history fe9e14b0-c97a-11ee-991c-6ff1f4bd6155] Compacted 2 sstables to [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system/group0_history-027e42f5683a3ed7b404a0100762063c/me-3gdk_0lnf_00n5d2btliyp9udlqt-big-Data.db:level=0]. 13kB to 7684 bytes (~57% of original) in 3ms = 4MB/s. ~256 total partitions merged to 1.
INFO  2024-02-12 07:47:39,008 [shard 0:comp] compaction - [Compact system_schema.tables fe9ed800-c97a-11ee-991c-6ff1f4bd6155] Compacting [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gdk_0lne_5uh5s2btliyp9udlqt-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/md-2-big-Data.db:level=0:origin=memtable]
INFO  2024-02-12 07:47:39,013 [shard 0:comp] compaction - [Compact system_schema.tables fe9ed800-c97a-11ee-991c-6ff1f4bd6155] Compacted 2 sstables to [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3gdk_0lnf_01pq92btliyp9udlqt-big-Data.db:level=0]. 21kB to 14kB (~69% of original) in 4ms = 5MB/s. ~256 total partitions merged to 7.
INFO  2024-02-12 07:47:39,013 [shard 0:comp] compaction - [Compact system_schema.columns fe9f9b50-c97a-11ee-991c-6ff1f4bd6155] Compacting [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-3gdk_0lne_5uovk2btliyp9udlqt-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-2-big-Data.db:level=0:origin=memtable]
INFO  2024-02-12 07:47:39,018 [shard 0:comp] compaction - [Compact system_schema.columns fe9f9b50-c97a-11ee-991c-6ff1f4bd6155] Compacted 2 sstables to [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node3/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/me-3gdk_0lnf_02sb52btliyp9udlqt-big-Data.db:level=0]. 26kB to 21kB (~80% of original) in 4ms = 6MB/s. ~256 total partitions merged to 7.```

then node4 was started with replace node3 but startup failed:
```
INFO  2024-02-12 07:48:07,365 [shard 0:strm] storage_service - entering STARTING mode
INFO  2024-02-12 07:48:07,365 [shard 0:strm] storage_service - Loading persisted ring state
INFO  2024-02-12 07:48:07,366 [shard 0:strm] storage_service - initial_contact_nodes={127.0.73.3, 127.0.73.2, 127.0.73.1}, loaded_endpoints={}, loaded_peer_features=0
INFO  2024-02-12 07:48:07,367 [shard 0:strm] storage_service - Found group 0 with ID f33628b1-c97a-11ee-9701-e011da53ec95, with leader of ID 400f4ebb-12f2-4b66-8d8e-cc671f576b3c and IP 127.0.73.1
INFO  2024-02-12 07:48:07,367 [shard 0:strm] storage_service - Will join existing cluster in raft topology operations mode
INFO  2024-02-12 07:48:07,367 [shard 0:strm] storage_service - Gathering node replacement information for da76afc5-8cd5-4439-b983-3620f07b3ede/::
INFO  2024-02-12 07:48:07,367 [shard 0:strm] storage_service - Performing gossip shadow round
INFO  2024-02-12 07:48:07,367 [shard 0:strm] gossip - Gossip shadow round started with nodes={127.0.73.3, 127.0.73.2, 127.0.73.1}
WARN  2024-02-12 07:48:07,367 [shard 0:strm] gossip - Node 127.0.73.3 is down for get_endpoint_states verb
INFO  2024-02-12 07:48:07,367 [shard 0:strm] gossip - Gossip shadow round finished with nodes_talked={127.0.73.1, 127.0.73.2}
INFO  2024-02-12 07:48:07,367 [shard 0:strm] storage_service - Host e493aeab-8a9d-4403-8dae-752d7f093052/127.0.73.4 is replacing da76afc5-8cd5-4439-b983-3620f07b3ede/127.0.73.3
INFO  2024-02-12 07:48:07,368 [shard 0:strm] storage_service - Save advertised features list in the 'system.local' table
INFO  2024-02-12 07:48:07,371 [shard 0:strm] schema_tables - Schema version changed to 59adb24e-f3cd-3e02-97f0-5b395827453f
INFO  2024-02-12 07:48:07,371 [shard 0:strm] storage_service - Starting up server gossip
INFO  2024-02-12 07:48:07,371 [shard 0:strm] gossip - failure_detector_loop: Started main loop
INFO  2024-02-12 07:48:07,371 [shard 0:strm] raft_group0 - Replacing a node with Raft ID: da76afc5-8cd5-4439-b983-3620f07b3ede, IP address: 127.0.73.3
INFO  2024-02-12 07:48:07,371 [shard 0:strm] raft_group0 - setup_group0: joining group 0...
INFO  2024-02-12 07:48:07,371 [shard 0:strm] raft_group0 - server e493aeab-8a9d-4403-8dae-752d7f093052 found no local group 0. Discovering...
INFO  2024-02-12 07:48:07,372 [shard 0:strm] raft_group0 - server e493aeab-8a9d-4403-8dae-752d7f093052 found group 0 with group id f33628b1-c97a-11ee-9701-e011da53ec95, leader db41c761-2a98-4b6a-b75c-14cfee9935e1
INFO  2024-02-12 07:48:07,372 [shard 0:strm] raft_topology - join: sending the join request to 127.0.73.2
INFO  2024-02-12 07:48:07,401 [shard 0:strm] raft_topology - join: request to join placed, waiting for the response from the topology coordinator
INFO  2024-02-12 07:48:07,401 [shard 0:strm] raft_group0 - Server e493aeab-8a9d-4403-8dae-752d7f093052 is starting group 0 with id f33628b1-c97a-11ee-9701-e011da53ec95
INFO  2024-02-12 07:48:07,402 [shard 0:strm] raft_group0 - Detected snapshot with index=0, id=b6a1aa48-7b9d-40f1-847a-3b78fc12ff6d, triggering new snapshot
WARN  2024-02-12 07:48:07,402 [shard 0:strm] raft_group0 - Could not create new snapshot, there are no entries applied
...
ERROR 2024-02-12 07:48:09,414 [shard 0:main] init - Startup failed: std::runtime_error (the topology coordinator rejected request to join the cluster: Cannot replace node da76afc5-8cd5-4439-b983-3620f07b3ede because it is considered alive)
```
Raft topology coordinator aborted bootstrap:
```
INFO  2024-02-12 07:47:39,005 [shard 0:comp] compaction - [Compact system.topology fe9e62d0-c97a-11ee-9701-e011da53ec95] Compacting [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gdk_0lne_5r9f42ao4w6hu67jit-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gdk_0ln4_55m3l2ao4w6hu67jit-big-Data.db:level=0:origin=compaction]
INFO  2024-02-12 07:47:39,010 [shard 0:comp] compaction - [Compact system.topology fe9e62d0-c97a-11ee-9701-e011da53ec95] Compacted 2 sstables to [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gdk_0lnf_012kx2ao4w6hu67jit-big-Data.db:level=0]. 33kB to 26kB (~78% of original) in 4ms = 8MB/s. ~256 total partitions merged to 1.
INFO  2024-02-12 07:47:46,781 [shard 0:main] raft_group_registry - marking Raft server da76afc5-8cd5-4439-b983-3620f07b3ede as dead for raft groups
WARN  2024-02-12 07:47:47,869 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:47:49,869 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:47:51,870 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:47:53,870 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:47:55,870 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:47:57,870 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:47:59,870 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:48:01,871 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:48:03,871 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-12 07:48:05,871 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2024-02-12 07:48:07,378 [shard 0:comp] compaction - [Compact system.topology 0f87c320-c97b-11ee-9701-e011da53ec95] Compacting [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gdk_0lo7_285sw2ao4w6hu67jit-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gdk_0lnf_012kx2ao4w6hu67jit-big-Data.db:level=0:origin=compaction]
INFO  2024-02-12 07:48:07,388 [shard 0:strm] raft_topology - coordinator fiber found a node to work on id=e493aeab-8a9d-4403-8dae-752d7f093052 state=none
WARN  2024-02-12 07:48:07,388 [shard 0:strm] raft_topology - (rate limiting dropped 196 similar messages) cannot map e493aeab-8a9d-4403-8dae-752d7f093052 to ip, retrying.
INFO  2024-02-12 07:48:07,391 [shard 0:comp] compaction - [Compact system.topology 0f87c320-c97b-11ee-9701-e011da53ec95] Compacted 2 sstables to [/jenkins/workspace/scylla-staging/abykov/Dtest/master-dtest-with-raft/scylla/.dtest/dtest-tkqnkd84/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gdk_0lo7_298ds2ao4w6hu67jit-big-Data.db:level=0]. 34kB to 27kB (~79% of original) in 11ms = 3MB/s. ~256 total partitions merged to 1.
WARN  2024-02-12 07:48:07,871 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.73.3, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2024-02-12 07:48:07,872 [shard 0:strm] gossip - failure_detector_loop: Mark node 127.0.73.3 as DOWN
INFO  2024-02-12 07:48:07,872 [shard 0:strm] gossip - InetAddress 127.0.73.3 is now DOWN, status = NORMAL
INFO  2024-02-12 07:48:08,374 [shard 0: gms] gossip - InetAddress 127.0.73.4 is now UP, status = UNKNOWN
INFO  2024-02-12 07:48:08,375 [shard 0:strm] raft_topology - updating topology state: bootstrap: node rejected
INFO  2024-02-12 07:48:08,380 [shard 0:strm] gossip - Removed endpoint 127.0.73.4
INFO  2024-02-12 07:48:08,380 [shard 0:strm] gossip - InetAddress 127.0.73.4 is now DOWN, status = UNKNOWN
INFO  2024-02-12 07:48:08,381 [shard 0:strm] gossip - Finished to force remove node 127.0.73.4
INFO  2024-02-12 07:48:08,386 [shard 0:strm] raft_topology - rejected node moved to left state e493aeab-8a9d-4403-8dae-752d7f093052
INFO  2024-02-12 07:48:08,387 [shard 0:strm] load_balancer - Examining DC datacenter1
INFO  2024-02-12 07:48:08,387 [shard 0:strm] load_balancer - Node 400f4ebb-12f2-4b66-8d8e-cc671f576b3c: rack=rack1 avg_load=0, tablets=0, shards=2, state=normal

```

Logs could be found here: https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/42/artifact/logs-full.release.000/1707724092753_replace_address_test.py%3A%3ATestReplaceAddress%3A%3Atest_replace_first_boot%5Buse_host_id-rbo_enabled%5D/

**Comment by aleksbykov** [comment]
As workaround her, we can have some waiter, to be sure that node3 is completely down on all nodes, it it is test error due to some races

**Comment by aleksbykov** [comment]
The same error are met in tests:
https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/43/testReport/

**Comment by mykaul** [comment]
@aleksbykov - sounds like a flaky test, not a bug in Scylla itself?

**Comment by aleksbykov** [comment]
@mykaul , yes, it sound like flaky test. but i want to get approve from @kbr-scylla

**Comment by kbr-scylla** [comment]
node3 is stopping gracefully, so in theory there should be a notification to other nodes that it's going down, thus there should be no race.

But I don't remember if that notification is delivered synchronously or async. Probably async, in which case there could be flakiness. cc @gleb-cloudius I recall you looked at this, do you remember?

But is the test also flaky in gossiper mode? Or only raft-topology mode? Maybe we're not delivering the notification correctly in raft-topology mode

**Comment by aleksbykov** [comment]
I will check the stat for test with gossiper, but it looks quite stable with gossiper mode.

**Comment by gleb-cloudius** [comment]
Of course shutdown notification is delivered asynchronously vs test code.

**Comment by bhalevy** [comment]
The node shutting sends and forgets the gossip shutdown message.

**Comment by bhalevy** [comment]
ccm has a wait_other_notice flag to node.stop()
that is working in gossip mode and aparently is broken (or not used) with raft cinsistent topology changes in this test.
Please check if it is used and if so, how to make it work in this configuration.
Cc @fruch

**Comment by patjed41** [comment]
These are flaky tests, not a bug in Scylla.

> The same error are met in tests:
https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/43/testReport/

I'll start with explaining the errors above since they are simpler.

In the test:
```python
def test_replace_with_background_workload(self, use_host_id: bool):
    ...
    node3.stop(gently=False)
```
In scylla-ccm:
```python
class Node(object):
    ...
    def stop(self, wait=True, wait_other_notice=False, other_nodes=None, gently=True, wait_seconds=127):
        ...
          - wait_other_notice: return only when the other live nodes of the
            cluster have marked this node has dead.
```

It looks like node3 isn't stopped gracefully and the test initiates the replace operation without waiting until other nodes mark node3 as dead. Hence, the failure is expected. Moreover, the test could theoretically fail even with `node3.stop(gently=True)`. In such a case, we wouldn't have the guarantee that other nodes receive the shutdown notification in time.

To make the test not flaky, we need to use `wait_other_notice=True`. Additionally, we should use `gently=True` to not slow down the test too much. Other nodes would mark the replaced node as dead after receiving the notification from it, which usually happens much quicker than a failure detector timeout (20 s).

In `test_replace_first_boot`, there is `node3.stop(gently=False)` too, but before replacing node3, the test does:
```python
logger.info("Testing node stoppage (query should fail).")
with pytest.raises(expected_exception=(Unavailable, ReadTimeout, ReadFailure, OperationTimedOut)):
    session.execute(query, timeout=30)
```
We can see in logs that successively:
- node2 (presumably the request coordinator) marks node3 as DOWN:
```
INFO  2024-02-12 07:48:06,832 [shard 0:strm] gossip - failure_detector_loop: Mark node 127.0.73.3 as DOWN
```
- the request starts failing because of an unvailable host (it's restarted 5 times due to`FlakyRetryPolicy`):
```
07:47:46,941 795     replace_address_test           INFO     replace_address_test.py:427  | test_replace_first_boot[use_host_id-rbo_enabled]: Testing node stoppage (query should fail).
07:47:56,941 795     dtest_class                    DEBUG    dtest_class.py      :31   | test_replace_first_boot[use_host_id-rbo_enabled]: Retrying read after timeout. Attempt #0
07:48:06,942 795     dtest_class                    DEBUG    dtest_class.py      :31   | test_replace_first_boot[use_host_id-rbo_enabled]: Retrying read after timeout. Attempt #1
07:48:06,943 795     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_first_boot[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #2
07:48:06,944 795     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_first_boot[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #3
07:48:06,945 795     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_first_boot[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #4
07:48:06,945 795     replace_address_test           INFO     replace_address_test.py:432  | test_replace_first_boot[use_host_id-rbo_enabled]: Starting node 4 to replace node 3
```
- node4 replacing node3 starts booting and sends the join request to node2:
```
INFO  2024-02-12 07:48:07,372 [shard 0:strm] raft_topology - join: sending the join request to 127.0.73.2
```
- node1 (the topology coordinator) starts handling the join request:
```
INFO  2024-02-12 07:48:07,388 [shard 0:strm] raft_topology - coordinator fiber found a node to work on id=e493aeab-8a9d-4403-8dae-752d7f093052 state=none
```
- node1 marks node3 as DOWN (and the join request validation has failed):
```
INFO  2024-02-12 07:48:07,872 [shard 0:strm] gossip - failure_detector_loop: Mark node 127.0.73.3 as DOWN
```

So, the failure scenario in this test is quite peculiar, but it's still an expected failure. I would also fix it by changing `node3.stop(gently=False)` to `node3.stop(wait_other_notice=True, gently=True)`. Then, the query would fail immediately, but I don't think the test would be weakened.

I'll check if there are other tests with a similar problem (perhaps with removenode) and send a fix.

**Comment by aleksbykov** [comment]
@patjed41 , we already have a fix: https://github.com/scylladb/scylladb/issues/17276. For test_replace_first_boot it has quite stable good results with/without raft topology. With the fix test test_replace_with_background_workload failed with error in teardowns which described in https://github.com/scylladb/scylladb/issues/17209.

**Comment by patjed41** [comment]
> @patjed41 , we already have a fix: https://github.com/scylladb/scylladb/issues/17276.

I think you linked this issue instead of the fix by mistake.

**Comment by patjed41** [comment]
OK, now I see it: https://github.com/scylladb/scylla-dtest/pull/3958.

It looks like this fix reeinvents the `wait_other_notice=True` though.

Also, it would be nice to see that the issue is being worked on, so that I'm not assigned just to waste my time.
