### ISSUE TITLE
`storage_service - Failed to complete splitting of table` when stopping scylla service, when tablets is enabled

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylladb#17286]
## Packages

Scylla version: `5.5.0~dev-20240204.784c2f8ad21f` with build-id `ea88d58c7ad71134a76536223c22079704e583d9`
Kernel Version: `5.15.0-1052-aws`

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

- **In these runs, both `consistent-topology-changes` and `tablets` are enabled**

In this scenario, every few minutes we stop a random node's scylla service, and then start it again. In this specific run, did so five times in total. In the first three times, the stop-start process went without issue:
1. On node 2, between `2024-02-05 08:58:10` - `2024-02-05 09:00:06`
2. On node 3, between `2024-02-05 09:09:28` - `2024-02-05 09:11:24`
3. On node 2, between `2024-02-05 09:24:26` - `2024-02-05 09:26:23`

On the fourth occurrence, at `2024-02-05 09:38:35,646`, we stop the scylla service on node 3:
`< t:2024-02-05 09:38:35,646 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo systemctl stop scylla-server.service"...`
and during the shutdown procedure, the following error message appeared:
```
2024-02-05T09:38:42.741+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-3     !INFO | scylla[9893]:  [shard 0:main] init - Shutting down group 0 usage in local storage
2024-02-05T09:38:42.741+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-3     !INFO | scylla[9893]:  [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
2024-02-05T09:38:42.741+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-3     !INFO | scylla[9893]:  [shard 0:strm] raft_topology - cleanup fiber aborted
2024-02-05T09:38:42.741+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-3      !ERR | scylla[9893]:  [shard 0:strm] storage_service - Failed to complete splitting of table 67b62e50-c404-11ee-af9c-daa3299a2a69 due to raft::request_aborted (Request is aborted by a caller), retrying after 5000ms seconds
2024-02-05T09:38:42.741+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-3     !INFO | scylla[9893]:  [shard 0:main] init - Shutting down group 0 usage in local storage was successful
```
It didn't stop the shutdown process, and the scylla service managed to stop and start with no issue afterwards.

The same thing happened in the next occurrence, when we stopped node 2:
`< t:2024-02-05 09:52:24,323 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo systemctl stop scylla-server.service"...`
```
2024-02-05T09:52:31.443+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-2     !INFO | scylla[11158]:  [shard 0:main] init - Shutting down group 0 usage in local storage
2024-02-05T09:52:31.443+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-2     !INFO | scylla[11158]:  [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
2024-02-05T09:52:31.443+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-2     !INFO | scylla[11158]:  [shard 0:strm] raft_topology - cleanup fiber aborted
2024-02-05T09:52:31.443+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-2      !ERR | scylla[11158]:  [shard 0:strm] storage_service - Failed to complete splitting of table 67b62e50-c404-11ee-af9c-daa3299a2a69 due to raft::request_aborted (Request is aborted by a caller), retrying after 5000ms seconds
2024-02-05T09:52:31.443+00:00 longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-2     !INFO | scylla[11158]:  [shard 0:main] init - Shutting down group 0 usage in local storage was successful
```
Again, scylla managed to stop without issue afterwards

## How frequently does it reproduce?

Seem to only happen occasionally, around 40% of the time.

The same error appears in other scenarios, but always when during the scylla shutdown process, and in similar frequency.
The error is obviously related to tablets, but to be certain I reran the job with only `consistent-topology-changes` enabled (and tablets disabled) and the issue did not reoccur.

## Installation details

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-3 (3.251.82.232 | 10.4.2.82) (shards: 2)
- longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-2 (34.246.177.34 | 10.4.2.115) (shards: 2)
- longevity-5gb-1h-StopStartMonkey-ta-db-node-439e3098-1 (34.242.89.152 | 10.4.2.252) (shards: 2)

OS / Image: `ami-00c6a0851f2c6664c` (aws: undefined_region)

Test: `longevity-5gb-1h-StopStartMonkey-aws-test`
Test id: `439e3098-d841-4e5e-8e03-c572b37fbc94`
Test name: `scylla-staging/tablets/longevity-5gb-1h-StopStartMonkey-aws-test`
Test config file(s):

- [longevity-5gb-1h-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4da142261600609396b758544e7c5e1d32ebf816/configurations/nemesis/longevity-5gb-1h-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 439e3098-d841-4e5e-8e03-c572b37fbc94`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=439e3098-d841-4e5e-8e03-c572b37fbc94)
- Show all stored logs command: `$ hydra investigate show-logs 439e3098-d841-4e5e-8e03-c572b37fbc94`

## Logs:
- **db-cluster-439e3098.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/db-cluster-439e3098.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/db-cluster-439e3098.tar.gz)
- **sct-runner-events-439e3098.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/sct-runner-events-439e3098.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/sct-runner-events-439e3098.tar.gz)
- **sct-439e3098.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/sct-439e3098.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/sct-439e3098.log.tar.gz)
- **loader-set-439e3098.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/loader-set-439e3098.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/loader-set-439e3098.tar.gz)
- **monitor-set-439e3098.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/monitor-set-439e3098.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/monitor-set-439e3098.tar.gz)
- **parallel-timelines-report-439e3098.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/parallel-timelines-report-439e3098.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/439e3098-d841-4e5e-8e03-c572b37fbc94/20240205_101258/parallel-timelines-report-439e3098.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/tablets/job/longevity-5gb-1h-StopStartMonkey-aws-test/2/)
[Argus](https://argus.scylladb.com/test/f3fee4e5-ad26-4a37-bcb3-b07bb867d278/runs?additionalRuns[]=439e3098-d841-4e5e-8e03-c572b37fbc94)
</details>

**Comment by mykaul** [comment]
So apart from a somewhat scary (not very) error message, what's the impact?

**Comment by raphaelsc** [comment]
The problem might be the choice of error log level and SCT failing on that. @ShlomiBalalis does SCT fail on WARN log?

**Comment by raphaelsc** [comment]
> > The problem might be the choice of error log level and SCT failing on that. @ShlomiBalalis does SCT fail on WARN log?
> 
> We can always skip this error under this condition. SCT can do that easily.

Great. but maybe I should really demote the message from error to warn level, as it's not really an error, but just a warning. It's ok for a replica to not complete its local split work if it's going down. Coordinator won't be able to proceed with the split process anyway until the node is back up and resumes its split work.

**Comment by ShlomiBalalis** [comment]
> So apart from a somewhat scary (not very) error message, what's the impact?

Again, doesn't seem like much of an impact. Just needed to be sure if the error itself is problematic

> The problem might be the choice of error log level and SCT failing on that. @ShlomiBalalis does SCT fail on WARN log?

It should not, by default, but some error types can cause the run to fail even if it's warning.
But this log message's level seem to be error?

> > The problem might be the choice of error log level and SCT failing on that. @ShlomiBalalis does SCT fail on WARN log?
> 
> We can always skip this error under this condition. SCT can do that easily.

Yep, just say the word

**Comment by raphaelsc** [comment]
> > So apart from a somewhat scary (not very) error message, what's the impact?
> 
> Again, doesn't seem like much of an impact. Just needed to be sure if the error itself is problematic
> 
> > The problem might be the choice of error log level and SCT failing on that. @ShlomiBalalis does SCT fail on WARN log?
> 
> It should not, by default, but some error types can cause the run to fail even if it's warning. But this log message's level seem to be error?
> 
> > > The problem might be the choice of error log level and SCT failing on that. @ShlomiBalalis does SCT fail on WARN log?
> > 
> > 
> > We can always skip this error under this condition. SCT can do that easily.
> 
> Yep, just say the word

pattern: "Failed to complete splitting of table * due to raft::request_aborted (Request is aborted by a caller)"

**Comment by mykaul** [comment]
> pattern: "Failed to complete splitting of table * due to raft::request_aborted (Request is aborted by a caller)"

This itself should be (in SCT) only upon certain conditions (like when stopping Scylla).

**Comment by ShlomiBalalis** [comment]
> > pattern: "Failed to complete splitting of table * due to raft::request_aborted (Request is aborted by a caller)"
> 
> This itself should be (in SCT) only upon certain conditions (like when stopping Scylla).

Of course. Right Now I'll only ignore it when stopping scylla

**Comment by bhalevy** [comment]
@raphaelsc so what's the purpose of this issue?
Demoting the error message to warning on the scylla side?

**Comment by raphaelsc** [comment]
> @raphaelsc so what's the purpose of this issue? Demoting the error message to warning on the scylla side?

yes, in the context of shutdown.

**Comment by mykaul** [comment]
what's the status of this issue? Is it blocking sct tests?

**Comment by raphaelsc** [comment]
@ShlomiBalalis ping

**Comment by bhalevy** [comment]
> > > pattern: "Failed to complete splitting of table * due to raft::request_aborted (Request is aborted by a caller)"
> > 
> > 
> > This itself should be (in SCT) only upon certain conditions (like when stopping Scylla).
> 
> Of course. Right Now I'll only ignore it when stopping scylla

@ShlomiBalalis please see if that already happened and close the issue respectively.

**Comment by mykaul** [comment]
Closing for the time being, please re-open if still relevant.
