### ISSUE TITLE
dtest: no expected log message for topology_test.TestTopology.test_decommissioned_node_cant_rejoin

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylladb#17282]
topology_test.TestTopology.test_decommissioned_node_cant_rejoin fails to wait for https://github.com/scylladb/scylladb/blob/13e16475fabb51be4c24e14c3ed1551885c4fe56/service/storage_service.cc#L1212 in RAFT topology mode.

Test flow:

        - create a cluster
        - decommission a node
        - stop & start the node
        - assert that the "node was decommissioned and will not rejoin" error is in the logs for that node

Scylla version: 5.5.0~dev-0.20240209.7a710425f0e2

It's a regression from 5.5.0~dev-0.20240208.082ad51b7183

Example of failure: https://jenkins.scylladb.com/job/scylla-staging/job/evgeniy/job/gating-dtest-release-with-consistent-topology-changes/206/testReport/junit/topology_test/TestTopology/FullDtest___full_split001___test_decommissioned_node_cant_rejoin/

**Comment by mykaul** [comment]
With such a small window of regression, can we run bisect?

**Comment by kbr-scylla** [comment]
From @gusev-p's daily
>   * investigating https://github.com/scylladb/scylladb/issues/17282(dtest: no expected log message for topology_test.TestTopology.test_decommissioned_node_cant_rejoin)
>    * the was_decommissioned check is in join_token_ring and we get stuck in join_cluster, in the new upgate code, trying to discover_group0()

So it's most likely from e9e24f47ec84b90a784e0064203da06888703e99 which modified the boot procedure
