### ISSUE TITLE
View building can hang with tablets

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#17297]
The dtest `materialized_views_test.py::TestMaterializedViews::test_mv_alter_with_synchronous_updates` is set up by creating a table with 100,000 rows and then adding 50 (!) materialized views to it and waiting for them to be built (this is just the setup, before anything is tested!).

The test uses the `wait_for_view()` utility function to wait for the views. This by default waits 10 minutes for all the views to be built, and without tablets it was successful. A couple of weeks ago I remember running it _with_ tablets, and it also passed.

But today, when I run this test, it doesn't end in 10 minutes and also doesn't end if the timeout is increased to 1 hour.
Initially, it seems that all 4 Scylla processes (representing 4 nodes) work equally hard, using 200% CPU each (two shards). After a few minutes, it seems only one of the nodes remains busy, at around 100% CPU (i.e., just one shard is busy). And this node doesn't finish to build some of the views (the dtest log shows what it is waiting for).

I don't see any explanation in the logs why this single node is hung or what it is doing.

If I do `grep "Finished building view" logfile | wc -l` on three of the nodes, I get 50 as expected - they finished building all 50 views. On the problematic node, I see just 38 views finished to build. And after the 38th, nothing of interest appears in the log. But it seems one shard is stuck in an endless loop. Doing what?

**Comment by bhalevy** [comment]
fwiw, I've noticed tablet allocation for new tables hang with random configurations without the changes in #17846

**Comment by nyh** [comment]
This test now seem to pass for me (I don't know what changed), prints the following error:
```
18:10:49,061 materialized_views_test ERROR materialized_views_test.py:1124 | Expected [['c2 value 2414335']] from select c2 from ks.mv_cf_view_4 where key='k77' and c1 = 'c1 value 77', but got [['c2 value 77']]
```
But it doesn't fail the test - and eventually (after a long time) it passes. Why?

**Comment by bhalevy** [comment]
@nyh should this issue block the release?

**Comment by nyh** [comment]
The original problem was blocking, but it appears this was actually fixed (by a deadlock fix, not specifically related to materialized view). The new problem, if it is even a problem, doesn't appear to be a blocker but I'll need to look into this issue more deeply.

**Comment by mykaul** [comment]
> The original problem was blocking, but it appears this was actually fixed (by a deadlock fix, not specifically related to materialized view). The new problem, if it is even a problem, doesn't appear to be a blocker but I'll need to look into this issue more deeply.

@nyh - did you get to look at this?

**Comment by nyh** [comment]
Indeed, the hanging bug is gone, so closing this issue. 

I still see an error message printed by the test:
```
19:24:37,682 materialized_views_test ERROR materialized_views_test.py:1116 | Expected [['c2 value 166453752']] from select c2 from ks.mv_cf_view_4 where key='k2104' and c1 = 'c1 value 2104', but got [['c2 value 2104']]
```
So I'll think about it and if it's a real problem I'll open a new issue about it.

**Comment by nyh** [comment]
Turns out the error message was a red herring (CC @juliayakovlev who wrote this test and may want to consider fixing it). This test always needs to print this error message exactly once:

The purpose of the test `test_mv_alter_with_synchronous_updates` was to verify that we can take a view with asynchronous updates and change it to have synchronous updates. The test checks that before the ALTER we have asynchronous updates and after it's synchronous. It checks the synchronous-ness of the updates by doing a base write and then reading from a view, and checking if we get the wrong value. If we **ever** get a wrong value, we print the above message. But for the asynchronous updates case we **expect** this "wrong value" and in fact when we reach it this part of the test ends successfully - so we expect to see exactly one such error message every time. When the test moves on to the synchronous setting, we don't expect to see this error message again - and if we ever did, the test would fail. And it doesn't - it passes.

So there is no bug here.
