### ISSUE TITLE
test_topology_recovery_basic

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#17305]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6597/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_topology_recovery_basic_dev_1/

Log files for the record:
[log.txt](https://github.com/scylladb/scylladb/files/14258378/log.txt)
[scylla-2068.log](https://github.com/scylladb/scylladb/files/14258381/scylla-2068.log)
[scylla-2069.log](https://github.com/scylladb/scylladb/files/14258382/scylla-2069.log)

It seems like it could be another driver reconnect issue, but I also saw this in the scylla logs:
```
WARN  2024-02-12 19:20:10,181 [shard 0:stmt] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 127.52.139.35, application_states = {{RPC_READY -> Value(1,1)}})
```

**Comment by kbr-scylla** [comment]
@piodul is this the issue fixed by https://github.com/scylladb/scylladb/pull/17278?

**Comment by piodul** [comment]
> @piodul is this the issue fixed by #17278?

Yes, the test failure happens in the same place and I believe that the fix is the same.

The `WARN` log message seems to be an orthogonal issue, though.

**Comment by piodul** [comment]
> The `WARN` log message seems to be an orthogonal issue, though.

It's most likely https://github.com/scylladb/scylladb/issues/16932 - the warning appears right after the maintenance socket is set up. All three nodes in the test issue a similar warning:

```
INFO  2024-02-12 19:20:02,598 [shard 0:stmt] cql_server_controller - Setting up maintenance socket on /scylladir/testlog/x86_64/dev/scylla-2068/cql.m
INFO  2024-02-12 19:20:02,598 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on /scylladir/testlog/x86_64/dev/scylla-2068/cql.m (unencrypted, non-shard-aware)
WARN  2024-02-12 19:20:02,598 [shard 0:stmt] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 127.52.139.48, application_states = {{RPC_READY -> Value(1,1)}})
```

**Comment by mykaul** [comment]
@piodul - can this issue be closed now?

**Comment by piodul** [comment]
Yes, I believe so. The main issue is fixed and the warning is tracked somewhere else. I'm closing now.
