### ISSUE TITLE
nodetool cleanup failed with "Can't find a keyspace"

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylladb#17302]
## Packages

Scylla version: `5.5.0~dev-20240209.7a710425f0e2` with build-id `f4777533fdd4b53d42e7a22dd9605eb4feb4fc5a`

Kernel Version: `5.15.0-1053-aws`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

`nodetool cleanup` command failing with following error:

```
Command: '/usr/bin/nodetool  cleanup '

Exit code: 4

Stdout:



Stderr:

error executing POST request to http://localhost:10000/storage_service/cleanup_all with parameters {}: remote replied with status code 400 Bad Request:
Can't find a keyspace 


```

This is a regression from `5.5.0~dev-20240202.52e6398ad64d`: [scylla-master/longevity/longevity-twcs-48h-test#106](https://argus.scylladb.com/test/ca1ac895-78c0-4abd-80d5-0ba6dc7844bf/runs?additionalRuns[]=bd044655-65f8-481d-8960-46c0adbf5785)

The main suspect is https://github.com/scylladb/scylladb/pull/16757/commits/5e0b3671d3cd571d79418425ad5a76ad865155b6 but maybe not alone and it's a combination of this one and another recent changes.

## Impact

Unable to successfully run `nodetool cleanup` command.

## How frequently does it reproduce?

In the SCT test run all 3 disrupt_nodetool_cleanup nemesis runs failed.

## Installation details

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-afcdf00b-8 (3.248.225.149 | 10.4.10.254) (shards: 7)
- longevity-twcs-48h-master-db-node-afcdf00b-7 (3.255.167.128 | 10.4.8.105) (shards: -1)
- longevity-twcs-48h-master-db-node-afcdf00b-6 (18.201.133.180 | 10.4.11.69) (shards: -1)
- longevity-twcs-48h-master-db-node-afcdf00b-5 (34.241.107.131 | 10.4.9.87) (shards: -1)
- longevity-twcs-48h-master-db-node-afcdf00b-4 (52.16.163.66 | 10.4.8.161) (shards: 7)
- longevity-twcs-48h-master-db-node-afcdf00b-3 (54.217.137.119 | 10.4.10.110) (shards: 7)
- longevity-twcs-48h-master-db-node-afcdf00b-2 (34.244.67.253 | 10.4.9.248) (shards: 7)
- longevity-twcs-48h-master-db-node-afcdf00b-1 (3.253.51.25 | 10.4.10.155) (shards: 7)

OS / Image: `ami-07569b2b3deaa1ea9` (aws: undefined_region)

Test: `longevity-twcs-48h-test`
Test id: `afcdf00b-2ebd-4914-8b13-651493354d53`
Test name: `scylla-master/longevity/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fba16698a8f23c0c1457cc8e9c268d371f4b3d6c/test-cases/longevity/longevity-twcs-48h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor afcdf00b-2ebd-4914-8b13-651493354d53`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=afcdf00b-2ebd-4914-8b13-651493354d53)
- Show all stored logs command: `$ hydra investigate show-logs afcdf00b-2ebd-4914-8b13-651493354d53`

## Logs:
- **db-cluster-afcdf00b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/db-cluster-afcdf00b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/db-cluster-afcdf00b.tar.gz)
- **sct-runner-events-afcdf00b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/sct-runner-events-afcdf00b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/sct-runner-events-afcdf00b.tar.gz)
- **sct-afcdf00b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/sct-afcdf00b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/sct-afcdf00b.log.tar.gz)
- **loader-set-afcdf00b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/loader-set-afcdf00b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/loader-set-afcdf00b.tar.gz)
- **monitor-set-afcdf00b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/monitor-set-afcdf00b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/afcdf00b-2ebd-4914-8b13-651493354d53/20240211_051301/monitor-set-afcdf00b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-twcs-48h-test/107/)
[Argus](https://argus.scylladb.com/test/ca1ac895-78c0-4abd-80d5-0ba6dc7844bf/runs?additionalRuns[]=afcdf00b-2ebd-4914-8b13-651493354d53)
</details>

**Comment by mykaul** [comment]
@tchaikov - please take a look.

**Comment by mykaul** [comment]
@enaydanov - why do we think the bug is on nodetool, when the API clearly failed?

**Comment by enaydanov** [comment]
@mykaul it's not clear which party need to handle this error. If you look at the suspicious change you will see removal of error handling code in `scylla-nodetool.cc`
