### ISSUE TITLE
Error: raft_topology - Removenode failed. See earlier errors (Canceled. Dead nodes should be a warning?

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#17327]
Scylla version 5.5.0~dev-0.20240211.13e16475fabb with build-id 155eca419cef95b6429a4ad42483e828be0ba4dc 

For dtest test: [test_simple_removenode_3](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/dtest_raft_topolgy/job/dtest-run-consistent-topology-issue-tests/16/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/FullDtest___full_split000___test_simple_removenode_3_api_True_/) next error found in log on raft topology coordinator node on teardown:
```
dtest-dixkuuph/test/node1/logs/system.log:ERROR 2024-02-14 03:49:41,078 [shard 0:strm] raft_topology - Removenode failed. See earlier errors (Canceled. Dead nodes: {162e4840-1d98-4ada-b628-c4c64c2c9309, 1b722a6e-c270-411e-a77b-b0a0dced016e, 87eaaf33-7532-45d6-97d7-91eb937a5206})
```

This error happened, when remove node operation called when 2 other nodes were stopped, but quorum is present, because cluster has 7 nodes..
cluster started with 7 nodes.
then stopped node2, node4 and node5 or node2 and node5. And removenode operation started without --ignore-node flag with host ids of stopped node

**Comment by kbr-scylla** [comment]
It's an expected error in this case -- but still an error, so we report it at `ERROR` level.

Besides, the code which reports it doesn't know the reason of failure (it "knows" it in the sense that it has the exception message only, but not the exception type).

I think you should ignore the pattern in the test.

**Comment by aleksbykov** [comment]
PR: https://github.com/scylladb/scylla-dtest/pull/3931

**Comment by temichus** [comment]
Job with 100 runs is passed: https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/73/testReport/

close this Issue
