### ISSUE TITLE
docs: Issue in left menu item: Alternator 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#17326]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.4/index

### Problem

Not sure why Alternator is at the end of the menu.

![image](https://github.com/scylladb/scylladb/assets/170200/f5c536ec-4471-4d8e-adad-0b4f68fd560b)

###  Suggest a fix

It make more sense to place it after CQL, or move both CQL and Alternator under ScyllaDB for Developers.

**Comment by nyh** [comment]
I'm closing this issue. In the master branch, https://opensource.docs.scylladb.com/master/index.html, Alternator is listed right next to CQL.

I doubt we'll want to go back to the 5.4 documentation and fix them (but if you do want to fix older versions, please reopen this issue.
