### ISSUE TITLE
test/rest_api breaks with tablets enabled

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#17338]
When run via `test.py`, this suite passes because `suite.yaml` doesn't enable tablets currently. However if tablets are enabled in `suite.yaml`, many tests break. The same happens if the tests are run with `run`, because this re-uses the run logic from `cql-pytest` suite which already enabled tablets.

**Comment by denesb** [comment]
To enable tablet support in `suite.yaml`, the following diff is needed:
```diff
diff --git a/test/rest_api/suite.yaml b/test/rest_api/suite.yaml
index 7fe0d46910..a1d90b3857 100644
--- a/test/rest_api/suite.yaml
+++ b/test/rest_api/suite.yaml
@@ -4,3 +4,8 @@ pool_size: 1
 skip_in_release:
     - test_task_manager
     - test_compaction_task
+
+extra_scylla_cmdline_options:
+  - '--experimental-features=udf'
+  - '--experimental-features=consistent-topology-changes'
+  - '--experimental-features=tablets'
```

Like I said above, when running the tests via `run`, tablets are already enabled by default.

**Comment by mykaul** [comment]
> ```diff
> +  - '--experimental-features=udf'
> ```

UDF?

**Comment by denesb** [comment]
> UDF?

It works with lowercase too.

**Comment by nyh** [comment]
Yes, but why do you need to enable UDF? Do any of the rest_api tests use UDF?

**Comment by mykaul** [comment]
> Yes, but why do you need to enable UDF? Do any of the rest_api tests use UDF?

That was my question, not the case.

**Comment by denesb** [comment]
Oh. For some reason, if I omit that line, Scylla refuses to start up, complaining that I need to also enable the experimental UDF features. I suppose some other component (probably the default command line args in cluster manager) enables the regular UDF feature, so now everybody has to pass the exprimental feature too.

**Comment by mykaul** [comment]
> Oh. For some reason, if I omit that line, Scylla refuses to start up, complaining that I need to also enable the experimental UDF features. I suppose some other component (probably the default command line args in cluster manager) enables the regular UDF feature, so now everybody has to pass the exprimental feature too.

Thanks - please open a seperate issue on this and let's fix it. I don't think we need to force UDF (which might have whatever issues) for other features to work.

**Comment by denesb** [comment]
> > Oh. For some reason, if I omit that line, Scylla refuses to start up, complaining that I need to also enable the experimental UDF features. I suppose some other component (probably the default command line args in cluster manager) enables the regular UDF feature, so now everybody has to pass the exprimental feature too.
> 
> Thanks - please open a seperate issue on this and let's fix it. I don't think we need to force UDF (which might have whatever issues) for other features to work.

I found a place, will send a fix soon.

**Comment by denesb** [comment]
> > > Oh. For some reason, if I omit that line, Scylla refuses to start up, complaining that I need to also enable the experimental UDF features. I suppose some other component (probably the default command line args in cluster manager) enables the regular UDF feature, so now everybody has to pass the exprimental feature too.
> > 
> > 
> > Thanks - please open a seperate issue on this and let's fix it. I don't think we need to force UDF (which might have whatever issues) for other features to work.
> 
> I found the place, will send a fix soon.

https://github.com/scylladb/scylladb/pull/17350

**Comment by bhalevy** [comment]
I'm not sure we have xfail for the rest_api tests, but ideally, any test that currently fails with tablets enabled due to getting the effective_replication_map from the keyspace, but we want to have the api support tablets eventually should be marked as xfail for the time being.

**Comment by denesb** [comment]
Yes, that could be a quick fix to get the ball rolling and allow adding tablets test to the suite.

**Comment by denesb** [comment]
And then we could follow-up with fixing the tests/APIs as needed.

**Comment by Deexie** [comment]
I opened a quick fix (https://github.com/scylladb/scylladb/pull/17400). I will continue working on the proper fixes
