### ISSUE TITLE
decommission could failed after node changed ip with error:  token_metadata - host_id for endpoint 127.0.95.33 is not found

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#17337]
Scylla version 5.5.0~dev-0.20240211.13e16475fabb with build-id 155eca419cef95b6429a4ad42483e828be0ba4dc 

We have dtest: update_cluster_layout_tests.py::TestUpdateClusterLayout::test_decommission_after_changing_node_ip.  This test is a bit flaky. 
Link to test : https://github.com/scylladb/scylla-dtest/blob/next/update_cluster_layout_tests.py#L2301

the test start with 3 nodes. then it stops node3. IP is changed to new one and settings of node3 are updated accordingly. Then node is started and once it up it is started to decommission.
But decommission could failed with next error:
```
ERROR 2024-02-14 18:03:22,702 [shard 0:strm] token_metadata - host_id for endpoint 127.0.95.33 is not found, at: 0x61baa7e 0x61bb090 0x61bb378 0x5c76b17 0x3ef1d1a 0x43562e8 0x4356145 0x60956a6
ERROR 2024-02-14 18:03:22,702 [shard 0: gms] raft_topology - raft_topology_cmd failed with: seastar::internal::backtraced<std::runtime_error> (host_id for endpoint 127.0.95.33 is not found Backtrace: 0x61baa7e 0x61bb090 0x61bb378 0x5380445 0x5380154 0x5c76bff 0x3ef1d1a 0x43562e8 0x4356145 0x60956a6)
ERROR 2024-02-14 18:03:22,726 [shard 0:strm] raft_topology - Decommission failed. See earlier errors (Rolled back: Failed stream ranges: std::runtime_error (failed status returned from 6090056c-9999-4a03-a618-6f0cd97f2e3b/127.0.95.33))
```
but according logs node started to listen new ip address

because this errors found on teardown or if remove retry_till_success it could fail test due to decommision command failure, test is marked as failed.
Issue happened periodically and not often. latest result 1 failed from 10.

logs: [logs.tar.gz](https://github.com/scylladb/scylladb/files/14278761/logs.tar.gz)

**Comment by aleksbykov** [comment]
with gossiper test is stable

**Comment by aleksbykov** [comment]
@kbr-scylla @gleb-cloudius may be we need wait some log message, before start decommission?

**Comment by gleb-cloudius** [comment]
@gusev-p any hints?

**Comment by aleksbykov** [comment]
and unfortunately i coudn't decode the backtrace, Do we need it in log?

**Comment by gleb-cloudius** [comment]
> and unfortunately i coudn't decode the backtrace, Do we need it in log?

It would have been nice.

**Comment by kbr-scylla** [comment]
I'm putting it in the backlog, @gusev-p @gleb-cloudius don't investigate it now.
Let's retest once https://github.com/scylladb/scylladb/pull/17162 is merged

**Comment by gusev-p** [comment]
> @gusev-p any hints?

I'm currently fixing exactly that (https://github.com/scylladb/scylladb/issues/17199)

**Comment by gleb-cloudius** [comment]
So this is a dup?

**Comment by aleksbykov** [comment]
Yes, it looks same, but without coredump
