### ISSUE TITLE
raft topology: document the recovery and upgrade procedures

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17341]
Upgrade: when cluster is upgraded from 5.4 to 6.0 (for example), it won't automatically switch to raft-topology mode. The procedure to switch to raft-topology mode has to be manually triggered and monitored by the cluster administrator.

Clusters bootstrapped from scratch in 6.0 won't need to go through this procedure, but see below.

---

Recovery: in case of majority loss, administrator needs to go through manual Raft group 0 recovery procedure. We already have it in 5.4 and 5.2 if Raft is enabled (https://opensource.docs.scylladb.com/stable/architecture/raft.html#raft-manual-recovery-procedure), but if one wants Raft-topology mode, it needs to be extended with the extra step to trigger the Raft-topology switch (the exact same one as described above); and that step is in fact mandatory if the cluster was using Raft-topology specific features before losing majority (such as tablets.)

**Comment by tzach** [comment]
> Upgrade: when cluster is upgraded from 5.4 to 6.0 (for example), it won't automatically switch to raft-topology mode. The procedure to switch to raft-topology mode has to be manually triggered and monitored by the cluster administrator.


This is unfortunate and will make the upgrade harder.
In this case, the cluster should not be fully functional before moving to raft-topology mode.

**Comment by kbr-scylla** [comment]
> This is unfortunate and will make the upgrade harder.

It's something we want to improve in follow-up release. We made it manual for now to simplify the implementation (so we can deliver earlier).

>  In this case, the cluster should not be fully functional before moving to raft-topology mode.

Curious -- when we designed and implemented the upgrade procedure, we actually took care for the cluster to remain functional. The data path definitely has to work of course to not disrupt applications. But the implementation also takes care for topology changes and schema changes to remain functional; when a node joins, it consults the cluster to see whether to use gossiper-based topology procedure or the new raft-topology-coordinator-based one. (cc @piodul)

We'll need to consult such decisions better in the future. It would've simplified @piodul's life a lot.

(cc @avikivity, @mykaul)

**Comment by tzach** [comment]
You suggest to make raft-topology mode opt-in. 
This make sense, and we did it with raft-schema mode in 5.2, but AFAIU, will also makes Tablets opt-in.
Is it the case?

**Comment by kbr-scylla** [comment]
> You suggest to make raft-topology mode opt-in.

For upgraded clusters yes -- not for new clusters.

>  This make sense, and we did it with raft-schema mode in 5.2, but AFAIU, will also makes Tablets opt-in.
> Is it the case?

Yes, the implementation of tablets is built on top of the raft-topology coordinator.
