### ISSUE TITLE
build.ninja is ridiculously large, avoid repeating long list of dependencies

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#17361]
As of this writing, the **build.ninja** file that our configure.py generates is 66 MB (!) in size, which is roughly the size of the first hard disk I used ;-) I think this size also causes ninja startup to take almost a second (e.g., try "time ninja zzz" and see how much time it needs to think before it can print an error).

The problem is that we have a huge number of test targets, and each one has a full list of hundreds of dependencies. For example:

> build $builddir/debug/test/boost/auth_passwords_test: link_stripped.debug $builddir/debug/test/boost/auth_passwords_test.o $builddir/debug/message/messaging_service.o $builddir/debug/replica/database.o $builddir/debug/replica/table.o $builddir/debug/replica/tablets.o $builddir/debug/replica/distributed_loader.o $builddir/debug/replica/memtable.o $builddir/debug/replica/exceptions.o....

The reason for this is that we have in configure.py lines like:
```python
for t in sorted(scylla_tests):
    deps[t] = [t + '.cc']
    if t not in tests_not_using_seastar_test_framework:
        deps[t] += scylla_tests_dependencies
    else:
        deps[t] += scylla_core + alternator + idls + scylla_tests_generic_dependencies
```

This inserts into the dependency list of each test a long list of Scylla source files. A better approach would be to insert variable interpolations, e.g., `$scylla_core`, and set `scylla_core` just once in build.ninja. Actually, it's a bit more complicated that that - configure.py's "deps" is source files, and we'll need the per-mode list of _object_ files, but that's also easy - we just need to set three variables `$scylla_core_debug`, `$scylla_core_dev`, `$scylla_core_release`, and in the rule for each mode use the right variable.

This change will not only make build.ninja much smaller and hopefully ninja startup speedier (I'm saying "hopefully" because I hope it doesn't interpolate variables when it reads builds.ninja), but it will also make build.ninja somewhat possible to read and understand - which today it isn't.

**Comment by avikivity** [comment]
Please don't work on it, we're migrating to cmake.

**Comment by nyh** [comment]
> Please don't work on it, we're migrating to cmake.

I think cmake is even worse and don't understand why anybody would choose to use it, but I agree that if it was already decided, then this issue is moot.

**Comment by nyh** [comment]
FYI, almost half a year later, build.ninja has grown to 71 MB, and we're no closer to dropping it.

**Comment by avikivity** [comment]
71 MB is just a number.

**Comment by nyh** [comment]
I'm reopening this issue. Let's close the configure.py-related issues when we finally switch to cmake... In the meantime it's been two and a half years since the comment "we're migrating to cmake" in https://github.com/scylladb/scylladb/issues/17361#issuecomment-1947061596 and we still haven't done it. And build.ninja continues to grow:

```
$ ls -lh build.ninja
-rw-r--r--. 1 nyh nyh 80M Aug 28 14:23 build.ninja
```

**Comment by avikivity** [comment]
I don't see the issue. Is it wasteful? Yes it is. Will anyone notice if we reduce it by a factor of 10? No. 80MB is 40ppm of my 2TB disk.

I don't want to encourage waste, but this is affecting maybe 100 people in a unnoticable way.

**Comment by nyh** [comment]
> I don't see the issue. Is it wasteful? Yes it is. Will anyone notice if we reduce it by a factor of 10?

I gave two examples of how it is noticable (if you're nice convinced by the "it's bigger than my first hard disk" argument ;-)):
1. An almost one-second delay on running tests because test.py runs "ninja mode_list". Not to mention this one-second delay on any ninja execution.
2. It's virtually impossible to **look** at build.ninja and see anything under the mountains of dependency lists, or even search for specific files. This frustrates me every time I try to debug a build problem.

> No. 80MB is 40ppm of my 2TB disk.

You got the VIP hard disk - my laptop has just 0.4 TB :-)

> I don't want to encourage waste, but this is affecting maybe 100 people in a unnoticable way.

I never said we should throw all our developers on this issue - this was supposed to be a trivial fix (do variable interpolation in build.ninja instead of the Python configure.py). I think it shouldn't take more than an hour work. And when done, I can see how it affects the run times - there's a risk that the variable interpolation will still be slow and it won't help :-(

**Comment by nyh** [comment]
Another example of how the build.ninja is inflated is the line printed for every single object file, and we have more than 800 of those times 4 modes:
```
f.write(f'build {obj}: {cxx_cmd}.{mode} {src} | {profile_dep} || {seastar_dep} {abseil_dep} {gen_headers_dep} {pch_dep}\n')
```
This includes a literal copy of the list of all the bazillion abseil libraries we use, and a list of a bazillion generated header files, over 5000 characters. This is ridiculous, but explains "just" 16MB (800 times 5000 times 4 modes) of the 80 MB.

It's also, sadly, not easy to fix and I'm **not** going to continue working on it today. The "obvious" fix is to do something like
```
f.write(f'build {obj}: {cxx_cmd}.{mode} {src} | {profile_dep} || $seastar_dep_{mode} {abseil_dep} {gen_headers_dep} {pch_dep}\n')
```
I.e., make "seastar_dep_{mode}" a ninja variable (set once) instead of interpolating it into every line. But it doesn't work, the script /home/nyh/scylla/./scripts/merge-compdb.py croaks on this output, and I don't understand why.

**Comment by avikivity** [comment]
> 
> I never said we should throw all our developers on this issue - this was supposed to be a trivial fix (do variable interpolation in build.ninja instead of the Python configure.py). I think it shouldn't take more than an hour work. And when done, I can see how it affects the run times - there's a risk that the variable interpolation will still be slow and it won't help :-(

It will be measurable, but irrelevant for human timescales.
