### ISSUE TITLE
Add an option for test.py to enable tablets

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#17406]
Currently tablet is enabled in the code on a per test suite basis.
See for example 6defcb7bd55c4ccd752297ad77df7a4200e42b37, 04881b391523afbeebb0678fd24bce30ee9f7273
For testing automation we would to be able to enable tablets for all non-boost unit tests using a command line option to test.py so that we can run that automatically in a periodic test job and later in CI.

**Comment by bhalevy** [comment]
@nyh is this something you're familiar enough with and can take it?

**Comment by bhalevy** [comment]
@tchaikov please look into this issue.

**Comment by tchaikov** [comment]
ack. i am on it.

**Comment by nyh** [comment]
> Currently tablet is enabled in the code on a per test suite basis. See for example [6defcb7](https://github.com/scylladb/scylladb/commit/6defcb7bd55c4ccd752297ad77df7a4200e42b37), [04881b3](https://github.com/scylladb/scylladb/commit/04881b391523afbeebb0678fd24bce30ee9f7273) For testing automation we would to be able to enable tablets for all non-boost unit tests using a command line option to test.py so that we can run that automatically in a periodic test job and later in CI.

@bhalevy the cql-pytest, alternator and topology_experimental_raft and perhaps a few more already enable tablets experimental mode by default. So which subdirectories were you thinking about when suggesting to add this option?

Why don't these subdirectories do exactly what we did in cql-pytest at al., which is to enable experimental raft, by default, without an option - and deal with the fallout immediately? Why does "--tablets" need to be an **option** if anyway the intention in the very short term is to make it the default?

I can understand why we need this option in dtest, with dozens of failing tests that nobody knows how to fix. This is not the situation with test.py!

So personally, I wouldn't add this "--tablets" option to test.py - I would do what we did in cql-pytest and the rest: Make experimental-tablets the default in all tests when it's relevant (even cql and boost, which do NOT use Scylla!), and if we need, add the reverse option "--vnodes", if (in the short term) someone wants to check if something got broken in vnodes.

**Comment by bhalevy** [comment]
> > Currently tablet is enabled in the code on a per test suite basis. See for example [6defcb7](https://github.com/scylladb/scylladb/commit/6defcb7bd55c4ccd752297ad77df7a4200e42b37), [04881b3](https://github.com/scylladb/scylladb/commit/04881b391523afbeebb0678fd24bce30ee9f7273) For testing automation we would to be able to enable tablets for all non-boost unit tests using a command line option to test.py so that we can run that automatically in a periodic test job and later in CI.
> 
> @bhalevy the cql-pytest, alternator and topology_experimental_raft and perhaps a few more already enable tablets experimental mode by default. So which subdirectories were you thinking about when suggesting to add this option?
> 
> Why don't these subdirectories do exactly what we did in cql-pytest at al., which is to enable experimental raft, by default, without an option - and deal with the fallout immediately? Why does "--tablets" need to be an **option** if anyway the intention in the very short term is to make it the default?
> 
> I can understand why we need this option in dtest, with dozens of failing tests that nobody knows how to fix. This is not the situation with test.py!
> 
> So personally, I wouldn't add this "--tablets" option to test.py - I would do what we did in cql-pytest and the rest: Make experimental-tablets the default in all tests when it's relevant (even cql and boost, which do NOT use Scylla!), and if we need, add the reverse option "--vnodes", if (in the short term) someone wants to check if something got broken in vnodes.

Does that mean we stopped testing the above unit tests with consistent-topology-changes / tablets disabled?
Is that really desired?  consistent-topology-changes and tablets, even when enabled by default, can still be disabled by users, right? So how can we not test that?

Since tablets can be controlled when creating the keyspace one can still run with tablets enabled and not use tablets in practice, so in theory we can require consistent-topology-changes and tablets to always be enabled and not support disabling them, otherwise, we need to continue to test scylla with them also disabled.

**Comment by nyh** [comment]
> Does that mean we stopped testing the above unit tests with consistent-topology-changes / tablets disabled? Is that really desired? consistent-topology-changes and tablets, even when enabled by default, can still be disabled by users, right? So how can we not test that?

The thinking was that **most** tests have absolutely no relation to tablets - e.g., the single-node tests that check check CQL's casting expressions don't care if the keyspace uses tablets or vnodes. 

Some specific tests which we know are different in tablets and vnodes (e.g., DESC CLUSTER test) run twice, with and without tablets. 

In the past I suggested the possibility that **Jenkins** should run the entire test suite twice, once with tablets and once without. But it was deemed excessive and never done.

**Comment by nyh** [comment]
> @nyh Hi Nadav, i think tablets is a machinery which impacts quite a few perspectives of scylla cluster in a profound way. and in a relatively long time span, tablet will be an optional feature unless we decide to always enable it since the first day of its GA. so i concur with Benny that to parameterize it when performing relevant tests would be important for us to keep existing vnode working _and_ to be aware of the status of tablet support.

We already have a way to run specific tests both with tablets and without (and we used it in a few places). I think Benny suggests we need to go further - and run most tests - perhaps except single-node tests - topology tests, dtests, etc., both with and without tablets. I agree. But I claim this (running all tests twice) should be done in the level of Jenkins, **NOT** in the level of test.py or dtest's pytest. When I run a single test during development, I don't want it to be run twice.


> and in light of that we could have some other experimental features in future, i propose the `--experimental-features` option in #17446.

I'm not sure how how the two suggestions (Benny's and yours) are different other than the name of the option. Both of them suffer from the problem I mentioned: We actually decided (and already implemented in some of the test suites) that the default should be **with** tablets, and an option (e.g., "--vnodes") could be used to turn the experimental feature **off**, not turn it on.

**Comment by bhalevy** [comment]
Closing until proven as needed
