### ISSUE TITLE
can't connect new node after dead node was removed

### ISSUE THREAD

**Issue by oturek** [scylladb/scylladb#17404]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2.9-0.20230920.5709d0043978-1
Cluster size: 4 nodes 
[cluster-log.txt](https://github.com/scylladb/scylladb/files/14334273/cluster-log.txt)
[health-check.txt](https://github.com/scylladb/scylladb/files/14334274/health-check.txt)
[node-log.txt](https://github.com/scylladb/scylladb/files/14334275/node-log.txt)

OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 22.04

**Comment by mykaul** [comment]
The cluster log (where is it coming from?) is a bit shy in details:
```
Feb 19 15:35:51 scylla-bm-node2 scylla[5147]:  [shard  0] raft_group_registry - Raft server id c3af2f4e-b70a-4d14-8467-3f52d518963f cannot be translated to an IP address.
Feb 19 15:36:16 scylla-bm-node2 scylla[5147]:  [shard  2] gossip - failure_detector_loop: Send echo to node 10.10.26.15, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Feb 19 15:36:16 scylla-bm-node2 scylla[5147]:  [shard  2] rpc - client 10.10.26.15:7000: client connection dropped: connection is closed
```

Can you share more details? How did you perform the replace, what was the IP of the old node, the new node, etc.?

**Comment by mykaul** [comment]
This is interesting, from the node log:
```
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]: scylla: schema.cc:368: schema::schema(schema::private_tag, const schema::raw_schema &, std::optional<raw_view_info>): Assertion `!def.id || def.id == id - column_offset(def.kind)' failed.
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]: Aborting on shard 0.
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]: Backtrace:
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x4ff41f8
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x5026632
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x3cb1f
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x8ce5b
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x3ca75
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x267fb
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x2671a
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x35655
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x1af7c9b
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x1afb064
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x3172f43
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x31d62bc
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x31d3488
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x31b7373
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x323cb2d
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x1201fba
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x5004a74
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x5005cf7
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x5005039
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x4fabaf5
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x4faac68
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x1148d34
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x114a840
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x114746a
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x2750f
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   /opt/scylladb/libreloc/libc.so.6+0x275c8
Feb 19 14:35:53 scylla-bm-node3 scylla[20205]:   0x1145624
```

**Comment by mykaul** [comment]
Which is identical to https://github.com/scylladb/scylladb/issues/16683#issuecomment-1884353511 , I think.

**Comment by oturek** [comment]
> The cluster log (where is it coming from?) is a bit shy in details:
> 
> ```
> Feb 19 15:35:51 scylla-bm-node2 scylla[5147]:  [shard  0] raft_group_registry - Raft server id c3af2f4e-b70a-4d14-8467-3f52d518963f cannot be translated to an IP address.
> Feb 19 15:36:16 scylla-bm-node2 scylla[5147]:  [shard  2] gossip - failure_detector_loop: Send echo to node 10.10.26.15, status = failed: seastar::rpc::timeout_error (rpc call timed out)
> Feb 19 15:36:16 scylla-bm-node2 scylla[5147]:  [shard  2] rpc - client 10.10.26.15:7000: client connection dropped: connection is closed
> ```
> 
> Can you share more details? How did you perform the replace, what was the IP of the old node, the new node, etc.?

Hi, 
old IP - 10.10.26.13
How i removed:
- nodetool drain
- nodetool removenode <node ID>


tryded to add new node with ip 10.10.26.13
then after same issue: 
 -found ghost member id
 - nodetool removenode <ghost member id>


tryied to add with ip 10.10.26.15

This log got from other node with:  journalctl  _COMM=scylla

**Comment by oturek** [comment]
> see if it's still

Hi, the same problem with 5.2.15

**Comment by mykaul** [comment]
@kbr-scylla - can someone from your team look at this?
@oturek - can you please share more complete logs? Snippets sometimes lack critical information.

**Comment by oturek** [comment]
> @kbr-scylla - can someone from your team look at this? @oturek - can you please share more complete logs? Snippets sometimes lack critical information.

sure, here is syslog and journalctl from node I've tryied to connect
[scylla-node3-syslog.txt](https://github.com/scylladb/scylladb/files/14359664/scylla-node3-syslog.txt)
[journalctl-node3.txt](https://github.com/scylladb/scylladb/files/14359717/journalctl-node3.txt)
log from alive node:
[alive-node-log.txt](https://github.com/scylladb/scylladb/files/14359774/alive-node-log.txt)

@mykaul what cat I  share more?

**Comment by mykaul** [comment]
The alive node is only 10-15 lines or so, I'm not sure it's sufficient. Let's see.

**Comment by oturek** [comment]
sorry, log from 6am:
[alive-node2-log.txt](https://github.com/scylladb/scylladb/files/14360107/alive-node2-log.txt)

**Comment by oturek** [comment]
@kbr-scylla no, cluster wasn't updated to 5.2.15 (tested before on test cluster if node with version 5.2.15 is able to connect to cluster with version 5.2.1 and there was no problem)
health reports:
[node1.zip](https://github.com/scylladb/scylladb/files/14364161/node1.zip)
[node3.zip](https://github.com/scylladb/scylladb/files/14364186/node3.zip)
[node4.zip](https://github.com/scylladb/scylladb/files/14364196/node4.zip)
[node2-part1.zip](https://github.com/scylladb/scylladb/files/14364372/node2-part1.zip)
[node2-part2.zip](https://github.com/scylladb/scylladb/files/14364376/node2-part2.zip)

sorry, node 2 scylla-logs.txt.gz I've split on two patrs( scylla-logs.txt.gz.part-aa and scylla-logs.txt.gz.part-ab, because one file was too big to upload here)

**Comment by kbr-scylla** [comment]
@oturek in that case please upgrade your cluster to 5.2.15 before trying to join the node again, it contains important fixes which should eliminate the crash you're seeing.

**Comment by oturek** [comment]
> @oturek in that case please upgrade your cluster to 5.2.15 before trying to join the node again, it contains important fixes which should eliminate the crash you're seeing.

thx, @kbr-scylla I'll back with the result

**Comment by mykaul** [comment]
@oturek - any news?

**Comment by oturek** [comment]
Hi, sorry for delay, finally connected with version 5.2.9( it was last try) before upgrading to 5.2.15 :)
Thanks for support, I'll close the issue.
