### ISSUE TITLE
Need materialized-view admission control

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#17426]
MV flow control slows down a _batch client_ (see definitions and discussion in https://www.scylladb.com/2018/12/04/worry-free-ingestion-flow-control/), i.e., a client that has a fixed concurrency. Such a client would be slowed down  to the rate that will keep memory use capped.  

However, an "interactive" client with an unlimited concurrency could keep sending new requests without previous one ever completing. At some point we need to give up on attempting flow control and start doing **admission control** (again, see the above link for explanation). This issue is about verify (in the code, and with a test) that this admission control actually works, and if not (and I suspect it doesn't) - add it. In other words, we should not admit new MV writes on a coordinator if the backlog of the replica nodes  is already past 100% of what we want it to be.

We do have CQL-level admission control, but I think it only accounts outstanding CQL requests, and not the fact that all the CQL requests might be done (because they only wait for the base writes) but we're accruing a bigger and bigger view update backlog. The newly admitted CQL requests, if they are writes to a base table, may allow the view update backlog to grow without limit.

**Comment by mykaul** [comment]
Anything that we can combine with https://github.com/scylladb/scylladb/blob/master/docs/dev/per-partition-rate-limit.md ?

**Comment by nyh** [comment]
@mykaul I'm not sure how it's related. The view update backlog isn't per partition, and we already account it (we didn't account it enough for small updates, this will be fixed in #17364). If a coordinator needs to send a write to a table with a view to replica R and it knows replica R already has a very large backlog (e.g., more than 10% of memory), it knows it shouldn't send this write, and better just fail the entire request immediately. Obviously, the idea is that the flow-control will slow the client before we reach that 10% level, but if we already reach it it means the client is ignoring the flow control (i.e., it has unlimited concurrency) and we don't have much of an alternative except to refuse new requests.

**Comment by mykaul** [comment]
Imagined interface:
```
ALTER TABLE ks.tbl WITH per_materialized_view_rate_limit = {
    'max_reads_per_second': 123,
    'max_writes_per_second': 456
```

**Comment by tzach** [comment]
> ALTER TABLE ks.tbl WITH per_materialized_view_rate_limit = {
>     'max_reads_per_second': 123,
>     'max_writes_per_second': 456

This is bad UX. How should one guess what values to use here?

**Comment by wmitros** [comment]
@nyh we have something that acts as the admission controller at https://github.com/scylladb/scylladb/blob/3a734facc7476a949ecadf5f98bccb00f8d0c9cb/replica/table.cc#L3212-L3220
This, however, instead of rejecting requests, skips generating and applying view updates, apparently to avoid inconsistencies between base replicas. Until https://github.com/scylladb/scylladb/pull/17420 this could never be triggered, so the decision to drop writes didn't matter, but now when this code is actually reachable we can decide to either commit to it or replace it with something like https://github.com/scylladb/scylladb/pull/17777

**Comment by nyh** [comment]
@wmitros you're right that for very small updates whose size was badly underestimated, we wouldn't have reached this case, but I believe that we definitely were able to reach it when this code was added by Duarte, some six years ago. Maybe we still need this case as some sort of emergency fail-safe (do we?), but it's the wrong code at the wrong place: We need to fail the user's write at the coordinator - not fail a single replica write (for reasons the comment explains) and certainly not silently fail only the view write as we do today (because this leads to the dreaded base-view inconsistencies).

If I remember correctly, getting rid of exactly the piece of code you quoted was on Eliran's list of things to get rid of to improve the base-view consistency.

**Comment by nyh** [comment]
In https://github.com/scylladb/scylla-dtest/issues/4115 we mentioned another situation where admission control is needed:

Consider a workload where the server is slow enough or the individual writes are large enough (e.g., many rows) or other details conspire (e.g., all view updates go to the same shard, many views, etc.), that the server can only finish the view updates of 100 requests per second. Now imagine that the client has concurrency of 200, so the average latency each request + all view updates will be 2 whole seconds. At such latencies, our flow control sleep (which is capped at 1 second when the view backlog reached 10% of memory) will not be able to slow the client down significantly, and the queue will continue growing. We need to start rejecting requests when that happens.

Today, we do have something close to admission control, but not exactly what is asked in this issue: The coordinator doesn't reject new requests, but they are rejected on individual base replicas where the view update backlog is too large. If this happens on only one node, the write request may succeed (with one base replica not updated, and will be repaired later). This is better than nothing - it still prevents memory overflow once we reach the 10% limit - but it is not the coordinator-side admission control I was asking for in this issue.
