### ISSUE TITLE
[dtest] test_replace_node_same_ip_take_write: AssertionError with raft topology

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#17421]
The test become flaky again with same errors if it runs with raft topology feature as described in #16963 .
Results are here: https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/Dtest/job/master-dtest-with-raft/61/testReport/
PR which allow to run it : https://github.com/scylladb/scylla-dtest/pull/3934

```
>       assert writes_when_replace_ops_done - writes_when_replace_ops_started > writes_diff_cnt
E       assert (511 - 479) > 125.0

replace_address_test.py:1000: AssertionError
```

---

Edit from kbr-scylla:
The test is sometimes failing with another error too
```
E   cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1" info={'consistency': 'QUORUM', 'required_replicas': 2, 'alive_replicas': 1}
```

while the above assertion is not unexpected, the write failures are and that needs to be definitely investigated.

I expected such failures to be fixed by https://github.com/scylladb/scylladb/commit/5ef47c42b3639c8490c3b5dbc171abd00f44801c (https://github.com/scylladb/scylladb/issues/17445) but apparently it's something else, or the fix is not complete

**Comment by kbr-scylla** [comment]
Previous fix: fa472d57f2b6c681ece40054ac141f3c449be494

perhaps the timings changed again in raft-topology mode.

**Comment by kbr-scylla** [comment]
@bhalevy @asias I believe it is just another incarnation of https://github.com/scylladb/scylladb/issues/16963. In raft-topology, topology changes are faster -- so the test's inherent nondeterminism (based on timing) just comes out again.

Could I leave it to you to look at this test?

Or perhaps, we should just take it out of gating.

**Comment by bhalevy** [comment]
We shouldn't ahve flaky tests in gating.
So we need to stabilize the test (like allowing a very low threshold of any writes) or take it out of gating until it's stabilized.

**Comment by kbr-scylla** [comment]
Hm, but in raft-topology mode we're seeing something that does not happen outside raft-topology:
```
19:26:24,031 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,031 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,031 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,031 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,032 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,032 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,032 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,032 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,032 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,033 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
19:26:24,033 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_disabled]: Retrying request after UE. Attempt #0
```

Possible cause: scylladb/scylladb#17445, which was fixed by 5ef47c42b3639c8490c3b5dbc171abd00f44801c

I need to rerun the test with that fix

**Comment by kbr-scylla** [comment]
> Possible cause: https://github.com/scylladb/scylladb/issues/17445, which was fixed by https://github.com/scylladb/scylladb/commit/5ef47c42b3639c8490c3b5dbc171abd00f44801c

I reran on 6bdb456fadfef65d9719069a5f43ad376ffa9d2d and it's still happening
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/dtest_raft_topolgy/job/dtest-full-with-consistent-topology-changes/34/artifact/logs-full.release.002/dtest-gw0.log
```
08:36:45,051 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
08:36:45,051 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
08:36:45,051 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
08:36:45,051 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
08:36:45,052 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
08:36:45,052 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
08:36:45,052 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
08:36:45,053 793     dtest_class                    DEBUG    dtest_class.py      :45   | test_replace_node_same_ip_take_write[use_host_id-rbo_enabled]: Retrying request after UE. Attempt #0
```

It looks like the test sometimes fails not due to the assertion, but due to write failure
```
E   cassandra.Unavailable: Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1" info={'consistency': 'QUORUM', 'required_replicas': 2, 'alive_replicas': 1}
```

we should investigate that

**Comment by kbr-scylla** [comment]
Marking as release blocker due to the write failures

**Comment by kbr-scylla** [comment]
In runs that fail with the metric comparison assertion error, we also see some retries of the writes due to UAE -- I suspect that these retries are what causes fewer writes to be made in total during the test.

**Comment by gusev-p** [comment]
I'm not sure I understand [this condition](https://github.com/scylladb/scylladb/blob/101fdfc33aec152a1a686a322bda6d5d748bc978/db/consistency_level.cc#L224). Does it suppose that pending endpoints are live?

In our case .5 is pending and dead:
`INFO  2024-03-26 17:47:06,221 [shard 0:stmt] storage_proxy - HUJ assure_sufficient_live_nodes error exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1) live: {127.0.79.1, 127.0.79.4} dead: {127.0.79.5}, table=ks.cf`
so this condition is true (`2 < 2 + 1`).

**Comment by gusev-p** [comment]
the test passes in gossiper mode with --count 10 and the following log entry is never written
```
for (const auto& e: pending_endpoints) {
        if (!is_alive(e)) {
            slogger.info("DBG pending_endpoint {} is not alive, table={}.{}",
                e, s->ks_name(), s->cf_name());
        }
    }
```

**Comment by gusev-p** [comment]
something probably guarantees that in `node_ops_cmd::bootstrap_prepare` handler `gossiper.is_alive(endpoint) == true`

**Comment by gusev-p** [comment]
hmm, not `node_ops_cmd::bootstrap_prepare`, but `node_ops_cmd::replace_prepare`. There is actually a separate command `node_ops_cmd::replace_prepare_mark_alive`  which does `_gossiper.wait_alive`. This command is invoked by `run_replace_ops` after `replace_prepare`, so there is actually a small window where the same problem can occur, but all this happens before streaming, so this is much less likely than in raft mode.

**Comment by gusev-p** [comment]
We mark a replacing node as pending/bootstrapping as soon as topology coordinator transitions to `transition_state::join_group0`. This is the moment we start getting `unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1)`. On the other hand, the replacing node starts advertising itself only in `join_node_response_params::accepted` handler. This happens as the first step when topology coordinator starts handling `transition_state::join_group0`, but it's too late already.

**Comment by kbr-scylla** [comment]
I'm curious why we're not seeing similar write failures in our test.py test_topology_ops, which also does writes in the background while performing topology operations. cc @patjed41

**Comment by kbr-scylla** [comment]
> I'm not sure I understand [this condition](https://github.com/scylladb/scylladb/blob/101fdfc33aec152a1a686a322bda6d5d748bc978/db/consistency_level.cc#L224). Does it suppose that pending endpoints are live?
> 
> In our case .5 is pending and dead: `INFO 2024-03-26 17:47:06,221 [shard 0:stmt] storage_proxy - assure_sufficient_live_nodes error exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1) live: {127.0.79.1, 127.0.79.4} dead: {127.0.79.5}, table=ks.cf` so this condition is true (`2 < 2 + 1`).

The error message for `unavailable_exception` is completely confusing, especially with this `adjust_live_for_error` thing. Why did C* devs decide to design it like this, instead of returning pending in `unavailable_exception` and having the driver do the necessary adjustments for `DowngradingConsistencyRetryPolicy`...

Anyway

Apparently, we have RF=3 table, doing QUORUM operation, so normally we require 2 replicas to answer
But while there is a pending replica, the number of required replicas increases by 1.
So we require 3 alive replicas to answer.

Here we have 2 live normal replicas, 1 dead pending. So in total we only have 2 alive replicas.

Dunno if that explains sufficiently.

The error should say "Requires 3, alive 2", would be much less confusing.

**Comment by kbr-scylla** [comment]
>I'm curious why we're not seeing similar write failures in our test.py test_topology_ops, which also does writes in the background while performing topology operations. cc @patjed41

Ah, because we don't replace with same IP?

**Comment by kbr-scylla** [comment]
So during our discussion on the daily, we determined there's a bug in gossiper code as well.
The gossiper path bug causes potential consistency loss. The raft-topology path bug we're dealing with here causes availability loss.

On gossiper path:
```cpp
        // Step 4: Allow nodes in sync_nodes list to mark the replacing node as alive
        _gossiper.advertise_to_nodes(sync_nodes_generations).get();
        slogger.info("replace[{}]: Allow nodes={} to mark replacing node={} as alive", uuid, ctl.sync_nodes, get_broadcast_address());

        // Step 5: Wait for nodes to finish marking the replacing node as live
        ctl.send_to_all(node_ops_cmd::replace_prepare_mark_alive).get();

        // Step 6: Update pending ranges on nodes
        ctl.send_to_all(node_ops_cmd::replace_prepare_pending_ranges).get();
```

Between marking replacing node as alive by other nodes, and preparing pending ranges, we start writing to the replacing node, but without increasing CL. Thus we may ACK writes without achieving necessary CL. This is very hard to catch by tests.

Specifically, suppose we have 3 replicas {A, B, C}, C is dead, and new node D is replacing C.
Before the replace, QUORUM ops succeed after writing to {A, B}
During replace:
- before preparing pending ranges, QUORUM ops may succeed after writing to {A, D} or {B, D}
- after preparing pending ranges, QUORUM ops need to write to {A, B, D} to succeed.

So in that small period before preparing pending ranges, we're acking writes too early.

cc @asias @gleb-cloudius 


On the other hand, in raft-topology mode, the replacing node is marked as alive **after** we prepare pending ranges.
This causes availability loss during the window between preparing pending ranges and marking it as alive.

The correct solution is to do these two events at the same time on each node --- when a node sees that the node obtains pending ranges, it needs to **atomically** mark it as alive.

**Comment by gusev-p** [comment]
> Between marking replacing node as alive by other nodes, and preparing pending ranges, we start writing to the replacing node, but without increasing CL. Thus we may ACK writes without achieving necessary CL. This is very hard to catch by tests.

That's not true -- `node_ops_cmd::replace_prepare` doesn't make a new node pending, it only adds a replacing endpoint. The `node_ops_cmd::replace_prepare_pending_ranges` command calls `update_topology_change_info`, only here the replacing endpoint becomes pending, and this happens after `_gossiper.wait_alive`.

**Comment by gleb-cloudius** [comment]
It looks like the gossiper is fine. It first marks the dead node as "bein replaced" and from that point one it is not used for reads and writes since those use `get_natural_endpoints_without_node_being_replaced`. Then it waits for new node to be UP and only after that it adds it as pending (only at this point CL is elevated).
