### ISSUE TITLE
Allow disabling tablet balancing for a given table

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#17435]
Commit  d1c1b592362ce6d5f0e94828b390b042e65cf758 added support of disabling load balance for the whole cluster.  It will be useful if we could control per table. 

For example, when scylla manager wants to schedule repair for a given table, it can disable the migration of the given table instead of all tables. Schedule repair on different nodes without worrying the token ownership changes in the middle. Enable the migration of the table. Move to work on next table. 

```
commit d1c1b592362ce6d5f0e94828b390b042e65cf758
Author: Tomasz Grabiec <tgrabiec@scylladb.com>
Date:   Wed Nov 22 18:22:39 2023 +0100

    storage_service, api: Add API to disable tablet balancing
    
    Load balancing needs to be disabled before making a series of manual
    migrations so that we don't fight with the load balancer.
    
    Also will be used in tests to ensure tablets stick to expected locations.
```

**Comment by mykaul** [comment]
(assuming for the time being we can defer this to 6.1)

**Comment by asias** [comment]
> (assuming for the time being we can defer this to 6.1)

For 6.0, if we think scylla manager disable the tablet migration for the whole cluster is good enough when scheduling and running repair, we can defer this to 6.1.

We do not have this per table control infrastructures currently. So I think we have to defer to 6.1.

**Comment by tzach** [comment]
> For example, when scylla manager wants to schedule repair for a given table, it can disable the migration of the given table instead of all tables. 


Is running repair during migration an actual limitation of tablets?
If so, it makes sense to fail it in Scylla Core.

**Comment by asias** [comment]
> > For example, when scylla manager wants to schedule repair for a given table, it can disable the migration of the given table instead of all tables.
> 
> Is running repair during migration an actual limitation of tablets? If so, it makes sense to fail it in Scylla Core.

We need a way to coordinate tablet migration and repair jobs requested by the management tool. For example, scylla manager think a range of tablet is owned by n1 and n2, so it schedules a repair on n1 and n2. But the tablet is migrated to n3 and n4.  Repair on n1 and n2 will not repair the range. On one hand,  this is not the end of the world when a range is not repaired due to the migration, it can be repaired until the next repair. On the other hand, if we disable the migration, we can make sure the range is repaired. 

In the long term, we will move the repair scheduling inside scylla core to integrate better with tablet. But this will not be in the initial tablet release.

**Comment by tgrabiec** [comment]
Disabling load balancing of a single table can lead to bad balance, which makes me think it's more trouble than it's worth.

For example, suppose you have 2 tables and N nodes, and add a new empty node. If one table is pinned, load balancer will fill the new node with tablets of the other table, and that node will own more tablets of that table than other tables. That violates even per-table distribution - if that unpinned table is hot, the new node will be overloaded. There currently no code in the load balancer to fix that when the cold table is unpinned.

**Comment by tchaikov** [comment]
just wanted to note down the related discussion on yesterday's tablet meeting:

To minimize disruption to overall cluster performance during repairs on a subset of tables, we can isolate the tables undergoing repair and allow other tables to continue migrating their tablets.

Disabling tablet balancing alone (on a per-table or per-keyspace basis) is insufficient.  If we exclude these tables from migration, the load balancer will optimize for a balanced distribution without them.  However, unpinning them afterwards will cause a significant imbalance, especially for hot tables (tables with high access rates or a large number of tablets).

Here are two approaches to address this imbalance issue:

1. Pre-allocate slots for pinned tables during balancing plan creation. This reserves space on nodes for the pinned tables. Once unpinned, their tablets can migrate seamlessly into these pre-allocated slots, maintaining a balanced distribution after migration.
2. Leverage existing load balancing mechanism. Currently, the load balancer halts after achieving a balanced distribution. We can modify it to trigger rebalancing upon unpinning tables. This will prompt the load balancer to re-evaluate the tablet distribution and issue instructions/decisions for the cluster to achieve a new balanced state.

**Comment by tchaikov** [comment]
The second approach offers greater simplicity, but it comes with a potential drawback. The load balancer might not consider "pinned tables" when distributing workload across nodes. This can lead to uneven workload, especially when these tables are accessed frequently.  Nodes holding pinned tables could become overloaded, while others remain underutilized.

**Comment by tgrabiec** [comment]
The problem with solution 1 (pretending that pinned table tablets are moved) is that until the tablets are really moved, the real balance will be off, which may lead to overload of the shards which own the pinned table.

The problem with solution 2 is that current algorithm is not prepared to rebalance tables, we'd have to implement a new step in the algorithm.

**Comment by tchaikov** [comment]
hi @asias, @bhalevy reminded me that you were working on a tablet-native repair, and the repair is being moved to the tablet migration track, IIUC, this renders the requirement of disabling tablet balancing on a per-table basis not necessary, am i right? as with your change, the repair process is already serialized as a regular migration task, and we don't need to worry about the intervention between them.

**Comment by asias** [comment]
> hi @asias, @bhalevy reminded me that you were working on a tablet-native repair, and the repair is being moved to the tablet migration track, IIUC, this renders the requirement of disabling tablet balancing on a per-table basis not necessary, am i right? as with your change, the repair process is already serialized as a regular migration task, and we don't need to worry about the intervention between them.

For tablet repair yes, we do not need to disable migration after repair is integrated with the tablet scheduler.  

However, people might want to disable migration for other reasons for a given table, e,g., reducing the streaming of data when the volume of the table is huge.

**Comment by tchaikov** [comment]
I see. let's close this issue for now. probably a better alternative is to limit the resource consumption of background tasks like migration using QoS methods. like running it in the maintenance scheduling group.
