### ISSUE TITLE
Maintenance socket: set the default value of the `maintenance-socket-group` option

### ISSUE THREAD

**Issue by margdoc** [scylladb/scylladb#17442]
from @avikivity:

https://github.com/scylladb/scylladb/pull/17113#discussion_r1478622279
> We need to default it to scyllaadm in installations.
>
> This means to set it scyllaadm in conf/scylla.yaml, but that's used in un-installed runs (./build/dev/scylla ...) (is it really? please check)
>
> I think this is the most flexible wrt. packaging.
> 1. add --admin-group option to install.sh, and if set, use its value to adjust the installed scylla.aml.
> 2. use the new option in dist/redhat/scylla.spec and dist/debian/debian/rules, with scyllaadm as the group
> 3. also adjust those files to create scyllaadm and make it the scylla user's group (these files create the scylla user via useradd/adduser), also install.sh plays with users too
>
> /cc @syuu1228
>
> I guess this is quite some work (esp. testing) so can be done in a follow-up.

https://github.com/scylladb/scylladb/pull/17113#discussion_r1478624718
> I think we need to use the scylla group. scyllaadm only exists in scylla-machine-image. Later, we'll need to adjust it to make scyllaadm a member of the scylla group.

**Comment by kbr-scylla** [comment]
@avikivity who should we assign this to? @scylladb/releng ?

**Comment by margdoc** [comment]
@avikivity what do you mean by this:
> I think we need to use the scylla group. scyllaadm only exists in scylla-machine-image. Later, we'll need to adjust it to make scyllaadm a member of the scylla group.

So can we just modify scylla-machine-image such that scyllaadm is a member of the scylla group? Without modifying install.sh, dist/redhat/scylla.spec, dist/debian/debian/rules?

**Comment by avikivity** [comment]
Would that grant scylladm write permissions to /var/lib/scylla? That's too dangerous.

We have several options here:
1. make scyllaadm a member of the scylla group, ensure there there are no group permissions on /var/lib/scylla/**
2. make scyllaadm a member of the scylla group, ensure there there are only read group permissions on /var/lib/scylla/**
3. create yet another group,  make both scylla and scyllaadm members, chgrp the socket to the new group
4. make scylla a member of scyllaadm, chgrp the socket to scyllaadm

The big question is whether scyllaadm should be allowed to read data files. Probably it's safer that we don't grant it that ability. @tzach 

Currently I like option 4.

I see scyllaadm is outside the scope of dist/debian / dist/redhat. This means the change has to happen in scylla-machine-image. Maybe it would be better to move scyllaadm into dist/debian / dist/redhat (so non-cloud users could benefit), but seems like quite some work.

**Comment by margdoc** [comment]
> I see scyllaadm is outside the scope of dist/debian / dist/redhat. This means the change has to happen in scylla-machine-image. Maybe it would be better to move scyllaadm into dist/debian / dist/redhat (so non-cloud users could benefit), but seems like quite some work.

Can we add the `admin-group` option to `install.sh`, `dist/redhat/scylla.spec` and `dist/debian/debian/rules`?
1. `scylla-machine-image` would use this option in `dist/debian` / `dist/redhat`, with `scyllaadm` as the group
2. `dist/redhat/scylla.spec` and `dist/debian/debian/rules` would use it in `install.sh` to set `scyllaadm` as the group
3. `install.sh` would chgrp the socket to `scyllaadm` and add scylla to this group

**Comment by kbr-scylla** [comment]
@margdoc in your last post, you meant not `scyllaadm`, but whatever was passed to the `admin-group` option, right?

---

@avikivity 

> I see scyllaadm is outside the scope of dist/debian / dist/redhat. This means the change has to happen in scylla-machine-image. Maybe it would be better to move scyllaadm into dist/debian / dist/redhat (so non-cloud users could benefit), but seems like quite some work.

Here's my proposal: write additional documentation on the maintenance socket page, do not modify the install scripts.

The cluster administrator can decide themselves what they want.
We can just inform them: if you want access to maintenance socket from user X, then user X needs to be in the same group as user scylla.
How the cluster admin achieves that is up to them.

We give them several options: they can add themselves to group scylla, they can run cqlsh as user scylla, or they can use the maintenance-socket-group flag to change which group the socket is owned by.

For cloud we can indeed pick an option and modify `scylla-machine-image` to add `scylla` to `scyllaadm` (if it doesn't do this already.)

**Comment by avikivity** [comment]
> > I see scyllaadm is outside the scope of dist/debian / dist/redhat. This means the change has to happen in scylla-machine-image. Maybe it would be better to move scyllaadm into dist/debian / dist/redhat (so non-cloud users could benefit), but seems like quite some work.
> 
> Can we add the `admin-group` option to `install.sh`, `dist/redhat/scylla.spec` and `dist/debian/debian/rules`?
> 
> 1. `scylla-machine-image` would use this option in `dist/debian` / `dist/redhat`, with `scyllaadm` as the group
> 2. `dist/redhat/scylla.spec` and `dist/debian/debian/rules` would use it in `install.sh` to set `scyllaadm` as the group
> 3. `install.sh` would chgrp the socket to `scyllaadm` and add scylla to this group

Yes it makes sense. The option should be optional (duh) to avoid breaking existing scripts.

A lazy person could `sudo ./install.sh --admin-group $(id -gn)` to gain admin access to the group.

Should install.sh create the group or use an existing one, or both? I think only an existing one is fine and we can/should rely on the caller to create the group if needed.

**Comment by avikivity** [comment]
> @margdoc in your last post, you meant not `scyllaadm`, but whatever was passed to the `admin-group` option, right?
> 
> @avikivity
> 
> > I see scyllaadm is outside the scope of dist/debian / dist/redhat. This means the change has to happen in scylla-machine-image. Maybe it would be better to move scyllaadm into dist/debian / dist/redhat (so non-cloud users could benefit), but seems like quite some work.
> 
> Here's my proposal: write additional documentation on the maintenance socket page, do not modify the install scripts.
> 
> The cluster administrator can decide themselves what they want. We can just inform them: if you want access to maintenance socket from user X, then user X needs to be in the same group as the socket's owner group. How the cluster admin achieves that is up to them.
> 
> We give them several options: they can add themselves to group scylla, they can run cqlsh as user scylla, or they can use the maintenance-socket-group flag to change which group the socket is owned by.
> 
> For cloud we can indeed pick an option and modify `scylla-machine-image` to add `scylla` to `scyllaadm` (if it doesn't do this already) and leave maintenance-socket-group the default so it is owned by `scylla`. Alternatively, set maintenance-socket-group to `scyllaadm`.



> > > I see scyllaadm is outside the scope of dist/debian / dist/redhat. This means the change has to happen in scylla-machine-image. Maybe it would be better to move scyllaadm into dist/debian / dist/redhat (so non-cloud users could benefit), but seems like quite some work.
> > 
> > 
> > Can we add the `admin-group` option to `install.sh`, `dist/redhat/scylla.spec` and `dist/debian/debian/rules`?
> > 
> > 1. `scylla-machine-image` would use this option in `dist/debian` / `dist/redhat`, with `scyllaadm` as the group
> > 2. `dist/redhat/scylla.spec` and `dist/debian/debian/rules` would use it in `install.sh` to set `scyllaadm` as the group
> > 3. `install.sh` would chgrp the socket to `scyllaadm` and add scylla to this group
> 
> Yes it makes sense. The option should be optional (duh) to avoid breaking existing scripts.
> 
> A lazy person could `sudo ./install.sh --admin-group $(id -gn)` to gain admin access to the group.
> 
> Should install.sh create the group or use an existing one, or both? I think only an existing one is fine and we can/should rely on the caller to create the group if needed.

Sorry, it doesn't work. rpm/deb don't have options, they install things the same each time.

**Comment by avikivity** [comment]
So we could follow @kbr-scylla's proposal.

**Comment by kbr-scylla** [comment]
Fixed by https://github.com/scylladb/scylladb/pull/17701
