### ISSUE TITLE
topology/test_change_ip.py times out after server restarts

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#17444]
```
    @pytest.mark.asyncio
    async def test_change_two(manager, random_tables, mode):
        """Stop two nodes, change their IPs and start, check the cluster is
        functional"""
...
        servers[2] = ServerInfo(servers[2].server_id, s2_new_ip, s2_new_ip)
        await reconnect_driver(manager)
>       await wait_proper_ips([servers[0], servers[1], servers[2]])
...
    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float,
            period: float = 1,
            before_retry: Optional[Callable[[], Any]] = None) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.
```

```
12:00:19.623 INFO> [release/topology.test_change_ip.3] Test release/topology.test_change_ip.3::test_change_two FAILED, cluster: ScyllaCluster(name: daa4283e-d09f-11ee-bb2a-a8a159ead539, running: ScyllaServer(291, 127.195.25.25, 6511109b-bc52-40dd-91bb-216eacd80716), ScyllaServer(292, 127.195.25.5, 186e49e7-b8ee-45c6-a6ad-fe675df19bcb), ScyllaServer(293, 127.195.25.20, 98113ab9-84de-42f4-91e5-02dde2ad7590), stopped: )
12:00:19.623 INFO> [release/topology.test_change_ip.3] The cluster daa4283e-d09f-11ee-bb2a-a8a159ead539 is dirty, not checking keyspace count post-condition
```

in `scylla-291.log`:
```
INFO  2024-02-21 12:00:19,376 [shard 0: gms] gossip - 60000 ms elapsed, 127.195.25.32 gossip quarantine over
```

in `scylla-292.log`:
```
INFO  2024-02-21 11:59:08,347 [shard 0:main] init - Scylla API server listening on 127.195.25.32:10000 ...
...
INFO  2024-02-21 11:59:08,347 [shard 0:main] init - Scylla API server listening on 127.195.25.32:10000 ...
```
[scylla-293.log](https://github.com/scylladb/scylladb/files/14358619/scylla-293.log)
[scylla-292.log](https://github.com/scylladb/scylladb/files/14358620/scylla-292.log)
[scylla-291.log](https://github.com/scylladb/scylladb/files/14358621/scylla-291.log)

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6833

**Comment by Annamikhlin** [comment]
seen also on: https://jenkins.scylladb.com/job/scylla-master/job/next/7284/testReport/(root)/test_change_ip/Build___aarch64___Unit_Tests_aarch64___test_change_two/

**Comment by avikivity** [comment]
Raising priority

**Comment by kbr-scylla** [comment]
`127.195.25.20` is the new IP of s2
```
11:59:17.716 INFO> s1 new ip 127.195.25.5, s2 new ip 127.195.25.20
```

**Comment by gusev-p** [comment]
```
[2024-02-21T10:32:16.598Z] 11:59:21.433 DEBUG> Message pushed from server: <EventMessage(event_type='TOPOLOGY_CHANGE', event_args={'change_type': 'NEW_NODE', 'address': ('127.195.25.20', 9042)}, stream_id=-1, trace_id=None)>

   _refresh_nodes_if_not_up scheduled with random delay

[2024-02-21T10:32:16.598Z] 11:59:21.434 DEBUG> Message pushed from server: <EventMessage(event_type='TOPOLOGY_CHANGE', event_args={'change_type': 'REMOVED_NODE', 'address': ('127.195.25.26', 9042)}, stream_id=-1, trace_id=None)>
    
    remove_host scheduled with zero delay, host is captured

[2024-02-21T10:32:16.598Z] 11:59:21.528 DEBUG> [control connection] Refreshing node list and token map
    _refresh_node_list_and_token_map triggered

[2024-02-21T10:32:16.598Z] 11:59:21.530 DEBUG> [control connection] Updating host ip from 127.195.25.26:9042 to 127.195.25.20:9042 for (98113ab9-84de-42f4-91e5-02dde2ad7590)

    observed the new IP for the host_id, update the host instance in place

[2024-02-21T10:32:16.598Z] 11:59:21.530 INFO> Cassandra host 127.195.25.20:9042 removed

    the scheduled remove node is triggered, it's now removing the new host_id

    [2024-02-21T10:32:16.598Z] 11:59:21.530 WARNING> Host 127.195.25.20:9042 has been marked down
    [2024-02-21T10:32:16.599Z] 11:59:21.530 DEBUG> [cluster] Removing host 127.195.25.20:9042

[2024-02-21T10:32:16.599Z] 11:59:21.530 DEBUG> [control connection] Finished fetching ring info

    закончил работу исходный запланированный _refresh_node_list_and_token_map



[2024-02-21T10:32:16.599Z] 11:59:21.530 DEBUG> [control connection] Refreshing node list and token map
    _refresh_node_list_and_token_map is called one more time

[2024-02-21T10:32:16.599Z] 11:59:21.530 DEBUG> Starting reconnector for host 127.195.25.20:9042
[2024-02-21T10:32:16.599Z] 11:59:21.530 DEBUG> [control connection] Rebuilding token map due to topology changes
[2024-02-21T10:32:16.599Z] 11:59:21.531 INFO> Driver not connected to 127.195.25.20:9042 yet
[2024-02-21T10:32:16.599Z] 11:59:21.532 DEBUG> [control connection] Finished fetching ring info
[2024-02-21T10:32:16.599Z] 11:59:22.532 INFO> Driver not connected to 127.195.25.20:9042 yet
[2024-02-21T10:32:16.599Z] 11:59:23.533 INFO> Driver not connected to 127.195.25.20:9042 yet
[2024-02-21T10:32:16.599Z] 11:59:24.534 INFO> Driver not connected to 127.195.25.20:9042 yet
[2024-02-21T10:32:16.599Z] 11:59:25.535 INFO> Driver not connected to 127.195.25.20:9042 yet
[2024-02-21T10:32:16.599Z] 11:59:26.536 INFO> Driver not connected to 127.195.25.20:9042 yet
[2024-02-21T10:32:16.599Z] 11:59:27.538 INFO> Driver not connected to 127.195.25.20:9042 yet


    everything is broken here

```

The driver mistakenly removes the new IP because of the delay in `remove_host` call. This seems buggy, but shouldn't be a problem - the `_refresh_node_list_and_token_map` is called several times after this removal, and it should have restored the removed node, but didn't do so for some reason.

**Comment by tchaikov** [comment]
> > [scylla-293.log](https://github.com/scylladb/scylladb/files/14358619/scylla-293.log)
> > [scylla-292.log](https://github.com/scylladb/scylladb/files/14358620/scylla-292.log)
> > [scylla-291.log](https://github.com/scylladb/scylladb/files/14358621/scylla-291.log)
> 
> > see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6833
> 
> Important file missing, the test log: [topology.test_change_ip.3.log](https://github.com/scylladb/scylladb/files/14404951/topology.test_change_ip.3.log)
> 
ahh, will add it the next time. thanks for pointing this out and for uploading the missing log file.

**Comment by gusev-p** [comment]
Managed to reproduce it once locally.

The problem is here
```
async def wait_for_cql(cql: Session, host: Host, deadline: float) -> None:
    async def cql_ready():
        try:
            await cql.run_async("select * from system.local", host=host)
        except NoHostAvailable:
            logging.info(f"Driver not connected to {host} yet")
            return None
        return True
    await wait_for(cql_ready, deadline)
```
Theory: the host gets removed by the dark magic described above, then later it's returned back but the instance of the Host is different, `NoHostAvailable` is throws because the driver can't find the host, which is byref equal to the passed one.

**Comment by gusev-p** [comment]
> `host` is the :class:`cassandra.pool.Host` that should handle the query. If the host specified is down or
> not yet connected, the query will fail with :class:`NoHostAvailable`. Using this is
> discouraged except in a few cases, e.g., querying node-local tables and applying schema changes.

**Comment by gusev-p** [comment]
```
def _query(self, host, message=None, cb=None):
        if message is None:
            message = self.message

        pool = self.session._pools.get(host)
        if not pool:
            self._errors[host] = ConnectionException("Host has been marked down or removed")
            return None
        elif pool.is_shutdown:
            self._errors[host] = ConnectionException("Pool is shutdown")
            return None
```

```
def on_down(self, host):
        """
        Called by the parent Cluster instance when a node is marked down.
        Only intended for internal use.
        """
        future = self.remove_pool(host)
        if future:
            future.add_done_callback(lambda f: self.update_created_pools())
```

Seems confirmed. We should retake the host inside `wait_for_cql`.

**Comment by gusev-p** [comment]
@kbr-scylla pointed out, that Host has `__eq__` and `__hash__`, that means we should have found the host when it's returned to the pool.

**Comment by kbr-scylla** [comment]
I would investigate this
```
[2024-02-21T10:32:16.599Z] 11:59:21.530 DEBUG> Starting reconnector for host 127.195.25.20:9042
```

is looks to be the last time that the driver logs mention this host.

So it looks like the host was added to the driver pool, and there is some reconnection process going on. But the process is stuck or something.

There is also old issue in python driver https://github.com/scylladb/python-driver/issues/230 about not reconnecting after full cluster restart (thanks @piodul for reminding), here we don't have full cluster restart, but perhaps it's a similar case? Same root cause?

@avelanarius @sylwiaszunejko maybe you also know something

**Comment by gusev-p** [comment]
```
1. TOPOLOGY_CHANGE (NEW_NODE) -> self._cluster.on_down -> on_down_potentially_blocking (in background) -> self._start_reconnector
2. TOPOLOGY_CHANGE (REMOVED_NODE) -> cluster.remove_host -> host.get_and_set_reconnection_handler(None).cancel()
```
So `wait_for_cql` starts without a pool for the third node, because of the race above reconnector is cancelled and nobody is going to add a pool for it.

**Comment by kbr-scylla** [comment]
But the `TOPOLOGY_CHANGE (REMOVED_NODE)` happens for different Host (the old IP of this server), no?
```
[2024-02-25T09:48:15.496Z] 08:21:16.965 DEBUG> Message pushed from server: <EventMessage(event_type='TOPOLOGY_CHANGE', event_args={'change_type': 'NEW_NODE', 'address': ('127.190.213.20', 9042)}, stream_id=-1, trace_id=None)>
[2024-02-25T09:48:15.496Z] 08:21:16.967 DEBUG> Message pushed from server: <EventMessage(event_type='TOPOLOGY_CHANGE', event_args={'change_type': 'REMOVED_NODE', 'address': ('127.190.213.29', 9042)}, stream_id=-1, trace_id=None)>
```

**Comment by gusev-p** [comment]
> But the `TOPOLOGY_CHANGE (REMOVED_NODE)` happens for different Host (the old IP of this server), no?
> 
> ```
> [2024-02-25T09:48:15.496Z] 08:21:16.965 DEBUG> Message pushed from server: <EventMessage(event_type='TOPOLOGY_CHANGE', event_args={'change_type': 'NEW_NODE', 'address': ('127.190.213.20', 9042)}, stream_id=-1, trace_id=None)>
> [2024-02-25T09:48:15.496Z] 08:21:16.967 DEBUG> Message pushed from server: <EventMessage(event_type='TOPOLOGY_CHANGE', event_args={'change_type': 'REMOVED_NODE', 'address': ('127.190.213.29', 9042)}, stream_id=-1, trace_id=None)>
> ```

No, it's the same host, `_refresh_node_list_and_token_map` just mutates it's endpoint (`host.endpoint = endpoint`). We see in the logs `Cassandra host 127.195.25.20:9042 removed` that when it removes the host it already has a new IP.

**Comment by kbr-scylla** [comment]
In the logs we saw that "Starting reconnector" happened after "Removing host"
```
11:59:21.530 DEBUG> [cluster] Removing host 127.195.25.20:9042
11:59:21.530 DEBUG> [control connection] Finished fetching ring info
11:59:21.530 DEBUG> [control connection] Refreshing node list and token map
11:59:21.530 DEBUG> Starting reconnector for host 127.195.25.20:9042
```

So these are racing with each other? I see `Removing host` is printed inside `on_remove` which at the end lookups and cancels handler, I guess it can happen after the handler is created.

@gusev-p would it be possible to prepare a reproducer for the race? Maybe we could instrument a race within Scylla to send the REMOVED notification later than the NEW_NODE notification...

But if that's possible, then it leads to the question that maybe it's Scylla's fault because it's sending these notifications out of order? On the other hand, even if it sent REMOVED before NEW_NODE, do we have a guarantee that they will get delivered in order? Probably yes if the control_connection is a tcp connection.

On the other hand, even if Scylla sends these notifications in this order (BTW. I wonder what happens in test runs where it doesn't fail -- what is the order there?), perhaps it's wrong for the driver to handle it this way

Yet... is REMOVED_NODE really the proper notification here? @gusev-p it's possible that we weren't sending this notification before, and it's the result of the latest changes in raft-topology. And that we should not be sending this notification for the IP-change case. What happens in gossip mode?

**Comment by gusev-p** [comment]
> But if that's possible, then it leads to the question that maybe it's Scylla's fault because it's sending these notifications out of order? On the other hand, even if it sent REMOVED before NEW_NODE, do we have a guarantee that they will get delivered in order? Probably yes if the control_connection is a tcp connection.

```
def _handle_topology_change(self, event):
        change_type = event["change_type"]
        addr, port = event["address"]
        host = self._cluster.metadata.get_host(addr, port)
        if change_type == "NEW_NODE" or change_type == "MOVED_NODE":
            if self._topology_event_refresh_window >= 0:
                delay = self._delay_for_event_type('topology_change', self._topology_event_refresh_window)
                self._cluster.scheduler.schedule_unique(delay, self._refresh_nodes_if_not_up, host)
        elif change_type == "REMOVED_NODE":
            self._cluster.scheduler.schedule_unique(0, self._cluster.remove_host, host)
```
Sending `REMOVED_NODE` and `NEW_NODE` in order won't fundamentally solve the problem since there are a lot of threading and asynchrony in the driver. The `_handle_topology_change` above puts callbacks into some 'scheduler' (priority queue by time), which is a dedicated thread. This scheduler in turn runs these callbacks on the worker pool with two threads, so there are no ordering guarantees at all.

The delay in the code above is calculated by `_delay_for_event_type` at random:
```
def _delay_for_event_type(self, event_type, delay_window):
        # this serves to order processing correlated events (received within the window)
        # the window and randomization still have the desired effect of skew across client instances
        next_time = self._event_schedule_times.get(event_type, 0)
        now = self._time.time()
        if now <= next_time:
            this_time = next_time + 0.01
            delay = this_time - now
        else:
            delay = random() * delay_window
            this_time = now + delay
        self._event_schedule_times[event_type] = this_time
        return delay
```

On the other hand, in addition to adding the random jitter to node refreshes, it tries to preserve the original order. Maybe we should just account for `REMOVED_NODE` in the same `_event_schedule_times`.

>  @gusev-p it's possible that we weren't sending this notification before, and it's the result of the latest changes in raft-topology. And that we should not be sending this notification for the IP-change case. What happens in gossip mode?

That's probably true, will check.

**Comment by kostja** [comment]
* Kamil Braun ***@***.***> [24/02/27 15:53]:
> 
> But if that's possible, then it leads to the question that maybe it's Scylla's fault because it's sending these notifications out of order? On the other hand, even if it sent REMOVED before NEW_NODE, do we have a guarantee that they will get delivered in order? Probably yes if the control_connection is a tcp connection.

If the python driver expects in-order delivery it should assert
for it. Relying on tcp messages being in-order is fragile.
Out-of-order delivery may happen if the connection is
re-established concurrently with some processing of the older
message or due to a yield, or due to a bug on the driver side.

In my experience this is a frequent cause of bugs, so best to not
rely on it if possible.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by avikivity** [comment]
I think the server should serialize notifications on a per-connection basis.

**Comment by avikivity** [comment]
It's already true:

```c++
void cql_server::event_notifier::on_create_keyspace(const sstring& ks_name)
{
    for (auto&& conn : _schema_change_listeners) {
        using namespace cql_transport;
        if (!conn->_pending_requests_gate.is_closed()) {
            conn->write_response(conn->make_schema_change_event(event::schema_change{
                event::schema_change::change_type::CREATED,
                event::schema_change::target_type::KEYSPACE,
                ks_name
            }));
        };
    }
}

```

```c++
void cql_server::connection::write_response(foreign_ptr<std::unique_ptr<cql_server::response>>&& response, service_permit permit, cql_compression compression)
{
    _ready_to_respond = _ready_to_respond.then([this, compression, response = std::move(response), permit = std::move(permit)] () mutable {
        auto message = response->make_message(_version, compression);
        message.on_delete([response = std::move(response)] { });
        return _write_buf.write(std::move(message)).then([this] {
            return _write_buf.flush();
        });
    });
}
```
