### ISSUE TITLE
[cqlsh][Regression]: COPY TO STDOUT is broken 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#17451]
*Installation details*
Scylla version: 5.4.0

*Description*
cqlsh COPY TO STDIN command fails with a following symptom:
```
cassandra@cqlsh> COPY system_schema.tables TO STDOUT ; 
'NoneType' object is not callable
cassandra@cqlsh> 
```

This is a regression introduced in 5.4.0

**Comment by mykaul** [comment]
5.4 - https://github.com/scylladb/scylladb/commit/02182caff4fe526e3e59f7b5550e263093235124
