### ISSUE TITLE
docs: some repair options are deprecated, but still shown in the following page

### ISSUE THREAD

**Issue by maesta2** [scylladb/scylladb#17457]
some repair options are deprecated, but still shown in the following page
- https://manager.docs.scylladb.com/stable/repair/examples.html#
- deprecated options:  [-s <date>] [-i <time-unit>]

```
# sctool repair -c '0aa34674-4472-4bbe-8b4c-007a74e56642' -s now+4h -i 7d
Flag --start-date has been deprecated, use cron instead
Flag --interval has been deprecated, use cron instead
```

it is still working, but better to change with cron example?

**Comment by tzach** [comment]
Thanks @maesta2 !
Good catch.

Please reopen in the scylla manager repo.
Note the "Create an issue" at the top right.
![image](https://github.com/scylladb/scylladb/assets/170200/ff817f0b-e4f6-484f-a254-9d66ca4edd41)
