### ISSUE TITLE
scylla_setup "Do you want to setup sysconfig?" - not clear why

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#1748]
_Installation details_
Scylla version (or git commit hash): 1.3

The general questions in scylla_setup `Do you want to setup sysconfig?`  is really all about NIC setting.
a better question will be 
`Do you want to optimize NIC queue settings? this will update sysconfig`

**Comment by syuu1228** [comment]
@tzach Sent "[PATCH scylla] dist/common/scripts/scylla_setup: improve scylla_sysconfig_setup prompt message" while ago, please review it

**Comment by slivne** [comment]
@syuu1228 - was this fixed ?

**Comment by slivne** [comment]
@syuu1228 ping ?

**Comment by tzach** [comment]
> "[PATCH scylla] dist/common/scripts/scylla_setup: improve scylla_sysconfig_setup prompt message" while ago, please review it

Look like it was never committed.

**Comment by syuu1228** [comment]
We don't have this message anymore, closing.
