### ISSUE TITLE
[jepsen] test is failing to start during bootstrap of a node (Node 10.142.0.92 has gossip status=UNKNOWN)

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#17520]
## Packages

Scylla version: `5.5.0~dev-20240222.57c408ab5d20` with build-id `791df0e77826e1d60ee9f89c8e1b27daf1f265b7`

Kernel Version: `4.19.0-26-cloud-amd64`

## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

one test is to setup

```
< t:2024-02-25 13:28:31,421 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Caused by: clojure.lang.ExceptionInfo: throw+: {:type :jepsen.db/setup-failed, :msg :await-open-timeout, :node "10.142.0.86"}
```

and this node was failing to boot
```
Feb 25 13:26:12.238326 jepsen-ubuntu-db-node-431e30aa-0-2 scylla[16666]:  [shard 0:main] init - Startup failed: std::runtime_error (Node 10.142.0.92 has gossip status=UNKNOWN. Try fixing it before adding new node to the cluster.)
```

seems similar to https://github.com/scylladb/scylladb/issues/11853, but not as permanent 

## Impact

out of 3 run, this one test is failing

## How frequently does it reproduce?

it's the first time seen

## Installation details

Cluster size: 5 nodes (n1-standard-4)

Scylla Nodes used in this run:
- jepsen-ubuntu-db-node-431e30aa-0-5 (34.73.48.180 | 10.142.0.95) (shards: 4)
- jepsen-ubuntu-db-node-431e30aa-0-4 (34.75.175.42 | 10.142.0.92) (shards: 4)
- jepsen-ubuntu-db-node-431e30aa-0-3 (34.139.229.40 | 10.142.0.87) (shards: 4)
- jepsen-ubuntu-db-node-431e30aa-0-2 (34.23.136.206 | 10.142.0.86) (shards: 4)
- jepsen-ubuntu-db-node-431e30aa-0-1 (35.237.5.88 | 10.142.0.84) (shards: 4)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10` (gce: undefined_region)

Test: `jepsen-all-test`
Test id: `431e30aa-2e59-4e65-897b-d8c30ae0f89c`
Test name: `scylla-master/tier1/jepsen-all-test`
Test config file(s):

- [jepsen.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4103add70864490e724e9ddc608ef14835926677/test-cases/jepsen/jepsen.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 431e30aa-2e59-4e65-897b-d8c30ae0f89c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=431e30aa-2e59-4e65-897b-d8c30ae0f89c)
- Show all stored logs command: `$ hydra investigate show-logs 431e30aa-2e59-4e65-897b-d8c30ae0f89c`

## Logs:
- **db-cluster-431e30aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/db-cluster-431e30aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/db-cluster-431e30aa.tar.gz)
- **sct-runner-events-431e30aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/sct-runner-events-431e30aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/sct-runner-events-431e30aa.tar.gz)
- **sct-431e30aa.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/sct-431e30aa.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/sct-431e30aa.log.tar.gz)
- **loader-set-431e30aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/loader-set-431e30aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/loader-set-431e30aa.tar.gz)
- **monitor-set-431e30aa.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/monitor-set-431e30aa.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/monitor-set-431e30aa.tar.gz)
- **jepsen-data.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/jepsen-data.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/431e30aa-2e59-4e65-897b-d8c30ae0f89c/20240225_142551/jepsen-data.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/jepsen-all-test/2/)
[Argus](https://argus.scylladb.com/test/2af4cb81-4b9e-4fc7-8c32-661c694b0924/runs?additionalRuns[]=431e30aa-2e59-4e65-897b-d8c30ae0f89c)
</details>

**Comment by fruch** [comment]
Happens in this week run

## Packages

Scylla version: `5.5.0~dev-20240301.94cd23588832` with build-id `d010caa35e3ede60b884b4c94bcc945bfd3ccd4b`





Kernel Version: `4.19.0-26-cloud-amd64`


## Installation details

Cluster size: 5 nodes (n1-standard-4)

Scylla Nodes used in this run:
- jepsen-ubuntu-db-node-a60c242d-0-5 (34.73.20.190 | 10.142.0.213) (shards: 4)
- jepsen-ubuntu-db-node-a60c242d-0-4 (104.196.3.176 | 10.142.0.211) (shards: 4)
- jepsen-ubuntu-db-node-a60c242d-0-3 (34.23.91.249 | 10.142.0.208) (shards: 4)
- jepsen-ubuntu-db-node-a60c242d-0-2 (35.243.229.140 | 10.142.0.206) (shards: 4)
- jepsen-ubuntu-db-node-a60c242d-0-1 (34.75.9.106 | 10.142.0.205) (shards: 4)


OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10` (gce: undefined_region)

Test: `jepsen-all-test`
Test id: `a60c242d-7bb1-4172-af3c-5fe171ba8b09`
Test name: `scylla-master/tier1/jepsen-all-test`
Test config file(s):

- [jepsen.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/19a0f45cd759e2c4d0ae07c75c04da701a14073f/test-cases/jepsen/jepsen.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor a60c242d-7bb1-4172-af3c-5fe171ba8b09`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a60c242d-7bb1-4172-af3c-5fe171ba8b09)
- Show all stored logs command: `$ hydra investigate show-logs a60c242d-7bb1-4172-af3c-5fe171ba8b09`


## Logs:
- **db-cluster-a60c242d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/db-cluster-a60c242d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/db-cluster-a60c242d.tar.gz)
- **sct-runner-events-a60c242d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/sct-runner-events-a60c242d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/sct-runner-events-a60c242d.tar.gz)
- **sct-a60c242d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/sct-a60c242d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/sct-a60c242d.log.tar.gz)
- **loader-set-a60c242d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/loader-set-a60c242d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/loader-set-a60c242d.tar.gz)
- **monitor-set-a60c242d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/monitor-set-a60c242d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/monitor-set-a60c242d.tar.gz)
- **jepsen-data.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/jepsen-data.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a60c242d-7bb1-4172-af3c-5fe171ba8b09/20240302_124736/jepsen-data.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/jepsen-all-test/3/)
[Argus](https://argus.scylladb.com/test/2af4cb81-4b9e-4fc7-8c32-661c694b0924/runs?additionalRuns[]=a60c242d-7bb1-4172-af3c-5fe171ba8b09)
</details>

**Comment by mykaul** [comment]
@kostja - Jepsen issue for tier1 - what's the next step here?

**Comment by temichus** [comment]
seen in SCT only once on 2024-02-25 and newer reproduced. Close as "can't repro"
