### ISSUE TITLE
docs: Issue in page Scylla Java Driver

### ISSUE THREAD

**Issue by maesta2** [scylladb/scylladb#17551]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.4/using-scylla/drivers/cql-drivers/scylla-java-driver

### Problem
The Scylla Java driver is shard aware

###  Suggest a fix
It depends on java driver version. 3.x support this, but 4.x doesn't yet.
We should be more specific about the version.

**Comment by tzach** [comment]
@avelanarius please comment

**Comment by avelanarius** [comment]
Both 3.x and 4.x are shard aware. What 4.x lacks is support for "advanced shard awareness" (an optimization where the driver can connect to a specific shard by setting a specific TCP source port). But even without that feature, the driver is shard aware - sending queries to correct shards.
