### ISSUE TITLE
[dtest] lwt_schema_modification_test.py::TestLWTSchemaModification::test_table_alter_delete fails

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#17563]
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/194/

```
cassandra.WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] message="Operation failed for lwt_load_ks.table1 - received 1 responses and 1 failures from 2 CL=QUORUM." info={'consistency': 'QUORUM', 'required_responses': 2, 'received_responses': 1, 'failures': 1}
```

[node1.log](https://github.com/scylladb/scylladb/files/14435326/node1.log)
[node2.log](https://github.com/scylladb/scylladb/files/14435327/node2.log)
[node3.log](https://github.com/scylladb/scylladb/files/14435328/node3.log)
[node4.log](https://github.com/scylladb/scylladb/files/14435330/node4.log)
[test_table_alter_delete.log](https://github.com/scylladb/scylladb/files/14435351/test_table_alter_delete.log)

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylladb/issues/17549 ?

**Comment by denesb** [comment]
> Dup of #17549 ?

Yes, closing.
