### ISSUE TITLE
test_topology_recovery_basic fails on topology-CDC consistency check

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#17587]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/next/7308/.

`test_topology_recovery_basic` failed in aarch64/debug on assertion in `check_system_topology_and_cdc_generations_v3_consistency`:
```
            # Check that the contents fetched from the current host are the same as for other nodes
>           assert topo_results[0] == topo_res
E           AssertionError
```

Logs:
[topology_experimental_raft.test_topology_recovery_basic.1.log](https://github.com/scylladb/scylladb/files/14450460/topology_experimental_raft.test_topology_recovery_basic.1.log)
[scylla-783.log](https://github.com/scylladb/scylladb/files/14450454/scylla-783.log)
[scylla-784.log](https://github.com/scylladb/scylladb/files/14450456/scylla-784.log)
[scylla-785.log](https://github.com/scylladb/scylladb/files/14450458/scylla-785.log)

**Comment by kbr-scylla** [comment]
cc @piodul

**Comment by piodul** [comment]
The test fetches `system.topology` contents from all nodes and then compares whether it's the same on all nodes. I saw that the only difference between them is the `unpublished_cdc_generations` column. So, it looks like the test is racing with the CDC generation publisher fiber.

**Comment by Annamikhlin** [comment]
seems the same symptom in `test_topology_upgrade_basic` test:
https://jenkins.scylladb.com/job/scylla-master/job/next/7319/testReport/junit/(root)/test_topology_upgrade/Build___aarch64___Unit_Tests_aarch64___test_topology_upgrade_basic/

and also here:
https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2819/testReport/junit/(root)/test_topology_upgrade/Unit_Tests_aarch64___test_topology_upgrade_basic/
