### ISSUE TITLE
Tombstone GC is extremely ineffective when memtable is frequently appended with old data

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#17599]
Currently, tombstone GC is built on assumption that memtables will rarely contain data older than the expiring ones. 

It's broken when application events are ingested out of order, and uses explicit timestamp to correct the ordering (when persisting those events into the db). That means memtables will frequently contain old data.

If a memtable contains data that is 99% older than expired tombstones, it means only 1% can be GCed. That, of course, causes disk space issues.

It's a rare use case, but it should work. So I suggest that if we detect memtable contains older data than sstables being compacted, then the procedure to calculate max purgeable timestamp will check for presence of key in memtable too. If key is not present, then we don't have to take into account its minimum timestamp. Checking first if memtable contains older data, helps to avoid penalizing (due to log N when looking up key in memtable) the common scenario where memtables won't have out-of-order writes.

This is a desireable trade-off. We don't want the node to run out of space, nor expired tombstones to accumulate indefinitely, causing read amplification.

**Comment by raphaelsc** [comment]
@denesb fyi.

**Comment by vladzcloudius** [comment]
Why not to flush a memtable when the older data is detected? 
* This would not create a flush storm because flushes would only happen in the context of a compaction (as described in the opening message).
* This would allow us to keep the rest of the logic unchanged (==KISS)

**Comment by vladzcloudius** [comment]
On a second thought the original idea is simple enough as well...

**Comment by raphaelsc** [comment]
> Why not to flush a memtable when the older data is detected?
> 
> * This would not create a flush storm because flushes would only happen in the context of a compaction (as described in the opening message).
> * This would allow us to keep the rest of the logic unchanged (==KISS)

I am tackling a problem when old data goes to memtable with a high frequency. With high frequency, old data can be appended to new memtable as soon as you flush the old one, and you still have the problem. I agree it helps when old data in memtable is rare, but not for the problem I opened this issue for.

**Comment by raphaelsc** [comment]
> On a second thought the original idea is simple enough as well...

Indeed, it's very simple to implement. We'd be treating memtable as we treat a L0 sstable essentially.

**Comment by avikivity** [comment]
> It's a rare use case, but it should work.

Why is it so important?

**Comment by mykaul** [comment]
@yaronkaikov - I wonder if we should let mergify work on 5.4 first - if it fails there due to merge-conflicts - any point in running a backport to 5.2, or should the 5.2 backport be taken from the 5.4 pull request?

**Comment by yaronkaikov** [comment]
> @yaronkaikov - I wonder if we should let mergify work on 5.4 first - if it fails there due to merge-conflicts - any point in running a backport to 5.2, or should the 5.2 backport be taken from the 5.4 pull request?

I remember at least one PR that had conflicts in 5.4 but 5.2 worked without any. So i am not sure about that. But, the question is should we always do 5.4 first, and only after we should do backport for 5.2? just to avoid a situation where we merge 5.2 before 5.4

**Comment by mykaul** [comment]
> > @yaronkaikov - I wonder if we should let mergify work on 5.4 first - if it fails there due to merge-conflicts - any point in running a backport to 5.2, or should the 5.2 backport be taken from the 5.4 pull request?
> 
> I remember at least one PR that had conflicts in 5.4 but 5.2 worked without any. So i am not sure about that. But, the question is should we always do 5.4 first, and only after we should do backport for 5.2? just to avoid a situation where we merge 5.2 before 5.4

That too.

**Comment by yaronkaikov** [comment]
@mykaul here is one example https://github.com/scylladb/scylladb/pull/17858 (5.2) was merged already while https://github.com/scylladb/scylladb/pull/17859 (5.4) is still open

**Comment by yaronkaikov** [comment]
> > > @yaronkaikov - I wonder if we should let mergify work on 5.4 first - if it fails there due to merge-conflicts - any point in running a backport to 5.2, or should the 5.2 backport be taken from the 5.4 pull request?
> > 
> > 
> > I remember at least one PR that had conflicts in 5.4 but 5.2 worked without any. So i am not sure about that. But, the question is should we always do 5.4 first, and only after we should do backport for 5.2? just to avoid a situation where we merge 5.2 before 5.4
> 
> That too.

Also, i am not sure we should do the backport to 5.2 from 5.4
