### ISSUE TITLE
[5.2, topology, aarch64, debug] topology tests failed on timeouts

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#17618]
During the build of 5.2.16 unit tests failed on arm debug mode with timeouts - https://jenkins.scylladb.com/job/scylla-5.2/job/build/24/testReport/ 

Not sure if we have fixes for newer releases but we should either backport or disable those tests from running

/cc @mykaul

**Comment by yaronkaikov** [comment]
@kbr-scylla Please advice , note that those failures only happened on `Armatrading` , while running on fleet it's passing

**Comment by mykaul** [comment]
@kbr-scylla - I think we should disable those tests on 5.2. We have 5.4 and master which substantially better topology code, that we do not really care (at this point) about topology (experimental feature!) in 5.2.
If you are agree, please just disable them in 5.2.

**Comment by kbr-scylla** [comment]
In 5.2 the tests are not running with raft-topology experimental feature

**Comment by kbr-scylla** [comment]
There are known issues that cause tests to be flaky in 5.2, we fixed them in 5.4 and later, but the changes were too large and complex for backporting.

These issues may happen on every node bootstrap. So we'd basically have to disable all topology tests, which also doesn't seem like a good idea.

**Comment by kbr-scylla** [comment]
> @kbr-scylla Please advice , note that those failures only happened on Armatrading , while running on fleet it's passing

Maybe let's not run it on armatrading then?

**Comment by mykaul** [comment]
> We can't disable it for 5.2 only, if we disable it is for all releases

I'm sure it's doable... Either via branches (of dtest at least), test.py in 5.2 branch only, or otherwise.

**Comment by yaronkaikov** [comment]
> > We can't disable it for 5.2 only, if we disable it is for all releases
> 
> I'm sure it's doable... Either via branches (of dtest at least), test.py in 5.2 branch only, or otherwise.

It's not related to the dtest in any way., I can disable the Armatrading for 5.2 which means that we always run in the fleet

**Comment by yaronkaikov** [comment]
Sent a patch https://github.com/scylladb/scylla-pkg/pull/3879

**Comment by yaronkaikov** [comment]
> Sent a patch [scylladb/scylla-pkg#3879](https://github.com/scylladb/scylla-pkg/pull/3879)

Patch was merged, closing

**Comment by mykaul** [comment]
https://github.com/scylladb/scylla-pkg/pull/3879 doesn't fix this one, but I'm OK with closing it if it doesn't happen anymore due to it.
