### ISSUE TITLE
`cassandra.DriverException: Node list was not refreshed` error in `topology_custom.test_topology_remove_garbage_group0`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17616]
Attaching logs
[scylla-1431.log](https://github.com/scylladb/scylladb/files/14481362/scylla-1431.log)
[scylla-1432.log](https://github.com/scylladb/scylladb/files/14481363/scylla-1432.log)
[scylla-1436.log](https://github.com/scylladb/scylladb/files/14481365/scylla-1436.log)
[scylla-1437.log](https://github.com/scylladb/scylladb/files/14481366/scylla-1437.log)
[topology_custom.test_topology_remove_garbage_group0.3.log](https://github.com/scylladb/scylladb/files/14481367/topology_custom.test_topology_remove_garbage_group0.3.log)

error:
```
>       group0_members = await get_current_group0_config(manager, servers[3])

test/topology_custom/test_topology_remove_garbage_group0.py:109: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology/util.py:67: in get_current_group0_config
    host = (await wait_for_cql_and_get_hosts(manager.cql, [srv], time.time() + 60))[0]
test/pylib/util.py:81: in wait_for_cql_and_get_hosts
    hosts = await wait_for(
test/pylib/util.py:53: in wait_for
    before_retry()
test/pylib/util.py:84: in <lambda>
    before_retry=lambda: cql.cluster.refresh_nodes(force_token_rebuild=True),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.DriverException: Node list was not refreshed. See log for details.
```

I looked at implementation of `wait_for_cql_and_get_hosts` because I remembered this `before_retry=lambda: cql.cluster.refresh_nodes(force_token_rebuild=True)` didn't exist before.
I see it was added in 10eebe3c66b

@enaydanov the commit message does not have any motivation for this `refresh_nodes` call --- what is this needed for? Isn't driver automatically refreshing anyway?

And shouldn't we catch and ignore the exception? It looks like it can happen if we call `refresh_nodes` while the driver is in the middle of reconnecting (e.g. because we just stopped a node that hosted the control connection, like in this test)
here the error was:
```
08:39:29.884 DEBUG> [control connection] Error refreshing node list and token map
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3843, in cassandra.cluster.ControlConnection.refresh_node_list_and_token_map
  File "cassandra/cluster.py", line 3869, in cassandra.cluster.ControlConnection._refresh_node_list_and_token_map
  File "cassandra/connection.py", line 1102, in cassandra.connection.Connection.wait_for_responses
cassandra.connection.ConnectionShutdown: Connection <CustomConnection(140433625811792) 127.71.198.29:9042 (closed)> is already closed
```

`127.71.198.29` was just stopped (gracefully) by the test :
```
        await manager.server_stop_gracefully(servers[2].server_id)
    
        token_ring_ids = await get_token_ring_host_ids(manager, servers[3])
        logging.info(f'token ring members: {token_ring_ids}')
    
>       group0_members = await get_current_group0_config(manager, servers[3])
```

**Comment by enaydanov** [comment]
@kbr-scylla Afair, it's a part of workaround for https://github.com/scylladb/python-driver/issues/273 

So, the answer is no, driver doesn't behave nice for such cases yet.

As for catching exceptions, probably it depends on a test we do.

**Comment by kbr-scylla** [comment]
> @kbr-scylla Afair, it's a part of workaround for https://github.com/scylladb/python-driver/issues/273

`wait_for_cql_and_get_hosts` itself is the workaround -- we wait for query to succeed or timeout. Not sure why we need the extra `refresh_nodes` on each retry.

Such changes should be motivated in commit message, there had to be a specific reason you added it. We now don't know :(

> As for catching exceptions, probably it depends on a test we do.

It can happen in any test that uses `wait_for_cql_and_get_hosts` after shutting down a node which is probably majority of topology tests.

So it basically makes all tests flaky.

I'm gonna send PR to silence the exception. `wait_for_cql_and_get_hosts` should fail by timeout, not when a refresh attempt fails.

**Comment by kbr-scylla** [comment]
> Such changes should be motivated in commit message, there had to be a specific reason you added it. We now don't know :(

I'm guessing it had something to do with using `wait_for_token_ring_and_group0_consistency` (which uses `wait_for_cql_and_get_hosts` underneath) inside the new test `test_change_rpc_address`? Maybe it's necessary when we change addresses of all servers.

But I see in this test a new driver session is established anyway after each node restart, so not sure.

And this change affects many tests, not just this one, because `wait_for_cql_and_get_hosts` is used by many tests directly or indirectly.
