### ISSUE TITLE
deletion_test.py::TestRangeDeletion::test_delete_when_decommission_node fails due to "No live endpoint available" after stopping all nodes except for the new joiner

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#17614]
after applying https://github.com/scylladb/scylla-dtest/pull/4015, we are able to run the said test with `--tablets` command line option. but it fails like
```
        for node in self.cluster.nodelist():
            if not (node in (node_new, node2)):
                logger.info(f"Stop node {node.name}")
                node.stop()

        session = self.fixture_dtest_setup.patient_exclusive_cql_connection(node_new)

>       assert_one(session, "select count(*) from ks.test1", [17])
...
tools/assertions.py:144: in assert_one
    res = session.execute(simple_query)
cassandra/cluster.py:2729: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.50.5:9042 datacenter1>: <Error from server: code=0000 [Server error] message="No live endpoint available">
})
...
```

`"No live endpoint available"` is returned by the new node (node5). it seems that `tablet_effective_replication_map::get_natural_endpoints()` returned an empty set.

the test passes with `--experimental-features=consistent-topology-changes` though.

my guess is that tablets requires that the cluster keep at least RF number of nodes in the cluster so it is readable?

**Comment by tchaikov** [comment]
i am not 100% sure if this is a dtest issue or a scylla issue. so filed it here while created a fix at https://github.com/scylladb/scylla-dtest/pull/4022

**Comment by bhalevy** [comment]
Cc @tgrabiec 
This does look like an issues on the scylla side of things.
Shouldn't the full-scan query return only the local data with cl=ONE, and all other nodes stopped?

**Comment by tgrabiec** [comment]
The situation during failure is this:

node1: down
node2: decommissioned
node3: down
node4: down
node5: up

RF=3 and there are 4 member nodes. It's possible that node5 doesn't have any replica for the key, so the error is expected.

Before the modification to +1 number of nodes it was not possible, since there were 3 member nodes which is equal to RF.

**Comment by tchaikov** [comment]
closing. as it's a regression introduced by #4015

**Comment by bhalevy** [comment]
you mean https://github.com/scylladb/scylla-dtest/issues/4015, right?

**Comment by bhalevy** [comment]
> The situation during failure is this:
> 
> node1: down node2: decommissioned node3: down node4: down node5: up
> 
> RF=3 and there are 4 member nodes. It's possible that node5 doesn't have any replica for the key, so the error is expected.
> 
> Before the modification to +1 number of nodes it was not possible, since there were 3 member nodes which is equal to RF.

There is no key in the query, it's a full scan.
Even if the queried node is empty of data in one or all tablets, shouldn't that result in an empty result with cl=ONE rather than NoHostAvailable?

**Comment by tchaikov** [comment]
> you mean [scylladb/scylla-dtest#4015](https://github.com/scylladb/scylla-dtest/pull/4015), right?

ahh, right. thank you.  corrected.

**Comment by tchaikov** [comment]
> > The situation during failure is this:
> > node1: down node2: decommissioned node3: down node4: down node5: up
> > RF=3 and there are 4 member nodes. It's possible that node5 doesn't have any replica for the key, so the error is expected.
> > Before the modification to +1 number of nodes it was not possible, since there were 3 member nodes which is equal to RF.
> 
> There is no key in the query, it's a full scan. Even if the queried node is empty of data in one or all tablets, shouldn't that result in an empty result with cl=ONE rather than NoHostAvailable?

i was reading the source code. IIUC, we scan the full token range, and lookup the endpoints owing each token range, if none is returned, we fail the query.

**Comment by bhalevy** [comment]
> > > The situation during failure is this:
> > > node1: down node2: decommissioned node3: down node4: down node5: up
> > > RF=3 and there are 4 member nodes. It's possible that node5 doesn't have any replica for the key, so the error is expected.
> > > Before the modification to +1 number of nodes it was not possible, since there were 3 member nodes which is equal to RF.
> > 
> > 
> > There is no key in the query, it's a full scan. Even if the queried node is empty of data in one or all tablets, shouldn't that result in an empty result with cl=ONE rather than NoHostAvailable?
> 
> i was reading the source code. IIUC, we scan the whole token range, and lookup the endpoints owing each token range, if none is returned, we fail the query.

I concur.  I verified that with vnodes as well.

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/pull/17629 adds a test to verify the error when executing the scan query with not enough nodes to satisfy CL

**Comment by tgrabiec** [comment]
> > The situation during failure is this:
> > node1: down node2: decommissioned node3: down node4: down node5: up
> > RF=3 and there are 4 member nodes. It's possible that node5 doesn't have any replica for the key, so the error is expected.
> > Before the modification to +1 number of nodes it was not possible, since there were 3 member nodes which is equal to RF.
> 
> There is no key in the query, it's a full scan. Even if the queried node is empty of data in one or all tablets, shouldn't that result in an empty result with cl=ONE rather than NoHostAvailable?

A full scan touches all keys, if at least one key is unavailable, it will fail. CL=ONE means that we return data from 1 replica. Here there is not even 1 replica available, since node5 is not a replica for that key. It would be incorrect to return no data, that would be like data loss.
