### ISSUE TITLE
Tablets are not dropped when secondary index is dropped leading to live-lock of topology coordinator 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#17627]
Reproducer:
```
create keyspace test WITH REPLICATION = {'class' : 'NetworkTopologyStrategy', 'replication_factor' : 1} and tablets = {'initial': 32 };
create table test.t1 (pk int primary key, v int);
create index idx ON test.t1 (v);
drop index test.idx;
```

We can see that tablets are still there by doing select on system.tablets, while they shouldn't be there.

This will live-block the topology coordinator in the tablet migration track due to retry on failure, because tablet's table cannot be found:

```
ERROR 2024-03-05 00:43:05,896 [shard 0:strm] raft_topology - topology change coordinator fiber got error data_dictionary::no_such_column_family (Can't find a column family with UUID 6c7881d0-da80-11ee-9723-746b0771e35e)
```

Throw from for_each_tablet_transition() here:
```
        for (auto&& [table, tmap] : tm->tablets().all_tables()) {
            co_await coroutine::maybe_yield();
            auto s = _db.find_schema(table);
```

**Comment by bhalevy** [comment]
We don't tablets also when views are dropped.
It's easier to fix for that path since it uses `prepare_view_drop_announcement` that can notify `before_drop_column_family`.
