### ISSUE TITLE
`test_restart_node_localhost[wait_and_restart=False]` dtest failure with raft topology

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17631]
[dtest-gw1.log](https://github.com/scylladb/scylladb/files/14493219/dtest-gw1.log)
[node1.log](https://github.com/scylladb/scylladb/files/14493220/node1.log)
[node2.log](https://github.com/scylladb/scylladb/files/14493221/node2.log)

```
>           assert len(notifications) >= min_expected_notifications and len(notifications) <= expected_notifications
E           AssertionError: assert (4 >= 2 and 4 <= 3)
E            +  where 4 = len([{'address': ('127.0.55.2', 9161), 'change_type': 'NEW_NODE'}, {'address': ('127.0.55.2', 9161), 'change_type': 'UP'}, {'address': ('127.0.55.2', 9161), 'change_type': 'DOWN'}, {'address': ('127.0.55.2', 9161), 'change_type': 'UP'}])
E            +  and   4 = len([{'address': ('127.0.55.2', 9161), 'change_type': 'NEW_NODE'}, {'address': ('127.0.55.2', 9161), 'change_type': 'UP'}, {'address': ('127.0.55.2', 9161), 'change_type': 'DOWN'}, {'address': ('127.0.55.2', 9161), 'change_type': 'UP'}])
```

Looks like Scylla pushed one too many notifications?

**Comment by gusev-p** [comment]
doesn't reproduce locally on `0a7854ea4de0` (scylla commit hash from the node logs above).

`(env) [gusev-p@potwor1 scylla-dtest]$ pytest --rootdir '/home/gusev-p/scylla-dtest' -c '/home/gusev-p/scylla-dtest/pytest.ini' --count 10 --cassandra-dir '/home/gusev-p/scylladb/build/release' pushed_notifications_test.py::TestPushedNotifications::test_restart_node_localhost --experimental-features consistent-topology-changes &> /home/gusev-p/dtest-run/my_out`

**Comment by kbr-scylla** [comment]
@temichus @aleksbykov We should be able to re-enable the test in raft-topology mode now.

I actually already ran it 100 times in raft-topology with this job https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/artsiom_mishuta/job/dtest-pytest-gating/302/parameters/ using this commit https://github.com/kbr-scylla/scylla-dtest/commit/d60e218600759e2036b65be5d08033cc8c04220a 

Please review if I did it correctly, and if so, send PR to re-enable the test.
