### ISSUE TITLE
docs: Issue in page Upgrade ScyllaDB

### ISSUE THREAD

**Issue by pogzie** [scylladb/scylladb#17649]
I would like to report an issue in page https://enterprise.docs.scylladb.com/branch-2024.1/upgrade/index

### Problem
> You should perform the upgrades consecutively - to each successive X.Y version, without skipping any major or minor version.

The statement above tells that a skip upgrade is not possible. 

The link text in the URL in [Upgrade ScyllaDB Enterprise from 2022.2.y to 2023.1.z](https://enterprise.docs.scylladb.com/branch-2024.1/upgrade/upgrade-enterprise/upgrade-guide-from-2022.2-to-2024.1/upgrade-guide-from-2022.2-to-2024.1-generic.html) is incorrect. 

###  Suggest a fix
As per Tzach, it is possible to jump from 2022.2 to 2024.1 straight. https://forum.scylladb.com/t/scylladb-enterprise-release-2024-1-0/1292 

[Upgrade ScyllaDB Enterprise from 2022.2.y to **2023.1.z**](https://enterprise.docs.scylladb.com/branch-2024.1/upgrade/upgrade-enterprise/upgrade-guide-from-2022.2-to-2024.1/upgrade-guide-from-2022.2-to-2024.1-generic.html) link text should be corrected to Upgrade ScyllaDB Enterprise from 2022.2.y to **2024.1.z** the actual link is correct.

**Comment by tzach** [comment]
Closing for a Enterprise issue
