### ISSUE TITLE
topology_custom test_replace_ignore_nodes fails - driver fails to reconnect

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#17672]
We are seeing this a lot recently in CI and promotion

Logs:
[scylla-1229.log](https://github.com/scylladb/scylladb/files/14521131/scylla-1229.log)
[scylla-1231.log](https://github.com/scylladb/scylladb/files/14521133/scylla-1231.log)
[scylla-1235.log](https://github.com/scylladb/scylladb/files/14521135/scylla-1235.log)
[scylla-1242.log](https://github.com/scylladb/scylladb/files/14521136/scylla-1242.log)
[scylla-1251.log](https://github.com/scylladb/scylladb/files/14521138/scylla-1251.log)
[scylla-1256.log](https://github.com/scylladb/scylladb/files/14521139/scylla-1256.log)
[scylla-1260.log](https://github.com/scylladb/scylladb/files/14521140/scylla-1260.log)
[scylla-1282.log](https://github.com/scylladb/scylladb/files/14521142/scylla-1282.log)
[stdout.log](https://github.com/scylladb/scylladb/files/14521145/stdout.log)

**Comment by denesb** [comment]
@kbr-scylla

**Comment by kbr-scylla** [comment]
@denesb the stdout.log file you posted is truncated
```
18:46:56.392 DEBUG> Sent StartupMessage on <CustomConnection(140689107171152) 127.217.22.52:9042>
18:46:56.392 DEBUG> Got ReadyMessage on new connection (140689107171152) from 127.217.22.52:9042
18:46:56.393 DEBUG> [c
...[truncated 3315482 chars]...
._connect_host_in_lbp
  File "cassandra/cluster.py", line 3737, in cassandra.cluster.ControlConnection._try_connect
```

we need the full file. What's the CI link?

**Comment by mykaul** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7170/ ?

**Comment by denesb** [comment]
> https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7170/ ?

Yes.

**Comment by kbr-scylla** [comment]
Two failures
[topology_custom.test_replace_ignore_nodes.1.log](https://github.com/scylladb/scylladb/files/14521827/topology_custom.test_replace_ignore_nodes.1.log)
[topology_custom.test_replace_ignore_nodes.2.log](https://github.com/scylladb/scylladb/files/14521828/topology_custom.test_replace_ignore_nodes.2.log)

**Comment by kbr-scylla** [comment]
Closing as duplicate
