### ISSUE TITLE
Concurrent removenode-s are not allowed due to legacy storage service API lock

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#17681]
If issuing two removenode-s, the 2nd one would likely fail because of API lock (or rather a guard) in storage service.
This may lead to nasty side effects, e.g.

Cluster with 4+ nodes {A, B, C, D, ...}
Tablet with replicas on {A, B}
Tablet migration B->C starts
Node B goes down while streaming
Operator calls removenode B via node A // this marks B as ingored, but waits until removenode cycles through raft log
State machine switches to cleanup_target stage calling cleanup on C
Node C goes down while doing it
Operator calls removenode C via node A, but this operation fails early since removenode B is in progress
The topology state machine gets stuck in cleanup_target stage waiting for C to be removed

Running removenode(C) against some other D helps to unlock this

**Comment by xemul** [comment]
from https://github.com/scylladb/scylladb/issues/16527

**Comment by kbr-scylla** [comment]
We need to take down the API lock on raft-topology path.
Why didn't our concurrent removenode tests catch this? @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> We need to take down the API lock on raft-topology path. Why didn't our concurrent removenode tests catch this? @gleb-cloudius

Which test? It only matters if "ignore nodes" are specified (which us a recent change). Otherwise it does not matter where removenode sleeps.

**Comment by kbr-scylla** [comment]
@xemul would you say this is a release blocker for tablets?

**Comment by xemul** [comment]
Not a blocker, but it's pretty funny limitation. Like if sqlsh told you -- cannot execute your SELECT on this node, try me against some other one in the cluster

**Comment by mykaul** [comment]
> Not a blocker, but it's pretty funny limitation. Like if sqlsh told you -- cannot execute your SELECT on this node, try me against some other one in the cluster

Will defer from 6.0 soon.
