### ISSUE TITLE
Sporadic failure in test_simple_bypass_cache

### ISSUE THREAD

**Issue by pwrobelse** [scylladb/scylladb#17704]
In CI run https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/362/testReport/ the following error occurred in `bypass_cache_test.TestBypassCache.test_simple_bypass_cache`:

```
AssertionError: Running query that is suppose to read from disk following errors found:
  Metric scylla_sstables_index_page_cache_misses should not be changed, before:3, after:5
  Metric scylla_sstables_index_page_cache_populations should not be changed, before:3, after:5
assert not ['Metric scylla_sstables_index_page_cache_misses should not be changed, before:3, after:5', 'Metric scylla_sstables_index_page_cache_populations should not be changed, before:3, after:5']
```

The log files can be found below:
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/362/artifact/logs-full.release.000/

**Comment by kbr-scylla** [comment]
@denesb aren't you working on this? I saw in your weekly
> unflake bypass cache test (CI stability)

**Comment by denesb** [comment]
We have a dtest issue for this: https://github.com/scylladb/scylla-dtest/issues/4033

**Comment by denesb** [comment]
And yes, I have an open PR with a fix: https://github.com/scylladb/scylla-dtest/pull/4040

**Comment by kbr-scylla** [comment]
Thx, closing as dup
