### ISSUE TITLE
auth_cluster.test_auth_raft_command_split connection failure

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#17713]
Seen on master gating https://jenkins.scylladb.com/job/scylla-master/job/next/7359/testReport/junit/(root)/non-boost%20tests/Build___aarch64___Unit_Tests_aarch64___auth_cluster_test_auth_raft_command_split_dev_1/

```
=================================== FAILURES ===================================
_________________________ test_auth_raft_command_split _________________________

manager = <test.pylib.manager_client.ManagerClient object at 0xffff429a69d0>

    @pytest.mark.asyncio
    async def test_auth_raft_command_split(manager: ManagerClient) -> None:
        servers = await manager.servers_add(3)
    
        cql = manager.get_cql()
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
        await manager.servers_see_each_other(servers)
    
        initial_perms = await cql.run_async("SELECT * FROM system_auth_v2.role_permissions")
    
        shared_role = "shared_role_" + unique_name()
        await cql.run_async(f"CREATE ROLE IF NOT EXISTS {shared_role}")
    
        users = ["user_" + unique_name() for _ in range(30)]
        for user in users:
            # if not exists due to https://github.com/scylladb/python-driver/issues/296
            await cql.run_async(f"CREATE ROLE IF NOT EXISTS {user}")
            await cql.run_async(f"GRANT ALL ON ROLE {shared_role} TO {user}")
    
        # this will trigger cascade of deletes which should be packed
        # into raft commands in a way that none exceeds max_command_size
        await manager.driver_connect(server=servers[0])
        cql = manager.get_cql()
        async with inject_error(manager.api, servers[0].ip_addr,
                                'auth_announce_mutations_command_max_size'):
>           await cql.run_async(f"DROP ROLE IF EXISTS {shared_role}", execution_profile='whitelist')
E           cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.82.77.1:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})

test/auth_cluster/test_auth_raft_command_split.py:43: NoHostAvailable
```

The issue is probably more than just connection failure (the test involves adding/removing nodes), but I'm not sure about the exact failure,
It's a new test added on https://github.com/scylladb/scylladb/pull/16578 
@nuivall please take a look

**Comment by nuivall** [comment]
@mykaul What platform/arm label means in this context? That it's happening only on arm and not other platforms? Or  first random failure happened to be on arm?

**Comment by mykaul** [comment]
> @mykaul What platform/arm label means in this context? That it's happening only on arm and not other platforms? Or first random failure happened to be on arm?

Yes to both... If we see that it's happening on other platforms, I'd remove it. Usually ARM is breaking as the tests are considerably slower on the platform.

**Comment by kbr-scylla** [comment]
@nuivall I think we need more `wait_for_cql_and_get_hosts`

**Comment by nuivall** [comment]
> @nuivall I think we need more wait_for_cql_and_get_hosts

or we need less need to put them everywhere...

if this is the problem it may be solved inside testing lib, for instance some other test:
```
async def test_sticky_coordinator_enforced(manager: ManagerClient) -> None:
    await manager.servers_add(2, cmdline=['--logger-log-level', 'paging=trace'])

    cql = manager.get_cql()

    await cql.run_async("create keyspace ks"
                        " with replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 2}")
```
is also issuing CQL command right after get_cql with potentially more such cases.

I can make a blind fix as I am not able to reproduce locally (100 runs, on debug mode).

**Comment by tchaikov** [comment]
[scylla-85.log](https://github.com/scylladb/scylladb/files/14581799/scylla-85.log)
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7329

[scylla-86.log](https://github.com/scylladb/scylladb/files/14581800/scylla-86.log)
[scylla-87.log](https://github.com/scylladb/scylladb/files/14581801/scylla-87.log)
[auth_cluster.test_auth_raft_command_split.3.log](https://github.com/scylladb/scylladb/files/14581802/auth_cluster.test_auth_raft_command_split.3.log)
