### ISSUE TITLE
Do we need to modify Alternator's documentation about where auth keys are taken from?

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#17718]
After commit 9cb1f111d5db9b88d138eb22e307d029e950fb34 by @nuivall (merged a few days ago), Alternator has apparently started to read from `system_auth_v2.roles` instead of `system_auth.roles`. I'm not up-to-date on why this was changed and what this change means, but I'm worried that now the instructions in `docs/alternator/compatibility.md` on how to find the secret key are out of date (refer to the wrong table) and should be updated.

The commit actually includes a sentence which refers to this documentation, but I don't understand what it means or why:

> Docs will be updated later, when auth-v2 is enabled as default.

So either the doc should be updated now, or as the commit message suggests - later (if later, please explain why).
But in either case we should have an issue open, so I'm creating one.

Also recently it has come to my attention that it may not be easy to understand the instructions we have regarding authorization, and there are some unclear points (like needing to enable password authentication in CQL first), so we may want to use this opportunity to make the instructions in this area clearer.

**Comment by fruch** [comment]
@nuivall 

alternator internal docs still point to the old variation:
https://github.com/scylladb/scylladb/blob/ccbb9f534302935d078de302b11037e4d7143388/test/alternator/README.md?plain=1#L110

Also SCT isn't updated to support it:
https://github.com/scylladb/scylla-cluster-tests/blob/57420794127e7335b5b2dd3a6af1b25a66e1cd94/sdcm/tester.py#L1013

Just run into it, trying on of the alternator TTL cases that wasn't running in a while

**Comment by nuivall** [comment]
latest change in https://github.com/scylladb/scylladb/pull/18769 should bring it up to date
