### ISSUE TITLE
Scylla alternator abnormal latency and http connection

### ISSUE THREAD

**Issue by codingcuisg** [scylladb/scylladb#17744]
Hello Team,

We are using scylla alternator with 3 nodes, recently started seeing abnormal behaviour multiple times

p99 latency spike on a node, and after restart the node the same case happens on another node
<img width="651" alt="image" src="https://github.com/scylladb/scylladb/assets/33821205/55d6f32a-dd35-4ae3-81d6-649f5d80b596">

<img width="381" alt="image" src="https://github.com/scylladb/scylladb/assets/33821205/232ce7b7-befe-43f5-bb56-1886c0403d80">

upon checking, the `scylla_httpd_connections_current` looks consistent with the latency pattern
<img width="1681" alt="image" src="https://github.com/scylladb/scylladb/assets/33821205/9623e8ce-adb5-458f-ab25-9e01d29e1c5b">

read / write pattern
<img width="809" alt="image" src="https://github.com/scylladb/scylladb/assets/33821205/30fb375d-6f71-4062-a83d-a617f85c6e9d">

There was no log during this period, would like to understand how to further troubleshoot this ?

**Comment by mykaul** [comment]
It'd be great if you could share the version used, and logs around that incident(s).

**Comment by codingcuisg** [comment]
scylla OSS version is on 5.0.5

for the logs:
1. this strange pattern started happening after a semaphore timeout `[shard 11] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 1/100 count and 16776/176622141 memory resources: timed out, dumping permit diagnostics`
2. however we also observed this case without any log from scylla 

wondering if there is any metric / log can help further troubleshoot, since the http connection increased but the replica read were not changed. we were suspecting that might be some issues with the ddb http client (which is developed using aws go sdk v2) but didn't have enough metric to support this guess 

thanks !

**Comment by mykaul** [comment]
5.0.x is not supported any more - I suggest upgrading to 5.2 or 5.4.
Even 5.0.5 is not the latest in the 5.0.x series - see https://forum.scylladb.com/tag/open-source-5-0 for release notes of later patche releases.
There were multiple fixes to some issues around reader concurrency semaphore that might be applicable here.
For example:
Stability: reader_concurrency_semaphore: inactive reader eviction is too aggressive, leading to Reads timing out, especially in range scans. [#11803 1](https://github.com/scylladb/scylladb/issues/11803)
(from https://forum.scylladb.com/t/release-scylladb-5-0-13-the-last-patch-release-of-the-5-0-branch/537 )
or:
Stability: reader_concurrency_semaphore: inactive readers are only evicted on the admission path [#11770 4](https://github.com/scylladb/scylladb/issues/11770)
(from https://forum.scylladb.com/t/release-scylladb-5-0-11/431 )

**Comment by codingcuisg** [comment]
Thanks for your suggestion, we are evaluating 5.2 at this moment but still couldn't locate the exact root cause

Understand the starting point is possibly that semaphore timeout or no semaphore timeout but read latency increased (write latency may also be affected since we use update item api which will read the existing record internally). The following excess of new connections make the thing worse. 

We suspected the client issue mainly because the issue always happened on a single node randomly, and the throughput (read qps per node) were stable and balanced 

Curious to know, what is the recommended setup of http connections for alternator use case ? i.e number of connections, timeout config, keep-alive timing ?

**Comment by nyh** [comment]
I'm closing this issue for the reasons explained above. Please reopen if you still it see with a more recent version.
