### ISSUE TITLE
migration_test.py::TestLoadAndStream::test_load_and_stream_2_columns_pk[3_0_md] fails due to missing rows after load-n-stream with tablets

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#17748]
```
   def test_load_and_stream_2_columns_pk(self):
        """
        Test for the feature load_and_stream:
        https://github.com/scylladb/scylla/commit/df3ef800c20c60d7929ffa600649793aa6c73064
    
        Test data was created on the 4-nodes cluster, RF=3, Scylla was started with SMP 1
        - Load and stream sstables of table with 2 columns primary key and validate the data
        """
  ...
        for node in self.cluster.nodelist():
>           self.check_number_of_rows(node, self.EXPECTED_ROWS_NUMBER, keyspace=self.KEYSPACE_NAME, table=self.TABLE_NAME)
...
>       assert result[0].count == expected_number_of_rows, f"Expected {expected_number_of_rows} rows in {keyspace}.{table} on {node.name}. " f"Got {result[0].count}"
E       AssertionError: Expected 1000 rows in keyspace1.standard1 on node1. Got 248
E       assert 248 == 1000
E        +  where 248 = Row(count=248).count
```
[1710156056335_migration_test.py TestLoadAndStream test_load_and_stream_2_columns_pk[3_0_md].zip](https://github.com/scylladb/scylladb/files/14567908/1710156056335_migration_test.py.TestLoadAndStream.test_load_and_stream_2_columns_pk.3_0_md.zip)
[dtest-gw1.log](https://github.com/scylladb/scylladb/files/14567909/dtest-gw1.log)

see https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/164

**Comment by tchaikov** [comment]
@raphaelsc hi Raphel, do you happen to know if this issue is currently being worked on by us? if yes, do we have a PR or an issue for it?

**Comment by raphaelsc** [comment]
Fix just landed on master: https://github.com/scylladb/scylladb/commit/6115c113feece3afbdbe0bc0711d330d35a0896d

**Comment by tchaikov** [comment]
thanks @raphaelsc ! i am closing this issue then. dup of #17733
