### ISSUE TITLE
system_tables_test.TestRuntimeInfoTable.test_cache_metrics: AssertionError metrics before and after flush

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#17778]
Seen on master next
https://jenkins.scylladb.com/job/scylla-master/job/next/7373/testReport/junit/system_tables_test/TestRuntimeInfoTable/Build___x86___dtest_with_topology_changes___test_cache_metrics/

Same for 2024 (last week)
https://jenkins.scylladb.com/job/enterprise-2024.1/job/next/116/testReport/junit/system_tables_test/TestRuntimeInfoTable/Tests___Sanity_Tests_RAFT___test_cache_metrics/

```
self = <system_tables_test.TestRuntimeInfoTable object at 0x7f8d549d28d0>

    @pytest.mark.single_node
    def test_cache_metrics(self):
        """
        Test scenario:
        1. Start one-node Scylla cluster
        2. Create one new table with data
        3. Select the cache metrics values from the table (group='cache')
        4. Flush the memtable for created table
        5. Select the cache metrics again and compare the results
        6. Send requests to the cashed data from flushed table
        7. Select the cache metrics one more time and compare the values
        """
    
        cluster = self.prepare_cluster(nodes=1)
        node = cluster.nodelist()[0]
        node_ip_address = node.address()
    
        number_of_rows = 100
    
        with self.patient_cql_connection(node) as session:
            logger.info("Creating a new keyspace '%s' and 1 table with data...", self.TEST_KEYSPACE)
            table = self.create_tables_with_data(session=session, keyspace_name=self.TEST_KEYSPACE, replication_factor=1, table_name_prefix="table", number_of_tables=1, number_of_rows=number_of_rows)[0]
    
            logger.info("Getting the cache metrics values from %s.%s on node %s before flush...", self.KEYSPACE_NAME, self.TABLE_NAME, node_ip_address)
            query_to_run = f"select item, value from {self.KEYSPACE_NAME}.{self.TABLE_NAME} where group = 'cache';"
            result = self.run_query_on_node(session=session, query=query_to_run)
            metrics_before_flush = {row.item: int(row.value) for row in result if row.item not in ["hit_rate_recent", "hit_rate_total"]}
    
            logger.info("Flushing the table %s...", table)
            node.nodetool(cmd=f"flush {table.replace('.', ' ')}")
    
            logger.info("Getting the cache metrics values from %s.%s on node %s after flush...", self.KEYSPACE_NAME, self.TABLE_NAME, node_ip_address)
            result = self.run_query_on_node(session=session, query=query_to_run)
            metrics_after_flush = {row.item: int(row.value) for row in result if row.item not in ["hit_rate_recent", "hit_rate_total"]}
    
        logger.info("Comparing the results...")
>       assert metrics_after_flush["entries"] - metrics_before_flush["entries"] == number_of_rows
E       assert (140 - 39) == 100

system_tables_test.py:805: AssertionError
```

**Comment by benipeled** [comment]
@fruch ^^

**Comment by benipeled** [comment]
And again (enterprise) https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2854/testReport/junit/system_tables_test/TestRuntimeInfoTable/Build___x86___dtest_with_topology_changes___test_cache_metrics/

**Comment by dani-tweig** [comment]
@denesb 
Can you check if this is a flush problem?

**Comment by denesb** [comment]
> @denesb Can you check if this is a flush problem?

This is very likely a test issue. I will have a look.

**Comment by denesb** [comment]
> @denesb didn't you (or someone else?) fix a similar problem a few days ago? We had a test for cache metrics, and these metrics changed by some random background Raft activity that did some internal requests and incremented the cache metrics.

Yes, I fixed a test related to sstable index cache metrics. This test could be similar but I didn't check yet.

**Comment by fruch** [comment]
history show, it started failing like this since Feb 11, and since then mostly on the topology changes jobs:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/0ad1dcd0-eb54-11ee-81c7-3986d18dafd5

regardless this test seem to be assuming change info is accurate to the exact number of queries, and it's not clear what changed since it was written (2 years ago)

**Comment by Annamikhlin** [comment]
same here:
https://jenkins.scylladb.com/job/enterprise-2024.1/job/next/143/testReport/junit/system_tables_test/TestRuntimeInfoTable/Tests___dtest_RAFT___test_cache_metrics/

**Comment by Annamikhlin** [comment]
seen again on 2024.1
https://jenkins.scylladb.com/job/enterprise-2024.1/job/next/147/testReport/junit/system_tables_test/TestRuntimeInfoTable/Tests___dtest_RAFT___test_cache_metrics/

**Comment by mykaul** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/next/7529/testReport/junit/system_tables_test/TestRuntimeInfoTable/Build___x86___dtest_with_topology_changes___test_cache_metrics/

**Comment by kbr-scylla** [comment]
> I wonder if it's always an off by 1? 

Nope
https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/295/testReport/junit/system_tables_test/TestRuntimeInfoTable/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split001___test_cache_metrics/
`assert (136 - 33) == 100`

**Comment by lkshminarayanan** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8921/testReport/system_tables_test/TestRuntimeInfoTable/Tests___dtest_with_topology_changes___test_cache_metrics/

**Comment by mykaul** [comment]
https://jenkins.scylladb.com/job/scylla-6.0/job/gating-dtest-release-with-consistent-topology-changes/65/testReport/system_tables_test/TestRuntimeInfoTable/FullDtest___full_split000___test_cache_metrics/
[test_cache_metrics_dtest-gw0.log](https://github.com/user-attachments/files/15589839/test_cache_metrics_dtest-gw0.log)
[test_cache_metrics_node1.log](https://github.com/user-attachments/files/15589843/test_cache_metrics_node1.log)

**Comment by Annamikhlin** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/next/7781/testReport/junit/system_tables_test/TestRuntimeInfoTable/Build___x86___dtest_with_topology_changes___test_cache_metrics/

**Comment by mykaul** [comment]
@denesb - this needs attention, as it happens too often.

**Comment by denesb** [comment]
> @denesb - this needs attention, as it happens too often.

https://github.com/scylladb/scylla-dtest/pull/4414
