### ISSUE TITLE
Mark `initial_token` as `Deprecated`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17845]
```cpp
    , initial_token(this, "initial_token", value_status::Used, {/* N/A */},
        "Used in the single-node-per-token architecture, where a node owns exactly one contiguous range in the ring space. Setting this property overrides num_tokens.\n"
        "If you not using vnodes or have num_tokens set it to 1 or unspecified (#num_tokens), you should always specify this parameter when setting up a production cluster for the first time and when adding capacity. For more information, see this parameter in the Cassandra 1.1 Node and Cluster Configuration documentation.\n"
        "This parameter can be used with num_tokens (vnodes) in special cases such as Restoring from a snapshot.")
```

This configuration parameter is not supported in raft-topology mode (we ignore it). Raft-topology will be enforced for new clusters in 6.0. You could theoretically still use it when joining a node to a cluster that upgraded from 5.4 but did not yet do the upgrade-to-raft-topology-procedure; but I see no point in keeping it just for that case.

**Comment by kbr-scylla** [comment]
Dtest will need to be adjusted: https://github.com/scylladb/scylla-dtest/issues/4069

**Comment by tzach** [comment]
`initial_token` is documented in:

- [ ] https://opensource.docs.scylladb.com/stable/reference/configuration-parameters.html#confval-initial_token (extract directly from the config
- [ ] https://opensource.docs.scylladb.com/stable/reference/glossary.html#term-Token

**Comment by kbr-scylla** [comment]
Ah, if it's used by restore-from-backup procedures, then we'll have to support it! @kostja @gleb-cloudius

**Comment by gleb-cloudius** [comment]
There is something wrong here. Documentation says "Used in the single-node-per-token architecture, where a node owns exactly one contiguous range in the ring space", but the option allow specifying multiple ranges.

**Comment by gleb-cloudius** [comment]
> Ah, if it's used by restore-from-backup procedures, then we'll have to support it! @kostja @gleb-cloudius

We need to revise the procedure. Will it work with raft at all or raft needs to be enabled through recovery after the restore?

**Comment by kostja** [comment]
@kbr-scylla I don't undestand how it's used. Do you?

**Comment by kbr-scylla** [comment]
I **guess** that it's used to recreate a cluster with the same token distribution, to which we can then upload data as it was in the original cluster.

An alternative is to redistribute data when uploading. We nay already support a procedure like this, in which case `initial_token` is not necessary, but Manager would have to be adjusted.

cc @avikivity @Michal-Leszczynski @karol-kokoszka

**Comment by gleb-cloudius** [comment]
> I guess that it's used to recreate a cluster with the same token distribution, to which we can then upload data as it was in the original cluster.

Why not restore system tables instead?

**Comment by kostja** [comment]
> I **guess** that it's used to recreate a cluster with the same token distribution, to which we can then upload data as it was in the original cluster.
> 
> An alternative is to redistribute data when uploading. We nay already support a procedure like this, in which case `initial_token` is not necessary, but Manager would have to be adjusted.
> 
> cc @avikivity @Michal-Leszczynski @karol-kokoszka

I agree with @gleb-cloudius here, seems like by restoring the local tables of the future cluster leader we are guaranteed to gt the right tokens. The tokens could be inconsistent before, when they were managed by gossip, now they are guaranteed to be the same on all of the nodes.

**Comment by kostja** [comment]
One thing to consider when performing a backup is to do suspend group0 operations for  a while and finish all ongoing work. then grab the backup of the systme tables. Not manipulate with the config file.

**Comment by kbr-scylla** [comment]
@kostja if restoring local tables is the obvious and correct solution, why do we need to implement "describe schema with mutations"? https://github.com/scylladb/scylladb/issues/16482 It shouldn't be needed in that case.

We need to understand the actual restore procedures that are used in the field and by Manager...

**Comment by avikivity** [comment]
There are two restore procedures. One is where creating the cluster is decoupled from populating it with data (it could have different topology). Another is where we create a cluster of exactly the same shape.

The first is more general, so must be supported. The second is applicable in a subset of cases, but is faster.

@roydahan do you know which ones are tested?

**Comment by avikivity** [comment]
But, initial_token is useless, since it predates vnodes.

**Comment by Michal-Leszczynski** [comment]
> https://github.com/scylladb/scylla-manager/blob/ef46c8bd68e824edbaa08d32cae8b976152d1b6d/ansible/restore/restore.yaml#L87 (Manager, Ansible restore script)

This ansible script is a way for performing restore previous to SM 3.1 and we don't support it anymore. SM 3.1 restore task does not use `initial_token`.

Ansible script restored data only into a cluster with the same topology, but the SM 3.1 restore task should work for any topology.

In general, SM don't backup any keyspaces with `LocalStrategy` (except for `system_schema` which causes other mentioned problems). I don't know how such tables could be restored into a cluster with different topology.

**Comment by kbr-scylla** [comment]
Good. Thanks for all the explanations.

We can get rid of `initial_token`.

**Comment by kbr-scylla** [comment]
Field will have to switch to use the same as latest Manager, versions, i.e. load & stream which redistributes data according to newest tokens.

cc @vladzcloudius

**Comment by roydahan** [comment]
> There are two restore procedures. One is where creating the cluster is decoupled from populating it with data (it could have different topology). Another is where we create a cluster of exactly the same shape.
> 
> The first is more general, so must be supported. The second is applicable in a subset of cases, but is faster.
> 
> @roydahan do you know which ones are tested?

AFAIK we test both but only using SM 3.1 and above.

**Comment by vladzcloudius** [comment]
This parameter is heavily used in the field for Ideal Token Ring implementation.
Please consider discarding this patch, @kbr-scylla @kostja

**Comment by vladzcloudius** [comment]
> I **guess** that it's used to recreate a cluster with the same token distribution, to which we can then upload data as it was in the original cluster.
> 
> An alternative is to redistribute data when uploading. We nay already support a procedure like this, in which case `initial_token` is not necessary, but Manager would have to be adjusted.
> 
> cc @avikivity @Michal-Leszczynski @karol-kokoszka

Guys, I have a strong feeling you don't understand what this parameter is used for.
It's used to explicitly specify tokens for the bootstrapping node instead of allowing the bootstrapping node to (randomly) choose ones for itself.

If you need further clarification, I suggest we have a call.

**Comment by kbr-scylla** [comment]
>  It's used to explicitly specify tokens for the bootstrapping node instead of allowing the bootstrapping node to (randomly) choose ones for itself.

What do humans have legs for?
answer A: so you can move them back and forth
answer B: so you can walk

I'm more interested in the B type answer.

I.e.:
> This parameter is heavily used in the field for Ideal Token Ring implementation.

in that case we indeed have to support it.

**Comment by mykaul** [comment]
@vladzcloudius  - please share (offline/enterprise) the ideal token ring stuff (I've seen the script) - need to see if/how it'll be done with Tablets!

**Comment by tzach** [comment]
> This parameter is heavily used in the field for Ideal Token Ring implementation.

The questions are:
- Does it make sense with Tablets
- Does it make sense with a mix of tablets and vNodes

**Comment by vladzcloudius** [comment]
> > This parameter is heavily used in the field for Ideal Token Ring implementation.
> 
> The questions are:
> 
>     * Does it make sense with Tablets
> 
>     * Does it make sense with a mix of tablets and vNodes

My request was completely in the context of the current model and there is a very long time from now forward while we still need to support it (the current model).

The issue wasn't filed in the context of Tablets but rather in the context of Raft-managed tolpology - which is **already** in use.
Hence I don't understand why Tablets are even mentioned in this context, @tzach @mykaul.
I think it's absolutely irrelevant.

**Comment by kostja** [comment]
* Vladislav Zolotarov ***@***.***> [24/03/18 19:02]:
> This parameter is heavily used in the field for Ideal Token Ring
> implementation.
> Please consider discarding this patch, @kbr-scylla @kostja 

Thanks for your input. 

Now that we have a centralized topology coordinator, we can 
always produce an ideal token ring. It should be perhaps a 20 line
patch.

Could you file a feature request?

And wrt this deprecation request, @kbr-scylla will most likely
take another route.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by vladzcloudius** [comment]
> * Vladislav Zolotarov ***@***.***> [24/03/18 19:02]:
> This parameter is heavily used in the field for Ideal Token Ring implementation. Please consider discarding this patch, @kbr-scylla @kostja
> Thanks for your input. Now that we have a centralized topology coordinator, we can always produce an ideal token ring. It should be perhaps a 20 line patch. Could you file a feature request? And wrt this deprecation request, @kbr-scylla will most likely take another route.
> […](#)
> -- Konstantin Osipov, Moscow, Russia

Done

**Comment by kbr-scylla** [comment]
Opened https://github.com/scylladb/scylladb/issues/17893, closing this one
