### ISSUE TITLE
docs: Issue in page Nodetool status

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#17840]
I would like to report an issue in page https://opensource.docs.scylladb.com/master/operating-scylla/nodetool-commands/status

### Problem

The optional keyspace parameter to `nodetool status` is under-documented.
The page only states that:
```
status - This command prints the cluster information for a single keyspace or all keyspaces.
```

But the syntax is unclear, and there's no example for it.
We should also explain that the effective ownership is provided only when a keyspace parameter is given.
Without it, the command prints `?` in that column.

@denesb what are going to be the ramifications for tablets?
IIUC there is going to be another optional parameter to state a table in the given keyspace.
Will we print `?` for tablet-enabled keyspaces if the table is omitted, or are we going to calculate the ownership over all tables in that keyspace?

Also, there is a table for the output format of `nodetool status` which has those captions: Parameter, Description.
Using `Parameter` It is confusing since usually Parameters refer to the command parameters not to the command output.
Need a better name for that, e.g. `property` or `attribute`?
Cc @annastuchlik 

Lastly, some properties currently documented are never printed with Scylla, like the "Moving" state.

Cc @tzach

**Comment by bhalevy** [comment]
Cc @ShlomiBalalis

**Comment by denesb** [comment]
> @denesb what are going to be the ramifications for tablets? IIUC there is going to be another optional parameter to state a table in the given keyspace. Will we print `?` for tablet-enabled keyspaces if the tablet is omitted, or are we going to calculate the ownership over all tables in that keyspace?

Yes, we will have an optional `table` parameter. Without it, we will just print `?` for the load of tablet keyspaces.
