### ISSUE TITLE
Maintenance socket: node hangs on startup instead of throwing error when maintenance socket path has >108 chars

### ISSUE THREAD

**Issue by margdoc** [scylladb/scylladb#17862]
This code throws an error:
https://github.com/scylladb/scylladb/blob/88119006022d52b03824efb756ebc01734444a5a/transport/controller.cc#L152-L154
, but
https://github.com/scylladb/scylladb/blob/88119006022d52b03824efb756ebc01734444a5a/transport/controller.cc#L246
hangs on the stack unwinding caused by this error.

Bug introduced in 6b178f9a4a90176ed4534a70468b63efd2e9dfc5.

**Comment by AbhinavKumarJha** [comment]
This issue is non-reproducible. Upon trying to spin a fresh scylla node with long maintenance socket path, the node shuts down successfully throwing the above error, it doesn't hang.

The above behavior is confirmed by @kbr-scylla as well.

**Comment by kbr-scylla** [comment]
Hmm, this looks like something that could have fixed our issue: https://github.com/scylladb/scylladb/pull/20212
