### ISSUE TITLE
get_multi_slice() will return incorrect range for reversed slices with certain composite pairs

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#1787]
Thrift API doc says: "When reversed is true, start will determine the right end of the range while finish will determine the left, meaning start must be >= finish." 

So, a reversed slice containing [{5, eoc=1}, {5, eoc=-1}] should return values from range [{5, eoc=-1}, {5, eoc=1}] but in reverse order. It should return 5.

However, our `make_non_overlapping_ranges()` would return an open ended range for such input:

```
            auto range = mapper(std::move(cslice));
            if (reversed) {
                range.reverse();
                if (is_wrap_around(range)) {
                    // If a wrap around range is still wrapping after reverse, then it's (a, a). This is equivalent
                    // to an open ended range.
                    range = wrapping_range<RangeType>::make_open_ended_both_sides();
                }
            }
```

The `range` will hold (5, 5), which after `reverse()` would still be wrapping - `(5, 5)`.

**Comment by tchaikov** [comment]
won't be fixed because Thrift is dropped. see #18416
