### ISSUE TITLE
sstables::malformed_sstable_exception during upgrade with consistent topology changes

### ISSUE THREAD

**Issue by dawmd** [scylladb/scylladb#17873]
When trying to upgrade Scylla when using consistent topology changes, the following error occurs during the very early phase of initialization:

```log
ERROR 2024-03-18 16:24:28,362 [shard 0:main] storage_proxy - Exception when communicating with 127.0.77.1, to read from system.topology: sstables::malformed_sstable_exception (Failed to read partition from SSTable /home/dawidmedrek/.dtest/dtest-__lxq72a/test/node1/data/system/topology-5be1feb3929e3df98da8d771c36129a0/me-3gej_16so_172xc28t9xuy9cmbh2-big-Data.db due to Column current_cdc_generation_timestamp missing in current schema)
```

I list the steps to create a minimal example reproducing the issue, but it occurs in a larger cluster as well (3 nodes); in that case, the problem happens when upgrading the first node as well.

**Reproduction steps**
1. Create a cluster consisting of one node using `--experimental-features=consistent-topology-changes`
2. When the node has started, perform an upgrade

**Installation details**
* Scylla version (or git commit hash): a4e8bea679970059974388e9fdebee72ef6610bd
* Cluster size: 1
* OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 38, kernel Linux 6.7.7-100.fc38.x86_64
* Initial version of Scylla: release:5.4
* Features: consistent topology changes

For what it's worth, I was using a dist-unified package when I experienced the issue.

**Comment by mykaul** [comment]
Sounds like it's CDC related somehow? @kbr-scylla  ?

**Comment by kbr-scylla** [comment]
The particular failure you're getting is because there were backward-incompatible changes done to `system.topology` definition between 5.4 and 6.0.
