### ISSUE TITLE
load-and-stream disregards write replica selector during tablet migration which may violate tablet consistency when migration is reverted

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#17892]
It adds the pending replica to the set of streamed-to replicas regardless of the stage (`tablet_sstable_streamer::get_endpoints`).

So it will write to the pending replica even in the allow_write_both_read_old stage. But in this stage the write selector (`tablet_transition_info.writes`)  is still "previous" (see `get_selector_for_writes()`). This is relied upon when rolling back migration, which doesn't clean up the pending replica. It jumps from `allow_write_both_read_old` directly to `revert_migration`. This may leave data on the node which is no longer a replica, which violates the invariant:

```
When tablet is not in transition, the following invariants hold:

1. The storage layer (database) on any node contains writes for keys which belong to the tablet only if
    that shard is one of the current tablet replicas.
```

Later, when tablet replica is migrated back to the previous pending replica, that data will reappear and may cause data resurrection issues as it was not participating in repair.

**Comment by raphaelsc** [comment]
@tgrabiec isn't it enough that we retrieve pending replica (if any) with        
` return tm.get_endpoint_for_host_id(tinfo->pending_replica.host);` ?

That's implemented for tablets as:

```
        switch (info->writes) {
            case write_replica_set_selector::previous:
                return {};
            case write_replica_set_selector::both:
                tablet_logger.trace("get_pending_endpoints({}): table={}, tablet={}, replica={}",
                                    search_token, _table, tablet, info->pending_replica);
                return {_tmptr->get_endpoint_for_host_id(info->pending_replica.host)};
            case write_replica_set_selector::next:
                return {};
        }
```

**Comment by raphaelsc** [comment]
> @tgrabiec isn't it enough that we retrieve pending replica (if any) with ` return tm.get_endpoint_for_host_id(tinfo->pending_replica.host);` ?
> 
> That's implemented for tablets as:
> 
> ```
>         switch (info->writes) {
>             case write_replica_set_selector::previous:
>                 return {};
>             case write_replica_set_selector::both:
>                 tablet_logger.trace("get_pending_endpoints({}): table={}, tablet={}, replica={}",
>                                     search_token, _table, tablet, info->pending_replica);
>                 return {_tmptr->get_endpoint_for_host_id(info->pending_replica.host)};
>             case write_replica_set_selector::next:
>                 return {};
>         }
> ```

Ah wait, it's not actually used. Perhaps the fix is about using get_pending_endpoints() indeed. Thanks for the report.
