### ISSUE TITLE
raft topology: support `initial_token`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17893]
After the discussion in https://github.com/scylladb/scylladb/issues/17845, and in particular input from @vladzcloudius , I conclude that we need to continue supporting `initial_token` in Raft-based topology. Apparently, the parameter is being used in Field scripts:
- for backup&restore,
- for "ideal token ring" token allocation

**Comment by mykaul** [comment]
CC @regevran , @bhalevy - on how to set up a cluster with specific token distribution (for 1:1 restore work)
