### ISSUE TITLE
compaction_test.py::TestCompaction::test_compaction_delete_tombstone_gc unexpected deleted partitions found

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#17947]
params=[immediate-SizeTieredCompactionStrategy]

Seen in: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/608/testReport/junit/compaction_test/TestCompaction/FullDtest___full_split002___test_compaction_delete_tombstone_gc_immediate_SizeTieredCompactionStrategy_/

```
self = <compaction_test.TestCompaction object at 0x7f2be0ac5a10>
session = <cassandra.cluster.Session object at 0x7f2bdc887f50>
node = <ccmlib.scylla_node.ScyllaNode object at 0x7f2bdcabef10>
num_deleted_rows = 0

    def verify_deleted(self, session, node, num_deleted_rows):
        """
        This method verifies there are <num_deleted_rows> deleted rows (tombstones) on node.
        """
        count, jsoninfo = self.count_deleted(session=session, node=node)
>       assert count == num_deleted_rows, f"Error: expected {num_deleted_rows} deleted partitions but found {count}:\n{jsoninfo}"
E       AssertionError: Error: expected 0 deleted partitions but found 10:
```
Full logs:
[node1.log](https://github.com/scylladb/scylladb/files/14691928/node1.log)
[node2.log](https://github.com/scylladb/scylladb/files/14691929/node2.log)

This test assumes that major compaction is able to purge all tombstones. This is not necessarily true, and I think this is the source of the flakyness of this test.

**Comment by denesb** [comment]
We have seen this fail since the native nodetool was merged, multiple times. It is always with the `immediate` parameter but with different compaction strategies. Both with and without the consistent topology changes.

**Comment by denesb** [comment]
Immediate-mode tombstone gc is broken. This was hidden before, because the tests sets a gc grace of 5 seconds when using immediate mode. With the slow Java nodetool, by the time the test got around to check the tombstones, the gc grace seconds was already up, so the tombstones were GC'd and the test passed. With the much faster native nodetool, the test gets to this phase faster, sometimes before the 5 seconds gc grace has elapsed, finding the tombstones and failing.

**Comment by denesb** [comment]
PR to disable the test until the issue is solved: https://github.com/scylladb/scylla-dtest/pull/4088

**Comment by tchaikov** [comment]
spotted at https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/653/
