### ISSUE TITLE
[ARM] user_types_test.test_invalid_user_type_statements failed in raft_operation_timeout_error

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylladb#17987]
user_types_test.test_invalid_user_type_statements failed in ARM with ERROR:
```
[Exception] - service::raft_operation_timeout_error: group [3afa0630-e9c4-11ee-9258-7ecf9c80936f] raft operation [add_entry] timed out
 == [File] - test/lib/exception_utils.cc
 == [Line] - 21
```
link to the failure:
https://jenkins.scylladb.com/job/scylla-master/job/next/7428/testReport/junit/boost/user_types_test/test_invalid_user_type_statements/

link to the log:
https://jenkins.scylladb.com/job/scylla-master/job/next/7428/artifact/testlog/aarch64/debug/boost.user_types_test.test_invalid_user_type_statements.1.log

`unknown location(0): fatal error: in "test_invalid_user_type_statements": service::raft_operation_timeout_error: group [3afa0630-e9c4-11ee-9258-7ecf9c80936f] raft operation [add_entry] timed out`

**Comment by Annamikhlin** [comment]
seems related to the commit: https://github.com/scylladb/scylladb/commit/3d1b94475f885ded38bd72bfb3e5d4b1526d4c3d

**Comment by mykaul** [comment]
@avikivity - please see what else can be reverted.

**Comment by Annamikhlin** [comment]
bisect results on ARM:

- **After** the commit: 3d1b94475f885ded38bd72bfb3e5d4b1526d4c3d - raft_group_registry: add group0_with_timeouts

6 FAIL / 4 PASS - https://jenkins.scylladb.com/view/master/job/scylla-master/job/bisect/44
```
19:45:44  [115/130]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.1 263.89s
19:45:44  [116/130]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.2 264.10s
19:45:44  [117/130]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.3 265.26s
19:45:46  [118/130]   boost    debug  [ FAIL ] boost.user_types_test.test_invalid_user_type_statements.5 245.25s
19:45:46  [119/130]   boost    debug  [ FAIL ] boost.user_types_test.test_invalid_user_type_statements.4 246.91s
19:46:08  [120/130]   boost    debug  [ FAIL ] boost.user_types_test.test_invalid_user_type_statements.6 245.14s
19:46:10  [121/130]   boost    debug  [ FAIL ] boost.user_types_test.test_invalid_user_type_statements.7 244.98s
19:46:31  [122/130]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.8 259.88s
19:46:34  [123/130]   boost    debug  [ FAIL ] boost.user_types_test.test_invalid_user_type_statements.9 244.14s
19:46:41  [125/130]   boost    debug  [ FAIL ] boost.user_types_test.test_invalid_user_type_statements.10 243.87s
```

- **Before** the commit: 3d1b94475f885ded38bd72bfb3e5d4b1526d4c3d 

20 / 20 PASSED - https://jenkins.scylladb.com/view/master/job/scylla-master/job/bisect/45/

```
20:43:11  [209/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.1 271.22s
20:43:12  [213/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.2 272.82s
20:43:14  [215/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.3 274.34s
20:43:32  [219/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.4 267.56s
20:43:32  [221/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.5 266.71s
20:43:59  [226/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.7 268.06s
20:43:59  [227/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.6 270.88s
20:44:00  [228/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.8 266.10s
20:44:21  [229/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.9 266.45s
20:44:26  [230/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.10 265.67s
20:44:47  [231/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.11 268.22s
20:45:01  [232/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.12 260.68s
20:45:06  [233/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.13 261.46s
20:45:29  [237/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.14 263.41s
20:45:36  [239/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.15 264.23s
20:45:51  [240/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.16 258.98s
20:46:20  [241/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.17 267.06s
20:46:33  [242/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.18 263.50s
20:46:48  [244/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.19 263.33s
20:47:08  [247/260]   boost    debug  [ PASS ] boost.user_types_test.test_invalid_user_type_statements.20 258.41s
```

**Comment by kbr-scylla** [comment]
```
INFO  2024-03-24 11:55:56,707 [shard 0:stat] migration_manager - Prepare Create new User Type: ut4
WARN  2024-03-24 11:55:57,212 [shard 0:stat] raft_group_registry - group [3afa0630-e9c4-11ee-9258-7ecf9c80936f] raft operation [add_entry] timed out; timeout requested at [service/migration_manager.cc(972:109) `future<> service::migration_manager::announce_with_raft(std::vector<mutation>, group0_guard, std::string_view)`], original error raft::request_aborted (Request is aborted by a caller)
```

it times out in less than 1 second?

**Comment by benipeled** [comment]
And now on enterprise https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2870/testReport/junit/boost/user_types_test/test_invalid_user_type_statements/
```
INFO  2024-03-25 04:03:17,703 [shard 0:main] schema_tables - Schema version changed to d8d3a35c-ea4b-11ee-4fd2-b1b3b6aea22c
INFO  2024-03-25 04:06:41,140 [shard 0:sl:d] migration_manager - Prepare Create new User Type: ut4
WARN  2024-03-25 04:06:41,648 [shard 0:sl:d] raft_group_registry - group [d65c15f0-ea4b-11ee-9845-3543779aa173] raft operation [add_entry] timed out; timeout requested at [service/migration_manager.cc(983:109) `future<> service::migration_manager::announce_with_raft(std::vector<mutation>, group0_guard, std::string_view)`], original error raft::request_aborted (Request is aborted by a caller)
INFO  2024-03-25 04:06:41,715 [shard 0:main] view - Stopping view builder
```

**Comment by gusev-p** [comment]
> ```
> INFO  2024-03-24 11:55:56,707 [shard 0:stat] migration_manager - Prepare Create new User Type: ut4
> WARN  2024-03-24 11:55:57,212 [shard 0:stat] raft_group_registry - group [3afa0630-e9c4-11ee-9258-7ecf9c80936f] raft operation [add_entry] timed out; timeout requested at [service/migration_manager.cc(972:109) `future<> service::migration_manager::announce_with_raft(std::vector<mutation>, group0_guard, std::string_view)`], original error raft::request_aborted (Request is aborted by a caller)
> ```
> 
> it times out in less than 1 second?

Looks like an artefact of [logger timestamp formatting code](https://github.com/scylladb/seastar/blob/cd8a9133d2c02f63dbd578d882cf7333a427e194/src/util/log.cc#L257), but I don't see a problem in it.

Reproduces on armtrading with reasonable timestamps:
```
DBG2
INFO  2024-03-25 09:03:41,958 [shard 0:stat] raft_group_registry - DBG read_barrier, now 5430867070, timeout 5430927070
INFO  2024-03-25 09:03:41,959 [shard 0:stat] raft_group_registry - DBG start read_barrier
INFO  2024-03-25 09:03:42,005 [shard 0:stat] raft_group_registry - DBG finish read_barrier
INFO  2024-03-25 09:12:43,618 [shard 0:stat] migration_manager - Prepare Create new User Type: ut4
INFO  2024-03-25 09:12:45,251 [shard 0:stat] raft_group_registry - DBG add_entry, now 5431461087, timeout 5431521087
INFO  2024-03-25 09:12:45,252 [shard 0:stat] raft_group_registry - DBG start add_entry
INFO  2024-03-25 09:13:45,229 [shard 0:stat] raft_group_registry - DBG finish add_entry
INFO  2024-03-25 09:13:45,229 [shard 0:stat] raft_group_registry - DBG finish add_entry, TIMEOUT
WARN  2024-03-25 09:13:45,230 [shard 0:stat] raft_group_registry - group [4cf97c40-ea86-11ee-a942-e13814b37400] raft operation [add_entry] timed out; timeout requested at [service/migration_manager.cc(972:109) `future<> service::migration_manager::announce_with_raft(std::vector<mutation>, group0_guard, std::string_view)`], original error raft::request_aborted (Request is aborted by a caller)
```

The test creates `ut4` with 32767 fields, it takes a lot of time to process them or `arm/debug`, we should probably increase the timeout in this test.

**Comment by kbr-scylla** [comment]
> Looks like an artefact of [logger timestamp formatting code](https://github.com/scylladb/seastar/blob/cd8a9133d2c02f63dbd578d882cf7333a427e194/src/util/log.cc#L257), but I don't see a problem in it.

So in reality more time has passed?

**Comment by kbr-scylla** [comment]
> The test creates ut4 with 32767 fields, it takes a lot of time to process them or arm/debug, we should probably increase the timeout in this test.

Please do (and verify on armatrading that it's enough)

**Comment by gusev-p** [comment]
> > Looks like an artefact of [logger timestamp formatting code](https://github.com/scylladb/seastar/blob/cd8a9133d2c02f63dbd578d882cf7333a427e194/src/util/log.cc#L257), but I don't see a problem in it.
> 
> So in reality more time has passed?

This is the hypothesis. Another one - some strange behaviour of `lowres_timer`, if it wasn't updated properly by reactor and we got `lowres_clock::now()` from the past in `run_with_timeout`.

**Comment by kbr-scylla** [comment]
cc @tchaikov

**Comment by kbr-scylla** [comment]
> This is the hypothesis. Another one - some strange behaviour of lowres_timer, if it wasn't updated properly by reactor and we got lowres_clock::now() from the past in run_with_timeout.

Hm but in that case, why did the timeout happen? If now() returns value from past, then the difference calculated (1s in the above case) should be less than the timeout, therefore timeout should not happen.

**Comment by gusev-p** [comment]
> > This is the hypothesis. Another one - some strange behaviour of lowres_timer, if it wasn't updated properly by reactor and we got lowres_clock::now() from the past in run_with_timeout.
> 
> Hm but in that case, why did the timeout happen? If now() returns value from past, then the difference calculated (1s in the above case) should be less than the timeout, therefore timeout should not happen.

There are different clocks, logger uses wall clock, timers - lowres_clock.

**Comment by kbr-scylla** [comment]
So which clock is behind which?

If lowres_clock returns value from the past, but wall clock keeps up, then timeout should not happen, given that wall clock showed 1s difference.

If wall clock returns value from the past, but lowres_clock keeps up -- that would be plausible given these logs. There was a timeout, but wall clock showed 1s difference.

**Comment by gusev-p** [comment]
> So which clock is behind which?
> 
> If lowres_clock returns value from the past, but wall clock keeps up, then timeout should not happen, given that wall clock showed 1s difference.

Timeouts are measured by the lowres_clock. It could return value from the past when we capture the timeout (`timeout->value = lowres_clock::now() + _group_server.default_op_timeout.value();`), then later it was updated by the reactor to the current value and triggered timeout.
