### ISSUE TITLE
data structure for tablet storage provides very inefficient iteration with a large tablet count

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#18010]
The data structure used today is chunked_vector, it's used as a sparse array.

A rack is expected to grow up to 100k tablets, and each shard holds up to 100 tablets (≃ 0.5T). So today we'd iterate through 100k tablets only to find 100 allocated. That's inefficient and creates a potential for reactor stalls, e.g. the tablet_sstable_set ctor 
iterates through all tablets, not only the ones allocated in the shard.

chunked_vector must be replaced to avoid that. A simpler wrapper can be added over chunked_vector that will manage allocated indexes in a std::set (which is a red black tree), and an iterator can also be wrapped over std::set::iterator for going through allocated elements only. The wrapper is very simple as it's just control plane code, the data plane is reused of existing well-tested containers.

Alternatively, we thought of using compact radix tree, but tests showed it can be 2x slower than chunked_vector due to increased cpu usage for shrinking memory usage. We're probably fine with the increased footprint in a sparse array, as the worse case is ~100k * 8 = ~0.8M / shard. A good trade-off to make, in order to not have a regression compared to today with vnodes, specially with write intensive workloads, that will result in a lookup, on every write, to append to a memtable.

**Comment by avikivity** [comment]
radix tree is also a poor choice, since it's sparse.

We can use absl::hash_flat_map. It will allocate just once, and the allocation will be O(tablet replicas per shard), so small enough.

**Comment by raphaelsc** [comment]
> radix tree is also a poor choice, since it's sparse.
> 
> We can use absl::hash_flat_map. It will allocate just once, and the allocation will be O(tablet replicas per shard), so small enough.

log2 (100) = 6 is a low-order factor, but couldn't in practice accumulate to significant difference, compared to today which is just one dereference to the compaction group? I think we should measure it at least with a write intensive workload in cassandra-stress. do you agree? I tended to think that we're willing sacrifice less than 1/mb per shard (with a sparse array and std::set as auxiliary), if that means devoting cpu for more important tasks than iterating a few levels (even though a small constant at most) in the tree, which will happen on every append to memtable.

**Comment by avikivity** [comment]
radix tree works well when some nodes have high occupancy and others have low occupancy, here nodes have similar occupancy since assignment of tablet replicas to a shard are random.

**Comment by raphaelsc** [comment]
I'll experiment with absl::hash_flat_map, thanks for the suggestion
