### ISSUE TITLE
Generate tablets repair/rebuild plan when altering keyspace

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#18031]
Continuation of #17116

ALTER should apply several mutations via raft, one of them is rebuild plan that includes a set of "rebuid" transitions (#18030). This change should be applied by ALTER in the background

**Comment by bhalevy** [comment]
Is this issue addressed by https://github.com/scylladb/scylladb/pull/16723?

**Comment by bhalevy** [comment]
How does decreasing replicas work?
Just by having pending replicas be a subset of the current tablet replicas? will that ensure proper cleanup if the deleted replicas?

cc @ptrsmrn

**Comment by mykaul** [comment]
What's the next step here?

**Comment by xemul** [comment]
Ah, it's fixed as a part of #16723
