### ISSUE TITLE
compaction: print stats about tombstone GC

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#18034]
Currently, we have have no visibility into how many tombstones compaction purges and why. When there is problem around tombstone GC, we are left guessing and inferring. We should extend the end-of-compaction printout with some stats around tombstone GC:
```
tombstone GC stats: total={}, purged={}/{}, not purged due to overlap: {} (sstable={}, memtable={}, commitlog={})
```
We could possibly add the same information to repair-history.

**Comment by mykaul** [comment]
Compaction already heavily dominates our logs. How often do we wish to get this kind of additional messages?

**Comment by raphaelsc** [comment]
we could alternatively extend tablestats with these metrics. in the issue https://github.com/scylladb/scylladb/issues/13742 I suggested adding these as actual metrics, so we can see tombstone GC efficiency over time.

**Comment by denesb** [comment]
I think it is very useful to see these in a per-compaction resolution. Global metrics can muddy the picture.

**Comment by denesb** [comment]
Closing as duplicate of https://github.com/scylladb/scylladb/issues/13742.
