### ISSUE TITLE
Memtable reader needs an incremental selector for range scans with tablets

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#18067]
This will help reducing memory usage when doing a range scan in a shard with many tablets (up to ~100)

With point queries, we're able to filter out irrelevant memtables, but for range scans, we need incremental selection (similar to the one used on sstables).

**Comment by mykaul** [comment]
Looks like an improvement we can defer to 6.1?

**Comment by avikivity** [comment]
I don't understand why we need it. The coordinator should manage switching tablets.

**Comment by raphaelsc** [comment]
> I don't understand why we need it. The coordinator should manage switching tablets.

Actually you're the one who proposed it in the past when compaction groups were introduced. The idea is that if a shard has many tablets, and we're doing a range scan, then a replica can incrementally read from memtables, to reduce memory requirement like we do with sstables. My understanding is that in a range scan, the coordinator calls each replica once with the range that belongs to it.

**Comment by raphaelsc** [comment]
Ah ok, you're right, we're no longer intersecting ranges with shard, but with tablets instead. That's what you're saying right? In that case, yes, I think we don't need this.

**Comment by raphaelsc** [comment]
I think we can close this as invalid, closing...

**Comment by avikivity** [comment]
> > I don't understand why we need it. The coordinator should manage switching tablets.
> 
> Actually you're the one who proposed it in the past when compaction groups were introduced. The idea is that if a shard has many tablets, and we're doing a range scan, then a replica can incrementally read from memtables, to reduce memory requirement like we do with sstables. My understanding is that in a range scan, the coordinator calls each replica once with the range that belongs to it.

No, I proposed eliminating this behavior.

With vnodes, the ranges that belong to a shard can be tiny, so the coordinator overhead can be large. So we call multishard_reader which is a sort of mini-coordinator that is much loved by @denesb.

With tablets, each shard owns a substantial amount of data even without skipping tablets, so letting the coordinator be the sole range manager is efficient.
