### ISSUE TITLE
Need to reject LWT queries on tablets-enabled tables while LWT is not supported with tablets

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18066]
As @kostja noted, it's not enough to warn about the lack of support for LWT.
We should return an error when LWT is in use until we officially support it with tablets.
(And disable lwt tests with tablets until then).

Refs https://github.com/scylladb/scylladb/issues/15465
Refs https://github.com/scylladb/scylladb/issues/16594
Refs https://github.com/scylladb/scylladb/issues/16807

**Comment by kbr-scylla** [comment]
Much easier to do for 6.0 than https://github.com/scylladb/scylladb/issues/15465

**Comment by tgrabiec** [comment]
> Much easier to do for 6.0 than #15465

Also, supporting LWT is not just about #15465, we have to carefully review the code to check if it's prepared for tablet migrations. https://github.com/scylladb/scylladb/issues/16594 adds an extra twist to the problem.

**Comment by kbr-scylla** [comment]
Opened epic https://github.com/scylladb/scylladb/issues/18068

**Comment by bhalevy** [comment]
The error should be returned by the storage_proxy, not at the cql layer, so we'd fail also internal lwt queries.
Sadly, with that, we cannot claim support for Alternator over tablets as well.

Cc @nyh
