### ISSUE TITLE
docs: Issue in page Scylla SStable

### ISSUE THREAD

**Issue by maesta2** [scylladb/scylladb#18096]
I would like to report an issue in page https://opensource.docs.scylladb.com/branch-5.4/operating-scylla/admin-tools/scylla-sstable

### Problem
```
SStable Content[¶](https://opensource.docs.scylladb.com/stable/operating-scylla/admin-tools/scylla-sstable.html#sstable-content)
All operations target either one specific sstable component or all of them as a whole. For more information about the sstable components and the format itself, visit [SStable](https://opensource.docs.scylladb.com/architecture/sstable).
```

the following link is broken
visit [SStable](https://opensource.docs.scylladb.com/architecture/sstable).

###  Suggest a fix

fix link

**Comment by tzach** [comment]
Link should be fix to https://opensource.docs.scylladb.com/master/architecture/sstable
