### ISSUE TITLE
test_replace_reuse_ip: data loss during replace-with-same-ip

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylladb#18111]
The test `test_replace_reuse_ip` writes some data while a replacing node is starting with the same ip. The part of the test which checks we can read what we wrote is commented out. This check fails, sometimes we don't see some keys (often `key_0`, but also other keys).

**Comment by kbr-scylla** [comment]
> The test test_replace_reuse_ip writes some data while a replacing node is starting with the same ip. The part of the test which checks we can read what we wrote is commented out.

Refers to this PR:
https://github.com/scylladb/scylladb/pull/18112

**Comment by gleb-cloudius** [comment]
The test reads only one page of data.

**Comment by kbr-scylla** [comment]
Damn. The fact that `run_async` fetches only one page by default is stupid.

**Comment by gleb-cloudius** [comment]
> Damn. The fact that `run_async` fetches only one page by default is stupid.

Don't you like default parameters?
