### ISSUE TITLE
Verify that the replacing node is in the same DC/RACK as the node being replaced when needed

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#18139]
*Installation details*
HEAD: ce1784186042b9ed6681688683440be5849f4808

## Description
When one replaces a node using `replace_addres_xx`/`replace_node_xxx` parameters and by mistake uses a node that will belong to a different rack or even a different DC `scylla` will just allow that.

As a result, if `NetworkTolopolyStrategy` is used, the ownership is going to change on nodes unrelated to the node being replaces hence even if RBNO is used the data is on those nodes is not going to be streamed to reflect the new ownership.

As a result we will end with an inconsistent data and will need to run a full repair to fix that.

This is obviously not a desired behavior and such mistakes should be prevented.

We need a "safeguard" that would fail such an attempt.

**Comment by vladzcloudius** [comment]
One way to implement such a safeguard is:

On the replacing node after it fetches a cluster the application state of the node being replaced and schema:

```
validate_topology_params = false;
For each keyspace KS {
   if (KS replication strategy is `NetworkTolopolyStrategy`) {
       validate_topology_params = true;
       break;
   }
}

if (validate_topology_params) {
    verify that this node's DC and RACK are the same as the ones of the node we are replacing
    if they are not - exit with the corresponding error message
}
```

**Comment by vladzcloudius** [comment]
cc @mkeeneyj

**Comment by mykaul** [comment]
I kinda remember @bhalevy raising a similar concern.

**Comment by mykaul** [comment]
> I kinda remember @bhalevy raising a similar concern.

https://github.com/scylladb/scylladb/issues/15787

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylladb/issues/16858 more accurately.

**Comment by vladzcloudius** [comment]
> #16858 more accurately.

The description suggests that this one is a duplicate of the above. 
However I'm probably a bit more explicit in regards "what I want" (I want a safeguard!).
So, up to you, guys - you can close this one as a duplicate but we really want this safeguard to be implemented and this is a rather trivial thing to do which will save lives!

I can add it to a FE Hackaton list for this R&D Summit maybe...

**Comment by vladzcloudius** [comment]
Wait a second! There is even a patch already: https://github.com/bhalevy/scylla/commit/1dc449ca9f42295a7ed01696b6eec37f4bbb80f7

Why wasn't it merged, @bhalevy ?

**Comment by bhalevy** [comment]
> Wait a second! There is even a patch already: [bhalevy@1dc449c](https://github.com/bhalevy/scylla/commit/1dc449ca9f42295a7ed01696b6eec37f4bbb80f7)
> 
> Why wasn't it merged, @bhalevy ?

It had a dependency on another issue and that was fixed relatively recently.
See https://github.com/scylladb/scylladb/pull/16862#issuecomment-2100855476

**Comment by kbr-scylla** [comment]
I believe this was fixed by https://github.com/scylladb/scylladb/pull/16862 cc @bhalevy .
Closing.
