### ISSUE TITLE
doc: replace reference to the Download Center for Azure and GCP deployment

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#18144]
https://opensource.docs.scylladb.com/master/getting-started/install-scylla/launch-on-azure.html
https://opensource.docs.scylladb.com/master/getting-started/install-scylla/launch-on-gcp.html

The above pages contain references to the Download Center as a step to obtain the image info (e.g., _Go to [ScyllaDB for GCP](https://www.scylladb.com/download/?platform=gcp#open-source) in ScyllaDB’s download center to obtain the image information).

They should be removed and replaced with the latest information using the images directive with the `:only_latest:` parameter.

```
.. scylladb_azure_images_template::
   :exclude: rc,dev
  :only_latest:
```

```
.. scylladb_gcp_images_template::
   :exclude: rc,dev
   :only_latest:
```

**Comment by yaronkaikov** [comment]
> @yaronkaikov The GCP image information you provided about the [GCP image](https://opensource.docs.scylladb.com/master/reference/gcp-images.html) is **Image name** and **Image ID**.
> 
> The deployment instructions only use the image name: `gcloud compute instances create scylla-node1 --image scylladb-5-4-5 --image-project scylla-images --local-ssd interface=nvme --machine-type=n1-standard-8`
> 
> How is the image ID used?

Amm. it seems we don't use it during the installation instructions
