### ISSUE TITLE
commitlog: store oversized mutations in blob files

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18161]
Currently, commitlog throws an error if a mutation is larger than `max_mutation_size`.
In general, we do need to avoid large mutations, but we could support them more gracefully, if they are stored in a uniquely named blob file, which can be referred to in a corresponding commitlog record.

The blob file can be deleted once the commitlog segment that refers to it is recycled.

On startup, we should also detect and delete orphaned blob files that are not referred by any segment (maybe scylla crashed before committing the record referring to the blob, or lost it in some other way).

In addition, the blob sizes should be taken into account against the commitlog soft and hard limits.

**Comment by elcallio** [comment]
Was shot down by @avikivity . Closing
