### ISSUE TITLE
Tablets: support tablets merge

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18181]
Currently, tablets are split automatically when average tablet size grows over a certain limit (twice the desired size).
This allows larger tables to spread over more shards while keeping the tablet size roughly constant.

We need also to implement the reverse process, so that when tables shrink in size and the average tablet size goes below the limit (half of the desired size), tablets should be merged back together in pairs, so to bring them back into the desired size, and spread the table over fewer shards correspondingly.

The plan is to migrate the odd tablets to be collocated along with their even counterparts, and then, once they are owned by the same shard, merge them together into a single tablet (and internally, storage group).

**Comment by tgrabiec** [comment]
Design doc: https://docs.google.com/document/d/1k1u9r9kByvc6d6lF52fhHCyFkCNgDnU4L6h1qYwnm_0/edit?pli=1&tab=t.0#heading=h.97hvtzxpawvi

**Comment by mykaul** [comment]
> Design doc: https://docs.google.com/document/d/1k1u9r9kByvc6d6lF52fhHCyFkCNgDnU4L6h1qYwnm_0/edit?pli=1&tab=t.0#heading=h.97hvtzxpawvi

@bhalevy - is the above design complete (reviewed, approved, etc.) ?
