### ISSUE TITLE
select * from mutation_fragments on tablets may miss data during tablet migration

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#18199]
The mutation fragment query uses local multishard reader, which is based on `tablet_range_splitter` (unlike regular queries, which don't use multishard reads). The implementation of the tablet_range_splitter always looks at "replicas", so during migration it disregards the read selector and always goes to old replicas. Its result will be inconsistent with what regular reads observe, and during migration it may happen that the read will not see any data on any of the replicas.

The fix could be to make the behavior of the splitter be consistent with the sharder, by invoking the tablet sharder.

**Comment by tgrabiec** [comment]
c7908c319f contains a workaround for this bug by executing a read barrier after add_replica API so that query on the new replica is guaranteed to see the non-transitional erm.

**Comment by denesb** [comment]
This was seen cause a test failure in CI: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8025/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_test_select_from_mutation_fragments_release_2/
Adding ci-stability label.

**Comment by avikivity** [comment]
Although it causes a test failure, I consider it a minor bug. SELECT mutation_fragments() is weird in that it is node-local. If you do node-local things on things that can migrate, what do you expect?

**Comment by nyh** [comment]
> Although it causes a test failure, I consider it a minor bug. SELECT mutation_fragments() is weird in that it is node-local. If you do node-local things on things that can migrate, what do you expect?

Exactly. We have an API to temporarily disable migration, so why not use it while trying to do node-local reads? In Python we can even have a context manager to make it easy to temporarily disable migration. It reminds me of code we had in OSv to run CPU-local things while disabling thread migration between CPUs :-)

**Comment by denesb** [comment]
Ok, I will send a PR tomorrow, to disable migrations for this entire test file.

Although... now that I think of it, the test is ran against a single node cluster and we don't have intra-node migrations yet. So what migrations could we have here? Tablet split?

**Comment by raphaelsc** [comment]
> Ok, I will send a PR tomorrow, to disable migrations for this entire test file.
> 
> Although... now that I think of it, the test is ran against a single node cluster and we don't have intra-node migrations yet. So what migrations could we have here? Tablet split?

bumped into this locally

**Comment by denesb** [comment]
> > Ok, I will send a PR tomorrow, to disable migrations for this entire test file.
> > Although... now that I think of it, the test is ran against a single node cluster and we don't have intra-node migrations yet. So what migrations could we have here? Tablet split?
> 
> bumped into this locally

You mean the test failed?

**Comment by bhalevy** [comment]
This is a minor issue since `SELECT * FROM MUTATION_FRAGMENTS` is used for debugging, so can be postponed to 6.1.

@mykaul / @dani-tweig WDYT?

**Comment by dani-tweig** [comment]
> This is a minor issue since `SELECT * FROM MUTATION_FRAGMENTS` is used for debugging, so can be postponed to 6.1.
> 
> @mykaul / @dani-tweig WDYT?

@bhalevy 
I vote for 6.1 +  maybe add a note in the release notes if you think people will encounter this symptom.

**Comment by mykaul** [comment]
> > This is a minor issue since `SELECT * FROM MUTATION_FRAGMENTS` is used for debugging, so can be postponed to 6.1.
> > @mykaul / @dani-tweig WDYT?
> 
> @bhalevy I vote for 6.1 + maybe add a note in the release notes if you think people will encounter this symptom.

No need for the release notes - it's a debugging aid.

**Comment by dani-tweig** [comment]
> [c7908c3](https://github.com/scylladb/scylladb/commit/c7908c319f0594210967ce5907b64125b3c88ba5) contains a workaround for this bug by executing a read barrier after add_replica API so that query on the new replica is guaranteed to see the non-transitional erm. We should remove the workaround after this is fixed.

@denesb , will this work?

**Comment by denesb** [comment]
> > [c7908c3](https://github.com/scylladb/scylladb/commit/c7908c319f0594210967ce5907b64125b3c88ba5) contains a workaround for this bug by executing a read barrier after add_replica API so that query on the new replica is guaranteed to see the non-transitional erm. We should remove the workaround after this is fixed.
> 
> @denesb , will this work?

Possibly, I didn't dig into this yet.

**Comment by denesb** [comment]
This was last seen in April, and I have recently developed a related fix: https://github.com/scylladb/scylladb/pull/20109.
I will close this, we will reopen if we see it again.
