### ISSUE TITLE
service levels on raft: upgrade might get stuck if nodes were removed recently

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#18198]
One of the steps during upgrade to raft topology involves rewriting data from legacy service levels tables into the group0-managed tables. RF of the keyspace where legacy tables are in is 3, and it is chosen based on the `gossiper::num_endpoints()` method:

```c++
        rtlogger.info("migrating service levels data");
        co_await qos::service_level_controller::migrate_to_v2(_gossiper.num_endpoints(), _sys_ks, _sys_ks.query_processor(), _group0.client(), _as);
```

```c++
future<> service_level_controller::migrate_to_v2(size_t nodes_count, db::system_keyspace& sys_ks, cql3::query_processor& qp, service::raft_group0_client& group0_client, abort_source& as) {

    // ...

    // `system_distributed` keyspace has RF=3 and we need to scan it with CL=ALL
    // To support migration on cluster with 1 or 2 nodes, set appropriate CL
    auto cl = db::consistency_level::ALL;
    if (nodes_count == 1) {
        cl = db::consistency_level::ONE;
    } else if (nodes_count == 2) {
        cl = db::consistency_level::TWO;
    }

    // ...
}
```

However, the behavior of `num_endpoints` is to return the number of _elements in the endpoint states map_:

```c++
    size_t num_endpoints() const noexcept {
        return _endpoint_state_map.size();
    }
```

The current behavior of `nodetool removenode` results in the endpoint state of the removed node being kept for three more days. Due to that, if the cluster was downsized recently to 2 nodes or 1 node, this might prevent upgrade from proceeding as too stong of a consistency level will be chosen. This is especially bad in case of disaster recovery - it involves performing `nodetool removenode` in legacy operations mode and then redoing the upgrade - if only 2 or 1 node is left after that then finishing recovery won't be possible for 3 days.

**Comment by piodul** [comment]
I'm working on a fix, it should be rather simple.

**Comment by mykaul** [comment]
"if the cluster was downsized recently to 2 nodes or 1 node" sounds like a (very?) rare scenario to me. Should this still be considered a release blocker? Unsure.
