### ISSUE TITLE
doc: link to SBOM from the docs

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#18195]
See https://github.com/scylladb/scylla-pkg/issues/3754

**Comment by Annamikhlin** [comment]
@annastuchlik - any update about this task?

**Comment by yaronkaikov** [comment]
@annastuchlik we need to upload the SBOM report we keep generating during our releases to our trust center. 

Can you handle it?

/cc @tzach @mykaul @Annamikhlin

**Comment by yaronkaikov** [comment]
> [@yaronkaikov](https://github.com/yaronkaikov) The plan discussed with [@tzach](https://github.com/tzach) is to add a link to the SBOM report to our docs rather than include the contents of the report in the docs. I'd like to start working on this task, but I need your input.
> 
> What would be the appropriate link? In downloads, I've found the following links:
> 
> * https://downloads.scylladb.com/downloads/scylla-enterprise/sbom/ - Enterprise-related reports

For now we should use the above

> * https://downloads.scylladb.com/downloads/scylla/sbom/ - This is apparently a folder for ScyllaDB OSS, but it only contains `/scylladb-master/` with information up to version 6.0
> * https://downloads.scylladb.com/downloads/sbom/ - This folder is empty.
