### ISSUE TITLE
Add sstable disk size metric

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#18191]
This metric will be very useful to understand disk usage by sstables per shard, e.g. see compaction dropping space on the fly, and also easily see data inbalance by shard due to bad modelling. Today we have to scan the directory to get that info, which is bad.

**Comment by avikivity** [comment]
It doesn't work as a metric, you can't look at tables, you can't get distributions.

Better a virtual table. We could have a virtual table for sstables, or a virtual table for files under data/.

**Comment by raphaelsc** [comment]
> It doesn't work as a metric, you can't look at tables, you can't get distributions.
> 
> Better a virtual table. We could have a virtual table for sstables, or a virtual table for files under data/.

today we have bloom filter memory size, and you know the percentage of it in comparison to ram. a disk size metric will allow us to quickly get inbalance. I am investigated a problem where this metric you help a lot.

an advance of metric over virtual table is that you understand behavior over time, and I need that for correlating disk usage activity (per shard) with compaction.

**Comment by raphaelsc** [comment]
For example, right now, I am looking at number of sstables per shard, bloom filter per size, I need sstable disk size per shard, and I only have a node wide one. Today disk usage metric as provided by OS is suboptimal when we need correlation with activity in a single shard

**Comment by raphaelsc** [comment]
I think it will be valuable. And I wish we had this metric now.

**Comment by raphaelsc** [comment]
I put more thought on this and I think metric is valuable. After all, this issue was opened in the context of an investigation and the lack of metric made my life much harder for understanding compaction behavior in a shard. You're right it doesn't provide distribution per table but it already provides distribution per shard (which is enough for detecting imbalance as a first step; today you cannot see it through monitoring) and it's the only way to see behavior over time (something virtual table cannot provide and it's important for correlation with activity in a shard). @avikivity Do you agree? Virtual table can still be added in addition to the metric.

**Comment by asias** [comment]
> This metric will be very useful to understand disk usage by sstables per shard, e.g. see compaction dropping space on the fly, and also easily see data inbalance by shard due to bad modelling. Today we have to scan the directory to get that info, which is bad.

This metric sounds useful.  How and when do we update the metrics? E.g., background scan at a low frequency (10s), or update the metric immediately when a sstable is added to / removed from the system. We need to consider file stream and sstables in upload directory too.

**Comment by raphaelsc** [comment]
> > This metric will be very useful to understand disk usage by sstables per shard, e.g. see compaction dropping space on the fly, and also easily see data inbalance by shard due to bad modelling. Today we have to scan the directory to get that info, which is bad.
> 
> This metric sounds useful. How and when do we update the metrics? E.g., background scan at a low frequency (10s), or update the metric immediately when a sstable is added to / removed from the system. We need to consider file stream and sstables in upload directory too.

SSTable manager knows when a sstable is added / closed, we can easily calculate it on the fly without any scanning. So it covers all sstables in the system. We can consider only sealed sstables.

**Comment by changkhothuychung** [comment]
Hi, is this issue still active? I am new to this project, and would like to take this issue if possible. Thanks!

**Comment by mykaul** [comment]
> Hi, is this issue still active? I am new to this project, and would like to take this issue if possible. Thanks!

Tanks @changkhothuychung - it's not actively being worked on - feel free to take this.

**Comment by changkhothuychung** [comment]
@mykaul Thanks! 

Can you let me know which files am I supposed to change, and how do I test my changes?

**Comment by mykaul** [comment]
> @mykaul Thanks!
> 
> Can you let me know which files am I supposed to change, and how do I test my changes?

I have no idea what your implementation plan is, so it's hard to say. I see from the discussion above the suggestions are a virtual table in addition to the metric.
The code should include a test. https://github.com/scylladb/scylladb/blob/master/docs/dev/testing.md has some information on available test frameworks and options (we have few...).

**Comment by kiran-4444** [comment]
Hey @changkhothuychung are you still working on this? I’d like to take this up if not. Thanks!

**Comment by changkhothuychung** [comment]
> Hey @changkhothuychung are you still working on this? I’d like to take this up if not. Thanks!

Please feel free to take this issue!

**Comment by bhalevy** [comment]
@kiran-4444 did you pick this up?

If not, @lersek, I suggest you take it.

Cc @paszkow

**Comment by lersek** [comment]
@raphaelsc

> SSTable manager knows when a sstable is added / closed, we can easily calculate it on the fly without any scanning. So it covers all sstables in the system. We can consider only sealed sstables.

There seem to be three questions:
- what's an existent metric to use as an example? (-> to teach myself metrics in general)
- what are some good hook points for refreshing the new metric? (i.e., increase and decrease the "current total", by the disk space taken up, or released, by a particular sstable)
- how can we calculate the disk space that's occupied by a given sstable?

Regarding the middle question... after reading commit 5db96170a589 ("sstables: make sstables_manager take charge of closing sstables", 2020-09-23):
- `_active` and `_undergoing_close` together contain the list of sstables that may take up disk space
- `sstables_manager::remove` is the method that runs after `sstable::close_files` resolves (and potentially frees up disk space by deleting the sstable component files), so `sstables_manager::remove` seems like a suitable location for decreasing the total
- `sstables_manager::add` extends the `_active` list, but it doesn't seem general enough (or good, at all) for increasing the total:
  - disk space for a newly written sstable seems to peak (or "settle") in `sstable::seal_sstable` -> `filesystem_storage::seal`; which happens later. New hook for `sstables_manager`?
  - for preexistent sstables (i.e., for sstables created and sealed by prior launches of scylla), calculating the disk space may have to be an async operation (?), which would not be suitable for the sstable constructor / `sstables_manager::add`. The two `sstable::load` members look more suitable. There seems to be some kind of prior art, too:
    ~~~
    sstable::load // variant for tests
        open_data
            _manager.increment_total_reclaimable_memory_and_maybe_reclaim

    sstable::load // variant using components shared by a shard
        ...
            _manager.increment_total_reclaimable_memory_and_maybe_reclaim
    ~~~

**Comment by bhalevy** [comment]
@lersek see `table::update_stats_for_new_sstable`

**Comment by lersek** [comment]
Posted the v3 series to the mailing list (`[PATCH v3 0/3] sstables: measure storage usage per storage type per shard`); can't provide a direct URL yet because (I assume) as a new list member, I must pass moderation first.

**Comment by bhalevy** [comment]
> Posted the v3 series to the mailing list (`[PATCH v3 0/3] sstables: measure storage usage per storage type per shard`); can't provide a direct URL yet because (I assume) as a new list member, I must pass moderation first.

Why the diversion from github PR to the mailing list?
It's and antipattern now to our ci and backporting process.

**Comment by lersek** [comment]
- CI: I covered CI with a manually submitted job.
- backporting: this is a backport/none set.

I've learned from Gleb that `backport/none` patch sets are feasible on the mailing list, as long as we submit the CI job manually against the branch. Wrt. patch sets that require backporting, I've learned that github PRs are the only way (because that's the only way for poking the backporting robot).

I've made a serious effort to adopt github, and I will use it when I really have to, but review sessions that are even slightly nontrivial are super difficult to follow on github, at least to me. I've never had that kind of trouble with mailing list based reviews.

(GitHub continues to suffer from objective shortcomings, such as:
- it's data model is wrong; it associates review comments with lines of the _cumulative diff_, not of the individual patch, so comments given for version#N patch#M show up in the contexts of different patches of the same branch version, what's more, under different versions of the entire set too)
- it doesn't support `git-range-diff`
- it doesn't hang on to earlier versions of a patch set, so as a reviewer, after a force-push by the contributor, you can't even fetch the old version and do a `git-range-diff` locally.)

**Comment by lersek** [comment]
The desired storage footprint should be possible to calculate, for any shard `N`, by summing the following (existent) metrics:
~~~
scylla_column_family_total_disk_space{cf=*,ks=*,shard=N}
~~~
alternatively
~~~
scylla_column_family_live_disk_space{cf=*,ks=*,shard=N}
~~~
These depend on [`enable_keyspace_column_family_metrics`](https://github.com/scylladb/scylladb/blob/master/docs/dev/metrics.md#per-table-metrics).
