### ISSUE TITLE
Adding parameter to stats_metadata

### ISSUE THREAD

**Issue by 851110504** [scylladb/scylladb#18212]
I want to track the tombstone count in each sstable to determine when to execute compaction. Therefore, I added a new parameter, ‘tombstone_count,’ to ‘stats_metadata.’ The newly generated sstable statistics files with this parameter seem to have no issues. However, when reading the older sstable statistics files, the value of this parameter appears as a random value. I would like to know if making this modification will cause any issues, or if it is necessary to modify the sstable version when adding a new parameter to stats_metadata.
![image](https://github.com/scylladb/scylladb/assets/100502050/0db076f5-ce2b-440f-a9cc-6782a8ed9c3e)
![image](https://github.com/scylladb/scylladb/assets/100502050/a364d9ce-144f-4958-a9d6-7754bbcdeee4)

**Comment by mykaul** [comment]
CC @raphaelsc

@851110504 - Can you share the code (via a draft PR even) ?

**Comment by 851110504** [comment]
> CC @raphaelsc
> 
> @851110504 - Can you share the code (via a draft PR even) ?

I have already submitted my current code.
