### ISSUE TITLE
Potential infinite loop in view_update_generator::start()

### ISSUE THREAD

**Issue by pgoron** [scylladb/scylladb#18222]
During repair on one of our scylla cluster (5.2.14), we observed multiple occurrences of unresponsive shard.

shard was constantly logging:
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
[shard 10] view_update_generator - Processing {keyspace} failed for table {table}:std::bad_alloc (std::bad_alloc). Will retry...
...

The root cause of our issue is probably somewhere else and related to std::bad_alloc.
BUT error management seems incorrect in view_update_generator::start() in case of unrecoverable error.

In case of exceptions, faulty sstables is put back in queue and retried immediately without yielding thread to another task.
```
                } catch (...) {
                    vug_logger.warn("Processing {} failed for table {}:{}. Will retry...", s->ks_name(), s->cf_name(), std::current_exception());
                    // Need to add sstables back to the set so we can retry later. By now it may
                    // have had other updates.
                    std::move(sstables.begin(), sstables.end(), std::back_inserter(_sstables_with_tables[t]));
                    break;
                }
```

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2.14
Cluster size: 22 nodes on 3 DC
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS8

Platform (physical/VM/cloud instance type/docker): on-prem kubernetes
Hardware: sockets=AMD EPYC 7502P cores=32 hyperthreading=Yes (64 threads) memory=256GB
Disks: (SSD/HDD, count): 4 NVME

**Comment by nyh** [comment]
I think I fixed this tight loop recently, in commit 0fe40f729e9b9b0af892115635807adb914e387e - part of the https://github.com/scylladb/scylladb/issues/16598. As in your case, there was some root bug that caused this infinite loop of log spam, but the log spam was annoying enough that I fixed it in the third patch of the PR that fixed the root problem.

The commit message explained:

>     mv: sleep a bit before view-update-generator restart
>    The "view update generator" is responsible for generating view updates
>    for staging sstables (such as coming from repair). If the processing
>    fails, the code retries - immediately. If there is some persistent bug,
>    such as issue #16598, we will have a tight loop of error messages,
>   potentially a gigabyte of identical messages every second.
>    
>    In this patch we simply add a sleep of one second after view update
 >   generation fails before retrying. We can still get many identical
 >   error messages if there is some bug, but not more than one per second.

The patch was just
```patch
--- a/db/view/view_update_generator.cc
+++ b/db/view/view_update_generator.cc
@@ -179,6 +179,8 @@ future<> view_update_generator::start() {
                     // Need to add sstables back to the set so we can retry later. By now it may
                     // have had other updates.
                     std::move(sstables.begin(), sstables.end(), std::back_inserter(_sstables_with_tables[t]));
+                    // Sleep a bit, to avoid a tight loop repeatedly spamming the log with the same message.
+                    seastar::sleep(std::chrono::seconds(1)).get();
                     break;
                 }
                 try {
```

https://github.com/scylladb/scylladb/issues/16598 was not backported, so neither was this log-spam-avoiding patch (the third in the PR).

Shall I backport just this patch to close this issue?

**Comment by pgoron** [comment]
HI @nyh , thanks a lot for your quick feedback.
As log spam issue is already fixed in master, I think we can close this issue. We will apply the same change on our build of scylla.

Regarding backport of the fix, I think it would make sense but decision is on your end.

**Comment by piodul** [comment]
The issue aged out - all OSS releases that didn't have the fix are not supported anymore, so there is no need to backport anything.
