### ISSUE TITLE
[dtest] test_max_columns_and_query_parameters failed: DID NOT RAISE <class 'Exception'>

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18227]
Failing consistently since https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/531/testReport/limits_test/TestLimits/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_max_columns_and_query_parameters/
Scylla version 5.5.0~dev-0.20240328.4c0dadee7c32
```
self = <limits_test.TestLimits object at 0x7f923c2aa350>

    @pytest.mark.scylla_mode("!debug")  # client times out in debug mode
    def test_max_columns_and_query_parameters(self):
        cluster = self.prepare()
        cluster.set_configuration_options(values={"query_tombstone_page_limit": 9999999})
        cluster.populate(1).start()
        node = cluster.nodelist()[0]
    
        session = self.patient_cql_connection(node)
        create_ks(session, "ks", 1)
        session.execute("UPDATE system.config SET value='100000' WHERE name='query_tombstone_page_limit'")
    
        count = 1
        for i in range(int(math.log(MAX_COLUMNS, 2))):
            count <<= 1
>           self._do_test_max_columns(session, count - 1, expect_failure=count == MAX_COLUMNS)

limits_test.py:214: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <limits_test.TestLimits object at 0x7f923c2aa350>
session = <cassandra.cluster.Session object at 0x7f9211447310>, count = 32766
expect_failure = True

    def _do_test_max_columns(self, session, count, expect_failure=False):
        print("Testing maximum numbers of columns with count {}.{}".format(count, " Expected failure..." if expect_failure else ""))
    
        # we must count the primary key
        count -= 1
        if count < 0:
            count = 0
    
        keys = ""
        keys_create = ""
        for i in range(count):
            keys += "key" + str(i) + ", "
            keys_create += "key" + str(i) + " int, "
        values = "1, " * count
    
        c = """CREATE TABLE test1 (%s blub int PRIMARY KEY,)""" % keys_create
        if expect_failure:
            expected_error = r"Command size \d+ is greater than the configured limit \d+"
            self.ignore_log_patterns += [expected_error]
>           with pytest.raises(Exception, match=expected_error):
E           Failed: DID NOT RAISE <class 'Exception'>

limits_test.py:189: Failed
```

Last pass was with 5.5.0~dev-0.20240327.6bd0be71ab32

**Comment by mykaul** [comment]
@yaronkaikov - if it's consistent, let's run the bisect job.

**Comment by yaronkaikov** [comment]
@bhalevy I have done the bisect using https://jenkins.scylladb.com/job/scylla-master/job/bisect/61
Based on this the commit causing this is https://github.com/scylladb/scylladb/commit/c1dcf0fae7a5b3e3b36e3d3742444ffed73ad84a , Does it make sense? 

git bisect log - https://jenkins.scylladb.com/job/scylla-master/job/bisect/61/artifact/gitBisectLog.txt/*view*/

**Comment by mykaul** [comment]
CC @gleb-cloudius

**Comment by gleb-cloudius** [comment]
> @bhalevy I have done the bisect using https://jenkins.scylladb.com/job/scylla-master/job/bisect/61 Based on this the commit causing this is [c1dcf0f](https://github.com/scylladb/scylladb/commit/c1dcf0fae7a5b3e3b36e3d3742444ffed73ad84a) , Does it make sense?
> 
It does because the test is testing the limits and the patch changes how the limits are calculated. Before the patch the limit was lower (incorrectly). The test need to be fixed.

@patjed41 in dtest commit 1b2c840806babe17e70dec72989c989ab64fbba9 you changes the limit to be 32k instead  of 256k. Why?

**Comment by patjed41** [comment]
> > @bhalevy I have done the bisect using https://jenkins.scylladb.com/job/scylla-master/job/bisect/61 Based on this the commit causing this is [c1dcf0f](https://github.com/scylladb/scylladb/commit/c1dcf0fae7a5b3e3b36e3d3742444ffed73ad84a) , Does it make sense?
> 
> It does because the test is testing the limits and the patch changes how the limits are calculated. Before the patch the limit was lower (incorrectly). The test need to be fixed.
> 
> @patjed41 in dtest commit 1b2c840806babe17e70dec72989c989ab64fbba9 you changes the limit to be 32k instead of 256k. Why?

I didn't change the limit. See [a6090b6b93738ea72c7769e659721fe1f183b633](https://github.com/scylladb/scylla-dtest/pull/3770/commits/a6090b6b93738ea72c7769e659721fe1f183b633#diff-23b7f74fc428b588ed84c89057961218ddeef449707ebb1e15c684a958696e18), line 206.

This commit is a part of the series that adjusted dtest after making `consistent-cluster-management` mandatory. Before this series, this test used different limits for two cases: `consistent-cluster-management` enabled and disabled. After making `consistent-cluster-management` mandatory, we only needed to test the first case, so I simplified the test.

**Comment by gleb-cloudius** [comment]
> > > @bhalevy I have done the bisect using https://jenkins.scylladb.com/job/scylla-master/job/bisect/61 Based on this the commit causing this is [c1dcf0f](https://github.com/scylladb/scylladb/commit/c1dcf0fae7a5b3e3b36e3d3742444ffed73ad84a) , Does it make sense?
> > 
> > 
> > It does because the test is testing the limits and the patch changes how the limits are calculated. Before the patch the limit was lower (incorrectly). The test need to be fixed.
> > @patjed41 in dtest commit 1b2c840806babe17e70dec72989c989ab64fbba9 you changes the limit to be 32k instead of 256k. Why?
> 
> I didn't change the limit. See [a6090b6b93738ea72c7769e659721fe1f183b633](https://github.com/scylladb/scylla-dtest/pull/3770/commits/a6090b6b93738ea72c7769e659721fe1f183b633#diff-23b7f74fc428b588ed84c89057961218ddeef449707ebb1e15c684a958696e18), line 206.
> 
> This commit is a part of the series that adjusted dtest after making `consistent-cluster-management` mandatory. Before this series, this test used different limits for two cases: `consistent-cluster-management` enabled and disabled. After making `consistent-cluster-management` mandatory, we only needed to test the first case, so I simplified the test.

This commit https://github.com/scylladb/scylla-dtest/commit/4decb06089f6a2be6e0e5787a2d637a7bdea64d1 adjusts the limit after schema commit log limit was increased, but it leaves raft limit the same since it says that `server::configuration::max_command_size` did not change, but it did not change because of a bug the https://github.com/scylladb/scylladb/commit/c1dcf0fae7a5b3e3b36e3d3742444ffed73ad84a fixes.

**Comment by mykaul** [comment]
@patjed41 - are you handling this issue?

**Comment by kostja** [comment]
@temichus the test needs to be updated to reflect the changes in the commit log + become more stable. Could you please take a look?

**Comment by mykaul** [comment]
@temichus - any updates?

**Comment by temichus** [comment]
Only put in the backlog.

Now for me  it is not clear how commit log is connected with query_tombstone_page_limit.
And how to change the test 

The test changed many times in 
https://github.com/temichus/scylla-dtest/commit/10fcafd88b90c291caf30fb4882066540ce27ff0 - adjust for raft 
https://github.com/temichus/scylla-dtest/commit/4decb06089f6a2be6e0e5787a2d637a7bdea64d1  - adjust max collum limit  
https://github.com/scylladb/scylla-dtest/commit/1b2c840806babe17e70dec72989c989ab64fbba9 - adjust max collum limit again

I think tests in this file too much depends on hardcoded values 
```
MAX_KEY_SIZE = LIMIT_64_K
MAX_BLOB_SIZE = 8388608  # theoretical limit LIMIT_2GB
MAX_COLUMNS = LIMIT_32K
MAX_TUPLES = LIMIT_32K
MAX_BATCH_SIZE = 50 * 1024
MAX_CELLS_COLUMNS = LIMIT_32K
MAX_CELLS_BATCH_SIZE = 50
MAX_CELLS = 16777216
```
I think that should to be gotten from Scylla itself(or calculated based on Scylla system data)


@kostja, @patjed41 @gleb-cloudius  is it possible to calculate MAX_COLUMNS dynamically, based on Scylla config/system data instead of just setting  32k or 256k?

**Comment by gleb-cloudius** [comment]
> @avikivity I suggest we introduce a hard-coded minimal segment size and a hard-coded constant for max columns ~20k. The test will continue to be flaky until the contract is respected by the database.

What's the point to introduce artificial max columns limit if the goal of the test is to test commitlog segment size limit? The test is naturally breaks when the limits it tests change.

**Comment by temichus** [comment]
@kostja in CI test took about 1-15 sec 
![image](https://github.com/scylladb/scylladb/assets/1948660/47cdf130-a87b-4f1d-b767-08447503425c)

so I think we can include it in the next_gating.
In this case, if the Limit is changed, PR in scyllaSB will fail.

**Comment by kostja** [comment]
> > @avikivity I suggest we introduce a hard-coded minimal segment size and a hard-coded constant for max columns ~20k. The test will continue to be flaky until the contract is respected by the database.
> 
> What's the point to introduce artificial max columns limit if the goal of the test is to test commitlog segment size limit? The test is naturally breaks when the limits it tests change.

The way you describe you inverts the dependency. The reason we have a flaky test that tests the max columns limit is that ScyllaDB never committed to a certain limit - the limit depends on the commit log segment size, mutation metadata overhead, commit log metadata overhead. This is impossible to test - the test will forever be flaky until there is a formal contract established between scylladb and its users. The test can test this formal contract then, and whoever is changing the code will have to comply with the contract.

Until this happens the test will forever be flaky.

**Comment by temichus** [comment]
> > > @avikivity I suggest we introduce a hard-coded minimal segment size and a hard-coded constant for max columns ~20k. The test will continue to be flaky until the contract is respected by the database.
> > 
> > 
> > What's the point to introduce artificial max columns limit if the goal of the test is to test commitlog segment size limit? The test is naturally breaks when the limits it tests change.
> 
> The way you describe it inverts the dependency. The reason we have a flaky test that tests the max columns limit is that ScyllaDB never committed to a certain limit - the limit depends on the commit log segment size, mutation metadata overhead, commit log metadata overhead. This is impossible to test - the test will forever be flaky until there is a formal contract established between scylladb and its users. The test can test this formal contract then, and whoever is changing the code will have to comply with the contract.
> 
> Until this happens the test will forever be flaky.

@kostja , @patjed41 
Or/And we can update and include this test into next_gating to detect flaky early, now test run 35sec
I've prepared PR if you decide to put in into next_gating - https://github.com/scylladb/scylla-dtest/pull/4189

**Comment by gleb-cloudius** [comment]
> > > @avikivity I suggest we introduce a hard-coded minimal segment size and a hard-coded constant for max columns ~20k. The test will continue to be flaky until the contract is respected by the database.
> > 
> > 
> > What's the point to introduce artificial max columns limit if the goal of the test is to test commitlog segment size limit? The test is naturally breaks when the limits it tests change.
> 
> The way you describe it inverts the dependency. The reason we have a flaky test that tests the max columns limit is that ScyllaDB never committed to a certain limit - the limit depends on the commit log segment size, mutation metadata overhead, commit log metadata overhead. This is impossible to test - the test will forever be flaky until there is a formal contract established between scylladb and its users. The test can test this formal contract then, and whoever is changing the code will have to comply with the contract.
> 
> Until this happens the test will forever be flaky.

As far as I see the test does not test max columns limit. It tests that nothing bad happens when a schema mutation is too large. The way it creates large enough schema mutation is by creating a lot of columns.

**Comment by temichus** [comment]
the test was updated and included in next_gating to detect fails early. 
close the issue.
