### ISSUE TITLE
Total size of build/test folder is 650Gb

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#18229]
When we get during gating/CI spot termination during the unit-tests phase, we automatically re-trigger the job. Since normally this job runs from the same SHA, we should skip the building phase since we already have the artifacts. 
But since the total size of the test binary is more than 600Gb, we can't upload it to S3 (it will take hours)

By reducing the size of those binaries, we could do the following:

- Upload test binaries upon failure to skip building Scylla from the same SHA
- Upload test binaries during success to split the unit tests between multiple smaller nodes, allowing us to run those tests in parallel
- will probably reduce the building time of Scylla

```
[yaronkaikov@spider8 scylladb]$ du -hs build
657G	build
[yaronkaikov@spider8 scylladb]$ du -hs build/dev/test/
16G	build/dev/test/
[yaronkaikov@spider8 scylladb]$ du -hs build/release/test/
309G	build/release/test/
[yaronkaikov@spider8 scylladb]$ du -hs build/debug/test/
295G	build/debug/test/
```

/cc @denesb

**Comment by denesb** [comment]
There is an open issue for compiling all tests into a single binary, see https://github.com/scylladb/scylladb/issues/9155.
Doing this would reduce the size of the build directory by at least one order of magnitude, but maybe even more.

**Comment by yaronkaikov** [comment]
@denesb Thanks, Closing as duplicate https://github.com/scylladb/scylladb/issues/9155
