### ISSUE TITLE
`nodetool snapshot` fails if `--` argument separator is used

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#18226]
when the following command is used:
```
nodetool snapshot -t sct-20240330_061754 -- system_schema
```

we see the following error in scylla log:
```
api - take_snapshot failed: data_dictionary::no_such_keyspace (Can't find a keyspace --help)
```

a quick reproducer of the issue:
```python
import logging

from dtest_class import Tester

logger = logging.getLogger(__name__)


class TestReproducer(Tester):
    def test_timestamp_ontop_mv(self):
        self.cluster.populate(1)
        self.cluster.start(wait_for_binary_proto=True)
        node1, *_ = self.cluster.nodelist()

        node1.nodetool("snapshot -t sct-20240330_061754 -- system_schema")
```

## Packages

Scylla version: `5.5.0~dev-20240329.885cb2af07b8` with build-id `4d1fc3fe8868b3d00a42f2b0b51f9953e9fa7346`

Kernel Version: `5.15.0-1059-azure`

## Installation details

Cluster size: 4 nodes (Standard_L16s_v3)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-master-db-node-c5f05305-eastus-7 (20.62.198.196 | 10.0.0.6) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-c5f05305-eastus-6 (172.210.24.26 | 10.0.0.14) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-c5f05305-eastus-5 (20.102.105.120 | 10.0.0.14) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-c5f05305-eastus-4 (4.246.139.117 | 10.0.0.8) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-c5f05305-eastus-3 (4.246.139.110 | 10.0.0.7) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-c5f05305-eastus-2 (4.246.139.59 | 10.0.0.6) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-c5f05305-eastus-1 (4.246.137.14 | 10.0.0.5) (shards: 14)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-5.5.0-dev-x86_64-2024-03-30T02-20-45` (azure: undefined_region)

Test: `longevity-1tb-5days-azure-test`
Test id: `c5f05305-97d6-414f-a9f3-9f6b287a963b`
Test name: `scylla-master/tier1/longevity-1tb-5days-azure-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a9e63b344dadce8820a1ab37bb4cc9bd664ff058/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c5f05305-97d6-414f-a9f3-9f6b287a963b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c5f05305-97d6-414f-a9f3-9f6b287a963b)
- Show all stored logs command: `$ hydra investigate show-logs c5f05305-97d6-414f-a9f3-9f6b287a963b`

## Logs:
- **db-cluster-c5f05305.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/db-cluster-c5f05305.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/db-cluster-c5f05305.tar.gz)
- **sct-runner-events-c5f05305.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/sct-runner-events-c5f05305.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/sct-runner-events-c5f05305.tar.gz)
- **sct-c5f05305.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/sct-c5f05305.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/sct-c5f05305.log.tar.gz)
- **loader-set-c5f05305.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/loader-set-c5f05305.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/loader-set-c5f05305.tar.gz)
- **monitor-set-c5f05305.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/monitor-set-c5f05305.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c5f05305-97d6-414f-a9f3-9f6b287a963b/20240331_062908/monitor-set-c5f05305.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-1tb-5days-azure-test/7/)
[Argus](https://argus.scylladb.com/test/1e333df8-a7e8-4171-8ab7-1d7bdea907d5/runs?additionalRuns[]=c5f05305-97d6-414f-a9f3-9f6b287a963b)
</details>

**Comment by mykaul** [comment]
I assume it's the native nodetool?

**Comment by fruch** [comment]
> I assume it's the native nodetool?

It's the new tool wrapper that adds the --help, in the wrong place

**Comment by denesb** [comment]
We should just drop that wrapper. I will send a PR.
