### ISSUE TITLE
[RFE] allow running load&stream on multiple shards

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylladb#18234]
AFAIU, querying `/storage_service/sstables/{keyspace}` endpoint with `load_and_stream` param utilizes only a single shard for performing the work. When Scylla Manager performs a full cluster restore (meaning that there is no traffic to the cluster during this time) this behavior does not utilizes enough of node's resources for the restore resulting in a slowness of the procedure (see [example benchmark](https://docs.google.com/document/d/1zh7zcPTwFEMMqHQFA_pjkkatdj78lJx4H_rLbYjxH1k/edit#heading=h.4uxf2hwc5ran)). 

Although it's theoretically possible for SM to try to utilize more of node's resources by load and streaming sstables from multiple tables in parallel on the same node (as explained [in this doc](https://docs.google.com/document/d/11sSBrlo-OSvEJVba8xRPBAJbsxL2pP7qvET_JoCf3Nw/edit#heading=h.ktu32e28mzjf)), it does not help when restoring only a single, but very large table.

Because of that, it could really improve SM restore performance if the `/storage_service/sstables/{keyspace}` endpoint would support additional param like `utilized_shards` with the default value of 1. From my conversation with @raphaelsc, it sounded like this wouldn't be that difficult to implement on the Scylla side.

@tzach please take a look and prioritize this request in the context of the efforts of speeding up SM restore procedure.

**Comment by Michal-Leszczynski** [comment]
cc: @karol-kokoszka

**Comment by raphaelsc** [comment]
@Michal-Leszczynski turns out we're actually utilizing all shards. one of the problems is that we're limited by a node throughput to process and stream sstable data, and that depends on the data shape. 

when benchmarking again, please take a look at cpu usage with per shard view (for each node). 

@asias does rpc sink have buffering by default? what's the size? I want to make sure we're efficient by buffering some fragments and only them sending them down the stream.

**Comment by raphaelsc** [comment]
I quickly read rpc code, it seems the buffering is per connection and it seems small. Maybe we should do buffering similar to the one done in view updating path. we push fragments to a queue, keep track of memory used, and flush once usage exceeds limit.

**Comment by asias** [comment]
Yes, we utilize all the shards when performing load and streaming. The sstables files to be uploaded are distributed and processed to all shards. @Michal-Leszczynski if you copy less than N shards of sstables to upload dir each time, some of the shards will be idle.

**Comment by asias** [comment]
> @Michal-Leszczynski turns out we're actually utilizing all shards. one of the problems is that we're limited by a node throughput to process and stream sstable data, and that depends on the data shape.
> 
> when benchmarking again, please take a look at cpu usage with per shard view (at least from node we're restoring data from).
> 
> @asias does rpc sink have buffering by default? what's the size? I want to make sure we're efficient by buffering some fragments and only them sending them down the stream.

The rpc stream is a thin wrapper of the tcp socket. There are many things decide how much data we send on wire each packet.  I do not think batching tons of fragments then asking rpc stream or rpc socket to send is going to make sending more efficient.  I think most of the time the bottleneck is how we read those fragments out from sstables which might consume a lot of cpu, not the network side.

**Comment by tzach** [comment]
@Michal-Leszczynski, let's update the subject of the issue or open a new one. It looks like the original issue does not exist.

**Comment by raphaelsc** [comment]
> > @Michal-Leszczynski turns out we're actually utilizing all shards. one of the problems is that we're limited by a node throughput to process and stream sstable data, and that depends on the data shape.
> > when benchmarking again, please take a look at cpu usage with per shard view (at least from node we're restoring data from).
> > @asias does rpc sink have buffering by default? what's the size? I want to make sure we're efficient by buffering some fragments and only them sending them down the stream.
> 
> The rpc stream is a thin wrapper of the tcp socket. There are many things decide how much data we send on wire each packet. I do not think batching tons of fragments then asking rpc stream or rpc socket to send is going to make sending more efficient. I think most of the time the bottleneck is how we read those fragments out from sstables which might consume a lot of cpu, not the network side.

I was thinking of cpu icache. Remember execution stages.
