### ISSUE TITLE
Flaky Tests / Unit Tests / test_fence_hints

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#18241]
It was seen here: https://github.com/scylladb/scylladb/pull/18141#issuecomment-2041774444

The CI result is here:

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7946/testReport/junit/(root)/test_fencing/

which says it has failed:

```
[Tests / Unit Tests / test_fence_hints](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7946/testReport/junit/(root)/test_fencing/Tests___Unit_Tests___test_fence_hints_9)	3.3 sec	Failed
```

But nothing is there.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7946/testReport/junit/(root)/test_fencing/Tests___Unit_Tests___test_fence_hints_9/

**Comment by kbr-scylla** [comment]
Artifacts are gone, cannot investigate! :((((( Please upload relevant logs to github when reporting issues

From the summary, it looks like dup of https://github.com/scylladb/scylladb/issues/17654

**Comment by yaronkaikov** [comment]
@asias 

> > Artifacts are gone, cannot investigate! :((((( Please upload relevant logs to github when reporting issues
> > From the summary, it looks like duplicate of #17654
> 
> First, the logs were not available when I created the issue. I could not find or upload the logs.
> 

That's strange, we should have it. if for some reason you can't find the logs next time, please ping releng-team and we will assist


> Second, why can't we keep the CI logs longer. This is not the first time the CI log are gone when someone wants to take a look. The compressed log for the test should not be huge. It is cheap to store them for a few month.
> 

Today we keep the artifacts for 7 days. I guess we can save it for more days, but shouldn't 7 days be enough to investigate ci failures? or at least save them?

> Third, it is hard to find the logs for the specific runs in the CI web page. It would be much better, if it shows a direct link to the scylla logs instead of huge amount of detective work.

Today when a test is failing in CI we have a direct link to the failed test, is this not what you need?  you can an example [here](https://github.com/scylladb/scylladb/pull/18290)

> 
> @mykaul We really need some improvement for our CI. It is wasting everybody's time.

**Comment by mykaul** [comment]
> Today when a test is failing in CI we have a direct link to the failed test, is this not what you need? you can an example [here](https://github.com/scylladb/scylladb/pull/18290)

It's not enough. I always need to dig into the test logs to figure out which NODE logs I need to fetch.

**Comment by yaronkaikov** [comment]
> > Today when a test is failing in CI we have a direct link to the failed test, is this not what you need? you can an example [here](https://github.com/scylladb/scylladb/pull/18290)
> 
> It's not enough. I always need to dig into the test logs to figure out which NODE logs I need to fetch.

yes, but this is related to the way we save the logs in Scylla, right? I mean, we can point to the logs. but we don't know from the failure which node is it

**Comment by mykaul** [comment]
> yes, but this is related to the way we save the logs in Scylla, right? I mean, we can point to the logs. but we don't know from the failure which node is it

May be, but this is what both @asias and myself are complaining on. The test could have been more verbose for example with what nodes are used, which could have helped.

**Comment by asias** [comment]
> @asias
> 
> > > Artifacts are gone, cannot investigate! :((((( Please upload relevant logs to github when reporting issues
> > > From the summary, it looks like duplicate of #17654
> > 
> > 
> > First, the logs were not available when I created the issue. I could not find or upload the logs.
> 
> That's strange, we should have it. if for some reason you can't find the logs next time, please ping releng-team and we will assist

Let's look at https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7946/testReport/junit/(root)/test_fencing/Tests___Unit_Tests___test_fence_hints_9/

I suggest we mention in the web page saying, that the logs are removed. Currently, if one look at the page, one has no idea that the log was removed, wasting time to find something one would never find. 

With the logs:

![image](https://github.com/scylladb/scylladb/assets/320076/aef07aa7-d8c1-406c-a9bb-883834bcd779)


With out the logs:

![image](https://github.com/scylladb/scylladb/assets/320076/c88db294-e72d-4fcb-82af-065e3b822f5a)




> > Second, why can't we keep the CI logs longer. This is not the first time the CI log are gone when someone wants to take a look. The compressed log for the test should not be huge. It is cheap to store them for a few month.
> 
> Today we keep the artifacts for 7 days. I guess we can save it for more days, but shouldn't 7 days be enough to investigate ci failures? or at least save them?

One may find the logs are useless at first but then another person find it useful. 

Let's take a look at your example: 

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8038/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest___test_rolling_upgrade/

The failed logs are 509.3KiB. 

That's the only failed test in the whole CI runs.

If we want to save money, we can save only the failed runs.

We can save them cheaply for years. Not to remove them in 7 days. 


> 
> > Third, it is hard to find the logs for the specific runs in the CI web page. It would be much better, if it shows a direct link to the scylla logs instead of huge amount of detective work.
> 
> Today when a test is failing in CI we have a direct link to the failed test, is this not what you need? you can an example [here](https://github.com/scylladb/scylladb/pull/18290)

Do we have direct links for the pytest runs in CI  failure report page? I mean if one test failed, it shows the direct links to the logs of scylla node for the exact run, instead of a sea of log  files. 

> 
> > @mykaul We really need some improvement for our CI. It is wasting everybody's time.

**Comment by asias** [comment]
@yaronkaikov BTW, what are those dest-gw{0,1,2,3,4}.log and why the dtest.log is of zero size. What is the last directory?

![image](https://github.com/scylladb/scylladb/assets/320076/fa6e044c-d2b6-472f-9d76-569e0288fef5)

**Comment by asias** [comment]
> > > Today when a test is failing in CI we have a direct link to the failed test, is this not what you need? you can an example [here](https://github.com/scylladb/scylladb/pull/18290)
> > 
> > 
> > It's not enough. I always need to dig into the test logs to figure out which NODE logs I need to fetch.
> 
> yes, but this is related to the way we save the logs in Scylla, right? I mean, we can point to the logs. but we don't know from the failure which node is it

Yes. A link to the logs of the node that have participated the test is good enough. If we could do the same for the tests run by ./test.py in CI report, that would be wonderful.

**Comment by mykaul** [comment]
> @yaronkaikov BTW, what are those dest-gw{0,1,2,3,4}.log and why the dtest.log is of zero size. What is the last directory?
> 
> ![image](https://private-user-images.githubusercontent.com/320076/323498755-fa6e044c-d2b6-472f-9d76-569e0288fef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQ2NDUsIm5iZiI6MTcxMzQyNDM0NSwicGF0aCI6Ii8zMjAwNzYvMzIzNDk4NzU1LWZhNmUwNDRjLWQyYjYtNDcyZi05ZDc2LTU2OWUwMjg4ZmVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzEyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmY1ZDI4OGM0MGEwNDExZjlmNDk0ZDRiMTJhMzJjNmZkZjY1MDg2NjExZWM2NzU2YmRhYWM3MmViZjY4ODIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDTfQUXQMAFwiKKT1RG547RHrZMS6aMYtkHNUP4Uy4Y)

Worked ID tells you which dtest-gwX log you need to look at. From there, you can understand the rest of the flows.

**Comment by yaronkaikov** [comment]
> > > @yaronkaikov BTW, what are those dest-gw{0,1,2,3,4}.log and why the dtest.log is of zero size. What is the last directory?
> > > ![image](https://private-user-images.githubusercontent.com/320076/323498755-fa6e044c-d2b6-472f-9d76-569e0288fef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQ2NDUsIm5iZiI6MTcxMzQyNDM0NSwicGF0aCI6Ii8zMjAwNzYvMzIzNDk4NzU1LWZhNmUwNDRjLWQyYjYtNDcyZi05ZDc2LTU2OWUwMjg4ZmVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzEyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmY1ZDI4OGM0MGEwNDExZjlmNDk0ZDRiMTJhMzJjNmZkZjY1MDg2NjExZWM2NzU2YmRhYWM3MmViZjY4ODIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDTfQUXQMAFwiKKT1RG547RHrZMS6aMYtkHNUP4Uy4Y)
> > 
> > 
> > Worked ID tells you which dtest-gwX log you need to look at. From there, you can understand the rest of the flows.
> 
> If CI knows the test is run under gw0 and other dtest logs are not relevant, why do we show the other gwX.logs in the first place.

Since Dtest is running on differenet pipeline, we just copy all artifacts that are available

**Comment by yaronkaikov** [comment]
@asias I suggest that if there are some specific changes you would like to do (or us to do ;-) ), please open an issue under Scylla-pkg, and we'll address them

**Comment by nyh** [comment]
> @asias I suggest that if there are some specific changes you would like to do (or us to do ;-) ), please open an issue under Scylla-pkg, and we'll address them

I feel the same pain as @asias. Apparently only @kbr-scylla really knows how to find these logs, but what seems obvious to him is not obvious to mortals like me and apparently Asias. I suggested in the past the following specific changes:

1. Don't delete logs of failed tests after 7 days. We need to use some common sense here - I don't need huge compilation results or core files (these can easily reach dozens of gigabytes), but the logs are tiny (usually!), so why delete them?
2. Using the logs should not require esoteric knowledge about how the CI or dtest works - we should have **direct HTTP links** to the specific log files that are implicated in this specific test failure, not "hints" or "filenames" that maybe (?) can help me find those logs files.

I don't know how easy it is to do this, or whether it should be done in the context of scylla-pkg, dtest, test.py or what. But since you asked for specific improvements, this is what I would have liked to see. I see that Asias now opened two issues on exactly these two things. Thanks Asias.

**Comment by asias** [comment]
> @asias I suggest that if there are some specific changes you would like to do (or us to do ;-) ), please open an issue under Scylla-pkg, and we'll address them

OK. I have created 4 so far ;)


https://github.com/scylladb/scylla-pkg/issues/3963
https://github.com/scylladb/scylla-pkg/issues/3964
https://github.com/scylladb/scylla-pkg/issues/3965
https://github.com/scylladb/scylla-pkg/issues/3966

**Comment by kbr-scylla** [comment]
@temichus and @xtrey are working on improving test.py log findability

**Comment by kbr-scylla** [comment]
> Apparently only @kbr-scylla really knows how to find these logs, but what seems obvious to him is not obvious to mortals like me and apparently Asias. 

@nyh It's not obvious, I had to learn it. I decided to learn it because I needed it so I learned it. If you don't want to learn it or you're not willing to put in the effort then obviously you won't magically gain the ability.

**Comment by mykaul** [comment]
> > Apparently only @kbr-scylla really knows how to find these logs, but what seems obvious to him is not obvious to mortals like me and apparently Asias.
> 
> @nyh It's not obvious, I had to learn it. I decided to learn it because I needed it so I learned it. If you don't want to learn it or you're not willing to put in the effort then obviously you won't magically gain the ability.

Agreed, but I'd also argue that we should not learn it - we can make it easier - and quicker.

**Comment by nyh** [comment]
> > Apparently only @kbr-scylla really knows how to find these logs, but what seems obvious to him is not obvious to mortals like me and apparently Asias.
> 
> @nyh It's not obvious, I had to learn it.

This is exactly why I called this "esoteric knowledge". It's not impossible to understand, but it can only be understood by someone who specifically learned how to do it. And don't forget the details are different for different types of tests (dtests, test.py, SCT, etc.). In an ideal world, one would not need to "learn" how to find files relevant to a specific test - this is why Vannevar Bush invented the hyperlink.
