### ISSUE TITLE
[Dtest]: possible scylla stopping procedure was stucked for test :TestSecondaryIndexes.test_stop_node_during_index_build 

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#18278]
During CI next test: [secondary_indexes_test.TestSecondaryIndexes.test_stop_node_during_index_build](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/981/testReport/secondary_indexes_test/TestSecondaryIndexes/FullDtest___full_split006___test_stop_node_during_index_build/) failed and generate coredump file, because stop node operation could stuck according logs:

According to log [https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent[…]y-changes/981/artifact/logs-full.release.006/dtest-gw0.log](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/981/artifact/logs-full.release.006/dtest-gw0.log)
Coredump was triggered because scylla process was not stopped during timeout:
```
16:21:45,827 793     cassandra.pool                 WARNING  thread.py           :58   | test_stop_node_during_index_build: Error attempting to reconnect to 127.0.50.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.50.2', 9042)]. Last error: Connection refused
16:21:49,119 793     ccm                            WARNING  cluster.py          :768  | test_stop_node_during_index_build: node2: node2 is still running after 127 seconds. Trying to generate coredump using kill(30752, SIGQUIT)...
16:21:49,835 793     cassandra.pool                 WARNING  thread.py           :58   | test_stop_node_during_index_build: Error attempting to reconnect to 127.0.50.2:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.50.2', 9042)]. Last error: Connection refused
16:21:50,121 793     ccm                            WARNING  cluster.py          :768  | test_stop_node_during_index_build: node2: node2 scylla-jmx is still running. Killing process using kill(127, SIGKILL)...
16:21:50,122 793     secondary_indexes_test         DEBUG    secondary_indexes_test.py:264  | test_stop_node_during_index_build: FINISH: stop node node2
```

And according to log node [https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent[…]ryIndexes%3A%3Atest_stop_node_during_index_build/node2.log](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/981/artifact/logs-full.release.006/1713284645226_secondary_indexes_test.py%3A%3ATestSecondaryIndexes%3A%3Atest_stop_node_during_index_build/node2.log)
stop process could stuck at this point:
```
INFO  2024-04-16 16:19:44,398 [shard 0:main] database - Flushed system tables
INFO  2024-04-16 16:19:44,409 [shard 0:main] view - Draining view builder
WARN  2024-04-16 16:19:44,409 [shard 0:strm] view - Unexcepted error executing build step: <no exception>. Ignored.
INFO  2024-04-16 16:19:44,409 [shard 1:main] view - Draining view builder
INFO  2024-04-16 16:19:44,928 [shard 0:main] raft_group_registry - marking Raft server bd667e91-9711-41d4-ae30-8d64287edc1a as dead for raft groups
INFO  2024-04-16 16:19:44,957 [shard 0:main] raft_group_registry - marking Raft server 09296259-ab08-4213-a8a8-712f612675ae as dead for raft groups
INFO  2024-04-16 16:19:44,963 [shard 0:main] raft_group_registry - marking Raft server f15e9585-2bc2-49bf-9f77-9bd5ae0d33cc as dead for raft groups
WARN  2024-04-16 16:20:42,274 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
WARN  2024-04-16 16:21:42,274 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
Scylla version 5.5.0~dev-0.20240416.d35c3a7035a2 with build-id dd43cd28a0bbeb33fcc44ef4b1c5f0912a9d167d starting ...
command used: "/jenkins/workspace/scylla-master/gating-dtest-release-with-consistent-topology-changes/scylla/.dtest/dtest-lf31zikc/test/node2/bin/scylla --options-file /jenkins/workspace/scylla-master/gating-dtest-release-with-consistent-topology-changes/scylla/.dtest/dtest-lf31zikc/test/node2/conf/scylla.yaml --log-to-stdout 1 --abort-on-seastar-bad-alloc --abort-on-lsa-bad-alloc 1 --abort-on-internal-error 1 --api-address 127.0.50.2 --smp 2 --memory 1024M --developer-mode true --default-log-level info --overprovisioned --prometheus-address 127.0.50.2 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --commitlog-use-o-dsync 0 --max-networking-io-control-blocks 1000"
pid: 36944
parsed command line options: [options-file: /jenkins/workspace/scylla-master/gating-dtest-release-with-consistent-topology-changes/scylla/.dtest/dtest-lf31zikc/test/node2/conf/scylla.yaml, log-to-stdout, (positional) 1, abort-on-seastar-bad-alloc, abort-on-lsa-bad-alloc: 1, abort-on-internal-error: 1, api-address: 127.0.50.2, smp, (positional) 2, memory, (positional) 1024M, developer-mode: true, default-log-level, (positional) info, overprovisioned, prometheus-address: 127.0.50.2, unsafe-bypass-fsync, (positional) 1, kernel-page-cache, (positional) 1, commitlog-use-o-dsync: 0, max-networking-io-control-blocks, (positional) 1000]
WARN  2024-04-16 16:21:50,278 seastar - Could not read cgroups v2 file (memory.max).
INFO  2024-04-16 16:21:50,280 seastar - Reactor backend: linux-aio
INFO  2024-04-16 16:21:50,281 seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
INFO  2024-04-16 16:21:50,285 [shard 0:main] seastar - updated: blocked-reactor-notify-ms=36000000000
INFO  2024-04-16 16:21:50,285 [shard 1:main] seastar - updated: blocked-reactor-notify-ms=36000000000
INFO  2024-04-16 16:21:50,289 [shard 0:main] init - installing SIGHUP handler
INFO  2024-04-16 16:21:50,292 [shard 0:main] init - Scylla version 5.5.0~dev-0.20240416.d35c3a7035a2 with build-id dd43cd28a0bbeb33fcc44ef4b1c5f0912a9d167d starting ...
```
all logs available: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/981/artifact/logs-full.release.006/

logs on github: 
[TestSecondaryINdex_stop_operation.tar.gz](https://github.com/scylladb/scylladb/files/15012303/TestSecondaryINdex_stop_operation.tar.gz)

Core : https://storage.googleapis.com/upload.scylladb.com/18278/node2-scylla.30752.1713284509.core.gz

**Comment by kbr-scylla** [comment]
Could be related but not sure: https://github.com/scylladb/scylladb/issues/17246

**Comment by kbr-scylla** [comment]
Shutdown issue, not critical, setting 6.1 milestone.
Also seems very rare, didn't see it before.

**Comment by kbr-scylla** [comment]
> all logs available: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/981/artifact/logs-full.release.006/

@aleksbykov can you upload logs to github? I'm worried that they might get garbage-collected from Jenkins

**Comment by kbr-scylla** [comment]
>  Also seems very rare, didn't see it before.

Well, apparently popping up recently, and pretty frequently

**Comment by kbr-scylla** [comment]
[dtest-gw2.log](https://github.com/scylladb/scylladb/files/15022854/dtest-gw2.log)
[node1.log](https://github.com/scylladb/scylladb/files/15022855/node1.log)
[node2.log](https://github.com/scylladb/scylladb/files/15022856/node2.log)
[node3.log](https://github.com/scylladb/scylladb/files/15022857/node3.log)
[node4.log](https://github.com/scylladb/scylladb/files/15022858/node4.log)

Another failure

**Comment by xemul** [comment]
Last meaningful logging message is about draining view builder. Recent change in this place was in #16558 , more specifically 1e0d96cfeded92c947910c36d92965ffb4745783

```
diff --git a/main.cc b/main.cc
index 2eeb815ab6..d5dda95129 100644
--- a/main.cc
+++ b/main.cc
@@ -2037,12 +2037,6 @@ To start the scylla server proper, simply invoke as: scylla server (or just scyl
                 ss.local().drain_on_shutdown().get();
             });
 
-            auto drain_view_builder = defer_verbose_shutdown("view builder ops", [cfg] {
-                if (cfg->view_building()) {
-                    view_builder.invoke_on_all(&db::view::view_builder::drain).get();
-                }
-            });
-
             startlog.info("Scylla version {} initialization completed.", scylla_version());
             stop_signal.wait().get();
             startlog.info("Signal received; shutting down");
diff --git a/service/storage_service.cc b/service/storage_service.cc
index e62afb539a..c921821d71 100644
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -4343,6 +4343,7 @@ future<> storage_service::do_drain() {
     co_await _db.invoke_on_all(&replica::database::drain);
     co_await _sys_ks.invoke_on_all(&db::system_keyspace::shutdown);
     co_await _repair.invoke_on_all(&repair_service::shutdown);
+    co_await _view_builder.invoke_on_all(&db::view::view_builder::drain);
 }
 
 future<> storage_service::do_cluster_cleanup() {
```

It effectively moved v.b. drain few steps down

**Comment by kbr-scylla** [comment]
I see no evidence that it's related to raft, taking off the label.

**Comment by kbr-scylla** [comment]
Ah, it was merged 2 days ago. So that's probably the culprit.

**Comment by xemul** [comment]
Let's see how it goes more verbosely :point_up:

**Comment by kbr-scylla** [comment]
The change should get reverted, it's making CI flaky.

**Comment by xemul** [comment]
> @denesb @xemul this failure happened on a CI run on your PR and everybody ignored it :/ [#16558 (comment)](https://github.com/scylladb/scylladb/pull/16558#issuecomment-2040525340)

@kbr-scylla , it then passed https://github.com/scylladb/scylladb/pull/16558#issuecomment-2049441419

**Comment by kbr-scylla** [comment]
> @kbr-scylla , it then passed https://github.com/scylladb/scylladb/pull/16558#issuecomment-2049441419

That's the thing with flakiness, sometimes tests pass, sometimes they don't
