### ISSUE TITLE
scylla-nodetool: links to online documentation have hardcoded product and version

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#18276]
The help for each commands has a link to the online documentation for that command. This link is currently hardcoded to point to the open-source documentation and the master version.
This worked fine until now, but as soon as we release, we will need these links to be context-sensitive: point to the documentation of the appropriate product (open-source or enterprise) and version.

**Comment by tzach** [comment]
@dgarcia360 any common solution?

**Comment by denesb** [comment]
I have a half-baked solution on a branch. I just need to get back to it.
