### ISSUE TITLE
Cannot run nodetool scrub --mode validate

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#18294]
## Packages

Scylla version: `5.5.0~dev-20240416.6707bc673c24` with build-id `c8d1d34663f8acf143dd1f790b2abcba9f4b4fde`

Kernel Version: `5.15.0-1057-aws`

## Issue description

- [X] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Running `nodetool scrub --mode VALIDATE` throws error:
```
Command: '/usr/bin/nodetool  scrub --mode VALIDATE --no-snapshot'
Exit code: 4
Stdout:
Stderr:
error executing GET request to http://localhost:10000/storage_service/keyspace_scrub/system_auth with parameters {{disable_snapshot -> true}, {scrub_mode -> VALIDATE}}: remote replied with status code 404 Not Found:
Not found

```
## Impact

Unable to run nodetool scrub with VALIDATE (other modes not tested)

## How frequently does it reproduce?

Always? 

## Installation details

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-ScyllaKillMonkey-t-db-node-18668e9a-3 (34.252.52.243 | 10.4.1.226) (shards: 2)
- longevity-5gb-1h-ScyllaKillMonkey-t-db-node-18668e9a-2 (34.245.204.106 | 10.4.3.177) (shards: 2)
- longevity-5gb-1h-ScyllaKillMonkey-t-db-node-18668e9a-1 (34.253.165.178 | 10.4.1.38) (shards: 2)

OS / Image: `ami-02d146088b477717a` (aws: undefined_region)

Test: `longevity-5gb-1h-ScyllaKillMonkey-aws-test`
Test id: `18668e9a-1ab6-47e1-b96d-52afa6498ab1`
Test name: `scylla-staging/lukasz/longevity-5gb-1h-ScyllaKillMonkey-aws-test`
Test config file(s):

- [longevity-5gb-1h-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1cbc34843b67a6927fe25a0c96e72f00936e3869/configurations/nemesis/longevity-5gb-1h-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 18668e9a-1ab6-47e1-b96d-52afa6498ab1`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=18668e9a-1ab6-47e1-b96d-52afa6498ab1)
- Show all stored logs command: `$ hydra investigate show-logs 18668e9a-1ab6-47e1-b96d-52afa6498ab1`

## Logs:
- **db-cluster-18668e9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/db-cluster-18668e9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/db-cluster-18668e9a.tar.gz)
- **sct-runner-events-18668e9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/sct-runner-events-18668e9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/sct-runner-events-18668e9a.tar.gz)
- **sct-18668e9a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/sct-18668e9a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/sct-18668e9a.log.tar.gz)
- **loader-set-18668e9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/loader-set-18668e9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/loader-set-18668e9a.tar.gz)
- **monitor-set-18668e9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/monitor-set-18668e9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/monitor-set-18668e9a.tar.gz)
- **parallel-timelines-report-18668e9a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/parallel-timelines-report-18668e9a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/18668e9a-1ab6-47e1-b96d-52afa6498ab1/20240417_145729/parallel-timelines-report-18668e9a.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/longevity-5gb-1h-ScyllaKillMonkey-aws-test/5/)
[Argus](https://argus.scylladb.com/test/38256c5f-88a2-4356-b777-c655de35e9cb/runs?additionalRuns[]=18668e9a-1ab6-47e1-b96d-52afa6498ab1)
</details>

**Comment by denesb** [comment]
I don't see any problems here with the printed URL: http://localhost:10000/storage_service/keyspace_scrub/system_auth with parameters {{disable_snapshot -> true}, {scrub_mode -> VALIDATE}}
This same command works for me locally, even if I call the URL explicitly with `curl`.

Are you by any chance calling `nodetool scrub` during startup/shutdown? I think what happens here is that you are attempting a scrub at a time when the API endpoints were either not yet registered or already unregistered.

**Comment by soyacz** [comment]
> Are you by any chance calling `nodetool scrub` during startup/shutdown? I think what happens here is that you are attempting a scrub at a time when the API endpoints were either not yet registered or already unregistered.

By chance it is exactly what happened, one node was during startup.
