### ISSUE TITLE
Potential use-after-move in mutation dump reader (courtesy of clang-tidy)

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#18322]
```
replica/mutation_dump.cc:187:56: warning: 'transformed_cr' used after it was moved [bugprone-use-after-move]
                maybe_push(e.underlying_crs, std::move(transformed_cr), clustering_key_view::tri_compare(*_underlying_schema));
                                                       ^
replica/mutation_dump.cc:187:17: note: move occurred here
                maybe_push(e.underlying_crs, std::move(transformed_cr), clustering_key_view::tri_compare(*_underlying_schema));
                ^
replica/mutation_dump.cc:187:56: note: the use happens in a later loop iteration than the move
                maybe_push(e.underlying_crs, std::move(transformed_cr), clustering_key_view::tri_compare(*_underlying_schema));
```

looks like a true positive, but @denesb please confirm it.

**Comment by raphaelsc** [comment]
@avikivity @mykaul I'd love that we somehow integrate clang-tidy into our CI. Maybe we can allow it to emit warnings (posted in PR), run it against the changed files only, so the patch writer / maintainer can at least review the warnings. If it's false positive, we just ignore it. To avoid a huge warning noise, maybe we can run it with a limited amount of checks (e.g. --checks=bugprone-use-after-move), and perhaps have a file (in master itself) with whitelisted warnings that we certainly know to be false positives. It's some significant work I know, but maybe worthwhile. I remember finding some significant amount of use-after-moves with clang-tidy and clang's annottation attributes, and these problems can easily result in crash / misbehavior for users. I run clang-tidy from time to time, but we need to automate it in some way, maybe we can find even something better than I suggested.

**Comment by raphaelsc** [comment]
I just found another use-after-move in sstable layer (again courtesy of clang-tidy), and this time it's a regression (in a error handling path). Automation could have prevented it.

**Comment by tchaikov** [comment]
@raphaelsc hi Raphael, it's on my to-do list. i planed to add it using github workflow, see #18122. since scylla-antlr35 is missing on jammy, i will try to find another way to integrate clang-tidy to our workflow.

**Comment by raphaelsc** [comment]
> @raphaelsc hi Raphael, it's on my to-do list. i planed to add it using github workflow, see #18122. since scylla-antlr35 is missing on jammy, i will try to find another way to integrate clang-tidy to our workflow.

Really glad that you plan to work on it @tchaikov. Thanks a lot. Please let me know if I can help you with anything.

**Comment by denesb** [comment]
> looks like a true positive, but @denesb please confirm it.

It is a false-positive. I'm moving a `const auto` variable multiple times, so it is in fact copying it. That said, the move is confusing so I'll send PR to remove it.

**Comment by raphaelsc** [comment]
> > looks like a true positive, but @denesb please confirm it.
> 
> It is a false-positive. I'm moving a `const auto` variable multiple times, so it is in fact copying it. That said, the move is confusing so I'll send PR to remove it.

thanks

summary of recent findings with clang-tidy

false positive

https://github.com/scylladb/scylladb/issues/18322
https://github.com/scylladb/scylladb/issues/18330

true positive - bug

https://github.com/scylladb/scylladb/issues/18323
https://github.com/scylladb/scylladb/issues/18324
https://github.com/scylladb/scylladb/issues/18332

true positive - benign

https://github.com/scylladb/scylladb/issues/18331
https://github.com/scylladb/scylladb/issues/18329

Kefu's PR to add clang-tidy to workflow: https://github.com/scylladb/scylladb/pull/18342
