### ISSUE TITLE
storage_proxy::_throttled_writes may grow without bound 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#1834]
If we're constantly under throttling condition, new handlers will be appended to _throttled_writes, but won't be removed when they're done.

**Comment by tgrabiec** [comment]
It has been de-prioritized since it seems relatively unlikely to cause problems.

**Comment by nyh** [comment]
> It has been de-prioritized since it seems relatively unlikely to cause problems.

Famous last words ;-)
Ended up causing problems - see https://github.com/scylladb/scylladb/issues/17476#issuecomment-1967942878.

**Comment by mykaul** [comment]
> > It has been de-prioritized since it seems relatively unlikely to cause problems.
> 
> Famous last words ;-) Ended up causing problems - see [#17476 (comment)](https://github.com/scylladb/scylladb/issues/17476#issuecomment-1967942878).

@nyh - didn't seem to cause problems in 7 years - I do wonder what changed.

**Comment by nyh** [comment]
> @nyh - didn't seem to cause problems in 7 years - I do wonder what changed.

I think that this specific bug only becomes relevant on a node which is **constantly** overloaded - as soon as the load slightly subsides, the memory is cleared. I assume this isn't a situation which will ever happen for real customers (who don't want their cluster to even temporarily be overloaded, let alone constantly be overloaded) - but can happen in tests which do this deliberately. In such tests we've seen in the past all sorts of overloads and OOMs, but these tests usually involved a lot of different things concurrently (MV, hints, repairs, view building, topology changes - all at the same time) and it was always easier to blamed the least-trusted component than to to debug a specific case which we can never reproduce (I think @wmitros and now @michoecho were the first to try to use a core dump and esoteric gdb utilities to analyze such OOMs).

As I noted in #17476, adding both view building and topology changes caused the system to become significantly more loaded than it was, which can probably increase the chance that we'll see throttling never turn off for a long time and cause this bug. But even then I think it's a random thing - if throttling goes of for just a tiny amount of time, all the garbage could have been cleared. A more reliable for this test case would probably need to **ensure** that throttling is constantly needed, but I'm not sure how: I'm not sure that making one node artificially slower will be enough to guarantee that we don't finish one background write and discover we're one byte blow the throttling limit. In fact, I'm not even sure how this didn't always happen (namely, we're at the limit but finish one write - at which point, haven't we gone below the limit?) - if this happened, we wouldn't have this bug at all, right?

**Comment by michoecho** [comment]
> In fact, I'm not even sure how this didn't always happen (namely, we're at the limit but finish one write - at which point, haven't we gone below the limit?) - if this happened, we wouldn't have this bug at all, right?

@nyh There are two limits: on background[^1] writes (10% of RAM) and on queued[^2] writes (6 MiB). The throttling happens when any of them is exceeded.
You seem to have assumed that only the first one exists.  But the problem here is actually triggered by the second one:
```
(gdb) py print(sharded(gdb.parse_and_eval('debug::the_storage_proxy')).local().dereference()['_global_stats']['queued_write_bytes'])
395521691
```

So the volume of queued writes is 400 MiB — faaar above the threshold of 6 MiB.

[^1]: CL satisfied, but some replicas haven't replied yet.
[^2]: Passed to the RPC layer, but RPC haven't sent it out yet.

**Comment by nyh** [comment]
@michoecho you're right, I had no idea what are "queued writes" as opposed to "background writes". @gleb-cloudius is this documented anywhere (some ancient design document or commit message or something).

It sounds from your explanation that the "queued writes" are "passed to the RPC layer but the RPC haven't sent it out yet". In this case, it is different from _throttled_writes, right? So it sounds like we have yet another bug besides _throttled_writes - the fact that we tried to limit "queued writes" to 6MB but it actually reached 400 MB and didn't go down?

**Comment by gleb-cloudius** [comment]
> @michoecho you're right, I had no idea what are "queued writes" as opposed to "background writes". @gleb-cloudius is this documented anywhere (some ancient design document or commit message or something).
> 

Commit that introduced it have the explanation fe4bc741f47f181c241001aeb4764606518dd447.

> It sounds from your explanation that the "queued writes" are "passed to the RPC layer but the RPC haven't sent it out yet". In this case, it is different from _throttled_writes, right?

There is a coordinator write handler and writes to replicas. Coordinator throttles replies to writes based on queue length of writes to replicas. Those two a completely different things.

> So it sounds like we have yet another bug besides _throttled_writes - the fact that we tried to limit "queued writes" to 6MB but it actually reached 400 MB and didn't go down?

Throttling does not work for unlimited concurrency. I do wonder though how did we get to a state that we queued 400MB of unsent messages. The dst may have reached its memory limit (managed somewhere in RPC) and stop admitting new RPCs.
