### ISSUE TITLE
"scylla sstable dump-data" fails to load schema if ran from dbuild container 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#18352]
It fails with "failed loading schema tables from (...): keyspace directory entry (...) has unrecognized type". This comes from this check:

```c++
            if (!de.type) {
                throw std::runtime_error(fmt::format("failed loading schema tables from {}: keyspace directory entry {} has unrecognized type", scylla_data_path.native(), de.name));
            } else if (*de.type != directory_entry_type::directory) {
                throw std::runtime_error(fmt::format("failed loading schema tables from {}: keyspace directory entry {} has unrecognized type {}", scylla_data_path.native(), de.name, static_cast<int>(*de.type)));
            }
```

If the check is commented out, the tool successfully loads the schema and dumps the sstable.

**Comment by denesb** [comment]
I cannot reproduce this. I tried running scylla-sstable both on a directory which lived inside the container, and one attached via `-v` and in both cases it worked.
What is the command-line you used?

In any case, with the new support for [loading schema from the sstable itself](https://github.com/scylladb/scylladb/pull/19169), you shouldn't hit this error anymore.

**Comment by mykaul** [comment]
@denesb - what's the next step here?

**Comment by denesb** [comment]
> [@denesb](https://github.com/denesb) - what's the next step here?

Either @tgrabiec provides instructions on how to reproduce, or we close this as stale.

**Comment by tgrabiec** [comment]
I can't reproduce anymore. Don't know what special conditions are needed.
