### ISSUE TITLE
[Regression]: the ability of figuring which shard owns a partition from system.large_partition by analyzing a corresponding sstable id is broken

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#18381]
*Installation details*
HEAD: e431e7dc163af6c78c65209a538d111fb019ae98

*Description*
SStable ID was changed to be a UUID instead of an integer which was encoding a shard ID that owns the corresponding SStable.

As a result there is no easy way to tell which shard owns items from `system.large_partition/cell/row` when before that one could simply do `<sstable id> mod <total shards count>`.

We need a way to get a shard ownership for items from these tables.

In the tablets world we also need a way to tell what shard owns a particular sstable **now**.

**Comment by vladzcloudius** [comment]
cc @avikivity @raphaelsc @mkeeneyj

**Comment by raphaelsc** [comment]
turns out we have this shard-of command https://github.com/scylladb/scylladb/pull/16345 (available through scylla binary), but it's not available in 5.4 (probably worth backporting since uuid is the default sstable generation type there IIRC).

**Comment by vladzcloudius** [comment]
> turns out we have this shard-of command #16345 (available through scylla binary), but it's not available in 5.4 (probably worth backporting since uuid is the default sstable generation type there IIRC).

Was it merged?

**Comment by tchaikov** [comment]
prepared a backport targeting `branch-5.4`.

**Comment by mykaul** [comment]
@tchaikov - I think this can be closed as completed?

**Comment by tchaikov** [comment]
agreed. Closing.
