### ISSUE TITLE
ninja: error: unknown target 'build/dev/scylla'

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#18384]
With recent master, scylla commit: c0e4f3e646d66603a11eabf2e3d3757b4e2ace42, it seems the build/dev/scylla is missing for some reason.

```
bash-5.2$ ./configure.py --disable-dpdk
bash-5.2$ ninja build/dev/scylla
[1/2] ./SCYLLA-VERSION-GEN --output-dir /home/asias/src/cloudius-systems/scylla/build
ninja: error: unknown target 'build/dev/scylla'

```

**Comment by michoecho** [comment]
Duplicate of https://github.com/scylladb/scylladb/issues/18321

**Comment by asias** [comment]
Closed as duplicate of https://github.com/scylladb/scylladb/issues/18321.
