### ISSUE TITLE
5.4.6/dtest-debug test_nodes_rejoining_a_cluster_synch_on_schema failure with AssertionError

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#18401]
Log snippet:
```
       logger.debug("6. Verify the stopped node synchs on the updated schema")
        session = self.patient_exclusive_cql_connection(node1)
        rows = session.execute(SimpleStatement(
            "SELECT * FROM ks.cf WHERE key=\'test\'", consistency_level=ConsistencyLevel.ALL))
        expected = [['test', 'test', 'test', 'test']]
>       assert rows_to_list(rows) == expected, f"Expected {expected} but got {rows} instead"
E       AssertionError: Expected [['test', 'test', 'test', 'test']] but got <cassandra.cluster.ResultSet object at 0x7fca84dd0190> instead
E       assert [['test', 'test', 'test']] == [['test', 'test', 'test', 'test']]
E         At index 0 diff: ['test', 'test', 'test'] != ['test', 'test', 'test', 'test']
E         Full diff:
E         - [['test', 'test', 'test', 'test']]
E         ?                  --------
E         + [['test', 'test', 'test']]
```

Logs:
[rejoin_dtest-gw1.log](https://github.com/scylladb/scylladb/files/15093575/rejoin_dtest-gw1.log)
[rejoin_node1.log](https://github.com/scylladb/scylladb/files/15093578/rejoin_node1.log)
[rejoin_node2.log](https://github.com/scylladb/scylladb/files/15093579/rejoin_node2.log)
[rejoin_node3.log](https://github.com/scylladb/scylladb/files/15093587/rejoin_node3.log)

**Comment by mykaul** [comment]
Previous failure link - https://jenkins.scylladb.com/job/scylla-5.4/job/dtest-debug/17/artifact/logs-full.debug.009/

**Comment by mykaul** [comment]
To everyone's surprise, it also fails on 2024.1.5/dtest-debug.

@kbr-scylla - does that belong to your team?

**Comment by kbr-scylla** [comment]
The node doesn't block on startup before opening CQL port, waiting for schema sync or group 0 sync or whatever.
So there is no guarantee that by the time we query it after restarting, it got the latest schema. The test bases its "correctness" on timing.

And I guess in debug mode it's easier to hit the race where we query before the restarted node obtains latest schema change.

@temichus I see you implemented this test last year (scylladb/scylla-dtest@3bb33bcd6), so I'm assigning this to you. The fix is simple -- we can perform a read barrier on the restarted node before querying, something like (modulo how the interface of `read_barrier` will look like):
```python3
        logger.debug("6. Verify the stopped node synchs on the updated schema")
        session = self.patient_exclusive_cql_connection(node1)
        read_barrier(session, node1)
        rows = session.execute(SimpleStatement("SELECT * FROM ks.cf WHERE key='test'", consistency_level=ConsistencyLevel.ALL))
```

To implement `read_barrier` we can do similar thing to what test.py does:
```python3
async def read_barrier(cql: Session, host: Host):
    """To issue a read barrier it is sufficient to attempt dropping a
    non-existing table. We need to use `if exists`, otherwise the statement
    would fail on prepare/validate step which happens before a read barrier is
    performed.
    """
    await cql.run_async("drop table if exists nosuchkeyspace.nosuchtable", host = host)
```

There is also a request to add read barrier API https://github.com/scylladb/scylladb/issues/19213 but for now we can use the above workaround

**Comment by mykaul** [comment]
Same failure in 5.4.8  - https://jenkins.scylladb.com/job/scylla-5.4/job/dtest-debug/29/testReport/schema_management_test/TestSchemaManagement/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split006___test_nodes_rejoining_a_cluster_synch_on_schema_True_/

**Comment by mykaul** [comment]
2024.1.8/dtest-debug - https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-debug/34/testReport/schema_management_test/TestSchemaManagement/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split010___test_nodes_rejoining_a_cluster_synch_on_schema_False_/ - but I assume it just missed the backport (https://github.com/scylladb/scylla-dtest/pull/4820 )

**Comment by mykaul** [comment]
2024.1.8/dtest-debug - https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-debug/34/testReport/schema_management_test/TestSchemaManagement/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split008___test_nodes_rejoining_a_cluster_synch_on_schema_True_/

**Comment by mykaul** [comment]
Even with the backport, 2024.1.9/dtest-debug still fails - 2024.1.9/dtest-debug still fails - https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-debug/37/testReport/schema_management_test/TestSchemaManagement/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split008___test_nodes_rejoining_a_cluster_synch_on_schema_False_/

**Comment by kbr-scylla** [comment]
[node1.log](https://github.com/user-attachments/files/16994575/node1.log)

Opening the log, this immediately stands out -- the node is doing schema pulls:
```
INFO  2024-08-30 12:01:10,708 [shard 0:goss] migration_manager - Requesting schema pull from 127.0.90.2:0
INFO  2024-08-30 12:01:10,708 [shard 0:goss] migration_manager - Pulling schema from 127.0.90.2:0
INFO  2024-08-30 12:01:10,779 [shard 0:stre] migration_manager - Requesting schema pull from 127.0.90.2:0
```

which implies that it is running without Raft (in 2024.1 / 5.4: Raft enabled => schema pulls disabled)
and indeed:
```
INFO  2024-08-30 12:01:09,854 [shard 0:stre] raft_group0 - finish_setup_after_join: local RAFT feature disabled, skipping.
```

**Comment by kbr-scylla** [comment]
I propose to switch dtest-debug job to run with Raft enabled, because that is the default in 2024.1.
Opened issue in dtest: https://github.com/scylladb/scylla-dtest/issues/4937
That will automatically fix this one. So I guess we can keep this one closed.

**Comment by mykaul** [comment]
2024.1.11 / dtest-debug - https://jenkins.scylladb.com/job/enterprise-2024.1/job/dtest-debug/46/testReport/schema_management_test/TestSchemaManagement/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split006___test_nodes_rejoining_a_cluster_synch_on_schema_True_/ 

Should not be seen in 2024.1.12 and above with Raft enabled by default in the tests.
