### ISSUE TITLE
RFC: Remove Thrift support

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#18416]
[ScyllaDB 5.2 release notes](https://forum.scylladb.com/t/release-scylla-5-2-0-release-part-2/520) includes the following:
> Thrift API - legacy ScyllaDB (and Apache Cassandra) API is deprecated and will be removed in followup release. Thrift has been disabled by default.

Enougth time has pass to remove Thrift support from the code.

**Comment by tchaikov** [comment]
I already started working on it

**Comment by tchaikov** [comment]
see also #3811
