### ISSUE TITLE
[MacOS with Docker on Colima runtime) : need method to run scyllaDB in docker with less memory since --max-io-requests  removed

### ISSUE THREAD

**Issue by calvin2021y** [scylladb/scylladb#18448]
for old 5.1, I can start docker with option `--memory 2G --smp 2 --max-io-requests 4 --num-io-groups 1` to reduce memory.

after recent 5.1 images,  It is removed.

I can not find a way to made it work with 8G memory (for dev env, 8G is big, since there is a lot other containers need to run)

```sh
Could not initialize seastar: std::runtime_error (insufficient physical memory: needed 2147483648 available 500000000)
```

*Installation details*

docker with `--memory 2G --smp 2 --overprovisioned --developer-mode 0 --io-setup 0 --max-io-requests 4 --num-io-groups 1 --api-address 0.0.0.0`

**Comment by calvin2021y** [comment]
I need skip `io-setup`, and made it start with 2GB memory.  any solution?

**Comment by calvin2021y** [comment]
I try run the docker from linux with same configure, it work fine.

If I run it from macOS with colima, I get the available 500000000 error, but there is a lot memory:

```sh
docker exec -it scylla free 
              total        used        free      shared  buff/cache   available
Mem:        8117088     1362680     5316496        5376     1437912     6495896
Swap:             0           0   
```

Seems scyllaDB read wrong memory size in colima container, any tips ?

**Comment by mykaul** [comment]
So it's on Mac, with Colima - what about other container runtimes under Mac?

**Comment by calvin2021y** [comment]
after change to podman it work like linux docker.

**Comment by calvin2021y** [comment]
I am not sure the problem is cause by ScyllaDB or Colima runtime, so maybe should keep this open.

**Comment by mykaul** [comment]
Did you ask / file a bug on Colima?

**Comment by calvin2021y** [comment]
not yet, I has to switch my env into podman. and I plan late create a new env to do it so I can have more details for them.
