### ISSUE TITLE
describe schema with internals: CREATE statement for CDC tables are incorrectly included

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#18459]
Consider this python script (I'm not using cqlsh because it does not support server-side describe yet (https://github.com/scylladb/scylla-cqlsh/issues/17)):

```python3
from cassandra.cluster import Cluster

c = Cluster()
s = c.connect()

s.execute("create keyspace if not exists ks with replication = {'class': 'SimpleStrategy', 'replication_factor': 1}")
s.execute("create table if not exists ks.t (a int primary key, b int) with cdc = {'enabled': true}")
result = s.execute("describe schema with internals")

for r in result:
    print(r.create_statement)
```

This is the output:

```
CREATE KEYSPACE ks WITH replication = {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;
CREATE TABLE ks.t (
    a int,
    b int,
    PRIMARY KEY (a)
) WITH ID = 8c091d40-0607-11ef-b773-697dd8707676
AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1
    AND dclocal_read_repair_chance = 0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0
    AND speculative_retry = '99.0PERCENTILE'
    AND paxos_grace_seconds = 864000
    AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'}
    AND cdc = {'delta': 'full', 'enabled': 'true', 'postimage': 'false', 'preimage': 'false', 'ttl': '86400'};

CREATE TABLE ks.t_scylla_cdc_log (
    "cdc$stream_id" blob,
    "cdc$time" timeuuid,
    "cdc$batch_seq_no" int,
    a int,
    b int,
    "cdc$deleted_b" boolean,
    "cdc$end_of_batch" boolean,
    "cdc$operation" tinyint,
    "cdc$ttl" bigint,
    PRIMARY KEY ("cdc$stream_id", "cdc$time", "cdc$batch_seq_no")
) WITH ID = 8c091d42-0607-11ef-b773-697dd8707676
AND CLUSTERING ORDER BY ("cdc$time" ASC, "cdc$batch_seq_no" ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'enabled': 'false', 'keys': 'NONE', 'rows_per_partition': 'NONE'}
    AND comment = 'CDC log for ks.t'
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '60', 'compaction_window_unit': 'MINUTES', 'expired_sstable_check_frequency_seconds': '1800'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1
    AND dclocal_read_repair_chance = 0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0
    AND speculative_retry = '99.0PERCENTILE'
    AND paxos_grace_seconds = 864000
    AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'};
```

This is incorrect for the purpose of restoring schema from DESCRIBE SCHEMA WITH INTERNALS, because the first CREATE TABLE statement creates two tables (`t` and `t_scylla_cdc_log`) due to the `WITH cdc` option. Due to that, the last CREATE TABLE statement  will fail because the table already exists.

We should check whether it's possible to adjust any of the parameters of the `_scylla_cdc_log` table.

- If it is not possible, we can drop the second statement completely.
- If it is possible, we should change the second statement into an `ALTER TABLE`.

**Comment by piodul** [comment]
I think this is a release blocker for restoring schema via DESCRIBE SCHEMA WITH INTERNALS without manual intervention or some unsavory filtering by name. I'll mark it as such.

**Comment by piodul** [comment]
> Manager might be able to workaround it. Need to check. @Michal-Leszczynski might be able to help.

If we decide that Manager uses a driver and executes DESCRIBE SCHEMA WITH INTERNALS, then it could filter out tables with name ending with `_scylla_cdc_log`. There is a risk that a user creates a table with a name that ends with `_scylla_cdc_log`, it would be improperly ignored, but perhaps that risk is not large.

If one restores schema from a file with CQL commands (which we consider as an _option_ for the Manager, but it is _required_ for the manual schema restore procedure) then it's more tricky as it is just a text file. Some parsing would be needed to filter out the problematic statements (maybe user could do it manually?).

**Comment by Michal-Leszczynski** [comment]
As @piodul said, it depends on the way in which SM receives schema from Scylla.

**Comment by mykaul** [comment]
> Is the milestone correct? Isn't this a blocker for 6.0?

I don't think so. I think @piodul suggested (@ https://github.com/scylladb/scylladb/issues/18459#issuecomment-2083248292 ) a very reasonable workaround for Manager.
