### ISSUE TITLE
View update backlog may not be read from gossip if it drops to 0

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#18462]
When gossiping the view update backlog https://github.com/scylladb/scylladb/blob/4433d2e10e1764609e98b59273b298720d301ca7/service/misc_services.cc#L237-L262
We get the backlog using `storage_proxy::get_view_update_backlog()`: https://github.com/scylladb/scylladb/blob/4433d2e10e1764609e98b59273b298720d301ca7/service/storage_proxy.cc#L2444-L2446
Which takes the backlog from the `node_view_update_backlog`: https://github.com/scylladb/scylladb/blob/4433d2e10e1764609e98b59273b298720d301ca7/db/view/view.cc#L2628-L2644
However, the received backlog is not updated if the backlog's current size or max capacity is `ULLONG_MAX`:
https://github.com/scylladb/scylladb/blob/4433d2e10e1764609e98b59273b298720d301ca7/service/misc_services.cc#L271-L299

^ I'm not actually sure why we have this check. I assume it's to avoid updating an actual value that we got with a default one (represented by `backlog{0, ULLONG_MAX}`), but I don't see where we could get an invalid default backlog.

The issue occurs because when trying to update the backlog , we create the backlog to send using: https://github.com/scylladb/scylladb/blob/4433d2e10e1764609e98b59273b298720d301ca7/db/view/view.cc#L2633-L2638
And when the backlogs are empty, the default, `update_backlog::no_backlog()` is returned in the above expression.

We can fix this either by removing the `ULLONG_MAX` check, or by making sure that actual backlogs (with max capacity less than `ULLONG_MAX`) are treated as "larger" than the default backlog

**Comment by nyh** [comment]
I only have vague recollections about this code (it was Duarte who wrote it six years ago), but this may have been deliberate, a (permature?) optimization that if there's nothing interesting to gossip, we won't gossip, and when the other nodes want to know our backlog, they see they don't have any new information and assume (even without this gossip) the value is zero. I remember (again, vaguely) that we remember the time when the backlog information was received (via gossip or piggy-backed on a response), and after a short time we "forget" this value and it becomes zero anyway.

So although I share you puzzlement on why there is this weird maxint corner-case, I'm afraid I don't understand what is the actual problem you are reporting here. Is the problem that we only "forget" (zero) the outdated gossiped value after a long time (?) and not quickly enough ? Don't we get the zero value almost immediately in responses? Did you see an actual problem with this in a real test case, and can you say something about what you did and what you saw?

**Comment by wmitros** [comment]
> So although I share you puzzlement on why there is this weird maxint corner-case, I'm afraid I don't understand what is the actual problem you are reporting here. Is the problem that we only "forget" (zero) the outdated gossiped value after a long time (?) and not quickly enough ? Don't we get the zero value almost immediately in responses? Did you see an actual problem with this in a real test case, and can you say something about what you did and what you saw?

The incorrect values that we had because of this issue were interfering with my testing of https://github.com/scylladb/scylladb/pull/18334. 
This issue doesn't have any big consequences in the current codebase because we're only using the backlogs for calculating delays for mv flow control, so the worst that could happen is using too long of a delay.
However, what we have is also just incorrect. Because of the `ULLONG_MAX` condition, we simply cannot reduce the tracked view update backlog size to 0 through gossip. Many times, it will be quickly updated through a response, but it doesn't have to - if the requests were sent in one big burst, the backlog returned in their responses may have grown considerably, and if it managed to drop to 0 before the gossip timer finished, we will be stuck with the bigger value

**Comment by nyh** [comment]
> > So although I share you puzzlement on why there is this weird maxint corner-case, I'm afraid I don't understand what is the actual problem you are reporting here. Is the problem that we only "forget" (zero) the outdated gossiped value after a long time (?) and not quickly enough ? Don't we get the zero value almost immediately in responses? Did you see an actual problem with this in a real test case, and can you say something about what you did and what you saw?
> 
> However, what we have is also just incorrect. Because of the `ULLONG_MAX` condition, we simply cannot reduce the tracked view update backlog size to 0 through gossip. Many times, it will be quickly updated through a response, but it doesn't have to - if the requests were sent in one big burst, the backlog returned in their responses may have grown considerably, and if it managed to drop to 0 before the gossip timer finished, we will be stuck with the bigger value

I had a vague recollection that we had sort of expiration time on backlogs, so if we remember some old value from a minute ago and never got a new value, we ignore the old value and default to 0. But now that I tried to look for this code, I couldn't find so I guess it doesn't exist, and you're right - gossip should be allowed to send the value 0.

One consequence of this will be that a database that has no materialized views at all will still gossip these zero values all the time. I guess this negligible, but maybe this was the reason why this "optimization" was added originally?

**Comment by piodul** [comment]
About the `ULLONG_MAX`: apparently, it can be returned by `std::strtoull` if the number it tries to parse is out of range, ref: https://en.cppreference.com/w/cpp/string/byte/strtoul . I think the code is trying to handle this case - you can also see that later there is a call to `std::strtoll` which checks for `LLONG_MAX` (note that this is a different function and a constant), so this looks intentional.

On the other hand, the confusion of `ULLONG_MAX` == `std::numeric_limits<size_t>::max()` (latter being used in `update_backlog::no_backlog()` seems unintentional.

Perhaps we should look at `errno` if we receive `ULLONG_MAX` (or use a more sensible string-to-number conversion function.. C++ has multiple of them).

**Comment by piodul** [comment]
On the other hand, if we get a value out of range in the backlog description in gossip (which seems unlikely to me) then I suppose that falling back to `ULLONG_MAX` is a sensible behavior, so perhaps removing the check is the way to go.

**Comment by wmitros** [comment]
> About the `ULLONG_MAX`: apparently, it can be returned by `std::strtoull` if the number it tries to parse is out of range, ref: https://en.cppreference.com/w/cpp/string/byte/strtoul . I think the code is trying to handle this case - you can also see that later there is a call to `std::strtoll` which checks for `LLONG_MAX` (note that this is a different function and a constant), so this looks intentional.
> 
> On the other hand, the confusion of `ULLONG_MAX` == `std::numeric_limits<size_t>::max()` (latter being used in `update_backlog::no_backlog()` seems unintentional.
> 
> Perhaps we should look at `errno` if we receive `ULLONG_MAX` (or use a more sensible string-to-number conversion function.. C++ has multiple of them).

This definitely sounds like the actual reason for introducing this check, thanks for investigating

> On the other hand, if we get a value out of range in the backlog description in gossip (which seems unlikely to me) then I suppose that falling back to `ULLONG_MAX` is a sensible behavior, so perhaps removing the check is the way to go.

I can only imagine getting a value out of the ullong range as a result of some error, in which case we may actually get a backlog of `relative_size()` more than 1 (if the error only occurs for the backlog size, not max), which could cause issues in MV control, so I used the `errno`s after all
