### ISSUE TITLE
enhancement: override service level per query using USING SERVICE LEVEL = name

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18471]
Generally, service levels apply to the entire session. But we may want to allow drivers to run their metadata operations (schema fetches) in a separate service level, to avoid schema refreshes from impacting the main workload.

Example:

```cql
SELECT *
FROM system_schema.columns
USING SERVICE_LEVEL = '...'
```

**Comment by dorlaor** [comment]
Neat, should be simple and aligns with our other options (timeout, bypass
cache,..)

**Comment by tzach** [comment]
Scylla needs to stop users from escalating their shares beyond what the admin attaches to their role.

**Comment by mykaul** [comment]
@ptrsmrn - a follow up to this would be to actually use this in specific metadata queries that clients perform.

**Comment by ptrsmrn** [comment]
> [@ptrsmrn](https://github.com/ptrsmrn) - a follow up to this would be to actually use this in specific metadata queries that clients perform.

@mykaul like in auth you mean?

**Comment by mykaul** [comment]
> > [@ptrsmrn](https://github.com/ptrsmrn) - a follow up to this would be to actually use this in specific metadata queries that clients perform.
> 
> [@mykaul](https://github.com/mykaul) like in auth you mean?

Yes.

**Comment by mykaul** [comment]
@avikivity - which service level would they use? How does the driver know which service levels exists, what is it assigned to, etc? We'd want (I reckon) some (fixed?) low service level?

**Comment by avikivity** [comment]
We need to create a new service level for drivers.

In general a driver can list service levels by using the LIST SERVICE LEVELS command, but the goal is to avoid executing queries on the main service level.

I think we should negotiate it early. The driver sends an OPTIONS message (it does so anyway), the server responds with SUPPORTED that also includes 'CONNECTION_SERVICE_LEVEL': '<NAME>' that tells the driver both that it can use the USING SERVICE LEVEL per-statement clause for that node, and what service level to use.

We should automatically create a service level named "driver" with 200 shares for this.

**Comment by piodul** [comment]
I think that one potential problem with the `SELECT ... USING SERVICE LEVEL` approach for querying metadata by the driver is that the service level will not cover all parts of the statement processing code. At a minimum, the statement needs to be parsed (or looked up if its prepared) and only then we can switch the scheduling group.

Ideally, the driver would authenticate with the right user which has the right service level assigned to it, but I understand that the driver can't be expected to know the user and the credentials, and involving authentication into this causes more problems.

How about `USE SERVICE LEVEL <lvl_name>`? This would allow downgrading the priority of a connection. We already have infrastructure for switching scheduling group of existing connections in runtime. I believe that it would also be easier to adjust drivers to use this, it's easier to issue one statement after the handshake than change all statements to use the `USING` clause and making sure that the statements are prepared in order not to waste time on parsing in the main service level.
