### ISSUE TITLE
systemd/packaging: relax dependencies on scylla-tools, scylla-jmx

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18472]
After 7cbe5c78b473117dab88dba1a9a521e94a2cf92e, we no longer need to install scylla-tools packages as a hard dependency. We also don't need to install scylla-jmx, and can make scylla-jmx.service optional.

**Comment by denesb** [comment]
I would prefer if someone more versed in packaging like @tchaikov or @syuu1228 worked on this, I can be a fall-back in case the others are too busy with other work.
