### ISSUE TITLE
Upgrade Node Exporter to 1.8.1

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#18493]
New release - not very exciting changelog, but still - https://github.com/prometheus/node_exporter/releases/tag/v1.8.0 :
[CHANGE] exec_bsd: Fix labels for vm.stats.sys.v_syscall sysctl https://github.com/prometheus/node_exporter/pull/2895
[CHANGE] diskstats: Ignore zram devices on linux systems https://github.com/prometheus/node_exporter/pull/2898
[CHANGE] textfile: Avoid inconsistent help-texts https://github.com/prometheus/node_exporter/pull/2962
[CHANGE] os: Removed caching of modtime/filename of os-release file https://github.com/prometheus/node_exporter/pull/2987
[FEATURE] xfrm: Add new collector https://github.com/prometheus/node_exporter/pull/2866
[FEATURE] watchdog: Add new collector https://github.com/prometheus/node_exporter/pull/2880
[ENHANCEMENT] cpu_vulnerabilities: Add mitigation information label https://github.com/prometheus/node_exporter/pull/2806
[ENHANCEMENT] nfsd: Handle new wdeleg_getattr attribute https://github.com/prometheus/node_exporter/pull/2810
[ENHANCEMENT] netstat: Add TCPOFOQueue to default netstat metrics https://github.com/prometheus/node_exporter/pull/2867
[ENHANCEMENT] filesystem: surface device errors https://github.com/prometheus/node_exporter/pull/2923
[ENHANCEMENT] os: Add support end parsing https://github.com/prometheus/node_exporter/pull/2982
[ENHANCEMENT] zfs: Log mib when sysctl read fails on FreeBSD https://github.com/prometheus/node_exporter/pull/2975
[ENHANCEMENT] fibre_channel: update procfs to take into account optional attributes https://github.com/prometheus/node_exporter/pull/2933
[BUGFIX] cpu: Fix debug log in cpu collector https://github.com/prometheus/node_exporter/pull/2857
[BUGFIX] hwmon: Fix hwmon nil ptr https://github.com/prometheus/node_exporter/pull/2873
[BUGFIX] hwmon: Fix hwmon error capture https://github.com/prometheus/node_exporter/pull/2915
[BUGFIX] zfs: Revert "Add ZFS freebsd per dataset stats https://github.com/prometheus/node_exporter/pull/2925
[BUGFIX] ethtool: Sanitize ethtool metric name keys https://github.com/prometheus/node_exporter/pull/2940
[BUGFIX] fix: data race of NetClassCollector metrics initialization https://github.com/prometheus/node_exporter/pull/2995

**Comment by yaronkaikov** [comment]
Already released https://github.com/prometheus/node_exporter/releases/tag/v1.8.1 , 

It will solve some of the CVE we have from `go`
