### ISSUE TITLE
abseil failures in debug mode in Fedora 39/40

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18507]
Likely cause is updated abseil. Fedora 38 packages 20220623.1, 40 packages 20240116.2.

abseil-cpp detects the sanitizier during package build time and during application compile time. In our debug mode, the two detections yield different results and things crash.

Likely the most practical solution is to reinstate abseil-cpp as a submodule and build it with our build flags, once per mode.

https://github.com/abseil/abseil-cpp/issues/1524
https://bugzilla.redhat.com/show_bug.cgi?id=2278689

**Comment by tchaikov** [comment]
@avikivity hi Avi, could you push fetch `lts_2024_01_16` from https://github.com/abseil/abseil-cpp/ and push it to https://github.com/scylladb/abseil-cpp ? i am seeing a FTBFS due to missing `#include <cstdint>` in abseil when building with 4e5ff1559ca3bd7bb777a1c48106464cb656e041.

**Comment by avikivity** [comment]
> @avikivity hi Avi, could you push fetch `lts_2024_01_16` from https://github.com/abseil/abseil-cpp/ and push it to https://github.com/scylladb/abseil-cpp ? it's the latest LTS branch. i am seeing a FTBFS due to missing `#include <cstdint>` in at least one of abseil's source files when building with 4e5ff1559ca3bd7bb777a1c48106464cb656e041.

It's pushed now.

**Comment by avikivity** [comment]
It would be more correct to use 2022-06-23 lts since that's what we have now, but if it causes problems, we can skip directly to 20240-01-16.

**Comment by tchaikov** [comment]
fixed by #18511. closing.
