### ISSUE TITLE
casting varint to float fails with boost-1.83.0-3.fc40.x86_64

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18508]
test/cql-pytest/test_cast_data.py

```python
    v = 32767456456456456456545678943512357658768763546575675
    cql.execute(f'INSERT INTO {table1} (p, cVarint) VALUES ({p}, {v})')
...
    # Casting to a 32-bit floating point, which only supports numbers up
    # to 1e38, results in infinity
    assert [(math.inf,)] == list(cql.execute(f"SELECT CAST(cVarint AS float) FROM {table1} WHERE p={p}"))
```

The server crashes while evaluating CAST().

**Comment by avikivity** [comment]
```
[44/3096]  cql-pytest   dev   [ FAIL ] cql-pytest.test_cast_data.1
[48/3096]  cql-pytest   dev   [ FAIL ] cql-pytest.test_compaction_strategy_validation.1
[151/3096] topology   dev   [ FAIL ] topology.test_coordinator_queue_management.1
[152/3096] topology   dev   [ FAIL ] topology.test_global_ignore_nodes.1
[2420/3096]  boost     dev   [ FAIL ] boost.string_format_test.1
```

**Comment by tchaikov** [comment]
looks like a bug in boost. created a fix at https://github.com/boostorg/multiprecision/pull/618 , which returns NaN in this case. as a workaround, we could "compare" the integer with maximum and minimum float, and return "inf" or "nan", if the number breaches the bounds. but as comparing an integer and a float is always complicated, i am not sure i am able to create a simple workaround.

**Comment by nyh** [comment]
Wouldn't it be better to creat an issue, not an incorrect fix?
The correct fix would return Inf, as before, not NaN.... Or even an
exception, I don't know why they are against those

**Comment by tchaikov** [comment]
@nyh could you please create an issue against boost upstream with more context and reasoning? apparently i don't understand why "inf" is correct or why "nan" is correct. i am just trying to follow the way how multiprecision's theory instead of against it.

**Comment by nyh** [comment]
Well, I just assumed that:
1. The old return value (inf) was correct.
2. It makes intuitive sense that if a large number is wrapped to anything, it should be to inf.
3. It would have been even better to throw an exception, but that's against the api which says noexcept.

**Comment by tchaikov** [comment]
merge upstream. i will prepare a backport in fedora packaging.

**Comment by avikivity** [comment]
Thanks!

**Comment by avikivity** [comment]
A build is available for people who moved to Fedora 40: https://koji.fedoraproject.org/koji/taskinfo?taskID=117264902

**Comment by tchaikov** [comment]
boost.math has a pending patch to correct this behavior. see https://github.com/boostorg/math/issues/1132

**Comment by tchaikov** [comment]
the patch above was backported to rawhide. now pending on review. see targetting rawhide

**Comment by tchaikov** [comment]
> the patch above was backported to rawhide. now pending on review. see https://src.fedoraproject.org/rpms/boost/pull-request/25

patched merged. i will keep an eye on it, and update here.

**Comment by tchaikov** [comment]
f40 now has this fix. see https://bodhi.fedoraproject.org/updates/FEDORA-2024-58ffecd8ed. and i verified locally with the test introduced by 51d09e6a2a407ea9b9ad380ba30e5558a25bb8be
