### ISSUE TITLE
Python-driver matrix reports regression in metadata tests for table extensions

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylladb#18501]
[Test: test_table_extensions](https://github.com/scylladb/python-driver/blob/7cdc1ca25ffa2194a0772e46ccd89645f8514c1b/tests/integration/standard/test_metadata.py#L959)
Class: datastax_version_3.28.0_v4_tests.integration.standard.test_metadata.SchemaMetadataTests
 ```
AssertionError: OrderedMapSerializedKey([('tombstone_gc', b'\x02\x00\x00\x00\x04\x00\x00\x00mode\x07\x00\x00\x00timeout\x1c\x00\x00\x00propagation_delay_in_seconds\x04\x00\x00\x003600')]) is not false (no-type)
```
Currently, both scylla and datastax tests are failing with this error, which seems to be an issue with deserializing table extensions response. Last known good build was `0.20240421.87b08c957ff7` (there were a couple of spot terminations in between the builds, so not sure if it was succesful there)

*Installation details*
Scylla version (or git commit hash): 5.5.0~dev0.20240501.af5674211dd4 (started with 0.20240425.c2b8ca7d7145)
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

**Comment by mykaul** [comment]
@k0machi - it's unclear (to me) what's failing. Which driver are you using here?

**Comment by fruch** [comment]
this is the python driver 

https://jenkins.scylladb.com/job/scylla-master/job/driver-tests/job/python-driver-matrix-test/1546/testReport/junit/scylla_version_3.25.11_v3_tests.integration.standard.test_metadata/SchemaMetadataTests/test_table_extensions/


on 5.5.0~dev-0.20240421.87b08c957ff7, test was passing
on 5.5.0~dev-0.20240425.c2b8ca7d7145, it started failing


@Deexie can you take a look ?, seem like this change is break this test expectation of not having any extensions by default

**Comment by k0machi** [comment]
> @k0machi - it's unclear (to me) what's failing. Which driver are you using here?

It's all versions of python-driver failing, both datastax and scylla ones.

**Comment by fruch** [comment]
@Lorak-mmk FYI, 

what do you think about this test ? maybe it's expectation to not have extension by default, is a bit off ?

**Comment by denesb** [comment]
I think the test will need to change. Tablets require using an extension (possibly more in the future) by default and going forward tablets is going to be the default.

**Comment by Lorak-mmk** [comment]
I think we should skip the test on new versions of Scylla. @fruch mentioned that it started failing on some 5.5 dev version - so I assume 5.4 should work and 6.0 onwards should be skipped, right?

**Comment by Lorak-mmk** [comment]
Opened https://github.com/scylladb/python-driver/pull/341
