### ISSUE TITLE
cql/describe: User-defined types should be sorted topologically to safely restore schema 

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#18539]
Currently, all elements in statements like `DESC SCHEMA`, `DESC KEYSPACE ks`, ... are sorted alphabetically.

But UDTs can depend on each other and in order to safely restore schema based on `DESC SCHEMA` output, UDTs should be sorted in a topological order to create UDTs which are dependencies in others firstly.

**Comment by piodul** [comment]
Marked this as a release blocker, as it's necessary for schema restore from DESCRIBE SCHEMA (we had a PR for this for some time already, but we created an issue only recently)
