### ISSUE TITLE
clang 18.1.1 miscompiles coroutines with references to static thread_local variables with initializers in debug mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18537]
Example 1: hold_merge_lock()

```c++
static thread_local semaphore the_merge_lock {1};

future<semaphore_units<>> hold_merge_lock() noexcept {
    assert(this_shard_id() == 0);

    if (slogger.is_enabled(log_level::trace)) {
        slogger.trace("hold_merge_lock at {}", current_backtrace());
    }
    return get_units(the_merge_lock, 1);
}
```

The semaphore is uninitialized when get_units is called.

Example 2: password_authenticator::create_default_if_missing()

```c++
static thread_local auto rng_for_salt = std::default_random_engine(std::random_device{}());

future<> password_authenticator::create_default_if_missing() {
    const auto exists = co_await default_role_row_satisfies(_qp, &has_salted_hash, _superuser);
    if (exists) {
        co_return;
    }
    std::string salted_pwd(get_config_value(_qp.db().get_config().auth_superuser_salted_password(), ""));
    if (salted_pwd.empty()) {
        salted_pwd = passwords::hash(DEFAULT_USER_PASSWORD, rng_for_salt);
    }
    const auto query = update_row_query();
    if (legacy_mode(_qp)) {
        co_await _qp.execute_internal(
            query,
            db::consistency_level::QUORUM,
            internal_distributed_query_state(),
            {salted_pwd, _superuser},
            cql3::query_processor::cache_internal::no).then([](auto&&) {
            plogger.info("Created default superuser authentication record.");
        });
    } else {
        co_await announce_mutations(_qp, _group0_client, query,
            {salted_pwd, _superuser}, &_as, ::service::raft_timeout{}).then([]() {
            plogger.info("Created default superuser authentication record.");
        });
    }
}
```

The call never terminates.

**Comment by avikivity** [comment]
17.0.6 is also broken.

**Comment by avikivity** [comment]
Verified manually, I'll file a bug with llvm.

**Comment by avikivity** [comment]
https://github.com/llvm/llvm-project/issues/91312

**Comment by michoecho** [comment]
How did you find this?

**Comment by tchaikov** [comment]
without the fix on clang on the workaround, scylla is broken, as we cannot load a table. without `thread_local static` member variables in `cql3_type`. see `cql3/cql3_type.cc`.

BTW, i just realized that i was actually suffering from this issue from a while, and my fix was
```diff
--- a/cmake/mode.Debug.cmake
+++ b/cmake/mode.Debug.cmake
@@ -2,7 +2,7 @@ if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
   # -fasan -Og breaks some coroutines on aarch64, use -O0 instead
   set(OptimizationLevel "0")
 else()
-  set(OptimizationLevel "g")
+  set(OptimizationLevel "0")
 endif()
```
but never got a chance to fix it, and then forgot it. as i keep a branch full of the random cleanup fixes so that scylla builds in my environment.

**Comment by avikivity** [comment]
> How did you find this?

Traditional debugging. Server hangs, breakpoint at last known good, notice that hold_merge_lock hangs, see that it's not initialized, hack the initializer to use a function containing a static instead of just a static, start the server, see same problem in password_authenticator, two samples -> generalization, bisect, file bug.

**Comment by avikivity** [comment]
Fix landed in https://github.com/llvmbot/llvm-project/commit/3d0752b9492efd60e85aedec79676596af6fb4f8. @tchaikov please see if you can get a new Fedora build going.

**Comment by tchaikov** [comment]
created https://src.fedoraproject.org/rpms/llvm/pull-request/207. it will need to be backported to f40 once the patch lands.

**Comment by avikivity** [comment]
Meanwhile, 18.1.6 was tagged: https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.6

**Comment by tchaikov** [comment]
@avikivity if we are building clang from source, can we just bump the version in at https://github.com/scylladb/scylladb/blob/a86fb293fe4a3fae1245e12dd6aaa86dfc344a13/tools/toolchain/optimized_clang.sh#L45 to 18.1.6 , and rebuild the docker image based on f40?

**Comment by nyh** [comment]
> 17.0.6 is also broken.

I see this too. On Fedora 39, clang 17.0.6-2.fc39, the debug build hangs during boot. So until it's fixed, I need to use dbuild for the debug builds.

**Comment by tchaikov** [comment]
> created https://src.fedoraproject.org/rpms/llvm/pull-request/207. it will need to be backported to f40, f39 and probably f38 once the patch lands.

patch closed. i need to create a patch targeting fc39.

**Comment by avikivity** [comment]
> @avikivity if we are building clang from source, can we just bump the version in at
> 
> https://github.com/scylladb/scylladb/blob/a86fb293fe4a3fae1245e12dd6aaa86dfc344a13/tools/toolchain/optimized_clang.sh#L45
> 
> to 18.1.6 , and rebuild the docker image based on f40?

I want a plain f40 to be able to build too. In any case, f40 now has 18.1.6.

**Comment by avikivity** [comment]
Closing as completed - https://bodhi.fedoraproject.org/updates/FEDORA-2024-9f3b00db88.

**Comment by tchaikov** [comment]
> > created https://src.fedoraproject.org/rpms/llvm/pull-request/207. it will need to be backported to f40, f39 and probably f38 once the patch lands.
> 
> the PR was closed due to the new release. i will create a patch targeting fc39.

https://src.fedoraproject.org/rpms/llvm/pull-request/224
