### ISSUE TITLE
boost.logalloc_test.background_reclaim: critical check compacted_pre == compacted_post has failed

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#18551]
Spotted in CI

[boost.logalloc_test.1.log](https://github.com/scylladb/scylladb/files/15237400/boost.logalloc_test.1.log)
```
test/boost/logalloc_test.cc(756): fatal error: in "background_reclaim": critical check compacted_pre == compacted_post has failed [2706735850 != 2712476452]
```

**Comment by bhalevy** [comment]
Isn't this a duplicate of https://github.com/scylladb/scylladb/issues/8234?

**Comment by kbr-scylla** [comment]
GitHub search is bad, or I can't use it, or both.

I'm pretty sure I pasted "background_reclaim" into GH issues search and it gave no results.

But now that I do it again, there are 8 opened issues found.

wtf.

Closing as duplicate of https://github.com/scylladb/scylladb/issues/15677
