### ISSUE TITLE
scylla-nodetool --help exits with error status

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18554]
https://github.com/scylladb/scylla-ccm/pull/574 wants scylla nodetool to returns a success status when invoked with `--help` so we can detect when a nodetool command is supported by the native scylla nodetool.

But currently (2d9142250eac278286428f52f62d339691d3598a), all seastar-based applications, including scylla, return status code 1 on `--help`.
This was fixed by https://github.com/scylladb/seastar/pull/2213 , which requires seastar submodule update to take effect in scylla.

**Comment by tchaikov** [comment]
fixed by #18598
