### ISSUE TITLE
Get rid of SHUTDOWN status

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#18552]
When a node performs graceful shutdown, it enters a "special" SHUTDOWN status. My understanding is that for most practices and purposes, it behaves like NORMAL status -- it is still a regular member of the token ring, being included in replica sets and so on.

In https://github.com/scylladb/scylladb/pull/14424 @asias proposed to remove the status. Citing the explanation:

> The SHUTDOWN status is a special NORMAL status. A node in SHUTDOWN status is part of the ring the same as NORMAL status. To simplify the handling, we can get rid of the SHUTDOWN status completely. There is no real difference between a node in SHUTDOWN status and a in NORMAL + DOWN status.
> 
> After this patch, when a node shutdown:
> 
>   * The shutdown node does not advertise SHUTDOWN gossip status
> 
>   * The shutdown node still sends the the SHUTDOWN rpc message
> 
>   * The receivers of the SHUTDOWN rpc message do not change the status of the node to SHUTDOWN but only mark the node as DOWN, keep the node as NORMAL gossip status.
> 
> 
> This way, other nodes still can mark the shutdown node as DOWN immediately while we have less gossip status in the system to handle and reason about.
> 
> For example, with this patch, we can now get rid of the hacks in [f3bd7e9](https://github.com/scylladb/scylladb/commit/f3bd7e9b8c610851dad07838c7bc43e99e1085c7) to add LEFT status to avoid sending shutdown message.
> 
> ```
> // Need to set it otherwise gossiper will try to send shutdown on exit
> co_await _gossiper.add_local_application_state({{
>     gms::application_state::STATUS, gms::versioned_value::left({},
>     _gossiper.now().time_since_epoch().count()) }});
> ```

It makes sense. However, if all of that is true, then the question is, what was the reason of introducing SHUTDOWN in the first place? It should have never been needed, right?

Potential explanations:
- Maybe it's for nodes that did not manage to receive RPC, but we still want them to notice the graceful shutdown fast (faster than failure detector's 20 seconds)?
- What about the drivers? Don't they rely on SHUTDOWN somehow?

Perhaps we have dtests that could help us answer the question?

Getting rid of this status would be a nice clean-up, but we should first investigate the above questions and determine whether it won't break anything. There could be something we're simply not aware of.

cc @asias @gleb-cloudius @kostja @tgrabiec

**Comment by kbr-scylla** [comment]
> Not sure why is this an issue and not a mailing list thread though.

I can't put a mailing list thread into a github project.

> https://github.com/scylladb/scylladb/commit/f62a6f234b1d113e3b1feeca0badb31eded05662 have some explanation.

Thanks. Copy-pasting:

> When X is shutdown, X sends SHUTDOWN message to both Y and Z, but for
some reason, only Y receives the message and Z does not receive the
message. If Z has a higher gossip version for X than Y has for
X, Z will initiate a gossip with Y and Y will mark X alive again.

So it's similar to this hypothesis

> Maybe it's for nodes that did not manage to receive RPC, but we still want them to notice the graceful shutdown fast (faster than failure detector's 20 seconds)?

Indeed, [principle of sufficient reason](https://en.wikipedia.org/wiki/Principle_of_sufficient_reason) prevails.

Closing.

**Comment by kbr-scylla** [comment]
Actually reopening, I jumped to conclusions too quickly.

> If Z has a higher gossip version for X than Y has for X, Z will initiate a gossip with Y and Y will mark X alive again.

This is no longer true -- our failure detector no longer works like that. To mark X alive again, Z now has to contact X directly, which it won't be able to.

**Comment by kostja** [comment]
@kbr-scylla afaiu @asias patch it gets rid of the enum value but the shutdown state itself can be inferred from NORMAL status + DOWN gossiper state. I think it's OK to not have a separate enum state and the patch is harmless. As such I think this separate issue doesn't have extra substance - if we are to merge the suggested patch from @asias we're of course to investigate whether or not it breaks any tests (through CI or otherwise).

**Comment by gleb-cloudius** [comment]
> @kbr-scylla afaiu @asias patch it gets rid of the enum value but the shutdown state itself can be inferred from NORMAL status + DOWN gossiper state. 

Down state is a local decision. How can we infer that a node was shutdown just because we cannot ping it?

**Comment by kbr-scylla** [comment]
> the shutdown state itself can be inferred from NORMAL status + DOWN gossiper state

It's not obvious like that, because DOWN is not a state like NORMAL, it is a local decision done independently by each node.

**Comment by gleb-cloudius** [comment]
> > Why would you want to put a discussion about if anything should be done at all into a github project?
> 
> Because the discussion may turn into a task 

Put the task into the issue when a discussion turns into one. Issue tracker is not a discussion forum.

**Comment by kbr-scylla** [comment]
> Issue tracker is not a discussion forum.

https://www.youtube.com/watch?v=pWdd6_ZxX8c

**Comment by gleb-cloudius** [comment]
> > Issue tracker is not a discussion forum.
> 
> https://www.youtube.com/watch?v=pWdd6_ZxX8c

Well, same can be said about yours. But your argument is basically "Sorry I do not know how to use email properly so  lets abuse the issue tracker".  Next thing we will use it instead of the slack as well. And actually the slack is so bad that it may be an improvement.

**Comment by gleb-cloudius** [comment]
And with email if you have a decent UA you can mark important emails or move them to the special mail box . With gmail you can label them.

**Comment by kostja** [comment]
> > @kbr-scylla afaiu @asias patch it gets rid of the enum value but the shutdown state itself can be inferred from NORMAL status + DOWN gossiper state.
> 
> Down state is a local decision. How can we infer that a node was shutdown just because we cannot ping it?

While looking at Asias patch I thought that  if node is DOWN without a clean shutdown, it's get_gossip_status would be UNKNOWN - but looking at the code I am wrong.

Now I tihnk the patch should be discarded, we want to distinguish between clean and unclean shutdown going forward, and the patch is blurring this distinction.

**Comment by kbr-scylla** [comment]
> And with email if you have a decent UA you can mark important emails or move them to the special mail box . With gmail you can label them.

With GitHub project if a bus hit me then someone can simply take over the project and continue from there. Easier than taking over my personal mail box configuration.

**Comment by mykaul** [comment]
> > And with email if you have a decent UA you can mark important emails or move them to the special mail box . With gmail you can label them.
> 
> With GitHub project if a bus hit me then someone can simply take over the project and continue from there. Easier than taking over my personal mail box configuration.

If you win the lottery and retire to an Island of your choice in the Carribeans. We don't get rid of people by accidents.

**Comment by gleb-cloudius** [comment]
> > And with email if you have a decent UA you can mark important emails or move them to the special mail box . With gmail you can label them.
> 
> With GitHub project if a bus hit me then someone can simply take over the project and continue from there. Easier than taking over my personal mail box configuration.

You are not discussing things with yourself (hopefully). If a bus hits you the discussion still exist on the mailing list and can be continued. Github issues should not be someones personal diary where his thoughts about the project are kept in case of a sudden demise :)

**Comment by gleb-cloudius** [comment]
> > > @kbr-scylla afaiu @asias patch it gets rid of the enum value but the shutdown state itself can be inferred from NORMAL status + DOWN gossiper state.
> > 
> > 
> > Down state is a local decision. How can we infer that a node was shutdown just because we cannot ping it?
> 
> While looking at Asias patch I thought that if node is DOWN without a clean shutdown, it's get_gossip_status would be UNKNOWN - but looking at the code I am wrong.
> 
> Now I tihnk the patch should be discarded, we want to distinguish between clean and unclean shutdown going forward, and the patch is blurring this distinction.

But what @kbr-scylla says is that it may be that original purpose of shutdown state is not there any more.

**Comment by gleb-cloudius** [comment]
> Actually reopening, I jumped to conclusions too quickly.
> 
> > If Z has a higher gossip version for X than Y has for X, Z will initiate a gossip with Y and Y will mark X alive again.
> 
> This is no longer true -- our failure detector no longer works like that. To mark X alive again, Y now has to contact X directly, which it won't be able to.

But it looks like we still need the sate for:

>   Maybe it's for nodes that did not manage to receive RPC, but we still want them to notice the graceful shutdown fast (faster than failure detector's 20 seconds)?

no?

**Comment by kostja** [comment]
We know shutdown is broken because of https://github.com/scylladb/scylladb/issues/15899. And because of this issue we know we will need to fix it. So either way we need shutdown status. I think this issue can be closed and further discussion can continue in scope of https://github.com/scylladb/scylladb/issues/15899
