### ISSUE TITLE
sstable_compaction_test doesn't complete in debug mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18564]
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/7609/consoleFull

https://scratch.scylladb.com/testlog/x86_64/debug/boost.sstable_compaction_test.max_ongoing_compaction_test.1.log

**Comment by dani-tweig** [comment]
@michoecho , any findings from your analysis? (after your computer worked so hard to get you the file :) )

**Comment by michoecho** [comment]
> @michoecho , any findings from your analysis? (after your computer worked so hard to get you the file :) )

No, I didn't analyze it at all. I only took a glance.
