### ISSUE TITLE
Adjust current documentation of Cluster Management Procedures with Tablet changes

### ISSUE THREAD

**Issue by dani-tweig** [scylladb/scylladb#18595]
The page https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/index.html holds Cluster Management Operations, and some will need to be updated due to the Tablet feature.

The following operations need to be updated:
[Remove a Data-Center from a ScyllaDB Cluster](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/decommissioning-data-center.html)
[Upscale a Cluster](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/scale-up-cluster.html) - not sure this scenario is supported.
[Adding a New Data-Center Into an Existing ScyllaDB Cluster - Out Scale](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.html)
[Remove a Node from a ScyllaDB Cluster - Down Scale](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/remove-node.html) - RF restriction. We cannot go lower than the RF. If we do want it we first need to reduce the RF.
[Repair Based Node Operations (RBNO)](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/repair-based-node-operation.html)

**Comment by bhalevy** [comment]
Cc @annastuchlik @tgrabiec

**Comment by bhalevy** [comment]
@xemul can you please take:
- [Adding a New Data-Center Into an Existing ScyllaDB Cluster - Out Scale](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.html)
- [Remove a Data-Center from a ScyllaDB Cluster](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/decommissioning-data-center.html)

**Comment by bhalevy** [comment]
@tgrabiec please look into:
- [Upscale a Cluster](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/scale-up-cluster.html) - not sure this scenario is supported.
  - even if we don't reshard on restart in 6.0 we should document that.
  - I expect tablet load balancer to kick in later and maybe trigger split and migrate tablet replicas across shards - that needs to be documented as well.
- [Remove a Node from a ScyllaDB Cluster - Down Scale](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/remove-node.html) - RF restriction. We cannot go lower than the RF. If we do want it we first need to reduce the RF.
- [Repair Based Node Operations (RBNO)](https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/repair-based-node-operation.html)
  - Let's document the general differences between tablets-based node operations vs. legacy node-ops (I don't think consistent-topology-changes vs. gossip-based topology changes make a difference with that regards)

**Comment by tzach** [comment]
https://docs.google.com/document/d/1ZA_bVIQQXaafpAWZYs7gzQ4OxI8INJIP7TFuWfhkrQM/edit#heading=h.h663h81105

**Comment by swasik** [comment]
@annastuchlik could you take a look who should be the assignee of this task? Is it you or one of the people mentioned by Dani (Tomek and Pavel)?

**Comment by swasik** [comment]
That is great, I will close both of them! Thanks for update and completing the work on documentation for tablets.
