### ISSUE TITLE
service::raft_operation_timeout_error in distributed_queries_test.TestDistributedAggregations.test_distributed_count_all

### ISSUE THREAD

**Issue by Deexie** [scylladb/scylladb#18602]
```
WARN  2024-05-08 22:57:04,563 [shard 0:strm] raft_group_registry - group [df9309c1-0d8d-11ef-9254-d149bedebcdf] raft operation [read_barrier] timed out, there is no raft quorum, total voters count 3, alive voters count 1, dead voters [127.0.54.2,127.0.54.3]; timeout requested at [service/storage_service.cc(1304:91) `future<> service::storage_service::update_topology_with_local_metadata(raft::server &)`], original error raft::request_aborted (Request is aborted by a caller)
```
```
ERROR 2024-05-08 22:57:07,588 [shard 0:main] init - Startup failed: service::raft_operation_timeout_error (group [df9309c1-0d8d-11ef-9254-d149bedebcdf] raft operation [read_barrier] timed out, there is no raft quorum, total voters count 3, alive voters count 1, dead voters [127.0.54.2,127.0.54.3])
```
Related jenkins files:
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1459/testReport/junit/distributed_queries_test/TestDistributedAggregations/FullDtest___full_split006___test_distributed_count_all/

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1459/artifact/logs-full.release.006/1715209027833_distributed_queries_test.py%3A%3ATestDistributedAggregations%3A%3Atest_distributed_count_all/node1.log

**Comment by kbr-scylla** [comment]
Logs gone, closing.

(Next time when opening an issue, please assign it to someone, otherwise nobody will look at it other than by accident)
