### ISSUE TITLE
Need to add more metrics to the per-table-per-instance reporting

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#18642]
The following metrics are part of the dashboard, so they should be enabled per-instance by default:
cache_hit_rate
latency
live_disk_space

**Comment by amnonh** [comment]
@mykaul it would be nice if it can make it to 6.0, I'm testing a patch now, it should be backported to 2024.1

**Comment by mykaul** [comment]
If the PR is merged before 6.0 branches, it'll be there.

**Comment by tzach** [comment]
@amnonh are these metrics reflected in the Tablet dashbard?

**Comment by amnonh** [comment]
In the table dashboard, there is no tablet dashboard
