### ISSUE TITLE
doc: update Tablet information in the CREATE KEYSPACE section

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#18670]
As tablets are configured per keyspace, the following section needs to be updated:
https://opensource.docs.scylladb.com/master/cql/ddl.html#the-tablets-property-experimental

This issue is a release blocker. Tablets are no longer experimental in 6.0.

**Comment by bhalevy** [comment]
Reassigned to @xemul to balance the load.
Please review the documentation and see what exactly needs to change.
