### ISSUE TITLE
Doc: install optional JMX service

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#18687]
https://github.com/scylladb/scylladb/issues/18472 remove JMX server from the default install.
If one wants to continue using the JMX server (not recommended!), they need to manually install it.
We need to document this.

**Comment by tzach** [comment]
Questions: 
- will upgrade from 5.4 to 6.0 remove the JMX package?
- When installing JMX, should one run it in a service , and/or a systemd slice?

**Comment by tzach** [comment]
@yaronkaikov please advise

**Comment by mykaul** [comment]
> Questions:
> 
> * will upgrade from 5.4 to 6.0 remove the JMX package?

I would disable the service, not remove the package.

> * When installing JMX, should one run it in a service , and/or a systemd slice?
