### ISSUE TITLE
Cache role and service-level lookups

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#18738]
This issue is a spin-off from issue #17089. In that issue, an Alternator user noticed that Alternator requests are slowed down when authentication is used, because as soon as an authenticated user name is available in the query, we use this username to call `client_state.maybe_update_per_service_level_params()`. This function looks up in a system table the user's roles (`role_manager.query_granted()`) and then looks up in another system table the roles' service levels (`_sl_controller->find_service_level()`). These two lookups are slow and the request of this issue is to cache them.

The same slow `client_state.maybe_update_per_service_level_params()` is also used in CQL, but there it is called just once when making a connection - and not once per request - so its performance impact is less noticeable in CQL. However, it may still contribute to the "Monday morning effect"- where when the load suddenly increases (e.g., on Monday morning when everyone returns to work) a lot of new connections are opened so the slowness of opening a new connection is suddenly noticeable.

Note that these two system-table lookups are (relatively) slow even if the system tables they read are already cached, because the entire CQL machinery is invoked twice on every Alternator query. Consider that also the user's query itself can be fast (namely a read that can be served from cache), so adding two more CQL queries to it can have a noticeable performance impact.

Today, `auth::get_permissions()` caches what it reads from its system tables (this caching is configured by the parameters `permissions_validity_in_ms`, `permissions_update_interval_in_ms`, `permissions_cache_max_entries`). Perhaps we should do exactly the same for role lookups and service-level lookups.

**Comment by kostja** [comment]
Roles and service levels are different teams  and  also split between community/enterprise branches. Best to avoid having a single ticket. Besides, it would be a duplicate of e.g. https://github.com/scylladb/scylladb/issues/7397 when it comes to roles. there is a bunch of similar bugs. @nuivall presented at the dev summit that we will be moving to the full cache of auth information on every shard, and a change from pull to push model (e.g. cache the record when it is changed, not when it is used). I think the issue should be closed.

**Comment by nyh** [comment]
> Roles and service levels are different teams and also split between community/enterprise branches. Best to avoid having a single ticket.

‎This issue is about a specific problem - the slowness of `client_state.maybe_update_per_service_level_params()` called in Alternator before each and every request (and in CQL less often - just when creating a connection) - which affects open-source (there's nothing Enterprise-specific in this issue). Although service levels are more powerful and more useful in the Enterprise branch, the concept of service levels already exists in open-source, and the performance hit is there too. The user who was hit with this bug was using the open-source version.

So there is no reason to split this issue.

> Besides, it would be a duplicate of e.g. #7397 when it comes to roles.

That issue is about the size of the cache, and seems to me completely unrelated to this issue which is about the limited size of the cache, which `maybe_update_per_service_level_params()` doesn't even use.

> there is a bunch of similar bugs. @nuivall presented at the dev summit that we will be moving to the full cache of auth information on every shard, and a change from pull to push model (e.g. cache the record when it is changed, not when it is used). I think the issue should be closed.

A issue shouldn't be closed just because someone said he was _going to_ fix a problem - an issue should remain open until it is actually fixed. Unless you are saying we already have another issue open about the same problem - but so far I didn't see where is that other issue.

**Comment by nuivall** [comment]
> maybe_update_per_service_level_params() doesn't even use this cache

but it should, and that's what connects those issues. It may be a duplicate in the sense that one PR will fix all of those issues (but in a different way than reporters originally expected).

anyway it's fine to keep it open in the cache epic

**Comment by nyh** [comment]
In https://github.com/scylladb/scylladb/issues/17089#issuecomment-2370940798 @piodul said:

> After https://github.com/scylladb/scylladb/pull/19085 we no longer query from the system tables, the service levels are cached in an `std::unordered_map`. It should be much faster than querying system tables, even if their contents are in the cache.

If this is true, then does it mean this issue was solved and we forgot to "Fixes" it?

**Comment by piodul** [comment]
@nyh we precompute both lookups in our cache. Our cache maps role name -> effective service level params directly, no need to do more lookups - you can take a look at `maybe_update_per_service_level_params` to see for yourself. We recalculate this cache every time something changes in service levels or in auth.

We didn't have to implement any kind of cache for auth to solve this particular problem. I personally think the problem is indeed solved, but the issue title is "Cache role and service-level lookups", so I'll leave it up to you whether to close it or not as AFAIK we don't have this kind of cache for auth itself.

**Comment by nyh** [comment]
> @nyh we precompute both lookups in our cache. Our cache maps role name -> effective service level params directly, no need to do more lookups - you can take a look at `maybe_update_per_service_level_params` to see for yourself. We recalculate this cache every time something changes in service levels or in auth.

Good. So you are saying that `client_state.maybe_update_per_service_level_params()` is no longer slow because it caches its previous decisions for the same role **name**. Nice. 

> We didn't have to implement any kind of cache for auth to solve this particular problem. I personally think the problem is indeed solved, but the issue title is "Cache role and service-level lookups", so I'll leave it up to you whether to close it or not as AFAIK we don't have this kind of cache for auth itself.

Yes, it seems instead of caching the two lookups separately, you cached the result of running both. I hope the cache invalidation part was done correctly (because the two parts may independently become stale).

I'll close this issue now, but I feel a bit awkward closing it without doing any testing myself. The developer of the patch should have done the testing, see (with printouts, metrics, or benchmark or whatever) that indeed the slow lookups are gone, and mark this issue Fixed.

**Comment by nyh** [comment]
Please note that the declared fix for this issue, https://github.com/scylladb/scylladb/pull/19085, has NOT been backported. That PR seems to include much more than just caching, so I don't know how easy it would be to backport.
