### ISSUE TITLE
auth on raft: safe backup and restore

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#18750]
Auth is going to be managed via raft in 6.0.

As we know from the case of schema-on-raft (https://github.com/scylladb/scylladb/issues/16349), restoring data via the usual restore procedure ([link](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html)) to a raft-managed table is prone to issues if different sstables are uploaded to different nodes. It can happen for example if one backs up the same table on two nodes at a different point in time and the contents of the table changes. For raft tables, there is no manual or automatic (like in the case of schema) mechanism of repair, so they might be inconsistent until a manual intervention happens.

In case of schema, we decided to go with the approach of using a CQL command DESCRIBE SCHEMA WITH INTERNALS which returns a list of CQL statements that can be used to reconstruct the schema. We can consider doing the same for auth: introduce a DESCRIBE AUTH command which returns a sequence of CREATE ROLEs, GRANTs, etc.

Considerations:

- Permissions give access to resources defined by schema (keyspaces, tables) so auth state is linked with schema. It should be possible to atomically dump both schema information (DESCRIBE SCHEMA WITH INTERNALS) and auth state.
- Like in the case of DESCRIBE SCHEMA __WITH INTERNALS__, we need CQL commands that will allow to recreate auth resources as they were before. For example, this would require dumping hashed passwords.
- Some permissions are granted automatically to the creator of the resource, and we should account for that (perhaps restoring schema with authorization completely disabled does the trick?).

**Comment by nuivall** [comment]
> Considerations:
> 
> * Permissions give access to resources defined by schema (keyspaces, tables) so auth state is linked with schema. It should be possible to atomically dump both schema information (DESCRIBE SCHEMA WITH INTERNALS) and auth state.

So it's doable if it's a single statement but how to do it for 2 separate statements? Maybe it should be part of describe schema?

> * Like in the case of DESCRIBE SCHEMA **WITH INTERNALS**, we need CQL commands that will allow to recreate auth resources as they were before. For example, this would require dumping hashed passwords.

This is problematic, we either need some nasty workaround or some new feature because:
- current statement require password not its hash
- insert statements are obviously not hooked into raft so they won't work

But the way the hack could be useful also for alternator as password there is used as a secret, so no need to be hashed.

> * Some permissions are granted automatically to the creator of the resource, and we should account for that (perhaps restoring schema with authorization completely disabled does the trick?).

 We will express auto-grants as normal grants, but yes we should somehow disable auto-grand during restore. But disabling auth in the config seems incontinent. How difficult would be adding something similar to USE statement, something which would disable auto-grant for the session?

**Comment by piodul** [comment]
> > Considerations:
> > 
> > * Permissions give access to resources defined by schema (keyspaces, tables) so auth state is linked with schema. It should be possible to atomically dump both schema information (DESCRIBE SCHEMA WITH INTERNALS) and auth state.
> 
> So it's doable if it's a single statement but how to do it for 2 separate statements? Maybe it should be part of describe schema?

Perhaps we could have a single DESCRIBE METADATA or something like that to cover schema, auth and service levels.

> 
> > * Like in the case of DESCRIBE SCHEMA **WITH INTERNALS**, we need CQL commands that will allow to recreate auth resources as they were before. For example, this would require dumping hashed passwords.
> 
> This is problematic, we either need some nasty workaround or some new feature because:
> 
> * current statement require password not its hash
> * insert statements are obviously not hooked into raft so they won't work
> 
> But the way the hack could be useful also for alternator as password there is used as a secret, so no need to be hashed.

We already have some additions to the DDL statements (taken from Cassandra) which only make sense in context of schema restore, e.g. ALTER TABLE DROP COLUMN USING TIMESTAMP.

> 
> > * Some permissions are granted automatically to the creator of the resource, and we should account for that (perhaps restoring schema with authorization completely disabled does the trick?).
> 
> We will express auto-grants as normal grants, but yes we should somehow disable auto-grand during restore. But disabling auth in the config seems incontinent. How difficult would be adding something similar to USE statement, something which would disable auto-grant for the session?

USE-like semantics are not ideal because it sets per-connection state and it requires some special handling from the driver (there is a special response to USE which drivers notice and re-send the statement on all connections).

An easy alternative, though, would be to create a superuser just for the duration of the restore who would create everything and grant all the necessary permissions to the right people, then it would be dropped. Unless there is something special about auto-granted permissions, it looks like this could work.

**Comment by nuivall** [comment]
> An easy alternative, though, would be to create a superuser just for the duration of the restore who would create everything and grant all the necessary permissions to the right people, then it would be dropped. Unless there is something special about auto-granted permissions, it looks like this could work.

Yes, sounds like an easy win. We'll need to create it in a separate transaction so that it's readable.

**Comment by mykaul** [comment]
@piodul - isn't this issue a blocker for 6.0?

**Comment by mykaul** [comment]
I hope describe for authv2 shouldn't be a big item to implement and is probably the better approach.

**Comment by kbr-scylla** [comment]
> so perhaps it would be possible to load backed up auth sstables from a single node to the first node in the new cluster and only then proceed with creating the remaining nodes

This should work with schema too, by the way.

**Comment by Michal-Leszczynski** [comment]
@mykaul @tzach I see that the milestone has been changed to 6.1.
Does it mean that we want to use the [workaround](https://github.com/scylladb/scylladb/issues/18750#issuecomment-2124712069) described by @piodul instead of DESC AUTH for 6.0?

**Comment by mykaul** [comment]
> @mykaul @tzach I see that the milestone has been changed to 6.1. Does it mean that we want to use the [workaround](https://github.com/scylladb/scylladb/issues/18750#issuecomment-2124712069) described by @piodul instead of DESC AUTH for 6.0?

It means it missed 6.0, and now we do not backup/restore auth. Let's continue on finishing the design for the describe and implementing it and see where we are at once we are done.

**Comment by Michal-Leszczynski** [comment]
> It means it missed 6.0, and now we do not backup/restore auth.

What do you mean by that? Right now SM does backup and restore `system_auth` tables and it will be impossible when those tables are managed by raft.

**Comment by mykaul** [comment]
> > It means it missed 6.0, and now we do not backup/restore auth.
> 
> What do you mean by that? Right now SM does backup and restore `system_auth` tables and it will be impossible when those tables are managed by raft.

This is exactly why we need to complete this issue. But it'll be past 6.0 regretfully.

**Comment by piodul** [comment]
@ptrsmrn @nuivall moving this to Core-Backend. We have expertise in implementing server-side DESCRIBE SCHEMA, so it makes sense for us to do it.

A design doc is pending, but I already asked @dawmd to start looking around.

**Comment by avikivity** [comment]
The maintenance socket has its own authentication, so it effectively bypasses any auth we're manipulating.

**Comment by mykaul** [comment]
This has missed 6.2 - pushed to 6.3.
