### ISSUE TITLE
New Node Joining(raft consensus) Stuck with Removed Nodes

### ISSUE THREAD

**Issue by vincentwenatsa** [scylladb/scylladb#18779]
Hi, I have recently upgraded a cluster of five 5.2.2 nodes to 5.4.6. Everything looks fine after upgrade. But the new 5.4.6 node cannot correctly join this cluster. It gets stuck at 

> May 21 02:03:26 ip-172-19-22-42 scylla[4783]:  [shard 3:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id 989641b4-f41a-421b-b4e4-79565
> 029b1de cannot be translated to an IP address.
> May 21 02:03:26 ip-172-19-22-42 scylla[4783]:  [shard 1:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id ca916f74-fd89-4a71-ad0c-60d50
> 50e31b0 cannot be translated to an IP address.
> May 21 02:03:26 ip-172-19-22-42 scylla[4783]:  [shard 2:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id f9169421-c8fa-4448-abc9-b7d66
> 100a87e cannot be translated to an IP address.
> May 21 02:03:26 ip-172-19-22-42 scylla[4783]:  [shard 2:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id 7ac9e7db-dbbd-404e-8388-f0233
> 998dba7 cannot be translated to an IP address.
> May 21 02:03:26 ip-172-19-22-42 scylla[4783]:  [shard 0:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id a2c1dc02-68d9-4c60-a19f-9853e
> a93a191 cannot be translated to an IP address.
> May 21 02:08:26 ip-172-19-22-42 scylla[4783]:  [shard 3:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id 989641b4-f41a-421b-b4e4-79565
> 029b1de cannot be translated to an IP address.
> May 21 02:08:26 ip-172-19-22-42 scylla[4783]:  [shard 1:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id ca916f74-fd89-4a71-ad0c-60d50
> 50e31b0 cannot be translated to an IP address.
> May 21 02:08:26 ip-172-19-22-42 scylla[4783]:  [shard 2:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id f9169421-c8fa-4448-abc9-b7d66
> 100a87e cannot be translated to an IP address.
> May 21 02:08:26 ip-172-19-22-42 scylla[4783]:  [shard 2:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id 7ac9e7db-dbbd-404e-8388-f0233
> 998dba7 cannot be translated to an IP address.
> May 21 02:08:26 ip-172-19-22-42 scylla[4783]:  [shard 0:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id a2c1dc02-68d9-4c60-a19f-9853e
> a93a191 cannot be translated to an IP address.

I confirmed that these nodes are not in the gossipinfo
<img width="661" alt="image" src="https://github.com/scylladb/scylladb/assets/108292376/43ac53ad-8d93-48f1-a9fb-53429daec2d5">

It seems that this new node's joining phase got stuck at trying to find out these non-existed removed nodes

*Installation details*
Scylla version (or git commit hash): Five 5.2.2 nodes, upgraded to 5.4.6, and a new node of 5.4.6 joining this cluster
Cluster size: 5 (+1) nodes i3en.xlarge EC2 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 22, ScyllaDB's EC2 AMI 5.4.6
<img width="1483" alt="image" src="https://github.com/scylladb/scylladb/assets/108292376/dc50e173-4124-4373-a437-69989627e68e">

**Comment by kbr-scylla** [comment]
Looks like Raft configuration contains some leftovers. You're saying these nodes were removed? Perhaps `removenode` did not manage to finish to the end.

You should be able to remove the leftovers using `removenode` as described in this procedure:
https://opensource.docs.scylladb.com/master/operating-scylla/procedures/cluster-management/handling-membership-change-failures.html#cleaning-up-after-change

**Comment by vincentwenatsa** [comment]
These nodes are node presented in either gossip or nodetool status, and `nodetool removenode` just failed. 
<img width="1491" alt="image" src="https://github.com/scylladb/scylladb/assets/108292376/fa1be46e-32a3-4dc9-9cc2-ab287df86674">

However, it seems the new node joined the cluster successfully after a very long time (but I still see `[shard 1:main] raft_group_registry - (rate limiting dropped 2998 similar messages) Raft server id 7ac9e7db-dbbd-404e-8388-f02
33998dba7 cannot be translated to an IP address.` errors in log).

**Comment by kbr-scylla** [comment]
> nodetool removenode just failed

Because you pasted the UUID partially: I think you copied it from the terminal, and only copied the part that was printed on the first line of the log message (but there's a second line which contains a suffix of the UUID)

> These nodes are not presented in neither gossip nor nodetool status

Sorry I posted wrong link to the documentation, `master` branch
Here's 5.4 doc:
https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/handling-membership-change-failures.html

It mentions querying `system.raft_state` table, which should show all of these host IDs which are not members of the cluster (don't appear in gossip/nodetool status)

**Comment by vincentwenatsa** [comment]
Thanks, removenode that seems to work.
