### ISSUE TITLE
docs: Issue on page Enable Authorization

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#18773]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-5.4/operating-scylla/security/enable-authorization

### Problem
Clearly, keeping the default username/password "cassandra"/"cassandra" is not recommended because it's a security risk.
But this document **also** emphasizes, twice, that using the default user cassandra/cassandra "may significantly impact performance" and creates "performance degradation." It's not explained why... What performance degradation? If this statement is really true, we should present a more convincing explanation why it is so. (If it's not true, then we should delete those statements.)

Datastax's document, https://docs.datastax.com/en/dse/6.8/securing/authorization-authentication/create-root-account.html, suggests that the performance problem with the default "cassandra" account is that:

> "Requests from the cassandra account, including login, use a consistency level of QUORUM. QUORUM may cause significant performance degradation in multiple datacenter environments. ... Requests from all other authenticated accounts have a consistency level of LOCAL_ONE. 

Looking at the Scylla code, I indeed found this logic in Scylla too:
```c++
static db::consistency_level consistency_for_role(std::string_view role_name) noexcept {
    if (role_name == meta::DEFAULT_SUPERUSER_NAME) {
        return db::consistency_level::QUORUM;
    }

    return db::consistency_level::LOCAL_ONE;
}
```
But it seems (please correct me if I'm wrong) that this function is only used for the consistency level when executing the internal queries to read or write the roles table (I don't know what is the rationale for this, by the way). Unless I'm missing something, I don't think it affects the user's real request, which uses the consistency level specified by the driver or application.  If my understanding of this is correct, then the warning in Datastax's document, and our mysteriously shortened version of it, are misleading.

Theoretically, if role lookups are not cached, the slower reads can hurt performance. But 1. role lookups are rare in CQL, they only happen in connection initialization; 2. they should be cached (#18738), and 3. if this is the real story about the "performance impact", it should be explicitly mentioned (so when we do fix #18738, we'll know this warning is no longer relevant).

CC @nuivall @avikivity 

###  Suggest a fix

**Comment by tzach** [comment]
https://github.com/scylladb/scylladb/issues/3163

**Comment by nuivall** [comment]
> hat performance degradation? If this statement is really true, we should present a more convincing explanation why it is so. (If it's not true, then we should delete those statements.)

That's obsolete, sent a doc patch.

**Comment by nyh** [comment]
‎Turns out that the page https://opensource.docs.scylladb.com/stable/operating-scylla/security/create-superuser.html also has a reference (and according to @nuivall obsolete) to the performance issue, although that other page is much clearer what this issue was about:

> During login, the credentials for the default superuser cassandra are read with a consistency level of QUORUM, whereas those for all other roles are read at LOCAL_ONE. QUORUM may significantly impact performance, especially in multi-datacenter deployments.
