### ISSUE TITLE
Disabling tablets using ALTER KEYSPACE should be forbidden

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18795]
Currently we allow setting the `tablets = {'enabled': false}` keyspace property using `ALTER KEYSPACE`, but other than storing it in the schema we do nothing with it.
Since we don't allow to migrate vnodes-based keyspace to tablets yet, we already do not allow it in ALTER KEYSPACE.
The same goes for disabling tablets for an existing keyspace that was created with tablets enabled.

**Comment by bhalevy** [comment]
@ptrsmrn this is orthogonal to the support of rf changes.  Enabling or disabling tablets for an existing keyspace should still be forbidden since it's not supported.

**Comment by ptrsmrn** [comment]
> @ptrsmrn this is orthogonal to the support of rf changes. Enabling or disabling tablets for an existing keyspace should still be forbidden since it's not supported.

@bhalevy I assumed it's already the case, please see https://github.com/scylladb/scylladb/pull/18772#discussion_r1617339932

**Comment by bhalevy** [comment]
> > @ptrsmrn this is orthogonal to the support of rf changes. Enabling or disabling tablets for an existing keyspace should still be forbidden since it's not supported.
> 
> @bhalevy I assumed it's already the case, please see [#18772 (comment)](https://github.com/scylladb/scylladb/pull/18772#discussion_r1617339932)

But you just closed this issue as "not planned" with no explanation whatsoever.

How would anyone know what you assumed and that closing as "not planned" actually means that the issue is already fixed.

Let's reference the patch/PR/cods that addresses this and also a test(s) that verifies it.

**Comment by bhalevy** [comment]
```
cqlsh> create keyspace tablets_ks with replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} and tablets = {'initial': 1};

Warnings :
Tables in this keyspace will be replicated using tablets, and will not support the CDC feature (issue #16317) and LWT may suffer from issue #5251 more often. If you want to use CDC or LWT, please drop this keyspace and re-create it without tablets, by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.

Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.

cqlsh> alter keyspace tablets_ks with  tablets = {'initial': 2};
cqlsh> alter keyspace tablets_ks with  tablets = {'enabled': false};
```
The last query should be rejected as disabling tablets is unimplemented.

Cc @xemul 

```
cqlsh> create keyspace vnodes_ks with replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} and tablets = {'enabled': false};

Warnings :
Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.

cqlsh> alter keyspace vnodes_ks with tablets = {'enabled': true};
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot alter replication strategy vnode/tablets flavor"
cqlsh> alter keyspace vnodes_ks with tablets = {'initial': 1};
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot alter replication strategy vnode/tablets flavor"
```

That's fine

**Comment by xemul** [comment]
Ah, that's because of

```c++
    std::optional<unsigned> initial_tablets = get_initial_tablets(*sc, old->initial_tablets().has_value());
    if (!initial_tablets) {
        initial_tablets = old->initial_tablets();
    }
...

    std::optional<unsigned> ret;

    auto it = tablets_options->find("enabled");
    if (it != tablets_options->end()) {
        auto enabled = it->second;
        tablets_options->erase(it);

        if (enabled == "true") {
            ret = 0; // even if 'initial' is not set, it'll start with auto-detection
        } else if (enabled == "false") {
            assert(!ret.has_value());
            return ret;
        } else {
            throw exceptions::configuration_exception(sstring("Tablets enabled value must be true or false; found: ") + enabled);
        }
    }
```

the `ret` is disengaged, so the upper code just inherits it from current meta

**Comment by ptrsmrn** [comment]
@bhalevy can we drop the `release_blocker` label, since the Issue's milestone is set to 6.1?

**Comment by mykaul** [comment]
> @bhalevy can we drop the `release_blocker` label, since the Issue's milestone is set to 6.1?

Actually - no. We'd like to make sure 6.1 isn't released with it. So let's fix it promptly.
