### ISSUE TITLE
docs: Issue on page Scylla Memory Usage

### ISSUE THREAD

**Issue by myagizmaktav** [scylladb/scylladb#18805]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-5.4/kb/memory-usage

### Problem
Its not clear.
###  Suggest a fix
I don't have too much traffic for db. 
I have 1 GB database how much will be enough to Scylladb?

**Comment by tzach** [comment]
More about ScyllaDB RAM requirements here.
https://opensource.docs.scylladb.com/stable/getting-started/system-requirements.html#memory-requirements

Closing this issue as there is no apparent issue we need to fix.
@myagizmaktav let's continue the disscusion on the forum as @mykaul suggested
