### ISSUE TITLE
Group 0 state machine queries are using `streaming` scheduling group

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#18863]
The `streaming` scheduling group is used for heavy, long running operations, like those done by repair.

Group 0 state machine is used for operations that should be quick -- for example, when we're doing a schema change, we want the cluster to quickly synchronize to learn about the new schema. The longer two nodes are out of sync (one still uses the previous schema version), the higher latency bumps we'll observe on the data path -- when the outdated node, acting as a replica, receives a query from the updated node, acting as a coordinator, the query will have to wait for schema to synchronize.

Through unpleasant experience we've learned that group 0 state machine is using the `streaming` scheduling group, and therefore it's using the same concurrency-limiting semaphores, so `group0_state_machine::apply` may get stuck waiting for a long-running repair operation to finish. Customer issue https://github.com/scylladb/scylla-enterprise/issues/3876 was caused by a deadlock in repair (https://github.com/scylladb/scylladb/issues/17591), with a side effect of group 0 getting stuck as well.

Some relevant comments from that thread, starting at https://github.com/scylladb/scylla-enterprise/issues/3876#issuecomment-1929242215:

> The streaming semaphore was meant to be used for repair and streaming only. The timeout repair uses when getting permits for this semaphore is 30min. There are a lot of repairs here, let's reduce the repair concurrency to <10.

> Also, it seems there are reads initiated by raft on this semaphore. These will now have to fight low priority repair reads and can get stuck behind them for a looooong time (remember, repairs use 30min timeout).

The reads initiated by Raft were `system.group0_history` reads, which are done by `group0_state_machine::apply` for doing `state_id` check.

> We pick semaphores based on the current SG. If the current SG is streaming, then the streaming semaphore is picked.
See https://github.com/scylladb/scylladb/blob/115ee4e1f528c69c6d011f7bbbb0e09783446912/replica/database.cc#L1374-L1396

> And its caller, get_reader_concurrency_semaphore().

>  Note that SGs cross node boundaries, as they are preserved across RPC calls.

> Note that each RPC VERB has a SG associated with it. Statement VERBS can have multiple "tenants", so they choose the SG to transmit based on the current SG. The other verbs have a fixed SG associated with them on both the sender and receiver side.

> Verbs are classified here: https://github.com/scylladb/scylladb/blob/a3d4131918e5d0862065fa5d0c86cba571b6af88/message/messaging_service.cc#L559-L656
> The ids assigned by the above, are mapped to scheduling groups here, taking tenants into consideration https://github.com/scylladb/scylladb/blob/a3d4131918e5d0862065fa5d0c86cba571b6af88/message/messaging_service.cc#L694-L714

The most likely reason that group 0 state machine runs inside `streaming` is:
```
            auto maintenance_scheduling_group = make_sched_group("streaming", "strm", 200);
...
            with_scheduling_group(maintenance_scheduling_group, [&] {
                return ss.local().join_cluster(sys_dist_ks, proxy, gossiper, service::start_hint_manager::yes);
            }).get();
```

group 0 is started from within `storage_service::join_cluster`.

---

What scheduling group should we put group 0 stuff in?

In https://github.com/scylladb/scylladb/pull/18715 a new SG was created for schema commitlog.

But it was suggested that we rename the `gossip` scheduling group and put schema commitlog there instead of having a separate SG --- and perhaps we could also put group 0 state machine there.

cc @denesb @avikivity @kostja @gleb-cloudius 

---

When we do this change, I think it should be backported to all releases running group 0, because all might suffer with group 0 getting stuck on streaming semaphore waiting for long running operations to finish.

**Comment by kbr-scylla** [comment]
Also copying from https://github.com/scylladb/scylladb/pull/18715#issuecomment-2122708407:

> Statement verbs support tenants -- it can switch between a predefined set of scheduling groups. Currently there is 2: statement and default (system). There is an open PR for a third: streaming.
> That said tenants are not free, they each have their own connection. So maybe the best solution is to move DDL verbs to the gossip connection. This cannot be done if the verbs is shared with other users.

**Comment by avikivity** [comment]
> When we do this change, I think it should be backported to all releases running group 0, because all might suffer with group 0 getting stuck on streaming semaphore waiting for long running operations to finish.

Such deep changes are not backported lightly. They can be backported if we prove a problem and extensively test the solution, but not backport it as soon as it promotes.

**Comment by kbr-scylla** [comment]
> Such deep changes are not backported lightly. 

I'm not sure I'd call this a deep change, and definitely not compared to the huge tablets PRs which we are backporting to 6.0 like crazy last-minute before the release.
