### ISSUE TITLE
Bogus warning about SimpleStrategy when a keyspace is created with NetworkTopologyStrategy

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18874]
Seen when pre-created the `keyspace1` keyspace for cassandra-stress.

```
INFO  2024-05-26 16:46:16,885 [shard 0:stmt] migration_manager - Create new Keyspace: KSMetaData{name=keyspace1, strategyClass=org.apache.cassandra.locator.NetworkTopologyStrategy, strategyOptions={"datacenter1": "1"}, cfMetaData={}, durable_writes=true, userTypes=org.apache.cassandra.config.UTMetaData@0x600004d585a8}
INFO  2024-05-26 16:46:16,886 [shard 0:strm] schema_tables - Creating keyspace keyspace1
INFO  2024-05-26 16:46:16,887 [shard 0:strm] migration_manager - Gossiping my schema version 533c55d0-1b66-11ef-27f8-70191da02de7
INFO  2024-05-26 16:46:16,887 [shard 0:strm] schema_tables - Schema version changed to 533c55d0-1b66-11ef-27f8-70191da02de7
WARN  2024-05-26 16:46:16,888 [shard 0:stmt] create_keyspace - Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
WARN  2024-05-26 16:46:18,299 [shard 0:stmt] create_keyspace - org.apache.cassandra.locator.SimpleStrategy replication class is not recommended, but was used for keyspace keyspace1. You may suppress this warning by delisting org.apache.cassandra.locator.SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.
WARN  2024-05-26 16:46:18,299 [shard 0:stmt] create_keyspace - Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
INFO  2024-05-26 16:46:18,304 [shard 0:stmt] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x600004c27880[cfId=5414d400-1b66-11ef-807e-396e0d1927c8,ksName==keyspace1,cfName=standard1,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.BytesType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.BytesType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=C0, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C1, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C2, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C3, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C4, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=5414d401-1b66-11ef-807e-396e0d1927c8,droppedColumns={},collections={},indices={}]
```

The migration_manager message clearly shows that the keyspace is created with `strategyClass=org.apache.cassandra.locator.NetworkTopologyStrategy`
But there's a bogus warning right after that:
```
create_keyspace - org.apache.cassandra.locator.SimpleStrategy replication class is not recommended, but was used for keyspace keyspace1
```

**Comment by nyh** [comment]
Strange, I was pretty sure we tested all these guardrail cases thoroughly in `test/cql-pytest/test_guardrail_replication_strategy.py`: That SimpleStrategy generates a warning, that NetworkTopologyStrategy doesn't, etc. What did we miss?

**Comment by nyh** [comment]
CC @ptrsmrn

**Comment by bhalevy** [comment]
Hmm, the context is a dtest that invokes cassandra-stress, and to enable tablets for it, it creates the `keyspace1` in advance of executing stress, so maybe the second warning is due to cassandra-stress attempt to create the same keyspace (`keyspace1`) with SimpleStrategy - and hopefully failing since the keyspace already exists, but the validation logic happens before checking if the keyspace already exists.

**Comment by nyh** [comment]
> Hmm, the context is a dtest that invokes cassandra-stress, and to enable tablets for it, it creates the `keyspace1` in advance of executing stress, so maybe the second warning is due to cassandra-stress attempt to create the same keyspace (`keyspace1`) with SimpleStrategy - and hopefully failing since the keyspace already exists, but the validation logic happens before checking if the keyspace already exists.

Makes sense. In such a case, I don't even know what is the right thing to do. I'm not sure it's wrong to produce warning in this case. Maybe it's not bogus at all, and this issue should be closed? It does make sense that an operation checks the validity of all its parameters before actually trying to invoke the operation and realizing there's nothing to do.

**Comment by bhalevy** [comment]
Closing.  I agree we don't have to fix this.
BTW, I wonder when we're going to reject SimpleStrategy altogether.

**Comment by ptrsmrn** [comment]
> Hmm, the context is a dtest that invokes cassandra-stress, and to enable tablets for it, it creates the `keyspace1` in advance of executing stress, so maybe the second warning is due to cassandra-stress attempt to create the same keyspace (`keyspace1`) with SimpleStrategy - and hopefully failing since the keyspace already exists, but the validation logic happens before checking if the keyspace already exists.

We won't get a 2nd guardrails warning when a KS with a name that is already uesd by other KS is being created (6.0 OSS):
```
cqlsh> CREATE KEYSPACE simple WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

Warnings :
SimpleStrategy replication class is not recommended, but was used for keyspace simple. You may suppress this warning by delisting SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.

Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.

cqlsh> CREATE KEYSPACE simple WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
AlreadyExists: Keyspace 'simple' already exists
cqlsh> 
```
The simplest explanation why this warning is printed is that there is some KS with SimpleStrategy created, be it by the c-s or scylla internally.

**Comment by ptrsmrn** [comment]
> Closing. I agree we don't have to fix this. BTW, I wonder when we're going to reject SimpleStrategy altogether.

It's discouraged by guardrails already, and, to the best of my knowledge, will stick with us forever (like anything our clients could be using, which, when removed, could cause to break their code/scripts).

**Comment by bhalevy** [comment]
> > Closing. I agree we don't have to fix this. BTW, I wonder when we're going to reject SimpleStrategy altogether.
> 
> It's discouraged by guardrails already, and, to the best of my knowledge, will stick with us forever (like anything our clients could be using, which, when removed, could cause to break their code/scripts).

We don't and won't support SimpleStrategy with tablets so apps that use it would have to be adapted to either disable tablets (in the midterm.  vnode support will go away to), or move to NetworkTopologyStrategy.

Also, in the cloud, with elastic clusters we will take this choice away altogether and the keyspace topology will be determined by some policy set out-of-band rather than in create/alter keyspace (`replication = {'class': 'auto'}` or something like that)
