### ISSUE TITLE
docs: in case of majority loss, restore-from-backup is the only remaining option.

### ISSUE THREAD

**Issue by dani-tweig** [scylladb/scylladb#18895]
Documentation needed for the 6.0 release. Related to this issue: https://github.com/scylladb/scylladb/issues/17705

@kbr- can you please add the details?

**Comment by tzach** [comment]
> @kbr-scylla Is it sufficient to say that the[ manual recovery procedure](https://opensource.docs.scylladb.com/stable/architecture/raft.html#raft-manual-recovery-procedure) doesn't work if tablets are enabled on a keyspace and you should restore from backup in such a case?

It makes sense to me, and will require minimal updates once the issue is fixed
