### ISSUE TITLE
topology_experimental_raft/test_tablets is flaky

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#18896]
caught in CI with repeat=100, not able to reproduce it locally so far.

- test_tablets.test_topology_changes

this is https://github.com/scylladb/scylladb/issues/18904

- test_tablets.test_table_dropped_during_streaming 

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/debug/topology_experimental_raft.test_tablets.82.log
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/debug/scylla-7860.log
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/debug/scylla-7868.log

- test_tablets.test_tablet_split

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/dev/topology_experimental_raft.test_tablets.16.log
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/dev/scylla-7874.log
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/dev/scylla-7878.log

this seems an external issue when tearing down the test, causing reconnection storm (may be https://github.com/scylladb/scylladb/issues/15356)

```
15:07:29.261 DEBUG> Sending options message heartbeat on idle connection (140636003666256) 127.107.220.3:9042
15:07:29.262 DEBUG> Sending options message heartbeat on idle connection (140636022678288) 127.107.220.3:9042
15:07:29.262 DEBUG> Sending options message heartbeat on idle connection (140636022443856) 127.107.220.17:9042
```

- test_tablets.test_tablet_metadata_propagates_with_schema_changes_in_snapshot_mode
	
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/dev/topology_experimental_raft.test_tablets.17.log
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/dev/scylla-7875.log
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/dev/scylla-7876.log
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9204/artifact/testlog/x86_64/dev/scylla-7877.log

```
        manager.driver_close()
>       await manager.server_start(s0, wait_others=2)
```

**Comment by tgrabiec** [comment]
@raphaelsc These seem to be independent failures/issues, please split.

**Comment by mykaul** [comment]
I'm closing this, assuming we have specific items for them. If not - please re-open and split.
