### ISSUE TITLE
Seamless transition to inter-node encryption

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18903]
Currently, transitioning from `internode_encryption="none"` to any other mode (`all`, `dc`, or `,rack`)
is painful, since the procedure requires rolling restart and nodes that would like to start encrypting their internode communication need their peers to listen on the ssl port already.

To achieve that, the proposal is to always listen on `ssl_storage_port` is it's not set to 0, and the `certificate` and `keyfile` attributes are provided in `server_encryption_options` regardless of the `internode_encryption` mode.

With that, the procedure to enable internode encryption would be:
1. Set `internode_encryption="none"`, `certificate=<path to cert file>`, and `keyfile=<path to key file>` in scylla.yaml
2. Do cluster rolling restart (after which all nodes will listen on the `ssl_storage_port`, but will still use the unencrypted `storage_port` to send RPCs)
3. Change `internode_encryption` to one of `all`, `dc`, or `rack`
4. Do cluster rolling restart (after which all nodes will transition to the desired internode_encryption mode, will listen on the ssl_storage_port, and will listen also on `storage_port` by default for `dc` and `rack` modes, and will use the encrypted port depending on the mode and the peer node network topology locality.

Documentation also needs to be updated to reflect that procedure.

**Comment by bhalevy** [comment]
cc @gcarmin @tzach @annastuchlik

**Comment by bhalevy** [comment]
In addition we need a cql-pytest or a dtest for that, testing single dc and multi-dc/multi-rack setups.

**Comment by bhalevy** [comment]
> Currently, transitioning from `internode_encryption="none"` to any other mode (`all`, `dc`, or `,rack`) is painful, since the procedure requires rolling restart and nodes that would like to start encrypting their internode communication need their peers to listen on the ssl port already.
> 
> To achieve that, the proposal is to always listen on `ssl_storage_port` is it's not set to 0, and the `certificate` and `keyfile` attributes are provided in `server_encryption_options` regardless of the `internode_encryption` mode.
> 
> With that, the procedure to enable internode encryption would be:
> 
> 1. Set `internode_encryption="none"`, `certificate=<path to cert file>`, and `keyfile=<path to key file>` in scylla.yaml
> 2. Do cluster rolling restart (after which all nodes will listen on the `ssl_storage_port`, but will still use the unencrypted `storage_port` to send RPCs)
> 3. Change `internode_encryption` to one of `all`, `dc`, or `rack`
> 4. Do cluster rolling restart (after which all nodes will transition to the desired internode_encryption mode, will listen on the ssl_storage_port, and will listen also on `storage_port` by default for `dc` and `rack` modes, and will use the encrypted port depending on the mode and the peer node network topology locality.
> 
> Documentation also needs to be updated to reflect that procedure.



> Currently, transitioning from `internode_encryption="none"` to any other mode (`all`, `dc`, or `,rack`) is painful, since the procedure requires rolling restart and nodes that would like to start encrypting their internode communication need their peers to listen on the ssl port already.
> 
> To achieve that, the proposal is to always listen on `ssl_storage_port` is it's not set to 0, and the `certificate` and `keyfile` attributes are provided in `server_encryption_options` regardless of the `internode_encryption` mode.
> 
> With that, the procedure to enable internode encryption would be:
> 
> 1. Set `internode_encryption="none"`, `certificate=<path to cert file>`, and `keyfile=<path to key file>` in scylla.yaml
> 2. Do cluster rolling restart (after which all nodes will listen on the `ssl_storage_port`, but will still use the unencrypted `storage_port` to send RPCs)
> 3. Change `internode_encryption` to one of `all`, `dc`, or `rack`
> 4. Do cluster rolling restart (after which all nodes will transition to the desired internode_encryption mode, will listen on the ssl_storage_port, and will listen also on `storage_port` by default for `dc` and `rack` modes, and will use the encrypted port depending on the mode and the peer node network topology locality.

Sorry, there's still an issue with this proposed procedure with `internode_encryption="all"` since it doesn't listen on the unecrypted `storage_port`, and the existing nodes will try to use it.

To solve this, we can either:
* have a cluster pseudo-feature so to stop listening on storage_port once all nodes support encrypted internode communication, or, in the spirit of step 1 above:
* let `internode_encryption` control only the send path, and let the listen path be controlled solely by the `storage_port` setup, so we continue to listen on the unencrypted `storage_port` also in with `internode_encryption="all"`, unless `storage_port==0`.  This way, during the transition it can be kept as the default (port 7000) or some other port, and then it can be disabled in another round of RR, if it is really required to not listen on it, to prevent inadvertent unencrypted communications after `internode_encryption="all"` has been deployed.

**Comment by bhalevy** [comment]
@dani-tweig can you please add a label for "internode communication" or "internode encryption"?

**Comment by tzach** [comment]
@bhalevy, can we simplify the process by *always* starting with inter-node encryption?
The user should still be able to update the setting with a rolling restart (or, better yet, no restart), but we won't allow non-encrypted communication.
Can this work without extra work for casual users?

**Comment by bhalevy** [comment]
> @bhalevy, can we simplify the process by _always_ starting with inter-node encryption? The user should still be able to update the setting with a rolling restart (or, better yet, no restart), but we won't allow non-encrypted communication. Can this work without extra work for casual users?

1. To enable encryption, the user has to provides the certificate and key, so it cannot be enabled by default out-of-the-box.  That said, if the cluster is restarted reom scratch, there should be no problem.
2. The above procedure, if separating the encryption mode to control the send path, vs. the storage_port/ssl_storage_port that would orthogonally control the listen path, is useful for seamless transition from any encryption mode to any other encryption mode.  And I think it's more intuitive and simpler to explain and document than the current semantics.  Data point: an issue was opened for 4 years and a dtest was disabled, and people asking me how to enable encryption seamlessly, where there is no clear documentation for it and nobody really knows and this should be done.
3. I wholeheartedly agree that the config should be live-updateable and no restarts should be required.  ai don't know if that's the case today.  We can certainly make that a requiremnt.

Cc @elcallio

**Comment by bhalevy** [comment]
Refs https://github.com/scylladb/scylla-dtest/pull/4342

**Comment by elcallio** [comment]
> * Change `internode_encryption` to one of `all`, `dc`, or `rack`
> 
> * Do cluster rolling restart (after which all nodes will transition to the desired internode_encryption mode, will listen on the ssl_storage_port, and will listen also on `storage_port` by default for `dc` and `rack` modes, and will use the encrypted port depending on the mode and the peer node network topology locality.

Actually, I realized I forgot one thing during the discussion on this: If `internode_encryption` is set to any other than `none`, all _incoming_ connections are also required to use TLS if they are from outside the configured topology (rack, dc, all). Thus, while you could, in the rolling scenario, call _out_ from a node moving to encryption, all the rest of the cluster calls _into_ the updated node will fail (dropped). 

I guess one could add a mode "transitional", during which we accept unencrypted incoming RPC, but only do encrypted calls out.

The rolling upgrade would then be:

* For each node, set `ssl_listen_port` + certificate etc config (`server_encryption_options`). `internode_encryption=none` and restart.
* For each node set `internode_encryption=transitional` and restart
* For each node set `internode_encryption=all` and restart

Note than `internode_encryption`=`dc` or `rack` should be considered deprecated and insecure.

Comments?

**Comment by bhalevy** [comment]
> > * Change `internode_encryption` to one of `all`, `dc`, or `rack`
> > * Do cluster rolling restart (after which all nodes will transition to the desired internode_encryption mode, will listen on the ssl_storage_port, and will listen also on `storage_port` by default for `dc` and `rack` modes, and will use the encrypted port depending on the mode and the peer node network topology locality.
> 
> Actually, I realized I forgot one thing during the discussion on this: If `internode_encryption` is set to any other than `none`, all _incoming_ connections are also required to use TLS if they are from outside the configured topology (rack, dc, all). Thus, while you could, in the rolling scenario, call _out_ from a node moving to encryption, all the rest of the cluster calls _into_ the updated node will fail (dropped).
> 
> I guess one could add a mode "transitional", during which we accept unencrypted incoming RPC, but only do encrypted calls out.
> 
> The rolling upgrade would then be:
> 
> * For each node, set `ssl_listen_port` + certificate etc config (`server_encryption_options`). `internode_encryption=none` and restart.
> * For each node set `internode_encryption=transitional` and restart
> * For each node set `internode_encryption=all` and restart
> 
> Note than `internode_encryption`=`dc` or `rack` should be considered deprecated and insecure.
> 
> Comments?

I think that this `transitional` mode can work,
but the more I think about it, my conclusion that those modes entail too many side effects on the receive path.

IMO the simplest model would be point 2 in https://github.com/scylladb/scylladb/issues/18903#issuecomment-2133925121

I.e. letting the encryption mode control only encryprion on the send path, while letting storage_port and ssl_storage_port (plus a required certificate) control the listen parh, independently of the encryption mode.

This way, for enabling encryption from `none` mode, one needs to:
1. enable ssl_storage_port in the first pass,
2. then change the encryption mode to `all` in a second pass, and optionally,
3. disable the unencrypted storage_port in a third pass.

For transitioning back from `all` to `none`, execute the reverse:
1. enable the unencrypted storage_port in first pass
2. transition to `none` on all nodes in a second pass
3. optionally disable the encrypted ssl_storage_port in a third pass

**Comment by elcallio** [comment]
It is an optiona, but it would change the behaviour of existing installations which have `storage_port` set, opening up a vulnerable non-TLS port. 
Similarly, making storage_port default to 0 would break non-TLS usage.

An option is to consider storage_port default 0 IFF TLS options are set, and 7000 if not, but it might seem weird, especially since we ship a default scylla.yaml with the value (though commented) set to 7000.

The main benefit of the `transitional` mode is that it becomes 100% explicit that you are transitioning to TLS.

**Comment by mykaul** [comment]
@elcallio , what's the status of this issue?

**Comment by elcallio** [comment]
Should be good to go. The test is in CI now.
