### ISSUE TITLE
`raft::request_aborted` gives no information what exactly was aborted

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#18902]
I'm trying to understand the failure in https://github.com/scylladb/scylladb/issues/18821 but having a very hard time due to bad design of errors thrown in the Raft library which give no details about what happened.

For example I see this:
```
May 19 16:34:13 perf-latency-nemesis-ubuntu-db-node-35f17665-5 scylla[5418]:  [shard 0:strm] raft_group_registry - group [05892de0-15a8-11ef-ac9e-f1748327176a] raft operation [add_entry] timed out; timeout requested at [service/storage_service.cc(3513:113) `future<> service::storage_service::raft_decommission()`], original error raft::request_aborted (Request is aborted by a caller)
```

`add_entry` call has timed out.

However, later in the logs I see evidence that the entry actually got added -- this entry added a decommission request for this node, and a minute later, logs show that topology coordinator picked up the request and the node started getting decommissioned.

So what I'm interested in is **in what stage of `add_entry` call the timeout happened**?
- was it when we were waiting for response to the RPC that sends entry to the leader? -- this could indicate some transient network problem
- or was it when we were waiting for the applier fiber to reach this index? -- this could indicate that state_machine::apply was slow, perhaps it was stuck on some earlier entry, that's why this one timed out

But of course I don't know, because when the timeout triggers an abort source, we get a generic
`original error raft::request_aborted (Request is aborted by a caller)`

I hate this. Why can't we design better errors?

`request_aborted` should include information about where the error was thrown from.

cc @scylladb/raft

**Comment by kbr-scylla** [comment]
For example
```cpp
future<> server_impl::wait_for_entry(entry_id eid, wait_type type, seastar::abort_source* as) {
...
    if (as) {
        it->second.abort = as->subscribe([it = it, &container] () noexcept {
            it->second.done.set_exception(request_aborted());
            container.erase(it);
        });
        assert(it->second.abort);
    }
```

This could be

```cpp
            it->second.done.set_exception(request_aborted(format("Timed out when waiting for entry with idx {}, term {}", ...));
```

and so on.

**Comment by bhalevy** [comment]
Also, we see this error during shutdown, causing dtests to fail sporadically.
Does it have to be printed at all during shutdown?
`request_aborted` is expected during shutdown when abort is requested by the abort_source, so can't we just skip it?

For example:
https://jenkins.scylladb.com/job/scylla-master/job/tablets/job/dtest-release-with-tablets/20/artifact/logs-full.release.002/1719614135982_materialized_views_test.py%3A%3ATestMaterializedViews%3A%3Atest_mv_sync_after_remove_add_node/node2.log
```
INFO  2024-06-28 22:35:24,500 [shard 0:main] compaction_manager - Asked to stop
INFO  2024-06-28 22:35:24,500 [shard 0:main] view_update_generator - Terminating background fiber
INFO  2024-06-28 22:35:24,500 [shard 0:main] service_level_controller - update_from_distributed_data: configuration polling loop aborted
INFO  2024-06-28 22:35:24,500 [shard 0:main] init - Signal received; shutting down
INFO  2024-06-28 22:35:24,500 [shard 0:main] init - Shutting down thrift controller API
INFO  2024-06-28 22:35:24,500 [shard 0:main] compaction_manager - Stopped
INFO  2024-06-28 22:35:24,500 [shard 0:strm] view_update_generator - leaving 0 unstaged sstables unprocessed
INFO  2024-06-28 22:35:24,500 [shard 1:main] compaction_manager - Asked to stop
INFO  2024-06-28 22:35:24,500 [shard 1:main] view_update_generator - Terminating background fiber
INFO  2024-06-28 22:35:24,500 [shard 1:main] compaction_manager - Stopped
INFO  2024-06-28 22:35:24,500 [shard 1:strm] view_update_generator - leaving 0 unstaged sstables unprocessed
WARN  2024-06-28 22:35:24,500 [shard 0:strm] gossip - failure_detector_loop: Got error in the loop, live_nodes={127.0.15.5, 127.0.15.3, 127.0.15.1}: seastar::sleep_aborted (Sleep is aborted)
INFO  2024-06-28 22:35:24,500 [shard 0:strm] gossip - failure_detector_loop: Finished main loop
INFO  2024-06-28 22:35:24,500 [shard 0:main] init - Shutting down thrift controller API was successful
INFO  2024-06-28 22:35:24,500 [shard 0:main] init - Shutting down transport controller API
INFO  2024-06-28 22:35:24,501 [shard 0:main] init - Shutting down transport controller API was successful
INFO  2024-06-28 22:35:24,501 [shard 0:main] init - Shutting down local storage
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Stop transport: starts
INFO  2024-06-28 22:35:24,501 [shard 0:main] migration_manager - stopping migration service
INFO  2024-06-28 22:35:24,501 [shard 1:main] migration_manager - stopping migration service
INFO  2024-06-28 22:35:24,501 [shard 0: gms] raft - [738e720d-c697-46ab-8b57-0e57f3d25e75] applier fiber stopped because state machine was aborted: abort requested
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Shutting down native transport server
WARN  2024-06-28 22:35:24,501 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
INFO  2024-06-28 22:35:24,501 [shard 0:main] cql_server_controller - CQL server stopped
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Shutting down native transport server was successful
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Shutting down alternator server
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Shutting down alternator server was successful
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Shutting down redis server
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Shutting down redis server was successful
INFO  2024-06-28 22:35:24,501 [shard 0:main] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2024-06-28 22:35:24,501 [shard 0:main] gossip - My status = NORMAL
INFO  2024-06-28 22:35:24,501 [shard 0:main] gossip - Announcing shutdown
WARN  2024-06-28 22:35:24,501 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
INFO  2024-06-28 22:35:24,501 [shard 0:main] gossip - Sending a GossipShutdown to 127.0.15.5 with generation 1719614093
INFO  2024-06-28 22:35:24,501 [shard 0:main] gossip - Sending a GossipShutdown to 127.0.15.3 with generation 1719614093
INFO  2024-06-28 22:35:24,501 [shard 0:main] gossip - Sending a GossipShutdown to 127.0.15.1 with generation 1719614093
WARN  2024-06-28 22:35:24,706 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
WARN  2024-06-28 22:35:24,734 [shard 0: gms] gossip - === Gossip round FAIL: seastar::abort_requested_exception (abort requested)
INFO  2024-06-28 22:35:24,734 [shard 0: gms] gossip - Gossip loop is not scheduled because it is disabled
INFO  2024-06-28 22:35:24,998 [shard 0: gms] rpc - client 127.0.15.1:51436 msg_id 3:  exception "gate closed" in no_wait handler ignored
INFO  2024-06-28 22:35:24,998 [shard 0: gms] rpc - client 127.0.15.1:51436 msg_id 4:  exception "gate closed" in no_wait handler ignored
INFO  2024-06-28 22:35:25,371 [shard 0: gms] rpc - client 127.0.15.3:65138 msg_id 2:  exception "gate closed" in no_wait handler ignored
INFO  2024-06-28 22:35:26,129 [shard 0: gms] rpc - client 127.0.15.5:58882 msg_id 2:  exception "gate closed" in no_wait handler ignored
INFO  2024-06-28 22:35:26,371 [shard 0: gms] rpc - client 127.0.15.3:65138 msg_id 4:  exception "gate closed" in no_wait handler ignored
INFO  2024-06-28 22:35:26,501 [shard 0:main] gossip - Disable and wait for gossip loop started
INFO  2024-06-28 22:35:26,501 [shard 0:main] gossip - Gossip is now stopped
INFO  2024-06-28 22:35:26,501 [shard 0:main] storage_service - Stop transport: stop_gossiping done
INFO  2024-06-28 22:35:26,501 [shard 0:main] messaging_service - Shutting down nontls server
INFO  2024-06-28 22:35:26,501 [shard 0:main] messaging_service - Shutting down tls server
INFO  2024-06-28 22:35:26,501 [shard 0:main] messaging_service - Shutting down tls server - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.4:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.4:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Shutting down nontls server
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Shutting down tls server
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Shutting down tls server - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:0
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.5:0
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:1
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:1
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.3:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:0
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.5:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:1 - Done
INFO  2024-06-28 22:35:26,502 [shard 0:main] messaging_service - Shutting down nontls server - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:1 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.3:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.5:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopping client for address: 127.0.15.1:0 - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Shutting down nontls server - Done
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 1:main] messaging_service - Stopped clients
INFO  2024-06-28 22:35:26,502 [shard 0:main] storage_service - Stop transport: shutdown messaging_service done
INFO  2024-06-28 22:35:26,502 [shard 0:main] storage_service - Stop transport: shutdown stream_manager done
INFO  2024-06-28 22:35:26,502 [shard 0:main] storage_service - Stop transport: done
INFO  2024-06-28 22:35:26,502 [shard 0:main] tracing - Asked to shut down
INFO  2024-06-28 22:35:26,502 [shard 0:main] tracing - Tracing is down
INFO  2024-06-28 22:35:26,502 [shard 1:main] tracing - Asked to shut down
INFO  2024-06-28 22:35:26,502 [shard 1:main] tracing - Tracing is down
INFO  2024-06-28 22:35:26,502 [shard 0:main] batchlog_manager - Asked to drain
INFO  2024-06-28 22:35:26,502 [shard 0:main] batchlog_manager - Drained
INFO  2024-06-28 22:35:26,502 [shard 1:main] batchlog_manager - Asked to drain
INFO  2024-06-28 22:35:26,502 [shard 1:main] batchlog_manager - Drained
INFO  2024-06-28 22:35:26,502 [shard 0:main] compaction_manager - Asked to drain
INFO  2024-06-28 22:35:26,502 [shard 0:main] compaction_manager - Drained
INFO  2024-06-28 22:35:26,502 [shard 1:main] compaction_manager - Asked to drain
INFO  2024-06-28 22:35:26,502 [shard 1:main] compaction_manager - Drained
INFO  2024-06-28 22:35:26,502 [shard 0:main] database - Flushing non-system tables
INFO  2024-06-28 22:35:26,503 [shard 1:main] database - Flushing non-system tables
INFO  2024-06-28 22:35:26,505 [shard 0:main] database - Flushed non-system tables
INFO  2024-06-28 22:35:26,508 [shard 1:main] database - Flushed non-system tables
INFO  2024-06-28 22:35:26,508 [shard 0:main] database - Flushing system tables
INFO  2024-06-28 22:35:26,508 [shard 1:main] database - Flushing system tables
INFO  2024-06-28 22:35:26,512 [shard 1:main] database - Flushed system tables
INFO  2024-06-28 22:35:26,529 [shard 0:main] database - Flushed system tables
INFO  2024-06-28 22:35:26,536 [shard 0:main] view - Draining view builder
INFO  2024-06-28 22:35:26,536 [shard 1:main] view - Draining view builder
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down local storage was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down view builder API
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down view builder API was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down hinted handoff API
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down hinted handoff API was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down view update backlog broker
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down view update backlog broker was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down cf cache hit rate calculator
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down cf cache hit rate calculator was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down load meter API
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down load meter API was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down load meter
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down load meter was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down batchlog manager
INFO  2024-06-28 22:35:26,536 [shard 0:main] batchlog_manager - Asked to stop
INFO  2024-06-28 22:35:26,536 [shard 0:main] batchlog_manager - Stopped
INFO  2024-06-28 22:35:26,536 [shard 1:main] batchlog_manager - Asked to stop
INFO  2024-06-28 22:35:26,536 [shard 1:main] batchlog_manager - Stopped
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down batchlog manager was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down service level controller subscription
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down service level controller subscription was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down authorization cache api
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down authorization cache api was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down auth service
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down auth service was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down tracing
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down tracing was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down group 0 usage in local storage
INFO  2024-06-28 22:35:26,536 [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
INFO  2024-06-28 22:35:26,536 [shard 0:strm] raft_topology - cleanup fiber aborted
ERROR 2024-06-28 22:35:26,536 [shard 0: gms] raft_topology - raft_topology_cmd failed with: raft::request_aborted (Request is aborted by a caller)
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down group 0 usage in local storage was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down storage service uninit address map
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down storage service uninit address map was successful
INFO  2024-06-28 22:35:26,536 [shard 0:main] init - Shutting down group 0 service
INFO  2024-06-28 22:35:26,537 [shard 0:main] init - Shutting down group 0 service was successful
```

**Comment by bhalevy** [comment]
Can this request_aborted error propagate to other nodes?
Maybe this explains https://github.com/scylladb/scylladb/issues/18959?

**Comment by gleb-cloudius** [comment]
> Also, we see this error during shutdown, causing dtests to fail sporadically. Does it have to be printed at all during shutdown? `request_aborted` is expected during shutdown when abort is requested by the abort_source, so can't we just skip it?

May we not with error level, but the same log has aborts from the gossiper (and entire log will probably have aborts from other subsystems) and you do not complain about those.

**Comment by bhalevy** [comment]
> > Also, we see this error during shutdown, causing dtests to fail sporadically. Does it have to be printed at all during shutdown? `request_aborted` is expected during shutdown when abort is requested by the abort_source, so can't we just skip it?
> 
> May we not with error level, but the same log has aborts from the gossiper (and entire log will probably have aborts from other subsystems) and you do not complain about those.

I will complain if they get in the way :)
It's fine to return an request_aborted error, but I don't see the point in logging it, certainly in error level.

**Comment by gleb-cloudius** [comment]
> > > Also, we see this error during shutdown, causing dtests to fail sporadically. Does it have to be printed at all during shutdown? `request_aborted` is expected during shutdown when abort is requested by the abort_source, so can't we just skip it?
> > 
> > 
> > May we not with error level, but the same log has aborts from the gossiper (and entire log will probably have aborts from other subsystems) and you do not complain about those.
> 
> I will complain if they get in the way :) 

So it is not logging of abort that stands in the way, right?

> It's fine to return an request_aborted error, but I don't see the point in logging it, certainly in error level.

What's the point to log anything at all? If it works nobody needs the logs anyway. So we should spend time fixing bugs instead of adding logs /s

**Comment by bhalevy** [comment]
> > > > Also, we see this error during shutdown, causing dtests to fail sporadically. Does it have to be printed at all during shutdown? `request_aborted` is expected during shutdown when abort is requested by the abort_source, so can't we just skip it?
> > > 
> > > 
> > > May we not with error level, but the same log has aborts from the gossiper (and entire log will probably have aborts from other subsystems) and you do not complain about those.
> > 
> > 
> > I will complain if they get in the way :)
> 
> So it is not logging of abort that stands in the way, right?
> 
> > It's fine to return an request_aborted error, but I don't see the point in logging it, certainly in error level.
> 
> What's the point to log anything at all? If it works nobody needs the logs anyway. So we should spend time fixing bugs instead of adding logs /s

What does **this** log message help with?
We're in shutdown so `request_aborted` is expected, what benefit does printing the error in this condition provide?

**Comment by gleb-cloudius** [comment]
> > > > > Also, we see this error during shutdown, causing dtests to fail sporadically. Does it have to be printed at all during shutdown? `request_aborted` is expected during shutdown when abort is requested by the abort_source, so can't we just skip it?
> > > > 
> > > > 
> > > > May we not with error level, but the same log has aborts from the gossiper (and entire log will probably have aborts from other subsystems) and you do not complain about those.
> > > 
> > > 
> > > I will complain if they get in the way :)
> > 
> > 
> > So it is not logging of abort that stands in the way, right?
> > > It's fine to return an request_aborted error, but I don't see the point in logging it, certainly in error level.
> > 
> > 
> > What's the point to log anything at all? If it works nobody needs the logs anyway. So we should spend time fixing bugs instead of adding logs /s
> 
> What does **this** log message help with?

What does ***same*** messages from the gossiper help with? I bet you wold be happy to have them when debugging shutdown hang. 

> We're in shutdown so `request_aborted` is expected, what benefit does printing the error in this condition provide?

I do not argue about severity level, it should not be an error at least during shutdown,  but I find the argument about not having them at all, while excluding the same kind of messages from the gossiper in the same log snippet, to be funny.

**Comment by bhalevy** [comment]
> > > > > > Also, we see this error during shutdown, causing dtests to fail sporadically. Does it have to be printed at all during shutdown? `request_aborted` is expected during shutdown when abort is requested by the abort_source, so can't we just skip it?
> > > > > 
> > > > > 
> > > > > May we not with error level, but the same log has aborts from the gossiper (and entire log will probably have aborts from other subsystems) and you do not complain about those.
> > > > 
> > > > 
> > > > I will complain if they get in the way :)
> > > 
> > > 
> > > So it is not logging of abort that stands in the way, right?
> > > > It's fine to return an request_aborted error, but I don't see the point in logging it, certainly in error level.
> > > 
> > > 
> > > What's the point to log anything at all? If it works nobody needs the logs anyway. So we should spend time fixing bugs instead of adding logs /s
> > 
> > 
> > What does **this** log message help with?
> 
> What does _**same**_ messages from the gossiper help with?

It doesn't help either.

> I bet you wold be happy to have them when debugging shutdown hang.

Not sure.  What I found helpful to debug shutdown hangs, is more detailed, info-level logging
of the shutdown steps, so when we get a hang during shutdown we can determine in which step the hang happened, in higher accuracy.  Then reproducing the issue with debug/trace level logging to zoom-in on the problem.

> 
> > We're in shutdown so `request_aborted` is expected, what benefit does printing the error in this condition provide?
> 
> I do not argue about severity level, it should not be an error at least during shutdown, but I find the argument about not having them at all, while excluding the same kind of messages from the gossiper in the same log snippet, to be funny.

Yeah, the double standard comes from the gossiper message being logged as a warning rather than an error and so it's less disruptive for dtest.  That's it.  There's no scientific grounds for that :)

**Comment by gleb-cloudius** [comment]
> 
> > I bet you wold be happy to have them when debugging shutdown hang.
> 
> Not sure. What I found helpful to debug shutdown hangs, is more detailed, info-level logging of the shutdown steps, so when we get a hang during shutdown we can determine in which step the hang happened, in higher accuracy. Then reproducing the issue with debug/trace level logging to zoom-in on the problem.
> 

More logging during hang is always better than less. If you see "gossiper is stopping message", but do not see messages about aborted operations it may point where the hang happens. You cannot put info logging at each step since most of them are executed during regular work as well (unlike the error path that is logged here).

**Comment by bhalevy** [comment]
> > > I bet you wold be happy to have them when debugging shutdown hang.
> > 
> > 
> > Not sure. What I found helpful to debug shutdown hangs, is more detailed, info-level logging of the shutdown steps, so when we get a hang during shutdown we can determine in which step the hang happened, in higher accuracy. Then reproducing the issue with debug/trace level logging to zoom-in on the problem.
> 
> More logging during hang is always better than less. If you see "gossiper is stopping message", but do not see messages about aborted operations it may point where the hang happens. You cannot put info logging at each step since most of them are executed during regular work as well (unlike the error path that is logged here).

The info logs I am talking about would be from the top level `stop()` or `shutdown()` methods before calling other functions, not from the called functions.

**Comment by gleb-cloudius** [comment]
> > > > I bet you wold be happy to have them when debugging shutdown hang.
> > > 
> > > 
> > > Not sure. What I found helpful to debug shutdown hangs, is more detailed, info-level logging of the shutdown steps, so when we get a hang during shutdown we can determine in which step the hang happened, in higher accuracy. Then reproducing the issue with debug/trace level logging to zoom-in on the problem.
> > 
> > 
> > More logging during hang is always better than less. If you see "gossiper is stopping message", but do not see messages about aborted operations it may point where the hang happens. You cannot put info logging at each step since most of them are executed during regular work as well (unlike the error path that is logged here).
> 
> The info logs I am talking about would be from the top level `stop()` or `shutdown()` methods before calling other functions, not from the called functions.

This is what we have and this is not enough. It may only point to a subsystem that hanged, not where exactly it hanged. Logs that tells you which work has been aborted are helpful.

**Comment by kbr-scylla** [comment]
> Maybe this explains https://github.com/scylladb/scylladb/issues/18959?

https://github.com/scylladb/scylladb/issues/18959 is most likely caused by the compaction/flush locking, same as the other `raft_timeout_error`s. (Should be fixed by https://github.com/scylladb/scylladb/pull/19469)

**Comment by bhalevy** [comment]
We discussed this in today's release status meeting, and the conclusion is that we need to distinguish between the expected case (like getting this exception during shutdown) vs. unexpected cases.
In the expected case, we can demote it to a warning or even consider not printing it all.

Cc @avikivity @mykaul
