### ISSUE TITLE
docs: Issue on page Replace a Dead Node in a Scylla Cluster

### ISSUE THREAD

**Issue by maesta2** [scylladb/scylladb#18920]
I would like to report an issue on page https://enterprise.docs.scylladb.com/branch-2022.2/operating-scylla/procedures/cluster-management/replace-dead-node

### Problem
![image](https://github.com/scylladb/scylladb/assets/147455686/a9505406-7f50-467f-a40b-2b948e77f55b)

###  Suggest a fix
sudo systemctl start scylla-server

**Comment by tzach** [comment]
Ouch. Thanks for reporting!
