### ISSUE TITLE
docs: Issue on page Backup your Data - need to use Describe Schema with Internals

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#18930]
I would like to report an issue on page https://opensource.docs.scylladb.com/master/operating-scylla/procedures/backup-restore/backup

### Problem

The backup does not relflect the new DESCRIBE SCHEMA WITH INTERNALS 
https://github.com/scylladb/scylladb/issues/16482

###  Suggest a fix

Use DESCRIBE SCHEMA WITH INTERNALS

**Comment by Michal-Leszczynski** [comment]
@tzach, was @Jadw1 supposed to be assigned to this issue?

**Comment by tzach** [comment]
@Michal-Leszczynski you open the original issue #16482  so I assumed you can review.
If other Michals can help - I'm all for it :)

**Comment by piodul** [comment]
This is a duplicate of https://github.com/scylladb/scylladb/issues/18456
