### ISSUE TITLE
"sstable not found" error during file-based tablet migration

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#18977]
`May 26 07:23:46 perf-latency-grow-shrink-ubuntu-db-node-3d74b9b3-3 scylla[5489]:  [shard 3:strm] sstable - Could not create SSTable component /var/lib/scylla/data/keyspace1/standard1-b78491c01b1011efa6a80da84ff2476e/me-3ggg_0kh6_3v3ps25adul7ll3oq8-big-Scylla.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: open failed: No such file or directory [/var/lib/scylla/data/keyspace1/standard1-b78491c01b1011efa6a80da84ff2476e/me-3ggg_0kh6_3v3ps25adul7ll3oq8-big-Scylla.db])`

it happens due to a race with compaction, which can delete a sstable while it's being consumed for the file-based migration.

**Comment by mykaul** [comment]
@raphaelsc - what's the impact? data loss?!

**Comment by raphaelsc** [comment]
> @raphaelsc - what's the impact? data loss?!

delayed migration, I think we're able to eventually succeed on retries. data loss doesn't happen because the error is propagated back into the coordinator

just confirmed it by looking at coordinator logs: 
`2024-05-26T07:23:46.800+00:00 perf-latency-grow-shrink-ubuntu-db-node-3d74b9b3-1  !WARNING | scylla[5471]:  [shard 0:strm] raft_topology - streaming for tablet b78491c0-1b10-11ef-a6a8-0da84ff2476e:80 failed: seastar::rpc::remote_verb_error (filesystem error: open failed: No such file or directory [/var/lib/scylla/data/keyspace1/standard1-b78491c01b1011efa6a80da84ff2476e/me-3ggg_0kh6_3v3ps25adul7ll3oq8-big-Scylla.db])`

**Comment by raphaelsc** [comment]
fix sent https://github.com/scylladb/scylladb/pull/18979

**Comment by tzach** [comment]
@mykaul wrong repo?

**Comment by raphaelsc** [comment]
> @mykaul wrong repo?

no, the mechanism is in OSS.
