### ISSUE TITLE
Backport PR with single commit reference to the wrong commit SHA

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#18973]
Since we implemented the backport automation process with `Mergify` we noticed that whenever a new backport PR is open and has only one commit, the reference points to a non-existent commit SHA.
Just an example (we have many) - https://github.com/scylladb/scylladb/pull/18963 is pointing to https://github.com/scylladb/scylladb/commit/77c61f907ed1e40b984100c9cf6431ad72808621 that doesn't exist anymore
![image](https://github.com/scylladb/scylladb/assets/9914527/f1214818-9c4b-4323-b56f-501c1b230636)

The reason for that is that we don't merge our PR but close, and there is no `mergeCommit` in the GitHub API 
```
[yaronkaikov@london]~/git/scylladb (debug-ci-yaron)$ gh pr view 18963 --json mergeCommit
{
  "mergeCommit": null
}
```

There are 2 possible solutions:

1. Modify `scripts/pull_github_pr.sh` to create merge commits for every PR
2. Change the way we work with PR today:
      * set base branch to `next` instead of `master` (can be done automatically) 
      * merge PR instead of closing them - which means when we dequeue or revert a patch the developer will need to open a new PR rather than re-use the original one
      * modify `pull_github_pr.sh` to merge a single commit PR without adding the `Closes` prefix - meaning we will not have a reference in git commit to the relevant PR

@scylladb/scylla-maint will appreciate your feedback about the suggested solution (or a new one if you have:-) 

/cc @roydahan @mykaul @dani-tweig

**Comment by roydahan** [comment]
> We can definitely change this decision, it's not set in stone, but it feels strange to change it just because a bug in "mergify".

It's not because of a bug in "mergify" but because our "twisted" process that we don't merge PRs from GitHub, but merges through a script that ammends a commit (UGLY), merge the commit, and then CLOSE the PR ticket in GitHub.
(As @yaronkaikov wrote above).

**Comment by roydahan** [comment]
> Please correct me if I'm wrong, but I think all these bullet points are simply not relevant. The problem with the single-patch PRs are that they are inserted using a **rebase** instead of **merge**. That's it - the base branch or "Closes" or the script are just red herrings and not relevant. The only problem is that when a patch is rebased into the repository, its commit hash changes - and it can continue to change when that branch continues to get rebased (e.g., when something is dequeued from "next").

No, what @yaronkaikov means is that if we merge the PR ticket (even with rebase) through the GitHub API that will actually merge the PR instead of closing it, it will solve our problem.

**Comment by nyh** [comment]
> It's not because of a bug in "mergify" but because our "twisted" process that we don't merge PRs from GitHub, but merges through a script that ammends a commit (UGLY), merge the commit, and then CLOSE the PR ticket in GitHub. (As @yaronkaikov wrote above).

No, as I keep trying to explain (and still didn't receive a convincing rebuttal that convinced me otherwise), the "script-instead-of-button" or the "Closes" text has **nothing** to do with the changing commit hash. The commit hash changes because we **rebase** it onto next instead of **merging** it. This can happen with a button and can happen with a script, and can happen with a "Closes" line and without one. If I'm wrong, please try to convince me.

**Comment by yaronkaikov** [comment]
> > It's not because of a bug in "mergify" but because our "twisted" process that we don't merge PRs from GitHub, but merges through a script that ammends a commit (UGLY), merge the commit, and then CLOSE the PR ticket in GitHub. (As @yaronkaikov wrote above).
> 
> No, as I keep trying to explain (and still didn't receive a convincing rebuttal that convinced me otherwise), the "script-instead-of-button" or the "Closes" text has **nothing** to do with the changing commit hash. The commit hash changes because we **rebase** it onto next instead of **merging** it. This can happen with a button and can happen with a script, and can happen with a "Closes" line and without one. If I'm wrong, please try to convince me.

@nyh When we merge the commit in Github API we will get the proper commit SHA as shown below
```
[yaronkaikov@london]~/git/scylladb (debug-ci-yaron)$ gh pr view 18963 --json mergeCommit
{
  "mergeCommit": <Some sha>
}
```

This value is been used by mergify when doing the backports.

**Comment by yaronkaikov** [comment]
> > > It's not because of a bug in "mergify" but because our "twisted" process that we don't merge PRs from GitHub, but merges through a script that ammends a commit (UGLY), merge the commit, and then CLOSE the PR ticket in GitHub. (As @yaronkaikov wrote above).
> > 
> > 
> > No, as I keep trying to explain (and still didn't receive a convincing rebuttal that convinced me otherwise), the "script-instead-of-button" or the "Closes" text has **nothing** to do with the changing commit hash. The commit hash changes because we **rebase** it onto next instead of **merging** it. This can happen with a button and can happen with a script, and can happen with a "Closes" line and without one. If I'm wrong, please try to convince me.
> 
> @nyh When we merge the commit in Github API we will get the proper commit SHA as shown below
> 
> ```
> [yaronkaikov@london]~/git/scylladb (debug-ci-yaron)$ gh pr view 18963 --json mergeCommit
> {
>   "mergeCommit": <Some sha>
> }
> ```
> 
> This value is been used by mergify when doing the backports.

And a real example:
[yaronkaikov@london]~/git/scylladb (next)$ gh pr view 18899 --json mergeCommit
```
{
  "mergeCommit": {
    "oid": "b7fa5261c8e8c87e526b2162e2bf92a3cfcadecd"
  }
}
```
https://github.com/scylladb/scylladb/pull/18899

**Comment by nyh** [comment]
> @nyh When we merge the commit in Github API we will get the proper commit SHA as shown below

I keep repeating myself - let's hear from other people too (@avikivity)?
As I keep saying, if you do a "merge", you get a merge commit. If you do a "rebase", you don't.  It doesn't matter if a script or a button does it, or whether or not the line "Closes:" is added.

**Comment by denesb** [comment]
This is a limitation of the Github API. It refuses to acknowledge that there are other ways to merge a PR, than the 2 it offers (simple merge or squash merge). We use a third way and GH is not cooperating with us to recognize this.

And I agree with @nyh, it would feel very annoying if we had to adjust our processes to be in the intersection of the limitations of all the tools we use.

BTW, we can check if the squash-merge would work for us, instead of rebase/cherry-pick.

**Comment by nyh** [comment]
> . The problem is that the hash of this merge commit itself will change when this merge commit is itself "rebased" to various places - like between "next" and "master" and when "next" has things dequeued in it.

On second thought, next-to-master doesn't change shas (since next commits are descendants of  master's head) - so the only problem I fear now is dequeuing things in next that can change shas of things still in next.
