### ISSUE TITLE
Bundle cqlsh with support for "DESC SCHEMA WITH INTERNALS"

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#18989]
The latest back/restore procedure is built on a new "DESC SCHEMA WITH INTERNALS" and requires support in CQLSh.
We need to bundle the latest CQLSh with Scylla to use it.

https://github.com/scylladb/scylladb/pull/18953

**Comment by mykaul** [comment]
@fruch - status for 6.1?

**Comment by mykaul** [comment]
> The server side has been in master for quite some time.
> 
> So assuming it's in the scylla server side and working (which I didn't test), it's in.
> 
> I would recommend who owns this to confirm it's working as expected.

Right now, you own it ;-)

I think this functionality is tested with Manager tests though - perhaps we need to add smaller, focused tests around this functionality - but should they be in cqlsh or in scylla?

**Comment by dani-tweig** [comment]
@fruch , what is the status here? (trying to understand the content of 6.1, and if we have blockers)

**Comment by fruch** [comment]
> @fruch , what is the status here? (trying to understand the content of 6.1, and if we have blockers)

as I've wrote above, cqlsh has the server side describe support in, and that in 6.1

as for the feature itself i.e. `.. WITH INTERNALS` , I don't know who tested it with cqlsh or not, I did not. and I'm not owning it.
even that @mykaul think I'm.

there a group owning this feature, they need to test it, and confirm the docs they suppoiled is working.

**Comment by fruch** [comment]
> > The server side has been in master for quite some time.
> > So assuming it's in the scylla server side and working (which I didn't test), it's in.
> > I would recommend who owns this to confirm it's working as expected.
> 
> Right now, you own it ;-)
> 
> I think this functionality is tested with Manager tests though - perhaps we need to add smaller, focused tests around this functionality - but should they be in cqlsh or in scylla?

question should go to the team developed and documented this feature, how it's covered, and how it should be covered.

**Comment by mykaul** [comment]
> > @fruch , what is the status here? (trying to understand the content of 6.1, and if we have blockers)
> 
> as I've wrote above, cqlsh has the server side describe support in, and that in 6.1
> 
> as for the feature itself i.e. `.. WITH INTERNALS` , I don't know who tested it with cqlsh or not, I did not. and I'm not owning it. even that @mykaul think I'm.
> 
> there a group owning this feature, they need to test it, and confirm the docs they suppoiled is working.

The ask is not if the feature 'WITH INTERNALS' is working or not, but whether it's working via CQLSH. We know it's working (via gocql for example).

**Comment by fruch** [comment]
> > > @fruch , what is the status here? (trying to understand the content of 6.1, and if we have blockers)
> > 
> > as I've wrote above, cqlsh has the server side describe support in, and that in 6.1
> > 
> > as for the feature itself i.e. `.. WITH INTERNALS` , I don't know who tested it with cqlsh or not, I did not. and I'm not owning it. even that @mykaul think I'm.
> > 
> > there a group owning this feature, they need to test it, and confirm the docs they suppoiled is working.
> 
> The ask is not if the feature 'WITH INTERNALS' is working or not, but whether it's working via CQLSH. We know it's working (via gocql for example).
> 

And again, I don't know if it is working or not, and not going to find out.
