### ISSUE TITLE
Scylla is not using ME sstables by default

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#18995]
Example:
```
INFO  2024-05-29 22:50:25,277 [shard 0:main] init - Scylla version 6.1.0~dev-0.20240529.0de3a5f3ff4b with build-id 1de40b9b16a4170d7165efd48ccc21f68a5187b5 starting ...
...
INFO  2024-05-29 22:50:25,455 [shard 0:strm] gossip - Feature check passed. Local node 127.0.13.1 features = {"AGGREGATE_STORAGE_OPTIONS", "ALTERNATOR_TTL", "CDC", "CDC_GENERATIONS_V2", "COLLECTION_INDEXING", "COMPUTED_COLUMNS", "CORRECT_COUNTER_ORDER", "CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX", "CORRECT_NON_COMPOUND_RANGE_TOMBSTONES", "CORRECT_STATIC_COMPACT_IN_MC", "COUNTERS", "DIGEST_FOR_NULL_VALUES", "DIGEST_INSENSITIVE_TO_EXPIRY", "DIGEST_MULTIPARTITION_READ", "EMPTY_REPLICA_MUTATION_PAGES", "EMPTY_REPLICA_PAGES", "GROUP0_SCHEMA_VERSIONING", "HINTED_HANDOFF_SEPARATE_CONNECTION", "HOST_ID_BASED_HINTED_HANDOFF", "INDEXES", "LARGE_COLLECTION_DETECTION", "LARGE_PARTITIONS", "LA_SSTABLE_FORMAT", "LWT", "MATERIALIZED_VIEWS", "MC_SSTABLE_FORMAT", "MD_SSTABLE_FORMAT", "ME_SSTABLE_FORMAT", "NONFROZEN_UDTS", "PARALLELIZED_AGGREGATION", "PER_TABLE_CACHING", "PER_TABLE_PARTITIONERS", "RANGE_SCAN_DATA_VARIANT", "RANGE_TOMBSTONES", "RANGE_TOMBSTONE_AND_DEAD_ROWS_DETECTION", "ROLES", "ROW_LEVEL_REPAIR", "SCHEMA_COMMITLOG", "SCHEMA_TABLES_V3", "SECONDARY_INDEXES_ON_STATIC_COLUMNS", "SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT", "STREAM_WITH_RPC_STREAM", "SUPPORTS_CONSISTENT_TOPOLOGY_CHANGES", "SUPPORTS_RAFT_CLUSTER_MANAGEMENT", "TABLE_DIGEST_INSENSITIVE_TO_EXPIRY", "TOMBSTONE_GC_OPTIONS", "TRUNCATION_TABLE", "TYPED_ERRORS_IN_READ_RPC", "UDA", "UDA_NATIVE_PARALLELIZED_AGGREGATION", "UNBOUNDED_RANGE_TOMBSTONES", "UUID_SSTABLE_IDENTIFIERS", "VIEW_VIRTUAL_COLUMNS", "WRITE_FAILURE_REPLY", "XXHASH"}, Remote common_features = {}
...
INFO  2024-05-29 22:50:25,455 [shard 0:comp] compaction - [Compact system.truncated d6889c60-1e0d-11ef-bfe3-a16d9fba19fc] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-3hqw3wcl/test/node1/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-6-big-Data.db:level=0]. 10kB to 5797 bytes (~52% of original) in 7ms = 1MB/s. ~256 total partitions merged to 1.
```

So latest master, and unless I'm missing something looks like the default is still to use MD and not ME.

Could be explained by https://github.com/scylladb/scylladb/blob/8a72324ff1ed3509e5f59d8ab26da0c7f413be0f/sstables/sstables_manager.hh#L96 , but I thought https://github.com/scylladb/scylladb/commit/63b266e94c773d007d3139a49abc26465d3d13f2 was supposed to ensure we use ME by default.

**Comment by denesb** [comment]
@tchaikov

**Comment by tchaikov** [comment]
ack. lemme double check it.

**Comment by raphaelsc** [comment]
IIRC, it can happen early in the boot until there's cluster agreement on the feature. Maybe the title of https://github.com/scylladb/scylladb/commit/63b266e94c773d007d3139a49abc26465d3d13f2 is a bit misleading, we're making md mandatory and me optional.

**Comment by raphaelsc** [comment]
But in practice it doesn't change much, clusters will be picking me once they're agree on the feature.

**Comment by tchaikov** [comment]
just reviewed the source, and started a tiny cluster to verify the behavior, as @raphaelsc put, this is the expected behavior: after this change, scylla instances start with "MD". but once the cluster is up and gets the consensus on the members' cluster features, if all of them support "ME", they will start using "ME". so, in production, "ME" is the default format used by 6.0 clusters.

**Comment by mykaul** [comment]
Thanks, looks like we can close this then.

**Comment by aleksbykov** [comment]
@raphaelsc @tchaikov , can you help me
Here is a link to log: https://cloudius-jenkins-test.s3.amazonaws.com/a6ab8440-8689-4fb8-a608-1961d46ad16d/20240610_152132/db-cluster-a6ab8440.tar.gz
Rolling upgrade was run from 6.0 -> 6.1. i set sstable_format explicitly `--sstable_format me`. But all nodes in with 6.0 and after upgrade with 6.1, and even after `nodetool upgradesstable` all sstables stay in md format

additionally, i checked that all node have supported feature: ME_SSTABLE_FORMAT

**Comment by tchaikov** [comment]
ack. looking..

**Comment by tchaikov** [comment]
i was on something else, will be back to this issue tomorrow.

**Comment by tchaikov** [comment]
> thank you Raphael, for the remarks!
> 
> just reviewed the source, and started a tiny cluster to verify the behavior, as @raphaelsc put, this is the expected behavior: after this change, scylla instances start with "MD". so we don't break the backward compatibility. but once the cluster is up and gets the consensus on the members' cluster features, if all of them support "ME", they will start using "ME". so, in production, "ME" is the default format used by 6.0 clusters.

turns out i was testing with an old branch. and this issue is a regression!

**Comment by tchaikov** [comment]
@aleksbykov thanks for pointing this out. created a fix just now.
