### ISSUE TITLE
Auth breaks on the upgrade of the 1st node

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#19032]
## Packages

Base Scylla version: `6.0.0~rc0-20240523.1b4d5d02ef89` with build-id `a54b5be81dd2a68aab64c8915301259e38b20df6`
Target Scylla version (or git commit hash): `6.1.0~dev-20240531.5b4e688668bf` with build-id `39014653044c4f256aa6a74e012aa1cc1fd7d8b6`

Kernel Version: `5.15.0-1062-aws`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

After 1st node update (node-3: 10.4.2.45), all client are failing to authenticate:

Python driver from the test:
```
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'10.4.2.45:9042': AuthenticationFailed('Failed to authenticate to 10.4.2.45:9042: Error from server: code=0100 [Bad credentials] message="Username and/or password are incorrect"')})
```

Java driver in C-S:
```
ERROR 04:23:49,755 Authentication error on host /10.4.2.45:9042: Username and/or password are incorrect
ERROR 04:23:49,758 Authentication error during reconnection to /10.4.2.45:9042, scheduling retry in 4000 milliseconds
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /10.4.2.45:9042: Username and/or password are incorrect
```

go driver in gemini:
```
2024/06/01 04:11:10 error: failed to connect to 10.4.2.45:9042 due to error: Username and/or password are incorrect
2024/06/01 04:11:14 error: failed to connect to 10.4.2.45:9042 due to error: Username and/or password are incorrect
```

also seen those errors on node-1:

```
2024-06-01 04:10:59.757 <2024-06-01 04:10:59.710>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=1d3ecb94-1ab6-4e12-9eef-b60bc5af09a6: type=DATABASE_ERROR regex=(^ERROR|!\s*?ERR).*\[shard.*\] line_number=6792 node=rolling-upgrade--ubuntu-focal-db-node-abc561ee-1
2024-06-01T04:10:59.710+00:00 rolling-upgrade--ubuntu-focal-db-node-abc561ee-1      !ERR | scylla[5543]:  [shard 0:strm] group0_raft_sm - Error while applying mutations from 10.4.2.45: Can't find a column family with UUID 23392e27-9e45-3292-b429-12845e17c153
```

which seems to be coming from `system.roles`
```
< t:2024-06-01 04:10:59,475 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2024-06-01T04:10:59.375+00:00 rolling-upgrade--ubuntu-focal-db-node-abc561ee-3     !INFO | scylla[13148]:  [shard 4:main] repair - Loading repair history for keyspace=system, table=roles, table_uuid=23392e27-9e45-3292-b429-12845e17c153
```

## Impact

User can upgrade a cluster, since first node upgrade breaks all auth

## How frequently does it reproduce?

happens all across the rolling upgrading on all the different distros

## Installation details

Cluster size: 4 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-abc561ee-4 (34.248.187.215 | 10.4.1.17) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-abc561ee-3 (3.254.233.230 | 10.4.2.45) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-abc561ee-2 (34.244.36.188 | 10.4.2.148) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-abc561ee-1 (34.254.205.148 | 10.4.3.48) (shards: 7)

OS / Image: `ami-076c53c6f3f336b25` (aws: undefined_region)

Test: `rolling-upgrade-ami-test`
Test id: `abc561ee-af8c-4fb9-87e4-db4f036f9352`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/da5f0d43b6fb0a0c84731585cf4c79ee6a58bc17/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor abc561ee-af8c-4fb9-87e4-db4f036f9352`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=abc561ee-af8c-4fb9-87e4-db4f036f9352)
- Show all stored logs command: `$ hydra investigate show-logs abc561ee-af8c-4fb9-87e4-db4f036f9352`

## Logs:
- **db-cluster-abc561ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/db-cluster-abc561ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/db-cluster-abc561ee.tar.gz)
- **sct-runner-events-abc561ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/sct-runner-events-abc561ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/sct-runner-events-abc561ee.tar.gz)
- **sct-abc561ee.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/sct-abc561ee.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/sct-abc561ee.log.tar.gz)
- **loader-set-abc561ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/loader-set-abc561ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/loader-set-abc561ee.tar.gz)
- **monitor-set-abc561ee.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/monitor-set-abc561ee.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/abc561ee-af8c-4fb9-87e4-db4f036f9352/20240601_042858/monitor-set-abc561ee.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-ami-test/222/)
[Argus](https://argus.scylladb.com/test/cc80460f-2278-4fe5-8781-1776502bc7e1/runs?additionalRuns[]=abc561ee-af8c-4fb9-87e4-db4f036f9352)
</details>

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/issues/19023 ?

**Comment by fruch** [comment]
> #19023 ?

yes, seems it's on the same issue.

Also it's a bug in SCT that it does upgrade from a release candidate, it should be skipping them, and falling back to 5.4
I need to check why it didn't.

if we didn't hit it now, we would have when 6.0 was released...

**Comment by mykaul** [comment]
Shall we close as duplicate?

**Comment by fruch** [comment]
> > #19023 ?
> 
> yes, seems it's on the same issue.
> 
> Also it's a bug in SCT that it does upgrade from a release candidate, it should be skipping them, and falling back to 5.4 I need to check why it didn't.
> 
> if we didn't hit it now, we would have when 6.0 was released...

I take it back, on release we filter rc versions, on master/enterprise we don't.

anyhow this issue is blocking us for getting a good view of what's the status with upgrades now that tablets is enabled by default. maybe on 6.0 rc2 we'll see it...

**Comment by fruch** [comment]
> Shall we close as duplicate?

yes, I would recommend leaving the one that is clearer...

**Comment by mykaul** [comment]
> > > #19023 ?
> > 
> > 
> > yes, seems it's on the same issue.
> > Also it's a bug in SCT that it does upgrade from a release candidate, it should be skipping them, and falling back to 5.4 I need to check why it didn't.
> > if we didn't hit it now, we would have when 6.0 was released...
> 
> I take it back, on release we filter rc versions, on master/enterprise we don't.
> 
> anyhow this issue is blocking us for getting a good view of what's the status with upgrades now that tablets is enabled by default. maybe on 6.0 rc2 we'll see it...

This is not related to tablets but to authv2 (over Raft)

**Comment by nuivall** [comment]
duplicate https://github.com/scylladb/scylladb/issues/19023, first bug entry wins.
