### ISSUE TITLE
Incremental Repair

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#19045]
Placeholder, description TODO

**Comment by Surrina-ki** [comment]
@denesb Is there a planned timeline for starting the development of incremental repairs?

**Comment by denesb** [comment]
> @denesb Is there a planned timeline for starting the development of incremental repairs?

Incremental repair will be an enterprise-only feature. Work on it has already started, but that is all I can share about it for now.

**Comment by nyh** [comment]
@denesb please note that this issue was a duplicate of https://github.com/scylladb/scylladb/issues/83. If there is an official decision that this will *never* be done, let's write it in https://github.com/scylladb/scylladb/issues/83 as well.
