### ISSUE TITLE
scrub/validate: verify both per-chunk checksums and digest

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#19058]
Currently we check checksums only for compressed sstables. Digest is never checked.
Sstables failing the check should be declared invalid.

All scrub modes should check checksums and digest.

**Comment by denesb** [comment]
We already check checksums for compressed sstables. This is implemented in the [compressed_file_data_source_impl](https://github.com/scylladb/scylladb/blob/849856b96407f3a79811c6aa4be98a38b6b2df8f/sstables/compress.cc#L337-L452). The checksums are checked on every read, but only for the chunks affected by the read.

We want the following to happen on every scrub:
1) Check the checksum on every single chunk in the data file.
2) Check the digest calculated over the entire file.

Scrub always reads the entire file, so for compressed sstables, we get (1) for free already. We just need to implement digest calculation and checking (see existing implementation in [do_validate_compressed()](https://github.com/scylladb/scylladb/blob/849856b96407f3a79811c6aa4be98a38b6b2df8f/sstables/sstables.cc#L2447-L2496]) This should be conditional, enabled by a flag, only when doing scrub.
For uncompressed sstables, we need to implement a file source implementation, which does the checksum and digest checking transparently, like in the case of compressed sstables. This file source would only be injected into the stack when doing scrub. We can use the existing code in [do_validate_uncompressed()](https://github.com/scylladb/scylladb/blob/849856b96407f3a79811c6aa4be98a38b6b2df8f/sstables/sstables.cc#L2498-L2542) to implement this file sync.

Once done, I think we should reimplement `do_validate_uncompressed()` and `do_validate_compressed()` to rely on these file streams, to avoid code duplication.

**Comment by mykaul** [comment]
I would split the work on non-compressed to a sub-item, with lower priority.

**Comment by denesb** [comment]
As for testing, we need two test cases, for both compressed/uncompressed (so 4 in total):
* A random corruption to the file, run scrub --mode=validate which detects the corruption via checksum validation.
* A corruption to the file, which either truncates an entire chunk from the file, or corrupts a chunk in such a way that the checksum validation doesn't detect it, but the digest calculation does. I don't know if this is possible and we don't need to try very hard, the above case is more important.

**Comment by mykaul** [comment]
> > I would split the work on non-compressed to a sub-item, with lower priority.
> 
> Why? The entire point is to make validate reliable, not having to think about whether the sstable is compressed or not.

When was the last time you've looked at an uncompressed sstable? I think it's rare (would be nice not to support it at all, if you ask me).

**Comment by denesb** [comment]
> > > I would split the work on non-compressed to a sub-item, with lower priority.
> > 
> > 
> > Why? The entire point is to make validate reliable, not having to think about whether the sstable is compressed or not.
> 
> When was the last time you've looked at an uncompressed sstable? I think it's rare (would be nice not to support it at all, if you ask me).

Some customers do use it (I don't know why either, they have their reasons) and we need to be able to find corruptions in such sstables too.

**Comment by ndragazis** [comment]
Following up on @denesb plan (https://github.com/scylladb/scylladb/issues/19058#issuecomment-2273067830):

Note that we already have a function in the SSTables API that performs checksum and digest checking: it's the `validate_checksums()`. This calls `do_validate_{compressed, uncompressed}()` underneath and it's currently being used by `scylla sstable validate-checksums`. Theoretically, we could plug this into scrub/validate. The reason @denesb suggests we embed the checksum and digest checking in the data source instead is to avoid reading data more than once. Scrub/validate already reads the SSTable data once to run the mx or the older reader-level validator. This happens in `sstables::scrub_sstables_validate_mode()` -> `sstables::sstable::validate()`.

**Comment by ndragazis** [comment]
## Design considerations for digest

For compressed SSTables the validators read data via the `compressed_filed_data_source_impl`. This already does checksum checking. Extending this data source with digest checking presents some challenges:
1. **Passing expected digest as an argument**: The data source knows nothing about SSTables, so it needs to receive it from the SSTable layer. We need an optional constructor argument with a `nullopt` default value to disable digest checking by default. The problem is that this code path is synchronous, whereas digest retrieval is asynchronous. This means that the digest argument has to traverse a lot of levels (up to `data_consume_rows()`), so a lot of APIs have to be changed. We should try to avoid that if possible.
3. **Define the data source's behavior for partial reads, skips and early closes**:
    The data source will be calculating the digest incrementally while reading new chunks in `get()`, and perform the check on EOF. But what if the user never reads the whole Data file? We need to clearly define the API for this case. I see three options here:
    1. Abort the digest calculation silently as soon as we discover we cannot calculate it.
    2. Fail loudly if we discover that we cannot calculate it.
    3. Implicitly read the missing data to calculate it.

**Comment by ndragazis** [comment]
Copying from @denesb's plan:

> For uncompressed sstables, we need to implement a file source implementation, which does the checksum and digest checking transparently, like in the case of compressed sstables. This file source would only be injected into the stack when doing scrub.

Note that we have an open issue about enabling checksum validation for uncompressed SSTables in all cases: https://github.com/scylladb/scylladb/issues/497.
In this issue we focus only on adding this functionality for scrub.

**Comment by denesb** [comment]
With both https://github.com/scylladb/scylladb/pull/20207 and https://github.com/scylladb/scylladb/issues/19058 in, this issue can be closed as complete.
