### ISSUE TITLE
scrub/validate: catch all `malformed_sstable_exception` errors

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#19057]
When validating an sstable hits a malformed sstable error, the sstable should be declared invalid immediately.

**Comment by ndragazis** [comment]
Scrub already supports the desired behavior.

Validation happens in `scrub_sstables_validate_mode()`, which offloads validation to the SSTable layer, i.e. either `sstable::validate()` or `mx::validate()`. Both of these methods have try..catch blocks to handle `malformed_sstable_exception` errors gracefully.

If the SSTable layer reports any errors, `scrub_sstables_validate_mode()` moves the SSTable to quarantine.
