### ISSUE TITLE
Repair: nodetool repair range is set with start_token and end_token

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylladb#19077]
Nodetool repair range is set with start_token and end_token, then the option startToken and endToken is null. Please see the following example:
command1
```
./tools/java/bin/nodetool -p 7200 repair -pr -st 9139226322587443227 -et 9170170169869227572
```
Here is the error info I add in code api/storage_service.cc
```
void set_repair(http_context& ctx, routes& r, sharded<repair_service>& repair) {
    ss::repair_async.set(r, [&ctx, &repair](std::unique_ptr<request> req) {
        static std::vector<sstring> options = {"primaryRange", "parallelism", "incremental",
                "jobThreads", "ranges", "columnFamilies", "dataCenters", "hosts", "ignore_nodes", "trace",
                "startToken", "endToken" };
        std::unordered_map<sstring, sstring> options_map;
        for (auto o : options) {
            auto s = req->get_query_param(o);
            apilog.error("set_repair req option is {} option param s is {}", o, s); // here to print the info of options and req param
            if (s != "") {
                options_map[o] = s;
            }
        }
...
}
```
then I get 
```
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is primaryRange option param s is true
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is parallelism option param s is parallel
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is incremental option param s is false
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is jobThreads option param s is 1
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is ranges option param s is 9139226322587443227:9170170169869227572
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is columnFamilies option param s is 
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is dataCenters option param s is 
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is hosts option param s is 
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is ignore_nodes option param s is 
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is trace option param s is false
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is startToken option param s is 
ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is endToken option param s is 
```

command2
```
./tools/java/bin/nodetool -p 7200 repair -pr -st 9139226322587443227
```
then I get 
```
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is primaryRange option param s is true
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is parallelism option param s is parallel
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is incremental option param s is false
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is jobThreads option param s is 1
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is ranges option param s is 9170170169869227572:
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is columnFamilies option param s is 
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is dataCenters option param s is 
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is hosts option param s is 
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is ignore_nodes option param s is 
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is trace option param s is false
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is startToken option param s is 
ERROR 2024-06-04 16:15:58,619 [shard 0] api - set_repair req option is endToken option param s is 
```
and it does not support a single `-st` or `-et` in executing `nodetool repair`

```
# ./tools/java/bin/nodetool -p 7200 repair -pr -st 9139226322587443227
error: Scylla API server HTTP POST to URL '/storage_service/repair_async/system_auth' failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
```

**Comment by denesb** [comment]
@qiuqiu-007 please provide ScyllaDB version.

**Comment by qiuqiu-007** [comment]
> @qiuqiu-007 please provide ScyllaDB version.

ver 5.2.18

**Comment by denesb** [comment]
@qiuqiu-007 nodetool uses the `ranges` option, see:

> ERROR 2024-06-04 16:10:00,643 [shard 0] api - set_repair req option is ranges option param s is 9139226322587443227:9170170169869227572

The `startToken` and `endToken` parameters are not used by nodetool.

**Comment by qiuqiu-007** [comment]
@denesb Look at here, it shows the parameters `-st` `-et` , as it is described, the  `startToken` and `endToken` parameters are the same.
![image](https://github.com/scylladb/scylladb/assets/143240433/d9e74359-949b-477c-a76c-6c1014f2e0b8)

**Comment by denesb** [comment]
I mean that the `startToken` and `endToken` parameters of `nodetool repair` map to the `range` parameter of the repair API endpoint, not to the parameters of the same name.

**Comment by qiuqiu-007** [comment]
Then if I wanna specify the the `startToken` and `endToken` parameters of `nodetool repair` when I use `-pr`, the only way is to use API to execute repair ? As the following range and primary_range logic :
```
if (options.ranges.size()) {
        ranges = options.ranges;
} else if (options.primary_range) {
//...
} else {//... }
```

**Comment by denesb** [comment]
> Then if I wanna specify the the `startToken` and `endToken` parameters of `nodetool repair` when I use `-pr`, the only way is to use API to execute repair ? As the following range and primary_range logic :
> 
> ```
> if (options.ranges.size()) {
>     ranges = options.ranges;
> } else if (options.primary_range) { //...
> } else {//... }
> ```

Specifying `-pr` and a range for the repair is mutually exclusive, regardless of how you supply the range: via `startToken`/`endToken` or `range.

**Comment by qiuqiu-007** [comment]
When I send the HTTP request it works:
```
curl -X POST "http://172.17.0.2:3005/storage_service/repair_async/system?primaryRange=true&startToken=9139226322587443227&endToken=9170170169869227572"
```
![image](https://github.com/scylladb/scylladb/assets/143240433/b96df5c0-0208-415b-b48a-cf6dd9d906db)

Then I think it is `nodetool repair -pr` get in bug.

**Comment by denesb** [comment]
@asias is this deliberate or an oversight? Maybe we should just remove `startToken` and `endToken`, it looks like they are not handled consistently with the `ranges` option.

**Comment by asias** [comment]
> When I send the HTTP request it works:
> 
> ```
> curl -X POST "http://172.17.0.2:3005/storage_service/repair_async/system?primaryRange=true&startToken=9139226322587443227&endToken=9170170169869227572"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/143240433/339179028-b96df5c0-0208-415b-b48a-cf6dd9d906db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTU4NzIsIm5iZiI6MTcxODI1NTU3MiwicGF0aCI6Ii8xNDMyNDA0MzMvMzM5MTc5MDI4LWI5NmRmNWMwLTAyMDgtNDE1Yi1iNDhhLWNmNmRkOWQ5MDZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNTEyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWIwMGVhZTU2NTAzMDQ3MDBkNWNhMGNmOTA4ZDY1NzA4MmJlOTgwY2JmMjBjMTliMmUzODI3MmQ3MjBjM2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AQUK9M_fzCXjmkkriZt-jYGKW1nQRWMALad-WkiBBwM)
> 
> Then I think it is `nodetool repair -pr -st xxx -et xxx` get in bug, or it is mean to.

The two options startToken and endToken in the rest api are legacy. They are not very useful since we already have the ranges options. Combining primaryRange and startToken/endToken options are not recommended. In general, it makes little sense for users to manipulate the ranges by intersection some user chosen tokens.  Either use nodetool repair -pr  options or specific vnode token ranges by using nodetool repair -st -et.

**Comment by asias** [comment]
> @asias is this deliberate or an oversight? Maybe we should just remove `startToken` and `endToken`, it looks like they are not handled consistently with the `ranges` option.

They are not the same by design. The startToken and endToken are about intersection and ranges about direct ranges selection.  

I am not sure if we should remove it. Sophisticated users might still use this option over restful API.  Normal users they will not care about it anyway.

**Comment by qiuqiu-007** [comment]
Another one, here the `options.start_token`  and  `options.end_token` is set to repair the intersect of range or primary range, I wanna know the idea of this function in API ?

**Comment by qiuqiu-007** [comment]
> > @asias is this deliberate or an oversight? Maybe we should just remove `startToken` and `endToken`, it looks like they are not handled consistently with the `ranges` option.
> 
> They are not the same by design. The startToken and endToken are about intersection and ranges about direct ranges selection.
> 
> I am not sure if we should remove it. Sophisticated users might still use this option over restful API. Normal users they will not care about it anyway.

So will the api and nodetool command be selected one method to an union,  or just let it?
