### ISSUE TITLE
tablets: alter keyspace - refactor

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#19126]
The code introduced in https://github.com/scylladb/scylladb/pull/16723, while working, doesn't look all that readable, and because it's to stay with us, we can save our future selves time by investing in its refinement right now. This includes:
1. Refactoring larger portions of the code into separate functions
2. https://github.com/scylladb/scylladb/pull/16723#discussion_r1606051055
3. https://github.com/scylladb/scylladb/pull/16723#discussion_r1606050588
4. Consider https://github.com/scylladb/scylladb/pull/16723#discussion_r1587180354
5. https://github.com/scylladb/scylladb/pull/16723#discussion_r1587115923
6. Consider https://github.com/scylladb/scylladb/pull/16723#discussion_r1587072137

**Comment by nuivall** [comment]
I will probably be doing 3. as part of auth work.

**Comment by nuivall** [comment]
And 6. potentially too

**Comment by dani-tweig** [comment]
@ptrsmrn , can this one be closed?

**Comment by ptrsmrn** [comment]
Not yet, only some subproblems are resolved.

**Comment by mykaul** [comment]
> Not yet, only some subproblems are resolved.

@ptrsmrn - it's very unclear what's left to be done here.

**Comment by ptrsmrn** [comment]
Some of this has been addressed already: https://github.com/scylladb/scylladb/issues/19126#issuecomment-2151784387 & https://github.com/scylladb/scylladb/issues/19126#issuecomment-2151787481, other items don't seem that important, closing.
