### ISSUE TITLE
tablets: alter keyspace follow-ups (epic) - part 1

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#19123]
Follow-ups to https://github.com/scylladb/scylladb/pull/16723

Part 2 - https://github.com/scylladb/scylladb/issues/20665
Remaining improvement ideas - https://github.com/scylladb/scylladb/issues/20666

Setting milestone to 6.1, as the follow-up work is not critical. Can be backported to 6.0.1+
```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/18795
- [ ] https://github.com/scylladb/scylladb/pull/20208
```

**Comment by mykaul** [comment]
If there are items that are done, I suggest marking them as such.

**Comment by ptrsmrn** [comment]
> If there are items that are done, I suggest marking them as such.

As of now, there are no such items.

**Comment by bhalevy** [comment]
Please add https://github.com/scylladb/scylladb/issues/17572
and the reversal of this (alter from N->0):
https://github.com/scylladb/scylladb/issues/17579
