### ISSUE TITLE
Optimal way of adding node in a heavy loaded ScyllaDB cluster

### ISSUE THREAD

**Issue by amitesh88** [scylladb/scylladb#19128]
We have scylladb multidc cluster setup with 3 nodes in dc1 for writes and 6 in dc2 for reads
Currently dc1 nodes have 16cpu with 80% utilisation
We want to add 3  more nodes in dc1 for smooth  write operation in future as app traffic is growing

Please suggest correct method to add nodes in cluster with minimum downtime

Note: We have 1.8 tb of data present on each node
Scylla version : 5.4.1

**Comment by tzach** [comment]
There is no need for downtime!
See
https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-node-to-cluster.html

Also, as this is more of a question than an issue, it better fit in https://forum.scylladb.com/

**Comment by amitesh88** [comment]
Already posted on slack ,  i ll post on community too
https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-node-to-cluster.html
 Followed the link 
But not sure if it is good for nodes where continuous writing is happening
Also , when should I alter keyspace of system_auth to make it equal to number of nodes, when continuous writing is happening
Shall alter keyspace before starting new node or after
