### ISSUE TITLE
I have Issue on nodetool rebuild : keeps getting stuck for a long time

### ISSUE THREAD

**Issue by shitalnyaupane** [scylladb/scylladb#19211]
I am trying to add a new Data Center to an existing 3 node scylla cluster. The older DC and the new DC are are different location (connected via IPsec).
I successfully joined the new DC and is UN.
The problem arises while running nodetool rebuild command on the new node. It runs smoothly for a while but gets stuck at a certain point and the process stops suddenly.
What could be the possible cause for this issue and how can i fix it ?

## Suggest a fix

**Comment by mykaul** [comment]
Hi @shitalnyaupane - I suggest asking questions @ https://forum.scylladb.com - it's a better venue for questions.
But there as well - I assume logs will be needed (version as well) to understand what's going on.

**Comment by shitalnyaupane** [comment]
Thank you for the response. Will post there.
