### ISSUE TITLE
repair: make repair_history work with tablets

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#19210]
Repair history is currently a local table. This means that every time ranges are moved around, repair history for said range is left behind. This is not a problem for vnodes, as range movements are rare.
With tablets however, ranges are expected to move around a lot more and with the current setup, this means that tombstones are harder to be purged.

There are two possible solutions here:
1) Move repair_history to RAFT, make it a group0-distributed system table, there is a PR for this: https://github.com/scylladb/scylladb/pull/18211
2) Move repair_history content into the tablets table, which is already a group0-distributed table

**Comment by denesb** [comment]
I think (2) is a much better choice:
* Moving tables to group0 has a cost, we shouldn't just move everything to group0, if there are alternatives.
* system.tablets already exists and is managed by group0, storing per-repair history data in said table is a natural choice, and integrates nicely with incremental repair.
* If we keep using repair_history, we need to make it work for both tablets and vnodes. Best to leave repair_history as-is, to be vnode specific and use system.tablets for tablets.

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/issues/17507 ?
