### ISSUE TITLE
RFE: Add API for read barrier

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylladb#19213]
This could be useful for Scylla Manager in the backup procedure. It contains the 3 following steps:
- snapshot all requested tables
- await schema agreement
- backup the output of DESCRIBE SCHEMA WITH INTERNALS

As SM wants to backup only a single version of DESC SCHEMA (backing up DESC SCHEMA from every node creates decision problem with restore procedure), it queries DESC SCHEMA on only 1 of the nodes. The problem is that SM needs to backup schema that is not older than sstables in the snapshot - older sstables should work fine with altered schema, but newer sstables used with older schema might create problems. The idea was to await schema agreement between snapshot and DESC SCHEMA stages, so that all nodes have the same schema - meaning that all nodes have schema that's not older than snapshot sstables.

Problem with awaiting schema agreement is that it is usually done from a single node POV. Gocql implementation does that by checking if schema versions from `system.local/peers` are the same, but it does so only from the control connection POV. From the backup perspective it is not enough. See the following scenario:
- node1 gets schema change
- node1 gets inserts with new schema
- SM backup is performed, assume that gocql control connection is connected to node2
- from node2 POV, cluster is in a state of schema agreement (the schema change wasn't propagated to it yet)
- SM backs up DESC SCHEMA output from node2

This scenario (if possible) results in having newer sstables than schema in the backup and that might create problem.
On the other hand, if we replaced await schema agreement with read barrier followed by querying DESC SCHEMA on the same node, on which read barrier was performed, then it should work fine.

Right now read barrier API is not exposed, but @kbr-scylla mentioned that it can be simulated by running some dummy schema change:
```
async def read_barrier(cql: Session, host: Host):
    """To issue a read barrier it is sufficient to attempt dropping a
    non-existing table. We need to use `if exists`, otherwise the statement
    would fail on prepare/validate step which happens before a read barrier is
    performed.
    """
    await cql.run_async("drop table if exists nosuchkeyspace.nosuchtable", host = host)
```

Questions:
1. Does read carrier indeed solve SM issue? 
2. Is this enough of a reason to introduce read barrier in Scylla API?
3. Is using the workaround of sending dummy schema change safe and will it be supported in the future?

Of course, there are other ways to make sure that backed up DESC SCHEMA is newer than snapshot sstables. SM could probably do it by:
- implementing custom host selection policy for the driver - not sure if it would be easy outside of gocql pkg - and using it to query `system.local` on every node
- creating many single host sessions and querying `system.local` from every host manually
- changing gocql to somehow support that in `AwaitSchemaAgreement` method
- in case `schema_version` contains timestamp information, SM could parse it in order to find a node with the newest schema and use it to query DESC SCHEMA

What do you think about that?
@piodul @kbr-scylla @kostja @karol-kokoszka

**Comment by kbr-scylla** [comment]
> Does read carrier indeed solve SM issue?

Yes

> Is this enough of a reason to introduce read barrier in Scylla API?

Yes, we already need to do read barrier from tests, and the `drop table if exists` thing is a hack, and adding a read barrier API is like 2 hours of work testing included (for experienced dev).

> Is using the workaround of sending dummy schema change safe and will it be supported in the future?

`drop table` must check the table's presence and we decided that all schema changes are linearizable, so it will always have to perform a read barrier. So if it stops working at any point it would be a bug in schema changes implementation.

But nevertheless using it for read barrier is a hack.

Adding the API is also a `good first issue`. I'm adding this to the backlog.

But priority is P3 because there's a workaround

**Comment by kbr-scylla** [comment]
> implementing custom host selection policy for the driver - not sure if it would be easy outside of gocql pkg - and using it to query system.local on every node

You have to be able to query a specific node for the workaround to apply anyway, but I think all drivers should already be capable of doing that? They should all support some kind of `host` parameter or whitelist policy

**Comment by Michal-Leszczynski** [comment]
> drop table must check the table's presence and we decided that all schema changes are linearizable, so it will always have to perform a read barrier. So if it stops working at any point it would be a bug in schema changes implementation.

Ok, so that's what SM will do in 3.3 release which integrates with Scylla 6.0.

> You have to be able to query a specific node for the workaround to apply anyway, but I think all drivers should already be capable of doing that? They should all support some kind of host parameter or whitelist policy

In terms of `gocql`, it's possible to set host whitelist when creating session, but not per single query, so SM would need to create a separate session for the describe schema query. This is not perfect, but it's not a problem as well.

**Comment by Michal-Leszczynski** [comment]
Actually, there is also a question of permissions.
Even when SM has credentials to managed cluster, the user used by SM usually has minimal entry permissions (more invasive permissions are usually added only for the time of performing restore). They are enough to query DESC SCHEMA and find which tables are views, but it does not allow for dropping table and other schema related operations.
Trying to use mentioned read barrier workaround results in:
```
Unauthorized: Error from server: code=2100 [Unauthorized] message="User X has no DROP permission on <table Y.Z> or any of its parents"
```
My understanding of the comment:
```
    """To issue a read barrier it is sufficient to attempt dropping a
    non-existing table. We need to use `if exists`, otherwise the statement
    would fail on prepare/validate step which happens before a read barrier is
    performed.
    """
```
is that is that the error pasted above is returned from the prepare/validate step and it does not result in performing a read barrier. Is this correct @kbr-scylla?

So in order to use this workaround, SM would not only need credentials to the cluster, but also permissions to make some dummy schema change?

**Comment by kbr-scylla** [comment]
Good point.

I checked the code and the group 0 guard is taken (which does read barrier internally) **before** checking permissions.

You could potentially argue that this is an implementation detail and the order could be reversed... Although with the switch to auth v2 (in 6.0, with raft-topology mode), permissions are stored in Raft group 0, so taking the guard refreshes both permissions and schema, and arguably it is the only correct thing to do (we want the schema change to be based on the latest state for both schema and permissions).


So:
- even if you get the permissions error, the barrier was done, so you should be good (if I understand the code correctly)
- still it is arguably an implementation detail and incorrect to depend on
- but this detail will 99.9% not change and in fact we're strengthening the dependency
- still we should probably implement the API eventually so we don't waste our brain cycles on these discussions

**Comment by kostja** [comment]
* Kamil Braun ***@***.***> [24/06/17 17:15]:
> I checked the code and the group 0 guard is taken (which does read barrier internally) **before** checking permissions.
> 
> You could potentially argue that this is an implementation detail and the order could be reversed... Although with the switch to auth v2 (in 6.0, with raft-topology mode), permissions are stored in Raft group 0, so taking the guard refreshes both permissions and schema, and arguably it is the only correct thing to do (we want the schema change to be based on the latest state for both schema and permissions).
> 
> 
> So:
> - even if you get the permissions error, the barrier was done, so you should be good (if I understand the code correctly)
> - still it is arguably an implementation detail and incorrect to depend on
> - but this detail will 99.9% not change and in fact we're strengthening the dependency
> - still we should probably implement the API eventually so we don't waste our brain cycles on these discussions

There is also an option to add a new SQL statement for it. 

-- 
Konstantin Osipov, Moscow, Russia

**Comment by Michal-Leszczynski** [comment]
In the context of SM use case - using read barrier to ensure updated schema for DESC SCHEMA output - @mykaul suggested to make DESC SCHEMA perform a read barrier before creating and returning CQL statements.

From SM POV (and also regular user) this would be the most convenient, but as @piodul noticed, it would make it impossible to perform DESC SCHEMA in a cluster without QUORUM of alive nodes, which might be a problem in those already difficult situations.

@kbr-scylla, @kostja what do you think about this idea?

**Comment by mykaul** [comment]
Could the barrier be made optional, in the sense that if it fails (due to lack of quorum), let's proceed without it?

**Comment by kbr-scylla** [comment]
For this use case we need a guaranteed read barrier though.

So I don't think there's value adding read barrier to DESC SCHEMA. It cannot be mandatory. And making it non-mandatory doesn't really help the current issue.

**Comment by Michal-Leszczynski** [comment]
I'm not sure why, but this missed the 2024.2 release.
Do we know which enterprise release is planned to contain it?
@mykaul @emdroid

**Comment by kbr-scylla** [comment]
Go to the commit which GH referenced when the PR was closed:
https://github.com/scylladb/scylladb/commit/a9e985fcc90d0917669ceb16f0531707a0989aa7

click the 3 dots to see which branches the commit ended up on
![Image](https://github.com/user-attachments/assets/4f51bebd-2461-4786-aed2-7fe459945af9)

![Image](https://github.com/user-attachments/assets/d4e6cedb-7690-4906-a7a2-87d29ddab8d8)


6.1 was the first branch this went into.

2024.2 is based on 6.0.

The next enterprise release following 2024.2 will be 2025.1, which is based on 6.3 (actually equal given the migration to SA)

**Comment by Michal-Leszczynski** [comment]
Thanks for the explanation, for some reason I though that 2024.2 was based on a newer Scylla version than 6.0.
