### ISSUE TITLE
Deprecate node operation APIs that are IP based (we want to receive host IDs)

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#19218]
See https://github.com/scylladb/scylladb/issues/12277

This is a part of the above --- we need to deprecate the APIs **first** (the sooner the better), then in a later release, remove them.

IIUC the remaining non-deprecated part is `ignore_nodes` used in removenode and replace. It accepts both host IDs and IPs, we want to deprecate the IP support.

Deprecation means:
- we should document that passing IP here is deprecated (if it was even documented in the first place)
- and print a warning if one passes IP

**Comment by kbr-scylla** [comment]
https://github.com/scylladb/scylladb/issues/12277 will be unblocked only after we branch a release that has this issue solved.

**Comment by PrabhuUdurg** [comment]
I am new here, does someone working on it already?

**Comment by kbr-scylla** [comment]
Hi @PrabhuUdurg, I guess that you're looking for issues to contribute?

I have internally planned this issue for my team to do in the next quarter.

Perhaps I could interest you instead in some other issues also labeled `good first issue` that were not planned to be done in the next quarter, and nobody works on them:
- https://github.com/scylladb/scylladb/issues/16985
- https://github.com/scylladb/scylladb/issues/15286
- https://github.com/scylladb/scylladb/issues/15558
- https://github.com/scylladb/scylladb/issues/17443

**Comment by PrabhuUdurg** [comment]
@kbr-scylla Thank you so much I will look to them!
