### ISSUE TITLE
docker run only works with --listen-address as commandline argument unable to override with /etc/scylla/scylla.yaml

### ISSUE THREAD

**Issue by kalmastenitin** [scylladb/scylladb#19216]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 6.0.0-0.20240606.a77615adf324
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker image

I have mounted yaml config file as described in [documentation](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/tips/best-practices-scylla-on-docker) --volume ~/master_scylla.yaml:/etc/scylla/scylla.yaml

and changed options listen_address: 0.0.0.0 broadcast_rpc_address: 10.0.0.5

but docker logs says  INFO  2024-06-10 13:23:24,093 [shard  0:stmt] cql_server_controller - Starting listening for CQL clients on 10.4.7.2:9042 (unencrypted, non-shard-aware) (docker network address)

if i pass 

```  scylla:
    image: scylladb/scylla
    volumes:
      - scylla-data:/var/lib/scylla
      - ./configs/scylla/master_scylla.yaml:/etc/scylla/scylla.yaml
    command: ["--listen-address=0.0.0.0","--broadcast-rpc-address=192.168.1.121"] # as command line arguments
    ports:
      - 7000-7001:7001-7001
      - 9042:9042
 ```
 in my docker compose file then it works.
 
INFO  2024-06-10 13:23:24,093 [shard  0:stmt] cql_server_controller - Starting listening for CQL clients on 0.0.0.0:9042 (unencrypted, non-shard-aware)

I saw some issue in scyllasetup.py file file only listen address is set only in arguments function.

I can solve this issue if not currently assigned to anyone.

**Comment by mykaul** [comment]
Looks like a Docker configuration issue to me. You expect Scylla to listen on a specific IP address, but you need to configure Docker to set this IP address to the Scylla container, no?

**Comment by kalmastenitin** [comment]
yes,
 I need to pass --listen-addresses as command line argument so Scylla should able to listen.
it should be change directly as soon as we mounted /etc/scylla/scylla.yaml file with listen_address to 0.0.0.0

**Comment by mykaul** [comment]
> yes, I need to pass --listen-addresses as command line argument so Scylla should able to listen. it should be change directly as soon as we mounted /etc/scylla/scylla.yaml file with listen_address to 0.0.0.0

I'm not sure if you are agreeing with me (that it's a docker configuration issue) or not.

**Comment by kalmastenitin** [comment]
yes @mykaul its docker configuration issue.

**Comment by mykaul** [comment]
Thanks for confirming, closing.
