### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#19225]
it would be handy if developer finds himself/herself facing a coredump and a build id. if scylla's compilation is deterministic, he/she can just checkout the given commit, and build it with the accompanied dbuild image, without pulling the executable.

the status quo is yet known. according to Botond, Jesse tried to make our builds deterministic. but we lose the track of the output of his initiative. so the first step is to understand if our builds are deterministic or not.
```[tasklist]
### Tasks
- [x] understand if our builds are deterministic or not.
- [x] compare the generated .o
```

**Comment by tchaikov** [comment]
tested with 3c921d57126ee6b879a81dd21ac8ec7ee640f951
```console
$ ./configure.py --mode dev --with scylla --compiler clang++ --disable-dpdk
$ ninja build/dev/scylla
$ mv build build.a
$ rm build.ninja
$ ./configure.py --mode dev --with scylla --compiler clang++ --disable-dpdk
$ ninja build/dev/scylla
$ md5sum ./build{.a,}/dev/scylla
7ed8f98d51b344429b532c5809635d3a  ./build.a/dev/scylla
e809ee148cbd86a5ec9862ae4191589a  ./build/dev/scylla
$ md5sum build{.a,}/SCYLLA-*-FILE
285386b0eebbbfc54ae2d52158ca746f  build.a/SCYLLA-PRODUCT-FILE
ef643d04845d225892e9cc04f8386e50  build.a/SCYLLA-RELEASE-FILE
298d2cdd2ab47f17e0970705cc35620b  build.a/SCYLLA-VERSION-FILE
285386b0eebbbfc54ae2d52158ca746f  build/SCYLLA-PRODUCT-FILE
ef643d04845d225892e9cc04f8386e50  build/SCYLLA-RELEASE-FILE
298d2cdd2ab47f17e0970705cc35620b  build/SCYLLA-VERSION-FILE
```

**Comment by tchaikov** [comment]
after comparing the md5sum of the .o and .a files of these two builds:
```diff
2d1
< 05e7143a6bef61a74c280e9284ea38c1  ./dev/rust-dev/build/link-cplusplus-3a8f69b5c1d28756/out/liblink-cplusplus.a
4a4
> 16d436f00cef7b47a63ed77a0a0fbc46  ./dev/rust-dev/build/wasmtime-runtime-e068acf5c9e4c9bc/out/libwasmtime-helpers.a
7a8
> 39a1767eb872491158a0e32048f1190a  ./dev/rust-dev/build/link-cplusplus-3a8f69b5c1d28756/out/liblink-cplusplus.a
9,11d9
< 46430904c649c567d6ca69b68dd422ea  ./dev/rust-dev/build/wasmtime-runtime-502f6160a3a0966f/out/libwasmtime-helpers.a
< 46f9fb17ed8060d7b5a557677387e5a0  ./dev/rust-dev/build/psm-429387796fc95832/out/libpsm_s.a
< 49a75848798cbfbfbc28629efcb7829a  ./dev/rust-dev/build/cxx-6b02df409529c4bc/out/libcxxbridge1.a
14a13,15
> 6799b9d71067e15dc6b97b6b955c6b85  ./dev/rust-dev/build/link-cplusplus-5700789b50f58487/out/liblink-cplusplus.a
> 6a2f77633ff4ef97b0a969fa5298063e  ./dev/rust-dev/deps/librust_combined-3d297b640bd5a479.a
> 6a2f77633ff4ef97b0a969fa5298063e  ./dev/rust-dev/librust_combined.a
20a22
> a3f104840658f5c286e33355e9854401  ./dev/rust-dev/build/cxx-6b02df409529c4bc/out/libcxxbridge1.a
22,23c24
< b4f9f2cad50b4f0f903fca91108e6640  ./dev/rust-dev/deps/librust_combined-0d1b156d4f0acc19.a
< b4f9f2cad50b4f0f903fca91108e6640  ./dev/rust-dev/librust_combined.a
---
> b2464742426d01450882d5cef2a9030d  ./dev/rust-dev/build/cxx-a666908e0f1fd069/out/libcxxbridge1.a
25a27
> bacd25903f0f602c328fbcf2b7da62d9  ./dev/rust-dev/build/wasmtime-runtime-502f6160a3a0966f/out/libwasmtime-helpers.a
26a29
> bef4cdb035d081a5ba36b76b4bf736ac  ./dev/rust-dev/build/psm-b87f320790518feb/out/libpsm_s.a
32a36
> f6105f1270ebd835cc319af687fb31fa  ./dev/rust-dev/build/psm-429387796fc95832/out/libpsm_s.a
```

**Comment by tchaikov** [comment]
so i think we should disable incremental build of rust code at least for release builds.

**Comment by tchaikov** [comment]
after disabling the incremental build of rust_combined project in `rust/Cargo.toml`, the generated `scylla` executables of two different builds are identical.
```console
$ md5sum build.a/dev/scylla 
59a4c31d4f7aa80643eba60903ff2ed8  build.a/dev/scylla
$ md5sum build.a/dev/scylla 
59a4c31d4f7aa80643eba60903ff2ed8  build.a/dev/scylla
```

**Comment by tchaikov** [comment]
@bhalevy @denesb @raphaelsc in case you are interested.

**Comment by nyh** [comment]
> it would be handy if developer finds himself/herself facing a coredump and a build id. if scylla's compilation is deterministic, he/she can just checkout the given commit, and build it with the accompanied dbuild image, without pulling the executable.

While I can understand the desire to do this, I don't understand the motivation. Why is "pulling the executable" a problem, given that we do save them?

**Comment by tchaikov** [comment]
@nyh in my case, my networking is very spotty, it could take hours to pull an relocatable tarball. YMMV. and i see that Raphael also had a similar needs the other day, but he didn't put the exact reason why. probably he chime in here.

**Comment by denesb** [comment]
We also don't currently keep and upload test executable from CI runs, so reproducible builds can come handy to debug problems that happen in CI.

**Comment by tchaikov** [comment]
> We also don't currently keep and upload test executable from CI runs, so reproducible builds can come handy to debug problems that happen in CI.

ahh, very true! it would be very helpful in this use case.

**Comment by raphaelsc** [comment]
can we do something to preserve this in the long run? like a test? perhaps there's an easier way to test it than comparing different builds? it seems to me that another dependency tomorrow could break this feature.

**Comment by tchaikov** [comment]
> can we do something to preserve this in the long run? like a test? perhaps there's an easier way to test it than comparing different builds? it seems to me that another dependency tomorrow could break this feature.

i can create a nightly job to build the tree twice and compare the md5sum of the generated `scylla` executables. does this make sense ?

**Comment by raphaelsc** [comment]
> > can we do something to preserve this in the long run? like a test? perhaps there's an easier way to test it than comparing different builds? it seems to me that another dependency tomorrow could break this feature.
> 
> i can create a nightly job to build the tree twice and compare the md5sum:s of the generated `scylla` executables. does this help ?

maybe it's enough to do it once a week. it's not like we'll add a dependency every day.

**Comment by tchaikov** [comment]
ack. will try to implement this tomorrow.
