### ISSUE TITLE
6.0.1/dtest-debug: test_no_read_amplification_on_repair fails on assert 732360 < ((2048 * 100) * 3)

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#19319]
https://jenkins.scylladb.com/job/scylla-6.0/job/dtest-debug/14/testReport/read_amplification_test/TestReadAmplification/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split018___test_no_read_amplification_on_repair/ 

```
        logger.info("Verify there is no read amplification on repair")
        node_ips = [cluster.get_node_ip(node_ind) for node_ind in range(1, len(nodes) + 1)]
        amplification_rate = 3
        max_val = {}
        metric_names = ["rx_row_bytes", "tx_row_bytes"]
        started = time.time()
        timeout = 600
        while not thr.done():
            bytes_total = self.get_metrics(metric_names, node_ips)
            for param in bytes_total:
>               assert 0 < bytes_total[param] < size * cnt * amplification_rate
E               assert 732360 < ((2048 * 100) * 3)

read_amplification_test.py:111: AssertionError
```
[test_no_read_amplification_on_repair_dtest-gw0.log](https://github.com/user-attachments/files/15857954/test_no_read_amplification_on_repair_dtest-gw0.log)
[test_no_read_amplification_on_repair_node1.log](https://github.com/user-attachments/files/15857955/test_no_read_amplification_on_repair_node1.log)
[test_no_read_amplification_on_repair_node2.log](https://github.com/user-attachments/files/15857956/test_no_read_amplification_on_repair_node2.log)
[test_no_read_amplification_on_repair_node3.log](https://github.com/user-attachments/files/15857957/test_no_read_amplification_on_repair_node3.log)
[test_no_read_amplification_on_repair_node4.log](https://github.com/user-attachments/files/15857958/test_no_read_amplification_on_repair_node4.log)

**Comment by mykaul** [comment]
@denesb - who can take a look at this, ensure it's not a 6.0.1 regression?

**Comment by denesb** [comment]
@Deexie please take a look.

**Comment by Deexie** [comment]
> @denesb - who can take a look at this, ensure it's not a 6.0.1 regression?

Definitely not a 6.0.1 regression. `branch-5.4` is also flaky on this test with even worse read amplification (`assert 1236394 < ((2048 * 100) * 3)`). 

There was a recent change to counting repair size (https://github.com/scylladb/scylladb/pull/17785) which was backported to 5.4, but it modified `rx_row_bytes` and `tx_row_bytes` in `repair_stats` and not in `row_level_repair_metrics` so it's unrelated.

In the test we have `amplification_rate = 3` while it actually equals to ~3,6. It looks arbitrarily (is it?). Maybe it's just too small for debug mode or 100kB data size?

The test was modified (data size) and added to gating a month ago (https://github.com/scylladb/scylla-dtest/pull/4163).
 
 Cc @dimakr

**Comment by mykaul** [comment]
> Definitely not a 6.0.1 regression. `branch-5.4` is also flaky on this test with even worse read amplification (`assert 1236394 < ((2048 * 100) * 3)`).

Odd - I usually look for open bugs before opening a new one. Might have missed it.

**Comment by Deexie** [comment]
> > Definitely not a 6.0.1 regression. `branch-5.4` is also flaky on this test with even worse read amplification (`assert 1236394 < ((2048 * 100) * 3)`).
> 
> Odd - I usually look for open bugs before opening a new one. Might have missed it.

No, no. It's not opened, I run the test locally on both master and 5.4

**Comment by Deexie** [comment]
> > > Definitely not a 6.0.1 regression. `branch-5.4` is also flaky on this test with even worse read amplification (`assert 1236394 < ((2048 * 100) * 3)`).
> > 
> > 
> > Odd - I usually look for open bugs before opening a new one. Might have missed it.
> 
> No, no. It's not opened, I run the test locally on both master and 5.4. Well, it's odd it wasn't caught then....

I just checked, it is not actually - the PR which modified and added the test to gating wasn't backported to 5.4
