### ISSUE TITLE
[centos9] install without setup of selinux fails on coredump configuration check

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#19325]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

Scylla can't finish setup on centos9 when `--no-selinux-setup` flag was used

```
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks --no-selinux-setup --swap-directory / '
Exit code: 1
Stdout:
Owner UID: 1000 (scylla-test)
Boot ID: 6f33cbb0b1bb448bbf0b72920cc40819
Machine ID: 3b0e2d5c20c14370a70a7f03c4dd1ea0
Hostname: artifacts-centos9-selinux-jenkins-db-node-d57fb40a-0-1
Storage: none
Message: Process 73647 (bash) of user 0 dumped core.
Does not able to detect coredump file, failed to configure systemd-coredump.
Your current Scylla release is 6.1.0~dev while the latest patch release is 6.0.0, update for the latest bug fixes and improvements
coredump setup failed.
Stderr:
Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /usr/lib/systemd/system/scylla-server.service.
Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-systemd-coredump.mount → /etc/systemd/system/var-lib-systemd-coredump.mount.
Created symlink /etc/systemd/system/scylla-server.service.wants/var-lib-systemd-coredump.mount → /etc/systemd/system/var-lib-systemd-coredump.mount.
```

## Impact

User that want to leave selinux enable, can install scylla on this distro

## How frequently does it reproduce?

100%

## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-centos9-selinux-jenkins-db-node-d57fb40a-0-1 (34.138.157.72 | 10.142.0.95) (shards: 2)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-9` (gce: undefined_region)

Test: `artifacts-centos9-selinux-test`
Test id: `d57fb40a-da00-4272-9346-4850107c0b0d`
Test name: `scylla-staging/fruch/artifacts-centos9-selinux-test`
Test config file(s):

- [centos9-selinux.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ea453de4edfbe2853750ea61131b1ef6d9087190/test-cases/artifacts/centos9-selinux.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d57fb40a-da00-4272-9346-4850107c0b0d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d57fb40a-da00-4272-9346-4850107c0b0d)
- Show all stored logs command: `$ hydra investigate show-logs d57fb40a-da00-4272-9346-4850107c0b0d`

## Logs:
- **db-cluster-d57fb40a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/db-cluster-d57fb40a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/db-cluster-d57fb40a.tar.gz)
- **sct-runner-events-d57fb40a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-runner-events-d57fb40a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-runner-events-d57fb40a.tar.gz)
- **sct-d57fb40a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-d57fb40a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-d57fb40a.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/artifacts-centos9-selinux-test/8/)
[Argus](https://argus.scylladb.com/test/f85b0648-41ce-46b0-80a8-f289d6a9b3ab/runs?additionalRuns[]=d57fb40a-da00-4272-9346-4850107c0b0d)
</details>

**Comment by syuu1228** [comment]
I guess this is GCE specific issue, since coludn't reproduce this on other clouds / local VMs, even I able to reproduce this on GCE.
Seems like missing SELinux rules is systemd-container-coredump, we can fix the issue by loading the rule & enable the rule.
PR opened at #19382

**Comment by fruch** [comment]
> I guess this is GCE specific issue, since coludn't reproduce this on other clouds / local VMs, even I able to reproduce this on GCE.
> Seems like missing SELinux rules is systemd-container-coredump, we can fix the issue by loading the rule & enable the rule.
> PR opened at #19382

FYI we only had such a test for centos8

So it might be like that in other distros as well, but we never test all of them.

It might be worth doing a sweep to see if it's not just centos9 suffering from this. (I.e. maybe the fix should be that exact on the distro version)

**Comment by syuu1228** [comment]
> FYI we only had such a test for centos8
> 
> So it might be like that in other distros as well, but we never test all of them.
> 
> It might be worth doing a sweep to see if it's not just centos9 suffering from this. (I.e. maybe the fix should be that exact on the distro version)

I checked on CentOS7/8/9, and I found that this is only happens on CentOS9 latest update.
https://github.com/scylladb/scylladb/pull/19382#issuecomment-2185705235

And it's not happen on Debian/Ubuntu since SELinux is not available on them.

**Comment by mykaul** [comment]
We should test on Rocky or Alma or RHEL, not CentOS and see if it happens. CentOS (Stream) is not a stable platform by definition.

**Comment by syuu1228** [comment]
> We should test on Rocky or Alma or RHEL, not CentOS and see if it happens. CentOS (Stream) is not a stable platform by definition.

I found that RHEL9 or RHEL9 compatible distro has systemd-252-32, the version doesn't affect this problem.
I guess systemd-252-33 - systemd-252-35 are only available on CentOS Stream 9, and maybe it means these versions are still testing before merging to RHEL.

**Comment by yaronkaikov** [comment]
@syuu1228 What is the next step here?

**Comment by syuu1228** [comment]
@yaronkaikov We decided to merge the patch (#19382) since the bug is only occur on beta version of RHEL9 variants.
If the issue keep happens on the artifact test, the test should change the distribution to rocky-9, alma-9 or rhel-9, not centos-stream-9.

**Comment by yaronkaikov** [comment]
So i assume this can be closed , right @syuu1228 ?

**Comment by yaronkaikov** [comment]
@syuu1228 based on @fruch comment in https://github.com/scylladb/scylla-cluster-tests/pull/8589#issuecomment-2337327506 it also happens in rocky9, please try to investigate this

**Comment by syuu1228** [comment]
This is also SELinux permission issue, but it's different issue than previous one.
On #19382, the problem was newly introduced "systemd-container-coredump" module is not loaded.
But on Rocky9 I can verify the module is actually loaded.

And when I checked audit log, I found that error reason is different than previous one:
```
type=PROCTITLE msg=audit(1725912691.082:963): proctitle="/usr/lib/systemd/systemd-coredump"
type=SYSCALL msg=audit(1725912691.082:963): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=56199b7f67d0 a2=a01c2 a3=1a0 items=0 ppid=1 pid=6636 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-coredum" exe="/usr/lib/systemd/systemd-coredump" subj=system_u:system_r:systemd_coredump_t:s0 key=(null)
type=AVC msg=audit(1725912691.082:963): avc:  denied  { write } for  pid=6636 comm="systemd-coredum" name="coredump" dev="nvme0n1" ino=131 scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=unconfined_u:object_r:unlabeled_t:s0 tclass=dir permissive=0
```
Seems like it says systemd-coredump does not have permission to write to /var/lib/scylla/coredump, and the security label is unlabeled_t.
The label name means /var/lib/scylla/coredump is not labeled correctly, and I can verify it doesn't:
```
$ ls -laZ
total 4
drwxr-xr-x.  8 scylla scylla system_u:object_r:unlabeled_t:s0      102 Sep  9 18:35 .
drwxr-xr-x. 29 root   root   system_u:object_r:var_lib_t:s0       4096 Sep  9 18:33 ..
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:unlabeled_t:s0    6 Sep  9 18:35 commitlog
drwxr-xr-x.  2 root   root   unconfined_u:object_r:unlabeled_t:s0    6 Sep  9 18:35 coredump
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:unlabeled_t:s0    6 Sep  9 18:35 data
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:unlabeled_t:s0    6 Sep  9 18:35 hints
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:unlabeled_t:s0    6 Sep  9 18:35 saved_caches
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:unlabeled_t:s0    6 Sep  9 18:35 view_hints
```
So I relabel it:
```
$ sudo restorecon -Rv .
Relabeled /var/lib/scylla from system_u:object_r:unlabeled_t:s0 to system_u:object_r:var_lib_t:s0
Relabeled /var/lib/scylla/coredump from unconfined_u:object_r:unlabeled_t:s0 to unconfined_u:object_r:var_lib_t:s0
Relabeled /var/lib/scylla/data from unconfined_u:object_r:unlabeled_t:s0 to unconfined_u:object_r:var_lib_t:s0
Relabeled /var/lib/scylla/commitlog from unconfined_u:object_r:unlabeled_t:s0 to unconfined_u:object_r:var_lib_t:s0
Relabeled /var/lib/scylla/hints from unconfined_u:object_r:unlabeled_t:s0 to unconfined_u:object_r:var_lib_t:s0
Relabeled /var/lib/scylla/view_hints from unconfined_u:object_r:unlabeled_t:s0 to unconfined_u:object_r:var_lib_t:s0
Relabeled /var/lib/scylla/saved_caches from unconfined_u:object_r:unlabeled_t:s0 to unconfined_u:object_r:var_lib_t:s0

$ ls -laZ
total 4
drwxr-xr-x.  8 scylla scylla system_u:object_r:var_lib_t:s0      102 Sep  9 18:35 .
drwxr-xr-x. 29 root   root   system_u:object_r:var_lib_t:s0     4096 Sep  9 18:33 ..
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:var_lib_t:s0    6 Sep  9 18:35 commitlog
drwxr-xr-x.  2 root   root   unconfined_u:object_r:var_lib_t:s0    6 Sep  9 18:35 coredump
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:var_lib_t:s0    6 Sep  9 18:35 data
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:var_lib_t:s0    6 Sep  9 18:35 hints
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:var_lib_t:s0    6 Sep  9 18:35 saved_caches
drwxr-xr-x.  2 scylla scylla unconfined_u:object_r:var_lib_t:s0    6 Sep  9 18:35 view_hints
```

Although, even after relabel I still get similar error: 

```
type=PROCTITLE msg=audit(1725913077.338:1253): proctitle="/usr/lib/systemd/systemd-coredump"
type=SYSCALL msg=audit(1725913077.338:1253): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=563394f16840 a2=a01c2 a3=1a0 items=0 ppid=1 pid=6793 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-coredum" exe="/usr/lib/systemd/systemd-coredump" subj=system_u:system_r:systemd_coredump_t:s0 key=(null)
type=AVC msg=audit(1725913077.338:1253): avc:  denied  { write } for  pid=6793 comm="systemd-coredum" name="coredump" dev="nvme0n1" ino=131 scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=unconfined_u:object_r:var_lib_t:s0 tclass=dir permissive=0
```
Seems like systemd-coredump does not have permission to write var_lib_t, it has to be same label as original directory /var/lib/systemd/coredump.

I found that /var/lib/systemd/coredump has systemd_coredump_var_lib_t:
```
$ ls -laZ /var/lib/systemd/
total 8
drwxr-xr-x.  7 root root system_u:object_r:init_var_lib_t:s0               98 Sep  3 18:41 .
drwxr-xr-x. 29 root root system_u:object_r:var_lib_t:s0                  4096 Sep  9 18:33 ..
drwxr-xr-x.  2 root root system_u:object_r:init_var_lib_t:s0               22 Sep  9 18:26 catalog
drwxr-xr-x.  2 root root system_u:object_r:systemd_coredump_var_lib_t:s0    6 Aug 15 12:29 coredump
drwxr-xr-x.  2 root root system_u:object_r:systemd_logind_var_lib_t:s0      6 Sep  9 08:10 linger
drwxr-xr-x.  2 root root system_u:object_r:systemd_pstore_var_lib_t:s0      6 Aug 15 12:32 pstore
-rw-------.  1 root root system_u:object_r:init_var_lib_t:s0             1024 Sep  9 18:29 random-seed
drwxr-xr-x.  2 root root system_u:object_r:init_var_lib_t:s0               68 Sep  9 08:10 timers
```

So I changed security label of /var/lib/scylla/coredump to systemd_coredump_var_lib_t:
```
$ sudo semanage fcontext -a -t systemd_coredump_var_lib_t "/var/lib/scylla/coredump(/.*)?"
$ cd /var/lib/scylla
$ sudo restorecon -R -v coredump/
Relabeled /var/lib/scylla/coredump from system_u:object_r:var_lib_t:s0 to system_u:object_r:systemd_coredump_var_lib_t:s0
```

After the change, scylla_coredump_setup just works:
```
$ sudo /opt/scylladb/scripts/scylla_coredump_setup 
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h
kernel.core_pipe_limit = 16
fs.suid_dumpable = 2
Generating coredump to test systemd-coredump...

PID: 8196 (bash)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-09-09 21:04:10 UTC (3s ago)
  Command Line: /bin/bash /tmp/tmp7bfsojgx
    Executable: /usr/bin/bash
 Control Group: /user.slice/user-1014.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1014.slice
       Session: 1
     Owner UID: 1014 (syuu)
       Boot ID: d60fcfb2c2b047d29c8cccbac5707221
    Machine ID: dae8d946712d42a3a7a9cbf1e15a0b68
      Hostname: takuya-rocky9-test1
       Storage: /var/lib/systemd/coredump/core.bash.0.d60fcfb2c2b047d29c8cccbac5707221.8196.1725915850000000.zst (present)
  Size on Disk: 44.6K
       Message: Process 8196 (bash) of user 0 dumped core.
                
                Stack trace of thread 8196:
                #0  0x00007f0e11a3e92b kill (libc.so.6 + 0x3e92b)
                #1  0x000055d56b768e89 kill_builtin (bash + 0xb1e89)
                #2  0x000055d56b708e29 execute_builtin.lto_priv.0 (bash + 0x51e29)
                #3  0x000055d56b70222d execute_simple_command (bash + 0x4b22d)
                #4  0x000055d56b7035aa execute_command_internal (bash + 0x4c5aa)
                #5  0x000055d56b705748 execute_command (bash + 0x4e748)
                #6  0x000055d56b6f7109 reader_loop (bash + 0x40109)
                #7  0x000055d56b6e897e main (bash + 0x3197e)
                #8  0x00007f0e11a29590 __libc_start_call_main (libc.so.6 + 0x29590)
                #9  0x00007f0e11a29640 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x29640)
                #10 0x000055d56b6e8d75 _start (bash + 0x31d75)
                ELF object binary architecture: AMD x86-64


systemd-coredump is working finely.
```

The problem is we don't apply correct security label under /var/lib/scylla, when we created RAID volume.
We probably need to add `sudo semanage fcontext` and `restorecon` to scylla_raid_setup.

Seems like our setup code never labeled /var/lib/scylla, same problem ocurr on older versions.
But seems like the permission error only occur on RHEL9, seems like this is new security policy, only available RHEL9.
On RHEL8, scylla_coredump_setup just works with unlabeled /var/lib/scylla.

Although, we shouldn't leave /var/lib/scylla unlabeled, it should be fix.
We may also need to consider to fixup existing /var/lib/scylla while package update.

**Comment by mykaul** [comment]
@syuu1228 - great summary - thanks! I believe you are right and we need to both label new and fix existing deployments on upgrade.

**Comment by syuu1228** [comment]
On https://github.com/scylladb/scylladb/pull/20528#issuecomment-2346359847,  I found that Rocky9 has two bug, first one: https://github.com/scylladb/scylladb/issues/19325#issue-2355992016 and second one: https://github.com/scylladb/scylladb/issues/19325#issuecomment-2339237015, so I opened new issue for the second one.

**Comment by mykaul** [comment]
@syuu1228 - what's the next step here? Does it work with other EL9 distros? Rocky 9 latest for example?

**Comment by yaronkaikov** [comment]
> @syuu1228 - what's the next step here? Does it work with other EL9 distros? Rocky 9 latest for example?

Waiting for https://github.com/scylladb/scylladb/pull/20528 to get merge

**Comment by syuu1228** [comment]
> @syuu1228 - what's the next step here? Does it work with other EL9 distros? Rocky 9 latest for example?

The next step is merge #20528. Then it fix on all EL9 distros.
