### ISSUE TITLE
batchlog: time to replay failed batches can explode as the batchlog table accumulats tombstones

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#19376]
The `system.batchlog` table has a partition for each batch that failed to complete. After finally applying the batch, the partition is deleted. Although the table has `gc_grace_second = 0`, tombstones can still accumulate in memory, because we don't purge partition tombstones from either the memtable or the cache. This can lead to the cache and memtable of this table to accumulate many thousands of even millions of tombstones, making batchlog replay very slow. We didn't notice this before, because we would only replay all failed batches on unbootstrap, which is rare and a heavy and slow operation on its own right already.
With repair-based tombstone-gc however, we do a full batchlog replay at the beginning of each repair, and now this extra delay is noticeable.

**Comment by michoecho** [comment]
> We didn't notice this before, because we would only replay all failed batches on unbootstrap, which is rare and a heavy and slow operation on its own right already.

Not quite. Even if there is no repair or unbootstrap happening, we still replay the batchlog every 60s. It happens in the background, and nothing *waits* for it, so it's hard to notice it without looking at the metrics, but it's still eating CPU.

**Comment by denesb** [comment]
Indeed, I only looked at external callers so didn't notice the replay loop.
