### ISSUE TITLE
Counter columns are supposedly broken with tablets, but Scylla allows that silently

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylladb#19449]
According to https://github.com/scylladb/scylladb/issues/18180, counters are one of the things which don't work correctly with tablets yet.

Other such things, such as LWT, are [rejected](https://github.com/scylladb/scylladb/issues/18066) on tablet-based keyspaces.

However, Scylla doesn't reject counters in tablet-based tables, and it doesn't even warn about them.

If counters-on-tablets truly don't work, then it probably shouldn't be possible to create counter columns in tablet-based keyspaces.

**Comment by bhalevy** [comment]
@ptrsmrn does that fall in your realm?

Cc @kostja

**Comment by nyh** [comment]
> However, Scylla doesn't reject counters in tablet-based tables, and it doesn't even warn about them.

If you want to improve the CREATE KEYSPACE warning message (among other things), please see https://github.com/scylladb/scylladb/issues/18876 on other edits it needs.
