### ISSUE TITLE
run off strategy compaction on all nodes after decommission in topology coordinator like we do with node ops

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#19460]
Node ops run off strategy compaction on all nodes after decommission as can be seen here: 4f0a1cbca3595069ee8999e57566227f18385594. There was probably a good reason to do so (was it?) so we should consider doing the same with the raft topology.

**Comment by kbr-scylla** [comment]
I'm having trouble assessing the priority of this

> There was probably a good reason to do so (was it?)

@asias or @raphaelsc could you provide some insight?

**Comment by kbr-scylla** [comment]
ping @asias @raphaelsc 

Could you explain if (why) we need to perform off strategy compation on all nodes after decommission?

**Comment by asias** [comment]
> ping @asias @raphaelsc
> 
> Could you explain if (why) we need to perform off strategy compation on all nodes after decommission?

It is not all nodes. It is all nodes that receiving data from decommission. The reason is that we need to trigger off strategy when there is no more incoming data so the off strategy could start.

Later, we added automatic trigger (off strategy triggered after some timeout if no data is received from streaming) support. After that, the trigger in decommission_done is not mandatory but an optimization.

**Comment by gleb-cloudius** [comment]
> > ping @asias @raphaelsc
> > Could you explain if (why) we need to perform off strategy compation on all nodes after decommission?
> 
> It is not all nodes. It is all nodes that receiving data from decommission. The reason is that we need to trigger off strategy when there is no more incoming data so the off strategy could start.

Why do we need it to start?

> 
> Later, we added automatic trigger (off strategy triggered after some timeout if no data is received from streaming) support. After that, the trigger in decommission_done is not mandatory but an optimization.

IOW raft topology may not copy nodeops here and the issue can be closed, right?

**Comment by asias** [comment]
> > > ping @asias @raphaelsc
> > > Could you explain if (why) we need to perform off strategy compation on all nodes after decommission?
> > 
> > 
> > It is not all nodes. It is all nodes that receiving data from decommission. The reason is that we need to trigger off strategy when there is no more incoming data so the off strategy could start.
> 
> Why do we need it to start?

Otherwise, the sstables stay in off strategy compaction set forever.

> 
> > Later, we added automatic trigger (off strategy triggered after some timeout if no data is received from streaming) support. After that, the trigger in decommission_done is not mandatory but an optimization.
> 
> IOW raft topology may not copy nodeops here and the issue can be closed, right?

Yes. I think so.
