### ISSUE TITLE
Tests / dtest / lwt_schema_modification_test.TestLWTSchemaModification.test_materialized_view failed

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#19476]
```
Stacktrace

self = <lwt_schema_modification_test.TestLWTSchemaModification object at 0x7ff956c0e480>

    def test_materialized_view(self):
>       self._test_combine([LWTLoad(row_start=1001, row_end=9999), MaterializedView(row_max=1000)], nrows=10000, loops=1, run_s=10)

lwt_schema_modification_test.py:594: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lwt_schema_modification_test.py:523: in _test_combine
    thread.result()
/usr/local/lib/python3.12/concurrent/futures/_base.py:449: in result
    return self.__get_result()
/usr/local/lib/python3.12/concurrent/futures/_base.py:401: in __get_result
    raise self._exception
/usr/local/lib/python3.12/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
lwt_schema_modification_test.py:472: in _action_thread
    action.run(session, stop, start_event, end_event)  # Hand over control to action
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <lwt_schema_modification_test.MaterializedView object at 0x7ff9146f17c0>
session = <cassandra.cluster.Session object at 0x7ff90fdb86e0>
stop = <threading.Event at 0x7ff91467a120: set>, start_event = None
end_event = None

    def run(self, session, stop, start_event, end_event):
        if start_event:
            start_event.wait()  # Wait for other action to signal done
    
        # Create view *ascending* so top rows are untouched
        session.execute(
            """
                CREATE MATERIALIZED VIEW table1_top_v_view AS
                    SELECT pk, ck, v FROM table1
                    WHERE ck IS NOT NULL
                    PRIMARY KEY (pk, ck)
                    WITH CLUSTERING ORDER BY (ck ASC)
                """
        )
    
        select_cql = "SELECT pk, ck, v FROM table1_top_v_view LIMIT %i" % (self.row_max)
        select_stmt = session.prepare(select_cql)
        select_stmt.consistency_level = ConsistencyLevel.ALL
        rows_expected = listify(sorted(session.execute(select_stmt).current_rows))
    
        while not stop.is_set():
            rows = listify(sorted(session.execute(select_stmt).current_rows))
>           assert rows == rows_expected
```
[assertion-error.txt](https://github.com/user-attachments/files/15966620/assertion-error.txt)

I don't know who to ping for this, it involves LWT and MV, so I guess @kbr-scylla and @nyh.

**Comment by nyh** [comment]
I can't make any sense out of this test, but it is an old test that @juliayakovlev wrote in 2021 so why did it start failing now? Or was it just a fluke? How many times has this test failed in the past?

The description of MaterializedView in that test doesn't match the code - it says "drop an existing index and add it again", but it doesn't do this - it just creates a materialized view and never drops it. After creating the materialized view, the test (again, MaterializedView class) seems to repeatedly perform the same read request on the table, stopping after the first page in each read (why?) - and asserting that it always gets the same results. But why should it? You can't read from a view immediately after adding it and then expect to see all the data! So it's not surprising the read result changed... To make things even more bizarre, this test seems to do LWT writes in the background (?) so these change the data as well. The test comments that it creates the view "so top rows are untouched" but I have no idea what this means.  The full assertion message (thanks to @fruch for converting dtest to pytest so we get good assertion messages, and thanks to @denesb for finding it) shows a diff like:
```
[
E                [[5, 5, 5],
E                 [23, 23, 23],
E                 [28, 28, 28],
E                 [33, 33, 33],
E                 [53, 53, 53],
E                 [55, 55, 55],
E             +   [91, 91, 91],
E                 [105, 105, 105],
E             +   [110, 110, 110],
E                 [114, 114, 114],
E                 [117, 117, 117],
E                 [120, 120, 120],
....
E                 [913, 913, 913],
E                 [914, 914, 914],
E                 [919, 919, 919],
E                 [925, 925, 925],
E                 [935, 935, 935],
E                 [948, 948, 948],
E             -   [959, 959, 959],
E                 [960, 960, 960],
E                 [976, 976, 976],
E                 [987, 987, 987],
E                 [998, 998, 998],
E                 [1009, 1009, 1009],
....
```
I don't know what to make of this. I don't want to waste any more time trying to reverse-engineer what this test does before someone can help me find evidence that this test never failed before.

Note that this test only runs without tablets (LWT is not supported with tablets), so it's not a new tablets regression.

**Comment by fruch** [comment]
this is the orignial test:
https://github.com/scylladb/scylla-dtest/commit/aa1f952f78fbfdea62586143b1c415a613bd14bc

@juliayakovlev is the one translated it to pytest

it happened 5 times in 2 years (3 in debug jobs): 
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/6119c6b0-32ea-11ef-81c7-3986d18dafd5

I your guess about the paging sounds like a possible thing. 

but doesn't seems to be that easily reproducible

**Comment by kostja** [comment]
@temichus Let's discuss and possibly rewrite (I remember the idea of the test - at the time I wasn't aware how broken MVs are).

**Comment by temichus** [comment]
according to a discussion with @kostja, the following changes/checks need to be added in MaterializedView class
1 work with sinc MV
2 add view build status check
3 wait for the base table has min 10 lines
4 Add "order by pk" in select

**Comment by temichus** [comment]
> according to a discussion with [@kostja](https://github.com/kostja), the following changes/checks need to be added in MaterializedView class 1 work with sinc MV 2 add view build status check 3 wait for the base table has min 10 lines 4 Add "order by pk" in select

added PR with following changes:

1 Now test work with synchronous_updates MV
2 "nodetool viewbuildstatus" check was added to make sure that MV built
3 wait for the MV populated by self.row_max before first SELECT

note:  'Add "order by pk" in select' is not needed due to MV itself already has ordering " ``` WITH CLUSTERING ORDER BY (ck ASC)```

**Comment by mykaul** [comment]
synchronous updates is great to test with, but it's not the default and not what I'd imagine 99% of our users use.

**Comment by temichus** [comment]
> synchronous updates is great to test with, but it's not the default and not what I'd imagine 99% of our users use.

but there is no mechanism to check that MV synced(at least I don't know such). But this check is a must-have for this test stability, otherwise, it will be unstable
