### ISSUE TITLE
[bitnami/scylladb] --smp argument doesn't work with scylla binary

### ISSUE THREAD

**Issue by nahimr** [scylladb/scylladb#19490]
*Installation details*
Scylla version (or git commit hash): 6.0.1
Cluster size: Single Node base on K3S using LongHorn
OS (RHEL/CentOS/Ubuntu/AWS AMI): Rocky Linux

Recently, I have installed scylla on K3S cluster with the bitnami image, I used the --smp argument but it doesn't work, I would like to decrease usage of cpu cores, if you have any ideas how to perform this with bitnami, please let me know !

**Comment by mykaul** [comment]
I think this question should be forwarded to Bitnami, we do not deploy or manage their (helm?) charts (or whatever they use to manage a Scylla cluster)
