### ISSUE TITLE
tablet_sstable_set copy ctor does not copy _sstable_set_ids

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#19519]
Commit 9f93dd9fa3376cfe560c65fb9c9c938ff1d3f99d changed `tablet_sstable_set::_sstable_sets` to be a `absl::flat_hash_map` and in addition, `std::set<size_t> _sstable_set_ids` was added (Used when ordering is required for correctness).

`_sstable_set_ids` is set up in the `tablet_sstable_set(schema_ptr s, const storage_group_manager& sgm, const locator::tablet_map& tmap)` constructor, but it is not copied in `tablet_sstable_set(const tablet_sstable_set& o)`.

* Requires backport to 6.0

**Comment by bhalevy** [comment]
Let's also add a unit test that catches the issue, since the existing unit tests apparently don't cover it.

**Comment by denesb** [comment]
@raphaelsc @bhalevy is the P0 justified here? I understood that the problem is benign (but we should still fix it).

**Comment by bhalevy** [comment]
If there is no code path exercising the copy constructor for the table sstable_set then we can demote priority
