### ISSUE TITLE
Make sure S3 part upload is idempotent

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#19534]
A theory: when issuing PUT /object?partNumber=i request server may (?) write the object, but fail to return us the response with success status. If the failure renders into transport error (connection closed by server) , seastar will try replay the request again.

refs: #19533
refs: #19461

note: this is likely not a problem, re-sending the part again successfully overwrites it, but we still need a test proving it

**Comment by kreuzerkrieg** [comment]
It is clearly stated in the AWS S3 [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html)

> If you upload a new part using the same part number as a previously uploaded part, the previously uploaded part is overwritten.

**Comment by regevran** [comment]
>but we still need a test proving it

:point_up:

**Comment by kreuzerkrieg** [comment]
> > but we still need a test proving it
> 
> ☝️

Disagree. What are you planning to test AWS SDK?

**Comment by xemul** [comment]
It's not that simple. I admit that PUT-ing a part is replayable, but what if CreateMultipartUpload or, which seems worse, the CompleteMultipartUpload is replayed? Third option -- AbortMultipartUpload can also be replayed.

**Comment by kreuzerkrieg** [comment]
It has another issue mentioning CompleteMultipartUpload
https://github.com/scylladb/scylladb/issues/19533

**Comment by kreuzerkrieg** [comment]
Ok, closing this issue as discussed with @xemul
