### ISSUE TITLE
Raft_group0 - failed to modify config when rebuild more than one node using replace_node_first_boot

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylladb#19537]
Here I tested the parameter  replace_node_first_boot in a three nodes cluster, the following is my args added to /etc/scylla/scylla.yaml
```
replace_address_first_boot: 95eb7456-3d14-4ba9-818b-3347a50a38e1
enable_repair_based_node_ops: true
ignore_dead_nodes_for_replace: cc5428c3-7569-420b-bd25-96356d843a09
```
raid created and mounted  successfully , but scylla got stuck in loop , logs  as

```
raft_group0 - failed to modify config at peer 147d1149-b095-4a4f-8f5d-b895d54baeb1: seastar::rpc::timeout_error (rpc call timed out). Retrying.
```
The live node is healthy. And host_id is replaced
```
# nodetool gossipinfo
/.......
  generation:1719556289
  heartbeat:61
  SCHEMA:333be05c-43b3-321b-adc1-678e84d4721b
  NET_VERSION:0
  HOST_ID:cd09a5e9-386a-4bbf-88c0-5e776d1bfc41
```

Then I tried nodetool removenode --ignore-dead-nodes <host_id of DN node> <host_id of DN node to remove>
```
api - remove_node: host_id=cd09a5e9-386a-4bbf-88c0-5e776d1bfc41 ignore_nodes={10.235.195.72}
[shard  0] raft_group0 - Performing a group 0 read barrier...
[shard  0] cdc - Could not update CDC description table with generation (2024/06/28 02:28:29, 67302ef8-73f3-4565-91e2-[shard  0] cdc - Could not update CDC description table with generation (2024/06/28 02:28:29, 67302ef8-73f3-4565-91e2-9134a9d8fae4): exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1). Will try again.
[shard  2] raft_group_registry - (rate limiting dropped 2999 similar messages) Raft server id 95eb7456-3d14-4ba9-818b-3347a50a38e1 cannot be translated to an IP address.
```

As u can see, `95eb7456-3d14-4ba9-818b-3347a50a38e1` is the host_id of the node before rebuild

*Installation details*
Scylla version : 5.2.18
Cluster size: 3

**Comment by qiuqiu-007** [comment]
It is get in stuck with chaos raft id, and fixed by remove them.

**Comment by kostja** [comment]
Please provide a full list of steps to reproduce the problem: the size of the cluster, the steps performed during replace, and so on.
Did you try using 5.4 instead?

**Comment by qiuqiu-007** [comment]
It is because that I did not clear the host-id of the first time to rebuild a node, which is failed, then the raft group remembered the new server id, but it not rebuild succesfullly. At the same time, I retried to rebuild node using the old host-id, then it occurred the log info like above descripped. 

Finnally, I used `nodetool removenode <null-server-id>`, then the cluster becomes normal and rebuild greatly faster.

**Comment by mykaul** [comment]
> It is because that I did not clear the host-id of the first time to rebuild a node, which got failed, then the raft group remembered the new server id, but it did not rebuild successfully. At the same time, I retried to rebuild node using the old host-id, then it occurred the log info like above description.
> 
> Finnally, I use `nodetool removenode <null-server-id>`, then the cluster becomes normal and rebuild greatly faster.

Thanks @qiuqiu-007 for the update - can we close the issue then?

**Comment by qiuqiu-007** [comment]
Done
