### ISSUE TITLE
docs: Issue on page Data Distribution with Tablets

### ISSUE THREAD

**Issue by Alex-Covecube** [scylladb/scylladb#19582]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-6.0/architecture/tablets

### Problem

According to Google Gemini Advanced:

(https://g.co/gemini/share/e22f4c84f55d)

In ScyllaDB 6.0, tablets do not have to contain whole partitions. Partitions can be split across multiple tablets. This is a key advantage of the tablet design, as it allows for more flexibility and granular control over data distribution.

Here's how it works:

1. Partition Splitting: When a partition grows beyond a certain size, it can be split into smaller chunks called "splits."
2. Tablet Assignment: These splits are then assigned to different tablets, which can be distributed across the cluster for better load balancing and performance.
3. Dynamic Adjustment: The system can dynamically adjust the number and size of tablets as needed, based on the growth and distribution of data.

This means that even if you have large partitions, the tablet system can break them down into smaller, more manageable units, helping to mitigate some of the challenges associated with large partitions.

###  Suggest a fix

This is a pretty important aspect of tablets. Consider adding detailed documentation on how partition splitting across multiple tablets works to that page.

**Comment by tzach** [comment]
Google Gemini Advanced is wrong.
In ScyllaDB, a partition can not stretch more than one tablet.
Note that each DB has a different definition of Partition, Tablet.

**Comment by bhalevy** [comment]
But it's a gallant attempt I must say

**Comment by tzach** [comment]
Closing. We can revisit if and when Scylla would support this feature.
