### ISSUE TITLE
storage_proxy: LWT contention metric is not initialized

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylladb#19654]
The LWT contention metric is counted by a stack variable that is never initialized. This makes the metric show rubbish numbers.

**Comment by kbr-scylla** [comment]
Fixed by 691e24515290e257ec788bfc0ec0d3e54cab31ad

**Comment by avikivity** [comment]
So the effect is only on metrics? Not on actual execution?

I guess only the derivative is displayed, so no one ever noticed.

**Comment by wprzytula** [comment]
> So the effect is only on metrics? Not on actual execution?

Correct.
