### ISSUE TITLE
Default ScyllaDB loglevel can't be changed in containers

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylladb#19660]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
`Scylla version 6.0.1-0.20240612.bc89aac9d017 with build-id e845b7c6530ae1385e7bb3b7def09b4ffdf191c2`
Cluster size:
1
OS (RHEL/CentOS/Ubuntu/AWS AMI):
ScyllaDB Container Image (`docker.io/scylladb/scylla:6.0.1`)

In `/etc/default/scylla-server` the ScyllaDB startup scripts have hard wired
`SCYLLA_ARGS="--log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix"`
which makes it "impossible" for the loglevel to be adjusted by the user.
That later makes is into `/opt/scylladb/supervisor/scylla-server.sh`
`execsudo /usr/bin/env SCYLLA_HOME=$SCYLLA_HOME SCYLLA_CONF=$SCYLLA_CONF "$bindir"/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET $SCYLLA_DOCKER_ARGS`
but because the flag is already used once, and ScyllaDB doesn't allow redefining it :(, the `$SCYLLA_DOCKER_ARGS` won't help.

From [the docs](https://opensource.docs.scylladb.com/stable/troubleshooting/log-level.html) it also looks like `info` is the default so maybe it shouldn't be there at all.

```
Scylla version 6.0.1-0.20240612.bc89aac9d017 with build-id e845b7c6530ae1385e7bb3b7def09b4ffdf191c2 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --smp 1 --overprovisioned --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=10.85.5.102 --broadcast-address 10.85.5.102 --broadcast-rpc-address 10.85.5.102 --alternator-address 0.0.0.0 --blocked-reactor-notify-ms 999999999 --default-log-level=trace --prometheus-address=0.0.0.0"
pid: 58
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, smp, (positional) 1, overprovisioned, listen-address: 0.0.0.0, rpc-address: 0.0.0.0, seed-provider-parameters: seeds=10.85.5.102, broadcast-address: 10.85.5.102, broadcast-rpc-address: 10.85.5.102, alternator-address: 0.0.0.0, blocked-reactor-notify-ms, (positional) 999999999, default-log-level: trace, prometheus-address: 0.0.0.0]
error: option '--default-log-level' cannot be specified more than once

Try --help.
```

**Comment by mykaul** [comment]
@yaronkaikov - does that belong to your team?

**Comment by yaronkaikov** [comment]
> @yaronkaikov - does that belong to your team?

We probably can handle this, although i guess anyone can do it ;-)

**Comment by tnozicka** [comment]
I've send a PR to drop the flag https://github.com/scylladb/scylladb/pull/19671

**Comment by tzach** [comment]
The fix was merged. Not sure why this issue was not closed automatically.

**Comment by tnozicka** [comment]
despite the status https://github.com/scylladb/scylladb/pull/19671 actually landed so closing
