### ISSUE TITLE
Assertion fails when truncating table during migration

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#19707]
When a node is truncated during tablet migration, this error can happen:

```
INFO  2024-07-11 05:05:28,594 [shard 0: gms] database - Dropping test.test without snapshot
INFO  2024-07-11 05:05:28,594 [shard 0: gms] database - Truncating test.test without snapshot
ERROR 2024-07-11 05:05:28,594 [shard 0: gms] on_internal_error - compaction not disabled on table test.test during TRUNCATE
```

this is probably a race between tablet cleanup and truncate, where the latter expects compaction to be completely disabled, but compaction group stopped during cleanup will cause check in table::discard_sstables() to fail.

the synchronization of tablet migration and truncate might be the real fix (https://github.com/scylladb/scylladb/issues/16411).

link to logs: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10340/artifact/testlog/x86_64/dev/failed_test/test_tablet_drain_failure_during_decommission.5/

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/pull/20159#issuecomment-2291007689 has a good analysis of the issue. @bhalevy - does it make sense to crash, rather than err out and not truncate? (or is it just in debug mode that we crash on internal error? )

**Comment by bhalevy** [comment]
> [#20159 (comment)](https://github.com/scylladb/scylladb/pull/20159#issuecomment-2291007689) has a good analysis of the issue. @bhalevy - does it make sense to crash, rather than err out and not truncate? (or is it just in debug mode that we crash on internal error? )

We abort on internal errors using a configurable option that is enabled in testing, but disabled in production by default.
So on_internal_error will throw an error rather than crash in production.
