### ISSUE TITLE
Major compaction should check only the compacted sstables for the purpose of tombstone garbage collection

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#19728]
Currently, major compaction, as regular compaction, checks the presence of potentially shadowed data in the memtable and commitlog, even after flushing all tables (see scylladb/scylladb#15820 / 3ed6925673dea88a5fe157f6239b98d60ec1690a).

Flushing all tables ensures that anything present in the memtable is flushed and added to the compacted sstable set,
and that the commitlog is sync'ed, to prevent resurrection of shadowed data due to node restart.

Checking the memtable, commitlog, and any uncompacted sstable for data shadowing is therefore complimentary (and even somewhat paranoid :)).

Conflicting writes with backdated data, can happen right after checking the memtable and commitlog,
and since we cannot hold on to the garbage-collectible tombstones forever, we must draw a line somewhere, and setting that line at the time major compaction is as good as setting it at a any time after that, when a particular tombstone is about to be purged.

It is important to keep in mind that the garbage-collectible tombstones already check for two criteria for eligibility:
a. The tombstone_gc mode-based check (like being older than gc_grace_seconds, or the last successful repair rime, for example)
b. They do not possibly shadow any data in any other sstables in the compacted sstable set

The motivation for this requested change comes from particular workloads with materialized views that cause backdated data or shadowable row tombstones to be written to the memtable as part of view updates.
Those inhibit tombstone garbage collection in the view, that may already have a large number of shadowable tombstones that are created view updates whenever a column that is part of the view's primary key is updated.

For the materialized views use case, the tombstone_gc repair-mode eligibility also depends on the admin or scylla-manager repairing the view tables only after the base table is successfully repaired and consequential view-update-generation also completes successfully (See https://github.com/scylladb/scylladb/issues/19727).

**Comment by bhalevy** [comment]
@denesb please assign

**Comment by bhalevy** [comment]
Cc @tgrabiec

**Comment by denesb** [comment]
We need one more thing: we have customer workloads that also use backdated writes and we need to keep supporting these and not resurrect their data. So in the case of `tombstone_gc=repair`, we need to add a further option, a GC grace period, so that a tombstone is garbage-collected if:
1) `deletion_time + gc_grace_seconds < gc_clock::now()`
2) `deletion_time < last_repair_time`
3) no overlap detected (omitted for the proposed special major)

This is to prevent a freshly written tombstone, being immediately collected if it is quickly followed by a repair. The `gc_grace_seconds` can be 0 by default. Note that current `tombstone_gc` implementation is already prone to this problem.

**Comment by raphaelsc** [comment]
@denesb I think we already have a grace period for repair mode, which is propagation_delay_in_seconds (defaults to 1h).

```
            min_gc_before = check_min(s, saturating_subtract(min_repair_timestamp, propagation_delay));
            max_gc_before = check_min(s, saturating_subtract(max_repair_timestamp, propagation_delay));
```

**Comment by denesb** [comment]
Ah, great. Then we are good to go to implement this.

The remaining question is: do we want this new behavior to be enabled via a flag? So by default the old behavior is used?

**Comment by mykaul** [comment]
> Ah, great. Then we are good to go to implement this.
> 
> The remaining question is: do we want this new behavior to be enabled via a flag? So by default the old behavior is used?

I hate to say it, but probably with a flag.
