### ISSUE TITLE
[QUESTION] How to create a table with 2 primary keys and 0 clustering keys?

### ISSUE THREAD

**Issue by mojixcoder** [scylladb/scylladb#19732]
Hello all,
In the tutorials provided in the scylla university, it says that it is possible to have one or more primary keys and 0 or more clustering keys.

In the example provided for compound keys in scylladb you can define a table like this:
```
CREATE TABLE heartrate_v1 (
   pet_chip_id uuid,
   time timestamp,
   heart_rate int,
   PRIMARY KEY (pet_chip_id, time)
);
```
In this example, it creates a table with a primary key with `pet_chip_id` and with a clustering key on `time` column.

I have two questions:
1) How can I make `time` to be part of the primary key not clustering key?
2) Why can I have two rows with the same `pet_chip_id` but different `time`? Since time is part of the clustering key and is only used for sorting, why is it also used for identifying rows like primary keys? 

Thank you so much

**Comment by mykaul** [comment]
Can you please re-ask the question @ https://forum.scylladb.com/ ? GH issues are not for questions, but for code issues.

**Comment by mykaul** [comment]
CC @guy9 - maybe we can improve the example in Scylla Uni.

**Comment by mojixcoder** [comment]
Thanks,
Here is the question link if anyone wants to answer: https://forum.scylladb.com/t/how-to-create-a-table-with-2-primary-keys-and-0-clustering-keys/2303
