### ISSUE TITLE
cql: CREATE tablets KS allowed with tablets disabled in config

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#19744]
If tablets are disabled in `scylla.yaml`:
```
# This enables tablets on newly created keyspaces
enable_tablets: false
```
but a KS is CREATEd with tablets turned on:
```
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3} AND tablets = {'enabled': true, 'initial': 8};

Warnings :
SimpleStrategy replication class is not recommended, but was used for keyspace ks. You may suppress this warning by delisting SimpleStrategy from replication_strategy_warn_list configuration option, or make it into an error by listing this replication strategy on replication_strategy_fail_list.
```
Scylla is creating such a KS without any warning nor error. Unaware users may proceed thinking every table within this KS works on top of tablets.
The above example is also wrong for another reason, mainly - SimpleStrategy is not supported for tablets.

**Comment by bhalevy** [comment]
Is the keyspace actually created with tablets, or is the option simply ignored?
What happens when trying to create a table?

**Comment by ptrsmrn** [comment]
> The above example is also wrong for another reason, mainly - SimpleStrategy is not supported for tablets.

This is addressed here: https://github.com/scylladb/scylladb/issues/19743

**Comment by ptrsmrn** [comment]
I misunderstood the `enable_tablets` parameter, the `scylla.yaml` reads:
> When enabled, newly created keyspaces will have tablets enabled by default

So it just controls the default. I re-checked manually, and everything's fine.

**Comment by ptrsmrn** [comment]
Actually, the behavior of this flag isn't symmetrical:
1. if `enable_tablets: true` and we CREATE KS:
a) without specifying tablets options, it has tablets
b) specifying that tablets are enabled, it has tablets
c) specifying that tablets are disabled, it doesn't have tablets
2. but if `enable_tablets: false` and we CREATE KS:
a) without specifying tablets options, it doesn't have tablets
b) specifying that tablets are enabled, we get an error: "ConfigurationException: Tablet replication is not enabled"

So this flag actually does 2 things:
1. enables tablets feature, so that users can create keyspaces with tablets
2. makes tablets the default option for keyspaces.

**Comment by ptrsmrn** [comment]
I rechecked the steps from the description and the issue doesn't exist:
```
cqlsh> select * from system.config where name = 'enable_tablets';

 name           | source | type | value
----------------+--------+------+-------
 enable_tablets | config | bool | false

(1 rows)
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND tablets = {'enabled': true, 'initial': 8};
ConfigurationException: Tablet replication is not enabled
