### ISSUE TITLE
raft: replacing node should never create its own group0

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#19751]
Use 5.4 or any derived enterprise version.

How to reproduce:
0) Set up a cluster of 3 nodes
1) Create a scylla.yaml in which seed: self, but replace_address/replace_node_first_boot are also set and are pointing at an existing cluster node
2) Start a replacing node with this scylla.yalm
3) Observe that the node is running replace successfully but lives within its own group0.

How to fix:
If replace_address is provided, include it into the seed list.

**Comment by dorlaor** [comment]
Is the issue about preventing this and rejecting the configuration?

**Comment by kbr-scylla** [comment]
>  If replace_address is provided, include it into the seed list.

That doesn't make sense, because the replaced node is dead.
We can reject this config -- a proper seed must be provided (a healthy node in the cluster)

**Comment by kostja** [comment]
@kbr-scylla indeed. then I don't get how people could end up assembling a wholesome gossip cluster with disjoint raft clusters. let's get back to this issue after more fact checking (aka the logs).

**Comment by kbr-scylla** [comment]
> Create a scylla.yaml in which seed: self, but replace_address/replace_node_first_boot are also set and are pointing at an existing cluster node

I tried to reproduce your scenario, and the replacing node got:
```
INFO  2024-08-01 13:44:38,319 [shard 0:main] init - seeds={127.0.0.13}, listen_address=127.0.0.13, broadcast_address=127.0.0.13 
ERROR 2024-08-01 13:44:38,319 [shard 0:main] init - Bad configuration: replace-address and replace-address-first-boot are not allowed for seed nodes
...
ERROR 2024-08-01 13:44:38,661 [shard 0:main] init - Startup failed: bad_configuration_error (std::exception)
```

so it looks like it's already impossible.

**Comment by kbr-scylla** [comment]
Used `Scylla version 5.4.10-0.20240801.58377036b075 with build-id 55af00bd388dcc5a91cb644b47f44f7b6c38181e`

**Comment by kbr-scylla** [comment]
> indeed. then I don't get how people could end up assembling a wholesome gossip cluster with disjoint raft clusters.

How do we know that they managed to assemble a "wholesome gossip cluster" though? Maybe they just thought they had a single cluster, but in reality, these were 2 separate clusters all the time.

**Comment by kbr-scylla** [comment]
Ah, well.

In 2023.1 it is possible to assemble a wholesome gossip cluster with separate Raft groups:
just start two separate clusters, and then shut down one of them, set seeds to point at the other, and restart.

This is not possible in 2024.1 due to 0bff96a61140529cdbf012ffd02286e70fa84094

**Comment by kostja** [comment]
Then I guess nothing needs to be done here, @vladzcloudius
