### ISSUE TITLE
co-routinize `do_write_sst()` in `test/boost/sstable_test.cc`

### ISSUE THREAD

**Issue by lersek** [scylladb/scylladb#19803]
@bhalevy [suggests](https://github.com/scylladb/scylladb/pull/19624#discussion_r1682984688) coroutinizing `do_write_sst()` in `test/boost/sstable_test.cc` @ commit 21c67a5a649f.

Investigate whether the rest of the file could / should be coroutinized, as well.

Backporting should not be necessary; this change is supposed to be purely refactoring, for readability's sake (and for easier future modifications).

**Comment by lersek** [comment]
> Investigate whether the rest of the file could / should be coroutinized, as well.

This is proving very convoluted. Several test cases in `test/boost/sstable_test.cc` deeply nest cleanup wrappers and other kinds of wrappers, such as `do_with`, `do_with_async`, `defer`, `finally` and so on. I've expanded / open coded a few of the simpler ones (for co-routinizing them), but it's already leading to a code size explosion, in particular related to exception nesting.

I've also gotten the impression that seastar / scylladb uses multiple *competing* patterns for deferred cleanup; it's hard to navigate them.

For now I'll only submit a patch for `do_write_sst()`.

**Comment by avikivity** [comment]
For tests, converting to seastar::thread might be easier since exception handling in threads is natural.

**Comment by lersek** [comment]
@avikivity 

> For tests, converting to seastar::thread might be easier since exception handling in threads is natural.

(I didn't mean to ignore this comment; I just didn't see it before submitting #19937.)

I have now read up on `seastar::thread` here: https://github.com/scylladb/seastar/blob/master/doc/tutorial.md#seastarthread

I get the impression that this won't help. Namely, `seastar::thread` seems to enable a programming style where `future::get()` is preempted in case it blocked. But (I think) `co_await` offers exactly the same imperative style already (although `seastar::thread` may predate coroutine support).

The problem is nesting exceptions during cleanup, and that's orthogonal to the above.

For example, consider `test_env::do_with()` in `test/lib/sstable_test_env.hh`. It constructs a `test_env` instance, runs the input lambda futurized, and chains `env.stop()` to the end, with `future::finally()`. The complication is the exception handling by `future::finally()`: if both the input lambda and `env.stop()` throw, then `future::finally()` collects both exceptions into a `seastar::nested_exception`. Reimplementing that, with either `co_await`, or -- equivalently -- with `seastar:thread`, is a mess:

```
diff --git a/test/boost/sstable_test.cc b/test/boost/sstable_test.cc
index 32ce4721ff24..e916aab8e612 100644
--- a/test/boost/sstable_test.cc
+++ b/test/boost/sstable_test.cc
@@ -40,10 +40,38 @@ bytes as_bytes(const sstring& s) {
     return { reinterpret_cast<const int8_t*>(s.data()), s.size() };
 }
 
+static future<>
+stop_env(test_env& env, std::exception_ptr inner)
+{
+    std::exception_ptr outer = nullptr;
+
+    try {
+        co_await env.stop();
+    } catch (...) {
+        outer = std::current_exception();
+    }
+
+    if (inner) {
+        if (outer) {
+            throw seastar::nested_exception(inner, outer);
+        }
+        std::rethrow_exception(inner);
+    }
+
+    if (outer) {
+        std::rethrow_exception(outer);
+    }
+}
+
 future<> test_using_working_sst(schema_ptr s, sstring dir) {
-    return test_env::do_with([s = std::move(s), dir = std::move(dir)] (test_env& env) {
-        return env.reusable_sst(std::move(s), std::move(dir)).discard_result();
-    });
+    test_env env;
+    std::exception_ptr inner = nullptr;
+    try {
+        (void)co_await env.reusable_sst(std::move(s), std::move(dir));
+    } catch (...) {
+        inner = std::current_exception();
+    }
+    co_await stop_env(env, inner);
 }
 
 SEASTAR_TEST_CASE(uncompressed_data) {
```

Similarly:

```
@@ -74,12 +102,19 @@ test_using_reusable_sst(schema_ptr s, sstring dir, sstables::generation_type::in
 }
 
 future<std::vector<partition_key>> index_read(schema_ptr schema, sstring path) {
-    return test_using_reusable_sst(std::move(schema), std::move(path), 1, [] (test_env& env, sstable_ptr ptr) {
-        return sstables::test(ptr).read_indexes(env.make_reader_permit()).then([] (auto&& indexes) {
-            return boost::copy_range<std::vector<partition_key>>(
-                    indexes | boost::adaptors::transformed([] (const sstables::test::index_entry& e) { return e.key; }));
-        });
-    });
+    test_env env;
+    std::exception_ptr inner = nullptr;
+    std::vector<partition_key> ret;
+    try {
+        auto sst = co_await env.reusable_sst(std::move(schema), std::move(path), generation_from_value(1));
+        auto indexes = co_await sstables::test(sst).read_indexes(env.make_reader_permit());
+        ret = boost::copy_range<std::vector<partition_key>>(
+                indexes | boost::adaptors::transformed([] (const sstables::test::index_entry& e) { return e.key; }));
+    } catch (...) {
+        inner = std::current_exception();
+    }
+    co_await stop_env(env, inner);
+    co_return ret;
 }
 
 SEASTAR_TEST_CASE(simple_index_read) {
```

In the above, I managed to extract the env-stopping and the exception nesting to a helper function `stop_env()`, but it does not generalize to other, more complex tests.

For example, in

```
// See CASSANDRA-7593. This sstable writes 0 in the range_start. We need to handle that case as well
SEASTAR_TEST_CASE(wrong_range) {
    return test_using_reusable_sst(uncompressed_schema(), "test/resource/sstables/wrongrange", 114, [] (auto& env, auto sstp) {
        return do_with(dht::partition_range::make_singular(make_dkey(uncompressed_schema(), "todata")), [&env, sstp] (auto& range) {
            auto s = columns_schema();
            return with_closeable(sstp->make_reader(s, env.make_reader_permit(), range, s->full_slice()), [sstp, s] (auto& rd) {
              return read_mutation_from_mutation_reader(rd).then([sstp, s] (auto mutation) {
                return make_ready_future<>();
              });
            });
        });
    });
}
```

we have *two* `finally()` links in the chain of futures:

-  the outer one is from `test_using_reusable_sst()` -- for stopping the test environment --,
-  and the inner one is from `with_closeable()` -- for closing the `mutation_reader` returned by `make_reader()`.

That translates to 2³=8 exception configurations: `read_mutation_from_mutation_reader()` may fail in the innermost lambda, and then on the cleanup path, each of `mutation_reader::close()` and `test_env::stop()` may *independently* fail.

In the worst case (three exceptions), the final future might resolve to a small *tree* of `seastar::nested_exception` objects:

```
      seastar::nested_exception
     /                         \
outer:             inner: seastar::nested_exception
env.stop()           /                       \
failure          outer:                     inner:
                 mutation_reader::close()   read_mutation_from_mutation_reader()
                 failure                    failure
```

Now, in this particular case, `mutation_reader::close()` will never fail (`with_closeable()` requires "nothrow move constructible"), and therefore I might be able to handle `mutation_reader::close()` through normal destruction upon scope leaving; that is, via `seastar::defer()`.

However, in general: whenever we need `n` cleanup actions (each of which might throw), then the future-chaining coding style will use `n` `future::finally()` calls. Consequently, the final tree of `seastar::nested_exception`s may correspond to any one of approx. `2^n` exception configurations. ("Approximately" because, the 1 configuration of "no exception", and the `n` configrations of "exactly 1 exception", do not involve `seastar::nested_exception` instances.) Reproducing these `2^n` exception configurations / exception trees  with explicit `try/catch/if` blocks -- as shown above with `stop_env()` for only `n=1` --, is not feasible, regardless of using `co_await` vs. `seastar:thread`. It would require some new infrastructure for dealing with general lists (or trees) of exceptions.

... @tchaikov floated the idea of coroutinizing only the lambdas that are passed *into* `do_with()` and friends; i.e., expanding neither `do_with()` nor the other similar wrappers. But, when I tried that, the compiler told me "you can't use co_await in this lambda" or some such. :/

**Comment by lersek** [comment]
@avikivity thank you for the [approval](https://github.com/scylladb/scylladb/pull/19937#pullrequestreview-2207666086) on the PR meanwhile! I believe the PR should be mergeable as a well-contained improvement, even though I can't currently coroutinize the test cases that employ multiple "finally" futures, per above discussion.

**Comment by lersek** [comment]
Thanks; I've found relevant prior art for this. I wanted to see if `test_env::stop()` could actually throw (and if so, what types).

Commit 8d704f253229 ("sstable_test_env: Coroutinize and move to .cc test_env::stop()", 2023-10-31) is relevant. Just before that commit, `_impl->mgr.close()` -- that is, `sstables_manager::close()` -- was not marked `noexcept`. Therefore, in theory at least, commit 8d704f253229 introduced a code path where `co_await _impl->mgr.close()` might throw, and ` co_await _impl->semaphore.stop()` would not be reached.

Descendant commit 2c78b46c784d ("sstables::test_env: Carry compaction manager on board", 2023-10-31) is also relevant. `compaction_manager::stop()` is not marked `noexcept`; therefore, again in theory at least, this commit introduced another code path in `test_env::stop()` where `co_await _impl->cmgr->get_compaction_manager().stop()` could throw, and the rest of the coroutine would not be reached.

So this suggests that we don't mind "weakening" (at least theoretically) exception safey when converting code from explicit futures to coroutines (or to `seastar::thread`); we just assume that close and stop methods won't throw even in case they aren't marked `noexcept`. The conversion effectively equated `.finally` to `.then`.

Accordingly, it should be acceptable to open-code the `finally ... env.close()` from `test_env::do_with()` as `defer ... env.close()`.
