### ISSUE TITLE
Test reader_concurrency_semaphore_test::test_reader_concurrency_semaphore_admission fails with : [Exception] - admission scenario 'need_cpu > awaits'

### ISSUE THREAD

**Issue by lkshminarayanan** [scylladb/scylladb#19801]
Failure log :
```
[Exception] - admission scenario 'need_cpu > awaits'  with expected_can_admit=false failed at test/boost/reader_concurrency_semaphore_test.cc:761
diagnostics: Semaphore test_reader_concurrency_semaphore_admission with 1/2 count and 1024/2048 memory resources: user request, dumping permit diagnostics:
permits	count	memory	table/operation/state
1	1	1K	ks.cf/require_can_admit/active
1	0	0B	ks.cf/test_reader_concurrency_semaphore_admission/evicted

2	1	1K	total

Stats:
permit_based_evictions: 0
time_based_evictions: 1
inactive_reads: 0
total_successful_reads: 0
total_failed_reads: 0
total_reads_shed_due_to_overload: 0
total_reads_killed_due_to_kill_limit: 0
reads_admitted: 20
reads_enqueued_for_admission: 4
reads_enqueued_for_memory: 0
reads_admitted_immediately: 20
reads_queued_because_ready_list: 0
reads_queued_because_need_cpu_permits: 2
reads_queued_because_memory_resources: 0
reads_queued_because_count_resources: 1
reads_queued_with_eviction: 0
total_permits: 23
current_permits: 2
need_cpu_permits: 0
awaits_permits: 0
disk_reads: 0
sstables_read: 0
 == [File] - test/boost/reader_concurrency_semaphore_test.cc
 == [Line] -642
```

Seen at : https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10466/testReport/junit/boost/reader_concurrency_semaphore_test/test_reader_concurrency_semaphore_admission/

[test.log](https://github.com/user-attachments/files/16311461/boost.reader_concurrency_semaphore_test.test_reader_concurrency_semaphore_admission.1.log)

**Comment by Annamikhlin** [comment]
seen on next twice https://jenkins.scylladb.com/job/scylla-master/job/next/7969/testReport/boost/reader_concurrency_semaphore_test/test_reader_concurrency_semaphore_admission/

**Comment by Annamikhlin** [comment]
according to bisect  - 
https://jenkins.scylladb.com/view/master/job/scylla-master/job/bisect/111/artifact/gitBisectLog.txt
the bad commit is - https://github.com/scylladb/scylladb/commit/4fbfecbb3eb140f73aafd7a89ae0ca5115c6c730

**Comment by mykaul** [comment]
@tchaikov  / @denesb - I'm not sure how a seastar update caused the test to start failing - any ideas?

**Comment by tchaikov** [comment]
Lemme take a look.

**Comment by tchaikov** [comment]
i am trying to reproduce this issue locally with the same build and the same random seed, have ran it for 1000 times, no luck so far.

**Comment by tchaikov** [comment]
nice, i am able to reproduce this issue with the "debug" build. looking..

**Comment by tchaikov** [comment]
@denesb hi Botond, if you haven't looked into this issue, may i take it?

**Comment by denesb** [comment]
> @denesb hi Botond, if you haven't looked into this issue, may i take it?

Sure, feel free. I haven't looked into it yet.

**Comment by tchaikov** [comment]
> I think one of these is the most likely candidates as the causes of the regression:
> 
>     * [reader_concurrency_semaphore: execution_loop(): move maybe_admit_waiters() to the inner loop #19600](https://github.com/scylladb/scylladb/pull/19600)
> 
>     * [reader_concurrency_semaphore: make CPU concurrency configurable #19018](https://github.com/scylladb/scylladb/pull/19018)
> 
> 
> Furthermore, I think the problem will be in the test, i.e. the behavior of the semaphore changed in ways the test didn't anticipate and I failed to prepare the test in the above PRs.

i reverted both PR in my local env, the test is still failing randomly. like 1 out of 50 times.

**Comment by denesb** [comment]
> i reverted both PRs in my local branch, the test is still failing randomly. like 1 out of 50 times.

There was another change recently: https://github.com/scylladb/scylladb/pull/19248.

**Comment by tchaikov** [comment]
the commit which breaks the test is https://github.com/scylladb/seastar/commit/7fcc9902a4c7f17ced4b690c3bc4b76d9170c16f .

**Comment by tchaikov** [comment]
just wanted to note down some observations:

with https://github.com/scylladb/seastar/commit/7fcc9902a4c7f17ced4b690c3bc4b76d9170c16f, instead of updating the lowres clock every 64 reactor loops, we update `lowres_lock::_now` and `lowres_system_clock::_now` more frequently. so these lowres clock are not drifted overtime, and its accuracy is preserved to be around a "task_quota". so after the said change:

- `db::timeout_clock::now()` can reflect the time closer to the wall time.
- and when the reactor polls the lowres timer poller, it also uses a more accurate wall time as a reference to tell if the timer is expired.

on scylla's end, `db::timeout_clock` is an alias of `seastar::lowres_clock`, and we use a timer with `db::timeout_clock` for setting a timeout alert triggered when it takes too long to obtain the permit. in this test, we set the `timeout` as `db::timeout_clock::now()`.

**Comment by denesb** [comment]
@tchaikov any luck? We are hitting this a lot.

**Comment by denesb** [comment]
I think the failing test could do with a refactor. TBH I don't know how it was passing before, it should have failed earlier.

**Comment by denesb** [comment]
I found the bug in the test and the connection with the timer changes. Patch coming soon.

**Comment by tchaikov** [comment]
@denesb thanks. i think the root cause is that the reader stays in inactive state, and gets evicted too soon after the timer change.

**Comment by denesb** [comment]
> @denesb thanks. i think the root cause is that the reader stays in the inactive state, and gets evicted too early after the timer change, which expires `_ttl_timer` sooner with a more accurate clock.

Yes, see the fix here: https://github.com/scylladb/scylladb/pull/19859.
