### ISSUE TITLE
nodetool status should show zero-token nodes

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#19849]
#19684 introduces zero-token nodes. They do not replicate data, but are normal topology members. Therefore, `nodetool status` should show them, as it is often used to check the cluster's topology. Currently, zero-token nodes are ignored by `nodetool status` because some API endpoints used by it consider only token-owning nodes.

**Comment by kbr-scylla** [comment]
This is an important follow-up, we should do it ASAP.
