### ISSUE TITLE
Restarting a existing node while bootstrapping a new node fails

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#19884]
As followup on https://github.com/scylladb/scylla-dtest/issues/4676

In `test_simple_kill_streaming_node_while_bootstrapping` we kill an existing node while a new node is being bootstrapped and expect the bootstrapping node to fail.
That is all fine in principle.  However, I tried making the testing more interesting and restart the node that was killed after the new node failed bootstrapping, but unfortunately, this node fails to restart.

I will post a dtest that reproduces the problem, marked to be skipped on this issue.

What I see at the bottom of the restarted node (node2) log is the following.
node4 is the node that failed bootstrap when node2 is killed during streaming to it
```
INFO  2024-07-25 17:40:25,978 [shard 0: gms] gossip - Node 127.0.63.1 has restarted, now UP, status = NORMAL
INFO  2024-07-25 17:40:25,978 [shard 0: gms] gossip - Node 127.0.63.3 has restarted, now UP, status = NORMAL
INFO  2024-07-25 17:40:25,978 [shard 0: gms] gossip - Node 127.0.63.4 has restarted, now UP, status = UNKNOWN
INFO  2024-07-25 17:40:25,979 [shard 0: gms] gossip - InetAddress bc927f17-2da0-47ea-b35b-b30e8f80b3e0/127.0.63.1 is now UP, status = NORMAL
INFO  2024-07-25 17:40:25,980 [shard 0: gms] gossip - InetAddress cf03c095-d41f-4f8e-8893-fba0b5b30e1a/127.0.63.4 is now UP, status = UNKNOWN
INFO  2024-07-25 17:40:25,980 [shard 0: gms] gossip - InetAddress a3bf414e-0bb0-4844-ae8a-96d462887182/127.0.63.3 is now UP, status = NORMAL
INFO  2024-07-25 17:40:25,982 [shard 0:main] migration_manager - Schema agreement check passed.
INFO  2024-07-25 17:40:25,982 [shard 1:main] migration_manager - Schema agreement check passed.
INFO  2024-07-25 17:40:33,837 [shard 0:main] raft_group_registry - marking Raft server cf03c095-d41f-4f8e-8893-fba0b5b30e1a as dead for raft groups
INFO  2024-07-25 17:40:33,857 [shard 0: gms] gossip - Removed endpoint 127.0.63.4
INFO  2024-07-25 17:40:33,857 [shard 0: gms] gossip - InetAddress cf03c095-d41f-4f8e-8893-fba0b5b30e1a/127.0.63.4 is now DOWN, status = UNKNOWN
INFO  2024-07-25 17:40:33,857 [shard 0: gms] gossip - Finished to force remove node 127.0.63.4
WARN  2024-07-25 17:40:34,979 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.0.63.4, status = failed: seastar::rpc::closed_error (connection is closed)
```

**Comment by bhalevy** [comment]
The additional dtest that fails is currently very simple:
```python
        self.test_simple_kill_streaming_node_while_bootstrapping()

        cluster = self.cluster
        nodes = self.cluster.nodelist()[0:-1]

        logger.debug("Make sure that the killed node(s) can be restarted")
        cluster.start_nodes(nodes, wait_other_notice=True)
```

**Comment by kbr-scylla** [comment]
Do you have full logs from test run stashed somewhere?

**Comment by kbr-scylla** [comment]
Ran locally, will post analysis in a sec

**Comment by kbr-scylla** [comment]
[dtest.log](https://github.com/user-attachments/files/16439515/dtest.log)
[node1.log](https://github.com/user-attachments/files/16439516/node1.log)
[node2.log](https://github.com/user-attachments/files/16439517/node2.log)
[node3.log](https://github.com/user-attachments/files/16439518/node3.log)
[node4.log](https://github.com/user-attachments/files/16439519/node4.log)

@bhalevy contrary to what you said here:

>  That is all fine in principle. However, I tried making the testing more interesting and restart the node that was killed after the new node failed bootstrapping, but unfortunately, this node fails to restart.

node2 actually does restart.
```
INFO  2024-07-31 11:40:35,440 [shard 0:main] init - Scylla version 6.2.0~dev-0.20240731.9214aecbe71c initialization completed.
```

The test fails due to a different reason. The `watch_rest_for_alive` call (originating from `cluster.start_nodes(nodes, wait_other_notice=True)`) for some reason waits for node 4 to be alive too. To be specific we're waiting for node 2 to observe node 4 as alive:
```
11:42:36,497 513330  ccm                            DEBUG    cluster.py          :762  | test_simple_restart_streaming_node_while_bootstrapping: node2: watch_rest_for_alive: tofind={'127.0.91.4'} found=set(): tofind_host_id_map={'127.0.91.4': '663f8704-e
0b9-43c3-8514-d565c10ac8f1'} found_host_id_map={}
```

This happens here:
```
        if wait_other_notice:
            for node, _ in marks:
                t = self.cluster.default_wait_other_notice_timeout
                node.watch_rest_for_alive(self, timeout=t, wait_normal_token_owner=wait_normal_token_owner)
>               self.watch_rest_for_alive(node, timeout=t, wait_normal_token_owner=wait_normal_token_owner)
```

`marks` is calculated as follows:
```
        marks = []
        if wait_other_notice:
            marks = [(node, node.mark_log()) for node in
                     list(self.cluster.nodes.values()) if node.is_live()]
```

I suspect that node 4 is included in `marks` because at the moment the test calls `cluster.start_nodes(...)`, node 4 is actually still shutting down after the failed bootstrap attempt. So `is_live()` returns true for it.
```
WARN  2024-07-31 11:40:35,141 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.0.91.2, status = failed: seastar::rpc::closed_error (connection is closed)
INFO  2024-07-31 11:40:35,464 [shard 0:main] raft_group_registry - marking Raft server d98fd0a0-d378-42ea-a68b-52735df280d9 as alive for raft groups
INFO  2024-07-31 11:40:37,141 [shard 0: gms] gossip - Node 127.0.91.2 has restarted, now UP, status = NORMAL
INFO  2024-07-31 11:40:44,983 [shard 0:main] init - Shutting down group 0 usage in local storage
...
ERROR 2024-07-31 11:40:45,239 [shard 0:main] init - Startup failed: std::runtime_error (Bootstrap failed. See earlier errors (Rolled back: Failed stream ranges: std::runtime_error (failed status returned from 663f8704-e0b9-43c3-8514-d565c10ac8f1/127.0.91.4)))
```

I see no Scylla bug here. More like bug in the test or ccm

**Comment by kbr-scylla** [comment]
Note: I ran this test in raft-topology mode which is the default, I assumed you did as well.

**Comment by bhalevy** [comment]
> Note: I ran this test in raft-topology mode which is the default, I assumed you did as well.

Well, tablets are enabled by default, so --tablets should be the new default.

**Comment by bhalevy** [comment]
> I suspect that node 4 is included in `marks` because at the moment the test calls `cluster.start_nodes(...)`, node 4 is actually still shutting down after the failed bootstrap attempt. So `is_live()` returns true for it.

It's not really shutting down, but "isolated" in the sense that it is up, but not serving CQL.
Stopping it after that is enough for starting the other node(s) using libccm start_nodes().
