### ISSUE TITLE
Faster scale out time: reduce the 2 min wait between adding nodes to the cluster.

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#199]
Cassandra best practices recommend at least 2 min between joining two nodes to the cluster [1]

Trying to add more than one instance in (about) the same time results with error:

```
ERROR [main] 2015-04-29 12:42:41,620 CassandraDaemon.java:465 - Exception encountered during startup
java.lang.UnsupportedOperationException: Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while cassandra.consistent.rangemovement is true
INFO  [StorageServiceShutdownHook] 2015-04-29 12:42:41,622 Gossiper.java:1318 - Announcing shutdown
```

It is desirable to remove this limitation or significantly reduce it.
This use case is measured as part of the cloud burst use case.

[1] http://docs.datastax.com/en/cassandra/2.1/cassandra/operations/ops_add_node_to_cluster_t.html

**Comment by avikivity** [comment]
@asias I don't remember we have this limitation.

**Comment by tzach** [comment]
Closing. Raft base topology update made this irrelevant.
