### ISSUE TITLE
docs: ScyllaDB Web Installer for Linux doc is lacking post-installation configuratio

### ISSUE THREAD

**Issue by gcarmin** [scylladb/scylladb#19908]
https://opensource.docs.scylladb.com/stable/getting-started/installation-common/scylla-web-installer.html
https://enterprise.docs.scylladb.com/stable/getting-started/installation-common/scylla-web-installer.html

1. Both Does not includes the scylla_setup part
2. Both includes deprecated versions - 4.6 and 2021.

**Comment by tzach** [comment]
@yaronkaikov FYI

**Comment by tzach** [comment]
The instructions are available in https://opensource.docs.scylladb.com/stable/getting-started/install-scylla/install-on-linux.html we need to make it easier to find

**Comment by tzach** [comment]
@gcarmin please take a look
https://opensource.docs.scylladb.com/master/getting-started/installation-common/scylla-web-installer.html

**Comment by gcarmin** [comment]
Looks good.
tnx.
