### ISSUE TITLE
repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_ignore_dead_nodes_for_whole_dc_replace_option due to unexpected error messages in log

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#19907]
```
request = <SubRequest 'fixture_dtest_setup' for <Function test_ignore_dead_nodes_for_whole_dc_replace_option>>
dtest_config = <dtest_config.DTestConfig object at 0x7fb7e1aca690>
fixture_dtest_setup_overrides = <dtest_setup_overrides.DTestSetupOverrides object at 0x7fb791ba39e0>
fixture_logging_setup = None, fixture_dtest_cluster_name = 'test'
fixture_dtest_create_cluster_func = <function DTestSetup.create_ccm_cluster at 0x7fb7e6f06660>

    @pytest.fixture(scope="function", autouse=False)
    def fixture_dtest_setup(  # noqa: PLR0912, PLR0913
        request,
        dtest_config,
        fixture_dtest_setup_overrides,
        fixture_logging_setup,
        fixture_dtest_cluster_name,
        fixture_dtest_create_cluster_func,
    ):
        # do all of our setup operations to get the enviornment ready for the actual test
        # to run (e.g. bring up a cluster with the necessary config, populate variables, etc)
        initial_environment = copy.deepcopy(os.environ)
        dtest_setup = DTestSetup(dtest_config=dtest_config, setup_overrides=fixture_dtest_setup_overrides, cluster_name=fixture_dtest_cluster_name)
    
        cassandra_cluster = dtest_config.cassandra_version
    
        if not cassandra_cluster:
            if request.node.get_closest_marker("single_node") or not request.node.get_closest_marker("no_boot_speedups"):
                dtest_setup.cluster_options.setdefault("skip_wait_for_gossip_to_settle", 0)
            # Reduce waiting time for the nodes to hear from others before joining the ring.
            # Since all test cases run on localhost and there are no large test clusters
            # it's safe to reduce the value to save a lot of time while testing.
            # (Default value for the option is 30s)
            dtest_setup.cluster_options.setdefault("ring_delay_ms", 10000)
    
        cluster_options = request.node.get_closest_marker("cluster_options")
        if cluster_options:
            for name, value in cluster_options.kwargs.items():
                dtest_setup.cluster_options.setdefault(name, value)
    
        manager_install_dir = dtest_setup.prepare_scylla_manager() if request.node.get_closest_marker("scylla_manager") else None
        dtest_setup.initialize_cluster(fixture_dtest_create_cluster_func, manager_install_dir=manager_install_dir)
    
        # at this point we're done with our setup operations in this fixture
        # yield to allow the actual test to run
        yield dtest_setup
    
        # phew! we're back after executing the test, now we need to do
        # all of our teardown and cleanup operations
    
        reset_environment_vars(initial_environment)
        dtest_setup.jvm_args = []
    
        for con in dtest_setup.connections:
            con.cluster.shutdown()
        dtest_setup.connections = []
    
        rep_setup = getattr(request.node, "rep_setup", None)
        rep_call = getattr(request.node, "rep_call", None)
        failed = getattr(rep_setup, "failed", False) or getattr(rep_call, "failed", False)
    
        try:
            dtest_setup.cluster.stop(gently=True)
        except Exception as e:  # noqa: BLE001
            logger.error("Error stopping cluster: %s", str(e))
    
        try:
            if not dtest_setup.allow_log_errors:
                exclude_errors = []
                marker = request.node.get_closest_marker("exclude_errors")
                if marker:
                    exclude_errors = list(marker.args)
                try:
>                   dtest_setup.check_errors_all_nodes(exclude_errors=exclude_errors)

conftest.py:306: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <dtest_setup.DTestSetup object at 0x7fb791ba2570>
nodes = [<ccmlib.scylla_node.ScyllaNode object at 0x7fb7b07ed040>, <ccmlib.scylla_node.ScyllaNode object at 0x7fb7b0789940>, <...ccmlib.scylla_node.ScyllaNode object at 0x7fb791157ec0>, <ccmlib.scylla_node.ScyllaNode object at 0x7fb7d0322150>, ...]
exclude_errors = [], search_str = None, regex = False

    def check_errors_all_nodes(self, nodes=None, exclude_errors=None, search_str=None, regex=False):
        if nodes is None:
            nodes = self.cluster.nodelist()
    
        critical_errors = []
        found_errors = []
        for node in nodes:
            try:
                critical_errors_pattern = r"Assertion.*failed|AddressSanitizer"
                if self.ignore_cores_log_patterns:
                    expr = "|".join([f"({p})" for p in set(self.ignore_cores_log_patterns)])
                    matches = node.grep_log(expr)
                    if matches:
                        logger.debug(f"Will ignore cores on {node.name}. Found the following log messages: {matches}")
                        self.ignore_cores.append(node)
                if node not in self.ignore_cores:
                    critical_errors_pattern += "|Aborting on shard"
                filter_expr = "|".join(self.ignore_log_patterns)
                matches = node.grep_log(critical_errors_pattern, filter_expr=filter_expr)
                if matches:
                    critical_errors.append((node.name, [m[0].strip() for m in matches]))
            except FileNotFoundError:
                pass
            logger.debug(f"exclude_errors: {exclude_errors}")
            errors = self.check_errors(node=node, exclude_errors=exclude_errors, search_str=search_str, regex=regex, return_errors=True)
            if len(errors):
                found_errors.append((node.name, errors))
    
        if critical_errors:
            raise AssertionError(f"Critical errors found: {critical_errors}\nOther errors: {found_errors}")
        if found_errors:
            logger.error(f"Unexpected errors found: {found_errors}")
            errors_summary = "\n".join([f"{node}: {len(errors)} errors\n" + "\n".join(errors[:5]) for node, errors in found_errors])
>           raise AssertionError(f"Unexpected errors found:\n{errors_summary}")
E           AssertionError: Unexpected errors found:
E           node8: 1 errors
E           ERROR 2024-07-27 05:16:19,092 [shard 0:strm] cdc - Could not retrieve CDC streams with timestamp optional((2024/07/27 05:16:03, b7810f81-8195-4439-a0aa-acd4d7f19767)) upon gossip event. Reason: "std::runtime_error (read_cdc_generation: wrong number of rows. The `num_ranges` column claimed 1792 rows, but reading the partition returned 1000.)". Action: not retrying.
E           node9: 1 errors
E           ERROR 2024-07-27 05:16:46,559 [shard 0:strm] cdc - Could not retrieve CDC streams with timestamp optional((2024/07/27 05:16:03, b7810f81-8195-4439-a0aa-acd4d7f19767)) upon gossip event. Reason: "std::runtime_error (read_cdc_generation: wrong number of rows. The `num_ranges` column claimed 1792 rows, but reading the partition returned 792.)". Action: not retrying.

dtest_setup.py:639: AssertionError
```

**Comment by tchaikov** [comment]
[Uploading 1722057446396_repair_based_node_operations_test.py__TestRepairBasedNodeOperations__test_ignore_dead_nodes_for_whole_dc_replace_option.zip…]()

**Comment by mykaul** [comment]
@yaronkaikov , @Annamikhlin - this needs to be run in the bisect pipeline and find the offending PR quickly.

**Comment by bhalevy** [comment]
> @yaronkaikov , @Annamikhlin - this needs to be run in the bisect pipeline and find the offending PR quickly.

@mykaul this is a new test, so it probably hit a preexisting bug
Cc @kbr-scylla

**Comment by yaronkaikov** [comment]
> > @yaronkaikov , @Annamikhlin - this needs to be run in the bisect pipeline and find the offending PR quickly.
> 
> @mykaul this is a new test, so it probably hit a preexisting bug. I.e. I doubt it's a regression. Cc @kbr-scylla

Re-run passed successfully as well - https://jenkins.scylladb.com/job/scylla-6.1/job/next/29/

**Comment by yaronkaikov** [comment]
Seen again https://jenkins.scylladb.com/job/scylla-master/job/next/8007/

**Comment by bhalevy** [comment]
@kbr-scylla I presume that the errors reported above are benign.
Please let us know otherwise.

@Lakshmipathi can you please prepare a PR adding a pattern to `ignore_log_patterns` to filter those errors, for example:
```
ERROR 2024-07-28 20:37:29,189 [shard 0:strm] cdc - Could not retrieve CDC streams with timestamp optional((2024/07/28 20:36:48, 6441cb2b-a4fd-416b-bb0a-4e985bb08f5e)) upon gossip event. Reason: "std::runtime_error (read_cdc_generation: wrong number of rows. The `num_ranges` column claimed 1792 rows, but reading the partition returned 1000.)". Action: not retrying.
```

To restrict it to the specific error, I suggest something like `r"cdc - Could not retrieve CDC streams with timestamp .*std::runtime_error \(read_cdc_generation: wrong number of rows"`

**Comment by bhalevy** [comment]
@kbr-scylla it seems like a good idea to develop a cdc test based on the same scenario of replacing all nodes in a DC (and using the --ignore-dead-nodes option)

**Comment by kbr-scylla** [comment]
> @kbr-scylla I presume that the errors reported above are benign.

No they are not, why do you think so? We're reading wrong number of rows.

> @Lakshmipathi can you please prepare a PR adding a pattern to ignore_log_patterns to filter those errors, for example:

Please don't, it's a bad idea to silence bugs.

**Comment by kbr-scylla** [comment]
Copy-pasting my explanation from https://github.com/scylladb/scylla-dtest/issues/4698#issuecomment-2255507212

The node who calls `insert_cdc_generation` does not announce the generation's existence until it has been inserted fully with CL=ALL.

So the precondition for `read_cdc_generation` is that the generation data is present in the table (and was written with CL=ALL!)

This precondition check failure indicates a very serious bug in our distributed tables implementation: CL=ALL writes are not being observed by nodes!

**Comment by kbr-scylla** [comment]
Another potential explanation is, that the test is not bootstrapping the cluster correctly -- if it's using gossip mode, then non-sequential bootstraps lead to data loss (e.g. we introduce tokens of new node while streaming of another node is still in progress, etc.)

**Comment by kbr-scylla** [comment]
> Another potential explanation is, that the test is not bootstrapping the cluster correctly

Confirmed. This:
```python
self.cluster.populate(nodes).start(...)
```

starts all nodes concurrently.

This leads to data loss in gossip mode, hence we get our error.

Either boot nodes sequentially in gossip mode, or disable the test in gossip mode.

Unassigning myself, test needs to be fixed.

**Comment by mykaul** [comment]
> This leads to data loss in gossip mode, hence we get our error.
> 
> Either boot nodes sequentially in gossip mode, or disable the test in gossip mode.

@gmizrahi - FYI - for cloud - important!

**Comment by bhalevy** [comment]
> > Another potential explanation is, that the test is not bootstrapping the cluster correctly
> 
> Confirmed. This:
> 
> ```python
> self.cluster.populate(nodes).start(...)
> ```
> 
> starts all nodes concurrently.
> 
> This leads to data loss in gossip mode, hence we get our error.
> 
> Either boot nodes sequentially in gossip mode, or disable the test in gossip mode.
> 
> Unassigning myself, test needs to be fixed.

@kbr-scylla we use this `populate` with all tests.  It's not particular to this test.
Also, the errors happened in raft-based consistent topology changes, not forced-gossip mode.

**Comment by gmizrahi** [comment]
+ @karol-kokoszka @Michal-Leszczynski

**Comment by kbr-scylla** [comment]
>  Also, the errors happened in raft-based consistent topology changes, not forced-gossip mode.

All evidence points to the opposite.

The fact that `insert_cdc_generation` and `read_cdc_generation` functions were used implies that this was gossip mode. In raft-topology mode CDC generations are distributed through group 0, not through CL=ALL write to Everywhere distributed table.

Gossip mode is confirmed by node logs which contain:
```
INFO  2024-07-27 05:14:56,686 [shard 0:strm] storage_service - handle_state_normal for 127.0.59.1/bdd64e02-02e7-4ab3-bd98-5e7f45516294 finished
```
and
```
INFO  2024-07-27 05:14:56,688 [shard 0:strm] raft_topology - The cluster is ready to start upgrade to the raft topology. The procedure needs to be manually triggered. Refer to the documentation
```

Final confirmation comes from the scylla-ci jenkins output:
```
[2024-07-27T04:37:42.238Z] Starting building: scylla-master » gating-dtest-release-with-consistent-topology-changes #2760
[2024-07-27T04:37:42.329Z] Starting building: scylla-master » gating-dtest-release #10780
...
[2024-07-27T05:45:10.045Z] Build scylla-master » gating-dtest-release #10780 completed: FAILURE
...
[2024-07-27T06:08:47.637Z] Build scylla-master » gating-dtest-release-with-consistent-topology-changes #2760 completed: SUCCESS
```

the raft-topology job succeeded, the other one failed, which implies that the collected failed dtest artifact had to come from the non-raft-topology job.

**Comment by kbr-scylla** [comment]
> @kbr-scylla we use this populate with all tests. It's not particular to this test.

See cdc_test.py, `populate_sequentially` and `populate_sequentially_multidc` functions.

**Comment by kbr-scylla** [comment]
> @gmizrahi - FYI - for cloud - important!

Guys, this is not new, and if it's a surprise for anyone, then people should start reading documentation more.
5.4 docs, "Create a ScyllaDB Cluster":
https://opensource.docs.scylladb.com/branch-5.4/operating-scylla/procedures/cluster-management/create-cluster.html


Step 4:
> After Scylla has been installed and configured, edit scylla.yaml file on all the nodes, using the first node as the seed node. Start the seed node, and **once it is in UN state**, repeat for all the other nodes, each **after the previous is in UN state**.

(emphasis mine)

**Comment by bhalevy** [comment]
> > @gmizrahi - FYI - for cloud - important!
> 
> Guys, this is not new, and if it's a surprise for anyone, then people should start reading documentation more. 5.4 docs, "Create a ScyllaDB Cluster": [opensource.docs.scylladb.com/branch-5.4/operating-scylla/procedures/cluster-management/create-cluster.html](https://opensource.docs.scylladb.com/branch-5.4/operating-scylla/procedures/cluster-management/create-cluster.html)
> 
> Step 4:
> 
> > After Scylla has been installed and configured, edit scylla.yaml file on all the nodes, using the first node as the seed node. Start the seed node, and **once it is in UN state**, repeat for all the other nodes, each **after the previous is in UN state**.
> 
> (emphasis mine)

Then this should be implemented in libccm with the wait_other_notice=True flag.
Not specifically for this test.

**Comment by bhalevy** [comment]
> > > @gmizrahi - FYI - for cloud - important!
> > 
> > 
> > Guys, this is not new, and if it's a surprise for anyone, then people should start reading documentation more. 5.4 docs, "Create a ScyllaDB Cluster": [opensource.docs.scylladb.com/branch-5.4/operating-scylla/procedures/cluster-management/create-cluster.html](https://opensource.docs.scylladb.com/branch-5.4/operating-scylla/procedures/cluster-management/create-cluster.html)
> > Step 4:
> > > After Scylla has been installed and configured, edit scylla.yaml file on all the nodes, using the first node as the seed node. Start the seed node, and **once it is in UN state**, repeat for all the other nodes, each **after the previous is in UN state**.
> > 
> > 
> > (emphasis mine)
> 
> Then this should be implemented in libccm with the wait_other_notice=True flag. Not specifically for this test.

scylla_node.watch_rest_for_alive is based on:
```
            url_live = f"http://{self.address()}:10000/gossiper/endpoint/live"
            url_joining = f"http://{self.address()}:10000/storage_service/nodes/joining"
...
where the live nodes are the set of endpoint returned by `/gossiper/endpoint/live` minus the set returned by `/storage_service/nodes/joining`.

Now, see scylla-nodetool:
```
void status_operation(scylla_rest_client& client, const bpo::variables_map& vm) {
...
    const auto live = get_endpoints_of_status(client, "live");
...
    const auto joining = get_nodes_of_state(client, "joining");
    const auto leaving = get_nodes_of_state(client, "leaving");
    const auto moving = get_nodes_of_state(client, "moving");
...
            if (live.contains(ep)) {
                status = 'U';
            } else if (down.contains(ep)) {
                status = 'D';
            } else {
                status = '?';
            }
            if (joining.contains(ep)) {
                state = 'J';
            } else if (leaving.contains(ep)) {
                state = 'L';
            } else if (moving.contains(ep)) {
                state = 'M';
            } else {
                state = 'N';
            }
```

So `UN` is printed by `nodetool status` if the node is in `live` and not joining/leaving/moving.
In since in the bootstrap case, only `joining` is interesting, it looks the libccm/scylla_node `watch_rest_for_alive` is compatible with the `nodetool status` `UN` method.

**Comment by kbr-scylla** [comment]
> Then this should be implemented in libccm with the wait_other_notice=True flag.

Hmm, I'd say it's arguable what `wait_other_notice=True` means:
1. does it mean that nodes wait so see each other as alive after population finishes
2. or does it mean we do this wait during the population, after each node is started

currently the first meaning is taken

and it still makes sense for raft-based topology.

For gossip-based topology we need the second meaning, but perhaps another flag would be more appropriate (e.g. `sequentially=True` or something) (for the `start` function)

**Comment by kbr-scylla** [comment]
`start(sequentially=True, wait_other_notice=True)`

**Comment by bhalevy** [comment]
@kbr-scylla please see https://github.com/scylladb/scylladb/issues/19907#issuecomment-2255734700 above

**Comment by yaronkaikov** [comment]
Seen again https://jenkins.scylladb.com/job/scylla-6.1/job/next/32/

**Comment by bhalevy** [comment]
@kbr-scylla uses a paged query with a page size of 1000, and the error we see typically are about retrieving 1000 entries rather than the expected 1792 (in one case there was an error about retrieving 792 out of 1792.  It's odd, but still <= the page size of 1000)
```c++
    co_await _qp.query_internal(
            // This should be a local read so 20s should be more than enough
            format("SELECT range_end, streams, ignore_msb, num_ranges FROM {}.{} WHERE id = ? USING TIMEOUT 20s", NAME_EVERYWHERE, CDC_GENERATIONS_V2),
            db::consistency_level::ONE, // we wrote the generation with ALL so ONE must see it (or there's something really wrong)
            { id },
            1000, // for ~1KB rows, ~1MB page size
            [&] (const cql3::untyped_result_set_row& row) {
```

**Comment by bhalevy** [comment]
@avikivity @kbr-scylla @tchaikov  I think that f4016d3289f4c2596d98ec71c5825b0e15a26c8a broke query_processor::for_each_cql_result paging by replacing a `break` in the previous code with `co_return` so we don't get to `has_more_results(state)`.

**Comment by bhalevy** [comment]
Duplicate of https://github.com/scylladb/scylladb/issues/16826

**Comment by bhalevy** [comment]
I validated it's caused by the unsafe replace with implicit source_dc after losing all nodes in that dc.
(And found a bug in https://github.com/scylladb/scylladb/pull/16827, with `everywhere_topology` in the process, which is a good thing :))

**Comment by tchaikov** [comment]
> I validated it's caused by the unsafe replace with implicit source_dc after losing all nodes in that dc. (And found a bug in #16827, with `everywhere_topology` in the process, which is a good thing :))

@bhalevy so based on your analysis, shall we disable this test with something like
```py
@pytest.mark.skip_if(issue_open("scylladb/scylladb#16826")
```

**Comment by Lakshmipathi** [comment]
> @bhalevy so based on your analysis, shall we disable this test with something like
> 
> ```python
> @pytest.mark.skip_if(issue_open("scylladb/scylladb#16826")
> ```
> 
@tchaikov Few minutes back added skip and updated PR https://github.com/scylladb/scylla-dtest/pull/4724

**Comment by tchaikov** [comment]
> Duplicate of #16826

closing as not planned.
