### ISSUE TITLE
Extra alternator tables reported with DynamoDB ListTables

### ISSUE THREAD

**Issue by rraziel** [scylladb/scylladb#19911]
When using the DynamoDB API and listing table names, additional tables with a `_scylla_cdc_log` suffix are part of the list, e.g.:

```sh
$ aws dynamodb list-tables --endpoint-url http://localhost:8000
{
    "TableNames": [
        "Content",
        "Content_scylla_cdc_log"
    ]
}
```

However when describing those suffixed tables, they are not found ("proper" tables are described fine):

```sh
$ aws dynamodb describe-table --table-name Content_scylla_cdc_log --endpoint-url http://localhost:8000

An error occurred (ResourceNotFoundException) when calling the DescribeTable operation: Requested resource not found: Table: Content_scylla_cdc_log not found
```

It would be nice if those additional tables were filtered away from the ListTables response.

While ListTables likely isn't a commonly used command, it prevents tools such as dynamodb-admin (a small local UI for DynamoDB) from running.

*Installation details*
Scylla version (or git commit hash): 6.0.1-0.20240612.bc89aac9d017
Cluster size: n/a
OS (RHEL/CentOS/Ubuntu/AWS AMI): official ScyllaDB docker image

**Comment by nyh** [comment]
I sent a PR with a reproducing test and a fix for this issue: https://github.com/scylladb/scylladb/pull/19914
