### ISSUE TITLE
Scylla-nodetool refresh fails if only keyspace is informed

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylladb#19984]
*Installation details*
Scylla version (or git commit hash): 6.0.2-0.20240703.c9cd171f426e

*Description*
The `refresh` operation under Scylla's rewritten `nodetool` fails if only the keyspace is informed. The error message states:

`error processing arguments: required parameters are missing: keyspace and/or table`

The previous java-based `nodetool` requires both `ks` AND `cf`.
If table is indeed required, change the error message to remove `/or`.

*Example*

_From: ScyllaDB 6.0.2_
```
# nodetool refresh system
error processing arguments: required parameters are missing: keyspace and/or table
# nodetool refresh system compaction_history
# nodetool version
ReleaseVersion: 3.0.8
# scylla --version
6.0.2-0.20240703.c9cd171f426e
# 
```

**Comment by denesb** [comment]
Is backport needed? This is a minor UX issue, so I wouldn't backport, but if you guys want it, I won't object.

**Comment by mykaul** [comment]
> Is backport needed? This is a minor UX issue, so I wouldn't backport, but if you guys want it, I won't object.

I don't think so.
