### ISSUE TITLE
`storage_service::wait_for_topology_request_completion` may hang waiting for event after request was completed

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#19994]
The code:
```cpp
future<sstring> storage_service::wait_for_topology_request_completion(utils::UUID id, bool require_entry) {
    while (true) {
        auto [done, error] = co_await  _sys_ks.local().get_topology_request_state(id, require_entry);
        if (done) {
            co_return error;
        }
        co_await _topology_state_machine.event.when();
    }

    co_return sstring();
}
```

`_sys_ks.local().get_topology_request_state` may return `done = false` which is obtained by selecting from topology requests table, but this could race with concurrent update of this table which would set `done = true`, and notifying of `_topology_state_machine.event`. `wait_for_topology_request_completion` after resuming from a yield misses the notification (which happened while it was yielding) and hangs waiting for a new notification.

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius @tgrabiec

**Comment by kbr-scylla** [comment]
`seastar::condition_variable::when` should have an overload which waits for futurized predicate, and correctly handles the predicate result changing concurrently with notification:
- `when` calls the futurized predicate
- predicate yields
- internally, predicate calculates result = false
- conditions change to set result = true before predicate resumes
- condition variable is signaled
- predicate resumes and returns result = false
- `when` should detect that the cv was signaled while predicate was working, and call the predicate again

**Comment by kbr-scylla** [comment]
Alternative solution which wouldn't require this stronger version of `when` would be protecting accesses to this table with a lock. Lock is taken around the call to `get_topology_request_state`, so when we get `false`, we know that it didn't change to `true` in the meantime.

**Comment by gleb-cloudius** [comment]
Our CV is a little bit weird. It remembers signal event, so next wait after a signal will not wait. But this wait may not be next, so the problem may still happen. Did you see it happening?

**Comment by kbr-scylla** [comment]
> Did you see it happening?

No, only noticed it when reading this code (in context of debugging test failure, but I don't think this was the cause)

**Comment by emdroid** [comment]
Another "easy" solution I can think of is to use the `wait()` with timeout (that seems to be available) with some reasonable timeout value (probably rather short one), which will make it try again instead of being stuck forever.

**Comment by emdroid** [comment]
The fix looks good, is also working also for the #21548 reproducer test (with the inserted abortable sleep).
