### ISSUE TITLE
Set linked issue condition for opening backport PR

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#20021]
Today we have a situation where Mergify opened a PR for backport that doesn't have a reference for an issue (for example https://github.com/scylladb/scylladb/pull/20008), those fixes will not be include in our release notes and changelog

We need to make sure all backport PR will have a proper reference to an issue based on https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by yaronkaikov** [comment]
One way to handle this is to validate the PR body, and if we don't have a linked issue, create a comment to the PR author so he can fix the PR body (and open an issue if needed) 

@avikivity @denesb @mykaul  thoughts?

**Comment by denesb** [comment]
Sounds good to me. Although the failed github workflow should be noticed, in  practice it is not noticed. They are too out-of-the way.

**Comment by yaronkaikov** [comment]
> Sounds good to me. Although the failed github workflow should be noticed, in practice it is not noticed. They are too out-of-the way.

@denesb I have implemented it in Scylla-pkg (it's about to get merged), see below an example of PR without a valid reference 
https://github.com/scylladb/scylla-pkg/pull/4006#issuecomment-2402063483
![Image](https://github.com/user-attachments/assets/b015073a-f25d-4f73-996d-0c8bbe7a932c)

**Comment by denesb** [comment]
Thanks @yaronkaikov, it looks good. Make sure to support PRs that only `Refs:` an issue (but not `Fixes`). We use this when some fix is spread in multiple PRs, each of them referencing the issue, but not fixing it.

**Comment by denesb** [comment]
See https://github.com/scylladb/scylladb/pull/20955, where the bot is complaining, even though the backport is fine.

**Comment by yaronkaikov** [comment]
> See [#20955](https://github.com/scylladb/scylladb/pull/20955), where the bot is complaining, even though the backport is fine.

Because `Refs` is not a valid keyword by Github, and will not link between an issue and PR.

**Comment by denesb** [comment]
> > See [#20955](https://github.com/scylladb/scylladb/pull/20955), where the bot is complaining, even though the backport is fine.
> 
> Because `Refs` is not a valid keyword by Github, and will not link between an issue and PR.

Github will create a reference just by adding a recognizable issue number, the `Refs` is for humans, github doesn't need it.

**Comment by yaronkaikov** [comment]
> > > See [#20955](https://github.com/scylladb/scylladb/pull/20955), where the bot is complaining, even though the backport is fine.
> > 
> > 
> > Because `Refs` is not a valid keyword by Github, and will not link between an issue and PR.
> 
> Github will create a reference just by adding a recognizable issue number, the `Refs` is for humans, github doesn't need it.

Reference yes (like will add a line saying it's mention of something like that), but it will not be linked, meaning when the PR was merged/closed it will not close the issue

**Comment by denesb** [comment]
> Reference yes (like will add a line saying it's mention of something like that), but it will not be linked, meaning when the PR was merged/closed it will not close the issue

But that is *exactly* what we want when we use `Refs`: have a line saying this PR mentioned this issue, but not close the issue when said PR is merged.

**Comment by yaronkaikov** [comment]
> > Reference yes (like will add a line saying it's mention of something like that), but it will not be linked, meaning when the PR was merged/closed it will not close the issue
> 
> But that is _exactly_ what we want when we use `Refs`: have a line saying this PR mentioned this issue, but not close the issue when said PR is merged.

Ok, but should we also backport in this case? if the answer is yes i will add this logic as well. Although i am not sure this is what @avikivity was aiming to (maybe i am wrong here :-)

**Comment by denesb** [comment]
> Ok, but should we also backport in this case? if the answer is yes i will add this logic as well. Although i am not sure this is what [@avikivity](https://github.com/avikivity) was aiming to (maybe i am wrong here :-)

Yes, we often backport such patches. The point is: al backported PRs should either:
1) Closes/Fixes an issue
2) Reference an issue

We use both regularly. Sometimes a fix is incomplete and cannot close the issue on its own.

**Comment by yaronkaikov** [comment]
> > Ok, but should we also backport in this case? if the answer is yes i will add this logic as well. Although i am not sure this is what [@avikivity](https://github.com/avikivity) was aiming to (maybe i am wrong here :-)
> 
> Yes, we often backport such patches. The point is: al backported PRs should either:
> 
> 1. Closes/Fixes an issue
> 2. Reference an issue
> 
> We use both regularly. Sometimes a fix is incomplete and cannot close the issue on its own.

Ok. I will add it 

By the way, today we have in Mergify a reference to the original PR as `Refs #xxxx` we should change it to `Parent PR #xxxxx` or something like that so it will be unique

**Comment by denesb** [comment]
> By the way, today we have in Mergify a reference to the original PR as `Refs #xxxx` we should change it to `Parent PR #xxxxx` or something like that so it will be unique

Yes, we need to recognize this reference and not confuse it with the required reference.
An easy way is to check that the reference is to an issue, we don't count reference/closes/etc. against PRs.

**Comment by yaronkaikov** [comment]
@denesb Yesterday we discussed this during the status meeting. As requested by @avikivity we should only support `Fix|es|ed` options as validation for an issue. In case the PR fix only partial fix, we should open an issue for this partial fix (we can ofc include the `refs` to the original issue)

**Comment by yaronkaikov** [comment]
Sure we can, but this restriction is only relevant when we have backport labels , if no backport is needed, there is no restrictions

**Comment by denesb** [comment]
> Sure we can, but this restriction is only relevant when we have backport labels , if no backport is needed, there is no restrictions

Yes, that is what I meant, only do this check in the presence of backport labels.
