### ISSUE TITLE
Creating a table allocates tablets on the node being decommissioned   

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#20032]
If tablet-based table is created concurrently with node being decommissioned after tablets are already drained, the new table may be permanently left with replicas on the node which is no longer in the topology. 

One effect is that this will lead to load balancer failure which will inhibit progress of any topology operations:

```
load_balancer - Replica 154b0380-1dd2-11b2-9fdd-7156aa720e1a:0 of tablet 7e03dd40-537b-11ef-9fdd-7156aa720e1a:1 not found in topology, at:  ...
```

**Comment by mykaul** [comment]
@tgrabiec - don't we need to backport this to 6.1 as well?

**Comment by tgrabiec** [comment]
> @tgrabiec - don't we need to backport this to 6.1 as well?

Yes.
