### ISSUE TITLE
[Perf] Read throughput degradation (shard aware test, vnodes)

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#20033]
## Packages

Scylla version: `6.2.0~dev-20240802.39b49a41cc5d` with build-id `b5677630be86ba0391852836a26ee357a4912e5c`

Kernel Version: `6.8.0-1012-aws`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Max ops in the run with `6.2.0~dev-20240726.27b305b9d120 Build id: 5cd1c04ffa511154048a4408ad4ccfdfbdc36b48` is **402401.0** (https://argus.scylladb.com/test/5528fe34-4acc-4286-99e3-1024a2eabff6/runs?additionalRuns[]=4122d81b-c4dc-4a94-b20f-63a9143cfa65)

Test with `6.2.0~dev-20240802.39b49a41cc5d with build-id b5677630be86ba0391852836a26ee357a4912e5c` was run twice and both times the max ops is significantly less:
- **329154.0** (https://argus.scylladb.com/test/5528fe34-4acc-4286-99e3-1024a2eabff6/runs?additionalRuns[]=4c9442f1-0a10-46c7-8bf8-82029b0788a1)
- **338707.0** (current run)

Test runs with **disable tablets**

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- perf-regression-i4i-ubuntu-db-node-0793e51c-3 (34.201.65.223 | 10.12.7.192) (shards: 7)
- perf-regression-i4i-ubuntu-db-node-0793e51c-2 (54.174.27.57 | 10.12.7.82) (shards: 7)
- perf-regression-i4i-ubuntu-db-node-0793e51c-1 (54.161.241.183 | 10.12.5.144) (shards: 7)

OS / Image: `ami-09b3b03d83b13dfad` (aws: undefined_region)

Test: `scylla-master-perf-regression-throughput-shard-aware-i4i`
Test id: `0793e51c-a18c-4f2e-97a8-c0496954d491`
Test name: `scylla-master/perf-regression/scylla-master-perf-regression-throughput-shard-aware-i4i`
Test method: `performance_regression_test.PerformanceRegressionTest.test_read`
Test config file(s):

- [perf-regression.100threads.30M-keys-i4i.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3bf07664dbbe6d37335f919686fbc891bd9843ef/test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0793e51c-a18c-4f2e-97a8-c0496954d491`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0793e51c-a18c-4f2e-97a8-c0496954d491)
- Show all stored logs command: `$ hydra investigate show-logs 0793e51c-a18c-4f2e-97a8-c0496954d491`

## Logs:
- **db-cluster-0793e51c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/db-cluster-0793e51c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/db-cluster-0793e51c.tar.gz)
- **sct-runner-events-0793e51c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/sct-runner-events-0793e51c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/sct-runner-events-0793e51c.tar.gz)
- **sct-0793e51c.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/sct-0793e51c.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/sct-0793e51c.log.tar.gz)
- **loader-set-0793e51c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/loader-set-0793e51c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/loader-set-0793e51c.tar.gz)
- **monitor-set-0793e51c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/monitor-set-0793e51c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0793e51c-a18c-4f2e-97a8-c0496954d491/20240804_091427/monitor-set-0793e51c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/perf-regression/job/scylla-master-perf-regression-throughput-shard-aware-i4i/13/)
[Argus](https://argus.scylladb.com/test/5528fe34-4acc-4286-99e3-1024a2eabff6/runs?additionalRuns[]=0793e51c-a18c-4f2e-97a8-c0496954d491)
</details>

**Comment by mykaul** [comment]
@avikivity - who can look at this? 

Suspect (is there a reasonable way to git bisect the diff?)
```
commit be880ab22cfeb5e9a1db646afc7f87fd2afad276
Author: Benny Halevy <bhalevy@scylladb.com>
Date:   Sun Jul 28 18:03:51 2024 +0300

    Update seastar submodule

```

(Do we run performance tests when updating the Seastar module? )

**Comment by fruch** [comment]
just for context that 40K run (https://argus.scylladb.com/test/5528fe34-4acc-4286-99e3-1024a2eabff6/runs?additionalRuns[]=4122d81b-c4dc-4a94-b20f-63a9143cfa65)

op_rate
---------

| Current test result | Version compared to | Best | Diff best | Commit, Date | Last | Diff last | Commit, Date |
|--|--|--|--|--|--|--|--
| 402401.0 | 6.1.0~dev | 379208.0 | +6% | #21c67a5a649f 2024-07-17 | 379208.0 | +6% | #21c67a5a649f 2024-07-17 |

**Comment by fruch** [comment]
This deviation isn't something new in those tests

@juliayakovlev is working with @roydahan, on building a gradual test, that would be able to take those into account a bit better.

for now we care closing this issue, as it was agreed in the weekly meeting
