### ISSUE TITLE
Prevent tablet metadata with too many pending replicas from being saved to disk

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#20043]
Saving tablet metadata with more than 1 pending replica will prevent this metadata from being (re)loaded due to sanity check on load. This will bring group0 to a halt and prevent nodes from booting. This will require manual recovery to fix. Better to fail the operation which tries to save the wrong metadata with a similar sanity check.

Refs https://github.com/scylladb/scylladb/issues/20039

**Comment by mykaul** [comment]
@bhalevy - this sounds quite severe to me (so I've assigned it a P1) - please assign it to an owner and/or fix my priority label.

**Comment by bhalevy** [comment]
@xemul can you please send a fix?
