### ISSUE TITLE
Possible data resurrection during tablet split preparation

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#20044]
When tablet split is in prepare phase, sstables are split from main group into left and right groups.

The problem is that each compaction group is self contained, and during tombstone GC, we only look for a group's sstable set to determine if an expired tombstone can be GCed.

If compaction runs in e.g. left group, and finds an expired tombstone, which shadows data still sitting in main group, compaction will not be able to tell that data will be resurrected. 

That can be easily fixed by compaction asking for a snapshot containing all sstables that overlap with the group's token range.

**Comment by mykaul** [comment]
@raphaelsc - this seems quite severe, but was not handled thus far?

**Comment by raphaelsc** [comment]
> @raphaelsc - this seems quite severe, but was not handled thus far?

Agreed. I will increase its priority and work on a fix by the end of this week.

**Comment by bhalevy** [comment]
> > @raphaelsc - this seems quite severe, but was not handled thus far?
> 
> Agreed. I will increase its priority and work on a fix by the end of this week.

@denesb please track this.

**Comment by mykaul** [comment]
@denesb - this is the last item I have for 6.2.0. Do we have any updates?

**Comment by denesb** [comment]
@raphaelsc is working on a solution.

**Comment by raphaelsc** [comment]
PR sent: https://github.com/scylladb/scylladb/pull/20939/
