### ISSUE TITLE
doc: document Metric update between 6.0 and 2024.2

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#20062]
The list must be added to the upgrade guide from 6.0 to 2024.2.

**Comment by amnonh** [comment]
The following metrics are added to 2024.2 
metrics|documentation
-----------|-----------------------
scylla_rpc_compression_bytes_received|bytes read from RPC connections, before decompression
scylla_rpc_compression_bytes_sent|bytes written to RPC connections, after compression
scylla_rpc_compression_compressed_bytes_received|nanoseconds spent on compression
scylla_rpc_compression_compressed_bytes_sent|nanoseconds spent on decompression
scylla_rpc_compression_compression_cpu_nanos|RPC messages received
scylla_rpc_compression_decompression_cpu_nanos|RPC messages sent
scylla_rpc_compression_messages_received|Size of backlog on this queue, in tasks; indicates whether the queue is busy and/or contended
scylla_rpc_compression_messages_sent|Accumulated runtime of this task queue; an increment rate of 1000ms per second indicates full utilization
