### ISSUE TITLE
message/messaging_service: guard adding maintenance statement tenant with cluster feature

### ISSUE THREAD

**Issue by Jadw1** [scylladb/scylladb#20070]
In https://github.com/scylladb/scylladb/pull/18729, we introduced a new statement tenant $maintenance, but the change wasn't protected by any cluster feature.
This isn't a problem in OSS, because it uses `$system` tenant for unknown isolation cookie.  However, in enterprise that leads to creating a service level on not-upgraded nodes, which may end up in an error if user create maximum number of service levels.

Enterprise issue: https://github.com/scylladb/scylla-enterprise/issues/4403

**Comment by tzach** [comment]
@Jadw1 should this issue be closed?  AFAICS https://github.com/scylladb/scylladb/pull/20122 fix it

**Comment by mykaul** [comment]
@piodul - is this going to make it to 6.2 (branch today!) or shall we defer it, or is it done?

**Comment by Jadw1** [comment]
I think it can be closed since the PR is merged. For some reason GH's hook for `Fixes ...` didn't work.

**Comment by piodul** [comment]
Done in https://github.com/scylladb/scylladb/commit/f7eb74e31f322f2d44e0a4d1b6f9a4b19df65c0d, closing.
