### ISSUE TITLE
docs: Issue on page Decoding Stack Traces

### ISSUE THREAD

**Issue by dani-tweig** [scylladb/scylladb#20104]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-5.4/kb/decode-stack-trace

### Problem
6.1 is not released yet, and therefore the message in 5.4 should not say:
Caution
You're viewing documentation for a previous version of ScyllaDB Open Source. [Switch to the latest stable version.](https://opensource.docs.scylladb.com/stable/kb/decode-stack-trace.html)
###  Suggest a fix
This message should be presented only after the newer version (in this case 6.1) is officially released.

**Comment by tzach** [comment]
Why? 5.4 is not the latest. There is only one **latest** stable version, currently its 6.0

**Comment by dani-tweig** [comment]
I thought we keep 2 last versions as supported

**Comment by tzach** [comment]
Yes, supported != latest.
The recommendation is to use the latest.
