### ISSUE TITLE
After multiple hard reboots a node eventually loses connection to all other nodes in the cluster

### ISSUE THREAD

**Issue by dimakr** [scylladb/scylladb#20162]
## Packages

Scylla version: `6.2.0~dev-20240809.3745d0a53457` with build-id `d168ac61c2ac38ef15c6deba485431e666a8fdef`
Kernel Version: `6.8.0-1013-aws`

## Issue description
`disrupt_method multiple_hard_reboot_node` nemesis performed 10 hard reboots of a node-5 in a row (the number of reboots is randomly selected from range 2 to 10 for each test run) - the 1st one started ad `08:41:02`, the 10th finished at `08:54:07`. All reboots finished successfully, scylla started after 10th reboot at `08:54:07`:
```
08:54:07.223699 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:main] init - Scylla version 6.2.0~dev-0.20240809.3745d0a53457 initialization completed. 
```
Then post-nemesis check health of the cluster was performed and passed, and the nemesis was marked as successfully finished at `09:18:14`.

Next `replace_service_level_using_detach_during_load` nemesis was scheduled at `09:23:14`. At the beginning of each nemesis cluster health check is performed. This nemesis passed the pre-nemesis health check, but the nemesis disruption itself was not executed as it is dedicated for SLA tests only. At `09:47:15` the nemesis was marked as skipped.

Next `network_reject_node_exporter` nemesis was scheduled at `09:47:15` and its pre-nemesis cluster health check failed - `nodetool status` check on node-5 (the one that was hard rebooted multiple times previously) returned at `09:54:26` that it sees all other nodes as down:
```
< t:2024-08-10 09:54:26,720 f:cluster.py      l:2701 c:sdcm.cluster         p:DEBUG > Check the health of the node `longevity-tls-50gb-3d-master-db-node-7b8958f1-5' [attempt #1]                           │
< t:2024-08-10 09:54:26,896 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: Datacenter: eu-west                                                                                    │
< t:2024-08-10 09:54:26,897 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: ===================                                                                                    │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: Status=Up/Down                                                                                         │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: |/ State=Normal/Leaving/Joining/Moving                                                                 │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: -- Address     Load     Tokens Owns Host ID                              Rack                          │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.21.103 19.41 GB 256    ?    af2bd628-7745-4085-baa8-6199972679e8 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: UN 10.4.21.183 19.54 GB 256    ?    b4273168-eea5-459e-8567-ee7350612c57 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.21.250 20.67 GB 256    ?    ce1395db-9b0e-47b8-9853-8806c70459f4 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.22.115 19.49 GB 256    ?    15b3be5f-54bc-473a-b823-2ea2945a6bf2 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.23.56  19.74 GB 256    ?    c26fe030-4ef8-4d18-84f1-a13d65fbcf01 1c                            │
< t:2024-08-10 09:54:26,902 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.8.69>: DN 10.4.23.78  24.07 GB 256    ?    8f147dbe-f7d4-409a-be66-32937d802a8c 1c   
```

At `09:54:24` In system.log on node-5 there are records that the other nodes are marked down in gossip:
```
Aug 10 09:54:22.939111 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  3:strm] gossip - failure_detector_loop: Send echo to node 10.4.22.115, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:22.939121 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  3:strm] gossip - failure_detector_loop: Mark node 10.4.22.115 as DOWN
Aug 10 09:54:22.940995 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress 15b3be5f-54bc-473a-b823-2ea2945a6bf2/10.4.22.115 is now DOWN, status = NORMAL
Aug 10 09:54:23.147016 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - failure_detector_loop: Send echo to node 10.4.23.78, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.147026 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - failure_detector_loop: Mark node 10.4.23.78 as DOWN
Aug 10 09:54:23.148989 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress 8f147dbe-f7d4-409a-be66-32937d802a8c/10.4.23.78 is now DOWN, status = NORMAL
Aug 10 09:54:23.535627 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  1:strm] gossip - failure_detector_loop: Send echo to node 10.4.21.250, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.535637 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  1:strm] gossip - failure_detector_loop: Mark node 10.4.21.250 as DOWN
Aug 10 09:54:23.536990 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress ce1395db-9b0e-47b8-9853-8806c70459f4/10.4.21.250 is now DOWN, status = NORMAL
Aug 10 09:54:23.757903 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  2:strm] gossip - failure_detector_loop: Send echo to node 10.4.21.103, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.757913 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  2:strm] gossip - failure_detector_loop: Mark node 10.4.21.103 as DOWN
Aug 10 09:54:23.759997 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress af2bd628-7745-4085-baa8-6199972679e8/10.4.21.103 is now DOWN, status = NORMAL
Aug 10 09:54:23.890642 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  4:strm] gossip - failure_detector_loop: Send echo to node 10.4.23.56, status = failed: seastar::rpc::timeout_error (rpc call timed out)
Aug 10 09:54:23.890653 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  4:strm] gossip - failure_detector_loop: Mark node 10.4.23.56 as DOWN
Aug 10 09:54:23.892488 longevity-tls-50gb-3d-master-db-node-7b8958f1-5 scylla[926]:  [shard  0:strm] gossip - InetAddress c26fe030-4ef8-4d18-84f1-a13d65fbcf01/10.4.23.56 is now DOWN, status = NORMAL
``` 

To summarize, after multiple reboots of node-5 there were no other disruptions executed during the test and the cluster was able to pass a few cluster health checks, but eventually within an hour the node-5 lost connection to other nodes.

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

Node lost connection to other cluster nodes, over time, after multiple hard reboots

## How frequently does it reproduce?

No occurrences of the issue were noticed previously.

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-7b8958f1-7 (54.217.202.232 | 10.4.21.250) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-6 (52.212.55.136 | 10.4.23.56) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-5 (54.73.59.86 | 10.4.21.183) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-4 (52.48.211.247 | 10.4.22.17) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-3 (46.137.188.213 | 10.4.22.115) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-2 (34.246.25.227 | 10.4.23.78) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-7b8958f1-1 (63.35.206.244 | 10.4.21.103) (shards: 14)

OS / Image: `ami-05a75d3ca4e6ebd9f` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `7b8958f1-4a7f-4cef-a68d-32c1393493b0`
Test name: `scylla-master/tier1/longevity-50gb-3days-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/05b966987503dfe0602025e101fff695d0bf169c/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7b8958f1-4a7f-4cef-a68d-32c1393493b0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7b8958f1-4a7f-4cef-a68d-32c1393493b0)
- Show all stored logs command: `$ hydra investigate show-logs 7b8958f1-4a7f-4cef-a68d-32c1393493b0`

## Logs:
- **db-cluster-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/db-cluster-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/db-cluster-7b8958f1.tar.gz)
- **sct-runner-events-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-runner-events-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-runner-events-7b8958f1.tar.gz)
- **sct-7b8958f1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-7b8958f1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/sct-7b8958f1.log.tar.gz)
- **loader-set-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/loader-set-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/loader-set-7b8958f1.tar.gz)
- **monitor-set-7b8958f1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/monitor-set-7b8958f1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8958f1-4a7f-4cef-a68d-32c1393493b0/20240810_184109/monitor-set-7b8958f1.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-50gb-3days-test/32/)
[Argus](https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=7b8958f1-4a7f-4cef-a68d-32c1393493b0)
</details>

**Comment by mykaul** [comment]
Looks like network down event - not sure, but even the Amazon agent gave up. Afterwards, it went up (you can see external SSH attacks trying to login!), but Scylla did not. Not sure this is a very interesting scenario.

**Comment by kbr-scylla** [comment]
ssh access was available all the time, I think. SCT could still connect to this node.

But one of the interfaces, the one used by Scylla (with ipv4=10.4.21.183) went down and judging from SCT logs, never went back up again: drivers were also trying to connect to this node until the end of the test (~18:40) and never succeeded.
(also Java driver likes to spam logs with absolutely no rate limiting... it prints thousands of lines in a single millisecond) Other nodes were also printing that they fail to apply view update on this node.

Not enough evidence to say that it's a Scylla problem. Can be explained by networking problem. So I'm closing the issue.

**Comment by fruch** [comment]
@juliayakovlev 

this case is using the two interfaces step, it's not doing public communication at all, how come it can be attacked from anyone external ? we need to investigate what's going on with this one

**Comment by fruch** [comment]
@mykaul can you transfer it to SCT ?
