### ISSUE TITLE
scylla db startup issue (Failed to create GoogleCloudSnitch: std::runtime_error (Error: HTTP response does not contain: Content-Length )) - v4.0.1

### ISSUE THREAD

**Issue by rohitraj-carousellgroup** [scylladb/scylladb#20180]
*Installation details*
Scylla version (or git commit hash): 4.0.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Running in gke k8s

We have restarted our scylla db but it is not coming up with this error
`INFO  2024-08-16 11:07:32,888 [shard 0] init - starting prometheus API server
INFO  2024-08-16 11:07:32,890 [shard 0] init - starting tokens manager
INFO  2024-08-16 11:07:32,890 [shard 0] init - starting migration manager notifier
INFO  2024-08-16 11:07:32,891 [shard 0] init - creating tracing
INFO  2024-08-16 11:07:32,892 [shard 0] init - creating snitch
ERROR 2024-08-16 11:07:32,906 [shard 0] snitch_logger - Failed to create GoogleCloudSnitch: std::runtime_error (Error: HTTP response does not contain: Content-Length
)
INFO  2024-08-16 11:07:32,906 [shard 0] init - Shutting down migration manager notifier
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down prometheus API server
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down prometheus API server was successful
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down feature service
INFO  2024-08-16 11:07:32,908 [shard 0] init - Shutting down feature service was successful
INFO  2024-08-16 11:07:32,908 [shard 0] init - Shutting down sighup
INFO  2024-08-16 11:07:32,908 [shard 0] init - Shutting down sighup was successful
ERROR 2024-08-16 11:07:32,908 [shard 0] init - Startup failed: std::runtime_error (Error: HTTP response does not contain: Content-Length
)
2024-08-16 11:07:32,961 INFO exited: scylla (exit status 1; not expected)`

kindly help here

**Comment by tchaikov** [comment]
i am reformatting the log above:
```
INFO  2024-08-16 11:07:32,888 [shard 0] init - starting prometheus API server
INFO  2024-08-16 11:07:32,890 [shard 0] init - starting tokens manager
INFO  2024-08-16 11:07:32,890 [shard 0] init - starting migration manager notifier
INFO  2024-08-16 11:07:32,891 [shard 0] init - creating tracing
INFO  2024-08-16 11:07:32,892 [shard 0] init - creating snitch ERROR 2024-08-16 11:07:32,906 [shard 0] snitch_logger - Failed to create GoogleCloudSnitch: std::runtime_error (Error: HTTP response does not contain: Content-Length )
INFO  2024-08-16 11:07:32,906 [shard 0] init - Shutting down migration manager notifier
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down prometheus API server
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down prometheus API server was successful
INFO  2024-08-16 11:07:32,907 [shard 0] init - Shutting down feature service
INFO  2024-08-16 11:07:32,908 [shard 0] init - Shutting down feature service was successful
INFO  2024-08-16 11:07:32,908 [shard 0] init - Shutting down sighup
INFO  2024-08-16 11:07:32,908 [shard 0] init - Shutting down sighup was successful
ERROR 2024-08-16 11:07:32,908 [shard 0] init - Startup failed: std::runtime_error (Error: HTTP response does not contain: Content-Length ) 2024-08-16 11:07:32,961
INFO exited: scylla (exit status 1; not expected)
```

so it seems scylla failed to retrieve the VM metadata via "http://metadata.google.internal/computeMetadata/v1".

**Comment by mykaul** [comment]
4.0.x is very outdated, please upgrade to the latest release (6.0 or 6.1). If it reproduces, we'll be happy to take a look and see what's missing.

**Comment by rohitraj-carousellgroup** [comment]
Actually we are using istio and in our sts accidentally the sidecar got injected by mistake which is converting Content-Length into smallcase content-length. After removing sidecar it is started working with googlecloudsnitch. I wanted to ask like is the library that we are using to get header it should be case insensitive or intentionally we have matching case sensitive header keys?

**Comment by tchaikov** [comment]
this is indeed a bug , and it was addressed in seastar, see https://github.com/scylladb/seastar/commit/58f97fc5b3a492952780c35ae53dfc547f77f815 , and later scylla picked up this change in https://github.com/scylladb/scylladb/commit/1554b5cb61699a21a018c97dbb88ea696e882892. all releases after 5.4.0 should include this fix. 

so i am closing this issue.
