### ISSUE TITLE
compaction_manager::drain should wait if stop_ongoing_compactions is already in progress

### ISSUE THREAD

**Issue by lkshminarayanan** [scylladb/scylladb#20197]
Stop request is sent to the compaction_manager multiple times when the server is being shut down. The initial request comes from [`compaction_manager::really_do_stop()`](https://github.com/scylladb/scylladb/blob/390e01673be1f365e42f826490ed95aeede1a259/compaction/compaction_manager.cc#L1115) and later another request gets sent from [`database::shutdown()`](https://github.com/scylladb/scylladb/blob/390e01673be1f365e42f826490ed95aeede1a259/replica/database.cc#L2270) via `compaction_manager::drain()`. The second call is there to ensure that all the compactions are stopped before closing all the tables. But the `compaction_manager::drain()` returns immediately as the stop is already in progress. Due to this, when the tables are being closed, they might run into errors like the following :

```
exception during mutation write to 127.0.0.1: utils::internal::nested_exception<std::runtime_error> (Could not write mutation system:compaction_history (pk{0010b70d31705e0411efb2edf6467f094c8b}) to commitlog): seastar::gate_closed_exception (gate closed)
```

To prevent this from happening, either `compaction_manager::drain()` should wait until all the compactions are stopped (or) update `database::shutdown()`, so that it waits until all the compactions are stopped before closing the tables.

Patch to reproduce the issue : [Reproduce-drain-issue.patch](https://github.com/user-attachments/files/16658009/Reproduce-drain-issue.PATCH)

**Comment by bhalevy** [comment]
> Patch to reproduce the issue : [Reproduce-drain-issue.patch](https://github.com/user-attachments/files/16658009/Reproduce-drain-issue.PATCH)

Can it be turned into a unit test?

Also, looks like this needs to be fixed regardless:
```diff
diff --git a/test/pylib/rest_client.py b/test/pylib/rest_client.py
index c4e334f660..50ccc21331 100644
--- a/test/pylib/rest_client.py
+++ b/test/pylib/rest_client.py
@@ -331,7 +331,7 @@ class ScyllaRESTAPIClient():
         """Compact the specified or all tables in the keyspace"""
         url = f"/storage_service/keyspace_compaction/{keyspace}"
         if table is not None:
-            url += "?cf={table}"
+            url += f"?cf={table}"
         await self.client.post(url, host=node_ip)
 
     async def dump_llvm_profile(self, node_ip : str):
```

**Comment by lkshminarayanan** [comment]
> > Patch to reproduce the issue : [Reproduce-drain-issue.patch](https://github.com/user-attachments/files/16658009/Reproduce-drain-issue.PATCH)
> 
> Can it be turned into a unit test?

I wrote it as a part of topology_custom test suite. I'll include this test in the PR that fixes this issue. 

> 
> Also, looks like this needs to be fixed regardless:
> 
> ```diff
> diff --git a/test/pylib/rest_client.py b/test/pylib/rest_client.py
> index c4e334f660..50ccc21331 100644
> --- a/test/pylib/rest_client.py
> +++ b/test/pylib/rest_client.py
> @@ -331,7 +331,7 @@ class ScyllaRESTAPIClient():
>          """Compact the specified or all tables in the keyspace"""
>          url = f"/storage_service/keyspace_compaction/{keyspace}"
>          if table is not None:
> -            url += "?cf={table}"
> +            url += f"?cf={table}"
>          await self.client.post(url, host=node_ip)
>  
>      async def dump_llvm_profile(self, node_ip : str):
> ```
> 
> BTW, can we use a params dictionary instead of manipulating the url?

I'll fix it in a separate PR. I'll check if this is possible.

**Comment by lkshminarayanan** [comment]
> > > Patch to reproduce the issue : [Reproduce-drain-issue.patch](https://github.com/user-attachments/files/16658009/Reproduce-drain-issue.PATCH)
> > 
> > 
> > Can it be turned into a unit test?
> 
> I wrote it as a part of topology_custom test suite. I'll include this test in the PR that fixes this issue.
> 
> > Also, looks like this needs to be fixed regardless:
> > ```diff
> > diff --git a/test/pylib/rest_client.py b/test/pylib/rest_client.py
> > index c4e334f660..50ccc21331 100644
> > --- a/test/pylib/rest_client.py
> > +++ b/test/pylib/rest_client.py
> > @@ -331,7 +331,7 @@ class ScyllaRESTAPIClient():
> >          """Compact the specified or all tables in the keyspace"""
> >          url = f"/storage_service/keyspace_compaction/{keyspace}"
> >          if table is not None:
> > -            url += "?cf={table}"
> > +            url += f"?cf={table}"
> >          await self.client.post(url, host=node_ip)
> >  
> >      async def dump_llvm_profile(self, node_ip : str):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > BTW, can we use a params dictionary instead of manipulating the url?
> 
> I'll fix it in a separate PR. I'll check if this is possible.

PR at https://github.com/scylladb/scylladb/pull/20243
