### ISSUE TITLE
test_check_comparison_query_key_condition_options_without_scan_index_forward: AssertionError: The following items differs

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#20191]
Failing since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/656/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_check_comparison_query_key_condition_options_without_scan_index_forward/

scylladb/scylladb@3de4e8f91b338151142a6915e0c195e410df7681
scylladb/scylla-dtest@ff81475de3a8be2477c88d7dddf98b18dc6db5b6
scylladb/scylla-ccm@9370f298cec8f6ce06468aa12a5aa33d38b0a7bf

```
AssertionError: The following items differs:
  {'iterable_item_removed': {'root[1]': {'hash_key': '2', 'range_key': 0}}}
```

And https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/656/testReport/alternator_tests/TesterAlternator/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_check_string_and_binary_query_key_condition_options_without_scan_index_forward/

```
AssertionError: The following items differs:
  {'iterable_item_removed': {'root[0]': {'hash_key': '4', 'range_key': 'ù'}}}
```

Those tests passed in the previous jenkins job with:
scylladb/scylladb@d82fd8b5f04002a1d8d5e9bd9dca256c97d20fde
scylladb/scylla-dtest@bb5b0dcc764d7a21ed4f6daaac2992954bed3450
scylladb/scylla-ccm@9370f298cec8f6ce06468aa12a5aa33d38b0a7bf

bhalevy@lt scylla$ git log --oneline d82fd8b5f04002a1d8d5e9bd9dca256c97d20fde..3de4e8f91b338151142a6915e0c195e410df7681
3de4e8f91b Merge 'cql: process LIMIT for GROUP BY select queries' from Paweł Zakrzewski
8c257db283 Merge 'Native reverse pages over RPC' from Łukasz Paszkowski
99be8de71e doc: set 6.1 as the latest stable version
4d77faa61e cql_test_env: ensure shutdown() before stop() for system_keyspace
4ba9cb0036 README: Update the version of C++ to C++23
a3d53bd224 Merge 'Prevent ALTERing non-existing KS with tablets' from Piotr Smaron
ddb5204929 tests: ensure ALTER tablets KS doesn't crash if KS doesn't exist
ba2f037af5 mutation_partition: drop reverse parameter in compact_for_query
43221bbeed clustering_key_filter: unify get_ranges and get_native_ranges
8b5ec0e963 streamed_mutation_freezer: drop the reverse parameter
f4ca734ccb reverse-reads.md: Drop legacy reverse format information
b3bf555036 Fix comments refering to half-reversed (legacy) slices
15a01c7111 select_statement::do_execute: Add tracing informaction
158b994676 query::trim_clustering_row_ranges_to: require reversed schema for native reversed ranges
8d95d44027 query-request: Drop half_reverse_slice as it is no longer used anywhere
da95f44adc readers: Use reversed schema and native reversed slices
faa62310d9 database: accept reversed schema for reversed queries
df734e35a1 storage_proxy: Support reverse queries in native format
d9e76a5295 query_pagers: Replace _schema with _query_schema
0b2e5ff28f query_pagers: Support reverse queries in native format
309ba68692 select_statement: Execute reversed query in native format
8c391a8ebe storage_proxy::remote: Add support for mixed-node clusters
fbd324b5cd mutation_query: Add reversed function to reverse reconcilable_result
b91edbacf1 query-request: Add reversed function to reverse read_command
9690785112 features: add native_reverse_queries
7b201e9165 kl::reader::make_reader: Unify interface with mx::reader::make_reader
b270097f1f config: drop reversed_reads_auto_bypass_cache
80df313f49 config: drop enable_optimized_reversed_reads
9db272c949 test/cql-pytest: Add test for GROUP BY queries with LIMIT
e7ae7f3662 cql3: process LIMIT for GROUP BY queries
3838ad64b3 cql3/select_statement: simplify the get_limit function
08f3219cb8 cql3: respect the user-defined page size in aggregate queries
0ea2128140 cql: refactor rf_change indentation
5b089d8e10 Prevent ALTERing non-existing KS with tablets

**Comment by bhalevy** [comment]
@paszkow this looks to be related to reverse queries, please investigate.

**Comment by bhalevy** [comment]
Cc @avikivity @mykaul. We may need to revert 8c257db28322a134e131ae2200200c6f878a5c8a if this is not fixed promptly.

**Comment by paszkow** [comment]
> @paszkow this looks to be related to reverse queries, please investigate.

Looking at it, right now.
