### ISSUE TITLE
Partition estimation with split compaction is not being adjusted

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#20253]
Lots of bloom filter rebuilds are seen during split compactions. Turns out partition estimation on input is not adjusting for the split, so each output filter is twice as large as it should, triggering the rebuild.

**Comment by mykaul** [comment]
@denesb - what's the priority of this item?

**Comment by denesb** [comment]
I added priority. It is possibly contributing to issues like https://github.com/scylladb/scylladb/issues/20211, so maybe even higher priority is justified, especially that the fix is really easy one.
