### ISSUE TITLE
DESCRIBE: Invalid type names of arguments in UDFs

### ISSUE THREAD

**Issue by dawmd** [scylladb/scylladb#20256]
Performing `DESC SCHEMA WITH INTERNALS` may produce invalid statements to restore user-defined functions. The type of an argument of a function may be wrapped within `frozen<>`. However, Scylla doesn't allow for using `frozen<>` for the type of an argument when defining a function.

---

Steps to reproduce the problem:

```cql
$ CREATE KEYSPACE my_ks WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor' : 1 } ;
$ CREATE TYPE my_ks.my_type (value int);
$ CREATE FUNCTION my_ks.my_func(val1 int, val2 my_type)
        RETURNS NULL ON NULL INPUT
        RETURNS int
        LANGUAGE lua
        AS $$ return val1 + val2.value $$;
$ DESC SCHEMA WITH INTERNALS;
```

The resultant statement to restore the function is:

```cql
CREATE FUNCTION my_ks.my_func(val1 int, val2 frozen<my_type>)
RETURNS NULL ON NULL INPUT
RETURNS int
LANGUAGE lua
AS $$
 return val1 + val2.value 
$$;
```

Trying to perform the query and restore the function results in the following error:

```bash
InvalidRequest: Error from server: code=2200 [Invalid query] message="User defined argument and return types should not be frozen"
```

---

Scylla version: scylladb/scylladb@2ef5b5e
cqlsh: `[cqlsh 6.0.21 | Scylla 6.2.0~dev-0.20240822.2ef5b5e4fefd | CQL spec 3.3.1 | Native protocol v4]`

**Comment by mykaul** [comment]
I'm not sure why it's a Q4 item. I'd defer.

**Comment by piodul** [comment]
@mykaul It's a bug which breaks backup/restore in some circumstances. Making backup/restore work is our topic right now, so ideally we'd like to fix it right after https://github.com/scylladb/scylladb/pull/20168, maybe even in this quarter.

**Comment by avikivity** [comment]
It's better to fix things quickly than create backlog

**Comment by dawmd** [comment]
I guess the fix should be simple. When scylladb/scylladb#20168 is merged, the introduced `cql3_type_name_without_frozen()` should be enough to solve the issue (unless the problem is more complex than I think).
