### ISSUE TITLE
When SSTable compression metadata is corrupted, no hints of the underlying SSTable is shown in the logs

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#20277]
That's a result of assert usage, when doing a sanity check on chunk length in the compression metadata. So you'd need to either run a offline validate, or inspect the coredump. Let's improve it by switching to malformed exception instead.

**Comment by raphaelsc** [comment]
to solve this, we replace this assert by an exception

```
void compression::segmented_offsets::init(uint32_t chunk_size) {
    SCYLLA_ASSERT(chunk_size != 0);
```

**Comment by shriVATSA54** [comment]
Hlo, not sure of my skill level but can u assign this issue. I will try to solve .
