### ISSUE TITLE
major compaction flushes all tables in successive runs despite compaction_flush_all_tables_before_major_seconds having a non zero value

### ISSUE THREAD

**Issue by lkshminarayanan** [scylladb/scylladb#20301]
If `compaction_flush_all_tables_before_major_seconds` is set to a value greater than zero, major compaction should flush all the tables only if the last flush was done more than `compaction_flush_all_tables_before_major_seconds` seconds ago. But right now, the tables are always flushed regardless of the `compaction_flush_all_tables_before_major_seconds` value. The bug seems to be in `database::get_all_tables_flushed_at` method, which always returns timestamp 1 causing an all table flush from the `maybe_flush_all_tables` method.

**Comment by denesb** [comment]
The real bug here is that this feature doesn't have a test ;).

**Comment by horschi** [comment]
This bug only affects major compactions?
