### ISSUE TITLE
scylla-conf depends on /bin/sh in pretrans

### ISSUE THREAD

**Issue by bjanders** [scylladb/scylladb#20321]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 6.0.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Almalinux 8

Platform (physical/VM/cloud instance type/docker): physical
Hardware: N/A
Disks: N/A

The scylla.spec files depends on /bin/sh in %pretrans. This is wrong, as you cannot assume that /bin/sh is installed in %pretrans. See https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#pretrans:

> Note that the %pretrans scriptlet will, in the particular case of system installation, run before anything at all has been installed. This implies that it cannot have any dependencies at all. For this reason, %pretrans is best avoided, but if used it MUST (by necessity) be written in Lua.

And https://rpm-software-management.github.io/rpm/manual/lua.html:

> Internal Lua is the only thing that can reliably run in %pretrans. On initial system installation, there’s absolutely nothing in the environment where %pretrans scriptlets execute. 

This is the problem I have now. I'm doing an initial system installation with nothing that yet provides /bin/sh. scylla-conf and the whole installation now fails, because the %pretrans dependency cannot be fulfilled. Bash will eventually be installed, providing /bin/sh, but has not yet been installed.

So if %pretrans really is needed here, then it must be rewritten in Lua, as stated in the quotes above, to be compliant with the RPM spec.

**Comment by bjanders** [comment]
Yes, that's what I'm referring to. I should I have included it in the report.

**Comment by mykaul** [comment]
@avikivity - do we still need this ancient part?
```
ver=$(rpm -qi scylla-server | grep Version | awk '{print $3}')
if [ -n "$ver" ]; then
    ver_fmt=$(echo $ver | awk -F. '{printf "%d%02d%02d", $1,$2,$3}')
    if [ $ver_fmt -lt 10703 ]; then
        # for <scylla-1.2
        if [ ! -f /opt/scylladb/lib/scylla/scylla_config_get.py ]; then
            echo
            echo "Error: Upgrading from scylla-$ver to scylla-%{version} is not supported."
            echo "Please upgrade to scylla-1.7.3 or later, before upgrade to %{version}."
            echo
            exit 1
        fi
        commitlog_directory=$(/opt/scylladb/lib/scylla/scylla_config_get.py -g commitlog_directory)
        commitlog_files=$(ls $commitlog_directory | wc -l)
        if [ $commitlog_files -ne 0 ]; then
            echo
            echo "Error: Upgrading from scylla-$ver to scylla-%{version} is not supported when commitlog is not clean."
            echo "Please upgrade to scylla-1.7.3 or later, before upgrade to %{version}."
            echo "Also make sure $commitlog_directory is empty."
            echo
            exit 1
        fi
    fi
fi
```

I think it should all go away.

**Comment by bjanders** [comment]
Slightly off-topic, but still related: What's the purpose of having the scylla-conf in a separate package instead of having the configuration directly in the scylla-server package? When would install scylla-conf without scylla-server? Having the default configuration in the main package seems to be the common practice.

**Comment by avikivity** [comment]
> Slightly off-topic, but still related: What's the purpose of having the scylla-conf in a separate package instead of having the configuration directly in the scylla-server package? When would install scylla-conf without scylla-server? Having the default configuration in the main package seems to be the common practice.

scylla-tools depends on the configuration (I forget why) and one would want to install scylla-tools on a machine that doesn't have scylla-server. See https://github.com/scylladb/scylladb/issues/421.
