### ISSUE TITLE
Thrift: Range deletions should cover static rows

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#2037]
*Installation details*
Scylla version (or git commit hash): master @ bce0fb3

Not sure if it's needed, but the Thrift code should special case range deletions so it can also delete a static row, as is expected by the dtest test_range_tombstone_and_static. Currently, the range delete is just mapped to a range tombstone which doesn't apply to static rows.

**Comment by tchaikov** [comment]
won't be fixed because Thrift is dropped. see #18416
