### ISSUE TITLE
[object-storage, tablets]: Deduplication of SSTable in backup 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#20373]
A followup to https://github.com/scylladb/scylladb/issues/18391

[Manager base Backup](https://manager.docs.scylladb.com/stable/backup/#features) uses SSTable deduplication: It only uploads an SSTable to S3 if it is not already there.
The manager also updates the manifest and manages the relation between SSTable and backup, for example, updating the TTL on deduplicate SSTables.
This is an essential optimization as the bigger the SSTables are, the more likely they will be long-lived.

Core-base backup needs a similar feature.

**Comment by tzach** [comment]
@xemul FYI

**Comment by bhalevy** [comment]
Shouldn't the issue be in the scylla-manager repo?
Scylla core does not manage the backup manifest yet.

**Comment by tzach** [comment]
In Scylla Manager, deduplication is done *before* uploading the files to S3.
How can the manager deduplicate the files if the ScyllaDB core uploads the ssatble?

**Comment by tzach** [comment]
@karol-kokoszka please advise on how Manager backup works today

**Comment by karol-kokoszka** [comment]
> In Scylla Manager, deduplication is done before uploading the files to S3.
How can the manager deduplicate the files if the ScyllaDB core uploads the ssatble?

This is valid for Scylla Manager >= 3.3.1 where explicit de-duplication stage is introduced.

Before, the deduplication happened during upload and was managed by RClone that was generating checksum (if the file with same name and size exists), comparing local and remote checksum and then don't copy if checksum are equal.

RFC for manager deduplication (3.3.1) is here https://docs.google.com/document/d/1EtGlF6UGNy34D_7QsnCheaukp3UwVObZU56PBdd0CQ8/edit#heading=h.jl2qbpcarwp9

**Comment by bhalevy** [comment]
Cc also @tchaikov @kreuzerkrieg @regevran

**Comment by tzach** [comment]
Thanks @karol-kokoszka 
To validate my understanding:  deduplication happened *before* upload before and after Manager 3.3.1

**Comment by regevran** [comment]
This is a [WIP](https://www.notion.so/WIP-e5be0a416c5e477caa654e902cee88c5?pvs=4) - however, for my understanding at this point:
It is SM to deduplicate and ask Scylla to backup just the non-duplicating files.
So this issue might go to scylla-manger repo.

**Comment by regevran** [comment]
This should be in Scylla-Manager. De-duplication is done by SM just before starting the upload.

**Comment by regevran** [comment]
Replaced by:
https://github.com/scylladb/scylla-manager/issues/4069

**Comment by avikivity** [comment]
How can it be replaced by scylla-manager code, if core is performing the backup?

**Comment by bhalevy** [comment]
> How can it be replaced by scylla-manager code, if core is performing the backup?

@avikivity scylla-manager still manages the manifest at this stage so it knows which sstables are already backed up.
When we move the ownership of the backup manifest to scylla (with tiering), we should respectively move the responsibility for deduplication also to scylla
