### ISSUE TITLE
conf: scylla.yaml: can't use parameters for error injections at startup because of too old yaml-cpp lib (need >=0.8.0)

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylladb#20406]
We use `std::unordered_map` for the `parameters` field in the `error_injection_at_startup` struct:

https://github.com/scylladb/scylladb/blob/8f31d3f1fcff14b064ebd2b6b1589f18fcc64fa2/db/config.hh#L70-L80

https://github.com/scylladb/scylladb/blob/8f31d3f1fcff14b064ebd2b6b1589f18fcc64fa2/utils/error_injection.hh#L45

But support for it was added in yaml-cpp 0.8.0 only (we use 0.7.0 now): https://github.com/jbeder/yaml-cpp/releases/tag/0.8.0

Example of error:

scylla.yaml:
```yaml
alternator_address: 127.111.182.1
api_address: 127.111.182.1
authenticator: AllowAllAuthenticator
authorizer: AllowAllAuthorizer
auto_snapshot: false
cas_contention_timeout_in_ms: 180000
cluster_name: 0ae6a3aa-69a2-11ef-9ec7-525400724bfb
counter_write_request_timeout_in_ms: 180000
developer_mode: true
enable_tablets: true
enable_user_defined_functions: false
error_injections_at_startup:
- name: raft_server_set_snapshot_thresholds
  one_shot: true
  parameters:
    snapshot_threshold: 3
    snapshot_trailing: 1
...
```

scylla.log:
```
WARNING: debug mode. Not for benchmarking or production
WARN  2024-09-03 03:10:16,754 seastar - Seastar compiled with default allocator, --memory option won't take effect
WARN  2024-09-03 03:10:16,761 seastar - Seastar compiled with default allocator, will not abort on bad_alloc
INFO  2024-09-03 03:10:16,762 seastar - Reactor backend: linux-aio
INFO  2024-09-03 03:10:16,763 seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
==97==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
INFO  2024-09-03 03:10:16,777 [shard 0:main] seastar - updated: blocked-reactor-notify-ms=36000000000
INFO  2024-09-03 03:10:16,777 [shard 1:main] seastar - updated: blocked-reactor-notify-ms=36000000000
ERROR 2024-09-03 03:10:16,787 [shard 0:main] init - yaml-cpp: error at line 16, column 5: bad conversion : error_injections_at_startup
INFO  2024-09-03 03:10:16,790 [shard 0:main] init - installing SIGHUP handler
INFO  2024-09-03 03:10:17,508 [shard 0:main] init - Scylla version 6.2.0~dev-0.20240901.afa461550741 with build-id c319177b8bd84ee983e0ea90052f43417ad43aba starting ...
...
```

Unfortunatelly, there is still no official 0.8.0 package for Fedora: https://src.fedoraproject.org/rpms/yaml-cpp , but Ubuntu 24.04 already has it: https://launchpad.net/ubuntu/+source/yaml-cpp

**Comment by mykaul** [comment]
I wonder why https://bugzilla.redhat.com/show_bug.cgi?id=2231666 is stalled. Ping them.

**Comment by enaydanov** [comment]
Done: https://bugzilla.redhat.com/show_bug.cgi?id=2231666#c3

**Comment by roydahan** [comment]
I think that the assignee should be @piodul who implemented this feature.
Then he can choose either we wait for yaml-cpp 0.8.0 or refactor error_injection_at_startup.

**Comment by piodul** [comment]
@enaydanov I think you are just using the wrong syntax. I didn't implement support for error injection parameters, but if I read the code correctly, I think you should just flatten the "parameters" map.

The snipped below does not cause any errors for me:

```yaml
error_injections_at_startup:
- name: raft_server_set_snapshot_thresholds
  one_shot: true
  snapshot_threshold: 3
  snapshot_trailing: 1
```

This is the relevant piece of code responsible for parsing a single error injection:

https://github.com/scylladb/scylladb/blob/53524974db281231bfb3117996089a9d492ead31/db/config.cc#L290-L313

**Comment by enaydanov** [comment]
OK, got it. So, it's a difference with how we pass parameters to error injections via API:

Anyway, we can close this issue.
