### ISSUE TITLE
tombstone garbage collection shadowing check may consider only timestamps of live data

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#20423]
Currently, tombstone purging is inhibited if the purgeable tombstone might shadow data in the memtable or in any uncompacted sstable.

The shadowing check is heuristic, based on the min_timestamp in the memtable or sstable,
and if the min_timestamp is less than the tombstone's timestamp, and the memtable contains the respective partition key, or the sstable contains the key's token, it is deemed unsafe to purge the tombstone, as this might cause data resurrection.

However, the mentioned min_timestamp statistic tracks all timestamps in the memtable/sstable - live and dead.
But we shouldn't care if the tombstone shadows older dead data (like other tombstones, or expired cells), since it is already dead and therefore it won't get resurrected.

This issue calls for tracking min_live_timestamp in the memtable and sstables (by extending scylla_metadata), which will track only timestamps of live data.

**Comment by bhalevy** [comment]
Cc @denesb @raphaelsc

**Comment by mykaul** [comment]
> But we shouldn't care if the tombstone shadows older dead data (like other tombstones, or expired cells), since it is already dead and therefore it won't get resurrected.

How do we know to ignore a tombstone's timetamp (as it shadows *only* dead data)?

**Comment by bhalevy** [comment]
> > But we shouldn't care if the tombstone shadows older dead data (like other tombstones, or expired cells), since it is already dead and therefore it won't get resurrected.
> 
> How do we know to ignore a tombstone's timetamp (as it shadows _only_ dead data)?

The fix tracks the minimum timestamp of **live** data in the memtable and writing SSTables, and so it ignore tombstones and ttl-expired data (that has already expired when writing the sstable).
Later on, in get_max_purgeable_timestamp, we examine either the min_live_timestamp or min_live_row_marker_timestamp (if it's a shadowable tombstone), and ensure the presence of the partition key in the memtable, or token in the sstable.

This isn't perfect for expiring data since its liveness is checked when inserted into the memtable or into the sstable, and not when the timestamps are checked, but another compaction round will turn the expired data into a dead tombstone and then it can be properly ignored for the purpose of tombstone garbage collection.
