### ISSUE TITLE
materialized views updates might inhibit tombstone garbage collection

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#20424]
Currently, tombstone purging is inhibited if the purgeable tombstone might shadow data in the memtable or in any uncompacted sstable.

The shadowing check is heuristic, based on the min_timestamp in the memtable or sstable,
and if the min_timestamp is less than the tombstone's timestamp, and the memtable contains the respective partition key, or the sstable contains the key's token, it is deemed unsafe to purge the tombstone, as this might cause data resurrection.

When a column in the base table that is part of the view's primary key is updated, the view updates algorithm generates:
1. a row-marker with a shadowable tombstone for the current view row (based on the pre-updated value of said column).  This tomestone carries the highest timestamp in the row.
2. a new row in the view that consists of a row marker with the current write timestamp plus all other cells in the row with their original write timestamps.

The inserted cells with the original timestamps might cause false positive checks when considering purging of shadowable tombstones in that partition as they are not greater than the shdowable tombstone timestamp and therefore they inhibit its purging.

Since the live row-marker timestamp is greater than the shadowable tombstone's timestamp, it will in fact, shadow it, thus exposing the backdated-cells, that need to be "resurrected" by design.

Therefore, for the purpose of purging shadowable tombstones, we should track the minimum timestamp of live row markers in the memtable and sstable, similar to the `min_live_timestamp` suggested in https://github.com/scylladb/scylladb/issues/20423 (also using the scylla_metadata for sstables)

**Comment by bhalevy** [comment]
Cc @denesb @raphaelsc @nyh @piodul

**Comment by nyh** [comment]
Nice catch, I think you're right: If we see in a view table a **shadowable** tombstone with time T, then in any row where the **row marker**'s timestamp is _higher_ than T the shadowable tombstone is completely ignored and it doesn't hide any data in any column, so the shadowable tombstone can be safely purged without any effect or risk resurrecting any deleted data.

In other words, rows which might cause problems for purging a **shadowable** tombstone with time T are rows with row markers older or equal T. So to know if a whole sstable can cause problems for shadowable tombstone of time T, we need to check if the sstable's oldest row marker (and _not_ oldest column) is older or equal T.

So the logic on purging regular tombstones and shadowable tombstones will be slightly different, and require slightly different min-timestamp values to be saved for memtables/commitlogs/sstables.

I think this is more-or-less what you suggested. I believe it will help a lot, and potentially solve _all_ the problem we've seen in this area - we won't need to exclude memtables/commitlogs/new sstables, and won't need to make shadowable tombstones newer.

**Comment by kostja** [comment]
This is pretty much what I've discussed with Botond last morning. Did you arrive to this independently?

**Comment by bhalevy** [comment]
> This is pretty much what I've discussed with Botond last morning. Did you arrive to this independently?

Yes.  I was circulating these ideas lately.

**Comment by denesb** [comment]
With these changes in mind, do we still need the controversial https://github.com/scylladb/scylladb/pull/20031? Maybe it is still useful as a back-up and as something we can backport readily.

**Comment by bhalevy** [comment]
> With these changes in mind, do we still need the controversial #20031? Maybe it is still useful as a back-up and as something we can backport readily.

The fix is quite intrusive, so I'm not sure if it's a good idea to backport it.
I think that #20031 provides a sensible mitigation, while the long term fix can be provided in the next enterprise version 
after making sure there are no regressions, and the backport it to 2024.2, maybe also to 2024.1 if the merge conflicts won't be too bad to cause a high risk of destabilization.
