### ISSUE TITLE
Make sure S3 multipart upload abortion is idempotent

### ISSUE THREAD

**Issue by kreuzerkrieg** [scylladb/scylladb#20425]
According to the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_AbortMultipartUpload.html) AbortMultipartUpload is more complicated than just calling `DELETE` with `upload-Id`
First issue - call for abortion multiple times:

> if any part uploads are currently in progress, those part uploads might or might not succeed. As a result, it might be necessary to abort a given multipart upload multiple times in order to completely free all storage consumed by all parts.

Second issue - call ListParts API
>To verify that all parts have been removed and prevent getting charged for the part storage, you should call the [ListParts](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html) API operation and ensure that the parts list is empty.

Third issue, looks like our retry for the http client in case of error (the only one possible is 404) will retry, which is unnecessary

For the first and the second issue I'm not sure we have to do anything in case we have Object Lifecycle Management enabled for our bucket. @mykaul , @xemul WDYT?

refs: https://github.com/scylladb/scylladb/pull/19461

**Comment by mykaul** [comment]
I don't believe we have any life cycle management settings whatsoever. I feel it's better to fix it on our side.

**Comment by kreuzerkrieg** [comment]
> I don't believe we have any life cycle management settings whatsoever. I feel it's better to fix it on our side.

You cant get away without LCM. What happens if the application crashes? What happens when you have connectivity problems and the client gives up on retrying? These dangling multipart uploads will stay there forever and amazon going to keep charging us on these.

**Comment by mykaul** [comment]
> > I don't believe we have any life cycle management settings whatsoever. I feel it's better to fix it on our side.
> 
> You cant get away without LCM. What happens if the application crashes? What happens when you have connectivity problems and the client gives up on retrying? These dangling multipart uploads will stay there forever and amazon going to keep charging us on these.

@karol-kokoszka - what do we do in Manager today?

**Comment by karol-kokoszka** [comment]
MultiPartUpload is supported and handled by RClone under the hood. SM is using this feature as well.

In terms of LCM, I confirm that S3 keeps the links forever and it's up to us to abort the multipart upload
https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-abort-incomplete-mpu-lifecycle-config.html

...and we don't define the LCM for backup buckets neither.
That's bad, seems that RClone can cleanup broken multipart uploads https://rclone.org/s3/#cleanup , but SM is never calling to do so. They may remain forever if the RClone server is killed during the multipart upload.

We can address it in SM by calling to cleanup when SM is purging expired snapshots or by defining the policy on the bucket.

**Comment by regevran** [comment]
We have nothing to do with failed abortion. 
This issue will be closed with #19533.

**Comment by kreuzerkrieg** [comment]
@xemul @mykaul @regevran Do we agree that #21054 closes this issue in a way?

**Comment by regevran** [comment]
> [@xemul](https://github.com/xemul) [@mykaul](https://github.com/mykaul) [@regevran](https://github.com/regevran) Do we agree that [#21054](https://github.com/scylladb/scylladb/pull/21054) closes this issue in a way?

In a way. Yes.
We need to manage S3 in general.
This management can't be a single action by a single actor at a single point of operation: there is always the option that this actor dies in the middle.

**Comment by regevran** [comment]
> This management can't be a single action by a single actor at a single point of operation: there is always the option that this actor dies in the middle.

Created: https://github.com/scylladb/scylladb/issues/21528

**Comment by xemul** [comment]
https://github.com/scylladb/scylladb/pull/21054/commits/7fd1ff8d7976d52248eb00fcc8022db1508b2144 fixes it
