### ISSUE TITLE
toolchain: restore multiarch build on frozen toolchain

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylladb#20442]
When we introduced optimized clang at 6e487a49aa8d5504567b85a6ce157886ecb750b3, we dropped multiarch build on frozen toolchain, because building clang on QEMU emulation is too heavy.

Actually, even after the patch merged, there are two mode which does not build clang, --clang-build-mode INSTALL_FROM and --clang-build-mode SKIP.
So we probably should restore multiarch build only these mode, and keep skipping on INSTALL mode since it builds clang.

Note that --clang-archive parameter cannot use current way, because if we apply multiarch build on INSTALL_FROM mode it will requires both x86_64 clang archive and aarch64 clang archive.
So it should be take two parameters, one for x86_64 archive and the other for aarch64 clang archive.

**Comment by avikivity** [comment]
Or maybe a super-tarball with the two in it.

**Comment by avikivity** [comment]
But, a multiarch build using qemu is too slow.

**Comment by yaronkaikov** [comment]
So maybe we should automate the toolchain build, so it will automatically create the multiarch ?

**Comment by yaronkaikov** [comment]
> I would love ./tools/toolchain/prepare --node aarch64=my_aarch64_node --node x86_64=my_x86_64_node

It means you must clone Scylla and have the proper SSH key to do it, right? (in the remote node)
