### ISSUE TITLE
Proposal: keep original sstable uuid generation in scylla metadata

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#20459]
We use the sstable generation as part of the backup deduplication algorithm.
But currently, when a tablet is migrated across shards in the same node, we "rename" it by creating hard-links to a new generation, and therefore it will be considered as a different sstable for the purpose of deduplication.

Also, with file-based streaming across nodes, we do keep the sstable generation as part of the component file names, but re-encrypting the contents might cause it to seem like a new sstable, despite having exactly the same contrents.

In addition, if we decrypt the sstable before backing it up, relying on the object-storage encryption-at-rest, we would need to compare the decrypted contents of to prove their identical.

Instead, I propose to keep the the original sstable generation in the scylla metadata and carry it over in any kind of sstable migration, so it can be used as a global unique identifier for the sstable **contents**, that are immutable.
This contents can go over transformations like compression and encryption, but when reversed, the canonical form of the data is exactly the same, regardless of transformation.

Note that this is orthogonal to digest crc and other signatures, like block checksums, that protect the data integrity as stored, while for deduplication purposes, we care about the abstract data, not about how it's represented at the moment.

**Comment by bhalevy** [comment]
We may want to use this stable generation when taking a snapshot, so it will be used naturally for the name of the object on object storage.

**Comment by regevran** [comment]
Sure.
Already did.
I am waiting for @raphaelsc to come back to me and have a discussion.
