### ISSUE TITLE
Scylla optimized clang should have target vendor set to 'Scylla'

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#20467]
To make it easy to determine you are using our optimized clang. Currently:
```
ykaul@ykaul:~/github/scylladb$ ./tools/toolchain/dbuild  clang --version
clang version 18.1.6 (https://github.com/llvm/llvm-project 1118c2e05e67a36ed8ca250524525cdb66a55256)
Target: x86_64-unknown-linux-gnu     <---- unknown
Thread model: posix
InstalledDir: /usr/local/bin
```

And on my host (Fedora 40):
```
ykaul@ykaul:~/github/scylladb$ clang --version
clang version 18.1.6 (Fedora 18.1.6-3.fc40)
Target: x86_64-redhat-linux-gnu   <---- Red Hat
Thread model: posix
InstalledDir: /usr/bin
Configuration file: /etc/clang/x86_64-redhat-linux-gnu-clang.cfg

```

**Comment by syuu1228** [comment]
Is this something okay to change?
I found that there are codes which hardcoded these target names: 
https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/ToolChains/Gnu.cpp#L2494

**Comment by mykaul** [comment]
> Is this something okay to change? I found that there are codes which hardcoded these target names: https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/ToolChains/Gnu.cpp#L2494

That's a good enough reason not to pursue this!
