### ISSUE TITLE
Filtering a regular column can be ignored when a static row is present

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#20485]
Given

```cql

CREATE TABLE t3 (p int, c int, s int static, r int, PRIMARY KEY(p, c));
UPDATE t3 SET s=5 WHERE p=5;
SELECT * FROM t3 WHERE r=0 ALLOW FILTERING;
```

we get

```
 p | c    | s | r
---+------+---+------
 5 | null | 5 | null

(1 rows)
```

Although we specified r=0, we get a result with NULL r.

**Comment by nyh** [comment]
I believe this is a duplicate of a known bug - https://github.com/scylladb/scylladb/issues/10357, so should be closed as a duplicate.
There are four tests reproducing this issue, so in your fix please verify that it fixes them too.

**Comment by nyh** [comment]
Another likely duplicate: https://github.com/scylladb/scylladb/issues/10091

**Comment by kostja** [comment]
@avikivity how did you step into it?

**Comment by avikivity** [comment]
> @avikivity how did you step into it?

#20487 not-really-accidentally fixed it and caused an unrelated test that relied on the bug to fail. After examining the faiing test I came into the conclusion that #20487 fixed a bug and did not introduce a new one, and came up with an independent fix.

What would really have helped is if test.py reported xfails that began passing.

**Comment by avikivity** [comment]
Closing as duplicate of #10357.

(not a duplicate of #10091)
