### ISSUE TITLE
Range scans take forever even on local system tables and cause internal timeouts

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#20563]
I don't think people will ever learn to avoid range scans on local tables.

Long-running range scans may cause internal timeouts, which significant consequences such as killing group 0 state machine. Recent example in tests: https://github.com/scylladb/scylladb/issues/20483

Range scans for local system tables should use a separate query path, there's no point in sequentially scanning over vnodes, which has a complexity depending on the size of the cluster (size of cluster * vnodes per node).

**Comment by mykaul** [comment]
This is a too general GH issue - I don't see who should own this item, and what exactly needs to be fixed here. Should we add a warning to such scans? Won't it be ignored? In debug mode only?

**Comment by kbr-scylla** [comment]
We should fix range scans -- I proposed a solution in the issue:

> Range scans for local system tables should use a separate query path, there's no point in sequentially scanning over vnodes, which has a complexity depending on the size of the cluster (size of cluster * vnodes per node).

Doing a range scan like we're doing now, i.e. doing a separate read for every vnode and then merging the results, makes no sense for local tables. It's **absurd** that the time complexity of a **local read** scales with the size of the cluster.

**Comment by avikivity** [comment]
> I don't think people will ever learn to avoid range scans on local tables.
> 

Why should they learn it? Range scans are perfectly normal.


> Long-running range scans may cause internal timeouts, which significant consequences such as killing group 0 state machine. Recent example in tests: #20483

That's a bug.

> 
> Range scans for local system tables should use a separate query path, there's no point in sequentially scanning over vnodes, which has a complexity depending on the size of the cluster (size of cluster * vnodes per node).

Sure.

**Comment by nyh** [comment]
> We should fix range scans -- I proposed a solution in the issue:

It wasn't clear if you wanted to fix them, or to have people stop using them - and more importantly, you mixed the discussion of what users do, and internal queries (which, you claim, are "killing group 0 state machine" - I don't know why).

It would be helpful if you could be more concrete on what the problem is (or if there are multiple instances of this problem).

> Doing a range scan like we're doing now, i.e. doing a separate read for every vnode and then merging the results, makes no sense for local tables. It's **absurd** that the time complexity of a **local read** scales with the size of the cluster.

I don't follow - if the table is local, most of the vnodes (which belong to other nodes) will just be ignored (a local table doesn't ask data from remote nodes). So perhaps there is O(vnodes) code doing if()s, which will be good to fix, but it should be a trivial memory lookup; Why is it causing serious problems in practice in anything but super-humongous clusters?

**Comment by piodul** [comment]
> I wonder how limited we are in the structure of service_level_v2; does it have to repeat the structure of the original service levels or we could add a surrogate partition key? @Jadw1 @piodul

@kostja I don't see any obstacles. I think that such transformation (i.e. conversion of a table to a single-partition table) can be done on any table in general unless you have static columns, but the service levels table does not have static columns.

We would of course implement migration of data on upgrade, and there would be some churn in the form of the leftover `service_levels_v2` table.

I'm also afraid that auth tables in group0 might potentially have a similar problem (we don't scan them but we might want to in the future if their state is supposed to be cached).

**Comment by kbr-scylla** [comment]
@nyh just to give you a high level idea of the complexity, going through `storage_proxy::query_partition_key_range`:

for every vnode (256 * num_nodes):
```cpp
    query_ranges_to_vnodes_generator ranges_to_vnodes(erm->make_splitter(), schema, std::move(partition_ranges), merge_tokens);

...

    for (;;) {
        std::vector<::shared_ptr<abstract_read_executor>> exec;
        std::unordered_map<abstract_read_executor*, std::vector<dht::token_range>> ranges_per_exec;
        dht::partition_range_vector ranges = ranges_to_vnodes(concurrency_factor);
        dht::partition_range_vector::iterator i = ranges.begin();
```

we create a read executor
```cpp
            exec.push_back(::make_shared<never_speculating_read_executor>(schema, cf.shared_from_this(), p, erm, cmd, std::move(range), cl, std::move(filtered_endpoints), trace_state, permit, std::monostate()));\
            ranges_per_exec.emplace(exec.back().get(), std::move(merged_ranges));
```

and execute all of them
```cpp
        auto wrapped_result = co_await utils::result_map_reduce(exec.begin(), exec.end(), [timeout] (::shared_ptr<abstract_read_executor>& rex) {
            return rex->execute(timeout);
        }, std::move(merger));
```

then for every such executor, (which is a piece of work itself), somewhere deep in the callstack and after doing probably tens of heap allocations and taking tens of semaphores (for memory limiting etc.) see `query_nonsingular_data_locally` -> `query_data_on_all_shards` -> `do_query_on_all_shards` -> `do_query_vnodes` + `data_query_result_builder` -> `read_page`
we must create a `multishard_combining_reader_v2`
```cpp
    auto reader = make_multishard_combining_reader_v2(ctx, s, ctx->erm(), ctx->permit(), ranges.front(), cmd.slice,
            trace_state, mutation_reader::forwarding(ranges.size() > 1));
```

(again this happens **for every vnode**!)

And implementing `multishard_combining_reader_v2` probably required @denesb to sign a pact with satan; looking at it gives me that weird chill going over my spine; go to readers/multishard.cc if you're interested

And then once we're on the correct shard (which is again not so simple, and happens for multiple shards) there is the bloom filter and so on

**Comment by kostja** [comment]
* Piotr Dulikowski ***@***.***> [24/09/12 15:29]:
> > I wonder how limited we are in the structure of service_level_v2; does it have to repeat the structure of the original service levels or we could add a surrogate partition key? @Jadw1 @piodul
> 
> @kostja I don't see any obstacles. I think that such transformation (i.e. conversion of a table to a single-partition table) can be done on any table in general unless you have static columns, but the service levels table does not have static columns.
> 
> We would of course implement migration of data on upgrade, and there would be some churn in the form of the leftover `service_levels_v2` table.
> 
> I'm also afraid that auth tables in group0 might potentially have a similar problem (we don't scan them but we might want to in the future if their state is supposed to be cached).

Looks like a better course of action is to implement local scans
with paging, rather than map/reduce over vnodes.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by denesb** [comment]
Proposed fix here: https://github.com/scylladb/scylladb/pull/20577
Let's see whether it explodes or not.

**Comment by tgrabiec** [comment]
> for every vnode (256 * num_nodes):

query_ranges_to_vnodes_generator should not split around vnodes for local tables:

```
    if (_local) { // if the range is local no need to divide to vnodes
        add_range(get_remainder());
        return;
    }

```

**Comment by denesb** [comment]
So it looks like local range scans are already optimized and this issue is moot.

**Comment by denesb** [comment]
@kbr-scylla I think we should close this issue.

**Comment by avikivity** [comment]
@kbr-scylla run a TRACING ON SELECT query on a local table and close.

**Comment by nyh** [comment]
> So it looks like local range scans are already optimized and this issue is moot.

@kbr-scylla was sure that local range scans are super-slow, @denesb even sent a patch to "fix" it, but now the conclusion is that they were never super-slow at all? Did anyone actually try to measure or trace it before reporting a problem or "fixing" it? If not, why not?

Maybe someone with initiative can think what sort of testing framework we are missing to have made such testing easy?

**Comment by denesb** [comment]
> > So it looks like local range scans are already optimized and this issue is moot.
> 
> @kbr-scylla was sure that local range scans are super-slow, @denesb even sent a patch to "fix" it, but now the conclusion is that they were never super-slow at all? Did anyone actually try to measure or trace it before reporting a problem or "fixing" it? If not, why not?
> 
> Maybe someone with initiative can think what sort of testing framework we are missing to have made such testing easy?

I have proposed a fix and when I started measuring it, I saw no improvement, so I asked for the PR to be not merged until I find out why my improvement has no effect. Then @tgrabiec explained that the optimization I tried to add already exists at another layer. Thus I have withdrawn my proposal.

I don't know how @kbr-scylla concluded that range-scans are too slow, I'll let him explain that.

**Comment by tgrabiec** [comment]
Range scans may be slow for sparse tables on many shards due to static sharding and the fact that we do a rump-up of concurrent shards we read from. We start from the shard of the first range. Most of those ranges will not have enough data to fill a page with small tables. Maybe that's what's slow.

**Comment by piodul** [comment]
> Range scans may be slow for sparse tables on many shards due to static sharding and the fact that we do a ramp-up of concurrent shards we read from. We start from the shard of the first range. Most of those ranges will not have enough data to fill a page with small tables. Maybe that's what's slow.

System tables use the null sharder, all data is supposed to be on shard 0. Not sure if the current code attempts to read from all shards or not, but if it does then it shouldn't be necessary.

**Comment by tgrabiec** [comment]
> > Range scans may be slow for sparse tables on many shards due to static sharding and the fact that we do a ramp-up of concurrent shards we read from. We start from the shard of the first range. Most of those ranges will not have enough data to fill a page with small tables. Maybe that's what's slow.
> 
> System tables use the null sharder, all data is supposed to be on shard 0. Not sure if the current code attempts to read from all shards or not, but if it does then it shouldn't be necessary.

Good point. Many of them are (not all of them). system.service_levels_v2 is using null sharder.

**Comment by denesb** [comment]
> > > Range scans may be slow for sparse tables on many shards due to static sharding and the fact that we do a ramp-up of concurrent shards we read from. We start from the shard of the first range. Most of those ranges will not have enough data to fill a page with small tables. Maybe that's what's slow.
> > 
> > 
> > System tables use the null sharder, all data is supposed to be on shard 0. Not sure if the current code attempts to read from all shards or not, but if it does then it shouldn't be necessary.
> 
> Good point. Many of them are (not all of them). system.service_levels_v2 is using null sharder.

The multishard reader uses the sharder of the read table, to determine which shards to read from. So if the appropriate sharder is configured, we should already read from just a single shard. I'll do some tracing to confirm.

**Comment by piodul** [comment]
@kbr-scylla is there any reason to keep this issue open? @denesb has shown that the implementation of range scans on local tables does not do unnecessary stuff.

Otherwise, I am not sure what is the definition of done for this issue.

**Comment by kbr-scylla** [comment]
Apparently not. It seems it was my misconception.

Thanks for providing the data @denesb
