### ISSUE TITLE
Bootstrap fails with `init - Startup failed: std::runtime_error (Failed to obtain IP addresses of nodes that should be seen as alive within 30s)`

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#20600]
I a bootstrapping node waits to be added to group0 for too long it may expire all entries in the raft address map and a the time it is added to group0 it will not have any address mappings. In this case the bootstrap will fail with the message in the title.

**Comment by yarongilor** [comment]
@gleb-cloudius , @aleksbykov , can you please advise - running a [multi-dc test](https://argus.scylladb.com/tests/scylla-cluster-tests/f8c6b803-1a3e-44be-8175-5ef64ba30793) of 5 regions encountered such an error like:
```
./messages.log-2025-08-10T15:56:32.155+00:00 parallel-topology-schema-changes-5--db-node-f8c6b803-2  !WARNING | scylla[5902]:  [shard  0: gms] raft_topology - (rate limiting dropped 199 similar messages) cannot map nodes [f5ed86b0-160d-432f-9f00-2
144c3e91c5d, b5fee34a-381d-48bc-9315-e0292f2e8c3b, a76bcdb8-d9f9-4e94-bffc-6358d267df15, 8e1b4116-7183-46df-8908-75b4be408617, 83f36214-8d9d-4532-91a4-68b5b351e13c, 58e42c7e-27bc-4bd6-9fa6-3af8718d2c19, 3a7f2028-aba8-4e6e-aee8-4bdc36de1532, 80996a
28-5f27-4812-98a1-9ba79f18b393, 235f252a-b259-4621-ab79-bb5217507c6d] to ips, retrying.
./messages.log-2025-08-10T15:56:33.154+00:00 parallel-topology-schema-changes-5--db-node-f8c6b803-2  !WARNING | scylla[5902]:  [shard  0: gms] raft_topology - error while handling the join response from the topology coordinator. The node will not 
join the cluster. Error: std::runtime_error (Failed to obtain IP addresses of nodes that should be seen as alive within 30s)

```

**Comment by gleb-cloudius** [comment]
> [@gleb-cloudius](https://github.com/gleb-cloudius) , [@aleksbykov](https://github.com/aleksbykov) , can you please advise - running a [multi-dc test](https://argus.scylladb.com/tests/scylla-cluster-tests/f8c6b803-1a3e-44be-8175-5ef64ba30793) of 5 regions encountered such an error like:
> 
> ```
> ./messages.log-2025-08-10T15:56:32.155+00:00 parallel-topology-schema-changes-5--db-node-f8c6b803-2  !WARNING | scylla[5902]:  [shard  0: gms] raft_topology - (rate limiting dropped 199 similar messages) cannot map nodes [f5ed86b0-160d-432f-9f00-2
> 144c3e91c5d, b5fee34a-381d-48bc-9315-e0292f2e8c3b, a76bcdb8-d9f9-4e94-bffc-6358d267df15, 8e1b4116-7183-46df-8908-75b4be408617, 83f36214-8d9d-4532-91a4-68b5b351e13c, 58e42c7e-27bc-4bd6-9fa6-3af8718d2c19, 3a7f2028-aba8-4e6e-aee8-4bdc36de1532, 80996a
> 28-5f27-4812-98a1-9ba79f18b393, 235f252a-b259-4621-ab79-bb5217507c6d] to ips, retrying.
> ./messages.log-2025-08-10T15:56:33.154+00:00 parallel-topology-schema-changes-5--db-node-f8c6b803-2  !WARNING | scylla[5902]:  [shard  0: gms] raft_topology - error while handling the join response from the topology coordinator. The node will not 
> join the cluster. Error: std::runtime_error (Failed to obtain IP addresses of nodes that should be seen as alive within 30s)
> ```

Why do you run with version 6.1.0?
