### ISSUE TITLE
scylla restart fails after MV created (core dump [shard 11:main] table - Unable to load SSTable)

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylladb#20626]
## Packages

Scylla version: `6.2.0~dev-20240823.4823a1e203f3` with build-id `e10debae1ff787e99a04652a9d600caed311b388`

Kernel Version: `6.8.0-1013-gcp`

## Issue description

- [ ] This issue is a regression.
- [+] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*
The failure happened during the add_remove_mv nemesis.
It's steps:

    Stop scylla on some of the DB nodes
    Create MV
    Start previously stopped Scylla
    Repair that DB node
    Wait for the MV building on that DB node
    Drop MV

after the scylla node was stopped and mv was created, while attempt to start the same node, scylla crashed with:

```
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4      !ERR | scylla[17293]:  [shard 10:main] table - Unable to load SSTable /var/lib/scylla/data/scylla_bench/view_test-f1c77fd061d011efa6013b4ea5895acd/me-3giy_0kta_3i
vwg22lqq0i4n35qe-big-Data.db that belongs to tablets 204 and 205, at: 0x601ca9e 0x601d0b0 0x601d3b8 0x5ae2d97 0x1b44d00 0x256d3ed 0x470148e 0x470565b 0x25c2421 0x1cb40da 0x5b20dff 0x5b2237a 0x5b23557 0x5b46e90 0x5ae3a9a /opt/scylladb/libreloc/libc.so.6+0x97506 /opt/scylladb/libreloc/libc.so.6+0x11b40b
   --------
   seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_type
   --------
   seastar::internal::coroutine_traits_base<unsigned long>::promise_type
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::smp_message_queue::async_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}, seastar::future<unsigned long>::then_wrapped_nrvo<void, seastar::smp_message_queue::async_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}>(seastar::smp_message_queue::async_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::smp_message_queue::async_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(auto:1, auto:2, auto:3)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}&, seastar::future_state<unsigned long>&&)#1}, unsigned long>
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]: Aborting on shard 2, in scheduling group main.
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]: Backtrace:
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5b51af4
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5b10cab
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5b46876
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   /opt/scylladb/libreloc/libc.so.6+0x40cff
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   /opt/scylladb/libreloc/libc.so.6+0x994a3
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   /opt/scylladb/libreloc/libc.so.6+0x40c4d
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   /opt/scylladb/libreloc/libc.so.6+0x28901
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5ae2e16
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x1b44d00
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x256d3ed
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x470148e
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x470565b
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x25c2421
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x1cb40da
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5b20dff
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5b2237a
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5b23557
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5b46e90
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   0x5ae3a9a
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   /opt/scylladb/libreloc/libc.so.6+0x97506
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:   /opt/scylladb/libreloc/libc.so.6+0x11b40b
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4      !ERR | scylla[17293]:  [shard 11:main] table - Unable to load SSTable /var/lib/scylla/data/scylla_bench/view_test-f1c77fd061d011efa6013b4ea5895acd/me-3giy_0kta_2py8g2pnfcd9c1d0w6-big-Data.db that belongs to tablets 210 and 211, at: 0x601ca9e 0x601d0b0 0x601d3b8 0x5ae2d97 0x1b44d00 0x256d3ed 0x470148e 0x470565b 0x25c2421 0x1cb40da 0x5b20dff 0x5b2237a 0x5b23557 0x5b46e90 0x5ae3a9a /opt/scylladb/libreloc/libc.so.6+0x97506 /opt/scylladb/libreloc/libc.so.6+0x11b40b
```

## Impact

Scylla cant start itself and node became unavailable

## Installation details

Cluster size: 5 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-5 (35.243.156.28 | 10.142.0.98) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4 (34.23.201.172 | 10.142.0.96) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-3 (34.23.167.96 | 10.142.0.91) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-2 (35.196.151.252 | 10.142.0.77) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-1 (35.227.30.195 | 10.142.0.54) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-6-2-0-dev-x86-64-2024-08-24t01-48-33` (gce: undefined_region)

Test: `longevity-large-partition-200k-pks-4days-gce-test`
Test id: `2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b`
Test name: `scylla-master/tier1/longevity-large-partition-200k-pks-4days-gce-test`
Test method: `longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4ff526a2f249ab9291cb41af6d3a6381903aafcf/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b)
- Show all stored logs command: `$ hydra investigate show-logs 2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b`

## Logs:
- **core.scylla-longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4-2024-08-24_09-18-38.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.107.2167bee55c934888a654510991f23bf6.17293.1724490892000000./core.scylla.107.2167bee55c934888a654510991f23bf6.17293.1724490892000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.107.2167bee55c934888a654510991f23bf6.17293.1724490892000000./core.scylla.107.2167bee55c934888a654510991f23bf6.17293.1724490892000000.zst)
- **core.scylla-longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4-2024-08-24_09-21-15.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.107.2167bee55c934888a654510991f23bf6.17654.1724491071000000./core.scylla.107.2167bee55c934888a654510991f23bf6.17654.1724491071000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.107.2167bee55c934888a654510991f23bf6.17654.1724491071000000./core.scylla.107.2167bee55c934888a654510991f23bf6.17654.1724491071000000.zst)
- **db-cluster-2ceb5eef.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/db-cluster-2ceb5eef.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/db-cluster-2ceb5eef.tar.gz)
- **sct-runner-events-2ceb5eef.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/sct-runner-events-2ceb5eef.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/sct-runner-events-2ceb5eef.tar.gz)
- **sct-2ceb5eef.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/sct-2ceb5eef.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/sct-2ceb5eef.log.tar.gz)
- **loader-set-2ceb5eef.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/loader-set-2ceb5eef.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/loader-set-2ceb5eef.tar.gz)
- **monitor-set-2ceb5eef.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/monitor-set-2ceb5eef.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b/20240824_092521/monitor-set-2ceb5eef.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-large-partition-200k-pks-4days-gce-test/32/)
[Argus](https://argus.scylladb.com/test/996501ad-c137-40ef-8dcc-a7d12f0ba3b6/runs?additionalRuns[]=2ceb5eef-0eef-4ef5-b420-eee2ebb1dd1b)
</details>

**Comment by timtimb0t** [comment]
the issue has similar to #19872 symptom

**Comment by mykaul** [comment]
@timtimb0t - please decode the backtrace.

**Comment by timtimb0t** [comment]
decoded backtrace:
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]: Backtrace:
2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:825
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:870
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4019
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3995
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3991
/data/scylla-s3-reloc.cache/by-build-id/e10debae1ff787e99a04652a9d600caed311b388/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=8f53abaad945a669f2bdcd25f471d80e077568ef, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:56
replica::tablet_storage_group_manager::compaction_group_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/table.cc:1029
replica::table::table_state_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/database.hh:1225
 (inlined by) compaction::shard_reshaping_compaction_task_impl::run() at ././compaction/task_manager_module.cc:602
tasks::task_manager::task::impl::run_to_completion() at ././tasks/task_manager.cc:214
tasks::task_manager::task::start() at ././tasks/task_manager.cc:329
_ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36shard_reshaping_compaction_task_implEJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RN5utils11tagged_uuidINS_11task_id_tagEEERN8sstables17sstable_directoryERN7seastar7shardedIN7replica8databaseEEERNSH_12reshape_modeERSt8functionIFNSK_13lw_shared_ptrINSH_7sstableEEEjEERSS_IFbRKSV_EERmEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNSK_10shared_ptrIS1_EEDpOT0__XcvS17__fL0p_spclsr3stdE7forwardIS1A_EfL0p0_EERSt7same_asIS17_EEEENSK_6futureINST_IS15_EEEENS_9task_infoES1C_ at ././tasks/task_manager.hh:360
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:80
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2634
seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3104
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3272
std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4531
seastar::posix_thread::start_routine(void*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
start_thread at ??:?
__clone3 at :?

2024-08-24T09:14:52.957+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4     !INFO | scylla[17293]: Backtrace:
2024-08-24T09:14:52.958+00:00 longevity-large-partitions-200k-pks-db-node-2ceb5eef-0-4      !ERR | scylla[17293]:  [shard 11:main] table - Unable to load SSTable /var/lib/scylla/data/scylla_bench/view_test-f1c77fd061d011efa6013b4ea5895acd/me-3giy_0kta_2py8g2pnfcd9c1d0w6-big-Data.db that belongs to tablets 210 and 211, at:
[Backtrace #1]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_0>(seastar::current_backtrace_tasklocal()::$_0&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:97
seastar::current_tasktrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:148
seastar::current_backtrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:181
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:50
 (inlined by) seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:54
replica::tablet_storage_group_manager::compaction_group_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/table.cc:1029
replica::table::table_state_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/database.hh:1225
 (inlined by) compaction::shard_reshaping_compaction_task_impl::run() at ././compaction/task_manager_module.cc:602
tasks::task_manager::task::impl::run_to_completion() at ././tasks/task_manager.cc:214
tasks::task_manager::task::start() at ././tasks/task_manager.cc:329
_ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36shard_reshaping_compaction_task_implEJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RN5utils11tagged_uuidINS_11task_id_tagEEERN8sstables17sstable_directoryERN7seastar7shardedIN7replica8databaseEEERNSH_12reshape_modeERSt8functionIFNSK_13lw_shared_ptrINSH_7sstableEEEjEERSS_IFbRKSV_EERmEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNSK_10shared_ptrIS1_EEDpOT0__XcvS17__fL0p_spclsr3stdE7forwardIS1A_EfL0p0_EERSt7same_asIS17_EEEENSK_6futureINST_IS15_EEEENS_9task_infoES1C_ at ././tasks/task_manager.hh:360
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:80
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2634
seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3104
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3272
std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4531
seastar::posix_thread::start_routine(void*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
start_thread at ??:?
__clone3 at :?

**Comment by mykaul** [comment]
> the issue has similar to #19872 symptom

which ended up as a dup of https://github.com/scylladb/scylladb/issues/19378 - and was fixed though? 

@raphaelsc - can you please take a look at this?

**Comment by raphaelsc** [comment]
> > the issue has similar to #19872 symptom
> 
> which ended up as a dup of #19378 - and was fixed though?
> 
> @raphaelsc - can you please take a look at this?

looking at it already... I think it's related to reshape not being aware that a sstable produced by repair in parallel to split can be unsplit until it's added to table's sstable set. I will try to confirm later today with a reproducer.

**Comment by raphaelsc** [comment]
@timtimb0t please redo the test on master, since the fix was merged.
