### ISSUE TITLE
[dtest] Tests / dtest with tablets / update_cluster_layout_tests.TestUpdateClusterLayout.test_removenode_rejoin : Startup failed: seastar::gate_closed_exception (gate closed)

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#20630]
```
failed on teardown with "AssertionError: Unexpected errors found:
node3: 1 errors
ERROR 2024-09-16 12:36:29,906 [shard 0:main] init - Startup failed: seastar::gate_closed_exception (gate closed)"
```

Logs:
* [test.log](https://github.com/user-attachments/files/17022726/test.log)
* [node3.log](https://github.com/user-attachments/files/17022727/node3.log)
* [node2.log](https://github.com/user-attachments/files/17022728/node2.log)
* [node1.log](https://github.com/user-attachments/files/17022729/node1.log)

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylla-dtest/pull/4948 ?

**Comment by denesb** [comment]
Yes, possibly. I hit it just before the fix got in.
