### ISSUE TITLE
sync-labels.yaml adds labels to PR which references an issue

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#20659]
see #20632, which only references an issue instead of fixing it or closing it. but the workflow still sync'ed all the labels attached to the references issue to the PR referencing it. actually, the PR is a cleanup, and it just *references* the issue.

i think, in this case, we should not sync the labels. better off tighten the criteria of syncing labels, so that only the PRs which claims "Fixes" or "Resolves" (for a complete list, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) are sync'ed with the fixed issue.

**Comment by tchaikov** [comment]
cc @yaronkaikov

**Comment by yaronkaikov** [comment]
@tchaikov I don't think there is a problem here. let me explain:

in #20632 the PR description was edited by @bhalevy 
![image](https://github.com/user-attachments/assets/833c9a20-5e66-4f84-99d3-b22959526fc0)

if you check the original PR description you can see that there was an official reference to #20608 

![image](https://github.com/user-attachments/assets/5f225d21-c731-4ca0-8047-a461c1676ee5)

The sync labels from a linked issue is taking place while opening the PR. if you edit it after , we will not remove the labels

**Comment by tchaikov** [comment]
@yaronkaikov thank you for looking into this. i should have taken the time to examine the cover letter's history before sounding a false alarm.
