### ISSUE TITLE
Compile scylla dev with -g CPP FLAG 

### ISSUE THREAD

**Issue by dani-tweig** [scylladb/scylladb#20745]
- Adding the debug flag will give us more information when we need backtrace for troubleshooting purpose.
- Publish relocatable of dev mode

Creating this issue instead of https://github.com/scylladb/scylla-pkg/issues/4368 

CC @bhalevy, @tchaikov, @regevran

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylladb/issues/20721
