### ISSUE TITLE
SStable's clustering key index lookup may yield incorrect position 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#20766]
Affects scylla version >= 4.6.0

When this bug is triggered, an sstable read may use an incorrect index block. There will be no parsing errors. This may manifest as missing data which actually exists. That's the case if we jump to a position which is after the key. If we're jumping to an earlier position, we will still find the row, it will just take longer.

Clustering key index lookup is based on the index file page cache. We do a binary search within the index, which involves parsing index blocks touched by the algorithm. Index file pages are 4 KB chunks which are stored in LSA.   

To parse the first key of the block, we reuse `clustering_parser`, which is also used when parsing the data file. The parser is stateful and accepts consecutive chunks as `temporary_buffer`s. The parser is supposed to keep its state across chunks.

In b1b5bda848c0624a3e7e10a51c1a155421d2fdfe, the parser was changed to keep shared fragments of the buffer passed to the parser in its internal state (across pages) rather than copy the fragments into a new buffer. This is problematic when buffers come from page cache because LSA buffers may be moved around or evicted. So the temporary_buffer which is a view on the LSA buffer is valid only around the duration of a single consume() call to the parser:

```c++
 template <typename Consumer>
    future<> consume_stream(cached_file::stream& s, Consumer& c) {
        return repeat([&] {
            return s.next_page_view().then([&] (cached_file::page_view&& page) {
                if (!page) {
                    on_internal_error(sstlog, "End of stream while parsing");
                }
                return _as(_cached_file.region(), [&] {
                    auto buf = page.get_buf();
                    return stop_iteration(c.consume(buf) == data_consumer::read_status::ready);
                });
            });
        });
    }
```

If the blob which is parsed (e.g. variable-length clustering key component) spans pages, the fragments stored in the parser may be invalidated before the component is fully parsed. As a result, the parsed clustering key may have incorrect component values. This never causes parsing errors because the "length" field is always parsed from the current buffer, which is valid, and component parsing will end at the right place in the next (valid) buffer. 

The problematic path for clustering_key parsing is the one which calls `primitive_consumer::read_bytes()`, which is called for example for `text` components. Fixed-size components are not parsed like this, they store the intermediate state by copying data. 

```c++
    inline read_status read_bytes(temporary_buffer<char>& data, uint32_t len, fragmented_temporary_buffer& where) {
        if (data.size() >= len) {
            auto fragments = std::move(where).release();
            fragments.clear();
            fragments.push_back(data.share(0, len));
            where = fragmented_temporary_buffer(std::move(fragments), len);
            data.trim_front(len);
            return read_status::ready;
        } else {
            // copy what we have so far, read the rest later
            _read_bytes.clear();
            _read_bytes.push_back(data.share());

// ^^ data.share() is problematic, stores a view to the buffer which may be invalidated.

            _read_bytes_len = len;
            _read_bytes_where = &where;
            _pos = data.size();
            data.trim(0);
            _prestate = prestate::READING_BYTES;
            return read_status::waiting;
        }
    }
``` 

This may cause incorrect clustering keys to be parsed when doing binary search in the index, diverting the search to an incorrect block. The incorrect parsing has a scope of a single read because parsed blocks are cached within the reader. So later readers will not be affected. It is likely that the next parsing will not hit the problem for the same key, because both pages will be hot in cache, and the probability that buffers will be invalidated across pages is low. 

The problem is more likely to happen with larger indexes. If the index fits within 32KB, all its pages will be hot in cache due to read-ahead done to read the partition index entry. If pages are hot, they are unlikely to be invalidated during parsing because they are recently accessed and preemption when parsing across pages is unlikely. Also, most memory allocation is done when parsing the first page so LSA movement is unlikely.

Reducing "column-index-size-in-kb" makes the problem more likely because it makes the index larger, and the risk of page cache misses is higher.

Larger clustering keys make the problem more likely, because page crossing is more likely.

**Comment by michoecho** [comment]
Wow. Quite a find.

Out of curiosity: how did you find it, in the end? Did you figure it out purely from coredumps, or did you have a reproducer and progressively added logs?

> In https://github.com/scylladb/scylladb/commit/b1b5bda848c0624a3e7e10a51c1a155421d2fdfe, the parser was changed to keep shared fragments of the buffer passed to the parser in its internal state (across pages) rather than copy the fragments into a new buffer. This is problematic when buffers come from page cache because LSA buffers may be moved around or evicted.

Actually it seems that when b1b5bda848c0624a3e7e10a51c1a155421d2fdfe was written, it wasn't problematic, because at the time the `temporary_buffer` returned from `cached_file` used to keep a live copy of the contents. This was only changed later — to avoid copying the data out of LSA — in 934824394aed64dcdb30a15e074b5067ae533647.

> the temporary_buffer which is a view on the LSA buffer is valid only

We made an evil API. The entire codebase trains us to expect that holding a `temporary_buffer` will keep its contents alive. Except for this one case where it doesn't. It was begging for something to go wrong.

**Comment by avikivity** [comment]
How does data.share() end up invalid? It's whole purpose is to keep data alive. Do we reuse the buffer?

Ah I see @michoecho explains it, I'll go look there.

**Comment by tgrabiec** [comment]
> because LSA buffers may be moved around or evicted. So the temporary_buffer which is a view on the LSA buffer is valid only around the duration of a single consume() call to the parser:

" because LSA buffers may be moved around or evicted. So the temporary_buffer which is a view on the LSA buffer is valid only around the duration of a single consume() call to the parser:"

**Comment by avikivity** [comment]
```c++
        // Returns a buffer which reflects contents of this page.
        // The buffer will not prevent eviction.
        // The buffer is invalidated when the page is evicted or when the owning LSA region invalidates references.
        temporary_buffer<char> get_buf_weak() {
            return temporary_buffer<char>(_lsa_buf.get(), _lsa_buf.size(), deleter());
        }
```

Empty deleter() - more or less asking for it.

**Comment by tgrabiec** [comment]
> Wow. Quite a find.
> 
> Out of curiosity: how did you find it, in the end? Did you figure it out purely from coredumps, or did you have a reproducer and progressively add logs (or bisected, or live-debugged it)?

Reproducer + asserts + deduction from core dumps + some guessing. I had a semi-reliable reproducer, by adding a loop of cache invalidation parallel to the read workload. Added code which copies keys around lookups, from which I deduced that the problem is not with instability of the search keys. Added re-reading of promoted index blocks and a check that the second read gives the same key as the existing entry, which was triggered. I got mismatched keys. Based on the schema and other entries I knew how good keys look like, they should have a timestamp in the first component. After several cores, I noticed that the front of the key looks wrong, but the back looks good. The bad key had other data in that component which looked like a text component of a different key, or a timestamp which was only partially good. The point where they broke matched with page boundary. Which was a hint that the problem is either with the page cache or the parser. I logged returned pages and they were good, so it must have been the parser. I didn't trust that bisecting would find it because the reproducer was fragile.

**Comment by mykaul** [comment]
> > Wow. Quite a find.
> > Out of curiosity: how did you find it, in the end? Did you figure it out purely from coredumps, or did you have a reproducer and progressively add logs (or bisected, or live-debugged it)?
> 
> Reproducer + asserts + deduction from core dumps + some guessing. I had a semi-reliable reproducer, by adding a loop of cache invalidation parallel to the read workload. Added code which copies keys around lookups, from which I deduced that the problem is not with instability of the search keys. Added re-reading of promoted index blocks and a check that the second read gives the same key as the existing entry, which was triggered. I got mismatched keys. Based on the schema and other entries I knew how good keys look like, they should have a timestamp in the first component. After several cores, I noticed that the front of the key looks wrong, but the back looks good. The bad key had other data in that component which looked like a text component of a different key, or a timestamp which was only partially good. The point where they broke matched with page boundary. Which was a hint that the problem is either with the page cache or the parser. I logged returned pages and they were good, so it must have been the parser. I didn't trust that bisecting would find it because the reproducer was fragile.

Amazing work @tgrabiec !
