### ISSUE TITLE
rename cql-pytest without a hyphen

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#20846]
Four years ago, I created test/cql-pytest (475d8721a5d2d957bfd0fb5ef210bb5809ddcd9d), as a way to easily write functional tests for CQL requests in Python, using the "pytest" framework. This was the second time that we used pytest in the project (the first use was in test/alternator, a few months earlier), so I stuck the suffix "-pytest" on the directory name, without thinking too much of it.

Fast forward a few years, developers started complaining that it was called "cql-pytest", with a hyphen (one user even went as far as creating a pull request - https://github.com/scylladb/scylladb/pull/11395). The problem is that Python doesn't like directory names with hyphens - they don't look like a valid "package". This didn't matter if you were using cql-pytest in the way I designed it, but other developers had their own preferred ways to run Python tests, and sometimes the "invalid" directory name interfered.

So the purpose of this issue is to rename **test/cql-ptyest** to a name without a hyphen.

Some have suggested to replace the hyphen with an underscore. However, underscore is harder to type (requires a shift!), and https://peps.python.org/pep-0008/ recommends against it: "_Underscores can be used in the module name if it improves readability. ... the use of underscores is discouraged._".

So I propose the easier to type, shorter, and underscore-free - **test/cqlpy**.

This name test/cqlpy still reminds the reader that these are **Python** tests - nowadays all Python tests across the company use pytest anyway. And the word "test" already appears in the top-level directory name, so in the old name was redundant.

Note that we couldn't just call these tests test/cql because that name is taken (by CQL-only approval tests). And I actually like the reminder that these are Python tests in the directory's name, so I like the "py" in the name.

cc @kostja @xtrey @temichus @kbr-scylla

**Comment by kbr-scylla** [comment]
yay
