### ISSUE TITLE
nodetool repair option

### ISSUE THREAD

**Issue by infordb** [scylladb/scylladb#2084]
* scylla version : scylla-1.5.0-20161221.654919c.el7.centos.x86_64

I applied the parallel repair option, like "nodetool repair -par"
but it does not work according to the log.

I think the pr option also does not  work

Let me know which repair options are not currently supported
 ex) unsupported incremental repair

[root]fomstap01:/root>nodetool repair **-par** test
[2017-02-15 09:04:01,407] Starting repair command #7, repairing 1 ranges for keyspace test (parallelism=**SEQUENTIAL**, full=true)
[2017-02-15 09:04:01,512] Repair session 7 finished

[root]fomstap01:/root>nodetool repair **-pr** test
[2017-02-15 09:04:12,519] Starting repair command #8, repairing 1 ranges for keyspace test (parallelism=SEQUENTIAL, full=true)
[2017-02-15 09:04:12,623] Repair session 8 finished

**Comment by nyh** [comment]
Scylla does not adhere to the "parallel" or "sequential" repair options in the regular Cassandra sense, and performs the repair differently from both. So both options are silently ignored.
Can you please clarify what this issue would like? Is it simply about the log being incorrect? Or something more profound, e.g., you really want the repair to work differently somehow?

Two additional comments:

1. The "-pr" option you tried too is **not** parallel repair, but rather "partitioner range" or "primary range", where a node only repairs part of the range it owns - only the part for which it is the "primary" owner (the first of several replicas). 
2. In Cassandra 3, there is no "-par" option - it is the default, and instead there is the "-seq" option. It is possible (but I didn't check) that it silently ignores a "-par" option (knowing it is the default), but our code assumes the default is SEQUENTIAL (while, again, ignoring this ;-)), which explains the misleading log message.

**Comment by tzach** [comment]
This can be close as not planned.

**Comment by nyh** [comment]
It's not clear what this issue is about and since then we've already improved the documentation and opened other more specific issues about repair options, so let's close this one.
