### ISSUE TITLE
Control Throttling of Restore

### ISSUE THREAD

**Issue by regevran** [scylladb/scylladb#20868]
To mimic today's behavior when `rclone` is replaced by `scylla` we need a mechanism to throttle the restore process.
This is the rclone API that we use today: `POST /rclone/core/bwlimit`

**Comment by Michal-Leszczynski** [comment]
Mentioned rclone API allows to set rate in MiB/s.
For completness, here is how user can set the rate limit via SM flag:
```
      --rate-limit [<dc>:]<limit>             Limits the upload rate (as expressed in  megabytes (MiB) per second) at which snapshotfiles can be uploaded from a Scylla node to its backup destination.
                                              You can set limits for more than one DC using a comma-separated list expressed in the format [<dc>:]<limit>.
                                              The <dc>: part is optional and is only needed when different datacenters require different upload limits.
                                              Set to 0 for no limit (default 100).

```

**Comment by xemul** [comment]
Restore task is running in a "streaming" scheduling group, that has stream_io_throughput_mb_per_sec option to control IO bandwidth. It will be enough to control this task, it will be neither CPU nor networking bound.

The option is live-updateable, you can modify scylla.yaml and send HUP to scylla, you can update the option via system.config table with the help if CQL UPDATE query, or there's API call to modify config options (well, at least you can read them)

But we may want to relocate restore task into its own scheduling group, as tuning the backup IO bandwidth will implicitly affect repair tasks running in the same sched groups.

**Comment by regevran** [comment]
> But we may want to relocate restore task into its own scheduling group, as tuning the backup IO bandwidth will implicitly affect repair tasks running in the same sched groups.

Let's defer this to the time we see problems.

**Comment by regevran** [comment]
> To mimic today's behavior when rclone is replaced by scylla we need a mechanism to throttle the restore process.
