### ISSUE TITLE
scylla_commitlog_memory_buffer_bytes ever growing since 6.0

### ISSUE THREAD

**Issue by horschi** [scylladb/scylladb#20862]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 6.0.2
Cluster size: Same issue with 6 node or 20 node cluster
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 22.04

The metric "scylla_commitlog_memory_buffer_bytes" seems to be ever growing since we have updated to 6.0.2:
![image](https://github.com/user-attachments/assets/b4121b84-6b36-40c9-9453-261a3b07a365)

9/22 is the day the cluster was upgraded from 5.4 to 6.0. The times when the lines drop to 0 is when the cluster got restarted. This is the case on various different landscapes.

The metric is defined as
`sm::make_gauge("memory_buffer_bytes", totals.buffer_list_bytes, sm::description("Holds the total number of bytes in internal memory buffers.")),`

**Comment by lucowehrlin** [comment]
Observed this in our cluster, and this was an indicator that something went wrong. After a while of observing this metric increase constantly, our system started doing alot of smaller memtable-flushes, that ultimately made the cluster very unresponsive.

Is this now just changing the optics, or would this change also fix (probably) unnecessary flushes?

**Comment by elcallio** [comment]
The `scylla_commitlog_memory_buffer_bytes` growing is just a mismatched inc/dec. There is no actual memory being leaked or anything. Nor does it affect flushing other than if something external would be looking at metrics and initiating it via nodetool or similar. 
So no.
