### ISSUE TITLE
 Failed to load SSTable and got `Aborting on shard` and `coredump` after upgrade during Scylla start [tablets are enabled]

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#20911]
## Packages

Base Scylla version: `6.2.0~rc0-20240917.cbc53f0e81f5` with build-id `a76b6bece2744410fa062558bb8df6a360556565`
Target Scylla version (or git commit hash): `6.3.0~dev-20240927.c17d35371846` with build-id `a9b08d0ce1f3cf99eb39d7a8372848fa2840dc1d`

Kernel Version: `6.8.0-1016-aws`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Tablets are enabled.
**NOTE:** This issue does not happen when tablets are disabled.
Upgrade from `6.2.0~rc0-20240917.cbc53f0e81f5` to `6.3.0~dev-20240927.c17d35371846` .
The node `perf-latency-upgrade-ubuntu-db-node-7daec109-2` got `Aborting on shard` and `coredump` after upgrade during Scylla start.
```
Sep 29 22:54:27.513929 perf-latency-upgrade-ubuntu-db-node-7daec109-2 scylla[17239]:  [shard 1:main] 
table - Unable to load SSTable /var/lib/scylla/data/keyspace1/standard1-1c6d6a807e9e11ef9
da87e4969505689/me-3gjy_1ozn_5jjn42ubdccao0qzto-big-Data.db that belongs to tablets 120 and 123, at: 0x61aa65e 0x61aac80 0x61aaf88 0x5c6e8d7 0x1b6aff5 0x25ab1ad 0x4836cae 0x483ae7b 0x260a601 0x1cdc26a 0x5cac8af 0x5cade2a 0x5caf007 0x5cd33b0 0x5c6f5ea /opt/scylladb/libreloc/libc.so.6+0x976d6 /opt/scylladb/libreloc/libc.so.6+0x11b60b
--------
seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_
type
--------
seastar::internal::coroutine_traits_base<unsigned long>::promise_type
--------
seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::smp_message_queue::asy
nc_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}, seastar::future<unsigned long>::then_wrapped_nrvo<void, seastar::smp_message_queue::async_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_r
eshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}>(seastar::smp_message_queue::async_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::smp_message_queue::async_work_item<seastar::sharded<sstables::sstable_directory>::map_reduce0<compaction::table_reshaping_compaction_task_impl::run()::$_0, unsigned long, std::plus<unsigned long> >(auto:1, auto:2, auto:3)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>::run_and_dispose()::{lambda(auto:1)#1}&, seastar::future_state<unsigned long>&&)#1}, unsigned long>
```

Aborting on shard:
```
Sep 29 22:54:27.514372 perf-latency-upgrade-ubuntu-db-node-7daec109-2 scylla[17239]: Aborting on shard 1, in scheduling group main.
Sep 29 22:54:27.514372 perf-latency-upgrade-ubuntu-db-node-7daec109-2 scylla[17239]: Backtrace:
0x5cde604
0x5c9c76b
0x5cd2d98
/opt/scylladb/libreloc/libc.so.6+0x40cff
/opt/scylladb/libreloc/libc.so.6+0x99663
/opt/scylladb/libreloc/libc.so.6+0x40c4d
/opt/scylladb/libreloc/libc.so.6+0x28901
0x5c6e956
0x1b6aff5
0x25ab1ad
0x4836cae
0x483ae7b
0x260a601
0x1cdc26a
0x5cac8af
0x5cade2a
0x5caf007
0x5cd33b0
0x5c6f5ea
/opt/scylladb/libreloc/libc.so.6+0x976d6
/opt/scylladb/libreloc/libc.so.6+0x11b60b
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:823
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:868
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3960
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3937
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3932
/data/scylla-s3-reloc.cache/by-build-id/a9b08d0ce1f3cf99eb39d7a8372848fa2840dc1d/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=77c77fee058b19c6f001cf2cb0371ce3b8341211, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:56
replica::tablet_storage_group_manager::compaction_group_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/table.cc:1087
replica::table::table_state_for_sstable(seastar::lw_shared_ptr<sstables::sstable> const&) const at ././replica/database.hh:1223
 (inlined by) compaction::shard_reshaping_compaction_task_impl::run() at ././compaction/task_manager_module.cc:626
tasks::task_manager::task::impl::run_to_completion() at ././tasks/task_manager.cc:214
tasks::task_manager::task::start() at ././tasks/task_manager.cc:329
_ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36shard_reshaping_compaction_task_implEJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RN5utils11tagged_uuidINS_11task_id_tagEEERN8sstables17sstable_directoryERN7seastar7shardedIN7replica8databaseEEERNSH_12reshape_modeERSt8functionIFNSK_13lw_shared_ptrINSH_7sstableEEEjEERSS_IFbRKSV_EERmEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNSK_10shared_ptrIS1_EEDpOT0__XcvS17__fL0p_spclsr3stdE7forwardIS1A_EfL0p0_EERSt7same_asIS17_EEEENSK_6futureINST_IS15_EEEENS_9task_infoES1C_ at ././tasks/task_manager.hh:360
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<seastar::lw_shared_ptr<tasks::task_manager::task> >::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:80
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2578
seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3044
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3212
std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:4525
seastar::posix_thread::start_routine(void*) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
start_thread at ??:?
__clone3 at :?
```

Coredump:
```
2024-09-29 22:57:23.233 <2024-09-29 22:54:27.000>: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=5b5885d5-ef84-42db-ac04-6a466e36c31c node=Node perf-latency-upgrade-ubuntu-db-
node-7daec109-2 [3.231.4.23 | 10.12.0.182]
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000./core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17
239.1727650467000000.zst
backtrace=           PID: 17239 (scylla)
           UID: 106 (scylla)
           GID: 108 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Sun 2024-09-29 22:54:27 UTC (2min 47s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 5 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --log-to-syslog 1 --log-t
o-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7 --lock-memory=1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: scylla-server.slice
       Boot ID: 0fcd70fc182e4d7e9e9d6c769da247f0
    Machine ID: ec26faf86857d0d610151c8f7671aba3
      Hostname: perf-latency-upgrade-ubuntu-db-node-7daec109-2
       Storage: /var/lib/systemd/coredump/core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000.zst (present)
  Size on Disk: 686.7M
       Message: Process 17239 (scylla) of user 106 dumped core.
                Stack trace of thread 17240:
                #0  0x00007b31ea4a8664 __pthread_kill_implementation (libc.so.6 + 0x99664)
                #1  0x00007b31ea44fc4e raise (libc.so.6 + 0x40c4e)
                #2  0x00007b31ea437902 abort (libc.so.6 + 0x28902)
                #3  0x0000000005c6e957 _ZN7seastar17on_internal_errorERNS_6loggerESt17basic_string_viewIcSt11char_traitsIcEE (scylla + 0x5a6e957)
                #4  0x0000000001b6aff6 _ZNK7replica28tablet_storage_group_manager28compaction_group_for_sstableERKN7seastar13lw_shared_ptrIN8sstables7sstableEEE (scylla + 0x196aff6)
                #5  0x00000000025ab1ae _ZN10compaction36shard_reshaping_compaction_task_impl3runEv (scylla + 0x23ab1ae)
                #6  0x0000000004836caf _ZN5tasks12task_manager4task4impl17run_to_completionEv (scylla + 0x4636caf)
                #7  0x000000000483ae7c _ZN5tasks12task_manager4task5startEv (scylla + 0x463ae7c)
                #8  0x000000000260a602 _ZN5tasks12task_manager6module19make_and_start_taskIN10compaction36shard_reshaping_compaction_task_implEJRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RN5utils11tagged_uuidINS_11task_id_tagEEERN8sstables17sstable_directoryERN7seastar7shardedIN7replica8databaseEEERNSH_12reshape_modeERSt8functionIFNSK_13lw_shared_ptrINSH_7sstableEEEjEERSS_IFbRKSV_EERmEQaasr3stdE12is_base_of_vINS0_4task4implET_ErQNSK_10shared_ptrIS1_EEDpOT0__XcvS17__fL0p_spclsr3stdE7forwardIS1A_EfL0p0_EERSt7same_asIS17_EEEENSK_6futureINST_IS15_EEEENS_9task_infoES1C_.resume (scylla + 0x240a602)
                #9  0x0000000001cdc26b _ZN7seastar8internal21coroutine_traits_baseINS_13lw_shared_ptrIN5tasks12task_manager4taskEEEE12promise_type15run_and_disposeEv (scylla + 0x1adc26b)
                #10 0x0000000005cac8b0 _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla + 0x5aac8b0)
                #11 0x0000000005cade2b _ZN7seastar7reactor14run_some_tasksEv (scylla + 0x5aade2b)
                #12 0x0000000005caf008 _ZN7seastar7reactor6do_runEv (scylla + 0x5aaf008)
                #13 0x0000000005cd33b1 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE3$_0E9_M_invokeERKSt9_Any_data (scylla + 0x5ad33b1)
                #14 0x0000000005c6f5eb _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x5a6f5eb)
                #15 0x00007b31ea4a66d7 start_thread (libc.so.6 + 0x976d7)
                #16 0x00007b31ea52a60c __clone3 (libc.so.6 + 0x11b60c)
```

download_instructions:
```
gsutil cp gs://upload.scylladb.com/core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000./core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000.zst .
unzstd core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000.zst
```

## Impact

Scylla could not start on the node after upgrade

## How frequently does it reproduce?

It happened first time with `6.3.0~dev-20240927.c17d35371846` and reproduced in the next run - https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=ee4a7c51-53c0-4e87-a7d0-132321f6e02f

## Installation details

Cluster size: 6 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- perf-latency-upgrade-ubuntu-db-node-7daec109-6 (44.195.21.122 | 10.12.3.93) (shards: 7)
- perf-latency-upgrade-ubuntu-db-node-7daec109-5 (44.204.137.156 | 10.12.2.29) (shards: 7)
- perf-latency-upgrade-ubuntu-db-node-7daec109-4 (44.211.85.129 | 10.12.0.192) (shards: 7)
- perf-latency-upgrade-ubuntu-db-node-7daec109-3 (44.203.51.134 | 10.12.1.165) (shards: 7)
- perf-latency-upgrade-ubuntu-db-node-7daec109-2 (3.231.4.23 | 10.12.0.182) (shards: 7)
- perf-latency-upgrade-ubuntu-db-node-7daec109-1 (44.204.223.204 | 10.12.2.56) (shards: -1)

OS / Image: `ami-07ad144f2c38d82db` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-during-rolling-upgrade-tablets`
Test id: `7daec109-58ee-4a3b-9815-e1cbc7e86532`
Test name: `scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade-tablets`
Test method: `performance_regression_test.PerformanceRegressionUpgradeTest.test_latency_write_with_upgrade`
Test config file(s):

- [perf-regression-latency-650gb-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/daf5adb4ee3b60a952ed8b4eff30e7f5c44720ec/test-cases/performance/perf-regression-latency-650gb-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7daec109-58ee-4a3b-9815-e1cbc7e86532`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7daec109-58ee-4a3b-9815-e1cbc7e86532)
- Show all stored logs command: `$ hydra investigate show-logs 7daec109-58ee-4a3b-9815-e1cbc7e86532`

## Logs:
- **core.scylla-perf-latency-upgrade-ubuntu-db-node-7daec109-2-2024-09-29_22-57-23.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000./core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000./core.scylla.106.0fcd70fc182e4d7e9e9d6c769da247f0.17239.1727650467000000.zst)
- **db-cluster-7daec109.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/db-cluster-7daec109.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/db-cluster-7daec109.tar.gz)
- **sct-runner-events-7daec109.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/sct-runner-events-7daec109.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/sct-runner-events-7daec109.tar.gz)
- **sct-7daec109.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/sct-7daec109.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/sct-7daec109.log.tar.gz)
- **loader-set-7daec109.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/loader-set-7daec109.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/loader-set-7daec109.tar.gz)
- **monitor-set-7daec109.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/monitor-set-7daec109.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7daec109-58ee-4a3b-9815-e1cbc7e86532/20240929_225959/monitor-set-7daec109.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/perf-regression/job/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade-tablets/7/)
[Argus](https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=7daec109-58ee-4a3b-9815-e1cbc7e86532)
</details>

**Comment by juliayakovlev** [comment]
I found another run with this error.
Upgrade to `6.3.0~dev-0.20240924.36d68ec955d4 with build-id 3ece0fa61f67ac70e07b4083ed230be4094ad810`
https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=505b7ce7-0c1a-4ef8-b52e-2bc754bc808c

Actually it is first run of this test. So this issue may be not new. But we do not know it.
Do I need to search first occurrence?

**Comment by roydahan** [comment]
I don't think it's necessary.

**Comment by mykaul** [comment]
Fix is probably - https://github.com/scylladb/scylladb/pull/20737 - which was not yet backported to 6.0.
@raphaelsc - can you confirm?

**Comment by mykaul** [comment]
> Upgrade to `6.3.0~dev-0.20240924.36d68ec955d4 with build-id 3ece0fa61f67ac70e07b4083ed230be4094ad810`

The fix (above) was merged only on the 25th of Sep.

**Comment by juliayakovlev** [comment]
> > Upgrade to `6.3.0~dev-0.20240924.36d68ec955d4 with build-id 3ece0fa61f67ac70e07b4083ed230be4094ad810`
> 
> The fix (above) was merged only on the 25th of Sep.

This issue happened in the run 29.9
And same failure 30.9 - https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=ee4a7c51-53c0-4e87-a7d0-132321f6e02f

**Comment by mykaul** [comment]
> > > Upgrade to `6.3.0~dev-0.20240924.36d68ec955d4 with build-id 3ece0fa61f67ac70e07b4083ed230be4094ad810`
> > 
> > 
> > The fix (above) was merged only on the 25th of Sep.
> 
> @mykaul This issue happened in the run 29.9 And same failure 30.9 - [https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=ee4a7c51-53c0-4e87-a7d0-132321f6e02f](https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns%5B%5D=ee4a7c51-53c0-4e87-a7d0-132321f6e02f)

But the Scylla version used is 6.2.0~rc0-20240917.cbc53f0e81f5 ? So was built 17th of Sept?

**Comment by juliayakovlev** [comment]
> > > > Upgrade to `6.3.0~dev-0.20240924.36d68ec955d4 with build-id 3ece0fa61f67ac70e07b4083ed230be4094ad810`
> > > 
> > > 
> > > The fix (above) was merged only on the 25th of Sep.
> > 
> > 
> > @mykaul This issue happened in the run 29.9 And same failure 30.9 - [https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=ee4a7c51-53c0-4e87-a7d0-132321f6e02f](https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns%5B%5D=ee4a7c51-53c0-4e87-a7d0-132321f6e02f)
> 
> But the Scylla version used is 6.2.0~rc0-20240917.cbc53f0e81f5 ? So was built 17th of Sept?

@mykaul is this issue in base version, not target? Because the failure happens after upgrade, not in the `6.2.0~rc0-20240917.cbc53f0e81f5`

**Comment by mykaul** [comment]
> > > > > Upgrade to `6.3.0~dev-0.20240924.36d68ec955d4 with build-id 3ece0fa61f67ac70e07b4083ed230be4094ad810`
> > > > 
> > > > 
> > > > The fix (above) was merged only on the 25th of Sep.
> > > 
> > > 
> > > @mykaul This issue happened in the run 29.9 And same failure 30.9 - [https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns[]=ee4a7c51-53c0-4e87-a7d0-132321f6e02f](https://argus.scylladb.com/test/fd24cecf-b43e-4230-831c-5c80a3ee04b7/runs?additionalRuns%5B%5D=ee4a7c51-53c0-4e87-a7d0-132321f6e02f)
> > 
> > 
> > But the Scylla version used is 6.2.0~rc0-20240917.cbc53f0e81f5 ? So was built 17th of Sept?
> 
> @mykaul is this issue in base version, not target? Because the failure happens after upgrade, not in the `6.2.0~rc0-20240917.cbc53f0e81f5`

I don't understand if the upgrade version has the fix or not.

**Comment by raphaelsc** [comment]
If we're upgrading from a unfixed version to a fixed version, we're still susceptible to the problem since there might be files on disk (left by unfixed version) that prevent node from booting up. In practice, we require user intervention here since the tablet may have been migrated to a remote node. We have https://github.com/scylladb/scylladb/issues/18038 tracking this, since there's room for improvement.

**Comment by raphaelsc** [comment]
```
[raphaelsc@localhost perf-latency-upgrade-ubuntu-db-node-7daec109-2]$ cat messages.log | grep "Unable" | awk '{print $14}' | sort -n | uniq 
matching
/var/lib/scylla/data/keyspace1/standard1-1c6d6a807e9e11ef9da87e4969505689/me-3gjy_1ozn_5jjn42ubdccao0qzto-big-Data.db
/var/lib/scylla/data/keyspace1/standard1-1c6d6a807e9e11ef9da87e4969505689/me-3gjy_1q06_0nkrk2v4pag3r081y4-big-Data.db
/var/lib/scylla/data/keyspace1/standard1-1c6d6a807e9e11ef9da87e4969505689/me-3gjy_1q06_0o0742ubdccao0qzto-big-Data.db
[raphaelsc@localhost perf-latency-upgrade-ubuntu-db-node-7daec109-2]$ cat messages.log | grep "Failed to load SSTable" | awk '{print $14}'| sort -n | uniq
/var/lib/scylla/data/keyspace1/standard1-1c6d6a807e9e11ef9da87e4969505689/me-3gjy_1ozn_5iwhs2ubdccao0qzto-big-TOC.txt:
/var/lib/scylla/data/keyspace1/standard1-1c6d6a807e9e11ef9da87e4969505689/me-3gjy_1q06_0nkrk2ubdccao0qzto-big-TOC.txt:
/var/lib/scylla/data/keyspace1/standard1-1c6d6a807e9e11ef9da87e4969505689/me-3gjy_1q06_0nkrk2v4pag3r081y4-big-TOC.txt:
```

yes, same problem fixed by me.

**Comment by raphaelsc** [comment]
@juliayakovlev let's please retest this with two versions that contain the fix https://github.com/scylladb/scylladb/pull/20737/commits/38ce2c605dc97d0ed13a7fc241e086c768e03d35

**Comment by juliayakovlev** [comment]
I created ami on top of branch with fix https://github.com/scylladb/scylladb/commit/38ce2c605dc97d0ed13a7fc241e086c768e03d35 and ran an upgrade test to latest version:
```
Base scylla version: 6.3.0~dev-20241006.38ce2c605dc9
Build id: e36c4c5977e51c7e35e6b14f6bd193657c31a827
Upgraded scylla version: 6.3.0~dev-20241006.960aa38cf32b
Build id: d9c1c78fef9b7b6f55a36909aa3cf250f3dbe4a7
```

Test passed.

https://argus.scylladb.com/test/7c3163a3-480c-49b1-94ab-f00d74f3fe76/runs?additionalRuns[]=2aa394be-2314-4ef9-9d9c-92abfb0b4e9f
