### ISSUE TITLE
Data in memtable is not considered when deciding whether expired tombstone can be discarded during read

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#20916]
Similar in nature to https://github.com/scylladb/scylladb/issues/1745, but this one happens due to expired tombstone being incorrectly discarded in the read path, not during sstable compaction.

---
Bumped into a data resurrection scenario today where cache is completely empty, memtable and sstable are the only data sources.

Fact:
On read path, table applies compacting reader on sstable reader (only), so an expired tombstone read from a sstable can be purged (not from disk, but from the request) before it has chance to be merged with deleted data in memtable.

Looks like this:
```
                                      ------ (memtable)
                                      |
    read <-(mutation reader merger) <-|
                                      |----- (row cache) <- (compacting reader) <- (sstable)
```

How it could be reproduced:

1. n1 has row @ t1 written to memtable of a table that has very low write activity
2. n1 misses the tombstone @ t2
3. repair runs and writes that tombstone @ t2 directly into a sstable in n1
4. with repair gc mode, that tombstone @ t2 gets expired after 1h (the default propagation delay)
5. since the table has low activity, row @ t1 still sits in memtable
6. on read path, compacting reader purges the tombstone @ t2 read from the sstable, before it's pushed to mutation merger, so the row @ t1 in memtable is returned to the client.

With bypass cache, there's no compacting reader so the expired tombstone is read from disk and merged with memtable. So no live data is returned.

I realized that compacting reader is ignoring the memtable content when calculating max purgeable timestamp (only commitlog content is taken into account on read path today). I am thinking it should look into memtable timestamp like compaction does, as compaction does it to avoid a unlikely but possible data resurrection (steps above show how it can happen). Alternatively the compacting reader wraps both the memtable and sstable data sources.

**Comment by denesb** [comment]
@raphaelsc is this a regression?

**Comment by raphaelsc** [comment]
> [@raphaelsc](https://github.com/raphaelsc) is this a regression?

I think it's introduced here ce96b472d39a6c72f99176c8cf84e171143ae046

**Comment by raphaelsc** [comment]
```
# Reproducer for https://github.com/scylladb/scylladb/issues/20916.
@pytest.mark.asyncio
async def test_memtable_data_is_not_discard_when_reading_through_cache(manager: ManagerClient):
    logger.info("Bootstrapping cluster")
    cmdline = [
        '--logger-log-level', 'table=debug',
        '--logger-log-level', 'mutation_compactor=debug',
    ]
    servers = [await manager.server_add(cmdline=cmdline)]

    cql = manager.get_cql()
    await cql.run_async("CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1};")
    await cql.run_async("CREATE TABLE test.test (pk int PRIMARY KEY, c int) WITH gc_grace_seconds = 0;")

    await manager.api.disable_autocompaction(servers[0].ip_addr, "test")

    key = 7 # Whatever

    # Simulates scenario where node missed tombstone and has it written to sstable directly
    # after repair, whereas the deleted data remains on memtable due to low write activity.

    # write a expiring tombstone into a sstable (flushed below)
    await cql.run_async(f'DELETE FROM test.test USING timestamp 10 WHERE pk = {key}')

    # waits for tombstone to expire
    time.sleep(1)

    # system-wide flush to prevent CL segment from blocking tombstone GC in the read path.
    # /storage_service/flush
    await manager.api.flush_all_keyspaces(servers[0].ip_addr)

    # write into memtable data shadowed by the tombstone now living in the sstable
    await cql.run_async(f'INSERT INTO test.test (pk, c) VALUES ({key}, 0) USING timestamp 9')

    await manager.api.drop_sstable_caches(servers[0].ip_addr)

    # Verify that read through cache won't discard the deleted data in memtable and incorrectly
    # purge the tombstone

    through_cache_rows = cql.execute(f'SELECT pk, c FROM test.test WHERE pk = {key};')
    bypass_cache_rows = cql.execute(f'SELECT pk, c FROM test.test WHERE pk = {key} BYPASS CACHE;')

    assert len(list(bypass_cache_rows)) == 0
    assert len(list(through_cache_rows)) == len(list(bypass_cache_rows))
```

**Comment by fee-mendes** [comment]
Yet another reason for #20270 

Btw @raphaelsc in your pytest, you probably want to specify `WITH tombstone_gc` options on your `CREATE TABLE` statement. Won't this fail when `{mode: 'repair'}`?

**Comment by raphaelsc** [comment]
> Yet another reason for [#20270](https://github.com/scylladb/scylladb/issues/20270)
> 
> Btw [@raphaelsc](https://github.com/raphaelsc) in your pytest, you probably want to specify `WITH tombstone_gc` options on your `CREATE TABLE` statement. Won't this fail when `{mode: 'repair'}`?

It's possible, but would require a well crafted reproducer (with repair to unblock tombstone GC), and this one is simple enough to demonstrate the problem.

**Comment by fee-mendes** [comment]
> It's possible, but would require a well crafted reproducer (with repair to unblock tombstone GC), and this one is simple enough to demonstrate the problem.

I mean, just enforce mode `timeout`. My point is, since it is possible, and we have plans to eventually switch to repair-mode as default, just start enforcing the behavior already so you don't need to iterate on it again.

**Comment by raphaelsc** [comment]
> > It's possible, but would require a well crafted reproducer (with repair to unblock tombstone GC), and this one is simple enough to demonstrate the problem.
> 
> I mean, just enforce mode `timeout`. My point is, since it is possible, and we have plans to eventually switch to repair-mode as default, just start enforcing the behavior already so you don't need to iterate on it again.

I think it doesn't matter much, since you just want to prove that read path won't discard data in memtable after a tombstone gets expired, how it gets expired is orthogonal.
