### ISSUE TITLE
should capture boost::regex_error in auth::certificate_authenticator's ctor

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#20941]
in a3db5401, we introduced the TLS certi authenticator, which is configured using `auth_certificate_role_queries` option . the value of this option contains a regular expression. so there are chances the regular expression is malformatted. in that case, when converting its value presenting the regular expression to an instance of `boost::regex`, Boost.Regex throws a `boost::regex_error` exception, not `std::regex_error`.

**Comment by dawmd** [comment]
Is there a reason to use `boost::regex` instead of `std::regex`?

**Comment by tchaikov** [comment]
@dawmd i am not sure why Calle decided to use Boost.Regex in favor of the one in the standard library, but Ceph had run into a bug related to Boost.Regex, see https://tracker.ceph.com/issues/59196, which turns out to be an issue in libstdc++, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164 . also it's well known that the performance of regex in libstdc++ (and the one in libc++) is lower than Boost.Regex, see https://www.boost.org/doc/libs/1_86_0/libs/regex/doc/html/boost_regex/background/performance.html .

guess that's why. you might want to ask Calle for confirmation.

**Comment by dawmd** [comment]
Thank you, that makes sense
