### ISSUE TITLE
`.clang-format` causes unwanted refactors to happen while developing code in IDE

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#20951]
See this discussion: https://github.com/scylladb/scylladb/pull/20394#discussion_r1786189784

cc @emdroid @avikivity 

@kreuzerkrieg Please fix, it is making review harder and annoying the hell out of me.

**Comment by kbr-scylla** [comment]
@emdroid best to just disable automatic `clang-format`ting in whatever IDE you're using

**Comment by emdroid** [comment]
Another thing that seems to not be necessary is reordering the `#include` headers - not sure why that was introduced into the clang-format (as it normally ignored and requires specific options to actually do the reordering) - that causes quite large changes especially in code that includes a lot of headers.

**Comment by kbr-scylla** [comment]
Another problem: https://github.com/scylladb/scylladb/pull/20394/files/8ba3291043c5c422ffee4e8d5010c8a966716073..6a3ac43b2c51e5bf5612de6f101090e0f946d050#r1786168504

**Comment by kbr-scylla** [comment]
@kreuzerkrieg please ensure that clang formatting doesn't go beyond what is documented in Seastar/Scylla coding guidelines.

If you want to introduce more guidelines, and in fact turn these guidelines into hard rules, that should be discussed with @scylladb/scylla-maint and documented **before** making it automatic

**Comment by emdroid** [comment]
> @emdroid best to just disable automatic clang-formatting in whatever IDE you're using

I had it disabled at the beginning, but as the `.clang-format` has been introduced, I re-enabled it to use that configuration (I'm using VS Code).

And in fact I have it set to format just the modifications on saving to localize the formatting just to the parts I'm changing (not the whole files, as that would cause even more formatting changes on each file touched). But for example when I need to add a new `#include` header, the clang-format then reorders the whole include block around the modification.

**Comment by emdroid** [comment]
Just for the completeness of the ticket, the `.clang-format` file has been introduced in here: #20123
