### ISSUE TITLE
Support sequential repair

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#210]
This issue is a subset of #79

Sequential repair, default,  are the most useful, as they do not require down time.

By default, the repair command takes a snapshot of each replica immediately and then sequentially repairs each replica from the snapshots. For example, if you have RF=3 and A, B and C represents three replicas, this command takes a snapshot of each replica immediately and then sequentially repairs each replica from the snapshots (A<->B, A<->C, B<->C) instead of repairing A, B, and C all at once. This allows the dynamic snitch to maintain performance for your application via the other replicas, because at least one replica in the snapshot is not undergoing repair.

http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsRepair.html

**Comment by tzach** [comment]
@slivne I think we can close this

**Comment by raphaelsc** [comment]
ping

**Comment by nyh** [comment]
According to Cassandra documentation, "Sequential Repair" was the default mode until Cassandra 2.1, and in 2.2 they switched to defaulting to "Parallel Repair".

I think that if we managed without this repair mode for seven years, we don't need to add it now, and can close this issue.   @asias what do you think?

I'll open a separate issue on the documentation - we shouldn't say we support sequential repair if we don't.

**Comment by nyh** [comment]
I'm closing this issue for reasons explained above. @asias or @tzach if you want to keep it open, please reopen it.

**Comment by asias** [comment]
Closing. It is not relevant to scylla.
