### ISSUE TITLE
UPDATE ALL ROWS IN A TABLE

### ISSUE THREAD

**Issue by mighty-phoenix** [scylladb/scylladb#21006]
I want to update all rows in a table, setting specific field values to a given value.
My use case is this:
Alter table adding a new field
Update default value for that field for all rows
I have a composite primary key (id(text),marketplace(text)), so that adds on to the complexity

**Comment by mykaul** [comment]
@mighty-phoenix - I suggest you ask questions in our forum - https://forum.scylladb.com/latest - or our users mailing list - https://groups.google.com/g/scylladb-users

Issues are for bugs / feature requests.

**Comment by nyh** [comment]
This feature has been requested in the past (see for example https://github.com/scylladb/scylladb/issues/8654, and a similar issue for DELETE in https://github.com/scylladb/scylladb/issues/10593), but to leave an issue open as a feature request, more work will need to be done to formulate what exactly the API you are requesting would look like, and how it might work.

In particular, it might not make sense to "overload" the existing "UPDATE" syntax with a long-running operation to modify all rows. It will be difficult to implement (will require parallelization like we did for aggregations in SELECT), the user will not know when to time out, and it will be impossible to recover from temporary failures in the middle of the operation. Perhaps this can be solved by allowing the UPDATE to apply not to all rows but to all rows in a specific token range (via some "WHERE" syntax). These details should be considering before we propose such a feature. Also I have a vague recollection that @avikivity hoped in the past to have a more general _transformation_ operation, that allows you to run a user-defined function, not just an "UPDATE", on the entire table - but I can't find an issue right now.

**Comment by avikivity** [comment]
UPDATE is a transformation, just not generic. If we can expand it in the same direction that SQL already supports, we should.

We should have an EXPLAIN statement that will all the user to estimate the performance.
