### ISSUE TITLE
Unable to produce private builds on latest master

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#21027]
Something broke in configure.py, SCYLLA_BUILD in SCYLLA-VERSION-GEN can no longer be adjusted (in master branch), without ninja getting stuck in CONFIGURE phase. 

Reverting both d1c7e2effab1 and 85219e9294 fixed it for me.

**Comment by piodul** [comment]
Interestingly, the issue only occurs if `SCYLLA_BUILD` is set to a value like `counter.yourname` (according to the recommendation), where `counter` is a number. If you set it to just `counter` - for example it is set to just `0` by default - then there is no reconfigure loop.
