### ISSUE TITLE
test_multidc_alter_tablets_rf: Keyspace 'ks' already exists

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#21034]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12287/testReport/(root)/test_tablets/test_multidc_alter_tablets_rf_dev_10/
```
request = <FixtureRequest for <Coroutine test_multidc_alter_tablets_rf.10.dev.10>>
manager = <test.pylib.manager_client.ManagerClient object at 0x7f2a085b3bc0>

    @pytest.mark.asyncio
    async def test_multidc_alter_tablets_rf(request: pytest.FixtureRequest, manager: ManagerClient) -> None:
        config = {"endpoint_snitch": "GossipingPropertyFileSnitch", "enable_tablets": "true"}
    
        logger.info("Creating a new cluster of 2 nodes in 1st DC and 2 nodes in 2nd DC")
        # we have to have at least 2 nodes in each DC if we want to try setting RF to 2 in each DC
        await manager.servers_add(2, config=config, property_file={'dc': f'dc1', 'rack': 'myrack'})
        await manager.servers_add(2, config=config, property_file={'dc': f'dc2', 'rack': 'myrack'})
    
        cql = manager.get_cql()
>       await cql.run_async("create keyspace ks with replication = {'class': 'NetworkTopologyStrategy', 'dc1': 1}")
E       cassandra.AlreadyExists: Keyspace 'ks' already exists

test/topology_custom/test_tablets.py:210: AlreadyExists
```

The test creates a new cluster so maybe the `already exists` error happens due to a client retry?

**Comment by bhalevy** [comment]
[test_multidc_alter_tablets_rf.10.dev.10.zip](https://github.com/user-attachments/files/17322942/test_multidc_alter_tablets_rf.10.dev.10.zip)

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12287/artifact/testlog/x86_64/dev/failed_test/test_multidc_alter_tablets_rf.10.dev.10/pytest.log
```
18:27:55.518 DEBUG> Message pushed from server: <EventMessage(event_type='SCHEMA_CHANGE', event_args={'target_type': 'KEYSPACE', 'change_type': 'CREATED', 'keyspace': 'ks'}, stream_id=-1, trace_id=None)>
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12287/artifact/testlog/x86_64/dev/failed_test/test_multidc_alter_tablets_rf.10.dev.10/scylla-782.log
```
INFO  2024-10-09 18:27:55,455 [shard 0: gms] schema_tables - Creating keyspace ks
INFO  2024-10-09 18:27:55,459 [shard 0: gms] migration_manager - Gossiping my schema version 0e71e05c-8653-11ef-2cc3-3c2645c862fc
INFO  2024-10-09 18:27:55,459 [shard 0: gms] schema_tables - Schema version changed to 0e71e05c-8653-11ef-2cc3-3c2645c862fc
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12287/artifact/testlog/x86_64/dev/failed_test/test_multidc_alter_tablets_rf.10.dev.10/scylla-783.log
```
INFO  2024-10-09 18:27:55,515 [shard 0: gms] schema_tables - Creating keyspace ks
INFO  2024-10-09 18:27:55,519 [shard 0: gms] migration_manager - Gossiping my schema version 0e71e05c-8653-11ef-2cc3-3c2645c862fc
INFO  2024-10-09 18:27:55,520 [shard 0: gms] schema_tables - Schema version changed to 0e71e05c-8653-11ef-2cc3-3c2645c862fc
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12287/artifact/testlog/x86_64/dev/failed_test/test_multidc_alter_tablets_rf.10.dev.10/scylla-787.log
```
INFO  2024-10-09 18:27:55,516 [shard 0: gms] schema_tables - Creating keyspace ks
INFO  2024-10-09 18:27:55,520 [shard 0: gms] migration_manager - Gossiping my schema version 0e71e05c-8653-11ef-2cc3-3c2645c862fc
INFO  2024-10-09 18:27:55,520 [shard 0: gms] schema_tables - Schema version changed to 0e71e05c-8653-11ef-2cc3-3c2645c862fc
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12287/artifact/testlog/x86_64/dev/failed_test/test_multidc_alter_tablets_rf.10.dev.10/scylla-788.log
```
INFO  2024-10-09 18:27:55,452 [shard 0:stmt] migration_manager - Create new Keyspace: KSMetaData{name=ks, strategyClass=org.apache.cassandra.locator.NetworkTopologyStrategy, strategyOptions={"dc1": "1"}, cfMetaData={}, durable_writes=true, tablets={"initial":0}, userTypes=org.apache.cassandra.config.UTMetaData@0x600004adfb20}
...
INFO  2024-10-09 18:27:55,516 [shard 0: gms] schema_tables - Creating keyspace ks
INFO  2024-10-09 18:27:55,522 [shard 0: gms] migration_manager - Gossiping my schema version 0e71e05c-8653-11ef-2cc3-3c2645c862fc
INFO  2024-10-09 18:27:55,522 [shard 0: gms] schema_tables - Schema version changed to 0e71e05c-8653-11ef-2cc3-3c2645c862fc
WARN  2024-10-09 18:27:55,523 [shard 0:stmt] create_keyspace - Using Replication Factor dc1=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
```

**Comment by bhalevy** [comment]
I wonder if this issue shares the root cause with https://github.com/scylladb/scylladb/issues/20060

**Comment by kostja** [comment]
If I understand anything, the comment in the test is not matching what the test is doing:
```
@pytest.mark.asyncio
async def test_multidc_alter_tablets_rf(request: pytest.FixtureRequest, manager: ManagerClient) -> None:
    config = {"endpoint_snitch": "GossipingPropertyFileSnitch", "enable_tablets": "true"}

    logger.info("Creating a new cluster of 2 nodes in 1st DC and 2 nodes in 2nd DC")
    # we have to have at least 2 nodes in each DC if we want to try setting RF to 2 in each DC
    await manager.servers_add(2, config=config, property_file={'dc': f'dc1', 'rack': 'myrack'})
    await manager.servers_add(2, config=config, property_file={'dc': f'dc2', 'rack': 'myrack'})
```

It's adding servers to an existing cluster, not creating a new cluster. Thus this keyspace may exist from the previous test.
It's recommended to use unique_name() for exactly this purpose, as well as drop the keyspace at the end of the test.

**Comment by kostja** [comment]
@ptrsmrn could you verify my suspicion and perhaps send a fix?

**Comment by ptrsmrn** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/124208650?s=64&amp;v=4">@ptrsmrn](https://github.com/ptrsmrn) could you verify my suspicion and perhaps send a fix?

I took a quick look: every testcase in this file does the same thing: adding servers, then creating a keyspace. But the KS name is different from my, other testcases use:
```
CREATE KEYSPACE test...
```
and not `ks` as a KS name.

**Comment by ptrsmrn** [comment]
Also seen in https://jenkins.scylladb.com/job/scylla-6.0/job/scylla-ci/252/testReport/junit/(root)/test_tablets/test_multidc_alter_tablets_rf_2/
which is a 6.0 backport - https://github.com/scylladb/scylladb/pull/21047 - of the PR introducing this test
We should not backport anything until this flakiness is addressed, I'll change backport PRs to drafts.

**Comment by kbr-scylla** [comment]
> Doesn't it mean that each testcase starts a new cluster with 0 nodes?

That's what it means.

**Comment by bhalevy** [comment]
Seen again in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12355/testReport/(root)/test_tablets/test_multidc_alter_tablets_rf_dev_3/
