### ISSUE TITLE
group0_state_id_handler is being destroyed without being stopped

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#21074]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/708/testReport/update_cluster_layout_tests/TestStopNodeEarly/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split000___test_stop_node_while_restarting_True_False_/
```
failed on teardown with "AssertionError: Critical errors found: [('node1', ['Aborting on shard 0, in scheduling group gossip.'])]
Other errors: [('node1', ['ERROR 2024-10-11 22:09:15,698 [shard 0: gms] group0_tombstone_gc_handler - group0_state_id_handler is being destroyed without being stopped, at: 0x61e74fe 0x61e7b20 0x61e7e28 0x5ca913e 0x5ca92f7 0x465fa76 0x466f46f 0x4a02cbc 0x4a02e7f 0x46e8b5c 0x142d7ea 0x5ce7b4f 0x5ce90ca 0x5cea2a7 0x5ce9658 0x5c78d33 0x5c78093 0x13da0a5 0x13dba60 0x13d84c3 /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/96070bb5b39e0eeed7457e2f5f9befcb19d1e2df/libreloc/libc.so.6+0x2a087 /jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/96070bb5b39e0eeed7457e2f5f9befcb19d1e2df/libreloc/libc.so.6+0x2a14a 0x13d5b44'])]"
```

Scylla version 6.3.0~dev-0.20241011.96070bb5b39e with build id 71f2d6ee5f0cb5c9c28370c8fc72b1a4af608b58

Decoded:
```
[Backtrace #0]
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_0>(seastar::current_backtrace_tasklocal()::$_0&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:68
 (inlined by) seastar::current_backtrace_tasklocal() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:97
seastar::current_tasktrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:148
seastar::current_backtrace() at ./build/release/seastar/./build/release/seastar/./seastar/src/util/backtrace.cc:181
void log_error_and_backtrace<std::basic_string_view<char, std::char_traits<char> > >(seastar::logger&, std::basic_string_view<char, std::char_traits<char> > const&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:50
seastar::on_fatal_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:79
service::group0_state_id_handler::~group0_state_id_handler() at ././service/raft/group0_state_id_handler.cc:121
service::group0_state_machine::~group0_state_machine() at ././service/raft/group0_state_machine.hh:97
std::default_delete<raft::state_machine>::operator()(raft::state_machine*) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:93
 (inlined by) std::unique_ptr<raft::state_machine, std::default_delete<raft::state_machine> >::~unique_ptr() at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:398
 (inlined by) raft::server_impl::~server_impl() at ././raft/server.cc:67
raft::server_impl::~server_impl() at ././raft/server.cc:67
 (inlined by) non-virtual thunk to raft::server_impl::~server_impl() at ././raft/server.cc:?
std::default_delete<raft::server>::operator()(raft::server*) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:93
 (inlined by) std::unique_ptr<raft::server, std::default_delete<raft::server> >::~unique_ptr() at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/unique_ptr.h:398
 (inlined by) service::raft_server_for_group::~raft_server_for_group() at ././service/raft/raft_group_registry.hh:48
 (inlined by) service::raft_group_registry::start_server_for_group(service::raft_server_for_group) at ././service/raft/raft_group_registry.cc:373
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
 (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:122
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2621
seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3087
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3255
seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3145
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ././main.cc:703
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
main at ././main.cc:2292
```

**Comment by bhalevy** [comment]
@emdroid can you please look into this?
Cc @kbr-scylla

**Comment by emdroid** [comment]
Will have a look, seems like the handler is not being stopped properly and is triggering the assertion check.

**Comment by bhalevy** [comment]
Seen also in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/324/testReport/update_cluster_layout_tests/TestStopNodeEarly/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split002___test_stop_node_while_restarting_True_False_/

**Comment by bhalevy** [comment]
> Will have a look, seems like the handler is not being stopped properly and is triggering the assertion check.

@emdroid why do we need `stop` before group0_state_id_handler is destroyed?
stop only cancels the timer, but this happens implicitly when the timer is destroyed.

**Comment by emdroid** [comment]
That's true, maybe the `stop()` isn't even needed there ... I saw a similar pattern being used in other similar handlers (like e.g. the cache hitrate calculator) including the assertion, so I used it as well here (but it's true that such other handlers are started and stopped from `main()`).

But in any case it looks there is some issue in how the stopping is being handled (the name of the test `stop_node_while_restarting` suggests that there might be some unexpected interactions when stopping, possibly also a race).

**Comment by emdroid** [comment]
Removing the `_is_stopped` check seems to work, however I'm wondering if that couldn't cause some other issue e.g. when destroing the handler while the timer is currently being triggered and the group0 check is being run.

Seems that in this particular test the `stop()` is not being called for some reason, might be the whole server is not even started yet ... but first want to understand the flow and the exact reason why this is the case (stopping while restarting is a strong hint indeed).

**Comment by bhalevy** [comment]
> Removing the `_is_stopped` check seems to work, however I'm wondering if that couldn't cause some other issue e.g. when destroing the handler while the timer is currently being triggered and the group0 check is being run.
> 
> Seems that in this particular test the `stop()` is not being called for some reason, might be the whole server is not even started yet ... but first want to understand the flow and the exact reason why this is the case (stopping while restarting is a strong hint indeed).

I think that the `group0_state_id_handler` is destroyed as a member of `group0_state_machine`
but it doesn't matter.  The timer callback is synchronous so it wouldn't run the background if the timer is canceled when destroyed.
So I think the whole check is redundant and can be safely dropped.
