### ISSUE TITLE
enable_tablets and force_gossip_topology_changes: it should not be possible to enable them together.

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#21075]
Affected branches: 6.0, 6.1, 6.2, current master

How to repeat:
Specify enable_tablets:true and force_gossip_topology_changes:true in the configuration file.

Create a keyspace with default options.
Then get a weird error in CREATE TABLE:

>       await cql.run_async(f"CREATE TABLE ks.t (p int, c int, PRIMARY KEY (p, c))")
E       cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.36.16.5:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Shard count not known for node e1bf395f-9dfa-4a33-9e63-54a02d57189e">, <Host: 127.36.16.4:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Shard count not known for node 224cd710-4bd8-412a-8d45-8aa037bac43f">, <Host: 127.36.16.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Shard count not known for node ef392ce9-f049-49bf-83ab-78064e76ea2d">})

**Comment by kostja** [comment]
An easy way to repeat is to enable tablets in test/pylib/scylla_cluster.py and run test/topology_custom/test_view_build_status.py

**Comment by bhalevy** [comment]
Added a unit test and fixed this issue in https://github.com/scylladb/scylladb/pull/20729
