### ISSUE TITLE
A table tablet is not split on writing more than target_tablet_size_in_bytes

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#21092]
## Packages

Scylla version: `6.3.0~dev-1.tabletmerge.20241013.259dcf894703` with build-id `#NO_BUILDID`

Kernel Version: `6.8.0-1016-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

The test configuration sets target_tablet_size_in_bytes to 1GB : 
```
append_scylla_yaml:
  target_tablet_size_in_bytes: 1073741824  # 1GB
  enable_tablets: true
```
It then creates a keyspace with 1 tablet like:
```
< t:2024-10-13 13:24:27,997 f:common.py       l:1324 c:utils                p:DEBUG > Executing CQL 'CREATE KEYSPACE IF NOT EXISTS scylla_bench WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3} and tablets={'initial':1};' ...
```
Then write a dataset of ~ 10GB like:
```
stress_cmd:        "scylla-bench -workload=sequential -mode=write -replication-factor=3 -partition-count=1000 -clustering-row-count=5555 -partition-offset=51 -clustering-row-size=1884 -concurrency=20 -connection-count=20 -consistency-level=quorum -rows-per-request=10 -timeout=30s -validate-data"
```
```
< t:2024-10-13 13:24:29,363 f:tablets_split_merge_test.py l:53   c:TabletsSplitMergeTest p:DEBUG > Calculated dataset size: 9.746868163347244 GB
< t:2024-10-13 13:24:29,363 f:tablets_split_merge_test.py l:54   c:TabletsSplitMergeTest p:DEBUG > Maximum expected tablets number: 9
```
it queries the number of tablets like:
```
< t:2024-10-13 14:21:57,869 f:common.py       l:1324 c:utils                p:DEBUG > Executing CQL 'select tablet_count,resize_type from system.tablets where keyspace_name='scylla_bench' ALLOW FILTERING'
```
and always gets a result of "1":
```
< t:2024-10-13 14:21:57,872 f:common.py       l:63   c:sdcm.utils.tablets.common p:DEBUG > Retrieved a tablets count of: 1 for keyspace scylla_bench
```
The test then fails 3 times (once per cycle) for:
```
2024-10-13 13:43:18.145: (InfoEvent Severity.ERROR) period_type=not-set event_id=cfda0ee2-c4a8-4dcd-a245-971c8376d1b6: message=Waiting for a tablets number bigger than 4 FAILED.
```
More scenario details are also in https://github.com/scylladb/scylladb/issues/21084
## Impact
only a single tablet for a table with a big dataset. could probably hurt performance.
*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- tablets-split-merge-master-db-node-ecba0625-3 (18.207.111.166 | 10.12.2.65) (shards: 2)
- tablets-split-merge-master-db-node-ecba0625-2 (44.203.32.197 | 10.12.2.173) (shards: 2)
- tablets-split-merge-master-db-node-ecba0625-1 (44.202.212.93 | 10.12.0.234) (shards: 2)

OS / Image: `ami-07af88cdc0b3d8af9` (aws: undefined_region)

Test: `byo-longevity-test-yg`
Test id: `ecba0625-b97d-4d41-b708-7538ce55fcca`
Test name: `scylla-staging/yarongilor/byo-longevity-test-yg`
Test method: `tablets_split_merge_test.TabletsSplitMergeTest.test_tablets_split_merge`
Test config file(s):

- [tablets-split-merge-test.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/063f0c7fda630113e7bce7256906c9c3deefd625/test-cases/features/tablets/tablets-split-merge-test.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor ecba0625-b97d-4d41-b708-7538ce55fcca`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ecba0625-b97d-4d41-b708-7538ce55fcca)
- Show all stored logs command: `$ hydra investigate show-logs ecba0625-b97d-4d41-b708-7538ce55fcca`

## Logs:
- **db-cluster-ecba0625.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/db-cluster-ecba0625.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/db-cluster-ecba0625.tar.gz)
- **sct-runner-events-ecba0625.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/sct-runner-events-ecba0625.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/sct-runner-events-ecba0625.tar.gz)
- **sct-ecba0625.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/sct-ecba0625.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/sct-ecba0625.log.tar.gz)
- **loader-set-ecba0625.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/loader-set-ecba0625.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/loader-set-ecba0625.tar.gz)
- **monitor-set-ecba0625.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/monitor-set-ecba0625.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ecba0625-b97d-4d41-b708-7538ce55fcca/20241013_143539/monitor-set-ecba0625.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/byo-longevity-test-yg/36/)
[Argus](https://argus.scylladb.com/test/e6972842-591d-472f-9e39-f196d3670053/runs?additionalRuns[]=ecba0625-b97d-4d41-b708-7538ce55fcca)
</details>

**Comment by mykaul** [comment]
It is not split, or the split is delayed? We are aware of a bug of the latter case.

**Comment by yarongilor** [comment]
> It is not split, or the split is delayed? We are aware of a bug of the latter case.

not split at all. along the whole test there's only 1 tablet reported. (so the merge cannot be tested at all as well).

**Comment by raphaelsc** [comment]
> > It is not split, or the split is delayed? We are aware of a bug of the latter case.
> 
> not split at all. along the whole test there's only 1 tablet reported. (so the merge cannot be tested at all as well).

Can be a misunderstanding. A table is split when its size is higher than target*2, not target. Also make sure to flush since memtable size is not taken into account

**Comment by yarongilor** [comment]
> [@yarongilor](https://github.com/yarongilor)
> 
> 10G=10737418240
> 
> logs tell me max tablet size seen was 10358193392.
> 
> add some extra 1G to calculation to make sure split / merge happens. working with the boundary may lead to flakiness.
> 
> data_set_size_for_split=(current_tablet_count * (target_cfg*2+1G)) data_set_size_for_merge=(current_tablet_count * (target_cfg/2-1G))
> 
> please close this issue.

according to the above, it sums up to:

data_set_size_for_split=(current_tablet_count * (target_cfg*2+1G))
= 1 * (1073741824 * 2 + 1G)
= 3221225472
this is ~ 3GB
and the dataset size is 10GB
10737418240 // 3221225472 = 3
10358193392 // 3221225472 = 3

So tablet size is 3 times larger than target_tablet_size_in_bytes and not split.

**Comment by raphaelsc** [comment]
Probably you didn't set up target size properly. I cannot see target_tablet_size_in_bytes in yaml file nor in SCYLLA_ARGS of nodes. The decision to split is very simple functionality that is tested, and logs show that average size is being properly pulled from nodes, so I am confident this is a testing issue.
