### ISSUE TITLE
Control Throttling of Backup

### ISSUE THREAD

**Issue by regevran** [scylladb/scylladb#21095]
We need a way to throttle backup process when done within Scylla.
In most cases probably there is no need to rush the backup, it can be given a very low priority.
Backups are normally taken once-in-a-{day/week/month} so we have the entire cycle to backup.

There is no such functionality today when we are uploading using `rclone`.

@tzach - do we want the user to set the rate (like in restore) or do we want to control it internally?

Future implementation: Throttle the upload based on other activities.
The backup may be balanced with user-queries, compaction, tablet migration or any other background demanding activity.

Also Refs: #20868

**Comment by tzach** [comment]
A primary motivation for moving the backup to the core is using the IO scheduler. The goal is to complete the backup in a few hours - and keep p99 latency under the 10ms threshold.
Static Throttle threshold should be used as a last resort.
If a must we can use the same value we use now (do use one?)

**Comment by xemul** [comment]
We may want to fix https://github.com/scylladb/seastar/issues/1070 first making scheduling groups nested, and then have two sub-groups in "streaming" one -- streaming.repair and streaming.backup (and even streaming.restore)

**Comment by regevran** [comment]
[seastar #1070](https://github.com/scylladb/seastar/issues/1070) may have a huge impact and can take time to stabilize. I don't want to wait for it to be able to throttle backup - I prefer using existing methods.
Currently we'll use the "streaming" scheduling group and if we see problems originated from conjunctions with repair we'll resort to either backup has its own scheduling group or the nested solution (1070).
I am closing the issue as there is nothing to be done.
