### ISSUE TITLE
storage_io_error (S3 access denied (403 Forbidden)) when trying to backup to local minio endpoint

### ISSUE THREAD

**Issue by cezarmoise** [scylladb/scylladb#21126]
With a minio endpoind where backup/restore via manager works.
`object_storage.yaml`
```yaml
endpoints:
- aws_access_key_id: test1
  aws_secret_access_key: '12345678'
  name: localhost
  port: 32835
```
scylla-manager-agent.yaml
```yaml
https: 127.0.23.1:10001
auth_token: 80352e06-8dd2-45d1-a9f3-cc8df796810e
tls_cert_file: 
  /home/cezar/.pyenv/versions/3.12.5/envs/dtest-3.12.5/lib/python3.12/site-packages/ccmlib/scylla_test_ssl/scylla-manager-agent.crt
tls_key_file: 
  /home/cezar/.pyenv/versions/3.12.5/envs/dtest-3.12.5/lib/python3.12/site-packages/ccmlib/scylla_test_ssl/scylla-manager-agent.key
logger:
  level: debug
debug: 127.0.23.1:56112
scylla:
  api_address: 127.0.23.1
  api_port: 10000
prometheus: 127.0.23.1:56090
s3:
  endpoint: http://localhost:32835
  access_key_id: test1
  secret_access_key: '12345678'
  provider: Minio
```
nodetool does not throw an error, output is
```
done
start: 2024-10-15T17:14:31Z
end: 2024-10-15T17:14:31Z
```
but node log has errors:
```
ERROR 2024-10-15 20:14:31,699 [shard 0:strm] snapshots - Error uploading /home/cezar/.dtest/dtest-q5llvt95/test/node1/data/ks/cf1-f0c4f3d08b1811efbeb8699f6078137a/snapshots/snapshot/me-3gke_1bw7_33o282888ugtiv0ns8-big-Scylla.db: storage_io_error (S3 access denied (403 Forbidden))
WARN  2024-10-15 20:14:31,699 [shard 0:strm] seastar - Exceptional future ignored: storage_io_error (S3 access denied (403 Forbidden)), backtrace: 0x61efcae 0x61f02d0 0x61f05d8 0x5c93275 0x3ab6019 0x5ceed0f 0x5cf02aa 0x5cf1487 0x5cf0838 0x5c7ffc3 0x5c7f323 0x13df4e5 0x13e0ea0 0x13dd903 /home/cezar/.ccm/scylla-repository/unstable/master/latest/libreloc/libc.so.6+0x2a087 /home/cezar/.ccm/scylla-repository/unstable/master/latest/libreloc/libc.so.6+0x2a14a 0x13daf84
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<db::snapshot::backup_task_impl::do_backup()::$_2, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<db::snapshot::backup_task_impl::do_backup()::$_2, false> >(seastar::future<void>::finally_body<db::snapshot::backup_task_impl::do_backup()::$_2, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<db::snapshot::backup_task_impl::do_backup()::$_2, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>

```

Reproducer: https://github.com/cezarmoise/scylla-dtest/blob/new-backup-restore-tests/scylla_backup_restore_tests.py

**Comment by cezarmoise** [comment]
@tchaikov 
May be related to this note in the docs:
>    - All AWS-related parameters must be either present or absent as a group.
>   - When set, these values are used by the S3 client to sign requests.
 >  - If not set, requests are sent unsigned, which may not be accepted by all servers.

But for this use case there is no region or token.

**Comment by cezarmoise** [comment]
> [@tchaikov](https://github.com/tchaikov) May be related to this note in the docs:
> 
> > * All AWS-related parameters must be either present or absent as a group.
> 
> But for this use case there is no region or token.

After looking at the unit tests, I found that minio does have a region, default to `local`, and if I use that then backup succeeds.

**Comment by cezarmoise** [comment]
I now get a different error on restore:
```
nodetool -h 127.0.13.1 -p 10000 restore --endpoint localhost --bucket backup-bucket --keyspace ks --table cf1 --prefix backup

stderr: error running operation: boost::wrapexcept<boost::bad_any_cast> (boost::bad_any_cast: failed conversion using boost::any_cast)
```

**Comment by tchaikov** [comment]
@cezarmoise i created #21135 and #21136 to address this usability issue

**Comment by tchaikov** [comment]
@cezarmoise hi Cezar, after a second thought, shall we also update `docs/dev/object_storage.md` to note your finding:

> After looking at the unit tests, I found that minio does have a region, default to `local`, and if I use that then backup succeeds.

so that the posterity won't have the same problem?

**Comment by tchaikov** [comment]
> Yes, the confusion came from the fact the scylla-manager was not configures with region, but still worked.

i think scylla-manager is encoded with lots of regions already. guess it is using it . after building scylla-manager, i can find 
```
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
```
which actually encodes quite a few regions supported by aws. guess the same applies to minio backend.
