### ISSUE TITLE
Error sending messages automatically on the Scylla University website

### ISSUE THREAD

**Issue by NikiYani** [scylladb/scylladb#21140]
The problem has already been sent to university@scylladb.com

Good afternoon. I logged in through my Github account and should have received a confirmation email, but it didn’t arrive. Can you resend? Or fix sending emails?

Thank you in advance)

**Comment by mykaul** [comment]
CC @tzach , @guy9 

I think the forum is a better venue for such questions/issues.

**Comment by tzach** [comment]
Yes, the issue is not related to this repo.
Closing.
