### ISSUE TITLE
test.py/topology_custom/test_multidc.py/test_multidc fails in tablets mode.

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#21166]
Enable tablets in test/pylib/scylla_cluster.py.

Then run test_multidc. It will fail.

The test is creating a 5-node cluster in 5 data centers and then creates a table with replication factor 3. This fails with:
```
test/topology_custom/test_multidc.py:38:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/pylib/random_tables.py:292: in add_tables
    await asyncio.gather(*(t.create(if_not_exists) for t in tables))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test.pylib.random_tables.RandomTable object at 0x7f947dd785f0>
if_not_exists = False

    async def create(self, if_not_exists: bool = False) -> asyncio.Future:
        """Create this table"""
        col_defs = ", ".join(f"{c.cql}" for c in self.columns)
        pk_names = ", ".join(c.name for c in self.columns[:self.pks])
        cql_stmt = f"CREATE TABLE {'IF NOT EXISTS ' if if_not_exists else ''} {self.full_name} "\
                   f"({col_defs}, , primary key({pk_names}))"
        logger.debug(cql_stmt)
        assert self.manager.cql is not None
>       return await self.manager.cql.run_async(cql_stmt)
E       cassandra.protocol.ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="Datacenter dc3 doesn't have enough token-owning nodes for replication_factor=3">
```

The test fails in:
```
=================================== FAILURES ===================================
________________________________ test_multidc.1 ________________________________

request = <FixtureRequest for <Coroutine test_multidc.1.dev.1>>
manager = <test.pylib.manager_client.ManagerClient object at 0x7f947dd06e70>

    @pytest.mark.asyncio
    async def test_multidc(request: pytest.FixtureRequest, manager: ManagerClient) -> None:
        logger.info("Creating a new cluster")
        for i in range(5):
            s_info = await manager.server_add(
                config=CONFIG,
                property_file={'dc': f'dc{i}', 'rack': 'myrack1'}
            )
            logger.info(s_info)
        random_tables = RandomTables(request.node.name, manager, unique_name(), 3)
        logger.info("Creating new tables")
>       await random_tables.add_tables(ntables=3, ncolumns=3)
```

**Comment by kostja** [comment]
@tgrabiec  either I don't understand something,or there is a genuine bug in the tablets mode. The replication factor is 3 and there is a node in dc3, but the token assignment algorithm doesn't find it.

**Comment by tgrabiec** [comment]
If RF is 3, then you need at least 3 nodes in each dc, but you're saying you have 1 node per dc.

**Comment by kostja** [comment]
I don't get this. Why? RF=3 doesn't mean - in each DC - no?

**Comment by ptrsmrn** [comment]
> I don't get this. Why? RF=3 doesn't mean - 3 in each DC - no?

RF is always per DC, not the whole cluster. So RF=3 means 3 nodes in a DC.

**Comment by kostja** [comment]
This is quite confusing and not documented anywhere. Imagine I have the following CREATE KEYSPACE:

CREATE KEYSPACE IF NOT EXISTS {keyspace} WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3}

I am going to get 3 copies of my data.

If I change the strategy to NetworkTopologyStrategy, then I am going to get as many copies as I have DCs. But I already can explicitly specify how many copies per DC I want with:

ALTER KEYSPACE keyspace WITH REPLICATION = {'class' : 'NetworkTopologyStrategy', 'DC1' : 3, 'DC2' : 2 };

**Comment by tgrabiec** [comment]
https://enterprise.docs.scylladb.com/stable/cql/ddl.html#networktopologystrategy


> 'replication_factor'
> 
> int
> 
> The number of replicas to use as a default per datacenter if not specifically provided. Note that this always defers to existing definitions or explicit datacenter settings. For example, to have three replicas per datacenter, supply this with a value of 3.
> 
> The replication factor configured for a DC should be equal to or lower than the number of nodes in that DC. Configuring a higher RF may prevent creating tables in that keyspace.
>
