### ISSUE TITLE
doc: remove the Cassandra references from the nodetool documentation

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#21238]
Now that we have the native nodetool, the references to Cassandra should be removed. This includes the introduction (_ScyllaDB’s nodetool is a fork of [the Apache Cassandra nodetool](https://cassandra.apache.org/doc/latest/tools/nodetool/nodetool.html) with the same syntax and a subset of the operations_) and the copyright section.

**Comment by tzach** [comment]
We can remove it from the index page.
For commands, it needs to stay in places where we used the **docs** from the Apache Project.
