### ISSUE TITLE
test.py hides the real status of xfail tests

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#21300]
In pytest when a test is marked `xfail`, instead of the usual PASSED (`.`) or FAILED (`F`) results, it will get either XFAIL (`x`) or XPASS (`X`) results:
1.  XFAIL means an expected failure - the test really did fail like its author had anticipated.
2. XPASS means the test passed even though its author had anticipated that it would fail.

Unfortunately, our test.py wrapper converts **both** these results, either XFAIL or XPASS, to a normal "PASS" that it reports.
This is a bad thing for two reasons:
1. During development, I can't know if the test really still fails or I solved the bug. I need to remove the "xfail" mark manually from the test to know if the test began to pass.
2. We have no indication, in either CI or in manual runs done via test.py, that we "accidentally" fix a known bug. Unexpectedly fixing a known bug isn't a disaster, of course, but we SHOULD know about it - both to know that the issue about this bug should be close, and to consider backporting the fix that we now learned fixed a bug.

CC @xtrey @temichus @kostja

**Comment by xtrey** [comment]
https://github.com/pytest-dev/pytest/issues/7009

**Comment by nyh** [comment]
@xtrey it's not accurate that "test.py has nothing to do with it" - I discovered this problem while running test.py manually (on a test from the test/topology framework, so I can't run it without test.py) - and seeing these words "PASS" or "FAIL" on the screen next to each test name. I noticed that xfail-marked tests always report "PASS" regardless if they pass or fail, which was very frustrating for me as a developer trying to fix a bug.

I agree that perhaps additionally, we have a problem with how this information is saved to junit and then how how the UI in Jenkins ends up showing this information. But we don't need to solve this problem all at once - we can start by test.py itself showing correct information on the screen, and only later Jenkins will be fixed to understand this information.

Thanks for the link to the discussion https://github.com/scylladb/scylladb/pull/20502 - I had the vague feeling this was discussed recently, but couldn't find an open issue and didn't remember it was in the middle of some unrelated pull request :-) So now we have an open issue, and propose solutions here instead of in some random pull requests.

**Comment by xtrey** [comment]
test.py shows the pass or fail based on pytest exit code. That's why it have no any other statuses. Adding this to the test.py seems not very reasonable, since I'm working on the possibility to run all tests with pytest command. So there will be no need for this.
Regarding the Jenkins, it's already there in Allure report. So you can check it by yourself. In the search field put tag:@pytest.mark.xfail, and you will have some tests. Caveat here that it's searching by exact tag, so if a tag has some additional text, it will not be shown there. I suppose we can overwrite how Allure adds the tag, so it will always add only 'xfail' for example, for easier searching.
If you want to have it in the previous reports, then we need to write our own plugin for Jenkins that will be able to distinguish these new statuses. For me, it seems like not a reasonable way to go.

**Comment by nyh** [comment]
> test.py shows the pass or fail based on pytest exit code. That's why it have no any other statuses. Adding this to the test.py seems not very reasonable

Ok,  you convinced me:

I forgot that test.py's output shows entire test **files**, not individual test functions, and the entire file "PASS"ing just means none of the tests in it failed. So there's no place even mention xfail, let alone which test xfailed.

The reason why I didn't notice this was that I was explicitly running a single test function, so the "PASS" for the entire file was actually just one test function. But in the general case I agree there is no place to put xfail.

I think this is design mistake - that test.py deals with - and reports failures - of entire files instead of individual tests. But I agree it has nothing to do with xfail and it is beyond what I want to care about right now. So I'm closing this issue. Sorry for the spam.

>, since I'm working on the possibility to run all tests with pytest command. So there will be no need for this. 

I agree. All I want to do is run a single test locally, so Jenkins and Allure are of no interest to me. When the test is in test/cql-pytest or test/alternator, I can already run pytest directly (or use the convenience script test/cql-pytest/and see the good output. I guess in the future thanks to the work you're doing now I'll be able to run a single test/topology test with test.py so I'll also see good output.
