### ISSUE TITLE
Cap bloom filter, compression metadata overhead

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#2130]
Bloom filters and compression metadata can grow with data size, which is not tied to memory size.  If we see them growing, we should limit memory usage:

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/19049
- [ ] https://github.com/scylladb/scylladb/issues/19050
```

**Comment by c3mb0** [comment]
What is the progress on this issue? I experienced both problems in several occasions.

**Comment by avikivity** [comment]
@c3mb0 can you give details? which file became too large? how large? what's the schema?

**Comment by denesb** [comment]
Splitting this issue, as it covers two loosely related things, which we want to schedule independently.
Split into:
* https://github.com/scylladb/scylladb/issues/19050
* https://github.com/scylladb/scylladb/issues/19049
