### ISSUE TITLE
Don't snapshot view on base table snapshot

### ISSUE THREAD

**Issue by kreuzerkrieg** [scylladb/scylladb#21339]
As discussed in #20760 we want to stop taking snapshots of MVs in both cases - auto-snapshot and user initiated snapshot. It will eliminate shapshoting MVs altogether since we cant ensure consistency of these, so it makes no sence to provide such functionality. MVs are supposed to be restored by repopulating it from the base table once the base is restored as mentioned by @Michal-Leszczynski [here](https://github.com/scylladb/scylladb/issues/20760#issuecomment-2373475620)

EDIT 001:
Just to preserve the ability to take a snapshot of MV it was decided to change the snpashot machinery in such a way that user will be able to take a snapshot of whatever entity consisting of SSTables - a table, a MV or an index. Note: When taking a shapshot of the index one should use the physical index name which can be obtained by running `DESC MY_TABLE` where the `MY_TABLE` is the base table of the index in question

cc: @bhalevy @regevran @nyh 
Any comments/suggestions are appreciated

**Comment by nyh** [comment]
What's the difference between this issue and https://github.com/scylladb/scylladb/issues/20760 to which you referred? Why open a duplicate if you're already aware it's a duplicate?

**Comment by kreuzerkrieg** [comment]
@nyh just to get to the bottom line. If you think it is redundant I can move it to the original one

**Comment by bhalevy** [comment]
One comment: do we want an option to the snapshot api to enable snapshot of view when taking a snapshot of the base table?

**Comment by kreuzerkrieg** [comment]
> One comment: do we want an option to the snapshot api to enable snapshot of view when taking a snapshot of the base table?

As I understand we cant assure the consistency of MV snapshot, then why we should bother with such an option?

**Comment by bhalevy** [comment]
> > One comment: do we want an option to the snapshot api to enable snapshot of view when taking a snapshot of the base table?
> 
> As I understand we cant assure the consistency of MV snapshot, then why we should bother with such an option?

I don't have a definite answer for that, but there could be users like tests that rely on the comprehensive snapshot for data verification 

Note that the api doesn't allow taking direct snapshot of a view (if I remember correctly) and directs the user to take a snapshot of the base table instead.
An alternative to the proposed option would be to drop this restriction and allow taki g a snapshot of a view or index if the app wants it for some reason.

Another use case I can come up with is generating a first class table from the view by ingesting the sstables of the view from the snapshot, say to a different usrer altogether.

**Comment by kreuzerkrieg** [comment]
> > > One comment: do we want an option to the snapshot api to enable snapshot of view when taking a snapshot of the base table?
> > 
> > 
> > As I understand we cant assure the consistency of MV snapshot, then why we should bother with such an option?
> 
> I don't have a definite answer for that, but there could be users like tests that rely on the comprehensive snapshot for data verification
> 
> Note that the api doesn't allow taking direct snapshot of a view (if I remember correctly) and directs the user to take a snapshot of the base table instead. An alternative to the proposed option would be to drop this restriction and allow taki g a snapshot of a view or index if the app wants it for some reason.
> 
> Another use case I can come up with is generating a first class table from the view by ingesting the sstables of the view from the snapshot, say to a different usrer altogether.

@regevran I think it answers your question regarding "dead code"

**Comment by regevran** [comment]
> @regevran I think it answers your question regarding "dead code"

Yes, let's keep the code that saves snapshots but we'll simply not use it at the moment.
If requirement arises, we'll re-enable it.
Note that we might would like to add in the future, something along the lines of these [comments](https://github.com/scylladb/scylladb/issues/20760#issuecomment-2424853330)

**Comment by kreuzerkrieg** [comment]
@regevran / @bhalevy Task description is updated to reflect our discussions

**Comment by nyh** [comment]
> [@nyh](https://github.com/nyh) just to get to the bottom line. If you think it is redundant I can move it to the original one

I don't understand. If you think that the original issue https://github.com/scylladb/scylladb/issues/20760 was missing a bottom line and this one is the better one, you can close the original issue (or ask to close it, if you lack the permissions). I still don't understand what we gain from having the two issues open and seem (at least to me) the same thing.

**Comment by kreuzerkrieg** [comment]
> > [@nyh](https://github.com/nyh) just to get to the bottom line. If you think it is redundant I can move it to the original one
> 
> I don't understand. If you think that the original issue [#20760](https://github.com/scylladb/scylladb/issues/20760) was missing a bottom line and this one is the better one, you can close the original issue (or ask to close it, if you lack the permissions). I still don't understand what we gain from having the two issues open and seem (at least to me) the same thing.

I remember there was something like "convert to discussion" on an issue, coz the #20760 is more a discussion. Can we just convert it and then technically we dont have "two issues open and seem the same thing"
