### ISSUE TITLE
scylla_raid_setup: failed to install "policycoreutils-python-utils" package on Amazon Linux 2

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylladb#21351]
When I implemented 5a470b2bfbe6fdb371bbde2a2f8987d6618dd265, I thought we only have RHEL8 and RHEL9 clones on our support list, but actually Amazon Linux 2 is fork of RHEL7.
Since the patch was only tested on Rocky8/9, I didn't realized that "policycoreutils-python-utils" package is not exist on Amazon Linux 2.
The package name on Amazon Linux 2 is "policycoreutils-python".
To avoid error on scylla_raid_setup, we need to add code something like:
```
-            pkg_install('policycoreutils-python-utils')
+            if is_amzn2():
+                pkg_install('policycoreutils-python')
+            else:
+                pkg_install('policycoreutils-python-utils')
```

**Comment by Annamikhlin** [comment]
@syuu1228 - https://jenkins.scylladb.com/job/scylla-6.1/job/offline-installer/14/ failed on few tests including `Rocky8/9, OEL8 and Amazon Linux2`

with the same error:
```
11:09:14  ======================================================================
11:09:14  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
11:09:14  ----------------------------------------------------------------------
11:09:14  sdcm.sct_events.system.TestResultEvent: ================================= TEST RESULTS =================================
11:09:14  
11:09:14  ----- LAST ERROR EVENT -------------------------------------------------------
11:09:14  2024-10-28 09:08:59.404: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=72494d55-938c-46ca-8d9e-1acbe5e61913, source=ArtifactsTest.SetUp()
11:09:14  exception=[Node artifacts-rocky9-jenkins-db-node-829bf145-0-1 [34.75.200.29 | 10.142.0.92]] NodeSetupFailed: Encountered a bad command exit code!
11:09:14  Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory /  --no-verify-package '
11:09:14  Exit code: 1
11:09:14  Stdout:
11:09:14  naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
11:09:14  log      =internal log           bsize=4096   blocks=48000, version=2
11:09:14  =                       sectsz=4096  sunit=1 blks, lazy-count=1
11:09:14  realtime =none                   extsz=4096   blocks=0, rtextents=0
11:09:14  Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
11:09:14  Package "policycoreutils-python-utils" required.
11:09:14  [1;31mntp setup is disabled by default, since the installation is offline mode.[0m
11:09:14  Your current Scylla release is 6.1.3 the latest minor release is 6.2.0 go to http://www.scylladb.com/ for upgrade instructions
11:09:14  RAID setup failed.
11:09:14  Stderr:
11:09:14  Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /usr/lib/systemd/system/scylla-server.service.
11:09:14  Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
11:09:14  Traceback (most recent call last):
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 3857, in node_setup
11:09:14  cl_inst.node_setup(_node, **setup_kwargs)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 4669, in node_setup
11:09:14  self._scylla_post_install(node, install_scylla, nic_devname)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 4797, in _scylla_post_install
11:09:14  node.scylla_setup(disks, devname)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 121, in inner
11:09:14  res = func(*args, **kwargs)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 2251, in scylla_setup
11:09:14  self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
11:09:14  result = _run()
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 72, in inner
11:09:14  return func(*args, **kwargs)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
11:09:14  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
11:09:14  result = connection.run(**command_kwargs)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
11:09:14  return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
11:09:14  raise UnexpectedExit(result)
11:09:14  sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
11:09:14  Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory /  --no-verify-package '
11:09:14  Exit code: 1
11:09:14  Stdout:
11:09:14  naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
11:09:14  log      =internal log           bsize=4096   blocks=48000, version=2
11:09:14  =                       sectsz=4096  sunit=1 blks, lazy-count=1
11:09:14  realtime =none                   extsz=4096   blocks=0, rtextents=0
11:09:14  Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
11:09:14  Package "policycoreutils-python-utils" required.
11:09:14  [1;31mntp setup is disabled by default, since the installation is offline mode.[0m
11:09:14  Your current Scylla release is 6.1.3 the latest minor release is 6.2.0 go to http://www.scylladb.com/ for upgrade instructions
11:09:14  RAID setup failed.
11:09:14  Stderr:
11:09:14  Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /usr/lib/systemd/system/scylla-server.service.
11:09:14  Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
```

**Comment by syuu1228** [comment]
> [@syuu1228](https://github.com/syuu1228) - https://jenkins.scylladb.com/job/scylla-6.1/job/offline-installer/14/ failed on few tests including `Rocky8/9, OEL8 and Amazon Linux2`
> 
> with the same error:
> 
> ```
> 11:09:14  ======================================================================
> 11:09:14  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
> 11:09:14  ----------------------------------------------------------------------
> 11:09:14  sdcm.sct_events.system.TestResultEvent: ================================= TEST RESULTS =================================
> 11:09:14  
> 11:09:14  ----- LAST ERROR EVENT -------------------------------------------------------
> 11:09:14  2024-10-28 09:08:59.404: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=72494d55-938c-46ca-8d9e-1acbe5e61913, source=ArtifactsTest.SetUp()
> 11:09:14  exception=[Node artifacts-rocky9-jenkins-db-node-829bf145-0-1 [34.75.200.29 | 10.142.0.92]] NodeSetupFailed: Encountered a bad command exit code!
> 11:09:14  Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory /  --no-verify-package '
> 11:09:14  Exit code: 1
> 11:09:14  Stdout:
> 11:09:14  naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
> 11:09:14  log      =internal log           bsize=4096   blocks=48000, version=2
> 11:09:14  =                       sectsz=4096  sunit=1 blks, lazy-count=1
> 11:09:14  realtime =none                   extsz=4096   blocks=0, rtextents=0
> 11:09:14  Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
> 11:09:14  Package "policycoreutils-python-utils" required.
> 11:09:14  �[1;31mntp setup is disabled by default, since the installation is offline mode.�[0m
> 11:09:14  Your current Scylla release is 6.1.3 the latest minor release is 6.2.0 go to http://www.scylladb.com/ for upgrade instructions
> 11:09:14  RAID setup failed.
> 11:09:14  Stderr:
> 11:09:14  Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /usr/lib/systemd/system/scylla-server.service.
> 11:09:14  Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
> 11:09:14  Traceback (most recent call last):
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 3857, in node_setup
> 11:09:14  cl_inst.node_setup(_node, **setup_kwargs)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 4669, in node_setup
> 11:09:14  self._scylla_post_install(node, install_scylla, nic_devname)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 4797, in _scylla_post_install
> 11:09:14  node.scylla_setup(disks, devname)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 121, in inner
> 11:09:14  res = func(*args, **kwargs)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/cluster.py", line 2251, in scylla_setup
> 11:09:14  self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
> 11:09:14  result = _run()
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 72, in inner
> 11:09:14  return func(*args, **kwargs)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
> 11:09:14  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
> 11:09:14  result = connection.run(**command_kwargs)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
> 11:09:14  return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
> 11:09:14  File "/tmp/workspace/scylla-6.1/artifacts-offline-install/artifacts-rocky9-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
> 11:09:14  raise UnexpectedExit(result)
> 11:09:14  sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
> 11:09:14  Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory /  --no-verify-package '
> 11:09:14  Exit code: 1
> 11:09:14  Stdout:
> 11:09:14  naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
> 11:09:14  log      =internal log           bsize=4096   blocks=48000, version=2
> 11:09:14  =                       sectsz=4096  sunit=1 blks, lazy-count=1
> 11:09:14  realtime =none                   extsz=4096   blocks=0, rtextents=0
> 11:09:14  Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
> 11:09:14  Package "policycoreutils-python-utils" required.
> 11:09:14  �[1;31mntp setup is disabled by default, since the installation is offline mode.�[0m
> 11:09:14  Your current Scylla release is 6.1.3 the latest minor release is 6.2.0 go to http://www.scylladb.com/ for upgrade instructions
> 11:09:14  RAID setup failed.
> 11:09:14  Stderr:
> 11:09:14  Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /usr/lib/systemd/system/scylla-server.service.
> 11:09:14  Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
> ```

Opened issue for this: https://github.com/scylladb/scylladb/issues/21441
I will send a patch for both problem.
