### ISSUE TITLE
Support Cassandra 4.1's "CREATE ROLE WITH HASHED PASSWORD"

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#21350]
Cassandra 4.1 [announced in this blog post](https://cassandra.apache.org/_/blog/Apache-Cassandra-4.1-Features-Client-side-Password-Hashing.html) a feature requested in issue [CASSANDRA-17334](https://issues.apache.org/jira/browse/CASSANDRA-17334)  - "CREATE ROLE WITH HASHED PASSWORD". This issue is about implementing this feature in Scylla.

Before this feature one would create a role given a password:

```
CREATE ROLE role1
    WITH LOGIN = true
    AND PASSWORD = 'mySecret';
```

And Cassandra/ScyllaDB picks a salt, and saves a salted-hash version of this password, not the password itself.
The new feature allows setting the salted-hash password directly:

```
CREATE ROLE role1
    WITH LOGIN = true
    AND HASHED PASSWORD ‘$2a$10$F5pRau9mKg5abP.DsuPQl.8rQpEoNm3OV91mKjb9vdKPUPejIPq/u’;
```

Cassandra's motivation for this feature (eloquently explained in the above-linked blog post) is a security motivation: If the Scylla server logs requests, the log will contain the plain-text password in the regular CREATE ROLE.  Instead, with the new API, the client can salt and hash the password himself, and send the already-hashed password, and Scylla will never log the real password.

_UPDATE: the security severity of this is fairly weak. Importantly, this change does **not** prevent a hacked server from learning the user's cleartext password: Although the CREATE ROLE statement no longer includes the cleartext password, the user does send the cleartext password on every authentication, so a hacked server will learn it._

In ScyllaDB, we have a second motivation: Currently, the "secret key" for a role in Alternator is its hashed password. The recommended way to create such a key is to use `CREATE ROLE role1` followed by `SELECT salted_hash FROM system.roles WHERE role = 'role1'`. But if we ever want to forbid reading `system.roles` (because it's a security problem - see also https://github.com/scylladb/scylladb/issues/5206), a different way for the user to know what the salted hash is it to have the user set it himself, with the new `CREATE ROLE ... WITH HASHED PASSWORD` API.

**Comment by avikivity** [comment]
We have it, but it's spelled CREATE ROLE WITH SALTED HASH. If it's not in any release we can rename it (and if it is, add an alias).

/cc @dawmd

**Comment by dawmd** [comment]
I'm already working on it, thank you for the CC. Do you think we should also rename `DESC SCHEMA WITH INTERNALS AND PASSWORDS` to `DESC SCHEMA WITH INTERNALS AND HASHED PASSWORDS`? The statement becomes quite long, but it would match the create statement and convey the idea better. I don't have any opinion on it, but I thought it might be good to bring it up now that the changes haven't made it to any release yet than to introduce aliases later if we eventually decide it's a better path to tread.

**Comment by dawmd** [comment]
Another thing: we should also decide if we want to support `ALTER ROLE WITH HASHED PASSWORD`, which Cassandra does (as a separate task of course)

**Comment by nyh** [comment]
> Another thing: we should also decide if we want to support `ALTER ROLE WITH HASHED PASSWORD`, which Cassandra does (as a separate task of course)

It seems like a bug that we supported CREATE ROLE WITH _something_, but didn't support ALTER ROLE WITH _something_ for the same something...

**Comment by dawmd** [comment]
> > Another thing: we should also decide if we want to support `ALTER ROLE WITH HASHED PASSWORD`, which Cassandra does (as a separate task of course)
> 
> It seems like a bug that we supported CREATE ROLE WITH _something_, but didn't support ALTER ROLE WITH _something_ for the same something...

It was intentional. We designed the statement to only be used when restoring the schema. The user wasn't supposed to be concerned about it, but we can try to follow the same path as Cassandra
