### ISSUE TITLE
tasks-manager: create tasks for tablet migration

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#21365]
Tablet migration is an internal process, users shouldn't be able to cancel them.
They can cancel higher level operations (like bootstrap or decomission) to stop migrations, but that is outside the scope of this task.

**Comment by bhalevy** [comment]
> > Do we want to keep the history of migration tasks? There may be a lot of them. Maybe we should treat them analogically to regular compaction which is reflected by tasks as long as it is running and unregistered from task manager when it's finished?
> 
> I think that is a good idea. [@bhalevy](https://github.com/bhalevy) WDYT?

We have log messages for them.
It's important to have longer-term tracking of higher-level topology changes like bootstrap, decommission, remove/replace node.
But for load balancing, as @Deexie observed, tablet migrations are akin to regular compaction, and it's ok for them to be ephemeral.
If need be, there are log messages about them that are kept around.

**Comment by bhalevy** [comment]
> Can't users initiate them via the API?

Yes, users can initiate tablet migration from the api,
but it's orthogonal to having task_manager tasks tracking them, and having those tasks tracked in tasks history table.
