### ISSUE TITLE
Incremental backups

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#214]
Subset of #101 
"When incremental backups are enabled (disabled by default), Cassandra hard-links each flushed SSTable to a backups directory under the keyspace data directory. This allows storing backups offsite without transferring entire snapshots. Also, incremental backups combine with snapshots to provide a dependable, up-to-date backup mechanism.  As with snapshots, Cassandra does not automatically clear incremental backup files. DataStax recommends setting up a process to clear incremental backup hard-links each time a new snapshot is created."

http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_backup_incremental_t.html

**Comment by tzach** [comment]
The feature comes with a match configuration option `incremental_backups`

https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__incremental_backups

**Comment by tzach** [comment]
demoting this feature from high to nice to have for GA:
- its false by default
- can be bypass by external tools, generating snapshot each time and pull only new files

**Comment by slivne** [comment]
@vladzcloudius I think you impled this can you update the issue with the ref and then we will be able to close the issue

**Comment by vladzcloudius** [comment]
@slivne You are right - incremental backups have been enabled in a commit b5833e8002f4d47b1638984b119374b488397b31 .
We still have issue with enabling this with the nodetool cmmand see issue #845

**Comment by slivne** [comment]
@vladzcloudius just to make sure:
1. Can we enable this via config 
2. We have a unitest to test this.

**Comment by vladzcloudius** [comment]
@slivne 
1. Yes.
2. Yes: backup_restore_tests.py:incremental_backup (scylla-dtest issue #108)

**Comment by tzach** [comment]
@mykaul not sure why this issue was closed many years ago, but AFAIU it is:
- not done yet
- planned as part of the tablet effort

**Comment by Michal-Leszczynski** [comment]
@tzach so why do we have it in [docs](https://opensource.docs.scylladb.com/branch-5.1/operating-scylla/procedures/backup-restore/backup.html#incremental-backup) and in `scylla.yaml`?
```yaml
# Set to true to have Scylla create a hard link to each sstable
# flushed or streamed locally in a backups/ subdirectory of the
# keyspace data.  Removing these links is the operator's
# responsibility.
# incremental_backups: false
```

**Comment by tzach** [comment]
Look like I mixed two features (inc repair and backup).
