### ISSUE TITLE
`Wait_for_ip failed` error on the new node after online discard disabling

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#21457]
## Packages

Scylla version: `6.3.0~dev-20240921.cd861bc78881` with build-id `66f68fcba94a28c6d0267156866992dd3da6f7a0`

Kernel Version: `6.8.0-1016-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

As part of the [issue](https://github.com/scylladb/scylladb/issues/20921) investigation I've been asked to run performance test with [disabled online discard](https://github.com/scylladb/scylladb/issues/20921#issuecomment-2430008401). 
 I tried to use `--online-discard 0` Scylla setup argument. But it did not disable the discard - opened issue https://github.com/scylladb/scylladb/issues/21426.

So I added the code that explicitly disable the discard. And it caused to the problem for Scylla start up.

I do not know why it happens and how to solve it:

1. create cluster with 3 nodes.
2. disable online discard after Scylla installation - succeeded
3. grow the cluster, add 3 nodes
4. disable online discard after Scylla installation on the new added nodes - Scylla started
```
sudo systemctl stop scylla-server.service
sudo umount /dev/nvme1n1
sudo mount /dev/nvme1n1 /var/lib/scylla -o rw,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota
sudo systemctl start scylla-server.service
```
6. continue with node configuration and stop/start Scylla again - then every "old node" (existing, not new added) got error `wait_for_ip failed` and complains that new added node failed to obtain IP. :
```
2024-10-31T22:01:54.473+00:00 elasticity-test-ubuntu-db-node-d6f29648-1  !WARNING | scylla[6982]:  [shard 0: gms] raft_topology - (rate limiting dropped 198 similar messages) cannot map 12e0129c-4fde-4d7b-a50d-5b3cdb380bf9 to ip, retrying.
2024-10-31T22:01:55.474+00:00 elasticity-test-ubuntu-db-node-d6f29648-1      !ERR | scylla[6982]:  [shard 0: gms] raft_topology - raft_topology_cmd wait_for_ip failed with: service::wait_for_ip_timeout (failed to obtain an IP for 12e0129c-4fde-4d7b-a50d-5b3cdb380bf9 in 30s)
2024-10-31T22:01:55.474+00:00 elasticity-test-ubuntu-db-node-d6f29648-1  !WARNING | scylla[6982]:  [shard 0: gms] raft_topology - raft_topology_cmd::command::wait_for_ip failed, error std::runtime_error (raft topology: exec_global_command(wait_for_ip) failed with std::runtime_error (failed status returned from b73c3ee7-458c-465c-906b-8578359f13b8/10.4.1.157))
2024-10-31T22:01:55.474+00:00 elasticity-test-ubuntu-db-node-d6f29648-1     !INFO | scylla[6982]:  [shard 0: gms] raft_topology - updating topology state: bootstrap: node rejected
2024-10-31T22:01:55.474+00:00 elasticity-test-ubuntu-db-node-d6f29648-1     !INFO | scylla[6982]:  [shard 0: gms] gossip - Removed endpoint 10.4.0.73
2024-10-31T22:01:55.474+00:00 elasticity-test-ubuntu-db-node-d6f29648-1     !INFO | scylla[6982]:  [shard 0: gms] gossip - InetAddress b3871b47-0c24-4722-b56f-d021126ee052/10.4.0.73 is now DOWN, status = UNKNOWN
2024-10-31T22:01:55.474+00:00 elasticity-test-ubuntu-db-node-d6f29648-1     !INFO | scylla[6982]:  [shard 0: gms] gossip - Finished to force remove node 10.4.0.73
2024-10-31T22:01:55.474+00:00 elasticity-test-ubuntu-db-node-d6f29648-1     !INFO | scylla[6982]:  [shard 0: gms] raft_topology - rejected node moved to left state b3871b47-0c24-4722-b56f-d021126ee052
```

And than Scylla start on the new added nodes failed:
```
024-10-31T22:00:55.865+00:00 elasticity-test-ubuntu-db-node-d6f29648-6      !ERR | scylla[6930]:  [shard 0:main] init - Startup failed: std::runtime_error (the topology coordinator rejected request to join the cluster: wait_for_ip failed, error std::runtime_error (raft topology: exec_global_command(wait_for_ip) failed with std::runtime_error (failed status returned from b73c3ee7-458c-465c-906b-8578359f13b8/10.4.1.157)))
```

**NOTE**: If do not run online discard disabling - startup successes and no failed to obtain an IP problem.

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- elasticity-test-ubuntu-db-node-d6f29648-6 (3.251.86.5 | 10.4.1.165) (shards: 7)
- elasticity-test-ubuntu-db-node-d6f29648-5 (34.244.117.92 | 10.4.0.73) (shards: 7)
- elasticity-test-ubuntu-db-node-d6f29648-4 (52.51.233.30 | 10.4.1.198) (shards: 7)
- elasticity-test-ubuntu-db-node-d6f29648-3 (52.49.118.7 | 10.4.2.140) (shards: 7)
- elasticity-test-ubuntu-db-node-d6f29648-2 (34.254.113.159 | 10.4.0.42) (shards: 7)
- elasticity-test-ubuntu-db-node-d6f29648-1 (63.32.59.72 | 10.4.1.157) (shards: 7)

OS / Image: `ami-01c7a2af0b5876566` (aws: undefined_region)

Test: `scylla-master-perf-regression-latency-650gb-elasticity-20921`
Test id: `d6f29648-cbe7-4d7e-af33-9b5a06fadf96`
Test name: `scylla-staging/yulia/performance/scylla-master-perf-regression-latency-650gb-elasticity-20921`
Test method: `performance_regression_test.PerformanceRegressionTest.test_latency_read_with_nemesis`
Test config file(s):

- [perf-regression-latency-650gb-elasticity.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/11ee9e7b435308a290e59a4a434f6275e99d781e/test-cases/performance/perf-regression-latency-650gb-elasticity.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d6f29648-cbe7-4d7e-af33-9b5a06fadf96`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d6f29648-cbe7-4d7e-af33-9b5a06fadf96)
- Show all stored logs command: `$ hydra investigate show-logs d6f29648-cbe7-4d7e-af33-9b5a06fadf96`

## Logs:
- **db-cluster-d6f29648.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/db-cluster-d6f29648.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/db-cluster-d6f29648.tar.gz)
- **sct-runner-events-d6f29648.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/sct-runner-events-d6f29648.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/sct-runner-events-d6f29648.tar.gz)
- **sct-d6f29648.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/sct-d6f29648.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/sct-d6f29648.log.tar.gz)
- **loader-set-d6f29648.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/loader-set-d6f29648.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/loader-set-d6f29648.tar.gz)
- **monitor-set-d6f29648.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/monitor-set-d6f29648.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d6f29648-cbe7-4d7e-af33-9b5a06fadf96/20241031_220538/monitor-set-d6f29648.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/performance/job/scylla-master-perf-regression-latency-650gb-elasticity-20921/13/)
[Argus](https://argus.scylladb.com/test/05ddbde6-0609-45c4-8585-33c786e10b46/runs?additionalRuns[]=d6f29648-cbe7-4d7e-af33-9b5a06fadf96)
</details>

**Comment by mykaul** [comment]
This looks completely unrelated to each other. Anything else that we can see in the node's log? journal perhaps?

**Comment by piodul** [comment]
It looks that the three nodes from step 3 were not bootstrapped properly, they were shut down before the bootstrap process finished.

For example:

```
Oct 31 21:59:24.438251 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - setup_group0: joining group 0...
Oct 31 21:59:24.439634 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - server fd2bf65e-5bee-4b24-b9a2-eaf702c2c7e4 found no local group 0. Discovering...
Oct 31 21:59:24.440355 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - server fd2bf65e-5bee-4b24-b9a2-eaf702c2c7e4 found group 0 with group id 3dded101-97a7-11ef-9dd2-f1aa776782de, leader 51f8cf51-3572-41fb-a746-24267b69753e
Oct 31 21:59:24.440385 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_topology - join: sending the join request to 10.4.2.140
Oct 31 21:59:24.592702 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_topology - join: request to join placed, waiting for the response from the topology coordinator
Oct 31 21:59:24.595707 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - Server fd2bf65e-5bee-4b24-b9a2-eaf702c2c7e4 is starting group 0 with id 3dded101-97a7-11ef-9dd2-f1aa776782de
Oct 31 21:59:24.600488 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - Detected snapshot with index=0, id=b3d354b2-4b70-448d-8a8e-ac7bf075bd6f, triggering new snapshot
Oct 31 21:59:24.600497 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - Could not create new snapshot, there are no entries applied
Oct 31 21:59:24.791175 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:main] compaction_manager - Asked to stop
Oct 31 21:59:24.791226 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:main] view_update_generator - Terminating background fiber
```

The node told the topology coordinator that it wants to join, and then it was shut down before the procedure completed ("Asked to stop" suggests that the node was requested to be stopped). The procedure is not retryable and the topology coordinator will reject the second attempt to bootstrap the nodes.

You should wait until the nodes are properly bootstrapped and reach the NORMAL status and only then restart and change configuration.

**Comment by juliayakovlev** [comment]
> It looks that the three nodes from step 3 were not bootstrapped properly, they were shut down before the bootstrap process finished.
> 
> For example:
> 
> ```
> Oct 31 21:59:24.438251 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - setup_group0: joining group 0...
> Oct 31 21:59:24.439634 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - server fd2bf65e-5bee-4b24-b9a2-eaf702c2c7e4 found no local group 0. Discovering...
> Oct 31 21:59:24.440355 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - server fd2bf65e-5bee-4b24-b9a2-eaf702c2c7e4 found group 0 with group id 3dded101-97a7-11ef-9dd2-f1aa776782de, leader 51f8cf51-3572-41fb-a746-24267b69753e
> Oct 31 21:59:24.440385 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_topology - join: sending the join request to 10.4.2.140
> Oct 31 21:59:24.592702 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_topology - join: request to join placed, waiting for the response from the topology coordinator
> Oct 31 21:59:24.595707 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - Server fd2bf65e-5bee-4b24-b9a2-eaf702c2c7e4 is starting group 0 with id 3dded101-97a7-11ef-9dd2-f1aa776782de
> Oct 31 21:59:24.600488 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - Detected snapshot with index=0, id=b3d354b2-4b70-448d-8a8e-ac7bf075bd6f, triggering new snapshot
> Oct 31 21:59:24.600497 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:strm] raft_group0 - Could not create new snapshot, there are no entries applied
> Oct 31 21:59:24.791175 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:main] compaction_manager - Asked to stop
> Oct 31 21:59:24.791226 elasticity-test-ubuntu-db-node-d6f29648-5 scylla[5312]:  [shard 0:main] view_update_generator - Terminating background fiber
> ```
> 
> The node told the topology coordinator that it wants to join, and then it was shut down before the procedure completed ("Asked to stop" suggests that the node was requested to be stopped). The procedure is not retryable and the topology coordinator will reject the second attempt to bootstrap the nodes.
> 
> You should wait until the nodes are properly bootstrapped and reach the NORMAL status and only then restart and change configuration.

Thanks, @piodul , I will add waiting for bootstrap finish and re-test

**Comment by swasik** [comment]
We confirmed that this was problem related to the test setup so closing this issue.
