### ISSUE TITLE
alternator_tests.test_slow_query_logging failed in configuration_exception (Unrecognized strategy option {UNKNOWN_DC}..)

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylladb#21490]
seen in https://jenkins.scylladb.com/job/scylla-master/job/next/8447/testReport/junit/alternator_tests/TesterAlternator/Build___x86___dtest_with_tablets___test_slow_query_logging/

```
self = <alternator_tests.TesterAlternator object at 0x7f2954ac43b0>

    @pytest.mark.next_gating
    @pytest.mark.skip_if(with_feature("tablets") & issue_open("#18002"))
    def test_slow_query_logging(self):
        """
        Test slow query logging for alternator queries.
        Verifies https://github.com/scylladb/scylla/pull/8298
        Test scenario:
        1) Configure slow-query threshold to a low number.
        2) Issue Alternator long-enough queries
        3) Verify slow queries of create-table are logged.
        4) Verify slow queries of create-table are stopped being logged after set to disabled.
        """
        # Setting a small enough threshold value that is lower than createTable operation minimum duration.
        slow_query_threshold = 2
        num_of_nodes = self._num_of_nodes_for_test(rf=3)
        self.prepare_dynamodb_cluster(num_of_nodes=num_of_nodes)
        node1 = self.cluster.nodelist()[0]
        logger.info("Running background stress and topology changes..")
        self.create_table(table_name=TABLE_NAME, node=node1)
        stress_thread = self.run_write_stress(table_name=TABLE_NAME, node=node1, num_of_item=1000, ignore_errors=True)
        decommission_thread = self.run_decommission_add_node_thread()
    
        logger.info("Enable slow-query-logging with specified threshold")
        self._set_slow_query_logging_api(run_on_node=node1, threshold=slow_query_threshold)
        logger.info("Execute 5 'createTable' slow-enough queries")
        first_table_names = self.create_tables(count=5, node=node1)
        logger.info("Verify all created tables are found in log results")
        self.wait_for_create_table_slow_query_logs(node=node1, table_names=first_table_names)
        logger.info("Disable slow-query-logging")
        self._set_slow_query_logging_api(run_on_node=node1, is_enable=False)
        logger.info("Execute 5 additional 'createTable' slow-enough queries after slow-query-logging is disabled")
>       second_table_names = self.create_tables(count=5, node=node1)

alternator_tests.py:1122: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
alternator_tests.py:1075: in create_tables
    self.create_table(table_name=name, node=node)
alternator_utils.py:299: in create_table
    table = dynamodb_api.resource.create_table(TableName=table_name, BillingMode="PAY_PER_REQUEST", **schema, **stream, **kwargs)
/usr/local/lib/python3.12/site-packages/boto3/resources/factory.py:580: in do_action
    response = action(self, *args, **kwargs)
/usr/local/lib/python3.12/site-packages/boto3/resources/action.py:88: in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
/usr/local/lib/python3.12/site-packages/botocore/client.py:535: in _api_call
    return self._make_api_call(operation_name, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.client.DynamoDB object at 0x7f29521d1370>
operation_name = 'CreateTable'
api_params = {'AttributeDefinitions': [{'AttributeName': 'hash_key', 'AttributeType': 'S'}], 'BillingMode': 'PAY_PER_REQUEST', 'KeySchema': [{'AttributeName': 'hash_key', 'KeyType': 'HASH'}], 'TableName': '653KE63LPA'}

    def _make_api_call(self, operation_name, api_params):
        operation_model = self._service_model.operation_model(operation_name)
        service_name = self._service_model.service_name
        history_recorder.record(
            'API_CALL',
            {
                'service': service_name,
                'operation': operation_name,
                'params': api_params,
            },
        )
        if operation_model.deprecated:
            logger.debug(
                'Warning: %s.%s() is deprecated', service_name, operation_name
            )
        request_context = {
            'client_region': self.meta.region_name,
            'client_config': self.meta.config,
            'has_streaming_input': operation_model.has_streaming_input,
            'auth_type': operation_model.auth_type,
        }
        api_params = self._emit_api_params(
            api_params=api_params,
            operation_model=operation_model,
            context=request_context,
        )
        endpoint_url, additional_headers = self._resolve_endpoint_ruleset(
            operation_model, api_params, request_context
        )
        request_dict = self._convert_to_request_dict(
            api_params=api_params,
            operation_model=operation_model,
            endpoint_url=endpoint_url,
            context=request_context,
            headers=additional_headers,
        )
        resolve_checksum_context(request_dict, operation_model, api_params)
    
        service_id = self._service_model.service_id.hyphenize()
        handler, event_response = self.meta.events.emit_until_response(
            'before-call.{service_id}.{operation_name}'.format(
                service_id=service_id, operation_name=operation_name
            ),
            model=operation_model,
            params=request_dict,
            request_signer=self._request_signer,
            context=request_context,
        )
    
        if event_response is not None:
            http, parsed_response = event_response
        else:
            maybe_compress_request(
                self.meta.config, request_dict, operation_model
            )
            apply_request_checksum(request_dict)
            http, parsed_response = self._make_request(
                operation_model, request_dict, request_context
            )
    
        self.meta.events.emit(
            'after-call.{service_id}.{operation_name}'.format(
                service_id=service_id, operation_name=operation_name
            ),
            http_response=http,
            parsed=parsed_response,
            model=operation_model,
            context=request_context,
        )
    
        if http.status_code >= 300:
            error_info = parsed_response.get("Error", {})
            error_code = error_info.get("QueryErrorCode") or error_info.get(
                "Code"
            )
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.errorfactory.InternalServerError: An error occurred (InternalServerError) when calling the CreateTable operation (reached max retries: 0): Internal server error: exceptions::configuration_exception (Unrecognized strategy option {UNKNOWN_DC} passed to org.apache.cassandra.locator.NetworkTopologyStrategy for keyspace alternator_653KE63LPA)

/usr/local/lib/python3.12/site-packages/botocore/client.py:983: InternalServerError
```

full log: [dtest-gw1.log](https://github.com/user-attachments/files/17667068/dtest-gw1.log)
node logs: [1730973511674_alternator_tests.py__TesterAlternator__test_slow_query_logging.zip](https://github.com/user-attachments/files/17667074/1730973511674_alternator_tests.py__TesterAlternator__test_slow_query_logging.zip)

**Comment by tchaikov** [comment]
spotted again: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1614/testReport/junit/alternator_tests/TesterAlternator/FullDtest___full_split001___test_slow_query_logging/

**Comment by tchaikov** [comment]
and again: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13214

**Comment by ptrsmrn** [comment]
> An error occurred (InternalServerError) when calling the CreateTable operation (reached max retries: 0): Internal server error: exceptions::configuration_exception (Unrecognized strategy option {UNKNOWN_DC} passed to org.apache.cassandra.locator.NetworkTopologyStrategy for keyspace alternator_653KE63LPA)

I don't think "Unrecognized strategy option {UNKNOWN_DC} passed to org.apache.cassandra.locator.NetworkTopologyStrategy for keyspace alternator_653KE63LPA" is an internal error, we throw
```
throw exceptions::configuration_exception(...);
```
in `abstract_replication_strategy::validate_replication_strategy` for unsupported strategies and `UNKNOWN_DC` is unsupported strategy name.

**Comment by ptrsmrn** [comment]
is the driver translating this exception incorrectly into the InternalServerError?

**Comment by ptrsmrn** [comment]
I don't see `UNKNOWN_DC` symbol used anywhere in the dtests repository.
The only mention of it comes from scylladb `s2/locator/production_snitch_base.hh`:
```
static constexpr const char* default_dc   = "UNKNOWN_DC";
```
Which indicates something in snitch might have falied.

**Comment by ptrsmrn** [comment]
BTW. `dtest-gw1.log.txt` has 2k+ mentions of the word _error_, I can't possibly go through all of them (and also check for _warning_s etc.), which makes these logs a bit useless.

**Comment by ptrsmrn** [comment]
This is interesting, in `node1.log` I see:
> WARN  2024-11-07 09:58:08,651 [shard 0:stmt] topology - Requested location for node 127.0.86.4 not in topology. backtrace 0x62040de 0x6204700 0x6204a08 0x3e0b819 /jenkins/workspace/scylla-master/gating-dtest-release-with-tablets/scylla/.ccm/scylla-repository/ef104b7b9605eca48688ff87d81345320131136a/libreloc/libfmt.so.10+0x12ab6 /jenkins/workspace/scylla-master/gating-dtest-release-with-tablets/scylla/.ccm/scylla-repository/ef104b7b9605eca48688ff87d81345320131136a/libreloc/libfmt.so.10+0x1542e 0x3e0c3bb 0x6210604 0x3e06d99 0x4f1f2fa 0x4f61492 0x4e1605a 0x5d02d7f 0x5d0431a 0x5d054f7 0x5d048a8 0x5c930b3 0x5c92413 0x13dffb5 0x13e1970 0x13de3d3 /jenkins/workspace/scylla-master/gating-dtest-release-with-tablets/scylla/.ccm/scylla-repository/ef104b7b9605eca48688ff87d81345320131136a/libreloc/libc.so.6+0x2a087 /jenkins/workspace/scylla-master/gating-dtest-release-with-tablets/scylla/.ccm/scylla-repository/ef104b7b9605eca48688ff87d81345320131136a/libreloc/libc.so.6+0x2a14a 0x13dba54

Which is decoded as:
```

**Comment by ptrsmrn** [comment]
So the stacktrace indicates `locator::topology::get_datacenter` was called and it most probably returned `UNKNOWN_DC` (which explains https://github.com/scylladb/scylladb/issues/21490#issuecomment-2485121292). 
I also see this in the log:
> WARN  2024-11-07 09:57:39,504 [shard 0: gms] raft_topology - cannot map 0c7b2d0a-5e5a-473c-8b57-ffee647c34d2 to ip, retrying.

Perhaps that explains the unknown DC.

**Comment by ptrsmrn** [comment]
@kbr-scylla is what I wrote in the comment above normal? Or does it indicate something went south?

**Comment by kostja** [comment]
@ptrsmrn looks like a genuine bug to me. The tablets are enabled, and this leads to CREATE KEYSPACE actually veirfying that the keyspace definition maps to the physical topologyT of the cluster. But the node has not gossiped apparently its physical topology yet.

This is how it happens: when the node boots, it looks at its snitch file, and adds its contents to the gossip messages it disseminates. This is how other nodes learn about its DC. However, this doesn't happen immediately, the initial gossip messages do not contain snitch data (Cc @xemul). So my theory is that this node is already present in locator::topology, but its snitch data is not complete yet. this is not expected by CREATE KEYSPACE.

**Comment by ptrsmrn** [comment]
@kostja thanks. I think the problem may be not with the boot but shutting a node down.

Out of the relevant parts for this issue, the test flow is as follows:
1. Init a dynamodb cluster with 4 nodes
2. `run_decommission_add_node_thread()` is called, which decomissions 4th node and adds 5th
3. I think 4th node gets decomission req at:
```
// node4.log
INFO  2024-11-07 09:57:55,010 [shard 0:strm] api - decommission
INFO  2024-11-07 09:57:55,011 [shard 0:strm] raft_topology - request decommission for: 8d159d3b-3534-4d8a-96ef-2a6ac0bf9ad0
```
4. And here's where the things get tricky - 4th node decomission is done at:
```
// node4.log
INFO  2024-11-07 09:58:08,417 [shard 0:strm] raft_topology - streaming completed
... // compaction, bloom filter rebuilding
INFO  2024-11-07 09:58:08,679 [shard 0:strm] raft_topology - decommission: successfully removed from topology (request ID: c2710216-9cee-11ef-dc51-eca8f015ecc6), updating gossip status
INFO  2024-11-07 09:58:08,679 [shard 0:strm] raft_topology - Decommission succeeded. Request ID: c2710216-9cee-11ef-dc51-eca8f015ecc6
```
and 1st node requests for 4th's node location earlier, before it's officially decomissioned:
```
// node1.logs, here's where the failure is at:
WARN  2024-11-07 09:58:08,651 [shard 0:stmt] topology - Requested location for node 127.0.86.4 not in topology. backtrace ...
```
Only later it also ack the 4th node's decommission:
```
// node4.log
INFO  2024-11-07 09:58:08,681 [shard 0: gms] raft_topology - removing node 8d159d3b-3534-4d8a-96ef-2a6ac0bf9ad0 from group 0 configuration...
INFO  2024-11-07 09:58:08,682 [shard 0:main] raft_group_registry - marking Raft server 8d159d3b-3534-4d8a-96ef-2a6ac0bf9ad0 as dead for raft groups
```

**Comment by ptrsmrn** [comment]
These are the 1st node's raft logs from before the error:
```
INFO  2024-11-07 09:58:08,418 [shard 0: gms] raft_topology - updating topology state: decommissioning: streaming completed for node 8d159d3b-3534-4d8a-96ef-2a6ac0bf9ad0
INFO  2024-11-07 09:58:08,438 [shard 0: gms] raft_topology - entered `write both read new` transition state
INFO  2024-11-07 09:58:08,438 [shard 0: gms] raft_topology - executing global topology command barrier_and_drain, excluded nodes: {}
INFO  2024-11-07 09:58:08,476 [shard 0:stmt] migration_manager - Schema agreement check passed.
INFO  2024-11-07 09:58:08,486 [shard 0: gms] raft_topology - updating topology state: advance fence version to 12
... // compaction, bloom filter rebuild
INFO  2024-11-07 09:58:08,507 [shard 0: gms] raft_topology - updating topology state: decommissioning: read fence completed
INFO  2024-11-07 09:58:08,523 [shard 0: gms] raft_topology - entered `left token ring` transition state
INFO  2024-11-07 09:58:08,523 [shard 0: gms] raft_topology - executing global topology command barrier_and_drain, excluded nodes: {}
... // compaction, bloom filter rebuild
INFO  2024-11-07 09:58:08,583 [shard 0: gms] raft_topology - updating topology state: advance fence version to 13
INFO  2024-11-07 09:58:08,594 [shard 0: gms] raft_topology - updating topology state: report request completion in left_token_ring state
WARN  2024-11-07 09:58:08,651 [shard 0:stmt] topology - Requested location for node 127.0.86.4 not in topology. backtrace ...
```
1st node couldn't assume that the 4th node is decomissioned, because that happened later, which I mention in the comment above, but maybe these operations erased some 4th node's data, which made 1st node "crash".

**Comment by ptrsmrn** [comment]
@asias by https://github.com/scylladb/scylladb/pull/21088#issuecomment-2485373463 do you mean that your PR is going to fix this issue?

**Comment by ptrsmrn** [comment]
@kostja @mykaul I'm not sure how to make progress, maybe someone else can take a look

**Comment by ptrsmrn** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/482910?s=64&amp;u=b76308ed86961c1c146d5d78a86b0d726b6ef0a1&amp;v=4">@kostja](https://github.com/kostja) [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/4655593?s=64&amp;u=4dddfbf798e52ae4a5d9ee628e6fab1fb22461cb&amp;v=4">@mykaul](https://github.com/mykaul) I'm not sure how to make progress, maybe someone else can take a look

@mykaul @kostja ping

**Comment by mykaul** [comment]
node 4 log[node4.log](https://github.com/user-attachments/files/17930936/node4.log)

**Comment by mykaul** [comment]
@kostja - looks like an alternator/Raft race of some sort?

**Comment by kostja** [comment]
Could be a dup of https://github.com/scylladb/scylladb/issues/20036

**Comment by kostja** [comment]
I have a theory for this if tablets are ON. But with tablets OFF I am lost. Alternator is not using tablets, so they must be OFF. So I'd wait for more occurrences.

**Comment by Annamikhlin** [comment]
seen again on https://jenkins.scylladb.com/job/scylla-master/job/next/8529/testReport/junit/alternator_tests/TesterAlternator/Build___x86___dtest_with_tablets___test_slow_query_logging/

**Comment by fruch** [comment]
I happend 10 times only in the last month:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/7732e3b0-b02f-11ef-81c7-3986d18dafd5

seen first Nov 6, with scylla `6.3.0-dev-0.20241106.583455ef21ce`

9/10 was with tablets jobs, first occurrence was with consistent-topology-changes job

**Comment by lsfreitas** [comment]
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/next/8554/testReport/alternator_tests/TesterAlternator/Build___x86___dtest_with_tablets___test_slow_query_logging/

**Comment by mykaul** [comment]
> I have a theory for this if tablets are ON. But with tablets OFF I am lost. Alternator is not using tablets, so they must be OFF. So I'd wait for more occurrences.

@kostja - we now have more occurences.

**Comment by lsfreitas** [comment]
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/next/8578/testReport/alternator_tests/TesterAlternator/Build___x86___dtest_with_tablets___test_slow_query_logging/

**Comment by kostja** [comment]
@nyh get_network_topology_options() is using gossip data and iterates topology using IPs not host ids. This is asking for an inconsistency like above. What is the reason to not use get_datacenters()?

**Comment by nyh** [comment]
> [@nyh](https://github.com/nyh) get_network_topology_options() is using gossip data and iterates topology using IPs not host ids. This is asking for an inconsistency like above. What is the reason to not use get_datacenters()?

Feel free to change it, I guess I just used whatever API I thought was available and perhaps not the best one available back then, and very likely not the best one available today.
The only purpose of this function is to create a map like `{dc1: 3, d2: 3}` so the keyspace we create will have RF=3 on each of the live data centers. There was certainly no intention to look at IP addresses or host IDs.

**Comment by kostja** [comment]
@ptrsmrn I think this place is the culprit. It should call get_datacenters() directly and not iterate over IPs in gossip. Could you please send a patch?
