### ISSUE TITLE
Alternator "/localnodes" can return a down node

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#21538]
In https://github.com/scylladb/scylladb/pull/19725 we fixed the Alternator "/localnodes" API to only return nodes in "normal" state, to avoid returning nodes in joining state that cannot really respond to requests. The fix was changing a check of `_gossiper.is_alive(ip)` to `_gossiper.is_normal(ip)`. I assumed that is_normal() also checks is_alive() (how can a node be _normal_ if it's not alive?), but as @hopugop discovered - this assumption is incorrect: A node **can** be in "DN" state. It can happen in a node was once in normal state, but currently known it be down.

So we need to check both - `_gossiper.is_alive(ip) && _gossiper.is_normal(ip)`.

The test that I wrote for /localnodes as part of  https://github.com/scylladb/scylladb/pull/19725 missed this situation - it brought down a node in an orderly fashion (with "nodetool drain")  and it disappeared from "/localnodes" because it was no longer "normal". We also need a test that brings the node down in a way that leaves it in "normal" state in the gossiper.

**Comment by nyh** [comment]
The fix for this issue would need to be backported to all the live branches to which https://github.com/scylladb/scylladb/pull/19725 was backported :-(

**Comment by avikivity** [comment]
Why is it wrong to return a node that is temporarily down?

How often will a client query /localnodes? If it's queried rarely, then we can forget that a node exists.

**Comment by nyh** [comment]
> Why is it wrong to return a node that is temporarily down?

What is "temporarily" down? 5 seconds? 5 minutes? 5 hours?

Also, while you are right that there are situations when we know that a node is **decomissioned** and we're absolutely sure it is gone forever, I think there are many situations where we just don't know. If a node died, will it ever come back or not?

> How often will a client query /localnodes? If it's queried rarely, then we can forget that a node exists.

What I am fixing here is a mechanism in Scylla which a load-balancer implementation to implement its own policy. It can decide that if it gets a new list of nodes and node A disappeared from it, maybe the best thing is to remove A from the load balancing **immediately** (after all, we know this work is down now!) but maybe it's worth checking again in a few seconds instead of the default one minute - or whatever. That is a good idea, I can open an issue about it. You're right that if the API told us that for sure A is down for good there is no point to retry getting the list in a few seconds - but I don't think that optimization is interesting.

The current implementation of the load balancer doesn't have this - the Java implementation has a sleep of 1000 seconds between each `updateLiveNodes()` call so it may not notice that a node is down for 1000 seconds (oops... this magic 1000 came all the way from commit cc45fb43860f11b68cc13d3281fdf9503d4cfdad), and will also not notice that a node came back up in 1000 seconds.  
The Python driver does this every 1 second, not 1000. The API to get this list is so cheap, I hardly see a reason not to do it, unless we have a huge number of idle clients, where there are more silly localnodes requests than real requests. Maybe clients should be lazy, and not perform the localnodes requests until a real request happens. I'll open issues about all these ideas.

**Comment by nyh** [comment]
Turns out I'm an idiot, in Java `Thread.sleep(1000);` sleeps for 1000 **milliseconds**, not 1000 seconds :-)
So it's a 1-second node-list update frequency in both Python and Java load balancers.
This is more frequent than our gossiper turnaround time, so we'll discover a node is down as soon as the gossiper discovers it, and discover it is back up as soon as the gossiper discovers it.
