### ISSUE TITLE
mutate_MV may lose paired view replica if it is swapped with my_address

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#21549]
First thing, mutate_MV sets target_endpoint to a paired replica: https://github.com/scylladb/scylladb/blob/1c212df62de2cd7d464a20b542a320446239c1c6/db/view/view.cc#L1873

Then, if `target_endpoint` is not the local node's address (`my_address`), but my_address is a pending endpoint (i.e. exists in `remote_endpoints`), we swap it with `target_endpoint`, in: https://github.com/scylladb/scylladb/blob/1c212df62de2cd7d464a20b542a320446239c1c6/db/view/view.cc#L1900

and at this point we lose track of it and we may choose a different endpoint if there are multiple pending endpoints, in: https://github.com/scylladb/scylladb/blob/1c212df62de2cd7d464a20b542a320446239c1c6/db/view/view.cc#L1947

Based on the CL we may still send the updates to the paired replica that is listed in `remote_endpoints`, in:  https://github.com/scylladb/scylladb/blob/1c212df62de2cd7d464a20b542a320446239c1c6/db/view/view.cc#L1959

But I don't think it's guaranteed to happen.

**Comment by wmitros** [comment]
If I'm not mistaken, it should actually be guaranteed that we'll wait for the update to be sent to the view replica even if some other replica is used as `target_endpoint`
In `apply_to_remote_endpoints` we call `send_to_endpoint` where we eventually add both the `target_endpoint` and all remaining `remote_endpoints` to a list:
https://github.com/scylladb/scylladb/blob/1c212df62de2cd7d464a20b542a320446239c1c6/service/storage_proxy.cc#L4061-L4068
And in the write response handler we set `_total_block_for` to basically all endpoints (`db::block_for` returns 1 for both cl::ONE and cl::ANY used for view updates, `pending_endpoints` below is the same as `remote_endpoints.size()`)
https://github.com/scylladb/scylladb/blob/1c212df62de2cd7d464a20b542a320446239c1c6/service/storage_proxy.cc#L1416

**Comment by bhalevy** [comment]
Okay, fair enough, that should do.
