### ISSUE TITLE
docs: Issue on page Install ScyllaDB Linux Packages

### ISSUE THREAD

**Issue by pdbossman** [scylladb/scylladb#21557]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-6.2/getting-started/install-scylla/install-on-linux

### Problem
Public key is not available.

```
Reading package lists... Done
W: GPG error: https://downloads.scylladb.com/downloads/scylla/deb/debian-ubuntu/scylladb-6.2 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A43E06657BAC99E3
E: The repository 'https://downloads.scylladb.com/downloads/scylla/deb/debian-ubuntu/scylladb-6.2 stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

###  Suggest a fix

Fix the keys.

**Comment by ut0mt8** [comment]
is it supposed to be fixed?

**Comment by tchaikov** [comment]
Yes, it is supposed to be fixed already.

**Comment by ut0mt8** [comment]
> Yes, it is supposed to be fixed already.

Yup but not in the doc in the site last time I watched

**Comment by tchaikov** [comment]
@ut0mt8 hi Raphael, yeah. it might take time to populate the change to our web server. i believe it's now fixed. see https://opensource.docs.scylladb.com/stable/getting-started/install-scylla/install-on-linux.html
