### ISSUE TITLE
Can we get each row's old versions and timestamps?

### ISSUE THREAD

**Issue by takaaki7** [scylladb/scylladb#21559]
For example, bigtable retain multi version for each cell, and user can read old rows, and can read each row's version(that is server-side generated timestamp by default)
https://cloud.google.com/bigtable/docs/overview

Does Scylladb support those operations?
- Read old version row
- Read each rows timestamp

**Comment by mykaul** [comment]
Hi @takaaki7 - https://forum.scylladb.com is a better venue to ask such questions.
