### ISSUE TITLE
Eradicate link to old "alternator-preview" branch, or the old branch itself

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#21606]
Today, I got a question from a user who pointed me to https://github.com/scylladb/scylladb/blob/alternator-preview/docs/alternator/alternator.md and asked whether it accurately documents what Alternator supports. The answer is obviously **no** - that "alternator-preview" branch in that URL is a 5 year old branch that we branched before Alternator was ready for GA, and now is a living fossil among dozens of other ancient branches. The information in it is completely outdated.

So how did this customer even find this link?
I suspect the five-year-old blog post https://www.scylladb.com/2019/09/11/scylla-alternator-the-open-source-dynamodb-compatible-api/ by @dorlaor - which has that link in its "The Current Status of Alternator" section.

I think we should consider changing this link in that old blog post to the modern version of this link - namely to https://github.com/scylladb/scylladb/blob/master/docs/alternator/compatibility.md

We should probably also search for "alternator-preview" links in all our blog posts, perhaps there are more of them that I missed - and fix all we find.

Another possibility we should consider is to delete the **alternator-preview** branch. But I think this opens up a lot of questions... We don't normally delete old branches - we even have branch-0.10. Should we start deleting old branches? Or just "alternator-preview"? Were we just unlucky that a user found that "alternator-preview" link and not a "branch-0.10" link ?

**Comment by tzach** [comment]
> I think we should consider changing this link in that old blog post to the modern version of this link - namely to https://github.com/scylladb/scylladb/blob/master/docs/alternator/compatibility.md

Done

**Comment by tzach** [comment]
> Another possibility we should consider is to delete the alternator-preview branch. But I think this opens up a lot of questions... We don't normally delete old branches - we even have branch-0.10. Should we start deleting old branches? Or just "alternator-preview"? Were we just unlucky that a user found that "alternator-preview" link and not a "branch-0.10" link ?

Since linking to old branches is an exception, deleting or renaming the branch, in this case, makes sense.

**Comment by nyh** [comment]
@tzach thanks for changing the link in the old blog post. I think since I can't find any more links to that old branch, I prefer not to touch it and just leave it be.
