### ISSUE TITLE
Clean old and none relevant open PRs

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#21675]
I have noticed that in the Scylladb repo, we currently have 263 open PR (based on master),

And about 125 of them are 6 months old or more (we have even a PR from 2019 :-)

please see https://github.com/scylladb/scylladb/pulls?q=is%3Aopen+base%3Amaster+created%3A%3C2024-02-14+

**Comment by yaronkaikov** [comment]
I would assume that PRs opened more than 3-4 months are not relevant

1. We can/should notify PR owners when a PR is opened over X days (Month?) 
2. Close it if no actions in 2-3 months 

@dani-tweig @avikivity @mykaul @roydahan  does it sound reasonable ?

**Comment by mykaul** [comment]
I don't see the value in cleaning it. What's the motivation?

**Comment by yaronkaikov** [comment]
When we branch to new releases we often miss open PRs from being backported to new releases (because they are open), so we have added in our automation scan for all open PRs (based to `master`) so we can add the relevant label 

having a lot of open PRs (which clearly no one use) doesn't make any sense and will just increase the time it will take us to scan those PRs

**Comment by nyh** [comment]
> I don't see the value in cleaning it. What's the motivation?

I wholeheartedly agree with the not seeing a value. Looking at my own open PRs, I see some that I forgot to nag about (and I should), but also some that were really worthy ideas but for some reason not ready for the lime light, so I turned them into "draft". In general, I think we should encourage developers to turn every pull request that they do not want to be reviewed suddenly - to be turned into a draft. 
But I would definitely not like a bot that "cleans" (closes) those PRs.

If you find yourself having to "scan" all open PRs, can't you filter out from this scan old PRs?

**Comment by yaronkaikov** [comment]
> > I don't see the value in cleaning it. What's the motivation?
> 
> I wholeheartedly agree with the not seeing a value. Looking at my own open PRs, I see some that I forgot to nag about (and I should), but also some that were really worthy ideas but for some reason not ready for the lime light, so I turned them into "draft". In general, I think we should encourage developers to turn every pull request that they do not want to be reviewed suddenly - to be turned into a draft. But I would definitely not like a bot that "cleans" (closes) those PRs.
> 
> If you find yourself having to "scan" all open PRs, can't you filter out from this scan old PRs?

Yes, this is what we will do :-)
