### ISSUE TITLE
types: large allocations and stalls while comparing Decimal values

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#21716]
Recently, we have seen a case where a cluster became completely unresponsive, spewing large allocation warnings and stalls in the logs.
It turned out that the problem is caused by `Decimal` type used in primary keys (both as partition and as clustering key). Some of the values in these tables were huge, resulting in large allocations and stalls with backtraces like this: [decimal-backtrace.txt](https://github.com/user-attachments/files/17947611/decimal-backtrace.txt)

We have seen large allocations of >= 1GiB and multi-second stalls.

The reason is the way comparing decimals work:
https://github.com/scylladb/scylladb/blob/23a7e9a6d09dcc631d2b42c72f7a18ddd63a2b87/utils/big_decimal.cc#L137-L144

The numbers are first normalized w.r.t. their scale, then compared. This means that we potentially calculate 10 to the power of an arbitrarily large number (in practice, max power is maxint).

**Comment by nyh** [comment]
> Recently, we have seen a case where a cluster became completely unresponsive, spewing large allocation warnings and stalls in the logs. It turned out that the problem is caused by `Decimal` type used in primary keys (both as partition and as clustering key). Some of the values in these tables were huge, resulting in large allocations and stalls with backtraces like this: [decimal-backtrace.txt](https://github.com/user-attachments/files/17947611/decimal-backtrace.txt)

Good catch. We've known for a long time that if we start to support arithmetic operators in CQL as Cassandra 4 introduced, we'll have this problem when adding two decimals (see https://github.com/scylladb/scylladb/issues/2693#issuecomment-1529067047) but unfortunately we missed the fact we already have this problem, with comparison.

**Comment by nyh** [comment]
Note that this bug has a security (denial-of-service) implication: It is possible that by causing the database to insert specially-crafted numbers, e.g, 1e-10000000 and 1e+10000000, the database can potentially be crashed or hung while comparing these numbers.

In Alternator, to avoid this possibility (and also to be compatible with the limits of DynamoDB) we limited the scale of numbers (https://github.com/scylladb/scylladb/issues/6794) but this might not be allowed for CQL, so fixes like you're doing now might be the best thing we can do.

**Comment by nyh** [comment]
By the way, related issue about **printing** decimals: https://github.com/scylladb/scylladb/issues/8002
