### ISSUE TITLE
Recent conftest change broke pytest's default output format and made it too spammy

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#21712]
By default, pytest uses a concise output format which makes it easy to run interactively and see the progress of the test without much detail **unless a test fails**. For example,
```
cassandra_tests/batch_test.py ....xxxxxx                                [  1%]
cassandra_tests/functions/cast_fcts_test.py x                           [  1%]
cassandra_tests/validation/entities/counters_test.py xXxxxxx            [  2%]
cassandra_tests/validation/entities/secondary_index_test.py xxxxx       [  3%]
cassandra_tests/validation/entities/timestamp_test.py x                 [  3%]
```
Here you can see a new line when entering each new **test file**, and just a single character for each test function - `.` if the test was successful, `x` for xfail, `X` for xpass (passing xfail), etc. pytest also has the options `-v` and `-s` for overriding this default and being more verbose even on successful tests - showing a separate line for each test function, and/or showing output even of successful tests.

Much to my disappointment, we broke this tradition in commit 8bf62a086f6b6825907d900023b5da28f97fd2af which introduced a common conftest.py. One of the things this patch changed is the default format of the output. The output of "pytest test/cqlpy" (or test/cqlpy/run, which just runs pytest) is now supper-spammy, hundreds of lines go by while the test is running to the point you can't actually see what's going on or if anything failed, listing each individual test function and outputs all errors and warnings that happened even during successful tests (some tests have expected errors).

For example the output today (note how this is just part of one test file, reaching 0% of the work!!)
```
assandra_tests/batch_test.py::testMixedInCounterBatch 
------------------------------- live log setup --------------------------------
11:31:55.183 WARNING>  Server warning: Tables in this keyspace will be replicated using Tablets and will not support CDC, LWT and counters features. To use CDC, LWT or counters, drop this keyspace and re-create it without tablets by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
11:31:55.183 WARNING>  Server warning: Using Replication Factor datacenter1=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
11:31:55.199 WARNING>  Server warning: Using Replication Factor datacenter1=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
11:31:55.210 WARNING>  Server warning: Tables in this keyspace will be replicated using Tablets and will not support CDC, LWT and counters features. To use CDC, LWT or counters, drop this keyspace and re-create it without tablets by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
11:31:55.210 WARNING>  Server warning: Using Replication Factor datacenter1=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
11:31:55.216 WARNING>  Server warning: Tables in this keyspace will be replicated using Tablets and will not support CDC, LWT and counters features. To use CDC, LWT or counters, drop this keyspace and re-create it without tablets by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
11:31:55.216 WARNING>  Server warning: Using Replication Factor datacenter1=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
PASSED                                                                  [  0%]
cassandra_tests/batch_test.py::testMixedInLoggedBatch PASSED            [  0%]
cassandra_tests/batch_test.py::testMixedInUnLoggedBatch PASSED          [  0%]
cassandra_tests/batch_test.py::testNonCounterInCounterBatch PASSED      [  0%]
cassandra_tests/batch_test.py::testNonCounterInLoggedBatch[tablets] XFAIL [  0%]
```

The new output format is very inconvenient for interactive development, and importantly makes an incompatible change to pytest which we shouldn't have done.

@xtrey I understand that you wanted the output of "pytest" to better resemble the current output of "test.py". That's a mistake :-( The output of pytest should be familiar to people who like pytest - not to people who like test.py (by the way, the new output of pytest is even spammier than test.py). People can run "pytest -v" if they want more verbose output. Or you can have a script (say, "test.py") that runs pytest with the more verbose options. It shouldn't be default.

CC @xtrey

**Comment by nyh** [comment]
What caused the non-default spammy output from pytest is actually a single line in test/pytest.ini:
```
log_cli = true
```

I don't know what was the **intended** function of this line (I guess you just copied it from one the many `test/*/pytest.ini` files that used to exist), but it obviously does much more than it bargained for.

**Comment by mykaul** [comment]
On Jenkins, now I don't see a test level run time, just file level.
For example: test_tools - took 2 min 39 sec - but I don't know why/what test.
(taken from https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/lastCompletedBuild/testReport/(root)/non-boost%20tests/Build___aarch64___Unit_Tests_aarch64___cqlpy_test_tools_release_1/ )

Was that intended? I think we are missing some resolution here. Perhaps just in Jenkins?

**Comment by nyh** [comment]
pytest's junit feature does report the success and also execution time for each test function separately, I don't know why we lost this knowledge, but I don't think it's related to **this** issue, which was about tons of log output for successful tests and I don't think (?) is related to measuring the runtime.

I think you should open a new issue on the specific problem that bothers you, and get somebody who understands what actually happens in our Jenkins/junit/test.py combination to debug it. I don't understand it enough to give you a concrete answer.

By the way, I looked at a random log file on my laptop (note that it's not new, it's a couple of months old) , testlog/dev/xml/cqlpy.cassandra_tests/batch_test.1.xunit.xml
and I see it clearly measures the time of each individual test case (i.e., function). For example:
```
testcase classname="cassandra_tests.batch_test" name="testNonCounterInCounterBatch.dev.1" time="0.085"/>
```
