### ISSUE TITLE
backward incompatible change in `application_state_name`: `CDC_STREAMS_TIMESTAMP` -> `CDC_GENERATION_ID`

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#21811]
https://github.com/scylladb/scylladb/commit/e486e0f7593e6071d4bf0bb6915fffbd5fc57602 changed `application_state::CDC_STREAMS_TIMESTAMP` to `application_state::CDC_GENERATION_ID` but didn't touch the gossiped string:
```
The actual string gossiped by nodes in their application state is left
as "CDC_STREAMS_TIMESTAMP" for backward compatibility.
```
Then, https://github.com/scylladb/scylladb/commit/a840949ea04abf1696a0cc0fe5837762f16b06cf that was supposed to be a cleanup commit changed
```cpp
{application_state::CDC_GENERATION_ID,      "CDC_STREAMS_TIMESTAMP"}, /* not named "CDC_GENERATION_ID" for backward compatibility */
```
to
```cpp
    case application_state::CDC_GENERATION_ID:
        return "CDC_GENERATION_ID";
```
which is a backward incompatible change. If we do a rolling upgrade from a version without this change to a version with this change, nodes with different versions will fail to gossip this state.

I found this bug while browsing logs of the following longevity run: https://argus.scylladb.com/tests/scylla-cluster-tests/bb5271a9-0ba8-4c2d-9f83-b36c394079f3

Node 3 logged
```
Dec 02 14:07:04.227560 rolling-upgrade-artifacts--ubuntu-j-db-node-bb5271a9-0-3 scylla[17379]:  [shard  0: gms] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 10.142.1.3, application_states = {CDC_STREAMS_TIMESTAMP: Value(v2;1733148033946;a5c41290-b0b5-11ef-9a2c-f3001a6dc938,2), STATUS: Value(NORMAL,9016996953396528631,3), TOKENS: Value(9016996953396528631;8969105116291160787;...
```
and I was surprised when I found out that there is no `CDC_STREAMS_TIMESTAMP` in the code on master.

We should revert the gossiped string to "CDC_STREAMS_TIMESTAMP" before the next release.

Also, we should consider changing the log level of
```
logger.warn("Fail to apply application_state: {}", std::current_exception());
```
to ERROR so that our upgrade tests catch bugs like this one.

cc @kbr-scylla @emdroid

**Comment by kbr-scylla** [comment]
Thanks, great catch. This  is a major regression. It's sad that we're not catching such things in gating :(


@emdroid please fix. Also review the change if any other renames didn't slip in

**Comment by emdroid** [comment]
Oops ... yeah, it looks I apparently didn't notice the string difference when doing the cleanup change (might actually even used the Github Copilot to generate the cases which might have lead to that, could be it just generated the matching strings according to the ids and it is difficult to notice the difference then).

Will check the rest as well.

**Comment by emdroid** [comment]
There is one more: The previous string for `application_state::IGNORE_MSB_BITS` had `"IGNOR_MSB_BITS"` (note the missing "E" in "IGNORE") and has been changed to `"IGNORE_MSB_BITS"`. Will revert that one as well.
