### ISSUE TITLE
Add type to nodetool stop

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#2187]
Support compaction types in `nodetool stop`
compaction type:	COMPACTION, VALIDATION, CLEANUP, SCRUB, VERIFY, INDEX_BUILD.

Refernce: https://issues.apache.org/jira/browse/CASSANDRA-1740
Example: https://docs.datastax.com/en/cassandra/3.0/cassandra/tools/toolsStop.html

**Comment by slivne** [comment]
some of this are not relevant ....

we do not support scrub AFAIK

Index is not yet supported

verify was added in 2.2 (
https://issues.apache.org/jira/browse/CASSANDRA-5791) and we do not support
it

validation I think is related to repair


We do support cleanup/compaction/repair so those should be supported - the
rest are depdnent on adding the functionality as well (not only allowing to
stop it).

**Comment by tzach** [comment]
related addition to nodetool stop compaction: 
nodetool: Allow to stop a specific compaction https://issues.apache.org/jira/browse/CASSANDRA-7207

**Comment by raphaelsc** [comment]
On Thu, Mar 23, 2017 at 12:33 PM, Tzach Livyatan <notifications@github.com>
wrote:

> related addition to nodetool stop compaction:
> nodetool: Allow to stop a specific compaction https://issues.apache.org/
> jira/browse/CASSANDRA-7207
>
 It's possible to stop a compaction type (e.g. COMPACTION, CLEANUP), but we
still don't support compaction stop by ID, which would be a nice add. We
don't even assign a ID to a compaction yet.

**Comment by raphaelsc** [comment]
recent work of mine introduced support to stop all compaction types, but i'll leave this issue opened until we add ability to stop a given compaction job from its uuid.

**Comment by tzach** [comment]
@raphaelsc can we close this?

**Comment by tzach** [comment]
@raphaelsc can we close this?

**Comment by raphaelsc** [comment]
> @raphaelsc can we close this?

we don't support stop compaction by id yet. it might be interesting in the field

**Comment by tzach** [comment]
Let's close this issue; it is 95% done.
If there is ever a request to stop compaction by ID, we will open a dedicated issue.
