### ISSUE TITLE
[coredump] event occurred during disrupt_nodetool_enospc (no space condition)

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylladb#21944]
## Packages

Scylla version: `6.3.0~dev-20241213.b4b7617554bd` with build-id `841b805c8c0cd46714ba20a46dc23e26bdd9b069`

Kernel Version: `6.8.0-1020-aws`

## Issue description

- New issue

Coredump event occurred within disrupt_nodetool_enospc nemesis (which simulates no space conditions on device)
```
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3  !WARNING | systemd[1]: scylla-server.service: State 'stop-sigterm' timed out. Killing.
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3   !NOTICE | systemd[1]: scylla-server.service: Killing process 24186 (scylla) with signal SIGABRT.
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]: Aborting on shard 0, in scheduling group main.
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]: Backtrace:
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5e31854
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5dec79b
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5e243c8
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   /opt/scylladb/libreloc/libc.so.6+0x40cff
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   /opt/scylladb/libreloc/libc.so.6+0x1193dc
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5e54080
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5e4b87f
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5e4bffc
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5e01bcc
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5e00cb8
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5d8e833
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x5d8db93
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x1405c27
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x1407ab0
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x1403763
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   /opt/scylladb/libreloc/libc.so.6+0x2a087
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   /opt/scylladb/libreloc/libc.so.6+0x2a14a
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:   0x1401714
2024-12-15T03:15:10.734+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | systemd[1]: Created slice system-systemd\x2dcoredump.slice - Slice /system/systemd-coredump.
```
here is the decoded backtrace:
```
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]: Backtrace:
2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]:
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:69
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:805
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:850
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3995
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3972
 (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3967
/data/scylla-s3-reloc.cache/by-build-id/841b805c8c0cd46714ba20a46dc23e26bdd9b069/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=77c77fee058b19c6f001cf2cb0371ce3b8341211, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
syscall at ??:?
seastar::internal::io_pgetevents(unsigned long, long, long, seastar::internal::linux_abi::io_event*, timespec const*, __sigset_t const*, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/linux-aio.cc:162
seastar::reactor_backend_aio::await_events(int, __sigset_t const*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor_backend.cc:496
seastar::reactor_backend_aio::wait_and_process_events(__sigset_t const*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor_backend.cc:567
seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3330
seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3136
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:276
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
scylla_main(int, char**) at ././main.cc:778
std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
main at ././main.cc:2391
__libc_start_call_main at ??:?
__libc_start_main_alias_2 at :?
_start at ??:?
```

## Impact

Core dump event, scylla crashed 

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-2143f167-7 (34.245.41.37 | 10.4.11.16) (shards: 14)
- longevity-50gb-12h-master-db-node-2143f167-6 (18.203.186.54 | 10.4.8.147) (shards: 10)
- longevity-50gb-12h-master-db-node-2143f167-5 (34.255.117.47 | 10.4.11.11) (shards: 11)
- longevity-50gb-12h-master-db-node-2143f167-4 (54.170.35.13 | 10.4.8.99) (shards: 14)
- longevity-50gb-12h-master-db-node-2143f167-3 (54.246.138.137 | 10.4.9.254) (shards: 8)
- longevity-50gb-12h-master-db-node-2143f167-2 (3.249.88.145 | 10.4.9.238) (shards: 12)
- longevity-50gb-12h-master-db-node-2143f167-1 (52.214.54.142 | 10.4.9.146) (shards: 8)

OS / Image: `ami-0adc25f7488142655` (aws: undefined_region)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `2143f167-0e2d-45f8-8958-d1b0026d6456`
Test name: `scylla-master/tier1/longevity-150gb-asymmetric-cluster-12h-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/341a94643b85609ab302ccd44f74b8b1072a0258/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 2143f167-0e2d-45f8-8958-d1b0026d6456`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=2143f167-0e2d-45f8-8958-d1b0026d6456)
- Show all stored logs command: `$ hydra investigate show-logs 2143f167-0e2d-45f8-8958-d1b0026d6456`

## Logs:
- **longevity-50gb-12h-master-db-node-2143f167-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241214_040659/longevity-50gb-12h-master-db-node-2143f167-5-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241214_040659/longevity-50gb-12h-master-db-node-2143f167-5-2143f167.tar.gz)
- **longevity-50gb-12h-master-db-node-2143f167-6** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241214_040659/longevity-50gb-12h-master-db-node-2143f167-6-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241214_040659/longevity-50gb-12h-master-db-node-2143f167-6-2143f167.tar.gz)
- **longevity-50gb-12h-master-db-node-2143f167-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241214_040659/longevity-50gb-12h-master-db-node-2143f167-2-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241214_040659/longevity-50gb-12h-master-db-node-2143f167-2-2143f167.tar.gz)
- **core.scylla-longevity-50gb-12h-master-db-node-2143f167-3-2024-12-15_03-57-58.gz** - [https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.848e8988986c4962803336ca8a97828d.24186.1734232510000000./core.scylla.106.848e8988986c4962803336ca8a97828d.24186.1734232510000000.zst](https://storage.cloud.google.com/upload.scylladb.com/core.scylla.106.848e8988986c4962803336ca8a97828d.24186.1734232510000000./core.scylla.106.848e8988986c4962803336ca8a97828d.24186.1734232510000000.zst)
- **db-cluster-2143f167.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/db-cluster-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/db-cluster-2143f167.tar.gz)
- **sct-runner-events-2143f167.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/sct-runner-events-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/sct-runner-events-2143f167.tar.gz)
- **sct-2143f167.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/sct-2143f167.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/sct-2143f167.log.tar.gz)
- **loader-set-2143f167.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/loader-set-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/loader-set-2143f167.tar.gz)
- **monitor-set-2143f167.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/monitor-set-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/monitor-set-2143f167.tar.gz)
- **ssl-conf-2143f167.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/ssl-conf-2143f167.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/2143f167-0e2d-45f8-8958-d1b0026d6456/20241215_043117/ssl-conf-2143f167.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-150gb-asymmetric-cluster-12h-test/50/)
[Argus](https://argus.scylladb.com/test/7f604213-5cad-4418-921e-1ca98918071c/runs?additionalRuns[]=2143f167-0e2d-45f8-8958-d1b0026d6456)
</details>

**Comment by mykaul** [comment]
> 2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3  !WARNING | systemd[1]: scylla-server.service: State 'stop-sigterm' timed out. Killing.
> 2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3   !NOTICE | systemd[1]: scylla-server.service: Killing process 24186 (scylla) with signal SIGABRT.
> 2024-12-15T03:15:10.733+00:00 longevity-50gb-12h-master-db-node-2143f167-3     !INFO | scylla[24186]: Aborting on shard 0, in scheduling group main.

@timtimb0t - do note that it coredumped because it timed out - it did not complete shutdown within the required 15 minutes. Compare the lines before to a regular normal shutdown and lets see where it got stuck please.

**Comment by mykaul** [comment]
As suspected, the infamous mapreduce getting stuck:
```
Dec 15 03:00:14.570857 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 6:main] storage_service - Stopped node_ops_abort_thread
Dec 15 03:00:14.570866 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 4:main] storage_service - Stopped node_ops_abort_thread
Dec 15 03:00:14.570897 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down storage_service was successful
Dec 15 03:00:14.570901 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down topology_state_machine
Dec 15 03:00:14.571030 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down topology_state_machine was successful
Dec 15 03:00:14.571033 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down Raft
Dec 15 03:00:14.571102 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down Raft was successful
Dec 15 03:00:14.571105 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down migration manager
Dec 15 03:00:14.571124 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down migration manager was successful
Dec 15 03:00:14.571128 longevity-50gb-12h-master-db-node-2143f167-3 scylla[24186]:  [shard 0:main] init - Shutting down mapreduce service
Dec 15 03:15:10.233252 longevity-50gb-12h-master-db-node-2143f167-3 systemd[1]: scylla-server.service: State 'stop-sigterm' timed out. Killing.

```

We have a bug about it somewhere. CC @piodul

**Comment by timtimb0t** [comment]
@mykaul , this error happened while test was trying to restart scylla-server after it deleted all the dummy data that been written on disc. So the sequence is: write dummy data -> sleep before releasing space -> releasing space -> attempt to restart scylla server which caused core dump event

**Comment by mykaul** [comment]
> [@mykaul](https://github.com/mykaul) , this error happened while test was trying to restart scylla-server after it deleted all the dummy data that been written on disc. So the sequence is: write dummy data -> sleep before releasing space -> releasing space -> attempt to restart scylla server which caused core dump event

But this not a Scylla coredump event - it's an external coredump after Scylla did not shutdown after 15 minutes. We've seen it before. And as you can see from the snippet above - it's because mapreduce doesn't shutdown cleanly.

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylladb/issues/21568 most likely.

**Comment by timtimb0t** [comment]
Okay, I see, I thought such event related to lack of disk space
