### ISSUE TITLE
Scylla got into startup by SIGILL

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylladb#21954]
Here we compiled an arm version , then start it up in an arm environment, got SIGILL 
command
```
docker run --name scylla -d -p 8000:8000 xxx/scylla:5.2.18-2-arm64 --alternator-port=8000
```

cpu
```
# lscpu
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 112
  On-line CPU(s) list:  0-111
Vendor ID:              ARM
  BIOS Vendor ID:       SANECHIPS
  BIOS Model name:      ZXIC(R) ZhuFengXin 8155 Processor
  Model:                1
  Thread(s) per core:   1
  Core(s) per socket:   112
  Socket(s):            1
  Stepping:             r0p1
  Frequency boost:      disabled
  CPU max MHz:          2800.0000
  CPU min MHz:          800.0000
  BogoMIPS:             250.00
  Flags:                fp asimd evtstrm crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop asimddp sve asimdfhm dit uscat il
                        rcpc flagm ssbs sb paca pacg dcpodp sve2 svebitperm flagm2 frint svei8mm svebf16 i8mm bf16 dgh
```

error info

```
2024-12-16 20:25:44,064 INFO spawned: 'scylla' with pid 755
Scylla version 5.2.18-2.20240622.15eba729be07 with build-id 22a512be307d875f3913129d516daf521d382146 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --alternator-address 172.17.0.2 --alternator-port 8000 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, alternator-address: 172.17.0.2, alternator-port: 8000, blocked-reactor-notify-ms, (positional) 999999999]
2024-12-16 20:25:45,173 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-16 20:25:52,732 INFO exited: scylla (terminated by SIGILL; not expected)
2024-12-16 20:25:53,734 INFO spawned: 'scylla' with pid 986
Scylla version 5.2.18-2.20240622.15eba729be07 with build-id 22a512be307d875f3913129d516daf521d382146 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --alternator-address 172.17.0.2 --alternator-port 8000 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, alternator-address: 172.17.0.2, alternator-port: 8000, blocked-reactor-notify-ms, (positional) 999999999]
2024-12-16 20:25:54,845 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-16 20:26:02,614 INFO exited: scylla (terminated by SIGILL; not expected)
2024-12-16 20:26:03,616 INFO spawned: 'scylla' with pid 1217
Scylla version 5.2.18-2.20240622.15eba729be07 with build-id 22a512be307d875f3913129d516daf521d382146 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --alternator-address 172.17.0.2 --alternator-port 8000 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, alternator-address: 172.17.0.2, alternator-port: 8000, blocked-reactor-notify-ms, (positional) 999999999]
2024-12-16 20:26:04,800 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-12-16 20:26:12,319 INFO exited: scylla (terminated by SIGILL; not expected)
2024-12-16 20:26:13,321 INFO spawned: 'scylla' with pid 1448
```

**Comment by qiuqiu-007** [comment]
And I see this https://github.com/scylladb/scylladb/issues/4921, does it the same problem ?

**Comment by michoecho** [comment]
Scylla ARM releases are compiled with `-march=armv8-a+crc+crypto` by default, see https://github.com/scylladb/scylladb/blob/d0cda8ebefef0805eca5e7d107fac0eda1561254/configure.py#L211. You should be able to use the `--target=...` option of `configure.py` to choose a different value for `-march`.

**Comment by mykaul** [comment]
(note that the optimized clang, if used, also may need to be adjusted - see https://github.com/scylladb/scylladb/blob/d0cda8ebefef0805eca5e7d107fac0eda1561254/tools/toolchain/optimized_clang.sh#L47C28-L47C48 )

**Comment by michoecho** [comment]
> (note that the optimized clang, if used, also may need to be adjusted - see https://github.com/scylladb/scylladb/blob/d0cda8ebefef0805eca5e7d107fac0eda1561254/tools/toolchain/optimized_clang.sh#L47C28-L47C48 )

The report says "we compiled an arm version", so their compiler doesn't have to be adjusted.

**Comment by qiuqiu-007** [comment]
> Scylla ARM releases are compiled with `-march=armv8-a+crc+crypto` by default, see
> 
> [scylladb/configure.py](https://github.com/scylladb/scylladb/blob/d0cda8ebefef0805eca5e7d107fac0eda1561254/configure.py#L211)
> 
> Line 211 in [d0cda8e](/scylladb/scylladb/commit/d0cda8ebefef0805eca5e7d107fac0eda1561254)
> 
>  return 'armv8-a+crc+crypto' 
> . You should be able to use the `--target=...` option of `configure.py` to choose a different value for `-march`.

I didn't catch u. Does it mean that I should specify the `--target` value

**Comment by michoecho** [comment]
> > Scylla ARM releases are compiled with `-march=armv8-a+crc+crypto` by default, see
> > [scylladb/configure.py](https://github.com/scylladb/scylladb/blob/d0cda8ebefef0805eca5e7d107fac0eda1561254/configure.py#L211)
> > Line 211 in [d0cda8e](/scylladb/scylladb/commit/d0cda8ebefef0805eca5e7d107fac0eda1561254)
> > return 'armv8-a+crc+crypto'
> > . You should be able to use the `--target=...` option of `configure.py` to choose a different value for `-march`.
> 
> I didn't catch u. Does it mean that I should specify the `--target` value

Yes. `--target` specifies the value of `-march=...` passed to the C++ compiler.

SIGILL means that your CPU doesn't support some CPU instructions which were compiled into Scylla. By default, Scylla is built for the `armv8-a+crc+crypto` instruction set. You have to choose an instruction set which works on your CPU.

If you configured Scylla with `./configure.py ...`, you can change the instruction set by configuring `./configure.py --target=XXX ...` instead, where XXX is something supported by CPU.

If you are compiling Scylla on the same CPU that you later use for running it, you can try `./configure.py --target=native ...`. Otherwise, you have to learn on your own what `-march=...` is appropriate for your CPU. ZhuFengXin 8155 doesn't even show up in google, so I won't help you with that.

**Comment by avikivity** [comment]
ScyllaDB likely won't build without the crc extension.


```c++
#elif defined(__aarch64__)
#include <arm_acle.h>
/* Implement x86-64 intrinsics with according aarch64 ones */
inline uint32_t _mm_crc32_u8(uint32_t crc, uint8_t in)
{
    return __crc32cb(crc, in);
}
inline uint32_t _mm_crc32_u16(uint32_t crc, uint16_t in)
{
    return __crc32ch(crc, in);
}
inline uint32_t _mm_crc32_u32(uint32_t crc, uint32_t in)
{
    return __crc32cw(crc, in);
}
inline uint32_t _mm_crc32_u64(uint32_t crc, uint64_t in)
{
    return __crc32cd(crc, in);
}
#else
```

**Comment by avikivity** [comment]
flags show crc32, so it's probably the crypto extension that's missing.
