### ISSUE TITLE
update_cluster_layout_tests.TestUpdateClusterLayout.test_simple_removenode_4 is flacky

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#21966]
Seen here: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13905/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4/

Node2 fails during restart because becoming a voter fails with ` raft::commit_status_unknown (Commit status of the entry is unknown)`. It fails because at the time the node tried to execute the operation it does not see the leader as alive yet and the operation (that happens in `raft_group0::finish_setup_after_join`) is not retried. This is a timing issue. We need to retry the operation for recoverable errors  like unknown status.

**Comment by mykaul** [comment]
Isn't this a dup of https://github.com/scylladb/scylladb/issues/20814 ?
