### ISSUE TITLE
Add support for SASI

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#2203]
SSTable Attached Secondary Indexes (SASI) implements three types of indexes, PREFIX, CONTAINS, and SPARSE.

create table examples (from http://www.doanduyhai.com/blog/?p=2058#what_is_sasi)

```
// Full text search on albums title
CREATE CUSTOM INDEX albums_title_idx ON music.albums(title) 
USING 'org.apache.cassandra.index.sasi.SASIIndex'
WITH OPTIONS = {
    'mode': 'CONTAINS',
    'analyzer_class': 'org.apache.cassandra.index.sasi.analyzer.StandardAnalyzer',
    'tokenization_enable_stemming': 'true',
    'tokenization_locale': 'en',
    'tokenization_skip_stop_words': 'true',
    'analyzed': 'true',
    'tokenization_normalize_lowercase': 'true'
};
 
// Full text search on artist name with neither Tokenization nor case sensitivity
CREATE CUSTOM INDEX albums_artist_idx ON music.albums(artist) 
USING 'org.apache.cassandra.index.sasi.SASIIndex'
WITH OPTIONS = {
     'mode': 'PREFIX', 
     'analyzer_class': 'org.apache.cassandra.index.sasi.analyzer.NonTokenizingAnalyzer',
     'case_sensitive': 'false'
};
```
select examples

```
SELECT * FROM team WHERE name = 'TZACH';
SELECT * FROM team WHERE name LIKE 't%';
SELECT * FROM team WHERE name LIKE '%t%';
SELECT * FROM team WHERE name LIKE '%t%' ALLOW FILTERING;
SELECT * FROM team WHERE name LIKE '%T%';
```

**Comment by tzach** [comment]
related Apache C* tickets:
Add SASI https://issues.apache.org/jira/browse/CASSANDRA-10661
Enable SASI index for static columns https://issues.apache.org/jira/browse/CASSANDRA-11183

**Comment by geekfivestart** [comment]
As @micobarac , our team use the secondary index of C* , by integrating lucene, for full text search. We plan to migrate to ScyllaDB, however, the current global secondary index is based on MV,  and we expect the local secondary index supporting, as C* SASI.  I notice that the feature of local secondary index is not on the schedule. 
Will someone join us to develop this feature, or could someone  give advice for developing, since I am not familiar with codes of scylladb. @tzach @duarten @dorlaor

**Comment by dorlaor** [comment]
Recently we added local (regular) indexes but without any search
capabilities. SASI is very interesting but it's still not
on the near term roadmap (it is on the long term)

**Comment by hdost** [comment]
Is this actually likely to happen, my guess would be no.

**Comment by tzach** [comment]
@hdost we (ScyllaDB team) are not planning to work on this soon, mostly because of other more urgent features.
SASI does have a valid use case as an integration point, and we will appreciate PRs

**Comment by nyh** [comment]
> Tzach, I suggest we'll close it, we can always reopen if/when we have a concrete implementation schedule

I vote that we don't close this issue. This issue allows other users who might look for SASI in Scylla to find the issue, and see what we wrote here - i.e., that Scylla indeed doesn't have this feature, and that Tzach and Dor are saying that we're not planning to do it any time soon. This is useful information - I don't think it should be hidden in a closed issue.

**Comment by nyh** [comment]
Some translated Cassandra unit test that test the SASI feature:
* `cassandra_tests/validation/entities/secondary_index_test.py`::`testPrepareStatementsWithLIKEClauses`

Note that [the current Cassandra documentation](https://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html) calls SASI indexes "experimental and are not recommended for production use" and not enabled by default: A recent Cassandra user will need to enable the "enable_sasi_indexes" option to use them.

**Comment by PeterCorless** [comment]
@nyh : The link to here is broken: https://cassandra.apache.org/doc/latest/cassandra/configuration/cassandra_config_file.html

There is more to be found on this CEP page: 

https://cwiki.apache.org/confluence/display/CASSANDRA/CEP-7%3A+Storage+Attached+Index

**Comment by nyh** [comment]
As noted above, Scylla will most likely never implement SASI. Cassandra themselves downgraded their SASI feature Apache Cassandra 4.0  to "experimental" status - in https://www.youtube.com/watch?v=zmqIYg_duPM Benjamin Lerer explains that it didn't match the standard that they wanted to set for the future of Apache Cassandra. Instead, Cassandra 5.0 will have a different implementation with similar features, called SAI (Storage Attached Index), officially designed here: https://cwiki.apache.org/confluence/display/CASSANDRA/CEP-7%3A+Storage+Attached+Index. SASI will be deprecated in Cassandra 5.0 and removed entirely in Cassandra 6.0.

So if we want to add any Cassandra-compatible improved indexing, we should add SAI compatibility - not SASI.

**Comment by tzach** [comment]
Closing (see @nyh comment above).
