### ISSUE TITLE
Counters: Allow mixing counter and non counter columns

### ISSUE THREAD

**Issue by MarkReedZ** [scylladb/scylladb#2433]
Cassandra has an open issue to support mixing counter and non counter columns at some point in 4.  Posting here for visibility as it seems from their discussion they didn't have to keep them separate.   

https://issues.apache.org/jira/browse/CASSANDRA-9810

**Comment by slivne** [comment]
please note its not yet in cassandra 4

**Comment by dnrusakov** [comment]
\+1

**Comment by nyh** [comment]
Note that although this feature was originally planned for Cassandra 4, it didn't happen, and the issue was never fixed there (their issue hasn't been touched in six years, like this issue).

**Comment by kostja** [comment]
Per @nyh comment - not planned.

**Comment by nyh** [comment]
I agree we'll most likely never do this feature, but personally, I would keep such issues which describe a real problem and give useful links - open. I don't think we should even have a "not planned" status.
