### ISSUE TITLE
Support for SELECT column['key'] 

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylladb#2448]
Currently we can 

```
UPDATE tab SET col['key'] = ...
DELETE col['key'] FROM tab
```

but we can't 

```
SELECT col['key'] FROM tab
```

for `map<keytype,valtype>` data type,

**Comment by slivne** [comment]
I tried the following on cassandra 2.2 / 3.0 - its not possible in cassandra CQL as well.

It may be supported by upstream cassandra toward 4.0 https://issues.apache.org/jira/browse/CASSANDRA-7396

```
create KEYSPACE ks with replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
use ks;
create TABLE tb ( key text primary key, value map<text,text> );
insert into tb (key, value) values ('0',{'0': '0', '1' :'1'});
select value['0'] from tb where key='0';
```

**Comment by avikivity** [comment]
Still unsupported.

**Comment by nyh** [comment]
Three years later, I opened https://github.com/scylladb/scylladb/issues/7751 that is a duplicate of this one, but the newer issue is more complete, has a list of reproducing tests and also user's requests, so I'm closing this one as a duplicate.
