### ISSUE TITLE
Skip adding view updates to the commit log

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#2539]
*Installation details*
Scylla version (or git commit hash): 2.0

There will be a mechanism ensuring view updates will eventually reach the view replica, so we can skip writing it to that replica's commitlog.

**Comment by slivne** [comment]
not clear why we should have this optimization

flushing of commitlog is done on size/time based
flushing of memtables is triggered on memory pressure

if we do not write to the commitlog then we rely on a synch mechanism from base - replica that we will have in the future - but even at that point - having local commitlog may replay a lot of replica updates if a node crashed before the memtables have been flushed.

**Comment by duarten** [comment]
This optimization was more important in the context of synchronous updates.

It might still be desirable as it will a) speed up writes to the view replica, b) decrease write amplification.

There are lots of clusters that run without a commitlog, using replication as fault tolerance. Since view rows can be recovered from the base table, this might still be a valid optimization. I think we should leave this open until the whole MV code and approach solidify.

**Comment by nyh** [comment]
Removed "n00b" label and added "enhancement" one instead. This is an optimization with some argument whether it is a good idea or not. We definitely don't want a new developer to blindly take this idea and implement it, without discussing first whether we actually want to do it.

**Comment by kostja** [comment]
This can't work, for reasons outlined by @slivne. Every node should be fully recoverable from its commit log.
