### ISSUE TITLE
Scylla installation failed - no disks used

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylladb#2655]
Scylla version (or git commit hash): ScyllaDB 1.7.4 
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-78c5df01

Region - Oregon (us-west-2)
Installation succeeded on version 1.6.3 and 1.6.5

Setup was with 1 disk

Installation failed, error message:

```
Aug 01 08:13:52 ip-172-31-11-15 scylla_ami_setup[732]: Traceback (most recent call last):
Aug 01 08:13:52 ip-172-31-11-15 scylla_ami_setup[732]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 162, in <module>
Aug 01 08:13:52 ip-172-31-11-15 scylla_ami_setup[732]: get_disk_bundles()
Aug 01 08:13:52 ip-172-31-11-15 scylla_ami_setup[732]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 139, in get_disk_bundles
Aug 01 08:13:52 ip-172-31-11-15 scylla_ami_setup[732]: raise Exception("No disks found")
Aug 01 08:13:52 ip-172-31-11-15 scylla_ami_setup[732]: Exception: No disks found
Aug 01 08:13:52 ip-172-31-11-15 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Aug 01 08:13:52 ip-172-31-11-15 systemd[1]: Failed to start Scylla AMI Setup.
Aug 01 08:13:52 ip-172-31-11-15 systemd[1]: Unit scylla-ami-setup.service entered failed state.
Aug 01 08:13:52 ip-172-31-11-15 systemd[1]: scylla-ami-setup.service failed.
[centos@ip-172-31-11-15 ~]$ sudo systemctl status scylla-ami-setup
```

**Comment by nirmaayan** [comment]
Exception: No disks found error message need to be **highlighted**

**Comment by tzach** [comment]
@nirmaayan what instance type?

> OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-78c5df01

is it Scylla AMI or different? (if the second, which OS?)

> Setup was with 1 disk

did you run scylla_setup? if so please paste the full execution

**Comment by nirmaayan** [comment]
@tzach tested with m3.medium and 2x.large
It was our AMI
The difference between 1.6.x and 1.7.x is:
1.6.x:
Step 4: Add Storage - it was OK to remove all the HD except 1 (see picture)

![fireshot capture 4 - ec2 management console_ - https___console aws amazon com_ec2_v2_home](https://user-images.githubusercontent.com/18263247/28860704-4cc82b30-7766-11e7-9cc2-953920f967b5.png)

 1.7.x

![1 7 x](https://user-images.githubusercontent.com/18263247/28861659-8041cd28-776a-11e7-858c-9fc6d6938ef6.png)

**Comment by tzach** [comment]
@nirmaayan why are you running scylla_setup on the AMI?
please paste `df -k` and `lsblk` before and after setup

**Comment by nirmaayan** [comment]
I didn't run scylla_setup
I only used the AWS GUI for the installation

**Comment by tzach** [comment]
Scylla AMI assumes the original disk is attached. It will not work with a 10GB root device only.
We need to clarify in the [AWS instructions](http://www.scylladb.com/download/amazon/)

**Comment by nirmaayan** [comment]
It worked in 1.6.x

**Comment by syuu1228** [comment]
Duplicated with #2540, and fix is already on the ML.

**Comment by syuu1228** [comment]
Please close this issue, since it fixed at https://github.com/scylladb/scylla-ami/commit/5c19d4e7cd8587fc65d458c92a78ef16143c2ca8

**Comment by syuu1228** [comment]
ping, please close this

**Comment by syuu1228** [comment]
This is fixed at https://github.com/scylladb/scylla-ami/commit/5c19d4e7cd8587fc65d458c92a78ef16143c2ca8, closing.
