### ISSUE TITLE
Migrate to the CMake build system

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#2717]
CMake is the de-facto standard (or as close as it gets to standard) build system for C++ projects. @hakuch  wrote up a good list of benefits on the equivalent seastar [issue](https://github.com/scylladb/seastar/issues/313) so I'm not going to repeat them here.

Switching build-systems is no simple task. There is always that one dude who uses it in ways that you would never imagine and hence didn't port the feature to the new build system. To avoid such problems I plan to roll this out in multiple stages, gradually achieving feature parity and maturity, and leaving the current build-system in place until everybody is happy with the new one.

Roadmap:
- [ ] Build scylla in release/debug mode
- [ ] Build the unit test suite
- [ ] Feature parity w.r.t. configuration options
- [ ] Proper dependency detection (don't just rely on everything being in /usr/include)

**Comment by avikivity** [comment]
There are some features missing from the current build system, so let's be sure they won't be missing:
 - archive support - currently tests link with everything in the code. If we had archives (`.a` files) then we could link with the archive and get faster links with smaller products
 - thin archives - a feature of `ld` that doesn't copy the object file into the archive
 - multiple archives - say one per module
 - C++2a module support

I imagine CMake supports the first three at least and support will come in time for the fourth, but let's verify it beforehand.

**Comment by hakuch** [comment]
For reference, I've started a [discussion](https://groups.google.com/d/msg/seastar-dev/D4j1cm3xBeU/X8LWPA83AAAJ) about preliminary CMake support for Seastar.

**Comment by denesb** [comment]
As discussed in the first RFC's [email thread](https://groups.google.com/d/topic/scylladb-dev/-70FAiai9iA/discussion) configure.py will be changed so that it invokes CMake (both with release and debug build types), translating it's own flag to something equivalent that CMake understands.

**Comment by tchaikov** [comment]
```
[2024-03-18T12:44:29.480Z] [2562/3353] Generating ../Dev/iotune
[2024-03-18T12:44:29.480Z] FAILED: Dev/iotune /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/iotune 
[2024-03-18T12:44:29.480Z] cd /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dist && /usr/bin/cmake -E copy /jenkins/workspace/scylla-master/scylla-ci/scylla/build/seastar/apps/iotune/Dev/iotune /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/iotune
[2024-03-18T12:44:29.480Z] Error copying file "/jenkins/workspace/scylla-master/scylla-ci/scylla/build/seastar/apps/iotune/Dev/iotune" to "/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/iotune".
```

cmake is not able to build iotune for Dev configuration when `ninja -C build` in the `scylla-ci` pipeline.

**Comment by tchaikov** [comment]
```
07:43:41  [3295/4112] Generating ../Dev/iotune.debug, ../Dev/iotune.stripped
07:43:41  /usr/bin/gdb.minimal
07:43:41  Error while writing index for `/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/iotune.stripped': No debugging symbols
07:43:41  gdb-add-index: No index was created for /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/iotune.stripped
07:43:41  gdb-add-index: [Was there no debuginfo? Was there already an index?]
```

```
08:02:46  Get basename for unified-package - command output: scylla-unified-6.1.0~dev-0.20240613.d5bdddaeb40b.x86_64.tar.gz
08:02:46  [Pipeline] echo
08:02:46  Get basename for unstripped-package - command: basename $(ls /jenkins/workspace/scylla-master/scylla-ci/scylla/build/RelWithDebInfo/dist/tar/scylla-unstripped-6.1.0~dev-0.20240613.d5bdddaeb40b.x86_64.tar.gz)
08:02:46  [Pipeline] sh
08:02:47  ++ ls /jenkins/workspace/scylla-master/scylla-ci/scylla/build/RelWithDebInfo/dist/tar/scylla-unstripped-6.1.0~dev-0.20240613.d5bdddaeb40b.x86_64.tar.gz
08:02:47  ls: cannot access '/jenkins/workspace/scylla-master/scylla-ci/scylla/build/RelWithDebInfo/dist/tar/scylla-unstripped-6.1.0~dev-0.20240613.d5bdddaeb40b.x86_64.tar.gz': No such file or directory
08:02:47  + basename
08:02:47  basename: missing operand
08:02:47  Try 'basename --help' for more information.
08:02:48  [Pipeline] withCredentials
08:02:48  Masking supported pattern matches of $GITHUB_TOKEN
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9683/consoleFull

**Comment by tchaikov** [comment]
```
boost.sstable_3_x_test.test_uncompressed_collections_read 
...
[Exception] - no_such_class: unable to find class 'org.apache.cassandra.io.compress.ZstdCompressor'
 == [File] - seastar/src/testing/seastar_test.cc
 == [Line] - 43
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9893/testReport/boost/sstable_3_x_test/test_uncompressed_collections_read/


the reason why these tests failed was that i was experimenting the build with CMake. and with the rules generated by CMake, linker removes the unreferenced symbols when linking against libscylla-main.a.

**Comment by tchaikov** [comment]
```
08:48:14  [3325/4124] Generating ../Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240629.60955ead75ef.noarch.tar.gz
08:48:14  FAILED: Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240629.60955ead75ef.noarch.tar.gz /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240629.60955ead75ef.noarch.tar.gz 
08:48:14  cd /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dist && /usr/bin/cmake -E copy /jenkins/workspace/scylla-master/scylla-ci/scylla/tools/cqlsh/build/scylla-cqlsh-6.1.0~dev-0.20240629.60955ead75ef.noarch.tar.gz /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240629.60955ead75ef.noarch.tar.gz
08:48:14  Error copying file "/jenkins/workspace/scylla-master/scylla-ci/scylla/tools/cqlsh/build/scylla-cqlsh-6.1.0~dev-0.20240629.60955ead75ef.noarch.tar.gz" to "/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240629.60955ead75ef.noarch.tar.gz".

```

**Comment by tchaikov** [comment]
```
17:11:11  [3321/4124] Generating ../Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz[K
17:11:11  [3322/4124] Generating ../Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz[K
17:11:11  [31mFAILED: [0mDebug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz 
17:11:11  cd /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dist && /usr/bin/cmake -E copy /jenkins/workspace/scylla-master/scylla-ci/scylla/tools/cqlsh/build/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz
17:11:11  Error copying file "/jenkins/workspace/scylla-master/scylla-ci/scylla/tools/cqlsh/build/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz" to "/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240701.bb82a1018a98.noarch.tar.gz".
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10109/consoleFull

**Comment by tchaikov** [comment]
```
20:39:41  [4096/4124] Generating ../Dev/dist/tar/scylla-unified-6.1.0~dev-0.20240712.f159abfda486.x86_64.tar.gz[K
20:39:41  [31mFAILED: [0mDev/dist/tar/scylla-unified-6.1.0~dev-0.20240712.f159abfda486.x86_64.tar.gz /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/dist/tar/scylla-unified-6.1.0~dev-0.20240712.f159abfda486.x86_64.tar.gz 
20:39:41  cd /jenkins/workspace/scylla-master/scylla-ci/scylla && /jenkins/workspace/scylla-master/scylla-ci/scylla/unified/build_unified.sh --build-dir /jenkins/workspace/scylla-master/scylla-ci/scylla/build --pkgs "/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/dist/tar/scylla-6.1.0~dev-0.20240712.f159abfda486.x86_64.tar.gz;/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/dist/tar/scylla-cqlsh-6.1.0~dev-0.20240712.f159abfda486.x86_64.tar.gz;/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/dist/tar/scylla-tools-6.1.0~dev-0.20240712.f159abfda486.noarch.tar.gz;/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/dist/tar/scylla-jmx-6.1.0~dev-0.20240712.f159abfda486.noarch.tar.gz;/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/dist/tar/scylla-python3-6.1.0~dev-0.20240712.f159abfda486.x86_64.tar.gz" --unified-pkg "/jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/dist/tar/scylla-unified-6.1.0~dev-0.20240712.f159abfda486.x86_64.tar.gz"
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/iotune: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/patchelf: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/lscpu: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/gawk: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/gzip: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/ifconfig: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/ethtool: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/netstat: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/libexec/hwloc-distrib: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
...
20:39:41  tar: scylla/node_exporter/NOTICE: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/ubsan-suppressions.supp: Cannot open: No such file or directory
20:39:41  tar: scylla: Cannot mkdir: No such file or directory
20:39:41  tar: scylla/fix_system_distributed_tables.py: Cannot open: No such file or directory
20:39:41  tar: Exiting with failure status due to previous errors
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10370/consoleFull

**Comment by tchaikov** [comment]
with `--use-cmake`, seastar is always built as static library. this behavior is not consistent with the existing settings. to fix the discrepency, we need to build seastar as a shared library for Debug and Dev builds. but it turns out difficult to implement this with CMake -- we need to set `BUILD_SHARED_LIBS` only when building Debug and Dev configurations, but this variable is a "configure"-time setting. there are three approaches

- build seastar as an external project. but we'd consume its public interfaces by repeating them in the parent project
- build seastar in `configure.py`. but it'd difficult to integrate its build with the parent project.
- explicitly define the `Seastar_BUILD_SHARED_LIBS` in Seastar, and add an interface library with different `LOCATION_<CONFIG>`.

**Comment by denesb** [comment]
@tchaikov can we add an option to seastar's CMake to build both static and shared libraries? Then ScyllaDB (and other downstream projects) could consume the one they need/want.

**Comment by tchaikov** [comment]
@denesb thank you for the pointers. this is exactly how SDL2 addresses this problem. see https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt . SDL2 provides options to allow users to separately enable/disable the build of shared / static libraries. see https://github.com/libsdl-org/SDL/blob/df501040fd646a1f4eab92aa5b698b35a36013ed/CMakeLists.txt#L359-L360 .

i think i will follow your suggestion and SDL2's approach

1. add `Seastar_BUILD_STATIC_LIBS` and `Seastar_BUILD_SHARED_LIBS` options, and if neither of they is set, `BUILD_SHARED_LIBS` is respected. otherwise, Seastar will be build as static libraries and / or static libraries as configured
2. Seastar will use different target names for shared and static libraries, and `Seastar::seastar` and friends will be the aliases of the shared libraries if available, and fall back to the static libraries. or they could be interface libraries with different `LOCATION_<CONFIG>`s. 
3. seastar's tests, demos and applications will link against `Seastar::seastar`. (this is the existing behavior)
4. in Scylla, we enable both of these options. as we *cannot* conditionally pick one of them using generator expression when including Seastar.
5. in Scylla, we define an interface library which conditionally link to shared / static libraries depending on the CONFIG using the generator expression.
