### ISSUE TITLE
Scylla AMI - "sudo poweroff"

### ISSUE THREAD

**Issue by noamha** [scylladb/scylladb#2758]
*Installation details*
Scylla version (or git commit hash): 2.0.rc3-0.20170828.c57cc55.el7.centos
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-084a7873 (North Viriginia)

When you work with our AMI one can accidentally run our last history command which is "sudo poweroff", it happened to me when I ran a command and tried to run it again by clicking the upper arrow and accidentally shut down down the machine.

It's not a big thing, but I think we should probably clear the history and shut down the machine from AWS is possible.

**Comment by tzach** [comment]
Its also good security practice to remove the history from the AMI

**Comment by nyh** [comment]
If this issue is still relevant, I think it should be moved to https://github.com/scylladb/scylla-machine-image/issues and removed from here, no?
