### ISSUE TITLE
Join up reader params into a "mega-param"

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#2764]
Currently we have about 7 parameters (partition_range, partition_slice, io_priority_class, trace_state, fwd flags, etc.) that we pass down through countless layers for readers. This makes code hard to read and write. We should join them up into a struct and pass around that instead.
The challenge is that not all related functions take exactly the same combinations of these "cookies".

**Comment by avikivity** [comment]
Adding a new one: seastar::scheduling_group

**Comment by denesb** [comment]
Also adding a new one: reader_resource_tracker :)

**Comment by avikivity** [comment]
io_priority_class, scheduling_group, and reader_resource_tracker are all about resource control. Maybe we ought to merge them. Since the first two are from seastar, they will need to become an extensible mechanism (maybe resource_group).

**Comment by avikivity** [comment]
We can also merge partition_range and partition_slice into a read_range (or something). The fwd flags should just die.

**Comment by geokollias** [comment]
@avikivity I'm not sure what

> Since the first two are from seastar, they will need to become an extensible mechanism (maybe resource_group).

means. Are there any "extensible mechanism" examples in the code?

**Comment by denesb** [comment]
Closing this, see https://github.com/scylladb/scylladb/pull/21988#issuecomment-2556773108 for justification.
