### ISSUE TITLE
Make scylla_setup non interactive mode errors more descriptive

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#2772]
*Installation details*
Scylla version (or git commit hash): 1.7.4

Currently, every error print the same usage message, which makes it hard to understand where the problem is.
For example `--setup-nic` is mandatory in non-interactive mode, but the error code return by
```
if [ $INTERACTIVE -eq 0 ] && [ $SYSCONFIG_SETUP -eq 1 ] && [ "$NIC" = "" ]; then
    print_usage
fi
```
does not let you know that.
It would be much better if each test will point the user to the specific error

**Comment by syuu1228** [comment]
Closing, since we have better setup scripts now.
