### ISSUE TITLE
Print all Scylla init errors to the terminal

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#2799]
*Installation details*
Scylla version (or git commit hash): 2.0

When a Scylla process fails early, for any reason, it will be useful to print the error to the terminal.
For example, no enough memory per shared error (below) can be immediately reported.

```
  [shard 0] init - Only 476 MiB per shard; this is below the recommended minimum of 1 GiB/shard; terminating.Configure more memory (--memory option) or decrease shard count (--
smp option).
```

**Comment by amnonh** [comment]
This would work only in cases that a user actually run the application by himself, it's not relevant when running it as a service or when running an image.

In AWS we run nodetool command first thing when we enter scylla, how about we add an option for nodetool, that when it fails to connect to scylla, it would search for a cause.

There could be multiple ways of going around that, but we can even have scylla write something to file when it fails to start and exit

**Comment by tzach** [comment]
> This would work only in cases that a user actually run the application by himself, it's not relevant when running it as a service or when running an image.

This enhancement is specifically **for** running Scylla as a service. Scylla service already print our errors for init issues; I'm suggesting to include even more.

You are right about the AMI, this feature will not help there.

**Comment by tzach** [comment]
Need to exit with 1 in this case like Scylla does here:
https://github.com/scylladb/scylla/commit/587d375e19cf3dc671455121ba0a7074e9eb94cf

**Comment by syuu1228** [comment]
@tzach Don't understand what is this issue about.
As @amnonh suggesting, when scylla started as a service under systemd, stdout/stderr will redirect to syslog (then redirect to journal), there is no way to print errors to your terminal.

**Comment by syuu1228** [comment]
Closing since it is outdated issue.
