### ISSUE TITLE
"Scylla unexpectedly exited. Do you want to report the issue?"

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#2801]
*Installation details*
Scylla version (or git commit hash): 2.0

When Scylla exit, or fail to start, it will be very useful to get the relevant logs. We can make it easier with a single command #2800, and even easier by initiating a request when Scylla fails to start.

```
> sudo systemctl start scylla-server
Error in starting Scylla"  [shard 0] init - Only 476 MiB per shard; this is below the recommended minimum of 1 GiB/shard; terminating.Configure more memory (--memory option) or decrease shard count (--
smp option).
> Do you want to report the issue [Yn]: Y
Report uploaded to http://upload.scylladb.com/0af4c623-3f30-47db-b9b2-6f49101f0906/
```

**Comment by avikivity** [comment]
`systemctl` is provided by the OS, not us.

We can provide a wrapper, but that will only add complexity, because real service management is done by systemd.

**Comment by slivne** [comment]
Alternatively we can have the following

```
sudo systemctl start scylla-server
Error in starting Scylla"  [shard 0] init - Only 476 MiB per shard; this is below the recommended minimum of 1 GiB/shard; terminating.Configure more memory (--memory option) or decrease shard count (--smp option). 
Scylla failed - to assist us to investigate the issue please run XXXX to report it.
```

@tzach ?

**Comment by tzach** [comment]
@slivne reasonable compromise
XXXX can be #2800

**Comment by tzach** [comment]
Closing no progress.
