### ISSUE TITLE
Report pending compactions metric on a per table basis

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#2892]
C* does it from 3.2 onwards and even updated 'nodetool compactionstats' to show the metric for each non system table. That's useful because we can't tell much from the aggregate value.

**Comment by raphaelsc** [comment]
C* issue for it: https://issues.apache.org/jira/browse/CASSANDRA-10718

**Comment by gnumoreno** [comment]
+1 Please see #2810

**Comment by raphaelsc** [comment]
That's already fixed. When running nodetool compactstats, we already have each active table feeding its pending tasks data.
