### ISSUE TITLE
Secondary index support for Thrift

### ISSUE THREAD

**Issue by penberg** [scylladb/scylladb#2964]

**Comment by nyh** [comment]
@penberg can you please say a few more words about what is missing? Is some sort of API missing (which)? Something wrong with SI or MV support for Thrift-created tables? Or what?

**Comment by nyh** [comment]
@penberg do you remember what this issue is about?
@tzach do we still officially support Thrift?

**Comment by tzach** [comment]
> @tzach do we still officially support Thrift?

Yes.

**Comment by nyh** [comment]
Thrift will probably be deprecated soon - see https://github.com/scylladb/scylladb/issues/3811. So if this issue was open for 5 years without anyone complaining, we'll probably never fix it.
We can keep the issue open until officially deprecating Thrift.

**Comment by tzach** [comment]
@nyh agree.  We can close this issue *now*.
