### ISSUE TITLE
Reproducible error with `LIST USERS` and non-superuser

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylladb#2970]
*Installation details*
Scylla version (or git commit hash): 2.0.0

Executing `LIST USERS` with a newly created non-superuser user results in a reproducible error.

## Steps to reproduce:

Start Scylla with the `PasswordAuthenticator` and the `DefaultAuthorizer`.

Login with with the default superuser, and observe that executing `LIST USERS` works as expected:

```
$ cqlsh -u cassandra -p cassandra
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> LIST USERS;

 name      | super
-----------+-------
 cassandra |  True

(1 rows)
```

Create a new non-superuser user (`joe`), and observe that `LIST USERS` still functions correctly:

```
cassandra@cqlsh> CREATE USER joe WITH PASSWORD 'joe';
cassandra@cqlsh> LIST USERS;

 name      | super
-----------+-------
 cassandra |  True
       joe | False

(2 rows)
```

Now, login as `joe` and observe the failure:

```
cassandra@cqlsh> LOGIN joe;
Password: 
joe@cqlsh> LIST USERS;

'Row' object has no attribute 'values'
```

Scylla's console output doesn't elaborate on any issue.

The problem persists even after logging in back to the superuser:

```
joe@cqlsh> LOGIN cassandra;
Password: 
cassandra@cqlsh> LIST USERS;

'Row' object has no attribute 'values'
```
Restarting the node and the `cqlsh` allows `LIST USERS` to function again as `cassandra`.

**Comment by ptrsmrn** [comment]
The `DefaultAuthorizer` mentioned in the issue's description does no longer exist. There are 3 authorizes available at the moment:
- AllowAllAuthorizer
- CassandraAuthorizer
- com.scylladb.auth.TransitionalAuthorizer

The issue does not reproduce for any of them (everything works). The steps to reproduce result in the same behaviour for each authorizer:
```
[piotrs@fedora scylladb]$ cqlsh -u cassandra -p cassandra
Connected to  at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cassandra@cqlsh> list users;

 name      | super
-----------+-------
 cassandra |  True

(1 rows)
cassandra@cqlsh> CREATE USER joe WITH PASSWORD 'joe';
cassandra@cqlsh> list users;

 name      | super
-----------+-------
 cassandra |  True
       joe | False

(2 rows)
cassandra@cqlsh> login joe;
Password: 
joe@cqlsh> list users;

 name | super
------+-------
  joe | False

(1 rows)
joe@cqlsh> login cassandra;
Password: 
cassandra@cqlsh> list users;

 name      | super
-----------+-------
 cassandra |  True
       joe | False

(2 rows)
cassandra@cqlsh> 
```
