### ISSUE TITLE
Internal auth queries should not use "system" `client_state`

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylladb#3166]
When a CQL statement is executed, behavior of the request such as access-control checking and limits on the allowed duration of execution are based on the particular `client_state` associated with the request.

There are currently two kinds of `client_state`: `external`, for most requests, and `internal` for requests made internally as part of the implementation (and targeting system tables).

The `internal` `client_state` bypasses access-control checks and also assumes the "system" keyspace. With support for request-specific time-outs of requests, we also ensure that internal queries never  time-out.

The implementation of access-control CQL statements like `GRANT PERMISSION` or `CREATE ROLE` internally also use metadata tables and skip access-control checks on these requests by using the `internal` `client_state`. However, this is a problem because:

1. Access-control queries query tables in the `system_auth` keyspace, not `system`.
2. Access-control statements like `LIST ROLES` do not time-out, and they should.

One possible solution is for us to introduce a third kind of `client_state` alongside `internal` and `external` which would be used specifically for implementing access-control.

\cc @glommer

**Comment by elcallio** [comment]
On 01/29/2018 06:47 PM, Jesse Haber-Kucharsky wrote:
>
> When a CQL statement is executed, behavior of the request such as 
> access-control checking and limits on the allowed duration of 
> execution are based on the particular |client_state| associated with 
> the request.
>
> There are currently two kinds of |client_state|: |external|, for most 
> requests, and |internal| for requests made internally as part of the 
> implementation (and targeting system tables).
>
> The |internal| |client_state| bypasses access-control checks and also 
> assumes the "system" keyspace. With support for request-specific 
> time-outs of requests, we also ensure that internal queries never 
> time-out.
>
> The implementation of access-control CQL statements like |GRANT 
> PERMISSION| or |CREATE ROLE| internally also use metadata tables and 
> skip access-control checks on these requests by using the |internal| 
> |client_state|. However, this is a problem because:
>
>  1. Access-control queries query tables in the |system_auth| keyspace,
>     not |system|.
>
I'm pretty sure the internal states "home keyspace" does not limit it to 
query or insert into other keyspaces.
>
>  1. Access-control statements like |LIST ROLES| do not time-out, and
>     they should.
>
> One possible solution is for us to introduce a third kind of 
> |client_state| alongside |internal| and |external| which would be used 
> specifically for implementing access-control.
>
If you need time out, why not just add an optional timeout 
parameter/overload to the internal query path?

**Comment by tzach** [comment]
@haaawk what is the user impact of this bug (if any?)

**Comment by slivne** [comment]
@hakuch - have we done any updates related to this ?

**Comment by nuivall** [comment]
> Access-control queries query tables in the system_auth keyspace, not system.

But it's still considered internal, especially now auth-v2 keyspace behaves pretty much as system except having different name.

> Access-control statements like LIST ROLES do not time-out, and they should.

Currently they should timeout, even despite using internal client state (their own flavor to be precise)
```
    // Give the much slower debug tests more headroom for completing auth queries.
    static const auto t = 30s;
#else
    static const auto t = 5s;
```

I'm not sure if this issue is still valid.

**Comment by nuivall** [comment]
In theory we could plug client state taken from CQL layer but I'm unsure about benefit vs potential regressions.

**Comment by ptrsmrn** [comment]
> I'm not sure if this issue is still valid.

I agree, closing for the time being. We can reopen later.
