### ISSUE TITLE
Support UPSERTs using Secondary Index column in the WHERE Clause

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylladb#3230]
Users want to use the secondary index column as their predicate for the WHERE clause to update a partition. Below is an example of such use case

1. The data model looks as the following:

cqlsh:> CREATE TABLE mytable (
            ...     id text PRIMARY KEY,
            ...     id_a text,
            ...     id_b text,
            ...     id_c text,
            ...     id_d text
            ... );

2. Creating 2 secondary indexes on the table
cqlsh> CREATE INDEX ON mytable (id_a);
cqlsh> CREATE INDEX ON mytable (id_c);

cqlsh> INSERT INTO mytable (id, id_a, id_b , id_c, id_d ) VALUES ( '1', '2', '45' , '6', '65');
cqlsh> INSERT INTO mytable (id, id_a, id_b , id_c, id_d ) VALUES ( '2', '2', '45' , '6', '65');
cqlsh> SELECT * FROM mytable;

 id | id_a | id_b | id_c | id_d
----+------+------+------+------
  2 |    2 |   45 |    6 |   65
  1 |    2 |   45 |    6 |   65

3. why would we prevent from the following query to happen? :
UPDATE mytable SET id_a = '4' WHERE id_c = '6';
The results is : 
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid where clause contains non PRIMARY KEY columns: 69645f63"

Same request exists on the C* implementation:
https://issues.apache.org/jira/browse/CASSANDRA-13286

**Comment by avikivity** [comment]
In the extreme case, the update needs to write to all of the rows in the database. It's possible to implement it, but it may not be easy.

**Comment by nyh** [comment]
By the way, even if we don't add this feature, we should at least fix the error message to print "id_c" instead of the gibberish "69645f63".

**Comment by dorlaor** [comment]
Even though it can translate to an extreme case, it can still be functional
to user. I think functionality is more important than protecting the user

**Comment by duarten** [comment]
At the moment I don't think this can be implemented in any sane way. Our SI/MV implementation is eventually consistent with the base table, so using that to drive updates to the base table will result in inconsistencies (not all base rows matching the filter are updated); in the worst case, the update is lost.

**Comment by duarten** [comment]
Same goes for deletions.

**Comment by sumannewton** [comment]
Any update on this? +1 for this feature.

**Comment by nyh** [comment]
> Same goes for deletions.

The DELETE version of this issue is https://github.com/scylladb/scylladb/issues/10593.

**Comment by avikivity** [comment]
This won't be implemented until we have multi-partition transactions. Closing for now to reduce noise.

**Comment by nyh** [comment]
> This won't be implemented until we have multi-partition transactions. Closing for now to reduce noise.

I think you're making a mistake. This (and its DELETE variant) is is an issue that was opened and duplicated multiple times by real users. Keeping the issue open can help avoid further duplicates, as well as tell the user finding it that it's not planned.
