### ISSUE TITLE
Store schema in CQL statements

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#3236]
*Installation details*
Scylla version (or git commit hash): master

Currently, CQL statements store the table and keyspace names, and require a lookup to obtain the schema at some point of the pipeline. We should, however, store a schema pointer in the statement, calculated in the prepare stage. 

This is safe to do as prepared statements are invalidated upon schema changes (save for materialized view updates, which we would need to fix).

**Comment by kostja** [comment]
Nice suggestion, but it's not a bug - when /if we need this optimisation, we can add it (or consider alternatives).
