### ISSUE TITLE
Range tombstones should be evicted gradually

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#3288]
*Installation details*
Scylla version (or git commit hash): any

With row-level eviction (#2576) we now evict partition rows gradually. We never evict range tombstones though, they accumulate and can go away only together with the whole partition. This is problematic, because:

 - more is evicted than necessary, which decreases cache efficiency. In the worst case, the whole cache gets evicted at once

- evicting large amounts of memory at once may impact latency badly

**Comment by avikivity** [comment]
Similar problem in Linux: https://lwn.net/Articles/894098/

**Comment by denesb** [comment]
I think this will become almost naturally solved once we implement the unified v2 internal format. AFAIK we established that we want to store range tombstone markers in/next to rows. In that case, when evicting a row with any range tombstone marker on it, we just move the marker to the next row. If no other row in range, or next row already a marker (current range tombstone ends ther), we drop the range tombstone marker too.
