### ISSUE TITLE
Use Scylla as default username and password for the Authenticator

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#3450]
*Installation details*
Scylla version (or git commit hash): 2.2

Current username is Cassandra
http://docs.scylladb.com/operating-scylla/authentication/

**Comment by hakuch** [comment]
This makes sense, but it's possible that clients are depending on the default username and password being `"cassandra"`.

**Comment by ptrsmrn** [comment]
The default credentials `cassandra:cassandra` are compatible with ... Cassandra ;) and nothing has changed since 6 years (!) in this matter, which makes it highly unlikely to ever change, and for this reason I'm closing this ticket.
