### ISSUE TITLE
Remove probabilistic read repair

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#3502]
This is a mirror for [CASSANDRA-13910](https://issues.apache.org/jira/browse/CASSANDRA-13910).

While reads are typically sent to just enough replicas to satisfy the CL, read requests may be randomly sent to all replicas in order to repair potentially inconsistent data, based on ``read_repair_chance`` and ``dclocal_read_repair_chance`` (another exception is speculative retry).

Often this extra load is not justifiable, since inconsistencies are reliably repaired by either QUORUM reads or by hints. When there are dropped hints (something the manager should pay attention to, btw), then issuing a full repair is in order.

Other good arguments are given in the linked issue.

**Comment by tzach** [comment]
We cant remove it, we invested too much in documenting it! 
http://docs.scylladb.com/architecture/anti-entropy/read-repair/

**Comment by duarten** [comment]
This is a strong indicator that we should document nothing!

**Comment by glommer** [comment]
On Thu, Jun 7, 2018, 8:56 AM Tzach Livyatan, <notifications@github.com>
wrote:

> We cant remove it, we invested too much in documenting it!
> http://docs.scylladb.com/architecture/anti-entropy/read-repair/
>

And ?

**Comment by duarten** [comment]
https://en.wikipedia.org/wiki/Joke

**Comment by nyh** [comment]
Since commit ed0d00f51eda18829aea5bb146e6985a6fb2dc12(a retry of fdd2d9de3d1fb68f96e6a23eb965ad4f957f6805) done for issue #6109, the default of `dc_local_read_repair_chance` is now 0.
So although probabilistic read repair was not officially "removed" as this issue suggests, or even officially deprecated, it's no longer on unless a user deliberately turns it on.

**Comment by mykaul** [comment]
Probably should be removed, the default was changed ages ago.

**Comment by mykaul** [comment]
I wonder if we can continue the path of slow agonizing deprecation by removing read_repair_chance and dclocal_read_repair_chance setting - leaving them hard-coded to 0.
(I don't know how much code we have behind this - if it's substantial or not).

**Comment by avikivity** [comment]
It's code that's good to remove.
