### ISSUE TITLE
Apply hinted-handoff DC blacklisting selectively

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#3517]
There are two hint managers, one for normal mutations, and another for view mutations. View mutations are always DC local, and HH configuration should not intersect in any way with MVs, so we should extract out DC-related policies so we can selectively apply it to the normal hinted-handoff manager, but not to the view updates one.

This would be similar to how Cassandra skips DC-related configuration for their implementation of the batchlog manager, which is based on hinted-handoff.

**Comment by psarna** [comment]
What do you mean exactly by "DC-related policies" here? Hints manager for view updates already ignores `hinted_handoff_enabled=XXX` configuration entirely, and that's where DC blacklisting may occur (e.g. `hinted_handoff_enabled=dc1,dc2`). Only regular HH reads and parses these values. Are there any more DC-related policies I should take into account?

**Comment by duarten** [comment]
No, that's the only DC-related configuration. However, `db::hints::manager::can_hint_for` checks for DC's being enabled, and the manager has a `std::unordered_set<sstring> _hinted_dcs` field that's unneeded. In Cassandra, this is lifted to `StorageProxy`, so the check doesn't affect other usages of HH. We could lift it into another policy object. 

This is a very low priority issue though.

**Comment by psarna** [comment]
Yeah, but `_hinted_dcs` is filled in manager's constructor only. So in our `storage_proxy.cc`, regular hints manager is fed with whatever is passed to `hinted_handoff_enabled`, while hints_for_views_manager is given an empty list (i.e. "all datacenters are enabled"). Which means that hints_for_views_manager is not affected.

Ok, so it's not a correctness issue, but rather a low-priority enhancement, I get it now. Nevermind ;)

**Comment by nyh** [comment]
@psarna I don't understand this issue, and it seems you did, so can you please explain to the n00b who should supposedly (according to the label...) be able to fix it, what exactly needs to be fixed? You said that this is a "low-priority enhancement", but what does it enhance?

**Comment by psarna** [comment]
@nyh I already discussed it in the office a couple of days ago with PiotrD (the supposed future assignee), and I honestly cannot remember what's the point of this issue - it looks like the only issue here is that we could lift dc-checking to a separate abstraction, so that mv hints manager wouldn't even need to keep dc-related data structures. If that's indeed the case, the priority is really low, as it's a cosmetic change, semantics wouldn't really change, because we already ignore dc policy configuration for mv hints.

**Comment by psarna** [comment]
@eliransin I won't be involved in this issue anymore and the discussion seems to have died, so I'm unassigning myself to avoid confusion.

**Comment by kostja** [comment]
https://github.com/scylladb/scylladb/issues/3517#issuecomment-555105449 closing per this comment
