### ISSUE TITLE
AMI: old centos version used by default

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#3523]
*Installation details*
Scylla version (or git commit hash): 2.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

The AMI OS version is CentOS 7.2, leading to too many outdated components. An example is systemd, which lacks support for the AmbientCapabilities directive.

**Comment by mykaul** [comment]
Moved to Ubuntu 22 LTS (minimal) image.
