### ISSUE TITLE
Maxed out networking core on large machines

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#3528]
*Installation details*
Scylla version (or git commit hash): 782827cc1b
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Hardware details (for performance issues)*      
Platform: AWS i3.metal

I observed one thread of the networking core reaching 100% CPU. Likely we have the same problem on i3.16xlarge, we may want to reserve 2 full cores (one on each socket) on such large machines.

Another thing that can improve efficiency is to configure just 2 queues (4 if we allocate 2 cores for networking), so each vcpu needs to deal with just one queue.

**Comment by mykaul** [comment]
done.
