### ISSUE TITLE
nodetool largepartition

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#3589]
*Installation details*
Scylla version (or git commit hash): 2.3

#3292 added a table to capture large partitions in Scylla.
It would be useful to have a nodetool command and a REST API to expose this info to teh end user.

This is similar to `nodetool toppartitions` which expose the top active (not large) partitions

**Comment by glommer** [comment]
We already export that on cql.

Why would REST be better ?

**Comment by tzach** [comment]
Closing. CQL API is better.
We should do the opposite: CQL API for toppartitions
