### ISSUE TITLE
Materialized view update may not need to copy pre-existing columns

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#3594]
When a base update only modifies regular columns of the view (not its primary key), we don't need to create a completely new row in the view from scratch - because such a row already exists - it is enough to send an update to the existing view row, with just the updated columns.

The optimization is small when the view has just a few columns, but it can be large and the most extreme case is a collection column, which gets appended one element at a time until it has a million elements. The base update is tiny each time, and the view update **could** be tiny as well, but currently the last update would require reading the entire 1-million-item collection and writing it in one huge view update, which may even fail (#3586 may be about that).

This problem becomes even worse with #3362 because even *unselected* collection columns will cause this problem, because the view will still contain a collection with many keys - even if without the values.

I vaguely remember that we *used* to have such an optimization in the past, and forwent read-before-write in certain cases (e.g., when just regular columns were modified), but we dropped this optimization as more and more "liveness" issues appeared which forced us to do a full read-before-write in any case to calculate bizarre row markers. Now that #3362 will drop these bizarre row marker calculations (and replace them by virtual cells), maybe we can return the read-before-write avoidance?

**Comment by duarten** [comment]
I don't think we can avoid the read-before-write when we still need the base cells to calculate the virtual view cells, but maybe we don't need to read the unselected column's values, but just the metadata. This would be a separate optimization though.

For this case, the only thing we can do is indeed to try to include just the changed columns. Note however that this mostly optimizes multi-cell collections; frozen collections would still need to be sent in full if they change.

**Comment by nyh** [comment]
@duarten if we assume the base and view are consistent, in the discussed situation (the update only updated regular columns) the existing view row already includes all the correct virtual cells for the *non-updated* cells. There is no reason to build the same virtual cells yet again. Only the cells actually updated need to be written again (perhaps as virtual cells). And the only thing we need to read-before-write is the view's primary key columns (if the view doesn't have a new key column, we don't even need to read those, because the base's primary key we already have!).

**Comment by mlitvk** [comment]
@nyh since this issue is quite old, can you help me understand what is relevant and what could be done here?

For example, I tried to see if we copy the entire row with the following test:
```
# disableautocompaction
CREATE TABLE t(p int, s set<int>, v int, PRIMARY KEY(p));
CREATE MATERIALIZED VIEW vt AS SELECT * FROM t WHERE p IS NOT NULL PRIMARY KEY(p);
INSERT INTO t(p,s,v) VALUES(0,{1,2,3},0);
# flush
UPDATE t SET v=1 WHERE p=0;
# flush
# sstable dump
```
And I see that the new row contains only the key and the updated column. It doesn't write the set column.

I do see that this updates does a read-before-write which may be unnecessary, although I probably need to understand the liveness issues better

**Comment by nyh** [comment]
> @nyh since this issue is quite old, can you help me understand what is relevant and what could be done here?

Good question. I thought everything writen above was true and still relevant, but maybe maybe it never was true, or no longer is? In particular:

> INSERT INTO t(p,s,v) VALUES(0,{1,2,3},0);
> UPDATE t SET v=1 WHERE p=0;
> And I see that the new row contains only the key and the updated column. It doesn't write the set column.

So it looks like we do have this optimization already?
I think the relevant code is view_updates::generate_update(), which in this case calls `update_entry()` (and not delete_old_entry, create_entry). update_entry() indeed has code like:
```
        auto diff = update.cells().difference(*_base, kind, existing.cells());
        add_cells_to_view(*_base, *_view, kind, std::move(diff), r->cells());
```
And this isn't new code. The r->cells() is just the new update, and it suggests  the only thing that gets copied to the update in this case are the new parts in the update (r->cells()), not the full content of the base row.

BUT, looking at the `add_cells_to_view()` function (the last function called above), it does seem like it iterates over all of base_cells. These base_cells are `diff` above, so supposedly only the new updates, but maybe something is off in this calculation with collections? Please try also the case of an  **unselected** collection column (a collection column which is not SELECTed in the view but needs to be copied as a collection of empty elements, as part of the "virtual columns" liveness feature).

If we never had this bug (?), how did https://github.com/scylladb/scylladb/issues/3586 happen?

**Comment by mlitvk** [comment]
I tried few more cases
I see that when we update a view primary key then we copy also unchanged columns.
For example here we write the entire set each time we update `v`:
```
cqlsh:ks> CREATE TABLE t(p int, s set<text>, v int, PRIMARY KEY(p));
cqlsh:ks> CREATE MATERIALIZED VIEW vt AS SELECT * FROM t WHERE p IS NOT NULL AND v IS NOT NULL PRIMARY KEY(p,v);
cqlsh:ks> INSERT INTO t(p,s,v) VALUES(0,{'a','b','c'},0);
cqlsh:ks> UPDATE t SET v=1 WHERE p=0;
```
Maybe this could explain #3586?

**Comment by nyh** [comment]
> I tried few more cases I see that when we update a view primary key then we copy also unchanged columns. For example here we write the entire set each time we update `v`:

Yes, here we don't really have an option: We need to delete the old view row with v=0 and create a new one with v=1. Since the the new view row is new, we need to write all the data into it.
So this issue was not about this case, but about the case where we can only modify an existing view row and not create a new one. 

> Maybe this could explain #3586?

Perhaps. I saw on #3586 that the user's schema indeed had a new clustering key column in the view, so a write that modifies that column (lastshareid) will require writing the entire row. But I don't know if that's what actually what this user did. I suspect that if he has a set, then the most common update was to add something to that set.

So if you see that this issue is wrong, and we already optimized this case (please do check the unselected-collection case as well), maybe we should just closet his issue?

**Comment by mlitvk** [comment]
I tested the cases with unselected collection column and selected, doing operations of updating `v` and adding or removing elements to the set
```
cqlsh:ks> CREATE TABLE t(p int, s set<text>, v int, PRIMARY KEY(p));
cqlsh:ks> CREATE MATERIALIZED VIEW vt1 AS SELECT v FROM t WHERE p IS NOT NULL PRIMARY KEY(p);
cqlsh:ks> CREATE MATERIALIZED VIEW vt2 AS SELECT * FROM t WHERE p IS NOT NULL PRIMARY KEY(p);
```
It looks like we write only the changed columns, or changed cells in case of collection updates, so I don't see an issue here so far

> > Maybe this could explain #3586?
> 
> Perhaps. I saw on #3586 that the user's schema indeed had a new clustering key column in the view, so a write that modifies that column (lastshareid) will require writing the entire row. But I don't know if that's what actually what this user did. I suspect that if he has a set, then the most common update was to add something to that set.

It sounds not unlikely that the user updates `lastshareid` every time he adds an element to `allshareids`

**Comment by nyh** [comment]
> I tested the cases with unselected collection column and selected, doing operations of updating `v` and adding or removing elements to the set
> 
> ```
> cqlsh:ks> CREATE TABLE t(p int, s set<text>, v int, PRIMARY KEY(p));
> cqlsh:ks> CREATE MATERIALIZED VIEW vt1 AS SELECT v FROM t WHERE p IS NOT NULL PRIMARY KEY(p);
> cqlsh:ks> CREATE MATERIALIZED VIEW vt2 AS SELECT * FROM t WHERE p IS NOT NULL PRIMARY KEY(p);
> ```
> 
> It looks like we write only the changed columns, or changed cells in case of collection updates, so I don't see an issue here so far

Thanks for checking this. So it looks like this issue is wrong, and I'll close it.

> > > Maybe this could explain #3586?
> > 
> > 
> > Perhaps. I saw on #3586 that the user's schema indeed had a new clustering key column in the view, so a write that modifies that column (lastshareid) will require writing the entire row. But I don't know if that's what actually what this user did. I suspect that if he has a set, then the most common update was to add something to that set.
> 
> It sounds not unlikely that the user updates `lastshareid` every time he adds an element to `allshareids`

Yes, that looks like a good guess.
