### ISSUE TITLE
Thoroughly test CQL protocol

### ISSUE THREAD

**Issue by duarten** [scylladb/scylladb#3695]
Scylla implements the server component of the CQL protocol. It is currently tested somewhat indirectly by dtests, which are themselves restricted to the behavior of the python driver. As we've seen by #3688, some aspects of the implementation are undertested. The python driver is also well-behaved and has been around long enough to be mostly correct. It is possible developing a driver against Scylla from scratch would result in plenty of server crashes or bad behavior due to unexpected inputs.

To address this we should write tests that craft CQL messages and thoroughly test our implementation of the [protocol](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v5.spec). This can be done at unit or d-test level.

**Comment by kostja** [comment]
This is an obvious idea, I see very little value in tracking it as a github issue, and a clear overhead from shuffling it from person to person, team to team.

**Comment by nyh** [comment]
One of the key design goals of the cql-pytest framework was to exercise the real CQL protocol, via  a real CQL client, to reach as many CQL features as we possibly can, so cql-pytest already goes a long way towards the goal of this issue. But it probably does **not** exercise - at least not exhaustively - all the details of the CQL protocol such as all the different flags, multiple concurrent streams, and so on. If we were writing the CQL protocol now, I would have expected its author to make sure that indeed all these CQL protocol features are tested exhaustively, either through the cql-pytest framework (assuming that the driver even uses all these features) or through some sort of unit test. But I agree we'll probably never go back and do that now.
