### ISSUE TITLE
Make Dockerfile visible on Docker Hub

### ISSUE THREAD

**Issue by penberg** [scylladb/scylladb#3769]
The contents `Dockerfile` are useful for people that want to know what's inside the Scylla image.

We can either switch to automated builds to enable a `Dockerfile` tag on the project:

https://docs.docker.com/docker-hub/builds/

Or link from Docker Hub documentation to tag and its corresponding `Dockerfile`:

https://hub.docker.com/_/cassandra/

https://hub.docker.com/_/mysql/

**Comment by mykaul** [comment]
Done.
