### ISSUE TITLE
CQL layer needs a rewrite or refactoring

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#3815]
CQL layer contains inconsistencies and caveats for some functionalities,
there are also some not fully defined interfaces. It needs a rewrite or at least refactoring.
The Improved CQL layer should be more compatible to C* 3 features and hopefully will better support
features to come.

**Comment by penberg** [comment]
What specific C* 3 features do you think are missing from the transport layer?

**Comment by eliransin** [comment]
I didn't say there are missing features, but i got feedback from people working on
materialized views and secondary indexes saying that all sorts of
hacks had to be made in order to support them. From my own experience ,there
are some inconsistencies in the implementation, one example is ALLOW FILTERING
support on multi-column restrictions, it is known to be missing, but the reason is that
the current design makes it complicated to implement.

**Comment by penberg** [comment]
@eliransin So you mean the _whole_ CQL front-end? I misunderstood from "CQL layer" that you meant the transport protocol in `server/transport.cc`...

The CQL _front-end_ indeed has various inconsistencies and CQL features that are partially implemented (for historical reasons). A healthy dose of cleanups in that area would indeed be most welcome!

**Comment by duarten** [comment]
Yes, Cassandra 3.X saw a big refactoring at the CQL layer level. We could also stand to make it more C++ instead of using shared_ptrs all around and stuff like that.

**Comment by nyh** [comment]
This issue needs to be more concrete. Is it about the CQL transport, CQL parser, or the entire CQL implementation? What exactly needs a rewrite or refactoring, and why? @duarten mentioned Cassandra 3 also did a refactoring in this area, but with what goal? Is there a Cassandra issue or commit or something we can refer to?

**Comment by duarten** [comment]
This issue targets the contents of the `cql3` folder, and excludes the parser and the transport.

Cassandra has been making improvements in this area (starting with CASSANDRA-8099), while we have been mostly adding branches. I can barely figure out what's going on in `statement_restrictions` right now.

We of course should start by looking at the structure we use and how it can be improved (do we really need all those `shared_ptr`s ?), and the biggest pain points (restrictions). Also, we should look at the current Cassandra implementation, identify things we're missing, and possibly take inspiration from it.

**Comment by ptrsmrn** [comment]
I allowed myself to close this issue, as it's too generic and vague. There're other issues that continue with fixing CQL bugs/discrepancies/refactoring etc.
