### ISSUE TITLE
Scan timeout after all data TTL exceeded

### ISSUE THREAD

**Issue by OstCollector** [scylladb/scylladb#3914]
*Installation details*
Scylla version (or git commit hash): 2.1.6
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2.1511

*Description*
When insert data with TTL, scan timeouts after all data is expired.

*How to reproduce*
apply following patch to cassandra-3.11 to enable TTL support of cassandra-stress:
```diff -aurP cassandra.orig/tools/stress/src/org/apache/cassandra/stress/StressProfile.java cassandra/tools/stress/src/org/apache/cassandra/stress/StressProfile.java
--- cassandra.orig/tools/stress/src/org/apache/cassandra/stress/StressProfile.java	2018-11-14 14:26:23.000000000 +0800
+++ cassandra/tools/stress/src/org/apache/cassandra/stress/StressProfile.java	2018-11-14 14:27:25.000000000 +0800
@@ -524,7 +524,15 @@
                     StringBuilder sb = new StringBuilder();
                     if (!isKeyOnlyTable)
                     {
-                        sb.append("UPDATE ").append(quoteIdentifier(tableName)).append(" SET ");
+                        sb.append("UPDATE ").append(quoteIdentifier(tableName));
+
+                        if (insert.containsKey("ttl"))
+                        {
+                            sb.append(" USING TTL " + insert.get("ttl"));
+                            insert.remove("ttl");
+                        }
+
+                        sb.append(" SET ");
                         //PK Columns
                         StringBuilder pred = new StringBuilder();
                         pred.append(" WHERE ");
@@ -577,6 +585,12 @@
                         sb.delete(sb.lastIndexOf(","), sb.length());
                         value.delete(value.lastIndexOf(","), value.length());
                         sb.append(") ").append("values(").append(value).append(')');
+
+                        if (insert.containsKey("ttl"))
+                        {
+                            sb.append(" USING TTL " + insert.get("ttl"));
+                            insert.remove("ttl");
+                        }
                     }
 
                     if (insert == null)
```

Then create schema as follows:
```
CREATE KEYSPACE ttltest WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE ttltest.ttl (
    key ascii PRIMARY KEY,
    value blob
);
```

And create stress.yaml as follows:
```
keyspace: ttltest
# keyspace_definition: |
#   CREATE KEYSPACE ttltest WITH replication = { 'class':'SimpleStrategy', 'replication_factor':3};

table: ttl
# table_definition: |
#   CREATE TABLE ttl ( key ascii PRIMARY KEY, value blob );

columnspec: 
  - name: key
    size: fixed(11)
  - name: value
    size: fixed(200)

insert: 
  partitions: fixed(1)
  select: fixed(0)/1
  batchtype: UNLOGGED
  ttl: 20

queries:
  tests:
    cql: SELECT * FROM ttltest.ttl WHERE key = ?
```

Using following command to fill the database and use cqlsh to fetch the data
```
cassandra-stress user profile=stress.yaml n=100000000 'ops(insert=1)' -node 172.16.1.81 -rate threads=1024
```

*Expected behavior*
After all the TTL of the data are exceeded, perform `SELECT key ,value, ttl(value) from ttltest.ttl limit 5;` in cqlsh should return empty

*Actual behavior*
got following message:
```
ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for ttltest.ttl - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
```

If limit key like `where key = "foobar"` in the query, scylladb seems to work.

**Comment by OstCollector** [comment]
well, after thinking about this for a while, I think this is an explainable behavior.
ScyllaDB is required to scan the data that is not compacted, but it failed to find any.
So the result cannot be returned after the whole table being scanned.

**Comment by tgrabiec** [comment]
@OstCollector The timeout is not because we fail to find any live row, but probably because it takes too long to build a single page of results, as it requires a full table scan.

**Comment by nyh** [comment]
@tgrabiec I am not sure we should close this issue, because we could probably fix this issue if we wanted: Scylla is not forced to wait for a *full* page of results - when it sees the timeout is about to run out, it can also return a partial page of results - I believe we once even discussed the idea of returning an *empty* page if necessary, which is also fine (it will be an empty page, but with a flag saying you should ask for more).

**Comment by tgrabiec** [comment]
I agree with @nyh that the issue should be still open (it wasn't me who closed it).

**Comment by tgrabiec** [comment]
@raphaelsc Do we drop fully expired sstables during reads like we do during compaction? Or maybe, are fully expired sstables supposed to be dropped immediately when they expire?

**Comment by raphaelsc** [comment]
On Tue, Mar 17, 2020 at 2:15 PM Tomasz Grabiec <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> Do we drop fully expired
> sstables during reads like we do during compaction?
>
Almost sure we don't. BTW, fully expired sstables in compaction terms mean
sstable that can be purged for sure because its tombstones don't possibly
shadow any data in non-compacting sstables. For reader purpose, we'd need
to do the same.


> Or maybe, are fully expired sstables supposed to be dropped immediately
> when they expire?
>
Yes, we don't even care about compacting those, we just delete them at the
end of compaction, look:
https://github.com/scylladb/scylla/blob/14de126ff83d8322090e4190273aecf06ce64b31/sstables/compaction.cc#L487
