### ISSUE TITLE
Consider non-random token distribution, and lower num_tokens

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#3994]
The main reason we need to use a high number of vnodes per node (currently our default is num_tokens=256) is, IIRC, because the token distribution is random, so having too few of them can lead to unbalanced sizes of different nodes. Having a high number of tokens also has its prices (not very high, but still...), so Cassandra 3.0 replaced random token distribution with an algorithm - see https://issues.apache.org/jira/browse/CASSANDRA-7032 - to allocate tokens to a new node in a way which tries to keep the cluster balanced. 

Cassandra 3.0 still left the default num_tokens=256, but Datastax is already recommending num_tokens=8 (see https://docs.datastax.com/en/dse/5.1/dse-dev/datastax_enterprise/config/configVnodes.html) and Cassandra are considering lowering the default num_tokens to 16 (see https://issues.apache.org/jira/browse/CASSANDRA-13701) but have been sitting on this patch for a year and a half.

See also issue #863 about using a similar technique but the addition of token range movement after the vnodes have already been assigned.

See also https://github.com/scylladb/scylla-docs/issues/1516 about documenting our choice of num_nodes=256.

**Comment by avikivity** [comment]
Cassandra's algorithm has several problems:
 - it only works for one replication factor, others can get large imbalance
 - it does not work when nodes are removed; you can get large imbalance
 - you have to specify a keyspace for the algorithm to work on (to get the replication strategy and replicaton factor)

Is there a problem with num_tokens=256?

**Comment by nyh** [comment]
@avikivity thanks for clarifying the downsides of Cassandra's new approach (this is why I labeled the bug "consider", I wasn't entirely sure this was a good idea).
One of the problems with num_tokens=256 is that some algorithms are proportional to this. But the real reason that led me to look at this was a complaint from a user why we need such high number when Cassandra doesn't :-) I created scylladb/scylla-docs#1516 to document the benefits of our existing approach.

**Comment by eliaslevy** [comment]
Large numbers of vnodes affect availability as discussed in this [mailing list thread](http://mail-archives.apache.org/mod_mbox/cassandra-dev/201804.mbox/%3CCALShVHcz5PixXFO_4bZZZNnKcrpph-=5QmCyb0M=w-MhdYL89w@mail.gmail.com%3E) and the [paper](https://github.com/jolynch/python_performance_toolkit/raw/master/notebooks/cassandra_availability/whitepaper/cassandra-availability-virtual.pdf) by Joseph Lynch and Josh Snyder from Netflix.

**Comment by avikivity** [comment]
The improvement in availability is only for large clusters, and it is large clusters that are most affected by imbalance when there is a low number of vnodes. Large clusters are also more likely to have node removals.

**Comment by nyh** [comment]
I noticed now that Cassandra has resolved their issue https://issues.apache.org/jira/browse/CASSANDRA-13701. Cassandra 4.0 reduced their default num_tokens to 16.
In Scylla, the advent of **tablets** will make all this discussion moot.

**Comment by nyh** [comment]
Tablets are here, which indeed made this discussion about vnode improvements moot. I'm closing this ancient issue.
