### ISSUE TITLE
Remove "sstring_view" and replace its usages by std::string_view

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#4062]
We have in `bytes.hh`
```C++
using sstring_view = std::experimental::string_view;
```
About half the Scylla code uses this name `sstring_view`, half uses `stdx::string_view` and minority uses `std::experimental::string_view`.
I think we should switch all of these to `stdx::string_view` and remove the type "sstring_view". Eventually we'll do a sweep and replace all stdx in the code to std, but for now it can remain stdx.

**Comment by duarten** [comment]
I have a patch that does this, by replacing stdx types with std ones.

**Comment by eliransin** [comment]
I think that from c++17 it is just std::string_view.
I believe that @duarten patch already takes this into account.

**Comment by nyh** [comment]
@duarten @eliransin my point in this issue is **not** about stdx:: vs std:: isn't about our alias `sstring_view`, with two s'es, which doesn't need to exist any more. Even before C++17, we had stdx::string_view and can use that. True that with @duarten's patch it will be converted to std::string_view.

**Comment by eliransin** [comment]
@nyh  I got you :) , And I agree. We should get rid of the redundancy.
In order to avoid conflicts with @duarten's patch I sugest to only do: sstring_view->std::string_view and than duarte's pathch will clean up everything else.

**Comment by duarten** [comment]
This is not a priority, so it should happen after my patch goes in. Otherwise I'll have to rebase, and solve hundreds of conficts.

**Comment by nyh** [comment]
Update: all uses of stdx::string_view and std::experimental::string_view have been replaced by std::string_view. All that remains is changing the uses of the "sstring_view" alias to std::string_view.
