### ISSUE TITLE
Implement an API for re-balancing the token ring

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#4084]
HEAD: b247ce01c3d74dfd7884d0fce790f20420fe4055

*Description*
A token ring may end up in a rather unbalanced state due to a random nature of a token ring division algorithm used when a new node is added. 

We may want to implement an API which would trigger a re-balancing of a token ring and making sure that each token range has an equal size which in line would ensure a perfect balancing of tokens among all present nodes and in line would ensure a perfect balancing of partitions among nodes both as a primary and as a non-primary replica.

**Comment by vladzcloudius** [comment]
@glommer In this particular case I think having an explicit API may have not less sense than an automatic option. This is rarely critical or has any significant influence on a cluster's performance. Therefore in those rare cases when a customer wants to fix this it would make more sense to give a tool to issue the operation that has a well defined beginning and end so that he/she could stage it a way that suits him/her best.

**Comment by tzach** [comment]
As we move to Tablets, this become irrelevant.
@mykaul I sugget to close.
