### ISSUE TITLE
out-of-memory during read if compaction cannot keep up and excessive memtable flushing

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#4116]
With size-tiered compaction, the amount of memory required by a read is O(number of sstables in the table for this shard). Therefore, if we create sstables faster than we can compact them, the amount of memory required for a read will eventually exceed the amount of memory on a shard.

Normally, this is bad (as in bad_alloc) but not catastrophic; the reads will fail and eventually compaction will reduce the number of sstables (assuming compaction itself can make progress). However, during bootup, a read failure is catastrophic (we must read our metadata or we can't boot), and compaction is not yet enabled.

Due to the controllers, it is hard to reach this situation, as the compaction shares will keep increasing and we will give compaction more resources than memtable flushes, so compaction will eventually be able to keep up. We observed the problem in this scenario:

 1. Start with a moderately large node (> 10 shards)
 2. Create a keyspace with a large amount of tables (thousands)
 3. Drop that keyspace

Since dropping a table involves smp::count writes to system.local, with a flush after each one, we will have tens of thousands of memtable flushes, with the potential to create tens of thousands of sstables. If we restart before compaction had the chance to clear them up, the bootstrap read from system.local will run out of memory.

**Comment by glommer** [comment]
I want to point out that I disagree that bad_allocs are not catastrophic because the reads will fail and compaction will reduce the number of SSTables. You are being too optimistic with this.

In reality, memory is not exhausted for reads only, but for everything in that shard. This can lead to compaction itself failing, repairs failing, and the most serious of them I saw so far, gossip updates that are marked as noexcept failing and crashing the node.

If bad_allocs would affect just one operation, like reads, I would agree with you that they are usually okay. But in reality low memory situations are bad for the node health as a whole

**Comment by avikivity** [comment]
True, the while the read failure itself is not bad, the side effects can crash the machine.

**Comment by Mepherotus** [comment]
Hello guys!
Is anybody working on this issue right now?

**Comment by DoronArazii** [comment]
@mikolajsieluzycki 
Any progress with this one? it's required by the Mavenir case

**Comment by bhalevy** [comment]
@raphaelsc shouldn't reshape compaction deal with too many uncompacted sstables during startup?
Will it work also for the system schema table? (/cc @tgrabiec)

**Comment by raphaelsc** [comment]
> @raphaelsc shouldn't reshape compaction deal with too many uncompacted sstables during startup? Will it work also for the system schema table? (/cc @tgrabiec)

Yes, and yes. We reshape system tables before starting storage proxy, so reads on them should have reasonable read amplification. As we know, the backpressure work by Mikolaj will help with excessive flushing creating high readamp before compaction has a chance to catch up. Orthogonal work which will help is https://github.com/scylladb/scylla/issues/4076 and some tweaking in the compaction manager to prioritize tables with highest L0 backlog. Strategies themselves already do that.

**Comment by bhalevy** [comment]
I'm not sure why the `Backport candidate` label wasn't added automatically.
I added it manually for the sake of discussion (#10717 might be too invasive to backport, certainly before it gets some mileage in master and OSS release)

**Comment by avikivity** [comment]
I think it's too invasive. The issue is rare enough that I think it's better not to risk backports and instead let it graduate through upgrades.

**Comment by bhalevy** [comment]
@avikivity and it's not stable yet.
We're seeing hangs during flush in testing (See https://github.com/scylladb/scylla-dtest/pull/2761)

**Comment by avikivity** [comment]
Important fix, but not a regression (and a big change), so not backporting.
