### ISSUE TITLE
Fail to GRANT EXECUTE ON FUNCTION system.sum(int) / system.intasblob(int)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylladb#4276]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20190122.dbc1894bd
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Failed test:  [auth_roles_test:TestAuthRoles.disallow_grant_revoke_on_builtin_functions_test](https://github.com/scylladb/scylla-dtest/blob/next/auth_roles_test.py#L1080)
https://github.com/scylladb/scylla-dtest/blob/next/auth_roles_test.py#L1080

```
ERROR: disallow_grant_revoke_on_builtin_functions_test (auth_roles_test.TestAuthRoles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/auth_roles_test.py", line 1112, in disallow_grant_revoke_on_builtin_functions_test
    InvalidRequest)
  File "/home/amos/space/scylla-dtest/assertions.py", line 36, in assert_invalid
    res = session.execute(query)
  File "cassandra/cluster.py", line 2134, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4026, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:14  : syntax error...
">
```

Manual reproduce steps:
```
cassandra@cqlsh> CREATE ROLE mike;
cassandra@cqlsh> GRANT EXECUTE ON FUNCTION system.intasblob(int) TO mike;
SyntaxException: line 1:14  : syntax error...

cassandra@cqlsh> select system.sum(num) from rest.table1 ;

 system.sum(num)
-----------------
               3

(1 rows)
cassandra@cqlsh> GRANT EXECUTE ON FUNCTION system.sum(int) TO mike;
SyntaxException: line 1:14  : syntax error...
```

@hakuch @slivne @roydahan

**Comment by hakuch** [comment]
We don't support user-defined functions (UDF), so we cannot grant permission on `FUNCTION` resources.

**Comment by amoskong** [comment]
But sum and intasblob is not udf.

Jesse Haber-Kucharsky <notifications@github.com> 于 2019年2月25日周一 下午11:35写道：

**Comment by hakuch** [comment]
I see.

We don't support granting permissions on `FUNCTION` resources (even if they're not user-defined).

We could probably add support for this, but it may require changes to the CQL layer, so for now it's better to leave these tests out, I think.

**Comment by amoskong** [comment]
I agree with you, I will add require to skip this subtest.

Jesse Haber-Kucharsky <notifications@github.com> 于 2019年2月26日周二 上午3:55写道：

**Comment by slivne** [comment]
related to #2204

**Comment by bhalevy** [comment]
@espindola what's the status of this issue?

**Comment by tzach** [comment]
Dup with https://github.com/scylladb/scylla/issues/5572 ?

**Comment by espindola** [comment]
I think it is a dup of 5572, unless we want this issue to track having a better error message on the short term.
