### ISSUE TITLE
Do not allow (or warn) when a dead node come back to life after more than gc_grace_seconds

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#4277]
Scylla version (or git commit hash): 3.0

When a node is down for more than `gc_grace_seconds` and comes back to life, user risk a problem of data resurrection, as tombstones already removed in other nodes, but not in the failed node.

If the node knows how much time it was not available, it can compare the time to the schema gc_grace_seconds and warn about this risk.

**Comment by slivne** [comment]
gc_grace_seconds is per table

**Comment by tzach** [comment]
@asias @kostja does this make sense?
You are both working on related features

**Comment by kostja** [comment]
@gleb-cloudius one more reason we need to track node states as seen by the topology coordinator, including soft state changes like up and down. 

@tzach Regarding your question, I think it's a good idea but it's currently out of scope of our work, not part of feature graduation criteria. 

Please indicate the priority of this, i.e. how much value it is for our users. I think it's a fairly unlikely situation ,and if it happens, the impact is limited - perhaps whoever is concerned with that should keep an eye on their cluster health.

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius one more reason we need to track node states as seen by the topology coordinator, including soft state changes like up and down.

I did not see any single sane reason to put local fd decision of a random node into a global topology registry :) This is not the one either.

Here the decision to warn and refuse to boot is competently local to a node.

**Comment by tzach** [comment]
It should not be urgent, and I will close it.
I assume the admin can remove the nodes during the gc_grace_seconds period, and we have other means to ensure nodes do not resurrect from the dead.
