### ISSUE TITLE
Problem stopping node

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#4384]
Seen in [dtest-release/75/testReport/repair_additional_test/RepairAdditionalTest/repair_kill_2_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/testReport/repair_additional_test/RepairAdditionalTest/repair_kill_2_test/):
```
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/repair_additional_test.py", line 2485, in repair_kill_2_test
    return RepairAdditionalBase._repair_kill_2_test(self)
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/repair_additional_test.py", line 1276, in _repair_kill_2_test
    self._repair_kill_1_test(False)
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/repair_additional_test.py", line 1244, in _repair_kill_1_test
    node2.stop(wait_other_notice=True)
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-ccm/ccmlib/scylla_node.py", line 505, in stop
    raise NodeError("Problem stopping node %s" % self.name)
Problem stopping node node2
```
[node2.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554065722533_repair_additional_test.RepairAdditionalTest.repair_kill_2_test/node2.log):
```
INFO  2019-03-31 20:53:14,817 [shard 0] compaction_manager - Asked to stop
INFO  2019-03-31 20:53:14,817 [shard 1] compaction_manager - Asked to stop
INFO  2019-03-31 20:53:14,823 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-rkuN87/test/node2/data/ks/cf-c910271053f611e9a8b9000000000001/mc-131-big-Data.db:level=0, ]. 10829 bytes to 7023 (~64% of original) in 33ms = 0.20MB/s. ~256 total partitions merged to 9.
INFO  2019-03-31 20:53:14,830 [shard 0] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-rkuN87/test/node2/data/ks/cf-c910271053f611e9a8b9000000000001/mc-128-big-Data.db:level=0, ]. 23001 bytes to 18743 (~81% of original) in 85ms = 0.21MB/s. ~256 total partitions merged to 22.
INFO  2019-03-31 20:53:14,833 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-rkuN87/test/node2/data/ks/cf-c910271053f611e9a8b9000000000001/mc-133-big-Data.db:level=0, ]. 25500 bytes to 22521 (~88% of original) in 30ms = 0.72MB/s. ~256 total partitions merged to 35.
INFO  2019-03-31 20:53:14,833 [shard 0] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-rkuN87/test/node2/data/ks/cf-c910271053f611e9a8b9000000000001/mc-130-big-Data.db:level=0, ]. 9966 bytes to 6382 (~64% of original) in 83ms = 0.07MB/s. ~256 total partitions merged to 3.
INFO  2019-03-31 20:53:14,834 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-rkuN87/test/node2/data/ks/cf-c910271053f611e9a8b9000000000001/mc-135-big-Data.db:level=0, ]. 10441 bytes to 5936 (~56% of original) in 27ms = 0.21MB/s. ~256 total partitions merged to 8.
INFO  2019-03-31 20:53:14,835 [shard 1] compaction_manager - Stopped
INFO  2019-03-31 20:53:14,838 [shard 0] compaction_manager - compaction info: Compaction for ks/cf was stopped due to shutdown.: will stop
INFO  2019-03-31 20:53:14,854 [shard 0] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-rkuN87/test/node2/data/ks/cf-c910271053f611e9a8b9000000000001/mc-132-big-Data.db:level=0, ]. 22836 bytes to 19496 (~85% of original) in 94ms = 0.20MB/s. ~256 total partitions merged to 20.
INFO  2019-03-31 20:53:14,869 [shard 0] compaction - Compacted 3 sstables to [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-rkuN87/test/node2/data/ks/cf-c910271053f611e9a8b9000000000001/mc-136-big-Data.db:level=0, ]. 21695 bytes to 14399 (~66% of original) in 95ms = 0.14MB/s. ~384 total partitions merged to 9.
INFO  2019-03-31 20:53:14,870 [shard 0] compaction_manager - Stopped
INFO  2019-03-31 20:53:14,870 [shard 0] view - Stopping view builder
INFO  2019-03-31 20:53:14,870 [shard 1] view - Stopping view builder
INFO  2019-03-31 20:53:14,871 [shard 0] storage_service - Drain on shutdown: starts
INFO  2019-03-31 20:53:14,871 [shard 0] storage_service - Stop transport: starts
INFO  2019-03-31 20:53:14,872 [shard 0] storage_service - Thrift server stopped
INFO  2019-03-31 20:53:14,876 [shard 0] storage_service - CQL server stopped
INFO  2019-03-31 20:53:14,876 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2019-03-31 20:53:14,876 [shard 0] gossip - My status = NORMAL
INFO  2019-03-31 20:53:14,876 [shard 0] gossip - Announcing shutdown
INFO  2019-03-31 20:53:14,877 [shard 0] storage_service - Node 127.0.84.2 state jump to normal
INFO  2019-03-31 20:53:17,284 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - messaging_service stopped
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - stream_manager stopped
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - Stop transport: done
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - Drain on shutdown: stop_transport done
INFO  2019-03-31 20:53:17,285 [shard 0] tracing - Asked to shut down
INFO  2019-03-31 20:53:17,285 [shard 0] tracing - Tracing is down
INFO  2019-03-31 20:53:17,285 [shard 1] tracing - Asked to shut down
INFO  2019-03-31 20:53:17,285 [shard 1] tracing - Tracing is down
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - Drain on shutdown: tracing is stopped
INFO  2019-03-31 20:53:17,285 [shard 0] storage_service - Drain on shutdown: system distributed keyspace stopped
INFO  2019-03-31 20:53:17,285 [shard 0] hints_manager - Asked to stop
INFO  2019-03-31 20:53:17,285 [shard 0] hints_manager - Stopped
INFO  2019-03-31 20:53:17,285 [shard 1] hints_manager - Asked to stop
INFO  2019-03-31 20:53:17,286 [shard 1] hints_manager - Stopped
INFO  2019-03-31 20:53:17,286 [shard 0] storage_service - Drain on shutdown: hints manager is stopped
INFO  2019-03-31 20:53:17,483 [shard 0] storage_service - Drain on shutdown: flush column_families done
INFO  2019-03-31 20:53:17,483 [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
INFO  2019-03-31 20:53:17,483 [shard 0] storage_service - Drain on shutdown: done
INFO  2019-03-31 20:53:17,484 [shard 0] repair - Starting shutdown of repair
INFO  2019-03-31 20:53:17,484 [shard 0] repair - Completed shutdown of repair
```

This looks pretty normal but is missing the indication for completing shutdown.
For example, [dtest-release/75/artifact/logs-release.2/1554065581576_repair_additional_test.RepairAdditionalTest.repair_kill_1_test/node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554065581576_repair_additional_test.RepairAdditionalTest.repair_kill_1_test/node1.log):
```
init - Scylla version 666.development-0.20190331.77a0d5c5d shutdown complete.
```

**Comment by bhalevy** [comment]
@asias, can you please look at this and see if you have any insight?

@espindola I'd like to keep this issue as an umbrella issue for fixing our shutdown code so we shut down scylla cleanly.  As discussed with @avikivity the general direction we'd like to take is similar to systemd where the different services in the system start up and shut down in parallel, and we can implement the dependencies between the services wither in a data-driven or code-driven way, as long as we detect circular dependencies.

It may take further separation of the system tables from the user tables, either as a separate database instance or maybe a separate service, as the user tables depend on the system tables for large data handling.

I think that the init service should orchestrate startup and shutdown and monitor the other services.
It should log an INFO message when getting a signal to shutdown so we can see when the shutdown process starts and when it is retried.  On retry, we can also print the status of services that are have not shut down yet.

Finally, we should implement a timeout for shutdown and commit suicide when it goes off so to get a core dump for post-mortem analysis.

**Comment by bhalevy** [comment]
Stopping sstables is part of #4149

**Comment by denesb** [comment]
On a superficial look it seems to be related to https://github.com/scylladb/scylla/issues/4044.

**Comment by bhalevy** [comment]
Ref #2737

**Comment by bhalevy** [comment]
On Tue, 2019-04-02 at 11:39 +0300, @avikivity  wrote:
+ @gleb-cloudius 

> Here's how I think it should be done:
> 
> 
> 1. de-static-ify everything, every dependency passes via constructor 
> parameters
> 
> 2. all services created in main thread via this pattern
> 
> 
>      sharded<service1> a_service1;
> 
>      a_service1.start(dependency list...);
> 
>      auto stop_service1 = defer([&] { a_service1.stop().get(); } );
> 
> 
> This ensures stops happen in reverse order of starts, either due to 
> normal termination or an exception during startup.
> 
> 
> 3. add a wait_for_shutdown().get() at the end of the main thread
> 
> 
> wait_for_shutdown() becomes ready when a SIGSTOP/SIGTERM is caught, or 
> when the node chooses to shut down for another reason.
> 
> 
> These steps will likely need to be intermixed, not in order.
> 
> 
> A complication is that we will have circular dependencies for sure, 
> database -> query_processor -> storage_proxy -> database, when reading 
> system tables to bootstrap.
> 
> 
> One solution is to have two database instances (for system tables and 
> user tables), two storage_proxy instances, and two query_processor 
> instances. But this may not work well when we have multi-table 
> operations. Note that storage_proxy already special-cases system tables 
> since they are always local and don't follow the same ring topology as 
> other tables, and database has special memory areas and concurrency 
> limiters for system tables. Perhaps the user storage_proxy can have the 
> same special case, but instead of handling it directly, forward the 
> operations to the system storage_proxy.
> 
> 
> So we have
> 
>   user_query_processor -> user_storage_proxy
> 
>   user_storage_proxy -> messaging_service, user_database, 
> system_storage_proxy
> 
>   user_database -> system_query_processor
> 
>   system_query_processor -> system_storage_proxy
> 
>   system_storage_proxy -> system_database
> 
> 
> Notes:
> 
>   - no circular dependencies
> 
>   - system_storage_proxy only serves local tables, so it doesn't depend 
> on messaging_service

**Comment by bhalevy** [comment]
@xemul, this will be a good introductory project to get familiarized with the various services in the system.

**Comment by DoronArazii** [comment]
@xemul can we close it?

**Comment by xemul** [comment]
There should be a bunch of issues that aim at modernizing shutdown and I don't remember any of them :D So chances are that if we close yet another "stale" one of that kind we lose the context forever

**Comment by DoronArazii** [comment]
Okay, will keep this one open.

/Cc @bhalevy 

I'm raising the priority and targeting to 5.3 timeframe as we try to improve dtest stability.

**Comment by DoronArazii** [comment]
As it doesn't seem like we will get to it soon - reducing priority + removing to the backlog.

/Cc @bhalevy

**Comment by bhalevy** [comment]
This issue aged and can be closed.
We should open new, particular issues if shutdown hangs.
