### ISSUE TITLE
data directories permissions

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylladb#4395]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.4
Cluster size: -
OS (RHEL/CentOS/Ubuntu/AWS AMI): any

Scylla data folders and files have inconsistent permissions.

```
[centos@ip-172-31-4-242 ~]$ ls -al /var/lib/scylla/data/
total 8
drwxr-xr-x.  7 scylla scylla  120 Apr  3 08:21 .
drwxr-xr-x.  8 scylla scylla  121 Apr  3 08:15 ..
-rwx------.  1 scylla scylla    0 Apr  3 08:21 .lock
drwx------. 25 scylla scylla 4096 Apr  3 08:21 system
drwx------.  4 scylla scylla  105 Apr  3 08:21 system_auth
drwx------.  3 scylla scylla   64 Apr  3 08:21 system_distributed
drwx------. 14 scylla scylla 4096 Apr  3 08:21 system_schema
drwx------.  7 scylla scylla  277 Apr  3 08:21 system_traces
```

the keyspace and table directories (and all the subfolders) shall be `rwx` by scylla *group* members. I suggest that `/var/lib/scylla/data/` and all the subfolders are `770` for `scylla:scylla` and all the files are `440`.

**Comment by nyh** [comment]
In what sense are user-only permissions "inconsistent"?

By the way, the traditional Unix approach is that applications should not specifically choose permissions of new files and directory themselves. They create files and directory with 666 permissions for writable files or 444 for read-only files, like our sstable files, but the **umask** applicable to the process removes some of these permissions - e.g., remove the world permissions or the world and group permissions - depending on the choice of the user running the application (of course our package, AMI, or whatever can make a specific choice for this umask).

**Comment by mmatczuk** [comment]
@nyh my objective is to make users belonging to scylla group to be able to read the data (snapshots in particular). Setting different umask for scylla-server is maybe the way to fix it. The inconsistency is that 
`/var/lib/scylla/data/` is `drwxr-xr-x` while keyspace folders are `drwx------`.

**Comment by slivne** [comment]
@avikivity - any objections with group access privileges ?
@bhalevy  - I want to prioritize this - since scylla-manager 1.5 requires this

**Comment by mmatczuk** [comment]
Note that to restore as a group member it would have to be changed by adding write access.

**Comment by bhalevy** [comment]
Note that the default mode for creating directories is currently defined in seastar, not in scylla.

**Comment by bhalevy** [comment]
Now, with the seastar changes directories are created by default with 0777 permissions and files with 0666.

As discussed on scylladb-dev and suggsted by @avikivity and by @nyh above,
we want to set UMask in the .service file to mask group write permissions and all others permissions (UMask=0027), so files will be created as 0640 and directories as 0750.

The admin can change that, e.g. to 0007 if they want also group write permissions.

**Comment by bhalevy** [comment]
@slivne / @penberg who's the best person to assign this issue to?
Looks like @syuu1228 has done most of the work on scylla-server.service

**Comment by bhalevy** [comment]
We've been happy with the data directories permissions in the last years.
Closing as not planned.
