### ISSUE TITLE
Row-level Access Control

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#4411]
*Installation details*
Scylla version (or git commit hash): 3.1

Row-level Access Control (RLAC) allows setting granting different access (read, write/modify, no access) to different roles, **per a table partition and a table a row**

**Comment by tzach** [comment]
Similar features in other DBs
[Oracle](https://docs.oracle.com/middleware/12212/biee/BIEMG/GUID-031DAE26-1CEC-40D0-97E7-6EFA0E87377F.htm#BIEMG-GUID-031DAE26-1CEC-40D0-97E7-6EFA0E87377F)
[MongoDB](https://docs.mongodb.com/manual/tutorial/implement-field-level-redaction/)

**Comment by tzach** [comment]
Datastax (Enterprise) implements this using CQL RESTRICT
https://docs.datastax.com/en/dse/5.1/cql/cql/cql_reference/cql_commands/cqlRestrict.html

**Comment by tzach** [comment]
Closing, as not planed.

**Comment by ptrsmrn** [comment]
> Closing, as not planed.

This time I'm actually closing the Issue ;)

**Comment by nyh** [comment]
See also the newer issues https://github.com/scylladb/scylladb/issues/20400 for Alternator and https://github.com/scylladb/scylladb/issues/25807 for CQL. They are more general than this issue, and while the row-level access control is mentioned, it's probably not the main focus.
