### ISSUE TITLE
Scylla python driver fetches less than expected data from the scylla db

### ISSUE THREAD

**Issue by hemanthrough** [scylladb/scylladb#4475]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.5-0.20190414.403f66eca
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu
(Linux f1a3cce71cc9 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker 

When a scylla image is used in a docker container, using the command below

```
docker run -d --name scylla -p 9042:9042 scylladb/scylla

```

Then a the scylla db is connect via python driver. The insert statement of a large file is successful but retrieval of the same data file is not complete. To give some context the I split the input file into smaller chunks and then insert the chunks. Later I try to retrieve the chunks and then concatenate and get back the file.

Here is the code below for the same

```
from cassandra.cluster import Cluster
from cassandra.query import dict_factory
from cassandra.cluster import NoHostAvailable
from time import sleep

# small input file
#model_filename = 'path to less than 1MB '
# LARGE input file
model_filename = 'path to large more than 10MB' for example


# function to spilt a large file in to small size of ~1 MB
def create_chunks_from_bytes(bytes):
    chunk_size = 100000  # not a problem with the number of chunks works with a small file and lot chunks
    chunks = []
    while len(bytes) > 0:
        chunks.append(bytes[:chunk_size])
        bytes = bytes[chunk_size:]
    return chunks


data = {}
# read the data from the file
with open(model_filename, 'rb') as f:
    data = f.read()
# create a cluster
cluster = Cluster()
# connect to the cluster
cluster = Cluster(['172.17.0.2'], port=9042)
session = cluster.connect()
# create keyspace
query = "CREATE KEYSPACE IF NOT EXISTS test WITH replication = { 'class': 'SimpleStrategy', 'replication_factor': 1 }"
session.execute(query)
session.set_keyspace('test')
# delete the already existing table
query = """
            DROP TABLE test.data
        """
session.execute(query)

# create table with minimun params
query = """
            CREATE TABLE IF NOT EXISTS test.data (
                model_id int,
                chunk_number int,
                chunk_data blob,
                PRIMARY KEY (model_id, chunk_number)
            ) WITH CLUSTERING ORDER BY (chunk_number ASC)
            """
session.execute(query)


model_object = data
# split the data file into chunks
chunk_list = create_chunks_from_bytes(model_object)
# placeholder statement for the chunk insert
stmt = session.prepare("INSERT INTO test.data (model_id, chunk_number, chunk_data) VALUES (?, ?, ?)")
# hardcoding for test purpose
model_id = 1

# insert the spiltted chunks to scylla
for index, chunk in enumerate(chunk_list):
    # loading the params
    params = [model_id, index, chunk]
    # limiting the retries to 3 loop break condition
    retries = 3
    insert_successful = False
    # loop until successful
    while insert_successful is False:
        # insert into the db
        try:
            session.execute(stmt, params, timeout=None)
            insert_successful = True
        except Exception as e:
            retries = retries - 1
            sleep(1)
            if retries == 0:
                raise Exception(e)
# fetch the inserted data
stmt = "SELECT * FROM test.data WHERE model_id = %s"
params = [model_id]
rslt = session.execute(stmt, params, timeout=None)
# check the results
print("no of chuch retrived from db +"str(len(rslt._current_rows)+", this should be the same: "+str(len(chunk_list))))



```

It may work if we change something in the configuration but we don't exactly know which value we have to change.
Or 
May be there  another way to  retrieve a large data query.  If thats is case kindly point me to the right resource.

**Comment by hemanthrough** [comment]
Hello all,

Any updates on this issue. 

any help in this regard would be appreciated

**Comment by denesb** [comment]
@hemanthrough what is the difference between the expected and actual number? Is the retrieved data a prefix of the actual data? Have you tried querying your table through `cqlsh`?

**Comment by hemanthrough** [comment]
Hi @denesb 

1. expected (records inserted into the DB) and actual (one I get from the python driver). The difference is 100 and 10
(Note the no of records fetched, depends on the size of records inserted, smaller the size of record more the number of  records fetched)

2. The retrieved data is small percentage of records to be satisfying the query condition.

3. yes, querying through cqlsh gives the correct number of records

**Comment by denesb** [comment]
@hemanthrough You have 100K rows and you get back 10 of them. It appears that paging kicks in and you get a single page back (we have an internal 1MB limit for page size). You should read all the pages the query returns.

**Comment by hemanthrough** [comment]
Hi @denesb

Thank you for the update, I dint think about paging. It works fine now. I am closing this issue.
