### ISSUE TITLE
system_traces tables schema are not updated when upgrading to scylladb 3.0

### ISSUE THREAD

**Issue by Skunnyk** [scylladb/scylladb#4601]
Hello,

After a successful upgrade from ScyllaDB 2.3.5 to ScyllaDB 3.0 on a test cluster, I can't use `tracing on` command anymore.

```
 scylla:  [shard 0] trace_keyspace_helper - Tracing is enabled but system_traces.sessions doesn't meet expected schema: Unknown identifier request_size
```
The table system_traces.sessions does not have the `request_size` field, which as been introduced in scylladb 3.0 with `response_size`: https://docs.scylladb.com/using-scylla/tracing/ 

It looks like the script https://github.com/scylladb/scylla/blob/master/fix_system_distributed_tables.py needs to be run to update system_traces and system_auth keyspaces after scylladb upgrade, but it's not referenced anywhere in the documentation, and is not included in debian package (haven't looked for other distro).
After installing `python-cassandra` debian package and a script run, all is right:

```
# python fix_system_distributed_tables.py --node $(hostname)                                                                                           
Adjusting system_traces.node_slow_log
Adjusting system_traces.events
Adjusting system_traces.sessions
system_traces.sessions: added column 'response_size' of the type 'int'
system_traces.sessions: added column 'request_size' of the type 'int'
system_auth.credentials doesn't exist - skipping
system_auth.users doesn't exist - skipping
system_auth.permissions doesn't exist - skipping
```

*Installation details*
Scylla version (or git commit hash): 3.0.7-0.20190528.4c16c1fe1-1~stretch
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian Stretch

**Comment by slivne** [comment]
@vladzcloudius - should we run this after all the nodes have been upgraded / or should we run this when the first node is installed ?

**Comment by slivne** [comment]
@syuu1228 lets start by adding pakcaging so it will be installed and then see if this is a DOCs item or something that we should run in post phase of package being installed.

**Comment by syuu1228** [comment]
Fixed by https://github.com/scylladb/scylla/commit/cbaea172cd78792cfdb3c196f6a248f21615865e

**Comment by vladzcloudius** [comment]
> @vladzcloudius - should we run this after all the nodes have been upgraded / or should we run this when the first node is installed ?
> 
> There is a small issues related to running it after the first node - what happen if rollback

@slivne If there is a rollback - there is no issue. If there are extra columns the prepared statement will just work ignoring extra columns (there will be a `null` values in them).

**Comment by vladzcloudius** [comment]
@slivne Do we include this script in every distribution variant these days?
If yes, let's close this issue.

**Comment by slivne** [comment]
@syuu1228 do we add the script to the distribution ?

**Comment by penberg** [comment]
@slivne @syuu1228 I don't think we do. At least I wasn't able to find reference to the `fix_system_distributed_tables.py` script in our packaging files...

**Comment by syuu1228** [comment]
fix_system_distributed_tables.py added at https://github.com/scylladb/scylladb/commit/76519751bc4745317b4e4b0c479cb3649eb26a78, closing.
