### ISSUE TITLE
Single-node boot is slow

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#4632]
When I start a single Scylla node for tests (dev build), it takes a surprisingly long amount of time, e.g., in one run it took 37 seconds:
```
INFO  2019-07-01 18:08:22,590 [shard 0] init - Scylla version 9999.enterprise_dev-0.20190624.12899060e starting.
INFO  2019-07-01 18:08:59,386 [shard 0] init - Scylla version 9999.enterprise_dev-0.20190624.12899060e initialization completed.
```

This 37 second delay is not the end of the world, of course, but it's also quite annoying for interactive development - and I'm sure user's don't appreciate unnecessary delay as well.

This measurement is for booting without existing data, only one shard and 1GB of memory, and I used "-ring-delay-ms 4000" which someone told me in the past will reduce delays at boot. There is no other node in the system.

If I analyze boot logs, I see:

1. First 2 seconds - various things happen, let's ignore this part for now.
2. Next 11 seconds - absolutely nothing in the log, apparently some gossip-related delay ending with "gossip - No gossip backlog; proceeding". How can I reduce this wait?
3. Next 12 seconds - tons of sstable creations, compactions, etc for system tables. Tables like dropped_columns and keyspaces get compacted as many as 24 times. I can understand we need to write some system tables on first boot, but does it really need to take 12 seconds? Do we really need to flush the data to disk 24 times instead of just once? This step doesn't happen on second boot, which takes "only" 25 seconds.
4. Next 9 seconds - nothing happens except one message "standard_role_manager - Created default superuser role 'cassandra'.". This slow period is again ended with a "gossip - No gossip backlog; proceeding".

**Comment by asias** [comment]
I had a patch in the past. Do not have time to revisit it. 

```
    gossip: Make boot process faster and safer
    
    During boot up, we need to wait for gossip in 3 places:
    
    1) Wait until local node knows tokens of peer nodes before announcing
    join status. To make sure when the writes sent by the other nodes for
    pending token range arrives, the local node knows all the tokens of the
    cluster. See commit 89b769a073da1a1727b913159d85b97fe911676c.
    
    2) Wait until peer nodes know the bootstrap tokens of local node before
    streaming. To make sure all peer nodes knows the pending token range
    before the streaming starts, so that all writes after streaming starts
    that belong to the pending token range will be forwarded to the new node.
    
    3) Wait until gossip is settled before start the cql server. See commit
    8c909122a6a6b90ddb50ea8be250829c199616ab.
    
    Before this patch, we sleep ring_delay which is 30 seconds by default
    and wait for the size of endpoint_state_map does not change over some
    time. The time out based approach does not guarantee the above 3
    conditions are met. It can wait foo much or wait too few.
    
    This patch introduces a new method. Instead of waiting for some
    arbitrary time, we ask peer nodes to return the number of nodes it
    knows, the checksum of normal tokens, the checksum of bootstrap tokens
    and the checksum of gossip status (e.g., NORMAL). If the checksums
    between local node and all remote nodes are identical, it is guaranteed
    all nodes have the same view of tokens and nodes status.
    
    A new RPC verb GOSSIP_QUERY is introduced for this new method. If any of
    the nodes in the cluster does not support this new verb, it will
    fallback to the old timeout based method. A nice thing is we do not need
    to negotiate between nodes if GOSSIP_QUERY is supported. When the node
    that supports GOSSIP_QUERY send this verb to node that does not support
    it during boot process, the sender will get rpc::unknown_verb_error then
    it will fallback.
    
    With this patch, we observed significant improvement in scylla boot time.
    
    To bootstrap a single node with the default 30s ring_delay:
    Before: 88 seconds
    After: 4 seconds
    
    To run update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_node_1_test
    Before: 141 seconds
    After: 25 seconds
    
    To run update_cluster_layout_tests.py:TestLargeScaleCluster.add_50_nodes_test
    to increase a cluster from 3 nodes to 12 nodes
    Before: 866 seconds
    After: 111 seconds
```

**Comment by nyh** [comment]
Unfortunately, in the 6 months that passed, this issue did not improve.
I retested today on the same machine - a single-node Scylla boot time  is now 37 seconds (1 shard) to 43 seconds (3 shards).
One of the things which were added recently was CDC, which apparently tries (and fails) for about 3 seconds to generate its streams (that 99.9% of the tests will never want to use anyway).

This slow boot time adds a huge amount of time to dtests, and is even more frustrating for alternator-test during development - there a test often takes just one second, but you end up waiting 43 seconds just to boot Scylla after each fix. The very slow boot of Scylla is also one of the things which caused us to start using (see `test/cql`)  a special "cql repl" executable for testing instead of the ordinary scylla executable.

**Comment by asias** [comment]
@nyh "gossip: Make boot process faster and safer #5154" will help a lot but it is not merged.

**Comment by nyh** [comment]
In Issue #6310 I discovered that adding the "--skip-wait-for-gossip-to-settle 0" option completely eliminates the gossip delays and make Scylla boot in less than a second. It would still have been nice for the speed to be automatic, and not require a special option.

**Comment by rahultaing** [comment]
@avikivity @slivne can one of you help me understand the downside of using this `--skip-wait-for-gossip-to-settle ` on a 3 node cluster?

**Comment by nyh** [comment]
It is now possible, with judicious use options, to boot a single-node Scylla in a fraction of a second - on my laptop `test/cql-pytest/run`, which runs Scylla, boots it (i.e., gets to working CQL) in a mere 0.3 seconds!

So I'm tempted to close this issue. Although it would have been even better for boot to be faster also by **default**, not requiring weird options...

**Comment by congguosn** [comment]
Wonder if it is safe to set "--skip-wait-for-gossip-to-settle" to 0 in a real cluster?

**Comment by kostja** [comment]
With raft based topology changes it is safe. Currently available in master --experimental-features=consistent-topology-changes.

**Comment by avikivity** [comment]
> With raft based topology changes it is safe. Currently available in master --experimental-features=consistent-topology-changes.

It should override the setting then by itself.

**Comment by bhalevy** [comment]
Can this issue be closed with raft consistent-topology-changes?

**Comment by nyh** [comment]
> Can this issue be closed with raft consistent-topology-changes?

I don't know, @kbr-scylla please consider if this issue should be closed.

As I noted above in 2020, I found ways to speed up the boot passing in special options, and used them in cql-pytest and later in all other test frameworks (including dtest, for single-node tests). So the reason why this issue remains is just about the **default user experience**: Whether running Scylla without any special options - e.g., the Docker examples we have in our documentation - Scylla still waits 37 seconds doing absolutely nothing on "gossip" waits.

**Comment by kbr-scylla** [comment]
I think there are at least two prerequisites for closing this issue:
- https://github.com/scylladb/scylladb/issues/16055
- and making raft-topology non-experimental.

**Comment by mykaul** [comment]
> I think there are at least two prerequisites for closing this issue:
> 
> * [Ignore skip_wait_for_gossip_to_settle if consistent-topology-changes is ON #16055](https://github.com/scylladb/scylladb/issues/16055)
> * and making raft-topology non-experimental.

Both done - @kbr-scylla - can we close this as completed?

**Comment by kbr-scylla** [comment]
Yes
