### ISSUE TITLE
Try out lto

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#465]
For the lulz, enable -flto and see what it buys us.

**Comment by glommer** [comment]
@avikivity still relevant ?

**Comment by avikivity** [comment]
Yes.

**Comment by michoecho** [comment]
Enabled -flto for the lulz. Got 6%-10% throughput increases (in cassandra-stress benchmarks) across the board, depending on the workload. And compile time didn't become super long either – only 30-40 minutes or so.

Do we have any reasons not to use it for releases?

**Comment by michoecho** [comment]
To make LTO work, I had to remove the fallback versions of array_search functions, like so:
```diff
diff --git a/utils/array-search.cc b/utils/array-search.cc
index 60afc108a..c976eaa1a 100644
--- a/utils/array-search.cc
+++ b/utils/array-search.cc
@@ -30,41 +30,6 @@
 
 namespace utils {
 
-arch_target("default") int array_search_gt_impl(int64_t val, const int64_t* array, const int capacity, const int size) {
-    int i;
-
-    for (i = 0; i < size; i++) {
-        if (val < array[i])
-            break;
-    }
-
-    return i;
-}
-
-static inline unsigned array_search_eq_impl(uint8_t val, const uint8_t* arr, unsigned len) {
-    unsigned i;
-
-    for (i = 0; i < len; i++) {
-        if (arr[i] == val) {
-            break;
-        }
-    }
-
-    return i;
-}
-
-arch_target("default") unsigned array_search_16_eq_impl(uint8_t val, const uint8_t* arr) {
-    return array_search_eq_impl(val, arr, 16);
-}
-
-arch_target("default") unsigned array_search_32_eq_impl(uint8_t val, const uint8_t* arr) {
-    return array_search_eq_impl(val, arr, 32);
-}
-
-arch_target("default") unsigned array_search_x32_eq_impl(uint8_t val, const uint8_t* arr, int nr) {
-    return array_search_eq_impl(val, arr, 32 * nr);
-}
-
 #ifdef __x86_64__
 
 /*
```
because he linker was screaming something about undefined hidden symbols otherwise.

**Comment by avikivity** [comment]
When I tried it I got a regression, but that was a long time ago (in the gcc days).

The problems with lto are related to unit tests, since now each unit test will compile the entire source base:
1. how much does the compile time for release-build increase?
2. the unit tests are now less faithful to the runtime binary since the compiler can generate different code

Since we also test with dev and debug I'm willing to ignore 2. But if the compile time regression is horrendous, we'll have to think.

**Comment by michoecho** [comment]
> 1. how much does the compile time for release-build increase?

I only built release-dist. release-build is building right now, we'll see.

> But if the compile time regression is horrendous, we'll have to think.

Why, though? Can't we just enable it only for the final QA and release, to get a neat bonus for free? I think that's the sane way of using super-expensive optimizations.

**Comment by psarna** [comment]
Is lto likely to mess up debugging coredumps, or does it generate all the correct symbols? Maybe we should also verify that scylla-gdb.py is still operable on an optimized binary.

**Comment by michoecho** [comment]
@avikivity While we are at it, what about profile-guided optimization? I see Paweł Dziepak was experimenting with it:  https://twitter.com/PawelDziepak/status/1025065997584293888, apperently with good results. Why aren't we using it after all?

**Comment by avikivity** [comment]
> 
> > But if the compile time regression is horrendous, we'll have to think.
> 
> Why, though? Can't we just enable it only for the final QA and release, to get a neat bonus for free? I think that's the sane way of using super-expensive optimizations.

We can (esp. with profile-guided optimiztions, which will add maybe another two hours to the build). The risk is that we'll discover bugs late (or worse, not discover bugs). Maybe we can have a weekly build with lto+pgo on which most QA is done (this means that we'll introduce more QA lag, but maybe we can live with it).

**Comment by avikivity** [comment]
> @avikivity While we are at it, what about profile-guided optimization? I see Paweł Dziepak was experimenting with it: https://twitter.com/PawelDziepak/status/1025065997584293888, apperently with good results. Why aren't we using it after all?

No one sent a patch.

**Comment by michoecho** [comment]
> The risk is that we'll discover bugs late (or worse, not discover bugs).

Well, the final binary would be exercised less, but the source code would be exercised more.

**Comment by nyh** [comment]
@michoecho created this pull request: https://github.com/scylladb/scylladb/pull/10808

**Comment by DoronArazii** [comment]
@mykaul are we planning to have this on 5.2?

**Comment by nyh** [comment]
@michoecho @avikivity - I think we already did this (in the Enterprise branch), and can close this issue - right?

**Comment by michoecho** [comment]
> [@michoecho](https://github.com/michoecho) [@avikivity](https://github.com/avikivity) - I think we already did this (in the Enterprise branch), and can close this issue - right?

Yes. Closing.
