### ISSUE TITLE
nodetool cleanup effects may be partially reverted after an unclean restart

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#4734]
`nodetool cleanup` is supposed to drop writes not owned by the current node, so that it's safe to perform further cluster membership changes after adding a node.

Nodetool cleanup works by rewriting sstables. However, commitlog segments may still contain the writes which are dropped during sstable rewriting. Upon commitlog replay after an unclean restart, the effects of `nodetool cleanup` will be partially reverted when those writes are reapplied.

**Comment by tgrabiec** [comment]
If we flushed all memtables in the system, we would be currently ok (in the absence of LWT). But looking at the code, I think we don't. Looking at the code, we don't even seem to be flushing memtables for the target keyspace. @raphaelsc is that the case?

**Comment by tgrabiec** [comment]
I think that flushing memtables is actually not enough. Suppose this happens:

1. Memtable flush starts
2. New write is committed to the commit log segment which contains writes supposed to be cleaned up
3. Flush completes, releases replay positions, but the segment stays because of a later write
4. Node restarts, writes are brought back

**Comment by bhalevy** [comment]
writes can happen after cleanup starts.
since we don't have a barrier that will fence off writes to disowned range once the change in token metadata was commiited, I think we can only require cleanup of anything written up until when cleanup started.
With flushing the memtables, can the flushed data be played back on restart?

**Comment by tgrabiec** [comment]
I think we're safe (modulo the current reliance on sleeps for token metadata propagation) with regards to writes to disowned ranges, since coordinators are working with the new topology, and should not send writes to the old replica.

I'm worried about the fact that flushing memtables doesn't really guarantee that anything at all is released from the commit log.

**Comment by tgrabiec** [comment]
@elcallio, is that the case?

**Comment by bhalevy** [comment]
> I'm worried about the fact that flushing memtables doesn't really guarantee that anything at all is released from the commit log.

That would also be a problem for tombstone purging, no?
Can commitlog replay resurrect data?

**Comment by tgrabiec** [comment]
> That would also be a problem for tombstone purging, no?

Yes, that's the primary reason we need to cleanup.

**Comment by tgrabiec** [comment]
But if you're asking whether tombstone purging should consider data in commit log then, no, it doesn't have to, because the data is also in sstables.

**Comment by tgrabiec** [comment]
> But if you're asking whether tombstone purging should consider data in commit log then, no, it doesn't have to, because the data is also in sstables.

Actually, it could happen that the write landed in the commitlog but failed when being applied to the memtable, so it's only in the commitlog. A later repair should fix that, unless the write is only in the commitlog on all replicas.

**Comment by mykaul** [comment]
Targeting 5.4 (since it is needed for tablets).

**Comment by denesb** [comment]
Can we add a filtering phase to commitlog replay, dropping data not owned by the node?

**Comment by bhalevy** [comment]
> Can we add a filtering phase to commitlog replay, dropping data not owned by the node?

I'm not sure we've settled on the owned token ranges at this point.

But if we can load the (local) system tables first and replay their commit logs (using the full range as locally owned), we could read the tokens from system.topology or system.local and system.peers, if consistent topology changes are disabled, and use that to load the non-system tables and replay their commitlog with the latest information we have about the node's owned tokens.

**Comment by tgrabiec** [comment]
With topology on raft, token metadata is available before replaying user tables, so we can use it. With non-raft topology, it's available later, after ss.local().join_cluster().

**Comment by tgrabiec** [comment]
Another option is to implement a flush which guarantees that prior writes are not replayed, by closing active segments and flushing all memtables which pin those segments, then deleting/recycling the segments.

**Comment by raphaelsc** [comment]
> Another option is to implement a flush which guarantees that prior writes are not replayed, by closing active segments and flushing all memtables which pin those segments, then deleting/recycling the segments.

One of the problems with this solution is that we may flush really small memtables, which increases write amplification.

**Comment by raphaelsc** [comment]
> Can we add a filtering phase to commitlog replay, dropping data not owned by the node?

I think this may be fragile

Consider this

1) tablet is migrated away, but cannot release its commitlog segments as they're pinned by other users
2) the data in commitlog is deleted in new destination
3) tablet is migrated back
4) segments containing deleted data stay pinned till tablet is back
5) on restart, commitlog replays deleted data as it's owned.

**Comment by bhalevy** [comment]
> Another option is to implement a flush which guarantees that prior writes are not replayed, by closing active segments and flushing all memtables which pin those segments, then deleting/recycling the segments.

Agreed. f42eb4d1ce321e93b934ce23e128af29d23d66f8 in combination of be763bea34094281de7e3b5dd8a5ac3e7a27d43c allow that.

See 3ed6925673dea88a5fe157f6239b98d60ec1690a for how it's used for major compaction.
We can follow exactly the same lines for cleanup, including a global `nodetool cleanup` api on all keyspaces that will flush all tables once and then cleanup each keyspace.

**Comment by bhalevy** [comment]
@tchaikov please add to your queue.

Adding also the tablets label/project as @tgrabiec mentioned it is a prerequisite for tablets cleanup

**Comment by bhalevy** [comment]
> > Another option is to implement a flush which guarantees that prior writes are not replayed, by closing active segments and flushing all memtables which pin those segments, then deleting/recycling the segments.
> 
> Agreed. [f42eb4d](https://github.com/scylladb/scylladb/commit/f42eb4d1ce321e93b934ce23e128af29d23d66f8) in combination of [be763be](https://github.com/scylladb/scylladb/commit/be763bea34094281de7e3b5dd8a5ac3e7a27d43c) allow that.
> 
> See [3ed6925](https://github.com/scylladb/scylladb/commit/3ed6925673dea88a5fe157f6239b98d60ec1690a) for how it's used for major compaction. We can follow exactly the same lines for cleanup, including a global `nodetool cleanup` api on all keyspaces that will flush all tables once and then cleanup each keyspace.

@avikivity noted that this could be too expensive for a relatively common event like tablet migration.
We need to continue the discussion on this matter.

**Comment by bhalevy** [comment]
Quoting from [tablets design doc](https://docs.google.com/document/d/1uvJV_0MgMiRJJFM7_CVgS42VKV_zYGjizFkLAioSNmk/edit):
> When replaying the commit log, we should look at the current token metadata and drop writes which are not owned by the node. Writes which are owned, should be replicated to the owning shard(s). If the tablet is transitioning within the node, it can be owned by two shards. The mutations should be replicated to both.
>
> This is not enough to ensure that cleaned up writes don’t get resurrected. The node could have regained ownership of the tablet while the write sits in the commitlog. To protect against this, we can reuse the current mechanism for fencing writes when truncating the table, but make it per token range. See database::truncate().

**Comment by tchaikov** [comment]
> > Can we add a filtering phase to commitlog replay, dropping data not owned by the node?
> 
> I think this may be fragile
> 
> Consider this
> 
>     1. tablet is migrated away, but cannot release its commitlog segments as they're pinned by other users
> 
>     2. the data in commitlog is deleted in new destination
> 
>     3. tablet is migrated back
> 
>     4. segments containing deleted data stay pinned till tablet is back
> 
>     5. on restart, commitlog replays deleted data as it's owned.

i am visualizing the time sequence above as a diagram to help myself understand this use case better:

```mermaid
sequenceDiagram
    participant node.1
    participant node.2
    critical [commit log segments of tablet.42 are pinned]
        node.1->>node.2: migrate tablet.42 to
        node.2-->>node.2:  data deleted in commit log
        node.2->>node.1: migrate tablet.42 back
    end
    node.1-->>node.1: restart
    Note right of node.1: deleted data is resurrected, and the tablet.42 is owned by node.1
```

**Comment by tchaikov** [comment]
just had a discussion with @bhalevy on this issue, he proposed a solution which addresses the resurrected data in quite the same way as `db::commitlog_replayer`. i am trying to summarize it here for future discussions:

we will have a system table like `system.truncated` which has following columns:

- table uuid
- token range
- segment id

when a node loses its ownership of a given tablet, it inserts a row into this table, with

- the table owning this tablet
- the tablet's range (so we are prepared for dynamic tablets number)
- the last segment id of commit log marking the upper bound of a segment range

when the node restarts, it replays the commit log on disk. it checks every segment in the commit log, if a segment is "covered" by any of the rows in the table, the segment is skipped.

**Comment by bhalevy** [comment]
I'm inclined to open a new issue for safe tablets post-migration cleanup, if we end up with different solution for tablets vs. vnodes (where the latter can use the method we use for major compaction of forcing new active segment + flushing all/or tables pinning segments, when invoke from the api).

Currently, system.truncated schema is:
```
        // partition key
        {{"table_uuid", uuid_type}},
        // clustering key
        {{"shard", int32_type}},
        // regular columns
        {
                {"position", int32_type},
                {"segment_id", long_type}
        },
        // static columns
        {
                {"truncated_at", timestamp_type},
        },
```

Can we extend it by adding clustering columns for the token range or do we need to keep that in a new system table?

@michoecho, how about adding a timestamp column for truncate purposes as a truncate tombstone?

**Comment by denesb** [comment]
@bhalevy can we rewrite+cleanup commitlog files during cleanup, the same way we do sstables? Then we don't need to store anything, we know cleanup left the shard in a safe state.

**Comment by elcallio** [comment]
Trying to use RP:s for tables require you to ensure any ranges operated on are congruent between the CL and tablet/memtable operations. Which I imaging they won't be in the case of tablet migration. I.e. storing something like "truncated" for a range of mutations will not work, because mutations belonging to a different "token range" might be intermixed and would be lost. 
Adding a "token range" to truncation might work, but this must be applied in the mutation run, not the replay itself (since it has no idea of what data is). This is assuming that the mark still works as watershed, not a range. 
 Long way of saying "timestamp" will not do you any good. (And also user timestamps).

**Comment by bhalevy** [comment]
> Trying to use RP:s for tables require you to ensure any ranges operated on are congruent between the CL and tablet/memtable operations. Which I imaging they won't be in the case of tablet migration. I.e. storing something like "truncated" for a range of mutations will not work, because mutations belonging to a different "token range" might be intermixed and would be lost.

I'm a bit lost :)

The tablets scheduler serializes the operations on a given tablet using a persistent state machine.
For tablet migration, conceptually there is:
- start migration:
  - create destination tablet replica
  - read old, write both
  - take snapshot on source
  - stream from source to destination
- commit migration:
  - read new, write new
  - (at this point nothing should be written to the source node for the tablet token range)
- cleanup:
  - force new active commitlog segment
  - flush table
  - invalidate cache
  - calculate replay position
  - delete all sstable files belonging to the tablet replica (a.k.a. compaction group)
  - PROPOSED STEP: write truncated token range to system.truncate given the table_id, shard, tablet replica token range, replay_position
  - cleanup phase done

There is a bit of a hassle when and how to purge the record in system.truncate
Maybe after the relevant commitlog segments are recycled, and/or after restart and replay we can purge those records.

> Adding a "token range" to truncation might work, but this must be applied in the mutation run, not the replay itself (since it has no idea of what data is).

Maybe we can teach replay to be token aware.
How does it apply the per-table replay position today?

> This is assuming that the mark still works as watershed, not a range. Long way of saying "timestamp" will not do you any good. (And also user timestamps).

The timestamp is for logical truncation usage, not for cleanup.
The idea is to use it to "seed" the partition tombstone for all partitions in the token range for mutation readers (including cache, memtable, sstables) so to logically apply the truncate before physically deleting any data.
The run a truncate/major compaction that will drop any sstable that is fully truncated based on this timestamp, and rewrite others that may have data straddling the truncate timestamp so to filter out any truncated data and leave only the live data.

**Comment by elcallio** [comment]
> The tablets scheduler serializes the operations on a given tablet using a persistent state machine. For tablet migration, conceptually there is:
> 
Assuming CL entries are still per table, not per tablet, you will/can still have overlapping RP ranges for different token ranges. 
If you move to marking CL entries per tablet, this can indeed be ignored, but assuming that tablet migration/splitting etc will alter tablet location for data that is potentially candidates for replay, I would still say you need to token filter the output of replay. 


>       * PROPOSED STEP: write truncated token range to system.truncate given the table_id, shard, tablet replica token range, replay_position
>       * cleanup phase done
> 
Yup. The token range being the salient factor. 
> 
> There is a bit of a hassle when and how to purge the record in system.truncate Maybe after the relevant commitlog segments are recycled, and/or after restart and replay we can purge those records.
> 
They can be purged after a clean restart (like truncation records are today). This can also be enhanced so you remove them if you can guarantee that all CL entries pertaining to data related to token range and table is gone. This is trickier, but can more or less be handled by the same mechanism as the tombstone GC lockout - i.e. look at GC time of CL entries (stored as worst-case in segments). 

> > Adding a "token range" to truncation might work, but this must be applied in the mutation run, not the replay itself (since it has no idea of what data is).
> 
> Maybe we can teach replay to be token aware. How does it apply the per-table replay position today?
> 
Replay is replay. No need to make it more weird/heavily coupled. Just filter on the mutation apply side. Same thing, nicer layering. 

> > This is assuming that the mark still works as watershed, not a range. Long way of saying "timestamp" will not do you any good. (And also user timestamps).
> 
> The timestamp is for logical truncation usage, not for cleanup. The idea is to use it to "seed" the partition tombstone for all partitions in the token range for mutation readers (including cache, memtable, sstables) so to logically apply the truncate before physically deleting any data. The run a truncate/major compaction that will drop any sstable that is fully truncated based on this timestamp, and rewrite others that may have data straddling the truncate timestamp so to filter out any truncated data and leave only the live data.

This is more or less how RPC truncation works today. This is fine. My point was only that this time stamp cannot be compared to/used in any reliable way with the CL storage.

**Comment by bhalevy** [comment]
> @bhalevy can we rewrite+cleanup commitlog files during cleanup, the same way we do sstables? Then we don't need to store anything, we know cleanup left the shard in a safe state.

How? there is no way to rewrite commitlog segments AFAIK.
What we could do is selectively flush the tables that pin down the CL segments after forcing a new live segment. This will cause those segments to get recycled and not replayed on restart.

@elcallio do we have a way to do that selective flushing, maybe based on the same infrastructure you planned for timeout based flushing?

**Comment by denesb** [comment]
> > @bhalevy can we rewrite+cleanup commitlog files during cleanup, the same way we do sstables? Then we don't need to store anything, we know cleanup left the shard in a safe state.
> 
> How? there is no way to rewrite commitlog segments AFAIK.

I don't think it would be too hard to add: replay CL, but instead of applying mutations to memtable, just write them to new CL file. Except those mutations that the node no longer owns. Sounds easier then the complicated logic discussed above.

**Comment by tchaikov** [comment]
it's like a mini game of catching the flying arrow (AKA, recovery). because commit log is being consistently appended as there are write ops coming in, when we're filtering it. so, in theory, we would need to have a write barrier to sync the filtered commit log with the one being appended.

**Comment by elcallio** [comment]
To do partial replay/filtering you would have to drop some segments out of the normal life cycle for a while, first ensuring they are completed etc. Not super complex in truth. But question on whether it is easier than just the extended truncation table approach.

**Comment by bhalevy** [comment]
> it's like a mini game of catching the flying arrow (AKA, recovery). because commit log is being consistently appended as there are write ops coming in, when we're filtering it. so, in theory, we would need to have a write barrier to sync the filtered commit log with the one being appended.

That's a good point.
Even after forcing new active segment, if you want to stop writers (memtables) appending to existing segments you should flush them, but once you did that, you can just proceed with truncate / tablet cleanup and you're done.  No more filtering would be needed.

**Comment by bhalevy** [comment]
@elcallio please see my question above (https://github.com/scylladb/scylladb/issues/4734#issuecomment-1884236854)

**Comment by elcallio** [comment]
Not sure I understand the question? Can you do selective memtable flush? Yes. Can you get info on which tables are keeping CL stuff alive. Yes.

**Comment by bhalevy** [comment]
> Not sure I understand the question? Can you do selective memtable flush? Yes. Can you get info on which tables are keeping CL stuff alive. Yes.

Awesome.  Can you please point to an example or the functions we need to call to achieve that?
(I apologize for being lazy and not doing the research myself, it's just that we joggling a lot of balls at the same time right now)

**Comment by elcallio** [comment]
There is no query function at this time (because noone needed it), but the information is stored such that given a segment ID, you can easily retrieve which tables (or data UUID:s really) are currently keeping it alive. The salient point being the `_cf_dirty` map in each segment, which holds the usage count mapping data UUID to number of entries in the segment. Flush callback respective entries, and one the map is empty/all zero a segment is clean and can be released.

**Comment by elcallio** [comment]
> @elcallio hi Calle, thank you for the pointers! i noticed that you were using notation like "RP:s" and "UUID:s". could you help me understand what ":s" stands for?

Plural. They are legion, for they are many... :-)
 
> IIUC, the write ops should go to commit log first, and then mutate the memtables. so, if we are allowed to start a new active segment upon losing the ownership of tablets which contains the mutations in the current active commit log, the previous active one should be flushed, so that the dirty mutations are persisted into sstables. the downside of this approach is just that the overhead of extra flushes.

Two problems:  
1.) A segment will hold data from N tables, which means to fully clean and remove it, you might need to flush all these tables. 
2.) Ordering: You pretty much need to ensure the tablet contents is persisted to sstable and evacuated from CL _before_ loosing ownership/moving data elsewhere. Or at least before the dreaded "move back". Otherwise you could crash in the middle of the procedure and face the exact problem you try to avoid.

**Comment by tchaikov** [comment]
Calle, thank you for your insights. ! i see. seems we are going with the "extending system.truncated" solution when handling tablets case. guess the flush-and-cleanup will be plan B now.

**Comment by bhalevy** [comment]
> Calle, thank you for your insights ! i see. seems we are going with the "extending system.truncated" solution when handling tablets case. guess the flush-and-cleanup will be plan B now.

@tchaikov it's not plan B, but rather a conplimentary change focused on vnode-based keyspaces and also backportable to release branches.
While the system.truncated extension fits the ad-hoc cleanup of singular tablets.  It's not a good solution for vnodes as is (maybe if we allow a null table_id to act as a wild card, but even with that it won't be backported.
