### ISSUE TITLE
Add admission control to the thrift server

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#4826]
*Installation details*
Scylla version (or git commit hash): 547c072f9306f90267d5dbc3bc49f019d8ac6008

Currently the thrift server does not have admission control. We should add one.

**Comment by tzach** [comment]
@gleb-cloudius why do we need this?

**Comment by psarna** [comment]
I started tackling this one, although the Thrift interface doesn't make it easy to pass additional parameters (like permits) to handlers. I hope I'll figure something reasonable out.

**Comment by psarna** [comment]
I recommend testing with https://github.com/scylladb/scylla/pull/8318 applied, otherwise unrelated crashes might occur.

**Comment by tzach** [comment]
@bhalevy is this part of 4.6?

**Comment by bhalevy** [comment]
> @bhalevy is this part of 4.6?

Forwarding the question to @psarna who authored 115324f71ab4263e127cd396e2c69f317fcc60e5

**Comment by psarna** [comment]
Looks like it is:
```bash
$ git log --oneline origin/branch-4.6 | grep partial\ admission\ control\ to\ Thrift
115324f71 Merge 'Add partial admission control to Thrift frontend' from Piotr Sarna
```

**Comment by psarna** [comment]
fix was merged a long time ago, closing
