### ISSUE TITLE
repair: Add ranges_parallelism option

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#4847]
In commit 131acc09cc1d568f994059736c8500adf5d05d88 (repair: Adjust
parallelism according to memory size), we choose the ranges to repair in
parallel according to the memory size automatically.

However, this automatic number might not the optimal one. For example,
user wants repair to have minimal impact on the user cql reads and
writes, or user wants to repair at full speed allowing more cpu and
memory resources.

We can add an option that controls number of ranges that we repair 
in parallel, so that the advanced user can control the parallelism.

**Comment by slivne** [comment]
@asias I know we have high latency links in the scope of row level repair being merged - AFAIK we did not select to provide a user control over this for row level repair and settled on a manner to make sure the links are utilized if possible.

How does this issue change align with those decisions ?

**Comment by asias** [comment]
In addition to choosing parallelism automatically, we agreed that a user control of the parallelism is useful and needed.

**Comment by asias** [comment]
Ping. The [PR](https://github.com/scylladb/scylla/pull/4848) was sent almost 2 months ago.
