### ISSUE TITLE
test_expired_liveness_with_limit_rf3 finds unexpected deleted keys in mv

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#4853]
This test shows flakiness where sometimes deleted keys appear when querying the view.
E.g. [dtest-release/170/testReport/materialized_views_test/TestMaterializedViews/test_expired_liveness_with_limit_rf3](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/170/testReport/materialized_views_test/TestMaterializedViews/test_expired_liveness_with_limit_rf3/)
[dtest-release/207/testReport/materialized_views_test/TestMaterializedViews/test_expired_liveness_with_limit_rf3](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/207/testReport/materialized_views_test/TestMaterializedViews/test_expired_liveness_with_limit_rf3/):
```
Error Message
Expected [[50, 50, 50], [99, 99, 99]] from SELECT k,a,b FROM mv, but got [[91, 91, 91], [50, 50, 50], [88, 88, 88], [82, 82, 82], [67, 67, 67], [79, 79, 79], [99, 99, 99], [73, 73, 73], [94, 94, 94], [85, 85, 85], [64, 64, 64], [76, 76, 76], [97, 97, 97], [70, 70, 70]]

Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2468, in test_expired_liveness_with_limit_rf3
    self._test_expired_liveness_with_limit(rf=3, nodes=3)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2497, in _test_expired_liveness_with_limit
    assert_all(session, "SELECT k,a,b FROM mv", [[50, 50, 50], [99, 99, 99]])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1175, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 78, in assert_all
    assert list_res == expected, "Expected %s from %s, but got %s" % (expected, query, list_res)
AssertionError: Expected [[50, 50, 50], [99, 99, 99]] from SELECT k,a,b FROM mv, but got [[91, 91, 91], [50, 50, 50], [88, 88, 88], [82, 82, 82], [67, 67, 67], [79, 79, 79], [99, 99, 99], [73, 73, 73], [94, 94, 94], [85, 85, 85], [64, 64, 64], [76, 76, 76], [97, 97, 97], [70, 70, 70]]
```

The node [logs](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/207/artifact/logs-release.2/1565780268328_materialized_views_test.TestMaterializedViews.test_expired_liveness_with_limit_rf3/) show no errors.

**Comment by bhalevy** [comment]
Cc @eliransin

**Comment by slivne** [comment]
still happens https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/414/testReport/materialized_views_test/TestMaterializedViews/test_expired_liveness_with_limit_rf3/

**Comment by bhalevy** [comment]
Still happens.  https://jenkins.scylladb.com/view/nexts/job/scylla-4.0/job/dtest-release/20/testReport/junit/materialized_views_test/TestMaterializedViews/test_expired_liveness_with_limit_rf3/

**Comment by DoronArazii** [comment]
Last hit was 3 years ago.

Closing as not planned as part of leaning the dtest issues list.

/Cc @bhalevy @eliransin
