### ISSUE TITLE
Alternator: implement UpdateTable

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#5022]
The UpdateTable request can be used for changing billing mode and provisioning (which we currently ignore, but should remember), to enable or disable streams (which we don't yet support), to change encryption-at-rest settings (which we don't currently allow to configure). But most importantly, it allows to add or delete global secondary indexes.

We have xfailing tests for this last issue: `test_gsi_backfill` and `test_gsi_delete` test adding a new GSI, and deleting a GSI, respectively.

**Comment by nyh** [comment]
Note that UpdateTable as a mechanism for configuring streams is already supported. The rest of the examples given above still aren't.

**Comment by zabawaba99** [comment]
Any update on the gsi backfill?

**Comment by nyh** [comment]
> Any update on the gsi backfill?

No, not yet. If there will be any work done on this, this issue will be the first place to record it.

**Comment by nyh** [comment]
When we implement adding a GSI to an existing table, we should remember that while the backfilling ("view building") is in progress, `DescribeTable` should return for this index `IndexStatus=CREATING` and `Backfilling=True`. We don't have a test for that yet (it's not obvious how to test for this, because the backfilling stage can be so short we won't notice it is happening. Perhaps we can use injection to ensure it is paused and only resumed when we want).

**Comment by nyh** [comment]
I created issue  #11567 specifically on adding and removing a GSI from an existing table.
I'll also create a separate issue about encryption-at-rest.
So closing this issue.
