### ISSUE TITLE
Alternator: missing fields in return of DescribeTable

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#5026]
The `DescribeTable` operation returns only a subset of the fields it's supposed to return. While this is enough for many use cases - which only use `DescribeTable` to tell when creating a table actually finished - it might not be enough in different use cases.

What is missing - with xfailing tests for each already in `alternator-test/test_describe_table.py`:

1. The table's schema in `KeySchema`, `AttributeDefinitions` (see `test_describe_table_schema`).
2. `ItemCount` (see `test_describe_table_item_count`).
3. `TableSizeBytes` (see `test_describe_table_size`).
4. `ProvisionedThroughput` (see `test_describe_table_provisioned_throughput`).
5. `ARN` (see `test_describe_table_arn`)
6. `TableId` (see `test_describe_table_id`)

Also `CreationDateTime` is returned incorrectly (see separate issue #5013).

Also `BillingModeSummary` we return is always the same thing (`PAY_PER_REQUEST`) regardless of what the user chose when creating the table. This is often good enough, but we should reconsider this.

Moreover, when there are indexes in a table (GSI or LSI), we only provide partial information for those too - see xfailing test `test_gsi_describe` (we should probably have a similar test for LSI as well).

The `DeleteTable` operation returns the return type as `DescribeTable`, so maybe should return additional values as well.

**Comment by tzach** [comment]
@nyh I do see 

```
"TableId": "dbfd89f0-d86a-11e9-b3a5-000000000002"
```
On the Alternator create table response

**Comment by nyh** [comment]
@tzach reported to the mailing list a case where the `AttributeDefinitions` field was expected and caused an application to fail:
[dynamodb-admin](https://github.com/aaronshaf/dynamodb-admin) is an open-source node base UI project for DynamoDB.
I was able to create a table with it, but I try to view the data, I got the following error message below. Scylla itself does not report any issue.

```
TypeError: /usr/lib/node_modules/dynamodb-admin/views/scan.ejs:106
    104|     >
    105|       <datalist id="attributes">
 >> 106|         <% for (let AttributeDefinition of Table.AttributeDefinitions) { %>
    107|           <option value="<%= AttributeDefinition.AttributeName %>" />
    108|         <% } %>
    109|       </datalist>

Table.AttributeDefinitions is not iterable
    at eval (/usr/lib/node_modules/dynamodb-admin/views/scan.ejs:59:46)
    at scan (/usr/lib/node_modules/dynamodb-admin/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/usr/lib/node_modules/dynamodb-admin/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/usr/lib/node_modules/dynamodb-admin/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/usr/lib/node_modules/dynamodb-admin/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/lib/node_modules/dynamodb-admin/node_modules/express/lib/application.js:640:10)
    at Function.render (/usr/lib/node_modules/dynamodb-admin/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/usr/lib/node_modules/dynamodb-admin/node_modules/express/lib/response.js:1012:7)
    at describeTable.then.description (/usr/lib/node_modules/dynamodb-admin/lib/backend.js:404:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by nyh** [comment]
`KeySchema`, `AttributeDefinitions` were done in commit 6672059543cb1880de9c65aca1dad1775df769e2 ("alternator: make DescribeTable return table schema"), but one small corner case remains (in a specific case involving a GSI) and moved to a separate issue #5320.

**Comment by fruch** [comment]
@nyh, I've encountered a real example that  6672059 is actually helps with
I've was playing with [pynamodb](https://github.com/pynamodb/PynamoDB)
and it does assume having the `KeySchema`
https://github.com/pynamodb/PynamoDB/blob/master/pynamodb/connection/base.py#L101

I was using scylla 3.2.0, hence didn't had that. I guess I should use the latest docker for my this specific experiment

**Comment by nyh** [comment]
The ARN in the response was also already fixed, in commit  8c17b5aec4ff471d7c9682f8b1bda2d1d9ba08d5

This issue is becoming a mess, it's hard to tell what is still missing. I should split it to separate items.

**Comment by nyh** [comment]
Created issue #7550 for ItemCount and #7551 for TableSizeBytes. This big issue should probably be closed now.

**Comment by nyh** [comment]
(work in progress comment... to be edited...)

Now we have individual issues about all remaining missing fields:
* https://github.com/scylladb/scylladb/issues/7550 for ItemCount in base tables and indexes, 
* https://github.com/scylladb/scylladb/issues/7551 for TableSizeBytes (for base tables)
* https://github.com/scylladb/scylladb/issues/11466 for IndexSizeBytes (for indexes)

    BillingModeSummary we return is always the same thing (PAY_PER_REQUEST) regardless of what the user chose when creating the table. This is often good enough, but we should reconsider this.
    When there are indexes in a table (GSI or LSI), we only provide partial information for those too - see xfailing test test_gsi_describe (we should probably have a similar test for LSI as well).
    The DeleteTable operation returns the return type as DescribeTable, so maybe should return additional values as well.

**Comment by ScyllaPiotr** [comment]
> We have individual issues about all remaining missing fields:
> - [Alternator: missing ItemCount field in return of DescribeTable #7550](https://github.com/scylladb/scylladb/issues/7550) for ItemCount in base tables and indexes,
> - [Alternator: missing TableSizeBytes field in return of DescribeTable #7551](https://github.com/scylladb/scylladb/issues/7551) for TableSizeBytes (for base tables)
> - [Alternator: missing IndexSizeBytes field in return of DescribeTable #11466](https://github.com/scylladb/scylladb/issues/11466) for IndexSizeBytes (for indexes)
> - [ Alternator: missing Projection field in return of DescribeTable #11470](https://github.com/scylladb/scylladb/issues/11470) for Projection (for indexes)
> - [ Alternator: missing IndexStatus field in return of DescribeTable #11471](https://github.com/scylladb/scylladb/issues/11471) for IndexStatus (for indexes)
> - [Alternator: missing fields in return of DeleteTable #11472](https://github.com/scylladb/scylladb/issues/11472) for missing fields in  `DeleteTable`'s response.
> 
> So closing this issue.

Almost a dup of scylladb/scylla-enterprise#2732 . At least the issues that are currently open are the same.
