### ISSUE TITLE
Alternator: support ACLs

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#5047]
After the request parser knows which user (“IAM”) of which account authenticated (see issue #5046), and which operation is attempted on which item, it can apply access control as defined for this account - e.g., an account may choose to let one user write to tables, but another user to only read them, via an access control policy. We can get ideas from DynamoDB’s access control policies described in detail [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/authentication-and-access-control.html).

In AWS, users can use the AIM API to control those accounts and policies, so we should probably support this API as well (since we don't have UIs yet).

**Comment by tzach** [comment]
@nyh as you know, Scylla already have [Roll Base Access Control](https://docs.scylladb.com/operating-scylla/security/rbac_usecase/) we can use.

**Comment by nyh** [comment]
> @nyh as you know, Scylla already have [Roll Base Access Control](https://docs.scylladb.com/operating-scylla/security/rbac_usecase/) we can use.

It's indeed a good possibility. We already define the secret keys used for DynamoDB-API authentication using the same CQL table  `system_auth.roles` that is used for role-based access controls. Because Alternator uses the same "roles" and also uses ordinary CQL tables (each Alternator table is implemented as a CQL table whose name can be derived from the Alternator table's name), we can indeed specify relations like "role X may write to Alternator table Y" using the existing CQL RBAC instructions ("GRANT"). We will just need to add the appropriate permission checks to the various Alternator operations.

An important question is whether such a CQL-based API would not be very awkward for users who are familiar with the AWS APIs. But maybe we can start with the CQL API like @tzach suggested, and later add a more AWS-like API.

**Comment by nyh** [comment]
The function `server::handle_api_request()` (in `alternator/server.cc`) begins by authenticating the request (if enabled) and saving its `username`.
Today, the only thing we do with this `username` is to put it in a tracing message.
But we could use `username` for choosing workload-prioritization, and also pass it to the individual callback for the individual operation, to allow it to check that `username` has the permissions which are needed for this operation. 

Passing the username deep in the request handling is natural we want to support very fine-grained access control as DynamoDB supports - it allows one to set permissions on individual tables, specific keys and individual attributes. These attributes may come from inside expressions that haven't been parsed before the request handler begins to run.

**Comment by nyh** [comment]
In pull-request https://github.com/scylladb/scylladb/pull/11380 @psarna added the username information to the request, so we are one step closer to implementing this feature.

**Comment by nyh** [comment]
@hogupop raised an idea to implement a useful **subset** of access control, just on whole tables, by using only the DynamoDB API's tag operations and no need for CQLs or the concept of roles. For example,

1. Use a tag on a table to define a list of authenticated users may read this table and which may write it.
2. Changing a table's tag is considered writing it, so an unauthorized user cannot give himself write permissions on a table (but note that a authorized writer can give himself read permissions, so write permissions should imply read permissions).
3. A user creating a table can create it with the permission tags he wants.

This idea will be very easy to implement, and very easy to use.

Such implementation will be less powerful than in implementation that uses the concept of "roles" - a second level of indirection that names a list of authenticated users so you can give access to the same list of users to many separate tables. For example, to add another administrator to 100 tables you'd need to modify the tags for each of these 100 tables individually. But if we wanted to allow defining roles we would need a different API, and the benefit of the role-less suggestion here is that we don't need to invent new APIs - just use the per-table tags.

**Comment by mykaul** [comment]
@ptrsmrn - not sure why it's a P3 - need to re-consider.

**Comment by nyh** [comment]
Amazon recently introduced [resourced-based access policies](https://aws.amazon.com/blogs/database/simplify-cross-account-access-control-with-amazon-dynamodb-using-resource-based-policies/) to DynamoDB, which supposedly simplify access control over the existing IAM features:

> With the introduction of resource-based policies, you can define access control per resource, for example a DynamoDB table, index, or stream. By using this approach, you can avoid the hassle of creating and managing account roles for each tenant’s account, and instead achieve centralized access control at the table level, making your security controls simpler.

**Comment by nyh** [comment]
> > @nyh as you know, Scylla already have [Roll Base Access Control](https://docs.scylladb.com/operating-scylla/security/rbac_usecase/) we can use.
> 
> It's indeed a good possibility. We already define the secret keys used for DynamoDB-API authentication using the same CQL table `system_auth.roles` that is used for role-based access controls. Because Alternator uses the same "roles" and also uses ordinary CQL tables (each Alternator table is implemented as a CQL table whose name can be derived from the Alternator table's name), we can indeed specify relations like "role X may write to Alternator table Y" using the existing CQL RBAC instructions ("GRANT"). We will just need to add the appropriate permission checks to the various Alternator operations.

I started working on exactly this approach in pull-request https://github.com/scylladb/scylladb/pull/19762. It looks very promising. The result is not compatible with AWS, so I hesitate if it should "Fixes" this issue or not, but it does give table-granularity access control configured via CQL which may be "good enough" for many Alternator users.

**Comment by mykaul** [comment]
> > > @nyh as you know, Scylla already have [Roll Base Access Control](https://docs.scylladb.com/operating-scylla/security/rbac_usecase/) we can use.
> > 
> > 
> > It's indeed a good possibility. We already define the secret keys used for DynamoDB-API authentication using the same CQL table `system_auth.roles` that is used for role-based access controls. Because Alternator uses the same "roles" and also uses ordinary CQL tables (each Alternator table is implemented as a CQL table whose name can be derived from the Alternator table's name), we can indeed specify relations like "role X may write to Alternator table Y" using the existing CQL RBAC instructions ("GRANT"). We will just need to add the appropriate permission checks to the various Alternator operations.
> 
> I started working on exactly this approach in pull-request #19762. It looks very promising. The result is not compatible with AWS, so I hesitate if it should "Fixes" this issue or not, but it does give table-granularity access control configured via CQL which may be "good enough" for many Alternator users.

Would be good to understand how far off is it from AWS.

**Comment by nyh** [comment]
> Would be good to understand how far off is it from AWS.

First of all, the API is completely different - as I mentioned above AWS has two different APIs for configuring access control in DyanmoDB:
1. The original method is AIM, a REST API like all other AWS protocols (with support from all their libraries, e.g., boto3 in Python), to configure roles and permissions.
2. The newer "resource-based policies" introduced a few months ago (see https://aws.amazon.com/blogs/database/simplify-cross-account-access-control-with-amazon-dynamodb-using-resource-based-policies/). There is a new API request [PutResourcePolicy](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutResourcePolicy.html)  to attach a policy to a table - without learning how to use AIM or creating "roles".

Second, the _capabilities_ are different - our RBAC is more limited. Our RBAC allows controlling whether an entire table can be read or written or created or deleted. Amazon, in both APIs, gives you finer level of control - like giving a user the ability to only read keys which begin in a specific prefix, or the ability to allow reading only specific attributes in each item. Amazon also allows access control depending on the user's IP address. Whether or not any of these fine-grained access control features are actually needed by most DyanamoDB users, I don't know.

**Comment by scylladb-buff** [comment]
Both identity-based and resource-based policies are tightly coupled with AWS; they even persist in AWS, not in the DDB. Supporting those policies will be complex and we will only gain marginal compatibility with AWS, but it will strip us of one of our significant competitive advantages: The Alternator as a cloud-agnostic DynamoDB alternative. 

We should stick with our own (CQL) RBAC as a core of alternator authorization and integrate with the rest of the platforms for authentication. 
If the market demands it, we can create a one-off migration tool that migrates AWS IAM policies to LDAP/RBAC rules, allowing us to migrate customers who might need this.

All the fine grain access capabilities @nyh identified are niche, and it looks to me, we can implement quite easily, in case we discover a substantial demand for them. I doubt any of those fine permissions will be a deal breaker.

**Comment by nyh** [comment]
This issue was closed by https://github.com/scylladb/scylladb/pull/20135, which added a CQL-based ACL support to Alternator. Although it is probably "good enough" (famous last words), it is _not_ compatible with DynamoDB in neither API nor in functionality, so I opened a new issue about considering in the (hopefully distant) future a more DynamoDB-compatible access control feature: https://github.com/scylladb/scylladb/issues/20400
