### ISSUE TITLE
Timer callback failed: seastar::gate_closed_exception during storage_service shutdown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#5078]
Seen in [scylla-3.1/job/dtest-release/152/testReport/repair_additional_test/RepairAdditionalTest/repair_joint_row_3nodes_2_test](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/152/testReport/repair_additional_test/RepairAdditionalTest/repair_joint_row_3nodes_2_test/)
Scylla version d81ac93728211f29e76efc5a6e1e622095924ff0

[node1.log](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/152/artifact/logs-release.2/1569100372653_repair_additional_test.RepairAdditionalTest.repair_joint_row_3nodes_2_test/node1.log):
```
INFO  2019-09-21 21:11:42,418 [shard 0] storage_service - Drain on shutdown: starts
INFO  2019-09-21 21:11:42,418 [shard 0] storage_service - Stop transport: starts
INFO  2019-09-21 21:11:42,419 [shard 0] storage_service - Thrift server stopped
INFO  2019-09-21 21:11:42,419 [shard 0] storage_service - CQL server stopped
INFO  2019-09-21 21:11:42,419 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2019-09-21 21:11:42,419 [shard 0] gossip - My status = NORMAL
INFO  2019-09-21 21:11:42,419 [shard 0] gossip - Announcing shutdown
INFO  2019-09-21 21:11:42,420 [shard 0] storage_service - Node 127.0.37.1 state jump to normal
INFO  2019-09-21 21:11:44,432 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2019-09-21 21:11:44,433 [shard 0] storage_service - messaging_service stopped
INFO  2019-09-21 21:11:44,433 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2019-09-21 21:11:44,433 [shard 0] storage_service - stream_manager stopped
INFO  2019-09-21 21:11:44,433 [shard 0] storage_service - Stop transport: shutdown stream_manager done
ERROR 2019-09-21 21:11:44,433 [shard 0] seastar - Timer callback failed: seastar::gate_closed_exception (gate closed)
INFO  2019-09-21 21:11:44,433 [shard 0] storage_service - Stop transport: auth shutdown
INFO  2019-09-21 21:11:44,433 [shard 0] storage_service - Stop transport: done
INFO  2019-09-21 21:11:44,433 [shard 0] storage_service - Drain on shutdown: stop_transport done
```

The error message looks benign.
Not sure which callback hit a closed gate but it'd be better to handle this case more gracefully during shutdown by e.g. cancelling the timer before closing the gate.

Ref #4384

**Comment by mykaul** [comment]
@roydahan - are we still seeing this?

**Comment by roydahan** [comment]
AFAIK yes, but filter this "Error" so it won't fail the tests.

**Comment by DoronArazii** [comment]
@bhalevy it's in your team's queue for 5.3?

**Comment by bhalevy** [comment]
> AFAIK yes, but filter this "Error" so it won't fail the tests.

I haven't seen it for a long while.

> @bhalevy it's in your team's queue for 5.3?

No, I have no plan to tackle this. I think the issue can be closed without any more proof it even reproduces.
