### ISSUE TITLE
UX: check scylla version from cqlsh client

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylladb#5119]
*Installation details*
Scylla version (or git commit hash): latest master / scylladb/scylla-nightly:3.1.0.rc8
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Currently `SHOW version` returns compatible C* version.
The scylla user can't get specific scylla version from cqlsh client, they have to ask from DBA.

```
$ docker exec node1-rc8 cqlsh -e 'show version'
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
```

@tzach

**Comment by tzach** [comment]
Good point @amoskong see comments by @penberg on #680
AFAIU, it requires an update of CQLsh - which we should do

**Comment by nyh** [comment]
This is really a cqlsh issue, so moving it to the separate cqlsh repository and closing this issue.

**Comment by amnonh** [comment]
We had that implemented in our 2020 hackaton, no reason why it shouldn't make it to master

**Comment by nyh** [comment]
> We had that implemented in our 2020 hackaton, no reason why it shouldn't make it to master

I created https://github.com/scylladb/scylla-cqlsh/issues/9 and @fruch already sent a patch :-)
What did you have in the 2020 hackathon?

**Comment by fruch** [comment]
> This is really a cqlsh issue, so moving it to the separate cqlsh repository and closing this issue.

keep in mind the new repo is still on the process of being integrated into scylla-core. (it's a very low speed project..)

**Comment by nyh** [comment]
@fruch yes but I'm optimistic :-)
