### ISSUE TITLE
Users should not use SimpleStrategy for production (docs around AddDC are incorrect)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#5224]
https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add_dc_to_exist_dc/#adding-a-new-data-center-into-an-existing-scylla-cluster

Users are instructed in https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add_dc_to_exist_dc/#add-new-dc to change the mykeyspace from SimpleStrategy to NetworkToplogyStrategy

This will not really work as SimpleStrategy and NetworkToplogyStrategy on a single DC may select different replicas depending if the nodes are on different racks. 

Users should do this only if they have no data in the keyspace/tables or do a much more complex porcedure of:
1. stopping traffic
2. repairing
3. altering
4. repairing
5. cleanup
6. resuming traffic

**Comment by tzach** [comment]
Should we block or warn about SimpleStratagy when SimpleSnitch is **not** used?

**Comment by tzach** [comment]
@slivne see Doc fix https://github.com/scylladb/scylla-docs/pull/2189

**Comment by nyh** [comment]
Should this issue be closed as the doc was fixed, or is there a request here for something more (warning, error, expert mode, or something)?

**Comment by nyh** [comment]
Created issue #8582 about switching internal tables to NetworkStrategy, and #8586 about forbidding SimpleStrategy in CREATE KEYSPACE. I think nothing is left to do in this issue, and it can be closed?
