### ISSUE TITLE
LIMIT is not doing it right when using GROUP BY

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#5362]
as mentioned on #5361 , this is an effort for testing #2206 , and LIMIT is not behaving as expected (and not accordingly with C*):

```
cqlsh:test_paging_with_group_by> PAGING 1000
Page size: 1000
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 4;

 a | b | c | d
---+---+---+---
 1 | 2 | 1 | 3
 1 | 4 | 2 | 6

(2 rows)
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 5;

 a | b | c | d
---+---+---+---
 1 | 2 | 1 | 3
 1 | 4 | 2 | 6
 2 | 2 | 3 | 3

(3 rows)
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 3;

 a | b | c | d
---+---+---+---
 1 | 2 | 1 | 3
 1 | 4 | 2 | 6

(2 rows)
cqlsh:test_paging_with_group_by> SELECT a, b, c, d FROM test GROUP BY a, b LIMIT 8;

 a | b | c | d
---+---+---+----
 1 | 2 | 1 |  3
 1 | 4 | 2 |  6
 2 | 2 | 3 |  3
 2 | 4 | 3 |  6
 4 | 8 | 2 | 12

(5 rows)
```

**Comment by fgelcer** [comment]
could be resolved by same PR as #5361 , but reporting apart as it doesn't behave the same.

**Comment by dekimir** [comment]
See diagnosis here: https://github.com/scylladb/scylla/issues/5361#issuecomment-918545423

**Comment by nyh** [comment]
This issue is also reproduced by the Cassandra unit test which I'm translating now, `cassandra_tests/validation/operations/compact_storage_test.py`::`testGroupByWithoutPaging`.

**Comment by avelanarius** [comment]
This issue is also reproduced by an integration test in Java Driver 3.x: https://github.com/scylladb/java-driver/blob/b3f3ebaf161b21e5c4840ec294595d4e4b39d9bf/driver-core/src/test/java/com/datastax/driver/core/querybuilder/QueryBuilderExecutionTest.java#L636

**Comment by nyh** [comment]
Updated list of tests reproducing this issue:

cql-pytest:

* `cassandra_tests/validation/operations/compact_storage_test.py`::`testGroupByWithoutPaging`
* `cassandra_tests/validation/operations/select_group_by_test.py`::`testGroupByWithoutPaging`

Java Driver integration test:
https://github.com/scylladb/java-driver/blob/b3f3ebaf161b21e5c4840ec294595d4e4b39d9bf/driver-core/src/test/java/com/datastax/driver/core/querybuilder/QueryBuilderExecutionTest.java#L636

**Comment by ptrsmrn** [comment]
> [@ptrsmrn](https://github.com/ptrsmrn) -
> 
> ```
> @pytest.mark.xfail(reason="issue #5362")
> def test_group_by_clustering_prefix_with_limit_and_paging(cql, table1):
> ```
> 
> ?

https://github.com/scylladb/scylladb/pull/18842 has a longer discussion on whether https://github.com/scylladb/scylladb/issues/5362 is solved with this PR or not. Anyhow, the quoted test remains unfixed, yet it references this issue, so I should reopen this issue.
However, in https://github.com/scylladb/scylladb/pull/18842#issuecomment-2198546638 @nyh writes:
> Conceivably, we could say that we fixed 5362 - and then open a new issue that just the paging remains broken. But in my opinion, this failure suggests that something in your solution is wrong and it should be fixed now, before merging.

So I take the paging, which the quoted testcase is about, has not been fixed in the PR. I can do as suggested, @nyh do you have any preferences here?

**Comment by ptrsmrn** [comment]
Reopening just in case, so we don't forget about the above /\
