### ISSUE TITLE
Add single collection item indexing

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#5440]
This feature is a first step towards #2962 - and allows indexing a single collection value. Intended usage:

```cql
CREATE INDEX ON t(my_map['my_key']);
CREATE INDEX ON t((pk),my_map['my_key']);
SELECT * FROM t WHERE my_map['my_key'] = 42;
SELECT * FROM t WHERE pk = 17 AND my_map['my_key'] = 42;
SELECT * FROM t WHERE my_map CONTAINS 'my_key';
```

The nature of this kind of indexing is to only index a single item from a collection - so querying for that particular map or set entry can leverage an index and be faster, but querying for another item in the collection still requires filtering. As an example, the index above is created only for a single map item identified by the key `my_key`, and it's not possible to leverage this index to query by another item, e.g. `SELECT * FROM t WHERE my_map['some_other_key'] = 9`.

This feature was already posted on the mailing list for some time, but for easier manageability a specific issue is hereby created for it.

**Comment by psarna** [comment]
If somebody still needs the feature, #2962 is already merged, and based on the generic implementation it might be easier to make a more specific one, which only indexes a single value from a collection (or, perhaps,  more generally, only values that fulfill a predicate?)

**Comment by nyh** [comment]
I don't remember why we created this issue - the labels suggest it is for Cassandra compatibility, but I think that's a mistake and Cassandra doesn't have such a feature. Or does it? (Cassandra 4 added the ability to select one element - #7751 - but it's not supported in materialized views).

What I think a **variant** of this feature can be good for is Alternator's GSI, for adding a new GSI for a pre-existing table (issue #5022 ). Today, when we only allow a GSI to be created together with the table, we make this attribute a real schema column - and then we can make it the MV key. But on a pre-existing table a non-key attribute isn't a real column - it's just just one element in a single map column (`:attrs`). So we need to be able to create a view based on a single named element in a map - just like is requested in this feature. However, note that this issue talks about CQL secondary-index, which is not the same as MV that Alternator's GSI uses.

**Comment by psarna** [comment]
Originally the issue was created as a spin-off from #2962, because it was supposed to be the first iteration of it. Later it turned out that it would be useful for alternator too, at least if we decide to keep the current storage format (and not switch to, say, some custom CRDT flavor of JSON). The compatibility label shouldn't be here indeed, it belonged to #2962.

**Comment by nyh** [comment]
So I'm tempted to close this issue. The Alternator issue of adding a MV whose key is a map element (#11567) is "related" to this one but the implementation is different because: 1. It's a materialized view, not an secondary-index as in this issue, and 2. This issue is about a typed map (e.g., `map<string,int>` with the int being indexed) whereas the Alternator issue has `map<string,bytes>` and the bytes need to be deserialized in a very Alternator-specific way.

**Comment by psarna** [comment]
> So I'm tempted to close this issue.

good idea, no objections from me

**Comment by nyh** [comment]
Closing the issue, for reasons described above.
