### ISSUE TITLE
scylla service/maintenance mode

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#5489]
Often when disaster strikes it would be useful to bring up a "damaged" node, fix it e.g. using `nodetool compact`, `nodetool scrub`, etc, then let it join the cluster. This is curently not possible as a node, once started will instantly become "UP" and will start serving reads and writes.

It would be beneficial in these scenarios to have a "service mode", a mode in which a node will start up but not mark itself as "UP" and hence will not do its usual duties as a member of the cluster, instead it will work as if it is was a single-node cluster, being able to serve local reads, do compaction, scrub, etc. This would greatly ease disaster recovery when interference to/from the rest of the cluster is undesired or outright dangerous (because the node can spread corrupt data for example).

**Comment by bhalevy** [comment]
I think that compaction should not run automatically in service mode, but rather only using a nodetool command.

**Comment by denesb** [comment]
Agree, when there are problematic sstables, you don't want them compacted away automatically.

**Comment by denesb** [comment]
Another good point raised by @bhalevy is to start the client services (CQL, Thrift, Alternator, etc.) on non-standard ports, so that a driver accidentally connecting to this node and executing a LOCAL_ONE/ONE/ANY query doesn't silently succeeds.

**Comment by bhalevy** [comment]
also known as "maintenance mode" (for github keyword search)

**Comment by bhalevy** [comment]
@vladzcloudius please add you input and assign FE priority for this proposal.

**Comment by vladzcloudius** [comment]
> @vladzcloudius please add you input and assign FE priority for this proposal.

Thanks, @bhalevy.

The described mode also makes sense if `nodetool drain` times out during the upgrade.

Since this is supposed to be followed by crating a snapshot we want to make sure that all commitlogs are drained.

In such a case we want to kill the service (`kill -9`) and start it in the "maintenance mode" where it would not serve any new WRITEs as a replica and would replay whatever commitlogs it has to replay.

The priority of this is not urgent.

**Comment by vladzcloudius** [comment]
@ebenzecri FYI

**Comment by ebenzecri** [comment]
@vladzcloudius Amazing! Thanks for pushing this forward.
