### ISSUE TITLE
the replaced node is back after it has been replaced

### ISSUE THREAD

**Issue by wuzm2k05** [scylladb/scylladb#5523]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.8
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos

I have a cluster with four nodes. 

UN  192.168.122.239  1.06 MB    256          ?       04d20558-4aa6-4c0b-8478-25274f05e0ec  RACK2
UN  192.168.122.111  161.89 KB  256          ?       6cc4c16a-9407-4c00-b657-e14c60d30f03  RACK1
UN  192.168.122.82   573.62 KB  256          ?       7b384368-a277-4942-b1aa-4c4d649ff3de  RACK4
UN  192.168.122.230  567.26 KB  256          ?       9aa8c053-4064-45c2-940c-d826acdd2ba3  RACK3

Then I replaced 192.168.122.239 with 192.168.122.38 by using the following steps:
1. stop 192.168.122.239
2. install/config 192.168.122.38 (with replace_address_first_boot=192.168.122.239)
3. start 192.168.122.38

UN  192.168.122.111  161.88 KB  256          ?       6cc4c16a-9407-4c00-b657-e14c60d30f03  RACK1
UN  192.168.122.38   921.47 KB  256          ?       04d20558-4aa6-4c0b-8478-25274f05e0ec  RACK2
UN  192.168.122.82   573.62 KB  256          ?       7b384368-a277-4942-b1aa-4c4d649ff3de  RACK4
UN  192.168.122.230  567.26 KB  256          ?       9aa8c053-4064-45c2-940c-d826acdd2ba3  RACK3

Everything seems good now. 
However when I startted the the 192.168.122.239, it seems all nodes (except 192.168.122.38) took 239 back.

on all nodes (except 192.168.122.38)
UN  192.168.122.239  1.06 MB    256          ?       04d20558-4aa6-4c0b-8478-25274f05e0ec  RACK2
UN  192.168.122.111  161.89 KB  256          ?       6cc4c16a-9407-4c00-b657-e14c60d30f03  RACK1
UN  192.168.122.82   573.62 KB  256          ?       7b384368-a277-4942-b1aa-4c4d649ff3de  RACK4
UN  192.168.122.230  567.26 KB  256          ?       9aa8c053-4064-45c2-940c-d826acdd2ba3  RACK3

on 192.168.122.38:
UN  192.168.122.111  161.88 KB  256          ?       6cc4c16a-9407-4c00-b657-e14c60d30f03  RACK1
UN  192.168.122.38   921.47 KB  256          ?       04d20558-4aa6-4c0b-8478-25274f05e0ec  RACK2
UN  192.168.122.82   573.62 KB  256          ?       7b384368-a277-4942-b1aa-4c4d649ff3de  RACK4
UN  192.168.122.230  567.26 KB  256          ?       9aa8c053-4064-45c2-940c-d826acdd2ba3  RACK3

I was expecting the replaced node would not be accepted by the cluster but not the original one. So is this behavior of cluster expected? From my point view,  the cluster would be malfunctioned in this situation.

Thanks,
Zhaoming

**Comment by asias** [comment]
Hello Zhaoming,

Thanks for report. This is actually an operation error. The replaced node should not be restarted. 

I had a patch to catch such error. It is not merged in scylla yet. 

```
commit 2475833a590376de6d74f9c9649b75b2c7b62057
Author: Asias He <asias@scylladb.com>
Date:   Fri Jul 26 14:59:05 2019 +0800

    storage_service: Prevent a replaced node rejoins the cluster again
    
    Consider:
    
    start n1, n2, n3
    stop n3
    start n4 to replace n3
    start n3 again
    
    n3 can successfully start with the same host id and other nodes will see
    n3 in gossip. To prevent such operation error, we can detect and make n3
    to stop itself.
```

**Comment by slivne** [comment]
@asias is this patch on the mailing list ?

**Comment by asias** [comment]
It was part of another big series and was split out. It is not sent upstream yet.

**Comment by slivne** [comment]
@asias is the patch `storage_service: Prevent a replaced node rejoins the cluster again` merged ?

**Comment by asias** [comment]
> @asias is the patch `storage_service: Prevent a replaced node rejoins the cluster again` merged ?

No. It is turns out the patch does not really  prevent the replaced node joining again. When the replaced node start again it will use a new gossip generation number. There is no way to tell if it is the old replaced node.

**Comment by slivne** [comment]
@asias so do we have a solution for this ?

**Comment by asias** [comment]
I do not have good solution so far. It is a nice to have thing because it prevents a user operation error. We should document and emphasize not to do this in the replace procedure.

**Comment by kostja** [comment]
Fixed in the current master with node isolation patch by @kbr-scylla

**Comment by kbr-scylla** [comment]
> Fixed in the current master with node isolation patch by @kbr-scylla

Note: in raft-topology mode (currently experimental)

**Comment by temichus** [comment]
@bhalevy this issue is fixed but I see an old commit in Dtest that mentioned this issue. Could you please check:

https://github.com/scylladb/scylla-dtest/commit/f9be323d16b1e268391477048256b8ea512db97a

**Comment by temichus** [comment]
and here https://github.com/scylladb/scylla-dtest/commit/778dc92ef1a101072ce15f07d59f923e6549efeb
cc @asias
