### ISSUE TITLE
Add configurable mutation fragment stream validator to the read path

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#5615]
We currently have a mutation fragment stream validator on the write path, more specifically on the sstable write path. This validator validates mutation fragment kind order, and optionally partition and clustering key monotonicity. Key validation can be enabled with a configuration flag.

We should add a similar validator to all our read path. Violations caught by the write-path validator often have root causes that happened on a previous, finished read, perhaps on another node. Having a validator on the read paths would help zero in on the root cause. As the read path is more latency sensitive, we should have more levels of validation:
* none
* mutation fragment kind
* partition key
* clustering key

Additionally we might wish to enable the validator per-table, to impact only the workflow of that table which is suspected to have problems.

**Comment by denesb** [comment]
There seems to be no interest in this at the moment. There is a patch on the mailing list since January 2020 (with a rebased version sent in March). I'm giving up on pinging it, and keeping up with conflicts. Linking it here, in case we want to resume working on this: https://groups.google.com/d/topic/scylladb-dev/SmaOvNK8TrY/discussion

**Comment by bhalevy** [comment]
@denesb other than rebasing the patch mentioned above anything else needed?
We can also provide a private build to qa for 4.2 re: #7208

**Comment by denesb** [comment]
Off the top of my head only a rebasing is needed. I will resend the patches to the mailing list and give a private version to qa to test to speed things up.

**Comment by bhalevy** [comment]
Is #7736 basically a duplicate of this issue?
Can we close it with f0e2f31839b9bd9899fb6739d3d2359915ec676f?

**Comment by denesb** [comment]
> Is #7736 basically a duplicate of this issue?
> Can we close it with [f0e2f31](https://github.com/scylladb/scylla/commit/f0e2f31839b9bd9899fb6739d3d2359915ec676f)?

https://github.com/scylladb/scylla/commit/f0e2f31839b9bd9899fb6739d3d2359915ec676f can fulfill the functionality of this proposal for the case where the invalid fragments originate from the disk, but not in the case where the disk has a valid fragment stream which is corrupted by one of the readers in memory.

**Comment by denesb** [comment]
I think we can close this with 302917f63d. It is not configurable, but it is present on all read paths, and not just, so it has an even better coverage than what this issue proposed.
