### ISSUE TITLE
Change --workdir to use directories class

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#5626]
Current implementation of the --workdir option has to change the value of all directories prepending to them the --workdir path. This is not nice, the db::config object is better be kept intact.

To fix this we should make all the places that need some directory path from config use the directories object instead. The latter may change the path as needed.

**Comment by vss96** [comment]
Hi, I'm interested in contributing and would like to pick this up. Can someone point me in the correct direction so that I can explore the issue and put in a fix for it?

**Comment by xemul** [comment]
There are several directories that can be configured. All sit on db::config

    named_value<sstring> commitlog_directory;
    named_value<string_list> data_file_directories;
    named_value<sstring> hints_directory;
    named_value<sstring> view_hints_directory;
    named_value<sstring> saved_caches_directory;

all users of it get the value from db::config instance, but instead of doing so they should get it from the instance of <code>directories</code> class, that's created in main.cc:

    utils::directories dirs;

**Comment by nyh** [comment]
@xemul I'm not sure I understand exactly what you are proposing. Right now, for example, we have a function db::commitlog::config::from_db_config() which takes a db::config and extracts both the directory locations and other configurations from it. We'll now need to pass to it an additional structure? Or will db::config contain the utils::directory? I'm not sure exactly what you are suggesting.

**Comment by xemul** [comment]
@nyh , I'm suggesting to stop using db::config as the source of full directories paths, becaue to make it work corrctly (with --workdir) we need to have this ::setup_directories() thing. Istead, the directories should be used to provide full paths. In particular, equipping db::commitlog::config::from_db_config() sounds like one of the options to acheive that. Another might be to feed directories into db::commitlog::create_commitlog(). I cannot say for sure which one would be better, this is what the issue is partially about -- read the code carefully and decide.

**Comment by bhalevy** [comment]
More consideration:
1. Use `fs::path` instead of `sstring` for paths.
2. Call `fs::canonical` once on start up to make sure we're working with absolute paths, then the fs::canonical call in `sstables::dirname` can be safely removed (it causes lots of redundant `lstat` syscalls)

**Comment by bhalevy** [comment]
@lkshminarayanan are you working on this issue?

**Comment by lkshminarayanan** [comment]
> @lkshminarayanan are you working on this issue?

No, I'm working on https://github.com/scylladb/scylladb/issues/14506.
I think @pwrobelse talked about this issue during the team standup today.

**Comment by pwrobelse** [comment]
Yes, I am working on that issue.
