### ISSUE TITLE
YCSB Dynamodb Client errors while one node network partly blocked

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#5802]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200211.9eb6ac71622
Cluster size: 6 (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI):  ami-01747527c48afe65c

## Summary
While one node was disconnected partly (port=7000 and 7001) from other nodes  for 10min - (alternator-3h-alternat-db-node-25407ad1-5 [54.229.191.8 | 10.0.159.243]), client facing dynamodb api calls started failing.

### Nemsis starting:
```
< t:2020-02-12 16:16:06,968 f:nemesis.py      l:642  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method network_reject_inter_node_communication
< t:2020-02-12 16:16:06,969 f:nemesis.py      l:389  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> RejectInterNodeNetwork: every packet that belongs to inter node communication connections (port=7000 and 7001) will be dropped for 500s
```

### Errors received by the YCSB client
```
< t:2020-02-12 16:16:33,571 f:remote.py       l:680  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.20.63]: 
490453 [Thread-109] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.AmazonServiceException: 
Internal server error: exceptions::unavailable_exception (Cannot achieve consistency level for cl LOCAL_ONE. Requires 1, alive 0) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: Internal Server Error; Request ID: null)
```
![image](https://user-images.githubusercontent.com/340979/74412302-c7cc8200-4e45-11ea-9cf6-120e0a085326.png)

**NOTE**: I'm using `alternator_use_dns_routing: true` which mean we still get requests alternator the faulty node, but since those are working (i.e. return some response) I think the DNS isn't re-evaluated  

This is a fairly new Nemesis, @dkropachev you have a example of a run like this under regular cassandra stress so we could compare the behavior ?

## Logs
* **test_id**: 25407ad1-d919-494a-b5a1-20168912d47d
```bash
# download monitor data locally
hydra investigate show-monitor 25407ad1-d919-494a-b5a1-20168912d47d
```
* **Jenkins Job**: https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/longevity/job/longevity-alternator-3h-test/33

*  **db-cluster**: https://cloudius-jenkins-test.s3.amazonaws.com/25407ad1-d919-494a-b5a1-20168912d47d/20200212_193324/db-cluster-25407ad1.zip
* **monitor-set**: https://cloudius-jenkins-test.s3.amazonaws.com/25407ad1-d919-494a-b5a1-20168912d47d/20200212_193324/monitor-set-25407ad1.zip
* **loader-set**: https://cloudius-jenkins-test.s3.amazonaws.com/25407ad1-d919-494a-b5a1-20168912d47d/20200212_193324/loader-set-25407ad1.zip
* **sct-runner**: https://cloudius-jenkins-test.s3.amazonaws.com/25407ad1-d919-494a-b5a1-20168912d47d/20200212_193324/sct-runner-25407ad1.zip

**Comment by slivne** [comment]
This makes sense - dynamodb is not token aware - so the node receiving the request is not a replica of the data and as such can't necessarily serve a request that is LOCAL_ONE.

Having said that - AFAIK we do not close a nodes CQL port on internal communication being closed - @bentsi / @fruch did the same test pass for CQL. 

@asias / @gleb-cloudius - do we close CQL port when the node looses connectivy to other nodes in the cluster ?

**Comment by fruch** [comment]
@slivne the LOCAL_ONE is a LWT initiate call, we did yet test LWT with this new nemesis as far as I know.

Most of our CQL stress are with QUORUM, hence we won't see t error, in

**Comment by nyh** [comment]
As @slivne I don't think this is a bug. You fabricated a situation where clients can send their requests to the nemesis-victimized node, but this node cannot connect to other nodes that it needs to actually perform this request. Do you think this represents a real-world scenario we need to support?

An analogous LOCAL_ONE request would succeed in a **CQL** test because CQL will normally send the request to the right node, so the LOCAL_ONE request will arrive at the correct node and not need communication with any other node. But for CL>1 (e.g., QUORUM on RF=3), you should have the same problem in CQL as well. If you don't see this problem, maybe it's because CQL doesn't use port 7000 for forwarding requests, and instead uses port 9042 (the CQL port) to do this? I don't know if that's the case - a `docs/ports.md` is sorely missing (maybe I'll go ahead and write on tomorrow, I really feel a big hole in my knowledge in this area and want to fill it). 

So unless I'm misunderstanding something, this looks more like a buggy test, and the issue should be closed (and the test fixed to do something more realistic, like blocking a node from the network - not just blocking some of the ports).

**Comment by asias** [comment]
> This makes sense - dynamodb is not token aware - so the node receiving the request is not a replica of the data and as such can't necessarily serve a request that is LOCAL_ONE.
> 
> Having said that - AFAIK we do not close a nodes CQL port on internal communication being closed - @bentsi / @fruch did the same test pass for CQL.
> 
> @asias / @gleb-cloudius - do we close CQL port when the node looses connectivy to other nodes in the cluster ?

No. We do not close the CQL port when we mark other nodes down.

**Comment by dkropachev** [comment]
> This is a fairly new Nemesis, @dkropachev you have a example of a run like this under regular cassandra stress so we could compare the behavior ?
38dba915-d55a-42db-b7b6-ba24e77ca277

**Comment by slivne** [comment]
@Asias He <asias@scylladb.com>  / @Gleb Natapov <gleb@scylladb.com>  - does
C* close CQL ports on a node when other nodes are shown as down.

**Comment by gleb-cloudius** [comment]
On Sun, Feb 16, 2020 at 11:36:46PM -0800, Shlomi Livne wrote:
> @Asias He <asias@scylladb.com>  / @Gleb Natapov <gleb@scylladb.com>  - does
> C* close CQL ports on a node when other nodes are shown as down.
> 
I do not understand the question. Does Cassandra close CQL port on an
alive node when other nodes are considered to be down? Is this the
question? How this even make sense?

--
			Gleb.

**Comment by nyh** [comment]
According to what @gleb-cloudius told me (if I understood him correctly), also for a CQL workload, port 7000 is used for all communication between coordinators and replicas, so if port 7000 is artificially blocked, requests which need multiple replicas (e.g., CL>1) will fail. So I don't understand the point of this issue. If the scenario of blocking port 7000 is interesting at all (I think it isn't...), all we can check in this case that we don't get some crashes or similar disasters - we shouldn't be surprised when user requests can't work in this case.

**Comment by slivne** [comment]
we should consider if to drain a node that looses all conectify to other nodes in the cluster.

**Comment by slivne** [comment]
In alternator case this maybe more problematic.

In CQL a client that receives an error/timeout may try to send the request to other nodes.

In Alternator we need to check what happens when a client gets a 500 - does it attempt to send the request to another node ?

**Comment by tzach** [comment]
> we should consider if to drain a node that looses all connectivity to other nodes in the cluster.

This make sense. Node also need to reopen CQL once connections to other nodes reestablished.
Without this, a temp network shutdown will shutdown the cluster.

**Comment by fruch** [comment]
@roydahan FYI, this is the issue raise cause of `RejectInterNodeNetwork` nemesis

**Comment by nyh** [comment]
> In alternator case this maybe more problematic.
> 
> In CQL a client that receives an error/timeout may try to send the request to other nodes.
> 
> In Alternator we need to check what happens when a client gets a 500 - does it attempt to send the request to another node ?

Not really, because:
1. If the server returns an error on the HTTP connection without closing it, the client may retry on the same connection.
2. If the client has additional connections opens (typical on a concurrent client, because each HTTP connection is serialized) he can use them, but they may be connected to the exactly same server. This is only a problem for DNS load balancing, where you can open 100 connections but all of them get resolved to the same node. It's not a problem for HTTP load balancer, which sends each connection to a different server.

**Comment by fruch** [comment]
this issue still happening
https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-alternator-3h-test/26

> According to what @gleb-cloudius told me (if I understood him correctly), also for a CQL workload, port 7000 is used for all communication between coordinators and replicas, so if port 7000 is artificially blocked, requests which need multiple replicas (e.g., CL>1) will fail. So I don't understand the point of this issue. If the scenario of blocking port 7000 is interesting at all (I think it isn't...), all we can check in this case that we don't get some crashes or similar disasters - we shouldn't be surprised when user requests can't work in this case.

@nyh, you basically say that if **one** node isn't available on this port, user start getting error ? 

We are getting those errors, from all the loaders, when communicating to different nodes:
```ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.AmazonServiceException: Internal server error: exceptions::unavailable_exception (Cannot achieve consistency level for cl LOCAL_ONE. Requires 1, alive 0) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: Internal Server Error; Request ID: null)
```

Again we are blocking only one node port, I find it very weird it takes down the whole cluster like that. we didn't saw similar happening on CQL loads.

seems like this is specific to LWT load (i.e. the part doing those requests with cl.LOCAL_ONE)

**Comment by nyh** [comment]
@fruch you are suggesting that this only happens with LWT - did you check it with the LWT option disabled? If not, can you, please?
If this is the case, we should re-tag this an LWT issue and get the LWT guys involved for their advice on this. I don't know what LWT does with LOCAL_ONE...

One thing worth noting is that in the DynamoDB HTTP-based API, there is no request pipelining: If one request "hangs", then this connection hangs. If YCSB has a fixed number of connections - e.g., 100 (?), after all 100 are hung, we will have no request running. So if only some, not all, LWT requests want to contact the quarantined node, thinking it is alive - and these requests hang, we will very quickly hang all connections.

Also, what kind of workload is running there, read, write, or both?

**Comment by fruch** [comment]
the workload here is read only with data integrity checks.

I can try it once with disabling the LWT, and see the behavior. will do.

**Comment by nyh** [comment]
@fruch if this is really a read-only workload then it doesn't use LWT, and LWT has nothing to do with it.
If you see errors with CL=ONE reads, it means you are doing weak-consistency reads.
So my comment about connections hanging can (I think) easily explain the problem:
When **any** of the coordinators gets a CL=ONE read, there is some chance (e.g., 1/3rd) that the coordinator will choose to forward the request to the quarantined node - which it **thinks** is alive. This request will timeout eventually, but until it does, this connection will hang. 

However, there is one catch here - because blocking port 7000 also blocks gossip, pretty soon other nodes should consider the quarantined node to be dead, and stop sending any requests to it. At that point, two of the nodes should work normally, and not experience any hangs. If that's not what you're seeing, I don't know what's going on. The hung connections can all remain hang, but after 10 seconds, all the hung requests will have timed out and new requests should succeed. Do you continue to see timeouts and such more for more than 10 seconds - or only during a short period after starting the blockade?

**Comment by fruch** [comment]
If we'll change it to strong consistent reads, problem solved, and no more user getting errors ? BTW this test runs with 6 nodes, to accommodate the Nemsis.

And the if we disable consistent reads, we expect those errors to go away in 10sec or so ?

Right now the test is halting, if there more then 5 errors in one minute. I can fine tune the tolerance for errors, in case we choose to disable consistent reads

I'll give it a go with consistent reads.

That much more equivalent, to what we are usally test in SCT.

**Comment by fruch** [comment]
Also isn't the definition of ONE
ONE – Only a single replica must respond

In our case we only send it to one node ? Or it's like that only in the alternator implemention ?

**Comment by nyh** [comment]
@fruch, you said "Right now the test is halting, if there more then 5 errors in one minute.". I think this is a mistake. It can't distinguish between a bunch of errors while one node suddenly was quarantined, and a permanent failure. Maybe 5 errors is also bad, but it makes it really difficult to understand what problem exactly we're seeing - if it's something transient during the transition, or permanent after the transition (that Alternator can't work without one of the nodes). Perhaps the easiest way to check this (if you can't drop this "exit on 5 errors" logic) would be to start the quarantine on the node while the workload is down (and sleep for some time after starting the quarantine and before resuming the load). In this case, we should hope that the client will not see any errors (if he doesn't send his requests to the quarantined node, of course).

One very good question you hinted (also in the last comment) on is why doesn't the "optimistic retry" (is this how we call it?) feature save us. This feature means that before the coordinator times out on a request it sent a specific repica chosen at first, it will re-chose a replica send the same request again to another replica, and hopefully get a response from it quickly. When only one node is quarantined, this should have fixed the read (for both CL=ONE and CL=QUORUM). I don't know why it didn't. I don't know if this feature is guaranteed to work. Maybe it has some rare timing problems, but common enough that we just get 5 errors, and not much more. I don't know :-(

**Comment by fruch** [comment]
@nyh @slivne 
I've been able to reproduce this issue: (it depened on this ccm PR: https://github.com/scylladb/scylla-ccm/pull/231)
https://gist.github.com/fruch/f97ade6e117761c8b52a2dde9fbfed1a

and came to a conclusion it's would fail in the exact same way on CQL call, when call are getting to the node that has it port 7000 blocked.

I'll need to find a way to silence the alerts and errors in our test during this Nemesis.

meanwhile I think we could close this issue.
