### ISSUE TITLE
RFE: best practice validator

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylladb#5892]
This is a feature request to implement a validator (something like a linter) for schema and configuration best practices.

A command `nodetool bestpractice` would run some standard checks and return a list of compliant and non-compliant results in both the schema and the node configuration. Potential checks:

schema:
- good RF setting
- potential for huge partitions
- healthy table count
- etc...

configuration:
- latest stable version in use
- MC format in use
- encryption settings
- auth enabled
- not using simpleSnitch
- etc...

//these are just examples, the actual scope to be determined

**Comment by tzach** [comment]
This look like a natural extension for the node_health_check script

**Comment by dyasny** [comment]
I'd rather be able to extend monitoring with this as well as be able to query the health and validity of the setup.

**Comment by tzach** [comment]
> I'd rather be able to extend monitoring with this as well as be able to query the health and validity of the setup.

For sure that will be better and harder to do.

**Comment by dani-tweig** [comment]
@tzach 
Was this implemented in the monitoring?
Is this issue still relevant?

**Comment by tzach** [comment]
This issue can be close. We are gradually implementing this with 
https://github.com/scylladb/scylladb/labels/area%2Fguardrails
