### ISSUE TITLE
Bootstrapping node gets incorrect topology after cluster restart with not all nodes up

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#6088]
Scenario:

1. cluster nodes: n1, n2, n3
2. n1, n2, n3 go down
3. start n1, n2 (n3 still down)
4. add n4

n4 will only know about n1 and n2 and will proceed with bootstrapping as if n3 didn't exist in the ring:

```
INFO  2020-03-26 18:01:10,774 [shard 0] gossip - Known endpoints=[127.0.0.1, 127.0.0.2, 127.0.0.4], current_seeds={127.0.0.1, 127.0.0.2}, seeds_from_config={127.0.0.1, 127.0.0.2}, seen_any_seed=1
INFO  2020-03-26 18:01:10,774 [shard 0] storage_service - JOINING: Starting to bootstrap...
INFO  2020-03-26 18:01:10,896 [shard 0] range_streamer - Bootstrap starts, nr_ranges_remaining=1555
INFO  2020-03-26 18:01:10,896 [shard 0] range_streamer - Bootstrap with [127.0.0.1, 127.0.0.2] for keyspace=system_auth started, nodes_to_stream=2
```

n4 will use incorrect replica sets which can lead to data loss.

That's because topology on the bootstrapping node is derived from gossiped endpoint states. Endpoint states are not persisted, so n1 and n2 forget about n3 when they go down. Until n3 goes back up and advertises itself, other nodes will not be aware of its existence.

The ring information is persisted, so n1 and n2 use the correct topology.

I think we should either:
  1) persist endpoint states across restarts (at least statuses and tokens)
  2) do not use endpoint states to derive topology and do not use them to make topology-related decisions

Solution (1) requires less extensive changes.

**Comment by vladzcloudius** [comment]
Guys, @asias @tgrabiec, I'm a little confused here.
Don't remote nodes persist the bootstrapping node info into `system.peers` early in the bootstrapping process (probably before streaming)?

**Comment by kostja** [comment]
We should be going with 1) using group0. Tokens should be persisted using a group0 state change.

**Comment by kostja** [comment]
> Guys, @asias @tgrabiec, I'm a little confused here. Don't remote nodes persist the bootstrapping node info into `system.peers` early in the bootstrapping process (probably before streaming)?

The peer information is only pesistent once the node switches to NORMAL. While the node is bootstrapping, this information is part of the gossip application state but not persistent in the database.
With raft based topology ops this information should not part of gossip in the first place.

**Comment by vladzcloudius** [comment]
Got it. Thanks.

**Comment by vladzcloudius** [comment]
@asias I have questions about the patch that closed this issue:
* Why n4 can't tell if n3 is part of the ring - ring information is present on every node including n1 and n2. So is the schema. So, n4 should be able to tell just fine that n3 is part of the ring.
* IMO bootstrapping should only be rejected if the `DN` node(s) need to stream data to a joining node - I believe corresponding bits are already part of our code. For example, imagine that n3 belongs to DC2, n1, n2 and n4 - to DC1 and all replicated KSes are using NetworkTopologyStrategy with a replication 0 in DC2. There is no reason whatsoever to fail a bootstrapping in this case AFAIKT. Nor there is a reason to remove n3 too.

@kostja @gleb-cloudius @asias comments are welcome.

**Comment by asias** [comment]
> @asias I have questions about the patch that closed this issue:
> 
>     * Why n4 can't tell if n3 is part of the ring - ring information is present on every node including n1 and n2. So is the schema. So, n4 should be able to tell just fine that n3 is part of the ring.

n4 knows the topology through gossip status. Yes, n1 and n2 knows n3 isl part of the ring before they are shutdown. However, it is possible when n1 and n2 is down, n3 is removed from the cluster. Thus, n1 and n2 could have a wrong topology view that n3 is still part of the ring. This is the that reason, n1 and n2 should not inject gossip status for n3. Instead n3 should advertise n3's gossip status itself. 

>     * IMO bootstrapping should only be rejected if the `DN` node(s) need to stream data to a joining node - I believe corresponding bits are already part of our code. For example, imagine that n3 belongs to DC2, n1, n2 and n4 - to DC1 and all replicated KSes are using NetworkTopologyStrategy with a replication 0 in DC2. There is no reason whatsoever to fail a bootstrapping in this case AFAIKT. Nor there is a reason to remove n3 too.

Note, the patch in question rejects node with unknown status. This means this node could be in any situation, including it is up again but network partitioned from the network.  This node could have wrong token ring and serves request if it misses the new node added into the ring. Nothing prevents a keyspace with other strategy is created. Also we use EverywhereStrategy for system_distributed_everywhere. 

> @kostja @gleb-cloudius @asias comments are welcome.

**Comment by vladzcloudius** [comment]
> > @asias I have questions about the patch that closed this issue:
> > ```
> > * Why n4 can't tell if n3 is part of the ring - ring information is present on every node including n1 and n2. So is the schema. So, n4 should be able to tell just fine that n3 is part of the ring.
> > ```
> 
> n4 knows the topology through gossip status. Yes, n1 and n2 knows n3 isl part of the ring before they are shutdown. However, it is possible when n1 and n2 is down, n3 is removed from the cluster. Thus, n1 and n2 could have a wrong topology view that n3 is still part of the ring. This is the that reason, n1 and n2 should not inject gossip status for n3. Instead n3 should advertise n3's gossip status itself.

I see your point. Yes, we need a majority-based algo to not require all nodes to be up for a topology change. Raft will do ;)

> 
> > ```
> > * IMO bootstrapping should only be rejected if the `DN` node(s) need to stream data to a joining node - I believe corresponding bits are already part of our code. For example, imagine that n3 belongs to DC2, n1, n2 and n4 - to DC1 and all replicated KSes are using NetworkTopologyStrategy with a replication 0 in DC2. There is no reason whatsoever to fail a bootstrapping in this case AFAIKT. Nor there is a reason to remove n3 too.
> > ```
> 
> Note, the patch in question rejects node with unknown status. This means this node could be in any situation, including it is up again but network partitioned from the network. This node could have wrong token ring and serves request if it misses the new node added into the ring. Nothing prevents a keyspace with other strategy is created. Also we use EverywhereStrategy for system_distributed_everywhere.

EverywhereStrategy is not a problem since any alive node can stream such a data.

> 
> > @kostja @gleb-cloudius @asias comments are welcome.

**Comment by asias** [comment]
> > > @asias I have questions about the patch that closed this issue:
> > > ```
> > > * Why n4 can't tell if n3 is part of the ring - ring information is present on every node including n1 and n2. So is the schema. So, n4 should be able to tell just fine that n3 is part of the ring.
> > > ```
> > 
> > 
> > n4 knows the topology through gossip status. Yes, n1 and n2 knows n3 isl part of the ring before they are shutdown. However, it is possible when n1 and n2 is down, n3 is removed from the cluster. Thus, n1 and n2 could have a wrong topology view that n3 is still part of the ring. This is the that reason, n1 and n2 should not inject gossip status for n3. Instead n3 should advertise n3's gossip status itself.
> 
> I see your point. Yes, we need something like a majority-based algo to not require all nodes to be up for a topology change. Raft will do ;)
> 
> > > ```
> > > * IMO bootstrapping should only be rejected if the `DN` node(s) need to stream data to a joining node - I believe corresponding bits are already part of our code. For example, imagine that n3 belongs to DC2, n1, n2 and n4 - to DC1 and all replicated KSes are using NetworkTopologyStrategy with a replication 0 in DC2. There is no reason whatsoever to fail a bootstrapping in this case AFAIKT. Nor there is a reason to remove n3 too.
> > > ```
> > 
> > 
> > Note, the patch in question rejects node with unknown status. This means this node could be in any situation, including it is up again but network partitioned from the network. This node could have wrong token ring and serves request if it misses the new node added into the ring. Nothing prevents a keyspace with other strategy is created. Also we use EverywhereStrategy for system_distributed_everywhere.
> 
> EverywhereStrategy is not a problem since any alive node can stream such a data.

It is not about streaming data. It is about n3 in this case could use wrong topology. When n3 writes to everywhere, it will not write to n4 which is wrong.

**Comment by mykaul** [comment]
@asias - do we need to backport this? To 5.1?

**Comment by asias** [comment]
> @asias - do we need to backport this? To 5.1?

I vote for not backporting. This issue is there since the beginning and it happens only in rare conditions.
