### ISSUE TITLE
Alternator: concurrent TagResource from multiple nodes may race

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#6389]
Tags are stored in a schema table (`system_schema.tables.extensions['tags']`).
This means means that concurrent adding of tags for a single table on more than a single node may result in a race, until Scylla schema agreement is reimplemented to avoid them, or we use some other mechanism to serialize the operation.

**Comment by nyh** [comment]
This problem will be solved automatically when we switch to using Raft for schema operations.

**Comment by nyh** [comment]
At this point, most Alternator table operations like CreateTable already use Raft for serializing the schema operations: The take `mm.start_group0_operation()`, do whatever reading and writing to the schema they want, until finally calling `mm.announce()` to complete the operation. So CreateTable with tags should already be safe.

But this issue still exists because in our `TagResource` implementation (`executor::tag_resource()`) doesn't have this protection: It reads the tags from the current schema, modifies them, and writes them back - without any locking. 

The last "writes them back" step is done in a function `update_tags()` (which in commit 041cb77ad0 @havaker moved to `db/tags/utils.cc). The problem is that this function does both `start_group0_operation()` and `announce()`. This is wrong: The `start_group0_operation` should be called before preparing the new tags based on the old tags to keep the read-modify-write operation atomic. Perhaps `update_tags()` needs to be modified to take not the new `tags_map` but a function which generates these new tags - and this generation function will be called under the lock.

**Comment by denesb** [comment]
Backported to 5.2, 5.4 already has it.

**Comment by denesb** [comment]
Backport to 5.2. dequeued, breaks the build. @nyh please open a backport PR.

**Comment by nyh** [comment]
Doing the backport to 5.2 now.

**Comment by denesb** [comment]
> Created backport PR for 5.2 in #16453

This was queued, so I'm removing the backport labels.
