### ISSUE TITLE
MV may select wrong pending view replica during bootstrap

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#6451]
Node n1,n2,n3, n4 are in the cluster. New node n5 is bootstrapped. 

When a normal writes goes to n1, it eventually calls database::do_apply to apply the write and update the view replica.  The code path is: 
```
database::do_apply -> table::push_view_replica_updates -> table::do_push_view_replica_updates -> table::generate_and_propagate_view_updates -> db::view::mutate_MV -> send to  get_view_natural_endpoint and pending_endpoint
```
It looks like the way we select the pending view replica in  db::view::mutate_MV is not correct. It does not guarantee that the pending endpoint (the one that is bootstrapping) will be the new paired node for the base replica after the bootstrap is done, so we end up missing the view update on the real paired node.  

For example, with RF = 2:

```
                Before            After
Base replicas: n1 n2        ->  n1 n5
View replicas: n3 n4        ->  n2 n3

(before n1 pairs with n3, after n1 pairs with n2)
```

We should send the view replica update to n3 (old paired node for n1) and n2 (new paired node for n1). However, the current code will send the view replica update to n3 (old paired node for n1)  and n5 (pending node).

**Comment by psarna** [comment]
Why will current code send the view replica to n3 and n5? n5 is pending for the base token, but not for the view token - the pending node for the view token seems to be n2 in your example, so the update would be sent to n3 and n2, which is correct.

**Comment by asias** [comment]
> Why will current code send the view replica to n3 and n5? 

It might send view replica to 1) n3 only or  2) both n3 and n5 (if view token happens to in the pending range).

> n5 is pending for the base token, but not for the view token - the pending node for the view token seems to be n2 in your example, so the update would be sent to n3 and n2, which is correct.

pending_endpoints_for(view_token, keyspace_name) returns either empty or n5 (the new node joining the cluster), it will not return an existing node, e.g., n2.

**Comment by asias** [comment]
I think the view replica changes from  n3 n4  to  n2 n3 should not happen if one node is added to the ring.  The ownership either stays the same or one of the existing node is replaced by the new node.  
So, we should have this:

```
                Before            After
Base replicas: n1 n2        ->  n1 n5
View replicas: n3 n4        ->  n3 n4  (Case 1)
View replicas: n3 n4        ->  n3 n5  (Case 2)
View replicas: n3 n4        ->  n5 n4  (Case 3)
```

**Comment by psarna** [comment]
So,
Case 1: a view update is not sent to n5, because it's not pending for the view token, correct
Case 2: a view update is sent to pending n5, which is a correct target
Case 3 : a view update is sent to pending n5, which is a correct target
... isn't it all correct then?

**Comment by asias** [comment]
> So,
> Case 1: a view update is not sent to n5, because it's not pending for the view token, correct
> Case 2: a view update is sent to pending n5, which is a correct target
> Case 3 : a view update is sent to pending n5, which is a correct target
> ... isn't it all correct then?

We are talking about update generated by n1. So in case 2,  view update is not sent to n5. 
The above cases seem to be correct. 

However, in case 2 and case 3, I am not sure if the base / view replicas pair would change to 
```    
               Before            After
Base replicas: n1 n2        ->  n1 n5
View replicas: n3 n4        ->  n5 n3  (Case 2')
View replicas: n3 n4        ->  n4 n5  (Case 3')
```

**Comment by psarna** [comment]
Right, but it's not only n1 that generates updates, it's also n2, so:
* in case 2, n1 would send to n3 and n5, while n2 would send to n3 - the work is doubled, but nonetheless correct
* in case 3, n1 would send to n3 and n4, n2 would send to n4 and n5 - again, one of these updates could be avoided, but still, only the correct replicas got their updates

**Comment by asias** [comment]
> Right, but it's not only n1 that generates updates, it's also n2, so:
> 
>     * in case 2, n1 would send to n3 and n5, while n2 would send to n3 - the work is doubled, but nonetheless correct

In case 2, why would n1 send to both n3 and n5? Before n1 pairs with n3, after it still pairs with n3. I would expect n1 sends to n3 only. 

In case2, before n2 pairs with n4, after n2 is replaced by n5. Why would n2 send to n3?

> 
>     * in case 3, n1 would send to n3 and n4, n2 would send to n4 and n5 - again, one of these updates could be avoided, but still, only the correct replicas got their updates

**Comment by psarna** [comment]
Oh wait, I was talking about Case 2' and 3', didn't see that there are apostrophes added. Let me analyze original 2 and 3 again.

**Comment by psarna** [comment]
I think that with the original cases, the point still stands.
Case 2: n1 sends to n3, n2 sends to n4 and n5
Case 3: n1 sends to n3 and n5, n2 sends to n4
still - each replica that needs to get the mutation gets them, because the final set of replicas for case 2 is {n3, n5}, and for case 3 it's {n4, n5}

**Comment by asias** [comment]
> I think that with the original cases, the point still stands.
> Case 2: n1 sends to n3, n2 sends to n4 and n5
> Case 3: n1 sends to n3 and n5, n2 sends to n4
> still - each replica that needs to get the mutation gets them, because the final set of replicas for case 2 is {n3, n5}, and for case 3 it's {n4, n5}

Yes, this is what I expected for case 2 and case 3 too.

**Comment by asias** [comment]
> Oh wait, I was talking about Case 2' and 3', didn't see that there are apostrophes added. Let me analyze original 2 and 3 again.

OK.  Since you are talking about case 2' and case3'. For case 2',   I think n2 would send to both n3 and n4, not just n3 as you mentioned here https://github.com/scylladb/scylla/issues/6451#issuecomment-628515370.

If case2' and case 3' happen, the current code will not work:

For case2':  n1 should send to n3 and n5, n2 should send to n4 and n3 (does not work, pending node can only be n5, n3 will not be the extra replica)
For case3':  n1 should send to n3 and n4 (does not work, pending node can only be n5, n4 will not be the extra replica ), n2 should send to n4 and n5

**Comment by psarna** [comment]
Hm, I'm not sure if I understand the process as good as you do... Could you expand your examples above with what would be final set of replicas that received view updates? I mean:
For case 2', will the current code end up in sending the view updates to {n3, n4, n5} or {n3, n5} (summing the updates sent from n1 and n2)?
Same for case 3'.

**Comment by asias** [comment]
> Hm, I'm not sure if I understand the process as good as you do... Could you expand your examples above with what would be final set of replicas that received view updates? I mean:
> For case 2', will the current code end up in sending the view updates to {n3, n4, n5} or {n3, n5} (summing the updates sent from n1 and n2)?

I looked get_view_natural_endpoint. I think case 2' will not happen. Because n5 is both base replica and view replica. In get_view_natural_endpoint, n5 will always be paired with n5 itself. So case 2' can only be {n1 paired with n3, n5 paired with n5}, not {n1 paired with n5, n5 paired with n3}.

Let's ignore case2' and case3'. 

And let me try another (better) example:

```
               Before            After
Base replicas: n1 n2        ->  n1 n2
View replicas: n3 n4        ->  n3 n5  (Case 4)
```
Before
{n1 paired with n3, n2 paired with n4}

After
{n1 paired with n3, n2 paired with n5}

With current code, n1 will send view update  to both n3 and n5, n2 will send view update to both n4 and n5 (correct).  The reason n1 is sending to n5 is that, the view token is within the pending ranges (It must be within the pending range, otherwise the view replica after bootstrap will not be n3 and n5). However, n1 sending to n5 is not necessary. As a result, n5 will get N=RF view updates instead one that is paired with it. 

> Same for case 3'.

Let's ignore case3 or case 3' for simplicity, since they are symmetric with case 2 and case 2'.

**Comment by psarna** [comment]
Ok, got it, so this issue is about nodes sending redundant updates during range movements. Which is bad and worth fixing, but at least it does not lead to inconsistencies, only increased network usage.
I guess the fix would be to add some more sophisticated logic to counting pending endpoints - similarly to how the natural endpoint is computed, but for the new range, in order to avoid sending redundant mutations RF times.

**Comment by asias** [comment]
Yes, so far I could not find inconsistency issues which is good.

**Comment by asias** [comment]
Another example: 
```
               Before            After
Base replicas: n1 n2        ->  n1 n2
View replicas: n3 n4        ->  n5 n3  (Case 5)
```

We may end up with:


Before
{n1 paired with n3, n2 paired with n4}

After
{n1 paired with n5, n2 paired with n3}

In this case, n2 should send view update to both n4 and n3, but with current code, n2 will send to n4 and n5 instead.
