### ISSUE TITLE
Check if base64 decoding in Alternator needs to allow inputs without padding

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#6487]
I'm creating this issue based on reviewing the code - it's not based on noticing an actual bug.

The DynamoDB API uses base64 encoding for binary blobs.
The base64 definition, https://tools.ietf.org/html/rfc4648, says that:

> In some circumstances, the use of padding ("=") in base-encoded data is not required or used.

Our `base64_decode()` function indeed just ignores these padding characters, and does not require them. However, I am afraid our newer `base64_len()` and`base64_begins_with()` do assume them and can return incorrect results if the padding is missing.

I think we should test (probably in `test/alternator/test_manual_requests.py`) if DynamoDB allows unpadded base64 strings, and if it does, we should test (perhaps easiest in `test/alternator/test_manual_requests.py`) that the `base64_len()` and `base64_begins_with()` functions work correctly on unpadded encoded strings.

UPDATE: Maybe we don't need to even test if DynamoDB allows unpadded base64 strings - we can just assume that those should be allowed, and support them.

**Comment by psarna** [comment]
For the record, dynamodb replies with:
```json
{
  "__type": "com.amazon.coral.service#SerializationException",
  "Message": "Base64 encoded length is expected a multiple of 4 bytes but found: 11"
}
```

**Comment by psarna** [comment]
I used this quick manual test with pytest:
```python
def test_base64_with_missing_padding(dynamodb, test_table_b):
    payload = '{"TableName": "' + test_table_b.name + '", "Item": {"p": {"B": "YWJjZGVmZ2g"}}}'
    req = get_signed_request(dynamodb, 'PutItem', payload)
    response = requests.post(req.url, headers=req.headers, data=req.body, verify=True)
    print(response, response.text)
    items = test_table_b.scan()
    print(items)
```
with `YWJjZGVmZ2g` being a correct base64-encoded string, but with one `=` padding missing.

**Comment by nyh** [comment]
Interesting, I assume it's the PutItem which failed, not the Scan?
For us, I think it won't fail - our baset64_decode() doesn't check this (we do decode before storing, right?). I think we should be more consistent - either don't allow unpadded base64 at all (as apparently DynamoDB does) or always allow it, but not a mixture of the two.

**Comment by psarna** [comment]
yes, DynamoDB refuses to write an unpadded base64 string. I marked this issue as n00b for now, since I strongly suspect that 99.9% of the drivers provide correct base64 strings and that users don't actually use begins_with operators or size() functions on a binary string that often. Still, we should add a test (e.g. the one I posted above, with some validations added) and make alternator's behavior more consistent, I agree.

**Comment by mykaul** [comment]
I'm opportunistically setting target milestone to 5.2, as I see work in progress on this. If needed, we'll defer to 5.3.

**Comment by avikivity** [comment]
@nyh please evaluate for backport. If it affects only malformed requests, perhaps we don't need to backport it.

**Comment by avikivity** [comment]
@nyh ping

**Comment by avikivity** [comment]
@nyh what can we do to move this?

**Comment by kostja** [comment]
@avi my evaluation is that we do have this code in 5.2, but the impact on possible customers is low (how many customers are using 5.2 with alternator, how many of those depend on blob encoding being with or without padding? what json encoding are they using?) so  my resolution is do not backport.

**Comment by nyh** [comment]
> @nyh please evaluate for backport. If it affects only malformed requests, perhaps we don't need to backport it.

Right - the fix (https://github.com/scylladb/scylladb/pull/11944) just improves error handling. No need to backport.
