### ISSUE TITLE
reimplmenent nodetool in Golang

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#6519]
Scylla version (or git commit hash): 4.x

The Java JMX proxy part of the system is an ongoing source of pain.
See https://github.com/scylladb/scylla/issues/6518 https://github.com/scylladb/scylla/issues/6204  and many more
Reasons are memeory consumption, Java versions.
A Go lang (or similar) implementation, deliver as binary will allow us to fix both.

It would not be a full solution, as there are more Java base tools

**Comment by dorlaor** [comment]
I'd rather invest in sctools instead and with a better
api that will match cloud users patterns

**Comment by kostja** [comment]
Do we need an extra tool at all? Have we considered extending CQL with all the necessary administrative commands? This would greatly simplify test automation.

**Comment by avikivity** [comment]
Good idea.

Snags:
 - nodetool commands used to enable/disable the protocol server
 - we don't want to start the protocol server on a node before it is ready to serve, which may be later in the boot process

We might be able to resolve this with a separate port for administration.

**Comment by tzach** [comment]
Having all (or most) admin operations in CQL is even more useful for Scylla Cloud users, where REST (or JMX , CLI) is not available
In the past we discuss basing both REST and CQL operations on the same underline virtual tables.
This is more natural for queirs (for example node toppartitions ), less so for operations like compaction, drain or decommission.

Note that even if we remove nodetool, we have more Java base tools, so we can not eliminate Java yet.

**Comment by dorlaor** [comment]
On Sun, May 31, 2020 at 4:55 AM Avi Kivity <notifications@github.com> wrote:

> Good idea.
>
> Snags:
>
>    - nodetool commands used to enable/disable the protocol server
>    - we don't want to start the protocol server on a node before it is
>    ready to serve, which may be later in the boot process
>
> We might be able to resolve this with a separate port for administration.
>
If we really want CQL only (REST addition isn't too bad), we can have
two modes, the basic admin which will work by default and will be similar
to REST/JMX in functionality, and the extended, full CQL protocol

**Comment by dyasny** [comment]
We have been discussing an idea of writing a tool that would be tied to the api, basically something that parses the api json files and creates a unified CLI that addresses all of them. It can be a replacement for nodetool with a more automation friendly approach, future proof too (since a change in the api will mean a change in the tool).

I've worked with similar tools in the openstack world, and they were a huge convenience, when the REST API kept getting changed and extended every few months but the CLI tools remained stable without losing functionality

**Comment by amnonh** [comment]
I wouldn't tie it to the current API, it's tightly coupled with the JMX and is too patchy and too much of it is not implemented.

There is an open issue (and some preliminary work) to move the API to a better form.

**Comment by denesb** [comment]
Closing this. It didn't go anywhere and we opted for a scylla-native tool instead (written in C++), see https://github.com/scylladb/scylladb/issues/15588.
