### ISSUE TITLE
Implement join_ring option (coordinator-only nodes)

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#6527]
Cassandra has a configuration option **join_ring**, which if set to false means that the node will join the cluster but without adding any of its own tokens to the ring. In essence this becomes a [proxy node](https://image.slidesharecdn.com/cassandrasummit2016-160913041336/95/cassandra-at-instagram-2016-dikang-gu-facebook-cassandra-summit-2016-17-638.jpg?cb=1473961469), a coordinator only without storing any data. Such a node will parse client-facing protocols (CQL and/or DynamoDB API) but forward the requests further to a relevant node.

We marked this option "Unused" and it is simply ignored. It should be quite easy to support it.

We should also add a dtest to test the correctness of this option. This is what the test might do:
1. Create a cluster with two nodes, one node with join_ring=false (coordinator only), the second node with join_ring=true (a normal node).
2. Create a keyspace with RF=1. Write 10 random partitions into it.
3. Read the 10 rows successfully from the coordinator-only row.
4. Kill the coordinator-only node.
5. Read the 10 rows again, this time from the normal node.
If the last read was successful, we know that the coordinator-only node was not a normal node - were it a normal node, it would have received half of the data (since RF=1) and killing it would have made this data unreadable.

For me, the main motivation for this feature is as yet another way to do load balancing in Alternator, as explained in the Alternator load balancing design document  https://docs.google.com/document/d/1twgrs6IM1B10BswMBUNqm7bwu5HCm47LOYE-Hdhuu_8/edit#heading=h.jzkn8g34hyvh - the benefits are:
1. Because a coordinator-only node does not store data, it can quickly take over a dead node's IP address, allowing quick failover in a DNS-based load balancing implementation. Unlike the "virtual IP address" technique for failover, this one balances the dead node's load equally between all surviving node (and not just a couple), and does not require a lot of IP addresses.
2. Because a coordinator-only node uses significantly less resources than a full node for the same traffic, the standby coordinator-only node described above can be significantly weaker - and cheaper - than regular nodes.
3. Moreover, if a coordinator-only node can handle significantly more throughput than a full node (which is also a replica), it can become a load-balancer that can be used in front of multiple Alternator nodes. The benefit of a coordinator-only node over a TCP or HTTP load balancer is that that the coordinator-only node is a fully token and shard aware load balancer. While standard load balancers send the request to a random node, the coordinator-only node sends the request directly to the right node and shard. This can reduce latency, and increase throughput because wasteful request bouncing is avoided.

**Comment by nyh** [comment]
Note that we had in the past a broken implementation of this option, and it was removed in
https://github.com/scylladb/scylla/commit/998f51579aef1639cf81a57e6fdac29556bb7265

Some discussion about it:
https://groups.google.com/forum/#!msg/scylladb-dev/FueD7O9cuo4/RVxy4OvzAQAJ

**Comment by slivne** [comment]
ref additional discussion if this is needed https://groups.google.com/d/topic/scylladb-dev/C8Gn5QkkaTk/discussion

**Comment by kbr-scylla** [comment]
Nodes with zero tokens will also be useful for https://github.com/scylladb/scylladb/issues/15360
@patjed41 is already working on it.

**Comment by avikivity** [comment]
> Nodes with zero tokens will also be useful for #15360 @patjed41 is already working on it.

Not really necessary as that datacenter would not appear on any replication map. I guess it's needed for SimpleReplicationStrategy, but that should be forbidden.

@raphaelsc the tablet load balancer should exclude nodes with zero tokens.

**Comment by raphaelsc** [comment]
> > Nodes with zero tokens will also be useful for #15360 @patjed41 is already working on it.
> 
> Not really necessary as that datacenter would not appear on any replication map. I guess it's needed for SimpleReplicationStrategy, but that should be forbidden.
> 
> @raphaelsc the tablet load balancer should exclude nodes with zero tokens.

I see Patryk took care of load balancing changes. Good.
