### ISSUE TITLE
compaction_history api does not report rows_merged

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#666]
A call to the API:
curl -X GET --header "Accept: application/json" "http://localhost:10000/compaction_manager/compaction_history"

returns the compaction history but without the row_merged field

**Comment by tzach** [comment]
@amnonh what nodetool operation is affected?

**Comment by raphaelsc** [comment]
@tzach: As far as I can tell, no one. It's just missing information about merged rows in compaction.

**Comment by slivne** [comment]
Raphael I think nodetool compactionhistory does prvide this info

https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsCompactionHistory.html

(scroll down a bit)

**Comment by raphaelsc** [comment]
@slivne: Sorry for not being clear. That's what I meant. We are still missing that information.

**Comment by nirmaayan** [comment]
@slivne do we have expected version for the fix?

**Comment by mykaul** [comment]
@paszkow - is this in review? Where's the PR?

**Comment by paszkow** [comment]
> [@paszkow](https://github.com/paszkow) - is this in review? Where's the PR?

@mykaul Forgot to mention the issue, in the PR's cover letter. Fixed now.
