### ISSUE TITLE
Newly created index resulted in compaction failures and service degradation

### ISSUE THREAD

**Issue by kharmabum** [scylladb/scylladb#6756]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**
Scylla version (or git commit hash): `3.3.0-0.20200319.7ae2cdf46c7` 
Cluster size: `5`
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ScyllaDB 2.3.1 (ami-0402378ae7131b7a0)`

**Issue**
Newly created index `market_forecast_value_market_forecast_id_idx` resulted in errors during compaction (`marshaling error: read_simple_exactly - size mismatch (expected 4, got 7)`) and service degradation. Resolution came in the form of reverting the change by stopping Scylla, removing the index data directory and commitlogs from the moment the change was made and everything after. See log sample below.

This issue may be related to issues we've experienced upgrading our cluster. See https://github.com/scylladb/scylla/issues/6252

**Abbreviated history**
- 2020-07-01 10:00: Index is created, `CREATE INDEX ON markets_dev.market_forecast_value (market_forecast_id);`
- 2020-07-01 10:49: Scylla compaction process is kicked off on all the scylla nodes within a few minutes of each other.
- 2020-07-01 10:54: All but one node `dev-scylla-0` finishes compaction job.
- 2020-07-01 13:29: Error rates increase; read timeouts increase; requests served by instance drops.
- 2020-07-01 15:00: Attempt is made to drop the index via `drop index market_forecast_value_market_forecast_id_idx;` however service is unresponsive and request timeouts after >20 min.
- 2020-07-01 18:13: Attempt to restart the Scylla service, but service would not return until 20 minutes or so has passed. 
- 2020-07-01 18:13: Attempt to stop compactions with `nodetool stop compaction`; however, this command is in a non-working state. The following: `curl --fail -S -s -X POST http://localhost:10000/compaction_manager/stop_compaction?type=COMPACTION` is run instead with no difference in error rates.
- 2020-07-01 18:59: Service stopped
- 2020-07-01 19:35: Based on https://github.com/scylladb/scylla/issues/3262 we remove `market_forecast_value_market_forecast_id_idx_index-c2c23b21bbc211ea807f000000000003` data directory and moved commitlogs modified after 10:00 am to a temp dir (left in /var/lib/scylla/ directory as temp and temp_2); scylla service starts up and runs without issue. 
- 2020-07-02 06:00: Compaction runs on Scylla cluster; errors re-appear in logs.
- 2020-07-02 12:33: Index is dropped successfully via `drop index market_forecast_value_market_forecast_id_idx;`

**Table schema**
```
create table market_forecast_value
(
	region_id int,
	product_id int,
	month text,
	tag text,
	market_forecast_id timeuuid,
	start_time timestamp,
	values frozen<list<frozen<list<double>>>>,
	primary key ((region_id, product_id, month, tag), market_forecast_id)
)
with caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
	and compaction = {'class': 'SizeTieredCompactionStrategy'}
	and compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
	and dclocal_read_repair_chance = 0.1
	and speculative_retry = '99.0PERCENTILE';
```

**scylla.yaml**
```
cluster_name: dev
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "x.x.x.1"
listen_address: x.x.x.4
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: x.x.x.4
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
auto_bootstrap: true
enable_sstables_mc_format: true
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
```

**Log sample**
```
Jul 01 17:46:15 ip-xxx-xx-xx-xxx.us-west-2.compute.internal scylla[13752]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/markets_dev/market_forecast_value-e7b59600f75c11e9a0eb000000000002/mc-3908-big-Data.db:level=0, /var/lib/scylla/data/markets_dev/market_forecast_value-e7b59600f75c11e9a0eb000000000002/mc-3508-big-Data.db:level=0, ]
Jul 01 17:46:16 ip-xxx-xx-xx-xxx.us-west-2.compute.internal scylla[13752]:  [shard 0] view - Building view markets_dev.market_forecast_value_market_forecast_id_idx_index, starting at token minimum token
Jul 01 17:46:16 ip-xxx-xx-xx-xxx.us-west-2.compute.internal scylla[13752]:  [shard 2] database - Schema version changed to 446207be-a1d4-39a6-9910-c92a87907a04
Jul 01 17:46:16 ip-xxx-xx-xx-xxx.us-west-2.compute.internal scylla[13752]:  [shard 0] compaction - Compacted 2 sstables to [/var/lib/scylla/data/markets_dev/market_forecast_value-e7b59600f75c11e9a0eb000000000002/mc-3912-big-Data.db:level=0, ]. 36686656 bytes to 36600917 (~99% of original) in 777ms = 44.92MB/s. ~256 total partitions merged to 84.
Jul 01 17:48:20 ip-xxx-xx-xx-xxx.us-west-2.compute.internal scylla[13752]:  [shard 0] table - failed to write sstable /var/lib/scylla/data/markets_dev/market_forecast_value_market_forecast_id_idx_index-c2c23b21bbc211ea807f000000000003/mc-4-big-Data.db: seastar::internal::backtraced<marshal_exception> (marshaling error: read_simple_exactly - size mismatch (expected 4, got 7) Backtrace:   0x2c54aed
                                                                             0x9fcdee
                                                                             0x444be8
                                                                             0x4d8db7
                                                                             0xe42a3e
                                                                             0xe3945c
                                                                             0xe39a21
                                                                             0xdd4727
                                                                             0xd288d8
                                                                             0xd295b6
                                                                             0x7730ac
                                                                           )
J
```

**Comment by avikivity** [comment]
@psarna @nyh any ideas?

@roydahan please assign someone to try to reproduce with the reported schema and version

**Comment by psarna** [comment]
Since it's Scylla 3.3, a natural suspect would be a missing backport. I didn't manage to reproduce this issue on master, which is good, I'll try 3.3 now.

**Comment by roydahan** [comment]
Hasn't we dropped support from scylla-3.3?

**Comment by psarna** [comment]
I didn't manage to reproduce on 3.3. One more thing to do is to try and decode the backtrace, but it's probably going to just point to an error in deserialization, which wouldn't answer the most important question - how did wrong data end up in the buffer.

**Comment by slivne** [comment]
@kharmabum 
- 3.3 is indeed unsuipported - so if you can upgrade to 4.0, 4.1 we can help
- having said that we would like to test and see if this is reproducible - can you share the sstables from one of the nodes that you got an error for - we will try and build an index on a local node with your schema and see if it reproduces for us as well (you can do that to).

**Comment by kostja** [comment]
Another manifestation of the backpressure problem.
