### ISSUE TITLE
scylla_setup error when install with virtual card network  device

### ISSUE THREAD

**Issue by arita37** [scylladb/scylladb#6757]
*Installation details*
Scylla version (or git commit hash):  2019.1 ENT
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7.2

Please select a NIC from the following list:
> XXXXX

```
Error when installing with scylla-setup with virtual NIC :
ERROR: Not supported virtual device eno3.1038. Your system can't be tuned until the issue is fixed.
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla_sysconfig_setup", line 75, in <module>
    rps_cpus = out('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname))
  File "/usr/lib/scylla/scylla_util.py", line 279, in out
    return subprocess.check_output(cmd, shell=shell).strip().decode('utf-8')
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/lib/scylla/perftune.py', '--tune', 'disks', '--dir', '/var/lib/scylla/data', '--dir', '/var/lib/scylla/commitlog', '--dir', '/var/lib/scylla/hints', '--dir', '/var/lib/scylla/view_hints', '--tune', 'net', '--nic', 'eno3.1038', '--get-cpu-mask']' returned non-zero exit status 1.
NIC queue setup failed. Press any key to continue...

```

**Comment by dorlaor** [comment]
Weird, until it's solved, you can bypass the network setup, it 'only' puts
the NIC
in the right multi-queue or single queue mode. If the script doesn't allow
you
to bypass it, run the setup script w/o the --nic parameter.

usr/lib/scylla/perftune.py', '--tune', 'disks', '--dir',
'/var/lib/scylla/data', '--dir', '/var/lib/scylla/commitlog', '--dir',
'/var/lib/scylla/hints', '--dir', '/var/lib/scylla/view_hints',
'--tune', 'net', '--nic', 'eno3.1038', '--get-cpu-mask']'

**Comment by arita37** [comment]
There are 2 NIC on the node :
    eno3 (dummy) and eno3.1038

We suspect if the wrong NIC is input,
It leads to crash the node itself. (I/O is locked, no ssh possible in the node).

Node is bare metal.

**Comment by syuu1228** [comment]
Isn't it eno3.1038 is a virtual interface for VLAN?
The error is caused by perftune.py, it says the NIC does not tuneable since it's virtual device:
https://github.com/scylladb/seastar/blob/master/scripts/perftune.py#L540

I guess `eno3` instead of `eno3.1038` may work, even if you want run Scylla on the VLAN (because the NIC parameter is just for HW parameter tune-up, does nothing for listening port)

**Comment by arita37** [comment]
Thanka for replying.

eno3 is dummy one
Actual one ia eno3.1038

Scylla still works even after this msg in scylla_setup.


How much the NIC tuning 
actually impacts perfs  ?
(Does it matter ?)


Thanks

**Comment by vladzcloudius** [comment]
@arita37 Please, send us the output of following commands:

```
ifconfig -a
ethtool -i eno3
ethtool -i eno3.1038
```

Thanks.
