### ISSUE TITLE
Limit scale and precision of numbers in Alternator

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#6794]
DynamoDB has a number type - for integers and floating point - which doesn't match any of the standard C++ types. It is basically a floating point number with 38 _decimal_ digits of precision and decimal exponent between -130 and 125 - see more information 
[here](https://docs.google.com/document/d/1i4yjF5OSAazAY_-T8CBce9-2ykW4twx_E_Nt2zDoOVs/edit#heading=h.vvocat9deqa9) or [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes).

In Alternator we implemented this number type using Scylla's `big_decimal` type. However, `big_decimal` (based on Java's `BigDecimal`) is an overkill: it allows for numbers of _unlimited_ precision and huge scales - far beyond what DynamoDB allows.

The risk is that Alternator users may discover these unlimited-precision numbers in Alternator, and come to rely on them, so if in the future we may want to change the implementation of numbers (e.g., to make them take less space), these use cases will break. 

When DynamoDB attempts to store or calculate numbers with excessive scale or precision, it produces an error and refuses to store such overflowing or over-precise numbers. We should behave similarly.

**Comment by nyh** [comment]
I just added in `test_number.py` four xfailing tests which demonstrate four aspects of this issue:

1. `test_number_magnitude_not_allowed` demonstrates that numbers with excessive magnitude can be stored.
2. `test_number_precision_not_allowed` demonstrates that numbers with excessive precision can be stored.
3. `test_update_expression_plus_overflow` demonstrates that numbers with excessive magnitude can be the result of a sum operation.
4. `test_update_expression_plus_imprecise` demonstrates that numbers with excessive precision can be the result of a sum operation.

**Comment by nyh** [comment]
Unlimited precision also carries a risk of a DoS attack against Scylla: A malicious user might create a value of 1.0 and then ask to add 1e-1000000000 to it. This addition requires 1000000000 digits, and can cause unlimited CPU usage, non-preemption, and unlimited memory usage. One way to completely avoid this risk is to limit the exponent of all numbers.

**Comment by nyh** [comment]
Although I added the "Security" tag to this issue, note that as far as security issues go, this one is, at the moment, fairly minor:
It's "only" about a DoS, not privilege elevation, and moreover - it only allows an authenticated user to perform the DoS. This makes is less of a performance in a single-tenant installation, because only the tenant can ruin its own performance. But there's still a risk even in single-tenant installations in **certain workload**: If an application does number additions, and if an end-user could cause the database to insert arbitrary numbers into this addition work, inserting data like 1e-1000000 can cause the database to waste memory or CPU, or reach std::bad_alloc.

**Comment by cvybhu** [comment]
I remember that there was a similar issue with `toJson`: #8002, doing `toJson(1e1000000)` caused an OOM. Perhaps it could also be qualified as DoS/Security.

**Comment by denesb** [comment]
This fixes a minor issue, and is already part of 5.4. Not backporting further.
