### ISSUE TITLE
cqlsh return the wrong version string in status line

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#680]
When using cqlsh to connect to scylla, it return the following

```
Connected to Test Cluster at 127.0.0.1:9052.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
```

Although scylla is indeed compatible to Cassandra 2.1.8, it will be better to return Scylla version:

```
[cqlsh 5.0.1 | Scylla 0.13.1 | CQL spec 3.2.0 | Native protocol v3]
```

The current result is confusing when working with both servers.

**Comment by slivne** [comment]
I think we have been through this in the past and Glauber even changed that and we rolled that back - in the previous itteration the decision was to stick with cassandra 2.1.8 because we did not know how and if this will affect the drivers / clients etc ?

I am not sure if we have an answer what side effects this change may cause.

**Comment by tzach** [comment]
At least for me, as a user, this is annoying and confusing. Where is this value is taken from?

If it break drivers than we should not change it.
if it only affect cqlsh, we should.

**Comment by penberg** [comment]
@slivne, @tzach, we cannot change the Cassandra version number because the drivers use that to auto-negotiate the CQL binary protocol version.

What we can do is something like this in ``cqlsh``:

```
diff --git a/bin/cqlsh b/bin/cqlsh
index f37e0db..066b5de 100755
--- a/bin/cqlsh
+++ b/bin/cqlsh
@@ -721,7 +721,7 @@ class Shell(cmd.Cmd):
         # system.Versions['cql'] apparently does not reflect changes with
         # set_cql_version.
         vers['cql'] = self.cql_version
-        print "[cqlsh %(shver)s | Cassandra %(build)s | CQL spec %(cql)s | Native protocol v%(protocol)s]" % vers
+        print "[cqlsh %(shver)s | Scylla [Cassandra %(build)s] | CQL spec %(cql)s | Native protocol v%(protocol)s]" % vers
 
     def show_session(self, sessionid):
         print_trace_session(self, self.session, sessionid)
```

which makes the interactive shell look like this:

```
[penberg@nero scylla-tools-java]$ ./bin/cqlsh --no-color
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Scylla [Cassandra 2.1.8] | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
```

**Comment by tzach** [comment]
Bringing this back, because its confusing and misleading, and the Cassandra version is even less relevant.
Can we update CQLsh to *add* a new filed with the Scylla version (something like @penberg suggested?)

The same goes for nodetool
```
> nodetool version
ReleaseVersion: 3.0.8
```
For nodetool, if we switch to [Scylla Driver fork](https://github.com/scylladb/java-driver/) we have more control of the version presentation.

**Comment by nyh** [comment]
Created https://github.com/scylladb/scylla-cqlsh/issues/9 in the cqlsh repository, and closing this issue.
