### ISSUE TITLE
STCS is quite inefficient getting rid of expired SSTables in workloads with default TTL

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#6895]
In a workload where data is only written with default TTL, STCS can do way better when getting rid of expired data. In a real world use case, it was found that lots of expired SSTables (hundreds of GBs) had no blockers, meaning they could be purged right away, but they weren't being selected by compaction because of the strategy heuristics which waits for N similar-sized SSTables before compacting them.

This problem can be easily fixed by making the strategy check for fully expired SSTables in a given time interval, similar to TWCS. In TWCS, the time interval can be controlled by compaction property expired_sstable_check_frequency_seconds.

**Comment by slivne** [comment]
cases which are timeseries with expiration or default ttl should use TWCS and not use STCS.

**Comment by raphaelsc** [comment]
STCS mixes old and new data, making it hard to purge expired data in a timely manner. ICS has a more aggressive cross-tier comapction, but that's because it can afford it due to its incremental compaction. Closing this issue as won't fix.
