### ISSUE TITLE
CQLSh only Docker

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#6981]
When using a remote Scylla service, like Scylla Cloud, one need an easy way to run CQLSh to interact with the server.
The only official Docker instance includes Scylla server, which is not required here.
We should provide a minimal instance with tooling for a remote access like CQLSh, cassandra-stress.

**Comment by slivne** [comment]
@tzach there are more tools than CQLSH user can use - cassandra-stress / sstableloader - I do not see why CQLSH is different (I certainly don;t want to start creating dockers for evert permutation) - I think a good compromise is to ask users to use scylla docker (although it also contains scylla)

**Comment by tzach** [comment]
@slivne I did mention cassandra-stress in the original issue...
Running Scylla is problematic since its easy to connect to it instead of the actual DB you want to use.
See an examples:
https://hub.docker.com/r/mongoclient/mongoclient/

**Comment by tzach** [comment]
The new cqlsh fork https://github.com/scylladb/scylla-cqlsh will allow to download cqlsh from PyPi, and in the future, if we want to as an independent docker

**Comment by mykaul** [comment]
@fruch - I believe you are already working on it / done?

**Comment by fruch** [comment]
> @fruch - I believe you are already working on it / done?

yes, it was done in: 
https://github.com/scylladb/scylla-cqlsh/pull/14

images would be available at:
https://hub.docker.com/r/scylladb/scylla-cqlsh/tags

**Comment by fruch** [comment]
@tzach 

I was pushing to get cqlsh replaced on core, that I didn't thought about publishing the fact we have a docker images to the world.

**Comment by tzach** [comment]
There is now an offical docker image for CQLSh https://hub.docker.com/r/scylladb/scylla-cqlsh

**Comment by tzach** [comment]
Thanks @fruch
