### ISSUE TITLE
sstableloader should warn in case a ks/cf directory holds sstables with an unknown format

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#7035]
sstaleloader today emits stats for its run

We need to add a stat + warning that sstable loader failed to upload sstables of unknown format.

**Comment by elcallio** [comment]
Not sure what you are aiming for here, or what the use case/point of pain is? The SSTable parser code in origin (which is what read stuff for sstableloader) does validation of format, in the sense that it checks if it is too old (or in general not recognized), but for it sort of assumes that formats _newer_ than the "current" one (mc) are enough backwards compatible that they can be read. 

Do we have a case where a new format (md?) cannot be parsed by a mc parser?

**Comment by elcallio** [comment]
See /scylladb/scylla-tools-java#196

**Comment by slivne** [comment]
Lets add a test for this

**Comment by roydahan** [comment]
added a task for it.

**Comment by amoskong** [comment]
Hi @elcallio 

By default TYPE:CUSTOM will be returned from `Type.fromRepresentation(path.right)` if path.right doesn't match any TYPE.
So IllegalStateException or IllegalArgumentException will never be raised.

The only way to trigger the `"Skipping file {} - unsupported SSTable format or version"` is using a invalid prefix for sstables, and trigger UnsupportedOperationException first.

**Comment by elcallio** [comment]
Yes, I know this. My question was "why is this a problem"? Is there a case with sstables that cannot be properly enough parsed in backwards compatible parsing mode that should result from opening something not explicitly supported?
