### ISSUE TITLE
test_topology_change_in_presence_of_down_node fails since gotten rid of seed concept

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#7087]
Since 3b1ff90a1a80c4b0d2b6784de052a376ad75e7ee
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/581/testReport/paxos_tests/TestPaxos/test_topology_change_in_presence_of_down_node/ fails as follows:
```
Unexpected errors found: [('node7', ['ERROR 2020-08-18 14:39:25,814 [shard 0] init - Startup failed: std::runtime_error ({shard 0: std::runtime_error (Repair mandatory neighbor=127.0.79.4 is not alive, keyspace=system_auth, mandatory_neighbors={127.0.79.4}), shard 1: std::runtime_error (Repair mandatory neighbor=127.0.79.4 is not alive, keyspace=system_auth, mandatory_neighbors={127.0.79.4})})', 'ERROR 2020-08-18 14:39:25,603 [shard 0] repair - Repair 15 out of 256 ranges, id=[id=1, uuid=57053bb3-4777-4f41-b59c-4ca54d7ebc96], shard=0, keyspace=system_auth, table={role_members, roles}, range=(7831588158035343013, 7846371413714673545], peers={127.0.79.4}, live_peers={}, status=failed: mandatory neighbor=127.0.79.4 is not alive', 'ERROR 2020-08-18 14:39:25,603 [shard 1] repair - Repair 15 out of 256 ranges, id=[id=1, uuid=57053bb3-4777-4f41-b59c-4ca54d7ebc96], shard=1, keyspace=system_auth, table={role_members, roles}, range=(7831588158035343013, 7846371413714673545], peers={127.0.79.4}, live_peers={}, status=failed: mandatory neighbor=127.0.79.4 is not alive'])]
```

And the node fails to start, and reported as yet another failure (but it's the same one)
```
The process is dead, returncode=1
```

This seems 100% reproducible at 3b1ff90a1a80c4b0d2b6784de052a376ad75e7ee
and passes at 5356e8319dea73455b8cba0551d672ea3e4327fb

Note that to run the dtest locally, you need to remove the `@since('3.0')` decoration on this test case (See https://github.com/scylladb/scylla-dtest/issues/1641)
like this:
```diff
diff --git a/paxos_tests.py b/paxos_tests.py
index 14958d25..dec40024 100644
--- a/paxos_tests.py
+++ b/paxos_tests.py
@@ -296,7 +296,6 @@ class TestPaxos(Tester):
             loaders[node].stop()
             del loaders[node]
 
-    @since('3.3')
     def test_topology_change_in_presence_of_down_node(self):
         session = self.prepare(nodes=6, rf=4)
         lower_node_limit = 3
```

**Comment by bhalevy** [comment]
@asias do you have a fix for this issue?

**Comment by kostja** [comment]
@ManManson could you please share an update of your findings too?

**Comment by asias** [comment]
The test is problematic. When we bootstrap a node, a node that is losing the range is a mandatory node to sync data with. In the test, the mandatory node is down, it is expected the bootstrap will fail.

**Comment by ManManson** [comment]
That's the same conclusion that I have come to. I've thought if there is any way to restore the old behavior for the test, i.e. disable auto bootstrapping for nodes which is default after the patch from @asias. But given more thought now I think that was a bad idea, so I am thinking of some other way to fix the test.

**Comment by ManManson** [comment]
@asias Is there any legitimate way to work around this? It looks to me as a serious regression if we are now more restricted on how to perform topology changes in presence of down nodes.

If so, maybe it would be better to investigate further and revert the patch in the meanwhile?

**Comment by ManManson** [comment]
Cc @kostja

**Comment by asias** [comment]
> @asias Is there any legitimate way to work around this? It looks to me as a serious regression if we are now more restricted on how to perform topology changes in presence of down nodes.
> 
> If so, maybe it would be better to investigate further and revert the patch in the meanwhile?

We are now preferring safety more. If a node is down, we should fix the down node and then add the new node. What are the test test_topology_change_in_presence_of_down_node trying to test? I do not think it makes sense to revert the repair based node operations patch because this test fails.

**Comment by ManManson** [comment]
I believe what test does is testing that we are able to add and remove nodes while the cluster is in a degraded state.

So that means now the test is invalid and we cannot add new nodes until all the existing ones are up and healthy?

**Comment by asias** [comment]
> I believe what test does is testing that we are able to add and remove nodes while the cluster is in a degraded state.

BTW, this test does not look like related to paxos? Why such test is in paxos_tests.py. 

> So that means now the test is invalid and we cannot add new nodes until all the existing ones are up and healthy?

It is not a must all node needs to be up. We require the node losing the range to be up because otherwise we might lose data.

Anway, we need to adjust the test.

**Comment by kostja** [comment]
The test is testing that such a use case does not break paxos consistency.
The test can be adjusted.

**Comment by avikivity** [comment]
> 
> It is not a must all node needs to be up. We require the node losing the range to be up because otherwise we might lose data.
> 

In a cluster that is smaller than 256 nodes every node loses a range.

Aren't repair-based operations supposed to prevent data loss in this case? Bootstrap should read data from two live replicas instead of the dead replica that is losing the range.

> Anway, we need to adjust the test.

**Comment by asias** [comment]
> > It is not a must all node needs to be up. We require the node losing the range to be up because otherwise we might lose data.
> 
> In a cluster that is smaller than 256 nodes every node loses a range.
> 
> Aren't repair-based operations supposed to prevent data loss in this case? Bootstrap should read data from two live replicas instead of the dead replica that is losing the range.


If the node is temporarily down, sync from more than 1 node is a waste. 

It is also unsafe. Consider RF = 3,  READ = 3, Write = 1, n1: new, n2: old, n3: old. N1 is losing the range. n4 bootstraps from n2 and n3. We would end up with n2: old, n3 : old, n4: old. Reads will get wrong data.

**Comment by avikivity** [comment]
> > > It is not a must all node needs to be up. We require the node losing the range to be up because otherwise we might lose data.
> > 
> > 
> > In a cluster that is smaller than 256 nodes every node loses a range.
> > Aren't repair-based operations supposed to prevent data loss in this case? Bootstrap should read data from two live replicas instead of the dead replica that is losing the range.
> 
> If the node is temporarily down, sync from more than 1 node is a waste.
> 

What if it is down for an extended period and we are bringing up the new node because of that?

> It is also unsafe. Consider RF = 3, READ = 3, Write = 1, n1: new, n2: old, n3: old. N1 is losing the range. n4 bootstraps from n2 and n3. We would end up with n2: old, n3 : old, n4: old. Reads will get wrong data.

We should optimize for the common case of R=QUORUM/W=QUORUM. I agree we should support ALL/ONE, but not at the expense of Q/Q.

We can have a repair_policy section in the table definition, which says which consistency model the table is using (Q/Q or A/O or O/A) and reject node operations on the latter if a node is down.

**Comment by avikivity** [comment]
(O/A or A/O lose availability if a node is down anyway)

**Comment by asias** [comment]
> > > > It is not a must all node needs to be up. We require the node losing the range to be up because otherwise we might lose data.
> > > 
> > > 
> > > In a cluster that is smaller than 256 nodes every node loses a range.
> > > Aren't repair-based operations supposed to prevent data loss in this case? Bootstrap should read data from two live replicas instead of the dead replica that is losing the range.
> > 
> > 
> > If the node is temporarily down, sync from more than 1 node is a waste.
> 
> What if it is down for an extended period and we are bringing up the new node because of that?

We can bring up a new node to replacing the dead node.

> 
> > It is also unsafe. Consider RF = 3, READ = 3, Write = 1, n1: new, n2: old, n3: old. N1 is losing the range. n4 bootstraps from n2 and n3. We would end up with n2: old, n3 : old, n4: old. Reads will get wrong data.
> 
> We should optimize for the common case of R=QUORUM/W=QUORUM. I agree we should support ALL/ONE, but not at the expense of Q/Q.


Support of ALL/ONE consistency  is only one of the reasons we require nodes to be up during bootstrap (topology change). 
Another reason is the down node might be partitioned and use the right token ring.  For example, a node is partitioned in network, a topology change is performed, the topology change can succeed without the partitioned node being aware of this change, as a result reads and writes to the partitioned node will use the old topology causing consistency issue. 
Here is an example, before the topology change, the partitioned node thinks replicas are in n1,n2,n3. After the topology changes, the new replicas set is in n1,n4,n5. A client can write to n2, n3, but read from n4, n5. Even quorum read / write will give  wrong results. 

> We can have a repair_policy section in the table definition, which says which consistency model the table is using (Q/Q or A/O or O/A) and reject node operations on the latter if a node is down.

Can user use different consistency model over time or by different clients?

**Comment by asias** [comment]
> (O/A or A/O lose availability if a node is down anyway)

Yes, but it is better to fail the request than giving wrong answer.

**Comment by DoronArazii** [comment]
@kostja are we planning to solve this for 5.1?

**Comment by kostja** [comment]
The test is not related to raft in any way. It can be fixed by anyone. I don't have it on my todo list.

**Comment by DoronArazii** [comment]
@eliransin please have a look (it seems to be old)

**Comment by kostja** [comment]
@gusev-p could you pleaes take a moment to remove this test from dtest and we'll close this one? The test is superseded by the work we do now in test.py. Thanks!

**Comment by DoronArazii** [comment]
@gusev-p i'm doing some work to clean 5.2 from unplanned issues.
It's in your queue?

**Comment by gusev-p** [comment]
> @gusev-p i'm doing some work to clean 5.2 from unplanned issues.
> It's in your queue?

Not yet. Is it urgent?

**Comment by DoronArazii** [comment]
I don't know, maybe ask Kostja about it.
Anyway, if it's not in your queue - i'm pushing it into the large backlog (5.x) until you'll attack it someday in other OSS version.

**Comment by DoronArazii** [comment]
@bhalevy AFAICS it's last seen at 2020 - do we still need to track this?

**Comment by bhalevy** [comment]
no
