### ISSUE TITLE
Split the WHERE-clause expression into two parts: primary-key slice and filter

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylladb#7217]
This has been [suggested](https://github.com/scylladb/scylla/pull/5763#discussion_r443211311) [twice](https://github.com/scylladb/scylla/pull/7143#discussion_r479616235) in PR reviews.  It will simplify evaluating the primary-key slice to fetch from storage and make it possible to neatly implement compilation of the filter subexpression.

Once we split the expression, we can simplify `statement_restrictions` to only keep the subexpressions while providing to its clients the same functionality it provides today.

Existence of secondary indexes will complicate this and must be handled correctly.

**Comment by dekimir** [comment]
This is covered in the plan for CQL rewrite (see #3815).

**Comment by kostja** [comment]
Not a bug, CQL rewrite is implemented.
