### ISSUE TITLE
Investigate consensus protocol for membership and ownership

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#7221]
Instead of relying on gossip for node status propagation, use a consensus protocol to guarantee propagation.
Similar to #1461

**Comment by tzach** [comment]
Similar Apache Cassandra request https://issues.apache.org/jira/browse/CASSANDRA-9667

**Comment by avikivity** [comment]
Those issues can never be closed. Consider not opening them at all.

**Comment by kostja** [comment]
Investigation is done and we're making strides with the implementation.
