### ISSUE TITLE
Make schema change reconcilitation more robust

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#724]
In C*, alter statement will create a new `CFMetaData` object by copying and altering the old one. That's respectively being implemented in our `schema_builder`. The problem with this approach is that the new object looses knowledge of what is actually being altered. 

We don't coordinate schema changes globally because we want to maintain high availability. The schema changes are made eventually consistent by the means of commutativity of their mutations. When we execute a schema change statement, we need to emit mutations corresponding to the change. C\* does it by calculating a diff between the old and new schema objects (`CFMetaData.toSchemaUpdate`). Because it doesn't know what was affected by the statement it makes some assumptions. It always adds all properties and definitions with current timestamp as if the statement redefined all of them. I think this can lead to lost schema changes when there's a need to reconcile changes made on different coordinating nodes. Mutations from one statement will override effects of the other statement even if they were not conflicting, eg. first statement sets property X, second statement sets property Y. 

A way to solve this is to make alter statements pass down not full schema object but a change object which encapsulates the intent of change. Those objects could then be asked to give mutations for the change. The new schema object would be built using the current algorithm which creates it from mutations after merging the change with current schema's mutations.

**Comment by tgrabiec** [comment]
Related to https://issues.apache.org/jira/browse/CASSANDRA-10250

**Comment by kostja** [comment]
@tgrabiec is this still relevant?

**Comment by avikivity** [comment]
obsoleted by consistent schema
