### ISSUE TITLE
Allow throttling repair-based node ops

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#7255]
*Installation details*
Scylla version: 5f541fbdc55be813e99ff3c0f7ae6034b2908e3a

*Description*
During the PR review I asked for tunables that would allow throttling the repair/streaming intensity of the repair-based node ops.

For instance: 
* How many shards should be repairing/streaming at the same time.
* How many ranges in parallel should the repair be streaming on each shard.

These are what we already have for a repair throttling in SM today.

In addition it would be nice to be able to limit the maximum bandwidth the streaming is allowed to consume.

Without these repair-based node ops are going to overload the cluster similarly to how the regular repair overloads it today unless throttled, which in line will make users disable it at the spot.

**Comment by vladzcloudius** [comment]
@asias @bhalevy @gnumoreno @eyalgutkind @eliransin @slivne @avikivity FYI

**Comment by dorlaor** [comment]
Vlad, don't tag the entire world. Also, Asias has an idea how to throttle
this
in a different way. Not to mention it's time that the repair itself will
'behave'
according to our schedulers and no throttling will be needed but we do have
a plan already, Asias is welcome to point you to the github issue (I hope
one exists)
and close this one in return

**Comment by asias** [comment]
We have those for regular repair

https://github.com/scylladb/scylla/issues/4847
https://github.com/scylladb/scylla/pull/4848

Avi rejected the idea to allow user to control the parallelism though.

The repair bandwidth limiter idea is not translated to github issue yet.

**Comment by dorlaor** [comment]
Here's the design doc: https://docs.google.com/document/d/1VmSK3GwhZSX4v6hCGlLrbGn-2Wh8ysh2U1o0bieajQM/edit

**Comment by vladzcloudius** [comment]
@dorlaor Only relevant people were tagged.

@dorlaor @asias This design is very nice and cool but I don't see how this is going to be read sooner than a year from now.

The change I'm suggesting is a trivial change. As I described, without it the repair-based ops feature is as good as dead.

@asias Do we have preformance testing numbers? Something more challenging, like LCS + data uniformly distributed in the range between 300B and 500MB + read latency SLA below 10ms in 99th + make sure data is reasonably inconsistent (restart the service on different nodes a few times during the loading stage including the one that is going to be decommissioned).

And then try to decommission/bootstrap/replace a node.

Do we know how new feature behaves compared to the regular streaming?

I have a strong felling that we may see that latencies are going to be heavily impacted.

However, Dor, if we had the controls that I've requested - it would be possible to control the intensity of the repair and thereby - the latencies.

**Comment by vladzcloudius** [comment]
> We have those for regular repair
> 
> #4847
> #4848
> 
> Avi rejected the idea to allow user to control the parallelism though.
> 
> The repair bandwidth limiter idea is not translated to github issue yet.

I've just read the discussion on the PR above and I totally agree with @asias there.
I think his arguments there are totally in line with my vision (as described above) and with what we see every time we stream in the real life.

**Comment by bhalevy** [comment]
@xemul waht needs to be done to resolve this issue with the new i/o scheduler rate limiting?

**Comment by xemul** [comment]
Add a config option that would put bandwidth limit on the relevant sched group. I'm doing this for compaction sched group currently.

**Comment by xemul** [comment]
Presumably 1f21c1ecc8e90d2bced38c019b1de0b3f651ddf1 fixes it
