### ISSUE TITLE
std::out_of_range during nodetool removenode

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#7366]
Running the latest scylla jepsen from https://github.com/scylladb/jepsen one can occasionally observe:
```
lein run test -w list-append --nemesis partition,remove --nemesis-interval 5 --time-limit 500
```
```
Scylla API server HTTP POST to URL '/storage_service/remove_node' failed: std::out_of_range
```

There may be some issues with formatting of removenode arguments, but this shouldn't lead to HTTP 500 response and std::out_of_range.

**Comment by bhalevy** [comment]
s/rande/range/ in title

**Comment by asias** [comment]
what parameter was sent exactly?

**Comment by asias** [comment]
Here is a pointer:

 476     ss::remove_node.set(r, [](std::unique_ptr<request> req) {
 477         auto host_id = req->get_query_param("host_id");
 478         return service::get_local_storage_service().removenode(host_id).then([] {
 479             return make_ready_future<json::json_return_type>(json_void());
 480         });
 481     });

We can validate the input.

**Comment by slivne** [comment]
@kostja any idea - so we can try and fix this

**Comment by kostja** [comment]
Ok, we can look into this.

**Comment by kostja** [comment]
Has rotten, closing.
