### ISSUE TITLE
Dump diagnostics on SIGQUIT

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#7400]
From @avikivity:
>   - add a SIGQUIT[1] handler and dump it from there too (we should dump as much info as we can on SIGQUIT, not just this).
>
> [1] similar to how the JVM performs a thread dump on SIGQUIT.

We should dump [memory (#6365)](https://github.com/scylladb/scylla/issues/6365) and [reader permit (#7398)](https://github.com/scylladb/scylla/issues/7398) and any other diagnostics we add in the future.

**Comment by denesb** [comment]
In a previous life we had the SIGQUIT handler read a file from a known location, where you could configure what to dump exactly. We can do this to specify the shard/semaphore/etc. to reduce the scope for the dump, with the default being dumping everything (if the file doesn't exist or is empty).

**Comment by fee-mendes** [comment]
Lobbying for it
