### ISSUE TITLE
Failed schema pulls are not retried which may leave the cluster in schema disagreement

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#7426]
Schema pull is triggered in reaction to changes of advertised schema versions. Currently, if the pull fails it is not retried. This may leave the cluster in schema version disagreement until the next schema change. 

We should retry failed pulls.

One way is to give up on triggering pulls from change listeners entirely and have a worker fiber which keeps issuing pulls based on current state. This has the advantage over listener-based approach because it covers all possible changes of conditions which are involved in the failure logic. The disadvantage is that it requires continuous polling for state. If the number of endpoints is not large that shouldn't be a problem.

Refs #7396.

**Comment by kostja** [comment]
May be way less relevant with Raft where the leader is responsible for constantly pushing the state to the follower. We still perform schema pulls on schema mismatch to provide liveness in an isolated minority, but if that fails, it will be retried.

**Comment by tgrabiec** [comment]
There is a patch set on the mailing list which fixes it for gossip: "migration_manager: Make schema pulls more robust".

Agree that it will be obsoleted by RAFT when we switch to it.

**Comment by avikivity** [comment]
We'll have to keep gossip for a while so better to fix it for gossip too.

**Comment by kostja** [comment]
The patch set for the non-raft implementation has rotten and the raft has no issue. I don't think we realistically can get to fixing the non-raft branch. Closing.
