### ISSUE TITLE
scylla_bootparam_setup uses TSC clocksource even on AWS Nitro VMs where it is not recommended

### ISSUE THREAD

**Issue by ziggythehamster** [scylladb/scylladb#7444]
According to [AWS Support](https://aws.amazon.com/premiumsupport/knowledge-center/manage-ec2-linux-clock-source/) and the [relevant optimization procedure](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-os.html), scylla_bootparam_setup should only switch to the TSC clock source on Xen VMs, not Nitro VMs. I'm not sure how you tell you're on a Nitro VM, but checking if `/sys/devices/system/clocksource/clocksource0/available_clocksource` contains `kvm-clock` should be sufficient (and then I guess set the clocksource to kvm-clock instead of tsc).

If there's a reason why TSC is better than the recommended clock on Nitro VMs, then it would be helpful to document that.

**Comment by avikivity** [comment]
I suppose we could check if the clocksource is kvm-clock, and not touch it if that's the case.

**Comment by syuu1228** [comment]
We currently setting clocksource=tsc as boot parameter, we have to stop it.
We need to configure clocksource on instance boot time instead, and use tsc only when the instance running on Xen.

**Comment by syuu1228** [comment]
Sent PR to use kvm-clock on perftune.py --tune-clock, also needed patch for scylla-machine-image to use it.

**Comment by vladzcloudius** [comment]
> I suppose we could check if the clocksource is kvm-clock, and not touch it if that's the case.

This is already supposed to be the case: https://github.com/scylladb/seastar/blob/master/scripts/perftune.py#L854

**Comment by yaronkaikov** [comment]
@syuu1228 Is this relevant?

**Comment by syuu1228** [comment]
This is fixed, closing
