### ISSUE TITLE
Config file workdir option not working

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylladb#7478]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.2 5fcc1f20

Setting workdir param

```
# Directory where Scylla should store all its files, which are commitlog,
# data, hints, view_hints and saved_caches subdirectories. All of these
# subs can be overriden by the respective options below.
# If unset, the value defaults to /var/lib/scylla
workdir: /home/michal/scylla/
```

results in 

```
WARN  2020-10-22 15:25:45,067 [shard 0] init - Unknown option : workdir
```

and config option is not applied.

**Comment by mmatczuk** [comment]
In master this can be added to the `matches` function added to `config_src`.

**Comment by Reimus** [comment]
I confirm in Scylla version 4.3 Docker image: scylladb/scylla:4.3.0 the issue still exists.

Workdir is respected by IO setup script. It tests directory properly, but once main program runs, warning is issued

WARN  2021-02-17 18:14:50,179 [shard 0] init - Unknown option : workdir

Main program still uses /var/lib/scylla for the workdir.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1. 5.2 has the fix.
