### ISSUE TITLE
alternator: remove the dependency on CQL query processor

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#7520]
Currently, the only implementation of alternator's auth is based on CQL roles and uses internal CQL requests to check for credentials. This queries can also be represented as internal calls to storage proxy, which circumvent the CQL query processor - making alternator depend on one less service. The goal of this task is to remove the dependency on the query processor from alternator and rewrite the auth code to communicate directly with storage proxy.

**Comment by nuivall** [comment]
Wasn't this done in https://github.com/scylladb/scylladb/pull/9538 ? At least the title and description suggests that.

**Comment by nyh** [comment]
It seems you're right... So closing this issue.
