### ISSUE TITLE
scylla_swap_setup fails when swap already exists

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylladb#7522]
Scylla version (or git commit hash): `666.development-0.20201101.6be9f4938`

If scylla_swap_setup is run when the swap already exists the scripts exits with error code 1. We shouldn't fail the script in such case.
If the script is intended to run by a customer separately(not part of scylla_setup), I don't think it is a correct behavior to fail when the swap exists.
@syuu1228 The function swap_exists() should probably check not only if the swap exists but has the recommended size
and fail when we swap is set but has incorrect size.

```
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]: swap already configured, exiting setup
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]: Traceback (most recent call last):
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]:   File "/opt/scylladb/scylla-machine-image/libexec/scylla_image_setup", line 34, in <module>
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]:     run('/opt/scylladb/scripts/scylla_swap_setup --swap-directory /')
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]:   File "/opt/scylladb/scripts/scylla_util.py", line 503, in run
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]:     return subprocess.run(cmd, stdout=stdout, stderr=stderr, shell=shell, check=exception, env=scylla_env).returncode
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]:     raise CalledProcessError(retcode, process.args,
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 scylla_image_setup[743]: subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_swap_setup', '--swap-directory', '/']' returned non-zero exit status 1.
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 systemd[1]: scylla-image-setup.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 systemd[1]: scylla-image-setup.service: Failed with result 'exit-code'.
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 systemd[1]: Failed to start Scylla Cloud Image Setup service.
Nov 01 21:36:57 artifacts-gce-image-jenkins-db-node-aa57409d-0-1 systemd[1]: Dependency failed for Scylla Server.
```

**Comment by amoskong** [comment]
What's the background? scylla-image-setup service was executed twice?

**Comment by bentsi** [comment]
@amoskong  if it is run twice or swap already exists

**Comment by syuu1228** [comment]
> If scylla_swap_setup is run when the swap already exists the scripts exits with error code 1. We shouldn't fail the script in such case.

scylla_swap_setup is intended to create swapfile only when swap is not available on the system, so it shouldn't create swapfile when swap is already there. (maybe we can have an option to force creating a swapfile though, something like --force)

> If the script is intended to run by a customer separately(not part of scylla_setup), I don't think it is a correct behavior to fail when the swap exists.

If scylla_swap_setup exits with 0, the customer script may create swap twice. That's not correct behavior, so it should exits with non-zero to avoid such mistake.

I'm not sure why scylla_image_setup script causing error at scylla_swap_setup on your log attached this PR, since scylla_image_setup is only execute once, not try to create swap twice.
If it because swap is enabled by default on some cloud, we should fix scylla_image_setup instead of scylla_swap_setup.
We can avoid such error by adding swap_exists(), just like we do in scylla_setup:
```
if swap_exists():
    run('/opt/scylladb/scripts/scylla_swap_setup --swap-directory /')
```

**Comment by syuu1228** [comment]
This issue is not exists anymore, since we moved swap allocation on machine-image building time on 069318bb48963aa5bede707579e499a8bd1288c4.
Closing.
