### ISSUE TITLE
nonroot offline install: can't filter scylla-server log by `journalctl -u scylla-server -xe`

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylladb#7602]
*Installation details*
Scylla version (or git commit hash): scylla-unified-package-4.4.dev.0.20201110.78c598e08e.tar.gz
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS8 instance on GCE
GCE Machine type:  e2-medium (2 vCPUs, 4 GB memory)

### Description

After nonroot offline installation, try to start scylla-server.
Now for issue  #7578 , we can only check the scylla-server log by `journalctl -xe`. `journalctl -xe --user` doesn't work.

#### Problem

I want to only filter scylla-server log by `journalctl -u scylla-server -xe`, but it doesn't work.

```
[scylla-test@amos-offline-install-centos8 ~]$ journalctl -u scylla-server -xe
-- Logs begin at Thu 2020-11-12 08:40:23 UTC, end at Thu 2020-11-12 20:40:38 UTC. --
-- No entries --

[scylla-test@amos-offline-install-centos8 ~]$ sudo journalctl -u scylla-server -xe
-- Logs begin at Thu 2020-11-12 08:40:23 UTC, end at Thu 2020-11-12 20:40:38 UTC. --
-- No entries --

[scylla-test@amos-offline-install-centos8 ~]$ journalctl -xe -u scylla-server --user
-- No entries --
```

/CC @penberg @roydahan @syuu1228

**Comment by syuu1228** [comment]
Isn't it same issue with https://github.com/scylladb/scylla/issues/7578#issuecomment-727861177 ?

**Comment by yaronkaikov** [comment]
@syuu1228 Is this relevant ?

**Comment by syuu1228** [comment]
Offline install on CentOS8 does not support journal log, due to systemd bug.
Since it doe not fix on distribution side, we provide a workaround: https://github.com/scylladb/scylladb/commit/0f786f05fed41be94b09e33aa34a767074a14ec1
So there is a solution, closing.
