### ISSUE TITLE
Scylla-jmx crashes

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#7609]
*Installation details*
Scylla version (or git commit hash): 4.3.rc0-0.20201028.bbef05ae3c with build-id adad9e1dae9eb9dbebab38bd5e7258d5c7360350
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-01cc969208fae7a3a

```
Command: 'nodetool  cfstats '

Exit code: 2

Stdout:

Using /etc/scylla/scylla.yaml as the config file

Stderr:

error: Java heap space
-- StackTrace --
java.lang.OutOfMemoryError: Java heap space
```

full logs here:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 0924e5e2-3404-4dd6-b498-8cbe68f030dd                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20201112_163045 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/0924e5e2-3404-4dd6-b498-8cbe68f030dd/20201112_163045/db-cluster-0924e5e2.zip |
| 20201112_163045 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/0924e5e2-3404-4dd6-b498-8cbe68f030dd/20201112_163045/sct-runner-0924e5e2.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```

**Comment by fgelcer** [comment]
relates to scylladb/scylla-enterprise#1295

**Comment by slivne** [comment]
@fgelcer how many tables do we have in this workload is this the 5000 tables workload ?

**Comment by slivne** [comment]
According to roy this is 5000 tables.

**Comment by slivne** [comment]
We need to check the jmx defaults - maybe we need to increase the setting for jmx memory.

If the default is 256M we need to increase it up to 512M / 1G and see if this works - we have reduced the memory consumption and this should be enough and supported

**Comment by fgelcer** [comment]
> @fgelcer how many tables do we have in this workload is this the 5000 tables workload ?

i was opening the logs to confirm (as i didn't remember) and it is indeed the 5000 tables test

**Comment by fgelcer** [comment]
@slivne just hit this again with the 5000 tables test - i'm adding a workaround to increase the `scylla-jmx` from 256M to 1024M (as it is a big instance (i3.8xlarge) and will report results once get one.

**Comment by fgelcer** [comment]
@slivne , after increasing the Java heap memory (thank you to @gnumoreno for the trick here) this crash hasn't happen again for 5000 tables test.

**Comment by eliransin** [comment]
@slivne are we considering this a fix or do you think we should try and look for the root cause (the cause for memory bloat on jmx)

**Comment by elcallio** [comment]
Fwiw, we've already done a bunch of tweaks to reduce the jmx bloat, virtualizing jmx objects etc. The proper fix is to eventually get rid of the jmx and instead base node tool on rest calls.

**Comment by mykaul** [comment]
We got rid of JMX!
