### ISSUE TITLE
float_precision option missing in cqlsh

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylladb#7651]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):  4.2.0-0.20201025.94597e38e2
and  2020.1.3
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by tarzanek** [comment]
float_precision option in cqlsh is missing
(e.g. https://issues.apache.org/jira/browse/CASSANDRA-5274 )

we should backport it

**Comment by tarzanek** [comment]
reproduction steps:
```
CREATE KEYSPACE bla WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;
CREATE TABLE bla.bcmapp (
    tablename text,
    tablepk text,
    tsversion double,
    maintabledata blob,
    tablenamecopy text,
    PRIMARY KEY ((tablename, tablepk), tsversion)
) WITH CLUSTERING ORDER BY (tsversion DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'Table comments altered final check'
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '32', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 2592000
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.1
    AND speculative_retry = '99.0PERCENTILE';
```
Insert Query :
```
insert into bla.bcmapp(tablename,tablepk,tsversion,maintabledata,tablenamecopy) VALUES ('TABLE_USER_LOGIN_NAME','HEENA',15678908765,null,'TABLE_USER_LOGIN_NAME');
insert into bcmapp(tablename,tablepk,tsversion,maintabledata,tablenamecopy) VALUES ('TABLE_USER_LOGIN_NAME','BLA',15278908765,null,'TABLE_USER_LOGIN_NAME');
```
Local rc config:
```
[root@localhost guy]# cat .cassandra/cqlshrc 
[ui]
; increase floating point precision to avoid scientific notation. 
float_precision = 30
```
Reproduction query:
```
[root@localhost guy]# cqlsh -e "SELECT * FROM bla.bcmapp;"
 tablename             | tablepk | tsversion  | maintabledata | tablenamecopy
-----------------------+---------+------------+---------------+-----------------------
 TABLE_USER_LOGIN_NAME |   HEENA | 1.5679e+10 |          null | TABLE_USER_LOGIN_NAME
 TABLE_USER_LOGIN_NAME |     BLA | 1.5279e+10 |          null | TABLE_USER_LOGIN_NAME
(2 rows)
```

**Comment by tarzanek** [comment]
The goal is not to see the "e+10" and rather full number in output

**Comment by slivne** [comment]
I know you rebased the scylla-tools-java  on 3.11.X did we also rebase the cqlsh / python parts ?

**Comment by tarzanek** [comment]
oh, I should have filed this in scylla-tools-java repo

**Comment by elcallio** [comment]
Is "you" me? All of cassandra 3.11 as it looked at the time was merged into scylla-tools-java. But a lot has happened since then. 
Do you want just a cherry-pick of this change? Or a general update?
Note that cqlsh in cassandra trunk finally supports python 3, which in itself is a reason for at least one more cherrypick, if not a general merge of the full repo.

**Comment by tarzanek** [comment]
hooray for python3 !
and if you get the float precision with it, it'd be even better!
@elcallio FTW!

**Comment by elcallio** [comment]
Am I missing something? It looks like float_precision is supported by our cqlsh?
Also, I don't think we got a firm answer on merging from origin for java-tools?
Should we try doing so? In that case, all? And from which tree? 3.11 (we have a partially modified 3.11 now, including 4.x feature java11 support), or 4.0 (master)?

**Comment by roydahan** [comment]
I belive this issue isn't relevant anymore.
