### ISSUE TITLE
Improve flushing memtables from commitlog sync timer

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#7664]
As described in #7663, commitlog can grow very fast in some cases. One reason for it to grow is that memtables pin segments with references. To recycle commitlog segments memtables should be flushed on disk from time to time. There are two places, that do it -- dirty manager and commitlog flush timer. Both do not work well in LWT case.

The dirty manager fails to flush memtables in timely manner because in LWT case memtables grow too slow and reach the flushing threshold later than commitlog grows enormous.

The commitlog flush timer runs with constant period, which is quite big, between runs commitlog can grow significantly. Another problem with this timer is that it flushes all memtables without any selection, meanwhile to keep the commitlog size in bounds it's often enough to flush some of them.

Said that, there's the need for better commitlog->memtables back-pressure. It should be more selective about which memtables to flush and it shouldn't be a dumb periodic timer. As for the latter -- technique we commonly use is to tie the shares of the process that is clearing the backlog to the size of the backlog. In this case, clearing process is memtable flush. So we could increase its shares as we go closer to the point where we exhaust recycled commitlog segments.

**Comment by elcallio** [comment]
If you are using batch mode, the timer should not do any "flush" at all (flush being write-to-disk). It should only check disk footprint and maybe request memtable flushes. Thus you could probably just increase timer freq. We should maybe change flush_segments to not include CF_IDS from the active segment in callback, but...

**Comment by xemul** [comment]
I think that this task is not about flushing more frequently, but more about doing it more selectively. I.e. flushing not everything, but only some subset that's enough to release the needed amount of segments. Maybe in real life all memtables have references to all segments? And thus it doesn't matter what to flush.

**Comment by elcallio** [comment]
Assuming reasonable even temporal spread of writes, yes, most segments will contain data from all active tables. We already do limit the backpressure flush request to CF:s that are hogging finished segments. It just tends to be everything that is being written to.

**Comment by kostja** [comment]
Sufficiently addressed by the commit log hard limit and changing the backpressure defaults.
