### ISSUE TITLE
Out-of-memory when a partition with a large tombstone prefix is read

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#7689]
(Part of #3672)

When a partition with a large prefix of tombstones is read (with no live data between the tombstones), the tombstones will accumulate in memory until we run out of memory, or the partition ends. This is bad.

**Comment by bhalevy** [comment]
@denesb / @avikivity should this issue be labled as "Backport candidate"?

**Comment by denesb** [comment]
I don't know if we'll ever backport something this complex. There is a lot of risks involved with touching paging code.

**Comment by denesb** [comment]
There has been precedents (for #1865 -- we backported for enterprise) but those were very special.

**Comment by avikivity** [comment]
Absolutely won't be backported.

**Comment by avikivity** [comment]
But, why didn't the bot mark it as a candidate? @benipeled
