### ISSUE TITLE
"Can't find a column family with UUID..." after trying to create table with wrong compaction options

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#7811]
```
cqlsh> create table ks.t (pk int primary key) with compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_unit': 'NOPE'};
SyntaxException: Invalid window unit NOPE for compaction_window_unit
```

Scylla reported in its logs:
```
INFO  2020-12-18 15:20:38,734 [shard 1] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x6020053bae00[cfId=33c517d0-413c-11eb-90ec-000000000000,ksName=ks,cfName=t,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.Int32Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy,compactionStrategyOptions={compaction_window_unit=NOPE, enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=33c53ee0-413c-11eb-90ec-000000000000,droppedColumns={},collections={},indices={}]
INFO  2020-12-18 15:20:38,850 [shard 0] compaction - [Compact system_schema.keyspaces 33d6f220-413c-11eb-87bc-000000000002] Compacting [tmp/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-6-big-Data.db:level=0, tmp/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-3-big-Data.db:level=0, ]
INFO  2020-12-18 15:20:38,882 [shard 1] schema_tables - Creating ks.t id=33c517d0-413c-11eb-90ec-000000000000 version=bef90011-cf86-313c-9c7a-2fb373f1296b
INFO  2020-12-18 15:20:38,890 [shard 0] compaction - [Compact system_schema.keyspaces 33d6f220-413c-11eb-87bc-000000000002] Compacted 2 sstables to [tmp/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-9-big-Data.db:level=0, ]. 10kB to 5kB (~52% of original) in 36ms = 157kB/s. ~256 total partitions merged to 1.
```

was the table created?
```
cqlsh> select * from ks.t;
InvalidRequest: Error from server: code=2200 [Invalid query] message="unconfigured table t"
```
doesn't seem so... let's try to create it again, but with different settings
```
cqlsh> create table ks.t (pk int primary key);
ServerError: Can't find a column family with UUID 33c517d0-413c-11eb-90ec-000000000000
```
oops

interestingly, Scylla reports in its log messages that suggest the table is being created...
```
INFO  2020-12-18 15:23:08,863 [shard 1] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x6020053b7880[cfId=8d411cf0-413c-11eb-90ec-000000000000,ksName=ks,cfName=t,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.Int32Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=8d411cf1-413c-11eb-90ec-000000000000,droppedColumns={},collections={},indices={}]
INFO  2020-12-18 15:23:08,968 [shard 0] compaction - [Compact system_schema.columns 8d512280-413c-11eb-87bc-000000000002] Compacting [tmp/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-60-big-Data.db:level=0, tmp/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-57-big-Data.db:level=0, ]
INFO  2020-12-18 15:23:09,073 [shard 0] compaction - [Compact system_schema.tables 8d612810-413c-11eb-87bc-000000000002] Compacting [tmp/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/md-60-big-Data.db:level=0, tmp/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/md-57-big-Data.db:level=0, ]
INFO  2020-12-18 15:23:09,083 [shard 0] compaction - [Compact system_schema.scylla_tables 8d62aeb0-413c-11eb-87bc-000000000002] Compacting [tmp/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-60-big-Data.db:level=0, tmp/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-57-big-Data.db:level=0, ]
INFO  2020-12-18 15:23:09,106 [shard 0] compaction - [Compact system_schema.columns 8d512280-413c-11eb-87bc-000000000002] Compacted 2 sstables to [tmp/data/system_schema/columns-24101c25a2ae3af787c1b40ee1aca33f/md-63-big-Data.db:level=0, ]. 11kB to 5kB (~51% of original) in 115ms = 50kB/s. ~256 total partitions merged to 1.
INFO  2020-12-18 15:23:09,123 [shard 0] compaction - [Compact system_schema.tables 8d612810-413c-11eb-87bc-000000000002] Compacted 2 sstables to [tmp/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/md-63-big-Data.db:level=0, ]. 14kB to 7kB (~51% of original) in 46ms = 158kB/s. ~256 total partitions merged to 1.
INFO  2020-12-18 15:23:09,126 [shard 0] compaction - [Compact system_schema.keyspaces 8d693e60-413c-11eb-87bc-000000000002] Compacting [tmp/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-66-big-Data.db:level=0, tmp/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-63-big-Data.db:level=0, ]
INFO  2020-12-18 15:23:09,131 [shard 0] compaction - [Compact system_schema.scylla_tables 8d62aeb0-413c-11eb-87bc-000000000002] Compacted 2 sstables to [tmp/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/md-63-big-Data.db:level=0, ]. 11kB to 5kB (~51% of original) in 43ms = 132kB/s. ~256 total partitions merged to 1.
INFO  2020-12-18 15:23:09,146 [shard 0] compaction - [Compact system_schema.keyspaces 8d693e60-413c-11eb-87bc-000000000002] Compacted 2 sstables to [tmp/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/md-69-big-Data.db:level=0, ]. 11kB to 5kB (~51% of original) in 17ms = 333kB/s. ~256 total partitions merged to 1.
```

but there's no log from `schema_tables` which usually appears when a table is created.

Interestingly, after restarting Scylla:
```
cqlsh> create table ks.t (pk int primary key);
AlreadyExists: Table 'ks.t' already exists
cqlsh> drop table ks.t;
cqlsh> create table ks.t (pk int primary key);
cqlsh> 
```

but that was a single node, with many nodes I guess you would have to restart the entire cluster or something?
I don't know what happens with many nodes - needs further investigation.

Tested on recent master.
May be related: https://github.com/scylladb/scylla/issues/5080.

**Comment by raphaelsc** [comment]
i think the problem may be that we're performing validation of compaction options too late.

1) table is created with incorrect compaction options 
2) when setting up table, the compaction options will be passed to strategy which will perform validation
3) strategy perform validation only now and triggers an exception as it finds an incorrect option

so table cannot be queried as exception was triggered during its setup.

so we need to move validation to 1)

**Comment by bhalevy** [comment]
Refs #2336

**Comment by bhalevy** [comment]
not fixed for all strategies yet... only fir twcs

**Comment by raphaelsc** [comment]
> not fixed for all strategies yet... only fir twcs

Even TWCS may be affected. With Felipe's patch we're applying sanity checks on window settings, but other options are still vulnerable to this problem.

**Comment by bhalevy** [comment]
Still happening.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release-with-raft/226/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_resetlocalschema_api_issue_7811_SizeTieredCompactionStrategy_/
```
AssertionError: Got unexpected exception: ('Unable to complete the operation against any hosts', {<Host: 127.0.16.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1206): exceptions::syntax_exception (Invalid long value NOPE for 'min_sstable_size')"">})
assert "Can't find a column family with UUID" in '(\'Unable to complete the operation against any hosts\', {<Host: 127.0.16.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1206): exceptions::syntax_exception (Invalid long value NOPE for \'min_sstable_size\')"">})'
 +  where '(\'Unable to complete the operation against any hosts\', {<Host: 127.0.16.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1206): exceptions::syntax_exception (Invalid long value NOPE for \'min_sstable_size\')"">})' = str(NoHostAvailable('Unable to complete the operation against any hosts', {<Host: 127.0.16.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="Raft instance is stopped, reason: "background error, std::_Nested_exception<raft::state_machine_error> (State machine error at raft/server.cc:1206): exceptions::syntax_exception (Invalid long value NOPE for 'min_sstable_size')"">}))
```

**Comment by DoronArazii** [comment]
@bhalevy from a quick look it's seems like under your team's domain

**Comment by Deexie** [comment]
> i think the problem may be that we're performing validation of compaction options too late.
> 
>     1. table is created with incorrect compaction options
> 
>     2. when setting up table, the compaction options will be passed to strategy which will perform validation
> 
>     3. strategy perform validation only now and triggers an exception as it finds an incorrect option
> 
> 
> so table cannot be queried as exception was triggered during its setup.
> 
> so we need to move validation to 1)

A fix for that is here: https://github.com/scylladb/scylladb/pull/15091

I can't recreate the original issue, `Can't find a column family with UUID 33c517d0-413c-11eb-90ec-000000000000` isn't thrown and schema_tables logs do appear.

**Comment by fruch** [comment]
@bhalevy 

Can you reopen this ? I think it was close cause some fork dtest operation by mistake

**Comment by fgelcer** [comment]
> @bhalevy
> 
> Can you reopen this ? I think it was close cause some fork dtest operation by mistake

**Comment by bhalevy** [comment]
> @bhalevy
> 
> Can you reopen this ? I think it was close cause some fork dtest operation by mistake

This is quite funny, actually, because this commit mentioned that yet another PR fixed this issue inadvertently, but by mentioning that, it also "fixed" this issue inadvertently.

**Comment by bhalevy** [comment]
With all that said, @Deexie, should this issue be closed now with https://github.com/scylladb/scylladb/pull/15091?

**Comment by Deexie** [comment]
> With all that said, @Deexie, should this issue be closed now with #15091?

It doesn't reproduce now, but I couldn't reproduce the issue before either. I can't really tell.

> I can't recreate the original issue, `Can't find a column family with UUID 33c517d0-413c-11eb-90ec-000000000000` isn't thrown and schema_tables logs do appear.

**Comment by bhalevy** [comment]
Let's close the issue then based on our best knowledge.
It can always be reopwned if reproduced

**Comment by roydahan** [comment]
This test: test_resetlocalschema_api_issue_7811 is now failing on branch-2023.1.
I see that the issue is fixed, but I don't think that the bacport reached branch-2023.1 (I couldn't find this commit there).
On the test itself it says:

`# TODO: This test should be removed when issue #7811 will be fixed`

The failure is the exact failure as the original issue of 7811, but I don't see any "required" so I don't understand how it used to pass.

@juliayakovlev / @bhalevy ?

**Comment by bhalevy** [comment]
@roydahan the test is flaky, it doesn't fail consistently AFAIK.
The fix on the scylla side (https://github.com/scylladb/scylladb/commit/91a8100b3f51acd76277c123369b422e98b232d8) is tracked by https://github.com/scylladb/scylladb/issues/14710
and it wasn't backported

**Comment by roydahan** [comment]
I don't know why you claim it's flakey, at least in branch 2023.1 it passed 25/25 times and failed only in the last 2 runs.

**Comment by mykaul** [comment]
> I don't know why you claim it's flakey, at least in branch 2023.1 it passed 25/25 times and failed only in the last 2 runs.

We need to run it 1000 times, incl. in ARM/debug and such and then we can declare it's not flaky, btw.

**Comment by fruch** [comment]
> > I don't know why you claim it's flakey, at least in branch 2023.1 it passed 25/25 times and failed only in the last 2 runs.
> 
> We need to run it 1000 times, incl. in ARM/debug and such and then we can declare it's not flaky, btw.

Just a note, on this branch we don't support ARM dtest runs 
We do support it on master, but it's not yet being used

**Comment by denesb** [comment]
Nothing to backport, removing label.

**Comment by bhalevy** [comment]
> Nothing to backport, removing label.

@denesb I'm not sure why the issue was closed with the dtest PR (which is just a workaround on the test side).
https://github.com/scylladb/scylladb/commit/91a8100b3f51acd76277c123369b422e98b232d8 / https://github.com/scylladb/scylladb/issues/14710 should be fixing this issue.
and it requires backport to 5.2 (can be done as part of this issue or #14710, doesn't matter).

**Comment by ptrsmrn** [comment]
@bhalevy I see this commit https://github.com/scylladb/scylladb/commit/91a8100b3f51acd76277c123369b422e98b232d8 is in 2023.1 enterprise branch:
```
[piotrs@fedora scylla-enterprise]$ git branch
* branch-2023.1
[piotrs@fedora scylla-enterprise]$ git log --grep="Validate compa"
commit d96440e8b67c8ba49a491685fb32680ed34b0530
Merge: 7e9107cc97 ea41a811d6
Author: Botond Dénes <bdenes@scylladb.com>
Date:   Fri Jan 12 10:56:54 2024 +0200

    Merge '[Backport 5.2] Validate compaction strategy options in prepare' from Aleksandra Martyniuk
```
but the latest 2023.1.4 Jenkins job failed on this dtest 7 times consecutively - https://jenkins.scylladb.com/job/enterprise-2023.1/job/dtest-release/33/testReport/. In the enterprise repo I don't see anything related to this issue, maybe except for https://github.com/scylladb/scylla-enterprise/issues/1824. This fail is currently blocking the 2023.1.4 release. IIUC I should open a new issue in the enterprise github for someone to fix it.

**Comment by ptrsmrn** [comment]
@bhalevy I checked out scylla-dtest on branch-2023.1 and the comment says:
```
    # TODO: This test should be removed when issue #7811 will be fixed
    @pytest.mark.parametrize("strategy", ['TimeWindowCompactionStrategy', 'SizeTieredCompactionStrategy'])
    def test_resetlocalschema_api_issue_7811(self, strategy):
```
so I understand we can safely ignore this failure and I can open a dtest PR against branch-2023.1 to remove this test?

**Comment by bhalevy** [comment]
I'm not sure why this comment as added.
There is no need to remove the test, as it's good as a regression test for #7811

The test fails the same way in 5.2:
https://jenkins.scylladb.com/view/scylla-5.2/job/scylla-5.2/job/dtest-release/39/testReport/nodetool_additional_test/TestNodetool/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split004___test_resetlocalschema_api_issue_7811_SizeTieredCompactionStrategy_/

due to missing backport.
See https://github.com/scylladb/scylladb/issues/11643#issuecomment-1867295020

That said, https://github.com/scylladb/scylladb/commit/d96440e8b67c8ba49a491685fb32680ed34b0530 was backported last week and reached branch-5.2 and it should reach 2023.1 eventually.
