### ISSUE TITLE
Yield while building large results in Alternator

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#7926]
In commit 7953f7c65fcc3d41276a6d3602ec50a8ee40f0d0 @psarna added yielding (i.e., preemption points) to the JSON **parsing** code in Alternator, so that a large request doesn't cause large stalls and high latency for other requests.

However, there is also a similar issue for building large **responses** - such as a `GetItem` of a large item or a `Scan` with a relatively large page. Every O(N) algorithm in such responses needs to be able to yield. This includes (probably incomplete list - edit this issue if more are found):

*  The low-level JSON printing code (`rjson::print()` called in `server.cc`).
* Also higher-level code building the JSON object for the reply. In `Scan` or `Query` we have `describe_items()` which iterates over a page of items, converts them to JSON, filters them, etc. - currently without yielding during this loop.
* For `BatchGetItem`, `executor::batch_get_item()` also ends with a loop over all items, which doesn't yield.
* The `executor::describe_single_item()` converts a single item to JSON, and needs to copy the item's entire content. In DynamoDB this is limited to 400 KB but in Scylla even this limit is not enforced and can be even larger (see https://github.com/scylladb/scylladb/issues/11880), so we should consider whether we should - or shouldn't - yield also inside this function. This `describe_single_item()` is used by `GetItem`, by `PutItem` to read the previous content (for read-modify-write operations and ReturnValues), in `BatchGetItem` for each of the items.

Maybe we should split this issue into multiple issues about the different parts that need making yieldable.
 
Since we have coroutines now, writing yielding code has become easier, though some functions that today return an immediate value will need to be changed to return a future.

This issue was inspired by issue #7873 - which reported huge (3.5 second) stalls - but those stalls were probably not caused by anything mentioned above, rather they are caused by #7929 - stalls in scanning a partition with a huge string of row tombstones which aren't specific to Alternator.

**Comment by psarna** [comment]
Some more context: yielding during building JSON strings (`rjson::print`) was also considered for 7953f7c, but it was harder to do because yieldable JSON routines rely on running inside a Seastar thread context (`seastar::async`). And that's because yielding had to be injected into rapidjson code in a slightly hacky way. For parsing, in order to avoid spawning many Seastar threads, a single worker thread is used to parse the JSON if the input is big enough. Same **could** be done for printing, but it's much less convenient, since it's used both to return strings to the user and to print debug information - so some functions would have to be futurized just to be able to print something into the debug log.

As for breaking higher-level loops - good idea, we actually should have done it from the start :)

**Comment by slivne** [comment]
@nyh / @eliransin lets add this to the plan ...

**Comment by nyh** [comment]
`rjson::print` not only doesn't yield, it also uses internally a `rapidjson::internal::Stack` (see https://rapidjson.org/stack_8h_source.html) which keeps the output as one contiguous string. Allocating a big contiguous buffer can fail, and when it does, rapidjson crashes on null pointer dereference (this is issue #8515).
So it will be much better to generate the JSON string in pieces instead of trying to put it in one contiguous string.

**Comment by nuivall** [comment]
I split the issue, what's left here:
- descibe_items() (my comment about it here: https://github.com/scylladb/scylladb/pull/12351#issuecomment-1357388012)
- describe_single_item()

**Comment by mykaul** [comment]
> I split the issue, what's left here:
> 
> * descibe_items() (my comment about it here: [Yield while building large results in Alternator - rjson::print, executor::batch_get_item #12351 (comment)](https://github.com/scylladb/scylladb/pull/12351#issuecomment-1357388012))
> * describe_single_item()

@nuivall - is there any issue/PR for the 2nd item?

**Comment by nuivall** [comment]
No, it was not clear to me if it's worth doing (no evidence it would help) compared to merged stuff which definitely helped.

**Comment by mykaul** [comment]
Closing as completed then, for the time being.
