### ISSUE TITLE
Block parallel bootstraps

### ISSUE THREAD

**Issue by yakirgb** [scylladb/scylladb#7940]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Opened based on [Slack thread](https://scylladb-users.slack.com/archives/C2NLNBXLN/p1610895283055800?thread_ts=1610880220.054200&cid=C2NLNBXLN) with @fruch 

*Installation details*
Scylla version: 4.1.7-0.20200918.2251a1c577
Cluster size: 5TB
OS: CentOS Linux release 7.4.1708 (Core) 

Platform: physical
Hardware: sockets=2 cores=40 hyperthreading=disabled memory=187GB
Disks: 1 NVME, 3 TB

On Cassandra, bootstrap multiple nodes it's not possible and second node will fail with error, it will work only with `-Dcassandra.consistent.rangemovement=false` but[ it's not safe.](https://issues.apache.org/jira/browse/CASSANDRA-7069)

I saw that Scylla not blocking multiple bootstraps, i think that startup for second nodes should fail with error or give option to join two or more nodes with specific option in `scylla.yaml`

Example for my test, just started multiple nodes at same time:
```
[root@r3 ~]# nodetool status
Datacenter: my_data_center
==========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  1.2.3.11  ?          256          ?       e42c1d32-3b0d-4a72-86ca-f77510b71af3  my_rack
UJ  1.2.3.14  ?          256          ?       daa4c67e-cb94-4eb4-b451-83c33346f808  my_rack
UJ  1.2.3.15  ?          256          ?       c626dc38-75b0-43c0-9ea8-0c0ff803fa60  my_rack
UJ  1.2.3.13  ?          256          ?       33d65613-72b8-4b2f-b72f-4645c648d8c7  my_rack
UJ  1.2.3.18  ?          256          ?       83c83bc9-bdb3-4b43-ba86-ac7c5b90b032  my_rack
UJ  1.2.3.19  ?          256          ?       0f3e0842-b1a0-4694-ba0a-0db0a2769b3a  my_rack
UJ  1.2.3.16  ?          256          ?       e30bdded-eebb-4292-ad29-63288aa89c9f  my_rack
UJ  1.2.3.17  ?          256          ?       a301910f-85e5-4c88-b74d-349e15bf4c90  my_rack
UJ  1.2.3.20  ?          256          ?       d37353cb-f90c-44bd-a7b7-f425b1eeee67  my_rack
UJ  1.2.3.21  0 bytes    256          ?       2b1fe144-a417-4d8b-97e1-ca7dc1123de4  my_rack
```

Thank you, Yakir Gibraltar.

**Comment by slivne** [comment]
strange we do have dtests that verify this 

I think we do have a code check for this - not sure why its not working, 

In master the requirement for this to work is even harder because of cdc

**Comment by asias** [comment]
When a node bootstraps, it will check if other node is in JOINING status in gossip, if so it rejects to bootstrap. But if we start multiple nodes at the same in parallel, it is possible that a node does not see other nodes in JOINING status when it does the check.  Transitional topology change would help but we do not have it yet.

**Comment by yakirgb** [comment]
Right, in my case the hosts started at same time (diff of few seconds).

**Comment by asias** [comment]
FYI, https://github.com/scylladb/scylla/pull/8481 will make it much safer to block parallel bootstrap.

**Comment by slivne** [comment]
@asias can we close this

**Comment by kbr-scylla** [comment]
Solved by Raft-based topology, although not by blocking the bootstraps, but sequencing them instead.
