### ISSUE TITLE
fromJson() fails to set a map<ascii, int>

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#7949]
The `fromJson()` function can take a map JSON and use it to set a map column. For example, if we have a `map<text, int>` column `m`, the following test works well in coverting the JSON `{"a": 1, "b": 2}` to a value for this column:
```python
stmt = cql.prepare(f"INSERT INTO {table} (p, m) VALUES (?, fromJson(?))")
cql.execute(stmt, [p, '{"a": 1, "b": 2}'])
assert list(cql.execute(f"SELECT p, m from {table} where p = {p}")) == [(p, {'a': 1, 'b': 2})]
```

However, we have a bug if the column type is a `map<ascii, int>` - note the **ascii** instead of **text**. Although the strings "a" and "b" above are perfectly legal ASCII, Scylla fails the statement execution, with the error:
```
E   cassandra.FunctionFailure: Error from server: code=1400 [User Defined Function failure] message="execution of fromJson failed: Failed parsing fromJson parameter: Parsing JSON failed: Invalid value."
```

The same thing works correctly in Cassandra, and is in fact checked by the Cassandra `test cassandra_tests/validation/entities/json_test.py`::`testFromJsonFct` - which fails on Scylla on this issue. I also created separate tests for this issue (based on the example code above) in `test_json.py`::`test_fromjson_map_ascii_unprepared` and `test_fromjson_map_ascii_prepared`.

The "Parsing JSON failed" error is a red herring: This is a perfectly valid JSON, and moreover, exactly the same statement works if the type of the column is `map<text,int>` instead of `map<ascii,int>` - and it parses exactly the same JSON without any complains. I'm guessing that the ASCII validation is incorrectly applied to the correctly-parsed JSON, and when this validation (wrongly) fails, we produce a misleading error message. 

As part of fixing this issue we should also improve this error message - which may (?) be visible in other cases as well and mislead us again. 
When we discover the cause for this bug, we should consider whether it is specific to ascii (why?) and map - or maybe a similar bug applies to other key types? To value types? To other collection types?

**Comment by denesb** [comment]
Backported to 5.2.
