### ISSUE TITLE
toJson() is missing a timezone on timestamp

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#7997]
When running the `toJson()` function on a timestamp column, the result in Cassandra looks like `"2014-01-01 00:00:00.000Z"` while in Scylla it is `"2014-01-01T00:00:00"`. Scylla's output has two problems:

1. The "T" instead of space is indeed one of the allowed _input_ formats for timestamp (see https://cassandra.apache.org/doc/latest/cql/types.html#timestamps) but it was not the format chosen by Cassandra for `toJson()`'s _output_.

2. When a timezone specification is missing, the aforementioned Cassandra documentation states that "_the date will be interpreted as being in the time zone under which the coordinating Cassandra node is configured_", and that is not useful so "_it is recommended that the time zone always be specified for timestamps when feasible._". Cassandra's `toJson()` was missing the timezone in the past - see https://issues.apache.org/jira/browse/CASSANDRA-11137 - but it was fixed in Cassandra commit 88f22b9692c6fdddf837556f13140d949afe0d28 from 2016 - which landed in Cassandra 2.2.7, 3.0.6, 3.6 and of course 4.0. 

This issue is reproduced by `cassandra_tests/validation/entities/json_test.py`::`testToJsonFct`, a translated Cassandra test which among many other things tests `toJson()` of a timestamp column.

**Comment by fruch** [comment]
in cast case it's a bit different, since the Z of the timezone is missing only when milisec is 0.
for example:

`2017-12-27T11:57:42.500+0000` ->  2017-12-27T11:57:42.500Z
while 
`2017-12-27T11:57:42.000+0000` ->  2017-12-27T11:57:42

**Comment by fruch** [comment]
> in cast case it's a bit different, since the Z of the timezone is missing only when milisec is 0. for example:
> 
> `2017-12-27T11:57:42.500+0000` -> 2017-12-27T11:57:42.500Z while `2017-12-27T11:57:42.000+0000` -> 2017-12-27T11:57:42

I think that might be acceptable, even if it slightly differs from cassandra

**Comment by nyh** [comment]
Opened #14518 for the CAST issue. But it's a separate issue - let's reserve **this** issue to discuss the originally-reported toJson() timezone problem.

**Comment by denesb** [comment]
This is a minor compatibility improvement in CQL, which can even break clients, not backporting.
