### ISSUE TITLE
Spurious dtest failures: Exception when communicating with <self>, to read from system_auth.roles: seastar::named_semaphore_timed_out

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#7999]
Quite a few regressions seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/730/testReport/
Scylla version b32ece6975425f566be78419c027fbb073be62b0

I suspect this was caused by 32cdcc0c8bf90ee915d43097c4b85d59b43dcff9 (`Merge "sstables: consolidate reader factory methods" from Botond`)

For example:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/730/testReport/replace_address_test/TestReplaceAddress_rbo_disabled/replace_stopped_node_test/
```
Unexpected errors found: [('node3', ['ERROR 2021-01-29 11:24:16,929 [shard 0] storage_proxy - Exception when communicating with 127.0.42.3, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-29 11:24:16,930 [shard 0] storage_proxy - Exception when communicating with 127.0.42.3, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/730/testReport/replace_address_test/TestReplaceAddress_rbo_disabled/replace_stopped_node_with_schema_rf_1_test/
```
Unexpected errors found: [('node2', ['ERROR 2021-01-29 11:24:16,810 [shard 0] storage_proxy - Exception when communicating with 127.0.22.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-29 11:24:16,807 [shard 0] storage_proxy - Exception when communicating with 127.0.22.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-29 11:24:16,808 [shard 0] storage_proxy - Exception when communicating with 127.0.22.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-29 11:24:16,811 [shard 0] storage_proxy - Exception when communicating with 127.0.22.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-29 11:24:16,806 [shard 0] storage_proxy - Exception when communicating with 127.0.22.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-29 11:24:16,809 [shard 0] storage_proxy - Exception when communicating with 127.0.22.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/731/testReport/counter_tests/TestCountersOnMultipleNodes/counter_consistency_node_add_test/
```
Unexpected errors found: [('node4', ['ERROR 2021-01-30 08:24:49,517 [shard 0] storage_proxy - Exception when communicating with 127.0.65.4, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 08:24:49,520 [shard 0] storage_proxy - Exception when communicating with 127.0.65.4, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 08:24:49,521 [shard 0] storage_proxy - Exception when communicating with 127.0.65.4, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 08:24:49,518 [shard 0] storage_proxy - Exception when communicating with 127.0.65.4, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 08:24:49,519 [shard 0] storage_proxy - Exception when communicating with 127.0.65.4, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 08:24:49,516 [shard 0] storage_proxy - Exception when communicating with 127.0.65.4, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 08:24:49,515 [shard 0] storage_proxy - Exception when communicating with 127.0.65.4, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/731/testReport/cql_tracing_addition_test/TestTracingReadAccess/test_tracing_info_for_sstables_on_each_node_from_replica_with_cache_enabled/
```
Unexpected errors found: [('node2', ['ERROR 2021-01-30 08:58:14,031 [shard 0] storage_proxy - Exception when communicating with 127.0.47.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 08:58:14,032 [shard 0] storage_proxy - Exception when communicating with 127.0.47.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/731/testReport/hintedhandoff_additional_test/TestHintedHandoff/hintedhandoff_counter_test/
```
Unexpected errors found: [('node2', ['ERROR 2021-01-30 09:28:25,321 [shard 0] storage_proxy - Exception when communicating with 127.0.69.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/731/testReport/materialized_views_test/TestMaterializedViews/ttl_test/
```
Unexpected errors found: [('node2', ['ERROR 2021-01-30 11:07:50,213 [shard 0] storage_proxy - Exception when communicating with 127.0.87.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 11:07:50,214 [shard 0] storage_proxy - Exception when communicating with 127.0.87.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)', 'ERROR 2021-01-30 11:07:50,212 [shard 0] storage_proxy - Exception when communicating with 127.0.87.2, to read from system_auth.roles: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)'])]
```

**Comment by bhalevy** [comment]
@denesb we're still seeing a lot of this failure on master.
please look into this issue when you can.

**Comment by denesb** [comment]
I couldn't reproduce a single failure so far. Looking at the job at hand I cannot see any scylla commits in the changes list and I don't know where to find the scylla commit hash used, compared to the previous job.

**Comment by bhalevy** [comment]
@denesb as I wrote when opening the issue, the regression was detected in Scylla version b32ece6
According to https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/729/artifact/00-Build.txt,
the previous run was testing scylla version a1f93e42972df729c899c4e6ef3653f101c806dd

**Comment by bhalevy** [comment]
```
$ git log --oneline a1f93e4..b32ece6
```
b32ece6975 Update tools/java submodule
bf115e7d69 schema_tables: put schema tables on shard 0
32cdcc0c8b Merge "sstables: consolidate reader factory methods" from Botond
1e9ce62ee6 cql_query_test: add unit test covering the non-optimal TWCS sstable read path
55609f2033 Update seastar submodule
b4f875f08e uuid: reduce code dependency on UUID_gen.hh
6024ef5dad sstable_mutation_reader: consolidate constructors
dd26a96e63 tests: don't pass temporary ranges to readers
43ad64db78 sstables: sstable_mutation_reader: remove now unused whole sstable constructor
ec6c540c30 sstables: stats: remove now unused sstable_partition_reads counter
5f18e9eb37 sstable: remove read_.*row.*_flat() methods
c3b4e990a2 tree-wide: use sstables::make_reader() instead of the read_.*row.*_flat() methods
080bc2ffec sstables: pass partition_range to create_single_key_sstable_reader()
a5a8037f6e sstables: sstable: add make_reader()

**Comment by DoronArazii** [comment]
@bhalevy should we keep tracking this?

**Comment by DoronArazii** [comment]
> @bhalevy should we keep tracking this?

@denesb any suggestion will be helpful

**Comment by mykaul** [comment]
ping @denesb

**Comment by denesb** [comment]
Don't think there is any point in keeping this open. There were major changes to the semaphore since this issue was opened. Let's close and open new issues for any problems still seen.
