### ISSUE TITLE
DOCS: Revise the Contribute sections

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylladb#8037]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

https://scylla.docs.scylladb.com/master/contribute/ all documents in this directory need to be re-written and updated.

**Comment by nyh** [comment]
To clarify, the goal here is to revise the files in `docs/contribute/*.md` - these end up on our site as https://scylla.docs.scylladb.com/master/contribute/ (which is linked from https://docs.scylladb.com/contribute/).

I see several problems with the current content:
1. The "contribute" directory looks like a mix of documents for two different target audiences: One is for would-be first-time contributors, and the second is experienced maintainers. I think we should split the two.
2. There is no need to split the information for contributors to multiple files each just a few lines in length. It would be better to have a single file for it. And we already had one: CONTRIBUTING.md in the top-level directory (not in docs). So no need for the contributing/ directory to exist at all, in my opinion.
3. CONTRIBUTING.md has some out of date information. Especially about pull requests being forbidden. We need to fix this.

**Comment by nyh** [comment]
@lauranovich I sent a patch to the mailing list (titled "docs: improve CONTRIBUTING.md"). I'm not sure if after that we should close this issue, or leave it open. I am still not a big fan of the "contribute" directory, but it looks like everything left there is actually for maintainers, not contributors, so maybe it just needs to be renamed? 
So maybe this issue should be closed unless you or anyone else has more specific ideas on what we should improve in CONTRIBUTING.md.

**Comment by lauranovich** [comment]
Hi Nadav, 
Here is the way I see it.
1. We need information for contributing to Scylla. 
2. We need something for Maintainers and this info should be in the "Maintainer's handbook" which I think we are in the process of finalizing. 
Can you please identify the components which need to be for maintainers and put them in a new document named maintainer.md or maintainer.rst ? This way only the contributing to Scylla is in the contributing.md file. 
Does this make sense to you? 
Let me know

**Comment by nyh** [comment]
@lauranovich right now, everything left in the contribute/ - backport.md, maintainer.md, review-checklist.md - is for maintainers, not regular contributors. In my opinion, only maintainer.md should remain: backport.md should just be a small section in maintainer.md (and in fact there is already a similar section), and I never understood the point of `review-checklist.md` and who its target audience is, but @avikivity can comment on that.

If I understand correctly, the "contributor/" directory is a new subdirectory that didn't exist before, and maybe doesn't need to exist as a subdirectory at all.

**Comment by nyh** [comment]
Closing this issue - there is no longer a "contributor" directory. I think the situation is still not great, I'll open a new issue on the current state.
