### ISSUE TITLE
SELECT JSON ignores the "AS" specification

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#8078]
The CQL command `SELECT JSON v AS foo, k AS bar FROM table` should result in JSON output that looks like `{"foo": 0, "bar": 0}` - i.e., the names of the columns should be replaced by the names "foo" and "bar" as specified by the "AS" alias clauses in the command. But unfortunately, Scylla ignores these "AS" aliases, and its output is `{"v": 0, "k": 0}`.

This bug is reproduced by the following tests translated from Cassandra's unit tests:
* `cassandra_tests/validation/entities/json_test.py`::`testSelectJsonSyntax`
* `cassandra_tests/validation/entities/json_test.py`::`testCaseSensitivity`

**Comment by nyh** [comment]
This issue was just reported by an actual user, who used SELECT JSON with `writetime(x) as y`, and saw `writetime(x)` in the output instead of `y` as expected. So we should probably solve it...

**Comment by nyh** [comment]
I have a fix for this already, it's basically two lines of code.

But the two translated Cassandra unit tests that demonstrated this bug unfortunately demonstrate two other bugs as well (#8086 and #8077), so these two tests keep xfailing after this patch as well. I did verify manually that all the assertions related to "AS" which used to fail now pass, but still, these tests don't serve as a good regression test if they continue to xfail - so if they later start to fail even more badly, we won't know.
So I want to add to my patch also a new test that reproduces **only** this bug and not the two other ones, I'll do this tomorrow.

**Comment by avikivity** [comment]
Minor, but can stump newcomers.
