### ISSUE TITLE
Gemini detect difference in query result for GSI between test and oracle nodes

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#8090]
*Installation details*
Scylla version (or git commit hash): `4.4.rc1-0.20210210.5b6c28428 with build-id 6b0809e6195738bc6d0948a86885be2cadd9eac1`
Cluster size: 3 nodes (i3.large)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-01ca3b82f1341c9ac` (aws: eu-north-1)

Gemini command:
`/$HOME/gemini -d --duration 3h --warmup 30m -c 100 -m mixed -f --non-interactive --cql-features normal --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --async-objects-stabilization-attempts 5 --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --oracle-replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '1'}" --test-cluster=10.0.2.235,10.0.1.196,10.0.2.210 --outfile /home/centos/gemini_result_bea3c826-b0f4-4980-a202-82fa953976ef.log --seed 28 --oracle-cluster=10.0.0.234 `
Gemini version: `1.7.4`

Test id: `6241e66c-17f6-4d93-b23b-f34a48b4b236`
Test: `BYO-abykov-staging`
Test name: `gemini_test.GeminiTest.test_load_random_with_nemesis`
Test config file(s):
- [gemini-3h-with-nemesis.yaml] (https://github.com/scylladb/scylla-cluster-tests/blob/0d21beeb95740f69f66ef07af45df7d24a22b9d0/test-cases/gemini/gemini-3h-with-nemesis.yaml)
Gemini seed: 28

**Issue description**

====================================
Gemini create next schema:
```
cqlsh> DESC KEYSPACE ks1 ;

CREATE KEYSPACE ks1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TYPE ks1.udt_2408576938 (
    udt_2408576938_0 ascii,
    udt_2408576938_1 duration,
    udt_2408576938_2 timeuuid,
    udt_2408576938_3 timestamp,
    udt_2408576938_4 ascii,
    udt_2408576938_5 inet,
    udt_2408576938_6 timeuuid
);

CREATE TABLE ks1.table1 (
    pk0 tinyint,
    pk1 smallint,
    pk2 tinyint,
    pk3 int,
    pk4 tinyint,
    ck0 timeuuid,
    ck1 inet,
    col0 inet,
    col1 set<inet>,
    col10 smallint,
    col2 frozen<udt_2408576938>,
    col3 bigint,
    col4 ascii,
    col5 inet,
    col6 list<timestamp>,
    col7 map<timeuuid, text>,
    col8 text,
    col9 ascii,
    PRIMARY KEY ((pk0, pk1, pk2, pk3, pk4), ck0, ck1)
) WITH CLUSTERING ORDER BY (ck0 ASC, ck1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE INDEX table1_col10_idx ON ks1.table1 (col10);

CREATE MATERIALIZED VIEW ks1.table1_col10_idx_index AS
    SELECT col10, idx_token, pk0, pk1, pk2, pk3, pk4, ck0, ck1
    FROM ks1.table1
    WHERE col10 IS NOT NULL
    PRIMARY KEY (col10, idx_token, pk0, pk1, pk2, pk3, pk4, ck0, ck1)
    WITH CLUSTERING ORDER BY (idx_token ASC, pk0 ASC, pk1 ASC, pk2 ASC, pk3 ASC, pk4 ASC, ck0 ASC, ck1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW ks1.table1_mv_0 AS
    SELECT *
    FROM ks1.table1
    WHERE col9 IS NOT null AND pk0 IS NOT null AND pk1 IS NOT null AND pk2 IS NOT null AND pk3 IS NOT null AND pk4 IS NOT null AND ck0 IS NOT null AND ck1 IS NOT null
    PRIMARY KEY ((col9, pk0, pk1, pk2, pk3, pk4), ck0, ck1)
    WITH CLUSTERING ORDER BY (ck0 ASC, ck1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

after warmup period 30min when only write operations were executed gemini start to report next warning  
```
{"L":"INFO","T":"2021-02-16T06:39:17.167Z","N":"generator","M":"starting partition key generation loop"}
{"L":"INFO","T":"2021-02-16T07:09:18.636Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.639Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.646Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.651Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.657Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.670Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.697Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.707Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.729Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.771Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:18.776Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
...
{"L":"INFO","T":"2021-02-16T07:09:24.726Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:24.732Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:24.739Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:24.744Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
{"L":"INFO","T":"2021-02-16T07:09:24.748Z","N":"validation_job","M":"validation failed for possible async operation","trying_again_in":"500ms"}
```
====================================

And then Next query failed:
```
 Query:"SELECT * FROM ks1.table1 WHERE col10=12987 
```

Gemini try to read with index and detect that rows on oracle and test clusters are different: 
[gemini-l0-dadb5935-a4b1-4d5e-b756-383e601f91f9.log](https://github.com/scylladb/scylla/files/5988122/gemini-l0-dadb5935-a4b1-4d5e-b756-383e601f91f9.log)

i compared result of failed query for  each node of test cluster and for oracle node, and data on each node is same and differs from oracle.
to avoid repair on read, 2 nodes of 3 have scylla stopped. Failed query was sent to one live test cluster node and oracle cluster node.

Live monitoring could be found here:
http://13.49.245.228:3000/d/dyfHJyEGk/byo-abykov-staging-scylla-per-server-metrics-nemesis-master?orgId=1&refresh=30s

Restore Monitor Stack command: `$ hydra investigate show-monitor 6241e66c-17f6-4d93-b23b-f34a48b4b236`
Show all stored logs command: `$ hydra investigate show-logs 6241e66c-17f6-4d93-b23b-f34a48b4b236`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_071538/grafana-screenshot-byo-abykov-staging-scylla-per-server-metrics-nemesis-20210216_071930-gemini-with-nemesis-3h-normal-maste-monitor-node-6241e66c-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_071538/grafana-screenshot-byo-abykov-staging-scylla-per-server-metrics-nemesis-20210216_071930-gemini-with-nemesis-3h-normal-maste-monitor-node-6241e66c-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_071538/grafana-screenshot-overview-20210216_071538-gemini-with-nemesis-3h-normal-maste-monitor-node-6241e66c-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_071538/grafana-screenshot-overview-20210216_071538-gemini-with-nemesis-3h-normal-maste-monitor-node-6241e66c-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/db-cluster-6241e66c.zip](https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/db-cluster-6241e66c.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/loader-set-6241e66c.zip](https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/loader-set-6241e66c.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/monitor-set-6241e66c.zip](https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/monitor-set-6241e66c.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/sct-runner-6241e66c.zip](https://cloudius-jenkins-test.s3.amazonaws.com/6241e66c-17f6-4d93-b23b-f34a48b4b236/20210216_072407/sct-runner-6241e66c.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/BYO-abykov-staging/69/)

**Comment by aleksbykov** [comment]
Cluster nodes:
```
| gemini-with-nemesis-3h-normal-maste-db-node-6241e66c-1        | eu-north-1a | 13.51.6.169   |
| gemini-with-nemesis-3h-normal-maste-db-node-6241e66c-2        | eu-north-1a | 13.48.5.101   |
| gemini-with-nemesis-3h-normal-maste-db-node-6241e66c-3        | eu-north-1a | 13.53.100.244 |
| gemini-with-nemesis-3h-normal-maste-oracle-db-node-6241e66c-1 | eu-north-1a | 13.51.64.16   |
```

**Comment by eliransin** [comment]
@psarna the cluster for this GSI problem is still alive. We need to decide if we need it, and if so, use it. If not QA will kill the cluster.

**Comment by psarna** [comment]
It looks like it simply falls into the broad category of issue #3340 . If this run involves network partitions and killing nodes (which I assume from seeing a "chaos monkey nemesis" in gemini config), then until #3340 is solved, these kinds of inconsistencies are bound to happen.

**Comment by eliransin** [comment]
@psarna thanks, I guess that also means that we can kill the cluster right? :slightly_smiling_face:

**Comment by psarna** [comment]
indeed

**Comment by eliransin** [comment]
@aleksbykov we can kill the cluster, we have a good grasp of the problem.
Thanks,

**Comment by kostja** [comment]
GSI are eventually consistent and are based on MVs where we separately track inconsistency bugs.
