### ISSUE TITLE
update compaction history failed: exceptions::mutation_write_timeout_exception (Operation timed out for system.compaction_history - received only 0 responses from 1 CL=ONE.): ignored

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylladb#8263]
*Installation details*
Kernel version: `5.11.3-1.el7.elrepo.x86_64`
Scylla version (or git commit hash): `4.5.dev-0.20210307.2d9feaace with build-id d779669835c747cc193d97d16b2e84c7cf05177a`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0291a3585729c627b` (aws: eu-north-1)

Test: `longevity-cdc-100gb-4h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ca8a02961c8a045df4e2ea49d1cc2fde06d11620/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

**Issue description**

====================================

During CDC job while no nemesis is running we see this message on all nodes many times.
(Similar error message was in #4291)

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor bd425ab1-f195-4af3-98b3-9a4c12415d87`
Show all stored logs command: `$ hydra investigate show-logs bd425ab1-f195-4af3-98b3-9a4c12415d87`

Test id: `bd425ab1-f195-4af3-98b3-9a4c12415d87`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_044649/grafana-screenshot-longevity-cdc-100gb-4h-test-scylla-per-server-metrics-nemesis-20210308_045038-longevity-cdc-100gb-4h-master-monitor-node-bd425ab1-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_044649/grafana-screenshot-longevity-cdc-100gb-4h-test-scylla-per-server-metrics-nemesis-20210308_045038-longevity-cdc-100gb-4h-master-monitor-node-bd425ab1-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_044649/grafana-screenshot-overview-20210308_044649-longevity-cdc-100gb-4h-master-monitor-node-bd425ab1-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_044649/grafana-screenshot-overview-20210308_044649-longevity-cdc-100gb-4h-master-monitor-node-bd425ab1-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/db-cluster-bd425ab1.zip](https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/db-cluster-bd425ab1.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/loader-set-bd425ab1.zip](https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/loader-set-bd425ab1.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/monitor-set-bd425ab1.zip](https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/monitor-set-bd425ab1.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/sct-runner-bd425ab1.zip](https://cloudius-jenkins-test.s3.amazonaws.com/bd425ab1-f195-4af3-98b3-9a4c12415d87/20210308_045529/sct-runner-bd425ab1.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/190/)

**Comment by roydahan** [comment]
@raphaelsc & @bhalevy is this error message has a bad effect anyhow?

**Comment by raphaelsc** [comment]
> @raphaelsc & @bhalevy is this error message has a bad effect anyhow?

this is a symptom. we need to find the root cause which may not have anything to do with compaction.
