### ISSUE TITLE
Optimize cleanup by being more precise about which sstables really need cleanup

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#828]
Currently, we say that a sstable needs cleanup if its token range isn't fully contained in any of the owned token ranges (needs_cleanup() at database.cc). That's not very good because a sstable token range may be spread across multiple owned token ranges. As a result, we could cleanup a sstable that has no mutation to be filtered out. In other words, a waste of time and resources.

To solve this problem, we need to convert C*'s CompactionManager::needsCleanup() and start using it instead to decide whether a sstable needs cleanup.

**Comment by slivne** [comment]
Scylla version (or git commit hash): 1.1

on cassandra
```
ccm create cas-1  --vnodes -n 1 --install-dir=~/scylla-tools-java
ccm start
ccm node1 stress write n=600000 -mode cql3 native -schema compaction\(strategy=LeveledCompactionStrategy\) keyspace=keyspace2 -pop seq=1..100000000000
check the files in the data/keyspace2
ccm node1 nodetool cleanup
check the files in the data/keyspace2
```

how I tested this on scylla
```
ccm create scylla-1 --scylla --vnodes -n 1 --install-dir=~/scylla
ccm start
ccm node1 stress write n=600000 -mode cql3 native -schema compaction\(strategy=LeveledCompactionStrategy\) keyspace=keyspace2 -pop seq=1..100000000000
check the files in the data/keyspace2
ccm node1 nodetool cleanup
check the files 
```
logs
s. ~606464 total partitions merged to 602080.
INFO  2016-06-06 09:11:34,057 [shard 0] compaction - Cleaning [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-35-Data.db:level=1, ]
INFO  2016-06-06 09:11:34,057 [shard 0] compaction - Cleaning [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-36-Data.db:level=1, ]
INFO  2016-06-06 09:11:34,262 [shard 0] compaction - Cleaned 1 sstables to [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-38-Data.db:level=0, ]. 1412306 bytes to 1412306 (~100% of original) in 204ms = 6.60235MB/s. ~5248 total partitions merged to 5026.
INFO  2016-06-06 09:11:41,548 [shard 0] compaction - Cleaned 1 sstables to [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-37-Data.db:level=0, ]. 167772174 bytes to 167772174 (~100% of original) in 7491ms = 21.359MB/s. ~597248 total partitions merged to 597054.
```
```
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ ls
keyspace2-standard1-ka-35-CRC.db       keyspace2-standard1-ka-35-Index.db       keyspace2-standard1-ka-36-CRC.db       keyspace2-standard1-ka-36-Index.db
keyspace2-standard1-ka-35-Data.db      keyspace2-standard1-ka-35-Statistics.db  keyspace2-standard1-ka-36-Data.db      keyspace2-standard1-ka-36-Statistics.db
keyspace2-standard1-ka-35-Digest.sha1  keyspace2-standard1-ka-35-Summary.db     keyspace2-standard1-ka-36-Digest.sha1  keyspace2-standard1-ka-36-Summary.db
keyspace2-standard1-ka-35-Filter.db    keyspace2-standard1-ka-35-TOC.txt        keyspace2-standard1-ka-36-Filter.db    keyspace2-standard1-ka-36-TOC.txt
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ ccm node1 cleanup


shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ ls
keyspace2-standard1-ka-37-CRC.db       keyspace2-standard1-ka-37-Index.db       keyspace2-standard1-ka-38-CRC.db       keyspace2-standard1-ka-38-Index.db
keyspace2-standard1-ka-37-Data.db      keyspace2-standard1-ka-37-Statistics.db  keyspace2-standard1-ka-38-Data.db      keyspace2-standard1-ka-38-Statistics.db
keyspace2-standard1-ka-37-Digest.sha1  keyspace2-standard1-ka-37-Summary.db     keyspace2-standard1-ka-38-Digest.sha1  keyspace2-standard1-ka-38-Summary.db
keyspace2-standard1-ka-37-Filter.db    keyspace2-standard1-ka-37-TOC.txt        keyspace2-standard1-ka-38-Filter.db    keyspace2-standard1-ka-38-TOC.txt
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ 
```

**Comment by raphaelsc** [comment]
Summarizing my discussion with Benny on this topic:

- A SSTable's token range can span multiple vnode ranges
- Currenty algorithm picks a SSTable for cleanup if it's token range is fully contained in any of the node's owned ranges.
- That's suboptimal, which is the reason this issue was created.
- Even with compaction strategies that generate a run, it can still happen a fragment range can span more than one vnode range

There are two possible solutions for this problem:
A) 
    Let sorted_owned_ranges = [0, 1] [3, 5]
    Let sstable_range = [0, 3]
    
    if we split sstable_range to not span more than one range in sorted_owned_ranges, we end up with:
    [0, 1] [2, 2], [3, 3]

    then we can check if all sstable ranges if fully contained in sorted_owned_ranges in O(N)
B)
    Let sorted_owned_ranges = [0, 1] [3, 5]
    Let sstable_range = [0, 3]
    
    subtracts sorted_owned_ranges from full sstable_range, and if the output is not empty, the SSTable needs cleanup

**Comment by bhalevy** [comment]
It might be worth preparing more detailed ranges when writing the sstable so we have an array of token ranges, each contained in a single owned range, determined at the time of writing the sstable.

**Comment by raphaelsc** [comment]
> It might be worth preparing more detailed ranges when writing the sstable so we have an array of token ranges, each contained in a single owned range, determined at the time of writing the sstable.

That's similar to what we do for sstable resharding. we split sstable range into a range list, with each one spanning a single shard, and store the info in Scylla.DB. On restart, we calculate the set of owner shards and then discard the metadata. vnode and shard ranges don't coincide so we can't reuse the existing metadata. For cleanup, we can read the range metadata on demand, for determining if the sstable needs cleanup. I think your idea can work.

**Comment by bhalevy** [comment]
Fixed by tablets (TM)

**Comment by raphaelsc** [comment]
> Fixed by tablets (TM)

if you agree, let's close this since it's invalidated with tablets.

**Comment by bhalevy** [comment]
> > Fixed by tablets (TM)
> 
> if you agree, let's close this since it's invalidated with tablets.

Yes, we can reopen if needed, but there's very little chance we'll do this optimization for vnodes.
