### ISSUE TITLE
Repair - Increment repair

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#83]
Incremental repair is not supported (see
    http://www.datastax.com/dev/blog/more-efficient-repairs)

**Comment by haoyixin** [comment]
+1

**Comment by nyh** [comment]
Check out http://thelastpickle.com/blog/2017/12/14/should-you-use-incremental-repair.html for survey of known problems of incremental repair (some of which have been solved in Cassandra, some not) which we should be aware of.

**Comment by tzach** [comment]
One of the issue @nyh mentioned:
https://issues.apache.org/jira/browse/CASSANDRA-9143

**Comment by nirmaayan** [comment]
+1

**Comment by Surrina-ki** [comment]
Could you confirm if this approach is feasible?

During full repair, repairs are carried out based on token ranges. Let's assume the repair process is halted midway by using ctrl+c. Would it be possible to record the token ranges currently being repaired in a table? Then, during incremental repair, could these token ranges be retrieved from the table, allowing the repair process to resume from the current token range onwards?

**Comment by nyh** [comment]
@Surrina-ki what you are describing is **not** the "incremental repair" that this issue asks for (which still hasn't been implemented in ScyllaDB). What you ask for already exists, sort of, in ScyllaDB:

The regular repair already allows you to split the entire token range into a number of smaller token ranges, and repair each of these ranges separately - giving you good control over the parallelism of the repair and also the ability to retry failed pieces of the repair. You can implement such a tool yourself (it would be sitting outside of Scylla, sending it commands to repair various ranges of tokens) or if you are a Scylla Enterprise or Scylla Cloud customer, you'll have access to the "Scylla Manager" tool which can do this and other things for you.

**Comment by Surrina-ki** [comment]
@nyh Thank you. I also wanted to ask if there are any plans in place to develop incremental repair functionality?

**Comment by denesb** [comment]
We will not implement incremental repair, as C* implemented it.
We will have a feature called incremental repair, but it will be strongly related to tablets and will be enterprise-only. Closing this issue as wontfix.

**Comment by nyh** [comment]
@denesb now that we no longer have "enterprise-only", perhaps we should reopen this issue. 

I see you opened https://github.com/scylladb/scylladb/issues/22472 but I don't understand why it was better than this one. The new issue doesn't even mention Cassandra or the lessons we can learn from their past mistakes.

**Comment by denesb** [comment]
I simply forgot this issue existed. I added a link to this issue to the new one. I don't see a point in close+reopen just to have the older issue open.
