### ISSUE TITLE
Docs: document the config parameter per release

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#8424]
db/config.cc hold all the config parameter, including default value, LiveUpdate etc
It would be easier to user to access this data in docs, and not via the code and grep commands.
This is similar to #6708 but as a static, part of the release page, not dynamic.

**Comment by tzach** [comment]
An implementation can be part of the Make process, extracting the parameters from the cc file and pushing it into a md file under the doc/ dir

Another alternative is to define the config as YAML/JSON/EDN to start with, and extract the data from it to cc and md.

**Comment by tzach** [comment]
As markdown the output can look something like:


name | value_status | default | liveness | description
-- | -- | -- | -- | --
background_writer_scheduling_quota | Unused | 1 | FALSE | max cpu usage ratio (between 0 and 1) for compaction process. Not intended for setting in normal operations. Setting it to 1 or higher will disable it, recommended operational setting is 0.5.
auto_adjust_flush_quota | Unused | FALSE | FALSE | true: auto-adjust memtable shares for flush processes)
memtable_flush_static_shares" | Used | 0 | FALSE | If set to higher than 0, ignore the controller's output and set the memtable shares statically. Do not set this unless you know what you are doing and suspect a problem in the controller. This option will
compaction_static_shares | Used | 0 | FALSE | If set to higher than 0, ignore the controller's output and set the compaction shares statically. Do not set this unless you know what you are doing and suspect a problem in the controller. This option will be
compaction_enforce_min_threshold | Used | FALSE | TRUE | If set to true, enforce the min_threshold option for compactions strictly. If false (default), Scylla may decide to compact even if below min_threshold

**Comment by tzach** [comment]
What would be easier: to extract the config parameters from config.cc, or extract them to a yaml file, and generate doc and code from both?
The first can also use for a CLI / API tool.

**Comment by dgarcia360** [comment]
@annastuchlik @tzach If the project maintainers could create a function that prints the following YAML file from ``config.cc``:

 ```
 - name: background_writer_scheduling_quota
   value_status: Unused
   default: 1
   liveness: False
   description: "max cpu usage ratio (between 0 and 1) for compaction process. Not intended for setting in normal operations. Setting it to 1 or higher will disable it, recommended operational setting is 0.5."
- name: auto_adjust_flush_quota
   value_status: Unused
   default: False
   liveness: False
   description: "true: auto-adjust memtable shares for flush processes)."
 - ...
 ```
We could autogenerate a doc [as we did for scylla-manager](https://davidgarcia.dev/posts/autogenerating-documentation-for-a-cli/) by creating a custom template that defines how to transform this YAML file into restructuredText.

Alternatively, I could create a function within the docs folder that reads the function https://github.com/scylladb/scylla/blob/master/db/config.cc#L272 from the file ``config.cc`` and formats it as YAML. However, I'd avoid this option since the custom parser could stop working if the project maintainers update the file ``config.cc`` since it would be too attached to the current implementation.

**Comment by fee-mendes** [comment]
Any update on this? Now that Scylla has virtual tables, thus allowing one to change settings on the fly via `LiveUpdate` I believe the priority of such a doc page should be raised. @annastuchlik @tzach

**Comment by tzach** [comment]
@fee-mendes no update yet. We will need help from the core or release team to extract the config info as mention above.
@yaronkaikov maybe you can take a look?

**Comment by tzach** [comment]
@dgarcia360 an alternative we can explore is parsing the confg.cc file using a C++ Sphinx extension
like
https://leimao.github.io/blog/CPP-Documentation-Using-Sphinx/
