### ISSUE TITLE
test/{alternator,cql-pytest,redis}/run: don't always use SIGKILL to kill Scylla

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#8543]
The `test/*/run` scripts run Scylla to run various Alternator/CQL/Redis tests against it. At the end of the test, we kill Scylla abruptly with "kill -9". The rationale for using SIGKILL was that killing Scylla more gracefully would be a waste of time: Any sort of memtable flushing, finishing lingering compactions, etc., that such graceful shutdown might do would be unnecessary given that a millisecond later we'll delete the temporary directory anyway.

However, on second thought, after the test completes (i.e., the `pytest` run completes), anyway no such time-wasting operations would occur on shutdown: At the end of the test pytest destroys all the fixtures, which means it deletes all the temporary tables created for the test. After that, even in a clean shutdown there would be no memtables to flush, no compaction to finish, etc. So even a clean shutdown at that point should be nearly instantaneous.

On the other hand, if we need to kill Scylla when the test has _not_ completed and tables still exist - e.g., when a user pressed control-C during the test - it is still worthwhile to kill Scylla with "kill -9" and not more gracefully. So the cleanup function (`abort_run_with_temporary_dir()` in cql-pytest, `cleanup()` in alternator) should know in which situation it was called. Also, if we ever kill Scylla with a graceful kill, we should be prepared to verify that it really went down and if not, kill it again with "-9". 

The benefit of the change proposed here is that according to @denesb checking the _coverage_ of tests requires exiting Scylla gracefully, so it could write the coverage data to disk. Note that this "graceful shutdown" is only needed when the tests completed - when the user interrupts the test with control-C, there is no expectation that coverage testing should work.

**Comment by nyh** [comment]
@denesb noted on the mailing list that even for coverage, we don't really Scylla to be shut down gracefully - probably all we need is for it to call the standard C function `exit()` immediately. Would be good if we could elicit an immediate `exit()` (without any shutdown steps) via some signal. If we don't already have such a signal maybe we should.

When doing this, we should remember that the `test/cql-pytest/run.py` function `abort_run_with_temporary_dir()` is used not just to kill Scylla, but also other servers like Cassandra. One thing we can do is to have a "protocol" that will work for all of them (e.g., first kill with signal X, then with signal Y, etc.). But perhaps **a better alternative** is to leave the generic "kill with -9" in place, and only kill Scylla in a special (and gentle) way when the test finished until the end, i.e., in `test/cql-pytest/run` and `test/alternator/run` right before calling `exit()` we could send a special signal (or whatever to pid).

**Comment by nyh** [comment]
The following patch to `test/cql-pytest/run.py` (use by `test/*/run`) kills Scylla with SIGTERM (15) before timing out and killing with SIGKILL:
```patch
index 44134e58cb..209db7d48a 100755
--- a/test/cql-pytest/run.py
+++ b/test/cql-pytest/run.py
@@ -90,6 +90,37 @@ def restart_with_dir(old_pid, run_cmd_generator, dir):
 # pid to the temporary directory - which will also be removed.
 run_with_temporary_dir_pids = set()
 
+# killpg_gentle() calls killpg() on the given pid on with the given signal,
+# giving it up to timeout seconds to exit, and if it doesn't - kills again
+# abruptly with SIGKILL. In any case, the other processes in the process
+# group besides pid itself are killed with SIGKILL at the end.
+def killpg_gentle(pid, signal, timeout):
+    os.killpg(pid, signal)
+    print(f"sent signal {signal}")
+    deadline = time.time() + timeout
+    while time.time() < deadline:
+        # To check if the process died, we need to first get rid of the
+        # zombie (if it exists) with waitpid, and then check if the process
+        # still exists, with kill.
+        try:
+            os.waitpid(pid, os.WNOHANG)
+            os.kill(pid, 0)
        except (ProcessLookupError, ChildProcessError):
+            # The process is dead, we're done. But just in case the process
+            # itself is dead but other processes in its process group survived,
+            # kill them all again with SIGKILL.
+            try:
+                os.killpg(pid, 9)
+            except (ProcessLookupError, ChildProcessError):
+                pass
+            return
+        time.sleep(0.1)
+    # The gentle signal didn't work (or didn't work quickly enough).
+    # Fall back to killing with SIGKILL, that is guaranteed to work.
+    os.killpg(pid, 9)
+    print(f"sent signal 9")
+    os.waitpid(pid, 0) # don't leave an annoying zombie
+
 # abort_run_with_temporary_dir() kills a process started earlier by
 # run_with_temporary_directory, and and removes its temporary directory.
 # Currently, the log file is opened and returned so the caller can show
@@ -98,8 +129,7 @@ run_with_temporary_dir_pids = set()
 # of copying it to stdout.
 def abort_run_with_dir(pid, tmpdir):
     try:
-        os.killpg(pid, 9)
-        os.waitpid(pid, 0) # don't leave an annoying zombie
+        killpg_gentle(pid, 15, 5)
     except ProcessLookupError:
         pass
     # We want to read tmpdir/log to stdout, but if stdout is piped, this can
```

But sadly the performance is underwhelming :-( Whereas Scylla boot takes around 0.3 seconds, waiting for the shutdown adds a whopping 2 seconds to the test, despite the fact that - as I noted above, this already after pytest deleted all the tables and there's nothing left to really flush.

The logs show (I just picked a subset of interesting lines:
```
INFO  2023-07-25 18:09:42,797 [shard 0] init - Signal received; shutting down
INFO  2023-07-25 18:09:42,798 [shard 0] gossip - Announcing shutdown
INFO  2023-07-25 18:09:42,798 [shard 0] storage_service - Node 127.24.148.63 state jump to normal
INFO  2023-07-25 18:09:44,799 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2023-07-25 18:09:44,800 [shard 0] gossip - Gossip is now stopped
INFO  2023-07-25 18:09:44,817 [shard 0] init - Scylla version 5.4.0~dev-0.20230717.4a63037cb770 shutdown complete.
```

So I think gossip is sleeping for seconds on shutdown and we never noticed it. We should fix it (or at least allow the test to optionally disable this shutdown sleep).
CC @asias @kostja

**Comment by nyh** [comment]
I'm happy to report that we already have an option, `--shutdown-announce-in-ms 0`, which can remove the default two-second gossip sleep during shutdown!
Adding this option to `test/cql-pytest/run.py` reduced the shutdown overhead to just 0.02 seconds:
```
INFO  2023-07-25 21:59:07,513 [shard 0] init - Signal received; shutting down
INFO  2023-07-25 21:59:07,532 [shard 0] init - Scylla version 5.4.0~dev-0.20230717.4a63037cb770 shutdown complete.
```

So I'm thinking of even making this the default in `test/*/run`.

**Comment by nyh** [comment]
I'm sending a patch for test/*/run now, but @kostja and @fruch you may want to use this "--shutdown-announce-in-ms 0" in test/topology and dtest as well - if you don't kill Scylla with "kill -9", it will shave off two seconds (for each node) from the end of the test.

**Comment by eliransin** [comment]
I see that there is already a fix will comment on it.
