### ISSUE TITLE
Json object should not store its field name

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#856]
Currently each field in the json object holds its name, this implementation should be replaced so that the serializer would add the names excplicitely.

It would simplify the assignment and constructors

**Comment by nyh** [comment]
@amnonh do you remember what this six-year-old issue was about?

I'm guessing it was about Seastar's `json_elements.hh`, and if so, this issue should be moved to the Seastar repository, so I'm closing it here.
But to be honest, I don't understand what this issue is proposing or why.

**Comment by amnonh** [comment]
It relates to the json objects of the API and the way they are serilized, from what I vaugely remember, it was based on @avikivity comment of a patch.

The way the json from swagger implementation works, the field names (i.e. the strings of the names) is part of the object, there's not real need, it could be added by the serilizer.
