### ISSUE TITLE
Secondary index CREATE INDEX syntax is missing the "values" option

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#8745]
Although secondary index of unfrozen column columns is not yet supported (#2962) we should already support its full syntax to provide useful error messages.  The CQL command:
```
CREATE INDEX idx ON table (values(v))
```
produces a syntax error in Scylla. It shouldn't. In `Cql.g` we have `indexIdent` which already supports K_KEYS, K_ENTRIES and K_FULL - it should also support K_VALUES. 

This issue is reproduced by the following cql-pytest translated from Cassandra:
* `cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnFrozenCollectionOfUDT`

This tests tries `CREATE INDEX idx ON table (values(v))` where v is a _frozen_ set. It should be refused saying that frozen collections can only be indexed in their entirety - not with a syntax error.

Another test tries the `values(v)` on a _non-frozen_ collection or in other strange places:
* `cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnNonFrozenCollectionOfFrozenUDT`
* `cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnNonFrozenUDT`

See https://docs.datastax.com/en/cql-oss/3.x/cql/cql_using/useIndexColl.html for the Cassandra documentation on the "VALUES" index type (which is only valid for map columns).

**Comment by avikivity** [comment]
Not a bug, not backporting.
