### ISSUE TITLE
How can I delete Recycled-Commitlog?

### ISSUE THREAD

**Issue by hieunguyen1809** [scylladb/scylladb#8822]
My cluster is running on version 4.2.1. Until today, recycled commit log files have taken up almost 200GB disk. Please help me explain what is the purpose of Recycled-Commitlog for? How can I delete them?

**Comment by elcallio** [comment]
Recycled commit log files are commit log segments (storage) that have been fully committed to sstable, and are now kept open awaiting re-use by new data. Scylla does this to improve disk writing speed (not creating new files or appending to them helps with disk latency). Depending on the size of the node you are running, 200GB might be perfectly reasonable, but it can also be a sign you should either consider decreasing the commit log size or that there might be other latency issues in the config, causing a slight imbalance here. 
How much disk is used for non-recycled commit log files? How many cores and RAM+disk space total on the node?
What is the load?

**Comment by slivne** [comment]
@hieunguyen1809  any additional information you want to share - if not we will close

**Comment by Felix-zhoux** [comment]
Hi, I have the same doubt.
Will these Recycled-Commitlogs be automatically deleted eventually?

In my test environment, Recycled-Commitlog takes up **3TB** of storage, almost as big as the data directory. The `commitlog_total_space_in_mb ` in the configuration file is the default value `-1`, and the node memory is only **600GB**. This doesn't look normal.

what do you mean by saying ' there might be other latency issues in the config' ? @slivne

**Comment by elcallio** [comment]
@Felix-zhoux "other latency" as in "data cannot reach sstables quick enough, so piles up in commit log". But again, _recycled_ files are currently empty, awaiting reuse. Having 3TB of them sounds like you at one point or another hit a rather high peak load, and data was stuck in the commit log. Now the system is anxiously awaiting a similar stressful time...
But again, as @slivne said, need more details on the installation and workload to really say anything.

**Comment by avikivity** [comment]
@elcallio commitlog should delay acks in order to increase backpressure and not increase commitlog past the limit. We should also increase memtable group shares so the flush completes earlier, if commitlog starts to run out of space.

But aren't recycled segments not dependent on flushing? We could just delete them if we are over the limit.

**Comment by kostja** [comment]
Addressed by the commit log hard limit.
