### ISSUE TITLE
Stress failure: could not achieve consistency during mgmt backup many timeouts due to multiple nodes timing out 

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylladb#8877]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.5.rc2-0.20210610.e820e7f3c5a`
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-tls-50gb-3d-4-5-db-node-889c555a-1 (3.250.139.239 | 10.0.2.243): 14 shards
   longevity-tls-50gb-3d-4-5-db-node-889c555a-3 (34.242.40.10 | 10.0.2.105): 14 shards
   longevity-tls-50gb-3d-4-5-db-node-889c555a-5 (3.250.66.190 | 10.0.3.73): 14 shards
   longevity-tls-50gb-3d-4-5-db-node-889c555a-6 (34.254.205.71 | 10.0.3.11): 14 shards
   longevity-tls-50gb-3d-4-5-db-node-889c555a-7 (54.246.6.113 | 10.0.0.255): 14 shards
   longevity-tls-50gb-3d-4-5-db-node-889c555a-8 (54.154.95.92 | 10.0.1.41): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-tls-50gb-3d-4-5-db-node-889c555a-4 (54.75.112.36 | 10.0.1.222): 14 shards
   longevity-tls-50gb-3d-4-5-db-node-889c555a-2 (176.34.149.86 | 10.0.2.88): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-02f3eac8aa2b1d8b9` (aws: eu-west-1)

Test: `longevity-50gb-3days-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a192e58bf41a53b06cb23c3eb83926943583f13d/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

**Issue description**

====================================

Description:
There are c-s errors while  mgmt backup  is running.
SCT starts ManagementBackup
```
2021-06-14 17:44:59.357: (DisruptionEvent Severity.NORMAL): type=ManagementBackup subtype=start target_node=Node longevity-tls-50gb-3d-4-5-db-node-889c555a-8 [54.154.95.92 | 10.0.1.41] (seed: False) duration=None
```

```
2021-06-15 02:08:25.947	
(CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=14139 node=Node longevity-tls-50gb-3d-4-5-loader-node-889c555a-3 [34.243.98.178 | 10.0.0.114] (seed: False)
java.io.IOException: Operation x10 on key(s) [33324b384d3936373531]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
	
CassandraStressLogEvent, CRITICAL, events, OperationOnKey
2021-06-15 02:08:25.948	(CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=14147 node=Node longevity-tls-50gb-3d-4-5-loader-node-889c555a-3 [34.243.98.178 | 10.0.0.114] (seed: False)
java.io.IOException: Operation x10 on key(s) [4e503834364e35304b30]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
	CassandraStressLogEvent, CRITICAL, events, OperationOnKey
2021-06-15 02:08:25.948	(CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=14157 node=Node longevity-tls-50gb-3d-4-5-loader-node-889c555a-3 [34.243.98.178 | 10.0.0.114] (seed: False)
java.io.IOException: Operation x10 on key(s) [394c3937303934363730]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
	CassandraStressLogEvent, CRITICAL, events, OperationOnKey
2021-06-15 02:08:26.095	(CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=14166 node=Node longevity-tls-50gb-3d-4-5-loader-node-889c555a-3 [34.243.98.178 | 10.0.0.114] (seed: False)
java.io.IOException: Operation x10 on key(s) [333436344e334e323430]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
	CassandraStressLogEvent, CRITICAL, events, OperationOnKey
2021-06-15 02:08:26.220	(CassandraStressLogEvent Severity.CRITICAL): type=OperationOnKey regex=Operation x10 on key\(s\) \[ line_number=14175 node=Node longevity-tls-50gb-3d-4-5-loader-node-889c555a-3 [34.243.98.178 | 10.0.0.114] (seed: False)
java.io.IOException: Operation x10 on key(s) [3231334d33384c313030]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
	CassandraStressLogEvent, CRITICAL, events, OperationOnKey

```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 889c555a-624d-4940-930b-a3fdab008b31`
Show all stored logs command: `$ hydra investigate show-logs 889c555a-624d-4940-930b-a3fdab008b31`

Test id: `889c555a-624d-4940-930b-a3fdab008b31`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210615_023914/grafana-screenshot-longevity-50gb-3days-test-scylla-per-server-metrics-nemesis-20210615_024321-longevity-tls-50gb-3d-4-5-monitor-node-889c555a-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210615_023914/grafana-screenshot-longevity-50gb-3days-test-scylla-per-server-metrics-nemesis-20210615_024321-longevity-tls-50gb-3d-4-5-monitor-node-889c555a-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/db-cluster-889c555a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/db-cluster-889c555a.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/loader-set-889c555a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/loader-set-889c555a.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/monitor-set-889c555a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/monitor-set-889c555a.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/sct-runner-889c555a.zip](https://cloudius-jenkins-test.s3.amazonaws.com/889c555a-624d-4940-930b-a3fdab008b31/20210617_113353/sct-runner-889c555a.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/longevity/job/longevity-50gb-3days-test/2/)-------------------------------------------------------------------------------------------
Test is still running cluster alive, I'll attach logs and regular issue template when test will finish.

Nodes IP:
longevity-tls-50gb-3d-4-5-db-node-889c555a-1 [3.250.139.239 | 10.0.2.243]
longevity-tls-50gb-3d-4-5-db-node-889c555a-2 [176.34.149.86 | 10.0.2.88] 
longevity-tls-50gb-3d-4-5-db-node-889c555a-3 [34.242.40.10 | 10.0.2.105] 
longevity-tls-50gb-3d-4-5-db-node-889c555a-4 [54.75.112.36 | 10.0.1.222]
longevity-tls-50gb-3d-4-5-db-node-889c555a-5 [3.250.66.190 | 10.0.3.73] 
longevity-tls-50gb-3d-4-5-db-node-889c555a-6 [34.254.205.71 | 10.0.3.11]

**Comment by roydahan** [comment]
Please supply more information and change the title.

**Comment by slivne** [comment]
@shoshan ping / @roydahan ping

**Comment by tzach** [comment]
@shoshan please include the Manager version for such issues.
The issue might be specific to a Manager version / Scylla version combniation.

**Comment by slivne** [comment]
Waiting for 4.5.rc5 runs to see if this reproduces

**Comment by slivne** [comment]
4.5.rc5 is beeing promoted please retest

**Comment by slivne** [comment]
Going to run again

**Comment by slivne** [comment]
It seems the same as https://github.com/scylladb/scylla/issues/9053 - need to work on finding the source

**Comment by kostja** [comment]
The hard limit is merged  & tested. Please feel free to re-open if there is anything left to do here.
