### ISSUE TITLE
Add option for minimal allowed RF in keyspaces

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#8891]
We have seen users unintentionally use RF=1 or RF=2 for their database. We would like to have an option for a minimal RF that is allowed.

Cassandra is thinking of  exactly such an option, called **minimum_keyspace_rf** - see the issue https://issues.apache.org/jira/browse/CASSANDRA-14557 and proposed patch https://github.com/sumanth-pasupuleti/cassandra/commit/f9fb9537e2c6a41b3df13c7c4af2d23b0912b18c - but it wasn't yet committed into Cassandra.

**Comment by nyh** [comment]
In duplicate issue #9032, @slivne added that: "Replication Factor = 3 is the most commonly used replication factor.
It assures that LOCAL_QUORUM WRITE / LOCAL_QUORUM READ operations can be done and strong consistency can be achieved even in case of a single replica failure." and that we should "Restrict keyspace creation to at least 3 replicas following scylla best practices https://docs.scylladb.com/scylla-cloud/cloud-setup/scylla-best-practices/".

**Comment by nyh** [comment]
I just noticed that https://issues.apache.org/jira/browse/CASSANDRA-14557 was closed in Cassandra 4.1, commit 
https://github.com/apache/cassandra/commit/5fdadb25f95099b8945d9d9ee11d3e380d3867f4

**Comment by avikivity** [comment]
Not a bug, not backporting.
