### ISSUE TITLE
Idea: add an option for default replication strategy and RF for new keyspaces

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#8892]
Today, when creating a keyspace a replication strategy and replication factor must be explicitly stated - for example:
```
CREATE KEYSPACE ks WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 3 }
```
This syntax is verbose and hard to remember, which too often leads users to blindly copy example they find on the web - and often the examples they find are bad - such as using `SimpleStrategy` (see #8586) or using an ill-advised RF (see #8891, #8619).

If we allow configuring (separately) a default replication class and a default replication factor, it will be harder to mistakenly use a bad one.

Cassandra has an issue https://issues.apache.org/jira/browse/CASSANDRA-14557 about adding a `default_keyspace_rf` configuration option (there is also an uncommitted patch - https://github.com/sumanth-pasupuleti/cassandra/commit/f9fb9537e2c6a41b3df13c7c4af2d23b0912b18c). I'm not aware of an idea to add a default replication _strategy_ in Cassandra.

These defaults can be especially useful for managed deployments like Scylla Cloud, where by virtue of the number of nodes, DCs and racks, there is a recommended replication strategy and factor that the user should most probably use - unless they really know what they are doing. See also #8619.

**Comment by tzach** [comment]
Agree the current syntax ( ` { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 3 }` is bad and confusing.

Not sure about having a default replication across DCs:
Transferring data across DCs can be a *very* expensive operation. This about a 100 TB cluster you need to stream to another region or cloud.
User need to be very careful about running such an operation, and the default might be risky.

**Comment by gcarmin** [comment]
Agree with both - we should have a defaults for replication strategy and in my mind it should be enable by default.
for replication factor we can split this into something like that:
```
default_single_dc_rf=
defaults_multi_dc_rf=
```

**Comment by tzach** [comment]
@gcarmin to clarify: I do *not* think multi DC replication should be the default.
I think a users should be able to add a DC first, and start streaming (if he choose to) later.

**Comment by gcarmin** [comment]
@tzach  agree.
1. single DC cluster - user add a dc stream data and set RF manually - later if he wants he can set the default RF.
2. multi DC cluster - let's assume default RF for all DC set to 3  so all new KS will be RF3 on all DC's.  when adding another DC the customer would need to manually ALTER KEYSPACE and then control the streaming and RF.
3. no default - so each DC gets his own RF manually.

**Comment by avikivity** [comment]
It's not possible to replicate while a datacenter is being brought up. There will not be enough space.

So, if we want default replication, new datacenters should be offline by default, and require an explicit command to be brought online for default replication.

**Comment by nyh** [comment]
I'm not sure I understand you guys (or even if all of you are talking about the same thing :-)). I'm not talking about adding a DC, but about a situation when you already have two DCs (for example), and create a new keyspace. 

Today `WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 3 }` will replicate the _new_ keyspace to both pre-existing DCs (with RF=3 in each). Now it seems @tzach is suggesting that this was a bad idea - that it's never useful - you always want to replicate on just the current DC - and you'll be able to change this (with streaming later). If this is the case, why didn't we do this instead of the "auto expand" thing?

If we wanted, the syntax `'replication_factor': 3` could have meant set the replication factor of **this** DC, instead of all DCs. But it's not what it's doing now.

In any case, I claim that it is both ugly and error-prone, that users need to write all these settings, if we believe that "the correct way" can be configured and then all new keyspaces can use this correct way.

**Comment by mailmahee** [comment]
Usually creating a keyspace is not a frequent operation - even though the syntax is clumsy, I would think the relative benefit of setting these defaults vs the pain of explicitly stating them is not much. 
Of course... except for the case when the user uses simplestrategy in production.

**Comment by tzach** [comment]
@nyh sorry, I misread you.
I was referring to adding a DC, you wrote about adding a Keyspace.
I was thinking about default RF for DCs, you wrote about default RF for Keyspaces.

I have no objection, and I support it, use case.
You did not explicitly copy it, but I understand you suggest that the following syntax, with the new config `default_keyspace_rf` will work:

```
CREATE KEYSPACE foo WITH replication = {'class': 'NetworkTopologyStrategy'}
```

There is still a risk in multi DC use case, where a user can (too?) easily create a multi DC replication by mistake.

**Comment by nyh** [comment]
> Usually creating a keyspace is not a frequent operation - even though the syntax is clumsy, I would think the relative benefit of setting these defaults vs the pain of explicitly stating them is not much.
> Of course... except for the case when the user uses simplestrategy in production.

What I am suggesting is that having a clumsy syntax doesn't just slow down infrequently (which would have been forgivable) - it also means that most people won't remember the syntax and look on Google for examples and then copy-paste them. What we have seen in the past in real users' installations is that based on some example they found on the web they created SimpleStrategy replication instead of the desirable NetworkTopologyStrategy.  In other cases we saw a disconnect between whomever designed the cluster and whomever created a keyspace (which may be the same person but after a time lag): The cluster might have been designed with 3 racks intended with the intent of being used with RF=3, and then someone went and created a keyspace with RF=2. While we have other issues for adding options to **restrict** a user's ability to use undesirable replication strategies and replication factors, it would have been even simpler - and more convenient - if not specifying those things simply gave you the default that _is_ recommended.

**Comment by nyh** [comment]
> ```
> CREATE KEYSPACE foo WITH replication = {'class': 'NetworkTopologyStrategy'}
> ```
> 
> There is still a risk in multi DC use case, where a user can (too?) easily create a multi DC replication by mistake.

But I think this ship has already sailed, when we added the so-called "auto-expand" option. Today you can do
```
CREATE KEYSPACE foo WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3}
```
And whether you understand this or not, the meaning of this will be RF=3 on **every DC** and replication to all DCs.

**Comment by tzach** [comment]
> And whether you understand this or not, the meaning of this will be RF=3 on every DC and replication to all DCs.

True

**Comment by gcarmin** [comment]
> > And whether you understand this or not, the meaning of this will be RF=3 on every DC and replication to all DCs.
> 
> True

and from my point of view - this is the desire default for new keyspaces. 
It is mor "fail-safe" than the other options.

**Comment by avikivity** [comment]
> > > And whether you understand this or not, the meaning of this will be RF=3 on every DC and replication to all DCs.
> > 
> > 
> > True
> 
> and from my point of view - this is the desire default for new keyspaces.
> It is a "fail-safe" options.

It guarantees a failure. As soon as you add once node in a new datacenter, repairs will start sending it data. It could easily overwhelm the node. It would also choke on write, slowing down the entire cluster.

**Comment by nyh** [comment]
@avikivity I don't understand your statement: When you create a keyspace, it is replicated only to the **existing** data centers. If later you add new data centers, data will not be replicated to it until you ALTER the keyspace. The name "auto expand" is misleading - the data does not expand to new DCs.

**Comment by avikivity** [comment]
Then it's not "n every DC and replication to all DCs".

**Comment by nyh** [comment]
> Then it's not "n every DC and replication to all DCs".

It's all **existing** (at the time of keyspace creation) DCs. This is the current behavior of the "replication_factor" option in NetworkToplogyStrategy, and it should never have been called "auto expand" because if there's anything this option doesn't do is to auto-expand when new DCs are added :-) We recently fixed the documentation to use the phrase "auto expand" much less prominently.

**Comment by nyh** [comment]
I just noticed that https://issues.apache.org/jira/browse/CASSANDRA-14557 was done, and reached Cassandra 4.1, commit
apache/cassandra@5fdadb2.
This means that Cassandra now has a "default_rf" configuration. I'm not sure that's the solution we want, but we should at least consider doing this - if not for another reason, for Cassandra compatibility.

**Comment by nyh** [comment]
> I just noticed that https://issues.apache.org/jira/browse/CASSANDRA-14557 was done, and reached Cassandra 4.1, commit [apache/cassandra@5fdadb2](https://github.com/apache/cassandra/commit/5fdadb2). This means that Cassandra now has a "default_rf" configuration. I'm not sure that's the solution we want, but we should at least consider doing this - if not for another reason, for Cassandra compatibility.

Since Cassandra 4.1 and above now have `default_keyspace_rf`, we should support it for Cassandra 4 compatibility - so added the appropriate tag. There is a translated Cassandra unit test that checks this feature - that one can create a keyspace without explicitly giving the replication factor:
* `cassandra_tests/validation/operations/create_test.py`::`testCreateKeyspaceWithSimpleStrategyNoOptions`

We should perhaps split this issue to one about the Cassandra-compatible `default_keyspace_rf` feature and the other about additional ideas of allowing a default replication strategy - not just default RF.

**Comment by ptrsmrn** [comment]
@nyh (reaching out to you, since you've opened the issue)
I am closing this issue (please re-open if you think I shouldn't), because "guardrails" for [replication factor](https://github.com/scylladb/scylladb/commit/eb46f1bd17174833095d363a1f1c9a277a8bd818) and [replication strategy](https://github.com/scylladb/scylladb/commit/8c464b2ddb100b9b873344d9f0647bca5c48825c) have reached OSS master. I understand the issue proposed introducing a default value, and not restricting values to some subset, but:
1. For replication strategy discouraging using SimpleStrategy nearly equals defaulting to NetworkTopologyStrategy, because 2 other strategies, i.e. local and everywhere, are implicit
2. We've never reached any consensus on what specific value range is OK-ish for RF, and only agreed that values lower than 3 should be discouraged (but also are allowing the value of 0, so essentially we discouraged RF=1 & RF=2), which implies that for a default we could suggest RF=3 but RF=5 as well. So to me it seems like the default RF we suggest is not a number, but rather an equation: "please choose anything, but don't go lower than 3". 
So IMHO we're done here.

**Comment by nyh** [comment]
> @nyh (reaching out to you, since you've opened the issue) I am closing this issue (please re-open if you think I shouldn't), 

Yes, I think you made a mistake and this issue shouldn't have been close. But since it's really two separate issues, I'll open two new issues to replace this one and will explain why I think they are still relevant.

**Comment by nyh** [comment]
@ptrsmrn I split this issue into two new issues #16028 and #16029. The first issue is a Cassandra 4.1 compatibility (minor, to be sure, but nevertheless a compatibility issue with Cassandra's configuration parameters), and the second issue is just an idea for an enhancement, which I guess you can say we don't need and we can close it again ;-)
