### ISSUE TITLE
Repair takes more than 6h test reach timeout. 

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylladb#8917]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.5.rc3-0.20210620.706de00ef`
Cluster size: 3 nodes (i3en.3xlarge)
Scylla running with shards number (live nodes):
   gemini-8h-large-num-columns-4-5-db-node-1684666d-1 (54.229.175.18 | 10.0.2.40): 12 shards
   gemini-8h-large-num-columns-4-5-db-node-1684666d-2 (34.245.115.3 | 10.0.2.115): 12 shards
   gemini-8h-large-num-columns-4-5-db-node-1684666d-3 (52.212.146.141 | 10.0.2.37): 12 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0b80e391c39a18403` (aws: eu-west-1)

Gemini command:
`/$HOME/gemini -d --duration 7h --warmup 1h -c 20 -m mixed -f --non-interactive --cql-features normal --async-objects-stabilization-backoff 500ms --replication-strategy "{'class': 'SimpleStrategy', 'replication_factor': '3'}" --max-mutation-retries 5 --max-mutation-retries-backoff 500ms --max-partition-keys 12 --min-partition-keys 8 --max-clustering-keys 20 --min-clustering-keys 12 --max-columns 100 --min-columns 80 --verbose --test-cluster=10.0.2.40,10.0.2.115,10.0.2.37 --outfile /home/centos/gemini_result_bcb20a18-5e3c-41d2-9005-828011f6fb15.log --seed 82 `
Gemini version: `1.7.5`

Test: `gemini-8h-large-num-columns-test`
Test name: `gemini_test.GeminiTest.test_load_random_with_nemesis`
Test config file(s):
- [gemini-8h-large-num-columns.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0d21beeb95740f69f66ef07af45df7d24a22b9d0/test-cases/gemini/gemini-8h-large-num-columns.yaml)

**Issue description**

====================================
Repair takes more than 6h test reach timeout. 
Log from node 2 contains many error notifications "storage_proxy - Failed to apply mutation from" 

```
2021-06-22 18:55:15.608: (NodetoolEvent Severity.NORMAL): type=repair subtype=start node=gemini-8h-large-num-columns-4-5-db-node-1684666d-3
2021-06-22 23:07:35.818: (TestTimeoutEvent Severity.CRITICAL), Test started at 2021-06-22 15:12:12, reached it's timeout (500 minute)
2021-06-22 23:07:35.971: (InfoEvent Severity.NORMAL): message=TEST_END
```

restoring offline monitor command failed, adding email snapshot instead.

![image](https://user-images.githubusercontent.com/99000/123076060-73fe7f80-d421-11eb-93d6-ea012137de3a.png)
 

```

```

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 1684666d-ff9e-418a-926b-cff18b926001`
Show all stored logs command: `$ hydra investigate show-logs 1684666d-ff9e-418a-926b-cff18b926001`

Test id: `1684666d-ff9e-418a-926b-cff18b926001`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_233959/grafana-screenshot-gemini-8h-large-num-columns-test-scylla-per-server-metrics-nemesis-20210622_234414-gemini-8h-large-num-columns-4-5-monitor-node-1684666d-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_233959/grafana-screenshot-gemini-8h-large-num-columns-test-scylla-per-server-metrics-nemesis-20210622_234414-gemini-8h-large-num-columns-4-5-monitor-node-1684666d-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/db-cluster-1684666d.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/db-cluster-1684666d.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/loader-set-1684666d.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/loader-set-1684666d.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/monitor-set-1684666d.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/monitor-set-1684666d.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/sct-runner-1684666d.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1684666d-ff9e-418a-926b-cff18b926001/20210622_234944/sct-runner-1684666d.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/gemini-/job/gemini-8h-large-num-columns-test/3/)

**Comment by mykaul** [comment]
I assume less relevant these days.
