### ISSUE TITLE
Remove ARBT conflict

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylladb#892]
Instead of conflict Scylla rpm with arbt, do the following:

BlackListedPaths = /usr/share/doc/_, */example_
Crashes in executables in these paths will be ignored by ABRT.

**Comment by avikivity** [comment]
I think abrt installs a handler in `/proc/sys/kernel/core-pattern`, overriding systemd's.

As a result abrt ignores the core, but then so does systemd.

**Comment by syuu1228** [comment]
ABRT installs coredump handler (abrt-addon-ccpp) by default. The handler is separated process, main process of ABRT is abrtd.
When a program crashes, /usr/libexec/abrt-hook-ccpp consumes coredump from kernel, pass it to abrtd.
BlackListedPaths seems refered from abrtd, so even I specified BlackListedPaths, abrt-hook-ccpp takes nearly 1min, then abrtd dropped it.
So it may takes very long time even we specified on black list.

And if we specified scylla on black list, abrt just drops it. We will lose all crash information with this.
Actually ABRT able to use systemd-coredump for coredump handler instead of abrt-addon-ccpp, this way it may leave coredump and crash report on systemd-coredump when we specified scylla on BlackListedPaths. (Not yet confirmed, will test it)

**Comment by syuu1228** [comment]
One question about ABRT with systemd-coredump is, ABRT has a service to consume coredump from systemd-coredump (abrt-dump-journal-core), document says it reads coredump from journal, but not sure about External mode. (will need to test it)
And dump to journal may too big, in our case.

**Comment by syuu1228** [comment]
I read ABRT docs, but I really don't find a way to keep coredump but not let handles by ABRT.
I think we have two choices:
- Just drop scylla coredump when user using ABRT. No report on journal, no coredump.
- Keep conflict with ABRT.

**Comment by syuu1228** [comment]
I still think best way to solve #892 and #784 is use scylla_save_coredump by default.
If it is not acceptable, then should use systemd-coredump.
With ABRT and BlackListedPaths= setting, you won't able to know why scylla was crashed. And also not able to report it to us.

**Comment by slivne** [comment]
@avikivity , @dorlaor need your input on @syuu1228 comment

**Comment by syuu1228** [comment]
Ideas?

**Comment by avikivity** [comment]
My preference is systemd-coredump.  It should integrate best with the logs.

How is the conflict between systemd-coredump and abrt-ccpp handled?  Does abrt-ccpp override systemd-coredump?

We should report these issues on abrt upstream.

**Comment by syuu1228** [comment]
There is abrt-ccpp.service, it installs coredump hook unconditionally so systemd-coredump's handler will overwrite by abrt-ccpp.
And I don't find abrt-dump-journal-core in CentOS7.3, so abrt always needs/installs abrt-ccpp hook and disable systemd-coredump.

How about to remove abrt conflict, enables systemd-coredump's hook silently instead?
Or prevent to start scylla-server.service until abrt-ccpp.service enabled. Like iotune settings.

**Comment by syuu1228** [comment]
@avikivity What do you think, Avi?

**Comment by syuu1228** [comment]
@avikivity ping

**Comment by jfilak** [comment]
ABRT will not be in charge of core dumping in Fedora26 by default. Fedora folks have decided to switch to coredumpctl and ABRT will be getting core dump files from coredumpctl.

**Comment by avikivity** [comment]
Instead of conflict, perhaps "Obsoletes". It's less friendly but works.

**Comment by tzach** [comment]
@avikivity @syuu1228 any new ideas of removing this limitation?
Users keeping tripping on it before realizing they need to remove abrt

**Comment by avikivity** [comment]
Instead of a package-level conflict, we can add a systemd unit-level conflict:

```
Conflicts: abrtd.service
```

So starting scylla will stop abrtd. However, we'll have to make sure starting scylla updates the core_pattern sysctl.

**Comment by tzach** [comment]
@avikivity is this still an issue?

**Comment by yaronkaikov** [comment]
@syuu1228 Do we still have such an issue? if not let's close it
