### ISSUE TITLE
Automatically convert --max-io-requests to --io-properties-file during upgrade

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#9016]
The `--max-io-requests` CLI option is deprecated by (https://github.com/scylladb/seastar/commit/a717a7d0a4fe9fd71f9cd003d240bcb9a90e658f) (while the io-properties was declared to be the strongly preferred IO confiuration even earlier by (https://github.com/scylladb/seastar/commit/37a22d9de6b20ee3ecd76cbbec09c343836d7b72)). Some day the `--max-io-requests` will be removed, so the upgrading scripts must be prepared for that and convert configuration respectively.

**Comment by slivne** [comment]
@xemul I expect you will need to give the conversion method :)

**Comment by penberg** [comment]
@xemul We don't do this type of automatic conversions in the upgrade scripts because they're way too easy to get wrong, and break stuff. IMHO, what we should do instead, is start complaining in the logs about use of `--max-io-requests`, wait for a long time, turn it into an error, and then remove the option. /cc @avikivity if he disagrees.

**Comment by xemul** [comment]
@penberg , the warning is there since Apr 2021 :) What if some people ignore this warning until the "long time" passes and the option is removed, is it OK if they fail to restart scylla after upgrade until manual reconfiguration?

@slivne , the conversion method is to run `iotune` and replace `--max-io-requests` with `--io-properties-file`.

**Comment by penberg** [comment]
@xemul I think it is OK, but it's ultimately up to @avikivity and @slivne, I think.

**Comment by avikivity** [comment]
@xemul nobody looks at warnings.

I think it's okay if we give instructions in the release notes on how to change it.
