### ISSUE TITLE
Safe Mode : TWCS tables disallow CQL USING TTL 0

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#9029]
TWCS tables are designed to work well utilizing default_time_to_live
CQL ``` USING TTL 0 ``` allows users to unset TTL 

Restrict users from doing such operations to assure that TWCS is capable of comapcting sstables as its designed

**Comment by nyh** [comment]
Why is `USING TTL 0` more problematic than `USING TTL 7` or `USING TTL 1000000000`?

**Comment by raphaelsc** [comment]
> Why is `USING TTL 0` more problematic than `USING TTL 7` or `USING TTL 1000000000`?

TTL 0 disables expiration. So TWCS will not be able to purge any data. People may deliberately use TTL 0, while being aware that no data will ever be purged. I think we should print a warning at the very least.

**Comment by raphaelsc** [comment]
If you mix expire-able data with non-expire-able data, then TWCS will find itself in a situation that the only a subset of the sstable will be expired. So you'll have to enable tombstone compaction, which will affect badly the write amplification.

**Comment by nyh** [comment]
Isn't TTL= 10 years just as bad as TTL=0?
If you think that "USING TTL 0" is some sort of typical mistake, or something people may copy from some silly example on the web, then I agree. Otherwise, I'm a bit puzzled why we are worried about this specific mistake. But I guess adding a restriction is cheap, so ok.

**Comment by eliransin** [comment]
I would like to join @nyh question but in an even looser form:
Isn't explicitly setting TTL is always a bad practice when using TWCS? If so what is a possible "excuse" for setting TTL in the first
place?

**Comment by raphaelsc** [comment]
> I would like to join @nyh question but in an even looser form:
> Isn't explicitly setting TTL is always a bad practice when using TWCS? If so what is a possible "excuse" for setting TTL in the first
> place?

Unfortunately there are people out there that mix TTL. It's a bad practice indeed. But we can't just disallow it. If you use multiple TTL values which aren't too far apart, TWCS can still do a good job. But if you bring in data that will never expire or that will take much longer to expire than its counterparts, then TWCS is basically screwed.

**Comment by eliransin** [comment]
@raphaelsc is there a way to restrict this on runtime using a defined criterya? 
Meaning:
>  If you use multiple TTL values which aren't too far apart, TWCS can still do a good job
Is there a reasonable condition that we can check on runtime and reject the violating request or alert the user that he does something wrong? It doesn't have to be one criteria but can be something gradual like: soft, medium, restrictive, super restrictive etc.. or even have a free parameter that can be set during runtime to adjust this criteria.

**Comment by eliransin** [comment]
@slivne so IIUC you view is that we should forbid any 'WITH TTL' for tables with TWCS right?

**Comment by slivne** [comment]
Yes and users can override the restriction if they really want to.
