### ISSUE TITLE
Cassandra-stress got ReadTimeoutException during full read of the c-s test table

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#9054]
*Installation details*
Scylla version (or git commit hash): `4.6.dev-0.20210706.775a64b00 with build-id 2b277dccbd78b81b6ad5dd834e9d52c51a8fad05`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-04b5522b1a15e9f47` (eu-north-1)

Test: `longevity-50gb-3days`
Test config file: [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

This test was run to reproduce the issue #9053  .
Same test configuration as in the issue #9053  but this test wan without any disruptions (no nemesis).

During the test full scan was started twice.
First run of full scan started at `13:08:50,950`:

```
< t:2021-07-14 13:08:50,950 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-07-14 13:08:50.949: (FullScanEvent Severity.NORMAL) period_type=not-set event_id=3c120ddc-3973-402e-9853-6cc96bfddcf5: type=start select_from=keyspace1.standard1 on db_node=10.0.1.116
```

and finished at `13:20:08,956`:
```
< t:2021-07-14 13:20:08,956 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-07-14 13:20:08.955: (FullScanEvent Severity.NORMAL) period_type=not-set event_id=d07f3d2e-aab1-4946-9d50-55119a7af04c: type=finish select_from=keyspace1.standard1 on db_node=10.0.1.116 message=finished successfully
```

ran the query:

```
select * from keyspace1.standard1 bypass cache USING TIMEOUT 30s
```

Second full scan run was started at `14:20:09,632` and wasn't finished:
```
< t:2021-07-14 14:20:09,632 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-07-14 14:20:09.624: (FullScanEvent Severity.NORMAL) period_type=not-set event_id=eee376ab-ba2b-4c38-a347-575436c5a6be: type=start select_from=keyspace1.standard1 on db_node=10.0.2.224
```

ran the same query:
```
select * from keyspace1.standard1 bypass cache USING TIMEOUT 30s
```

After 1.5 hours the full scan wasn't finished (first full scan has been finished after 11 minutes) and Scylla reported about exception during apply mutations:
```
< t:2021-07-14 15:56:26,901 f:cluster.py      l:1309 c:sdcm.cluster         p:DEBUG > 2021-07-14T15:56:25+00:00  longevity-tls-50gb-3d-repr-no--db-node-3c705194-2 !WARNING | scylla:  [shard 8] storage_proxy - Failed to apply mutation from 10.0.3.10#8: seastar::semaphore_timed_out (Semaphore timedout)
< t:2021-07-14 15:56:26,901 f:cluster.py      l:1309 c:sdcm.cluster         p:DEBUG > 2021-07-14T15:56:25+00:00  longevity-tls-50gb-3d-repr-no--db-node-3c705194-2 !WARNING | scylla:  [shard 7] storage_proxy - Failed to apply mutation from 10.0.0.87#7: seastar::semaphore_timed_out (Semaphore timedout)
< t:2021-07-14 15:56:26,902 f:cluster.py      l:1309 c:sdcm.cluster         p:DEBUG > 2021-07-14T15:56:25+00:00  longevity-tls-50gb-3d-repr-no--db-node-3c705194-2 !ERR     | scylla:  [shard 8] storage_proxy - exception during mutation write to 10.0.2.224: seastar::semaphore_timed_out (Semaphore timedout)
```

And after 7 min got ReadTimeoutException from cassandra-stress:
```
< t:2021-07-14 22:03:46,099 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [4f4c314f3735304e3430]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-14 22:03:46,215 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [3632304b36314c384b30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-14 22:03:46,217 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [504e37333937504c3330]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-14 22:03:46,229 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [384e4d314c3837343631]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-14 22:03:46,248 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [4c4b4e32394b4b303930]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-14 22:03:46,259 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [35384f50383732303630]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-14 22:03:46,265 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [504f4c364d3539383630]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
```

Search for part of the keys that c-s complained as missing,  found that all "missed" keys exist in the 3 replicas (RF=3).
How I checked it:
1. run select with tracing on every node: 
`CONSISTENCY one;tracing on;select count(*) from keyspace1.standard1 where key = 0x504f4c364d3539383630'`

2. check tracing and found that every key found locally on 3 nodes

![Screenshot from 2021-07-15 14-49-14](https://user-images.githubusercontent.com/34435448/125783332-405cb8c0-b20e-4166-a90b-178badb51f1f.png)
![Screenshot from 2021-07-15 14-49-32](https://user-images.githubusercontent.com/34435448/125783343-7601160a-6ad9-4d1a-a1ce-2a3d444f0a90.png)

Logs on SCT Runnier, IP: `ubuntu@13.53.127.165`

Cluster is alive

Test id: `3c705194-3303-4f27-846e-6439690393b2`

Hydra commands:

Restore Monitor Stack command: $ hydra investigate show-monitor 3c705194-3303-4f27-846e-6439690393b2
Show all stored logs command: $ hydra investigate show-logs 3c705194-3303-4f27-846e-6439690393b2

Logs:

db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/3c705194-3303-4f27-846e-6439690393b2/20210718_001357/db-cluster-3c705194.tar.gz
loader-set - https://cloudius-jenkins-test.s3.amazonaws.com/3c705194-3303-4f27-846e-6439690393b2/20210718_001357/loader-set-3c705194.tar.gz
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/3c705194-3303-4f27-846e-6439690393b2/20210718_001357/monitor-set-3c705194.tar.gz
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/3c705194-3303-4f27-846e-6439690393b2/20210718_001357/sct-runner-3c705194.tar.gz

[Job](https://jenkins.scylladb.com/view/master/job/scylla-master/job/reproducers/job/repr-longevity-50gb-3days-missed-keys/2/console)

**Comment by slivne** [comment]
@juliayakovlev the monitor doesn;t work for me - can you try and fix that.

**Comment by slivne** [comment]
@juliayakovlev / @roydahanis is this on 4.6 or 4.5 ?

Does 4.5 pass this test ?

**Comment by juliayakovlev** [comment]
> @juliayakovlev / @roydahanis is this on 4.6 or 4.5 ?
> 
> Does 4.5 pass this test ?

This is master, 4.6dev

I ran same test on 4.4 and it is passed. Didn't run on 4.5

**Comment by slivne** [comment]
Please run on 4.5 so we'll know if we have a regression

**Comment by juliayakovlev** [comment]
> Please run on 4.5 so we'll know if we have a regression

Ok, will start.

**Comment by slivne** [comment]
@juliayakovlev I still can't connect to monitoring

**Comment by juliayakovlev** [comment]
> @juliayakovlev I still can't connect to monitoring

From some reason the monitor has been removed. Cluster is alive.
Restore Monitor Stack command: 
`hydra investigate show-monitor 3c705194-3303-4f27-846e-6439690393b2`

**Comment by juliayakovlev** [comment]
Similar issue got in the `longevity-multi-keyspaces-60h-test` running on the branch `4.5.rc5`
Cassandra-stress exception got during rebuild (`CorruptThenRebuild` nemesis)

```
2021-07-15 15:41:42.689: (DisruptionEvent Severity.NORMAL): type=CorruptThenRebuild subtype=start target_node=Node longevity-1000-keyspaces-4-5-db-node-3a9de768-4 [13.53.38.98 | 10.0.0.10] (seed: False) duration=None
```

After Scylla restart (stop and start):
```
2021-07-15 16:07:54.000: (DatabaseLogEvent Severity.NORMAL): type=STOP regex=Stopping Scylla Server line_number=910267 node=Node longevity-1000-keyspaces-4-5-db-node-3a9de768-4 [13.53.38.98 | 10.0.0.10] (seed: F
alse)
2021-07-15T16:07:54+00:00  longevity-1000-keyspaces-4-5-db-node-3a9de768-4 !INFO    | systemd[1]: Stopping Scylla Server...
2021-07-15 16:09:31.000: (DatabaseLogEvent Severity.NORMAL): type=BOOT regex=Starting Scylla Server line_number=910944 node=Node longevity-1000-keyspaces-4-5-db-node-3a9de768-4 [13.53.38.98 | 10.0.0.10] (seed: F
alse)
2021-07-15T16:09:31+00:00  longevity-1000-keyspaces-4-5-db-node-3a9de768-4 !INFO    | systemd[1]: Starting Scylla Server...
```

A few sstables were deleted. Rebuild was started at `2021-07-15 16:11:40`:
```
2021-07-15 16:11:40.534: (NodetoolEvent Severity.NORMAL): type=rebuild subtype=start node=longevity-1000-keyspaces-4-5-db-node-3a9de768-4
```

Failed to apply mutation (named_semaphore_timed_out) started at `2021-07-15 18:07:33`
```
< t:2021-07-15 18:07:33+00:00  longevity-1000-keyspaces-4-5-db-node-3a9de768-4 !WARNING | scylla:  [shard 10] storage_proxy - Failed to apply mutation from 10.0.1.146#10: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->10 semaphore)
```

Cassandra-stress failes (failed to write/read the keys) started at `2021-07-15 23:51:52`:
```
< t:2021-07-15 23:51:52,922 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [36394f4c313538503131]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
< t:2021-07-15 23:52:37,350 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > java.io.IOException: Operation x10 on key(s) [36394f4c313538503131]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
< t:2021-07-16 00:10:46,628 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [365033374e3636333630]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-16 00:10:53,433 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout durinjava.io.IOException: Operation x10 on key(s) [365033374e3636333630]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-16 00:12:54,263 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [50354c343631374f3331]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-16 00:12:55,664 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > java.io.IOException: Operation x10 on key(s) [50354c343631374f3331]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-16 00:49:38,067 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [3532373938334b4c3631]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
< t:2021-07-16 00:49:38,485 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > com.datastax.driver.core.exceptions.ReadTimejava.io.IOException: Operation x10 on key(s) [3532373938334b4c3631]: Error executing: (WriteFailureException): Cassandra failure during write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
< t:2021-07-16 00:50:25,817 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > java.io.IOException: Operation x10 on key(s) [4f3530394e3533373430]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
< t:2021-07-16 00:50:37,092 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica respondjava.io.IOException: Operation x10 on key(s) [4f3530394e3533373430]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
```

All missed keys were found on the 3 nodes (RF=3)


![Screenshot from 2021-07-18 15-24-05](https://user-images.githubusercontent.com/34435448/126067092-f227cd7e-f00d-43ff-9a7b-95c5e8e024d0.png)
![Screenshot from 2021-07-18 15-24-25](https://user-images.githubusercontent.com/34435448/126067097-9c0af848-f66f-4e6e-8ee5-2b652de1fbbe.png)
![Screenshot from 2021-07-18 15-25-02](https://user-images.githubusercontent.com/34435448/126067103-a040ef4c-e6c3-4897-9029-c7355719b092.png)
![Screenshot from 2021-07-18 15-27-21](https://user-images.githubusercontent.com/34435448/126067105-a8b2438f-6e7d-467b-a705-e21199d28921.png)

[Live monitor](http://13.49.57.195:3000/d/S2VxbLinz/longevity-multi-keyspaces-60h-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1626364113102&to=1626403249600)

*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.5.rc5-0.20210711.7f96719c5`
Cluster size: 6 nodes (i3.8xlarge)
Scylla running with shards number (live nodes):
   longevity-1000-keyspaces-4-5-db-node-3a9de768-1 (13.51.167.63 | 10.0.2.120): 30 shards
   longevity-1000-keyspaces-4-5-db-node-3a9de768-2 (13.51.69.18 | 10.0.3.247): 30 shards
   longevity-1000-keyspaces-4-5-db-node-3a9de768-3 (13.48.71.98 | 10.0.3.238): 30 shards
   longevity-1000-keyspaces-4-5-db-node-3a9de768-4 (13.53.38.98 | 10.0.0.10): 30 shards
   longevity-1000-keyspaces-4-5-db-node-3a9de768-5 (13.51.193.145 | 10.0.1.242): 30 shards
   longevity-1000-keyspaces-4-5-db-node-3a9de768-6 (13.48.45.37 | 10.0.1.146): 30 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-09a138d84af5dd9e9` (aws: eu-north-1)


Test: `longevity-multi-keyspaces-60h-test`
Test name: `longevity_test.LongevityTest.test_batch_custom_time`
Test config file(s):
- [longevity-multi-keyspaces.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/51c0de0507915702b55c394ef4889377c190c804/test-cases/longevity/longevity-multi-keyspaces.yaml)

Restore Monitor Stack command: `$ hydra investigate show-monitor 3a9de768-c86f-4b82-aafd-b0f9d35085dd`
Show all stored logs command: `$ hydra investigate show-logs 3a9de768-c86f-4b82-aafd-b0f9d35085dd`

Test id: `3a9de768-c86f-4b82-aafd-b0f9d35085dd`


Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/db-cluster-3a9de768.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/db-cluster-3a9de768.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/loader-set-3a9de768.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/loader-set-3a9de768.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/monitor-set-3a9de768.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/monitor-set-3a9de768.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/sct-runner-3a9de768.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/3a9de768-c86f-4b82-aafd-b0f9d35085dd/20210717_033618/sct-runner-3a9de768.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/longevity/job/longevity-multi-keyspaces-60h-test/2/)

**Comment by slivne** [comment]
@juliayakovlev - the issur reported on 4.6 was on steady state no nemesis - are we seeing in 4.5 in steady state no nemesis with full scans the same problem - if not its not a regression.

Please clarify this first so we will know if without nemesis 4.5 with full scans if 4.5 has the same issue or not.

If it doesn't the bug at the top is only relevant to 4.6

With regards to the issue on rebuild - I extracted to https://github.com/scylladb/scylla/issues/9060

**Comment by juliayakovlev** [comment]
> @juliayakovlev - the issur reported on 4.6 was on steady state no nemesis - are we seeing in 4.5 in steady state no nemesis with full scans the same problem - if not its not a regression.
> 
> Please clarify this first so we will know if without nemesis 4.5 with full scans if 4.5 has the same issue or not.
> 
> If it doesn't the bug at the top is only relevant to 4.6
> 
> With regards to the issue on rebuild - I extracted to #9060 and I need your help on that as well

It's not regression between 4.5 and 4.6. 
I got same exception during exactly same scenario:
- same cluster configuration
- no nemesises
- run full scan

First full scan started at `2021-07-18 08:55:57`:
```
2021-07-18 08:55:57.191: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.0.219
```

Finished very fast at `2021-07-18 08:56:09` but with warning:
```
2021-07-18 08:56:09.416: (FullScanEvent Severity.WARNING): type=finish select_from=keyspace1.standard1 on db_node=10.0.0.219 message=Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for keyspace1.standard1 - received only 0 responses from 1 CL=ONE." info={'consistency': 'ONE', 'required_responses': 1, 'received_responses': 0}
```

Second  full scan started at `2021-07-18 09:56:10`:
```
2021-07-18 09:56:10.103: (FullScanEvent Severity.NORMAL): type=start select_from=keyspace1.standard1 on db_node=10.0.0.219
```

And not finished. Tests failed with cassandra-stress ReadTimeoutException:
```
java.io.IOException: Operation x10 on key(s) [39364e3238324f4c3230]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [31393133353639373330]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [4c384b313234304f4d30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [324d35504f5037383331]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [4e384f31393937324f30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [35503533314d36393830]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [3835333833394f363730]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [4b3931344d36354c4e30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [3930324c3538324c3130]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)java.io.IOException: Operation x10 on key(s) [4b4d4d34394e50304b30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [383438303450314e3431]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
java.io.IOException: Operation x10 on key(s) [4c50313431374c383131]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
```

![Screenshot from 2021-07-19 08-14-33](https://user-images.githubusercontent.com/34435448/126106477-2f6e1481-0adb-40d2-bfbe-4fad8f180f5d.png)

[Live cluster](http://13.53.87.144:3000/d/mRsxW6m7k/longevity-50gb-3days-missed-keys-scylla-per-server-metrics-nemesis-master?orgId=1&from=1626596343000&to=now&refresh=30s&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-sct_tags=FullScanEvent)

Cluster is alive

Restore Monitor Stack command: `$ hydra investigate show-monitor 12cb11be-4dda-4888-a837-bbaea69800b6`
Show all stored logs command: `$ hydra investigate show-logs 12cb11be-4dda-4888-a837-bbaea69800b6`

Test id: `12cb11be-4dda-4888-a837-bbaea69800b6`


Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/db-cluster-12cb11be.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/db-cluster-12cb11be.tar.gz)
events - [https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/events.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/events.log.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/loader-set-12cb11be.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/loader-set-12cb11be.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/monitor-set-12cb11be.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/monitor-set-12cb11be.tar.gz)
events - [https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/raw_events.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/12cb11be-4dda-4888-a837-bbaea69800b6/20210718_193825/raw_events.log.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/Reproducers/job/longevity-50gb-3days-missed-keys/2/)

**Comment by slivne** [comment]
Please create a reproducer job that we can run and try to reproduce this - how long does it take to run a test ...

We may attempt to run more then a single job at a time to try and do bisect faster.

**Comment by juliayakovlev** [comment]
> Please create a reproducer job that we can run and try to reproduce this - how long does it take to run a test ...
> 
> We may attempt to run more then a single job at a time to try and do bisect faster.

Reproducer jobs running longevity-50gb-3days with no nemesis, with full scan:

1. branch-4.5 - issue has been reproduced after about 12 hours:
https://jenkins.scylladb.com/job/scylla-4.5/job/Reproducers/job/longevity-50gb-3days-missed-keys/

2. master - issue has been reproduced after about 10 hours:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/reproducers/job/repr-longevity-50gb-3days-missed-keys/
