### ISSUE TITLE
Queries which need to reconcile large pages due to a long prefix of tombstones fail on mutation application

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#9111]
I saw this happening during `select`, which needs to reconcile replicas, from a partition which has 1M row deletions before a live row:

```
ERROR 2021-07-29 01:23:07,589 [shard 0] storage_proxy - exception during mutation write to 127.0.0.3: std::invalid_argument (Mutation of 76000092 bytes is too large for the maximum size of 16777216)
```

**Comment by nyh** [comment]
The fix for this issue was reverted, so reopening. The new PR (https://github.com/scylladb/scylladb/pull/15414) will hopefully close it again soon.

**Comment by denesb** [comment]
The fix is too risky, not backporting.
