### ISSUE TITLE
Cache: support reverse queries efficiently

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9132]
From [Supporting reversed queries efficiently](https://docs.google.com/document/d/192XATwnsv_VHc76AsEZmVkMgVh0I33OzYCFn3LQDT5o/edit):

> Cache currently uses a complex “weaving” system where it supplies cached rows from cache and uncached rows from disk.
> We can simplify and use this algorithm for reversed reads:
>
> Try to fill a page from cache using reversed scan
> If we reached end-of-data or end-of-page, and did not encounter a hole, return that data
> Otherwise, fall back to the sstable reader.
> We can consider populating cache from the just-read data, or not.
>
> We can consider phase 1 that just bypasses cache for reversed reads, but that may regress workloads that read small partitions using reversed reads now.

Refs #9130
Refs #9131

**Comment by bhalevy** [comment]
Refs #1413

**Comment by bhalevy** [comment]
@tgrabiec / @xemul how are we standing with this issue?  Is it still needed?
cc @paszkow @michoecho

**Comment by tgrabiec** [comment]
Looks like this issue is obsolete. Cache supports reverse queries natively. SStable reader also supports it, except for the multi-partition range scans: https://github.com/scylladb/scylladb/issues/9134#issuecomment-1784642231.
