### ISSUE TITLE
Don't report latencies metrics for scheduling group that don't have queries

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#9159]
Scheduling groups that do not have queries shouldn't report latencies:
atexit, background_reclaim, compaction, gossip, main, mem_compaction...

**Comment by amnonh** [comment]
@eliransin it will be good to solve this when tempring with the scheduling groups

**Comment by eliransin** [comment]
@amnonh are you referring to storage_proxy stats? If not or not only, which stats are you referring to?

**Comment by amnonh** [comment]
@eliransin yes, storage_proxy stats

**Comment by amnonh** [comment]
Closed by https://github.com/scylladb/scylladb/commit/2c0932cc412c682ddf7607fd793c1b1a7ea517be
