### ISSUE TITLE
order of columns from create table is not kept

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylladb#9201]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.4
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by tarzanek** [comment]
consider this:

```
cqlsh> create KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
cqlsh> use test
   ... ;
cqlsh:test> CREATE TYPE testtype (
   i int,
   s text);

cqlsh:test> CREATE TABLE columnordertestthree (
c text,
s text,
pct float,
myset frozen<list<frozen <testtype>>>,
PRIMARY KEY (c,s)
);
cqlsh:test> describe test;

CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TYPE test.testtype (
    i int,
    s text
);

CREATE TABLE test.columnordertestthree (
    c text,
    s text,
    myset frozen<list<frozen<testtype>>>,
    pct float,
    PRIMARY KEY (c, s)
) WITH CLUSTERING ORDER BY (s ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

Note that order of pct and myset is now switched ...
Is this expected? I'd expect columns get created exactly in order how DDL specifies them

**Comment by tzach** [comment]
I see the same with Apache Cassandra 3.11, so at least its compatible

**Comment by psarna** [comment]
@tarzanek it's expected. You'll always get the primary key in the correct order because it actually matters (partition key needs proper ordering to compute tokens from, and clustering key defines the ordering within a partition), but the regular columns are just a map, so regular columns will just get printed in arbitrary order - and I'm pretty sure it will be lexicographical, but it's an implementation detail.

**Comment by tarzanek** [comment]
so I guess this should be documented, what do you think @tzach

**Comment by nyh** [comment]
It may be interesting to note in https://docs.scylladb.com/getting-started/ddl/#create-table-statement that the order of the column definition doesn't matter. @psarna is correct that clustering key columns are ordered - but this order is NOT related to the order of the column definitions in CREATE TABLE but rather it is determined in the PRIMARY KEY specification, e.g., you can have
```
CREATE TABLE tbl (
a int,
b int,
c int,
d int,
PRIMARY KEY ((d,c),b, a)
);

The order that a,b,c,d were listed initially doesn't matter - the partition key's first column will be `d` and the second `c`, and the clustering key's first column is `b` and the second is `a`. It's probably true that DESCRIBE TABLE will list them in this new order (and the regular columns in some unknown order), but I don't know if that deserves mention in the documentation - the whole point of DESCRIBE TABLE is to create a CREATE TABLE statement that can be used in CQL, and if we document in CREATE TABLE that the order doesn't matter, nobody can make any assumptions on it.

**Comment by mykaul** [comment]
> the problem here is mapping between dataframes in spark, where the created table didn't match its original from parquet but it is likely a spark connector dataframe bug too (which has a mapping override workaround/fix) https://github.com/datastax/spark-cassandra-connector/blob/master/doc/5_saving.md#example-creating-a-new-table-using-a-completely-custom-definition

@tarzanek - Is there an issue we can track on the spark connector?
