### ISSUE TITLE
DOCS: Runtime error

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylladb#9250]
/home/lauranovich/github-repo/laura-scylla-oss-docs/docs/service_levels.md: WARNING: document isn't included in any toctree
/home/lauranovich/github-repo/laura-scylla-oss-docs/docs/contribute/review-checklist.md:13: WARNING: None:any reference target not found: ./coding-style
/home/lauranovich/github-repo/laura-scylla-oss-docs/docs/guides/HACKING.md:392: WARNING: None:any reference target not found: docs/guides/debugging
/home/lauranovich/github-repo/laura-scylla-oss-docs/docs/service_levels.md:6: WARNING: Pygments lexer name 'CREATE TABLE system_auth.role_attributes (' is not known
/home/lauranovich/github-repo/laura-scylla-oss-docs/docs/service_levels.md:6: WARNING: Pygments lexer name "SELECT * FROM  system_auth.role_attributes WHERE role='r' and attribute_name='service_level'" is not known
/home/lauranovich/github-repo/laura-scylla-oss-docs/docs/service_levels.md:27: WARNING: Pygments lexer name 'CREATE TABLE system_distributed.service_levels (' is not known
| writing output... [100%] service_levels
|

**Comment by tzach** [comment]
Not relevant anymore. Closing.
