### ISSUE TITLE
View has less then expected rows after nodetool refresh

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#9262]
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20210823.3c6a7d2dc
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): relocatables packages (unstable/master:2021-08-23T23:43:29Z)

During testing of `load-and-stream` feature I added tests for views building after load.
In case of increase cluster - test data was created on small cluster (in my test 2-nodes) and has been loaded to the bigger cluster (in my test 4-nodes), view has expected rows amount on my laptop but failed in dtest-byo.
But when data was loaded from bigger cluster to smaller, view has less rows then expected.

Here the scenarios:

**Test 1 - increase cluster**
- Test data was created on the 2-nodes cluster, keyspace RF=2
- New cluster is 4-nodes, keyspace RF=3

Result: 
local run **succeeded**: Row count in the table and index view as expected
dtest-byo **failed**: https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/596/testReport/
```
Starting a cluster of 4 node(s)...
CREATE COLUMNFAMILY standard1 (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {}
Create index: CREATE INDEX c2_ind ON standard1 (c2)
Copy sstables of node1 to node4
Running load and stream on the node node4 for keyspace1.standard1'
Send load_and_stream api: http://127.0.52.4:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node2 to node1
Running load and stream on the node node1 for keyspace1.standard1'
Send load_and_stream api: http://127.0.52.1:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Waiting for view keyspace1.c2_ind_index to finish building...
Checking rows on node1, keyspace1.standard1... - Passed
Checking rows on node1, keyspace1.c2_ind_index... - Passed
Checking rows on node2, keyspace1.standard1... - Passed
Checking rows on node2, keyspace1.c2_ind_index... - Passed
Checking rows on node3, keyspace1.standard1... - Passed
Checking rows on node3, keyspace1.c2_ind_index... - Passed
Checking rows on node4, keyspace1.standard1... - Passed
Checking rows on node4, keyspace1.c2_ind_index... - Passed
```

**Test 2 - decrease cluster**
- Test data was created on the 4-nodes, keyspace RF=3
- New cluster has 2-nodes cluster, keyspace RF=2

Result: test **failed**. Row count in the index view less then expected, in the table - as expected

```
Starting a cluster of 2 node(s)...
CREATE COLUMNFAMILY standard1 (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {}
Create index: CREATE INDEX c2_ind ON standard1 (c2)
Copy sstables of node1 to node1
Send load_and_stream api: http://127.0.48.1:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node2 to node1
Send load_and_stream api: http://127.0.48.1:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node3 to node2
Send load_and_stream api: http://127.0.48.2:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node4 to node2
Send load_and_stream api: http://127.0.48.2:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Waiting for view keyspace1.c2_ind_index to finish building...
Checking rows on node1, keyspace1.standard1...
Passed
Checking rows on node1, keyspace1.c2_ind_index...
Count failed: 478 != 1000 : Expected 1000 rows in keyspace1.c2_ind_index on node1. Got 478
```

I also ran 2 similar tests:
1. with materialized views instead of SI - test failed  same error
2. without `load-and-stream` parameter - test failed with same error

https://github.com/scylladb/scylla/issues/9205#issuecomment-906521017

**Comment by juliayakovlev** [comment]
Tests for reproduce:
```
repo: https://github.com/juliayakovlev/scylla-dtest.git
branch: load_and_stream
Failed test:

migration_test.TestLoadAndStream.load_and_stream_decrease_cluster_with_index_view_test
migration_test.TestLoadAndStream.load_and_stream_decrease_cluster_with_mv_test
```

**Comment by juliayakovlev** [comment]
I found that this issue is reproduced when run the test using API. If run refresh with nodetool it's passed

**Comment by asias** [comment]
> I found that this issue is reproduced when run the test using API. If run refresh with nodetool it's passed


How is it going with the dtest for the load and stream at the moment? Are they passing?

I am not sure what you meant by "If run refresh with nodetool it's passed", did you mean the test passed with nodetool refresh with the --load-and-stream flag (calls the restful api in the end with the load and stream flag) or using nodetool refresh without any flag which uses the old single node refresh.

**Comment by asias** [comment]
are those tests merged in scylla dtest master?

**Comment by slivne** [comment]
@juliayakovlev ping

**Comment by juliayakovlev** [comment]
> are those tests merged in scylla dtest master?

Sorry for delay, I missed it.
All load-and-stream test are merged and passed on master:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1130/testReport/migration_test/TestLoadAndStream_with_3_0_md/

`test_load_and_stream_primary_replica_only` test is skipped due the issue https://github.com/scylladb/scylla-tools-java/issues/282

**Comment by piodul** [comment]
Didn't reproduce in the last ~two years, closing.
