### ISSUE TITLE
scrub compaction doesn't return an error status to the api caller if it finds any invalid parts

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9289]
Currently (b3f4a37a7) it looks like we just count some of the validation errors we hit in `_stats.errors`, when we hit e.g. a malformed sstable exception (meaning the sstable is screwed and can't be validated).
See https://github.com/scylladb/scylla/blob/b3f4a37a758e5f77ba7f932203aa56fe98b48755/compaction/compaction_manager.cc#L805

Validation errors, e.g. like invalid partition, don't seem to be counted at all, other than being reported to the log.
For example: https://github.com/scylladb/scylla/blob/b3f4a37a758e5f77ba7f932203aa56fe98b48755/compaction/compaction.cc#L1208-L1222

For using scrub as part of automation, we should convey the scrub status up the api stack so that it should return a success status iff it found no validation problems in the scrubbed sstables.

**Comment by bhalevy** [comment]
Refs #9288

**Comment by bhalevy** [comment]
Cc @denesb @raphaelsc @amnonh

**Comment by bhalevy** [comment]
@Deexie this is a good issue to get familiar with the integration between compaction and the api layer.

**Comment by amnonh** [comment]
After looking at the JMX (the other API user) it seems that the expected results are:
1 - abort
2 - completed with error
Everyhing else, ok

**Comment by bhalevy** [comment]
@amnonh can you please point to a reference?
I couldn't find it.
Whatever it is, let's document it so there's agreement on what the int returned by `keyspace_scrub` means.

**Comment by bhalevy** [comment]
Can be closed with d4abb73389e3d63cf2511eda285baae0fcf38941
