### ISSUE TITLE
commitlog test: test_allocation_failure might not create memory tight enough environment

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#9391]
We have seen a failure of this test with:
`std::runtime_error (Adding mutation of size 16777203 succeeded unexpectedly`

https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/next/336/testReport/junit/test_boost_commitlog_test/cc/test_allocation_failure/

Examining the code path that can lead to this revealed that this test might leave behind just enough memory to create the
desired size of fragmented buffer.

The problem is that it is wrogly assumed that after:
https://github.com/scylladb/scylla/blob/d7ac699a555a2d5423b6bc66458df3b9c53002fc/test/boost/commitlog_test.cc#L592

The memory content will be equal to 128K which means that after the continuation allocation it is guarantied that there are no more default_size fragments for the fragmented output stream.
However, after the aforementioned line, all that we can guarantee is that there is no more than `(128K*2) - 1` but this amount of
memory might (and probably was in the failure instance) just enough to accommodate the continuation and the fragmented buffer together.

**Comment by eliransin** [comment]
After examining the code path I can think of two places from where the extra memory can come.
1. The most likely is that there is some amount of memory < 128K that is left after the loop and is enough for allocating the continuation along with the last part of the fragmented buffer (which can be smaller than 128K).
2. The less likely is the `erase` statement which might indirectly release some memory from the list structure.

I will propose a patch that will try to address those two problems.

**Comment by elcallio** [comment]
Did by this perhaps start to happen after the alloc-path was converted to use coroutines instead of raw continuations? 
The change is probably sound in the sense that any such test case is sound (I though this test was disabled by default?), but perhaps it would be better to be able to white-box this as just ensure we OOM where we want, by hooks or something?

**Comment by eliransin** [comment]
> perhaps it would be better to be able to white-box this as just ensure we OOM where we want, by hooks or something?

I am not sure I understand - can you explain what do you mean, I guess you are suggesting to generalize the test case (or at least to add a hook that will OOM where we want - error injection?)
 

> Did by this perhaps start to happen after the alloc-path was converted to use coroutines instead of raw continuations?

I am not sure, but the failure was in an old version that I think doesn't have the coroutines ( I will double check and get back to you)

**Comment by elcallio** [comment]
Yes, very specific error injection, for this particular alloc (not general, stochastic). 
Interesting about old version. 
In any case, your fix is good. lgtm.

**Comment by kostja** [comment]
The test is passing.
