### ISSUE TITLE
Empty error message from wrong query: nested exceptions "hide" the original message once it reaches cql layer.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#9497]
The issue found during running dtest EaR test with enterprise version `2021.2.dev-0.20211013.107a2afaa`. But it's relevant for OSS as well.

During the tests we try to create the table with wrong cipher_algorithm option and expect to receive clear error message in the exception.
There are 5 scylla_encryption_options when empty message got within exception:
('Unable to complete the operation against any hosts', {})'

Those are configurations:
```
Abc/AES/ECB , length 256, key provider KeyProviderEnum.kmip
AbcDES/CBC/PKCS5Padding , length 56, key provider KeyProviderEnum.default
Abc/RC2 , length 80, key provider KeyProviderEnum.local
RC2Abc/ , length 80, key provider KeyProviderEnum.replicated
RC2Abc , length 128, key provider KeyProviderEnum.local
```

Example of query:
```
CREATE COLUMNFAMILY ks.cf (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {} AND scylla_encryption_options={'cipher_algorithm': 'AbcDES/CBC/PKCS5PaddingAES', 'secret_key_strength': 56}
```

But when @elcallio  ran the same query from cqlsh, he got the error message. 
@elcallio  suppose that we have nested exceptions that "hide" the original message once it reaches cql layer.

**Comment by fruch** [comment]
according to the testing, seems the issue was resolved, don't know exactly when, and by which change.
