### ISSUE TITLE
staging sstables are not cleaned up in cleanup compaction potentially causing data resurrection

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9559]
Currently (scylla 4.6.dev 034f79cfb), when cleanup compaction is performed via `compaction_manager::perform_cleanup`
https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/compaction/compaction_manager.cc#L844

We select the sstables to compact with `get_candidates`
https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/compaction/compaction_manager.cc#L185

that calls `table::in_strategy_sstables`
https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/table.cc#L1140-L1146

that filters out staging sstables that are undergoing view building.

This means that when view building completes and the sstables are moved out of staging
https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/db/view/view_update_generator.cc#L128
calling https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/table.cc#L2214

They may contain tokens that are no longer owned by the current node, if a topology change occurred after the said sstables were written and before view build completed.

**Comment by bhalevy** [comment]
I think that the right way to go here is not to fix the cleanup case specifically, but rather allow compaction of sstables in staging, and mark them for deletion when compaction is done, as we do in the `delete_sstables_for_interrupted_compaction` case:
https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/compaction/compaction.cc#L778-L786

Then, when view building is done, the sstable will be auto-deleted in `close_files`:
https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/sstables/sstables.cc#L2443-L2462

and `move_sstables_from_staging` can be skipped.

**Comment by bhalevy** [comment]
An important corner case that needs to be handled is keeping the sstable around until view building successfully completes.
For this we may want to introduce a new `mark_for_deletion` code:
https://github.com/scylladb/scylla/blob/bd0b573a9252045bcc86bc48eb919ff807c740a4/sstables/sstables.hh#L528-L532

e.g. 'tentative', that can be examined and turned into `marked` by the view building code, but will not cause auto-deletion, by itself, in `sstable::close_files()`.

**Comment by bhalevy** [comment]
Cc @raphaelsc @psarna @nyh

**Comment by bhalevy** [comment]
Simplified (and untested yet) idea: create the sstables with hardlinkes both in main table directory and under `staging`.
Normal reads, compaction, snapshot, etc. will not consider the staging directory at all and will treat the staging sstables in the main directory as any other sstable.  The hardlink in the staging directory will only function to mark the sstables that need view building as it does today and when vie building is done it will just unlink the sstable unconditionally from the staging dir.
Compaction (and kind) will happen orthogonally and independently on the hardlink in the main directory regardless of staging.

Truncate will need to remove all the hardlinks in staging after stopping the view build.

Snapshot will consider only sstables in the main directory.

**Comment by raphaelsc** [comment]
@bhalevy If I understandl correctly, the sstables in staging dir are excluded, but the cloned ones in base dir are not. a possible solution is to exclude any sstable that shares the same run id as the ones being explicitly excluded

**Comment by bhalevy** [comment]
> @bhalevy If I understandl correctly, the sstables in staging dir are excluded, but the cloned ones in base dir are not. a possible solution is to exclude any sstable that shares the same run id as the ones being explicitly excluded

See my answer in https://github.com/scylladb/scylla/pull/10901#issuecomment-1168737580
I don't think there a safe way to exclude the cloned data (in contrast to the cloned sstable files) after it's compacted away.

**Comment by bhalevy** [comment]
A better approach that could work is stopping view building during cleanup, cleaning up the sstables in the staging dir in-place, then resuming view building if there are any staging sstables left.

**Comment by bhalevy** [comment]
Cc @raphaelsc @denesb

**Comment by DoronArazii** [comment]
@bhalevy can you achieve this for 5.2?

**Comment by bhalevy** [comment]
> @bhalevy can you achieve this for 5.2?

Unlikely, but I'll try to make some progress towards that.
(and fix #11933 in the process)

**Comment by mykaul** [comment]
What's missing to close this for 5.3?

**Comment by DoronArazii** [comment]
> @bhalevy What's missing to close this for 5.3?

@bhalevy ping

**Comment by bhalevy** [comment]
To close this issue (which I'm not sure is feasible for 5.3.0), cleanup compaction needs to resolve only after all the sstables that were detected as requiring cleanup were cleaned up.

Making cleanup persistent, so it would reevaluate sstable if the node restarts would be great too, but it's out of the scope of this issue.

**Comment by DoronArazii** [comment]
Removing "backport candidate" label as it's should be added only once the issue being closed.

**Comment by denesb** [comment]
This is not a simple backport. There were two big series that I remember, maybe even more (@bhalevy).
Did we decide we want to backport this, despite the risk involved? If yes, do we want to backport straight away or we wait for it to spend some time in master first.

In any case, I think @bhalevy will need to prepare backport PRs for all target versions, and make sure all follow-up fixes are included.

**Comment by mykaul** [comment]
> @scylladb/scylla-maint please consider backport

Why?

**Comment by DoronArazii** [comment]
> > @scylladb/scylla-maint please consider backport
> 
> Why?

Asked by the field - https://github.com/scylladb/scylla-enterprise/issues/2434#issuecomment-1504115860.
@mykaul please update if it's going to be backported, or shall I close the 3 request-issues.
