### ISSUE TITLE
Scylla errors under YCSB logs:  failure_detector - Not marking nodes down due to local pause

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#957]
The following errors under YCSB logs
(same use case which produce #956)
`
Feb 29 11:45:40 alon-scylla-01.localdomain scylla[8629]:  [shard 9] compaction - Compacting [/var/lib/scylla/data/ycsb/usertable-282f0b80deca11e5907f000000000000/ycsb-usertable-k
Feb 29 11:45:41 alon-scylla-01.localdomain scylla[8629]:  [shard 0] failure_detector - Not marking nodes down due to local pause of 7085 > 5000 (milliseconds)
Feb 29 11:45:42 alon-scylla-01.localdomain scylla[8629]:  [shard 9] compaction - Compacted 4 sstables to [/var/lib/scylla/data/ycsb/usertable-282f0b80deca11e5907f000000000000/ycs
F
`

**Comment by slivne** [comment]
should be fixed by 022c7e50a1b87f05e68fd02b58b11d8b0e264f57

should be retested with 0.19

**Comment by slivne** [comment]
@tzach in the next round can you verify this was fixed

**Comment by tzach** [comment]
Issue not seen for a few years.
