### ISSUE TITLE
cqlsh - Support for Python 3 and Server-side DESCRIBE statements

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#9571]
**Installation details**
Scylla version (or git commit hash): 4.5.1-0.20211024.4c0eac049
Cluster size: 1

**Description**
Cassandra 4 recently released `cqlsh` 6.0.0 (see [cqlsh pip](https://pypi.org/project/cqlsh/)) with support for Python 3 and several other breaking changes, such as server-side DESCRIBE statements no longer being handled by the client side (see [CASSANDRA-14825](https://issues.apache.org/jira/browse/CASSANDRA-14825) -- thanks @slivne !)

It turns out that C* 4.0 changes and the new `cqlsh` implementation effectively break issuing `DESC` statements with Scylla (and Cassandra 3.x also, for that matter), and the shell will reject our requests with:

```shell
Connected to  at 127.0.0.1:9042
[cqlsh 6.0.0 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> DESC SCHEMA;

WARN: DESCRIBE|DESC was moved to server side in Cassandra 4.0. As a consequence DESRIBE|DESC will not work in cqlsh '6.0.0' connected to Cassandra '3.0.8', the version that you are connected to. DESCRIBE does not exist server side prior Cassandra 4.0.
cqlsh> 
```

The rationale for moving `DESC` statements to the server-side is reasonably well explained within [CASSANDRA-14822](https://issues.apache.org/jira/browse/CASSANDRA-14822), where different drivers had different ways of parsing the contents of `system_schema` tables and could potentially dump incorrect schema parameters that were removed. Interestingly enough, for that specific issue, `read_repair_chance` and `dclocal_read_repair_chance` were the removed options, which Scylla has officially deprecated as of https://github.com/scylladb/scylla/issues/3502 .

In addition to these, it is time to get rid of Python2.7. Scylla already ships a python3 binary that could be used to support cqlsh but, currently, we still depend on Python2.7 for cqlsh compatibility. Scylla docker image is currently based on top of CentOS7, which stopped shipping new Python2.7 releases at `2.7.5`, even though the latest Python 2.7 release is `2.7.18`! :-) 

Supporting Python2.7 makes our container images unnecessarily bigger and can cause all type of weirdos - for example, since Python2 default encoding is still ASCII (see the [Python mailing-list](https://www.mail-archive.com/python-dev@python.org/msg44652.html)) one of such weirdos that could have been avoided if we used Python3 can be seen at #9570 .

It is not enough to exhaust that Python2.7 has been long gone deprecated. [Ubuntu 20.04 no longer ships it by default](https://lists.ubuntu.com/archives/ubuntu-devel/2020-February/040918.html) and eventually support for it should be removed from all major Linux distributions.

Therefore, given the breaking `DESCRIBE SCHEMA` change mentioned, we can't simply merge Cassandra 4 `cqlsh` implementation without - first - implementing it on Scylla server-side. Another lazy option would be to modify the newer `cqlsh` to make it parse our `system_schema` tables in the old fashion, but that will effectively just delay history to repeat itself.

**Comment by eliransin** [comment]
@psarna added you so we know who to approach :slightly_smiling_face:

**Comment by psarna** [comment]
Do we want higher priority on this? A while ago I queued this task for @Jadw1 after he's done with distributing UDA statements.

**Comment by bschoening** [comment]
CQLSH in Cassandra 4.1 has removed Python 2.7 support.

**Comment by vladzcloudius** [comment]
@fee-mendes Just one clarification: U20 still ships Python2: from the post you quoted above

```
 - 20.04 LTS will ship python2. Derivatives who cannot port some
applications are able to use python2 for the 20.04 LTS release.
```

**Comment by vladzcloudius** [comment]
> @vladzcloudius kinetic seems to also be packaging Python2. As it is clear in the opening message, Python2 is no longer the default.

My point was that on U20 it still is. 

> There is no python-is-python2 package any longer. A smart and necessary move so we can finally move forward. :-)

No argument about that. ;)
I also agree that it makes a lot of sense to switch to `cqlsh` written in Python3.
Having a dependency on Python2 is quite an inconvenience these days.

**Comment by tzach** [comment]
@eliransin can we close this?

**Comment by Jadw1** [comment]
I'm closing the issue. Server-side describe was introduced here https://github.com/scylladb/scylladb/pull/11106 and I believe Python 3 was also added in the meantime.

Cc @eliransin @ptrsmrn

**Comment by mykaul** [comment]
@fruch - was there anything to be done on the cqlsh side to support server-side DESCRIBE?

**Comment by fruch** [comment]
> @fruch - was there anything to be done on the cqlsh side to support server-side DESCRIBE?

no

**Comment by mykaul** [comment]
Then we should probably remove the 'and Server-side DESCRIBE statements' from this issue...
