### ISSUE TITLE
Commitlog hard limit 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#9625]
collecting all the issues related to commitlog limit - so we can revisit them once we enable it again.

- [x] #8969
- [x] #8877 
- [x] #9053 
- [x] #9054

**Comment by slivne** [comment]
@eliransin / @roydahan I know we discussed this and I think eliran actually checked and from his end it seems commitlog hard limit can be enabled (its not worse then without it ...) lets align and then verify the above - leaving in 5.0 as it may be important

**Comment by eliransin** [comment]
@slivne 
There is #9331 , the population indeed don't take longer, however, on additional runs from the ones @roydahan requiered
there are some unexplained stalls that might or might not be related. @elcallio is supposed to be looking at this, we will do it next
week.

**Comment by DoronArazii** [comment]
@eliransin @elcallio Any new with this one?

**Comment by eliransin** [comment]
Still not, trying to push this. The summary is that we are trying to prove that it works and doesn't introduce regressions
(There are no known bugs).

**Comment by DoronArazii** [comment]
@eliransin it's in your queue? (asking for a customer)

**Comment by eliransin** [comment]
Yes.
We have PR #10974 that I still need to provide a targeted test to. Then it will be merged and will be part of the relevant enterprise
releases.

**Comment by DoronArazii** [comment]
@eliransin / @wmitros what's the status?

**Comment by mykaul** [comment]
@eliransin - per our discussion today - let's get it in finally - to 5.4!

**Comment by avikivity** [comment]
Possible followup - add feedback from the amount of space remaining until we reach the limit to memtable flush shares, so as we get closer to the limit we increase the flush rate. Need to prove it's necessary.

**Comment by eliransin** [comment]
Some progress,  commitlog hard limit by default PR (#10974 ) queued on next.

**Comment by eliransin** [comment]
Hard limit by default is in. We need to go over those issues one by one and validate if it really fixed them.

**Comment by kostja** [comment]
I closed all dependent issues, closing this one as well.
