### ISSUE TITLE
[tools/scylla-sstable]: add built-in scripting support

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#9679]
Although https://github.com/scylladb/scylla/issues/9678 already enables scripting, dumping the entire content of the sstable can be very slow for large sstables. Add JSON generation + parsing on top of that. It would be much faster if `scylla-sstable` supported loading scripts and feeding data to them directly, allowing them to do anything they want with it.
Possible scripting languages:
* Lua - already built-in, quick-to-learn, simple to write bindings for (we already have examples);
* Python - almost everybody is already familiar with it but we don't have it in scylla, adding it just for a tool might meet some resistance;
* WASM - already in scylla, very flexible, any language can be compiled into it but needs a compilation step and we still don't have any bindings beyond toy C examples;

**Comment by avikivity** [comment]
Not a bug, not backporting.
