### ISSUE TITLE
messaging service build_reloadable_server_credentials flakiness

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9775]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4261/testReport/junit/internode_ssl_test/TestInternodeSSL/dtest___putget_with_reloaded_certificates_test/
scylla-next on top of e032f92c5cf400c6bdc253c0dbba735ce4aafe84
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/internode_ssl_test.py", line 58, in putget_with_reloaded_certificates_test
    self.__putget_with_internode_ssl_test('all', internode_encryption='all', reload_certs=True)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/internode_ssl_test.py", line 106, in __putget_with_internode_ssl_test
    "internode-ccm_node.pem", "internode-ccm_node.key"], from_mark=mark)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/native_transport_ssl_test.py", line 21, in wait_for_cert_reload
    node.watch_log_for("^.*{}.*Reloaded.*{}\.*".format(module, f.replace('.', '\.')), from_mark=from_mark)
  File "/jenkins/workspace/scylla-master/next/scylla-ccm/ccmlib/node.py", line 486, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 09 Dec 2021 00:20:34 [node1] Missing: ['^.*messaging_service.*Reloaded.*internode-ccm_node\\.pem\\.*']:
INFO  2021-12-09 00:10:27,283 [shard 0] messaging_.....
See system.log for remainder
```

Although I'm tempted to consider this a test bug, the node logs seem to indicate some race across shards:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4261/artifact/logs-gating.release.2/1639009237913_internode_ssl_test.TestInternodeSSL.putget_with_reloaded_certificates_test/node1.log
```
INFO  2021-12-09 00:10:27,283 [shard 0] messaging_service - Reloaded {/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-trust.pem}
INFO  2021-12-09 00:10:27,283 [shard 1] messaging_service - Reloaded {/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-trust.pem}
```

Vs.

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4261/artifact/logs-gating.release.2/1639009237913_internode_ssl_test.TestInternodeSSL.putget_with_reloaded_certificates_test/node2.log
```
INFO  2021-12-09 00:10:27,283 [shard 1] messaging_service - Reloaded {/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-trust.pem}
INFO  2021-12-09 00:10:27,285 [shard 0] messaging_service - Reloaded {/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-ccm_node.pem, /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-ccm_node.key}
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4261/artifact/logs-gating.release.2/1639009237913_internode_ssl_test.TestInternodeSSL.putget_with_reloaded_certificates_test/node3.log
```
INFO  2021-12-09 00:10:27,283 [shard 1] messaging_service - Reloaded {/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-trust.pem}
INFO  2021-12-09 00:10:27,285 [shard 1] messaging_service - Reloaded {/jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-ccm_node.pem, /jenkins/workspace/scylla-master/next/scylla/.dtest/dtest-nmxwt4h6/test/internode-ccm_node.key}
```

`messaging_service::start_listen()` is being called in parallel on all shards

https://github.com/scylladb/scylla/blob/e032f92c5cf400c6bdc253c0dbba735ce4aafe84/message/messaging_service.cc#L222-L229

@elcallio do they all race on building the reloadable_server_credentials?

Should we do that only on shard 0 and then copy the creds to all other shards?

**Comment by bhalevy** [comment]
ping @elcallio 
this is still happening.

See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/1019/testReport/junit/internode_ssl_test/TestInternodeSSL/test_putget_with_reloaded_certificates/

**Comment by elcallio** [comment]
I'd say it is a log parsing error, i.e. cannot assume the reload file list looks any way particular (need more wildcards).
It is not an error that we have a reloadable per shard service. The alternative would be either making messaging service aware of other shards, or make reloadable_credentials shard-safe (internally sharded - not very pretty). We will indeed potentially get different order of rewrite notifications per shard, and can quite possibly get various permutations of partial reloads before settling. 
One option would maybe be to add some delay + cleverness to the reloadable object itself. For example, be aware of the pair-nature of certificates and keys and wait X seconds if only one is modified before actually reloading to reduce number of partial loads.

**Comment by mykaul** [comment]
@elcallio - what's the next action here?

**Comment by elcallio** [comment]
Does the test still fail occasionally (on the above)? Or are the fixes done enough? If not, I guess revisit the log parsing expressions.

**Comment by DoronArazii** [comment]
Last hit was more than 1 year ago - closing it for the time being.
We will re-open if necessary.
