### ISSUE TITLE
Scylla needs a generic job tracker for long-running jobs

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9809]
#8392 and #7845, for example call for extending the api for the benefit for better control of compaction jobs.

Rather than adding compaction_manager specific code, we should reuse most of the concepts already implemented by scylla's repair tracker and introduce a generic job tracker to track all kinds of long-running jobs in the system,
including repair, compaction, view-building, and possibly more in the future.

On top of it, add a unified api to list jobs (by module), get their status and progression,
wait for their completion, abort them, and possibly also support pause/resume (might be useful for controlling view-building, for example).

Each job should have a uuid (and a parent uuid when its a subordinate job, e.g. major compaction of a keyspace generating major compaction per table).
Also, jobs should have a per module sequence number, like today's repair jobs.

Job's abort_source can be used by the job's specific implementation so it can be subscribed to get aborted.
Otherwise, the job should be marked as non-abortable and be presented this way over the api.

Job's status can be: RUNNING, SUCCESSFUL, or FAILED.

To report the job progression, implementation can provide the units (as a string), and 2 counters: `total` and `completed`, updated periodically by the job implementation as it makes progress.

**Comment by bhalevy** [comment]
Design doc: https://docs.google.com/document/d/1w-BWSPHIrG-CdD5ZoS-sYCSlQNhOxaxi7MEjEqBESLo/edit

**Comment by amnonh** [comment]
This should probably be a metric (gauge) with or without the API with the job type as label, if possible it should be reported per node not per shard.
