### ISSUE TITLE
Scylla should setup irq_cpu_mask

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9903]
scylladb/seastar@50b683aef99e5af27f50bf61de6a774258a329d4 introduced an explicit `irq_cpu_mask` configuration variable in perftune.yaml (and a command line option) to perftune that is aimed at replacing the current mode-based configuration.

See https://github.com/scylladb/seastar/pull/939#pullrequestreview-750317106

We may want to to have a `scylla_irq_setup` script similar to `scylla_io_setup` that can do the auto-detection and/or use presets for supported cloud machine types.

**Comment by bhalevy** [comment]
@xemul I'm putting this on your queue as you're intimately familiar with hwloc / numa / irq balancing issues.

Cc @vladzcloudius @gcarmin @avikivity

**Comment by bhalevy** [comment]
First step is to setup irq_cpu_mask for known platforms.
Auto-detection can be done as a follow-up.

**Comment by slivne** [comment]
don't we have that done via the perftune scripts ?

If this is done please add a way to disable this as well - if multiple
scylla instances run on the same HW they may conflict

**Comment by bhalevy** [comment]
> don't we have that done via the perftune scripts ?

seastar perftune.py does that today based on the mode (sq/sq-split/mq), but since scylladb/seastar@50b683aef99e5af27f50bf61de6a774258a329d4 the intention is that we don't keep adding new modes, but rather allow setting a specific `irq_cpu_mask`

See also the discussion in https://github.com/scylladb/seastar/pull/939

> If this is done please add a way to disable this as well - if multiple
> scylla instances run on the same HW they may conflict

How would they not conflict with the current mechanism?

Do you mean when running scylla instances on the same machine in dtests?
In this case I don't think we run perftune at all.

**Comment by dorlaor** [comment]
Benny, do you guys plan to address it? It's important for large machines

**Comment by bhalevy** [comment]
> Benny, do you guys plan to address it? It's important for large machines

I apologize, we dropped the ball on this.
@xemul can you please pick it up and prioritize it?

**Comment by vladzcloudius** [comment]
Depends on https://github.com/scylladb/seastar/issues/1170

**Comment by slivne** [comment]
### make it clear no scylla process should set this up - it needs to be external

**Comment by vladzcloudius** [comment]
> To make it clear no scylla process should set this up - it needs to be external

You need to be clearer on this, @slivne. 
Today this (perftune.yaml generation) is configured by `scylla_prepare` process and I don't see a reason why it should change.
Please, clarify why you think this needs to be changed and how?
