### ISSUE TITLE
Add Thrift functional tests in scylla.git

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#9911]
The Thirft API is antiquated, and was removed from Cassandra 4.0 (see https://issues.apache.org/jira/browse/CASSANDRA-11115), but is still supported in Scylla and not even deprecated (it was proposed to deprecate it is issue #3811, but this never materialized). 

Because Scylla developers rarely use Thrift themselves, we are at a real risk of Thrift bit-rotting while developers are improving things for CQL but potentially breaking support for Thrift. The main thing protecting us today from Thrift bit-rot is the **dtest** tests in `thrift_tests.py` which we inherited from Cassandra. These tests are good, but slow (each small functionality test starts a new cluster, although luckily a one-node cluster), and also outside the Scylla tree, so developers aren't likely to run them.

So it would have been nice to move or copy some of the tests from `scylla-dtest/thrift_tests.py` to a functional-test framework in scylla.git just like we have for the CQL, DynamoDB and Redis APIs. I.e., have a run script which runs one Scylla node with the Thrift protocol enabled, and then runs various tests against it. We could also run the same tests against Cassandra 3 to check our compatibility.

One thing I don't know is where to get the Cassandra Thrift driver for Python. Dtest uses some "thrift_bindings" library included as a subdirectory - but I don't know where this came from, or whether this is what real Scylla + Thrift users are using. Ideally, we should try to use the same driver that real users use.

**Comment by nyh** [comment]
See also #1478 about some areas that the current dtests do not cover.

**Comment by mykaul** [comment]
I don't think it is worth pursuing, closing (it's already disabled by default, etc.)

**Comment by nyh** [comment]
@mykaul the consequence of the decision not to do this issue is, for example, https://github.com/scylladb/scylladb/pull/13456. Exactly as I worried, Thrift "bit rotted" - a change introduced in https://github.com/scylladb/scylladb/commit/c642ca9e73714db41c058005f9dfc7ca762492ef broke thrift, but the CI didn't notice - and it was only caught later by some dtest for Thrift that luckily we still have (I have no idea what they cover, but at least they covered this very basic bug).

**Comment by mykaul** [comment]
> @mykaul the consequence of the decision not to do this issue is, for example, #13456. Exactly as I worried, Thrift "bit rotted" - a change introduced in [c642ca9](https://github.com/scylladb/scylladb/commit/c642ca9e73714db41c058005f9dfc7ca762492ef) broke thrift, but the CI didn't notice - and it was only caught later by some dtest for Thrift that luckily we still have (I have no idea what they cover, but at least they covered this very basic bug).

Doesn't that prove that we should work (harder) to deprecate (and remove) Thrift?

**Comment by nyh** [comment]
Deprecating Thrift is not enough, we still need to confirm it doesn't bit-rot a second after we deprecate it. (and we saw now, we do have some partial testing for it in dtest).
Removing Thrift isn't hard work :-) It just needs to be decided. It's mostly a business/product decision - we'll be losing N users. I don't know if N>0, though ;-) If N=0, the business decision is fairly easy.

**Comment by mykaul** [comment]
> Deprecating Thrift is not enough, we still need to confirm it doesn't bit-rot a second after we deprecate it. (and we saw now, we do have some partial testing for it in dtest). Removing Thrift isn't hard work :-) It just needs to be decided. It's mostly a business/product decision - we'll be losing N users. I don't know if N>0, though ;-) If N=0, the business decision is fairly easy.

We deprecate it in https://github.com/scylladb/scylladb/issues/3811 (Scylla 5.2 - unsure why it's marked for 5.3?), and the next step should be code removal, I assume in 5.3 (I could not find the issue for it - I remember seeing one, need to do more searching...)
