### ISSUE TITLE
Virtual table cluster_status does not work in multi dc case

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylladb#9979]
After https://github.com/scylladb/scylla/commit/8dddfab5db2cfdb5eecdb91b5f2e9d0956deb1c1, we have got `system.cluster_status` table that has same thing that is returned by `nodetool status`

It does work perfectly with one datacenter, but if cluster is deployed with multiply datacenters `SELECT * FROM system.cluster_status` returns `unconfigured table cluster_status`

*Installation details*
Scylla version (or git commit hash): 4.6.rc2

**Steps to reproduce**
1. Create cluster with 2 dcs
2. Run query `SELECT * FROM system.cluster_status`

**Comment by tgrabiec** [comment]
The error is weird. "unconfigured table cluster_status" means that there is no such table in the schema. I don't see how multi-DC could affect this, unless the other DC runs an old scylla version and cqlsh connects to the old scylla.

**Comment by tgrabiec** [comment]
\cc @haaawk

**Comment by haaawk** [comment]
> tly with one datacenter, but if cluster is deployed with multiply datacenters `SELECT * FROM system.cluster_status` returns `unconfigured table cluster_status`

Could you confirm @dkropachev that this is not the case please?

**Comment by dkropachev** [comment]
test case is available at https://github.com/scylladb/scylla-dtest/pull/2571/files, called `test_virtual_table_cluster_status_multi_dc`

**Comment by dkropachev** [comment]
> > tly with one datacenter, but if cluster is deployed with multiply datacenters `SELECT * FROM system.cluster_status` returns `unconfigured table cluster_status`
> 
> Could you confirm @dkropachev that this is not the case please?

It is not the case

**Comment by tgrabiec** [comment]
Maybe it's specific to dtest environment

**Comment by jul-stas** [comment]
I run the new dtest on 4.6.rc2 dev, dozens of times, without a single failure.
```
pytest system_tables_test.py::TestClusterStatusTable::test_content_multi_dc_all_nodes_are_up --count=100
```
@dkropachev are you able to reproduce the issue? If not, I'd vote to close it.

**Comment by dkropachev** [comment]
This issue is gone and could be closed
